### ISSUE TITLE
IO_URING as epoll alternative

### ISSUE THREAD

**Issue by gliwka** [netty/netty#10006]
Since Linux 5.1 there’s a new mechanism for high-performance batched asynchronous IO called io_uring. While it was primarily designed for disk io, it also works for network requests: https://blog.cloudflare.com/io_submit-the-epoll-alternative-youve-never-heard-about/

Is this something that would make sense for netty?

**Comment by normanmaurer** [comment]
@gliwka yes! In fact its something I plan to do if its not done as part of GSOC:

https://github.com/netty/netty/wiki/Google-Summer-of-Code-Ideas-2020#add-io_uring-based-transport

**Comment by ijuma** [comment]
Is it happening as part of GSOC still @normanmaurer?

**Comment by normanmaurer** [comment]
@ijuma yes! .... See https://github.com/netty/netty/issues/10142
