### ISSUE TITLE
Termination future listeners can accumulate when resolver groups outlive executors

### ISSUE THREAD

**Issue by jchambers** [netty/netty#10011]
[`AddressResolverGroup`](https://github.com/netty/netty/blob/4.1/resolver/src/main/java/io/netty/resolver/AddressResolverGroup.java) appears to be designed with the expectation that resolver groups will be few in number and will generally have the same lifecycle as the executors that make address resolution requests. In cases where that expectation doesn't hold, though (for example, a case where multiple clients share a common `EventLoopGroup`, but each maintain their own internal `AddressResolverGroup`), listeners attached to executors by `AddressResolverGroup` are never cleared and accumulate, consuming excessive memory.

The issue stems from this executor termination listener: https://github.com/netty/netty/blob/a3e5e4876cf6ddb28e9896867517759fba4146ef/resolver/src/main/java/io/netty/resolver/AddressResolverGroup.java#L72-L80

That's a very reasonable thing to do! My understanding is that the mechanism is in place so links to "dead" executors (which won't produce new address resolution requests) don't pile up and consume memory. The irony is that, if the resolver group closes before the executor, that listener will remain in memory with no way to clear it, having exactly the opposite of the desired effect.

### Expected behavior

After calling `AddressResolverGroup#close()`, all memory and resources associated with the group are freed and can be garbage-collected.

### Actual behavior

A listener remains attached to the executor's termination future, consuming memory even after the resolver group has closed.

### Minimal yet complete reproducer code (or URL to code)

```java
final EventLoopGroup eventLoopGroup = new NioEventLoopGroup(1);

while (true) {
    final RoundRobinDnsAddressResolverGroup resolverGroup = new RoundRobinDnsAddressResolverGroup(
            NioDatagramChannel.class, DefaultDnsServerAddressStreamProvider.INSTANCE);

    resolverGroup.getResolver(eventLoopGroup.next());

    resolverGroup.close();
}
```

…although this should happen with any type of `AddressResolverGroup`.

### Netty version

[4.1.0-beta4](https://github.com/netty/netty/commit/e848066cab19c5b374e44d3e3ceceed03cd42305#diff-4f46bc7344ac420366c5c9094214cf6eR73-R79) through 4.1.45.

**Comment by jchambers** [comment]
Pull request in progress.

**Comment by normanmaurer** [comment]
@jchambers merged... thanks !
