### ISSUE TITLE
EC support in SelfSignedCertificate 

### ISSUE THREAD

**Issue by hyperxpro** [netty/netty#10025]
Should we add support for EC in SelfSignedCertificate? EC is faster and smaller and might be a good choice for the testing environment.

I can do PR for it too.

### Minimal yet complete reproducer code (or URL to code)
https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/util/SelfSignedCertificate.java

### Netty version
4.1.45.Final

**Comment by normanmaurer** [comment]
@hyperxpro sure why not 👍

**Comment by hyperxpro** [comment]
> @hyperxpro sure why not 👍

Should I add a Builder design pattern along with constructor?

**Comment by normanmaurer** [comment]
@hyperxpro not sure if it is really needed. Maybe just add another constructor ?

**Comment by hyperxpro** [comment]
I will do a pull request soon.
