### ISSUE TITLE
Does netty-transport-native-epoll support android?

### ISSUE THREAD

**Issue by LMig2k** [netty/netty#10029]
### Minimal yet complete reproducer code (or URL to code)
```
EventLoopGroup group = new NioEventLoopGroup();
Bootstrap bootstrap = new Bootstrap();
bootstrap.group(group)
		.channel(EpollDomainSocketChannel.class)
		.option(ChannelOption.TCP_NODELAY, true)
		.handler(new ChannelInitializer<SocketChannel>() {
			@Override
			protected void initChannel(SocketChannel ch) {
				ChannelPipeline pipeline = ch.pipeline();
				pipeline.addLast("frameDecoder", new LineBasedFrameDecoder(1000000));
				pipeline.addLast("stringDecoder", new StringDecoder(CharsetUtil.UTF_8));
				pipeline.addLast("resultHandler", new ResultHandler());
				pipeline.addLast("stringEncoder", new LineEncoder(CharsetUtil.UTF_8));
			}
		});

Channel channel = bootstrap.connect(new DomainSocketAddress("XXX")).sync().channel();
```
### Netty version
4.1.43.Final 
<classifier>linux-x86_64</classifier>
### JVM version (e.g. `java -version`)
jdk7+
### OS version (e.g. `uname -a`)
android 9.0

**Comment by normanmaurer** [comment]
No it does not...

**Comment by 4ntoine** [comment]
Will it be as easy as creating "build.gradle" file with cmake/autotools build configuration?

**Comment by 4ntoine** [comment]
JIC trying to do it here: https://github.com/4ntoine/netty/tree/epoll-android

**Comment by 4ntoine** [comment]
now [works](https://github.com/4ntoine/JniBenchmarking/blob/a056d4030fc0d9841c48d62f6209b2ca773a18d5/rpc/src/androidTest/java/com/eyeo/ctu/rpc/AndroidRpcTest.kt#L166) for me, [MR](https://github.com/netty/netty/pull/10881 )
