### ISSUE TITLE
Additional DNS Record decode failed

### ISSUE THREAD

**Issue by kyze8439690** [netty/netty#10034]
### Netty version
4.1.45.Final
### JVM version (e.g. `java -version`)
Java1.8
### OS version (e.g. `uname -a`)
Android 9.0

I am running `dig www.baidu.com` command on Termux(which is a terminal app on android platform), and use `DefaultDnsRecordDecoder` to decode it, and it will fail when name is `.`. Throw exception like below:

```
W/System.err: java.lang.IllegalArgumentException: Invalid input to toASCII: .
W/System.err:     at java.net.IDN.toASCII(IDN.java:110)
W/System.err:     at java.net.IDN.toASCII(IDN.java:133)
W/System.err:     at io.netty.handler.codec.dns.AbstractDnsRecord.<init>(AbstractDnsRecord.java:71)
W/System.err:     at io.netty.handler.codec.dns.DefaultDnsRawRecord.<init>(DefaultDnsRawRecord.java:61)
W/System.err:     at io.netty.handler.codec.dns.DefaultDnsRecordDecoder.decodeRecord(DefaultDnsRecordDecoder.java:105)
W/System.err:     at io.netty.handler.codec.dns.DefaultDnsRecordDecoder.decodeRecord(DefaultDnsRecordDecoder.java:69)
Caused by: Found zero length lable after NamePrep.. line:  0. preContext:  . postContext: 
    at android.icu.impl.IDNA2003.convertToASCII(IDNA2003.java:187)
    at android.icu.impl.IDNA2003.convertIDNToASCII(IDNA2003.java:277)
    at android.icu.text.IDNA.convertIDNToASCII(IDNA.java:654)
    at java.net.IDN.toASCII(IDN.java:108)
	... 11 more
```

And I captured to dns query packet using wireshark, which can decode the additional record properly, showing screenshot like below:

![image](https://user-images.githubusercontent.com/1637169/74602834-f6698780-50e7-11ea-9df7-c9a02eef2e6f.png)

I am not an expert to dns, I hope I have provided the necessary information. 
Thanks.

**Comment by normanmaurer** [comment]
@kyze8439690 this looks like an android bug as in OpenJDK 8 it is correctly handled:

https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/jdk/src/share/classes/java/net/IDN.java#L116
https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/jdk/src/share/classes/java/net/IDN.java#L442
https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/jdk/src/share/classes/java/net/IDN.java#L450

That said I think we can add a workaround for Android if its not fixed there... WDYT ?

**Comment by normanmaurer** [comment]
Yep this is a bug in android 9:

https://android.googlesource.com/platform/libcore/+/refs/tags/android-9.0.0_r53/ojluni/src/main/java/java/net/IDN.java#109

But was fixed in android 10:

https://android.googlesource.com/platform/libcore/+/refs/tags/android-10.0.0_r29/ojluni/src/main/java/java/net/IDN.java#109

**Comment by normanmaurer** [comment]
For a workaround see https://github.com/netty/netty/pull/10039

**Comment by kyze8439690** [comment]
Thank you so much, I will look into it
