### ISSUE TITLE
OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by ali-bagheri** [netty/netty#10042]
### Netty version
4.1.44

### JVM version
10

### OS version
Ubuntu 18

Hi, I use netty for chat server. after 8 to 9 hours work, my server crash.

Received message:

io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor forceClose
WARNING: Failed to register an accepted channel: [FAILED toString()]
java.lang.OutOfMemoryError: Java heap space

**Comment by amizurov** [comment]
@ali-bagheri , Hi could you please provide more details, currently I'm only see that server cannot accepts new connection because not enough memory.

**Comment by ali-bagheri** [comment]
Tanks. I am sorry, I have not time for that. I must migrate to another library/framework. :(
