### ISSUE TITLE
Client side connections share source port even when  SO_REUSEPORT is not configured

### ISSUE THREAD

**Issue by moderakh** [netty/netty#10052]
### Expected behavior
Client side connections shouldn't share the same source port when `SO_REUSEPORT` is not explicitly set.

### Actual behavior

We have a client side TCP based protocol implemented using netty 4.1.45.Final.
running the application on "Linux 5.0.0-1032-azure #34-Ubuntu SMP Mon Feb 10 19:37:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux"

We are not setting `SO_REUSEPORT` explicitly. However, when running application there are multiple connections with the same source port.

```bash
xyz:~$ netstat -nap | grep java | grep -v "104.214.18.14:443" | grep ESTABLISHED | grep 65242
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp6       0      0 10.0.6.9:65242          104.214.18.16:14058     ESTABLISHED 6172/java           
tcp6       0      0 10.0.6.9:65242          104.214.18.16:14331     ESTABLISHED 6172/java           
tcp6       0      0 10.0.6.9:65242          104.214.18.16:14037     ESTABLISHED 6172/java 
```
As we are not setting `SO_REUSEPORT` why some connections share the same source ports are shared?

### Steps to reproduce
I explicitly reduced the empirical port range to study port reuse:

```bash
sysctl net.ipv4.ip_local_port_range 
net.ipv4.ip_local_port_range = 65000	65500
```

### Minimal yet complete reproducer code (or URL to code)
This is not complete code, but it is how we configure the Bootstrap channel:

```java
final Bootstrap bootstrap = new Bootstrap()
  .channel(NioSocketChannel.class)
  .group(group)
  .option(ChannelOption.ALLOCATOR, config.allocator())
  .option(ChannelOption.AUTO_READ, true)
  .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, config.connectionTimeoutInMillis())
  .option(ChannelOption.RCVBUF_ALLOCATOR, receiveBufferAllocator)
  .option(ChannelOption.SO_KEEPALIVE, true)
  .remoteAddress(physicalAddress.getHost(), physicalAddress.getPort());
```

https://github.com/Azure/azure-sdk-for-java/blob/feature/cosmos/v4/sdk/cosmos/azure-cosmos/src/main/java/com/azure/cosmos/implementation/directconnectivity/rntbd/RntbdServiceEndpoint.java#L76-L84

### Netty version
netty 4.1.45.Final

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

### OS version (e.g. `uname -a`)
Linux xyz 5.0.0-1032-azure #34-Ubuntu SMP Mon Feb 10 19:37:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@moderakh netty itself does not do anything here if you dont specify it. This means whatever you see here is the default behaviour of the OS / Kernel you are running.

**Comment by moderakh** [comment]
@normanmaurer I tested this on vanilla Ubuntu as well (without azure customization):
Linux parallels-Parallels-Virtual-Platform 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
same behaviour, source port is reused without explicitly setting SO_REUSEPORT..

I don't find any documentation on this behaviour to be default for Ubuntu. Any idea which Linux distro doesn't have this as the default behaviour?

I need to test SO_REUSEPORT and I need a baseline Linux distro where I can see the difference with and without this option how it operates. Could you please suggest a Linux distro that you know it doesn't have this as the default behaviour?
