### ISSUE TITLE
How to make sure Netty Zero-Copy is working?

### ISSUE THREAD

**Issue by hyperxpro** [netty/netty#10054]
I am working on a TCP/UDP Load Balancer and I want zero-copy support for it because the Load Balancer will receive data and just forward it to the backend servers. 

I want to make sure Netty is using its zero-copy feature but not sure how to check it. Is there any way?

### Netty version
4.1.45.Final

### JVM version (e.g. `java -version`)
11.0.5

### OS version (e.g. `uname -a`)
CentOS 8

**Comment by zhenjunMa** [comment]
In my opinion, `zero-copy` is only used in file transfer.
i think you just need a proxy that send whatever it received,  you can get `ByteBuf` by the client channel and just write this buf to server.

**Comment by hyperxpro** [comment]
> In my opinion, `zero-copy` is only used in file transfer.
> i think you just need a proxy that send whatever it received, you can get `ByteBuf` by the client channel and just write this buf to server.

File Transfer? How?

**Comment by hyperxpro** [comment]
Aren't Zero-Copy for Data Packets?

**Comment by hyperxpro** [comment]
I am targeting 'Kernel Bypass' with Zero-Copy of Netty.

**Comment by zhenjunMa** [comment]
yes, i know your case, but i don't think you can achieve the goal by netty 
or i just don't know this feature in netty.

**Comment by hyperxpro** [comment]
@normanmaurer You've any idea about Kernel Bypass Zero-Copy in Netty?

**Comment by normanmaurer** [comment]
We dont support user-space tcp stack in netty. We will support io_uring tho in the future for sure.

**Comment by hyperxpro** [comment]
> We dont support user-space tcp stack in netty. We will support io_uring tho in the future for sure.

Cool! So io_uring coming in Netty 5?
