### ISSUE TITLE
The App uses an insecure Random Number Generator.

### ISSUE THREAD

**Issue by karthik-dusk** [netty/netty#10083]
### Expected behavior

MobSF should not report any issue saying that, these below classes are using insecure-random-number-generator. 

io\netty\handler\ssl\util\ThreadLocalInsecureRandom.java
io\netty\util\internal\PlatformDependent.java
io\netty\util\internal\ThreadLocalRandom.java

### Actual behavior
MobSF is reporting any issue saying that, these below classes are using insecure-random-number-generator. 

io\netty\handler\ssl\util\ThreadLocalInsecureRandom.java
io\netty\util\internal\PlatformDependent.java
io\netty\util\internal\ThreadLocalRandom.java

### Steps to reproduce
1. include io.netty into any of your android project
2. build an apk
3. Scan in MobSF

### Minimal yet complete reproducer code (or URL to code)

io\netty\handler\ssl\util\ThreadLocalInsecureRandom.java
io\netty\util\internal\PlatformDependent.java
io\netty\util\internal\ThreadLocalRandom.java

### Netty version
Latest 

### JVM version (e.g. `java -version`)
Java 8

### OS version (e.g. `uname -a`)
Android - any version 

![image](https://user-images.githubusercontent.com/5618488/75865149-1f4c8500-5e29-11ea-93d6-1f928bf6adc6.png)

**Comment by slandelle** [comment]
That's a MobSF issue that reports a false positive, not a Netty one.

**Comment by karthik-dusk** [comment]
Aah ..! This MobSF is freaking me out. 
Thank you Landelle.

**Comment by karthik-dusk** [comment]
I want to repoen this issue. I checked the source code of these class, Netty is using Random (Insecure) from the package "import java.util.Random;"

**Comment by slandelle** [comment]
Those classes are not used for cryptography so there's no need to use a SecureRandom and pay the extra performance penalty. It's used for example for generating self signed certificates, multipart delimiter and WebSocket challenges.

You should reach out to MobSF so they whitelist those classes. It's a MobSF issue.

**Comment by karthik-dusk** [comment]
Hi @slandelle , this is just for my understanding, 
Is this package "import io.netty.handler.ssl.SslContext" and the above false positive(above 3 classed) are anyway related? 

Please help me understand.

**Comment by hyperxpro** [comment]
> Hi @slandelle , this is just for my understanding,
> Is this package "import io.netty.handler.ssl.SslContext" and the above false positive(above 3 classed) are anyway related?
> 
> Please help me understand.

No, they are not.
