### ISSUE TITLE
GSoC 2020 Proposal

### ISSUE THREAD

**Issue by rustberry** [netty/netty#10088]
Hello everyone! This is Zejin Xu from Beijing China, finishing 4th year at China University of Mining and Technology as an undergraduate.

I read the book *Netty in Action* last year and learned to utilize Netty as the underlying transport for my [tiny RPC framework](https://github.com/rustberry/berry-rpc), which helped me get my internship. It is exciting to see Netty in this year’s GSoC. When I looked at your project list, I am thrilled by the idea that I may contribute to Netty too!

I’m interested in the second idea from the project list: Regression test suite. I did a lot of CI work in Jenkins as I started my internship. I like the idea of adding performance regression test as part of PR validations.

As of now, I have cloned locally and browsed the code base of Netty, but found little document on project’s CI process, except this one on [Netty’s microbechmarks](https://netty.io/wiki/microbenchmarks.html). I’d appreciate it if anyone can guide me more on this task.

I browsed the possible tools listed in [Related Resources](https://github.com/netty/netty/wiki/Google-Summer-of-Code-Ideas-2020#related-resources-1), and I would also propose to use the native Java tool [Metrics](https://github.com/dropwizard/metrics), which is more lively developed and has a large community. It could provide with us finer-grained control over what kind of metrics do we want with various features like [histograms](https://metrics.dropwizard.io/4.1.2/manual/core.html#histograms). Also, I think it may make it easier to generate trend graphs.

I’m new to open source development, please correct me where I am wrong ;) Looking forward to your reply!

**Comment by normanmaurer** [comment]
Sorry for the late response... 

At the moment we use a self-hosted Jenkins installation that uses docker to run the jobs (see the docker files). For the task we basically look just for a way to run a set of benchmarks via CI and somehow build up report about values that changed since the last run and which changes were applied. This for example would include numbers like allocations, GC CPU time, throughput etc.

**Comment by rustberry** [comment]
Hi Norman, never mind, thanks for the information! These days I have gone through and roughly understood the Docker part of CI process. Next I will try to come up with runnable demos of some of the regression tests.

**Comment by normanmaurer** [comment]
Please share the proposal via google docs once you have it written so we can have a look.

**Comment by rustberry** [comment]
Thanks for the reminder, I'm working on it.

**Comment by rustberry** [comment]
Hi, this is my draft of GSoC proposal, sorry to have finished it just before DDL... [Link to proposal - Add Regression Testsuite to Netty](https://docs.google.com/document/d/10hd2eGR1T3IFeJSD18L6_t6x41StI966ojPLM-DD5bM/edit?usp=sharing)

Please leave your comments, your feedback is valuable to me.

Thanks.

**Comment by normanmaurer** [comment]
Let's close this... the students were selected for GSOC
