### ISSUE TITLE
Question about HashedWheelTimer in netty

### ISSUE THREAD

**Issue by seedeed** [netty/netty#10099]
HashedWheelTimer in netty is an awesome timer optimized for approximated I/O timeout scheduling. But in our business project, I had seen a lot of use cases about HashedWheelTimer as below: 
```java
hashedWheelTimer.newTimeout(timeout -> {
	businessExecutor().execute(() -> {
		//business code here
	});
}, 1, TimeUnit.SECONDS);
```
In order not to block the HashedWheelTimer's worker thread, we must make all our real business code run in a business Executor (an instance of java.util.concurrent.Executor) but not in the implemention of io.netty.util.TimerTask itself. So I think how about introducing a parameter representing an Executor in which a TimerTask runs for our HashedWheelTimer's constructor?

**Comment by normanmaurer** [comment]
@seedeed honestly I think if the user wants to do this it should be up to the user to just do it by him / herself.
