### ISSUE TITLE
MD5 is a weak hash known to have hash collisions - Reported by MobSF

### ISSUE THREAD

**Issue by karthik-dusk** [netty/netty#10090]
### Expected behavior
MobSF should not report this issue that, "MD5 is a weak hash known to have hash collisions."

### Actual behavior
MobSF is reporting this issue that, "MD5 is a weak hash known to have hash collisions."
![Capture](https://user-images.githubusercontent.com/5618488/76063009-d0c7f380-5fac-11ea-88c8-24f2e02d94c2.PNG)

### Steps to reproduce
Include Netty library in any android project & Scan the apk with MobSF

### Minimal yet complete reproducer code (or URL to code)
-NA-

### Netty version
4.2

### JVM version (e.g. `java -version`)
8.0

### OS version (e.g. `uname -a`)
Android 4+

**Comment by slandelle** [comment]
False positive again. WebSocket spec requires MD5 usage here. Not used for crypto.

**Comment by karthik-dusk** [comment]
Thank you for the response Landelle.

**Comment by karthik-dusk** [comment]
Hi @slandelle , 
![md5](https://user-images.githubusercontent.com/5618488/76981196-3da19d00-6960-11ea-97b6-cd309effa581.png)
How is the variable named MD5 linked with actual MD5 hash? 

Thanks for your time @slandelle .
