### ISSUE TITLE
WebSocketClientHandshaker13 header key "Host" doesn't take custom header

### ISSUE THREAD

**Issue by dennylee** [netty/netty#10101]
### Information
I'm trying to do a load test using Gatling, which uses netty to make the request.  The load test is focused on websockets against AWS cloudfront.  So, the websocket will go through cloudfront then forwards to the actual host sitting behind cloudfront.  We've been told that we need to pass header key "Host" and the actual hostname as the value.  However, WebSocketClientHandshaker13 overwrites the header key "Host" with the parsed websocket url (which in my example is the cloudfront url).  So, even if I pass a custom header with the "Host" defined, it wont take the custom header value.

My Gatling set up is as follows,
```
val loadTestWsHttp = http
    .acceptEncodingHeader("gzip, deflate") 
    .header("host", <hosting server>)
    .wsBaseUrl("wss://<cloudfront>")
```

In WebSocketClientHandshaker13.java
```
        if (customHeaders != null) {
            headers.add(customHeaders);
        }

        headers.set(HttpHeaderNames.UPGRADE, HttpHeaderValues.WEBSOCKET)
               .set(HttpHeaderNames.CONNECTION, HttpHeaderValues.UPGRADE)
               .set(HttpHeaderNames.SEC_WEBSOCKET_KEY, key)
               .set(HttpHeaderNames.HOST, websocketHostValue(wsURL));  <---- This stomps the value from customHeaders
```

### Expected behavior

I should be able to establish the websocket request with cloudfront and eventually be able to send messages to the hosting server that will be forwarded by cloudfront.

### Actual behavior

`Invalid handshake response getStatus: 502 Bad Gateway`

### Steps to reproduce

Have a running server sitting behind cloudfront which supports websocket
Setup cloudfront to enable websocket and forward messages to the server noted above
Create Gatling scripts to send a websocket message
Gatling script will fail with 502 Bad Gateway

### Netty version

4.1.42.Final

### JVM version (e.g. `java -version`)

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

### OS version (e.g. `uname -a`)

Windows

**Comment by dennylee** [comment]
So my question is.
Is there a way to inject my own websocket client handshaker which will contain a fix.  Or am I doing something wrong here.

**Comment by normanmaurer** [comment]
@dennylee sounds like a bug... I think we should only set the `Host` header if it is not already set.
