### ISSUE TITLE
GSoC 2020 Proposal - Add io_uring based transposrt

### ISSUE THREAD

**Issue by Marti2203** [netty/netty#10116]
Hello, I am a first year student from the Technical University of Eindhoven and I saw this task. I have seen the capabilties of Netty and the things it can do and I am interested in finally using the documentation I have been reading for Linux in my spare time for something useful. 

I have a lot experience with java and working with C and have used Interoperability solutions (JNI, P/Invoke)  for some small programs I have written down. I would prepare a little more if accepted before the coding starts so I can feel more at ease with the project and task. I think that I will fit into the required time and do all things - documentation, tests, analysis, development and communication with my mentor.

I would be happy to answer any questions or prepare for any requirements you have.

**Comment by ninja-** [comment]
I am looking forward to it :)

**Comment by Marti2203** [comment]
Quick question- What should I submit as a pdf of the proposal?

**Comment by normanmaurer** [comment]
@Marti2203 You should out-line a "milestone" plan with different sub-tasks and explain what each of the sub-tasks include and how long you expect it to take.  You may want to consider using either google docs or a PR with markdown so we can discuss directly on the proposal itself.

**Comment by Marti2203** [comment]
Okay, perfect. I will prepare one in the next day or two as I would like to invest some time of the internals of Netty.

**Comment by Marti2203** [comment]
Hello, this is my [first draft in Google Notes](https://docs.google.com/document/d/1hHSfuveVRMenTaAC7whln_qZ1eytwR7AWb7NyxTvYrs/edit?usp=sharing)

**Comment by hyperxpro** [comment]
@Marti2203 Will io_uring be dependent on another C library to make its API calls?

**Comment by Marti2203** [comment]
I know of liburing, I think that may be the only such dependency, but it depends on the maintainers of the project - I can try to go without it and directly communicate with the kernel.

**Comment by normanmaurer** [comment]
@Marti2203 I strongly prefer to NOT use liburing. We should just use the kernel API directly.

**Comment by Marti2203** [comment]
Okay, not a problem for me.

**Comment by hyperxpro** [comment]
I also have the same opinion. We're going to invest lots of time on io_uring and using third-party dependency might not seem much beneficial apart from the ease in development.

Coming back to performance, do we have plans for zero-copy or something similar to reduce copies? #10054

**Comment by Marti2203** [comment]
Well, the goal of io_uring is to have almost no copies that are in kernel space and user space - have a memory mapped area where the application and the kernel write data. I will focus on making as few copies as possible, if given the opportunity to work on the proposal.

**Comment by hyperxpro** [comment]
If you've space for testing people, count me in. I'll happy to work on performance and benchmark side.

**Comment by normanmaurer** [comment]
Let's close this... the students were selected for GSOC
