### ISSUE TITLE
Multiple call to exceptionCaught since 4.1.23 in case of Ssl Handshake Failure

### ISSUE THREAD

**Issue by asanglard** [netty/netty#10119]
### Expected behavior
Before release 4.1.23, there was only ONE call to exceptionCaught method when an ssl handshake failure occurs

### Actual behavior
Since release 4.1.23, exceptionCaught method is called twice. Looking in the stacktrace:
- it is called a first time, and it is related to the fireChannelRead method of the SslHandler,
- it is called a second time, and it is related to the fireChannelInactive method of the SslHandler,

### Steps to reproduce
Try to connect to netty server with a client that does not trust the server CA certificate.
The client will close the session with an Alert - Certificate Unknown error.
Netty will call twice the exceptionCaught method.

### Minimal yet complete reproducer code (or URL to code)
Clone this repository https://github.com/asanglard/dummyNettyServer
and connect with an SSL client to the server which is running on port 8282. You may use your web browser (https://127.0.0.1:8282/)

Dummy exceptionCaught will be called twice for the same channel.
error on client channel 69a6a755 : javax.net.ssl.SSLException: Received fatal alert: certificate_unknown - exception class: io.netty.handler.codec.DecoderException
error on client channel 69a6a755 : javax.net.ssl.SSLException: Received fatal alert: certificate_unknown - exception class: io.netty.handler.codec.DecoderException

### Netty version
I tested Netty 4.1.23 and 4.1.48 (last version). The behaviour is the same with these two versions.

### JVM version (e.g. `java -version`)
java version "1.8.0_152-ea"

### OS version (e.g. `uname -a`)
Mac OS Catalina 19.3.0 Darwin Kernel Version 19.3.0

**Comment by normanmaurer** [comment]
@asanglard the reason for this is that when we close the channel we try to drain to call `unwrap` one last time to ensure we completely drain every alert that is left in the engine. So while it is not "pretty" I am note sure its a big deal to report the exception two times in some cases. For example if you use the `OPENSSL` provider there will be only one exception.

**Comment by asanglard** [comment]
@normanmaurer You are right for `OPENSSL` provider, there is only one exception raised.

This behaviour with `JDK` provider may be a "big deal" in case that the application (that use netty) triggers business logic when exceptionCaught method is called. In case that this business logic is not idempotent, it may affect the service.

In our case, we track, thanks to the exceptionCaught  method, unsuccessful handshake with a counter.  With this change (two calls), our counter is therefore incremented twice. This is a basic example, but I imagine that it may affect other application that also triggers any business logic.

To my point of view, it is also a bit weird to have a difference of behaviour between `JDK` and `OPENSSL` for such situation.

In case that you don't fix this behaviour, people must ensure that the business logic executed behind this method is idempotent.

**Comment by normanmaurer** [comment]
@asanglard got it... Let me see what I can do.

**Comment by normanmaurer** [comment]
@asanglard PTAL https://github.com/netty/netty/pull/10134

**Comment by normanmaurer** [comment]
This was fixed
