### ISSUE TITLE
GsoC Proposal

### ISSUE THREAD

**Issue by lukago** [netty/netty#10126]
Hi! I'd like to take part in Netty Project during GSoC. 
I have strong JVM background, some C and linux networking too so I think i can fit.
Here is my proposal for io_uring but other submitted topics with metrics are fine for me as well.
[GsoC proposal draft on Google Docs](https://docs.google.com/document/d/1TnW2Ar2AOXZQ7G2U3mQ6rvouJkymJZwxXfdcpZ7ZfRc/edit?usp=sharing)

Let me know what do you think about it.

**Comment by hyperxpro** [comment]
Isn't it better to separate Epoll and IO_URING?

**Comment by johnou** [comment]
@normanmaurer looks like there are three different GsoC proposals for io_uring :)

**Comment by hyperxpro** [comment]
> @normanmaurer looks like there are three different GsoC proposals for io_uring :)
> 
> #10116
> #10126
> #10131

That's good to be honest, at one time when there were no proposals, I actually thought @normanmaurer has to do all heavy lifting for work again to add io_uring.

**Comment by lukago** [comment]
@hyperxpro yep its probably better approach, i tought at first we can do somethink like epoll will just try to use io_uring if thats posibble, but making it separate gives us more flexibility with this. 

@normanmaurer i updated docs a bit accoring to your comments

**Comment by hyperxpro** [comment]
Remove Epoll out of the picture completely.

**Comment by normanmaurer** [comment]
@lukago I will have a look... that said I would first keep epoll and concentrate on the rest. Once this is sorted we can still check if we also should remove the rest of epoll.

**Comment by lukago** [comment]
Unfortunately I will not participate
