### ISSUE TITLE
ReplayingDecoderByteBuf#copy returns copy of underlying buffer, losing replay-ability

### ISSUE THREAD

**Issue by eager** [netty/netty#10122]
### Expected behavior

`ReplayingDecoderByteBuf#copy(int index, int length)` should maintain the special replay-ability of the buffer, or the docs should note that the copy does not retain the replay behavior.

### Actual behavior

If an in-bounds `index + length` is specified, the underlying buffer is copied and returned, leading to surprising errors in replaying decoders that use the copy.

### Minimal yet complete reproducer code (or URL to code)

```java
class MyDecoder extends ReplayingDecoder<?> {

    final ExecutorService executor = new ThreadPoolExecutor(4,
                                                            10,
                                                            60,
                                                            TimeUnit.SECONDS,
                                                            new ArrayBlockingQueue<>(1000));
    @Override
    protected final void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) throws Exception {
    
        final ByteBuf copy = in.copy(in.readerIndex(), in.writerIndex() - in.readerIndex();
        
        executor.execute(() -> {
                        
            try {
                decodeCommand(ctx.channel(), copy, data);
            } catch (Exception e) {
                log.error("Unable to decode data in separate thread" + LogHelper.toString(data), e);
            } finally {
                copy.release();
            }
        });
    }
}
```

### Netty version

4.1.48.Final

**Comment by carryxyh** [comment]
I believe this is a wrong use. We must throw the exception in `decode`, otherwise the `decoder` will not work properly...

**Comment by normanmaurer** [comment]
@eager I think what it does is correct... `copy` will just return a copy of the `ByteBuf` and it is not guaranteed that the buffer type is the same as before. This is generally true for `ByteBuf`.

**Comment by eager** [comment]
> we must throw the exception in `decode`

@carryxyh that make sense. 

> I think what it does is correct... copy will just return a copy of the ByteBuf and it is not guaranteed that the buffer type is the same as before.

@normanmaurer that also makes sense. Since `ReplayingDecoderByteBuf` has its special behavior, does it make sense to update the docs to note that the behavior won’t be present in the copy?

**Comment by normanmaurer** [comment]
@eager I am happy to review any PR to improve docs etc. Please submit a PR if you think we should clarify.
