### ISSUE TITLE
GSoC 2020 Proposal - Implement event loop telemetry

### ISSUE THREAD

**Issue by dev-ritik** [netty/netty#10139]
Hello Everyone,

I'm a third-year undergrad at Indian Institute of Technology, Roorkee. I successfully participated in GSoC last year. This year I am looking forward to contributing to Netty. 

[Here](https://docs.google.com/document/d/1Z4qJS5GfII1Z9UbTfJKgIn9uEUKHq4rJ9-jYDBLG6l0/edit?usp=sharing) is my proposal for the topic, **Implement event loop telemetry**. I have added all other details in it.

I am looking forward to working with you.

**Comment by hyperxpro** [comment]
Seems good.

How are you planning to implement those metrics counter into Netty? During Server bootstrapping or some different approach?

**Comment by franz1981** [comment]
@dev-ritik Consider https://github.com/netty/netty/pull/9080 in the mix, although very basic :)

**Comment by dev-ritik** [comment]
I think this could be done using some interfaces. Custom implementations, as required, can be added to various EventLoops and EventLoopGroups or their superclasses. Users can decide while Server bootstrapping if they want to observe those counters or not.

**Comment by normanmaurer** [comment]
Let's close this... the students were selected for GSOC
