### ISSUE TITLE
DoH Support

### ISSUE THREAD

**Issue by hyperxpro** [netty/netty#10138]
I am planning to add DoH Support. Should I use [dnsjava](https://github.com/dnsjava/dnsjava) DNS library or Netty DNS classes?

P.S- dnsjava seems more matured and stable.

**Comment by normanmaurer** [comment]
Nettys implementation is fully async so I would use it...

**Comment by hyperxpro** [comment]
I was actually talking about #9091. I want to do a pull request to DoH support. Are Netty DNS classes stable enough? I saw `Unstable` annotation on DNS classes.

**Comment by normanmaurer** [comment]
@hyperxpro yes
