### ISSUE TITLE
GSoC 2020

### ISSUE THREAD

**Issue by grishasht** [netty/netty#10135]
As for now, I’m a student of Kyiv Polytechnical Institute, 4 course, Computer science. 
I started my career from successfully passing the Java external course of a big European company.
At the moment I’m a Java software engineer at another big European company with 7 months of commercial experience. Besides a job I’m engaged in studying, keeping my best and developing new skills.

Well, so what can I be useful for?
As I said before, I have some commercial experience with writing maintainable code and refactoring existing, implementing features, writing tests, working with Agile methodology. Also, I have quite a good level of English and I guess it’s enough for communicating with a foreign team.  
So I can be like any other Junior developer on the project: take a task, investigate the problem, resolve it, write unit tests, provide dev testing and write documentation.

So what benefit will I get?
First of all, a lot of useful experience. I’ll get a better technical background which is so mandatory for me as for the Junior developer. 
Secondly, the contribution to opensource. I feel amazing when I deliver products to customers, see its value and get positive feedback for this. And thoughts of contribution to the project, which will use many engineers, give me high motivation and much desire to work with.

**Comment by normanmaurer** [comment]
You will need to write a proposal for the specific task you want to pick up for GSOC.

**Comment by grishasht** [comment]
> You will need to write a proposal for the specific task you want to pick up for GSOC.

Great! Will be done

**Comment by normanmaurer** [comment]
Please share the proposal up-front so we can provide some feedback and help you...

**Comment by grishasht** [comment]
> Please share the proposal up-front so we can provide some feedback and help you...

Sorry for the late response

So, this proposal must be mine? Or can I choose some issues from the list?

**Comment by normanmaurer** [comment]
@grishasht sorry but its too late now... The submission deadline for GSOC is over.
