### ISSUE TITLE
GSoC 2020 Proposal

### ISSUE THREAD

**Issue by KhaledEmaraDev** [netty/netty#10131]
Hi,

I'm Khaled from Egypt. I'm interested in participating this year in GSoC. I have been trying to reach you for quite sometime, but I though the project was dead. No one answers the mailing list, gitter, nor the IRC room.

I'm keen on the `io_uring` transport project as I'm looking to hone my kernel skills through userland projects. I also like to work with networks.

If you'd be kind enough to have a look at my [proposal](https://docs.google.com/document/d/1XT7JvsuFgX_xvU9nNTd7ksIe70yjaLSP-LvGc6NeRAo/edit?usp=sharing) and give me pointers, I would be grateful.

Looking forward to working with you.

**Comment by normanmaurer** [comment]
@KhaledEmaraDev can you give me the rights to put comments on the doc ?

**Comment by KhaledEmaraDev** [comment]
@normanmaurer Yeah sorry. Though I already enabled comments for sharing. You can do it now.

**Comment by normanmaurer** [comment]
Let's close this... the students were selected for GSOC
