### ISSUE TITLE
Can't get somaxconn

### ISSUE THREAD

**Issue by yechao4j** [netty/netty#10137]
When i start Springcloud gateway in 'Alibaba Cloud Elastic Compute Service', i found
```
State       Recv-Q Send-Q   Local Address:Port 
LISTEN      0        0                    *:8080 
```
Send-Q is 0, but `somaxconn` is 262144
```
[abc@iZt4nc4r ~]$ cat /proc/sys/net/core/somaxconn
262144
```
Is anything problem with server?
netty version is 4.1.38.Final, reactor-netty 0.8.10, core 3.2.11

**Comment by yechao4j** [comment]
And another question, how to enable Netty debug log level?

**Comment by johnou** [comment]
somaxconn has nothing to do with the send and receive queue of your socket, I suggest reading the manual again? you can enable debug log level by setting DEBUG level for the package io.netty

**Comment by yechao4j** [comment]
@johnou  if Send-Q is 0, in my environment the Ngnix in front of gateway will connect timeout, error log below
```
connect() failed (110: Connection timed out) while connecting to upstream
```
If i increase somaxconn to 128, it will be ok. Why you say it is nothing to do with the send queue?
And where's the manual, i need to check it.
Thanks.

**Comment by johnou** [comment]
this is a bug tracker, not a support forum, use your preferred search engine to look up what those terms mean. If you need to change the so_backlog in your Netty server look up the option ChannelOption.SO_BACKLOG.

**Comment by yechao4j** [comment]
OK，i understand.  Thanks
