### ISSUE TITLE
GSoC Idea Proposal 2020 -  Implement event loop telemetry

### ISSUE THREAD

**Issue by shashank-shark** [netty/netty#10140]
# GSoC Idea Proposal 2020 -  *Implement event loop telemetry*

Hello community I am Shashank J, a final year student pursuing the course of Computer Science and Engineering at Sai Vidya Institute of Technology (VTU) -  Bangalore and a follower of Pieter Hintjens.

I have strong knowledge on Java and good knowledge about AMQP, Asynchronous messaging / networking libraries (**ZeroMQ**), Zero-Copy, Message Queuing , different types of messaging patterns like PUB-SUB, PUSH-PULL, REQ-RES, PAIR, Polling, Majordomo, Suicidal Snail,B-STAR, TItanic patterns etc. I am also familiar with JMH, JMeter and JProfiler. I started using netty few months back and have built some IoT releated projects (Fog Computing) which requires communication with various level of devices. I would be really interested to work with the community and provide long term support to this project.

**Here s my proposal for GSoC 2020 :** [Link to Proposal - Implement event loop telemetry](https://docs.google.com/document/d/1iVK1V6rzQxCnKY14z4LWUdD68G4bDiR9_P0jiAePc9Y/edit?usp=sharing)

I am thinking to use messaging (internal and external) mechanisms  to achieve the metrics counter effect. 
More details are discussed in the provided google doc.

I would really love your feedback on this proposal and any suggestions or add-ons for this proposal are always open.

**Comment by hyperxpro** [comment]
JVM Communication is a nice way but much data can it extract from Netty?

**Comment by shashank-shark** [comment]
> JVM Communication is a nice way but much data can it extract from Netty?

Yes, with JVM IPCs using a memory mapped file we can retrieve about 10~14 million messages per second and with average latency in less than 100 nano seconds.

I am planning to benchmark on **raw** bytes as most of the time is spent in serializing and deserilizing the message. I believe benchmarking on the messages after serializing  / deserilizing could provide extra overhead which will give us an average latency in few milliseconds.

**Comment by shashank-shark** [comment]
On different methods like **RMI**, **TCP/IP** communication without any persistence I found that inter process communication (JVMs) with a memory mapped file performs significantly faster and is more memory efficient. @hyperxpro What is your idea on this ?

**Comment by franz1981** [comment]
@shashank-shark Aeron Is currently using the IPC strategy (https://github.com/real-logic/aeron/wiki/Monitoring-and-Debugging#counters) to expose counters, but requires Unsafe in order to perform atomic operations over the underline bytes of MappesByteBuffer.

**Comment by hyperxpro** [comment]
> > JVM Communication is a nice way but much data can it extract from Netty?
> 
> Yes, with JVM IPCs using a memory mapped file we can retrieve about 10~14 million messages per second and with average latency in less than 100 nano seconds.
> 
> I am planning to benchmark on **raw** bytes/messages first and then move to benchmark the messages after their serialization / deserilization and this approach would also give us the average serialization/deserilization latency as well.

Did you benchmark these numbers?

**Comment by franz1981** [comment]
@hyperxpro i won't focus on the perf of such mechanisms (others has already demonstrated the effectiveness of them, see my previous comment about it) but on which kind of benefits and cost it brings if compared to other mechanisms.

**Comment by shashank-shark** [comment]
@franz1981 yes the points that you've listed are crucial when dealing with IPCs and multithreaded environments. Using **Unsafe** is the best way to modify an object in memory with less cost.

Adding to the first point, here I would try to use a different atomic counter for different events and let the thread allocated for this event in a handler update the counter atomically(1) using Unsafe and the counters offset address. With this I think I would achieve event level versioning.

For thread level versioning I am currently working on the data structure part which maps threadId to an atomic incrementer as threadId would remain same and unchanged during the life cycle of the thread. But still once the thread is terminated, the threadId may be reused by some other newly created thread. Any suggestions ?

Adding to the second point, I am thinking of implementing a shared queue and a broker which provides persistence (of 1 second) to the messages that are sent by the producer running on target netty application. The remote JVM (not part of netty application) which is connected to another end of this queue gets these updates every 1 second and to check the liveliness of the process or to detect a crash I am thinking to implement heartbeating between the broker and the process. Any suggestions ?

**Comment by franz1981** [comment]
@shashank-shark The problem I see with this approach is that in order to work (without considering the new VarHandle methods on next jdk that will introduce it) is that it needs Unsafe to work fine: it means Android and IBM platfoem won't work (maybe :P). Netty features IMHO should aim to be available for most possible platforms (see how PlatformDependent works) and hence an approach that work just with Unsafe needs to be careful evaluated: unless you are able to make it work across different JVM impls without relying on it I am not sure the IPC approach is feasible...but I am happy to be wrong :)

**Comment by shashank-shark** [comment]
Yes using Unsafe is not much fruitful as Unsafe is already deprecated in JDK 11 and is available in `jdk.unsupported` module and even I doubt that Unsafe won't be supported in future by many JDK vendors out there.
The solution I was able to think of was to determine the JDK version at runtime and then move on to implement the counters. Here are the versions with the plan of implementation.

| JDK Version  | Plan  |
|---|---|
| JDK 7  | To use **JNI** for counters implementation.  |
|  JDK 8  |  To see if Unsafe is supported by the vendor, if **yes** then use Unsafe else use **JNI**. |
| JDK 9  | To use Variable Handlers (*VarHandle*) to implement counters.  |
| JDK 10 and above  | To use Variable Handlers (*VarHandle*) to implement counters.  |

Let me try out using IPCs, if this solution is not feasible then I am planning to use message queues with shared memory (which I described in my previous comment) and let you know.

By the way, can I confirm that use of JNI is allowed to achieve this target and are there any additions that I can make to the above table ?

**Comment by shashank-shark** [comment]
> > > JVM Communication is a nice way but much data can it extract from Netty?
> > 
> > 
> > Yes, with JVM IPCs using a memory mapped file we can retrieve about 10~14 million messages per second and with average latency in less than 100 nano seconds.
> > I am planning to benchmark on **raw** bytes/messages first and then move to benchmark the messages after their serialization / deserilization and this approach would also give us the average serialization/deserilization latency as well.
> 
> Did you benchmark these numbers?

Yes, these numbers could be number of :

1. Threads.
2. Channels.
3. Events.
4. Iterations (depending on use case).

**Comment by normanmaurer** [comment]
Let's close this... the students were selected for GSOC
