### ISSUE TITLE
GSoC 2020 Proposal

### ISSUE THREAD

**Issue by 1Jo1** [netty/netty#10142]
Hey, I'm Josef. I'm studying Software Engineering. I'm interested in joining the Google Summer of Code. The netty io_uring proposal is interesting for me as I implemented multiple netty and JNI projects last year. [GsoC proposal draft](https://docs.google.com/document/d/1JwfnmUbLy4-7Q7In9Be-8elOhj75M9cX1whWG2xMTuY/edit?usp=sharing)

**Comment by hyperxpro** [comment]
`the minimum supported Kernel version would have to be 5.7.`

5.7 Kernel is not out yet. Fix it.

**Comment by 1Jo1** [comment]
yeah I know it is not yet released, IORING_FEAT_FAST_POLL will be released in Linux Kernel 5.7, IORING_FEAT_FAST_POLL, it would be interesting to use it, the benchmark is very impressed 
compare to epoll https://twitter.com/josefgrieb/status/1239238240823099393

**Comment by 1Jo1** [comment]
we can also start with Linux kernel 5.6, we add some ifdef to check if it's available

**Comment by hyperxpro** [comment]
According to me, It's too early to use Kernel 5.6 or upcoming 5.7. Current LTS: 5.4.

So 'NO' from my side on this proposal,

**Comment by hyperxpro** [comment]
Let's see what others say about this.

cc @normanmaurer @franz1981

**Comment by normanmaurer** [comment]
I think we can support different things here and just ifdef to enable or disable depending on the kernel.

**Comment by normanmaurer** [comment]
Let's close this... the students were selected for GSOC
