### ISSUE TITLE
GSOC 2020 Proposal - Regression Testsuite

### ISSUE THREAD

**Issue by Yuvraj1108** [netty/netty#10145]
Hello everyone,

I am Yuvraj, a sophomore undergrad in Computer Science & Engineering from Indian Institute Of Technology, Goa. 
I am looking forward to contributing to Netty this year in GSOC 2020 for the project: Regression testsuite.

[Here](https://docs.google.com/document/d/1YMeEsS_9EUbu0AYExSFHvLR-6C8sMKF1CwrlHV5T7cY/edit?usp=sharing) is my first draft proposal.

Please provide your feedback for the same.

Thanks

**Comment by Yuvraj1108** [comment]
Please provide a review as only two days are left for the final submission.
Your feedback is highly valuable for me and will help me to modify my proposal.

**Comment by Yuvraj1108** [comment]
Hi,

Please provide your valuable feedback as it will help me a lot to modify my proposal.

Thanks

**Comment by Yuvraj1108** [comment]
Hi,

Please provide a feedback before the final hour. Your feedback is highly valuable to me.

Thanks

**Comment by Yuvraj1108** [comment]
Hi,

I am still open to discussing my proposal. Please provide me with feedback on the same.

Thanks,
Yuvraj

**Comment by normanmaurer** [comment]
Let's close this... the students were selected for GSOC
