### ISSUE TITLE
SslHandler handshake timeout occurs even after removal from pipeline

### ISSUE THREAD

**Issue by BenD10** [netty/netty#10158]
### Expected behavior
When an SslHandler that has a handshake timeout set is removed from the pipeline, no exceptions are thrown.

### Actual behavior
When an SslHandler that has a handshake timeout set is removed from the pipeline, `javax.net.ssl.SSLException: handshake timed out` is thrown.

### Steps to reproduce
1. Create a new pipeline and add a SslHandler with an SSLEngine set to server mode and handshake timeout set to 1 second.
2. Remove the SslHandler from the pipeline.

SSLException will be thrown in the pipeline after 1 second.

### Netty version
`4.1.44.Final`

### JVM version (e.g. `java -version`)
```
$ java -version
openjdk version "11.0.5" 2019-10-15 LTS
OpenJDK Runtime Environment Zulu11.35+18-SA (build 11.0.5+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.35+18-SA (build 11.0.5+10-LTS, mixed mode)
```

### OS version (e.g. `uname -a`)
```
$ uname -a
Linux *** 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

As soon as the SSLHandler is added to a channel and the channel becomes active, it starts the handshake processing
https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L1916

If the SSLHandler is acting as a server, it starts the timeout for the handshake
https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L1929

Which schedules a runnable to throw an exception if the handshake isn't completed before the timeout, once the handshake finishes the scheduled runnable is cancelled
https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L2043

HOWEVER, if the handler is removed from the pipeline, that scheduled runnable isn't cancelled.
https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L687

So I think that `handlerRemoved0` should cancel the scheduled runnable, but want feedback. If you agree this is the solution I'd be more than happy to contribute a patch.

**Comment by normanmaurer** [comment]
@BenD10 this makes sense... please provide a PR with a testcase included 👌

**Comment by normanmaurer** [comment]
@BenD10 actually its a bit more complicated then that... will open a PR asap

**Comment by normanmaurer** [comment]
@BenD10 PTAL https://github.com/netty/netty/pull/10161

**Comment by BenD10** [comment]
Looks awesome, thanks @normanmaurer!
