### ISSUE TITLE
 Unable to wrap SSLEngine of type sun.security.ssl.SSLEngineImpl

### ISSUE THREAD

**Issue by gautamkct** [netty/netty#10154]
I am working with Spring boot project and while starting application i am getting following exception. Followed few links as well to resolve but same issue,

```
java.lang.RuntimeException: Unable to wrap SSLEngine of type sun.security.ssl.SSLEngineImpl
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$AlpnWrapper.wrapSslEngine(JdkAlpnApplicationProtocolNegotiator.java:144) ~[netty-handler-4.1.31.Final.jar:4.1.31.Final]
	at io.netty.handler.ssl.JdkSslContext.configureAndWrapEngine(JdkSslContext.java:361) ~[netty-handler-4.1.31.Final.jar:4.1.31.Final]
```

Spring boot Gradle File

```
buildscript {
	ext {
		springBootVersion = '2.1.1.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
		 classpath 'com.google.gradle:osdetector-gradle-plugin:1.4.0'
	}
}

group = 'org.springframework.security.samples'
version = '1.0-SNAPSHOT'

apply plugin: 'java'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'com.google.osdetector'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
	maven { url "https://repo.spring.io/libs-milestone" }
	mavenCentral()
}

dependencyManagement {
	imports {
		mavenBom 'org.springframework.cloud:spring-cloud-dependencies:Greenwich.RC1'
	}
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation	'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation	'org.springframework.boot:spring-boot-starter-security'
	implementation	'org.springframework.boot:spring-boot-starter-oauth2-client'
	implementation	'org.springframework.boot:spring-boot-starter-actuator'
	implementation	'org.springframework.cloud:spring-cloud-starter-gateway'
	implementation 	'org.thymeleaf.extras:thymeleaf-extras-springsecurity5'
	implementation 	'org.conscrypt:conscrypt-openjdk:2.4.0:' + osdetector.classifier
	implementation 	'io.netty:netty-tcnative:2.0.29.Final'
}
```

**Comment by normanmaurer** [comment]
@gautamkct can you please update to the latest Netty version and let me know if you still see the problem ? 4.1.31 is quite old

**Comment by gautamkct** [comment]
@normanmaurer   Thanks for prompt response however i can see below exception in newer version as well.Please suggest

java.lang.RuntimeException: Unable to wrap SSLEngine of type sun.security.ssl.SSLEngineImpl
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$AlpnWrapper.wrapSslEngine(JdkAlpnApplicationProtocolNegotiator.java:144) ~[netty-handler-4.1.45.Final.jar:4.1.45.Final]

**Comment by slandelle** [comment]
What is your JDK version?

**Comment by gautamkct** [comment]
@slandelle JDK version is jdk 1.8.0_171

**Comment by normanmaurer** [comment]
@gautamkct ALPN is only supported in Java9 or if you use conscrypt as your provider or have the jetty alpn stuff on the class path.

**Comment by gautamkct** [comment]
@normanmaurer  - Thanks once again. Have already added below dependecy

**Comment by normanmaurer** [comment]
@gautamkct as far as I know this is not enough... you will also need to tell it to use it.

**Comment by gautamkct** [comment]
@normanmaurer - is it possible for you to provide some pointer for this or any reference link.

**Comment by johnou** [comment]
@gautamkct depends on your usecase, here is a simple example.. https://github.com/google/conscrypt/blob/8e79804715c18c19c1f3a56fd20f66fce6feb060/testing/src/main/java/org/conscrypt/TestUtils.java#L204

**Comment by normanmaurer** [comment]
Let me close this as its not a netty issue.
