### ISSUE TITLE
AbstractChannelHandlerContext eats performance

### ISSUE THREAD

**Issue by xxDark** [netty/netty#10165]
### Expected behavior
`AbstractChannelHandlerContext` should not reduce performance when exception is caught

### Actual behavior
Performance is highly reduced if too much exceptions occur

### Steps to reproduce
Popular Minecraft proxy BungeeCord suffers because of that problem during too much junk sent to the proxy.

### Minimal yet complete reproducer code (or URL to code)
```Java
	public static void main(String[] args) {
		byte[] buffer = new byte[2000];
		for (int i = 0; i <= 1000; buffer[i++] = 0);
		for (int i = 1001; i < 2000; buffer[i++] = 1);
		for (int x = 0; x < 16; x++) {
			new Thread(() -> {
				while (true) {
					try {
						Socket s = new Socket("localhost", 25577);
						OutputStream os = s.getOutputStream();
						os.write(buffer);
						os.flush();
					} catch (Exception ignored) { }
					try {
						Thread.sleep(50L);
					} catch (InterruptedException ignored) { }
				}
			}).start();
		}
		try {
			System.in.read();
		} catch (IOException ignored) { }
		System.exit(0);
	}
```
### Netty version
Tested with Netty 4.1.48-Final

### JVM version (e.g. `java -version`)
`openjdk version "1.8.0_212"
LibericaJDK Runtime Environment (build 1.8.0_212-BellSoft-b12)
LibericaJDK 64-Bit Server VM (build 25.212-b12, mixed mode)`

### Notice
This issue is caused by `AbstractChannelHandlerContext#isExceptionCaught`
The JVM takes too much time to:
1. To initialize stack trace array first time on `Throwable#getOurStackTrace` call,
2. Immediately copying it (see `Throwable#getStackTrace`).

Please fix that issue.

**Comment by xxDark** [comment]
Invoking `AbstractChannelHandlerContext#invokeExceptionCaught` directly resolved that issue, but thati's probably not the right way to deal with the problem.

**Comment by hyperxpro** [comment]
#Off-topic

Does Minecraft use TCP?

**Comment by xxDark** [comment]
> #Off-topic
> 
> Does Minecraft use TCP?

yes

**Comment by normanmaurer** [comment]
@xxDark I have a hard time to understand what you suggest here... Can you explain in more detail what you think the problem is ?

**Comment by xxDark** [comment]
> 
> 
> @xxDark I have a hard time to understand what you suggest here... Can you explain in more detail what you think the problem is ?

Each titme exception is caught, `AbstractChannelHandlerContext` checks if it is thrown in `exceptionCaught` method, which generates JVM stack trace, and copies it. Both of these operations eats performance.

**Comment by slandelle** [comment]
@normanmaurer I think the point is about `inExceptionCaught` that calls `Throwable#getStackTrace()` and hence creates a copy of the StackTrace.

If it's really not possible to do not do such stacktrace inspection (eg use a ThreadLocal), one easy optimization would be to use `StackWalker` in Java 9+.

@xxDark Then, Exceptions are supposed to be exceptional, not a standard flow control mechanism. If your system suffers from performance issues because of the way Netty handles Exceptions, your actual issue is upstream and you shouldn't throw that many exceptions.

**Comment by normanmaurer** [comment]
@slandelle I see...

I think will looking into this and thinking about it I found a bug in the current implementation:

```java

    @Test(timeout = 3000)
    public void testThrowInOtherHandlerAfterInvokedFromExceptionCaught() throws InterruptedException {
        final CountDownLatch latch = new CountDownLatch(1);
        final AtomicInteger counter = new AtomicInteger();
        Channel channel = new LocalChannel();
        try {
            group.register(channel).syncUninterruptibly();
            channel.pipeline().addLast(new ChannelInboundHandlerAdapter() {
                @Override
                public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause){
                    ctx.fireChannelReadComplete();
                }
            }, new ChannelInboundHandlerAdapter() {
                class TestException extends Exception { }

                @Override
                public void channelReadComplete(ChannelHandlerContext ctx) throws Exception {
                    throw new TestException();
                }

                @Override
                public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
                    if (cause instanceof TestException) {
                        ctx.executor().execute(new Runnable() {
                            @Override
                            public void run() {
                                latch.countDown();
                            }
                        });
                    }
                    counter.incrementAndGet();
                    throw new Exception();
                }
            });

            channel.pipeline().fireExceptionCaught(new Exception());
            latch.await();
            assertEquals(1, counter.get());
        } finally {
            channel.close().syncUninterruptibly();
        }
    }
```

This currently fails which I think is just not right as `exceptionCaught(...)` should still be called here for the second handler. WDYT @slandelle ?

**Comment by normanmaurer** [comment]
Also @trustin @Scottmitch

**Comment by xxDark** [comment]
> @xxDark Then, Exceptions are supposed to be exceptional, not a standard flow control mechanism. If your system suffers from performance issues because of the way Netty handles Exceptions, your actual issue is upstream and you shouldn't throw that many exceptions.

Thrown exceptions are `DecoderException`s, so I can't do really much about that.
Currently I'm cathing all incoming exceptions from client -> server and shutdown channel immediately.

**Comment by franz1981** [comment]
@normanmaurer Not a good practice, but maybe `-XX:-StackTraceInThrowable` can help here (them) :)

**Comment by ninja-** [comment]
nice find
