### ISSUE TITLE
keep netty !!!

### ISSUE THREAD

**Issue by LessTalk** [netty/netty#10173]
I'm in my android project use netty 4.1.45 and i only use mqtt socket function so i need a cut proguard

**Comment by hyperxpro** [comment]
Explain in more detail.

**Comment by LessTalk** [comment]
this is my code 
-keepclasseswithmembers class io.netty.** { # netty
    *;
}
but i only keep critical code i only use mqtt function

**Comment by hyperxpro** [comment]
So you're using Proguard Obfuscator to shrink size of your app.

If you only want MQTT functions then import `codec-mqtt`, `handler` and `buffer`.

Please use Stackoverflow for these types of question.

**Comment by hyperxpro** [comment]
@normanmaurer I think we can close this since it's not a Netty bug/problem.

**Comment by LessTalk** [comment]
thanks
