### ISSUE TITLE
TLSv1.3 Wrong Cipher Negotiation

### ISSUE THREAD

**Issue by hyperxpro** [netty/netty#10172]
### Expected behavior
Use TLSv1.3 Cipher TLS_AES_256_GCM_SHA384

### Actual behavior
Using TLSv1.3 Cipher TLS_AES_128_GCM_SHA256

### Steps to reproduce
Client:
```java
SslContext sslCtx = SslContextBuilder.forClient()
                .trustManager(InsecureTrustManagerFactory.INSTANCE)
                .protocols("TLSv1.3")
                .ciphers(Collections.singletonList("TLS_AES_256_GCM_SHA384"))
                .build();
```

Server:
```java
SslContext sslCtx = SslContextBuilder.forServer(ssc.certificate(), ssc.privateKey())
                    .protocols("TLSv1.3")
                    .ciphers(Collections.singletonList("TLS_AES_256_GCM_SHA384"))
                    .build();
```

### Minimal yet complete reproducer code (or URL to code)
https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/echo

### Netty version
4.1.48.Final

### JVM version (e.g. `java -version`)
openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment Corretto-11.0.6.10.1 (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.6.10.1 (build 11.0.6+10-LTS, mixed mode)

### OS version (e.g. `uname -a`)
Linux hyperxpro 5.3.0-45-generic #37~18.04.1-Ubuntu SMP Fri Mar 27 15:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hyperxpro** [comment]
On TLSv1.2, everything works perfectly.
Server:
```java
 SslContext sslCtx = SslContextBuilder.forServer(ssc.certificate(), ssc.privateKey())
                    .protocols("TLSv1.2")
                    .ciphers(Collections.singletonList("TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"))
                    .build();
```

Client:
```java
SslContext sslCtx = SslContextBuilder.forClient()
                .trustManager(InsecureTrustManagerFactory.INSTANCE)
                .protocols("TLSv1.2")
                .ciphers(Collections.singletonList("TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"))
                .build();
```

HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

**Comment by normanmaurer** [comment]
@hyperxpro is this with `SslProvider.JDK` or `SslProvider.OPENSSL` ?

**Comment by hyperxpro** [comment]
> @hyperxpro is this with `SslProvider.JDK` or `SslProvider.OPENSSL` ?

Didn't specified SslProvider.

**Comment by normanmaurer** [comment]
@hyperxpro can you explicit try with both ?

**Comment by hyperxpro** [comment]
OpenSSL:

Server:
```java
 SslContext sslCtx = SslContextBuilder.forServer(ssc.certificate(), ssc.privateKey())
                .protocols("TLSv1.3")
                .ciphers(Collections.singletonList("TLS_AES_256_GCM_SHA384"))
                .sslProvider(SslProvider.OPENSSL)
                .build();
```

Client:
```java
    SslContext sslCtx = SslContextBuilder.forClient()
                .trustManager(InsecureTrustManagerFactory.INSTANCE)
                .protocols("TLSv1.3")
                .ciphers(Collections.singletonList("TLS_AES_256_GCM_SHA384"))
                .sslProvider(SslProvider.OPENSSL)
                .build();
```

HANDSHAKEN: TLS_AES_128_GCM_SHA256


JDK:
```java
 SslContext sslCtx = SslContextBuilder.forServer(ssc.certificate(), ssc.privateKey())
                .protocols("TLSv1.3")
                .ciphers(Collections.singletonList("TLS_AES_256_GCM_SHA384"))
                .sslProvider(SslProvider.JDK)
                .build();
```

Client:
```java
    SslContext sslCtx = SslContextBuilder.forClient()
                .trustManager(InsecureTrustManagerFactory.INSTANCE)
                .protocols("TLSv1.3")
                .ciphers(Collections.singletonList("TLS_AES_256_GCM_SHA384"))
                .sslProvider(SslProvider.JDK)
                .build();
```

HANDSHAKEN: TLS_AES_256_GCM_SHA384

**Comment by normanmaurer** [comment]
@hyperxpro do you use netty-tcnative-boringssl-static ?

**Comment by hyperxpro** [comment]
Yes

**Comment by normanmaurer** [comment]
@hyperxpro ok this makes sense... BoringSSL does not allow to configure the cipher explicit and so will select what it things in the best:

https://github.com/netty/netty-tcnative/blob/netty-tcnative-parent-2.0.30.Final/openssl-dynamic/src/main/c/sslcontext.c#L492

And the selection in BoringSSL:

https://boringssl.googlesource.com/boringssl/+/refs/heads/chromium-stable/ssl/handshake_client.cc#234
