### ISSUE TITLE
Please update Bouncy Castle

### ISSUE THREAD

**Issue by Neustradamus** [netty/netty#10184]
Please update Bouncy Castle
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by normanmaurer** [comment]
@Neustradamus we love PRs... The said bouncy castle is an optional dependency anyway

**Comment by Neustradamus** [comment]
@normanmaurer: Thanks for your comment!

You can see here in the code:
- https://github.com/search?q=org%3Anetty+bouncycastle&type=Code

**Comment by Neustradamus** [comment]
@normanmaurer: Thanks for your comment!

You can see here in the code:
- https://github.com/netty/netty/search?q=bouncycastle&unscoped_q=bouncycastle

I see "1.54", please look previous links.

**Comment by Neustradamus** [comment]
@normanmaurer, @ihanyong: Can you update to 1.69?
