### ISSUE TITLE
MessageToMessageDecoder has a bug？

### ISSUE THREAD

**Issue by GeXin666** [netty/netty#10183]
### Actual behavior
if ctx.fireChannelRead has throw some execption
the code out.recycle() was not call, Whether the resource is leaked？

`for (int i = 0; i < size; i ++) {
      ctx.fireChannelRead(out.getUnsafe(i));
}
out.recycle();
`
### Minimal yet complete reproducer code (or URL to code)
MessageToMessageDecoder
`@Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
        CodecOutputList out = CodecOutputList.newInstance();
        try {
            if (acceptInboundMessage(msg)) {
                @SuppressWarnings("unchecked")
                I cast = (I) msg;
                try {
                    decode(ctx, cast, out);
                } finally {
                    ReferenceCountUtil.release(cast);
                }
            } else {
                out.add(msg);
            }
        } catch (DecoderException e) {
            throw e;
        } catch (Exception e) {
            throw new DecoderException(e);
        } finally {
            int size = out.size();
            for (int i = 0; i < size; i ++) {
                ctx.fireChannelRead(out.getUnsafe(i));
            }
            out.recycle();
        }
    }`
### Netty version
4.1.44.Final
### JVM version (e.g. `java -version`)
1.8.x

**Comment by normanmaurer** [comment]
This method should never throw... that said I think it can't hurt to just put it in a finally block

**Comment by GeXin666** [comment]
I see. Thank you so much for your response.
