### ISSUE TITLE
How to writeandflush() send data directly to the remote end instead of through the channeloutboundbuffer

### ISSUE THREAD

**Issue by hexstia** [netty/netty#10199]
When I send small byte data through netty, data merging occurs. The receiving end needs to wait a long time to receive a large data block that has been merged. I don't want to have merged data, and I need to send it in real time。
How can I do it? Thank you for telling me

**Comment by RoganDawes** [comment]
`writeAndFlush()` should put the data on the wire, that's what the `Flush` part means. Check with tcpdump exactly what is going on, perhaps?

**Comment by normanmaurer** [comment]
also depending on the pattern you may want to experiment with `TCP_NO_DELAY`

**Comment by hexstia** [comment]
I've tried TCP? Nodely, but I can't

**Comment by hexstia** [comment]
I try to read the netty source code and find that there is a do while and LinkedList in addflush() in the channeloutboundbuffer, and then the real write of DoWrite. I don't know if it's the reason here. I guess it's because of outboundbuffer that I can't write data in time. Instead, aggregate small data blocks and send them
