### ISSUE TITLE
CompositeByteBuf.addComponent doesn't guard agaist overflow

### ISSUE THREAD

**Issue by szegedi** [netty/netty#10194]
### Expected behavior

`CompositeByteBuf.addComponent` should throw an exception when adding a component overflows the maximum size of the buffer (`Integer.MAX_VALUE`).

### Actual behavior

Both `writableBytes` and/or `readableBytes` (depending on setting for `increaseWriterIndex`) as well as `capacity` overflow into negative numbers.

### Steps to reproduce

Run the reproducer in scala. Use a higher setting, e.g. `-Xmx8G` to experience the issue before running out of heap. Output will be something like:
```
400000000 400000000
800000000 800000000
1200000000 1200000000
1600000000 1600000000
2000000000 2000000000
-1894967296 -1894967296
-1494967296 -1494967296
-1094967296 -1094967296
-694967296 -694967296
-294967296 -294967296
105032704 105032704
...
```

### Minimal yet complete reproducer code (or URL to code)

```scala
import io.netty.buffer.{ ByteBufAllocator, Unpooled }

object BufTest {
  def main(args: Array[String]): Unit = {
    val alloc = ByteBufAllocator.DEFAULT

    val buf = alloc.compositeBuffer()
    // We'll keep adding 400MB components
    while (true) {
      val arr = new Array[Byte](400 * 1000 * 1000)
      buf.addComponent(Unpooled.wrappedBuffer(arr))
      println(s"${buf.writableBytes()} ${buf.capacity()}")
    }
  }
}
```

### Netty version

4.1.44 final

### JVM version (e.g. `java -version`)
```
openjdk version "11.0.5" 2019-10-15 LTS
OpenJDK Runtime Environment Zulu11.35+15-CA (build 11.0.5+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.35+15-CA (build 11.0.5+10-LTS, mixed mode)
```
### OS version (e.g. `uname -a`)
```
Darwin Attilas-MacBook-Pro-4.local 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64
```

**Comment by normanmaurer** [comment]
@szegedi sounds like a bug... would you be interested to provide a PR ?

**Comment by szegedi** [comment]
I can try. Seems to me like calling `AbstractByteBuf.checkIndex` from `CompositeByteBuf.addComponent0` is the right solution.

**Comment by normanmaurer** [comment]
@szegedi https://github.com/netty/netty/pull/10197 PTAL

**Comment by szegedi** [comment]
@normanmaurer thanks for the super-quick turnaround on this one!

**Comment by normanmaurer** [comment]
@szegedi no problem ... happy to help. Would love to hear more about how faunadb uses netty :)

**Comment by szegedi** [comment]
In one word: heavily 😄. All of network communication is async I/O based on Netty socket channel handler pipelines. We use the ByteBuf API pervasively too even outside of immediate domain of networking (disk I/O, internal transformations). It's a nice (consistent, comprehensive, easy to understand) API to manipulate byte-based data, and if we're smart about it then we also minimize copying when it's time to send the bytes over the network.
