### ISSUE TITLE
can netty take over jvm's  memory allocation when new a object?

### ISSUE THREAD

**Issue by jiemar** [netty/netty#10204]
### Expected behavior
when new a object , jvm will allocate memory at heap, it cause  gc overhead.
As we know, netty  manages a memory pool. netty can allocate and deallocate memory when using ByteBuf.
Could netty take over jvm's default behavior of allocate memory when new object?
when new a object, netty allocate memory at pool.
when object is release ,  netty gets the memory returned to pool.

gc is gone, there is no gc here, like c++

**Comment by carryxyh** [comment]
I believe this is impossible and meaningless.

**Comment by jiemar** [comment]
i believe it is meaningful considering long live objects. Ehcache、MapDB、Chronicle Map can do this, but they don't have memory pool concept at off-heap

**Comment by jiemar** [comment]
i believe it is meaningful considering long live objects. Ehcache、MapDB、Chronicle Map can do this by allocating an object 's memory at off-heap, but they don't have memory pool concept at off-heap

**Comment by normanmaurer** [comment]
Its impossible
