### ISSUE TITLE
DNS Resolver - Honor etc/resolv.conf options timeout, rotate and attempts

### ISSUE THREAD

**Issue by fabienrenaud** [netty/netty#10202]
[/etc/resolv.conf](https://linux.die.net/man/5/resolv.conf) options support `timeout`, `rotate` and `attempts` but the [UnixResolverDnsServerAddressStreamProvider](https://github.com/netty/netty/blob/4.1/resolver-dns/src/main/java/io/netty/resolver/dns/UnixResolverDnsServerAddressStreamProvider.java#L292) ignores these options.

These should be parsed and used accordingly to their documented behavior.

**Comment by normanmaurer** [comment]
@fabienrenaud we love contributions :) So if you are interested maybe you want to provide a PR

**Comment by fabienrenaud** [comment]
PR: https://github.com/netty/netty/pull/10207
