### ISSUE TITLE
Identifying security related exceptions on failed TLS handshake

### ISSUE THREAD

**Issue by rekalov** [netty/netty#10214]
Hi,

Is there a reliable way to distinguish security related exceptions from the rest (transport etc) in unsuccessful `SslHandshakeCompletionEvent`?

We'd like to block further re-connections to locations presenting invalid/unmatched certificates, but not honest handshake communication errors and timeouts.
In other words if the protocol appears to have proceeded without any erroneous behaviour, but then just stops or get a TCP RST packet we wish to know. Anything where signatures, or checksums, or identity presented, or root mismatch, or bad packets, or CRL revocation is treated as bad and to be blocked.

At the moment we're categorizing exceptions based on message text, which is completely unreliable and causes issues during upgrades. For example, we had to adjust our code to the new transport related SSLException introduced in `SslHandler.setHandshakeFailureTransportFailure()` during 4.1.29 -> 4.1.46 upgrade.

Netty version: 4.1.46

**Comment by hyperxpro** [comment]
Nice idea but there is no reliable way yet to get detailed information about TLS failures.

**Comment by normanmaurer** [comment]
@rekalov I think the closest you could do is to check if the cause is an `SslHandshakeException` and if so what kinds of exception it wraps

**Comment by rekalov** [comment]
thanks @normanmaurer
