### ISSUE TITLE
Not support for  SSLV2 

### ISSUE THREAD

**Issue by apa7** [netty/netty#10216]
Does not support the  protocol-sslv2, breakpoint debugging found that byte [0] is not 22 but -128. 
In other words, byte [0] =-128 cannot be accurately identified as SSL2hello.

### Netty version
4.1.48
### JVM version (e.g. `java -version`)
jdk11
windows  sslv2 protocol

**Comment by hyperxpro** [comment]
AFAIK, SSLv2 is not supported. OpenSSL also dropped its support long ago.

**Comment by normanmaurer** [comment]
@apa7 this is expected... if I understand what you asking for correctly
