### ISSUE TITLE
what would happenned when pooled memory's remaining size is not enough

### ISSUE THREAD

**Issue by jiemar** [netty/netty#10230]
PooledByteBufAllocator.newDirectBuffer(initialCapacity, maxCapacity)

if the remaining size of memory pool is below initialCapacity, what would happend when i call the method?
it will blocked the caller until the memory pool 's remaining size turns ok, or throw an oom?

does it mean  i need to keep a atomlong variable to calculate all the bytebufs i have allocated and
the sum size must below off-heap's size to avoid the oom?

**Comment by zhenjunMa** [comment]
in my idea:
1. throw OOM
you can read codes in class: `DirectArena`  method: `allocateDirect`

2. how to avoid the OOM is just like java, if you get an OOM error, 
first you should check your code, maybe it has memory leak problem
second you must add the memory size use `-Dio.netty.maxDirectMemory`

**Comment by normanmaurer** [comment]
it throws.
