### ISSUE TITLE
Why EventLoopGroup takes 1 second to awaitTermination ?

### ISSUE THREAD

**Issue by runzhiwang** [netty/netty#10241]
Netty version 4.1.48.Final

EventLoopGroup cost one second to finish awaitTermination, Could someone explain me the reason ?

The close order is:
1. EventLoopGroup::close
2. EventLoopGroup::awaitTermination(5000, TimeUnit.MILLISECONDS);

**Comment by ninja-** [comment]
AFAIK it was hardcoded value to kill everything if something isn't properly cleaned up first. maybe you need to shutdown listening channels as well?

**Comment by runzhiwang** [comment]
@ninja- Thanks for response. I'm not sure I have closed everything. If you do not mind, could you help review my code [closeImpl](https://github.com/apache/incubator-ratis/blob/master/ratis-netty/src/main/java/org/apache/ratis/netty/server/NettyRpcService.java#L145).

**Comment by normanmaurer** [comment]
You can use `EventLoopGroup.shutdownGracefully(...)` and pass in the amount of timeout
