### ISSUE TITLE
not clearing heap memory - threads allocated and not releasing netty latest version

### ISSUE THREAD

**Issue by praveens4all** [netty/netty#10252]
### Expected behavior
Heap memory should clear after processing messages
### Actual behavior
Keep piling up memory not releasing my threads still serving for network messages for checking connections.
### Steps to reproduce
keep checking network connectivity and processing messages.
![image](https://user-images.githubusercontent.com/19388738/81173023-a63fea00-8f9f-11ea-8d0e-24dce0738d98.png)

### Minimal yet complete reproducer code (or URL to code)

server :
            ServerBootstrap bootstrap = new ServerBootstrap();
            bootstrap.group(bossGroup, workerGroup)
                    .channel(NioServerSocketChannel.class)
                    .childHandler(new ChannelInitializer<SocketChannel>() {
                        @Override
                        public void initChannel(SocketChannel ch)
                                throws Exception {
                            ch.pipeline().addLast("decoder", new Decoder())
                                    .addLast("encoder", new Encoder())
                                    .addLast(group, new Handler());

                        }
                    }).option(ChannelOption.SO_BACKLOG, 1024)
                    .childOption(ChannelOption.TCP_NODELAY, true)
                    .childOption(ChannelOption.SO_KEEPALIVE, true);

 List<Integer> ports = Arrays.asList(8080,8081);
             channels = new ArrayList<>(ports.size());
            for (int port : ports) {
                Channel serverChannel = bootstrap.bind(port).sync().channel();
                channels.add(serverChannel);
            }

decoder : 
public class Decoder extends ByteToMessageDecoder {

    @Override
    protected void decode(ChannelHandlerContext ctx, ByteBuf byteBuf, List<Object> out) throws Exception {
---- business logic to read --
add object to out.
out.add(msg);
}
}
handler : 
public class Handler extends ChannelInboundHandlerAdapter {

@Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
--business logic--
ctx.writeAndFlush(msg);
}
}

Encoder : 

public class Encoder extends MessageToByteEncoder<Object> {

 @Override
    protected void encode(ChannelHandlerContext ctx, Object msg, ByteBuf out) {

--business logic --

out.writeBytes(msg.getBytes());

}
}

### Netty version
4.1.45.Final
### JVM version (e.g. `java -version`)
Adopt OpenJDK 11
### OS version (e.g. `uname -a`)
Linux

**Comment by amizurov** [comment]
@praveens4all Hi by default Netty uses the PooledByteBufAllocator which can cache an allocated buffer to reusing.

**Comment by praveens4all** [comment]
> @praveens4all Hi by default Netty uses the PooledByteBufAllocator which can cache an allocated buffer to reusing.

Okay, Thank you for response, In my application i wont reuse any messages, processing messages were huge and making out of memory because Old Generation GC filled up my entire RAM. Is there any way to clear or use another buffer ? Pls advise.

**Comment by amizurov** [comment]
You can try `UnpooledByteBufAllocator`  
 ```
ServerBootstrap serverBootstrap = new ServerBootstrap();
serverBootstrap
    .childOption(ChannelOption.ALLOCATOR, UnpooledByteBufAllocator.DEFAULT);
 ...
 ```
See if it is suitable for your case, since now Netty will not be able to reuse buffers and will allocate them every time, which can lead to frequent GC.

**Comment by normanmaurer** [comment]
Also alternative you can configure the `PooledByteBufAllocator` to only pool direct memory

**Comment by praveens4all** [comment]
> Also alternative you can configure the `PooledByteBufAllocator` to only pool direct memory

Sorry for late reply.....Please provide me example how to do that, i did not configure any explicitly. 

Still my GC filledup..

![Capture](https://user-images.githubusercontent.com/19388738/82444011-d066d100-9aa2-11ea-8309-21984d2ad54b.JPG)

**Comment by amizurov** [comment]
e.g. via system properties `-Dio.netty.allocator.numHeapArenas=0`

**Comment by praveens4all** [comment]
Thank you for reply @amizurov 

I have tried, 
 .childOption(ChannelOption.ALLOCATOR, UnpooledByteBufAllocator.DEFAULT); still no change in memory.

as i explained, my requirement server and client runs 24/7 never disconnects keep processing messages.

if i use system property -Dio.netty.allocator.numHeapArenas=0 then can i revert UnpooledByteBufAllocator changes ? still need to use UnpooledByteBufAllocator? please advise.

**Comment by amizurov** [comment]
No, you can remove ‘UnpooledByteBufAllocator’ and use default pooled allocator with disabled heap arena, like @normanmaurer suggested.

**Comment by praveens4all** [comment]
okay, Thank you, will try and update you tomorrow.

**Comment by praveens4all** [comment]
> No, you can remove ‘UnpooledByteBufAllocator’ and use default pooled allocator with disabled heap arena, like @normanmaurer suggested.

Still no changes in memory, i have added vm argument.
how can i verify properties reflected or not ? 

i debug my ByteToMessageDecoder , SimpleChannelInboundHandler, MessageToByteEncoder ..seems releasing buffer code not triggering, because my connection still active.

**Comment by itlidaye** [comment]
> ![捕获](https://user-images.githubusercontent.com/19388738/82444011-d066d100-9aa2-11ea-8309-21984d2ad54b.JPG)

What is this tool?

**Comment by praveens4all** [comment]
> > ![捕获](https://user-images.githubusercontent.com/19388738/82444011-d066d100-9aa2-11ea-8309-21984d2ad54b.JPG)
> 
> What is this tool?

dynatrace

**Comment by itlidaye** [comment]
Has the problem been solved?

**Comment by praveens4all** [comment]
No still we facing outofmemory - due to old generation space filled up with netty buffer i think..not clearing buffer.

**Comment by normanmaurer** [comment]
I think you will need to share more code and also ensure there are no buffer leaks detected.
