### ISSUE TITLE
Implementing Write Throttling / Back pressure

### ISSUE THREAD

**Issue by ajaygeorge** [netty/netty#10254]
This is more of a design question on what is the correct way to implement _Write Throttling / Back pressure_, so that we don't continue writing to a channel when `isWritable` flag returns false.
I have added the High and Low WaterMarks to control when exactly this flag should return false.

looking at @normanmaurer 's answer on [SO](https://stackoverflow.com/a/19721250/628943) for this issue : 

> You are writing faster then the network stack can handle. Be aware it's all asynchronous... You want to stop writing once Channel.isWritable() returns false and resume once it returns true again. You can notified for this changes by override the channelWritabilityChanged(...) method in ChannelInboundHandler.

What I have tried in order to **stop** writing when `Channel.isWritable()` returns false and **resume** when it returns true, is to block on the event loop thread while checking for the flag in a loop. This is not ideal since the event loop thread is blocked. What would be the correct way to do achieve throttling/back pressure handling ? . Any help is much appreciated.

### Relevant code snippets.
Listening to channel writability changed and unlocking
```
public void channelWritabilityChanged(ChannelHandlerContext ctx)
            throws Exception {
        Channel channel = ctx.channel();
        ThrottleLock throttleLock = channel.attr(THROTTLE_LOCK_KEY).get();
        if (channel.isWritable()) {
            synchronized (throttleLock) {
                throttleLock.notifyAll();
            }
        }
        ctx.fireChannelWritabilityChanged();
    }
```
waiting and blocking to see if the channel is writable 

```
    ThrottleLock throttleLock = channel.attr(THROTTLE_LOCK_KEY).get();                       
     synchronized (throttleLock) {
         while (!channel.isWritable()) {                                    
                 throttleLock.wait(TimeUnit.MILLISECONDS.toMillis(100));
       }
       channel.writeAndFlush(request);
     }
                        
```
### Netty Version
4.1.29.Final

### Java Version
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)

**Comment by ajaygeorge** [comment]
@normanmaurer , wondering if you have any ideas around this.?

**Comment by hk-ng** [comment]
You get notification from event loop in channelWritabilityChanged by implementing ChannelInboundHandler:

[https://netty.io/4.1/api/io/netty/channel/ChannelInboundHandler.html#channelWritabilityChanged-io.netty.channel.ChannelHandlerContext-](https://netty.io/4.1/api/io/netty/channel/ChannelInboundHandler.html#channelWritabilityChanged-io.netty.channel.ChannelHandlerContext-)

**Comment by hk-ng** [comment]
How about writing your own queue instead? You are not support to do anything blocking in the event loop.

**Comment by ajaygeorge** [comment]
@hk-ng . Thanks for taking a look. ! This is something I considered. 
This queue/buffer will have to be a bounded blocking queue since if it is unbounded we run into the same issue as continuing to write when the write flag is false and exhausting the memory. It has to be a blocking queue as well, else we will have to start dropping the requests on the floor when the queue is full or sending an error back to client.(which might be a reasonable approach, but if the ordering is important we will have to start considering some edge cases if the retries come out of order)
This bounded blocking queue solution is just bringing the problem from the netty internal code to our code and having to deal with the same issues all over again.
Let me know if this thought process is correct or you were thinking of something completely different.

**Comment by hk-ng** [comment]
If the event loop is blocked, Netty will stop sending or receiving from socket.
In the example above, it causes a dead lock because Netty will not be able to send anything when the event loop is blocked.

**Comment by johnou** [comment]
@ajaygeorge try taking a look at https://github.com/netty/netty/pull/6662/files

**Comment by ajaygeorge** [comment]
Thanks @johnou . Looking at that PR , it seems like trustin had some concerns over the implementation which I believe was the reason why it was not merged.
As the PR description suggests this for implementing back-pressure to stop reading from a socket.

> Often what can be done to implement back-pressure is to stop reading from the socket until we were able to flush out enough data. We should provide some generic re-usable handlers.

In my case, the backpressure handling is needed for writes to a remote peer (not running netty) from a local client (running netty)

**Comment by normanmaurer** [comment]
@ajaygeorge basically you need to stop writing unit the channel becomes writable again. You will be notified once the writability state of the `Channel` changes via the `ChannelInboundHandler.channelWritabilityChanged(...)` callback. Once this happens you can start writing again. How you propagate this though your application / framework, is up to you. Just never block the event loop.
