### ISSUE TITLE
why stomp.js can not get the message body

### ISSUE THREAD

**Issue by xiaozaiyuji** [netty/netty#10261]
### Expected behavior
Expect the stomp.js can use netty stomp send a messge to a topic and other stomp.js can receive the message.
### Actual behavior
when Iuse netty stomp send a messge to a topic and other stomp.js  receive the message,I found the stomp.js client can not recevice the message the message body is empty. In the web brower network console chosse ws you will find the message is split to two message .
### Steps to reproduce
use the code in package io.netty.example.stomp  and start the server, use stomp.js send a messge to a topic and other stomp.js receive the message.
### Netty version
4.1.49.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_231"
### OS version (e.g. `uname -a`)
windows 10

**Comment by amizurov** [comment]
Hi, I take a look
