### ISSUE TITLE
[Improvement] Add Http status as a separate field in exception on not 101 HTTP response code during web socket handshake

### ISSUE THREAD

**Issue by Fetsivalen** [netty/netty#10277]
### Reason
In my project (built on top of Spring Cloud Gateway https://github.com/spring-cloud/spring-cloud-gateway) to be able to properly proxy HTTP response (on not 101 Http response code) from the backend server to the client, I need to extract actual Http Status code. For now, it could be done only by parsing the exception's message.
To simplify such use cases I'd like to introduce the sub-class of the WebSocketHandshakeException and enrich it with actual Http status to avoid extra string parsing.
### Expected behavior
In the case of the wrong Http Status during Handshake throw WrongStatusWebSocketHandshakeException (for example) with Http status as an exception field
### Actual behavior
Actual Http status code could be only obtained by parsing exception's message of the WebSocketHandshakeException.
### Steps to reproduce
Try to establish a web-socket  connection with a server which returns not 101 HttpStatus code
### Minimal yet complete reproducer code (or URL to code)
I can create a reproducible  sample, but it seems obvious from the code
https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshaker13.java#L274
(same for other Handshaker implementations ).

I omitted versions since they are not relevant in this case.

**Comment by amizurov** [comment]
So, what if we extend the current exception to `ClientWebSocketHandshakeException` and add `HttpResponse` field and `ServerWebSocketHandshakeException` with `HttpRequest` field and provide additional hint `AbortingType` like INVALID_RESPONSE_STATUS, INVALID_CONNECTION_HEADER,... and other by https://tools.ietf.org/html/rfc6455#section-4.2.2. WDYT @normanmaurer, @slandelle ?

**Comment by normanmaurer** [comment]
@amizurov I am a bit hesitant as this may also put the burden of reference counting on the user.

**Comment by amizurov** [comment]
> @amizurov I am a bit hesitant as this may also put the burden of reference counting on the user.

I mean only `DefaultHttpResponse` and `DefaultHttpRequest` without body, in most of case it will be enough.

**Comment by Fetsivalen** [comment]
From my perspective it will be sufficient just to bypass a separate field in exception the information which is already present in it's exception message, just to avoid parsing strings.
But I agree with @amizurov  that whole meta-information (like headers) will cover more use cases.
From other perspective I don't find similar tickets here, and not sure whether someone need any information, which is not provided in message.
In any case I can contribute this improvement if it will be welcomed.
WDYT @normanmaurer  ?

**Comment by amizurov** [comment]
Hi, guys added some related links according this discussion
 
- #4528 (i think this is first mention about problem)

- https://github.com/spring-cloud/spring-cloud-gateway/issues/1884 (similar to our case)
