### ISSUE TITLE
netty-transport-native-epoll for aarch64 is missing from netty-bom

### ISSUE THREAD

**Issue by rovarga** [netty/netty#10290]
### Expected behavior
linux-aarch64 version declaration is available from netty-bom import

### Actual behavior
Version declaration is not present

### Steps to reproduce
Pull netty declarations via netty-bom import, attempt to reference linux-aarch64 netty-transport-native-epoll

### Minimal yet complete reproducer code (or URL to code)
https://git.opendaylight.org/gerrit/c/odlparent/+/89743

### Netty version
4.1.50.Final

### JVM version (e.g. `java -version`)
All

### OS version (e.g. `uname -a`)
All

**Comment by normanmaurer** [comment]
@rovarga sounds like a bug... would you be interested in providing a PR ?

**Comment by rovarga** [comment]
@normanmaurer yup, along with a safety check forthcoming.
