### ISSUE TITLE
Not able to make connection to the server which supports TLS1.2 only

### ISSUE THREAD

**Issue by karthik-dusk** [netty/netty#10307]
### Expected behavior
Should be able to connect to the server

### Actual behavior

`WampClient.State newState`
says connecting

### Steps to reproduce
```
IWampConnectorProvider connectorProvider = new NettyWampClientConnectorProvider();
        NettyWampConnectionConfig connectionConfiguration =
                new NettyWampConnectionConfig.Builder()
                        .withSslContext(SslContext.newClientContext())
                        .build();

        String url = mWampCredentials.mConnectionURL.replace(" ", "");
        String token  = AuthenticationModule.getAuthenticationService().getAuthenticationToken();
        WampClientBuilder builder = new WampClientBuilder();
        builder.withConnectorProvider(connectorProvider)
                .withConnectionConfiguration(connectionConfiguration)
                .withUri(url)
                .withRealm(WAMP_REALM)
                .withAuthId(mWampCredentials.mUsername)
                .withAuthMethod(new Ticket(token))
                .withInfiniteReconnects()
                .withReconnectInterval(10, TimeUnit.SECONDS);
        // Create a client through the builder. This will not immediately start
        // a connection attempt
        mWampClient = builder.build();

        mWampStateSubscription = RxJavaInterop.toV2Observable(mWampClient.statusChanged())
                .subscribeOn(Schedulers.io())
                .subscribe(new Consumer<WampClient.State>() {
                    @Override
                    public void accept(@NonNull WampClient.State newState) throws Exception {
                        if (newState instanceof WampClient.ConnectingState) {
                            Logger.get().d(this, "3.2: WAMP State Changed to: Connecting");
                        } else if (newState instanceof WampClient.ConnectedState) {
                            Logger.get().d(this, "3.2: WAMP State Changed to: Connected");
                            // Client got connected to the remote router
                            // and the session was established
                            updateConnectionConnected();
                        } else if (newState instanceof WampClient.DisconnectedState) {
                            Logger.get().d(this, "3.2: WAMP State Changed to: Disconnected");
                            // Client got disconnected from the remote router
                            // or the last possible connect attempt failed
                            updateConnectionDisconnected(false);
                        }
                    }
                }, new Consumer<Throwable>() {
                    @Override
                    public void accept(@NonNull Throwable throwable) throws Exception {
                        throwable.printStackTrace();
                        Logger.get().d(this, "3.2: WAMP State Changed to: Disconnected - Exception Thrown");
                        updateConnectionDisconnected(true);
                    }
                });
```

### Minimal yet complete reproducer code (or URL to code)
Updated above

### Netty version
4.1.48

### JVM version (e.g. `java -version`)
1.8

### OS version (e.g. `uname -a`)
Android-21

**Comment by karthik-dusk** [comment]
NettyWampConnectionConfig object
![Capture](https://user-images.githubusercontent.com/5618488/82246041-a063e480-9961-11ea-93c5-c0b13c71d56b.PNG)

**Comment by hyperxpro** [comment]
This is clearly not a Netty bug.

**Comment by karthik-dusk** [comment]
But I am using all netty APIs.

**Comment by karthik-dusk** [comment]
It works fine with TLS1.1 but failing to connect TLS1.2

**Comment by hyperxpro** [comment]
Can you show `SslContext` builder code?

**Comment by karthik-dusk** [comment]
> This is clearly not a Netty bug.

What else could be the problem .?

**Comment by hyperxpro** [comment]
> > This is clearly not a Netty bug.
> 
> What else could be the problem .?

`SslContext` not configured properly.

**Comment by karthik-dusk** [comment]
I have attached the screenshot of SslContext instance

**Comment by karthik-dusk** [comment]
> NettyWampConnectionConfig object
> ![Capture](https://user-images.githubusercontent.com/5618488/82246041-a063e480-9961-11ea-93c5-c0b13c71d56b.PNG)
> 
> Logs as per the code above,
> 
> ```
> D/com.karthik.ispmobile.communicator.event.network.EventNWService: 1.1: Fetching WAMP Credential: State: 1
> D/com.karthik.ispmobile.communicator.event.network.EventNWService$2: 1.1: WAMP Credential fetched: State: 1
> D/com.karthik.ispmobile.communicator.event.network.EventNWService: 2.1: Fetching WAMP Subscription: State: 1
> D/com.karthik.ispmobile.network.volley.VolleyRequest: Requested succeeded for URL: https://xyz.karthik.com/ksome/KSOME/EventMgmt/EventStreams/filters?q=(eventFilter.filterElement.eventTypeTemplateName=MobileWamp)
> D/com.karthik.ispmobile.communicator.event.network.EventNWService$4: 2.1: WAMP Subscription fetched: State: 1
> D/com.karthik.ispmobile.communicator.event.network.EventNWService: 3.1: Connecting to WAMP: State: 1
> D/com.karthik.ispmobile.communicator.event.network.EventNWService$6: 3.2: WAMP State Changed to: Disconnected
> D/com.karthik.ispmobile.communicator.event.network.EventNWService$6: 3.2: WAMP State Changed to: Connecting
> ```
> 
> it stops here.

Here

**Comment by hyperxpro** [comment]
What cipher suites are enabled?

**Comment by karthik-dusk** [comment]
I will get back to you on these .. tomorrow pls

**Comment by karthik-dusk** [comment]
here it is ..
![Capture1](https://user-images.githubusercontent.com/5618488/82283139-22c8c480-99b3-11ea-9075-632286651c7b.PNG)

**Comment by hyperxpro** [comment]
And you show server `SslContext` builder?

**Comment by karthik-dusk** [comment]
Got it fixed @hyperxpro , The problem is not at all related to Netty and it is also not related to sslContext properties. 

I was facing this issue because of the org's firewall was blocking the connection and events. 

So, closing this issue. And, thank you so much for spending your valuable time on this issue. I appreciate that.
