### ISSUE TITLE
readableBytes

### ISSUE THREAD

**Issue by wplzw** [netty/netty#10308]

**Comment by wplzw** [comment]
why value of buffer.readableBytes()  less than readableBytes(4) would throw REPLAY

**Comment by hyperxpro** [comment]
Can you please elaborate?

**Comment by wplzw** [comment]
thanks for you response,I have got it，thank you again!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Aayush Atharva"<notifications@github.com&gt;; 
发送时间: 2020年5月20日(星期三) 中午12:21
收件人: "netty/netty"<netty@noreply.github.com&gt;; 
抄送: "危飘林"<1977334800@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [netty/netty] readableBytes (#10308)





 
Can you please elaborate?
