### ISSUE TITLE
NioSocketChannel.writeAndFlush().addListener() callback sometimes called before the message is written/flushed

### ISSUE THREAD

**Issue by kareemadel** [netty/netty#10306]
I have a netty client that used a NioSocketChannel to send/receive messages to/from a server, the pipeline has only two outbound handlers, WebSocketClientCompressionHandler and HttpClientCodec handler.
The code that writes to the channel is something like

```java
// message is of type WebSocketFrame
channel.writeAndFlush(message).addListener(future -> {
    if (message.refCnt() > 0) {
        ReferenceCountUtil.release(message, message.refCnt);
    }
    if (future.isSuccess()) {
        // do something
    } else {
        // handle error
    }
});
```

### Expected behavior
The add listener callback to be executed after the message is written and flushed
### Actual behavior
Sometimes, this [line](https://github.com/liaokailin/netty/blob/master/codec/src/main/java/io/netty/handler/codec/MessageToMessageEncoder.java#L91) throws an IllegalReferenceCountException due to over release.

This code runs a lot and it happens rarely but I noticed that it only happens only when the `if (message.refCnt() > 0)`  block is executed, so my guess is that sometimes this channelFuture callback, is called before the MessageToMessageEncoder actually calls release.

I know that it's the responsibility of the last outbound channel to release the buffer, but I had this as a precaution in case the code later was modified, and I don't get why this happens sometimes.  I thought the callback to the channelFuture returned by writeAndFlush would be executed only after the messaged is flushed. or is that not a guarantee? if it's not, then when is it actually called?
### Steps to reproduce
I can't reproduce it consistently.

### Netty version
4
### JVM version (e.g. `java -version`)
8
### OS version (e.g. `uname -a`)
RHEL 5

**Comment by normanmaurer** [comment]
@kareemadel this can happen if the same content of the buffer is duplicated and retained for example. Don't do this.

**Comment by kareemadel** [comment]
@normanmaurer I'm not reusing the buffer, I allocate new buffer for each message
```java
public Future<?> write(Protobuf.Message message) {
    // input validations
    int size = message.getSerializedSize();
    ByteBuf messagebuffer = channel.alloc().buffer(size + HEADER_SIZE);
    messageBuffer.writeShort(size);
    messageBuffer.writeBytes(message.toByteArray());
    return writeWebSocketFrame(new BinaryWebSocketFrame(messagebuffer), messageBuffer);
}

private Future<?> writeWebSocketFrame(WebSocketFrame message, ByteBuf buffer) {
    return channel.writeAndFlush(message).addListener(future -> {
        if (message.refCnt() > 0) {
            ReferenceCountUtil.release(message, message.refCnt);
        }
        if (future.isSuccess()) {
            // do something
        } else {
            // handle error
        }
    });
}
```

**Comment by kareemadel** [comment]
@normanmaurer the underlying buffer allocator is pooled though, do you think that could be the problem? This is how I initialize the buffer allocator.

```java
new PreferHeapByteBufAllocator(new PooledByteBufAllocator(false))
```
