### ISSUE TITLE
Http2ConnectionHandler: Http2Settings used by preface, and ones exposed through decoder().localSettings() are different instances

### ISSUE THREAD

**Issue by mostroverkhov** [netty/netty#10302]
### Expected behavior

Http2Settings returned by public Http2ConnectionHandler.decoder().localSettings() are used for sending preface

### Actual behavior

Above are different instances so options added through public API are ignored

### Steps to reproduce

https://github.com/netty/netty/blob/bdbf68f9881b7187c0da45d5b45f32f92fe5efaa/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L362

https://github.com/netty/netty/blob/bdbf68f9881b7187c0da45d5b45f32f92fe5efaa/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L179

### Netty version

4.1.50

**Comment by mostroverkhov** [comment]
@normanmaurer I can resort to reflection for accessing actual [settings](https://github.com/netty/netty/blob/bdbf68f9881b7187c0da45d5b45f32f92fe5efaa/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L362) sent in preface, though this is will take effect only when #10300 gets resolution - is this intended behavior?

**Comment by ejona86** [comment]
No, I don't think `Http2ConnectionHandler.decoder().localSettings()` is likely appropriate for changing the initial settings. In general the encoder/decoder need to be notified when the settings change, so allowing "random" mutation outside of their knowledge would just cause "bad things" to happen.

Instead, pass the initial settings in the [constructor](https://github.com/netty/netty/blob/bdbf68f9881b7187c0da45d5b45f32f92fe5efaa/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L85) or [builder](https://github.com/netty/netty/blob/bdbf68f9881b7187c0da45d5b45f32f92fe5efaa/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandlerBuilder.java#L35).

**Comment by mostroverkhov** [comment]
@ejona86 e.g. for https://tools.ietf.org/html/rfc8441 one needs `SETTINGS_ENABLE_CONNECT_PROTOCOL SETTINGS` parameter set on server settings - what is suggested "clean" way of doing that for if implemented outside of netty (without forcing users to set parameter on http2's builders)

**Comment by mostroverkhov** [comment]
what I mean is asking users to put `initialSettings().put(SETTINGS_ENABLE_CONNECT_PROTOCOL, (Long) 1L);` on their builders is not cleanest solution (one also needs to know 0xcode of parameter), or builders can be extended with `enableHttp2WebSocket()` option - despite there is no support for that inside netty itself?

**Comment by ejona86** [comment]
> without forcing users to set parameter on http2's builders

@mostroverkhov, why is that solution dismissed?

> what I mean is asking users to put initialSettings().put(SETTINGS_ENABLE_CONNECT_PROTOCOL, (Long) 1L); on their http2 builders is not cleanest solution (one also needs to know 0xcode of parameter)

That seems completely separate from the issue filed. The issue filed was that you couldn't change the initial settings using the Http2Settings API. Now you _don't_ want to use the existing Http2Settings API?

I don't see it as unreasonable to require you to know the hexcode for the setting, given you are implementing the HTTP/2 extension. But it seems it would also be easy to add a convenience method to Http2Settings.

**Comment by mostroverkhov** [comment]
> Now you don't want to use the existing Http2Settings API?

To clarify crux of the problem - I can't change Http2Settings outside of Http2ConnectionHandler (from `http2WebSocketHandler` present in pipeline) for 2 reasons:

* only public API for settings I am aware of - `Http2ConnectionHandler.decoder().localSettings()` - returns new instance of settings, not the instance actually sent in [preface](https://github.com/netty/netty/blob/bdbf68f9881b7187c0da45d5b45f32f92fe5efaa/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L362). Modifications on this new instance are not accounted when sending preface.

*  preface is sent before `Http2ConnectionHandler.handlerAdded()`  returns so It is too late to change settings in `http2WebSocketHandler.handlerAdded()` - I regret this was filed as separate  issue (#10300), should be done as one.
 
> why is that solution dismissed?

Presence of hypothetical `http2WebSocketHandler` in server pipeline implies `SETTINGS_ENABLE_CONNECT_PROTOCOL` parameter should be set on `Http2ConnectionHandler` settings - otherwise other side of connection wont be able to use http2 websocket.  Requirement to set in explicitly in `Http2ConnectionHandler`'s Builder looks redundant - if user forgets flag, but has `http2WebSocketHandler`, that is programming mistake which can be avoided by just putting all necessary parameters in 1 place - `http2WebSocketHandler`. Either both `http2WebSocketHandler` and respective settings param are present, or none of them.

> But it seems it would also be easy to add a convenience method to Http2Settings

That would be useful addition. 

Also I guess having `:protocol` pseudoheader in [Http2Headers](https://github.com/netty/netty/blob/de134da720d23909151d20e6af6eb2a96181bf03/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2Headers.java#L34) is necessary so [HPackDecoder](https://github.com/netty/netty/blob/de134da720d23909151d20e6af6eb2a96181bf03/codec-http2/src/main/java/io/netty/handler/codec/http2/HpackDecoder.java#L393) validation succeeds? - asking here to not split info related to 1 feature across multiple issues.

**Comment by ejona86** [comment]
> only public API for settings I am aware of

I referenced _two_ public APIs, the Http2ConnectionHandler constructor and its builder. If you are using the http/2 multiplexing codec, then it is also available on Http2MultiplexCodecBuilder. So we should be clear the issue is _not_ the lack of public APIs.

> Requirement to set in explicitly in Http2ConnectionHandler's Builder looks redundant

Okay, so the issue isn't "it isn't possible" but instead "it has usability issues."

> if user forgets flag, but has http2WebSocketHandler, that is programming mistake which can be avoided by just putting all necessary parameters in 1 place

So it is possible for `Http2WebSocketHandler` to _verify_ the setting is in-place. So the only issue is the developer would have to go through another modify/test cycle.

However, with the way SETTINGS_ENABLE_CONNECT_PROTOCOL was designed, I don't think it is _safe_ for Http2WebSocketHandler to implicitly set it. The setting is for the _entire connection_. If any other code present also handles CONNECT, then it may be broken by the setting. The application author needs to be aware that _all_ CONNECT code has to be compatible when setting SETTINGS_ENABLE_CONNECT_PROTOCOL.

**Comment by mostroverkhov** [comment]
> I referenced two public APIs

The question was how to modify `Http2Settings` *after* `Http2ConnectionHandler` is created, but *before* settings are sent. 

Anyways, I will do what was suggested - set settings parameters when server `Http2ConnectionHandler` is created. Particularly, for [rcf8441](https://tools.ietf.org/html/rfc8441) that means roughly `initialSettings().put(SETTINGS_ENABLE_CONNECT_PROTOCOL, (Long) 1L);` for `Http2ConnectionHandler` in addition to having `Http2WebSocketHandler` on pipeline.

Thanks @ejona86!
