### ISSUE TITLE
Netty 3.10.6.Final nullSession jdk8u252

### ISSUE THREAD

**Issue by WTFGEDelphia** [netty/netty#10322]
error messages:
java.lang.NoSuchFieldError: nullSession

![image](https://user-images.githubusercontent.com/36285660/83002801-0d513b80-a040-11ea-9898-e5301ac370f1.png)

**Comment by hyperxpro** [comment]
AKAIK, Netty 3 reached EOL. Consider upgrading to latest versions.

**Comment by WTFGEDelphia** [comment]
> AKAIK, Netty 3 reached EOL. Consider upgrading to latest versions.

but we use akka-2.5.23 , the dependency of config version is 3.10.6.Final

**Comment by hyperxpro** [comment]
Now this is a problem because excluding Akka Netty 3 dependency and adding Netty 4.1.X dependency won't work in 1 shot.

**Comment by WTFGEDelphia** [comment]
I find some java Bug :
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8230977
so how to fixed the problem in netty 3.10.6.Final ?

**Comment by hyperxpro** [comment]
Netty 3 is no longer maintained. So if there is a problem in Netty 3.10.6.Final. we can't do anything.

**Comment by normanmaurer** [comment]
netty 3 is EOL for years so there is not much we can do.
