### ISSUE TITLE
DelimiterBasedFrameDecoder Is this a bug？

### ISSUE THREAD

**Issue by GeXin666** [netty/netty#10338]
### Netty version
4.1.49

DelimiterBasedFrameDecoder code segment

`if (minDelim != null) {
            int minDelimLength = minDelim.capacity();
            ByteBuf frame;

            if (discardingTooLongFrame) {
                // We've just finished discarding a very large frame.
                // Go back to the initial state.
                discardingTooLongFrame = false;
                buffer.skipBytes(minFrameLength + minDelimLength);

                //Whether the length of this byte should be added？？？？
                //int tooLongFrameLength = this.tooLongFrameLength + minFrameLength + minDelimLength;???????????
                int tooLongFrameLength = this.tooLongFrameLength;
                this.tooLongFrameLength = 0;
                if (!failFast) {
                    fail(tooLongFrameLength);
                }
                return null;
            }..........`

**Comment by normanmaurer** [comment]
@GeXin666 can you provide a unit test ?
