### ISSUE TITLE
Support for Circuit Breaker to prevent OOM error

### ISSUE THREAD

**Issue by boicehuang** [netty/netty#10334]
@trustin  @normanmaurer 
Hi, I am a user of Elasticsearch which uses Netty in the network layer. Currently, if we are sending high volumes of messages to Netty in elasticsearch in a very short time, faster than it can process, heap memory would be filled with Netty buffer and causes an OOM error before messages reach Elasticsearch. 

Elasticsearch provides a [Circuit Breaker](https://www.elastic.co/guide/en/elasticsearch/reference/current/circuit-breaker.html) that specifies the total amount of memory that can be used. It greatly reduces the risk of OOM by stopping memory allocation when its memory usage reaches up to 95%. But it can't stop Netty from accepting incoming message and running out of memory in the network layer.

Does Netty have a plan to support Circuit Breaker to prevent operations from causing an OutOfMemoryError?

**Comment by normanmaurer** [comment]
Limit the amount of messages read can easily be archived by stop reading. This cane be done by toggle `AUTO_READ` to false until the application is ready to accept messages again. There is nothing special here needed by netty.

**Comment by boicehuang** [comment]
Thanks for your comment, @normanmaurer. Is there any way to limit the amount of Chunk?

**Comment by normanmaurer** [comment]
@boicehuang if toggling AUTO_READ was done too late then you must toggle it earlier. There is not much more that we can do here... Either you need to stop writing if the Channel is not writable and continue writing once it becomes writable again or you need to stop reading if you accept data faster then you can process it. Most of the times you want to do a mix of both.

**Comment by zhenjunMa** [comment]
maybe use `AUTO_READ ` to  limit used memory by READ
use `WriteBufferWaterMark` to limit used memory by WRITE

**Comment by normanmaurer** [comment]
Let me close this one for now

**Comment by boicehuang** [comment]
Thanks, @normanmaurer.  I understood and still had a question.
By toggling AUTO_READ, we can put a limit on bulk data requests to prevent used memory from growing up.  But is it possible or any way to not restrict cluster coordination requests, such as vote/join requests, to keep nodes always connected and cluster intact while rejecting bulk data requests at the same time?

**Comment by normanmaurer** [comment]
@boicehuang you need to ask on the elastic search project for this. Netty is just the framework used for networking and how they use it and how they implement safe-guards is up to them.
