### ISSUE TITLE
How do I determine if I sent successfully

### ISSUE THREAD

**Issue by HonestMan123** [netty/netty#10343]
future.isSuccess() return success when I was disconnected from the network

```java
mSocketChannel.writeAndFlush(msg).addListener((ChannelFutureListener) future -> {
            if (future.isSuccess()) {
                
            } else {
                
            }
        });
```
### Netty version
4.1.48.Final
### JVM version (e.g. `java -version`)
1.8.0_151
### OS version (e.g. `uname -a`)
Android 7.0

**Comment by amizurov** [comment]
Hi, future.isSuccess() mean only successful flash to socket it doesn't mean that any data was delivered to client. You need implement your own ping-pong, heart-beating mechanism to detect problem with network communication.

**Comment by HonestMan123** [comment]
ok，thank you
