### ISSUE TITLE
Multithreading for WorkerGroup doesn't work

### ISSUE THREAD

**Issue by oleg-sta** [netty/netty#10352]
Hi, please check the issue, not sure if the behaviour is expected.

### Expected behavior
When workergroup created with multiple number of thread it is expected that handling will be parallel as written in the https://netty.io/4.1/api/io/netty/channel/ChannelPipeline.html

### Actual behavior
handling in serial. In the logs we see that messages handled on by one with 1 second interval

> Server received: Hello new message! index 0 Thread name defaultEventExecutorGroup-4-1 time: Wed Jun 17 20:28:04 BST 2020
> Server received end: Hello new message! index 0
> Server received: Hello new message! index 1 Thread name defaultEventExecutorGroup-4-1 time: Wed Jun 17 20:28:05 BST 2020
> Server received end: Hello new message! index 1
> Server received: Hello new message! index 2 Thread name defaultEventExecutorGroup-4-1 time: Wed Jun 17 20:28:06 BST 2020
> Server received end: Hello new message! index 2
> Server received: Hello new message! index 3 Thread name defaultEventExecutorGroup-4-1 time: Wed Jun 17 20:28:07 BST 2020
> 

Is it issue or the behaviour is correct?

### Steps to reproduce
link to the code provided

### Minimal yet complete reproducer code (or URL to code)
https://github.com/oleg-sta/NettyExample/blob/master/src/main/java/com/example/netty/Main.java

### Netty version
4.1.42

### JVM version (e.g. `java -version`)
java version "14.0.1" 2020-04-14

### OS version (e.g. `uname -a`)
Darwin C02ZQ2D6MD6R 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

**Comment by zhenjunMa** [comment]
`ChannelPipeline addLast(EventExecutorGroup group, ChannelHandler... handlers)`
means when server get a connection, it will pick one worker from the group and `bind` this worker to this connection to process follow up data.  
not means pick one worker every time when a connection get a request.

**Comment by normanmaurer** [comment]
@oleg-sta as @zhenjunMa said... the reason for this is that most protocols need some sort of ordering which can't be guaranteed if we just pick a new thread for each message. That said you can archive what you want by using the `UnorderedThreadPoolEventExecutor` when adding a handler to the pipeline

**Comment by oleg-sta** [comment]
Maybe an example in the documentation should be changed: https://netty.io/4.1/api/io/netty/channel/ChannelPipeline.html?
