### ISSUE TITLE
Netty Pipeline processes flush operation out of order

### ISSUE THREAD

**Issue by jwils** [netty/netty#10353]
During an attempted upgrade of netty we ran into an issue starting in version 4.1.35 it appears that sometimes channel.flush() ends up getting processed before a channel.write() even when called after the write(). These actions happen on a thread outside the netty pipeline.

Calling channel.writeAndFlush() seems to fix the issue, but not sure what else might be impacted.

### Expected behavior

on an thread external to the netty pipeline:
```
channel.write()
channel.flush()
```
works the same as
```
channel.writeAndFlush()
```

### Actual behavior
channel.flush() after a few channel.write() operations may get processed by the pipeline before the writes, causing the connection to hang without flushing data. 

### Steps to reproduce
I assume the trigger here is writing to the channel from an outside thread.

### Minimal yet complete reproducer code (or URL to code)
Unfortunately I can't share the current code that causes it, I haven't yet come up with a minimal demo.

### Netty version
works in 4.1.34, 
broken in 4.1.35

### JVM version (e.g. `java -version`)
1.8.0_202

### OS version (e.g. `uname -a`)
macos Catalina 10.15.5
Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

**Comment by aikar** [comment]
Feels pretty expected, as all this does is invoke 2 schedules to the event loop, and each can end up on a different thread.

If you want to send many writes and a single flush, you should jump into the event loop first then send it all on the same thread.

**Comment by normanmaurer** [comment]
@aikar are there any `ChannelHandler`s added to the `ChannelPipeline` with a `EventExecutor` ? Also are the operations on the `Channel` (`write` and `flush`) be done from the same calling `Thread` ?

**Comment by aikar** [comment]
@normanmaurer im not the one with the issue :) That's @jwils 

Unless my understanding of calling .flush() separately does have some magic that would ensure it gets on the same event loop thread.

**Comment by jwils** [comment]
@normanmaurer Some channels are added with EventExecutors. The operations on the channel are all called from a single thread. 

My understanding is we could optimize this by trying to put all the calls on the event executor, but I'd expect actions on the pipeline to be executed in order, regardless of where they are called from. My understanding is that each channel has only 1 executor thread that should be executing these actions in the order queued. 

Let me know if that assumption is incorrect. Either way the change in behavior in 4.1.35 broke some of our expectations. Clarity on expected behavior would also help us determine next steps.

**Comment by normanmaurer** [comment]
@jwils I see... is the code OSS by any chance and so I could have a look ?

**Comment by jwils** [comment]
Unfortunately it's not and it's a tangled mess. I haven't reproduced it in sharable code. Can you clarify though, the expected behavior is that a flush will happen after the writes regardless of what thread calls them? I can spend some more time trying to reproduce.

**Comment by normanmaurer** [comment]
@jwils if the method returns before you call the other this is general speaking true. There is one possible gotcha here... Even if you call a method from outside the `EventLoop` but you are currently call another method in the `EventLoop` then the method call done within the `EventLoop` will happen first.

**Comment by jwils** [comment]
Okay that is was I assumed. Just checking based on @aikar's comment. 

I am not able to reproduce and the app has many querks so I am not sure what pipeline config causes the issue. I can try next week to see if I can recreate

**Comment by normanmaurer** [comment]
@jwils any updates ?

**Comment by normanmaurer** [comment]
@jwils so did you solve this ?

**Comment by jwils** [comment]
Hey Norm Kind of, We worked around it by hacking in the updated http cookie code back to our version. I believe there is still some race condition and we can't upgrade our version of netty until we figure out the root cause. I haven't been able to find the time to get a reproducible example, and I've moved on to other projects. Closed it so you didn't have the pending ticket without enough details.

Happy to reopen if you want the bug tracked so someone can investigate later. Apologies for not being able to more helpful in providing a reproducible example or tracking down the root cause.

**Comment by wangzihaogithub** [comment]
I had exactly the same situation, please don't close this issue

**Comment by wangzihaogithub** [comment]
In non-IO thread processing, must be able to reproduce.

**Comment by wangzihaogithub** [comment]
hi,  I found the problem and fixed it. Can you help with the merging.  thanks.

**Comment by efiala** [comment]
Looking at the difference between `4.1.34.Final` and `4.1.35.Final` where @jwils reported the issue first occurred, I notice in `AbstractChannleHandlerContext` that the signature of `findContextOutbound` has changed to include an `int mask` parameter. The body of that method has changed as follows:
```
- private AbstractChannelHandlerContext findContextOutbound() {
+ private AbstractChannelHandlerContext findContextOutbound(int mask) {
      AbstractChannelHandlerContext ctx = this;
      do {
          ctx = ctx.prev;
-     } while (!ctx.outbound);
+     } while ((ctx.executionMask & mask) == 0);
  }
```

In the `write` method we see that we get an executor from the channel handler context via `EventExecutor executor = next.executor();`. `next` was previously was just whatever matched `ctx.outbound` for both `flush` and `write`, but is now potentially different for these: 
```
    private void write(Object msg, boolean flush, ChannelPromise promise) {
        ObjectUtil.checkNotNull(msg, "msg");
        try {
            if (isNotValidPromise(promise, true)) {
                ReferenceCountUtil.release(msg);
                // cancelled
                return;
            }
        } catch (RuntimeException e) {
            ReferenceCountUtil.release(msg);
            throw e;
        }

-       AbstractChannelHandlerContext next = findContextOutbound();
+       final AbstractChannelHandlerContext next = findContextOutbound(flush ?
+               (MASK_WRITE | MASK_FLUSH) : MASK_WRITE);
        final Object m = pipeline.touch(msg, next);
        EventExecutor executor = next.executor();
        if (executor.inEventLoop()) {
            if (flush) {
                next.invokeWriteAndFlush(m, promise);
            } else {
                next.invokeWrite(m, promise);
            }
        } else {
            final AbstractWriteTask task;
            if (flush) {
                task = WriteAndFlushTask.newInstance(next, m, promise);
            }  else {
                task = WriteTask.newInstance(next, m, promise);
            }
            if (!safeExecute(executor, task, promise, m)) {
                // We failed to submit the AbstractWriteTask. We need to cancel it so we decrement the pending bytes
                // and put it back in the Recycler for re-use later.
                //
                // See https://github.com/netty/netty/issues/8343.
                task.cancel();
            }
        }
    }
```

Because the executor may now be different, then sequential `write` and `flush` invocations made in the same thread may be enqueued on different `executor`s. 

Though note that if the `flush` parameter of the `write` method is `true` as is the case for `writeAndFlush`, then it will potentially (and possibly always, depending on the ordering of the contexts in the context chain) select the same context as in the pure `flush` case given that the mask in that case is `MASK_WRITE | MASK_FLUSH`.

This may help explain why a `write` might be executed after a `flush` even within the same thread, but that a `writeAndFlush` mitigates the issue.

https://github.com/netty/netty/compare/netty-4.1.34.Final...netty-4.1.35.Final#diff-14b9f0e2bf3471c6dc6495bf8c2689e926ddc8f63b1a9608191497977f047a66R775
