### ISSUE TITLE
A little bit of advice

### ISSUE THREAD

**Issue by pengzhengfa** [netty/netty#10358]
Can you write official documents more perfectly? Some core documents seem to be missing

**Comment by ona993** [comment]
Wow, that's rude

**Comment by pengzhengfa** [comment]
Too much, too much

**Comment by normanmaurer** [comment]
If you think there is anything to improve (and yes I am sure there is plenty to improve) open a PR with the improvements. This is an OSS project and so contributions are mostly welcome
