### ISSUE TITLE
create SslHandler for mqtt protocol

### ISSUE THREAD

**Issue by BehzadArabi** [netty/netty#10366]
Hi,
I'm creating an mqtt client via netty for my customer in android, 
My client should support SSL otherwise the mqtt server will deny the my requests
I found a port of netty for microsoft .net
https://github.com/Azure/DotNetty/blob/dev/src/DotNetty.Handlers/Tls/TlsHandler.cs
is there any similar code available for java?

**Comment by normanmaurer** [comment]
Not that I am aware of .... we only have the `SslHandler`
