### ISSUE TITLE
SRCCLR-SID-22277

### ISSUE THREAD

**Issue by thunderbird** [netty/netty#10369]
I have SRCCLR-SID-22277 being flagged up by a veracode / sourceclear scan for vulnerability to man in the middle attacks: https://sca.analysiscenter.veracode.com/vulnerability-database/security/sca/vulnerability/sid-22277/summary

Details are not great, but I'm making sure this is registered here as I've found no reference. Looks like the bug is down to netty handler not using a SSL Engine that does not verify certificate hostnames when establishing connections with clients by default

**Comment by hyperxpro** [comment]
Duplicate of #10362 #9930
