### ISSUE TITLE
`ResourceLeakDetectorFactory.newResourceLeakDetector(Class, int)` ignores sampling interval.

### ISSUE THREAD

**Issue by trustin** [netty/netty#10378]
### Expected behavior

`ResourceLeakDetectorFactory.newResourceLeakDetector(Class, int)` should use the second parameter as the sampling interval of the newly created `ResourceLeakDetector`.

### Actual behavior

`ResourceLeakDetector.SAMPLING_INTERVAL` is used, i.e. cannot customize the sampling interval without using the deprecated `newResourceLeakDetector(Class, int, long)`.

### Netty version

4.1.50

**Comment by normanmaurer** [comment]
@trustin time for a PR ;)
