### ISSUE TITLE
ProtobufVarint32FrameDecoder is not annotated shareable but documentation says otherwise

### ISSUE THREAD

**Issue by AnveshMora** [netty/netty#10371]
### Expected behavior
Should be able to remove or add to pipeline dynamically
### Actual behavior
Fails with below exception:
```
03:27:40.208 [nioEventLoopGroup-2-4] WARN io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0xef7d30b3]
io.netty.channel.ChannelPipelineException: io.netty.handler.codec.protobuf.ProtobufVarint32FrameDecoder is not a @Sharable handler, so can't be added or removed multiple times.
	at io.netty.channel.DefaultChannelPipeline.checkMultiplicity(DefaultChannelPipeline.java:588)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:199)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:192)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)

```
### Steps to reproduce
1. Main class(Client) to connect to a server and use channel future listener to attach to bootstrap connect
2. Make sure server is down fails to connect to server for the first time
3. Make Channel future listner used in step 1 to connect to same server using clientbootstrap created in step 1 (you can't use channelfuture available, because channel is already closed)

Refer to : https://github.com/netty/netty/issues/10370 for more implementation
### Minimal yet complete reproducer code (or URL to code)
https://netty.io/4.0/api/io/netty/handler/codec/protobuf/ProtobufVarint32FrameDecoder.html
### Netty version
4.1.12

**Comment by AnveshMora** [comment]
I've addressed 10370, by making  "ProtobufVarint32FrameDecoder " and it's parent Class "ByteToMessageDecoder". "ByteToMessageDecoder" shareable. 

Because above classes are not shareable, every time code try to reconnect using boostrap, initializer class fails to add handlers in pipeline results in "ctx.close()" and no handlers.

Considering this scenario, we might have to make ByteToMessageDecoder and subclasses shareable and remove explicit check in ByteToMessageDecoder.

**Comment by normanmaurer** [comment]
@AnveshMora These are not sharable by design as these keep state... You will need to create a new instance of these everytime you create a new Channel. 

I am also not seeing how the documentation could be misleading here in `ProtobufVarint32FrameDecoder`.

**Comment by AnveshMora** [comment]
@normanmaurer , That makes sense. I missed that. Btw what kind of state information is stored as part 
`ProtobufVarint32FrameDecoder`

**Comment by normanmaurer** [comment]
@AnveshMora the received bytes as we may receive fragemented packets etc
