### ISSUE TITLE
X509TrustManager with OPEN_SSL provider is not wrapped with hostname verification if Conscrypt is inserted in the first place

### ISSUE THREAD

**Issue by voidzcy** [netty/netty#10374]
This is an edge case for the fix of #6664.

When Conscrypt is inserted as the first security provider while OPEN_SSL is specified in building `SslContext`, hostname verification is not performed.

#8307 adds the `OpenSslX509TrustManagerWrapper` that tries to wrap an X509TrustManager with JDK's hostname verification logic (a.k.a., [AbstractKeyManagerWrapper](http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/cadea780bc76/src/share/classes/sun/security/ssl/SSLContextImpl.java#l1312)). It [assumes the default SSLContext provider is JDK](https://github.com/netty/netty/blob/7cf69022d48d123ac9f2920729613766f08f0874/handler/src/main/java/io/netty/handler/ssl/OpenSslX509TrustManagerWrapper.java#L153-L155). If it is actually not (e.g., Conscrypt), no `AbstractKeyManagerWrapper` will be found and the original X509TrustManager will not get wrapped (thus, no hostname verification). This could potentially be a security issue. To avoid such a miss, we may want to explicitly get JDK's SSLContext for reusing its code.

**Comment by normanmaurer** [comment]
@voidzcy are you interested in providing a fix ?

**Comment by normanmaurer** [comment]
@voidzcy see https://github.com/netty/netty/pull/10375... PTAL
