### ISSUE TITLE
class ByteToMessageDecoder‘s method callDecode fall into a dead cycle

### ISSUE THREAD

**Issue by melowYX** [netty/netty#10379]
My coder is inherited from ByteToMessageDecoder , I need to deal with a message: determine the next message length according to the content in a fixed interval of the message,so I will use the readablebytes() to determine whether there is enough data.If there is not so much data, I will use the resetReaderIndex() and wait for the next trigger.code just like:

```java
if(in.readableBytes()<num1){
    return;
}   
byte [] data1 = new byte[num1];
in.readBytes(data1, 0, num1);
if(in.readableBytes()<num2){
    in.resetReaderIndex();
    return;
}
// The variable num2 is calculated from a location in the array data1
```

If it is a normal message, but if other content is added after the message, and its length is just greater than num1 and less than num1 + num2, it will fall into a while loop in calldecode() and cannot exit, thus executing firechannelread() multiple times and repeating the subsequent logic.
    When I found this problem, I find that I couldn't modify the processing logic due to the message format. I tried to solve this problem by calling setSingledecode(), but I found that I still couldn't jump out of the while loop from the calldecode().
    So far my solution is to remove the coder from the pipeline after decode is complete: ctx. pipeline(). remove ("MyCoder") 
  
Netty version : 4.1.36.Final
JVM version: JDK8U101-B13
OS version:  AIX 7.2

**Comment by normanmaurer** [comment]
@melowYX can you share a reproducer using `EmbeddedChannel` and your decoder ?

**Comment by melowYX** [comment]
For some reason I can't give you the detailed code, this is the simplified processing code

```java
public class MyCoder extends ByteToMessageDecoder {   
     @Override    
     protected final void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) throws Exception{        
                 if(in.readableBytes() < 4){
                       return;        
                }        
                byte[] data1 = new byte[4];        
                in.readBytes(data1, 0, 4);        
                int num = Integer.valueOf(new String(data1));        
                if(in.readableBytes() < num){            
                       in.resetReaderIndex();            
                       return;        
                }        
                byte[] data2 = new byte[num];        
                in.readBytes(data2, 0, num);        
                String s2 = new String(data2);        
                System.out.println(s2);        
                out.add(s2);    
       }
}


public class TestMyCoder {    
    @Test    
    public void test(){        
        ByteBuf input = Unpooled.buffer();        
        byte[] req = "0003123456789".getBytes();        
        for(byte data : req){            
            input.writeByte(data);        
        }        
        EmbeddedChannel testChannel = new EmbeddedChannel(new MyCoder());        
        testChannel.writeInbound(input);    
    }
}
```

This code will not exit in the while loop in class ByteToMessageDecoder‘s method callDecode.You will see the “123” printed over and over again. This could easily lead to an attack on my system

**Comment by zhenjunMa** [comment]
```
public class MyCoder extends ByteToMessageDecoder {   
     @Override    
     protected final void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) throws Exception{        
                 if(in.readableBytes() < 4){
                       return;        
                }        
                byte[] data1 = new byte[4];        
                in.readBytes(data1, 0, 4);        
                int num = Integer.valueOf(new String(data1));        
                if(in.readableBytes() < num){            
                       in.resetReaderIndex();            
                       return;        
                }        
                byte[] data2 = new byte[num];        
                in.readBytes(data2, 0, num);       
 -----------------------------------------
                //add this here, or when you call in.resetReaderIndex();  the readIndex will set to 0, so over and over again
                in.markReaderIndex();
 -----------------------------------------
                String s2 = new String(data2);        
                System.out.println(s2);        
                out.add(s2);    
       }
}
```

**Comment by melowYX** [comment]
I konw the reason，but i want netty to process it(in.markReaderIndex()). my code just read the data and send to next handler

**Comment by melowYX** [comment]
> ```
> public class MyCoder extends ByteToMessageDecoder {   
>      @Override    
>      protected final void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) throws Exception{        
>                  if(in.readableBytes() < 4){
>                        return;        
>                 }        
>                 byte[] data1 = new byte[4];        
>                 in.readBytes(data1, 0, 4);        
>                 int num = Integer.valueOf(new String(data1));        
>                 if(in.readableBytes() < num){            
>                        in.resetReaderIndex();            
>                        return;        
>                 }        
>                 byte[] data2 = new byte[num];        
>                 in.readBytes(data2, 0, num);       
>  -----------------------------------------
>                 //add this here, or when you call in.resetReaderIndex();  the readIndex will set to 0, so over and over again
>                 in.markReaderIndex();
>  -----------------------------------------
>                 String s2 = new String(data2);        
>                 System.out.println(s2);        
>                 out.add(s2);    
>        }
> }
> ```
