### ISSUE TITLE
The number of TCP connections is increasing.

### ISSUE THREAD

**Issue by hcl78184889** [netty/netty#10394]
![85951174-f336b000-b993-11ea-9a42-ff0b0f7c90f0](https://user-images.githubusercontent.com/6574953/86758956-cad74180-c076-11ea-9a53-fe929f4ad0a3.png)

When using a sample Webclient to retrive a remote restful API, the number of TCP connections is not increasing unless restart.

Netty 4.1.50

java 1.8

centos 6.9

**Comment by normanmaurer** [comment]
sorry but you will need to provide more details to receive help.

**Comment by hcl78184889** [comment]
When using spring cloud gateway, it happens. I think this bug's root cause is not Gateway, when using a sample Webclient to retrive a remote restful API, this happens.

The dependency netty version is 4.1.50

The test code:

@RestController
@Slf4j
public class WebClientController {

    @Autowired
    private WebClient.Builder webClientBuilder;

    @PostMapping(value = "/wb")
    public Mono<String> wbTest(@PathVariable(required = false) String action) {
        return webClientBuilder.build().get().uri("http://remoteIP:remotePort/privaters/jwks/pub")
                .retrieve()
                .bodyToMono(String.class);
    }

}

After a few requst, using lsof -p XXX to check, then shows scokets leaked!

java    10823 ircp   32u     sock                0,7       0t0 154700740 protocol: TCP
java    10823 ircp   33u     sock                0,7       0t0 154701211 protocol: TCP
java    10823 ircp   34u     sock                0,7       0t0 154700776 protocol: TCP
java    10823 ircp   35u     sock                0,7       0t0 154700777 protocol: TCP
java    10823 ircp   36u     sock                0,7       0t0 154700778 protocol: TCP
java    10823 ircp   37u     sock                0,7       0t0 154701301 protocol: TCP
java    10823 ircp   38u     sock                0,7       0t0 154701304 protocol: TCP
java    10823 ircp   39u     sock                0,7       0t0 154701307 protocol: TCP
java    10823 ircp   40u     sock                0,7       0t0 154701837 protocol: TCP

I guess this bug should be caused by Netty 4.1.50.

**Comment by normanmaurer** [comment]
You will need to provide a reproducer if you think there is any issue... Without this we really can't help. Also keep in mind that Netty itself mostly provide codecs everything else is handled by the user of Netty.

**Comment by hcl78184889** [comment]
OK, thanks

**Comment by violetagg** [comment]
@hcl78184889 Please update Reactor Netty to version 0.9.9.RELEASE there was a regression related to opened FDs.
Spring Gateway and WebClient do not use Netty directly.

**Comment by hcl78184889** [comment]
OK,thinks

**Comment by normanmaurer** [comment]
let me close this one then
