### ISSUE TITLE
StreamException in CORS Pre-flight with HTTP/2

### ISSUE THREAD

**Issue by gustavonalle** [netty/netty#10390]
### Expected behavior

CORS Pre-flights requests correctly handled by the ```CorsHandler``` with a HTTP/2 pipeline

### Actual behavior

Client hangs, exception is thrown by Netty:
```
io.netty.handler.codec.http2.Http2Exception$StreamException: HTTP/2 to HTTP layer caught stream reset
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:147)
	at io.netty.handler.codec.http2.InboundHttp2ToHttpAdapter.onRstStreamRead(InboundHttp2ToHttpAdapter.java:289)
	at io.netty.handler.codec.http2.Http2FrameListenerDecorator.onRstStreamRead(Http2FrameListenerDecorator.java:59)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onRstStreamRead(DefaultHttp2ConnectionDecoder.java:406)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readRstStreamFrame(DefaultHttp2FrameReader.java:516)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:260)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:174)
	at io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)19:02:12,558
```

The client is ```OkHttp``` and it prints the following exchange:
```
19:08:25,516 DEBUG (OkHttp https://localhost:34513/...) [Http2] >> 0x00000003   110 HEADERS       END_HEADERS
19:08:25,516 DEBUG (OkHttp localhost) [Http2] << 0x00000000     6 SETTINGS      
19:08:25,516 DEBUG (OkHttp https://localhost:34513/...) [Http2] >> 0x00000003     0 DATA          END_STREAM
19:08:25,517 DEBUG (OkHttp localhost) [Http2] << 0x00000000     0 SETTINGS      ACK
19:08:25,517 DEBUG (OkHttp localhost ACK Settings) [Http2] >> 0x00000000     0 SETTINGS      ACK
19:08:25,519 DEBUG (OkHttp localhost) [Http2] << 0x00000002   437 HEADERS       END_STREAM|END_HEADERS|PRIORITY
19:08:25,520 DEBUG (OkHttp localhost Push Headers[2]) [Http2] >> 0x00000002     4 RST_STREAM    
```

### Steps to reproduce

I have a server pipeline which has the main components like the following:

```java

// SSL, ALPN omitted for brevity 
// . . .
DefaultHttp2Connection connection = new DefaultHttp2Connection(true);

InboundHttp2ToHttpAdapter listener = new InboundHttp2ToHttpAdapterBuilder(connection)
            .propagateSettings(true)
            .validateHttpHeaders(false)
            .maxContentLength(maxContentLength())
            .build();

HttpToHttp2ConnectionHandler http2ConnectionHandler = new HttpToHttp2ConnectionHandlerBuilder()
            .frameListener(listener)
            .connection(connection)
            .build();
      
pipeline.addLast(http2ConnectionHandler);
pipeline.addLast(new CorsHandler(corsConfigs));
// MyCustomHandler deals with FullHttpRequest objects
pipeline.addLast(new MyCustomHandler());

```

The pipeline works fine untill adding the CorsHandler, then it hangs on the pre-flight requests. Maybe I am overlooking something in this setup?

### Minimal yet complete reproducer code (or URL to code)

// TODO

### Netty version

4.1.50.Final

### JVM version (e.g. `java -version`)

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

### OS version (e.g. `uname -a`)

Linux 5.6.16-200.fc31.x86_64 #1 SMP Thu Jun 4 18:07:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gustavonalle** [comment]
I found the problem: ```CorsHandler```, during pre-flight requests (basically an  ```OPTIONS``` with some headers), writes 
the ```HttpResponse``` directly to the pipeline, preventing ```MyCustomHandler``` to be called. ```MyCustomHandler```, in the setup described above, sets the ```x-http2-stream-id``` from the request into the response, and this work is not done by the CorsHandler.

**Comment by normanmaurer** [comment]
@gustavonalle not sure I understand... can you give some more details here ? From what I understood this could be solved by putting your handler in front of it ?

**Comment by gustavonalle** [comment]
> could be solved by putting your handler in front of it 

Not quite, since my handler doesn't handle OPTION request, responding with forbidden, and preventing the CorsHandler to handle the pre-flight. What I can try is to extract this behaviour of copying the ```x-http2-stream-id``` into a separate handler and put it in front of both CorsHandler and MyCustomHandler.

So I guess this is not a bug: it is rather a side effect of my particular setup of using the same ```SimpleChannelInboundHandler``` based on FullHttpRequest and FullHttpResponse for both HTTP/1 and HTTP/2 pipelines...
