### ISSUE TITLE
milo-netty-wheel-timer Question

### ISSUE THREAD

**Issue by YW767486516** [netty/netty#10398]
Hi,
When I use JCONSOLE to check the thread, I find that the waiting number of milo-netty-wheel-timer has been increasing, and the speed is very fast. Could it affect my program?

`Name: milo-netty-wheel-timer
Status: TIMED_WAITING
Total blocked: 0, total waited: 913,277,651

Stack trace:
java.base@11.0.4/java.lang.Thread.sleep(Native Method)
app//io.netty.util.HashedWheelTimer$Worker.waitForNextTick(HashedWheelTimer.java:579)
app//io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:478)
java.base@11.0.4/java.lang.Thread.run(Thread.java:834)`

Best Regards

### Netty version
4.1.39.Final
### JVM version (e.g. `java -version`)
java 11.0.4
### OS version (e.g. `uname -a`)
windows2012R2 i5 x86_64

**Comment by normanmaurer** [comment]
Please provide more details on who is creating the timer + a reproducer

**Comment by YW767486516** [comment]
`import io.netty.channel.Channel;
import io.netty.channel.ChannelDuplexHandler;
import io.netty.channel.ChannelHandlerContext;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ResponseBody;

@ControllerAdvice
@ResponseBody
public class OpcUaException extends ChannelDuplexHandler {

    @Override
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
        Channel channel = ctx.channel();

        if(channel.isActive())ctx.close();
    }
}`

**Comment by YW767486516** [comment]
I searched the code, only netty is directly referenced here. After I commented the code, the problem also exists.

**Comment by YW767486516** [comment]
`    public UaStackClientConfig build() {
        Preconditions.checkNotNull(endpoint, "endpoint must be non-null");

        if (executor == null) {
            executor = Stack.sharedExecutor();
        }
        if (eventLoop == null) {
            eventLoop = Stack.sharedEventLoop();
        }
        if (wheelTimer == null) {
            **wheelTimer = Stack.sharedWheelTimer();**
        }

        return new UaStackClientConfigImpl(
            endpoint,
            keyPair,
            certificate,
            certificateChain,
            certificateValidator,
            encodingLimits,
            executor,
            eventLoop,
            wheelTimer,
            connectTimeout,
            acknowledgeTimeout,
            requestTimeout,
            messageLimits,
            channelLifetime
        );
    }`

`    /**
     * @return a shared {@link HashedWheelTimer}.
     */
    public static synchronized HashedWheelTimer sharedWheelTimer() {
        if (WHEEL_TIMER == null) {
            ThreadFactory threadFactory = r -> {
                Thread thread = new Thread(r, "milo-netty-wheel-timer");
                thread.setDaemon(true);
                return thread;
            };

            WHEEL_TIMER = new HashedWheelTimer(threadFactory);
        }

        return WHEEL_TIMER;
    }`

**Comment by normanmaurer** [comment]
I am really not sure what you are asking about here... So `HashedWheelTimer` will basically block for some amount of time and then process the next slot of the wheel. This will be done in an endless loop so its expected that you have wait time.

**Comment by normanmaurer** [comment]
closing as no response
