### ISSUE TITLE
After using this LengthFieldBasedFrameDecoder, it leads to Chinese garbled

### ISSUE THREAD

**Issue by nongchangzhu** [netty/netty#10393]
### Expected behavior

{"name":"nana","age":"18","counts":"1","counts2":{"lala":"我是中国人"}}

### Actual behavior

{"name":"nana","age":"18","counts":"1","counts2":{"lala":"我是�}

### Minimal yet complete reproducer code (or URL to code)

//public class Decoder extends ByteToMessageDecoder {
public class Decoder extends LengthFieldBasedFrameDecoder {

	private int HEADER_SIZE = 6;

	public Decoder(int maxFrameLength, int lengthFieldOffset, int lengthFieldLength, int lengthAdjustment, int initialBytesToStrip, boolean failFast,int HEADER_SIZE) {
		super(maxFrameLength, lengthFieldOffset, lengthFieldLength, lengthAdjustment, initialBytesToStrip, failFast);

		this.HEADER_SIZE = HEADER_SIZE;
	}

	@Override
	public  Object decode(ChannelHandlerContext ctx, ByteBuf in) throws Exception {

		ByteBuf in2 = in.copy();
		//读取body
		byte []bytes2 = new byte[in2.readableBytes()];
		in2.readBytes(bytes2);

               System.out.println("--------1-------"+ new String(bytes2, CharsetUtil.UTF_8));
               //{"name":"nana","age":"18","counts":"1","counts2":{"lala":"我是中国人"}}

		
		in2.clear();
		in2.release();

		in = (ByteBuf) super.decode(ctx,in);
		
		if(in == null){
			return null;
		}

		if(in.readableBytes()<HEADER_SIZE){
			throw new Exception("字节数不足");
		}
		byte type = in.readByte();
		byte flag = in.readByte();
		int length = in.readInt();

		if(in.readableBytes()!=length){
			throw new Exception("标记的长度不符合实际长度");
		}

		//读取body
		byte []bytes = new byte[in.readableBytes()];
		in.readBytes(bytes);
		//in.readBytes(bytes,0,in.readableBytes());

		System.out.println("------------2-------------"+new String(bytes, CharsetUtil.UTF_8));
               //  {"name":"nana","age":"18","counts":"1","counts2":{"lala":"我是�}

		return new MessageContent(type,flag,length,new String(bytes));

**Comment by zhenjunMa** [comment]
```
// instead with new String(bytes, StandardCharsets.UTF_8)?
System.out.println("------------2-------------"+new String(bytes));
```

**Comment by nongchangzhu** [comment]
even if this "StandardCharsets.UTF_8" is added, it is still garbled， 

I have tested it and it is related to this line of code: "in = (ByteBuf) super.decode(ctx,in)"

**Comment by nongchangzhu** [comment]
> ```
> // instead with new String(bytes, StandardCharsets.UTF_8)?
> System.out.println("------------2-------------"+new String(bytes));
> ```


even if this "StandardCharsets.UTF_8" is added, it is still garbled，

I have tested it and it is related to this line of code: "in = (ByteBuf) super.decode(ctx,in)"
