### ISSUE TITLE
io.netty.ByteBuf writeBytes(java.nio.ByteBuffer src) APIclarification

### ISSUE THREAD

**Issue by shashanka981** [netty/netty#10404]
This is a question, not an issue

I wanted to know how many memory copies are involved in the below writeBytes API from io.netty.buffer.ByteBuf Interface. Will the data gets copied to an intermediate byte array before getting transferred to Bytebuf ? or will the data directly gets copied from backing array of nio.ByteBuffer to ByteBuf ? or will it depend on type of nio.ByteBuffer supplied or type of implementation of ByteBuf used ?

Note i am supplying a read-only ByteBuffer as a parameter.

API writeBytes(java.nio.ByteBuffer src)

![Capture](https://user-images.githubusercontent.com/24698946/87458733-069a7a00-c628-11ea-81da-255dd7830e2b.PNG)

**Comment by normanmaurer** [comment]
@shashanka981 it totally depends on the implementation. That said we try to reduce the number of memory copies as much as possible in Netty.
