### ISSUE TITLE
Netty Client

### ISSUE THREAD

**Issue by github-big-cheng** [netty/netty#10406]
I create this project(https://github.com/github-big-cheng/netty-protostuff.git) when I learning Netty,
I want to code a utility class NettyClient, it can work for http, rpc with a few config,
it will build a pool with org.apache.commons.commons-pool2 when accecpt a  new group of host and port, 
but when i using a threadPool with 10 threads to run it, it does not work well.
I think it's my misuse to use Netty, but there's too little information about my exceptions on the Internet, so I went here for some helps.
Looking forward to your kind reply! Thanks very much...

### Expected behavior

It can works well in highly High concurrency environment

### Actual behavior

1. It looks like blocked in rpc model...
2. Also not work well in http model...

### Steps to reproduce

when rpc test:
step 1. run ServerMain.java
step 2. run RpcClientMain.java
It looks like blocked, but I can't find the problems...
sometimes, it stoped with exception as 'throw exception:DefaultChannelPromise@447aeba5(incomplete)'

when http test
step 1. run HttpCLientMain.java
there are some exceptions like this:
io.netty.channel.ChannelPipelineException: io.netty.handler.codec.http.HttpClientCodec is not a @Sharable handler, so can't be added or removed multiple times.

### Minimal yet complete reproducer code (or URL to code)  

https://github.com/github-big-cheng/netty-protostuff.git

### Netty version 

5.0.0.Alpha2

### JVM version (e.g. `java -version`) 

java version "1.8.0_251"
Java(TM) SE Runtime Environment (build 1.8.0_251-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.251-b08, mixed mode)

**Comment by hyperxpro** [comment]
Why are you using Netty `5.0.0.Alpha2`?

**Comment by github-big-cheng** [comment]
> Why are you using Netty `5.0.0.Alpha2`?

It's that version unstable? which version should I take? I'm new to learn Netty, and hope to use it in my work usefully

**Comment by normanmaurer** [comment]
4.1.51.Final...

**Comment by github-big-cheng** [comment]
> 4.1.51.Final...

I will try it, thanks a lot~

**Comment by amizurov** [comment]
@github-big-cheng Hi one of the more likely reasons you didn’t add it to the pipeline. This is code `client.channel.pipeline().get(NettyClientByteBufHandler.class)` will try to found any handler which is represented by `NettyClientByteBufHandler.class` otherwise return `null`.

**Comment by github-big-cheng** [comment]
> @github-big-cheng Hi one of the more likely reasons you didn’t add it to the pipeline. This is code `client.channel.pipeline().get(NettyClientByteBufHandler.class)` will try to found any handler which is represented by `NettyClientByteBufHandler.class` otherwise return `null`.

I had added to a `new NettyClientByteBufHandler()` pipeline already...

`
        this.bootstrap = new Bootstrap();
        this.bootstrap.group(WORKER_GROUP)
                    .channel(NioSocketChannel.class)
                    .option(ChannelOption.SO_KEEPALIVE, true)
                    .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 3000)
                    .handler(new ChannelInitializer() {
            @Override
            protected void initChannel(Channel ch) throws Exception {
                ChannelPipeline pipeline = ch.pipeline();
                if(config.getHandlers()!=null && config.getHandlers().length>0){
                    pipeline.addLast(config.getHandlers());
                }
            }
        });
`

**Comment by github-big-cheng** [comment]
I generate a new `NettyClientPool` (it created by commons-pool2) when accept a new group of host,port and handlers,when a same sign `NettyConfig` accept,  
the `NettyConfig` is like this:
`String host;`
`int port;`
`ChannelHandler[] handlers;`
`public int hashCode(){return host+port+handlers;}`
my `NettyCLientPool` will return a `NettyClient` for net work, and `NettyClient`  is about work like this:
`Channel channel;`
`NettyConfig config;`
`this.bootstrap = new Bootstrap();`
`        this.bootstrap.group(WORKER_GROUP)`
`                    .channel(NioSocketChannel.class)`
`                    .option(ChannelOption.SO_KEEPALIVE, true)`
`                    .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 3000)`
`                    .handler(new ChannelInitializer() {`
`            @Override`
`            protected void initChannel(Channel ch) throws Exception {`
`                ChannelPipeline pipeline = ch.pipeline();`
`                if(config.getHandlers()!=null && config.getHandlers().length>0){`
`                    pipeline.addLast(config.getHandlers());`
`                }`
`            }`
`           ChannelFuture future =
                this.bootstrap.connect(this.config.getHost(), this.config.getPort());`
`         this.channel = future.channel(); `
`        });` 
The caller can use `NettClient` in multi model, like rpc,http just call the model static method. 
The model config is about like this:
`private static ChannelHandler[] httpHandlers(){`
`        ChannelHandler[] handlers = new ChannelHandler[]{`
`                new HttpClientCodec(), // codec
`                new HttpObjectAggregator(1024 * 10 * 1024), // aggegator`
`                new HttpContentDecompressor(), //  decompressor`
`                new ChunkedWriteHandler(), // chunked `
`                new NettyClientHttpObjHandler(), // http handler`
`        };`
`        return handlers;
`    }`
Is it used improper? the `Channel` cann't be used many times in loop?

**Comment by github-big-cheng** [comment]
May I  found some help here ?...

**Comment by hyperxpro** [comment]
Tried with newer version of Netty?

**Comment by github-big-cheng** [comment]
> Tried with newer version of Netty?

umm... I had tried with 4.1.51.Final, 5.0.0.Alpha1,5.0.0.Alpha2
There are some screenshot about it...
Sincerely hope to get some help, all the best wishes!
 
<img width="600" alt="66ab7a53545bd319a41c8db9ed71751" src="https://user-images.githubusercontent.com/20948229/88608335-1e581080-d0b4-11ea-90cc-8563a5a871fa.png">
<img width="542" alt="3c2dd6db983113037b51c2543992ec2" src="https://user-images.githubusercontent.com/20948229/88608347-23b55b00-d0b4-11ea-99e7-c3d3d31344c8.png">
<img width="960" alt="1ea15815a8bd3154d8cc860ebca3ee0" src="https://user-images.githubusercontent.com/20948229/88608355-257f1e80-d0b4-11ea-8c33-92faf9cd4288.png">

**Comment by hyperxpro** [comment]
Use blocking operation because by the time you fetch it, sometime the value is present and sometimes it's null. So block or use listeners.

**Comment by github-big-cheng** [comment]
> Use blocking operation because by the time you fetch it, sometime the value is present and sometimes it's null. So block or use listeners.

It more detail about it?Thanks a lot

**Comment by hyperxpro** [comment]
> > Use blocking operation because by the time you fetch it, sometime the value is present and sometimes it's null. So block or use listeners.
> 
> I had block it with `Promise.get()` , and tried it like `channel.arrt().set(promise)` or `channel.get(MyHandler.class).setPromise(promise)`,but all not work well
> Is it more detail about it?Thanks a lot

Take a look at my code:
```java

import io.netty.channel.ChannelHandlerContext;
import io.netty.handler.codec.dns.doh.DoHDecoder;
import io.netty.handler.codec.dns.doh.DoHQueryEncoder;
import io.netty.handler.codec.http.HttpClientCodec;
import io.netty.handler.codec.http.HttpObjectAggregator;
import io.netty.handler.codec.http2.DefaultHttp2Connection;
import io.netty.handler.codec.http2.DelegatingDecompressorFrameListener;
import io.netty.handler.codec.http2.Http2Connection;
import io.netty.handler.codec.http2.HttpToHttp2ConnectionHandler;
import io.netty.handler.codec.http2.HttpToHttp2ConnectionHandlerBuilder;
import io.netty.handler.codec.http2.InboundHttp2ToHttpAdapter;
import io.netty.handler.codec.http2.InboundHttp2ToHttpAdapterBuilder;
import io.netty.handler.ssl.ApplicationProtocolNames;
import io.netty.handler.ssl.ApplicationProtocolNegotiationHandler;
import io.netty.util.concurrent.Promise;
import io.netty.util.internal.ObjectUtil;

import java.net.URL;

final class ALPNHandler extends ApplicationProtocolNegotiationHandler {

    private final URL url;
    private final Promise<Void> promise;

    ALPNHandler(URL url, Promise<Void> promise) {
        super(ApplicationProtocolNames.HTTP_1_1);
        this.url = url;
        this.promise = ObjectUtil.checkNotNull(promise, "promise");
    }

    Promise<Void> promise() {
        return promise;
    }

    @Override
    protected void configurePipeline(ChannelHandlerContext ctx, String protocol) {
        if (protocol.equalsIgnoreCase(ApplicationProtocolNames.HTTP_2)) {
            Http2Connection connection = new DefaultHttp2Connection(false);

            InboundHttp2ToHttpAdapter listener = new InboundHttp2ToHttpAdapterBuilder(connection)
                    .propagateSettings(false)
                    .validateHttpHeaders(true)
                    .maxContentLength(1024 * 64)
                    .build();

            HttpToHttp2ConnectionHandler http2Handler = new HttpToHttp2ConnectionHandlerBuilder()
                    .frameListener(new DelegatingDecompressorFrameListener(connection, listener))
                    .connection(connection)
                    .build();

            ctx.pipeline().addLast(http2Handler,
                    new HttpObjectAggregator(1024 * 64, true),
                    new DoHQueryEncoder(url),
                    new DoHDecoder(),
                    new Handler());
            promise.setSuccess(null);
        } else if (protocol.equalsIgnoreCase(ApplicationProtocolNames.HTTP_1_1)) {
            ctx.pipeline().addLast(
                    new HttpClientCodec(),
                    new HttpObjectAggregator(1024 * 64, true),
                    new DoHQueryEncoder(url),
                    new DoHDecoder(),
                    new Handler());
            promise.setSuccess(null);
        } else {
            promise.setFailure(new IllegalArgumentException("Unsupported Protocol: " + protocol));
        }
    }

    @Override
    protected void handshakeFailure(ChannelHandlerContext ctx, Throwable cause) {
        promise.setFailure(cause);
    }

    @Override
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {
        promise.setFailure(cause);
    }
}
```

**Comment by hyperxpro** [comment]
And then block like this:
```java
 channel.pipeline().get(ALPNHandler.class).promise().sync();
```

**Comment by github-big-cheng** [comment]
> And then block like this:
> 
> ```java
>  channel.pipeline().get(ALPNHandler.class).promise().sync();
> ```

thanks very much!~~ I'll try it as soon as I can~

**Comment by github-big-cheng** [comment]
@hyperxpro 
Thanks a lot!~ I had resolve it !!!!
I use `client.channel.attr(NETTY_CLIENT_REQUEST).set(byteBuf);`   and used override method `channelActive  ctx.writeAndFlush(byteBuf)` to instead of of `client.channel.ctx.writeAndFlush(byteBuf)` .
Thank you again for all kind helps !
There are some codes, hope can help some other peoples...
`// set request
            ByteBuf byteBuf = Unpooled.copiedBuffer(message);
            client.channel.attr(NETTY_CLIENT_REQUEST).set(byteBuf);


            // set response
            NettyResponse<byte[]> response = new NettyResponse();
            client.channel.attr(NETTY_CLIENT_PROMISE).set(response);

            // block for result
            result = response.get();`


`@Override
    public void channelActive(ChannelHandlerContext ctx) throws Exception {
        this.byteBuf = (ByteBuf) ctx.channel().attr(NettyClient.NETTY_CLIENT_REQUEST).get();
        if(this.byteBuf == null){
            throw new SystemException("byteBuf is not bind...");
        }

        ctx.writeAndFlush(this.byteBuf);
    }`
