### ISSUE TITLE
Http2: writing valid PRIORITY frame fails with misleading error message

### ISSUE THREAD

**Issue by mostroverkhov** [netty/netty#10416]
### Expected behavior
* Writing valid PRIORITY frame with `streamDependency=0` succeeds
*  PRIORITY frame validation message contains actual cause of error

### Actual behavior
Writing PRIORITY frame with `streamDependency=0`
```
http2Handler.encoder()
     .writePriority(ctx, streamId, /*dependency*/ 0, weight, /*exclusive*/ false, ctx.newPromise());
```

fails with misleading error message

```
java.lang.IllegalArgumentException: streamId: 0 (expected: > 0)
 at io.netty.util.internal.ObjectUtil.checkPositive(ObjectUtil.java:44)
 at io.netty.handler.codec.http2.DefaultHttp2FrameWriter.verifyStreamId(DefaultHttp2FrameWriter.java:605)
 at io.netty.handler.codec.http2.DefaultHttp2FrameWriter.writePriority(DefaultHttp2FrameWriter.java:277)
 at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writePriority(DefaultHttp2ConnectionEncoder.java:278)
 at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writePriority(DecoratingHttp2FrameWriter.java:59)
```
caused by [DefaultHttp2FrameWriter](https://github.com/netty/netty/blob/28e1fbd366602d8f4b50921afb2c9d5e41b94a2d/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameWriter.java#L277) that expects `streamDependency > 0`,  
but fails with message `java.lang.IllegalArgumentException: streamId: 0 (expected: > 0)`. 

### Netty version
4.1.51.Final

**Comment by normanmaurer** [comment]
@ejona86 can you have a look ?

**Comment by ejona86** [comment]
I'll send out a PR.

The `verifyStreamId()` check for `streamDependency` should be a `verifyStreamOrConnectionId()`:
https://github.com/netty/netty/blob/f58223982ce8d9ed056c3d127972222966d0ebd1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameWriter.java#L273-L277

The mislabled error seems to be a bug in the verify function, in that it ignores `argumentName`:
https://github.com/netty/netty/blob/f58223982ce8d9ed056c3d127972222966d0ebd1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameWriter.java#L604-L610

It looks like the reading direction has the correct verification:
https://github.com/netty/netty/blob/f58223982ce8d9ed056c3d127972222966d0ebd1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameReader.java#L501-L511

It later re-verifies with (although note these are asserts, so they are internal checks and not for verifying remotes):
https://github.com/netty/netty/blob/f58223982ce8d9ed056c3d127972222966d0ebd1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2RemoteFlowController.java#L184-L186
