### ISSUE TITLE
Can add a function  that Retrieving original destination from iptables after REDIRECT  with netty  “SO_ORIGINAL_DST ”

### ISSUE THREAD

**Issue by huchaogithup** [netty/netty#10419]
I want to use this as a transparent proxy, where my original plan is to use iptables with a REDIRECT rule forward all connections to my application proxy.

**Comment by hyperxpro** [comment]
I did this last year and far as I can remember, Netty was receiving original source and destination IP and Port. I had `EpollChannelOption.IP_TRANSPARENT` enabled.

**Comment by huchaogithup** [comment]
I configure this feature whit EpollChannelOption.IP_TRANSPARENT enabled. How do I get it original source and destination IP and Port when  TCP connect？

**Comment by huchaogithup** [comment]
there is demo 
i```
ptables -t nat -A OUTPUT -p tcp -j REDIRECT  --to-ports 12345
iptables -t nat -A PREROUTING -p tcp -j REDIRECT  --to-ports 12345
```
netty code

`      ServerBootstrap serverBootstrap1 =new ServerBootstrap();
        serverBootstrap1.group(new EpollEventLoopGroup())
                .channel(EpollServerSocketChannel.class)
                .option(EpollChannelOption.IP_TRANSPARENT,true)
                .childOption(EpollChannelOption.IP_TRANSPARENT,true)
                .childHandler(new ChannelInitializer<SocketChannel>() {
                    @Override
                    protected void initChannel(SocketChannel ch) throws Exception {
                        ch.pipeline().addLast(new SimpleChannelInboundHandler<Object>() {

                            @Override
                            protected void channelRead0(ChannelHandlerContext ctx, Object msg) throws Exception {
                                System.out.println(ctx.channel().remoteAddress());
                                System.out.println(ctx.channel().localAddress());
                                System.out.println(ctx.channel());
                                EpollSocketChannelConfig config = (EpollSocketChannelConfig)ctx.channel().config();
                                System.out.println(config.isIpTransparent());


                            }
                        });


                    }
                }).bind("0.0.0.0",12345).sync();`



request：
**curl localhost:12**
result ： 
**/127.0.0.1:37466
/127.0.0.1:12345
[id: 0x128b8653, L:/127.0.0.1:12345 - R:/127.0.0.1:37466]**

**Comment by hyperxpro** [comment]
Not sure but try this command: 
```
iptables -t mangle -A PREROUTING -p tcp --dport 443 -j TPROXY --on-port=9110 --on-ip=127.0.0.1
```

**Comment by hyperxpro** [comment]
This will forward traffic received on TCP:443 to 127.0.0.1:9110/TCP using Transparent Proxy.

**Comment by huchaogithup** [comment]
The problem has been solved. Thank you.but I still hope that netty can adapt a function Retrieving original destination through the DNAT  instead of TPROXY in the future

**Comment by zengqi826** [comment]
> The problem has been solved. Thank you.but I still hope that netty can adapt a function Retrieving original destination through the DNAT instead of TPROXY in the future

how to solve it ? I want to learn more about this .Thanks
