### ISSUE TITLE
io.netty.handler.ssl.Conscrypt.isConscryptEngine(SSLEngine engine) may throw the NullPointerException

### ISSUE THREAD

**Issue by skyguard1** [netty/netty#10413]
### Expected behavior
not throw the NullPointerException
### Actual behavior
may throw the NullPointerException
### Steps to reproduce
  In io.netty.handler.ssl.Conscrypt.loadIsConscryptEngine(),there is the code which try to get ClassLoader

  ```
private static Method loadIsConscryptEngine() {
        try {
            Class<?> conscryptClass = Class.forName("org.conscrypt.Conscrypt", true,
                    ConscryptAlpnSslEngine.class.getClassLoader());
            return conscryptClass.getMethod("isConscrypt", SSLEngine.class);
        } catch (Throwable ignore) {
            // Conscrypt was not loaded.
            return null;
        }
      }

```
  and there is a Method object
  ` private static final Method IS_CONSCRYPT_SSLENGINE = loadIsConscryptEngine();`
  and the io.netty.handler.ssl.Conscrypt.isConscryptEngine(SSLEngine engine) use the IS_CONSCRYPT_SSLENGINE,and 
  may throw the NullPointerException

  ```
private static boolean isConscryptEngine(SSLEngine engine) {
        try {
            return (Boolean) IS_CONSCRYPT_SSLENGINE.invoke(null, engine);
        } catch (IllegalAccessException ignore) {
            return false;
        } catch (InvocationTargetException ex) {
            throw new RuntimeException(ex);
        }
    }

```
@normanmaurer,Please confirm this is a problem, if yes, I can submit pr to fix it ,thank you

### Netty version
4.1.51
### JVM version (e.g. `java -version`)
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
### OS version (e.g. `uname -a`)
Darwin EBJ1203253.local 18.7.0 Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020

**Comment by normanmaurer** [comment]
@skyguard1 as It calls `isAvailable()` before calling this method there is no risk in reality. That said I think an extra `null` check can't hurt for readability and to ensure we not produce a regression at some point. So sure PRs welcome

**Comment by skyguard1** [comment]
Yes, you could do without fixing the problem, but you need to do a non-null check when someone else calls the method,thanks for you apply
