### ISSUE TITLE
Send queue backlog causes memory leak

### ISSUE THREAD

**Issue by junhao521** [netty/netty#10429]
### Expected behavior
i am writing a simple http proxy server, there is no problem with proxy operations, but when i transfer a big file (like download a 10G file),  will causes OOM
### Actual behavior
i try to debug it and monitor the memory, when download a big file, the proxy-client will constantly write chunk data of the file to proxy-server,  when the proxy-server cannot process the chunk data in time, the chunk data will be put into memory, i think this process leads to unlimited memory growth.
### Minimal yet complete reproducer code (or URL to code)
=== Proxy Server ===
                EventLoopGroup bossGroup = new NioEventLoopGroup(1);
		EventLoopGroup workerGroup = new NioEventLoopGroup();
		try {
			ServerBootstrap b = new ServerBootstrap();
			b.group(bossGroup, workerGroup)
					.channel(NioServerSocketChannel.class)
					.option(ChannelOption.SO_BACKLOG, 1024)
					.childOption(ChannelOption.SO_KEEPALIVE, true)
					.childOption(ChannelOption.TCP_NODELAY, true)
					.childOption(ChannelOption.AUTO_READ, false)
					.childHandler(new ChannelInitializer<Channel>() {

						@Override
						protected void initChannel(Channel ch) throws Exception {
							if (proxyConfig.isSslEnable()) {
								ch.pipeline().addLast(new SslHandler(sslEngineFactory.getServerSSLEngine()));
							}
							ch.pipeline().addLast(
									//new GlobalTrafficShapingHandler(ch.eventLoop().parent(), 1 * M, 5 * M),
									new HttpServerCodec(),
									new HttpContentCompressor(),
									new HttpObjectAggregator(Integer.MAX_VALUE),
									//new ChunkedWriteHandler(),
									proxyServerHandler);
						}
					});

			ChannelFuture f = b.bind(proxyConfig.getPort()).sync();
			f.channel().closeFuture().sync();

		} catch (Exception e) {
			log.error(e.getMessage(), e);
		} finally {
			bossGroup.shutdownGracefully();
			workerGroup.shutdownGracefully();
		}

====Proxy Client===
		bootstrap = new Bootstrap();
		bootstrap
				.group(inboundChannel.eventLoop())
				.channel(inboundChannel.getClass())
				.option(ChannelOption.TCP_NODELAY, true)
				.option(ChannelOption.AUTO_READ, false)
				.handler(new ProxyClientInitializer(inboundChannel, route));

                ChannelFuture cf = bootstrap.connect(route.getHost(), route.getPort());
		outboundChannel = cf.channel();
		log.info("===>>> Connecting Server {}:{}", route.getHost(), route.getPort());

		cf.addListener(new ChannelFutureListener() {

			public void operationComplete(ChannelFuture future) throws Exception {
				if (future.isSuccess()) {
					log.info("===>>> Connect Server Successfully.");
					inboundChannel.read();
					
					if (outboundChannel.isActive()) {
						outboundChannel.writeAndFlush(request).addListener(new ChannelFutureListener() {
							@Override
							public void operationComplete(ChannelFuture future) {
								if (future.isSuccess()) {
									outboundChannel.read();
								} else {
									//log.info(future.cause().getMessage(), future.cause());
									ProxyUtils.closeOnFlush(future.channel());
								}
							}
						});
					}
				}
			}
		});

=== Proxy Client Handler===
@Override
	public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
			System.out.println("write msg: " + msg.toString());
			clientChannel.writeAndFlush(msg).addListener(new ChannelFutureListener() {
				@Override
				public void operationComplete(ChannelFuture future) {
					if (future.isSuccess()) {
						ctx.channel().read();
					} else {
						//log.info(future.cause().getMessage(), future.cause());
						ProxyUtils.closeOnFlush(future.channel());
					}
				}
			});
		}
	}

### Netty version
4.1.39.Final
### JVM version (e.g. `java -version`)
1.8.0_111
### OS version (e.g. `uname -a`)
windows and linux

**Comment by normanmaurer** [comment]
This most likely caused by `new HttpObjectAggregator(Integer.MAX_VALUE)` which will cause the whole request to be buffered in memory before it will be proxied.
