### ISSUE TITLE
Netty does not set correct ByteBuffer capacity

### ISSUE THREAD

**Issue by xxDark** [netty/netty#10421]
### Expected behavior
Capacities  of NIO buffer and Netty's buffer are the same

### Actual behavior
Capacities are diefferent

### Steps to reproduce
See code snippet below

### Minimal yet complete reproducer code (or URL to code)
```Java
        ByteBuf buf = Unpooled.directBuffer(4);
        ByteBuffer nio = buf.nioBuffer();
        assert buf.capacity() == nio.capacity();
```

### Netty version
4.1.51.Final

**Comment by xxDark** [comment]
See https://github.com/luben/zstd-jni/blob/3d16e515253a0b6941810ab3ee4055201ca9ff54/src/main/native/jni_fast_zstd.c#L468 to understand the use case.

**Comment by little-pan** [comment]
According to netty api doc, the method nioBuffer() of ByteBuf only confirms that this NIO buffer content is the readable content of the ByteBuf, doesn't define the capacity of the NIO buffer.
