### ISSUE TITLE
OutOfMemoryError on Dns Resolution

### ISSUE THREAD

**Issue by kireet** [netty/netty#10420]
I recently upgraded to 4.1.51 to pull in a fix for #10246. However, now I get an OutOfMemory issue that seems related to the same code? We have been running netty for a few months with no OOM issues until now. I plan to downgrade netty back to 4.1.50 for now.

![heap dump](https://user-images.githubusercontent.com/1395755/87963075-04438000-ca6d-11ea-8edd-c76f17c1cf5d.png)

### Expected behavior
dns resolution

### Actual behavior
OutOfMemoryError
### Steps to reproduce
unfortunately i am not able to provide reproduction steps.

### Netty version
4.1.51

### JVM version (e.g. `java -version`)
java version "1.8.0_212"
Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.212-b10, mixed mode)

### OS version (e.g. `uname -a`)
Linux 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
Can you share the heapdump?

**Comment by kireet** [comment]
is there a way i could share it privately with you? it's also pretty big, about 1GB bzipped.

**Comment by normanmaurer** [comment]
Google drive ? norman.maurer@googlemail.com

**Comment by kireet** [comment]
ok, i uploaded it and shared it with you.

**Comment by kireet** [comment]
does it look like a fix for this will make it into the next release?

**Comment by normanmaurer** [comment]
@kireet I will have a look next week as I was out for vacation

**Comment by normanmaurer** [comment]
@kireet is this somehow easy for you to reproduce ?

**Comment by kireet** [comment]
we reverted back to the previous netty version that produces tons of logs. i assume they are related, but i can't reproduce either issue reliably. the logs problem only happens every 2-3 weeks on a quite busy server. 😕 

i checked the host (ns2.bitgest.es) from the heap dump and doing a resolve on it doesn't seem to trigger any problems.

**Comment by normanmaurer** [comment]
@kireet yeah I was not able to reproduce it as well. I will continue to debug and see if I somehow can. That said I think I will revert the Stackoverflow "fix" for now as it seems that the real reason is not really fixed which at the end then cause an OOME as we not overflow now anymore. Agree ?

**Comment by normanmaurer** [comment]
@kireet also one more question... you don't use a custom `*Cache` for the resolver, right ?

**Comment by normanmaurer** [comment]
@kireet can you try to resolve `ns2.bitgest.es.` and `ns1.bitgest.es.` on your system using the same name servers that are used by netty using either `dig` or `nslookup` and let me know what the outcome is ? I think I have a suspect for the OOME.

**Comment by kireet** [comment]
```
$ dig ns1.bitgest.es

; <<>> DiG 9.9.4-RedHat-9.9.4-50.el7_3.1 <<>> ns1.bitgest.es
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6196
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ns1.bitgest.es.			IN	A

;; ANSWER SECTION:
ns1.bitgest.es.		86400	IN	A	89.17.204.109

;; AUTHORITY SECTION:
bitgest.es.		86400	IN	NS	ns1.bitgest.es.
bitgest.es.		86400	IN	NS	ns2.bitgest.es.

;; ADDITIONAL SECTION:
ns2.bitgest.es.		86400	IN	A	89.17.204.109

;; Query time: 475 msec
;; SERVER: [removed]
;; WHEN: Tue Aug 11 10:40:11 PDT 2020
;; MSG SIZE  rcvd: 107

$ dig ns2.bitgest.es

; <<>> DiG 9.9.4-RedHat-9.9.4-50.el7_3.1 <<>> ns2.bitgest.es
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 12933
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 2

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;ns2.bitgest.es.			IN	A

;; ANSWER SECTION:
ns2.bitgest.es.		86400	IN	A	89.17.204.109

;; AUTHORITY SECTION:
bitgest.es.		86396	IN	NS	ns2.bitgest.es.
bitgest.es.		86396	IN	NS	ns1.bitgest.es.

;; ADDITIONAL SECTION:
ns1.bitgest.es.		86396	IN	A	89.17.204.109

;; Query time: 161 msec
;; SERVER: [removed]
;; WHEN: Tue Aug 11 10:40:15 PDT 2020
;; MSG SIZE  rcvd: 107

```

it's been awhile though, this info could have changed. 

we do use a slightly customized cache, here is the code:

```
            new DnsNameResolverBuilder()
                .eventLoop(_group.next())
                .channelFactory(new ReflectiveChannelFactory<DatagramChannel>(channelClass))
                .queryTimeoutMillis(_timeoutSecs * 1000)
                .resolveCache(new DnsCache())
                .build();

    public class DnsCache extends DefaultDnsCache {

        public DnsCache() {
            super(0, 60, 0); //limit cache size
        }

        @Override
        public List<? extends DnsCacheEntry> get(String hostname, DnsRecord[] additionals) {
            List<? extends DnsCacheEntry> rv = super.get(hostname, additionals);

            _cacheHitRate = expSmooth(_cacheHitRate, rv != null ? 1 : 0);
            return rv;
        }
    }
```

**Comment by normanmaurer** [comment]
@kireet interesting... these resolve for me as well now. Earlier today they didn't tho....

**Comment by normanmaurer** [comment]
@kireet ok I know what happens... Just need to think a bit about how to solve this in a proper way. stay tuned

**Comment by normanmaurer** [comment]
@kireet https://github.com/netty/netty/pull/10478 PTAL... 

That said I will create another PR as well as there is also another related issue

**Comment by normanmaurer** [comment]
actually scratch that... #10478 is all we need
