### ISSUE TITLE
DefaultEventExecutorChooserFactory is not strict round-robin if executors length is not power of two

### ISSUE THREAD

**Issue by quaff** [netty/netty#10423]
### Expected behavior
[GenericEventExecutorChooser.next()](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/concurrent/DefaultEventExecutorChooserFactory.java#L70) will act as strict round-robin

### Actual behavior
If idx is reaching Integer.MAX_VALUE, it will turn round

### Steps to reproduce
```
AtomicInteger idx = new AtomicInteger(Integer.MAX_VALUE);
for (int i = 0; i < 10; i++)
	System.out.print(Math.abs(idx.getAndIncrement() % 10) + " ");
```
```
 printed: 7 8 7 6 5 4 3 2 1 0 
expected: 7 8 9 0 1 2 3 4 5 6
```

**Comment by FastInvite2k2** [comment]
How can it be fixed?

**Comment by wagnerluis1982** [comment]
There is no perfect solution.

Since Java integers are always unsigned at overflow we have [2147483647, -2147483648, -2147483647], which makes the repetition. If we treat the integer as unsigned we won't have a repetition, but we still will have a skip (that occurs from -1 to 0).

So, if we need a perfect round robin, the only way I can see is to update `idx` atomically with a expression (available from Java 8), something like that:

```diff
         @Override
         public EventExecutor next() {
-             return executors[Math.abs(idx.getAndIncrement() % executors.length)];
+             return executors[idx.getAndUpdate(x -> (x + 1) % executors.length)];
         }
```

**Comment by quaff** [comment]
Here is my solution, please review.
```java
public class CounterUtils {

	public static int getAndIncrement(AtomicInteger counter, int mod) {
		int value = incrementAndGet(counter, mod) - 1;
		return value < 0 ? value + mod : value;
	}

	public static int incrementAndGet(AtomicInteger counter, int mod) {
		return counter.updateAndGet(current -> {
			int next = ((current != Integer.MAX_VALUE ? current : -1) + 1) % mod;
			if (next < 0)
				next += mod;
			return next;
		});
	}

}

```

**Comment by normanmaurer** [comment]
@chrisvest can you have a look please ?

**Comment by chrisvest** [comment]
We can either change the counter to a long, which won't overflow for hundreds of years, or we can reset the sequence whenever the max value is reached.

**Comment by normanmaurer** [comment]
yeah lets just use a long @chrisvest  that should be good enough...
