### ISSUE TITLE
When available, TLSv1.3 should be enabled by default

### ISSUE THREAD

**Issue by slandelle** [netty/netty#10439]
### Expected behavior

TLSv1.3 is enabled as long as long as the SSLEngine supports it.
This is very surprising that Netty actually disables it by default and requires users to explicitly enable it.

### Actual behavior

TLSv1.3 support was introduced almost 2 years ago but was disabled by default in both [JdkSslContext](https://github.com/netty/netty/commit/0ddc62cec0b4715ae37cef0e6a9f8c79d42d74e9#diff-7647922272ab3791df0dbfd63f919ae7R110) and [ReferenceCountedOpenSslContext](https://github.com/netty/netty/commit/0ddc62cec0b4715ae37cef0e6a9f8c79d42d74e9#diff-82f94494cc35616a8a19b6aa9ed033efR271).

Is the rationale behind this decision of not enabling it by default still valid?

### Netty version

From 4.1.31 to 4.1.51.Final included.

### JVM version (e.g. `java -version`)

TLSv1.3 is available since Java 11 and was backported in some builds of Java 8 such as Oracle and Zulu.

**Comment by normanmaurer** [comment]
@slandelle I think you are right and we should enable it by default these days depending on if it is enabled by default for the JDK implementation as well. I will have a look next week or if you want you can also take a stab @slandelle

**Comment by normanmaurer** [comment]
Fixed https://github.com/netty/netty/pull/10451
