### ISSUE TITLE
HttpClient Connection Reuse

### ISSUE THREAD

**Issue by ThierrySquirrel** [netty/netty#10435]
### Expected behavior

When httpclient sends a request, the parameter header carries keep alive (httpserver does not close the connection), and then sends requests many times without creating a new connection

### Actual behavior

Httpclient add HttpobjectAggregator cannot receive fullhttpresponse,

Remove HttpObjectAggregator,
Only the first response received HttpResponse（HttpObject ）After that, all the responses are HttpContent（HttpObject ）.
Convert it to a string
content ().toString (CharsetUtil.UTF_8),
It is found that httpresponse and httpcontent 'stick together`

### Steps to reproduce

1.Start the httpserver
2.httpclient Send the request
3.httpserver return DefaultFullHttpResponse,Do not close the connection
4.httpclient  The response is received（HttpObject ）//Remove HttpObjectAggregator
5.httpclient  Send request again (connection multiplexing)
6.httpserver return DefaultFullHttpResponse,Do not close the connection
7.httpclient  The response is received   HttpContent（HttpObject ）//httpresponse and httpcontent 'stick together`

### Minimal yet complete reproducer code (or URL to code)

public class HttpClientInitializer extends ChannelInitializer<SocketChannel> {

    @Override
    public void initChannel(SocketChannel ch) {
        ChannelPipeline pipeline = ch.pipeline();

        pipeline .addLast (new HttpClientCodec ());
//     pipeline .addLast (new HttpObjectAggregator (65535));

        pipeline.addLast(new HttpClientHandler ());
    }
}

public class HttpClientHandler extends SimpleChannelInboundHandler<HttpObject> {

    @Override
    protected void channelRead0(ChannelHandlerContext ctx, HttpObject msg) throws Exception {
        if(msg instanceof HttpResponse){
            System.out.println ("HttpResponse");
            System.out.println (msg);
        }
       if (msg instanceof HttpContent){
            System.out.println ("HttpContent");
            DefaultHttpContent defaultHttpContent= (DefaultHttpContent) msg;
            String body = defaultHttpContent.content ().toString (CharsetUtil.UTF_8);
            System.out.println (body);
         DefaultFullHttpRequest defaultFullHttpRequest = new DefaultFullHttpRequest (HttpVersion.HTTP_1_1, HttpMethod.GET, "/a", Unpooled.copiedBuffer ("hello",CharsetUtil.UTF_8));
            defaultFullHttpRequest.headers ().add (HttpHeaderNames.CONTENT_TYPE,HttpHeaderValues.KEEP_ALIVE);
            ctx.writeAndFlush (defaultFullHttpRequest);
        }
    }
}

public class HttpClient {
    public static void main(String[] args)throws Exception {
        Bootstrap bootstrap = new Bootstrap ();
        EventLoopGroup group = new NioEventLoopGroup ();
        bootstrap.group (group)
                .channel (NioSocketChannel.class)
                .handler (new HttpClientInitializer ());
        ChannelFuture channelFuture=null;
        try {
            channelFuture = bootstrap.connect ("127.0.0.1",80).sync ();
            DefaultFullHttpRequest defaultFullHttpRequest = new DefaultFullHttpRequest (HttpVersion.HTTP_1_1, HttpMethod.GET, "/a", Unpooled.copiedBuffer ("hello", CharsetUtil.UTF_8));
            defaultFullHttpRequest.headers ().add (HttpHeaderNames.CONTENT_TYPE, HttpHeaderValues.KEEP_ALIVE);
            channelFuture.channel ().writeAndFlush (defaultFullHttpRequest);
        } catch (Exception e) {
            throw new RestfulClientException ("connect Error",e);
        }finally {
//            group.shutdownGracefully();
//            channelFuture.channel ().closeFuture().sync();
        }
    }
}

public class HttpServerHandler extends SimpleChannelInboundHandler<FullHttpRequest> {

    @Override
    protected void channelRead0(ChannelHandlerContext ctx, FullHttpRequest msg) throws Exception {
        System.out.println (ctx.channel ().id ().asShortText ());
        System.out.println (ctx.channel ().id ().asLongText ());
        DefaultFullHttpResponse defaultFullHttpResponse = new DefaultFullHttpResponse (HttpVersion.HTTP_1_1, HttpResponseStatus.OK, Unpooled.copiedBuffer ("world", CharsetUtil.UTF_8));
        ctx.channel ().writeAndFlush (defaultFullHttpResponse);

    }
}

### Netty version

4.1.51.Final

### JVM version (e.g. `java -version`)

`` Java8

### OS version (e.g. `uname -a`)
windows10

### Other

If you can, forgive my English. Thank you very much

**Comment by normanmaurer** [comment]
Sorry but I done get what you try to say... Also netty only decodes / encodes. All the other logic is in your usage.

**Comment by ThierrySquirrel** [comment]
OK, I see. Thank you for your help
