### ISSUE TITLE
Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.14:build (build-native-lib) on project netty-transport-native-kqueue: build failed: org.apache.maven.plugin.MojoExecutionException: ./configure failed with exit code: 1

### ISSUE THREAD

**Issue by yesheng1112** [netty/netty#10446]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Netty 4.1.51.Final:
[INFO]
[INFO] Netty/Dev-Tools .................................... SUCCESS [  0.597 s]
[INFO] Netty .............................................. SUCCESS [  2.460 s]
[INFO] Netty/Common ....................................... SUCCESS [  5.825 s]
[INFO] Netty/Buffer ....................................... SUCCESS [  1.564 s]
[INFO] Netty/Resolver ..................................... SUCCESS [  0.696 s]
[INFO] Netty/Transport .................................... SUCCESS [  1.890 s]
[INFO] Netty/Codec ........................................ SUCCESS [  1.435 s]
[INFO] Netty/Codec/DNS .................................... SUCCESS [  1.007 s]
[INFO] Netty/Codec/HAProxy ................................ SUCCESS [  0.733 s]
[INFO] Netty/Handler ...................................... SUCCESS [  2.097 s]
[INFO] Netty/Codec/HTTP ................................... SUCCESS [  2.083 s]
[INFO] Netty/Codec/HTTP2 .................................. SUCCESS [  1.648 s]
[INFO] Netty/Codec/Memcache ............................... SUCCESS [  0.767 s]
[INFO] Netty/Codec/MQTT ................................... SUCCESS [  0.813 s]
[INFO] Netty/Codec/Redis .................................. SUCCESS [  0.701 s]
[INFO] Netty/Codec/SMTP ................................... SUCCESS [  0.638 s]
[INFO] Netty/Codec/Socks .................................. SUCCESS [  0.879 s]
[INFO] Netty/Codec/Stomp .................................. SUCCESS [  0.761 s]
[INFO] Netty/Codec/XML .................................... SUCCESS [  0.674 s]
[INFO] Netty/Handler/Proxy ................................ SUCCESS [  0.676 s]
[INFO] Netty/Resolver/DNS ................................. SUCCESS [  0.996 s]
[INFO] Netty/Transport/RXTX ............................... SUCCESS [  0.662 s]
[INFO] Netty/Transport/SCTP ............................... SUCCESS [  0.741 s]
[INFO] Netty/Transport/UDT ................................ SUCCESS [  0.718 s]
[INFO] Netty/Example ...................................... SUCCESS [  2.350 s]
[INFO] Netty/Transport/Native/Unix/Common ................. SUCCESS [  0.774 s]
[INFO] Netty/Testsuite .................................... SUCCESS [  1.629 s]
[INFO] Netty/Transport/Native/Unix/Common/Tests ........... SUCCESS [  0.609 s]
[INFO] Netty/Transport/Native/KQueue ...................... FAILURE [  8.350 s]
[INFO] Netty/Resolver/DNS/MacOS ........................... SKIPPED
[INFO] Netty/Transport/Native/Epoll ....................... SKIPPED
[INFO] Netty/All-in-One ................................... SKIPPED
[INFO] Netty/Tarball ...................................... SKIPPED
[INFO] Netty/Testsuite/Autobahn ........................... SKIPPED
[INFO] Netty/Testsuite/Http2 .............................. SKIPPED
[INFO] Netty/Testsuite/OSGI ............................... SKIPPED
[INFO] Netty/Testsuite/Shading ............................ SKIPPED
[INFO] Netty/Testsuite/NativeImage ........................ SKIPPED
[INFO] Netty/Transport/BlockHound/Tests ................... SKIPPED
[INFO] Netty/Microbench ................................... SKIPPED
[INFO] Netty/BOM .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  45.128 s
[INFO] Finished at: 2020-08-01T15:09:35+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.14:build (build-native-lib) on project netty-transport-native-kqueue: build failed: org.apache.maven.plugin.MojoExecutionException: ./configure failed with exit code: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :netty-transport-native-kqueue

**Comment by hyperxpro** [comment]
Show logs

**Comment by amizurov** [comment]
Hi, @yesheng1112 check that you installed `brew install autoconf automake libtool`

**Comment by normanmaurer** [comment]
Please do what @amizurov said and if the issue still exists re-open with more details
