### ISSUE TITLE
JMX support

### ISSUE THREAD

**Issue by Sneezry** [netty/netty#10440]
I learnt from https://github.com/netty/netty/issues/6523, until 2017, there is no JMX metrics available for Netty.

May I confirm the recent state of metrics? Any update about metrics? If no, is there any plan to support to expose metrics to JMX?

Thanks.

**Comment by normanmaurer** [comment]
You are right hat there is nothing shipped as part of netty. That said you can add such instrumentation easily by yourself for most parts. Like adding a `ChannelHandler` that publish metrics etc
