### ISSUE TITLE
FileUpload.get() created by a HttpPostMultipartRequestDecoder returns incomplete array on 4.1.51

### ISSUE THREAD

**Issue by danielflower** [netty/netty#10449]
### Expected behavior

UploadFile.get() should return the full byte array uploaded.

### Actual behavior

It appears that although `fileUpload.length()` returns the correct value, the byte array from `get()` returns only a partial array.

### Steps to reproduce

Create a `HttpPostMultipartRequestDecoder` and call offer at least twice with some request form data. The test below passes on 4.1.50 but fails on 4.1.51.

### Minimal yet complete reproducer code (or URL to code)

````java
@Test
public void fileUploadRegression() throws IOException {
    byte[] file = new byte[32000];
    Arrays.fill(file, (byte) 1);

    String body = "--861fbeab-cd20-470c-9609-d40a0f704466\n" +
        "Content-Disposition: form-data; name=\"image\"; filename=\"guangzhou.jpeg\"\n" +
        "Content-Type: image/jpeg\n" +
        "Content-Length: " + file.length + "\n" +
        "\n" + new String(file, UTF_8) + "\n" +
        "--861fbeab-cd20-470c-9609-d40a0f704466--\n";
    byte[] bodyBytes = body.getBytes(UTF_8);

    HttpRequest request = new DefaultHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.POST, "/upload");
    request.headers().set("content-type", "multipart/form-data; boundary=861fbeab-cd20-470c-9609-d40a0f704466");
    request.headers().set("content-length", bodyBytes.length);
    HttpPostMultipartRequestDecoder decoder = new HttpPostMultipartRequestDecoder(request);
    decoder.offer(new DefaultHttpContent(Unpooled.copiedBuffer(bodyBytes, 0, 8192)));
    decoder.offer(new DefaultHttpContent(Unpooled.copiedBuffer(bodyBytes, 8192, bodyBytes.length - 8192)));
    decoder.offer(new DefaultLastHttpContent());
    FileUpload data = (FileUpload) decoder.getBodyHttpDatas().get(0);
    assertThat(data.length(), is((long)file.length)); // passes
    assertThat(data.get().length, is(file.length)); // fails on 4.1.51
}
````

### Netty version

4.1.51

### JVM version (e.g. `java -version`)

Multiple versions tested (8, 10, 11, 12). 

### OS version (e.g. `uname -a`)

Windows, Linux.

**Comment by fredericBregier** [comment]
@normanmaurer Might it be linked to recent changes, such as in https://github.com/netty/netty/blob/c4754cf7b890e7169b2438567fa2f881728715ed/codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java#L167

I saw a few days ago a remark on the possibility that this call might not write all buffer to filechannel (not getting the real number of bytes written) and that the buffer has its readerIndex not changed.
I don't have any access right now, except web, so I cannot investigate more, but it might be linked, wdyt?

**Comment by amizurov** [comment]
Hi, guys could you please check fix.

**Comment by paplorinc** [comment]
This affected us as well (is still working properly with `4.1.50.Final`), when can we expect `4.1.52.Final`?

**Comment by normanmaurer** [comment]
@paplorinc I think next week

**Comment by paplorinc** [comment]
Thanks @normanmaurer

**Comment by paplorinc** [comment]
Hey @normanmaurer, any update on when this fix will be released?

**Comment by normanmaurer** [comment]
@paplorinc sorry it took longer then expected but within the next week.
