### ISSUE TITLE
ChannelFuture hangs in connect().sync() 

### ISSUE THREAD

**Issue by thineagle** [netty/netty#10441]
### Expected behavior
when i use connect.sync() , a lot of thread is on wating state
`   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:221)
	- locked <0x0000000764482828> (a io.netty.bootstrap.AbstractBootstrap$PendingRegistrationPromise)
	at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:131)
	at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:30)
	at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:328)
	at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:119)
	at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:30)`

use netstat i can not find any connection, but the thread  hangs forever

### Netty version
4.1.37.Final

### JVM version (e.g. `java -version`)
1.8

### OS version (e.g. `uname -a`)
Linux redhat 6.5

**Comment by hyperxpro** [comment]
Can you show us the Netty bootstrap code?

**Comment by thineagle** [comment]
the code like this

`private static final EventLoopGroup  group = new NioEventLoopGroup(17);
private Channel channel = null;

private void start() throws Exception {
		
		Bootstrap b = new Bootstrap();
		b.group(group)
		.channel(NioSocketChannel.class)
		.option(ChannelOption.TCP_NODELAY, true)
		.option(ChannelOption.SO_KEEPALIVE, true)
		.handler(new ChannelInitializer<SocketChannel>() {

			@Override
			protected void initChannel(SocketChannel ch) throws Exception {
				
				if (handlers != null && handlers.length > 0) {
					
					for(ChannelHandler handler : handlers) {					
						ch.pipeline().addLast(handler);
					}
					
				}
				
				if (sendHandler == null) {
					throw new RuntimeException("Handler did not implement the TcpSendHandler interface!");
				}
			}
			
		});
		

		ChannelFuture future =  b.connect(host, port).sync();
		this.channel = future.channel();
	`

**Comment by thineagle** [comment]
``private static final EventLoopGroup  group = new NioEventLoopGroup(17);
 
private void start() throws Exception {
		Bootstrap b = new Bootstrap();
		b.group(group)
		.channel(NioSocketChannel.class)
		.option(ChannelOption.TCP_NODELAY, true)
		.option(ChannelOption.SO_KEEPALIVE, true)
		.handler(new ChannelInitializer<SocketChannel>() {

			@Override
			protected void initChannel(SocketChannel ch) throws Exception {
				
				if (handlers != null && handlers.length > 0) {
					
					for(ChannelHandler handler : handlers) {					
						ch.pipeline().addLast(handler);
					}
					
				}
				
				if (sendHandler == null) {
					throw new RuntimeException("Handler did not implement the TcpSendHandler interface!");
				}
			}
			
		});
		

		ChannelFuture future =  b.connect(host, port).sync();
		this.channel = future.channel();`

**Comment by thineagle** [comment]
`	private void start() throws Exception {
		
		Bootstrap b = new Bootstrap();
		b.group(group)
		.channel(NioSocketChannel.class)
		.option(ChannelOption.TCP_NODELAY, true)
		.option(ChannelOption.SO_KEEPALIVE, true)
		.handler(new ChannelInitializer<SocketChannel>() {

			@Override
			protected void initChannel(SocketChannel ch) throws Exception {
				
				if (handlers != null && handlers.length > 0) {
					
					for(ChannelHandler handler : handlers) {

						ch.pipeline().addLast(handler);
					}
					
				}
				
				if (sendHandler == null) {
					throw new RuntimeException("Handler did not implement the TcpSendHandler interface!");
				}
			}
			
		});
		
		//TODO 20181102 预启动线程 BEGIN
		ChannelFuture future =  b.connect(host, port).sync();
		this.channel = future.channel();
		//TODO 20181102 预启动线程 END
	}`

**Comment by hyperxpro** [comment]
Looks like there is a problem with the remote host. Did you checked remote host?

**Comment by thineagle** [comment]
the remote host is normal.  
and if the remote host is down, we can not connect the remote host, default 63s second should have a exception ， but the thread is hangs forever.  connect().sync will create a new thread to notify  the connect thread the connected state . what condition will lead the notify thread can not work?

**Comment by thineagle** [comment]
i found that,  if the client NioEventLoopGroup's some thread is running forever, the connect somtimes will hangs forever.  how the nio group thread selected?  have any suggestion to avoid this ?

**Comment by wwwhongchang** [comment]
@thineagle Has this problem been resolved? How to solve it?
