### ISSUE TITLE
Netty Webpage Fault [Not Code]

### ISSUE THREAD

**Issue by hyperxpro** [netty/netty#10452]
[Netty Adopters](https://netty.io/wiki/adopters.html) page has an `EpollServer` example in the bottom which I should not be there as per my knowledge.

Screenshot attached.

![Netty](https://user-images.githubusercontent.com/24762260/89180546-9c824e80-d5af-11ea-8573-705881b9d958.png)

**Comment by hyperxpro** [comment]
@normanmaurer Please have a look

**Comment by Bennett-Lynch** [comment]
All netty.io/wiki pages apparently:

https://netty.io/wiki/writing-a-commit-message.html

**Comment by hyperxpro** [comment]
Yeah, I know that. But I found `EpollServer` example at
![Screenshot (103)](https://user-images.githubusercontent.com/24762260/89466882-3dc8fa80-d792-11ea-8f0a-4517ee655f73.png)
 the bottom of https://netty.io/wiki/writing-a-commit-message.html also. Interesting,

**Comment by hyperxpro** [comment]
It looks like `EpollServer` example is pretty much everywhere on the website at the bottom.

**Comment by Bennett-Lynch** [comment]
Whatever is generating the HTML content for `<div id="wiki-footer" class="mt-5 mb-0 wiki-footer gollum-markdown-content">` is including it somehow.

**Comment by hyperxpro** [comment]
I checked Revisions of Wiki pages and looks like someone added it for no reason. Maybe we should put restrictions on who can edit Wiki pages.

**Comment by normanmaurer** [comment]
Seems like this was fixed by the last deploy of the website

**Comment by hyperxpro** [comment]
How about adding some restrictions on Wiki so only selected people can change it?
