### ISSUE TITLE
export keying material from tls connection

### ISSUE THREAD

**Issue by kamalthakur1** [netty/netty#10458]
### Problem Statement

I am trying to export the shared keying material that is established during the creation of a TLS connection between the two endpoints.
OpenSSL has the functions SSL_export_keying_material() and SSL_export_keying_material_early() which enable an application to use some of this keying material for its own purposes in accordance with RFC5705 (for TLSv1.2 and below) or RFC8446 (for TLSv1.3).
I am using netty-tcnative with OpenSsl Engine. netty-tcnative using native library: BoringSSL
There in one method in io.netty.internal.tcnative.SSL.setKeyMaterial() to set Keying Material but I could not find any method to export that Keying Material which would be internally mapped to SSL_export_keying_material() function of BoringSsl(fork of OpenSsl).

Is there a way to export keying material using the existing APIs or any way by which I can export keying material.

### Netty version
4.1.50

### JVM version (e.g. `java -version`)
java version "11.0.3" 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)

### OS version (e.g. `uname -a`)
Linux 4.1.12-124.27.1.el7uek.x86_64 #2 SMP Mon May 13 08:56:17 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
We only have `SslMasterKeyHandler` but I am not sure if this is what you are looking for.

**Comment by normanmaurer** [comment]
@kamalthakur1 that said we love contributions. So if you feel a strong need for this feature consider providing a PR
