### ISSUE TITLE
OOM problem using PooledByteBufAllocator.DEFAULT.heapBuffer

### ISSUE THREAD

**Issue by c-s-t-z** [netty/netty#10461]
I have used the ByteBuf object (using PooledByteBufAllocator.DEFAULT.heapBuffer to apply in the A thread) and released it (released in thread B), but this situation still occurs;I checked some information on the Internet, saying that there are cross-line applications/releases that cause memory leaks, but there are different opinions on the Internet; I want to get help from @normanmaurer;what is the reason for my situation:
1 is caused by cross-thread application/release
2 parameter configuration issues;

If it is cause 1, can I set the -Dio.netty.recycler.maxCapacity parameter to zero for this situation? But does this have a greater impact on performance; if it is cause 2, what do I need to deal with in this situation? Parameter adjustment
@normanmaurer for your hard work. Thank you. Thanks again.

My application ran normally for a week, and then many abnormalities occurred. By checking the online monitoring, I found that the memory usage has exceeded expectations;

I saved the scene, checked the heap memory through the dump file, and found that there are large objects in it, namely PoolChunkList and PoolChunk;

The analysis dump picture is as follows:

![20200810040258-1](https://user-images.githubusercontent.com/19266458/89762953-11133b00-db24-11ea-8f6e-01caa1a7a7c0.png)
![20200810040413-2](https://user-images.githubusercontent.com/19266458/89762957-17a1b280-db24-11ea-98cf-dab651f24f66.png)
![20200810040459-3](https://user-images.githubusercontent.com/19266458/89762967-1bcdd000-db24-11ea-80ca-6c9038cdb61f.png)

### Netty version
netty 4.1.6.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
### OS version (e.g. `uname -a`)
Linux al-XXXX 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by c-s-t-z** [comment]
I did not find the LEAK keyword in the log; there is no breakthrough now. For this problem, I hope to get help, thank you very much

**Comment by normanmaurer** [comment]
Please upgrade your netty version first... The version you are using is years old...

**Comment by c-s-t-z** [comment]
Thank you for your reply. I will update the netty version first in the follow-up. If there is a problem, I am troubleshooting feedback, thank you very much.

**Comment by c-s-t-z** [comment]
@normanmaurer
Thank you for your reply, I am still quite curious, where did the problem occur during my use of this version; could you please tell me the reason for the problem?

**Comment by c-s-t-z** [comment]
> @normanmaurer
> Thank you for your reply, I am still quite curious, where did the problem occur during my use of this version; could you please tell me the reason for the problem?


Is it a bug in the netty version itself or a problem with my use, I am worried that this problem will still exist after upgrading to 4.1.5X.Final, thank you @normanmaurer for your patient and professional reply.thank you very much.

**Comment by hyperxpro** [comment]
It could be `Netty 4.1.6.Final` issue, but not sure. That's why you should upgrade to `Netty 4.1.51.Final` and see if the issue still persists.

**Comment by normanmaurer** [comment]
Let me close this for now and please reopen if you still see issues after upgrading
