### ISSUE TITLE
Netty enforce HTTP proxy to support HTTP CONNECT method

### ISSUE THREAD

**Issue by manolvalchev** [netty/netty#10475]
### Expected behavior
In case of HTTP protocol, the client request is sent as is, without sending the initial message with HTTP CONNECT method.

#### Background
> CONNECT
> This specification reserves the method name CONNECT for use with a
> **proxy that can dynamically switch to being a tunnel** (e.g. SSL
> tunneling 44).

Source: https://tools.ietf.org/html/rfc2616#section-9.9

> CONNECT
> The CONNECT method requests that the recipient establish a tunnel to
> the destination origin server identified by the request-target and,
> **if successful, thereafter restrict its behavior to blind forwarding
> of packets, in both directions, until the tunnel is closed**. Tunnels
> are commonly used to create an end-to-end virtual connection, through
> one or more proxies, which can then be secured using TLS (Transport
> Layer Security, RFC5246).
Source: https://tools.ietf.org/html/rfc7231#section-4.3.6

#### Request
No every HTTP proxy supports being a transparent tunnelling proxy. Therefore, Netty as a library shall either react differently on HTTP and HTTPS protocols, or alternatively provide an option to control this behaviour.

This issue is related to:
- https://github.com/netty/netty/issues/3634
- https://github.com/reactor/reactor-netty/issues/159

### Actual behaviour
No matter of the concrete HTTP protocol, HTTP or HTTPS, Netty's [HttpProxyHandler](https://github.com/netty/netty/blob/0c3eae34ec25203e22d3fa6a678a11a936f9c8b4/handler-proxy/src/main/java/io/netty/handler/proxy/HttpProxyHandler.java#L165) always sends HTTP CONNECT request as initial message.

### Steps to reproduce
Use pure Netty (or Spring WebClient based on Netty) as plain HTTP client behind a plain HTTP proxy.

### Minimal yet complete reproducer code (or URL to code)
N/A

### Netty version
Up to 4.1.51.FINAL

### JVM version (e.g. `java -version`)
N/A

### OS version (e.g. `uname -a`)
N/A

**Comment by normanmaurer** [comment]
@manolvalchev do you have any proposal how to "fix" this ?

**Comment by thomas-br** [comment]
Maybe the `ProxyProvider` on `tcpClient.proxy(proxy -> ... )` could receive options to specify whether the tunneling with HTTP CONNECT should be used or plain/normal proxying.

Not sure yet what needs to be changed then in the [HttpProxyHandler](https://github.com/netty/netty/blob/0c3eae34ec25203e22d3fa6a678a11a936f9c8b4/handler-proxy/src/main/java/io/netty/handler/proxy/HttpProxyHandler.java#L165) then to also support normal proxy behavior.

**Comment by violetagg** [comment]
> Maybe the `ProxyProvider` on `tcpClient.proxy(proxy -> ... )` could receive options to specify whether the tunneling with HTTP CONNECT should be used or plain/normal proxying.

@thomas-br The configuration above is Reactor Netty specific and should be discussed in Reactor Netty project when/if there is an extension to the current HttpProxyHandler provided by Netty

**Comment by manolvalchev** [comment]
@normanmaurer, Usually, such a decision is taken based on the URL protocol scheme, e.g. ```http``` -> no usage of CONNECT method; ```https``` -> with usage of CONNECT method. Another option would be to offer configuration parameter, so that the consumer of the library (on the fly, not static for the library) decide whether HTTP CONNECT to be used or not - at the end, the consumer of the proxy knows what are the specifics and requirements of the proxy - the low level library can only help in offering this or that option but IMHO cannot take that decision.

**Comment by thomas-br** [comment]
> @thomas-br The configuration above is Reactor Netty specific and should be discussed in Reactor Netty project when/if there is an extension to the current HttpProxyHandler provided by Netty

@violetagg Agree. But despite the configuration capabilities offered by Reactor Netty, shouldn't both proxy behaviors be offered by the `HttpProxyHandler` of netty? Because as @manolvalchev stated, the current implementations only supports the proxy tunneling.

**Comment by kachayev** [comment]
If there's no need to establish tunnel when connecting to the proxy, the `HttpProxyHandler` would be probably an overkill: no need to create and send initial message, wait for the response, decode it and handle issues as it goes, as well as no need to stash writes before CONNECT response is processed. The only significant difference compared to generic HTTP when not using CONNECT:
* connection should be established to another address
* DNS resolve should be disabled

Which could be done in another handler that only intercepts `connect`. Adding conditional configuration into `HttpProxyHandler` seems somewhat questionable as it basically means conditioning over which methods to overwrite. And as far as decision between tunnel/non-tunnel requires user input (there's no way to figure out if proxy supports tunneling and/or if the tunnel is necessary when it's supported) prior to establishing the connection, the same input could be used to choose between 2 different handlers.

**Comment by slandelle** [comment]
> connection should be established to another address
DNS resolve should be disabled

Also, request url must be absolute instead of relative to domain root.

**Comment by thomas-br** [comment]
@kachayev What do you suggest to continue on this one to get to a suitable solution, maybe similar as in the Aleph framework you showed?
Would that be offering a second non-CONNECT handler which then can be selected in [reactor-netty](https://github.com/reactor/reactor-netty/blob/fbce9325c2da531e1877b6ada84eaf74db3c40fd/reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java#L126) then? Or is there a better solution we can work on?

**Comment by kachayev** [comment]
@thomas-br honestly, I've never worked with `reactor-netty` :) From what I see in `ProxyProvider` code, it seems more than reasonable to add new configuration `tunnel` and when it is set to `false` and `type` = `HTTP`, choose another handler [here](https://github.com/reactor/reactor-netty/blob/fbce9325c2da531e1877b6ada84eaf74db3c40fd/reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java#L124).  Maybe if it's common enough situation, it would be good to have this handler implemented in Netty (like `NonTunnelHttpProxyHandler` or something).

It's still somewhat "messy" and not always intuitive as non-tunnel usage invalidates other parameters, like `username`, `password`, `httpHeaders` etc. But in practice if your proxy asks for user/password, it definitely expectes tunnel.

**Comment by kachayev** [comment]
After some investigation, turned out I was wrong on this:

* DNS resolve should be disabled

In some networks the name resolution is expected to happen on the client rather than on the proxy (typically with custom DNS resolvers or in networks like Tor).

**Comment by manolvalchev** [comment]
It turns out Netty's [ProxyHandler](https://github.com/netty/netty/blob/0c3eae34ec25203e22d3fa6a678a11a936f9c8b4/handler-proxy/src/main/java/io/netty/handler/proxy/ProxyHandler.java) is written with the _wrong_ assumption that every proxy (in general) offers _tunneling_ option with a dedicated protocol-specific handshake based on a <ins>single</ins> request/response mechanism. In case no initial message is sent, and no response is received - it simply times out. Latter seems to be a bug as the impl allow skipping the initial message. Childs have no control over this behaviour.

As per specification, for HTTP protocol, there are two cases:
1. Protocol scheme is "http" - the client has two options - _with_ or _without_ tunneling - the most common option is <ins>without</ins> tunneling, notable examples are cURL, Jetty, Java UrlConnection, Apache HTTP Client, etc.
2. Protocol scheme is "https" - the client must use tunneling

If there is a ```NoTunnelingHttpProxyHandler``` or even ```NoTunnelingProxyHandler``` with just the ```connect()``` method implemented, and if that handler is used, for example, in the reactor-netty's HttpClient pipeline as ProxyHandler, then the scenario would succeed as the only thing that the no tunneling proxy handler would be to connect to the proxy instead of the target host, specified in the HttpClient configuration, either as pure host or as URI. ```Proxy-Authorization``` and other HTTP headers could be handled the same way as in the current implementation of [HttpProxyHandler](https://github.com/netty/netty/blob/0c3eae34ec25203e22d3fa6a678a11a936f9c8b4/handler-proxy/src/main/java/io/netty/handler/proxy/HttpProxyHandler.java).

I see the following options:
- introducing a switch flag stating whether the proxy handler's behaviour shall be tunneling or not - each child can decide by its implementation - it could also be defined by the higher level user in case it's exposed via constructor parameter, for example, in reactor-netty's [ProxyProvider](https://github.com/reactor/reactor-netty/blob/v1.0.0-RC1/reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java#L124) class.
- pass somehow the protocol scheme to the protocol specific handler and let it decide whether to request tunneling or not - again, for the sake of backward compatibility, maybe a flag would be still required
- provide a dedicated impl in Netty for the non-tunneling HTTP proxy handler - ProxyHandler would need to change to an interface as now it's an abstract class and a new impl would not be suitably used, e.g. [ProxyProvider](https://github.com/reactor/reactor-netty/blob/v1.0.0-RC1/reactor-netty-core/src/main/java/reactor/netty/transport/ProxyProvider.java#L124) class.

**Comment by javier-hulft** [comment]
I don't get this... how can a tunnel be established to a remote host without specifying the host in CONNECT?

**Comment by valodzka** [comment]
Via request like this:

    GET http://ipinfo.io/ HTTP/1.1
    Host: ipinfo.io
    User-Agent: curl/7.64.0
    Accept: */*
    Proxy-Connection: Keep-Alive

**Comment by jeffreyschultz** [comment]
HTTP Connect support should allow you to CONNECT to HTTP and HTTPS target sites. This supports the forward proxy use case, while it seems to me through a cursory glance of the source code that Proxy support currently exists as a Reverse Proxy configuration, where you predetermine the destination of request.

I am looking into this now because I have a need for a forward proxy capable of tunneling to both HTTP and HTTPS web servers within a private vlan. The proxy must support a request pipeline for adding behavior to the request handlers, such as first redirecting them to a auth webapp to authenticate, and then allowing access to certain apps based on their authorization. The web apps themselves will also implement authorization, but the intent is to be able to forward certain clients to certain environments, since it will be a cornerstone of our multi-tenant approach. One idea is allow forward requests based on the users account into specific Kubernetes namespaces, but I digress...

We will also need SOCKS5 forward proxy functionality as well, but that seems to be outside the scope of Netty itself. I could certainly develop a SOCKS5 proxy using Netty, but core functionality seems related to HTTP/HTTPS.

**Comment by Kitanotori** [comment]
Is there no workaround? This issue is currently blocking us from using Netty and consequently also WebFlux. We don't have control over the proxies. There is no issue with RestTemplate, so the only choice would be to fall back to using RestTemplate and WebMVC.

**Comment by Kitanotori** [comment]
Just found a workaround. For Spring Boot users, the workaround is to use jetty-reactive-httpclient as WebClient's client connector.

Example: https://www.baeldung.com/jetty-reactivestreams-http-client

**Comment by idelpivnitskiy** [comment]
`netty-handler-proxy` module and it's abstract `ProxyHandler` is designed specifically for tunneling use-cases that require a protocol-dependent message exchange before switching to a tunnel mode, like HTTP CONNECT or SOCKSx. 

The copied RFC sections highlight that SSL/TLS **can** be used, but not required. Going through a blind forwarding tunnel for both http and https requests is correct.

I'm agreed that HTTP also supports a 3rd option for proxying of http requests without the tunnel.
However, it's outside of `HttpProxyHandler` responsibilities. When this use-case is required, users should not use `HttpProxyHandler` (or any other variant of `ProxyHandler` subclass) at all. Instead, they have 2 options:
1. Connect to `proxyAddress` and send `HttpRequest`(s) with absolute-form request-target manually.
2. Implement a `ChannelOutbountHandler` that will intercept `connect` and `write` methods with a goal to replace `remoteAddress` and rewrite the relative-form request-target into absolute-form for all outgoing requests.

It will be great to clarify that in javadoc for `HttpProxyHandler`.

**Comment by mannprerak2** [comment]
Another hack I used was to implement an `AddressResolverGroup<InetSocketAddress>` that can be supplied in `httpClient.resolver`. And then simply return `new InetSocketAddress(SocketUtils.addressByName(proxyHost), proxyPort)` as the address.

Not sure how performant this is, but for my dev use cases, it worked.

<details>
<summary>Example implementation I used in spring boot</summary>

```java
/**
 * A helper class to configure a http proxy.
 *
 * Spring autoconfigures this as it implements HttpClientCustomizer for gateway
 * outbound requests, but any webclient must manually call this.
 */
@Component
public class LocalProxyConfig implements HttpClientCustomizer {
 
    @Override
    public HttpClient customize(HttpClient httpClient) {
        // Configure http proxy.
        if (StringUtils.isNotBlank(System.getProperty("http.proxyHost"))) {
            httpClient = httpClient.resolver(new LocalProxyNameResolverGroup(
                    System.getProperty("http.proxyHost"),
                    Integer.parseInt(System.getProperty("http.proxyPort", "80"))));
        }
        return httpClient;
    }
 
    @AllArgsConstructor
    public final class LocalProxyNameResolverGroup extends AddressResolverGroup<InetSocketAddress> {
        private final String proxyHost;
        private final Integer proxyPort;
 
        @Override
        protected AddressResolver<InetSocketAddress> newResolver(EventExecutor executor) throws Exception {
            return new LocalProxyInetSocketAddressResolver(executor, proxyHost, proxyPort);
        }
    }
 
    public class LocalProxyInetSocketAddressResolver extends AbstractAddressResolver<InetSocketAddress> {
        private final String proxyHost;
        private final Integer proxyPort;
 
        public LocalProxyInetSocketAddressResolver(EventExecutor executor, String proxyHost, Integer proxyPort) {
            super(executor, InetSocketAddress.class);
            this.proxyHost = proxyHost;
            this.proxyPort = proxyPort;
        }
 
        @Override
        protected boolean doIsResolved(InetSocketAddress address) {
            return !address.isUnresolved();
        }
 
        @Override
        protected void doResolve(final InetSocketAddress unresolvedAddress, final Promise<InetSocketAddress> promise)
                throws Exception {
            try {
                promise.setSuccess(new InetSocketAddress(SocketUtils.addressByName(proxyHost), proxyPort));
            } catch (Exception e) {
                promise.setFailure(e);
            }
        }
 
        @Override
        protected void doResolveAll(final InetSocketAddress unresolvedAddress,
                final Promise<List<InetSocketAddress>> promise) throws Exception {
            try {
                promise.setSuccess(List.of(new InetSocketAddress(SocketUtils.addressByName(proxyHost), proxyPort)));
            } catch (Exception e) {
                promise.setFailure(e);
            }
        }
    }
}
```

</details>
