### ISSUE TITLE
Ability to change the logger and level used by DnsNameResolverBuilder#traceEnabled

### ISSUE THREAD

**Issue by violetagg** [netty/netty#10485]
### Expected behavior
Ability to change the logger and level used by `DnsNameResolverBuilder#traceEnabled`

### Actual behavior
When `DnsNameResolverBuilder#traceEnabled` is enabled, it uses always the logger and level below
https://github.com/netty/netty/blob/46cb4015ff25ff2dd3d0dede5c3185ac498e56b0/resolver-dns/src/main/java/io/netty/resolver/dns/TraceDnsQueryLifeCycleObserverFactory.java#L26-L28

It would be nice if those can be configured.

Possible solutions:
- `DnsNameResolverBuilder#traceEnabled` where one can specify logger and level

Or

- `TraceDnsQueryLifeCycleObserverFactory` can be made public and also it can expose construction similar to what `LoggingHandler` provides i.e.

```
    public TraceDnsQueryLifeCycleObserverFactory(Class<?> clazz, LogLevel level) {
        ObjectUtil.checkNotNull(clazz, "clazz");
        ObjectUtil.checkNotNull(level, "level");
        this.logger = InternalLoggerFactory.getInstance(clazz);
        this.level = level.toInternalLevel();
    }
```

With this approach one will be able to add such observer with `DnsNameResolverBuilder#dnsQueryLifecycleObserverFactory`

this second approach will require a dependency to `netty-handler` module

Wdyt?

### Netty version
current snapshot

### JVM version (e.g. `java -version`)
jdk 8

### OS version (e.g. `uname -a`)
Mac OS

**Comment by chrisvest** [comment]
It's not clear to me why you want to change the log level, and if you want to change it to TRACE or INFO, or some other level? Log levels are normally hard-coded on the usage site, and the current code follows that convention.

This setting is about whether or not logging is enabled. Detail configuration of how logging works is something we'd prefer to leave to the logging framework.

**Comment by violetagg** [comment]
@chrisvest The use case is the following: Reactor Netty wants to expose this as a configuration so that the user can decide which logger and what level to use. With the current approach the user sees that the tracing is enabled but needs to know the exact logger and level that are needed (which are not from Reactor Netty but from a library that Reactor Netty uses)

**Comment by chrisvest** [comment]
But that's the case with all logging in Netty, isn't it? Well, almost I suppose. The logging implementation that is used everywhere is discovered at runtime, and the level is always hard coded, with the exception of `LoggingHandler` and `Http2FrameLogger`. With that in mind I think the second approach makes the most sense: expose some clean-up version of `TraceDnsQueryLifeCycleObserverFactory`, and remove `traceEnabled`.

**Comment by violetagg** [comment]
> But that's the case with all logging in Netty, isn't it? Well, almost I suppose. The logging implementation that is used everywhere is discovered at runtime, and the level is always hard coded, with the exception of `LoggingHandler` and `Http2FrameLogger`. With that in mind I think the second approach makes the most sense: expose some clean-up version of `TraceDnsQueryLifeCycleObserverFactory`, and remove `traceEnabled`.

Yes I agree from my point of view it is like `LoggingHandler`, I can add this handler to the pipeline. The same is with `TraceDnsQueryLifeCycleObserverFactory` I can add it to the configuration.
