### ISSUE TITLE
DatagramPacket is not sent if InetSocketAddress is unresolved

### ISSUE THREAD

**Issue by hyperxpro** [netty/netty#10484]
### Expected behavior
Netty should send DatagramPacket if the host is IP address.

### Actual behavior
Netty does not send DatagramPacket if InetSocketAddress is created using `#createUnresolved(String host, int port)` and the host is an IP address.

We can send the packet to an IP address because IP address does not need any kind of resolution.

### Steps to reproduce
Just create InetSocketAddress using `#createUnresolved(String host, int port)`

### Minimal yet complete reproducer code (or URL to code)
```java
Channel#writeAndFlush(new DatagramPacket(Unpooled.wrappedBuffer("Meow".getBytes()), InetSocketAddress.createUnresolved("127.0.0.1", 9110)));
```

### Netty version
4.1.51.Final

### JVM version (e.g. `java -version`)
OpenJDK Runtime Environment Corretto-11.0.5.10.1 (build 11.0.5+10-LTS)

### OS version (e.g. `uname -a`)
Microsoft Windows 10 Pro 10.0.19041 N/A Build 19041 x64

**Comment by normanmaurer** [comment]
@hyperxpro you have a stack trace for the failed write ?

**Comment by normanmaurer** [comment]
actually that is expected and exactly what java.io and java.nio does.

**Comment by hyperxpro** [comment]
I see, my bad. Sorry!
