### ISSUE TITLE
Is SniHandler vulnerable to partial Client Hello message attack?

### ISSUE THREAD

**Issue by aspcompiler** [netty/netty#10496]
Suppose an attacker send a partial Client Hello message and leave the connection open, would SniHandler wait indefinitely for the remaining part of the message?

I was looking for a timeout that would close the connection if the remaining part of the message does not arrive within a timeout limit, but I did not find one in the class hierarchy.

Just to ensure that I did not miss anything.

### Netty version
4.1

**Comment by Bennett-Lynch** [comment]
I don't think any of the codec-level handlers enforce timeouts. You are expected to use an `IdleStateHandler` to define and enforce your own timeouts, if needed.

**Comment by qerub** [comment]
I haven't looked at the details, but maybe `SslHandler`'s `setHandshakeTimeout` might come in handy: https://netty.io/4.1/api/io/netty/handler/ssl/SslHandler.html#setHandshakeTimeout-long-java.util.concurrent.TimeUnit-

**Comment by aspcompiler** [comment]
I am not sure if IdleStateHandler is granular enough. I can use IdleStateHandler to close the connection if no traffic for sometime after the handshake. "setHandshakeTimeout" is closer to what I need as it enforce that the handshake completes within a limit. It seems that we need another level of timeout to enforce that all packets of a message received within a limit.

**Comment by normanmaurer** [comment]
just put the `IdleStateHandler` in front of the `SniHandler` that will do the trick.
