### ISSUE TITLE
[Question] how does netty process reset command ?

### ISSUE THREAD

**Issue by francisoliverlee** [netty/netty#10504]
### description
client would do handshaking with jdbc server every 2 seconds  to check whether it is  alive. then send reset command to close tcp, but there are a lot of closed-connections hold by jdbc server.
i wander how netty do with reset command. 

![image](https://user-images.githubusercontent.com/5908412/91313678-38d2f600-e7e8-11ea-8ac9-44cb5926081a.png)

### Netty version
netty-all 4.1.42.Final
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
centos 7.3

**Comment by hyperxpro** [comment]
Netty Handler will receive exception about connection closed by the host and it'll be treated as a normal connection close.

**Comment by hyperxpro** [comment]
> Netty Handler will receive exception about connection closed by the host and it'll be treated as a normal connection close.

And I hope you mean RST, not FIN.
