### ISSUE TITLE
[Question] How to configure max no of connection in Netty server?

### ISSUE THREAD

**Issue by harshmah** [netty/netty#10519]
### Expected behavior
I am new to Netty world. In my project, we are using Netty along with WebFlux. I come from Tomcat world.  My question is in Netty, how can we can limit no of threads (like in Tomcat have setting max-thread)? Is this configurable? If yes, please refer me some doc. Thanks

**Comment by violetagg** [comment]
@harshmah Spring WebFlux uses Reactor Netty and not Netty directly. Use https://gitter.im/reactor/reactor-netty for questions related to Reactor Netty.

**Comment by hyperxpro** [comment]
AFAIK, no way to specify number of maximum connection but I can add this functionality. We can define maximum connection, maximum connections per minute (rate limit thing), etc.

What you say @normanmaurer ?

**Comment by normanmaurer** [comment]
Like @violetagg said... this is not a netty question
