### ISSUE TITLE
whick highest version is support for jdk1.7

### ISSUE THREAD

**Issue by github-big-cheng** [netty/netty#10516]
### Expected behavior

When I upload a big file (more than 100 kb), the `FileUpload.getFile()` return a size of 16 kb File on jdk1.7, but it's ok on jdk1.8
so I want to know what's the highest `Netty` version supported for jdk1.7 ?
So kind of you all! Thanks .

### Steps to reproduce

with url http://127.0.0.1/version/add to upload a big file

### Minimal yet complete reproducer code (or URL to code)

https://github.com/github-big-cheng/upgrade.git

### Netty version

4.1.51.Final
4.1.10.Final

### JVM version (e.g. `java -version`)

jdk 1.7 / 1.8

### OS version (e.g. `uname -a`)

windows 10

**Comment by github-big-cheng** [comment]
> ### Expected behavior
> When I upload a big file (more than 100 kb), the `FileUpload.getFile()` return a size of 16 kb File on jdk1.7, but it's ok on jdk1.8
> so I want to know what's the highest `Netty` version supported for jdk1.7 ?
> So kind of you all! Thanks .
> 
> ### Actual behavior
> ### Steps to reproduce
> with url http://127.0.0.1/version/add to upload a big file
> 
> ### Minimal yet complete reproducer code (or URL to code)
> https://github.com/github-big-cheng/upgrade.git
> 
> ### Netty version
> 4.1.51.Final
> 4.1.10.Final
> 
> ### JVM version (e.g. `java -version`)
> jdk 1.7 / 1.8
> 
> ### OS version (e.g. `uname -a`)
> windows 10
I'm so sorry ! It wasn't described clearly, I used 4.1.51.Final on jdk1.7, it doesn't works. but  4.1.10.Final can fixed it (1.7).
So I want a version can works on jdk 1.7 .
Thanks...

**Comment by hyperxpro** [comment]
Netty is working fine up to Java 15 right now.

**Comment by github-big-cheng** [comment]
> Netty is working fine up to Java 15 right now.

Threre are some old programs used jdk 1.7 ,  and  the jave version can't be upgraded. 
So I want a version can run Netty fine up on jdk 1.7. 
May I get a better version ? Thanks...

**Comment by johnou** [comment]
@github-big-cheng sounds like a regression, is an exception thrown?

**Comment by hyperxpro** [comment]
> > Netty is working fine up to Java 15 right now.
> 
> Threre are some old programs used jdk 1.7 , and the jave version can't be upgraded.
> So I want a version can run Netty fine up on jdk 1.7.
> May I get a better version ? Thanks...

4.1.X versions are perfect for Java 1.7.

**Comment by johnou** [comment]
@github-big-cheng looks like a regression which is fixed in the next release https://github.com/netty/netty/issues/10449

**Comment by github-big-cheng** [comment]
> @ github-big-cheng看起来像一个回归，该回归已在下一个版本[＃10449中修复](https://github.com/netty/netty/issues/10449)

Does it means it will be fixed in 4.1.52.Final ?

**Comment by normanmaurer** [comment]
It should just work with any 4.1.x release. If that’s not the case please provide a stacktrace etc

**Comment by github-big-cheng** [comment]
there are some pictures about my problem.
Is threre any different configs in version 4.1.51.Final ?
<img width="966" alt="e43ffc5ae3d4be3e176826fed3fa792" src="https://user-images.githubusercontent.com/20948229/91675246-4254b900-eb6e-11ea-93b4-a1c361b64c34.png">
<img width="966" alt="1b48a32eeff393e78d571fe8d5aa6e1" src="https://user-images.githubusercontent.com/20948229/91675250-44b71300-eb6e-11ea-9142-f6aa8b65cf63.png">
<img width="966" alt="2f5cf84c9dff3c14553fa7678c0c0aa" src="https://user-images.githubusercontent.com/20948229/91675253-4680d680-eb6e-11ea-8258-cf39837a926b.png">

**Comment by johnou** [comment]
@github-big-cheng please try 4.1.52 when it is released.

**Comment by github-big-cheng** [comment]
> @github-big-cheng please try 4.1.52 when it is released.

Thanks a lot, looking forward for 4.1.52.released.
