### ISSUE TITLE
Netty should always provide a terminal event for WebSocket Handshake

### ISSUE THREAD

**Issue by divijvaidya** [netty/netty#10515]
I have a client implementation which uses SSL Handler with `WebSocketClientProtocolHandshakeHandler`. If SSL handshake fails for some reason, it leads to channel close which deactivates/deregisters the WebSocket handler. The client implementation has a WebSocket connection initialization logic that is performing a sync wait for either `ClientHandshakeStateEvent.HANDSHAKE_TIMEOUT` or `ClientHandshakeStateEvent.HANDSHAKE_COMPLETE`.

### Expected behavior
After handshake has been started i.e. `ClientHandshakeStateEvent.HANDSHAKE_ISSUED` has been triggered, one of either `ClientHandshakeStateEvent.HANDSHAKE_TIMEOUT` or `ClientHandshakeStateEvent.HANDSHAKE_COMPLETE` must always be triggered.

### Actual behavior
In certain cases when the Channel is closed before the callback could be invoked neither of the above events are triggered. In such cases the sync wait on the application defined above waits indefinitely.

I can fix this situation on my application my interrupting the sync wait on channel closure, but I think it would be cleaner if my application could rely on Netty to always provide a terminal event for a handshake.

### Steps to reproduce
Similar to the unit test added in https://github.com/netty/netty/pull/10510

1. Add a handler in the chain that waits on a terminal `ClientHandshakeStateEvent`s to proceed ahead with the business logic. Currently, the two terminal events are: `HANDSHAKE_COMPLETE` and `HANDSHAKE_TIMEOUT`.
2. Start WebSocket handshake.
3. Assert `HANDSHAKE_ISSUED` is received.
4. Close the channel before the handshake can complete.
5. Observe that no terminal event reaches the client handler introduced in step 1.

### Minimal yet complete reproducer code (or URL to code)
The test case would be similar to the one added in https://github.com/netty/netty/pull/10510

### Netty version
4.1

### Suggested improvement
Either of the two options below would work:

Option 1: Add a new event `ClientHandshakeStateEvent.HANDSHAKE_FAILED` which would be triggered if anything (including channel closure) goes wrong during the handshake.

Option 2: Provide public access to the `handshakePromise` in `WebSocketClientProtocolHandshakeHandler.java` which should be completed on `ChannelInactive`

**Comment by normanmaurer** [comment]
This was fixed by #10510

**Comment by divijvaidya** [comment]
@normanmaurer #10510 does not address the scenario described in the issue. That PR simply ensures that the resources (executor threads) and the scheduled timer is cleared if channel is closed.

This issue discusses a very different problem i.e. the handshake process does not provide a terminal event. I have provided two suggestions at the end of the description. I would be happy to implement once we could arrive at a conclusion about the preferred approach.

Please re-open this issue.
