### ISSUE TITLE
Is one netty's channel map to a tcp connection and a socket port?

### ISSUE THREAD

**Issue by KaimingWan** [netty/netty#10512]
Another question is that can I parallel send data in multi thread over a single tcp connection? If the answer is yes,let's see the case. The first send request from client are blocked in server caused by some code bug. Can other thread's callback listener receive their response successfully?

**Comment by hyperxpro** [comment]
You should consider [Stackoverflow - Netty](https://stackoverflow.com/questions/tagged/netty) for questions.

Coming to your question, if you've 4 workers and 1 worker is blocked for some reason. Let's say, heavy processing or something, the other 4 workers will handle the traffic. However, you should not block Netty workers.

**Comment by KaimingWan** [comment]
@hyperxpro Thanks for your remind. I will move the question to stackoverflow. As what you said, netty server can process multi client thread's request in parallel. How netty ensure their order?

**Comment by hyperxpro** [comment]
Netty doesn't use threads. It's event-loop based.
