### ISSUE TITLE
I deployed the Netty service in Tomcat

### ISSUE THREAD

**Issue by thisIBaby** [netty/netty#10536]
I deployed the Netty service in Tomcat. The server receives the data normally, but the client cannot receive the data. It is normal for a Netty client not running in Tomcat to receive data
### JVM version (e.g. `java -version`)e
java 1.8  Tomcat8.57
### OS version (e.g. `uname -a`)
win7

**Comment by hyperxpro** [comment]
More details needed.

**Comment by thisIBaby** [comment]
This is how I respond to the data to the client

`private void OnoffLoad(NetMessage nms, ChannelHandlerContext ctx) {
		if (StringUtils.isNotEmpty( nms.getContent().toString() )) {
			 
			ctx.writeAndFlush(JSON.toJSONString(new NetMessage("",PacketType.ONOFF_LOAD_COMMIT, null)) + "$_$");
		}
	}`
The client sent data into this method without any errors,  ctx. writeAndFlush also performs normally. 
However, my client could not receive any data

io.netty   version ：4.1.29.Final

**Comment by thisIBaby** [comment]
My project environment
`<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>2.1.0.RELEASE</version>
				<type>pom</type>
				<scope>import</scope>
				<exclusions>
					<exclusion>
						<groupId>org.springframework.boot</groupId>  
                    	<artifactId>spring-boot-starter-tomcat</artifactId> 
					</exclusion>
				</exclusions>
			</dependency>
		</dependencies>`

**Comment by hyperxpro** [comment]
> This is how I respond to the data to the client
> 
> `private void OnoffLoad(NetMessage nms, ChannelHandlerContext ctx) {
> if (StringUtils.isNotEmpty( nms.getContent().toString() )) {
> 
> ```
> 		ctx.writeAndFlush(JSON.toJSONString(new NetMessage("",PacketType.ONOFF_LOAD_COMMIT, null)) + "$_$");
> 	}
> }`
> ```
> 
> The client sent data into this method without any errors, ctx. writeAndFlush also performs normally.
> However, my client could not receive any data
> 
> io.netty version ：4.1.29.Final

An error is being thrown but you're not catching it. You need a Listener for that.
Try this:

```java
ByteBuf byteBuf = ctx.alloc().buffer();
byteBuf.writeCharSequence(JSON.toJSONString(new NetMessage("",PacketType.ONOFF_LOAD_COMMIT, null)) + "$_$", StandardCharsets.UTF_8);
ctx.writeAndFlush(bytebuf);
```

**Comment by thisIBaby** [comment]
Thank you. The problem has been solved.

**Comment by hyperxpro** [comment]
Make sure to write ByteBuf not just any object.

:)
