### ISSUE TITLE
About io.netty.util.Recycler object pool object recycling

### ISSUE THREAD

**Issue by wind-clothes** [netty/netty#10532]
### Actual behavior
Hello, when will the objects in the Netty object pool (io.netty.util.Recycler) be recycled by the JVM gc, because there are a large number of
io.netty.util.Recycler$DefaultHandle[] io.netty.util.Recycler$WeakOrderQueue$Link
### Netty version
4.1.39-Final
### JVM version (e.g. `java -version`)
1.8.0_191

**Comment by ninja-** [comment]
These will not be recycled because that's a cache.
How large is your JVM heap and what % is occupied by recycler?
There are java properties to tune the recycler but there's a large chance you don't need to do this.

**Comment by wind-clothes** [comment]
@ninja- 
What I understand is the weak reference used by the Netty object pool. Will it be fully recycled in a Young GC or Full GC?

**Comment by Shevchik** [comment]
WeakOrderQueue is weak itself, not the objects it references, and will GCed when the thread that used the cache will be GCed.

**Comment by wind-clothes** [comment]
@Shevchik 
Thanks for your answer, when will the following objects be recycled by gc:
io.netty.util.Recycler $ DefaultHandle []
io.netty.util .Recycler $ WeakOrderQueue $ Link

**Comment by Shevchik** [comment]
When the recycler itself will be GCed.
