### ISSUE TITLE
EpollSocketChannel cannot be cast to NioSocketChannel

### ISSUE THREAD

**Issue by CalvinKirs** [netty/netty#10531]
Sep 04, 2020 4:56:48 AM io.netty.channel.ChannelInitializer exceptionCaught
WARNING: Failed to initialize a channel. Closing: [id: 0x11c90191, L:/127.0.0.1:12346 - R:/127.0.0.1:56476]
java.lang.ClassCastException: io.netty.channel.epoll.EpollSocketChannel cannot be cast to io.netty.channel.socket.nio.NioSocketChannel

### Netty version
4.1.33

### JVM version (e.g. `java -version`)
1.8

### OS version (e.g. `uname -a`)
linux

**Comment by hyperxpro** [comment]
You cannot cast `EpollSocketChannel` to `NioSocketChannel` and it's perfectly normal. The bug is in your code. Not Netty Issue,

**Comment by CalvinKirs** [comment]
Thx, this is my problem
