### ISSUE TITLE
Waited 10000 milliseconds for org.apache.drill.shaded.guava.com.google.common.util.concurrent.SettableFuture@6c2d4cc6[status=PENDING]

### ISSUE THREAD

**Issue by alkakumari42** [netty/netty#10550]
Hi, I have upgraded Netty jar from 4.0.48.Final to 4.1.50.Final. I have made the required code changes. After running my drill project with the new Netty version Plain connection without SSL is working. While not able to connect to drillbit with enabling SSL . 
Below error is coming (without stack trace)
Waited 10000 milliseconds for org.apache.drill.shaded.guava.com.google.common.util.concurrent.SettableFuture@6c2d4cc6[status=PENDING]

It would be great if someone can suggest is this issue related to Netty.

### Netty version
4.1.50.Final

### JVM version (e.g. `java -version`)
JAVA 8

**Comment by hyperxpro** [comment]
Show `SslContext` code.

**Comment by alkakumari42** [comment]
Hi,
 SslContext code is the same as of io.netty.handler.ssl.SslContext.java. Do you want me to show this code?

**Comment by hyperxpro** [comment]
The builder code I mean. Show.

**Comment by normanmaurer** [comment]
I will close this as @alkakumari42 never responded...
