### ISSUE TITLE
Cannot access 'MqttSubscriptionOption.RetainedHandlingPolicy' in 4.1.52.Final

### ISSUE THREAD

**Issue by sealte** [netty/netty#10562]
### Expected behavior
when i do 'new MqttSubscriptionOption(MqttQoS.AT_LEAST_ONCE, true, true, MqttSubscriptionOption.RetainedHandlingPolicy.SEND_AT_SUBSCRIBE_IF_NOT_YET_EXISTS)',   

'MqttSubscriptionOption.RetainedHandlingPolicy' should be accessable 

### Actual behavior

but 'MqttSubscriptionOption.RetainedHandlingPolicy' cannot be access in 4.1.52.Final 

### Steps to reproduce

MqttMessageBuilders.subscribe()
                        .addSubscription(topic, new MqttSubscriptionOption(MqttQoS.AT_LEAST_ONCE, true, true, MqttSubscriptionOption.RetainedHandlingPolicy.SEND_AT_SUBSCRIBE_IF_NOT_YET_EXISTS))

### Netty version

4.1.52.Final

### JVM version (e.g. `java -version`)

openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.1+9, mixed mode, sharing)

### OS version (e.g. `uname -a`)
Darwin vapple.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
@paul-lysak  can you have a look ?

**Comment by paul-lysak** [comment]
> @paul-lysak can you have a look ?

Ok, will take a look tomorrow.

**Comment by paul-lysak** [comment]
Actually, done today: https://github.com/netty/netty/pull/10565/files
