### ISSUE TITLE
Why is read() method defined in ChannelOutboundHandler rather than ChannelInboundHandler

### ISSUE THREAD

**Issue by RaulGuo** [netty/netty#10567]
As far as I understand, ChannelInboundHandler should be used to handle IO inbound event, while ChannelOutboundHandler should be used to handle outbound event. And that is confirmed by the Java doc of ChannelHandler

> ChannelHandler itself does not provide many methods, but you usually have to implement one of its subtypes:
ChannelInboundHandler to handle inbound I/O events, and ChannelOutboundHandler to handle outbound I/O operations.

So, I can surely understand that write() is an outbound event so it should be defined in ChannelOutboundHandler, but it confuses me when I saw that read() is also defined in ChannelOutboundHander, as I understand, read() should be an inbound event, so it should be defined in ChannelInboundHandler. Did I understand sth wrong? How should I understand this design?

```
public interface ChannelOutboundHandler extends ChannelHandler {
    /**
     * Intercepts {@link ChannelHandlerContext#read()}.
     */
    void read(ChannelHandlerContext ctx) throws Exception;

    /**
    * Called once a write operation is made. The write operation will write the messages through the
     * {@link ChannelPipeline}. Those are then ready to be flushed to the actual {@link Channel} once
     * {@link Channel#flush()} is called
     *
     * @param ctx               the {@link ChannelHandlerContext} for which the write operation is made
     * @param msg               the message to write
     * @param promise           the {@link ChannelPromise} to notify once the operation completes
     * @throws Exception        thrown if an error occurs
     */
    void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) throws Exception;

}
```

**Comment by hyperxpro** [comment]
For reading data from Outbound Channel.

**Comment by RaulGuo** [comment]
> For reading data from Outbound Channel.

@hyperxpro Thank you for your reply, you mean the read() method will be a call back method when the Outbound Channel is beging readed, right? And I saw that in ChannelInboundHandler, there are two method related to read:

```
public interface ChannelInboundHandler extends ChannelHandler {
    /**
     * Invoked when the current {@link Channel} has read a message from the peer.
     */
    void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception;

    /**
     * Invoked when the last message read by the current read operation has been consumed by
     * {@link #channelRead(ChannelHandlerContext, Object)}.  If {@link ChannelOption#AUTO_READ} is off, no further
     * attempt to read an inbound data from the current {@link Channel} will be made until
     * {@link ChannelHandlerContext#read()} is called.
     */
    void channelReadComplete(ChannelHandlerContext ctx) throws Exception;
}
```
So, let's assume we have an inbound channel A and an outbound Channel B, and A read data from B, then the Inbound Handler of Channel A will have its channelRead and channelReadComplete method invoked, and the Outbound Handler of Channel B will have its read method invoked, is this right?

**Comment by normanmaurer** [comment]
read() signals we want to read something. This means as soon as some data can be read we will do so and dispatch it via channelRead(...)

**Comment by RaulGuo** [comment]
@normanmaurer So, the read() method will be invoked when current channel is prepared to be readed? maybe renaming the function to sth else, like readable() will be more easy to understand.
