### ISSUE TITLE
is there any way to customize ssl ClientHello message ?

### ISSUE THREAD

**Issue by swoky** [netty/netty#10579]
i am using netty as the http client , 
and  SslProvider  is  OPENSSL ,
i want to modify the Extension part ,
so is there any way to customize ssl ClientHello message ?

### Expected behavior

support a handler to customize the ClientHello message before handshake.

### Netty version
4.1.50
### JVM version (e.g. `java -version`)
jdk8
### OS version (e.g. `uname -a`)
win7

**Comment by hyperxpro** [comment]
Add handler before SslHandler and modify the `ByteBuf` containing `ClientHello` message of TLS.

**Comment by normanmaurer** [comment]
@swoky what exactly you want to modify there ?

**Comment by swoky** [comment]
@normanmaurer  Actually i am using netty as the crawler , 
the problem now is about the SSL Fingerprints ,  see [https://github.com/salesforce/ja3](url)  ,
so i want to change the Extension part randomly, 
such as the supportedCurves , supportedPoints,  etc

**Comment by normanmaurer** [comment]
@swoky as @hyperxpro said you may be able to modify the `ByteBuf`. Thats the only way I can think of atm.
