### ISSUE TITLE
Add validation check about websocket path

### ISSUE THREAD

**Issue by Doyuni** [netty/netty#10582]
### Expected behavior

If I add WebSocketServerProtocolHandler like below,
```java
private final String WEBSOCKET_PATH = "/websocket";

// ~~

final ChannelPipeline p = ch.pipeline();

p.addLast(new WebSocketServerProtocolHandler(WEBSOCKET_PATH, true));
```
I expected :
 `/websocket/a` : return true
 `/websocketabc` : return false
 `/websocket?name=doyuni` : return true

### Actual behavior

But it return true on all above case.

I don't want this handler to pass `/websocketabc` through.

### Steps to reproduce

Just modify one method like below code. 

### Minimal yet complete reproducer code (or URL to code)
- WebSocketServerProtocolHandshakeHandler
```java
private boolean isNotWebSocketPath(FullHttpRequest req) {
    String websocketPath = serverConfig.websocketPath();
    char nextStartUri = '/';
    if (req.uri().length() > websocketPath.length()) nextStartUri = req.uri().charAt(websocketPath.length());  
    return serverConfig.checkStartsWith() ? !(req.uri().startsWith(websocketPath) && (nextStartUri == '/' || nextStartUri == '?')) 
                                          : !req.uri().equals(websocketPath);
}
```

### Netty version

- 4.1.52.Final

### JVM version (e.g. `java -version`)
```
java version "11.0.5" 2019-10-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.5+10-LTS, mixed mode)
```
### OS version (e.g. `uname -a`)

- Mac OS Catalina v. 10.15.6

**Comment by normanmaurer** [comment]
@Doyuni please open a PR with the fix and a testcase-

**Comment by Doyuni** [comment]
> @Doyuni please open a PR with the fix and a testcase-

Okay I got it.
