### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: io.netty.util.concurrent.OrderedEventExecutor

### ISSUE THREAD

**Issue by hussain-k1** [netty/netty#10592]
Having this Caused by: java.lang.ClassNotFoundException: io.netty.util.concurrent.OrderedEventExecutor
 error in when using Netty 4.1. Please suggest a work around, Thanks

**Comment by hyperxpro** [comment]
Missing dependencies.

**Comment by normanmaurer** [comment]
This means you don't have "netty-common" on the class path.
