### ISSUE TITLE
What's the use of function addToVariablesToRemove() in FastLocalThread

### ISSUE THREAD

**Issue by prgitpr** [netty/netty#10599]
### Expected behavior

I just what to know the use of function addToVariablesToRemove() in FastLocalThread , I think  variable index can as a identity of FastLocalThread. 

/*
 private static void addToVariablesToRemove(InternalThreadLocalMap threadLocalMap, FastThreadLocal<?> variable) {

        Object v = threadLocalMap.indexedVariable(variablesToRemoveIndex);

        Set<FastThreadLocal<?>> variablesToRemove;

        if (v == InternalThreadLocalMap.UNSET || v == null) {

            variablesToRemove = Collections.newSetFromMap(new IdentityHashMap<FastThreadLocal<?>, Boolean>());

            threadLocalMap.setIndexedVariable(variablesToRemoveIndex, variablesToRemove);

        } else {

            variablesToRemove = (Set<FastThreadLocal<?>>) v;

        }

        variablesToRemove.add(variable);

    }

*/

hope for your reply

**Comment by MrLawrenc** [comment]
What's the reason

**Comment by chrisvest** [comment]
It's used for tracking all thread local variables created in any given thread, so that a thread can bulk-remove all of its thread-local variables.

**Comment by MrLawrenc** [comment]
> It's used for tracking all thread local variables created in any given thread, so that a thread can bulk-remove all of its thread-local variables.

why not delete the threadLocalMap?this can also achieve the purpose of deleting all
why use SetFromMap instead of list.I do not understand.
hope you can answer
