### ISSUE TITLE
OpenSslHandler should allow modification of SSLHandshake timeout

### ISSUE THREAD

**Issue by divijvaidya** [netty/netty#10608]
### Expected behavior
I want to modify the [SSL Handshake timeout](https://netty.io/4.1/api/io/netty/handler/ssl/SslHandler.html#setHandshakeTimeout-long-java.util.concurrent.TimeUnit-) defined in [SSLHandler](https://netty.io/4.1/api/io/netty/handler/ssl/SslHandler.html). In my pipeline, SSLHandler is added (optionally) by the OptionalSslHandler. 
 
### Actual behavior
[OptionalSslHandler](https://netty.io/4.1/api/io/netty/handler/ssl/OptionalSslHandler.html) does not provide an option to modify the SslHandshakeTimeout for the SslHandler that was created by it.

Note that it is important to change the SslHandshakeTimeout *before* the SslHandler is added to the pipeline because inside SslHandler `onHandlerAdded` callback, [the handshake processing is started](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L1948) and a timeout is scheduled.

### Steps to reproduce
N/A
### Minimal yet complete reproducer code (or URL to code)
[Code for OptionalSslHandler](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/OptionalSslHandler.java)
### Netty version
4.1.48
### JVM version (e.g. `java -version`)
N/A
### OS version (e.g. `uname -a`)
N/A

**Comment by normanmaurer** [comment]
@divijvaidya you can override `newSslHandler` and apply this there. Thats why it is protected
