### ISSUE TITLE
Using ByteBuf as a wrapper for an InputStream which uses a ByteBuf as a buffer

### ISSUE THREAD

**Issue by collinsmith** [netty/netty#10602]
I've been using `ByteBuf` for file I/O in a project I'm working on, and I've been toying around with the idea of using a `ByteBuf` as a wrapper for an `InputStream`. Since my `InputStream` implementation already uses a `ByteBuf` as a buffer, I thought it may be more elegant if I can write a custom `ByteBuf` implementation which uses that buffer directly (with maybe an intermediary cache for across-page reads). My idea was to have my `ByteBuf` implementation wrap a `CompositeByteBuf` which consists of slices of the underlying `InputStream` instance's `ByteBuf`, and when a new page needs to be read, setting the tail component to be the cache consisting of the remaining bytes in the old page.

I was wondering if this has been tried before or if it's feasible/a good idea since I don't think any of this was designed to work this way. I can apply certain constraints, such as read-only and no direct index access, as well as enforce limited reads (or provide a dynamically-sized cache).

**Comment by fenik17** [comment]
[ByteBufInputStream](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/ByteBufInputStream.java)?

**Comment by collinsmith** [comment]
I want to use a ByteBuf as an interface for an InputStream (which in my case happens to use a ByteBuf as a buffer), not the other way around.

**Comment by chrisvest** [comment]
It's somewhat of an awkward fit, since ByteBufs can freely change their read and write indexes, and access data by absolute offset. This is a conceptual difference between streams and buffers, which might bite you down the road as your code evolves. But if your use case is narrow enough to only need features that are easily implemented on top of an `InputStream` then you can certainly give it a try. I personally haven't heard of anyone doing this.

**Comment by collinsmith** [comment]
That's more or less what I thought I'd hear. I like the API that `ByteBuf` provides for reading data, but in a couple codecs, it's not very feasible to load the entire data stream as a `ByteBuf` all at once, so I was going to end up doing a lot of `ByteBuf#writeBytes(InputStream,int)` which would be a waste if my `InputStream` implementation already has a `ByteBuf` being used as a buffer. I wanted to hear what contributors who know more about this than me thought. I'll play with it a bit more and see if I can come up with something I like. Thank you for your input!
