### ISSUE TITLE
Websocket handshaker failed for  sec-websocket-version can't be recognized 

### ISSUE THREAD

**Issue by jiangguilong2000** [netty/netty#10607]
### Expected behavior
Request's Header:

> GET https:l /game.weplaycn.comf9001/websocket HTTF/1.1
Host: game.weplayen.com
onnection: Upgrade
Fragma: no-cache
ache-Control: no-cache
Upgrade: websocket
0rigin: https:/fres.weplaycn.com
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate
Accept-Language: zh-CH,zh;q-0.8,en-US ; q-0.6,en;q-0.5;q-0.4
Sec-WebSocket一Key: g2VPrctBwjppDsfDGi dBoA—
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

Response's header:

> HTTP/1.1 101 Switching Protocols
Server: nginx1.8.0
Date: Thu,24 Sep 2020 12:57:0 GMr
Connection: upgrade
upgrade: websocket
Sec-WebSocket-Accept: +ckML/qljT1PEuAxOntWh49nBmE
ccess-Control-Allow-Origin: *

### Actual behavior
Request's Header:

> GET /websocket HTTP/1.1
host: 47.99.67.129:5131
upgrade: websocket
connection: upgrade
sec-websocket-key: pD7zzfEba9wxlH9tBoIX3A==
origin: http://47.99.67.129:5131
**sec-websocket-version**: 13

Response's header:
> DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)
HTTP/1.1 400 Bad Request

### Steps to reproduce
the root cause is as following : 
in other programming language ,for instance. JS or php ,the websocket hand shaker protocol ‘s only think the parameter"**Sec-WebSocket-Version**" is legal, 
But in netty version for '4.1.52.Final',the parameter has been changed to "sec-websocket-version", it cause some application can't work OK now. it works ok before.I think  this version upgrade is go down.
you can use php as server,netty as client network framework,or use js as client,netty as server network framework,this bug is reproduced  easily.

### Minimal yet complete reproducer code (or URL to code)
for compatibility,this code should be modified as follows:
client side:
[io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13.newHandshakeRequest()](https://github.com/netty/netty/blob/4b22d8ab352912e9ac1217f51ecbff68c5b99572/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshaker13.java#L200)

server side:
[io.netty.handler.codec.http.websocketx.WebSocketServerHandshakerFactory.newHandshaker(HttpRequest)](https://github.com/netty/netty/blob/a4276e8dffd42ea7b990e6707c11c2c2037d2d82/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshakerFactory.java#L129)

### Netty version
4.1.52.Final
### JVM version (e.g. `java -version`)
OpenJDK Runtime Environment (Alibaba 8.0.0) (build 1.8.0_66-b60)
### OS version (e.g. `uname -a`)
win10

**Comment by normanmaurer** [comment]
@jiangguilong2000 this is bug with the other library as the RFC clearly state that header names are **not** case sensitive.

**Comment by jiangguilong2000** [comment]
> @jiangguilong2000 this is bug with the other library as the RFC clearly state that header names are **not** case sensitive.

as ur opinion,this code is not right:
[](https://github.com/netty/netty/blob/a4276e8dffd42ea7b990e6707c11c2c2037d2d82/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshakerFactory.java#L131)

**Comment by slandelle** [comment]
@jiangguilong2000 Nah. HttpHeaders#get is case insensitive.

**Comment by normanmaurer** [comment]
Closing as this is a not an netty issue
