### ISSUE TITLE
support "CCM" cipher suites

### ISSUE THREAD

**Issue by chendifan** [netty/netty#10611]
### Expected behavior
support cipher suites which use CCM as bulk cipher.

### Actual behavior
we found that CCM is not included in available suites of OpenSsl(from netty-tcnative).

### Steps to reproduce

``` java
Set<String> ciphers = OpenSsl.availableOpenSslCipherSuites();
for (String cipher : ciphers) {
    System.out.println(cipher);
}
```

results are:

```
ECDHE-ECDSA-AES128-GCM-SHA256
ECDHE-RSA-AES128-GCM-SHA256
ECDHE-ECDSA-AES256-GCM-SHA384
ECDHE-RSA-AES256-GCM-SHA384
ECDHE-ECDSA-CHACHA20-POLY1305
ECDHE-RSA-CHACHA20-POLY1305
ECDHE-PSK-CHACHA20-POLY1305
ECDHE-ECDSA-AES128-SHA
ECDHE-RSA-AES128-SHA
ECDHE-PSK-AES128-CBC-SHA
ECDHE-ECDSA-AES256-SHA
ECDHE-RSA-AES256-SHA
ECDHE-PSK-AES256-CBC-SHA
AES128-GCM-SHA256
AES256-GCM-SHA384
AES128-SHA
PSK-AES128-CBC-SHA
AES256-SHA
PSK-AES256-CBC-SHA
DES-CBC3-SHA
TLS_AES_128_GCM_SHA256
TLS_AES_256_GCM_SHA384
TLS_CHACHA20_POLY1305_SHA256
AEAD-AES128-GCM-SHA256
AEAD-AES256-GCM-SHA384
AEAD-CHACHA20-POLY1305-SHA256
```

### Netty version
up-to-date snapshot, also exists in recently release - 4.1.52.Final

### JVM version
jdk1.8.0_261

### OS version
Windows 10 Professional build 17134.1

### related code(maybe)

- static code block in io.netty.handler.ssl.OpenSsl
- io.netty.handler.ssl.SslUtils#TLSV13_CIPHERS
- io.netty.handler.ssl.CipherSuiteConverter#toOpenSsl
- io.netty.handler.ssl.CipherSuiteConverter#cacheFromJava
- io.netty.handler.ssl.CipherSuiteConverter#toOpenSslUncached
- io.netty.handler.ssl.CipherSuiteConverter#JAVA_CIPHERSUITE_PATTERN

related RFC: https://tools.ietf.org/html/rfc8446#appendix-B.4

**maybe it was because io.netty.handler.ssl.CipherSuiteConverter#JAVA_CIPHERSUITE_PATTERN uses "_WITH_" style to resolve the io.netty.handler.ssl.SslUtils#TLSV13_CIPHERS**

sorry for my poor English...

**Comment by normanmaurer** [comment]
it may take a bit for me to investigate ... if you already have an idea how to fix this I would be happy to review a pr.

**Comment by chendifan** [comment]
it's not that a bug of regex but because openssl is not support "TLS_AES_128_CCM_8_SHA256" and "TLS_AES_128_CCM_SHA256" yet.

use `openssl ciphers ALL` we'll see none of the above two exists.

Not a bug, let me close it.
