### ISSUE TITLE
UnorderedThreadPoolEventExecutor#scheduleAtFixedRate not working as expected

### ISSUE THREAD

**Issue by matteobertozzi** [netty/netty#10614]
### Expected behavior
The runnable passed to scheduleAtFixedRate() should run multiple times, not just once.

### Actual behavior
using UnorderedThreadPoolEventExecutor the runnable is executed just once, using directly the ScheduledThreadPoolExecutor or DefaultEventExecutorGroup the task is executed at fixed rate as expected

### Minimal yet complete reproducer code 
```java
public static void main(final String[] args) throws Exception {
  final UnorderedThreadPoolEventExecutor executor = new UnorderedThreadPoolEventExecutor(2);
  //final ScheduledThreadPoolExecutor executor = new ScheduledThreadPoolExecutor(2); // THIS WORKS
  //final DefaultEventExecutorGroup executor = new DefaultEventExecutorGroup(2); // THIS WORKS
  executor.scheduleAtFixedRate(() -> System.out.println("XXX"), 1, 1, TimeUnit.SECONDS);
  executor.awaitTermination(10, TimeUnit.SECONDS); // let it run...
}
```

### Netty version
4.1.52.Final 

### JVM version
latest OpenJDK 11 and 15

**Comment by prgitpr** [comment]
hi~  I not sure UnorderedThreadPoolEventExecutor#scheduleAtFixedRate should work as you expected ,but as you expected ,you can change the code as I already commit.
