### ISSUE TITLE
Better hash algorithm in FingerprintTrustManagerFactory

### ISSUE THREAD

**Issue by artem-smotrakov** [netty/netty#10649]
`FingerprintTrustManagerFactory` checks if a certificate is trusted by comparing its SHA-1 hash to a list of pre-configured ones:

https://github.com/netty/netty/blob/0cde4d9cb4d19ddc0ecafc5be7c5f7c781a1f6e9/handler/src/main/java/io/netty/handler/ssl/util/FingerprintTrustManagerFactory.java#L85

Unfortunately, nowadays SHA-1 is considered insecure. The issue was reported by [LGTM](https://lgtm.com/projects/g/netty/netty/snapshot/090bf3d107cb3099317e1cd9e0d661ac0797c126/files/handler/src/main/java/io/netty/handler/ssl/util/FingerprintTrustManagerFactory.java?sort=name&dir=ASC&mode=heatmap#xedd0183a9626d84c:1).

I see the following ways to fix it:

1. Update `FingerprintTrustManagerFactory` to use a stronger algorithm such as SHA-512. Unfortunately, most likely it'll break applications that pass a SHA-1 hash to the class.
1. Deprecate `FingerprintTrustManagerFactory` and add a new implementation that use a stronger algorithm. 
1. Updated `FingerprintTrustManagerFactory` to determine a hash algorithm based on a length of a hash passed to the constructor. If a caller passes a SHA-1 hash, the class can also print a warning.

Please let me know if one of the options above is fine (or, you see a better option), and I'll open a pull request.

**Comment by hyperxpro** [comment]
SHA-512 is an overkill and not useful for this purpose. SHA-256 or SHA-384 is the way to go.

**Comment by artem-smotrakov** [comment]
@trustin @normanmaurer What do you think?

**Comment by chrisvest** [comment]
As far as I understand how `FingerprintTrustManagerFactory` is meant to be used, I think it's better to deprecate it, and add a new implementation that uses a stronger hash function, or allow the hash function to be configured. Maybe the configurable implementation can be extracted into a new super-class of `FingerprintTrustManagerFactory`.

**Comment by normanmaurer** [comment]
I agree with @chrisvest here...

**Comment by trustin** [comment]
I don't see a reason to introduce a new `TrustManagerFactory` implementation class. We could deprecate the public constructors in favor of builders and static factory methods. e.g.

```java
FingerprintTrustManagerFactory f =
  FingerprintTrustManagerFactory
    .builder("SHA256") // Always require the algorithm name
    .fingerprint("deadbeef...")
    .fingerprint("cafecafe...")
    .build();
```

The public constructors could call the internal constructor that passes the message digest function, e.g.

```java
@Deprecated
public FingerprintTrustManagerFactory(String... fingerprints) {
    this(FingerprintTrustManagerFactory::sha1Fingerprint, fingerprints);
}

// Called by the builder or the legacy public constructors.
// The example uses Java 8 Function but we can define a dedicated interface if necessary.
FingerprintTrustManagerFactory(
    Function<? super X509Certificate, byte[]> fingerprintFunc,
    String... fingerprints) {
    ...
}
```

We could also consider implementing more versatile `TrustManagerFactory` by extracting the verification logic out of the `TrustManagerFactory`, e.g.

```java
SomeTrustManagerFactory
  .builder()
  .add(CertificateMatchers.fingerprint("SHA256", "deadbeef..."))
  .add("bar.foo.com", CertificateMatchers.strict())
  .add("*.foo.com", CertificateMatchers.any());
  .build();
```

**Comment by artem-smotrakov** [comment]
I like the idea with a builder and deprecating only the public constructor suggested by @trustin 

```java
FingerprintTrustManagerFactory f =
  FingerprintTrustManagerFactory
    .builder("SHA256") // Always require the algorithm name
    .fingerprint("deadbeef...")
    .fingerprint("cafecafe...")
    .build();
```

If no objections, I'll implement this logic then.
