### ISSUE TITLE
Wonder whether order of fireSniCompletionEvent and onLookupComplete should be switched

### ISSUE THREAD

**Issue by aspcompiler** [netty/netty#10655]
https://github.com/netty/netty/blob/77effdc4da76cb967b9c214b0682b742e90b4203/handler/src/main/java/io/netty/handler/ssl/AbstractSniHandler.java#L131-L132

Currently, fireSniCompletionEvent runs before onLookupComplete. If I save the lookup result in onLookupComplete, events triggered by SniCompletionEvent will not see the effects. Wonder whether fireSniCompletionEvent should run after onLookupComplete.

**Comment by normanmaurer** [comment]
@aspcompiler what exactly you want to save ?

**Comment by normanmaurer** [comment]
@aspcompiler ok got it.... Can you create a PR with the change ?

**Comment by normanmaurer** [comment]
@aspcompiler PTAL https://github.com/netty/netty/pull/10688

**Comment by aspcompiler** [comment]
@normanmaurer  #10688 looks good. Thank you!
