### ISSUE TITLE
No p2p node network implementation in examples

### ISSUE THREAD

**Issue by CarlOsterberg** [netty/netty#10657]
I have noticed upon scouring through the examples folder that there is no p2p examples, but there seems to be support for it in netty. A simple implementation with a node acting as server and client, meaning it should handle outgoing and inbound communication should be implementable.

**Comment by hyperxpro** [comment]
We love contributions. You can do a PR.

**Comment by normanmaurer** [comment]
@CarlOsterberg like @hyperxpro said... We love PRs. That said you may find something useful in the `hexproxy` example.
