### ISSUE TITLE
Enable CodeQL or LGTM scans for pull requests

### ISSUE THREAD

**Issue by artem-smotrakov** [netty/netty#10669]
GitHub now offers code scanning that is based on CodeQL (the same engine that is used in LGTM.com). Shortly, that's a static analysis tool that is able to catch various issues including security ones. Once enabled for pull requests, it would help with catching issues earlier.

The scan may be run via [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository#enabling-code-scanning-using-actions) for pull requests. Or, LGTM checks may be added, the instructions are [here](https://lgtm.com/projects/g/netty/netty/ci/).

How about enabling the scans for Netty? If it's okay, I can try to set it up but maybe it will need some support from project admins.

**Comment by normanmaurer** [comment]
Good idea.... see https://github.com/netty/netty/pull/10696
