### ISSUE TITLE
Illegal reflective access by io.netty.util.internal.ReflectionUtil to DirectByteBuffer

### ISSUE THREAD

**Issue by rafmichalak84** [netty/netty#10661]
### Actual behavior
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/Users/<user>/.m2/repository/io/netty/netty-all/4.1.52.Final/netty-all-4.1.52.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

### Netty version
4.1.52.Final

### JVM version (e.g. `java -version`)
java version "15" 2020-09-15
Java(TM) SE Runtime Environment (build 15+36-1562)
Java HotSpot(TM) 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)

### OS version (e.g. `uname -a`)
Darwin MacBook-Pro.local 20.1.0 Darwin Kernel Version 20.1.0: Thu Sep 24 20:22:06 PDT 2020; root:xnu-7195.40.89.100.3~1/RELEASE_X86_64 x86_64

**Comment by hyperxpro** [comment]
You can safely ignore the warning.

**Comment by chrisvest** [comment]
Netty uses reflection in order to support, and have good performance, on a large range of Java versions.
You can silence the warnings by running java with a `--illegal-access=permit` (or `--illegal-access=deny`) flag.
This is safe (for Netty) because we have fall-back code paths for all the places.
If something breaks when you use those flags, then that's a bug that should be reported separately.

**Comment by normanmaurer** [comment]
@rafmichalak84 this is very strange as it should not try to do so by default...

Did you by any chance specify:

`-Dio.netty.tryReflectionSetAccessible=true`?

**Comment by normanmaurer** [comment]
@rafmichalak84 ping... ^^

**Comment by normanmaurer** [comment]
I will close this one for now again... Please reopen once you have more infos to provide

**Comment by YuriyGavrilov** [comment]
@normanmaurer 
Just got this warning with arrow jdbc driver installed in Tableau

`WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2023-10-12T22:09:48.924283 Protocol Server starting. 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cfjd.io.netty.util.internal.ReflectionUtil (file:/Users/yuriygavrilov/Library/Tableau/Drivers/flight-sql-jdbc-driver-10.0.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of cfjd.io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
`
