### ISSUE TITLE
There are some problems here. If the following code is not added to this place, a page will not be used again.PoolSubpage.free()

### ISSUE THREAD

**Issue by suntianji123** [netty/netty#10685]
![R0LTCGOX 6V0DT~C80~D2VR](https://user-images.githubusercontent.com/34296859/96003341-b7edbd80-0e6c-11eb-85d0-036f94c89347.png)

**Comment by normanmaurer** [comment]
Can you open a PR with the fix and if possible a unit test ?

**Comment by normanmaurer** [comment]
@suntianji123 also I think there are other changes that needs to be done in PoolChunk.

**Comment by normanmaurer** [comment]
Actually I think it is already handled correctly in the latest netty release as if `PoolSubpage.free(...)` returns false we will take care of it.

**Comment by normanmaurer** [comment]
Let me close this as I think its a none issue... Please re-open if you still think there is an issue in the latest 4.1 branch / release
