### ISSUE TITLE
Netty's select native method not fetch data from socket recv buffer when reconnection is done too frequently

### ISSUE THREAD

**Issue by KaimingWan** [netty/netty#10687]
Here come a strange case. My application(server) use netty to fetch data from remote node(client) and I found sometime the server fetch data from remote is very slow after reconnection. The server's select operation cost much time. Although the socket receive buffer have data, the select operation don't response to it.

My running environment:

openjdk version "1.8.0_232"
Mac 10.15.4 (By the way, I also reappear the issue on Linux centos 7.7)
Netty 4.0.42
The screenshot description:
![image](https://user-images.githubusercontent.com/4374015/96070921-b4415180-0ed3-11eb-8bab-f9629b86df47.png)

192.168.0.149:7007(server) receive data from 192.168.0.149:52501(client) with netty
There always have accumulation data in socket receive buffer and select do not feel that.
Every time the receive buffer's data size change, I can see the select operation is done(Using arthas to trace the java stack's invoke).
The netty select operation cost long time to feel the data in receive buffer
My question is:

Why select operation do not feel data in receive buffer?
Why use select here rather than selectNow?
I use the default options to initial netty server and client. Is there any netty options's default value or linux kerner parameters that can cause this issue(Like TCP_NODELAY etc.)?
enter image description here

**Comment by normanmaurer** [comment]
Are you sure it really has received the data ? Check with Wireshark if this is really the case. Depending on how small the data is you may also want to experiment with `TCP_NODELAY`.

Let me close this tho as this is an issue tracker.
