### ISSUE TITLE
Different behavoius between ByteBufs returned by PooledUnsafeDirectByteBuf.slice().retain() and PooledUnsafeDirectByteBuf.retainedSlice()

### ISSUE THREAD

**Issue by zhengdehui** [netty/netty#10713]
### Expected behavior
try this test case
~~~java
		ByteBuf buf1 = PooledByteBufAllocator.DEFAULT.directBuffer(1024);
		ByteBuf slice1 = buf1.retainedSlice(0, 512);
		slice1.release();
		Assert.assertEquals(1, buf1.refCnt());
		Assert.assertEquals(0, slice1.refCnt());

		ByteBuf buf2 = PooledByteBufAllocator.DEFAULT.directBuffer(1024);
		ByteBuf slice2 = buf2.slice(0, 512).retain();
		slice2.release();
		Assert.assertEquals(1, buf2.refCnt());
		Assert.assertEquals(0, slice2.refCnt()); // expected:<0> but was:<1>

		slice2.release(); // expected IllegalReferenceCountException, but didn't
~~~
The only difference between slice1 and slice2 is `slice1` is returned by `retainedSlice()` and `slice2` is returned by `slice(0, 512).retain()`
I was expecting the behavious of `release()` and `refCnt()` should be the same between slice1 and slice2, but it's not, see test case comments above.

Furthermore, slice1 is sharing the same refCnt with buf1 which can make buf1 to be unusable if slice1 release more than once. This is very dangerous when multiple ByteBufs are sliced from the same common ByteBuf.

### Netty version
4.1.51

### JVM version (e.g. `java -version`)
any JVM

### OS version (e.g. `uname -a`)
any OS

**Comment by chrisvest** [comment]
Yeah, looks like there's a bug in how the pooled buffers are maintaining their reference counts. Pooled and unrolled buffers should behave the same, and `retainedSlice()` should be equivalent to `slice().retain()`.

> slice1 is sharing the same refCnt with buf1 which can make buf1 to be unusable if slice1 release more than once.

I think it would be a bug in the integrators code. Releasing more than you acquired/retain is just wrong use of reference counting.
I see the appeal of having the second `slice2.release()` call throw, but it changes the reference counting model a bit, which makes me concern about compatibility.

**Comment by chrisvest** [comment]
Turns out this happens because for pooled buffers, we also pool the buffers we use for slices. This means the slices must maintain independent reference counts in order to know when to return to the pool.

This should not have any impact on the behaviour as long as retain/acquires and releases are paired up correctly.
I wonder if we might just consider this an implementation detail that leaks through the `refCnf()`. What do you think, @normanmaurer?

**Comment by chrisvest** [comment]
We've had a discussion about this, and concluded that the exact value of the `refCnt` is implementation defined, except when it is zero which means the thing has been closed or deallocated.

We'd like to make this more consistent and predictable, but that would be for Netty 5. In Netty 4 we'll keep it like this. The important thing is that things are correctly deallocated when reference increments and decrements are correctly paired.
