### ISSUE TITLE
I think the traversal of the refqueue of the memory leak detector should be implemented using a daemon thread similar to ObjectCleaner

### ISSUE THREAD

**Issue by suntianji123** [netty/netty#10715]
private void reportLeak() {
        //如果不支持记录错误级别日志 清理掉引用queue
        if (!logger.isErrorEnabled()) {
            //清理掉refQueue中所有的引用对象
            clearRefQueue();
            return;
        }

        // 当对象T被gc回收后，追踪器添加到refQueue中
        for (;;) {
            //获取追踪器
            @SuppressWarnings("unchecked")
            DefaultResourceLeak ref = (DefaultResourceLeak) refQueue.poll();
            if (ref == null) {
                break;
            }

            //删除追踪器在allLInk map中
            if (!ref.dispose()) {
                continue;
            }

            //获取追踪器的记录（遍历Record链表）
            String records = ref.toString();
            //添加到报告过的的追踪器map
            if (reportedLeaks.putIfAbsent(records, Boolean.TRUE) == null) {
                //没有没有record信息的几率
                if (records.isEmpty()) {
                    reportUntracedLeak(resourceType);
                } else {
                    //记录有信息的泄露
                    reportTracedLeak(resourceType, records);
                }
            }
        }
    }

This string of code does not guarantee that the trace record will be written to the log

**Comment by normanmaurer** [comment]
We don't want to introduce another `Thread` here. Why you think the current implementation is not sufficient ?

**Comment by suntianji123** [comment]
> We don't want to introduce another `Thread` here. Why you think the current implementation is not sufficient ?

Zhège fāngfǎ de for xúnhuán zhǐ néng chǔlǐ zhīqián de zhuīzōng qì zuìhòu yīgè tiānjiā dào duìliè de zhuīzōng qì bù huì bèi chǔlǐ
39/5000
The for loop of this method can only process the previous tracker. The last tracker added to the queue will not be processed.

**Comment by normanmaurer** [comment]
sure but it will be processed "at some point". So this should be good enough.

**Comment by normanmaurer** [comment]
Closing this as I think it works as expected
