### ISSUE TITLE
Eclipse mat memory leak on PoolChunk

### ISSUE THREAD

**Issue by jorgebo10** [netty/netty#10717]
Hi,

Eclipse mat is reporting a suspicious memory leak on io.netty.buffer.PoolChunk . Just wanted to check if this is normal behavior and whether  should i  worry. 

Thanks,
Jorge

[heapdump-1603222350462.hprof.zip](https://github.com/netty/netty/files/5416989/heapdump-1603222350462.hprof.zip)

### Netty version
4.1.51-final

### JVM version (e.g. `java -version`)
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

### OS
Darwin SSFF-00221 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
Thats normal... netty is using memory pooling by default and memory is allocated in chunks (which we use to slice out data). By default a chunk is 16mb.

**Comment by brestmoor** [comment]
Hi, currently I am also analysing a heap dump which is 1.1GB, and 512MBs of it are io.netty.buffer.PoolChunk instances (32 instances). Is it working as designed? We are running Wildfly 15.0.1 on Java 11.
That's what it looks like in MAT:
![image](https://user-images.githubusercontent.com/17832444/103566975-3d5c9900-4ec3-11eb-83a8-fbd5f6bd2c8b.png)

**Comment by franz1981** [comment]
@brestmoor it should be fine, it depends by the available cores (32 looks as 16 " 2 that sounds similar to the available cores * 2, just a guess)
