### ISSUE TITLE
Execute ChannelFuture writeAndFlush(Object msg)  method timeout ,channel=NioSocketChannel

### ISSUE THREAD

**Issue by yhc19850706** [netty/netty#10729]
### Netty version
          Netty version=4.0.39

### JVM version (e.g. `java -version`)
      JVM version= 1.8.0_261
### OS version (e.g. `uname -a`)
      windows10
in javaNSQClient(https://github.com/brainlag/JavaNSQClient) project ,use  netty 4.0.39, producer.produce() send message ;
when excutor six million message,excption  [java.util.concurrent.TimeoutException: command: PUB TestTopic timedout],timout=15s

**Comment by hyperxpro** [comment]
4.0.X reached EOL. Upgrade to Netty 4.1.53.Final and see if the issue still persists.

**Comment by normanmaurer** [comment]
As @hyperxpro said...
