### ISSUE TITLE
My netty server reported an error 'io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: index: 16384, length: -14771 (expected: range(0, 8192))'. Can you tell me why? thank you

### ISSUE THREAD

**Issue by AldirchEugene** [netty/netty#10724]

**Comment by hyperxpro** [comment]
More details needed and please use issue template.

**Comment by normanmaurer** [comment]
Usually this means you tried to read more data then what is readable in the buffer.

**Comment by chenvsdhf55** [comment]
问题解决了吗？

**Comment by AldirchEugene** [comment]
> Usually this means you tried to read more data then what is readable in the buffer.

thank you so much
