### ISSUE TITLE
This should be a more accurate exception or a type judgment mechanism when method get a wrong parameter

### ISSUE THREAD

**Issue by fantow** [netty/netty#10727]
### Expected behavior
IMHO，we should add some confirmation mechanism to ensure the useful method SingleThreadEventExecutor.shutdownGracefully(long quietPeriod, long timeout, TimeUnit unit) running in a right way or ensure the exception of Timeunit parameter can be correctly represented.

![Netty_2](https://user-images.githubusercontent.com/18530950/97008670-b52e4f00-1575-11eb-8846-befcb1ea0429.png)

![Netty_1](https://user-images.githubusercontent.com/18530950/97008669-b3fd2200-1575-11eb-98fe-d228f278073b.png)

If this issue is necessary，may I sumbit a PR to fix it?

**Comment by normanmaurer** [comment]
I am not sure what you are suggesting but I am happy to review a pr

**Comment by fantow** [comment]
> 
> 
> I am not sure what you are suggesting but I am happy to review a pr

I think the easiest way is providing a more accurate exception description,rather than just throw a NPE.

**Comment by normanmaurer** [comment]
honestly I think a NPE does exactly tell you what is wrong here.

**Comment by fantow** [comment]
Okay,I will close this issue.Thank you for your answer.
