### ISSUE TITLE
Consider treating null as "none" in ChannelPipeline#add(..) functionality

### ISSUE THREAD

**Issue by Bennett-Lynch** [netty/netty#10728]
When adding handlers to a pipeline using the varargs methods, if Netty encounters a handler that is null, it will cease the insertion logic:

https://github.com/netty/netty/blob/1ca7d5db8167f904395d879b8851eb35d6f596f3/transport/src/main/java/io/netty/channel/DefaultChannelPipeline.java#L374-L382

I propose that it would be more intuitive to use `continue` here, rather than `break`.

This would allow for handlers to be conditionally added with ease. E.g.,

```
ch.pipeline().addLast(
        new FooHandler(),
        condition ? new BarHandler() : null,
        new BazHandler()
);
```

This is technically a behavior change so I'm not sure if it would be allowed in Netty 4 or not, but it seems reasonably safe.

**Comment by normanmaurer** [comment]
yeah sounds a good idea...can you do a PR against master ?
