### ISSUE TITLE
AbstractUnsafe.write() should use `safeRelease` instead of `release` when exception thrown

### ISSUE THREAD

**Issue by togetsukyo** [netty/netty#10723]
There are two ways for proactively detecting potential leaks and release a leaked `msg` when calling `channel.write(msg)`.
1. Add `try...catch...` around all the custom handlers, and release the `msg` in `catch...` clause. The downside of this is that we need to modify all the handlers. Also we could not do this to some library handlers like `HttpObjectEncoder`.
2. Add a promise listener to the `ChannelFuture` returned by `channel.write(msg)`, and release the `msg` inside the listener. Like the following code:

```
channel.write(msg).addListener((ChannelFutureListener) future -> {
  if (!future.isSuccess()) {
    if (msg.refCnt() > 0) {
      ReferenceCountUtil.safeRelease(msg);
    }
  }
});
```

If an exception thrown inside `flush0` method, it will help us first release the message and then call the promise handler:
https://github.com/netty/netty/blob/1ca7d5db8167f904395d879b8851eb35d6f596f3/transport/src/main/java/io/netty/channel/ChannelOutboundBuffer.java#L305-L308.

Usually the behavior is that if we've handed over the `msg` to `HeadContext` handler, if exception thrown, Netty should help us release the `msg` and call the promise listener. However, when I go through the code, there's one place that's not following this behavior: https://github.com/netty/netty/blob/1ca7d5db8167f904395d879b8851eb35d6f596f3/transport/src/main/java/io/netty/channel/AbstractChannel.java#L856-L886.

There're two places in the above link that's first calling the promise listener and then release the `msg`.

This would lead to a de-sync behavior where some places call `safeSetFailure(promise)` before `ReferenceCountUtil.release(msg)` while some places call them in reverse order.

If user tries to release the `msg` inside the promise listener and Netty is calling `ReferenceCountUtil.release(msg)` after `safeSetFailure(promise)`, an `IllegalReferenceCountException` would throw.

If user does not release the `msg` inside the promise listener and there's exception thrown in a custom handler, user can't easily tell if the exception was thrown from Netty's `HeadContext` or user's custom handler as the `msg.refCnt()` in these scenarios are both `1`.

There're two ways to fix this issue:
1. Reverse the order of `safeSetFailure(promise)` and `ReferenceCountUtil.release(msg)` in [`AbstractUnsafe`](https://github.com/netty/netty/blob/1ca7d5db8167f904395d879b8851eb35d6f596f3/transport/src/main/java/io/netty/channel/AbstractChannel.java#L856-L886). This would probably not be backward compatible though.
2. Use `ReferenceCountUtil.safeRelease(msg)` instead. In this case user can always release the `msg` in promise listener if they've found `msg.refCnt() > 0` and don't need to worry about the `IllegalReferenceCountException` that might have thrown by `ReferenceCountUtil.release(msg)`.

Please let me know your thoughts on this. I can create a PR if we think this issue needs to get fixed.

**Comment by normanmaurer** [comment]
@togetsukyo I think I don't agree with this... honestly saying I think a user should only call `release` if they know a reference count should be decremented. If you call `write` you basically transfer the ownership of the message and can be sure you don't need to decrement the reference count yourself. You only would need to call `release()` if you before called `retain()`.

That said I think you are right we should always release the message first and then call the listener. But only because this way we will release it as soon as possible which is the right thing to do.

**Comment by togetsukyo** [comment]
@normanmaurer Thanks for the response!

What's the recommended way to proactively prevent `msg` from LEAK? In the time when developing new features, it would be easy to forget to handle exception cases, and `msg` might leak. We can add promise listeners to log the exception message, but not responsible for releasing the `msg`. Sometimes the exception is not serious and we may not need to rollback the deployment, but we still may not want to see memory leak.

Should we add `try...catch...` exclusively to all the `write` functions of handlers? Like:
```
public abstract class SafeChannelDuplexHandler extends ChannelDuplexHandler {

    @Override
    public final void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) throws Exception {
        try {
            safeWrite(ctx, msg, promise);
        } catch (Throwable t) {
            // log.error(..)
            ReferenceCountUtil.safeRelease(msg);
            throw t;
        }
    }

    public abstract void safeWrite(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) throws Exception;

}
```

Or should we just simply use promise listeners for visibility and fix those exceptions after they got fired?

**Comment by normanmaurer** [comment]
@togetsukyo usually what I suggest is to run your CI with paranoid leak detection level enabled and fix the issues that are reported.

**Comment by normanmaurer** [comment]
@togetsukyo FYI https://github.com/netty/netty/pull/10726
