### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (build-native-lib) on project netty-transport-native-unix-common: An Ant BuildException has occured: exec returned: 2

### ISSUE THREAD

**Issue by xiaoliang-wang** [netty/netty#10730]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (build-native-lib) on project netty-transport-native-unix-common: An Ant BuildException has occured: exec returned: 2
[ERROR] around Ant part ...<exec resolveexecutable="true" failonerror="true" executable="make">... @ 4:71 in /Users/wangxiaoliang/github/netty/transport-native-unix-common/target/antrun/build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :netty-transport-native-unix-common

**Comment by normanmaurer** [comment]
Please include the full output

**Comment by normanmaurer** [comment]
Closing as I got no response from the reporter

**Comment by AceHCL** [comment]
楼主解决了嘛？我也遇到了

**Comment by wuhuisheng** [comment]
这个问题解决了吗？

**Comment by chrisvest** [comment]
Make sure you've set up your development environment as [described in the wiki](https://github.com/netty/netty/wiki/Setting-up-development-environment). Capture the full output. Use the `-X` switch to Maven to investigate which underlying command is failing.
