### ISSUE TITLE
Implement SWAR indexOf byte search

### ISSUE THREAD

**Issue by franz1981** [netty/netty#10731]
Currently Netty uses an expensive (GC-wise too) `ByteBufUtil::indexOf` implementation based on `ByteProcessor.IndexOfProcessor`  to save bound-checks to happen: this could be changed into what @richardstartin has implemented on https://richardstartin.github.io/posts/finding-bytes.

Same could be applied to `ByteBuf::indexOf` that's *not* using `ByteBufUtil::indexOf`(!!!)
@normanmaurer  Any idea why?

**Comment by franz1981** [comment]
@normanmaurer While having fun implementing this I've found something odd while adding this test to by adding this test to `AbstractByteBufTest`:
```java
    @Test
    public void testEndiannessIndexOf() {
        buffer.clear();
        final int v = 1
                      | (2 << 8)
                      | (3 << 16)
                      | (2 << 24);
        buffer.writeIntLE(v);
        buffer.writeByte((byte) 1);

        assertEquals(-1, buffer.indexOf(1, 4, (byte) 1));
        assertEquals(-1, buffer.indexOf(4, 1, (byte) 1));
        assertEquals(1, buffer.indexOf(1, 4, (byte) 2));
        assertEquals(3, buffer.indexOf(4, 1, (byte) 2));
    }
```
See the test results:
![image](https://user-images.githubusercontent.com/13125299/97137221-99819f00-1755-11eb-89e7-4755c1c8feef.png)

I don't think is expect or I'm not correctly using the `setXXXLE` methods...

**Comment by hyperxpro** [comment]
Possible to do Draft PR?

**Comment by franz1981** [comment]
@hyperxpro 
Already done on a private branch: need first to understand what's the problem with LE/BE order first!

**Comment by chrisvest** [comment]
@franz1981 I don't get any test failures when I run all the `AbstractByteBufTest`. Both `master` and `4.1` branches pass. Maybe you have some local changes somewhere.

**Comment by franz1981** [comment]
@chrisvest you should add the test I've linked on https://github.com/netty/netty/issues/10731#issuecomment-716315268

**Comment by Bennett-Lynch** [comment]
Nice article. Maybe @richardstartin would be interested, since he mentioned Netty specifically.
