### ISSUE TITLE
HttpUtil.setTransferEncodingChunked:No. 347 should add a flashback array code, otherwise it will change the order of the original attribute values in the linked list

### ISSUE THREAD

**Issue by suntianji123** [netty/netty#10752]
![11](https://user-images.githubusercontent.com/34296859/97667170-3deb4480-1aba-11eb-9797-c0d072bcc218.png)

**Comment by normanmaurer** [comment]
This seems to be not valid... we make a copy of the values

**Comment by suntianji123** [comment]
> This seems to be not valid... we make a copy of the values

Changed the order of the original linked list nodes，
Wrong order

**Comment by hyperxpro** [comment]
HTTP RFC does not enforce ordering AFAIK.
