### ISSUE TITLE
Migrating to JUnit 5

### ISSUE THREAD

**Issue by chrisvest** [netty/netty#10757]
I propose that we start migrating the test suite for Netty 5 (the `master` branch) to JUnit 5.

JUnit 5 is more expressive, extensible, and composable in many ways, and it's better able to run tests in parallel.
It can also directly run JUnit 4 tests, using the vintage engine, which means we can do this in small steps; there's no need to migrate all tests all at once.

Once the JUnit 5 infrastructure is there, tests or modules can be migrated one by one, or be left as is for the time being. Regardless, new tests that are only added to the `master` branch can immediately use the new JUnit 5 test APIs.

Some benefits I anticipate are:

1. Some tests will become easier to write, because JUnit 5 is more capable at expressing nesting of tests, and parameterisations.
2. Builds should complete faster because JUnit 5 is better able to run tests in parallel. This is something that needs to be enabled explicitly, however, since it can cause latent test isolation failures to pop up.
3. JUnit 5 is extensible enough that something like `TimedOutTestsListener` won't need to live in the `netty-build` anymore.

A drawback I can think of is that forward porting changes to a JUnit 4 test in Netty `4.1`, to a migrated JUnit 5 test in `master`, will be more challenging and add to the workload of doing changes in `4.1`.

What do people think?

**Comment by Bennett-Lynch** [comment]
Is there any reason that JUnit 5 cannot be added to Netty 4.1?

Considering test artifacts are not exported as part of the build process, it doesn't seem like it should pose a compatibility issue.

**Comment by normanmaurer** [comment]
The testsuite is exposed so we can consume it . That said I would not consider this API

**Comment by chrisvest** [comment]
JUnit 5 is now enabled in both the `4.1` branch and the `master` branch.

**Comment by kashike** [comment]
I have started working on this in #11301.

**Comment by kashike** [comment]
- [ ] all
- [ ] bom
- [ ] buffer
- [ ] codec
- [ ] codec-dns
- [ ] codec-haproxy
- [ ] codec-http
- [ ] codec-http2
- [ ] codec-memcache
- [ ] codec-mqtt
- [ ] codec-redis
- [ ] codec-smtp
- [ ] codec-socks
- [ ] codec-stomp
- [ ] codec-xml
- [ ] common
- [ ] dev-tools
- [ ] example
- [ ] handler
- [ ] handler-proxy
- [ ] microbench
- [ ] resolver
- [ ] resolver-dns
- [ ] resolver-dns-native-macos
- [ ] tarball
- [ ] testsuite
- [ ] testsuite-autobahn
- [ ] testsuite-http2
- [ ] testsuite-native
- [ ] testsuite-native-image
- [ ] testsuite-native-image-client
- [ ] testsuite-native-image-client-runtime-init
- [ ] testsuite-osgi
- [ ] testsuite-shading
- [ ] transport
- [ ] transport-blockhound-tests
- [ ] transport-native-epoll
- [ ] transport-native-kqueue
- [ ] transport-native-unix-common
- [ ] transport-native-unix-common-tests
- [ ] transport-sctp

**Comment by kashike** [comment]
I hope that's a good start for now! I have pushed all my progress so far, and I will probably pick up on this again later today.

**Comment by kashike** [comment]
The `handler` module is proving problematic to migrate - it heavily uses class-scoped parameterized tests.
