### ISSUE TITLE
Please open a security advisory

### ISSUE THREAD

**Issue by JLLeitschuh** [netty/netty#10768]
Hello Netty Team,

I'd like to privately disclose a security vulnerability in netty.

Would you be willing to open an advisory here so we can discuss the details?

https://github.com/netty/netty/security/advisories

Cheers,
Jonathan Leitschuh

**Comment by normanmaurer** [comment]
@JLLeitschuh can you just follow what is outline here: https://github.com/netty/netty/blob/4.1/SECURITY.md ?

**Comment by JLLeitschuh** [comment]
Hey @normanmaurer,

Your SECURITY.md links to a google group that I can't access. And it doesn't convey what email to send information to, so currently, no, I can't. I'd like if we could perform disclosure via the GitHub Security Advisories, so if we could skip the step of reporting via email, that would be nice for me, but I'm happy to use email initially if required.

**Comment by normanmaurer** [comment]
Please use the group.... you can just sent an email there: netty-security@googlegroups.com

**Comment by JLLeitschuh** [comment]
Okay, will do! 😀

**Comment by JLLeitschuh** [comment]
This was disclosed here. Closing now.

https://github.com/netty/netty/security/advisories/GHSA-5mcr-gq6c-3hq2
