### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by LiQusha** [netty/netty#1077]
First of all, IMHO, it's not https://github.com/netty/netty/issues/606 .

It's more like http://lists.jboss.org/pipermail/netty-users/2009-July/000938.html for Netty 4.x.

I also have the problem on Windows (development/coding) environment but still very frustrating. It's only caused by holding the refresh button (sending many requests) for a few seconds. After that, memory consumption is unbelievable. When I switch back to 3.6.x , It' really hard to get the same problem ...

Maybe It's time for improvement once again as @trustin  did before for 3.x: "I recently improved the acceptance throughput in Netty NIO transport, so it might help to some extent" as he said on that mailing list post.

**Comment by wjkhappy14** [comment]
An existing connection was forcibly closed by the remote host
远程主机强迫关闭了一个现有的连接
