### ISSUE TITLE
suggestion: netty/example/objectecho inform about missing "implements Serializable" on client side

### ISSUE THREAD

**Issue by oxplay2** [netty/netty#10777]
Hello,

as new user i wanted to try Objectecho "Example", and was confused when i sent **Serializable Object** that were **containing** an **"non-serializable" Object** as some depth field(that i didnt notice earlier), it was not sent at all, and i received no information at all. It took me time to debug and notice that one of its fields was an object that didnt implement Serializable.

Thats why i just throw some suggestion to add into "Objectecho Example" some new user friendly code to inform about it like:

**1)** some "Objectecho Example"  class extending ObjectEncoder:

    @Override
    public boolean acceptOutboundMessage(Object msg) throws Exception {
        if(!super.acceptOutboundMessage(msg)){
            // some information
        }
        return true;
    }

**OR**

(i didnt try enable Asserts, so if you use some, this option might be better)
**2)** **Just add comment about it**, to let new users know they will receive NO information when trying to send complex Objects that in some depth contains non-serializable Object.

**Please note this refer only to "Objectecho Example"  and Encoder (so its client side).** 

Just thought it could be helpfull for new users having same problem.

### Expected behavior

- some warning/error/information for "Objectecho Example"  if there is missing Serializable

### Actual behavior

- Demo give NO information if sent object do not match, client and server print **no information/warning/error at all.**

### Steps to reproduce

- in "Objectecho Example"  try sent Serializable object with not serializable Object in it, it will not be sent and no information will be printed anywhere. Also comments do not mention anything about it.

### Netty version

4.1.43

And ofc, hello to netty users/devs ;)

Please close it if "Objectecho Example" is not prepared for new users and its for testing purpose, or if you think its not needed, since its just suggestion.

**Comment by hyperxpro** [comment]
Enable `DEBUG` log level.

**Comment by oxplay2** [comment]
if you mean:

p.addLast(new LoggingHandler(LogLevel.DEBUG));

do not help. No information is printed. **(using non-serialized object - that dont work)**

--------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------
**BELOW IS WORKING CASE, BUT PROBABLY FOUND SOME new BUG**:

Anyway im not sure if i found some BUG or what.
im having Client+Server in same application,

by default without logging i have:

> lis 07, 2020 1:08:56 PM io.netty.handler.logging.LoggingHandler channelRegistered
> INFO: [id: 0x70dbfa79] REGISTERED
> lis 07, 2020 1:08:56 PM io.netty.handler.logging.LoggingHandler bind
> INFO: [id: 0x70dbfa79] BIND: 0.0.0.0/0.0.0.0:6143
> lis 07, 2020 1:08:56 PM io.netty.handler.logging.LoggingHandler channelActive
> INFO: [id: 0x70dbfa79, L:/0:0:0:0:0:0:0:0:6143] ACTIVE
> lis 07, 2020 1:08:56 PM io.netty.handler.logging.LoggingHandler channelRead
> INFO: [id: 0x70dbfa79, L:/0:0:0:0:0:0:0:0:6143] READ: [id: 0x1ff7f916, L:/127.0.0.1:6143 - R:/127.0.0.1:59428]
> lis 07, 2020 1:08:56 PM io.netty.handler.logging.LoggingHandler channelReadComplete
> INFO: [id: 0x70dbfa79, L:/0:0:0:0:0:0:0:0:6143] READ COMPLETE
> Server Channel Active
> ByteBuf out size: 256

when i add for example 

p.addLast(new LoggingHandler(LogLevel.WARN));

i have:

> lis 07, 2020 1:05:02 PM io.netty.handler.logging.LoggingHandler channelRegistered
> INFO: [id: 0x47da6a0b] REGISTERED
> lis 07, 2020 1:05:02 PM io.netty.handler.logging.LoggingHandler channelRegistered
> WARNING: [id: 0x107f76a8] REGISTERED
> lis 07, 2020 1:05:02 PM io.netty.handler.logging.LoggingHandler connect
> WARNING: [id: 0x107f76a8] CONNECT: localhost/127.0.0.1:6143
> lis 07, 2020 1:05:02 PM io.netty.handler.logging.LoggingHandler bind
> INFO: [id: 0x47da6a0b] BIND: 0.0.0.0/0.0.0.0:6143
> lis 07, 2020 1:05:02 PM io.netty.handler.logging.LoggingHandler channelActive
> INFO: [id: 0x47da6a0b, L:/0:0:0:0:0:0:0:0:6143] ACTIVE
> lis 07, 2020 1:05:02 PM io.netty.handler.logging.LoggingHandler channelActive
> WARNING: [id: 0x107f76a8, L:/127.0.0.1:59414 - R:localhost/127.0.0.1:6143] ACTIVE
> lis 07, 2020 1:05:02 PM io.netty.handler.logging.LoggingHandler channelRead
> INFO: [id: 0x47da6a0b, L:/0:0:0:0:0:0:0:0:6143] READ: [id: 0x1c26ccdb, L:/127.0.0.1:6143 - R:/127.0.0.1:59414]
> lis 07, 2020 1:05:02 PM io.netty.handler.logging.LoggingHandler channelReadComplete
> INFO: [id: 0x47da6a0b, L:/0:0:0:0:0:0:0:0:6143] READ COMPLETE
> lis 07, 2020 1:05:02 PM io.netty.handler.logging.LoggingHandler channelRegistered
> WARNING: [id: 0x1c26ccdb, L:/127.0.0.1:6143 - R:/127.0.0.1:59414] REGISTERED
> lis 07, 2020 1:05:02 PM io.netty.handler.logging.LoggingHandler channelActive
> WARNING: [id: 0x1c26ccdb, L:/127.0.0.1:6143 - R:/127.0.0.1:59414] ACTIVE
> Server Channel Active
> ByteBuf out size: 256
> lis 07, 2020 1:05:02 PM io.netty.handler.logging.LoggingHandler write
> WARNING: [id: 0x1c26ccdb, L:/127.0.0.1:6143 - R:/127.0.0.1:59414] WRITE: 98B
>          +-------------------------------------------------+
>          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
> +--------+-------------------------------------------------+----------------+
> 

Where "Message cant be sent! do not match!" is my output for code i provided in earlier message.

and when i set 

p.addLast(new LoggingHandler(LogLevel.ERROR));

i see:

> lis 07, 2020 1:06:43 PM io.netty.handler.logging.LoggingHandler channelRegistered
> INFO: [id: 0xc67da6c8] REGISTERED
> lis 07, 2020 1:06:43 PM io.netty.handler.logging.LoggingHandler channelRegistered
> SEVERE: [id: 0x80004f41] REGISTERED
> lis 07, 2020 1:06:43 PM io.netty.handler.logging.LoggingHandler connect
> SEVERE: [id: 0x80004f41] CONNECT: localhost/127.0.0.1:6143
> lis 07, 2020 1:06:43 PM io.netty.handler.logging.LoggingHandler bind
> INFO: [id: 0xc67da6c8] BIND: 0.0.0.0/0.0.0.0:6143
> lis 07, 2020 1:06:43 PM io.netty.handler.logging.LoggingHandler channelActive
> INFO: [id: 0xc67da6c8, L:/0:0:0:0:0:0:0:0:6143] ACTIVE
> lis 07, 2020 1:06:43 PM io.netty.handler.logging.LoggingHandler channelActive
> SEVERE: [id: 0x80004f41, L:/127.0.0.1:59420 - R:localhost/127.0.0.1:6143] ACTIVE
> lis 07, 2020 1:06:43 PM io.netty.handler.logging.LoggingHandler channelRead
> INFO: [id: 0xc67da6c8, L:/0:0:0:0:0:0:0:0:6143] READ: [id: 0x223834f5, L:/127.0.0.1:6143 - R:/127.0.0.1:59420]
> lis 07, 2020 1:06:43 PM io.netty.handler.logging.LoggingHandler channelReadComplete
> INFO: [id: 0xc67da6c8, L:/0:0:0:0:0:0:0:0:6143] READ COMPLETE
> Server Channel Active
> lis 07, 2020 1:06:43 PM io.netty.handler.logging.LoggingHandler channelRegistered
> SEVERE: [id: 0x223834f5, L:/127.0.0.1:6143 - R:/127.0.0.1:59420] REGISTERED
> lis 07, 2020 1:06:43 PM io.netty.handler.logging.LoggingHandler channelActive
> SEVERE: [id: 0x223834f5, L:/127.0.0.1:6143 - R:/127.0.0.1:59420] ACTIVE
> ByteBuf out size: 256
> lis 07, 2020 1:06:43 PM io.netty.handler.logging.LoggingHandler write
> SEVERE: [id: 0x223834f5, L:/127.0.0.1:6143 - R:/127.0.0.1:59420] WRITE: 98B
>          +-------------------------------------------------+
>          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
> +--------+-------------------------------------------------+----------------+

While EVERYTHING WORK FINE (since i use serialialized object in this example)

how it can now know if this is SEVERE or WARN or INFO it just depends what level i set, it anyway print same info that is harmless...

**Comment by oxplay2** [comment]
**Also next issue i have** (i still write in this github issue, since mayeb its all related)

why, sometimes, it write "CHANNEL is active", while it is not executing "channelActive" in ServerHandler(ChannelInboundHandlerAdapter) i have for it.

like i have:

```
    @Override
    public void channelActive(ChannelHandlerContext ctx) throws Exception {
        System.out.println("Server Channel Active");
        this.ctx = ctx;
    }
```

but anyway in 50% of run, i dont see println and ctx is not setup.(my warning message)

> lis 07, 2020 1:31:01 PM io.netty.handler.logging.LoggingHandler channelRegistered
> INFO: [id: 0x6a9e56c4] REGISTERED
> lis 07, 2020 1:31:01 PM io.netty.handler.logging.LoggingHandler bind
> INFO: [id: 0x6a9e56c4] BIND: 0.0.0.0/0.0.0.0:6143
> lis 07, 2020 1:31:01 PM io.netty.handler.logging.LoggingHandler channelActive
> INFO: [id: 0x6a9e56c4, L:/0:0:0:0:0:0:0:0:6143] ACTIVE
> lis 07, 2020 1:31:02 PM pl.sarnet.engine.rnetwork.Server broadcast
> WARNING: Could not broadcast message, handler context is still not available
> lis 07, 2020 1:31:02 PM pl.sarnet.engine.rnetwork.Server broadcast
> WARNING: Could not broadcast message, handler context is still not available

**Comment by chrisvest** [comment]
This should help: https://github.com/netty/netty/pull/10807
