### ISSUE TITLE
Question about multiple TCP ports in the same service

### ISSUE THREAD

**Issue by matildasmeds** [netty/netty#10781]
We are looking into how to expose multiple TCP ports using Netty, because we need different handling pipelines based on message source.

We see following implementations in the wild:
* Create one ServerBootstrap for each port. This solution has some overhead (not known how much), and separate thread pools for each ServerBootstrap.
* Bind each port to the same ServerBootstrap. With this option it might be possible to use the same NioEventLoopGroups for all ports, on code level, but we don’t know if the ports will be matched correctly to the pipelines or not.

However, we can't find mentions of these uses in the official documentation. Would be incredibly helpful to hear from maintainers, or someone who knows the code well, what are the considerations for each option. The service will likely have a large number of simultaneous active connections.

**Comment by normanmaurer** [comment]
You should use multiple bootstraps but use the same EventLoopGroups for these. This way you share the thread pools.

**Comment by matildasmeds** [comment]
Great! On code level this is straight-forward to setup. Based on docs we just weren't sure if it is "supported" in a sense. Thank you for the prompt response. :100:

**Comment by matildasmeds** [comment]
Would you use the same EventLoopGroup for both boss & worker threads, or separate?
In case of separate, how many boss threads per bootstrap?

**Comment by matildasmeds** [comment]
Copying the answer from Twitter here (in case someone finds the issue and needs this info)
"This depends on what you do etc… attach a profiler to pick the right one. Usually I would start with using the same group for boss and worker"
Closing issue. Thanks! 💯 🎉
