### ISSUE TITLE
ByteBuf#setBytes(xxx) cause JVM crash

### ISSUE THREAD

**Issue by Ech0Fan** [netty/netty#10791]
### Expected behavior

```java
Unpooled.directBuffer().setBytes(0, (byte[]) null, 0, 1);
```
this code is expecting a NPE

### Actual behavior

JVM crashed after calling `PlatformDependent.copyMemory(src, srcIndex, addr, length)`.
Maybe we should check whether the `byte[] ` is null?

https://github.com/netty/netty/blob/944a0205862e32f1020647bbf4ef4eca5587446e/buffer/src/main/java/io/netty/buffer/PooledUnsafeDirectByteBuf.java#L198-L201
https://github.com/netty/netty/blob/944a0205862e32f1020647bbf4ef4eca5587446e/buffer/src/main/java/io/netty/buffer/UnsafeByteBufUtil.java#L533-L538

And the same behavior with `UnpooledUnsafeDirectByteBuf`
https://github.com/netty/netty/blob/944a0205862e32f1020647bbf4ef4eca5587446e/buffer/src/main/java/io/netty/buffer/UnpooledUnsafeDirectByteBuf.java#L261-L264
### Netty version

4.1.53.Final

### JVM version (e.g. `java -version`)

1.8.0_232

### OS version (e.g. `uname -a`)

Windows env

**Comment by franz1981** [comment]
It makes sense!
prs are welcome: we love contributions :)

**Comment by Ech0Fan** [comment]
Ok, I'll try :)
