### ISSUE TITLE
WebSocketClientExtensionHandler doesn't check if extensions are already present in sec-websocket-extensions header

### ISSUE THREAD

**Issue by slandelle** [netty/netty#10792]
### Expected behavior

Netty verifies that extensions are not already present in sec-websocket-extensions header before appending them.

### Actual behavior

Netty doesn't check, possibly resulting in duplicated values.

### Steps to reproduce

Just read existing code: https://github.com/netty/netty/blob/netty-4.1.54.Final/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketClientExtensionHandler.java#L65-L73

### Netty version

4.1.54

### JVM version (e.g. `java -version`)

Irrelevant

### OS version (e.g. `uname -a`)

Irrelevant

**Comment by slandelle** [comment]
Will provide a PR, probably next week.

**Comment by normanmaurer** [comment]
@slandelle any update ?

**Comment by slandelle** [comment]
@normanmaurer PTAL #10951
