### ISSUE TITLE
Vulnerability: Man-in-the-Middle (MitM)

### ISSUE THREAD

**Issue by superalb21234** [netty/netty#10806]
### Actual behavior
netty-handler is vulnerable to man-in-the-middle attacks. The library uses an SSLEngine that does not verify certificate hostnames when establishing connections with clients by default. This allows an attacker to potentially intercept and modify network traffic in a successful man-in-the-middle attack.

### Netty version
Latest version still has this vulnerability

**Comment by superalb21234** [comment]
is there a possible future fix for this vulnerability issue?
FYI: using veracode platform to find some vulnerabilities in the application

**Comment by hyperxpro** [comment]
Duplicate of #10362  #9930.

This issue will not be fixed in Netty 4.1.X. It's already scheduled for Netty 5.X in #8537.

**Comment by normanmaurer** [comment]
Yes as stated we will change this in netty 5.
