### ISSUE TITLE
DatagramPacket.recipient() of NioDatagramChannel doesn't return the actual  destination IP (multicast address)

### ISSUE THREAD

**Issue by zglslyg** [netty/netty#10823]
### Expected behavior
get the actual multicast address like : 234.2.1.4
### Actual behavior
get the app is bound to like: 192.168.1.101
### Steps to reproduce
--
### Minimal yet complete reproducer code (or URL to code)
... 
 private class MulticastHandler extends SimpleChannelInboundHandler<DatagramPacket> {
        @Override
        protected void channelRead0(ChannelHandlerContext ctx, DatagramPacket msg) throws Exception {
            String destinationIp = msg.recipient().getAddress().getHostAddress();
...
### Netty version
4.1.53 Final
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
windows 10

**Comment by normanmaurer** [comment]
We only return what is retuned by the OS / JDK. There is nothing we can do here.
