### ISSUE TITLE
io.netty.channel.DefaultFileRegion.transferTo throws EOPNOTSUPP (java.io.IOException: Operation not Supported)

### ISSUE THREAD

**Issue by ouyangxiaochen** [netty/netty#10828]
Expected behavior
Host A send a file stream to Host B successfully

Actual behavior
Got an IOException：Operation not Supported
ERROR org.apache.spark.network.server.TransportRequestHandler: Error sending result StreamResponse{streamId=/jars/spark-examples_2.11-2.2.1.jar, byteCount=1992533, body=FileSegmentManagedBuffer{file=/opt/spark/examples/jars/spark-examples_2.11-2.2.1.jar, offset=0, length=1992533}} to /175.117.1.16:42812; closing connection
java.io.IOException: Operation not Supported
        at sun.nio.ch.FileChannelImpl.transferTo0(Native Method)
        at sun.nio.ch.FileChannelImpl.transferToDirectlyInternal(FileChannelImpl.java:428)
        at sun.nio.ch.FileChannelImpl.transferToDirectly(FileChannelImpl.java:493)
        at sun.nio.ch.FileChannelImpl.transferTo(FileChannelImpl.java:608)
        at io.netty.channel.DefaultFileRegion.transferTo(DefaultFileRegion.java:139)

Steps to reproduce
1. Install a spark cluster
2. Run ’spark-submit --class org.apache.spark.examples.SparkPi --executor-cores 1 --executor-memory 1g --total-executor-cores 3 spark-examples_2.11-2.2.1.jar 100‘
3. we can find the IOE(Operation not Supported) in console
4. we catched the Process trace log as follows:
```
98724 15:32:58.175513 open("/opt/spark/examples/jars/spark-examples_2.11-2.2.1.jar", O_RDONLY) = 421 <0.000027>
98724 15:32:58.175581 fstat(421, {st_mode=S_IFREG|0777, st_size=1992533, ...}) = 0 <0.000016>
98724 15:32:58.175662 fstat(421, {st_mode=S_IFREG|0777, st_size=1992533, ...}) = 0 <0.000015>
98724 15:32:58.175725 sendfile(420, 421, [0], 1992533) = -1 EOPNOTSUPP (Operation not supported) <0.000024>
98724 15:32:58.175892 getsockopt(420, SOL_SOCKET, SO_LINGER, {onoff=0, linger=0}, [8]) = 0 <0.000018>
```

### Minimal yet complete reproducer code (or URL to code)

Netty version
4.0.43

JVM version (e.g. `java -version`)
JDK1.8

 OS version (e.g. `uname -a`)
SUSE12 SP5

**Comment by normanmaurer** [comment]
This exception is thrown from the JDK itself, so there is nothing we can do about it.
