### ISSUE TITLE
Whitespace Header Value Decoding Failure

### ISSUE THREAD

**Issue by camron-johnson** [netty/netty#10820]
### Expected behavior

Netty should successfully decode a header field value beginning with a character that Java considers [isWhitespace](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Character.html#isWhitespace(char)) but is not either a space(0x20) or horizontal tab(0x09). According to [RFC 7230 Section 3.2](https://tools.ietf.org/html/rfc7230#section-3.2), there can be optional whitespace (OWS) between the colon and the field value with OWS defined as a space or horizontal tab: `OWS = *( SP / HTAB )`. Therefore, an `IllegalArgumentException` should not be thrown for field values beginning with characters Java considers whitespace that are not either a space or a horizontal tab. Here is the Netty logic in question:
https://github.com/netty/netty/blob/9cfe3bf5e3a3f0527bf70d969a32c2cd54a30343/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java#L903-L909

Characters in the following list should be considered as the first character of the field value rather than result in decoder failure:

* '\u000B', U+000B VERTICAL TABULATION
* '\f', U+000C FORM FEED
* '\u001C', U+001C FILE SEPARATOR
* '\u001D', U+001D GROUP SEPARATOR
* '\u001E', U+001E RECORD SEPARATOR
* '\u001F', U+001F UNIT SEPARATOR

### Actual behavior

If the first character after the colon in a header, besides a space or horizontal tab, is one of the six characters above an IllegalArgumentException is thrown.

```
Caused by: java.lang.IllegalArgumentException: Invalid separator, only a single space or horizontal tab allowed, but received a ''
    at io.netty.handler.codec.http.HttpObjectDecoder.findNonWhitespace(HttpObjectDecoder.java:907)
    at io.netty.handler.codec.http.HttpObjectDecoder.splitHeader(HttpObjectDecoder.java:861)
    at io.netty.handler.codec.http.HttpObjectDecoder.readHeaders(HttpObjectDecoder.java:613)
    at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:258)
    at io.netty.handler.codec.http.HttpClientCodec$Decoder.decode(HttpClientCodec.java:225)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
```

### Steps to reproduce

This test should succeed but currently fails. 

```
@Test
public void testOtherWhitespace() {
    EmbeddedChannel channel = new EmbeddedChannel(new HttpRequestDecoder());
    String fieldName = "name";
    char unitSeparator = 0x1f;
    String fieldValue = unitSeparator + "value";
    channel.writeInbound(Unpooled.copiedBuffer("GET / HTTP/1.1\r\n", CharsetUtil.US_ASCII));
    channel.writeInbound(Unpooled.copiedBuffer(fieldName + ": " + fieldValue + "\r\n\r\n", CharsetUtil.US_ASCII));
    HttpRequest request = channel.readInbound();
    org.hamcrest.MatcherAssert.assertThat(request.decoderResult().isSuccess(), org.hamcrest.Matchers.is(true));
    org.hamcrest.MatcherAssert.assertThat(request.headers().get(fieldName), org.hamcrest.Matchers.is(fieldValue));
}
```

### Netty version

4.1.51.Final

**Comment by normanmaurer** [comment]
After rechecking the RFC I think there is a problem in how we implement the logic here but I think what you expect is not correct as well.

This is how a header is defined:

```
    field-content  = field-vchar [ 1*( SP / HTAB ) field-vchar ]
    field-vchar    = VCHAR / obs-text
```

```
     obs-text       = %x80-FF
```
So while I think its invalid to throw because of invalid separator, the code-points you listed (and also what you used in the unit test) is not allowed as a header value.

**Comment by camron-johnson** [comment]
I see, thanks for pointing this out. How do you think the characters provided should be handled?

**Comment by normanmaurer** [comment]
@camron-johnson I think it still should throw because of header validation. But it should indicate that these are not valid for header values.

**Comment by ct-tzarouali** [comment]
After upgrading to Netty 4.1.84.Final I'm also seeing that leading whitespaces inside the header value produce the following error:
`java.lang.IllegalArgumentException: a header value contains prohibited character 0x20 at index 0.`

**Comment by chrisvest** [comment]
@ct-tzarouali That is correct. Header values cannot start with a whitespace.

**Comment by chrisvest** [comment]
Header value validation was overhauled in 4.1.84.Final to follow the RFCs to the letter:

```
Validate value to field-content rule.
 field-content  = field-vchar [ 1*( SP / HTAB ) field-vchar ]
 field-vchar    = VCHAR / obs-text
 VCHAR          = %x21-7E ; visible (printing) characters
 obs-text       = %x80-FF
 SP             = %x20
 HTAB           = %x09 ; horizontal tab
 See: https://datatracker.ietf.org/doc/html/rfc7230#section-3.2
 And: https://datatracker.ietf.org/doc/html/rfc5234#appendix-B.1
```

According to the above, the characters mentioned in this issue are not valid characters in header values:

* '\u000B', U+000B VERTICAL TABULATION
* '\f', U+000C FORM FEED
* '\u001C', U+001C FILE SEPARATOR
* '\u001D', U+001D GROUP SEPARATOR
* '\u001E', U+001E RECORD SEPARATOR
* '\u001F', U+001F UNIT SEPARATOR

So I think we can close this.

**Comment by ngupta0205** [comment]
I also ran into this issue mentioned [here](https://github.com/Azure/azure-sdk-for-java/issues/34161).

@chrisvest as per RFC-7230 :
`Each header field consists of a case-insensitive field name followed
   by a colon (":"), optional leading whitespace, the field value, and
   optional trailing whitespace.`
   
 having a whitespace before the value is correct. Shouldn't we fix this in netty?

**Comment by chrisvest** [comment]
@ngupta0205 When we decode the header in the HTTP object e.g. from a request off the network, the optional whitespace is ignored, but the header *value* still cannot start with a whitespace. The issue you link is about someone generating a header value from other data, and the generated value ends up starting with a space. When they attempt to add the value to a (HTTP) Headers object, the validation refuses the value.

**Comment by chrisvest** [comment]
@ngupta0205 See #13486

**Comment by ngupta0205** [comment]
@chrisvest what is the difference between using an extra space prefixed into an existing data and the test you wrote above? The issue I linked had this header value ` Azure-Storage/11.0.0 (JavaJRE 1.8.0_292; MacOSX 10.16)` for user-agent. Notice the leading whitespace. Are you trying to say that - in the above test you wrote if the value of `X-0-Header` was generated by a value of another string which had a trailing space then it would have failed?

**Comment by chrisvest** [comment]
I'm saying that if we are decoding an HTTP message with the following header:

```
user-agent:  Azure-Storage/11.0.0 (JavaJRE 1.8.0_292; MacOSX 10.16)
```

Where there are two spaces after the colon, then we will decode a header value that has no leading spaces, because the optional whitespace after the colon is ignored.

On the other hand, if you have an `HttpHeaders` object with value validation, and you add a value to it that contains leading whitespace, then you will get an exception.
