### ISSUE TITLE
Channel#writeAndFlush method costly

### ISSUE THREAD

**Issue by hyperxpro** [netty/netty#10835]
### Expected behavior
Since Netty is asynchronous and all I/O events are handled by EventLoop, there should be the minimal cost of calling `Channel#writeAndFlush`.

### Actual behavior
However, for 1.2M writes, `Channel#writeAndFlush` is taking 26,925 ms.

### Steps to reproduce
Just do lots of write and flush.

### Minimal yet complete reproducer code (or URL to code)
N/A

### Netty version
4.1.54.Final

### JVM version (e.g. `java -version`)
Java 11

### OS version (e.g. `uname -a`)
Linux DESKTOP-ANM4Q9I 4.19.128-microsoft-standard
Windows 10 Pro x64

Attaching a screenshot of JProfiler.
![Screenshot (60)](https://user-images.githubusercontent.com/24762260/101001030-a1b6d080-3584-11eb-87ba-061e6e7a1702.png)

**Comment by hyperxpro** [comment]
![Screenshot (59)](https://user-images.githubusercontent.com/24762260/101001078-ac716580-3584-11eb-8523-815f2dea6fdd.png)

Also, I'm wondering, why Recycler is on fire?

**Comment by hyperxpro** [comment]
Btw, Netty Epoll is matching head to head with HAProxy performance. :D

**Comment by normanmaurer** [comment]
`writeAndFlush(...)` will walk the pipeline of handlers so its expected that it needs to do some work. That said what I see in your profile doesn't look crazy at all.  Recycler is used for pool a lot of different things. So This sounds about right as well.

**Comment by hyperxpro** [comment]
Sounds fair enough but:
1. I only have 1 Handler in the pipeline. And `channelRead` is just calls `writeAndFlush` into `DownstreamChannel`.

2. I'd love to know a little more about the object pooling mechanism. Because after 1.2M writes and reads, it has created 800k Instances. Is this normal? Also, can I tune it to optimize it for high throughput?

I'm pushing Netty hard and it's super strong indeed. 🔥🔥🔥🔥

**Comment by johnou** [comment]
@hyperxpro what are you doing with the write and flush promise? If nothing you may consider passing in voidPromise().

**Comment by hyperxpro** [comment]
I do nothing with the returned `ChannelFuture`. `voidPromise` creates a new instance too? And how does using it will affect performance?

**Comment by johnou** [comment]
@hyperxpro like this

```java
channel.writeAndFlush(buf, channel.voidPromise());
```

**Comment by hyperxpro** [comment]
> @hyperxpro like this
> 
> ```java
> channel.writeAndFlush(buf, channel.voidPromise());
> ```

Traffic is not being sent with `voidPromise`. ;/

**Comment by johnou** [comment]
oh side note, this will break write idle timeout with IdleStateHandler.

**Comment by johnou** [comment]
> > @hyperxpro like this
> > ```java
> > channel.writeAndFlush(buf, channel.voidPromise());
> > ```
> 
> Traffic is not being sent with `voidPromise`. ;/

then your channel pipeline might rely on it..?

**Comment by hyperxpro** [comment]
I had IdleStateHandler but removed it. Nothing in my pipeline relies on `writeAndFlush` AFAIK.

Would you mind talking look? https://github.com/shieldblaze/ExpressGateway/tree/main/protocol-tcp/src/main/java/com/shieldblaze/expressgateway/protocol/tcp

**Comment by hyperxpro** [comment]
Man this thing is going beyond 2M Instances ;/ and then GC kicks in and freeze.

**Comment by hyperxpro** [comment]
Okay, I got `voidPromise` working but no difference in object creation and flush time. Throughout is almost near HAProxy and NGINX levels.

Just worried about those big Recyclers now.

**Comment by normanmaurer** [comment]
I wonder if you are just writing to fast and so stuff pills up. Are you handling writability at all ?

**Comment by hyperxpro** [comment]
Yes, I'm benchmarking so lots of writes. I am not handling writability because it's an L4 Load Balancer and I push data down to the backend server as soon as I read it.

**Comment by franz1981** [comment]
@hyperxpro 

> I am not handling writability because it's an L4 Load Balancer and I push data down to the backend server as soon as I read it.

That doesn't mean that data would actually being flushed ASAP as you expect anyway...
I suggest to use some other tool (nudge nudge async-profiler) to get the over-all picture (per-thread?) of cpu and alloc(ation) side.

As a general rule of thumb, if Recycler are hanling burst of allocation/releases across threads is quite normal they cost a bit: that's something that could (and is nice) to improve but still need a wide-spectrum investigation IMO to understand how relevant is on your use case. The very last version of the code you've sent doesn't show void promises usage as far as I can see or am I missing anything?

**Comment by hyperxpro** [comment]
@franz1981 Here is the branch where I'm testing: https://github.com/shieldblaze/ExpressGateway/tree/prof/protocol-tcp/src/main/java/com/shieldblaze/expressgateway/protocol/tcp

I'm going to deploy and test on Google Cloud VM and also test IO_URING performance. I don't have the async-profiler and looks like it's not available for Windows.

Just wondering, even when using `voidPromise` I can see `DefaultChannelPromise` being created,
![Screenshot (61)](https://user-images.githubusercontent.com/24762260/101125627-b2685480-361f-11eb-91f0-d46e0c185621.png)

**Comment by normanmaurer** [comment]
@hyperxpro no matter what you do you need to keep `writability` in mind if you write something like a proxy. Otherwise you risk to blow up memory.

For proxy like applications it is usually good enough to stop reading when there is too much stuff in the outbound channel and  turn out reading again once the channel become readable again.

**Comment by hyperxpro** [comment]
IO_URING on Fire. Free 5x performance improvement over Epoll. 🔥🔥🔥🔥

![Screenshot (62)](https://user-images.githubusercontent.com/24762260/101163565-c8930680-3659-11eb-8b11-6c90b7c09cba.png)

**Comment by hyperxpro** [comment]
> @hyperxpro no matter what you do you need to keep `writability` in mind if you write something like a proxy. Otherwise you risk to blow up memory.
> 
> For proxy like applications it is usually good enough to stop reading when there is too much stuff in the outbound channel and turn out reading again once the channel become readable again.

I'll take care of this for sure. But for now, I'm debugging every single call and Netty is just working perfectly.

**Comment by hyperxpro** [comment]
I'm closing this now. Switching to IO_URING did decrease access time and increased throughput.

Thanks to everyone for suggestions and their efforts. :)

**Comment by normanmaurer** [comment]
@hyperxpro if you have any perf numbers to share (before and later) in terms of thoughtput please let us know

**Comment by hyperxpro** [comment]
```
Epoll:

root@client:/home/ExpressGateway# wrk -t8 -c100 http://10.128.0.4:9110 -d10s -R 100k
Running 10s test @ http://10.128.0.4:9110
  8 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.86s     2.19s    8.17s    58.15%
    Req/Sec       -nan      -nan   0.00      0.00%
  224894 requests in 10.00s, 18.45MB read
Requests/sec:  22489.07
Transfer/sec:      1.84MB


IOURING:

root@client:/home/ExpressGateway# wrk -t8 -c100 http://10.128.0.4:9110 -d10s -R 100k
Running 10s test @ http://10.128.0.4:9110
  8 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.12s   630.22ms   2.48s    59.34%
    Req/Sec       -nan      -nan   0.00      0.00%
  772343 requests in 10.00s, 36.83MB read
Requests/sec:  77238.49
Transfer/sec:      3.68MB
```

My kernel is hacked a little bit so not vanilla but even on the vanilla kernel, people should be able to get good results.

**Comment by hyperxpro** [comment]
Unfortunately, Epoll TCP Splice vs Read and Write makes no difference. Don't know why. ;/
