### ISSUE TITLE
netty  接收超过1024字节的数据

### ISSUE THREAD

**Issue by git-chenjiqing** [netty/netty#10833]
### Expected behavior
单包数据读取大于1024
### Actual behavior
> 得到此异常：java.lang.IndexOutOfBoundsException: readerIndex(8) + length(8968) exceeds writerIndex(1024): PooledUnsafeDirectByteBuf(ridx: 8, widx: 1024, cap: 1024)
### Steps to reproduce
read单包大小超过1024
### Netty version
4.1.2.Final
### JVM version (e.g. `java -version`)
java8
### OS version (e.g. `uname -a`)
win10

**Comment by normanmaurer** [comment]
Please use English ... and also include the full stacktrace

**Comment by git-chenjiqing** [comment]
Hello, thank you for your reply
I'm using netty to read data,However, the size of a single packet exceeds 1024.
So I get the following exception
>java.lang.IndexOutOfBoundsException: readerIndex(8) + length(8968) exceeds writerIndex(1024): PooledUnsafeDirectByteBuf(ridx: 8, widx: 1024, cap: 1024)

**Comment by normanmaurer** [comment]
@git-chenjiqing you need to check first if there is enough data to read. Remember netty is non blocking so it will push bytes through the pipeline as it sees it. You may need to implement your own `ByteToMessageDecoder` to buffer data until there is enough to be read
