### ISSUE TITLE
Condition present in AbstractNioByteChannel triggering a websocket disconnect.

### ISSUE THREAD

**Issue by earce** [netty/netty#10830]
### Expected behavior

No explicit expectation but I am looking to understand Netty behavior. 

### Actual behavior

`AbstractNioByteChannel.java` triggers a disconnect. 

In particular why is the condition present on line 156 [AbstractNioByteChannel.java](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/nio/AbstractNioByteChannel.java#L156) a trigger for a close?

### Steps to reproduce

Connecting to various web socket based services getting disconnected every few hours.

### Minimal yet complete reproducer code (or URL to code)

[NettyStreamingService.java](https://github.com/knowm/XChange/blob/develop/xchange-stream-service-netty/src/main/java/info/bitrich/xchangestream/service/netty/NettyStreamingService.java#L182)

### Netty version

4.1.54.Final

### JVM version (e.g. `java -version`)

Java 11

### OS version (e.g. `uname -a`)

Linux ip-172-31-68-243.ec2.internal 4.14.186-146.268.amzn2.x86_64 #1 SMP Tue Jul 14 18:16:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by earce** [comment]
@chrisvest opened an issue https://github.com/netty/netty/commit/99c85ef4f55d098cab482da0955ef3f05617758e#commitcomment-44674478, thanks for the heads up

**Comment by normanmaurer** [comment]
Because -1 means EOF https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/channels/SocketChannel.html#read(java.nio.ByteBuffer)

**Comment by earce** [comment]
@normanmaurer thanks for the quick response, is that EOF indicative of the server having sent a close/shutdown hook?
