### ISSUE TITLE
AnnotatedConnectException: Connection refused: localhost/127.0.1.1:37655

### ISSUE THREAD

**Issue by violetagg** [netty/netty#10834]
When there are more than one entries for localhost in `/etc/hosts`, connection is refused.
This happens only when using `DnsAddressResolverGroup`. If `DefaultAddressResolverGroup` is used there is no problem with connection establishment.

```
# /etc/hosts
127.0.1.1	localhost
127.0.0.1	localhost
```

If `127.0.0.1` is first then there is no problem

```
# /etc/hosts
127.0.0.1	localhost
127.0.1.1	localhost
```

Original issue https://github.com/reactor/reactor-netty/issues/1405

### Expected behavior
Connection to be established regardless of the `AddressResolverGroup` that is used.

### Actual behavior
Exception is thrown with `DnsAddressResolverGroup`:
`AnnotatedConnectException: Connection refused: localhost/127.0.1.1:37655`

### Steps to reproduce
A reproducible example and steps are described in the issue https://github.com/reactor/reactor-netty/issues/1405

I added additional test to the existing test cases here https://github.com/hisener/playground/blob/master/spring-webclient-connection-failure-test/src/test/java/com/github/hisener/spring/webclient/WebClientTest.java

```
    @RepeatedTest(10)
    void nettyClient() throws Exception {
        NioEventLoopGroup group = new NioEventLoopGroup();

        try {
            Bootstrap bootstrap = new Bootstrap();

            bootstrap.group(group)
                     .channel(NioSocketChannel.class)
                     // There is no issue with DefaultAddressResolverGroup
                     //.resolver(DefaultAddressResolverGroup.INSTANCE)
                     .resolver(new DnsAddressResolverGroup(new DnsNameResolverBuilder(group.next()).channelType(NioDatagramChannel.class)))
                     .handler(new ChannelInitializer<SocketChannel>() {
                         @Override
                         protected void initChannel(SocketChannel socketChannel) {
                             socketChannel.pipeline()
                                          .addLast(new HttpClientCodec());
                         }
                     });

            Channel ch = bootstrap.connect(baseUrl.getHost(), baseUrl.getPort())
                                  .sync()
                                  .channel();

            ch.close();
        }
        finally {
            group.shutdownGracefully();
        }
    }
```

### Netty version
4.1.55.Final-SNAPSHOT

### JVM version (e.g. `java -version`)
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment 18.9 (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9.1+1, mixed mode)

### OS version (e.g. `uname -a`)
Linux b732417723fd 5.4.39-linuxkit #1 SMP Fri May 8 23:03:06 UTC 2020 x86_64 GNU/Linux

**Comment by single-wolf** [comment]
That seems none of Netty`s business, cause just connect 127.0.0.1:37655 successfully but not 127.0.1.1:37655

**Comment by normanmaurer** [comment]
@violetagg can you connect to the service via telnet on `127.0.1.1` ?

**Comment by violetagg** [comment]
> @violetagg can you connect to the service via telnet on `127.0.1.1` ?

```
# python -m SimpleHTTPServer 8000 &> /dev/null & pid=$!
[1] 1143
# telnet 127.0.1.1 8000
Trying 127.0.1.1...
Connected to 127.0.1.1.
Escape character is '^]'.
^C
Connection closed by foreign host.
# telnet 127.0.0.1 8000
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
^C
Connection closed by foreign host.
# telnet localhost 8000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
^C
Connection closed by foreign host.
```

**Comment by hisener** [comment]
Thanks, @violetagg. I've also added the test case to [the repo](https://github.com/hisener/playground/blob/master/spring-webclient-connection-failure-test/src/test/java/com/github/hisener/spring/webclient/WebClientTest.java#L83). Do you have some time to have a look at this issue? @normanmaurer 

```
[ERROR] Failures: 
[ERROR]   WebClientTest.reactorNetty expectation "assertNext" failed (expected: onNext(); actual: onError(io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.1.1:42891))
[ERROR]   WebClientTest.webClient expectation "expectComplete" failed (expected: onComplete(); actual: onError(org.springframework.web.reactive.function.client.WebClientRequestException: finishConnect(..) failed: Connection refused: localhost/127.0.1.1:42891; nested exception is io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.1.1:42891))
[ERROR] Errors: 
[ERROR]   WebClientTest.nettyClient » AnnotatedConnect Connection refused: localhost/127...
[INFO] 
[ERROR] Tests run: 4, Failures: 2, Errors: 1, Skipped: 0
```
https://travis-ci.com/github/hisener/playground/builds/209949385#L1163-L1169

**Comment by violetagg** [comment]
@normanmaurer The current Netty implementations returns always only one address for `localhost` when `resolveAll` is invoked. If Netty is able to return all resolved addresses for `localhost`, Reactor Netty will be able to iterate over the result.

https://github.com/netty/netty/blob/6724786dcc9fa38ba516dab97a04e2bbc17e81d9/resolver/src/main/java/io/netty/resolver/DefaultHostsFileEntriesResolver.java#L46-L63

https://github.com/netty/netty/blob/6724786dcc9fa38ba516dab97a04e2bbc17e81d9/resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java#L1023

https://github.com/netty/netty/blob/6724786dcc9fa38ba516dab97a04e2bbc17e81d9/resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java#L684-L697

Also JDK's `HostsFileNameService` returns all entries IPv4/IPv6 for `localhost`, while Netty's `HostsFileParser` always returns the first for IPv4/IPv6. May be `completeOncePreferredResolved` if this is desired.

https://github.com/openjdk/jdk/blob/e8eda655bb27ab1b8d806a64622ea7ee9719a85d/src/java.base/share/classes/java/net/InetAddress.java#L1047-L1054

https://github.com/netty/netty/blob/6724786dcc9fa38ba516dab97a04e2bbc17e81d9/resolver/src/main/java/io/netty/resolver/HostsFileParser.java#L198-L209


Here is a simple test and its results:

```
@Test
void test() throws Exception {
    InetAddress[] addresses = InetAddress.getAllByName("localhost");
    System.out.println("JDK " + Arrays.asList(addresses));


    NioEventLoopGroup group = new NioEventLoopGroup();
    try {
        DefaultAddressResolverGroup.INSTANCE
                .getResolver(group.next())
                .resolveAll(InetSocketAddress.createUnresolved("localhost", 80))
                .addListener(future -> System.out.println("Netty DefaultAddressResolverGroup " + future.get()));

        DnsNameResolverBuilder builder = new DnsNameResolverBuilder(group.next())
                .channelType(NioDatagramChannel.class);
        DnsNameResolver resolver = builder.build();
        resolver.resolveAll("localhost")
                .addListener(future -> System.out.println("Netty DnsNameResolver " + future.get()));
    }
    finally {
        group.shutdownGracefully();
    }
}
```

```
JDK [localhost/127.0.0.1, localhost/127.0.1.1]
Netty DefaultAddressResolverGroup [localhost/127.0.0.1:80, localhost/127.0.1.1:80]
Netty DnsNameResolver [localhost/127.0.1.1]
```

Also I'm seeing that when I use JDK's `PlatformNameService`, the result is sorted, while when I force the usage of `HostsFileNameService`, they are not.

So I need a method that returns all entries for `localhost` like in JDK's implementation (preferably sorted). If it is not possible to modify the current interface (io.netty.resolver.HostsFileEntriesResolver), is it possible to introduce a new one?

**Comment by normanmaurer** [comment]
@violetagg I think we don't want to break the API ... So maybe add a "sup-interface" and implement it in our implementation ? We could expose a method like `List<InetAddress> addressess(...)` or something like this

**Comment by normanmaurer** [comment]
or we could just add an extra method to DefaultHostsFileEntriesResolver and do an instanceof check and call the extra method.

**Comment by violetagg** [comment]
> or we could just add an extra method to DefaultHostsFileEntriesResolver and do an instanceof check and call the extra method.

Even with `sup-interface` we will need `instance of` so may be let's add this functionality to `DefaultHostsFileEntriesResolver`, if later somebody wants also such functionality, we can always add `sup-interface`

**Comment by michael-o** [comment]
I see similar weird behavior when using Redisson 3.15.3 on top of Netty. Netty says:
```
1376 [main] [DEBUG] Loopback interface: lo1 (lo1, 127.0.1.1)
```
while `ifconfig` says:
```
$ ifconfig lo0
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x5
        inet 127.0.0.1 netmask 0xff000000
        groups: lo
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
osipovmi@deblndw013x:~/var/Projekte/MRESOLVER-25
$ ifconfig lo1
lo1: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet 127.0.1.1 netmask 0xffffffff
        groups: lo
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
```
Note that host `deblndw013x` uses `lo0` while `lo1` is a cloned loopback interface passed onto jails with a shared network stack as the jailhost.

Redis listens on:
```
$ sockstat | grep redis
menz_i   redis-serv 77878 6  tcp4   127.0.0.1:6379        *:*
```
