### ISSUE TITLE
netty-transport-native-kqueue-4.1.52.Final-osx-x86_64 jar  (and all previous versions) have a wrong Bundle-NativeCode on the manifest file

### ISSUE THREAD

**Issue by santdelv** [netty/netty#10856]
### Expected behavior
The value should be:
Bundle-NativeCode: META-INF/native/libnetty_transport_native_kqueue_x8
 6_64.jnilib; osname=MacOSX; processor=x86_64

### Actual behavior
The value is:
Bundle-NativeCode: META-INF/native/libnetty_transport_native_kqueue_x8
 6_64.jnilib; osname=MacOSX, processor=x86_64"

### Steps to reproduce
check the MANIFEST.MF in the netty-transport-native-kqueue-4.1.52.Final-osx-x86_64 jar or any previous version

**Comment by normanmaurer** [comment]
Thanks for the report... This should be fixed by https://github.com/netty/netty/pull/10865
