### ISSUE TITLE
EncoderException hidden when sending

### ISSUE THREAD

**Issue by brucelwl** [netty/netty#10861]
I used the ``marshalling`` serialization tool, but because the class ``UserInfo`` did not implements ``Serializable``, the client threw an exception when sending data. However, the exception was hidden, and there was no exception on the console. As a result, I did not know the cause of any exception

The second: 
according to my understanding, any exception should be handled by ``io.netty.channel.ChannelInboundHandler#exceptionCaught(ChannelHandlerContext ctx, Throwable cause)``

demo
https://github.com/brucelwl/demo/tree/netty-marshalling

**Comment by normanmaurer** [comment]
This is only true for inbound exceptions. Outbound bound operations (like write) will fail the promise only by default.

**Comment by brucelwl** [comment]
> This is only true for inbound exceptions. Outbound bound operations (like write) will fail the promise only by default.

OK, we don't discuss inbound exceptions, but please run my demo. The client sends data to the server, but the service can't receive it. It doesn't prompt any exceptions, which is very unfriendly。

In fact, the client has already had a serialization exception。
It is hoped that netty can output the exception stack information when the listener is not registered

![image](https://user-images.githubusercontent.com/13413715/102205208-d3755300-3f05-11eb-9cd4-9149136e5601.png)
