### ISSUE TITLE
Memory leak on handling https connections

### ISSUE THREAD

**Issue by junzhli** [netty/netty#10863]
### Expected behavior
No memory leak happened

### Actual behavior
Memory leak happened

### Steps to reproduce
To cause memory leak --> Use jdk-compiant ssl handler (e.g. conscrypt -> up to tls 1.3, jdk default security provider -> up to tls 1.2...) - non alpn supported ssl context

- conscrypt
set dependency in build.gradle - `org.conscrypt:conscrypt-openjdk:2.5.1:[use osdetector.classifier to set this properly e.g. osx-x86_64]`
specify jdk-compiant security provider by `Security.insertProviderAt(Conscrypt.newProvider(), 1)` before starting netty server

- jdk default security provider
additional setup is not necessary

Not to cause memory leak --> Use openssl-compiant ssl handler which provides alpn support for http2  (e.g. netty-tcnative-borningssl-static) - alpn supported ssl context

- netty-tcnative

set dependency in build.gradle - `io.netty:netty-tcnative-boringssl-static:2.0.35.Final`

### Minimal yet complete reproducer code (or URL to code)
[ktor-https-server.zip](https://github.com/netty/netty/files/5683230/ktor-https-server.zip)
Here is the code to make it easier to reproduce

### Netty version
4.1.54.Final

### JVM version (e.g. `java -version`)
jdk-8 (also reproducible when running on android api 29)

### OS version (e.g. `uname -a`)
macOS 10.15.7 (also reproducible when running on android)

I did several experiments to dig into what's going on here:
I use apache benchmark tool (ab) to send multiple https requests while monitoring the memory usage
I found out that memory usage goes higher when it comes to non jdk-compliant ssl handler solutions
Here is the results of memory usage for each ssl handler setting

- with conscrypt
![conscrypt](https://user-images.githubusercontent.com/4001697/101987444-14cfed80-3ccf-11eb-9e06-f1372227892b.gif)

- with jdk default security provider
![jdk](https://user-images.githubusercontent.com/4001697/101987452-1ef1ec00-3ccf-11eb-8387-d7eb850d7cc4.gif)

- with tcnative (borningssl)
![tcnative](https://user-images.githubusercontent.com/4001697/101987455-25806380-3ccf-11eb-846c-2c93d10cb351.gif)

Is there something wrong here? Thanks!

**Comment by hyperxpro** [comment]
I don't see any memory leak in this. Conscrypt is general purpose security provider. However, tcnative Boringssl is optimised for Netty TLS.

**Comment by junzhli** [comment]
Are these memory usages of two cases normal for non optimized ssl handlers (jdk compliant)? I would opt to use non tcnative ones as there is no obvious way to build tcnative for android platform. Or is it possible to build tcnative for android? Thanks!

**Comment by hyperxpro** [comment]
These values are fairly normal. I'm not sure about the Android build of tcnative.

**Comment by normanmaurer** [comment]
Like stated above this seems to be no memory leak just higher memory usage than what you may have expected. There is not much we can do as we have no control over the JDK implementation / conscrypt.

**Comment by junzhli** [comment]
After a few hours of experiments, I finally ends up using tcnative in Netty server running on Android. I am sure that tcnative should be compiled into android armv8 native library (aarch64-android)! It's really a big breakthrough! Thanks for all your supports and troubleshooting
