### ISSUE TITLE
QueryStringEncoder ignores Fragment

### ISSUE THREAD

**Issue by basalt79** [netty/netty#10864]
### Expected behavior
Fragment is handled correctly
### Actual behavior
Query parameters are attached at the end without checking the existence of fragment
### Minimal yet complete reproducer code (or URL to code)
https://github.com/basalt79/netty_QueryStringEncoder/blob/main/src/test/java/com/aigner/FragmentTest.java#L18
### Netty version
4.1.55.Final

### JVM version (e.g. `java -version`)
openjdk 15.0.1 2020-10-20

### OS version (e.g. `uname -a`)
5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@basalt79 we love PRs... Would you be interested to write a PR with a test-case + fix ?

**Comment by basalt79** [comment]
hi @normanmaurer  and @slandelle 

so looks like also existing parameters are not handled correctly
Because the Encoder is not using the Decoder to check for any existing parameters.
It just append to whatever string is passed.
https://github.com/basalt79/netty_QueryStringEncoder/blob/main/src/test/java/com/aigner/QueryStringEncoderTest.java#L12

so maybe the `QueryStringEncoder` and `QueryStringDecoder` are not the right tool to use for my usecase.

So I think this is not a fix, its rather a enhancement to the classes.
Sure I can provide this features in the Decoder and Encoder, but because I don't know the initial wanted behavior its hard to add functionality to this classes.

**Comment by slandelle** [comment]
Netty's QueryStringEncoder/QueryStringDecoder are very basic and are just toys for simple use cases.

Most people are not aware that RFC3936 is actually very complex, eg reserved chars are actually not the same in path and in query params, path segments, fragments... For example, lots of people use `java.net.URLEncoder` for encoding anything while as its javadoc states, it's used `for converting a String to the application/x-www-form-urlencoded MIME format`.

Supporting RFC3936 requires quite some work, eg:
* Apache HttpComponents' `org.apache.http.client.utils.URIBuilder`
* JAX-RS's `javax.ws.rs.core.UriBuilder`
* Spring's `org.springframework.web.util.UriComponentsBuilder`
* https://github.com/lemonlabsuk/scala-uri (Scala)

I'm not sure it's worth trying to fix this one use case, while there are so many other use cases that are broken.

I can think of the following:

* live with it as it is and recommend a good standalone Java library, like the Scala one I mentioned
* build a full RFC3936 implementation for Netty (I won't personally have time for this)

**Comment by basalt79** [comment]
Hi @normanmaurer and @slandelle, its fine for me, now I am aware of the provided functionality so i will use it in this regards.
So from my point of view, this issue can be closed.
