### ISSUE TITLE
有人使用springcloud alibaba集成过netty吗？？？

### ISSUE THREAD

**Issue by xiao-ma-nong** [netty/netty#10869]
我集成的无法访问

**Comment by chrisvest** [comment]
Please use English. And try asking your cloud provider first, until you're able to narrow the problem down to something Netty specific.

**Comment by xiao-ma-nong** [comment]
原文：
不好意思，原本以为你们会中文或者使用中文翻译...
是这样的
项目大体结构

springboot 2.3.4
springcloud Hoxton.SR8
springcloud alibaba  2.2.3.RELEASE
netty 4.1.50.Final

其他普通的http请求都是走 springcloud gateway的
netty 绑定的IP：端口是无法访问，当然啦也可以走网关，也不可以走网关
如果没有走网关那就直接 ip：服务端口即可访问，我使用webscoket无法进行访问
走了网关 不知道是不是http或者其他的原因是报错 URL404

translation：

Sorry, I thought you could speak Chinese or use Chinese translation... It’s the general structure of the project

springboot 2.3.4
springcloud Hoxton.SR8
springcloud alibaba  2.2.3.RELEASE
netty 4.1.50.Final

Other ordinary http requests are from springcloud gateway

Netty bound IP: The port is not accessible. Of course, you can also use the gateway or the gateway. If you don’t use the gateway, you can directly ip: The service port can be accessed. I can’t access it using webscoket. I don’t know if it is. It is not http or other reasons are error URL404
