### ISSUE TITLE
Netty FileDescriptor throws this exception [readAddress(..) failed: Connection reset by peer]

### ISSUE THREAD

**Issue by klboke** [netty/netty#10873]
### Expected behavior
I googled this question and found a lot of similar questions, but none of them is consistent with the exception message we encountered. The answer is similar to the link reset caused by the server not being closed properly, but I still want to get more accurate answer. Or have more people encountered readAddress(..) failed?
### Actual behavior
The grpc client finally threw this exception message [readAddress(..) failed: Connection reset by peer]
### Steps to reproduce
This is accidental, and it has not been able to reproduce in the test on this machine. I have tried various violent interventions on the Internet, but I can’t reproduce this anomaly
### Minimal yet complete reproducer code (or URL to code)
The exception is finally thrown by the following code:https://github.com/netty/netty/blob/4.1/transport-native-unix-common/src/main/java/io/netty/channel/unix/FileDescriptor.java#L140
```java
    public final int readAddress(long address, int pos, int limit) throws IOException {
        int res = readAddress(fd, address, pos, limit);
        if (res > 0) {
            return res;
        }
        if (res == 0) {
            return -1;
        }
        return ioResult("readAddress", res,
                READ_ADDRESS_CONNECTION_RESET_EXCEPTION, READ_ADDRESS_CLOSED_CHANNEL_EXCEPTION);
    }
```
### Netty version
grpc-netty-shaded-1.32.2.jar ,The netty version carried is 4.1.8.final
### JVM version (e.g. `java -version`)
```shell
/opt # java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```
### OS version (e.g. `uname -a`)
Container image  is openjdk:8-jdk-alpine
```shell
/opt # uname -a
Linux store-rpc-84474459ff-46hnd 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 Linux
```

**Comment by hyperxpro** [comment]
This is perfectly normal when the client doesn't close the TCP connection in a proper way.

**Comment by normanmaurer** [comment]
Yes this means that the remote peer did close without a proper TCP shutdown.
