### ISSUE TITLE
Behavior of JDKZlibDecoder depends on segmentation of data

### ISSUE THREAD

**Issue by mrksngl** [netty/netty#10875]
I have a `JDKZlibDecoder(ZlibWrapper.GZIP, true)` in the pipeline, i.e. `decompressConcatenated = true` inside the decoder.

GZIP "objects" are sent back-to-back but data may be split as of TCP segmentation.

### Expected behavior
After one GZIP object is done, a second one should be decoded, no matter how data is fed from previous stages in the pipeline.

### Actual behavior
Works most often as expected, but does not if the GZIP footer is split into two segments.

Then, we have `inflater.finished() = true` and thus `readFooter = true;` but `readGZIPFooter(in) = false`.

When new data arrives, we eventually end up in https://github.com/netty/netty/blob/a9ec3d86f60c193f73079b4c3d0fbafb460c62fb/codec/src/main/java/io/netty/handler/codec/compression/JdkZlibDecoder.java#L207
, leading the decoder to discard any further data.

Note the very different handling of the outcome of `readGZIPFooter` between the line referenced above and line https://github.com/netty/netty/blob/a9ec3d86f60c193f73079b4c3d0fbafb460c62fb/codec/src/main/java/io/netty/handler/codec/compression/JdkZlibDecoder.java#L269

### Steps to reproduce
It's actually a bit tricky to provoke, as data has to be split in the described manner.

### Netty version
4.1.48.Final

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_265"

### OS version (e.g. `uname -a`)
Linux zero 5.9.11-arch2-1 #1 SMP PREEMPT Sat, 28 Nov 2020 02:07:22 +0000 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@mrksngl are you interested in providing a PR with a fix and test case ?

**Comment by mrksngl** [comment]
@normanmaurer 
I'm not very used to netty, so I don't know how to get this artificial segmentation into an automated test case, at least not how to do it elegantly ;)

**Comment by normanmaurer** [comment]
ok... let me have a look.

**Comment by normanmaurer** [comment]
@mrksngl this should be fixed by https://github.com/netty/netty/pull/10948
