### ISSUE TITLE
Same code, different version, FileUpload failed.

### ISSUE THREAD

**Issue by Zhoutzzz** [netty/netty#10885]
### Expected behavior
FileUpload success.
### Actual behavior
In 'netty-all-4.1.52.Final' version,  can't upload 5Mb image when I use this code:
```
    @Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
        this.request = (HttpRequest) msg;

        URI uri = new URI(request.uri());

        System.out.println(uri);

        urlRoute(ctx, uri.getPath());

        if (decoder != null) {
            decoder.offer((HttpContent) msg); // this line throw exception
            readHttpDataChunkByChunk();
            System.out.println("LastHttpContent");
            reset();
            writeResponse(ctx, "<h1>success</h1>");
        }
    }
```

throw a IndexOutOfBoundsException
```
java.lang.IndexOutOfBoundsException: writerIndex(136670) + minWritableBytes(136670) exceeds maxCapacity(136670): UnpooledSlicedByteBuf(ridx: 136670, widx: 136670, cap: 136670/136670, unwrapped: CompositeByteBuf(ridx: 0, widx: 136670, cap: 136670, components=18))
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:295)
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:282)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1104)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1097)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1088)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:340)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:52)
	at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:223)
	at ztz.http.HttpTransportServer.channelRead(HttpTransportServer.java:66)
```

**this question won't happen in 'netty-all 4.1.10.Final'.**
**Maybe this question don't belong netty's bug, I just wanna konw why this happen, and if I only use '4.1.52.Final' version, how can i resolve this exception.If I see the source code use IDEA debug features, where should i start see the code.**

I hope your can solve my confusion, it is greatly appreciated.

### Minimal yet complete reproducer code (or URL to code)
the throw exception's complete file can see: https://github.com/Zhoutzzz/JAVA-000/blob/main/Week_02/http-ftp-server/src/main/java/ztz/http/HttpTransportServer.java
### Netty version
'netty-all 4.1.52.Final'

### JVM version (e.g. `java -version`)
oracleJDK java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)

### OS version (e.g. `uname -a`)
macOS catalina 10.15.7

**Comment by normanmaurer** [comment]
Can you please try 4.1.56.Final ?

**Comment by chenshun00** [comment]
@normanmaurer 
try it , 4.1.52.Final and 4.1.56.Final both fail. but 4.1.25.Final success. 

@Zhoutzzz 
please remove `decoder.offer((HttpContent) msg);` , offer twice lead this error.

**Comment by Zhoutzzz** [comment]
@chenshun00 
tks, i found the next invoke is here:
```
    public HttpPostMultipartRequestDecoder(HttpDataFactory factory, HttpRequest request, Charset charset) {
        this.request = checkNotNull(request, "request");
        this.charset = checkNotNull(charset, "charset");
        this.factory = checkNotNull(factory, "factory");
        // Fill default values

        setMultipart(this.request.headers().get(HttpHeaderNames.CONTENT_TYPE));
        if (request instanceof HttpContent) {
            // Offer automatically if the given request is als type of HttpContent
            // See #1089
            offer((HttpContent) request);
        } else {
            parseBody();
        }
    }
```
This problem has been bothering me for a long time, thank you again for solving my problem and this issus can be close
