### ISSUE TITLE
DatagramPacket.recipient() can not return the actual destination IP with NIO model, but the IP the app is bound to.

### ISSUE THREAD

**Issue by angelyouyou** [netty/netty#10891]
I'm using NIO on an application that is listening on all available interfaces (0.0.0.0). When I try to get the actual UDP packet destination IP, DatagramPacket.recipient() returns 0:0:0:0:0:0:0:0 and not the real packet destination IP. It seems to always return the IP the app is bound to.

Please, let me know if you need some extra information.

OS: Windows10 2020H2
Netty version: 4.1.55.Final

I found this has resolved with [epoll model,](https://github.com/netty/netty/issues/4950) but there is no extra information about nio.

**Comment by normanmaurer** [comment]
It’s not supported by NIO
