### ISSUE TITLE
TLS handshake failed while accessing https://geo.ngtv.io/locate

### ISSUE THREAD

**Issue by chhsiao90** [netty/netty#10898]
### Expected behavior
TLS handshake should succeed, server should send response.

### Actual behavior
TLS handshake failed.

### Steps to reproduce
* Update the url of [HttpSnoopClient](https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http/snoop/HttpSnoopClient.java) to https://geo.ngtv.io/locate
* Run HttpSnoopClient

### Minimal yet complete reproducer code (or URL to code)
See above

### Netty version
4.1.57.Final-SNAPSHOT

### JVM version (e.g. `java -version`)
1.8.0_275

### OS version (e.g. `uname -a`)
Linux LAPTOP-LLKNFMOC 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 GNU/Linux
(I'm using WSL2 with debian)

### Note
I had tried both Jdk SSL engine and openssl engine. There is no output while using Jdk SSL engine, but there is an error `error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER` while using openssl engine.
But I can access the website via browsers, curl, and also the openssl s_client. I guessed netty should have same behavior too.

```
openssl s_client -host geo.ngtv.io -port 443 -tls1_2
openssl s_client -host geo.ngtv.io -port 443 -tls1_3
```

**Comment by hyperxpro** [comment]
Can you dump packets with `PcapWriteHandler`?

**Comment by chhsiao90** [comment]
Thanks for the advise, just dump the packets [dump.pcap.gz](https://github.com/netty/netty/files/5744408/dump.pcap.gz)

**Comment by hyperxpro** [comment]
Checked.

You're sending TLS 1.0 request (SNI is also missing). That could be the reason behind the failure in Handshake. Enable TLSv1.2 and TLSv1.3 in `SslContextBuilder`.

**Comment by chhsiao90** [comment]
I guessed it's caused by that we use TLSv1.0 in the client hello with the extension supported_versions contains TLSv1.2 and TLSv1.3. But the website failed to select the correct TLS version from the extension.

Maybe we should update the TLS version to TLSv1.2 instead of TLSv1 by default.

**Comment by hyperxpro** [comment]
You can override it easily though.

**Comment by chhsiao90** [comment]
It looks like the client hello still sent TLSv1 while I only enable protocols `TLSv1.2` and `TLSv1.3`, it only affects the supported_versions extension.

I will check the root cause. Thanks for your comment! It's helpful.

**Comment by chhsiao90** [comment]
BTW, jdk ssl engine send correct TLS version (TLSv1.2), but still got failure ([dump.pcap.gz](https://github.com/netty/netty/files/5744491/dump.pcap.gz)). So there might be two issues here.

I will also check native openssl too.

**Comment by chhsiao90** [comment]
Root cause found that server requires SNI extension, issue fixed after providing the sni extension in the client hello.
