### ISSUE TITLE
When subpage.elemSize == 8192, the free subpage operation is not work

### ISSUE THREAD

**Issue by ZzxyNn** [netty/netty#10896]
### Actual behavior
allocate N * 8192 subpage, free part of them, but subpage still esixt in two-way linked list 

### Minimal yet complete reproducer code (or URL to code)
```
io.netty.buffer.PoolSubpage#free {
    if (numAvail ++ == 0) { // numAvail always equals 0 when free subpage and elemSize == 8192
        addToPool(head);
        return true;
    }
}
```
### Netty version
4.1.52
### JVM version (e.g. `java -version`)
1.8

**Comment by normanmaurer** [comment]
@ZzxyNn are you interested in providing a PR (with a fix and maybe also a test case) ?

**Comment by ZzxyNn** [comment]
`      int oneLength = 16,twoLength = 256;
        // int elemSize = 4096; // normal
        int elemSize = 8192; // unnormal
        ByteBuf[] ones = new ByteBuf[oneLength];
        ByteBuf[] twos = new ByteBuf[twoLength];
        //allocate
        for (int i = 0; i < oneLength; i++) {
            ones[i] = ByteBufAllocator.DEFAULT.buffer(elemSize, Integer.MAX_VALUE);
        }
        for (int i = 0; i < twoLength; i++) {
            twos[i] = ByteBufAllocator.DEFAULT.buffer(elemSize, Integer.MAX_VALUE);
        }

        //deallocate the 'tows', in oder to filled of PoolThreadCache.MemoryRegionCache.queue
        for (int i = 0; i < twoLength; i++) {
            new WrappedCompositeByteBuf(compositeBuffer().addComponent(twos[i])).deallocate();
        }
        // when deallocate ones, the MemoryRegionCache.queue had been filled, 
        for (int i = 0; i < oneLength; i++) {
            new WrappedCompositeByteBuf(compositeBuffer().addComponent(ones[i])).deallocate();
        }
`
elemSize = 8192:
when the 'twos' start be freed, the size of PoolChunk#subpages will be 256 + 16;

elemSIze = 4196;
the size of PoolChunk#subpages will be 256 + 1;

**Comment by ZzxyNn** [comment]
> @ZzxyNn are you interested in providing a PR (with a fix and maybe also a test case) ?

`      int oneLength = 16,twoLength = 256;
        // int elemSize = 4096; // normal
        int elemSize = 8192; // unnormal
        ByteBuf[] ones = new ByteBuf[oneLength];
        ByteBuf[] twos = new ByteBuf[twoLength];
        //allocate
        for (int i = 0; i < oneLength; i++) {
            ones[i] = ByteBufAllocator.DEFAULT.buffer(elemSize, Integer.MAX_VALUE);
        }
        for (int i = 0; i < twoLength; i++) {
            twos[i] = ByteBufAllocator.DEFAULT.buffer(elemSize, Integer.MAX_VALUE);
        }

        //deallocate the 'tows', in oder to filled of PoolThreadCache.MemoryRegionCache.queue
        for (int i = 0; i < twoLength; i++) {
            new WrappedCompositeByteBuf(compositeBuffer().addComponent(twos[i])).deallocate();
        }
        // when deallocate ones, the MemoryRegionCache.queue had been filled, 
        for (int i = 0; i < oneLength; i++) {
            new WrappedCompositeByteBuf(compositeBuffer().addComponent(ones[i])).deallocate();
        }
`
elemSize = 8192:
when the 'twos' start be freed, the size of PoolChunk#subpages will be 256 + 16;

elemSIze = 4196;
the size of PoolChunk#subpages will be 256 + 1;

**Comment by normanmaurer** [comment]
Please open a PR with a fix if you know how to solve this... We love contributions.

**Comment by ZzxyNn** [comment]
i have no idea yet....but you sure its a problem?
