### ISSUE TITLE
`Socket.isIPv6Preferred()` may return an incorrect value

### ISSUE THREAD

**Issue by trustin** [netty/netty#10909]
### Expected behavior

`io.netty.channel.unix.Socket.isIPv6Preferred()` returns `true` on a Linux system with IPv6 support, even if a user attempted to initialize io_uring support.

### Actual behavior

`false` is returned even on a Linux system with IPv6 support when both `Epoll` and `IOUring` are loaded.

It seems like the secondly loaded library 'reverts' the initialization performed by the firstly loaded library when it's loaded. `Native` class of the both libraries attempt to call `Socket.initialize()`, but the second call will not have any effect because of an initialization check.

We could solve this problem either by:

- resolving the JNI methods of `Socket` dynamically like we do for epoll and io_uring; or
- (perhaps not a good idea) allowing the force re-initialization of `Socket`

### Steps to reproduce

On Linux kernel without io_uring support (5.4.85 in my case),

1. Attempt to load `Epoll`, which succeeds.
2. Check if `Socket.isIPv6Preferred()` returns `true`, which should.
3. Attempt to load `IOUring`, which fails due to a 'failed to allocate a ring buffer' error.
   - Note that the loading of native library has succeeded.
4. `Socket.isIPv6Preferred()` suddenly starts to return `false`.

### Minimal yet complete reproducer code (or URL to code)

```java
Epoll.unavailabilityCause();
assertTrue(Socket.isIPv6Preferred());
IOUring.unavailabilityCause();
assertTrue(Socket.isIPv6Preferred()); // FAIL
```

### Netty version

4.1.54

### JVM version (e.g. `java -version`)

```
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.2+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.2+12, mixed mode, sharing)
```

### OS version (e.g. `uname -a`)

```
Linux ... 5.4.85-1-MANJARO #1 SMP PREEMPT Mon Dec 21 21:38:53 UTC 2020 x86_64 GNU/Linux
```

**Comment by trustin** [comment]
Possible workarounds for this issue at the moment are:

- Do not load both epoll and io_uring transport; or
- Call `Socket.initialize(NetUtil.isIPv4StackPreferred())` reflectively with the `setAccessible(true)` trick.

I'm currently using the second workaround because Armeria currently tries to detect all available native transports upfront.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty-incubator-transport-io_uring/pull/31 and https://github.com/netty/netty/pull/10876

**Comment by trustin** [comment]
Oh, that's awesome :smile:

**Comment by normanmaurer** [comment]
Please open a new issue and a reproducer :)
