### ISSUE TITLE
Flush is not always invoked on non-eventloop thread.

### ISSUE THREAD

**Issue by xxDark** [netty/netty#10907]
### Expected behavior
Outbound buffer is flushed

### Actual behavior
Part of the data in outbound buffer is not flushed

### Steps to reproduce
Invoke `writeAndFlush` on non-eventloop thread.
`ch.writeAndFlush(data).addListener(ChannelFutureListener.CLOSE);`

### Netty version
4.1.56.Final

I don't know if this is intended behaviour or not, but outbound buffer is not flushed due to this check:
https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java#L1068
One of the solutions is of course enforcement of write operation on a event loop, however, I don't see that logic here:
https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java#L788

Thanks.

**Comment by normanmaurer** [comment]
@xxDark do you have a reproducer ? how big is the data and what type is it ?

**Comment by xxDark** [comment]
> 
> 
> @xxDark do you have a reproducer ? how big is the data and what type is it ?

The code I'm talking about is:
https://github.com/SpigotMC/BungeeCord/blob/c987ee199d3ec93ce13469deefb1e2787d97147c/proxy/src/main/java/net/md_5/bungee/netty/ChannelWrapper.java#L83

The packet is: https://github.com/SpigotMC/BungeeCord/blob/master/protocol/src/main/java/net/md_5/bungee/protocol/packet/Kick.java
It is encoded into byte buffer, that is a size of about 200-400 bytes.

**Comment by xxDark** [comment]
I see that default message estimator will count the size of `Kick` packet as 8 bytes, so `8 | Integer.MIN_VALUE` is -2147483640

**Comment by normanmaurer** [comment]
@xxDark which means it should flush, no ? 

https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java#L1071

**Comment by xxDark** [comment]
> 
> 
> @xxDark which means it should flush, no ?
> 
> https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java#L1071

Hm, sorry, my bad.
However, I'm still curious of why that might happen.
Is there any way to diagnostic that?

**Comment by xxDark** [comment]
I suspect that listener gets notified before channel is flushed. Is that may be the case?

**Comment by normanmaurer** [comment]
it could only be notified if the Channel is closed while the write is not complete yet or when the write fails or when the write completes.

**Comment by xxDark** [comment]
Alright then, will diagnostic that on my side. Thanks for assistance.
