### ISSUE TITLE
Change default used ByteBufAllocator to unpooled heap impl

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#1090]
I think we should change the default used ByteBufAllocator to the unpooled heap implementation. Users just expect to have a low memory usage as default. If someone wants to use pooled he can change it easily.

@trustin wdyt ?

**Comment by loolooyyyy** [comment]
I understand the primary focus of Netty developers is large-scale applications, yet Netty provides a very elegant architecture even for small-scaled projects. I do not see why I should not use it on a raspberry pi, serving only 20 clients (they are other embedded devices controlled by a central raspberry).

I think it's worth noting on newbies user guide http://netty.io/wiki/user-guide-for-4.x.html about pooled buffers being memory hungry, before they find it the hard way!

**Comment by doom369** [comment]
> I do not see why I should not use it on a raspberry pi, serving only 20 clients (they are other embedded devices controlled by a central raspberry).

And you can right now despite on `ByteBufAllocator` type. My raspberry handles ~200 req/sec without problems on Netty and memory not a problem at all.
