### ISSUE TITLE
Please update Bouncy Castle

### ISSUE THREAD

**Issue by Neustradamus** [netty/netty#10905]
Please update Bouncy Castle
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by Neustradamus** [comment]
@hyperxpro: Thanks :)

**Comment by Neustradamus** [comment]
@hyperxpro, @normanmaurer: Thanks :)

**Comment by Neustradamus** [comment]
@hyperxpro, @normanmaurer: Can you update to 1.69?

**Comment by hyperxpro** [comment]
Sure, will do PR.

**Comment by hyperxpro** [comment]
@Neustradamus PTAL #11495
