### ISSUE TITLE
Suitable JDK for netty version 4.1.50.Final and above

### ISSUE THREAD

**Issue by nightfurytoothlesss** [netty/netty#10903]
### Explanation

I am working on a maven project which uses netty version  4.1.50.Final and I am encountering some PORT unavailability errors related to http2, which I am guessing is due to the JDK I am using. I used openjdk8 on ubuntu: bionic 64 bit x86 machine. Probably it lacks netty http2 libraries. 
~~~
[ERROR]   BasicGrpcTestCase.start:61->BaseTestCase.init:175->BaseTestCase.init:131->BaseTestCase.initHttpServer:47 Port: 9443 already in use. expected [false] but found [true]
~~~
Can you please suggest some jdk8 that can work successfully with netty 4.1.50.Final and above, and contains netty http2 libraries...?  And most importantly, does netty work with openjdk8?
And the problem with oracle JDK is that we can't install it now via apt-get directly. Oracle JDK is now paid.

### Expected behavior
NA

### Actual behavior
NA

### Steps to reproduce
NA

### Minimal yet complete reproducer code (or URL to code)
NA

### Netty version
4.1.50.Final and above

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~18.04-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)

### OS version (e.g. `uname -a`)
x86_64 ubuntu: bionic

**Comment by hyperxpro** [comment]
You're trying to bind on a port that is already being used by some other service/program. So this is expected and normal.

Netty works perfectly with Java 8. I am using Netty in production with Java 15 and it works like charm. You can use Amazon Corretto JDK if you're not willing to pay for Oracle JDK.

**Comment by nightfurytoothlesss** [comment]
@hyperxpro 
Thank you for the response. Actually, my package was using an older netty version, and only after updating the netty version to 4.1.50.Final, that I am getting this issue. 
Just curious to know that do latest netty versions use PORT 9443 ??

**Comment by hyperxpro** [comment]
Netty does not use any port by itself unless you configure it.

**Comment by hyperxpro** [comment]
You should check which program/service is using 9443 Port and close it in order to use 9443 in Netty,
