### ISSUE TITLE
Wrong the comment for the remove method on FastThreadLocal class.

### ISSUE THREAD

**Issue by andrewvo148** [netty/netty#10914]
https://github.com/netty/netty/blob/0dc246eb129796313b58c1dbdd674aa289f72cad/common/src/main/java/io/netty/util/concurrent/FastThreadLocal.java#L234

**Comment by chrisvest** [comment]
What's wrong about it?

**Comment by andrewvo148** [comment]
`    /**
     * Sets the value to uninitialized; a proceeding call to get() will trigger a call to initialValue().
     */
    public final void remove() {
        remove(InternalThreadLocalMap.getIfSet());
    }`

The remove() method call to getIfSet() not call to get().

**Comment by chrisvest** [comment]
What it's meant to say is that after you've called `remove()`, if you then call `get()`, you'll get a new `initialValue()` out.

**Comment by andrewvo148** [comment]
@chrisvest,
I got it. I think to more meant should change the word `proceeding` by other words.
