### ISSUE TITLE
"Shut down by issue" executors are not cleaned up, is this some kind of a missing feature?

### ISSUE THREAD

**Issue by ujhazib** [netty/netty#10918]
I have been debugging a fairly rare issue in our production system which is based on spring boot reactor and uses amongst others, Lettuce and Netty. Sometimes we see that we start to get a fairly small rate, but stable error rate increases on certain Lettuce calls.

Where I got my investigation is the following: Some usual error comes on a Mono and a rather unusual situation happens because as it seems, that the next handling might have been already called on that. So [MonoNext draws an onErrorDropped](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/MonoNext.java#L89) because it sees a 'done' has already happened. This will roll up to [SingleThreadEventExecutor](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java#L992) only to shut down that executor for sure. However, it turns out, that by design MultithreadEventExecutorGroup is not capable of handling this situation gracefully in the wider picture. It is only able to shut down the bunch of executors and let them go and that seems to be the only shutdown handling scenario there, which might have been designed for a graceful server shutdown or when you just simply remove your executor group. In case of Lettuce, DefaultEventExectorGroup is used [(here)](https://github.com/lettuce-io/lettuce-core/blob/main/src/main/java/io/lettuce/core/resource/DefaultEventLoopGroupProvider.java#L218). So what is the consequence is that the group still has this item and all usages of that executor becomes "rejected", adding a stable failure rate into a running Netty server instance. I've been thinking for a while, which part is the issue here and didn't able to decide if Lettuce should use a different event executor group or reinitialize this or what, but came on the conclusion, that running instances should not be harmed, so maybe this or a yet-to-be-existing executor group should rather heal itself. Overall this is seen just as a "harmless" timeout if the redis was somekinda cache, but the logs showed rejection on executors.

While I'm sure we still need to trace down why happens sometimes this 'done' collision, I strongly belive, that a better executor pool handling is needed here. There are numerous reasons this could happen later on with other bugs, plus the whole code seem to "support" that an executor can go into a shutdown without shutting down the server itself. Question is, how can any client user of these codes make sure that the executor group is able to clean up failing executors of such reason and replacing them with new ones?

### Expected behavior
When an executor fails in a group, the group should heal itself by removing failed and shut down executors and replacing them with new ones.

### Actual behavior
An executor which was shut down by an error and not by server shutdown remains in the executor group and it causes a stable failure rate in server calls

### Steps to reproduce
Breakpoints were set into [RedisPublisher.OnComplete.run](https://github.com/lettuce-io/lettuce-core/blob/5.3.x/src/main/java/io/lettuce/core/RedisPublisher.java#L1093) and [MonoNext.onError](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/MonoNext.java#L88)
An artifhttps://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/MonoNext.java#L88
Because the issue was rare, I needed to artifically create the situation that happened by overriding values. First of all, in the RedisPublisher.OnComplete, I set 'signal' to an exception only to go into MonoNext's onError handler after a while. At that point, what is the fishy story is that this.done was already true. I set that values as well to true with the debugger and in this way, the exception will roll out to that particulare shutdown code.

### Minimal yet complete reproducer code (or URL to code)
https://github.com/martin-tarjanyi/lettuce-executor-reject-repro

### Netty version
4.1.51

### JVM version (e.g. `java -version`)
OpenJDK Runtime Environment Corretto-8.222.10.3 (build 1.8.0_222-b10)

### OS version (e.g. `uname -a`)
Windows 10

**Comment by ujhazib** [comment]
It came to my knowledge, that this certain onErrorDropped induced exception though is fixed from a certain reactor version:
https://github.com/reactor/reactor-core/releases/tag/v3.4.0?fbclid=IwAR0t73ArcwxX3MpIDlhB4Q-rXpd0ROHRo7VGhrHo37izBSmP82WzoeCyavg

**Comment by ujhazib** [comment]
Very nice of y'all that you don't even consider checking this, I mean I don't care anymore, but there should have been an answer at least.

**Comment by franz1981** [comment]
I suggest to open this up to the reactor core team or who is responsible to use Netty as a library. I don't see yet (we need a full Netty only reproducer) to consider this problem as something which Netty has to solve 🙏

**Comment by franz1981** [comment]
If you don't care it anymore @ujhazib please close it 🙏
