### ISSUE TITLE
Netty SSL issue

### ISSUE THREAD

**Issue by hnuwangchao** [netty/netty#10921]

**Comment by normanmaurer** [comment]
This netty version is very old... please upgrade to the latest and provide more details

**Comment by hnuwangchao** [comment]
> This netty version is very old... please upgrade to the latest and provide more details

Frist, Thanks for your reply:
As your suggestion, I have upgraded the Netty Version to 4.1.56, Unfortunately, I still encounter the same error; 　Specifically, I use Netty as the client to upload data to the server, and I use packet capture analysis software(Wireshark) to find that the client did not send the client's certificate to the server, resulting in the disconnection of TSL connection. I am quite sure that my certificate is OK.

My code is as follows:

`public class NettyClient {

    public static final String TAG = "NettyClient";
    public void SslInit()
    {
        try {
            connet("192.168.48.51",8020);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void connet(String host, int port) throws Exception
    {
        File certChainFile = new File(ClientSslContextFactory.certChainFile);
        File privateKey = new File(ClientSslContextFactory.keyFile);
        File rootCA = new File(ClientSslContextFactory.serverFile);
        ClientSslContextFactory clientSslContextFactory = new ClientSslContextFactory();
        SslContext sslContext = SslContextBuilder.forClient()
                .keyManager(certChainFile,privateKey).trustManager(InsecureTrustManagerFactory.INSTANCE).build();


        EventLoopGroup workerGroup = new NioEventLoopGroup();
        try {
            Bootstrap bootstrap = new Bootstrap();
            bootstrap.group(workerGroup);
            bootstrap.channel(NioSocketChannel.class);
            bootstrap.handler(new MyChannleInitializer(sslContext));

            Channel channel = bootstrap.connect(host, port).sync().channel();

            // Read commands from the stdin.
            ChannelFuture lastWriteFuture = null;
            BufferedReader in = new BufferedReader(new InputStreamReader(new FileInputStream(certChainFile)));
            for (;;) {
                String line = in.readLine();
                if (line == null) {
                    break;
                }

                // Sends the received line to the server.
                lastWriteFuture = channel.writeAndFlush(line + "\r\n");

                // If user typed the 'bye' command, wait until the server closes
                // the connection.
                if ("bye".equals(line.toLowerCase())) {
                    channel.closeFuture().sync();
                    break;
                }
            }

            // Wait until all messages are flushed before closing the channel.
            if (lastWriteFuture != null) {
                lastWriteFuture.sync();
            }
        }

        catch (InterruptedException e)
        {
            e.printStackTrace();
        }
        finally {
            workerGroup.shutdownGracefully();
        }
    }
}


public class MyChannleInitializer extends ChannelInitializer<SocketChannel> {


    private SslContext sslContext;

    public MyChannleInitializer(SslContext sslContext)
    {
        this.sslContext = sslContext;
    }
    @Override
    protected void initChannel(SocketChannel ch) throws Exception {
        ch.pipeline().addLast(sslContext.newHandler(ch.alloc()));
        ch.pipeline().addLast(new LineBasedFrameDecoder(1024));
        ch.pipeline().addLast(new StringEncoder(Charset.forName("GBK")));
        ch.pipeline().addLast(new StringDecoder(Charset.forName("GBK")));
    }
}


`

I want to ask whether Netty supports mutually authentication now? If you can, please advise.

**Comment by hyperxpro** [comment]
`ch.pipeline().addLast(sslContext.newHandler(ch.alloc()));` > Add host and port for SNI extension and try again.

**Comment by hnuwangchao** [comment]
> `ch.pipeline().addLast(sslContext.newHandler(ch.alloc()));` > Add host and port for SNI extension and try again.
Thanks for your reply, however, it still also cannot work well. By using the packet capture analysis software(Wireshark), I can find the handshake process, the problem is that the sever send the certificates request, but the Netty client do not send the  certificates to server(the length of  certificates= 0, in the Wireshark).

**Comment by hyperxpro** [comment]
Is the server requesting Mutual TLS?

**Comment by normanmaurer** [comment]
Like @hyperxpro said.. I suspect the server does not request mutual TLS... We have various tests for mTLS and all pass. Let me close this one for now.
