### ISSUE TITLE
NoSuchMethodError : `Exception in thread "_(:3」∠)_" java.lang.NoSuchMethodError: io.netty.channel.SingleThreadEventLoop.<init>(Lio/netty/channel/EventLoopGroup;Ljava/util/concurrent/Executor;ZLjava/util/Queue;Ljava/util/Queue;Lio/netty/util/concurrent/RejectedExecutionHandler;)V`

### ISSUE THREAD

**Issue by Patrick5455** [netty/netty#10924]
### Expected behavior
I am using the blade-frameowrk  [https://github.com/lets-blade/blade](url) which uses netty at its core. When I run blade, it is exepcted to start without throwing errors,

### Actual behavior
When I start the application, I get this error from netty and I have spent the past 3 days trying to debug the issue now.
Here is an image of the error I get when I try to debug the problem
![netty+error](https://user-images.githubusercontent.com/46347439/104322971-dc961780-54e5-11eb-9e88-7afcbd07a143.png)

### Steps to reproduce
Run the code below after adding blad to the POM file... this is the blad main application
### Minimal yet complete reproducer code (or URL to code)
public class Service {

    private static final Logger log = LoggerFactory.getLogger(Service.class);

    public static void main(String[] args) {

        Blade.of().gzip(true)
                .enableCors(Boolean.TRUE, getCorsConfiger())
                //.use(new Security())
                .start(Service.class, args);
    }

    public static CorsConfiger getCorsConfiger() {
        return CorsConfiger.builder()
                .allowedMethods(Stream.of("GET", "OPTIONS", "HEAD", "PUT", "POST", "DELETE").collect(Collectors.toList()))
                .allowedHeaders(Stream
                        .of("Origin", "X-Requested-With", "Content-Type", "Accept", "Connection", "User-Agent", "Cookie",
                                "Cache-Control").collect(
                                Collectors.toList()))
                .maxAge(1300L)
                .allowCredentials(Boolean.TRUE)
                .build();
    }
}

### Netty version
netty-all:4.1.49.Final
### JVM version (e.g. `java -version`)
Java 8

### OS version (e.g. `uname -a`)
Ubuntu

**Comment by normanmaurer** [comment]
This looks like you have multiple netty-* versions on the classpath. Ensure you only have one.

**Comment by Patrick5455** [comment]
> This looks like you have multiple netty-* versions on the classpath. Ensure you only have one.

Thanks @normanmaurer 
these are my nety versons 
![Uploading netty_versions.png…]()

**Comment by normanmaurer** [comment]
remove all versions which are not 4.1.49. You may need to add some exclusions to your pom.xml. That said this is not a netty problem but related how you configure your build.

**Comment by Patrick5455** [comment]
Alright thanks.
