### ISSUE TITLE
Why method void processSelectedKey(SelectionKey k, NioTask<SelectableChannel> task) in NioEventLoop be static?

### ISSUE THREAD

**Issue by Gene1994** [netty/netty#10949]
in NioEventLoop.java
line 673 private void processSelectedKey(SelectionKey k, AbstractNioChannel ch)
line 726 private static void processSelectedKey(SelectionKey k, NioTask<SelectableChannel> task)
why the below method be static?

### Netty version
4.1
### JVM version (e.g. `java -version`)
1.8

**Comment by chrisvest** [comment]
The second one does not need access to the event loop object or its state, but the first one does.

**Comment by Gene1994** [comment]
@chrisvest I know why first method is non-static. but idk why the second method is static? beacuse it is used frequently?

**Comment by slandelle** [comment]
Because it doesn’t depend on any instance state. More of a convention / coding style.

**Comment by Gene1994** [comment]
> Because it doesn’t depend on any instance state. More of a convention / coding style.

ok. thank you.
