### ISSUE TITLE
Multiple files have hardcoded passwords, encryption keys. Software is relatively easy to reverse engineer, so attackers could gain access to those secrets. - reported by MobSF

### ISSUE THREAD

**Issue by kaiseiyouse** [netty/netty#10950]
### Expected behavior
MobSF should not report this issue.

### Actual behavior
io.netty.handler.ssl.OpenSsl

Multiple files have hardcoded passwords, encryption keys. Software is relatively easy to reverse engineer, so attackers could gain access to those secrets. - reported by MobSF
![image](https://user-images.githubusercontent.com/9845747/104992553-440b1480-5a5c-11eb-9abe-d43b454982f9.png)

### Steps to reproduce
Include Netty library in any android project & Scan the apk with MobSF

### Netty version
4.1.48.Final
### JVM version (e.g. `java -version`)
8.0
### OS version (e.g. `uname -a`)
android 8.0

**Comment by kaiseiyouse** [comment]
@slandelle can you help explain, thx

**Comment by normanmaurer** [comment]
@kaiseiyouse these are only used to probe for some functionality and so will never be used in the "running" program. So these are "false positives"

**Comment by kaiseiyouse** [comment]
> @kaiseiyouse these are only used to probe for some functionality and so will never be used in the "running" program. So these are "false positives"

thanks normanmaurer!

**Comment by SandyPeng1990** [comment]
> ### Expected behavior
> MobSF should not report this issue.
> 
> ### Actual behavior
> io.netty.handler.ssl.OpenSsl
> 
> Multiple files have hardcoded passwords, encryption keys. Software is relatively easy to reverse engineer, so attackers could gain access to those secrets. - reported by MobSF
> ![image](https://user-images.githubusercontent.com/9845747/104992553-440b1480-5a5c-11eb-9abe-d43b454982f9.png)
> 
> ### Steps to reproduce
> Include Netty library in any android project & Scan the apk with MobSF
> 
> ### Minimal yet complete reproducer code (or URL to code)
> ### Netty version
> 4.1.48.Final
> 
> ### JVM version (e.g. `java -version`)
> 8.0
> 
> ### OS version (e.g. `uname -a`)
> android 8.0

You previously replied that these are only used to probe for some functionality and so will never be used in the "running" program, if we modify and delete  the encryption keys and  selfSignedCertificate related codes in OpenSsl.java, will there be any problems? Do we need to force the modified code to be uploaded and released?
