### ISSUE TITLE
How to report a security related issue

### ISSUE THREAD

**Issue by ZeddYu** [netty/netty#10959]
Hi. I found a security related issue. And I also read the security policy.
> If you think the bug you found is likely to make Netty-based applications vulnerable to an attack,
please do not use our public issue tracker
but report it to [the dedicated private Google Group](https://groups.google.com/d/forum/netty-security).

But I can't access the dedicated private Google Group. How can I report?

**Comment by normanmaurer** [comment]
Send an email there ... we will reply

**Comment by ZeddYu** [comment]
New to using google group. Thank you.
