### ISSUE TITLE
App creates temp file. Sensitive information should never be written into a temp file. - reported by MobSF

### ISSUE THREAD

**Issue by kaiseiyouse** [netty/netty#10963]
### Expected behavior
MobSF should not report this issue.

### Actual behavior
![image](https://user-images.githubusercontent.com/9845747/105805003-0c601780-5fdc-11eb-896e-56deed6e7b2e.png)

It appears that a .dynlib or .jnilib file is being written out to temporary storage. Please confirm whether or not the library file may contain sensitive information.  - reported by MobSF

### Steps to reproduce
Include Netty library in any android project & Scan the apk with MobSF

### Netty version
4.1.48.Final

### JVM version (e.g. `java -version`)
8.0

### OS version (e.g. `uname -a`)
android 8.0

**Comment by chrisvest** [comment]
That's native code we use for interfacing with openssl and the like. No sensitive info in there.
