### ISSUE TITLE
Make SslContextBuilder more "extensible"

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#10978]
At the moment we have a few things on various `SslContext` implementations that can only be configured by "casting". I think it would be better to introduce something like `ChannelOption` but for `SslContext` and so allow easier configuration and also changing things without breaking others.

So I think we should introduce `SslContextOption` which follows the pattern of `ChannelOption` and add something like:

`
SslContextBuilder.option(SslContextOption, value);
`

**Comment by normanmaurer** [comment]
Something like would also allow us to make it easier to setup key logging etc when using BoringSSL and so on.

**Comment by chrisvest** [comment]
I can get behind consistent, smaller and more flexible API surfaces.
