### ISSUE TITLE
Any updates and plans about netty5?

### ISSUE THREAD

**Issue by thinkerou** [netty/netty#10975]
as title, thanks!

**Comment by hyperxpro** [comment]
It's still in development but there is no release date yet.

**Comment by xiaoheng1** [comment]
By the way, is there any plan to release netty5? I used to see that netty5 was abandoned.

**Comment by LifeIsStrange** [comment]
I hope it will support io_uring by default :)

**Comment by normanmaurer** [comment]
Its still ongoing... no concrete plans for a release yet
