### ISSUE TITLE
PemReader

### ISSUE THREAD

**Issue by violetgo** [netty/netty#10974]
### Expected behavior
     
hi , I have a few confuse. it seem PemRead.java have not close InputStream at `readPrivateKey` and `readContent method` ?
https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/PemReader.java

why neety don't close it ?
Are they not make open file leak?

 if i use SslContextBuilder for build ssl `SslContextBuilder forServer(InputStream keyCertChainInputStream, InputStream keyInputStream) `
the method call stack seems are not close InputStream yet ?
it is mean I need close it by myself?

### Actual behavior

it seems i got file open leak?
    
![image](https://user-images.githubusercontent.com/5086059/106243242-fbb1da80-6243-11eb-97f4-16fd761f03f8.png)

![image](https://user-images.githubusercontent.com/5086059/106243320-24d26b00-6244-11eb-981e-251abe88610d.png)

### Steps to reproduce
N/A

### Minimal yet complete reproducer code (or URL to code)
N/A

### Netty version
netty-all-4.1.25.Final.jar

### JVM version (e.g. `java -version`)
java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)

### OS version (e.g. `uname -a`)
uname -a
Linux ip-10-0-4-111.ec2.internal 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
Yes at the moment we expect you to call close... That said I can't think of a good reason why we shouldn't call close here one we consumed the stream. I will open a PR to change this

**Comment by normanmaurer** [comment]
Should be fixed by https://github.com/netty/netty/pull/10976

**Comment by normanmaurer** [comment]
Clarified javadocs in https://github.com/netty/netty/pull/10983

**Comment by violetgo** [comment]
> Clarified javadocs in #10983

/lgtm  
and I found this bug by use dubbo , and I will report this bug to dubbo too, thanks~
