### ISSUE TITLE
A lot of unflushed io.netty.channel.ChannelOutboundBuffer$Entry

### ISSUE THREAD

**Issue by glcanvas** [netty/netty#10985]
#### Expected behavior
netty stop execution if allocated a lot of unprocessed entries. 

####Actual behavior
I use java stream with resteasy and netty for sending a huge file from a server.
Today my file is about 30gb, and netty creates a lot of ChannelOutboundBuffer$Entry items
![image](https://user-images.githubusercontent.com/22433265/106588015-5bb5c300-655b-11eb-9857-41358d2a8159.png)

As I noticed a lot of Entries already storages in netty, but not written to socket yet
![image](https://user-images.githubusercontent.com/22433265/106588173-899b0780-655b-11eb-917f-8eef30c81684.png)

So, is it expected way? 
Maybe exists some way to restrict such behavior? For example, stop execution until flushed entries won't be written

####Netty version
4.1.19.Final

####JVM version (e.g. java -version)
openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment Corretto-11.0.6.10.1 (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.6.10.1 (build 11.0.6+10-LTS, mixed mode)

####OS version (e.g. uname -a)
Linux serv_1 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
It is expected... It is up to the user of netty to stop writing if things can not be written fast enough. So this would need to be reported to resteasy I guess
