### ISSUE TITLE
Run netty4.1.58 test case error

### ISSUE THREAD

**Issue by xiaoheng1** [netty/netty#10992]
### Actual behavior

Run netty4.1.58 test case error

### Steps to reproduce

```
@Test
public void test02(){
        PooledByteBufAllocator allocator = newAllocator(true);
        ByteBuf byteBuf = allocator.ioBuffer(128);
        System.out.println(byteBuf);
    }
```

run test02 case，report the following error

```
Unrecognized option: --illegal-access=deny
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

### Netty version

4.1.58.final

### JVM version (e.g. `java -version`)

1.8

### OS version (e.g. `uname -a`)

macos

**Comment by hyperxpro** [comment]
This is not a Netty bug. Check your runtime configuration.

**Comment by xiaoheng1** [comment]
thanks, i will check it.

**Comment by j-tooyoung** [comment]
@xiaoheng1 how do you solve this problem. where idea need to configure

**Comment by j-tooyoung** [comment]
@xiaoheng1 i also meet the same problem. how do you solve it.

**Comment by xiaoheng1** [comment]
You can search illegal-access=deny in pom.xml and comment this out and try

**Comment by chrisvest** [comment]
Commenting it out should not be necessary. Sounds like a Java 9 (or greater) profile is somehow enabled. Could be Maven is running with a mix of Java versions, e.g. `java` command invoking one version and `JAVA_HOME` pointing to another version. Or something else is wrong with the environment. So that's what people need to investigate if they run into this issue.

**Comment by newstarjones** [comment]
> Commenting it out should not be necessary. Sounds like a Java 9 (or greater) profile is somehow enabled. Could be Maven is running with a mix of Java versions, e.g. `java` command invoking one version and `JAVA_HOME` pointing to another version. Or something else is wrong with the environment. So that's what people need to investigate if they run into this issue.

it’s ok when i uncheck the java11 profile.
![image](https://user-images.githubusercontent.com/3959734/126428716-f1262f8c-e6c6-4f34-904d-5bf15cf734d7.png)

**Comment by Phukety** [comment]
> > Commenting it out should not be necessary. Sounds like a Java 9 (or greater) profile is somehow enabled. Could be Maven is running with a mix of Java versions, e.g. `java` command invoking one version and `JAVA_HOME` pointing to another version. Or something else is wrong with the environment. So that's what people need to investigate if they run into this issue.
> 
> it’s ok when i uncheck the java11 profile. ![image](https://user-images.githubusercontent.com/3959734/126428716-f1262f8c-e6c6-4f34-904d-5bf15cf734d7.png)

Thank you. I solved it

**Comment by Sicilianz** [comment]
> I solved it

**Comment by Sicilianz** [comment]
> > > Commenting it out should not be necessary. Sounds like a Java 9 (or greater) profile is somehow enabled. Could be Maven is running with a mix of Java versions, e.g. `java` command invoking one version and `JAVA_HOME` pointing to another version. Or something else is wrong with the environment. So that's what people need to investigate if they run into this issue.
> > 
> > 
> > it’s ok when i uncheck the java11 profile. ![image](https://user-images.githubusercontent.com/3959734/126428716-f1262f8c-e6c6-4f34-904d-5bf15cf734d7.png)
> 
> Thank you. I solved it

Thank you , I solved it too.

This problem may happen when there are 2 versions of jdk, comment out the profile about jkd11 in pom.xml then it is solved.
