### ISSUE TITLE
Netty - GH Discussions

### ISSUE THREAD

**Issue by tomasherman** [netty/netty#10996]
Hello,

i was wondering if it would make sense to enable GH discussions for netty. I'm trying to ask questions via stackoverflow but it's kinda difficult sometimes when it comes to follow ups on questions.

Thanks and thanks for all the great work!

**Comment by hyperxpro** [comment]
GitHub Discussions is a great idea. @normanmaurer WDYT?

**Comment by kashike** [comment]
@normanmaurer What do you think about this? I've had a few questions I want to ask before working on some things, and the IRC channel is dead (and Slack (#5493) never took off).

GitHub Discussions seems like a good choice to me, since we can easily reference issues and pull requests.
