### ISSUE TITLE
[question] native transport for Windows?

### ISSUE THREAD

**Issue by TheDGOfficial** [netty/netty#10998]
I tried to search for it in issues but didn't found one. I know this the place for actual bugs/issues in Netty code, but can't find any other way to ask this. Are there plans to make native transport also available to Windows and Windows Server? It only supports Linux and macOS currently. (https://github.com/netty/netty/wiki/Native-transports)

**Comment by normanmaurer** [comment]
No plans at all. For windows just use the normal nio transport
