### ISSUE TITLE
android studio  uses versions after 4.1.26.Final to report errors

### ISSUE THREAD

**Issue by DavidAwing** [netty/netty#11005]
### Expected behavior
use netty-4.1.58.Final develop android  app 
### Actual behavior

log:

2021-02-08 18:10:09.647 10160-10246/com.wing.tvadmin I/om.wing.tvadmi: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.logging.log4j.spi.ExtendedLoggerWrapper" on path: DexPathList[[zip file "/data/app/com.wing.tvadmin-0m32SN1k7oCrKmWGnftx9Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.wing.tvadmin-0m32SN1k7oCrKmWGnftx9Q==/lib/arm64, /system/lib64, /product/lib64]]
2021-02-08 18:10:09.647 10160-10246/com.wing.tvadmin I/om.wing.tvadmi:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
2021-02-08 18:10:09.647 10160-10246/com.wing.tvadmin I/om.wing.tvadmi:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
2021-02-08 18:10:09.647 10160-10246/com.wing.tvadmin I/om.wing.tvadmi:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2021-02-08 18:10:09.647 10160-10246/com.wing.tvadmin I/om.wing.tvadmi:     at io.netty.util.internal.logging.InternalLoggerFactory io.netty.util.internal.logging.InternalLoggerFactory.useLog4J2LoggerFactory(java.lang.String) (InternalLoggerFactory.java:75)
2021-02-08 18:10:09.647 10160-10246/com.wing.tvadmin I/om.wing.tvadmi:     at io.netty.util.internal.logging.InternalLoggerFactory io.netty.util.internal.logging.InternalLoggerFactory.newDefaultFactory(java.lang.String) (InternalLoggerFactory.java:47)
2021-02-08 18:10:09.647 10160-10246/com.wing.tvadmin I/om.wing.tvadmi:     at io.netty.util.internal.logging.InternalLoggerFactory io.netty.util.internal.logging.InternalLoggerFactory.getDefaultFactory() (InternalLoggerFactory.java:111)
2021-02-08 18:10:09.647 10160-10246/com.wing.tvadmin I/om.wing.tvadmi:     at io.netty.util.internal.logging.InternalLogger io.netty.util.internal.logging.InternalLoggerFactory.getInstance(java.lang.String) (InternalLoggerFactory.java:134)
2021-02-08 18:10:09.647 10160-10246/com.wing.tvadmin I/om.wing.tvadmi:     at io.netty.util.internal.logging.InternalLogger io.netty.util.internal.logging.InternalLoggerFactory.getInstance(java.lang.Class) (InternalLoggerFactory.java:127)
2021-02-08 18:10:09.647 10160-10246/com.wing.tvadmin I/om.wing.tvadmi:     at void io.netty.channel.MultithreadEventLoopGroup.<clinit>() (MultithreadEventLoopGroup.java:35)
2021-02-08 18:10:09.647 10160-10246/com.wing.tvadmin I/om.wing.tvadmi:     at void com.wing.service.netty.AndroidHttpServer.start() (AndroidHttpServer.java:42)
2021-02-08 18:10:09.647 10160-10246/com.wing.tvadmin I/om.wing.tvadmi:     at void com.wing.service.netty.AndroidHttpServer.main(java.lang.String[]) (AndroidHttpServer.java:34)
2021-02-08 18:10:09.647 10160-10246/com.wing.tvadmin I/om.wing.tvadmi:     at void com.wing.tvadmin.MainActivity$3.run() (MainActivity.java:58)
2021-02-08 18:10:09.647 10160-10246/com.wing.tvadmin I/om.wing.tvadmi:     at void java.lang.Thread.run() (Thread.java:784)

### Steps to reproduce

1. new  android studio project
MainActivity,java   add code:

        new Thread(() -> {
            try {
                AndroidHttpServer.main(null);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();

2. run the app , look loacat window

### Minimal yet complete reproducer code (or URL to code)

AndroidHttpServer.java
 
import io.netty.bootstrap.ServerBootstrap;
import io.netty.channel.ChannelFuture;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.ChannelPipeline;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.handler.codec.http.*;
import java.net.InetSocketAddress;

public class AndroidHttpServer {
    private final int port;

    public AndroidHttpServer(int port) {
        this.port = port;
    }

    public static void main(String[] args) throws Exception {

        int port = Integer.parseInt("12319");
        new AndroidHttpServer(port).start();
    }
    

    public void start() throws Exception {

        final AndroidHttpServerHandler androidHttpServerHandler = new AndroidHttpServerHandler();

        EventLoopGroup group = new NioEventLoopGroup();
        try {
            ServerBootstrap b = new ServerBootstrap();
            b.group(group)
                    .channel(NioServerSocketChannel.class)
                    .localAddress(new InetSocketAddress(port))
                    .childHandler(new ChannelInitializer<SocketChannel>() {
                        public void initChannel(SocketChannel channel) throws Exception {

                            ChannelPipeline pipeline = channel.pipeline();
                            pipeline.addLast(new HttpResponseEncoder());
                            pipeline.addLast(new HttpRequestDecoder());
                            pipeline.addLast(new HttpObjectAggregator(1024*1024*10));
                            pipeline.addLast(androidHttpServerHandler);
                        }
                    }); 
            ChannelFuture f = b.bind().sync();
            System.out.println(AndroidHttpServer.class.getName() + " started and listening for connections on " + f.channel().localAddress()); 
            f.channel().closeFuture().sync();
        } finally { 
            group.shutdownGracefully().sync();
        }
    }
}
 

AndroidHttpServerHandler.java
 

import android.os.Environment;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.Unpooled;
import io.netty.channel.ChannelFutureListener;
import io.netty.channel.ChannelHandler.Sharable;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelInboundHandlerAdapter;
import io.netty.handler.codec.http.*;
import io.netty.util.CharsetUtil;
import java.io.*;
import java.net.URLDecoder;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
 
@Sharable
public class AndroidHttpServerHandler extends ChannelInboundHandlerAdapter {

    private static final String CRLF = "\r\n";
    private static final String BLANK = " ";

    public void channelRead(ChannelHandlerContext ctx, Object msg) {
 
        if (msg instanceof FullHttpRequest) {

            FullHttpRequest req = (FullHttpRequest) msg;
            try {
                String uri = null;
                try {
                    uri = URLDecoder.decode(req.uri(), "utf-8");
                } catch (UnsupportedEncodingException e) {
                    e.printStackTrace();
                }
                ByteBuf buf = req.content();
                String content = buf.toString(CharsetUtil.UTF_8);
                HttpMethod method = req.method();
                HttpHeaders headers = req.headers();
                if (method.equals(HttpMethod.GET)) {
                    responseStream(ctx, uri);
                }
                if (method.equals(HttpMethod.POST)) {
                    responseText(ctx, uri);
                }

            } finally {
                req.release();
            }
        }
    }

    private void responseText(ChannelHandlerContext ctx, String c) {

        FullHttpResponse resp = new DefaultFullHttpResponse(HttpVersion.HTTP_1_1,
                HttpResponseStatus.OK,
                Unpooled.copiedBuffer(c, CharsetUtil.UTF_8));
        resp.headers().set(HttpHeaderNames.CONTENT_TYPE, "text/html; charset=UTF-8");
        ctx.writeAndFlush(resp).addListener(ChannelFutureListener.CLOSE);
    }

    public static String getRootDirectory() {
        String rootDirectory = "/storage/emulated/0/";
        if (!new File(rootDirectory).exists()) {
            rootDirectory = Environment.getExternalStorageDirectory().getAbsolutePath() + File.separator + "EMACRO" + File.separator;
        }
        return rootDirectory;
    }

    private void responseStream(ChannelHandlerContext ctx, String url) {

        if (url.equals("/image")) {
 
            File file = new File(getRootDirectory() + "image.jpg");
            ByteBuf respByte = Unpooled.buffer((int) file.length());

            try { 
                FileInputStream fis = new FileInputStream(file); 
                FileChannel channel = fis.getChannel(); 
                ByteBuffer allocate = ByteBuffer.allocate((int) file.length()); 
                try {
                    channel.read(allocate);
                } catch (IOException e) {
                    e.printStackTrace();
                }
                respByte.writeBytes(allocate.array());
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            }
  
            FullHttpResponse resp = new DefaultFullHttpResponse(HttpVersion.HTTP_1_1,
                    HttpResponseStatus.OK,
                    respByte
            );
 
            resp.headers().set(HttpHeaderNames.ACCEPT_RANGES, "bytes");
            resp.headers().set(HttpHeaderNames.CACHE_CONTROL, "no-cache, no-store, max-age=0, must-revalidate");
            resp.headers().set(HttpHeaderNames.CONNECTION, "keep-alive");
            resp.headers().set(HttpHeaderNames.CONTENT_LENGTH, respByte.capacity());
            resp.headers().set(HttpHeaderNames.CONTENT_TYPE, "image/jpeg");
            resp.headers().set(HttpHeaderNames.DATE, "Mon, 08 Feb 2021 05:14:21 GMT");
            resp.headers().set(HttpHeaderNames.EXPIRES, 0);
            resp.headers().set(HttpHeaderNames.KEEP_ALIVE, "timeout=60");
            resp.headers().set(HttpHeaderNames.LAST_MODIFIED, "Mon, 14 Dec 2020 01:59:59 GMT");
            resp.headers().set(HttpHeaderNames.PRAGMA, "no-cache");
            resp.headers().set(HttpHeaderNames.VARY, "Origin");
            resp.headers().set(HttpHeaderNames.VARY, "Access-Control-Request-Method");
            resp.headers().set(HttpHeaderNames.VARY, "Access-Control-Request-Headers");
            resp.headers().set("X-Content-Type-Options", "nosniff");
            resp.headers().set("X-Frame-Options", "DENY");
            resp.headers().set("X-XSS-Protection", "1; mode=block");
            resp.headers().set("Android_ID", "wang");
 
            ctx.writeAndFlush(resp).addListener(ChannelFutureListener.CLOSE);
        }
 
        if (url.equals("/video")) {

            File file = new File(getRootDirectory() + "video.mp4");
            ByteBuf respByte = Unpooled.buffer((int) file.length());

            try {
                FileInputStream fis = new FileInputStream(file);
                FileChannel channel = fis.getChannel();
                ByteBuffer allocate = ByteBuffer.allocate((int) file.length());
                try {
                    channel.read(allocate);
                } catch (IOException e) {
                    e.printStackTrace();
                }
                respByte.writeBytes(allocate.array());
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            }
 
            FullHttpResponse resp = new DefaultFullHttpResponse(HttpVersion.HTTP_1_1,
                    HttpResponseStatus.OK,
                    respByte
            );
 
            resp.headers().set(HttpHeaderNames.ACCEPT_RANGES, "bytes");
            resp.headers().set(HttpHeaderNames.CACHE_CONTROL, "no-cache, no-store, max-age=0, must-revalidate");
            resp.headers().set(HttpHeaderNames.CONNECTION, "keep-alive");
            resp.headers().set(HttpHeaderNames.CONTENT_LENGTH, file.length());
            resp.headers().set(HttpHeaderNames.CONTENT_TYPE, "video/mp4");
            resp.headers().set(HttpHeaderNames.DATE, "Mon, 08 Feb 2021 05:14:21 GMT");
            resp.headers().set(HttpHeaderNames.EXPIRES, 0);
            resp.headers().set(HttpHeaderNames.KEEP_ALIVE, "timeout=60");
            resp.headers().set(HttpHeaderNames.LAST_MODIFIED, "Mon, 14 Dec 2020 01:59:59 GMT");
            resp.headers().set(HttpHeaderNames.PRAGMA, "no-cache");
            resp.headers().set(HttpHeaderNames.VARY, "Origin");
            resp.headers().set(HttpHeaderNames.VARY, "Access-Control-Request-Method");
            resp.headers().set(HttpHeaderNames.VARY, "Access-Control-Request-Headers");
            resp.headers().set("X-Content-Type-Options", "nosniff");
            resp.headers().set("X-Frame-Options", "DENY");
            resp.headers().set("X-XSS-Protection", "1; mode=block");
            resp.headers().set("Android_ID", "wang");
 
            ctx.writeAndFlush(resp).addListener(ChannelFutureListener.CLOSE);
        }

    }

    public void channelReadComplete(ChannelHandlerContext ctx) throws Exception {
 
        ctx.writeAndFlush(Unpooled.EMPTY_BUFFER)
                .addListener(ChannelFutureListener.CLOSE);
    }

    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {
        cause.printStackTrace();
        ctx.close();
    }
} 

### Netty version
netty-all:4.1.58.Final

### JVM version (e.g. `java -version`)
jdk8

### OS version (e.g. `uname -a`)
android 6-9

**Comment by normanmaurer** [comment]
Can you tell me what error it shows ?

**Comment by normanmaurer** [comment]
Please reopen with more details.
