### ISSUE TITLE
Http2ConnectionHandler may send GOAWAY frame before connection preface

### ISSUE THREAD

**Issue by Bennett-Lynch** [netty/netty#11026]
### Expected behavior

A [GOAWAY frame](https://tools.ietf.org/html/rfc7540#section-6.8) (or any other HTTP/2 frame) should not be sent before the [connection preface](https://tools.ietf.org/html/rfc7540#section-3.5).

### Actual behavior

If a connection is terminated early from the client-side, the `Http2ConnectionHandler` may attempt to send a GOAWAY frame as part of the channel's shutdown logic, even if a connection preface was not yet sent.

On the server-side, this results in errors like:
```
io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 0000080700000000000000000000000000
```

### Minimal yet complete reproducer code (or URL to code)

https://gist.github.com/Bennett-Lynch/19576c3d6f68ab79536b1bbe12d221a7

### Relevant source code

https://github.com/netty/netty/blob/b0ec37d686898161583be692510dc2fb25f8ef25/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L249-L253

https://github.com/netty/netty/blob/b0ec37d686898161583be692510dc2fb25f8ef25/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L457-L478

https://github.com/netty/netty/blob/b0ec37d686898161583be692510dc2fb25f8ef25/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L306-L307

**Comment by normanmaurer** [comment]
Sounds like a bug... @Bennett-Lynch are you interested in doing a PR ?

**Comment by Bennett-Lynch** [comment]
@normanmaurer I am low on available bandwidth right now but if no one picks this up in the next few weeks I will try to take a stab at it.

**Comment by normanmaurer** [comment]
Sounds good.. not sure if I will time anytime soon as well.
