### ISSUE TITLE
[Question] Is the operation of pipeline.invokeHandlerAddedIfNeeded() is repetitive ? 

### ISSUE THREAD

**Issue by horizonzy** [netty/netty#11034]
Hi, I notice the process of io.netty.channel.AbstractChannel.AbstractUnsafe#register0.
https://github.com/netty/netty/blob/28d4154fffc9c51f73b5969c64d74ca17ca4baba/transport/src/main/java/io/netty/channel/AbstractChannel.java#L488-L525

pipeline.invokeHandlerAddedIfNeeded();  at line 502. 
Then at line 505,  pipeline.fireChannelRegistered(); 

When headContext channelRegistered, pipeline.invokeHandlerAddedIfNeeded() will be executed again.
https://github.com/netty/netty/blob/28d4154fffc9c51f73b5969c64d74ca17ca4baba/transport/src/main/java/io/netty/channel/DefaultChannelPipeline.java#L1381-L1384

It's repeatitive?

**Comment by normanmaurer** [comment]
its fine to be called multiple times
