### ISSUE TITLE
Consider exposing WrappedByteBuf (or similar)

### ISSUE THREAD

**Issue by kashike** [netty/netty#11041]
The [WrappedByteBuf](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/WrappedByteBuf.java) class exists, but is package-private. This class can be quite useful in reducing boilerplate in projects which add "helper" methods to their own wrappers - I currently have [this](https://paste.gg/p/kashike/4e98ec073fbf451e8542067ecb7439fd) class in one of my projects, and if `WrappedByteBuf` (or similar) became `public` I could eliminate it.

**Comment by chrisvest** [comment]
There is also `DuplicatedByteBuf`, but objects that wrap `ByteBuf` usually go with `ByteBufHolder` via `DefaultByteBufHolder`. I'm not convinced we need to exposed more stuff here.

**Comment by normanmaurer** [comment]
I agree... I would like to keep this internal
