### ISSUE TITLE
A small problem about traffic shaping. I need your help.Thanks

### ISSUE THREAD

**Issue by sanshiwu** [netty/netty#11040]
About this class TrafficCounter.

When the timer starts, call the method "resetaccounting".

Can add logic code to print traffic shaping message?

I know it's not a bug, it's not a big problem.

```
    @Override
    public void run() {
      GlobalTrafficShapingHandler globalTrafficShapingHandler =
          (GlobalTrafficShapingHandler) ctx.pipeline().get("GlobalTrafficShapingHandler");
      System.out.println(globalTrafficShapingHandler.toString());
      ChannelTrafficShapingHandler channelTrafficShapingHandler =
          (ChannelTrafficShapingHandler) ctx.pipeline().get("ChannelTrafficShapingHandler");
      System.out.println(channelTrafficShapingHandler.toString());
    }
```
Is there another way? Thank you.

**Comment by fredericBregier** [comment]
Maybe by extending the original classes (XxxTrafficShapingHandler), even maybe TrafficCounter, such that you can override your own business logic while calling super() code when necessary ?

**Comment by sanshiwu** [comment]
@fredericBregier 
Thanks for your reply.These classes contain many private variables and methods.
I tried to extend it and looked at the source code.
Because just print some messages, but need to write a lot of extension code, the cost is a bit big.
For a large number of users, the official can add a switch to control printing.

Thanks again for your reply.

**Comment by sanshiwu** [comment]
@All
Because the original class of traffic shaping already has a timer. 
We can consider using this timer to print messages regularly.
Otherwise, we need to create a new timer.
It's not worth the loss.

**Comment by fredericBregier** [comment]
@sanshiwu Yes, you're right. Maybe you can propose a way in a patch to add some "business" handler to enable specific extra actions on Read/Write suspend/activation of traffic, in addition of course to what is done already ?

**Comment by sanshiwu** [comment]
@fredericBregier  I see,Thanks.
