### ISSUE TITLE
negative total numNormalAllocations

### ISSUE THREAD

**Issue by hongliang5623** [netty/netty#11045]
### Expected behavior
positive numNormalAllocations value 
### Actual behavior
negative numNormalAllocations value 
### Steps to reproduce
![image](https://user-images.githubusercontent.com/7711621/109478793-ab34d380-7ab4-11eb-9f85-1a04094d4928.png)
![image](https://user-images.githubusercontent.com/7711621/109478878-bee03a00-7ab4-11eb-9c20-683c01ba7a8f.png)

### Minimal yet complete reproducer code (or URL to code)

```
import io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator;
import io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocatorMetric;

PooledByteBufAllocatorMetric metric = PooledByteBufAllocator.DEFAULT.metric();
List<PoolArenaMetric> directArenaMetrics = metric.directArenas();
long numNormalAllocations = directArenaMetrics.stream().mapToLong(PoolArenaMetric::numNormalAllocations).sum();
```

### Netty version
4.1.38
### JVM version (e.g. `java -version`)
java version "1.8.0_202"
### OS version (e.g. `uname -a`)
CentOS Linux release 7.3.1611 (Core）

**Comment by chrisvest** [comment]
@hongliang5623 Are you sure this is a problem in Netty and not in the integration code or configuration that produced those charts? I don't see anything suspicious in how those counters are handled internally.

**Comment by hyperxpro** [comment]
Pretty sure that this is a chart error. Which software you're using to generate these charts?

**Comment by hongliang5623** [comment]
the charts was generate by [graphite](https://grafana.com/docs/grafana/latest/datasources/graphite/), I've doubted the charts also, but some of them looks normal, so it's strange
![image](https://user-images.githubusercontent.com/7711621/109587720-85eea680-7b42-11eb-9e5d-2877c602d791.png)

**Comment by hongliang5623** [comment]
I'm debugging direct memory leaks about netty (used by [grpc-java 1.23](https://github.com/grpc/grpc-java/releases/tag/v1.23.0)), so i made this [num_xxx_Allocations](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/PoolArenaMetric.java#L24) chart as reference, 
my code is :
```
import io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocator;
import io.grpc.netty.shaded.io.netty.buffer.PooledByteBufAllocatorMetric;

PooledByteBufAllocatorMetric metric = PooledByteBufAllocator.DEFAULT.metric();
List<PoolArenaMetric> directArenaMetrics = metric.directArenas();
long numNormalAllocations = directArenaMetrics.stream().mapToLong(PoolArenaMetric::numNormalAllocations).sum();
long numNormalDeallocations = directArenaMetrics.stream().mapToLong(PoolArenaMetric::numNormalDeallocations).sum();
long numActiveNormalAllocations = directArenaMetrics.stream().mapToLong(PoolArenaMetric::numActiveNormalAllocations).sum();
```
by reading the source code, I think it must  be
`numActiveNormalAllocations + numNormalDeallocations = numNormalAllocations`

the numActiveNormalAllocations value seems normal, but numNormalDeallocations and numNormalAllocations may not be right,The following is the numActiveNormalAllocations chart：
![image](https://user-images.githubusercontent.com/7711621/109589939-17134c80-7b46-11eb-8607-e230e9844afe.png)

**Comment by chrisvest** [comment]
@hongliang5623 Are you able to check if the problem is still there in the latest Netty 4.1? There were recently (last summer) some changes to the pooled allocator.

**Comment by hongliang5623** [comment]
@chrisvest after i upgrade Netty  4.1.51 used by [grpc-java 1.33.1](https://github.com/grpc/grpc-java/blob/v1.33.x/build.gradle#L57 ) the `numActiveNormalAllocations`  `numNormalDeallocations`  `numNormalAllocations` change to 0 , with the same code, except directArenaMetrics.size()=128
```
directArenaMetrics.size()=128
```

**Comment by hongliang5623** [comment]
Oh, I see，the maximum value long is exceeded, closed!
```
public class HelloWorld {
    public static void main(String []args) {
       System.out.println("Hello World!");
	   System.out.println(1024*1024*1024*10);
    }
}
Hello World!
-2147483648
```

**Comment by chrisvest** [comment]
@hongliang5623 that example, `System.out.println(1024*1024*1024*10)`, is an integer overflow… 32-bits. Long is 64-bits. It would be surprising if had a 64-bit overflow, but it could be that we have a 32-bit calculation hiding somewhere.
