### ISSUE TITLE
Allow to config the listen address on DnsResolver

### ISSUE THREAD

**Issue by Shoothzj** [netty/netty#11054]
The DnsResolver default start address listen to "0.0.0.0", which may have some security risks.
Can we allow to config the listen address on DnsResolver?

**Comment by normanmaurer** [comment]
@Shoothzj sure... Maybe provide a PR that allows to configure the `SocketAddress` via the `DnsResolverBuilder` ?

**Comment by Shoothzj** [comment]
@normanmaurer I am new to Netty code contributing. How about java property `io.netty.dnsResolverListenAddress`

**Comment by normanmaurer** [comment]
I would prefer to make it configurable via the builder..
