### ISSUE TITLE
NullPointerException from WriteTimeoutTask.operationComplete()

### ISSUE THREAD

**Issue by dadepo** [netty/netty#11053]
### Expected behavior

Not to throw null pointer exception

### Actual behavior

An application was recently upgraded to Netty 4 and I am observing unexplainable Null pointer being thrown.

```
2021-03-02T17:56:37,551 WARN  [DefaultPromise] An exception was thrown by io.netty.handler.timeout.WriteTimeoutHandler$WriteTimeoutTask.operationComplete()
java.lang.NullPointerException: null
	at io.netty.handler.timeout.WriteTimeoutHandler.removeWriteTimeoutTask(WriteTimeoutHandler.java:165) ~[db-8569c76d.jar:?]
	at io.netty.handler.timeout.WriteTimeoutHandler.access$000(WriteTimeoutHandler.java:66) ~[db-8569c76d.jar:?]
	at io.netty.handler.timeout.WriteTimeoutHandler$WriteTimeoutTask.operationComplete(WriteTimeoutHandler.java:217)
```

### Steps to reproduce

No definitive reproducible steps as this seems to happen sporadically. So far, the application is restarted and left alone, and in couple of minutes sometimes hours, the Null pointer exception pops up in the log.

Perhaps someone more familiar with the internals  of the framework have an idea why and how this is happening? 

### Netty version

4.1.59.Final

### JVM version (e.g. `java -version`)

```
openjdk version "11.0.9" 2020-10-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.9+11-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9+11-LTS, mixed mode, sharing)
```

### OS version (e.g. `uname -a`)

```
Linux host 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by normanmaurer** [comment]
Will have a look

**Comment by normanmaurer** [comment]
@dadepo can you show me the code that adds handlers to the pipeline ?

**Comment by dadepo** [comment]
@normanmaurer sure. [Here](https://github.com/RIPE-NCC/whois/blob/085d1d300c0d741d78ab555297812d03c3d407a0/whois-query/src/main/java/net/ripe/db/whois/query/pipeline/WhoisServerChannelInitializer.java#L65)

**Comment by normanmaurer** [comment]
@dadepo that was helpful... I think it should be fixed by https://github.com/netty/netty/pull/11056
