### ISSUE TITLE
How to build Netty 4.1 in IntelliJ for its JDK7+ dependencies?

### ISSUE THREAD

**Issue by Bennett-Lynch** [netty/netty#11069]
This is perhaps a dumb question, but how am I supposed to build Netty 4.1 in IntelliJ for its JDK7+ dependencies? If I do a fresh clone of Netty/4.1 and open it in IntelliJ, the build fails due to:

```
Executing pre-compile tasks...
Loading Ant configuration...
Running Ant tasks...
Running 'before' tasks
Checking sources
Copying resources... [netty-resolver]
Copying resources... [netty-buffer]
Copying resources... [netty-common]
Copying resources... [netty-codec]
Copying resources... [netty-transport]
Copying resources... [netty-handler]
Copying resources... [netty-codec-http]
Parsing java... [netty-common]
java: Errors occurred while compiling module 'netty-common'
Checking dependencies... [netty-common]
Dependency analysis found 0 affected files
javac 11.0.10 was used to compile java sources
Finished, saving caches...
Compilation failed: errors: 48; warnings: 7
Executing post-compile tasks...
Loading Ant configuration...
Running Ant tasks...
Synchronizing output directories...
3/8/21, 8:27 PM - Build completed with 48 errors and 7 warnings in 10 sec, 766 ms
```

Errors like, e.g.,

![Screen Shot 2021-03-09 at 5 06 44 PM](https://user-images.githubusercontent.com/11811448/110559906-e7da7d80-80f9-11eb-9629-a59e65dc14cc.png)

```
.../netty/common/src/main/java/io/netty/util/internal/PlatformDependent.java:141:48
java: cannot find symbol
  symbol:   class ThreadLocalRandom
  location: package java.util.concurrent
```

This is with the IntelliJ Project SDK set to JDK11 and the project language level set to 11:

![Screen Shot 2021-03-09 at 5 11 56 PM](https://user-images.githubusercontent.com/11811448/110560287-97175480-80fa-11eb-8774-512fdaacc772.png)

I see that individual modules have their language level set lower, but I'm assuming I don't need to manually modify all of those.

I understand that Netty conditionally checks the JDK version at runtime to determine behavior, but I'm not sure how to fix this in IntelliJ and/or Maven so that I can run unit tests and the like. I've been resorting to running unit tests from the command-line, which is not great for debugging.

**Comment by chrisvest** [comment]
I tell Intellij to use a Java 8 SDK. I let the Docker-based builds deal with JDK 6 and 7. It seems Intellij is not evaluating some build configurations in quite the same way that Maven does.

If you wish to debug something while running the tests on older JDKs, I would suggest running the tests from Maven with that JDK, and a `-Dmaven.surefire.debug` runtime flag, and then remote-debug that JVM from Intellij.

**Comment by Bennett-Lynch** [comment]
Thanks, @chrisvest. In my case, I'm telling IntelliJ to use JDK11, but it still will not recognize the language features added in JDK7 and above. Did you do anything else to get IntelliJ to recognize those language features with your JDK8? I'm assuming JDK11 should not behave much differently than JDK8, unless it behaves differently due to the new Jigsaw-module feature.

(I'm okay not trying to run/debug on older JDKs, but good point on the remote debugger.)

**Comment by chrisvest** [comment]
@Bennett-Lynch Try opening the Maven side-panel, unfold Profiles and make sure `java11` is checked.

**Comment by Bennett-Lynch** [comment]
![Screen Shot 2021-03-09 at 5 04 30 PM](https://user-images.githubusercontent.com/11811448/110559713-93cf9900-80f9-11eb-92a6-2f9188800e7d.png)

**Comment by chrisvest** [comment]
@Bennett-Lynch What is the setting of your "Use `--release`" Java compiler setting? Mine looks like this:

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/7993/110696068-e50b8580-81ea-11eb-96c0-346c64894be7.png">

**Comment by Scottmitch** [comment]
I've experience the same issue. Default configuration resulting in broken project is painful. I wonder if the way we are configuring the pom file (or idea) can be improved, or if this is a idea issue. seems like this will continue to impact folks re-initializing their environment IIUC.

https://www.jetbrains.com/help/idea/java-compiler.html#compiler
> By default, this option is selected. IntelliJ IDEA deduces from project settings when the cross-compilation is needed and automatically applies the --release compiler option for Java 9.
