### ISSUE TITLE
SCTP reconnect with same localAddress will be timeout

### ISSUE THREAD

**Issue by KisetsuLee** [netty/netty#11065]
### Expected behavior
Excepted reconnect to server use first connected local address success.
### Actual behavior
occured timeout
### Steps to reproduce
1. client connect to remote (127.0.0.1:8007) and get local address (127.0.0.1:50000 or ipv6:50000)
2. client disconnect
3. client reconnect to remote (127.0.0.1:8007), localAddress set to 127.0.0.0:50000 simultaneously
4. timeout to connect to 127.0.0.1:8007
### Minimal yet complete reproducer code (or URL to code)
https://github.com/KisetsuLee/netty-demo/tree/master/src/main/java/com/lee/sctp

recommend run step (or other ways you like):
1. change dir to pom.xml located dir, doing maven package `mvn clean package -Dmaven.test.skip=true`
2. cd to target dir, you will get a jar package named `netty-1.0-SNAPSHOT-jar-with-dependencies.jar` that contain everyting about running class
3. setup server first `java -cp netty-1.0-SNAPSHOT-jar-with-dependencies.jar com.lee.sctp.SctpEchoService`
4. setup client later `java -cp netty-1.0-SNAPSHOT-jar-with-dependencies.jar com.lee.sctp.SctpEchoClient`

### Netty version
io.netty:netty-all:4.1.32.Final
### JVM version 
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
### OS version 
Linux VM-0-15-centos 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
### lksctp-tools version
lksctp-tools-1.0.17-2.el7.x86_64
lksctp-tools-1.0.17-2.el7.i686

**Comment by normanmaurer** [comment]
We just re-use what the JDK provides... You may need to open a bug there.

**Comment by KisetsuLee** [comment]
Fine，thanks
