### ISSUE TITLE
io.netty.eventLoopThreads  Why the default value is NettyRuntime.availableProcessors() * 2

### ISSUE THREAD

**Issue by asasas234** [netty/netty#11079]
I would like to ask you, when I read the Netty source code, I found that the default value of io.netty.eventLoopThreads is NettyRuntime.availableProcessors() * 2, that is, the CPU multiplier multiplied by 2. I don't understand what the reason is, Netty I understand is a non-blocking IO call. Since it does not block threads, why not NettyRuntime.availableProcessors()? Is there any explanation for this?

**Comment by normanmaurer** [comment]
@asasas234 it goes back many years... and while it is non-blocking users still may do some work in the `ChannelHandler`s. That said I think there is really no "this setting fits all" value and at the end you will need to profile your app to find the right value.
