### ISSUE TITLE
How to properly release the DIY message

### ISSUE THREAD

**Issue by theodore414** [netty/netty#11078]
### Expected behavior
DIY message is released

### Steps to reproduce
Used 4.1.50.Final jar 
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)

public class TransmissionMessage implements ReferenceCounted {

    private Map<String,Object> someMap;

    @Override
    public int refCnt() {
        return 0;
    }

    @Override
    public ReferenceCounted retain() {
        return null;
    }

    @Override
    public ReferenceCounted retain(int i) {
        return null;
    }

    @Override
    public ReferenceCounted touch() {
        return null;
    }

    @Override
    public ReferenceCounted touch(Object o) {
        return null;
    }

    @Override
    public boolean release() {
        return false;
    }

    @Override
    public boolean release(int i) {
        return false;
    }
}

we what to know how to release our msg 
We need to pass somemap to the next handler

**Comment by normanmaurer** [comment]
The handler that "consumes the message" is responsible to call `release()`
