### ISSUE TITLE
UnorderedThreadPoolEventExecutor's future.get() returns null

### ISSUE THREAD

**Issue by meshcow** [netty/netty#11072]
### Expected behavior
get() & getNow() methods of futures returned by submit(task) method of UnorderedThreadPoolEventExecutor return the task's result 
### Actual behavior
null is always returned
### Steps to reproduce
see code below
### Minimal yet complete reproducer code (or URL to code)
```java
import io.netty.util.concurrent.UnorderedThreadPoolEventExecutor;
import org.junit.Assert;
import org.junit.Test;
import java.util.concurrent.Future;

public class TestUnorderedThreadPoolEventExecutor {

    @Test
    public void testGet() throws Exception{
        UnorderedThreadPoolEventExecutor executor = new UnorderedThreadPoolEventExecutor(1);
        // compare: ScheduledThreadPoolExecutor executor = new ScheduledThreadPoolExecutor(1);

        Future<String> f = executor.submit(() -> "completed!");

        while(!f.isDone()) {
            Thread.sleep(1);
        }

        Assert.assertNotNull(f.get());

        executor.shutdown();
    }
}
```

### Netty version
All from 4.1.54.Final to 4.1.60.Final. Worked correctly in 4.1.53.Final.
### JVM version (e.g. `java -version`)
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.275-b01, mixed mode)
### OS version (e.g. `uname -a`)
Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
Sounds like a bug... I will have a look
