### ISSUE TITLE
How can I remove AttributeKey created by AttributeKey.valueOf from ConstantPool's constants property?

### ISSUE THREAD

**Issue by zqq1202** [netty/netty#11073]
### Expected behavior
I can remove AttributeKey created by AttributeKey.valueOf from ConstantPool's constants property
### Actual behavior
I can't  find a way to do it.
### Steps to reproduce
For every request to the Netty server，the program will create a AttributeKey using AttributeKey.valueOf.
But after running for about a day or two, the dump file shows that about more than one million instances of AttributeKey  exist and finally caused OOM。
I look into the souce code of class io.netty.util.ConstantPool and found that when using AttributeKey.valueOf to create a AttributeKey , one instance (with unique name) of AttributeKey  would be put into ConstantPool's property "constants"  which is instance of ConcurrentMap.

```java
public abstract class ConstantPool<T extends Constant<T>> {

    private final ConcurrentMap<String, T> constants = PlatformDependent.newConcurrentHashMap();
}
```

I want to know how can I remove the AttributeKey from  ConstantPool's property "constants"?
### Netty version
4.1.47.Final

### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
CentOS

**Comment by normanmaurer** [comment]
You can't... `AttributeKey`s should be created once and then reused. Basically create it as a static field and re-use it.
