### ISSUE TITLE
Issue - Netty channelRead0 retrun ByteBuf msg null object and channel().isActive false 

### ISSUE THREAD

**Issue by vaibhavpatil123** [netty/netty#11075]
### Expected behavior
ByteBuf msg should not null
### Actual behavior
ByteBuf msg is null
### Steps to reproduce
Used  <version>4.1.48.Final</version> jar java and normal client 
### Netty version
3
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)

@Override
        public void channelRead0(ChannelHandlerContext ctx, final ByteBuf msg) {
         
            do {
                log.info(" channel().isActive false so waiting till become active");
                try {
                    Thread.sleep(10);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            } while (!ctx.channel().isActive());
            if (msg != null) {
                byte[] bytes = new byte[msg.readableBytes()];
                msg.readBytes(bytes);
                response = bytes;
                if (response != null) {
                    log.info("impl.DhcpNetty.DHCPClientHandler.channelRead0() - response length: {0}", response.length);
                } else {
                    log.info("managers.dhcp.impl.DhcpNetty.DHCPClientHandler.channelRead0() - response length is ZERO");
                }
                msg.retain();
                msg.release();
            }
            responseReady.compareAndSet(false, true);
            request = null;
            log.info("SUCCESSFUL DHCPClientHandler.channelRead0");
        }

**Comment by normanmaurer** [comment]
Please provide a full reproducer... Also calling `Thread.sleep()` in a handler is never a good idea as this will block the event loop.

**Comment by hyperxpro** [comment]
Also, please use the latest version of Netty to test. Current latest version: 4.1.60.Final.

**Comment by vaibhavpatil123** [comment]
Removed thread sleep 
changed code 

@Override
        public void channelRead0(ChannelHandlerContext channelHandlerContext, final ByteBuf msg) {
            log.info("START .DHCPClientHandler.channelRead0");
            this.channelHandlerContext = channelHandlerContext;
            try {
                if (msg != null) {
                    byte[] bytes = new byte[msg.readableBytes()];
                    msg.readBytes(bytes);
                    response = bytes;
                    if (response != null) {
                        log.info("Successful .DHCPClientHandler.channelRead0() - response length: {0}", response.length);
                    } else {
                        log.info("Successful .DHCPClientHandler.channelRead0() - response length is ZERO");
                    }
                    msg.retain();
                    msg.release();
                    responseReady.compareAndSet(false, true);
                    request = null;
                } else {
                    log.info(".DHCPClientHandler.channelRead0() channelHandlerContext.isRemoved {0} - ", this.channelHandlerContext.isRemoved());
                    log.info(".DHCPClientHandler.channelRead0() channelHandlerContext.channel().isOpen {0} - ", this.channelHandlerContext.channel().isOpen());
                }
            } catch (Exception ex) {
                log.severe("ERROR .DHCPClientHandler.channelRead0 {0}", ex.getMessage());
            }
            log.info("SUCCESSFUL .DHCPClientHandler.channelRead0");
        }



Observation >>>>>>>>>>>>>> some time below method get read response but above metod returns always blank response
@Override
        public void channelRead(ChannelHandlerContext ctx, Object msg) {
}

Currently I have kept 2 methods in class

We cant use new version due restrictions

**Comment by normanmaurer** [comment]
You will need to provide us with a "full reproducer". Also please format your code in the markdown its really hard to read

**Comment by normanmaurer** [comment]
Closing as no response from reporter
