### ISSUE TITLE
A memory leak

### ISSUE THREAD

**Issue by zhangran2616** [netty/netty#11098]
![image](https://user-images.githubusercontent.com/6472032/111612392-6204b380-8818-11eb-8ccd-c8c445096038.png)

![image](https://user-images.githubusercontent.com/6472032/111612316-52856a80-8818-11eb-8a79-771c5cfe6976.png)

![image](https://user-images.githubusercontent.com/6472032/111612592-94161580-8818-11eb-8966-c10e3ec69508.png)

![image](https://user-images.githubusercontent.com/6472032/111612749-c0319680-8818-11eb-8568-399d0c351a4b.png)

A memory leak

jdk1.8

**Comment by normanmaurer** [comment]
Please upgrade your netty version. `ObjectCleaner` is not used anymore for ages.

**Comment by zhangran2616** [comment]
> Please upgrade your netty version. `ObjectCleaner` is not used anymore for ages.

thanks
