### ISSUE TITLE
Will it use netty-handler's define instead of netty-all's own define?

### ISSUE THREAD

**Issue by SK-Yang** [netty/netty#11118]
I read your netty-all:4.1.60.Final POM on maven central, seem like it will also download buffer, codec, and other netty libs and pack them into my WebAPP while I export it. So I have a question:  If I modified netty-handler's jdkSSLContext class and build my own jar, then replace the default netty-handler-4.1.60.final with my modified handler. Will netty use my customized handler lib instead of its own define inside netty all-in-one.jar? If no, is it necessary to have those netty libs but one netty-all?

**Comment by hyperxpro** [comment]
`netty-all` downloads all Netty modules `jar`s. If you want to modify something, you should look forward to shading.

**Comment by normanmaurer** [comment]
@SK-Yang in this case you should use each lib/jar independently and not use netty-all
