### ISSUE TITLE
Why momory usage of preferDirectBufs mode is larger than set it to false?

### ISSUE THREAD

**Issue by squalud** [netty/netty#11129]
### Expected behavior
In the same test case, memory usage of using direct memory is the same as using heap memory. 

### Actual behavior
The used memory in preferDirectBufs mode is about 4 times as preferDirectBufs is set to false

### Steps to reproduce
1) set preferDirectBufs=true;
2) do some performance test
3) check the value of PooledByteBufAllocatorMetric#usedDirectMemory()

4) set preferDirectBufs=false;
5) do the same test as in step 2
6) check the value of PooledByteBufAllocatorMetric#usedHeapMemory()

then I found that the used memory in preferDirectBufs mode is about 4 times as preferDirectBufs is set to false. And cause direct memory OOM errors

### Netty version
4.1.47

### JVM version (e.g. `java -version`)
java version "1.8.0_242"

**Comment by chrisvest** [comment]
@squalud Are you able to provide a self-contained test case that shows this? Some things, such as certain IO operations on some transports, require direct memory. The setting changes the behaviour of `ByteBufAllocator.buffer()` methods, but not the behaviour of `ByteBufAllocator.ioBuffer()` methods. I think that's what you're seeing. You can try instrumenting these methods in a debugger and see what gets allocated where.

**Comment by normanmaurer** [comment]
Let me close this as the reporter did not respond. Please re-open with more details
