### ISSUE TITLE
[Netty5] ChannelHandler interface should offer initialize/teardown callbacks

### ISSUE THREAD

**Issue by Bennett-Lynch** [netty/netty#11131]
Some/many ChannelHandler implementations need to implement one-time initialize/teardown logic, where the initialize logic is only suitable to call once the handler has been added to an active channel. The ChannelHandler callback that is first invoked in this state highly depends on _when_ the handler is added to or removed from a channel/pipeline. This results in having to implement a large amount of boilerplate code to try to gracefully detect and handle the desired event.

E.g., the `IdleStateHandler` implements all of the following callbacks just to correctly invoke `initialize(..)`:

https://github.com/netty/netty/blob/e4dd6ee53278018b1bce86ed79581876f1a89ba5/handler/src/main/java/io/netty/handler/timeout/IdleStateHandler.java#L239-L249

https://github.com/netty/netty/blob/e4dd6ee53278018b1bce86ed79581876f1a89ba5/handler/src/main/java/io/netty/handler/timeout/IdleStateHandler.java#L256-L263

https://github.com/netty/netty/blob/e4dd6ee53278018b1bce86ed79581876f1a89ba5/handler/src/main/java/io/netty/handler/timeout/IdleStateHandler.java#L265-L272

And it implements the following callbacks just to correctly invoke `destroy()`:

https://github.com/netty/netty/blob/e4dd6ee53278018b1bce86ed79581876f1a89ba5/handler/src/main/java/io/netty/handler/timeout/IdleStateHandler.java#L251-L254

https://github.com/netty/netty/blob/e4dd6ee53278018b1bce86ed79581876f1a89ba5/handler/src/main/java/io/netty/handler/timeout/IdleStateHandler.java#L274-L278

And then there is additional boilerplate logic inside of `initialize(..)` and `destroy()` to ensure they are only invoked once.

Rather than requiring users to implement this boilerplate logic, Netty could offer guaranteed-to-be-called-only-once initialize and teardown methods, where the default implementation does nothing. There are similar design precedents in other frameworks.

This should be offered natively by Netty because while users can try to create an abstract handler to achieve similar functionality, it would be brittle due to requiring subclasses to always invoke the super method (which is not always desired), or the abstract handler would need to replace the standard Netty callbacks with new abstract methods.

Possible method names:
* `handlerActive(..)`
* `handlerInactive(..)`

**Comment by normanmaurer** [comment]
hmm `handlerAdded` and `handlerRemoved` already give these guarantees ...  I think most of the methods you have linked here could be simplified as like I said there is already this guarantee

**Comment by Bennett-Lynch** [comment]
Can’t `handlerAdded` be called before the channel is active, and `handlerRemoved` be called after the channel is inactive?

Maybe I’m over-indexing on how common the need to only act on an active channel is.

**Comment by normanmaurer** [comment]
yes it can... but I think thats ok.

**Comment by normanmaurer** [comment]
Let me close this for now
