### ISSUE TITLE
Content-length=0 header in `HttpMessage.headers` for GET request that doesnt contain Content-length at all

### ISSUE THREAD

**Issue by declspec-cdecl** [netty/netty#11139]
https://github.com/netty/netty/blob/e5951d46fc89db507ba7d2968d2ede26378f0b04/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectAggregator.java#L230

Cant understand why it should be added for requests that doesnt contain Content-length header at all . Isn't the purpose of FullHttpMessage to represent corresponding http request maximum accurately. If so, why should we add header that doesn't exist in original query?

**Comment by normanmaurer** [comment]
It just tries to handle things consistent... Why would there be an issue to add the header ? It is inline with the spec and so should not have any negative side-effect.s
