### ISSUE TITLE
ChunkedInputStream isEndOfInput blocks event loop

### ISSUE THREAD

**Issue by davydotcom** [netty/netty#11147]
In all versions of netty the ChunkedInputStream isEndOfInput uses b.read() which is blocking. This should instead use available()

**Comment by chrisvest** [comment]
`available()` only tells you how many bytes you can read without blocking; it doesn't tell if you're at the end of the stream.

**Comment by davydotcom** [comment]
Actually it returns -1 or an error when at end of stream
