### ISSUE TITLE
Netty DNS resolver fails to resolve computer's name on Windows

### ISSUE THREAD

**Issue by violetagg** [netty/netty#11142]
When running on a VM with Windows 10, Netty DNS resolver cannot resolve computer's name.

### Expected behavior
When on Windows, Netty DNS resolver is able to resolve the computer's name

### Actual behavior
The current implementation throws an exception when one tries to resolve the computer's name

```
Caused by: java.net.UnknownHostException: failed to resolve 'DESKTOP-BHE9K15' after 2 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1013)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:966)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:414)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:938)
	at io.netty.resolver.dns.DnsResolveContext.access$700(DnsResolveContext.java:63)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:467)
```

### Minimal yet complete reproducer code (or URL to code)

```
public class Application {

    public static void main(String[] args) throws Exception {
        // JDK
        InetAddress[] addresses = InetAddress.getAllByName("DESKTOP-BHE9K15");
        System.out.println(Arrays.asList(addresses));

        // JDK
        InetAddress localhost = InetAddress.getLocalHost();
        System.out.println(localhost);

        NioEventLoopGroup group = new NioEventLoopGroup();
        try {
            List<InetSocketAddress> result =
                    DefaultAddressResolverGroup.INSTANCE
                            .getResolver(group.next())
                            .resolveAll(InetSocketAddress.createUnresolved("DESKTOP-BHE9K15", 80))
                            .get();
            System.out.println("Netty DefaultAddressResolverGroup " + result);

            DnsNameResolverBuilder builder = new DnsNameResolverBuilder(group.next())
                    .channelType(NioDatagramChannel.class);
            DnsNameResolver resolver = builder.build();
            resolver.resolveAll("DESKTOP-BHE9K15")
                    .get();
        }
        finally {
            group.shutdownGracefully();
        }
    }
}
```

when the above code is executed, the result is:

```
[DESKTOP-BHE9K15/IPv4, DESKTOP-BHE9K15/IPv6]
DESKTOP-BHE9K15/IPv4
Netty DefaultAddressResolverGroup [DESKTOP-BHE9K15/IPv4:80, DESKTOP-BHE9K15/[IPv6]:80]
Exception in thread "main" java.util.concurrent.ExecutionException: java.net.UnknownHostException: failed to resolve 'DESKTOP-BHE9K15' after 2 queries 
```

### Netty version
4.1.63.Final

### JVM version (e.g. `java -version`)
java 11

### OS version (e.g. `uname -a`)
Windows 10

**Comment by violetagg** [comment]
Is it possible to have a solution similar to the one for `localhost`?

https://github.com/netty/netty/blob/4.1/resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java#L684-L697

**Comment by normanmaurer** [comment]
@violetagg not sure what you are suggesting... can you maybe do a PR to show the idea ?

**Comment by violetagg** [comment]
@normanmaurer I see two options but none of them is good enough.

- To use `System.getenv("COMPUTERNAME")` and implement it in a way `localhost` is handled, but we use environment variable which I don't think is reliable and secure.
- Another option is to use `InetAddress.getLocalHost().getHostName()` but this is blocking

Wdyt?
I don't like both of them

**Comment by normanmaurer** [comment]
@violetagg couldn't we just call `InetAddress.getLocalHost().getHostName()` once in a static block ?

**Comment by violetagg** [comment]
> @violetagg couldn't we just call `InetAddress.getLocalHost().getHostName()` once in a static block ?

Yep and then apply the solution for `localhost`

**Comment by normanmaurer** [comment]
@violetagg can you do a PR ?

**Comment by violetagg** [comment]
> @violetagg can you do a PR ?

ok
