### ISSUE TITLE
Keepalive connection returns invalid response if HttpResponseEncoder is reused on the pipeline

### ISSUE THREAD

**Issue by abstractdog** [netty/netty#11155]
### Expected behavior
Attached a sample, which is an excerpt from tez/hive ShuffleHandler. With netty3, a unit test pass, with netty4, a strange workaround needed. In the example unit test, a connection is made, both of them should succeed.

### Actual behavior
The second query fails, because it finds HttpResponseEncoder in an "invalid" state here:
```
            if (state != ST_INIT) {
                throw new IllegalStateException("unexpected message type: " + StringUtil.simpleClassName(msg)
                        + ", state: " + state);
            }
```
Original analysis is here:
https://issues.apache.org/jira/browse/TEZ-4157?focusedCommentId=17100835&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17100835

### Steps to reproduce
Linked unit test, removed all hive/tez specific code.
Fails by default, but passes with a workaround:
```
                // !!!!!!!! workaround: uncomment this to make the test pass !!!!!!!!!
                // pipeline.replace(pipeline.get("encoder"), "encoder", new HttpResponseEncoder());
```

### Minimal yet complete reproducer code (or URL to code)
https://gist.github.com/abstractdog/5b9330318b1676614234af57a5e97eef

### Netty version
4.1.48.Final

### JVM version (e.g. `java -version`)
```
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

### OS version (e.g. `uname -a`)
```
Darwin MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
```

**Comment by chrisvest** [comment]
You need to tell the encoder that there is no more content coming from your HTTP response:

```java
ch.writeAndFlush(LastHttpContent.EMPTY_LAST_CONTENT);
```

This resets the state of the `HttpResponseEncoder`. The `LastHttpContent` is a marker interface which you could make any last message implement, if the types align like that. There's also `DefaultFullHttpResponse` that you could use in your example.

**Comment by chrisvest** [comment]
Also, you could make most writes just be `write` calls, and only have the last one be a `writeAndFlush`.

**Comment by chrisvest** [comment]
Netty 3 and 4 have many differences, so I think this is just how the API works now. You can perhaps draw some inspiration from the "file server" and "upload" examples: https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/http

I think this resolves your issue, so I'm going to close this.

**Comment by abstractdog** [comment]
thanks @chrisvest, I reviewed write/writeAndFlush usage in my use-case according to your comments, and it helped!
