### ISSUE TITLE
NioEventLoop#select can hang forever

### ISSUE THREAD

**Issue by rmannibucau** [netty/netty#11153]
### Expected behavior
All branches in io.netty.channel.nio.NioEventLoop#select should have a timeout handling (at least the capability to do so).
Concretely deadlineNanos == NONE branch should get a default global timeout or so handling.

### Actual behavior
If there is no scheduled task associated an infinite timeout is used and select() hangs.

### Steps to reproduce
Just did a simple line based client and stopping the executor service is not sufficient since select() blocks (and ES is not supposed to kill the threads to enable a graceful shutdown).

### Minimal yet complete reproducer code (or URL to code)
Not yet but guess issue is easy enough to see in the code.

### Netty version
4.1.62.Final

### JVM version (e.g. `java -version`)
11.0.10 (azul)

### OS version (e.g. `uname -a`)
Ubuntu 21.04

**Comment by chrisvest** [comment]
This is not a problem because we call `selector.wakeup()` when new tasks are added. This causes the next or any currently-blocked `select()` call to return.

**Comment by rmannibucau** [comment]
@chrisvest hmm, wonder if it can't be an issue at shutdown time - this is where I met it and the shutdown was hanging. Due to io.netty.util.concurrent.SingleThreadEventExecutor#ensureThreadStarted the wakeup call can be skipped I think and the forced run of io.netty.util.concurrent.SingleThreadEventExecutor#doStartThread can also miss the wakeup call. I'm not 100% of the cause yet and I can't reproduce it each time but in some aggressive shutdown version of the code (very small awaiting duration and quiet=0 + shutdown of the worker thread pool just after) it was happening regularly. At least not hanging forever would be neat, even if the shutdown pattern is not expected (proposed to put a timeout but forcing some more wakeup can do it too). Will try to provide more info if I can reproduce it again but reworked most of the code today so can be hard now.

**Comment by chrisvest** [comment]
Okay, from the original issue it sounded like it was theoretical, but if you've encountered the problem then we need to look at it. If you're able to narrow it down to some test case, then that would be super helpful.

**Comment by rmannibucau** [comment]
@chrisvest yep, I really suspect the agressive shutdown before the connection was fully startup was the issue (i use - ok abuse ;)) of CompletionStage in this code and enable to start send messages before connect is actually finished by buffering them. In the test I was shutting down very quickly because of an error - wrong assert in early stage independent of the network - so I was in the "in between" state I described in the previous code. I don't expect it to be "normal" nor "common" but it happens and debugging the select() was preventing the JVM to shutdown because the thread are not - intentionally - daemon. Will report more if I hit it again.

**Comment by normanmaurer** [comment]
Lets close for now
