### ISSUE TITLE
Utilize i.n.u.internal.ObjectUtil to assert Preconditions

### ISSUE THREAD

**Issue by boris-unckel** [netty/netty#11170]
### Expected behavior
NullChecks resulting in a NullPointerException or IllegalArgumentException, numeric ranges (>0, >=0) checks, not empty strings/arrays checks must never be anonymous but with the parameter or variable name which is checked. They must be specific and should not be done with an "OR-Logic" (if a == null || b == null) throw new NullPointerEx.

### Actual behavior
Some checks are already done with the io.netty.util.internal.ObjectUtil code. Some are done manually.

### Steps to reproduce
checkout the master
grep -r "Objects.req"
grep -r "throw new NullPointerException"
grep -r "throw new IllegalArgumentException" (individual check necessary)

### Minimal yet complete reproducer code (or URL to code)
Existing codebase.

### Netty version
4.1 (updated version)

### JVM version (e.g. `java -version`)
Not relevant, all
### OS version (e.g. `uname -a`)
Not relevant, all

### Providing the fix
One pull request per sub-project to enable reviewers to focus on a relevant subset. First one is common itself, including a new unit test for ObjectUtil itself.

**Comment by normanmaurer** [comment]
@boris-unckel I am happy to review a PR 👍
