### ISSUE TITLE
Adaptation problem

### ISSUE THREAD

**Issue by TonbovoShaw** [netty/netty#11176]
### OS version
Hello developer, I am a developer using the m1 chip version of the macbook. My project will report "Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_kqueue_aarch_64 in java.library.path" when it starts. I hope to develop Out of the jar package of the arm architecture. Grateful.

**Comment by TonbovoShaw** [comment]
> ### OS version
> Hello developer, I am a developer using the m1 chip version of the macbook. My project will report "Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_kqueue_aarch_64 in java.library.path" when it starts. I hope to develop Out of the jar package of the arm architecture. Grateful.

**Comment by tzssangglass** [comment]
hi, I encountered a similar problem, how did you solve it?
