### ISSUE TITLE
Jcenter Migration Steps

### ISSUE THREAD

**Issue by austince** [netty/netty#11189]
Since the [`jcenter` sunset and shut down is imminent](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter), what are the plans going forward? It looks like March 31st, 2021 is the last day new package submissions will be accepted and packages will still be served through January of 2022, but the service reliability has taken a big hit in the last few weeks.

**Comment by chrisvest** [comment]
Netty releases are published directly to Maven Central, and I don't think we have any dependencies on bintray or jcenter. So this shouldn't impact us.

(closing because I think this answers the question; feel free to reopen if not)

**Comment by gemmellr** [comment]
@chrisvest @normanmaurer 

Though the releases may be published to Central directly, the main website has download links to bintray. It shut down on May 1st, so the site download links are currently broken.

See https://netty.io/downloads.html plus the Downloads menu dropdown on each page.

**Comment by normanmaurer** [comment]
@gemmellr good point... I will fix that

**Comment by normanmaurer** [comment]
Fixed by pointing the GitHub releases

**Comment by gemmellr** [comment]
@normanmaurer Each page still has a Downloads menu at the top with broken latest and previous releases links to Bintray. The downloads page still has a broken 'previous releases' link.

**Comment by normanmaurer** [comment]
@gemmellr now for real... I did forgot to push one file :/ Thanks a lot!
