### ISSUE TITLE
Identifying how a Channel got disconnected

### ISSUE THREAD

**Issue by a2l007** [netty/netty#11200]
My application has a `SimpleChannelUpstreamHandler` implementation and `channelDisconnected(ChannelHandlerContext context, ChannelStateEvent event)` gets invoked after a channel gets disconnected.
There are some unexpected disconnects happening and I'm trying to figure out why. Is there a way to identify how a Channel got disconnected?

**Comment by hyperxpro** [comment]
You can try to catch the exception if the client closes the connection with the RST frame.

**Comment by normanmaurer** [comment]
As @hyperxpro said... Also note the netty 3 is EOL for a long time.
