### ISSUE TITLE
`SslHandler#unwrap` sends `fireChannelRead` event BEFORE a notification for a handshake success

### ISSUE THREAD

**Issue by violetagg** [netty/netty#11201]
With change 0ef2f05373be323f8a70a8e343473cf9e6f49683 in some cases `fireChannelRead` event is sent BEFORE a notification for a handshake success

https://github.com/netty/netty/blob/3657805711668ff1249b4c19e227bedb94d55417/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L1359-L1371

In the comment above the code it is stated that the `fireChannelRead` should be sent AFTER a notification for a  handshake success, however the code never checks for `handshakeStatus`.

The issue is visible only with `SslProvider.OPENSSL`

### Expected behavior

`fireChannelRead` event is sent AFTER a notification for a  handshake success

### Actual behavior

`fireChannelRead` event is sent BEFORE a notification for a handshake success

### Steps to reproduce

Start `io.netty.example.http2.helloworld.server.Http2Server` and `io.netty.example.http2.helloworld.client.Http2Client` where the `SslProvider` is `SslProvider.JDK` => the example is working as expected.

Change the `SslProvider` to `SslProvider.OPENSSL` and ensure that there is a dependency to `netty-tcnative-boringssl-static` => the example is not working anymore.

### Netty version

4.1.64.Final-SNAPSHOT

### JVM version (e.g. `java -version`)

adopt-openjdk-1.8.0_292

### OS version (e.g. `uname -a`)

Mac OS

**Comment by violetagg** [comment]
With  a quick fix like this, the example above is working

```
diff --git a/handler/src/main/java/io/netty/handler/ssl/SslHandler.java b/handler/src/main/java/io/netty/handler/ssl/SslHandler.java
index 45d63bc319..a5a0901724 100644
--- a/handler/src/main/java/io/netty/handler/ssl/SslHandler.java
+++ b/handler/src/main/java/io/netty/handler/ssl/SslHandler.java
@@ -1367,7 +1367,7 @@ public class SslHandler extends ByteToMessageDecoder implements ChannelOutboundH
                 // Dispatch decoded data after we have notified of handshake success. If this method has been invoked
                 // in a re-entry fashion we execute a task on the executor queue to process after the stack unwinds
                 // to preserve order of events.
-                if (decodeOut.isReadable()) {
+                if (decodeOut.isReadable() && handshakePromise.isDone()) {
                     setState(STATE_FIRE_CHANNEL_READ);
                     if (isStateSet(STATE_UNWRAP_REENTRY)) {
                         executedRead = true;
```

**Comment by normanmaurer** [comment]
Will investigate tomorrow

**Comment by normanmaurer** [comment]
@violetagg thanks for the possible fix ... I will double check and see if I can get a unit test as well. Alternative you may want to beat me if you have some time 😉

**Comment by violetagg** [comment]
> @violetagg thanks for the possible fix ... I will double check and see if I can get a unit test as well. Alternative you may want to beat me if you have some time 😉

ok let me try something today
