### ISSUE TITLE
DNS resolver tries CNAME for non-A/AAAA queries

### ISSUE THREAD

**Issue by benevans** [netty/netty#11214]
### Expected behavior

If querying an non-A/AAAA record type, such as SRV or NAPTR, the operation should not try CNAME if no records are found.

### Actual behavior

When querying a non-existent SRV record, Netty's DNS resolver falls back to trying to lookup the CNAME record of the same name. But this makes no sense, as the results of a CNAME query are only going to refer to A/AAAA records. There is no way for a CNAME to refer to an SRV record or other record types.

The fallback to CNAME should only happen if the requested record type is A or AAAA.
 
### Steps to reproduce

Lookup an SRV record that doesn't exist, and observe in logs or packet capture that a CNAME query is also performed.

### Minimal yet complete reproducer code (or URL to code)

https://gist.github.com/benevans/910e5dd451899135267d21420b72e4dd

### Netty version

4.1.63.Final

### JVM version (e.g. `java -version`)

   openjdk version "11.0.9.1" 2020-11-04
   OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
   OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

### OS version (e.g. `uname -a`)

   Linux orogene 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
Yeah sounds like a bug... Seems like you are planing to contribute a PR :) Please do and I will review
