### ISSUE TITLE
why not my application show this log ,my http is not work

### ISSUE THREAD

**Issue by vxinv** [netty/netty#11229]
[55:41:912] [INFO] - com.xxg.vxinv.client.handler.VxinvClientHandler.channelRead(VxinvClientHandler.java:32) - client read len  529 , id 2

```
/**
 * Created by wucao on 2019/3/2.
 */

public class LocalProxyHandler extends VxinvCommonHandler {

    Logger Log = LoggerFactory.getLogger(LocalProxyHandler.class);

    private Short id;

    public LocalProxyHandler(Short id) {
        this.id = id;
    }


    @Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
        byte[] data = (byte[]) msg;
        Log.info("LocalProxyHandler read  Client bind write {}", data.length);
        LengthMessage message = new LengthMessage();
        message.setData(data);
        message.setId(id);
        message.setLength(data.length);
        ChannelHolder.clientHandler.getCtx().writeAndFlush(message);
    }

    @Override
    public void channelActive(ChannelHandlerContext ctx) throws Exception {
        Log.info("LocalProxy {} active", id);
        super.channelActive(ctx);

        ChannelHolder.channelGroup.add(ctx.channel());
        ChannelHolder.pm.put(id, ctx.channel().id().asLongText());
    }

}

**Comment by vxinv** [comment]
/**
 * 存放 channel handler 引用
 */
public class ChannelHolder {
    // 和client 链接 转发流量
    public static VxinvClientHandler clientHandler;
    // 监听本地连接的 channelHandler
    public static Map<Short, LocalProxyHandler> proxyClientHandlerMap = new ConcurrentHashMap<>(4);
    public static Map<Short, String> pm = new ConcurrentHashMap<>(4);
    public static ChannelGroup channelGroup = new DefaultChannelGroup(GlobalEventExecutor.INSTANCE);
}

**Comment by normanmaurer** [comment]
Sorry but you will need to provide some more details about the problem and what the exact questions is.

**Comment by vxinv** [comment]
Hello , I use Netty for TCP forwarding , But I found a problem that I couldn't solve。When my program first ran, everything was fine，
But after a few seconds, the traffic forwarding failed，I watched many times before I failed，A log will be printed before the program fails  Here is the printed log :   [55:41:912] [INFO] - com.xxg.vxinv.client.handler.VxinvClientHandler.channelRead(VxinvClientHandler.java:32) - client read len 529 , id 2

### Expected behavior
I expect my program can proxy http ，But the program will fail after a while，But it was OK at the beginning。
### Actual behavior
I expect my program can proxy http ，But the program will fail after a while，But it was OK at the beginning。
### Steps to reproduce

### Minimal yet complete reproducer code (or URL to code)

myCode url：https://github.com/vxinv/octor

### Netty version
4.1.42.Final
### JVM version (e.g. `java -version`)
java 1.8  
### OS version (e.g. `uname -a`)
mac  10.13.6

**Comment by vxinv** [comment]
I'm sure my HTTP program won't work after the log is printed, but TCP is normal

**Comment by normanmaurer** [comment]
Sorry but you will need to provide more details in terms of a reproducer etc. We can't review your whole code-base. Also you are using a very old netty version. Ensure you at least upgrade to the latest one and see if the problem persists

**Comment by vxinv** [comment]
OK, thank you very much for your reply，But I don't know what went wrong  ，Thank you again for your reply
