### ISSUE TITLE
HttpPostRequestDecoder consumes too much CPU

### ISSUE THREAD

**Issue by vietj** [netty/netty#11222]
### Expected behavior
`HttpPostRequestDecoder` consumes a reasonable amount of CPU.

### Actual behavior
`HttpPostRequestDecoder` consumes an unreasonable amount of CPU.

### Steps to reproduce

Create an HTTP server with Netty and upload a large file that will trigger the usage of `HttpPostRequestDecoder`

### Minimal yet complete reproducer code (or URL to code)

Use the reproducer https://github.com/vert-x3/vertx-web/issues/1937#issuecomment-832553750 here

### Netty version

4.1.60.Final but also later version and also previous version (but not 4.1.49.Final)

### JVM version (e.g. `java -version`)

N/A

### OS version (e.g. `uname -a`)

N/A

**Comment by normanmaurer** [comment]
@vietj can you test latest 4.1 branch ?

**Comment by vietj** [comment]
sure thing, I'll run the reproducer with the latest 4.1 branch

**Comment by vietj** [comment]
@normanmaurer the latest branch does not exhibit anymore the issue and provides a similar CPU consumption than 4.1.49.Final has

**Comment by normanmaurer** [comment]
@vietj perfect... I plan a release for next week.

**Comment by vietj** [comment]
good to hear @normanmaurer
