### ISSUE TITLE
AbstractDecoderTest instantiation and execution logic is probably racy 

### ISSUE THREAD

**Issue by slandelle** [netty/netty#11233]
### Expected behavior

`AbstractDecoderTest` should provide a robust base for extension.

### Actual behavior

`AbstractDecoderTest` relies on JUnit 4's experimental `Theories` to have parameterized tests.
It looks like the `Theories` runner heavily depends on calling static methods by reflection, bypassing the constructor, which the regular `Test` runner doesn't.

Methods in `AbstractDecoderTest` annotated `@DataPoints` are static, but rely on protected static non final fields that are initialized by the constructor.
Depending on the test, constructor might not be called. And I suspect data can be corrupted when tests run in parallel.

### Steps to reproduce

1. remove the @Test method in any class extending `AbstractDecoderTest` (so it should only execute the `Theories`.
2. run mvn test
3. NPE

### Minimal yet complete reproducer code (or URL to code)

See above

### Netty version

4.1.63.Final

### JVM version (e.g. `java -version`)

irrelevant

### OS version (e.g. `uname -a`)

irrelevant

**Comment by slandelle** [comment]
IMHO, the best solution is to upgrade to JUnit 5 and benefit from stable `@ParameterizedTest` instead of this experimental `@Theories` from unmaintained JUnit 4.

**Comment by normanmaurer** [comment]
@slandelle sure that sounds good :) You are fancy doing so ? As far as I know we can just use junit 5 stuff for new things but still run our old tests that are writing with junit 4. /cc @chrisvest

**Comment by slandelle** [comment]
> You are fancy doing so ?

Sorry, I'd love to be able to help, but I'm sure I won't have time any time soon :(

**Comment by chrisvest** [comment]
@normanmaurer Yes, junit 5 is already available.

**Comment by kashike** [comment]
#11306 covered the migration to JUnit 5 for `AbstractDecoderTest`.

**Comment by slandelle** [comment]
Closing, then. Thanks!
