### ISSUE TITLE
Download page links are broken

### ISSUE THREAD

**Issue by rschmitt** [netty/netty#11235]
The links on the [downloads page](https://netty.io/downloads.html) are returning 403 Forbidden:

* https://dl.bintray.com/netty/downloads/netty-4.1.63.Final.tar.bz2
* https://dl.bintray.com/netty/downloads/netty-4.0.56.Final.tar.bz2
* https://dl.bintray.com/netty/downloads/netty-3.10.6.Final-dist.tar.bz2

This may just be a transient outage of the hosting platform.

**Comment by normanmaurer** [comment]
will check

**Comment by astei** [comment]
This is because [Bintray shut down](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) earlier this month. As a workaround, one can use the [GitHub releases page](https://github.com/netty/netty/releases) to get the source code for all versions of Netty.

**Comment by normanmaurer** [comment]
Fixed by pointing to the GitHub releases.

**Comment by NiteshKant** [comment]
@normanmaurer we should perhaps change the README to replace download instruction with dependency inclusion like in the [quic repo](https://github.com/netty/netty-incubator-codec-quic#how-to-include-the-dependency)

**Comment by rschmitt** [comment]
Thanks for the reminder. Grabbing the artifacts from Maven Central works fine.
