### ISSUE TITLE
What are the side effects of using io.netty.buffer.checkBounds=false?

### ISSUE THREAD

**Issue by ninja-** [netty/netty#11249]
Hi,

I had a a look at what checkBounds=false does.
From what I see, it disables bound checks during change of writerIndex and readerIndex, disables automagic expansion of buffers (writeByte -> automatic expansion if it's out of space, right?), and during read/write it directly fetches memory at bufferAddress + readerIndex, for example(so could return garbage memory).
Is there any checklist to make sure that application code is ready to use the checkBounds=false flag while having no memory corruption in all edge cases?
For example, manually calling isReadable() every time before calling readByte(), or something?
And manually expanding buffers in case of no space to write?
Is every protocol parser in netty like HTTP etc. safe against checkBounds=false?

Also, in my opinion I think it would be good to be able to choose between bounds checking and not checking for different areas of code, for example by something like unwrap()? So you would have bound checking by default, but you can unwrap the buffer to get rid of it for performance-critical areas?

**Comment by normanmaurer** [comment]
@ninja- it basically it will remove all "safe-guards" which means you need to be 100% sure you never try to read / write out of bounds as otherwise you may corrupt memory etc.

**Comment by ninja-** [comment]
@normanmaurer  that much I know but it haven't answered the other questions :)

**Comment by chrisvest** [comment]
> Is every protocol parser in netty like HTTP etc. safe against checkBounds=false?

No, because we don't run tests with bounds checking off. You are kind of "on your own" when you turn it off.

**Comment by normanmaurer** [comment]
As @chrisvest said... its something you should only use if you basically own all decoders / encoders etc and are 100 sure. Also you should only use it if you really are sure its a bottle-neck. For most people it is not.

**Comment by ninja-** [comment]
I understand, but the main issue I am facing is that an application might mix both it's own fully safe decoders as we ll as netty HTTP handlers etc. and there is no way to turn it on only for specific ones

**Comment by normanmaurer** [comment]
Honestly I don't want to expose just another thing... Like I said I am sure 99% of users shouldn't care about bound checks.

**Comment by franz1981** [comment]
Hi @ninja- let me report some context from the PR I've sent to add this "feature":
https://github.com/netty/netty/pull/7521#issuecomment-360315624

> It is not a (common) user tool but IMO is pretty important as a benchmarking/test tool and in extreme cases as a proper tool...

As suggested by others, I suggest you to prove youself first that it worth to use it, considering the trade-off it bring, but users are left by their own while using it: it was meant to be exposed mostly for (micro)benchmarking reasons (and i'm the author of this, so I know it for sure ;) )
