### ISSUE TITLE
[Question] Assign executor according to the result of group by channel

### ISSUE THREAD

**Issue by jjz921024** [netty/netty#11257]
### Expected behavior
If i want to implememt this feature that some channel assign fix executor,
do i need to implement a custom EventExecutorChooser?
but, I can't get channel on method next()

There are any way to implement this feature? thank..

**Comment by NiteshKant** [comment]
If you want to use a specific `EventLoop` for a channel you can specify it in the `Bootstrap` using `bootstrap.group()`. As `EventLoop` also implements `EventLoopGroup` an `EventLoop` instance can directly be passed in the `group()` method. As a reference you can see [servicetalk](https://servicetalk.io) code [here](https://github.com/apple/servicetalk/blob/main/servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpConnector.java#L139-L161).
