### ISSUE TITLE
Netty frequently sends and receives messages, causing memory to increase slowly

### ISSUE THREAD

**Issue by xiaoxiaoshudeshu** [netty/netty#11258]
### Expected behavior
One thousand devices send heartbeat messages to the server every 5 seconds, and the server sends heartbeat messages back to the devices
### -----------------------------------------init class start--------------------------------------

package com.etv.manage.netty;

import java.net.InetSocketAddress;
import java.nio.charset.Charset;

import org.apache.http.util.TextUtils;
import org.apache.log4j.Logger;

import io.netty.bootstrap.ServerBootstrap;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.Unpooled;
import io.netty.channel.Channel;
import io.netty.channel.ChannelFuture;
import io.netty.channel.ChannelFutureListener;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.ChannelOption;
import io.netty.channel.ChannelPipeline;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.ServerSocketChannel;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.handler.codec.DelimiterBasedFrameDecoder;
import io.netty.handler.codec.LengthFieldBasedFrameDecoder;
import io.netty.handler.codec.LineBasedFrameDecoder;
import io.netty.handler.codec.http.HttpServerCodec;
import io.netty.handler.codec.serialization.ClassResolvers;
import io.netty.handler.codec.serialization.ObjectDecoder;
import io.netty.handler.codec.serialization.ObjectEncoder;
import io.netty.handler.codec.string.StringDecoder;
import io.netty.handler.codec.string.StringEncoder;
import io.netty.handler.stream.ChunkedWriteHandler;
import io.netty.util.CharsetUtil;
import io.netty.util.concurrent.DefaultEventExecutorGroup;
import io.netty.util.concurrent.EventExecutorGroup;

public class NettyInitTcpServer {
	private Logger logger = Logger.getLogger(this.getClass());
	private static final String TAG = "NettyTcpServer";
    private final int port = 7989;
    private Channel channel;

    private static NettyInitTcpServer instance = null;
    private NettyChannelListener<String> listener;
    //    private boolean connectStatus;
    private EventLoopGroup bossGroup;
    private EventLoopGroup workerGroup;
    private boolean isServerStart;

    private String packetSeparator;
    private int maxPacketLong = 1024;
//    private final static EventExecutorGroup excutor = new DefaultEventExecutorGroup(16);

    public void setPacketSeparator(String separator) {
        this.packetSeparator = separator;
    }

    public void setMaxPacketLong(int maxPacketLong) {
        this.maxPacketLong = maxPacketLong;
    }

    public static NettyInitTcpServer getInstance() {
        if (instance == null) {
            synchronized (NettyInitTcpServer.class) {
                if (instance == null) {
                    instance = new NettyInitTcpServer();
                }
            }
        }
        
        return instance;
    }

    private NettyInitTcpServer() {
    	
    }

    public void start() {
        new Thread() {
            @Override
            public void run() {
                super.run();
                bossGroup = new NioEventLoopGroup(1);
                workerGroup = new NioEventLoopGroup();
                try {
                    ServerBootstrap b = new ServerBootstrap();
                    b.group(bossGroup, workerGroup)
                            .channel(NioServerSocketChannel.class) // 5
                            .localAddress(new InetSocketAddress(port)) // 6
                            .childOption(ChannelOption.SO_KEEPALIVE, true)
                            .childOption(ChannelOption.SO_REUSEADDR, true)
                            .childOption(ChannelOption.TCP_NODELAY, true)
                            .childHandler(new ChannelInitializer<SocketChannel>() { // 7

                                @Override
                                public void initChannel(SocketChannel ch) throws Exception {
//                                	ch.pipeline().addLast(new StringEncoder(CharsetUtil.UTF_8));
//                                    if (!TextUtils.isEmpty(packetSeparator)) {
////                                        ByteBuf delimiter = Unpooled.copiedBuffer(packetSeparator.getBytes());
//                                        ByteBuf delimiter= Unpooled.buffer();
//                                        delimiter.writeBytes(packetSeparator.getBytes());
//                                        ch.pipeline().addLast(new DelimiterBasedFrameDecoder(maxPacketLong, delimiter));
//                                    } else {
//                                        ch.pipeline().addLast(new LineBasedFrameDecoder(maxPacketLong));
//                                    }
                                    ch.pipeline().addLast(new StringEncoder(CharsetUtil.UTF_8));
                                    ch.pipeline().addLast(new StringDecoder(CharsetUtil.UTF_8));
                                    ch.pipeline().addLast(new NettyServerHandler(listener));
                                }
                            });

                    // Bind and start to accept incoming connections.
                    ChannelFuture f = b.bind().sync(); // 8
                    logger.error(TAG+ NettyInitTcpServer.class.getName() + " started and listen on " + f.channel().localAddress());
                    isServerStart = true;
                    listener.onStartServer();
                    // Wait until the server socket is closed.
                    // In this example, this does not happen, but you can do that to gracefully
                    // shut down your server.
                    f.channel().closeFuture().sync(); // 9
                } catch (Exception e) {
                	logger.error(TAG, e);
                    e.printStackTrace();
                } finally {
                    isServerStart = false;
                    listener.onStopServer();
                    workerGroup.shutdownGracefully();
                    bossGroup.shutdownGracefully();
                }
            }
        }.start();

    }

    public void disconnect() {
        workerGroup.shutdownGracefully();
        bossGroup.shutdownGracefully();
    }

    public void setListener(NettyChannelListener<String> listener) {
        this.listener = listener;
    }

    public boolean isServerStart() {
        return isServerStart;
    }

    // 
    public boolean sendMsgToClient(Object data,Channel channel,ChannelFutureListener listener) {
        boolean flag = channel != null && channel.isActive();
        System.out.println("发送的clientId"+channel.id().asShortText());
        String separator = TextUtils.isEmpty(packetSeparator) ? System.getProperty("line.separator") : packetSeparator;
        if (flag) {
            channel.writeAndFlush(data + separator).addListener(listener);
        }
        return flag;
    }

    public boolean sendMsgToClient(String data) {
        boolean flag = channel != null && channel.isActive();
        if (flag) {
//			ByteBuf buf = Unpooled.copiedBuffer(data);
//            ByteBuf byteBuf = Unpooled.copiedBuffer(data + System.getProperty("line.separator"), //2
//                    CharsetUtil.UTF_8);
            String separator = TextUtils.isEmpty(packetSeparator) ? System.getProperty("line.separator") : packetSeparator;
            ChannelFuture channelFuture = channel.writeAndFlush(data + separator).awaitUninterruptibly();
            return channelFuture.isSuccess();
        }
        return false;
    }

    public void selectorChannel(Channel channel) {
        this.channel = channel;
    }
}

### -----------------------------------handle class start------------------------------------------

/**   
 * Copyright © 2019 yskj Tech Co., Ltd. All rights reserved.
 * 
 * @Package: com.etv.manage.netty 
 * @author: xya
 * @date: 2019年12月23日 下午7:29:17 
 */
package com.etv.manage.netty;

import java.util.Date;

import javax.annotation.PostConstruct;

import org.apache.log4j.Logger;
import org.springframework.stereotype.Component;

import com.etv.manage.utils.constantUtils.CommonConstant;
import com.etv.manage.utils.tool.ThreadPoolSingleton;

import io.netty.buffer.ByteBuf;
import io.netty.buffer.PooledByteBufAllocator;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelInboundHandlerAdapter;
import io.netty.channel.SimpleChannelInboundHandler;
import io.netty.util.ReferenceCountUtil;
import net.sf.json.JSONObject;

@Component
public class NettyServerHandler extends ChannelInboundHandlerAdapter {
		
		private Logger logger = Logger.getLogger(this.getClass());
	    private NettyChannelListener<String> mListener;
	    PooledByteBufAllocator allocator=new PooledByteBufAllocator(false);
	    
	
	    public static NettyServerHandler nettyserverhandler;
	   
	    @PostConstruct
	    public void init() {
	    	nettyserverhandler = this;
	    }
	    
	    public NettyServerHandler() {
			super();
		}

		public NettyServerHandler(NettyChannelListener<String> listener) {
	        this.mListener = listener;
	    }

		

	    @Override
	    public void exceptionCaught(ChannelHandlerContext ctx,Throwable cause) {
	    	logger.error("\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"+ctx.channel().id().asLongText()+"exception unlink<<<<<<<<<<<<<<<<<<<<<<<<<<");
	    	mListener.onExceptionChannelConnect(ctx.channel(),cause);
	    }

	  
	    public boolean acceptInboundMessage(Object msg) throws Exception {
	        return true;
	    }
	    

	    @Override
	    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
	    	String channelId = ctx.channel().id().asShortText();
    		NettyChannelMap.intsance().add(channelId, ctx.channel());
	    	logger.info("\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>online client【"+NettyChannelMap.intsance().size()+"】num<<<<<<<<<<<<<<<<<<<<<<<<<<");
//	  
	    	JSONObject jsonObj = new JSONObject();
	    	jsonObj.put("type", CommonConstant.WAKE_TYPE.getValue());// ping value
			jsonObj.put("code", CommonConstant.SERVER_ONLINE.getValue());
//			jsonObj.put("mac", clNo);
	    	ctx.writeAndFlush(jsonObj.toString());
	    	
	    	
		}

	
	    @Override
	    public void channelActive(ChannelHandlerContext ctx) throws Exception {
	    	logger.error("\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"+ctx.channel().id().asLongText()+"in link<<<<<<<<<<<<<<<<<<<<<<<<<<");
	        mListener.onChannelConnect(ctx.channel());
	    }

	    @Override
	    public void channelInactive(ChannelHandlerContext ctx) throws Exception {
	    	System.out.println(ctx.channel().id().asShortText()+"unlink");
//	    	logger.info("");
	    	logger.error("\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"+ctx.channel().id().asLongText()+"unlink<<<<<<<<<<<<<<<<<<<<<<<<<<");
	        mListener.onChannelDisConnect(ctx.channel());
	    }

		
	    
	    
}

### Netty version
4.1.28fin
### JVM version (e.g. `java -version`)
jdk1.8
### OS version (e.g. `uname -a`)
linux

**Comment by hyperxpro** [comment]
Please upgrade to the latest version of Netty and see if issue still persists.

**Comment by NiteshKant** [comment]
@xiaoxiaoshudeshu I am afraid you have to describe your problem in some more detail for us to help you. 

> frequently sends and receives messages ...

What messages are these? Netty does not automatically sends messages unless required by the protocol (like HTTP/2 control frames), you have to write to a channel for netty to send it to the peer. Netty will read messages when `AUTO_READ` option is set to `true`.

> causing memory to increase slowly

Which memory are you referring to? Are you storing read messages somewhere?

**Comment by xiaoxiaoshudeshu** [comment]
> @xiaoxiaoshudeshu恐怕您需要更详细地描述您的问题，以便我们为您提供帮助。
> 
> > 经常发送和接收消息...
> 
> 这些是什么消息？Netty不会自动发送消息，除非协议要求（例如HTTP / 2控制框架），否则您必须写入netty的通道才能将其发送给对等方。当`AUTO_READ`option设置为时，Netty将读取消息`true`。
> 
> > 导致记忆缓慢增加
> 
> 您指的是哪个记忆？您是否将已读邮件存储在某个地方？

It is the heartbeat message defined by yourself, sent on the same channel

**Comment by hyperxpro** [comment]
Please use English.

**Comment by xiaoxiaoshudeshu** [comment]
> Please use English.

It is the heartbeat message defined by yourself, sent on the same channel

**Comment by xiaoxiaoshudeshu** [comment]
> Please upgrade to the latest version of Netty and see if the issue still persists.

The new version will conflict with redis

**Comment by xiaoxiaoshudeshu** [comment]
> Please use English.
Report an error after changing to a new version
`
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    io.lettuce.core.resource.DefaultEventLoopGroupProvider.createEventLoopGroup(DefaultEventLoopGroupProvider.java:200)

The following method did not exist:

    io.netty.util.concurrent.DefaultEventExecutorGroup.<init>(ILjava/util/concurrent/ThreadFactory;)V

The method's class, io.netty.util.concurrent.DefaultEventExecutorGroup, is available from the following locations:

    jar:file:/C:/Users/Administrator.DESKTOP-J7P9047/.m2/repository/io/netty/netty-all/5.0.0.Alpha2/netty-all-5.0.0.Alpha2.jar!/io/netty/util/concurrent/DefaultEventExecutorGroup.class

The class hierarchy was loaded from the following locations:

    io.netty.util.concurrent.DefaultEventExecutorGroup: file:/C:/Users/Administrator.DESKTOP-J7P9047/.m2/repository/io/netty/netty-all/5.0.0.Alpha2/netty-all-5.0.0.Alpha2.jar
    io.netty.util.concurrent.MultithreadEventExecutorGroup: file:/C:/Users/Administrator.DESKTOP-J7P9047/.m2/repository/io/netty/netty-all/5.0.0.Alpha2/netty-all-5.0.0.Alpha2.jar
    io.netty.util.concurrent.AbstractEventExecutorGroup: file:/C:/Users/Administrator.DESKTOP-J7P9047/.m2/repository/io/netty/netty-all/5.0.0.Alpha2/netty-all-5.0.0.Alpha2.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of io.netty.util.concurrent.DefaultEventExecutorGroup

`

**Comment by hyperxpro** [comment]
Well, the latest version of Netty is 4.1.64.Final.

**Comment by xiaoxiaoshudeshu** [comment]
> Well, the latest version of Netty is 4.1.64.Final.

Tried this version and still the same will cause problems

**Comment by xiaoxiaoshudeshu** [comment]
> @xiaoxiaoshudeshu I am afraid you have to describe your problem in some more detail for us to help you.
> 
> > frequently sends and receives messages ...
> 
> What messages are these? Netty does not automatically sends messages unless required by the protocol (like HTTP/2 control frames), you have to write to a channel for netty to send it to the peer. Netty will read messages when `AUTO_READ` option is set to `true`.
> 
> > causing memory to increase slowly
> 
> Which memory are you referring to? Are you storing read messages somewhere?

It is the heartbeat message defined by yourself, sent on the same channel

**Comment by NiteshKant** [comment]
> It is the heartbeat message defined by yourself, sent on the same channel

Ok I don't think I follow, which heartbeat? If you feel this is a memory leak then please provide an explanation of your use case, up to date reproducer and a heap dump demonstrating the problem.
