### ISSUE TITLE
[Question] Is Netty 5 dead?

### ISSUE THREAD

**Issue by andreypfau** [netty/netty#11288]

**Comment by normanmaurer** [comment]
No its not... in fact I am about to pick up some tasks again together with @chrisvest and @NiteshKant

**Comment by hyperxpro** [comment]
@normanmaurer Can I work on Kernel Bypass thing? (DPDK)

**Comment by terrarier2111** [comment]
is it still planned to only support java 11 or are than any plans to support java 8 in any way shape or form?

**Comment by chrisvest** [comment]
@terrarier2111 Netty 4.1 would still be supported for some time after Netty 5 is out, so you can use that on Java 8. I expect it'll take a long time for Netty 4 usage to drop away.

**Comment by jreuben11** [comment]
**Netty guide** https://netty.io/wiki/user-guide.html states Netty 5 is **abandonded** and that 4 is the recommended version
looks like it was dropped a decade ago https://github.com/netty/netty/issues/4466
