### ISSUE TITLE
It seems that the 4.1.65 final release is source only

### ISSUE THREAD

**Issue by hervegirod** [netty/netty#11292]
### Expected behavior
The content of the release should contain the jar files for Netty

### Actual behavior
The content of the release contain the source code and the pom.xml files

### Steps to reproduce
look in the release zip file

### Minimal yet complete reproducer code (or URL to code)
N/A

### Netty version
4.1.65.final

### JVM version (e.g. `java -version`)
1.8

### OS version (e.g. `uname -a`)
N/A

**Comment by hervegirod** [comment]
The 4.1.65 final release sees to be source only (src and pom.xml content). The zip content is very different from the previous ones

**Comment by chrisvest** [comment]
Because Bintray shut down, so the download page now links to Github tag archives. Most people would use some sort of dependency management tool and download the binaries from Maven Central.

**Comment by hervegirod** [comment]
Ah ok!
