### ISSUE TITLE
transport-sctpmodule  tests are not in a working state

### ISSUE THREAD

**Issue by kashike** [netty/netty#11325]
The `transport-sctp` module tests are in the wrong directory (`src/main/test/io/...` instead of `src/test/java/io/...`) and are thus not being ran - they also do not compile, due to classes they use being removed and other validations.

**Comment by normanmaurer** [comment]
Actually these should be in `src/test/java`... let me fix this . Good catch!

**Comment by hyperxpro** [comment]
Do we really need SCTP in Netty 5?

**Comment by normanmaurer** [comment]
@hyperxpro maybe... maybe it will be moved out of the core netty branch.

**Comment by hyperxpro** [comment]
In my opinion, we should drop SCTP i. We've QUIC #rfc9000 which is superior to SCTP.
