### ISSUE TITLE
Feature request: Client proxy support

### ISSUE THREAD

**Issue by jasonbrittain** [netty/netty#1133]
Looking through both the docs and the code, I have not found a way to configure the Netty HTTP client to use a proxy.  I did find this discussion which suggests that Netty client doesn't currently implement it:

Netty Client and Proxy Server (StackOverflow)
http://stackoverflow.com/questions/14383017/netty-and-proxy-server-in-an-applet

If there's a way, could someone point it out?  If there's no implementation, then this issue is a feature request.

Thanks!

**Comment by vitaliy-kuzmich** [comment]
it is good to have transparent requests support(possibly some boolean vriable in constructor), currently io.netty.handler.proxy.HttpProxyHandler has just "CONNECT" method support, in some cases connect does not working with proxies.... 
HINT:
io.netty.handler.proxy.ProxyHandler:
   @Override
    public final void channelActive(ChannelHandlerContext ctx) throws Exception {
       // sendInitialMessage(ctx);
        setConnectSuccess();
        ctx.fireChannelActive();
    }

  public final void handlerAdded(ChannelHandlerContext ctx) throws Exception {
        this.ctx = ctx;
        addCodec(ctx);

        if (ctx.channel().isActive()) {
            // channelActive() event has been fired already, which means this.channelActive() will
            // not be invoked. We have to initialize here instead.
            setConnectSuccess();
            //sendInitialMessage(ctx);

**Comment by grational** [comment]
Please release this feature if possible: for what it is worth, this will avoid a massive rewriting of our microservices (our servers are currently migrating beyond a proxy). Thank you!

**Comment by vidhyashankarpaysafe** [comment]
Is this Feature merged? If so why is this issue still open?

**Comment by trustin** [comment]
Yes, long time ago. I don't remember why it is still open anymore. It's probably a good idea to open a new one if a follow-up is necessary. Thanks for pinging.
