### ISSUE TITLE
Null pointer occurs in ctx.channel.remoteAddress() in high concurrency scenarios

### ISSUE THREAD

**Issue by theodore414** [netty/netty#11355]
### Netty version
4.1.50

### JVM version (e.g. `java -version`)
JDK1.8

Null pointer occurs in ctx.channel.remoteAddress() in high concurrency scenarios

our handler extends SimpleChannelInboundHandler<>{}

**Comment by normanmaurer** [comment]
You will need to share the code and the stack trace at least

**Comment by theodore414** [comment]
> You will need to share the code and the stack trace at least

I can only take a screenshot for you for some reason sorry for that

![WechatIMG475](https://user-images.githubusercontent.com/35146274/120459083-70e81480-c3ca-11eb-9aa1-0ae254c227f5.jpeg)

**Comment by chrisvest** [comment]
Are you sure the NPE doesn't occur in your own code? `Channel.remoteAddress` can sometimes return `null`.

The stack trace you show doesn't have any `remoteAddress` call in it that we can see.

**Comment by normanmaurer** [comment]
Closing as this not seems to be a netty issue at all
