### ISSUE TITLE
[ByteBuf]May be there are something wrong about memory allocation strategy of PoolChunkList 

### ISSUE THREAD

**Issue by fantow** [netty/netty#11350]
Is this a wrong order when a ByteBuf wants to allocate memory.**I think the right order is that 75 -> 50 -> 25 -> 00 -> init，this order may be a perfer memory allocation strategy.**

![maybeamistake](https://user-images.githubusercontent.com/18530950/120407757-5be69380-c380-11eb-9391-9a0cc943a9b7.png)

May I pull a PR to fix it?

**Comment by fantow** [comment]
@chrisvest @normanmaurer

**Comment by chrisvest** [comment]
I don't know why it's like that, actually. It's been like that since @trustin added the initial pooled buffer allocator. Perhaps jemalloc does, or did do, something like that.

**Comment by fantow** [comment]
But this is really a wrong order of allocating memory.

@trustin Hello Trustin,how do you think about this allocate memory order?

**Comment by fantow** [comment]
@chrisvest @normanmaurer @trustin Hello,Is this a problem to be optimized?I found that in previous version,Netty didn't have a ChunkList to indicate 75% usage.So I am more likely understood it as a mistake when netty do something version iteration.
    I have completed and already test it.If it is not necessory,I will close this issue.

**Comment by trustin** [comment]
It's heuristic from the original jemalloc. When a chunk is already 75% full, it's likely that it may fail to find a run that fits. It is programmed to try 50% and others first because they have better chances.

**Comment by trustin** [comment]
Thanks for asking, though. :smile: Closing!
