### ISSUE TITLE
Recycler.WeakOrderQueue  drop Object hasBeenRecycled

### ISSUE THREAD

**Issue by pjzhong** [netty/netty#11353]
https://github.com/netty/netty/blob/d34212439068091bcec29a8fad4df82f0a82c638/common/src/main/java/io/netty/util/Recycler.java#L399

I am confuse why drop Object that already hasBeenRecycled？ It's didn't test the DefaultHandler.hasBeenRecycler field. 

should apply the same rule as this method?
https://github.com/netty/netty/blob/d34212439068091bcec29a8fad4df82f0a82c638/common/src/main/java/io/netty/util/Recycler.java#L727

### Netty version
4.1.65.Final

**Comment by normanmaurer** [comment]
@pjzhong not sure I follow... do you want to provide a PR with the idea ?

**Comment by pjzhong** [comment]
Here is my test_case
[recycler_test.zip](https://github.com/netty/netty/files/6682498/recycler_test.zip)
