### ISSUE TITLE
NoSuchMethodError checkNonEmptyAfterTrim

### ISSUE THREAD

**Issue by heixiaoma** [netty/netty#11356]
Exception in thread "main" java.lang.NoSuchMethodError: io.netty.util.internal.ObjectUtil.checkNonEmptyAfterTrim(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String; at io.netty.handler.codec.http.HttpMethod.<init>(HttpMethod.java:124) at io.netty.handler.codec.http.HttpMethod.<clinit>(HttpMethod.java:37)

<netty.version>4.1.65.Final</netty.version>

**Comment by NiteshKant** [comment]
Most likely you have mismatched versions of `common` and `http` module. This method was added recently.

**Comment by heixiaoma** [comment]
Thank you for your help. At present, I am using Netty-All Maven dependency. At present, it is used with the redisson framework, and it will report an error on startup.

**Comment by heixiaoma** [comment]
Netty all Maven dependencies should have the same module version, but compared with previous versions, some files, such as examples, are missing

**Comment by heixiaoma** [comment]
> Most likely you have mismatched versions of `common` and `http` module. This method was added recently.

hi

**Comment by trustin** [comment]
Could you try to dump the complete class path of your application? I bet you'll have both `netty-all` and `netty-common` with different version for example.

**Comment by heixiaoma** [comment]
> 您可以尝试转储应用程序的完整类路径吗？我敢打赌，例如，您将同时拥有`netty-all`和`netty-common`使用不同的版本。



> Could you try to dump the complete class path of your application? I bet you'll have both `netty-all` and `netty-common` with different version for example.



> Could you try to dump the complete class path of your application? I bet you'll have both `netty-all` and `netty-common` with different version for example.

**Comment by heixiaoma** [comment]
https://mvnrepository.com/artifact/io.netty/netty-all/4.1.65.Final
Netty/All In One » 4.1.65.Final

**Comment by heixiaoma** [comment]
> Could you try to dump the complete class path of your application? I bet you'll have both `netty-all` and `netty-common` with different version for example.
https://mvnrepository.com/artifact/io.netty/netty-all/4.1.65.Final
Netty/All In One » 4.1.65.Final

**Comment by sevenscorpio** [comment]
我把4.1.65换成4.1.48就没有这个问题了

**Comment by heixiaoma** [comment]
> 我把4.1.65然后4.1.48就没有这个问题了

你redission用最新版本也可以了
