### ISSUE TITLE
Counterintuitive behavior of method io.netty.buffer.AbstractByteBuf#readBytes(int)

### ISSUE THREAD

**Issue by laosijikaichele** [netty/netty#11354]
### Expected behavior
The following code should print both `true` or both `false`:
```
public static void main(String[] args) {
        ByteBuf heapBuffer =  new PooledByteBufAllocator(false).heapBuffer(1, 1).writeByte(1);

        ByteBuf buffer_a = heapBuffer.readBytes(0);
        ByteBuf buffer_b = heapBuffer.readBytes(1);

        System.out.println(buffer_a.isDirect());
        System.out.println(buffer_b.isDirect());
    }
```

### Actual behavior
`buffer_a.isDirect()` printed `true` ,
`buffer_b.isDirect()` printed `false`.

### Steps to reproduce
See above
### Minimal yet complete reproducer code (or URL to code)
See above
### Netty version
4.1
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
MacOS

**Comment by NiteshKant** [comment]
Usage of empty buffers (capacity = 0) in netty is optimized to return a static immutable buffer instance.  `heapBuffer.readBytes(0)` utilizes this optimization as the returned buffer has to be empty (reading 0 bytes). 

Netty also does further optimizations if it sees an empty buffer instance. So, although I agree that the behavior is not ideal but it may not be weird enough to require fixing.

**Comment by laosijikaichele** [comment]
@NiteshKant the immutable empty buffer instance is OK, but I wonder why the empty buffer always use a direct alloc, for example, the following code printed `true` ,which is more weird:
```
ByteBuf heapBuffer =  new PooledByteBufAllocator(false).heapBuffer(0, 0);

System.out.println(heapBuffer.isDirect());
```
The code wanted to create a heap buffer:`new PooledByteBufAllocator(false).heapBuffer(0, 0)` , but actually it gave a direct buffer?

**Comment by njhill** [comment]
See https://github.com/netty/netty/issues/2373#issuecomment-41648562 for the philosophical explanation :)

**Comment by laosijikaichele** [comment]
> See [#2373 (comment)](https://github.com/netty/netty/issues/2373#issuecomment-41648562) for the philosophical explanation :)

@njhill  Thanks for the referring, as quoted from Trustin(https://github.com/netty/netty/issues/2373#issuecomment-41648562):

> An empty buffer is neither heap not direct. Its capacity is 0 - it occupies no memory region theoretically. At the same time, an empty buffer is both heap and direct. It keeps an empty byte array and an empty direct buffer internally. It's a kind of special being.

If the empty buffer is neither heap not direct, then I think `emptyBuffer.isDirect()` should throw an `Exception` or something else? It is confusing to return a `true`/`false` for the method`emptyBuffer.isDirect()`, IMO.

**Comment by trustin** [comment]
> An empty buffer is neither heap not direct. Its capacity is 0 - it occupies no memory region theoretically. At the same time, an empty buffer is both heap and direct. It keeps an empty byte array and an empty direct buffer internally. It's a kind of special being.

Nope. An empty buffer is both heap and direct. :laughing: It has a real `byte[0]` and a direct memory address. Although the actually memory region will never be accessed. The array's reference itself and its length field is accessible though.

**Comment by trustin** [comment]
So, if we had `ByteBuf.isHeap()`, an empty buffer could have returned `true` for both.

**Comment by laosijikaichele** [comment]
@trustin, Thanks a lot for the explanation, it really makes sense someway. Maybe I can add this explanation to the doc of method `io.netty.buffer.EmptyByteBuf#isDirect`, so that more people can better understand it.

**Comment by trustin** [comment]
Great. Looking forward to your pull request :bow:
