### ISSUE TITLE
[codec-mqtt] Netty tries to interpret QOS level on CONNECT package

### ISSUE THREAD

**Issue by hylkevds** [netty/netty#11379]
The MQTT CONNECT package FIXED header contains only the MQTT Control Packet type in the first 4 bits. The remaining bits in the first byte are reserved. ([SPEC](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180841))
Currently, the MqttDecoder parses the fixed header the same for all packet types, and thus tries to interpret the reserved bits of the fixed header in the CONNECT packet:
https://github.com/netty/netty/blob/c78afbc4f13ac4d6cb488fb14b31379960f03fff/codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttDecoder.java#L166
 https://github.com/netty/netty/blob/c78afbc4f13ac4d6cb488fb14b31379960f03fff/codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttDecoder.java#L185 

Apparently, the HiveMQ client sets the remaining bits to all 1, resulting the MqttDecoder to try to interpret bits 2 + 3 of the reserved bits as "QOS 3" resulting in an exception.

### Expected behavior
Ignore reserved bits

### Actual behavior
tries to interpret reserved bits, resulting in an exception.
Caused by: java.lang.IllegalArgumentException: invalid QoS: 3

### Steps to reproduce
Send a CONNECT packet with the reserved bits set to 1

### Minimal yet complete reproducer code (or URL to code)
Working on it

### Netty version
netty-4.1.65

### JVM version (e.g. `java -version`)
11

### OS version (e.g. `uname -a`)
Linux

**Comment by normanmaurer** [comment]
@hylkevds sounds like a bug... are you able to provide a PR with a fix and unit test ?

**Comment by hylkevds** [comment]
Digging a bit deeper, it seems the problem is both in HiveMQ and Netty. The [spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180835) states:

> Where a flag bit is marked as “Reserved” in Table 2.2 - Flag Bits, it is reserved for future use and MUST be set to the value listed in that table [MQTT-2.2.2-1]. If invalid flags are received, the receiver MUST close the Network Connection

So technically, in this case Netty does the correct thing, for the wrong reason. Netty should complain if any of the reserved bits are non-zero, not only if it detects a QOS of 3.

**Comment by hylkevds** [comment]
The values of the bits of the fixed header depend on the messageType, as seen in [Table 2.2](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180835). I could implement the validation in two ways:
- with a `switch(messageType)`, has the advantage that the entire check is contained in MqttDecoder.decodeFixedHeader
- by adding a `checkHeader()` method in the MqttMessageType enum, which is cleaner.

Which method would you prefer?
