### ISSUE TITLE
HttpUtil.getCharset() fails for charset in double-quotes

### ISSUE THREAD

**Issue by jerrinot** [netty/netty#11370]
I understood from [RFC 7231](https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.1) the content-type header can have charset value in double-quotes. 
```
media-type = type "/" subtype *( OWS ";" OWS parameter )
type       = token
subtype    = token

The type/subtype MAY be followed by parameters in the form of name=value pairs.
parameter  = token "=" ( token / quoted-string )
```

### Expected behaviour
When the content-type header is set to `text/html; charset="utf-8"` then the charset is parsed correctly as utf-8.

### Actual behaviour
When the content-type header is set to `text/html; charset="utf-8"` then the charset is parsed incorrectly as default ISO-8859-1.

### Steps to reproduce
Change the [`testGetCharset()`](https://github.com/netty/netty/blob/65e1f0e27c99c226041a21373985f584958ec971/codec-http/src/test/java/io/netty/handler/codec/http/HttpUtilTest.java#L78) to look like this:
```java
@Test
public void testGetCharset() {
    String NORMAL_CONTENT_TYPE = "text/html; charset=utf-8";
    String UPPER_CASE_NORMAL_CONTENT_TYPE = "TEXT/HTML; CHARSET=UTF-8";
    String CHARSET_IN_DOUBLE_QUOTES = "text/html; charset=\"utf-8\"";

    HttpMessage message = new DefaultHttpResponse(HttpVersion.HTTP_1_1, HttpResponseStatus.OK);
    message.headers().set(HttpHeaderNames.CONTENT_TYPE, NORMAL_CONTENT_TYPE);
    assertEquals(CharsetUtil.UTF_8, HttpUtil.getCharset(message));
    assertEquals(CharsetUtil.UTF_8, HttpUtil.getCharset(NORMAL_CONTENT_TYPE));

    message.headers().set(HttpHeaderNames.CONTENT_TYPE, UPPER_CASE_NORMAL_CONTENT_TYPE);
    assertEquals(CharsetUtil.UTF_8, HttpUtil.getCharset(message));
    assertEquals(CharsetUtil.UTF_8, HttpUtil.getCharset(UPPER_CASE_NORMAL_CONTENT_TYPE));

    message.headers().set(HttpHeaderNames.CONTENT_TYPE, CHARSET_IN_DOUBLE_QUOTES);
    assertEquals(CharsetUtil.UTF_8, HttpUtil.getCharset(message));
    assertEquals(CharsetUtil.UTF_8, HttpUtil.getCharset(CHARSET_IN_DOUBLE_QUOTES));
}
```

### Netty version
b0d1bff64

**Comment by normanmaurer** [comment]
@NiteshKant can you please take a look ?

**Comment by NiteshKant** [comment]
@jerrinot thanks for reporting!

Here is the PR to fix it: https://github.com/netty/netty/pull/11373
