### ISSUE TITLE
io.netty.util.HashedWheelTimer.HashedWheelBucket#expireTimeouts

### ISSUE THREAD

**Issue by November22** [netty/netty#11386]
Should I first judge that the task has been cancelled?
——————from Google Translate
### Expected behavior
![image](https://user-images.githubusercontent.com/26109828/121763997-cfec1d00-cb72-11eb-975a-fbd01b4042d9.png)

### Actual behavior
![image](https://user-images.githubusercontent.com/26109828/121763929-4b010380-cb72-11eb-96d1-56dc41dd505b.png)

### Netty version
4.1.40
### JVM version (e.g. `java -version`)
1.8.0_131
### OS version (e.g. `uname -a`)
Darwin ***MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
This is fine as it is as if it is cancelled `timeout.expire()` will just return.
