### ISSUE TITLE
No constant for ssl protocol selection

### ISSUE THREAD

**Issue by danielbaniel** [netty/netty#11393]
This is a minor issue but one that I think would be easy to fix. Please educate me if there's a complexity or nuance that I'm not seeing.

Netty lets the user choose the tls version.

```
            clientSslContext = SslContextBuilder
                    .forClient()
                    .protocols("TSLv1.3")
                    ...
                    .build();
```

There's no constant/enum defined for this that I can find in netty. Should there be a public string/enum for customers to use when making this selection?

The only definition I can find is this constant but it is package private - https://github.com/netty/netty/blob/a98c60283b38830607780e039c7dd52715ec5814/handler/src/main/java/io/netty/handler/ssl/SslUtils.java#L66

**Comment by hyperxpro** [comment]
Enum sounds like a good idea. 

@normanmaurer WDYT? I can do a PR.

**Comment by NiteshKant** [comment]
Following the pattern of `ApplicationProtocolNames`[1] will keep it consistent, i.e. define a class containing the constants for the names instead of a java enum.

[1] https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/ApplicationProtocolNames.java

**Comment by hyperxpro** [comment]
@NiteshKant Sounds a good idea.
