### ISSUE TITLE
FullHttpRequest content

### ISSUE THREAD

**Issue by heixiaoma** [netty/netty#11399]
### Netty 

     <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.64.Final</version>
        </dependency>
4.1.64+
Content cannot be obtained
![image](https://user-images.githubusercontent.com/10923974/122520891-c5d08f80-d046-11eb-84ed-d4e70373ad38.png)

**Comment by normanmaurer** [comment]
@heixiaoma this makes sense... you should obtain the content before you pass it to the decoder and destroy it .
