### ISSUE TITLE
Tail tasks queue: configure separately from tasks queue

### ISSUE THREAD

**Issue by mostroverkhov** [netty/netty#11391]
IO transports (primarily epoll, but this also applies to kqueue, nio) cant be configured with separate `tail tasks` queue factory -
instead single queue factory is used for both normal tasks and tail tasks.

Their parent [SingleThreadEventLoop](https://github.com/netty/netty/blob/0d5774a82b470833c5f8a84fa4708142a4801f52/transport/src/main/java/io/netty/channel/SingleThreadEventLoop.java#L63) does have constructor accepting both `taskQueue` and `tailTaskQueue`.

I use `SingleThreadEventLoop.executeAfterEventLoopIteration(Runnable)` for internal tasks executed strictly from eventloop,
and would prefer to configure queue other than MPSC.

**Comment by NiteshKant** [comment]
@mostroverkhov SGTM, would you like to send a PR?
