### ISSUE TITLE
[Question]  Why does my netty is unresponsible after two blocked request?

### ISSUE THREAD

**Issue by ykalay** [netty/netty#11396]
### Expected behavior
I expect I/O Threads to keep consuming requests.
### Actual behavior
After 2 blocked requests. It starts to not accepting requests. Even If I am using 16 Threads as a child worker Thread
### Steps to reproduce
1-) Send open the websocket request
2-) On the Server side block the in the coming event before handshake for 20 Secs (In My real case, It is a blocked JDBC call before the handshake. I need to validate the incoming request with querying DB before opening the socket)
3-) Do It above Steps two times
4-) For requests after 3, the server starts to not answering until the first blocking request done.
### Minimal yet complete reproducer code (or URL to code)
```
@Override
    protected void channelRead0(ChannelHandlerContext channelHandlerContext, HttpRequest httpRequest) {
    Thread.sleep(20000); // Represents my blocked logic before handshake
    // Handsake or not with result
    Do stuff...
    }
    
EventLoopGroup bossGroup = new NioEventLoopGroup(1);
EventLoopGroup workerGroup = new NioEventLoopGroup();

ChannelPipeline pipeline = socketChannel.pipeline();
        pipeline.addLast(new HttpObjectAggregator(65536));
        pipeline.addLast(HTTP_CODEC.value(), new HttpServerCodec());
        .
        .
        .
```
### Netty version
4.1.59.Final
### JVM version (e.g. `java -version`)
1.8 don't be mad at me :P

I am passing blocked business logic to the custom thread pool. But, In the handshake case, I can not do that. and After two blocked requests my netty server is unresponsible until the first one ends. Is there any good way to handle the blocked handshake logic without block child threads.

**Comment by hyperxpro** [comment]
You should never block I/O threads else you'll end up with weird problems. Better use `ExecutorService` for costly operations.

**Comment by ykalay** [comment]
Yes. I am doing that. I am running my blocking logics from a separate thread except for the Handshake phase. 
For handshake pahse: Is there any way to handle the handshake phase from another thread with asynchronously?

**Comment by hyperxpro** [comment]
Well, if you wanna control WebSocket handshake then you should extend the implementation class and do it.

**Comment by hyperxpro** [comment]
If you can explain in little more detail about use case and all, I can help.

**Comment by ykalay** [comment]
Sure, Below I shared the sample code. When I do the handshake like this (async without blocking I/O Thread). It does not work. Is there an option to not block the I/O thread and doing blocked business logic before the handshake for example JDBC call?.
'''
@Override
    protected void channelRead0(ChannelHandlerContext channelHandlerContext, HttpRequest httpRequest) {
		Thread handshakeWorker = new Thread(() -> {
            // For example my blocked logic works here before handshake
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            // And after It is okay I do handshake or not with result of the blocked process
            WebSocketDecoderConfig webSocketDecoderConfig = getDecoderConfig();
            WebSocketServerHandshaker handShaker =
                    new WebSocketServerHandshaker13(getRemoteURL(httpRequest), null, webSocketDecoderConfig);
            handShaker.handshake(channelHandlerContext.channel(), httpRequest);
        });
        handshakeWorker.start();

    }
'''

**Comment by ykalay** [comment]
so what I want to do
- I do not want to block IO Thread
- I want to do some blocking logics(JDBC call) before handshake
- with the result of the blocking call I wan to do handshake or not

**Comment by hyperxpro** [comment]
Well, the business logic looks good. As far I can understand, when you block and wait for database operation to complete, the client is getting times out.

Like this:
12:00:00 - Client fired WebSocket handshake request
12:00:01 - Your app makes call to database.
12:00:05 - Client didn't get any response, times out.
12:00:07 - Your database call is finished
12:00:08 - You try to complete handshake but client is already gone.

**Comment by ykalay** [comment]
Yes. but even if I switch the JDBC call with Thread.sleep(500). The above code does not work.

**Comment by ykalay** [comment]
But when I do the process without creating a new thread. It works. Even If, I sleep It for 10 secs or more than 10. but The I/O Threads are pausing and stop consuming

**Comment by hyperxpro** [comment]
Aaaaaaaaaaaaa, I gotcha. You're using 'SimpleChannelInboundHandler'. It'll release Http Request as soon as it finishes processing channelRead0. (Even before your logic finishes in 500ms).

Use ChannelInboundHandler.

**Comment by ykalay** [comment]
Wow. but how do we do the handshake without FullHttpRequest? Is there any documentation/resource about that?

**Comment by ykalay** [comment]
Thanks for the help @hyperxpro It was about to retain/release the message as you said. Very thanks for the answer to my question
