### ISSUE TITLE
[feature request] support GMSSL

### ISSUE THREAD

**Issue by wujimin** [netty/netty#11406]
openssl already support GMSSL algorithm:
https://www.openssl.org/docs/man1.1.1/man7/SM2.html

to support GMSSL, need to modify https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslUtils.java#L279  
* add code: `|| buffer.getShort(offset + 1) == 0x101`
* add comments: or GMSSLv1.0 or GMSSLv1.1

```
if (tls) {
    // SSLv3 or TLS or GMSSLv1.0 or GMSSLv1.1 - Check ProtocolVersion
    int majorVersion = buffer.getUnsignedByte(offset + 1);
    if (majorVersion == 3 || buffer.getShort(offset + 1) == 0x101) {
        // SSLv3 or TLS or GMSSLv1.0 or GMSSLv1.1
        packetLength = unsignedShortBE(buffer, offset + 3) + SSL_RECORD_HEADER_LENGTH;
        if (packetLength <= SSL_RECORD_HEADER_LENGTH) {
            // Neither SSLv3 or TLSv1 (i.e. SSLv2 or bad data)
            tls = false;
        }
    } else {
        // Neither SSLv3 or TLSv1 (i.e. SSLv2 or bad data)
        tls = false;
    }
}
```

**Comment by normanmaurer** [comment]
I would be happy to review a PR

**Comment by hyperxpro** [comment]
Would you explain how it'll be beneficial to use `GMSSL` and how it's better than `TLSv1.3`?

**Comment by wujimin** [comment]
Sorry, i didn't research this, just because a specific customer requires this feature.

**Comment by wujimin** [comment]
> I would be happy to review a PR

Ok, i'll try
