### ISSUE TITLE
[Netty 4] How do I work with attributes?

### ISSUE THREAD

**Issue by RumoEL** [netty/netty#11401]
### Netty version
4

how to create a connection property?
how to check that there is a property?
How do I get the value of a property?
how to remove a property?

what need to store:

enum hostType; // worker, client
Double healthStatus

**Comment by RumoEL** [comment]
public class ServerHandler extends ChannelInboundHandlerAdapter {

public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
//todo
}

}

**Comment by NiteshKant** [comment]
`ctx.channel()` gives you the associated `Channel` instance which implements [`AttributeMap`](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/AttributeMap.java). You can use the `AttributeMap` interface to get/set attributes for the channel. Here is an example of setting attributes:

https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2StreamChannelBootstrap.java#L252
