### ISSUE TITLE
Native-image build failure when using codec-http on GraalVM 21.2 dev

### ISSUE THREAD

**Issue by gradinac** [netty/netty#11427]
### Description of the issue
Including `codec-http` in the project and building a native-image out of it using a GraalVM 21.2 nightly can result in:
```
...
[native-tests:26191]    (objects):  30,812.60 ms,  6.77 GB
[native-tests:26191]   (features):   4,280.68 ms,  6.77 GB
[native-tests:26191]     analysis:  86,171.65 ms,  6.77 GB
Error: Class initialization of io.netty.handler.codec.compression.BrotliDecoder failed. Use the option --initialize-at-run-time=io.netty.handler.codec.compression.BrotliDecoder to explicitly request delayed initialization of this class.
```
Usage of `Brotli` is hidden behind this check (https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpContentDecompressor.java#L70):
```
        if (Brotli.isAvailable() && BR.contentEqualsIgnoreCase(contentEncoding)) {
            return new EmbeddedChannel(ctx.channel().id(), ctx.channel().metadata().hasDisconnect(),
              ctx.channel().config(), new BrotliDecoder());
        }
```
However, while parsing the bytecode of this method, native-image will see a new instance of `BrotliDecoder` being created and, as `io.netty` is marked for build-time initialization, try to eagerly initialize it. If `Brotli` is not available, this can lead to a failure during class linking (in this particular case, because `com.aayushatharva.brotli4j.decoder.DecoderJNI` isn't on the classpath), resulting in a failed image build.

### Steps to reproduce
The easiest way to reproduce this is using `spring-native` samples:
```
export JAVA_HOME=<path-to-graalvm-21.2-dev>
export PATH=$JAVA_HOME/bin:$PATH
git clone https://github.com/spring-projects-experimental/spring-native.git
cd spring-native/samples/data-elasticsearch/
git checkout 49239a7fa24e09bbc91b943df579394fe74ef12c # Necessary because of an existing workaround on `main`
./build.sh
```

### Netty version
4.1.65.Final

### JVM version (e.g. `java -version`)
Reproducible on both GraalVM 21.2 nightlies and 21.3 dev, Java 11

### OS version (e.g. `uname -a`)
Reproducible on Linux-AMD64, running Ubuntu 20.04

**Comment by sdeleuze** [comment]
We had to do a similar update on Spring side so +1 from my POV.
