### ISSUE TITLE
Websocket connections fails when headers are case sensitive

### ISSUE THREAD

**Issue by Jerry29** [netty/netty#11456]
Trying to access a third party web  application having websocket connections through spring cloud gateway

All http requests are success but websocket connections fails with **_`io.netty.handler.codec.http.websocketx.WebSocketClientHandshakeException: Invalid handshake response getStatus: 404`_** 

While examining the packets observed that request headers are sent in lower case letters (upgrade, connection and sec-websocket-key) from netty > io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13

` headers.set(HttpHeaderNames.UPGRADE, HttpHeaderValues.WEBSOCKET).set(HttpHeaderNames.CONNECTION, HttpHeaderValues.UPGRADE).set(HttpHeaderNames.SEC_WEBSOCKET_KEY, key);`
       
Unfortunately the third party web application I am trying to access is expecting case sensitive headers. Is there a way I can override these headers?

 Netty version :  reactor-netty 1.0.8

JDK 1.8

OS : Ubuntu 20.04

**Comment by hyperxpro** [comment]
HTTP Headers are case-insensitive, as per RFC. If the third-party is make it case-sensitive then it's an RFC violation and you should use custom `WebSocketClientHandshake` to achieve it.

**Comment by Jerry29** [comment]
@hyperxpro Can you please provide me a reference?  I am trying to create a custom class by extending WebSocketClientHandshaker13. Is it what u meant ?

**Comment by slandelle** [comment]
@Jerry29 You should report this issue to the broken third party application so they fix it instead of trying to fork the valid implementation in Netty.

**Comment by hyperxpro** [comment]
Yeah, extending is also 1 way. I'm not familiar with Spring Cloud Gateway so I cannot provide an exact solution. But you should add a handler above `WebSocketClientHandshake`. 

But as @slandelle said, reporting broken RFC implementation is an ideal solution.

**Comment by Jerry29** [comment]
@slandelle @hyperxpro I had reported it to their technical team. In my scenario this third party application can be from vendors. So just want to make sure it doesn't break even if it is not fixed in their end.

**Comment by violetagg** [comment]
> @slandelle @hyperxpro I had reported it to their technical team. In my scenario this third party application can be from vendors. So just want to make sure it doesn't break even if it is not fixed in their end.

In my opinion the third party component that violates the RFC should be fixed

**Comment by Jerry29** [comment]
@slandelle @hyperxpro @violetagg observed another issue, for websocket requests alone Authorization header is missing .

**Comment by hyperxpro** [comment]
Can you show the code?

**Comment by Jerry29** [comment]
spring:
  main:
    web-application-type: reactive
  profiles:
    active: dev
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      httpclient:
        pool:
          max-idle-time: 10s
      ssl:
        useInsecureTrustManager: true
      filter:
        StripPrefix: 1
        remove-non-proxy-headers:
          headers:
            - Keep-Alive
            - TE
            - Trailer
            - Transfer-Encoding
            - Upgrade
            - Connection
            - Host
      routes:
        - id: http_requests
          uri: http://192.168.0.125:5554
          predicates:
            - Path=/**
        - id: ws_requests
          uri: ws://192.168.0.125:5554
          predicates:
            - Path=/websocket/**

**Comment by Jerry29** [comment]
@hyperxpro Have pasted my application.yml. Do you need any other details ?

**Comment by violetagg** [comment]
@Jerry29 May be check this one https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#building-a-simple-gateway-by-using-spring-mvc-or-webflux

```
First-class support is provided for “sensitive” headers (by default, cookie and authorization), which are not passed downstream, and for “proxy” (x-forwarded-*) headers.
```

However I think that this second question is not related to the original issue and you should continue that second discussion with SCG :)

**Comment by Jerry29** [comment]
@violetagg I raised a different issue for that https://github.com/spring-cloud/spring-cloud-gateway/issues/2289

**Comment by Jerry29** [comment]
@violetagg @hyperxpro any help on https://github.com/spring-cloud/spring-cloud-gateway/issues/2289

**Comment by hyperxpro** [comment]
Drop me an email. Lemme help you of-the-track. :)

**Comment by Jerry29** [comment]
@hyperxpro Done.

**Comment by normanmaurer** [comment]
I think this can be closed now.
