### ISSUE TITLE
[question] getting all sessions

### ISSUE THREAD

**Issue by resresd** [netty/netty#11458]
how to get all sessions (connected to the server / connected by the client)

by analogy in apache mina:

### in handlers:
public class MyHandler extends IoHandlerAdapter {

@Override
public void messageReceived(IoSession session, Object message) throws Exception {
Map<Long, IoSession> sessionsExc = session.getService().getManagedSessions();
}	

}
### in handlers acceptor:
Map<Long, IoSession> sessionsExc =getMyHandler().getAcceptor().getManagedSessions();	

### Netty version
4.1.65.Final

**Comment by NiteshKant** [comment]
I am not sure about apache mina's terminology but what you are saying seems like a `Channel` in netty. By default, netty does not store all created channels (implicitly by accepting a server channel or explicitly by creating a channel from the client) but it provides a utility of [`ChannelGroup`](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/group/ChannelGroup.java) which you can use to store them yourself.

**Comment by resresd** [comment]
In which places can track connection and disconnection of the session?
needed to save to the list

**Comment by resresd** [comment]
![clientHandler](https://user-images.githubusercontent.com/86285598/124663529-bef4aa00-de99-11eb-88dc-ea36e7af6291.png)
![clientInit](https://user-images.githubusercontent.com/86285598/124663533-c025d700-de99-11eb-8641-3882b9b750de.png)
![serverInit](https://user-images.githubusercontent.com/86285598/124663535-c0be6d80-de99-11eb-9f93-3931d7928e25.png)

**Comment by resresd** [comment]
yes, you got it right about IoSession and Channel

**Comment by resresd** [comment]
here is another 1 question: netty doesn't see classes from other maven dependencies, I have to specify at least 1 classloader from my library
see serverInit && clientInit :
ch.pipeline().addLast(new ObjectDecoder(ClassResolvers.softCachingConcurrentResolver(CheckPacket.class.getClassLoader())));

**Comment by NiteshKant** [comment]
For client you will do something like this to establish a channel: 

https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/qotm/QuoteOfTheMomentClient.java#L49

So tracking creation is associated with the call to `bind()`

Fo server you can you do that in the `initChannel()` method of the handler [you provided](https://github.com/netty/netty/issues/11458#issuecomment-875064027).

For either client/server you can implement `channelInactive()` method in any of your [`ChannelInboundHandler`](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/ChannelInboundHandler.java#L43) to track disconnects.

**Comment by NiteshKant** [comment]
> netty doesn't see classes from other maven dependencies

Netty does not do anything special here. This sounds like some problem with your local setup.
