### ISSUE TITLE
Complie transport-native-unix-common subproject encounter fatal error: 'netty_jni_util.h' file not found

### ISSUE THREAD

**Issue by huibinliupush** [netty/netty#11478]
### Expected behavior

build success

### Actual behavior

[INFO] --- maven-antrun-plugin:1.8:run (build-native-lib) @ netty-transport-native-unix-common ---
[INFO] Executing tasks

main:
     [exec] mkdir -p /myNettyHome/netty/transport-native-unix-common/target/native-objs-only
     [exec] clang -o /myNettyHome/netty/transport-native-unix-common/target/native-objs-only/netty_unix_buffer.o -c src/main/c/netty_unix_buffer.c -O3 -Werror -Wno-attributes -fPIC -fno-omit-frame-pointer -Wunused-variable -fvisibility=hidden -I/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_40.jdk/Contents/Home/include/darwin -Itarget/netty-jni-util/src/c
     [exec] In file included from src/main/c/netty_unix_buffer.c:17:
     [exec] src/main/c/netty_unix_util.h:23:10: fatal error: 'netty_jni_util.h' file not found
     [exec] #include "netty_jni_util.h"
     [exec]          ^~~~~~~~~~~~~~~~~~
     [exec] 1 error generated.
     [exec] make: *** [/myNettyHome/netty/transport-native-unix-common/target/native-objs-only/netty_unix_buffer.o] Error 1
### Steps to reproduce

cd netty
mvn clean install -Dmaven.test.skip=true

### Netty version
4.1.56.Final
### JVM version (e.g. `java -version`)
1.8.0_40
### OS version (e.g. `uname -a`)
macOS BigSur 11.3

**Comment by sgammon** [comment]
@huibinliupush How did you solve this?
