### ISSUE TITLE
GraalVM Native Image compilation fails related to BrotliDecoder

### ISSUE THREAD

**Issue by perezd** [netty/netty#11477]
I know Netty recently supported integrating with GraalVM native images and I think the recent Brotli has silently broken the native image support.

This class needed to be added to the `--initialize-at-run-time` stanza for netty, but I don't know where it belongs:
```
io.netty.handler.codec.compression.BrotliDecoder
```

When I did that manually as a workaround everything compiled as expected.

**Comment by hyperxpro** [comment]
Check: https://github.com/netty/netty/pull/11428

**Comment by perezd** [comment]
Ha! yay, fixed at head. I'll just wait for the next version to be released, thanks!
