### ISSUE TITLE
Possible bug in PoolThreadCache

### ISSUE THREAD

**Issue by VladimirKempik** [netty/netty#11481]
### Expected behavior
no jvm crash
### Actual behavior
jvm crash
### Steps to reproduce
no reproducer 
### Netty version
4.1.51
### JVM version (e.g. `java -version`)
Zulu11.43+22-SA (11.0.9+11) (build 11.0.9+11-LTS)
### OS version (e.g. `uname -a`)
OS:CentOS Linux release 7.8.2003 (Core)
uname:Linux 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64

I was working on a JVM crash and I suspect it's a netty bug

jvm crashes when G1GC processes an object and this object has bad "next" value

inspect 0x7fc1800ebf60
instance of Oop for java/lang/ref/WeakReference @ 0x00007fc1800ebf60 @ 0x00007fc1800ebf60 (size = 48)
<<Reverse pointers>>:
_mark: 140464753441755
_metadata._klass: InstanceKlass for java/lang/ref/WeakReference
referent: Oop for java/lang/Thread @ 0x00007fc18006f248 Oop for java/lang/Thread @ 0x00007fc18006f248
queue: Oop for java/lang/ref/ReferenceQueue$Null @ 0x00007fbca100f7c8 Oop for java/lang/ref/ReferenceQueue$Null @ 0x00007fbca100f7c8
next: ** BAD OOP **7fb85457a40000** **
discovered: null null

the value for "next" is left shifted ( by 8 bits) address of JavaThread
  0x00007fb85457a400 JavaThread "data-server-tcp-socket-worker-1301" daemon [_thread_in_native, id=214144, stack(0x00007fb2b9ac0000,0x00007fb2b9bc1000)]

the object 0x7fc1800ebf60 (java.lang.ref.WeakReference\<Thread\>) was created by netty
Here is path to roots for this object (NOTE: visualvm shows null instead of bad OOP values)

<img width="1026" alt="path_to_roots2" src="https://user-images.githubusercontent.com/69576004/125285650-8afb0800-e323-11eb-842a-e200d72fd86f.png">

I suspect the netty might have some issues when working with j.l.r.WeakReference\<Thread\> in Recycler.java

**Comment by hyperxpro** [comment]
Please use the latest version of Netty and see if the issue still persists.

**Comment by normanmaurer** [comment]
Also this might be a JVM bug.

**Comment by chrisvest** [comment]
@VladimirKempik What Netty settings are you using? Since you're on Java 11, I guess you don't have Unsafe enabled, correct? Do you use NIO channels or something else?

If Unsafe usage is disabled, and that you're using NIO channels, and still see the problem then it's very likely to be a JVM bug.
I recommend you try upgrading your JVM first and see if that fixes it.

**Comment by hyperxpro** [comment]
> Since you're on Java 11, I guess you don't have Unsafe enabled, correct?

Java 11 has Unsafe enabled.

```
15 Jul 2021 20:06:27.448 [main] DEBUG i.n.u.i.PlatformDependent0 - -Dio.netty.noUnsafe: false
15 Jul 2021 20:06:27.448 [main] DEBUG i.n.u.i.PlatformDependent0 - Java version: 11
15 Jul 2021 20:06:27.450 [main] DEBUG i.n.u.i.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
15 Jul 2021 20:06:27.450 [main] DEBUG i.n.u.i.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
15 Jul 2021 20:06:27.451 [main] DEBUG i.n.u.i.PlatformDependent0 - java.nio.Buffer.address: available
```

**Comment by chrisvest** [comment]
@hyperxpro On Java 11, you need an `--add-opens` command line flag to access Unsafe. Not sure how many do that in prod.

**Comment by normanmaurer** [comment]
@chrisvest as far as I know this is not true... you only need it for `jdk.internal.misc.Unsafe` but not for `sun.misc.Unsafe`.

**Comment by franz1981** [comment]
I can confirm what @normanmaurer and @hyperxpro said here: on JCTools Jdk 11 just work with sun misc Unsafe OOTB

**Comment by VladimirKempik** [comment]
netty came as part of aluxio, the only netty related option in args was
-Dorg.apache.ratis.thirdparty.io.netty.allocator.useCacheForAllThreads=false
will try to check if -Dio.netty.noUnsafe=true will change anything ( I don't have a reproducer locally)
the issue is reproducable and always happens with netty's object of type WeakRefence<Thread> ( "next" field), and it's always  - proper oop pointer left shifted by 8 bits. Such stable behaviour made me think JVM may not be cause of this.

**Comment by normanmaurer** [comment]
@VladimirKempik keep us posted

**Comment by VladimirKempik** [comment]
I will try, I don't possess the reproducer tho.

**Comment by VladimirKempik** [comment]
-Dio.netty.noUnsafe=true on netty 4.1.51 haven't helped, next is netty upgrade.

**Comment by chrisvest** [comment]
Is the `-Dio.netty.noUnsafe=true` configuration actually picked up, though?
What does the log say?

You said the only other Netty option is `-Dorg.apache.ratis.thirdparty.io.netty.allocator.useCacheForAllThreads=false` and that looks like Netty has been shaded and package names have been modified.
So that makes me wonder if the `noUnsafe` option needs to be modified too.

**Comment by chrisvest** [comment]
Also, we don't have any code in Netty that touches the `WeakReference.next` field, so to me it sounds more likely to be a JVM bug related to weak reference handling.

**Comment by VladimirKempik** [comment]
will try to see if -Dorg.apache.ratis.thirdparty.io.netty.noUnsafe helps

it's not common for JVM to have object pointer shifted left by 8 bits ( I haven't seen such in my 6 years of jvm bugs analyzing experience). And this always happens with netty's object. Hence my guess is some deserialization issue in netty (if there is any)

**Comment by chrisvest** [comment]
@VladimirKempik did you find any more clues to this?

If we're able to eliminate the use of sun.misc.Unsafe as the cause here, then the next suspect is (again) a JVM bug - perhaps related to interactions with weak reference handling.
A JVM update might have already fixed it. But also, Netty 4.1.71 will include a rewritten Recycler that does not use any weak references, so that might also make it go away if it hasn't already.

**Comment by VladimirKempik** [comment]
That thing got resolved. And AFAIR it required update of some software component. Sadly I can't say for now was it Netty or Not.
