### ISSUE TITLE
epollEventLoop no way to set ioRatio

### ISSUE THREAD

**Issue by lawnight** [netty/netty#11493]
cause send data far more than read data in my server, so  i want to set ioratio in epollEventLoop，but i find no way to do it。setIoRatio method in EpollEventLoopGroup.java is deprecated.

```java
//EpollEventLoopGroup.java
  /** @deprecated */
  @Deprecated
  public void setIoRatio(int ioRatio) {
      if (ioRatio <= 0 || ioRatio > 100) {
          throw new IllegalArgumentException("ioRatio: " + ioRatio + " (expected: 0 < ioRatio <= 100)");
      }
  }
```

after some dig, this pull #7834 "decouple schedule tasks from epoll_wait life cycle " really helps，but sadlly this change reverted in #9561 @normanmaurer 

i wonder if there were some ways to set IoRatio or there's plan to implement some thing like #7834
sorry for my poor english. 

### Netty version
4.1.65 final
### OS version (e.g. `uname -a`)
linux

**Comment by NiteshKant** [comment]
The `setIoRation()` method on the `EpollEventLoopGroup` is deprecated but it is [present](https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java#L267) and applicable on the `EpollEventLoop` class.

**Comment by lawnight** [comment]
> The `setIoRation()` method on the `EpollEventLoopGroup` is deprecated but it is [present](https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java#L267) and applicable on the `EpollEventLoop` class.

thank you for reply , i found the way to set ioRatio. though EpollEventLoop class not public , i only can put my class in io.netty.channel.epoll package to invoke this method.a litter tricky.

**Comment by normanmaurer** [comment]
@lawnight just do it on the `EpollEventLoopGroup`. This will apply the setting for all the `EpollEventLoop` instances it contains.

**Comment by normanmaurer** [comment]
Closing...

**Comment by lawnight** [comment]
> @lawnight just do it on the `EpollEventLoopGroup`. This will apply the setting for all the `EpollEventLoop` instances it contains.

in fact , `EpollEventLoopGroup` just check parameters not apply the setting
```Java

//EpollEventLoopGroup.java
  /** @deprecated */
  @Deprecated
  public void setIoRatio(int ioRatio) {
      if (ioRatio <= 0 || ioRatio > 100) {
          throw new IllegalArgumentException("ioRatio: " + ioRatio + " (expected: 0 < ioRatio <= 100)");
      }
  }

```
