### ISSUE TITLE
netty doesn't use maximum cpu even though it has room and things to do, much waiting at epollWaitNoTimerChange

### ISSUE THREAD

**Issue by mouse500** [netty/netty#11492]
I'm writing a network intensive WebFlux application. When receiving request, application requests and recieves something with another external server and then reply to original requester. I'm talking about the WebFlux application, and I'm using WebClient when call to external server.

Application's performance is not that satisfiable. I think it should touch the maximum of CPU resource, maximum TPS at maximum CPU. But it shows low tps, cpu is just at 30 ~ 40%.  Can we check why it does not use CPU any more to get more TPS, even though it has more room to execute more requests.

It waits a lot at many threads, like this...
{
  "threadName": "reactor-http-epoll-3",
  "threadId": 20,
  "blockedTime": -1,
  "blockedCount": 8,
  "waitedTime": -1,
  "waitedCount": 0,
  "lockName": null,
  "lockOwnerId": -1,
  "lockOwnerName": null,
  "inNative": true,
  "suspended": false,
  "threadState": "RUNNABLE",
  "stackTrace": [
    {
      "methodName": "epollWait",
      "fileName": "Native.java",
      "lineNumber": -2,
      "className": "io.netty.channel.epoll.Native",
      "nativeMethod": true
    },
    {
      "methodName": "epollWait",
      "fileName": "Native.java",
      "lineNumber": 148,
      "className": "io.netty.channel.epoll.Native",
      "nativeMethod": false
    },
    {
      "methodName": "epollWait",
      "fileName": "Native.java",
      "lineNumber": 141,
      "className": "io.netty.channel.epoll.Native",
      "nativeMethod": false
    },
    {
      "methodName": "epollWaitNoTimerChange",
      "fileName": "EpollEventLoop.java",
      "lineNumber": 290,
      "className": "io.netty.channel.epoll.EpollEventLoop",
      "nativeMethod": false
    },
    {
      "methodName": "run",
      "fileName": "EpollEventLoop.java",
      "lineNumber": 347,
      "className": "io.netty.channel.epoll.EpollEventLoop",
      "nativeMethod": false
    },
    {...

### Expected behavior
CPU reaches 100% and  shows good TPS

### Actual behavior
CPU just stays at 30~40%, and shows low TPS

### Steps to reproduce
reproducing codes :  https://github.com/mouse500/perfwebf

/workloadwexcall : workload using external call

external call is implemented with simple nodejs server 

jmeter to call above api with more than 200 threads.

### Netty version
netty-transport-native-epoll-4.1.52.Final

### JVM version (e.g. `java -version`)
java 1.8.0_292
spring boot 2.3.4.RELEASE, WebFlux, WebClient

**Comment by NiteshKant** [comment]
Since this is using WebFlux/reactor have you tried asking that community where the bottleneck could be?

**Comment by mouse500** [comment]
I didn't ask that community but I can try.
----

The reason why I'm trying to talk about this here.
When I capture a thread dump when situation going on(low cpu, low tps),
I can see 70~80% of all worker threads show above stacktrace,  not any other point of WebClient or reactor thing.
  
  io.netty.channel.epoll.Native.epollWait
  ...
  io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange
  ...

So, I thought the bottleneck seems here, epollWait~epollWaitNoTimerChange.



Please give your valuable opinion.
Thank you very much

**Comment by NiteshKant** [comment]
Netty is an EventLoop based library, so it waits for I/O or other tasks to be available to process. If you see eventloop threads waiting in netty's internal stacks, it most likely because there is no I/O work available to do.

**Comment by mouse500** [comment]
Thank you for your opinion~

Yes,  that is exactly what I expected too.
It can be thought that it because there is no I/O work available to do.

That's why I prepare a very simple backend server and get it on local network with the WebFlux application.
(I also tried with many backend server,  and simple backend server in local env.  all is same result)
The application use cpu 30% while backend server use cpu under 5%

Backend server which is prepared in this sample project(https://github.com/mouse500/perfwebf) is about
just static result nodejs app(15k size dummy result)

===
another question.
Then, is it better that I need to think of this issue as network performance at AWS EC2?
I don't think you are a right person for this question, but just begging your opinion.
Thank you very much.

**Comment by violetagg** [comment]
@mouse500 I will encourage you to upgrade as this version Spring Boot 2.3.4.RELEASE is pretty old.

**Comment by mouse500** [comment]
@violetagg Ok,  Thank you,  I will try.
Actaully, I already tried with various version of Spring Boot, and JDK version, Linux Distribion.
Anway,  will try with the latest version.

Now, I think this is not about some other issue.
I will look around something else more.

Thank you very much.

**Comment by mouse500** [comment]
Thank you for all
