### ISSUE TITLE
Decorate Runnable / Callables Task.

### ISSUE THREAD

**Issue by kevinten10** [netty/netty#11491]
Hello netty team.

As mentioned by #2759, #6524 and #8680. 

Does the netty community plan to implement the feature “_decorate Runnable / Callables when submitted to the EventExecutor / EventLoop_“?

I currently use netty4 and I hope to expand the `Runnable`. 

If it makes sense, I can achieve this PR.

Thanks.

**Comment by NiteshKant** [comment]
The way to achieve this today is by extending/delegating the existing eventloop implementations. Although, doing so makes it harder to use as channel types are coupled with eventloop types. If you do control all your usages of EventLoop it may be doable. Netty 5 makes such extensions easier and AFAIK we do not intend to improve this for 4.x version.

**Comment by kevinten10** [comment]
Thanks for your reply, I already understand the community’s plan.
