### ISSUE TITLE
BoringSSL + TLSv1.2 client side stateful session resumption doesn't work

### ISSUE THREAD

**Issue by slandelle** [netty/netty#11505]
### Expected behavior

TLSv1.2 state session resumption should work when using BoringSSL just like it does when using Java's SSLContext.

When sending a subsequent ClientHelllo, netty should send the previous Session ID.

### Actual behavior

When using BoringSSL, Netty always send `Session ID Length: 0`.

### Steps to reproduce

* Send 2 requests with Netty based client to google.com (enforce TLSv1.2 protocol), separated by a pause of 10 seconds to trigger keep-alive idle timeout so the initial connection is closed and the second request will trigger a second TLS handshake.
* Capture traffic with wireshark
* Compare results with JDK and OPENSSL providers: the former properly sets the Session ID from the first Server Hello, the latter always sends `Session ID Length: 0`

### Minimal yet complete reproducer code (or URL to code)

https://github.com/slandelle/netty-ssl-resumption

### Netty version

* netty 4.1.66.Final
* netty-tcnative-boringssl-static 2.0.40.Final

### JVM version (e.g. `java -version`)

1.8.0_292-b10

### OS version (e.g. `uname -a`)

Darwin Kernel Version 20.5.0

**Comment by slandelle** [comment]
I've created a pure netty reproducer.

**Comment by slandelle** [comment]
@normanmaurer Do you have any idea about what's going on? Am I doing something wrong?

**Comment by normanmaurer** [comment]
I had no time yet to check... will check and come back to you.

**Comment by slandelle** [comment]
Thanks. Please let me know if I can be of any help.

**Comment by normanmaurer** [comment]
@slandelle so this is expected as we disable session caching when using the native SSL implementation by default due a JDK bug that was only be fixed recently. If we would enable it by default it would most likely make things very hard to debug as the bug is triggered on the remote peer when the JDK implementation for SSL is enabled. More details can be found here:

https://github.com/netty/netty/pull/10994

So if you really want you can enable it via a system property or by explicit do so on the `OpenSslContext`.

**Comment by slandelle** [comment]
@normanmaurer Indeed, session resumption is properly triggered once the System prop is enabled, thanks a lot!

> due a JDK bug that was only be fixed recently

Do you have a reference to the JDK ticket? Your thread on the JDK mailing list suddenly comes to a halt and the JDK issue you referenced (https://bugs.openjdk.java.net/browse/JDK-8241248 that was indeed fixed in the last update batch) doesn't exactly have the same stacktrace.

**Comment by normanmaurer** [comment]
@slandelle it is in fact the one you linked.

**Comment by slandelle** [comment]
Awesome, thanks!
