### ISSUE TITLE
netty doesn't support DNS refresh

### ISSUE THREAD

**Issue by AngryMills** [netty/netty#11519]
### Expected behavior
We use spring-boot-starter-data-redis to connect redis with domain name，when redis server down, we switch DNS of domain name，but it doesn't work
### Actual behavior
I check the code,whether io.netty.netty-resolver-dns or io.netty.netty-resolver save dns cache after successful parsing.
When will cache refresh? Maybe try for a few times or make a schedule timer to update the cache?

### Netty version
4.1.65.Final
### JVM version (e.g. `java -version`)
jdk 1.8
### OS version (e.g. `uname -a`)
windows 10/Centos 7

Thanks for answering,have a nice day!

**Comment by skyguard1** [comment]
@normanmaurer How about adding a method to manually clear `resolveCache`, `authoritativeDnsServerCache` and `cnameCache`?

**Comment by hyperxpro** [comment]
This is expected because a DNS query response should be cached till TTL. Lowering TTL is a good way to ensure the freshness of cached responses.

**Comment by normanmaurer** [comment]
@skyguard1 it is already possible via `dnsCache().clear()` etc.

**Comment by shyr** [comment]
Can we manually specify dns cache TTL by using JVM_OPT? or, can we also use `networkaddress.cache.ttl` with netty dns resolver?
