### ISSUE TITLE
[Question][4.1.66.Final] [JSON{DECODER/ENCODER}]

### ISSUE THREAD

**Issue by JavLock** [netty/netty#11524]
### Netty version
4.1.66.Final
how to send objects as json

JavaObject(Serializable)->Encoder(to Json)->network->Decoder(to JavaObject) ->JavaObject

server:
![aaa](https://user-images.githubusercontent.com/87483305/127265676-8fff82fc-af97-4ee7-a195-624272134bb0.png)

client:
![aaa2](https://user-images.githubusercontent.com/87483305/127265754-1003d0db-9af9-45f9-8f65-795b7d5bb07a.png)

**Comment by JavLock** [comment]
trace:
![aaa3](https://user-images.githubusercontent.com/87483305/127265846-93df4f96-2797-49af-99b8-88dbc4b14bf2.png)

**Comment by fredericBregier** [comment]
As far as I understand the decoder implemented in Netty:
- There is only the decoder, used without any other handler before: the assumption is that the received stream is a string
- It is up to the sender part to decide which implementation is needed (Jackson, Google...) to transform an object to Json string
- ObjectEncoder and ObjectDecoder are not concerned: they (de)serialize objects, not in Json format

On my own experiments, I use Jackon to both transform Object to Json and reverse, and I send a packet with the form as:

`length{Json}`, meaning first an integer to know the length of the packet, then waiting to have the full string to parse using Jackson

- Coder: serialize to Json with Jackon, write first the length of byte arrays (don't forget the Charset) and put the length at first
- Decoder: using `LengthFieldBasedFrameDecoder` for instance at first handler, that transforms the stream into the final String (first item being the length), then using back Jackson to revert to Json object

You can use any Json codec for that.
