### ISSUE TITLE
BoringSSL + TLSv1.2 client side SSL renegociation fails

### ISSUE THREAD

**Issue by slandelle** [netty/netty#11529]
### Expected behavior

BoringSSL based SSLEngine should support SSL renegociation out of the box like the JDK one.

### Actual behavior

SSLEngine and connection crashes during renegociation.

This issue was originally reported against Gatling, see https://github.com/gatling/gatling/issues/4120 for more details.

### Steps to reproduce

See pure Netty reproducer below.

### Minimal yet complete reproducer code (or URL to code)

https://github.com/slandelle/netty-ssl-renegociation

### Netty version

4.1.66.Final

### JVM version (e.g. `java -version`)

openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

### OS version (e.g. `uname -a`)

Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
As far as I remember we don't support renegotiation when using the OpenSSL / BoringSSL based engines   because these are considered not secure anymore.

https://boringssl.googlesource.com/boringssl/+/refs/heads/master/include/openssl/ssl.h#4056

**Comment by slandelle** [comment]
>  If \|ssl\| is a server, peer-initiated renegotiations are *always* rejected and this function does nothing.

> There is no support in BoringSSL for initiating renegotiations as a client or server.

Here, Netty is client side and the initiator is the server. Also, this request works fine with Chrome, whose TLS implementation is BoringSSL.

Doesn't renegotiation only bring security issues when the initiator is the client, not the server?

**Comment by normanmaurer** [comment]
I suspect we would need to enable it explicit for BoringSSL:

https://boringssl.googlesource.com/boringssl/+/6b6e0b20893e2be0e68af605a60ffa2cbb0ffa64/PORTING.md#tls-renegotiation

**Comment by slandelle** [comment]
Indeed.

Does it looks feasible to you to introduce a new option to be passed through `SslContextOption` to configure the underlying BoringSSL?

**Comment by normanmaurer** [comment]
Yeah I guess something like this. That said I think we will also need to add some changes to `ReferenceCountedOpenSslEngine`

**Comment by slandelle** [comment]
I'm off on vacation tonight, so I'll only be able to have a look in a few weeks. Thanks for your insights!

**Comment by normanmaurer** [comment]
@slandelle no worries... I will also be on vacation soon 😆

**Comment by slandelle** [comment]
Again??? You're just back! 😆

**Comment by normanmaurer** [comment]
Let me pick this up this week again

**Comment by normanmaurer** [comment]
This is also related to https://github.com/apple/swift-nio-ssl/pull/111

**Comment by normanmaurer** [comment]
tcnative change that is needed: https://github.com/netty/netty-tcnative/pull/654
