### ISSUE TITLE
Http2 ReferenceCountUtil.release(request, refCount) can not real release 

### ISSUE THREAD

**Issue by linking12** [netty/netty#11522]
### Expected behavior
  when cpu use 100%, directBufer will release success when I'm sure have called ReferenceCountUtil.release 
### Actual behavior
  not release
### Steps to reproduce
 none
### Minimal yet complete reproducer code (or URL to code)
 none
### Netty version
4.1.52.Final
### JVM version (e.g. `java -version`)
JDK8
### OS version (e.g. `uname -a`)
CenterOs

Log:
![image](https://user-images.githubusercontent.com/4882172/127191768-5aeeeba4-76ff-4839-b443-487eb4fe82ff.png)

My release Code:

```
 public void releaseHttpRequest() {
        if (originalRequest == null)
            return;
        logger.info("will release copy httpRequest, request is: " + ProxyUtils.appendRequest(originalRequest));
        while (ReferenceCountUtil.refCnt(originalRequest) > 0) {
            ReferenceCountUtil.release(originalRequest);
        }
    }
```
My question：

If the CPU uses 100%, will the release job fail to work properly? 
If the answer is yes, how to make sure release job with high priority?

**Comment by hyperxpro** [comment]
> If the CPU uses 100%, will the release job fail to work properly?

Yes, `ReferenceCounted#release` will work under any circumstance regardless of system load.

> If the answer is yes, how to make sure release job with high priority?

No way.

**Comment by linking12** [comment]
> > If the CPU uses 100%, will the release job fail to work properly?
> 
> Yes, `ReferenceCounted#release` will work under any circumstance regardless of system load.
> 
> > If the answer is yes, how to make sure release job with high priority?
> 
> No way.

Thanks for your reply @hyperxpro  

can you check my screenshot log?  I'm sure have call  ReferenceCountUtil.release, But the log tell me " LEAK: ByteBuf.release() was not called " , The only explanation when system cpu is use 100%, The  ByteBuf.release() is not normal.

**Comment by hyperxpro** [comment]
As per the screenshot, ByteBuf is released at 21:59 and exception was thrown at 22:06, there are 7 minutes approx and as per my experience, it is enough for ByteBuf to be released even under extreme system load.

I'd suggest doing something like this:
```java
        ByteBuf byteBuf = Unpooled.buffer();
        int refCount = buf.refCnt();
        ReferenceCountUtil.release(byteBuf, refCount);
```

You should show the code for more detailed review.

**Comment by linking12** [comment]
> As per the screenshot, ByteBuf is released at 21:59 and exception was thrown at 22:06, there are 7 minutes approx and as per my experience, it is enough for ByteBuf to be released even under extreme system load.
> 
> I'd suggest doing something like this:
> 
> ```java
>         ByteBuf byteBuf = Unpooled.buffer();
>         int refCount = buf.refCnt();
>         ReferenceCountUtil.release(byteBuf, refCount);
> ```
> 
> You should show the code for more detailed review.

Thank you again @hyperxpro 

Step1:  copy and save

```
 private final Map<Integer, HttpFiltersAdapter> httpFiltersAdapter = Maps.newConcurrentMap();

  private ConnectionState doReadHTTPInitial(HttpRequest httpRequest) {
        // Make a copy of the original request
        HttpRequest currentCopyRequest = copy(httpRequest);
        HttpFiltersAdapter currentFilters =  new HttpFiltersAdapter(copyRequest, ctx);
        int streamId = getStreamIdFromRequest(httpRequest);
        this.httpFiltersAdapter.put(streamId, currentFilters);
}
```

HttpFiltersAdapter.class
```

 private final HttpRequest originalRequest;

 public HttpFiltersAdapter(HttpRequest originalRequest, ChannelHandlerContext ctx) {
        this.clientCtx = ctx;
        this.originalRequest = originalRequest;
        this.servletRequest = new NettyHttpServletRequest((FullHttpRequest)originalRequest, ctx);
        this.traceId = StringUtils.replaceEach(TrackingUtils.getTraceIdFromRequest(servletRequest),
            new String[] {"(", ")", "="}, new String[] {"", "", "-"});
        this.pinPointId = servletRequest.getHeader("pinpoint-trace-id");
        this.timeOutCircuitBreaker = TimeOutCircuitBreaker.getInstance();
  }
  public void releaseHttpRequest() {
        if (originalRequest == null)
            return;
        logger.info("will release copy httpRequest, request is: " + ProxyUtils.appendRequest(originalRequest));
        while (ReferenceCountUtil.refCnt(originalRequest) > 0) {
            ReferenceCountUtil.release(originalRequest);
        }
    }

```

Step2: find httpFiltersAdapter and call releaseHttpRequest

```
 public void releaseHttpRequest(HttpRequest request, boolean isProxyRespond) {
        boolean firstUpgradeRequest = false;
        EventLoop channelEventLoop = super.channel.eventLoop();
        try {
            if (request == null) {
                this.httpFiltersAdapter.forEach((streamerId, httpFiltersAdapter) -> {
                    httpFiltersAdapter.releaseHttpRequest();
                });
                this.httpFiltersAdapter.clear();
            } else {
                int streamId = getStreamIdFromRequest(request);
                HttpFiltersAdapter removedHttpFiltersAdapter = this.httpFiltersAdapter.get(streamId);
                if (removedHttpFiltersAdapter != null) {
                    removedHttpFiltersAdapter.releaseHttpRequest();
                    this.httpFiltersAdapter.remove(streamId);
                } else {
                    LOG.error("removedHttpFiltersAdapter == null! streamId: {}, request: {}", streamId,
                        ProxyUtils.appendRequest(request));
                }
            }
        }

````

Troubleshoot step：
    By x-trace-id to find which request；
  
![image](https://user-images.githubusercontent.com/4882172/127197911-fbc09f90-d73b-4e79-aeca-6e5332f3b507.png)

![image](https://user-images.githubusercontent.com/4882172/127198072-ca7f0e73-20a4-4604-8f67-e7ad746a525e.png)

**Comment by linking12** [comment]
![image](https://user-images.githubusercontent.com/4882172/127327346-ae7fd931-8e3e-4b04-a1f6-d441de347924.png)

@hyperxpro I can not understand this phenomenon， I make sure have call release, but log say fail to release, and then memory leak;


```
 if (request == null)
            return;
        int refCount = ReferenceCountUtil.refCnt(request);
        if (refCount > 0) {
            ReferenceCountUtil.safeRelease(request, refCount);
        } else {
            ReferenceCountUtil.safeRelease(request, 1);
```

**Comment by hyperxpro** [comment]
I can't tell exactly what is wrong with your code but from a quick look, it looks like the way you're making a copy and storing it.

**Comment by linking12** [comment]
I think this is netty http2 bug

![image](https://user-images.githubusercontent.com/4882172/127654909-ff7567d2-5e84-4aa9-aa1e-1560a4de112b.png)

call code:

```
  HttpFiltersAdapter removedHttpFiltersAdapter = this.allHttpFiltersAdapter.get(streamId);
                if (removedHttpFiltersAdapter != null) {
                        HttpRequest copyRequest = removedHttpFiltersAdapter.getCopyHttpRequest();
                        LOG.info("Will release copy httpRequest, request is: " + ProxyUtils.appendRequest(copyRequest));
                        boolean releaseSuccessed = super.releaseHttpRequest(copyRequest);
                        if (releaseSuccessed) {   // Notice: releaseHttpRequest return true
                            this.allHttpFiltersAdapter.remove(streamId);
                        }
                }
```
releaseHttpRequest code
```
 protected boolean releaseHttpRequest(HttpRequest request) {
        if (request == null)
            return true;
        int refCount = ReferenceCountUtil.refCnt(request);
        if (refCount > 0) {
            try {
                return ReferenceCountUtil.release(request, refCount);
            } catch (Throwable t) {
                LOG.warn("Failed to release a message: {} (decrement: {})", request, refCount, t);
            }
        }
        return true;
    }
```

I'm call  ReferenceCountUtil.release(request, refCount) and return success, but cause memory leak..

**Comment by linking12** [comment]
My fault, is something wrong happened PooledByteBufAllocator

**Comment by hyperxpro** [comment]
Good to know that the issue is resolved. :)
