### ISSUE TITLE
Why not use directbuffernocleaner by default in JDK 11.

### ISSUE THREAD

**Issue by wjm0729** [netty/netty#11532]
Why Platformdependent.usedirectbuffernocleaner()  is false by default in JDK 11. in other word why the default value is false of function PlatformDependent0.explicitTryReflectionSetAccessible0() in jdk11. the function code is :

`
 PlatformDependent0.java

    private static boolean explicitTryReflectionSetAccessible0() {
        // we disable reflective access
        return SystemPropertyUtil.getBoolean("io.netty.tryReflectionSetAccessible", javaVersion() < 9);
    }
`

what trouble will I have? If I set  -Dio.netty.tryReflectionSetAccessible=true in JDK11.

Thanks !

### JVM version (e.g. `java -version`)
  openjdk version "11.0.11" 2021-04-20
  OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
  OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

**Comment by chrisvest** [comment]
If the try set accessible is enabled, but then fails at runtime due to the increased protections in JDK 11, you will just get a message printed to the log.

**Comment by wjm0729** [comment]
Thank for your answer !  @chrisvest 

As we all know, "directbuffernocleaner" has higher performance than GC. I enabled it in the my netty application (jdk11). At present, everything seems to be fine, but I'm worried about whether the default setting of netty (using GC but using directbuffernocleaner) means other errors, not just avoiding jdk11's enhanced security access exceptions.

**Comment by chrisvest** [comment]
It should not cause any trouble as long as you are fine with log messages that might contain stack traces.

**Comment by wjm0729** [comment]
OK, Thank you very much !

**Comment by wjm0729** [comment]
OK, Thank you very much !
