### ISSUE TITLE
DatagramChannel join without a network interface could use the channel option multicast interface instead of guessing from the local address

### ISSUE THREAD

**Issue by vietj** [netty/netty#11541]
### Expected behavior

`DatagramChannel#joinGroup(multicastAddress)` calls `DatagramChannel.joinGroup(multicastAddress, networkInterface, source)` with the same network interface set on the channel options.

The code would look like

```java
        try {
            return joinGroup(
                    multicastAddress,
                    config().getNetworkInterface(),
                    null, promise);
        } catch (SocketException e) {
            promise.setFailure(e);
        }
        return promise;
```

### Actual behavior

`DatagramChannel#joinGroup(multicastAddress)` calls `DatagramChannel.joinGroup(multicastAddress, networkInterface, source)` with `NetworkInterface.getByInetAddress(localAddress().getAddress())` that sometimes returns the `null` reference.

### Steps to reproduce

Obvious

### Minimal yet complete reproducer code (or URL to code)

Obvious

### Netty version

Most

**Comment by NiteshKant** [comment]
this sounds reasonable to me, @vietj you want to send a PR, I am happy to review.

**Comment by normanmaurer** [comment]
@vietj PTAL https://github.com/netty/netty/pull/11585
