### ISSUE TITLE
Make `PcapWriteHandler` support files bigger than 2 GB

### ISSUE THREAD

**Issue by hyperxpro** [netty/netty#11543]
### Expected behavior
`PcapWriteHandler` should support large files, say 10 GB or 1 TB.

### Actual behavior
Currently, `PcapWriteHandler` can only support files up to 2 GB because it uses 32-bit Integer.

### Steps to reproduce
N/A

### Minimal yet complete reproducer code (or URL to code)
Just capture data big enough to exceed 2 GB.

### Netty version
4.1.66.Final

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_302"
OpenJDK Runtime Environment Corretto-8.302.08.1 (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM Corretto-8.302.08.1 (build 25.302-b08, mixed mode)

### OS version (e.g. `uname -a`)
Windows 10 Pro x64

**Comment by NiteshKant** [comment]
@hyperxpro are the fields in question `sendSegmentNumber` and `receiveSegmentNumber`[1]? 

I see that we do not guard against integer overflow while accumulating bytes in these fields[2], perhaps we can do that before supporting larger payloads?

[1] https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/pcap/PcapWriteHandler.java#L97-L103
[2] https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/pcap/PcapWriteHandler.java#L284

**Comment by hyperxpro** [comment]
Yes, we need to guard them against overflow. Norman did share swift-nio pcap where they fixed larger payloads and overflow. Lemme try to find it.

**Comment by hyperxpro** [comment]
Here: https://github.com/apple/swift-nio-extras/pull/85
