### ISSUE TITLE
Flaky test: io.netty.channel.ThreadPerChannelEventLoopGroupTest

### ISSUE THREAD

**Issue by hyperxpro** [netty/netty#11551]
### Expected behavior
There are multiple instances when the build stalled at `io.netty.channel.ThreadPerChannelEventLoopGroupTest` test and kept running forever until it was interrupted by GitHub Actions for consuming 6 hours of runtime.

### Actual behavior
The test should pass or fail but not stall.

### Steps to reproduce
Run `io.netty.channel.ThreadPerChannelEventLoopGroupTest` test.

### Log file
[log.txt](https://github.com/netty/netty/files/6936107/log.txt)

### Netty version
4.1.66.Final

### JVM version (e.g. `java -version`)
Java 11

### OS version (e.g. `uname -a`)
Microsoft Windows Server 2016

**Comment by hyperxpro** [comment]
Happened here too: https://github.com/netty/netty/pull/11539

**Comment by hyperxpro** [comment]
Happened on #11653 
```
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.25 s - in io.netty.bootstrap.BootstrapTest
[INFO] Running io.netty.channel.DefaultFileRegionTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.224 s - in io.netty.channel.DefaultFileRegionTest
[INFO] Running io.netty.channel.ThreadPerChannelEventLoopGroupTest
Terminate batch job (Y/N)? 
Error: The operation was canceled.
```

@normanmaurer @NiteshKant Should we disable this test too?

**Comment by hyperxpro** [comment]
Happened on #11680 

```
[INFO] Running io.netty.channel.ThreadPerChannelEventLoopGroupTest
Error: The operation was canceled.
```

**Comment by hyperxpro** [comment]
@chrisvest I think it is the time to disable this test?

**Comment by NiteshKant** [comment]
@hyperxpro sure thing, please send a PR
