### ISSUE TITLE
[Netty 5] Discussion - Remove SCTP Support

### ISSUE THREAD

**Issue by hyperxpro** [netty/netty#11555]
Currently, Netty supports SCTP (transport-sctp). However, SCTP is kind of dead. The documentation of the `transport-sctp` module is also not up to the mark. We should consider removing it from Netty 5 onwards.

So this is a discussion thread to find whether we should support it or not in Netty 5.

**Comment by chrisvest** [comment]
I wonder if we could split it out into its own repo, and let it be maintained by whatever parties might be interested in it, if any.
There are also a number of codecs that look questionable in the main repo, like redis, memcache, xml.

**Comment by hyperxpro** [comment]
I have the same opinions on those modules (or codecs). In the main repo, we should only support widely used protocols like HTTP/2, WebSocket, etc.

**Comment by hyperxpro** [comment]
@NiteshKant I'd love to hear your feedback on this too.

**Comment by NiteshKant** [comment]
Yeah I would agree with both of you, we should not migrate deprecated protocols to netty 5. If and when we see interest we can help folks migrate by creating separate repos, reviewing PRs etc

**Comment by chenmeng1994** [comment]
The sctp protocol was abandoned, when did it happen?

**Comment by hyperxpro** [comment]
Something can't be abandoned if it was never fully adopted. So is SCTP, adopted by a very few percentage of users.

**Comment by chrisvest** [comment]
Removal got merged.
