### ISSUE TITLE
Module compatibility

### ISSUE THREAD

**Issue by jameskleeh** [netty/netty#11567]
Netty 4.1.66 introduced a requirement on tc-native 2.0.40 with this commit https://github.com/netty/netty/commit/40fb6026efd2a9fc67049b437e4db5d6d81d688c

This led to a user being confronted with an error after upgrading Micronaut (which includes 4.1.66) https://github.com/micronaut-projects/micronaut-core/issues/5920

Can we get the tc-native modules added to the netty bom so we can avoid this?

**Comment by normanmaurer** [comment]
@jameskleeh I am currently not sure how to do this as the user can either use `netty-tcnative` or `netty-tcnative-boringssl-static`. Or you are saying we should add both ?

**Comment by jameskleeh** [comment]
Yeah I think both

**Comment by normanmaurer** [comment]
@jameskleeh want to provide a PR ?

**Comment by jameskleeh** [comment]
Sure

**Comment by normanmaurer** [comment]
@jameskleeh ping me once something is ready for review

**Comment by normanmaurer** [comment]
@jameskleeh https://github.com/netty/netty/pull/11609
