### ISSUE TITLE
Android11高并发请求会间隔5秒

### ISSUE THREAD

**Issue by MartinQAQ** [netty/netty#11579]
###Android11

On Android11 devices, the default interval for high concurrent requests is 5 seconds. On devices below Android11。

**Comment by hyperxpro** [comment]
Please use the issue template and provide detailed information.

**Comment by MartinQAQ** [comment]
// Connection code
synchronized (NettyTcpClient.this) {
	ChannelFuture channelFuture = null;
	if (!isConnect) {
		isConnecting = true;
		group = new NioEventLoopGroup(2);
		Bootstrap bootstrap = new Bootstrap().group(group)
				.option(ChannelOption.SO_SNDBUF, 1024 * 1024)
				.option(ChannelOption.SO_RCVBUF, 1024 * 1024)
				.option(ChannelOption.SO_KEEPALIVE, true)
				.channel(NioSocketChannel.class)
				.handler(new ChannelInitializer<SocketChannel>() {
					@Override
					public void initChannel(SocketChannel ch) throws Exception {
						if (isSendheartBeat) {
							ch.pipeline().addLast("ping", new IdleStateHandler(0, 5, 0, TimeUnit.SECONDS));
						}

						SSLEngine engine = SslContextFactory.getClientContext(App.getContext()).createSSLEngine();
						engine.setUseClientMode(true);
						ch.pipeline().addLast("ssl", new SslHandler(engine))
								.addLast(new DelimiterBasedFrameDecoder(1024 * 1024, Delimiters.lineDelimiter()))
								.addLast(new StringDecoder(CharsetUtil.UTF_8))
								.addLast(new StringEncoder(CharsetUtil.UTF_8))
								.addLast(new IdleStateHandler(0, 0, 5))
								.addLast(new LengthFieldBasedFrameDecoder(1024, 0, 4, -4, 0));

						ch.pipeline().addLast(new NettyClientHandler(listener, mIndex, isSendheartBeat, heartBeatData,packetSeparator));
					}
				});

		try {
			channelFuture = bootstrap.connect(host, tcp_port).addListener(new ChannelFutureListener() {
				@Override
				public void operationComplete(ChannelFuture channelFuture) throws Exception {
					if (channelFuture.isSuccess()) {
						reconnectNum = MAX_CONNECT_TIMES;
						isConnect = true;
						channel = channelFuture.channel();
						ViseLog.e(heartBeatData.toString());
						boolean is = sendMsgToServer(heartBeatData.toString(), null);
					} else {
						isConnect = false;
					}
					isConnecting = false;
				}
			}).sync();

			// Wait until the connection is closed.
			channelFuture.channel().closeFuture().sync();
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			isConnect = false;
			if (listener != null) {
				listener.onClientStatusConnectChanged(ConnectState.STATUS_CONNECT_CLOSED, mIndex);
			}
			if (null != channelFuture) {
				if (channelFuture.channel() != null && channelFuture.channel().isOpen()) {
					channelFuture.channel().close();
				}
			}
			group.shutdownGracefully();
//                    reconnect();
		}
	}
}




//Send message  mode
  ChannelFuture channelFuture = channel.writeAndFlush(data).addListener(new ChannelFutureListener() {
                @Override
                public void operationComplete(ChannelFuture channelFuture) throws Exception {
                    try {
                        if (listener != null) {
                            listener.isSendSuccss(channelFuture.isSuccess());
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            });
            
          
Is it because of the cause  “ch.pipeline().addLast("ping", new IdleStateHandler(0, 5, 0, TimeUnit.SECONDS));”， If it is caused by the heartbeat interval, how can I change it？

**Comment by MartinQAQ** [comment]
@hyperxpro 

// Connection code
synchronized (NettyTcpClient.this) {
	ChannelFuture channelFuture = null;
	if (!isConnect) {
		isConnecting = true;
		group = new NioEventLoopGroup(2);
		Bootstrap bootstrap = new Bootstrap().group(group)
				.option(ChannelOption.SO_SNDBUF, 1024 * 1024)
				.option(ChannelOption.SO_RCVBUF, 1024 * 1024)
				.option(ChannelOption.SO_KEEPALIVE, true)
				.channel(NioSocketChannel.class)
				.handler(new ChannelInitializer<SocketChannel>() {
					@Override
					public void initChannel(SocketChannel ch) throws Exception {
						if (isSendheartBeat) {
							ch.pipeline().addLast("ping", new IdleStateHandler(0, 5, 0, TimeUnit.SECONDS));
						}

						SSLEngine engine = SslContextFactory.getClientContext(App.getContext()).createSSLEngine();
						engine.setUseClientMode(true);
						ch.pipeline().addLast("ssl", new SslHandler(engine))
								.addLast(new DelimiterBasedFrameDecoder(1024 * 1024, Delimiters.lineDelimiter()))
								.addLast(new StringDecoder(CharsetUtil.UTF_8))
								.addLast(new StringEncoder(CharsetUtil.UTF_8))
								.addLast(new IdleStateHandler(0, 0, 5))
								.addLast(new LengthFieldBasedFrameDecoder(1024, 0, 4, -4, 0));

						ch.pipeline().addLast(new NettyClientHandler(listener, mIndex, isSendheartBeat, heartBeatData,packetSeparator));
					}
				});

		try {
			channelFuture = bootstrap.connect(host, tcp_port).addListener(new ChannelFutureListener() {
				@Override
				public void operationComplete(ChannelFuture channelFuture) throws Exception {
					if (channelFuture.isSuccess()) {
						reconnectNum = MAX_CONNECT_TIMES;
						isConnect = true;
						channel = channelFuture.channel();
						ViseLog.e(heartBeatData.toString());
						boolean is = sendMsgToServer(heartBeatData.toString(), null);
					} else {
						isConnect = false;
					}
					isConnecting = false;
				}
			}).sync();

			// Wait until the connection is closed.
			channelFuture.channel().closeFuture().sync();
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			isConnect = false;
			if (listener != null) {
				listener.onClientStatusConnectChanged(ConnectState.STATUS_CONNECT_CLOSED, mIndex);
			}
			if (null != channelFuture) {
				if (channelFuture.channel() != null && channelFuture.channel().isOpen()) {
					channelFuture.channel().close();
				}
			}
			group.shutdownGracefully();
//                    reconnect();
		}
	}
}




//Send message  mode
  ChannelFuture channelFuture = channel.writeAndFlush(data).addListener(new ChannelFutureListener() {
                @Override
                public void operationComplete(ChannelFuture channelFuture) throws Exception {
                    try {
                        if (listener != null) {
                            listener.isSendSuccss(channelFuture.isSuccess());
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            });
            
            

Is it because of the cause “ch.pipeline().addLast("ping", new IdleStateHandler(0, 5, 0, TimeUnit.SECONDS));”， If it is caused by the heartbeat interval, how can I change it？
