### ISSUE TITLE
Some questions about Http2MultiplexHandler

### ISSUE THREAD

**Issue by xiaoheng1** [netty/netty#11577]
### Expected behavior

Can Http2MultiplexHandler handle different streams concurrently

### Actual behavior

When a stream is blocked, other sreams cannot be processed

### Steps to reproduce

I am using io.netty.example.http2.helloworld.multiplex.server.Http2Server. But the code of HelloWorldHttp2Handler is modified, as follows:

```
private static void onHeadersRead(ChannelHandlerContext ctx, Http2HeadersFrame headers)
            throws Exception {
        if (headers.isEndStream()) {
            Thread.sleep(2 * 1000);
            ByteBuf content = ctx.alloc().buffer();
            content.writeBytes(RESPONSE_BYTES.duplicate());
            ByteBufUtil.writeAscii(content, " - via HTTP/2");
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss SSS");
            System.out.println("---->" +sdf.format(new Date(System.currentTimeMillis())));
            sendResponse(ctx, content);
        }
    }
```

Client core code：

```
for(int i=0; i<3; i++) {
                    // Create a simple GET request.
                    FullHttpRequest request = new DefaultFullHttpRequest(HTTP_1_1, GET, URL, Unpooled.EMPTY_BUFFER);
                    request.headers().add(HttpHeaderNames.HOST, hostName);
                    request.headers().add(HttpConversionUtil.ExtensionHeaderNames.SCHEME.text(), scheme.name());
                    request.headers().add(HttpHeaderNames.ACCEPT_ENCODING, HttpHeaderValues.GZIP);
                    request.headers().add(HttpHeaderNames.ACCEPT_ENCODING, HttpHeaderValues.DEFLATE);
                    responseHandler.put(streamId, channel.write(request), channel.newPromise());
                    channel.flush();
                    streamId += 2;
                }

responseHandler.awaitResponses(3, TimeUnit.SECONDS);
```

If the http2 server processes the stream in parallel, then the result should be obtained normally at this time, but the actual result is a timeout.

i view the code of the io.netty.handler.codec.http2.Http2MultiplexHandler.

It is found that the created AbstractHttp2StreamChannel is registered to the evenLoop of the channel. Should we register the AbstractHttp2StreamChannel to the new eventLoop?

```
if (stream.id() == Http2CodecUtil.HTTP_UPGRADE_STREAM_ID && !isServer(ctx)) {
                            // We must have an upgrade handler or else we can't handle the stream
                            if (upgradeStreamHandler == null) {
                                throw connectionError(INTERNAL_ERROR,
                                        "Client is misconfigured for upgrade requests");
                            }
                            ch = new Http2MultiplexHandlerStreamChannel(stream, upgradeStreamHandler);
                            ch.closeOutbound();
                        } else {
                            ch = new Http2MultiplexHandlerStreamChannel(stream, inboundStreamHandler);
                        }

                        ChannelFuture future = ctx.channel().eventLoop().register(ch);
                        if (future.isDone()) {
                            registerDone(future);
                        } else {
                            future.addListener(CHILD_CHANNEL_REGISTRATION_LISTENER);
                        }
```

### Netty version

netty 4.1.58

### JVM version (e.g. `java -version`)

1.11

### OS version (e.g. `uname -a`)

macos

**Comment by hyperxpro** [comment]
If you block a stream in EventLoop then you'll definitely not be able to process other streams concurrently.

**Comment by xiaoheng1** [comment]
If this is the case, what is the difference between using Http2MultiplexHandler and not using it? I understand that Http2MultiplexHandler helps users process streams in parallel. If you don’t use them, then the server will process them on a first-come, first-served basis.

**Comment by hyperxpro** [comment]
Well, this is completely wrong. `Http2MultiplexHandler` creates a new channel for each stream from the client. If you use `Http2MultiplexHandler` and you receive streams id 3, 5, 7 then `Http2MultiplexHandler` will create 3 channels to handle it. However, since it's multiplexing, if you block any channel, it'll block the entire TCP connection and no other channels will receive data.


You can still handle multiple streams without `Http2MultiplexHandler` but that's complex.

**Comment by xiaoheng1** [comment]
Is it understood that Http2MultiplexHandler simplifies the user's programming model?

By the way, if we create a channel for the stream, if we recreate the eventLoop to process the request, instead of registering the channel to the corresponding channel at the bottom of the tcp, would it be more appropriate?

**Comment by hyperxpro** [comment]
Yes, that's the job of Multiplex Handler.

EventLoop will be registered on TCP handshake completion. All stream channels will share the same EventLoop.

**Comment by xiaoheng1** [comment]
Ok, i understand it. thanks.
