### ISSUE TITLE
HttpContentCompressor doesn't handle optional encoders

### ISSUE THREAD

**Issue by jkuhn1** [netty/netty#11581]
Hi,

Following #11480 and the use of `CompressionOptions` it appears the `HttpContentCompressor` doesn't handle optional encoders such as Brotli and Zstd properly when using `CompressionOptions`. 

For instance, if brotli4j is missing at runtime, Http compression is actually  completely broken as the constructor always tries to create `BrotliOptions` even if not specified which result in an `IllegalStateException`.

Then, if zstd-jni is missing at runtime, a request with `accept-encoding: gzip, deflate, zstd` will fail since `determineEncoding()` still returns zstd resulting in a `NoClassDefFoundError` when the `beginEncode()` method is invoked.

This behaviour is actually quite different than what's implemented in `CompressorHttp2ConnectionEncoder` which only considers the encoders for which `CompressionOptions` have been specified.

### Expected behavior

When using the `HttpContentCompressor` with `CompressionOptions` without brotly4j or zstd-jni at runtime, we expect the brotly and zstd encoding to be ignored, fallbacking to another encoding or to no encoding following `accept-encoding` HTTP header rules.

For instance:
`accept-encoding: gzip, br` should result in a response compressed in gzip
`accept-encoding: br, zstd` should result in an uncompressed response

In general, the `HttpContentCompressor` should only consider the encodings corresponding to the `CompressionOptions` provided to the constructor.

For instance, if the `HttpContentCompressor` is created with `GzipOptions` only, then only gzip encoding should be accepted and a response to a request with different accept encodings should be uncompressed. This behaviour is the same as for `CompressorHttp2ConnectionEncoder`.

### Actual behavior

Using the `HttpContentCompressor` without the brotli4j results in a `IllegalStateException: "Brotli is not available"` thrown when it tries to create default `BrotliOptions` in the constructor.

Using the `HttpContentCompressor` without zstd-jni results in a `NoClassDefFoundError` thrown when it tries to encode a response in zstd encoding.

When creating a `HttpContentCompressor` with a single `CompressionOptions` such as `GzipOptions`, the constructor actually sets default options for the other encodings and as a result, a response can be compressed using deflate, brotli or zstd encoders event if we didn't want it.

### Steps to reproduce

- Define a `HttpContentCompressor` with `GzipOptions` in a HTTP server
- Run the server without brotli or zstd-jni
- query the server with various `accept-encoding` headers: `accept-encoding: gzip`, `accept-encoding: br`, `accept-encoding: deflate`...  

### Netty version

4.1.66.Final

### JVM version (e.g. `java -version`)

openjdk version "16" 2021-03-16
OpenJDK Runtime Environment (build 16+36-2231)
OpenJDK 64-Bit Server VM (build 16+36-2231, mixed mode, sharing)

### OS version (e.g. `uname -a`)

Linux 4.19.0-17-amd64 #1 SMP Debian 4.19.194-1 (2021-06-10) x86_64 GNU/Linux

**Comment by hyperxpro** [comment]
Can you do a PR? Or I should go ahead with that?

**Comment by jkuhn1** [comment]
I'm on it!

**Comment by hyperxpro** [comment]
Perfect! Thanks a lot :)

**Comment by jkuhn1** [comment]
Please let me know if I missed something.
