### ISSUE TITLE
CauseHolder

### ISSUE THREAD

**Issue by HelloVonLea** [netty/netty#11598]
I have a question about CauseHolder in DefaultPromise. What I want is, it should be a member variable,
### private final Throwable cause;
but actual behavior is  a nested class.
### private static final class CauseHolder{...}
Why? What advantage it is?

**Comment by chrisvest** [comment]
It allows the promise implementation to distinguish a failed future/promise from one that succeeded and produced an exception as a result.

**Comment by chrisvest** [comment]
It also means we only need one field for the result, making promise objects smaller since succeeding is the most common outcome.
