### ISSUE TITLE
Add support getting the pooled memory size for each PooledByteBufAllocator instance

### ISSUE THREAD

**Issue by JamesChenX** [netty/netty#11637]
### Motivation
Our server has its own implementation to decide whether to provide service for users according to the real-time total free memory of the heap memory and the direct memory (mainly the memory used by `io.netty.buffer.PooledByteBufAllocator` for our server). If our server detects it's running out of physical memory, it will just respond with the client requests with something like `Service Unavailable`.

But the problem is: We cannot know the free memory of PooledByteBufAllocator efficiently. For example, we have allocated and cached 8GB chunks in a `PooledByteBufAllocator`, but there is no property to know: what exactly the free memory is, 1GB or 8GB?

### Solution
The [PR](https://github.com/netty/netty/pull/5133/files) in 2016 is similar to what we want and it provides a new property `pooledBytes` to record the free memory of the arena but we want the free memory in the scope of each allocator instance.

And `io.netty.maxDirectMemory` is similar but isn't what we want because it applies the limit to all buffers while we just want to know the free memory size of a PooledByteBufAllocator instance

**Comment by chrisvest** [comment]
For the heap _in general_, the free memory on the heap is not the same as the amount of memory that could be freed if the GC was to do a run, so we can only realistically do this for direct memory where we have precise accounting of what memory is in use and what is not. But then there's also fragmentation; having X free bytes doesn't necessarily mean there's room for an X-sized allocation.

But to count the free bytes, you can iterate the arenas (`pool.arenaMetrics()`), and then iterate the chunk lists for each (`arena.chunkLists`) and then for each chunk in those you can get the `freeBytes()`. Not super convenient, but if you are up for it you could make a PR to improve that.
