### ISSUE TITLE
Veracode Flaw - Insecure Temporary File is identified -

### ISSUE THREAD

**Issue by ravik-github** [netty/netty#11645]
### Expected behavior
A veracode flaw has been reported from Netty thirdparty

### Steps to reproduce
Scanned a Cassandra JDBC driver in veracode

### Netty version
4.1.63

### OS version (e.g. `uname -a`)
Windows

**Comment by chrisvest** [comment]
Hi @ravik-github, can you share more details, like where the problematic code is and how it's problematic? Also, if you think there's a security issue, we have a security policy for how to report such issues: https://github.com/netty/netty/security/policy

**Comment by normanmaurer** [comment]
Let's close this as there was no more details
