### ISSUE TITLE
Why not provide a way for users to get directArenas?

### ISSUE THREAD

**Issue by skyguard1** [netty/netty#11658]
### Expected behavior
Users can get directArenas by themselves

### Actual behavior
Users cannot get directArenas by themselves

In many cases, users want to obtain memory allocation bytes by themselves. `PooledByteBufAllocator` is a public class, but directArenas is private, and there is no way to obtain directArenas directly, so users can only obtain directArenas in this way
        
```
        Object[] allocDirectArenas = null;
         try {
             Field directArenasField = PooledByteBufAllocator.class.getDeclaredField("directArenas");
             directArenasField.setAccessible(true);

             allocDirectArenas = (Object[]) directArenasField.get(this);
         } catch (Exception e) {
             LOG.error("Memory statistics not available",e);
         } 
```

What is the reason for not providing a method to obtain directArenas, allowing users to calculate the number of bytes allocated for direct memory by themselves? thanks

### Netty version
4.1.67

**Comment by chrisvest** [comment]
@skyguard1 Why would you want access to the internal arenas, rather than calling something like `newDirectBuffer()`? If the allocator internals where publicly accessible, we would be restricted in what changes we can make to them. For instance, the pooled allocator for the new `Buffer` API in Netty 5 does not know if it's allocating heap or direct buffers: https://github.com/netty/netty/blob/main/buffer/src/main/java/io/netty/buffer/api/pool/PooledBufferAllocator.java

**Comment by skyguard1** [comment]
This is a different scene
Some users only want to use `newDirectBuffer()` to allocate memory. Considering that many users are using direct memory a lot, some users may want to know the details of memory allocation, so they will extend `PooledByteBufAllocator`, but `directArenas` is private and cannot be accessed directly. Have to use reflection to do this, which is a bit inconvenient
See https://github.com/apache/flink/blob/master/flink-runtime/src/main/java/org/apache/flink/runtime/io/network/netty/NettyBufferPool.java#L101
The user may want to monitor the memory allocation. Of course, it is ok if the current state is maintained, but when the user wants to extend a class, of course, he will pay attention to the implementation details of the class. When the user extends `PooledByteBufAllocator`, he cannot directly use `directArenas`, this would be a little strange. In my opinion, it is more convenient for users to extend `PooledByteBufAllocator` to provide users with a way to obtain `directArenas`,thanks

**Comment by chrisvest** [comment]
So you use it to implement a `getNumberOfAllocatedBytes()`. Is the computed value different from what you get with `metric().usedDirectMemory()`?
I'm wondering if what you really want is similar to what was ask for on #11637?

**Comment by skyguard1** [comment]
Not really. The scope of discussion here is broader than that of pr. Users may get directArenas to do some different things, such as multi-dimensional memory allocation statistics. In most cases, this is not necessary, but some users may do some complicated calculations, thanks
