### ISSUE TITLE
[Netty 5] Remove ReplayingDecoder

### ISSUE THREAD

**Issue by chrisvest** [netty/netty#11659]
I propose we remove `ReplayingDecoder` in Netty 5.

The code might look convenient, but it's relying on simulating continuations with exceptions - a constant, but still.
It also needs to modify how `ByteBuf` behaves, while in the new `Buffer` API we wish to have maximally consistent behaviours.

If we remove the `ReplayingDecoder`, then the following decoders will have to be rewritten in terms of the regular `ByteToMessageDecoder`:

- [ ] Socks5InitialRequestDecoder
- [ ] MqttDecoder
- [ ] StompSubframeDecoder
- [ ] SocksInitResponseDecoder
- [ ] Socks5CommandResponseDecoder
- [ ] Socks5PasswordAuthRequestDecoder
- [ ] CompatibleMarshallingDecoder
- [ ] SocksAuthResponseDecoder
- [ ] Socks5PasswordAuthResponseDecoder
- [ ] WebSocket00FrameDecoder
- [ ] Socks5CommandRequestDecoder
- [ ] Socks4ClientDecoder
- [ ] SocksCmdRequestDecoder
- [ ] SocksInitRequestDecoder
- [ ] Socks5InitialResponseDecoder
- [ ] SocksAuthRequestDecoder
- [ ] Socks4ServerDecoder

**Comment by normanmaurer** [comment]
big +1 from me.

**Comment by NiteshKant** [comment]
SGTM

**Comment by amizurov** [comment]
+1 can help with STOMP

**Comment by normanmaurer** [comment]
Let me take care of this one...

**Comment by normanmaurer** [comment]
almost done with all of it :)

**Comment by amizurov** [comment]
@normanmaurer I prepared PR for STOMP for 4.1 branch, do you think it no need ?

**Comment by normanmaurer** [comment]
@amizurov nope... this will be "main" only. I have all done, just running the testsuite atm.
