### ISSUE TITLE
Issues on UDS path binding

### ISSUE THREAD

**Issue by ran-su** [netty/netty#11652]
I think there are couple issues relate to the UDS path binding logic:

1. In the JNI `netty_unix_socket_bindDomainSocket` method, when the upper level passes in a [longer-than-limit UDS path](https://github.com/netty/netty/blob/d58d8a1df832a5185193368e589cb4a488709ffe/transport-native-unix-common/src/main/c/netty_unix_socket.c#L768).
a. the `unlink()` is called on a different [path](https://github.com/netty/netty/blob/d58d8a1df832a5185193368e589cb4a488709ffe/transport-native-unix-common/src/main/c/netty_unix_socket.c#L772) than the [one](https://github.com/netty/netty/blob/d58d8a1df832a5185193368e589cb4a488709ffe/transport-native-unix-common/src/main/c/netty_unix_socket.c#L776) the code later `bind` to.
b. Netty is [quietly truncating the path](https://github.com/netty/netty/blob/d58d8a1df832a5185193368e589cb4a488709ffe/transport-native-unix-common/src/main/c/netty_unix_socket.c#L770) if user provides a over the limit path. This can be an issue if we have a non-Netty client which has a different path handling logic.

2. According to the manual, "a UNIX domain socket can be bound to a *null-terminated* filesystem pathname", but Netty is not doing anything about this requirement. Although there are some [messes](https://man.archlinux.org/man/core/man-pages/unix.7.en#BUGS) on handling this requirement, we should not simply ignore it. This is also an issue if we have a non-Netty client.

I am proposing a possible fix for all these issues. We can just validate the `socketPath` passed in and let Java throw exceptions if: 1) the `socketPath` is longer than `sizeof(addr.sun_path)`, 2) or, the `socketPath` has the same length as `sizeof(addr.sun_path)` but the last byte is not '\0'. A similar thing also need to be done on the client side. This can ensure the UDS paths Netty can use have maximum compatibility with other UDS servers/clients.

I can send a PR if the change mentioned above is desirable. Thank you.

**Comment by normanmaurer** [comment]
Sounds good . Will provide more feedback on the PR
