### ISSUE TITLE
Netty 4.1.64+ netty-all package does not upgrade transitive deps of netty-* packages

### ISSUE THREAD

**Issue by tlf30** [netty/netty#11657]
### Expected behavior
When building with gradle, with the `netty-all` package, any `netty-*` transitive dependencies should get upgraded to the version of netty-all. 

### Actual behavior
Starting with netty 4.1.64, a mix of netty versions become present on the runtime classpath.
```
runtimeClasspath - Runtime classpath of source set 'main'.
...
+--- com.impossibl.pgjdbc-ng.tools:udt-gen:0.8.8
|    +--- com.impossibl.pgjdbc-ng:pgjdbc-ng:0.8.8
|    |    +--- com.impossibl.pgjdbc-ng:spy:0.8.8
|    |    +--- io.netty:netty-common:4.1.63.Final
|    |    +--- io.netty:netty-buffer:4.1.63.Final
|    |    |    \--- io.netty:netty-common:4.1.63.Final
|    |    +--- io.netty:netty-transport:4.1.63.Final
|    |    |    +--- io.netty:netty-common:4.1.63.Final
|    |    |    +--- io.netty:netty-buffer:4.1.63.Final (*)
|    |    |    \--- io.netty:netty-resolver:4.1.63.Final
|    |    |         \--- io.netty:netty-common:4.1.63.Final
|    |    +--- io.netty:netty-codec:4.1.63.Final
|    |    |    +--- io.netty:netty-common:4.1.63.Final
|    |    |    +--- io.netty:netty-buffer:4.1.63.Final (*)
|    |    |    \--- io.netty:netty-transport:4.1.63.Final (*)
|    |    +--- io.netty:netty-handler:4.1.63.Final
|    |    |    +--- io.netty:netty-common:4.1.63.Final
|    |    |    +--- io.netty:netty-resolver:4.1.63.Final (*)
|    |    |    +--- io.netty:netty-buffer:4.1.63.Final (*)
|    |    |    +--- io.netty:netty-transport:4.1.63.Final (*)
|    |    |    \--- io.netty:netty-codec:4.1.63.Final (*)
|    |    +--- io.netty:netty-transport-native-unix-common:4.1.63.Final
|    |    |    +--- io.netty:netty-common:4.1.63.Final
|    |    |    +--- io.netty:netty-buffer:4.1.63.Final (*)
|    |    |    \--- io.netty:netty-transport:4.1.63.Final (*)
|    |    +--- io.netty:netty-transport-native-kqueue:4.1.63.Final
|    |    |    +--- io.netty:netty-common:4.1.63.Final
|    |    |    +--- io.netty:netty-buffer:4.1.63.Final (*)
|    |    |    +--- io.netty:netty-transport:4.1.63.Final (*)
|    |    |    \--- io.netty:netty-transport-native-unix-common:4.1.63.Final (*)
|    |    \--- io.netty:netty-transport-native-epoll:4.1.63.Final
|    |         +--- io.netty:netty-common:4.1.63.Final
|    |         +--- io.netty:netty-buffer:4.1.63.Final (*)
|    |         +--- io.netty:netty-transport:4.1.63.Final (*)
|    |         \--- io.netty:netty-transport-native-unix-common:4.1.63.Final (*)
...
\--- project :<name censored>
     +--- project :<name censored>
...
     +--- io.netty:netty-all:4.1.67.Final
    ...
```

### Steps to reproduce
See: https://github.com/tlf30/netty-test-1

### Netty version
4.1.64+

### JVM version (e.g. `java -version`)
`openjdk version "14.0.1" 2020-04-14`

### OS version (e.g. `uname -a`)
```
Microsoft Windows 11 Pro Insider Preview
Version	10.0.22449 Build 22449
```

**Comment by normanmaurer** [comment]
Not sure I get it..  Can you provide a reproducer ?

**Comment by fredericBregier** [comment]
Migh it be related to #11272 already fixed in 4.1.65 ?

**Comment by tlf30** [comment]
I have tested up to 4.1.67. When I get a second today I will post an example. But basically if you are using the `netty-all` package, and a library you are using is using separate netty packages, such as `netty-common`, then you will have both jars on the runtime classpath at whatever versions are specified. So if the library is using 4.1.63, and you are using 4.1.67, then `netty-common` 4.1.63 and `netty-all` 4.1.67 will both be on the runtime classpath.

**Comment by tlf30** [comment]
OK, I put together a example this morning: https://github.com/tlf30/netty-test-1

**Comment by slandelle** [comment]
You shouldn't have `netty-all` and netty-* modules in the classpath altogether. Any build tool, be it gradle or maven, would see them as unrelated artifacts.

You must exclude one or the other with exclusion rules.

**Comment by tlf30** [comment]
While in this small example that is possible, but when dealing with many libraries adding hundreds of exclusions is not a maintainable option. If `netty-all` was only a pom artifact this would not be an issue. Take note of how groovy does their `groovy-all` package, it does not have this problem.

**Comment by normanmaurer** [comment]
This should be fixed by https://github.com/netty/netty/pull/11732
