### ISSUE TITLE
Multipart upload splits CRLF across 2 chunks

### ISSUE THREAD

**Issue by zentol** [netty/netty#11668]
### Expected behavior

CLRF is always part of a single chunk.

### Actual behavior

CRLF _can_ be split across 2 chunks (in some super rare exotic circumstances), causing the first CR to be considered part of the multipart payload and being offered to the Decoder, causing

```
io.netty.handler.codec.http.multipart.HttpPostRequestDecoder$ErrorDataDecoderException: java.io.IOException: Out of size: 5043445 > 5043444
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.loadDataMultipartOptimized(HttpPostMultipartRequestDecoder.java:1190)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.getFileUpload(HttpPostMultipartRequestDecoder.java:926)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.decodeMultipart(HttpPostMultipartRequestDecoder.java:572)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.parseBodyMultipart(HttpPostMultipartRequestDecoder.java:463)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.parseBody(HttpPostMultipartRequestDecoder.java:432)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:347)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:54)
	at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:223)
```

This is **very much** a _theory_. Any hints to figure out whether something else could cause this would be appreciated.

### Steps to reproduce

We have a test in Apache Flink that uploads a multipart HTTP request containing a bit of JSON as a MemoryAttribute and a FileUpload.
When the size of these attributes is just right (deviating by as much as 3 bytes hides the issue) the decoding of the request fails.
If it fails, then it is always with an off-by-one error as shown above, one more byte arriving than expected.

While debugging I inspected the chunk that causes the error. The last readable byte in the chunk had the value '13', i.e., CR. This makes me to believe that it is somehow possible that the CRLF can be split across chunks.

According to the the [4.1.49 decoder](https://github.com/netty/netty/blob/d0ec961cce19646519d6a0d59e7604b0eacd9bf2/codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java#L1101) this should be impossible, but the explicit check was removed in 1529ef1794e0a6654fa4334fd979b769d6940e61.

We further consistently observe that the return value `HttpPostRequestEncoder#length()` after finalizing the request differs by _exactly 1_ between successful and failed runs, e.g., 5043832 (successful) vs 5043831 (failed).
Not sure what to make of that, but it's too consistent to ignore.

We have only observed this error after upgrading from 4.1.49 to 4.1.65.

### Minimal yet complete reproducer code (or URL to code)

Still working on that. I could provide a reproducer that relies on a few Apache Flink classes if that would be acceptable.

### Netty version

4.1.65.Final

### JVM version (e.g. `java -version`)

openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

### OS version (e.g. `uname -a`)

Windows 11, but we also observed it on Ubuntu 20.

**Comment by NiteshKant** [comment]
cc @fredericBregier

**Comment by NiteshKant** [comment]
This code does look suspicious for cases when CRLF are split across buffer boundaries:

https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostBodyUtil.java#L164-L168

**Comment by fredericBregier** [comment]
IMHO, it is the contrary:
- when the CR is there but not LF, then it returns -1 since it does not found the boundary ending
- when it gets the next buffer, then LF will be found
However, I think I can do a reproducer as you described (very easy). It will then show the bug, if any, and finally I will propose a fix (of course, if I found the root cause).

**Comment by fredericBregier** [comment]
Just to let you know that I can reproduce with the following scenario (could you confirm that this one is the same as yours):
- Last-1 buffer contains last chunk + CR only (no LF)
- Last buffer contains LF and separator (with LF/CRLF at the end, but even with a n+1 buffer containing LF or CRLF it's the same)
- Issue is on Last-1 buffer: CR is included in the final data (which should not)

If the following scenario occurs, it's OK:
- Last-1 buffer contains last chunk + LF/CRLF + separator + CR
- Last buffer contains LF
- No issue

**Comment by zentol** [comment]
> Last-1 buffer contains last chunk + CR only (no LF)
> Issue is on Last-1 buffer: CR is included in the final data (which should not)

yep, this sounds like the issue we're having.

> Last buffer contains LF and separator

I haven't confirmed this detail yet (because well, things crash when processing Last-1 buffer), but I can try to do that if that would help.

**Comment by zentol** [comment]
The last buffer did indeed contain `\n--9dd083c5bacd1377--\r\n`

**Comment by fredericBregier** [comment]
OK, thanks ! I'm trying to find out the best way to fix it (with no new issue of course)...
