### ISSUE TITLE
The resolver does not re-read /etc/hosts upon change

### ISSUE THREAD

**Issue by gbrdead** [netty/netty#11661]
### Expected behavior
When /etc/hosts is changed, the netty resolver should re-read it.

### Actual behavior
io.netty.resolver.DefaultHostsFileEntriesResolver parses /etc/hosts only once, upon creation.

### Netty version
4.1.67

### JVM version (e.g. `java -version`)
any

### OS version (e.g. `uname -a`)
any

The WatchService (https://docs.oracle.com/javase/tutorial/essential/io/notification.html) can be used to monitor /etc/hosts and re-read it immediately after it is changed. The same Java API can be used in UnixResolverDnsServerAddressStreamProvider for re-reading /etc/resolv.conf.
At the very least, /etc/hosts should be re-read every few minutes (like the current approach for /etc/resolv.conf).

**Comment by hyperxpro** [comment]
Sounds good! Can you do a PR?

**Comment by bric3** [comment]
Careful with the current JDK `WatchService` as it will miss changes if the file is _bind mounted_. In container based productions this is likely `/etc/hosts` is bind mounted.

I wrote a bit a few years ago : https://blog.arkey.fr/2019/09/13/watchservice-and-bind-mount/

**Comment by normanmaurer** [comment]
@bric3 I think we should just re-read after X seconds.

**Comment by bric3** [comment]
Agreed, polling is the cheapest thing to do and it's portable.
That's what I ended up doing.

**Comment by govi20** [comment]
@normanmaurer would be happy to work on it. Can you pls assign it to me.

**Comment by violetagg** [comment]
It would be good if we keep this non-blocking ...

**Comment by normanmaurer** [comment]
I think what we should do is very similar to here : https://github.com/netty/netty/blob/4.1/resolver-dns-classes-macos/src/main/java/io/netty/resolver/dns/macos/MacOSDnsServerAddressStreamProvider.java#L170

**Comment by Gowrima** [comment]
I am new to this project and I'd like to take this up. Do I wait until this is assigned to me or can I start working on it immediately? Thanks!

**Comment by normanmaurer** [comment]
There is already a pending PR for this: https://github.com/netty/netty/pull/11922

**Comment by Gowrima** [comment]
> There is already a pending PR for this: #11922

ok, I will look into other open issues. Thanks!
