### ISSUE TITLE
4.1.68 security advisories use floating links for code references

### ISSUE THREAD

**Issue by gemmellr** [netty/netty#11675]
The security reports for 4.1.68, [GHSA-9vjp-v76f-g363](https://github.com/netty/netty/security/advisories/GHSA-9vjp-v76f-g363) and [GHSA-grg4-wf29-r9vv](https://github.com/netty/netty/security/advisories/GHSA-grg4-wf29-r9vv), contain a few reference links to their related code areas. However they use links to the 4.1 branch which may float over time, and so while they may be correct now they will likely become incorrect as the various files change. The references should used fixed links such as via the release tag to ensure they remain appropriate.

**Comment by normanmaurer** [comment]
Fixed... Thanks!
