### ISSUE TITLE
ByteBufUtil ClassCastException in 4.1.66+

### ISSUE THREAD

**Issue by rs017991** [netty/netty#11678]
`ByteBufUtil.indexOf` was rewritten recently in https://github.com/netty/netty/pull/11367.

That change introduced a cast of the passed parameter to **AbstractByteBuf**
https://github.com/netty/netty/blob/43f3956030dbb0e6e6cca9b6ceee6812f11c5a4b/buffer/src/main/java/io/netty/buffer/ByteBufUtil.java#L250

The consequence of this is that a ClassCastException is now thrown whenever other **ByteBuf** implementations are used.

The method doc did not and does not indicate that the parameter is required to be an **AbstractByteBuf**, so this appears to be a bug.
https://github.com/netty/netty/blob/43f3956030dbb0e6e6cca9b6ceee6812f11c5a4b/buffer/src/main/java/io/netty/buffer/ByteBufUtil.java#L227-L232

**Comment by normanmaurer** [comment]
yep... This is a regression. @skyguard1 want to have a look ?

**Comment by skyguard1** [comment]
Sure. Should also skip using `firstIndexOf()` when `haystack` is not `AbstractByteBuf`@normanmaurer ,I can fix this
