### ISSUE TITLE
`SingleThreadEventExecutor.shutdownGracefully` starts thread to shut it down?

### ISSUE THREAD

**Issue by kristian** [netty/netty#11686]
### Expected behavior

If `shutdownGracefully` is called on a `SingleThreadEventExecutor` that has not created a thread yet, the executor should shutdown without creating a thread.

### Actual behavior

If `shutdownGracefully` is called on `SingleThreadEventExecutor`, `ensureThreadStarted` will be called in line [#660](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java#L660), which will start the thread, to then? I don't know? Shut it down? I do not get behind the logic to return the `terminationFuture` in that case.

### Steps to reproduce

Create any kind of `EventLoopGroup`, without putting work on it, shut it down gracefully and threads will be created.

### Minimal yet complete reproducer code (or URL to code)

```
public static void main(String[] args) {
    EventLoopGroup group = new NioEventLoopGroup(1, runnable -> {
        return new Thread(runnable) {
            {
                new IllegalStateException("I was created, because Netty wants to shut me down :(")
                        .printStackTrace();
            }
        };
    });
    group.shutdownGracefully();
}
```

Will print:

```
java.lang.IllegalStateException: I was created, because Netty wants to shut me down :(
        ...
        at io.netty.util.concurrent.ThreadPerTaskExecutor.execute(ThreadPerTaskExecutor.java:32)
        at io.netty.util.internal.ThreadExecutorMap$1.execute(ThreadExecutorMap.java:57)
        at io.netty.util.concurrent.SingleThreadEventExecutor.doStartThread(SingleThreadEventExecutor.java:978)
        at io.netty.util.concurrent.SingleThreadEventExecutor.ensureThreadStarted(SingleThreadEventExecutor.java:961)
        at io.netty.util.concurrent.SingleThreadEventExecutor.shutdownGracefully(SingleThreadEventExecutor.java:663)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.shutdownGracefully(MultithreadEventExecutorGroup.java:163)
        at io.netty.util.concurrent.AbstractEventExecutorGroup.shutdownGracefully(AbstractEventExecutorGroup.java:70)
        ...
```

### Netty version

4.1

### JVM version (e.g. `java -version`)

openjdk 11.0.12 2021-07-20 LTS
OpenJDK Runtime Environment SapMachine (build 11.0.12+7-LTS-sapmachine)
OpenJDK 64-Bit Server VM SapMachine (build 11.0.12+7-LTS-sapmachine, mixed mode)

### OS version (e.g. `uname -a`)

Windows 10

**Comment by NiteshKant** [comment]
@kristian is there a use case where this is causing an issue for you or you are just trying to reason about the code?

**Comment by kristian** [comment]
Hey @NiteshKant, we are currently heavily stuck in an issue where our Vert.x-based unit tests keep getting stuck. We are meanwhile in [so deep](https://github.com/SAP/neonbee/pull/69) that we orchestrated all `VertxThread`s with a custom Java agent, in order to find out where they are created. We noticed two things:

1. The bsehaviour above, that depending on the size of the EventPool hundrets of threads are created only to be thrown away afterwards and
2. The threads are created *after* JUnit signals completion of the test, which (as I don‘t entitely understand the snippet I mentioned above) we are not entirely sure if this is caused by the Vert.x shutdown logic, or the issue provided here, such that we fear, that is the reason for our voters not finishing.

Anyways I do think, especially for large thread pools, creation of hundrets of threads on shutdown, might not be desireable either. Thanks for any clue from your side!

**Comment by NiteshKant** [comment]
> creation of hundreds of threads on shutdown, might not be desirable either. 

I understand what you are saying but this statement isn't really true. Threads are not created "on shutdown", but the code ensures that the associated thread per eventloop is created before shutdown, optimistically assuming that if an eventloop is created the intent is to use it. The downside is that if this optimistic assumption is violated, as in your case, then it seems unnecessary to create the thread. 

The reason thread is created and run before graceful shutdown is that we want to ensure if there is a race between task submission and graceful shutdown, we try to drain the queue. The complexity associated with not doing that IMHO outweighs the non ideal behavior for this edge case you are describing.

**Comment by kristian** [comment]
Hey @NiteshKant, thanks for the elaborate explanation of actually _why_ the threads are created in the first place and I fully support your viewpoint of favouring a more robust / less complex implementation over covering an edge case that should next to never cause major side effects in the first place. As you say: in most (especially productive) applications, all executors should be well in use, before a shutdown is initiated. Our example within unit tests is a extreme case, cause we start and tear down Vert.x instances for many of our tests in quick succession.

Do you have any idea / could the current implmentation cause the `shutdownGracefully` future to report a successfull shutdown, before the threads are actually gone in the mentioned edge case? Because this is what we somehow observe: Vert.x signaling a shutdown and the threads beeing created _after_ that. I am willing to do a more in depth analysis on this, as it could be also a flaw in the Vert.x shutdown logic. However _afaik_, they just end the ThreadPools by calling the gracefull shutdown and wait for completion.

I can fully live with what you mentioned, because the edge case doesn‘t really hurt, however if you agree that an early signaled shutdown could be considered an issue (because it is hard to find a workaround for such cases), I would offer take another look into it. What do you think, do you have any hint if this could actually happen?

**Comment by kristian** [comment]
Hey @NiteshKant, I think I have some good news to share, all thanks to your reply, as it got me thinking, so thanks for that!!

I believe I found out the root cause of my assumption, why Vert.x is not "completing" as I thought it would: Calling `vertx.close()` will shut down all the event loop threads, created by Vert.x, gracefully, as I mentioned, by calling the `shutdownGracefully` method on all `EventLoopGroup`s created by Vert.x. However, what I didn't think of, is that Vert.x has to dispatch the "close" event somehow to it's close future, returned by the `close` method. And (this was my wrong assumption) Vert.x is using the _last_ created event loop thread, to dispatch this very final event. Thus the close future will actually block the final event-loop thread exiting, until it is done executing, being the result of my initial assumption, that it is not properly waiting for it to be closed!

Phew... that was a tricky one to warp my head around! ;) Thanks a lot for the explanation and help, as you say I don't think this issue needs further mitigation and it can stay as is. So if you agree, I think we could close it? Good to understand the concept however, so maybe this issue will be useful also to others, which run into this edge case! :) Thanks again!

**Comment by NiteshKant** [comment]
great news @kristian .. your explanation makes sense. I agree, let us close this issue, thanks for reporting your findings back
