### ISSUE TITLE
[Question] DNS native resolver for Apple Silicon M1 still not working?

### ISSUE THREAD

**Issue by lars-lewerenz** [netty/netty#11693]
DNS native resolver for Apple Silicon M1 still doesn't work for me.

Same issue as mentioned here: https://github.com/netty/netty/issues/11020#issue-806940633

### Netty version

netty-resolver-dns-native-macos-4.1.68.Final.jar

### JVM version (e.g. `java -version`)

openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Zulu16.32+15-CA (build 16.0.2+7)
OpenJDK 64-Bit Server VM Zulu16.32+15-CA (build 16.0.2+7, mixed mode)

### OS version (e.g. `uname -a`)

Darwin Larss-Air.fritz.box 21.1.0 Darwin Kernel Version 21.1.0: Thu Aug 19 02:54:44 PDT 2021; root:xnu-8019.40.29~26/RELEASE_ARM64_T8101 arm64

**Comment by lars-lewerenz** [comment]
Resolved by adding io.netty:netty-all:4.1.68.Final.

**Comment by chrisvest** [comment]
Should just work with the `netty-resolver-dns-native-macos-4.1.68.Final.jar` dependency if you have the right classifier.

**Comment by lars-lewerenz** [comment]
> Should just work with the `netty-resolver-dns-native-macos-4.1.68.Final.jar` dependency if you have the right classifier.

I added implementation 'io.netty:netty-resolver-dns-native-macos:4.1.68.Final:osx-x86_64' to my build.gradle, but that didn't work

**Comment by hyperxpro** [comment]
> I added implementation 'io.netty:netty-resolver-dns-native-macos:4.1.68.Final:osx-x86_64' to my build.gradle, but that didn't work

The classifier is wrong, I think.

**Comment by lars-lewerenz** [comment]
> > I added implementation 'io.netty:netty-resolver-dns-native-macos:4.1.68.Final:osx-x86_64' to my build.gradle, but that didn't work
> 
> The classifier is wrong, I think.

Does anyone know the correct classifier?

**Comment by slandelle** [comment]
M1 are ARM, not x86.
Search this archetype on maven.org for the correct classifier.

**Comment by chrisvest** [comment]
Yeah, it should be `osx-aarch_64`.

**Comment by lars-lewerenz** [comment]
> Yeah, it should be `osx-aarch_64`.

Alright, I will check that later. Thank you all for your quick help!

**Comment by krameshRTR** [comment]
Can confirm that the `osx_arch64` classifier works successfully.

**Comment by lars-lewerenz** [comment]
> Can confirm that the `osx_arch64` classifier works successfully.

Yes, thank you!

**Comment by btkelly** [comment]
I'm not sure why there are so many different classifiers reported here but the only one that worked for me was `osx-aarch_64`. I'm using Maven Central BTW so maybe that could be the difference 🤷

**Comment by chrisvest** [comment]
I think the others are typos. The `osx-aarch_64` classifier is the correct one.

**Comment by NicklasWallgren** [comment]
Why do we need to specify the `classifier`, shouldn't that be handled automatically?

**Comment by chrisvest** [comment]
To Maven, the `classifier` tag is an opaque string that is used to distinguish artefacts that were built from the same pom but differ in contents. So, no, it's not automatic. The reason you don't need to specify a classifier for many other libraries that carry native code, is that they include native binaries for all supported platforms in a single jar file.

**Comment by NicklasWallgren** [comment]
@chrisvest Alright, thanks for the explanation.
