### ISSUE TITLE
Epoll consuming lot more CPU than Nio

### ISSUE THREAD

**Issue by praveen97uma** [netty/netty#11695]
I am building a websocket based broker. During load testing, we found that Epoll transport uses around 55% CPU compared to around 20% for Nio, just for maintaining the connections without doing any business specific IO on those connections. Is this expected? What could I be doing wrong?  Happy to share any more info required around this.

Total concurrent connections: Around 27K
Boss Threads: 1
Worker Threads: 32

Cores in the VM: 8

Relevant code that sets up netty.
```
  EventExecutorChooserFactory chooserFactory = DefaultEventExecutorChooserFactory.INSTANCE;

  ThreadFactory bossThreadFactory = ThreadFactoryUtil.createInstrumented("boss", metricRegistry);

  Executor workerExecutor = new ThreadPerTaskExecutor(
          ThreadFactoryUtil.createAffinityThreadFactory("worker.thread", metricRegistry));

private void setupNioEventLoopGroups(EventExecutorChooserFactory chooserFactory, ThreadFactory bossThreadFactory,
            Executor workerExecutor) {
        bossPool = new NioEventLoopGroup(acceptorThreads, bossThreadFactory);
        workerPool = new NioEventLoopGroup(workerThreads, workerExecutor, chooserFactory, SelectorProvider.provider(),
                DefaultSelectStrategyFactory.INSTANCE);
        channelType = NioServerSocketChannel.class;
        log.info("Initialiazing Java NIO Event System");
    }

    private void setupEpollEventLoopGroups(EventExecutorChooserFactory chooserFactory, ThreadFactory bossThreadFactory,
            Executor workerExecutor) {
        bossPool = new EpollEventLoopGroup(acceptorThreads, bossThreadFactory);
        workerPool = new EpollEventLoopGroup(workerThreads, workerExecutor, chooserFactory,
                DefaultSelectStrategyFactory.INSTANCE);
        channelType = EpollServerSocketChannel.class;
        log.info("Initialiazing Epoll IO Event System");
    }


        ServerBootstrap serverBootstrap = new ServerBootstrap().group(bossPool, workerPool);

        // Choose socket options.
        Map<ChannelOption<?>, Object> channelOptions = new HashMap<>();
        channelOptions.put(ChannelOption.SO_BACKLOG, 256);
        channelOptions.put(ChannelOption.ALLOCATOR, new PooledByteBufAllocator(true));
        channelOptions.put(ChannelOption.SO_TIMEOUT, 3000);

        channelOptions.forEach(
                (key, value) -> serverBootstrap.option(ChannelOption.valueOf(String.valueOf(key)), value));

        // Set transport options
        serverBootstrap.childOption(ChannelOption.TCP_NODELAY, true);
        serverBootstrap.childOption(ChannelOption.SO_KEEPALIVE, true);
        serverBootstrap.childOption(ChannelOption.SO_LINGER, -1);
        serverBootstrap.childOption(ChannelOption.SO_REUSEADDR, true);
        serverBootstrap.childOption(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT);
        serverBootstrap.childOption(ChannelOption.ALLOW_HALF_CLOSURE, false);
        serverBootstrap.childOption(ChannelOption.SO_SNDBUF, 10 * 1024);
        serverBootstrap.channel(serverGroup.getChannelType());
        serverBootstrap.childHandler(channelInitializer);

```

### Netty version
4.1.68

### JVM version (e.g. `java -version`)
openjdk version "11.0.12" 2021-07-20 LTS
OpenJDK Runtime Environment Zulu11.50+19-CA (build 11.0.12+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.50+19-CA (build 11.0.12+7-LTS, mixed mode)

### OS version (e.g. `uname -a`)
Linux bolt-004 5.8.0-1041-azure #44~20.04.1-Ubuntu SMP Fri Aug 20 20:41:09 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Epoll
<img width="1209" alt="Screenshot 2021-09-20 at 6 36 30 PM" src="https://user-images.githubusercontent.com/586275/134007274-c1dd0365-89d1-4858-80f7-c489288c3169.png">

Nio
<img width="1218" alt="Screenshot 2021-09-20 at 6 22 49 PM" src="https://user-images.githubusercontent.com/586275/134007373-321b17c3-4639-4711-ab14-b616f2f02414.png">

**Comment by hyperxpro** [comment]
More information needed.

**Comment by praveen97uma** [comment]
@hyperxpro I have added some code. Please let me know if anything specific info would help.

**Comment by franz1981** [comment]
@praveen97uma 
The load and performance result is the same for both the tests?

eg 
NIO perform the test in X seconds.
EPOLL perform the test in Y seconds.

**Comment by praveen97uma** [comment]
@franz1981 Yes, The ramp up to 27K connections is same for both NIO and EPOLL. The graph I shared are in steady state after the ramp up with nothing being written to the connections, except the websocket ping/pongs  every 5 sec, which again happens for both the transports.

**Comment by franz1981** [comment]
> Yes, The ramp up to 27K connections is same for both NIO and EPOLL

It would worth to capture some profiling using https://github.com/jvm-profiling-tools/async-profiler

1. https://github.com/jvm-profiling-tools/async-profiler#basic-usage
2. add `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints` as JVM flags
3. run the profiler with `-t -d 10` (or whatever `d`uration you think is ok)

And share the flamegraphs (`-f nio.html` and `-f epoll.html`) somehow

qq
> Worker Threads: 32
> Cores in the VM: 8

if you don't suppose to block on the event loop, why not using 8 worker threads (or less?)

**Comment by praveen97uma** [comment]
@praveen97uma @hyperxpro Here are the files. Profiled for 30s.

https://raw.githubusercontent.com/praveen97uma/experiments/main/epoll.html
https://raw.githubusercontent.com/praveen97uma/experiments/main/nio.html

Screenshots of the same files if convenient.

<img width="1783" alt="Screenshot 2021-09-20 at 7 48 10 PM" src="https://user-images.githubusercontent.com/586275/134018326-295d1ca6-fc02-4145-b9f8-99546665481b.png">


<img width="1787" alt="Screenshot 2021-09-20 at 7 48 22 PM" src="https://user-images.githubusercontent.com/586275/134018303-d8f2f62f-ff7b-44e3-8919-1d704e0a4421.png">

**Comment by franz1981** [comment]
there are an insane amount of samples on epollWait0 due to timerset.
What's this instrumented runnable? can be disabled?

Another thing: I won't suggest to set affinity with netty threads > number of cores...is a BAD idea :)

**Comment by hyperxpro** [comment]
Also, try this: `ServerBootstrap#option(EpollChannelOption.EPOLL_MODE, EpollMode.EDGE_TRIGGERED)`

**Comment by franz1981** [comment]
Good point, it could be that wakeup is spuriously happening or that there are scheduled tasks that cause epoll to awake and go asleep continuosly

**Comment by praveen97uma** [comment]
@franz1981  @hyperxpro  Thank you both for the help . So, I am doing the following changes and will keep you guys posted.

1) Remove the InstrumntedThreadFactory which instruments threads created/running/terminated created by a thread factory.
2) Reduce the worker threads to 8 (equal to no of cores). I am anyway using separate event loop group for blocking channel handlers. Found out the hard way to not set affinity to threads more than > no of cores.
3). try ServerBootstrap#option(EpollChannelOption.EPOLL_MODE, EpollMode.EDGE_TRIGGERED)

**Comment by praveen97uma** [comment]
@franz1981 I made the changes. The CPU has dropped to 40% but, IMO, it is still high.


<img width="1201" alt="Screenshot 2021-09-20 at 9 01 15 PM" src="https://user-images.githubusercontent.com/586275/134029747-b3d2d8f2-2632-45ee-9265-51a98e6c69f9.png">

<img width="1778" alt="Screenshot 2021-09-20 at 8 59 43 PM" src="https://user-images.githubusercontent.com/586275/134029648-656a30b2-5145-4a99-9af9-0a3e077f9b49.png">

**Comment by franz1981** [comment]
It's still too much time...
There are any scheduled task submitted?

**Comment by praveen97uma** [comment]
I have scheduled tasks which run at every 200ms to consume messages from a buffer queue for that connection and push to the client. This is scheduled on the channel's event executor itself. That is the cause of all this I guess then. @franz1981

**Comment by franz1981** [comment]
yeah, probably rescheduling it, is a bit more costy with epool, or it could be due to the hypervised env you run the bench, according to the flamegraphs it doesn't seema bare metal server no? Maybe I'm wrong :)

**Comment by hyperxpro** [comment]
Are you running the program on Shared-CPU VM or Bare Metal?

**Comment by praveen97uma** [comment]
Its not a bare metal but Azure's VM. These are virtual CPUs.

**Comment by normanmaurer** [comment]
@praveen97uma can you upload the flame graph so we can navigate in it ? It seems it spend quite some time on `timerfd_settime`

**Comment by franz1981** [comment]
@normanmaurer It looks to me that due to the too tight period of the scheduled tasks (for that virtual env) epoll always find some new scheduled task to rearm, causing that method to be called too much.

**Comment by praveen97uma** [comment]
@normanmaurer Here is flame graph(updated). https://raw.githubusercontent.com/praveen97uma/experiments/main/epoll.html

**Comment by praveen97uma** [comment]
@normanmaurer @franz1981 @hyperxpro Guys, so ByteBuf.duplicate() creates a new UnpooledDuplicatedByteBuf(). Is it possible to let netty create a Pooled version of the bytebuf? This particular call is causing the highest allocations in my profiling.

**Comment by normanmaurer** [comment]
@praveen97uma if you use the `PooledByteBufAllocator` it should pool these.

**Comment by normanmaurer** [comment]
@praveen97uma also can you explain why and how you schedule so many tasks ?

**Comment by praveen97uma** [comment]
@normanmaurer We had to batch push messages over the connection every 200ms. These msgs are merged in a specific structure to reduce bytes on the wire. I have a buffer queue for every connection and tasks are scheduled for every connection on the eventloops that do this batching and flush over the connection. Is this entirely wrong approach and is there a better way to do this in some other way in netty? Had read about FlushConsolidationHandler but not sure if there is a hook that I can use to do the merging I want to do  before flushing.

I am using PolledByteBufAllocator.

`        serverBootstrap.childOption(ChannelOption.ALLOCATOR, new PooledByteBufAllocator(true));`


```

    public static ByteBuf encodePublishOperation(ByteBufAllocator byteBufAllocator,
            List<ServerPublishOperation> topicPublishes) {

        ByteBuf byteBuf = byteBufAllocator.buffer();
```
ServerPublishOperation is a ByteBufHolder. Channel's alloc is passed to the above function.

<img width="999" alt="Screenshot 2021-10-04 at 3 26 11 PM" src="https://user-images.githubusercontent.com/586275/135831338-5bffad5e-9635-4ba1-a9f9-0ce40a4b3e03.png">

**Comment by normanmaurer** [comment]
> @normanmaurer We had to batch push messages over the connection every 200ms. These msgs are merged in a specific structure to reduce bytes on the wire. I have a buffer queue for every connection and tasks are scheduled for every connection on the eventloops that do this batching and flush over the connection. Is this entirely wrong approach and is there a better way to do this in some other way in netty? Had read about FlushConsolidationHandler but not sure if there is a hook that I can use to do the merging I want to do before flushing.
> 
> I am using PolledByteBufAllocator.
> 
> ` serverBootstrap.childOption(ChannelOption.ALLOCATOR, new PooledByteBufAllocator(true));`
> 
> ```
> 
>     public static ByteBuf encodePublishOperation(ByteBufAllocator byteBufAllocator,
>             List<ServerPublishOperation> topicPublishes) {
> 
>         ByteBuf byteBuf = byteBufAllocator.buffer();
> ```
> 
> ServerPublishOperation is a ByteBufHolder. Channel's alloc is passed to the above function.
> 
> <img alt="Screenshot 2021-10-04 at 3 26 11 PM" width="999" src="https://user-images.githubusercontent.com/586275/135831338-5bffad5e-9635-4ba1-a9f9-0ce40a4b3e03.png">

I see... If you switch to `retainedDuplicate()` it should be pooled as well. Just note that this also will increment the reference count by 1.

**Comment by chrisvest** [comment]
> I have a buffer queue for every connection and tasks are scheduled for every connection on the eventloops that do this batching and flush over the connection. Is this entirely wrong approach and is there a better way to do this in some other way in netty?

If you keep track of your connections (ideally just the ones with messages), you could have a single task scheduled, that go over all current connections and process their batches.

**Comment by NiteshKant** [comment]
> If you keep track of your connections (ideally just the ones with messages), you could have a single task scheduled, that go over all current connections and process their batches.

+1 .. may be not a single task but a single task per eventloop so that you do not have to jump the eventloop for flushing the connection.

**Comment by normanmaurer** [comment]
I wonder if the time used by `timerfd_settime` is any indicator that we might be better of to not use it when possible (when the timeout is milliseconds) and just use `epoll_wait(...)` with the right timeout. WDYT ?

**Comment by normanmaurer** [comment]
Let me put this on my todo list...

**Comment by normanmaurer** [comment]
@praveen97uma I think this should improve things: https://github.com/netty/netty/pull/12145
