### ISSUE TITLE
tcnative.version property is not set in 4.1.68.Final version

### ISSUE THREAD

**Issue by sourabhsparkala** [netty/netty#11691]
### Expected behavior
There seems to be a compilation issue with Netty release `4.1.68.Final`. The reason being you failed to set the property

```
<properties>
    <!-- Keep in sync with ../pom.xml -->
    <tcnative.version>2.0.43.Final</tcnative.version>
  </properties>
  ```
in https://github.com/netty/netty/blob/netty-4.1.68.Final/bom/pom.xml

Hence due to this, please find the screen shot from Maven repository
<img width="1440" alt="Screenshot 2021-09-17 at 12 31 47" src="https://user-images.githubusercontent.com/10615448/133768835-5dacaed7-9bfa-43e8-be31-7228a90899fe.png">

### Actual behavior
The Maven repository should not contain loose properties listed as given in screen shot.

### Netty version
`4.1.68.Final`

**Comment by sourabhsparkala** [comment]
@trustin could you please have a look?

**Comment by hyperxpro** [comment]
@normanmaurer PTAL

**Comment by gemmellr** [comment]
This was already addressed within the changes made on PRs https://github.com/netty/netty/pull/11672 and https://github.com/netty/netty/pull/11682, the reporting comment here even seems to include a copy of the most relevant addition: https://github.com/netty/netty/pull/11682/files#diff-954221b717ff3d93b2f171be5b7d728359dfa4ebee98e8e5691c0697682d247eR66-R69

(Might be nice to do a 4.1.69 fixing the problem, given 4.1.68 actually had security fixes)
