### ISSUE TITLE
Confusion about NioServerSokcetChannel process OP_ACCEPT event in io.netty.channel.nio.AbstractNioMessageChannel.NioMessageUnsafe#read Method

### ISSUE THREAD

**Issue by huibinliupush** [netty/netty#11708]
### Netty version
4.1.56.final

### The purpose of  this issue

I have been reading Netty Souce Code recently，but i have some confusions about `AbstractNioMessageChannel.NioMessageUnsafe#read` method  logic which process the OP_ACCPET event in `NioServerSocketChannel`。and i want to get helped！！

### my confusion

```
                   do {
                        int localRead = doReadMessages(readBuf);
                        if (localRead == 0) {
                            break;
                        }
                        if (localRead < 0) {
                            closed = true;
                            break;
                        }
                        allocHandle.incMessagesRead(localRead);
                    } while (allocHandle.continueReading());
```
this do{...}while loop block is executed only once by main reactor thread （NioEventLoop）in every event loop。

this code `allocHandle.continueReading()` is always return false here, no matter how many clients are connect to the server side at the same time 。because `totalBytesRead` is always `0` in OP_ACCEPT situation

![image](https://user-images.githubusercontent.com/5794695/134673745-e77df965-2429-4637-9dcc-b3991763626c.png)

**so my consusion** is about  the purpose of this do{...}while loop，because `allocHandle.continueReading()` is always return false here

### my point of view

Let‘s suppose a situation that there are mutiple clients(for example three clients) connect to the server side at the same time，but currently 
this do{...}while loop can only create one NioSocketChannel and then quick the do{...}while loop。

and the main  reactor thread back to block in the `selector.select();` again。because there are still two clients left at this time ,so the main reactor thread will not be blocked in `selector.select()` , so main reactor thread continue process the OP_ACCEPT  event ,execute the NioMessageUnsafe#read  again to create another NioSocketChannel for the second cilent。

i think creation of NioSocketChannel for those three cilents should be done in do{...}while loop  together。but max num of this loop shoud be limitd to 16。

this is More effective for handling OP_ACCEPT  event in my point of view

**Comment by normanmaurer** [comment]
Will have a look.

**Comment by huibinliupush** [comment]
> Will have a look.

thanks for your reply，and looking forward to the explanation of this issue。
really appreciate!!

**Comment by normanmaurer** [comment]
@huibinliupush good catch... This was a bug! https://github.com/netty/netty/pull/11729

**Comment by huibinliupush** [comment]
> @huibinliupush good catch... This was a bug! #11729

very honored to contribute something to the great Netty community

my solution of this issue is the same as you think，i also think `NioServerSocketChannelConfig` and `NioSocketChannelConfig` can not use DefaultMaxMessagesRecvByteBufAllocator  together。

this will be perfect to introduce `ServerChannelRecvByteBufAllocator` and use it for all  ServerChannel implementations
