### ISSUE TITLE
ByteBuf.order() seems to have wrong behavior

### ISSUE THREAD

**Issue by dapengzhang0** [netty/netty#11700]
Found unexpected behavior when calling 
```java
Unpooled.buffer(1024).order(ByteOrder.LITTLE_ENDIAN).writeShortLE(message)
```
since netty 4.1.54.Final.

The `order()` method has already been deprecated, but nevertheless it shouldn't be broken. 

### Expected behavior

Test passes

### Actual behavior

Test failed 
```
expected: -12208
but was : 20688
	at NettyEndianTest.endianTestCallingOrder(NettyEndianTest.java:26)
```

### Steps to reproduce

Create the following project

*./build.gradle*
```gradle
plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'com.google.truth:truth:1.0.1'
    testImplementation 'io.netty:netty-buffer:4.1.68.Final'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'
}

test {
    useJUnitPlatform()
}
```

*./src/NettyEndianTest.java*
```java
import static com.google.common.truth.Truth.assertThat;

import io.netty.buffer.ByteBuf;
import io.netty.buffer.Unpooled;
import java.nio.ByteOrder;
import org.junit.jupiter.api.Test;

class NettyEndianTest {

  // Test will fail for netty 4.1.54.Final and above 
  @SuppressWarnings("deprecation")
  @Test
  void endianTestCallingOrder() {
    short message = (short) 0xD050;
    short reverse = (short) 0x50D0;
    ByteBuf b = Unpooled.buffer(1024).order(ByteOrder.LITTLE_ENDIAN).writeShortLE(message);

    assertThat(b.getShortLE(0)).isEqualTo(message);
    assertThat(b.getShort(0)).isEqualTo(reverse);
  }

  // Test is passing
  @Test
  void endianTestWithoutCallingOrder() {
    short message = (short) 0xD050;
    short reverse = (short) 0x50D0;
    ByteBuf b = Unpooled.buffer(1024).writeShortLE(message);

    assertThat(b.getShortLE(0)).isEqualTo(message);
    assertThat(b.getShort(0)).isEqualTo(reverse);
  }
}
```

Run *gradle test*

### Netty version
4.1.54.Final - 4.1.68.Final

Earlier versions before 4.1.54 were good.

### JVM version (e.g. `java -version`)

openjdk version "11.0.11" 2021-04-20 LTS
OpenJDK Runtime Environment Zulu11.48+21-CA (build 11.0.11+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.48+21-CA (build 11.0.11+9-LTS, mixed mode)

Other JVMs the same.

### OS version (e.g. `uname -a`)
Darwin Kernel Version 20.6.0
Other platforms the same.

**Comment by forchid** [comment]
Actually your this test has bug in line 26, 27.

**Comment by dapengzhang0** [comment]
> Actually your this test has bug in line 26, 27.

@forchid  The test where line 26 and 27 are is passing. What bug does it have? The issue is that the other test is failing.

**Comment by forchid** [comment]
> The test where line 26 and 27 are is passing. What bug does it have? The issue is that the other test is failing.

In the method endianTestCallingOrder(), the byte order is LITTLE_ENDIAN, so these asserts should be:
```java
assertThat(b.getShort(0)).isEqualTo(message);
assertThat(b.getShortLE(0)).isEqualTo(reverse);
```

**Comment by dapengzhang0** [comment]
> > The test where line 26 and 27 are is passing. What bug does it have? The issue is that the other test is failing.

> In the method endianTestCallingOrder(), the byte order is LITTLE_ENDIAN, so these asserts should be:
>  ```
>  assertThat(b.getShort(0)).isEqualTo(message);
>  assertThat(b.getShortLE(0)).isEqualTo(reverse);
>  ```

Line 26 and 27 are not in method `endianTestCallingOrder()`. Is there still a bug in line 26 and 27 in method `endianTestWithoutCallingOrder()`?

The method `endianTestCallingOrder()` was passing in Netty 4.1.53.Final, does that mean there was a bug in Netty 4.1.53.Final? (Is it related to #10747 ?)

**Comment by forchid** [comment]
Yes, this bug was existing before Netty 4.1.54.Final.

**Comment by chrisvest** [comment]
The `*LE` methods have different behaviour depending on the concrete buffer implementation and how it's put together with wrappers and so on.

**Comment by ejona86** [comment]
@chrisvest, "different behavior depending on the implementation" sounds like a bug or a useless API. It seems especially bad with the methods being encouraged over `order()`. We had assumed "maybe it is a bug with order()", but if the API is "a box of chocolates and you never know what you are going to get" then that is a more severe issue.

But even if there is some variation in implementation, it seems particularly surprising that `writeShortLE` and `getShortLE` disagree with each other; I don't know how to interpret that other than there's a bug.

**Comment by chrisvest** [comment]
Oh, I didn't catch that those two were disagreeing, but either way, yeah I think it's a bug.

**Comment by ejona86** [comment]
Looks like the entire class needs an audit. But it also looks like it has always been broken https://github.com/netty/netty/commit/0f9492c9affc528c766f9677952412564d4a3f6d . It seems what changed is https://github.com/netty/netty/commit/96da45de2d53d74ad3a77e83c840410eb3f847c7 fixed many of the methods, but also missed many of them. Before the methods were wrong, but in agreement. Now some methods are just a bit more obviously broken.

https://github.com/netty/netty/blob/23405e2000427e9cad104913e7071d8d08e91a3c/buffer/src/main/java/io/netty/buffer/SwappedByteBuf.java#L247-L250

And getMediumLE, getIntLE, and getLongLE look busted. And then I see some other busted methods like:

https://github.com/netty/netty/blob/23405e2000427e9cad104913e7071d8d08e91a3c/buffer/src/main/java/io/netty/buffer/SwappedByteBuf.java#L402-L406

**Comment by chrisvest** [comment]
Opened #11706 to fix this.

@dapengzhang0 Note the tests I added to `UnpooledTest` are different from the ones you posted above. Specifically, the test you said was failing is now making the _opposite_ assertion, namely that `LE` methods always perform little-endian accesses.
