### ISSUE TITLE
Add support for ExtendedSocketOptions `TCP_KEEP*`

### ISSUE THREAD

**Issue by violetagg** [netty/netty#11704]
Currently in Netty with Epoll one can configure `TCP_KEEP*` options.

With Java 11 one can specify the options below when NIO is in use:

https://docs.oracle.com/en/java/javase/11/docs/api/jdk.net/jdk/net/ExtendedSocketOptions.html

```
TCP_KEEPCOUNT
TCP_KEEPIDLE
TCP_KEEPINTERVAL
```

This feature request is for supporting these options for NIO transport.

**Comment by normanmaurer** [comment]
I think you can already do this by using: `NioChannelOption.of(...)` or I am missing something ?

**Comment by violetagg** [comment]
Thanks a lot @normanmaurer, it works perfect :bowing_woman:
