### ISSUE TITLE
TLSv1 and TLSv1.1 is not supported by Netty

### ISSUE THREAD

**Issue by Sandeep-CodeAcc** [netty/netty#11741]
### Expected behaviour
With an endpoint that only supports TLSv1 and TLSv1.1, the handshake should be successful

### Actual behaviour
With an endpoint that only supports TLSv1 and TLSv1.1, the handshake fails with SSLHandshakeException

### Steps to reproduce
Write any dummy app that does handshake using Netty.

### Test Code
https://github.com/Sandeep-CodeAcc/NettyClient.git
Please clone above git, build and run the App.java

### Netty version
4.1.63.Final

### JVM version (e.g. `java -version`)
Java 1.8.0_291 from Oracle.
You might need to change java.security file to enable the TLSv1 and TLSv1.1 Handshakes, by default these are disabled.

### OS version (e.g. `uname -a`)
Darwin Kernel Version 20.6.0

**Comment by chrisvest** [comment]
You are using the JDK SslProvider on a Java version where TLSv1.0 and TLSv1.1 are no longer support: https://www.oracle.com/java/technologies/javase/8u291-relnotes.html#JDK-8202343

**Comment by Sandeep-CodeAcc** [comment]
> Can you show the stacktrace?

|>>15:47:47749.477 [main]INFO  -Starting App
|>>15:47:49049.490 [main]DEBUG -Using SLF4J as the default logging framework
|>>15:47:49449.494 [main]DEBUG --Dio.netty.eventLoopThreads: 24
|>>15:47:52449.524 [main]DEBUG --Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
|>>15:47:52449.524 [main]DEBUG --Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
|>>15:47:53549.535 [main]DEBUG --Dio.netty.noKeySetOptimization: false
|>>15:47:53549.535 [main]DEBUG --Dio.netty.selectorAutoRebuildThreshold: 512
|>>15:47:56349.563 [main]DEBUG -Platform: MacOS
|>>15:47:56649.566 [main]DEBUG --Dio.netty.noUnsafe: false
|>>15:47:56649.566 [main]DEBUG -Java version: 8
|>>15:47:57049.570 [main]DEBUG -sun.misc.Unsafe.theUnsafe: available
|>>15:47:57249.572 [main]DEBUG -sun.misc.Unsafe.copyMemory: available
|>>15:47:57249.572 [main]DEBUG -java.nio.Buffer.address: available
|>>15:47:57349.573 [main]DEBUG -direct buffer constructor: available
|>>15:47:57549.575 [main]DEBUG -java.nio.Bits.unaligned: available, true
|>>15:47:57549.575 [main]DEBUG -jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
|>>15:47:57549.575 [main]DEBUG -java.nio.DirectByteBuffer.<init>(long, int): available
|>>15:47:57549.575 [main]DEBUG -sun.misc.Unsafe: available
|>>15:47:57649.576 [main]DEBUG --Dio.netty.tmpdir: /var/folders/ys/h9flwll967b6d8yd6d51lg8c0000gn/T (java.io.tmpdir)
|>>15:47:57649.576 [main]DEBUG --Dio.netty.bitMode: 64 (sun.arch.data.model)
|>>15:47:58049.580 [main]DEBUG --Dio.netty.maxDirectMemory: 3817865216 bytes
|>>15:47:58049.580 [main]DEBUG --Dio.netty.uninitializedArrayAllocationThreshold: -1
|>>15:47:58149.581 [main]DEBUG -java.nio.ByteBuffer.cleaner(): available
|>>15:47:58149.581 [main]DEBUG --Dio.netty.noPreferDirect: false
|>>15:47:59449.594 [main]DEBUG -org.jctools-core.MpscChunkedArrayQueue: available
|>>15:47:61549.615 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@3c756e4d
|>>15:47:61649.616 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@402f32ff
|>>15:47:61749.617 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@573f2bb1
|>>15:47:61749.617 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@5ae9a829
|>>15:47:61849.618 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@6d8a00e3
|>>15:47:61849.618 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@548b7f67
|>>15:47:61849.618 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@7ac7a4e4
|>>15:47:61849.618 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@6d78f375
|>>15:47:61949.619 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@50c87b21
|>>15:47:61949.619 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@5f375618
|>>15:47:61949.619 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@1810399e
|>>15:47:61949.619 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@32d992b2
|>>15:47:62049.620 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@215be6bb
|>>15:47:62049.620 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@4439f31e
|>>15:47:62049.620 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@5dfcfece
|>>15:47:62149.621 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@23ceabc1
|>>15:47:62149.621 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@5d5eef3d
|>>15:47:62249.622 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@56f4468b
|>>15:47:62249.622 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@6cc4c815
|>>15:47:62349.623 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@3a82f6ef
|>>15:47:62449.624 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@100fc185
|>>15:47:62449.624 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@643b1d11
|>>15:47:62449.624 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@2ef5e5e3
|>>15:47:62549.625 [main]TRACE -instrumented a special java.util.Set into: sun.nio.ch.KQueueSelectorImpl@36d4b5c
|>>15:47:5850.058 [main]DEBUG --Dio.netty.processId: 7652 (auto-detected)
|>>15:47:6050.060 [main]DEBUG --Djava.net.preferIPv4Stack: false
|>>15:47:6050.060 [main]DEBUG --Djava.net.preferIPv6Addresses: false
|>>15:47:6850.068 [main]DEBUG -Loopback interface: lo0 (lo0, 0:0:0:0:0:0:0:1%lo0)
|>>15:47:7050.070 [main]DEBUG -Failed to get SOMAXCONN from sysctl and file /proc/sys/net/core/somaxconn. Default: 128
|>>15:47:7750.077 [main]DEBUG --Dio.netty.machineId: ac:de:48:ff:fe:00:11:22 (auto-detected)
|>>15:47:9350.093 [main]DEBUG --Dio.netty.leakDetection.level: simple
|>>15:47:9350.093 [main]DEBUG --Dio.netty.leakDetection.targetRecords: 4
|>>15:47:12650.126 [main]DEBUG --Dio.netty.allocator.numHeapArenas: 24
|>>15:47:12650.126 [main]DEBUG --Dio.netty.allocator.numDirectArenas: 24
|>>15:47:12650.126 [main]DEBUG --Dio.netty.allocator.pageSize: 8192
|>>15:47:12650.126 [main]DEBUG --Dio.netty.allocator.maxOrder: 11
|>>15:47:12650.126 [main]DEBUG --Dio.netty.allocator.chunkSize: 16777216
|>>15:47:12650.126 [main]DEBUG --Dio.netty.allocator.smallCacheSize: 256
|>>15:47:12650.126 [main]DEBUG --Dio.netty.allocator.normalCacheSize: 64
|>>15:47:12650.126 [main]DEBUG --Dio.netty.allocator.maxCachedBufferCapacity: 32768
|>>15:47:12650.126 [main]DEBUG --Dio.netty.allocator.cacheTrimInterval: 8192
|>>15:47:12750.127 [main]DEBUG --Dio.netty.allocator.cacheTrimIntervalMillis: 0
|>>15:47:12750.127 [main]DEBUG --Dio.netty.allocator.useCacheForAllThreads: true
|>>15:47:12750.127 [main]DEBUG --Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
|>>15:47:14250.142 [main]DEBUG --Dio.netty.allocator.type: pooled
|>>15:47:14350.143 [main]DEBUG --Dio.netty.threadLocalDirectBufferSize: 0
|>>15:47:14350.143 [main]DEBUG --Dio.netty.maxThreadLocalCharBufferSize: 16384
|>>15:47:56650.566 [nioEventLoopGroup-2-1]DEBUG -Default protocols (JDK): [TLSv1.2] 
|>>15:47:56650.566 [nioEventLoopGroup-2-1]DEBUG -Default cipher suites (JDK): [TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384]
|>>15:47:59850.598 [nioEventLoopGroup-2-1]DEBUG --Dio.netty.buffer.checkAccessible: true
|>>15:47:59850.598 [nioEventLoopGroup-2-1]DEBUG --Dio.netty.buffer.checkBounds: true
|>>15:47:59950.599 [nioEventLoopGroup-2-1]DEBUG -Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@29a9f82a
Channel Writtable: true
Handshake Complete
Handshake Failed
javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
InboundHandler: channelActive
ChannelHandlerContext(SSLOutboundHandler#0, [id: 0x450dea71, L:0.0.0.0/0.0.0.0:64179 ! R:https://v250005-iflmap.avtsbhf.us3.hana.ondemand.com/169.145.118.162:443

**Comment by chrisvest** [comment]
Netty inspects `javax.net.ssl.SSLContext.getDefaultSSLParameters().getProtocols()` to see what protocols are supported by the JDK, and TLSv1.0 and TLSv1.1 are not in that list. Your configuration to enable these might not be correct. An alternative path is to use a different SSL engine.

**Comment by Sandeep-CodeAcc** [comment]
> Netty inspects `javax.net.ssl.SSLContext.getDefaultSSLParameters().getProtocols()` to see what protocols are supported by the JDK, and TLSv1.0 and TLSv1.1 are not in that list. Your configuration to enable these might not be correct. An alternative path is to use a different SSL engine.

Do you mean that even if I am setting protocols by following statement:
`SslContextBuilder ctxBuilder = SslContextBuilder.forClient().sslProvider(SslProvider.JDK).startTls(true).protocols(new String[]{"TLSv1.1"})`
and enabling TLS 1.0 and 1.1 from Java Control Panel, TLSv1.0 and TLSv1.1 will not appear in list of protocols supported by JDK?
How can I set up different SSL Engine, since I am using aforementioned statement to create SSLContext and consuming `#newEngine(ByteBufAllocator.DEFAULT)` method on SSLContext to create the SSLEngine.

**Comment by Sandeep-CodeAcc** [comment]
If you possible can you please share a test code where I can do an handshake over TLSv1.0 and TLSv1.1 protocol using Netty?
