### ISSUE TITLE
libnetty_transport_native_epoll_x86_64.so contains unsafety compilation options

### ISSUE THREAD

**Issue by jakemiao735** [netty/netty#11750]
### Expected behavior
Binary jar of netty has no unsafety compilation problems

### Actual behavior
Binary jar of netty-transport-native-epoll-4.1.62.Final-linux-x86_64.jar integrates a so file, which is libnetty_transport_native_epoll_x86_64.so. 
From binary security scanning I found some safety compilation options hasn't open.
such as BIND_NOW(Bind Now) RELRO(GOT table protection) SP(Stack protection) FS(Fortify Source) Ftrapv(Integer overflow check) Strip(Delete Symbol Table).

### Steps to reproduce
binary security scanning

### Minimal yet complete reproducer code (or URL to code)
NA

### Netty version
4.1.62.Final

### JVM version (e.g. `java -version`)
Java 1.8.0_242

### OS version (e.g. `uname -a`)
Linux Centos 8.2

**Comment by chrisvest** [comment]
Hi @jakemiao735
If you know what flags are good to add, feel free to open a PR!

**Comment by normanmaurer** [comment]
Lets close this one
