### ISSUE TITLE
I think I found a bug

### ISSUE THREAD

**Issue by GeXin666** [netty/netty#11814]
### Expected behavior
        ByteBuf buf = ByteBufAllocator.DEFAULT.buffer(32);
        //ByteBuf buf = Unpooled.buffer(32);
        buf.writeInt(32);

        ByteBuf buf2 = buf.retainedSlice();
        System.out.println(buf.refCnt());
        System.out.println(buf2.refCnt());
        buf2.release();
        buf2.release();
The above code reports an error!!!
Exception in thread "main" io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1

but The code below runs fine，way？？？？
        //ByteBuf buf = ByteBufAllocator.DEFAULT.buffer(32);
        ByteBuf buf = Unpooled.buffer(32);
        buf.writeInt(32);

        ByteBuf buf2 = buf.retainedSlice();
        System.out.println(buf.refCnt());
        System.out.println(buf2.refCnt());
        buf2.release();
        buf2.release();

### Netty version
4.1.49.Final
### JVM version (e.g. `java -version`)
jdk11
### OS version (e.g. `uname -a`)
windows-10

**Comment by chrisvest** [comment]
@GeXin666 That is to be expected. A retaining buffer, such as a slice or duplicate, must itself be released for the retain to be undone.

Avoid relying on the refCnt value, and instead pair retains and releases correctly:

```java
ByteBuf parent = …
ByteBuf child = parent.retainedSlice();
child.release();
parent.release();
```

The above will work regardless of the ByteBuf implementation.
