### ISSUE TITLE
【pom】【bug】Could not find artifact io.netty:netty-tcnative:jar:linux-aarch_64:2.0.44.Final in maven-mirror (https://repo1.maven.org/maven2/)

### ISSUE THREAD

**Issue by MoonLord-LM** [netty/netty#11834]
The classifier of【netty-tcnative】is not correct?
The pom of 【netty-bom-4.1.70.Final.pom】 is something like this:

```
            <!-- https://mvnrepository.com/artifact/io.netty/netty-bom -->
            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-bom</artifactId>
                <version>4.1.70.Final</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

```
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-tcnative</artifactId>
        <version>${tcnative.version}</version>
        <classifier>linux-aarch_64</classifier>
      </dependency>
```

But the file is not right?

【netty-tcnative-2.0.45.Final-linux-aarch_64-fedora.jar】does not exist?
【netty-tcnative-2.0.45.Final-linux-aarch_64.jar】does exist!

Try these links: 

https://repo1.maven.org/maven2/io/netty/netty-tcnative/2.0.45.Final/netty-tcnative-2.0.45.Final-linux-aarch_64-fedora.jar
https://repo1.maven.org/maven2/io/netty/netty-tcnative/2.0.45.Final/netty-tcnative-2.0.45.Final-linux-aarch_64.jar

**Comment by MoonLord-LM** [comment]
404 not found:
https://repo1.maven.org/maven2/io/netty/netty-tcnative/2.0.45.Final/netty-tcnative-2.0.45.Final-linux-aarch_64.jar

**Comment by normanmaurer** [comment]
Thats a bug... let me fix it.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/11838
