### ISSUE TITLE
Link in security-policy for reporting security issues is invalid

### ISSUE THREAD

**Issue by AndreasBrieg** [netty/netty#11832]
### Expected behavior

The security policy under https://github.com/netty/netty/security/policy should specify a valid link to report security issues.

### Actual behavior

The link specified leads to a 404 page.

### Steps to reproduce

- go to security/security-policy
- click on the provided link for reporting a security issue

**Comment by AndreasBrieg** [comment]
I just saw that discussion: https://groups.google.com/g/netty/c/dcTyF_0SeoU/m/Z07SsSEx_HEJ - does this mean I should be sending an email to netty-security@googlegroups.com for reporting an issue? If so this should be explicitly mentioned in the security policy.

**Comment by normanmaurer** [comment]
Yes please doo so... I will add it.

**Comment by normanmaurer** [comment]
This was fixed by 684c1dd1628e9c87ba03cac6d24ebe4d9ad4e471
