### ISSUE TITLE
netty uses unsafe.Allocatememory() cause native memory leak 

### ISSUE THREAD

**Issue by caizy-2020** [netty/netty#11835]
Hey,

In the production environment, we found that the memory occupied by the program has been increasing. Using the `top `command, we found that the value of `RES `has been increasing, even exceeding `Xmx`. We use `jconsole.exe` to observe that the number of threads and classes is stable, and the size of heap memory and meta space are within the normal range. Therefore, **we begin to suspect that the program is constantly occupying native memory and is not released.**

When we use gperftools to analyze the memory allocation occupied by the program, **we will find that the method `unsafe.Allocatememory0` occupies a very large proportion of memory and increases over time**.

![141609235-184610ca-3bb6-4b0c-9840-3ba77ee76662](https://user-images.githubusercontent.com/65394715/141644580-ab714120-d186-4a10-ae64-7bcbdbfd950f.png)
![141609283-0cafa3b4-b4c5-4f94-957b-b36660990898](https://user-images.githubusercontent.com/65394715/141644584-9d43822a-96f3-472f-98fc-9ef4c751f173.png)

This is the original PDF file generated using gperftools analyzer memory
[redisson-demo_1318.pdf](https://github.com/netty/netty/files/7532095/redisson-demo_1318.pdf)
[redisson-demo_1450.pdf](https://github.com/netty/netty/files/7532097/redisson-demo_1450.pdf)

After debugging with debug, **it is found that the thread `redisson-netty` calls `unsafe.Allocatememory()`**.

![image](https://user-images.githubusercontent.com/65394715/141644370-81048657-9264-4c79-bbc5-95f9f36368d4.png)

stack info
```
allocateMemory:614, Unsafe (jdk.internal.misc)
<init>:122, DirectByteBuffer (java.nio)
allocateDirect:317, ByteBuffer (java.nio)
allocateDirect:645, PoolArena$DirectArena (io.netty.buffer)
newChunk:621, PoolArena$DirectArena (io.netty.buffer)
allocateNormal:204, PoolArena (io.netty.buffer)
tcacheAllocateSmall:174, PoolArena (io.netty.buffer)
allocate:136, PoolArena (io.netty.buffer)
allocate:128, PoolArena (io.netty.buffer)
newDirectBuffer:378, PooledByteBufAllocator (io.netty.buffer)
directBuffer:187, AbstractByteBufAllocator (io.netty.buffer)
directBuffer:178, AbstractByteBufAllocator (io.netty.buffer)
ioBuffer:131, AbstractByteBufAllocator (io.netty.buffer)
allocateBuffer:140, MessageToByteEncoder (io.netty.handler.codec)
write:105, MessageToByteEncoder (io.netty.handler.codec)
write:76, CommandEncoder (org.redisson.client.handler)
invokeWrite0:717, AbstractChannelHandlerContext (io.netty.channel)
invokeWrite:709, AbstractChannelHandlerContext (io.netty.channel)
write:792, AbstractChannelHandlerContext (io.netty.channel)
write:702, AbstractChannelHandlerContext (io.netty.channel)
write:120, MessageToByteEncoder (io.netty.handler.codec)
write:45, CommandBatchEncoder (org.redisson.client.handler)
invokeWrite0:717, AbstractChannelHandlerContext (io.netty.channel)
invokeWrite:709, AbstractChannelHandlerContext (io.netty.channel)
write:792, AbstractChannelHandlerContext (io.netty.channel)
write:702, AbstractChannelHandlerContext (io.netty.channel)
write:115, ChannelDuplexHandler (io.netty.channel)
write:97, CommandsQueue (org.redisson.client.handler)
invokeWrite0:717, AbstractChannelHandlerContext (io.netty.channel)
invokeWriteAndFlush:764, AbstractChannelHandlerContext (io.netty.channel)
write:790, AbstractChannelHandlerContext (io.netty.channel)
writeAndFlush:758, AbstractChannelHandlerContext (io.netty.channel)
writeAndFlush:1020, DefaultChannelPipeline (io.netty.channel)
writeAndFlush:299, AbstractChannel (io.netty.channel)
sendData:123, CommandsQueue (org.redisson.client.handler)
write:100, CommandsQueue (org.redisson.client.handler)
invokeWrite0:717, AbstractChannelHandlerContext (io.netty.channel)
invokeWriteAndFlush:764, AbstractChannelHandlerContext (io.netty.channel)
write:790, AbstractChannelHandlerContext (io.netty.channel)
writeAndFlush:758, AbstractChannelHandlerContext (io.netty.channel)
writeAndFlush:808, AbstractChannelHandlerContext (io.netty.channel)
writeAndFlush:1025, DefaultChannelPipeline (io.netty.channel)
writeAndFlush:294, AbstractChannel (io.netty.channel)
send:169, RedisConnection (org.redisson.client)
async:215, RedisConnection (org.redisson.client)
async:187, RedisConnection (org.redisson.client)
async:183, RedisConnection (org.redisson.client)
channelActive:89, BaseConnectionHandler (org.redisson.client.handler)
invokeChannelActive:230, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelActive:216, AbstractChannelHandlerContext (io.netty.channel)
fireChannelActive:209, AbstractChannelHandlerContext (io.netty.channel)
channelActive:1398, DefaultChannelPipeline$HeadContext (io.netty.channel)
invokeChannelActive:230, AbstractChannelHandlerContext (io.netty.channel)
invokeChannelActive:216, AbstractChannelHandlerContext (io.netty.channel)
fireChannelActive:895, DefaultChannelPipeline (io.netty.channel)
fulfillConnectPromise:305, AbstractNioChannel$AbstractNioUnsafe (io.netty.channel.nio)
finishConnect:335, AbstractNioChannel$AbstractNioUnsafe (io.netty.channel.nio)
processSelectedKey:707, NioEventLoop (io.netty.channel.nio)
processSelectedKeysOptimized:655, NioEventLoop (io.netty.channel.nio)
processSelectedKeys:581, NioEventLoop (io.netty.channel.nio)
run:493, NioEventLoop (io.netty.channel.nio)
run:989, SingleThreadEventExecutor$4 (io.netty.util.concurrent)
run:74, ThreadExecutorMap$2 (io.netty.util.internal)
run:30, FastThreadLocalRunnable (io.netty.util.concurrent)
run:834, Thread (java.lang)
```

After modifying the redisson configuration so that redisson is no longer used to connect to redis, we use `gperftools `to observe that there is no `Unsafe_AllocateMemory0`, and the memory occupied by the program remains stable and will not increase,**so we now suspect that netty caused the program's native memory leak**

### Expected behavior
We hope to get your help so that we can use redisson without increasing the memory all the time

### Minimal yet complete reproducer code (or URL to code)
https://github.com/redisson/redisson/files/7531565/redisson_demo.zip

1. unzip redisson_ demo.zip
2. modify start.sh to set your redis address
3. execute start.sh to start the jar

### Netty version
`4.1.48.Final`

### JVM version (e.g. `java -version`)
redis `5.0.12`
redisson `3.12.4`
springboot `2.4.2`
openjdk `version "11" 2018-09-25`

### OS version (e.g. `uname -a`)
Linux

**Comment by caizy-2020** [comment]
`jstack `info
[jstack.txt](https://github.com/netty/netty/files/7533508/jstack.txt)

**Comment by normanmaurer** [comment]
You can change this by using `-Dio.netty.maxDirectMemory=0`

**Comment by caizy-2020** [comment]
> You can change this by using `-Dio.netty.maxDirectMemory=0`

We've tried this scheme, but it didn't work.
**We even tried to use `System.setProperty("io.netty.noUnsafe","true")`**

On the premise of using `-Dio.netty.maxDirectMemory=0`, if there is `redisson-netty`, we can still find that `unsafe.allocatememory0` is called by using the tool `gperftools`, but this will not happen when we remove` redisson-netty`

This is the memory map obtained by using the tool `gperftools`
[withRedisson-netty_11151930.pdf](https://github.com/netty/netty/files/7538515/withRedisson-netty_11151930.pdf)
[noRedisson-netty_11151950.pdf](https://github.com/netty/netty/files/7538516/noRedisson-netty_11151950.pdf)

**Comment by chrisvest** [comment]
Note that if you use the `System.setProperty(…)`, you have to do so before any netty classes are loaded. These properties are read once on class-load time, and then cached.

**Comment by caizy-2020** [comment]
> Note that if you use the `System.setProperty(…)`, you have to do so before any netty classes are loaded. These properties are read once on class-load time, and then cached.

how about i use `-Dio.netty.noUnsafe=true`?

**Comment by chrisvest** [comment]
Yes, that works.

**Comment by caizy-2020** [comment]
> Yes, that works.

It's very disappointing.  After many tests, we found that `-Dio.netty.noUnsafe=true` didn't work, and the test results are the same as this https://github.com/netty/netty/issues/11835#issuecomment-968850027

**Comment by normanmaurer** [comment]
is redision shading netty by any chance ?

**Comment by caizy-2020** [comment]
> is redision shading netty by any chance ?

I once submitted this issue to `redisson`,https://github.com/redisson/redisson/issues/3945, but they said that the memory allocation is controlled by `netty`, so I submitted this issue here

**Comment by caizy-2020** [comment]
> is redision shading netty by any chance ?

Through debugging class `io.netty.util.internal.platformdependent`, I found that these two parameters are valid and are not overwritten by `redisson`

![企业微信截图_20211116195424](https://user-images.githubusercontent.com/65394715/141981824-bca80a9b-8b83-4142-8572-389e8b596af2.png)

After using two parameters:
![企业微信截图_20211116195619](https://user-images.githubusercontent.com/65394715/141981875-f4994531-9d6a-4e9f-a284-31b1d1085451.png)

You can't see the redisson correlation in the deeper code

**Comment by caizy-2020** [comment]
> @caizy-2020 if you use redisson-all netty will be shaded

We use `reisson`,but we haven't used `reisson all`

```
<dependency>
    <groupId>org.redisson</groupId>
    <artifactId>redisson</artifactId>
    <version>3.12.4</version>
</dependency>
```
![企业微信截图_20211117011117](https://user-images.githubusercontent.com/65394715/142032826-d9f39ea6-e753-4314-b44a-e266a99fff57.png)

**Comment by caizy-2020** [comment]
**I have used `-Dio.netty.leakDetectionLevel=paranoid`, but no `LEAK `is found in the log. Does this mean that there is no netty memory leak?**
![企业微信截图_20211117110649](https://user-images.githubusercontent.com/65394715/142130826-f790cba9-f007-416a-b9d3-f25ba89cc222.png)


When `redisson `is removed, `unsafe_Allocatememory0` does not exist in the memory allocation graph, but it exists when `redisson `is used. According to this phenomenon, and through my debugging of the demo program, **it can be determined that `unsafe_Allocatememory0` is called and unreleased stack information is among the following three**

[stack_1.txt](https://github.com/netty/netty/files/7551752/stack_1.txt)
[stack_2.txt](https://github.com/netty/netty/files/7551750/stack_2.txt)
[stack_3.txt](https://github.com/netty/netty/files/7551751/stack_3.txt)

All of them are called `unsafe.allocatememory0` by `netty`

So this is very confusing. I can't think of any other causes of native memory leakage. Is it caused by the `open JDK`?

**Comment by SplotyCode** [comment]
Did you ever ran into Problems because of this? It is possible that the resource are not cleaned because there is no reason for it. The Point of the buffer pooling is that buffer (or areas of it) can be reused so they are not deallocated as they are shared. You can use an UnpooledByteBufAllocator if you want to avoid that

**Comment by caizy-2020** [comment]
> Did you ever ran into Problems because of this? It is possible that the resource are not cleaned because there is no reason for it. The Point of the buffer pooling is that buffer (or areas of it) can be reused so they are not deallocated as they are shared. You can use an UnpooledByteBufAllocator if you want to avoid that

![企业微信截图_20211117141338](https://user-images.githubusercontent.com/65394715/142145125-d319daca-a8b2-4068-a8f0-efc6da57c1a9.png)

So you mean like this?
`-Dio.netty.allocator.type=unpooled`

**Comment by franz1981** [comment]
@caizy-2020 
I think that the leak analysis is pointing to something that's not a leak at all: Netty use native (and heap) memory pooling and that looks like a "leak" indeed, because memory will be released only on application stop. 
This issue can be closed I think.

**Comment by caizy-2020** [comment]
> @caizy-2020 I think that the leak analysis is pointing to something that's not a leak at all: Netty use native (and heap) memory pooling and that looks like a "leak" indeed, because memory will be released only on application stop. This issue can be closed I think.

I understand what you mean, but isn't it a problem that the memory occupied is becoming larger and larger?
We found that the memory occupied by method `unsafe.Allocatememory0` becomes larger and larger over time, and the memory occupied by the whole application is also increasing

**Comment by franz1981** [comment]
> We found that the memory occupied by method unsafe.Allocatememory0 becomes larger and larger over time, and the memory occupied by the whole application is also increasing

If the leak detector hasn't found anything abnormal it just means that the memory wasn't enough to cope with the load: similarly to a java heap, that grows to cope with the load and fail with OOM if the max capacity isn't enough.

> but isn't it a problem that the memory occupied is becoming larger and larger?

That's a smart question indeed: we (I'm a user of Artemis, a messaging broker relying on Netty for networking layer) found that there are cases where it would be nice, under certain cicustances, that netty will return back memory (similarly to some recent changes on G1GC, Shenandoah and ZGC) to the operating system, and I'm  sure the allocator can be changed (making it to diverge from what jemalloc does) in order to do it BUT this is not implemented.
Feel free to add a RFC and I will happily try to help there, because I thunk this can be a useful feature for containerized apps :)

**Comment by caizy-2020** [comment]
> If the leak detector hasn't found anything abnormal it just means that the memory wasn't enough to cope with the load: similarly to a java heap, that grows to cope with the load and fail with OOM if the max capacity isn't enough.

We have monitored the `Java heap` memory for a long time and found no abnormality. At the same time, there has been no `OOM `exception in the production and test environment, because the heap memory has always been small. Now the problem in production is that the system memory is insufficient because the memory occupied by each application is gradually becoming larger, so the operating system will automatically kill other applications

**Comment by caizy-2020** [comment]
> Did you ever ran into Problems because of this? It is possible that the resource are not cleaned because there is no reason for it. The Point of the buffer pooling is that buffer (or areas of it) can be reused so they are not deallocated as they are shared. You can use an UnpooledByteBufAllocator if you want to avoid that

[@SplotyCode](url) Fortunately, after setting `-Dio.netty.allocator.type=unpooled` , no method `unsafe.Allocatememory0` has been called in the memory allocation diagram obtained through `gperftools` , but we are still monitoring the change of memory occupied by the application

**But I have another question. When we use `unpool `mode, will this reduce netty performance? Will it affect the memory application or release of netty?**

**Comment by SplotyCode** [comment]
Yeah it will reduce netty performance that's the reason this feature exists.
