### ISSUE TITLE
InboundHttp2ToHttpAdapter fires exception on reading RST_STREAM frame

### ISSUE THREAD

**Issue by BrianRothermich** [netty/netty#11836]
### Issue
When using the HTTP2 Connection API, `InboundHttp2ToHttpAdapter` fires an exception when reading an RST_STREAM frame [here](https://github.com/netty/netty/blob/7d34282f9d2ffdd64c91cb4780b09902d9779b92/codec-http2/src/main/java/io/netty/handler/codec/http2/InboundHttp2ToHttpAdapter.java#L281-L290):

```    
@Override
public void onRstStreamRead(ChannelHandlerContext ctx, int streamId, long errorCode) throws Http2Exception {
    Http2Stream stream = connection.stream(streamId);
    FullHttpMessage msg = getMessage(stream);
    if (msg != null) {
        onRstStreamRead(stream, msg);
    }
    ctx.fireExceptionCaught(Http2Exception.streamError(streamId, Http2Error.valueOf(errorCode),
            "HTTP/2 to HTTP layer caught stream reset"));
}
```

Per [RFC 7540](https://datatracker.ietf.org/doc/html/rfc7540#section-6.4) there are a number of valid cases where a client may send an RST_STREAM frame.  

If using the `DefaultHttp2ConnectionDecoder` the error cases for reading an RST_STREAM frame described in RFC 7540 are handled [here](https://github.com/netty/netty/blob/7d34282f9d2ffdd64c91cb4780b09902d9779b92/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L425-L440) before calling the supplied `Http2FrameListener`.

Firing an exception here seems to be conservative default behavior that requires extending `InboundHttp2ToHttpAdapter` or implementing a custom `Http2FrameListener` to bypass. It also seems to differ from the HTTP2 codec/child-channel API in making the assumption that an exception should be fired when reading an RST_STREAM frame. 

I understand the intent is to deprecate this API in favor of the child-channel API, but is there any reason not to remove this exception?

### Netty version
4.1.68

### JVM version (e.g. `java -version`)
11

**Comment by normanmaurer** [comment]
@BrianRothermich I agree I think we should handle it the same as in `DefaultHttp2ConnectionDecoder`. Want to provide a PR ?

**Comment by normanmaurer** [comment]
@BrianRothermich are you playing to work on a PR ?

**Comment by BrianRothermich** [comment]
@normanmaurer yes. I should have one soon
