### ISSUE TITLE
Multithreading reclaiming objects in the Recycler object pool issue problem

### ISSUE THREAD

**Issue by huibinliupush** [netty/netty#11864]
### Netty version
4.1.70.final

### Issue

The issue shown in the picture below，Thread 2 is recycling objects which belongs to stack1 created by thread 1。

If thread1 was GC'ed at this moment，i think thread2 does not need to add this object to the `weakOrderQueue node` which is in the `Stack1` any more。 because `stack1` will be GC'ed sooner or later。This object will never be used again even if it is recycled.

![netty recycler issue](https://user-images.githubusercontent.com/5794695/143539720-36080ab2-458e-4c52-b6cb-db0c2f6f602d.png)

But the `Recycler`'s related source code about recycling objects does not deal with the situation of `threadRef.get()  == null`,
and still continue to add objects to the weakOrderQueue node. I think this is a waste of time.  the sooner we deal with the situation of `threadRef.get()  == null` , the better。

```
private static final class Stack<T> {

        void push(DefaultHandle<?> item) {
            Thread currentThread = Thread.currentThread();
            if (threadRef.get() == currentThread) {
                // The current Thread is the thread that belongs to the Stack, we can try to push the object now.
                pushNow(item);
            } else {
                // The current Thread is not the one that belongs to the Stack
                // (or the Thread that belonged to the Stack was collected already), we need to signal that the push
                // happens later.
                pushLater(item, currentThread);
            }
        }

}
```

**Comment by laosijikaichele** [comment]
@chrisvest I think the following issue seems still exists in the newest 4.1.72.Final version.

"When thread2 is recycling objects which created by thread1. If thread1 was GC'ed at this moment, thread2 still put the objects back to thread1's queue."

Corrects me if I wrongly understood it.

**Comment by chrisvest** [comment]
@laosijikaichele Right, yeah… I'm not sure it makes sense to salvage those objects. We could be in a system shutdown phase; there might not be other threads to offload the objects to; we'd have to centrally track threads joining and leaving the pool.

**Comment by laosijikaichele** [comment]
@chrisvest  What about we store the thread to `WeakReference` in `io.netty.util.Recycler.LocalPool`, and do the `null` check while recycling, like the following:
```
private static final class LocalPool<T> {
    ...
    private final WeakReference<Thread> threadRef = new WeakReference<>(Thread.currentThread());
    ...
}

private static final class DefaultHandle<T> implements Handle<T> {
    @Override
    public void recycle(Object object) {
        ...
        if (localPool.threadRef.get() == null) {
            return; // Do not need to recycle;
        }
        ...
    }
}
```
WDYT?

**Comment by chrisvest** [comment]
@laosijikaichele Not a fan of adding back `WeakReferences` when we just got rid of them. They have some overhead that can impact GC pause times. But we can mark the local pool in `FastThreadLocal.onRemoval` somehow, and avoid adding handles to the queue based on that.
