### ISSUE TITLE
[Question] Regarding DEFAULT_LOW_WATER_MARK and DEFAULT_HIGH_WATER_MARK

### ISSUE THREAD

**Issue by RoySunnySean007** [netty/netty#11874]
Dear Netty experts,

Regarding io.netty.channel.WriteBufferWaterMark, we have default value for LOW_WATER_MARK and HIGH_WATER_MARK, could u please kindly let me know how we set the these two default value?
1. If I set it bigger, what's the side effect? 

```
    private static final int DEFAULT_LOW_WATER_MARK = 32 * 1024;
    private static final int DEFAULT_HIGH_WATER_MARK = 64 * 1024;
```
2. BTW, can we use ```channel.unsafe().outboundBuffer()``` to monitor usage?
Refer: https://stackoverflow.com/questions/64930528/what-happens-to-writes-when-channeloutboundbuffer-is-full
```
Looking at the source for ChannelOutboundBuffer in 4.1.37, the method addMessage always adds incoming messages to an internal linked list, regardless of the state of isWritable. This list grows unbounded.

The total byte length of this buffer is reachable via channel.unsafe().outboundBuffer().totalPendingWriteBytes().

For an indirect value, if you don't want to use unsafe(), you can alternatively use channel.bytesBeforeWritable() which will return the queued bytes minus the low watermark. 
```

Really appreciate ur great help in advance!

Thanks,
Roy

**Comment by needmorecode** [comment]
@RoySunnySean007 As you mentioned in the first question, if you set the water marks bigger, then more memory probably will be used in the buffer. So the program memory will more likely to reach the limit when the traffic is heavy.

**Comment by RoySunnySean007** [comment]
Thx @huibinliupush and @needmorecode !
