### ISSUE TITLE
netty merge the ssl handshake message

### ISSUE THREAD

**Issue by bluefreezing** [netty/netty#11871]
When a link is set up between the client and the server, during the SSL handshake, Netty combines the SSL handshake messages and sends them.
Like this:
![image](https://user-images.githubusercontent.com/84161895/143676163-988f8782-f56e-45ca-8085-422927761479.png)

netty merge these message:
Server Hello/Certificate/Certificate Request/Server Key Exchange/Server Hello Done

But I use the jdk SSLServerSocket, these messages will send one by one:
![image](https://user-images.githubusercontent.com/84161895/143676213-63a64c1b-93a0-4df4-aee9-1e1666b758b1.png)

The reason for this problem is that the client buffer is very small, and message merging causes SSL handshake failure.

Netty version 4.1.63

JVM version 1.8.0_302

OS version linux

**Comment by chrisvest** [comment]
Do I understand it right that the receive buffer on the client-side is too small to fit the merged messages from the server?

**Comment by bluefreezing** [comment]
Yes. you are right.

**Comment by bluefreezing** [comment]
> Do I understand it right that the receive buffer on the client-side is too small to fit the merged messages from the server?

Yes. you are right. Is there a way to send messages separately?

**Comment by chrisvest** [comment]
I think your client is buggy.

The `SslHandler` does not have a configuration option for working around this.

You could insert a `ChannelOutboundHandler` in front of the `SslHandler` that will add a flush after every write, unless the SSL handshake has completed (you can add a listener to the `SslHandler.handshakeFuture` to flip an `AtomicBoolean` or something like that, for the purpose of notifying your outbound handler).
That should cause each message in the SSL handshake to be sent as an individual message.

**Comment by bluefreezing** [comment]
I try to insert a ChannelOutboundHandler in front of the SslHandler, but didn't work.
Is it possible for the SSLhandler to provide a configurable parameter for this scenario? 
It is too complicated to use the socket of JDK to implement the server. My client is an IoT device and has a small memory.

**Comment by normanmaurer** [comment]
Like @chrisvest said this is a bug on the client side... It must be able to handle multiple records in one input buffer.
