### ISSUE TITLE
IdleStateHandler can trigger Leak?

### ISSUE THREAD

**Issue by linking12** [netty/netty#11878]
LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
	io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:592)
	io.netty.handler.codec.http.HttpObjectEncoder.encode(HttpObjectEncoder.java:131)
	io.netty.handler.codec.http.HttpClientCodec$Encoder.encode(HttpClientCodec.java:202)
	io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
	io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:346)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:304)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:302)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1069)
	io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	java.base/java.lang.Thread.run(Thread.java:829)
#2:
	io.netty.buffer.AdvancedLeakAwareByteBuf.writeShort(AdvancedLeakAwareByteBuf.java:550)
	io.netty.buffer.ByteBufUtil.writeShortBE(ByteBufUtil.java:664)
	io.netty.handler.codec.http.HttpObjectEncoder.encode(HttpObjectEncoder.java:102)
	io.netty.handler.codec.http.HttpClientCodec$Encoder.encode(HttpClientCodec.java:202)
	io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
	io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:346)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:304)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:302)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1069)
	io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	java.base/java.lang.Thread.run(Thread.java:829)
#3:
	io.netty.buffer.AdvancedLeakAwareByteBuf.setShort(AdvancedLeakAwareByteBuf.java:292)
	io.netty.buffer.ByteBufUtil.setShortBE(ByteBufUtil.java:673)
	io.netty.handler.codec.http.HttpHeadersEncoder.encoderHeader(HttpHeadersEncoder.java:45)
	io.netty.handler.codec.http.HttpObjectEncoder.encodeHeaders(HttpObjectEncoder.java:192)
	io.netty.handler.codec.http.HttpObjectEncoder.encode(HttpObjectEncoder.java:101)
	io.netty.handler.codec.http.HttpClientCodec$Encoder.encode(HttpClientCodec.java:202)
	io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
	io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:346)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:304)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:302)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1069)
	io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	java.base/java.lang.Thread.run(Thread.java:829)
#4:
	io.netty.buffer.AdvancedLeakAwareByteBuf.setCharSequence(AdvancedLeakAwareByteBuf.java:388)
	io.netty.handler.codec.http.HttpHeadersEncoder.writeAscii(HttpHeadersEncoder.java:54)
	io.netty.handler.codec.http.HttpHeadersEncoder.encoderHeader(HttpHeadersEncoder.java:43)
	io.netty.handler.codec.http.HttpObjectEncoder.encodeHeaders(HttpObjectEncoder.java:192)
	io.netty.handler.codec.http.HttpObjectEncoder.encode(HttpObjectEncoder.java:101)
	io.netty.handler.codec.http.HttpClientCodec$Encoder.encode(HttpClientCodec.java:202)
	io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
	io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:346)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:304)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:302)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1069)
	io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	java.base/java.lang.Thread.run(Thread.java:829)
#5:
	io.netty.buffer.AdvancedLeakAwareByteBuf.setShort(AdvancedLeakAwareByteBuf.java:292)
	io.netty.buffer.ByteBufUtil.setShortBE(ByteBufUtil.java:673)
	io.netty.handler.codec.http.HttpHeadersEncoder.encoderHeader(HttpHeadersEncoder.java:41)
	io.netty.handler.codec.http.HttpObjectEncoder.encodeHeaders(HttpObjectEncoder.java:192)
	io.netty.handler.codec.http.HttpObjectEncoder.encode(HttpObjectEncoder.java:101)
	io.netty.handler.codec.http.HttpClientCodec$Encoder.encode(HttpClientCodec.java:202)
	io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
	io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:346)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:304)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:302)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1069)
	io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	java.base/java.lang.Thread.run(Thread.java:829)
#6:
	io.netty.buffer.AdvancedLeakAwareByteBuf.setCharSequence(AdvancedLeakAwareByteBuf.java:388)
	io.netty.handler.codec.http.HttpHeadersEncoder.writeAscii(HttpHeadersEncoder.java:54)
	io.netty.handler.codec.http.HttpHeadersEncoder.encoderHeader(HttpHeadersEncoder.java:39)
	io.netty.handler.codec.http.HttpObjectEncoder.encodeHeaders(HttpObjectEncoder.java:192)
	io.netty.handler.codec.http.HttpObjectEncoder.encode(HttpObjectEncoder.java:101)
	io.netty.handler.codec.http.HttpClientCodec$Encoder.encode(HttpClientCodec.java:202)
	io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
	io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:346)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:304)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:302)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1069)
	io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	java.base/java.lang.Thread.run(Thread.java:829)

```
  Netty Version: 4.1.67.Final
  Netty Client idleTimeout : 70s
  Tomcat Server KeepAliveTime: 60s
```

**Comment by hyperxpro** [comment]
More information is needed. Also, please use the Issue template.

**Comment by RoySunnySean007** [comment]
Dear Netty experts,

We encountered this issue as well, it's hard to reproduce this issue currently.  Could u please let me know the possible task list for safeExecute() method? So we can troubleshooting them one by one. 

Really appreciate ur great help in advance!

```
io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1069)
io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
java.base/java.lang.Thread.run(Thread.java:829)
```

```
    /**
     * Try to execute the given {@link Runnable} and just log if it throws a {@link Throwable}.
     */
    protected static void safeExecute(Runnable task) {
        try {
            task.run();
        } catch (Throwable t) {
            logger.warn("A task raised an exception. Task: {}", task, t);
        }
    }
```

Our netty version is 4.1.67.Final

Thanks,
Roy

**Comment by normanmaurer** [comment]
Please upgrade to latest version and reopen if its still an issue.
