### ISSUE TITLE
io.netty.internal.tcnative.Library.initialize crashes JVM

### ISSUE THREAD

**Issue by Zane-XY** [netty/netty#11879]
### Expected behavior
grpc-netty-shaded and netty-all can coexist.

### Actual behavior

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000001340353e0, pid=69021, tid=98823


---------------  T H R E A D  ---------------

Current thread (0x00007fd461acd800):  JavaThread "ForkJoinPool.commonPool-worker-19" daemon [_thread_in_native, id=98823, stack(0x00007000087ce000,0x00007000088ce000)]

Stack: [0x00007000087ce000,0x00007000088ce000],  sp=0x00007000088cbf78,  free space=1015k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x00000001340353e0
j  io.netty.internal.tcnative.Library.initialize(Ljava/lang/String;Ljava/lang/String;)Z+31
j  io.netty.handler.ssl.OpenSsl.initializeTcNative(Ljava/lang/String;)Z+3
j  io.netty.handler.ssl.OpenSsl.<clinit>()V+225
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x3b56d2]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x21a
V  [libjvm.dylib+0x39ce13]  InstanceKlass::call_class_initializer(Thread*)+0x19f
V  [libjvm.dylib+0x39c761]  InstanceKlass::initialize_impl(Thread*)+0x49f
V  [libjvm.dylib+0x51549b]  LinkResolver::resolve_static_call(CallInfo&, LinkInfo const&, bool, Thread*)+0x6b
V  [libjvm.dylib+0x51704d]  LinkResolver::resolve_invokestatic(CallInfo&, constantPoolHandle const&, int, Thread*)+0x35
V  [libjvm.dylib+0x3afe79]  InterpreterRuntime::resolve_invoke(JavaThread*, Bytecodes::Code)+0x22b
V  [libjvm.dylib+0x3b0499]  InterpreterRuntime::resolve_from_cache(JavaThread*, Bytecodes::Code)+0x37
j  io.netty.handler.ssl.SslProvider.isAlpnSupported(Lio/netty/handler/ssl/SslProvider;)Z+40
j  reactor.netty.http.Http2SslContextSpec.lambda$static$0(Lio/netty/handler/ssl/SslContextBuilder;)V+4
j  reactor.netty.http.Http2SslContextSpec$$Lambda$1695.accept(Ljava/lang/Object;)V+4
j  reactor.netty.tcp.AbstractProtocolSslContextSpec.configure(Ljava/util/function/Consumer;)Lreactor/netty/tcp/AbstractProtocolSslContextSpec;+12
j  reactor.netty.tcp.AbstractProtocolSslContextSpec.<init>(Lio/netty/handler/ssl/SslContextBuilder;)V+14
j  reactor.netty.http.Http2SslContextSpec.<init>(Lio/netty/handler/ssl/SslContextBuilder;)V+2
j  reactor.netty.http.Http2SslContextSpec.forClient()Lreactor/netty/http/Http2SslContextSpec;+7
j  reactor.netty.http.client.HttpClientSecure.<clinit>()V+3
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x3b56d2]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x21a
V  [libjvm.dylib+0x39ce13]  InstanceKlass::call_class_initializer(Thread*)+0x19f
V  [libjvm.dylib+0x39c761]  InstanceKlass::initialize_impl(Thread*)+0x49f
V  [libjvm.dylib+0x51549b]  LinkResolver::resolve_static_call(CallInfo&, LinkInfo const&, bool, Thread*)+0x6b
V  [libjvm.dylib+0x51704d]  LinkResolver::resolve_invokestatic(CallInfo&, constantPoolHandle const&, int, Thread*)+0x35
V  [libjvm.dylib+0x3afe79]  InterpreterRuntime::resolve_invoke(JavaThread*, Bytecodes::Code)+0x22b
V  [libjvm.dylib+0x3b0499]  InterpreterRuntime::resolve_from_cache(JavaThread*, Bytecodes::Code)+0x37
j  reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(Lreactor/netty/http/client/HttpClientConnect$HttpClientHandler;Lreactor/core/publisher/MonoSink;)V+61
j  reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$$Lambda$1683.accept(Ljava/lang/Object;)V+12
j  reactor.core.publisher.MonoCreate.subscribe(Lreactor/core/CoreSubscriber;)V+21
j  reactor.core.publisher.InternalMonoOperator.subscribe(Lreactor/core/CoreSubscriber;)V+33
j  reactor.core.publisher.FluxRetryWhen.subscribe(Lreactor/core/CoreSubscriber;Lreactor/util/retry/Retry;Lreactor/core/CorePublisher;)V+106
j  reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(Lreactor/core/CoreSubscriber;)Lreactor/core/CoreSubscriber;+9
j  reactor.core.publisher.InternalMonoOperator.subscribe(Lreactor/core/CoreSubscriber;)V+4
j  reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(Lreactor/core/CoreSubscriber;)V+49
j  reactor.core.publisher.InternalMonoOperator.subscribe(Lreactor/core/CoreSubscriber;)V+33
j  reactor.core.publisher.MonoDefer.subscribe(Lreactor/core/CoreSubscriber;)V+39
j  reactor.core.publisher.Mono.subscribe(Lorg/reactivestreams/Subscriber;)V+71
j  reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run()V+15
j  reactor.core.scheduler.WorkerTask.call()Ljava/lang/Void;+14
j  reactor.core.scheduler.WorkerTask.call()Ljava/lang/Object;+1
j  java.util.concurrent.ForkJoinTask$AdaptedCallable.exec()Z+5 java.base@11.0.11
j  java.util.concurrent.ForkJoinTask.doExec$$$capture()I+10 java.base@11.0.11
j  java.util.concurrent.ForkJoinTask.doExec()I+5 java.base@11.0.11
j  java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Ljava/util/concurrent/ForkJoinTask;Ljava/util/concurrent/ForkJoinPool$WorkQueue;I)V+12 java.base@11.0.11
j  java.util.concurrent.ForkJoinPool.scan(Ljava/util/concurrent/ForkJoinPool$WorkQueue;I)Z+182 java.base@11.0.11
j  java.util.concurrent.ForkJoinPool.runWorker(Ljava/util/concurrent/ForkJoinPool$WorkQueue;)V+25 java.base@11.0.11
j  java.util.concurrent.ForkJoinWorkerThread.run()V+24 java.base@11.0.11
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x3b56d2]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x21a
V  [libjvm.dylib+0x3b4b1c]  JavaCalls::call_virtual(JavaValue*, Klass*, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0xee
V  [libjvm.dylib+0x3b4bd8]  JavaCalls::call_virtual(JavaValue*, Handle, Klass*, Symbol*, Symbol*, Thread*)+0x62
V  [libjvm.dylib+0x43c0dd]  thread_entry(JavaThread*, Thread*)+0x78
V  [libjvm.dylib+0x77d062]  JavaThread::thread_main_inner()+0x82
V  [libjvm.dylib+0x77cea6]  JavaThread::run()+0x174
V  [libjvm.dylib+0x77ad88]  Thread::call_run()+0x68
V  [libjvm.dylib+0x6280e7]  thread_native_entry(Thread*)+0x139
C  [libsystem_pthread.dylib+0x6109]  _pthread_start+0x94
C  [libsystem_pthread.dylib+0x1b8b]  thread_start+0xf

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  io.netty.internal.tcnative.Library.aprMajorVersion()I+0
j  io.netty.internal.tcnative.Library.initialize(Ljava/lang/String;Ljava/lang/String;)Z+31
j  io.netty.handler.ssl.OpenSsl.initializeTcNative(Ljava/lang/String;)Z+3
j  io.netty.handler.ssl.OpenSsl.<clinit>()V+225
v  ~StubRoutines::call_stub
j  io.netty.handler.ssl.SslProvider.isAlpnSupported(Lio/netty/handler/ssl/SslProvider;)Z+40
j  reactor.netty.http.Http2SslContextSpec.lambda$static$0(Lio/netty/handler/ssl/SslContextBuilder;)V+4
j  reactor.netty.http.Http2SslContextSpec$$Lambda$1695.accept(Ljava/lang/Object;)V+4
j  reactor.netty.tcp.AbstractProtocolSslContextSpec.configure(Ljava/util/function/Consumer;)Lreactor/netty/tcp/AbstractProtocolSslContextSpec;+12
j  reactor.netty.tcp.AbstractProtocolSslContextSpec.<init>(Lio/netty/handler/ssl/SslContextBuilder;)V+14
j  reactor.netty.http.Http2SslContextSpec.<init>(Lio/netty/handler/ssl/SslContextBuilder;)V+2
j  reactor.netty.http.Http2SslContextSpec.forClient()Lreactor/netty/http/Http2SslContextSpec;+7
j  reactor.netty.http.client.HttpClientSecure.<clinit>()V+3
v  ~StubRoutines::call_stub
j  reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(Lreactor/netty/http/client/HttpClientConnect$HttpClientHandler;Lreactor/core/publisher/MonoSink;)V+61
j  reactor.netty.http.client.HttpClientConnect$MonoHttpConnect$$Lambda$1683.accept(Ljava/lang/Object;)V+12
j  reactor.core.publisher.MonoCreate.subscribe(Lreactor/core/CoreSubscriber;)V+21
j  reactor.core.publisher.InternalMonoOperator.subscribe(Lreactor/core/CoreSubscriber;)V+33
j  reactor.core.publisher.FluxRetryWhen.subscribe(Lreactor/core/CoreSubscriber;Lreactor/util/retry/Retry;Lreactor/core/CorePublisher;)V+106
j  reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(Lreactor/core/CoreSubscriber;)Lreactor/core/CoreSubscriber;+9
j  reactor.core.publisher.InternalMonoOperator.subscribe(Lreactor/core/CoreSubscriber;)V+4
j  reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(Lreactor/core/CoreSubscriber;)V+49
j  reactor.core.publisher.InternalMonoOperator.subscribe(Lreactor/core/CoreSubscriber;)V+33
j  reactor.core.publisher.MonoDefer.subscribe(Lreactor/core/CoreSubscriber;)V+39
j  reactor.core.publisher.Mono.subscribe(Lorg/reactivestreams/Subscriber;)V+71
j  reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run()V+15
j  reactor.core.scheduler.WorkerTask.call()Ljava/lang/Void;+14
j  reactor.core.scheduler.WorkerTask.call()Ljava/lang/Object;+1
j  java.util.concurrent.ForkJoinTask$AdaptedCallable.exec()Z+5 java.base@11.0.11
j  java.util.concurrent.ForkJoinTask.doExec$$$capture()I+10 java.base@11.0.11
j  java.util.concurrent.ForkJoinTask.doExec()I+5 java.base@11.0.11
j  java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Ljava/util/concurrent/ForkJoinTask;Ljava/util/concurrent/ForkJoinPool$WorkQueue;I)V+12 java.base@11.0.11
j  java.util.concurrent.ForkJoinPool.scan(Ljava/util/concurrent/ForkJoinPool$WorkQueue;I)Z+182 java.base@11.0.11
j  java.util.concurrent.ForkJoinPool.runWorker(Ljava/util/concurrent/ForkJoinPool$WorkQueue;)V+25 java.base@11.0.11
j  java.util.concurrent.ForkJoinWorkerThread.run()V+24 java.base@11.0.11
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x00000001340353e0

Register to memory mapping:

RAX=0x00000001340353e0 is an unknown value
RBX={method} {0x0000000133f822e8} 'aprMajorVersion' '()I' in 'io/netty/internal/tcnative/Library'
RCX=0x0000000000000009 is an unknown value
RDX=0x000000000000000a is an unknown value
RSP=0x00007000088cbf78 is pointing into the stack for thread: 0x00007fd461acd800
RBP=0x00007000088cbfc8 is pointing into the stack for thread: 0x00007fd461acd800
RSI=0x00007000088cbfd8 is pointing into the stack for thread: 0x00007fd461acd800
RDI=0x00007fd461acdb48 points into unknown readable memory: 0x0000000106b833a8 | a8 33 b8 06 01 00 00 00
R8 ={method} {0x0000000133f822e8} 'aprMajorVersion' '()I' in 'io/netty/internal/tcnative/Library'
R9 =0x00007fd463509380 points into unknown readable memory: 0x000000010eba23c0 | c0 23 ba 0e 01 00 00 00
R10=0x00000001180fa1b4 is at code_begin+1652 in an Interpreter codelet
method entry point (kind = native)  [0x00000001180f9b40, 0x00000001180fab40]  4096 bytes
R11=0x000000070f925368 is an oop: java.lang.Class 
{0x000000070f925368} - klass: 'java/lang/Class'
R12=0x0 is NULL
R13={method} {0x0000000133f822e8} 'aprMajorVersion' '()I' in 'io/netty/internal/tcnative/Library'
R14=0x00007000088cbfe0 is pointing into the stack for thread: 0x00007fd461acd800
R15=0x00007fd461acd800 is a thread

```

### Steps to reproduce

In the class path, there're 
- a library using grpc 1.30.2 shaded with netty 4.1.48.Final, netty-tcnative-boringssl-static 2.0.30.Final.
- a library depends on grpc-netty-shaded 1.31.1 and netty-tcnative-boringssl-static 2.0.31.Final
- a library depends on reactor-netty 1.0.7 (depends on netty 4.1.63.Final)

remove library 1 or library 2, does not throw errors, reactor-netty calls can return success.
start application with `-Dio.netty.handler.ssl.noOpenSsl=true` [openssl disabled](https://projectreactor.io/docs/netty/snapshot/reference/index.html#_ssl_and_tls), reactor-netty calls can return success.

Following the debugging process, when calling `aprMajorVersion` crashes the JVM.

### Netty version

The final resolved netty version is 4.1.65.Final with netty-tcnative-boringssl-static 2.0.39.Final. (There maybe other netty version defined in parent pom.)

### JVM version (e.g. `java -version`)
```
# JRE version: OpenJDK Runtime Environment Zulu11.48+21-NV (11.0.11+9) (build 11.0.11+9-LTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu11.48+21-NV (11.0.11+9-LTS, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
```

### OS version (e.g. `uname -a`)

Host: MacBookPro16,1 x86_64 2400 MHz, 16 cores, 16G, Darwin 19.6.0

**Comment by chrisvest** [comment]
You can use a `<dependencyManagement>` section in your pom file to force both libraries to use the same version of grpc-netty-shaded.

The issue is most likely that you have two different versions of shaded netty in your grpc dependencies, and these each bring their own native libraries, but at runtime they will both use the same native library (whichever shows up first in the class path) and for one of them it'll be the wrong one.

**Comment by Zane-XY** [comment]
@chrisvest 

`grpc-netty-shaded` is enforced in dependencyManagement. there's only one with version 1.31.1.
It looks like `grpc-netty-shaded` is conflicting with another self shaded netty lib.

Can I control "whichever shows up first in the class path"?

**Comment by vchekan** [comment]
I am getting the same SIGSEGV with the same stack trace. I reproduced minimalistic google cloud project which does only thing: access secret via google `com.google.cloud:google-cloud-secretmanager`.

This project does not have any dependency besides what google cloud requires to run spark ad access secrets yet it does already have a conflict?

build.gradle.kts:
``` 
dependencies {
    implementation("org.scala-lang:scala-library:2.12.14")
    compileOnly("org.apache.spark:spark-core_2.12:2.4.8")
    implementation(platform("com.google.cloud:libraries-bom:24.2.0"))
    implementation("com.google.cloud:google-cloud-secretmanager")
    implementation("com.typesafe:config:1.2.1")
}

tasks.shadowJar {
    archiveClassifier.set("uber")
    isZip64 = true
    append("reference.conf")

    relocate("com.google.common", "shade.com.google.common")
    relocate("com.google.protobuf", "shade.com.google.protobuf")
}
```

Main.scala:
```
class GcpSecrets(config: Config) extends SecretsProvider {
  override def read(name: String): String = {
    val project = config.getString("gcp.project")
    val client = SecretManagerServiceClient.create()
    try {
      val version = SecretVersionName.of(project, name, "latest")
      val response = client.accessSecretVersion(version)
      response.getPayload.getData.toStringUtf8
    } finally {
      client.close()
    }
  }
}
```

**Comment by normanmaurer** [comment]
I think we fixed this

**Comment by jlynet** [comment]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fcbcd000960, pid=46609, tid=0x00007fcbcd7ef700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.181-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  0x00007fcbcd000960
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x00007fcae70ea000):  JavaThread "vert.x-eventloop-thread-14" [_thread_in_native, id=46995, stack(0x00007fcbcd6ef000,0x00007fcbcd7f0000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x00007fcbcd000960

Registers:
RAX=0x00007fcbcd000960, RBX=0x00007fcbce5ba7d0, RCX=0x00007fcc380073d0, RDX=0x00007fcc3eb1d030
RSP=0x00007fcbcd7ed468, RBP=0x00007fcbcd7ed4b0, RSI=0x00007fcbcd7ed4c0, RDI=0x00007fcae70ea1f8
R8 =0x0000000000000000, R9 =0x000000000000000d, R10=0x00007fcc2901877b, R11=0x00007fcc3e51b540
R12=0x0000000000000000, R13=0x00007fcbce5ba7d0, R14=0x00007fcbcd7ed4c8, R15=0x00007fcae70ea000
RIP=0x00007fcbcd000960, EFLAGS=0x0000000000010283, CSGSFS=0x0000000000000033, ERR=0x0000000000000014
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007fcbcd7ed468)
0x00007fcbcd7ed468:   00007fcc290187a7 00007fcbcd7ed470
0x00007fcbcd7ed478:   00007fcbce5ba7d0 00007fcbcd7ed4c8
0x00007fcbcd7ed488:   00007fcbce5bab98 0000000000000000
0x00007fcbcd7ed498:   00007fcbce5ba7d0 0000000000000000
0x00007fcbcd7ed4a8:   00007fcbcd7ed4d0 00007fcbcd7ed510
0x00007fcbcd7ed4b8:   00007fcc29007d80 000000078d6620d8
0x00007fcbcd7ed4c8:   00007fcc29011db6 00007fcbcd7ed4d0
0x00007fcbcd7ed4d8:   00007fcbce5ba9b7 00007fcbcd7ed528
0x00007fcbcd7ed4e8:   00007fcbce5bab98 0000000000000000
0x00007fcbcd7ed4f8:   00007fcbce5baa30 00007fcbcd7ed4d0
0x00007fcbcd7ed508:   00007fcbcd7ed520 00007fcbcd7ed570
0x00007fcbcd7ed518:   00007fcc29007b10 0000000000000000
0x00007fcbcd7ed528:   000000078d662160 00007fcbcd7ed530
0x00007fcbcd7ed538:   00007fcbce5afdc3 00007fcbcd7ed580
0x00007fcbcd7ed548:   00007fcbce5b06d0 0000000000000000
0x00007fcbcd7ed558:   00007fcbce5afde0 00007fcbcd7ed520
0x00007fcbcd7ed568:   00007fcbcd7ed580 00007fcbcd7ed5c8
0x00007fcbcd7ed578:   00007fcc29007b10 0000000000000000
0x00007fcbcd7ed588:   00007fcbcd7ed588 00007fcbce5b0011
0x00007fcbcd7ed598:   00007fcbcd7ed668 00007fcbce5b06d0
0x00007fcbcd7ed5a8:   0000000000000000 00007fcbce5b0578
0x00007fcbcd7ed5b8:   00007fcbcd7ed580 00007fcbcd7ed670
0x00007fcbcd7ed5c8:   00007fcbcd7ed6d0 00007fcc290007a7
0x00007fcbcd7ed5d8:   0000000000000000 0000000000000000
0x00007fcbcd7ed5e8:   0000000000000000 0000000000000000
0x00007fcbcd7ed5f8:   0000000000000000 0000000000000000
0x00007fcbcd7ed608:   0000000000000000 0000000000000000
0x00007fcbcd7ed618:   0000000000000000 0000000000000000
0x00007fcbcd7ed628:   0000000000000000 0000000000000000
0x00007fcbcd7ed638:   0000000000000000 0000000000000000
0x00007fcbcd7ed648:   0000000000000000 0000000000000000
0x00007fcbcd7ed658:   0000000000000000 0000000000000000 

Instructions: (pc=0x00007fcbcd000960)
0x00007fcbcd000940:   
[error occurred during error reporting (printing registers, top of stack, instructions near pc), id 0xb]

Register to memory mapping:

RAX=0x00007fcbcd000960 is an unknown value
RBX={method} {0x00007fcbce5ba7d0} 'aprMajorVersion' '()I' in 'io/netty/internal/tcnative/Library'
RCX=0x00007fcc380073d0 is an unknown value
RDX=0x00007fcc3eb1d030: <offset 0xfd0030> in /app/sinova/jdk1.8/jre/lib/amd64/server/libjvm.so at 0x00007fcc3db4d000
RSP=0x00007fcbcd7ed468 is pointing into the stack for thread: 0x00007fcae70ea000
RBP=0x00007fcbcd7ed4b0 is pointing into the stack for thread: 0x00007fcae70ea000
RSI=0x00007fcbcd7ed4c0 is pointing into the stack for thread: 0x00007fcae70ea000
RDI=0x00007fcae70ea1f8 is an unknown value
R8 =0x0000000000000000 is an unknown value
R9 =0x000000000000000d is an unknown value
R10=0x00007fcc2901877b is at code_begin+859 in an Interpreter codelet
method entry point (kind = native)  [0x00007fcc29018420, 0x00007fcc29018da0]  2432 bytes
R11=0x00007fcc3e51b540: <offset 0x9ce540> in /app/sinova/jdk1.8/jre/lib/amd64/server/libjvm.so at 0x00007fcc3db4d000
R12=0x0000000000000000 is an unknown value
R13={method} {0x00007fcbce5ba7d0} 'aprMajorVersion' '()I' in 'io/netty/internal/tcnative/Library'
R14=0x00007fcbcd7ed4c8 is pointing into the stack for thread: 0x00007fcae70ea000
R15=0x00007fcae70ea000 is a thread

**Comment by leccyril** [comment]
i have same issue when using GCP libs on java 21 what to do ?
