### ISSUE TITLE
Manual release object when using Http2 to Http1 adapter

### ISSUE THREAD

**Issue by dpy1123** [netty/netty#11876]
I am using InboundHttp2ToHttpAdapter and HttpToHttp2ConnectionHandler to delegate http2 stream objects to HttpObject. And also configured to disable the autoRelease, and do the release by myself.
When I release the HttpObject on http1-layer, the under http2-layer may not finish the write(maybe the msg send splites into two write action), and cause a "refCnt: 0" exception. Now I am using event-loop scheduer to delay release the msg, but I think it`s not the right way. So I am here asking for suggestion. THX~

**Comment by chrisvest** [comment]
Can you add a `retain()` call (or a similar named method) when you hand over the buffer or HttpObject from http1-layer to http2-layer? Then both layers will be allowed to call `release` when they want to, so you don't have to delay the release.

**Comment by Kvicii** [comment]
@chrisvest hi, cloud you guide me how to do this? I want start with basic

**Comment by chrisvest** [comment]
I think we can close this. Doesn't sound like a bug in Netty, and we didn't hear back from OP.
