### ISSUE TITLE
Help help help!

### ISSUE THREAD

**Issue by devzwy** [netty/netty#11889]
Use Netty 4
Business scenario: A, B and C are client forwarding servers and real servers respectively. The problem now is that all IP addresses of data forwarded through B obtained by C are the same. Assuming that B and C are on the same computer, the IP obtained by C will always be 127.0.0.1. Is there any way for C to obtain the real request address of a? The AC ends cannot be modified and can only be processed at the B end. I hope someone can help me. It's been bothering me for half a year.

**Comment by normanmaurer** [comment]
This is an issue tracker. Please open a topic in the discussions or ask question on stackoverflow
