### ISSUE TITLE
Why DirectMemory In Java Heap ?

### ISSUE THREAD

**Issue by Sunyelw** [netty/netty#11895]
I use a code without release like [OutOfDirectMemoryError](https://github.com/netty/netty/issues/11754)

when Stress test it by jmeter and see it by Jconsole.

![image](https://user-images.githubusercontent.com/31758533/144838048-c69a9caf-a29c-4edd-bfb3-3ed76afd7a7b.png)

this is a DirectMemoryError,  why Heap is full and directMemory is empty?

### Netty version

4.1.65

### JVM version (e.g. `java -version`)

```
❯ java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)
```

**Comment by franz1981** [comment]
https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/PlatformDependent.java#L153

this is the key part you should be interested in: if `io.netty.maxDirectMemory` is not specified, Netty would apply it's own direct memory limit (same as JVM one - by default == to the max heap size), without using nor `Cleaner` nor traditional NIO direct memory allocation mechanism (that means that no tools can detect though JMX the direct memory used with standard JVM mechanism, if not by using allocator own metrics)

**Comment by Sunyelw** [comment]
sorry, i forget put my vm options
```
-Xms128m
-Xmx128m
-XX:MaxMetaspaceSize=128m
-XX:MetaspaceSize=128m
-XX:MaxDirectMemorySize=4m
-Dio.netty.leakDetectionLevel=PARANOID
-XX:NativeMemoryTracking=summary
-XX:+UnlockDiagnosticVMOptions
-XX:+PrintNMTStatistics
-XX:+HeapDumpOnOutOfMemoryError
-XX:HeapDumpPath=/logs/HeapDumpOnOutOfMemoryError/
```

And Error is
```
io.netty.handler.codec.EncoderException: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 158 byte(s) of direct memory (used: 4194209, max: 4194304)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104) ~[netty-codec-4.1.65.Final.jar:4.1.65.Final]
```

the `MaxDirectMemorySize` is 4m.

**Comment by chrisvest** [comment]
Netty has its own memory accounting. What you see from the JMX beans is the accounting done by the JVM, but that only takes the DirectByteBuffer instances into account. In Netty, when Unsafe is available, we allocate direct memory with it, and those allocations are not counted by the JVM.

**Comment by Luckyangle** [comment]
您好，您的邮件已收到，我会尽快查阅并回复，谢谢。

**Comment by Sunyelw** [comment]
> Netty has its own memory accounting. What you see from the JMX beans is the accounting done by the JVM, but that only takes the DirectByteBuffer instances into account. In Netty, when Unsafe is available, we allocate direct memory with it, and those allocations are not counted by the JVM.


thx, i got it. Then how can i observe this `direct memory`?

**Comment by Sunyelw** [comment]
I use jvisualvm `BufferPools` plugin got this:
![image](https://user-images.githubusercontent.com/31758533/145143843-020a6657-a4ca-479f-9822-7ee4a6048ce2.png)
```
count: 3 
```
 is  `the DirectByteBuffer instances`

```
Memory Used：4,101 个字节, Total Capacity：4,100 个字节
```
Did you know what it is?  As you say `those allocations are not counted by the JVM.`.

**Comment by chrisvest** [comment]
It's not exposed to JMX by default. You have to create and register your own JMX bean that pulls the number from `PlatformDependent.usedDirectMemory()`.

**Comment by Chuanhui-Liu** [comment]
Wondering if this is platform dependent?

**Comment by Sunyelw** [comment]
As I try add JMX to exposed Netty Memory Leak
```java
import io.netty.util.internal.PlatformDependent;
import org.springframework.jmx.export.annotation.ManagedAttribute;
import org.springframework.jmx.export.annotation.ManagedResource;
import org.springframework.stereotype.Component;

@Component
@ManagedResource(objectName = "com.mbean.netty:name=NettyLeakCheck")
public class NettyMemoryLeakCheck implements INettyMemoryLeakCheck {

    @ManagedAttribute
    @Override
    public long getLeak(){
        return PlatformDependent.usedDirectMemory();
    }
}
```

Then start to stress test it which with netty memory leak.

I got this from JvisualVM 'Buffer Pool' plugin
![image](https://user-images.githubusercontent.com/31758533/147438456-4503a6c3-3f81-4967-b81b-2995c3cb3b2a.png)

I got this from JMX MBean (It's always be '-1')
![image](https://user-images.githubusercontent.com/31758533/147438479-67fd5465-8961-4e6a-8712-308eae9ba4c8.png)

1 Why didn't JvisualVM 'Buffer Pool' plugin work before?
2 Why JMX MBean doesn't work always?
3 What should I do to reserve NettyDirectMemory on a simple way?

@chrisvest Could you give me some any suggestion, thx a lot.

**Comment by chrisvest** [comment]
`PlatformDependent.usedDirectMemory()` return `-1` when there is no max direct memory configured for Netty. In other words, when the `io.netty.maxDirectMemory` system property is set to `-1`, which is the default.
(Or when either `sun.misc.Unsafe` is not available, or we cannot create direct `ByteBuffer` instances based on a raw pointer.)

Netty has a built-in leak detector, that you can enable with the `io.netty.leakDetection.level` and `io.netty.leakDetection.targetRecords` system properties.
In our CI builds, we set the following system properties on the command line:

```
-Dio.netty.leakDetection.level=paranoid -Dio.netty.leakDetection.targetRecords=32
```

Note that the `paranoid` level has a very high performance cost.
To reduce overhead, you can set the level to `advanced`, which is like `paranoid`, but only instruments and samples ~1% of allocated buffers.
Detected leaks will be printed to the log, and include the recent history of accesses to the leaked buffer.

**Comment by normanmaurer** [comment]
Closing this for now
