### ISSUE TITLE
Netty BOM v4.1.71 refers to non-existent netty-tcnative-classes version

### ISSUE THREAD

**Issue by kedar-joshi** [netty/netty#11903]
### Expected behavior
Netty BOM should include dependency `io.netty:netty-tcnative-classes:2.0.46.Final`.

### Actual behavior
Non-existent dependency `io.netty:netty-tcnative-classes:2.0.44.Final` is included.

### Steps to reproduce

See following sections from https://repo1.maven.org/maven2/io/netty/netty-bom/4.1.71.Final/netty-bom-4.1.71.Final.pom -

```xml
<properties>
    <!--  Keep in sync with ../pom.xml  -->
    <tcnative.version>2.0.44.Final</tcnative.version>
</properties>

<!-- .. -->

<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-tcnative-classes</artifactId>
    <version>${tcnative.version}</version>
</dependency>
```
### Minimal yet complete reproducer code (or URL to code)

URL : https://repo1.maven.org/maven2/io/netty/netty-bom/4.1.71.Final/netty-bom-4.1.71.Final.pom

### Netty version

Version : `4.1.71.Final`.

### JVM version (e.g. `java -version`)

```
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)
```

### OS version (e.g. `uname -a`)

Windows 10 (64 Bit)

**Comment by chrisvest** [comment]
Fix was merged in #11902
