### ISSUE TITLE
Invalid BOM for 4.1.71

### ISSUE THREAD

**Issue by jameskleeh** [netty/netty#11908]
The bom file references 

```
<dependency>
<groupId>io.netty</groupId>
<artifactId>netty-tcnative-classes</artifactId>
<version>${tcnative.version}</version>
</dependency>
```

with 

```
<properties>
<!--  Keep in sync with ../pom.xml  -->
<tcnative.version>2.0.44.Final</tcnative.version>
</properties>
```

however that module only has a 2.0.46 version

https://repo1.maven.org/maven2/io/netty/netty-tcnative-classes/

**Comment by gemmellr** [comment]
Was addressed in previous issues/PRs, e.g see https://github.com/netty/netty/pull/11902 and https://github.com/netty/netty/issues/11903

**Comment by jameskleeh** [comment]
Thanks!
