### ISSUE TITLE
netty-tcnative 2.0.46 jar is empty in maven repo

### ISSUE THREAD

**Issue by novos40** [netty/netty#11918]
### Expected behavior
netty-tcnative-2.0.46.Final.jar  should contain java classes
### Actual behavior
it contains only manifest and maven metadata
### Steps to reproduce
look inside the jar (https://repo1.maven.org/maven2/io/netty/netty-tcnative/2.0.46.Final/netty-tcnative-2.0.46.Final.jar)
### Minimal yet complete reproducer code (or URL to code)
N/A
### Netty version
N/A
### JVM version (e.g. `java -version`)
N/A
### OS version (e.g. `uname -a`)
N/A

**Comment by normanmaurer** [comment]
This is expected as it just depends on all the sub-modules. Check its pom.xml
