### ISSUE TITLE
Netty 4.1.[69-70].Final are missing Automatic-Module-Name

### ISSUE THREAD

**Issue by mnriem** [netty/netty#11917]
### Expected behavior

Automatic-Module-Name: io.netty.all

### Actual behavior

Automatic-Module-Name: 

### Netty version

Netty 4.1.[69-70]

**Comment by normanmaurer** [comment]
@mnriem what about 4.1.72.Final ?

**Comment by mnriem** [comment]
Unfortunately, also missing it

**Comment by normanmaurer** [comment]
@mnriem PRs welcome ...

**Comment by mnriem** [comment]
I have looked at it and it appears that some of the JARs have conflicting exports. So I was unable to do the work as I am not sure what to do here. E.g see codec and codec-xml they both have the same package in it. I moved my own project to use the appropriate modules instead (I do not use the XML stuff).

**Comment by mnriem** [comment]
@normanmaurer Are you OK if I close this. While it is still an issue I decided to use the modules separately and that works. That is probably how it should be used in a modularized environment anyway.

**Comment by chrisvest** [comment]
Yeah, let's close this. We can't fix the package name conflicts in 4.1 because that would break compatibility.

**Comment by kohsuke** [comment]
@mnriem before you close the issue, I'd appreciate a little more details about the workaround you found? Not to use netty-all but use different parts of netty individually?

I'm stuck with this same problem and that's currently preventing me from updating beyond 4.1.69.

**Comment by mnriem** [comment]
@kohsuke For me it was replacing 

    requires io.netty.all;

with

    requires io.netty.buffer;
    requires io.netty.codec;
    requires io.netty.codec.http;
    requires io.netty.codec.http2;
    requires io.netty.common;
    requires io.netty.handler;
    requires io.netty.transport;
