### ISSUE TITLE
这个删了本地仓库的这个jar包试下

### ISSUE THREAD

**Issue by process-sk** [netty/netty#11912]
早上试了一个小时了，这个答案对我没用，要么报错Failure to find io.netty:netty-dev-tools:jar:4.1.26.Final-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository，要么不报错，但是问题也不解决，就是这么神奇。

_Originally posted by @InuYasha000 in https://github.com/netty/netty/issues/7518#issuecomment-774364938_

**Comment by hyperxpro** [comment]
Please use English.
