### ISSUE TITLE
When will Netty new version with log4j security fix be available

### ISSUE THREAD

**Issue by neilm30** [netty/netty#11913]
Hello All
This is a kind of urgent regarding "log4j" security issue.
We are using hivemq client dependency in our android project. Hivemq client internally uses netty as a dependency as per below link:

https://search.maven.org/artifact/com.hivemq/hivemq-mqtt-client/1.3.0/jar

I see that current netty/common version is 4.1.71.Final which uses log4j dependencies

https://mvnrepository.com/artifact/io.netty/netty-common/4.1.71.Final

Regarding the "log4j" version update I have below 2 queries:
1.Does netty internally use any of log4j classes since its mentioned its optional?
2. When will the new version  netty be available with security fix for "log4j" so that dependent libraries can update their versions ?

Thank you

**Comment by slandelle** [comment]
Please properly read the mvnrepository page you linked: `log4j` is flagged as **optional**, meaning netty won't pull it.
Netty has its own abstraction layer that lets you pull your favorite logging library, hence the optional dependency.
