### ISSUE TITLE
Failed to include netty-bom:4.1.71.FINAL, as tcnetty-classes:2.0.44.FINAL is not on maven central

### ISSUE THREAD

**Issue by barclay-reg** [netty/netty#11914]
### Expected behavior
tcnetty-classes:2.0.44.FINAL can be downloaded from maven central
### Actual behavior
only tcnetty-classes:2.0.46.FINAL is availeble on maven central

**Comment by normanmaurer** [comment]
Duplicate of https://github.com/netty/netty/pull/11902
