### ISSUE TITLE
Boring SSL JAR conflict when using the same JAR in two different classpaths

### ISSUE THREAD

**Issue by BuddhiWathsala** [netty/netty#11921]
### Expected behavior
I have two isolated subprojects (with two different classpaths) which I can run each of them separately or at the same time. Both of these sub-projects contains the same `netty-tcnative-boringssl-static-2.0.46.Final.jar`. According to the [Netty library loading logic here](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/NativeLibraryLoader.java#L247), when there is more than one resource, it gives an error.

It is better if the implementation could check at least the JAR is the same or not. If JARs are different, it is okay to give an error. But when `urlsList` has the same JAR twice, it is problematic to give an error.

### Actual behavior
Gives an error without checking the JAR replications.

### Steps to reproduce
- Run netty SSL example with two classpaths

### Netty version
`netty-tcnative-boringssl-static-2.0.46.Final.jar`

### JVM version (e.g. `java -version`)
- Java 11

### OS version (e.g. `uname -a`)
- macOS

**Comment by normanmaurer** [comment]
@BuddhiWathsala PRs welcome

**Comment by normanmaurer** [comment]
Maybe it would be even better to check if filename is the same and also compare the sha256 for the file. And if the filename is the same and the sha256 not fail. WDYT @BuddhiWathsala  ?

**Comment by BuddhiWathsala** [comment]
@normanmaurer, yes exactly. Checking the file names will solve my issue.

**Comment by normanmaurer** [comment]
@BuddhiWathsala  see https://github.com/netty/netty/pull/11927
