### ISSUE TITLE
`InternalThreadLocalMap.UNSET` field should not allow accessed from outside

### ISSUE THREAD

**Issue by laosijikaichele** [netty/netty#11929]
I think the `UNSET` field in class `io.netty.util.internal.InternalThreadLocalMap` should not allow accessed from outside. Otherwise it will cause inconsistent behavior in some extreme corner case, see the following example:
### Minimal yet complete reproducer code (or URL to code)
```
import io.netty.util.concurrent.FastThreadLocal;
import io.netty.util.internal.InternalThreadLocalMap;
import java.util.Set;

public static void main(String[] args) {
        FastThreadLocal<Object> fsl = new FastThreadLocal<Object>() {
            @Override
            protected Object initialValue() throws Exception {
                return InternalThreadLocalMap.UNSET; // set initial value
            }
        };

        fsl.get();
        Set ftlSet = (Set) InternalThreadLocalMap.get().indexedVariable(0);
        System.out.println("size:" + ftlSet.size()); // print Size:1
        fsl.set(InternalThreadLocalMap.UNSET); // set value again
        System.out.println("size:" + ftlSet.size()); // print Size:0
    }
```
The console prints:
> size:1
> size:0

Which are logically inconsistent. 
So I think it's better to limit the access level of `UNSET` filed in some way.

### Netty version
4.1.72.Final

**Comment by chrisvest** [comment]
It would be a compatibility break to hide it in 4.1.

**Comment by normanmaurer** [comment]
@laosijikaichele you might want to do a PR against main.

**Comment by laosijikaichele** [comment]
> @laosijikaichele you might want to do a PR against main.

OK, I will take a look.

**Comment by laosijikaichele** [comment]
@normanmaurer  I am considering moving `InternalThreadLocalMap` to package `io.netty.util.concurrent`, and change the access modifier of field `InternalThreadLocalMap.UNSET` to package private. WDYT?

**Comment by normanmaurer** [comment]
sounds good
