### ISSUE TITLE
Netty tcnative 2.0.46 breaks dependencies

### ISSUE THREAD

**Issue by karthickm512** [netty/netty#11926]
### Expected behavior
Upgrade from Netty tcnative 2.0.44.Final to 2.0.46.Final should be smooth

### Actual behavior
tcnative 2.0.46 has corrupted manifest and does not have bundle name etc  which is needed by other netty artifacts like netty handler 4.1.72.Final that resolves critical log4j vulnerability.

Following is seen in 2.0.44.Final manifest which is completely missing in 2.0.46
Manifest-Version: 1.0
Implementation-Title: Netty/TomcatNative [OpenSSL - Dynamic]
Bundle-Description: A Mavenized fork of Tomcat Native which incorporat
es various patches. This artifact is dynamically linked to OpenSSL
and Apache APR.
Automatic-Module-Name: io.netty.internal.tcnative
Bundle-SymbolicName: io.netty.tcnative
Implementation-Version: 2.0.46.Final
Built-By: norman
Bnd-LastModified: 1637143333958
Bundle-ManifestVersion: 2
Implementation-Vendor-Id: io.netty
Tool: Bnd-5.1.1.202006162103
Bundle-Name: Netty/TomcatNative [OpenSSL - Dynamic]
Bundle-Version: 2.0.46.Final
Build-Jdk-Spec: 1.8
Created-By: Apache Maven Bundle Plugin
Build-Jdk: 1.8.0_252
Implementation-URL: https://github.com/netty/netty-tcnative/netty-tcnative/

### Steps to reproduce
Try to bring up Netty Handler 4.1.72.Final along with Netty tcnative 2.0.46.Final in karaf 4.3.x container

### Netty version
4.1.72.Final and tcnative 2.0.46.Final

### JVM version (e.g. `java -version`)
Java 11

**Comment by normanmaurer** [comment]
This was fixed in the latest tcnative release
