### ISSUE TITLE
netty-all. jar 4.1.72 at MVNRepository.com seems to be almost empty

### ISSUE THREAD

**Issue by jo-kin** [netty/netty#11935]
I'm not sure you are involved with uploading netty.jars to Maven Repository at all. But give me a try here.

### Expected behavior
Until Version 4.1.68 the netty-all.jar has a size about 4MB when downloading from mvnrepository.com

### Actual behavior
The size is just 4k. Except directory META-INF the jar is empty.

### Steps to reproduce
Just visit https://mvnrepository.com/artifact/io.netty/netty-all/4.1.72.Final

### Minimal yet complete reproducer code (or URL to code)
https://mvnrepository.com/artifact/io.netty/netty-all/4.1.72.Final

### Netty version
Seems to be empty since 4.1.69

**Comment by normanmaurer** [comment]
@jo-kin thats expected... it just has dependencies on all the sub-modules to pull them down.

**Comment by jo-kin** [comment]
Thank you, Norman.
I am not very happy with your decision, due to we maintain our own repository for external dependencies. By company policy it is not allowed to resolve any external dependency transitive from wilderness. To download netty-all and, after checking checksum etc, to copy it into the local repository was a more comfortable way.
On the other hand we have now a motive to survey which netty-sub-modules we need we really....
