### ISSUE TITLE
question about HttpContentCompressor mangle the content in the AbstractChannelHandlerContext#skipContext method

### ISSUE THREAD

**Issue by huibinliupush** [netty/netty#11930]
## Netty version

4.1.72.Final

## question

![image](https://user-images.githubusercontent.com/5794695/146409217-735ec625-b312-42a1-8422-64c700123a55.png)

I do not understand the problem that needs to be solved in this [issue10067](https://github.com/netty/netty/issues/10067)

if i do not check the executor in the prev ChannelHandlerContext is the same executor as the current executor in the AbstractChannelHandlerContext#skipContext method.

**why does this behavior cause HttpContentCompressor mangle the content** when it is put on an alternate EventExecutor

what confuses me more is that no matter whether this condition `ctx.executor() == currentExecutor`  is added or not, the propagation order of **write events**  always is `outBoundHandler->httpContentCompressor->httpServerCodec` in the following test case

![image](https://user-images.githubusercontent.com/5794695/146411661-feb7713e-b514-4f48-9733-5969a48a9cb9.png)

Since the processing order of outbound events  always is `outBoundHandler->httpContentCompressor->httpServerCodec`, then what is the reason causes  to HttpContentCompressor mangle the content

**Comment by normanmaurer** [comment]
The problem is that if we don't check that we might sometimes offload and sometimes not which might let events happen out of order. There is even a unit test:

https://github.com/netty/netty/pull/10069/files#diff-9bfd6af4dcfe9b82a83ed76d261c14ad2f7128825c9862ee4cf37192aa6faf74R281

**Comment by huibinliupush** [comment]
![image](https://user-images.githubusercontent.com/5794695/146875205-0f9f9295-b078-448b-a65e-ee91c6d641ba.png)

Hi @normanmaurer 

I modified this `skipContext` method locally to delete the check condition as shown in the figure above, and then debugged this unit test.

![image](https://user-images.githubusercontent.com/5794695/146876000-9760dde0-07a2-4031-869f-67fd315418a1.png)

found that the write event order always is `outBoundHandler->httpContentCompressor->httpServerCodec`， there is no disorder，but the unit test failed。

![image](https://user-images.githubusercontent.com/5794695/146876338-1bdbd884-8bfe-491d-b162-2b0248433c3b.png)

but i put the `HttpContentCompressor` on the same eventExecutor ，the unit test successed。

**I am confused as to why this unit test  failed when i put the `HttpContentCompressor` on an alternate EventExecutor ??**

**What are the specific reasons?**
