### ISSUE TITLE
io.netty.handler.ssl.OpenSsl hardcoded keys

### ISSUE THREAD

**Issue by kommersz** [netty/netty#11942]
Hi, probably not an Issue, but hope you do not mind me raising this here. io.netty.handler.ssl.OpenSsl contains a hardoded key, which appears to be passed on to an SSL handler created via tcnative, apparently wit the purpose to prove if a feature that can be configured with (the deprecated) "io.netty.handler.ssl.openssl.useKeyManagerFactory" is available or not. I am not familiar with tcnative, found no documentation on the "io.netty.handler.ssl.openssl.useKeyManagerFactory" property either. Can someone confirm that this key is never used productively, and maybe link some documentation/brief explanation on what it should be doing? Thank you, Gabor

**Comment by normanmaurer** [comment]
@kommersz yes its just used for probing if a specific feature can be used. These keys are never used after probing.
