### ISSUE TITLE
DefaultHttp2RemoteFlowController: writeAllocatedBytes & Endless loop

### ISSUE THREAD

**Issue by lin233** [netty/netty#11959]
There is a small probability I can't shut down a stream normally. 
and I found I'm stuck in an endless loop at these code：

                while (!cancelled && (frame = peek()) != null) {
                    int maxBytes = min(allocated, writableWindow());
                    if (maxBytes <= 0 && frame.size() > 0) {
                        // The frame still has data, but the amount of allocated bytes has been exhausted.
                        // Don't write needless empty frames.
                        break;
                    }
                    writeOccurred = true;
                    int initialFrameSize = frame.size();
                    try {
                        frame.write(ctx, max(0, maxBytes));
                        if (frame.size() == 0) {
                            // This frame has been fully written, remove this frame and notify it.
                            // Since we remove this frame first, we're guaranteed that its error
                            // method will not be called when we call cancel.
                            pendingWriteQueue.remove();
                            frame.writeComplete();
                        }
                    } finally {
                        // Decrement allocated by how much was actually written.
                        allocated -= initialFrameSize - frame.size();
                    }
                }

my pendingWriteQueue had 2 frame, and the first one cannot always be removed, the second is endStream. 

### Netty version
4.1.63.Final

**Comment by normanmaurer** [comment]
@lin233 can you provide some more details about what `maxBytes` is and `frame.size()` ?

**Comment by lin233** [comment]
maxBytes = 19, frame.size() = 19 ，allocated = 19

![image](https://user-images.githubusercontent.com/26543047/147560784-71f6890c-36d5-4bec-bbcc-815f42db7cd7.png)

![image](https://user-images.githubusercontent.com/26543047/147560848-16d44a55-80c0-4078-8c47-ad90908e536d.png)


other details: 
![image](https://user-images.githubusercontent.com/26543047/147559460-088492a8-ea0f-401d-abfb-de393e0774f6.png)


"grpc-nio-worker-ELG-1-4" #317 daemon prio=5 os_prio=0 cpu=56709.54ms elapsed=1062.05s tid=0x00007f5798016000 nid=0x4b90 runnable  [0x00007f5754233000]
   java.lang.Thread.State: RUNNABLE
	at io.netty.channel.socket.nio.NioSocketChannel.config(NioSocketChannel.java:116)
	at io.netty.channel.socket.nio.NioSocketChannel.config(NioSocketChannel.java:57)
	at io.netty.channel.ChannelOutboundBuffer.incrementPendingOutboundBytes(ChannelOutboundBuffer.java:176)
	at io.netty.channel.ChannelOutboundBuffer.addMessage(ChannelOutboundBuffer.java:129)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:884)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:715)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:707)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:700)
	at io.netty.handler.codec.http2.DefaultHttp2FrameWriter.writeData(DefaultHttp2FrameWriter.java:174)
	at io.netty.handler.codec.http2.Http2OutboundFrameLogger.writeData(Http2OutboundFrameLogger.java:44)
	at io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeData(DecoratingHttp2FrameWriter.java:39)
	at io.grpc.netty.NettyServerHandler$WriteMonitoringFrameWriter.writeData(NettyServerHandler.java:1014)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder$FlowControlledData.write(DefaultHttp2ConnectionEncoder.java:509)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.writeAllocatedBytes(DefaultHttp2RemoteFlowController.java:362)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$WritabilityMonitor.write(DefaultHttp2RemoteFlowController.java:547)
	at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor$State.write(WeightedFairQueueByteDistributor.java:604)
	at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.distribute(WeightedFairQueueByteDistributor.java:292)
	at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.distributeToChildren(WeightedFairQueueByteDistributor.java:325)
	at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.distribute(WeightedFairQueueByteDistributor.java:273)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$WritabilityMonitor.writePendingBytes(DefaultHttp2RemoteFlowController.java:627)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController.writePendingBytes(DefaultHttp2RemoteFlowController.java:267)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:188)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelWritabilityChanged(Http2ConnectionHandler.java:428)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:439)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:426)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:419)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelWritabilityChanged(DefaultChannelPipeline.java:1433)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:439)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:426)
	at io.netty.channel.DefaultChannelPipeline.fireChannelWritabilityChanged(DefaultChannelPipeline.java:931)
	at io.netty.channel.ChannelOutboundBuffer.fireChannelWritabilityChanged(ChannelOutboundBuffer.java:628)
	at io.netty.channel.ChannelOutboundBuffer.setWritable(ChannelOutboundBuffer.java:594)
	at io.netty.channel.ChannelOutboundBuffer.decrementPendingOutboundBytes(ChannelOutboundBuffer.java:196)
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:273)
	at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:352)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:431)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:930)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:361)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:708)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@11.0.4/Thread.java:834)

**Comment by lin233** [comment]
@normanmaurer Is there anything else i can provide? Thank you for your attention.

**Comment by RK23HUNTER** [comment]
whirt one progarm and print

**Comment by chrisvest** [comment]
Is the frame.size() not changed by the write() call for some reason?

**Comment by lin233** [comment]
> 
yes， the frame.size() not changed.

**Comment by normanmaurer** [comment]
@lin233 is there a way for us to reproduce easily ?

**Comment by lin233** [comment]
The time It happened was always when I disconnect grpc connections, and the stream state is "HALF_CLOSED_REMOTE". Maybe frequent disconnection grpc can reproduce easily. The way I reproduce is to connect and disconnect frequently and with high concurrency.

**Comment by lin233** [comment]
The time It happened was always when I disconnect grpc connections, and the stream state is "HALF_CLOSED_REMOTE". Maybe connect and disconnect frequent grpc with high concurrency can reproduce easily. and my situation is two-way flow.

**Comment by lin233** [comment]
The problem will put the service into suspended animation. If it is difficult to find out why the frame.size() cannot be changed？Is it possible to make it not stuck in an infinite loop  when frame.size() cannot be changed  for some reason？

**Comment by lin233** [comment]
The problem will put the service into suspended animation. If it is difficult to find out why the frame.size() cannot be changed, can we make it not stuck in an infinite loop when frame.size() cannot be changed for some reason？

**Comment by normanmaurer** [comment]
@lin233 btw 4.1.63.Final is really old. Can you upgrade to latest netty version and see if this still happens ?

**Comment by lin233** [comment]
@normanmaurer OK，I will try.  

Thank you for your attention.

**Comment by normanmaurer** [comment]
@lin233 please report back

**Comment by lin233** [comment]
@normanmaurer I upgrade to 4.1.72.Final and this still happened.

**Comment by normanmaurer** [comment]
@lin233 can you provide me a program that I can run here and reproduce ?

**Comment by lin233** [comment]
@normanmaurer It is difficult to reproduce, the probability is very small.  And sorry I can't provide my current program to you,  it is complicated. I need to try to reproduce with a simple program and then I can provide it to you.

**Comment by normanmaurer** [comment]
Can you fully "expand" the variables when this happens ?

**Comment by normanmaurer** [comment]
@lin233 ping

**Comment by normanmaurer** [comment]
@lin233 ping again ...

**Comment by normanmaurer** [comment]
Let me close this ... Please reopen again if you see this in the latest release

**Comment by koo-taejin** [comment]
Hello :)

The service I run has a very similar problem to the above.

It happens about once every two or three months, but unfortunately I don't know how to reproduce it.

I'm using spring-cloud-gateway, and the `netty-4.1.111-Final` version.

Looking at the heap dump in the situation where the problem occurred, there is about 3.7 GB of unflushed data accumulated in ChannelOutboundBuffer.

![Untitled](https://github.com/user-attachments/assets/9f91d2c7-9d43-4a33-9b06-30bf0776dd07)

Look closely at unflusedEntry, you can see that at some point it starts repeatedly including EmptyByteBuf.

![image](https://github.com/user-attachments/assets/4d267d81-3368-4963-85a2-647c30657f32)

Just before EmptyByteBuf, it appears to be a 9-byte header.
The actual StackTrace at that point is as follows.
The heap dump point is before the netty version was updated.
The same problem occurred after the update.

```
reactor.netty.resources.DefaultLoopResources$EventLoop @ 0x7025fcc00                                                                                                                                                                                                    |webflux-http-epoll-1|      0.12 KB |      26.72 KB |                            |org.springframework.boot.loader.LaunchedURLClassLoader @ 0x700000000|true     |        5 |[alive, runnable]|         0x5
|- at io.netty.channel.ChannelOutboundBuffer$Entry$1.newObject(Lio/netty/util/internal/ObjectPool$Handle;)Lio/netty/channel/ChannelOutboundBuffer$Entry; (ChannelOutboundBuffer.java:804)                                                                               |                    |              |               |                    0.02 KB |                                                                    |         |          |                 |            
|- at io.netty.channel.ChannelOutboundBuffer$Entry$1.newObject(Lio/netty/util/internal/ObjectPool$Handle;)Ljava/lang/Object; (ChannelOutboundBuffer.java:801)                                                                                                           |                    |              |               |                            |                                                                    |         |          |                 |            
|- at io.netty.util.internal.ObjectPool$RecyclerObjectPool$1.newObject(Lio/netty/util/Recycler$Handle;)Ljava/lang/Object; (ObjectPool.java:77)                                                                                                                          |                    |              |               |                            |                                                                    |         |          |                 |            
|- at io.netty.util.Recycler.get()Ljava/lang/Object; (Recycler.java:176)                                                                                                                                                                                                |                    |              |               |                            |                                                                    |         |          |                 |            
|- at io.netty.util.internal.ObjectPool$RecyclerObjectPool.get()Ljava/lang/Object; (ObjectPool.java:84)                                                                                                                                                                 |                    |              |               |                            |                                                                    |         |          |                 |            
|- at io.netty.channel.ChannelOutboundBuffer$Entry.newInstance(Ljava/lang/Object;IJLio/netty/channel/ChannelPromise;)Lio/netty/channel/ChannelOutboundBuffer$Entry; (ChannelOutboundBuffer.java:825)                                                                    |                    |              |               |                    0.11 KB |                                                                    |         |          |                 |            
|- at io.netty.channel.ChannelOutboundBuffer.addMessage(Ljava/lang/Object;ILio/netty/channel/ChannelPromise;)V (ChannelOutboundBuffer.java:115)                                                                                                                         |                    |              |               |            3,699,604.92 KB |                                                                    |         |          |                 |            
|- at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Ljava/lang/Object;Lio/netty/channel/ChannelPromise;)V (AbstractChannel.java:882)                                                                                                                            |                    |              |               |                            |                                                                    |         |          |                 |            
|- at io.netty.channel.DefaultChannelPipeline$HeadContext.write(Lio/netty/channel/ChannelHandlerContext;Ljava/lang/Object;Lio/netty/channel/ChannelPromise;)V (DefaultChannelPipeline.java:1367)                                                                        |                    |              |               |                            |                                                                    |         |          |                 |            
|- at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(Ljava/lang/Object;Lio/netty/channel/ChannelPromise;)V (AbstractChannelHandlerContext.java:717)                                                                                                        |                    |              |               |                    0.11 KB |                                                                    |         |          |                 |            
|- at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(Ljava/lang/Object;Lio/netty/channel/ChannelPromise;)V (AbstractChannelHandlerContext.java:709)                                                                                                         |                    |              |               |                            |                                                                    |         |          |                 |            
|- at io.netty.channel.AbstractChannelHandlerContext.write(Ljava/lang/Object;ZLio/netty/channel/ChannelPromise;)V (AbstractChannelHandlerContext.java:792)                                                                                                              |                    |              |               |                            |                                                                    |         |          |                 |            
|- at io.netty.channel.AbstractChannelHandlerContext.write(Ljava/lang/Object;Lio/netty/channel/ChannelPromise;)Lio/netty/channel/ChannelFuture; (AbstractChannelHandlerContext.java:702)                                                                                |                    |              |               |                    0.11 KB |                                                                    |         |          |                 |            
|- at io.netty.handler.codec.http2.DefaultHttp2FrameWriter.writeData(Lio/netty/channel/ChannelHandlerContext;ILio/netty/buffer/ByteBuf;IZLio/netty/channel/ChannelPromise;)Lio/netty/channel/ChannelFuture; (DefaultHttp2FrameWriter.java:174)                          |                    |              |               |                    0.11 KB |                                                                    |         |          |                 |            
|- at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder$FlowControlledData.write(Lio/netty/channel/ChannelHandlerContext;I)V (DefaultHttp2ConnectionEncoder.java:509)                                                                                          |                    |              |               |                            |                                                                    |         |          |                 |            
|- at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.writeAllocatedBytes(I)I (DefaultHttp2RemoteFlowController.java:362)                                                                                                                       |                    |              |               |                    0.33 KB |                                                                    |         |          |                 |            
|- at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$WritabilityMonitor.write(Lio/netty/handler/codec/http2/Http2Stream;I)V (DefaultHttp2RemoteFlowController.java:547)                                                                                  |                    |              |               |                            |                                                                    |         |          |                 |            
|- at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor$State.write(ILio/netty/handler/codec/http2/StreamByteDistributor$Writer;)V (WeightedFairQueueByteDistributor.java:612)                                                                              |                    |              |               |                            |                                                                    |         |          |                 |            
|- at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.distribute(ILio/netty/handler/codec/http2/StreamByteDistributor$Writer;Lio/netty/handler/codec/http2/WeightedFairQueueByteDistributor$State;)I (WeightedFairQueueByteDistributor.java:292)          |                    |              |               |                    0.11 KB |                                                                    |         |          |                 |            
|- at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.distributeToChildren(ILio/netty/handler/codec/http2/StreamByteDistributor$Writer;Lio/netty/handler/codec/http2/WeightedFairQueueByteDistributor$State;)I (WeightedFairQueueByteDistributor.java:325)|                    |              |               |                    0.44 KB |                                                                    |         |          |                 |            
|- at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.distribute(ILio/netty/handler/codec/http2/StreamByteDistributor$Writer;)Z (WeightedFairQueueByteDistributor.java:273)                                                                               |                    |              |               |                    0.36 KB |                                                                    |         |          |                 |            
|- at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$WritabilityMonitor.writePendingBytes()V (DefaultHttp2RemoteFlowController.java:627)                                                                                                                 |                    |              |               |                    0.05 KB |                                                                    |         |          |                 |            
|- at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController.writePendingBytes()V (DefaultHttp2RemoteFlowController.java:267)                                                                                                                                    |                    |              |               |                            |                                                                    |         |          |                 |            
|- at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Lio/netty/channel/ChannelHandlerContext;)V (Http2ConnectionHandler.java:188)                                                                                                                            |                    |              |               |                    6.73 KB |                                                                    |         |          |                 |            
|- at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0()V (AbstractChannelHandlerContext.java:750)                                                                                                                                                           |                    |              |               |                    0.08 KB |                                                                    |         |          |                 |            
|- at io.netty.channel.AbstractChannelHandlerContext.invokeFlush()V (AbstractChannelHandlerContext.java:742)                                                                                                                                                            |                    |              |               |                            |                                                                    |         |          |                 |            
|- at io.netty.channel.AbstractChannelHandlerContext.flush()Lio/netty/channel/ChannelHandlerContext; (AbstractChannelHandlerContext.java:728)                                                                                                                           |                    |              |               |                    0.05 KB |                                                                    |         |          |                 |            
|- at io.netty.handler.codec.http2.AbstractHttp2StreamChannel.flush0(Lio/netty/channel/ChannelHandlerContext;)V (AbstractHttp2StreamChannel.java:1094)                                                                                                                  |                    |              |               |                            |                                                                    |         |          |                 |            
|- at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.flush()V (AbstractHttp2StreamChannel.java:1040)                                                                                                                                        |                    |              |               |                            |                                                                    |         |          |                 |            
|- at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(Lio/netty/channel/ChannelHandlerContext;)V (DefaultChannelPipeline.java:1372)                                                                                                                           |                    |              |               |                            |                                                                    |         |          |                 |            
|- at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0()V (AbstractChannelHandlerContext.java:750)                                                                                                                                                           |                    |              |               |                    0.06 KB |                                                                    |         |          |                 |            
|- at io.netty.channel.AbstractChannelHandlerContext.invokeFlush()V (AbstractChannelHandlerContext.java:742)                                                                                                                                                            |                    |              |               |                            |                                                                    |         |          |                 |            
|- at io.netty.channel.AbstractChannelHandlerContext.flush()Lio/netty/channel/ChannelHandlerContext; (AbstractChannelHandlerContext.java:728)                                                                                                                           |                    |              |               |                    0.08 KB |                                                                    |         |          |                 |            
|- at reactor.netty.channel.MonoSendMany$SendManyInner.run()V (MonoSendMany.java:325)                                                                                                                                                                                   |                    |              |               |                    8.95 KB |                                                                    |         |          |                 |            
|- at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(Ljava/lang/Runnable;)V (AbstractEventExecutor.java:164)                                                                                                                                                |                    |              |               |                    0.09 KB |                                                                    |         |          |                 |            
|- at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(J)Z (SingleThreadEventExecutor.java:469)                                                                                                                                                           |                    |              |               |                  916.54 KB |                                                                    |         |          |                 |            
|- at io.netty.channel.epoll.EpollEventLoop.run()V (EpollEventLoop.java:391)                                                                                                                                                                                            |                    |              |               |                  916.54 KB |                                                                    |         |          |                 |            
|- at io.netty.util.concurrent.SingleThreadEventExecutor$4.run()V (SingleThreadEventExecutor.java:986)                                                                                                                                                                  |                    |              |               |                    0.02 KB |                                                                    |         |          |                 |            
|- at io.netty.util.internal.ThreadExecutorMap$2.run()V (ThreadExecutorMap.java:74)                                                                                                                                                                                     |                    |              |               |                    0.02 KB |                                                                    |         |          |                 |            
|- at io.netty.util.concurrent.FastThreadLocalRunnable.run()V (FastThreadLocalRunnable.java:30)                                                                                                                                                                         |                    |              |               |                    0.02 KB |                                                                    |         |          |                 |            
'- at java.lang.Thread.run()V (Thread.java:840)                                                                                                                                                                                                                         |                    |              |               |                   26.72 KB |                                                                    |         |          |                 |            
---------------------------------------------------
```

When analyzing the data and code together, this is the suspicious part.
FlowControlledData looks like a data mismatch.
readableByte is 292,
but the actual bufAndListenerParis is already an empty value.
![image](https://github.com/user-attachments/assets/4bdfb3fd-5d97-4737-86f0-febb27495ca3)


Because of this, the termination condition of the code below is not achieved,

It seems to keep throwing the header and an empty EmptyByteBuf.
```java
io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController.FlowState#writeAllocatedBytes
```

I tried to see if the data was written somewhere else,
![image](https://github.com/user-attachments/assets/54d59767-4d22-42ae-a971-7563cff05ad3)

Actual pendingBytes is 59282, and the buffer above is 58990.

![image](https://github.com/user-attachments/assets/12e9b071-1775-4460-af1c-7ae72ed83863)
![image](https://github.com/user-attachments/assets/af6c5c33-2314-4602-8fc8-93ea7a9936a3)


And the value that is judged to be non-existent but still remaining is 292, which is the result of subtracting the two values ​​above.

Actually, I don't know the root cause.

However, if a problem like mine occurs, if you change the assert in the code below to an exception so that it doesn't fall into OOM, I think there won't be a bigger problem.


```java
// io.netty.channel.AbstractCoalescingBufferQueue#remove
public final ByteBuf remove(ByteBufAllocator alloc, int bytes, ChannelPromise aggregatePromise) {
        checkPositiveOrZero(bytes, "bytes");
        checkNotNull(aggregatePromise, "aggregatePromise");

        // Use isEmpty rather than readableBytes==0 as we may have a promise associated with an empty buffer.
        if (bufAndListenerPairs.isEmpty()) {
            assert readableBytes == 0;
            return removeEmptyValue();
        }
        
    }    
```

I would really appreciate it if you could tell me how to solve this problem.

And if there is any information you need, I will try my best to provide it to you.

Thank you. :)

**Comment by normanmaurer** [comment]
@koo-taejin thanks a lot! I think I might have an idea

**Comment by normanmaurer** [comment]
@koo-taejin thanks a lot for all the details... it really helped me to understand what is wrong here. Fix should be this https://github.com/netty/netty/pull/14220

**Comment by koo-taejin** [comment]
@normanmaurer 

I have a question.

I thought the code I mentioned would not throw an exception and would continue to loop infinitely.

```
// io.netty.channel.AbstractCoalescingBufferQueue#remove
if (bufAndListenerPairs.isEmpty()) {
            assert readableBytes == 0;
            return removeEmptyValue();
}
```
However, the fix seems to fix the problem in the case where an exception is thrown.

I may have misunderstood because I do not have enough knowledge about netty.
Thank you for your quick response to this issue.

**Comment by normanmaurer** [comment]
@koo-taejin I think what happened is that it did throw an IllegalReferenceCountException at some point and so things did end up in an inconsistent state which never could break recovered. This is not possible anymore with this change

**Comment by koo-taejin** [comment]
@normanmaurer  
Thanks for letting me know. :)
