### ISSUE TITLE
ChannelInitializer#initChannel not firing

### ISSUE THREAD

**Issue by CommandCracker8** [netty/netty#11971]
### Expected behavior
The `initChannel()` event to fire whenever a client attempts to connect, and log it to console. It might just be me not knowing how Netty works but from what I know `initChannel()` should be firing when the server is pinged or has any data sent to it.

### Actual behavior
Nothing is printed to console when I ping the server

### Steps to reproduce
Run the code that creates my `ServerConnection`
Ping the server in the Minecraft server list (I'm creating a completely custom server software from Minecraft, but to be honest you can probably ping it from anything to test it. This is also why I haven't provided any client code)

### Minimal yet complete reproducer code (or URL to code)
My code that creates my `ServerConnection`: https://www.toptal.com/developers/hastebin/ajufisituy.java
The code for the `ServerConnection`: https://www.toptal.com/developers/hastebin/kitisoqayi.java

### Netty version
4.0.0.Final

### JVM version
17

### OS version
Microsoft Windows [Version 10.0.19042.1415]

**Comment by hyperxpro** [comment]
The Netty version which you're using is very old and reached EOL. Please upgrade to the latest version of Netty and try again.

**Comment by CommandCracker8** [comment]
Oh okay. What's the latest version?

**Comment by CommandCracker8** [comment]
Cool thanks

**Comment by CommandCracker8** [comment]
I've updated the Netty version but it's still not working, any ideas?

**Comment by hyperxpro** [comment]
Why `new NioEventLoopGroup(0, new ThreadFactoryBuilder().setNameFormat("Netty Default IO #%d").setDaemon(true).build());` is set to 0?

The code looks fine. Can you show client-side code?

**Comment by CommandCracker8** [comment]
Not sure why it's 0, just what I was told to do.

As I said I don't have client-side code. I'm making a custom server for Minecraft from scratch.

**Comment by CommandCracker8** [comment]
Minecraft uses netty, their protocol page is https://wiki.vg/Protocol if you want to take a look

**Comment by hyperxpro** [comment]
![Screenshot (71)](https://user-images.githubusercontent.com/24762260/148236303-c416a03e-3252-4f10-b9b9-00de466035b0.png)

The code works fine.

**Comment by CommandCracker8** [comment]
What are you pinging that with?

**Comment by hyperxpro** [comment]
I used [Packet Sender](https://packetsender.com/). However, you can use any TCP client and it should work just fine.

**Comment by CommandCracker8** [comment]
I just tried that and I didn't get anything in console. This is really strange

**Comment by hyperxpro** [comment]
Use this.

```java
import io.netty.bootstrap.ServerBootstrap;
import io.netty.channel.Channel;
import io.netty.channel.ChannelException;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.ChannelOption;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.ServerChannel;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.nio.NioServerSocketChannel;

public class Main {

    public static void main(String[] args) {
        Class<? extends ServerChannel> serverChannel;   // The channel that listens for new connections
        EventLoopGroup loopGroup;   // The "new connection polling loop"?

        serverChannel = NioServerSocketChannel.class;
        loopGroup = new NioEventLoopGroup(0);

        new ServerBootstrap().channel(serverChannel).childHandler(new ChannelInitializer<Channel>() {
            @Override
            protected void initChannel(Channel channel) throws Exception {
                try {
                    channel.config().setOption(ChannelOption.TCP_NODELAY, true);
                } catch (ChannelException channelException) {
                    System.out.println(channelException);
                }

                System.out.println("Channel at " + channel.remoteAddress().toString() + " initialized");
            }
        }).group(loopGroup).localAddress("127.0.0.1", 9110).bind().syncUninterruptibly();

    }
}
```

**Comment by hyperxpro** [comment]
:D

**Comment by CommandCracker8** [comment]
Do you know why `InetAddress.getLocalhost()` didn't work?

**Comment by hyperxpro** [comment]
Because:
```
System.out.println(InetAddress.getLocalHost());       // Workstation/10.8.1.2
System.out.println(InetAddress.getLoopbackAddress()); // localhost/127.0.0.1
```

Localhost and Loopback are different addresses.

**Comment by CommandCracker8** [comment]
Interesting. Thanks for the information. I'll close this now as I don't have any more problems currently :D
