### ISSUE TITLE
netty udp 接收 windows 接收正常, centos 接收不到数据

### ISSUE THREAD

**Issue by xman55555** [netty/netty#11986]
### Actual behavior
 centos 8 不起作用, win 正常
### Minimal yet complete reproducer code (or URL to code)

public class Mserver {

    private static Logger logger = LoggerFactory.getLogger(Mserver.class);
    private static final boolean isLinux = !System.getProperty("os.name").toLowerCase().contains("win");

    public static void showInterface() {
        try {

            Enumeration<NetworkInterface> networkInterfaces = NetworkInterface.getNetworkInterfaces();
            while (networkInterfaces.hasMoreElements()){
                NetworkInterface networkInterface = networkInterfaces.nextElement();
                Enumeration<InetAddress> inetAddresses = networkInterface.getInetAddresses();
                while (inetAddresses.hasMoreElements()){
                    InetAddress inetAddress = inetAddresses.nextElement();
                    if (inetAddress instanceof Inet4Address) {
                        logger.info("接口名称{},接口地址{}",networkInterface.getName(),inetAddress.getHostAddress());
                    }
                }
            }
        } catch (Exception e) {

        }

    }

    public static void main(String[] args) {
        showInterface();
        System.setProperty("java.net.preferIPv4Stack", "true");//只使用IPV4
        // 组播地址
        InetSocketAddress groupAddress = new InetSocketAddress("224.2.1.1", 4444);
        EventLoopGroup group = new NioEventLoopGroup();
        try {
            NetworkInterface ni;
            if (!isLinux) {
                ni = NetworkInterface.getByName("eth3");
            } else {
                ni = NetworkInterface.getByName("ens33");
            }
            Enumeration<InetAddress> addresses = ni.getInetAddresses();
            InetAddress localAddress = null;
            while (addresses.hasMoreElements()) {
                InetAddress address = addresses.nextElement();
                if (address instanceof Inet4Address) {
                    localAddress = address;
                }
            }
            System.out.println(localAddress);
            Bootstrap bootstrap = new Bootstrap();
                  bootstrap.group(group)
                    .channelFactory(new ChannelFactory<Channel>() {
                        @Override
                        public NioDatagramChannel newChannel() {
                            return new NioDatagramChannel(InternetProtocolFamily.IPv4);
                        }
                    })
                    .localAddress(localAddress, groupAddress.getPort())
                    .remoteAddress(localAddress, groupAddress.getPort())
                    //设置Option 组播
                    .option(ChannelOption.IP_MULTICAST_IF, ni)
                    //设置Option 地址
                    .option(ChannelOption.IP_MULTICAST_ADDR, localAddress)
                    //设置地址
                    .option(ChannelOption.SO_REUSEADDR, true)
                    //缓冲区
                    .option(ChannelOption.SO_RCVBUF, 1024 * 1024 * 2)
                    //
                    .handler(new ChannelInitializer<NioDatagramChannel>() {
                        @Override
                        public void initChannel(NioDatagramChannel ch) throws Exception {
                            ChannelPipeline addLast = ch.pipeline().addLast();
                            addLast.addLast(new NioEventLoopGroup(), new UdpServerHandler());
                        }
                    });

            //获取NioDatagramChannel
            NioDatagramChannel channel = (NioDatagramChannel) bootstrap
                    .bind(new InetSocketAddress(groupAddress.getPort())).sync().channel();

            //加入组
            channel.joinGroup(groupAddress, ni).sync();
            //关闭Channel
            channel.closeFuture().await();
        } catch (InterruptedException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            group.shutdownGracefully();//优雅退出
        }
    }
}

//只是为了打印数据
UdpServerHandler.java
  ByteBuf byteBuf = datagramPacket.content();
        byte[] dst = new byte[byteBuf.readableBytes()];
        byteBuf.readBytes(dst);
System.out.println("dst: " + HexUtil.encodeHexStr(dst));

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_312"

### OS version (e.g. `uname -a`) centos8 
 4.18.0-305.19.1.el8_4.x86_64 #1 SMP Wed Sep 15 15:39:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by xman55555** [comment]
I use it normally in windows , but in ubuntu environment, udp multicast data cannot be received, it doesnot work.

**Comment by xman55555** [comment]
I want to know how to send data to the server in a loop. It is a time-synchronized sending. Every time I get the local time and send data to the udp server, can you tell me how to find the corresponding example?thank you very much

**Comment by Geker** [comment]
if  client server   communicate  on localhost 
you should investigate the option IP_MULTICAST_LOOP_DISABLED, the option behavior diff on win or linux
