### ISSUE TITLE
PooledByteBufAllocator.pinnedDirectMemory is sometimes returning 0 even if some direct buffers are used

### ISSUE THREAD

**Issue by pderop** [netty/netty#11984]
I'm trying to monitor the estimate of memory that is used by in-use direct buffers.
To do so, I'm trying to use the PooledByteBufAllocator.pinnedDirectMemory() method but sometimes, it seems that this method is returning 0 even if some buffers are currently allocated and used (not yet released).

### Expected behavior

PooledByteBufAllocator.pinnedDirectMemory() should not return 0 in case some buffers are currently allocated.

### Actual behavior

Sometimes, not always, it seems that the PooledByteBufAllocator.pinnedDirectMemory() is returning 0 even if some buffers are allocated.

### Steps to reproduce

Please check attached sample project: 

[netty.pinnedMemory.test.tar.gz](https://github.com/netty/netty/files/7835795/netty.pinnedMemory.test.tar.gz)

The Test class is allocating some buffers, and before releasing them, it displays the pinned direct memory. It also displays an estimate of used memory by traversing arena of direct buffers, and for each arena, it accumulates the diff between the  chunk size and the bytes that are not yet allocated by in-use buffers:

```
    static long usedMem(List<PoolArenaMetric> arenas) {
        long totalUsed = 0;
        for (PoolArenaMetric arenaMetrics : arenas) {
            for (PoolChunkListMetric arenaMetric : arenaMetrics.chunkLists()) {
                for (PoolChunkMetric chunkMetric : arenaMetric) {
                    // chunkMetric.chunkSize() returns maximum of bytes that can be served out of the chunk
                    // and chunkMetric.freeBytes() returns the bytes that are not yet allocated by in-use buffers
                    totalUsed += (chunkMetric.chunkSize() - chunkMetric.freeBytes());
                }
            }
        }
        return totalUsed;
    }
```
To run the program:

./gradlew jar
./gradlew runTest

The program displays many logs, like this:

```
used=1810432, pinned=1372971008
used=2097152, pinned=1373257728
used=1974272, pinned=1371643904
```

_used_ corresponds to the result of the _usedMem_ method shown above, and _pinned_ corresponds to the result of the call to alloc.pinnedDirectMemory().

Now, sometimes, you will notice that the pinned memory is zero:

```
used=2031616, pinned=1835008
used=1892352, pinned=188416
used=1916928, pinned=212992
used=1892352, pinned=0
used=2023424, pinned=0
used=2072576, pinned=0
...
used=2220032, pinned=2146779136
used=2310144, pinned=2146869248
used=1843200, pinned=2144354304
used=1974272, pinned=2144485376
used=2007040, pinned=2144518144
used=1998848, pinned=2143215616
used=2138112, pinned=2143354880
```

To stop, just press CTRL-C

### Minimal yet complete reproducer code (or URL to code)

Please see attached sample project above

### Netty version

4.1.72.Final

### JVM version (e.g. `java -version`)

openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Zulu 8.56.0.23-CA-macos-aarch64) (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Zulu 8.56.0.23-CA-macos-aarch64) (build 25.302-b08, mixed mode)

### OS version (e.g. `uname -a`)

MacOS M1:

Darwin xxx 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64

The issue is also observed on linux Ubuntu:

Linux xxx 5.13.0-22-generic #22-Ubuntu SMP Fri Nov 5 13:21:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@chrisvest can you have a look at this one ?

**Comment by chrisvest** [comment]
I got the test running and showing the expected failure. It disappears if I add a `alloc.trimCurrentThreadCache();` after the `release()` loop. The accounting is done in a bad place, where we might either miss out on activity happening at the cache layer, or we'll have the same memory activity accounted twice. I need to find a better place to do the accounting of the pinned memory.
