### ISSUE TITLE
[Question] Calling ReferenceCountUtil.release from another thread

### ISSUE THREAD

**Issue by ykalay** [netty/netty#11983]
Hi everyone.
I have a small question
Can we call ReferenceCountUtil.release from another Thread? I mean Is there any relation between reference-counting and netty io thread-local/context or I can call the ReferenceCountUtil.release from anywhere?

Thanks

**Comment by hyperxpro** [comment]
Yes, you can.

**Comment by ykalay** [comment]
@hyperxpro Thanks for the answer. So there is no relation between reference counting of objects and netty io thread local?

**Comment by hyperxpro** [comment]
By design, ByteBuf are thread-safe.

**Comment by ykalay** [comment]
Thanks @hyperxpro
