### ISSUE TITLE
PoolChunkList free PoolChunk and get  usage(1) = minUsage(1) cause PoolChunk waste memory 

### ISSUE THREAD

**Issue by yuanyetao** [netty/netty#11998]
We use PooledByteBufAllocator.DEFAULT to deal http data allocation. 

### Expected behavior
The count of PoolChunks in PoolChunkList can be balanced automatically with the data deal pressure.
When http process data in low waterline, less count of PoolChunks costs and consumer less noheap memory.

### Actual behavior
When Big data response appears and data loaded into DirectByteBuf.  I found that many PoolChunks appeared in Jvm Heap Dump and every PoolChunk consumed about 16MB.  After Big data response gone away,  the PoolChunk's count didn't reduce. When debuged with idea, i found that some PoolChunk  which needed to be freed was  not released because the usage which is 1 after  calculated  equaled the minUsage(1) of the PoolChunkList.  

`io.netty.buffer.PoolChunkList#free`
`if (chunk.usage() < minUsage) {`
` remove(chunk);`
` return move0(chunk);`
`}`

### Netty version
4.1.25
### JVM version (e.g. `java -version`)
jdk1.8.0_291
### OS version (e.g. `uname -a`)
Max OS X

**Comment by normanmaurer** [comment]
@yuanyetao please upgrade to the latest netty version and check if the problem still exists.
