### ISSUE TITLE
Netty discards hostnames without dots from TLS SNI

### ISSUE THREAD

**Issue by Spikhalskiy** [netty/netty#12005]
### Expected behavior

If we establish a secured client connection to `temporal.local:9090`, `temporal.local` hostname is used in TLS SNI Extension.
If we establish a secured client connection to `temporal:9090`, `temporal` hostname is used in TLS SNI Extension.

`temporal` is a valid SNI hostname as much as `temporal.local`. `new javax.net.ssl.SNIHostName(hostname)` doesn't throw for both of them.

### Actual behavior
If we establish a secured client connection to `temporal.local:9090`, `temporal.local` is coming as an SNI.
If we establish a secured client connection to `temporal:9090`, `temporal` is DISCARDED and NOT coming as an SNI.

### Root cause

Netty enforces that the SNI hostname has to have a dot.

https://github.com/netty/netty/blob/b6021330a7db9bf2a1a5e7fe9bb4b0584bb50ecd/handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java#L344
```java
  // Use SNI if peerHost was specified and a valid hostname
  // See https://github.com/netty/netty/issues/4746
  if (clientMode && SslUtils.isValidHostNameForSNI(peerHost)) {
      // If on java8 and later we should do some extra validation to ensure we can construct the
      // SNIHostName later again.
      if (PlatformDependent.javaVersion() >= 8) {
          if (Java8SslUtils.isValidHostNameForSNI(peerHost)) {
              SSL.setTlsExtHostName(ssl, peerHost);
              sniHostNames = Collections.singletonList(peerHost);
          }
      } else {
          SSL.setTlsExtHostName(ssl, peerHost);
          sniHostNames = Collections.singletonList(peerHost);
      }
  }
```

https://github.com/netty/netty/blob/b6021330a7db9bf2a1a5e7fe9bb4b0584bb50ecd/handler/src/main/java/io/netty/handler/ssl/SslUtils.java#L482
```java
static boolean isValidHostNameForSNI(String hostname) {
    return hostname != null &&
           hostname.indexOf('.') > 0 &&
           !hostname.endsWith(".") && !hostname.startsWith("/") &&
           !NetUtil.isValidIpV4Address(hostname) &&
           !NetUtil.isValidIpV6Address(hostname);
}
```

### Netty version

4.1.63.Final, master(765e56a93ae15d682a0611fbb3886eb7df738fc9)

**Comment by Spikhalskiy** [comment]
@normanmaurer I can prepare a PR if you confirm that it looks like a bug and there is no reason why it has to be implemented this way.

**Comment by normanmaurer** [comment]
@Spikhalskiy I think you are right... Please open a PR with a unit test. thanks !

**Comment by Spikhalskiy** [comment]
After some digging, I found the following code in `sun.security.ssl.Utilities`
```
    private static SNIHostName rawToSNIHostName(String hostname) {
        SNIHostName sniHostName = null;
        if (hostname != null && hostname.indexOf('.') > 0 &&
                !hostname.endsWith(".") &&
                !IPAddressUtil.isIPv4LiteralAddress(hostname) &&
                !IPAddressUtil.isIPv6LiteralAddress(hostname)) {

            try {
                sniHostName = new SNIHostName(hostname);
            } catch (IllegalArgumentException iae) {
                // don't bother to handle illegal host_name
                if (SSLLogger.isOn && SSLLogger.isOn("ssl")) {
                     SSLLogger.fine(hostname + "\" " +
                        "is not a legal HostName for  server name indication");
                }
            }
        }
        return sniHostName;
    }
```
So, JDK itself makes a `hostname.indexOf('.') > 0` check and requires SNI to be a Fully Qualified Domain Name, otherwise, it discards it. So, it looks like Netty right now behaves the same way as JDK.

I verified it with the specification of [SNI TLS Extension](https://datatracker.ietf.org/doc/html/rfc3546#section-3.1) and indeed: `"HostName" contains the fully qualified DNS hostname of the server`.
FQDN can't be just a hostname, it has to include a domain, even if this domain is "local".

I will still submit a PR with a test and comments about why it's implemented the following way for the next reader.

**Comment by Spikhalskiy** [comment]
Not a bug
