### ISSUE TITLE
Test testWriteBEAndReadOnLEByteBuf fails after upgrading to 4.1.72.Final

### ISSUE THREAD

**Issue by sanjaypujare** [netty/netty#12009]
### Expected behavior
The following test should pass

### Actual behavior
The test fails

### Steps to reproduce

We used to have the following test pass with 4.1.63.Final but after upgrading to 4.1.72.Final the test failed. Pls let us know if the test needs to be modified.

### Minimal yet complete reproducer code (or URL to code)

```

import io.netty.buffer.ByteBuf;
import io.netty.buffer.Unpooled;
import java.nio.ByteOrder;

...

  /**
   * Shows the write on LE ByteBuf would put the value as LE. Read on LE ByteBuf would
   * just read ByteBuf along the way and assemble it reversely. ReadLE is just reverse the result
   * from ReadBE.
   */
  @SuppressWarnings("deprecation")
  @Test
  public void testWriteBEAndReadOnLEByteBuf() {
    short message = (short) 0xD050;
    short reverse = (short) 0x50D0;
    ByteBuf b = Unpooled.buffer(MEDIUM_BYTE_BUF_SIZE).order(ByteOrder.LITTLE_ENDIAN);
    b.writeShort(message);

    assertThat(b.getShortLE(0)).isEqualTo(reverse);
    assertThat(b.getShort(0)).isEqualTo(message);
  }
  public static final int MEDIUM_BYTE_BUF_SIZE = 1024;
```

### Netty version
4.1.72.Final

### JVM version (e.g. `java -version`)
1.8

### OS version (e.g. `uname -a`)
MacOS BigSur

**Comment by chrisvest** [comment]
This is correct behaviour. `*LE` methods should always work in little-endian mode, rather than swap the configured mode.
See #11706, #10747, and #11700
