### ISSUE TITLE
is there a thread safety issue in allocateSubpage method on Netty-4.1.20.Final ?

### ISSUE THREAD

**Issue by RexChengZhu** [netty/netty#12010]
i've got a question when reading the source code on Netty-4.1.20.Final . in PollChunk#allocateSubpage

```java
      PoolSubpage<T> head = arena.findSubpagePoolHead(normCapacity);
        synchronized (head) {
            int d = maxOrder; 
            int id = allocateNode(d);
      }
```
what if different thread with different head all to allocateNode.. one thread find a node which is the child of the other thread find.
won't be a problem?
```java
private int allocateNode(int d) {
        int id = 1;
        int initial = - (1 << d); // has last d bits = 0 and rest all = 1
        byte val = value(id);
        if (val > d) { // unusable
            return -1;
        }
        while (val < d || (id & initial) == 0) { // id & initial == 1 << d for all ids at depth d, for < d it is 0
            id <<= 1;
            val = value(id);
            if (val > d) {
                id ^= 1;
                val = value(id);
            }
        }
        byte value = value(id);
        assert value == d && (id & initial) == 1 << d : String.format("val = %d, id & initial = %d, d = %d",
                value, id & initial, d);
        setValue(id, unusable); // mark as unusable
        updateParentsAlloc(id);
        return id;
    }
```

**Comment by chrisvest** [comment]
4.1.20 is pretty old.
In the latest code, the capacity maps to a size index, and there's a head per size index, so all modifications for a relevant size index fall under that lock.
Additionally, we also synchronise on the arena.

**Comment by RexChengZhu** [comment]
cuz i'm working in a bank system. lots of things are old . is this a thread safety issue ? or i misunderstood  the code . otherwise i need to report the bug to update the Netty version
