### ISSUE TITLE
netty-transport-native-* Bundles missing a Fragment-Host

### ISSUE THREAD

**Issue by MrEasy** [netty/netty#12017]
### Initial Position
The netty-transport-native-epoll and -kqueue bundles ship native libraries, e.g. for linux_x86_64.
The do declare this in their manifest via Bundle-NativeCode header to make it available in an OSGi environment.

### Actual behavior
However, when the native library gets loaded via e.g. io.netty.channel.epoll.Epoll, it is not found with the following error:

```
java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_epoll_x86_64
caused by:
    java.io.FileNotFoundException: META-INF/native/libnetty_transport_native_epoll_x86_64.so
```

You see that the file location is correctly retrieved from manifest header of bundle netty-transport-native-epoll, but class EPoll is trying to load the resource from its bundle classloader (netty-transport-classes-epoll), which the resource does not reside in.

### Evaluation and Proposal for Fix
What is missing from my point of view is the declaration of the Fragement-Host, this bundle shipping the native lib should get attached to. In case of epoll:
`Fragment-Host: io.netty.transport-classes-epoll`
Altered this in my environment (Karaf with Artemis using Netty) and it immediately works then - class EPoll can the nsuccessfully load the native lib being shipped in the fragment bundle.

### Netty version
4.1.73

### JVM version
openjdk version "17.0.1" 2021-10-19 LTS

### OS version
Ubuntu 21.10, 5.13.0-25-generic

**Comment by normanmaurer** [comment]
@MrEasy can you provide a PR ?

**Comment by MrEasy** [comment]
> @MrEasy can you provide a PR ?

Sure, can do if you agree.
Would do it for epoll and kqueue. Not for netty-transport-native-unix-common/linux-x86_64, since it does not ship a library, only sources as far as I see.

**Comment by normanmaurer** [comment]
@MrEasy yes sounds good... thanks!

**Comment by MrEasy** [comment]
PR#12018 for main. Also applicable for `4.1` branch
