### ISSUE TITLE
The comment in PoolThreadCache is wrong, there is no longer tiny

### ISSUE THREAD

**Issue by xuziyang** [netty/netty#12015]
### Expected behavior
Remove tiny from comments

### Actual behavior
Comments containing tiny
![image](https://user-images.githubusercontent.com/8465969/149874408-254c0e7a-04be-48a5-9ac4-f5ce4e7de59e.png)

**Comment by normanmaurer** [comment]
@xuziyang Fixed... thanks https://github.com/netty/netty/pull/12020
