### ISSUE TITLE
Unexpected cause in SslCloseCompletionEvent

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [netty/netty#12027]
I noticed one thing when trying to remove SslHandler to downgrade connection to plaintext - 

There is no check on handshake state here
https://github.com/netty/netty/blob/d34212439068091bcec29a8fad4df82f0a82c638/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L700

but message says  `"...before handshake completed"` and sometimes it's not true - see reproducer, I can see that handshake is done but still see this message.

### Expected behavior

either don't notify close promise if handshake is done by additional check like
`if (!sslClosePromise.isDone() && !handshakePromise.isDone()) `

or keep condition but rephrase error message like "...removed before ssl close future is done" - not sure it makes sense

### Actual behavior

Handshake is done but message "`SslHandler removed before handshake completed"` is shown (reproducer output below)

### Minimal yet complete reproducer code (or URL to code)

```
EventLoopGroup group = new NioEventLoopGroup();
Bootstrap bootstrap = new Bootstrap()
    .group(group)
    .channel(NioSocketChannel.class)
    .handler(new ChannelInitializer<Channel>() {
        @Override
        protected void initChannel(Channel ch) throws Exception {
            SslContext build = SslContextBuilder.forClient().trustManager(InsecureTrustManagerFactory.INSTANCE).build();
            final SslHandler sslHandler = build.newHandler(ch.alloc());
            sslHandler.engine().setUseClientMode(true);
            ch.pipeline().addFirst("client-handler", sslHandler);
        }
    });

ServerBootstrap serverBootstrap = new ServerBootstrap()
    .group(group)
    .channel(NioServerSocketChannel.class)
    .childHandler(new ChannelInitializer<Channel>() {
        @Override
        protected void initChannel(Channel ch) throws Exception {
            SelfSignedCertificate ssc = new SelfSignedCertificate();
            SslContext build = SslContextBuilder.forServer(ssc.certificate(), ssc.privateKey()).build();
            final SslHandler sslHandler = build.newHandler(ch.alloc());
            sslHandler.handshakeFuture().addListener(future -> {
                if (future.isSuccess()) {
                    System.out.println("server: handshake is done");
                    ch.pipeline().remove("server-handler");
                }

            });
            sslHandler.sslCloseFuture().addListener(future -> {
                if (future.cause() != null) {
                    System.out.println("server: close future has not non null casue");
                    future.cause().printStackTrace();
                }
            });
            ch.pipeline().addFirst("server-handler", sslHandler);
        }
    });
serverBootstrap.bind("localhost", 1234).sync();
bootstrap.connect("localhost", 1234).sync();
```

**Output:**

```
server: handshake is done
server: close future has not non null casue
javax.net.ssl.SSLHandshakeException: SslHandler removed before handshake completed
	at io.netty.handler.ssl.SslHandler.handlerRemoved0(SslHandler.java:695)
```

### Netty version
4.1.73.Final

### JVM version (e.g. `java -version`)
openjdk version "15.0.2" 2021-01-19

P.S.
Removing `SslHandler` works in general and it looks like such `SslCloseCompletionEvent` doesn't hurt but there is one case where code hangs - I tried adding `if (!sslClosePromise.isDone() && !handshakePromise.isDone())` to my local custom `SslHandler` and this error was gone but it didn't help with hanging. I decided to report anyway since this message looked confusing.

**Comment by normanmaurer** [comment]
@BaurzhanSakhariev thanks for reporting! PTAL https://github.com/netty/netty/pull/12033
