### ISSUE TITLE
 netty-testsuite-native

### ISSUE THREAD

**Issue by FeiYanWu** [netty/netty#12026]
### Expected behavior
main:
     [echo] Current commit: 3cf83d5a2a on 2022-01-19 20:41:16 +0100
   [delete] Deleting: D:\software\ideaworkspace\netty\testsuite-native\target\classes\META-INF\io.netty.versions.properties
[propertyfile] Creating new property file: D:\software\ideaworkspace\netty\testsuite-native\target\classes\META-INF\io.netty.versions.properties
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ netty-testsuite-native ---
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ netty-testsuite-native ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\software\ideaworkspace\netty\testsuite-native\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ netty-testsuite-native ---
[INFO] No sources to compile
[INFO] 
[INFO] --- forbiddenapis:2.2:check (check-forbidden-apis) @ netty-testsuite-native ---
[INFO] Scanning for classes to check...
[WARNING] No classes found in 'D:\software\ideaworkspace\netty\testsuite-native\target\classes' (includes=[**/*.class], excludes=null), forbiddenapis check skipped.
[INFO] 
[INFO] --- animal-sniffer-maven-plugin:1.16:check (default) @ netty-testsuite-native ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1
[INFO] 
[INFO] <<< maven-bundle-plugin:2.5.4:manifest (generate-manifest) < process-classes @ netty-testsuite-native <<<
[INFO] 
[INFO] 
[INFO] --- maven-bundle-plugin:2.5.4:manifest (generate-manifest) @ netty-testsuite-native ---
[WARNING] Manifest io.netty:netty-testsuite-native:jar:4.1.74.Final-SNAPSHOT : Unused Export-Package instructions: [io.netty.*] 
[WARNING] Manifest io.netty:netty-testsuite-native:jar:4.1.74.Final-SNAPSHOT : Unused Import-Package instructions: [sun.misc.*, sun.security.*] 
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ netty-testsuite-native ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\software\ideaworkspace\netty\testsuite-native\src\test\resources
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ netty-testsuite-native ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to D:\software\ideaworkspace\netty\testsuite-native\target\test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] D:\software\ideaworkspace\netty\testsuite-native\src\test\java\io\netty\testsuite_native\NativeLoadingTest.java:[18,29] ����: �����io.netty.channel.epoll������
[ERROR] D:\software\ideaworkspace\netty\testsuite-native\src\test\java\io\netty\testsuite_native\NativeLoadingTest.java:[19,30] ����: �����io.netty.channel.kqueue������
[ERROR] D:\software\ideaworkspace\netty\testsuite-native\src\test\java\io\netty\testsuite_native\NativeLoadingTest.java:[20,34] ����: �����io.netty.resolver.dns.macos������
[ERROR] D:\software\ideaworkspace\netty\testsuite-native\src\test\java\io\netty\testsuite_native\NativeLoadingTest.java:[30,8] ����: �Ҳ�������
  ����:   ���� KQueue
  λ��: �� NativeLoadingTest
[ERROR] D:\software\ideaworkspace\netty\testsuite-native\src\test\java\io\netty\testsuite_native\NativeLoadingTest.java:[36,8] ����: �Ҳ�������
  ����:   ���� MacOSDnsServerAddressStreamProvider
  λ��: �� NativeLoadingTest
[ERROR] D:\software\ideaworkspace\netty\testsuite-native\src\test\java\io\netty\testsuite_native\NativeLoadingTest.java:[42,8] ����: �Ҳ�������
  ����:   ���� Epoll
  λ��: �� NativeLoadingTest
[INFO] 6 errors 
................
[INFO] Netty/Testsuite/Shading ............................ SUCCESS [ 25.056 s]
[INFO] Netty/Testsuite/Native ............................. FAILURE [  2.843 s]
[INFO] Netty/Testsuite/NativeImage ........................ SKIPPED
[INFO] Netty/Testsuite/NativeImage/Client ................. SKIPPED
[INFO] Netty/Testsuite/NativeImage/ClientRuntimeInit ...... SKIPPED
[INFO] Netty/Transport/BlockHound/Tests ................... SKIPPED
[INFO] Netty/Microbench ................................... SKIPPED
[INFO] Netty/BOM .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:12 min
[INFO] Finished at: 2022-01-21T13:22:43+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:testCompile (default-testCompile) on project netty-testsuite-native: Compilation failure: Compilation failure: 
[ERROR] D:\software\ideaworkspace\netty\testsuite-native\src\test\java\io\netty\testsuite_native\NativeLoadingTest.java:[18,29] ����: �����io.netty.channel.epoll������
[ERROR] D:\software\ideaworkspace\netty\testsuite-native\src\test\java\io\netty\testsuite_native\NativeLoadingTest.java:[19,30] ����: �����io.netty.channel.kqueue������
[ERROR] D:\software\ideaworkspace\netty\testsuite-native\src\test\java\io\netty\testsuite_native\NativeLoadingTest.java:[20,34] ����: �����io.netty.resolver.dns.macos������
[ERROR] D:\software\ideaworkspace\netty\testsuite-native\src\test\java\io\netty\testsuite_native\NativeLoadingTest.java:[30,8] ����: �Ҳ�������
[ERROR]   ����:   ���� KQueue
[ERROR]   λ��: �� NativeLoadingTest
[ERROR] D:\software\ideaworkspace\netty\testsuite-native\src\test\java\io\netty\testsuite_native\NativeLoadingTest.java:[36,8] ����: �Ҳ�������
[ERROR]   ����:   ���� MacOSDnsServerAddressStreamProvider
[ERROR]   λ��: �� NativeLoadingTest
[ERROR] D:\software\ideaworkspace\netty\testsuite-native\src\test\java\io\netty\testsuite_native\NativeLoadingTest.java:[42,8] ����: �Ҳ�������
[ERROR]   ����:   ���� Epoll
[ERROR]   λ��: �� NativeLoadingTest

### Actual behavior
build source code 

### Netty version
Netty latest(4.1)

### JVM version (e.g. `java -version`)
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### OS version (e.g. `uname -a`)
MINGW64_NT-10.0-15063 WYF-PC 3.1.7-340.x86_64 2021-03-26 22:17 UTC x86_64 Msys

**Comment by normanmaurer** [comment]
What is the issue ? Please include some details here...

**Comment by Kvicii** [comment]
@FeiYanWu build failed?

**Comment by Kvicii** [comment]
@normanmaurer hi there, I just joined,could you guide me how to contribute netty, I can start with the basic😁

**Comment by normanmaurer** [comment]
Works here and also on the CI. Maybe something is wrong with your setup and so the class path.

**Comment by FeiYanWu** [comment]
Thank you for your reply.
