### ISSUE TITLE
Vulnerability in Netty with High Severity

### ISSUE THREAD

**Issue by shyam94** [netty/netty#12046]
Hi,

Veracode scan has reported some High Severity Vulnerabilities in Netty library. 

**File:**  \io\netty\util\internal\NativeLibraryLoader.java:325
**Reason:** OS Command Injection: An attacker can put any command which if executed could be malicious. 
**CWE ID:** 78

**File:**  \io\netty\util\internal\NativeLibraryUtil.java:36 and 38
**Reason:** If Attacker changes the libName to something else, then the code will open that Library and could be malicious.
**CWE ID:** 114

The version of Netty we're using is **netty-common-4.1.73.Final.jar.**

Please let me know if these vulnerabilities are false positives or needs to be addressed.

Thanks,
Shyam Joshi

**Comment by chrisvest** [comment]
There are no code paths that I can see, that would allow externally controlled data into those functions.

**Comment by chrisvest** [comment]
(Checked using Intellij Data-Flow To Here, and found all incoming code paths derive from constants)
