### ISSUE TITLE
Vulnerability found in Netty 4.1.73 version

### ISSUE THREAD

**Issue by shyam94** [netty/netty#12055]
Hi,

Veracode scan reported Medium Vulnerabilities found in netty.

1. **netty-handler-4.1.73.Final.jar**
- Files:
  - io/netty/handler/ssl/JdkAlpnSslUtils.java : 51
  - io/netty/handler/ssl/JdkSslClientContext.java : 292
  - io/netty/handler/ssl/JdkSslContext.java : 74
  - io/netty/handler/ssl/JdkSslServerContext.java : 271
  - io/netty/handler/ssl/OpenSslX509TrustManagerWrapper.java : 159
  - io/netty/handler/ssl/SslUtils.java : 188 & 190
- CWE ID: 757
- Reason: Selection of Less-Secure Algorithm During Negotiation ('Algorithm Downgrade') (check CWE for more details).

2. **netty-resolver-4.1.73.Final.jar**
- Files:
  - io/netty/resolver/HostsFileEntriesProvider.java : 307
- CWE ID: 73
- Reason: External Control of File Name or Path. This call contains a path manipulation flaw. The argument to the function is a
                filename constructed using untrusted input. (check CWE for more details).
                     
 
3. **netty-common-4.1.73.Final.jar**
- CWE ID: 377
   - Files:
      - io/netty/util/internal/PlatformDependent.java : 1438 & 1440
   - Reason: Insecure Temporary File. Creating and using insecure temporary files can leave application and system data vulnerable to 
                   attack. In particular, file names created by the tmpnam family of functions can be easily guessed by an attacker (More 
                   details on CWE)

- CWE ID: 331
   - Files:
      - io/netty/util/internal/NativeLibraryLoader.java: 350
   - Reason: Standard random number generators do not provide a sufficient amount of entropy when used for security purposes.
                   Attackers can brute force the output of pseudorandom number generators such as rand(). (Check CWE for more details).
                
- CWE ID: 117
   - Files:
      - io/netty/util/internal/logging/Log4JLogger.java: 328
      - io/netty/util/internal/logging/CommonsLogger.java: 305
   - Reason: Improper Output Neutralization for Logs. A function call could result in a log forging attack. Writing untrusted data into a log file allows an attacker to forge log entries or inject malicious content into log files. (More details on CWE).

- CWE ID: 732
   - Files:
      - io/netty/util/internal/PlatformDependent.java: 1442
   - Reason: The software specifies permissions in a way that causes the resource to be accessible to an unintended sphere of control. 
                   A common manifestation of this is setting overly lax file permissions. (More details on CWE).
                   
Please let me know if these are false Positives or needs to be addressed.

Thanks,
Shyam Joshi

**Comment by hyperxpro** [comment]
Thanks for reporting. However, all of them are false alerts.

Also, please do a little bit of self-research before reporting tool-generated alerts.
