### ISSUE TITLE
mvn command is empty package

### ISSUE THREAD

**Issue by GreatBareBear** [netty/netty#12062]
Hello, there are already several versions. The jars packaged by the mvn command is empty package, only 4k, and they are also on maven snapshot repository.

**Comment by chrisvest** [comment]
Can you be more specific? If you are talking about `netty-all`, it's on purpose that the jar file is empty. It's now a pom-dependency that pull in all other modules as transitive dependencies.

**Comment by Kvicii** [comment]
@GreatBareBear 
I don't think that's the issue.Of course if you can provide more information
