### ISSUE TITLE
How to get full jar

### ISSUE THREAD

**Issue by andreasdc** [netty/netty#12068]
Earlier versions of netty-all had size of around 4mb, currently it has around 4kb. How to get full working single jar of the newest netty? Thank you for help.

**Comment by chrisvest** [comment]
We don't provide pre-built shaded jars anymore, because it lead to class-path conflicts, and issues with loading the native code.
See https://github.com/netty/netty/pull/11732#issuecomment-949432023

**Comment by andreasdc** [comment]
> We don't provide pre-built shaded jars anymore, because it lead to class-path conflicts, and issues with loading the native code. See [#11732 (comment)](https://github.com/netty/netty/pull/11732#issuecomment-949432023)

What's the best method to have it?

**Comment by chrisvest** [comment]
Depends on what you're trying to do. I don't know why you want it in one jar to begin with. I could think of many reasons, but I don't know your situation specifically.

**Comment by andreasdc** [comment]
> Depends on what you're trying to do. I don't know why you want it in one jar to begin with. I could think of many reasons, but I don't know your situation specifically.

I load libraries from a folder, so it would be better to have it in one jar.

**Comment by chrisvest** [comment]
They can be extracted and repackaged with the `jar` tool.

**Comment by andreasdc** [comment]
> They can be extracted and repackaged with the `jar` tool.

Do you have some small tutorial by any chance?

**Comment by andreasdc** [comment]
> They can be extracted and repackaged with the `jar` tool.

How to get all jars then?

**Comment by normanmaurer** [comment]
@andreasdc you can just "depend" on the netty-all jar and maven / gradle will download all the needed jars. All the jars are published to maven central.

**Comment by andreasdc** [comment]
> @andreasdc you can just "depend" on the netty-all jar and maven / gradle will download all the needed jars. All the jars are published to maven central.

I don't use maven/gradle, that's why it's problematic. Is there a place other than jar-download website to get all jars and in the best scenario all in one jar?

**Comment by normanmaurer** [comment]
no

**Comment by andreasdc** [comment]
> no

How to pack it in 1 jar then?
