### ISSUE TITLE
Throwing protocol error when http2 max concurrent streams is exceeded instead of resStream

### ISSUE THREAD

**Issue by stefanklas** [netty/netty#12065]
### Expected behavior
I'm new to Http2, and was trying to implement some load shedding on our server by limiting the number of concurrent streams set. This is currently fixed at 100. When setting the maxConcurrentStream in the HttpToHttp2ConnectionHandler, I was expecting to get see the behaviour mentioned in the spec (https://httpwg.org/specs/rfc7540.html#rfc.section.8.1.4)  and get a RST_STREAM frame back to the client. 

### Actual behavior
Instead i am getting an error, Stream ID does not exist. This results in a connection error, causing a GOAWAY with "PROTOCOL_ERROR" and closes the whole connection instead of just the stream? I have not understood if I am doing anything wrong here.

![Screenshot 2022-02-01 at 15 50 15](https://user-images.githubusercontent.com/98832797/152010319-bf8355f0-bf74-4ac8-8244-06019b706653.png)

![Screenshot 2022-02-01 at 15 50 30](https://user-images.githubusercontent.com/98832797/152004563-d3ad7869-029b-49cb-a845-d45a1ca9e60b.png)

![Screenshot 2022-02-01 at 16 32 55](https://user-images.githubusercontent.com/98832797/152009792-addba3b9-86a0-4d91-b435-3d15457d3bfc.png)

### Minimal yet complete reproducer code (or URL to code)

Server Configuration

```
public class Http2OnlyHandler extends ApplicationProtocolNegotiationHandler {
 @Override
    protected void configurePipeline(ChannelHandlerContext ctx, String protocol) throws Exception {
        if (ApplicationProtocolNames.HTTP_2.equals(protocol)) {
            configureRedisPipeline(ctx);
            return;
        }

        if (ApplicationProtocolNames.HTTP_1_1.equals(protocol)) {
            configureFallback(ctx);
            return;
        }

        throw new IllegalStateException("Unsupported protocol: " + protocol);
    }


  private void configureRedisPipeline(ChannelHandlerContext ctx) {
  
    DefaultHttp2Connection connection = new DefaultHttp2Connection(true);
     InboundHttp2ToHttpAdapter listener = new InboundHttp2ToHttpAdapterBuilder(connection)
        .propagateSettings(true).validateHttpHeaders(false)
        .maxContentLength(maxContentLength).build();
  
    HttpToHttp2ConnectionHandler connectionHandler = new HttpToHttp2ConnectionHandlerBuilder()
        .frameListener(tester)
        .initialSettings(new Http2Settings().maxConcurrentStreams(100))
        .connection(connection).build();
  
    ctx.pipeline().addLast(connectionHandler);
  }
}


 bootstrap.group(bossGroup, workerGroup)
                .channel(channelClazz)
                .childHandler(new ChannelInitializer<SocketChannel>() {
                    @Override
                    protected void initChannel(SocketChannel ch) {
                        ch.pipeline().addLast(sslCtx.newHandler(ch.alloc()),
                            new Http2OnlyHandler(),
                            etc...)
                    }
                 })
```

Client:
```
channel.eventLoop().submit(() -> {
            int streamId = this.streamId.addAndGet(2);

            req.headers().setInt(HttpConversionUtil.ExtensionHeaderNames.STREAM_ID.text(), streamId);
            req.headers().set(HttpConversionUtil.ExtensionHeaderNames.SCHEME.text(), "https");
            req.headers().set(HttpHeaderNames.HOST, "server");
            req.headers().add(HttpHeaderNames.ACCEPT_ENCODING, HttpHeaderValues.GZIP);
            req.headers().add(HttpHeaderNames.ACCEPT_ENCODING, HttpHeaderValues.DEFLATE);

            pendingRequests.put(streamId, new PendingReq<>(responseTransformer, future, System.currentTimeMillis(), (timeoutMs > 0) ? System.currentTimeMillis() + timeoutMs : -1));
            channel.writeAndFlush(req, channel.voidPromise());
        });

}
```

### Netty version
4.1.70.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)
### OS version (e.g. `uname -a`)
Darwin sklas-mac 19.6.0 Darwin Kernel Version 19.6.0: Sun Nov 14 19:58:51 PST 2021; root:xnu-6153.141.50~1/RELEASE_X86_64 x86_64

**Comment by hyperxpro** [comment]
Can you do a PR?

**Comment by alecharmon** [comment]
@hyperxpro Created a pr to address the issue @stefanklas was running into

**Comment by normanmaurer** [comment]
BTW I think PROTOCOL_ERROR is also fine here: https://httpwg.org/specs/rfc7540.html#rfc.section.5.1.2

**Comment by idelpivnitskiy** [comment]
Heads up that the original PR #13485 was reverted in Netty 4.1.96: https://github.com/netty/netty/commit/013c38298f6d28ec14543d02ede9bb6a6472ca3f
