### ISSUE TITLE
Netty Shaded high cpu utilization

### ISSUE THREAD

**Issue by anujbansal16** [netty/netty#12078]
Hello,

In one of the service while using the _netty shaded_ to build the channel we have observed a high cpu utilisation. 
While running the profiler on the service we have found that _epollEventLoop_ is consuming most of the cpu.
The problem was resolved when we moved to _netty_ library (NettyChannelBuilder) instead of netty shaded (ManagedChannelBuilder). 

Netty shaded version used that caused high cpu: 1.39.0
`def grpcVersion = '1.39.0'`
`implementation "io.grpc:grpc-netty-shaded:${grpcVersion}"`

netty (we use this to replace netty shaded)
`def grpcVersion = '1.41.0'`
`implementation "io.grpc:grpc-netty:${grpcVersion}"`

### OS version (e.g. `uname -a`): Linux <someip> 5.4.0-1009-aws #9-Ubuntu SMP Sun Apr 12 19:46:01 UTC 2020 x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/12298554/152734226-4b058ecc-fd47-440d-b861-54792f208599.png)

Is this a right place for the clarification on this issue?

**Comment by normanmaurer** [comment]
I think you should open an issue within grpc
