### ISSUE TITLE
Clarify how to engage with the community

### ISSUE THREAD

**Issue by aochagavia** [netty/netty#12071]
_Note: this is kind of a meta-issue, as it is not related to the code_

I have been working with Netty 4 for the past two months and it has been a great experience. At times I would have liked to talk to someone about design choices and general questions about the library, but I wasn't able to find a place where Netty users come together (e.g. an IRC channel, a Discord server, etc). Netty's website brought me to StackOverflow, but my impression was that most questions go unanswered. The website's link to IRC is broken, and when I checked out #netty on liberachat I only saw 3 users in the channel. This leaves me wondering: where does the Netty community hang around? It would be helpful to clarify this somewhere visible, because right now the first impression is that the project is not as active as it used to be.

By the way, in case you are curious, I implemented a MySQL proxy from scratch (i.e. it receives MySQL connections and forwards them to arbitrary backends). I have the feeling that the library has helped me follow good design practices and that it has provided me a solid foundation to build upon, so thanks for that 😉 !

**Comment by hyperxpro** [comment]
@normanmaurer I created the Netty Discord server a few days back. Should we make it public so Netty people can engage with each other?

**Comment by franz1981** [comment]
I am just a Netty committee but I love the @hyperxpro idea 👍  
I saw many people struggling to find the right place to share their experience/hints...and with Netty 5 I believe this is going to happen more frequently

**Comment by normanmaurer** [comment]
@hyperxpro sure lets do it.

**Comment by hyperxpro** [comment]
Here we go: https://discord.gg/q4aQ2XjaCa

Let's spread the word and see how things go.
