### ISSUE TITLE
Does http2 parent channel's handler apply to its http2StreamChannel's msg ? 

### ISSUE THREAD

**Issue by xianggaolinkedin** [netty/netty#12074]
Hi, I'm new to the Netty Http2 APIs. Just have 1 question: 

if I create 1 http2 connection to a server, using `Http2MultiplexHandler`, and also using `Http2StreamChannelBootstrap` to create `Http2StreamChannel` inside the parent connection.  Let's say I have 1 custom handler on the parent connection, will this handler process the inbound and outbound http2Frames inside the  `Http2StreamChannel` child channels?  I tested locally and it seems the answer is no, but just want to get some official answers. 

Thanks. 

### Netty version
4.12

**Comment by normanmaurer** [comment]
no... each `HttpStreamChannel` has its own `ChannelPipeline`
