### ISSUE TITLE
HTTP2 multiplexing:  (1 Http2StreamChannelBootstrap for 1 Http2StreamChannel) vs (1 Http2StreamChannelBootstrap for multi Http2StreamChannel)

### ISSUE THREAD

**Issue by xianggaolinkedin** [netty/netty#12083]
This case is (1 Http2StreamChannelBootstrap for 1 Http2StreamChannel):
https://github.com/netty/netty/blob/201f6b6bb2dcdff07df6e30552b96fedbcf21759/codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexTest.java#L530

but 1 Http2StreamChannelBootstrap can also `open()` multiple Http2StreamChannels. Is there any difference b/w these two ways? Thanks.

**Comment by normanmaurer** [comment]
If you want to use the same configuration for the streams you can re-use the same bootstrap.
