### ISSUE TITLE
Client Http2ConnectionHandler: preface is not flushed on http2 start with prior-knowledge

### ISSUE THREAD

**Issue by mostroverkhov** [netty/netty#12089]
### Expected behavior

Preface is flushed by client `Http2ConnectionHandler` on http2 start with prior-knowledge (aka plaintext) so connection is established (SETTINGS of both sides are sent) in timely manner - which corresponds to netty's http2 `tls/alpn` start.

### Actual behavior

Preface may be [not flushed](https://github.com/netty/netty/blob/51eda20432568ffdf736a673abc6b5a44839413f/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L358) on http2 start with prior-knowledge, so http2 connection is not established unless "next" handler knows this peculiarity and does initial redundant flush (e.g. in `channelActive()`).

### Steps to reproduce

Currently [test](https://github.com/jauntsdn/netty-websocket-http2/commit/97d037ac8209750a724b8e38483c388760cd2620) in netty based project, passes with [workaround](https://github.com/jauntsdn/netty-websocket-http2/commit/668bf0ef26a2f0d2cf7d28b913f708c72c2a0aca).

### Netty version

4.1.74.Final

**Comment by mostroverkhov** [comment]
@normanmaurer am I missing something and this works as intended?

**Comment by normanmaurer** [comment]
Sorry missed that one... let me check

**Comment by normanmaurer** [comment]
Thanks again for the ping... This should be fixed by https://github.com/netty/netty/pull/12349
