### ISSUE TITLE
shoud Http2DataChunkedInput work with the channel?

### ISSUE THREAD

**Issue by alalag1** [netty/netty#12086]
`Http2DataChunkedInput` is introduced in https://github.com/netty/netty/pull/12066 and it looks good to me.

example:

https://github.com/netty/netty/blob/60ebae0553e6b9b1af3ac2f036b3fe271c4d7da2/example/src/main/java/io/netty/example/http2/file/Http2StaticFileServerInitializer.java#L25-L41

does it need to work with `ChunkedWriteHandler` which is per-channel level? we know that there is also a `Http2RemoteFlowController` in Http2 which is per-stream level, should this `Http2DataChunkedInput` need to work on a single stream instead of a channel?

**Comment by hyperxpro** [comment]
It works at stream level and you've to pass `Http2FrameStream` instance.

**Comment by hyperxpro** [comment]
Though, you can use `Http2DataChunkedInput` instance per channel.

**Comment by alalag1** [comment]
Can I just write a `Http2DataChunkedInput ` like

```
ctx.writeAndFlush(new Http2DataChunkedInput(
                     new ChunkedFile(new File(("/home/meow/cats.mp4"))), http2HeadersFrame.stream()));
```
without the `ChunkedWriteHandler`?

```
ChannelPipeline pipeline = ch.pipeline(); 
pipeline.addLast(sslCtx.newHandler(ch.alloc())); 
pipeline.addLast(Http2FrameCodecBuilder.forServer().build()); 
pipeline.addLast(new Http2StaticFileServerHandler()); 
```

In my understanding, the `Http2DataChunkedInput` should be picked up by the `ChunkedWriteHandler`  whose writability is dependent on the `channel#isWritable()` and `ChannelOutboundHandler#channelWritabilityChanged()` intead of the `Http2RemoteFlowController`.
That's what I mean per-channel level,  when to read chunk data depends on the state of the channel, not the stream.

**Comment by alalag1** [comment]
Different streams have different priorities and FlowController states, it could be different with Channel's writability.
eg.
- `Channel#isWritable()` returns `true`
- `Http2RemoteFlowController#isWritable()` returns `false`

it will keep reading chunk data from the `Http2DataChunkedInput` regardless of whether the stream is readable or not.

**Comment by hyperxpro** [comment]
> Can I just write a `Http2DataChunkedInput ` like
> 
> ```
> ctx.writeAndFlush(new Http2DataChunkedInput(
>                      new ChunkedFile(new File(("/home/meow/cats.mp4"))), http2HeadersFrame.stream()));
> ```
> 
> without the `ChunkedWriteHandler`?
> 
> ```
> ChannelPipeline pipeline = ch.pipeline(); 
> pipeline.addLast(sslCtx.newHandler(ch.alloc())); 
> pipeline.addLast(Http2FrameCodecBuilder.forServer().build()); 
> pipeline.addLast(new Http2StaticFileServerHandler()); 
> ```
> 
> In my understanding, the `Http2DataChunkedInput` should be picked up by the `ChunkedWriteHandler` whose writability is dependent on the `channel#isWritable()` and `ChannelOutboundHandler#channelWritabilityChanged()` intead of the `Http2RemoteFlowController`. That's what I mean per-channel level, when to read chunk data depends on the state of the channel, not the stream.

Yes, you can write like that. And you'll require `ChunkedWriteHandler` in pipeline.

**Comment by hyperxpro** [comment]
> Different streams have different priorities and FlowController states, it could be different with Channel's writability. eg.
> 
> * `Channel#isWritable()` returns `true`
> * `Http2RemoteFlowController#isWritable()` returns `false`
> 
> it will keep reading chunk data from the `Http2DataChunkedInput` regardless of whether the stream is readable or not.

@normanmaurer maybe?

**Comment by normanmaurer** [comment]
@hyperxpro `Http2StreamChannel.isWritable()` takes the writability of the stream into account. So it should be all good.

**Comment by alalag1** [comment]
> @hyperxpro `Http2StreamChannel.isWritable()` takes the writability of the stream into account. So it should be all good.

sorry for commenting on closed issue.
what if I do not use `Http2FrameCodecBuilder.forServer().build()` and use `Http2ConnectionHandlerBuilder` to build a `Http2ConnectionHandler`? `Http2StreamChannel` will not work right?

**Comment by normanmaurer** [comment]
right... You should use it with the `Http2MultiplexHandler`

**Comment by alalag1** [comment]
> right... You should use it with the `Http2MultiplexHandler`

emmm...  It would be great if it could support `Http2ConnectionHandlerBuilder`, because `Http2MultiplexHandler`  is a bit too hard for me to understand, and `Http2ConnectionHandlerBuilder` is more simple and easy to understand.
