### ISSUE TITLE
Allow attaching additional metadata to ResourceLeakTrackers

### ISSUE THREAD

**Issue by yawkat** [netty/netty#12080]
It would be useful to add an API to `ResourceLeakDetector` that allows subclasses to supply custom metadata on `DefaultResourceLeak` creation. This would make it easier to associate detected leaks with parameters of the code that caused the leak, e.g. the test case involved (or in my case, the fuzzer input). 

Right now there is no way to hook into the `ResourceLeakTracker` creation at all, so the only workaround seems to be a custom allocator that `touch`es any buffer on creation, but that doesn't work with separately tracked objects.

IMO a sensible API to implement that would be to add a `protected Object initialHint() { return null; }` method that is called for the "creation" `TraceRecord`. This hint would then be reported alongside the "Created at:" stack trace.

Another alternative is to make `track(T obj)` not be final, so that subclasses can `touch` the record with their own information.

I can make a PR for this, if you think this is a sensible thing to support.

### Netty version

4.1.73

### JVM version (e.g. `java -version`)

openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

### OS version (e.g. `uname -a`)

Linux yawkat-oracle 5.13.0-28-generic #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by chrisvest** [comment]
@yawkat @normanmaurer In this PR, we would just be adding this protected do-nothing method, and call it in the right places, right? And then expect down-stream clients to use e.g. `ResourceLeakDetectorFactory` to install custom detectors that override this method? If that's the case, I think it sounds fine, and would be happy to review a PR.
