### ISSUE TITLE
netty-all-4.1.74.final.jar is not a fat jar?

### ISSUE THREAD

**Issue by code-ferry** [netty/netty#12111]
### Expected behavior
I downloaded netty-all-4.1.74.final.jar from the maven repository, only 33KB, not a fat jar. I dependencied the netty-all-4.1.60.final.jar before, it is still a fat jar. Did the packaging method changed?  

### Netty version
4.1.74

**Comment by chrisvest** [comment]
That's on purpose. See https://github.com/netty/netty/pull/11732#issuecomment-949432023
