### ISSUE TITLE
Internal Logging API - make MessageFormatter and FormattingTuple public

### ISSUE THREAD

**Issue by devsprint** [netty/netty#12129]
### Expected behavior
While trying to use netty with ZIO 2.x Logging support I found out that I can't implement properly AbstractInternalLogger  interface for integration with ZIO 2.x, relying on the optimised implementation of MessageFormatter.

### Actual behavior
Should be able to add new Logging integrations.

### Netty version
4.1.74
### JVM version (e.g. `java -version`)
Not dependent on java version
### OS version (e.g. `uname -a`)
Not dependent on OS version.

**Comment by normanmaurer** [comment]
@devsprint I wonder if it would be better to write a `SLF4J ` implement for it and then just use the provided SLF4J implementation for netty ?

**Comment by devsprint** [comment]
To achieve my current work, it is exactly what I did, but I was thinking of removing layers of indirections...
