### ISSUE TITLE
io.netty.internal.tcnative is not optional in MANIFEST.MF of io.netty.handler

### ISSUE THREAD

**Issue by tkohn** [netty/netty#12132]
Hi folks, I updated the netty dependencies in our OSGi project from 4.1.63.Final to 4.1.74.Final to address a few CVEs.
Unfortunately the OSGi App can not start because `io.netty.handler` is missing the dependency `io.netty.internal.tcnative`.

I looked at the MANIFEST.MF files in both versions and found the diff, that `tcnative` is not optional anymore.

### Expected behavior

`io.netty.handler` has an optional dependency on `io.netty.internal.tcnative` like `io.netty.internal.tcnative;resolution:=optional`

[4.1.63.Final-MANIFEST.MF.txt](https://github.com/netty/netty/files/8155143/4.1.63.Final-MANIFEST.MF.txt)

Also the handler pom still declares tcnative as optional https://github.com/netty/netty/blob/4.1/handler/pom.xml#L71

### Actual behavior

`io.netty.handler` has a mandatory dependency on `io.netty.internal.tcnative` -> `io.netty.internal.tcnative;version="[2.0,3)"`
[4.1.74.Final-MANIFEST.MF.txt](https://github.com/netty/netty/files/8155151/4.1.74.Final-MANIFEST.MF.txt)

### Steps to reproduce

Download both JARs and compare MANIFEST.MF files.

### Netty version

* 4.1.69.Final
* 4.1.70.Final
* 4.1.71.Final
* 4.1.72.Final
* 4.1.73.Final
* 4.1.74.Final

### JVM version (e.g. `java -version`)

It is independent of the java version: 

> openjdk version "1.8.0_302"
> OpenJDK Runtime Environment (Zulu 8.56.0.21-CA-macosx) (build 1.8.0_302-b08)
> OpenJDK 64-Bit Server VM (Zulu 8.56.0.21-CA-macosx) (build 25.302-b08, mixed mode)

### OS version (e.g. `uname -a`)

It is independent of the OS version: Darwin Kernel Version 21.3.0; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64

Is this change intended?

**Comment by normanmaurer** [comment]
Should be fixed by https://github.com/netty/netty/pull/12146

**Comment by normanmaurer** [comment]
This was merged and so fixed
