### ISSUE TITLE
`io.netty:netty-all:4.1.75.Final` declares an empty automatic module name

### ISSUE THREAD

**Issue by shs96c** [netty/netty#12175]
### Expected behavior

If the `Automatic-Module-Name` manifest property is present, it should be set to a meaningful value. This attribute is defined in the manifest for `io.netty:netty-all:4.1.75.Final`

### Actual behavior

In `io.netty:netty-all:4.1.75.Final` (and earlier versions), this is declared but not set. This causes any toolchain that attempts to use java modules to get upset.

### Steps to reproduce

```shell
jar xvf ~/Downloads/netty-all-4.1.75.Final.jar META-INF/MANIFEST.MF
head META-INF/MANIFEST.MF
```

The output is:

```
Manifest-Version: 1.0
Implementation-Title: Netty/All-in-One
Bundle-Description: Netty is an asynchronous event-driven network appl
 ication framework for    rapid development of maintainable high perfo
 rmance protocol servers and    clients.
Automatic-Module-Name: 
Bundle-License: https://www.apache.org/licenses/LICENSE-2.0
Bundle-SymbolicName: io.netty.all
Implementation-Version: 4.1.75.Final
Built-By: norman
```

The problematic thing is that `Automatic-Module-Name` is declared but not set.

### Netty version

4.1.75.Final

### JVM version (e.g. `java -version`)

9+

**Comment by shs96c** [comment]
The simple solution of just slapping in some random name (`io.netty.all`) is that this will cause the packages within this jar to be exported from more than one Java Module, and that will also cause problems.

The simple fix is to remove the attribute from the manifest entirely.

**Comment by chrisvest** [comment]
Netty-all is a pom-only dependency now, so it doesn't have any packages in the jar file. Still, it _probably_ shouldn't try to declare any automatic module name.
