### ISSUE TITLE
SslContextBuilder Error

### ISSUE THREAD

**Issue by heixiaoma** [netty/netty#12174]
java version :1.8
netty version :4.1.75.Final
system version :win10

```

//The default choice is OpenSSL. There is no problem using JDK


    private static SslProvider defaultSslProvider() {
        return OpenSsl.isAvailable() ? SslProvider.OPENSSL : SslProvider.JDK;
    }

       SslContextBuilder sslContext = SslContextBuilder.forServer(cinput, pinput, privateKeyPwd).sslProvider(defaultSslProvider());
        if (ConstConfig.openHttp2) {
            sslContext.ciphers(Http2SecurityUtil.CIPHERS, SupportedCipherSuiteFilter.INSTANCE);
            sslContext.applicationProtocolConfig(selectApplicationProtocolConfig(defaultSslProvider()));
        }

        ConstConfig.sslContext = sslContext.build();

```

```
Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/internal/tcnative/CertificateCompressionAlgo
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:473)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:606)
	at top.hserver.core.server.util.SslContextUtil.setSsl(SslContextUtil.java:115)
	at top.hserver.core.server.HServer.run(HServer.java:101)
	at top.hserver.HServerApplication.startServer(HServerApplication.java:80)
	at top.hserver.HServerApplication.run(HServerApplication.java:51)
	at com.m3u8.StartApp.main(StartApp.java:10)
Caused by: java.lang.ClassNotFoundException: io.netty.internal.tcnative.CertificateCompressionAlgo
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more
```

**Comment by normanmaurer** [comment]
Sounds like a bug...

**Comment by normanmaurer** [comment]
@heixiaoma just checked ... seems like you use an old netty-tcnative version. What version you are using ?

**Comment by normanmaurer** [comment]
@heixiaoma can you please show the full dependency tree:

```
mvn dependency:tree
```

**Comment by heixiaoma** [comment]
> @heixiaoma can you please show the full dependency tree:
> 
> ```
> mvn dependency:tree
> ```

[INFO] top.hserver:HServer:jar:2.9.82
[INFO] +- io.netty:netty-all:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-buffer:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-codec:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-codec-dns:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-codec-haproxy:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-codec-http:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-codec-http2:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-codec-memcache:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-codec-mqtt:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-codec-redis:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-codec-smtp:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-codec-socks:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-codec-stomp:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-codec-xml:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-common:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-handler:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-handler-proxy:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-resolver:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-resolver-dns:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-transport:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-transport-rxtx:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-transport-sctp:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-transport-udt:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-transport-classes-epoll:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-transport-native-unix-common:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-transport-classes-kqueue:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-resolver-dns-classes-macos:jar:4.1.75.Final:compile
[INFO] |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.75.Final:runtime
[INFO] |  +- io.netty:netty-transport-native-epoll:jar:linux-aarch_64:4.1.75.Final:runtime
[INFO] |  +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.75.Final:runtime
[INFO] |  +- io.netty:netty-transport-native-kqueue:jar:osx-aarch_64:4.1.75.Final:runtime
[INFO] |  +- io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.75.Final:runtime
[INFO] |  \- io.netty:netty-resolver-dns-native-macos:jar:osx-aarch_64:4.1.75.Final:runtime
[INFO] +- io.netty:netty-tcnative-boringssl-static:jar:2.0.41.Final:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] +- ch.qos.logback:logback-core:jar:1.2.10:compile
[INFO] +- ch.qos.logback:logback-classic:jar:1.2.10:compile
[INFO] +- ch.qos.logback:logback-access:jar:1.2.10:compile
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.12.3:compile
[INFO] +- com.fasterxml.jackson.core:jackson-annotations:jar:2.12.3:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.12.3:compile
[INFO] +- org.javassist:javassist:jar:3.28.0-GA:compile
[INFO] +- org.freemarker:freemarker:jar:2.3.31:compile
[INFO] +- com.dyuproject.protostuff:protostuff-core:jar:1.1.6:compile
[INFO] |  \- com.dyuproject.protostuff:protostuff-api:jar:1.1.6:compile
[INFO] +- com.dyuproject.protostuff:protostuff-runtime:jar:1.1.6:compile
[INFO] |  \- com.dyuproject.protostuff:protostuff-collectionschema:jar:1.1.6:compile
[INFO] +- org.objenesis:objenesis:jar:3.2:compile
[INFO] +- junit:junit:jar:4.13.2:compile
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] +- com.lmax:disruptor:jar:3.4.4:compile
[INFO] +- com.google.guava:guava:jar:30.1.1-jre:compile
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- org.checkerframework:checker-qual:jar:3.8.0:compile
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.5.1:compile
[INFO] |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] \- com.alibaba:transmittable-thread-local:jar:2.12.4:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  36.508 s
[INFO] Finished at: 2022-03-15T23:03:10+08:00
[INFO] ------------------------------------------------------------------------

**Comment by normanmaurer** [comment]
Here is your problem:

```
[INFO] +- io.netty:netty-tcnative-boringssl-static:jar:2.0.41.Final:compile
```

Use 2.0.50.Final or newer

**Comment by heixiaoma** [comment]
> Here is your problem:
> 
> ```
> [INFO] +- io.netty:netty-tcnative-boringssl-static:jar:2.0.41.Final:compile
> ```
> 
> Use 2.0.50.Final or newer

test use 2.0.51.Final  The same problem

**Comment by normanmaurer** [comment]
there must be something wrong with the dependencies... please recheck with mvn

**Comment by heixiaoma** [comment]
> there must be something wrong with the dependencies... please recheck with mvn

I've just re established a project. There's no problem with testing. It should be my dependence. Thank you for your advice
