### ISSUE TITLE
initChannel method for ChannelHandlers in Netty 5

### ISSUE THREAD

**Issue by WhiteTrashLord** [netty/netty#12199]
Please add the method initChannel for ChannelHandlers in Netty 5. The method would be used to initialize the channel.
So this can be an alternative for a ChannelInitializer. I no longer want to use ChannelInitializers because they are totally annoying.

**Comment by chrisvest** [comment]
You can use `handlerAdded`, which is what `ChannelInitializer` does.

**Comment by normanmaurer** [comment]
As @chrisvest said... lets close this for now
