### ISSUE TITLE
channel NPE with netty-all-4.1.43.final,but not with netty-all-5.0.0.Alpha2

### ISSUE THREAD

**Issue by zhangqing132155** [netty/netty#12206]
### Expected behavior
channelFuture = bootStrap.connect(ip,port);
channelFuture.addlistener(...).sync();
wait this future until it is done and excute the callback function and keep going on;
### Actual behavior
didn't wait the future done,and the callback function is not excuted,and keep going on;
then,while excuting NioSocketChannel.witeAndFlush(),throws Exception,the object channel NPE.
### Netty version
netty-all-4.1.43.final has this problem
netty-all-5.0.0.Alpha2 works well
### JVM version (e.g. `java -version`)
1.8.0_241
### OS version (e.g. `uname -a`)
windows 10

**Comment by zhangqing132155** [comment]
Anyone encountered this problem?If does ,please help to leave me the issue link or explain to me why this happened?Thanks!

**Comment by chrisvest** [comment]
Try upgrading to netty-all 4.1.75.Final.

There has been a lot of fixes since 4.1.43. Also, that `netty-all-5.0.0.Alpha2` you found is from 2015, and not related to what's currently going on for Netty 5. The new ones are prefixed with `netty5-*`.

**Comment by zhangqing132155** [comment]
> Try upgrading to netty-all 4.1.75.Final.
> 
> There has been a lot of fixes since 4.1.43. Also, that `netty-all-5.0.0.Alpha2` you found is from 2015, and not related to what's currently going on for Netty 5. The new ones are prefixed with `netty5-*`.

Thanks!Yes,the new version can solve this propblem,even `netty-all-5.0.0.Alpha2`.
But i want to know what bug it is?How it meets the problem?Any issues refer to this bug?

**Comment by normanmaurer** [comment]
Sorry but you will need to check the commit history yourself.
