### ISSUE TITLE
More useful exception logging on ReadTimeoutHandler

### ISSUE THREAD

**Issue by jonathannaguin** [netty/netty#12218]
### Expected behavior

When ReadTimeoutHandler throws a ReadTimeoutException, it would be useful if the exception message shows the timeout value.

### Actual behavior
Currently, it does not include any useful information to the user:

```
io.netty.handler.timeout.ReadTimeoutException: null
```

### Steps to reproduce
Perform a long HTTP request over the timeout.

### Netty version
4.1.72.Final

### JVM version (e.g. `java -version`)
Java 17

### OS version (e.g. `uname -a`)
Mac OS

**Comment by normanmaurer** [comment]
@jonathannaguin I think you can easily do something like this by just override `readTimedOut(...)` in `ReadTimeoutHandler`.

**Comment by jonathannaguin** [comment]
hey @normanmaurer! yeah, I realise I can always override the class, however the question is whether the default behaviour should provide more information to the user. The change is quite small and I believe I could even raise a PR if that's welcome?

**Comment by normanmaurer** [comment]
@jonathannaguin this would be a breaking change as users may expect that the same static instance is always be thrown.

**Comment by normanmaurer** [comment]
@jonathannaguin you might be surprised :)

**Comment by jonathannaguin** [comment]
@normanmaurer  Also, it does not seem there is a good way of overwriting the `ReadTimeoutHandler` to throw a better exception message. The constructors for ReadTimeoutException and TimeoutException do not offer an alternative with the message and I really don't want to extend from ChannelException (some AWS libraries expect Netty TimeoutException).

**Comment by normanmaurer** [comment]
@jonathannaguin I think we can change the protection level... Let me do a PR

**Comment by normanmaurer** [comment]
@jonathannaguin PTAL https://github.com/netty/netty/pull/12234
