### ISSUE TITLE
Low performance

### ISSUE THREAD

**Issue by andreasdc** [netty/netty#12239]
### Expected behavior
Better performance
### Actual behavior
Low performance
### Steps to reproduce
Write and flush packets.
I see REALLY big % on time spent for example from:
invokeWriteAndFlush
invokeWrite0 -> writePromiseCombiner
invokeFlush0 -> writevAddresses

### Minimal yet complete reproducer code (or URL to code)
Normal netty.
### Netty version
4.1.75 (is there a difference in performance between 5.0?)

### JVM version (e.g. `java -version`)
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)

### OS version (e.g. `uname -a`)
Linux ns31343129 4.19-ovh-xxxx-std-ipv6-64 #1818198 SMP Wed Jun 16 15:21:25 UTC 2021 x86_64 GNU/Linux

**Comment by pindumb** [comment]
This can't be fixed without a rewrite in another language.

**Comment by chrisvest** [comment]
Netty can be thought of as a system call orchestration framework - how we interact with the kernel matters more than the language.
This cant be fixed because there's not enough information in the report to investigate.

**Comment by hyperxpro** [comment]
Please elaborate more and attach profiling results.

**Comment by zhrgithub** [comment]
done


| |
zhr
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年03月28日 13:12，Aayush ***@***.***> 写道：

Please elaborate more and attach profiling results.

**Comment by andreasdc** [comment]
> Please elaborate more and attach profiling results.

On which part do I have to elaborate more? I don't want to share profilers in public as they contain sensitive data.

**Comment by hyperxpro** [comment]
Sorry then, we can't you. You might wanna close this issue now.

**Comment by andreasdc** [comment]
> Sorry then, we can't you. You might wanna close this issue now.

What do you mean?

**Comment by andreasdc** [comment]
Similar screenshot from the profiler:
![image](https://user-images.githubusercontent.com/82218780/163736363-a89ec778-b690-4e21-a007-5ada9fbf8ae0.png)

**Comment by chrisvest** [comment]
Going by that profiler screenshot, if it is to be believed, then eliminated 100% of the cost of the `write()` call, would only make the system 2.08% faster.

It is fine if you can't share the profiling results. You just have to do more of the investigation work yourself (which is appreciated regardless). I don't know what profiler you've used here. I have had success with [Async-Profiler](https://github.com/jvm-profiling-tools/async-profiler) in the past. It can directly produce flame graphs, which is a very useful visualisation for investigating performance issues.
If you can then capture your specific scenario that is slow, in a benchmark, then we can take it from there and see if it can be made faster.

**Comment by andreasdc** [comment]
> Going by that profiler screenshot, if it is to be believed, then eliminated 100% of the cost of the `write()` call, would only make the system 2.08% faster.
> 
> It is fine if you can't share the profiling results. You just have to do more of the investigation work yourself (which is appreciated regardless). I don't know what profiler you've used here. I have had success with [Async-Profiler](https://github.com/jvm-profiling-tools/async-profiler) in the past. It can directly produce flame graphs, which is a very useful visualisation for investigating performance issues. If you can then capture your specific scenario that is slow, in a benchmark, then we can take it from there and see if it can be made faster.

2% of cpu is quite a lot, when you have 100% of cpu usage, you will have 98% after correcting this part to 0%. On the profiler from today it shows 2.30%.
Another screenshot that might be useful:
![image](https://user-images.githubusercontent.com/82218780/163847800-efe2f019-7602-466f-a1e4-79307d228de0.png)
Here you have 7.5% for example:
![image](https://user-images.githubusercontent.com/82218780/163847959-537b8cb0-10d0-440b-b746-988083568b88.png)
And another 2% here:
![image](https://user-images.githubusercontent.com/82218780/163848054-3677097c-3ab1-4c26-a5d1-87c292bd6067.png)
Or 2.6% here:
![image](https://user-images.githubusercontent.com/82218780/163848139-0c3a4ccc-1f0c-4c73-a8c2-01b5365eae3a.png)
Another screenshots:
![image](https://user-images.githubusercontent.com/82218780/163848266-35366bb4-f478-42a8-a946-5820b4047528.png)
![image](https://user-images.githubusercontent.com/82218780/163848310-3fbcbb05-f4fc-40b4-b4fb-e56771fb05b2.png)

Combined it takes around 16% of cpu from this particular process.

**Comment by franz1981** [comment]
I am not quite sure the % count matches what means using 100% of cpu time (on CPU): as @chrisvest I suggest to use a better profiler that can show what happen on both kernel and JVM stack traces, given that Netty is meant to stress the I/O layer ie interacting with many system calls. async-profiler is a good one and perf map is another one.
I can help configuring async profiler command line to get her what we need to correctly weight the responsibility of Netty in the overall cost of the application.

**Comment by andreasdc** [comment]
> I am not quite sure the % count matches what means using 100% of cpu time (on CPU): as @chrisvest, I suggest as well to use a better profiler that can show what happen on both kernel and JVM stack traces, given that Netty is meant to stress the I/O layer ie interacting with the OS using system calls. async-profiler is a good one and perf map is another one. I can help configuring async profiler command line to get what we need to correctly weight the responsibility of Netty in the overall cost of the application/load test.

100% of cpu is just an example, if you have cpu usage at 100%, improving netty from 16% to 0% (hypothethically) would give you cpu usage at 86%.
I'm using Java 17 and Debian 9, if you want you can give me instructions for the commands and installation, I will give you it, if https://spark.lucko.me/ is not enough to debug that.

**Comment by franz1981** [comment]
> 2% of cpu is quite a lot, when you have 100% of cpu usage

It was looking as it was the case, sorry if I have misinterpreted it :)
Anyway, I see that profiler is using async profiler as the engine hence it should be possible extract flame graph data from it, including kernel events.
Please take a look at the documentation of the profiler you have suggested, to extract the flame graph format.

It would help to correlate the absolute importance/responsibility of Netty in whatever results you got, but as said before, even if it was 2% of all the Java samples it doesn't say anything yet about the cou time spent on it, unless using the right profiler.

**Comment by andreasdc** [comment]
![image](https://user-images.githubusercontent.com/82218780/163857332-726f3ccf-6a74-4b6b-9db9-fb780e38e9cf.png)
This is part of the flame graph. But other parts of it contains netty's calls, you see it on my screenshots.

I think percentage is proportional to the time spent.

**Comment by franz1981** [comment]
Nope, or at least is not the whole thing.

We need the full data, the duration of profiling and info about how many cores the application was using.
We need the navigable format in HTML or we won't be able to count the samples.

**Comment by andreasdc** [comment]
> Nope, or at least is not the whole thing.
> 
> We need the full data, the duration of profiling and info about how many cores the application was using. We need the navigable format in HTML or we won't be able to count the samples.

Isn't percentage of time spent and on which methods enough?

**Comment by andreasdc** [comment]
> Let's say that you have a test where a tiny fraction of cpu time is spent by the application: even if any profiler report that 50% of that (small amount of) cpu time is spent on Netty, the test won't be representative enough to conclude that worth improving the Netty side. Having the right profiler and the information I have told you before help to understand if it worth to spend time improving specific code paths found in the profiling data.

The test was running for 300 seconds
100% - 1108008.81ms
50% - 571412.58ms

**Comment by andreasdc** [comment]
Any updates?

**Comment by andreasdc** [comment]
Couple more screenshots:
1. ![image](https://user-images.githubusercontent.com/82218780/168454336-998e7590-b8d1-497b-98f1-ee657f917fe9.png)
2. ![image](https://user-images.githubusercontent.com/82218780/168454346-d17e0a07-6338-404e-883c-4cc41cce5153.png)
3. ![image](https://user-images.githubusercontent.com/82218780/168454368-16844027-fa3d-4c65-b1dd-16ea9c6fc611.png)

**Comment by andreasdc** [comment]
> Closing this as it's not very actionable.

How is it not actionable? It is related to every project based on Netty.

**Comment by chrisvest** [comment]
There's no hypothesis for how things could be faster, no specific issue identified and no goal for what is fast enough. We have to call `writev(2)` to put data on the network; if we don't recycle objects or pool buffers, we'll have to allocate more; if we don't do reference counting of buffers, we'll have memory leaks, and so on.

Meanwhile, @franz1981 has been working on identifying and fixing tangible performance issues, so there are real performance improvements in 4.1.84 compared to 4.1.75 that this issue was opened for. So give that a try, and if it's not meeting your performance goals, then try to find out what specific thing is having the biggest drag on your system.

**Comment by andreasdc** [comment]
Are you talking about https://github.com/netty/netty/pull/12806?
It needs changes for the code, correct?

**Comment by franz1981** [comment]
@andreasdc yep and not only.
It doesn't need any code change to benefit from it.
It both benefit http 1.1 users and others

**Comment by andreasdc** [comment]
I think I see improved performance, nice job! 🚀 You know when it comes to competition in gameplay, everyone has some ping to the server, every ms is important also small changes can do a lot in terms of smoothness and general speed. ❤️ Do you think it's possible to improve something more?

**Comment by franz1981** [comment]
> I think I see improved performance, nice job!

I've pushed few changes, including replacing `read` and `write` syscalls with faster ones, but TBH I've no idea re your use case

ie
- you run with many cores?
- do you have `DuplexChannelHandler`s in your pipeling?
- are you using HTTP?
- which machine you run the benchmark(s)?
- which load generator?

Happy that has worked for you anyway ;)

**Comment by andreasdc** [comment]
I use netty in Minecraft servers, fork of Spigot and fork of BungeeCord https://github.com/SpigotMC/BungeeCord.
you run with many cores?
Yes, I run with many cores.
do you have DuplexChannelHandlers in your pipeling?
I don't think so.
are you using HTTP?
I don't think so.
which machine you run the benchmark(s)?
Which profiler you mean? I use https://spark.lucko.me/
which load generator?
I don't understand.

In this Spigot's fork you can see more about how the pipeline is constructed:
https://github.com/CobbleSword/NachoSpigot/blob/master/NachoSpigot-Server/src/main/java/dev/cobblesword/nachospigot/protocol/MinecraftPipeline.java
https://github.com/CobbleSword/NachoSpigot/blob/master/NachoSpigot-Server/src/main/java/net/minecraft/server/NetworkManager.java
https://github.com/CobbleSword/NachoSpigot/search?q=netty

**Comment by andreasdc** [comment]
@franz1981 did you look into that by any chance?

**Comment by franz1981** [comment]
Please open a new issue if there is any real concern on a specific subject and not a generic moving target ie be faster.
FYI your app using duplex handlers under the hood ( see https://netty.io/4.1/api/io/netty/handler/timeout/ReadTimeoutHandler.html) hence it already benefit of the latest improvements (no idea if yet in a released version)

**Comment by andreasdc** [comment]
Do you have an idea on how to describe it?
