### ISSUE TITLE
jvm heap have a large number of  StackTraceElement objects 

### ISSUE THREAD

**Issue by iamlinhui** [netty/netty#12247]
### Expected behavior
fix this problem

### Netty version
4.1.75.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

### OS version (e.g. `uname -a`)
Windows10

![image](https://user-images.githubusercontent.com/17065583/160579724-48d92a48-fb5d-42c8-a5b8-4016ce432885.png)
![image](https://user-images.githubusercontent.com/17065583/160582593-c18394f5-43c3-4702-8d0a-aec724fe0647.png)

i find jvm heap have a large number of  StackTraceElement objects , but not throw error log, how should I position the problem?

**Comment by normanmaurer** [comment]
Please upload the heap dump somewhere so we can have a look

**Comment by iamlinhui** [comment]
[rpt.zip](https://github.com/netty/netty/files/8371082/rpt.zip)
this is heap snapshot

**Comment by chrisvest** [comment]
@iamlinhui I'm not sure what tool is used for working on .jps files. Can you create a heap dump with `jmap -dump:format=b,file=heap.hprof <pid>`, or otherwise export it in the .hprof format?

**Comment by chrisvest** [comment]
Also, to speculate, if you have paranoid leak detection turned on, that's going to capture a lot of stack traces for the lifecycle report of any leaking buffer.

**Comment by iamlinhui** [comment]
[heapdump-1648608343484.zip](https://github.com/netty/netty/files/8376715/heapdump-1648608343484.zip)
StackTraceElement[] or StackTraceElement  , i dump the hprof file

**Comment by testn** [comment]
@iamlinhui  there are just a few in your heapdump

**Comment by iamlinhui** [comment]
when i create dump file trigger  gc, so the  StackTraceElement objects is  a few in the heapdump, i find my logger pattern is `%logger{60}.%M:%line` ,i guess the cause is climbing stack, when i remove this `%M:%line` , it recovery  @testn @chrisvest thanks a lot
