### ISSUE TITLE
Netty builds 4.1 since 4.1.69.Final are broken

### ISSUE THREAD

**Issue by eshkel** [netty/netty#12259]
### Expected behavior
Expected jar file netty-all-4.1.XX.Final.jar size more than 4 Mb
### Actual behavior
jar file is about 4Kb (only service information)

### Steps to reproduce
check files on maven repo
https://repo1.maven.org/maven2/io/netty/netty-all/4.1.69.Final/netty-all-4.1.69.Final.jar
https://repo1.maven.org/maven2/io/netty/netty-all/4.1.70.Final/netty-all-4.1.70.Final.jar
https://repo1.maven.org/maven2/io/netty/netty-all/4.1.71.Final/netty-all-4.1.71.Final.jar
https://repo1.maven.org/maven2/io/netty/netty-all/4.1.72.Final/netty-all-4.1.72.Final.jar
https://repo1.maven.org/maven2/io/netty/netty-all/4.1.73.Final/netty-all-4.1.73.Final.jar
https://repo1.maven.org/maven2/io/netty/netty-all/4.1.74.Final/netty-all-4.1.74.Final.jar
https://repo1.maven.org/maven2/io/netty/netty-all/4.1.75.Final/netty-all-4.1.75.Final.jar

or
try to download link https://github.com/netty/netty/archive/refs/tags/netty-4.1.75.Final.tar.gz - Downloads menu for 4.1.XX from https://netty.io/

### Minimal yet complete reproducer code (or URL to code)
N/A
### Netty version
4.1.69 - 4.1.75
### JVM version (e.g. `java -version`)
any
### OS version (e.g. `uname -a`)
any

**Comment by normanmaurer** [comment]
@eshkel thats expected... It just depends on its modules and so will pull things in

**Comment by ipkpjersi** [comment]
What about people who want to use netty locally without an Internet connection, and thus would rely on the published jar except that jar file is now no longer usable for those people?

**Comment by chrisvest** [comment]
You can get the individual jar files in the same way you used to get the netty-all file. It's just more files now.
