### ISSUE TITLE
Cannot resolve io.netty:netty-tcnative:2.0.51.Final on Mac M1

### ISSUE THREAD

**Issue by SimoneGiusso** [netty/netty#12251]
### Expected behavior

Compile the netty project successfully

### Actual behavior

Cannot resolve io.netty:netty-tcnative:2.0.51.Final error during compilation

### Steps to reproduce

Clone the repo and compile branch 4.1

### Netty version

4.1.76

### JVM version (e.g. `java -version`)

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### OS version (e.g. `uname -a`)

Darwin ip-1.xxx.internal 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64

**Comment by chrisvest** [comment]
You have to use `-Pboringssl`, because only the boringssl variant of netty-tcnative is supported on M1 Macs: https://github.com/netty/netty-tcnative/issues/711

**Comment by normanmaurer** [comment]
@chrisvest I thought we already do this for the user:
https://github.com/netty/netty/blob/4.1/pom.xml#L393

Maybe `aarch64` is incorrect ?

**Comment by chrisvest** [comment]
Ohh… maybe?

**Comment by normanmaurer** [comment]
let me investigate
