### ISSUE TITLE
Suggested modules to open to reflections to not decrease Netty performances - JDK17+ 

### ISSUE THREAD

**Issue by nicoloboschi** [netty/netty#12265]
In Apache Pulsar and Apache BookKeeper we are switching from JDK11 to JDK17. Netty is at the core of the networking system and we want to rely on the Netty optimizations as much as possible.

We're wondering what are the recommended modules to "open" to reflection in order to enable Netty to fully execute their "hacks".
Since JDK17, there's no JVM option to allow illegal accesses so we have to know the exact jdk modules.

After looking at the code I came up only with `java.nio` for:
* java.nio.DirectByteBuffer
* Directy memory alignment

Are there other suggested modules?  
We already set `-Dio.netty.tryReflectionSetAccessible=true`

**Comment by chrisvest** [comment]
This is what we use in our builds when testing with unsafe access enabled: `-Dio.netty5.tryReflectionSetAccessible=true --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/jdk.internal.misc=ALL-UNNAMED`
