### ISSUE TITLE
Native#epollWait(FileDescriptor, EpollEventArray, FileDescriptor, int, int, long) returns different types of result

### ISSUE THREAD

**Issue by violetagg** [netty/netty#12280]
Some of Reactor Netty tests fail with the change 86004b7303621784f7ec8850323d9a707f17f9f8

I think that this is because the method below returns different types of result https://github.com/netty/netty/blob/34ae67a5b1fb1f119c1ed509f576c205d1e7fd78/transport-classes-epoll/src/main/java/io/netty/channel/epoll/Native.java#L170

This one does not require `unpack` of the result
https://github.com/netty/netty/blob/34ae67a5b1fb1f119c1ed509f576c205d1e7fd78/transport-classes-epoll/src/main/java/io/netty/channel/epoll/Native.java#L174

While this one requires  `unpack` of the result
https://github.com/netty/netty/blob/34ae67a5b1fb1f119c1ed509f576c205d1e7fd78/transport-classes-epoll/src/main/java/io/netty/channel/epoll/Native.java#L181

This method is used in the code below where it always performs `unpack` and this leads to the problems that I observe  https://github.com/netty/netty/blob/34ae67a5b1fb1f119c1ed509f576c205d1e7fd78/transport-classes-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java#L354-L357

### Expected behavior
Native#epollWait(FileDescriptor, EpollEventArray, FileDescriptor, int, int, long) returns same types of result

### Actual behavior
Native#epollWait(FileDescriptor, EpollEventArray, FileDescriptor, int, int, long) returns different types of result

### Steps to reproduce
Unfortunately I'm unable to extract an example with vanilla Netty

### Netty version
v4.1.76.Final-SNAPSHOT

### JVM version (e.g. `java -version`)
Distribution: temurin
Version: 8.0.322+6

### OS version (e.g. `uname -a`)
Ubuntu 20.04

**Comment by normanmaurer** [comment]
@violetagg want to provide a PR?

**Comment by violetagg** [comment]
@normanmaurer I'm not sure for the proper place to address this :(

**Comment by normanmaurer** [comment]
ok will have a look later today

**Comment by normanmaurer** [comment]
@violetagg PTAL https://github.com/netty/netty/pull/12283
