### ISSUE TITLE
Netty TCP server doesnot accept much load

### ISSUE THREAD

**Issue by Patricia144** [netty/netty#12298]
I am performing benchmarking of single Netty TCP server with following configurations, but at max Netty can process 110 messages/second. Even if more loads (i.e. 2000 users at a time back to back at a period of 1 hour) are ingested through Jmeter , but Netty TCP server can't go beyond 110 messages/sec boundary.

Memory remain within 20%. 
CPU usage falls between 70-90 %

Even though sufficient memory and cpu cycles are available ,but messages per second doesn't go beyond 110 messages/sec.

**Server Hardware Configuration:**
CPU: 4 Core
RAM: 16 GB
OS: Windows

**Netty TCP Server Configuration:**

 ServerBootstrap b = new ServerBootstrap();
       EventLoopGroup group = new NioEventLoopGroup();
        b.group(group)
                .channel(NioServerSocketChannel.class)
                .handler(new LoggingHandler(LogLevel.DEBUG))
                .childHandler(serverChannelInitializer);
        b.option(ChannelOption.TCP_NODELAY,true);

**Note**: I am not using boss , worker threads and backlog parameter in netty server. Please suggest if any additional configuration in netty server will improves messages/sec.
Netty Version: **4.1.45.Final**

Request your input to increase the message load capacity of netty tcp server.

**Comment by hyperxpro** [comment]
The single thread won't take you so far. Increase the EventLoop count.

**Comment by Patricia144** [comment]
> The single thread won't take you so far. Increase the EventLoop count.
Thanks for quick reply. You mean to increase the Boss and Worker thread count  during server bootstrap ? If yes, what the formula to determine the size of boss, worker thread ? Do we need to increase netty backlog as well ?

Please review below configuration..

         ServerBootstrap b = new ServerBootstrap();
         NioEventLoopGroup bossEventLoopGroup =       new NioEventLoopGroup(32, Executors.defaultThreadFactory());
        NioEventLoopGroup workerGroup  =                    new NioEventLoopGroup(2000, Executors.defaultThreadFactory());
        b.group(bossEventLoopGroup,workerGroup)
                .channel(NioServerSocketChannel.class)
                .handler(new LoggingHandler(LogLevel.DEBUG))
                .childHandler(serverChannelInitializer);
        b.option(ChannelOption.SO_BACKLOG, 500);
        b.option(ChannelOption.TCP_NODELAY,true);

**Comment by hyperxpro** [comment]
Try this:
```java
EventLoopGroup boss = new NioEventLoopGroup(Runtime.getRuntime().availableProcessors());
EventLoopGroup child = new NioEventLoopGroup(Runtime.getRuntime().availableProcessors() * 2);
```

Set `SO_BACKLOG` to `100_000`

**Comment by Patricia144** [comment]
Above configuration has been used , but load ratio hasn't been increased, its remains same as before.
Memory utilization is around 20% and CPU utilization falls arounf 70%.

**Comment by Patricia144** [comment]
@Aayush, request your update.

**Comment by hyperxpro** [comment]
Also, remove LoggingHandler.

**Comment by Patricia144** [comment]
> Are you performing heavy workload on Handler?

In handler , I am communicating with kafka and redis with few business logic.  In those section , message execution is very fast and completing within few milisec. The core issue is server is not accepting much inbound tcp connection. 

Again, another observation, If above hardware configuration (single machine having 4 core cpu and 16 GB RAM)  is  distributed to  4 different machine each having (1 core CPU and 4 GB RAM), then messages per seconds increases substantially.

**Comment by slandelle** [comment]
Have you properly tuned the TCP stack on your kernel (ulimit, IO buffers, etc)?

**Comment by franz1981** [comment]
> In handler , I am communicating with kafka and redis with few business logic

If it will use the existing Kafka client it means it can block due to metadata or buffer pool exhausting.
Is it using any reactive libraries to communicate with Kafka?

**Comment by Patricia144** [comment]
> Have you properly tuned the TCP stack on your kernel (ulimit, IO buffers, etc)?

Thank you for the suggestion. ulimit  shows **unlimited** in my underlying linux machine.  Is there any specific value to be set for ulimit and IO buffers ? Request you to specify.

**Comment by Patricia144** [comment]
> > In handler , I am communicating with kafka and redis with few business logic
> 
> If it will use the existing Kafka client it means it can block due to metadata or buffer pool exhausting. Is it using any reactive libraries to communicate with Kafka?

Reactive kafka stack is **not** being used right now. But with existing non react kafka, there is milisec latency with our existing kafka and it's fast.

**Comment by franz1981** [comment]
Sorry to be picky on this, but quick math:
If Kafka client takes 10 ms, how many req/sec can be executed in 1 second?
100 req/sec
Hence, 10 ms is too much time... that's why I have asked about it

**Comment by Patricia144** [comment]
> Sorry to be picky on this, but quick math: If Kafka client takes 10 ms, how many req/sec can be executed in 1 second? 100 req/sec Hence, 10 ms is too much time (and 1 ms too!)... that's why I have asked about it. If it's executed for each incoming packet, it can become the bottleneck.
> 
> Try removing Kafka or redis from the handler and we can think/measure about what Netty can deliver..right now this doesn't look like a Netty issue.

Thanks @franz1981. I will test it by disabling kafka and redis .

**Comment by Patricia144** [comment]
> > In handler , I am communicating with kafka and redis with few business logic.
> 
> As others have hinted at, you should not do anything blocking in a handler, because handler logic is executed in the event loop thread. You can instead have a separate thread-pool where you execute these Kafka and redis interactions - off-loading the work, essentially. You can grab the `ChannelHandlerContext` object in your off-load tasks, and call back into Netty from your thread-pool threads, to continue processing your pipeline in Netty. That way, the event-loop can do network IO in parallel with your Kafka and redis work.

Thanks @chrisvest . Instead of separate threadpool, reactor kafka and redis will help ?

**Comment by franz1981** [comment]
*Reactive* versions of such libraries (@cescoffier can detail it better then me, @violetagg as well) still likely use some thread pool to handle blocking due to the wrapped client's nature.
There is no existing driver AFAIK that's natural born non-blocking without using additional thread pool.

**Comment by Patricia144** [comment]
Apologize for late response. Thanks @franz1981 and @chrisvest . Wrapping into thread pool (i.e. Spring @async) , we got improved performance. 
We can close the ticket.

**Comment by Flenzy** [comment]
@Patricia144 we also face a similar issue can help us solve the same using spring async
