### ISSUE TITLE
Allow for pluggable algorithm to choose next EventLoop

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#1230]
At the moment we just choose the next EventLoop based on some modulo operation. This may be not optimal for some reasons as there may be one EventLoop which is more busy as the other. Optimal we would allow to plugin the agorithm.

**Comment by danhyun** [comment]
Hello, I'm trying to find the status of this work but last I see it seems that @buchgr is no longer legally allowed to continue work on this effort. Is this something that's still planned for release?

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5279
