### ISSUE TITLE
Netty version upgrade

### ISSUE THREAD

**Issue by FengYue99** [netty/netty#12325]
Hello, I'm upgrading netty version from 4.1.68 to 4.1.76 and have encountered many problems with classes under netty-all that don't exist, such as io.netty.util.concurrent.EventLoopGroup, io.netty.util.concurrent. GenericFutureListener
How can I solve it? Thank you!

**Comment by chrisvest** [comment]
Make sure you're pulling in transitive dependencies. If you are, it could be your download got messed up, so maybe clear your local maven cache and try again.

**Comment by FengYue99** [comment]
I'm using gradle and the local cache has been cleared, but I still get the above problem

**Comment by normanmaurer** [comment]
This is a gradle issue... Please get support there.
