### ISSUE TITLE
[question] [netty-all (4) 4.1.75.Final] [How to bind all ipv4 addresses of a computer]

### ISSUE THREAD

**Issue by freedom1b2830** [netty/netty#12329]
How to bind all ipv4 addresses of a computer without using jvm argument
needed ```0.0.0.0:8470``` for first app (example)
needed ```0.0.0.0:1024``` for second app (example)

### Actual behavior
binded only ```ipv6``` address ```lo```

### Steps to reproduce
run 1 app,wait (binded to ipv6)
run 2 (binded to ipv6)

### Minimal yet complete reproducer code (or URL to code)
code: https://pastebin.com/tmfRHwK6

log apps,netstat ,ncat(nmap proj)
https://pastebin.com/2X3BJzhm

### Netty version
netty-all (4) 4.1.75.Final

### JVM version (e.g. `java -version`)
17,18
openjdk version "18.0.1" 2022-04-19
OpenJDK Runtime Environment (build 18.0.1+10)
OpenJDK 64-Bit Server VM (build 18.0.1+10, mixed mode)

### OS version (e.g. `uname -a`)
Linux archlinux 5.17.3-arch1-1 #1 SMP PREEMPT Thu, 14 Apr 2022 01:18:36 +0000 x86_64 GNU/Linux

**Comment by freedom1b2830** [comment]
```-Djava.net.preferIPv4Stack=true``` works but how to do it for netty ```from code```

**Comment by hyperxpro** [comment]
Set system property in code.

**Comment by hyperxpro** [comment]
```java
    static {
        System.setProperty("java.net.preferIPv4Stack", "true");
    }
```

**Comment by freedom1b2830** [comment]
Is there a switch between families in netty itself?

**Comment by hyperxpro** [comment]
https://netty.io/4.1/api/io/netty/channel/epoll/EpollServerSocketChannel.html#EpollServerSocketChannel-io.netty.channel.socket.InternetProtocolFamily-
