### ISSUE TITLE
Netty HTTP access log

### ISSUE THREAD

**Issue by GlebIgnatevEmlid** [netty/netty#12327]
Hello everyone!

I'm developing a Ktor application with embedded Netty server, and I was wondering is there a way to get Netty's HTTP access log like the one for [Jetty](https://docs.huihoo.com/jetty/the-definitive-reference/configuring-jetty-request-logs.html)? At the moment I'm trying to set up JSON logging, and it's easy with Logback + Jetty as there's a proper integration, but I'm not sure if I should switch a web server for this. I've seen that Reactor Netty provides [`AccessLog`](https://projectreactor.io/docs/netty/1.0.9/api/index.html?reactor/netty/http/server/logging/AccessLog.html) and even though there's no integration with Logback access, I could use it with classic in theory, but I couldn't find anything related to the access log in Netty docs. If there's anything that I've missed, please, let me know. Thanks!

**Comment by hyperxpro** [comment]
It does not exist as of now. Interested in doing a PR?

**Comment by normanmaurer** [comment]
Closing now... This is not an issue

**Comment by GlebIgnatevEmlid** [comment]
> It does not exist as of now. Interested in doing a PR?

@hyperxpro Thanks for the response, I just wanted to make sure.
