### ISSUE TITLE
StacklessChannelClosedException while calling bootstrap.connect

### ISSUE THREAD

**Issue by krshvik** [netty/netty#12339]
We have a Netty Client talking to a Tomcat Server. We establish a new connection to Tomcat server for streaming requests/responses. We also re-use the connection for subsequent requests if its still within the KeepAliveIdleTimeout range. We have a scenario where the previous connection to the server drops on hitting the KeepAliveIdleTimeout and when trying to establish a new connection with the server, Netty throws StacklessClosedChannel Exception. 

Failed to connect to Tomcat 
io.netty.channel.StacklessClosedChannelException: null |      at 
io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(ChannelPromise)(Unknown Source) ~[netty-all-4.1.jar:4.1.68.Final] |   
                                                         
We see the log.error(ctx, "Failed to connect to Tomcat", future.cause()); report the exception with the above stack trace. In the below piece of code, we see a new channelId created from connectFuture.channel(); . However, the connetFuture eventually fails and reports the StacklessClosedChannel Exception. It almost feels like the bootstrap.connect call is still referencing the old closed channel some reason. We are not sure as to how and where this reference is being stored in Netty code base. 

### Minimal yet complete reproducer code (or URL to code)

```
// snippet of code with Bootstrap initialization logic
private void initChannel(SocketChannel ch) {

        Bootstrap bootstrap = *new* ** Bootstrap();
        bootstrap.group(ch.eventLoop())
                .channel(ch.getClass())
                .handler(handler_1 ....
                .....
                .....
                        handler_n))
                .option(ChannelOption.*SO_REUSEADDR**,** **true**)*
*                **.**option**(**ChannelOption**.**SO_RCVBUF**,** some_size**)*
*                **.**option**(**ChannelOption**.**SO_SNDBUF**,** some_size**)*
*                **.**option**(**ChannelOption**.**AUTO_READ**,** **true**)*
*                **.**option**(**ChannelOption**.**CONNECT_TIMEOUT_MILLIS**,**some_time_out**)*;

}

public class TomcatProxyHanlder {

// Bootstrap object is created once (as stated above) and used for 
// creating all channels in this handler.
private Bootstrap bootstrap;

// Code that invokes the new channel creation logic on seeing the very first request or 
// on seeing a new request with previous connection dropped. 
@Override
public void channelRead(ChannelHandlerContext ctx, Object msg) {
        if (msg instanceof HttpRequest) {
            if (isFirstMessage() || isSubsequentRequestAndPreviousConnectionClosed()) {
                connectToTomcat(ctx, msg);
            }
}

// snippet of code to connect to Tomcat using a bootstrap object 
private void connectToTomcat(ChannelHandlerContext ctx, Object msg){        

        SocketAddress endpoint = downstreamEndpointMapper.getDestForChannel(upstream);
        connectFuture = bootstrap.connect(endpoint);
        downstream = connectFuture.channel();

        connectFuture.addListener((ChannelFutureListener) future -> {
            if (future.isSuccess()) {              log.debug(ctx, "Successfully connected to tomcat");
            } else {
                    log.error(ctx, "Failed to connect to Tomcat", future.cause());
                    ctx.fireExceptionCaught(new ServiceUnavailableError(future.cause()));
            }
        });
}

}
```

### Netty version

4.1.68.Final

### JVM version (e.g. `java -version`)

Java 11

### OS version (e.g. `uname -a`)

x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
Please share full code... This looks incomplete.
