### ISSUE TITLE
Direct Buffer not cleaned / released after updating to > v4.1.74

### ISSUE THREAD

**Issue by mgmeiner** [netty/netty#12333]
First of all: I'm not sure if this is 100% the right place for this Issue as Reactor-Netty and Spring-Webflux are also involved.

After updating our Spring-Webflux app to 2.6.6 we encountered "java.lang.OutOfMemoryError Direct buffer memory" exceptions in our logs. After some investigation I found out that netty update to 4.1.75/4.1.76 is the problem and in particular the ['Reduce the default PooledByteBufAllocator chunk size from 16 MiB to 4 MiB'](https://github.com/netty/netty/pull/12108) change. 
When I change the 'io.netty.allocator.maxOrder' setting back to 11 it works fine but for 9 it seems that the direct buffer is never released. 
We also tried to increase the `XX:MaxDirectMemorySize` setting but that just delays the 'overflow'.

I also debugged Webflux and release on the ByteBuf is always called. 

I mean it works by setting the maxOrder setting back to 11 but i want to understand why this happens or if this is an actual bug.

### Some background of the use case: 
This happens when we 'stream' (application/stream+json) a lot of of pretty large json (~80KB per json) to the client. 

### Minimal yet complete reproducer code (or URL to code)
I tried to create a small project just with just netty but could not reproduce it. 
If you want i can create a small spring-webflux project that reproduces the issue.

### Netty version
4.1.75 & 4.1.76

### JVM version (e.g. `java -version`)
17

### JVM Settings
-XX:MaxDirectMemorySize=80M 
-Xmx512m 

No netty settings have been tweaked.

**Comment by chrisvest** [comment]
Enable leak detection to see if there's a buffer that isn't being released. It's not clear why the chunk size change would influence this. Only thing I can think of is that perhaps a large - greater than 4 MiB - buffer is allocated, which will now be unpooled where it was previously pooled. Unpooled buffers, depending on what hacks are available (since you're using Java 17) might be relying on the GC in order to free the actual native memory.

**Comment by mgmeiner** [comment]
I forgot to mention: mongodb reactive streams driver is also involved

I tested this on Java 11 and it seems that the buffer gets freed again 

When leak detection is set to _paranoid_ i get following error log: [leak-log.txt](https://github.com/netty/netty/files/8554589/leak-log.txt)
 
Do you want me create an example application? I know its hard to guess from only this information as many things are involved.

**Comment by chrisvest** [comment]
@mgmeiner Your leak report says:

```
Created at:
	…
	io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:116)
	org.springframework.core.io.buffer.NettyDataBufferFactory.allocateBuffer(NettyDataBufferFactory.java:71)
	org.springframework.core.io.buffer.NettyDataBufferFactory.allocateBuffer(NettyDataBufferFactory.java:39)
	org.springframework.http.codec.json.AbstractJackson2Encoder.encodeStreamingValue(AbstractJackson2Encoder.java:284)
	org.springframework.http.codec.json.AbstractJackson2Encoder.lambda$encode$1(AbstractJackson2Encoder.java:168)
```

And the recent accesses to that buffer are also from the `AbstractJackson2Encoder` class, so you need to bring this issue up with the people maintaining that class.

**Comment by normanmaurer** [comment]
Like @chrisvest said... This seems to be not a netty issue.
