### ISSUE TITLE
CorruptedFrameException: data frame using reserved opcode 7

### ISSUE THREAD

**Issue by ppb1984** [netty/netty#12347]
### Expected behavior

Web socket connect and run 

### Actual behavior

I am able to handshake and connect but also getting below error every time, what could be the reason of it - 

```
io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.CorruptedFrameException: data frame using reserved opcode 7
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:412)
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:229)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)

```

How can I avoid this exception? Is there a way to catch and log this exception.

### Netty version

4.1.50.Final

### JVM version (e.g. `java -version`)

Java 8

**Comment by hyperxpro** [comment]
Please use the latest version of Netty (4.1.76.Final) as well as WebSocket (13).

**Comment by ppb1984** [comment]
Hi @hyperxpro, thank you for your suggestion, I tried the version, Netty (4.1.76.Final) but still facing the same error. By using this version I am not able to connect to websocket or I don't see handshaking happening. 

Do I need to change any other dependency?

**Comment by hyperxpro** [comment]
Can you capture packets with PcapHandler?

**Comment by ppb1984** [comment]
I tired capturing packets with wireshark, above error happens when TCP RST (resetting) packets comes in. I believe this exception happening at the time of my `IdleStateHandler` inside my handler's has overridden method channelRead()

Is there any way to handle this exception and log or check if the frame is not in correct format and ignore it.

**Comment by ppb1984** [comment]
Hello @hyperxpro , I found the issue it is because of the jar conflict. We were using some third party jar which also having the Netty jars which causes this issue. This is a old code so miss that change.
Thank you for your advice and help.

**Comment by abbasvalliani** [comment]
That is not the case. WebSocket08FrameDecoder has the following offending code:

         if (!(frameOpcode == OPCODE_CONT || frameOpcode == OPCODE_TEXT
                      || frameOpcode == OPCODE_BINARY)) {
                    protocolViolation(ctx, in, "data frame using reserved opcode " + frameOpcode);
                    return;
                }

If there is an opCode of 7 (which is unassigned based on the registry), this will result in an error. Based on the RFC, the opCode is unassigned but that doesn't mean we need to throw a protocol exception. A live example:

edge-chat.facebook.com using opCode 7. Therefore, you can't proxy websockets! 

I think this should be fixed and prioritized. Otherwise, we'll all have our own version of the decoder!
