### ISSUE TITLE
mvn compile netty-resolver-dns-native-macos failed hint: unpack-dependencies 

### ISSUE THREAD

**Issue by WuYHH** [netty/netty#12389]
### Expected behavior
SUCCESS
### Actual behavior
Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack-dependencies (unpack) on project netty-resolver-dns-native-macos: Artifact has not been packaged yet. When used on reactor artifact, unpack should be executed after packaging: see MDEP-98. -> [Help 1]
### Steps to reproduce
mvn clean compile from root
### Netty version
netty 4.1.78
### JVM version (e.g. `java -version`)
jdk 12.0.2
### OS version (e.g. `uname -a`)
macos monterey 12.3.1

**Comment by WuYHH** [comment]
[INFO] Reactor Summary for Netty 4.1.78.Final-SNAPSHOT:
[INFO] 
[INFO] Netty/Dev-Tools .................................... SUCCESS [  0.964 s]
[INFO] Netty .............................................. SUCCESS [  5.034 s]
[INFO] Netty/Common ....................................... SUCCESS [  6.752 s]
[INFO] Netty/Buffer ....................................... SUCCESS [  4.922 s]
[INFO] Netty/Resolver ..................................... SUCCESS [  1.286 s]
[INFO] Netty/Transport .................................... SUCCESS [  4.550 s]
[INFO] Netty/Codec ........................................ SUCCESS [  4.259 s]
[INFO] Netty/Codec/DNS .................................... SUCCESS [  2.011 s]
[INFO] Netty/Codec/HAProxy ................................ SUCCESS [  1.679 s]
[INFO] Netty/Handler ...................................... SUCCESS [  5.839 s]
[INFO] Netty/Codec/HTTP ................................... SUCCESS [  6.312 s]
[INFO] Netty/Codec/HTTP2 .................................. SUCCESS [  6.343 s]
[INFO] Netty/Codec/Memcache ............................... SUCCESS [  1.386 s]
[INFO] Netty/Codec/MQTT ................................... SUCCESS [  1.691 s]
[INFO] Netty/Codec/Redis .................................. SUCCESS [  1.344 s]
[INFO] Netty/Codec/SMTP ................................... SUCCESS [  1.133 s]
[INFO] Netty/Codec/Socks .................................. SUCCESS [  1.702 s]
[INFO] Netty/Codec/Stomp .................................. SUCCESS [  1.263 s]
[INFO] Netty/Codec/XML .................................... SUCCESS [  1.262 s]
[INFO] Netty/Handler/Proxy ................................ SUCCESS [  1.276 s]
[INFO] Netty/Resolver/DNS ................................. SUCCESS [  2.603 s]
[INFO] Netty/Transport/RXTX ............................... SUCCESS [  1.111 s]
[INFO] Netty/Transport/SCTP ............................... SUCCESS [  1.372 s]
[INFO] Netty/Transport/UDT ................................ SUCCESS [  1.465 s]
[INFO] Netty/Transport/Native/Unix/Common ................. SUCCESS [  2.370 s]
[INFO] Netty/Transport/Classes/Epoll ...................... SUCCESS [  1.920 s]
[INFO] Netty/Transport/Classes/KQueue ..................... SUCCESS [  1.841 s]
[INFO] Netty/Resolver/DNS/Classes/MacOS ................... SUCCESS [  1.271 s]
[INFO] Netty/All-in-One ................................... SUCCESS [  1.251 s]
[INFO] Netty/Resolver/DNS/Native/MacOS .................... FAILURE [  0.290 s]
[INFO] Netty/Transport/Native/Unix/Common/Tests ........... SKIPPED
[INFO] Netty/Testsuite .................................... SKIPPED
[INFO] Netty/Transport/Native/Epoll ....................... SKIPPED
[INFO] Netty/Transport/Native/KQueue ...................... SKIPPED
[INFO] Netty/Example ...................................... SKIPPED
[INFO] Netty/Testsuite/Autobahn ........................... SKIPPED
[INFO] Netty/Testsuite/Http2 .............................. SKIPPED
[INFO] Netty/Testsuite/OSGI ............................... SKIPPED
[INFO] Netty/Testsuite/Shading ............................ SKIPPED
[INFO] Netty/Testsuite/Native ............................. SKIPPED
[INFO] Netty/Testsuite/NativeImage ........................ SKIPPED
[INFO] Netty/Testsuite/NativeImage/Client ................. SKIPPED
[INFO] Netty/Testsuite/NativeImage/ClientRuntimeInit ...... SKIPPED
[INFO] Netty/Transport/BlockHound/Tests ................... SKIPPED
[INFO] Netty/Microbench ................................... SKIPPED
[INFO] Netty/BOM .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:17 min
[INFO] Finished at: 2022-05-12T10:01:05+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack-dependencies (unpack) on project netty-resolver-dns-native-macos: Artifact has not been packaged yet. When used on reactor artifact, unpack should be executed after packaging: see MDEP-98. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :netty-resolver-dns-native-macos

**Comment by WuYHH** [comment]
add some information below:

[INFO] 
[INFO] --- maven-hawtjni-plugin:1.14:build (build-native-lib) @ netty-resolver-dns-native-macos ---
[INFO] executing: /bin/sh -c ./configure --disable-ccache --prefix=/Users/wuyuhan/IdeaProjects/netty-996/resolver-dns-native-macos/target/native-build/target 'LDFLAGS=-Wl,-weak_library,/Users/wuyuhan/IdeaProjects/netty-996/resolver-dns-native-macos/target/unix-common-lib/META-INF/native/lib/libnetty-unix-common.a -Wl,-platform_version,macos,10.6,10.6' 'CFLAGS=-O3 -Werror -fno-omit-frame-pointer -Wunused-variable -fvisibility=hidden -I/Users/wuyuhan/IdeaProjects/netty-996/resolver-dns-native-macos/target/unix-common-lib/META-INF/native/include' MACOSX_DEPLOYMENT_TARGET=10.6
[INFO] configure: WARNING: unrecognized options: --disable-ccache
[INFO] checking build system type... x86_64-apple-darwin21.4.0
[INFO] checking host system type... x86_64-apple-darwin21.4.0
[INFO] checking target system type... x86_64-apple-darwin21.4.0
[INFO] checking for gcc... gcc
[INFO] checking whether the C compiler works... yes
[INFO] checking for C compiler default output file name... a.out
[INFO] checking for suffix of executables... 
[INFO] checking whether we are cross compiling... no
[INFO] checking for suffix of object files... o
[INFO] checking whether the compiler supports GNU C... yes
[INFO] checking whether gcc accepts -g... yes
[INFO] checking for gcc option to enable C11 features... none needed
[INFO] checking whether gcc understands -c and -o together... yes
[INFO] checking for a BSD-compatible install... /usr/bin/install -c
[INFO] checking for ar... ar
[INFO] checking the archiver (ar) interface... ar
[INFO] checking how to print strings... printf
[INFO] checking for a sed that does not truncate output... /usr/bin/sed
[INFO] checking for grep that handles long lines and -e... /usr/bin/grep
[INFO] checking for egrep... /usr/bin/grep -E
[INFO] checking for fgrep... /usr/bin/grep -F
[INFO] checking for ld used by gcc... /Library/Developer/CommandLineTools/usr/bin/ld
[INFO] checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
[INFO] checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
[INFO] checking the name lister (/usr/bin/nm -B) interface... BSD nm
[INFO] checking whether ln -s works... yes
[INFO] checking the maximum length of command line arguments... 786432
[INFO] checking how to convert x86_64-apple-darwin21.4.0 file names to x86_64-apple-darwin21.4.0 format... func_convert_file_noop
[INFO] checking how to convert x86_64-apple-darwin21.4.0 file names to toolchain format... func_convert_file_noop
[INFO] checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
[INFO] checking for objdump... objdump
[INFO] checking how to recognize dependent libraries... pass_all
[INFO] checking for dlltool... no
[INFO] checking how to associate runtime and link libraries... printf %s\n
[INFO] checking for archiver @FILE support... no
[INFO] checking for strip... strip
[INFO] checking for ranlib... ranlib
[INFO] checking for gawk... no
[INFO] checking for mawk... no
[INFO] checking for nawk... no
[INFO] checking for awk... awk
[INFO] checking command to parse /usr/bin/nm -B output from gcc object... ok
[INFO] checking for sysroot... no
[INFO] checking for a working dd... /bin/dd
[INFO] checking how to truncate binary pipes... /bin/dd bs=4096 count=1
[INFO] checking for mt... no
[INFO] checking if : is a manifest tool... no
[INFO] checking for dsymutil... dsymutil
[INFO] checking for nmedit... nmedit
[INFO] checking for lipo... lipo
[INFO] checking for otool... otool
[INFO] checking for otool64... no
[INFO] checking for -single_module linker flag... yes
[INFO] checking for -exported_symbols_list linker flag... yes
[INFO] checking for -force_load linker flag... yes
[INFO] checking for stdio.h... yes
[INFO] checking for stdlib.h... yes
[INFO] checking for string.h... yes
[INFO] checking for inttypes.h... yes
[INFO] checking for stdint.h... yes
[INFO] checking for strings.h... yes
[INFO] checking for sys/stat.h... yes
[INFO] checking for sys/types.h... yes
[INFO] checking for unistd.h... yes
[INFO] checking for dlfcn.h... yes
[INFO] checking for objdir... .libs
[INFO] checking if gcc supports -fno-rtti -fno-exceptions... yes
[INFO] checking for gcc option to produce PIC... -fno-common -DPIC
[INFO] checking if gcc PIC flag -fno-common -DPIC works... yes
[INFO] checking if gcc static flag -static works... no
[INFO] checking if gcc supports -c -o file.o... yes
[INFO] checking if gcc supports -c -o file.o... (cached) yes
[INFO] checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
[INFO] checking dynamic linker characteristics... darwin21.4.0 dyld
[INFO] checking how to hardcode library paths into programs... immediate
[INFO] checking whether stripping libraries is possible... yes
[INFO] checking if libtool supports shared libraries... yes
[INFO] checking whether to build shared libraries... yes
[INFO] checking whether to build static libraries... no
[INFO] configure: javac was on your path, checking to see if it's part of a JDK we can use...
[INFO] checking if '/usr' is a JDK... no
[INFO] configure: Taking a guess as to where your OS installs the JDK by default...
[INFO] checking if '/System/Library/Frameworks/JavaVM.framework' is a JDK... no
[INFO] configure: error: JDK not found. Please use the --with-jni-jdk option
[INFO] rc: 1

**Comment by chrisvest** [comment]
Try `mvn clean package` instead.

**Comment by chrisvest** [comment]
The native compilation that require shared sources between platforms, need the packaging step.

**Comment by WuYHH** [comment]
> Try `mvn clean package` instead.

Thank you. I have try it, but I have still this problem.

**Comment by WuYHH** [comment]
> The native compilation that require shared sources between platforms, need the packaging step.


> > Try `mvn clean package` instead.
> 
> Thank you. I have try it, but I have still this problem.

Is it a problem with my jdk version?

**Comment by WuYHH** [comment]
> Try `mvn clean package` instead.

Thank you. I have fixed this problem. but new problem in "netty-resolver-dns-native-macos" module happened. The error info is below:
the netty-parent is :

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.14:build (build-native-lib) on project netty-resolver-dns-native-macos: build failed: org.apache.maven.plugin.MojoExecutionException: ./configure failed with exit code: 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :netty-resolver-dns-native-macos

The netty-reslover-dns-native-macos is belows:
[INFO] checking whether stripping libraries is possible... yes
[INFO] checking if libtool supports shared libraries... yes
[INFO] checking whether to build shared libraries... yes
[INFO] checking whether to build static libraries... no
[INFO] configure: javac was on your path, checking to see if it's part of a JDK we can use...
[INFO] checking if '/usr' is a JDK... no
[INFO] configure: Taking a guess as to where your OS installs the JDK by default...
[INFO] checking if '/System/Library/Frameworks/JavaVM.framework' is a JDK... no
[INFO] configure: error: JDK not found. Please use the --with-jni-jdk option
[INFO] rc: 1

**Comment by chrisvest** [comment]
```
[INFO] checking if '/System/Library/Frameworks/JavaVM.framework' is a JDK... no
[INFO] configure: error: JDK not found. Please use the --with-jni-jdk option
```

You need to use a JDK for building.
