### ISSUE TITLE
`PooledByteBuf.readBytes` allocates released buffer instead of a writeable one

### ISSUE THREAD

**Issue by derklaro** [netty/netty#12387]
### Expected behavior
ByteBuf.readBytes should not throw an exception because the buffer allocated within the method is already released.

### Actual behavior
`readBytes` when using a PooledByteBufAllocator sometimes (rarely) throws an exception because the buffer allocated inside the method is already released:
```
io.netty.util.IllegalReferenceCountException: refCnt: 0
  at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1454)
  at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:289)
  at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:280)
  at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1103)
  at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:872)
  at eu.cloudnetservice.driver.network.netty.codec.NettyPacketDecoder.decode(NettyPacketDecoder.java:68)
```

The method `newDirectBuffer` in PooledByteBufAllocator seems to have a directArea available and allocates a buffer from it (was able to catch it once using a debugger). The buffer returned from that is already released.

### Steps to reproduce
As suggested by @chrisvest : "You can try setting io.netty.allocator.smallCacheSize, io.netty.allocator.normalCacheSize, and io.netty.allocator.maxCachedBufferCapacity to 0."

Then make sure netty is using the PooledByteBufAllocator (for me directByDefault is true) and just try to read bytes of a spcifc length from an incoming buffer (`ByteBuf#readBytes(int): ByteBuf`)

Sometimes the method will raise an IllegalReferenceCountException when trying to copy the bytes from one buffer to the other.

### Minimal yet complete reproducer code (or URL to code)
```java
int length = in.readInt();
ByteBuf body = in.readBytes(length);
```

### Netty version
4.1.77.Final

### JVM version (e.g. `java -version`)
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment (build 17.0.3+7-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 17.0.3+7-Debian-1deb11u1, mixed mode, sharing)

### OS version (e.g. `uname -a`)
Linux 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux

**Comment by chrisvest** [comment]
So disabling the thread-local cache increases the likelihood of this happening?

**Comment by derklaro** [comment]
Setting the system properties you send me (I mentioned them above) increases the likeliness by a lot

**Comment by normanmaurer** [comment]
interesting.. @chrisvest you are investigating ?

**Comment by chrisvest** [comment]
@normanmaurer Haven't started looking at it

**Comment by chrisvest** [comment]
It's not the `readBytes` that's the problem, but that the pooled allocator returns a buffer that's already been released.
What pattern of sizes are you using? I'm trying to create a sequence of allocations that recreates the problem.

**Comment by derklaro** [comment]
Should be around 100 - 150. Maybe it is also noteworthy that there are multiple indepent applications running which are all allocating buffers at the same time (the receive the same message around the same time)

**Comment by abstract-liu** [comment]
Wonder if there is any conclusion? Met with similar problem...

**Comment by franz1981** [comment]
> Met with similar problem...
@abstract-liu with the latest netty version?

**Comment by abstract-liu** [comment]
No, 4.1.76.Final

**Comment by franz1981** [comment]
Try the latest please @abstract-liu

**Comment by chrisvest** [comment]
I wonder if this might also have been fixed by https://github.com/netty/netty/pull/13478

**Comment by abstract-liu** [comment]
I will have a try of this version

**Comment by abstract-liu** [comment]
By the way, I found the previous problem was that i reuse a released buffer, and call decnt method again. When the new pooled allocator allocate this buffer, it will failed refcnt check, what’s worse it may crash jvm somehow. 
And I will check the new version soon. Thanks
