### ISSUE TITLE
mvn clean package -DskipTests failed in netty-resolver-dns-native-macos. [ERROR] Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.14:build (build-native-lib) on project netty-resolver-dns-native-macos:

### ISSUE THREAD

**Issue by WuYHH** [netty/netty#12391]
### Expected behavior
SUCCESS
### Actual behavior
when i use `mvn clean package -DskipTests`, the error happened. The detail is below:

The error info of **netty-parent**
[ERROR] Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.14:build (build-native-lib) on project netty-resolver-dns-native-macos: build failed: org.apache.maven.plugin.MojoExecutionException: ./configure failed with exit code: 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :netty-resolver-dns-native-macos

The error info of **netty-resolver-dns-native-macos**
[INFO] checking for dlfcn.h... yes
[INFO] checking for objdir... .libs
[INFO] checking if gcc supports -fno-rtti -fno-exceptions... yes
[INFO] checking for gcc option to produce PIC... -fno-common -DPIC
[INFO] checking if gcc PIC flag -fno-common -DPIC works... yes
[INFO] checking if gcc static flag -static works... no
[INFO] checking if gcc supports -c -o file.o... yes
[INFO] checking if gcc supports -c -o file.o... (cached) yes
[INFO] checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
[INFO] checking dynamic linker characteristics... darwin21.4.0 dyld
[INFO] checking how to hardcode library paths into programs... immediate
[INFO] checking whether stripping libraries is possible... yes
[INFO] checking if libtool supports shared libraries... yes
[INFO] checking whether to build shared libraries... yes
[INFO] checking whether to build static libraries... no
[INFO] configure: javac was on your path, checking to see if it's part of a JDK we can use...
[INFO] checking if '/usr' is a JDK... no
[INFO] configure: Taking a guess as to where your OS installs the JDK by default...
[INFO] checking if '/System/Library/Frameworks/JavaVM.framework' is a JDK... no
[INFO] configure: error: JDK not found. Please use the --with-jni-jdk option
[INFO] rc: 1

### Netty version
4.1.78
### JVM version (e.g. `java -version`)
Picked up _JAVA_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
java version "12.0.2" 2019-07-16
Java(TM) SE Runtime Environment (build 12.0.2+10)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)
### OS version (e.g. `uname -a`)
Darwin mbp.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
Are you sure your `JAVA_HOME` points to a JDK ?

**Comment by Kvicii** [comment]
I think you need config your developer environment.

**Comment by chrisvest** [comment]
I think we can close this as we haven't heard, and the issue is plausibly with reporters build environment.

**Comment by superRainGit** [comment]
I config the JAVA_HOME  and  execute `echo $JAVA_HOME` can print the root path of java, but the log print with -X show 

(skip......)
checking if '/usr' is a JDK... no
[INFO] configure: Taking a guess as to where your OS installs the JDK by default...
[INFO] checking if '/System/Library/Frameworks/JavaVM.framework' is a JDK... no
[INFO] configure: error: JDK not found. Please use the --with-jni-jdk option
(skip......)

not use PATH's JAVA_HOME,  how can i resolve this compile error

**Comment by ThinWichael** [comment]
I encounter this issue by running mvn install.

I set it in my pom.xml.

I add 
       <arg>--with-jni-jdk=/Users/petterLee/Library/Java/JavaVirtualMachines/corretto-18.0.2/Contents/Home</arg>
to below pom.xml

```
<executions>
              <execution>
                <id>build-native-lib</id>
                <configuration>
                  <name>netty_resolver_dns_native_macos_${os.detected.arch}</name>
                  <nativeSourceDirectory>${nativeSourceDirectory}</nativeSourceDirectory>
                  <libDirectory>${project.build.outputDirectory}</libDirectory>
                  <!-- We use Maven's artifact classifier instead.
                       This hack will make the hawtjni plugin to put the native library
                       under 'META-INF/native' rather than 'META-INF/native/${platform}'. -->
                  <platform>.</platform>
                  <configureArgs>
                    <arg>${jni.compiler.args.ldflags}</arg>
                    <arg>${jni.compiler.args.cflags}</arg>
                    <arg>MACOSX_DEPLOYMENT_TARGET=10.9</arg>
                    <arg>--with-jni-jdk=/Users/petterLee/Library/Java/JavaVirtualMachines/corretto-18.0.2/Contents/Home</arg>
                  </configureArgs>
                </configuration>
                <goals>
                  <goal>generate</goal>
                  <goal>build</goal>
                </goals>
              </execution>
            </executions>
```
