### ISSUE TITLE
tcnative binaries for Windows not available on Maven Central

### ISSUE THREAD

**Issue by davidmc24** [netty/netty#12410]
### Expected behavior

Based on the documentation [here](https://netty.io/wiki/forked-tomcat-native.html#wiki-h2-5), I expect that `netty-tcnative` binaries for Windows should be available in Maven Central with the classifier `windows-x86_64`.

### Actual behavior

At least as of `2.0.52.Final`, the classifiers available do not include `windows-x86_64`.  The classifiers available were:

* `osx-x86_64`
* `linux-x86_64`
* `linux-x86_64-fedora`
* `linux-aarch_64-fedora` (undocumented)

https://search.maven.org/artifact/io.netty/netty-tcnative/2.0.52.Final/jar

### Netty version

2.0.52.Final

**Comment by chrisvest** [comment]
Looks like 2.0.36 is the last version that had Windows binaries? https://repo1.maven.org/maven2/io/netty/netty-tcnative/2.0.36.Final/

**Comment by davidmc24** [comment]
Interesting. I hadn't noticed that there we any versions that did, but that appears to be correct.

**Comment by normanmaurer** [comment]
We only support windows for netty-tcnative-boringssl-static for a long time now

**Comment by davidmc24** [comment]
Thank you for the response. Could that be stated more clearly in the documentation?

**Comment by chrisvest** [comment]
I've updated https://github.com/netty/netty/wiki/Forked-Tomcat-Native
