### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class io.netty.channel.DefaultChannelId

### ISSUE THREAD

**Issue by DevinChemeleon** [netty/netty#12449]
### Expected behavior

connect to server(tcp use netty).

### Actual behavior

got an error NoClassDefFoundError, and there was a warn print by logger:  WARN io.netty.channel.DefaultChannelId - Failed to find the current process ID from ''; using a random value: 749849705

### Steps to reproduce

1.prepare my netty client in a common way.
2.connect to loop server.

### Minimal yet complete reproducer code (or URL to code)

client:

        eventExecutors = new NioEventLoopGroup();
        bootstrap = new Bootstrap();

        bootstrap.group(eventExecutors)
                .channel(NioSocketChannel.class)
                .handler(new ChannelInitializer<SocketChannel>() {
                    @Override
                    protected void initChannel(SocketChannel ch) throws Exception {
                        ch.pipeline().addLast(new ByteArrayDecoder())
                                .addLast(new ByteArrayEncoder())
                                .addLast(new Handler()); // not important in reproduce
                    }
                });
        try{
                 // problem
                channelFuture = bootstrap.connect(127.0.0.1, 7070).sync();
        }catch(Error e){
                // logger.log(e)
        }

besides, you need a common server use netty.

### Netty version

i had try 4.1.75.final and 4.1.77.final, problem exist in both.

### JVM version (e.g. `java -version`)

jdk1.6.0_u45

### OS version (e.g. `uname -a`)

Red Hat Enterprise Linux Server release 5.6 (Tikanga)
Linux version 2.6.18-238.el5PAE

**Comment by 500242990401** [comment]
java.lang.NoClassDefFoundError: Could not initialize class io.netty.util.internal.EmptyArrays is the reason why this method failed!

**Comment by chrisvest** [comment]
@DevinChemeleon do you have the complete stack trace?

**Comment by DevinChemeleon** [comment]
no, i didn't get one from java, but there are some information through debug, and the source code version is 4.1.77.final:

java.lang.NoClassDefFoundError: javax/security/cert/X509Certificate
java.lang.NoClassDefFoundError: Could not initialize class io.netty.util.internal.EmptyArrays
java.lang.NoClassDefFoundError: Could not initialize class io.netty.channel.DefaultChannelId
io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioSocketChannel
-----------------------------------------------------------------------------------------
the invoke happends in io.netty.channel.AbstractChannel's newId().
the stack trace is like to:

  io.netty.channel.DefaultChannelId.newInstance()
  io.netty.channel.AbstractChannel.newId()
  ...

and the Error appeared in the Class:DefaultChannelId's static init block:

static {
 ...
        if (processId < 0) {
//  first appearance but is not fatal
            processId = defaultProcessId();
...
        }
...
        if (machineId == null) {
// the second and fatal
            machineId = defaultMachineId();
...
        }
...
    }
------------------------------------------------------------------------------------
some supplementary informations:
the project jdk is 1.6.0.0 and the runtime jre is 1.6.0_u45
linux verison: Linux localhost.localdomain 2.6.18-238.el5PAE #1 SMP Sun Dec 19 14:42:44 EST 2010 i686 i686 i386 GNU/Linux

**Comment by chrisvest** [comment]
I think something is wrong with your JRE. It's complaining that `javax/security/cert/X509Certificate` is missing, but that class was introduced in Java 1.4: https://docs.oracle.com/javase/6/docs/api/javax/security/cert/X509Certificate.html

Also, your Linux and Java versions are 12 and 9 years old, respectively. I strongly recommend migrating to something more recent.

**Comment by DevinChemeleon** [comment]
thanks, for some reason, my project need to compatible with these older versions.

i'm not sure if it's the X509Certificate causeed the failure. I hope we can determine the real reason.

**Comment by normanmaurer** [comment]
We don't support java 1.4. You will need something more recent to use netty.

**Comment by DevinChemeleon** [comment]
oh, something went wrong with my jre, the problem has been solved, thanks!
