### ISSUE TITLE
Multipart implementation for Netty 5

### ISSUE THREAD

**Issue by violetagg** [netty/netty#12450]
Multipart implementation was removed from Netty 5 (`main` branch) and there is no project in Netty contrib.

What are the plans for providing Multipart implementation for Netty 5?
Will it be part of Netty 5 or will it be a Netty contrib project or there are no plans to provide such implementation?

**Comment by normanmaurer** [comment]
@violetagg basically I think we need to add a new codec for it in contrib

**Comment by violetagg** [comment]
@normanmaurer Great! Can we create the project or you need to create it? @pderop will be working on this.

**Comment by chrisvest** [comment]
@violetagg @pderop I can invite you to the contrib org and you can create it.

**Comment by violetagg** [comment]
@chrisvest thanks

**Comment by pderop** [comment]
Thanks @chrisvest !

Before going ahead, I have few questions:

Regarding the project creation, I looked into the netty-contrib wiki and I'm thinking about creating a new **codec-multipart** project using the **template-multi** template. Can you please confirm if you are fine with this project name and with the following project structure ?

- netty-contrib/codec-multipart/codec-multipart/src/main/java/io/netty/contrib/handler/codec/http/multipart/*, 
- netty-contrib/codec-multipart/examples/src/main/java/io/netty/contrib/handler/codec/example/http/multipart/*
- netty-contrib/codec-multipart/src/main/java/io/netty/contrib/microbenchmarks/http/multipart/*

Now, regarding the new multipart codec, can you clarify if your intention is to get a porting of the old MP codec to Netty5 (with the API revamped to the new _Buffer_ API, using _Resource_, etc ...) or if you wish to get a completely new MP codec, with a totally different contract API (based on netty5 Buffer, of course) ? 

thanks for letting me know.

**Comment by chrisvest** [comment]
@pderop The project structure looks good to me.
I don't have a strong opinion on how much the API should or should not change.

**Comment by pderop** [comment]
@chrisvest ,

Hi,

just to say I created the project and copied the code from 4.1.78 and soon I will open a PR for discussion and then close this issue.

**Comment by pderop** [comment]
@chrisvest ,

Hi,

I have just created this [PR](https://github.com/netty-contrib/codec-multipart/pull/1) for the new multipart codec.
Some tasks still need to be done, but if you want you can take a first look ? There is an overview of the main changes that have been done, a TODO list, and also few open questions.

So, I'm closing this PR and we can then continue to discuss using the created PR.

thank you !

**Comment by pderop** [comment]
It seems I can't close this PR, could someone else do it ? thanks
