### ISSUE TITLE
[BUG]module not found : io.netty.transport.epoll

### ISSUE THREAD

**Issue by Netyyyy** [netty/netty#12456]
When upgrading `io.netty:netty-transport-native-epoll` to 4.1.77.Final, I met this error:
![image](https://user-images.githubusercontent.com/92105726/172979609-abc47235-08d5-4eb5-8b77-3c62372e73fa.png)
After checking the two versions: 4.1.76.Final and 4.1.77.Final, I found that `Automatic-Module-Name` changed in MANIFEST.MF,
4.1.76.Final:
![image](https://user-images.githubusercontent.com/92105726/172980004-cee357f3-9ec9-44da-8ef1-9c64e0ca8a36.png)
4.1.77.Final:
![image](https://user-images.githubusercontent.com/92105726/172980072-dd16da36-b9d5-4872-bebf-fc4ab711280e.png)

Does this change cause the error? Could help fix the error ASAP, thanks!

### Netty version
4.1.77.final
### JVM version (e.g. `java -version`)
Linux   java17

**Comment by normanmaurer** [comment]
@Netyyyy this change was needed to support multiple different architectures at the same time. Just change your module name you use.

**Comment by saragluna** [comment]
Hi @normanmaurer, this change will make it difficult for a library to support multiple Netty versions. To support Netty version `<= 4.1.69` requires the dependency on the module `io.netty.transport.epoll`, but to support Netty version `> 4.1.77` we must remove this same module. Do you have any suggestions on this?

**Comment by chrisvest** [comment]
Yeah, that's also my conclusion. JPMS is not flexible enough to express this, and we can't change the release that's already out.
