### ISSUE TITLE
AttributeKey valueOf whether there is a memory leak？

### ISSUE THREAD

**Issue by 1031885103** [netty/netty#12471]
package io.netty.util;

import io.netty.util.internal.ObjectUtil;
import io.netty.util.internal.PlatformDependent;
import java.util.concurrent.ConcurrentMap;

public final class AttributeKey<T> extends UniqueName {
    private static final ConcurrentMap<String, AttributeKey> names = PlatformDependent.newConcurrentHashMap();

    public static <T> AttributeKey<T> valueOf(String name) {
        ObjectUtil.checkNotNull(name, "name");
        AttributeKey<T> option = (AttributeKey)names.get(name);
        if (option == null) {
            option = new AttributeKey(name);
            AttributeKey<T> old = (AttributeKey)names.putIfAbsent(name, option);
            if (old != null) {
                option = old;
            }
        }

        return option;
    }

valueOf of AttributeKey saves data to map and does not see a method to remove names from map. Is there a memory leak or correct usage?Thank you very much!

**Comment by 1031885103** [comment]
ok

**Comment by 1031885103** [comment]
> Please in English

ok

**Comment by hyperxpro** [comment]
JVM will automatically wipe out unreferenced objects. So you don't have to worry about them.

**Comment by 1031885103** [comment]
> 



> JVM will automatically wipe out unreferenced objects. So you don't have to worry about them.

names is a statically decorated member variable,JVM GC automatically reclaim put objects?Look at the following code to see why the GC did not collect.If there is a mistake in the demo, how should it be presented?thank you.
![image](https://user-images.githubusercontent.com/34467531/173847937-2d6af2ff-51cc-4d16-bf4b-fe471a580cb9.png)

**Comment by hyperxpro** [comment]
That's not how JVM Garbage Collector works. You've to wipe all references linked with Objects you put in Map. The best situation is when you're done with map and you stop referencing it from everywhere, Garbage Collector will do it's job without calling `System#gc`.

Also, `System#gc` only triggers Garbage Collector but does it does not guarantee cleanup.

**Comment by chrisvest** [comment]
Attribute keys are meant to be effectively constants and gets internalised in the map, so we can reuse the same instances over and over. You should not generate them dynamically based on external data.

The code you have in the issue is from a really old version. It looks like this now: https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/AttributeKey.java#L25-L32

**Comment by 1031885103** [comment]
> Attribute keys are meant to be effectively constants and gets internalised in the map, so we can reuse the same instances over and over. You should not generate them dynamically based on external data.
> 
> The code you have in the issue is from a really old version. It looks like this now: https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/AttributeKey.java#L25-L32

Ok，Thank you very much!
