### ISSUE TITLE
download links dont point to latest 4.1.78 release

### ISSUE THREAD

**Issue by gemmellr** [netty/netty#12472]
The website news feed notes 4.1.78 was released:
https://netty.io/news/index.html
https://netty.io/news/2022/06/14/4-1-78-Final.html

However the link in the Downloads menu dropdown (and the download page the heading itself links to) at the top of the pages still point to 4.1.77 rather than 4.1.78.

**Comment by chrisvest** [comment]
It's updated now, thanks.
