### ISSUE TITLE
netty-resolver-nds:Cname max ttl can not be 0 

### ISSUE THREAD

**Issue by intxzt** [netty/netty#12488]
netty-resolver-nds:
The maxTtl of DefaultDnsCache can be set to 0, but the DefaultDnsCnameCache and DefaultAuthoritativeDnsServerCache can`t be 0.What is the reason  for this impl?

**Comment by chrisvest** [comment]
The `DefaultDnsCache` is older than the other two, so it is stuck with this feature for configuring a non-caching behaviour. Instead of setting max TTL to zero, integrators who don't want any caching should instead configure their resolver to use the `Noop*Cache.INSTANCE` implementations.
