### ISSUE TITLE
Opt-out from blocking reads of OS files for classifiers

### ISSUE THREAD

**Issue by mostroverkhov** [netty/netty#12480]
### Expected behavior

Less of redundant blocking IO in netty 

### Actual behavior

On initialization netty does [blocking](https://github.com/netty/netty/blob/c87c911c010c3a34a69e550d52299df20e5fc740/common/src/main/java/io/netty/util/internal/PlatformDependent.java#L231) reads of `/etc/os-release`, `/usr/lib/os-release` for
specific classifiers that are never available on some popular distros (e.g. ubuntu, alpine).
It would be helpful to avoid such blocking calls with system property - e.g. `-Dio.netty.readOsClassifiers=false`.

### Netty version

4.1.78.Final

**Comment by chrisvest** [comment]
These are used by the native code loading. I think it'd be better to have a system property where the classifier set can be directly specified, and then avoid reading the files if that property is present. Then it could also serve a dual purpose of overriding the files in case they produce a wrong classifier set for some reason.

**Comment by mostroverkhov** [comment]
@chrisvest Loading native library from user input probably has security implications - check input against shortlist of most popular distros? Also empty property `-Dio.netty.osClassifiers` should be allowed to ignore any distro-specific libraries, like with ubuntu/alpine nowadays?
