### ISSUE TITLE
Use the un-padded JCTools qs where makes sense

### ISSUE THREAD

**Issue by franz1981** [netty/netty#12496]
Some JCTools use cases are there to save useless garbage to be created and/or use bounded lock-free algorithms eg recycler, thread local pools for allocator
and not to save contention to squeeze the best scalability by such qs; maybe worth using the un-padded variants introduced recently and save the additional space required by the padded ones

Wdyt @nitsanw , @normanmaurer @chrisvest ?

**Comment by chrisvest** [comment]
I think this sounds like a good idea.

**Comment by slandelle** [comment]
Ping @franz1981 . The jctools dep was updated as of https://github.com/netty/netty/pull/14096

**Comment by franz1981** [comment]
Yep @slandelle I was hoping to need snipe some good buddy to work on this, cause I am scarce at cycles :)

**Comment by franz1981** [comment]
This can be closed due to https://github.com/netty/netty/commit/0211f48fa6c016d02b286a3fd9511daf4751de43
