### ISSUE TITLE
ChannelPipeline.fireChannelRead() called when autoread is false

### ISSUE THREAD

**Issue by gbrdead** [netty/netty#12503]
### Expected behavior
We expect that ChannelPipeline.fireChannelRead() will not be called while autoread is false.

### Actual behavior
Sometimes ChannelPipeline.fireChannelRead() will be called while autoread is false.

### Steps to reproduce
First, some statements:
A. We set autoread to false only from the channel's executor thread (from a reading handler).
B. We set autoread to true only from a different thread, never from channel's executor thread.

Here is what happens:
1. At the beginning, autoread is false.
2. autoread is set to true; since it is not set from the executor's thread, a read task is scheduled.
3. ChannelPipeline.fireChannelRead() is called on the channel by AbstractNioByteChannel.read(). Since autoread is true, this is not a problem. However, it is not called as a result of executing the read task from 2.
4. One of the channel's handlers sets autoread to false.
5. The read task from 2. is executed. This leads to ChannelPipeline.fireChannelRead() being called while autoread is false.

### Minimal yet complete reproducer code (or URL to code)
The situation is rare (though not extremely rare) and I don't know how to reproduce it with simple code. It does reproduce with our very big test suite every time (the suite runs for one hour; most of the tests are based on netty; there are about 2 reproductions of the described situation on each run).

### Netty version
4.1.77

### JVM version (e.g. `java -version`)
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 8.1.080)

### OS version (e.g. `uname -a`)
Windows and Linux (both x86-64)

**Comment by normanmaurer** [comment]
`AutoRead` is just a hint and there might still be situations where even tho autoRead is false we might pass data through the pipeline.
