### ISSUE TITLE
use netty to implement java.nio.channels

### ISSUE THREAD

**Issue by silence-coding** [netty/netty#12514]
I have a piece of software that relies on java.nio.channels and its underlying implementation uses junix socket. I was hoping to replace If Netty can provide an adaptation layer to decapsulate java.nio.channels implementation, Java.nio.channels-based programs can be quickly switched to Netty.

**Comment by chrisvest** [comment]
NIO channels are synchronous, while Netty channels are asynchronous. It's not impossible to bridge this gap, but you'll have to do it yourself.
I don't think this is something Netty should provide out of the box.
Perhaps you want to look at Virtual Threads (formally Project Loom) which is in preview in Java 19: https://bell-sw.com/announcements/2022/06/22/java-19-new-features-and-enhancements/#jep-425-virtual-threads-preview
