### ISSUE TITLE
Need osx-aarch_64 classifier version of epoll libraries

### ISSUE THREAD

**Issue by amitsgawali** [netty/netty#12563]
### Expected behavior
It doesn't support osx-aarch_64 classifier

### Actual behavior
It should support osx-aarch_64 classifier

### Steps to reproduce
1. Include below dependency tag in pom.xml and will give the error.

### Minimal yet complete reproducer code (or URL to code)
```
<dependency>
<groupId>io.netty</groupId>
<artifactId>netty-transport-native-epoll</artifactId>
<classifier>osx-aarch_64</classifier>
<version>4.1.63.Final</version>
</dependency>
```

### Netty version
4.1.63.Final

### JVM version (e.g. `java -version`)
```
openjdk version "1.8.0_333"
OpenJDK Runtime Environment (build 1.8.0_333-b02)
OpenJDK 64-Bit Server VM (build 25.333-b02, mixed mode)
```

### OS version (e.g. `uname -a`)
`Darwin <username>-MacBook-Pro 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64`

**Comment by hyperxpro** [comment]
AFAIK, Epoll is unsupported on Linux only.

**Comment by amitsgawali** [comment]
No, It is there for linux. linux_aarch_64 is there.

**Comment by hyperxpro** [comment]
Oops, That was a typo.

**Comment by normanmaurer** [comment]
@amitsgawali thats expected as epoll is not supported on macOS at all. Its a linux only feature
