### ISSUE TITLE
SingleThreadedEventLoop: add read-only iterator of channels

### ISSUE THREAD

**Issue by mostroverkhov** [netty/netty#12595]
### Expected behavior

For servers there is a need for per eventloop "watchdog" timer that ticks for all eventloop channels. For moderately high number of connections, It is cheaper cpu-wise than per channel scheduling. 

Now this requires additional data structure to hold active channels - which is wasteful as It duplicates the one from `SingleThreadedEventLoop` (its practically useful impls - epoll, kqueue, nio). 

It would be convenient to avoid this redundant additional data structure, and instead have read-only iterator of eventloop channels exposed on `SingleThreadedEventLoop` as `Iterator<Channel> registeredChannelsIterator()` (complementary to existing `int registeredChannels()` for channels count).

### Netty version

4.1.79

**Comment by chrisvest** [comment]
`NioEventLoop` do not already have a channel map, even though it knows how many channels are registered.

**Comment by mostroverkhov** [comment]
@chrisvest `NioEventLoop` has all its channels as collection - `selector.keys()`, where each key has ref to `NioChannel` with `attachment()`. While not map but collection, It also may be iterated the same way as `Map.values()`.

**Comment by chrisvest** [comment]
In that case I think it's fine to add if we mention in the javadoc that the method is optional, and the default implementation throws UnsupportedOperationException.

Are you interested in providing a PR?

**Comment by luneew** [comment]
I created a pr. please review.
