### ISSUE TITLE
HpackEncoder lookup performance for headers with unique values

### ISSUE THREAD

**Issue by amirhadadi** [netty/netty#12615]
Profiling one of our services which uses gRPC, I noticed that the call to ```HpackEncoder::getEntryInsensitive``` is cpu intensive.
The reason is that we are using tracing, which is implemented by having a header with trace id as value. So each header value is unique.
This is a worst case scenario for ```getEntryInsensitive```, as the hash map it uses is keyed by header name. So there's a single bucket with dozens of entries, all of which have the same name but different values, and all of them are traversed each time the tracing header is being looked up. Of course if there is any other header which happens to fall to the same hash bucket, it suffers the same fate.

A possible workaround is to make the header sensitive, so that it won't be added to the hash map. But this is a bit hackish, as it's not a sensitive header. Also, ```HpackEncoder``` is not configurable using [grpc-java](https://github.com/grpc/grpc-java).

A more robust approach is to have an additional hash map keyed by header name and value, instead of just the name. I implemented this approach, so if there's interest I can create a PR.

WDYT?

**Comment by hyperxpro** [comment]
Please create PR with benchmark results.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/12665
