### ISSUE TITLE
Netty allocator should be made more Virtual Thread friendly

### ISSUE THREAD

**Issue by franz1981** [netty/netty#12621]
Fixing https://github.com/netty/netty/pull/12109#issuecomment-1061686373 has saved many fast-thread-local creations while the allocator thread is a virtual one, that's good, but when allocation contention is happening, the current uses of `synchronized` keyword to protect pool arena's contended allocations prevent virtual threads to make uses of their scheduler, blocking their carrier threads: using Java Lock should improve it

@chrisvest wdyt?

**Comment by franz1981** [comment]
Yep @normanmaurer deal!

**Comment by thekalinga** [comment]
I read elsewhere that thread pinning happens where java stack has native frames. Since netty uses native code, will it have any impact on virtual threads?
