### ISSUE TITLE
Http2 connection is detected as Idle with the IdleStateHandler even when receiving Http2 frames 

### ISSUE THREAD

**Issue by Patanouk** [netty/netty#12660]
Hello!
I'm not sure if this is an issue. Feel free to close the ticket if netty behaves as expected

If the behavior is as expected, I am also looking for another way to detect idleness in an http2 connection from the client side
I couldn't find anything in the documentation, but there might be a better way than using the `IdleStateHandler`?

### Expected behavior
An http2 client with an `IdleStateHandler` does not get idle if we receive an `Http2StreamFrame`

### Actual behavior
An http2 client with an `IdleStateHandler` triggers an `IdleStateEvent` even if the connection receives some http2 frames`Http2StreamFrame`

For more details, the cause of this behavior is in the [Http2MultiplexHandler](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexHandler.java#L180), line 180
The `Http2MultiplexHandler` creates one child channel per http2 stream, and only fire the read to the child channel (e.g. the relevant http2 stream for a given Http2StreamFrame) 

This behavior makes sense, but it also means that the read event is never forwarded to the `IdleStateHandler`

### Steps to reproduce
Create an http2 server sending a ping
Connect the below client. The `IdleStateEvent` is triggered by the `IdleStateHandler`, despite data being received

### Minimal yet complete reproducer code (or URL to code)
```
    HttpClient httpClient = HttpClient.create()
        .protocol(HttpProtocol.H2C)
        .doOnConnected(
            connection -> connection.addHandlerLast(new IdleStateHandler(5, 0, 0)));
```

### Netty version
4.1.77

### JVM version (e.g. `java -version`)
Java 17

### OS version (e.g. `uname -a`)
20.04.1-Ubuntu

**Comment by Patanouk** [comment]
I actually fixed this shorty after opening the issue, by using the `doOnChannelInit` method, as described in the below

```
    HttpClient httpClient = HttpClient.create()
        .protocol(HttpProtocol.H2C)
        .doOnChannelInit((observer, channel, remoteAddress) -> channel.pipeline()
            .addFirst(new IdleStateHandler(readerIdleTimeSeconds, 0, 0)));
```

As far as I can tell, the `IdleStateHandler` should always be the first handler in a pipeline
If that's the case, it might be worth to update the javadoc for this class?
I would be happy to open a PR if you agree with this

In the meantime I will close this issue
Thanks a lot for Netty btw, awesome project!

**Comment by chrisvest** [comment]
The IdleStateHandler will monitor the location in the pipeline where it's placed. So it's depends on what you're trying to do; e.g. do you want it to see pings or handshakes, or do you want it to monitor a higher-level protocol.

With that in mind, I'm not sure if the javadocs need to be updated.
