### ISSUE TITLE
Replace stdlib write/read with send/recv

### ISSUE THREAD

**Issue by franz1981** [netty/netty#12673]
See https://github.com/fredrikwidlund/libreactor/issues/5 for more info;

I've verified (thanks to async-profiler using dwarf stack walking) that indeed the write/read code paths are a bit more "involved" then plain send/recv with FLAG == 0

I'll run some benchs in our labs, but the issue I've mentioned (and the super nice blog posts on https://talawah.io/blog/extreme-http-performance-tuning-one-point-two-million/) is encouraging
@chrisvest @normanmaurer

**Comment by franz1981** [comment]
I believe that we have used write/read due to what the JDK does, but JDK is handling general file descriptors (meaning files too!!) while on Netty we can benefit from being specialized

**Comment by normanmaurer** [comment]
@franz1981 yep thats a good one.. I remember reading about that as well but totally forgot to open a PR / issue:)

**Comment by franz1981** [comment]
I can open one, it should be 2 lines of code I suppose

**Comment by franz1981** [comment]
@normanmaurer 
Famous last words

> I can open one, it should be 2 lines of code I suppose

eheh
