### ISSUE TITLE
Pipeline configuration: Decoder, Handler, Encoder - throws: UnsupportedOperationException: unsupported message type: DefaultHttpResponse (expected: ByteBuf, FileRegion)

### ISSUE THREAD

**Issue by ShlomiRex** [netty/netty#12698]
### Expected behavior
The pipeline configuration:
* Decoder
* Handler
* Encoder
should not throw exception when a client sends HTTP request.

![image](https://user-images.githubusercontent.com/17744127/184534308-aca8b47a-134e-4eb1-8b60-29d9ad91d7cf.png)

By reading the documentation, the order should be executed like so:

Inbound:
Decoder, Handler

Outbound:
Encoder

### Actual behavior
The pipeline thorws exception:
```
Aug 14, 2022 2:14:04 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.UnsupportedOperationException: unsupported message type: DefaultHttpResponse (expected: ByteBuf, FileRegion)
```

### Steps to reproduce
* Clone my repo: https://github.com/ShlomiRex/netty-pipeline-test
* Run the code with the pipeline configuration:
![image](https://user-images.githubusercontent.com/17744127/184534284-66391ece-fd81-40ff-a74b-8db2504a9354.png)
* Send dummy HTTP request: `curl -v 127.0.0.1:8080`
* The program throws exception.
* Uncomment the 'Works' section, and comment the 'Doesn't work' section and see that it works, but not the other way around.

### Minimal yet complete reproducer code (or URL to code)
https://github.com/ShlomiRex/netty-pipeline-test

### Netty version
4.1.10.Final

### JVM version (e.g. `java -version`)
11

### OS version (e.g. `uname -a`)
* macOS 12.6, macbook pro 16 M1 
* Linux CentOS

**Comment by hyperxpro** [comment]
Move `MyHandler` to the bottom. That's it.

**Comment by chrisvest** [comment]
@hyperxpro is right.

The logic is that inbound data flows down the pipeline, and outbound data flows up the pipeline.

**Comment by ShlomiRex** [comment]
> Move `MyHandler` to the bottom. That's it.

I know. But this is a bug. Don't you agree?

> @hyperxpro is right.
> 
> The logic is that inbound data flows down the pipeline, and outbound data flows up the pipeline.

Which is exactly what my pipeline does. You disagree? If so, can you explain?

**Comment by chrisvest** [comment]
`MyHandler` reads a `HttpRequest` and writes a `DefaultHttpResponse`, but it sits _before_ the `HttpResponseEncoder` in the pipeline, so the response is never converted to a `ByteBuf` that the transport can send.

**Comment by ShlomiRex** [comment]
> `MyHandler` reads a `HttpRequest` and writes a `DefaultHttpResponse`, but it sits _before_ the `HttpResponseEncoder` in the pipeline, so the response is never converted to a `ByteBuf` that the transport can send.

Reading the official documentation of interface `ChannelPipeline`:
![image](https://user-images.githubusercontent.com/17744127/184834313-268bfdf7-7e67-43e1-a39d-2008a795b663.png)

It says that the outbound starts from the end and goes up the pipeline. As we know, the encoder is outbound handler. But from my understanding, what your saying, is that outbound flows from `MyHandler` and upwards, and not from `HttpResponseEncoder`. Is that what you are saying? 

I'm sorry if my question sounds dumb, but I really want to understand the execution order of inbound/outband handlers. By the documentation, this should not be a problem, since the outbound flow starts from `HttpResponseEncoder` and up.

Thanks!

**Comment by chrisvest** [comment]
If your handler does a write to the `ChannelHandlerContext` it's passed in, say, `channelRead`, then the write will propagate up from the handlers position in the pipeline. Otherwise handlers wouldn't have a way to pass the write through.

If you do a write to the `Channel`, then it'll propagate from the bottom of the pipeline.

**Comment by ShlomiRex** [comment]
> If your handler does a write to the `ChannelHandlerContext` it's passed in, say, `channelRead`, then the write will propagate up from the handlers position in the pipeline. Otherwise handlers wouldn't have a way to pass the write through.
> 
> If you do a write to the `Channel`, then it'll propagate from the bottom of the pipeline.

Thanks a lot!
If I change `ctx.write()` to `ctx.channel.write()` it propogates to the next pipeline as expected! And so the code:
```
                            pipeline.addLast(new HttpRequestDecoder());
                            pipeline.addLast(new MyHandler());
                            pipeline.addLast(new HttpResponseEncoder());
```
works! (it didn't work before because I was writing to context, and not channel).

Your a life savior!
