### ISSUE TITLE
microbench module is subject to API compatibility validations

### ISSUE THREAD

**Issue by amirhadadi** [netty/netty#12716]
### Expected behavior
All changes in the `microbench` module should not be subjected to API compatibility validations.
### Actual behavior
Some changes in the `microbench` module are subjected to API compatibility validations.

### Steps to reproduce
Remove a method from a benchmark class that's not in the `io.netty.microbench` package and run `mvn clean install -am -pl microbench`. This will fail on compatibility issues.

**Comment by normanmaurer** [comment]
@amirhadadi that sounds like a bug...

**Comment by amirhadadi** [comment]
@normanmaurer sounds like a bug to me too.
There are a couple of ways to fix it:

1. Move all existing classes into the `io.netty.microbench` package.
2. Override `japicmp-maven-plugin` and `revapi-maven-plugin` for the microbench module.

Which do you think is better?

**Comment by normanmaurer** [comment]
@amirhadadi lets add the override
