### ISSUE TITLE
Able to wrap the byte array or ByteBuffer without copying in the new Buffer API in the Netty 5 

### ISSUE THREAD

**Issue by floating-cat** [netty/netty#12723]
In Netty 4, there are `Unpooled.wrappedBuffer` APIs below which could wrap the `byte[]` or `ByteBuffer` without copying.
In Netty 5, it seems we need to use the `DefaultBufferAllocators.xxxAllocator().copyOf()` now which copies the data once. 
I have some direct ByteBuffers and some byte arrays and now I need to copy them once when using the Buffer API, which is not needed in Netty 4.

```java
public static ByteBuf wrappedBuffer(byte[] array)
public static ByteBuf wrappedBuffer(byte[] array, int offset, int length)
public static ByteBuf wrappedBuffer(ByteBuffer buffer)
...
```

Would it be possible to add similar APIs in the Netty 5 with the new Buffer API?
In this case, the API can require the user that they are transferring the ownership of these byte arrays or ByteBuffers data and won't edit them anymore.

I feel this is needed because 

* Without a way to warp it and need to always copy it once, it hurts performance.
* There is a `Buffer#forEachReadable` which could get the underhood `byte[]` or `ByteBuffer` but there is no counterpart to wrap them into `Buffer` which seems odd.
* In some cases, we can guarantee that we won't edit these `byte[]` or the `ByteBuffer` anymore and would like to transfer the ownership into the Netty framework and there is no need to copy.

Example use case:
In some high-level framework that uses the Netty 5 under the hood. The framework API or the user code might use/provide the `byte[]` or direct `ByteBuffer` data (because these types are common in other Java libraries), and now I need to copy them once when using Netty 5 to send them.

### Expected behavior
Wrap the byte array or `ByteBuffer` in `Buffer` without copying.

### Actual behavior
Need to use `DefaultBufferAllocators.offHeapAllocator().copyOf(byteBuffer)` which need copy once.

### Netty version
5.0.0.Alpha4

**Comment by chrisvest** [comment]
It's available but hidden, because it's unsafe in the sense that we'll have to take the programmers word that the array won't be shared.

What you need is in `MemoryManager.instance().unsafeWrap(byte[])`. That will create an unpooled buffer with the given array inside.

**Comment by floating-cat** [comment]
@chrisvest Thanks for the info.
May I ask one more question? Is there any way to wrap a direct `ByteBuffer` too? So when sending, it only needs to copy the `ByteBuffer` to the kernel once. Otherwise, I need to copy this into the off-heap `Buffer`, and then it needs to copy into the kernel which uses two copies here.

**Comment by chrisvest** [comment]
@floating-cat No, there's no way to wrap a direct ByteBuffer. You can allocate off-heap netty buffers from the start, and get direct buffers from them.

**Comment by normanmaurer** [comment]
@chrisvest imho we should provide one..

**Comment by floating-cat** [comment]
@chrisvest Unfortunately, this way doesn't solve my use case. I have a framework that uses Netty and it gets all buffers produced from the Netty and wraps it in some `byte[]` and `ByteBuffer` or a composite wrapper (wrap multi `byte[]`, `ByteBuffer`) to provide a high-level API (because these types are more common to use with other libraries and in JVM ecosystem). Then we could check these bytes data, produce new data (e.g. a new direct `ByteBuffer`), or just forward the original bytes data into Netty 5.

Now:
* If we provide a direct `ByteBuffer`, it needs to copy into off-heap Buffer in Netty 5, which use one more copy.
* If I just forward the original `ByteBuffer` (got from `Buffer.forEachWritable` before), I need to copy them.
* If I produce a new `byte[]` with a offset, the `MemoryManager.instance().unsafeWrap(byte[])` doesn't help and I need to copy them too.

I could just provide a wrapper of the `Buffer` as a high-level API but if force everyone to learn how to use `Buffer` or a new API and unable to work with other libraries well.

I suspect I am not the only one have this use case because nowadays a lot of frameworks use Netty under the hood which provides high-level APIs and need to refeed these data type back to Netty. Or maybe there is a better way to solve this issue instead of using the wrapper?

In the old API, we could wrap them in several ways or can even warp the array of the `byte[]` and `ByteBuf` (let the user indirect use the feature provided from `CompositeBuffer/CompositeByteBuf`) which are really flexible:

```
static ByteBuf | wrappedBuffer(byte[]... arrays)
static ByteBuf | wrappedBuffer(byte[] array)
static ByteBuf | wrappedBuffer(byte[] array, int offset, int length)
static ByteBuf | wrappedBuffer(ByteBuf... buffers)
static ByteBuf | wrappedBuffer(ByteBuf buffer)
static ByteBuf | wrappedBuffer(ByteBuffer... buffers)
static ByteBuf | wrappedBuffer(ByteBuffer buffer)
static ByteBuf | wrappedBuffer(int maxNumComponents, byte[]... arrays)
static ByteBuf | wrappedBuffer(int maxNumComponents, ByteBuf... buffers)
static ByteBuf | wrappedBuffer(int maxNumComponents, ByteBuffer... buffers)
static ByteBuf | wrappedBuffer(long memoryAddress, int size, boolean doFree)
```

**Comment by floating-cat** [comment]
Just found it is easy to just wrap `Buffer` via an adapter pattern in my code and expose it into a high-level API so I don't need to wrap/extract the baked `btyte[]` and `ByteBuffer` to/from `Buffer` anymore and I also don't need to care the `Buffer` backed implementation (or even `MemorySegment` in the future) which is more elegant. Thanks for all your's help!
