### ISSUE TITLE
Example of Netty integrating Stomp protocol

### ISSUE THREAD

**Issue by 1148973713** [netty/netty#12753]
In the example of Netty integrating Stomp protocol, the source code lets the client use Netty, and the front-end page is set as the server to integrate Stomp protocol.
How to use Netty to set the server and set the Endpoint connection point, let the front-end page bind the Endpoint connection point configured in the server through SockJS, and create a stompClient through stomp.over() to complete the client creation?

**Comment by amizurov** [comment]
@1148973713 Hi, could you please add more info about  you problem? If we speaking about this [example](https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/stomp/websocket) it's just an example of how the WS and STOMP integration might look.
