### ISSUE TITLE
HttpMessages implementing HttpContent types too aren't handled correctly

### ISSUE THREAD

**Issue by franz1981** [netty/netty#12750]
Changes due to #12709 have added a code path where `HttpMessage` types that implement `HttpContent` types too are handled in their separate code paths while handled as just `HttpMessage` right after too.

The fact that CI doesn't fail there means that there are no types like that (and it's not impacting existing users using default types too).

**Comment by Nick-The-Uncharted** [comment]
All subclasses of `io.netty.handler.codec.http.FullHttpMessage` was affected. In our case it is `AggregatedFullHttpRequest`.
