### ISSUE TITLE
Make MessageFormatter and FormattingTuple public

### ISSUE THREAD

**Issue by geoand** [netty/netty#12761]
Classes `io.netty.util.internal.logging.FormattingTuple` and `io.netty.util.internal.logging.MessageFormatter` are `public` classes, but the latter's `format` methods are package-private while the former's `constructor` is package-private making their use in custom in `InternalLoggerFactory` implementations impossible.

We ran into this issue in Quarkus and had to resort to copying them.

**Comment by chrisvest** [comment]
Looks weird that these classes were public in the first place, but that's what we decided to do in #12131.

@geoand do you want to submit a PR to fix the remaining visibility restrictions in those two?

**Comment by geoand** [comment]
@chrisvest sure thing! I opened https://github.com/netty/netty/pull/12763
