### ISSUE TITLE
Unable to capture DecoderException (`TooLongHttpLineException`)

### ISSUE THREAD

**Issue by abelsromero** [netty/netty#12769]
### Expected behavior

Be able to capture DecodeExceptions (example `TooLongHttpLineException`) in a similar way other exceptions can be captured, like `ChannelInboundHandler.exceptionCaught`.

### Actual behavior

Based on what I 've seen, exceptions happening in `HttpObjectDecoder` like this https://github.com/netty/netty/blob/5256f3628c553081e674f7b27e93a97350141715/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java#L973-L985 are just swallowed in:

* https://github.com/netty/netty/blob/5256f3628c553081e674f7b27e93a97350141715/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java#L277
*  https://github.com/reactor/reactor-netty/blob/61b761c212fd06f578ac1017071bf3782c149caf/reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerOperations.java#L743-L745

### Minimal yet complete reproducer code (or URL to code)

See https://github.com/abelsromero/netty-runner

### Netty version

1.0.22

### JVM version (e.g. `java -version`)

openjdk version "17.0.3.1" 2022-04-22 LTS

### OS version (e.g. `uname -a`)
Darwin romeroab-a01.vmware.com 21.5.0 Darwin Kernel Version 21.5.0
root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

**Comment by hyperxpro** [comment]
You should report this on Spring repository because Spring passes 4096 max length parameter to `HttpObjectDecoder`.

**Comment by abelsromero** [comment]
To me the issue is not the value, but not been able to track the exception. For other exceptions like `io.netty.resolver.dns.DnsResolveContext` we can capture that easily and log the information of the request to take actions, but not for this one since there's no (or I was not abel to find in code and docs) a method to do so.

**Comment by violetagg** [comment]
@abelsromero I'll encourage you to ask your question here https://gitter.im/reactor/reactor-netty

**Comment by abelsromero** [comment]
Updated issue with reproducer https://github.com/abelsromero/netty-runner

**Comment by abelsromero** [comment]
Thanks a lot! I could finally make it work with (updated the reproducer with a new commit with it)
```
		@Override
		public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
			if (msg instanceof DecoderResultProvider request) {
				DecoderResult decoderResult = request.decoderResult();
				if (decoderResult.isFailure()) {
					Throwable cause = decoderResult.cause();
					System.out.println(cause);
				}
			}
			super.channelRead(ctx, msg);
		}
```
