### ISSUE TITLE
why netty don't use mmap to map socket fd in to directbytebuffer ?

### ISSUE THREAD

**Issue by lcdzhao** [netty/netty#12771]
why netty don't use mmap to map socket fd in to directbytebuffer ? 

I know this question has been asked, but there is no answer.

**Comment by chrisvest** [comment]
Because you can't mmap a socket except for packet capture purpose.

**Comment by lcdzhao** [comment]
@chrisvest But according to the following documentation, the second usage scenario can also be a non-tracking package scenario.

https://docs.kernel.org/networking/packet_mmap.html

**Comment by chrisvest** [comment]
The simple answer is no one built it. These days there's io_uring, which we do have a transport for, and which provides a more approachable API.

**Comment by lcdzhao** [comment]
@chrisvest Thanks～
