### ISSUE TITLE
Question about FlushConsolidationHandler and writeAndFlush.await

### ISSUE THREAD

**Issue by zymap** [netty/netty#12785]
### Netty version

4.1.77.Final

### OS version (e.g. `uname -a`)

--- 

This is a question about the FlushConsolidationHandler and writeAndFlush.await.

After adding FlushConsolidationHandler, I found the writeAndFlush.await will get blocked. We didn't switch the thread when processing the message from the channel, so it looks like a deadlock. I check the code and still haven't figured out the reason. Want to hear your's ideas.

We add the consolidation handler like this:

```
pipeline.addLast("consolidation", new FlushConsolidationHandler(1024, true));
```

**Comment by normanmaurer** [comment]
from which thread you call `writeAndFlush()` ? Also did you check with a thread dump ?

**Comment by normanmaurer** [comment]
Closing this as there was no response anymore. Please re-open with more details if you still think there is a problem
