### ISSUE TITLE
Compound message creation performance

### ISSUE THREAD

**Issue by agusevas** [netty/netty#12801]
Hi all, 

I was analyzing the `rsocket-java` performance and found out, that it uses `CompositeByteBuf` for creating compound messages and allocates additional memory for `CompositeByteBuf` and its `Component`s. It also needs to duplicate `DirectByteBuffer` objects for sending those messages (because of `CompositeByteBuf.nioBuffers()` call). It doesn't allocate a lot of memory, but sending many messages it sums up. See related ticket https://github.com/rsocket/rsocket-java/issues/1066. 

What is the best way from performance perspective for creating compound messages? Copy all message parts into one `ByteBuf` (preventing memory allocation) or use `CompositeByteBuf` (with additional memory allocation)? 
I couldn't find any information about it except this (https://netty.io/wiki/new-and-noteworthy-in-4.0.html#new-buffer-type-compositebytebuf):

> A user can save bulk memory copy operations using a composite buffer at the cost of relatively expensive random access.

**Comment by chrisvest** [comment]
They have pros and cons, and which one comes out ahead depends on your use case.

I suggest you try both and benchmark them.

**Comment by normanmaurer** [comment]
+1 to what @chrisvest said... Also `Unpooled.wrappedBuffer(...)` might make sense as it creates a `FixedCompositeByteBuf` which has some advantages. Beside this you can reduce the GC by using the native epoll transport as with this we often don't need to duplicate the underlying nio buffers.
