### ISSUE TITLE
AbstractTrafficShapingHandler null pointer dereference

### ISSUE THREAD

**Issue by tilkinsc** [netty/netty#12802]
https://github.com/netty/netty/blob/2f4beae8ecfec25d0504119a7c4881092872e16a/handler/src/main/java/io/netty/handler/traffic/AbstractTrafficShapingHandler.java#L558
In this function trafficCounter can potentially be null and WriteTimeToWait() could crash.

**Comment by tilkinsc** [comment]
Extend it myself

**Comment by normanmaurer** [comment]
Generally speaking you should ensure its set before processing of messages start.
