### ISSUE TITLE
No ChannelOption.SO_REUSEPORT

### ISSUE THREAD

**Issue by ShlomiRex** [netty/netty#12800]
### Expected behavior
Have option Channel.SO_REUSEPORT
SO_REUSEPORT can be better understood here:
https://lwn.net/Articles/542629/

I want to enable this option to be able to re-use the same port over and over again (because of stress tests - running the test over and over again, the test creates server, and so I encountered this issue).

### Actual behavior
Do not have this options

### Steps to reproduce
```
    serverBootstrap
        .group(bossGroup, workerGroup)
        .channel(NioServerSocketChannel.class)
        .option(EpollChannelOption.SO_REUSEPORT)
        .handler(new LoggingHandler(LogLevel.INFO))
        .childHandler(channelHandler);
```
Notice that we have `EpollChannelOption` and not `ChannelOption`.

### Netty version
4.1.79

**Comment by chrisvest** [comment]
It's in `UnixChannelOption`, yeah.
