### ISSUE TITLE
Question about unsafe used in processSelectedKey in 4.1

### ISSUE THREAD

**Issue by EvanMi** [netty/netty#12812]
![image](https://user-images.githubusercontent.com/43713766/190537971-d5d46654-2106-4069-9ffa-6511c9b839af.png)

why the OP_WRITE branch do not use unsafe directly?

the code url is https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/nio/NioEventLoop.java

**Comment by normanmaurer** [comment]
Yep this can be changed.

**Comment by normanmaurer** [comment]
https://github.com/netty/netty/pull/12813/files
