### ISSUE TITLE
Binding ChannelHandler instance to an EventLoop

### ISSUE THREAD

**Issue by yomr** [netty/netty#12825]
### Netty version
4.1

### JVM version
OpenJDK 11

#### Background:

For the project I am working on, we have an underlying resource(let's say, `class ExpensiveResource`) that is not thread safe and does IO intensive stuff. In order to scale out, we will have 3-4 instances of `ExpensiveResource` in our application, and each instance will be bound to a particular `SingleThreadedEventLoop` from `ExpensiveResourceEventLoopGroup`. The size of that group will be equal to the number of instances we plan to have eventually, based on our performance testing.

The `ExpensiveResource` class  extends `ChannelInboundHandlerAdapter`

Here is a bare minimum code:

```
@NotThreadSafe
class ExpensiveResource extends ChannelInboundHandlerAdapter {
    private EventLoop eventLoop;
    private Cache myCache; 
     ExpensiveResource(EventLoop eventLoop, OtherStuff otherStuff) {
         this.eventLoop = eventLoop;
         this.myCache = Cache.emptyCache();
     }
     
    public void runIteration() {
         // Periodically, keep syncing and update the cache
         this.eventLoop.schedule(...)
   }

    @Override
    public void channelActive(ChannelHandlerContext ctx) throws Exception {
        //do something
    }
   
   @Override
   public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
      // do something that involves reading/updating  "myCache"
    }

    //Override other methods of ChannelInboundHandlerAdapter
}

```

And then, during startup and application bootstrapping process:
```

class BootstrapApplication {
..
..
    public void initializeResources() {
          List<ExpensiveResource> resources = new ArrayList<ExpensiveResource>();
          for (int i=0; i <= totalResourceInstancesDesired; i++) {
               resources.add(new ExpensiveResource(expensiveResourceEventLoopGroup.next(), otherStuff);
          }
         ..
         ..
    }
}

```

I am skipping the code where I initialize netty ServerBootstrap. I provide `ExpensiveResourceEventLoopGroup` as both, parent and child group and, a `ChannelInitializer` that I talk about in the next section.

#### Question

When a channel is created and bound to a particular `EventLoop`, how do I add the instance of `ExpensiveResource` running in that EventLoop, as a `ChannelHandler`  in `ChannelPipeline`?

Here is the sample code for `ChannelInit`:

```
        @Override
        public void init(Channel channel) {
            ExpensiveResource exr = // How do I get the instance of `ExpensiveResource` bound to `channel.eventLoop()`?
            channel.pipeline().addLast(exr);
        }

```

I could think of couple of ways:

1. Filter through `List<ExpensiveResource> resources` to get the resource bound to `channel.eventLoop()`. Or maybe, use a map of eventLoop to ExpensiveResource(`Map<EventLoop, ExpensiveResource> assignments`) and then do `assignments.get(channel.eventLoop())`.
2. Use `ThreadLocal` on the EventLoop instance(during bootstrap process) to store the  bound `ExpensiveResource` instance, and then access that ThreadLocal instance in the `init` method.
3. [Not sure if feasible) Make `ExpensiveResource` extend `AbstractEventLoop`, which then makes it easy to just know the handler. But not sure if this recommended and might require more effort to make everything work smoothly?

Also, as far as I know, it is not possible to set any attributes on the `EventLoop` (like `channel.attr(..)`). That could have helped. 

Right now, the easiest looking solution to me is using a `Map`. But I think there might be a better solution. 

Also, I think a better phrasing of the original question could be "Can I add a `ChannelHandler` to  `ChannelPipeline` based on the `EventLoop` of the `channel`, without me having to maintain an explicit mapping?"

Thank You.

**Comment by yomr** [comment]
Just a gentle check to see if someone can help with this. Thank you in advance 😊

**Comment by yomr** [comment]
I went with `ThreadLocal` solution for now, but still curious to know the thoughts. Thank you.

**Comment by normanmaurer** [comment]
I think either a `Map` or `ThreadLocal` can work.
