### ISSUE TITLE
Netty Direct Memery LEAK

### ISSUE THREAD

**Issue by srctar** [netty/netty#12829]
### Actual behavior

Memery Counter:
`io.netty.util.internal.PlatformDependent#DIRECT_MEMORY_COUNTER`

It grow up when http 499, at last be `io.netty.util.internal.OutOfDirectMemoryError`

### Steps to reproduce

a sping cloud project, user netty for server;  reactor-netty version 0.8.5.RELEASE.
use netty http client。

Spring Controller only for translate http request:
```
  @GetMapping("/bigData3")
  public String bigData3() {
    if (big == null) {
      big = JSON.toJSONString(x());
    }
    String s = RandomUtils.nextDouble() + big + RandomUtils.nextLong();
    s += s;
    s += s;
    s += s;
    return s;
  }

  @GetMapping("/bigData5")
  public Mono<String> bigData5() {
    return webClientBuilder.build()
        .get()
        .uri("http://127.0.0.1:8080/bigData3")
        .retrieve()
        .onStatus(HttpStatus::is4xxClientError, upstream4xxResponseException())
        .bodyToMono(new ParameterizedTypeReference<String>() {
        });
  }
```
use `curl` for http client: `curl -m 4 127.0.0.1:8080/bigData5`.

as we know, bigData3 cost about 3~4 seconds, so, the curl request may cancel the http request when netty server is responsing.

if you try, you may found `DIRECT_MEMORY_COUNTER` increment but not decrement, cause OutOfDirectMemoryError

### Netty version
4.1.33.Final
### JVM version (e.g. `java -version`)
8.0
### OS version (e.g. `uname -a`)
linux, 4.18.0-193.6.3.el8_2.v1.2.x86_64

**Comment by chrisvest** [comment]
Try with `-Dio.netty.leakDetection.level=PARANOID` and see if your app is leaking memory.

**Comment by normanmaurer** [comment]
Beside this you should also upgrade... 4.1.33.Final is really old.

**Comment by srctar** [comment]
> 

Yes， Netty tould me there is memery leak(https://netty.io/wiki/reference-counted-objects.html):
```
LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:339)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:113)
	org.springframework.core.io.buffer.NettyDataBufferFactory.allocateBuffer(NettyDataBufferFactory.java:71)
```

I tried pmap for looking up the java memery, and I found a block almost 800MB(my http response is 10MB), contains my http response, but only 2 block(20MB), the other is 00000000...(780MB)

**Comment by srctar** [comment]
> 除此之外，您还应该升级... 4.1.33.Final 真的很旧。

I know what you say， but you konw:
1. Product environment, the most important is stabilization， if it`s ok, it should be run;
2. Java lib depenency, web dependency almost regular, each dependency upgrade may couse Product not stabilization, or cost a lot of time

**Comment by srctar** [comment]
> Try with `-Dio.netty.leakDetection.level=PARANOID` and see if your app is leaking memory.

My version:  4.1.33.Final

I found the place cause memery leak(I don`t know if the higher version fixed this)：
```
io.netty.channel.epoll.AbstractEpollStreamChannel.EpollStreamUnsafe#epollInReady
```
the boolean value close(**line 790**):
```
close = allocHandle.lastBytesRead() < 0;
```

my project is like this:
```
curl ->(http)->  netty server(spring cloud) --> netty-client --> other http server ;
```
when curl get http response and data is transfering, cancel the curl (`curl -m 1 http://xxx`);
  
the netty-client is recevicing (othes http server) http data,  into direct memery, but `allocHandle.lastBytesRead()` never return -1.

so the direct memery may not be cleard.

and this cause memery leak.

**Comment by normanmaurer** [comment]
I am sure there is no leak in the place in the lates release. Please upgrade
