### ISSUE TITLE
Multiple calls writeAndflush at the same time  will  delay 3-5 seconds

### ISSUE THREAD

**Issue by bolingling8** [netty/netty#12820]
There is no problem when there are not many users. When there are about 2000 users online（call writeAndFlush 2000 times per second） at the same time, the response will be delayed for a few seconds.

This is my code
Main Thread:
 
         ResourceLeakDetector.setLevel(ResourceLeakDetector.Level.ADVANCED);
         EventLoopGroup bossGroup = new NioEventLoopGroup();
         EventLoopGroup workGroup = new NioEventLoopGroup(128);
         try {
             ServerBootstrap b = new ServerBootstrap();
             b.group(bossGroup, workGroup)
                     .channel(NioServerSocketChannel.class)
                     .handler(new LoggingHandler(LogLevel.DEBUG))
                     .childOption(ChannelOption.SO_KEEPALIVE, true)
                     .childOption(ChannelOption.WRITE_BUFFER_WATER_MARK, new WriteBufferWaterMark(128*1024, 256*1024))
                     .childHandler(
                             new ChannelInitializer<SocketChannel>() {
                                 public void initChannel(SocketChannel ch) {
                                     ch.pipeline().addLast(new IdleStateHandler(60, 60, 60));
                                     ch.pipeline().addLast("http-codec", new HttpServerCodec());
                                     ch.pipeline().addLast("aggregator", new HttpObjectAggregator(65536));
                                     ch.pipeline().addLast("http-chunked", new ChunkedWriteHandler());
                                     ch.pipeline().addLast("decoder",new FixedLengthFrameDecoder(2*1024*1024));
                                     ch.pipeline().addLast("handler", new WebSocketServerHandler(port));
                                 }
                             }
                     );
             ChannelFuture f = b.bind(port).sync();
             f.channel().closeFuture().sync();
         } catch (Exception e) {
             e.printStackTrace();
         } finally {
             bossGroup.shutdownGracefully();
             workGroup.shutdownGracefully();
         }

Logic Thread

    public static void sendMsgToChannel(Channel channel, WebMessage message) {
        if (channel == null || !channel.isActive()) {
            return;
        }
        //logger.info("----sendMsgToChannel----{}", JSON.toJSONString(message));
        channel.writeAndFlush(new TextWebSocketFrame(JSON.toJSONString(message, new SerializerFeature[]{SerializerFeature.DisableCircularReferenceDetect})));
    }

There are lots of Logic Threads,  and every thread will send msg to client by channel after process.
When the call of sendMsgToChannel less than 1500 times per second, all are good. But more than 2000 times, some msg will delay about 5 seconds. I check the tcp win and buffer, both are enough, and the network also good, no delay. 
And I also thought maybe some channel got the  WRITE_BUFFER_WATER_MARK level,  but when i print log. every channel send one msg  in a few seconds and msg is small one.
I find the problem from internet, some one also has the same problem.

**Comment by bolingling8** [comment]
using netty-all-4.1.6.Final.jar

**Comment by bolingling8** [comment]
http://normanmaurer.me/presentations/2014-facebook-eng-netty/slides.html#10.0
I saw this PPT
I only use ChunkedWriteHandler, also checked channel.isWritable()

**Comment by hyperxpro** [comment]
Please upgrade to the latest version of Netty 4.1.

**Comment by bolingling8** [comment]
> Please upgrade to the latest version of Netty 4.1.
already found the issue and repaired?

**Comment by bolingling8** [comment]
I try the latest version , but it also the same.

**Comment by bolingling8** [comment]
hello,  no one help me

**Comment by hyperxpro** [comment]
Are you blocking any Event loop?

**Comment by normanmaurer** [comment]
Let me close this for now... Please re-open if the problem still shows up after you applied the suggestions

**Comment by vajaw** [comment]
spark shuffle has the same problem when using netty

**Comment by normanmaurer** [comment]
@vajaw please open a new issue and provide details
