### ISSUE TITLE
File descriptor leaking issue 

### ISSUE THREAD

**Issue by xkzhao** [netty/netty#12831]
### Expected behavior
We expected the fd will be released after netty channel is closed. 
### Actual behavior
fd usage keep increasing.  There are lots of `closed` sockets. 

```
$ ss -s
Total: 26574
TCP:   26297 (estab 5645, closed 20587, orphaned 0, timewait 8)
```

### Netty version
4.1

### JVM version (e.g. `java -version`)
jdk 11

### OS version (e.g. `uname -a`)
linux

**Comment by chrisvest** [comment]
Can you add more detail? What is the app doing; how do you recreate this issue? What specific Netty version are you using, or have tried?
