### ISSUE TITLE
Unable to build using 4.1.82.Final version jar

### ISSUE THREAD

**Issue by manojpunde91** [netty/netty#12840]
We are using netty-all-4.1.46.Final version in our project and want to upgrade to 4.1.82.Final.

[https://mvnrepository.com/artifact/io.netty/netty-all/4.1.82.Final
](https://mvnrepository.com/artifact/io.netty/netty-all/4.1.82.Final
)
[https://repo1.maven.org/maven2/io/netty/netty-all/4.1.82.Final/
](https://repo1.maven.org/maven2/io/netty/netty-all/4.1.82.Final/
)

But this artifact doesn't have sources.jar file. Only Jar and pom file is there.
I can see after 4.1.63.Final version there is no sources.jar

After using latest netty-all jar, it does not contains java code packages. Only meta-inf folder is loaded.

How to solve this issue? Help is appreciated.

OS : Amazon Linux 64 bit
JDK : openJDK 1.8.0 Update 342
IDE : Intellij
Build tool : Gradle
@sprsquish @adamv  @subbarao

**Comment by slandelle** [comment]
netty-all is now a Bill Of Material that pulls all the netty individual modules transitively, not a fatjar that merges all of them.

**Comment by manojpunde91** [comment]
tried to consume BOM library as :
'netty-bom'               : 'io.netty:netty-bom:4.1.82.Final',

But no luck. getting same error:
error: package io.netty.handler.ipfilter does not exist
import io.netty.handler.ipfilter.IpFilterRuleType;

It would be great if you provide any netty-bom example for gradle build.

**Comment by slandelle** [comment]
I think that's a question for gradle experts on a gradle forum.

**Comment by manojpunde91** [comment]
Sure. Will refer gradle document.
Just want to confirm we cant use netty-all version directly, we should use netty-bom for dependency management?

**Comment by normanmaurer** [comment]
netty-bom is usually a good way to ensure you use the right versions
