### ISSUE TITLE
Code check to prevent IllegalReferenceCountException to occur

### ISSUE THREAD

**Issue by joyfulnikhil** [netty/netty#12850]
Can a check for **cumulation.refCount() >0** be placed here? This will ensure that only those bytebuf are released whose refCount>0 and if bytebuf already has a refcount of 0, it is already deallocated or can be returned to the object pool. This will prevent IllegalReferenceCount from occurring. 
Not sure about the implication on memory (Whether this check will cause a memory leak ?)

_Originally posted by @joyfulnikhil in https://github.com/netty/netty/pull/12662#discussion_r984202665_

**Comment by normanmaurer** [comment]
@joyfulnikhil this would just "hide" bugs.
