### ISSUE TITLE
Proposal)Netty5)Remove Apache commons logging related classes

### ISSUE THREAD

**Issue by jchrys** [netty/netty#12856]
Apache commons logging has not been updated since 2014.
and Netty's classes that support for it was marked as deprecated in 2016. (#5615)
I think now is a good time to get rid of deprecated classes and their dependencies.

Please let me know If I can create a PR.

**Comment by normanmaurer** [comment]
Yes please 🙏

**Comment by jchrys** [comment]
Thank you for your reply. Let me create a PR soon 👍
