### ISSUE TITLE
Netty dependency not found for Gatling (via Gradle in Spring project) 

### ISSUE THREAD

**Issue by MichalKotecki** [netty/netty#12872]
I get an error
`Could not find netty-transport-native-epoll-4.0.51.Final-linux-aarch_64.jar (io.netty:netty-transport-native-epoll:4.0.51.Final).`
when trying to include Gatling (`id "io.gatling.gradle" version "3.8."`) into my Spring Gradle project, because it uses Netty. 
It seems like it could not been found in any repository, because the name is actually wrong. There is a JAR called 
netty-transport-native-epoll-4.0.51.Final-linux-**x86_64**.jar, so what is wrong is probably the naming mistake, the required artifact should be 'x86_64', not 'aarch_64'.

Probably the issue is related to:
https://github.com/netty/netty/issues/12861

Can I fix it somehow myself?

**Comment by normanmaurer** [comment]
We don't support native epoll lib on aarch64 when using netty 4.0.x. You either need too upgrade to 4.1.83.Final or remove the dependency

**Comment by MichalKotecki** [comment]
After changing the  Netty version to ` 4.1.83.Final`, I get similar error about another dependency
`Could not find netty-tcnative-boringssl-static-2.0.34.Final-linux-aarch_64.jar (io.netty:netty-tcnative-boringssl-static:2.0.34.Final).`

**Comment by slandelle** [comment]
Same thing: you're using an old `netty-tcnative-boringssl-static` version from 07-Nov-2019 that doesn't have aarch64 support. You have to upgrade to `2.0.54`.
