### ISSUE TITLE
Netty Http 2 server does not provide any option to ignore http2 request without response

### ISSUE THREAD

**Issue by iyappan** [netty/netty#12883]
### Requirement:

    Our application runs on Springboot with embedded Netty server(enabled http2). And it exposes services via Rest Apis.
    On Rest Api call, we have a scenario where we wanted to ignore the http2 request without sending any response.

### Expected behavior
     Netty server need to expose a API or any other visible provision to ignore a request without sending a response. 
### Actual behavior
     Not able to find any solution for this expectation
### Steps to reproduce
     Not able to find any solution for this expectation

### Your Environment
    Reactor version(s) used: reactor-netty-http : 1.0.16
    JVM version (java -version): 17.0.1
    springBootVersion= 2.6.7

**Comment by normanmaurer** [comment]
Please open an issue with spring. /cc @violetagg
