### ISSUE TITLE
SctpMessageCompletionHandler refer io.netty.util.collection.IntObjectMap, but can't find

### ISSUE THREAD

**Issue by wuzhj1** [netty/netty#12889]
### Actual behavior

class SctpMessageCompletionHandler refer to the io.netty.util.collection.IntObjectHashMap, but it isn't exist. because of module common already deleted the collection?

### Minimal yet complete reproducer code (or URL to code)
![image](https://user-images.githubusercontent.com/43143470/195483474-c254d1b9-4e21-496c-b213-4f6fa9619f93.png)

### Netty version
4.1.85.Final-SNAPSHOT

### JVM version (e.g. `java -version`)

java version "1.8.0_291"

### OS version (e.g. `uname -a`)

win10

**Comment by wuxuanqicn** [comment]
generated during build, run `mvn clean package`, see #12208
