### ISSUE TITLE
UnpaddedInternalThreadLocalMap nextIndex issues

### ISSUE THREAD

**Issue by jie-yang-java** [netty/netty#12907]
为什么UnpaddedInternalThreadLocalMap静态变量nextIndex不变成成员变量？静态变量导致了多个线程中有部分线程中的indexedVariables空间浪费情况。
translation：
Why does the UnpaddedInternalThreadLocalMap static variable nextIndex not become a member variable? Static variables lead to the waste of indexVariables space in some threads of multiple threads

**Comment by chrisvest** [comment]
Because the meaning of each index needs to be the same across all threads, in order to maintain a 1:1 mapping between FastThreadLocal objects, and slots in the thread-local maps.
