### ISSUE TITLE
Frame cannot be reused

### ISSUE THREAD

**Issue by hello-piper** [netty/netty#12928]
### Expected behavior
 Memory does not grows over time

### Actual behavior
 frame cannot be reused. So Memory grows over time .

### Steps to reproduce
broadcast msg

### Minimal yet complete reproducer code (or URL to code)

        TextWebSocketFrame frame = new TextWebSocketFrame(msg.toString());

        // 1 This is correct! But frame cannot be reused. So Memory grows over time .
        // At the beginning the memory increased from 500M to 1500M. which eventually led to OOM
        channels.forEach(ch -> ch.writeAndFlush(frame.retainedDuplicate()));

        // 2 This is not correct! Multiple channels only the first one can receive the frame?
        // Memory does not grows over time that meets my expectations.
        // Memory stable at 500M, the same as when I use Undertow
        channels.forEach(ch -> ch.writeAndFlush(frame));

        // So!  Please give me a way to reuse frame. without memory dont growing over time.

### Netty version
4.1.56.Final

### JVM version (e.g. `java -version`)
1.8.0_281

### OS version (e.g. `uname -a`)
Windows 10

**Comment by needmorecode** [comment]
Let's analyse the memory leak logic:
We assume the original RC(reference count) of the frame is 1, and the number of channels is N.
1. retainedDuplicate() makes RC++.
2. writeAndFlush() triggers RC-- at the end of the pipeline.
3. At last RC = 1 + N - N = 1, so it will not be released.

I think the right code should be:
```
frame.retain(channels.size() - 1);
channels.forEach(ch -> ch.writeAndFlush(frame.duplicate()));
```

**Comment by normanmaurer** [comment]
Closing as no response from reporter
