### ISSUE TITLE
WebSocketClientHandshaker java.lang.NullPointerException

### ISSUE THREAD

**Issue by heixiaoma** [netty/netty#12933]
WebSocketClientHandshaker 
![1666764902075](https://user-images.githubusercontent.com/10923974/197948891-0bc9490a-8b02-4d0f-bc49-506fcb1a0d11.png)

**Comment by heixiaoma** [comment]
Missing: header-> origin

**Comment by hyperxpro** [comment]
Please explain in more detail.

**Comment by heixiaoma** [comment]
When the websocketclient connection request header is missing the origin, a null pointer problem will occur

**Comment by chrisvest** [comment]
@amizurov What's your take? Do we need validation to check for the origin header somewhere?

**Comment by heixiaoma** [comment]
Now he throws a null pointer. I think we can give some warning logs

**Comment by amizurov** [comment]
Hi @heixiaoma , @chrisvest. Let me take a look.

**Comment by amizurov** [comment]
@heixiaoma  Could you please clarify, did you set `webSocketURL` -> "/ws" via constructor and `customHeaders` which contains `Host` but does not contain `Origin` header ?

**Comment by heixiaoma** [comment]
> @heixiaoma 您能否澄清一下，您是否`webSocketURL`通过构造函数设置了 -> "/ws" 并且`customHeaders`包含`Host`但不包含`Origin`header ？

yes

**Comment by amizurov** [comment]
So the main problem here, that if we pass the webSocketURL without host (e.g. '/ws') we faced with NPE even when we will build the `Host` header value. But if we pass the `Host` header value via `customHeaders` everything should works fine, but now we got the NPE on the building `Origin` header value (see https://github.com/netty/netty/issues/9673). 

I created the PR which should fix the `Origin` header behaviour (https://github.com/netty/netty/pull/12941). Also o think we can add additional check that if `webSocketURL` does not contain host and `Host` header does not present in custom headers we throw an invalid arg exception. @chrisvest WDYT ?

**Comment by chrisvest** [comment]
@amizurov Sounds good.

**Comment by amizurov** [comment]
> @amizurov Sounds good. Do you want to add that check to https://github.com/netty/netty/pull/12941, or in a different PR?

Added to https://github.com/netty/netty/pull/12941

**Comment by chrisvest** [comment]
I think this was fixed by #12941
