### ISSUE TITLE
io.netty.util.collection is not exist in source code

### ISSUE THREAD

**Issue by RealMuDao** [netty/netty#12937]
### Actual behavior
![image](https://user-images.githubusercontent.com/19743480/198467472-51617756-48d3-478a-ad63-0d6b405be19e.png)

### Netty version
4.1
### JVM version (e.g. `java -version`)
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)

**Comment by chrisvest** [comment]
It's generated at build time. Do a test-compile with Maven, and Intellij should be able to pick up the generated sources.
