### ISSUE TITLE
Spack support 

### ISSUE THREAD

**Issue by MatthewLieber** [netty/netty#12956]
Netty having support for Spack would extremely useful for some users.

This can be done by cloning the Spack repo from github https://github.com/spack/spack
cd spack
source share/spack/setup-env.sh
spack create https://github.com/netty/netty/archive/refs/tags/netty-4.1.84.Final.tar.gz

Then completing the FIXME items in the package file.  Mostly just adding who the maintainers for the package are and specifying the dependencies.

The Spack userguide can be found here https://spack.readthedocs.io/en/latest/index.html

**Comment by normanmaurer** [comment]
As @chrisvest said... let me close this one
