### ISSUE TITLE
Question about default encoding

### ISSUE THREAD

**Issue by freedom1b2830** [netty/netty#12973]
I know that with the release of java 17, the default encoding has become utf8. But how will this affect the version below?

`` find -type f -name *java -exec grep -HinE --color "defaultCharset\(\)" {} \;|grep -v "src/test"``
```
./codec/src/main/java/io/netty/handler/codec/string/StringDecoder.java:65:        this(Charset.defaultCharset());
./codec/src/main/java/io/netty/handler/codec/string/StringEncoder.java:61:        this(Charset.defaultCharset());
./resolver/src/main/java/io/netty/resolver/DefaultHostsFileEntriesResolver.java:144:            return parser.parseSilently(Charset.defaultCharset(), CharsetUtil.UTF_16, CharsetUtil.UTF_8);
./resolver/src/main/java/io/netty/resolver/HostsFileEntriesProvider.java:175:            return parse(locateHostsFile(), Charset.defaultCharset());
./resolver/src/main/java/io/netty/resolver/HostsFileEntriesProvider.java:188:                charsets = new Charset[]{Charset.defaultCharset()};
./resolver/src/main/java/io/netty/resolver/HostsFileEntriesProvider.java:284:            return parseSilently(locateHostsFile(), Charset.defaultCharset());
```
### Netty version
current version is a4c37bc06d16ba2267a3f8cac151f29bd9118aad
### JVM version (e.g. `java -version`)
java <17

**Comment by chrisvest** [comment]
All of those have overrides that allow the charset to be specified, except `DefaultHostsFileEntriesResolver` which on Windows is trying something on multiple different charsets, of which the default is one. I don't think we have a problem here.
