### ISSUE TITLE
accidental  JVM crash occurs in large clusters.

### ISSUE THREAD

**Issue by jr981008** [netty/netty#12995]
In 600 VM nodes microservice clusters. After upgrading som jars(not netty), jvm crash occurs occasionally. About one times a day, the crash stack points are associate netty.
The crash point is different each time and in different VM node。We are a little helpless about these jvm crashes. thank you provide idea about these jvm crash.
### Netty version
Netty 4.1.74.Final 
### JVM version (e.g. `java -version`)
1.8.0_272  aarch64
### OS version (e.g. `uname -a`)
linux 4.18.0-147.5.1.2

eg1：
![D664E302-95EF-44ED-9915-D0CDF9E12AD0 (1)](https://user-images.githubusercontent.com/20749545/201576517-911e3f43-c3de-460e-b843-e166754ec98e.jpg)

eg2:
![A34D6C7B-65CB-4BD1-9E8C-210BD24FCFD1](https://user-images.githubusercontent.com/20749545/201565637-f0e76feb-ef50-4eb9-86ed-def5b1184eaa.png)

eg3:

![92A1170F-DBA3-44A2-A75A-AD9E499D8CF3 (1)](https://user-images.githubusercontent.com/20749545/201576523-b77061d5-564b-45b4-931a-f87f5d36eba4.jpg)

sometimes crash in gc
![jdk](https://user-images.githubusercontent.com/20749545/201562825-7d5f3204-3de3-4960-a705-53e9f020e275.png)

we find jvm access some low address memory seems unnormally, guess that the jvm tries to access some damaged heap objects, and other components we used dont have jni method that have ability to operate local memory except netty.
![info](https://user-images.githubusercontent.com/20749545/201562831-cd743cf5-39be-4f74-bcd3-b814963dbbb2.png)

There is no clear way to reproduce this crash.

**Comment by normanmaurer** [comment]
Please upgrade to a more recent JVM version. The version you are using is really old

**Comment by jr981008** [comment]
same isuue in 1.8.0_341 aarch64

**Comment by chrisvest** [comment]
A couple of things you can try:

* Set the system property `io.netty.recycler.blocking` to `true`.
* Set the system property `io.netty.noUnsafe` to `true`.

Do these one at a time, and then together, to see what does and does not help.

**Comment by jr981008** [comment]
ok,i will try

**Comment by normanmaurer** [comment]
@jr981008 any update ?

**Comment by jr981008** [comment]
we rollback all libs we upgrade fix issue，but it contains more than 30 jars different，its too difficult to find which cause issue。
