### ISSUE TITLE
Why does the server respond with a 5-second delay

### ISSUE THREAD

**Issue by persistInHacker** [netty/netty#12999]
server:
`import io.netty.bootstrap.ServerBootstrap;
import io.netty.buffer.Unpooled;
import io.netty.channel.*;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.handler.codec.string.StringDecoder;
import io.netty.handler.codec.string.StringEncoder;
import lombok.extern.slf4j.Slf4j;

import java.nio.charset.Charset;

@Slf4j
public class NettyServer {

    public static void main(String[] args) throws Exception {
        EventLoopGroup bossGroup = new NioEventLoopGroup(1);
        EventLoopGroup workGroup = new NioEventLoopGroup(2);
        try {
            ServerBootstrap bootstrap = new ServerBootstrap();
            bootstrap.group(bossGroup, workGroup)
                    .channel(NioServerSocketChannel.class)
                    .option(ChannelOption.SO_BACKLOG, 128)
                    .childOption(ChannelOption.SO_KEEPALIVE, true)
                    .childHandler(new ChannelInitializer<SocketChannel>() {
                        @Override
                        protected void initChannel(SocketChannel ch) throws Exception {
                            ch.pipeline().addLast(new StringEncoder());
                            ch.pipeline().addLast(new StringDecoder());
                            ch.pipeline().addLast(new SimpleChannelInboundHandler<String>() {
                                @Override
                                protected void channelRead0(ChannelHandlerContext ctx, String msg) throws Exception {
                                    log.info("receive: {}", msg);
                                    ctx.writeAndFlush(Unpooled.copiedBuffer("ICY 200 OK\r\n", Charset.defaultCharset()));
                                    log.info("response success");
                                }
                            });
                        }
                    });
            log.info("server started...");
            bootstrap.bind(8001).sync().channel().closeFuture().sync();
        } finally {
            bossGroup.shutdownGracefully();
            workGroup.shutdownGracefully();
        }
    }
}`

client:
`import io.netty.bootstrap.Bootstrap;
import io.netty.buffer.ByteBuf;
import io.netty.channel.*;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioSocketChannel;
import io.netty.handler.logging.LogLevel;
import io.netty.handler.logging.LoggingHandler;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class NettyClient {

    public static void main(String[] args) throws Exception {
        EventLoopGroup eventExecutors = new NioEventLoopGroup();
        try {
            Bootstrap bootstrap = new Bootstrap();
            bootstrap.group(eventExecutors)
                    .channel(NioSocketChannel.class)
                    .handler(new ChannelInitializer<SocketChannel>() {
                        @Override
                        protected void initChannel(SocketChannel ch) throws Exception {
                            ch.pipeline().addLast(new LoggingHandler(LogLevel.INFO));
                            ch.pipeline().addLast(new SimpleChannelInboundHandler<String>() {

                                String loginPacket = "GET /RTCM32_GNSS_RTK HTTP/1.0\r\n" +
                                        "User-Agent: NTRIP GNSSInternetRadio/1.4.10\r\n" +
                                        "Accept: */*\r\n" +
                                        "Authorization: Basic YWFhYS0xMDAwMDU6MTIzNDU2\r\n\r\n";

                                @Override
                                public void channelActive(ChannelHandlerContext ctx) throws Exception {
                                    ByteBuf byteBuf = ctx.alloc().directBuffer();
                                    byteBuf.writeBytes(loginPacket.getBytes());
                                    ctx.channel().writeAndFlush(byteBuf);
                                }

                                @Override
                                protected void channelRead0(ChannelHandlerContext channelHandlerContext, String msg) throws Exception {
                                    log.info("receive: {}", msg);
                                }
                            });
                        }
                    });

            ChannelFuture channelFuture = bootstrap.connect("172.23.127.144", 8001);
            channelFuture.sync().channel().closeFuture().sync();
        } finally {
            eventExecutors.shutdownGracefully();
        }
    }
}`

When the server and client are on different IP addresses, the server responds with a delay of 5 seconds, who knows why, please help, thank you!

when update  String loginPacket = "GET /RTCM32_GNSS_RTK HTTP/1.0\r\n"  to   "GET /RTCM32_GNSS_RTK HTTP/1.4\r\n" , The problem goes away;

The netty thread is not blocked

**Comment by lhotari** [comment]
It's always DNS... Perhaps?

**Comment by persistInHacker** [comment]
> Tools like Wireshark or tcpdump can tell you if the request takes longer to arrive or the server takes longer to respond.

I did it, but I couldn't figure out why

**Comment by persistInHacker** [comment]
> It's always DNS... Perhaps?

Tell me more?

**Comment by persistInHacker** [comment]
> Is there any firewall on the network? It could be using deep packet inspecting, and assuming that an HTTP/1.0 request follows HTTP semantics, but since it does not have a profile for HTTP/1.4, it goes though the firewall

That opened my mind. Thank you. Let me test this hypothesis

**Comment by persistInHacker** [comment]
The final conclusion is caused by the company's encryption client. Thank you!

**Comment by persistInHacker** [comment]
The final conclusion is caused by the company's encryption client. Thank you!
