### ISSUE TITLE
How to configure low latency

### ISSUE THREAD

**Issue by LinHuiG** [netty/netty#13001]
I came across a scene like this. Ten TCP connections received a large number of requests and responses. We decode from the netty-work thread, submit the task to another thread, and call writeAndFlash when the task is completed. task has a 30us delay.

I found through tcpdump packet capture that the latency between request and response is very erratic. The delay ranges from 70us to 3000000us, and there is a certain regularity in the chronological order.

I've kernel the netty-Work thread and bang the task execution thread（affinity）
Were there any other points that I didn't notice

**Comment by LinHuiG** [comment]
[data.xlsx](https://github.com/netty/netty/files/10017373/data.xlsx)

**Comment by xiaoyifang** [comment]
I guess the delay was caused the you business logic .

submit the task to another thread,  **takes the delayed time to execute the task **  and call writeAndFlash when the task is completed.

**Comment by LinHuiG** [comment]
> 

I tested the task submission delay and execution delay, and they add up to 30us. That is to say, it is about 30us between receiving the request from netty and the writeAndFlash response

**Comment by LinHuiG** [comment]
> > I guess the delay was caused by you business logic .
> > submit the task to another thread, **takes the delayed time to execute the task** and call writeAndFlash when the task is completed.
> 
> I tested the task submission delay and execution delay, and they add up to 30us. That is to say, it is about 30us between receiving the request from netty and the writeAndFlash response I used cpu affinity+isolcpus+disruptor

submit task takes delay about 1us

**Comment by LinHuiG** [comment]
Maybe I know the reason, the client is not bound to the CPU, resulting in pulse traffic, and the server receives a large number of packets in an instant
