### ISSUE TITLE
netty dubbojson read timeout

### ISSUE THREAD

**Issue by chenatgit** [netty/netty#13000]
### Expected behavior
my project rpc frame isdubbo 2.7.0, use dubbo protocol sent json data, request and response without timeout
### Actual behavior
i has dev and test two env that delpoy with k8s cluster.

dev: 
rpc frame : dubbo 2.7.0
protocol:dubbo JVM 
version:open jdk1.8 
operate system : redhat 8.5 

kernel config: 
kernel.sysrq=1 
vm.swappiness=10 
net.ipv4.ip_forward=1 
net.bridge.bridge-nf-call-iptables=1 
net.ipv4.neigh.default.gc_thresh1=4096 
net.ipv4.neigh.default.gc_thresh2=6144 
net.ipv4.neigh.default.gc_thresh3=8192

test: 
rpc frame : dubbo 2.7.0 
protocol:dubbo 
JVM version:open jdk1.8 
operate system : redhat 7.9 

kernel config: 
kernel.sysrq=1 
net.ipv4.ip_forward=1 
net.bridge.bridge-nf-call-iptables=1 
net.ipv4.neigh.default.gc_thresh1=4096 
net.ipv4.neigh.default.gc_thresh2=6144 
net.ipv4.neigh.default.gc_thresh3=8192

with my project updata lib, but netty was still in 4.1.25version,when i deploy to test on k8s pod , it will throw an timeout exception via dubbojson.

however it was work well on dev. or update netty version to 4.1.71 on redhat 7.9.

the tcpdump that i get of netty4.1.25 on test env show everthing was normal
ie:
 docker container (psh ack)--->provider 
provider (psh ack)--->docker container 
docker (ack) ---> provider

tcpdump show data had been reccived and ack to provider,but netty was timeout to read data.

begin, i was think that may be it was netty version too lower has compatiable operation system version. 

so i use two server ,one os is redhat7.9, anther os is redhat8.5,both installed docker i pull image(problematic) delpoy on both server , the timeout not exists anymore.

after test, that was wrong.

### Netty version
4.1.25
### JVM version (e.g. `java -version`)
jdk 1.8
### OS version (e.g. `uname -a`)
redhat7.9 and redhat8.5

**Comment by normanmaurer** [comment]
Sorry but we need a reproducer or more infos etc.
