### ISSUE TITLE
A problem was encountered during the process of learning the source code

### ISSUE THREAD

**Issue by sqddk** [netty/netty#13006]
In "io.netty.util.internal.ReferenceCountUpdater # retain0", I can 't understand how this place was written.
`if ((oldRef <= 0 && oldRef + rawIncrement >= 0) || (oldRef >= 0 && oldRef + rawIncrement < oldRef))`
Can anyone told me the reason? Or is this place written by fault?

**Comment by chrisvest** [comment]
It deals with integer overflow.
