### ISSUE TITLE
包缺失异常

### ISSUE THREAD

**Issue by xuwanle** [netty/netty#13019]
<img width="604" alt="image" src="https://user-images.githubusercontent.com/37920211/204075911-9d05f25f-09a3-410c-89e4-43f7107d1492.png">

**Comment by needmorecode** [comment]
See [this link](https://blog.csdn.net/weixin_42765516/article/details/105767951) for reference.

**Comment by chrisvest** [comment]
As the link says, you just need to run a "generate sources" step with maven, e.g. via `mvn compile`, to get those classes.
