### ISSUE TITLE
udp socket leek

### ISSUE THREAD

**Issue by qqhai007** [netty/netty#13013]
### Expected behavior
udp socket not leek
### Actual behavior
udp socket   leek
### Steps to reproduce
Use lettcue to connect to the Redis,  
when use  io.netty.resolver.dns.DnsAddressResolverGroup  ,there is  udp socket  leek .

but  when I use io.netty.resolver.DefaultAddressResolverGroup ，there is no udp socket leek 

```shell
app@msmonitor-947d6f878-sh6dd:~/bin> lsof -i
COMMAND PID USER   FD   TYPE     DEVICE SIZE/OFF NODE NAME
java    590  app   37u  IPv4 1540893082      0t0  TCP msmonitor-947d6f878-sh6dd:55766->182.10.1.87:6830 (ESTABLISHED)
java    590  app   38u  IPv4 1540894345      0t0  UDP *:60714

```
### Minimal yet complete reproducer code (or URL to code)

```java
    static {
        boolean dnsResolverAvailable = LettuceClassUtils.isPresent("io.netty.resolver.dns.DnsAddressResolverGroup");
        Object group;
        if (dnsResolverAvailable) {
            logger.debug("Starting with netty's non-blocking DNS resolver library");
            group = AddressResolverGroupProvider.DefaultDnsAddressResolverGroupWrapper.INSTANCE;
        } else {
            logger.debug("Starting without optional netty's non-blocking DNS resolver library");
            group = DefaultAddressResolverGroup.INSTANCE;
        }

        ADDRESS_RESOLVER_GROUP = (AddressResolverGroup)group;
    }
```
### Netty version
4.1.76.final
### JVM version (e.g. `java -version`)
1.8.0
### OS version (e.g. `uname -a`)
x86_64 x86_64 x86_64 GNU/Linux

**Comment by qqhai007** [comment]
the  jar   is   netty-resolver-dns.4.1.76.Final

**Comment by hyperxpro** [comment]
Try the latest Netty version.

**Comment by qqhai007** [comment]
thank you
