### ISSUE TITLE
Why is LineBasedFrameDecoder not trying to reuse DelimiterBasedFrameDecoder implementation?

### ISSUE THREAD

**Issue by icankeep** [netty/netty#13023]
Hello!

### My question

When I read the source code, I found that LineBasedFrameDecoder is not based on DelimiterBasedFrameDecoder, but other additional codes. 

According to my understanding, when obtaining the LineBasedFrameDecoder object, it will be more concise to directly return a DelimiterBasedFrameDecoder object whose delimiters are \n and \r\n.

Why not, are there any additional considerations?

### Netty version
4.1

**Comment by icankeep** [comment]
I don't know if it is appropriate to put this question here, if not, I will close this issue

**Comment by deshanxiao** [comment]
In my opinion, LineBasedFrameDecoder is used to handle everything related to lines. This includes '\n' and '\r\n'. But DelimiterBasedFrameDecoder only used to handle the delimiter user specified.

We can see that DelimiterBasedFrameDecoder#isLineBased will determine whether to use the built-in lineBasedDecoder based on the parameter of constructor method. This actually means that DelimiterBasedFrameDecoder relies on LineBasedFrameDecoder.

**Comment by normanmaurer** [comment]
Like @deshanxiao said
