### ISSUE TITLE
Header values not validated after 4.1.82.Final

### ISSUE THREAD

**Issue by zageyiff** [netty/netty#13027]
### Expected behavior
Netty `4.1.82.Final` and previous versions were validating header names and values.
Which disables attacks such as cache-poisoning, cross-site scripting, cross-user defacement, page hijacking, cookie manipulation or open redirect. After `4.1.84.Final` no header value validation. (Had issues testing with `4.1.83.Final`)

The problem this method `io.netty.handler.codec.DefaultHeaders#setObject(K, java.lang.Iterable<?>)` validates the name via `validateName(nameValidator, false, name)` but does not validate the value, like done in the `io.netty.handler.codec.DefaultHeaders#set(K, java.lang.Iterable<? extends V>)`

This is a stack trace when the feature was working in `4.1.82.Final` as expected, a `null` character (`0x0`) being set in the header value.
```
java.lang.IllegalArgumentException: a header value contains a prohibited character '': en-US
	at io.netty.handler.codec.http.DefaultHttpHeaders$HeaderValueConverterAndValidator.validateValueChar(DefaultHttpHeaders.java:481) ~[netty-codec-http-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.codec.http.DefaultHttpHeaders$HeaderValueConverterAndValidator.convertObject(DefaultHttpHeaders.java:461) ~[netty-codec-http-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.codec.http.DefaultHttpHeaders$HeaderValueConverterAndValidator.convertObject(DefaultHttpHeaders.java:452) ~[netty-codec-http-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.codec.DefaultHeaders.setObject(DefaultHeaders.java:496) ~[netty-codec-4.1.79.Final.jar:4.1.79.Final]
	at io.netty.handler.codec.http.DefaultHttpHeaders.set(DefaultHttpHeaders.java:189) ~[netty-codec-http-4.1.79.Final.jar:4.1.79.Final]
	at org.springframework.http.client.reactive.ReactorClientHttpRequest.lambda$applyHeaders$3(ReactorClientHttpRequest.java:127) ~[spring-web-5.3.22.jar:5.3.22]
```

### Actual behavior
In Netty version `4.1.84.Final` and `4.1.85.Final`, header names are validated but not header values. In these versions the HTTP requests are served. See the Accept-Language header value containing a `null` character (`0x0`)
```
Web Client Request: 
Url: http://localhost:10275/resources
Method: GET
Headers: Accept: application/json, Accept-Charset: UTF-8, Accept-Language: en-US, Authorization: *****, 
```

### Steps to reproduce
Set a header value with an invalid character like `null` or `0x0`, `\t`, `\r`, `\v`, `\n`.
We're using spring reactor's webclient, which internally does this call to Netty set the headers `this.request.requestHeaders().set(key, value)`.
The problem this method `io.netty.handler.codec.DefaultHeaders#setObject(K, java.lang.Iterable<?>)` validates the name via `validateName(nameValidator, false, name)` but does not validate the value, like done in the `io.netty.handler.codec.DefaultHeaders#set(K, java.lang.Iterable<? extends V>)`

This is part of the stacktrace when setting a breakpoint in the `DefaultHeaders.setObject` method. 
[setObject:525, DefaultHeaders (io.netty.handler.codec)](https://github.com/netty/netty/blob/netty-4.1.85.Final/codec/src/main/java/io/netty/handler/codec/DefaultHeaders.java#L525)
[set:175, DefaultHttpHeaders (io.netty.handler.codec.http)](https://github.com/netty/netty/blob/netty-4.1.85.Final/codec-http/src/main/java/io/netty/handler/codec/http/DefaultHttpHeaders.java#L175)
[accept:-1, 757135059 (org.springframework.http.client.reactive.ReactorClientHttpRequest$$Lambda$1319)](https://github.com/spring-projects/spring-framework/blob/v5.3.24/spring-web/src/main/java/org/springframework/http/client/reactive/ReactorClientHttpRequest.java#L127)

### Netty version
`4.1.84.Final` and `4.1.85.Final`

### JVM version (e.g. `java -version`)
```
openjdk version "17.0.3.0.1" 2022-04-19 LTS
OpenJDK Runtime Environment SapMachine (build 17.0.3.0.1+7-LTS-sapmachine)
OpenJDK 64-Bit Server VM SapMachine (build 17.0.3.0.1+7-LTS-sapmachine, mixed mode)
```
### OS version (e.g. `uname -a`)
```
Darwin C02C3287MD6T 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64
```

**Comment by hyperxpro** [comment]
Interested in doing a PR?

**Comment by zageyiff** [comment]
@hyperxpro if I get some free time in between tasks I'll work on the PR, no promises :)

**Comment by chrisvest** [comment]
I think this is already being worked on, FYI.

**Comment by chrisvest** [comment]
@zageyiff yeah, no need to work on this. We got a fix on the way.
