### ISSUE TITLE
Update Netty to Java 17 

### ISSUE THREAD

**Issue by RodinDenis** [netty/netty#13020]
Is it possible to update Netty to the last features of Java 17?  

Spring 6 require a minimum of JDK 17 at runtime now.
I want to contribute this changes to Netty too, but I don't find a suitable branch.

**Comment by hyperxpro** [comment]
Not happening.

**Comment by RodinDenis** [comment]
The "main" branch is build against JDK 11. It's a good news. I hope that Netty 6 will be released with supported minimal version of JDK 17...

**Comment by chrisvest** [comment]
We routinely test with newer Java versions. We just can't make use of any new APIs or language features. But downstream projects are free to use newer Java.

**Comment by ijuma** [comment]
Given that Netty 5 is not out yet, Java 21 (next LTS) is due this year and Netty 4 will be supported for a while, it does make you wonder if Netty 5 should target should be 17 instead of 11. Especially if Netty 5 lasts 10+ years (like Netty 4).

Probably won't happen, but it's worth the question, at least. :)

**Comment by chrisvest** [comment]
There's not a lot of features that help us in Java 17, compared to Java 11. A few API additions to make one or two buffer operations a bit faster. I don't feel a strong need for records and sealed interfaces in our APIs.

The biggest impact I can see from moving to Java 17 is that the `SecurityManager` gets deprecated for removal in that version, so it would allow us to drop all the code related to it, and not run into trouble when it is eventually removed. However, we can work around that in other ways.

**Comment by ijuma** [comment]
For some reason, the following claims that Netty 5 will require Java 17 (along with many other projects):

https://youtu.be/NxpHg_GzpnY?si=vLaMLaz3f_qp8Hhq&t=409
