### ISSUE TITLE
Missing netty-transport-native-epoll for Apple Silicon

### ISSUE THREAD

**Issue by conteit** [netty/netty#13024]
Configured Maven Project for trying to create a Channel with Netty and UnixDomainSocket.  

<dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-epoll</artifactId>
            <version>4.1.85.Final</version>
            <classifier>${os.detected.classifier}</classifier>
</dependency>

### Expected behavior
Dependency successfully downloaded.

### Actual behavior

Maven fails saying: `Could not find artifact io.netty:netty-transport-native-epoll:jar:osx-aarch_64:4.1.85.Final in central (https://repo.maven.apache.org/maven2)`

### Minimal yet complete reproducer code (or URL to code)
Create a Maven project with pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.example</groupId>
    <artifactId>how-to-reproduce</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <properties>
        <java.version>17</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-epoll</artifactId>
            <version>4.1.85.Final</version>
            <classifier>${os.detected.classifier}</classifier>
        </dependency>
    </dependencies>

    <build>
        <extensions>
            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.7.0</version>
            </extension>
        </extensions>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>

```
Try to download dependencies.

NEEDED a Mac with Apple Silicon chip (mine is M2)

### Netty version
4.1.85.Final

### JVM version (e.g. `java -version`)
BellSoft Liberia Java 17

### OS version (e.g. `uname -a`)
macOS Ventura on Apple Silicon M2 Chip

**Comment by chrisvest** [comment]
Epoll is linux specific, hence we don't make MacOS binaries for it. On Mac, you want to use KQueue. The `Domain*Channel` classes are in `netty-transport-native-unix-common`.
