### ISSUE TITLE
Netty uses UDP

### ISSUE THREAD

**Issue by kana-cr** [netty/netty#13030]
Netty's NioDatagramChannel transfer limit in Java is 1472 bytes (obtained from tcpdump capture, the underlying layer of this method is jdk's DatagramChannelImpl send0 native method) This size is obviously too small for file transfer shards (SO_SNDBUF parameters do not work): Is there a good way ? Would appreciate documentation or a question～

**Comment by hyperxpro** [comment]
Do you want to transfer jumbo frames?

**Comment by chrisvest** [comment]
If you want to transfer big chunks of data, TCP is easier if you have that option. Or something else built on top of TCP, like HTTP. Otherwise you'll have to layer another protocol on top of UDP, such as QUIC.

**Comment by kana-cr** [comment]
Okay～ I'm ready to go to other options, thanks for the answer 🙏

> If you want to transfer big chunks of data, TCP is easier if you have that option. Or something else built on top of TCP, like HTTP. Otherwise you'll have to layer another protocol on top of UDP, such as QUIC.
