### ISSUE TITLE
Impossibility to modify ClientHello message

### ISSUE THREAD

**Issue by KVANTJVM** [netty/netty#13043]
### Expected behavior
Added handler before SSLHandler, that modifies ByteBuf containing ClientHello message allows successfull handshake.

### Actual behavior
The Handshake falls on "Client Handshake Finished" step, while checking if the message was tampered with or not.

If we'll try to print the sent messages of the Client, we can see that is succeeds until 
`14 03 03 00 01 01` packet, that means that the Client indicates that it has calculated the shared encryption keys and that all following messages from the client will be encrypted with the client write key.

The following step is "Client Handshake finished", which fails with throwing exception (using Bouncy Castle as a Provider):

`Caused by: javax.crypto.AEADBadTagException: mac check in GCM failed
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Caused by: javax.crypto.AEADBadTagException: mac check in GCM failed
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$AEADGenericBlockCipher.doFinal(Unknown Source)
	at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source)
	at java.base/javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:826)
	at java.base/javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2497)
	at java.base/sun.security.ssl.SSLCipher$T13GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1929)
	at java.base/sun.security.ssl.SSLEngineInputRecord.decodeInputRecord(SSLEngineInputRecord.java:240)
	at java.base/sun.security.ssl.SSLEngineInputRecord.decode(SSLEngineInputRecord.java:197)
	at java.base/sun.security.ssl.SSLEngineInputRecord.decode(SSLEngineInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	... 31 more`
	
This issue appears independently from any security provider.

### Steps to reproduce
1. Create basic ChannelOutboundHandlerAdapter.
2. Check for ClientHello header
3. Modify any bytes inside
4. Add it before SSL Handler
### Netty version
4.1.85 Final
### JVM version (e.g. `java -version`)
openjdk version "11.0.17" 2022-10-18
### OS version (e.g. `uname -a`)
Ubuntu 22.04

Possible solution for this can be using final ClientHello message that should be acquired from the handlers, for using not original but it in all following actions.

**Comment by hyperxpro** [comment]
Show code where you're modifying TLS Client Hello.

**Comment by KVANTJVM** [comment]
> Show code where you're modifying TLS Client Hello.

This is ChannelOutboundHandlerAdapter that I add to channel before SSLHandler
```
public class ClientHelloChannel extends ChannelOutboundHandlerAdapter {
    @Override
    public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) throws Exception {
        //Copy buf not to rewrite existing
        var buf = ((ByteBuf) msg).copy();

        var bytes = new byte[buf.readableBytes()];
        buf.readBytes(bytes);

        //Check if is ClientHello message with Handshake header
        if (bytes[0] != 22 && bytes[3] != 1) {
            //write original buffer
            super.write(ctx, msg, promise);
            return;
        }

        System.out.println("Original bytes:" + new String(Hex.encodeHex(bytes)));

        //Wrap ClientHello with model
        var hello = new ClientHello(bytes);

        //Add cipher as a sample
        hello.getCipherSuites().getCiphers().add(CipherSuite.TLS_AES_128_CCM_SHA256);

        //Get bytes and write it to buf
        var newBytes = hello.getBytes();

        System.out.println("Modified bytes: " + new String(Hex.encodeHex(newBytes)));

        //Clear old buf and write new bytes
        buf.clear().writeBytes(newBytes);

        //Write modified buf
        super.write(ctx, buf, promise);
    }
}

**Comment by KVANTJVM** [comment]
Note, that I wrap ClientHello bytes into model class. BTW, It fully works, passing original bytes and getting again works fully.
This is output of ClientHello bytes (before and after) request to https://www.google.com:
Before:
`16030301520100014e0303c52fde167668bdb42a272b860c12c53c3d21c28aa8a4f8942a3b1c7b7fbf157f20b5d49ac3ea3064b2c32fcabee2d260c5e068019f9df423414990c1bfd2ad335b0016c02cc02bc02fc030c013c014009c002f003513011302010000ef00000013001100000e7777772e676f6f676c652e636f6d000500050100000000000a00160014001d001700180019001e01000101010201030104000b00020100000d002c002a080708080403050306030804080508060809080a080b04010501060104020303030103020203020102020032002c002a080708080403050306030804080508060809080a080b04010501060104020303030103020203020102020011000900070200040000000000170000002b00050403040303002d00020101003300260024001d0020f0b7c6fb3828c78d3b7a378b5418926f6626fbca0a6f04b45a7331e769a91046ff01000100`

After:
`1603030154010001500303c52fde167668bdb42a272b860c12c53c3d21c28aa8a4f8942a3b1c7b7fbf157f20b5d49ac3ea3064b2c32fcabee2d260c5e068019f9df423414990c1bfd2ad335b0018c02cc02bc02fc030c013c014009c002f0035130113021304010000ef00000013001100000e7777772e676f6f676c652e636f6d000500050100000000000a00160014001d001700180019001e01000101010201030104000b00020100000d002c002a080708080403050306030804080508060809080a080b04010501060104020303030103020203020102020032002c002a080708080403050306030804080508060809080a080b04010501060104020303030103020203020102020011000900070200040000000000170000002b00050403040303002d00020101003300260024001d0020f0b7c6fb3828c78d3b7a378b5418926f6626fbca0a6f04b45a7331e769a91046ff01000100`

As we see it added valid bytes of cipher inside. It doesn't matter If I change cipher, or simple shuffle them or even modify 1 byte of client random, it results with exception on last step of Client Handshake (I do get ServerHello).

**Comment by HateMe02** [comment]
Have a similar problem

**Comment by KVANTJVM** [comment]
@hyperxpro any ideas to this matter? Is there any ability to handle integrity check error?

**Comment by hyperxpro** [comment]
Will check this soon.

**Comment by normanmaurer** [comment]
@KVANTJVM if this produces a correct client hello it should work... I dont see why it shouldn't. Are you sure the `ClientHello`.getBytes() actually does the correct thing in terms of generating the packet length / client hello message length ?

**Comment by normanmaurer** [comment]
Also is the exception be thrown on the client side or server side ?

**Comment by KVANTJVM** [comment]
@normanmaurer 
Yes, it produces 100% right result and all length calculations are done correctly (rechecked multiple times).
It doesn't fail on sending but fails on reading the server's message on one of the steps, failing with "mac check failed" (that is integrity check against MITMing the TLS traffic, maybe).

This is full successful handshake: https://pastebin.com/04S1dupU
This is what it is able to read and write while modifiying the bytes: https://pastebin.com/uLgFDC4a

Password: **nettyissue**

**Comment by KVANTJVM** [comment]
Corrupted ClientHello isn't accepted by server at all, while I get several handshakes and fail on mac check.
This issue is pretty important for me, I will be glad to hear opinions by you.

Thanks.

**Comment by KVANTJVM** [comment]
@normanmaurer pastebin staff decided to delete the pastes so I attach a file
[hello.txt](https://github.com/netty/netty/files/10261320/hello.txt)

**Comment by normanmaurer** [comment]
So I think there is nothing we can do about this as the `SSLEngine` itself does some verification. This is provided by the JDK itself.

**Comment by KVANTJVM** [comment]
@normanmaurer Verification should be 100%, in other case it would be big security hole. The solution for this error may be adding the ability to modify buffer when they are **constructed**, cause the ClientHello message that is sent is constructed on netty side and verification is made on initial buffer that netty constructed.

Like how it looks now:

CLIENT_HELLO_BYTES -> CONSTRUCT -> WRITE -> FLUSH
And when we modify it, it looks like: CLIENT_HELLO_BYTES -> CONSTRUCT -> WRITE -> **MODIFY** -> FLUSH

And then it fails, cause it checks the integrity with CLIENT_HELLO_BYTES

How I suggest to do this is:

CLIENT_HELLO_BYTES -> **MODIFY** -> CONSTRUCT -> WRITE -> FLUSH

Then the integrity check would be succeeded, because bytes are modified not on writing in the channel, but when the message is constructed.

I believe it would be good idea to add something like Handshake handler, cause It is not small problem, especially because of difference in JA3 fingerprints of HTTP clients and browsers, especially if you work with server that uses JA3 fingerprinting.
If you create own SSLSocketFactory with own SSLSocket implementation (or simply wrapping original and modifying startHandshake process). If you approach me to ClientHello handling (client side) in Netty Project, I believe I can try to make PR request, if not, I believe your team can implement it better than me.

**Comment by normanmaurer** [comment]
The `SSLEngine` does add the bytes to the buffer which is provided by OpenJDK and not netty itself. I have a hard time to see how we can change anything that is done inside it. What I am missing ?

**Comment by KVANTJVM** [comment]
> The `SSLEngine` does add the bytes to the buffer which is provided by OpenJDK and not netty itself. I have a hard time to see how we can change anything that is done inside it. What I am missing ?

`SSLEngine` by default is really restrictive. But you already provide own implementations (like `JdkSslEngine`) that wrap over default SSLEngine and in `beginHandshake` method you call wrapped engine's original method, while we can rewrite handshake process to add more scalability.
The same scenario as with SSLSockets and custom SSLSocketFactory.

**Comment by normanmaurer** [comment]
@KVANTJVM I think this is not really something we want to provide.. You can do it by-yourself and inject the `SSLEngine` into the `SslHandler` constructor.

**Comment by KVANTJVM** [comment]
@normanmaurer Ok then, I believe we can close this issue as something that should user do himself.
