### ISSUE TITLE
Header value characters with codes greater than 255 are sent as question marks

### ISSUE THREAD

**Issue by TorinoSM** [netty/netty#13048]
### Expected behavior
Sending header value "ĀāĂăĄąĆćĈĉĊċČčĎďĐđĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħĨĩĪīĬĭĮįİıĲĳĴĵĶķĸĹĺĻļĽľĿŀŁłŃńŅņŇňŉŊŋŌōŎŏŐőŒœŔŕŖŗŘřŚśŜŝŞşŠšŢţ"

Getting header value "ĀāĂăĄąĆćĈĉĊċČčĎďĐđĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħĨĩĪīĬĭĮįİıĲĳĴĵĶķĸĹĺĻļĽľĿŀŁłŃńŅņŇňŉŊŋŌōŎŏŐőŒœŔŕŖŗŘřŚśŜŝŞşŠšŢţ"

### Actual behavior
Sending header value "ĀāĂăĄąĆćĈĉĊċČčĎďĐđĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħĨĩĪīĬĭĮįİıĲĳĴĵĶķĸĹĺĻļĽľĿŀŁłŃńŅņŇňŉŊŋŌōŎŏŐőŒœŔŕŖŗŘřŚśŜŝŞşŠšŢţ"

Getting header value "????????????????????????????????????????????????????????????????????????????????????????????????????"

### Steps to reproduce
Run the "test" in the attached project
[web-client-headers-encoding.zip](https://github.com/netty/netty/files/10228080/web-client-headers-encoding.zip)

### Minimal yet complete reproducer code (or URL to code)
Please see attached project
[web-client-headers-encoding.zip](https://github.com/netty/netty/files/10228080/web-client-headers-encoding.zip)

### Netty version
4.1.85

### JVM version (e.g. `java -version`)
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

### OS version (e.g. `uname -a`)
Darwin cab-wsm-0706774 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

**Comment by chrisvest** [comment]
HTTP header values can only be US-ASCII. See https://tools.ietf.org/html/rfc7230#section-3.2 where `VCHAR` is [any
   visible USASCII character](https://www.rfc-editor.org/rfc/rfc7230#section-1.2), and [obs-text is %x80-FF](https://www.rfc-editor.org/rfc/rfc7230#section-3.2.6).
