### ISSUE TITLE
Remote parsing of the dns

### ISSUE THREAD

**Issue by 2259289435** [netty/netty#13050]
### Expected behavior
Local dns could not identify the intranet domain name，Want to parse the dns remotely by socks5 or other methods
### Actual behavior
Local parsing of the dns
### Minimal yet complete reproducer code (or URL to code)
```
public void customize(Config configuration) {
            configuration.setNettyHook(new DefaultNettyHook(){
                @Override
                public void afterBoostrapInitialization(Bootstrap bootstrap) {
                }

                @Override
                public void afterChannelInitialization(Channel channel) {
                    String socksProxyHost = System.getProperty("customSocksProxyHost");
                    int socksProxyPort = Integer.parseInt(System.getProperty("customSocksProxyPort", "1080"));
                    if(!Strings.isNullOrEmpty(socksProxyHost)){
                        Socks5ProxyHandler socks5ProxyHandler = new Socks5ProxyHandler(new InetSocketAddress(socksProxyHost, socksProxyPort));
                        channel.pipeline().addFirst(socks5ProxyHandler);
                    }
                }
            });
        }


io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'Intranet.domain.name.com' and search domain query for configured domains failed as well: [lan]
```
### Netty version
4.1.84
### JVM version (e.g. `java -version`)
1.8

### OS version (e.g. `uname -a`)
window

**Comment by normanmaurer** [comment]
I dont understand the problem... Please provide more details.

**Comment by trustin** [comment]
I think he wants the target host name resolved by the proxy server rather than by the client. To achieve that, you need to specify an 'unresolved` `InetSocketAddress`, using `InetSocketAddress.createUnresolved()`: https://docs.oracle.com/javase/8/docs/api/java/net/InetSocketAddress.html#createUnresolved-java.lang.String-int-

**Comment by normanmaurer** [comment]
Closing this.
