### ISSUE TITLE
Netty classloading duplicate calls to NetworkInterface.getNetworkInterfaces()

### ISSUE THREAD

**Issue by anudeepg** [netty/netty#13054]
### Expected behavior

Can we avoid this duplicate call by caching NetUtil loaded network interfaces 
and adapt MacAddressUtil to call NetUtil.getNetworkInterfaces() ? 

### Actual behavior
MacAddressUtil,bestAvailableMac() method is calling once NetworkInterface.getNetworkInterfaces()
But just before its triggering also NetUtil class loading that's invoking static method where NetworkInterface.getNetworkInterfaces() is called.  

![NettyDupCalls](https://user-images.githubusercontent.com/1820647/207843989-486cda44-339e-48b4-9633-54fc5bfd299c.PNG)

It's causing slowness for us during Grpc bootstrap process. 

### Steps to reproduce
Call MacAddressUtil,bestAvailableMac()

### Netty version
Latest 

### JVM version (e.g. `java -version`)
1.8

### OS version (e.g. `uname -a`)
Windows 10

**Comment by normanmaurer** [comment]
Should be "fixed" by https://github.com/netty/netty/pull/13060

**Comment by normanmaurer** [comment]
There is no planed date yet
