### ISSUE TITLE
netty is adding content-length=0 header in 204 response

### ISSUE THREAD

**Issue by BrahmKauntey** [netty/netty#13069]
### Expected behavior
A server MUST NOT send a Content-Length header field in any response
   with a status code of 1xx (Informational) or 204 (No Content).  A
   server MUST NOT send a Content-Length header field in any 2xx
   (Successful) response to a CONNECT request

### Actual behavior
netty is adding content-length=0 header in 204 response

### Steps to reproduce
Run a http request/response with response code 204.

### Minimal yet complete reproducer code (or URL to code)
        @Override
        @RequestMapping("/**")
        public ResponseEntity<?> handleReq(RequestEntity<byte[]> reqEntity,
                        @RequestHeader HttpHeaders reqHeaders) {
                HttpHeaders responseHeaderMap = new HttpHeaders();
                responseHeaderMap.set("abc11", "xyz11");
                responseHeaderMap.set("abc12", "xyz12");
                responseHeaderMap.set("abc13", "xyz13");
                responseHeaderMap.set("abc14", "xyz14");

                return (new ResponseEntity<byte[]>(responseHeaderMap, HttpStatus.NO_CONTENT));
        }

### Netty version
4.1.82

### JVM version (e.g. `java -version`)
jdk:17.0.5

### OS version (e.g. `uname -a`)
Linux 4.14.35-1818.3.3.el7uek.x86_64

**Comment by hyperxpro** [comment]
Is Netty doing that or Spring?

**Comment by dggcv** [comment]
any chance this is related to #12760 ?

**Comment by dggcv** [comment]
Any chance this is related to https://github.com/netty/netty/pull/12921?

**Comment by normanmaurer** [comment]
Sorry but we need more info here. I suspect its spring that is doing this as need does not add this kind of headers automatically.
