### ISSUE TITLE
MqttDecoder IndexOutOfBoundsException

### ISSUE THREAD

**Issue by chenmeng1994** [netty/netty#13078]
https://github.com/netty/netty/blob/bc49c4b1464c8345bf87b3053b3adefa64f91530/codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttDecoder.java#L231

Please ask, is there no exception here?

I see that the readable bytes are not checked in front of the code.

for example：
       remaining：  0x80, 0x80, 0x01
       But tcp is delivered for the first time ：0x80, 0x80

**Comment by normanmaurer** [comment]
It's using the `ReplayingDecoder` so there is no problem.
