### ISSUE TITLE
OpenSslEngine fails the TLSv1.3 handshake in some configurations

### ISSUE THREAD

**Issue by kwart** [netty/netty#13073]
### Expected behavior
TLS handshake finishes successfully.

### Actual behavior
OpenSSL / TLS 1.3 handshake fails to complete when mutual authentication is enabled, and the default `TrustManagerFactory` is used.

With this configuration client's `SSLEngine` reports `BUFFER_OVERFLOW`for the `unwrap()` operation and
the value of `SSLSession.getApllicationBufferSize()` got increased.

Even if we try to increase the application buffer size, there is a subsequent issue with the `BUFFER_UNDERFLOW` for the `wrap()` operation.

### Minimal yet complete reproducer code (or URL to code)
https://github.com/kwart/test-app/tree/netty-tcnative-default-truststore-issue

### Netty version
```xml
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>2.0.54.Final</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-handler</artifactId>
            <version>4.1.84.Final</version>
        </dependency>
```

### JVM version (e.g. `java -version`)
Tested with Java 8 and 11 (Azul Zulu).

### OS version (e.g. `uname -a`)
Ubuntu 22.04, 5.15.0-56-generic, x86_64

**Comment by kwart** [comment]
The reproducer: 
[netty-13073.zip](https://github.com/netty/netty/files/10286453/netty-13073.zip)

**Comment by normanmaurer** [comment]
Checking
