### ISSUE TITLE
NioByteUnsafe.read  in eventloop fail

### ISSUE THREAD

**Issue by jr981008** [netty/netty#13096]
### Actual behavior
![image](https://user-images.githubusercontent.com/20749545/210696281-75c15ff3-1e82-4166-b1ae-977ca75fcdd7.png)
![image](https://user-images.githubusercontent.com/20749545/210696424-b52fc833-29b1-42f4-8c6d-ead1e4713d7a.png)

We have 600 tcp clients full connection 400tcp servers.
One client Nioeventloop thread psConnect4  unsafe.read buffer overlimit in a short period of time, for multiple tcp servers. This is not business code and I searched known issues and found no similar errors. I'm not sure how to fix it.
600+ server cluster runs for 30 days, only one produced the problem in a few minutes.All other clients and servers full connections are normal at same time.

### Steps to reproduce
No idea to reproduce.
### Netty version
4.1.74
### JVM version (e.g. `java -version`)
openjdk 1.8.0_272
### OS version (e.g. `uname -a`)
linux 4.19.36 aarch64

**Comment by normanmaurer** [comment]
Thats interesting... can you upgrade to the latest netty / java8 release and tell us if you still see the issue on this one node ?

**Comment by jr981008** [comment]
Is it possible that I usedthe pooled buffer  incorrectly  causing the problem? Is the buffer used here be used by bussuness code before write?

**Comment by normanmaurer** [comment]
In theory this could be possible... like you release it and but still use it and the pool pick it up again.

**Comment by normanmaurer** [comment]
Closing this
