### ISSUE TITLE
A typo on the netty home page

### ISSUE THREAD

**Issue by PengzhengHe** [netty/netty#13092]
### Expected behavior
Netty is an NIO client server framework....
### Actual behavior
Netty is a NIO client server framework...
![image](https://user-images.githubusercontent.com/86673652/210338019-8fa81a51-fe58-4af6-a4fd-a7bdebfd035c.png)

**Comment by jchrys** [comment]
I think both are correct since NIO can be pronounced either 'nee-oh' or 'en-eye-oh'.

**Comment by chrisvest** [comment]
Pushed a fix
