### ISSUE TITLE
Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.14:build (build-native-lib) on project netty-resolver-dns-native-macos: build failed: org.apache.maven.plugin.MojoExecutionException: ./configure failed with exit code: 1

### ISSUE THREAD

**Issue by superRainGit** [netty/netty#13103]
### Expected behavior

compile success

### Actual behavior

Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.14:build (build-native-lib) on project netty-resolver-dns-native-macos: build failed: org.apache.maven.plugin.MojoExecutionException: ./configure failed with exit code: 1

(skip)
checking whether the gcc linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
[INFO] checking dynamic linker characteristics... darwin20.6.0 dyld
[INFO] checking how to hardcode library paths into programs... immediate
[INFO] checking whether stripping libraries is possible... yes
[INFO] checking if libtool supports shared libraries... yes
[INFO] checking whether to build shared libraries... yes
[INFO] checking whether to build static libraries... no
[INFO] configure: javac was on your path, checking to see if it's part of a JDK we can use...
[INFO] checking if '/usr' is a JDK... no
[INFO] configure: Taking a guess as to where your OS installs the JDK by default...
[INFO] checking if '/System/Library/Frameworks/JavaVM.framework' is a JDK... no
[INFO] configure: error: JDK not found. Please use the --with-jni-jdk option
[INFO] rc: 1

(skip...)

### Steps to reproduce

1、run `mvn clean -U install -DskipTests` at netty parent path then get the compile error

2、cd resolver-dns-native-macos and run `mvn clean -U install -DskipTests -X ` get the same compile error

### Netty version

4.1 

### JVM version (e.g. `java -version`)

java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

### OS version (e.g. `uname -a`)

Darwin Kernel Version 20.6.0: root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

###  I'm trying...

I config the JAVA_HOME and execute echo $JAVA_HOME can print the root path of java, but the log print with -X show

(skip......)
checking if '/usr' is a JDK... no
[INFO] configure: Taking a guess as to where your OS installs the JDK by default...
[INFO] checking if '/System/Library/Frameworks/JavaVM.framework' is a JDK... no
[INFO] configure: error: JDK not found. Please use the --with-jni-jdk option
(skip......)

not use PATH's JAVA_HOME, how can i resolve this compile error?

**Comment by superRainGit** [comment]
> Show us what is in `JAVA_HOME`

/Library/Java/JavaVirtualMachines/jdk1.8.0_281.jdk/Contents/Home

**Comment by normanmaurer** [comment]
Seems like for whatever reason it thinks it is set to `/System/Library/Frameworks/JavaVM.framework`
`

**Comment by superRainGit** [comment]
> Seems like for whatever reason it thinks it is set to `/System/Library/Frameworks/JavaVM.framework`

I see the log， but i don know how can i specify the `$JAVA_HOME` location when compile,   have you some suggestions?

**Comment by normanmaurer** [comment]
```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_281.jdk/Contents/Home
./mvnw clean -U install -DskipTests
```

**Comment by superRainGit** [comment]
> ```
> export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_281.jdk/Contents/Home
> ./mvnw clean -U install -DskipTests
> ```

Ok, I'll try

**Comment by chrisvest** [comment]
I'm guessing this can be closed since we did not hear back.
