### ISSUE TITLE
FlowControlHandler is passing read events when auto-reading is turned off

### ISSUE THREAD

**Issue by ivanangelov** [netty/netty#13104]
### Expected behavior
Not passing read events onto the pipeline (calling ctx.read() which results in reading from the client socket) when the queue is not empty and auto-reading is turned off for the channel. I would suggest that the expected behavior should look something like the following piece of code:
```
if (dequeue(ctx, 1) == 0) {
	shouldConsume = true;
	ctx.read();
} else if (ctx.channel().config().isAutoRead()) {
	ctx.read();
}
```

### Actual behavior
Read events are passed onto the pipeline in every case regardless of the auto-reading configuration of the channel.

### Steps to reproduce
1. Let's suppose we have a channel with a FlowControlHandler in its pipeline.
2. Turn auto-reading off for the channel.
3. Manually call ctx.read()
4. For every ctx.read() call, the FlowControlHandler's read method will pass the read event onto the pipeline which will result in reading from the client socket.
5. If the messages, which we read are not processed fast enough according to our custom logic, all of this can lead to a significant amount of data being stored in memory which leads to out-of-memory errors.

### Minimal yet complete reproducer code (or URL to code)
n/a

### Netty version
4.1.85.Final and above

### JVM version (e.g. `java -version`)
any

### OS version (e.g. `uname -a`)
any

**Comment by normanmaurer** [comment]
@ivanangelov can you do a PR with the suggested changes and a unit test ? We love contributions
