### ISSUE TITLE
CloseWebSocketFrame statusCode() get unexpected results

### ISSUE THREAD

**Issue by zhangjinying** [netty/netty#13113]
Set the  CloseWebSocketFrame code to 60000, and the result obtained by statusCode() is negative;

The WebSocket protocol states that Code is  a 2-byte unsigned integer (in network byte order)，But netty acquisition is obtained by signs.
![image](https://user-images.githubusercontent.com/11245691/211527112-5c0f2923-c6ba-4d29-9d4b-da5b228dcbdd.png)

![image](https://user-images.githubusercontent.com/11245691/211527879-19400bf7-f95c-4394-8301-8e3567245e63.png)

Here, getShort should be changed to getUnsignedShort.

Minimal yet complete reproducer code (or URL to code)
Netty version
4.1.80

JVM version (e.g. java -version)
openjdk 1.8.0_272

OS version (e.g. uname -a)
linux 4.19.36 aarch64

**Comment by normanmaurer** [comment]
@zhangjinying can you do a PR with the change and a test ?

**Comment by zhangjinying** [comment]
> @zhangjinying can you do a PR with the change and a test ?

👌
