### ISSUE TITLE
Use of install_tool_name triggers Command Line Tools installation and crashes for some macOS users

### ISSUE THREAD

**Issue by liamsharp** [netty/netty#13125]
### Expected behavior

No Command Line Tools pop up / no crashing.

### Actual behavior

Command line tools popup and and sometimes a crash.

### Steps to reproduce

Our product, [Screaming Frog SEO Spider](https://www.screamingfrog.co.uk/seo-spider/), integrates with Google Analytics 4 which uses netty. When users authorise they get the following pop up, shown here with our application for context:

<img width="894" alt="Screenshot 2023-01-05 at 11 41 46" src="https://user-images.githubusercontent.com/6429288/210774826-3d676b1d-5ebf-49ba-956e-ceabc5c7ee05.png">

This is confusing for users - they have no idea what "install_name_tool" is and why they would need it. If they accept this dialog Command Line Tools is installed. If they click cancel they can continue and everything works as expected.

However, we have had 5 users who have experienced a crash at this point. This is not a crash in Java application code, but in some native code causing a JVM exit, triggering a send to Apple dialog. We have logs for 2 of these cases:

- [103165.txt](https://github.com/googleapis/google-cloud-java/files/10352522/103165.txt)
- [104866.txt](https://github.com/googleapis/google-cloud-java/files/10352523/104866.txt)

Asking users to uninstall Command Line Tools resolved the issue in both cases, we are still waiting on feedback from the third.

For us it's unexpected behaviour for the `AnalyticsAdminServiceClient` to be triggering/requiring the installation of Command Line Tools, and a further issue that this sometimes crashes.

### Minimal yet complete reproducer code (or URL to code)

I haven't created this.

### Netty version

`grpc-netty-shaded-1.48.0.jar`

### JVM version (e.g. `java -version`)

```
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode)
```

### OS version (e.g. `uname -a`)

Any version of mac OS.

### Misc

We've chased the google-cloud-java team directly here https://github.com/googleapis/google-cloud-java/issues/8948 but haven't got very far. Do you have any suggestions on how to progress this issue? Or do you see this as a problem for the google-cloud-java team to handle?

**Comment by normanmaurer** [comment]
You can disable the usage of install_tool by: `-Dio.netty.native.tryPatchShadedId=false`. You might need to adjust the property name to match the shaded package tho.

**Comment by liamsharp** [comment]
@normanmaurer thanks for looking at this, much appreciated!

I've set `io.netty.native.tryPatchShadedId` as suggested but we're still getting the pop up. I've verified in our own code that the property is set correctly by logging the following and checking it's false:

        final boolean TRY_TO_PATCH_SHADED_ID = SystemPropertyUtil.getBoolean(
            "io.netty.native.tryPatchShadedId", true);
        LOGGER.info("-Dio.netty.native.tryPatchShadedId: {}", TRY_TO_PATCH_SHADED_ID);

We're aren't shading, we just have a lib/ folder containing all the jars we depend on.

I'd like to be able to enable the netty logging, but I can't see how to enable that? We're using Log4j in our application.

I'd also like to double check the source code of the version we're using. It looks like the sources aren't published to maven as Eclipse isn't automatically downloading them. When trying to locate them manually I'm confused by the version numbers. Via `com.google.analytics:google-analytics-admin:0.13.0` we have a dependancy on `io.grpc:grpc-netty-shaded:jar:1.48.0`. Looking on maven central [here](https://mvnrepository.com/artifact/io.grpc/grpc-netty-shaded) the version numbers tally with what we're using. How do these correlate to the [tags](https://github.com/netty/netty/tags) for the project?

**Comment by normanmaurer** [comment]
@liamsharp you will need to ask in the grpc issue tracker ... I am not sure how they are shading (which package name they use etc).

**Comment by liamsharp** [comment]
Thanks @normanmaurer .

I'm not 100% sure how all this hangs together, but after decompiling the `grpc-netty-shaded-1.48.0.jar` and looking at the code I could see that the correct property name to set was `io.grpc.netty.shaded.io.netty.native.tryPatchShadedId` - setting this resolves the issue for us and our Google integration works correctly.
