### ISSUE TITLE
netty thread was infinite loop in BaseMpscLinkedArrayQueue.poll

### ISSUE THREAD

**Issue by Musknine** [netty/netty#13137]
### Expected behavior
spring cloud gateway shoud comsume new requests.

### Actual behavior
i'm using spring cloud bulding a project,the gateway was spring cloud gateway which using [webflux ](web-application-type: reactive),and it's runing on netty. after about in 48 hours, the gateway didn't work. the process is runing,but it didn't accept new request anymore.
after did some analysises,i got some clues below:
accept queue overflows:
two days later,the queue is always full.
![accept_queue](https://user-images.githubusercontent.com/89766728/213392532-10e252b0-6473-4903-a6e4-6c60fa591d34.png)
also,i killed some tcp link manually,but the process didn't consume.

top threads is using cpu:
![top](https://user-images.githubusercontent.com/89766728/213393402-1f22de2e-1db8-41c1-a7e6-9153703b4b75.png)
accoding to the cpu usage by the threads that appears reactor threads is in the infinite loop(the details can find in the thread file below):
"reactor-http-nio-1" #42 daemon prio=5 os_prio=0 tid=0x0000ffff7ce24000 nid=0x4015 runnable [0x0000ffff48bbd000]
   java.lang.Thread.State: RUNNABLE
	at io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueue.poll(BaseMpscLinkedArrayQueue.java:340)
	at io.netty.util.internal.shaded.org.jctools.queues.MpscUnboundedArrayQueue.poll(MpscUnboundedArrayQueue.java:23)
	at io.netty.util.concurrent.SingleThreadEventExecutor.pollTaskFrom(SingleThreadEventExecutor.java:215)
	at io.netty.util.concurrent.SingleThreadEventExecutor.pollTask(SingleThreadEventExecutor.java:210)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:459)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
![image](https://user-images.githubusercontent.com/89766728/213394505-2245a6cf-4a27-4aeb-bda5-3bf4ed80be20.png)

DirectMemory usage is in an appropriate,about 83M:
![image](https://user-images.githubusercontent.com/89766728/213395223-5eb73fe0-4dab-42fe-bd95-506a08b7bf98.png)

jvm heap was fine:
![image](https://user-images.githubusercontent.com/89766728/213396690-c0925fbe-9a7d-4c09-939e-8c0f252e3c18.png)

this is thread file:
[gateway_thread.txt](https://github.com/netty/netty/files/10454788/gateway_thread.txt)

### Steps to reproduce
Couldn't reproduce

### Netty version
4.1.74

### JVM version (e.g. `java -version`)
Java HotSpot(TM) 64-Bit Server 1.8.0_341

### OS version (e.g. `uname -a`)
CentOS Linux release 7.5.1804 (AltArch)
Linux minio1 4.14.0-49.el7a.aarch64

Could anyone give me some advice?  thanks

**Comment by franz1981** [comment]
Please update to a way more recent version of JDK: it's very likely that it depends but it, because as per my understanding I cannot see any problem in such queue (disclaimer: I am a JCTools developer and @nitsanw is the main author).
I believe is possible to configure Netty in order to not use it, but I don't have my laptop at hand (I am travelling now), @normanmaurer ?

**Comment by Musknine** [comment]
It's not easy update to a more recent JDK version in pro evn. I want to find out why this happend then,get a solution to resolve the problem depends on the true bug is found out.   thank you.

**Comment by Musknine** [comment]
#11956   seems like this issue.   the machine has 4 cpu cores,3 threads was in infinite loop(reactor thread).   jdk1.8.x

**Comment by normanmaurer** [comment]
@nitsanw FYI..

**Comment by normanmaurer** [comment]
I agree with @franz1981 here... I think the most likely is a JDK bug.

**Comment by nitsanw** [comment]
> Java™ SE Development Kit 8, Update 341 (JDK 8u341). July 19, 2022.

This is not a super old version of 8, I would expect this to work.

> Netty 4.1.74 -> Feb 2023

So Netty version is a little old, but the JCTools version is 3.1.0 which same as latest.

The code in question has been changed in later versions:
```
    public E poll()
    {
        final E[] buffer = consumerBuffer;
        final long cIndex = lpConsumerIndex();
        final long mask = consumerMask;

        final long offset = modifiedCalcCircularRefElementOffset(cIndex, mask);
        Object e = lvRefElement(buffer, offset);
        if (e == null)
        {
            long pIndex = lvProducerIndex();
            // isEmpty?
            if ((cIndex - pIndex) / 2 == 0)
            {
                return null;
            }
            // poll() == null iff queue is empty, null element is not strong enough indicator, so we must
            // spin until element is visible.
            do
            {
                e = lvRefElement(buffer, offset);
            }
            while (e == null);
        }

        if (e == JUMP)
        {
            final E[] nextBuffer = nextBuffer(buffer, mask);
            return newBufferPoll(nextBuffer, cIndex);
        }

        soRefElement(buffer, offset, null); // release element null
        soConsumerIndex(cIndex + 2); // release cIndex
        return (E) e;
    }
```
The difference is due to a bug fix making `isEmpty` and `poll` consistent by reporting an empty queue during a potential producer transition to a new chunk. This is unlikely to make a difference in this case.

Note also that this is happening on `aarch64` which is a relatively new distro flavour. Can you please report the JVM vendor and CPU model?

This might be a JCTools bug exposed through ARM, or a JVM bug in the ARM distro exposed through JCTools :-)

**Comment by franz1981** [comment]
Oh gosh @nitsanw and I now remember I have worked with you on this one (code reviewing on my side)...I am getting old and memory start to fade away :)

**Comment by Musknine** [comment]
> Note also that this is happening on aarch64 which is a relatively new distro flavour. Can you please report the JVM vendor and CPU model?

@nitsanw  @franz1981 
Sometimes,there are some crash file,it includes some infos, like below:
JVM crash file:
[hs_err_pid1210.log](https://github.com/netty/netty/files/10471393/hs_err_pid1210.log)

dmidecode:
![image](https://user-images.githubusercontent.com/89766728/213841228-bdadf546-f732-418b-8d25-ddefc5e2d0cd.png)

but back to the infinite loop problem,the process haven't crash. It's running now(because i want to find out the bug,i keep it now).Another clues I think shoud be mentioned is the bug fired when using gateway to proxy files(images) stream(we have many jar,one is servered for file,image,that save in minio cluster,but proxy by spring cloud gateway),but I'm not sure.now,the problem haven't fired now,I have chaged the reactor model in spring cloud gateway，about 48 hours(i chaged intuitively ).

Need any other infomations,please @ me.   Thanks

**Comment by nitsanw** [comment]
@Musknine You are using QEMU, which is an emulator, not a real CPU.
I also can't quite see which JVM vendor you are using. Where did the JVM binary come from?

**Comment by Musknine** [comment]
@nitsanw 
JVM:
Java HotSpot(TM) 64-Bit Server VM (25.341-b10) for linux-aarch64 JRE (1.8.0_341-b10), built on Jun 16 2022 15:58:55 by "java_re" with gcc 7.3.0

CPU:
 Kunpeng 920

**Comment by nitsanw** [comment]
@Musknine where did you get the JVM binaries? Who is the vendor? Usually this is reported by `java -version` e.g. :
```
$ java -version
openjdk version "1.8.0_362"
OpenJDK Runtime Environment Corretto-8.362.08.1 (build 1.8.0_362-b08)
OpenJDK 64-Bit Server VM Corretto-8.362.08.1 (build 25.362-b08, mixed mode)
```

**Comment by xiezhaokun** [comment]
Can anyone provide a reproducible use case

**Comment by Musknine** [comment]
The problem did not happen anymore after i upgrade jdk to openjdk11, thanks all of you.

**Comment by yellowsand1** [comment]
I also encounter this problem. Version is 4.1.92.Final . We can rebuild this problem in various enviroment. I consider this a huge problem, please take this seriously instead of make us upgrade JDK .

**Comment by nitsanw** [comment]
@yellowsand1 I take all potential bugs in JCTools seriously. What version of the JDK are you on? I understand moving from 8 to 11 is a large effort, but updating to the latest update of the major version you are on is a reasonable ask.

**Comment by yellowsand1** [comment]
> @yellowsand1 I take all potential bugs in JCTools seriously. What version of the JDK are you on? I understand moving from 8 to 11 is a large effort, but updating to the latest update of the major version you are on is a reasonable ask.

Thx for reply. We r currently using OPENJDK-8u221 . We try netty-4.1.92-Final ,4.1.84.Final and 4.1.56.Final in one same enviroment. We accedently find that 4.1.92 will cause cpu 100% in pressure test , 4.1.84 cause shutdown without oom dump and cpu run up only to 15% . Without trace I cant give more detail. And 4.1.56 run stablely. So we change all our netty version to 4.1.56 . The reason why I dont wanna upgrade netty to latest version is that this problem occurs in spring-gateway production enviroment and is so urgent . And I seriously doubt that higher version would avoid this problem. Glad that we can stable our gateway for now .

**Comment by nitsanw** [comment]
> OPENJDK-8u221

Please update to LATEST update of JDK 8. This would be 8u391. Please use a reliable vendor (Zulu/Oracle/Corretto). This is critical, and blocking any further discussion. 

8u221 is from July 16, 2019, 4 years out of date JDK. I hope this is not an important system.

>  The reason why I dont wanna upgrade netty to latest version is that this problem occurs in spring-gateway production enviroment and is so urgent

I understand you are reluctant to make changes in production. We have no way of reproducing the issue you describe, and have every indication this is a JDK issue. I can not do anything for you if you can not try out recommended changes.

**Comment by yellowsand1** [comment]
> > OPENJDK-8u221
> 
> Please update to LATEST update of JDK 8. This would be 8u391. Please use a reliable vendor (Zulu/Oracle/Corretto). This is critical, and blocking any further discussion.
> 
> 8u221 is from July 16, 2019, 4 years out of date JDK. I hope this is not an important system.
> 
> > The reason why I dont wanna upgrade netty to latest version is that this problem occurs in spring-gateway production enviroment and is so urgent
> 
> I understand you are reluctant to make changes in production. We have no way of reproducing the issue you describe, and have every indication this is a JDK issue. I can not do anything for you if you can not try out recommended changes.

Thx for reply . My understand of this problem is that this is a enviroment issue  cause We only find this issue in container and arm64 enviroment..But I ll try different JDK version to reproduce this issue and as well other enviroment ro see if still happen.

**Comment by natl-set** [comment]
@yellowsand1  I'm quite curious if it still happens to you.

**Comment by natl-set** [comment]
> Is anyone else encountering this problem? We have encountered this many times in many applications.

which jdk do you use?

**Comment by yellowsand1** [comment]
> [@yellowsand1](https://github.com/yellowsand1) I'm quite curious if it still happens to you.

Yes,it still happends.And its easy to reproduce.But I figure it out by replacing versions of Netty , jdk, os.Truns out it only happends in lower version of netty and spcific brand of cpu which is Chinese cpu like Kunpeng. So if u meet this problem, try upgrade netty .

**Comment by franz1981** [comment]
> So if u meet this problem, try upgrade netty .

That's surprising: it is not instead related upgrading the Hotspot version instead?

**Comment by chrisvest** [comment]
> Truns out it only happends in lower version of netty and spcific brand of cpu

What Netty versions did you try? What's the oldest version you know of where it starts working?

**Comment by yellowsand1** [comment]
> > So if u meet this problem, try upgrade netty .
> 
> That's surprising: it is not instead related upgrading the Hotspot version instead?

I have not try diff jdk version yet,but according to reply above, it seems also work lol.
