### ISSUE TITLE
autoRead == false is sometimes ignored in Kqueue and Epoll sockets

### ISSUE THREAD

**Issue by kvr000** [netty/netty#13142]
### Expected behavior

When `autoRead == false`, Netty should not attempt to read data without explicit `ctx.read()` .

### Actual behavior

With `Nio`, it behaves correctly.  With `Kqueue` and `Epoll` and probably bigger amount of data, Netty starts reading data even though `autoRead == false` .

### Steps to reproduce

Simple Echo server with `halfClosure == true` and `autoRead == false` and socket implementation set to Kqueue and Epoll.  Although there is no `ctx.read()`, Netty still starts reading data.

### Minimal yet complete reproducer code (or URL to code)

https://github.com/kvr000/zbynek-netty-exp/tree/master/broken-autoread/ , with full documentation in README.md about strange behavior under different circumstances.

### Netty version

4.1.86.Final

### JVM version (e.g. `java -version`)

```
openjdk 17.0.5 2022-10-18 LTS
OpenJDK Runtime Environment Corretto-17.0.5.8.1 (build 17.0.5+8-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.5.8.1 (build 17.0.5+8-LTS, mixed mode, sharing)
```

### OS version (e.g. `uname -a`)

```
Darwin xyz 21.6.0 Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:13 PST 2022; root:xnu-8020.240.14~1/RELEASE_ARM64_T6000 arm64
```

Tested on Linux with Epoll too.

**Comment by normanmaurer** [comment]
This is kind of expected as auto read is just a hint. Both Epoll and Kqueue use edge-triggered and so it might need to read data to ensure there are no stales.

**Comment by kvr000** [comment]
Ok, thanks for the answer.  Is there then some way to protect overloading the server when the handlers are not ready yet to consume the data?  `FlowControlHandler` helps but it buffers all data and can run out of memory if client pushes the data too fast.

Also, it may be worth improving the `FlowControlHandler` to handle both data and UserTriggerredEvents such has ShutdownInput, as other the latter jumps the data.  I created my implementation to handle this and can eventually contribute to Netty `FlowControlHandler`, please let me know: https://github.com/kvr000/zbynek-java-exp/blob/master/netty-exp/netty4-exp/http-proxy/src/main/java/cz/znj/kvr/sw/exp/java/netty/netty4/proxy/common/netty/pipeline/FullFlowControlHandler.java
