### ISSUE TITLE
The problem of low efficiency and multiple cycles may occur in the TimeWheel Algorithm

### ISSUE THREAD

**Issue by 1294566108** [netty/netty#13166]
### Your Question
In the **HashedWheelTimer#normalizeTicksPerWheel** method, when the value of **ticksPerWheel** is large, the method will cycle many times, the method execution time is unstable, and the efficiency may be low.
![image](https://user-images.githubusercontent.com/91858554/215241258-f9ce7151-5185-46be-90ef-a42e57aa00a0.png)

### Your scenes
Use the relevant implementation of **java8 HashMap** to improve the algorithm.
The **HashedWheelTimer#normalizeTicksPerWheel** method achieves the same purpose as the method in **java8 HashMap**. Both can get a number greater than or equal to ticksPerWheel (and this number is a power of 2) and return.

### Your advice
The following algorithms can be used to improve efficiency：
int n = ticksPerWheel - 1;
n |= n >>> 1;
n |= n >>> 2;
n |= n >>> 4;
n |= n >>> 8;
n |= n >>> 16;
//Here 1073741824=2 ^ 30 to prevent overflow
return (n < 0) ? 1 : (n >= 1073741824) ? 1073741824 : n + 1;
Because the type of the parameter **ticksPerWheel** passed in by the **HashedWheelTimer#normalizeTicksPerWheel** method is [int], a total of **2 to the 31st power** has been calculated（16+8+4+2+1==31）. Since the maximum value of int type is the 31st power of 2, the input int type parameters can be moved to. There is no conversion failure caused by insufficient shift times.

**Comment by normanmaurer** [comment]
also @franz1981
