### ISSUE TITLE
websockets.exceptions.NegotiationError: Unsupported extension: name = permessage-deflate, params = []

### ISSUE THREAD

**Issue by ChatGPTT** [netty/netty#13176]
### Expected behavior
`validExtensions`List inside `io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler`  should be cleand after every request, otherwise it is leading to `Unsupported extension: name = premessage-deflate`
### Actual behavior
While I am sending requests to the WebSocket an exception was occurred by some requests: 
`Unsupported extension: name = premessage-deflate`
![image](https://user-images.githubusercontent.com/124066624/216022207-d4debff5-1605-49c2-92ef-84782388d9c7.png)
After debugging sessions it was noticed that the `validExtensions`List inside the method  `channelRead `in `io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler` had already an extension: `premessage-deflate` inside of it <see screenshot>
![image](https://user-images.githubusercontent.com/124066624/216064150-a717b462-2790-4b4f-849f-deaa650c375e.png)
in and the line 92 the extension was added again to the  validExtensions, which later lead to an exception in the method `checkDuplicateName `inside `io.netty.channel.DefaultChannelPipeline`.
So as a workaround I emptied the list validExtensions everytime the method chaneelRead was called and it worked fine for me, so I am asking here if I can use this workaround for now, and if some can support me with the case so we can find a solution together.
The Workaround:
![image](https://user-images.githubusercontent.com/124066624/216023280-9ff576f5-32e5-4313-9350-f64245e97fdd.png)

### Steps to reproduce
the fastest way to reproduce it for me was to make some WebSocket connection requests like 3-5 with correct credentials and then one time with incorrect credentials. repeating that like 2-3 times will lead to the exception. 
### Netty version
4.1.77
### JVM version (e.g. `java -version`)
Java 11
### Stacktrace
 "message": "An exception was thrown by io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler$1.operationComplete()",
    "level": "WARN",
    "loggerName": "io.netty.util.concurrent.DefaultPromise",
    "thrown": {
        "name": "java.lang.IllegalArgumentException",
        "message": "Duplicate handler name: io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoder",
        "localizedMessage": "Duplicate handler name: io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoder",
        "stackTrace": [
            {
                "class": "io.netty.channel.DefaultChannelPipeline",
                "method": "checkDuplicateName",
                "file": "DefaultChannelPipeline.java",
                "line": 1055
            },
            {
                "class": "io.netty.channel.DefaultChannelPipeline",
                "method": "filterName",
                "file": "DefaultChannelPipeline.java",
                "line": 284
            },
            {
                "class": "io.netty.channel.DefaultChannelPipeline",
                "method": "addAfter",
                "file": "DefaultChannelPipeline.java",
                "line": 301
            },
            {
                "class": "io.netty.channel.DefaultChannelPipeline",
                "method": "addAfter",
                "file": "DefaultChannelPipeline.java",
                "line": 290
            },
            {
                "class": "io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler$1",
                "method": "operationComplete",
                "file": "WebSocketServerExtensionHandler.java",
                "line": 142
            },
            {
                "class": "io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler$1",
                "method": "operationComplete",
                "file": "WebSocketServerExtensionHandler.java",
                "line": 133
            },
            {
                "class": "io.netty.util.concurrent.DefaultPromise",
                "method": "notifyListener0",
                "file": "DefaultPromise.java",
                "line": 578
            },
            {
                "class": "io.netty.util.concurrent.DefaultPromise",
                "method": "notifyListeners0",
                "file": "DefaultPromise.java",
                "line": 571
            },
            {
                "class": "io.netty.util.concurrent.DefaultPromise",
                "method": "notifyListenersNow",
                "file": "DefaultPromise.java",
                "line": 550
            },
            {
                "class": "io.netty.util.concurrent.DefaultPromise",
                "method": "notifyListeners",
                "file": "DefaultPromise.java",
                "line": 491
            },
            {
                "class": "io.netty.util.concurrent.DefaultPromise",
                "method": "setValue0",
                "file": "DefaultPromise.java",
                "line": 616
            },
            {
                "class": "io.netty.util.concurrent.DefaultPromise",
                "method": "setSuccess0",
                "file": "DefaultPromise.java",
                "line": 605
            },
            {
                "class": "io.netty.util.concurrent.DefaultPromise",
                "method": "trySuccess",
                "file": "DefaultPromise.java",
                "line": 104
            },
            {
                "class": "io.netty.util.internal.PromiseNotificationUtil",
                "method": "trySuccess",
                "file": "PromiseNotificationUtil.java",
                "line": 48
            },
            {
                "class": "io.netty.channel.ChannelOutboundBuffer",
                "method": "safeSuccess",
                "file": "ChannelOutboundBuffer.java",
                "line": 717
            },
            {
                "class": "io.netty.channel.ChannelOutboundBuffer",
                "method": "remove",
                "file": "ChannelOutboundBuffer.java",
                "line": 272
            },
            {
                "class": "io.netty.channel.ChannelOutboundBuffer",
                "method": "removeBytes",
                "file": "ChannelOutboundBuffer.java",
                "line": 352
            },
            {
                "class": "io.netty.channel.socket.nio.NioSocketChannel",
                "method": "doWrite",
                "file": "NioSocketChannel.java",
                "line": 414
            },
            {
                "class": "io.netty.channel.AbstractChannel$AbstractUnsafe",
                "method": "flush0",
                "file": "AbstractChannel.java",
                "line": 949
            },
            {
                "class": "io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe",
                "method": "flush0",
                "file": "AbstractNioChannel.java",
                "line": 354
            },
            {
                "class": "io.netty.channel.AbstractChannel$AbstractUnsafe",
                "method": "flush",
                "file": "AbstractChannel.java",
                "line": 913
            },
            {
                "class": "io.netty.channel.DefaultChannelPipeline$HeadContext",
                "method": "flush",
                "file": "DefaultChannelPipeline.java",
                "line": 1372
            },
            {
                "class": "io.netty.channel.AbstractChannelHandlerContext",
                "method": "invokeFlush0",
                "file": "AbstractChannelHandlerContext.java",
                "line": 750
            },
            {
                "class": "io.netty.channel.AbstractChannelHandlerContext",
                "method": "invokeFlush",
                "file": "AbstractChannelHandlerContext.java",
                "line": 742
            },
            {
                "class": "io.netty.channel.AbstractChannelHandlerContext",
                "method": "flush",
                "file": "AbstractChannelHandlerContext.java",
                "line": 728
            },
            {
                "class": "io.netty.channel.ChannelDuplexHandler",
                "method": "flush",
                "file": "ChannelDuplexHandler.java",
                "line": 127
            },
            {
                "class": "io.netty.channel.AbstractChannelHandlerContext",
                "method": "invokeFlush0",
                "file": "AbstractChannelHandlerContext.java",
                "line": 750
            },
            {
                "class": "io.netty.channel.AbstractChannelHandlerContext",
                "method": "invokeWriteAndFlush",
                "file": "AbstractChannelHandlerContext.java",
                "line": 765
            },
            {
                "class": "io.netty.channel.AbstractChannelHandlerContext",
                "method": "write",
                "file": "AbstractChannelHandlerContext.java",
                "line": 790
            },
            {
                "class": "io.netty.channel.AbstractChannelHandlerContext",
                "method": "writeAndFlush",
                "file": "AbstractChannelHandlerContext.java",
                "line": 758
            },
            {
                "class": "io.netty.channel.AbstractChannelHandlerContext",
                "method": "writeAndFlush",
                "file": "AbstractChannelHandlerContext.java",
                "line": 808
            },
            {
                "class": "io.netty.channel.DefaultChannelPipeline",
                "method": "writeAndFlush",
                "file": "DefaultChannelPipeline.java",
                "line": 1025
            },
            {
                "class": "io.netty.channel.AbstractChannel",
                "method": "writeAndFlush",
                "file": "AbstractChannel.java",
                "line": 306
            },
            {
                "class": "io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker",
                "method": "handshake",
                "file": "WebSocketServerHandshaker.java",
                "line": 223
            },
            {
                "class": "io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker",
                "method": "handshake",
                "file": "WebSocketServerHandshaker.java",
                "line": 273
            },
            {
                "class": "io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker",
                "method": "handshake",
                "file": "WebSocketServerHandshaker.java",
                "line": 250
            },
            {
                "class": "io.vertx.core.http.impl.ServerWebSocketImpl",
                "method": "doHandshake",
                "file": "ServerWebSocketImpl.java",
                "line": 184
            },
            {
                "class": "io.vertx.core.http.impl.ServerWebSocketImpl",
                "method": "handleHandshake",
                "file": "ServerWebSocketImpl.java",
                "line": 172
            },
            {
                "class": "io.vertx.core.http.impl.ServerWebSocketImpl",
                "method": "lambda$setHandshake$1",
                "file": "ServerWebSocketImpl.java",
                "line": 232
            },
            {
                "class": "io.vertx.core.impl.FutureImpl",
                "method": "dispatch",
                "file": "FutureImpl.java",
                "line": 105
            },
            {
                "class": "io.vertx.core.impl.FutureImpl",
                "method": "onComplete",
                "file": "FutureImpl.java",
                "line": 83
            },
            {
                "class": "io.vertx.core.http.impl.ServerWebSocketImpl",
                "method": "setHandshake",
                "file": "ServerWebSocketImpl.java",
                "line": 230
            },
            {
                "class": "io.vertx.core.http.impl.ServerWebSocketImpl",
                "method": "setHandshake",
                "file": "ServerWebSocketImpl.java",
                "line": 214
            },
            {
                "class": "io.vertx.core.http.impl.ServerWebSocketImpl",
                "method": "tryHandshake",
                "file": "ServerWebSocketImpl.java",
                "line": 206
            },
            {
                "class": "io.vertx.core.http.impl.ServerWebSocketImpl",
                "method": "accept",
                "file": "ServerWebSocketImpl.java",
                "line": 95
            },
            {
                "class": "io.vertx.core.http.impl.HttpServerRequestImpl",
                "method": "upgrade",
                "file": "HttpServerRequestImpl.java",
                "line": 424
            },
            {
                "class": "io.vertx.core.http.HttpServerRequest",
                "method": "toWebSocket",
                "file": "HttpServerRequest.java",
                "line": 386
            },

**Comment by normanmaurer** [comment]
I think this should be fixed by https://github.com/netty/netty/pull/13180... PTAL

**Comment by ChatGPTT** [comment]
> I think this should be fixed by #13180... PTAL
I appreciate your quick response. I tried now to reproduce the exception with your changes and it looks very fine. As you wrote there some unit tests would be great. Thanks again
