### ISSUE TITLE
Unknown channel options produce (expected) warning log

### ISSUE THREAD

**Issue by derklaro** [netty/netty#13178]
### Expected & Actual behaviour

Hi, I've been looking into Channel Options a bit over the last few days and came across and am using the TCP_FACTOPEN(_CONNECT) option. But since the option is not available for all channels (e.g. Nio on Windows) a warning is logged (`Unknown channel option 'TCP_FASTOPEN_CONNECT' for channel ...`).

Is there a specific reason why this message is logged in WARN level instead of debug level? Some users report "errors" based only on this log message, although the functionality does not change in any way.

Thanks for feedback in advance :)

### Netty version
5.0.0.Alpha5

**Comment by hyperxpro** [comment]
This is semantically correct because you're passing a `ChannelOption` explicitly on a `Channel` that does not support it. `DEBUG` is the wrong level for logging misconfiguration.

Instead, the user should check if `Channel` supports certain `ChannelOption` before passing it.

**Comment by derklaro** [comment]
My main issue with the approach is that there is no good way to check if an option is supported for a channel when using the (Server)Bootstrap class. It would require to move the options to a specialised channel initialiser, or check based on the selected transport (which isn't exposing a way to check if a channel option is supported).

So my main issue is that in an environment where I select the transport to use based on their availability, there is no way to pre-check if an option is support, other than making assumptions based on the transport type, or moving the options into a channel initialiser but using the (child)otion methods on the bootstrap classes is much more convenient...

**Comment by hyperxpro** [comment]
```java
ServerSocketChannel serverSocketChannel = new NioServerSocketChannel();
System.out.println(serverSocketChannel.config().setOption(UnixChannelOption.SO_REUSEPORT, true));
```
```
Output: false
```

Use this approach to check if `Channel` supports a given `ChannelOption`.

**Comment by derklaro** [comment]
Seems like the constructor no longer exists in netty 5.

**Comment by hyperxpro** [comment]
Netty 5:
```java
EpollServerSocketChannel channel = new EpollServerSocketChannel(bossGroup.next(), workerGroup);
System.out.println(channel.isOptionSupported(ChannelOption.TCP_FASTOPEN));
```

```
Output: true
```

**Comment by derklaro** [comment]
I went ahead and wrote a generalized channel initialiser that only sets options if they are supported by the provided channel. That solution seems easier and more intended to me that your suggestion.
