### ISSUE TITLE
removeBytes Cannot remove an entry that has been canceled

### ISSUE THREAD

**Issue by CodeDeveloperC** [netty/netty#13187]
### Expected behavior

The canceled Entry can be removed from ChannelOutboundBuffer

### Actual behavior
Netty writes the data to be sent by the user to the socket through the` io.netty.channel.socket.nio.NioSocketChannel # doWrite `function. First, get the ByteBuffer [] array to be sent through `io. net. channel. ChannelOutboundBuffer # nioBuffers (int, long)`. During the construction of the array to be sent, judge the condition through` if (! Entry. canceled) `to filter out the canceled ByteBuffer. That is, the` io. net. channel. ChannelOutboundBuffer # nioBuffers (int, long)` function returns an array of ByteBuffers that does not contain the cancelled ones.

Assumption: The total size of the ByteBuffer array that the user needs to send is `total` (including the canceled entries)

`Io. net. channel. ChannelOutboundBuffer # nioBuffers (int, long) `function returns ByteBuffer array size is `A`

The size of the ByteBuffer array that has been canceled is `B`.

Then We have total==A+B

We assume that in the` io. net. channel. socket. nio. NoSocketChannel # doWrite` function, our data is normally written to the inner socket. After sending, we will call the `io.nety.channel.ChannelOutboundBuffer # removeBytes` function to remove the written ByteBuffer. However, this function does not take into account the removal of the ByteBuffer array that has been canceled, so it may cause the data have been sent, but the entry of the current message has not been removed. That is, we need to remove the ByteBuffer of `total` size, but we only remove the ByteBuffer of `A` size. I think this is a problem.Thanks!
### Minimal yet complete reproducer code (or URL to code)
```java
public void removeBytes(long writtenBytes) {
        for (;;) {
            Object msg = current();
            if (!(msg instanceof ByteBuf)) {
                assert writtenBytes == 0;
                break;
            }

            // remove canceled Entry start
            Entry entry = flushedEntry;
            if (entry != null && entry.cancelled) {
                remove();
                continue;
            }
             // remove canceled Entry end

            final ByteBuf buf = (ByteBuf) msg;
            final int readerIndex = buf.readerIndex();
            final int readableBytes = buf.writerIndex() - readerIndex;

            if (readableBytes <= writtenBytes) {
                if (writtenBytes != 0) {
                    progress(readableBytes);
                    writtenBytes -= readableBytes;
                }
                remove();
            } else { // readableBytes > writtenBytes
                if (writtenBytes != 0) {
                    buf.readerIndex(readerIndex + (int) writtenBytes);
                    progress(writtenBytes);
                }
                break;
            }
        }
        clearNioBuffers();
    }
```
### Netty version
4.1
### JVM version (e.g. `java -version`)
openjdk version "1.8.0_352"
OpenJDK Runtime Environment (Zulu 8.66.0.15-CA-macos-aarch64) (build 1.8.0_352-b08)
OpenJDK 64-Bit Server VM (Zulu 8.66.0.15-CA-macos-aarch64) (build 25.352-b08, mixed mode)
### OS version (e.g. `uname -a`)
MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0
ARM64_T6000 arm64

**Comment by normanmaurer** [comment]
As shown in the added unit test it works as expected
