### ISSUE TITLE
Avoid ThreadLocals to be more loom friendly 

### ISSUE THREAD

**Issue by franz1981** [netty/netty#13191]
The current behaviour for the pooled buffer allocation path (on Netty 4.1, but on 5 is similar) include 2 loom unfriendly ops:
- in order to NOT use a cache, we still use a ThreadLocal operation -> https://github.com/netty/netty/blob/b61d7d40f40e3a797e8a60cd567f849a9799c771/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java#L537
- Recyclers uses thread local regardless the previous decision 

I see 2 fixes here:
- being able to determine if a thread shouldn't use any  cache without any thread local method (and sadly checking if current thread is a "used" event loop thread will still use another thread local ops :"/ )
- `PoolThreadCache(heapArena, directArena, 0, 0, 0, 0)` should be a singleton (using a specialized children, if possible) for v threads
- recyclers shouldn't be used with v threads for the same problem

The last is a problem we have right now as well with non-virtual and non-event loop threads as well (nudge nudge @chrisvest ): non event loop threads shouldn't use recycler(s) in the form of `ThreadLocal::get` ops or they will end up creating unecessary objects again.

**Comment by franz1981** [comment]
Sadly, while working on this I've just found that the changes I've made for https://github.com/netty/netty/issues/12621 can be dangerous, I'm opening a new issue to track this.

**Comment by franz1981** [comment]
@chrisvest 
I've created a branch to show a potential solution to the problem (see https://github.com/franz1981/netty/tree/4.1_loom_fix), but right after I remembered your solution at https://github.com/netty/netty/pull/13075 - can you please check if https://github.com/netty/netty/issues/13204 can  still happen with your changes, from a logical perspective?

**Comment by franz1981** [comment]
at the same time I've opened a sibling issue at https://github.com/quarkusio/quarkus/issues/33102

**Comment by trustin** [comment]
Out of curiosity, is there any way to create a thread local on the carrier thread and use it when on a virtual thread? I feel like there should still be a way to leverage platform/carrier thread-local even when using virtual thread...

**Comment by franz1981** [comment]
>  is there any way to create a thread local on the carrier thread and use it when on a virtual thread? I feel like there should still be a way to leverage platform/carrier thread-local even when using virtual thread...

yes, but is an internal JDK API, see https://github.com/FasterXML/jackson-core/issues/919 and the JDK code at https://github.com/openjdk/jdk/blob/861cc671e2e4904d94f50710be99a511e2f9bb68/src/java.base/share/classes/sun/nio/ch/Util.java#L56 but it can hides subtle un-expect behaviours really

eg

1. a virtual thread use this per-carrier thread local to create X
2. the virtual thread perform some blocking operation and is virtually parked
3. it is then unparked but another carrier is ready to continue it
4. it "release" X into a different carrier from the original one (making the pools unbalanced? depends)

**Comment by magicprinc** [comment]
@trustin Amazing answer to this question: https://stackoverflow.com/questions/75047540/is-it-possible-to-create-a-threadlocal-for-the-carrier-thread-of-a-java-virtual

**Comment by franz1981** [comment]
I believe that the adaptive allocator, thanks to #14279 can already benefit of a proper virtual-thread friendly allocator; sadly this is not the sole fast-thread local usage which can happen on worker thread, but i'll reopen a new one as we will find new ones to fix (in the hot path, clearly).
