### ISSUE TITLE
OutOfDirectMemoryError with pooled allocator 

### ISSUE THREAD

**Issue by krzysztofslusarski** [netty/netty#13206]
If you are using pooled allocator (even with default maxMemoryDirect) there are still places in Netty code where you use unpooled allocator. 

For example ```HttpObjectEncoder```:

```java
import static io.netty.buffer.Unpooled.directBuffer;

    // ...
    private static final ByteBuf CRLF_BUF = unreleasableBuffer(
            directBuffer(2).writeByte(CR).writeByte(LF)).asReadOnly();
    private static final ByteBuf ZERO_CRLF_CRLF_BUF = unreleasableBuffer(
            directBuffer(ZERO_CRLF_CRLF.length).writeBytes(ZERO_CRLF_CRLF)).asReadOnly();
```

The method ```directBuffer``` is from ```Unpooled``` class. It goes through following path:
```
io.netty.buffer.AbstractByteBufAllocator#directBuffer(int)
io.netty.buffer.AbstractByteBufAllocator#directBuffer(int, int)
io.netty.buffer.UnpooledByteBufAllocator#newDirectBuffer
io.netty.buffer.UnpooledByteBufAllocator.InstrumentedUnpooledUnsafeNoCleanerDirectByteBuf#InstrumentedUnpooledUnsafeNoCleanerDirectByteBuf
io.netty.buffer.UnpooledUnsafeNoCleanerDirectByteBuf#UnpooledUnsafeNoCleanerDirectByteBuf
io.netty.buffer.UnpooledUnsafeDirectByteBuf#UnpooledUnsafeDirectByteBuf(io.netty.buffer.ByteBufAllocator, int, int)
io.netty.buffer.UnpooledDirectByteBuf#UnpooledDirectByteBuf(io.netty.buffer.ByteBufAllocator, int, int)
io.netty.buffer.UnpooledByteBufAllocator.InstrumentedUnpooledUnsafeNoCleanerDirectByteBuf#allocateDirect
io.netty.buffer.UnpooledUnsafeNoCleanerDirectByteBuf#allocateDirect
io.netty.util.internal.PlatformDependent#allocateDirectNoCleaner
```

The method ```allocateDirectNoCleaner```:
```java
    public static ByteBuffer allocateDirectNoCleaner(int capacity) {
        assert USE_DIRECT_BUFFER_NO_CLEANER;

        incrementMemoryCounter(capacity);
        try {
            return PlatformDependent0.allocateDirectNoCleaner(capacity);
        } catch (Throwable e) {
            decrementMemoryCounter(capacity);
            throwException(e);
            return null;
        }
    }
```

It's the same method that is used by pooled allocator and the memory counter used in ```incrementMemoryCounter``` is common for both allocators. That creates a possibility where pooled allocator may OOM with OutOfDirectMemoryError thrown in:

```java
    private static void incrementMemoryCounter(int capacity) {
        if (DIRECT_MEMORY_COUNTER != null) {
            long newUsedMemory = DIRECT_MEMORY_COUNTER.addAndGet(capacity);
            if (newUsedMemory > DIRECT_MEMORY_LIMIT) {
                DIRECT_MEMORY_COUNTER.addAndGet(-capacity);
                throw new OutOfDirectMemoryError("failed to allocate " + capacity
                        + " byte(s) of direct memory (used: " + (newUsedMemory - capacity)
                        + ", max: " + DIRECT_MEMORY_LIMIT + ')');
            }
        }
    }
```

since some bytes are consumed by pooled allocator. Here a screen of a heap dump with default pooled allocator:
![image](https://user-images.githubusercontent.com/57556371/217785150-c4413ea0-1540-4509-92d9-a67f44b607ab.png)
As you can see we have 7 bytes consumed by unpooled one. Those 7 bytes later are needed by pooled allocator.

The ```HttpObjectEncoder``` is one of the class where unpoooled allocator is used, but there are others. There are 33 production code usages of direct unpooled usage, I believe all of them should be investigated/fixed:
![image](https://user-images.githubusercontent.com/57556371/217786970-e06f360a-7462-4401-9024-3fa1b5e56658.png)

### Expected behavior
No OutOfDirectMemoryError.

### Actual behavior
OutOfDirectMemoryError.

### Steps to reproduce
Not relevnat

### Minimal yet complete reproducer code (or URL to code)
Not relevnat

### Netty version
4.1.X

### JVM version (e.g. `java -version`)
Not relevnat

### OS version (e.g. `uname -a`)
Not relevant

**Comment by franz1981** [comment]
Hi @krzysztofslusarski !

I don't see that a problem given that such allocations will live till the duration of the mentioned class life cycles (they are actually, proper constant!), or am I misunderstood what you mean?

**Comment by krzysztofslusarski** [comment]
> till the duration of the mentioned class

Those are static fields, so the allocation is hold till unloading of a class / JVM kill.

**Comment by franz1981** [comment]
Yep, but why it should be a problem? 
are you suggesting to use Pooled allocations for them?

**Comment by krzysztofslusarski** [comment]
The scenario I just saw today is like that:
- maxMemoryDirect = 512 MB
- Netty already allocated 127 of 4MB off heap buffers through pooled allocator
- Netty tries to allocate one more 4MB through pooled allocator - that should succeed, since 4*128 = 512
- OODME is thrown since: ```newUsedMemory > DIRECT_MEMORY_LIMIT``` is true in ```incrementMemoryCounter```

The problem is that ```DIRECT_MEMORY_COUNTER``` should be 127*4*1024*1024 = 532676608 in that case, but it has higher value since unpooled allocator allocated 7 bytes:
![image](https://user-images.githubusercontent.com/57556371/217788579-761cb76d-b14a-480b-a93d-59e5ac8a55e4.png)

Regarding suggestion I see 2 way of dealing with it:
- Remove the direct usages of unpooled allocator and switch to "current active in the system"
- Add a method like ```allocateDirectNoCleanerWithoutIncreasingCounter```

**Comment by franz1981** [comment]
Yeah, but the problem is...such off-heap memory should be accounted somewhere and OOM on Netty (when you specify limits for it, implicitly or not) shouldn't be that different from what the JVM does.
With the JVM if you allocate direct memory, it won't care if you pool/make it constant or not, it's jus memory used, till will be released, if ever will be released.

Afaik the purpose of the Netty counter was the same as per the JVM, to enforce software limits that would make easier to track what a OOM killer would do, in a much less verbose and informative way.

**Comment by franz1981** [comment]
Let's see if @normanmaurer or @chrisvest got a different idea to help you on this

**Comment by franz1981** [comment]
Thinking about it, I see that what we can do to help users distinguish constant off-heap footprint (let's call it baseline, but is not a fair term, given that per class loaded, it can increase) is to use a specific method to allocate those constants and track both direct memory and constant direct memory (a new counter) per them.
Given that these are constant, the performance impact about adding 2 counters updates, shouldn't be a problem.

The results is that users, exposing such telemetry, are able to track what's the dynamically allocated memory vs the constant one (as a difference).
Why not using 2 separate counter per dynamic vs constant? 
Because we still need a global limit as we do now, to not break existing users.

**Comment by franz1981** [comment]
yes, it is, because `HttpClientCodec` has a constant footprint in term of direct memory usage that is (correctly) accounted in the Netty direct memory limit (as said; similarly to the JVM limits there is not distinction between "constant" and "dynamic")

**Comment by franz1981** [comment]
Consider that as soon as you create the pipeline (unless dynamically changed handlers types), the "constant" footprint should be already stable.

**Comment by krzysztofslusarski** [comment]
OK. So I believe I need to trace some memory leak in that application (not necessary in Netty, maybe some other library causes leak by not releasing acquired buffers).

Thank you for the explanation.

**Comment by krzysztofslusarski** [comment]
Closing the issue. The memory leak was found with ```-Dio.netty.leakDetection.level=advanced```, nothing related to Netty. Thank you for your explanations, that gave me better understanding of your allocators behavior.

**Comment by krzysztofslusarski** [comment]
Good job with ```-Dio.netty.leakDetection.level=advanced``` BTW :)
