### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by freedom1b2830** [netty/netty#13212]
io.netty.handler.codec.serialization.ClassResolvers;
io.netty.handler.codec.serialization.ObjectDecoder;
io.netty.handler.codec.serialization.ObjectEncoder;

Due to security issues in deserialization, the classes are marked as deprecated.
There are several projects that help solve this problem.
https://github.com/Contrast-Security-OSS/contrast-rO0
There is a list of allowed classes for serialization / deserialization and also a black list

**Comment by hyperxpro** [comment]
What exactly is the problem?

**Comment by hyperxpro** [comment]
Do we really need them? How does it fit into our use-case?

**Comment by normanmaurer** [comment]
@freedom1b2830 I dont think we want to add support back for Serialisation. Even with filtering I would consider it unsecure and so should not use in practice. Use protobuf or something else
