### ISSUE TITLE
How to get all sockets

### ISSUE THREAD

**Issue by 673885125** [netty/netty#13210]
Whether there is relevant api available?

**Comment by hyperxpro** [comment]
Explain more.

**Comment by 673885125** [comment]
> 多解释一下。
Want to monitor the total number of service sockets

Total number of sockets successfully created on the server

**Comment by freedom1b2830** [comment]
save connections to a list
connected(add):https://github.com/netty/netty/blob/d010e63bf5bf744f2ab6d0fc4386611efe7954e6/transport/src/main/java/io/netty/channel/ChannelInboundHandler.java#L37

disconnected(remove):
https://github.com/netty/netty/blob/d010e63bf5bf744f2ab6d0fc4386611efe7954e6/transport/src/main/java/io/netty/channel/ChannelInboundHandler.java#L43
