### ISSUE TITLE
Snappy compressor can't compress more than 32767 bytes

### ISSUE THREAD

**Issue by RaphiMC** [netty/netty#13226]
### Expected behavior
I expect the Snappy compressor to be able to compress a much larger amount than 32767 bytes.
### Actual behavior
An exception is thrown if the data is too large.
### Steps to reproduce
Try to compress a ByteBuf larger than 32767 bytes using the Snappy.encode method.
### Minimal yet complete reproducer code (or URL to code)
```java
public static void main(String[] args) {
    final byte[] random = new byte[40_000];
    ThreadLocalRandom.current().nextBytes(random);
    { // This should work
        final Snappy snappy = new Snappy();
        final ByteBuf data = Unpooled.wrappedBuffer(Arrays.copyOfRange(random, 0, 32767));
        final ByteBuf out = Unpooled.buffer();
        snappy.encode(data, out, data.readableBytes());
    }
    { // This does not work
        final Snappy snappy = new Snappy();
        final ByteBuf data = Unpooled.wrappedBuffer(random);
        final ByteBuf out = Unpooled.buffer();
        snappy.encode(data, out, data.readableBytes());
    }
}
```
### Netty version
4.1.89
### JVM version (e.g. `java -version`)
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)
### OS version (e.g. `uname -a`)
Windows 10 x64 22H2 19045.2546

**Comment by chrisvest** [comment]
The implementation is for use in the `SnappyFrameEncoder`, which limit its chunk size to this in order to conserve memory.

**Comment by RaphiMC** [comment]
Being able to configure the maximum allowed chunk size in the constructur would be a nice feature as I would like to use the Snappy encoder/decoder outside of the SnappyFrameEncoder without needing extra libraries

**Comment by normanmaurer** [comment]
@RaphiMC we love contributions

**Comment by RaphiMC** [comment]
I would if I knew why it is not working and how to fix it. As a temporary workaround I am just writing the data as uncompressed snappy chunks: https://github.com/RaphiMC/ViaBedrock/blob/main/src/main/java/net/raphimc/viabedrock/netty/SnappyCompression.java#L35

**Comment by normanmaurer** [comment]
Why not just chunk the data as we do in `SnappyFrameEncoder` ?

**Comment by RaphiMC** [comment]
The protocol I am implementing expects raw snappy data without framing. I would just use the SnappyFrameEncoder if it accepted that

**Comment by normanmaurer** [comment]
Got it... Then there is not much you can do other than adjusting `Snappy` and provide a PR.
