### ISSUE TITLE
macOS App Using resolver-dns-native-macos Fails Apple Notarization

### ISSUE THREAD

**Issue by jesusvigil** [netty/netty#13228]
I am working on a project where we are building a macOS app using netty-resolver-dns-native-macos. When I attempt to have my app notarized by Apple in order to distribute to users, the notarization process fails and Apple sends the reason for the failure is that "The binary uses an SDK older than the 10.9 SDK". The binary in question is "libnetty_resolver_dns_native_macos_x86_64.jnilib" which seems to have been compiled with Mac OS X SDK 10.6 according to this pom.xml file https://github.com/netty/netty/blob/4.1/resolver-dns-native-macos/pom.xml. I am wondering if it would be possible to raise the Mac OS X SDK to 10.9? Or what is the reasoning for staying at such an old SDK?

### Expected behavior
Apple successfully notarizes the application.
### Actual behavior
Apple rejects the application due to the usage of Mac OS X SDK 10.6 as it is now a requirement to use SDK 10.9 or later
[https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087723](https://developer.apple.com/documentation/security/notarizing_macos_software_before_distribution/resolving_common_notarization_issues#3087723)
### Steps to reproduce
Send an application using netty-resolver-dns-native-macos to be notarized by Apple
### Minimal yet complete reproducer code (or URL to code)
[https://github.com/netty/netty/tree/4.1/resolver-dns-native-macos](https://github.com/netty/netty/tree/4.1/resolver-dns-native-macos)
### Netty version
netty-resolver-dns-native-macos-4.1.87.Final-osx-x86_64.jar
### JVM version (e.g. `java -version`)
17
### OS version (e.g. `uname -a`)
Mac OS X Mojave (10.14) and later

**Comment by normanmaurer** [comment]
Yeah I think we can change that.
