### ISSUE TITLE
When network is turn off Channel#closeFuture method can't is called

### ISSUE THREAD

**Issue by GZYangKui** [netty/netty#13234]
### Expected behavior
When network is turn off Channel#closeFuture method is called

### Actual behavior
When network is turn off Channel#closeFuture method can't is called
### Steps to reproduce

When I use Vertx, if the network is closed, the NetClient # closeHandler method of Vertx will be called back immediately, but when I use Netty to change the network state, Channel # closeFuture will not be called back. The current solution is to add IdleStateHandler to detect the number and interval of server responses. Is there no mechanism in Netty to detect network changes like Vertx?
### Minimal yet complete reproducer code (or URL to code)
none.
### Netty version
4.1.87.Final
### JVM version (e.g. `java -version`)

openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

### OS version (e.g. `uname -a`)
Linux yangkui 5.19.0-31-generic #32-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 20 15:20:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
This is expected when using TCP. You will only be able to detect this when you either try to write or read from the socket or when the idle timeout hits.
