### ISSUE TITLE
RFC non complaince : RFC 7540 "Hypertext Transfer Protocol Version 2 (HTTP/2)" https://datatracker.ietf.org/doc/html/rfc7540

### ISSUE THREAD

**Issue by adhanoti** [netty/netty#13235]
**RFC behavior :**

 RFC7540 Section 8.1.2.3 : "All HTTP/2 requests MUST include exactly one
valid value for the ":method", ":scheme", and ":path" pseudo-header field,
unless it is a CONNECT request. An HTTP request that omits mandatory
pseudo-header fields is malformed."
    RFC7540 Section 8.1.2.6 "Malformed requests or responses that are
detected MUST be treated as a stream error (Section 5.4.2) of type
PROTOCOL_ERROR"
    RFC7540 Section 5.4.2 : "An endpoint that detects a stream error sends a
RST_STREAM frame (Section 6.4) that contains the stream identifier of the
stream where the error occurred. The RST_STREAM frame includes an error code
that indicates the type of error."

Actaul Issue - NRF is our network function.

Empty Path:
NRF does not reset the stream when :path pseudo-header field is empty
(without /).
See: 221003-114918_SBA_conformance_pseudoHeadersEmptyPath_172.19.124.pcap

Invalid Content-Length:
NRF sends RST_STREAM with CANCEL reason instead of PROTOCOL_ERROR when
content-length header is no correct for sent data.
See:
221003-114925_SBA_conformance_forbiddenHeadersContentLength_172.19.124.pcap

Invalid Connection-Specific header fields.
RFC7540 Section 8.1.2.2 "Connection-Specific Header Fields"
https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2.2
Noted:  Only valid connection-specific header field is "te" and must have
value of "trailers"

NRF does not reset stream when receiving a te header with a value other than
"trailers"
See:
221003-114929_SBA_conformance_forbiddenHeadersTE_172.19.124.pcap

NRF does not reset stream when receiving a request with other
connection-specific header fields.
See:
221003-114932_SBA_conformance_forbiddenHeadersTransferEncoding_172.19.124.pcap
 for "transfer-encoding" and
221003-114939_SBA_conformance_forbiddenHeadersKeepAlive_172.19.124.pcap for
"keep-alive"

**Netty version Used** : 1.0.24

**Java version used** : 17

Need to know whether Netty follow RFC 7540 and when the compliance will be available.

**Comment by violetagg** [comment]
>Netty version Used : 1.0.24


@adhanoti Is this version, Reactor Netty version?

If yes then may be we would better discuss this in Reactor Netty issue tracker

**Comment by adhanoti** [comment]
Thanks. Yes it is reactor netty version.

Do i need to create separate issue?

Regards,
Ashish

**Comment by violetagg** [comment]
yes please

**Comment by adhanoti** [comment]
RFC non complaince : RFC 7540 "Hypertext Transfer Protocol Version 2
(HTTP/2)" https://datatracker.ietf.org/doc/html/rfc7540 · Issue #2702 ·
reactor/reactor-netty (github.com)
<https://github.com/reactor/reactor-netty/issues/2702>

Ticket Created.

Let me know if you need wireshark for same. In ticket i am not able to
upload wireshark.

Regards,
Ashish

**Comment by violetagg** [comment]
@normanmaurer @idelpivnitskiy This PR #12975 removes `:path` not empty check. IMO we should keep it. Wdyt?

**Comment by violetagg** [comment]
hm ... it was checking before for duplicate pseudo-header ... ok ignore my comment above

**Comment by violetagg** [comment]
@adhanoti The issue with `:path` should be address with #13238

The issue with `connection-specific header` should be address with #12975

**Comment by violetagg** [comment]
@normanmaurer @chrisvest @idelpivnitskiy 

The issue with `Content-Length` that is not matching the actual data is interesting.
Netty correctly identifies that there is a mismatch and throws a stream error.

`Http2ConnectionHandler` correctly resets the stream with `PROTOCOL_ERROR`
https://github.com/netty/netty/blob/59aa6e635b9996cf21cd946e64353270679adc73/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L744

However when `Http2FrameCodec` and `Http2MultiplexHandler`, the flow is the following:

`Http2FrameCodec` forwards the stream error
https://github.com/netty/netty/blob/59aa6e635b9996cf21cd946e64353270679adc73/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2FrameCodec.java#L568

`Http2MultiplexHandler` notifies the child channel and closes it.
https://github.com/netty/netty/blob/59aa6e635b9996cf21cd946e64353270679adc73/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexHandler.java#L274-L278

When the stream channel is closed, it is closed always with `CANCEL`
https://github.com/netty/netty/blob/59aa6e635b9996cf21cd946e64353270679adc73/codec-http2/src/main/java/io/netty/handler/codec/http2/AbstractHttp2StreamChannel.java#L681

 I don't see a way to propagate the actual error code :(

**Comment by normanmaurer** [comment]
@violetagg let me have a look

**Comment by normanmaurer** [comment]
This should be fixed by https://github.com/netty/netty/pull/13309
