### ISSUE TITLE
Netty/Testsuite/NativeImage ........................ FAILURE

### ISSUE THREAD

**Issue by dwang010** [netty/netty#13240]
### Netty version
4.0.1.89
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
macOS 12

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Netty 4.1.89.Final:
[INFO] 
[INFO] Netty/Dev-Tools .................................... SUCCESS [  1.634 s]
[INFO] Netty .............................................. SUCCESS [  8.637 s]
[INFO] Netty/Common ....................................... SUCCESS [ 51.718 s]
[INFO] Netty/Buffer ....................................... SUCCESS [ 15.106 s]
[INFO] Netty/Resolver ..................................... SUCCESS [  5.722 s]
[INFO] Netty/Transport .................................... SUCCESS [ 12.634 s]
[INFO] Netty/Codec ........................................ SUCCESS [ 14.608 s]
[INFO] Netty/Codec/DNS .................................... SUCCESS [  6.510 s]
[INFO] Netty/Codec/HAProxy ................................ SUCCESS [  5.622 s]
[INFO] Netty/Transport/Native/Unix/Common ................. SUCCESS [  6.243 s]
[INFO] Netty/Handler ...................................... SUCCESS [ 17.047 s]
[INFO] Netty/Codec/HTTP ................................... SUCCESS [ 25.757 s]
[INFO] Netty/Codec/HTTP2 .................................. SUCCESS [ 15.782 s]
[INFO] Netty/Codec/Memcache ............................... SUCCESS [  4.856 s]
[INFO] Netty/Codec/MQTT ................................... SUCCESS [  6.393 s]
[INFO] Netty/Codec/Redis .................................. SUCCESS [  4.918 s]
[INFO] Netty/Codec/SMTP ................................... SUCCESS [  3.617 s]
[INFO] Netty/Codec/Socks .................................. SUCCESS [  5.946 s]
[INFO] Netty/Codec/Stomp .................................. SUCCESS [  4.926 s]
[INFO] Netty/Codec/XML .................................... SUCCESS [  4.278 s]
[INFO] Netty/Handler/Proxy ................................ SUCCESS [  4.668 s]
[INFO] Netty/Resolver/DNS ................................. SUCCESS [ 11.840 s]
[INFO] Netty/Handler/Ssl/Ocsp ............................. SUCCESS [  5.190 s]
[INFO] Netty/Transport/RXTX ............................... SUCCESS [  3.631 s]
[INFO] Netty/Transport/SCTP ............................... SUCCESS [  5.076 s]
[INFO] Netty/Transport/UDT ................................ SUCCESS [  5.160 s]
[INFO] Netty/Transport/Classes/Epoll ...................... SUCCESS [  5.147 s]
[INFO] Netty/Transport/Classes/KQueue ..................... SUCCESS [  4.177 s]
[INFO] Netty/Resolver/DNS/Classes/MacOS ................... SUCCESS [  2.368 s]
[INFO] Netty/All-in-One ................................... SUCCESS [  2.312 s]
[INFO] Netty/Resolver/DNS/Native/MacOS .................... SUCCESS [ 17.899 s]
[INFO] Netty/Transport/Native/Unix/Common/Tests ........... SUCCESS [  3.972 s]
[INFO] Netty/Testsuite .................................... SUCCESS [  9.939 s]
[INFO] Netty/Transport/Native/Epoll ....................... SUCCESS [  4.866 s]
[INFO] Netty/Transport/Native/KQueue ...................... SUCCESS [ 16.420 s]
[INFO] Netty/Example ...................................... SUCCESS [ 15.224 s]
[INFO] Netty/Testsuite/Autobahn ........................... SUCCESS [  7.277 s]
[INFO] Netty/Testsuite/Http2 .............................. SUCCESS [  7.823 s]
[INFO] Netty/Testsuite/OSGI ............................... SUCCESS [  4.076 s]
[INFO] Netty/Testsuite/Shading ............................ SUCCESS [  9.226 s]
[INFO] Netty/Testsuite/Native ............................. SUCCESS [  2.892 s]
[INFO] Netty/Testsuite/NativeImage ........................ FAILURE [  6.156 s]
[INFO] Netty/Testsuite/NativeImage/Client ................. SKIPPED
[INFO] Netty/Testsuite/NativeImage/ClientRuntimeInit ...... SKIPPED
[INFO] Netty/Transport/BlockHound/Tests ................... SKIPPED
[INFO] Netty/Microbench ................................... SKIPPED
[INFO] Netty/BOM .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:18 min
[INFO] Finished at: 2023-02-24T16:05:40+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.14.6:check (api-check) on project netty-testsuite-native-image: The following API problems caused the build to fail:
[ERROR] java.missing.oldClass: missing-class io.netty.channel.ChannelHandlerContext: Class 'io.netty.channel.ChannelHandlerContext' could not be found in the archives of the old API. It has been detected as contributing to the API and thus the analysis results may be incorrect.
[ERROR] java.missing.oldClass: missing-class io.netty.channel.socket.SocketChannel: Class 'io.netty.channel.socket.SocketChannel' could not be found in the archives of the old API. It has been detected as contributing to the API and thus the analysis results may be incorrect.
[ERROR] java.missing.oldClass: missing-class io.netty.handler.codec.http.HttpObject: Class 'io.netty.handler.codec.http.HttpObject' could not be found in the archives of the old API. It has been detected as contributing to the API and thus the analysis results may be incorrect.
[ERROR] java.missing.oldSuperType: class io.netty.testsuite.svm.HttpNativeServerHandler: Class inherits from 'io.netty.channel.SimpleChannelInboundHandler.SimpleChannelInboundHandler<io.netty.handler.codec.http.HttpObject>' which was not found in the supplied archives of the old API. Analysis may be incorrect. https://revapi.org/revapi-java/differences.html#java.missing.oldSuperType
[ERROR] java.method.finalMethodAddedToNonFinalClass: method void io.netty.channel.ChannelInitializer<C extends io.netty.channel.Channel>::channelRegistered(io.netty.channel.ChannelHandlerContext) throws java.lang.Exception @ io.netty.testsuite.svm.HttpNativeServerInitializer: A final method has been added to an inheritable class. https://revapi.org/revapi-java/differences.html#java.method.finalMethodAddedToNonFinalClass
[ERROR] java.missing.oldSuperType: class io.netty.testsuite.svm.HttpNativeServerInitializer: Class inherits from 'io.netty.channel.ChannelInitializer.ChannelInitializer<io.netty.channel.socket.SocketChannel>' which was not found in the supplied archives of the old API. Analysis may be incorrect. https://revapi.org/revapi-java/differences.html#java.missing.oldSuperType
[ERROR] 
[ERROR] Consult the plugin output above for suggestions on how to ignore the found problems.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :netty-testsuite-native-image

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/13258
