### ISSUE TITLE
HTTP/2 ALPN not working with BC FIPS TLS provider 

### ISSUE THREAD

**Issue by rajeshpnair** [netty/netty#13261]
### Expected behavior
Netty http/2 client includes the ALPN extension at the beginning of the TLS handshake to send a list of supported application protocols to the server as part of the ClientHello

### Actual behavior
Netty http/2 client does not include the ALPN extension at the beginning of the TLS handshake to send a list of supported application protocols to the server as part of the ClientHello when used with BC FIPS TLS provider (bctls-fips-1.0.13,jar)

### Steps to reproduce
Run a Netty based http/2 server  with multiple application protocols configured (http/1.1 , http/2)
Run a Netty based http/2 client  with multiple application protocols configured (http/1.1 , http/2)
The server and client is configured for TLS ,
Set crypto provider to bc-fips (bc-fips-1.0.2.3.jar)  , Set jsse provider BC FIPS TLS (bctls-fips-1.0.13)
The connection fails as the ALPN extension is not included in the client hello

### Minimal yet complete reproducer code (or URL to code)
https://github.com/rajeshpnair/nettyfipsissue/tree/main/HTTP2NettyTest

### Netty version
4.1.89

### JVM version (e.g. `java -version`)
11.0.16

### OS version (e.g. `uname -a`)
Windows_NT ICGLEBM432 10 00 x64

**Comment by rajeshpnair** [comment]
The issue seem to be with io.netty.handler.ssl.BouncyCastleAlpnSslUtils:
static void setApplicationProtocols(SSLEngine engine, List<String> supportedProtocols)  implementation resets the application protocol list in SSLParams object of the SSLEngine (ProvSSLEngine)  when it invokes , engine.setSSLParameters(parameters); 
The parameter object it caches with an initial invocation of engine.getSSLParameters(); does not have the supported application protocols correctly set. The issue is fixed if you set the application protocols in the SSLParams.

E.g.
String[] protocolArray = supportedProtocols.toArray(EmptyArrays.EMPTY_STRINGS); 
SET_SSLPARAMS_APPLICATION_PROTOCOLS.invoke(parameters, new Object[]{protocolArray});

**Comment by normanmaurer** [comment]
@rajeshpnair can you check https://github.com/netty/netty/pull/13262 ?
