### ISSUE TITLE
Is there a plan to support the sip protocol?

### ISSUE THREAD

**Issue by lixuanqun** [netty/netty#13271]

**Comment by Shoothzj** [comment]
@lixuanqun Maybe you will interesetd in https://github.com/aboutsip/sipstack/tree/master/sipstack-netty-codec-sip ?

**Comment by hyperxpro** [comment]
Nope, but contributions are welcome!

**Comment by lixuanqun** [comment]
> @lixuanqun Maybe you will interesetd in https://github.com/aboutsip/sipstack/tree/master/sipstack-netty-codec-sip ?


@Shoothzj   Yeah, that's it

**Comment by normanmaurer** [comment]
Like said above we are not planing to add it to Netty directly. That said it might be provided by another project that implements it as Netty codec.

**Comment by lixuanqun** [comment]
> Like said above we are not planing to add it to Netty directly. That said it might be provided by another project that implements it as Netty codec.

Yes, I understand.
