### ISSUE TITLE
New I/O client worker thread cpu 100%

### ISSUE THREAD

**Issue by uliyanjun** [netty/netty#13270]
Undertow server and java springboot application;
cpu usage 100% and memory used less than 10%

jstack info:

![b632eeb7e777d5aade64c24c17cef13](https://user-images.githubusercontent.com/31330070/224467560-f93efb45-62bb-46ba-a097-ee44c4443774.png)

Netty version: 3.2.1.Final

Jdk version: openjdk 1.8.0_292

OS : Docker container 2C 4G cnetos7

Any idea will be helpful!!!

**Comment by hyperxpro** [comment]
More information needed.
