### ISSUE TITLE
NPE in NetworkInterface.getNetworkInterfaces

### ISSUE THREAD

**Issue by Hartigan** [netty/netty#13272]
I face NPE during initialization of `netty` classes on Android in method `NetworkInterface.getNetworkInterfaces()`.
[Documentation](https://developer.android.com/reference/java/net/NetworkInterface#getNetworkInterfaces()) says:
```
ANDROID NOTE: On Android versions before S (API level 31), this method may throw a NullPointerException if called in an environment where there is a virtual interface without a parent interface present.
```
Would be nice too catch this NPE in `NetUtilInitializations.java`.

### Expected behavior
No NPE

### Actual behavior
NPE on some android devices

### Steps to reproduce
I have no devices to reproduce by myself, but exception documented in code.

### Netty version
`4.1.82`

### JVM version (e.g. `java -version`)
Android API level <31

### OS version (e.g. `uname -a`)
Android version <12

**Comment by normanmaurer** [comment]
Working on a fix

**Comment by normanmaurer** [comment]
@Hartigan thanks for reporting... Fixed by https://github.com/netty/netty/pull/13278

**Comment by Hartigan** [comment]
Thanks
