### ISSUE TITLE
Socks5ProxyHandler May need repair

### ISSUE THREAD

**Issue by small-thunder** [netty/netty#13287]
### Expected behavior
client send username and password, but server authMethod is NO_AUTH; connect success

### Actual behavior
can not connected, fail
### Minimal yet complete reproducer code (or URL to code)
![img_v2_0273bdb3-318d-46bf-8788-602e9116149g](https://user-images.githubusercontent.com/43597696/226239413-a5103792-4606-4626-b47c-6df86670e3d7.jpg)
![img_v2_3011d3eb-3b79-44b6-99cf-89087dddf77g](https://user-images.githubusercontent.com/43597696/226239418-a32d9fdc-0098-4ba9-b97a-1d5f02e48174.jpg)

### Netty version
all
### JVM version (e.g. `java -version`)
jdk8

**Comment by normanmaurer** [comment]
Please provide some more details on what exactly is the issue.

**Comment by small-thunder** [comment]
client is send username and password,

**Comment by normanmaurer** [comment]
I am still not getting it... Can you maybe provide a PR with a unit test and change ?

**Comment by small-thunder** [comment]
> I am still not getting it... Can you maybe provide a PR with a unit test and change ?
![image](https://user-images.githubusercontent.com/43597696/226658244-710cce31-33c3-4182-9ef4-3ba2714d319c.png)

This is what I changed
