### ISSUE TITLE
why the netty always treat the ping message as text frame

### ISSUE THREAD

**Issue by jiangxiaoqiang** [netty/netty#13286]
### Expected behavior

the netty treat the ping message as control frame.

### Actual behavior

the netty treat the ping message as text frame.

### Steps to reproduce

1. send message from client side like this

```

const heartbeatInterval = setInterval(() => {
            if (chatWebsocket && chatWebsocket.readyState === WebSocket.OPEN) {
                const pingFrame = new ArrayBuffer(2);
                const pingView = new DataView(pingFrame);
                pingView.setInt8(0, 0x89);
                pingView.setInt8(1, 0);
                chatWebsocket.send(pingFrame);
            }
        }, HEARTBEAT_INTERVAL_MS);


```

2. check the frame type on the server side like this;

 ```
@Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
        if (null != msg && msg instanceof FullHttpRequest) {
            FullHttpRequest request = (FullHttpRequest) msg;
            String uri = request.uri();
            Map paramMap=getUrlParams(uri);
            if(uri.contains("?")){
                String newUri=uri.substring(0,uri.indexOf("?"));
                System.out.println(newUri);
                request.setUri(newUri);
            }
        }else if(msg instanceof TextWebSocketFrame){
            TextWebSocketFrame frame=(TextWebSocketFrame)msg;
        }else if(msg instanceof PingWebSocketFrame){
            PingWebSocketFrame frame=(PingWebSocketFrame)msg;
        }
        super.channelRead(ctx, msg);
    }

```

### Minimal yet complete reproducer code (or URL to code)

not a minimal reproduce but more detail info: https://stackoverflow.com/questions/75784687/am-i-using-the-correct-way-to-send-a-ping-frame-with-websocket

### Netty version

implementation 'io.netty:netty-all:4.1.65.Final'

### JVM version (e.g. `java -version`)

Java 11

### OS version (e.g. `uname -a`)

macOS 13.2

**Comment by normanmaurer** [comment]
Netty is just parsing protocol which means it was encoded on the sending side as a text frame. You will need to figure out how to fix this on the sending side.
