### ISSUE TITLE
Whether there keys and certs are security risks

### ISSUE THREAD

**Issue by ywb123** [netty/netty#13280]
https://github.com/netty/netty/blob/a7cdfc153c9980b7a781afa280d595efc870567c/handler/src/main/java/io/netty/handler/ssl/OpenSsl.java#L121
What are the functions of the two lines of keys and certs hardcoded?
Whether there are security risks.

**Comment by hyperxpro** [comment]
These are for internal self-signed certs and are not "SECURITY RISK".

**Comment by normanmaurer** [comment]
These keys / certs are only used to test if some features are supported or not. So no security risk
