### ISSUE TITLE
Netty 5 Kqueue

### ISSUE THREAD

**Issue by NotArchon** [netty/netty#13291]
### Expected behavior
Netty5 doesn't appear to have kqueue. Is this intentional? Epoll was carried over.

### OS version (e.g. `uname -a`)
mac osx aarch64

**Comment by normanmaurer** [comment]
It is here https://github.com/netty/netty/tree/main ?

**Comment by NotArchon** [comment]
The last build it's part of is 4.9.0

https://github.com/netty/netty/blob/netty-4.1.90.Final/transport-classes-kqueue/src/main/java/io/netty/channel/kqueue/KQueueEventLoop.java

**Comment by NotArchon** [comment]
Changed my dependency to alpha5. I'm able to use KQueue now.
