### ISSUE TITLE
Missing support for java.net.preferIPv6Addresses=system  (OpenJDK 11)

### ISSUE THREAD

**Issue by alrossi** [netty/netty#13300]
### Expected behavior

OpenJDK 11 allows specifying

```
java.net.preferIPv6Addresses=system
```

https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/net/InetAddress.java

So setting it this way should be supported.

### Actual behavior

```
grep 'preferIPv6Addresses' /usr/share/dcache/defaults/*
/usr/share/dcache/defaults/dcache.properties:    -Djava.net.preferIPv6Addresses=system \
```

results in

```
[] Unable to parse the boolean system property 'java.net.preferIPv6Addresses':system - using the default value: false
```

### Steps to reproduce

Start the JVM with this property set to `system`

### Netty version

4.1.77.Final

### JVM version (e.g. `java -version`)

```
java -version 
openjdk version "11.0.14.1" 2022-02-08 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.14.1+1-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.14.1+1-LTS, mixed mode, sharing)
```

### OS version (e.g. `uname -a`)

```
Linux cmsdcadisk01new.fnal.gov 3.10.0-1160.81.1.el7.x86_64 #1 SMP Tue Dec 13 09:53:21 CST 2022 x86_64 x86_64 x86_64 GNU/Linux
```

It would seem that the internal `getBoolean` method defeats this

http://www.java2s.com/example/java-src/pkg/io/netty/util/internal/systempropertyutil-86905.html

**Comment by normanmaurer** [comment]
PTAL https://github.com/netty/netty/pull/13301
