### ISSUE TITLE
Extend decompression of HttpContentDecompressor.java

### ISSUE THREAD

**Issue by redcinelli** [netty/netty#13307]
### Actual behaviour

At the moment the [HttpContentDecompressor.java](https://github.com/netty/netty/blob/cf5c467f4ead5ba5e1e36f5c4903af78bd49c35c/codec-http/src/main/java/io/netty/handler/codec/http/HttpContentDecompressor.java#LL58C9-L73) support:

- deflate
- gzip
- brotli

I wonder if we should extend it ?
I am specifically in need of supporting `snappy` 

```java
        if (GZIP.contentEqualsIgnoreCase(contentEncoding) ||
            X_GZIP.contentEqualsIgnoreCase(contentEncoding)) {
            return new EmbeddedChannel(ctx.channel().id(), ctx.channel().metadata().hasDisconnect(),
                    ctx.channel().config(), ZlibCodecFactory.newZlibDecoder(ZlibWrapper.GZIP));
        }
        if (DEFLATE.contentEqualsIgnoreCase(contentEncoding) ||
            X_DEFLATE.contentEqualsIgnoreCase(contentEncoding)) {
            final ZlibWrapper wrapper = strict ? ZlibWrapper.ZLIB : ZlibWrapper.ZLIB_OR_NONE;
            // To be strict, 'deflate' means ZLIB, but some servers were not implemented correctly.
            return new EmbeddedChannel(ctx.channel().id(), ctx.channel().metadata().hasDisconnect(),
                    ctx.channel().config(), ZlibCodecFactory.newZlibDecoder(wrapper));
        }
        if (Brotli.isAvailable() && BR.contentEqualsIgnoreCase(contentEncoding)) {
            return new EmbeddedChannel(ctx.channel().id(), ctx.channel().metadata().hasDisconnect(),
              ctx.channel().config(), new BrotliDecoder());
        }
```

I am opening this issue to talk about that.
Is it something Netty would be interested in seeing happening ?
I could be doing the PR if needed.

### Netty version

4.1

**Comment by hyperxpro** [comment]
Extend the `HttpContentDecompressor` and override the `newContentDecoder` for Snappy and delegate the rest to `super#newContentDecoder`.

**Comment by redcinelli** [comment]
> Extend the `HttpContentDecompressor` and override the `newContentDecoder` for Snappy and delegate the rest to `super#newContentDecoder`.

Thanks for the guidance @hyperxpro, I assume this means Pr's are welcome ? I'll be working on it then ^^

**Comment by hyperxpro** [comment]
They're! ^^
