### ISSUE TITLE
java.security.cert.CertificateException: X.509 not found

### ISSUE THREAD

**Issue by sankar-gp** [netty/netty#13311]
### I'm trying to create a self signed certificate programatically in android using java

private SslContext getSslContext() throws CertificateException, SSLException {
        SelfSignedCertificate ssc = new SelfSignedCertificate();
        return SslContextBuilder.forServer(ssc.certificate(), ssc.privateKey()).protocols("TLSv1.2").build();
    }

I'm getting following error

cause = {CertificateException@24605} "java.security.cert.CertificateException: X.509 not found"
detailMessage = "No provider succeeded to generate a self-signed certificate. See debug log for the root cause."

### JVM version
 java version "11.0.12" 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

### OS version 
Darwin. XXXXXXX 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

**Comment by hyperxpro** [comment]
Please upgrade to Netty 4.1.91.Final.

**Comment by hyperxpro** [comment]
Sorry, my bad. It's 4.1.90.Final. ;/

**Comment by sankar-gp** [comment]
I tried 4.1.90.Final - Still i'm getting the error 

Execution failed for task ':app:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeJavaResWorkAction
   > 33 files found with path 'META-INF/INDEX.LIST' from inputs:

**Comment by hyperxpro** [comment]
Paste full log

**Comment by chrisvest** [comment]
Add `org.bouncycastle:bcprov-jdk15on:1.69` and `org.bouncycastle:bcpkix-jdk15on:1.69` dependencies.
