### ISSUE TITLE
How to add netty dependency in android

### ISSUE THREAD

**Issue by sankar-gp** [netty/netty#13310]
### I need to know how to create self signed certificate programatically in android (java)

Can you please help me on creating a self signed certificate programatically in Android using JAVA. 
Also i need to add netty in my android project for creating self signed certificate.

**Comment by hyperxpro** [comment]
Add Netty dependency to Grade.

Also, is Darwin on Android or I'm missing something?

**Comment by sankar-gp** [comment]
is this correct?? 

implementation group: 'io.netty', name: 'netty-all', version: '4.1.90.Final'
