### ISSUE TITLE
Possible issues with SelectedSelectionKeySet in non-linux operating systems

### ISSUE THREAD

**Issue by ramizdundar** [netty/netty#13328]
`SelectedSelectionKeySet` doesn't implement `contains()` method. Or at least it returns always false. This may create issues in non-linux operating systems.

To give you more context, in my work, like you do, we try to not produce garbage by replacing `HashSet` with something similar to `SelectedSelectionKeySet`. Actually this trick is something we learned from netty.

So while investigating a recent bug, I realized lack of correct implementation of `contains()` method creates problems in macos (and very possibly windows as well). I tried to summarize my finding in here: https://github.com/hazelcast/hazelcast/pull/24267

I do think this issue effects netty as well.

**Comment by chrisvest** [comment]
Good find, we'll take a look.
