### ISSUE TITLE
Netty handler vulnerability, please fix it as soon as possible, which has resulted in the inability to upload sonatype. Thank you very much

### ISSUE THREAD

**Issue by twelvet-s** [netty/netty#13322]
https://ossindex.sonatype.org/vulnerability/sonatype-2020-0026?component-type=maven&component-name=io.netty%2Fnetty-handler&utm_source=ossindex-client&utm_medium=integration&utm_content=1.7.0

The SSL vulnerability detected by sonatype has always been a dependency. Can you resolve it? Thank you

**Comment by hyperxpro** [comment]
This is not a vulnerability, certificate validation is just disabled by default.

**Comment by twelvet-s** [comment]
> This is not a vulnerability, certificate validation is just disabled by default.

ok Thank
