### ISSUE TITLE
java.net.BindException: Address already in use: bind，netty tcp port multiplexing cannot take effect

### ISSUE THREAD

**Issue by zzy444626905** [netty/netty#13330]
### Minimal yet complete reproducer code (or URL to code)
        EventLoopGroup bossGroup = new NioEventLoopGroup();
        EventLoopGroup workerGroup = new NioEventLoopGroup();
            ServerBootstrap b = new ServerBootstrap();
            b.group(bossGroup, workerGroup)
                    .channel(NioServerSocketChannel.class)
                    .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, CONNECT_TIMEOUT_MILLIS)
                    .option(NioChannelOption.SO_REUSEADDR, true)
                    .option(EpollChannelOption.SO_REUSEPORT, true)
                    .option(EpollChannelOption.SO_REUSEADDR, true)
                    .option(ChannelOption.RCVBUF_ALLOCATOR, new FixedRecvByteBufAllocator(RCVBUF_ALLOCATOR))
                    .option(ChannelOption.SO_BACKLOG, 100)
                    .childHandler(new ChannelInitializer<SocketChannel>() {
                        @Override
                        public void initChannel(SocketChannel ch) throws Exception {
                            ch.pipeline().addLast(
                                    PipelineUtils.getIdleStateHandler(),
                                    new HttpProxyServerHandler()
                            );
                        }
                    }).bind(port).sync().channel().closeFuture().sync();
### Netty version
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.50.Final</version>
        </dependency>
### JVM version (e.g. `java -version`)
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
### OS version (e.g. `uname -a`)
windows10

**Comment by chrisvest** [comment]
You can't use EpollChannelOprions with Nio channels/event loops.
If you want that option you need to use the epoll channels and the epoll event loop.

**Comment by chrisvest** [comment]
I see you're using Windows as well. Epoll is not supported on Windows, only Nio works there, and `SO_REUSEPORT` is not supported on Nio, so there's no supported way for you to do this.
