### ISSUE TITLE
java.net.BindException: Address already in use: bind when set ChannelOption.SO_REUSEADDR=true,it does not work

### ISSUE THREAD

**Issue by zzy444626905** [netty/netty#13332]
### Minimal yet complete reproducer code (or URL to code)
        EventLoopGroup bossGroup = new NioEventLoopGroup();
        EventLoopGroup workerGroup = new NioEventLoopGroup();
        try {
            ServerBootstrap b = new ServerBootstrap();
            b.group(bossGroup, workerGroup)
                    .channel(File.separatorChar == '/' ? EpollServerSocketChannel.class : NioServerSocketChannel.class)
//                    .handler(new LoggingHandler(LogLevel.INFO))
                    .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, CONNECT_TIMEOUT_MILLIS)
                    .option(ChannelOption.TCP_NODELAY, true)
                    .option(ChannelOption.SO_REUSEADDR, true)
                    .option(EpollChannelOption.SO_REUSEPORT, true)
                    .option(EpollChannelOption.SO_REUSEADDR, true)
                    .option(ChannelOption.RCVBUF_ALLOCATOR, new FixedRecvByteBufAllocator(RCVBUF_ALLOCATOR))
                    .option(ChannelOption.SO_BACKLOG, 100)
                    .childHandler(new ChannelInitializer<SocketChannel>() {
                        @Override
                        public void initChannel(SocketChannel ch) throws Exception {
                            ch.pipeline().addLast(
//                                    new LoggingHandler(LogLevel.DEBUG),
                                    PipelineUtils.getIdleStateHandler(),
//                                    PipelineUtils.getDecoder(),
                                    new HttpProxyServerHandler()
                            );
                        }
                    }).bind(new InetSocketAddress("0.0.0.0", port)).sync().channel().closeFuture().sync();
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            bossGroup.shutdownGracefully();
            workerGroup.shutdownGracefully();
        }
### Netty version
<artifactId>netty-all</artifactId>
<version>4.1.50.Final</version>
### JVM version (e.g. `java -version`)
jdk1.8.0.211
### OS version (e.g. `uname -a`)
win10

**Comment by hyperxpro** [comment]
Windows does not support SO_REUSEPORT.

**Comment by zzy444626905** [comment]
> Windows does not support SO_REUSEPORT.

old brother ，are you kidding me？many nginx.exe running on windows

**Comment by hyperxpro** [comment]
Then please show the Nginx code where it uses SO_REUSEPORT on Windows. :)

Here is the Nginx repo link to make your task easier: https://github.com/nginx/nginx

**Comment by zzy444626905** [comment]
like golang code

	cfg := net.ListenConfig{
		Control: func(network, address string, c syscall.RawConn) error {
			return c.Control(func(fd uintptr) {
				syscall.SetsockoptInt(syscall.Handle(int(fd)), syscall.SOL_SOCKET, syscall.SO_REUSEADDR, 1)
				syscall.SetsockoptInt(syscall.Handle(int(fd)), syscall.SOL_SOCKET, syscall.SO_REUSEPORT, 1)
			})
		},
	}

**Comment by zzy444626905** [comment]
> Then please show the Nginx code where it uses SO_REUSEPORT on Windows. :)
> 
> Here is the Nginx repo link to make your task easier: https://github.com/nginx/nginx

like golang code

cfg := net.ListenConfig{
	Control: func(network, address string, c syscall.RawConn) error {
		return c.Control(func(fd uintptr) {
			syscall.SetsockoptInt(syscall.Handle(int(fd)), syscall.SOL_SOCKET, syscall.SO_REUSEADDR, 1)
			syscall.SetsockoptInt(syscall.Handle(int(fd)), syscall.SOL_SOCKET, syscall.SO_REUSEPORT, 1)
		})
	},
}

**Comment by surajkumar** [comment]
It's true, Windows does not support SO_REUSEPORT. Try the following java.net example:

```
import java.io.IOException;
import java.net.*;

public class Main {
  public static void main(String[] args) throws IOException {
      ServerSocket serverSocket = new ServerSocket();
      serverSocket.bind(new InetSocketAddress(8080));
      while(true) {
          Socket socket = serverSocket.accept();
          socket.setOption(StandardSocketOptions.SO_REUSEPORT, true);
          // ...
      }
  }
}```

You'll get an exception: "Exception in thread "main" java.lang.UnsupportedOperationException: 'SO_REUSEPORT' not supported"

"java.net.BindException: Address already in use" is a very misleading error message none the less.

**Comment by zzy444626905** [comment]
> It's true, Windows does not support SO_REUSEPORT. Try the following java.net example:
> 
> ```
> import java.io.IOException;
> import java.net.*;
> 
> public class Main {
>   public static void main(String[] args) throws IOException {
>       ServerSocket serverSocket = new ServerSocket();
>       serverSocket.bind(new InetSocketAddress(8080));
>       while(true) {
>           Socket socket = serverSocket.accept();
>           socket.setOption(StandardSocketOptions.SO_REUSEPORT, true);
>           // ...
>       }
>   }
> }
> ```
> 
> You'll get an exception: "Exception in thread "main" java.lang.UnsupportedOperationException: 'SO_REUSEPORT' not supported"
> 
> "java.net.BindException: Address already in use" is a very misleading error message none the less.

I see, Thank you very much!

**Comment by chrisvest** [comment]
Windows supports `SO_REUSEADDR` as a slightly worse (uncooperative) version of `SO_REUSEPORT`: https://learn.microsoft.com/en-us/windows/win32/winsock/using-so-reuseaddr-and-so-exclusiveaddruse

On Windows we only support the Nio transport, so you cannot use the Epoll channel or socket options.

What do you get when you run the following on Windows?

```java
ServerSocket a = new ServerSocket();
a.setOption(StandardSocketOptions.SO_REUSEPORT, true);
a.bind(new InetSocketAddress(8080));
ServerSocket b = new ServerSocket();
b.setOption(StandardSocketOptions.SO_REUSEPORT, true);
b.bind(new InetSocketAddress(8080));
```

**Comment by normanmaurer** [comment]
That said you can use `NioChannelOption.of(...)` to use any `SocketOption` as long as its supported by the JDK

**Comment by chrisvest** [comment]
We also expose it as `ChannelOption.SO_REUSEADDR`
