### ISSUE TITLE
Should HttpRequestEncoder strip Content-Length headers on GET requests

### ISSUE THREAD

**Issue by nicholashagen** [netty/netty#13340]
Currently, if you make a `GET` request to a server and for some reason add a `Content-Length` header, but do not send a payload (which is not possible when using `GET`), then Netty sends the header to the server.  This results in the server waiting to receive the payload (one could argue the server should just drop these requests as well, but apparently some do not).  For example, there is this Spring ticket where they also encounter this issue: https://github.com/spring-projects/spring-framework/issues/25023#issuecomment-1173865081.

Essentially if you use WebClient (Netty-based) and pass headers through, a request could attempt a request to `GET` with `{}` payload and `Content-Length: 2`.  This results in the first request passing and then the next request reads the first two bytes `GE` and then uses the remainder as the request yielding `T /foo` since the `GE` portion mistaken for the prior content-length.

Currently, there is similar behavior in the response encoder : https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpResponseEncoder.java#L51

However, the request encoder is a noop: https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectEncoder.java#L554 (the `HttpRequestEncoder` does not override)

According to the RFC (https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.2), it says:

> A user agent SHOULD NOT send a Content-Length header field when the request message does not contain a payload body and the method semantics do not anticipate such a body.

Depending on how that is read, it is possible that a `GET` request should not send a payload and thus be stripped.  There is an exception for `HEAD` requests, however.

### Expected behavior

`Content-Length` headers, when added explicitly, are stripped before the HTTP request is sent on `GET` requests

### Actual behavior

`Content-Length` headers are sent.

### Steps to reproduce

1. Setup a Netty HTTP request pipeline (or use WebClient)
2. Create a `GET` request
3. Add a `Content-Length: 2` header
4. Fetch the data (Verify data is received)
5. Make a second request on the same connection
6. Observe that the server most likely fails due to `T` not supported method

### Minimal yet complete reproducer code (or URL to code)

WebClient:
```
String test1 = webclient.get().uri("/api/foo")
                .headers(h -> h.put("content-length", 2))
                .retrieve().bodyToMono(String.class).block();

// test1 should pass

String test2 = webclient.get().uri("/api/foo")
                .retrieve().bodyToMono(String.class).block();

// test2 should be a failure
```
### Netty version

4.1.90 or anything current

### JVM version (e.g. `java -version`)

17, but any version should yield the issue

### OS version (e.g. `uname -a`)

Mac M1, but any OS should result in same issue

**Comment by normanmaurer** [comment]
We usually don't try to enforce anything on the sending side.

**Comment by lyzzz0101** [comment]
got same issue here but with POST method

`container_ip：10.10.33.205
container_name： ish-intelligence-store-platform-admin-web
image_name：tastien-registry-vpc.cn-shanghai.cr.aliyuncs.com/tst-uat/ish-intelligence-store-platform-admin-web:5322
pod_name：ish-intelligence-store-platform-admin-web-6d8d47d954-h8g76
pod_uid：4a8cb38e-fe5c-4e10-b139-e4bf9c140f42
source：stdout
time：2024-09-24T01:16:53.710284065Z
app_id：intelligence-store-platform-admin-web
content：2024-09-24 09:16:53.709 ERROR [intelligence-store-platform-admin-web] [http-nio-8080-exec-187] [07452746a8fbdc11402d448032ddef1f] [||] c.s.i.a.a.WebExceptionHandler -  系统异常 原因：null uri:/intelligence/member/login,堆栈：Request method 'O' not supported
org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'O' not supported
	at org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping.handleNoMatch(RequestMappingInfoHandlerMapping.java:197)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.lookupHandlerMethod(AbstractHandlerMethodMapping.java:379)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:318)
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:62)
	at org.springframework.web.servlet.handler.AbstractHandlerMapping.getHandler(AbstractHandlerMapping.java:350)
	at org.springfram
log_level：ERROR
logger_class：c.s.i.a.a.WebExceptionHandler
message：null
thread：http-nio-8080-exec-187
time：2024-09-24 09:16:53.709
trace_id：07452746a8fbdc11402d448032ddef1f`
