### ISSUE TITLE
Netty support javax.net.SocketFactory 

### ISSUE THREAD

**Issue by hongphu8790** [netty/netty#13341]
### Expected behavior

I am using netty for a project on Android platform, all things are implemented such socks 5 server.

But i want to use `javax.net.SocketFactory` same as `OkHttpClient` with `socketFactory` reference [here](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/socket-factory/) to access specific network such cellular on Android.

I have tried to find a method of netty support `socketFactory` like `OkHttpClient` but no luck. Could you give me some solution about this?

```
 OkHttpClient client = new OkHttpClient.Builder()
                            .socketFactory(network.getSocketFactory())
                            .build();
```

**Comment by normanmaurer** [comment]
Netty does not use Sockets under the hood so this is not possible
