### ISSUE TITLE
io.netty.util.collection is not exist

### ISSUE THREAD

**Issue by wuhwAndGod** [netty/netty#13342]
i want improt 4.1.89.final to idea,but i have some problem.when i run the example module -> EchoServer.main()，it is error
![微信截图_20230419140230](https://user-images.githubusercontent.com/48238486/232980952-1027c555-e82e-4fb8-8158-3f850edc6947.png)
i see other issues to handle this problem, go into the common,and mvn clean package,i do it ,and there are some classes generate in the target,but it is still wrong.
![微信截图_20230419140316](https://user-images.githubusercontent.com/48238486/232980840-ac025f40-d4ee-4235-85ae-e3178342f177.png)
can someone  has the same situation,can you help me

**Comment by hyperxpro** [comment]
It is auto-generated during the build.

**Comment by hyperxpro** [comment]
English please

**Comment by wuhwAndGod** [comment]
> English please

Hello, thanks for the reply, the build process is triggered when the main method is executed? I'm just doing the main method by mistake right now

**Comment by hyperxpro** [comment]
Just use Netty dependency, why are you using the entire code base in your project?

**Comment by wuhwAndGod** [comment]
I'm not using it for projects, I want to learn the source code myself, so instead of importing dependencies, I import and compile the source code

**Comment by hyperxpro** [comment]
Follow this: https://netty.io/wiki/developer-guide.html

**Comment by wuhwAndGod** [comment]
Uninstall the maven helper plugin and compile and build it with the native maven command，it is ok
