### ISSUE TITLE
in io.netty.example.http.file.HttpStaticFileServerHandler class , variable RandomAccessFile raf not close

### ISSUE THREAD

**Issue by jiayaoguang** [netty/netty#13354]
in io.netty.example.http.file.HttpStaticFileServerHandler class , variable RandomAccessFile raf not close

**Comment by chrisvest** [comment]
That is fine.
`ChunkedFile` will close it directly. Or `DefaultFileRegion` will close its channel, which closes its parent, which is the `RandomAccessFile`.
