### ISSUE TITLE
UnpaddedInternalThreadLocalMap.nextIndex should not be static

### ISSUE THREAD

**Issue by magiczhangx** [netty/netty#13374]
### Expected behavior
UnpaddedInternalThreadLocalMap.nextIndex should not be static

### Actual behavior
UnpaddedInternalThreadLocalMap.nextIndex is static.

FastThreadLocal use this static nextIndex to initiate index
```java
    public FastThreadLocal() {
        index = InternalThreadLocalMap.nextVariableIndex();
    }
```

When set value , there possible cause many expand action:
```java
    public boolean setIndexedVariable(int index, Object value) {
        //****************************************************************
        //the default length of lookup is 32
        //****************************************************************
        Object[] lookup = indexedVariables; 
        if (index < lookup.length) {
            Object oldValue = lookup[index];

             /****************************************************************
              because index is generated by a static variable , when index is 31 ,
             it's possible that 1 ~ 30 occupied by other thread , so here may wast many slots , 
             especially when there are many threads and every thread have some FastThreadLocals.
           ***************************************************************/
            lookup[index] = value; 
            return oldValue == UNSET;
        } else {
           //****************************************************************
           //If there are more than 32 FastThreadLocals , then the next new FastThreadLocals will expand every time.
           //****************************************************************
            expandIndexedVariableTableAndSet(index, value);
            return true;
        }
    }
```

### Netty version
4.1.92.Final

**Comment by chrisvest** [comment]
There is an index per thread-local, not per thread. This is how threads are able to tell thread-locals apart.

**Comment by magiczhangx** [comment]
> There is an index per thread-local, not per thread. This is how threads are able to tell thread-locals apart.

but the initial value of index if from a static Integer , UnpaddedInternalThreadLocalMap.nextIndex

this nextIndex will becaom bigger and bigger by using times of thread-local

**Comment by chrisvest** [comment]
> this nextIndex will becaom bigger and bigger by using times of thread-local

Yes, it is best to avoid creating an unbounded number of FastThreadLocal objects. Their number should ideally be finite and small.

**Comment by magiczhangx** [comment]
Why Netty don't design nextIndex to be a non-static Integer? 
In non-static nextIndex way, FastThreadLocal can fully utilize UnpaddedInternalThreadLocalMap.indexedVariables.

In current static way , some slots of UnpaddedInternalThreadLocalMap.indexedVariables may be wasted.

**Comment by magiczhangx** [comment]
```java
    public boolean setIndexedVariable(int index, Object value) {
        Object[] lookup = indexedVariables;
        if (index < lookup.length) {
            Object oldValue = lookup[index];
            lookup[index] = value;
            return oldValue == UNSET;
        } else {
            expandIndexedVariableTableAndSet(index, value);
            return true;
        }
    }
```
See this function,   
lookup[index] = value ,  that means  lookup[1 ...... index-1] are all UNSET and never use them, a little strange at here?

**Comment by chrisvest** [comment]
Say you have FastThreadLocal A and B.
And two threads T1 and T2.
If T1 initialises A, and T2 initialises B, and then T1 accesses B, then T1 will find that B has the same value as what A was initialised to.

In the _best_ case this will cause a ClassCastException, and worst case who knows what problems random data sharing could cause.

**Comment by chrisvest** [comment]
The array is per thread, and each FastThreadLocal is an index into the array.

**Comment by trustin** [comment]
I guess @magiczhangx is concerned about having too large index number for a thread with just a few fast thread local variables. That's actually how `FastThreadLocal` is at the moment. 

We could maybe improve this sparseness by keeping a `Map<FastThreadLocal, Integer>` in `InternalThreadLocalMap`, but it will likely make it not 'fast' anymore given its overhead? Please feel free to experiment and let us know if you found a way to make it as fast as before while making it more compact.
