### ISSUE TITLE
java.lang.UnsupportedOperationException: sun.misc.Unsafe unavailable while using '-Dio.netty.noUnsafe=true'

### ISSUE THREAD

**Issue by T3P0X** [netty/netty#13378]
### Expected behavior
when using `-Dio.netty.noUnsafe=true` the following exception should not be thrown:
```
java.lang.UnsupportedOperationException: sun.misc.Unsafe unavailable
	at io.netty.util.internal.CleanerJava9.<clinit>(CleanerJava9.java:68)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:193)
```
### Actual behavior
So as i understand this is a debug log and does not impact functionality (only optimization) but when using `-Dio.netty.noUnsafe=true` the following exception is thrown, its unclear if this can be ignored and if it can be why not catch it, as we already explicitly say to not use unsafe:
```
java.lang.UnsupportedOperationException: sun.misc.Unsafe unavailable
	at io.netty.util.internal.CleanerJava9.<clinit>(CleanerJava9.java:68)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:193)
```
### Steps to reproduce
start java with property `-Dio.netty.noUnsafe=true`
### Minimal yet complete reproducer code (or URL to code)
n.a.
### Netty version
Netty 4.1.92.Final 
### JVM version (e.g. `java -version`)
11.0.3
### OS version (e.g. `uname -a`)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"

**Comment by normanmaurer** [comment]
@T3P0X I am not sure why you say this exception is thrown... its only logged in debug mode as the usage of sun.misc.Unsafe is not supported .

**Comment by normanmaurer** [comment]
Please reopen if you still think there is a problem

**Comment by MarioNocnik** [comment]
looks more like a System.err to me, not a log?
