### ISSUE TITLE
Getting OutOfMemoryError for netty 5.0.0 alpha 2

### ISSUE THREAD

**Issue by monalisha1994** [netty/netty#13387]

**Comment by monalisha1994** [comment]
Getting below error, My requirement is to stop the service on this scenario.
Is there a way to catch the error and write logic based on that

java.lang.OutOfMemoryError: Direct buffer memory 
 INITIAL_STACKTRACE:-
 io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:234)
io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:389)
io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:956)
io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:127)
io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514)
io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471)
io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385)
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351)
io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280)
io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877)
io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706)
io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661)
io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126)

**Comment by franz1981** [comment]
Are you using virtual threads as thread pools to run Netty?

Il gio 18 mag 2023, 09:49 anonymousJava ***@***.***> ha
scritto:

**Comment by chrisvest** [comment]
Your "netty 5" is _very_ outdated. The Netty 5 alphas we've been working on recently all use `io.netty5` for the package name.

I recommend sticking for the latest 4.1 for the time being.
