### ISSUE TITLE
Unable to supply resolveCache to DnsNameResolverBuilder and use TTL's for other two caches

### ISSUE THREAD

**Issue by samueldlightfoot** [netty/netty#13384]
### Expected behavior

If a resolveCache is set in the DnsNameResolverBuilder the min, max and negative TTL fields must be null. However, this means the cname cache and authoritative DNS server cache will be built with default (fallback) TTLs as opposed to a TTL which the user may want to set.

I'd expect to be able to provide the resolveCache and also TTL's which should be applied to the cname and authoritative DNS server caches.  This is not possible due to the following code:

```
       if (resolveCache != null && (minTtl != null || maxTtl != null || negativeTtl != null)) {
            throw new IllegalStateException("resolveCache and TTLs are mutually exclusive");
        }

        if (authoritativeDnsServerCache != null && (minTtl != null || maxTtl != null || negativeTtl != null)) {
            throw new IllegalStateException("authoritativeDnsServerCache and TTLs are mutually exclusive");
        }
```

This means the building of the cname cache is forced to use default values (0, Integer.MAX_VALUE)

```
    private DnsCnameCache newCnameCache() {
        return new DefaultDnsCnameCache(
                intValue(minTtl, 0), intValue(maxTtl, Integer.MAX_VALUE));
    }
```

### Steps to reproduce

Use DnsNameResolverBuilder to with a supplied resolveCache and minTtl, maxTtl or negativeTtl values.

### Netty version

4.1.92

**Comment by trustin** [comment]
You can specify a CNAME cache by calling `DnsNameResolverBuilder.cnameCache(DnsCnameCache)`, specifying `new DefaultDnsCnameCache()` with the desired min/max TTL values. Would this work for you?

**Comment by samueldlightfoot** [comment]
Thanks for the response, Trustin. This would work, but it feels like a workaround as opposed to allowing ttl values to be set for the other caches via the ttl fields

**Comment by violetagg** [comment]
@trustin I think it is a bit inconvenient to have configured either all types of caches or to leave them all default based on the TTLs. I prepared one change can you take a look at this #13386?
