### ISSUE TITLE
SpringBoot整合netty作为client连接服务器

### ISSUE THREAD

**Issue by joinGitHub01** [netty/netty#13391]
###  When I connect the Server for the sencond time(I use `ctx.channel().close()` closed the first channel before)，it  throw "io.netty.channel.StacklessclosedchannelException" exception,and `channelFuture.isSuccess() == false` in method `operationComplete`

使用springboot框架，作为客户端连接服务端，定时任务调用方法触发连接服务器，第一次触发时，一切正常，可以连接成功，也可以正确发送命令，然后使用`ctx.channel().close()`关闭channel。第二次触发的时候连接就失败了，也就是调用，报了`io.netty.channel.StacklessclosedchannelException`，查了资料说是试图往已关闭的通道中写数据，不知道为什么

**Comment by violetagg** [comment]
Please provide reproducible example.

**Comment by hyperxpro** [comment]
Please use English

**Comment by joinGitHub01** [comment]
I already solved this problem. Thank you for responding.

**Comment by pigletO** [comment]
@joinGitHub01 I had the same problem. How did you solve it?
