### ISSUE TITLE
Derived buffers are less likely to be selected for leak tracking

### ISSUE THREAD

**Issue by rdicroce** [netty/netty#13414]
### Expected behavior

Derived buffers should be at least as likely as non-derived buffers to be selected for leak tracking when leak detection level is SIMPLE or ADVANCED.

### Actual behavior

Derived buffers are exponentially less likely to be selected. From looking at the code, the parent buffer must be selected for leak tracking _and_ the derived buffer must also be selected by a separate roll of the dice.

This is creating a headache for me. I'm trying to debug a leak in an application where buffers are derived several times:

- Bytes are pulled off the wire. This level 1 buffer has, by default, 1 in 128 chance to be selected for leak tracking.
- The level 1 buffer is sliced, creating a level 2 buffer. This buffer has, by default, 1 in 16,384 chance to be selected for leak tracking.
- The level 2 buffer is sliced again, creating a level 3 buffer. This buffer has, by default, 1 in 2,097,152 chance to be selected for leak tracking. You have a better chance of winning $50,000 playing PowerBall.
- The level 3 buffer might be duplicated, creating a level 4 buffer. This buffer has, by default, 1 in 268,435,456 chance to be selected for leak tracking. Your odds of winning the PowerBall grand prize are only mildly worse.

I get some leak logging for the level 1 buffers, and a handful of level 2. Based on those, it looks like the actual problem is that level 3/4 buffers are not being released properly. But since I have zero logs for those due to how unlikely they are to be selected for tracking, I can't tell where the the problem is.

I'm now trying to work around this by setting `io.netty.leakDetection.samplingInterval` to 32 and hoping I get lucky. Obviously, I could switch to PARANOID level, but this is happening in a production environment and I haven't been able to reproduce it elsewhere.

IMO, Netty should provide a better solution for this situation. Two ideas off the top of my head:

- If the non-derived (level 1) buffer is selected for leak tracking, all derived buffers are automatically selected as well. No rolling dice.
- Make it possible for derived buffers to be selected for leak tracking even if the parent buffer was not.

### Netty version

4.1.92.Final

**Comment by normanmaurer** [comment]
@rdicroce imho both sound good. Want to do a PR ?

**Comment by rdicroce** [comment]
Sorry for the delay. I was on vacation last week.

Yes, I can take a stab at a PR for the first option. That looked fairly straightforward.
