### ISSUE TITLE
How can the client implement TLS PSK? Give me an example, thank you

### ISSUE THREAD

**Issue by yuanhongbo123** [netty/netty#13425]
### Netty version
4.1.86.Final

### JVM version (e.g. `java -version`)
jdk1.8.0_332

### OS version (e.g. `uname -a`)
Linux osssvr 4.18.0-147.5.2.13.h996.eulerosv2r10.x86_64 #1 SMP Thu Sep 1 07:54:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
TLS 1.3 PSK is not supported. See also https://github.com/netty/netty-incubator-codec-quic/issues/246
