### ISSUE TITLE
 Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.11:build (build-native-lib) on project netty-tcnative: build failed: org.apache.maven.plugin.MojoExecutionException: make based build failed with exit code: 2 

### ISSUE THREAD

**Issue by tangrunbo** [netty/netty#13448]
[INFO] src/sslcontext.c: In function ‘Java_org_apache_tomcat_jni_SSLContext_make’:
[INFO] src/sslcontext.c:130:13: error: ‘TLSv1_2_client_method’ is deprecated [-Werror=deprecated-declarations]
[INFO]   130 |             ctx = SSL_CTX_new(TLSv1_2_client_method());
[INFO]       |             ^~~
[INFO] In file included from /usr/include/openssl/e_os2.h:13,
[INFO]                  from /usr/include/openssl/ssl.h:15,
[INFO]                  from src/ssl_private.h:47,
[INFO]                  from src/sslcontext.c:32:
[INFO] /usr/include/openssl/ssl.h:1891:1: note: declared here
[INFO]  1891 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_client_method(void))
[INFO]       | ^~~~~~~~~~~~~~~~~~
[INFO] src/sslcontext.c:132:13: error: ‘TLSv1_2_server_method’ is deprecated [-Werror=deprecated-declarations]
[INFO]   132 |             ctx = SSL_CTX_new(TLSv1_2_server_method());
[INFO]       |             ^~~
[INFO] In file included from /usr/include/openssl/e_os2.h:13,
[INFO]                  from /usr/include/openssl/ssl.h:15,
[INFO]                  from src/ssl_private.h:47,
[INFO]                  from src/sslcontext.c:32:
[INFO] /usr/include/openssl/ssl.h:1890:1: note: declared here
[INFO]  1890 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_server_method(void))
[INFO]       | ^~~~~~~~~~~~~~~~~~
[INFO] src/sslcontext.c:134:13: error: ‘TLSv1_2_method’ is deprecated [-Werror=deprecated-declarations]
[INFO]   134 |             ctx = SSL_CTX_new(TLSv1_2_method());
[INFO]       |             ^~~
[INFO] In file included from /usr/include/openssl/e_os2.h:13,
[INFO]                  from /usr/include/openssl/ssl.h:15,
[INFO]                  from src/ssl_private.h:47,
[INFO]                  from src/sslcontext.c:32:
[INFO] /usr/include/openssl/ssl.h:1889:1: note: declared here
[INFO]  1889 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_method(void)) /* TLSv1.2 */
[INFO]       | ^~~~~~~~~~~~~~~~~~
[INFO] src/sslcontext.c:140:13: error: ‘TLSv1_1_client_method’ is deprecated [-Werror=deprecated-declarations]
[INFO]   140 |             ctx = SSL_CTX_new(TLSv1_1_client_method());
[INFO]       |             ^~~
[INFO] In file included from /usr/include/openssl/e_os2.h:13,
[INFO]                  from /usr/include/openssl/ssl.h:15,
[INFO]                  from src/ssl_private.h:47,
[INFO]                  from src/sslcontext.c:32:
[INFO] /usr/include/openssl/ssl.h:1885:1: note: declared here
[INFO]  1885 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_client_method(void))
[INFO]       | ^~~~~~~~~~~~~~~~~~
[INFO] src/sslcontext.c:142:13: error: ‘TLSv1_1_server_method’ is deprecated [-Werror=deprecated-declarations]
[INFO]   142 |             ctx = SSL_CTX_new(TLSv1_1_server_method());
[INFO]       |             ^~~
[INFO] In file included from /usr/include/openssl/e_os2.h:13,
[INFO]                  from /usr/include/openssl/ssl.h:15,
[INFO]                  from src/ssl_private.h:47,
[INFO]                  from src/sslcontext.c:32:
[INFO] /usr/include/openssl/ssl.h:1884:1: note: declared here
[INFO]  1884 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_server_method(void))
[INFO]       | ^~~~~~~~~~~~~~~~~~
[INFO] src/sslcontext.c:144:13: error: ‘TLSv1_1_method’ is deprecated [-Werror=deprecated-declarations]
[INFO]   144 |             ctx = SSL_CTX_new(TLSv1_1_method());
[INFO]       |             ^~~
[INFO] In file included from /usr/include/openssl/e_os2.h:13,
[INFO]                  from /usr/include/openssl/ssl.h:15,
[INFO]                  from src/ssl_private.h:47,
[INFO]                  from src/sslcontext.c:32:
[INFO] /usr/include/openssl/ssl.h:1883:1: note: declared here
[INFO]  1883 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_method(void)) /* TLSv1.1 */
[INFO]       | ^~~~~~~~~~~~~~~~~~
[INFO] src/sslcontext.c:150:13: error: ‘TLSv1_client_method’ is deprecated [-Werror=deprecated-declarations]
[INFO]   150 |             ctx = SSL_CTX_new(TLSv1_client_method());
[INFO]       |             ^~~
[INFO] In file included from /usr/include/openssl/e_os2.h:13,
[INFO]                  from /usr/include/openssl/ssl.h:15,
[INFO]                  from src/ssl_private.h:47,
[INFO]                  from src/sslcontext.c:32:
[INFO] /usr/include/openssl/ssl.h:1879:1: note: declared here
[INFO]  1879 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_client_method(void))
[INFO]       | ^~~~~~~~~~~~~~~~~~
[INFO] src/sslcontext.c:152:13: error: ‘TLSv1_server_method’ is deprecated [-Werror=deprecated-declarations]
[INFO]   152 |             ctx = SSL_CTX_new(TLSv1_server_method());
[INFO]       |             ^~~
[INFO] In file included from /usr/include/openssl/e_os2.h:13,
[INFO]                  from /usr/include/openssl/ssl.h:15,
[INFO]                  from src/ssl_private.h:47,
[INFO]                  from src/sslcontext.c:32:
[INFO] /usr/include/openssl/ssl.h:1878:1: note: declared here
[INFO]  1878 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_server_method(void))
[INFO]       | ^~~~~~~~~~~~~~~~~~
[INFO] src/sslcontext.c:154:13: error: ‘TLSv1_method’ is deprecated [-Werror=deprecated-declarations]
[INFO]   154 |             ctx = SSL_CTX_new(TLSv1_method());
[INFO]       |             ^~~
[INFO] In file included from /usr/include/openssl/e_os2.h:13,
[INFO]                  from /usr/include/openssl/ssl.h:15,
[INFO]                  from src/ssl_private.h:47,
[INFO]                  from src/sslcontext.c:32:
[INFO] /usr/include/openssl/ssl.h:1877:1: note: declared here
[INFO]  1877 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_method(void)) /* TLSv1.0 */
[INFO]       | ^~~~~~~~~~~~~~~~~~
[INFO] src/sslcontext.c:182:17: error: ‘TLSv1_2_client_method’ is deprecated [-Werror=deprecated-declarations]
[INFO]   182 |                 ctx = SSL_CTX_new(TLSv1_2_client_method());
[INFO]       |                 ^~~
[INFO] In file included from /usr/include/openssl/e_os2.h:13,
[INFO]                  from /usr/include/openssl/ssl.h:15,
[INFO]                  from src/ssl_private.h:47,
[INFO]                  from src/sslcontext.c:32:
[INFO] /usr/include/openssl/ssl.h:1891:1: note: declared here
[INFO]  1891 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_client_method(void))
[INFO]       | ^~~~~~~~~~~~~~~~~~
[INFO] src/sslcontext.c:184:17: error: ‘TLSv1_2_server_method’ is deprecated [-Werror=deprecated-declarations]
[INFO]   184 |                 ctx = SSL_CTX_new(TLSv1_2_server_method());
[INFO]       |                 ^~~
[INFO] In file included from /usr/include/openssl/e_os2.h:13,
[INFO]                  from /usr/include/openssl/ssl.h:15,
[INFO]                  from src/ssl_private.h:47,
[INFO]                  from src/sslcontext.c:32:
[INFO] /usr/include/openssl/ssl.h:1890:1: note: declared here
[INFO]  1890 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_server_method(void))
[INFO]       | ^~~~~~~~~~~~~~~~~~
[INFO] src/sslcontext.c:186:17: error: ‘TLSv1_2_method’ is deprecated [-Werror=deprecated-declarations]
[INFO]   186 |                 ctx = SSL_CTX_new(TLSv1_2_method());
[INFO]       |                 ^~~
[INFO] In file included from /usr/include/openssl/e_os2.h:13,
[INFO]                  from /usr/include/openssl/ssl.h:15,
[INFO]                  from src/ssl_private.h:47,
[INFO]                  from src/sslcontext.c:32:
[INFO] /usr/include/openssl/ssl.h:1889:1: note: declared here
[INFO]  1889 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_method(void)) /* TLSv1.2 */
[INFO]       | ^~~~~~~~~~~~~~~~~~
[INFO] src/sslcontext.c:190:17: error: ‘TLSv1_1_client_method’ is deprecated [-Werror=deprecated-declarations]
[INFO]   190 |                 ctx = SSL_CTX_new(TLSv1_1_client_method());
[INFO]       |                 ^~~
[INFO] In file included from /usr/include/openssl/e_os2.h:13,
[INFO]                  from /usr/include/openssl/ssl.h:15,
[INFO]                  from src/ssl_private.h:47,
[INFO]                  from src/sslcontext.c:32:
[INFO] /usr/include/openssl/ssl.h:1885:1: note: declared here
[INFO]  1885 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_client_method(void))
[INFO]       | ^~~~~~~~~~~~~~~~~~
[INFO] src/sslcontext.c:192:17: error: ‘TLSv1_1_server_method’ is deprecated [-Werror=deprecated-declarations]
[INFO]   192 |                 ctx = SSL_CTX_new(TLSv1_1_server_method());
[INFO]       |                 ^~~
[INFO] In file included from /usr/include/openssl/e_os2.h:13,
[INFO]                  from /usr/include/openssl/ssl.h:15,
[INFO]                  from src/ssl_private.h:47,
[INFO]                  from src/sslcontext.c:32:
[INFO] /usr/include/openssl/ssl.h:1884:1: note: declared here
[INFO]  1884 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_server_method(void))
[INFO]       | ^~~~~~~~~~~~~~~~~~
[INFO] src/sslcontext.c:194:17: error: ‘TLSv1_1_method’ is deprecated [-Werror=deprecated-declarations]
[INFO]   194 |                 ctx = SSL_CTX_new(TLSv1_1_method());
[INFO]       |                 ^~~
[INFO] In file included from /usr/include/openssl/e_os2.h:13,
[INFO]                  from /usr/include/openssl/ssl.h:15,
[INFO]                  from src/ssl_private.h:47,
[INFO]                  from src/sslcontext.c:32:
[INFO] /usr/include/openssl/ssl.h:1883:1: note: declared here
[INFO]  1883 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_method(void)) /* TLSv1.1 */
[INFO]       | ^~~~~~~~~~~~~~~~~~
[INFO] src/sslcontext.c:198:17: error: ‘TLSv1_client_method’ is deprecated [-Werror=deprecated-declarations]
[INFO]   198 |                 ctx = SSL_CTX_new(TLSv1_client_method());
[INFO]       |                 ^~~
[INFO] In file included from /usr/include/openssl/e_os2.h:13,
[INFO]                  from /usr/include/openssl/ssl.h:15,
[INFO]                  from src/ssl_private.h:47,
[INFO]                  from src/sslcontext.c:32:
[INFO] /usr/include/openssl/ssl.h:1879:1: note: declared here
[INFO]  1879 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_client_method(void))
[INFO]       | ^~~~~~~~~~~~~~~~~~
[INFO] src/sslcontext.c:200:17: error: ‘TLSv1_server_method’ is deprecated [-Werror=deprecated-declarations]
[INFO]   200 |                 ctx = SSL_CTX_new(TLSv1_server_method());
[INFO]       |                 ^~~
[INFO] In file included from /usr/include/openssl/e_os2.h:13,
[INFO]                  from /usr/include/openssl/ssl.h:15,
[INFO]                  from src/ssl_private.h:47,
[INFO]                  from src/sslcontext.c:32:
[INFO] /usr/include/openssl/ssl.h:1878:1: note: declared here
[INFO]  1878 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_server_method(void))
[INFO]       | ^~~~~~~~~~~~~~~~~~
[INFO] src/sslcontext.c:202:17: error: ‘TLSv1_method’ is deprecated [-Werror=deprecated-declarations]
[INFO]   202 |                 ctx = SSL_CTX_new(TLSv1_method());
[INFO]       |                 ^~~
[INFO] In file included from /usr/include/openssl/e_os2.h:13,
[INFO]                  from /usr/include/openssl/ssl.h:15,
[INFO]                  from src/ssl_private.h:47,
[INFO]                  from src/sslcontext.c:32:
[INFO] /usr/include/openssl/ssl.h:1877:1: note: declared here
[INFO]  1877 | DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_method(void)) /* TLSv1.0 */
[INFO]       | ^~~~~~~~~~~~~~~~~~
[INFO] src/sslcontext.c: In function ‘authentication_method’:
[INFO] src/sslcontext.c:1460:16: error: invalid use of incomplete typedef ‘SSL’ {aka ‘const struct ssl_st’}
[INFO]  1460 |     switch (ssl->version)
[INFO]       |                ^~
[INFO] src/sslcontext.c: In function ‘SSL_cert_verify’:
[INFO] src/sslcontext.c:1483:29: error: invalid use of incomplete typedef ‘X509_STORE_CTX’ {aka ‘struct x509_store_ctx_st’}
[INFO]  1483 |     STACK_OF(X509) *sk = ctx->untrusted;
[INFO]       |                             ^~
[INFO] src/sslcontext.c: In function ‘cert_requested’:
[INFO] src/sslcontext.c:1643:16: error: invalid use of incomplete typedef ‘SSL’ {aka ‘struct ssl_st’}
[INFO]  1643 |     switch (ssl->version) {
[INFO]       |                ^~
[INFO] src/sslcontext.c:1653:39: error: invalid use of incomplete typedef ‘SSL’ {aka ‘struct ssl_st’}
[INFO]  1653 |             ctype_bytes = (jbyte*) ssl->s3->tmp.ctype;
[INFO]       |                                       ^~
[INFO] src/sslcontext.c:1654:28: error: invalid use of incomplete typedef ‘SSL’ {aka ‘struct ssl_st’}
[INFO]  1654 |             ctype_num = ssl->s3->tmp.ctype_num;
[INFO]       |                            ^~
[INFO] cc1: all warnings being treated as errors
[INFO] make: *** [Makefile:561: src/sslcontext.lo] Error 1
[INFO] rc: 2
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Netty/TomcatNative [Parent] 1.1.33.Fork19:
[INFO]
[INFO] Netty/TomcatNative [Parent] ........................ SUCCESS [  3.463 s]
[INFO] Netty/TomcatNative [OpenSSL - Dynamic] ............. FAILURE [ 17.224 s]
[INFO] Netty/TomcatNative [OpenSSL - Static] .............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.021 s
[INFO] Finished at: 2023-06-15T16:14:10+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.11:build (build-native-lib) on project netty-tcnative: build failed: org.apache.maven.plugin.MojoExecutionException: make based build failed with exit code: 2 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :netty-tcnative

**Comment by normanmaurer** [comment]
I suspect you try to compile with openssl 3.0 which we not support atm. Also this is for netty-tcnative and not netty.
