### ISSUE TITLE
When I use the HTTP2 protocol, I occasionally encounter flow control error

### ISSUE THREAD

**Issue by yanghao605** [netty/netty#13444]
![image](https://github.com/netty/netty/assets/73453250/0a3bbf03-28af-45f5-a263-b6dbb4bcfc34)

**Comment by normanmaurer** [comment]
What version of netty is this also do you have a reproducer ?

**Comment by normanmaurer** [comment]
@yanghao605 ping

**Comment by normanmaurer** [comment]
Closing as the reporter did not provide any more details
