### ISSUE TITLE
ReplayingDecoderByteBuf.retainedSlice(...) behavior unexpected and not documented

### ISSUE THREAD

**Issue by codekrolik2** [netty/netty#13455]
`ByteBuf.retainedSlice` javadoc states: 
```
This method behaves similarly to {@code slice(...).retain()} 
except that this method may return a buffer implementation 
that produces less garbage.
```
However, `ReplayingDecoderByteBuf.retainedSlice(...)` is the same code as `ReplayingDecoderByteBuf.slice(...)`, i.e. it doesn't retain the slice. Not only it's unexpected and breaks the contract in one of the most important and error-prone domains of manual memory management, but also it's completely undocumented.
As a workaround one could use `slice(...).retain()`.
(Personally I just marked `retainedSlice(...)` as cursed for myself and switched to explicitly calling `slice(...).retain()` instead at all times).

If this is due to some unobvious design goals, at least it should be well documented, and ideally this information should be reachable from ByteBuf javadoc, as well as any other alterations to the original contract. Currently there is no way to discover this other than encountering unexpected program behavior causing errors and debugging.

### Expected behavior
`ReplayingDecoderByteBuf.retainedSlice()` retains the slice.

### Actual behavior
`ReplayingDecoderByteBuf.retainedSlice()` is the same code as `ReplayingDecoderByteBuf.slice()`, and doesn't retain the slice.

### Steps to reproduce
get an instance of `ReplayingDecoderByteBuf`, run `retainedSlice()`, check `refCnt()`s, `release()` main buffer, check `refCnt()`s.

### Minimal yet complete reproducer code (or URL to code) 
Apologies, I don't know how to create a minimal test that grabs an instance of `ReplayingDecoderByteBuf` without running a full client-server, but you can just look at this code here:
https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/ReplayingDecoderByteBuf.java#L863-L873
Literally the same code.

### Netty version 
4.1.60.Final

### JVM version (e.g. `java -version`) 
17

### OS version (e.g. `uname -a`) 
Darwin CSS-C02FM602MD6R 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64 x86_64

**Comment by overpathz** [comment]
Did you try something like that?
`ByteBuf retainedSlice = buffer.slice(index, length).retain();`
