### ISSUE TITLE
Possible race condition in method `io.netty.buffer.ByteBuf.capacity(int)`

### ISSUE THREAD

**Issue by laosijikaichele** [netty/netty#13467]
I think there is a race condition problem in method `io.netty.buffer.ByteBuf.capacity(int)` when calling it from multiple threads.
### Steps to reproduce
Run the following code:
```
import io.netty.buffer.ByteBuf;
import io.netty.buffer.PoolArenaMetric;
import io.netty.buffer.PoolSubpageMetric;
import io.netty.buffer.PooledByteBufAllocator;

public class TestCapacity {

    public static void main(String[] args) throws InterruptedException {

        final ByteBuf buf = PooledByteBufAllocator.DEFAULT.heapBuffer();
        final int ENLARGE_CAPACITY = 512;
        Thread thread_1 = new Thread(new Runnable() {
            @Override
            public void run() {
                buf.capacity(ENLARGE_CAPACITY);
            }
        });
        Thread thread_2 = new Thread(new Runnable() {
            @Override
            public void run() {
                buf.capacity(ENLARGE_CAPACITY);
            }
        });

        thread_1.start();
        thread_2.start();

        thread_1.join();
        thread_2.join();

        PoolArenaMetric metric = PooledByteBufAllocator.DEFAULT.metric().heapArenas().get(0);
        PoolSubpageMetric subpageMetric = metric.smallSubpages().get(0);

        System.out.println(subpageMetric.maxNumElements() >= subpageMetric.numAvailable());
    }
}

```
Run the code multiple times, you can see that sometimes it prints `true`, sometimes it prints `false`. 
But logically it should never be `false`, because `maxNumElements` should never less than `numAvailable`.
### Netty version
4.1.94.Final

**Comment by normanmaurer** [comment]
`ByteBuf` is not thread-safe... so I am not surprised by this :)

**Comment by laosijikaichele** [comment]
@normanmaurer 
Sorry may be I did not clearly explained it. 
IMHO, apart from `ByteBuf` class, the two fields `maxNumElems ` and `numAvail` belong to class `PoolSubpage`, does `maxNumElems < numAvail` logically ok to happen in class `PoolSubpage`? 
In other words, I think the logic in class `PoolSubpage` should always guarantee the two methods `maxNumElements() < numAvailable()`. Right?

**Comment by normanmaurer** [comment]
Just to make it clear... calling `capacity(...)` concurrently is still a bug :)
