### ISSUE TITLE
So many "DefaultHandle[] and Link" objects!!

### ISSUE THREAD

**Issue by robynron** [netty/netty#13464]
### Expected behavior
I don't know why there are so many DefaultHandle[] and Link" objects when I got a heapdump of my running project. As you can see as following:

objectName | count | total size | rate
io.netty.util.Recycler$DefaultHandle[] | 19557636 | 1.46 GB | 61.2%
io.netty.util.Recycler$WeakOrderQueue$Link | 19557636 | 596.85 MB | 24.5%

### Netty version
netty-4.1.50.Final
### JVM version (e.g. `java -version`)
java version "1.8.0_66"
OpenJDK Runtime Environment (Alibaba 8.0.0) (build 1.8.0_66-b60)
OpenJDK 64-Bit Server VM (Alibaba 8.0.0) (build 25.66-b60, mixed mode)
### OS version (e.g. `uname -a`)
Linux 3.10.0-327.ali2000.alios7.x86_64 #1 SMP Tue Dec 29 19:54:05 CST 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by franz1981** [comment]
Move to a more recent Netty version that get rid of weak ref for the Recycler

**Comment by robynron** [comment]
Could you please tell why this is happing in this version?
And which #pr fixed this issue? 
And are there any releated #issues?

**Comment by chrisvest** [comment]
There have been many improvements, including a rewrite in 4.1.71.Final: https://github.com/netty/netty/pulls?q=is%3Apr+is%3Aclosed+recycler
