### ISSUE TITLE
Reduce memory allocation of `SslHandler.flush`

### ISSUE THREAD

**Issue by leonchen83** [netty/netty#13462]
### Expected behavior
When we invoke `SslHandler.flush` method. it tooks 70% memory allocation. see image below.
I want to ask is there a way to reduce the memory allocation of `SslHandler.flush`?

more details see attachment.
### Netty version 
```
4.1.94.Final
```
### JVM version (e.g. `java -version`)
```
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
```
### OS version (e.g. `uname -a`)
```
Linux erebor-dev 2.6.32-642.el6.x86_64 #1 SMP Tue May 10 17:27:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
![image](https://github.com/netty/netty/assets/5235764/ec77f2ea-f4b1-445b-8ba3-ff812930c871)

[front2_alloc.zip](https://github.com/netty/netty/files/11878516/front2_alloc.zip)

**Comment by normanmaurer** [comment]
Check https://github.com/netty/netty/pull/13472... Which eliminate most of the ByteBuffer allocations .
