### ISSUE TITLE
HOw to use FileRegion to transfer files using zero copy.

### ISSUE THREAD

**Issue by DanielAlmeidaJoao** [netty/netty#13474]
### Expected behavior
I am using the following code from the book Netty in Action, and I am having the error  *unsupported message type: DefaultFileRegion*
Which encoder should I have in order to solve this error? 
FileInputStream in = new FileInputStream(file);
FileRegion region = new DefaultFileRegion(in.getChannel(), 0, file.length());
channel.writeAndFlush(region).

java 11,
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-all</artifactId>
    <version>4.1.90.Final</version>
</dependency>

**Comment by He-Pin** [comment]
@DanielAlmeidaJoao There is a book `Netty in Action` and a wiki you can make use of.

**Comment by DanielAlmeidaJoao** [comment]
@He-Pin I can't find any implementation of an encoder that solves the error I am having, not even on the wiki

**Comment by hyperxpro** [comment]
PTAL here: https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http/file/HttpStaticFileServerHandler.java

**Comment by DanielAlmeidaJoao** [comment]
@hyperxpro did you understand my question ? Don't just put a link here like a robot. What am I supposed to do with *PTAL here and a link* ?

**Comment by hyperxpro** [comment]
Well, if you look closely, you'll find:

https://github.com/netty/netty/blob/4bd20067ace14b3dfd14e4a4bb9cbe480e97d3b0/example/src/main/java/io/netty/example/http/file/HttpStaticFileServerHandler.java#L200

And then you can navigate to Pipeline configuration to see how to make FileRegion work:

https://github.com/netty/netty/blob/4bd20067ace14b3dfd14e4a4bb9cbe480e97d3b0/example/src/main/java/io/netty/example/http/file/HttpStaticFileServerInitializer.java#L42

Also, there is no need to trash talk over a GitHub Issue. :)

**Comment by DanielAlmeidaJoao** [comment]
@hyperxpro I think I found the solution. There is no need to use an encoder. 

FileRegion is used to send file data without reading the data into the app memory. I was using QUIC, and quic needs to load the data into the app memory to encrypt it, that's why it was failing. With TCP it worked, with TCP there is no need to process the data before sending it
