### ISSUE TITLE
ChannelOutboundBuffer flushed field should be volatile

### ISSUE THREAD

**Issue by lmagyar89** [netty/netty#13501]
### Expected behavior
As described in the documentation size() and isEmpty() can be called from other than IO thread , these method should be thread safe.
volatile is enough here, as single writer thread more reader thread.

### Actual behavior
size() and isEmpty() use flushed field, which should be volatile to get always the result of the last write.

### Netty version
4.1 branch

**Comment by franz1981** [comment]
According to http://psy-lob-saw.blogspot.com/2012/12/atomiclazyset-is-performance-win-for.html and recent measurements, `volatile` is the proper field definition, but would be better to update it by using `AtomicIntegerFieldUpdater::lazySet.

@normanmaurer are you aware first if the doc is still valid?

**Comment by lmagyar89** [comment]
if `AtomicIntegerFieldUpdater::lazySet` is the proper way, `totalPendingSize` field update is "wrong" in main branch.

**Comment by franz1981** [comment]
> totalPendingSize field update is "wrong" in main branch

WDYM with "wrong"?

**Comment by lmagyar89** [comment]
You suggestted that instead of simple volatile write, use `AtomicIntegerFieldUpdater::lazySet` rigth?
So if you are go with that direction, to use `AtomicIntegerFieldUpdater::lazySet` to modify `flushed` field, you should use the same when modify the `totalPendingSize` property on main branch. Just to be consistent.
So it is not wrong, but if you see the advantages in case `flushed` field, the same applied to  `totalPendingSize` property.

**Comment by franz1981** [comment]
Yep, exactly: if there's a single writer (in the hot path) usually `lazySet` is a perf win (as `VarHandle::setRelease` as well).

**Comment by normanmaurer** [comment]
I think  the javadoc is just wrong / outdated... `size` and `isEmpty` should only be called from within the EventLoop (which is what we do in our transport impls anyway). Let me fix the doc

**Comment by normanmaurer** [comment]
See https://github.com/netty/netty/pull/13502
