### ISSUE TITLE
Codec decorator for AddressedEnvelope support

### ISSUE THREAD

**Issue by trustin** [netty/netty#1350]
#1349 gives me an interesting idea:

    pipeline.addLast("udpDecoder", new DatagramPacketDecoder(new ProtobufDecoder(..)));
    pipeline.addLast("udpEncoder", new DatagramPacketEncoder(new ProtobufEncoder(..)));

where `DatagramPacketDecoder` unwraps the packet and feeds the enclosed `ByteBuf` to `ProtobufDecoder`, and `DatagramPacketEncoder` unwraps an `AddressedEnvelope` and feeds the enclosed `ByteBuf` to `ProtobufEncoder` to produce a `DatagramPacket`.

If we add a new copy operation to `AddressEnvelope` that allows us to specify the new content while preserving other properties such as remote address, we can get it work for all `AddressedEnvelope` messages rather than only `DatagramPacket`.

**Comment by windie** [comment]
This one can be closed now.

**Comment by trustin** [comment]
@windie Thanks for the heads up!
