### ISSUE TITLE
Netty Project CVEs

### ISSUE THREAD

**Issue by patrickrochemn** [netty/netty#13519]
I have vulnerabilities I would like to report and saw on the main site that I should report such findings in the private google group, but was unable to determine how to join the group. I apologize if this is not the correct place to request that access, but was not sure where else to post.

**Comment by hyperxpro** [comment]
See: https://github.com/netty/netty/security

![image](https://github.com/netty/netty/assets/24762260/8569f770-c0c7-4872-9901-adf946a8742d)

**Comment by chrisvest** [comment]
@patrickrochemn You don't get to join the security google group, but you can write emails to it without joining. There's also the GitHub way that @hyperxpro mentioned.
