### ISSUE TITLE
netty-tcnative is missing from BOM

### ISSUE THREAD

**Issue by spensonshih** [netty/netty#13517]
### Expected behavior
Using netty-bom, all versions of netty artifacts should be consistent.

### Actual behavior
A 3rd party lib with a transitive dependency to io.netty:netty-tcnative is resolving to a different version inconsistent with what I expected from the BOM.

### Steps to reproduce
1. Maven project to import io.netty:netty-bom:pom:4.1.95.Final.
2. Include Apache Zookeeper 3.8.0 as dependency, and io.netty:netty-tcnative-boringssl-static
3. Netty dependency correctly resolves to 4.1.95.Final.   However, io.netty:netty-tcnative:2.0.48.Final vs the io.netty:netty-tcnative-boringssl-static:2.0.61.Final.

```
[INFO] --- dependency:3.6.0:list (default-cli) @ testing ---
[INFO] 
[INFO] The following files have been resolved:
[INFO]    io.netty:netty-handler:jar:4.1.95.Final:compile
[INFO]    io.netty:netty-transport:jar:4.1.95.Final:compile
[INFO]    io.netty:netty-buffer:jar:4.1.95.Final:compile
[INFO]    io.netty:netty-codec:jar:4.1.95.Final:compile
[INFO]    io.netty:netty-common:jar:4.1.95.Final:compile
[INFO]    io.netty:netty-resolver:jar:4.1.95.Final:compile
[INFO]    io.netty:netty-transport-native-epoll:jar:4.1.95.Final:compile
[INFO]    io.netty:netty-transport-native-unix-common:jar:4.1.95.Final:compile
[INFO]    io.netty:netty-tcnative:jar:2.0.48.Final:compile
[INFO]    io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.95.Final:compile
[INFO]    io.netty:netty-transport-classes-epoll:jar:4.1.95.Final:compile
[INFO]    io.netty:netty-tcnative-boringssl-static:jar:2.0.61.Final:compile
[INFO]    io.netty:netty-tcnative-classes:jar:2.0.61.Final:compile
[INFO]    io.netty:netty-tcnative-boringssl-static:jar:linux-x86_64:2.0.61.Final:compile
[INFO]    io.netty:netty-tcnative-boringssl-static:jar:linux-aarch_64:2.0.61.Final:compile
[INFO]    io.netty:netty-tcnative-boringssl-static:jar:osx-x86_64:2.0.61.Final:compile
[INFO]    io.netty:netty-tcnative-boringssl-static:jar:osx-aarch_64:2.0.61.Final:compile
[INFO]    io.netty:netty-tcnative-boringssl-static:jar:windows-x86_64:2.0.61.Final:compile
```

The BOM seem to be missing `io.netty:netty-tcnative` entry.

### Netty version
4.1.95.Final

### JVM version (e.g. `java -version`)
Java 17

### OS version (e.g. `uname -a`)
MacOS Ventura 13.4.1

**Comment by chrisvest** [comment]
The entries are here, though: https://github.com/netty/netty/blob/4.1/bom/pom.xml#L314-L337

The zookeeper 3.8.0 parent tries to pull in these maven dependencies:

```xml
    <netty.version>4.1.73.Final</netty.version>
    <netty.tcnative.version>2.0.48.Final</netty.tcnative.version>
```

I don't know why only the netty version is being overwritten and not the tcnative version, but if you upgrade zookeeper to 3.8.2 it appears to be fixed.
