### ISSUE TITLE
SNYK Improper Certificate Validation vulnerability

### ISSUE THREAD

**Issue by CBaroud** [netty/netty#13511]
### Expected behavior
- A version we can upgrade to where this vulnerability is tackled

### Actual behavior
- There is no fixed version for io.netty:netty-handler.

### Steps to reproduce
- Affecting [io.netty:netty-handler](https://security.snyk.io/package/maven/io.netty%3Anetty-handler) package, versions [4.1.0.Final,]

- Affected versions of this package are vulnerable to Improper Certificate Validation. Certificate hostname validation is disabled by default in Netty 4.1.x which makes it potentially susceptible to Man-in-the-Middle attacks.

https://security.snyk.io/vuln/SNYK-JAVA-IONETTY-1042268

**Comment by hyperxpro** [comment]
Dup of #9930 #11213
