### ISSUE TITLE
Class loading fails after netty-transport-native-epoll  4.1.96.Final version 

### ISSUE THREAD

**Issue by Kavindu-Dodan** [netty/netty#13523]
### Expected behavior

While `EpollEventLoopGroup` is specifically targeting Linux (as it uses epoll), this should not prevent referencing the class in shared logic.

### Actual behavior

The recent change that was introduced with PR https://github.com/netty/netty/pull/13506 made the availability check `static` and this results in the availability check running at class loading time. This breaks library usage for non Linux systems.

### Steps to reproduce

Update `netty-transport-native-epoll` to version `4.1.96.Final` and use in a non Linux system where there is a class loading involved for the class `EpollEventLoopGroup`

### Netty version

4.1.96.Final

### JVM version (e.g. `java -version`)

17.x.x

### OS version (e.g. `uname -a`)

Darwin 22.x.x

**Comment by toddbaert** [comment]
Agreed with @Kavindu-Dodan . This means that applications which before would run just fine unless they actually instantiated these classes fail to start on no-linux systems. To deal with this, developers would probably need to make changes to instead dynamically load classes like `EpollEventLoopGroup`.

**Comment by hyperxpro** [comment]
Can you share a reproducer of this? I'm having a hard time trying to replicate.

**Comment by normanmaurer** [comment]
Generally speaking you should always guard it with an `Epoll.isAvailable()` call. That said I think we can change the code to guard against this "problem".

**Comment by normanmaurer** [comment]
check https://github.com/netty/netty/pull/13553

**Comment by toddbaert** [comment]
> Generally speaking you should always guard it with an `Epoll.isAvailable()` call. That said I think we can change the code to guard against this "problem".

I appreciate that. We will add a guard as you describe, that makes perfect sense.

**Comment by Kavindu-Dodan** [comment]
@normanmaurer  As you mentioned in the PR, this change cause existing code to fail once updated to the latest version (as we observed). This is the reason I created the issue and thank you for handling this.

We will follow-up on this through the issue created by @toddbaert  and I will close this issue.
