### ISSUE TITLE
Creating HttpPostRequestDecoder changes AbstractByteBuf.ReaderIndex since 4.1.65

### ISSUE THREAD

**Issue by WolfgangHG** [netty/netty#13532]
This is a rather complex problem, with a lot of steps to reproduce it. My question is: is it a bug/regression in Netty, or was it intentionally changed?
The problem occurs with versions newer then 4.1.65, it works with 4.1.63 or before.

I started some maintenance work on the [arquillian-extension-warp](https://github.com/arquillian/arquillian-extension-warp) project. It provides unit testing of JSF pages und uses [LittleProxy](https://github.com/LittleProxy/LittleProxy) to hook in the client requests (which are send to the proxy, and the proxy forwards them to the WildFly server) and add some headers. LittleProxy uses Netty.

Updating the extension to LittleProxy versions newer than 2.0.6 fails, because some unit tests of the extension fail: a servlet request is deadlocked on the server side.

With the help of LittleProxy logging, I found on the client one difference in the logs:

This is the log with 2.0.5:
`DEBUG 2023-04-12T21:10:40,630 [LittleProxy-0-ClientToProxyWorker-0] impl.ProxyToServerConnection.doWrite (ProxyConnection.java:233) - (AWAITING_INITIAL) [id: 0x2f129ced, L:/[127.0.0.1:54704](http://127.0.0.1:54704/) - R:/[127.0.0.1:8080](http://127.0.0.1:8080/)]: Wrote: HttpObjectAggregator$AggregatedFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 36, cap: 36, components=1))`

And this is the log snippet for 2.0.6:
`DEBUG 2023-04-12T21:12:01,321 [LittleProxy-0-ClientToProxyWorker-0] impl.ProxyToServerConnection.doWrite (ProxyConnection.java:233) - (AWAITING_INITIAL) [id: 0x44bb34f7, L:/[127.0.0.1:54862](http://127.0.0.1:54862/) - R:/[127.0.0.1:8080](http://127.0.0.1:8080/)]: Wrote: HttpObjectAggregator$AggregatedFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 36, widx: 36, cap: 36, components=1))`

The only difference is the "ridx" of the CompositeByteBuf. It seems due to this, the request is not sent to the server, and thus the server deadlocks.

In the end I tracked it to this one line of code in "arquillian-extension-warp" (which is found in the phase where the request is intercepted by the proxy, modified and forwarded to the server):
```java
final HttpPostRequestDecoder decoder =
  new HttpPostRequestDecoder(new DefaultHttpDataFactory(false), request);
```
Don't ask me for the reason for this - it is not my code ;-). But I assume it looks for certain request headers and form data.

I can print the reader index before/after this call with this code:
```java
io.netty.handler.codec.http.FullHttpMessage message = (io.netty.handler.codec.http.FullHttpMessage) request;
ByteBuf bufContent = message.content();
CompositeByteBuf compBuf = (CompositeByteBuf) bufContent;
System.out.println("==>proxyToServerRequest BEFORE: readerIndex=" + compBuf.readerIndex() + ", writerIndex =" + compBuf.writerIndex());
```

With newer netty versions, the readerIndex is "36" instead of "0". The "36" is in my sample the length of a post parameter.

I could work around it by resetting the reader index to "0" again:
```java
compBuf.setIndex(0, compBuf.writerIndex());
``` 

But before applying this workaround: what do you think? Is this a regression in Netty, or do I have to add the workaround?

I will post a sample in my next reply.

**Comment by WolfgangHG** [comment]
To reproduce:

- Step 1: download WildFly 26.1.3 server (no newer versions!): [https://github.com/wildfly/wildfly/releases/download/26.1.3.Final/wildfly-26.1.3.Final.zip](https://github.com/wildfly/wildfly/releases/download/26.1.3.Final/wildfly-26.1.3.Final.zip)
- Step 2: start it ("bin\standalone.sh")
- Step 3: download attached file [test.war.zip](https://github.com/netty/netty/files/12270213/test.war.zip), rename it to "test.war" und copy it to the WildFly directory "standalone\deployments".
This war file contains a html page and a small servlet that loops over "HttpServletRequest.getParameterMap()"


Now start the client application: I use Eclipse to run the application, but it should also work with plain Maven.

- Step 1: download [my.littleproxy.zip](https://github.com/netty/netty/files/12270215/my.littleproxy.zip), import it to Eclipse.
- Step 2: launch the application in Eclipse.
It will hang, and the WildFly console will stuck with the output "===>TestingServlet is here!!!"

The client application starts a LittleProxy on port 8085, which forwards requests to the WildFly server.
The "Main" class uses a Selenium WebDriver to call a web page in "test.war" and submit a POST request on this page.
The request is handled by LittleProxy, and a callback "MyHttpFiltersSource.filterRequest" is called. There, a filter adapter method "proxyToServerRequest" is called. And in this method, I create a "HttpPostRequestDecoder" and print the reader index before/after this call.

To run the sample with Netty 4.1.63, just change the version in pom.xml.

Hope you can reproduce the issue. If not, please ask.

**Comment by WolfgangHG** [comment]
A better workaround might be this:

```java
io.netty.handler.codec.http.FullHttpMessage message = (io.netty.handler.codec.http.FullHttpMessage) request;
ByteBuf bufContent = message.content();
bufContent.markReaderIndex();

final HttpPostRequestDecoder decoder =
  new HttpPostRequestDecoder(new DefaultHttpDataFactory(false), request);

bufContent.resetReaderIndex();
```

**Comment by normanmaurer** [comment]
honestly I think this a bug of the user of `HttpPostRequestDecoder`. Once you pass the `request` to the decoder you cant assume that the indexes dont change. Just duplicate the request before you pass it.

**Comment by WolfgangHG** [comment]
@normanmaurer Do you mean something like this? (variable "request" is of type "io.netty.handler.codec.http.HttpRequest"):

```
io.netty.handler.codec.http.FullHttpMessage message = (io.netty.handler.codec.http.FullHttpMessage) request;
io.netty.handler.codec.http.FullHttpMessage messageDuplicated = message.duplicate();

final HttpPostRequestDecoder decoder =
    new HttpPostRequestDecoder(new DefaultHttpDataFactory(false), (HttpRequest) messageDuplicated);

for (InterfaceHttpData data : decoder.getBodyHttpDatas()) {
    ...
}
messageDuplicated.release();
```

Are "duplicate" and "release" the correct methods to call?

**Comment by chrisvest** [comment]
@WolfgangHG if you want the `duplicate` to pair up with `release`, you'll need to use `retainDuplicate`. If, on the other hand, the `release` is pairing up with the allocation of the original `FullHttpMessage` request, then `duplicate` is correct.

**Comment by WolfgangHG** [comment]
> f you want the `duplicate` to pair up with `release`, you'll need to use `retainDuplicate`. If, on the other hand, the `release` is pairing up with the allocation of the original `FullHttpMessage` request, then `duplicate` is correct.

Sorry, I don't know which approach I should use ;-). Norman wrote " Just duplicate the request before you pass it.", so I tried to implement it. Is "release" necessary at all?

**Comment by chrisvest** [comment]
It is not clear from the context if it's necessary or not. If the only change you made to working code was to insert a `duplicate()`, then things should work as they did before, except the duplicate buffer has independent indexes.

In you'r code, the call `messageDuplicated.release();` is the same as `message.release();` because you used `duplicate()` instead of `retainDuplicate()`.

**Comment by WolfgangHG** [comment]
The existing code (which resides in the "client to server" side of the LittleProxy usage) forwards the HttpRequest to the server after the call to the `HttpPostRequestDecoder`. So, the request is still used afterwards.
Yes, adding `duplicate` seemed to be the only necessary part.

So I should use this code?

```java
FullHttpMessage messageDuplicated = message.retainDuplicate()
...
messageDuplicated.release();
```

Or can I ommit `release` and use a single `duplicate`?

**Comment by WolfgangHG** [comment]
@chrisvest To come back to my previous question - could you provide me clarification about the correct approach?
I could also use `markReaderIndex` / `resetReaderIndex` I think.

**Comment by normanmaurer** [comment]
for your use-case I would just use `duplicate()`

**Comment by WolfgangHG** [comment]
And `release() `afterwards?

**Comment by WolfgangHG** [comment]
I ended with this code (no `release()` call) and hope it is OK. At least it works for me ;-):


```java
io.netty.handler.codec.http.HttpContent content = (HttpContent) request;
HttpContent contentDuplicated = content.duplicate();


final HttpPostRequestDecoder decoder =
    new HttpPostRequestDecoder(new DefaultHttpDataFactory(false), (HttpRequest) messageDuplicated);

for (InterfaceHttpData data : decoder.getBodyHttpDatas()) {
    ...
}

//no "release" here.
```
