### ISSUE TITLE
Support throwing `UnknownServiceException` if there is no cleartext traffic permitted

### ISSUE THREAD

**Issue by Goooler** [netty/netty#13548]
### Expected behavior

If there is no cleartext traffic permitted on Android, we should throw `UnknownServiceException`, like [OkHttp did](https://github.com/square/okhttp/blob/735ed1a6e5a15042f6d7e8f100fb3c8376f6aa27/okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealRoutePlanner.kt#L205-L208), more info see https://developer.android.com/reference/android/security/NetworkSecurityPolicy#isCleartextTrafficPermitted()

### Actual behavior

Nope.

### Steps to reproduce

Request an HTTP URL on Android 8+

### Netty version

netty-4.1.96.Final

**Comment by normanmaurer** [comment]
I am not sure what you really are asking for... For example you could check if the `ChannelPipeline` contains a `SslHandler` and if not throw the exception.

**Comment by Goooler** [comment]
If we are using `Netty` to request an HTTP URL on Android 9+, there is no exception thrown, but thrown with the use of `OkHttp`, cause the `isCleartextTrafficPermitted` check had been implemented by them, like [this](https://github.com/square/okhttp/blob/735ed1a6e5a15042f6d7e8f100fb3c8376f6aa27/okhttp/src/jvmMain/kotlin/okhttp3/internal/connection/RealRoutePlanner.kt#L205-L208), this is [a suggested behavior on Android](https://developer.android.com/reference/android/security/NetworkSecurityPolicy#isCleartextTrafficPermitted()):
> This flag is honored on a best effort basis because it's impossible to prevent all cleartext traffic from Android applications given the level of access provided to them.
