### ISSUE TITLE
NoClassDefFounderError: io/netty/handler/codec/ValueConverter

### ISSUE THREAD

**Issue by Dharmik2510** [netty/netty#13542]
I want to migrate from spring boot 2.7.x to 3.1.2:

Everything migrated successfully except one thing that I am getting following error:
```
NoClassDefFounderError: io/netty/handler/codec/ValueConverter
```
I am importing:

```
reactor.netty.http.client.HttpClient in my project
```

Can anyone suggest me what's wrong ?

**Comment by chrisvest** [comment]
Your Netty dependencies are a mix of different versions. Get them all to the same version and the problem will go away.
