### ISSUE TITLE
Exceptions may occur during the invocation of the Netty write method.

### ISSUE THREAD

**Issue by zhangjinying** [netty/netty#13544]
Exceptions that occur during the invocation of the Netty write method can sometimes not be caught by the exceptionCaught method, even when the protobuf compilation and runtime versions are consistent. In such cases, one way to locate the exception is by adding a listener to the write method. However, this approach can have a negative impact on performance.

It would be beneficial if these exceptions could be propagated through the pipeline and caught and handled by the user.

<img width="995" alt="image" src="https://github.com/netty/netty/assets/11245691/892de485-9b58-4947-9de4-8728aacf99b0">
<img width="1063" alt="image" src="https://github.com/netty/netty/assets/11245691/05700e04-f938-432e-aa17-185f114f7f73">

### Netty version
netty-4.1.96 Final

**Comment by hyperxpro** [comment]
This doesn't seem right as there is no guarantee in which order exception will be called back to the calling method due to how the event loop and scheduling work.

**Comment by normanmaurer** [comment]
outbound operations notify about failure by failing the future / promise. You can then add a listener to this future to be notified when a failure shows up
