### ISSUE TITLE
Closing an SslHandler always result in allocating a (silent) SslClosedEngineException

### ISSUE THREAD

**Issue by slandelle** [netty/netty#13569]
### Expected behavior

Closing an SslHandler should be a normal operation that should not trigger an error path nor allocate an Exception.

### Actual behavior

The issue is with `SslHandler#closeOutboundAndChannel`:
1. first it [closes the SSLEngine](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L2021)
2. then, it [calls `flush`](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L2034)
3. flush [pushes an empty ByteBuf into the pending writes buffer](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L2061)
4. later, [`wrapAndFlush` gets called](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L802)
5. wrap [crashes on the empty ByteBuf from above](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L902)

### Steps to reproduce

Close a Channel that has a SslHandler and debug the [line](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L902) where the `SslClosedEngineException` is allocated.

### Minimal yet complete reproducer code (or URL to code)

Not sure if it's necessary, please let me know.

### Netty version

4.1.97

### JVM version (e.g. `java -version`)

Irrelevant

### OS version (e.g. `uname -a`)

Irrelevant

**Comment by slandelle** [comment]
I'm not sure of the best way to fix this.
Only close the SSLEngine once the empty buffer is wrapped?
Make the SslClosedEngineException a constant (it's only thrown in one single place)?

**Comment by slandelle** [comment]
Related question: should `SslHandler` have a protection against multiple closings (currently happens in grpc-java)? Currently, it doesn't, so an Exception is created every time.

**Comment by normanmaurer** [comment]
I will have a look soonish.

**Comment by normanmaurer** [comment]
@slandelle https://github.com/netty/netty/pull/13580 fixes the problem... that said I think there is also something wrong on how we handle the SslCloseCompletionEvent. As this is not related I will fix this in another PR.
