### ISSUE TITLE
Updating BouncyCastle will be a breaking change

### ISSUE THREAD

**Issue by chrisvest** [netty/netty#13561]
As of Netty 4.1.96.Final, we're depending (optionally) on BouncyCastle release 1.68.

In BC release 1.71 and onwards, the Java version baseline of `-jdk15on` packages was bumped from Java 1.5 to Java 1.8:

> **Java Version Details** With the arrival of Java 15. jdk15 is not quite as unambiguous as it was. The jdk18on jars are compiled to work with anything from Java 1.8 up. They are also multi-release jars so do support some features that were introduced in Java 9, Java 11, and Java 15. If you have issues with multi-release jars see the jdk15to18 release jars below.
> 
> **Packaging Change (users of 1.70 or earlier):** BC 1.71 changed the jdk15on jars to jdk18on so the base has now moved to Java 8. For earlier JVMs, or containers/applications that cannot cope with multi-release jars, you should now use the jdk15to18 jars.

Since the Netty 4.1.x baseline Java version is 1.6, we would have to switch our dependencies to use the `-jdk15to18` packages.
However, this changes the Maven coordinates of where we get our BouncyCastle, which means that downstream projects that overwrite/bump/exclude the Netty version currently do so expecting a `-jdk15on` artifact name that this upgrade would no longer match. This can lead to projects having multiple, mismatched, versions of BouncyCastle on their class path – and we have enough of that with our own modules already.

If we on the other hand keep using the `-jdk15on` packages, we would keep such Maven dependency fiddling working, but we would be dropping support for using BC on Java 1.6 and 1.7.

Either way, upgrading BouncyCastle will be a breaking change. Or we can do nothing and downstream projects will have to upgrade/override/exclude, etc. our BC dependency.

What's the preferred approach?

**Comment by hyperxpro** [comment]
If we had to choose b/w compatibility and security, I'd prefer a major callout in 4.1.100.Final with this breaking change. Most of the applications will, either way, accept degradation. There is not much we can do about legacy application who don't upgrade deps at all.
