### ISSUE TITLE
Is there a way to auto generate netty handler subclass  native-image reflection config in other project

### ISSUE THREAD

**Issue by FoghostCn** [netty/netty#13588]
### Expected behavior
In our project based on Netty 4.1, we have to manually add GraalVM reflect-config configuration every time we add a new ChannelHandler. Is there a way to automatically generate the native-image configuration for the Native Image in third-party packages?

for now I konw netty has a util method to generate reflect-config `ChannelHandlerMetadataUtil.generateMetadata`, but for third-party package manually add reflection config is a bit troublesome.

### Netty version
4.1.95 
### JVM version (e.g. `java -version`)
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13, mixed mode, sharing)

### OS version (e.g. `uname -a`)
Darwin 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101 arm64

**Comment by FoghostCn** [comment]
@violetagg please take a look

**Comment by violetagg** [comment]
@FoghostCn you should be able to use `ChannelHandlerMetadataUtil.generateMetadata`. What's the issue?

**Comment by FoghostCn** [comment]
> @FoghostCn you should be able to use `ChannelHandlerMetadataUtil.generateMetadata`. What's the issue?

I wonder if there is a simpler way to generate the native-image configuration for projects depends on netty.

**Comment by violetagg** [comment]
I don’t know for another

**Comment by FoghostCn** [comment]
> 

Thank you very much for your reply

**Comment by FoghostCn** [comment]
> I don’t know for another
> […](#)

Thank you very much for your reply

**Comment by violetagg** [comment]
@FoghostCn I think we can close this one
