### ISSUE TITLE
Protect main and 4.1 branches

### ISSUE THREAD

**Issue by slandelle** [netty/netty#13590]
### Expected behavior

Fools like myself shouldn't be able to commit directly on the `main` and `4.1` branches by mistake, or worse push force. They should be required to open a PR with at least one reviewer to get it merged.
If necessary, core maintainers could be exempted from these rules.
All these protection rules are available in GitHub.

### Actual behavior

I inadvertently push into 4.1 and was able to remove my commit. Sorry about this.
I definitely shouldn't be able to do that.

**Comment by slandelle** [comment]
cc @normanmaurer

**Comment by normanmaurer** [comment]
Good point... let me do this :)
