### ISSUE TITLE
Malformed requests with Pseudo Headers in trailers

### ISSUE THREAD

**Issue by isaacrivriv** [netty/netty#13602]
### Expected behavior
According to RFC 7540 `Pseudo-header fields MUST NOT appear in trailers. Endpoints MUST treat a request or response that contains undefined or invalid pseudo-header fields as malformed (Section 8.1.2.6).` Requests with pseudo-header fields in trailers should be treated as malformed.

### Actual behavior
Pseudo-header on trailers requests are not treated as malformed.

### Steps to reproduce
Send a request with pseudo-headers in trailers.

### Minimal yet complete reproducer code (or URL to code)
Because of using the same headers as trailers, this can be reproduced with the test https://github.com/netty/netty/blob/f1fa227ddf675f055766d04900cce6804fd7f710/codec-http2/src/test/java/io/netty/handler/codec/http2/Http2ConnectionRoundtripTest.java#L1030

### Netty version
4.1.97

### JVM version (e.g. `java -version`)
openjdk version "17.0.7" 2023-04-18
IBM Semeru Runtime Open Edition 17.0.7.0 (build 17.0.7+7)
Eclipse OpenJ9 VM 17.0.7.0 (build openj9-0.38.0, JRE 17 Mac OS X amd64-64-Bit Compressed References 20230418_450 (JIT enabled, AOT enabled)
OpenJ9   - d57d05932
OMR      - 855813495
JCL      - 9d7a231edbc based on jdk-17.0.7+7)

### OS version (e.g. `uname -a`)
Mac OS X x86_64

**Comment by natl-set** [comment]
Looks like it breaks https://github.com/grpc/grpc-java/issues/10707

**Comment by chrisvest** [comment]
@natl-set that's a grpc-java issue, which they're fixing.
