### ISSUE TITLE
Infinite loop in NioEventLoop class: selectCnt variable switchs value between 0 and 1. 

### ISSUE THREAD

**Issue by BMouhcine** [netty/netty#13618]
Hello. I have a probably netty issue in my elasticsearch stack and I would like to get some help to understand what's happening.
### Expected behavior
Having a non infinite loop in NioEventLoop.

### Actual behavior
in NioEventLoop.java, the process begins with selectCnt variable set to 0. Then, it's incremented to 1, then it's reset to 0, and so on.
I found this behavior as I was going step by step in debug mode, until this class "NioEventLoop" where I saw this behavior.

### Steps to reproduce
an Elasticsearch cluster, when I execute a search request to an elasticsearch node, it doesn't respond (postman stuck in loading & waiting for response indefinitely..). 
Using elasticsearch 8.6.1.

### Netty version
`4.1.79.Final`
### JVM version (e.g. `java -version`)

```
openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment (build 19.0.1+10-21)
```

### OS version (e.g. `uname -a`)
Docker env with an image based on `ubuntu:20.04, focal, focal-20221130`.
I'll also dump this here: `Linux e5d1813a556a 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

Thank you !

**Comment by franz1981** [comment]
> Having a non infinite loop in NioEventLoop.

This is pretty expected: it's an endless loop till the event loop is shutdown.

I'm more interested into:

> when I execute a search request to an elasticsearch node, it doesn't respond

The cluster I suppose is accepting connections into a NIO Netty event loop: there are any exception which show that now data has been correctly handled and produced any response?
In any case it seems more like a ElasticSearch problem and I suggest first to report it there.

**Comment by BMouhcine** [comment]
@franz1981 thank you for your answer.
in fact, when I'm in debug mode, I can verify and see the response of elasticsearch, but it's never returned as an http response.
Also note that my java code that I use to handle request & response of elasticsearch is written in async. (CompletableFuture).
