### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _netty_jni_util_JNI_OnLoad

### ISSUE THREAD

**Issue by violetagg** [netty/netty#13632]
### Expected behavior

Reactor Netty build to pass with 4.1.98.Final

### Actual behavior

Reactor Netty build fails on Mac OS with 4.1.98.Final

```
dyld: lazy symbol binding failed: Symbol not found: _netty_jni_util_JNI_OnLoad

  Referenced from: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/libnetty_resolver_dns_native_macos_x86_641605797750362329464.dylib

  Expected in: flat namespace

dyld: Symbol not found: _netty_jni_util_JNI_OnLoad
  Referenced from: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/libnetty_resolver_dns_native_macos_x86_641605797750362329464.dylib
  Expected in: flat namespace
```

https://github.com/reactor/reactor-netty/actions/runs/6263458403/job/17007965364#step:5:94

### Netty version

4.1.98.Final

### JVM version (e.g. `java -version`)

```
Java configuration:
    Distribution: temurin
    Version: 8.0.382+5
```

### OS version (e.g. `uname -a`)

```
macOS
  11.7.9
```

**Comment by normanmaurer** [comment]
@violetagg I guess this is on intel, correct ?

**Comment by violetagg** [comment]
yep

**Comment by vivekkothari** [comment]
I am seeing this too.
```
dyld[64568]: missing symbol called
```

**Comment by raja-jamwal** [comment]
Seeing same on intel mac os. Tried with java 17 corretto and java 17.0.8.1-tem

**Comment by normanmaurer** [comment]
Yep seems like something broke while cross-compiling 🤦

**Comment by normanmaurer** [comment]
Fixed

**Comment by violetagg** [comment]
@normanmaurer thanks
