### ISSUE TITLE
io.netty.handler.ssl.SslHandshakeTimeoutException caused by BouncyCastle certificate loading being slow

### ISSUE THREAD

**Issue by niklas-sparfeld-gcx** [netty/netty#13645]
Hi! 👋 

We have a Spring Boot application which loads an Azure Storage Blob via Spring Cloud Azure.

In the same application we use the BouncyCastle security provider.

Under the hood a netty request to Azure's HTTP API is performed.

When the first request TLS handshake is performed, during consumption of the Server Hello, netty's `SSLEngine` gets an instance of `PKIXValidator`.

In `PKIXValidator.setTrustedObjects()` my system's 154 known certificates are loaded, during which `X509CertificateImpl.getPublicKey()` of BouncyCastle is called.

And the construction of those public keys is *very* slow, because it performs the `Primes.enhancedMRProbablePrimeTest(...)`.

When the BC provider is not installed, the HTTP request is performed instantaneously.

Questions: Is this "as designed"?

Or: *Should* BC and netty work together, or should I look into configuring netty so that it does not pick up the BC implementation?

![Screenshot 2023-10-02 at 11 20 42](https://github.com/reactor/reactor-netty/assets/70274334/53e2c6a1-d5a9-45a2-b607-48a6fbffb27d)

I'll create a BC issue as well. Maybe the solution is in their control 🤷 

https://github.com/bcgit/bc-java/issues/1499

## Expected Behavior

When using the BouncyCastle security provider, netty requests do not run into a timeout exception.

## Actual Behavior

When the BouncyCastle security provider is installed, the first netty request will fail with a `SslHandshakeTimeoutException`.

## Steps to Reproduce

We do this:

1. Create a Spring Boot 3.1.x application with `com.azure.spring:spring-cloud-azure-starter-storage-blob`.
2. Configure `spring.cloud.azure.storage.blob`
3. Use `Security.insertProviderAt(BouncyCastleProvider(), 1)`
4.  Use `ResourceLoader` to load a `azure-blob://...` URI

I did not yet test it, but I guess *every* HTTPS request will fail similarly when the BC provider is installed.

## Your Environment

* Other relevant libraries versions (eg. `netty`, ...): 
* JVM version (`java -version`):
* OS and version (eg. `uname -a`): 

### Netty version

4.1.97.Final

Spring Boot 3.1.4

### JVM version (e.g. `java -version`)

liberica-17.0.8.1+1

### OS version (e.g. `uname -a`)

macos 14.0

**Comment by chrisvest** [comment]
BouncyCastle being slow is to be expected. It's pure Java implementations of crypto APIs. They're not meant to be fast, but rather to handle weird and niche cases. BouncyCastle is for doing things you cannot otherwise do through the normal Java security and crypto APIs.
I recommend you either use the built in Java security provider, or Amazon corretto security provider.
Do you have a very good reason to use BouncyCastle as the installed security provider, instead of a library you only call into in special cases?
