### ISSUE TITLE
Add support for RISC-V

### ISSUE THREAD

**Issue by luhenry** [netty/netty#13667]
### Expected behavior

Netty should work on linux-riscv64

### Actual behavior

Netty doesn't work on linux-riscv64. The packages containing native libraries don't have support for linux-riscv64.

### Steps to reproduce

Install and run any application depending on netty on a linux-riscv64 machine. You can also try to build and test Netty with [QEMU user emulation](https://www.qemu.org/docs/master/user/index.html)

### Minimal yet complete reproducer code (or URL to code)

```
podman run --rm -it --privileged --platform riscv64 -v $(pwd):$(pwd) -w $(pwd) riscv64/ubuntu:23.04 bash -c "apt update; apt install -y openjdk-21-jdk; ./mvnw clean package"
```

### Netty version

4.1

### JVM version (e.g. `java -version`)

11, 17, 21

### OS version (e.g. `uname -a`)

```
Linux 85a338514ae4 6.2.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct  6 10:23:26 UTC 2 riscv64 riscv64 riscv64 GNU/Linux
```

**Comment by chrisvest** [comment]
The NIO transport and JDK SSL providers should still work, as they are plain Java without JNI parts.

**Comment by luhenry** [comment]
brotli4j is currently adding support with https://github.com/hyperxpro/Brotli4j/pull/111 and https://github.com/hyperxpro/Brotli4j/pull/112.

**Comment by luhenry** [comment]
I'm currently working on adding support. I'll submit a PR shortly.
