### ISSUE TITLE
Unable to get path params from URL using Netty Http Request

### ISSUE THREAD

**Issue by ashok-mariyala** [netty/netty#13662]
I am trying to get the path parameters from the given URL using `io.netty.handler.codec.http.FullHttpRequest`. But here i am able to get the query params from the requested URL but not path params. 

E.g: 
```
/api/v1/services/{servicename}/containers/{containerid}?state=running
```
Here i am able to get the query params (`state=running`) using following snippet
```
QueryStringDecoder queryDecoder = new QueryStringDecoder(request.uri());
Map<String, List<String>> parameters = queryDecoder.parameters();
```
But here how can i to get the path parameters (`{servicename}` and `{containerid}`)

**Comment by slandelle** [comment]
I don't think there's any tool for this in Netty. 

If there are no chars that require encoding, you can just use a regex.
If you have more complex use cases, you'll have to use another lib for this: https://github.com/topics/url-parsing?l=java
