### ISSUE TITLE
Memory leak when using SslHandler

### ISSUE THREAD

**Issue by JaquierM** [netty/netty#13698]
### Expected behavior

No memory leak.

### Actual behavior

When a connection is open, we send data and the ram usage increase depending on the size of the data.

The java heap stay in a correct range (500 - 1000 Mb) but the process ram is increasing for each request (approximately by the size of the send payload).

The problem source is probably the off-heap allocation but even with the option `-Dio.netty.leakDetectionLevel=PARANOID` no error are shown.

When disabling the `.addLast(sslCtx.newHandler(ch.alloc()))`, the leak disappear.

### Steps to reproduce

1. Create a SslContext for a server with a crt, key and ca.
2. Bootstrap a server
3. Initialize a channel with :
  - sslHandler
  - ChannelInboundHandlerAdapter that send the data and close the channel
4. Send some requests with wget for example
5. The ram used should increase

### Minimal yet complete reproducer code (or URL to code)

1. Generate a random data file.
```console
dd if=/dev/urandom of=/tmp/random1G.bin bs=1G count=1 status=progress
```

2. Launch the server to send the data upon request.
```java
package org.example

import io.netty.bootstrap.ServerBootstrap;
import io.netty.buffer.ByteBuf;
import io.netty.channel.*;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.handler.logging.LogLevel;
import io.netty.handler.logging.LoggingHandler;
import io.netty.handler.ssl.ClientAuth;
import io.netty.handler.ssl.SslContext;
import io.netty.handler.ssl.SslContextBuilder;

import java.io.ByteArrayInputStream;
import java.io.FileInputStream;
import java.io.IOException;

public class Main {

    static final int PORT = Integer.parseInt(System.getProperty("port", "2222"));

    public static void main(String[] args) throws Exception {

        SelfSignedCertificate selfSignedCertificate = new SelfSignedCertificate("test");
        SslContext sslCtx = SslContextBuilder
            .forServer(selfSignedCertificate.certificate(), selfSignedCertificate.privateKey())
            .clientAuth(ClientAuth.OPTIONAL)
            .protocols(new String[] {"TLSv1.3"})
            .build();

        EventLoopGroup bossGroup = new NioEventLoopGroup(1);
        EventLoopGroup workerGroup = new NioEventLoopGroup();

        try {
            ServerBootstrap b = new ServerBootstrap();
            b.group(bossGroup, workerGroup)
                .channel(NioServerSocketChannel.class)
                .option(ChannelOption.SO_BACKLOG, 100)
                .handler(new LoggingHandler(LogLevel.INFO))
                .childHandler(new ChannelInitializer<SocketChannel>() {
                    @Override
                    public void initChannel(SocketChannel ch) {
                        ch.pipeline()
                            .addLast(sslCtx.newHandler(ch.alloc()))
                            .addLast(new ChannelInboundHandlerAdapter() {
                                @Override
                                public void channelActive(final ChannelHandlerContext ctx) {
                                    try {
                                        byte[] datas = new FileInputStream("/tmp/random1G.bin").readAllBytes();

                                        ByteBuf buffer = ctx.alloc().buffer(datas.length);
                                        buffer.writeBytes(datas);

                                        ctx.writeAndFlush(buffer).addListener(f -> ctx.close());
                                    } catch (IOException e) {
                                        System.out.println("closing " + e.getMessage());
                                        ctx.close();
                                    }
                                }
                            })
                            .addLast(new ChannelDuplexHandler() {
                                @Override
                                public void exceptionCaught(final ChannelHandlerContext ctx, final Throwable cause) {
                                    ctx.close();
                                }
                            });
                    }
                });

            // Bind and start to accept incoming connections.
            ChannelFuture f = b.bind(PORT).sync();

            // Wait until the server socket is closed.
            // In this example, this does not happen, but you can do that to gracefully
            // shut down your server.
            f.channel().closeFuture().sync();
        } finally {
            workerGroup.shutdownGracefully();
            bossGroup.shutdownGracefully();
        }
    }
}
```

### Netty version

6.1.101.Final

### JVM version (e.g. `java -version`)

openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05)
OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05, mixed mode, sharing)

### OS version (e.g. `uname -a`)

Linux workstation 6.5.0-2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.6-1 (2023-10-07) x86_64 GNU/Linux

**Comment by hyperxpro** [comment]
How big is your payload? What is the transfer speed? Which cipher are you exactly using?

**Comment by JaquierM** [comment]
The payload was around 1GB when we detected the problem but it is present with smaller payload (200MB).
On my machine, the speed is around 900MB/s.
The cipher suite is TLS_AES_128_GCM_SHA256.

**Comment by hyperxpro** [comment]
1 GB+ of memory usage seems fine.

Also, you're reading all data into `byte[]` and it will indeed result in larger heap usage, and GC will not immediately kick in.

**Comment by chrisvest** [comment]
A few suggestions:

1. Transport the file using a sequence of smaller buffers, and look out for channel writability – this allow our pooling buffer allocator to help you more.
2. Switch to using the native epoll transport, and tcnative-boringssl-static TLS implementation – this will let your pipeline use off-heap buffers throughout, so there's no need to copy data between heap and native memory.
3. Open your file with `FileChannel` instead of `FileInputStream` – this API lets you do file IO with off-heap buffers as well.
4. Allocate buffers using the `ByteBufAllocator.ioBuffer(int)` method, and read the file data using `ByteBuf.writeBytes(FileChannel, position, length)` – for actually doing the efficient off-heap file IO.

**Comment by JaquierM** [comment]
I was able to solve my problem. It was a misunderstanding of how buffers work (pool with SSL) and a misuse of Netty.

By using a ChunkedFile, the leak is gone.

Thanks a lot for your help.
