### ISSUE TITLE
Obtaining corrupted data when reading length-delimited payload from TCP stream

### ISSUE THREAD

**Issue by mkpaz** [netty/netty#13696]
### Behavior

I have a fairly simple TCP server that collects [IPFIX](https://datatracker.ietf.org/doc/html/rfc5101) (basically Netflow) from a network equipment. It's a length-delimited protocol that has the following structure:

- version, 2 bytes
- length (whole message), 2 bytes
- timestamp, 4 bytes,
- sequence number, 4 bytes
- body, the rest of the message

The issue is that I quite often receive corrupted data in the message handler. Most of the time, it's just a truncated body. Sometimes, the sequence numbers are out of order, and at times, I  receive what I call "frankenstein" messages.

![image](https://github.com/netty/netty/assets/25181998/4b000118-60d8-4455-9c7f-de576d655536)

**Server:**

```java
public final class Server {

    private final Config config;
    private final NioEventLoopGroup bossGroup;
    private final NioEventLoopGroup workerGroup;
    private @Nullable ChannelFuture channelFuture;

    public Server(Config config) {
        this.config = Objects.requireNonNull(config, "config can not be null");

        this.bossGroup = new NioEventLoopGroup();
        this.workerGroup = config.workerThreads() >= 0
                ? new NioEventLoopGroup(config.workerThreads())
                : new NioEventLoopGroup();
    }

    public void start() {
        var b = new ServerBootstrap()
                .group(bossGroup, workerGroup)
                .channel(NioServerSocketChannel.class)
                .childHandler(createPipeline())
                .option(ChannelOption.RCVBUF_ALLOCATOR, new AdaptiveRecvByteBufAllocator(1024 * 2, 1024 * 8, 1024 * 64));

        if (config.recvBufferBytes() > 0) {
            b = b.option(ChannelOption.SO_RCVBUF, config.recvBufferBytes());
        }

        var inet = new InetSocketAddress(config.host(), config.port());

        try {
            channelFuture = b.bind(inet).sync();
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }

    private ChannelInitializer<SocketChannel> createPipeline() {
        return new ChannelInitializer<>() {
            @Override
            public void initChannel(SocketChannel ch) {
                ch.pipeline().addLast(
                        new LengthFieldBasedFrameDecoder(config.maxFrameLength(), 2, 2, -4, 0)
                );
                ch.pipeline().addLast(new Dispatcher(config));
            }
        };
    }
}
```

**Handler:**

```java
public final class Dispatcher extends SimpleChannelInboundHandler<ByteBuf> {

    private final Config config;

    public Dispatcher(Config config) {
        this.config = Objects.requireNonNull(config, "config can not be null");
    }
    
    @Override
    protected void channelRead0(ChannelHandlerContext ctx, ByteBuf src) {
        // dispatcher basically just copies some bytes from the received buffer
        // and pushes it to the consumer queue, no reader or writer indices changed
        final var dest = PooledByteBufAllocator.DEFAULT.buffer(<length>);
        src.getBytes(12, dest, 14);
        queue.offer(dest);
    }
}
```

I've tried to:

- increase `SO_RCVBUF` up to 16MB
- increase expected frame length in allocator
- increase worker thread count

Nothing helps, I still got data corrupted and I honestly have no idea how to debug it further. TCP should prevent data loss. Could it be a fragmentation issue in the `ByteToMessageDecoder`?

### Netty version

4.1.100.Final

### JVM version (e.g. `java -version`)

17.0.6+10-LTS

### OS version (e.g. `uname -a`)

Centos 7.5

**Comment by mkpaz** [comment]
I removed all custom handlers and conducted some tests using tcpdump. I noticed that Wireshark shows occurrences of duplicate ACKs and lost segments happening simultaneously when data loss occurs. This suggests to me that there may be a performance bottleneck. TCP is supposed to ensure data delivery and integrity, but it seems that Netty's TCP implementation may not be as reliable. This could be due to its optimization for many short-lived connections, whereas I have only a few devices that send a significant amount of data through a constant TCP connection.

There's also a [similar issue](https://github.com/netty/netty/issues/12184) already. So, I guess I'm not the only one with this problem. Maybe Java is just a wrong language to implement this kind of server.

**Comment by normanmaurer** [comment]
@mkpaz your `Dispatcher` code is not correct, which is the first thing I can spot. 

```
 @Override
    protected void channelRead0(ChannelHandlerContext ctx, ByteBuf src) {
        // dispatcher basically just copies some bytes from the received buffer
        // and pushes it to the consumer queue, no reader or writer indices changed
        final var dest = PooledByteBufAllocator.DEFAULT.buffer(<length>);
        src.getBytes(src.readerIndex() + 12, dest, 14);
        queue.offer(dest);
    }
```

That said I am not sure how you can even assume that there will be 14 bytes to read ?  Don't you want to basically read `src.readableBytes() - 12` ?
