### ISSUE TITLE
When can netty use JDK21's virtual threads

### ISSUE THREAD

**Issue by iuxuanbor** [netty/netty#13720]
When can netty use JDK21's virtual threads?   !!!!!!!!!!!!!!!!!

**Comment by godmao233** [comment]
now

**Comment by Nefrols** [comment]
You can try using something like this:
`MultithreadEventLoopGroup workerGroup = new NioEventLoopGroup(1, Executors.newVirtualThreadPerTaskExecutor());`

**Comment by pbk20191** [comment]
> You can try using something like this: `MultithreadEventLoopGroup workerGroup = new NioEventLoopGroup(1, Executors.newVirtualThreadPerTaskExecutor());`

`Selector.select` does not support VirtualThread. `MultithreadEventLoopGroup workerGroup = new NioEventLoopGroup(1, Executors.newVirtualThreadPerTaskExecutor());` will cause all your Carried Thread stucked. 

You have use Oio-channel with `OioEventLoopGroup` on Netty4. which is not available in Netty5.

**Comment by wolftobias** [comment]
Why you close this? It's still not working right.

**Comment by MazizEsa** [comment]
Its not going to be supported based on https://github.com/netty/netty/issues/12816
