### ISSUE TITLE
When the server returns the Sec WebSocket Protocol header but the content is empty, the handshake should be successful rather than failed

### ISSUE THREAD

**Issue by alleniverson33** [netty/netty#13726]
### Expected behavior
When the server returns the Sec WebSocket Protocol header but the content is empty, the handshake should be successful rather than failed
### Minimal yet complete reproducer code (or URL to code)
if (expectedProtocol.isEmpty() && receivedProtocol == null) {
            protocolValid = true;
            this.setActualSubprotocol(this.expectedSubprotocol);
        } else if (!expectedProtocol.isEmpty() && receivedProtocol != null && !receivedProtocol.isEmpty()) {
            String[] var6 = expectedProtocol.split(",");
            int var7 = var6.length;

            for(int var8 = 0; var8 < var7; ++var8) {
                String protocol = var6[var8];
                if (protocol.trim().equals(receivedProtocol)) {
                    protocolValid = true;
                    this.setActualSubprotocol(receivedProtocol);
                    break;
                }
            }
        }

        if (!protocolValid) {
            throw new WebSocketClientHandshakeException(String.format("Invalid subprotocol. Actual: %s. Expected one of: %s", receivedProtocol, this.expectedSubprotocol), response);
        } 
receivedProtocol is empty ， not null
### Netty version
4.1.101.Final

**Comment by normanmaurer** [comment]
Can you point me to the relevant RFC section ?

**Comment by alleniverson33** [comment]
> Can you point me to the relevant RFC section ?

The sub protocol returned by the websocket server is an empty string, and I do not have the authority to change the server-side

**Comment by amizurov** [comment]
@alleniverson33 Hi, i think this is a problem on your server side. According RFC https://datatracker.ietf.org/doc/html/rfc6455#section-4.2.2 (/subprotocol/), server MUST NOT send back an empty value.

If you can not change the server behaviour you can add custom handler before `WebSocketClientProtocolHandshakeHandler` and remove that empty header if that OK for you. Once the handshake completes successfully, remove this custom handler from the pipeline.

**Comment by alleniverson33** [comment]
> @alleniverson33 Hi, i think this is a problem on your server side. According RFC https://datatracker.ietf.org/doc/html/rfc6455#section-4.2.2 (/subprotocol/), server MUST NOT send back an empty value.
> 
> If you can not change the server behaviour you can add custom handler before `WebSocketClientProtocolHandshakeHandler` and remove that empty header if that OK for you. Once the handshake completes successfully, remove this custom handler from the pipeline.

thanks
