### ISSUE TITLE
NioEventLoop wakeup failed.

### ISSUE THREAD

**Issue by echooymxq** [netty/netty#13738]
### Expected behavior
NioEventLoop selector wake_up work well.
### Actual behavior

We use `NioEventLoop`  at server, the simple logic is the business thread call `writeAndFlush` to write response to client, after the server run some days, the write delay is very significant and it's callback future will be very slow. i add some log to see what happend. we found the selector#select to epoll_wait first, and the business thread add write task to wakeup the selector, but it will not wakeup until some read event happend. It's a bit strange about only a few of nio selector theads affected.

### Steps to reproduce
I can't reproduce it , a production enviroment run some days, it will ocurr, then restart the server, it can resume work well.

### Netty version

4.1.78.Final

### JVM version (e.g. `java -version`)
1.8.0_221

### OS version (e.g. `uname -a`)

linux 4.19.90 aarch64

**Comment by normanmaurer** [comment]
Please update your netty version first and see if you can still can reproduce it
