### ISSUE TITLE
Heap are used by 2048 pregenerate unused error messages

### ISSUE THREAD

**Issue by Munoon** [netty/netty#13731]
I am investigating memory heap of my application and found a ton of error strings (see screenshot). I see, that netty loads it in static block, but it's not clear to me why would I need it.
![Снимок экрана 2023-12-15 в 12 29 52](https://github.com/netty/netty/assets/43534008/7be18d99-85d4-45be-8992-0b1caea9334b)

Maybe there is some way to avoid this class loading? I am using 512MB of RAM on my production servers, while memory usage is high enough, so unneeded memory allocation is crucial for me.

It might be helpful to know, that I am using BoringSSL on my project.

### Netty version
4.1.99.Final

### JVM version (e.g. `java -version`)
```
openjdk version "21-ea" 2023-09-19
OpenJDK Runtime Environment (build 21-ea+35-Ubuntu-1ubuntu120.04)
OpenJDK 64-Bit Server VM (build 21-ea+35-Ubuntu-1ubuntu120.04, mixed mode, sharing)
```

### OS version (e.g. `uname -a`)
`Linux XXX 5.4.0-169-generic #187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by normanmaurer** [comment]
these are used by the native transports., honestly I think the benefits of have these static vs not is bigger then saving a few mbs.
