### ISSUE TITLE
high heap used

### ISSUE THREAD

**Issue by L-Jim** [netty/netty#13744]
### Actual behavior
when workerGroup greater than 1 heap Significant increase
### Steps to reproduce
Using concurrent connections(about 4000 Client Connection)，Change workerGroup to any number greater than 1;
workerGroup=1
<img width="1180" alt="Snipaste_1" src="https://github.com/netty/netty/assets/21225136/7d7509c6-e8b3-4067-a343-5b6b6ddccccb">
workerGroup=2
<img width="1180" alt="Snipaste_2" src="https://github.com/netty/netty/assets/21225136/9f45b15b-64d8-40ac-97c8-16fbaba4f5fb">
### Minimal yet complete reproducer code (or URL to code)

`public class NettyDemo {

    public static void main(String[] args) throws Exception {
        new NettyDemo().start(8080);
    }
  
    public void start(int port) throws Exception {
        DefaultChannelGroup channelGroup = new DefaultChannelGroup(new DefaultEventLoop());

        EventLoopGroup bossGroup = new NioEventLoopGroup(1); 
        EventLoopGroup workerGroup = new NioEventLoopGroup(1); Change any number greater than 1
        try {
            ServerBootstrap b = new ServerBootstrap(); // (2)
            b.group(bossGroup, workerGroup)
                    .channel(NioServerSocketChannel.class) // (3)
                    .childHandler(new ChannelInitializer<SocketChannel>() {
                        @Override
                        protected void initChannel(SocketChannel ch) throws Exception {
                            ch.pipeline().addLast(new HttpServerCodec());
                            ch.pipeline().addLast(new HttpObjectAggregator(8192));
                            ch.pipeline().addLast(new AuthHandler(channelGroup));
                            ch.pipeline().addLast(new WebSocketServerProtocolHandler("/websocket", true));
                            ch.pipeline().addLast(new MyWebSocketServerHandler());
                        }
                    })
                    .option(ChannelOption.SO_BACKLOG, 128)// (5)
                    .childOption(ChannelOption.SO_KEEPALIVE, true); // (6)
            ChannelFuture f = b.bind(port).sync(); // (7)
            f.channel().closeFuture().sync();
        } finally {
            workerGroup.shutdownGracefully();
            bossGroup.shutdownGracefully();
        }
    }

    public static class AuthHandler extends ChannelInboundHandlerAdapter {

        private final DefaultChannelGroup DEFAULT_CHANNEL_GROUP;
        AuthHandler(DefaultChannelGroup defaultChannelGroup){
            this.DEFAULT_CHANNEL_GROUP = defaultChannelGroup;
        }
        @Override
        public void channelRead(ChannelHandlerContext ctx, Object msg) {
            if (msg instanceof FullHttpRequest request) {
                Channel channel = ctx.channel();
                String s = STR."channel: \{channel.id()} Login";
                ctx.fireChannelRead(request.retain());
                DEFAULT_CHANNEL_GROUP.writeAndFlush(new TextWebSocketFrame(s));
                DEFAULT_CHANNEL_GROUP.add(channel);
                ReferenceCountUtil.release(msg);
            } else {
                ctx.fireChannelRead(msg);
            }
        }

    }

    public static class MyWebSocketServerHandler extends SimpleChannelInboundHandler<WebSocketFrame> {

        @Override
        protected void channelRead0(ChannelHandlerContext ctx, WebSocketFrame msg) {
            WebSocketFrame webSocketFrame;
            switch (msg) {
                case PingWebSocketFrame pingWebSocketFrame -> webSocketFrame = new PongWebSocketFrame();
                case PongWebSocketFrame pongWebSocketFrame -> webSocketFrame = new PingWebSocketFrame();
                default -> webSocketFrame = new TextWebSocketFrame("ok");
            }
            ctx.channel().writeAndFlush(webSocketFrame);
        }
    }
}`

### Netty version
io.netty,netty-all,4.1.101.Final
### JVM version (e.g. `java -version`)
openjdk version "21.0.1" 2023-10-17
OpenJDK Runtime Environment Homebrew (build 21.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 21.0.1, mixed mode, sharing)
### OS version (e.g. `uname -a`)
MacOs-M1Max
Darwin xx 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64

**Comment by franz1981** [comment]
.option(ChannelOption.SO_BACKLOG, 128)// (5) doesn't seem a good idea with 4000 Client Connections, anyway...raise it to avoid queuing, unless is what you need.


Additionally, I suggest to take an heap dump/histogram with worker group 1 and beyond and report what's the diff between them, and which instances seems to not grow proportionally. If they belong to Netty, we can look at it.

**Comment by normanmaurer** [comment]
Yeah without more details its impossible to help

**Comment by normanmaurer** [comment]
Closing... there is nothing we can do without more details
