### ISSUE TITLE
Partitioned attribute support in ResponseCookie class

### ISSUE THREAD

**Issue by aramired** [netty/netty#13740]
Chrome is going to deprecate third party cookies in near future, and it is mentioned [here](https://developers.google.com/privacy-sandbox/3pcd). 

We have many integration/leading applications depends on cross site cookies; all those will not work if the third-party cookies are not allowed to use.

There are some suggested ways to mitigate cross site issues which depend on cookies.

Cookies having independent partitioned state (CHIPS) is one of the proposals(https://developer.chrome.com/docs/privacy-sandbox/chips/).

For this, in ResponseCookie need a Boolean attribute called **partitioned** similar to secure field

```
private final boolean partitioned;

/**
* Add the "Partitioned" attribute to the cookie.
*/
ResponseCookieBuilder partitioned(boolean partitioned);
```

For testing purposes, we did try extending httpcookie and created custom cookie class but to add that cookie in exchange response, they are expecting only of type ResponseCookie
spring-web/src/main/java/org/springframework/http/server/reactive/ServerHttpResponse.java - getCookies() and addCookie() 

We do create the below request https://github.com/spring-projects/spring-framework/issues/31454

Please do provide this support as early as possible, we want to test by disabling third party cookies from leading applications for impact analysis.

Thanks in advance.

**Comment by svankamamidi** [comment]
We are also facing the same issue.

**Comment by vseetha2007** [comment]
We are also facing the same issue
