### ISSUE TITLE
PooledByteBufAllocator.newDirectBuffer memory leak

### ISSUE THREAD

**Issue by rickyma** [netty/netty#13743]
I've encountered a memory-leak issue. Any ideas to fix this?

ERROR io.netty.util.ResourceLeakDetector.reportTracedLeak:319 - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
        io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:402)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
        io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:140)
    io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
    io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:150)
    io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
    io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
    io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
    io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
    io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
    io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    java.lang.Thread.run(Thread.java:750)

### Netty version
4.1.104.Final
### JVM version (e.g. `java -version`)
1.8.0_392
### OS version (e.g. `uname -a`)
CentOS 7.9

**Comment by chrisvest** [comment]
A buffer was allocated to hold some incoming data from a socket. The buffer was most likely sent to your pipeline where no code called `release()` on it, and thus it leaked.

**Comment by rickyma** [comment]
Why can't I see the stacktrace of my own classes? I can only find the stacktrace of io.netty. @chrisvest

**Comment by chrisvest** [comment]
You can call `touch()` on the ByteBuf, which will record the stack trace at the call site. Setting leak detection level to `paranoid` will also make it retain more records.

**Comment by rickyma** [comment]
Thx, I'll have a try.

**Comment by normanmaurer** [comment]
I will close this for now... Please re-open with more details if you still think this is a netty issue
