### ISSUE TITLE
Bad string Error

### ISSUE THREAD

**Issue by heixiaoma** [netty/netty#13748]
```
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.101.Final</version>
        </dependency>
```
POST json data

```
{productRequirements: "<p><span style=\"font-family: Verdana;\">1w</span></p>"}
```
content-type" -> application/json;charset=UTF-8
HttpPostRequestDecoder decoder = new HttpPostRequestDecoder(FACTORY, req);

![image](https://github.com/netty/netty/assets/10923974/2dc75885-b663-4eaa-ad19-f38de9cbe460)

**Comment by chrisvest** [comment]
POST requests frame their form data either as URL-encoded key-value tuples, or as multipart data blocks: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST

Your request appear to assume that you can include the request data directly in the request body, but those are the semantics of a PUT request: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT
