### ISSUE TITLE
How can i send multi response data to a http request?

### ISSUE THREAD

**Issue by zjcDM** [netty/netty#13768]
### Discussed in https://github.com/netty/netty/discussions/13767

<div type='discussions-op-text'>

<sup>Originally posted by **zjcDM** January  6, 2024</sup>
The channel pipeline is set like this:

    protected void initChannel(Channel ch) {
        ch.pipeline().addLast(new HttpServerCodec());
        ch.pipeline().addLast(new HttpObjectAggregator(
            Math.max(Config.DEFAULT_MAX_CONTENT_SIZE_100M, Config.INSTANCE.getMaxContentSize())));
        CorsConfig corsConfig = CorsConfigBuilder.forAnyOrigin()
            .allowNullOrigin()
            .allowCredentials()
            .preflightResponseHeader(HttpHeaderNames.ACCESS_CONTROL_ALLOW_HEADERS, HttpHeaderNames.CONTENT_TYPE)
            .build();
        ch.pipeline().addLast(new CorsHandler(corsConfig));
        ch.pipeline().addLast("handler", requestHandler);
    }

and multi response data send back like this:

                if (response.isFirst()) {
                    System.out.println("send first chunk");
                    FullHttpResponse httpResponse = new DefaultFullHttpResponse(HttpVersion.HTTP_1_1, HttpResponseStatus.OK, Unpooled.copiedBuffer(body, CharsetUtil.UTF_8));
                    ResponseUtils.addHead(httpResponse, HttpHeaderNames.CONTENT_TYPE, HttpHeaderValues.APPLICATION_JSON);
                    channel.writeAndFlush(httpResponse);
                    if (response.isLast()) {
                        channel.close();
                    }
                    return;
                }

                ByteBuf data = Unpooled.copiedBuffer(response.getResponseBody(), CharsetUtil.UTF_8);
                if (response.isLast()) {
                    System.out.println("send last chunk");
                    channel.writeAndFlush(new DefaultLastHttpContent(data)).addListener(ChannelFutureListener.CLOSE);
                } else {
                    System.out.println("send data chunk");
                    channel.writeAndFlush(new DefaultHttpContent(data));
                }

The result is the first response get by client, rest are gone.
</div>

**Comment by hyperxpro** [comment]
Use HttpResponse and DefaultHttpResponse.

FullHttpResponse will mark the request/response as fulfilled.

**Comment by zjcDM** [comment]
Thanks very much， it's works like this:

                if (response.isFirst()) {
                    System.out.println("send first chunk");
                    DefaultHttpResponse httpResponse = new DefaultHttpResponse(HttpVersion.HTTP_1_1, HttpResponseStatus.OK);
                    channel.writeAndFlush(httpResponse);
                }

                ByteBuf data = Unpooled.copiedBuffer(response.getResponseBody(), CharsetUtil.UTF_8);
                if (response.isLast()) {
                    System.out.println("send last chunk");
                    channel.writeAndFlush(new DefaultLastHttpContent(data)).addListener(ChannelFutureListener.CLOSE);
                } else {
                    System.out.println("send data chunk");
                    channel.writeAndFlush(new DefaultHttpContent(data));
                }
