### ISSUE TITLE
Empty WebSocketFrame cannot be released since 4.1.80.Final

### ISSUE THREAD

**Issue by lx-2015** [netty/netty#13766]
### Expected behavior
Our handler takes the `PingWebSocketFrame` and tries to release it. Because sometimes the `refCnt` is more than 1 (e.g., 2), we have a do-while loop to release the `PingWebSocketFrame`. Previously this has been working correctly for both empty and non-empty `PingWebSocketFrame`.

### Actual behavior
The release of empty `PingWebSocketFrame` stops working. The `refCnt` does not get reduced when `ReferenceCountUtil.release(pingWebSocketFrame);` is called. Since we have a do-while loop, the code runs into infinite loop. The issue is applicable to all [subclasses of WebSocketFrame](https://netty.io/4.1/api/io/netty/handler/codec/http/websocketx/WebSocketFrame.html).

### Steps to reproduce
Establish a WebSocket channel, and then send an empty `PingWebSocketFrame` (`new PingWebSocketFrame()`) to it. The other side of the channel tries to release the `PingWebSocketFrame` in a do-while loop (see next session).

### Minimal yet complete reproducer code (or URL to code)

```
public class PingCheckHandler extends ChannelInboundHandlerAdapter {
...

    @Override
    public void channelRead(final ChannelHandlerContext ctx, final Object msg) {
        if (msg instanceof PingWebSocketFrame) {
            PingWebSocketFrame pingWebSocketFrame = (PingWebSocketFrame) msg;
            do {
                ReferenceCountUtil.release(pingWebSocketFrame);
            } while (pingWebSocketFrame.refCnt() > 0);
...
```

### Netty version
We recently upgraded to latest Netty4, during which we noticed the issue. Further investigation shows that the first Netty4 version having this issue is 4.1.80.Final. 

More specifically, [this change seems to be related](https://github.com/netty/netty/pull/12651/files#diff-62f6c7c8221f5ffb30f75a7cdcab118c2e3d5a06d6416a759b072493280ab237R314-R318): the `payloadBuffer` is initialized as `Unpooled.EMPTY_BUFFER` and will not be updated for empty `PingWebSocketFrame` since `framePayloadLength == 0`. However, [EmptyByteBuf does not reduce refCnt during release](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/EmptyByteBuf.java#L1006-L1032).

### JVM version (e.g. `java -version`)
JDK8

### OS version (e.g. `uname -a`)
Linux 5.4.257-177.360.amzn2int.x86_64 x86_64

**Comment by normanmaurer** [comment]
you should never release something in a loop. Seems like you miss a release somewhere else
