### ISSUE TITLE
关于netty的ByteBuf与protobuf的序列化零拷贝

### ISSUE THREAD

**Issue by LinHuiG** [netty/netty#13774]
你好，我在实践中使用netty+protbuf进行通信，但是每次我encode或者decode的时候，我需要将byte[]从ByteBuf读出，然后交给protobuf进行decode，或者我需要将对象由protobuf encode为byte[]后再写入ByteBuf。
这额外的一次拷贝让我有点困扰，我发现protoBuf有writeTo和readFrom函数，不知道netty是否对此有支持，或者有什么合适的方案可以告诉我呢。
非常感谢

**Comment by He-Pin** [comment]
@LinHuiG This is an issue tracker and you can ask question in `Discussions`, btw, please use English not Chinese.
