### ISSUE TITLE
Failed to load the required native library. Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_osx_x86_64.jnilib

### ISSUE THREAD

**Issue by currencyft** [netty/netty#13772]
### Expected behavior
To connect to a hyperledger fabric network
Network network = gateway.getNetwork(channelName)
### Actual behavior
Error was thrown
Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_osx_x86_64.jnilib
### Steps to reproduce
The code is a SpringBoot Application
**_Environment_**:
gradle version: 7.5.1
java version 11
**_dependencies_**:

implementation 'com.google.guava:guava:29.0-jre'
implementation 'org.hyperledger.fabric:fabric-gateway-java:2.1.1'

```
public String createWallet() throws Exception{
        Path walletPath = Paths.get("wallet");
        Wallet wallet = Wallets.newFileSystemWallet(walletPath);

        Path networkConfigPath = Paths.get(commonConnectionProfile);
        Gateway.Builder builder = Gateway.createBuilder();
        builder.identity(wallet, appUser)
                .networkConfig(networkConfigPath)
                .discovery(true);
        Gateway gateway = builder.connect();
        Network network = gateway.getNetwork(channelName);

        return "hello";
    }
```

### Minimal yet complete reproducer code (or URL to code)
Network network = gateway.getNetwork(channelName);

### Netty version
Netty is bundled with: com.google.guava:guava:29.0-jre

### JVM version (e.g. `java -version`)
Java 11
### OS version (e.g. `uname -a`)
MacBook Apple Pro M3.
OS Sonoma 14.2.1

**Comment by hyperxpro** [comment]
See: https://netty.io/wiki/forked-tomcat-native.html
