### ISSUE TITLE
Support for hybrid RSA/ECC Certificates

### ISSUE THREAD

**Issue by JimmyBaize** [netty/netty#13776]
### Expected behavior
Use netty to start the TLS server (using tc-native boringssl). 
If the client supports the ECC algorithm, the server returns the ECC certificate first. Otherwise, the server returns the RSA certificate.
One-sentence summary : Support for hybrid RSA/ECC Certificates
Use case for this is to support legacy enterprise applications (only accepting rsa) consuming services  as well as newer clients which can handle ecc.

Similar capabilities have been supported by Nginx in 2016, see [https://github.com/nginx/nginx/commit/cf126b98b30847a453c6f62e0717867cb05098b0](url)
Related Issues  [https://github.com/kubernetes/ingress-nginx/issues/4889](url)
Can Netty implement this capability?

### Actual behavior
I tried 2 ways, but neither of them worked：

1. 

https://github.com/netty/netty/blob/78639fa5ec1da3271dbe79eac28cbf02171c0b73/handler/src/main/java/io/netty/handler/ssl/OpenSslKeyMaterialManager.java#L131-L137

I cannot be get cipher suite in the ClientHello packet of the client  in  `chooseEngineServerAlias` `engine.getHandshakeSession()` . Therefore, the key of the corresponding type cannot be selected.

2. 

https://github.com/netty/netty/blob/78639fa5ec1da3271dbe79eac28cbf02171c0b73/handler/src/main/java/io/netty/handler/ssl/SniHandler.java#L97

The SniHandler selects the corresponding certificate based on the domain name, but not based on the cipher suite.

### Asking for help
How does Netty implement hybrid RSA/ECC Certificates?

### Netty version

4.1.100.Final

### JVM version (e.g. `java -version`)
java8

**Comment by chrisvest** [comment]
Did you build a `KeyStore` with _both_ certificate/key-pairs? (these are _key_ entries with `PrivateKey` objects and certificate chains).

With such a key store, you should be able to `init` a `KeyManagerFactory`, then `SslContextBuilder.forServer(KeyManagerFactory keyManagerFactory)` to get an `SslContext`, and then get an `SSLHandler`.

The cert choosing logic should just work in that case.

**Comment by JimmyBaize** [comment]
Yes. I've found a way
Extend a KeyManager, For example,

```
public class SniKeyManager extends X509ExtendedKeyManager {

        public String chooseEngineServerAlias(String keyType, Principal[] issuers, SSLEngine engine) {
                 engine.getSSLParameters().cipherSuites
        }

}
```
I can get client cipher from `engine.getSSLParameters().cipherSuites`   , and I can find the certificate matching KeyType (EC or RSA) based on the cipher suite.
I'll try it with this idea.
