### ISSUE TITLE
DefaultHttp2Connection.DefaultEndpoint#lastStreamCreated return 0 when the actual stream id is Integer.MAX_VALUE

### ISSUE THREAD

**Issue by DreamLettuce** [netty/netty#13805]
### Expected behavior
when stream id is Integer.MAX_VALUE, `DefaultHttp2Connection.DefaultEndpoint#lastStreamCreated` is expected to return  Integer.MAX_VALUE
<img width="1003" alt="image" src="https://github.com/netty/netty/assets/7601244/3628e299-ace4-43a7-bc72-b3ca51e557ff">

### Actual behavior
1. `DefaultHttp2Connection.DefaultEndpoint#lastStreamCreated` return 0
2. `io.netty.handler.codec.http2.StreamBufferingEncoder#isExistingStream` return false
3. StreamBufferingEncoder write data frame failed
<img width="967" alt="image" src="https://github.com/netty/netty/assets/7601244/a376e976-26c5-4b49-a4cd-3bd86ca6dde2">

4. the further problem is that grpc-java does not handle this write data failure in  [NettyClientStream](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyClientStream.java#L188)  
.this result to the grpc client thread hangs forever is we use grpc blocking stub

### Steps to reproduce
add the following test case to `io.netty.handler.codec.http2.StreamBufferingEncoderTest`
```
    @Test
    public void testExhaustedStreamId() throws Http2Exception {
        int nextStreamId = Integer.MAX_VALUE - 2;
        testStreamId(nextStreamId);
        nextStreamId = connection.local().incrementAndGetNextStreamId();
        testStreamId(nextStreamId);
    }

    private void testStreamId(int nextStreamId) throws Http2Exception {
        connection.local().createStream(nextStreamId, false);
        ByteBuf data = data();
        ChannelFuture channelFuture = encoder.writeData(ctx, nextStreamId, data, 0, false, newPromise());
        if (channelFuture.cause() != null) {
            channelFuture.cause().printStackTrace();
        }
        assertTrue(channelFuture.cause() == null);
    }
```
<img width="1119" alt="image" src="https://github.com/netty/netty/assets/7601244/26e5b344-4341-4b93-a923-279a5be82148">
<img width="1128" alt="image" src="https://github.com/netty/netty/assets/7601244/9d65c584-de09-4c4d-aaf8-9df6ba20251d">

### Netty version
any support http2
 
### JVM version (e.g. `java -version`)
1.8

**Comment by PaulTan94** [comment]
a very critical issue, any suggestion pls？

**Comment by normanmaurer** [comment]
PTAL https://github.com/netty/netty/pull/13807

**Comment by normanmaurer** [comment]
@DreamLettuce you should also report the other issue in GRPC /cc @ejona86

**Comment by DreamLettuce** [comment]
> PTAL #13807

LGTM 👍
