### ISSUE TITLE
HTTP/1.1 decoder + aggregator together don't identify partial responses

### ISSUE THREAD

**Issue by DaveCTurner** [netty/netty#13816]
### Expected behavior

An HTTP/1.1 response using chunked transfer encoding should be terminated with an empty chunk. If the connection closes before receiving the terminating chunk then we should see some kind of failure condition so that the client can distinguish this case from a response that was received in full.

### Actual behavior

A pipeline with a `HttpResponseDecoder` and an `HttpObjectAggregator` will translate this incomplete response into an apparently-successful `FullHttpResponse` if the channel is closed afterwards:

```
HTTP/1.1 200 OK
Transfer-Encoding: chunked

8
12345678
```

### Steps to reproduce

See https://github.com/netty/netty/compare/4.1...DaveCTurner:2024/01/30/incomplete-chunked-response-bug:

```java
@Test
public void testPrematureClosureWithChunkedEncodingAndAggregator() throws Exception {
    EmbeddedChannel ch = new EmbeddedChannel(new HttpResponseDecoder(), new HttpObjectAggregator(1024));

    // Write the partial response.
    ch.writeInbound(Unpooled.copiedBuffer(
            "HTTP/1.1 200 OK\r\nTransfer-Encoding: chunked\r\n\r\n8\r\n12345678", CharsetUtil.US_ASCII));
    ch.finish();

    FullHttpResponse res = ch.readInbound();
    assertThat(res.protocolVersion(), sameInstance(HttpVersion.HTTP_1_1));
    assertThat(res.status(), is(HttpResponseStatus.OK));
    assertTrue(res.decoderResult().isFailure());
    res.release();

    assertThat(ch.readInbound(), is(nullValue()));
}
```

NB I'm not sure if `res.decoderResult().isFailure()` is the right thing to check, but nor can I see another way to distinguish success from failure here.

### Netty version

4.1.94 and 4.1 HEAD (and presumably everywhere in between)

### JVM version (e.g. `java -version`)

Tried with both of the following:

```
$ ~/jvms/jdk-11.0.19+7/Contents/Home/bin/java -version
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment Temurin-11.0.19+7 (build 11.0.19+7)
OpenJDK 64-Bit Server VM Temurin-11.0.19+7 (build 11.0.19+7, mixed mode)
$ ~/jvms/jdk-17.0.7+7/Contents/Home/bin/java -version
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode)
```

### OS version (e.g. `uname -a`)

```
$ uname -a
Darwin Davids-MacBook-Pro.local 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:31:00 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6020 arm64
```

**Comment by DaveCTurner** [comment]
The issue seems to be that we remove the `Transfer-Encoding` header in `HttpObjectAggregator#beginAggregation`:

https://github.com/netty/netty/blob/3ba2eed16a627371839c63113cdb39df9d6bfe35/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectAggregator.java#L207

Then later on we use the existence of that header in `HttpObjectDecoder#decodeLast` to decide how to handle the end-of-stream situation:

https://github.com/netty/netty/blob/78639fa5ec1da3271dbe79eac28cbf02171c0b73/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java#L548

Since it's no longer there, we get `chunked == false`, but also we don't have a `Content-Length` header, so end-of-stream looks like a success condition.

**Comment by normanmaurer** [comment]
@DaveCTurner good catch! Let me fix it

**Comment by normanmaurer** [comment]
@DaveCTurner thanks a lot... PTAL https://github.com/netty/netty/pull/13818

**Comment by DaveCTurner** [comment]
:+1: thanks for the speedy turnaround @normanmaurer. That works for me indeed.
