### ISSUE TITLE
Provide an all-in-one "netty-all-x.x.xxx.Final.jar"

### ISSUE THREAD

**Issue by gregkotsaftis** [netty/netty#13821]
**Please please please** provide an **all-in-one** jar for easy integration with other projects like you did up to version 4.1.68.
My team uses Netbeans with ant.
We do not use maven or gradle cause coding is challenging enough, we do not need to battle with "maven hell" as well.
I tried to make maven work, just to be able to provide others as well with the "precious" netty-all jar, but alas after almost one week of trying, i am left with a PC that needs formating cause maven and gradle hell has infected every sector of my %APPDATA% disk space...
Why someone would invent maven - "tool from hell", to replace Ant, is beyond me.
Maybe I am too old for this maven "shit", the fact is we need netty in a simple all-in-one form to include and distribute with our app.
If anyone else can provide such a jar, pls help some old timers....

**Comment by yawkat** [comment]
have you considered apache ivy? :wink:

**Comment by normanmaurer** [comment]
@gregkotsaftis sorry but no... We run into so much issues with that. People started to have a mix of netty-all plus the other jars on the class path which made things worse. There is nothing that prevent you from just download all the various jars by yourself and put them on the class path

**Comment by gregkotsaftis** [comment]
there is no easy way to download all dependencies even with maven (that we do not use).
at least provide a way to download all JARs and native binary libs for all supported OS in a single ZIP file for each new release!!!

**Comment by gregkotsaftis** [comment]
> have you considered apache ivy? 😉

thanks! will try it. I haven't used Ivy for more than 10 years...
