### ISSUE TITLE
Poor performance when accessing pinnedDirectMemory in high concurrency scenarios

### ISSUE THREAD

**Issue by rickyma** [netty/netty#13860]
We have observed that, under high concurrency scenarios, frequently accessing `pinnedDirectMemory` seems to cause lock contention issues, which leads to poor performance. Is it possible to calculate `pinnedDirectMemory` within Netty's `Allocator` using a more elegant approach, such as `AtomicLong` or something similar? The current bottleneck is in the following code snippet:
```
public long numPinnedBytes() {
    long val = activeBytesHuge.value(); // Huge chunks are exact-sized for the buffers they were allocated to.
    lock();
    try {
        for (int i = 0; i < chunkListMetrics.size(); i++) {
            for (PoolChunkMetric m: chunkListMetrics.get(i)) {
                val += ((PoolChunk<?>) m).pinnedBytes();
            }
        }
    } finally {
        unlock();
    }
    return max(0, val);
}
```

Related to [#11990](https://github.com/netty/netty/pull/11990), [#11667](https://github.com/netty/netty/pull/11667)

### Netty version
netty-4.1.107.Final
### JVM version (e.g. `java -version`)
1.8

**Comment by rickyma** [comment]
PTAL. @chrisvest @normanmaurer

**Comment by franz1981** [comment]
@chrisvest At the same time I see that `LongAdder` can be pretty costy on allocation side as well, see 

![image](https://github.com/netty/netty/assets/13125299/4c5b8775-3c3e-4f70-9c2c-de3162fb398b)

which is just the I/O thread while decrementing the pinned one.
By inspecting the rest of the flamegraph, the increment path, instead, is much less costy, but here's why:
- in the increment path, each allocation is separated by accessing the allocated buffer, doing something with it and other CPU intensive work; this will likely amortize the cost of the `compareAndSet` happening in the `LongAdder`, "padding" each with some other work
- in the decrement path, instead, especially for the outbound buffer `ByteBuf`s, the only job is to release the buffers, placing them into some recycler (if lucky, just an array q offer) in a almost tight loop, and than sending them via `writev`: it means that `LongAdder`s `compareAndSet` are not padded by any useful CPU work, amortizing them way less

This last point lead to the conclusion  that a great benefit could be brought by having the counters like that:
- LongAdder's pinnedBytes, always increasing
- LongAdder's unpinnedBytes, always increasing, used when the chunk is freeing outside of the even loop which is pinned (an information not available ATM)
- AtomicLong unguardedUnpinnedBytes, always increasing and using lazySet to update it, uncontended while performed in the I/O thread it is pinned to

Than the actual number of pinned bytes could be obtained by subtracting these, handling both order and negative outcome in smart way, wdyt @chrisvest do you think we could do something like this?
Sadly I forgot a lot of details of the allocator's threading model, so maybe I'm proposing something unfeasable.

**Comment by rickyma** [comment]
We maintain an `AtomicLong` type `usedMemory` object in the memory of the server-side process, using it to dynamically calculate how much direct memory space the Netty Allocator has allocated on the server side (it will also have other uses, so we can't directly use `pinnedDirectMemory` or `usedDirectMemory`). The calculation method is that we add up the capacity of each `ByteBuf` that comes in from the `channelRead` method. However, when we use `PooledByteBufAllocator`/`UnpooledByteBufAllocator`, we find that the final result of `usedMemory`, as time goes by, will be far from `usedDirectMemory`. Do you know why? Does Netty use such a large amount of extra memory? Is there a way for us to accurately count and add up the memory usage of each `ByteBuf` on the server side? We used to use GRPC-java's heap memory, which can be accurately counted, but now we have switched to using Netty's direct memory, and we can no longer count accurately.

As for your earlier question regarding why I need to frequently obtain `pinnedDirectMemory` at high concurrency, it's because in another scenario, I need to evaluate the availability of server-side memory (`maxDirectMemory` - `pinnedDirectMemory`) in real-time for each incoming client request, in order to successfully allocate memory for the client. If there is currently no available memory, I need to reject the client's request. That's the reason.

Any advice or suggestions you can provide us would be greatly appreciated. Thanks.
@chrisvest

**Comment by rickyma** [comment]
![image](https://github.com/netty/netty/assets/13834479/0751a0ac-fb5e-498a-bf72-5a4eba88229b)
As you can see, the final result of usedMemory, as time goes by, will be far from usedDirectMemory.
The deviation between them is too large, which ultimately leads to inaccurate judgment when allocating memory and consequently results in the occurrence of OOM.

**Comment by rickyma** [comment]
To sum up, there are two questions: 
1. Can we calculate the current memory usage of Netty by adding up the `capacity` of `ByteBuf` in the parameters of the `channelRead` method? 
2. When using `PooledByteBufAllocator`, can we obtain the current available memory through `maxDirectMemory` - `pinnedDirectMemory`? Is there any other better and more performance-efficient way to get the current available memory in real-time?
@chrisvest Thx.

**Comment by laosijikaichele** [comment]
IMHO, we can just remove the `lock()` from the method `PoolArena.numPinnedBytes()`, to reduce lock contention:
```
public long numPinnedBytes() {
    long val = activeBytesHuge.value();
    lock(); // REMOVE THIS LOCK.
    try {
        for (int i = 0; i < chunkListMetrics.size(); i++) {
            for (PoolChunkMetric m: chunkListMetrics.get(i)) {
                val += ((PoolChunk<?>) m).pinnedBytes();
            }
        }
    } finally {
        unlock(); // REMOVE THIS.
    }
    return max(0, val);
}
```
Because the method `PooledByteBufAllocator.pinnedMemory()` does not use any lock to guard the thread safety:
```
    public final long pinnedDirectMemory() {
        return pinnedMemory(directArenas);
    }

    private static long pinnedMemory(PoolArena<?>[] arenas) {
        if (arenas == null) {
            return -1;
        }
        long used = 0;
        for (PoolArena<?> arena : arenas) {
            used += arena.numPinnedBytes(); // NO LOCK for the 'add' operation.
            if (used < 0) {
                return Long.MAX_VALUE;
            }
        }
        return used;
    }
```
As you can see, the loop of `arenas` does not use any lock to guard the 'add' operation's thread safety. 
So I think we can also remove the `lock()` from the method `PoolArena.numPinnedBytes()`, to reduce lock contention

**Comment by normanmaurer** [comment]
This was done by @vietj
