### ISSUE TITLE
Possible incorrect license for zstd-jni

### ISSUE THREAD

**Issue by kswartz26** [netty/netty#13862]
The NOTICE file mentions an optional dependency on zstd-jni.txt, and references LICENSES/zstd-jni.txt . This file includes a copy of the Apache license. However, the NOTICE file points to the original project at https://github.com/luben/zstd-jni and the license there is NOT Apache, but BSD 2-clause (along with a downstream dependency on zstd under BSD or GPL v2.) This is also stated at the bottom of the README file.

Is this a mistake, or did the owner of this project agree to relicense under an Apache license for netty?

**Comment by hyperxpro** [comment]
This is a mistake

**Comment by normanmaurer** [comment]
Fixing it...
