### ISSUE TITLE
Allow looking up DNS servers, even if JNDI is disabled

### ISSUE THREAD

**Issue by snazy** [netty/netty#13883]
Context is [this Quarkus issue](https://github.com/quarkusio/quarkus/issues/23519), TL;DR Quarkus disables JNDI by default (can't use an `(Initial)Context(Factory)` [at all](https://github.com/quarkusio/quarkus/blob/2fa75a15e9b5c73990a7ca01ca2678161c0d3e3d/independent-projects/bootstrap/runner/src/main/java/io/quarkus/bootstrap/naming/DisabledInitialContext.java)), but that breaks the (default) DNS servers lookup in [DirContextUtils](https://github.com/netty/netty/blob/85cee9d1a8881a93e7c43a02baefea75b6ade2b5/resolver-dns/src/main/java/io/netty/resolver/dns/DirContextUtils.java), so DNS lookups default to the public Google DNS servers. This means, that looking up k8s service names isn't possible without either enabling JNDI, which is not such a great option, or specifying DNS servers manually (oh my).

Naively, one could instantiate `com.sun.jndi.dns.DnsContextFactory`, but nah - JPMS gets in the way there (which is fine IMO).

OTOH `sun.net.dns.ResolverConfigurationImpl` doesn't do anything else than reading `/etc/resolv.conf` (at least on Linux + macOS).

WDYT about adding a fallback to `DirContextUtils` that if the lookup of the DNS servers via JNDI fails, it reads `/etc/resolv.conf` directly? Doesn't feel to be a huge ton of work, can contribute a PR for that.

/cc @geoand @cescoffier

**Comment by normanmaurer** [comment]
@snazy soubds good ... unfortunately this only works for non windows tho
