### ISSUE TITLE
proxy-authorization header is not propagated to proxy server

### ISSUE THREAD

**Issue by SushmaPradeep** [netty/netty#13892]
HttpClient client = HttpClient.create()
				          .proxy(spec -> spec.type(ProxyProvider.Proxy.HTTP)
				                             .host("proxy")
				                             .port(8080)
                                                              .username("username")
                                                              .password(s-> "pwd"));

### Expected behavior

when I set proxy with username and password, HttpProxyHandler is setting 'proxy-authorization' header. The request needs to carry this header as part of the request to proxy server.

### Actual behavior

Even though the header is available in HttpProxyHandler, that is not propagated to proxy server.

### Steps to reproduce

Create HttpClient and set up proxy and hit request.

**Comment by normanmaurer** [comment]
I guess this might be reactor issue... @violetagg wdyt ?

**Comment by violetagg** [comment]
let me take a look

**Comment by SushmaPradeep** [comment]
Thanks for the response. 

Also, I need to avoid roundtrips (407 & 401 errors). To do so in apache there is a concept of PreemptiveAuthentication. Is there any similar concept to this in netty? If yes, could you please help me in configuring the same.

**Comment by violetagg** [comment]
@SushmaPradeep I am seeing that a request like this is sent.

```
17:23:58.216 [reactor-http-nio-1] DEBUG reactor.netty.proxy - [fd907a4e, L:/127.0.0.1:56744 - R:localhost/127.0.0.1:3128] WRITE, DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: EmptyByteBufBE)
CONNECT example.com:443 HTTP/1.1
host: example.com:443
proxy-authorization: Basic <filter>
```

Can you please elaborate more on the issue? Can you provide either logs or tcp dump?

**Comment by violetagg** [comment]
Let me close this issue. I will keep the issue https://github.com/reactor/reactor-netty/issues/3085 opened for a while, however I do not see any problems with the functionality.
