### ISSUE TITLE
Netty client will report an error when connecting to the server through a domain name

### ISSUE THREAD

**Issue by yx928** [netty/netty#13920]
### Netty version
4.1.79.Final
### JVM version (e.g. `java -version`)
jdk8
![微信图片_20240322103042](https://github.com/netty/netty/assets/46622316/2444b4a0-dc9c-4e29-af42-69d583e08fa0)
![微信图片_20240322103055](https://github.com/netty/netty/assets/46622316/e7062339-58e7-4396-a7ac-7ba6a49601e6)

**Comment by normanmaurer** [comment]
This is expected... strip the `http://` from the hostname
