### ISSUE TITLE
Reduce memory footprint of Recyclers 

### ISSUE THREAD

**Issue by franz1981** [netty/netty#13945]
Currently Recycler(s) uses mpsc queues from JCTools, which:
- could not be used at all and just relies on the local array queue (it is what happen if the chunk size capacity is good enough - which is 32 by default (see https://github.com/netty/netty/blob/fee3c39d0835ec18d7aace8776db5c5952ce8272/common/src/main/java/io/netty/util/Recycler.java#L315)
- being allocated using padded variant of JCTools

I believe things could be improved by both making the allocations of such queues lazy AND using atomic unpadded or unpadded unsafe variant, while allocated.

We just need a new release of JCTools (from the dear @nitsanw) in order to have both the unpadded flavours in (if unsafe isn't present).

**Comment by nitsanw** [comment]
Will get to it next week

**Comment by franz1981** [comment]
If I can help and learn how to roll the release I will, Nitsan, just pong me on Gmail/github

**Comment by lhotari** [comment]
jctools was upgraded to 4.0.5 in #14096

**Comment by slandelle** [comment]
Isn't this ticket a duplicate of #12496?

**Comment by franz1981** [comment]
@slandelle nope, as recyclers cab be highly contended (on release? which is an offer) if the users emply worker threads.
I'll close this since I cannot see evidences in heap dump that show that this matter, really.
Feel free to reopen if you feel is worthy
