### ISSUE TITLE
Netty Event Group Metrics

### ISSUE THREAD

**Issue by saivikas-dharma** [netty/netty#13966]
Hi, 

Is there a way to get the list of Pending tasks in EpollEventLoop Group ? 

Few requesting are taking long time to process periodically and analyzing thread dump shows no threads are in blocked state.. 

The EpollEventLoop group is part of server that implements Long poll and handle close to 800K active connections. 

Is incoming connections assigned to event loop threads on Round Robin Fashion or they are assigned based on runtime metrics of the event loop thread like pending tasks to complete

**Comment by normanmaurer** [comment]
@saivikas-dharma its done by round-robin by default but you can implement your own logic by implementing your `EventExecutorChooser`.
