### ISSUE TITLE
Add the parameter releaseOnClose to ByteBufOutputStream

### ISSUE THREAD

**Issue by finefuture** [netty/netty#13985]
### Expected behavior
Add parameter releaseOnClose to ByteBufOutputStream, consistent with ByteBufInputStream.

### Actual behavior
Currently inconsistent

### Steps to reproduce
Netty provides a adaptor from ByteBuf to Java's OutputStream interface.  The JDK Stream interfaces have an explicit lifetime because they implement the Closable interface.  This lifetime may be differnt than the ByteBuf which is wrapped, and controlled by the interface which accepts the JDK Stream.  However Netty's ByteBufOutputStream currently does not take reference count ownership of the underlying ByteBuf.  There may be no way for existing classes which only accept the OutputStream interface to communicate when they are done with the stream, other than calling close().  This means that when the stream is closed it may be appropriate to release the underlying ByteBuf, as the ownership of the underlying ByteBuf resource may be transferred to the Java Stream.

### Netty version
4.1.108.Final

### JVM version (e.g. `java -version`)
11

**Comment by finefuture** [comment]
> @finefuture we are happy to review a PR :)

Please review this PR: #13986 , thank you

**Comment by chrisvest** [comment]
PR got merged. Closing.
