### ISSUE TITLE
ZSTD decompression not resilient to compression bombs

### ISSUE THREAD

**Issue by pe-bernard** [netty/netty#14004]
In the latest version (`4.1.109.Final`) of Netty, I've encountered a significant performance issue related to sending compression bombs. Specifically, when utilizing Zstandard (zstd) compression, sending compression bombs results in a notable increase in direct memory consumption, ultimately leading to memory exhaustion and application instability. Interestingly, this behavior is not observed when employing gzip compression for compression bombs.

This is happening while using Netty `HTTPContentDecompressor` and `HttpObjectAggregator` with a max content size of 5 MiB. I expect memory consumption to be bound, but this is not what I actually observe.

### Expected behavior

Sending compression bombs should not excessively consume direct memory, maintaining stability and performance within acceptable bounds.

### Actual behavior

Direct memory usage spikes significantly when utilizing Zstandard compression for compression bombs, leading to potential memory exhaustion and application instability.

When sending compression bombs, one by one, with individual uncompressed size fitting into memory, it leads to direct memory exhaustion when using zstd. No issue is detected when gzip is used.

1. Sending gzip bombs works fine

1000 requests sent, 1000 `413 Request Entity Too Large` responses received.

2. Sending zstd bombs leads to fast exhaustion and OOM crash

After a few requests sent, server is crashing. Receiving a mix of `413 Request Entity Too Large` and `400 Bad Request` because of `DecompressionException`.

3. Sending smaller zstd bombs leads to fast exhaustion and OOM crash

After a few 10s requests sent, server is crashing. Receiving a mix of `413 Request Entity Too Large` and `400 Bad Request` because of `DecompressionException`.

```
io.netty.handler.codec.compression.DecompressionException: com.github.luben.zstd.ZstdIOException: Unknown frame descriptor
	at io.netty.handler.codec.compression.ZstdDecoder$ZstdStream.decompress(ZstdDecoder.java:172)
	at io.netty.handler.codec.compression.ZstdDecoder.decode(ZstdDecoder.java:75)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:344)
	at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:264)
	at io.netty.handler.codec.http.HttpContentDecoder.decodeContent(HttpContentDecoder.java:171)
	at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:160)
	at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:47)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
....
```

![netty_issue](https://github.com/netty/netty/assets/1727298/dc8b0fd2-c9b2-444e-8f21-b873145e77e9)

### Steps to reproduce

1. Send compression bombs using Zstandard compression in a Netty server having at least one `HTTPContentDecompressor`
and one `HttpObjectAggregator`.
2. Monitor direct memory consumption during the process.

### Minimal yet complete reproducer code (or URL to code)

1. Prepare the payload, uncompressed size > max content size in the aggregator

```sh
head -c 200M </dev/zero >bomb200.bin
head -c 50M </dev/zero >bomb50.bin
gzip --keep bomb200.bin
zstd bomb200.bin
zstd bomb50.bin
```
which gives the following files:

```
200M Apr 26 14:29 bomb200M.bin
200K Apr 26 14:29 bomb200M.bin.gz
6.5K Apr 26 14:29 bomb200M.bin.zst
1.7K Apr 26 14:38 bomb50M.bin.zst
```

2. Send payload using gzip content-encoding, one by one

```sh
repeat 1000 { curl -X POST -H "Content-Type: application/json" -H "Content-Encoding: gzip" --data-binary @bomb200M.bin.gz localhost:1234 }
```

3. Send payload using zstd content-encoding, one by one

```sh
repeat 1000 { curl -X POST -H "Content-Type: application/json" -H "Content-Encoding: zstd" --data-binary @bomb200M.bin.zst localhost:1234 }
```

### Netty and zstd-jni versions

`4.1.109.Final` with zstd-jni `1.5.6-3` (also tested with `1.5.5-2`)

### JVM version (e.g. `java -version`)

```sh
java -version
openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Zulu21.32+17-CA (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Zulu21.32+17-CA (build 21.0.2+13-LTS, mixed mode, sharing)
```

Relevant JVM arguments: `-Dio.netty.maxDirectMemory=0 -XX:MaxDirectMemorySize=744M -XX:+CrashOnOutOfMemoryError`

### OS version (e.g. `uname -a`)

```
uname -a
Linux 5.15.0-1058-gcp x86_64 GNU/Linux
```

**Comment by trazfr** [comment]
👋 Hello,

I have a small reproducer for this issue.
Please find it attached. It can run on docker.
The issue triggers with a real netty application, but it does not trigger in the unit tests using the `EmbeddedChannel`.

[test_netty_decompressor.tar.gz](https://github.com/netty/netty/files/15332088/test_netty_decompressor.tar.gz)

Steps:

```bash
# start the server using openjdk 18
$ ./run_docker_app.sh maven:3-openjdk-18
+ docker run -it --rm -v .../test_netty_decompressor:/usr/src/mymaven -v .../tmp/m2:/root/.m2 -w /usr/src/mymaven -p 4212:4212 -e 'MAVEN_OPTS=-Xmx128m -Xms64m' maven:3-openjdk-18 mvn exec:java -Dexec.mainClass=test_netty.App
...
Server listening on /0.0.0.0:4212
```

Send the 200MiB request:

```bash
$ dd if=/dev/zero bs=1024 count=$((200 * 1024)) status=none | zstd >| payload.zstd
$ curl -si -XPOST -H 'content-type: application/octet-stream' -H 'content-encoding: zstd' --data-binary '@payload.zstd' 127.0.0.1:4212
HTTP/1.1 500 Internal Server Error
content-type: text/plain
content-length: 4961
connection: close

java.lang.OutOfMemoryError: Cannot reserve 4194304 bytes of direct buffer memory (allocated: 130031625, limit: 134217728)
	at java.base/java.nio.Bits.reserveMemory(Bits.java:178)
	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118)
	at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:332)
```

As a comparison, gzip has no issue:

```bash
$ dd if=/dev/zero bs=1024 count=$((200 * 1024)) status=none | gzip >| payload.gzip
$ curl -si -XPOST -H 'content-type: application/octet-stream' -H 'content-encoding: gzip' --data-binary '@payload.gzip' 127.0.0.1:4212
HTTP/1.1 413 Request Entity Too Large
content-length: 0
connection: close
```

The channel setup in the app is very minimalistic:

```java
                    socketChannel
                        .pipeline()
                        .addLast(new HttpServerCodec())           // netty http codec
                        .addLast(new HttpContentDecompressor())   // netty decompressor
                        .addLast(new HttpObjectAggregator(_5_MB)) // aggregator with a 5MiB limit
                        .addLast(httpHandler)                     // custom handler to craft a simple response
                        .addLast(exceptionHandler);               // on exception, send a 500 response with the stack trace
```

System running docker:

```bash
$ uname -a
Linux colima 6.5.0-15-generic #15-Ubuntu SMP PREEMPT_DYNAMIC Tue Jan  9 22:39:36 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

$ docker run -ti --rm maven:3-openjdk-18 java -version
openjdk version "18.0.2.1" 2022-08-18
OpenJDK Runtime Environment (build 18.0.2.1+1-1)
OpenJDK 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)
```

Versions:

```xml
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-all</artifactId>
      <version>4.1.109.Final</version>
    </dependency>

    <dependency>
      <groupId>com.github.luben</groupId>
      <artifactId>zstd-jni</artifactId>


      <version>1.5.5-11</version> <!-- also broken with 1.5.6-3 -->
    </dependency>
```

Regards,
Alexandre

**Comment by trazfr** [comment]
cc @normanmaurer as you worked on this PR https://github.com/netty/netty/pull/13928 to enhance the zstd decoder.

**Comment by normanmaurer** [comment]
will check

**Comment by normanmaurer** [comment]
I am looking into it atm.. There is something strange going on.

**Comment by normanmaurer** [comment]
@trazfr @pe-bernard unfortunately the only fix I can think of atm is to revert my PR https://github.com/netty/netty/pull/14084 :(

**Comment by pe-bernard** [comment]
Thanks for looking into it!
