### ISSUE TITLE
[discuss] update slf4j to 2.x in 4.2 branch

### ISSUE THREAD

**Issue by shoothzj** [netty/netty#14011]
Slf4j 1.7 has not been maintained for almost 2 years. Shall we update slf4j to 2.x in 4.2 branch? I am willing to send a PR. :)

@normanmaurer @chrisvest

**Comment by shoothzj** [comment]
ping @normanmaurer @chrisvest

**Comment by normanmaurer** [comment]
@shoothzj is slf4j 2.x api compatible with slf4j 1.x ? or does it use different package names ?

**Comment by slandelle** [comment]
@normanmaurer Yes it is. The "only" issue is that users have to upgrade their implementation (eg logback) as well.

**Comment by shoothzj** [comment]
@normanmaurer Yes, It's compatible. And I have update in other project. https://github.com/apache/bookkeeper/pull/4248

> Log4j just update minor version. Logging configuration files don't need to change.

> SLF4J API version 2.0.0 requires Java 8 and introduces a backward-compatible fluent logging API. By backward-compatible, we mean that existing logging frameworks do not have to be changed in order for the user to benefit from the fluent logging API.

**Comment by normanmaurer** [comment]
I think that's fine... please send over a PR :)
