### ISSUE TITLE
Epoll: Ability to get amount of sent segments

### ISSUE THREAD

**Issue by dries-c** [netty/netty#14022]
### Expected behavior
To calculate the packet loss percentage, it would be possible to do tcpi_lost * 100 / tcpi_data_segs_out. 
Sadly, tcpi_data_segs_out is required to get the amount of sent segments, which is not exposed.

Adding it directly might not work either, because not all Linux versions support it.

**Comment by chrisvest** [comment]
In other words, you want to be able to query `tcp_info` from `getsocketopt`?

**Comment by dries-c** [comment]
A mechanism to do this already exists, it's just lacking some fields

**Comment by dries-c** [comment]
Closed due to glibc not providing an up to date struct.
