### ISSUE TITLE
Recent mvn install fails for io.netty:netty-resolver-dns-native-macos:zip:native-src:4.1.110.Final-SNAPSHOT 

### ISSUE THREAD

**Issue by snehanie** [netty/netty#14037]
### Expected behavior
In https://oss.sonatype.org i dont see  io.netty:netty-resolver-dns-native-macos:zip:native-src:4.1.110.Final-SNAPSHOT. May be this is the reason for failure. Whether 4.1.110 snapshot of netty-resolver-dns-native-macos is not uploaded yet?

### Actual behavior
[INFO] --- hawtjni:1.18:build (build-native-lib) @ netty-resolver-dns-native-macos ---
Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/io/netty/netty-resolver-dns-native-macos/4.1.110.Final-SNAPSHOT/maven-metadata.xml
Downloaded from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/io/netty/netty-resolver-dns-native-macos/4.1.110.Final-SNAPSHOT/maven-metadata.xml (1.3 kB at 26 kB/s)
Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/io/netty/netty-resolver-dns-native-macos/4.1.110.Final-SNAPSHOT/netty-resolver-dns-native-macos-4.1.110.Final-SNAPSHOT-native-src.zip
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.595 s
[INFO] Finished at: 2024-05-06T15:09:14-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fusesource.hawtjni:hawtjni-maven-plugin:1.18:build (build-native-lib) on project netty-resolver-dns-native-macos: build failed: org.apache.maven.plugin.MojoExecutionException: Requested download does not exist.: The following artifacts could not be resolved: io.netty:netty-resolver-dns-native-macos:zip:native-src:4.1.110.Final-SNAPSHOT (absent): Could not find artifact io.netty:netty-resolver-dns-native-macos:zip:native-src:4.1.110.Final-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots)
[ERROR] 

### Steps to reproduce
Pull in the latest netty code and cd to the directory
mvn -U clean install -DskipTests

### Netty version
4.1.110

### JVM version (e.g. `java -version`)
Not Applicable

### OS version (e.g. `uname -a`)
Not Applicable

**Comment by ttomaszewski** [comment]
We are seeing a similar issue with a different version
```
4.1.107.Final/netty-resolver-dns-native-macos-4.1.107.Final-jakarta.jar not found
```

**Comment by chrisvest** [comment]
The zip artifact should come from the local build, not the public repos. Try running maven with the `./mvnw` script, to make sure you use the same maven version as our builds.

We don't produce any `-jakarta` suffixed artifacts, so that must be coming from somewhere else.

**Comment by normanmaurer** [comment]
Most likely you have some tools missing that are needed to compile the native libs. Please show the full build log
