### ISSUE TITLE
netty5-codec-http2 has unexpected (wrong?) Automatic-Module-Name: io.netty.codec.http2

### ISSUE THREAD

**Issue by Stewori** [netty/netty#14060]
With this issue I just want to make you aware that netty5-codec-http2 is distributed with a non-netty5 automatic module name on maven central. See this file: https://repo1.maven.org/maven2/io/netty/netty5-codec-http2/5.0.0.Alpha5/netty5-codec-http2-5.0.0.Alpha5.jar
Therein, in MANIFEST.MF you can check the Automatic-Module-Name entry.

I believe the correct value should be `io.netty5.codec.http2`.
The other netty5 modules are correct (as far as I checked), it's only in codec-http2.

Please excuse if this should be a duplicate; I did a quick seach but may have overlooked it.

**Comment by Stewori** [comment]
Also see https://netty.io/5.0/api/index.html, where `io.netty.codec.http2` clearly violates the usual module naming pattern of `io.netty5.*`.

**Comment by chrisvest** [comment]
I don't know what happened, but it looks like both are fixed in the `main` branch.

**Comment by Stewori** [comment]
Okay, thank you. Do you have some rough idea when Alpha6 will be released?

**Comment by normanmaurer** [comment]
Not at the moment
