### ISSUE TITLE
En/Decode cookies with RFC6265

### ISSUE THREAD

**Issue by slandelle** [netty/netty#1406]
Hi,

Let's say the server returns a Set-Cookie header:

`canalnet=Apv3FQl3fsWZskAZda1GN0rN9BJiTbujoi7Puq/Iq37rUQrJirrnAPOTHZo2aKlpyzWbdaH1MjKyV6s=;domain=bnpparibas.net; path=/`

Then, having CookieDecoder.decode and CookieEncoder(false).encode produces:

`canalnet="Apv3FQl3fsWZskAZda1GN0rN9BJiTbujoi7Puq/Iq37rUQrJirrnAPOTHZo2aKlpyzWbdaH1MjKyV6s="; $Path="/"; $Domain=bnpparibas.net`

which is Version 1 minus the Version attribute.

According to [Netscape draft](http://curl.haxx.se/rfc/cookie_spec.html), I would expect `canalnet=Apv3FQl3fsWZskAZda1GN0rN9BJiTbujoi7Puq/Iq37rUQrJirrnAPOTHZo2aKlpyzWbdaH1MjKyV6s=` (no double quotes, no path, no domain)

This causes non Version 1 compliant components, such as F5 BigIP, to fail parsing the Cookie header.

If you're OK with this, I can easily provide a PR.

Regards,

Stéphane

**Comment by slandelle** [comment]
@trustin I guess this issue can now be closed as commit was cherry-picked to 4.1 and master.

**Comment by trustin** [comment]
Doing some final touches right now.

**Comment by slandelle** [comment]
OK, thanks!

**Comment by trustin** [comment]
@slandelle I have a few questions/ideas:

- It looks to me `Rfc6265Client/ServerCookieEncoder` can be a drop-in (or better) replacement of the old `Client/ServerCookieEncoder`. Correct? If so, I think we can simply remove the old encoders and remove the `Rfc6265` prefix.
- Similarly, we can remove the `Rfc6265` prefix for the decoders because we don't have name clash here.
- Would it be a good idea to port this pull request and the changes I proposed in this comment to 4.0 sans the `rawValue` part?

**Comment by slandelle** [comment]
> It looks to me Rfc6265Client/ServerCookieEncoder can be a drop-in (or better) replacement of the old Client/ServerCookieEncoder. Correct? If so, I think we can simply remove the old encoders and remove the Rfc6265 prefix.
Similarly, we can remove the Rfc6265 prefix for the decoders because we don't have name clash here.

Absolutely. I forked instead of replacing in order to not break compatibility and left the decision of such a move to you.

> Would it be a good idea to port this pull request and the changes I proposed in this comment to 4.0 sans the rawValue part?

I'm not sure. People using the existing set would experience behavior changes in a fix version. For example, existing code relying on encoders returning null might break now that they return empty collections.

**Comment by slandelle** [comment]
BTW, once you're done, I'd gladly fix #1466 :)

**Comment by trustin** [comment]
@slandelle One last question - it seems like the `first` local variable in `Rfc6265ClientCookieDecoder.decode()` is not really used at all.  When it is set to false, it always breaks out of the outer loop, and thus nobody will see the case where `first` is `false`.  Is it just a cruft I can clean up, or did you have something in your mind?

**Comment by slandelle** [comment]
What have I done? It seems `boolean first = true;` should be defined outside the outer loop.
Let me check.

**Comment by trustin** [comment]
If you are going to push another commit, then you'd better start your branch from scratch because your work has been cherry-picked and the classes have been renamed as I proposed. Let me check back tomorrow morning.

**Comment by slandelle** [comment]
OK

**Comment by slandelle** [comment]
I checked, and yes, it's no longer used and can be dropped, sorry for this.

**Comment by slandelle** [comment]
Done in #3340

**Comment by slandelle** [comment]
Someone forgot to close this :)
