### ISSUE TITLE
ByteBuf.asReadOnly() derived buffer doesn't support parent.release on deallocation which makes it unsuitable for ctx.write

### ISSUE THREAD

**Issue by lhotari** [netty/netty#14075]
### Expected behavior

It should be possible to share the reference count ownership to the read-only wrapper returned by `.asReadOnly()` in a similar way as `.duplicate()` behaves.

The behavior is well explained in a comment in AbstractPooledDerivedByteBuf:
https://github.com/netty/netty/blob/5085cef149134951c94a02a743ed70025c8cdad4/buffer/src/main/java/io/netty/buffer/AbstractPooledDerivedByteBuf.java#L32-L37

Without this support, it makes `.asReadOnly()` buffers unsuitable for use in writing to a channel pipeline where the reference count is decreased after the write completes. This would be needed for the use case explained in #14069 where it would be desired to write a shared ByteBuf instance to multiple clients that use TLS connections. One of the solution proposals would be to make the ByteBuf a read-only buffer so that SslHandler knows to avoid mutating the buffer.

### Actual behavior

The read-only wrapper doesn't call parent.release on deallocation. This makes it unsuitable for ctx.write calls where the reference count is decremented after the writing completes and this propagates to the parent buffer.

### Netty version

4.1.108

**Comment by normanmaurer** [comment]
You are right... will fix

**Comment by normanmaurer** [comment]
@lhotari PTAL https://github.com/netty/netty/pull/14076
