### ISSUE TITLE
Ask for Java 21 support for io.netty : netty-all

### ISSUE THREAD

**Issue by Swarn10** [netty/netty#14089]
### If there are plans already to support Java 21, is there an ETA for the same?

**Comment by lhotari** [comment]
Netty works well on Java 21. For example in apache/pulsar we use Netty extensively and also run scheduled builds in CI. There aren't any compatibility issues.

**Comment by chrisvest** [comment]
Yeah, we've been running Java 21 builds since it came out. It's not a problem.
