### ISSUE TITLE
Netty HttpClient failed to connect with SSLHandshakeException after establishing HTTPS connection with endpoint

### ISSUE THREAD

**Issue by deepak-chhetri** [netty/netty#14087]
We have built API Gateway application using Spring Cloud Gateway 4.0 (on webflux) framework and Azul Zulu OpendJDK 17. The application is able to intercept incoming request and redirect it to the configured downstream HTTPS endpoint using TLS certificate.
However, there is one request in which the gateway app unable to establish HTTPS connection with configured downstream endpoint and getting below SSL Handshake error (soon after connection and active channel):
```
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
```   
We have configured the TLS certificate for routing request to endpoint in following property which is passed as JVM_ARGS in java command line:
```
javax.net.ssl.trustStore=<path to .pkcs12 keystore>
```
We enabled more granular logs from Netty library by setting reactor.netty=DEBUG level and found below lines after above exception:
```
HttpServerOperations | [d7cffb05-1, L:/<Source IP:Port> - R:/<Destination IP:Port>] Detected non persistent http connection, preparing to close
HttpServerOperations | [d7cffb05-1, L:/<Source IP:Port> - R:/<Destination IP:Port>] Last HTTP response frame
HttpServerOperations | [d7cffb05-1, L:/<Source IP:Port> - R:/<Destination IP:Port>] Last HTTP packet was sent, terminating the channel
```
However, Netflix Zuul Gateway application (running on same server in which Spring Cloud Gateway app is running) is able to connect with the same HTTPS endpoint and redirect the request to it successfully using same TLS certificate.
Note:** Netflix Zuul is using RestTemplate to connect whereas Spring Cloud Gateway is using Netty HttpClient.**

We have tried many combination with different properties however still stuck with same error.
How can we resolve this SSL handshake failure soon after connection is established?
Any help is highly appreciated in this direction.
### Netty version
4.1.101.Final

### JVM version (e.g. `java -version`)
Azul Zulu OpenJDK 17

### OS version (e.g. `uname -a`)
RHEL 7.9 (Maipo)

**Comment by lhotari** [comment]
> We have tried many combination with different properties however still stuck with same error. How can we resolve this SSL handshake failure soon after connection is established? Any help is highly appreciated in this direction.

Have you already tried pinning TLS protocol version to TLSv1.2 ? TLSv1.3 handshakes behave slightly differently and could cause compatibility issues in some applications that aren't prepared for it. What is the exact version of Spring Cloud Gateway? Have you tried upgrading it?

**Comment by deepak-chhetri** [comment]
@lhotari Thanks for checking and sharing the possible pointers.
**Spring Cloud Gateway version: 4.1.0**
The latest version is 4.1.4 which seems to be minor update so we did not upgraded.
We tried with pinning down to TLSv1.2 by setting spring boot properties as follows, however the SSL Handshake error still exists.
```
server:
  ssl:
   enable: true
   protocol: TLS
   enabled-protocols: TLSv1.2
```
Then we tried to figure out the cipher suite used by remote server by using following command as suggested in https://stackoverflow.com/a/48602234 article:
```
openssl s_client -connect serverAddress:port
```
and got following output with cipher details:
```
SSL-Session:
    Protocol: TLSv1.2
    Cipher: AES256-SHA256
    Verify return code: 0 (ok)
```
We tried to configure the listed cipher suite in suggested spring boot property as follows, however then all request started failing with 502 BAD Gateway status/error:
```
server:
  ssl:
   enable: true
   protocol: TLS
   ciphers: AES256-SHA256
   enabled-protocols: TLSv1.2
```
We gone through the TLS/SSL section of official documentation of Spring Cloud Gateway and found out that above properties are used to accept HTTPS connection from client by Spring Cloud Gateway server application, however **spring.cloud.gateway.httpclient.ssl.trustedX509Certificates** property is used for establishing HTTPS connection by Spring Cloud Gateway app as client with remote endpoint server.
Is there anything else we are missing in the configuration that is resulting in SSL Handshake failure?

**Comment by lhotari** [comment]
I think it's better to continue this discussion in spring-cloud/spring-cloud-gateway#3414 since this isn't a Netty problem. It's a configuration problem. After reading your problem description once again, I now understood that the problem is in the Http client configuration of Spring Cloud Gateway and it's not a problem in the server configuration of Spring Cloud Gateway. You will need to configure the ciphers for the http client to address the problem. Please ask on the spring-cloud-gateway issue how to achieve this.
