### ISSUE TITLE
HashedWheelTimer doesn't obey contract of `Timer#stop()`

### ISSUE THREAD

**Issue by jbewing** [netty/netty#14081]
### Expected behavior

That calls to HashedWheelTimer.stop() will cancels all tasks which were scheduled but not executed yet as the [API docs of Timer indicate](https://github.com/netty/netty/blob/d7e2de108bc06a563ed2828b4ef83a22fc0094a0/common/src/main/java/io/netty/util/Timer.java#L40-L47).
```java
    /**
     * Releases all resources acquired by this {@link Timer} and cancels all
     * tasks which were scheduled but not executed yet.
     *
     * @return the handles associated with the tasks which were canceled by
     *         this method
     */
    Set<Timeout> stop();
```

### Actual behavior

Calls to HashedWheelTimer.stop() return tasks that are scheduled but not yet executed yet, but doesn't cancel them

### Steps to reproduce

The following unit test which I've added to HashedWheelTimerTest fails (excuse the use of Java 1.8+ language features, just want to illustrate problem w/out being too verbose):
```java
@Test
@org.junit.jupiter.api.Timeout(value = 3000, unit = TimeUnit.MILLISECONDS)
public void testStopTimerCancelsPendingTasks() throws InterruptedException {
    final Timer timerUnprocessed = new HashedWheelTimer();
    for (int i = 0; i < 5; i ++) {
        timerUnprocessed.newTimeout(new TimerTask() {
            @Override
            public void run(Timeout timeout) throws Exception {
            }
        }, 5, TimeUnit.SECONDS);
    }
    Thread.sleep(1000L); // sleep for a second

    assertTrue(timerUnprocessed.stop().stream().allMatch(Timeout::isCancelled),
        "All unprocessed tasks should be canceled");
}
```

### Minimal yet complete reproducer code (or URL to code)

See above

### Netty version

This test fails on the latest master branch, but I noticed it when running Netty 4.1.108

### JVM version (e.g. `java -version`)

N/A

### OS version (e.g. `uname -a`)

N/A

**Comment by normanmaurer** [comment]
@jbewing thanks for reporting: https://github.com/netty/netty/pull/14083
