### ISSUE TITLE
Internal state of HttpObjectDecoder is not reset when connection pooling is used

### ISSUE THREAD

**Issue by Airidas36** [netty/netty#14105]
I have a simple Spring Cloud Gateway application setup, which reroutes all of the calls to a specific URL and appends
some specific Authorization headers to the outgoing call. I've stumbled upon a weird HTTP client behavior when connection pooling is used:

### Expected behavior
I expect that the same remote sever response will be handled the same way for every request when connection pooling is used.

### Actual behavior
1. Call the gateway application through Postman client
2. Request gets rerouted to the configured server by the gateway application
3. HTTP 204 No Content is returned by the remote server
4. Gateway application successfully returns the response to the Postman client
5. Call the gateway application through Postman for the second time with the exact same request
6. Request is rerouted
7. HTTP 204 No Content is returned by the remote server
8. Gateway application is stuck until remote server sends RST/FIN flag and connection is closed (~4 minutes)
9. Gateway application raises `Connection prematurely closed BEFORE response` error.
### Steps to reproduce

In other words, every 2nd request is stuck and connection gets reset by the remote server after some timeout.
Upon further investigation why is this happening I inspected the network traffic using Wireshark and managed to decrypt the TLS traffic. It looks like some additional HTTP "Continuation" packets are being sent by the server after serving the HTTP 204 response.
The packets themselves do not contain HTTP version, therefore message creation fails in the `decode(..)` method, since `HttpRequestDecoder` raises an exception when `HttpVersion.valueOf(initialLine[2])` is called. This falls into an `catch` block which invokes the `invalidMessage` method and sets the `currentState` of `HttpDecoder` to `State.BAD_MESSAGE`. Regardless of that the first request and response is somehow still handled by the gateway application and response is successfully returned to the Postman client. Upon second request, `HttpDecoder` still has the previous `currentState` as `State.BAD_MESSAGE` and fails to decode the very first HTTP packet with the 204 response since it fall through the `switch` case in the `decode` method.

All of this can be avoided if connection pooling is disabled, and for every request a new connection is made, this results in `HttpDecoder` always starting in `currentState = State.SKIP_CONTROL_CHARS` and being able to decode the response.
### Minimal yet complete reproducer code (or URL to code)
Unfortunately I'm unable to provide a reproducible example since this issue is present only when these HTTP "Continuation" packets are present.
![wireshark_sc](https://github.com/netty/netty/assets/50202461/12456871-e077-4c47-925e-8ab64f507e43)

### Netty version
* Reactor Netty `1.1.16` with Netty `4.1.107.Final`
### JVM version (e.g. `java -version`)
* openjdk version `"17.0.5" 2022-10-18 LTS`
* OpenJDK Runtime Environment Corretto-`17.0.5.8.1 (build 17.0.5+8-LTS)`
* OpenJDK 64-Bit Server VM Corretto-`17.0.5.8.1 (build 17.0.5+8-LTS, mixed mode, sharing)`

### OS version (e.g. `uname -a`)
* Local - Windows 10 Enterprise `21H2 19044.4412` as well `RHEL9 5.14.0-284.57.1.el9_2.x86_64` in OpenShift

**Comment by violetagg** [comment]
@Airidas36 You already reported this issue in Reactor Netty and I think that it should be investigated there.
