### ISSUE TITLE
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: -1

### ISSUE THREAD

**Issue by Type-32** [netty/netty#14104]
### Expected behavior
No such error should be existent

### Actual behavior
Error exists

### Steps to reproduce
Unknown

### Netty version
Unknown

### JVM version (e.g. `java -version`)
17

### OS version (e.g. `uname -a`)
Unknown

**Comment by chrisvest** [comment]
We can't do anything with so little description of the problem
