### ISSUE TITLE
Utf8FrameValidator throws a CorruptedWebSocketFrameException on some control frames

### ISSUE THREAD

**Issue by jguerra** [netty/netty#14118]
### Expected behavior
CloseWebSocketFrame (or any control frame) should not have its content validated by Utf8FrameValidator

### Actual behavior
If a close frame is received in the middle of a fragmented message, and the close frame has specified a status code, the Utf8FrameValidator attempts to validate the binary content and throws a CorruptedWebSocketFrameException

### Steps to reproduce
In the middle of processing a fragmented message send a close frame with a status code

### Minimal yet complete reproducer code (or URL to code)
https://github.com/netty/netty/pull/14117

### Netty version
4.1.109.Final

### JVM version (e.g. `java -version`)
openjdk version "21" 2023-09-19
OpenJDK Runtime Environment Zulu21.28+85-CA (build 21+35)
OpenJDK 64-Bit Server VM Zulu21.28+85-CA (build 21+35, mixed mode, sharing)

### OS version (e.g. `uname -a`)
Darwin Justins-MacBook-Pro.local 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000 arm64

**Comment by normanmaurer** [comment]
@jguerra PTAL https://github.com/netty/netty/pull/14122
