### ISSUE TITLE
Apparent corruption with gRPC and Netty 4.1.111

### ISSUE THREAD

**Issue by ejona86** [netty/netty#14126]
Edit: This issue should be limited to grpc-java.

-----

Still very early, and I can totally believe gRPC's behavior could be contributing, but getting the word out as we figure out what is wrong. The gRPC version doesn't seem to matter much.

I'm seeing the HTTP/2 frame inside the gRPC message. https://github.com/grpc/grpc-java/issues/11284#issuecomment-2168264887

I've not yet reproduced it, but people are reporting there wasn't an issue with Netty 4.1.110. My current guess is the ByteBuf changes (fixes) in 4.1.111 may be causing gRPC's NettyAdaptiveCumulator to improperly reuse buffers or use the wrong indexes.

**Comment by normanmaurer** [comment]
@ejona86 keep me posted

**Comment by franz1981** [comment]
We noticed something on quarkus as well, cc @cescoffier

**Comment by lhotari** [comment]
Root cause explained in this comment: https://github.com/grpc/grpc-java/issues/11284#issuecomment-2168508923 .
> I suspect NettyAdaptiveCumulator got broken by https://github.com/netty/netty/pull/14093.
Because of https://github.com/netty/netty/issues/12844, we had a temporary workaround to correct r/w indexes, which never got resolved

**Comment by normanmaurer** [comment]
@franz1981 @cescoffier any more details ?

**Comment by franz1981** [comment]
I don't have much more details actually: https://github.com/quarkusio/quarkus/pull/41155#issuecomment-2165801888

**Comment by cescoffier** [comment]
@normanmaurer Yes, the Quarkus issue is related to grpc-java. Our "pure" gRPC server works nicely with 4.1.111.

**Comment by ejona86** [comment]
This issue is limited to grpc-java.

I'm going to leave this open until patch releases of grpc-java are available, to catch attention of anybody that stumbles on the issue.

**Comment by ejona86** [comment]
grpc-java v1.65.0 is available, which has a fix for the corruption. Some other releases are still in-progress with the fix. But I think this issue has served its purpose, so closing.
