### ISSUE TITLE
Questions about IdleStateHandler member variables

### ISSUE THREAD

**Issue by lwd-coding** [netty/netty#14139]
IdleStateHandler's lastReadTime and lastWriteTime should be volatile
Because IdleStateHandler cannot guarantee that it will work in the event loop

**Comment by He-Pin** [comment]
Why should you attach it to another executor?

**Comment by lwd-coding** [comment]
> Why should you attach it to another executor?

Could there be such a misuse?
channelPipeline.addLast(executorGroup, new IdleStateHandler(readIdleTimeOut, writeIdleTimeOut, allIdleTimeOut, TimeUnit.SECONDS));
