### ISSUE TITLE
Malformed ipv6 through proxy

### ISSUE THREAD

**Issue by dbeau35** [netty/netty#14137]
### Expected behavior

The CONNECT request send an well-formed ipv6
CONNECT [2001:0000:130F:0000:0000:09C0:876A:130B]:443
simple bracket

### Actual behavior
The CONNECT request send an malformed ipv6
CONNECT [[2001:0000:130F:0000:0000:09C0:876A:130B]]:443
double bracket

### Steps to reproduce
Sending a https request from an IPV4 network to an IPV6 server through http proxy

### Minimal yet complete reproducer code (or URL to code)
public static String formatHostnameForHttp(InetSocketAddress addr) {
        String hostString = NetUtil.getHostname(addr);
        if (NetUtil.isValidIpV6Address(hostString)) {
            if (!addr.isUnresolved()) {
                hostString = NetUtil.toAddressString(addr.getAddress());
            }

            return '[' + hostString + ']';
        } else {
            return hostString;
        }
    }
When ipv6 is [2001:0000:130F:0000:0000:09C0:876A:130B], the isValidIpV6Address return true, the addr is Unresolved (because the ipv6 is behind the proxy), but brackets is always added and the final result contains double brackets

### Netty version
4.1.107
### JVM version (e.g. `java -version`)
17

**Comment by normanmaurer** [comment]
@dbeau35 we love PRs
