### ISSUE TITLE
`PlatformDependent.directBufferAddress` method causes process core

### ISSUE THREAD

**Issue by mikechengwei** [netty/netty#14148]
### Expected behavior
Allocate bytesbuf normally
### Actual behavior
`PlatformDependent.directBufferAddress` method causes process core.

<img width="1391" alt="Screenshot 2024-06-30 at 12 30 12" src="https://github.com/netty/netty/assets/13257127/e2c104c8-a03e-45d5-b273-fd9ec4cbe211">

### Steps to reproduce
In high traffic scenarios.
### Netty version
4.1.31.
```
       <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-all</artifactId>
                <version>4.1.31.Final</version>
           </dependency>
```
### JVM version (e.g. `java -version`)
jdk1.8
### OS version (e.g. `uname -a`)
centos7

**Comment by hyperxpro** [comment]
Please use the latest version and give it a try.

**Comment by mikechengwei** [comment]
@hyperxpro  do you mean netty-all 4.1.111.Final verison?

**Comment by hyperxpro** [comment]
Yes

**Comment by mikechengwei** [comment]
> > Yes
> 
> Do you think there is a crash bug in the lower version like `4.1.31`,right ?

@hyperxpro  hi.

**Comment by hyperxpro** [comment]
Give it a try, there are lots of changes post 4.1.31 release.
