### ISSUE TITLE
Websocket MQTT client errors out when subscribing with QOS=1

### ISSUE THREAD

**Issue by oreillymj** [netty/netty#14146]
### Expected behavior
I put together a simple MQTT client over Websockets as I couldn't find a simple example anywhere. 

I expect to be able to PUB & SUB at various QOS once I get an MQTT CONNACK response. I would expect existing MQTT code to "just" work as essentially wrapping the MQTT packets for Websockets is handled for me. 
### Actual behavior
When my code runs, I see a disconnect from Moquitto broker (2.18 latest, but I've also tried older versions in Docker) if I 

Subscribe with QOS0  (QOS1 works fine)
Publish with QOS1 (QOS0 works fine)

Other brokers such as HiveMQ/EMQX tolerate whatever malformed MQTT packet I'm sending.

### Good
=================================
1719510324: mosquitto version 2.0.18 running
1719510410:  ++ [wsisrv|0|adopted] (1)
1719510410: New client connected from ::ffff:192.168.2.72:65237 as netty_websocket_clientId (p2, c1, k60).
1719510410: No will message specified.
1719510410: Sending CONNACK to netty_websocket_clientId (0, 0)
1719510410: Received PUBLISH from netty_websocket_clientId (d0, **q0,** r0, m0, 'test/topic', ... (32 bytes))
1719510410: Received PUBLISH from netty_websocket_clientId (d0, **q0**, r0, m0, 'test/topic2', ... (32 bytes))
1719510410: Received SUBSCRIBE from netty_websocket_clientId
1719510410:     topic/147b6211-8c2b-4e76-a5c1-4030218e97d0 (**QoS 1**)
1719510410: Sending SUBACK to netty_websocket_clientId
1719510470: Received PINGREQ from netty_websocket_clientId
1719510470: Sending PINGRESP to netty_websocket_clientId

### Bad - publish #2 = QOS1
==============================================
1719510579: Sending CONNACK to netty_websocket_clientId (0, 0)
1719510579: Received PUBLISH from netty_websocket_clientId (d0, q0, r0, m0, 'test/topic', ... (32 bytes))
1719510579: Client netty_websocket_clientId closed its connection.
1719510579:  -- [wsisrv|1|adopted] (0) 140.594ms

Connection is dropped when Publish #2 is received with QOS1

Here the connection is dropped at the Subscribe with QOS0
1719510655: New client connected from ::ffff:192.168.2.72:64518 as netty_websocket_clientId (p2, c1, k60).
1719510655: No will message specified.
1719510655: Sending CONNACK to netty_websocket_clientId (0, 0)
1719510655: Received PUBLISH from netty_websocket_clientId (d0, q0, r0, m0, 'test/topic', ... (32 bytes))
1719510655: Received PUBLISH from netty_websocket_clientId (d0, q0, r0, m0, 'test/topic2', ... (32 bytes))
1719510655: Client netty_websocket_clientId closed its connection.
1719510655:  -- [wsisrv|2|adopted] (0) 157.125ms

### Steps to reproduce
Build the client from the Github in Intelij. I'm using the JARS from 4.1.100. I haven't seen any MQTT changes recently.

For a broker, you can run one in Docker.
https://github.com/agmangas/mosquitto-websockets.git
I've used various versions for testing
```
FROM eclipse-mosquitto:2.0.18
#####FROM eclipse-mosquitto:1.4.12
#####FROM eclipse-mosquitto:1.4.4

RUN mkdir -p /mosquitto/data/
COPY mosquitto.conf /mosquitto/config/mosquitto.conf
VOLUME /mosquitto/data/
```
My mosquitto.conf looks as follows
```
##Logging

log_dest stdout
log_type debug
log_type error
log_type warning
log_type notice
log_type information
log_type websockets

websockets_log_level 4
#websockets_headers_size 1024

connection_messages true


##MQTT Listener

listener 1883
protocol mqtt
allow_anonymous true
##WebSockets Listener

listener 9001
protocol websockets
allow_anonymous true
##Persistence

persistence false
```
### Minimal yet complete reproducer code (or URL to code)
https://github.com/oreillymj/netty-mqtt-websocket-client

Change PUB/SUB settings here
https://github.com/oreillymj/netty-mqtt-websocket-client/blob/368198df6813aa6aa56e9fde5bd055b1623b036c/src/MqttMessageHandler.java#L105

### Netty version
4.1.100 (behaviour is the same with 4.1.111)
### JVM version (e.g. `java -version`)
I run this in Intellij with 
semeru-11.0.21

### OS version (e.g. `uname -a`)
I'm running this on Windows 11 against a Mosquitto broker running on Windows. I've also tested with the broker on Ubuntu 22.04

Linux ubuntu2204 5.15.0-105-generic #115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by michaeloreillyintel** [comment]
Added pom.xml to src [repo ](https://github.com/oreillymj/netty-mqtt-websocket-client) enabling building using Maven.

**Comment by oreillymj** [comment]
So I discovered that for subscription publishes, the MQTT Qos parameter in the MqttFixedHeader must be set to MqttQoS.AT_LEAST_ONCE.  What I think might be a bug, is that if the MessageType is set to MqttMessageType.SUBSCRIBE, that it accepts an invalid value.
I'm not sure if the correct behaviour would be to fix this on the users behalf.
