### ISSUE TITLE
The first half of the websocket packet is truncated

### ISSUE THREAD

**Issue by 131452099900** [netty/netty#14163]

**Comment by michaeloreillyintel** [comment]
I'd count the exact number of byte the truncation happens at and then look through the object in your pipeline that have configurable sizes to find a match.

e.g.

p.addLast(new HttpClientCodec(512, 512, 512));
p.addLast(new HttpObjectAggregator(65536));


Websockets also supports [fragmentation ](https://www.openmymind.net/WebSocket-Framing-Masking-Fragmentation-and-More/)of data across frames.

**Comment by normanmaurer** [comment]
Closing for now.
