### ISSUE TITLE
IoHandlerFactory#newFactory not taking the param passed in

### ISSUE THREAD

**Issue by dpy1123** [netty/netty#14164]
Just report a little mistake in IoUringIoHandler, ringSize should pass to Native.createRingBuffer().

<img width="645" alt="image" src="https://github.com/netty/netty/assets/3691507/3b05187b-fc91-4a1c-8469-2e278f2b032d">

### Netty version

4.2.0.Alpha2

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/14169
