### ISSUE TITLE
Is it possible to combine nio and virtual threads to create a new revolutionary version？

### ISSUE THREAD

**Issue by chenqimiao** [netty/netty#14175]
Firstly, this is not a question post, but a discussion post.
As is well known, netty combined with nio utilizes limited thread resources to achieve massive connections.
Is it possible to generate a more powerful Java network framework using nio+virtual threads?

**Comment by zekronium** [comment]
Vert.x, which is a higher level framework using netty, already offers this feature: https://github.com/eclipse-vertx/vert.x

There were also experiments where executors were replaced with Virtual thread executors but offered similar performance.

Additionally, if you mean actually using the eventloop threads as carrier threads, with the current JDK API its not possible to do so as far as I know and unsure if that would actually improve performance apart from reducing callback style code if that was possible.
