### ISSUE TITLE
SSL problem with >= 4.1.52

### ISSUE THREAD

**Issue by wowjavakr** [netty/netty#14173]
SSL problem with >= 4.1.52

I see that since the version 4.1.52 I have problems with SSL.
My JDK version is OpenJDK Runtime Environment Zulu21.34+19-CA (build 21.0.3+9-LTS).

When the attached source code is executed, “pass1” and “pass2” should appear as output.
However, it only executes correctly in Netty versions prior to 4.1.52.

-----

I solved this problem using OpenSSL.

**Comment by hyperxpro** [comment]
Please paste the code here. No body is gonna download and open it.
