### ISSUE TITLE
SBOM Report for Infor ( GRC Product )

### ISSUE THREAD

**Issue by AdityaBhinge** [netty/netty#14182]
Hi,

Aditya here from the Infor GRC automation team. We have been using these packages for our product, GRC (Governance Risk and Compliance), for a while now. Infor GRC has been generating SBOM reports for vulnerability scanning. Recently, we have been asked to obtain SBOM reports from third-party resources we have been using. Therefore, I request you to provide me with the SBOM reports for the packages mentioned below, along with their versions. The reports are required for these versions only and in CycloneDX JSON format.

netty-transport-native-epoll -	4.1.111.Final	
netty-transport-classes-epoll -	4.1.111.Final	
netty-buffer -	4.1.111.Final	
netty-codec -	4.1.111.Final	
netty-codec-http2 -	4.1.111.Final	
netty-transport-native-unix-common -	4.1.111.Final	
netty-resolver -	4.1.111.Final	
netty-transport	 - 4.1.111.Final	
netty-handler -	4.1.111.Final	
netty-codec-http -	4.1.111.Final	
netty-common  -	4.1.111.Final

**Comment by chrisvest** [comment]
Netty, as an open source project, has no obligation to provide you with such reports. You can check out the relevant tag, modify the pom files to add sbom plugins, and generate the reports yourselves. You could also take this opportunity to contribute sbom plugin configurations to our build, to make this less troublesome in the future.
