### ISSUE TITLE
Netty doesn't sufficiently validate received HTTP versions

### ISSUE THREAD

**Issue by kenballus** [netty/netty#14186]
### Steps to reproduce
1. Start a Netty HTTP/1.1 server that echos the parsed components of the request, such as [this one](https://raw.githubusercontent.com/narfindustries/http-garden/main/images/netty/GardenServer.java).
2. Send it a request with an invalid version:
```sh
(printf 'POST / INVALID/12.34\r\n\r\n'; sleep 1) \
    | ncat localhost 80 \
    | grep '"version"' \
    | jq '.["version"]' \
    | xargs echo \
    | base64 -d \
    | xxd
```
3. Observe that the invalid version was not rejected, and was preserved:
```
00000000: 494e 5641 4c49 442f 3132 2e33 34         INVALID/12.34
```

### Expected behavior
The RFCs are clear that HTTP versions need to consist of only the ASCII bytes "HTTP/", followed by a single ASCII digit, a dot, and another ASCII digit. The recommended behavior upon receiving a request with an invalid version should be to reject the request and close the connection. This is what most HTTP implementations do, including AIOHTTP, Apache httpd, Cheroot, FastHTTP, Go net/http, Gunicorn, H2O, HAProxy, Hyper, Hypercorn, Jetty, Libevent, Libsoup, Lighttpd, Nginx, Node.js LiteSpeed, Passenger, Puma, Tomcat, Tornado, OpenWrt uhttpd, Unicorn, Uvicorn, Waitress, WEBrick, OpenBSD httpd, Apache Traffic Server, nghttpx, Pingora, Pound, Squid, Varnish, Akamai GHost, Cloudflare's CDN, Google Cloud Classic App. LB, and Envoy.

### Actual behavior
Netty accepts the request with the invalid version.

### Netty version
4.1 @ 3881103a01488785a6d2f78a3a80258dd848609f

### JVM version (e.g. `java -version`)
```
openjdk version "23-ea" 2024-09-17
OpenJDK Runtime Environment (build 23-ea+20-Debian-1)
OpenJDK 64-Bit Server VM (build 23-ea+20-Debian-1, mixed mode, sharing)
```

### OS version (e.g. `uname -a`)
```
Linux a2d83c065945 6.9.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 05 Jul 2024 22:11:24 +0000 x86_64 GNU/Linux
```

**Comment by normanmaurer** [comment]
@kenballus please check https://github.com/netty/netty/pull/14187

**Comment by conet** [comment]
Can this new feature be controlled by a flag similar to `validateHeaders`?
