### ISSUE TITLE
SingleThreadEventExecutor#scheduleRemoveScheduled no need to execute immediate

### ISSUE THREAD

**Issue by dpy1123** [netty/netty#14199]
Hi there,
I think there is no need to wakeup ioHandler in this case.
<img width="903" alt="image" src="https://github.com/user-attachments/assets/028b8129-8455-4ead-bdc1-e016e55b55c2">
Just like before `lazyExecute` will not wakeup ioHandler.
<img width="708" alt="image" src="https://github.com/user-attachments/assets/89ea1b07-e73f-4f21-ac40-5809b8ea45f4">

### Netty version
4.2.0.Alpha3

**Comment by normanmaurer** [comment]
I think the code is correct
