### ISSUE TITLE
Netty's handling of OutOfMemory exceptions is not robust enough.

### ISSUE THREAD

**Issue by etcEriksen** [netty/netty#14207]
### Expected behavior

**### 1.Issue Description**
During health checks on the online Dubbo RPC service, a large number of CLOSE_WAIT state exceptions were observed on the TCP connections at the Dubbo server side. It has been identified that the Netty 3.7.0Final code, which Dubbo depends on, is not robust enough in handling OutOfMemory (OOM) exceptions.

**### 2.Preliminary Analysis**
Dubbo's network communication relies on Netty 3.7.0Final. When network communication is disconnected, a four-way handshake is performed. However, during the health check when the FIN is sent, the Netty server ACKs, but an OOM exception occurs, preventing the Netty server (TCP kernel) from sending a FIN back to the health check connection, resulting in a large number of CLOSE_WAIT states on the server side. I have verified this analysis using Wireshark and tcpdump.

**### 3.Analysis Process of This Issue**
1. The TCP three-way handshake is successful, and the connection is added to the kernel's full connection queue.
2. Netty's accept operation takes the connection that has been established from the full connection queue.
3. An OOM exception occurs.
4. The client sends a FIN to disconnect, and the Netty server sends an ACK.
5. However, the Netty server does not actively disconnect when handling the OOM exception, resulting in no FIN being sent to the client, and the last two steps of the four-way handshake are not completed successfully. This leads to the server being stuck in the CLOSE_WAIT state.

**### 4.Specific Netty 3.7.0 Source Code Analysis and Solution Approach**
The problematic code is located at src/main/java/org/jboss/netty/channel/socket/nio/NioServerBoss.java. In the process method of this class, when an OOM exception Throwable occurs, Netty should call close to shut down the connection properly.
@Override
protected void process(Selector selector) {
    Set<SelectionKey> selectedKeys = selector.selectedKeys();
    if (selectedKeys.isEmpty()) {
        return;
    }
    for (Iterator<SelectionKey> i = selectedKeys.iterator(); i.hasNext();) {
        SelectionKey k = i.next();
        i.remove();
        NioServerSocketChannel channel = (NioServerSocketChannel) k.attachment();
        try {
            // accept connections in a loop until no new connection is ready
            for (;;) {
                SocketChannel acceptedSocket = channel.socket.accept();
                if (acceptedSocket == null) {
                    break;
                }
                registerAcceptedChannel(channel, acceptedSocket, thread);
            }
        } catch (CancelledKeyException e) {
            // Raised by accept() when the server socket was closed.
            k.cancel();
            channel.close();
        } catch (SocketTimeoutException e) {
            // Thrown every second to get ClosedChannelException
            // raised.
        } catch (ClosedChannelException e) {
            // Closed as requested.
        } catch (Throwable t) {
            if (logger.isWarnEnabled()) {
                logger.warn(
                        "Failed to accept a connection.", t);
            }
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e1) {
                // Ignore
            }
        }
    }
}

**Comment by chrisvest** [comment]
First, Netty 3.x is not supported anymore and will not get further updates.

Second, handling OutOfMemoryError in Java is not a reasonable ask in general, because they can occur at almost every bytecode. It's better to handle them operationally with e.g. `-XX:+ExitOnOutOfMemoryError`.
If there is code that causes leaks, then those of course needs to be plugged.

**Comment by etcEriksen** [comment]
> First, Netty 3.x is not supported anymore and will not get further updates.
> 
> Second, handling OutOfMemoryError in Java is not a reasonable ask in general, because they can occur at almost every bytecode. It's better to handle them operationally with e.g. `-XX:+ExitOnOutOfMemoryError`. If there is code that causes leaks, then those of course needs to be plugged.

We encountered an OutOfMemory exception on the production line due to a scheduled task that flushed memory during the early hours of the morning. Our approach online was to fork the Netty source code, robustly handle the close operation, then package, test, and deploy it.

**Comment by etcEriksen** [comment]
> First, Netty 3.x is not supported anymore and will not get further updates.
> 
> Second, handling OutOfMemoryError in Java is not a reasonable ask in general, because they can occur at almost every bytecode. It's better to handle them operationally with e.g. `-XX:+ExitOnOutOfMemoryError`. If there is code that causes leaks, then those of course needs to be plugged.

thank you very much，coding guru ！
