### ISSUE TITLE
Creating new Threads even though there are idle threads running

### ISSUE THREAD

**Issue by Jasphy** [netty/netty#14204]
Nioevent loop run method running continuously due to which SingleThreadEventExecutor Threads are running  and new threads are creating on top of this which is causing native memory OOM issue due to thread unallocated error

Using netty version 4.1.31.Final.jar 

Any suggestions how to terminate long running threads ?

**Comment by Jasphy** [comment]
Can you please suggest version

**Comment by chrisvest** [comment]
@Jasphy latest version is 4.1.112.Final.

**Comment by Jasphy** [comment]
Any suggestions on how to reduce thread pool count , by default we have 16 , I tried updating bean tag in beans.xml for nettycomponent bean , given property 
Maxpoolsize value=1

**Comment by normanmaurer** [comment]
This seems like a spring question... Usually you would pass the number of threads to the `*EventLoopGroup` constructor.
