### ISSUE TITLE
Netty does not sufficiently validate HTTP methods

### ISSUE THREAD

**Issue by kenballus** [netty/netty#14201]
### Steps to reproduce
1. Start a Netty HTTP/1.1 server that echos the parsed components of the request, such as [this one](https://raw.githubusercontent.com/narfindustries/http-garden/main/images/netty/GardenServer.java).
2. Send it a request with an invalid method:
```sh
printf '\x22\x28\x29\x2c\x2f\x3a\x3b\x3c\x3d\x3e\x3f\x40\x5b\x5c\x5d\x7b\x7d\xa0\xa1\xa2\xa3\xa4\xa5\xa6\xa7\xa8\xa9\xaa\xab\xac\xad\xae\xaf\xb0\xb1\xb2\xb3\xb4\xb5\xb6\xb7\xb8\xb9\xba\xbb\xbc\xbd\xbe\xbf\xc0\xc1\xc2\xc3\xc4\xc5\xc6\xc7\xc8\xc9\xca\xcb\xcc\xcd\xce\xcf\xd0\xd1\xd2\xd3\xd4\xd5\xd6\xd7\xd8\xd9\xda\xdb\xdc\xdd\xde\xdf\xe0\xe1\xe2\xe3\xe4\xe5\xe6\xe7\xe8\xe9\xea\xeb\xec\xed\xee\xef\xf0\xf1\xf2\xf3\xf4\xf5\xf6\xf7\xf8\xf9\xfa\xfb\xfc\xfd\xfe\xff / HTTP/1.1\r\nHost: whatever\r\n\r\n' \
    | nc localhost 80 \
    | grep '"method"' \
    | jq '.["method"]' \
    | xargs echo \
    | base64 -d \
    | xxd
```
3. Observe that the invalid method was not rejected, and was preserved:
```
00000000: 2228 292c 2f3a 3b3c 3d3e 3f40 5b5c 5d7b  "(),/:;<=>?@[\]{
00000010: 7da0 a1a2 a3a4 a5a6 a7a8 a9aa abac adae  }...............
00000020: afb0 b1b2 b3b4 b5b6 b7b8 b9ba bbbc bdbe  ................
00000030: bfc0 c1c2 c3c4 c5c6 c7c8 c9ca cbcc cdce  ................
00000040: cfd0 d1d2 d3d4 d5d6 d7d8 d9da dbdc ddde  ................
00000050: dfe0 e1e2 e3e4 e5e6 e7e8 e9ea ebec edee  ................
00000060: eff0 f1f2 f3f4 f5f6 f7f8 f9fa fbfc fdfe  ................
00000070: ff                                       .
```

### Expected behavior
Netty should reject the request because its method is invalid due to containing forbidden characters. The HTTP RFCs define that only the following characters are permitted within an HTTP method:
> "!" / "#" / "$" / "%" / "&" / "'" / "*"
      / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
      / DIGIT / ALPHA

(where `DIGIT` stands for ASCII digits (0-9) and `ALPHA` stands for ASCII letters (a-zA-Z))

All of the characters in the above request's method are disallowed, so the request should definitely be rejected.

Nearly all other HTTP implementations reject this request, including AIOHTTP, Apache httpd, FastHTTP, Go net/http, Gunicorn, H2O, HAProxy, Hyper, Hypercorn, Jetty, Ktor, Libevent, Lighttpd, Mongoose, Nginx, Node.js, LiteSpeed, Passenger, Puma, ServiceTalk, Tomcat, Twisted, OpenWrt uhttpd, Unicorn, Uvicorn, Waitress, WEBrick, and OpenBSD httpd.

### Actual behavior
Netty accepts the request with the invalid method.

### Netty version
4.1 @ e35c34377cb99e0fdb2fafae060d73e5a6f16509

### JVM version (e.g. `java -version`)
```
openjdk version "23-ea" 2024-09-17
OpenJDK Runtime Environment (build 23-ea+20-Debian-1)
OpenJDK 64-Bit Server VM (build 23-ea+20-Debian-1, mixed mode, sharing)
```

### OS version (e.g. `uname -a`)
```
Linux 66e435c7ed44 6.9.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 05 Jul 2024 22:11:24 +0000 x86_64 GNU/Linux
```

**Comment by freeyob** [comment]
Hi, the [RFC](https://www.rfc-editor.org/rfc/rfc9110#section-9) doesn't forbid custom methods, so I think it's okay to handle method validation within the business logic.

**Comment by normanmaurer** [comment]
@freeyob while this is true it defines which chars are valid and we should validate that this is what is used.

**Comment by freeyob** [comment]
@normanmaurer  Got it, HTTP method is 'token' type, and the token character set can't include whitespace or delimiters.

**Comment by freeyob** [comment]
Hi, I’ve figured out the issue and the solution. May I go ahead and submit a pull request?

**Comment by normanmaurer** [comment]
@freeyob sure
