### ISSUE TITLE
HttpServerCodec limits max chunk size to 65536

### ISSUE THREAD

**Issue by Riddle4045** [netty/netty#14210]
### Expected behavior
I am setting the max `maxChunkSize` value to `10240000 Bytes ( 10Mib )` however HttpServerCodec limits the chunk to `65536` which is slowing down my server, expect the chunk size to be honored.

How can increase this limit? The `64KB` writes to disk slows down perf.
I ran into this stackoverflow link but I am not entirely sure how it relates to my scenario [stackoverflow qustion](https://stackoverflow.com/questions/37207133/why-does-netty-4-0-x-have-a-default-websocket-frame-size-of-only-65536-byte)

Note : I am aware of the ObjectAggregators in netty that I can use, I am trying to understand if I can avoid them as throughput is critical in this app, I would love to do minimum work. 

### Actual behavior
the chunk size is limited to 65536

### Minimal yet complete reproducer code (or URL to code)
On the server size the ChannelInitializer looks like this 
```java
    @Override
    protected void initChannel(SocketChannel ch)
            throws Exception
    {
        ChannelPipeline pipeline = ch.pipeline();
        pipeline.addLast(new HttpServerCodec(this.decoderConfig));
        pipeline.addLast(new ShuffleInboundHandler(this.config.getShuffleDataWriteDir())); //custom inbound handler which 
        // gets the file name, offset from HTTP request headers and uses a filechannel to copy the bytebuf to disk.
    }
```

On the client side, I map chunks of file to a ByteBuf and send them over to server
```java
          Bootstrap b = new Bootstrap();

          b.group(this.bossGroup)
                  .handler(new ShuffleClientInitializer(this.config))
                  .channel(OSUtils.isLinux ? EpollSocketChannel.class : NioSocketChannel.class);

          Channel f = b.connect(this.config.getHost(), this.config.getPort()).sync().channel();

          HttpRequest postReq = new DefaultFullHttpRequest(HttpVersion.HTTP_1_1,
                  HttpMethod.POST, new URI(this.serverUrl).getRawPath(), Unpooled.wrappedBuffer(block.getBuffer()));

          postReq.headers().set(HttpHeaderNames.HOST, new URI(this.serverUrl).getRawPath());
          postReq.headers().set(HttpHeaderNames.CONNECTION, HttpHeaderValues.KEEP_ALIVE);
          postReq.headers().set(HttpHeaderNames.CONTENT_TYPE, HttpHeaderValues.BINARY);
          postReq.headers().set(HttpHeaderNames.CONTENT_LENGTH, block.getSize());
          ....
          f.writeAndFlush(postReq);
          f.closeFuture().sync();
```
### Netty version
4.1.112.Final
### JVM version (e.g. `java -version`)
openjdk 17.0.12 2024-07-16
OpenJDK Runtime Environment (build 17.0.12+7-Ubuntu-1ubuntu224.04)
OpenJDK 64-Bit Server VM (build 17.0.12+7-Ubuntu-1ubuntu224.04, mixed mode, sharing)

**Comment by normanmaurer** [comment]
@Riddle4045 I suspect what you are limited by is the `SO_RCVBUF`: https://man7.org/linux/man-pages/man7/socket.7.html

This has nothing todo with netty.

**Comment by Riddle4045** [comment]
@normanmaurer  thank you! I will try to set if in ServerBootstrap to see if it helps :)
