### ISSUE TITLE
Regarding the issue of Netty's memory pool

### ISSUE THREAD

**Issue by luozongle01** [netty/netty#14218]
I encountered a problem while learning about the netty memory pool. In the newSizeClass method of the SizeClasses class, log2Group、log2Delta、nDelta、pageShifts， And how to calculate isSubpage and log2DeltaLookup, I'm a bit confused about this code. Can someone help me explain it? Thank you very much.🥺

<img width="970" alt="image" src="https://github.com/user-attachments/assets/c534840a-9c95-4452-97d5-3a6574d89c67">

**Comment by normanmaurer** [comment]
This is an issue tracker... for questions use the discussions
