### ISSUE TITLE
Split package between io.netty.codec and io.netty.codec.xml

### ISSUE THREAD

**Issue by vietj** [netty/netty#14228]
### Expected behavior

No split package between modules.

### Actual behavior

Split package on `io.netty.handler.codec.xml`, the `io.netty.codec` module contains the `io.netty.handler.codec.xml.XmlFrameDecoder`

This can trivially be solved by moving this class to the `io.netty.handler.codec.xml` module. That would be a breaking change since the same class would be moved to another jar, but it seems reasonable for 4.2.

I can provide a PR.

**Comment by chrisvest** [comment]
Searching on the public GitHub, only https://github.com/OpenNMS/opennms (actively maintained and tracking Netty updates reasonably well) and https://github.com/martinmine/ludo (not updated for 10 years) makes use of the `XmlFrameDecoder`.

So I think it's a reasonable compromise to move this class.

**Comment by vietj** [comment]
to clarify (what is obvious) this breaking change would be solved by adding the netty-codec-xml to the classpath

(the other option would be to keep the class in the same jar but rename it but it makes less sense to me)

**Comment by normanmaurer** [comment]
Splitting makes sense

**Comment by vietj** [comment]
will open a PR soonish

**Comment by vietj** [comment]
this issue should be closed
