### ISSUE TITLE
Memory leak in SSLHandler

### ISSUE THREAD

**Issue by Sipaha** [netty/netty#14221]
### Expected behavior

No memory leak

### Actual behavior

Memory leak

### Steps to reproduce

With help of ResourceLeakDetector I found that this code lead to memory leak:

https://github.com/netty/netty/blob/ebe2aa5b7cd36562a20b024d78ecff47a86874b8/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L1475
![image](https://github.com/user-attachments/assets/3874f1e1-02d6-4ead-8f98-7558ab637907)

This is ResourceLeakDetector log:

https://gist.github.com/Sipaha/c3f237018bcde7d750270bcb705d0453

### Netty version

4.1.111.Final

### JVM version (e.g. `java -version`)

openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)

### OS version (e.g. `uname -a`)

Linux gateway-app-dev 5.15.0-113-generic #123-Ubuntu SMP Mon Jun 10 08:16:17 UTC 2024 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
You most likely miss a release call in one of the handlers that are after the `SslHandler`
