### ISSUE TITLE
Increase modularity of netty-codec

### ISSUE THREAD

**Issue by vietj** [netty/netty#14239]
Some packages of `netty-codec` are self contained in their package and are not used elsewhere in `the netty-codec` and fall in a situtation very much like `netty-xml-codec`.

These packages could be extracted to their own module with the only impact of users adding the right dependency to their dependency descriptors.

- `io.netty.handler.codec.protobuf`
- `io.netty.handler.codec.marshalling`

It seems like a good opportunity also to decouple `netty-codec` from these less core libraries and increase the modularity of the project.

The `io.netty.handler.codec.compression` seems also to be a good candidate, it is reused by HTTP codecs and is more core-ish to Netty. If that's the case it would be added as a dependency of the HTTP modules.

**Comment by normanmaurer** [comment]
@vietj this sounds like a good idea to me.

**Comment by vietj** [comment]
great, will take care of it

**Comment by normanmaurer** [comment]
@vietj let me know once we can close this one

**Comment by vietj** [comment]
We could decouple more but remaining codecs don’t bring external dependencies, so i think it is fine closing nowLe 26 août 2024 à 11:40, Norman Maurer ***@***.***> a écrit :﻿
@vietj let me know once we can close this one
