### ISSUE TITLE
Drop support of Jetty NPN

### ISSUE THREAD

**Issue by vietj** [netty/netty#14237]
The NPN feature is currently supported in Netty using the Jetty NPN library.

This library has been archived and the maintainers are not keen on continuing to support it.

NPN has been deprecated in favour of ALPN and browsers should be using ALPN instead (ALPN is almost 10 years old), the Jetty project has dropped NPN in Jetty 9.3 (2015 - https://webtide.com/phasing-out-spdy-support/) and has not seen evidence of the lack of NPN being an issue (per @sbordet)

NPN could be dropped in Netty 5.0 and possibly in 4.2 as well.

**Comment by chrisvest** [comment]
I think we already dropped in Netty 5.

**Comment by vietj** [comment]
oh good to know, what is your opinion about 4.2 ?

**Comment by chrisvest** [comment]
I'm in favour, since it's been obsolete for a while, but I want to hear what @normanmaurer has to say as well.
Relatedly, there's a couple of related issues here about dropping NPN, and also https://github.com/netty/netty-tcnative/issues/856

**Comment by normanmaurer** [comment]
I am fine for 4.2 as well ... let's go

**Comment by vietj** [comment]
thanks for the feedback, shall I take care of it ?

**Comment by normanmaurer** [comment]
@vietj yes please
