### ISSUE TITLE
ChunkedWriteHandler hides closed channels

### ISSUE THREAD

**Issue by maczikasz** [netty/netty#14236]
### Expected behavior

When a ChunkedWriteHandler attempts tp pass-through write to a closed channel, the write promise fails

### Actual behavior

ChunkedWriteHandler tries to discard a closed channel but since it have not added any work to its queue, it will NOOP. This will cause the passed down Promise in `write` to never err

### Steps to reproduce

Close a channel during writing in a chain with a `ChunkedWriteHandler`

### Minimal yet complete reproducer code (or URL to code)

TBD

### Netty version

From 4.1.105, introduced by this commit

https://github.com/netty/netty/commit/ce0366bf9f09ede4600ed9ded699db4a379411d9

### JVM version (e.g. `java -version`)

openjdk 21.0.2 2024-01-16 LTS

### OS version (e.g. `uname -a`)

Darwin F7VN9D7X30 23.6.0 Darwin Kernel Version 23.6.0: Fri Jul  5 17:56:41 PDT 2024; root:xnu-10063.141.1~2/RELEASE_ARM64_T6000 arm64 arm Darwin

**Comment by maczikasz** [comment]
https://github.com/maczikasz/netty/commit/701f3e7c1a160a42f03158978c19d8c4bae4daed

This fixes the issue in my tests, but not 100% convinced it's the proper fix for this, or wether there is a way to work around the issue

**Comment by normanmaurer** [comment]
@maczikasz I think this should fix it: https://github.com/netty/netty/pull/14248

Can you verify ?

**Comment by maczikasz** [comment]
@normanmaurer Amazing, this fixes it, thanks for the quick turnaround
