### ISSUE TITLE
max_idle_time specification when using reactor-netty

### ISSUE THREAD

**Issue by kengokumagae** [netty/netty#14265]
We have found that we need to send FIN packets due to the specification of the firewall that exists on the intermediate route, but we would like to confirm the following two points regarding the max_idle_time specification for that part.
(1) If the max_idle_time limit is exceeded, do we send a FIN packet?
(2) If FIN packets are not sent, is there any way to send them?

### Expected behavior
Sessions are destroyed as per the lifetime setting in max_idle_time

### Actual behavior
The session lifetime is set in max_idle_time, but the session is not destroyed after the lifetime.

### Steps to reproduce
 Same as Actual behavior.

### Minimal yet complete reproducer code (or URL to code)

/**
   * Create an instance of WebClient.
   */
  private void createWebClient() {
    Builder builder = WebClient.builder();
    builder.baseUrl(baseUrl);
    HttpClient httpClient = null;
    if (maxIdleTime != null) {
      ConnectionProvider provider =
          ConnectionProvider.builder("com.kmp3g.dfw.restclient.RestClient")
              .maxIdleTime(Duration.ofMillis(maxIdleTime)).build();
      httpClient = HttpClient.create(provider);
    } else {
      httpClient = HttpClient.create();
    }
    // Connection timeout settings
    httpClient = httpClient.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, connectTimeout);
    // Response Timeout Settings
    if (responseTimeout != null) {
      httpClient = httpClient.responseTimeout(Duration.ofMillis(responseTimeout));
    }
    // proxy configuration
    if (proxyType != null && proxyHost != null && !proxyHost.isEmpty() && proxyPort != null) {
      httpClient =
          httpClient.proxy(typeSpec -> typeSpec.type(proxyType).host(proxyHost).port(proxyPort));
    }
    builder = builder.clientConnector(new ReactorClientHttpConnector(httpClient));
    if (codecMaxInMemorySize != null) {
      ExchangeStrategies strategies = ExchangeStrategies.builder()
          .codecs(configurer -> configurer.defaultCodecs().maxInMemorySize(codecMaxInMemorySize))
          .build();
      builder = builder.exchangeStrategies(strategies);
    }
    // Filter Settings
    builder = builder.filter(restRequestIDFilter.filter());
    if (Boolean.TRUE.equals(authInfoLink)) {
      builder = builder.filter(restAuthInfoLinkFilter.filter());
    }
    builder = builder.filter(restRequestLogFilter.filter());
    this.webClient = builder.build();
  }
    /**
   * Get REST client class.
   *
   * @param accessInfoKey Key to uniquely identify the connection destination.
   * @return Generated REST client class.
   * @throws IllegalArgumentException if no destination information matches the key that uniquely identifies the destination.
   * @see RestClient
   */
  public static RestClient getRestClient(String accessInfoKey) {
    String baseUrl = RestClientProperties.getBaseUrl(accessInfoKey);
    if (baseUrl == null || baseUrl.isEmpty()) {
      throw new IllegalArgumentException(
          String.format(MESSAGE_ACCESS_INFO_KEY_INVALID, accessInfoKey));
    }
    return (RestClient) RestClientAppConfig.getContext().getBean("dfw.restclient.RestClient",
        accessInfoKey);
  }
  /**
   * {@inheritDoc}
   */
  @Override
  public <T> RestRequester<T> createPostRequester(String urlPath, Map<String, String> requestHeader,
      Object jsonDto, Class<T> dtoClass) {
    validate(urlPath, dtoClass);
    RequestBodySpec bodySpec = webClient.post().uri(urlPath);
    setRequestHeader(bodySpec, requestHeader);
    String jsonBody = toStringJson(jsonDto);
    setJsonBody(bodySpec, jsonBody);
    ResponseSpec responseSpec = bodySpec.retrieve();
    Mono<ResponseEntity<T>> mono = responseSpec.toEntity(dtoClass);
    mono = setupMono(mono, METHOD_POST, createUrl(urlPath), jsonBody);
    return new RestRequester<>(mono);
  }

### Netty version
1.0.39

### JVM version (e.g. `java -version`)
Container Image：ibmcom/websphere-liberty:22.0.0.6-full-java17-openj9-ubi

### OS version (e.g. `uname -a`)
Linux/amd64

**Comment by kengokumagae** [comment]
Here is a sample source for the user side to use the above method

---
import java.util.HashMap;
import java.util.Map;

import com.kmp3g.dfw.restclient.RestClient;
import com.kmp3g.dfw.restclient.RestClientFactory;
import com.kmp3g.dfw.restclient.RestRequester;

 public class Sample {
 
     public void run() {
         // 1. get a REST client instance from the REST factory
         RestClient restClient = RestClientFactory.getRestClient("server1");
　　　　// 2. Execute GET method and get REST requestor class to get execution result in DTO
         RestRequester<Hello1ResultDTO> requester = restClient.createGetRequester("/api/hello/1", requestHeader, queryParam, Hello1ResultDTO.class);
         // 3. Perform access to REST API and receive execution results
         Hello1ResultDTO result = requester.execute();
     }
 }

**Comment by yuya17** [comment]
We apologize for the inconvenience, but we are currently investigating, but we would like to add the following points to be confirmed.
(2) If FIN packets are not sent, is there any way to send them?

Current behavior: Even if a request is made to the same destination address, a new PORT is assigned for each request and a new connection is established.
In light of the above behavior, do you have any knowledge of the following?
- When setting MAXpoolSize or MaxConnectionSize, do you know the general behavior when each upper limit is reached? (For example, if additional settings are added in addition to max-idle-time, FIN packets can be sent.)
- As stated in the following issue, as long as you use the build method of the ConnectionProvider class, the specification is that FIN packets will not be sent.
https://github.com/reactor/reactor-netty/issues/3071

**Comment by normanmaurer** [comment]
I thin this should be asked in the reactor issue tracker... /cc @violetagg
