### ISSUE TITLE
Recycler could use a LIFO local structure instead of an ArrayDeque

### ISSUE THREAD

**Issue by franz1981** [netty/netty#14268]
Currently the Recycler is using an `ArrayDeque` to handle single-same-threaded allocations, see https://github.com/netty/netty/blob/netty-4.1.112.Final/common/src/main/java/io/netty/util/Recycler.java#L300

In the ideal scenario of a pool which has already N elements in (recycled afer a burst of usage - yet to verify how much realistic can be this), if a new claim and release happen on a pooled element, the release will move the released element by the end of the `ArrayDeque`, meaning that a subsequent claim *won't* pick it again, but the next in line recycled element instead, wasting some precious cache locality effect.

Turning the `ArrayDeque` in an `ArrayList` used as a stack can be a better option, but require some benchmarking to verify that is a valid improvement.

**Comment by chrisvest** [comment]
You can also the ArrayDeque as a stack.

**Comment by franz1981** [comment]
@chrisvest i didn't check it, but yes, I suppose it would work efficiently the same...in short, this issue can be a one liner...

**Comment by normanmaurer** [comment]
@franz1981 I agree in "theory" this sound like some low-hanging fruit that should give some perf win.

**Comment by Obolrom** [comment]
@franz1981 could you please assign the issue to me?
