### ISSUE TITLE
AdaptiveByteBufAllocator may be memory leak

### ISSUE THREAD

**Issue by linking12** [netty/netty#14269]
### Expected behavior
use AdaptiveByteBufAllocator do not OOM
### Actual behavior
AdaptiveByteBufAllocator oom
### Steps to reproduce
use [LittleProxy](https://github.com/LittleProxy/LittleProxy )  

Server:
      
```
ServerBootstrap serverBootstrap = new ServerBootstrap()//
            .group(serverGroup.getProxyBoss(), serverGroup.getProxyWorker())//
            .childOption(ChannelOption.SO_LINGER, -1)//
            .childOption(ChannelOption.SO_KEEPALIVE, Boolean.TRUE)//
            .childOption(ChannelOption.TCP_NODELAY, Boolean.TRUE)//
            .childOption(ChannelOption.SO_REUSEADDR, Boolean.TRUE)//
            .childOption(ChannelOption.SO_SNDBUF, 4 * 1024 * 1024)//
            .childOption(ChannelOption.SO_RCVBUF, 64 * 1024)//
            /**
             * @see https://github.com/netty/netty/pull/13075
             */
            .childOption(ChannelOption.ALLOCATOR, new AdaptiveByteBufAllocator())//
            .option(ChannelOption.ALLOCATOR, new AdaptiveByteBufAllocator())//

```
    client:
   
 ```
        Bootstrap cb = new Bootstrap().group(eventLoopGroup)//
            .channel(proxyServer.getServerGroup().getSocketChannelClass())
            .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, proxyServer.getConnectTimeout())//
            .option(ChannelOption.SO_KEEPALIVE, Boolean.TRUE)//
            .option(ChannelOption.TCP_NODELAY, Boolean.TRUE)//
            .option(ChannelOption.SO_REUSEADDR, Boolean.TRUE)//
            .option(ChannelOption.SO_SNDBUF, 4 * 1024 * 1024)//
            .option(ChannelOption.SO_RCVBUF, 64 * 1024)//
            .option(ChannelOption.WRITE_BUFFER_WATER_MARK, new WriteBufferWaterMark(8 * 1024, 32 * 1024))
            .option(ChannelOption.AUTO_READ, true)//
            /**
             * @see https://github.com/netty/netty/pull/13075
             */
            .option(ChannelOption.ALLOCATOR, new AdaptiveByteBufAllocator())//
            .handler(new ChannelInitializer<Channel>() {
                public void initChannel(Channel ch) throws Exception {
                    initChannelPipeline(ch.pipeline());
                }
            });
    
```
   LittleProxy will OOM kill
   when i delete AdaptiveByteBufAllocator is ok
   
### Minimal yet complete reproducer code (or URL to code)
   hard to provide
### Netty version
   <netty.version>4.1.112.Final</netty.version>
   <netty-tcnative-boringssl-static.version>2.0.66.Final</netty-tcnative-boringssl-static.version>
### JVM version (e.g. `java -version`)
    jdk17
### OS version (e.g. `uname -a`)
    TBD

My colleague will provide some evidence later

**Comment by normanmaurer** [comment]
Can you provide a heapdump ?

**Comment by linking12** [comment]
> Can you provide a heapdump ?
15m 
<img width="710" alt="1" src="https://github.com/user-attachments/assets/b0acd143-bf55-4464-889e-724bb49df5da">
20m
<img width="809" alt="2" src="https://github.com/user-attachments/assets/5fc95f34-bc3b-45c4-afaa-9a1f4d66ba1b">
3h
<img width="657" alt="3" src="https://github.com/user-attachments/assets/c0e2c0ae-f087-4b24-a935-389156b917f4">

**Comment by franz1981** [comment]
@linking12 something is off here:

![image](https://github.com/user-attachments/assets/f5ab5bb5-c97a-467d-8ffe-3fd581626546)

what kind of cpu it is? it is a supported standard OpenJDK?

**Comment by franz1981** [comment]
![image](https://github.com/user-attachments/assets/f29c195e-48f4-43fe-b989-e56e7eb6ba81)

This is the problem: you number of allocators are too much...you should use a single instance you store and configure somewhere OR just https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/ByteBufAllocator.java#L24 but providing `-D-Dio.netty.allocator.type=adaptive`

**Comment by linking12** [comment]
> @linking12 something is off here:
> 
> ![image](https://private-user-images.githubusercontent.com/13125299/362587815-f5ab5bb5-c97a-467d-8ffe-3fd581626546.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTg4NTcsIm5iZiI6MTcyNDkxODU1NywicGF0aCI6Ii8xMzEyNTI5OS8zNjI1ODc4MTUtZjVhYjViYjUtYzk3YS00NjdkLThmZmUtM2ZkNTgxNjI2NTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA4MDIzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MzY2ZDAwZDY4ZWNlNDAzZDhlMjg2N2MyNTQyZDgyM2Q0MWFjYjlhZjVkNDUzN2ZlYTM0ZjczOWZmYjQ0OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F3qqoNhzo9V4AHxXtk8iFEa-m4bdOTT0LwZylA3Ebn8)
> 
> what kind of cpu it is? it is a supported standard OpenJDK?

```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               106
Model name:          Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz
Stepping:            6
CPU MHz:             3444.097
BogoMIPS:            5799.90
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            55296K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd ida arat avx512vbmi pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear flush_l1d arch_capabilities
```

**Comment by franz1981** [comment]
Please read the comment at https://github.com/netty/netty/issues/14269#issuecomment-2316970695

Regardless; the dump is not collected on the same machine I can tell, because the arch on the heap dump is ARM, while the cpu you past is an Intel Xeon.

I can close this as soon as you fix the code as suggested...

**Comment by linking12** [comment]
> Please read the comment at [#14269 (comment)](https://github.com/netty/netty/issues/14269#issuecomment-2316970695)
> 
> Regardless; the dump is not collected on the same machine I can tell, because the arch on the heap dump is ARM, while the cpu you past is an Intel Xeon.
> 
> I can close this as soon as you fix the code as suggested...

My fault， is docker container， is ARM

**Comment by franz1981** [comment]
@linking12 and now something "funny" which both me and @nitsanw are painfully much aware

![image](https://github.com/user-attachments/assets/cb13cd7f-2583-43ab-b35e-496c132e6793)


your application is supposed to "just" use the adaptive allocator, but..as you can see there's some other parts of your application/libraries with all the degrees of shading, which don't think the same - causing, likely, you to have more than one off-heap allocator in your application, increased RSS, increasd heap usage (because of the many thread local data structures that such allocators try hard to use to ensure good performance, etc etc).
And this is likely happen even if you use the default allocator.

@normanmaurer @chrisvest this is something I believe you will be very interested in

**Comment by linking12** [comment]
> @linking12 and now something "funny" which both me and @nitsanw are painfully much aware
> 
> ![image](https://private-user-images.githubusercontent.com/13125299/362633248-cb13cd7f-2583-43ab-b35e-496c132e6793.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjgwNTgsIm5iZiI6MTcyNDkyNzc1OCwicGF0aCI6Ii8xMzEyNTI5OS8zNjI2MzMyNDgtY2IxM2NkN2YtMjU4My00M2FiLWIzNWUtNDk2YzEzMmU2NzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDEwMzU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNDFhN2JlNTdhNzI0ODM3N2QxZDkyY2IwMzYzMzI4N2JlYWY1NDNlNDIwMTdhZTkyNzljNGU3ZDcxOGQyNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SxRXqye_kjf2eCM0RVkLD5L9SbE3MOYw2ScjjD-5z4Q)
> 
> your application is supposed to "just" use the adaptive allocator, but..as you can see there's some other parts of your application/libraries which don't think the same - causing, likely - to have more than one off-heap allocator instance in your application, (much) increased RSS, increased heap usage (because of the many thread local data structures that such allocators try hard to use to ensure good performance, etc etc). And this is likely happen even if you use the default allocator. This is usually dependent by shading (I see some alibaba shaded deps there), but not only, as you can see at [eclipse-vertx/vert.x#5262](https://github.com/eclipse-vertx/vert.x/pull/5262)
> 
> @normanmaurer @chrisvest this is something I believe you will be very interested in

@franz1981  i fixed code and make sure AdaptiveByteBufAllocator is single;
 so far so good,there is no native memory increase, I will monitor tomorrow to make sure everything is fixed

BTW,  I don't quite understand your question about Alibaba arthas, do you mean mean Arthas can't recognize new Allocator & impact performance?

**Comment by franz1981** [comment]
I mean that you have arenas which belong to other pools, not just the adaptive one. It is something quite visible in the name of the classes, which belong to the non adaptive one.

**Comment by linking12** [comment]
> I mean that you have arenas which belong to other pools, not just the adaptive one. It is something quite visible in the name of the classes, which belong to the non adaptive one.

yes, Alibaba arthas provide monitor by java agent, is a netty server embed in my application

**Comment by franz1981** [comment]
as @normanmaurer said...due to package renaming the risk is that it won't work to just use one...although it seems to me @linking12 you have both a netty pooled one AND the shaded one, in addition to the adaptive.

Said that, is unrelated to this issue, so as soon as you're happy we can close it ;)

**Comment by linking12** [comment]
> as @normanmaurer said...due to package renaming the risk is that it won't work to just use one...although it seems to me @linking12 you have both a netty pooled one AND the shaded one, in addition to the adaptive.
> 
> Said that, is unrelated to this issue, so as soon as you're happy we can close it ;)

I understand what you mean. Upgrading the Netty version of Alibaba Arthas is a difficult task. However, Alibaba Arthas has shaded, so it will not affect the application itself？ In this issue, I observed that the memory does not seem to increase today. I think it has been fixed. I will observe Alibaba Arthas again.
