### ISSUE TITLE
Don't use Netty recyclers for the adaptive ByteBuf pool, but leverage magazine-local ones

### ISSUE THREAD

**Issue by franz1981** [netty/netty#14279]
Currently the adaptive pool is splitting the allocation by:
- creating/reusing an "empty" `AdaptiveByteBuf`, at https://github.com/netty/netty/blob/c0fdb8e9f8f256990e902fcfffbbe10754d0f3dd/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java#L193
- filling it with some complex logic, at https://github.com/netty/netty/blob/c0fdb8e9f8f256990e902fcfffbbe10754d0f3dd/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java#L417

This is nice, but suboptimal for non `FastThreadLocalThread`s as reported at #14272 (see https://github.com/netty/netty/issues/14272#issuecomment-2326620742).

Instead, it would be better to have 2 recyclers:
1. attached to non event-loop magazines - It's fine(ish) to reuse the existing `Recycler` too if we don't want to create an extra type
2. attached to the `Magazine` (lazily) - https://github.com/netty/netty/blob/c0fdb8e9f8f256990e902fcfffbbe10754d0f3dd/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java#L223: which access is already protected by a lock and it allow release to happen from other threads

For the former, just reusing the existing logic is fine - while for the latter it is important to find the appropriate quiescient state to release such.
Clearly the issue will be that an explosion of magazine (due to lack of CPU resources i.e. when the allocators are from a non Netty event loop and they oversubscribe the system) will likely cause an explosion of magazine-locals recyclers - which means more memory; but the benefits, perf-wise should be obvious.

**Comment by franz1981** [comment]
@chrisvest @normanmaurer wdyt?

**Comment by normanmaurer** [comment]
@franz1981 hmm... I wonder why we not always just use the `Recycler` as we do as of today in `PooledByteBufAllocator` ?

**Comment by franz1981** [comment]
@normanmaurer this is because of virtual threads: these threads are supposely abundant and created while never been cached - allocating the whole `ThreadLocal` stuff there will kill perf -> see https://github.com/FasterXML/jackson-core/issues/919

**Comment by normanmaurer** [comment]
@franz1981 also we could just use a methodhandle to check if the thread is virtual or not and based on it use the recycler or not via using `thread. isVirtual()`

**Comment by franz1981** [comment]
@normanmaurer fully agree - it was what i do in other libs - but the problem si that recyclers retain lot of garbage and most of the time higher level frameworks/libs have blocking thread pools as well with TONS of idle threads, which can get destroyed and recreated while active again...
having all of them to retain N direct buffers from being used elsewhere or released, usually cost memory/RSS. 
That's why I prefer users to have a conscious choice and extends FastThreadLocalThread: it means they really need that

**Comment by normanmaurer** [comment]
@franz1981 not sure about that... I think both approaches have trade-offs . That said I am looking forward to see a PR with your ideas :)

**Comment by chrisvest** [comment]
If magazines can directly recycle AdaptiveByteBufs without the traditional Recycler machinery, then we could perhaps also reduce some of the event-loop special-case code in the allocator.

I don't understand the "explosion of magazines" problem that you are anticipating, @franz1981. The ByteBufs being recycled or not should not impact the number of magazines floating around, no?

**Comment by franz1981** [comment]
Let's say you have a blocking thread pool which grows due to a sudden burst of parallel work, it "could" cause magazine expansion due to 3 failures in a row to acquire the stamped lock; if later one these thread pool die, given that the buffer wrappers doesn't belong to them, they won't GC'd but will still be bound to the newly allocated magazine.

**Comment by franz1981** [comment]
@chrisvest if you are fine with this proposal - which I believe you got perfectly despite my poor language to explain it - fell free to send a PR or I will do it in the next week(s)...sadly right now I'm a bit overwhelmed...
The good thing of this is that recycling can be made fast like this, for ANY thread, including virtual ones, and will compensate with https://github.com/netty/netty/pull/14322 which had a performance impact - atomic ops in the hot path are never free (!)

**Comment by normanmaurer** [comment]
I think the "downside" of this approach would be:

- AdapativeByteBuf pooling will be per magazine, which might result into more objects pooled.
- The queue that is used for pooling would need to be MPSC as the offer might happen from any thread (there is no guarantees on which thread might call `release(...)`. 

I am not saying its worse then what we have as of today but something to keep in mind.

**Comment by franz1981** [comment]
yeah @normanmaurer fully agree on both points; My suggestion was to let any threads (virtual, event loops, whatever) to have the same mechanism to recycle such `AdapativeByteBuf`.
Virtual threads cannot really use `ThreadLocal`s for pooling if not with big performance problems and not using pooling is equally bad...
