### ISSUE TITLE
Cannot Change allowPartialChunks in HttpDecoderConfig

### ISSUE THREAD

**Issue by ByeongUkChoi** [netty/netty#14309]
Description:

I would like to change the `allowPartialChunks` value of HttpDecoderConfig to false. However, since the `HttpDecoderConfig` is created with the default value of true in the `HttpServerCodec` constructor (e.g., `new HttpDecoderConfig()`), there seems to be no way to modify this value directly.

As a workaround, I had to use reflection to forcibly change the `allowPartialChunks` value, but this doesn’t seem like the ideal approach. Is there a recommended way to set allowPartialChunks to false when using Spring or Netty?

Additional Context:

I am using Netty in a Spring-based project, and I’m trying to find a more elegant solution than using reflection. Any guidance or suggestions on how to handle this configuration change properly would be appreciated.

Thank you for your help.

**Comment by freeyob** [comment]
You could  build your HttpDecoderConfig and pass it to HttpServerCodec constructor.
https://github.com/netty/netty/blob/139d442f127fd0af853d1750621ca8eaa59d4ae3/codec-http/src/main/java/io/netty/handler/codec/http/HttpServerCodec.java#L146-L148

**Comment by violetagg** [comment]
@ByeongUkChoi Do you use Netty via Reactor Netty when in Spring?

**Comment by ByeongUkChoi** [comment]
@violetagg Yes. I use Reactor Netty

**Comment by freeyob** [comment]
There is a method to replace HttpServerCodec when initializing the HttpServer. Hope this helps you.
```java
HttpServer.create().doOnChannelInit(new ChannelPipelineConfigurer() {
	@Override
	public void onChannelInit(ConnectionObserver observer, Channel channel, SocketAddress socketAddress) {
		HttpDecoderConfig config = new HttpDecoderConfig();
		config.setAllowPartialChunks(false);
		channel.pipeline().replace("HttpServerCodec", "MyHttpServerCodec", new HttpServerCodec(config));
	}			
});

**Comment by violetagg** [comment]
> @violetagg Yes. I use Reactor Netty. So here is: https://github.com/reactor/reactor-netty/blob/main/reactor-netty-http/src/main/java/reactor/netty/http/server/HttpServerConfig.java#L802

@ByeongUkChoi I would recommend you to open a feature request in Reactor Netty issue tracker. We can add this configuration so that you will not need to do anything in addition.
