### ISSUE TITLE
Can ctx.write ensure that msg will be released in any case?

### ISSUE THREAD

**Issue by dpy1123** [netty/netty#14339]
The problem is that we called ctx.write() but still get the leak report in the log.
Full leak stacktrace is same as #14335  , here is the releated call trace.
```
   Hint: 'h2c-upgrade' will handle the message from this point.
   io.netty.buffer.AdvancedLeakAwareCompositeByteBuf.touch(AdvancedLeakAwareCompositeByteBuf.java:36)
   io.netty.handler.codec.http.HttpObjectAggregator$AggregatedFullHttpMessage.touch(HttpObjectAggregator.java:363)
   io.netty.handler.codec.http.HttpObjectAggregator$AggregatedFullHttpRequest.touch(HttpObjectAggregator.java:443)
   io.netty.handler.codec.http.HttpObjectAggregator$AggregatedFullHttpRequest.touch(HttpObjectAggregator.java:393)
   io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:115)
   io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:978)
   io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868)
   io.netty.handler.timeout.WriteTimeoutHandler.write(WriteTimeoutHandler.java:112)
   io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:893)
   io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875)
   io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984)
   io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868)
   io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:305)
   io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:891)
   io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:875)
   io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:984)
   io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:868)
   io.github.tesla.gateway.netty.transmit.connection.ProxyConnection.writeHttp(ProxyConnection.java:248)
```

This happens when upstream service is overloaded and maybe in shutdown period, I'm assuming the channel is disconnect. 
Since ChannelOutboundBuffer will track all unflushed buffers and will release all unflushed buffers when close, I'm assuming if I called ctx.write(msg), netty will release this msg in any case. Am I right?
And we have FlushConsolidationHandler in pipeline to reduce the flush times, is that releated to this leak?

'h2c-upgrade' is a HttpClientUpgradeHandler, in the leak trace we can confirm upgrade is done, and the handler should remove itself from pipeline , but still shows in the leak trace. that's another weird thing.

**Comment by normanmaurer** [comment]
@dpy1123 yes you are right if it reach the `outboundBuffer` it will be released. So it must get "lost" somewhere in the pipeline.

**Comment by linking12** [comment]
@normanmaurer  we think this get "lost"
```
private void invokeWrite0(Object msg, ChannelPromise promise) {
        try {
            // DON'T CHANGE
            // Duplex handlers implements both out/in interfaces causing a scalability issue
            // see https://bugs.openjdk.org/browse/JDK-8180450
            final ChannelHandler handler = handler();
            final DefaultChannelPipeline.HeadContext headContext = pipeline.head;
            if (handler == headContext) {
                headContext.write(this, msg, promise);
            } else if (handler instanceof ChannelDuplexHandler) {
                ((ChannelDuplexHandler) handler).write(this, msg, promise);
            } else if (handler instanceof ChannelOutboundHandlerAdapter) {
                ((ChannelOutboundHandlerAdapter) handler).write(this, msg, promise);
            } else {
                ((ChannelOutboundHandler) handler).write(this, msg, promise);
            }
        } catch (Throwable t) {
            notifyOutboundHandlerException(t, promise); //get Lost
        }
    }
```

and we want to change our code to avoid this situation；

```
channelFutureListener = new ChannelFutureListener() {
                @Override
                public void operationComplete(ChannelFuture future) throws Exception {
                        if (future.isSuccess()) {
                            
                        } else {
                            if (future.cause() != null) {
                                ReferenceCountUtil.safeRelease(httpRequest);
                            }
                        }
                }
            };
```

do you have any suggestion?  i think future.cause() instanceof *** is a good sulution;

**Comment by normanmaurer** [comment]
I think I found the leak https://github.com/netty/netty/pull/14342 ... It seems like you are writing another request while the upgrade is still in progress for which we fail the promise but didn't correctly release the message

**Comment by normanmaurer** [comment]
@linking12 no.. I think it was a bug in our handler

**Comment by normanmaurer** [comment]
That said I think you trigger it because you write more then one requests

**Comment by linking12** [comment]
> That said I think you trigger it because you write more then one requests

yes, when we ugrade success, we will write more than one requsts, because we want to use http2 multiplex

**Comment by normanmaurer** [comment]
@linking12 you need to wait until the upgrade is done before doing this. For example by observing that the `UpgradeEvent.UPGRADE_SUCCESSFUL` was received in `userEventTriggered(...)`

**Comment by linking12** [comment]
> @linking12 you need to wait until the upgrade is done before doing this. For example by observing that the `UpgradeEvent.UPGRADE_SUCCESSFUL` was received in `userEventTriggered(...)`

@normanmaurer  
We currently consider upgrade successful when we have received the first response,  so this is wrong?

I don't quite understand it. Logically, a remote call has been made and the server has returned response for the upgrade request.

**Comment by normanmaurer** [comment]
there is an event that is fired by the client handler that you should inspect and only after that writing the second request.

**Comment by dpy1123** [comment]
hi @normanmaurer Just wondering when 4.1.114.Final will be released? Do you have an approximate date? thx

**Comment by normanmaurer** [comment]
@dpy1123 next week
