### ISSUE TITLE
TLS 1.3 Renegotiation in SslHandler is Succeeding (It Should Fail)

### ISSUE THREAD

**Issue by aronee2008** [netty/netty#14345]
### Expected behavior
Renegotiation in TLS 1.3 should fail because TLS 1.3 does not support renegotiation, as per the RFC specification.

### Actual behavior
Renegotiation succeeds without any failure or exception, even though TLS 1.3 should prevent this operation.

### Steps to reproduce

Change the TLS version for the client and the server `SslContext` to use v1.3 and run the below unit test via mvn 
https://github.com/netty/netty/blob/4.1/handler/src/test/java/io/netty/handler/ssl/RenegotiateTest.java

It seems that SslHandler.renegotiate() should throw an exception or fail silently in TLS 1.3 contexts, but currently, it allows renegotiation.

### JVM version (e.g. `java -version`)
openjdk version "17.0.12" 2024-07-16

### OS version (e.g. `uname -a`)
macos arm64

**Comment by normanmaurer** [comment]
It fails the future when using our native implementation. When using the JDK implementation it does not fail as `beginHandshake()` does not throw.  There is nothing we can do about this in netty as `SSLEngineImpl` is part of the JDK
