### ISSUE TITLE
Is that possible to avoid SSLEngineResult objects allocation in SslHandler?

### ISSUE THREAD

**Issue by doom369** [netty/netty#14355]
Hello. In our recent extreme performance tests, along with `MqttDecoder$Result` , which we try to fix [here](https://github.com/netty/netty/pull/14343) and [here](https://github.com/netty/netty/pull/14349), we found out that netty also allocates many SSLEngineResults:

![image](https://github.com/user-attachments/assets/6968a40a-4490-4699-9b27-f0f406e4bf77)

The request rate for the above test is only 50k req/sec and the presence of `SSLEngineResults` seems a bit high. Is that possible to avoid this allocation? WDYT?

We use an OpenSSL provider with boring SSL in our tests:

```
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-epoll</artifactId>
            <version>4.1.113.Final</version>
            <classifier>linux-x86_64</classifier>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>2.0.66.Final</version>
            <classifier>linux-x86_64</classifier>
        </dependency>
```

OpenJDK 21.0.4, Ubuntu 24.04.

**Comment by chrisvest** [comment]
The class is immutable (no instance reuse) and part of the JDK API. It'd be a lot of work to avoid. It's a perfect candidate for a value type, though 😬
