### ISSUE TITLE
Increased modularity of netty-codec is backward incompatible change for 4.1

### ISSUE THREAD

**Issue by idelpivnitskiy** [netty/netty#14371]
Change made in #14241 to address #14239 is a breaking change for libraries that depend on any classes from protobuf/marshalling/compression packages of `netty-codec`.

As an example, it broke the pipeline we use in ServiceTalk to validate compatibility with the latest Netty 4.2 snapshots: https://github.com/apple/servicetalk/actions/runs/11032862432/job/30646115309

If we proceed with this change, the 4.2 release will be much harder to adopt and require intervention (build/dependencies manipulation) from application owners because libraries won't be able to make themselves compatible with both 4.1 and 4.2 netty releases at the same time.

Imho, this change should wait for 5.0.

**Comment by vietj** [comment]
@idelpivnitskiy to understand correctly, does fixing this implies more than adding missing dependencies ?

**Comment by idelpivnitskiy** [comment]
Correct, to make it work I have to add `io.netty:netty-codec-compression` dependency for our `servicetalk-encoding-netty` module. However, it makes a hard dependency on netty 4.2 and does not allow me to keep ServiceTalk compatible with both 4.1 and 4.2 at the same time.

Alternatively, we can keep it split into smaller modules, but still add `netty-codec-compression` (and others) as a dependency for `netty-codec`. That way users classpath that depends on `netty-codec` won't change.

**Comment by vietj** [comment]
Compression codecs are quite usually used by `netty-codec-http` and the current Maven dependency onto `netty-codec-compression` is marked as _optional_ because it is possible to use HTTP codecs without compression.

As compression seems in practice widely used when using HTTP, we could make waive the optionality and thus a dependency on `netty-codec-http` would transitively bring `netty-codec-compression` out of the box.

If that option is not enough, another option would be to rename the `netty-codec` to something like `netty-codec-base` and have `netty-codec` depend on `netty-codec-base` + `netty-codec-compression` + `netty-codec-protobuf` + ... and keep the finer grained modularity we achieved.

**Comment by idelpivnitskiy** [comment]
I'm agreed with your rational about reducing dependencies and ppl using HTTP without compression, etc.

My main concern is that it will require a lot (!!!) of efforts to migrate users across many projects from 4.1 to 4.2 if we change classpath components. Migration will take forever and users will hate us bcz these days netty is pretty much everywhere.

> As compression seems in practice widely used when using HTTP, we could make waive the optionality and thus a dependency on netty-codec-http would transitively bring netty-codec-compression out of the box.

This won't work for ServiceTalk because our `servicetalk-encoding-netty` does not depend on HTTP, it only depends on `netty-codec`.

Your idea of "empty" `netty-codec` to depend on `netty-codec-base` + `netty-codec-compression` + `netty-codec-protobuf` + `netty-codec-marshalling` is even better than my original proposal of `netty-codec` to depend on `netty-codec-*`. I double checked and realized that `netty-codec-compression` depends on `netty-codec`. Your idea will avoid circular dependency.

**Comment by normanmaurer** [comment]
> I'm agreed with your rational about reducing dependencies and ppl using HTTP without compression, etc.
> 
> My main concern is that it will require a lot (!!!) of efforts to migrate users across many projects from 4.1 to 4.2 if we change classpath components. Migration will take forever and users will hate us bcz these days netty is pretty much everywhere.
> 
> > As compression seems in practice widely used when using HTTP, we could make waive the optionality and thus a dependency on netty-codec-http would transitively bring netty-codec-compression out of the box.
> 
> This won't work for ServiceTalk because our `servicetalk-encoding-netty` does not depend on HTTP, it only depends on `netty-codec`.
> 
> Your idea of "empty" `netty-codec`(like `netty-all`) to depend on `netty-codec-base` + `netty-codec-compression` + `netty-codec-protobuf` + `netty-codec-marshalling` is even better than my original proposal of `netty-codec` to depend on `netty-codec-*`. I double checked and realized that `netty-codec-compression` depends on `netty-codec`. Your idea will avoid circular dependency.

I agree... The 3rd proposal of @vietj sounds like the way to go.

**Comment by vietj** [comment]
I'll make a PR for this @normanmaurer

**Comment by idelpivnitskiy** [comment]
Works as expected now: https://github.com/apple/servicetalk/actions/runs/11276735486/job/31361248993
Thank you @vietj!
