### ISSUE TITLE
OpenJdkSelfSignedCertGenerator is not compatible with JDK 20+

### ISSUE THREAD

**Issue by cushon** [netty/netty#14403]
`OpenJdkSelfSignedCertGenerator` reflectively loads `sun.security.x509.X509CertInfo#set(String, Object`):

https://github.com/netty/netty/blame/29bab2e58cca629939cd92a7ccc0bd08ec1c2d7f/handler/src/main/java/io/netty/handler/ssl/util/OpenJdkSelfSignedCertGenerator.java#L72

When running on JDK 20 and newer, that method does not exist. It was removed in this JDK change: https://github.com/openjdk/jdk/commit/671f84bd8625ea7e06fa8272ae629309df06e9ca#diff-df66d4b8841387e9f2526d362daed107617360a50ec3e7a2fc19b91f74f778d9L166

This causes failures like the following:

```
Caused by: java.lang.UnsupportedOperationException: OpenJdkSelfSignedCertGenerator not supported on the used JDK version
	at io.netty.handler.ssl.util.OpenJdkSelfSignedCertGenerator.generate(OpenJdkSelfSignedCertGenerator.java:167)
```

**Comment by chrisvest** [comment]
That's why you can add `org.bouncycastle:bcpkix-jdk18on:1.78.1` or newer to your dependencies and `SelfSignedCertificate` will use that instead.
