### ISSUE TITLE
None recovering Redis command timed out

### ISSUE THREAD

**Issue by mshahmoradi87** [netty/netty#14401]
### Expected behavior
the expected behaviour is that with periodic_refresh, the issue does not persist. 

### Actual behavior
we have started to use aws redis serveless, since the switch from redis cluster-mode enabled to redis serverless, out of the blue one client from many tasks running starts to have command timed out continuously. Depending on the service and size of objects and if put or get commands are being timed out, we see different side effects, sometimes it results in [OOM](https://github.com/redis/lettuce/issues/705), sometimes only increased latency. 

Note that in the services this happens, usually there are more than 12 tasks running, and only one container has this issue. 

I could correlate any CPU spike with the event causing the timeouts. 
### Steps to reproduce
this is reoccurring in production env in different services, but I don't know how this can be reproduced. 

### Versions and Config

<lettuce.version>6.3.2.RELEASE</lettuce.version>
<netty.version>4.1.109.Final</netty.version>

related configurations:
  ssl: true
  timeout: 5s
  connect-timeout: 500ms
  additional:
    dns-ttl: 5s
    periodic-refresh: 10s
    reconnect-delay-min: 100ms
    reconnect-delay-max: 5s
    read-from: replicaPreferred
    
 ### Possible related issues
 
 [RedisCommandTimeoutException intermittently](https://github.com/redis/lettuce/issues/757):
 in some cases this could be related, as we sometimes see timeouts for a minute, and they are recovered, however in this case it persists. 

[Lettuce cannot recover from connection problems](https://github.com/redis/lettuce/issues/1428):
maybe setting TCP_USER_TIMEOUT would help, default is 1 minutes, so for the recovering case, maybe this helps, but for the cases that this continues and gets stacked probably not.

**Comment by normanmaurer** [comment]
This is a Lucette question / issue

**Comment by mshahmoradi87** [comment]
> This is a lettuce question / issue

no this is a bug, what do I need to provide ?
