### ISSUE TITLE
Use Java `ThreadLocal` instead of `FastThreadLocal` on java 21+?

### ISSUE THREAD

**Issue by Munoon** [netty/netty#14408]
Do we actually need this? I've ran the `FastThreadLocalFastPathBenchmark` on Java 21 and it looks like Java's ThreadLocal is actually faster (and the difference is significant):
```
Benchmark                                            Mode  Cnt       Score      Error  Units
FastThreadLocalFastPathBenchmark.fastThreadLocal    thrpt   20  194154.530 ± 6684.777  ops/s
FastThreadLocalFastPathBenchmark.jdkThreadLocalGet  thrpt   20  130341.051 ± 9331.542  ops/s
```
Does this benchmark repeats to you?

P.S.: I'm not sure how accurate it is, but I've also tried running this benchmark inside the `FastThreadLocalThread`, and the result was still worse.

**Comment by chrisvest** [comment]
Your benchmark says FastThreadLocal achieves more operations per second, though?

**Comment by Munoon** [comment]
Yeah, sorry. I didn't realise that you are using throughput instead of average time. Closing it.
