### ISSUE TITLE
Inconsistencies in certificate behavior in Netty.

### ISSUE THREAD

**Issue by codekrolik2** [netty/netty#14419]
### Expected behavior
N/A

### Steps to reproduce

Hello guys, I'd like to understand whether the behavior shown below is expected and there is some logic behind it, or it's inconsistent (that's the way it looks to me).

To reproduce, we're using 2 certificates, one with private key
	- ca.crt
	- test.crt, test.key
, where "test.crt" is signed by "ca.crt".
[certificates.zip](https://github.com/user-attachments/files/17533300/certificates.zip)

Let's review 4 scenarios, each presenting a unique behavior:

1.1) Mutual TLS
	- Client is using
		KeyManagerFactory with { "test.crt", "test.key" }
		InsecureTrustManagerFactory.INSTANCE
	-Server is using
		new SelfSignedCertificate();
		TrustManagerFactory with { **"test.crt"** }
	
	Behavior - TLS handshake error on server "Empty client certificate chain"

1.2) Mutual TLS
	- Client is using         
		KeyManagerFactory with { "test.crt", "test.key" }
		InsecureTrustManagerFactory.INSTANCE
	-Server is using
		new SelfSignedCertificate();
		TrustManagerFactory with { **"ca.crt"** }
	
	Behavior - works normally

2.1) One-way TLS
	- Client is using         
		TrustManagerFactory with { **"test.crt"** }
	-Server is using
		KeyManagerFactory with { "test.crt", "test.key" }
	
	Behavior - works normally

2.2) One-way TLS
	- Client is using         
		TrustManagerFactory with { **"ca.crt"** }
	-Server is using
		KeyManagerFactory with { "test.crt", "test.key" }
	
	Behavior - TLS handshake error on client "Extended key usage does not permit use for TLS server authentication"

### Minimal yet complete reproducer code (or URL to code)
N/A

### Netty version
4.1

### JVM version (e.g. `java -version`)
openjdk version "17.0.12" 2024-07-16

### OS version (e.g. `uname -a`)
Linux dev1 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by chrisvest** [comment]
```
1.1) Mutual TLS
- Client is using
KeyManagerFactory with { "test.crt", "test.key" }
InsecureTrustManagerFactory.INSTANCE
-Server is using
new SelfSignedCertificate();
TrustManagerFactory with { "test.crt" }

Behavior - TLS handshake error on server "Empty client certificate chain"
```

Correct. Server requests a cert path from the client, and that request includes a list of CAs that will be accepted. In this case server thinks `test.crt` is a CA. The client will then be looking for a cert that is issued by `test.crt` and finds none, hence returns an empty cert path that the server rejects.

```
1.2) Mutual TLS
- Client is using
KeyManagerFactory with { "test.crt", "test.key" }
InsecureTrustManagerFactory.INSTANCE
-Server is using
new SelfSignedCertificate();
TrustManagerFactory with { "ca.crt" }

Behavior - works normally
```

Correct. You configured stuff correctly.

```
2.1) One-way TLS
- Client is using
TrustManagerFactory with { "test.crt" }
-Server is using
KeyManagerFactory with { "test.crt", "test.key" }

Behavior - works normally
```

Correct. The client considers `test.crt` to be a Trust Anchor, and can thus immediately trust it without doing any validation. This is effectively certificate pinning.

```
2.2) One-way TLS
- Client is using
TrustManagerFactory with { "ca.crt" }
-Server is using
KeyManagerFactory with { "test.crt", "test.key" }

Behavior - TLS handshake error on client "Extended key usage does not permit use for TLS server authentication"
```

Correct. The `test.crt` only include `TLS Web Client Authentication` in its extended key usage, so the server is not allowed to use this cert and the client refuses to validate it.

**Comment by codekrolik2** [comment]
@chrisvest Just to get this straight, according to you, 

1.1 In this case server thinks test.crt is a CA. The client will then be looking for a cert that is issued by test.crt and finds none, hence returns an empty cert path that the server rejects.

and

2.1 The client considers test.crt to be a Trust Anchor, and can thus immediately trust it without doing any validation. This is effectively certificate pinning. 

is not inconsistent?

**Comment by chrisvest** [comment]
@codekrolik2 the protocol is _not_ symmetric between client and server. The server always sends the cert you configure, so the client can check it. The other way, clients only send certs when requested, and the request includes what CAs are accepted, _most clients_ will not include those CAs in the returned list of certs because the CA should already be known to both peers. Then you end up with an empty path, which is an error. Clients and servers are different in important ways, and it shows like this in your tests.

**Comment by codekrolik2** [comment]
Ok, I was just making sure that it's expected behavior when client does certificate pinning, and server doesn't. 
What I read above is that there is no consistency that's expected between the behaviour of similar concepts on server and client.
Therefore, I shouldn't expect server to pin client certificates - it's expected that server won't pin, even though I can pin server certificates on the client.

@chrisvest Apparently to achieve similar pinning logic on server I need to implement a custom TLS handshake handler?

Thanks!
