### ISSUE TITLE
Epoll.isAvailable() returns false on Ubuntu 20.04 arch amd64

### ISSUE THREAD

**Issue by violetagg** [netty/netty#14410]
### Expected behavior
`Epoll.isAvailable()` returns `true` on Ubuntu 20.04 arch amd64

### Actual behavior
`Epoll.isAvailable()` returns `false` on Ubuntu 20.04 arch amd64

### Minimal yet complete reproducer code (or URL to code)
https://github.com/violetagg/netty-missing-natives-snapshot

The project has `devcontainers` configuration
* Run the project using `devcontainers` feature
* In terminal go to folder `IdeaProjects/netty-missing-natives-snapshot/`
* Execute `./mvnw test`

The project has configurations for `amd64` and `arm64`
The issue is observed only on `amd64`

### Netty version
4.1.115.Final-SNAPSHOT

### JVM version (e.g. `java -version`)
JDK 8

### OS version (e.g. `uname -a`)
Ubuntu 20.04

**Comment by normanmaurer** [comment]
will check

**Comment by normanmaurer** [comment]
FYI it fails with:

```
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libnetty_transport_native_epoll_x86_644739745466547630269.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.35' not found (required by /tmp/libnetty_transport_native_epoll_x86_644739745466547630269.so)

```

**Comment by normanmaurer** [comment]
This is super strange as we build with centos6 which has a much older glibc... investigating

**Comment by normanmaurer** [comment]
@violetagg should be fixed by https://github.com/netty/netty/pull/14450

**Comment by violetagg** [comment]
@normanmaurer Thanks!
