### ISSUE TITLE
javax.net.ssl.SSLException: error:1000045c:SSL routines:OPENSSL_internal:TLSV1_ALERT_CERTIFICATE_REQUIRED

### ISSUE THREAD

**Issue by SujathaHitnal** [netty/netty#14417]
### Expected behavior
We have service connecting to temporal service using temporal SDK via SSL and is using netty for SSL communication internally.
Client certs are generated using SHA384WITHECDSA using temporal cloud cli.
It works fine when used with jdk image however fail when service is built using jdk fips chainguard image with below error

****2","level":"TRACE","level_value":5000,"stack_trace":"java.security.cert.CertPathValidatorException: Signature algorithm 'SHA384WITHECDSA' not permitted with given parameters\n\tat**** 

Is something wrong with the algorithm used or anything else which can be found from log?

Fr-Oct-18-2024,11:03 [measurement-coordinator-deployment-6f8ccbc4f5-rgrt9] {"@timestamp":"2024-10-18T11:03:34.326147777Z","@version":"1","message":"Caught a connection error","logger_name":"io.grpc.netty.shaded.io.grpc.netty.NettyClientHandler","thread_name":"grpc-default-worker-ELG-1-3","level":"DEBUG","level_value":10000,"stack_trace":"io.grpc.netty.shaded.io.netty.handler.codec.DecoderException: j**avax.net.ssl.SSLException: error:1000045c:SSL routines:OPENSSL_internal:TLSV1_ALERT_CERTIFICATE_REQUIRED\n\tat** io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:499)\n\tat io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)\n\tat io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)\n\tat io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n\tat io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\tat io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)\n\tat io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\tat io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)\n\tat io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)\n\tat io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)\n\tat io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)\n\tat io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\nCaused by: javax.net.ssl.SSLException: error:1000045c:SSL routines:OPENSSL_internal:TLSV1_ALERT_CERTIFICATE_REQUIRED\n\tat 

failed","logger_name":"org.bouncycastle.jsse.provider.ProvX509KeyManager","thread_name":"grpc-default-executor-2","level":"TRACE","level_value":5000,"stack_trace":"java.security.cert.CertPathValidatorException: Signature algorithm 'SHA384WITHECDSA' not permitted with given parameters\n\tat org.bouncycastle.jsse.provider.ProvAlgorithmChecker.checkIssued(ProvAlgorithmChecker.java:263)\n\tat org.bouncycastle.jsse.provider.ProvAlgorithmChecker.checkChain(ProvAlgorithmChecker.java:206)\n\tat org.bouncycastle.jsse.provider.ProvX509KeyManager.isSuitableChain(ProvX509KeyManager.java:807)\n\tat org.bouncycastle.jsse.provider.ProvX509KeyManager.getKeyTypeQuality(ProvX509KeyManager.java:598)\n\tat org.bouncycastle.jsse.provider.ProvX509KeyManagerSimple.getPotentialMatch(ProvX509KeyManagerSimple.java:290)\n\tat org.bouncycastle.jsse.provider.ProvX509KeyManagerSimple.getBestMatch(ProvX509KeyManagerSimple.java:258)\n\tat org.bouncycastle.jsse.provider.ProvX509KeyManagerSimple.chooseAlias(ProvX509KeyManagerSimple.java:160)\n\tat org.bouncycastle.jsse.provider.ProvX509KeyManagerSimple.chooseEngineClientAlias(ProvX509KeyManagerSimple.java:97)\n\tat io.grpc.netty.shaded.io.netty.handler.ssl.OpenSslKeyMaterialManager.chooseClientAlias(OpenSslKeyMaterialManager.java:126)\n\tat io.grpc.netty.shaded.io.netty.handler.ssl.OpenSslKeyMaterialManager.setKeyMaterialClientSide(OpenSslKeyMaterialManager.java:95)\n\tat io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$OpenSslClientCertificateCallback.handle(ReferenceCountedOpenSslClientContext.java:266)\n\tat io.grpc.netty.shaded.io.netty.internal.tcnative.CertificateCallbackTask.runTask(CertificateCallbackTask.java:40)\n\tat io.grpc.netty.shaded.io.netty.internal.tcnative.SSLTask.run(SSLTask.java:48)\n\tat io.grpc.netty.shaded.io.netty.internal.tcnative.SSLTask.run(SSLTask.java:42)\n\tat io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.runAndResetNeedTask(ReferenceCountedOpenSslEngine.java:1496)\n\tat io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.access$700(ReferenceCountedOpenSslEngine.java:94)\n\tat io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine$TaskDecorator.run(ReferenceCountedOpenSslEngine.java:1471)\n\tat io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler$SslTasksRunner.run(SslHandler.java:1787)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat

**Comment by normanmaurer** [comment]
As far as I know `SHA384WITHECDSA` is not supported when using fips. You will need to chose something supported.
