### ISSUE TITLE
Gradle build failing on linux/aarch64 (arm64) machine due to EpollEventLoopGroup Class not defined. 

### ISSUE THREAD

**Issue by nix1n** [netty/netty#14431]
### Expected behavior
Gradle build should succeed if OS is same on which the build is done. 
### Actual behavior
Gradle build is sucessfull on linux/x86_64 machines with same OS Ubuntu 22.04.3 LTS . But fails on linux/aarach64 machine with same OS. 

Most of the test cases are failing with 
`Caused by: java.lang.NoClassDefFoundError at EpollEventLoopGroup.java:189`
### Steps to reproduce
In a private Java repo. But can provide necessary info if asked. Wasn't sure what to provide. Can provide dependencies used in build.gradle file.  
### Minimal yet complete reproducer code (or URL to code)
N/A
### Netty version
4.1.106.Final
### JVM version (e.g. `java -version`)
openjdk version "21.0.2" 2024-01-16 LTS
OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)
### OS version
Ubuntu 22.04.3 LTS

**Comment by slandelle** [comment]
It could be anything, including a corrupted cached jar on your side. Please provide a [reproducer](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by normanmaurer** [comment]
Also please upgrade to latest version

**Comment by nix1n** [comment]
Hey @slandelle thanks for your reply. I am still trying to build a minimal reproducible code (it's a large private repo, many org specific dependencies also, so still trying) . 
Though I have one update, when I tried to find jar files in my ARM64(aarch64) machine, I found jar file for linux-x86_64 arch instead of linux-aarch64. 
Could it be the case ?
How to fix it ? Do we have to explicitly mention aarch of dependency in build.gradle dependency file or something like that , if that's the reason ?
![iScreen Shoter - Warp - 241111105058](https://github.com/user-attachments/assets/2bb578fb-51ff-413d-b815-32f58ab183b6)

# find / -name "*jar*" | grep epoll
/root/.gradle/caches/modules-2/files-2.1/io.netty/netty-transport-classes-epoll/4.1.99.Final/961bd5b8d97ea6a07168176462f398089a24b5c8/netty-transport-classes-epoll-4.1.99.Final.jar
/root/.gradle/caches/modules-2/files-2.1/io.netty/netty-transport-classes-epoll/4.1.112.Final/67e590356eb53c20aaabd67f61ae66f628e62e3d/netty-transport-classes-epoll-4.1.112.Final.jar
/root/.gradle/caches/modules-2/files-2.1/io.netty/netty-transport-classes-epoll/4.1.106.Final/c058d5c712e00e8560e519970b3d27747778b8f2/netty-transport-classes-epoll-4.1.106.Final.jar
/root/.gradle/caches/modules-2/files-2.1/io.netty/netty-transport-native-epoll/4.1.106.Final/dd717a7c6558bc977209f5c10666e5d165f5a045/netty-transport-native-epoll-4.1.106.Final-linux-x86_64.jar
# uname -m
aarch64`

**Comment by nix1n** [comment]
Hey @normanmaurer what is the latest version , I suppose 4.1.114.Final ? 
even for this I don't see any jar file available for linux-aarch64 .
https://repo.maven.apache.org/maven2/io/netty/netty-transport-native-epoll/4.1.114.Final/netty-transport-native-epoll-4.1.114.Final-linux-aarch64.jar 
but it's only avaiable for linux-x86_64,
https://repo.maven.apache.org/maven2/io/netty/netty-transport-native-epoll/4.1.114.Final/netty-transport-native-epoll-4.1.114.Final-linux-x86_64.jar

**Comment by nix1n** [comment]
@slandelle Thanks for this info. Wanted to know if this is wrong convention or right ? 
On machine it's aarch64 and for x86_64 there is an underscore , why we have released jars with names like this ?
Now I have to just put the dependency explicitly like this which seems weird and non-generic .

![iScreen Shoter - Code - 241111163429](https://github.com/user-attachments/assets/74f63f85-6200-4c66-9048-ba006139022c)
![iScreen Shoter - Warp - 241111163042](https://github.com/user-attachments/assets/d225c6c4-31bd-47d7-b525-e002472114df)

**Comment by slandelle** [comment]
> Wanted to know if this is wrong convention or right ?

I can't tell, I'm not part of the core team here. @normanmaurer would know.

Then, IMHO you'll have to live with the existing convention because changing it would be a breaking change.
