### ISSUE TITLE
Is it possible to use Offheap ByteBuf instead of Java object for http header?

### ISSUE THREAD

**Issue by linking12** [netty/netty#14430]
For http1.1, header expansion is one of the main reasons for its criticism , so Hpack compression was introduced;
We have also recently encountered some problems where large headers caused the application throughput to not improve;

1: Is it possible to use Offheap ByteBuf instead of Java object for http header？
2: also provide a way to encode the header of interest into a Java object？

This approach will be very friendly to the proxy side, such as applications such as zuul2;

**Comment by franz1981** [comment]
Hi @linking12 can you point to the relevant part of Netty you mean?
I have been the one which has re-implemented the line and header decoding of http 1.1 in Netty and I would like to better understand your suggestion 🙏 
I have opted there to use an uncooked sketch on heap buffer (per decoder instance): are you suggesting to avoid the copy off to heap and just do it on the off-heap one?
Or it is instead related the encoding side where we don't know upfront the required capacity of the buffer while encoding the headers and we have to guess it (at the risk of expanding it)?

**Comment by franz1981** [comment]
in your case I would probably avoid creating the usual full http object as a whole and avoid having headers multi maps and similar; I am one of the maintainers of Hyperfoil (a load generator) and we have our own http handler which perform partial zero garbage decoding, although let's remember that incoming data can  arrive in chunks (on the network based on the MTU size( and there is still some need to retain some state in this case, hence performing some copy.
In the Netty decoder case I have a version which try hard not performing the copy but we have to eventually materialize the header names and and values as AsciiString (if not known) - which will be the next bottleneck to solve, again.

**Comment by linking12** [comment]
> in your case I would probably avoid creating the usual full http object as a whole and avoid having headers multi maps and similar; I am one of the maintainers of Hyperfoil (a load generator) and we have our own http handler which perform partial zero garbage decoding, although let's remember that incoming data can arrive in chunks (on the network based on the MTU size) and there is still some need to retain some state in this case, hence performing some copy. In the Netty decoder case I have a version which try hard not performing the copy but we have to eventually materialize the header names and and values as AsciiString (if not known) - which will be the next bottleneck to solve, again.

yes, avoid creating the usual full http object as a whole is good choice，I have considered it, but I  worried that it will bring greater risks. It seems that I need to re-evaluate; 

thanks;
