### ISSUE TITLE
BouncyCastlePemReader has hardcoded dependency on non FIPS compliant version of BouncyCastle

### ISSUE THREAD

**Issue by jwojcie** [netty/netty#14455]
### Expected behavior
Similar to change made in https://github.com/netty/netty/blob/04f9b4a827d992ad439823eeba85d65d3a89c265/handler/src/main/java/io/netty/handler/ssl/util/BouncyCastleSelfSignedCertGenerator.java#L45

### Actual behavior
https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/BouncyCastlePemReader.java#L80 has hard coded dependency on non FIPS-140 compliant version of BC. In result it blows up in the FIPS compliant environment where only BC FIPS is available and where BC non FIPS can't be used.

```
FINE: Cannot load Bouncy Castle provider
java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at io.netty.handler.ssl.BouncyCastlePemReader$1.run(BouncyCastlePemReader.java:80)
	at io.netty.handler.ssl.BouncyCastlePemReader$1.run(BouncyCastlePemReader.java:73)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.handler.ssl.BouncyCastlePemReader.tryLoading(BouncyCastlePemReader.java:73)
	at io.netty.handler.ssl.BouncyCastlePemReader.isAvailable(BouncyCastlePemReader.java:60)
	at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1178)
	at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1166)
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:391)
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:333)
	at org.example.netty.NettySslClient.testPEMReaderIssueInNetty(NettySslClient.java:100)
	at org.example.netty.NettySslClient.test(NettySslClient.java:31)
	at org.example.FipsUtils.main(FipsUtils.java:21)
```

### Steps to reproduce
1. configure environment to use only BC FIPS in java.security
2. remove non compliant BC libraries from the classpath
3. to make it more real you may set BC FIPS to work only in the approved mode - but that's not necessary to reproduce this particular issue

### Minimal yet complete reproducer code (or URL to code)

```
import io.netty.handler.ssl.SslContext;
import io.netty.handler.ssl.SslContextBuilder;

...

    public static void testPEMReaderIssueInNetty() {
        try {
            // Load client key and certificate files for mutual TLS
            File clientCert = ResourceToFile.getFileFromResource("mc-client-pem.crt");
            File clientKey = ResourceToFile.getFileFromResource("temporal/client.key");

            // Load server CA for trust store
            File serverCA = ResourceToFile.getFileFromResource("mc-ca-pem.crt");

            // Create SslContext for mTLS
            SslContext sslContext = SslContextBuilder.forClient()
                    .trustManager(serverCA)
                    .keyManager(clientCert, clientKey)
                    .build();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
```

### Netty version
4.1:
https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/BouncyCastlePemReader.java#L80

same with 5:
https://github.com/netty/netty/blob/a3000fe497823d61130dd1064b45172d56096257/handler/src/main/java/io/netty5/handler/ssl/BouncyCastlePemReader.java#L72

### JVM version (e.g. `java -version`)
doesn't matter, reproduced on 17

### OS version (e.g. `uname -a`)
doesn't matter, happend in container with Linux, reproduced on Windows

**Comment by chrisvest** [comment]
Can you add more detailed steps on how you configure the FIPS environment? To make it easier for me to recreate the issue when I have time to look at it.

**Comment by jwojcie** [comment]
To make it good enough for this use case:
1. replace your java.security content with this:
```
security.provider.1=org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider C:DEFRND[SHA256];ENABLE{ALL};
security.provider.2=org.bouncycastle.jsse.provider.BouncyCastleJsseProvider fips:BCFIPS
security.provider.3=SUN

securerandom.source=file:/dev/random
securerandom.strongAlgorithms=NativePRNGBlocking:SUN,DRBG:SUN
securerandom.drbg.config=

keystore.type=bcfks
keystore.type.compat=true

ssl.KeyManagerFactory.algorithm=PKIX
ssl.TrustManagerFactory.algorithm=PKIX

org.bouncycastle.fips.approved_only=true
```

2. make sure you have below libraries available in the classpath:
https://mvnrepository.com/artifact/org.bouncycastle/bc-fips/2.0.0
https://mvnrepository.com/artifact/org.bouncycastle/bcpkix-fips/2.0.7
https://mvnrepository.com/artifact/org.bouncycastle/bctls-fips/2.0.19
https://mvnrepository.com/artifact/org.bouncycastle/bcutil-fips/2.0.3

3. remove all other bouncycastle libraries from the classpath and application

Above should be enough to get that exception. If you want to go a bit further and actually estabilish an SSL connection with that context you also need to turn off netty native features - the are not compliant, in particular at some point in native mode netty tries to instantiate SunJSSE which as you can see above is not on the list (https://github.com/netty/netty/blob/04bba992563bdf8e25c74b710b8d4a4e8f622afd/handler/src/main/java/io/netty/handler/ssl/OpenSslX509TrustManagerWrapper.java#L159). Also for convenience I turned off default truststore, there are issues with out of the box truststore from java distribution after switching to BC FIPS.

```
            System.setProperty("javax.net.ssl.trustStore", "NONE");
            System.setProperty("io.netty.handler.ssl.noOpenSsl", "true");
            System.setProperty("io.netty.transport.noNative", "true");
            System.setProperty("io.netty.transport.noEpoll", "true");
```

**Comment by jwojcie** [comment]
hi, is there any progress on that one?

**Comment by jamonation** [comment]
@jwojcie question - though the [CMVP certificate is now historical](https://csrc.nist.gov/projects/cryptographic-module-validation-program/certificate/4616) for the 1.x BC-FIPS libraries, I'm curious if using them as a test results in different behaviour?

**Comment by jwojcie** [comment]
@jamonation I was testing it with latest, however I think it would fail with historical to. You can download it from here and look inside: https://repo1.maven.org/maven2/org/bouncycastle/
I checked some fips versions, I don't see org.bouncycastle.jce. package there. Also in the user guide to BC-FJA 1.0.2 I see only BouncyCastleFipsProvider mentioned, no BouncyCastleProvider there.

**Comment by chrisvest** [comment]
@jwojcie Happy holidays, check out https://github.com/netty/netty/pull/14618

**Comment by jwojcie** [comment]
Thank you @chrisvest , Happy New Year! :-)
