### ISSUE TITLE
Leak in HttpPostRequestDecoder

### ISSUE THREAD

**Issue by meshonline** [netty/netty#14452]
### Expected behavior
No leak report

### Actual behavior
Leak report
[myleakreport.txt](https://github.com/user-attachments/files/17685885/myleakreport.txt)

### Minimal yet complete reproducer code (or URL to code)
HttpPostRequestDecoder decoder = new HttpPostRequestDecoder(request);
This is line 47 which cause the leak.

### Netty version
4.1.114.Final

### JVM version (e.g. `java -version`)
openjdk 17.0.12 2024-07-16

### OS version (e.g. `uname -a`)
Debian 12.7

**Comment by franz1981** [comment]
Check if your top handler which receives the decoded frame is correctly releasing it

**Comment by meshonline** [comment]
Yes, you are right, there is a strong reference from another handler.

**Comment by meshonline** [comment]
I forgot to call decoder.destroy()
