### ISSUE TITLE
`AdaptivePoolingAllocator.CENTRAL_QUEUE_CAPACITY` and `MAGAZINE_BUFFER_QUEUE_CAPACITY` need to do range check early

### ISSUE THREAD

**Issue by laosijikaichele** [netty/netty#14489]
### Expected behavior
The `AdaptivePoolingAllocator.CENTRAL_QUEUE_CAPACITY` and `AdaptivePoolingAllocator.MAGAZINE_BUFFER_QUEUE_CAPACITY` MUST NOT less than 2, otherwise it will rise an exception when initialize the `AdaptivePoolingAllocator` instance.

We should set them to 2 if less than 2 by using `Math.max(...)`:
```
    private static final int CENTRAL_QUEUE_CAPACITY = Math.max(2,
            SystemPropertyUtil.getInt(
            "io.netty.allocator.centralQueueCapacity", NettyRuntime.availableProcessors()));

    private static final int MAGAZINE_BUFFER_QUEUE_CAPACITY = Math.max(2,
            SystemPropertyUtil.getInt("io.netty.allocator.magazineBufferQueueCapacity", 1024));
```
or we fail-fast in the class load stage:
```
static {
        if (CENTRAL_QUEUE_CAPACITY < 2) {
            throw new IllegalArgumentException("CENTRAL_QUEUE_CAPACITY: " + CENTRAL_QUEUE_CAPACITY
                    + " (expected: >= " + 2 + ')');
        }
        if (MAGAZINE_BUFFER_QUEUE_CAPACITY < 2) {
            throw new IllegalArgumentException("MAGAZINE_BUFFER_QUEUE_CAPACITY: " + MAGAZINE_BUFFER_QUEUE_CAPACITY
                    + " (expected: >= " + 2 + ')');
        }
    }
```

### Actual behavior
https://github.com/netty/netty/blob/a0e67671651a99977391c5552dd90e7bc147308a/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java#L112-L120
### Netty version

4.1.115.Final

**Comment by chrisvest** [comment]
I think it's better to reject nonsense configurations early, as we currently do, but with better messages (your second option).
We can't really presume to know what people intended, when people put in configurations that aren't within their expected value domains.

Will you make a PR?

**Comment by laosijikaichele** [comment]
OK, will submit a PR soon.
