### ISSUE TITLE
Sentinel object `Magazine.MAGAZINE_FREED` is possible be replaced without be restored back

### ISSUE THREAD

**Issue by laosijikaichele** [netty/netty#14498]
### Expected behavior

If I understood it right, the sentinel object `Magazine.MAGAZINE_FREED` should not be replaced without being restored back.

### Actual behavior

https://github.com/netty/netty/blob/afa465a49a3ce7379d64f7632aaf26f8767af6ab/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java#L665-L684

The line:671 `Chunk nextChunk = NEXT_IN_LINE.get(this);` if `nextChunk` get value `MAGAZINE_FREED`, which is possible when magazines table is doing resizing, then the line:673 `NEXT_IN_LINE.compareAndSet(this, nextChunk, current)` will replace the `MAGAZINE_FREED` object by `current`, and without restored the `MAGAZINE_FREED` back.

### Possible solution:

Modified line:672 to:
```
if (nextChunk != null && nextChunk != MAGAZINE_FREED 
&& current.remainingCapacity() > nextChunk.remainingCapacity()) {
...
}
```
### Netty version

4.1.115.Final

**Comment by normanmaurer** [comment]
@laosijikaichele sounds about right ... please do a PR

**Comment by laosijikaichele** [comment]
OK, will do it soon.
