### ISSUE TITLE
MqttPublishMessage doesn't properly implement refCnt

### ISSUE THREAD

**Issue by slandelle** [netty/netty#14507]
### Expected behavior

Calling `MqttPublishMessage#refCnt` on an instance whose payload is not longer accessible should return 0. 

### Actual behavior

It blows an `IllegalReferenceCountException`.

### Steps to reproduce

No need, see existing code:

```
  public int refCnt() {
        return content().refCnt();
    }

  public ByteBuf content() {
        return ByteBufUtil.ensureAccessible((ByteBuf) super.payload());
    }
```

### Netty version

4.1.115

### JVM version (e.g. `java -version`)

Irrelevant

### OS version (e.g. `uname -a`)

Irrelevant

**Comment by slandelle** [comment]
TBH, I don't think any of the methods in MqttPublishMessage that ensure ByteBufUtil.ensureAccessible make sense.
It's not part of `ByteBufHolder`'s contract. IMO, all these checks should be removed and let `ByteBuf do its job`.

**Comment by slandelle** [comment]
@normanmaurer @chrisvest Please let me know what you think so I can provide a PR.

**Comment by normanmaurer** [comment]
@slandelle sounds good to me
