### ISSUE TITLE
Visibility issue across threads for the field `AdaptivePoolingAllocator.Chunk.allocatedBytes`

### ISSUE THREAD

**Issue by laosijikaichele** [netty/netty#14505]
### Actual behavior

There is a possible visibility issue across threads for the field `AdaptivePoolingAllocator.Chunk.allocatedBytes`.

https://github.com/netty/netty/blob/caf240ced2ed06cc3df196f0a4dda5ea6b973bde/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java#L813-L837

The line:826 assigned a value to `allocatedBytes`: `allocatedBytes = 0;`, then if line:827 successfully set this chunk to the the magazine's next chunk, then another thread now allocate from the magazine's next chunk, there might be a visibility issue for the field `allocatedBytes`.

### Possible solution:

Change the field `allocatedBytes` to volatile?

### Netty version

4.1.115.Final

**Comment by laosijikaichele** [comment]
Another point: We also need to decrease the `usedMemory` before line:832: `mag.usedMemory.getAndAdd(-capacity()); `

**Comment by franz1981** [comment]
No need.
`mag.trySetNextInLine` and `offerToQueue` both act as store-release. 
See https://preshing.com/20120913/acquire-and-release-semantics/ for more information: `allocatedBytes` as long is performed in this form (for example)

Thread 1:
1. write opaque allocatedBytes
[ StoreStore + LoadStore ]
3. store release next

Thread 2:
1. load acquire next
[ LoadLoad + LoadStore ]
4. load opaque allocatedBytes

since there is an acquire-release through the `next` field, the `allocatedBytes` one can be stored/read without fences.

**Comment by laosijikaichele** [comment]
@franz1981 
The java doc of method `compareAndSet` states:
>     /**
>      * Atomically sets the field of the given object managed by this updater
>      * to the given updated value if the current value {@code ==} the
>      * expected value. This method is guaranteed to be atomic with respect to
>      * other calls to {@code compareAndSet} and {@code set}, but not
>      * necessarily with respect to other changes in the field.
>      *
>      * @param obj An object whose field to conditionally set
>      * @param expect the expected value
>      * @param update the new value
>      * @return {@code true} if successful
>      */
>     public abstract boolean compareAndSet(T obj, V expect, V update);

Seems it does not guaranteed the changes in the field?

> but not necessarily with respect to other changes in the field.

**Comment by franz1981** [comment]
If it succeed it will work like a volatile store which is like a store sequential consistent

**Comment by laosijikaichele** [comment]
@franz1981  I think you are right. There is a 'happens-before' on the same atomic reference.
