### ISSUE TITLE
Consider re-assign the `chunk.magazine` to current magazine after polled the chunk from the `centralQueue`

### ISSUE THREAD

**Issue by laosijikaichele** [netty/netty#14513]
### Expected behavior

For the `AdaptivePoolingAllocator`, after polled a `Chunk` from the `centralQueue`, do we need to change the field value of `Chunk.magazine` to current magazine instance?

Because the previous value of the `Chunk.magazine` may reference to an already freed magazine. 

This change may bring some benefits:

(1). May help the already freed magazine to be GC'ed by not reference to it.

(2). When the polled `Chunk` get de-allocated again, it will have greater chance to be moved to the current magazine's `NEXT_IN_LINE`, because the previous magazine's `NEXT_IN_LINE` have greater chance been marked as `MAGAZINE_FREED` than current magazine.

Does this worth to do or this change will cause other side effects?

### Netty version

4.1.115.Final

**Comment by normanmaurer** [comment]
you are correct but there is more todo... let me fix it
