### ISSUE TITLE
TooLongFrameException does not include actual frame size

### ISSUE THREAD

**Issue by jammyMarse** [netty/netty#14559]
### Description
When receiving frames larger than the configured maximum frame size, Netty throws a TooLongFrameException. However, the exception message does not include the actual size of the frame that exceeded the limit, which is crucial information for debugging frame size issues.

### Expected Behavior
The TooLongFrameException should include the actual size of the frame that was too large, as this would greatly aid in debugging and understanding the scope of the data issue.

### Environment
- Netty version: 4.1.114.Final

### Possible Solution
Modify the TooLongFrameException to include the frame size in the exception message or provide additional debugging information when this exception is thrown.

**Comment by normanmaurer** [comment]
@jammyMarse we are happy to review a PR :)
