### ISSUE TITLE
4.1.114.Final upgrade 4.1.115.Final OOM

### ISSUE THREAD

**Issue by linking12** [netty/netty#14553]
### Expected behavior
No OOM
### Actual behavior
OOM 
### Steps to reproduce
Hard to provide
### Minimal yet complete reproducer code (or URL to code)
Hard to provide
### Netty version
4.1.115
### JVM version (e.g. `java -version`)
Jdk17
### OS version (e.g. `uname -a`)
K8s

I think this is a hard to reproduce issue, when i upgrade netty to 4.1.115.Final, the application of our cluster 2 node oom killed;
one is aws ec2, one is k8s node, i found the oom reason is mmap cache is increaseing slow, but not all the instance occurs this issue;

es2 monitor:
![image](https://github.com/user-attachments/assets/bfef527a-425e-476b-b826-d02ba20a4244)

k8s node oom log:

<img width="1313" alt="image" src="https://github.com/user-attachments/assets/69d63a15-9588-4c22-ae34-05ad7388c71e">

<img width="692" alt="image" src="https://github.com/user-attachments/assets/cd2ec42a-0277-4e35-b577-d9574a42a6fe">

i make sure our app'mmap do not increase;
<img width="1370" alt="image" src="https://github.com/user-attachments/assets/86ab5ed7-763a-4a5c-b078-1ca05c58070a">

I'd like to confirm if there was any change in version 4.115 that caused the mmap to grow?

**Comment by chrisvest** [comment]
List of changes: https://github.com/netty/netty/compare/netty-4.1.114.Final...netty-4.1.115.Final

We don't directly map files, but anonymous mapped memory is where the system malloc sources its memory.
Maybe some of the adaptive allocator changes behaves poorly?

**Comment by linking12** [comment]
> List of changes: [netty-4.1.114.Final...netty-4.1.115.Final](https://github.com/netty/netty/compare/netty-4.1.114.Final...netty-4.1.115.Final)
> 
> We don't directly map files, but anonymous mapped memory is where the system malloc sources its memory. Maybe some of the adaptive allocator changes behaves poorly?

it happened high traffic comming, i will downgrade to 4.1.114.Final to investigate whether it is the cause of the Netty version, will report here if have any result find;

**Comment by linking12** [comment]
> List of changes: [netty-4.1.114.Final...netty-4.1.115.Final](https://github.com/netty/netty/compare/netty-4.1.114.Final...netty-4.1.115.Final)
> 
> We don't directly map files, but anonymous mapped memory is where the system malloc sources its memory. Maybe some of the adaptive allocator changes behaves poorly?


<img width="692" alt="image" src="https://github.com/user-attachments/assets/9d7d6c45-40dd-4125-bcfe-06ed03367966">

@chrisvest  i found inactive_anno & rss memory cause the k8s node oom, i think adaptive has some memory leak in 4.1.115.Final version

**Comment by linking12** [comment]
Another node has OOM for the same reason. I turned on Leak Detaction and found no leak. I suspect there is a problem with adaptive allocation. I will roll to version 114 for verification.

**Comment by He-Pin** [comment]
@linking12 Hi, which BytebufAllocator are you currently using? We found the same issue when we tried the `AdaptiveByteBufAllocator` when stressing testing, but sorry, have not had another chance to stress it again.

I think you can try to stress it with a different payload to see if that still happen in production.

**Comment by linking12** [comment]
> @linking12 Hi, which BytebufAllocator are you currently using? We found the same issue when we tried the `AdaptiveByteBufAllocator` when stressing testing, but sorry, have not had another chance to stress it again.
> 
> I think you can try to stress it with a different payload to see if that still happen in production.

AdaptiveByteBufAllocator,  4.1.114.Final i think there is no this issue, i want to found what have changed in 4.1.115.Final

**Comment by franz1981** [comment]
Mmap Is used by glibc malloc when the allocations exceed   MMAP_THRESHOLD; which native allocator you are using?
I suggest to use async profiler with -e mprotect if is glibc and we probably capture the code path which keep on leaking

**Comment by linking12** [comment]
> Mmap Is used by glibc malloc when the allocations exceed MMAP_THRESHOLD; which native allocator you are using? I suggest to use async profiler with -e mprotect if is glibc and we probably capture the code path which keep on leaking

We use the default glibc malloc of the operating system. I am currently rolling back the version to stop the bleeding. I will try your suggestion.

**Comment by franz1981** [comment]
Another option could be to use cleaners or limit the JVM native memory (you can do it both via a netty property or maxDirectMemory one on the JVM) and add heap dump on OOM so we can inspect the Chunk(s) instances there; my gut feeling point to https://github.com/netty/netty/issues/14550#issuecomment-2527126996 which shows that over a specific requested size we allocates instead of reusing memory..

**Comment by He-Pin** [comment]
@linking12 Add a `-XX:MaxDirectMemorySize=6g` in your staging ENV and do stressing, which will help.

**Comment by laosijikaichele** [comment]
This may related or not, I also observed the `OutOfMemoryError` when doing the benchmark for `AdaptiveByteBufAllocator`, it seems that the `AdaptiveByteBufAllocator` is more likely to encounter 'OOM' than the `PooledByteBufAllocator.DEFAULT` allocator. 

Use this sample code [BufAllocatorOOMBenchmark](https://github.com/laosijikaichele/netty/blob/tmp/buffer/src/main/java/io/netty/buffer/oom/BufAllocatorOOMBenchmark.java) to produce `OutOfMemoryError`, which limit the memory size by `-Xms168m -Xmx168m -XX:MaxDirectMemorySize=168m`

You will see the `PooledByteBufAllocator.DEFAULT` passed the benchmark, but the `AdaptiveByteBufAllocator` got `OutOfMemoryError`.

In this sample code, the netty-version does not matter, '4.1.114.Final' and '4.1.115.Final' both rise the `OutOfMemoryError`.

**Comment by He-Pin** [comment]
@laosijikaichele I think the AdaptiveByteBufAllocator may have many small fragmants which are not fully utilized when allocation, I have not have time to look into it :(

**Comment by laosijikaichele** [comment]
It seems that add the code 
`chunk.allocatedBytes = chunk.allocatedBytes - length;` 
after the line-1273 make the OOM less occurred:
https://github.com/netty/netty/blob/67c50a1647b5a1c7673a327c833799493f062b3e/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java#L1270-L1285
But, I am not sure if this is correct in logical. @chrisvest @franz1981 @He-Pin

**Comment by normanmaurer** [comment]
@lo

> It seems that add the code `chunk.allocatedBytes = chunk.allocatedBytes - length;` after the line-1273 make the OOM less occurred:
> 
> https://github.com/netty/netty/blob/67c50a1647b5a1c7673a327c833799493f062b3e/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java#L1270-L1285
> 
> 
> But, I am not sure if this is correct in logical. @chrisvest @franz1981 @He-Pin

So before null out `chunk` ?

**Comment by laosijikaichele** [comment]
@normanmaurer 
I am not sure, but the `allocatedBytes` is also used as the `startIndex`, which I think is can not be simply decreased:
https://github.com/netty/netty/blob/67c50a1647b5a1c7673a327c833799493f062b3e/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java#L870-L885

I think this non-decreaseable `allocatedBytes` limited the ability to reuse the released `byteBuf`'s space.

**Comment by He-Pin** [comment]
@laosijikaichele I'm not looking at the code, but I can expect there are some cases in the released space that have not been marked as usable to the Allocator, and then the allocator has to request more memory from the Host.

So  I think we can try a test for 40% 90% and 140% sizes etc things to find the problem, or even just request and free 1 byte.

Is there any picture or design wiki of how the new allocator works?

**Comment by laosijikaichele** [comment]
Run the following code to verify:
```
private static final AdaptiveByteBufAllocator adaptiveAllocatorNoCache =
            new AdaptiveByteBufAllocator(true, false);

    public static void main(String[] args) {
        for (int i = 0; i < 26; i ++) {
            ByteBuf buf = adaptiveAllocatorNoCache.heapBuffer(659225);
            buf.release();
            System.out.println("i = " + i + ",usedHeapMemory:" + adaptiveAllocatorNoCache.usedHeapMemory());
        }
    }
```
Output:
```
i = 0,usedHeapMemory:6592250
i = 1,usedHeapMemory:6592250
i = 2,usedHeapMemory:6592250
i = 3,usedHeapMemory:6592250
i = 4,usedHeapMemory:6592250
i = 5,usedHeapMemory:6592250
i = 6,usedHeapMemory:6592250
i = 7,usedHeapMemory:6592250
i = 8,usedHeapMemory:6592250
i = 9,usedHeapMemory:0
i = 10,usedHeapMemory:10485760
i = 11,usedHeapMemory:10485760
i = 12,usedHeapMemory:10485760
i = 13,usedHeapMemory:10485760
i = 14,usedHeapMemory:10485760
i = 15,usedHeapMemory:10485760
i = 16,usedHeapMemory:10485760
i = 17,usedHeapMemory:10485760
i = 18,usedHeapMemory:10485760
i = 19,usedHeapMemory:10485760
i = 20,usedHeapMemory:10485760
i = 21,usedHeapMemory:10485760
i = 22,usedHeapMemory:10485760
i = 23,usedHeapMemory:10485760
i = 24,usedHeapMemory:10485760
i = 25,usedHeapMemory:20971520
```
We can see the `usedHeapMemory` keeps going up.

**Comment by johnou** [comment]
not something this simple is it? i'll run some tests

```
Index: buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java b/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java
--- a/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java	(revision 67c50a1647b5a1c7673a327c833799493f062b3e)
+++ b/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java	(date 1734089651774)
@@ -836,6 +836,8 @@
                 deallocate();
                 return true;
             }
+            int startIndex = allocatedBytes;
+            allocatedBytes = startIndex - decrement;
             return false;
         }
 ```

**Comment by johnou** [comment]
```
Index: buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java b/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java
--- a/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java	(revision 67c50a1647b5a1c7673a327c833799493f062b3e)
+++ b/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java	(date 1734090510934)
@@ -1271,6 +1271,7 @@
         protected void deallocate() {
             if (chunk != null) {
                 chunk.release();
+                chunk.allocatedBytes = chunk.allocatedBytes - length;
             }
             tmpNioBuf = null;
             chunk = null;
```

@laosijikaichele looks like with your suggested patch the heap doesn't grow, debugging it locally though, is it expected the same chunk would be returned after it is released?

**Comment by johnou** [comment]
@laosijikaichele looks like there is also an edge case in io.netty.buffer.AdaptivePoolingAllocator.Chunk#readInitInto where allocatedBytes is incremented but in the finally catch when deallocating b/c of failure it is not decremented.

**Comment by normanmaurer** [comment]
> @laosijikaichele looks like there is also an edge case in io.netty.buffer.AdaptivePoolingAllocator.Chunk#readInitInto where allocatedBytes is incremented but in the finally catch when deallocating b/c of failure it is not decremented.
> 
> ```
> Index: buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java b/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java
> --- a/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java	(revision 67c50a1647b5a1c7673a327c833799493f062b3e)
> +++ b/buffer/src/main/java/io/netty/buffer/AdaptivePoolingAllocator.java	(date 1734091751136)
> @@ -880,6 +880,7 @@
>                      // If chunk is not null we know that buf.init(...) failed and so we need to manually release
>                      // the chunk again as we retained it before calling buf.init(...).
>                      chunk.release();
> +                    allocatedBytes = startIndex;
>                  }
>              }
>          }
> ```

Good catch https://github.com/netty/netty/pull/14577

**Comment by normanmaurer** [comment]
> @johnou Thanks for the quick test. But I thinks it's probably not that simple, as the [#14553 (comment)](https://github.com/netty/netty/issues/14553#issuecomment-2541222841) stated, we may need to find another way to make the released memory be reusable...

Yes its not as easy...

**Comment by normanmaurer** [comment]
So I think the problem basically steams from how we calculate the queue size:

```
    /**
     * The maximum size of a pooled chunk, in bytes. Allocations bigger than this will never be pooled.
     * <p>
     * This number is 10 MiB, and is derived from the limitations of internal histograms.
     */
    private static final int MAX_CHUNK_SIZE =
            BUFS_PER_CHUNK * (1 << AllocationStatistics.HISTO_MAX_BUCKET_SHIFT); // 10 MiB.

    /**
     * The capacity if the central queue that allow chunks to be shared across magazines.
     * The default size is {@link NettyRuntime#availableProcessors()},
     * and the maximum number of magazines is twice this.
     * <p>
     * This means the maximum amount of memory that we can have allocated-but-not-in-use is
     * 5 * {@link NettyRuntime#availableProcessors()} * {@link #MAX_CHUNK_SIZE} bytes.
     */
    private static final int CENTRAL_QUEUE_CAPACITY = SystemPropertyUtil.getInt(
            "io.netty.allocator.centralQueueCapacity", NettyRuntime.availableProcessors());
```

This basically means if you end up with a Chunk size of 10MB the worst case is that you will have 2 * 10 MB (for the Magazine) + cores * 10MB. This can easily a few hundred MB.

**Comment by He-Pin** [comment]
You mean if there are many cores ?

**Comment by linking12** [comment]
<img width="1048" alt="image" src="https://github.com/user-attachments/assets/cf64abb1-c093-400f-88c8-25478cbd2070" />

@normanmaurer  i'm not sure this issue is fixed, we use the latest code；
I found that the rss memory will continue to increase. Although it will decrease after a certain period of time, it is generally increasing. Now I understand why the mmap memory why increase. It should be that when the rss is not enough, it will try to exchange memory through mmap
