### ISSUE TITLE
AdaptivePoolingAllocator fails in an environment with less than 2 reported CPU's

### ISSUE THREAD

**Issue by kolstae** [netty/netty#14579]
Load class `io.netty.buffer.ByteBufUtil` in an environment with less than 2 CPU's.

### Actual behavior
Fails with `java.lang.IllegalArgumentException: capacity: 1 (expected: >= 2)`

### Steps to reproduce
In an environment with less than 2 CPU's run the below

### Minimal yet complete reproducer code (or URL to code)
```java
public static void main(String[] args) {
   io.netty.buffer.UnpooledByteBufAllocator.DEFAULT.directBuffer(16, 32);
}
```

### Netty version
`4.2.0.Beta1`

### JVM version (e.g. `java -version`)
```
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment (build 21.0.3+10-LTS)
OpenJDK 64-Bit Server VM (build 21.0.3+10-LTS, mixed mode, sharing)
```

### OS version (e.g. `uname -a`)
`6.12.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 22 Nov 2024 16:04:27 +0000 x86_64 GNU/Linux`

Seems to be caused by `io.netty.buffer.AdaptivePoolingAllocator.CENTRAL_QUEUE_CAPACITY` being set equal to available CPU's.

Initially [reported in vertx](https://github.com/eclipse-vertx/vert.x/issues/5404)

**Comment by normanmaurer** [comment]
Thanks for reporting... Fixed via https://github.com/netty/netty/pull/14582
