### ISSUE TITLE
IoUring: Memory Usage for receiving data

### ISSUE THREAD

**Issue by dreamlike-ocean** [netty/netty#14600]
I reviewed the io_uring transport code in the 4.2 branch and noticed that when auto-read is enabled, the first read operation allocates memory with a length of 1024 for io_uring_recv. In comparison, the epoll transport only allocates memory and reads from the socket after receiving an EPOLLIN event. In scenarios with a large number of connections, the io_uring transport causes a sudden surge in memory usage.

I recall that the io_uring transport previously used a combination of POLLIN + recv for receiving data. Could you please explain why this approach is no longer being used?

```java
    private void doBeginReadNow() {
        if (socket.isBlocking()) {
            // If the socket is blocking we will directly call scheduleFirstReadIfNeeded() as we can use FASTPOLL.
            ioUringUnsafe().scheduleFirstReadIfNeeded();
        } else if ((ioState & POLL_IN_SCHEDULED) == 0) {
            ioUringUnsafe().schedulePollIn();
        }
    }
```

**Comment by normanmaurer** [comment]
Yes that's true and we could also still allow users to do one or the other. Not doing the extra POLL_IN is cheaper if there is something that needs to be read. One of the things we still plan to do is adding support for the providing buffers via a ring on demand which then would eliminate the extra memory overhead while still provide the same optimizations.

**Comment by normanmaurer** [comment]
@dreamlike-ocean yes we can do this... Let me convert this to an issue

**Comment by normanmaurer** [comment]
Please check https://github.com/netty/netty/pull/14605
