### ISSUE TITLE
GlobalEventExecutor.terminationFailure - classloader leak with plugin-like classloaders

### ISSUE THREAD

**Issue by ninja-** [netty/netty#14615]
### Expected behavior

When netty in on the main classpath, and plugins are dynamically loaded and unloaded, there are no memory leaks that link from netty to the unloaded classloader.

### Actual behavior
GlobalEventExecutor.termiantionFailure leaks classloader of the first class accessing it, by storing the stacktrace

Workaround - manually null the stacktrace array after initialization
Proposed fix - switch to a stackless cached exception or avoid caching it

https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/concurrent/GlobalEventExecutor.java#L83

### Steps to reproduce
Provide netty in main classpath, and run something from GlobalEventExecutor from a plugin classloader

### Netty version
4.1.114

### JVM version (e.g. `java -version`)
OpenJDK 21

**Comment by ninja-** [comment]
btw I looked over code that is supposed to solve the contextClassloader leak https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/concurrent/GlobalEventExecutor.java#L232

I think in most cases it would be ineffective because it would still leak Thread.inheritedAccessControlContext  
to which a possible fix is to set the context classloader to classloader of GlobalEventExecutor class _before_ `new Thread()` is called, to avoid the control context being copied from user classloader initializing the class

but this one is more theoretical because the application would have to hammer GEE all the time for it to never shutdown or recreate the thread

**Comment by chrisvest** [comment]
@ninja- please take a look at https://github.com/netty/netty/pull/14616 – I think that should fix it, or at least the specific things you pointed out. This isn't a scenario that we generally test for, though… it's pretty hard to properly test this.

**Comment by ninja-** [comment]
> This isn't a scenario that we generally test for, though… it's pretty hard to properly test this.

don't worry about it...I appreciate the fix :smile:
