### ISSUE TITLE
ChannelGroup.write(...) must duplicate ByteBuf / copy ByteBufHolder

### ISSUE THREAD

**Issue by jarod** [netty/netty#1461]
before 4.0.0.CR3 I do this with this code:

```
void broadcast(byte[] data) {
  ByteBuf msg = Unpooled.wrappedBuffer(data);
  for (Channel ch : channels) {
    ch.write(msg);
  }
}
```

with CR3:

```
void broadcast(byte[] data) {
  ByteBuf msg = Unpooled.wrappedBuffer(data);
  for (Channel ch : channels) {
    msg.retain();
    ch.write(msg);
  }
}
```

after upgrade to CR5, the code not work again, seems like netty consume/copy(?) the ByteBuf in a asynchronization way now. And I change my code to:

```
void broadcast(byte[] data) {
  ByteBuf msg = Unpooled.wrappedBuffer(data);
  for (Channel ch : channels) {
    msg.retain();
    ch.write(msg.slice());
  }
}
```

I don't know this is the best way to do. I looked the netty-example project, the examples are all Request-Response. It would be great to add example to demonstrate the offical way to do Request->Broadcast.(e.g. chatting room)

**Comment by kenro** [comment]
private static Object safeDuplicate(Object message) {
 +        if (message instanceof ByteBuf) {
 +            return ((ByteBuf) message).duplicate().retain();
 +        } else if (message instanceof ByteBufHolder) {
 +            return ((ByteBufHolder) message).copy();
 +        } else {
 +            return ReferenceCountUtil.retain(message);
 +        }
 +    }

when brocast ByteBuff， duplicate() just copy byte[] ,and its readerIndex is still old.will a write method change the readerIndex?

**Comment by ratcashdev** [comment]
@normanmaurer looking at safeDuplicate and the write methods on the ChannelGroup.
If the initial/original object is a kind of buffer, shouldn't we release it after sending to the whole group? Becuase, afaik we only release the duplicates inside the `send()`
