### ISSUE TITLE
Data Length is missing in encoded DNS PTR response

### ISSUE THREAD

**Issue by Tiller** [netty/netty#14627]
### Expected behavior
Sending a DatagramDnsResponse with a DnsPtrRecord to answer a reverse DNS proxy using DefaultDnsRecordEncoder should generate a valid data packet

### Actual behavior
DefaultDnsRecordEncoder does not generate a valid data packet and the answer is not readable.

After analysis of the generate data packet, the data length in the PTR answer appear to be missing.

Valid answer (not from netty):
![valid](https://github.com/user-attachments/assets/3471c27b-0dda-49ea-9e41-2f680caf441d)

Invalid answer (from netty):
![invalid](https://github.com/user-attachments/assets/9b6c65d7-8995-4162-a203-c4a844501277)

The data length (00 1f) is missing. See #3.2.1 at https://www.ietf.org/rfc/rfc1035.txt

Adding the length to the encoding fixed the issue (see https://github.com/Tiller/dns-proxy/commit/89e90cf2289c61ee44a801a54a73ee91c855b889#diff-d3e926b3b5812f7a15cc077986d7eedc8ccaeac2771c840eabf081460c9a63dd )

```java
  private void encodePtrRecord(DnsPtrRecord record, ByteBuf out) throws Exception {
    encodeRecord0(record, out);
    encodeName(record.hostname(), out);
  }
// =>
 private void encodePtrRecord(DnsPtrRecord record, ByteBuf out) throws Exception {
    encodeRecord0(record, out);
    final ByteBuf buffer = Unpooled.buffer();
    encodeName(record.hostname(), buffer);
    out.writeShort(buffer.readableBytes());
    out.writeBytes(buffer);
  }
```

### Steps to reproduce
Setup a DNS server answering to reverse DNS queries and try to get an answer from `dig -x`

You can if you want use https://github.com/Tiller/dns-proxy (`java -jar dns-proxy-all.jar -v 1.1.1.1`) and revert to the default netty encoder in Application.java (in the constructor of DatagramDnsResponseEncoder)

### Netty version
4.1.101 but after checking out latest master on github the issue is still present

**Comment by normanmaurer** [comment]
@Tiller thanks for the report. Should be fixed https://github.com/netty/netty/pull/14628
