### ISSUE TITLE
max-age in cookie for Internet Explorer

### ISSUE THREAD

**Issue by ramn** [netty/netty#1466]
The Cookie class will add a max-time value instead of expires, which results in a session cookie in Internet Explorer.

Expected: Expires should be used in the cookie
Actual: max-age is used

**Comment by trustin** [comment]
The option 2 sounds better to me, but what do you think, @slandelle? What is the right thing here in your opinion?

**Comment by slandelle** [comment]
Option 2 is the more straightforward, so I'm OK with it. Waiting for #3239 to be merged before fixing this one.

**Comment by trustin** [comment]
Looks like this issue has been fixed for 4.0.26. Correct, @normanmaurer ?

**Comment by normanmaurer** [comment]
@trustin correct
