### ISSUE TITLE
Only call fireChannelReadComplete() if autoRead is false.

### ISSUE THREAD

**Issue by jpinner** [netty/netty#1559]
Tracking issue to update and document the autoRead, channelReadComplete, and read behavior.

The contract is that fireChannelReadComplete should be called to signal that a read() is required to continue reading. For channel implementations this means that fireChannelReadComplete should only be called if autoRead is false, indicating that once it is called, a read() call is required to get more data. If autoRead is true, the channel will continue to read whenever there is data available, so reads are never "complete."

**Comment by normanmaurer** [comment]
Lets close this for now
