### ISSUE TITLE
Channel's  id method has removed, so how to determine whether two channel are equal？

### ISSUE THREAD

**Issue by vintagewang** [netty/netty#1583]
In 4.0.0.CR9， I used id method to determine whether two channel are equal

I found 4.0.0.Final has removed id method, is there any method to  determine whether two channel are equal?

**Comment by nothing-whoami** [comment]
Where is the solution? I can't see it!

**Comment by nothing-whoami** [comment]
@trustin 
Channel.hashcode() is not guaranteed to be unique!
What is the solution? I can't see it!

**Comment by trustin** [comment]
In 4.1, we have `ChannelId` which is supposed to be very unique.

**Comment by nothing-whoami** [comment]
@trustin Ok! Thany you!
