### ISSUE TITLE
provide best practice (or replacement) for channel.id() removal

### ISSUE THREAD

**Issue by matlach** [netty/netty#1589]
Hi,

I'm a bit concerned about Issue #1535 and #1540 which has been resolved in 4.0.0.Final. I think internally to not rely on channel.id() is probably a good thing and I understand the reason of doing so. Tough, as an end user of Netty I was relying on this id to find back a Channel in a ChannelGroup.

Here is my use case:
I run a distributed application where I need to match many "Session" a simple replicated data structure which simply hold in ram:
- the session id (a uuid used all through my application)
- the machine id (the identifier of the server where the socket/channel is physically bound)
- the netty channel id

Before 4.0.0.Final, upon Channel creation, I was creating a "Session" with all the information explained before. Then my business logic could match many "Session" and make possible for them to interact which each other by sending message through a distributed task (run on the "machine id" server and sent to the Channel netty channel id found into the ChannelGroup).

In 4.0.0.Final, to solve my issue, the first thing that come to my mind is that I could use an AttributeKey to store an unique id. Then I would simply need to iterate on all Channel in ChannelGroup until I find the corresponding channel. This would work for sure but I doubt that would be very efficient.

Then I guess I could also create a kind of custom ChannelGroup based on some sort of WeakValueHashMap where I could find back easily my Channel by an unique id. I don't really like this idea because I think it would simply lead to many other problems like increased contention.

I think the root of the problem is not to create an id but to find back a Channel in a ChannelGroup where complete traversal seem the only way to do so.

Maybe Netty could enhance ChannelGroup to let user put a Channel with a specific Object as it is Key inside ? a bit like if ChannelGroup would extends both Set<Channel> and Map<ChannelKey, Channel> where ChannelKey would be a Generic. Or without any Netty enhancements, I guess I could extends DefaultChannelGroup and roll my own ?

I just think this need to be revisited.

Any ideas ?

Big thanks, and keep up the very good work !

**Comment by sqlboy** [comment]
I too have the same issue...no way to tie a process back to a channel without iterating all the channels.
