### ISSUE TITLE
PlatformDependent0.freeDirectBuffer(..) is a performance bottleneck

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#1698]
Currently we try to use Cleaner.clean(..) in PlatformDependent0.freeDirectBuffer(..) to free up direct ByteBuffer. Unfortunally this is big bottleneck as some Cleaner methods are 'static synchronized'.

We should think about how to fix this. Most likely via JNI...

**Comment by doom369** [comment]
@normanmaurer just wondering - does somebody reported this problem? I looked trough `Cleaner` code. And it seems for me very simple and straightforward.  It is very unlikely that even with 10-20k req/sec there any chance for contention (don't think real server with business logic can handle more).

Also according to Cleaner doc : 

> Cleaners are a lightweight and more robust alternative to finalization. They are lightweight because they are not created by the VM and thus do not require a JNI upcall to be created

I understand this as Cleaner is faster than JNI call :).

However look like in Java 9 will be [alternative](http://hg.openjdk.java.net/jdk9/jdk9/jdk/rev/7c8488605485) for Cleaner.

**Comment by normanmaurer** [comment]
Ler me close this for now as there is not much we can do
