### ISSUE TITLE
Interrogation and suggestion on HTTP Multipart Body Codec

### ISSUE THREAD

**Issue by fredericBregier** [netty/netty#1753]
Hi,
I'm currently trying to understand REST interface, and it appears that lot of REST implementation using HTTP protocol are using body with more than just PUT, POST, PATCH requests.

For instance, some implementations are using GET with a multipart body, while it is not largely implemented. But according to what I've read, it is allowed to have a BODY (and therefore a multipart request) for all type of HTTP requests excepting HEAD request.

So my interrogation and suggestion are around to change the Multipart Codec to allow all type of HTTP requests, excepting HEAD.
But as I'm not 100% sure of the correctness of this idea, I'm asking you guys what you think?

**Comment by fredericBregier** [comment]
I believe this issue could be closed once #6155 is cherry-picked.

**Comment by Scottmitch** [comment]
@fredericBregier - PR #6155 has been cherry-picked. Feel free to close if you are satisfied since you reported the original issue.

**Comment by fredericBregier** [comment]
#6155 respond to this request so closing this one too

Thanks
