### ISSUE TITLE
Optimize writeAndFlush for lots of small messages (do smart autoflush)

### ISSUE THREAD

**Issue by stepancheg** [netty/netty#1759]
Typical server code looks like this:

```
void channelRead(ChannelHandlerContext ctx, Object msg) {
    ctx.writeAndFlush(doSomething(msg));
}
```

This code is very ineffective when size of response is small, and number of request/responses are huge. Because this code seems to issue `send` syscall after each `writeAndFlush` operation.

There is an easy way to implement `writeAndFlush` efficiently. I implemented it on top of Netty, but I think it should be implemented inside of Netty.

Algorithm in pseudocode is this:

```
class Channel {
    ...
    // with lock-free-queue we don't need locks
    LockFreeQueue<Object> queue = new LockFreeQueue();

    // 3 states of write-queue-and-flush tasks:
    // * not executing
    // * executing
    // * executing, and should rerun one more time
    Tasks tasks = new Tasks();

    public void writeAndFlush(Object msg) {
        // enqueue message
        queue.enqueue(msg);
        if (tasks.addTask()) {
            // schedule write-queue-and-flush task if we have no one now
            executor.submit(this::writeQueueAndFlush);
        }
    }

    private void writeQueueAndFlush() {
        // while clients submit us tasks
        while (tasks.fetchTask()) {
            // we write these tasks, but do not flush
            List<Object> messages = queue.dequeueAll();
            for (message : messages) {
                doWrite(message);
            }
        }
        // and finally flush
        doFlush();
    }
}
```

I have sample project:

https://github.com/stepancheg/netty-td/

It has an implementation of this algorithm on top of Netty: [BetterWriter.write method](https://github.com/stepancheg/netty-td/blob/master/src/com/github/stepancheg/nettytd/BetterWrite.java#L56).

[Tasks](https://github.com/stepancheg/netty-td/blob/master/src/com/github/stepancheg/nomutex/tasks/framework/Tasks.java) class is lock-free helper to schedule not more than one write-queue-and-schedule task.

[LockFreeQueue implementation](https://github.com/stepancheg/netty-td/blob/master/src/com/github/stepancheg/nomutex/tasks/framework/LockFreeStackWithSize.java) (it is actually lock-free-stack; lock-free-stack is faster, and difference is not important for this issue).

Edit: [simpler implementation using atomics](https://github.com/stepancheg/netty-td/blob/master/src/com/github/stepancheg/nettytd/BetterWriteWithAtomic.java).

I did [simple test](https://github.com/stepancheg/netty-td/blob/master/src/com/github/stepancheg/nettytd/Perftest.java): client sending 4 byte messages and server replying with 4-byte messages.

With default client and server using writeAndFlush test result is about 30k rps (on my notebook), and with BetterWriter.write implementation result is about 200k rps. It is 6 times speed up!

WriteAndFlush is very convenient operation for situation when size of queue is unknown (for example, in server code I don't know whether my request is last or not, and whether I can omit flushing). So IMHO it should work well by default, and such smart buffering should not be delegated to the user of Netty.

**Comment by Climax777** [comment]
Perhaps what would satisfy this problem is having an optional periodic flush? But please enlighten me, why is it necessary to flush the channel? Does the internal socket implementation rely on external flushing to pass data to the transport layer? Most (if not all) network stacks rely on buffers internally and use algorithms such as nagle to improve batch sending. 

Coming from C++ with boost's asio, for example, no flushing is required.

**Comment by stepancheg** [comment]
@Climax777 `write` call just enqueues message in process memory, and `flush` is an operation that does `send` syscall.

BTW, better name for `write` could be `enqueue` and better name for `flush` could be `write`.

**Comment by Climax777** [comment]
Thanks for clarifying @stepancheg 

I would suggest a periodic flusher, with a selectable period.

**Comment by stepancheg** [comment]
@Climax777 periodic flusher is unsuitable for the most tasks: it either flushes too rarely, or consumes too much CPU.

**Comment by etaty** [comment]
We can make a nagle in netty.
We need to know when the OS has flushed (or ready for more data), 
so we can send the next batch of data to be flushed
or raise a flag telling that we can writeFlush next time

**Comment by stepancheg** [comment]
@etaty you seems not to understand the issue.

The problem is that if user quickly calls `writeAndFlush` several times when network buffer is full, and then after socket is available for writing, netty will call `send` syscall several times instead of filling the buffer and calling `send` once.

It is unrelated to nagle. It is about sending the whole queue in single batch instead of sending with multiple `send` calls.

>  We need to know when the OS has flushed (or ready for more data), 

Netty already knows when a socket is ready for new data. It is the essence of async IO.

**Comment by Climax777** [comment]
If not a periodic flushing task, what about defining thresholds? Perhaps
flush when the queue reaches a certain limit? Perhaps even a combination?
Actually I think this should be done on application level. Netty won't be
able to get it right for all use cases in my opinion.

**Comment by stepancheg** [comment]
@Climax777

> If not a periodic flushing task, what about defining thresholds?

Problem with threshold, if is that if you network traffic is not constant, then some messages may hang in the queue indefinitely.

> Netty won't be able to get it right for all use cases in my opinion.

Please explain drawbacks of solution I proposed.

**Comment by Climax777** [comment]
@stepancheg I've been looking at your repository. It seems you're onto something here. Your solution will guarantee that all writes sent before the scheduler starts running the flush task, will get flushed with once. That includes calls from different concurrent threads?

Also just a question, the listener you add to the write future, does it get called after flushing or after queuing in netty (I know this is a netty internal thing, but I'm not sure now).

**Comment by stepancheg** [comment]
@Climax777 

> Your solution will guarantee that all writes sent before the scheduler starts running the flush task, will get flushed with one flush syscall. That includes calls from different concurrent threads?

Yes. With one `send` syscall to be correct.

Better implementation could flush when chunks reach like 64k to avoid excessive memory allocations on network stalls.

> Also just a question, the listener you add to the write future, does it get called after flushing or after queuing in netty

Sorry, I don't remember, and don't have and IDE right now to look.

**Comment by erbenmo** [comment]
another suggestion, if you want to batch multiple pending writes in a single flush, it would be good to have a config which controls the maximum number of writes in a batch.

**Comment by stepancheg** [comment]
@erbenmo 

> it would be good to have a config which controls the maximum number of writes in a batch

Maybe it would be good, but it does not solve the problem.

**Comment by Viyond** [comment]
I focus on it, too.

**Comment by umermansoor** [comment]
How about flushing only when writer is idle? [IdleStateHandler](https://netty.io/4.0/api/io/netty/handler/timeout/IdleStateHandler.html)

e.g. application only writes to the channel:

` write1, write2, write3,...`

After say 500ms (or whatever latency is preferred), IdleStateHandler fires a writer idle event at which point the flush happens:

`[writer idle event] flush`

Not sure if there's an overhead involved with this approach and if it effects performance negatively. Feedback is appreciated.

**Comment by artem-v** [comment]
Easiest way to implement batching is when you have _reading_ and _writing_ channels registered on the same netty thread. Then you could catch a point when read operations have been completed on _all_ channels, and then flush all _dirty_ channels. I.e. approach looks like this: 
- setup thread local collection for channels that shall be flushed.
- on all channels setup outbound channel handler with overriden write() which would add a channel to thread local collection from prev step.
- when all read operations on [ch1, ..., chN] in this netty thread completed, then get the collection with dirty channels and flush them one by one.

This shall work for proxy like applications which doing a flow like:  decodeOnChannel1 -> lightbusinesslogic -> encodeOnChannel2  on the same netty thread.

**Comment by chongyangxue** [comment]
I build a message counter and a timer to do flush. 
e.g When write 1000 message and every 3 seconds, make a force  flush.
Looking for better way to do this.

**Comment by jadbaz** [comment]
I have written [here](https://gist.github.com/jadbaz/47d98da0ead2e71659f343b14ef05de6) a ChannelOutboundHandler that implements a queuing system to avoid flooding the socket and to optimize its usage.
It uses the same event listener process as the [DiscardClientHandler example](http://netty.io/4.1/xref/io/netty/example/discard/DiscardClientHandler.html).

In theory, this should never exhaust the socket no matter what you do as writes are only done after previous writes are completed.

It should be clear, however, that this is not an implementation of batching as was proposed in the [comment above](https://github.com/netty/netty/issues/1759#issuecomment-296889374). Batching could be integrated with this handler: when polling from the queue, poll up to X messages or N bytes and write them together. This could effectively reduce syscalls and might further optimize throughput. If haven't tried it though...

PS: make sure to use `channel.write` and not `channel.writeAndFlush` as the flushing is done inside the handler

**Comment by jamiemchow** [comment]
i have the same problem

**Comment by artash** [comment]
Nobody mentioned [FlushConsolidationHandler](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/flush/FlushConsolidationHandler.java) yet. Looks like it's designed to solve the same problem @stepancheg ?

**Comment by medusar** [comment]
@artash `FlushConsolidationHandler` is new to me, but it will hold the flushes only if it is `readInprogress`: 

`if (readInprogess) {
            // If there is still a read in compress we are sure we will see a channelReadComplete(...) call. Thus
            // we only need to flush if we reach the explicitFlushAfterFlushes limit.
            if (++flushPendingCount == explicitFlushAfterFlushes) {
                flushPendingCount = 0;
                ctx.flush();
            }
            return;
        }
        ctx.flush();
`

As in my application, there will not be too much inbound data, so the `readInprogess` will be `false` for a long time, but i have a lot of outbound data to be send, so this one will not work.

And i also don't understand why `flush` will be called after `channelReadComplete` ? What are the effects if i flush without caring about if it is reading ?

**Comment by medusar** [comment]
> Nobody mentioned [FlushConsolidationHandler](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/flush/FlushConsolidationHandler.java) yet. Looks like it's designed to solve the same problem @stepancheg ?

LGTM, thanks

**Comment by jchambers** [comment]
Yeah—does the job for me, too. https://github.com/relayrides/pushy/pull/657 has some before-and-after benchmarks, if anybody's curious.

**Comment by normanmaurer** [comment]
Let me close this

**Comment by m4ce** [comment]
@stepancheg, does [FlushConsolidationHandler](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/flush/FlushConsolidationHandler.java) solves the issue for you?

**Comment by stepancheg** [comment]
@m4ce looks so, hard to say, I didn't use netty for long time.
