### ISSUE TITLE
LengthFieldBasedFrameDecoder produces IllegalArgumentException when frame is too big

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#1798]
The problem arise if the max frame size exceed and the buffer hold the complete frame already. This is because the calculation of the value for skipBytes(...) will be negative atm.

**Comment by okou19900722** [comment]
Netty3 also has this problem, not fixed

**Comment by Scottmitch** [comment]
Netty 3.x has been EOL for a while [1]. Please upgrade to 4.1 and report a new issue if the problem still exists.

[1] http://netty.io/news/2016/06/29/3-10-6-Final.html
