### ISSUE TITLE
support re-registering channel with new event loop

### ISSUE THREAD

**Issue by wgallagher** [netty/netty#1799]
I removed deregister because it had a number of threading / message ordering issues.  Norman, Trustin, Jeff and I discussed an alternative that would allow channels to reregister with a new eventloop without calling deregister.  This has the nice property that channels are never in a state where they're not registered to an eventLoop.  There are still some problems to overcome:

Attempting to move a channel from one eventLoop to another is very tricky.  Some of the problems:

It can never be the case that a channel handler is being invoked by 2 event loops simultaneously.  This means that any event executing on the old event loop must complete before the first event on the new eventLoop is executed.

Events that are queued while the old eventLoop is still processing messages must be put somewhere.  They cannot be put directly on the new eventLoop because they would immediately begin to execute.  A solution proposed by Jeff is to continue to add the incoming events to the old event loop.  When an event executes, it checks if its event loop is the current event loop for the channel and, if not, re-enqueues in the new event loop.  

One problem with this approach is that messages can be reordered.  If an event executing on the new eventLoop enqueues a new event, this event will be appended to the new event loop and fire before events remaining on the old event loop.

**Comment by normanmaurer** [comment]
I think it is supported already now since some time
