### ISSUE TITLE
io.netty.channel.socket.nio.AbstractNioChannel     doRegister() ？？

### ISSUE THREAD

**Issue by boboyada** [netty/netty#1836]
@Override
    protected void doRegister() throws Exception {.............
selectionKey = javaChannel().register(eventLoop().selector, 0, this);
what does the  "opt==0" means ?
1=OP_READ
2=OP_WRITE
8=OP_CONNECT
16=OP_ACCEPT
0=??

but ,I found that:
NioEventLoop.has method :
 private static void processSelectedKey(SelectionKey k, AbstractNioChannel ch) {
............
....................
        try {
            int readyOps = k.readyOps();
            if ((readyOps & (SelectionKey.OP_READ | SelectionKey.OP_ACCEPT)) != 0 || readyOps == 0) {
                unsafe.read();
                if (!ch.isOpen()) {
                    // Connection already closed - no need to handle write.
                    return;
                }
            }
........
"readyOps==0"   ,why?

thanks you!

**Comment by dengyuankai272** [comment]
There are two way to register interested events:

1.Channel.register()
2.SelectionKey.interest(int)

netty use 2.

After binding channel to selector(that is, register the channel to selector with 0), netty will invoke fireChannelActive()->fire a read event->HeadContext.unsafe.doBeginRead()->SelectionKey.interestOps(int) to set interestOps.

protected void doBeginRead() throws Exception {  
        if (inputShutdown) {  
            return;  
        }  
  
        final SelectionKey selectionKey = this.selectionKey;  
        if (!selectionKey.isValid()) {  
            return;  
        }  
  
        final int interestOps = selectionKey.interestOps();  
        if ((interestOps & readInterestOp) == 0) {  
            selectionKey.interestOps(interestOps | readInterestOp);  
        }  
    }

**Comment by zuoshoulan** [comment]
It took me a day to find the place to register “SelectionKey.OP_ACCEPT”，finally，I found that，case 1 eq case 2
```
        selector = Selector.open();
        serverSocket = ServerSocketChannel.open();
        serverSocket.configureBlocking(false);
//        SelectionKey sk = serverSocket.register(selector, SelectionKey.OP_ACCEPT); // case 1
        SelectionKey sk = serverSocket.register(selector, 0); //case 2
        serverSocket.socket().bind(new InetSocketAddress(port));
        sk.attach(new Acceptor());
```
