### ISSUE TITLE
100 % CPU usage even with oracle java7u40

### ISSUE THREAD

**Issue by akshaydeo** [netty/netty#1873]
I have written a socket server for messages using netty 4.0.9-FInal. But even while handling a single connection, CPU load goes upto 100%. 

My setup:
1. amazon standard ami (centos)
2. java7u40 (which is supposed to have bug fix http://bugs.sun.com/view_bug.do?bug_id=6403933

What all I have tried
1. http://code.google.com/p/spymemcached/issues/detail?id=279
   This thing didn't help.
2. Attached Executor workers so as to keep min of load on nio worker groups.
3. setAutoRead is set to false whenever possible. TCP_NO_DELAY, RECV BUFFER, SEND_BUFFER are set to optmise performance.
4. I tuned up some kernel parameters related with buffers to maximize performance.

Is there anything that I am missing ?

**Comment by PunKeel** [comment]
Hello,
The link is now dead ... :( 

Any chance you still have your "solution" ?


Best regards!
