### ISSUE TITLE
Reconsider the built-in functionality that allows a user specify an EventExecutor for a handler

### ISSUE THREAD

**Issue by trustin** [netty/netty#1912]
#1808 and [this discussion](https://groups.google.com/d/topic/netty/1kAS-FJWGRE/discussion) tells me that we need to rethink this API:

```
ChannelPipeline p = ...;
p.addLast(eventExecutorGroup, "..", handler);
```

.. because the thread model provided by `EventExecutorGroup` is not really applicable to an arbitrary user application.  Which thread should be assigned for a business-related task is highly application specific and should be determined by a handler implementation, not the pipeline.  For example, some protocol might allow a client to make multiple connections to a server with the same credential and the server should make sure the requests made by the same user are executed sequentially.

The current behavior that allows multiple channels to share the same thread to perform potentially blocking operations aren't always useful to users.

Therefore, I think we should remove this built-in functionablity or revamp it quite a bit so that it is extensible enough.  Personally, I'd be happy to remove it completely without an alternative, and let users choose whatever they want to do with their own thread pool.

/cc @normanmaurer, @jpinner, and @wgallagher

**Comment by arunp1990** [comment]
Hi @trustin , @normanmaurer  ,

Could you please let me know if there is any example / documentation on how to uptake this new approach? Even I have an use-case where I want to execute time-consuming tasks in a DefaultEventExecutorGroup as mentioned in https://groups.google.com/g/netty/c/1kAS-FJWGRE (thread based on which these changes were initially started). I understand that one alternative is to use an ExecutorService that I manage myself and submit tasks to it. This was confirmed by @trustin  in https://groups.google.com/g/netty/c/1kAS-FJWGRE/m/GDqVs23J5KIJ. Is there any alternate approach possible with the changes done as part of this pull request?

Thanks!

**Comment by trustin** [comment]
@Knight-Wu wrote:

> I want to make sure that all events from one channel, including channelHandlers, read and write events is always done by one eventloop from worker eventloop, and not executed by other threads, is that right ?

Correct!

> Then, if two channels bind to the same threads, one channelHandler may block other events, is that right ?

Yes.

> So, if there are long time events, we should use new threadpool to handle , is that right, and are there any examples to show ?

Exactly. It should be as simple as calling `Executor.execute()` with your task. I guess it's so obvious that it doesn't need an example, but please let me know if you really need one.

**Comment by trustin** [comment]
@arunp1990 wrote:

> Could you please let me know if there is any example / documentation on how to uptake this new approach? Even I have an use-case where I want to execute time-consuming tasks in a `DefaultEventExecutorGroup` as mentioned in groups.google.com/g/netty/c/1kAS-FJWGRE (thread based on which these changes were initially started). I understand that one alternative is to use an `ExecutorService` that I manage myself and submit tasks to it. This was confirmed by @trustin in groups.google.com/g/netty/c/1kAS-FJWGRE/m/GDqVs23J5KIJ. Is there any alternate approach possible with the changes done as part of this pull request?

Using a separate `Executor` for long-running tasks is officially recommended way in Netty. We tried to introduce something that lets a user handle such tasks without leaving the boundary of `ChannelHandler`, but we chose not to do it because:

- It complicates the execution path for more common cases, i.e. an application with no/few long-running tasks;
- It's hard to maintain; and
- A user usually has his or her preferred way of handling such tasks depending on the nature of the tasks, so it's hard to generalize without complicating our API.

@normanmaurer  Could you confirm my memory is correct or if where was any changes in this decision while I was away? :laughing:
