### ISSUE TITLE
Support for SASL in the Pipeline

### ISSUE THREAD

**Issue by daschl** [netty/netty#1966]
Hi All,

@normanmaurer, @trustin I'd like to get your input on this if you have a minute.
I need SASL support in the pipelines, but since this is a general feature I thought everyone might benefit from it if we get it into the core.

So first question:
- Should we get generic SASL support in netty? It is also used in protocols like smpt, pop3, ldap,.. so I guess people building servers/clients for it could benefit.

Either way, I thought about reusing the built-in SASL functionality through the JDK supported objects (javax.security.sasl).
- What do you think would be the best namespace, subproject name and so on for it?

I think the rough behaviour would be that it gets added in the pipeline and removes itself once successfully authed. Do we already have "auth" infrastructure in place that I can reuse?

I think this would work out really well with the current model, because SASL potentially requires more auth steps and we could handle that with a state machine like in the decoders?

Thanks,
Michael

**Comment by eolivelli** [comment]
I'm really interested in this feature (for http://majordodo.org and http://blazingcache.org) projects)

**Comment by daschl** [comment]
@eolivelli if you want to see a client implementation, check out: https://github.com/couchbase/couchbase-jvm-core/blob/master/src/main/java/com/couchbase/client/core/endpoint/kv/KeyValueAuthHandler.java

**Comment by eolivelli** [comment]
Thank you. I saw in the code you pointed that it is very easy and I successfully integrated support to SASL in one on my netty based projects. I think that actually a basic support for SASL would be feasible in netty but it is not needed as this integration is quite trivial

**Comment by normanmaurer** [comment]
Lets close this for now
