### ISSUE TITLE
ByteBuf.writeByte(byte) in a loop is quite expensive 

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#2023]
ByteBuf.writeByte(byte) in a loop is quite expensive atm because for each writeByte(byte) it need to check for the refCnt of the buffer. We should think about if we can improve this by expose a special method for writing bytes but only check once for the refCnt.

**Comment by bwzhang2011** [comment]
@Scottmitch, any update with the issue ? we're caring about the HttpResponseEncoder  performance.

**Comment by Scottmitch** [comment]
@bwzhang2011 - No update on my end. Do you have benchmarking to indicate that this is a problem for `HttpResponseEncoder`?

**Comment by normanmaurer** [comment]
I think we should just close this for now. If we find out this is a real problem we can re-visit
