### ISSUE TITLE
Easier mocking of Bootstrap

### ISSUE THREAD

**Issue by daschl** [netty/netty#2034]
Currently, it's very hard to mock the Bootstrap. I would like to mock it for example to see how it calls connect and so on. This is not possible because.
- It is a final class
- Has no appropriate interface to mock that

It would be good to fix that in one way or another, it would make it very easy to mock the bootstrap part.

@trustin , @normanmaurer  what do you think?

**Comment by hepin1989** [comment]
I want to override the ```void init(Channel channel) throws Exception``` too.

**Comment by normanmaurer** [comment]
@hepin1989 can you tell me why ?

**Comment by hepin1989** [comment]
@normanmaurer thanks,I want to using netty to implement an akka-io-extension.and I finally come up with one way to implement it.
https://github.com/netty/netty/blob/master/transport/src/main/java/io/netty/bootstrap/ServerBootstrap.java#L181

suppose I have ```TcpManager``` and ```TcpListener``` which is created by the ```TcpManager``` when the manager received the ```Bind(handler:ActorRef,localAddress:InetSocketAddress ...)``` command.

1,It will create the ```ServerBootstrap``` inside the  ```TcpListener```  , setup it and call ```bind``` at it.
2,When there is an ```Channel``` accepted ,I want to passing the Channel to the ```TcpManager``` as a
```ChannelRegisterable``` message,then ```TcpManager``` create a child actor ,maybe ```ChannelActor``` with that channel.And then the ```ChannelActor```  send a ```Connected``` message the ```handler``` ,the ```handler``` will send an ```Register(handler:ActorRef)``` to it,after that the ```ChannelActor``` will register it channel to the ```childeventloopGroup```.


I don't want to automatic register the child Channel to the eventloop,and want control it by myself.and I found it would works by just override the ```init``` method.

by another way,I think I could just replace the last channel handler after the ```ServerSocketChannel``` bound with mine.and then do that work.

both way would works.

another concern about this I could send an ```ChannelAcceptable``` message to the handler and using the handler to accept the channel,and then register it to the ```childEventLoopGroup``` just as 
https://github.com/netty/netty/blob/master/transport/src/main/java/io/netty/channel/socket/nio/NioServerSocketChannel.java#L135.

but by this way the what should ```int doReadMessages``` return ? 1 ?I could not return a Promise(size:Int) here.

thanks.

**Comment by hepin1989** [comment]
@normanmaurer any suggestion?

**Comment by trustin** [comment]
That will defeat the original purpose of bootstrap - providing common behaviors (automatic registration is one of them). What you really want is *not* to use bootstrap.  Please keep in mind that bootstrap is just a utility class that's close to the builder pattern. Nothing prevents you from creating a new channel by yourself and register it at your convenient time.

**Comment by trustin** [comment]
Also, please note that your request is not directly related with the original issue reported here. You should have filed a new issue.

Let me lock this issue.
