### ISSUE TITLE
Lingering `GlobalEventExecutor` after graceful shutdown

### ISSUE THREAD

**Issue by jchambers** [netty/netty#2084]
We've noticed an issue where a global event executor thread lingers after calling `shutdownGracefully` on an event loop group. In practice, it goes away on its own after several hundred milliseconds, but it triggers alarms in cases where there's something looking for leaked resources (like a servlet container). Here's a sample app I wrote to illustrate the issue:

``` java
import io.netty.channel.nio.NioEventLoopGroup;

public class NettyShutdownTestApp {

    public static void main(String[] args) throws InterruptedException {
        new NioEventLoopGroup().shutdownGracefully().sync();

        // Expected: since we have shut down gracefully, there should be no
        // running Netty threads at this point.
        printRunningThreadList();
    }

    public static void printRunningThreadList() {
        final Thread[] threads = new Thread[128];
        getRootThreadGroup(Thread.currentThread().getThreadGroup()).enumerate(threads, true);

        for (final Thread thread : threads) {
            if (thread != null) {
                System.out.println(thread.getName());
            }
        }
    }

    public static ThreadGroup getRootThreadGroup(ThreadGroup startingPoint) {
        return startingPoint.getParent() == null ?
                startingPoint : getRootThreadGroup(startingPoint.getParent());
    }
}
```

My expectation would be that because we've gracefully shut down all Netty resources we created in our own app, all Netty-related threads would have stopped by the time the shutdown `Future` completed. When we dump the list of running threads after the sync, though, the actual list looks something like this:

```
Reference Handler
Finalizer
Signal Dispatcher
process reaper
main
globalEventExecutor-1-1
```

As a control, if we never create the `NioEventLoopGroup` or never call `shutdownGracefully`, then `globalEventExecutor-1-1` doesn't appear in the list of running threads.

Thanks!

**Comment by sujoykr1** [comment]
Threads are going to be renewed over time to try and avoid a probable memory leak...............Please help.
