### ISSUE TITLE
Support Android officially

### ISSUE THREAD

**Issue by trustin** [netty/netty#2127]
Given that:
- mobile devices are becoming more and more powerful,
- the most known issues with NIO and SSLEngine in ADK were fixed since Ice Cream Sandwich, and
- users obviously want to reuse their codecs and handlers in their mobile application.

Therefore, I think it will be worthwhile to support Android officially.  However, we had to rely on manual testing and user report to know if Netty works fine on Android or not, and it was painful to both the users and the devs.

To address the mentioned problem and to support Android in a saner way:
- Write the testsuite that extends our current testsuite, which runs the testsuite in an Android emulator.
  - One of the tasks to make this possible is going to be writing a simple application that runs a series of JUnit tests and logs its output to the Android console.
- Apply sensible defaults
  - The default allocator could be unpooled heap allocator for example and we should be less memory hungry.

Unfortunately, I don't have enough time to work on this.  If there's a volunteer, I'd be happy to set up a Jenkins account for him/her so he or she can play with it.

**Comment by sujitjagtap** [comment]
Want to use netty as server on Android. Will connect 200 to 500 clients with rest api support with backed by SQLITE. This server needs to serve a files to all connected clients. Does it will support? Any help will be appreciated

**Comment by steven-gao** [comment]
i use the netty 5.0.0jar to run on my sumsung s3,it occurs the same error as @darting ,does every one can tell me the solution?

**Comment by normanmaurer** [comment]
Can you try 4.1?

**Comment by steven-gao** [comment]
ok,i try 4.1 on my phone.i will give you result for a minuts.

**Comment by qning** [comment]
If you do not need the new features in 4.0 or higher, you can try 3.8.0, it
works well on my Nexus 5 (Android L) .

On Wed, Jan 21, 2015 at 12:35 AM, steven@Gao <notifications@github.com>
wrote:

> i use the netty 5.0.0jar to run on my sumsung s3,it occurs the same error
> as @darting <https://github.com/darting> ,does every one can tell me the
> solution?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/netty/netty/issues/2127#issuecomment-70791119>.
>



-- 

Regards,

QIAN NING

Electrical and Computer Engineering Department,Texas A&M University,.

**Comment by steven-gao** [comment]
i used 4.1jar on my phone, runs ok.thanks all.i think 5.0's compatibility is not so good,is it a bug?

**Comment by Scottmitch** [comment]
@steven-gao - Are you experiencing problems this with alpha1 or the master branch?  If it is alpha1 then could you try the master branch and see if you have the same problems?

**Comment by Akarshit** [comment]
@trustin Hello, i am using Netty for developing a library that is compatible with both android and java, can you please confirm that Netty will be compatible with Android, and also which version is most compatible with Android.

**Comment by normanmaurer** [comment]
@Akarshit use 3.x or 4.0.x

**Comment by Akarshit** [comment]
@normanmaurer thanks :smile:

**Comment by nmnhero** [comment]
Hi, when I use io.netty I get this errors:

Could not find method sun.misc.Unsafe.addressSize, referenced from method io.netty.util.internal.PlatformDependent0.addressSize
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54886: Lsun/misc/Unsafe;.addressSize ()I
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.allocateMemory, referenced from method io.netty.util.internal.PlatformDependent0.allocateMemory
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54887: Lsun/misc/Unsafe;.allocateMemory (J)J
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.copyMemory, referenced from method io.netty.util.internal.PlatformDependent0.copyMemory
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54893: Lsun/misc/Unsafe;.copyMemory (JJJ)V
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x74 at 0x0011
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.copyMemory, referenced from method io.netty.util.internal.PlatformDependent0.copyMemory
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54894: Lsun/misc/Unsafe;.copyMemory (Ljava/lang/Object;JLjava/lang/Object;JJ)V
02-03 17:10:08.775 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x74 at 0x0016
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.freeMemory, referenced from method io.netty.util.internal.PlatformDependent0.freeMemory
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54895: Lsun/misc/Unsafe;.freeMemory (J)V
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.getByte, referenced from method io.netty.util.internal.PlatformDependent0.getByte
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54896: Lsun/misc/Unsafe;.getByte (J)B
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.getByte, referenced from method io.netty.util.internal.PlatformDependent0.getByte
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54897: Lsun/misc/Unsafe;.getByte (Ljava/lang/Object;J)B
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.getInt, referenced from method io.netty.util.internal.PlatformDependent0.getInt
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54898: Lsun/misc/Unsafe;.getInt (J)I
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.getLong, referenced from method io.netty.util.internal.PlatformDependent0.getLong
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54901: Lsun/misc/Unsafe;.getLong (J)J
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.getShort, referenced from method io.netty.util.internal.PlatformDependent0.getShort
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54906: Lsun/misc/Unsafe;.getShort (J)S
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.getShort, referenced from method io.netty.util.internal.PlatformDependent0.getShort
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54907: Lsun/misc/Unsafe;.getShort (Ljava/lang/Object;J)S
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.putByte, referenced from method io.netty.util.internal.PlatformDependent0.putByte
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54911: Lsun/misc/Unsafe;.putByte (JB)V
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.putByte, referenced from method io.netty.util.internal.PlatformDependent0.putByte
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54912: Lsun/misc/Unsafe;.putByte (Ljava/lang/Object;JB)V
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.putInt, referenced from method io.netty.util.internal.PlatformDependent0.putInt
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54913: Lsun/misc/Unsafe;.putInt (JI)V
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.putLong, referenced from method io.netty.util.internal.PlatformDependent0.putLong
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54916: Lsun/misc/Unsafe;.putLong (JJ)V
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.putShort, referenced from method io.netty.util.internal.PlatformDependent0.putShort
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54924: Lsun/misc/Unsafe;.putShort (JS)V
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.putShort, referenced from method io.netty.util.internal.PlatformDependent0.putShort
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54925: Lsun/misc/Unsafe;.putShort (Ljava/lang/Object;JS)V
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x0006
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp I/dalvikvm: Could not find method sun.misc.Unsafe.throwException, referenced from method io.netty.util.internal.PlatformDependent0.throwException
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp W/dalvikvm: VFY: unable to resolve virtual method 54926: Lsun/misc/Unsafe;.throwException (Ljava/lang/Throwable;)V
02-03 17:10:08.780 22747-22747/com.nmn.industrialapp D/dalvikvm: VFY: replacing opcode 0x6e at 0x000a

**Comment by LisonLiou** [comment]
This is my solution for android use netty 4.0.36Final. It achieve text send and receive and image transfer.
http://lison.cc/508.html
And the demo on github: https://github.com/LisonLiou/netty-learning
