### ISSUE TITLE
Clean up transport-udt tests

### ISSUE THREAD

**Issue by trustin** [netty/netty#2141]
I see the following in the tests in transport-udt:
- performance test classes - these should be moved somewhere else
- we don't really need to depend on Caliper and Yammer Metrics
- the classes in the `util` package can be moved to the same package with the test classes and become package-private
- maybe some tests could be moved to the testsuite?

**Comment by normanmaurer** [comment]
I think we can just close this now as we deprecated the UDT transport and it will be removed in next major release
