### ISSUE TITLE
Add copiedBuffer() methods in ByteBufAllocator

### ISSUE THREAD

**Issue by trustin** [netty/netty#2207]
Original discussion from #2028

**Comment by normanmaurer** [comment]
@trustin do we really want to do this ? I don't think so :)

**Comment by trustin** [comment]
What's the current way of creating a pooled buffer from a string?

**Comment by normanmaurer** [comment]
allocator.allocate().writeCharSequence(...) ?

**Comment by trustin** [comment]
Sounds good to me.
