### ISSUE TITLE
Consider removing promise from write() and add a separate operation for adding a promise

### ISSUE THREAD

**Issue by trustin** [netty/netty#2279]
We could consider to separate promise from a write, because:

* It will simplify `ChannelOutboundBuffer` a lot.
* A handler that wants to add a listener to every write can just insert its own promise for each write:
```
void writeMessage(ctx, msg) {
  ctx.writeMessage(msg);
  ChannelPromise p = ctx.newPromise().addListener(...);
  ctx.writePromise(p);
  // or we could also do this as a shortcut:
  // ctx.write(msg).addListener(...); // also good for backward compatibility.
}

void writePromise(ctx, promise) {
  ctx.writePromise(promise);
}

void flush(ctx) {
  ctx.flush();
}
```

Most handlers don't create a new promise for each write, so we will probably save a lot of garbage for outbound traffic.  We can also keep the number of pending buffers small in `ChannelOutboundBuffer` until `flush()`.

**Comment by normanmaurer** [comment]
@trustin can we close this as won't fix ?

**Comment by trustin** [comment]
Yes
