### ISSUE TITLE
HttpObjectAggregator maxContentLength Setting

### ISSUE THREAD

**Issue by spmallette** [netty/netty#2345]
`HttpObjectAggregator` does not appear to respect the `maxContentLength` argument passed to its constructor.  The problem is shown here in this example repo:

https://github.com/spmallette/netty-example

with a "passing" test case:  By "passing", I simply mean that the test should fail by way of an exception generated in the form of a  `413 - Request Entity Too Large` from the request perspective and a `TooLongFrameException` from the response perspective , but it currently passes with no error.

Note the setting of the `HttpAggregator` to `1` here:

https://github.com/spmallette/netty-example/blob/master/src/main/java/com/genoprime/netty/example/Server.java#L54

Followed by the construction of a largish sort of request which would certainly exceed `1`:

https://github.com/spmallette/netty-example/blob/master/src/test/java/com/genoprime/netty/example/ServerIntegrateTest.java#L79

You can execute the test case with maven:

``` text
mvn clean install -Dlog4j.configuration=file:config/log4j.properties
```

The issue was original reported here:

https://groups.google.com/forum/#!topic/netty/CGzeZD7APuQ

**Comment by normanmaurer** [comment]
After checking this old issue again I think it works like expected. Let me close it (sorry for the long delay)
