### ISSUE TITLE
Bit Torrent (Client / Tracker) feature request

### ISSUE THREAD

**Issue by azimot** [netty/netty#2397]
according to usage of more than 40% of all internet traffic from this protocol , it is one of most popular network protocol .
if this protocol implemented in the netty (such as socks) could to represent great Bit Torrent            Client / Tracker with netty performance and features.

 this is very useful for most internet traffic usage i think place of p2p is empty in netty handler list , this is can to placed in io.netty.handler.codec.p2p.bt.

**Comment by normanmaurer** [comment]
I think this is out of scope for netty atm. If someone want to write a codec for it its fine to host this outside of netty.
