### ISSUE TITLE
netty 5: reader stavation in nio & oio channel

### ISSUE THREAD

**Issue by rzo12345** [netty/netty#2408]
hello,

on the same channel when there are continuous writes and some reads the read is never invoked, the only way to get a read invocation is to limit the write by adding Thread.sleep every x writes.

I did not have this issue with netty 3.

i tried setting the iorate to 99 but this did not help. i suppose its not an issue of the nio thread working on io/non-io tasks, but that for some reason data is not being read from the socket.

**Comment by johnou** [comment]
@rzo12345 do you experience the same issue with Netty 4.x?

**Comment by Scottmitch** [comment]
I will close this for now. 5.0 was abandoned a while ago. Please open another issue if this problem exists on 4.1.x.
