### ISSUE TITLE
ThreadLocalRandom enters a tight loop if the initialization thread is interrupted.

### ISSUE THREAD

**Issue by trustin** [netty/netty#2412]
[This line](https://github.com/netty/netty/blob/netty-4.0.18.Final/common/src/main/java/io/netty/util/internal/ThreadLocalRandom.java#L123) causes the wait loop to get tight because it keeps interrupting itself until the seed is retrieved.  This can take up to 3 seconds.  Instead, we should just break out of the loop immediately on interruption and log a warning.

**Comment by whybe** [comment]
I'm using netty-4.0.25-final, but it appeared the WARNNIG unfortunately.
I don't know what is the name of machine running app, but the result of its `uname -a` is `HP-UX nateifsd B.11.11 U 9000/800 3537491374 unlimited-user license`.
And java version is 
```
java version "1.6.0.13"
Java(TM) SE Runtime Environment (build 1.6.0.13-jinteg_01_dec_2011_03_39-b00)
Java HotSpot(TM) Server VM (build 20.3-b02-jre1.6.0.13-rc1b1 PA2.0 (aCC_AP), mixed mode)
```

How can I avoid this warning?
