### ISSUE TITLE
not sure about SingleThreadEventLoop.register(Channel, ChannelPromise)

### ISSUE THREAD

**Issue by colalife** [netty/netty#2422]
hi all, 
a little confused that why not  this method change to register(ChannelPromise) since the channel is a param in DefaultChannelPromise's constructor...(will the promise change channel? ) ,not sure, thanks
source code:
    @Override
    public ChannelFuture register(Channel channel) {
        return register(channel, new DefaultChannelPromise(channel, this));
    }
    @Override
    public ChannelFuture register(final Channel channel, final ChannelPromise promise) {

**Comment by normanmaurer** [comment]
@trustin do we want to "fix this" for 4.1.0.Final or not ?

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5231
