### ISSUE TITLE
Add kqueue channel implementation 

### ISSUE THREAD

**Issue by timothyjward** [netty/netty#2448]
I saw that an epoll Channel implementation has been added to netty. I think this is great, and definitely plan to use it. I do, however, have to support a number of platforms including MacOS. It would be great to have another high-performance channel implementation for platforms that use kqueue.

**Comment by Scottmitch** [comment]
PR #4335 starts to decouple Linux code from Unix code.

**Comment by caarlos0** [comment]
Same here. 

```
Downloading: http://companyrepo.nope/release/io/netty/netty-transport-native-epoll/4.0.32.Final/netty-transport-native-epoll-4.0.32.Final-osx-x86_64.jar
...
Failed to execute goal on project xockets-layer: Could not resolve dependencies for project proj:proj:jar:1.0-SNAPSHOT: Could not find artifact io.netty:netty-transport-native-epoll:jar:osx-x86_64:4.0.32.Final in repo.xockets.teamed.io (http://companyrepo.nope) -> [Help 1]
[ERROR]
```

Any workarounds?

**Comment by ninja-** [comment]
You need to specify the Linux suffix in your project's POM xml

**Comment by caarlos0** [comment]
@ninja- understood...

**Comment by ninja-** [comment]
@caarlos0 so did you fix your problem? If you add the Linux suffix to epoll artifact id it would stop inserting osx instead and breaking build

**Comment by caarlos0** [comment]
@ninja- yes, thank you very much!

**Comment by rnorth** [comment]
Is somebody actively working on implementing this? It seems to be reasonably significant given the changes in Docker for Mac, and there are many downstream projects that depend on this (many via docker-java/docker-java#537).

I'm not in a position to commit to working on this right now, but as maintainer of one of the affected downstream projects I'm thinking about rolling up my sleeves! If somebody else has this underway, though, I'd not want to duplicate any work.

**Comment by normanmaurer** [comment]
There is noone working at it as far as I know atm

**Comment by Scottmitch** [comment]
I also don't know of anyone working on this.

**Comment by marcuslinke** [comment]
@normanmaurer @Scottmitch What do you guys think of https://github.com/softprops/unisockets? It depends on https://github.com/jnr/jnr-unixsocket which doesn't make use of the event based methods like epoll and kqueue. Would it make sense to integrate this into netty for basic unix domain socket support somehow, so the user could use epoll or this one?

**Comment by normanmaurer** [comment]
@marcuslinke honestly I did not know these and would prefer to add "real" non-blocking support if we do it as part of Netty. For this we will need to write some jni code like we did for the epoll one.

**Comment by normanmaurer** [comment]
@marcuslinke actually https://github.com/jnr/jnr-unixsocket/ may work... Let me do some research.

**Comment by marcuslinke** [comment]
@normanmaurer Any news on this?

**Comment by normanmaurer** [comment]
@marcuslinke not yet... gimme a few more days.

**Comment by ndeloof** [comment]
for your information, we plan to rely on this for jenkins' [docker-slaves](https://wiki.jenkins-ci.org/display/JENKINS/Docker+Slaves+Plugin).

**Comment by normanmaurer** [comment]
@marcuslinke I had a look but unfortunately the KQSelector implementation and the channel implementations are not working conform to the nio API. I opened a few issues. Once these are fixed I may have another look. Also @ndeloof

**Comment by slandelle** [comment]
@normanmaurer FWIW, I recently faced an issue with [sshd](https://issues.apache.org/jira/browse/SSHD-666) where `sun.nio.ch.AsynchronousSocketChannelImpl#close()` blocks in infinitely on OSX (but always works properly on Linux). Could be related.

**Comment by normanmaurer** [comment]
@slandelle nope not related.

**Comment by slandelle** [comment]
bummer

**Comment by marcuslinke** [comment]
@normanmaurer Thanks! Just found https://github.com/jnr/jnr-unixsocket/issues/31. Are there more issues?

**Comment by marcuslinke** [comment]
OK. Found. For reference:

https://github.com/jnr/jnr-unixsocket/issues/31
https://github.com/jnr/jnr-enxio/issues/15
https://github.com/jnr/jnr-enxio/issues/16

**Comment by normanmaurer** [comment]
@marcuslinke there may be even more... Once these are fixed I will have another look

**Comment by headius** [comment]
jnr/jnr-unixsocket#31 is fixed and will be released in 0.13.
jnr/jnr-enxio#15 and jnr/jnr-enxio#16 are not yet fixed, but I'd appreciate help getting them into jnr-enxio 0.14.

Sorry these have sat for a while, folks. Let's fix 'em :-)

**Comment by Scottmitch** [comment]
Stand by for a PR! Volunteers wanted to help test and put some milage on the new transport!

**Comment by Scottmitch** [comment]
Please see #6000
