### ISSUE TITLE
documentation improvement request: HttpObjectAggregator: the sequel

### ISSUE THREAD

**Issue by tea-dragon** [netty/netty#2471]
The documentation could really stand to be yet clearer.
- It describes pipeline dependencies in two different places:

> Insert this handler after {@link HttpObjectDecoder} in the {@link ChannelPipeline}:

and

> Be aware that you need to have the {@link HttpResponseEncoder} or {@link HttpRequestEncoder} before the {@link HttpObjectAggregator} in the {@link ChannelPipeline}.
- They are different dependencies, which compounds the issue by creating uncertainty as to whether there might be a mistake in one of them.
- There actually is a mistake in the second one. As far as I can tell, HttpRequestEncoder should never be needed by HttpObjectAggregator. It _does_ require (and they must appear prior to it in the pipeline) either (both HttpRequestDecoder and HttpResponseEncoder) for a server or just HttpResponseDecoder for a client.

As an aside, the HttpResponseEncoder dependency was not mentioned at all prior to the previously filed issue (although it _is_ in the example). There was no mention of it there, so it might be worth mentioning here lest it be overlooked in any subsequent changes. That one got me when requests from certain clients were over certain lengths -- the clients were implicitly checking for a CONTINUE before submitting POSTs over a certain size and the CONTINUEs sent by the Aggregator were not being encoded (my response encoder was after the aggregator in the pipeline. I was trying to group relatively related components together where possible).

**Comment by normanmaurer** [comment]
I just re-read the docs and I think its clearly stated now what is needed. So this seems to be fixed.
