### ISSUE TITLE
Hide InternalLogger from Http2FrameLogger

### ISSUE THREAD

**Issue by trustin** [netty/netty#2512]
InternalLogger is intended for internal use only.  We should hide it from users.

* Instead of `InternalLogLevel`, we can use io.netty.handler.logging.LogLevel`.
* Instead of accepting `InternalLogger`, we can accept `String` and `Class<?>` to create an `InternalLogger` in the constructor of `Http2FrameLogger`.

**Comment by nmittler** [comment]
@trustin @normanmaurer is there any action that I can take on this currently? And if so, will it be backward compatible with 4.1?

**Comment by trustin** [comment]
@nmittler The thing is `InternalLogger` and `InternalLogLevel` are internal API and thus a user or an example should not use and should not be exposed to them.  My suggestion was to use `LogLevel` in the `io.netty.handler.logging` package instead and let user pass the name of the logger instead of `InternalLogger`, but I'm fine if there's a better idea.
