### ISSUE TITLE
NIO.2 support

### ISSUE THREAD

**Issue by chrisprobst** [netty/netty#2515]
Hi,

I saw that Netty.4.Final dropped support for AIO. In the book "Netty in Action" I read that it was dropped mainly because it was not faster and that netty's threading model would make it hard to interoperate, which makes sense.

But maybe I could provide another view, since I'm heavily interested in windows support:

The NIO.1 Selector works using kqueue, epoll and select on pretty much all platforms. Now Windows does have IOCP which is way better than select (select on windows have scalability issues). But, of course, IOCP is the proactor model and does not fit in the reactor-selector-pattern.

That's why JDK7 finally brought us AIO, which implements the proactor pattern. The good thing about the proactor pattern is that it abstract's both select-based-techniques and IOCP very well.

What this all means is, that NIO.1 (Netty =( ) on windows simply does not scale as good as it could be.

I do understand the technical consequences of AIO for netty, though. AIO does have limitations, too.
- First AIO expects a buffer before something was actually read, so if a lot of parallel clients are connected, the reading must be limited in some way.
- AIO runs the completion handlers on the given executor. So if the executor has multiple threads the handlers may be invoked on different threads which would destroy netty's wonderful threading-model. But it's basically simple: Every event-loop in netty would have it's own AsynchronousChannelProvider running using single thread executor. This should work.

I know that this means some work and I am willing to contribute, but I would like to hear your point of view, maybe I do not have enough knowledge about this topic ;=)

Cheers,
Chris

**Comment by lizhup** [comment]
@chrisprobst 然后呢
