### ISSUE TITLE
about built the new jar

### ISSUE THREAD

**Issue by Rekoe** [netty/netty#2534]
use what command to take the new jar package

```
D:\workspace\git\netty\all>mvn package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: windows
[INFO] os.detected.arch: x86_64
[INFO] os.detected.classifier: windows-x86_64
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Netty/All-in-One 5.0.0.Alpha2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/netty/ne
tty-codec-memcache/5.0.0.Alpha2-SNAPSHOT/netty-codec-memcache-5.0.0.Alpha2-20140
604.063835-475.jar
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/netty/ne
tty-codec-http/5.0.0.Alpha2-SNAPSHOT/netty-codec-http-5.0.0.Alpha2-20140604.0638
06-476.jar
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/netty/net
ty-codec-http/5.0.0.Alpha2-SNAPSHOT/netty-codec-http-5.0.0.Alpha2-20140604.06380
6-476.jar (424 KB at 80.3 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.899s
[INFO] Finished at: Wed Jun 04 14:51:53 CST 2014
[INFO] Final Memory: 14M/144M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project netty-all: Could not resolve dependenc
ies for project io.netty:netty-all:jar:5.0.0.Alpha2-SNAPSHOT: Could not transfer
 artifact io.netty:netty-codec-memcache:jar:5.0.0.Alpha2-20140604.063835-475 fro
m/to sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/sna
pshots): Connection to https://oss.sonatype.org refused: Connection timed out: c
onnect -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException
D:\workspace\git\netty\all>mvn compiler
```

**Comment by noodle-wang** [comment]
run “mvn -U clean package”，I got error below，any  suggestion?

λ mvn -U clean package
[INFO] Scanning for projects...
Downloading from repo1: http://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for io.netty:netty-parent:4.0.57.Final-SNAPSHOT: The following artifacts could not be resolved: org.sonatype.oss:oss-parent:pom:9 (absent): Could not transfer artifact org.sonatype.oss:oss-parent:pom:9 from/to repo1 (http://repo1.maven.org/maven2/): status code: 501, reason phrase: HTTPS Required (501) and 'parent.relativePath' points at wrong local POM @ line 20, column 11
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project io.netty:netty-parent:4.0.57.Final-SNAPSHOT (D:\AndroidStudioProjects\Netty\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for io.netty:netty-parent:4.0.57.Final-SNAPSHOT: The following artifacts could not be resolved: org.sonatype.oss:oss-parent:pom:9 (absent): Could not transfer artifact org.sonatype.oss:oss-parent:pom:9 from/to repo1 (http://repo1.maven.org/maven2/): status code: 501, reason phrase: HTTPS Required (501) and 'parent.relativePath' points at wrong local POM @ line 20, column 11 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
