### ISSUE TITLE
DefaultEventExecutor 's pendingTasks  is always 0

### ISSUE THREAD

**Issue by ghost** [netty/netty#2560]
Hello, I write a http server using netty 4.x. The following is my main code.

DefaultEventExecutorGroup eventExecutorGroup = new DefaultEventExecutorGroup(30, new CustomizableThreadFactory(threadFactoryName));

protected void initChannel(SocketChannel ch) throws Exception {
        ChannelPipeline p = ch.pipeline();
        p.addLast("codec", new HttpServerCodec());
        HttpObjectAggregator aggregator = new HttpObjectAggregator(serverConfig.maxContentLength);
        p.addLast("aggregator", aggregator);
        p.addLast("chunkedWriter", new ChunkedWriteHandler());
        p.addLast(eventExecutorGroup, "dispatcher", new HttpMessageDispatcher());
    }

eventExecutorGroup  contains 30 DefaultEventExecutors.  When I make a load test, I debug the defaultEventExecutor's pendingTasks.  Only one of the 30 DefaultEventExecutor has many pendingTasks,  other DefaultEventExecutor pendingTasks are all zero.   Why the tasks are assigend to only one DefaultEventExecutor ?  
Thanks  a lot.

**Comment by lik001** [comment]
@normanmaurer  Could you give a example of using DefaultChannelHandlerInvoker relating to hartprince's codes?
