### ISSUE TITLE
Investigate the cost of CAS operation in selector wakeup

### ISSUE THREAD

**Issue by trustin** [netty/netty#2628]
http://www.afewmoreamps.com/2014/03/a-practical-introduction-to-jmh.html

Need compare the performance of:
- a test application that performs many out-of-IO-thread operations (w/ or w/o CAS), with configurable number of threads.
- a fully asynchronous test application (w/ or w/o CAS)

**Comment by normanmaurer** [comment]
This was improved in our native transport... Lets close it
