### ISSUE TITLE
ByteBufs should be addressable by Long

### ISSUE THREAD

**Issue by md-5** [netty/netty#2637]
Not strictly an issue I am encountering at the moment (I mean who needs 2gb of data on the heap), however for another project I am using netty-buffer for, most of the data sizing and offsets come in the form of unsigned ints. As Java has no capability for unsigned numbers, these have to be upcast to signed longs.

This then means having a downcast again when reading from Netty ByteBufs. I propose that for Netty 5 the ByteBuf interface is changed to accept long values for addressing and capacity such that where possible (such as unsafe native buffers on 64 bit systems) they can be expanded to such large capacities.

Furthermore this will ensure a future proof ABI for when larger types become more mainstay.

**Comment by normanmaurer** [comment]
I think we can close this as at the end we just used ints
