### ISSUE TITLE
Netty sun.nio.ch.EPollArrayWrapper.epollWait High CPU usage profiler problem

### ISSUE THREAD

**Issue by WhiteTrashLord** [netty/netty#2639]
Some guys here (including me) reported that their Netty application has a very high CPU usage. This article helped me a lot:
http://www.brendangregg.com/blog/2014-06-09/java-cpu-sampling-using-hprof.html

To sum it up in a few sentences: When you profile your Netty application with the Java parameter '-agentlib:hprof=cpu=samples' it might show a very high CPU usage for this method: sun.nio.ch.EPollArrayWrapper.epollWait. This should be a wrong result in most of the cases.
It seems in my case it was the Java based SSLHandler which consumed a lot of CPU.

So my little Netty world is alright now :)

**Comment by purplefox** [comment]
Interesting. I just stumbled upon this issue doing some profiling for Vert.x 3 - looks like the exact same issue is present in VisualVM in JDK 8 :(
