### ISSUE TITLE
Inconsistent synchronization of some variables in SpdySessionHandler

### ISSUE THREAD

**Issue by idelpivnitskiy** [netty/netty#2677]
1. Field `io.netty.handler.codec.spdy.SpdySessionHandler.lastGoodStreamId`
Synchronized 50% of the time:
Unsynchronized access at SpdySessionHandler.java:[line 148]
Unsynchronized access at SpdySessionHandler.java:[line 243]
Synchronized access at SpdySessionHandler.java:[line 736]
Synchronized access at SpdySessionHandler.java:[line 851]

2. Field `io.netty.handler.codec.spdy.SpdySessionHandler.receivedGoAwayFrame`
Synchronized 50% of the time
Unsynchronized access at SpdySessionHandler.java:[line 361]
Synchronized access at SpdySessionHandler.java:[line 723]

3. Field `io.netty.handler.codec.spdy.SpdySessionHandler.localConcurrentStreams`
Synchronized 50% of the time
Unsynchronized access at SpdySessionHandler.java:[line 598]
Synchronized access at SpdySessionHandler.java:[line 728]

4. Field `io.netty.handler.codec.spdy.SpdySessionHandler.sentGoAwayFrame`
Synchronized 75% of the time
Unsynchronized access at SpdySessionHandler.java:[line 150]
Synchronized access at SpdySessionHandler.java:[line 723]
Synchronized access at SpdySessionHandler.java:[line 849]
Synchronized access at SpdySessionHandler.java:[line 850]

5. Field `io.netty.handler.codec.spdy.SpdySessionHandler.remoteConcurrentStreams`
Synchronized 50% of the time
Unsynchronized access at SpdySessionHandler.java:[line 318]
Synchronized access at SpdySessionHandler.java:[line 728]

Message from FindBugs:
The fields of this class appear to be accessed inconsistently with respect to synchronization.  This bug report indicates that the bug pattern detector judged that
The class contains a mix of locked and unlocked accesses,
The class is not annotated as javax.annotation.concurrent.NotThreadSafe,
At least one locked access was performed by one of the class's own methods, and
The number of unsynchronized field accesses (reads and writes) was no more than one third of all accesses, with writes being weighed twice as high as reads
A typical bug matching this bug pattern is forgetting to synchronize one of the methods in a class that is intended to be thread-safe.
You can select the nodes labeled "Unsynchronized access" to show the code locations where the detector believed that a field was accessed without synchronization.
Note that there are various sources of inaccuracy in this detector; for example, the detector cannot statically detect all situations in which a lock is held.  Also, even when the detector is accurate in distinguishing locked vs. unlocked accesses, the code in question may still be correct.

@trustin @normanmaurer @fredericBregier @jpinner 
Please, check it out.

**Comment by normanmaurer** [comment]
Let me fix this
