### ISSUE TITLE
Reduce the memory consumption of ChannelOutboundBuffer

### ISSUE THREAD

**Issue by trustin** [netty/netty#2693]
The initial capacity of a `ChannelOutboundBuffer` is 32, and it means each `ChannelOutboundBuffer` will end up with 32 entry objects as a channel lives on, even if the channel's maximum number of pending write requests is always 1.

We could do a few things to fix this:
- Reduce the initial capacity to a smaller value such as 4.
- Recycle entry objects or do something similar (we don't need thread local here obviously.)

http://stackoverflow.com/questions/24726973/netty-4-0-19-final-memory-leak-with-io-netty-channel-channeloutboundbufferentry

**Comment by kyze8439690** [comment]
I have meet this issue, I try to disable AUTO_READ, and manually trigger read() operation by my self, and this issue disappear, Java heap memory consumption is quite stable.
