### ISSUE TITLE
Allow to disable the use of sun.misc.Unsafe

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#272]
Sometimes it can be helpful to disable the use of sun.misc.Unsafe. This is for example true if you run in a OSGI container as sun.misc.Unsafe is not exported normally. It also can help if you have a custom ClassLoader in place or try to run in a non oracle/sun jdk.

**Comment by sachinkumarshetty** [comment]
We are facing a native memory increase when using 4.1.59.Final version of netty and JDK 8 + vertx.
This increase is gradual. Via jemalloc we saw Unsafe#allocateMemory usage is on a higher side.
As we are using vertx + netty, we see high usage of Unsafe by netty. So what kind of impact will disable Unsafe do? i.e setting -Dio.netty.tryUnsafe=false. How much will be a performance impact?
