### ISSUE TITLE
Provide a way to turn an I/O event loop into a task

### ISSUE THREAD

**Issue by trustin** [netty/netty#2759]
As mentioned by @mariusaeriksen previously in [his comment](https://github.com/netty/netty/issues/2250#issuecomment-38410897), I'd like to give a user even more control over who performs I/O tasks and how they are scheduled.

Although we successfully made our event loops are backed by arbitrary `Executor`, where the default is the `ForkJoinPool`, an event loop still decides when to schedule an I/O task by itself and doesn't leave much room for additional control.

We could expose a lower-level construct that enables a user to schedule I/O by him/herself to yield the ultimate control to him or her.

@mariusaeriksen, please feel free to let me know if you want to add something or amend it.

**Comment by normanmaurer** [comment]
@trustin @buchgr is this still something you think is worthwhile or can we close this one ?

**Comment by trustin** [comment]
OK to close.
