### ISSUE TITLE
EmbeddedChannel does not work with ChannelInitializer

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#2771]
From mailinglist:

I am new to Netty (using Netty 4.0.21.Final). I am trying to test my Netty pipeline setup that is encapsulated in `ChannelInitializer`. Example:

``` java
class MyChannelInitializer extends ChannelInitializer<Channel> {

        @Override
        public void initChannel(Channel ch) {
            ch.pipeline().addLast(new LengthFieldBasedFrameDecoder(MAX_FRAME_LENGTH, 0, 4, 0, 4));
            ch.pipeline().addLast(...);
            ch.pipeline().addLast(...);
        }
 }
```

When I setup my test this way:

``` java
EmbeddedChannel channel = new EmbeddedChannel(new MyChannelInitializer());
assertThat(channel.writeInbound(byteBuf)).isTrue();
```

Nohing happens, `ChannelInboundHandlers` that I have setup in an initializer are not executed. This seems to be due to how Netty initializes the `EmbeddedChannel` in its ctor:

``` java
   public EmbeddedChannel(ChannelHandler... handlers) {
        ...

        p.addLast(new LastInboundHandler());
        loop.register(this); // Here MyChannelInitializer is executed
    }
```

When processing incoming data it is always captured by "default" handler which ends up being the first one.

Am I using `EmbeddedChannel` in incorrect way or maybe it was not designed to test `ChannelInitializers`?

**Comment by flirtomania** [comment]
Reproduced on 5.0.0-Alpha2

didn't work:

    EmbeddedChannel ch = new EmbeddedChannel();
    ch.pipeline().addLast(
      new LoggingHandler(LogLevel.TRACE),
      //new LengthFieldBasedFrameDecoder(2048, 0, 2, 0, 0),
      new ReceiptDecoder(),
      receiptHandler
    );

worked ok:

    EmbeddedChannel ch = new EmbeddedChannel(
      new LoggingHandler(LogLevel.TRACE),
      //new LengthFieldBasedFrameDecoder(2048, 0, 2, 0, 0),
      new ReceiptDecoder(),
      receiptHandler
    );
