### ISSUE TITLE
Investigate options for splitting frames with padding in HTTP/2

### ISSUE THREAD

**Issue by nmittler** [netty/netty#2807]
Currently the Http2OutboundFlowController just keeps all the padding at the end of the data, regardless if the frame is split.  Is this the right thing to do WRT security considerations?  Should we instead spread the padding across all of the split frames?

@jpinner I'm moving this discussion here (from #2782 and #2805).

**Comment by Scottmitch** [comment]
@nmittler - I think the current approach we have is adequate ... please reopen if you feel there is work left to do here
