### ISSUE TITLE
Investigate proper handling of truncated HTTP/2 headers

### ISSUE THREAD

**Issue by nmittler** [netty/netty#2809]
The DefaultHttp2HeadersDecoder (which uses Twitters hpack) can encounter truncated results: https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2HeadersDecoder.java#L83

We should investigate the proper way to handle this.

@jpinner any suggestions?

**Comment by Scottmitch** [comment]
Updated code link: https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2HeadersDecoder.java#L70

**Comment by Scottmitch** [comment]
@nmittler - I'll take this issue. There is interest in being able to protect applications from being over-loaded with data. For this reason I'm thinking the default behavior will be to close the connection (with some sort of error), and allow this behavior to be overridable. WDYT?

**Comment by nmittler** [comment]
@Scottmitch SGTM

**Comment by Scottmitch** [comment]
@nmittler - FYI this may also come with other updates to the `DefaultHttp2FrameReader` to protect against accumulating too much data before we dispatch the `Http2Headers` to the `Http2FrameListener` too.

**Comment by Scottmitch** [comment]
This has been resolved since we started supporting a max size for headers.
