### ISSUE TITLE
HTTP/2 interoperability testing

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#2828]
We should run the http2-codec (in both server and client mode) against other implementations of the HTTP/2 spec.  This will be good to answer (and then update the examples) the following questions:
1. How can we configure and run a HTTP/2 compliant server/client w.r.t HTTP/2 security restrictions (http://tools.ietf.org/html/draft-ietf-httpbis-http2-14#section-9.2) in a java environment?
   - Does this require java 8 (for TLSv1.2 and supported ciphers)?  If not does the default `JdkSslContext` `PROTOCOL="TLS"` allow TLSv1.2 to be used for client sockets?
   - Do we have to add support for [jetty alpn](http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html) in netty?
   - Do we have to update the cipher list in `JdkSslContext` or supply a new cipher list specific for HTTP/2 
2. Ensure compatibility in client mode.  Here are some potential servers to test against (https://github.com/http2/http2-spec/wiki/Implementations):
   - [nghttp2](https://nghttp2.org) - test server already setup at this url
   - [Microsoft](https://github.com/http2/http2-spec/wiki/Microsoft-HTTP-2-Prototype)
   - [Akamai](https://github.com/http2/http2-spec/wiki/Akamaighost) - I should be able to get IP to test against
   - [Jetty](http://git.eclipse.org/c/jetty/org.eclipse.jetty.project.git/tree/?h=jetty-http2) - Can we try to find  a server setup for us to test against?
   - Twitter (details not yet known)
3. Ensure compatibility in server mode.  Here are some potential clients to test against (https://github.com/http2/http2-spec/wiki/Implementations):
   - [curl](http://curl.haxx.se/) - uses nghttp2
   - [mozilla](https://wiki.mozilla.org/Networking/http2)

We should also think if this can be done in a repeatable fashion (think regression testing)?  Some of the setup may be prohibitive at this time but it is worth considering.

**Comment by louiscryan** [comment]
@Scottmitch Have you seen

http://tools.ietf.org/html/draft-nakajima-httpbis-http2-interop-survey-00

I'm primarily interested in stress testing flow-control as that is where the bugs are most likely to lie. I did a stress test some time back with

Netty Client -> nghttp2 (in frame forwarding mode) --> Netty Server

and managed to get flow-control stuck. I'd be interested in getting something more automated up and running on github for this kind of thing if we could get some more folks involved. If it already exists even better.

If you have time maybe we could have a quick VC to discuss things HTTP2 related

**Comment by Scottmitch** [comment]
@louiscryan 
> Have you seen
http://tools.ietf.org/html/draft-nakajima-httpbis-http2-interop-survey-00

I just checked it out.  Looks like a good template but seems like a lot of the meat is missing (rational, approach, etc...).


I think it would be good to have some sort of microbenchmark and stress test setup in an automated fashion.  Would be really nice to be able to know if/how changes are impacting performance.
