### ISSUE TITLE
CPU spikes in netty 5 when no requests

### ISSUE THREAD

**Issue by jknair** [netty/netty#2840]
when using netty 5 @ 2128753484311a1854748d0274552e27007429a6 
```
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode) 

uname  -a  
Linux testbox 2.6.18-238.el5 #1 SMP Thu Jan 13 15:51:15 EST 2011 x86_64 x86_64 x86_64 GNU/Linux
```
We have a proxy like application which when loaded tested was working fine but when the request were stopped 2 of the nioeventloops started spiking the CPU. We have been seeing this behaviour quite often but have not been able to reproduce this. We added yourkit to see this issue, sadly couldnt save the snapshopt (yourkit crashed) but I have the following screenshots to explain :

![netty-thread-cpu-yourkit](https://cloud.githubusercontent.com/assets/335487/4072677/f714a132-2e89-11e4-8d57-a6dc0dd0d512.PNG)
![netty-thread-cpu-yourkit-2](https://cloud.githubusercontent.com/assets/335487/4072678/fb930a46-2e89-11e4-8dad-071c929a1593.PNG)
![netty-thread-cpu-htop-3](https://cloud.githubusercontent.com/assets/335487/4072680/fe99629e-2e89-11e4-94c0-f934c992b1d7.PNG)

is this the same as the selector bug in JDK ? if so any workarounds ?

**Comment by normanmaurer** [comment]
Please try again with latest release and let us know if you still see it.
