### ISSUE TITLE
ALPN openssl support

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#2845]
There is no support for ALPN when using the openssl ssl provider. This may also require updates to https://github.com/netty/netty-tcnative.

**Comment by Scottmitch** [comment]
@normanmaurer - It seems like this is still on your plate?  Are you still up for this?

**Comment by normanmaurer** [comment]
@Scottmitch yep... just not top of my to do list

**Comment by Scottmitch** [comment]
@normanmaurer - No problem. Just wanted to make sure the assignment was still valid.

**Comment by Scottmitch** [comment]
@buchgr - FYI. This may be the last piece of the puzzle for HTTP/2 OpenSSL drop in.

Here is an example of OpenSSL ALPN usage:

https://github.com/tatsuhiro-t/nghttp2/blob/master/src/h2load.cc#L429
https://github.com/tatsuhiro-t/nghttp2/blob/master/src/h2load.cc#L1208

Let me know if you have any questions.

**Comment by normanmaurer** [comment]
@Scottmitch cool... Let me work on it :)

**Comment by normanmaurer** [comment]
PR for this: https://github.com/netty/netty/pull/3481

**Comment by normanmaurer** [comment]
Fixed by #3481
