### ISSUE TITLE
HTTP/2 codec responds incorrectly to WINDOW_UPDATE after END_STREAM

### ISSUE THREAD

**Issue by nmittler** [netty/netty#2861]
From @Scottmitch, found while testing against Firefox:

Interesting observation in the above output interacting with the Mozilla client. Note they are sending a WINDOW_UPDATE frame after we received a frame with the END_STREAM set for that stream. I think the stream is in half closed remote state at when we receive the WINDOW_UPDATE and we are responding with a GO_AWAY -> PROTOCOL_ERROR: "Stream does not exist 3". Am I interpreting the state transitions correctly and is our response correct? If I'm interpreting the state correctly I think that the WINDOW_UPDATE is 1 of 3 frames that can be received in this state (according to http://tools.ietf.org/html/draft-ietf-httpbis-http2-14#section-5.1) and other frames warrant a STREAM_CLOSED error response.

**Comment by Scottmitch** [comment]
This issue may be related to (and superseded by) issue https://github.com/netty/netty/issues/3448.

**Comment by nmittler** [comment]
@Scottmitch yup, my thoughts exactly!

**Comment by nmittler** [comment]
@Scottmitch I think we can close this since we now gracefully handle this case.  WDYT?

**Comment by Scottmitch** [comment]
I would expect this to be fixed.  We can open a new issue if necessary.

**Comment by nmittler** [comment]
@Scottmitch SGTM,  thanks!
