### ISSUE TITLE
EmbeddedChannelId doesn't work properly if serialized

### ISSUE THREAD

**Issue by rdicroce** [netty/netty#2869]
I've been debugging an issue with a test in a clustered application, in which a ChannelId is serialized and sent to another node. The test uses EmbeddedChannels, which use EmbeddedChannelId instead of DefaultChannelId.

It's clearly intended that all EmbeddedChannels have the same ID, but the EmbeddedChannelId implementations of compareTo() and equals() don't take serialization into account:
- compareTo() tries to short circuit the comparison by checking if (o == INSTANCE), which fails if the other instance has been deserialized from somewhere. Fortunately, it still succeeds because it compares the long text which is still the same.
- equals() fails completely because it just uses Object#equals(), which returns false since they're not the same instance.

In both cases, a better solution would be to check if (o instanceof DefaultChannelId). Or maybe get rid of EmbeddedChannelId altogether. I don't see any reason an EmbeddedChannel can't have a real ID. In fact, this would be needed to test some scenarios in my application, so there should at least be some way to construct an EmbeddedChannel with a real ID.

**Comment by rdicroce** [comment]
Opened PR #4338 to address these issues.

**Comment by normanmaurer** [comment]
@rdicroce thanks again for the fix :)
