### ISSUE TITLE
Rename the AsciiString class

### ISSUE THREAD

**Issue by nmittler** [netty/netty#2909]
Our implementation of binary headers in HTTP/2 is based around the `AsciiString` class, which seems a slightly odd fit.  Looking at `AsciiString`, it's just a wrapper around a byte[] that implements `CharSequence`.  The `charAt()` method converts a byte to a char by masking with 0xFF, implying the Latin-1 charset (not US-ASCII) ... so already, the name "Ascii..." doesn't seem quite right.

I propose renaming this class to `ByteString`, and then documenting that the `CharSequence` interface implements the Latin-1 charset.  The new name would be a bit more palatable for HTTP/2 and I think would still make sense when used by `TextHeaders`.

What do you guys think?

**Comment by Scottmitch** [comment]
@trustin @nmittler - If we do introduce an additional class `ByteString` into the hierarchy as discussed. Would this be eligible for 4.1 (assuming we can keep the external `AsciiString` interface the same)?  If so would we target this to before the 4.1 release?

**Comment by trustin** [comment]
We didn't release the final version of 4.1 yet, so we are free from the changes.

**Comment by normanmaurer** [comment]
+1 let us just hurry up ;)

**Comment by Scottmitch** [comment]
@trustin - You took the assignment for this one a while back.  Do you still want to handle this?

@normanmaurer +1. The naming of `AsciiString` has already confused a few folks who are using the http/2 codec relative to how we are using it.

**Comment by trustin** [comment]
Assigning to you, @Scottmitch :-)

**Comment by Scottmitch** [comment]
@trustin - humm wasn't aware that I just volunteered :)  I'll see if I have bandwidth for this...something tells me this one is going to hurt....

**Comment by trustin** [comment]
Ah, I thought you were interested. Unassigning at the moment.

**Comment by trustin** [comment]
(Not that I'm uninterested. Just lack of time at the moment.0

**Comment by Scottmitch** [comment]
@trustin - Same mindset on my end.  Any one else have bandwidth?

**Comment by Scottmitch** [comment]
@trustin - I'll take this assignment back.  If we are treating as a blocker for a 4.1 release I would like to make sure this gets done.  Stand by for a review.

**Comment by normanmaurer** [comment]
@Scottmitch thanks!

**Comment by Scottmitch** [comment]
This was done.  Follow up PRs in progress.
