### ISSUE TITLE
Using HttpContentDecompressor with HttpObjectAggregator doesn't handle 100 CONTINUE correctly.

### ISSUE THREAD

**Issue by Dao007forever** [netty/netty#2914]
Hi,

I'm using the following configuration for my pipeline:

```
        pipeline.addLast("decoder", new HttpRequestDecoder(8192, 8192, 8192));
        pipeline.addLast("encoder", new HttpResponseEncoder());
        pipeline.addLast("decompressorHandler", new HttpContentDecompressor());
        pipeline.addLast("aggregator", new HttpObjectAggregator(maxContentLength));
        pipeline.addLast("chunkedWriter", new ChunkedWriteHandler());
```

The issue is the 100 CONTINUE is not propagated immediately to HttpObjectAggregator because it gets stuck at HttpContentDecompressor, so the server doesn't reply with CONTINUE, leaving the client hanging for some time before timing out.

Moving the Aggregator before Decompressor doesn't help as mentioned in #2658, we will get Reference count error.

**Comment by normanmaurer** [comment]
Let me close this as I think we handle this now correctly. Please reopen if you still see the issues with latest netty version
