### ISSUE TITLE
Version 5.0.0.Alpha2 release schedule

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#2933]
@trustin / @normanmaurer - Do we have a time frame on when 5.0.0.Alpha2 is planned to be released?  It may be a good idea to draw a line in the sand and put out a release (in the interest of hopefully getting time on the new code/features).  There are a few issues/PRs that may lead to bigger interface changes (https://github.com/netty/netty/issues/2909, https://github.com/netty/netty/pull/2908) that we may want to discuss what release they should go into. Is it worth scrubbing the 5.0.0.Alpha2 assignments to narrow the window?  WDYT?

**Comment by Scottmitch** [comment]
@trustin - I have heard a rumor that you plan on releasing this month?

**Comment by Scottmitch** [comment]
Depending on when we plan to release PR https://github.com/netty/netty/pull/3353 may be a good one to wait for (impacts 4.1 and 5.0 that the HTTP/2 backport has been merged).

**Comment by normanmaurer** [comment]
Released

**Comment by bglmmz** [comment]
When will the 5.0 be released?

**Comment by bglmmz** [comment]
When will the 5.0 be released?

**Comment by normanmaurer** [comment]
@bglmmz no plans yet. Use 4.1.x

**Comment by Scottmitch** [comment]
Note that 5.0 as it existed a few years ago has been abandoned https://github.com/netty/netty/issues/4466.
