### ISSUE TITLE
[SUGGESTION] ByteBuf Strings

### ISSUE THREAD

**Issue by ensirius** [netty/netty#2936]
How about provide method to read and write strings from buffer?

**Comment by ensirius** [comment]
I am sorry, but i must open this issue again. Because every time i need read or write string i fell pain.    
```java
public void writeString(String string) {
        byte[] bytes = string.getBytes();
        writeInt(bytes.length);
        writeBytes(bytes);
    }```

```java
   public String readString() {
        int len = readVarInt();
        byte[] bytes = new byte[len];
        readBytes(bytes);

        try {
            return new String(bytes, "UTF-8");
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }

        return null;
    }```

**Comment by Scottmitch** [comment]
@ensirius - Basically what you want is a [StringEncoder](https://github.com/netty/netty/blob/master/codec/src/main/java/io/netty/handler/codec/string/StringEncoder.java) that first writes the length (and a corresponding `StringDecoder`)?  If so would you be interested in submitting a PR? Sounds like you have done most of the work already....might as well get credit :)

**Comment by ensirius** [comment]
@Scottmitch If i corretcly understand, it's convert whole ByteBuf to String. This is not what i want. my packet read looks something like that:
```java
        buffer.writeInt(entityId);
        buffer.writeByte(0);
        buffer.writeByte(0);
        buffer.writeByte(2);
        buffer.writeByte(maxPlayers);
        buffer.writeString("default");
        buffer.writeBoolean(false);
```

I can write PR, but i am not sure that i can write good java doc

**Comment by Scottmitch** [comment]
@ensirius - I'm still not entirely sure what you want and how to generalize it, would you mind submitting a PR so I can better understand. We can help with the javadocs if necessary.

**Comment by ensirius** [comment]
https://github.com/ensirius/netty/commit/8ffd9bf6f4fa0bb08cbead2cea2d9cd255012407

**Comment by normanmaurer** [comment]
@ensirius like @Scottmitch said this is really just an encoder / decoder and not really specific to ByteBuf, so I would like to not add it to it. I guess we could add it to ByteBufUtils. @Scottmitch @trustin WDYT ?

**Comment by Scottmitch** [comment]
@normanmaurer - Agreed, lets keep this out of `ByteBuf`.  I'm not against adding it to `ByteBufUtils` (`Charset` will have to be a parameter on the encode/decode side).
