### ISSUE TITLE
HTTP/2 DefaultHttp2HeadersEncoder ByteArrayOutputStream usage

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#2947]
The `DefaultHttp2HeadersEncoder` class uses `ByteArrayOutputStream` because the twitter HPAC interface requires an `OutputStream.`  Would it make sense to use a `ByteBufOutputStream` to avoid the potentially synchronized implementation of `ByteArrayOutputStream`?

**Comment by Scottmitch** [comment]
This may not be needed if we are able to make twitter's HPACK more Netty friendly, or fork twitter's HPACK.  See https://github.com/netty/netty/issues/3503.

**Comment by Scottmitch** [comment]
See https://github.com/netty/netty/issues/3597 for potential HPACK updates.

**Comment by nmittler** [comment]
@Scottmitch I feel like this is a dup of #3597.  Should we just close this?

**Comment by Scottmitch** [comment]
Done.
