### ISSUE TITLE
Websocket examples broken in Chrome (extension negotiation problem)

### ISSUE THREAD

**Issue by Matthias247** [netty/netty#2953]
Hi,

I just discovered that the included WebSocketServer example doesn't work in chrome.
I can open the site in the browser and will get the message `Web Socket opened!`
However after sending a message from the browser netty will close the connection with the following logged error:

```
io.netty.handler.codec.CorruptedFrameException: RSV != 0 and no extension negotiated, RSV:4
at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:365)
at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:164)
```

For me this seems like there is a problem with extension negotiation: Netty acccepts the Chrome websocket extension request despite `allowExtensions` is set to false on the handshaker. If I set `allowExtensions` to true it works.

Chrome http log shows that netty accepts the extension:

Request URL:ws://127.0.0.1:8080/websocket
Request Method:GET
Status Code:101 Switching Protocols

**Request Headers**
Provisional headers are shown
Cache-Control:no-cache
Connection:Upgrade
Host:127.0.0.1:8080
Origin:http://127.0.0.1:8080
Pragma:no-cache
Sec-WebSocket-Extensions:permessage-deflate; client_max_window_bits, x-webkit-deflate-frame
Sec-WebSocket-Key:Urs+rkRJzGp+TRG6HDoqsQ==
Sec-WebSocket-Version:13
Upgrade:websocket
User-Agent:Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36

**Response Headers**
Connection:Upgrade
Sec-WebSocket-Accept:CHHUseBBz5XJ9stOJiBImbNrd5A=
**Sec-WebSocket-Extensions:permessage-deflate**
Upgrade:websocket

**Comment by IsuruLiyanage** [comment]
Is this closed. I still get the error when I'm using websocket server and client from the examples. I tried several branches all have the error. But it works when we i enable ssl.
