### ISSUE TITLE
WriteTimeoutHandler missed cleanup

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#2973]
It seems like the `WriteTimeoutHandler` does not always cancel the timeout task it schedules in all the same cases that the and IdleStateHandler does.  For example the `handlerRemoved` method is not overridden in `WrtieTimeoutHandler`.  There may be other cases where the timeout is not canceled when it should be and further investigation is needed.

**Comment by normanmaurer** [comment]
Fixed
