### ISSUE TITLE
Oversized request closed whenever Expect: 100-continue is not present, version 4.1.0-Beta3

### ISSUE THREAD

**Issue by g-eorge** [netty/netty#2975]
This is a question about an issue I have experienced with the implementation of HttpObjectAggregator.handleOversizedMessage in 4.1.0-Beta3.

When testing with my project I found that oversized requests were being closed prematurely (in the opinion of the client) because the Expect: 100-continue header was missing. [Relevant code here](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectAggregator.java#L166-L168). This caused some of the clients I tested with to fail with 'connection reset by peer' and 'broken pipe' messages.

Now, if it is the intention to be very strict and punish clients for not using the Expect header then that's ok I can provide my own implementation. However, if the intention was not to trigger connection errors in the client, then perhaps [my changes over here](https://github.com/netty/netty/pull/2976) could be helpful?

**Comment by normanmaurer** [comment]
@g-eorge sorry for the delay but I think this is fixed in 4.1.0.Beta6. If the issue still exists please reopen.
