### ISSUE TITLE
Epoll channelInactive delayed/not occuring?

### ISSUE THREAD

**Issue by Harry5573** [netty/netty#2996]
Hello, when using Epoll, if i disconnect my client channelInactive is not called instantly. Instead it appears wait for my ReadTimeoutHandler before it gets called. When using nio, if i disconnect my client channelInactive is called instantly. 

Java Version: 8.0- Server JDK
Operating System: Centos 6 64bit

**Comment by normanmaurer** [comment]
@Harry5573 is this still an issue ? Seems like everything works as expected here.

**Comment by normanmaurer** [comment]
@yinfeifan @Harry5573 let me close this. If the problem still exists let me know and re-open.
