### ISSUE TITLE
ExceptionCaught methods hides exceptions.

### ISSUE THREAD

**Issue by fenoloco** [netty/netty#2997]
If a handler throws an exception on method exceptionCaught, the exception is hidden by netty.
This correct way to handle it or is an issue?

Thanks

**Comment by hithendra** [comment]
Hello trustin, I have implemented write timed out in my application , but this is not working.
Meanwhile read timed out is working fine, I even tried IdleStateHandler , but no use.

Can I know when writeTimedout will fire ?

**Comment by trustin** [comment]
@hithendra Wrong thread. What made you think it's the right place to ask that question? I don't see any relevance to the original discussion.

**Comment by trustin** [comment]
Let me close and lock this issue for now. Please open a new issue if you find something new.
