### ISSUE TITLE
provide a better way to fire/trigger userEvent from out side of netty pipeline/thread model

### ISSUE THREAD

**Issue by He-Pin** [netty/netty#3002]
Background:
Hi,currently I am using netty with akka,and using netty to implement the io model just as akka.io.
I have a `NettyTcpManager` actor,which start the netty `serverBootstrap` and when a client connected in,in the callback of `onChannelActive(ctx:ChannelContext)`,I send a message `case class ChannelActive(ctx:ChannelContext)` to the `NettyTcpManager` actor,then it create a child Actor,and trigger an user defined event with
`case class SocketActorRegister(socketActor:ActorRef)` on the `channelContext` .And then at the end of the pipeline,When I handled the `userEventTriggered(event:Object)`,and then I cached the `socketActor` and then forward all the inbound messages to the `socketActor`.

Problem:
Cause I want to trigger an `UserEvent` inside the SocketActor,I have to make some call like below:

```
//not ok
ctx.fireUserEventTriggered(SocketActorRegister(socketActorRef))
```

or

```
//not ok
ctx.exector().execute(new runnable(){
   override run(){
      ctx.fireUserEventTriggered(SocketActorRegister(socketActorRef))
   }
})
```

or

```
//ok
ctx.pipeline().fireUserEventTriggered(SocketActorRegister(socketActorRef))
```

or

```
//ok
ctx.exector().execute(new runnable(){
   override run(){
      ctx.pipeline().fireUserEventTriggered(SocketActorRegister(socketActorRef))
   }
})
```

or

```
//ok
        channel.eventLoop().submit(new Runnable {
          override def run(): Unit = {
            channel.pipeline().fireUserEventTriggered(SocketActorRegister(self))
          }
        })
```

or

```
//ok
        channel.pipeline().fireUserEventTriggered(SocketActorRegister(self))
```

the problem is that,the ctx.fireUserEventTriggered will never trigger an event,even the ctx is got via 
`ctx.pipeline.firstContext`,or event in the `ctx.exector.execute/submit`.
but I could trigger an user defined event via `pipeline.fireUserEventTriggered(event:Object)`

so,should this be the right behavior,or need add any method for an user could safely trigger an event out side the netty thread model,like in `Actor`'s `onReceive` block?

**Comment by icedmilk** [comment]
seems the ChannelHandlerContext.fireXXX will trigger the operation on the next handler in the pipeline, not the current handler associated with the current handler

**Comment by Aitozi** [comment]
I think `ChannelHandlerContext.fireUserEvent` will try to invoke the `invokeUserEventTriggered(findContextInbound(),event)` and the `findContextInbound` will find the most closely inbound ctx from the current ctx, may be the next one. But the `ctx.pipeline().fireUserEvent()` will finally fireUserEvent on the `pipeline.next` which is `HeadContext`. Maybe this is the difference.
