### ISSUE TITLE
Cannot use OpenSsl on Debian 7 (Wheezy) and Ubuntu 12.04 (Precise)

### ISSUE THREAD

**Issue by blucas** [netty/netty#3005]
I am running a standard install of Ubuntu 12.04 and Debian 7 and installed the required libraries as follows below, but JNI fails to load the libraries.  Please see the steps I took below for more details on how to reproduce the issue.  I am using Netty 5.

```
root@debian:~# uname -a
Linux debian 3.2.0-4-amd64 #1 SMP Debian 3.2.60-1+deb7u3 x86_64 GNU/Linux

# Installed necessary libraries
root@debian:~# apt-get install openssl libapr1

# Echo installed libraries
root@debian:~# dpkg -l | grep -E "openssl|libssl|apr"
ii  libapr1                            1.4.6-3+deb7u1               amd64        Apache Portable Runtime Library
ii  libssl1.0.0:amd64                  1.0.1e-2+deb7u12             amd64        SSL shared libraries
ii  openssl                            1.0.1e-2+deb7u12             amd64        Secure Socket Layer (SSL) binary and related cryptographic tools

# Determined libssl and libcrypto are installed in /usr/lib/x86_64-linux-gnu
root@debian:~# dpkg -L libssl1.0.0
...
/usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
...

# As JNI references libssl and libcrypto as 'libssl.so.10' and 'libcrypto.so.10' respectively, 
# I created symbolic links to the files above
root@debian:~# ln -s /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 /usr/lib/x86_64-linux-gnu/libssl.so.10
root@debian:~# ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /usr/lib/x86_64-linux-gnu/libcrypto.so.10

# Confirm *.so files are in the right places:
root@debian:~# ls -latr /usr/lib/x86_64-linux-gnu/libcrypto*
-rw-r--r-- 1 root root 2048480 Aug  6 19:50 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
lrwxrwxrwx 1 root root      44 Oct 14 21:51 /usr/lib/x86_64-linux-gnu/libcrypto.so.10 -> /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0

root@debian:~# ls -latr /usr/lib/x86_64-linux-gnu/libssl*
-rw-r--r-- 1 root root 391944 Aug  6 19:51 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
lrwxrwxrwx 1 root root     41 Oct 14 21:50 /usr/lib/x86_64-linux-gnu/libssl.so.10 -> /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0

root@debian:~# ls -latr /usr/lib/libapr*
-rw-r--r-- 1 root root 202120 Jul  7  2013 /usr/lib/libapr-1.so.0.4.6
lrwxrwxrwx 1 root root     17 Jul  7  2013 /usr/lib/libapr-1.so.0 -> libapr-1.so.0.4.6
```
When I run my test app that tries to use netty's OpenSsl support, I get the following error:
```
java.lang.UnsatisfiedLinkError: /tmp/libnetty-tcnative8018331010701115954.so: /usr/lib/x86_64-linux-gnu/libssl.so.10: version `libssl.so.10' not found (required by /tmp/libnetty-tcnative8018331010701115954.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
        at java.lang.Runtime.load0(Runtime.java:795)
        at java.lang.System.load(System.java:1062)
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:193)
        at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:39)
```

@trustin Could you please let me know which specific versions of libssl, openssl, and libapr1 are actually working on your installation (I know its for a different distro, but it might help solve this).

I'm guessing the actual **version** of libssl I am using (which is the latest version available) is not supported by libnetty-tcnative.  Lets not forget that around two months ago the Heartbleed bug was found in openssl/libssl and they had to release new versions to fix it.

@normanmaurer /CCing you in here, just for fun :smile: Plus you love this stuff

**Comment by trustin** [comment]
Running the following command against the .so file in the netty-tcnative JAR file might fix this issue:

```
patchelf --replace-needed libssl.so.10 libssl.so \
        --replace-needed libcrypto.so.10 libcrypto.so libnetty-tcnative.so
```

If it does not work, try this:

```
patchelf --replace-needed libssl.so.10 libssl.so.1.0.0 \
        --replace-needed libcrypto.so.10 libcrypto.so.1.0.0 libnetty-tcnative.so
```

Oh, you will need to build patchelf by yourself from its master branch: https://github.com/NixOS/patchelf because the `--replace-needed` option has been added very recently.

**Comment by trustin** [comment]
Following [this instruction](http://netty.io/wiki/forked-tomcat-native.html#wiki-h4-4) fixes the problem for me.

Because I have no idea how to fix this at the build time of libnetty-tcnative.so, I'd like to write more user-friendly error message when loading OpenSSL fails with a certain exception message.

@blucas what do you think?

**Comment by blucas** [comment]
Hey @trustin sorry for the late response.  Thanks for looking into this, I know its not a simple task to resolve.  I haven't had a chance to try your ```patchelf``` suggestion, but a few weeks ago I did manage to get OpenSSL + netty-tcnative to work by compiling OpenSSL from source. @normanmaurer was the one who tried it first.  Below are the instructions he gave me (which seem to be more straightforward than your example of building and modifying OpenSSL).

```
wget https://www.openssl.org/source/openssl-1.0.1j.tar.gz
tar xfvz openssl-1.0.1j.tar.gz
cd openssl-1.0.1j
./config --prefix=$someplace/openssl-current shared  
make dep && make && make install

ln -s $someplace/openssl-current/lib/libssl.so.1.0.0 $someplace/openssl-current/lib/libssl.so.10
ln -s $someplace/openssl-current/lib/libcrypt.so.1.0.0 $someplace/openssl-current/lib/libcrypt.so.10

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$someplace/openssl-current/lib 

java -jar ...
```
You mention in your instructions that building and installing netty-tcnative locally would also solve the problem.  As it doesn't sound like there is a way to fix this in the source code, would it be possible to provide another jar for debian based builds?  Similar to how you ship netty-tcnative-linux, maybe you could make a netty-tcnative-linux-debian?

**Comment by normanmaurer** [comment]
You can now use it with netty-tcnative-1.1.33.Fork6 using linux-x86_64_debian classifier

**Comment by trustin** [comment]
You had to use hyphen as a separator, though. :-)

**Comment by normanmaurer** [comment]
@trustin honestly this is just a "hack" and I plan to do a better way to do this in the next release.
