### ISSUE TITLE
AggregatedFullHttpMessage toString()

### ISSUE THREAD

**Issue by d-t-w** [netty/netty#3019]
HttpObjectAggregator was modified in commit dfa5a889789526273504024c2bd9cf9683a095de to produce AggregatedFullHttpMessage rather than DefaultFullHttpMessage.

The behaviour of toString() on the FullHttpMessage provided by HttpObjectAggregator has changed:
- DefaultFullHttpMessage toString() does not access the content of the message
- AggregatedFullHttpMessage toString() does (it defaults to DefaultByteBufHolder toString())

this means you cannot log/prn/toString a FullHttpMessage decoded by the HttpObjectAggregator which has been released, whereas previously you could.

I'm happy to provide PR with toString for AggregatedFullHttpMessage which mimics previous if that helps.

**Comment by normanmaurer** [comment]
Fixed by #3638
