### ISSUE TITLE
NioDatagramChannel.newSocket() fails on Java 1.6

### ISSUE THREAD

**Issue by Kenishi** [netty/netty#3022]
The download page on the website states:

>Please note that Netty has no mandatory external dependencies. JDK 1.5 (1.6 for Netty 4+) or above is all that you need to run Netty.

In an app on Mac OS X 10.9 running Java 1.6; however, attempting to create a new NioDatagramChannel, while running Netty 4.1 Beta3, will cause an `UnsupportedOperationException`. When `NioDatagramChannel.newSocket() [L:98]` is called it will call `checkJavaVersion().` A check will be made: `if(PlatformDependent.javaVersion() < 7)` and then the exception is thrown:
`java.lang.UnsupportedOperationException: Only supported on java 7+.`

If 4.1 can't handle datagram sockets on Java versions < 1.7 then a note should be added to the site. Otherwise, this seems like a bug.

**Comment by normanmaurer** [comment]
@Scottmitch I think all the dependencies can be found in the pom.xml of the modules. So let me close it
