### ISSUE TITLE
Any idea for netty rest support ?

### ISSUE THREAD

**Issue by bwzhang2011** [netty/netty#3023]
@normanmaurer  or @trustin , as you know, rest architecture is popular in current web application and there're also some solution or project build on netty to support rest. but it always force you to rely on pure on that framework or lib which lost the simplicity of netty itself. I think netty could add some basic support for that as the basic standard.  the basic implementation is somewhat the support compared with the JAX-RS.  I think it would be some good idea for netty should take care of some application integration support just consider to be the enhacement for http or http2.

**Comment by bwzhang2011** [comment]
I think it's time to close such issue as @ngocdaothanh  has set up such support while others check the review continuously . thanks for any one could pay more attention to those.

**Comment by michaelwq** [comment]
Hi, are there any ways to write a pure netty rest support without any frameworks like restExpress?
