### ISSUE TITLE
If there are some Chinese characters in url, HttpRequest.getUri(), the return is messy code

### ISSUE THREAD

**Issue by zhanggang807** [netty/netty#3035]
code example:
Initializer:
    cp.addLast("httpReqDecoder", new HttpRequestDecoder());
    cp.addLast("httpObjectAggregator", new HttpObjectAggregator(65536));  
    cp.addLast("httpResEncoder", new HttpResponseEncoder());  
    cp.addLast("chunkedWriteHandler", new ChunkedWriteHandler());

the request url in IE is: http://127.0.0.1:11299/someurl.jsp?keyword=中国汉字

the return result of HttpRequest.getUri() is /someurl.jsp?keyword=ￖ￐ﾹ￺ﾺﾺￗￖ

What can I do to resovle this problem?

tips:
    IE does not encode the url, but chrome encode the url with UTF-8.
    for example in chrome:
    http://127.0.0.1:11299/someurl.jsp?keyword=中国汉字
    the result is:
    /someurl.jsp?keyword=%E4%B8%AD%E5%9B%BD%E6%B1%89%E5%AD%97

**Comment by wlwinston** [comment]
@zhanggang807 这个主要是因为IE传输URL时，会采用ISO8859-1编码格式传输，需要在服务端进行一次转码才可以获取到正确的中文。Chrome会把URL先encoding一下，所以没关系
