### ISSUE TITLE
QueryStringDecoder shouldn't replace semicolons in URI path with ampersands

### ISSUE THREAD

**Issue by yborovikov** [netty/netty#3044]
This patch: https://github.com/netty/netty/issues/72 introduced unconditional conversion of all semicolons in URI to ampersands.
Referenced W3C recommendation is applicable to query string part of URI only. Current implementation doesn't follow the standard and breaks matrix URI parameters (see http://www.w3.org/DesignIssues/MatrixURIs.html).

**Comment by povman** [comment]
I'm running into this one too. Qt's URL building functions don't encode `;` because technically they aren't required to do that if you are using `&` as query parameter separator. Thus netty receives a URL like `http://localhost/query/?a=hello;world&b=123` and interprets it as having 3 parameters where only 2 were intended by the client.

I think there needs to be a way to configure the query parameter separators.

See also https://bugreports.qt.io/browse/QTBUG-50843, in particular the first comment.

**Comment by slandelle** [comment]
I agree that `;` is a legit query character, as explained in [RFC3986](http://tools.ietf.org/html/rfc3986#section-3.4) and that Netty is buggy here.

Then, as the developper of an HTTP client, I constantly face broken servers that don't properly implement RFC3986, and users who have no idea about what they're doing.

A typical example of the latter is the reporter of the bug @povman mentioned. This user failed to realize he's comparing apples and oranges: he uses an online tester for **application/x-www-form-urlencoded** form submitting. This encoding is specified in the [HTML5 spec](https://www.w3.org/TR/html5/forms.html#url-encoded-form-data) and its safe-to-not-percent-encode character list is more restrictive than what's allowed by the URI spec (e.g. `/` and `;` have to be percent-encoded).

**Comment by yborovikov** [comment]
While `;` is indeed legitimate (doesn't need to be percent-encoded) in query part of URI - so is `&`. Both are allowed in query part but have special meaning (as name value pair delimiters), according to this [W3C recommendation](https://www.w3.org/TR/1999/REC-html401-19991224/appendix/notes.html#h-B.2.2), whether we like it or not.

Closing this particular issue as a duplicate of https://github.com/netty/netty/issues/1833, which was fixed by https://github.com/netty/netty/commit/2243970294565ebe2c045345f9a06be0973ab94a in 4.1 and https://github.com/netty/netty/commit/ca2ee88d19b6d7036b98366f5cb6046dddb1f97b in 3.x.

**Comment by povman** [comment]
My suggestion was to make this behaviour configurable. Not all standards-compliant clients will encode the semicolon, and Netty should allow this behaviour.
