### ISSUE TITLE
HTTP/2 avoid calling readClientPrefaceString for each decode

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3048]
It would be nice not to have to call `readClientPrefaceString` in the [decode](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L365) method every time.  It may be nice to separate all the preface processing such that there are 2 `ByteToMessageDecoder` objects.  One with a lifetime just long enough to process the preface, and when the preface is completed it creates the second `ByteToMessageDecoder` which does not have to worry about the preface at all.

**Comment by Scottmitch** [comment]
We should also be able to avoid `verifyPrefaceReceived` in each `onXXXRead` with this change too.

**Comment by nmittler** [comment]
Just to update the original link, I think this is the line we're talking about: https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L397

@Scottmitch IIRC, this is actually how we used to have things arranged a while back, but it probably makes sense to consider looking at it again.  Were you thinking of putting a PR together or shall I?

**Comment by Scottmitch** [comment]
@nmittler - Thanks for providing an updating link...code moved around a bunch :)

I can pull something together.

**Comment by Scottmitch** [comment]
@nmittler - I have a PR for this.  Notable changes:

1. `Http2ConnectionHandler` does not directly inherit from `ByteToMessageDecoder` and instead delegates the decoding to an internal member variable.  The actual instance is switched between a `pre initialed decoder` and a `post initialized decoder` depending on connection state (preface sent etc...).  
2. [DefaultHttp2ConnectionDecoder.internalFrameListener](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L39) is no longer final, and a similar technique is used as described in 1 (instance type is switched after initialization). [DefaultHttp2ConnectionDecoder.prefaceSent](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L45) is also gone.

**Comment by Scottmitch** [comment]
See PR #3542
