### ISSUE TITLE
netty's snappy encoder's performance is low. 

### ISSUE THREAD

**Issue by longlong524** [netty/netty#3049]
I use netty's snappy encoder and protocol buffer's encoder to transfer objects.
Test environment:
server: 192.168.2.162, client:192.168.2.53
the client connect to server and server will transfer 10W object to client with protocol buffer and snappy.
we get this result: ALL TIME=BUILD TIME+WRITE TIME+FLUSH TIME
ALL TIME:44.3S
BUILD TIME：1.4S
WRITE TIME：38.6S
FLUSH TIME：4.4S

we spend to much time in write. We test WRITE TIME:
get this: WRITE TIME=ENCODE TIME+OTHERS
WRITE TIME: 36.2S
ENCODE TIME:31.02S
OTHERS:5.18S

These results prove the  netty's snappy encoder have some performance problems.

So I write my own snappy encoder and decoder with dain's snappy library(https://github.com/dain/snappy).
I got this:
ALL TIME=BUILD TIME+WRITE TIME+FLUSH TIME
ALL TIME:21.3S
BUILD TIME：2.1S
WRITE TIME：11.3S
FLUSH TIME：7.8S

So netty's snappy encoder can be optimized.

**Comment by edwinchoi** [comment]
I ran into this issue as well. Attaching a profiler showed the majority of the time being spent in Snappy.findMatchingLength (specifically calls to getInt, which does a boundary check and volatile read in refCnt). Changing the code to use Unsafe with ByteBuf.array and ByteBuf.memoryAddress improved the performance significantly in my case.

**Comment by normanmaurer** [comment]
Can you show us the code?

**Comment by edwinchoi** [comment]
Sure, I'll work on coming up with an example demonstrating the changes over the weekend (can't share the actual code).

**Comment by normanmaurer** [comment]
Thanks!

**Comment by edwinchoi** [comment]
Modified Snappy.java:
https://gist.github.com/edwinchoi/160167e063a3d671a24e

Original:
https://github.com/netty/netty/blob/5725e804bcfbd0c76e0f11e7911a76970eb06c8c/codec/src/main/java/io/netty/handler/codec/compression/Snappy.java

Changes were only made to `findMatchingLength`, which is where `getInt` showed up as a hot spot.

**Comment by trustin** [comment]
@edwinchoi Do you have some numbers, like before/after vs. other Snappy impls (Dain's for example)?

**Comment by trustin** [comment]
@edwinchoi Oh, and would you mind if I ask you to sign the ICLA? http://netty.io/s/icla

**Comment by edwinchoi** [comment]
@trustin no, I have not run any microbenchmarks. For my specific case, I measured based on the application throughput (overall improvement was ~33% on highly compressible data). So these changes are biased against my workload. I expect there to be little to no improvement if the data were completely random.
I'll look into measuring and optimizing this more generally when I have some free time (and will look over / sign ICLA as well).

**Comment by normanmaurer** [comment]
We did many improvements... Lets close this for now
