### ISSUE TITLE
Issue with loading library in barchart-udt-bundle-2.3.0.jar 

### ISSUE THREAD

**Issue by shivakishoret** [netty/netty#3054]
Netty version: 4.1.0.Beta3

Context:
Iam using Netty to make HTTP Request and Response go over UDT at transport layer on Android Operating system. Netty is internally using barchart-udt-bundle-2.3.0.jar for UDT Channel communication. While I try to install my app using eclipse and Android SDK tools r23, I get the below error:

The library 'barchart-udt-bundle-2.3.0.jar' contains native libraries that will not run on the device.
Additionally some of those libraries will interfer with the installation of the application because of their location in lib/
lib/ is reserved for NDK libraries.
The following libraries were found:
lib/arm-Linux-gpp/jni/libbarchart-udt-core-2.3.0-SNAPSHOT.so

Steps to reproduce:
1. Add barchart-udt-bundle-2.3.0.jar to the project build path
2. Try to run the project using ADT from eclipse 

$ java -version
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)

Operating system: Ubuntu Linux 14.04 64-bit

$ uname -a
Linux <pc-name> 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
the udt transport was deprecated so I will just close this
