### ISSUE TITLE
AbstractNioMessageChannel not passing pipeline exceptions to exceptionCaught

### ISSUE THREAD

**Issue by shevek-nebula** [netty/netty#3059]
AbstractNioByteChannel wraps  ChannelPipeline.fireChannelRead() in a try/catch which passes any exceptions through to ChannelPipeline.fireExceptionCaught(). (try: line 113, fireRead: line 130, catch: line 160, -> handleReadException())

AbstractNioMessageChannel ( does NOT. It ONLY wraps the actual socket read in the try/catch. (fireRead: line 92).

In order to get "normal" exception reporting behaviour on an NioDatagramChannel, it is necessary to have an extra inbound handler which wraps all pipeline calls in a try/catch and forwards to exceptionCaught manually.

Please can UDP message channels handle exceptions in the "normal" manner, as right now they vanish into the ether.

Sidenote: It's very easy for Netty to "lose" exceptions. Even in the Byte case, the extra fireChannelRead() in the exception path may itself throw an exception which (a) masks the original exception, and (b) is itself lost.

**Comment by normanmaurer** [comment]
This is still valid.. Need to be fixed

**Comment by normanmaurer** [comment]
@shevek-nebula actually I just spend some time here and I think there is no risk to miss something here. Each pipeline.fire* call will take care of catch and propagate the exception by itself. So I think it is fine... Still I guess we should make it more consistent. WDYT ?

**Comment by normanmaurer** [comment]
Closing it... @shevek-nebula if you still think there are problems please reopen.
