### ISSUE TITLE
EpollDatagramChannel never calls fireChannelActive() after connect()

### ISSUE THREAD

**Issue by shevek** [netty/netty#3066]
NioDatagramChannel extends AbstractNioChannel and AbstractNioUnsafe call fulfillConnectPromise(), which calls fireChannelActive()

AbstractEpollUnsafe and EpollDatagramChannel have no equivalent call, so channelActive() is never called on the pipeline.

**Comment by normanmaurer** [comment]
Fixed... sorry for the delay.
