### ISSUE TITLE
Reduce the memory consumption of the tests

### ISSUE THREAD

**Issue by trustin** [netty/netty#3075]
Our CI system has been crashed.  We've been enjoying the advantage of using a dedicated machine for CI, but it probably does not justify the cost of maintaining it.

To migrate our builds to other SaaS CI providers, we should make sure our tests do not consume too much memory.  CircleCI and TravisCI for example fail to build Netty because of their memory limit (about 2GB)

/cc @Scottmitch

**Comment by normanmaurer** [comment]
Actually I did some work here and now its a lot better... let me close this
