### ISSUE TITLE
Memory leak in OrderedMemoryAwareThreadPoolExecutor if channel close event does not go through it

### ISSUE THREAD

**Issue by ghost** [netty/netty#3077]
OrderedMemoryAwareThreadPoolExecutor uses Channel instances as ChildExecutor keys (see OrderedMemoryAwareThreadPoolExecutor.getChildExecutorKey(ChannelEvent)).

Entries are removed from the childExecutors map in OrderedMemoryAwareThreadPoolExecutor only if a ChannelStateEvent is processed and the channel is closed (see OrderedMemoryAwareThreadPoolExecutor.getChildExecutor(ChannelEvent)). **This effectively means that if such event does not go through the executor, channels will be leaked.** Even though the map is weak, the parent class contains another map (channelCounters) which is not weak and prevents the instances from being garbage collected.

Ironically, the javadoc of OrderedMemoryAwareThreadPoolExecutor states that:

> Please be very careful of memory leak of the child executor map. You must call removeChildExecutor(Object) when the life cycle of the key ends (e.g. all connections from the same IP were closed.)

Actually, if the Channel is used as key the key life cycle ends not when the ChannelStateEvent is processed by the executor, but  when the channel is closed. So I would expect that entries are removed from the map via a channel close listener - similarly to what is done in OrderedDownstreamThreadPoolExecutor.

In our case we use a separate OrderedMemoryAwareThreadPoolExecutor to handle rare events, the processing of which requires extensive intervals where the treads simply wait, hence we don't want to block worker threads. This executor does not recevieve any ChannelStateEvents - they rather go through the regular worker executor so we end up with this memory leak.

**Comment by normanmaurer** [comment]
Netty 3 is EOL please upgrade
