### ISSUE TITLE
jcraft.zlib deprecated members

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3105]
jcraft.zlib has deprecated a portion of the Inflater and Defalter interfaces which are used by JZlibDecoder and JZlibEncoder.  We should clean this up and avoid using the deprecated interfaces.

**Comment by normanmaurer** [comment]
@Scottmitch I just looked through the code and at least intellij did not show me any warnings regarding `@deprecated` usage. Are you sure this still applies ?

**Comment by Scottmitch** [comment]
@normanmaurer - Yes it looks like it is still an issue. `com.jcraft.jzlib.Inflater` extends `ZStream` which has been deprecated. The majority of the usages of the `Inflater` in [JZlibDecoder](https://github.com/netty/netty/blob/master/codec/src/main/java/io/netty/handler/codec/compression/JZlibDecoder.java) are deprecated, and `Deflater` in [JZlibEncoder](https://github.com/netty/netty/blob/master/codec/src/main/java/io/netty/handler/codec/compression/JZlibEncoder.java#L38).

**Comment by normanmaurer** [comment]
@Scottmitch strange enough intellij shows no warnings... I will check again tomorrow and fix it

**Comment by Scottmitch** [comment]
@normanmaurer - Thanks!

**Comment by normanmaurer** [comment]
@Scottmitch I may be confused but for me it looks like they only deprecated `ZStream` in terms of make it "package-private" later. So I think we are good in terms of API usage.

See also:
https://github.com/ymnk/jzlib/blob/1.1.3/src/main/java/com/jcraft/jzlib/ZStream.java#L43

**Comment by Scottmitch** [comment]
@normanmaurer - Yes it seems that is their intention. However that doesn't change the fact that we are using deprecated code. Are you suggesting we should take no action and continue to use deprecated code?

**Comment by Scottmitch** [comment]
@normanmaurer - After further investigation I agree with you. Eclipse is not being "smart" in this case and the methods should be fine to use. Sorry for the noise (+1 for IntelliJ :cry:).

**Comment by normanmaurer** [comment]
@Scottmitch thanks... I almost thought I'm crazy =P

**Comment by Scottmitch** [comment]
@normanmaurer - Nope its just me :stuck_out_tongue_winking_eye: (and Eclipse)
