### ISSUE TITLE
Could DefaultHttp2FrameReader#readSettingsFrame delegation of settings be optional.

### ISSUE THREAD

**Issue by danbev** [netty/netty#3133]
In [DefaultHttp2FrameReader#readSettingsFrame](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameReader.java#L485) the settings are passed along the pipeline. 
Without a channel handler for the settings, you will see the following debug level message:
```shell
[nioEventLoopGroup-1-1] DEBUG io.netty.channel.DefaultChannelPipeline - Discarded inbound message {INITIAL_WINDOW_SIZE=131072, MAX_FRAME_SIZE=16384} that reached at the tail of the pipeline. Please check your pipeline configuration.
```
Would it be possible to make this delegation optional, or force the ```Http2FrameListener``` implementation to make this call if such delegation is desired?

I get the feeling that I'm not understanding the benefit of this, but would be interested in learning about the use case. 

Thanks

**Comment by Scottmitch** [comment]
Closing issue. I believe this was resolved by #3134.
