### ISSUE TITLE
Add the server SslContext factory methods that require only a single PKCS12 file

### ISSUE THREAD

**Issue by trustin** [netty/netty#3140]
@dparmar said at #3139:
> BTW, I have one question related to Netty SSL context. Why does it expect certChainFile and keyFile separately? Can we have an API in future versions which expects one PKCS12 file?

**Comment by normanmaurer** [comment]
@trustin I think we can close this now as we allow to configure SslContext via a PrivateKey and Certificate and how these are build is up to the user.

**Comment by Spikhalskiy** [comment]
@normanmaurer The doc states that netty works only with pkcs8: https://netty.io/wiki/sslcontextbuilder-and-private-key.html
While according to this thread it looks like PKCS12 can be used with netty's SslContext. May the doc be improved to provide more context on how formats other than PKCS8 can be used?
