### ISSUE TITLE
How to handle pooled ByteBufs and 0..N potential users of it

### ISSUE THREAD

**Issue by daschl** [netty/netty#3152]
Hi Folks,

in the Couchbase Java SDK, we use the `PooledByteBufAllocator` by default, but are running into a hard case to solve with `ByteBufs` and a unknown (zero to N possible "subscribers") of it.

So we are using it together With RxJava, and maybe it's not possible to solve with netty tools only but I thought asking and giving it a shot.

We are creating responses coming back from the server and exposing our nice little ByteBufs to whoever wants to consume it.

Now we have three cases:
- No one ever wants to consume the ByteBuf
- One user consumes the ByteBuf
- N users consume the same ByteBuf

The "one" case we could easily handle and say: hey user, here is your ByteBuf and make sure to release it when you don't need it anymore.

The tricky part is with the N consumers, because we don't know when they will consume it (or at all). And if noone consumes it, we need to think about releasing it before it gets GCed. We don't have destructors in Java, so a different solution needs to come up.

@normanmaurer @trustin any ideas on how to handle this with netty tools only? I have no problems in shipping a custom allocator or to do some magic with the refcounts, but I'm a little stuck on how to approach this in a generic way. Maybe you have some ideas :)

(And btw, I know the RxNetty guys are running into similar issues, but they have solutions with some tradeoffs that I don't really like and we might go somewhere else here)

**Comment by normanmaurer** [comment]
Let me close this discussion for now.
