### ISSUE TITLE
HttpObjectAggregator does not suppress channelReadComplete() when aggregation is not finished yet

### ISSUE THREAD

**Issue by trustin** [netty/netty#3168]
`HttpObjectAggregator` does not implement `channelReadComplete()` properly, resulting in seemingly duplicate `channelReadComplete()` events.  For example, where the pipeline looks like the following:

```
--> HttpRequestDecoder --> HttpObjectAggregator --> ..
```

`HttpRequestDecoder` could trigger the following events:

1. channelRead(HttpRequest)
1. channelReadComplete()
1. channelRead(HttpContent)
1. channelReadComplete()
1. channelRead(LastHttpContent)
1. channelReadComplete()

`HttpObjectAggregator` should trigger the following events:

1. channelRead(FullHttpRequest)
1. channelReadComplete()

However, the current behavior is:

1. channelReadComplete()
1. channelReadComplete()
1. channelRead(FullHttpRequest)
1. channelReadComplete()

**Comment by trustin** [comment]
Related pull request: #3263

**Comment by trustin** [comment]
I like the idea of #3263 and just finished the first round of review.

**Comment by normanmaurer** [comment]
Fixed by  #3263
