### ISSUE TITLE
Wait free extensible hash map

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3169]
Anyone interested in data structures may be interested in the following http://samos-conference.com/Resources_Samos_Websites/Proceedings_Repository_SAMOS/2013/Files/2013-IC-20.pdf.  I haven't look at it in detail but sounds interesting...wonder if it can be used to supplement ConcurrentHashMap?

**Comment by maseev** [comment]
It looks like ```NonBlockingHashMap``` from Cliff Click has been [added](https://github.com/JCTools/JCTools/releases/tag/v2.0) to JCTools among other non-blocking collections. I'm not sure if it's wait-free, but it looks promising. Maybe it's worth checking this thing out. WDYT?

**Comment by normanmaurer** [comment]
I think we can close this
