### ISSUE TITLE
Print the full thread dump on test timeout

### ISSUE THREAD

**Issue by trustin** [netty/netty#3172]
Otherwise it is sometimes difficult to analyze the test timeout reported by our CI server - e.g. #3138 

We could write a JUnit `RunListener` that prints the full thread dump when the test fails with timeout, and also do some additional operations like triggering GC when running a leak test.

The Maven surefire plugin allows us to specify the listener in the pom:

```
          <properties>
            <property>
              <name>listener</name>
              <value>...NettyRunListener</value>
            </property>
          </properties>
```

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4931
