### ISSUE TITLE
Netty 4.0.23 High CPU usage

### ISSUE THREAD

**Issue by chengy-actionsoft** [netty/netty#3182]
hi,all,is there a soluting to fix this problem?
jdk 1.7.0_60-b19
windows 2008 r2 sp 1

NioEventLoop.select(NioEventLoop.java:622)

I see some topic around this,such as  https://github.com/netty/netty/issues/327,it seems it has resolved.
So which versions is ok?Can anybody help...

**Comment by WhiteTrashLord** [comment]
I had a similar problem some while ago. It's possible that something else uses the CPU? In my case it was the SSLHandler. I found out that some profilers are so bad that they show the wrong methods for the CPU usage. You should also test it under Linux.

**Comment by cbatson** [comment]
I have been trying to make sense of this issue for ages. I'm wondering if it's not a problem with profiling: http://www.brendangregg.com/blog/2014-06-09/java-cpu-sampling-using-hprof.html

**Comment by normanmaurer** [comment]
Yep I think it is related to profiling... let me close this
