### ISSUE TITLE
ByteBuf handler able to address both read and write backed to real file?

### ISSUE THREAD

**Issue by fredericBregier** [netty/netty#3207]
I would like to try to implement a ByteBuf handler using file as backend both for read and write (not only one way).
Currently there are:
- ByteBufInputStream only capable to simulate an InputStream from a ByteBuf, respectively ByteBufOutputStream with OutputStream from a ByteBuf
- ChunkedInput able to act on File or RandomAccessFile as write to a channel with a ChunkedWriteHandler
- FileRegion (and DefaultFileRegion) able to act on a FileChannel as write to channel
- AbstractDiskHttpData is merely the most close to what I would like (backend is a file and filechannel)

Before trying anything, I would like to see if this is a good idea or not, and what could be ideas from anyone?

What I have in mind as capacity:
- being able to specify as a source or destination either a file, either a Filechannel (in or out mode), either a InputStream/OutputStream: but the issue is that if anything else than a file, only one way will be possible
- maybe other source/destination (mapped file ?)
- being able to use it both in write (as in FileRegion or ChunkedInput) or as in read (as in AbstractDiskHttpData) in order to limit the effort on writing/reading process from buffer

I don't know if its purely feasable since it will probably need to first have an handler that extract this buffer part out of "protocol" part (for instance first byte being the size of the packet until last packet where size = 0). But I think that making such an handler may interest some people.

WDYT?

**Comment by trustin** [comment]
Yeah, possibly.  Will take a stab of it this quarter.

**Comment by normanmaurer** [comment]
Let me close this for now... There was no-one that seems to be interested to work on it
