### ISSUE TITLE
First class little-endian support

### ISSUE THREAD

**Issue by trustin** [netty/netty#3209]
https://groups.google.com/d/topic/netty/T7L4gTUtNIE/discussion

In the environment where the byte order of most in-production CPUs is little-endian, it is often beneficial to use native order rather than network order for maximum efficiency.

However, our little endian support is pretty poor - a user has to create a `SwappedByteBuf` for each `ByteBuf`. It gives performance penalty as well as increased GC pressure.

To remedy the situation, I'd like to add a bunch of little-endian access methods to `ByteBuf`.

**Comment by normanmaurer** [comment]
@trustin let me do this before 4.1 :)

**Comment by ifesdjeen** [comment]
Hi, is anyone working on that one? I could pitch in, if there was no recent progress on it.

**Comment by normanmaurer** [comment]
@ifesdjeen that would be awesome! I planed to do this but I'm super busy atm :(  So the plan was to actually add a new variant of each "affected" method (so a new method for LE and a new for Be) to ByteBuf so a user can do LE and BE without call `order(...)`. Makes sense ? Another possibility is to just add a new overload like:

```java
ByteBuf.setInt(int, ByteOrder)
```
This would at least make the abstract class "less width".

WDYT ?

**Comment by ifesdjeen** [comment]
@normanmaurer I've started a #4477 PR to keep track of the discussion about the API. Just let me know if you're fine with the suggested. If yes - I'm just going to finish the rest shortly :)

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4477
