### ISSUE TITLE
Provide a generic connection pool

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#3218]
Almost all clients need a connection pool at some point as the overhead of connection establishment and  tcp slow-start is just to expensive.

We should provide a flexible / generic connection pool that users can use and adjust for their needs.

**Comment by m3alibusra** [comment]
@normanmaurer I am using AHC in my project. I had this short chat with @slandelle about a month ago.
We are looking for having somthing like setting up connections even before sending requests.
So our service sends http requests to some other systems. I want to make sure that when my service comes up it sets up connections to other services and only then start taking traffic hence avoiding initial bad performance for our clients. 

"Fixed size pool vs. lazy creating connections" looks interesting. So does fixed pool size here means that we will have some fixed number of connections always there, with or without requests or is it just max pool size?

Other thing do we have some approximate time for this (we want it soonish). We can also help you in some way if you think it can make things faster?

**Comment by normanmaurer** [comment]
Now in 4.0, 4.1 and master :)
