### ISSUE TITLE
Odd error from SCTP example

### ISSUE THREAD

**Issue by timboudreau** [netty/netty#3228]
Run SctpEchoServer in netty/examples.  Then run SctpEchoClient.  Kill SctpEchoClient.  The following is logged.  JDK issue, I guess?  Happens on 1.7 and 1.8.

```
java.lang.InternalError: should not reach here
	at sun.nio.ch.sctp.SctpChannelImpl.receive0(Native Method)
	at sun.nio.ch.sctp.SctpChannelImpl.receiveIntoNativeBuffer(SctpChannelImpl.java:859)
	at sun.nio.ch.sctp.SctpChannelImpl.receive(SctpChannelImpl.java:835)
	at sun.nio.ch.sctp.SctpChannelImpl.receive(SctpChannelImpl.java:778)
	at sun.nio.ch.sctp.SctpChannelImpl.receive(SctpChannelImpl.java:740)
	at io.netty.channel.sctp.nio.NioSctpChannel.doReadMessages(NioSctpChannel.java:273)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:69)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514)
```

**Comment by trustin** [comment]
Seems like they introduced this bug while trying to fix other one: https://bugs.openjdk.java.net/browse/JDK-8067846

We could implement a simple workaround that checks if the raised exception is `InternalError` and its message is exactly `should not reach here` to produce an artificial `SctpSendFailed` notification. However, as @timboudreau said, it could lead to an undefined behavior we are unaware of.

@timboudreau Are you interested in implementing this workaround and playing with it, so we can decide if it's worthwhile to keep the workaround?

**Comment by trustin** [comment]
My quick analysis of `jdk/src/solaris/native/sun/nio/ch/SctpChannelImpl.c` - it doesn't look harmful to implement the workaround.

**Comment by trustin** [comment]
However, `SctpSendFailed` requires the information we have no access to - association ID and stream number. :-/

**Comment by trustin** [comment]
I could wrap `InternalError` with less critical `ChannelException` so that it does not look that bad, but does it ever help us in any way?

**Comment by timboudreau** [comment]
ChannelException is at least less terrifying, for someone using Netty - it
definitely made me question whether SCTP in Java was mature enough for real
use.  Not sure what else we can do - it's a consequence of the connection
being broken by the other end of the wire.

On Sat, Jan 10, 2015 at 9:03 PM, Trustin Lee <notifications@github.com>
wrote:

> I could wrap InternalError with less critical ChannelException so that it
> does not look that bad, but does it ever help us in any way?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/netty/netty/issues/3228#issuecomment-69480488>.
>



-- 
http://timboudreau.com

**Comment by normanmaurer** [comment]
Let us close this as the original issue was fixed in openjdk,
