### ISSUE TITLE
Add support to ByteBuf to interface with position independent FileChannel calls

### ISSUE THREAD

**Issue by gbehrmann** [netty/netty#3229]
## Motivation

ByteBuf currently supports methods for reading from ScatteringByteChannel and writing to GatheringByteChannel. Reading and writing will happen at the current channel position and are thus not safe to use from multiple threads. 

FileChannel exposes read and write methods with absolute positioning: FileChannel#read(ByteBuffer, long) and FileChannel#write(ByteBuffer, long). These don't alter the position of the channel and can safely be called from multiple threads concurrently.

Currently, to use these position independent calls one has to access the ByteBuf internal nio buffer, modifying writer index to get access to the right portion of the buffer. In particular for read, this results in somewhat awkward code:

    ByteBuf chunk = alloc.ioBuffer(length);
    chunk.writerIndex(length);
    ByteBuffer buffer = chunk.nioBuffer();
    while (length > 0) {
        /* use position independent thread safe call */
        int bytes = channel.read(buffer, position);
        if (bytes < 0) {
            break;
        }
        position += bytes;
        length -= bytes;
    }
    chunk.writerIndex(chunk.writerIndex() - length);

## Requested change

Add setBytes/getBytes/readBytes/writeBytes methods for FileChannel calling through to the position independent methods.

**Comment by normanmaurer** [comment]
@gbehrmann are you still interested in providing a PR ?

**Comment by gbehrmann** [comment]
@normanmaurer, yes I am - just happen to be very busy lately (LHC startup for run two means everybody around here is trying to get all systems back into production mode).

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4842

**Comment by gbehrmann** [comment]
Thanks a lot, @windie! I have been perpetually pushing this ahead of me without finding time to do this.
