### ISSUE TITLE
@Deprecated *Codec

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#3248]
I think we could mark all *Codec classes as `@deprecated` and remove them in netty 5 as you can do the same by just write a decoder and encoder and combine them via CombinedChannelDuplexHandler.

This will remove a few classes and so simplify the class-hierarchy and also remove the need for maintain them.

@trustin wdyt ?

**Comment by trustin** [comment]
OK, except for `HttpClient/ServerCodec`.

**Comment by normanmaurer** [comment]
@trustin yep... I'm only talking about the "base classes".

**Comment by normanmaurer** [comment]
At the end we did not do this... so let me close it
