### ISSUE TITLE
SslHandler GCM cipher JVM workaround

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3256]
https://github.com/netty/netty/commit/108dc23cab13eea074397f0ade80859da4744323 introduced some code to workaround a suspected JVM bug when using GCM type ciphers.  I am wondering if this is still necessary or if we should file a bug upstream to OpenJDK (or which ever JDK was in use).

**Comment by Scottmitch** [comment]
@trustin +1. I can also reproduce the crash with the SocketSslEchoTest test when a direct buffer is being used (even on 1.8.0_20).  I'll start filing a bug report with Oracle.  Lets leave this issue open, and the work-around in until we verify with upstream JDK that is in fact an upstream issue and a fix is identified.

**Comment by normanmaurer** [comment]
@Scottmitch thanks man! Please also add the link to the issue here for easier reference

**Comment by Scottmitch** [comment]
Oracle bug report filed with `Review ID: JI-9018014`.  I have not yet attempted to get a minimal set of code (without netty framework) which reproduces the issue because we have a reliable reproducer with SocketSslEchoTest.  If I get more cycles, and if the upstream JDK folks need more support I will re-visit.  I will post updates from oracle when they are discovered in this issue.

**Comment by Scottmitch** [comment]
@normanmaurer - Will do.  Oracle's process includes a pre-screening of "reports" (identified by the Review ID) which then will be assigned another ID if they decide to turn it into a bug report.  I'll post the new ID (with a link) when it is assigned.

**Comment by Scottmitch** [comment]
I was not clear in my previous response but I also can reliably reproduce with Oracle JDK 1.8.0u25 (this is the version the bug report was filed against). Just giving some additional perspective that it is not specific to Oracle JDK.  Still waiting for a response from Oracle (no support contract and so I just filed a general report).

**Comment by WhiteTrashLord** [comment]
JDK 7 is also affected?

**Comment by normanmaurer** [comment]
Nope GCM is only supported with java 8+

**Comment by trustin** [comment]
It's up now: https://bugs.openjdk.java.net/browse/JDK-8068574
Thanks, @Scottmitch :-)

**Comment by Scottmitch** [comment]
@trustin @normanmaurer - I can't remember my login credentials to the open JDK site (or if I even have one).  It looks like a few engineers are having trouble building netty, but I can't reach out to them to help.  Would you mind posting a link to this issue in the openjdk bug?

**Comment by trustin** [comment]
@Scottmitch Do you know where I can sign up for an account? I'm not sure I have an account, but I don't seem to get any password reset messages.

**Comment by Scottmitch** [comment]
@trustin - Yah I'm in the same boat...

@netty/contributors - Anyone have a openjdk account which they can login with?  I'm going to reach out to discuss@openjdk.java.net in the mean time to see if we can get someone's attention.

**Comment by trustin** [comment]
@Scottmitch Yeah, I guess that's the way to go.

**Comment by Scottmitch** [comment]
I didn't hear anything back from the first email...sending another email.

**Comment by johnou** [comment]
@Scottmitch you could try reaching out to Nils directly? nils.eliasson@oracle.com

**Comment by Scottmitch** [comment]
@johnou - Thanks for brining my attention back to this. I generated an email directly to Nils.

**Comment by johnou** [comment]
@Scottmitch if you don't hear back from Nils you could also try Rory at rory.odonnell[at]oracle.com (he is active).

**Comment by Scottmitch** [comment]
@johnou - Thanks, I emailed Rory as well.

**Comment by normanmaurer** [comment]
Fixed https://github.com/netty/netty/pull/4875
