### ISSUE TITLE
HTTP/2 codec backport to 4.1?

### ISSUE THREAD

**Issue by NiteshKant** [netty/netty#3259]
### Netty version

4.1

### Context

HTTP/2 codec has been worked on in the latest version (5.x). As I understand 5.x version isn't in a stable state for release or release candidate soon.
At netflix we intend to aggressively start using http/2 for our IPC stack. I would like to stay on 4.x release and have HTTP/2 codec in 4.x.

### Proposal

I can work on backporting HTTP/2 codec to 4.1 and also commit to keeping it in sync with changes happening in 5.x branch.
Is this something that is acceptable to folks here?

**Comment by NiteshKant** [comment]
@Scottmitch @normanmaurer I have done a preliminary backport of http/2 from master to 4.1 and the code is available in my fork [here](https://github.com/NiteshKant/netty/tree/4.1)

I have a few questions:

- I have copy-pasted the code(from [this commit hash](https://github.com/netty/netty/commit/14039623137f2bfdaec9a7228e72fe94c663ded5)) from master on to 4.1 & I intend to cherry-pick any changes done to http/2 from now on. Obviously this means there isn't any history copied. Is this the best way of approaching the backport? If not, I am happy to follow any alt. way you guys suggest.
- I have not implemented any public API changes done as part of the changes in master. These changes are:
  - [`Headers.forEachEntry(EntryVisitor<T> visitor)`](https://github.com/netty/netty/blob/master/codec/src/main/java/io/netty/handler/codec/Headers.java#L1103) used in a couple of places in http/2 code.
  - [`FullHttpRequest.copy(ByteBuf newContent)`](https://github.com/netty/netty/blob/master/codec-http/src/main/java/io/netty/handler/codec/http/FullHttpRequest.java#L25) used in `InboundHttp2ToHttpAdapter` [here](https://github.com/NiteshKant/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/InboundHttp2ToHttpAdapter.java#L56)

Apart from the above, the examples of http/2 are running fine and tests are passing (but for [one test](https://github.com/NiteshKant/netty/blob/4.1/codec-http2/src/test/java/io/netty/handler/codec/http2/InboundHttp2ToHttpAdapterTest.java#L591) which I am looking at)

Let me know your thoughts on the above questions and how to proceed with this backport.

**Comment by Scottmitch** [comment]
Before I address specific questions let me say this sounds great!  Sound like you are close to being able to submit a PR for the backport?

> Obviously this means there isn't any history copied.

I don't think this is a problem.  My expectation is the backport will be 1 PR (squashed will be 1 commit).

> Headers.forEachEntry(EntryVisitor<T> visitor) used in a couple of places in http/2 code.

I think this method should already be available in the 4.1 branch [here](https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/Headers.java#L1103).  Am I missing something?

> FullHttpRequest.copy(ByteBuf newContent) used in InboundHttp2ToHttpAdapter here

I'm not sure I understand the comment above the line that you link, but backporting this API addition and related implementation is the correct thing to do.

> Apart from the above, the examples of http/2 are running fine and tests are passing (but for one test which I am looking at)

It would not be surprising if the test was a bit flaky.  If you continue to have problems or questions feel free to ask.

**Comment by NiteshKant** [comment]
> Sound like you are close to being able to submit a PR for the backport?

Yep, after addressing the open questions, I will be submitting a PR. May be in a couple of days.

>  My expectation is the backport will be 1 PR (squashed will be 1 commit).

Yes it will be a single commit PR.

> I think this method should already be available in the 4.1 branch here. Am I missing something?

Oops, I did not refer to the correct interface. You are correct, `Headers` interface does have that method in 4.1, however, [`HttpHeaders`](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpHeaders.java) does not extend that interface. Need for that method is in the following two places:
- [`HttpUtil.toHttp2Headers()`](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/HttpUtil.java#L307)
- [`InboundHttp2ToHttpPriorityAdapter.addHttpHeadersToHttp2Headers()`](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/InboundHttp2ToHttpPriorityAdapter.java#L139)

Both the above places use `HttpHeaders` interface. I can go ahead and add an abstract method to the `HttpHeaders` abstract class but that would mean a backward incompatible change (any implementation of the class would need to implement this method)

> I'm not sure I understand the comment above the line that you link, but backporting this API addition and related implementation is the correct thing to do.

My hesitation in adding these methods to the interface/abstract class was the resulting backward incompatible change (addition of a new method) in the public API. Is that ok?

> It would not be surprising if the test was a bit flaky. If you continue to have problems or questions feel free to ask.

Thanks, will do!

**Comment by Scottmitch** [comment]
You are right to pick up on this HttpHeaders differences.  HttpHeaders as designed existing on the master branch and a conscious decision was made during review to not change the HttpHeaders class hierarchy in 4.x branches.

> My hesitation in adding these methods to the interface/abstract class was the resulting backward incompatible change (addition of a new method) in the public API. Is that ok?

The interface differences is not ideal but adding new methods may be OK.  I would recommend keeping the interface as consistent as possible across baselines where possible but we can discuss in detail when the PR is submitted.

**Comment by NiteshKant** [comment]
>  I would recommend keeping the interface as consistent as possible across baselines where possible but we can discuss in detail when the PR is submitted.

Sounds good, will do.

**Comment by NiteshKant** [comment]
PR #3339 submitted for the backport.
