### ISSUE TITLE
channelReadComplete not triggered for EpollDatagramChannel

### ISSUE THREAD

**Issue by blucas** [netty/netty#3274]
Netty Version: Master (latest snapshot)
JDK: 1.7.0u21
Platform: Linux x86_64 GNU/Linux Ubuntu 12.04

When using UDP with Epoll, the `EpollDatagramChannel` does not trigger a `channelReadComplete` call after calling `channelRead`.  It needs to call `channelReadComplete` so that a user can trigger a `ctx.flush`. Possible fix is to trigger `pipeline.fireChannelReadComplete` after [this line](https://github.com/netty/netty/blob/master/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollDatagramChannel.java#L511)

Also, comparing `EpollDatagramChannel` to `EpollSocketChannel`, if an [exception is thrown while looping](https://github.com/netty/netty/blob/master/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollSocketChannel.java#L743), the catch clause in `EpollSocketChannel` calls [handleReadException](https://github.com/netty/netty/blob/master/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollSocketChannel.java#L483) and may trigger another `channelRead`.  `EpollDatagramChannel` does not do this... should it?

**Comment by trustin** [comment]
For the record - fixed in the following commit
