### ISSUE TITLE
java.lang.NoClassDefFoundError: io.netty.channel.DefaultChannelId

### ISSUE THREAD

**Issue by liuzhiyang** [netty/netty#3292]
When I use netty in android 4.4 has error  java.lang.NoClassDefFoundError: io.netty.channel.DefaultChannelId 

How to solve？

**Comment by normanmaurer** [comment]
Closing ... if the issue still exists let me know

**Comment by jdkjvm** [comment]
The problem still exists, can anyone tell me how to solve this it? thx.
