### ISSUE TITLE
ChannelId serialization drawbacks

### ISSUE THREAD

**Issue by travishaagen** [netty/netty#3295]
Related to the use-case described in ticket #2869, I want to be able to send the `ChannelId` over the network and respond to incoming messages by looking up the original channel in a `ChannelGroup`. Right now, `DefaultChannelId` can only be encoded/decoded using Java serialization, but the underlying unique identifier is a `byte[]`, that the `ChannelId` interface does not expose.

It would be sufficient for my use-case if a `getBytes()` method were added to the `ChannelId` interface, and a method or constructor were provided to create a `DefaultChannelId` from a given `byte[]`.

`AbstractChannel` is hard coded to use `DefaultChannelId`, which seems like it may need to be reevaluated, but isn't as crucial as providing a way to avoid using Java serialization for this use case.

**Comment by travishaagen** [comment]
I've decided on a work-around for my use case. Instead of using `DefaultChannelGroup`, I'll maintain my own `ConcurrentHashMap` with `DefaultChannelId.asShortText()` as the key for a `Channel` value.

**Comment by normanmaurer** [comment]
I will close this for now as there is no plan yet to do any work there.
