### ISSUE TITLE
WebSocketServerHandshaker.handshake() should take HttpRequest, not FullHttpRequest

### ISSUE THREAD

**Issue by lukehutch** [netty/netty#3301]
I built a web socket server based on the example in the Netty codebase. However, I'm not using HttpObjectAggregator in the pipeline (I'm assembling chunks manually using a decoder). Consequently, in my messageReceived() method, the msg parameter is never of type FullHttpRequest, but only ever HttpRequest if of HTTP request type.

The second parameter of the following method should be of type HttpRequest, not FullHttpRequest, because all it ever needs are HTTP headers (and the websocket upgrade message should have an empty body anyway):

    ChannelFuture io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker.handshake(Channel channel, FullHttpRequest req)

Instead, to get a handshaker working, I have to do the following:

    DefaultFullHttpRequest fullReq =
        new DefaultFullHttpRequest(httpReq.protocolVersion(), httpReq.method(), httpReq.uri());
    fullReq.headers().add(httpReq.headers());
    handshaker.handshake(ctx.channel(), (FullHttpRequest) fullReq);

**Comment by normanmaurer** [comment]
@lukehutch the problem is that some websocket versions need to inspect the body so we need a FullHttpRequest to make it work with all versions. But I get your point and should also make it work without the HttpObjectAggregator.

Let me have a look once I have some cycles

**Comment by normanmaurer** [comment]
Was fixed.. by https://github.com/netty/netty/commit/56148832816a6f215abd553c8ef4728189571474

**Comment by lukehutch** [comment]
Thanks!
