### ISSUE TITLE
CharsetUtil.getEn/Decoder() should not change the coding error action

### ISSUE THREAD

**Issue by trustin** [netty/netty#3321]
Related: #2999

Action plan:

* Deprecate CharsetUtil.getEn/Decoder()
* Add CharsetUtil.encoder() and decoder()
  * CharsetEncoder encoder(Charset charset)
  * CharsetEncoder encoder(Charset charset, CodingErrorAction codingErrorAction)
  * CharsetEncoder encoder(Charset charset, CodingErrorAction malformedInputAction, CodingErrorAction unmappableCharacterAction)
  * .. same goes for decoder()

**Comment by windie** [comment]
This one can be closed.

**Comment by normanmaurer** [comment]
@windie thanks for pinging... :)
