### ISSUE TITLE
Update Javassist from 3.18.0-GA to 3.19.0-GA

### ISSUE THREAD

**Issue by ngocdaothanh** [netty/netty#3331]
Javassist 3.19.0-GA released:
https://github.com/jboss-javassist/javassist/releases

**Comment by normanmaurer** [comment]
@ngocdaothanh we love PR's ;)

**Comment by ngocdaothanh** [comment]
What should I do if I want to send PR for this issue first?
I have another pending PR (#3236) that will take some more time to modify (I'll try to finish it this week).
