### ISSUE TITLE
UnsupportedOperationException thrown from AbstractNioByteChannel

### ISSUE THREAD

**Issue by bwzhang2011** [netty/netty#3333]
@normanmaurer, when upgrade to the latest netty, I got some exceptions from my log as follows, please take a look at such stack trace to help me locate where the problem if you could spare your free time:

java.lang.UnsupportedOperationException: unsupported message type: DefaultFullHttpResponse (expected: ByteBuf, FileRegion)
        at io.netty.channel.nio.AbstractNioByteChannel.filterOutboundMessage(AbstractNioByteChannel.java:276)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:746)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1277)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeWriteNow(ChannelHandlerInvokerUtil.java:157)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeWrite(DefaultChannelHandlerInvoker.java:337)
        at io.netty.channel.PausableChannelEventExecutor.invokeWrite(PausableChannelEventExecutor.java:132)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:483)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:491)
        at io.netty.handler.codec.MessageAggregator.decode(MessageAggregator.java:224)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
        at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
        at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:359)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:955)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:122)
        at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
        at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280)
        at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877)
        at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706)
        at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661)
        at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126)

by the way, I did some use cases as you did in vert.x like the http responseEncoder(I don't know whether I was wrong for that):

final class ChannelHttpResponseEncoder extends HttpResponseEncoder {
	private ChannelHandlerContext context;

	@Override
	protected void encode(ChannelHandlerContext ctx, Object msg, List<Object> out) throws Exception {
		super.encode(context, msg, out);
	}

	@Override
	public void handlerAdded(ChannelHandlerContext ctx) throws Exception {
		this.context = PartialPooledByteBufAllocator.forceDirectAllocator(ctx);
		super.handlerAdded(ctx);
	}
}

what's the more, the PartialPooledByteBufAllocator is the just the allocator copied from your code in vert.x. so please give me some advice If I were wrong to do that.

**Comment by normanmaurer** [comment]
Please show me your pipeline configuration. Also from which version you upgraded?

**Comment by bwzhang2011** [comment]
@normanmaurer, thanks for view. here comes my piple line with some abstract design:

1. configuration of the pipeline in the abstract class:
@Override
	public ChannelInitializer<SocketChannel> getServerChannelInitializer(final IProtocolDescribeDefine protocolDescribeDefine) {
		return new ChannelInitializer<SocketChannel>() {

			@Override
			protected void initChannel(SocketChannel ch) throws Exception {
				ChannelPipeline pipeline = ch.pipeline();

				/**
				 * 如果需要SSL支持的话
				 */
				if (isServerSSLSupport()) {
					ChannelHandlerAdapter sslHandler = getServerSSLHandler();

					if (sslHandler != null) {
						pipeline.addLast(SSL_TAG, sslHandler);
					}
				}
				
				/**
				 * 如果需日志支持的话
				 */
				if (isServerLogEnable()) {
					pipeline.addLast(LOGGING_TAG, getServerLogHandler());
				}
				
				/**
				 * 如果需要IP控制			
				 */
				if(needIpFilter()) {
					pipeline.addLast(IPFILTER_TAG, getIpFilterHandler());
				}

				// 得到绑定的职责链
				List<Object[]> serverHandleList = getServerHandlerList(protocolDescribeDefine);

				// 为channel分配职责
				for (int i = 0, size = serverHandleList.size(); i < size; i++) {
					Object[] handleParams = serverHandleList.get(i);
					pipeline.addLast((String) handleParams[0], (ChannelHandlerAdapter) handleParams[1]);
				}
			}

		};
	}

	/**
	 * 
	 * @Title: isServerLogEnable
	 * @Description: 是否启用日志记录
	 * @param @return
	 * @return boolean
	 * @throws
	 */
	public abstract boolean isServerLogEnable();

	/**
	 * 
	 * @Title: isServerSSLSupport
	 * @Description: 是否启用SSL支持
	 * @param @return
	 * @return boolean
	 * @throws
	 */
	public abstract boolean isServerSSLSupport();

	/**
	 * 
	 * @Title: getServerSSLContext
	 * @Description: 创建有关的ssl上下文
	 * @param @return
	 * @param @throws Exception
	 * @return SSLContext
	 * @throws
	 */
	public abstract SSLContext getServerSSLContext() throws Exception;

	/**
	 * 
	 * @Title: getServerHandlerMap
	 * @Description: 获得匹配的职责链处理器集合
	 * @param @param protocolDescribeDefine
	 * @param @return
	 * @param @throws Exception
	 * @return LinkedHashMap<String,ChannelHandlerAdapter>
	 * @throws
	 */
	public abstract List<Object[]> getServerHandlerList(IProtocolDescribeDefine protocolDescribeDefine) throws Exception;

	/**
	 * 
	 * @Title: needIdleSupport
	 * @Description: 设置是否需要超时控制
	 * @param @return
	 * @return boolean
	 * @throws
	 */
	public abstract boolean needIdleSupport();
	
	/**
	 * 
	 * @Title: needIpFilter
	 * @Description: 是否需要ip过滤
	 * @param @return  
	 * @return boolean   
	 * @throws
	 */
	public abstract boolean needIpFilter();

	/**
	 * 
	 * @Title: needInsideMsgDecoder
	 * @Description: 设置是否引入内置的解码器
	 * @param @return
	 * @return boolean
	 * @throws
	 */
	public abstract boolean needInsideMsgDecoder();

	/**
	 * 
	 * @Title: needInsideMsgEncoder
	 * @Description: 设置是否引入内置的编码器
	 * @param @return
	 * @return boolean
	 * @throws
	 */
	public abstract boolean needInsideMsgEncoder();

	/**
	 * 
	 * @Title: getIdleStateHandler
	 * @Description: 子类设置stateHandler
	 * @param @return
	 * @return ChannelHandlerAdapter
	 * @throws
	 */
	public abstract ChannelHandlerAdapter getIdleStateHandler();
	
	/**
	 * 
	 * @Title: getIpFilterHandler
	 * @Description: 由子类设置ipFilterHandler
	 * @param @return  
	 * @return ChannelHandlerAdapter   
	 * @throws
	 */
	public abstract ChannelHandlerAdapter getIpFilterHandler();

	/**
	 * 
	 * @Title: getInsideMsgDecoder
	 * @Description: 缺省内置解码器
	 * @param @return
	 * @return AbstractChannelTransferMsgDecoder<T>
	 * @throws
	 */
	public abstract ChannelHandlerAdapter getInsideMsgDecoder();

	/**
	 * 
	 * @Title: getInsideMsgEncoder
	 * @Description: 缺省内置编码器
	 * @param @return
	 * @return AbstractChannelTransferMsgEncoder<I>
	 * @throws
	 */
	public abstract ChannelHandlerAdapter getInsideMsgEncoder();

2. the second abstract class extends the first one:

	@Override
	public List<Object[]> getServerHandlerList(IProtocolDescribeDefine protocolDescribeDefine) throws Exception {
		List<Object[]> protocolList = getProtocolServerHandleList(protocolDescribeDefine);

		/**
		 * 若需内置编码
		 */
		if (needInsideMsgEncoder()) {
			ChannelHandlerAdapter insideMsgEncoder = getInsideMsgEncoder();

			if (insideMsgEncoder != null) {
				protocolList.add(new Object[] { CHENCODER_TAG, insideMsgEncoder });
			}
		}
		

		/**
		 * 如果需要idle控制
		 */
		if (needIdleSupport()) {
			protocolList.add(new Object[] { TIMEOUT_TAG, getIdleStateHandler() });
		}

		/**
		 * 业务处理
		 */
		protocolList.add(new Object[] { HANDLER_TAG, getProtocolChannelTransferMsgHandler() });

		return protocolList;
	}

	/**
	 * 设置readle和writeIdle
	 */
	@Override
	public ChannelHandlerAdapter getIdleStateHandler() {
		return new IdleStateHandler(this.serverConfigBean.getReadIdleTime(), this.serverConfigBean.getWriteIdleTime(), 0);
	}

	/**
	 * 创建ruleBaseId的filter
	 */
	@Override
	public ChannelHandlerAdapter getIpFilterHandler() {
		return new ChannelBasedIpDefaultFilter(this.ipFilterRuleCreator.createIpFilterRules());
	}

3. the third one extends the second one for http use cases:
@Override
	public List<Object[]> getProtocolServerHandleList(IProtocolDescribeDefine protocolDescribeDefine) throws Exception {
		List<Object[]> serverHandlerList = FastList.newList();

		// http解码支持
		serverHandlerList.add(new Object[] { DECODER_TAG, new HttpRequestDecoder() });

		// aggregate支持
		serverHandlerList.add(new Object[] { AGGREGATE_TAG, new HttpObjectAggregator(DEFAULT_AGGRSIZE) });

		// 增加内置解码
		if (needInsideMsgDecoder()) {
			ChannelHandlerAdapter insideMsgDecoder = getInsideMsgDecoder();

			if (insideMsgDecoder != null) {
				serverHandlerList.add(new Object[] { CHDECODER_TAG, insideMsgDecoder });
			}
		}

		// 压缩与否自动支持
		serverHandlerList.add(new Object[] { DEFLATOR_TAG, new HttpContentCompressor() });

		// http编码支持
		serverHandlerList.add(new Object[] { ENCODER_TAG, new ChannelHttpResponseEncoder() });

		return serverHandlerList;
	}

@normanmaurer , by the way:
1.  I set TCP inline params of SO_LINGER to be some small value like 15s  whether I don't know whether it could be matched with the NIO way.

2.  the version is netty5 snapshot of the master branch.

**Comment by bwzhang2011** [comment]
netty-handler.version=5.0.0.Alpha2-SNAPSHOT
netty-handler.buildDate=2015-01-14 19\:32\:43 +0000
netty-handler.commitDate=2015-01-13 18\:09\:56 +0900
netty-handler.shortCommitHash=d784281
netty-handler.longCommitHash=d78428139b84d7efd0c59c72a969c938690695cb
netty-handler.repoStatus=clean

from the netty build jar(just download such from the CI Server)

**Comment by bwzhang2011** [comment]
@normanmaurer, sorry for the code let you guess the pipeline configuration I just simplify the procedure as follows, please take a look at such:

ChannelPipeline pipeline = ch.pipeline();

//sslHandler extends SslHandler
ChannelHandlerAdapter sslHandler = getServerSSLHandler();
pipeline.addLast(SSL_TAG, sslHandler);

//logHandler extends LogHandler
ChannelHandlerAdapter logHandler = getServerLogHandler();
pipeline.addLast(LOGGING_TAG, getServerLogHandler());

//ipFilterHandler extends AbstractRemoteAddressFilter
ChannelHandlerAdapter ipFilterHandler = getServerIpFilterHandler();
pipeline.addLast(IPFILTER_TAG, getServerLogHandler());

//HttpRequest Decoder 
pipeline.addLast(DECODER_TAG, new HttpRequestDecoder());

//aggregate support
pipeline.addLast(AGGREGATE_TAG, new HttpObjectAggregator(DEFAULT_AGGRSIZE));

//deflator support
pipeline.addLast(DEFLATOR_TAG, new HttpContentCompressor());

//httpResponse encoder
pipeline.addLast(ENCODER_TAG, new HttpResponseEncoder());

//idle handler with IdleStateHandler  
pipeline.addLast(TIMEOUT_TAG,  new IdleStateHandler(30,60, 0));

// business handler extends SimpleChannelInboundHandler
ChannelHandlerAdapter businessHandler = getServerMsgHandler();
pipeline.addLast(HANDLER_TAG, new businessHandler());

**Comment by bwzhang2011** [comment]
@normanmaurer, how does this going on ? as your suggestion, I simplified the configuration. by the way, such exception thrown occasionally ? I don't know whether it would be some collision when idlestateHandler brought in.

**Comment by normanmaurer** [comment]
@bwzhang2011 you need to put the HttpResponseEncoder in from of the HttpObjectAggregator in the ChannelPipeline, as the HttpObjectAggregator may produce a HttpResponse to handle 100 continue.  This is also stated in the HttpObjectAggregator javadocs.

**Comment by bwzhang2011** [comment]
Thanks and I will move such in front and as your suggestion and it's very strange that it also work and I will prevent it from the 100 continue of the httpresponse produced.
