### ISSUE TITLE
OTR support 

### ISSUE THREAD

**Issue by gitdaemon** [netty/netty#3334]
It would be nice if Netty support OTR (Off-the Record Messaging). Currently the secured chat done through SSL, OTR support helps end to end encryption. End to end encryption is becoming popular in many messaging applications.

**Comment by Scottmitch** [comment]
@gitdaemon sounds interesting.  We love contributions :)

**Comment by trustin** [comment]
Yeah, sounds like a good addition to Netty.

**Comment by normanmaurer** [comment]
With the up coming netty 5 we decided to only support "core protocols" by ourself. This kind of stuff could be added to the netty-contribs repo tho
