### ISSUE TITLE
Make ChannelMetadata more useful

### ISSUE THREAD

**Issue by trustin** [netty/netty#3335]
Inspired by #3026 

Why don't we add the following properties to `ChannelMetadata`:

* `Set<Class<?>> inboundMessageTypes()`
* `Set<Class<?>> outboundMessageTypes()`

Also, we could add more properties to `ChannelMetadata` to remove the ugly `instanceof` in `DefaultChannelConfig`, such as:

* `defaultMaxMessagesPerRead`
* `defaultWriteSpinCount`
* `defaultBufferHighWaterMark`
* ...

**Comment by normanmaurer** [comment]
@trustin I think we can close this as won't fix ?

**Comment by normanmaurer** [comment]
Let us close this as won`t fix.
