### ISSUE TITLE
java.lang.NoClassDefFoundError: io/netty/channel/DefaultChannelId

### ISSUE THREAD

**Issue by steven-gao** [netty/netty#3338]
i write a netty demo,then run on my android phone,but it throws an exception,the error trace such as:
01-21 14:06:39.028: E/AndroidRuntime(25455): FATAL EXCEPTION: main
01-21 14:06:39.028: E/AndroidRuntime(25455): java.lang.NoClassDefFoundError: io/netty/channel/DefaultChannelId
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:51)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at io.netty.channel.VoidChannel.<init>(VoidChannel.java:34)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at io.netty.channel.VoidChannel.<clinit>(VoidChannel.java:31)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:265)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:181)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:137)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at com.example.netty.nettycore.NettyClient.start(NettyClient.java:47)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at com.example.netty.MainActivity.onCreate(MainActivity.java:16)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at android.app.Activity.performCreate(Activity.java)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at android.app.ActivityThread.access$700(ActivityThread.java)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at android.os.Handler.dispatchMessage(Handler.java)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at android.os.Looper.loop(Looper.java)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at android.app.ActivityThread.main(ActivityThread.java)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at java.lang.reflect.Method.invoke(Method.java)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
01-21 14:06:39.028: E/AndroidRuntime(25455): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

who can tell me how to resolve this problem?
thanks !

**Comment by Scottmitch** [comment]
What version of netty and android are you using?

**Comment by steven-gao** [comment]
thank you to scottmitch,the problem is solved,the reason is that client version not correct!

**Comment by oikomi** [comment]
hi @steven-gao   can you expain more more details?  thanks

**Comment by baiwfg2** [comment]
hi @steven-gao can you expain more more details? thanks

**Comment by juanmao123** [comment]
hi @steven-gao can you expain more more details? thanks

**Comment by normanmaurer** [comment]
I think there is most likely netty 4.0 and 4.1 on the class path. Only one of these can exists
