### ISSUE TITLE
resolver-dns: query cache appears to be unbounded

### ISSUE THREAD

**Issue by megahall** [netty/netty#3349]
The Netty `resolver-dns` has a `queryCache` variable which appears to be totally unbounded, thus resulting in memory leaks / loss / DoS attack vector. It can also cause stale DNS entries being sent back to clients:

```
final ConcurrentMap<DnsQuestion, DnsCacheEntry> queryCache = PlatformDependent.newConcurrentHashMap();
```

This calls the constructor: http://gee.cs.oswego.edu/dl/jsr166/dist/jsr166edocs/jsr166e/ConcurrentHashMapV8.html#ConcurrentHashMapV8() , which has no limitation on the maximum map size.

This is not really RFC-compliant since it doesn't seem to respect the idea of a small negative answer TTL or whatever positive TTL is specified in the DNS RRs / RRSets. It seems like a Concurrent LRU map with a hybrid eviction strategy based on the RR / RRSet being past its expected TTL, or past a user-defined max element count, is needed.

The problem was identified in a big production deployment of a geolocation and DNS resolution web service based on the DNS resolver, left running continuously for many weeks.

@trustin @heinousjay Can you have a look at this?

**Comment by normanmaurer** [comment]
@megahall this is not the case anymore as we support handling TTL now. Closing it
