### ISSUE TITLE
How to use AttributeKey in netty-5.0.0.Alpha1?

### ISSUE THREAD

**Issue by jsbd** [netty/netty#3351]
How to use AttributeKey in netty-5.0.0.Alpha1?

public static final AttributeKey<String>  key = new AttributeKey<String>("TEST");

this code works well in netty4.0.25.final, but not works in netty-5.0.0.Alpha1,how to assign some attachment to a Channel in netty-5.0.0.Alpha1.

**Comment by normanmaurer** [comment]
@jsbd use AttributeKey.valueOf(...).
See https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/AttributeKey.java#L38

**Comment by jsbd** [comment]
Thank you very much! I found it.@normanmaurer
