### ISSUE TITLE
Extension to ByteBuf interface for composite buffers

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3358]
A relatively common pattern within Netty is to conditionally operate on `ByteBuf` objects depending on how many internal buffers are maintained.  For example is there is just 1 internal buffer then some code is called, and if there is > 1 internal buffer those buffers are typically combined into 1 buffer.  This creates multiple code paths and potentially unnecessary buffer copy operations.  It would be nice if the `ByteBuf` interface could be expanded to facilitate this use case.

**Comment by Scottmitch** [comment]
For example adding a method such as `forEachComponent` which would provide an interface to iterate over internal buffers.  This may mitigate the need to count the number of buffers, move/copy buffers, and have fragmented code paths in these situations.

**Comment by Scottmitch** [comment]
This may make https://github.com/netty/netty/issues/3306 less important or even unnecessary.

@trustin @normanmaurer WDTY?

**Comment by Scottmitch** [comment]
Carried over from @trustin at https://github.com/netty/netty/pull/3344#discussion_r23517027:

> Currently, the only ByteBuf implementation that can have more than one ByteBuffer is CompositeByteBuf, so I think it's probably better adding a method like forEachComponent() to CompositeByteBuf only.

Wouldn't this require that all call sites still have conditional code based upon the class hierarchy of `ByteBuf` (i.e. `instance of CompositeByteBuf`)?  Do you think it would be too much overhead, or bad design to support this at the `ByteBuf` interface level?

**Comment by trustin** [comment]
This issue actually makes me think if it's really a good idea to have a composite buffer implementation at all. Would the composite buffer still be useful once we introduce stream (#859)?

Currently, composite buffer is being used in our code to cumulate multiple buffers without copying, and I think this is probably where stream can do a better job.

**Comment by Scottmitch** [comment]
I am all for getting rid of the special code paths in Netty code.  If streams can provide this then +1.  Is the expectation that once the stream interface is developed that a good portion of netty code will be modified to take advantage of this?  What is your expectation for time frame and version these changes would target?

**Comment by nmittler** [comment]
@trustin @Scottmitch will `Stream` be able to support use cases such as `SslHandler` that require NIO `ByteBuffer`?

**Comment by nmittler** [comment]
I think @Scottmitch's idea of a `forEachComponent` (or maybe `forEachNioBuffer`) method seems like a reasonable approach in that it would support nested `CompositeByteBuf`s reasonablly well. We'd have to take a closer look at each usage of NIO buffers in Netty to see if this API would be sufficient in all cases.

Also, it's not clear how the `Stream` abstraction simplifies access to the underlying NIO buffers.
