### ISSUE TITLE
Netty Guides

### ISSUE THREAD

**Issue by ifesdjeen** [netty/netty#3360]
Hi @normanmaurer 

I thought that it'd probably be a bit easier if I just open up an issue and we could start an open discussion and get more people involved into writing Netty Guides.

Netty is an awesome project, and once you know and get the basics, it's amazingly easy and simple to create very performant TCP, HTTP, SPDY and whatsoever services, to work with ByteBuffers, to create off-heap data structures and so on.

Although for me (personally) it was a bit hard to get up to speed (although it was quite some time ago). I've checked existing online resources, and there are quite a few nice blog posts on Netty, and an awesome upcoming (although already partially available) book. But I thought that some Guides could be also helpful. 

I thought that the following subjects could be useful (also, talked to several colleagues of mine who'd like to participate, I'll point them to the same issue): 

Writing TCP server and client with Netty (based on Cassandra experience and practices).

  * Tracking connections on the server side to push server-initiated messages
  * Implementing client-side reconnects 
  * Binary Protocol tips (based on ByteBuf)
  * Implementing Futures for waiting for responses 
  * Executors
  * Pipelining 
  * Heartbeats
  * Host Is Down notification
  * Retry policies 

Writing SPDY client and server

  * ALPN / NPN protocol negotiations
  * OpenSSL / JDK SSL
  * Server-Side pushes
  * Pipelining 
  * Implementing Futures for responses
  * Server-side connection tracking
  * Working with Headers 

I'll try working through some simpler scenarios, too (such as echo server, that is already partially covered in an existing guide).

Some of these things are already represented in Guides.

What do you think? Do you have anything in mind what should be covered first / next? How should we organize work? Are there any more volounteers for the good cause? Does it all make any sense at all? 

Thank you!

**Comment by Scottmitch** [comment]
@ifesdjeen improving code accessibility and docs sounds like a good idea. Did you have a format/approach in mind (were you thinking of referencing example code with additional explanations)? it would be important to keep the detail at the appropriate level so maintenance is not too high (and also have a plan for what maintenance would look like).

I'm not sure if the SPDY server/client is its own section but if so there should be some overlap in high level functionality with HTTP/2.

**Comment by jsbd** [comment]
Good idea! @ifesdjeen

**Comment by ifesdjeen** [comment]
@Scottmitch 

> were you thinking of referencing example code with additional explanations

I was basically thinking something along these lines (also authored by our team). Guide "outlike" would looks something like a list of high-level subjects with TOC, book-like:
http://clojurecassandra.info/articles/guides.html

And a guide itself would consist of a code snippets, explaining top-bottom approach. Referencing and explaining concepts in an order that would be usually used by someone who already knows how to develop same thing. 
http://clojurecassandra.info/articles/cql.html

But yes, I think in case of Netty it'd be also good to point people to a complete example, too. Which would serve as a more generic entrypoint. 

Probably HTTP2 would be a good idea, agree. I just only used SPDY, and never HTTP2, but I if you say they're similar, I could just try http2 out...

**Comment by Scottmitch** [comment]
> Ah, also, I was wondering if it'd be possible to host it on netty.io website itself, or shall we set up our own "playground"?..

I'm guessing you will have more control if you set up your own playground, but if possible use Netty styles/layout.  You may want to get feedback from @trustin and/or @normanmaurer before putting in too much effort.

**Comment by ifesdjeen** [comment]
@Scottmitch Sure, this was the reason why this issue was filed :)

I certainly don't mind more control, although I see almost no sense in creating "independent" doc guides, to be honest. In the end, it won't be read/trusted by the community "by default", and will eventually die out, or will take too much effort to promote and convince people that it's actually good quality (given it is good quality, of course).

I mostly wanted to know whether there's a general need for that, and if it'd make sense to invest energy in something like that. If yes - I could volunteer.

**Comment by Scottmitch** [comment]
> although I see almost no sense in creating "independent" doc guides, to be honest

Agreed. The suggestion was for while the docs were in development and not ready for prime time.

**Comment by ifesdjeen** [comment]
> Agreed. The suggestion was for while the docs were in development and not ready for prime time.
@Scottmitch good idea. Yeah, I think we'll just start with some markdown docs, and see where it all goes. Thank you for the feedback!

**Comment by junjiemars** [comment]
The good guide is better than nothing, but why we trying to use netty?:
more faster code, more cleaner API, more understandable/maintainable code, not just the better guides. 
We need more practical oriented example code not just toy code for fine. Under the netty/example directory I can't   find the practical oriented code, so I can't diff
```sync or. syncUninterruptibly, PooledByteBufAllocator or Unpooled```, etc., and I must dig into it to find why.

So, I think the most important thing is to rewrite 'netty/example' code for more practical oriented style, 
then the next move is better guides.

**Comment by Scottmitch** [comment]
@junjiemars - If you feel you have some good examples to contribute please feel free to open a PR.  Things can always be approved and we appreciate all the help we can get :)

**Comment by normanmaurer** [comment]
+1
