### ISSUE TITLE
EventLoop blocked during delegated task execution in SslHandler

### ISSUE THREAD

**Issue by systemtrap** [netty/netty#3361]
If a delegated task executor is used in SslHandler `SslHandler#runDelegatedTasks` pushes the delegated tasks to the delegated task executor and returns immediately. Callers like `SslHandler#unwrap`
are now caught in a loop `for (;;)` [[SslHandler#unwrap +933](https://github.com/netty/netty/blob/master/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L933)] busy waiting for a non-NEED_TASK handshake status to continue.

So the event loop is needlessly burning CPU clyces. Propably the delegated task runnable should be wrapped and enqueue an event on completion.

**Comment by trustin** [comment]
Yes, it is a known issue, and that's why the `delegatedTaskExecutor` is an `ImmediateExecutor` by default in 4.0 and we removed that parameter in 5 (and will in 4.1.)

Could you let us know why you specified an alternative `delegatedTaskExecutor`?

**Comment by systemtrap** [comment]
I'm sorry for creating this entry. I wasn't able to find a reference to this issue.

I tried to use an alternative executor because it is possible and being aware that executing the delegated tasks on the IO thread is not the smartest idea.

**Comment by trustin** [comment]
I see. We deprecated the `SslHandler` constructor that accepts a `delegatedTaskExecutor`, so we thought the message was clear, but yeah, it isn't always the case.
