### ISSUE TITLE
SPDY sonarqube syncronization error reports

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3363]
[SonarQube](http://clinker.netty.io/sonar/drilldown/issues/3670?rids%5B%5D=3676) reports a few synchronization issues related to SPDY code.  We should investigate these issues and either mark them as false positives or address the issues.

Example:
![image](https://cloud.githubusercontent.com/assets/7562868/5921205/51497c4c-a610-11e4-9f42-38d4543350a4.png)

**Comment by Scottmitch** [comment]
@jpinner - FYI.

**Comment by jpinner** [comment]
@Scottmitch I think these are bogus given the new threading model in 4.x

**Comment by Scottmitch** [comment]
@normanmaurer @trustin - Is there a way to mark false positives in our SonarQube?  If so who has access to this sort of thing?

**Comment by Scottmitch** [comment]
@trustin - Marked these as false positives.  Closing.
