### ISSUE TITLE
SSLHandler and... recycled already

### ISSUE THREAD

**Issue by andreipet** [netty/netty#3367]
Hello.

I'm using nightly builds of 5.0.0.Alpha2.
Using SSLHandler and JMeter stop button I receive:
java.lang.IllegalStateException: recycled already

The pattern to reproduce is:

ctx.write1(..., promise1);
ctx.write2(...);
...
ctx.flush();

in promise1 I do a ctx.close() for write IOExceptions.

Resumed, this happens:

1. flush()
2. SSLHandler pendingUnencryptedWrites.removeAndFailAll(SSLENGINE_CLOSED);
3. for all pending writes: recycle and their promise become failures.
4. somewhere in the loop in point 3. promise1 fails
5. as stated I do ctx.close() for promise1 fail.
6. -> flush() again
7. -> SSLHandler pendingUnencryptedWrites.removeAndFailAll(SSLENGINE_CLOSED); again
8. -> all pending (remaining) writes are recycled and their promise are failures.
9. return to point 3 after promise1 handled and the remaining pending writes are all recycled by handling promise1 fail. 
10 -> java.lang.IllegalStateException: recycled already 
because remaining writes in queue are already processed in point 8.

My solution to this would be to improve the PendingWriteQueue.
In methods removeAndFailAll() and removeAndWriteAll() we could safely replace:
<b>write = next;</b>
with:
<b>write = head;</b>
In this way the loop can take care of recursions (while removing one queue element the queue is already emptied by handling a promise). write.next can point to a recycled element.

Thank you.

**Comment by normanmaurer** [comment]
@andreipet sounds about right... Would you like to submit a PR ?

**Comment by andreipet** [comment]
Yes I will. I wanted to see if it sounds sane :)
Ty.

**Comment by normanmaurer** [comment]
@andreipet cool... I think we just need to ensure we guard against re-entrance . Please also add a unit test for it.

**Comment by andreipet** [comment]
This sounds more complicated. How to trap the weak spot. I'm testing with 250 connections and still can catch it all the time on the right spot. Maybe you can guide me.

**Comment by andreipet** [comment]
@normanmaurer  how can we write tests that trap concurrent server/client problems....? I mean if does pass the unit test it does not mean it will pass the test forever...sometimes it will pass sometimes not. It is a hunt for server moment1 and client moment2.

**Comment by normanmaurer** [comment]
@andreipet I think it should be easy to test with PendingWriteQueue only. But if you are not sure how I can just take care of fixing. Just let me know

**Comment by andreipet** [comment]
OK. I will give it a try tomorrow.

**Comment by normanmaurer** [comment]
@andreipet awesome... let me know if you need anything

**Comment by normanmaurer** [comment]
@andreipet not need to worry about it... I think I have everything almost ready :)

**Comment by trustin** [comment]
@normanmaurer OK to close, or do you have something to do yet?

**Comment by normanmaurer** [comment]
Closed...
