### ISSUE TITLE
HTTP/2 DefaultHttp2FrameWriter copy operations

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3372]
DefaultHttp2FrameWriter is currently assembling a frame into a single buffer (via copying) and writing that buffer to the socket.  Could we avoid copying and just write each individual piece to the socket independently?

**Comment by nmittler** [comment]
@Scottmitch Good idea!  Have you captured any performance metrics?  It would be interesting to see what the improvement is here.

**Comment by Scottmitch** [comment]
@nmittler - I have not yet implemented the changes.  Just wanted to get an issue on the books so I didn't forget :).

**Comment by nmittler** [comment]
@Scottmitch sgtm :)

**Comment by louiscryan** [comment]
@normanmaurer any guidance on the relative performance characteristics of dong the following inside the event-loop thread.

write(A)
write(B)
flush()

vs

A.write(B);
write(A)
flush()

**Comment by normanmaurer** [comment]
@louiscryan not sure I understand... what is A and B here ?

**Comment by Scottmitch** [comment]
@louiscryan - I'm guessing A and B are buffers.  write(A) is writing to the socket.  A.write(B) is a copy of B into A?

**Comment by louiscryan** [comment]
Exactly, or more concretely 

https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameWriter.java#L114

**Comment by trustin** [comment]
It depends on how efficient the gather write operation of the underlying transport is. My guess is the gathering write is faster on the epoll transport. Not sure about NIO transport due to the memory footprints it generates.

**Comment by Scottmitch** [comment]
Good point @trustin. I think @louiscryan's https://github.com/netty/netty/issues/2828#issuecomment-72277270 relted to micro bench-marking http/2 is the first step toward figuring out which is better for which configurations.  If usage will vary depending on configuration then maybe it is appropriate to provide 2 implementations (since I have a good start on the the direct write PR https://github.com/netty/netty/issues/3385)?

**Comment by trustin** [comment]
How about the sensible default implementation with overridability?

**Comment by Scottmitch** [comment]
@trustin - Sounds good. The interface is already exposed so I think we are good.  I'm working on a microbenchmark to evaluate the PR.

**Comment by nmittler** [comment]
@Scottmitch @louiscryan I've just cherry-picked and closed #3385.  Should we leave this open until the benchmarking work is completed?

**Comment by Scottmitch** [comment]
Yes let's leave it open.

**Comment by Scottmitch** [comment]
Benchmarking PR https://github.com/netty/netty/pull/3392 benchmarks the changes.

**Comment by Scottmitch** [comment]
@nmittler @louiscryan - Sooo what are your thoughts?  Should we close this?  Benchmarking is done and results have been posted.  My take away is the current benchmark didn't reveal any clear gain or loses when the real transports were used. If we are aiming at an "isolated" benchmark of the DefaultHttp2FrameWriter the current benchmark gives us a "writes are just immediately release buffers, and real allocators are used" view with the `EMBEDDED*` tests (where the benefits were more clearly visible).

**Comment by nmittler** [comment]
+1 I think we can close this

**Comment by Scottmitch** [comment]
Closing.  Lets open a new issue if we want more changes :)
