### ISSUE TITLE
Unable to join to IPv4 multicast group

### ISSUE THREAD

**Issue by systemtrap** [netty/netty#3374]
`Bootstrap#bind` aquires a `DatagramChannel` via `DatagramChannel#open()`. So, on a IPv6-enabled system, a `sun.nio.ch.DatagramChannelImpl` is contructed with a `StandardProtocolFamily.INET6-family`. Trying to join an IPv4-multicast group fails because a `StandardProtocolFamily.INET6-sun.nio.ch.DatagramChannelImpl` can't join any Inet4Address.
An `StandardProtocolFamily.INET-sun.nio.ch.DatagramChannelImpl` is normally contructed via `DatagramChannel#open(ProtocolFamily)`.

ATM it is possible to create a usable DatagramChannel by providing a different `ChannelFactory` via `Bootstrap#channelFactory`. May be this could be tweaked to take `localAddress` into account by default.

**Comment by trustin** [comment]
What happens if you specify the IPv6 local address converted from IPv4 address? (a.k.a [IPv4-translated addresses](http://en.wikipedia.org/wiki/IPv6_address#Transition_from_IPv4))

If it does not fail, I think we can make our `DatagramChannel` implementations do automatic conversions.

**Comment by normanmaurer** [comment]
@systemtrap did you see @trustin 's question ?

**Comment by normanmaurer** [comment]
Let me close this for now until we get more infos.
