### ISSUE TITLE
Http2LifecycleManager.closeLocalSide is always receiving a completed ChannelFuture

### ISSUE THREAD

**Issue by louiscryan** [netty/netty#3380]
The interface can be changed to remove the Future and just execute the listening logic immediately. 

There may be similar issues with other signatures in this type.

**Comment by Scottmitch** [comment]
@louiscryan - Can you let me know if you still think this is valid?

**Comment by louiscryan** [comment]
I think it's obsolete now with all the changes in the flow controller.
