### ISSUE TITLE
Http2Stream state consolidation

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3382]
Http2Stream has a few methods which represent state.  There is the [state()](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2Stream.java#L46) method which should be checked according to the rules defined in the HTTP/2 spec.  There are also some other methods which represent state:
1. [isEndOfStreamReceived](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2Stream.java#L83)
2. [isEndOfStreamSent](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2Stream.java#L83)
3. [isResetReceived](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2Stream.java#L106)
4. [isResetSent](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2Stream.java#L117)
5. [isReset](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2Stream.java#L129)

We should investigate if these are called in the correct places, and if they are all required.  For example is `isEndOfStreamSent` necessary if we change the stream's state synchronously in the [writeData](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionEncoder.java#L147) or [writeHeaders](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionEncoder.java#L210) method?

**Comment by Scottmitch** [comment]
@nmittler - FYI.

**Comment by trustin** [comment]
Great initiative.

**Comment by nmittler** [comment]
@Scottmitch good idea!  I'll start looking at this today.

**Comment by Scottmitch** [comment]
@nmittler - Thanks for taking care of this!

**Comment by nmittler** [comment]
@Scottmitch After playing with this a bit locally, I believe we can get rid of all of these with the exception of `isResetSent`.  We need to know if we sent RST_STREAM so that we ignore (and don't fail) frames coming in on that stream.  I should have a PR ready with a first cut of the changes shortly ... stay tuned.
