### ISSUE TITLE
SPDY costs too much memory on JDK 6

### ISSUE THREAD

**Issue by xmxsuperstar** [netty/netty#3383]
In SpdyHeaderBlockEncoder:
```
        if (PlatformDependent.javaVersion() >= 7) {
            return new SpdyHeaderBlockZlibEncoder(
                    version, compressionLevel);
        } else {
            return new SpdyHeaderBlockJZlibEncoder(
                    version, compressionLevel, windowBits, memLevel);
        }
```

In SpdyHeaderBlockJZlibEncoder : 

```
 int resultCode = z.deflateInit(
                compressionLevel, windowBits, memLevel, JZlib.W_ZLIB);

```

And in `z.deflateInit`

```
new Deflate(this);
```

It means every SpdyFrameCodec contains one Deflate object, but in Deflate object, there is some very large arrays, such as head and prev

In my case, every Deflate retained 268288 bytes, and when I create 2000+ spdy connections, jvm throws OutOfMemory exception.

When I use jdk7, I can create more than 8000+ spdy connections

**Comment by normanmaurer** [comment]
You will at least need to provide some details...

**Comment by xmxsuperstar** [comment]
@normanmaurer sorry, i have added the details

**Comment by normanmaurer** [comment]
Not sure we can do much about it as this memory is used by JZlib which is needed for java6

**Comment by trustin** [comment]
@xmxsuperstar - perhaps you could talk to the jcraft folks, or try to hack JZlib by yourself. I would also recommend upgrading to Java 8, because 6 and 7 are pretty much dead at this point.
