### ISSUE TITLE
ThreadPerChannelEventLoopGroupTest sometimes make the build stuck

### ISSUE THREAD

**Issue by trustin** [netty/netty#3391]
Build [#94](http://clinker.netty.io/jenkins/job/netty-sonar/branch/master/94) was stuck for several hours at `ThreadPerChannelEventLoopGroupTest`.

**Comment by normanmaurer** [comment]
Did not see this for a long time now... Let me close it

**Comment by Scottmitch** [comment]
@normanmaurer - should we add a timeout on this test? I saw some snags when I was reworking the DefaultPromise implementation (https://github.com/netty/netty/pull/5221) ... but I expected some snags while in development and knew where to look.
