### ISSUE TITLE
Reorder isRoot Check

### ISSUE THREAD

**Issue by md-5** [netty/netty#3405]
Minor thing, but in:
https://github.com/netty/netty/blob/e9bcc518fc6618aadf8d288968848b99da770e6a/transport/src/main/java/io/netty/channel/AbstractChannel.java#L539
and
https://github.com/netty/netty/blob/5725e804bcfbd0c76e0f11e7911a76970eb06c8c/transport/src/main/java/io/netty/channel/socket/DefaultDatagramChannelConfig.java#L161

If the isRoot check were moved to the end of the if statement, it would avoid the expensiveish processbuilder / cleanup threads etc being created if they aren't needed.
`System.getProperty("user.name")` could also be used as a short circuit, as if that value is root, there is no need to check the output of id.

**Comment by trustin** [comment]
Thanks for an idea. See 2cfebfe74cf7dfe6eb304ede01553cf9dc6523fa (master), a1efd1871bff4566e1666d4ad8c649e7451316fe (4.1), 10a5635acbb85e27d6eb8ff754fb888d699fd4f0 (4.0)

I didn't look into `System.getProperty("user.name")` though because I'm completely sure if the user name of the super user is always `root`.

**Comment by md-5** [comment]
I looked into it a bit more, and since IS_ROOT is set on clinit, I don't think this makes a difference:
https://github.com/netty/netty/blob/e9bcc518fc6618aadf8d288968848b99da770e6a/common/src/main/java/io/netty/util/internal/PlatformDependent.java#L63

Maybe a new ticket is needed to make those values lazily initialized?

**Comment by trustin** [comment]
Ah, yeah. Missed that part.

**Comment by trustin** [comment]
Actually, we have fixed that already: https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/internal/PlatformDependent.java#L120

**Comment by md-5** [comment]
Thanks!
