### ISSUE TITLE
Add useful reusable objects to InternalThreadLocalMap

### ISSUE THREAD

**Issue by trustin** [netty/netty#3411]
Just like we provided thread-local `StringBuilder` via `InternalThreadLocalMap`, we could provide the following objects for reusability:

- `byte[]`
- `ArrayList[]` - this replaces `RecyclableArrayList`

Also, make sure we make most use of these variables across our code base.  I suspect there are various places we create a new `byte[]`, `StringBuilder`, and `ArrayList` blindly.

**Comment by windie** [comment]
Add a reusable ArrayList to InternalThreadLocalMap in #4798. 

For `byte[]`, since it has a fixed length, we need a object pool for some commonly used `byte[]`. Not sure if it's worth.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4798
