### ISSUE TITLE
HTTP/2 Draft 17 and HPACK 12

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3418]
New drafts are out.  We should evaluate and make necessary updates.

https://tools.ietf.org/html/draft-ietf-httpbis-http2-17
~~https://tools.ietf.org/html/draft-ietf-httpbis-header-compression-11~~
https://tools.ietf.org/html/draft-ietf-httpbis-header-compression-12

We should coordinate with https://github.com/twitter/hpack if necessary.

**Comment by Scottmitch** [comment]
@nmittler @jpinner FYI.

**Comment by Scottmitch** [comment]
HPACK-11 didn't last very long :)  We now have draft 12.

Note that the issue description and links have been updated.

**Comment by nmittler** [comment]
@Scottmitch ha! ... thanks for keeping on top of this!

**Comment by jpinner** [comment]
Will release hpack-1.0.0 once the spec gets published as an RFC. There will likely be minor API breaking since "Header Table" has been renamed in the spec to "Dynamic Table" (i.e. maxHeaderTableSize -> maxDynamicTableSize).

**Comment by Scottmitch** [comment]
@jpinner - That shouldn't be a problem.  Thanks for the heads up.

I have seen a lot of chatter on the email thread about fixing static tables...do you think there is a draft 13 on the horizon?

**Comment by Scottmitch** [comment]
I am reviewing the draft 17 specification.  There are a few changes to the spec which appear to be made for clerical purposes but may have unintended implications.  I have opened issues on the http2-spec to get more clarity.
https://github.com/http2/http2-spec/issues/726
https://github.com/http2/http2-spec/issues/727
https://github.com/http2/http2-spec/issues/730

**Comment by nmittler** [comment]
@Scottmitch great work ... thanks for doing this!

**Comment by Scottmitch** [comment]
@nmittler - What are your thoughts on the following addition in [section 8.2](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-8.2):

> The server MUST include a value in the ":authority" header field for
   which the server is authoritative (see Section 10.1).  A client MUST
   treat a PUSH_PROMISE for which the server is not authoritative as a
   stream error (Section 5.4.2) of type PROTOCOL_ERROR.

Should we be providing an additional interface used to verify "authority" that the user must provide?  Or should we follow the approach we used with the "cacheability" which is just to add [comments](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2FrameListener.java#L160)?  Verifying authority can be relatively involved an context dependent, but we could have a simple interface which forces the issue (which we decided against doing for the "cacheability" case).

**Comment by nmittler** [comment]
+1 for a simple interface.  Something like:

```java
interface AuthorityVerifier {
    void verifyAuthority(String authority) throws Http2Exception;
}
```

And they provide a default that always allows the authority.

I suppose we could do something similar for cacheability, but let's leave it as-is for now.

WDYT?

**Comment by Scottmitch** [comment]
@nmittler - Yes I like making it explicit...comments are too easy to miss.

**Comment by Scottmitch** [comment]
Draft changes have been cherry-picked. I'm going to open a separate issue for updating HPACK.

**Comment by Scottmitch** [comment]
See https://github.com/netty/netty/issues/3535 for HPACK updates.
