### ISSUE TITLE
normal usage can yield entropy warning messages

### ISSUE THREAD

**Issue by mhgrove** [netty/netty#3419]
I originally mentioned this on [SO](http://stackoverflow.com/questions/28173570/conditions-for-lack-of-entophy-in-threadlocalrandom)

We've had users report seeing this from time to time, and we've been able to find a way to get it to occur in our test environment.

The gist of the bash script which can reliably reproduce this in our system is basically:

```
while (true) {
  client.performOperation()
}
```

**Comment by normanmaurer** [comment]
Can you tell us what performOperation does ?

**Comment by mhgrove** [comment]
the protobuf codec is used for the client/server communications.  it's just taking some user input, creating the relevant protobuf object and writing that over the channel to the server.

Here's a capture from the terminal where we're repeatedly sending a very small request to the server and we hit the issue:

```
fernando:stardog $ for i in `seq 10 50`; do echo adding nss$i; stardog namespace add --prefix nss$i --uri http://example.com/frequency/ -n test; done
adding nss10
Prefix nss10 already has this mapping.
adding nss11
Successfully added the namespace.
adding nss12
Successfully added the namespace.
adding nss13
Successfully added the namespace.
adding nss14
Successfully added the namespace.
adding nss15
Successfully added the namespace.
adding nss16
Successfully added the namespace.
adding nss17
Successfully added the namespace.
adding nss18
Successfully added the namespace.
adding nss19
Successfully added the namespace.
adding nss20
Successfully added the namespace.
adding nss21
Successfully added the namespace.
adding nss22
Successfully added the namespace.
adding nss23
Successfully added the namespace.
adding nss24
Successfully added the namespace.
adding nss25
Successfully added the namespace.
adding nss26
Successfully added the namespace.
adding nss27
Successfully added the namespace.
adding nss28
Successfully added the namespace.
adding nss29
Successfully added the namespace.
adding nss30
Successfully added the namespace.
adding nss31
Nov 17, 2014 3:50:52 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
adding nss32
Nov 17, 2014 3:50:57 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
adding nss33
Nov 17, 2014 3:51:02 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
adding nss34
Nov 17, 2014 3:51:07 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
adding nss35
Nov 17, 2014 3:51:12 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
adding nss36
Nov 17, 2014 3:51:17 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
adding nss37
Nov 17, 2014 3:51:22 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
adding nss38
Nov 17, 2014 3:51:27 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
adding nss39
Nov 17, 2014 3:51:32 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
adding nss40
Nov 17, 2014 3:51:37 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
adding nss41
Nov 17, 2014 3:51:42 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
adding nss42
Nov 17, 2014 3:51:47 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
adding nss43
Nov 17, 2014 3:51:52 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
adding nss44
Nov 17, 2014 3:51:57 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
adding nss45
Nov 17, 2014 3:52:02 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
adding nss46
Nov 17, 2014 3:52:07 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
adding nss47
Nov 17, 2014 3:52:12 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
adding nss48
Nov 17, 2014 3:52:17 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
adding nss49
Nov 17, 2014 3:52:22 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
adding nss50
Nov 17, 2014 3:52:27 PM io.netty.util.internal.logging.Slf4JLogger warn
WARNING: Failed to generate a seed from SecureRandom within 3 seconds. Not enough entrophy?
Successfully added the namespace.
```

**Comment by mhgrove** [comment]
I'm not sure if anything mentioned here (http://stackoverflow.com/questions/27173833/slow-service-response-times-java-securerandom-dev-random/27178322#27178322) would help alleviate the issue.

**Comment by normanmaurer** [comment]
@trustin could you check ?

**Comment by trustin** [comment]
My guess is that the application loads Netty multiple times with different class loaders. To work around this problem, we could store the initial seed in a System property.  @mhgrove Could you confirm?

**Comment by mhgrove** [comment]
Sort of.  What the example output from the CLI from my previous message is doing is starting java on each invocation of the loop.  So, yes, each of those different invocations of java is a new Netty client & classloader.  But there's only a single classloader in any one invocation.

Where we've commonly noticed the issue is as shown where we're trying to put together some scripts that will get the environment into a desired state, such as for testing.  Those are places were we're effectively creating, and recreating, a new java/netty/classloader on each command. 

I can try to use the system property to avoid the issue.  I took a quick glance as the SecureRandom code, is the correct property to set `io.netty.initialSeedUniquifier`?  What would be a suggested value to set it to?  `System.currentTimeMillis()`, `nanoTime()`?

**Comment by mhgrove** [comment]
We've noticed that setting the system property `-Djava.security.egd=file:/dev/./urandom` seems to resolve the issue, or at least, makes it much less likely to occur

**Comment by trustin** [comment]
I see. Netty tries to get the initial seed uniquifier from /dev/random via `SecureRandom`. We see the timeout warning because /dev/random can block for indefinite amount of time when there are not enough entrophy in the system.

Instead of using `-Djava.security.egd` option, I'd like to recommend using the `-Dio.netty.initialSeedUniquifier` option so that other parts of your code that uses `SecureRandom` remain unaffected and secure.

You can specify any 64-bit long integer as the value of the `-Dio.netty.initialSeedUniquifier` option. I would recommend setting the system property before any Netty classes are loaded in your `main(String[])` method.

**Comment by trustin** [comment]
One thing to discuss is, should we use `SecureRandom` really? Perhaps we could get the pseudo-random data from `/dev/urandom` or use `nanoTime()` if `/dev/urandom` is unavailable.

**Comment by trustin** [comment]
I'm fine with pulling the random value from `/dev/urandom` and `System.nanoTime()`. What do you think, @normanmaurer ?

**Comment by normanmaurer** [comment]
@trustin sounds good (Sorry for the late response).

**Comment by alexandrnikitin** [comment]
We've also encountered with the issue. We are using `4.0.30` version on CentOS 7.1 and 3.10.0 kernel. I don't know reasons yet.

**Comment by vikulin** [comment]
Look at https://code.google.com/p/selenium/issues/detail?id=1301 that is cause the issue

**Comment by vikulin** [comment]
Helped me:
$ sudo mv /dev/random /dev/random.real
$ sudo ln -s /dev/urandom /dev/random

**Comment by matanster** [comment]
This issue is really painful. One day you deploy with ease, the other you simply can't. 
Is there something definite that works around this? some of the shell commands above look a bit / mysterious.

**Comment by mhgrove** [comment]
@matanster we have been using the system properties, not the shell commands, and it seems to avoid the issue.

**Comment by johnou** [comment]
@vikulin would you please remove your shell commands which replaces /dev/random with /dev/urandom the two are separated for a reason (for security).

**Comment by normanmaurer** [comment]
Let me actually fix this by porting code from:
http://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/src/main/java/util/concurrent/ThreadLocalRandom.java?view=markup

**Comment by matanster** [comment]
@mhgrove thanks for up-to-date response. I think this made things work for me in combination with installing haveged, which derives entropy from within CPU activity not relying on device drivers. This made my server start on a quiet and dedicated cloud machine which obviously has very little entropy coming from device drivers or anything else. 

I have come to believe that the decision of whether to require good (and blocking) entropy or not should be left as a deployment option, rather than making netty inherently less secure by changing the code to use the less secure way of getting random numbers for crypto.

**Comment by matanster** [comment]
Actually my netty server now unexpectedly shuts down right after starting to listen, for no apparent reason now, so maybe it is still the same underlying reason and I've not solved the entropy matter after all.

all the logs provide, is this ―

```
2016-06-04 11:26:46,870 [INFO] from play.core.server.NettyServer in pool-4-thread-4 - Listening for HTTP on /0.0.0.0:9010
2016-06-04 11:26:46,954 [INFO] from play.core.server.NettyServer in pool-4-thread-4 - Stopping server...
```

**Comment by normanmaurer** [comment]
I actually just opened a PR to change it to use the same technique as the JDK implementations does: https://github.com/netty/netty/pull/5345

**Comment by normanmaurer** [comment]
Finally fixed..

**Comment by nchammas** [comment]
@trustin @normanmaurer - These posts claim that `/dev/urandom` should be the preferred source of randomness, even for cryptographic applications:
* http://www.2uo.de/myths-about-urandom/
* http://security.stackexchange.com/questions/3936/is-a-rand-from-dev-urandom-secure-for-a-login-key/3939#3939
* https://sockpuppet.org/blog/2014/02/25/safely-generate-random-numbers/

Have you considered just using `/dev/urandom` all the time?

I don't know much about cryptography, so I'm just asking out of curiosity. It looks like the practical problem raised here has already been addressed by https://github.com/netty/netty/pull/5345 anyway.
