### ISSUE TITLE
DefaultSocks5CommandResponseTest produce buffer leak

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#3422]
See here:
http://clinker.netty.io/jenkins/job/netty-leak/branch/master/96/consoleFull

**Comment by normanmaurer** [comment]
@trustin please check :)

**Comment by normanmaurer** [comment]
@trustin ping

**Comment by trustin** [comment]
Thanks for the heads up! Fixed in 6d822195b0a59514b8fbeee15b0466735efb2289 (master) and 7aeafb9c09c55a001b92975ea8fb895554757aa5 (4.1)
