### ISSUE TITLE
Netty 4.0.24 Final doc bug for ServerBootstrap.group(). [bug]

### ISSUE THREAD

**Issue by smwikipedia** [netty/netty#3429]
The javadoc for ServerBootstrap.group() in 4.0.24.Final is incorrect.

![netty doc bug](https://cloud.githubusercontent.com/assets/999318/6202298/76248d8a-b51b-11e4-914f-9e8860d0625b.png)

The SocketChannel should be ServerChannel.

This bug is first reported in this stackoverflow thread:
http://stackoverflow.com/questions/28473116/netty-doc-bug-for-serverbootstrap-group

**Comment by normanmaurer** [comment]
Was fixed by #3430

**Comment by normanmaurer** [comment]
Was fixed be #3430
