### ISSUE TITLE
Multiple writeAndFlush cause a race condition that sometimes leak buffers

### ISSUE THREAD

**Issue by marcottedan** [netty/netty#3432]
Netty version: 4.0.9.Final && 4.0.25.Final
- Netty started with PARANOID mode

java version "1.7.0_40"
Java(TM) SE Runtime Environment (build 1.7.0_40-b43)
Java HotSpot(TM) 64-Bit Server VM (build 24.0-b56, mixed mode)

Operating system: Windows 7, 8 and CentOS 6

Context: 
We had an error in our code base that was flushing the socket twice for every write (we only write once per request). There seems to be a race condition in Netty in this particular case. It sometimes causes a DirectBuffer Memory Leak. This happens very very rarely. We've had this stack trace in production for months but have no idea how to reproduce it.

Our HTTP pipeline looks like that :

- HttpServerCodec
- HttpContentCompressor
- HttpContentDecompressor
- HttpObjectAggregator(65536)
- CustomMessageHandler that handle HTTP request (was flushing twice) extends CombinedChannelDuplexHandler<HttpInboundMessageHandler, HttpOutboundMessageHandler>
* --> HttpInboundMessageHandler extends ChannelInboundHandlerAdapter
* --> HttpOuntboundMessageHandler extends ChannelOutboundHandlerAdapter

Here's the stack trace, from a build using 4.0.25:

13483 14:07:41.301 [child-group-3-3] ERROR i.n.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected.
Recent access records: 0
Created at:
	io.netty.buffer.CompositeByteBuf.<init>(CompositeByteBuf.java:60)
	io.netty.buffer.AbstractByteBufAllocator.compositeDirectBuffer(AbstractByteBufAllocator.java:191)
	io.netty.buffer.AbstractByteBufAllocator.compositeBuffer(AbstractByteBufAllocator.java:169)
	io.netty.handler.codec.http.HttpObjectAggregator.decode(HttpObjectAggregator.java:149)
	io.netty.handler.codec.http.HttpObjectAggregator.decode(HttpObjectAggregator.java:54)
	io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
	io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	com.frimastudio.snowstorm.communication.protocol.common.TrafficReportingHandler.channelRead(TrafficReportingHandler.java:30)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	java.lang.Thread.run(Thread.java:724)

The TrafficReportingHandler class does (nothing) the following : 

@Sharable
public class TrafficReportingHandler extends ChannelDuplexHandler
{
	@Override
	public void channelRead(ChannelHandlerContext ctx, Object msg)
	{
		ctx.fireChannelRead(msg);
	}
}

**Comment by normanmaurer** [comment]
@marcottedan can you share your full code, or is it closed-source ?

**Comment by marcottedan** [comment]
Unfortunately it's closed-source and I moved to a new organization since the creation of this issue.

**Comment by normanmaurer** [comment]
@marcottedan I think without a reproducer it will be impossible to help here :(

**Comment by marcottedan** [comment]
@normanmaurer I totally understand. Sorry for not having able to help more.
