### ISSUE TITLE
Add unescapeCsv method to StringUtil.

### ISSUE THREAD

**Issue by danbev** [netty/netty#3435]
For the solution for #3237 involved adding a method named ```escapeCsv``` to StringUtil. We should also add the counter part of this, ```unescapeCsv```, to StringUtil.

**Comment by Scottmitch** [comment]
Thanks for capturing this issue @danbev!

Just as #3271 added the ability to automatically combine and CSV escape values associated with the same header name; we should also add the ability to automatically unescape values returned by the accessor methods.  For example `CharSequence get(Charsequence name)` in `DefaultTextHeaders` should be unescaping the values that are returned (under some condition...which may be the same condition that activates escaping).

**Comment by Scottmitch** [comment]
@danbev - Any updates on this issue?

**Comment by danbev** [comment]
Sorry this parenting thing was more time consuming than I expected. I don't
think I'll be of much use before I return to work in July I'm afraid.

onsdag 8 april 2015 skrev Scott Mitchell <notifications@github.com>:

**Comment by Scottmitch** [comment]
@danbev - O wow I had no idea...congratulations!  Take care of your family and forget about this ;)

**Comment by trustin** [comment]
@danbev Congratulations! :-D

**Comment by danbev** [comment]
Thanks guys!

fredag 10 april 2015 skrev Trustin Lee <notifications@github.com>:

**Comment by Scottmitch** [comment]
Thanks @windie for taking care of this! The second part of this issue was moved to https://github.com/netty/netty/issues/4855.
