### ISSUE TITLE
Maybe pre-instance CONNECTION_RESET_EXCEPTION_READ too?

### ISSUE THREAD

**Issue by besief** [netty/netty#3438]
Hi everybody,

we have been using netty 3.9 in the past and are looking to move to 4.0 now.
Because we are running our servers behind an haproxy, and due to the way haproxy balances connections, there are a lot of connection resets (~10k per minute) on our backend servers. With the NIO transport, we just ignored them. With the EPOLL transport, we are going to do the same, but I noticed that each of them has a stacktrace still, wheres with the NIO transport, they stopped having stacktraces after the first few.

Looking into the epoll code, I stumpled upon the comment
"TODO: We could even go futher and use a pre-instanced IOException for the other error codes, but for all other errors it may be better to just include a stacktrace." (Native.java@L129)

So I thought I'd just give you a heads up describing our case, in which pre-instantiation / an empty stack trace would definitely be preferable. Though, of course, the JIT can probably be expected to already kind of mitigate the impact, as it is. (Because in our case the stack trace will always be the same.)

Anyways, I'm just going to use this opportunity to say that I love this project. Awesome work everyone!

Regards

**Comment by normanmaurer** [comment]
@besief which version are you using ?

**Comment by besief** [comment]
Upgrading to 4.0.25.Final, but from skimming the sources here on github, behaviour doesn't seem to have changed in the other versions. (?)
Upgrading from 3.9.0.Final.

**Comment by normanmaurer** [comment]
I'm asking because CONNECTION_RESET_EXCEPTION_READ should be used already. Can you show me the stack trace you are seeing ?

**Comment by besief** [comment]
java.io.IOException: readAddress() failed: Connection reset by peer
```
io.netty.channel.epoll.Native.newIOException(Native.java:112):1 in ""
io.netty.channel.epoll.Native.ioResult(Native.java:128):1 in ""
io.netty.channel.epoll.Native.readAddress(Native.java:219):1 in ""
io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.doReadBytes(EpollSocketChannel.java:675):1 in ""
io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:714):1 in ""
io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326):1 in ""
io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264):1 in ""
io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116):1 in ""
io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137):1 in ""
java.lang.Thread.run(Thread.java:745):1 in ""
```

I'm talking about the following part of Native.java. As far as I understand it, certain exceptions are always reused (they are static final), while other get new instances via calls to newIOException.
```java
    private static IOException newIOException(String method, int err) {
        return new IOException(method + "() failed: " + ERRORS[-err]);
    }

    private static int ioResult(String method, int err, IOException resetCause) throws IOException {
        // network stack saturated... try again later
        if (err == ERRNO_EAGAIN_NEGATIVE || err == ERRNO_EWOULDBLOCK_NEGATIVE) {
            return 0;
        }
        if (err == ERRNO_EPIPE_NEGATIVE) {
            throw resetCause;
        }
        if (err == ERRNO_EBADF_NEGATIVE) {
            throw CLOSED_CHANNEL_EXCEPTION;
        }
        // TODO: We could even go futher and use a pre-instanced IOException for the other error codes, but for
        //       all other errors it may be better to just include a stacktrace.
        throw newIOException(method, err);
    }
```
Of course, resetCause will always be the same CONNECTION_RESET_EXCEPTION_READ object (that is also static final), but what is given to the user code then will be a newly instanced IOException.

**Comment by normanmaurer** [comment]
@besief ah I see... it's a bug. Let me fix it.

**Comment by besief** [comment]
Cool, thanks.

ps: Sorry for not including all the details in the initial posting, I thought everything might be clear enough by just referring to that comment. :)

**Comment by normanmaurer** [comment]
@besief no worries... Thanks again to open the bug report!

**Comment by normanmaurer** [comment]
Fixed...
