### ISSUE TITLE
Clean up HTTP/2 MAX_CONCURRENT_STREAMS logic

### ISSUE THREAD

**Issue by nmittler** [netty/netty#3451]
There are several methods on `Http2Connection.Endpoint` that involve this parameter:

`acceptingNewStreams`
`createStream`
`reservePushStream`
`maxStreams` (getter and setter)

It is not always clear which direction the value applies to.  It's probably worth a pass to:

1) Make sure we're actually using it correctly in all places.
2) See if we can make the interface more clear as to the directionality of the parameter

**Comment by Scottmitch** [comment]
@nmittler - Do you have any suggestions to improve clarity?  By `direction` do you mean local/remote? The only thing that may be tough is the Endpoint interface is agnostic to direction due to it serving as both remote/local.

**Comment by nmittler** [comment]
@Scottmitch I haven't put much thought into it yet :).  For push, we do clarify direction with the method name `endpoint.allowPushTo()`.  Perhaps something like `endpoint.maxConcurrentStreamsFromPeer()` or `endpoint.maxRemotelyInitiatedConcurrentStreams`?

This would more clearly map to the `SETTINGS_MAX_CONCURRENT_STREAM` parameter from the spec.  It would, however, invert our current logic which maintains the value as the `maxStreams` that can be created by the endpoint.

WDYT?

**Comment by Scottmitch** [comment]
@nmittler - Seems a bit overloaded/confusing if the `remote` (or `local`) endpoint has a `remote` method.  In this context it already takes a second to get oriented when the "local" settings uses the "remote" endpoint's `maxStreams` [here](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L146)...and if we add more directionality...does that conceptually invert the relationship :)  A bit of devils advocate but I just want to be sure we can clarify the situation by adding more directionality context.

**Comment by nmittler** [comment]
@Scottmitch yes, the idea would be to invert the relationship so that the "local" settings use the local endpoint for everything. I think this would help to make things more clear for everyone wading through that code.

Naming is always tricky and I agree with all of your comments.  Suggestions are definitely welcome! :)

**Comment by Scottmitch** [comment]
@nmittler - Ok thanks for clarifying.  I think I understand the scope of your suggestion...thought we were just changing names and keeping existing structure.  Sounds like we are in agreement...I will think on it.

**Comment by nmittler** [comment]
@Scottmitch @buchgr here are my proposed changes to the `Endpoint` interface:

`createStream` (no change)

`acceptingNewStreams` becomes `canCreateStream`, and is documented to say that it compares against the `maxConcurrentStreams` of the opposite endpoint.

`numActiveStreams` becomes `concurrentStreams` and is documented to say the number of concurrent streams created by this endpoint.

`maxStreams` becomes `maxConcurrentStreams` and is documented to say that it's the number of concurrently active streams allowed to be created by this endpoint. This essentially keeps the logic as-is, but I think the documentation along with the other name changes help to clarify things a bit.  I considered having it represent the max concurrent streams allowed by the opposite endpoint, but all of the other methods refer to creating streams from this endpoint so I think it makes sense the way it is.

Thoughts?

**Comment by nmittler** [comment]
@Scottmitch any thoughts on this?  I think this change may be less controversial than the #3491 :)

**Comment by Scottmitch** [comment]
@nmittler - I'm sorry for the delay :(  +1 to your most recent suggestions.
