### ISSUE TITLE
latency significantly worse in http://www.techempower.com/ benchmark 10 preview

### ISSUE THREAD

**Issue by ceeaspb** [netty/netty#3455]
It could be the benchmark or netty....
The plaintext latency is significantly worse from round 9 to 10.
http://www.techempower.com/benchmarks/previews/round10/#section=data-r10&hw=peak&test=plaintext

May be of interest to review whilst it is in preview, before the final test is run.

**Comment by trustin** [comment]
Comparing to the round 9, the throughput has been increased from 2.7M reqs/sec to 3.8M reqs/sec, while the average latency has been increased from 233ms to 3460ms. Standard deviation has been increased by 2x, but II'm not sure if it is possible to get 10x worse average latency with 40% more throughput.  Thoughts?

**Comment by JatinderSingh** [comment]
@ceeaspb  Can we benchmark latency using https://github.com/LatencyUtils/LatencyUtils.
Latency does not follow normal distribution which makes averaging it out pointless.  This tool stores all values of latency and can help in visualizing the percentiles where latency starts increasing.

**Comment by daschl** [comment]
I bet if they cap the throughput at ~3M req/s you'll see the same percentiles. As @JatinderSingh  pointed out, averages and std. deviation on latency benchmarks are a joke. Only percentiles and max'es count at a specific throughput.

**Comment by JatinderSingh** [comment]
I use a mod of wrk (https://github.com/giltene/wrk2) which is integrated with above tool to measure latency percentiles, It provides option to cap the throughput and measure latency. I guess it might help in comparing frameworks.

**Comment by normanmaurer** [comment]
Let me close this for now.. I did some benchmarks and it seems to be "ok"
