### ISSUE TITLE
Latency between a writeAndFlush call and the actual data transportation.

### ISSUE THREAD

**Issue by dimitris01** [netty/netty#3459]
I have a thread that writes and flashes, with a frequency of 10 Hz, a message of 92 bytes using a netty(4.1.0.Beta) DatagramChannel, bootstraped for multicast. Using wireshark I don't verify the desired result, since instead of one message per 100 ms, I see 10 (ten) messages, all send at the same time, every second. The content of the message contains the timestamp and I can verify that each message has a difference in the timestamp exactly 100ms. Is there something I have missed during the channel bootstrap? Or is it a system network configuration?

**Comment by trustin** [comment]
That's not an expected behavior. Could you share the reproducer?

**Comment by normanmaurer** [comment]
I wonder if this is for OIO and id the SO_TIMEOUT..

**Comment by dimitris01** [comment]
Yes I have to use OioEventLoopGroup and OioDatagramChannel, because our java version <1.7. Is there a way to fix this without going to java 1.7?

**Comment by normanmaurer** [comment]
Do you need multicast? everything else should work with NIO even < java7

**Comment by dimitris01** [comment]
I have to use multicast, since it is required. By the way how can I use NIO with java < 7, because I always have runtime errors

Date: Tue, 3 Mar 2015 01:54:27 -0800

**Comment by trustin** [comment]
It's the limitation of OIO transport. I don't have a good idea to fix it.

**Comment by dimitris01** [comment]
Ok, thanks for the response. I will try java 7 for multicast.
