### ISSUE TITLE
Memory leak when multiple network interface is used

### ISSUE THREAD

**Issue by mingfai** [netty/netty#3462]
I have a netty server that accept connections and broadcast messages to clients. The server listens to 0.0.0.0 . Recently, I realize when there are connections from both 127.0.0.1 and the server's IP address, there are serious memory leak and basically every outgoing Direct ByteBuffer were strongly referenced and cannot be gc'd. When only one network interface is used, there is no such problem.

The problem doesn't affect me any more once the behavior is identified. I'm just reporting to see if it is a Netty bug.

environment
```
Netty: 4.0.25.Final, 4.0.26.Final
Java: java version "1.8.0_31"
  Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
  Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
Linux: Linux 3.13.0-32-generic 
```

Server Bootstrap code
```
new ServerBootstrap()
                    .option(ChannelOption.SO_BACKLOG, 1000)
                    .group(boss, work)
                    .channel(NioServerSocketChannel.class)
                    .option(ChannelOption.TCP_NODELAY, true)
                            //.childOption(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT) //not active, so the server is using default allocator            
```

Code that write simply use writeAndFlush to a ChannelGroup:
```
ChannelGroup connections = new DefaultChannelGroup(GlobalEventExecutor.INSTANCE);
connections.writeAndFlush(buf, matcher);
```

**Comment by Scottmitch** [comment]
@mingfai - Thanks for reaching out and reporting this issue.  Do you observe this problem only when these 2 connections are present?  For example if you have 2 connections from other interfaces is the problem still present?  Is there an interesting combination of 2 connections that isn't exactly what you reported where the issue still exists?

**Comment by mingfai** [comment]
@Scottmitch there are two connections from remote and one connection to the loopback address. 

With further investigation, my initial assessment that suggest using two different interfaces is may probably be wrong. instead, the non-loopback interface is busy and not able to flush the bytes to the network fast enough. by not to use the loopback address and also reduce network activity the leak seems to be gone. 

the symptom is a lot DirectByteBuffer accumulated in the heap can't be free even by a explicit force GC with JVisualVM, and the heap dump indicates those direct buffer are strong referenced. So I can just say in certain scenario, there is memory leak, but can't tell what exactly caused the leak yet.

i'll keep this issue updated. thx

**Comment by normanmaurer** [comment]
@mingfai also if you could share the heap dump and / or provide a reproducer it would be easier to help. Thanks!

**Comment by mingfai** [comment]
i think i can't provide more information on this issue. thx for your help.

**Comment by SUNILKAITHA** [comment]
we have upgrade to 4.0.33 then we started seeing High CPU Utilization and server unresponsive . We are using same SimpleChannelInboundHandler for WebSocket and Http Requests . Any help on this greatly appreciated.

we are seeing weird behavior , We are running some Load Test with 400 to 500 websocket connections open and sendign 100-200k messages . Load Testing is going perfectly well but actually the problem starts after compeltion of the Test , Memory Utilization is increasing within short time (1hr to 2hr) then CPU Utilization is reaching 100% and Server unresponsive and some requests are able process at this time also but only 5% chance of success.

**Comment by Scottmitch** [comment]
@SUNILKAITHA - please open a new issue and provide a reproducer if possible
