### ISSUE TITLE
EpollSocketChannel.localAddress() returns always null if Native.connect() was not able to connect directly

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#3463]
See:
https://github.com/netty/netty/issues/3328#issuecomment-77117377

**Comment by normanmaurer** [comment]
This Regression was introduce by myself (sigh) : https://github.com/netty/netty/commit/b898bdda846a4cc4ae5d6261406b138f5393d018

**Comment by normanmaurer** [comment]
Fixed... /cc @hepin1989

**Comment by hepin1989** [comment]
btw,I notice that when this issue occur,It was connect to the localhost address.
Like 10.11.0.147 try to connect to 10.11.0.147.
I will try the snapshort tomorrow.
