### ISSUE TITLE
Netty 4.0.26: no channelUnregistered callback for failed connection

### ISSUE THREAD

**Issue by aaronriekenberg** [netty/netty#3464]
With 4.0.25 and earlier, if initiating a client connection to the server fails I get SimpleChannelInboundHandler.channelRegistered called when the channel is created, then SimpleChannelInboundHandler.channelUnregistered is called because the connect fails.

With 4.0.26, if initiating a client connection to the server fails I get SimpleChannelInboundHandler.channelRegistered called when the channel is created, but SimpleChannelInboundHandler.channelUnregistered is never called.  In 4.0.26 it seems channelUnregistered is only called if the connection succeeds (channelActive) then is broken (channelInactive).

This breaks programs that set a timer to try reconnecting in channelUnregistered if the initial connect fails.

I can provide an example program if its helpful - this is easy to recreate.

**Comment by trustin** [comment]
Fixed in 5d15e18 (4.0), 068132f (4.1), e9d1aa2 (master)

**Comment by trustin** [comment]
Thanks for reporting, @aaronriekenberg!
