### ISSUE TITLE
Netty 3.9.6 > 3.10.0 degradation in AbstractChannel/AbstractNioChannel

### ISSUE THREAD

**Issue by virtman** [netty/netty#3466]
Hello,

just got crazy last days when trying to understand why my program stopped to shovel data correctly between two nio tcp channels.
It may be reproduced with actual HexDumpProxyInboundHandler example +  some webserver supporting multi part serving to start part downloads parallely + try to downlod some big file with download manager.
I tried to download 500mb big file with Downalod Manager via HexDumpProxyInboundHandler connecting to Webserver. 
DownloadManager>HexDumpProxyInboundHandler>WebServer>500mb_file
Issue happens even when doing that locally.
The issue happens accidently by using commands setReadable(false) or setReadable(true)
In few words, when only one file part gets shoveled.
Netty 3.9.6   > OK
Netty 3.10.0 > OK
but as soon the download manager tries to download the file by downloading it as parts parallely, as example 10 parallel downloads, accidently some channel/or sometimes 2/3 channels get not anymore set to readable with setReadable(true) (even if channel answers after setting with true by .isReadable(), so that Webserver is unable to send the rest data on this channel.
Netty 3.9.6   > OK
Netty 3.10.0 > BIG KO
I spent few days in trying to fix it by believing it is my issue, until I used the previous 3.9.6, which was working immediatelly perfect. So I looked what could be changed so much, that this caused such degradation, and saw big difference/update in AbstractChannel/AbstractNioChannel that highly caused this degradation between Netty 3.9.6 and Netty 3.10.0 
I did not try to discover exactly, what kind of issue that is and at which point that happens, pretty sure, the one who made these changes, knows exactly what he did and what he should check, why these issues began to happen.
My actual conclusion, Netty should remove degradated code from 3.10 and set it back as it was in 3.9.6 until getting fixed.

**Comment by normanmaurer** [comment]
@virtman could you please submit a reproducer that shows the problem ?

**Comment by virtman** [comment]
Just question since I am not familiar with, what kind of reproducer do you want, because no exception gets thrown, the stream just stops and gets unwritable for webserver..
Or do you want compiled version of HexDumpProxyInboundHandler from 3.10.0?

**Comment by virtman** [comment]
[URL=http://www.file-upload.net/download-10392766/error_reproducer.zip.html]error_reproducer.zip[/URL]
I have also uploaded full archive with reproducer.
It is already precompiled, but you can compile it by your self, sources are available.
When you wish to compile or to start
Adjust path to jdk, actually preset
C:\Program Files (x86)\Java\jdk1.8.0_25\

The batch file 1_start.bat starts as two separate java processes
1. HttpStaticFileServer on port 800 with www folder of batch file where it was started
2. HexDumpProxy 80 127.0.0.1 800, also on port 80 and forwards to 127.0.0.1:800

and compile.com compiles the data.
The own implementation HttpStaticFileServer supports multi download parts and download resuming, and has own implementation on files serving bigger than 500kbytes or when multi part was requested. (my conntribution)

When file download gets started via HexDumpProxy
as example http://127.0.0.1/a.zip
DownloadManager>HexDumpProxy_127.0.0.1:80>127.0.0.1:800>HttpStaticFileServer
sometimes one of channel get's not set to setReadable(true) and part never finishes.
but by direct download from webserver http://127.0.0.1:800/a.zip
everything gets downloaded perfectly and had never any issue.

**Comment by virtman** [comment]
Ok, the issue seems to be fixed with 3.10.1, it does not anymore happen, so I assume that was the cause of to early fired change notification.
However that is a pity, I can not figure out, if the change was fired because it was set to setReadable true/false, or because the channel changed it's writability state
May be I do not know hidden details, or is there a way? (except throwing error inside interest change function, catching this error and look up to the tree, if I called it with setReadable, this way works, but is not what i wish due speed)
