### ISSUE TITLE
When Channel connect failure,Channelbecome invalid;

### ISSUE THREAD

**Issue by chzhuo** [netty/netty#3470]
when Channel connect failure,Channel should give a method to replace the socket,not replace Channel.

**Comment by rockagen** [comment]
I think that's not a good idea.

**Comment by normanmaurer** [comment]
Same here... Can you explain why you think it makes sense?

**Comment by daschl** [comment]
Same here, the problem is that this will render lots of handler events useless and ambiguous (like channel active and so forth), since you very often need to bind them to implicit socket events. I'm sure your use case can be handled with our current semantics as well :)

**Comment by trustin** [comment]
No proper rationale
