### ISSUE TITLE
Memory leak during high load. 4.0.25.final, 4.0.26.final.

### ISSUE THREAD

**Issue by doom369** [netty/netty#3475]
Hi guys. First of all, thank you, for great project! 
I think I found memory leak during my performance testing.

I launched a server on VM with 2 CPUs (Xeon E5-2660 2.20GHz) under Ubuntu 14.04.1 LTS with java 1.8.0_31. And started performing load testing from another machine.

Test scenario is pretty simple:
1) Create 100 pairs of channels (1 pair is app and hard channels);
2) In loop send message from app channel; 
```
 while (true) {
       for (ClientPair clientPair : clients) {
            clientPair.appClient.send("hardware 1 1");
        }
        sleep(10);
  }
```
3) When server retrieves message it decodes it and forwards to connected hard channel and sends OK message back to app channel.
That's it. Protocol is binary and every message is only ~8-10 bytes. 

Initially I created 100 pairs and with code above generated ~10k req/sec. Server was pretty healthy with no problems during long term run. Network traffic was only ~1 MB/sec.
```
%Cpu0  : 10.6 us, 13.6 sy,  0.0 ni, 64.2 id,  0.0 wa,  0.0 hi, 11.6 si,  0.0 st
%Cpu1  : 10.3 us, 10.0 sy,  0.0 ni, 58.5 id,  0.0 wa,  0.0 hi, 21.3 si,  0.0 st
```

After that I decided to increase load by 50% by increasing number of client pairs to 150. After test restart I found that memory consumption started growing quickly. After few minutes I stopped generating load and java server process was 200% busy even without any load (look like GC was in infinite loop).

Here is heap dump:
![netty_4 0 25 final leak](https://cloud.githubusercontent.com/assets/1536494/6548390/ab855078-c5ff-11e4-9ebb-87f7e6405c01.png)

I also tried netty-4.0.26.final. And situation with it much better - memory leak still in place but memory consumption was few times slower than in 4.0.25.final version.
![netty_4 0 26 final leak](https://cloud.githubusercontent.com/assets/1536494/6548403/31c0b6f0-c600-11e4-85a7-14db777c801a.png)

Test itself you can find [here] (https://bitbucket.org/theblynk/blynk-server/src/194219672164a0e0560d26e44678af0468c8ac73/integration-tests/src/test/java/cc/blynk/integration/SimplePerformanceTest.java?at=master). Handler [here] (https://bitbucket.org/theblynk/blynk-server/src/194219672164a0e0560d26e44678af0468c8ac73/server/tcp-server/src/main/java/cc/blynk/server/handlers/workflow/HardwareHandler.java?at=master). Protocol encoder/decoder [here] (https://bitbucket.org/theblynk/blynk-server/src/194219672164a0e0560d26e44678af0468c8ac73/common/src/main/java/cc/blynk/common/handlers/?at=master). Server build [here] (https://bitbucket.org/theblynk/blynk-server/src/194219672164a0e0560d26e44678af0468c8ac73/build/server-0.1.jar?at=master#) if you want to reproduce locally run "java -jar server-0.1.jar". It needs java 8.

Do you aware of such issue? Let me know If I could provide you with more info.

**Comment by trustin** [comment]
Note that sending a message in Netty is asynchronous, which means you'll get `OutOfMemoryError` or the VM will enter GC spiral if you write many messages without making sure they are really sent out to the socket. `Thread.sleep(10)` is not a good idea because your write request can take more than 10 milliseconds.

**Comment by doom369** [comment]
I understand it is asynchronous and what does that mean. But why memory never released after I stopped performing test?

**Comment by trustin** [comment]
OK. Then please:

- fix your test
- fix your leaks in your code (read [this](http://netty.io/wiki/reference-counted-objects.html))
- rerun your test with higher JVM max memory

.. so that I can make sure this is really a bug in Netty.

**Comment by doom369** [comment]
Trustin,

1. My test is correct. It consuming only few resources and has no problem with CPU, memory or software interrupts; If you want me to wait response from server after every write operation I'll be not able to make high load;
2. I profiled both server and clients and didn't find any memory leaks in my code. Moreover - all resource management is done by ReplayingDecoder and MessageToByteEncoder. I don't make any allocations in my own code;
3. Heap size is big enough for my tasks. The funny thing is - my server during 10k req/sec consumes only 300mb of heap and works as expected without growing heap. Problems only appear after load increases and server starts consuming more and more and never releases it.

Here is also stacktrace during high-load. Maybe it will clarify something more. I also will try to use today native epoll transport so maybe situation there will be different.

```
"nioEventLoopGroup-4-2" #22 prio=10 os_prio=0 tid=0x00007f0650014800 nid=0x713d 
runnable [0x00007f06710bf000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x00000000ca81c068> (a io.netty.channel.nio.SelectedSelectionK
eySet)
        - locked <0x00000000ca81d0d8> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000000ca81bfd0> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:111)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorato
r.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by trustin** [comment]
Instead of sleep(10), you have to do this:

```java
void generateTraffic(Channel ch) {
    while (ch.isWritable()) {
        ch.write(msg);
    }
    ch.flush();
}

... in your load generating handler:

public void channelActive(ctx) {
    generateTraffic(ctx); // Generate the initial traffic
}
public void channelWritabilityChanged(ctx) {
    generateTraffic(ctx);
}
```

Also, your server-side decode has a leak. Are you sure it was not logged? Try to run at paranoid level.  Specifically, this has a leak:

```java
buf.readBytes(...).toString(charset);
```

`ByteBuf.readBytes(int)` returns a newly created buffer and thus you must release it. In this case, you could just use `readSlice(int)` because you do not need to release:

```java
buf.readSlice(...).toString(...);
```

I didn't spent a lot of time looking into your code due to lack of time, but I'm definitely interested in how this goes, so please be patient and let me know your findings. Please let me know if you still find a problem after fixing your tests and decoder. I will try to reproduce it on my machine.

**Comment by doom369** [comment]
Trustin,

before I read your message I tried 4.1.0.Beta4 version and run 10 hours long night test with 12k req/sec load. No leaks.

But, after applying proposed changes I switched back to 4.0.26.final and seems you're right. It was a memory leak in my code.

Thank you and sorry for taking your time.

**Comment by normanmaurer** [comment]
@doom369 thanks for the feedback!
