### ISSUE TITLE
Make TrafficCounter more general again

### ISSUE THREAD

**Issue by ngocdaothanh** [netty/netty#3476]
About a change in Netty 4.0.25:

I'm writing a **UDP** packet sender and I need to control the number of packets per second to send out.

I'm using TrafficCounter to control the rate to create packets. This rate controller doesn't use Netty's handler pipeline architecture. It's just a normal Java thread that loops forever. It:
* Sends a packet.
* Asks TrafficCounter how much time it should sleep.
* Sleeps.
* Send another packet.

TrafficCounter constructor:

```java
TrafficCounter(
  AbstractTrafficShapingHandler trafficShapingHandler,
  ScheduledExecutorService executor,
  String name,
  long checkInterval
)
```
In Netty 4.0.24, I can create a TrafficCounter instance like this:

```java
new TrafficCounter(
  null,
  Executors.newScheduledThreadPool(1),
  "serviceName",
  5000
)
```

From Netty 4.0.25, the above code will throw exception, saying that trafficShapingHandler is now required.

So I now have to create a dummy one like this:

```java
new TrafficCounter(
  new ChannelTrafficShapingHandler(5000),
  Executors.newScheduledThreadPool(1),
  "serviceName",
  5000
)
```

Should trafficShapingHandler be allowed to be null as before? Or should another constructor that doesn't require a trafficShapingHandler be added to TrafficCounter?

**Comment by trustin** [comment]
How about retaining the current behavior (disallow null handler) and adding a new constructor that does not require a handler parameter? That should make your life much easier.

**Comment by trustin** [comment]
See #3477

**Comment by ngocdaothanh** [comment]
Thanks Trustin :+1:
