### ISSUE TITLE
epoll throws an "Invalid Argument" error in writev() 

### ISSUE THREAD

**Issue by anfeng** [netty/netty#3484]
I am using Netty 4.0.19.Final, and got the following exception when a server handler is writing a response buffer. Any suggestions?

18:09:41 2015-03-10 18:09:36,149 [epollEventLoopGroup-68-1] WARN  server.ServerHandler - Server 8080 got an exception:
18:09:41 java.io.IOException: Error while writev(...): Invalid argument
18:09:41 	at io.netty.channel.epoll.Native.writev(Native Method)
18:09:41 	at io.netty.channel.epoll.EpollSocketChannel.writeBytesMultiple(EpollSocketChannel.java:130)
18:09:41 	at io.netty.channel.epoll.EpollSocketChannel.doWrite(EpollSocketChannel.java:191)
18:09:41 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:694)
18:09:41 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:206)
18:09:41 	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollOutReady(EpollSocketChannel.java:471)
18:09:41 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:322)
18:09:41 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
18:09:41 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
18:09:41 	at java.lang.Thread.run(Thread.java:745)

**Comment by normanmaurer** [comment]
@anfeng please upgrade to 4.0.26.Final... The version you are using is quite old. If you still have problems reopen
