### ISSUE TITLE
Unify Promise interfaces

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3485]
The signatures don't line up between [AbstractChannel.newPromise](https://github.com/netty/netty/blob/master/transport/src/main/java/io/netty/channel/AbstractChannel.java#L292) and [EventExecutor.newPromise](https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/concurrent/EventExecutor.java#L79). Return type difference and no argument to take the channel into account. This may mean more involved interface changes to resolve this...any ideas?

After this is resolved the following should be investigated (either new issue or resolved as part of this if it makes sense.

AbstractChannel factory methods that generate promise objects should delegate to its EventExecutor.

**Comment by Scottmitch** [comment]
PR https://github.com/netty/netty/pull/3392 would benefit from this.

**Comment by Scottmitch** [comment]
@trustin @louiscryan - FYI.

**Comment by trustin** [comment]
Assuming this will introduce some breaking changes, shoudn't it should be for 5.0?

**Comment by normanmaurer** [comment]
@trustin +1

**Comment by hepin1989** [comment]
https://github.com/reactive-streams/reactive-streams-jvm/issues/268

maybe this help,for the Promise.

**Comment by bsideup** [comment]
@Scottmitch @normanmaurer would you join the conversation if we make another reincarnation of https://github.com/reactive-streams/reactive-streams-jvm/issues/268 ? I guess it may also be relevant for ServiceTalk.

**Comment by normanmaurer** [comment]
We did do this for netty 5. /cc @chrisvest
