### ISSUE TITLE
Fix the critical multithreaded correctness issues discovered by Clinker Sonarqube

### ISSUE THREAD

**Issue by futurely** [netty/netty#3486]
http://clinker.netty.io/sonar/drilldown/issues/io.netty:netty-parent:master?severity=CRITICAL

Multithreaded correctness - Inconsistent synchronization	7	
Multithreaded correctness - Incorrect lazy initialization of static field	1

**Comment by Scottmitch** [comment]
@futurely - Thanks for bringing out attention to this.  @jpinner has already commented on these and indicated they were false positives.  @trustin - Is there any way to mark them as such in sonar?

**Comment by trustin** [comment]
I marked all but the `OpenSslEngine` one as false positives. @normanmaurer, could you confirm if it's a false positive or not?

**Comment by normanmaurer** [comment]
@trustin actually I think this one is fixed as part of https://github.com/netty/netty/pull/3481
