### ISSUE TITLE
Remove the 13,058 duplicated lines of 545 duplicated blocks in 172 duplicated files

### ISSUE THREAD

**Issue by futurely** [netty/netty#3487]
http://clinker.netty.io/sonar/drilldown/measures/3670?highlight=duplicated_lines_density&metric=duplicated_lines

http://clinker.netty.io/sonar/drilldown/measures/3670?metric=duplicated_lines

http://clinker.netty.io/sonar/drilldown/measures/3670?metric=duplicated_blocks

http://clinker.netty.io/sonar/drilldown/measures/3670?metric=duplicated_files

**Comment by Scottmitch** [comment]
@futurely - We love pull requests :) Any interest in contributing a PR?

**Comment by futurely** [comment]
I've no idea if the open source committee of my company would permit.

**Comment by hepin1989** [comment]
you could send a pr in your free time :P

**Comment by normanmaurer** [comment]
Let me close this for now
