### ISSUE TITLE
Remove Frame class from DefaultHttp2RemoteFlowController.

### ISSUE THREAD

**Issue by nmittler** [netty/netty#3488]
The Frame now just contains the payload and doesn't maintain any other state.  To reduce GC pressure, we should probably discard this class and move it's methods to the FlowState.

**Comment by Scottmitch** [comment]
+1.  Thanks @buchgr for taking this one on!

**Comment by nmittler** [comment]
@Scottmitch @normanmaurer shall I cherry-pick?
