### ISSUE TITLE
DefaultChannelId - Failed to find a usable hardware address on EC2

### ISSUE THREAD

**Issue by kubes** [netty/netty#3490]
Running 5.0.0.Alpha2 on EC2 I get the following warning:

WARN  DefaultChannelId - Failed to find a usable hardware address from the network interfaces; using random bytes: xxxxxxxxxxxxxxx

The system has two network interfaces:

eth0      Link encap:Ethernet  HWaddr 22:00:0B:7A:47:BD  
          inet addr:10.61.194.198  Bcast:10.61.194.255  Mask:255.255.255.0
          inet6 addr: fe80::2000:bff:fe7a:47bd/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:9001  Metric:1
          RX packets:13458177 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6024704 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:14279224426 (13.2 GiB)  TX bytes:6007218439 (5.5 GiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:7704 errors:0 dropped:0 overruns:0 frame:0
          TX packets:7704 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:4912763 (4.6 MiB)  TX bytes:4912763 (4.6 MiB)

The problem as I see it comes down to the scoreAddress method.  The default 127.0.0.1 best address is scored as a 4 and the 10.61.194.198 address is scored as a 2.  This results in a compareAddresses score of 2 which in turn does not replace the 127.0.0.1 with 10.61.194.198.

https://github.com/netty/netty/blob/master/transport/src/main/java/io/netty/channel/DefaultChannelId.java#L182

I am pretty sure the scoreAddress method needs to handle the case where it is a loopback address and if it is then return 0.  This would fix the scoring and the appropriate interface would be replaced and used.

https://github.com/netty/netty/blob/master/transport/src/main/java/io/netty/channel/DefaultChannelId.java#L283

**Comment by normanmaurer** [comment]
@kubes sounds good... could you submit a PR ?

**Comment by jeffreyji666** [comment]
I have encountered the same error, I refactor the scoreAddress method  as follows:
> private static int scoreAddress(InetAddress addr) {
        if (addr.isAnyLocalAddress() || addr.isLoopbackAddress()) {
             return 0;
         }

I did add the loop back address check, however I still have the same error after I build the netty.

Anyone has a solution?

**Comment by nmittler** [comment]
I've encountered this as well.

@kubes were you going to throw together a PR?

**Comment by kubes** [comment]
@nmittler I haven't had time to yet.  In the middle of a big project.  I may have some time in a couple weeks, if so I can put something together.  Let me know if you have time to do it before then.

**Comment by nmittler** [comment]
Created PR #3764
