### ISSUE TITLE
Use java requireNotNull instead of netty's checkNotNull

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3500]
Netty's [checkNotNull](https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/internal/ObjectUtil.java#L29) method is a duplicate of java's [requireNonNull](http://docs.oracle.com/javase/7/docs/api/java/util/Objects.html#requireNonNull(T,%20java.lang.String)) provided by jdk7.  We should use the JDK method instead of duplicating functionality.

**Comment by nmittler** [comment]
+1!

**Comment by normanmaurer** [comment]
@Scottmitch @nmittler just be sure we need to keep java 6 and 7 for netty 4.0 an 4.1

**Comment by Scottmitch** [comment]
@normanmaurer - Good point...that is more painful.

**Comment by trustin** [comment]
We can still do think for master. :-)

**Comment by normanmaurer** [comment]
As there is no master anymore we can close this
