### ISSUE TITLE
Investigate exception handling WRT Http2Connection.Listener notifications

### ISSUE THREAD

**Issue by nmittler** [netty/netty#3501]
We should take a closer look at how we notify the listeners of connection events and consider the proper course of action if a listener callback throws.

**Comment by Scottmitch** [comment]
+1. Thanks for reporting!

**Comment by Scottmitch** [comment]
@nmittler - I'll take this one.  As part of the resolution to https://github.com/netty/netty/issues/3550 I needed to do additional iteration over methods which use listeners and so I had to do something about this issue.  My approach was to catch `RuntimeExceptions` and only throw the last one:

```java
RuntimeException lastException = null;
for (Listener l : listeneres) {
  try {
    l.notify(...);
   } catch (RuntimeException e) {
    lastException = e;
   }
}
if (lastException != null) {
  throw lastException;
}
```

Does this make sense?  The goal being 1 listener's exception shouldn't cause other listener's from being notified.  However I am throwing 1 exception at the end of notification...just to ensure the exception is not swallowed...WDYT?

**Comment by nmittler** [comment]
@Scottmitch yep that sgtm ... that's sort of what I was thinking as well.  Make it so!

**Comment by Scottmitch** [comment]
@nmittler - Fair warning...it is ugly to ensure we process all events and complete all tree operations and also handle the `RuntimeExceptions` :(

**Comment by Scottmitch** [comment]
@nmittler - An alternative approach could be that we document the `Http2Connection.Listener` interface will result in the connection being closed.  This way we don't have to worry about tracking exceptions in recursive calls, and making sure state (stream state, priority tree, etc...) is maintained in the presence of exceptions.

**Comment by nmittler** [comment]
@Scottmitch yeah, that actually sounds better to me.  Let's keep it simple and just update the docs.

**Comment by Scottmitch** [comment]
@nmittler - I have to investigate but there may be code changes to ensure this always results in a GO_AWAY.  For example the removal policy stuff makes this a bit more complicated.  Perhaps we should handle this issue after https://github.com/netty/netty/issues/3448?

**Comment by nmittler** [comment]
@Scottmitch yeah that's fine.

**Comment by Scottmitch** [comment]
Reminder to me...also fix https://github.com/netty/netty/pull/3577/files#r27757163.

**Comment by Scottmitch** [comment]
@nmittler - I have looked at this a bit more.  When events occur as a result of read operations I think we ultimately catch the `RuntimeExceptions` and translate these to GO_AWAY frames.  However on the send side we don't do this, but instead we sometimes (depending on if try/catch blocks are placed appropriately) fail the promise that was provided in the `writeXXX` call.  My concern is that we are in a situation where we use listeners to update stream state, and it is possible that 1 listener (potentially user listener) could interrupt this process, and then we just continue processing events while in a bad state.  Should we translate runtime exceptions on the write side into `lifecycleManager` failure events?  Any other ideas?

**Comment by nmittler** [comment]
@Scottmitch yeah, I think that makes sense.  So fail the promise and send RST_STREAM/GO_AWAY.  Are you thinking of just adding this as try/catch logic to each encoder.writeXXX method?

**Comment by Scottmitch** [comment]
@nmittler - I will investigate more but I think so....it is not ideal to handle these events up the pipeline because then the classes which invoke the listeners are implicitly depending on those higher level classes to be present to clean up....I think the other options are to track exceptions at the call sites and either log them or throw the last one...but as I said this gets ugly...especially if we want to propagate 1 of the exceptions in the recursive calls we have.

**Comment by Scottmitch** [comment]
@nmittler - A "cleaner" alternative (from us tracking the exceptions perspective) is just to "log and swallow" these types of exceptions at the call site.  We won't have to worry about tracking/propagating the exceptions...but swallowing exceptions is terrible too....

**Comment by nmittler** [comment]
@Scottmich actually, I think I like logging (WARN?) better. Do you want to throw a PR together?

**Comment by Scottmitch** [comment]
@nmittler - I'm glad you said that because I just finished a PR for this..and just added a unit test for it ;)

**Comment by Scottmitch** [comment]
@nmittler - I updated the javadocs to describe this behavior (and logged it as an error).

**Comment by Scottmitch** [comment]
#3615 cherry-picked
