### ISSUE TITLE
Privacy violation in io.netty.handler.codec.socks.SocksAuthRequest

### ISSUE THREAD

**Issue by petardp** [netty/netty#3504]
There are two places in the SocksAuthRequest constructor where an IllegalArgumentException is thrown with a password as part of the exception message.
This constitutes mishandling of confidential information, which can compromise user privacy and is flagged as critical by security scanners.

**Comment by trustin** [comment]
Thanks for reporting. Fix has been pushed to all affected latest branches:

faf1d90 (3.10), 9091e66 (4.0), 1d061bb (4.1)

Please note the new `socksx` package is not affected by this issue.  Please consider migrating to `socksx`.

**Comment by petardp** [comment]
Thanks for the quick fix!
