### ISSUE TITLE
backport http/2 codec to 4.0

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3515]
I am exploring back porting codec-http2 to the ~~4.1~~ 4.0 branch.

**Comment by Scottmitch** [comment]
@trustin - Areas I see trouble are the headers, compression stuff, and some other http codec hooks.  Any guidance.  I'm of the mindset to deprecate interfaces in an effort to use more of the "newer" stuff.  Any guidance, suggestions, recommendations, or things you don't want to see?

**Comment by jpinner** [comment]
@Scottmitch mostly an FYI -- finally got around to updating the version we used internally at Twitter for 4.0 -- of note is the 'StreamedHttpMessage' interface -- https://github.com/jpinner/http2

**Comment by normanmaurer** [comment]
@Scottmitch I think you mean 4.0 ;) /cc @trustin

**Comment by Scottmitch** [comment]
@normanmaurer - Yip...typo corrected.

**Comment by leogomes** [comment]
+1 for this, but isn't 4.1 about to be released (i.e. final)?

**Comment by Scottmitch** [comment]
Just an update on this...We are currently exploring just using 4.1 to avoid the downfalls of back porting and additional maintenance overhead this will introduce.

**Comment by trustin** [comment]
+1 for 4.1. Porting to 4.0 is way too much work in my opinion.

**Comment by nmittler** [comment]
+1 for 4.1

**Comment by normanmaurer** [comment]
Ok then lets close this...

**Comment by Scottmitch** [comment]
+1 for 4.1 :)

**Comment by benmccann** [comment]
Will there be another 4.1 beta release soon? Quite eager to use the HTTP 2 stuff, but need the latest code to be released
