### ISSUE TITLE
HTTP/2 Priority Tree Management

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3518]
We are currently removing streams from the priority tree as they are closed (maybe subject to a stream removal policy which is being removed as part of https://github.com/netty/netty/issues/3448).  However we should not remove streams from the priority tree at least until they have no dependencies which are in states eligible for data transfer (i.e. OPEN, HALF_CLOSED, ...), or may be eligible for data transfer in the future (i.e. IDLE).

**Comment by Scottmitch** [comment]
@nmittler - FYI.

**Comment by Scottmitch** [comment]
We associate priority with the flow control window.  Therefore we rely on both peers sharing a common view of the priority tree.  However there seems to be some confusion (on my part or in the spec) with how to provide feedback when we don't accept a priority frame.  We can't rely upon sending a RST_STREAM to the other end because in [section 5.1](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-5.1):

> Endpoints MUST ignore
      WINDOW_UPDATE or RST_STREAM frames received in this state, though
      endpoints MAY choose to treat frames that arrive a significant
      time after sending END_STREAM as a connection error
      (Section 5.4.1) of type PROTOCOL_ERROR.

Some thought is needed (perhaps when I'm not so tired) as to how we can maintain the priority & flow control association and keep the peers in sync.

For example say stream X is closed, and it has no children.
1. We remove it from the priority tree.
2. Later our peer sends a priority frame for stream X.
What do we do:
- Should we have been keeping track of stream X's window? (it can't be controlled via WINDOW_UPDATE frames at this point)
- Should we ignore it? - What does that say about our windows throughout the tree?

**Comment by Scottmitch** [comment]
I'm working on a PR for this.  I think I was confused in my late night thought process :)  The window of the individual node doesn't particularly matter because we are considering how much the whole subtree *wants* to send, and any individual node which is not eligible to send will not contribute to this number.

**Comment by nmittler** [comment]
ignored :)

**Comment by Scottmitch** [comment]
@nmittler - Humm this didn't get auto closed like we had hoped...closing manually.

**Comment by nmittler** [comment]
@Scottmitch hmm ... maybe updates don't count and the original description has to have the "Fixes: " text?

**Comment by Scottmitch** [comment]
@nmittler I wonder if a link has to be in the git commit too?

**Comment by nmittler** [comment]
@Scottmitch ah yeah that would make sense.
