### ISSUE TITLE
4.0.10-Final: CancelledKeyException

### ISSUE THREAD

**Issue by md-5** [netty/netty#3522]
I've got a user on a legacy version reporting this error:
![3cwgkcf](https://cloud.githubusercontent.com/assets/1007849/6762375/1b54bbfc-cfb3-11e4-8a2d-3044cd82d1a4.png)

I know the version is old and it may be fixed, but I'd appreciate a look be taken. Apparently it happens to many connections to the server simultaneously.

**Comment by normanmaurer** [comment]
Yeah its fixed

**Comment by md-5** [comment]
Alright, I might try a backport.

Any idea which version it was fixed in @normanmaurer ?

**Comment by md-5** [comment]
Doesn't really matter, I've backported the 4.0.23 upgrade
