### ISSUE TITLE
HTTP/2 tiles example

### ISSUE THREAD

**Issue by leogomes** [netty/netty#3523]
I've put together a Netty version of the [gophertiles](https://http2.golang.org/gophertiles?latency=0) HTTP/2 example here: https://github.com/leogomes/http2-netty. If you think it's worth adding this to Netty's examples set, let me know and I can prepare a PR. 

Would also be nice if someone could host the example. I probably won't have time to set that up.

**Comment by trustin** [comment]
@nmittler @Scottmitch What do you think? Perhaps we could merge it into our HTTP/2 example?

**Comment by normanmaurer** [comment]
+1

**Comment by leogomes** [comment]
I've seen this morning that Akamai put on the same example to showcase HTTP/2: https://http2.akamai.com/demo

It would be nice to have one running for Netty, wouldn't it? Can't we run it on netty.io?

**Comment by trustin** [comment]
We currently rely on Github Pages to host the site, but yeah, it will be awesome if Netty serves netty.io. :-)

**Comment by ThomasLau** [comment]
cool,really impressive

**Comment by Scottmitch** [comment]
@leogomes - This seems interesting!  I agree with @trustin a good first step would be to submit a PR integrating this into our examples.  We can then look at running it on netty.io.

**Comment by leogomes** [comment]
Great, I will look into it by the end of week and will fit everything into Netty's examples. I'm a bit busy right now.

**Comment by leogomes** [comment]
@nmittler @Scottmitch I haven't had the time to dig into the specs and see if it's backward compatible, couldn't we support previous versions of the HTTP/2 spec with the current implementation? Basically, without hacking the version supported by Netty, we won't be able to run HTTP/2 examples with any current versions of Chrome or FF, except for "unstable" versions, because Chrome is currently h2-14 and FF is h2-15 (if I recall well). Having said that, they should be catching up soon. WDYT?

**Comment by trustin** [comment]
+1 for supporting only the latest HTTP/2 spec version. The browsers should catch up soon.

**Comment by normanmaurer** [comment]
@trustin @leogomes +1

**Comment by Scottmitch** [comment]
@leogomes - Don't worry about hacking the version.  The spec is in the finalization process and will be released *soon*.  I think most browsers support mostly the same features/drafts...some have been hesitant to update their draft numbers because 14 was the last "binary incompatible" version.

**Comment by leogomes** [comment]
Created PR here: https://github.com/netty/netty/pull/3620

**Comment by normanmaurer** [comment]
Was merged as part of https://github.com/netty/netty/pull/3620
