### ISSUE TITLE
SslContext construction is unwieldy

### ISSUE THREAD

**Issue by ejona86** [netty/netty#3531]
SslContext construction is very unwieldy. 18 methods with up to 12 arguments, and all but 2 on server side are optional (so lots of nulls and zeros for some usages). It is also incompatible with helper methods (e.g., with reasonable HTTP/2 defaults), unless they too are as unwieldy.

Would it make sense for it to be a builder instead? Even if we needed separate builders for client and server, it would be shorter, less noisy, and permit helpers.

**Comment by Scottmitch** [comment]
+1. SslContext is a beast that has grown to keep up with backwards compatibility.  There should be a better way :)

**Comment by trustin** [comment]
+1 :-)

**Comment by normanmaurer** [comment]
+1 ... Btw we love PRs ;)

**Comment by ejona86** [comment]
Fresh off the presses, this is the sort of Builder I was imaging: https://github.com/ejona86/grpc-java/blob/netty-tls/netty/src/main/java/io/grpc/transport/netty/SslContexts.java . Yes, I'll need to replace the Preconditions and figure out which file it seems most appropriate.

I'll make a PR for it, but it will probably be Thursday/Friday before that happens.

**Comment by ejona86** [comment]
I expect people will have opinions on whether to have two builders (one client, one server) and the overloading of keyManager/trustManager.

**Comment by Scottmitch** [comment]
@ejona86 - Care to submit this as a PR against 4.0?  It is easier to review that way.

**Comment by normanmaurer** [comment]
+1 ...

Just ensure you not break the API

**Comment by Scottmitch** [comment]
@normanmaurer - I was thinking to deprecate existing SslContext interfaces in 4.0 and 4.1.  Then perhaps get rid of it in 5.0. WDYT?

**Comment by normanmaurer** [comment]
Yep sure as long as we not break stuff in 4.x

**Comment by normanmaurer** [comment]
Fixed by #3541

**Comment by RoganDawes** [comment]
Is SslContextBuilder going to be added to 5.0? As far as I can tell, this has not yet been forward ported.
