### ISSUE TITLE
HELP! why log a warn when Channel connect failure .  version:netty-4.0.26.Final

### ISSUE THREAD

**Issue by chzhuo** [netty/netty#3533]
version:netty-4.0.26.Final 

when connect failure that not log anything in netty-4.0.25.Final.  But in netty-4.0.26.Final that will log warn "io.netty.channel.ChannelException: java.net.SocketException: Socket is closed".

I don't kown why and  how to shutdown  this warn.

![qq 20150325164907](https://cloud.githubusercontent.com/assets/10919124/6821021/3134359c-d30f-11e4-85fd-faca65fbd4ee.png)

**Comment by trustin** [comment]
I guess I have fixed this in 4.0.27.Final-SNAPSHOT. Could you try the snapshot build, @chzhuo ?

**Comment by chzhuo** [comment]
No,where is 4.0.27.Final-SNAPSHOT?   I think i need  come back to 4.0.25.Final

**Comment by trustin** [comment]
http://clinker.netty.io/jenkins/job/netty-oraclejdk7/branch/4.0/lastSuccessfulBuild/artifact/

**Comment by normanmaurer** [comment]
@chzhuo let me close this... Please re-open if you still see the issue after upgrade to 4.0.27.Final.
