### ISSUE TITLE
Java 8

### ISSUE THREAD

**Issue by WhiteTrashLord** [netty/netty#3534]
You have already plans when you will make a new Netty version which requires Java 8 or newer?
Or it's very clear that all Netty versions will work with Java 7 for the next years?

**Comment by trustin** [comment]
I'm considering to bump the minimum requirement for Netty 5 from Java 6 to Java 8. Any objections? /cc @nmittler @normanmaurer @Scottmitch

**Comment by normanmaurer** [comment]
+1

**Comment by danbev** [comment]
+1

torsdag 26 mars 2015 skrev Norman Maurer <notifications@github.com>:

**Comment by hepin1989** [comment]
+1

**Comment by WhiteTrashLord** [comment]
Let's set the minimum requirement for Netty 3 and 4 to Java 8 as well.
Fuck all the banks and insurance companies who don't like new technologies :D

**Comment by Scottmitch** [comment]
@trustin - +1.  We may want to discus usages of Lambdas and other functional programming or address these in the style guide.

**Comment by doom369** [comment]
Have in mind that lamdas may have some performance impact depending on you use it. See for instance http://www.oracle.com/technetwork/java/jvmls2013kuksen-2014088.pdf

**Comment by grossjonas** [comment]
+1

**Comment by benmccann** [comment]
+1 at least drop Java 6

**Comment by tea-dragon** [comment]
+1 -- put those new unsafe methods to work

**Comment by ganskef** [comment]
-1 Sorry, what's about Android? Is RoboVM a solution here?

**Comment by slandelle** [comment]
@ganskef IMHO, Android devs should be using libraries tailored for their needs (ie platform fragmentation). Android's Java is already different from standard one. E.g., I was horrified to discover that Android's "JDK7" purposefully didn't introduce/removed `SSLParameter.setEndpointIdentificationAlgorithm`. 

+1 for targeting JDK8

**Comment by normanmaurer** [comment]
For Android you will need to stay on 4.1 or lower

**Comment by ganskef** [comment]
Ok, I would like the shiny new Java features, too - and I'm failed to 
use SSL with Netty on Android - and I would like to use Lucene (depends 
on JDK8) instead of SQLite FTS via JNI - and I would like to support 
Android and iOS devices. RoboVM seems to provide a JDK8 to do so. The 
core is open-source.

Am 29.04.2015 um 17:27 schrieb Stephane Landelle:

**Comment by ganskef** [comment]
Sorry, I had a closer look. RoboVM is based on Android code base, not OpenJDK 8 und Lucene depends on JDK7 (but therefore I've used sqlite4java).

**Comment by rzorzorzo** [comment]
@normanmaurer  there are quite some java 5/6 and android projects using netty out there. Requiring us to stay with 4.1 is ok. The question is, how long dwill 4.1 be maintained/supported  ?

**Comment by flirtomania** [comment]
-1 We use Netty 5 on Android
Most of interfaces supposed to be implemented by client I've seen are not single-method interfaces.

**Comment by dmk23** [comment]
Netty 5 aside, is Netty 4.x fully tested/ready for JDK 8?

**Comment by normanmaurer** [comment]
Yes you can use netty 4.x with java8

**Comment by slachiewicz** [comment]
So for Netty 4.0/4.1 we will stay at minimum java 6 and for Netty 5.0 will be Java 8 ?

**Comment by normanmaurer** [comment]
That is the idea atm

**Comment by sczerwinski** [comment]
−1
Android is still mostly Java 6.

**Comment by guidomedina** [comment]
Why not make 4.1 Java 7? That way you gradually go through all relevant JDKs

**Comment by guidomedina** [comment]
And IMHO it is easy for projects and will be required to move to at least JDK due to lack of support from Oracle for anything less than JDK 7

**Comment by slandelle** [comment]
@guidomedina Appart from possible usage in companies that employ the Netty core developers, the only reason I can see is Android.

**Comment by guidomedina** [comment]
I mean, I'm using Java 8 and haven't seen any problem so far, but jumping from JDK 6 to 8 might be culture breaking for some companies and contributors (I don't mind TBH)

And style will change from JDK 6 to 7, also performance, just replacing JDK 6 with 7 is do-able without any hassle as far as my experience goes, I have migrated a couple of projects that have lots of legacy code from 6 to 7.

If you jump to lamdbas now you will have to deal with closure issues you might not easily detect; going through JDK 7 will not only help but also give time to developers to get more experienced with Java 8.

**Comment by ttashi** [comment]
Hey Guys I am seeing a lot more gc activity with ning-async client 1.7.19 thats using netty 3.6.6.Final after upgrading to JDK 8 from 7. Do any of you guys have thought on this. It happens mostly on larger responses.

**Comment by slandelle** [comment]
@ttashi (disclaimer: I'm the AHC dev) Latest AHC1 is 1.9.33, you REALLY should upgrade. Then, if you have questions on AHC, please ask on [our mailing list](https://groups.google.com/forum/#!forum/asynchttpclient).

**Comment by albertvaka** [comment]
Is there any need to jump to Java 8 (ie: better performance, obvious way to improve the code...)? It will mean that Android developers won't be able to update to Netty 5, so unless there is an urge to change I honestly believe it's better to stick to Java 7 for now.

**Comment by slandelle** [comment]
@albertvaka As the developper of a Netty based HTTP client (AsyncHttpClient), I'd be very curious to know what Android developers would use Netty for? Specific protocol clients?

On AsyncHttpClient, I barely had any Android users, so I finally made the move of dropping JDK6, then JDK7 support. With JDK8, I can use things like ConcurrentHashMap#computeIfAbsent.

IMHO, Android is a different beast than standard Java, both in terms of:
* API (eg Java 7 like Android SDK misses some APIs, such as [SSLParameters.html#setEndpointIdentificationAlgorithm](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLParameters.html#setEndpointIdentificationAlgorithm(java.lang.String)));
* concerns: on Android, you want lightweight, not low latency and super high throughput

It looks to me that OkHttp, which is tailor made for Android by the Square people, is a more natural fit in this space than Netty.

My opinion would be: drop Android, JDK 6 and 7 support, and focus on where Netty shines: on the server side.

**Comment by albertvaka** [comment]
I'm using Netty to have an abstract, event-based API on top of SSL sockets (on Android). Because, at least as of now, the project tagline is "an event-driven asynchronous network application framework" and not "Netty shines on the server side".

Jokes aside, there are bug reports in this same issue tracker from Android users, and even comments on this thread, so there is definitely a percentage of people using Netty on Android.

And again my question is: is there any need(/good reason) to adopt Java 8?

**Comment by slandelle** [comment]
The ones I see:
* `AbstractChannelPoolMap` and `DefaultDnsCache` would benefit from `computeIfAbsent`
* Client side HTTPS security could be enabled by default with SSLParameters.html#setEndpointIdentificationAlgorithm, see #4929
* Less need for hacks and fallbacks in `PlateformDependent`. For example, Netty currently has to ship a fork on JSR166. And I wonder how much extra pain Java 9 support will bring here, with the `sun.misc.Unsafe` changes.
* Less hard work for the Netty core devs to fix Android specific issues

**Comment by bogdanRada** [comment]
any updates on this? I am struggling with SSLParameters.html#setEndpointIdentificationAlgorithm which is missing on Java 8 . Would appreciate any help with this. Thank you

**Comment by Scottmitch** [comment]
No update. We haven't discussed any concrete plans for Netty 5 (in general). Also no concrete plans of changing the existing JDK support for Netty 4.

**Comment by bogdanRada** [comment]
I feel sad  :(  I managed to fix my issue....i was using scribejava for Oauth2 ...and their http client ( which is based on this library)  is working well for Android API Level >= 23, but for lower levels it had that issue with SSLParameters.html#setEndpointIdentificationAlgorithm which is missing, so i ended up  writing my own client which implements their interface HttpClient , and using a different library and then converting the response from my library back to their original Http client response in order to be able to convert this response into objects. 

Ugly hack but that did the trick.  Thank you though for your support. If there is something i could help , let me know. Have a nice day.

**Comment by songxin1990** [comment]
Ask a question,which version Netty will support lambda expression?

**Comment by Scottmitch** [comment]
You are free to use lambda expressions in your application if you use jdk8+, however in the Netty code base we are stuck supporting jdk6+.

**Comment by normanmaurer** [comment]
Netty 5 will be
