### ISSUE TITLE
HTTP/2 write interface clarifications

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3536]
We should investigate clarifying the interfaces that have `writeXXX` in the name with respect to the return status they provide.  For example some `writeXXX` methods (i.e. `Http2ConnectionHandler`) return "success" even if nothing is actually written.  Should we clarify the interfaces to indicate the return status behavior.  I can think of a few approaches:

1. Do nothing...they are fine as is.
2. Clarify in comments the expected behavior of the return values (or the ChannelPromise which serves as the return value).
3. Change the method names so they don't have `write` in the name.
4. Both 2 and 3.

This issue is carried over from discussion in https://github.com/netty/netty/pull/3528#issuecomment-85771057.

**Comment by Scottmitch** [comment]
@nmittler @buchgr - FYI.

**Comment by nmittler** [comment]
@Scottmitch What are your thoughts on how to rename the methods?

**Comment by Scottmitch** [comment]
@nmittler - I think the `writeXXX` terminology make sense for the `Http2FrameWriter`.  The `Http2FrameWriter` interface is at the level where it is directly writing, and the return status indicates the results of that write operation.  However interfaces that sit on top of `Http2FrameWriter` and provide conditional logic above and beyond the write operation are a bit less clear as to what their return status indicates.  Even the [DefaultHttp2ConnectionEncoder](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionEncoder.java) does some state checking but mostly remains consistent with the `Http2FrameWriter`'s definition of `writeXXX` (for example [DefaultHttp2ConnectionEncoder](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionEncoder.java#L259) even fails the promise when no write is done).

I think we need to reevaluate the 
[Http2LifecycleManager.writeGoAway](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2LifecycleManager.java#L66) and [Http2LifecycleManager.writeRstStream](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2LifecycleManager.java#L59) interface or [Http2ConnectionHandler](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L531)'s implementation of this interface which seems not to follow the same paradigm.  I'm still not 100% clear why these methods should be deviating from the typical meaning of `writeXXX`.  However if they must deviate perhaps a name change of `doXXX` or something more general (in addition to comments) may be less likely to mislead users of the API.

**Comment by nmittler** [comment]
@Scottmitch +1.  Maybe we could rename `Http2LifeCycleManager.writeRstStream` to `resetStream` and `writeGoAway` to something like `shutdown` or `close`?

I agree that the encoder names should probably change as well although I don't think it will be as simple to select a good name.  Probably needs more thought.

**Comment by Scottmitch** [comment]
@nmittler I like your suggestion for the lifecycle manager.

I will investigate more tomorrow but the encoder methods may not have to be renamed if they are upholding the 'writeXXX' interface contract. I took a quick look and most encoder write methods (besides life cycle related ones perhaps) seem to be upholding the return status indicates if and when a write is done. Do you see any problems with this?

**Comment by nmittler** [comment]
@Scottmitch I'm fine with leaving the encoder as-is

**Comment by Scottmitch** [comment]
PR is pending for this...

**Comment by Scottmitch** [comment]
PR https://github.com/netty/netty/pull/3580 addressed this.
