### ISSUE TITLE
Cookie should probably use AsciiString

### ISSUE THREAD

**Issue by timboudreau** [netty/netty#3538]
Updating Acteur for Netty 5, AsciiString is now heavily used.  However, Cookie and related classes still use String - it would be more intuitive for this to be consistent.

**Comment by Scottmitch** [comment]
Sounds like a good idea.  Would you be interested in submitting a PR?

**Comment by Sammers21** [comment]
Any updates here?

**Comment by slandelle** [comment]
1) API breaking
2) would be worth having a benchmark with AsciiString vs Java 9's new String implementation

**Comment by Sammers21** [comment]
@slandelle could you point me out about benchmarks?

**Comment by slandelle** [comment]
I don't think there's any benchmark yet.

**Comment by Sammers21** [comment]
I mean that I could work on that so i'd like to create them. Could you point me out what they should to compare

**Comment by normanmaurer** [comment]
@chrisvest did rework the `cookie` APIs. Lets close this
