### ISSUE TITLE
Why it slow? final Channel c = b.connect().sync().channel();

### ISSUE THREAD

**Issue by junjiemars** [netty/netty#3540]
Why my code slow, I wrote tiny app [NHttpClient](https://github.com/junjiemars/NHttpClient)
The env: ```Linux K27 3.2.0-69-generic-pae #103-Ubuntu SMP Tue Sep 2 05:15:53 UTC 2014 i686 i686 i686 GNU/Linux```

run it with ``` java -jar build/libs/NHttpClient-1.0.jar -p -d"Hello" -uhttp://cn.bing.com```
```
real    0m9.769s
user    0m2.000s
sys     0m0.128s
```

Blocked at ```final Channel c = b.connect().sync().channel();```
```
    private static boolean request(final URI uri,
                                   final FullHttpRequest requested,
                                   final PipelineBuilder pipelined) {
        final EventLoopGroup group = new NioEventLoopGroup();
        try {
            final Bootstrap b = new Bootstrap()
                    .remoteAddress(uri.getHost(), (-1 == uri.getPort() ? 80 : uri.getPort()))
                    .option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
                    .group(group)
                    .channel(NioSocketChannel.class)
                    .handler(new ChannelInitializer<NioSocketChannel>() {
                        @Override
                        protected void initChannel(NioSocketChannel ch) throws Exception {
                            pipelined.build(ch.pipeline());
                        }
                    });

            final Channel c = b.connect().sync().channel();
            c.writeAndFlush(requested);
            c.closeFuture().sync();

            return (true);
        } catch (final Exception e) {
            _l.error(e);
        } finally {
            group.shutdownGracefully();
        }

        return (false);
    }
```

**Comment by Scottmitch** [comment]
@junjiemars - Thanks for reaching out for help!  This github repository is primarily to report issues and feature requests.  If you would like support on using netty please use stackoverflow.com.  Other users  of netty may have the same questions as you and it is more likely they will find it on stackoverflow.  For this instance feel free to post a link to your question on stackoverflow but for future instances please go directly to stackoverflow.

**Comment by junjiemars** [comment]
@Scottmitch ok, thanks
