### ISSUE TITLE
3.9: AbstractNioChannel.WriteRequestQueue fires INTEREST_OPS event from wrong thread

### ISSUE THREAD

**Issue by huguesb** [netty/netty#3546]
My understanding is that for NIO socket channels all upstream events should be fired from the io thread.

However it appears that `WriteRequestQueue.poll()` and `WriteRequestQueue.offer()` are both called from arbitrary threads and proceed to call `fireChannelInterestChanged` instead of checking `isIoThread` and calling `fireChannelInterestChangedLater` accordingly.

This causes race conditions in a proxy server where writability change on one channel are used to adjust readability of another channel.

  - thread 1 (io thread of channel 1) : channel 1 writable
        -> mark channel 2 readable -> runnable enqueued on thread 2
  - thread 2 (io thread of channel 2) : channel 1 not writable
        -> mark channel 2 not readable -> change executed immediately
  - thread 2 : execute runnable enqueued from thread 1

Result: channel 2 readability is the inverse of what it should have been if INTEREST_OPS event where always propagated upstream on the channel's io thread, as the documentation suggests they should.

**Comment by normanmaurer** [comment]
Fixed in 3.10 branch
