### ISSUE TITLE
Cannot subclass HttpHeaders and build with JDK 7 with maven build of 4.0.26.Final

### ISSUE THREAD

**Issue by timboudreau** [netty/netty#3548]
It seems the build of Netty 4.0.26.Final from Maven is built with JDK 8, which adds default methods to collections classes that reference classes that don't exist in JDK 7.  That's binary compatible, but not source compatible, as follows:

I am stuck with JDK 7 for a while longer (thanks @schue ) for Actuer.  As of Netty 4.0.26.Final my [build is broken](http://timboudreau.com/builds/job/mastfrog-parent/703/console) because javac sees `spliterator` methods and classes in `HttpHeaders`.  To fix it I'm staying with Netty 4.0.25 for now for Acteur, but that's not a long-term solution.

Since AFAIK, Netty 4 is buildable on JDK 7, is it possible for JARs released to Maven Central also to be built with JDK 7?

I imagine I am not the only one in this situation.

**Comment by Scottmitch** [comment]
@timboudreau - Thanks for reporting!

@normanmaurer - Building the releases from jdk7 sounds reasonable...WDYT?

**Comment by trustin** [comment]
Sounds good to me. See the `restricted-release` profile to enforce JDK version when a release is made.

**Comment by trustin** [comment]
Should be fixed on 0222f412336f87909ff71494e5af8e2b221945da (4.0) and bdf0bddc8544666ce73b0e7e486ddccf214e79ef (4.1)

**Comment by trustin** [comment]
Should be fixed on 0222f412336f87909ff71494e5af8e2b221945da (4.0) and bdf0bddc8544666ce73b0e7e486ddccf214e79ef (4.1)

**Comment by normanmaurer** [comment]
@timboudreau @trustin I will revert this one as it seems like it was fixed in java some time ago
