### ISSUE TITLE
Avoid copying in DefaultHttp2RemoteFlowController

### ISSUE THREAD

**Issue by nmittler** [netty/netty#3550]
We should identify all of the places in the flow controller that we're copying and try to eliminate/reduce the total amount of copying for each call to ~~`writePendingStreams`~~ `writePendingBytes`.

**Comment by Scottmitch** [comment]
@nmittler - Thanks for filing this!

**Comment by Scottmitch** [comment]
I'll take a stab at this after https://github.com/netty/netty/pull/3549 is pulled in.

**Comment by Scottmitch** [comment]
We should also investigate if maintaining a separate collection for the streams that have bytes allocated is worth it.  For example if the number of streams that have bytes allocated is small relative to the total number of active stream it may be beneficial to maintain a separate set that tracks which streams have allocations.

**Comment by nmittler** [comment]
+1

**Comment by nmittler** [comment]
@Scottmitch were you going to look into this or shall I?

**Comment by Scottmitch** [comment]
@nmittler - I updated the issue description to `writePendingBytes`.  I have a PR pending approval which avoids the copy operation and also prevents concurrent modification.  Stay tuned :)

**Comment by Scottmitch** [comment]
@nmittler - I have not investigated if creating a separate collection which includes only the nodes that need writing is beneficial...but lets handle that after we avoid the copy.

**Comment by nmittler** [comment]
@Scottmitch sgtm, thanks!

**Comment by Scottmitch** [comment]
Closing.  Should be covered by https://github.com/netty/netty/pull/3577.

**Comment by nmittler** [comment]
@Scottmitch there is still [this copy](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2RemoteFlowController.java#L280) that we may want to think about. If we decide it's necessary, that's fine.

**Comment by Scottmitch** [comment]
@nmittler +1.  I thought about that briefly....now that we are not sorting it may be more feasible to remove.  The only hangup is how we are using this array to "re-visit" children that still want to send....we could maintain an alternative collection for this type of thing....but may make the loop a bit more complicated to handover to a secondary collection after the first iteration....WDYT?

**Comment by nmittler** [comment]
@Scottmitch Yeah I was thinking something similar ... let me take a crack at this.

**Comment by nmittler** [comment]
Remaining copy resolved by #3603.
