### ISSUE TITLE
JVM crashes when closing server.

### ISSUE THREAD

**Issue by doom369** [netty/netty#3551]
I have a shutdown hook on which I try to close netty server and sometimes during close() I'm getting JVM crashes.
```
J 175 C1 java.lang.ClassLoader.loadClass(Ljava/lang/String;)Ljava/lang/Class; (7 bytes) @ 0x00007f5f65159fc4 [0x00007f5f65159ec0+0x104]
v  ~StubRoutines::call_stub
j  io.netty.channel.AbstractChannelHandlerContext.close(Lio/netty/channel/ChannelPromise;)Lio/netty/channel/ChannelFuture;+39
j  io.netty.channel.AbstractChannelHandlerContext.close()Lio/netty/channel/ChannelFuture;+5
j  io.netty.channel.DefaultChannelPipeline.close()Lio/netty/channel/ChannelFuture;+4
j  io.netty.channel.AbstractChannel.close()Lio/netty/channel/ChannelFuture;+4
j  cc.blynk.server.core.BaseServer.stop()V+11
```

Here is full crash log : https://www.dropbox.com/s/u47fzlnk2mj861n/hs_err_pid38261.log?dl=0
Close method : https://github.com/blynkkk/blynk-server/blob/master/server/tcp-server/src/main/java/cc/blynk/server/core/BaseServer.java#L63

Netty version - 4.0.26.Final

**Comment by normanmaurer** [comment]
@doom369 looks like a jdk bug... Can you try to upgrade your jdk version ?

**Comment by doom369** [comment]
@normanmaurer It a latest one =). 1.8.0_40.

**Comment by normanmaurer** [comment]
@doom369 then I think your best bet is to open a openjdk bug-report :/

**Comment by doom369** [comment]
@normanmaurer look like you are right. Found exactly same issue https://bugs.openjdk.java.net/browse/JDK-8013062.
