### ISSUE TITLE
PoolThreadCache memory consumption ?

### ISSUE THREAD

**Issue by bwzhang2011** [netty/netty#3552]
When I dumped the process of the project in my production env, with the help of eclipse memory analyzer, I got some report as follows
![image](https://cloud.githubusercontent.com/assets/749788/6891384/295bc7e0-d6ed-11e4-988b-ec442921cc9c.png)

by the way, the ByteBufAllocator implementation is PartialPooledByteBufAllocator derived from vert.x written by normanmaurer. for the report, I've got to know that the poolthreadcache reached about 116.6m size in my project. 

here comes my question, how to analysis the report to define whether there is memory leak and how to optimize that.

**Comment by trustin** [comment]
It doesn't look like a leak from a glance. You might want to specify the following system properties when you launch a JVM:

* io.netty.allocator.tinyCacheSize (default: 512)
* io.netty.allocator.smallCacheSize (default: 256)
* io.netty.allocator.normalCacheSize (default: 64)
* io.netty.allocator.maxCachedBufferCapacity (default: 32768)

At worst case, you will have 64 32K thread-local buffers per thread, which is about 50 MB. I'm not sure why it's double of that though. I can investigate further if you share your heap dump.

**Comment by bwzhang2011** [comment]
@trustin, thanks for view. for the buffer setting, I just set sndbuffer to 64k while the recev buffer is 32k  for ChannelOption configuration (I don't know whether it was the reason for that). here comes the dump file if it does not matter about its size. please pay a visit to such link: http://yun.baidu.com/share/link?shareid=1946887138&uk=1631968089&third=15 (I just upload the file to baidu  yun)

**Comment by bwzhang2011** [comment]
@trustin , how does this going on ? I've got to know that @normanmaurer has done something to enhance the process for that. hope the master branch could be merged into that for support.

**Comment by normanmaurer** [comment]
@bwzhang2011 my changes have nothing to do with this...

**Comment by bwzhang2011** [comment]
@normanmaurer , would you mind leaving me more message for that or pointed out if I were wrong with my configuration, now I just set the buffer to the same size either 32k or 64k, I wonder whether the poolThreadCache would lead to memory leak and how. as only poolthreadcache occupied more heap.

**Comment by bwzhang2011** [comment]
@trustin, any update with such issue. I will be going to close it as you pointed out it's not the case.as we care about the memory use cases and @normanmaurer did some enhancement for poolthreadcache so once it's merged into the master, it should be closed.

**Comment by bwzhang2011** [comment]
@trustin, any update with such issue. I will be going to close it as you pointed out it's not the case.as we care about the memory use cases and @normanmaurer did some enhancement for poolthreadcache so once it's merged into the master, it should be closed.
