### ISSUE TITLE
Channel writability change notification failed to fire

### ISSUE THREAD

**Issue by cloudbow** [netty/netty#3565]
Although there is a similar issue I am able to reproduce this in 4.1.0-Beta code base. I was waiting for the channel writability and never got back a notification.

**Comment by normanmaurer** [comment]
@arungeorge81 can you share a reproducer ?

**Comment by arungeorge81** [comment]
I am in the process of opensourcing my netty library for APNS/GCM/ADM as a single platform. I currently fixed it by having a timeout in my code -  codVar.await(1,TimeUnit.SECONDS). I will share you both a dummy server and a client where we can reproduce it.

**Comment by normanmaurer** [comment]
@arungeorge81 thanks.. just let me know once you did.

**Comment by Scottmitch** [comment]
@cloudbow - Have you stopped seeing this issue, and were you able to find a root cause?

**Comment by trustin** [comment]
Please reopen when more information is available.
