### ISSUE TITLE
Excessively large cumulation ByteBuf in SslHandler

### ISSUE THREAD

**Issue by dkartaschew** [netty/netty#3567]
Hi,

Upon upgrading from netty 4.0.23 to netty 4.0.26, we've found that during large/fast data transfers via TLS 1.2, the "cumulation" ByteBuf in the SslHandler grows to over 1GB in direct buffer usage, leading to OOM errors. The growth of the "cumulation" ByteBuf does appear to correspond with the amount of data received.

This growth occurs only the receiving side, irrespective of which side initiated the connection.

Testing with netty 4.0.23 and 4.0.24 shows the buffer never/rarely grows, but starting with 4.0.25 the growth is seen. We've tested with Oracle JRE 7u67 and 8u31 with the same result. 

The channel pipeline setup is:
```java
ChannelPipeline p = ch.pipeline();
if(engine != null){
  p.addLast("ssl", new SslHandler(engine));
}
p.addLast("frameDecoder", new ProtobufVarint32FrameDecoder());
p.addLast("protobufDecoder", new ProtobufDecoder(ApplicationProtos.getDefaultInstance()));
p.addLast("frameEncoder", new ProtobufVarint32LengthFieldPrepender());
p.addLast("protobufEncoder", new ProtobufEncoder());
p.addLast("handler", handler);
```
This may be related to bugs #3559 and #3447 , but ultimately unsure. Removing the SslHandler does improve things in our instance, but suspect that is due to the pipeline setup. 

If there is any more information required, please let me know.

**Comment by trustin** [comment]
Thanks for reporting. I guess there might be some edge case we didn't handle correctly. Would you mind if I ask to share the heap dump with us?

**Comment by trustin** [comment]
Alternatively, you could just share the readerIndex and writerIndex of the cumulative buffer.

**Comment by dkartaschew** [comment]
Hi Trustin,

I've attached a screen shot from a heap dump using netty 4.0.25 and 4.0.26 showing the effect, a screenshot of the direct buffer usage from jvisualvm.

![netty_4 0 25](https://cloud.githubusercontent.com/assets/2052368/6957753/fd35d2ce-d943-11e4-9882-3f20ad028fe0.png)
![netty_4 0 26](https://cloud.githubusercontent.com/assets/2052368/6957755/083fe27c-d944-11e4-8281-702e8cdc6649.png)
![jvisualvm](https://cloud.githubusercontent.com/assets/2052368/6957751/f373d8f8-d943-11e4-94fa-633235fc66ef.png)

**Comment by trustin** [comment]
@dkartaschew Thanks! It seems like the reader/writerIndex of the cumulative buffer is: 556527170/556581723, which seems way too large.

**Comment by trustin** [comment]
@dkartaschew Could you tell me which `SSLEngine` implementation you are using? (OpenSslEngine vs the one from JDK)

**Comment by trustin** [comment]
@dkartaschew I'm also interested in the vaule of the `SslHandler.first` (boolean)

**Comment by trustin** [comment]
Should be fixed now: 4d8f824 (4.0), 2e509f7 (4.1), cdd2e1c8c1d42b596652a7030213b9084a12fc15 (master)

**Comment by trustin** [comment]
Perhaps we should make the handler method implementations in `ByteToMessageDecoder` final and provide protected hook methods. What do you think, @normanmaurer?

**Comment by trustin** [comment]
@dkartaschew Please feel free to reopen this issue if you still observe the problem with the SNAPSHOT build.

**Comment by normanmaurer** [comment]
@trustin ouch.... We should aim for release 4.0.27.Final very soon.

About your question: I agree we should probably do this but this is a breaking change so we will need to do it in master only.

**Comment by fredericBregier** [comment]
@normanmaurer Do you mind to release "exceptionnaly" 4.1 too ?

**Comment by dkartaschew** [comment]
@trustin, we're using the JRE's SSLEngine as the OpenSSL implementation isn't feature complete for our needs (#3005 and #3220).

And `SslHandler.first` is `false` in all cases we observed this issue.

**Comment by svnp10** [comment]
Hi, I find this issue 4.1.4.Final and 4.1.6.Final as well...

**Comment by normanmaurer** [comment]
@svnp10 please open a new issue and provide more infos

**Comment by svnp10** [comment]
@normanmaurer issue here #5928
