### ISSUE TITLE
UnsupportedOperationException of some examples when using ssl

### ISSUE THREAD

**Issue by lime62** [netty/netty#3568]
Some client examples don't specify ssl provider when initializing SslContext. 
And the default ssl provider is openssl if OpenSsl is available. 
So, those clients have UnsupportedOperationException when adding ssl handler because OpenSslContext.newEngine() throws it.

WDYT?

**Comment by Scottmitch** [comment]
@lime62 - What commit are you on?

**Comment by lime62** [comment]
@Scottmitch I'm on cdd2e1c8c1d42b596652a7030213b9084a12fc15.

**Comment by normanmaurer** [comment]
@lime62 this should be fixed now
