### ISSUE TITLE
More complete native collection support

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3569]
We have some support for primitive type collection via https://github.com/netty/netty/tree/master/common/src/main/java/io/netty/util/collection.  However it would be nice to have more complete support for the primitive collections.  This would allow a reduction in memory requirements and provide the opportunity to avoid boxing/unboxing.

**Comment by Scottmitch** [comment]
@nmittler - I assigned you to this and put it at 4.1.0.Beta5 for now.  Feel free to change.

**Comment by Scottmitch** [comment]
Just a reminder that we should fix the types being exposed by HTTP/2 settings object to be inline with the specification after this is resolved. See https://github.com/netty/netty/pull/3563#issuecomment-88664968.

**Comment by normanmaurer** [comment]
@Scottmitch @nmittler if this is only for http2 and not the core of netty we may also could just depend on something and so not need to maintain it. Just saying....

**Comment by Scottmitch** [comment]
@normanmaurer - I think HTTP/2 will take advantage of it...but it is generic enough that other codecs (and users of netty potentially) should be able to take advantage.

**Comment by nmittler** [comment]
@normanmaurer it's in the common module.  See #3576

**Comment by nmittler** [comment]
Fixed by #3576
