### ISSUE TITLE
Http/2 DefaultFrameWriter allocation reduction 

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3585]
The DefaultHttp2FrameWriter currently allocates a buffer for most frame types. There may be an opportunity to allocate the buffers ahead of time in ThreadLocal variables (as un releasable buffers) to avoid repeatedly allocating and releasing these buffers. We should investigate if this may provide memory allocation and/or performance benefits.

**Comment by Scottmitch** [comment]
@nmittler @buchgr WDYT? I can pull together a PR if we think this makes sense.

**Comment by buchgr** [comment]
@Scottmitch Could you point to the places in the framewriter? Why thread local?

**Comment by nmittler** [comment]
@Scottmitch definitely worth investigating.  I'm curious how much thread affinity we'll have when we have a lot of connections using the same `EventLoopGroup`.

**Comment by Scottmitch** [comment]
@buchgr - For example all/most of the frame types do:

1. Allocate small fixed size buffer for headers
2. Populate headers buffer
3. Write headers buffer.
4. (Dependent on frame type) write payload.
5. (Dependent on frame type) write padding.

See https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameWriter.java#L136 for the headers allocation.

It doesn't have to be thread local but the idea being we may be able to pre-allocate these header buffers and just populate & write (step 2 and 3) when needed.  Thread local would just be to get isolation from each thread that may be using this class.

**Comment by buchgr** [comment]
@Scottmitch 

I am pretty sure that I am missing something, so please be patient :P ... I don't see it. If you reuse the same buffer for the frame header, how can you handle multiple calls to `writeData(...)`?

**Comment by Scottmitch** [comment]
@buchgr - If the access pattern is such that `multiple calls to writeData(...)` are each on different threads then the thread local variable for that frame type can be used (if the same thread will not call `writeData` concurrently).  So we would pre-allocate and reserve (practically not-release) 1 buffer for each frame type , for each thread to use across all `DefaultHttp2FrameWriter` instances.  The idea being that we don't have to slam the buffer pool with events (allocate/release) at the expense of reserving some of the pool...because we know this will happen very frequently.

**Comment by buchgr** [comment]
@Scottmitch 

Let's forget about threads for a second. How would you handle two consecutive calls to `frameWriter.writeData(...)`?

```java
    frameWriter.writeData(...);
        FIXED_BUFFER.setBytes(...);
        ctx.write(FIXED_BUFFER);
    frameWriter.writeData(...);
        FIXED_BUFFER.setBytes(...);
        ctx.write(FIXED_BUFFER);
```

You can't overwrite the `FIXED_BUFFER` in the second call until the first write is complete.

**Comment by Scottmitch** [comment]
@buchgr +1. Needing to add listeners to know when we can re-use buffers would make pre-allocating a bit impractical....lets forget that this happened :)
