### ISSUE TITLE
HTTPProxyHandler Keep-alive

### ISSUE THREAD

**Issue by rhart** [netty/netty#3586]
Netty version: 4.1.0.Beta4

I think there is a bug with `io.netty.handler.proxy.HttpProxyHandler`. When the CONNECT request is sent to the proxy server, `HTTPProxyHandler#newInitialMessage`, it is sent as HTTP 1.0 without a Connection: Keep-alive request header. Then, when any pending writes are subsequently sent you get a Connection reset by peer because the connection has been closed by the server.

So, I think either the protocol needs to be changed to HTTP 1.1 or the request header needs to be added.

**Comment by normanmaurer** [comment]
@trustin can you check ?

**Comment by windie** [comment]
Fixed by #5437
