### ISSUE TITLE
4.1.0-Beta4: Regression in HttpRequestDecoder

### ISSUE THREAD

**Issue by huguesb** [netty/netty#3587]
We recently noticed that one of our Netty services was intermittently ignoring requests, causing the caller to timeout. Adding LoggingHandlers all over the place revealed that the failing request was received but never made it out of HttpRequestDecoder.

The connection is reused by the client and saw multiple similar requests before the server somehow choked on the last one. The server uses autoRead=false in case that is relevant.

We promptly reverted to 4.1.0-Beta3 and this failure mode completely disappeared. A quick look at the commit log between the two tags show a significant refactor of HttpRequestDecoder and some more subtle changes to ByteToMessageDecoder which are probably responsible for the regression.

**Comment by normanmaurer** [comment]
Can you share a reproducer?

**Comment by huguesb** [comment]
I wish I could but extracting a small reproducer from our codebase would take a lot of work and that's not a worthwhile time investment at this point since 4.1.0-Beta3 works for us.

However if you can provide a diff to add extra verbose logging I'd be happy to run the full reproducer with that and report the results here.

**Comment by huguesb** [comment]
@normanmaurer I went ahead and added the logging myself and I zeroed in on the issue.

 1. The channel is set to autoRead=false.
 2. upstream handler calls read()
 3. a fragmented HTTP request is received (in this case the packet is fragmented before the last \n separating headers and content).
 4. HttpObjectDecoder doesn't fire any channelRead because decoding isn't complete
 5. HttpObjectDecoder fires channelReadComplete but
    - invokedNextChannelRead is false because no channelRead was fired hence the channelReadComplete is not propagated up the pipeline
    - invokedPrevRead is *always false* because read() is propagated on the *outbound* context and HttpObjectDecoder is on the inbound *context* hence read() is not propagated down the pipeline
 5. STALL

Possible fixes I can think of:
 - make ByteToMessageDecoder a duplex handler to ensure invokePrevRead is set correctly
 - in ByteToMessageEncoder.channelReadComplete() when autoRead is false and no channelRead() was fired, call read() instead of firing channelReadComplete()
 - always propagate channelReadComplete() upstream for non-duplex handlers when autoRead is false

I'm not familiar enough with the 4.1 branch so I'll refrain from submitting a PR until someone more knowledgeable pick the best solution.

**Comment by huguesb** [comment]
The more I think about it the more convinced I become that the correct solution would be to move read() to ChannelInboundHandler and propagate it down the *inbound* context (as opposed to down the *outbound* context as is currently the case)

Similarly I think it would make more sense for channelWritabilityChanged() to be moved to ChannelOutboundHandler and propagated up the *outbound* context.

Rationale: read() modulates channelRead() and channelWritabilityChanged() similarly modulates write()
so it makes sense for each of these pairs to be in the same interface.

However it's probably too drastic an API change to be integrated in 4.1 at this time. Maybe 5.0 then?

**Comment by trustin** [comment]
Related: #3529

**Comment by trustin** [comment]
In 5, a handler always have handler methods for both directions. We are discussing about reworking the internal behavior we introduced to fix this in a better way.  See #3529

**Comment by normanmaurer** [comment]
Fixed by:

2e1325aa9de21b7fd10f2ac56b49fd5a3bbaa189
f35158f40206c8fa22ec30cf581216184314fb35
76dcda8259d60a822a2617cab6ebdd4e12d3fcb5
b35f2b4cb4dd82a174c64c3d38486cb0b33c8c18
3b1bf6348a563ecc23ccd4f1b651141f33fff1a9
5cd541c537bbf5f3faa6cf2dbceac5f1e4d75af9
