### ISSUE TITLE
ChannelInboundMessageHandlerAdapter cannot be resolved to a type

### ISSUE THREAD

**Issue by manee1982** [netty/netty#3589]
I am just trying to apply the web socket example, this error appears:

<code>ChannelInboundMessageHandlerAdapter cannot be resolved to a type</code>

i am new to netty i successfully add netty to class-path, i use eclipse.

**Comment by normanmaurer** [comment]
@manee1982 where you have the example from ? This class does not exists since 4.0.0.Final was released for sure
