### ISSUE TITLE
HTTP/2 associating state with streams

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3596]
Use cases currently exist within the codec (compression, decompression, http translation) which need to associate state with streams.  These use cases are not part of the core HTTP/2 functionality, and thus may not make sense to bake into HTTP/2 interfaces.  It is also assumed that users will have similar use cases where they will also need to associate state with streams.  `Http2Stream` currently supports a [generic map like interface](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2Stream.java#L106) to support this use case.

Questions:
- Is the existing interface sufficient?
- Is the existing implementation adequate?

Desired Properties:
- Low memory overhead if features are not in use
- Performant to update and retrieve state
- Flexible API to store arbitrary type of properties
- Minimal (zero) coordination required between codec and user space to maintain this state.

Do we support clean up of properties when streams close...or just let everyone add a connection listener and do it them selves?

**Comment by buchgr** [comment]
Just so that we don't forget, this has also been discussed in #3570 and 
#3593.

**Comment by nmittler** [comment]
+1 thanks for opening this, @Scottmitch!

**Comment by Scottmitch** [comment]
@nmittler - I'll take the assignment for now just so we don't lose track....feel free to re-assign (your PR is likely a good start) if you want.

**Comment by buchgr** [comment]
I did some thinking on this issue today and after having seen a few approaches (#3602, #3616, #3593), I came to the conclusion that we will likely not find a "clean" approach for this issue that will satisfy everyone.

Given that I think it's better to make some progress than none, I think we should go with @nmittler's solution #3593. The reason being that in my opinion it's likely the solution that will give us the best compromise of performance and usability with the least amount of code changes required. It's also the only solution that will get rid of this nasty per stream `HashMap`, which should give us some nice allocation savings.

So if @Scottmitch is fine with it, I would say LGTM to #3593.

**Comment by Scottmitch** [comment]
I would like to have an improvement in the properties map (@nmittler's https://github.com/netty/netty/pull/3593) but I would also like to have the feature (top level flow controller interface...flow control is a required part of the spec...I'm not convinced making it accessible is a problem) / potential improvements (only allocate the "full" state for flow control when it is actually needed...otherwise allocate a "reduced" set of state). I would like it if we could explore https://github.com/netty/netty/pull/3616 a bit more since it has been revised.

**Comment by nmittler** [comment]
@Scottmitch if we can get #3593 to the point where performance is no longer an issue, I'm not sure I see the point also exposing the flow control states in the API.  Unless you have a compelling reason, this seems like interface bloat and added complexity with no real benefit.

**Comment by Scottmitch** [comment]
@nmittler - Can we move the comments to their respective PRs?  Helps to have context.

**Comment by nmittler** [comment]
@Scottmitch done: https://github.com/netty/netty/pull/3616#issuecomment-93766867

**Comment by nmittler** [comment]
Fixed by #3593
