### ISSUE TITLE
Twitter HPACK updates

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3597]
Since HPACK is almost an RFC it may be worth investigating the [twitter/hapck](https://github.com/twitter/hpack) dependency we leverage as our HPACK implementation.  The following areas are of interest:

1. API
  - The current interface exposes byte[], InputStream, OutputStream, and other java native types ([Decoder.decode](https://github.com/twitter/hpack/blob/master/src/main/java/com/twitter/hpack/Decoder.java#L91), [Encoder.encodeHeader](https://github.com/twitter/hpack/blob/master/src/main/java/com/twitter/hpack/Encoder.java#L69)). We may be able to supplement these with Netty types.
2. Memory
 - There is a few places which require copy operations ([Encoder.add](https://github.com/twitter/hpack/blob/master/src/main/java/com/twitter/hpack/Encoder.java#L339), [Decoder.readStringLiteral](https://github.com/twitter/hpack/blob/master/src/main/java/com/twitter/hpack/Decoder.java#L518), [HuffmanDecoder.decode](https://github.com/twitter/hpack/blob/master/src/main/java/com/twitter/hpack/HuffmanDecoder.java#L92)).  Can we avoid these?
 - Investigation is needed into the [HuffmanDecoder.Node](https://github.com/twitter/hpack/blob/master/src/main/java/com/twitter/hpack/HuffmanDecoder.java#L107) class to see if the `256` child array is necessary...and if this leads to significant memory overhead.
3. Performance
 - Would using Netty's ByteString for comparison/hashcode/equals be an improvement over [HeaderField](https://github.com/twitter/hpack/blob/master/src/main/java/com/twitter/hpack/HeaderField.java#L59)/[HpackUtil.equals](https://github.com/twitter/hpack/blob/master/src/main/java/com/twitter/hpack/HpackUtil.java#L27) and not leak timing info?
  - Can iteration over the Stream objects ([Decoder.decode](https://github.com/twitter/hpack/blob/master/src/main/java/com/twitter/hpack/Decoder.java#L92)) be improved?
  - Is the [Encoder.headerFields](https://github.com/twitter/hpack/blob/master/src/main/java/com/twitter/hpack/Encoder.java#L35) usage and related [Encoder.BUCKET_SIZE](https://github.com/twitter/hpack/blob/master/src/main/java/com/twitter/hpack/Encoder.java#L26) optimal, or would having this be configurable make sense?
4. Benchmarking
 - If we do make changes...how can we say if they are good or bad?

**Comment by Scottmitch** [comment]
Previous discussion related to this matter can be found in https://github.com/netty/netty/issues/3503.

**Comment by Scottmitch** [comment]
@louiscryan @nmittler @buchgr - FYI. Has there been any movement on this on your end?

**Comment by louiscryan** [comment]
Sorry, not much yet, hoping to get back to it this week

**Comment by Scottmitch** [comment]
@louiscryan - No problem.  I took a brief look last night and couldn't find the synchronized blocks we talked about....but listed some areas that I though looked interesting in the issue description.  Feel free to append more areas of interest as you dive in.

**Comment by louiscryan** [comment]
I think the biggest item would be the ability to cache parsed representations of received header values and propagate that up through the stack.

**Comment by nmittler** [comment]
Just started an issue to create benchmarks for hpack: https://github.com/twitter/hpack/issues/23

**Comment by nmittler** [comment]
FYI, the benchmarks have been committed for hpack. See https://github.com/twitter/hpack/pull/24#issuecomment-96060432 for preliminary results.

**Comment by Scottmitch** [comment]
@nmittler - After the benchmarks have been added do you see any need for improvement?

I have noticed there is a bytes -> string conversions to do lookups into data structures on what appears to be a "hot" code path.  We may be able to avoid this with `ByteString`:

https://github.com/twitter/hpack/blob/master/hpack/src/main/java/com/twitter/hpack/StaticTable.java#L114

**Comment by nmittler** [comment]
@Scottmitch I definitely think something like this should be investigated and the benchmarks now provide a basis for comparison. The need for gRPC isn't that high, however, since we typically don't include very many headers so this has not been showing up as a "hot" code path in our testing thus far.

I'm probably not going to have the bandwidth to get to this any time soon.  If it's a priority for you feel free to throw together a PR.

**Comment by normanmaurer** [comment]
@Scottmitch is this still on your to do list ?

**Comment by Scottmitch** [comment]
@normanmaurer - I don't think we have diagnosed twitter's hapck as a bottleneck that warrants optimization as of now. I think there is an opportunity for improvement, but not sure this is a high priority issue.  I think most of the usages of twitter's hpack and so we should be able to improve this in the future if necessary.

@nmittler - Thoughts?

**Comment by nmittler** [comment]
@Scottmitch Yeah I think we can just close this.  @buchgr had done some profiling and hpack was not on his radar.

**Comment by normanmaurer** [comment]
Ok cool... Trying to cleanup a bit the issue tracker ;)

**Comment by Scottmitch** [comment]
@normanmaurer +1. Thanks for scrubbing the issues!

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5355
