### ISSUE TITLE
ServerCookieDecoder can't handle attributes without values

### ISSUE THREAD

**Issue by jurmous** [netty/netty#3599]
Netty version: 4.1.0.beta4

I want to decode a cookie with the Secure and HTTPOnly attributes but it won't be decoded by the ServerCookieDecoder. 

The cookie to decode:
```
SESSION=1|abcdef123|TEST123; Max-Age=300; Expires=Wed, 08 Apr 2015 10:44:01 GMT; Path=/; Domain=.example.net; Secure; HTTPOnly
```

It crashes with the following stack trace while it is decoding Secure
```
java.lang.NullPointerException: value
	at io.netty.handler.codec.http.DefaultCookie.setValue(DefaultCookie.java:106)
	at io.netty.handler.codec.http.DefaultCookie.<init>(DefaultCookie.java:78)
	at io.netty.handler.codec.http.ServerCookieDecoder.decode(ServerCookieDecoder.java:172)
        [...]
```

It works perfectly with the deprecated io.netty.handler.codec.http.CookieDecoder

Link to the standard: http://tools.ietf.org/html/rfc6265#section-5.2.5

**Comment by slandelle** [comment]
Your cookie header is not valid. A cookie pair must be name=value.

**Comment by jurmous** [comment]
Are you sure? It is not a pair on wikipedia:
http://en.wikipedia.org/wiki/HTTP_cookie#Domain_and_Path

From RFC6265:
> If the attribute-name case-insensitively matches the string "Secure",
> the user agent MUST append an attribute to the cookie-attribute-list
> with an attribute-name of Secure and an empty attribute-value.

Even here on github they are not sending them as pairs:
```
dotcom_user=jurmous; domain=.github.com; path=/; expires=Sun, 08-Apr-2035 12:57:14 GMT; secure; HttpOnly
```

**Comment by slandelle** [comment]
The NPE is on the cookie value, not an attribute value.
I'm on mobile now, I'll check asap.

**Comment by slandelle** [comment]
OK, I get it.

The attributes ("Max-Age", "Expires", etc) have NOTHING to do in a `Cookie` header (sent from the client to the server) being parsed by `ServerCookieDecoder`.

They belong to the `Set-Cookie` header (sent from the server to the client). Such header should then be parsed by `ClientCookieDecoder`.

What happens here is that, as ";" is the cookie pairs (name=value) separator in the `Cookie` header, `Secure` is interpreted as a cookie with a null value, hence the NPE as this field is required.

@trustin We could silently discard, but it's also a nice thing to have this Exception so the user gets notified he's sending/receiving invalid headers. WDYT?

**Comment by jurmous** [comment]
Ah yes thanks! I was indeed doing something wrong mixing up server and client side cookies in my test setup. This was not visible with the previous generic CookieDecoder. They now decode perfectly! A descriptive warning would be great if possible. :) 

Thanks for the quick responses!

**Comment by normanmaurer** [comment]
@fredericBregier @jurmous I think the exception is the right thing to do.
