### ISSUE TITLE
Excessive memory usage of DefaultHttp2Headers and overall slowness.

### ISSUE THREAD

**Issue by buchgr** [netty/netty#3600]
When running load tests for GRPC I have noticed that we are spending a lot of time in `DefaultHttp2Headers` and use very large amounts of memory, contributing to high allocation rates and lots of garbage collections. In one of my recent benchmarks we allocated roughly 500MB worth of `AsciiString` objects and their corresponding `byte[]` (representing the actual headers) over the time of the benchmark. We also allocated roughly 23GB worth of "overhead objects": `IntObjectHashMap`, `int[]`, `Object[]`, `HeaderEntry` and so on.

I was really surprised by that so I took a closer look at the `DefaultHttp2Headers`. JOL tells me that creating an empty `DefaultHttp2Headers` object uses 400 bytes. If I set the `:method` to `POST`, then the object takes 536 bytes (excluding any resizing that might have happened). Representing the example GRPC header from the spec [1] uses up 1920 bytes.

```
io.netty.handler.codec.http2.DefaultHttp2Headers instance footprint:
     COUNT       AVG       SUM   DESCRIPTION
        16        33       528   [B
         2       112       224   [I
         2       112       224   [Ljava.lang.Object;
        16        24       384   io.netty.handler.codec.AsciiString
         1        16        16   io.netty.handler.codec.AsciiString$1
         1        16        16   io.netty.handler.codec.DefaultBinaryHeaders$1
         1        16        16   io.netty.handler.codec.DefaultBinaryHeaders$2
         1        16        16   io.netty.handler.codec.DefaultBinaryHeaders$3
         9        40       360   io.netty.handler.codec.DefaultHeaders$HeaderEntry
         1        56        56   io.netty.handler.codec.http2.DefaultHttp2Headers
         2        40        80   io.netty.util.collection.IntObjectHashMap
        52                1920   (total)
```

That's almost 2KB to represent 220 characters worth of keys + values. Putting the same header into a `LinkedHashMap` only consumes 1368 bytes and it's well known that `LinkedHashMap` is memory consuming. Even using `String` instead of `AsciiString` takes up only 1584 bytes. A normal `HashMap` takes even less.

```
java.util.LinkedHashMap instance footprint:
     COUNT       AVG       SUM   DESCRIPTION
        16        33       528   [B
         1        80        80   [Ljava.util.HashMap$Node;
        16        24       384   io.netty.handler.codec.AsciiString
         1        56        56   java.util.LinkedHashMap
         8        40       320   java.util.LinkedHashMap$Entry
        42                1368   (total)
```

Additionaly, I benchmarked the lookup speed of `DefaultHttp2Headers` vs a `LinkedHashMap`.

```
Benchmark                             Mode  Cnt         Score       Error  Units
Benchmarks.measureRetrieveHeaders    thrpt  200  12559972.320 ± 10367.084  ops/s
Benchmarks.measureRetrieveMapAscii   thrpt  200  25384284.854 ± 61118.551  ops/s
Benchmarks.measureRetrieveMapString  thrpt  200  56829012.665 ± 61122.012  ops/s
```

Turns out `LinkedHashMap` is roughly twice as fast looking up `AsciiString` and five times as fast when using `String` objects. I haven't benchmarked insertion yet, as I am not sure how to do that correctly.

I just discovered this yesterday evening, I will do detailed profiling and come up with a more efficient implementation over the next few days. This should then be a big improvement for all the headers in the different Netty codecs.

@nmittler @Scottmitch @louiscryan @ejona86 

[1] https://github.com/grpc/grpc-common/blob/master/PROTOCOL-HTTP2.md#example

**Comment by normanmaurer** [comment]
@buchgr this is a very good find! /cc @trustin

**Comment by Scottmitch** [comment]
@buchgr - +1. There is definitely some fat to trim off the bones in [DefaultHeaders](https://github.com/netty/netty/blob/master/codec/src/main/java/io/netty/handler/codec/DefaultHeaders.java) and up the headers heriarchy.  It would be interesting to see if `IntObjectHashMap` could be optimized/improved also, or if the [DefaultHeaders](https://github.com/netty/netty/blob/master/codec/src/main/java/io/netty/handler/codec/DefaultHeaders.java)'s usage of it is just bad...

**Comment by buchgr** [comment]
@Scottmitch yeah definitely. Looking at all of those classes. Will see :-)

**Comment by Scottmitch** [comment]
@buchgr - Do you have a sample/profile from the above benchmarks you mentioned (not necessarily run in JMH but just in general)?

**Comment by louiscryan** [comment]
Good source for optimized collections...

https://github.com/real-logic/Agrona/tree/master/src/main/java/uk/co/real_logic/agrona/collections

**Comment by nmittler** [comment]
@normanmaurer what our your thoughts on taking that dependency?

**Comment by ejona86** [comment]
@louiscryan, those Agrona collections appear to be for Int/Long→Object. It seems we need Object→Object here.

I don't really follow how using a IntObjectMap could be productive for a String→String map, as the benefits of the IntObjectMap come from the key being a primitive.

**Comment by Scottmitch** [comment]
@ejona86 - Netty has its own primitive keyed map code (contributed by @nmittler I think?).  We are using that in the [DefaultHeaders.java#L84](https://github.com/netty/netty/blob/master/codec/src/main/java/io/netty/handler/codec/DefaultHeaders.java#L84) IIRC to decouple the array size from the number of buckets.  This may be beneficial when the spread of hash values is sparse amongst the total hash range (potentially use smaller amount of memory for what would be a "sparsely" populated array).  However depending on the use-case (i.e. if there is a good hash distribution relative to [bucketSize](https://github.com/netty/netty/blob/master/codec/src/main/java/io/netty/handler/codec/DefaultHeaders.java#L92)) this may end up requiring more memory and be counter-productive.

**Comment by Scottmitch** [comment]
Now that we are using this fancy `IntObjectMap` we should be able to lift the somewhat arbitrary `bucketSize` limitation...

**Comment by WhiteTrashLord** [comment]
I also don't understand why you did what you did. The class DefaultHttpHeaders is very complicated as well. Probably it makes sense for HttHeaders which come from a server. But I think it
s by far too much code for HttHeaders which you want to send to a client from a Netty HTTP server.
Therefor I suggest that we make a second much simpler HttpHeader class for Headers which are always sent from the Netty server back to the client.

I would do something like this:
Backed by an array and the Strings are actually CharSequences.

[0] -> new HeaderKeyValue("Server",  "Netty Pr0n Server")
[1] -> new HeaderKeyValue("Date",  "Sat, 10 Apr 2015 09:00:00 GMT")
[2] -> new HeaderKeyValue("Content-Length",  "64")

I think the developer will always know how many headers he wants to send back to the client. Therefor an array is the best structure?! And only this basic functions are needed:
Setting of headers
Reading all of the headers in the correct order

Or do I miss something?

**Comment by trustin** [comment]
My guess about perf difference between `AsciiString` and `String` is `String.equals()` is an intrinsic function. Didn't have time to dig deeper though.

**Comment by buchgr** [comment]
@trustin yes, got a PR regarding this on Monday.
