### ISSUE TITLE
potential memory leak in 4.0.19.final

### ISSUE THREAD

**Issue by garretwu** [netty/netty#3604]
I am using netty pooledByteBufAllocator as memory pool of my service.
The pattern is 1000+ front-end threads allocate ByteBuf to store the incoming data, and back end thread will use these ByteBuf and reclaim them.

However, I found that my service memory size keep increasing. Even when I stop all load, memory size does not shrink.(after PoolChunk be GCed the overall memory size will decrease, right?)
By dumping the heap of the service, I found that lots of PoolChunk whose freeBytes == chunkSize is not GCed because there are PooledHeapByteBuf still reference it.
The PooledHeapByteBuf, however, is in Recycler's threadlocal stack which means it has already been freed. 

Could we just dereference PoolChunk when deallocate PooledByteBuf?
protected final void deallocate() {
        if (handle >= 0) {
            final long handle = this.handle;
            this.handle = -1;
            memory = null;
            chunk.arena.free(chunk, handle, maxLength);
            chunk = null; <=== dereference the chunk
            recycle();
        }
    }

**Comment by normanmaurer** [comment]
No the memory usage will not go down once gc'ed. Why you think this would be the case?

**Comment by normanmaurer** [comment]
@garretwu but anyway we should dereference the chunk to allow faster GC. I think it will not help you though

**Comment by garretwu** [comment]
Thanks @normanmaurer ,  I may not express myself clearly.
What I see is that there are 100+ PoolChunk in heap dump even I stop the load, each of them is referenced by PooledHeapByteBuf which stay in Recycler's threadlocal stack.
Given all pooledByteBufs are released, I should not see so much PoolChunk in heap, right?

**Comment by virtman** [comment]
-XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=10 
you can try to run any java program with the parameters above, hard to say, if that is good way to go, but your program will give back memory to system after gc.

**Comment by garretwu** [comment]
Thanks @virtman ,  I will try.
However, what I met is that PoolChunk can not be GCed. Seems it is not the correct behavior for PooledByteBufAlloctor, right? 

Even we need pool some chunks to reduce memory allocation, but 100+ unused PoolChunk in heap does not sounds good...

It is more like object pool(PooledByteBuf pool) prevent memory pool(PoolChunk pool) to shrink because we do not dereference PooledByteBufs to PoolChunk when recycle them.

**Comment by normanmaurer** [comment]
@garretwu I just pushed a commit that will ensure these can de-referenced but like I said I'm not sure this is really the fix for the problem you see.

**Comment by garretwu** [comment]
Hi @normanmaurer, looks like the commit breaks following tests of netty/buffer:

 PooledLittleEndianHeapByteBufTest.testEnsureWritableAfterRelease »  Unexpected...
  PooledLittleEndianDirectByteBufTest.testEnsureWritableAfterRelease »  Unexpect...
  PooledBigEndianHeapByteBufTest.testEnsureWritableAfterRelease »  Unexpected ex...
  PooledBigEndianDirectByteBufTest.testEnsureWritableAfterRelease »  Unexpected ...

callstack:
Caused by: java.lang.NullPointerException: null
	at io.netty.buffer.PooledByteBuf.alloc(PooledByteBuf.java:118)
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:248)
	at io.netty.buffer.AbstractByteBufTest.testEnsureWritableAfterRelease(AbstractByteBufTest.java:1975)
	
These tests are expecting IllegalReferenceCountException when try to write to already released bytebuf but get NullPointerException.

In PooledByteBuf.java:118
    public final ByteBufAllocator alloc() {
        return chunk.arena.parent; <== chunk is set to null, thus NullPointerException throw
    }

**Comment by normanmaurer** [comment]
Doh! Let me fix asap

**Comment by normanmaurer** [comment]
Commit reverted.

**Comment by normanmaurer** [comment]
Commit reverted.

**Comment by stanpalatnik** [comment]
@normanmaurer @garretwu  @virtman  I don't see any labels or associated commits for this ticket. I'm also experiencing the exact same issue. Is this resolved in newer releases?
