### ISSUE TITLE
PrimitiveCollections template support

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3608]
Recently a template system was introduced to support more primitive type collections.  We should update `PrimitiveCollections` to reflect our broader support for primitive typed collections. This will likely involve making `PrimitiveCollections` templated in some fashion.

**Comment by Scottmitch** [comment]
@nmittler - FYI.

**Comment by normanmaurer** [comment]
+1

**Comment by Scottmitch** [comment]
We should hold off on this until we decide what to do about https://github.com/netty/netty/issues/3613.  No sense doing the work if we aren't going to keep our collections :)

**Comment by nmittler** [comment]
@Scottmitch +1

**Comment by Scottmitch** [comment]
@nmittler - I think you took care of this. Please re-open if you feel there is work still left to be done.

**Comment by nmittler** [comment]
@Scottmitch yup this is done ... thanks!
