### ISSUE TITLE
Netty IdleStateHandler finalize

### ISSUE THREAD

**Issue by balparslan** [netty/netty#3625]
How is IdleStateHandler closed on Android? I tried to use finalize() method but thread referred to IdleStateHandler is continue to work.

**Comment by normanmaurer** [comment]
@balparslan which version ?

**Comment by balparslan** [comment]
@normanmaurer  4.0.27

**Comment by normanmaurer** [comment]
@balparslan the IdleStateHandler uses the EventLoop of the Channels itself. So as long as the EventLoopGroup which is used by the Channels is alive you will see the threads.
