### ISSUE TITLE
Case sensitivity in HTTP/2 Headers.

### ISSUE THREAD

**Issue by buchgr** [netty/netty#3630]
This is to clarify some of the comments made in #3626 regarding case sensitivity of HTTP/2 Headers. (See https://github.com/netty/netty/pull/3626#issuecomment-92495119 and below).

Right now the HTTP/2 Headers have a feature to convert header names to lower case whenever they are inserted. It's turned on by default. Furthermore, all the equals comparisons when looking up names are always done case insensitive (independent of the lower case conversion) and we also have to specify a `HashCodeGenerator` that generates a case insensitive hash code. All of this adds a lot of complexity and it's very slow.

Headers in HTTP/2 are always lower case. I would argue it's therefore enough to simply check on insert that the header is all lower case and if not throw an Exception. That way we can be sure that we are conforming to the spec and we don't need to do any lowercase conversion, case insensitive compare or a `HashCodeGenerator`.

Now when running HTTP over HTTP/2 we can simply convert the headers to lower case in that specific handler.

WDYT @Scottmitch @nmittler

**Comment by Scottmitch** [comment]
@buchgr I'm assuming when you say `HTTP/2 Headers` you mean `header names in HTTP/2`, and if so +1 for HTTP/2 but -1 for HTTP/1.x.  [HTTP/1.x does not have the same restrictions](https://tools.ietf.org/html/rfc7230#section-3.2) as HTTP/2 w.r.t to header names and I think we still must do case insensitive comparisons / hash code generation.

**Comment by Scottmitch** [comment]
@buchgr - That being said if we are planning on diverging the implementations again (which I would prefer if we didn't have to) I think it would be useful to analyze the impact `HashCodeGenerator` has on performance / memory.

**Comment by buchgr** [comment]
@Scottmitch ok thanks. I am not planning on having completely separate implementations again. I think I have a plan on how to do with one without all this stuff. Will know more tomorrow, hope it works out :-). Wish me luck!

**Comment by Scottmitch** [comment]
@buchgr - That would be awesome! Good luck :)

**Comment by Scottmitch** [comment]
@buchgr - I'm going to pull in https://github.com/netty/netty/pull/3579.  I think it will make merging / re-work easier for your efforts in the headers re-work area.  Note you will have a small merge to resolve for your https://github.com/netty/netty/pull/3626 PR (just move your equals method changes from `AsciiString` to `ByteString`).

**Comment by archervanderwaal** [comment]
I expect the header name to be case sensitive, what should I do?
