### ISSUE TITLE
SSL fails on example in 4.0.27.Final

### ISSUE THREAD

**Issue by odbuser2** [netty/netty#3632]
io.netty:netty-all:4.0.27.Final
io.netty:netty-example:4.0.27.Final
Example: io.netty.example.http.file.HttpStaticFileServer
JavaSE: Oracle 8u40 on OSX

This example fails to serve a file when you use SSL (-Dssl=true).  Directory listing works fine.

**Comment by trustin** [comment]
Duplicate of #3592
