### ISSUE TITLE
HTTPProxyHandler CONNECT

### ISSUE THREAD

**Issue by rhart** [netty/netty#3634]
Netty version: 4.1.0.Beta4

Is it right that HTTPProxyHandler always sends a CONNECT request?  As I understand the spec, I think this is only applicable when you want to do tunneling?

**Comment by trustin** [comment]
Yes. Netty cannot assume you want to issue an HTTP request in your proxied connection, so it always opens a tunnel with a CONNECT request.

**Comment by rhart** [comment]
Ok thanks.  I just noticed that if I create my own crude proxy and set it as the proxy for a browser then I do not get a CONNECT so was just checking.  

What you're saying is that all proxies will (should) be able to deal with being sent a CONNECT even for a HTTP request.

**Comment by trustin** [comment]
@rhart Yes. The proxies that do not allow CONNECT will not work with Netty's HTTP proxy support implementation. In such a case, you'd better use the proxy support provided by the HTTP client libraries such as async-http-client. /cc @slandelle

**Comment by rhart** [comment]
The problem is, we are using Netty to create a HTTP client and therefore need this support in Netty :)  It sounds like from what you're saying we would need to roll our own proxy support?

**Comment by trustin** [comment]
[AsyncHttpClient](https://github.com/AsyncHttpClient/async-http-client) has Netty-based backend, so I guess it might be possible to use your existing event loop to send an HTTP request with AsyncHttpClient. I didn't take a close look though.

**Comment by rhart** [comment]
Thanks @trustin, I will look into this
