### ISSUE TITLE
AggregatedFullHttpMessage toString() behaviour

### ISSUE THREAD

**Issue by d-t-w** [netty/netty#3637]
This is related to #3019, the previous problem persists:

Prior to v4.0.24-FINAL you could call .toString on the output of HttpObjectAggregator regardless of whether the resulting HttpMessage has been released or not, from v.4.0.24-FINAL onwards you will encounter an error similar to:

```
io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.DefaultByteBufHolder.content(DefaultByteBufHolder.java:39) ~[netty-all-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.handler.codec.http.HttpMessageUtil.appendFullCommon(HttpMessageUtil.java:79) ~[netty-all-4.0.27.Final.jar:4.0.27.Final]
	at io.netty.handler.codec.http.HttpMessageUtil.appendFullRequest(HttpMessageUtil.java:55) ~[netty-all-4.0.27.Final.jar:4.0.27.Final]
```

This is due to the fact that AggregatedFullHttpMessage overrides .copy, .duplicate, and .retain from the ByteBufHolder interface but delegates .content to the DefaultByteBufHolder superclass which  checks the ref count every time you access content:

```java
@Override
public ByteBuf content() {
    if (data.refCnt() <= 0) {
        throw new IllegalReferenceCountException(data.refCnt());
    }
    return data;
}
```

whereas something like DefaultHttpContent does not check that count:

```java
@Override
public ByteBuf content() {
    return content;
}
```

It appears the AggregateFullHttpMessage only takes the benefit of .copy and .release from that type hierarchy, so I offer a PR where that is removed and the impl is similar internally to DefaultHttpContent, apologies if I've missed something obvious.

**context**

I have a Clojure networking framework which combines netty, clojure/core.async, and stuartsierra/component in an attempt at an async, event-driven architecture.

Basically you can combine components using core.async channels and macros, netty is plugged in as the network layer which translates input/output events to/from requests/responses. Any netty codec would work but in reality I use a fairly standard HTTP channel pipeline most often, and HttpObjectAggregator features in that.

I can manage the lifecycle of pooled bytebuf cleanly, or for some applications when each request is decoded and converted to an event I copy the bytebuf into memory as a single java.util.ByteBuffer and release the original at that point. In that case I still place the request alongside the ByteBuffer on the event, making it available for further processing - i.e. decoding the query-string or http-headers.

On occasion events are logged to disk, which calls toString, which errors if the msg has been released, where previously it did not.

There are multiple solutions to my problem, I could always manage pooled buffers and not memory copy, I could always configure my server to use Unpooled buffers, but all the other HttpMessage impl seem to be fine with .toString when released and the original behaviour has changed so I thought I'd chip in again.

Ta,
 Derek

**Comment by normanmaurer** [comment]
Fixed by #3638
