### ISSUE TITLE
TLS Application Protocol Accessor

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3641]
In order for the application to get access to the negotiated application protocol we currently require that a string `.split(":");` operation be done.  We should provide a more "standard" interface to access this information which does not require users to do string manipulation.

**Comment by trustin** [comment]
Thanks, @Scottmitch :-)

**Comment by trustin** [comment]
@Scottmitch Taking over :-)

**Comment by Scottmitch** [comment]
@trustin - Cool! Looking forward to a PR.

**Comment by Scottmitch** [comment]
fixed by https://github.com/netty/netty/pull/3846
