### ISSUE TITLE
optional netty dependency "jetty-alpn" is non-valid osgi artifact

### ISSUE THREAD

**Issue by CodingFabian** [netty/netty#3645]
I am currently lobbying on the jetty bugtracker to release a fixed up version of alpn-api which is identical to the one netty uses, but has a valid OSGi manifest
https://github.com/netty/netty/blob/master/pom.xml#L599

I am opening this issue to track this from here and to upgrade the dependency to make sure the netty pom does not poison the transitive dependency version once its fixed.

**Comment by normanmaurer** [comment]
@CodingFabian thanks! You guys rock....

**Comment by Scottmitch** [comment]
cool! let us know if you have any questions :)

**Comment by CodingFabian** [comment]
I actually wanted to leave the jetty bugzilla link here for tracking:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=459908

**Comment by CodingFabian** [comment]
you fixed it by upgrading to 1.1.2 in https://github.com/netty/netty/commit/e4af176be7e5049b5ae55525cb50bedf1437889b
I missed the point when thy released 1.1.1 which only contained the osgi fix.
