### ISSUE TITLE
Error compiling 4.1Beta5 on Windows

### ISSUE THREAD

**Issue by ottuzzi** [netty/netty#3646]
Hi,

   I would like to play with Google RPC (grpc) and to install it you need netty 4.1.
Instructions from grpc report the following:
$ git submodule update --init
$ cd lib/netty
$ mvn install -pl codec-http2 -am -DskipTests=true

And last step fails with:
```
[ERROR] Failed to execute goal on project netty-handler: Could not resolve dependencies for project io.netty:netty-handler:jar:4.1.0.Beta5-SNAPSHOT: Failure to find io.netty:netty-tcnative:jar:windows-x86_32:1.1.33.Fork1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```
As you can guess:
```
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: windows
[INFO] os.detected.arch: x86_32
[INFO] os.detected.classifier: windows-x86_32
[INFO] ------------------------------------------------------------------------
```

Bye
Piero

**Comment by Scottmitch** [comment]
@normanmaurer - Care to take a look?

**Comment by normanmaurer** [comment]
@ottuzzi this is because we not deploy netty-tcnative versions for 32bit windows. If you want to compile on windows 32bit you will need to compile and install your own version of netty-tcnative before try to build netty. 

See http://netty.io/wiki/forked-tomcat-native.html#wiki-h3-6
