### ISSUE TITLE
Discuss headers class hierarchy

### ISSUE THREAD

**Issue by buchgr** [netty/netty#3655]
While working on improving the performance and memory usage of Netty's headers, I couldn't help but notice that in my opinion the headers API is quite "fat" and maybe at times a bit too generic.

One of those very generic parts is the `DefaultConvertibleHeaders` class. As far as I can tell the reason to have the `DefaultConvertibleHeaders` is to maintain compatibility with `String` class after introducing `AsciiString`.

That's why I was wondering if it would make sense to merge the `DefaultConvertibleHeaders` with the `DefaultTextHeaders` and make the methods specifically for string conversion. This would reduce SLOC, complexity and make the API a lot nicer to use, because right now we would do something like `headers.getAndConvert("key")`, while with a string specific API it could be `headers.getString("key")`. It's not a big impact change and maybe it's a lot about personal taste, but I think this would make the API a lot more expressive and easier to understand.

I do understand that the idea behind the `DefaultConvertibleHeaders` is to provide a generic interface to be able to convert to any kind of object, but this might just not be needed here ...

**Comment by Scottmitch** [comment]
@buchgr - You got it.  The idea was to unify the class hierarchy and make it clear when type conversions were happening (i.e. `AndConvert` nomenclature). Now that the dust has settled `DefaultConvertibleHeaders` may be overkill and I agree we could simplify the hierarchy and remove some of the translation helper types associated with this.  So in summary it sounds reasonable to me!

**Comment by buchgr** [comment]
@Scottmitch sgtm, I won't touch it in my perf update for the headers as it comes with enough code changes already. Don't wanna change API's in this PR.

**Comment by Scottmitch** [comment]
@nmittler - FYI. We discussed this earlier today.  Seemed like you were interested in seeing this removed.

**Comment by nmittler** [comment]
@Scottmitch yeah, I was looking at the headers hierarchy when reviewing @buchgr's PR https://github.com/netty/netty/pull/3681#issuecomment-95244520.  It seems somewhat out of place in the hierarchy and may be better as a set of utility methods that operate on a `Headers` object.

**Comment by buchgr** [comment]
Let's broaden this issue to talk about the whole headers hierachy. 

I would argue we should get rid of `DefaultTextHeaders`, `DefaultBinaryHeaders` and `DefaultConvertibleHeaders` and their respective interfaces. The useful code in text and binary headers can be moved to utility classes and the methods in convertible headers should be part of the HttpHeaders interface and be specific to `String`. All agree? Cool! Let's do it :smile:

**Comment by Scottmitch** [comment]
+1. I think that the Headers implementation is centralized in DefaultHeaders these are no longer needed.  Used to be that they all has separate implementations....probably should have taken care of this when the headers class hierarchy and APIs were brought together...  These implementations mostly just change return types (just extra code that has to be maintained) and provide utilities already so seems reasonable to me.

**Comment by nmittler** [comment]
+1

**Comment by trustin** [comment]
Sounds good to me as long as API usability stays fine. (IIUC there should be no API usability problem with your proposal.)

**Comment by Scottmitch** [comment]
This should be mostly addressed by https://github.com/netty/netty/pull/4038. @nmittler - You may want to have a look.

**Comment by buchgr** [comment]
I think Nathan is on vacation #EastCoastBaby #StalkingTheMitOnFacebook

**Comment by nmittler** [comment]
@buchgr thanks for the stalking :)

@Scottmitch I took a quick scan ... LGTM

**Comment by Scottmitch** [comment]
I will close this for now. #4038 addresses most of the issue...if there are other specific suggestions lets track in a new issue.

**Comment by buchgr** [comment]
thanks! great work @Scottmitch
