### ISSUE TITLE
Close future hangs in ChannelFuture.close().sync()

### ISSUE THREAD

**Issue by gtomassi** [netty/netty#3656]
Netty version: 5.0.0.Alpha2

Context:
Changing from 4.1.0.Beta1 to 5.0.0.Alpha2, holding ALL else constant. I am positively using independent threads to call close() vs handle channel activity. Our "connection cleaning" job fails now as a result of close().sync() blocking forever. It happens to any socket channels that never actually connected. The channel close future remains false for isDone() forever, the fix is probably to add an immediate success return inside the close() somewhere for this scenario.

Steps to reproduce:
Bootstrap and connect a socket connection, make sure it fails and doesn't actually connect to anything. Then try and call close().sync() on the channel, it will hang indefinitely.

If you can't replicate the issue then feel free to reach out for more information, it is a very crucial item to Netty's reliability.

**Comment by normanmaurer** [comment]
checking....

**Comment by normanmaurer** [comment]
@gtomassi I think this was fixed... Please reopen if you still see the issue

**Comment by gtomassi** [comment]
@normanmaurer Great to hear, will try with newer Netty and our same code as soon as we get the opportunity and let you know otherwise. Thanks in advance..

**Comment by raner** [comment]
This issue may have resurfaced again with Netty 4.1.22, though I can't be sure that it was ever actually fixed. We keep running into a scenario where our application becomes extremely slow and shows very high latency. During these scenarios we noticed that, despite generously configured thread pools, the number of CPU threads suddenly starts stagnating at a certain plateau level, and we seemingly lost the ability to temporarily spawn up more threads. At the same time, we see a high number of our application's connections stuck in `CLOSE_WAIT` state, as shown in the diagram below:

<img width="931" alt="screen shot 2019-01-18 at 5 58 18 pm" src="https://user-images.githubusercontent.com/730344/51421126-85efe000-1b4e-11e9-9a22-138e484f0ba0.png">

A thread dump showed that a lot of CPU threads (typically several hundred) are stuck with the following stack trace, waiting for the promise that the Netty channel was closed:
```
java.lang.Thread.State: WAITING (on object monitor)
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:502)
at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:231)
- locked <0x00007fd0de000e58> (a io.netty.channel.DefaultChannelPromise)
at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:131)
at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:30)
at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:337)
at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:119)
at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:30)
at com.xxxxxxxxxxxx.core.comm.service.channels.AbstractSocketChannel.closeConnectionUnsafe(AbstractSocketChannel.java:273)
at com.xxxxxxxxxxxx.core.comm.service.channels.AbstractSocketChannel.closeConnection(AbstractSocketChannel.java:288)
at com.xxxxxxxxxxxx.app.comm.service.AppConnectionManager$2.run(AppConnectionManager.java:161)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```
What possible scenarios are there during which it could take a significant amount of time to close a Netty channel and the underlying TCP socket?
What additional things should we look at to shed some more light on this problem?
We've considered calling `close()` without `sync()`, i.e. in a non-blocking fashion, but unfortunately that has some other implications for our application.

If it's of any help, our application runs with a 64 GB heap on a system with 40 CPU cores.

**Comment by raner** [comment]
@normanmaurer do you have any additional suggestions what we could do to debug this problem or can you re-open the issue?

**Comment by normanmaurer** [comment]
@raner can you please upgrade to the latest 4.1.33.Final and see if you still see it ?

**Comment by raner** [comment]
@normanmaurer sure we'll do that. I won't be able to give you immediate feedback, though, as this problem does not occur very frequently (it happened twice in the last 4 months).
In the meantime, do you have any suggestions what else we could do to debug this? For example, what are the known reasons for significant delays when closing a connection?

**Comment by normanmaurer** [comment]
@raner my suspect would be a blocked EventLoop or a ChannelOutboundHandler that messes up the close call. An other problems could be a very large SO_LINGER setting

**Comment by finger92** [comment]
did you solve this problem?
