### ISSUE TITLE
JDK 9 might ship with a more space efficient String implementation

### ISSUE THREAD

**Issue by buchgr** [netty/netty#3664]
I stumbled across this issue on the openjdk bug tracker https://bugs.openjdk.java.net/browse/JDK-8054307 . It seems like JDK9 might ship with a more space efficient implementation for Strings, similar to what `ByteString` / `AsciiString` are trying to achieve. This is just meant as an FYI :-).

**Comment by Scottmitch** [comment]
Thanks for the heads up.  Perhaps we can utilize this some day :)
