### ISSUE TITLE
Removed HTTP/2 streams should consume all bytes

### ISSUE THREAD

**Issue by nmittler** [netty/netty#3668]
When a stream is removed from the connection, we should mark all of it's bytes as consumed so that the local flow controller will restore those bytes to the connection window. We'll also need to protect against the application trying to consume those bytes as well (probably just make it a no-op for closed streams).

**Comment by Scottmitch** [comment]
Thanks @nmittler.  I see you left this as a comment in https://github.com/netty/netty/pull/3616.  Are you pulling together a separate PR for this?

**Comment by nmittler** [comment]
I'm working on a PR to address this and history ... should have something ready shortly.

**Comment by Scottmitch** [comment]
@nmittler - OK. I would like to get a consolidated understanding as to why we need to keep stream history before you invest a lot of time in it.  See https://github.com/netty/netty/issues/3653#issuecomment-94580186.  Should we open another issue for stream history...or do you want to just list the rational here?

**Comment by nmittler** [comment]
@Scottmitch I've put together #3672 to address this.

I have been putting together a PR for stream history, but you're right we should finish our discussion on this: #3673.  Let's sort this out quickly ... grpc needs this.  @Scottmitch can you provide a dump of your thoughts on how we can avoid history on a case-by-case basis in the decoder?
