### ISSUE TITLE
HTTP/2 shouldn't flush automatically

### ISSUE THREAD

**Issue by ejona86** [netty/netty#3670]
HTTP/2 flushes for [WINDOW_UPDATES](https://github.com/netty/netty/blob/da01902ea2216f6cbf9d1b2e0cd80d3b879af06b/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2LocalFlowController.java#L376), [RST_STREAM](https://github.com/netty/netty/blob/9c4af6af7e59edf063c92b1d1eb7fddc432de586/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L503), [GOAWAY](https://github.com/netty/netty/blob/9c4af6af7e59edf063c92b1d1eb7fddc432de586/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L538), and [PING](https://github.com/netty/netty/blob/19c864505d017a52fdbf1ef600715d42d36d36fa/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L424). It also flushes "when appropriate" [in the remote flow controller](https://github.com/netty/netty/blob/da01902ea2216f6cbf9d1b2e0cd80d3b879af06b/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2RemoteFlowController.java#L221).

All these flushes should be removed, as they prevent efficient flush behavior. Flushing too often causes unnecessary syscalls but also causes extra TCP segments because Nagle's is off (by default in Netty). With the current code every DATA and WINDOW_UPDATE frame is sent separately, until flow control is exhausted after which DATA frames may become coalesced. Flushing when no messages have been queued is relatively cheap, as it does cause flush() calls through the entire pipeline, but the end of the pipeline [just ignores it](https://github.com/netty/netty/blob/da01902ea2216f6cbf9d1b2e0cd80d3b879af06b/transport/src/main/java/io/netty/channel/AbstractChannel.java#L799).

Flushing should occur on `channelReadComplete()` and if someone writes to the channel from outside of the channel. Both of these would be appropriate to do in the application (so HTTP/2 code would have _no_ flushes), but given the normal usages of the code, it may make sense for Http2ConnectionHandler to flush on `channelReadComplete()`.

**Comment by Scottmitch** [comment]
+1 for reducing flush calls.

**Comment by ejona86** [comment]
@louiscryan, you want to pick this up?

**Comment by ejona86** [comment]
Or Scott, have you already started working on it?

**Comment by Scottmitch** [comment]
@ejona86 - Sorry for the delay...I have not started working on this...just took the assignment so it didn't get lost.

**Comment by ejona86** [comment]
@Scottmitch, np, I wasn't trying to rush you. @louiscryan was just working on some related flushing and if you weren't working on it it might have made sense for him to pick it up.

**Comment by Scottmitch** [comment]
I'll take a stab at this.

**Comment by louiscryan** [comment]
Scott, If you haven't gotten to this already I can pick this up today.

**Comment by Scottmitch** [comment]
@louiscryan - Up to you. I just started looking at it.  If you want it then it is yours.

**Comment by louiscryan** [comment]
Ill take it if you don't mind. I'm working on some benchmarks in GRPC which
I can use to help validate...

**Comment by normanmaurer** [comment]
@louiscryan cool :)

**Comment by Scottmitch** [comment]
@louiscryan - You got it. Would you mind closing https://github.com/netty/netty/pull/3691?

**Comment by louiscryan** [comment]
Closed #3691

**Comment by ejona86** [comment]
Does it seem like this can be closed now?

**Comment by Scottmitch** [comment]
@ejona86 - I think so.  If we need to reduce flushing more we can open another issue.

@louiscryan - You mentioned you were doing performance testing in this area.  Do you have any results to report?

**Comment by louiscryan** [comment]
Scott

See benchmark notes in https://github.com/grpc/grpc-java/pull/431 for
before / after impact of write & flush coalescing in grpc
