### ISSUE TITLE
SSLContextBuilder builds client context for server and vice-versa

### ISSUE THREAD

**Issue by leogomes** [netty/netty#3671]
Introduced with: https://github.com/netty/netty/issues/3531

SslContextBuilder constructor has a [boolean parameter ``forServer``](https://github.com/netty/netty/blob/4d56028df5a7be31561442f45bc2141eb84aa5ad/handler/src/main/java/io/netty/handler/ssl/SslContextBuilder.java#L75), which is set to ``false`` in the [``forServer(...)`` static factory method](https://github.com/netty/netty/blob/4d56028df5a7be31561442f45bc2141eb84aa5ad/handler/src/main/java/io/netty/handler/ssl/SslContextBuilder.java#L57) and set to ``true`` in the ``forClient(...)`` equivalent. Leading the ``build()`` method to build a client context for a server and a server context for a client. It turns out that it doesn't seem to have caused too much damage nor there are tests failing for that. So, while I could have sent a quick PR to fix that, I think it deserves a bit more testing to make sure that this sort of think is caught/analysis to see if we really need those two types of contexts.

**Comment by Scottmitch** [comment]
@leogomes - Can you be more specific?  I looks like you are implying the context that is generated by `build()` is reversed.  However it looks to be correct https://github.com/netty/netty/blob/4d56028df5a7be31561442f45bc2141eb84aa5ad/handler/src/main/java/io/netty/handler/ssl/SslContextBuilder.java#L206.

**Comment by ejona86** [comment]
Doh!

The value [is propagated](https://github.com/netty/netty/blob/216d5ee5836f9c879de3831ab034c50b6eb9ea17/handler/src/main/java/io/netty/handler/ssl/JdkSslContext.java#L193) to the JDK's [SSLEngine](http://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLEngine.html#setUseClientMode(boolean)).

@Scottmitch, the [wrong value is passed to the contructor](https://github.com/netty/netty/blob/4d56028df5a7be31561442f45bc2141eb84aa5ad/handler/src/main/java/io/netty/handler/ssl/SslContextBuilder.java#L34).

**Comment by Scottmitch** [comment]
@ejona86 - Heh...we flipped the variable name from `forClient` but missed these cases...oops...care to submit a PR?

We can address unit tests after we have it patched.

**Comment by ejona86** [comment]
@Scottmitch, sure, I can do the PR.

**Comment by Scottmitch** [comment]
Fixed with https://github.com/netty/netty/issues/3674.

Thanks for reporting @leogomes!

**Comment by leogomes** [comment]
@Scottmitch Wouldn't it be good to keep this one open or create another one to make sure we add unit tests to avoid regression on this area?

**Comment by Scottmitch** [comment]
@leogomes - Thanks for the reminder... https://github.com/netty/netty/issues/3686.
