### ISSUE TITLE
Investigate resurrecting HTTP/2 stream history

### ISSUE THREAD

**Issue by nmittler** [netty/netty#3673]
There has been a lot of discussion recently due to breaking commit c6cfb68, which removed the stream removal policy.  This is the root cause of #3643. Other threads include #3653 and #3557.

@Scottmitch has suggested that we may be able to get by without bringing back some sort of stream history. We should investigate whether this is possible ... if not, we'll need to look into bringing back a lightweight history into the HTTP/2 codec.

@Scottmitch @buchgr @ejona86

**Comment by Scottmitch** [comment]
@nmittler - Thanks for reporting.  Here is your https://github.com/netty/netty/issues/3668#issuecomment-94590158

> I have been putting together a PR for stream history, but you're right we should finish our discussion on this: #3673.  Let's sort this out quickly ... grpc needs this.  @Scottmitch can you provide a dump of your thoughts on how we can avoid history on a case-by-case basis in the decoder?

**Comment by nmittler** [comment]
Just to recap some discussion between myself, @Scottmitch, and @buchgr ...

We're going to look into a no-history implementation.  The only snag is what to do about inbound flow control.  The current thought is that the local flow controller could somehow support missing (null?) streams.  When data is received for these streams, flow control is applied to the connection only and then immediately consumed.

**Comment by buchgr** [comment]
@nmittler I think that's a very pragmatic solution. SGTM.

**Comment by Scottmitch** [comment]
@nmittler +1. Link to your PR https://github.com/netty/netty/pull/3685.

**Comment by nmittler** [comment]
Fixed by #3685
