### ISSUE TITLE
Livelock issue in MpscLinkedQueue.java

### ISSUE THREAD

**Issue by gsoltis** [netty/netty#3675]
Hi,

We've been running netty 4.0.27 in production for ~1 week, and recently we started noticing cases where calls to `SingleThreadEventExecutor.pendingTasks()` were never completing. We traced the issue down to `MpscLinkedQueue.peekNode()`, which appears to be just spinning. 

Reading the contract at the top of the file seems to indicate that calling `MpscLinkedQueue.size()` should be ok from multiple threads, but perhaps I am reading it incorrectly?

Unfortunately I don't have a good way of reproducing this, it only showed up in production. For now we've removed the code that was calling `.size()`, but if anyone has suggestions on a way to try reproducing the bug (or suggestions as to how we're violating the queue contract), I'd be happy to try.

**Comment by normanmaurer** [comment]
@gsoltis so it only happens when you call size() ? I

**Comment by gsoltis** [comment]
So far, yes, that's the only place I've seen it. We have each event loop hooked up to a stats reporting module that reports the size of the task queue every few seconds. We noticed it because the stats stopped being reported, and it turns out the reporting thread was blocked on the call to `.size()`, which in turn was spinning on `peekNode()`. 

Here's the last few lines of the stacktrace:

>"StatsDLogger" prio=10 tid=0x00007f8e08f83800 nid=0x5664 runnable [0x00007f78f105b000]
>   java.lang.Thread.State: RUNNABLE
>	at io.netty.util.internal.MpscLinkedQueue.peekNode(MpscLinkedQueue.java:109)
>	at io.netty.util.internal.MpscLinkedQueue.size(MpscLinkedQueue.java:166)
>	at 
> io.netty.util.concurrent.SingleThreadEventExecutor.pendingTasks(SingleThreadEventExecutor.java:287)

**Comment by normanmaurer** [comment]
@gsoltis will check... Thanks for the report buddy!

**Comment by gsoltis** [comment]
No problem. Let me know if there's anything else I can provide. I realize
it's not a lot to go on :)

**Comment by normanmaurer** [comment]
@gsoltis what I can tell you is that size() is now allowed to be called by another thread then the EventLoop. Thinking about a proper fix.

**Comment by normanmaurer** [comment]
@gsoltis can you please check if #3684 fixes the problem for you ? Thanks!

**Comment by gsoltis** [comment]
I'll give it a shot. It may be a few days before I can both get it in production and verify that it's working, since it took so long to show up previously.

**Comment by normanmaurer** [comment]
Ok just let me know once you have results

**Comment by normanmaurer** [comment]
@gsoltis I think the change fixed it... Please re-open if you still see the issue.

**Comment by gsoltis** [comment]
Will do, thanks for your help!
