### ISSUE TITLE
netty-4.0.27.Final  compile error for cannot import netty-tcnative lib

### ISSUE THREAD

**Issue by stoneCrystal** [netty/netty#3676]
I download the netty-4.0.27.Final version by git, but after build project, the netty-handler project has compile error, like following:
![default](https://cloud.githubusercontent.com/assets/7323503/7243911/540f2840-e806-11e4-9573-db82933470c8.PNG)

is my local mavne repository setting problem or others problem??

**Comment by normanmaurer** [comment]
What OS ?

**Comment by stoneCrystal** [comment]
windows7

**Comment by normanmaurer** [comment]
@stoneCrystal 64bit or 32bit ?

**Comment by stoneCrystal** [comment]
import org.apache.tomcat.jni.Library;
import org.apache.tomcat.jni.Pool;
import org.apache.tomcat.jni.SSL;
import org.apache.tomcat.jni.SSLContext;

**Comment by stoneCrystal** [comment]
64

**Comment by stoneCrystal** [comment]
it seems like netty-tcnative  not import in project succesfully

**Comment by stoneCrystal** [comment]
@normanmaurer  how to fix is problem?

**Comment by normanmaurer** [comment]
@stoneCrystal does `mvn clean package` works for you on the cmd line ?

**Comment by stoneCrystal** [comment]
@normanmaurer   mvn clean pakcage not work, following is the error message
![1](https://cloud.githubusercontent.com/assets/7323503/7277817/ab73f46e-e944-11e4-95b9-bc79256c81cd.PNG)

**Comment by normanmaurer** [comment]
I need the full output to see why it fails.

**Comment by normanmaurer** [comment]
Closing as this need more info... Please ensure you have:

maven 3.1.1+
java 7+
