### ISSUE TITLE
SslContextBuilder unit tests and replace deprecated usage in examples

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3686]
1. https://github.com/netty/netty/issues/3671 was related to a simple mistake which built the opposite SslContext object type and this was not caught with unit tests.

2. The SslContextBuilder deprecated the old static factory methods but didn't replace all usages of these in the examples.

**Comment by Scottmitch** [comment]
@ejona86 - Would you mind taking care of this?

**Comment by ejona86** [comment]
Sure, I can take care of it.

For 1, I'm not sure exactly what should be in such tests. There aren't any existing tests for SslContext creation. I can make a single test for server vs client pretty easily though.

For 2, I fixed all the usages I saw, but that only included 4.0. I'll need to look at 4.1 and 5.0 to see what other usages there are.

**Comment by Scottmitch** [comment]
@ejona86 - Thanks.  If we have nothing then something should be better :)  I trust your judgement.

Yah 4.1 has http/2 that I noticed was not updated...maybe that is it?

**Comment by leogomes** [comment]
There's also: 
https://github.com/netty/netty/blob/d1a9a08f36c4b5c830f57fb9c032707ec309c3ae/example/src/main/java/io/netty/example/memcache/binary/MemcacheClient.java#L56

And I believe these unused imports are leftovers of the refactoring, so should be removed as well:
https://github.com/netty/netty/blob/4d56028df5a7be31561442f45bc2141eb84aa5ad/example/src/main/java/io/netty/example/spdy/client/SpdyClient.java#L35

https://github.com/netty/netty/blob/4d56028df5a7be31561442f45bc2141eb84aa5ad/example/src/main/java/io/netty/example/spdy/server/SpdyServer.java#L31

**Comment by leogomes** [comment]
Actually, the whole HTTP/2 thing in the MemCacheClient example seems a copy and paste mistake :)
I saw that it was [introduced here](https://github.com/netty/netty/commit/3f8194557b5fe14e8f3313570ef28f29cbbef150#diff-0026312c5ac1bba34c5cdfdc2d1dc0bb) by @trustin, but imho since it's demoing memcache binary protocol there shouldn't be an ALPN there, only plain TLS/SSL as an option.

**Comment by Scottmitch** [comment]
I agree...not sure why ALPN is needed in memcache... @trustin ?

**Comment by normanmaurer** [comment]
+1

**Comment by ejona86** [comment]
Okay, while I'm there I'll clean up the memcache example's usage of TLS.

**Comment by Scottmitch** [comment]
@ejona86 - I think we can close this. Do you agree?

**Comment by trustin** [comment]
Thanks for pointing that out. It was obviously my fault. :-/

**Comment by Scottmitch** [comment]
@ejona86 - I'm going to close this. Feel free to re-open if you feel more work needs to be done.
