### ISSUE TITLE
websocket server does not send close frame

### ISSUE THREAD

**Issue by gbrd** [netty/netty#3687]
Netty version = 4.0.27.Final

In WebSocketServerProtocolHandler getHandshaker and setHandshaker, storing in channel context instead of ChannelHandlerContext helped to make server answer to client close frame.

ctx.channel().attr(HANDSHAKER_ATTR_KEY)
instead of ctx.attr(HANDSHAKER_ATTR_KEY)

Without that,  handshaker is null at line 106 of WebSocketServerProtocolHandler (decode method and frame is a close frame)

Does it make sense ?
When are created ChannelHandlerContext ? we have a different one on each message received ?

**Comment by normanmaurer** [comment]
@gbrd sorry that it took so long... I somehow missed it :(
