### ISSUE TITLE
HTTP2 remote flow controller flushing is too eager

### ISSUE THREAD

**Issue by louiscryan** [netty/netty#3688]
@nmittler @Scottmitch 

The flow controller will always flush when data is added to it. This prevents higher layers from coalescing flushes when more data is known to follow. For example headers and payload for HTTP POST will cause a minimum of two flushes to the channel.

I suggest we remove flushing from the flow controller and make the encoder responsible for it and add an explicit flush param to the encoder interfaces for DATA & HEADERS at a minimum. This allows higher layers to decide flush timing

**Comment by nmittler** [comment]
+1

**Comment by louiscryan** [comment]
.. actually looking at the contract for Http2FrameWriter I think the flow-controller is in violation of it.

"All of the write methods in this interface write to the context, but DO NOT FLUSH. To perform a flush, you must separately call {@link ChannelHandlerContext#flush()}"

**Comment by ejona86** [comment]
@louiscryan, I strongly disagree. Neither the encoder nor the flow controller should handle it. Instead, it should be handled later in the channel pipeline. Doing so removes the need for passing flush parameters at all. See #3670.

**Comment by louiscryan** [comment]
Right, hence my earlier comment about being in violation of the documented contract in Http2FrameWriter.

**Comment by ejona86** [comment]
I don't understand what the flow controller has to do with Http2FrameWriter; I don't see it implementing that interface. But it is true that Http2RemoteFlowController [explicitly states that it will flush](https://github.com/netty/netty/blob/c884847af993fe5bf2cace1dfd9e219b348c7047/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2RemoteFlowController.java#L30).

So @louiscryan, at the present time is this issue any different than #3670?

**Comment by louiscryan** [comment]
DefaultHttp2ConnectionEncoder which implement Http2FrameWriter delegates it's writes to the flow-controller which flushes so it's the encoder that is in violation of its contract.

**Comment by Scottmitch** [comment]
Some one is flushing too much :)  We can also change the contracts to which ever makes more sense....if that helps :)

**Comment by louiscryan** [comment]
Closing. Work will now be tracked in https://github.com/netty/netty/issues/3670
