### ISSUE TITLE
Host spot in decoding memcache key

### ISSUE THREAD

**Issue by youngm** [netty/netty#3689]
Hi,

LOVE the new memcache codec!

I'm building a server and while doing some profiling found one of my biggest hot spots was decoding the memcache key:

https://github.com/netty/netty/blob/master/codec-memcache/src/main/java/io/netty/handler/codec/memcache/binary/AbstractBinaryMemcacheDecoder.java#L107

In my server I don't actually need the key to be a String and could make my server faster by not converting the key to a String.

Any thoughts on accepting a PR from me that stores the key as a ByteBuf and converts it to a String on demand on invocations of BinaryMemcacheMessage.key()?  Then expose new BinaryMemcacheMessage.rawKey() methods to get and set an actual ByteBuf storing the key?

**Comment by Scottmitch** [comment]
@youngm - Thanks for reporting!  Are you interested in submitting a PR?  This codec may be getting some updates soon...but not sure when....

**Comment by youngm** [comment]
@Scottmitch I'd be happy to submit a PR for this if you think the concept is worthy of being accepted.

**Comment by Scottmitch** [comment]
Using Strings is not ideal. I can't think of a reason why the binary codec should be using strings at all.  I would need to investigate the codec more to know what is the right way to go about it....but less reliance on strings seems like an improvement.

**Comment by youngm** [comment]
@Scottmitch The spec for the binary protocol is somewhat vague but implies in a couple of places that the keys should be text based.  Perhaps I should simply use an AsciiString instead.  That would be simple and would probably solve my hot spot.

Do you think I need to maintain API compatibility with String?  I'm not familiar with Netty's API backwards compatibility standards.

**Comment by Scottmitch** [comment]
We keep API compatibility across "major" versions.  So 4.x should be API compatible with 4.1.  A nice exception to this is new stuff doesn't break anything.  The memcache codec is not in 4.0 (which is released) and so it is therefore eligible for API changes.  This codec is targeting the binary protocol https://github.com/memcached/memcached/blob/master/doc/protocol-binary.xml.  I think the majority of it is binary based...not sure if there is some status text or something but I would think those would be just fixed binary values.

**Comment by youngm** [comment]
@Scottmitch Sounds good ByteBuf it is.  I'll put together a PR.  Thanks for talking me through this.

**Comment by normanmaurer** [comment]
@daschl wdyt ?

**Comment by daschl** [comment]
@normanmaurer thanks for pinging me, I didn't see that one coming in.

The vanilla memcached instances basically require the key to be 250 bytes. In practice people use ASCII or UTF-8 encoded strings, which of course might translate to less than 250 characters given that a character can occupy more bytes.

The main reason to use a string back when I wrote it is that I wanted to have an overlap with the ASCII protocol, but we ruled that out for various reasons. From my side, I'm good with moving it to ByteBuf.

@youngm please ping me once you have something to review :)

**Comment by windie** [comment]
This one can be closed

**Comment by Scottmitch** [comment]
thanks @windie !

**Comment by youngm** [comment]
@windie Yes Thanks!
