### ISSUE TITLE
Android SslHandler (4.0.27)

### ISSUE THREAD

**Issue by alexzk1** [netty/netty#3692]
Basically this one explains:
https://github.com/restlet/restlet-framework-java/issues/852

This one piece of netty code continuously drains memory in server mode until complete phone stuck:
```java
for (;;)
            {
                ByteBuffer out0 = out.nioBuffer(out.writerIndex(), out.writableBytes());

                SSLEngineResult result = engine.wrap(in0, out0);
                in.skipBytes(result.bytesConsumed());
                out.writerIndex(out.writerIndex() + result.bytesProduced());
                System.err.println("Android total fix, code: "+result.getHandshakeStatus()+
                        ", consumed: "+result.bytesConsumed()+", status: "+result.getStatus() +"produced: "+result.bytesProduced());
                switch (result.getStatus())
                {
                    case BUFFER_OVERFLOW:
                        out.ensureWritable(maxPacketBufferSize);
                        break;
                    default:
                        return result;
                }

                /*//fixme: android fix 2
                long total = 0;
                for (ByteBuffer b : in0)
                    total += b.remaining();
                if (total == 0)
                {
                    SSLEngineResult result = engine.wrap(in0, out0);
                    System.err.println("Android total fix, code: "+result.getHandshakeStatus()+", consumed: "+result.bytesConsumed()+", status: "+result.getStatus());
                    out.ensureWritable(maxPacketBufferSize);
                    return new SSLEngineResult(SSLEngineResult.Status.BUFFER_OVERFLOW, result.getHandshakeStatus(),0,0);
                }
                else
                {
                    //and of fix (android dont do BUFFER_OVERFLOW)

                }*/
            }
```
Log prints:
4689-15730/net.over.paste W/System.err﹕ Android total fix, code: NOT_HANDSHAKING, consumed: 0, status: OKproduced: 37
04-24 07:57:40.842  14689-15730/net.over.paste W/System.err﹕ Android total fix, code: NOT_HANDSHAKING, consumed: 0, status: OKproduced: 37
04-24 07:57:40.852  14689-15730/net.over.paste W/System.err﹕ Android total fix, code: NOT_HANDSHAKING, consumed: 0, status: OKproduced: 37
04-24 07:57:40.852  14689-15730/net.over.paste W/System.err﹕ Android total fix, code: NOT_HANDSHAKING, consumed: 0, status: OKproduced: 37
04-24 07:57:40.852  14689-15730/net.over.paste W/System.err﹕ Android total fix, code: NOT_HANDSHAKING, consumed: 0, status: OKproduced: 37

**Comment by Scottmitch** [comment]
@alexzk1 - Thanks for reporting! I'm assuming you are referring to this section of code [SslHandler.java#L614](https://github.com/netty/netty/blob/master/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L614)?  It sounds like you have a patch...would you care to submit a PR?

**Comment by Scottmitch** [comment]
However it seems like based upon your issue description this may be more of an Android bug?

**Comment by normanmaurer** [comment]
@Scottmitch @alexzk1 I guess even if it is just a "workaround" for an Android bug we maybe should include it if it not gives us a performance impact on non-android usage.

**Comment by alexzk1** [comment]
well...it do not work...that was what I tried.
It stops drain memory but...no connection yet. But by log it seems like that guy described.

**Comment by alexzk1** [comment]
Ok guys....android looks completely broken :/ I think need to re implement and provide own SSLEngine fixed ...I was able to bypass shake, but next android consumes 1 byte more than SE and shows checksum error. If I fix consumed by -1 byte it gets infinite loop again...





if (OsHelper.getOS() == Landiscovery.Platform.plANDROID)
                {
                    if (consumed > 0)
                        consumed -=1;

                    if (status == SSLEngineResult.HandshakeStatus.NOT_HANDSHAKING && lastStatus == SSLEngineResult.HandshakeStatus.NEED_WRAP)
                        status = SSLEngineResult.HandshakeStatus.FINISHED;
                    else
                    {
                        if (written == 37 && consumed == 0)//lastStatus == SSLEngineResult.HandshakeStatus.FINISHED)
                            written = 0;
                    }
                    lastStatus = status;
                }

**Comment by normanmaurer** [comment]
@alexzk1 ok so let us close this as won't fix then
