### ISSUE TITLE
Compare HPACK encoder/decoder with Twitter implementation

### ISSUE THREAD

**Issue by nmittler** [netty/netty#3700]
As discussed in https://github.com/twitter/hpack/pull/24#issuecomment-96905226, Twitter has their own HTTP/2 codec with their own hpack [encoder](https://github.com/twitter/netty-http2/blob/master/src/main/java/com/twitter/http2/HttpHeaderBlockEncoder.java) and [decoder](https://github.com/twitter/netty-http2/blob/master/src/main/java/com/twitter/http2/HttpHeaderBlockDecoder.java).  We should compare against the Netty versions for correctness and performance.

**Comment by nmittler** [comment]
Related to issue #2809

**Comment by Scottmitch** [comment]
+1

**Comment by normanmaurer** [comment]
@nmittler is this still needed or can we close this ?

**Comment by nmittler** [comment]
@normanmaurer I think we can close this for now.  Again, hpack doesn't seem to be a hotspot ATM.
