### ISSUE TITLE
Race condition in the ChannelPipeline.

### ISSUE THREAD

**Issue by buchgr** [netty/netty#3702]
We are experiencing a race condition related to the `ChannelPipeline`. The following code has a subtle race that @ejona86 and I found earlier today.

``` java
// This is from outside the event loop. cb = client bootstrap
Channel ch = cb.connect(address).channel();
ch.write(msg);
```

``` java
// This is the code for Channel.write(...)
public ChannelFuture write(Object msg, ChannelPromise promise) {
  AbstractChannelHandlerContext next = findContextOutbound();
  ReferenceCountUtil.touch(msg, next);
  next.invoker().invokeWrite(next, msg, promise);
  return promise;
}
```

So the registration of the channel and the initialization of the pipeline will be done as a task inside the event loop. Also the write to the channel will be done as a task inside the event loop. What's not done inside the event loop is `findContextOutbound()`, but instead it is executed by the calling thread. So what can happen is that `findContextOutbound()` is executed before the pipeline is set up (or while it is being set up), it will thus create a write task with e.g. the `HeadContext` as the `ChannelHandlerContext`.

It's not completely clear to me that this is actually a bug in the pipeline implementation or if this is expected behavior. Is there any reason for not executing the `findContextOutbound()` from within the event loop? @normanmaurer @trustin

**Comment by normanmaurer** [comment]
@trustin thoughts ? Maybe we could defer the findContextOutbound() if the Channel is not registered yet. WDYT ?

**Comment by buchgr** [comment]
@normanmaurer even after the pipeline is set up, the race remains: If a handler is removed, it might not exist anymore at the time the write task is executed, or more general the pipeline might be different at the time the write is executed and new handlers might have been added or removed since the task has been created.

Again, I am not sure if this is a bug or expected behaviour.

**Comment by normanmaurer** [comment]
@trustin WDYT ?

**Comment by normanmaurer** [comment]
This should be fixed in master as all of this is done in the EventLoop.
