### ISSUE TITLE
Remove memory copy when extract frame in LengthFieldBasedFrameDecoder …

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#3704]
Motivation:

We are currently doing a memory cop to extract the frame in LengthFieldBasedFrameDecoder which can be eliminated.

Modifications:

Use buffer.slice(...).retain() to eliminate the memory copy.

Result:

Better performance.

**Comment by normanmaurer** [comment]
Fixed by 4.0 (4c70a99e5a5761d0574f4308be4b6dc371f747df) , 4.1 (891be30a28c6dc5a1edf1cb5a3690644cf4ff66e) and master (4c70a99e5a5761d0574f4308be4b6dc371f747df)

**Comment by slandelle** [comment]
:+1:
