### ISSUE TITLE
Usage of nanoTime

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3705]
The recommended usage to compare two instances of [nanoTime](https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#nanoTime%28%29) is `t1 - t0 < 0` instead of `t1 < t0`.  It has been [suggested](https://github.com/netty/netty/pull/3607#discussion_r29312963) there may be instances where we are not using the recommended approach and may be vulnerable to overflow.  Usage of `nanoTime` needs broader investigation to determine if this is an issue.

**Comment by Scottmitch** [comment]
@normanmaurer - FYI.

**Comment by normanmaurer** [comment]
@Scottmitch thanks will take care!

**Comment by buchgr** [comment]
@Scottmitch ahh that's a very good point. I have just this week been bitten by this and wondered why I got negative deltas :-)

**Comment by slandelle** [comment]
@buchgr You can also have negative deltas because you're measuring start on one core, and end on another one (typically in a callback running in another thread) and cores are not always sync'ed. This is more likely to happen under load.

**Comment by normanmaurer** [comment]
I think we fixed everything here. Lets close this
