### ISSUE TITLE
Channel gets closed before response is consumed

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#3709]
Netty version: 4.1.0-Beta5-SNAPSHOT

Context: 

There appears to be a race condition in Netty 4.1.0-Beta w/ Epoll on Linux where Netty (acting as HTTP client) is closing the connection before it's consuming the response from the server that is waiting for it on the wire.

A very simple self-contained repro is available here:

https://github.com/Squarespace/netty-http-client-test

**Comment by normanmaurer** [comment]
@rkapsi will check...

**Comment by rkapsi** [comment]
Any luck to repro it?

**Comment by normanmaurer** [comment]
Soory had no time yet to try it

**Comment by normanmaurer** [comment]
@rkapsi will check tomorrow morning!

**Comment by normanmaurer** [comment]
@rkapsi thanks! I can reproduce locally :)

**Comment by rkapsi** [comment]
@normanmaurer great, glad to hear that it's reproducible.

**Comment by normanmaurer** [comment]
Would you grant us rights to include your testcode in Netty ? Or some code based on it?

**Comment by rkapsi** [comment]
Yea, just remove the com.squarespace from the pkg name.

**Comment by normanmaurer** [comment]
Awesome :) expect a fix and nee release soon

**Comment by slandelle** [comment]
@normanmaurer Do the other branches experience the issue too?

**Comment by normanmaurer** [comment]
Yes but only SNAPSHOTS with epoll

**Comment by slandelle** [comment]
Ok, thanks!

**Comment by normanmaurer** [comment]
Fixed
