### ISSUE TITLE
HTTP HEAD response generates a body with compression

### ISSUE THREAD

**Issue by naude-r** [netty/netty#3715]
Hi,

This is a similar situation as resolved with #3121. Issue was found with netty 4.0.27, although earlier versions may also have the same issue.

The use case is as follows:
1. netty based http proxy server
2. netty client performs HTTP HEAD
3. back-end (tomcat) returns HTTP HEAD response
4. proxy (HttpClientCodec) generates two response objects:
  - DefaultHttpResponse (with HEAD response), followed by
  - EmptyLastHttpContent

  this can be seen in HttpObjectDecoder::decode (state = READ_HEADER with nextState = SKIP_CONTROL_CHARS)

Ideally HttpContentEncoder::isPassthru should know that it was a HEAD request and passthru all responses.

Sample output:
> HEAD /resource HTTP/1.1
> Host: localhost:8080
> Accept-Encoding: gzip
>
> HTTP/1.1 200 OK
> Server: Apache-Coyote/1.1
> X-Powered-By: Servlet 2.4; JBoss-4.2.3.GA (build: SVNTag=JBoss_4_2_3_GA > date=200807181417)/JBossWeb-2.0
> ETag: W/"2097962-1410528220000"
> Last-Modified: Fri, 12 Sep 2014 13:23:40 GMT
> Date: Thu, 30 Apr 2015 13:07:12 GMT
> Content-Encoding: gzip
> Transfer-Encoding: chunked
>
> 14
> ....................
> 0

Any idea on how to accomplish something like that?

**Comment by normanmaurer** [comment]
@naude-r can you provide a test-case ?

**Comment by naude-r** [comment]
@normanmaurer please see the modified HttpStaticFileServer gist https://gist.github.com/naude-r/1fd5861743fbc2812650

test scenario is as follows:
* ./run-example.sh http-file-server
* curl -0 -v -X HEAD -H 'Accept-Encoding: gzip' http://localhost:8080/pom.xml
* view result with wireshark (output as above)

**Comment by naude-r** [comment]
from http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html:
> 9.4 HEAD
>
>The HEAD method is identical to GET except that the server MUST NOT return a message-body in the response.

**Comment by naude-r** [comment]
@normanmaurer  have submitted PR #3753 as fix for the problem. the fix feels hackish but could not find a better solution.

**Comment by normanmaurer** [comment]
Was fixed via https://github.com/netty/netty/pull/3753
