### ISSUE TITLE
Http2LocalFlowController.consumeBytes should indicate if write occurred

### ISSUE THREAD

**Issue by louiscryan** [netty/netty#3717]
Calls to Http2LocalFlowController.consumeBytes can trigger the generation of a WINDOW_UPDATE to the remote side. Callers of this method need to know if they should flush because an update was sent

**Comment by nmittler** [comment]
+1

**Comment by Scottmitch** [comment]
SGTM. @louiscryan - are you working on a PR?

**Comment by louiscryan** [comment]
Not yet but feel free to assign to me.

**Comment by Scottmitch** [comment]
@louiscryan - I guess I can't assign to you...I'll just keep the assignment for now.

**Comment by Scottmitch** [comment]
@nmittler Merged https://github.com/netty/netty/issues/3723.  I will close this issue.

**Comment by nmittler** [comment]
@Scottmitch thanks, I forgot to close this :)
