### ISSUE TITLE
netty close client connection 

### ISSUE THREAD

**Issue by rjbhewei** [netty/netty#3718]
Netty version: 5.0.0.Alpha2
use this for server test

bossGroup = new NioEventLoopGroup(1);
        workerGroup = new NioEventLoopGroup();
        ServerBootstrap bootstrap = new ServerBootstrap();
        bootstrap.option(ChannelOption.SO_BACKLOG, 1024);
        bootstrap.option(ChannelOption.SO_REUSEADDR, true);
        bootstrap.option(ChannelOption.TCP_NODELAY, true);
        bootstrap.option(ChannelOption.SO_KEEPALIVE, true);
        bootstrap.group(bossGroup, workerGroup).channel(NioServerSocketChannel.class).handler(new LoggingHandler(LogLevel.INFO)).childHandler(new ChannelInitializer<SocketChannel>() {

}

client use asynhttpclient 

client send async request to this server ，but sometime server close the connection

and the client get the  “java.io.IOException: Remotely closed” exception

at the same time ,i find LoggingHandler which log the message  lose same data

for example : client send 100 request  and get 3 “java.io.IOException: Remotely closed” exception
and the LoggingHandler only log 97 "RECEIVED" message in the channelRead method

**Comment by bobwenx** [comment]
maybe related to issue: https://github.com/netty/netty/issues/3709#issuecomment-98141356

**Comment by slandelle** [comment]
@bobwenx Could be. The client is AHC but the user didn't provide enough information, like the version. There was a [bug](https://github.com/AsyncHttpClient/async-http-client/issues/848) that could produce such failure, but it was fixed and release a month ago.

**Comment by rjbhewei** [comment]
![image](https://cloud.githubusercontent.com/assets/8099839/7451722/96e91ce0-f286-11e4-9f93-c56cd340ac3f.png)

**Comment by rjbhewei** [comment]
i find the red frame don't deal the real ，for example client sent 150 request but in the red frame only get the 137

**Comment by slandelle** [comment]
@rjbhewei Do you 150 frames on the server side with Wireshark?

**Comment by rjbhewei** [comment]
AHC version 
<dependency>
            <groupId>com.ning</groupId>
            <artifactId>async-http-client</artifactId>
            <version>1.9.17</version>
        </dependency>

use  like this 
![image](https://cloud.githubusercontent.com/assets/8099839/7451788/6b276cd2-f287-11e4-8dbe-72097ad7d5c7.png)


AHC use 5 thread and one thread loop send async http request  30 count

**Comment by rjbhewei** [comment]
i get the red frame deal num used intellij breakpoints like this 
![image](https://cloud.githubusercontent.com/assets/8099839/7451807/a33c7f40-f287-11e4-8149-32a28548ab6d.png)

**Comment by slandelle** [comment]
@rjbhewei A Java debugger won't tell you what's on the wire.

Then, please read my above comment: there was an issue that was fixed in AHC 1.9.18 (latest is 1.9.20)!

**Comment by rjbhewei** [comment]
but the LoggingHandler only 137 same with the debugger

**Comment by rjbhewei** [comment]
![image](https://cloud.githubusercontent.com/assets/8099839/7451840/13ad2f22-f288-11e4-9692-4b544dd0691c.png)

**Comment by slandelle** [comment]
So what? The client only sent 137 requests because of the mentioned issue.

**Comment by rjbhewei** [comment]
my project server use netty5  which version is 5.0.0.Alpha2  
i use AHC test the server  for pressure test
i use 10 thread and one thread loop 10000 ,i find the netty5 server sametimes had same request, and take exception 
so AHC config builder.setMaxRequestRetry(0); find  "│java.io.IOException: Remotely closed" exception

**Comment by rjbhewei** [comment]
client sent 150 and only get 137

**Comment by slandelle** [comment]
You're getting me nuts. Giving up. Bye.

**Comment by rjbhewei** [comment]
issue example is client send 100  and server get 97
my poject is client send 10 *10000 
and just now i said client send 5*30 and server get 137

**Comment by normanmaurer** [comment]
@rjbhewei please can you move this to the AHC project as this looks more like an AHC bug (if any) then a Netty one.

**Comment by rjbhewei** [comment]
@normanmaurer   https://github.com/AsyncHttpClient/async-http-client/issues/872 is close by @slandelle    
he said mybe server bug  and you said is AHC client bug 
both issues are closed

**Comment by slandelle** [comment]
@normanmaurer @rjbhewei No, I first said that this was a possible normal HTTP behavior because I assumed you properly did some basic checks before reporting an issue:
* check latest version
* check release notes

When you finally provided the version of AHC you were using, I told you [here](https://github.com/netty/netty/issues/3718#issuecomment-98651442) and [in the issue you opened in AHC](https://github.com/AsyncHttpClient/async-http-client/issues/872#issuecomment-98661046) that it WAS a AHC that has already been fixed and that you have to upgrade. Period.

**Comment by rjbhewei** [comment]
@slandelle  check out the latest AHC (2.0.0-SNAPSHOT) version ,the bug still appear

**Comment by rjbhewei** [comment]
i will still find why tomorrow
