### ISSUE TITLE
testsuite-osgi fails on 'mvn package' with no snapshot JARs installed.

### ISSUE THREAD

**Issue by trustin** [netty/netty#3719]
When your local Maven repository has no SNAPSHOT build of Netty installed and you run `mvn package`, testsuite-osgi will fail at the test phase.  It is because the paxexam's `mavenBundle` refers to the bundle as the JAR in the local Maven repository, which was never installed.  The build will fail until 1) a user runs `mvn install` to install the JARs to the local Maven repository, or 2) a user runs `mvn test` in the `testsuite-osgi` directory.

A simple workaround is to make the test run in the `install` phase, but I wonder if there's a better option.

Please note that we had the very same problem when I had to remove the old OSGi testsuite.

**Comment by trustin** [comment]
Another big problem of `testsuite-osgi` is that it tests against the wrong build when a user runs `mvn package`.  It will test with the *old* JARs installed in the local M2 repo.

**Comment by rovarga** [comment]
I am drawing blanks right now, as I will need to delve more deeply into the workings maven/exam to understand how we can refer to the reactor artifacts rather than .m2 ones. I am afraid I won't be able to do that in the next two weeks, though :-(

**Comment by trustin** [comment]
@rovarga No worries. Please take your time. I'll move the test to the `install` phase meanwhile.

**Comment by normanmaurer** [comment]
This was fixed some time ago
