### ISSUE TITLE
http2: writePing does not verify data.readableBytes() == 8

### ISSUE THREAD

**Issue by ejona86** [netty/netty#3721]
When [writing the ping frame](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameWriter.java#L238), we aren't verifying that the length is 8, as required by the spec:
> Receipt of a PING frame with a length field value other than 8 MUST be treated as a connection error (Section 5.4.1) of type FRAME_SIZE_ERROR.

The check [is being performed](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameReader.java#L332) for inbound PING frames.

**Comment by normanmaurer** [comment]
@ejona86 @Scottmitch @nmittler @louiscryan is this something we need to fix before 4.1.0.Final ?

**Comment by nmittler** [comment]
I don't think so. We seem to be conforming to the spec since we're checking the size on the inbound frame.

**Comment by normanmaurer** [comment]
@nmittler so closing ?

**Comment by nmittler** [comment]
@ejona86 thoughts on closing?

**Comment by Scottmitch** [comment]
wouldn't hurt to check the write size...make it harder for people to put bad stuff out on the network.

**Comment by normanmaurer** [comment]
@Scottmitch care to submit a pr ;) ?

**Comment by Scottmitch** [comment]
@normanmaurer - Will do.

@nmittler - Any objections?

**Comment by normanmaurer** [comment]
@Scottmitch :heart_eyes:  ;)

**Comment by Scottmitch** [comment]
pr pending

**Comment by nmittler** [comment]
@Scottmitch no objections ... thanks for taking care
