### ISSUE TITLE
[discussion] libaio implementation on the native layer

### ISSUE THREAD

**Issue by clebertsuconic** [netty/netty#3726]
Linux has a nice kernel module to write and read native files called libaio

This patch will use open(O_direct), Use Native buffers and callbacks on writing files.

**Comment by clebertsuconic** [comment]
I'm looking into doing this, and first thing I noticed is that there is FileDescriptor which will open files, but I need an extra flag (O_DIRECT) on the open.

So, I'm thinking about adding a new native method to FileDescriptor and use the same class.

Any objectios or ideas?

**Comment by Scottmitch** [comment]
@normanmaurer - Can you address this one?

**Comment by clebertsuconic** [comment]
Also: another question I have is... libaio is only available on Linux. is the native module being compiled in other systems other than Linux, and if so, is there a selective compilation option on the scripts? I looked over and I didn't find it.

**Comment by normanmaurer** [comment]
@clebertsuconic yeah this sounds fine to me (about FileDescriptor). I would just put it in the transport-native-epoll module for now which will only be compiles on linux.

**Comment by clebertsuconic** [comment]
@normanmaurer I need to add -laio to the linker on this hawtjni thing.. I will talk to Hiram tomorrow, but meanwhile do you know how to do it? I had to hack the autoconf.ac inside hawtjni to do it... not very easy.

Besides.. it looks like this would be better as a separate package, since it requires libaio.so as a dependency

**Comment by clebertsuconic** [comment]
some conversation I had on netty irc:

[09:45am] clebert: normanm: ping
[09:46am] clebert: normanm: I’m having trouble on changing the build … and do you want to change that build? libaio requires a new lib as a dependency… I’m feeling like this should be another native module
[09:46am] clebert: normanm: I will write this as a new module, using maven-nar that is simpler to tweak… if you want to merge it back later.. we can refactor it..
[09:46am] clebert: at least that will help me progress with the code...
[09:46am] clebert: which I will make something simple in a day or two now...
[09:47am] clebert: I have an idea of the API now.. which will be way simpler than what I had on Artemis / HornetQ
[09:47am] clebert: normanm:  dunno if I should have the native layer calling callbacks in Java yet… I will try to avoid that part



I'm having a lot of trouble on adding -laio for the linker with the current hawt-jni in place... the options are ignored. trying to find a hack now (will talk to Hiram, the author of the hawt-jni)

**Comment by clebertsuconic** [comment]
Update: I had some personal issues so I couldn't work over the weekend.. but doing great progress today.

I'm at the io_submit call already. so I would say 50%/60% done.

I'm doing basically a refactoring of what I had at artemis, but at a lower level.. much cleaner.. and still surviving anything I had as experience (things that I banged my head back then).

will keep updating this as I go.

**Comment by normanmaurer** [comment]
@clebertsuconic thanks for the update!

**Comment by clebertsuconic** [comment]
@normanmaurer  how do you want to go about this:

io_submit, required posix_memalign for ByteBuffer allocations.

It's exactly how I'm doing at Artemis. In the past ByteBuffer.allocateDirect was aligned but for some reason they stopped doing that.

I have written two method on my testcase for that:

public static native ByteBuffer newAlignedBuffer(int size, int alignment);
public static native void freeBuffer(ByteBuffer buffer);

You will need a version of NettyBuffer using these methods or copying before writing (non optimal)


I will do some more work over the next few days and I will need to sync up with you early next week to make some final decisions before I send you the final PR.

**Comment by clebertsuconic** [comment]
a simple SOF answer on this:
https://stackoverflow.com/questions/15605553/read-file-using-libaio-with-o-direct-flag/18760796#18760796

**Comment by clebertsuconic** [comment]
Great news.. got everything working...

will need some testing to make sure there are no leaks... and some exception handling (cleanup some TODOs on my code)...

but all the basics are working... the API is already defined (maybe needs some tidy up).

@normanmaurer let me know when it would be good to make a code review.

**Comment by normanmaurer** [comment]
@clebertsuconic just do a pr and we can start :)

**Comment by clebertsuconic** [comment]
@normanmaurer  PR sent: https://github.com/netty/netty/issues/3726

**Comment by clebertsuconic** [comment]
this should probably be closed.. unless there's still interest around it?

@normanmaurer ?

**Comment by Scottmitch** [comment]
I'll close for now and @normanmaurer can re-open if necessary.

**Comment by clebertsuconic** [comment]
@normanmaurer libaio is doing very well at Artemis BTW. 30% faster than what it used to be on HornetQ. If you ever reconsider this let me know.
