### ISSUE TITLE
HTTP2 should coalesce contiguous received DATA frames

### ISSUE THREAD

**Issue by louiscryan** [netty/netty#3737]
For larger payloads they are often split into 16k chunks based on the max allowed frame size setting. Even if these chunks are contiguous for a stream we report them individually to Http2FrameListener which can cause sub-optimal interactions with the flow-controller if the application returns bytes based on each chunk individually. 

Given a flow-control window of 64k, a caller could immediately issue 4x 16k frames on the wire. If a  recipient proccesses each one separately and returns bytes to the flow controller for each frame received the current implementation will send a WINDOW_UPDATE returning 32k to the remote side after processing the first two frames. If the other side needs to send another 64k it cannot, it sends two 16k frames and receives another 32k back which allows the final two frames to be sent. 

I suggest that if we read a contiguous sequence of frames of the wire for the same stream we treat it as a single DATA frame when reporting up to the application layer which can then release flow-control window in a more efficient fashion. This would also help if the DATA is shipped across a thread boundary.

@nmittler @Scottmitch @ejona86

**Comment by ejona86** [comment]
@louiscryan, in your example, did you intend to say the sender initially sends 3x 16k + 16k-1 ? In your current example as soon as the initial 64k is processed locally WINDOW_UPDATES return the entire 64k, albeit in two 32k WINDOW_UPDATES.

From my current understanding, the request seems misguided and maybe even a mis-feature. You don't want WINDOW_UPDATES to be batchy, as that means you are under-utilizing the network link (you are only using it half the time). Instead, you hope for half the window size to be in transit and the other half to be ACKs going the other direction. Looking at that a different way, if you are able to "receive" 64k all in one read, then either 1) your window size is too small for the network link or 2) you can't keep up with the flow of traffic. Neither problem should be solved by coalescing DATA frames.

Thread boundary optimizations need other solutions, as this solution does not handle merging HEADERS and DATA.

**Comment by louiscryan** [comment]
I think there is still significant benefit here. 

If returning bytes to the flow-controller is being done on the network thread then with the current behavior we will delay the flush of the window update until channelReadComplete so that is already batched. Not only that but consumption of the data frames following the trigger to window update which has now occurred is not acknowledged back to the remote side until another read occurs. 

If returning bytes to the flow-controller is done on a separate thread in a naive / simplistic way (i.e separate call backs per DATA frame read) then we incur separate flushes. In this case I agree timeliness matters with returning bytes as they are processed but the cost of the N context switches and flushes may outweigh any potential end-to-end latency benefit. Benchmarking would be useful to see impact in this case. This would matter for single-payload responses where parsing it as a unit on end-of-stream is the preferred choice.

Largely the proposal here is to address issues where max frame size < window size, Optimization of window size itself is an entirely separate issue.

**Comment by ejona86** [comment]
It seems you are conflating a problem we have in gRPC with a problem in Netty. That seems like it should be solved by our code, and I see nothing that would prevent us from doing so (buffer until channelReadComplete(), then send frames to other thread).

**Comment by ejona86** [comment]
@louiscryan and I discussed offline. He is interested in combining DATA frames when 1) they are contiguous in the same ByteBuf, 2) for the same stream, and 3) later frames are complete. The primary goal is to promote smaller frames into larger frames to gain the lower overhead advantages of larger frames without actually negotiating them. This sounds fine to me, with the above restrictions.

I was mainly concerned this was for multithreading and WINDOW_UPDATE optimization, which would be inappropriate rationale in my mind.

**Comment by louiscryan** [comment]
1 - I was looking at implementing something like a sliced buffer except
that it could represent more than one subsection of the underlying buffer
as CompositeBuffer is a little heavyweight and has different retention
behavior to slice which we are currently using. The alternative as you say
is to broaden the listener interface to receive more than one slice. If
we're open to that API change I could take a look at doing that

2 - Agreed. I think we'll just end up adjusting the connection window size
to compensate

**Comment by Scottmitch** [comment]
@louiscryan - Can you pseudo code the API change(s) you are proposing?

**Comment by louiscryan** [comment]
Instead of coalescing the DATA frames how would folks feel about coalescing the window-updates on flush? i.e. returning bytes to the flow-controller doesn't trigger a write of a window update immediately, instead the controller is marked stale, if more bytes are returned then it just accumulates until its told to flush a window update.

In the typical case where we process all reads (and return of their associated bytes) in the event loop this would work pretty well.

**Comment by Scottmitch** [comment]
@louiscryan - Sounds reasonable.  So are you suggesting adding another method onto the flow controller which does something like `writeAndFlushAccumulatedWindowUpdates`?  Then we will allow users to call this, and we will call it by default when we are flushing?

**Comment by louiscryan** [comment]
Yup, something along those lines. I want to run some benchmarks first to
see if that kind of change has any meaningful benefit vs varying the window
update ratio.

**Comment by normanmaurer** [comment]
I think this is done... @louiscryan please reopen if this is not the case.
