### ISSUE TITLE
JRuby subclass of SimpleChannelInboundHandler erases generics information; no other way to specify I

### ISSUE THREAD

**Issue by nelsnelson** [netty/netty#3747]
Netty version: 4.0.27.Final

Context:
Because JRuby erases generics information, the `TypeParameterMatcher` instance for `SimpleChannelInboundHandler` cannot appropriately determine how to handle an inbound message.  Instead, the inbound message parameter apparently defaults to an instance of `SimpleLeakAwareByteBuf`.

Even if I override `SimpleChannelInboundHandler#acceptInboundMessage(...)` to use a different `TypeParameterMatcher` instance, I still cannot get anything other than a `SimpleLeakAwareByteBuf` instance in the `messageReceived` method.

Steps to reproduce:
1. Use the `io.netty.example.telnet.TelnetServer`.
2. Port to JRuby.
3. Override `SimpleChannelInboundHandler#acceptInboundMessage(...)`.
4. In `#accept_inbound_message`, print the class of the inbound message.

$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

$ jruby --version
jruby 1.7.16 (1.9.3p392) 2014-09-25 575b395 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14 +jit [darwin-x86_64]

Operating system: MacOS X Version 10.10.3 (Yosemite)

$ uname -a
Darwin sol.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

My system has IPv6 enabled.

**Comment by normanmaurer** [comment]
@nelsnelson can you show us how you init your ChannelPipeline ?

**Comment by nelsnelson** [comment]
DECODER = StringDecoder.new
    ENCODER = StringEncoder.new

    def initChannel(ch)
      pipeline = ch.pipeline()

      ssl_handler = @sslCtx.newHandler(ch.alloc()) if @sslCtx
      pipeline.addLast(ssl_handler) if ssl_handler
      # Add the text line codec combination first,
      pipeline.addLast(DelimiterBasedFrameDecoder.new(8192, Delimiters.lineDelimiter()))
      # the encoder and decoder are static as these are sharable
      pipeline.addLast(DECODER)
      pipeline.addLast(ENCODER)

      # and then business logic.
      pipeline.addLast(self)
    end

The business logic handler is of course, ```self```, which extends ```SimpleChannelInboundHandler```.

**Comment by normanmaurer** [comment]
unfortunately there is nothing we can do I think :(
