### ISSUE TITLE
Bad design of AbstractEpollStreamChannel spliceTo

### ISSUE THREAD

**Issue by WhiteTrashLord** [netty/netty#3760]
The new spliceTo functions seem to be cool but I don't like the current design.
The offset and len parameters should be long instead of int. Some crazy dudes might want to transfer several GB of data, or not?
I also don't like the use of Integer.MAX_VALUE to copy infinitely. You might create a new constant EpollStreamChannel.INFINITE_TRANSFER which is -1 or something like that. Or maybe a spliceTo function without a len param can do the same.
In case I use this new sliceTo stuff I would also like to have a ChannelProgressiveFutureListener. Or it's already supported?

**Comment by Scottmitch** [comment]
@normanmaurer - I will assign to you...just some thoughts...

1. length data type we expose - [splice](http://man7.org/linux/man-pages/man2/splice.2.html) supports a `size_t` length and for linux we *should* be able to use a `jlong` for this.
2. Using `Integer.MAX_VALUE` for indefinite splice -  I agree we should not use a legitimate value from the input domain as special meaning.

**Comment by normanmaurer** [comment]
@WhiteTrashLord thanks for the feedback. I think it makes sense, let me come up with something :)

**Comment by doom369** [comment]
I also have a question here :
Why "Both channels need to be registered to the same EventLoop"? Is that because of performance reasons or because of netty design?

I have a scenario in which I have a proxy that forwards messages between two event loops...

**Comment by normanmaurer** [comment]
I think we should just drop it for 5.0

**Comment by normanmaurer** [comment]
This was dropped for 5.0
