### ISSUE TITLE
errors decoding cached records in DNS resolver/codec (IP address from A records)

### ISSUE THREAD

**Issue by dmk23** [netty/netty#3761]
#### Netty Version
4.1.0.Beta5 (using latest code/API per https://github.com/netty/netty/commit/63a02fc04e6ce45aee38b0437ae0279880e5fe40 @trustin )

#### Context
I've been trying to use the new DNS resolver on a mix of MX and A records together. While there is a great example for MX resolution (in here https://github.com/netty/netty/blob/netty-4.1.0.Beta5/resolver-dns/src/test/java/io/netty/resolver/dns/DnsNameResolverTest.java ), it was not clear how to extract actual IP records after A queries. In our example we've used this line to submit an A query:

```
resolver.query(new DefaultDnsQuestion(mx_host, DnsRecordType.A)).addListener(this);
```
and this one to extract the IP address from the response
```
try {
    mx_ips.add(InetAddresses.fromInteger(recordContent.readInt()));
} catch (Exception ex) {
    System.out.printf("%s : %s : %s", name, ttl, r);
    ex.printStackTrace();
}
```
This code worked without a hitch for a small list of 4 domains, but with ~20 domains we've been getting the errors below, repeating a variable number per run (from 0 to ~5)

#### Step to Reproduce
This seems to be one of those hard-to-reproduce issues, because the execution is non-deterministic. We load the list of domains to resolve MX and then find A records for each of the MX hosts. Everything is handled by the same listener object (vs. LinkedHashMap in DnsNameResolverTest), so the order of domains DNS answer processing is always random. Notably though, all errors happen when looking up A records for Gmail MX hosts and these MXes repeat several times in our test list of domains.

Here is an example output:

```
alt1.aspmx.l.google.com : 292 : DefaultDnsRawRecord(alt1.aspmx.l.google.com 292 IN A 0B)java.lang.IndexOutOfBoundsException: readerIndex(57) + length(4) exceeds writerIndex(57): DuplicatedByteBuf(ridx: 57, widx: 57, cap: 4096, unwrapped: PooledUnsafeDirectByteBuf(ridx: 68, widx: 68, cap: 4096))
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1139)
        at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:592)
        at com.ourapp.Domain$ResolverBatch.operationComplete(Domain.java:353)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
        at io.netty.util.concurrent.DefaultPromise.notifyListener(DefaultPromise.java:653)
        at io.netty.util.concurrent.CompleteFuture.addListener(CompleteFuture.java:49)
        at com.ourapp.Domain$ResolverBatch.operationComplete(Domain.java:334)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:567)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
        at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:821)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:946)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:744)

```
Here is the list of domains we used:
```
        String[] DOMAINS = new String[] {
                "GMAIL.com",
                "yahoo.com",
                "aol.com",
                "live.com",
                "hao123.com",
                "sina.com.cn",
                "blogspot.com",
                "weibo.com",
                "yahoo.co.jp",
                "tmall.com",
                "yandex.ru",
                "sohu.com",
                "bing.com",
                "ebay.com",
                "pinterest.com",
                "vk.com",
                "google.de",
                "wordpress.com",
                "apple.com",
                "google.co.jp",
                "google.co.uk",
        };
```

#### Likely Root Cause
We noticed that the problem happened for A records that were repeated several times in the input and therefore on the second run would be read / decoded from cache. This seemed consistent with the fact that the error message said the buffer is at its end.

To test this theory we tried to disable the resolver cache (with ```resolver.setTtl(0, 0);```) and observed the problem going away completely. Apparently once the record is decoded for the first time it needs to be reset and it is not clear how to do this. We tried ```recordContent.clear();``` but that caused exceptions even on the first read.

Seems like some input for improving the codecs and making them cache-compatible...

#### Environment
[root@localhost]# java -version
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)

[root@localhost]# uname -a
Linux localhost 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@trustin can you check ?

**Comment by trustin** [comment]
Will take a look.

**Comment by trustin** [comment]
A workaround could be to use `ByteBuf.getInt()` instead of `readInt()`:

    InetAddresses.fromInteger(recordContent.getInt(recordContent.readerIndex()))

@dmk23, could you try it and let me know if this fixes your problem?

**Comment by dmk23** [comment]
How would ByteBuf.getInt() find the right index to read? Seems to me once the buffer has been read once it is stuck at the end and needs to be reset somehow before the cached record is re-read?

Sorry, if I am missing something I just started working with Netty this week :)

**Comment by trustin** [comment]
Because we specified the index? - recordContent.getInt(**recordContent.readerIndex()**)

Also, please note that `getInt()` does not update the reader index of the buffer. So, unless you changed the reader index of the content, it should not change.

**Comment by dmk23** [comment]
Thanks for the solution/explanation - your fix worked for the A record.

**However** the same fix **WON'T** work for cached MX records which require two separate reads of the MX pref and the hostname. One way to deal with this issue would be to manually move the index back after the hostname read, but this really complicates the application code.

I think this issue should be at the very least about documentation and enhancement of the test code (right now the only way to find examples of the Netty DNS use).

But ideally the API should be improved to avoid having to pull DNS values out of raw records by hand and worry about the indices being moved around and being invalid next time record is read from cache...

Finally, seems to me that these index movements are going to fail in concurrent environment, so the client implementation should take care of thread-safety as well...

**Comment by trustin** [comment]
Thank you for the confirmation. Let me come up woth a proper fix.

--
https://twitter.com/trustin https://twitter.com/trustin_ko
https://twitter.com/netty_project


On Fri, May 15, 2015, at 09:24 PM, dmk23 wrote:
> Thanks for the solution/explanation - your fix worked for the A
> record.


> *However* the same fix *WON'T* work for cached MX records which
> require two separate reads of the MX pref and the hostname. One way to
> deal with this issue would be to manually move the index back after
> the hostname read, but this really complicates the application code.


> I think this issue should be at the very least about documentation and
> enhancement of the test code (right now the only way to find examples
> of the Netty DNS use).


> But ideally the API should be improved to avoid having to pull DNS
> values out of raw records by hand and worry about the indices being
> moved around and being invalid next time record is read from cache...


> Finally, seems to me that these index movements are going to fail in
> concurrent environment, so the client implementation should take care
> of thread-safety as well...


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/netty/netty/issues/3761#issuecomment-102385459

**Comment by trustin** [comment]
I encountered a little bit of complexity problem while trying to fix this issue. Will try again soon.

**Comment by kkuehl** [comment]
I have a related DnsRecord decoding question.
I am attempting to decode PTR record responses.

The DnsRecord does not expose rlength or rdata (yet) which would allow me to know how to read the ByteBuf content.

**Comment by trustin** [comment]
@kkuehl Down-cast it to `DnsRawRecord` and get the content.

**Comment by kkuehl** [comment]
Here is an example dig result
$ dig -x 97.74.197.162 

; <<>> DiG 9.10.2-RedHat-9.10.2-1.fc22 <<>> -x 97.74.197.162
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39610
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4000
;; QUESTION SECTION:
;162.197.74.97.in-addr.arpa.	IN	PTR

;; ANSWER SECTION:
162.197.74.97.in-addr.arpa. 3600 IN	PTR	ip-97-74-197-162.ip.secureserver.net.

;; Query time: 90 msec
;; SERVER: 10.150.1.8#53(10.150.1.8)
;; WHEN: Tue Jun 30 13:15:10 PDT 2015
;; MSG SIZE  rcvd: 105


Here is the snipped when I try to get the resolved hostname:

 DnsResponse response = envelope.content();
 final int answerCount = response.count( DnsSection.ANSWER );
  final DnsRawRecord s = (DnsRawRecord) response.recordAt( DnsSection.ANSWER, 0 );
 System.out.printf( "Raw: %s\n", s.content().toString());

And the output of the printf.

Raw: DuplicatedByteBuf(ridx: 57, widx: 85, cap: 4096, unwrapped: PooledUnsafeDirectByteBuf(ridx: 125, widx: 125, cap: 4096))


 DefaultDnsRawRecord(206.171.222.162.in-addr.arpa 37594 IN PTR 16B)

As you can see, I dont get 	ip-97-74-197-162.ip.secureserver.net

**Comment by trustin** [comment]
@kkuehl What you got is a `ByteBuf`. You need to decode it by yourself. Just doing `toString()` won't do that.

**Comment by trustin** [comment]
Should be fixed already - the cache in `DnsNameResolver` does not cache a `DnsResponse` anymore. It just caches the resolved `InetAddress` only.
