### ISSUE TITLE
Buffered streams for OIO

### ISSUE THREAD

**Issue by jesperpedersen** [netty/netty#3762]
Currently OioSocketChannel doesn't make use of buffered streams which could benefit performance (https://github.com/netty/netty/blob/master/transport/src/main/java/io/netty/channel/socket/oio/OioSocketChannel.java#L80 and https://github.com/netty/netty/blob/master/transport/src/main/java/io/netty/channel/socket/oio/OioSocketChannel.java#L200).

However, just wrapping these method calls causes test failures, so there is more to it.

https://github.com/jesperpedersen/pgjdbc-ng/tree/oio can be used for testing with -Dpgjdbc-ng.transport=oio defined, see README.md for more options (Netty 4.0 based).

Thanks for considering.

**Comment by normanmaurer** [comment]
I think we are not consider OIO as performance critical and focus on nio and native transports. Let me close this as won't fix.
