### ISSUE TITLE
HTTP/2 examples doesn't work with Chrome 42.0.2311.135 (64-bit) on OSX 10.10.3 , Java  1.8.0_45-b14 , Netty 5.0.0.Alpha3-SNAPSHOT 

### ISSUE THREAD

**Issue by bobymicroby** [netty/netty#3765]
The request stays as "pending"  forever

![image](https://cloud.githubusercontent.com/assets/927575/7539825/5457c9ba-f5b2-11e4-96d0-a5620b54ef8b.png)

The debug output:
May 08, 2015 6:45:27 PM io.netty.handler.logging.LoggingHandler channelRead
INFO: [id: 0x4d9163c8, /0:0:0:0:0:0:0:0:8080] RECEIVED: [id: 0x2e91accb, /127.0.0.1:64231 => /127.0.0.1:8080]

--------------------------------------------------------------

But the http2 client that is provided in the examples works flawlessly.

Hello World
---Stream id: 3 received---
Finished HTTP/2 request(s)

**Comment by Scottmitch** [comment]
@bobmcwhirter - Thanks for reaching out!

What flags are you starting chrome with?  Are you starting the example with the `-Dssl` flag?

**Comment by normanmaurer** [comment]
@Scottmitch it's @bobymicroby ;)

**Comment by Scottmitch** [comment]
In order for the example to work with chrome you will have to change Netty's http2 ALPN token from [h2-17](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2CodecUtil.java#L39) to `h2-14`.

**Comment by bobymicroby** [comment]
@Scottmitch No ssl,  the netty build is from master. I was expecting that Http2OrHttpHandler to select http 1 protocol if unable to upgrade.  Where do  you suggest me to implement the  fallback logic ?

**Comment by Scottmitch** [comment]
@bobymicroby - I observe the same behavior without `-Dssl` option when starting the `http2-server` example. However with the `-Dssl` option I am able to negotiate to `HTTP_1_1` (if I change nothing) and able to negotiate to `HTTP_2` if I change the version to `h2-14`.  I'm not sure that chrome or firefox support clear text mode for HTTP/2.  I think the reason why you are seeing the client example work is because we do support clear text mode.

**Comment by bobymicroby** [comment]
@Scottmitch Don't you think its best always to revert to http 1 if you cannot negotiate 2 ?

**Comment by Scottmitch** [comment]
@bobymicroby - Good point. Even though the example is to demonstrate HTTP/2 functionality I guess we should send some kind of response for http only clients.  I'll put together a PR.

**Comment by bobymicroby** [comment]
@Scottmitch Something like  " Hello old world. I was unable to negotiate a good protocol upgrade, but at least your request got served "   :)

**Comment by Scottmitch** [comment]
@bobymicroby - See #3793

**Comment by Scottmitch** [comment]
Fixed 4.1 (04c0d77, c6d61f9) master(37e6fd0)
