### ISSUE TITLE
HttpPostRequestEncoder incorrect "charset=charset" definition on Android

### ISSUE THREAD

**Issue by nibuen** [netty/netty#3768]
When using HttpPostRequestEncoder and trying to set an attribute if a charset is defined it attempts to set the definition of charset like so:

                internal.addValue(HttpHeaderNames.CONTENT_TYPE + ": " +
                        HttpPostBodyUtil.DEFAULT_TEXT_CONTENT_TYPE + "; " +
                        HttpHeaderValues.CHARSET + '='
                        + localcharset + "\r\n");

which on android gives a toString definition like this for example: "com.ibm.icu4jni.charset.CharsetICU[UTF-16]" which is unusable by HttpPostMultipartRequestDecoder.

It seems that instead localcharset.name() should be used instead like so (which would give "UTF-16"):

                internal.addValue(HttpHeaderNames.CONTENT_TYPE + ": " +
                        HttpPostBodyUtil.DEFAULT_TEXT_CONTENT_TYPE + "; " +
                        HttpHeaderValues.CHARSET + '='
                        + localcharset.name() + "\r\n");

**Comment by normanmaurer** [comment]
@fredericBregier could you check ?

**Comment by fredericBregier** [comment]
@normanmaurer I propose a fix (master branch, but all branches concerned).
@nibuen Nice catch !

**Comment by normanmaurer** [comment]
Fixes merged in
