### ISSUE TITLE
SslContextBuilder has conflicting conditions in keyManager(...)

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#3775]
The `keyManager(File, ...)` and `keyManager(KeyManagerFactory)` methods have conflicting conditions for the server SslContextBuilder.

Or SslContextBuilder is missing an argument-less `forServer()` method.

```
SslContextBuilder.forServer(null, null)
    .keyManager(myKeyManagerFactory)
    .build();
```

```
java.lang.NullPointerException: keyCertChainFile required for servers
	at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:31)
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:129)
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:115)
	at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:44)
```

**Comment by normanmaurer** [comment]
@ejona86 can you check ?

**Comment by ejona86** [comment]
There should be a `SslContextBuilder.forServer(KeyManagerFactory)` but it is missing. Workaround is to provide any `File` (doesn't need to exist) to `forServer()` and then change the configuration.

```
SslContextBuilder.forServer(new File("foo"), new File("foo"))
    .keyManager(myKeyManagerFactory)
    .build();
```

I'll create a PR to add the missing method.

**Comment by normanmaurer** [comment]
@ejona86 :beers: on me ;)

**Comment by ejona86** [comment]
@normanmaurer, I have discovered the method of getting :beers:: introduce bugs, then fix the bugs. :-)

**Comment by normanmaurer** [comment]
@ejona86 lol
