### ISSUE TITLE
Strange error when using OpenSSL with Netty and mutual SSL

### ISSUE THREAD

**Issue by doom369** [netty/netty#3779]
Hello,

I have service with hundreds of mobile users and all works fine during long term run, but sometimes I see in logs 

```
Reason : javax.net.ssl.SSLHandshakeException: error:140940E5:SSL routines:SSL3_READ_BYTES:ssl handshake failure 
```

Do you aware of what that could be?  The all info I have - users connected through 3g. So maybe slow connection could be an issue?

Netty 4.0.28.Final.

**Comment by normanmaurer** [comment]
@doom369 this most likely means that the user either send bad data or dropped the connection during handshake.

**Comment by jknair** [comment]
@normanmaurer is the following exception also when the user has sent bad data or dropped the connection 
```
 SSL_read failed: primingReadResult: -1; OpenSSL error: 'error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error'
```

there seems to be a bug reported : https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/861137

Tried using only ```"RC4-SHA"``` as the cipher as suggested in the posts in the above link but have not been able to rectify this
