### ISSUE TITLE
ChannelInitializer does not propagate Exceptions

### ISSUE THREAD

**Issue by zoowar** [netty/netty#3780]
Netty version: 5.0.0.Alpha2 (but others as well)

Context:
When an exception occurs in a user defined initChannel, it is not propagated through the framework so that it can be handled with exceptionCaught. Instead, channelRegistered logs a warning and dumps a stack trace.

Steps to reproduce:
Throw a generic exception in an initChannel from the netty examples should do the trick.

**Comment by normanmaurer** [comment]
@zoowar the question is how we should propagate here as if initChannel(...) throws an exception chances are good that you will not have an handler in the pipeline that can handle the exception.

**Comment by zoowar** [comment]
@normanmaurer When there is no exceptionCaught implemented by any of the pipeline handlers, the framework handles the exception by logging the following message:
> i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

It seems to me that ChannelInitializer/channelRegistered could log the specialized message ""Failed to initialize a channel." and throw the exception, which will be handled by the default handler or the user defined handler.

I'm not a java programmer, so the only question in my mind is how does the context get closed when an exception occurs in ChannelInitializer? Does it get closed in the default exceptionCaught path? If it doesn't, then ChannelInitializer could override exceptionCaught and close the context. Then document that users who wish to override ChannelInitializer/exceptionCaught must close the context.

**Comment by trustin** [comment]
I like the idea of letting `ChannelInitializer.channelRegistered()` propagate the exception so that `ChannelInitializer.exceptionCaught()` closes the connection by default.  That way, a user can override the default behavior.

**Comment by normanmaurer** [comment]
Let me fix this

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/3931
