### ISSUE TITLE
Openssl internal error:14077438 when using client mode 

### ISSUE THREAD

**Issue by jknair** [netty/netty#3782]
Openssl handshake exceptions when using client mode netty master @ 153a9c3
```
 SSL_read failed: primingReadResult: -1; OpenSSL error: 'error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error'
```
There seems to be a bug reported : https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/861137
Tried using only ```"RC4-SHA"``` as the cipher as suggested in the posts in the above link but have not been able to rectify this .
This was also seen when used with curl but the curl seems to be working without any cipher or turning on sslv3. So I am guessing this could be a netty bug.
Is the following exception also when the user has sent bad data or dropped the connection  ?

```
java version "1.8.0_20"
Debian 3.2.65
```

**Comment by Scottmitch** [comment]
@normanmaurer - I'll assign to you for now.

**Comment by jknair** [comment]
@normanmaurer ping

**Comment by normanmaurer** [comment]
@jknair can you provide a unit test or a reproducer ?

**Comment by normanmaurer** [comment]
I wonder if this may be related to #3893

**Comment by normanmaurer** [comment]
@jknair please reopen if you still see this
