### ISSUE TITLE
Certificate hostname verification with OpenSSL

### ISSUE THREAD

**Issue by ejona86** [netty/netty#3784]
Since `newEngine(ByteBufAllocator, String, int)` [isn't implemented for OpenSSL](https://github.com/netty/netty/blob/master/handler/src/main/java/io/netty/handler/ssl/OpenSslContext.java#L291) it seems that OpenSSL can't do hostname verification.

Is that correct? Is the hostname supposed to be provided some other way?

If so, that seems a major issue for client-side usage. It seems like SslContext _should not_ have it [as the defaultClientProvider](https://github.com/netty/netty/blob/master/handler/src/main/java/io/netty/handler/ssl/SslContext.java#L106) and it should have big huge warnings, or even [throw an exception during creation if in client mode](https://github.com/netty/netty/blob/master/handler/src/main/java/io/netty/handler/ssl/OpenSslContext.java#L139).

**Comment by normanmaurer** [comment]
@ejona86 seems like it possible with openssl 1.0.2 and later:

https://wiki.openssl.org/index.php/Hostname_validation

Is this what you are looking for ?

**Comment by normanmaurer** [comment]
@ejona86 also look at the link, there is even a version which can be used pre- 1.0.2 versions, but not support wildcards. WDYT ?

**Comment by normanmaurer** [comment]
@ejona86 actually the hostname check stuff should be done as part of the X509TrustManager. So this should be relative easy to fix ... Stay tuned.

**Comment by normanmaurer** [comment]
@ejona86 please check https://github.com/netty/netty/pull/3794

**Comment by normanmaurer** [comment]
Fixed.

**Comment by nmittler** [comment]
@normanmaurer what is the release plan going forward for the 4.1 branch? Are you expecting to release new betas more regularly? I'd love to see this fix in a beta release.

**Comment by normanmaurer** [comment]
@nmittler yep :) Let me try to do one over the next week,

**Comment by nmittler** [comment]
awesome! :)
