### ISSUE TITLE
HTTP/2 and HPACK published as RFCs (proposed standards)

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3787]
HTTP/2 - https://tools.ietf.org/html/rfc7540
HPACK - https://tools.ietf.org/html/rfc7541

We should investigate the deltas and update code as necessary.

**Comment by Scottmitch** [comment]
@nmittler - I just reviewed the HTTP/2 RFC and didn't find any changes. I have a PR pending which just updates the version info.  Have you looked at the RFC?  The only section that looks like "changes" were made was the GO_AWAY section, but I don't think there were any real changes after our last discussions with the spec maintainers.

**Comment by nmittler** [comment]
@Scottmitch I just scanned through the RFC and my take-away is the same as yours.  I think we're good.

**Comment by normanmaurer** [comment]
@Scottmitch I think this can be closed, right ?

**Comment by Scottmitch** [comment]
@normanmaurer - Yip.
