### ISSUE TITLE
Cookie EXPIRES encoding subject to int overflow for reasonable maxAge

### ISSUE THREAD

**Issue by jxtps** [netty/netty#3796]
Currently, [line 96 in ServerCookieEncoder.java](https://github.com/netty/netty/blob/fb6eae15911790f2af89254b16765c33b05515a5/codec-http/src/main/java/io/netty/handler/codec/http/cookie/ServerCookieEncoder.java#L96) reads: 

`Date expires = new Date(cookie.maxAge() * 1000 + System.currentTimeMillis());`

However, cookie.maxAge() is an int, and multiplying it by 1000 risks integer overflow (when, for example `maxAge = 30*24*60*60`, a not unreasonable maxAge), thereby unintentionally setting the EXPIRES cookie header to a value in the past. 

To fix this, just add "L" to the 1000 to make it a long: 

`Date expires = new Date(cookie.maxAge() * 1000L + System.currentTimeMillis());`

(Updated to fix formatting)

**Comment by slandelle** [comment]
Seems legit

**Comment by jxtps** [comment]
Some math to save people the trouble: 

`30*24*60*60 = 2592000`
`30*24*60*60*1000 = -1702967296`

`30*24*60*60*1000L = 2592000000`

The longest duration cookie you can currently encode is about 24 days into the future: `2^31 / (24*60*60*1000) = 24.855`

**Comment by slandelle** [comment]
Actually, no, this issue can be rejected: maxAge is a long since 4.0.
It's only an int in older versions, and this was already fixed as of #3777.

**Comment by jxtps** [comment]
Ah. Ok. Well, v3.9.8 that is used by Play v2.3.9 most unfortunately has the problem.

**Comment by jxtps** [comment]
(Also, adding the L to the 1000 is probably not a bad idea regardless)

**Comment by normanmaurer** [comment]
So I think this was fixed
