### ISSUE TITLE
IllegalReferenceCountException in DNS resolver

### ISSUE THREAD

**Issue by dmk23** [netty/netty#3797]
#### Netty Version
4.1.0.Beta5 (using latest code/API per https://github.com/netty/netty/commit/63a02fc04e6ce45aee38b0437ae0279880e5fe40 @trustin )

#### Context
Continuing to test the DNS resolver, now trying a very high volume of queries. We have experienced a reference counting exception while submitting queries to the resolver:

```
[root@localhost]# java com.ourapp.smtp.Domain
Exception in thread "main" io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1
        at io.netty.util.AbstractReferenceCounted.retain(AbstractReferenceCounted.java:57)
        at io.netty.handler.codec.dns.AbstractDnsMessage.retain(AbstractDnsMessage.java:367)
        at io.netty.handler.codec.dns.DefaultDnsResponse.retain(DefaultDnsResponse.java:163)
        at io.netty.handler.codec.dns.DatagramDnsResponse.retain(DatagramDnsResponse.java:170)
        at io.netty.handler.codec.dns.DatagramDnsResponse.retain(DatagramDnsResponse.java:26)
        at io.netty.resolver.dns.DnsNameResolver.query(DnsNameResolver.java:689)
        at io.netty.resolver.dns.DnsNameResolver.query(DnsNameResolver.java:662)
        at com.ourapp.smtp.Domain$ResolverBatch.process(Domain.java:304)
        at com.ourapp.smtp.Domain.main(Domain.java:466)
```

The line submitting the query is quite straightforward and I'd think no call to `query` should ever cause any exceptions like the one above.

```
resolver.query(new DefaultDnsQuestion(domain, DnsRecordType.MX)).addListener(this);
```

#### Step to Reproduce
There is not much more to go on here, since we are just running a large list of domains processed in random order - and we have not yet instrumented more detailed reporting of the context that caused this specific exception. So really we should just think what could be causing this sort of error in principle.

One possibility might be short max cache lifetime, per this setup:

```
        resolver.setTtl(0, 300);
```
Our resolver job is believed to have run in excess of 5 min and it is possible that some records were evicted from cache in a way that made the reference counts inconsistent. I have not reviewed the code base in depth to think of further details - wanted to share the error for discussion first.

#### Environment
[root@localhost]# java -version
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)

[root@localhost]# uname -a
Linux localhost 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by dmk23** [comment]
More findings to report.

We confirmed that the error happens only for repeatedly queried domains that re-occurred in our input (e.g. hotmail.com, gte.com) - so this has to be a bug in the cache. The errors happened within the timeframe way under DNS record's TTL - when these records should be looked up....

With duplicates removed from the input or the cache disabled (with ```resolver.setTtl(0, 0);```) all these exceptions go away. Our own solution is to disable the cache (which consumes way too much RAM anyways) but seems like this is something worth reviewing / fixing...

**Comment by trustin** [comment]
@dmk23 Thank you very much for reporting. Let me take care of this.

**Comment by trustin** [comment]
Should be fixed by 311532f (4.1) and c72082e (master).  Could you please check, @dmk23?

**Comment by dmk23** [comment]
I'll take a look at some point.

But based on the sum of our testing, we've disabled the Netty DNS cache in favor of our own, application-specific, that only keeps the data we need it tighter data structures

The object creation / memory consumption seems just too much - we got a very big boost in both resolver speed, memory footprint and reliability by simply turning the cache off...

**Comment by trustin** [comment]
Thanks for sharing your story.  That's helpful and it's always good to hear the bad news sooner.  And, it's also great to know it at least meets your expectation once cache is off. :-)  Would you mind if I ask you some numbers related with the resolver? E.g. dns queries / sec, # of event loop, machine & environment .. and maybe use cases

The current cache implementation caches the whole DNS question and
response, and it's often unnecessary.  Have you thought about how we
could improve its efficiency?

Oh, and I wonder what you thought about the overall API design. Was it
easy to use? Was there any impedence mismatch between the API and the
DNS protocol? What could we do to improve it even further?

**Comment by dmk23** [comment]
Let me answer in the order of easiness / definiteness :)

1. The issue with DNS protocol API is lack of ready-to-go methods for extracting records. So implementing it was all about looking up the examples and copying code from there (and running into issues like discussed here https://github.com/netty/netty/issues/3761). We still have not tried to extract other types of records (TXT for example) - and those I have not seen in examples either. As far as designing the API - I'd recommend to minimize object creation as it gets pretty bad on scale.

2. Regarding caching, without being familiar with all parts of Netty it seems to me that maintaining a *large* cache of records is rather unique to DNS use case (within the Netty world). With most other applications / protocols, objects / buffers are quickly cycled through and reused, so the efficiency of their representation and lookup might not be as critical. Creating / storing any Java object involves massive overhead and DNS cache seems to have layers and layers of nested small objects (questions, answers, sections, futures, envelopes, etc). We've seen the process with 1M domain records loaded growing to ~3.5G RAM (shunk to ~2.5G with Netty DNS cache disabled). So my suggestion would be to first design a more efficient in-memory data store (perhaps under io.netty.util) and then build a DNS cache on top of it. Here is one project / design approach that we are evaluating for our projects right now: http://www.mapdb.org/ (with great explanation of the use case here: http://kotek.net/blog/3G_map)

3. Now regarding the actual benchmarks, I do not have them documented rigorously other than seeing the memory consumption difference above and noticing about ~50-100% speed up in resolver just by turning off the cache. It is hard to design apples-to-apples comparisons here for several reasons including:

 - Number of concurrent DNS resolutions (at some point running into OS limits?)
 - The differences in synchronization methods used to feed the queue that submits to resolvers (we have not compared them extensively)
 - Severe rate limits on public resolvers we've been using (that we've sidestepped by using lot of public resolvers)
 - Subtleties in application design / use of Netty that influence the number of temporary objects created / GC'd (with possible memory leaks everywhere)

4. Our use case is to run DNS intelligence / analytics on the large scale. We've gotten the performance to resolving ~1M queries in ~3 min on a box with just 2 cores, EPoll event loop with default thread count, 50K concurrent queries and ~3K public DNS resolvers. Interestingly, bumping concurrency to 100K dropped the performance by about half - I suppose it might have something to do with low-level system settings for our CentOS 6.5 (probably address / port reuse settings), which we have not looked into deeply yet. I should also note that this has not saturated the CPU, so the workload seems to be bound by either network / resolver or perhaps memory bus.

In terms of practical suggestions for DNS cache in Netty - I do not see an easy / quick fix here... Doing it "properly" may involve designing something like MapDB (per links above) or adopting some of its concepts to use existing Netty framework / primitives. The key is compact storage of everything, aggregating lots of small objects in large buffers and providing efficient enough ways to look them up. This definitely looks like "major release" material...

Hope this helps.

**Comment by trustin** [comment]
@dmk23 Thanks for sharing your story! Record extraction should be implemented before the final release, and let's see if I can fix the cache before then. :-)
