### ISSUE TITLE
Change access level of LoggerHandler.formatByteBuf() to public

### ISSUE THREAD

**Issue by flirtomania** [netty/netty#3798]
##### Netty version: 5.0.0.Alpha2

When using as a generic library (especially ByteBufs) to see the contents of it it'd be nice to have some  convenient API to print out ByteBuf's content like LoggingHandler does.

Also it seems that Unppoled.java has incorrect javadoc about hex dumps.
...This class also provides various utility methods to help implementation
of a new buffer type, generation of hex dump and swapping an integer's
byte order...

There's actually no such methods. In 5.0.0.Alpha2

**Comment by trustin** [comment]
It's probably a good idea to add a similar method to `ByteBufUtil`?

**Comment by normanmaurer** [comment]
@trustin @flirtomania +1

**Comment by normanmaurer** [comment]
Fixed
