### ISSUE TITLE
proposal: rename package for netty 5

### ISSUE THREAD

**Issue by rzorzorzo** [netty/netty#3799]
given that code written for netty 4 will not run with netty 5 i recommend to rename the package to io.netty5. Similarly to apache commons lang.

**Comment by sksamuel** [comment]
It will certainly be useful when you look at examples in the future to know which version they were written for.

**Comment by hotbain** [comment]
maybe ,the comments will be more useful than that way

**Comment by johnou** [comment]
And what happens with Netty 6? That guarantees breaking changes every major release. Examples should be well documented / mention what version it was written for.

**Comment by normanmaurer** [comment]
Thats definitely something we want to do.. Anyway let me close this as there is no netty 5 for now.
