### ISSUE TITLE
Netty based client fails with Server Name Indication enabled server

### ISSUE THREAD

**Issue by ganskef** [netty/netty#3801]
Requesting a server with SNI enabled, like https://netty.io/ or https://kitematic.com/ for example, with a netty based client fails with an internal_error, received after TLS Handshake. An URLConnection based client sends a server_name extension. This seems to be missed in the handshake from the netty client. 

It's reproducable simply by launching ```java io.netty.example.http.snoop.HttpSnoopClient -Djavax.net.debug=all -Durl=https://netty.io```. I've tried it up to Netty version 4.1.0.Beta5. 

Please help me to find a workaround. See this issue too: https://github.com/adamfisk/LittleProxy/issues/207

**Comment by normanmaurer** [comment]
will check

**Comment by ganskef** [comment]
Hello Norman, some additional informations and a workaround:

Many of the Google services are using SNI too. Connecting 
https://developer.chrome.com with the Netty client, retrieve a 
Certificate CN=*.appspot.com with no matching SubjectAlternativeName.

  (!)This wrong certificate is accepted (it's valid signed) which means, 
there is no Host Name Verification happened.


It's been fixed simply by using 
io.netty.handler.ssl.util.SimpleTrustManagerFactory instead of 
io.netty.handler.ssl.util.InsecureTrustManagerFactory or 
javax.net.ssl.TrustManagerFactory. The Netty client sends an extension 
server_name, server_name: [host_name: developer.chrome.com] within 
handshake now. Note: Simply using the Java factory is not enough, it 
have to be the Netty implementation.


Is this pitfall a bug or missed documentation or simply missed knowledge 
of my mind? I'm frightened about the levered security here.


Regards Frank


Am 17.05.2015 um 20:23 schrieb Norman Maurer:

**Comment by normanmaurer** [comment]
@ganskef using the `InsecureTrustManagerFactory` is only for example / demo purposes. As it is "insecure" as the name should implies. 

So can we close this one ?

**Comment by ganskef** [comment]
Thank you, but sorry, there is no workaround. I've must been messed up with my tests or logs.

    Nettys based clients fails with https://netty.io/ and other SNI enabled sites.

Missed Host Name Verification vulnerability could be a missusage of the APIs by me. :-/

**Comment by ganskef** [comment]
Now I've found the solution in the example WebSocketClient. Such a client is working with SNI sites: 
```java
ChannelPipeline p = ch.pipeline();
if (sslCtx != null) {
    p.addLast(sslCtx.newHandler(ch.alloc(), peerHost, peerPort));
}
```
instead of:
```java
ChannelPipeline p = ch.pipeline();
if (sslCtx != null) {
    p.addLast(sslCtx.newHandler(ch.alloc()));
}
```

**Comment by Zhouguangfa123** [comment]
I solved the problem like the following example
`SSLEngine engine = sslContext.createSSLEngine();
engine.setUseClientMode(true);
pipeline.addLast("sslHandler", new SslHandler(engine));`
instead of:
``SSLEngine engine = sslContext.createSSLEngine(“host”, "port");
engine.setUseClientMode(true);
pipeline.addLast("sslHandler", new SslHandler(engine));``
