### ISSUE TITLE
DNS resolver loses ADDITIONAL records

### ISSUE THREAD

**Issue by dmk23** [netty/netty#3804]
#### Netty Version
4.1.0.Beta5 (using latest code/API per https://github.com/netty/netty/commit/63a02fc04e6ce45aee38b0437ae0279880e5fe40 @trustin )

#### Context
Additional records section is important for cutting down the number of necessary DNS questions - mainly to avoid follow-up queries for resolving hostnames (MX, CNAME or NS) to A / AAAA records. Unfortunately we've discovered that these records are **never** included when querying by Netty and we've tried to do MX queries for ~1 million different domains.

#### Step to Reproduce
First, try this on your shell prompt -
```
[root@localhost]# dig MX hotmail.com

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.30.rc1.el6 <<>> MX hotmail.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38795
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 4, ADDITIONAL: 16

;; QUESTION SECTION:
;hotmail.com.                   IN      MX

;; ANSWER SECTION:
hotmail.com.            3600    IN      MX      5 mx4.hotmail.com.
hotmail.com.            3600    IN      MX      5 mx1.hotmail.com.
hotmail.com.            3600    IN      MX      5 mx2.hotmail.com.
hotmail.com.            3600    IN      MX      5 mx3.hotmail.com.

;; AUTHORITY SECTION:
hotmail.com.            42729   IN      NS      ns1.msft.net.
hotmail.com.            42729   IN      NS      ns2.msft.net.
hotmail.com.            42729   IN      NS      ns3.msft.net.
hotmail.com.            42729   IN      NS      ns4.msft.net.

;; ADDITIONAL SECTION:
mx1.hotmail.com.        3600    IN      A       65.54.188.126
mx1.hotmail.com.        3600    IN      A       65.55.33.119
mx1.hotmail.com.        3600    IN      A       65.55.33.135
mx1.hotmail.com.        3600    IN      A       65.55.37.72
mx1.hotmail.com.        3600    IN      A       65.55.37.88
mx1.hotmail.com.        3600    IN      A       65.55.37.104
mx1.hotmail.com.        3600    IN      A       65.55.37.120
mx1.hotmail.com.        3600    IN      A       65.55.92.136
mx1.hotmail.com.        3600    IN      A       65.55.92.152
mx1.hotmail.com.        3600    IN      A       65.55.92.168
mx1.hotmail.com.        3600    IN      A       65.55.92.184
mx1.hotmail.com.        3600    IN      A       207.46.8.167
mx1.hotmail.com.        3600    IN      A       207.46.8.199
mx1.hotmail.com.        3600    IN      A       65.54.188.72
mx1.hotmail.com.        3600    IN      A       65.54.188.94
mx1.hotmail.com.        3600    IN      A       65.54.188.110

;; Query time: 14 msec
;; SERVER: 72.13.91.2#53(72.13.91.2)
;; WHEN: Sun May 17 22:08:02 2015
;; MSG SIZE  rcvd: 445
```
Then do the same query via Netty and observe no A records in the additional section of the response
```
resolver.query(new DefaultDnsQuestion("hotmail.com", DnsRecordType.MX)).addListener(this);
```
#### Possible Causes?
First of all, my knowledge of DNS protocol intricacies is limited, so I am just reporting a few things that seem different from the above ```dig``` test. I see that resolver is including some sort of ```OPT``` record in every DNS query ( https://github.com/netty/netty/blob/netty-4.1.0.Beta5/resolver-dns/src/main/java/io/netty/resolver/dns/DnsQueryContext.java#L74 ) and the DNS responses sometimes include an ```OPT``` record in the additional section. Seems to be this might be interfering with normal retrieval of additional records?

In any case perhaps it would be a good idea to allow a finer control over the additional section of the question vs. have the resolver always do exactly the same unchangeable thing...

#### Environment
[root@localhost]# java -version
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)

[root@localhost]# uname -a
Linux localhost 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by trustin** [comment]
On my radar although I don't have enough time at the moment. Will visit this soon.

**Comment by trustin** [comment]
I tried `dig` with and without `+noedns` (which removes the OPT record you said), but most DNS servers seem to omit the ADDITIONAL section no matter what I do:

```
$ dig @208.67.222.222 +noedns MX hotmail.com

; <<>> DiG 9.9.5-9-Debian <<>> @208.67.222.222 +noedns MX hotmail.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 36673
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;hotmail.com.                   IN      MX

;; ANSWER SECTION:
hotmail.com.            3462    IN      MX      5 mx3.hotmail.com.
hotmail.com.            3462    IN      MX      5 mx4.hotmail.com.
hotmail.com.            3462    IN      MX      5 mx1.hotmail.com.
hotmail.com.            3462    IN      MX      5 mx2.hotmail.com.

;; Query time: 90 msec
;; SERVER: 208.67.222.222#53(208.67.222.222)
;; WHEN: Wed Jun 03 18:26:51 KST 2015
;; MSG SIZE  rcvd: 109
```

Are you sure you specified the same DNS servers when you create a `DnsNameResolver`?

If you are in doubt, you could set a breakpoint in `DatagramDnsResponseDecoder.decode()` and step into `decodeRecords(..., DnsSection.ADDITIONAL, ...)`.  It's where the ADDITIONAL section is decoded.

**Comment by dmk23** [comment]
Interesting, I've just run the same command lines and seen the same results as you.

It may be that my local ISP resolver is including additional records on its own initiative and I've been taking it for granted. However, I've seen the same behavior of including additional records in this online DNS lookup tool (resolver not accessible publicly): http://network-tools.com/nslook/Default.asp?domain=hotmail.com&type=15&server=67.222.132.212&class=1&port=53&timeout=5000&go.x=21&go.y=9

I wonder if inclusion of additional records is always at the discretion of the resolver or there is a way to "force" it to do that by the contents of the query? What do the RFCs say?

**Comment by trustin** [comment]
I'm not sure - not a DNS expert either. :-/ My guess though is we are at the mercy of the DNS server we are talking to.  If you are fine, I'd like to close this issue until we find something more.  WDYT?

**Comment by dmk23** [comment]
Yes, I cannot find any ready solutions by Googling and this is probably not the most urgent item to drop everything and go read raw DNS specs to try and find out :)

The issue probably should be closed for now, but perhaps with a label of "needs more info".

Hopefully someone might come along with fresh insight.

**Comment by trustin** [comment]
Cool. Thanks.

**Comment by dmk23** [comment]
Additional note here, linking this to https://github.com/netty/netty/issues/3973

That other issue suggests that sometimes some DNS servers *DO* include A records in MX queries (see examples), however Netty treats such responses as errors to warn about.

I think such warnings should probably be removed (or be made configurable) at least in cases when at least one of the answers matches the original question. This seems to be normal DNS behavior...
