### ISSUE TITLE
Contradictory documentation in io.netty.util.internal.PlatformDependent

### ISSUE THREAD

**Issue by FunJp** [netty/netty#3805]
Netty 4.0.28.final

While working with Direct/Heap buffer, I've encountered this situation in the java doc.

On line 74 in io.netty.util.internal.PlatformDependent, the property loaded for Direct or Heap buffer for the used Allocator is like this

    private static final boolean DIRECT_BUFFER_PREFERRED =
            HAS_UNSAFE && !SystemPropertyUtil.getBoolean("io.netty.noPreferDirect", false);

But when going down to the getter of DIRECT_BUFFER_PREFERRED field, on line 152-158 the Java doc goes like this

    /**
     * Returns {@code true} if the platform has reliable low-level direct buffer access API and a user specified
     * {@code -Dio.netty.preferDirect} option.
     */

The two options stated have different name. Also, it's a bit confusing using the negate form in the first one "io.netty.noPreferDirect". It's then to double negate when trying to use an Allocator with HeapBuffer instead of DirectBuffer.

**Comment by normanmaurer** [comment]
Fixed the javadocs... Thanks!
