### ISSUE TITLE
Http2OrHttpChooser API design issue

### ISSUE THREAD

**Issue by trustin** [netty/netty#3813]
When setting up an HTTP/1 or HTTP/2 pipeline, a user usually ends up with adding arbitrary set of handlers.

`Http2OrHttpChooser` has two abstract methods (`createHttpNRequestHandler`) that expects a user to return a single handler, and `addHttpNHandlers()` method adds it to the pipeline as well as the pre-defined set of handlers.

The problem is, some users (read: I) don't need all of them or the user wants to add more than one handler.  For example, take a look at `io.netty.example.http2.tiles.Http2OrHttpHandler`, which works around this issue by overriding `addHttp2Handlers()` and making `createHttp2RequestHandler()` no-op.

I'd like to change the API like the following for better user experience:

- replace `addHttpHandlers()`, `addHttp2Handlers`, `createHttp1RequestHandler` and `createHttp2RequestHandler` with the two abstract methods:
  - `configureHttp1(ChannelPipeline p) throws Exception`
  - `configureHttp2(ChannelPipeline p) throws Exception`
- rename `getProtocol()` to `selectProtocol()` to make what it does clear
- provide the default implementation of `selectProtocol()`

What do you think?

/cc @nmittler @Scottmitch

**Comment by normanmaurer** [comment]
@trustin sounds good to me :)

Only comment I have is that I would call it `initHttp1Pipeline(...)` and `initHttp2Pipeline(...)`. Or if we want to make it consistent with `ChannelInitializer` we could also name it `initHttp1Channel(Channel)` and `initHttp2Channel(Channel)`.

**Comment by nmittler** [comment]
@trustin yeah that sounds much cleaner! :)

**Comment by Scottmitch** [comment]
@trustin - +1.

Your 2nd and 3rd top level bullet point would benefit from (or may overlap with) issue https://github.com/netty/netty/issues/3641.  Any interest in taking this on too?

**Comment by trustin** [comment]
@normanmaurer I still prefer `configure*()` to `init*()`, because we do not initialize the pipeline but re-configure the pipeline.

**Comment by normanmaurer** [comment]
@trustin I think you fixed this... closing now
