### ISSUE TITLE
Allow lazy instantiation of HTTP/2-related types

### ISSUE THREAD

**Issue by trustin** [netty/netty#3814]
I'm writing an h2c server, and my pipeline currently looks like the following:

```java
		final HttpServerCodec http1codec = new HttpServerCodec();
		final HttpObjectAggregator http1aggregator = new HttpObjectAggregator(config.maxFrameLength());
		final Http2Connection conn = new DefaultHttp2Connection(true);
		final Http2FrameWriter writer = new DefaultHttp2FrameWriter();
		final Http2FrameReader reader = new DefaultHttp2FrameReader();
		final Http2FrameListener listener = new InboundHttp2ToHttpAdapter.Builder(conn)
				.propagateSettings(true).validateHttpHeaders(false)
				.maxContentLength(config.maxFrameLength()).build();

		p.addLast(http1codec);
		p.addLast(new HttpServerUpgradeHandler(
				http1codec,
				Collections.singletonList(
						new Http2ServerUpgradeCodec(
								"http2to1adapter",
								new CleartextHttpToHttp2ConnectionHandler(
										conn, reader, writer, listener, p, http1aggregator))),
				config.maxFrameLength()));
```

It does what it's supposed to do, but it creates quite a few HTTP/2-related objects from the beginning of the connection.  Since we can't determine if the connection is HTTP/2 or HTTP/1 yet, I'd like to defer the instantiation of `HttpToHttp2ConnectionHandler`, `Http2Connection`, `Http2FrameReader`, `Http2FrameWriter`, and `HttpFrameListener` until the upgrade request has been received.

It seems to me that such lazy instantiation is impossible with the current API.

To fix this issue, I'd like to change `Http2ServerUpgradeCodec` to accept a factory.

Thoughts?

/cc @nmittler @Scottmitch

**Comment by normanmaurer** [comment]
@trustin sounds legit .

**Comment by nmittler** [comment]
@trustin sounds good ... Are you throwing together a PR? Would be good to see what the new code looks like.

**Comment by Scottmitch** [comment]
@trustin - I wonder if this factory could be used by https://github.com/netty/netty/issues/3813 too?  Seems like both classes *may* end up needing the HTTP/2 pipeline classes, but you may be able to delay creating these classes in both instances.

**Comment by trustin** [comment]
Please see #3876

**Comment by normanmaurer** [comment]
@trustin I think you fixed this... closing now
