### ISSUE TITLE
Do not use hard-coded handler names in HTTP/2

### ISSUE THREAD

**Issue by trustin** [netty/netty#3815]
Our HTTP/2 implementation sometimes uses hard-coded handler names when adding/removing a handler to/from a pipeline.  It's not really a good idea because it can easily result in name clashes.

Unless there is a good reason, we need to use the reference to the handlers:

```java
pipeline.addLast(handler1); // No name specified. Netty will generate one from its name cache for you.
pipeline.remove(handler1);
...
```

**Comment by normanmaurer** [comment]
@trustin makes sense.

**Comment by nmittler** [comment]
@trustin SGTM

**Comment by Scottmitch** [comment]
+1

**Comment by Scottmitch** [comment]
@trustin - Are you taking the assignment on this one?

**Comment by trustin** [comment]
I'm on a short travel right now, but will take care of the 3
HTTP/2-related issues I filed once I'm back on Monday.

**Comment by normanmaurer** [comment]
Thanks @trustin

**Comment by trustin** [comment]
@nmittler @Scottmitch PR created: #3873
