### ISSUE TITLE
HttpRequestDecoder generates FullHttpRequest in case of error.

### ISSUE THREAD

**Issue by fantayeneh** [netty/netty#3820]
In netty 4.0.28 `HttpRequestDecoder` generates a `FullHttpRequest` message in case of error.

```
@Override
    protected HttpMessage createInvalidMessage() {
        return new DefaultFullHttpRequest(
                HttpVersion.HTTP_1_0, HttpMethod.GET, "/bad-request", Unpooled.EMPTY_BUFFER, validateHeaders);
    }

```

Which confused me a little bit as i was seeing `DefaultFullHttpRequest(decodeResult: failure(java.lang.IllegalArgumentException...` as error message and  didn't have `HttpObjectAggregator` in the pipeline.

It used to be in 4.0.21 just a HttpRequest

```
    @Override
    protected HttpMessage createInvalidMessage() {
        return new DefaultHttpRequest(HttpVersion.HTTP_1_0, HttpMethod.GET, "/bad-request", validateHeaders);
    }

```
Is it not better to do have it as 4.0.21?

**Comment by NiteshKant** [comment]
The change was discussed in issue #3362, which also explains the reason for the change.

**Comment by normanmaurer** [comment]
Thanks @NiteshKant for chime in... Closing.
