### ISSUE TITLE
Expose more stats for channel pool

### ISSUE THREAD

**Issue by fantayeneh** [netty/netty#3824]
Currently there is no easy way to find 
- the number of available channels in the pool. (those that can be acquired immediately without having to make a new connection to the remote server)
- the number of pending acquires

This two stats can be used by a load balancing algo to make decisions.

**Comment by normanmaurer** [comment]
We love contributions ;)

**Comment by fantayeneh** [comment]
will do. :)

**Comment by normanmaurer** [comment]
awesome !

**Comment by normanmaurer** [comment]
@fantayeneh are you still working on this ?

**Comment by normanmaurer** [comment]
@fantayeneh ping... :)

**Comment by migralito** [comment]
ping! we use apache HC because our load balancing will lack of stats if we were to use netty :(

**Comment by normanmaurer** [comment]
ChannelPool was removed for 5.0
