### ISSUE TITLE
Remove the Unsafe delegation methods in PlatformDependent

### ISSUE THREAD

**Issue by trustin** [netty/netty#3835]
So far, we did not let the classes that need `Unsafe` use `Unsafe` directly. Instead, we exposed all the unsafe operations in `PlatformDependent` (and also `PlatformDependent0`).

To be honest, I'm not sure if it really adds something to us.  We should:
- Remove the Unsafe delegation methods from `PlatformDependent` and `PlatformDependent0`.
- Keep the boolean-returning methods that tells the availability of Unsafe and certain operations of Unsafe.

However, we need to consider that adding a method that returns `Unsafe` or refers to `Unsafe` in `PlatformDepent` because that will lead into the class-loading problem in Android.

Instead, our code need to follow the following pattern:

``` java
if (PlatformDependent.hasUnsafe()) {
    // Can't refer to sun.misc.Unsafe here because Android will fart.
    SomeOtherClass.performUnsafe(...);
} else {
   ...
}

final class SomeOtherClass {
    static void performUnsafe(...) {
        TheUnsafe.UNSAFE.copyMemory(...);
    }
}

public final class TheUnsafe {
    public static final sun.misc.Unsafe UNSAFE = ...;
}
```

**Comment by normanmaurer** [comment]
I think we can just close this for now and re-open later if we think it worth it.
