### ISSUE TITLE
channel connect listener order guarantee & passing args

### ISSUE THREAD

**Issue by dmk23** [netty/netty#3836]
I am implementing a protocol that requires passing args into a handler after connecting (TCP).

In my current approach I am using connect() method of a client Bootstrap to retrieve ChannelFuture, immediately calling addListener to pass these args to channel / context via AttributeKey. Then channel's read callbacks retrieve these args from the context and use them in our protocol logic.

**QUESTION1:** Is there a guarantee that the connect listener callback would always execute before first read callback - even if the server sends a greeting immediately after connecting? If not, what could be the proper workaround to delay/retry execution of the read callback till the state is initialized?

**QUESTION2:** Assuming there is no easy answer above. Could it be appropriate / possible to initialize channel state even before connection is established? e.g. obtain channel from the future and set its attributes immediately and not inside the connect listener callback?

**Comment by normanmaurer** [comment]
@dmk23 please use out mailinglist or stackoverflow for questions.

To answer your question you can use Bootstrap.attr(...) to specify which attributes should be set on the Channel before connect it.

**Comment by dmk23** [comment]
Thanks for the response.

Just to be safe I looked at the Bootstrap.attr(...) code and it seems to me to get the Channel without concurrency issues the code for setting attr and opening channel needs to be synchronized. Ideally on private attrs field, but since it is not externally visible then on the bootstrap object itself.

Does this make sense? In any case, seems like attrs and passing / managing state into handlers ought to be documented / explained somewhere in more detail...
