### ISSUE TITLE
flushing delays with TCP_CORK ?

### ISSUE THREAD

**Issue by dmk23** [netty/netty#3838]
I am exploring the use of TCP_CORK as a way of reducing packet fragmentation and thus bandwidth.

The flip side seems to be the increased latency (up to 200ms) in case of not having enough data for a full packet - which is a common scenario. The solution is to "uncork" and "recork" a corked connection to force sending, as described here: http://baus.net/on-tcp_cork/

Looking at Epoll package code it appears that Netty does not currently do this on a regular channel flush. I suppose it could be possible to manually call Native.setTcpCork after the flush, but I wonder if there ought to be a higher level API for this (or a flushing option) as well as a single native call that would both uncork / recork the channel in a single JNI invocation ...

**Comment by normanmaurer** [comment]
@dmk23 there is nothing high-level implemented via us.

**Comment by dmk23** [comment]
Should this be marked as a possible feature suggestion?

**Comment by trustin** [comment]
At least we could expose that operation somewhere in `EpollSocketChannel`?

**Comment by normanmaurer** [comment]
@trustin you can already doing this by just cal it during flush()

**Comment by dmk23** [comment]
Is it actually done right now? I saw the calls to Native.setTcpCork only on initial channel setup when I searched through the code - not in any place related to flushing...

It also seems to me it ought to be just an option of flush vs. something that is always enforced?

**Comment by normanmaurer** [comment]
@dmk23 I may be confused but you can just do `channel.config().set*` for changing socket options on the fly. What issue you have ?

**Comment by dmk23** [comment]
Yes, this can be done manually right now.

Just was wondering if it should/could be made an explicit option in the flushing API(s)... Since there is not much docs on TCP_CORK option the existing behavior / solution was not readily findable...

This is not a major thing, but might be an enhancement for clarity purposes...
