### ISSUE TITLE
wrong file FileDescriptor when set the config of epoll socket channel

### ISSUE THREAD

**Issue by hepin1989** [netty/netty#3840]
I encounter this when I try to set the config of the socket channel.
and after I restart again the app,it don't show up.

```
[Error][2015-05-29 12:36:59]: setsockopt() failed: 错误的文件描述符

java.lang.RuntimeException: setsockopt() failed: 错误的文件描述符
	at io.netty.channel.epoll.Native.setKeepAlive(Native Method)
	at io.netty.channel.epoll.EpollSocketChannelConfig.setKeepAlive(EpollSocketChannelConfig.java:197)
	at io.netty.channel.epoll.EpollSocketChannelConfig.setKeepAlive(EpollSocketChannelConfig.java:29)

```

I am trying to set the config after the channel is connected to remote server.

**Comment by normanmaurer** [comment]
@hepin1989 can you translate the error to english ?

**Comment by hepin1989** [comment]
错误的文件描述符 => wrong fd(FileDescriptor)

**Comment by normanmaurer** [comment]
@hepin1989 This error is most likely thrown as the channel itself is already closed. Is this possible ?

**Comment by hepin1989** [comment]
@normanmaurer I will keep eyes on that,I just encountered this once.

**Comment by normanmaurer** [comment]
@hepin1989 I will close this for now... Please re-open once you have more infos

**Comment by hepin1989** [comment]
@normanmaurer sure :)
