### ISSUE TITLE
Fix build stability issues with the epoll transport

### ISSUE THREAD

**Issue by trustin** [netty/netty#3848]
- http://clinker.netty.io/jenkins/job/netty-oraclejdk7/branch/4.1/412/
- http://clinker.netty.io/jenkins/job/netty-oraclejdk8/branch/4.1/412/

We might have more. Please go through the failures and fix the epoll-related ones.

**Comment by normanmaurer** [comment]
@trustin will check... can't reproduce so far here :/

**Comment by trustin** [comment]
It seemed to fail on the both centos6 slaves and one of them is yours. :-)

**Comment by normanmaurer** [comment]
@trustin will find out

**Comment by normanmaurer** [comment]
I think this should be fixed now
