### ISSUE TITLE
LEAK warning after Java 8 Migration with Netty 4.0.25-Final.

### ISSUE THREAD

**Issue by bagdemir** [netty/netty#3855]
We see occasionally this message "LEAK: ByteBuf.release() was not called before it's garbage-collected." as warning in the log files since the migration to Java 8 JRE. We have also switched to G1 GC. We are using Netty 4.0.25-Final in our backend service. Is there any known issue regarding Netty + Java 8 ? 

We are currently monitoring our system since the production deployment, and there is no leaking memory in Java heap and GC has done its work very well so far. I assume that the possible leak would be outside of the Java heap, because it is very likely, that Netty uses DirectBuffers which are allocated in the process' native memory ? 

My question is, how should we deal with this warning? Does this warning really indicate, that there is a real leak somewhere in our service ? What is wrong with the JRE 8. Before the migration, using JRE 7 and CMS, we did not have any problem like this.

**Comment by normanmaurer** [comment]
@bagdemir yep this means there is a "real" leak. So most likely you forgot to release an buffer in your ChannelInboundHandler implementation. Why it only shows up since java8 is not clear, maybe you was just more lucky before ?

Here are some docs to troubleshoot leaks:
http://netty.io/wiki/reference-counted-objects.html#wiki-h2-10

**Comment by bagdemir** [comment]
Thanks for the link @normanmaurer . I had already had a look at the wiki and set the leakDetectionLevel to see more and have been waiting for the next leak warning. 

However, in our implementation, everything looks actually OK and there had been no change in the source code since months before the deployment. Until Java 8 migration, I hadn't seen such a warning with JRE7. The instances have been running almost for a week now, and in Splunk, I can see this warning appeared 1x on every instance of 11 and just after our latest deployment. Since then, there is no warning any more. We have been monitoring the native process memory usage. In Java heap, the GC works well and usage stays stable as expected. But I assume that Netty allocates NIO's DirectBuffers outside of the heap and increments the counter, and if the number of references to these buffers is not same as the ref count, then netty is suspicious of a possible leak? 

As I told, I see only one warning per instance after cut-over and no more till today.
What would it mean? Should I expect more warnings on a continuously leaking machine, or it is fully sufficent to see once this message to make considerations on a huge leak ?

Thanks you for your reply.

**Comment by normanmaurer** [comment]
@bagdemir how huge the leak really is is impossible to say. If it reports a leak I would bet there is one. IF you run with the "default" resource leak detection level this reports may only be logged very rarely if it happens only on rare cases in your app. So better enable advanced or paranoid level and see what shows up. Be aware these will put some noticeable perf overhead on your app..

**Comment by bagdemir** [comment]
@normanmaurer yeah, that was actually what I am afraid of. I think It is better to run our load tests on Stage and try to reproduce the issue with leakDetectionLevel=paranoid.
