### ISSUE TITLE
Discussion of import external library

### ISSUE THREAD

**Issue by christophe-blettry** [netty/netty#3858]
Hello

Since using netty I did not need to import external libraries.
But since I want to use HTTP2.0 I found some import like this
 in : `netty/handler/src/main/java/io/netty/handler/ssl/OpenSsl.java`
```java
import org.apache.tomcat.jni.Library;
import org.apache.tomcat.jni.Pool;
import org.apache.tomcat.jni.SSL;
import org.apache.tomcat.jni.SSLContext;'
```
Is'it a new way for netty ? 

although it is noted in the main page 
Ease of use
    Well-documented Javadoc, user guide and examples
    **No additional dependencies, JDK 5 (Netty 3.x) or 6 (Netty 4.x) is enough**

Thanks

**Comment by trustin** [comment]
It's an optional dependency.  When the tcnatice is unavailable, Netty will not use it.
