### ISSUE TITLE
CompositeByteBuf.removeComponent deallocate another CompositeBuffer instance

### ISSUE THREAD

**Issue by brodier** [netty/netty#3863]
Netty version: 4.0.28.Final

Context:
Removing component of a CompositeByteBuf composed from sliced element of an other CompositeByteBuf result in an unexpected state of this other CompositeByteBuf

I have a code that throws an io.netty.util.IllegalReferenceCountException when accecssing on a component of CompositeByteBuf

Steps to reproduce:

Failing JUnit test : 

```java
	@Test
	public void testRemoveComponnentOnCompositeBuffer() {
		byte [] array1 = "0123456789".getBytes();
		byte [] array2 = "0123456789".getBytes();
		byte [] array3 = "0123456789".getBytes();
		CompositeByteBuf cb = Unpooled.compositeBuffer();
		CompositeByteBuf cb2 = Unpooled.compositeBuffer();
		cb.addComponent(Unpooled.wrappedBuffer(array1));
		cb.addComponent(Unpooled.wrappedBuffer(array2));
		cb.addComponent(Unpooled.wrappedBuffer(array3));
		assertEquals(30,cb.capacity());
		cb2.addComponent(cb.slice(2, 10));
		cb2.addComponent(cb.slice(14, 10));
		cb2.addComponent(cb.slice(26, 4));
		assertEquals(24, cb2.capacity());
		assertEquals(10, cb.component(0).capacity());
		cb2.removeComponent(0);
		assertEquals(10, cb.component(0).capacity());
	}	
```

**Comment by brodier** [comment]
Tested on 4.0.12.Final and 4.0.28.Final

**Comment by normanmaurer** [comment]
@brodier thanks for reporting. Do you grant us rights to include the unit test in netty ? I will work on a fix

**Comment by brodier** [comment]
Of course I grant you rights to include this unit test. 
Thank's for the quick reply

**Comment by normanmaurer** [comment]
@brodier actually I think this is expected... You will need to call cb2.addComponent(cb.slice(...).retain()). As slice(...) will not increment the reference count and removeComponent(...) will call release() on the components that are removed.
