### ISSUE TITLE
Buffer leak in HTTP2

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#3871]
06:54:56 02:54:56.245 [nioEventLoopGroup-47-0] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
06:54:56 Recent access records: 5
06:54:56 #5:
06:54:56 	io.netty.buffer.AdvancedLeakAwareByteBuf.release(AdvancedLeakAwareByteBuf.java:722)
06:54:56 	io.netty.handler.codec.http2.Http2ConnectionHandler.processGoAwayWriteResult(Http2ConnectionHandler.java:637)
06:54:56 	io.netty.handler.codec.http2.Http2ConnectionHandler.goAway(Http2ConnectionHandler.java:570)
06:54:56 	io.netty.handler.codec.http2.Http2ConnectionHandler.goAway(Http2ConnectionHandler.java:602)
06:54:56 	io.netty.handler.codec.http2.Http2ConnectionHandler.onConnectionError(Http2ConnectionHandler.java:502)
06:54:56 	io.netty.handler.codec.http2.Http2ConnectionHandler.onException(Http2ConnectionHandler.java:475)
06:54:56 	io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:174)
06:54:56 	io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeHeaders(DecoratingHttp2FrameWriter.java:51)
06:54:56 	io.netty.handler.codec.http2.StreamBufferingEncoder.writeHeaders(StreamBufferingEncoder.java:131)
06:54:56 	io.netty.handler.codec.http2.StreamBufferingEncoderTest.encoderWriteHeaders(StreamBufferingEncoderTest.java:405)
06:54:56 	io.netty.handler.codec.http2.StreamBufferingEncoderTest.exhaustedStreamsDoNotBuffer(StreamBufferingEncoderTest.java:372)
06:54:56 	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
06:54:56 	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
06:54:56 	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
06:54:56 	java.lang.reflect.Method.invoke(Method.java:497)
06:54:56 	org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
06:54:56 	org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
06:54:56 	org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
06:54:56 	org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
06:54:56 	org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
06:54:56 	org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
06:54:56 	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
06:54:56 	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
06:54:56 	org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
06:54:56 	org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
06:54:56 	org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
06:54:56 	org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
06:54:56 	org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
06:54:56 	org.junit.runners.ParentRunner.run(ParentRunner.java:363)
06:54:56 	org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
06:54:56 	org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
06:54:56 	org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
06:54:56 	org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
06:54:56 	org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
06:54:56 	org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
06:54:56 #4:
06:54:56 	io.netty.buffer.AdvancedLeakAwareByteBuf.toString(AdvancedLeakAwareByteBuf.java:676)
06:54:56 	io.netty.handler.codec.http2.Http2ConnectionHandler.processGoAwayWriteResult(Http2ConnectionHandler.java:621)
06:54:56 	io.netty.handler.codec.http2.Http2ConnectionHandler.goAway(Http2ConnectionHandler.java:570)
06:54:56 	io.netty.handler.codec.http2.Http2ConnectionHandler.goAway(Http2ConnectionHandler.java:602)
06:54:56 	io.netty.handler.codec.http2.Http2ConnectionHandler.onConnectionError(Http2ConnectionHandler.java:502)
06:54:56 	io.netty.handler.codec.http2.Http2ConnectionHandler.onException(Http2ConnectionHandler.java:475)
06:54:56 	io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:174)
06:54:56 	io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeHeaders(DecoratingHttp2FrameWriter.java:51)
06:54:56 	io.netty.handler.codec.http2.StreamBufferingEncoder.writeHeaders(StreamBufferingEncoder.java:131)
06:54:56 	io.netty.handler.codec.http2.StreamBufferingEncoderTest.encoderWriteHeaders(StreamBufferingEncoderTest.java:405)
06:54:56 	io.netty.handler.codec.http2.StreamBufferingEncoderTest.exhaustedStreamsDoNotBuffer(StreamBufferingEncoderTest.java:372)

**Comment by normanmaurer** [comment]
See also http://clinker.netty.io/jenkins/job/netty-pullreqs/1226/consoleFull

@nmittler @Scottmitch could you check ?

**Comment by Scottmitch** [comment]
@normanmaurer - Will check

**Comment by Scottmitch** [comment]
I have a PR pending for this.

**Comment by trustin** [comment]
Ugh, I didn't know you had a fix. Just pushed my own fix: e72d04509f7d04d2a0a0e96cc5555728ac03aa29

**Comment by Scottmitch** [comment]
@trustin - No problem. Just got it approved and saw that I had a merge conflict :)  Sorry for the slow turn around :(  I was just using `ReferenceCountUtil` to avoid explicit `a instanceof ByteBuf` and cast, but leak fixed either way.

**Comment by trustin** [comment]
@Scottmitch I used `ReferenceCountUtil.release()` first, but wanted to make sure I release ByteBufs only. If the objects of other types are released, it's probably something we didn't really expect, so...

**Comment by trustin** [comment]
Anyways, sorry that I didn't notice you already have fixed it on your side. :facepalm:
