### ISSUE TITLE
FixedChannelPool creates 1 more channel than maxConnections

### ISSUE THREAD

**Issue by fratboy** [netty/netty#3881]
Netty version: 4.0.10.Beta5

Context:
1 more channel was created, when I tried to acquire channel via `FixedChannelPool.acquire`

Steps to reproduct:
1. Create a `FixedChannelPool` with `N`  `maxConnections`
2. Call `FixedChannelPool.acquire` from enough many thread
3. `N+1` channels is created.

Opinion:
It looks like

https://github.com/netty/netty/blob/master/transport/src/main/java/io/netty/channel/pool/FixedChannelPool.java#L267

```java
while (acquiredChannelCount <= maxConnections) {
```

should be 

```java
while (acquiredChannelCount < maxConnections) {
```

**Comment by Scottmitch** [comment]
@normanmaurer - Seems legit. WDYT?

**Comment by normanmaurer** [comment]
@Scottmitch yep, will fix

**Comment by normanmaurer** [comment]
Fixed

**Comment by fratboy** [comment]
:+1:
