### ISSUE TITLE
OpenSSL SSLSession returns incorrect peer principal

### ISSUE THREAD

**Issue by edwinchoi** [netty/netty#3883]
According to the docs for `javax.net.ssl.SSLSession` (http://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLSession.html#getPeerPrincipal()), `getPeerPrincipal` should be returning the identity of the peer.

The OpenSSL based implementation for Netty, however, is returning the identity of the issuer:
https://github.com/netty/netty/blob/netty-4.0.28.Final/handler/src/main/java/io/netty/handler/ssl/OpenSslEngine.java#L1406
`getPeerPrincipal()` calls `principal(certs)`, which casts to `X509Certificate` and calls `getIssuerX500Principal()` when it should be calling `getSubject500Principal()`.

The JDK based implementation returns the correct principal.

**Comment by normanmaurer** [comment]
@edwinchoi thanks for the report... Will fix it

**Comment by normanmaurer** [comment]
@edwinchoi can you verify the fix:

https://github.com/netty/netty/pull/3889

Thanks!

**Comment by edwinchoi** [comment]
@normanmaurer works as expected now, thanks!

**Comment by normanmaurer** [comment]
Fixed
