### ISSUE TITLE
SSL server side session resumption with Netty - issue or no support by Java?

### ISSUE THREAD

**Issue by virtman** [netty/netty#3892]
Hello,

tests were done with https://github.com/iSECPartners/sslyze
Checked already all Netty basic version as example with HttpSnoopServer example.
Java claims to support it transparently, but even when I use instead .createSSLEngine(); the version with hints .createSSLEngine("localhost", 443); etc.. this does not help.
Therefore the questions to smart guys in this forum, did ever anyone get session resumption to work with Java or Java just does not support it?
Or has anyone already succeed on this field?
Session resumption (cache or tickets) helps to greatly improve performance of SSL based connections.
Thank you in advance!

**Comment by brettwooldridge** [comment]
I am curious about this as well.

SSLyze reports;
```
* Session Resumption:
    With Session IDs:                  PARTIALLY SUPPORTED (3 successful, 2 failed, 0 errors, 5 total attempts). Try --resum_rate.
    With TLS Session Tickets:          NOT SUPPORTED - TLS ticket not assigned.
```

**Comment by virtman** [comment]
I got it to when runned for first time, but never again. 
Try the switch --resum_rate to check it with 100 tries which are more closer to real world result.
There I got zero hits..
You can check the same with google, there is success rate 100%

**Comment by normanmaurer** [comment]
@virtman so all good ?

**Comment by virtman** [comment]
Unfortunally absolutely not good, PARTIALLY SUPPORTED is not meant to be supported. Do not let you irritate by 3 succeed tries.
If you run with 100 tries (Try --resum_rate) you see NOT SUPPORTED ;) is that good? No.. Just make please proper tests by your self and compare results with other ssl servers like google etc..
Just to see real results when comparing.

**Comment by normanmaurer** [comment]
@virtman @brettwooldridge I am not sure about the JDK SSLEngine implementation but it works out of the box when you use our OpenSSLEngine implementation

**Comment by danadam** [comment]
JDK SSL Engine supports TLS resumption using cache.

There was a bug in nassl used by sslyze. It didn't properly shutdown TLS connection before closing a socket and the result was that the TLS session was being invalidated. The bug is already [fixed](https://github.com/nabla-c0d3/nassl/pull/43).

**Comment by normanmaurer** [comment]
Closing as it seems like everything is ok now. Please reopen if you still think there is an issue.
