### ISSUE TITLE
"ByteBuf copiedBuffer(ByteBuffer buffer)" in Netty 4.0.24 is NOT thread safe

### ISSUE THREAD

**Issue by sefler1987** [netty/netty#3896]
I'm not sure why this static method is not thread safe, but it bothers me a lot during the development. As the following code shows, the method firstly copy the position out and then set it back after copying. If there are two threads doing the same thing, the position may be stained.

```
    public static ByteBuf copiedBuffer(ByteBuffer buffer) {
        int length = buffer.remaining();
        if (length == 0) {
            return EMPTY_BUFFER;
        }
        byte[] copy = new byte[length];
        int position = buffer.position();
        try {
            buffer.get(copy);
        } finally {
            buffer.position(position);
        }
        return wrappedBuffer(copy).order(buffer.order());
    }
```

**Comment by normanmaurer** [comment]
@sefler1987 I think you are right... We should call duplicate on the buffer first. Let me fix it

**Comment by sefler1987** [comment]
Thank you so much~

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/3930
