### ISSUE TITLE
Please make EpollSocketChannel non final

### ISSUE THREAD

**Issue by purplefox** [netty/netty#3897]
Hi folks,

In Vert.x 3 HTTP each Netty channel is associated with our Vert.x ServerConnection object which represents our HTTP connection.

As an optimisation to avoid looking up the ServerConnection each time a channelRead is fired for the channel, we store a reference to the connection on a subclass of the NioSocketChannel object:

https://github.com/eclipse/vert.x/blob/perf5/src/main/java/io/vertx/core/http/impl/VertxNioSocketChannel.java#L34

And we provide our own factories (both server and client) to create these:

https://github.com/eclipse/vert.x/blob/perf5/src/main/java/io/vertx/core/http/impl/VertxNioSocketChannelFactory.java

https://github.com/eclipse/vert.x/blob/perf5/src/main/java/io/vertx/core/http/impl/VertxNioSocketChannelFactory.java

I would like to use this technique for the epoll transport too, but the class EpollSocketChannel is final so this is not possible.

Could you make the class non final with public constructor so we can support this technique?

Or even better: - perhaps you could provide a generic way to set/get user data on a channel object, e.g.:

<T> T getUserReference();

void setUserReference(Object ref)

**Comment by trustin** [comment]
How about `Channel.attr()`?

**Comment by purplefox** [comment]
Hi Trustin-

I ran a comparative benchmark to compare three different approaches:

1. Using a simple concurrent hashmap
2. Using Netty attributes
3. Using simple reference on subclass

This is on two 16 core servers with 10GbE, one acting as server, one as client.

Using wrk on the client side with command line:

./wrk -c 1000 -t20 http://192.168.123.25:8080/foo -d60s -s vpipeline.lua -- 200

I ran the above in a loop and discarded the first run due to JIT warmup, then took mean of subsequent 5 runs.

Results:

1. simple hashmap

3.12M req/s

2. netty attributes

3.17M req/s

3. simple reference

3.23M req/s

So netty attributes are faster than concurrent hashmap but not as fast as simple reference optimisation.

There is 1.9% difference in throughput between netty attributes and simple reference, so I would like to keep our simple reference optimisation and not use netty attributes so we can get the best performance.

**Comment by normanmaurer** [comment]
@purplefox honestly I would like to keep it final.

If you really want to not use this optimization you could just wrap the EpollSocketChannel.

Something like:

```java

    public final class VertxEpollSocketChannelFactory implements ChannelFactory<VertxSocketChannel> {
        @Override
        public VertxSocketChannel newChannel() {
            return new VertxSocketChannel(new EpollSocketChannel());
        }
    }
    
    public final class VertxSocketChannel implements SocketChannel {
        private final SocketChannel channel;
        private volatile Object attachment;

        public VertxSocketChannel(SocketChannel channel) {
            this.channel = channel;
        }

        public void setAttachment(Object attachment) {
            this.attachment = attachment;
        }

        public Object getAttachment() {
            return attachment;
        }

        @Override
        public ServerSocketChannel parent() {
            return channel.parent();
        }

        @Override
        public SocketChannelConfig config() {
            return channel.config();
        }

        @Override
        public InetSocketAddress localAddress() {
            return channel.localAddress();
        }

        @Override
        public InetSocketAddress remoteAddress() {
            return channel.remoteAddress();
        }

        @Override
        public boolean isInputShutdown() {
            return channel.isInputShutdown();
        }

        @Override
        public boolean isOutputShutdown() {
            return channel.isOutputShutdown();
        }

        @Override
        public ChannelFuture shutdownOutput() {
            return channel.shutdownOutput();
        }

        @Override
        public ChannelFuture shutdownOutput(ChannelPromise future) {
            return channel.shutdownOutput(future);
        }

        @Override
        public EventLoop eventLoop() {
            return channel.eventLoop();
        }

        @Override
        public boolean isOpen() {
            return channel.isOpen();
        }

        @Override
        public boolean isRegistered() {
            return channel.isRegistered();
        }

        @Override
        public boolean isActive() {
            return channel.isActive();
        }
        ...
        ...
    }
```

**Comment by purplefox** [comment]
We also have to override ServerSocketChannel so we can change where the server side SocketChannels are created.

Not sure a delegation approach like this will work there? ..

**Comment by normanmaurer** [comment]
@purplefox hmm you right... that said like I said I would prefer to not change this but better make the attribute stuff perform better ;) Let me see what I can do for you.

**Comment by purplefox** [comment]
Cool, thanks Norman :)

BTW, this is not urgent, as I actually found the epoll transport to be somewhat slower than the Nio transport in my tests, so we don't really have an important need to use a transport other than Nio at the moment.

**Comment by normanmaurer** [comment]
@purplefox gotcha :) I love low-priority stuff ;)

**Comment by takeseem** [comment]
waiting epoll support in vert.x :)

**Comment by triggerants** [comment]
+1

**Comment by takeseem** [comment]
@purplefox 

> Cool, thanks Norman :)
> 
> BTW, this is not urgent, as I actually found the epoll transport to be somewhat slower than the Nio transport in my tests, so we don't really have an important need to use a transport other than Nio at the moment.

Thank you for your test, it usefull for me.
Where can I find the test code?

**Comment by normanmaurer** [comment]
Let me close this... I think for now we want to keep it final
