### ISSUE TITLE
Example code in ByteBuf 4.0 javadoc uses 3.x API

### ISSUE THREAD

**Issue by justinjhendrick** [netty/netty#3899]
https://netty.io/4.0/api/io/netty/buffer/ByteBuf.html

 // Iterates the readable bytes of a buffer.
 ByteBuf buffer = ...;
 while (buffer.readable()) {
     System.out.println(buffer.readByte());
 }
 

But readable() was changed to isReadable() in 4.0

**Comment by normanmaurer** [comment]
@justinjhendrick yep... We love PR's, maybe you want to submit one ?

**Comment by justinjhendrick** [comment]
I'd like to but my company doesn't want to go through the analysis required for me to contribute to netty for such a small PR. Sorry.

**Comment by normanmaurer** [comment]
@justinjhendrick no worries... I will fix it

**Comment by justinjhendrick** [comment]
Thanks!

**Comment by normanmaurer** [comment]
Fixed
