### ISSUE TITLE
Buffer leak in HTTP2

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#3905]
exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
18:20:38 io.netty.channel.ChannelPipelineException: io.netty.handler.codec.http2.Http2ConnectionRoundtripTest$9.handlerAdded() has thrown an exception; removed.
18:20:38 	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:601) [classes/:na]
18:20:38 	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:45) [classes/:na]
18:20:38 	at io.netty.channel.DefaultChannelPipeline$3.run(DefaultChannelPipeline.java:577) [classes/:na]
18:20:38 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:322) [classes/:na]
18:20:38 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356) [classes/:na]
18:20:38 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703) [classes/:na]
18:20:38 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [classes/:na]
18:20:38 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
18:20:38 Caused by: java.lang.RuntimeException: Fake Exception
18:20:38 	at io.netty.handler.codec.http2.Http2ConnectionRoundtripTest$9.handlerAdded(Http2ConnectionRoundtripTest.java:253) ~[test-classes/:na]
18:20:38 	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:587) [classes/:na]
18:20:38 	... 7 common frames omitted
18:20:43 20:20:43.480 [nioEventLoopGroup-98-1] DEBUG io.netty.buffer.PoolThreadCache - Freed 5 thread-local buffer(s) from thread: nioEventLoopGroup-98-1
18:20:44 20:20:44.475 [nioEventLoopGroup-97-1] DEBUG io.netty.buffer.PoolThreadCache - Freed 3 thread-local buffer(s) from thread: nioEventLoopGroup-97-1
18:20:56 20:20:56.355 [nioEventLoopGroup-100-1] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
18:20:56 Recent access records: 0
18:20:56 Created at:
18:20:56 	io.netty.buffer.CompositeByteBuf.<init>(CompositeByteBuf.java:63)
18:20:56 	io.netty.buffer.AbstractByteBufAllocator.compositeDirectBuffer(AbstractByteBufAllocator.java:191)
18:20:56 	io.netty.buffer.AbstractByteBufAllocator.compositeBuffer(AbstractByteBufAllocator.java:169)
18:20:56 	io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder$FlowControlledData.merge(DefaultHttp2ConnectionEncoder.java:414)
18:20:56 	io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$DefaultState.enqueueFrame(DefaultHttp2RemoteFlowController.java:539)
18:20:56 	io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController.addFlowControlled(DefaultHttp2RemoteFlowController.java:215)
18:20:56 	io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeData(DefaultHttp2ConnectionEncoder.java:135)
18:20:56 	io.netty.handler.codec.http2.DecoratingHttp2FrameWriter.writeData(DecoratingHttp2FrameWriter.java:37)
18:20:56 	io.netty.handler.codec.http2.StreamBufferingEncoder.writeData(StreamBufferingEncoder.java:174)
18:20:56 	io.netty.handler.codec.http2.StreamBufferingEncoderTest.multipleWritesToActiveStream(StreamBufferingEncoderTest.java:115)
18:20:56 	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:20:56 	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:20:56 	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:20:56 	java.lang.reflect.Method.invoke(Method.java:497)
18:20:56 	org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
18:20:56 	org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
18:20:56 	org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
18:20:56 	org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
18:20:56 	org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
18:20:56 	org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
18:20:56 	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
18:20:56 	org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
18:20:56 	org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
18:20:56 	org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
18:20:56 	org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
18:20:56 	org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
18:20:56 	org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
18:20:56 	org.junit.runners.ParentRunner.run(ParentRunner.java:363)
18:20:56 	org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
18:20:56 	org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
18:20:56 	org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
18:20:56 	org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
18:20:56 	org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
18:20:56 	org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
18:20:57 20:20:57.256 [nioEventLoopGroup-101-1] DEBUG io.netty.buffer.PoolThreadCache - Freed 15 thread-local buffer(s) from thread: nioEventLoopGroup-101-1
18:20:58 20:20:58.253 [nioEventLoopGroup-100-1] DEBUG io.netty.buffer.PoolThreadCache - Freed 287 thread-local buffer(s) from thread: nioEventLoopGroup-100-1
18:20:58 20:20:58.279 [nioEventLoopGroup-104-1] DEBUG i.n.h.c.http2.Http2ConnectionHandler - Sent GOAWAY: lastStreamId '0', errorCode '1', debugData 'No more streams can be created on this connection'. Forcing shutdown of the connection.
18:20:58 20:20:58.284 [nioEventLoopGroup-103-1] DEBUG io.netty.buffer.PoolThreadCache - Freed 4 thread-local buffer(s) from thread: nioEventLoopGroup-103-1

**Comment by normanmaurer** [comment]
@louiscryan @Scottmitch @nmittler @ejona86 could you please check... Thanks!

**Comment by nmittler** [comment]
@normanmaurer, created #3909 to fix.

**Comment by Scottmitch** [comment]
thanks @nmittler!
