### ISSUE TITLE
Allow Netty 4 and 5 to be used simultaneously

### ISSUE THREAD

**Issue by benmccann** [netty/netty#3907]
I'm starting to have a lot of different libraries in my project which use Netty. That shows how successful Netty has been! The downside here is that I'm worried they depend on different versions of Netty. Right now that's not a problem because Netty 3 and Netty 4 have different package names. But I'm worried when Netty 5 comes out that if it gets pulled in, it will evict Netty 4 and cause my libraries depending on Netty 4 to fail at runtime. commons-lang and similar libraries have solved this by renaming the packages with each release, so for Netty 5 you could have something like io.netty5. Then you could have both io.netty and io.netty5 in your project without any problem

**Comment by hepin1989** [comment]
really?!based on netty5,the alpha one ?okay big move.
I think there will not have a rename,but I can see your problem we just stick on the netty 4.1 betas.

**Comment by NiteshKant** [comment]
Issue #3799 discusses the same thing. I certainly see this as an issue when netty 5.0 is ready for prime time. It wasn't an issue with the move from 3.x to 4.x as the package names changed from org.jboss to io.netty. 

The negative of this would be a big overhead for maintaining various versions w.r.t bug fixes, as I assume a simple cherry-pick would not work.

@trustin @normanmaurer et al., what are your opinions on this?

**Comment by fratboy** [comment]
There are so many popular open source projects needs Netty module, and I'm already suffering from this issue.

**Comment by benmccann** [comment]
I imagine there should be a good idea of how much work to handle backports of bug fixes since we're have to do it for bug fixes being backported from 4.x to 3.x

**Comment by normanmaurer** [comment]
Yeah the maintaining is an issue... Let me think a bit about this, but I would at least hope to drop "support" for 3.x at some point and so lighten the pain a bit.

**Comment by benmccann** [comment]
To give an example from my own project, Play Framework, Avro, Ning async HTTP client, and the MongoDB driver all depend on Netty. So I have 4 different dependencies on Netty. If one of them upgrades their Netty dependency to Netty 5 then I won't be able to use any future releases of that project unless the other three all upgrade as well.

**Comment by slandelle** [comment]
* AHC 2.0 (no, it's not named Ning, please) will come with both Netty 3 and Netty 4 support (different modules). I'll probably drop Netty 3 support for 2.1 if bringing HTTP2 support makes keeping a common API impossible.
* Play 2.5 will sit on top of Netty 4 and AHC 2.0 w/ Netty 4.
* I'm pretty confident ReactiveMongo will quickly follow

**Comment by benmccann** [comment]
There's no problem with mixing Netty 3 and 4 because the package names are different. The problem is what happens when you try to mix Netty 4 and 5 and can we avoid that being a problem and make it easier for users. I just gave one example and whether that specific example turns out to be problematic or not, there certainly will be combinations of libraries that people use that are indeed problematic.

(btw, I was referring to `"org.mongodb" % "mongodb-driver"` not ReactiveMongo)

**Comment by garydgregory** [comment]
We deal with this in Apache Commons projects all the time. Our solution is that when binary compatibility is broken, we change the package name and Maven coordinates. For example org.apache.commons.lang3.

**Comment by normanmaurer** [comment]
There is no netty 5 anymore and we not plan to work on it soon. So let me close this
