### ISSUE TITLE
Channel closed on one device but not closed on other

### ISSUE THREAD

**Issue by grgvineet** [netty/netty#3908]
Netty version : 4.0.23.Final

I am using Netty on Android, both server and client are on Android, different device. If there is a sudden network failure, like switching wifi on/off, all channels on that device are closed automatically and channelInactive is fired, while on other device channel is open, active and writable. Even writing on this channel leads to writing success and writing done.
Is there a way to detect this channel closed, or cause channel to close automatically when it is closed from other device, Can the device know immediately if channel is closed abruptly on other device like due to network failure.

**Comment by normanmaurer** [comment]
@grgvineet If the remote peer just dies the only way to detect is by writing data or try to read data.
