### ISSUE TITLE
Data frame coalescing in HTTP2 breaks with LocalChannel

### ISSUE THREAD

**Issue by louiscryan** [netty/netty#3914]
In DefaultHttp2ConnectionEncoder.FlowControlledData the use of discardReadComponents on completion of the write promise causes the slices read out of CompositeByteBuf to have invalid indices.

For local channel the write promise is completed before the received buffer is read.

Fix forthcoming

**Comment by normanmaurer** [comment]
@louiscryan is this fixed ?

**Comment by louiscryan** [comment]
yup
