### ISSUE TITLE
FixedCompositeByteBuf is broken copying bytes to direct buffers

### ISSUE THREAD

**Issue by louiscryan** [netty/netty#3915]
@normanmaurer @trustin 

In methods like

public ByteBuf getBytes(int index, ByteBuf dst, int dstIndex, int length) {

it uses 

int localLength = Math.min(length, s.capacity() - (index - adjustment));

instead of 

int localLength = Math.min(length, s.readableBytes() - (index - adjustment));

This looks like a rough copy and paste from CompositeByteBuf but unlike CompositeByteBuf it does not slice() buffers before they are added which makes capacity() == readableBytes()

This issue did not appear when copying bytes to an Unpooled buffer as that used

public ByteBuf getBytes(int index, byte[] dst, int dstIndex, int length) {

which correctly used readableBytes.

Test to demonstrate....

class FixedCompositeByteBufTest {
 ....
 

@Test
    public void testCopyingToOtherBuffer() {
        ByteBuf buf1 = Unpooled.directBuffer(10);
        ByteBuf buf2 = Unpooled.buffer(10);
        ByteBuf buf3 = Unpooled.directBuffer(10);
        buf1.writeBytes("a".getBytes(Charset.defaultCharset()));
        buf2.writeBytes("b".getBytes(Charset.defaultCharset()));
        buf3.writeBytes("c".getBytes(Charset.defaultCharset()));
        ByteBuf composite = unmodifiableBuffer(buf1, buf2, buf3);
        ByteBuf copy = Unpooled.directBuffer(3);
        ByteBuf copy2 = Unpooled.buffer(3);
        copy.setBytes(0, composite, 0, 3);
        copy2.setBytes(0, composite, 0, 3);
        copy.writerIndex(3);
        copy2.writerIndex(3);
        assertEquals(0, ByteBufUtil.compare(copy, composite));
        assertEquals(0, ByteBufUtil.compare(copy2, composite));
        assertEquals(0, ByteBufUtil.compare(copy, copy2));
    }
}

Looking at the code it seems like this issue would occur for other methods too

public ByteBuf getBytes(int index, OutputStream out, int length)
public ByteBuffer[] nioBuffers(int index, int length)

**Comment by normanmaurer** [comment]
@louiscryan sounds like a bug... would you mind creating a PR with fix + unit test?

**Comment by louiscryan** [comment]
already in progress... :)

**Comment by normanmaurer** [comment]
@louiscryan yay :) Ping me once ready for review

**Comment by normanmaurer** [comment]
Cherry-picked, thanks!
