### ISSUE TITLE
Utility method for efficient access to NIO buffers

### ISSUE THREAD

**Issue by nmittler** [netty/netty#3916]
The `SslHandler` has an optimization efficiently returning the underlying NIO buffers: https://github.com/netty/netty/blob/dec53cff86f9144c16ae446662bd4ea6e13e0a6d/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L605

This code seems rather generic and could be used in other places.

The one piece that may not be generic is the way we force a copy into a direct buffer when using OpenSSL: https://github.com/netty/netty/blob/dec53cff86f9144c16ae446662bd4ea6e13e0a6d/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L622.  I think the generic part would be everything within the first if-statement (or parameterize the method with a flag `requireDirect`).

@normanmaurer @Scottmitch WDYT?

**Comment by nmittler** [comment]
@normanmaurer gentle ping ;)

I think this should be an easy one. I'd be happy to put together a CL.  WDYT?

**Comment by normanmaurer** [comment]
@nmittler let me think a bit about it... (till tomorrow ;)).

**Comment by Scottmitch** [comment]
@nmittler - I think I created an issue or 2 when stumbling across this code 

https://github.com/netty/netty/issues/3306
https://github.com/netty/netty/issues/3358

So short term may be to pull this optimization out...but longer term I think it would be nice to have an interface which accommodates use cases more nicely.

**Comment by nmittler** [comment]
@Scottmitch awesome! ... glad you're already thinking about this :). What are the potential roadblocks to making the API changes less long-term? I'd be happy to help brainstorm.

**Comment by Scottmitch** [comment]
@nmittler - I would need to re-engage and get myself back up to speed. I spent a small amount of time thinking about the problem, but mostly just documented it.  If you have spent some cycles feel free to comment on existing issues and/or close/consolidate existing issues.  Just a quick glance back my mindset is to have an API that doesn't require special usage depending on underlying buffer counts or object type.

**Comment by nmittler** [comment]
@Scottmitch @normanmaurer @trustin @louiscryan interesting thing, we have a bunch of classes that have similar use cases:

[PendingWriteQueue](https://github.com/netty/netty/blob/ed4a89082bb29b9e7d869c5d25d6b9ea8fc9d25b/transport/src/main/java/io/netty/channel/PendingWriteQueue.java)
[CompositeByteBuf](https://github.com/netty/netty/blob/ed4a89082bb29b9e7d869c5d25d6b9ea8fc9d25b/buffer/src/main/java/io/netty/buffer/CompositeByteBuf.java)
[Stream](https://github.com/netty/netty/issues/859)
[CoalescingBufferQueue](https://github.com/netty/netty/pull/3926)

**Comment by nmittler** [comment]
@Scottmitch I'm going to close this as a duplicate of #3306. We can continue discussion there and in #3358.

**Comment by Scottmitch** [comment]
@nmittler SGTM
