### ISSUE TITLE
Can we return HTTP 400 upon malformed HTTP request?

### ISSUE THREAD

**Issue by alvinlin123** [netty/netty#3924]
This is related to https://github.com/playframework/playframework/issues/4077.

I searched the issues in github and couldn't find any related issue. 

We are using netty 2.6 and we found that if today we send an invalid http request like this `curl http://my.netty.host.com/oh I have space` netty will just throw IllegalArgumentException and close connection. 

I am wondering why not just return 400 in this case? 

This is an issue for the scenario where we fronted our netty server with some caching server. Caching server may return "5xx" if netty http server close connection with giving any response, which is a misleading status code.

**Comment by normanmaurer** [comment]
@alvinlin123 I think we only throw the exception and closing the connection is actually done by the play framework implementation when an exception is catched. I'm not sure what exact version play uses though

**Comment by alvinlin123** [comment]
Yes, looking deeper it looks like Netty just forward the exception to the next upstream. This is non issue then. Resolving. Thanks for replying.

**Comment by alvinlin123** [comment]
Actually, now I think about it upon unable to parse the HTTP request, wound't it make more sense to throw some kind of special exception instead of IllegalArgumentException?  We are using Netty 3.6 by the way. Netty do throw TooLongFrameException if the first line is too long, then I think it follows that Netty should throw, say, InvalidMessageFormatException, if it can't parse the Http message?

**Comment by trustin** [comment]
I think it's better upgrading in the long run.  `HttpObject` (the supertype of `HttpMessage` and `HttpContent`) has the `decoderResult()` property that tells you when decoding fails.  Since 4, Netty does not throw an exception on a decoding failure but emits a partial message with the information about the failure, so you can handle the decoding failure more gracefully.

With Netty 3, you don't have many options as you realized already.

**Comment by alvinlin123** [comment]
I think upgrading makes sense, but that's probably going to take some time with our production servers. 

Is Netty 3 in maintenance only mode? Is making fix to Netty 3 not possible now? I may be wrong, but catching http messge decoding error and throwing a new specialize exception should be a straight-forward and non-breaking change right?

**Comment by normanmaurer** [comment]
@alvinlin123 it's more or less in maintenance mode and we only fix bugs there atm.

**Comment by alvinlin123** [comment]
I am closing this issue because I no longer work at the company when I open this issue :)
