### ISSUE TITLE
DatagramChannel joingroup throws ClosedChannelException on Windows

### ISSUE THREAD

**Issue by darshansundaresh** [netty/netty#3925]
Netty version:4.0.30.Final

Context:
Trying to get an netty application to join a multicast group over udp throws a ClosedChannelException on windows. This however works on OSX. Sample code below.

    public class UDPMulticastTest {

        public void start() throws Exception{
            EventLoopGroup group=new NioEventLoopGroup();
            ChannelGroup allChannels=new DefaultChannelGroup("Test", ImmediateEventExecutor.INSTANCE);
            try{
                Bootstrap b=new Bootstrap();
                b.group(group)
                .channel(NioDatagramChannel.class)
                .option(ChannelOption.SO_BROADCAST,true)
                .handler(new SimpleChannelInboundHandler<DatagramPacket>() {

                    @Override
                    protected void channelRead0(ChannelHandlerContext arg0, DatagramPacket arg1) throws Exception {
                        String res=arg1.content().toString(CharsetUtil.UTF_8);
                        System.out.println(res);

                    }
                });

                InetSocketAddress hostAddress=new InetSocketAddress("239.21.208.200", 58999);
                ChannelFuture channelFuture=b.bind(hostAddress);
                channelFuture.awaitUninterruptibly();
                Channel channel=channelFuture.channel();
                DatagramChannel datagramChannel=(DatagramChannel)channel;
                NetworkInterface multicastNetworkInterface=NetworkInterface.getByName("wlan0"); //used en0 for OSX, 
                datagramChannel.joinGroup(hostAddress, multicastNetworkInterface).syncUninterruptibly();
                allChannels.add(datagramChannel);
                channel.closeFuture().await();

            }finally{
                group.shutdownGracefully();
            }
        }

        public static void main(String[] args)throws Exception{
           new UDPMulticastTest().start();
        }
    }

Exception:
        Caused by: java.nio.channels.ClosedChannelException
        at sun.nio.ch.DatagramChannelImpl.innerJoin(DatagramChannelImpl.java:832)
        at sun.nio.ch.DatagramChannelImpl.join(DatagramChannelImpl.java:894)
        at io.netty.channel.socket.nio.NioDatagramChannel.joinGroup(NioDatagramChannel.java:409)
        at io.netty.channel.socket.nio.NioDatagramChannel.joinGroup(NioDatagramChannel.java:382)
        at io.netty.channel.socket.nio.NioDatagramChannel.joinGroup(NioDatagramChannel.java:375)

java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

OS: Windows 7 Professional 64bit

**Comment by darshansundaresh** [comment]
Found the problem to be in binding to a multicast address before joining the group, which for some reason does not work on windows. Had to update the  bootstrap.bind to use a wildcard address.

>ChannelFuture channelFuture=b.bind(new InetSocketAddress(PORT_NUMBER));

**Comment by normanmaurer** [comment]
@darshansundaresh thanks for the info!
