### ISSUE TITLE
Memory almost full with io.netty.util.Recycler$DefaultHandle instances

### ISSUE THREAD

**Issue by fireinmyveins** [netty/netty#3936]
My current server config :
######################
bossGroup = new NioEventLoopGroup(1);
        workerGroup = new NioEventLoopGroup(workerThreads); //which is 2

        try {
            ServerBootstrap b = new ServerBootstrap();
            b.group(bossGroup, workerGroup).channel(NioServerSocketChannel.class).childHandler(new ChannelInitializer<SocketChannel>() {
                @Override
                public void initChannel(SocketChannel ch) throws Exception {
                    ch.pipeline().addLast(getChannelHandlers());
                }
            })
            .childOption(ChannelOption.SO_KEEPALIVE, true).childOption(ChannelOption.TCP_NODELAY, true);
#######################
and as decoder, i'm using ReplayingDecoder.
When i'm doing a test the load increases, also the memory, but after i stop the load test the memory remains in use at ~250MB.
![image](https://cloud.githubusercontent.com/assets/13166847/8500435/c8554ea0-21a4-11e5-96ae-d360b801fc51.png)
![image](https://cloud.githubusercontent.com/assets/13166847/8500441/e08bd9c6-21a4-11e5-892c-50d4b815e4c3.png)
![image](https://cloud.githubusercontent.com/assets/13166847/8500454/06b4be2e-21a5-11e5-9a7d-11e52ad1e9e2.png)
![image](https://cloud.githubusercontent.com/assets/13166847/8500584/3f625fbe-21a6-11e5-8dbb-5be46f8d73a7.png)
![image](https://cloud.githubusercontent.com/assets/13166847/8500592/53bfe210-21a6-11e5-9878-8e595ee23ba3.png)

i am decoding the received bytes and writing back new bytes using the following lines: 
##############################
ByteBuf bb = PooledByteBufAllocator.DEFAULT.buffer(b.length);
bb.writeBytes(b);
ctx.writeAndFlush(bb);
##############################
am i doing something wrong, or is it normal ?

**Comment by bobwenx** [comment]
try call `ByteBuf.release` to release buf?
```java
ByteBuf bb = PooledByteBufAllocator.DEFAULT.buffer(b.length);
try{
  bb.writeBytes(b);
  ctx.writeAndFlush(bb);
}
finally{
  bb.release();
}
```

**Comment by ThomasLau** [comment]
i think this is mainly how jvm woks,jvm will recycled heap space after gc,but wont give it back to os.
here is another detail topic http://stackoverflow.com/questions/4952568/is-there-a-way-to-lower-java-heap-when-not-in-use

**Comment by fireinmyveins** [comment]
i'm not concerned with the max heap size, what worries me is that the used heap contains ~250 MB of "?useless?" objects.

**Comment by normanmaurer** [comment]
@fireinmyveins you may want to adjust the max number of objects that are cached by the Recycler if you need to ensure the memory foot print is lower. 

see:
https://github.com/netty/netty/blob/4.0/common/src/main/java/io/netty/util/Recycler.java#L51
