### ISSUE TITLE
MqttDecoder.decodeAsciiString() may result in an npe.

### ISSUE THREAD

**Issue by ThomasLau** [netty/netty#3937]
hey,guys,currently i'm learning netty codec-mqtt,and i noticed these code:
[MqttDecoder line413](https://github.com/netty/netty/blob/master/codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttDecoder.java)

``` java
    Result<String> result = decodeString(buffer, 0, Integer.MAX_VALUE);
    final String s = result.value;
    for (int i = 0; i < s.length(); i++) {
        if (s.charAt(i) > 127) {
            return new Result<String>(null, result.numberOfBytesConsumed);
        }
    }
  private static Result<String> decodeString(ByteBuf buffer, int minBytes, int maxBytes) {
    final Result<Integer> decodedSize = decodeMsbLsb(buffer);
    int size = decodedSize.value;
    int numberOfBytesConsumed = decodedSize.numberOfBytesConsumed;
    if (size < minBytes || size > maxBytes) {
        buffer.skipBytes(size);
        numberOfBytesConsumed += size;
        return new Result<String>(null, numberOfBytesConsumed);
    }
    ByteBuf buf = buffer.readBytes(size);
    numberOfBytesConsumed += size;
    return new Result<String>(buf.toString(CharsetUtil.UTF_8), numberOfBytesConsumed);
    }
```

we can see from above that decodeString may "return new Result<String>(null, numberOfBytesConsumed);", and "final String s = result.value;" may lead s to a null value,as a result, "s.length()" get a chance to throw a NPE.

hope that helps.brs.

**Comment by bobwenx** [comment]
In most case, this will not happen, because MQTT message's payload can not exceeds `268,435,455`(256 MB). 
the code just check range between 0 - Integer.MAX(2147483647).

see 2.2.3: http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html

if the client send a invalid MQTT message(without payload), then, i think throw exception is reasonable option.

**Comment by ThomasLau** [comment]
tks @bobwenx , ye,i can see that there is a range check before,however, i don't think here we throw an "exception",i think this exception is made by s.length() itself,but not a validation logic.

**Comment by bobwenx** [comment]
the `s.length()` call only happen in MqttDecoder, all private static `decodeXX` method only be invoke by `MqttDecoder.decode`. 
so if any exception throws, it will be treat as decoding failure.  
from the perspective of decoder, it's the same: the message is invalid.

**Comment by ThomasLau** [comment]
@bobwenx yes,that sounds reasonable,and does that mean we could take no care of any exception that caused by our code but not by illegal inputs,just because the call method will catch all exception?

i think,as you mentioned,in that scenario, we may throw an illegalinputexception or sth,before we use 
 *s.length()*

**Comment by normanmaurer** [comment]
I agree... I think we can just close it
