### ISSUE TITLE
Congestion control in Netty

### ISSUE THREAD

**Issue by zhenyu-zhou** [netty/netty#3939]
Hello, 

I'm trying to understand congestion control in Floodlight, which implements Netty to handle its control channel. I find that if I burst to send more than around 1000 pkt-in, pkts begin to loss. I have asked the Floodlight people but they said they did not make this control by default and suggested me to look into Netty. Therefore I'm wondering whether there is such mechanism in Netty (where is it)? And is it possible to configure this mechanism by myself (eg, modify the threshold or even disable it)?

Many thanks!

**Comment by normanmaurer** [comment]
@zhenyu-zhou we not do any controlling by our own. What we have is the ability to get notified when a Channel becomes non writable and writable again. It's up to the user to back-up and continue in this cases-
