### ISSUE TITLE
netty-all-5.0.0.Alpha2 have memory leak?

### ISSUE THREAD

**Issue by icecooly** [netty/netty#3940]
i am using netty-all-5.0.0.Alpha2 

have such test
client:
ExecutorService service=Executors.newFixedThreadPool(10,new ContainerThreadFactory("TestGameServerClient"));
for(int i=0;i<1;i++){
        	TestGameServerClient client=new TestGameServerClient(host, port);
        	service.execute(client);
}
 @Override
    public void run() {
    	while(true){
        	if(isConnected){
        		write("{}\n");
        	}
        	try {
			Thread.sleep(10000);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
        }
    };

server
@Override
public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
     channel.writeAndFlush((GameResponseMessage)rspMessage);
}

i have this  test for 4 hours    then I found this result

 num     #instances         #bytes  class name
----------------------------------------------
   1:        312301       24993976  [Ljava.util.HashMap$Node;
   2:        312091       14980368  java.util.HashMap
   3:        311355       14945040  io.netty.channel.DefaultChannelPromise
   4:        315862       12634480  io.netty.channel.DefaultChannelHandlerInvoker$WriteTask
   5:        311353       12454120  org.elephant.gameserver.core.GameResponseMessage
   6:        315886       10108352  io.netty.util.Recycler$DefaultHandle
   7:        315135       10084320  java.util.HashMap$Node
   8:        311360        7472640  io.netty.util.internal.MpscLinkedQueue$DefaultNode

why GameResponseMessage is more and more?

if I delete channel.writeAndFlush((GameResponseMessage)rspMessage); 
then no such problem

**Comment by icecooly** [comment]
jmap -histo 2446

**Comment by icecooly** [comment]
i found the problem   when i use netty-all-5.0.0.Alpha1 is ok .  so  it is netty-all-5.0.0.Alpha2 bug

**Comment by normanmaurer** [comment]
Can you provide a simple reproducer and a heapdump?

**Comment by icecooly** [comment]
how can i emai my test project to u

**Comment by normanmaurer** [comment]
@icecooly norman dot maurer at googlemail dot com

**Comment by icecooly** [comment]
already send mail to u,  thx

**Comment by normanmaurer** [comment]
Let me close this... master branch is dead
