### ISSUE TITLE
Memory leak in SslHandler with ALPN

### ISSUE THREAD

**Issue by nmittler** [netty/netty#3941]
gRPC has a report of a memory leak related to ALPN: https://github.com/grpc/grpc-java/issues/598

Looking at the [SslHandler code](https://github.com/netty/netty/blob/dec53cff86f9144c16ae446662bd4ea6e13e0a6d/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L406), it looks like we close the `SslEngine` in `disconnect` and `close`.  I'm wondering if we have a missing event handler here. IIUC, both `disconnect` and `close` are user-initiated events and wouldn't be executed if the channel shutdown for some other reason.  I wonder if we also need to do this for something like `channelInactive`.

@normanmaurer WDYT?

/cc @ejona86 @ohad7

**Comment by normanmaurer** [comment]
@nmittler I think it should be correct:

https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L699
https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L1279

Here it calls closeInbound() and closeOutbound() which should cleanup stuff or I'm missing something ?

**Comment by nmittler** [comment]
@normanmaurer ah, I missed that - yeah, that should do it :/.

**Comment by nmittler** [comment]
Closing this as it doesn't look like it's a Netty issue afterall.
