### ISSUE TITLE
DNS resolver does not optimize text-format IP address queries

### ISSUE THREAD

**Issue by erimatnor** [netty/netty#3943]
Netty's DNS resolver seems to send DNS queries for any text-based hostname without first checking if the hostname is already a text-format IP address (e.g., "127.0.0.1" or "0.0.0.0"). Some DNS servers do not resolve such hostnames, causing failures. Ideally, Netty's DNS resolver should also check/parse the local /etc/hosts to avoid unnecessary lookups of well-known static hostnames (e.g., "localhost").

**Comment by normanmaurer** [comment]
@erimatnor we not do a dns lookup anymore when an ip is used.
