### ISSUE TITLE
Http2ConnectionHandler breaks channelReadComplete pipeline notification

### ISSUE THREAD

**Issue by blucas** [netty/netty#3945]
Netty Version: 5.0.0-Alpha3-SNAPSHOT

Hi guys,

```Http2ConnectionHandler``` overrides ```channelReadComplete(...)``` [here](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L421) but fails to pass notification further down the pipeline by calling ```super.channelReadComplete(...)``` or ```ctx.fireChannelReadComplete(...)```.  I assume it should call ```super.channelReadComplete(...)```, what are your thoughts? 

/cc @Scottmitch @nmittler @louiscryan as you guys know more about this :)

**Comment by normanmaurer** [comment]
@blucas makes sense. We love PRs as you know ;)

**Comment by nmittler** [comment]
+1 to PRs :)

**Comment by normanmaurer** [comment]
Let me fix this.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/3948#issuecomment-119327866
