### ISSUE TITLE
HttpToHttp2ConnectionHandler does not support converting from Http(Message|Content) to Http2 frames

### ISSUE THREAD

**Issue by blucas** [netty/netty#3946]
Is there a reason why ```HttpToHttp2ConnectionHandler``` does not support converting from ```Http(Message|Content)``` to Http2 frames?  Is there something that the handler requires that it cannot retrieve?  Or some data missing from ```Http(Message|Content)``` that is required?

My use case is that I have an ```HttpContentCompressor``` further down the pipeline, which ends up creating ```HttpMessage``` and ```HttpContent``` objects and sending them to ```HttpToHttp2ConnectionHandler``` which is then not being converted to Http2 frames.

For now I have extended ```HttpToHttp2ConnectionHandler``` and overridden the ```write(...)``` to support ```Http(Message|Content)```, but I think something like this should be in Netty directly.

**Comment by nmittler** [comment]
/cc @Scottmitch 

Looks like `HttpToHttp2ConnectionHandler` currently requires `FullHttpMessage`.  I don't recall whether or not there was a reason that it couldn't take `HttpMessage` or `HttpContent`.  Contributions are always welcome :)

**Comment by Scottmitch** [comment]
I think the main driver was HTTP generally has no proper framing and no stream concept. Without building higher level abstractions it is difficult to correlate one `HttpContent` with a particular stream.  `FullHttpMessage` provides the accumulation of all data and definitively associates all HTTP objects with a stream ID.

We may be able to create some kind of interface which combines `HttpMessage` and something that provides a stream id (i.e `int http2StreamId()`), but I haven't investigated it too much.

**Comment by blucas** [comment]
I'm more than willing to help out with this.  As I've stated previously, I have already implemented a rough draft that caters for my scenario.

@Scottmitch addressing the lack of a streaming concept, could we take the same approach used in the SPDY handlers by tracking the current stream ID? (see [here](https://github.com/netty/netty/blob/master/codec-http/src/main/java/io/netty/handler/codec/spdy/SpdyHttpEncoder.java#L121) [here](https://github.com/netty/netty/blob/master/codec-http/src/main/java/io/netty/handler/codec/spdy/SpdyHttpEncoder.java#L163) and [here](https://github.com/netty/netty/blob/master/codec-http/src/main/java/io/netty/handler/codec/spdy/SpdyHttpEncoder.java#L278))

Other question I have is what do we do about trailing headers?  It doesn't seem like the current HTTP/2 implementation converts ```FullHttpMessage``` HTTP/1 trailing headers into some HTTP/2 Frame (I assume we'd use a HEADERS frame as specified in [HTTP Request/Response Exchange](https://http2.github.io/http2-spec/#rfc.section.8.1) point 4.).

**Comment by Scottmitch** [comment]
> @Scottmitch addressing the lack of a streaming concept, could we take the same approach used in the SPDY handlers by tracking the current stream ID? (see here here and here)

Yes I think that is inline with what I was thinking.

> Other question I have is what do we do about trailing headers? It doesn't seem like the current HTTP/2 implementation converts FullHttpMessage HTTP/1 trailing headers into some HTTP/2 Frame (I assume we'd use a HEADERS frame as specified in HTTP Request/Response Exchange point 4.).

Yes if we are ignoring trailing headers then that is a bug.  The HTTP/2 codec should support this just by doing a `writeHeaders(..)` call. We should just take care to end the stream at the appropriate time.

**Comment by normanmaurer** [comment]
Sounds good. Any takers?

**Comment by blucas** [comment]
I can give this a shot tonight.  I'll let you know how I get on.

**Comment by blucas** [comment]
Hey guys,

Sorry its taken so long... [here it is](https://github.com/netty/netty/pull/3975)

**Comment by blucas** [comment]
Closing this issue now that the pull request has been cherry-picked into master (3ec02bf) and 4.1 (57d28dd)
