### ISSUE TITLE
Regression in codec-http 4.1.0.Beta4 and later

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#3962]
Regression caused by this commit:

https://github.com/netty/netty/commit/50e06442c3f2753c9b2a506f68ea70273b829e21

Before commit:

```
xxx:~/wrk $ ./wrk -H 'Host: localhost' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Connection: keep-alive' -d 120 -c 256 -t 16 -s scripts/pipeline-many.lua http://xxx:8080/plaintext
Running 2m test @ http://xxx:8080/plaintext
  16 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    18.74ms   11.25ms 120.51ms   65.93%
    Req/Sec   223.31k    31.27k  356.48k    67.88%
  421663332 requests in 2.00m, 56.94GB read
Requests/sec: 3514774.03
Transfer/sec:    486.03MB
```

After commit:
```
xxx:~/wrk $ ./wrk -H 'Host: localhost' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Connection: keep-alive' -d 120 -c 256 -t 16 -s scripts/pipeline-many.lua http://xxx:8080/plaintext
Running 2m test @ http://xxx:8080/plaintext
  16 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    28.89ms   14.90ms 170.28ms   74.57%
    Req/Sec   144.45k    17.11k  236.67k    68.90%
  274236571 requests in 2.00m, 37.03GB read
Requests/sec: 2285750.92
Transfer/sec:    316.08MB
```

**Comment by normanmaurer** [comment]
![screen shot 2015-07-09 at 12 31 11](https://cloud.githubusercontent.com/assets/439362/8593779/1627822a-263b-11e5-9936-9c8c1fb5d525.png)

Seems like the new header implementation is the problem... Will investigate

/cc @trustin @Scottmitch

**Comment by normanmaurer** [comment]
@Scottmitch @trustin I hacked together a version of 4.1.0.Beta6-SNAPSHOT that used the old DefaultHttpHeaders again and with it we are fast enough. I think we need to investigate what to do. While  revert the change for HTTP sounds fine at the first place I wonder if we need to investigate why the new implementation is so slow first as it may be used by others as well. WDYT ?

**Comment by Scottmitch** [comment]
@normanmaurer I anticipate @buchgr header improvement PR will rectify this. I have some follow up plans to investigate after these are pulled in too.

**Comment by Scottmitch** [comment]
@normanmaurer - can you run the benchmark with PR https://github.com/netty/netty/pull/3681?

**Comment by normanmaurer** [comment]
Yep will do

**Comment by normanmaurer** [comment]
@Scottmitch its better but still by far not in the same ball park compared to the old header impl:

```
xxx:~/wrk $ ./wrk -H 'Host: localhost' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Connection: keep-alive' -d 120 -c 256 -t 16 -s scripts/pipeline-many.lua http://xxx:8080/plaintext
Running 2m test @ http://xxx:8080/plaintext
  16 threads and 256 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    29.84ms   67.95ms   1.16s    97.64%
    Req/Sec   190.77k    39.62k  272.32k    81.99%
  354215750 requests in 2.00m, 47.83GB read
Requests/sec: 2952474.25
Transfer/sec:    408.28MB

```

**Comment by buchgr** [comment]
talked with @normanmaurer . working on it....

**Comment by normanmaurer** [comment]
@nmittler FYI as you asked for a new release... I think this is a blocker which we really need to fix first.

**Comment by nmittler** [comment]
@normanmaurer Yeah, agreed. Maybe I can entice @buchgr with :beers: :)

**Comment by normanmaurer** [comment]
Good plan!

**Comment by buchgr** [comment]
@nmittler oh you know me :smile:. will work on it this weekend.

**Comment by Scottmitch** [comment]
@trustin @buchgr @normanmaurer - I am working on rectifying the performance issues. I attempted to adapt the old DefaultHttpHeaders from 4.0 to the `Map` interface and use in #3681 but the perf metrics as reported by @normanmaurer were not satisfactory.  I have been seeing promising results by making the DefaultHeaders implementation based upon the implementation in of DefaultHttpHeaders in 4.0.  These changes are built on the shoulders of @buchgr's #3681 PR and if all goes well I think we should merge this PR and then review the followup PR that is in the works now.  I am going to validate performance numbers with @normanmaurer and if everything checks out expect a PR next week.

**Comment by nmittler** [comment]
@Scottmitch awesome! Looking forward to seeing the numbers!

**Comment by normanmaurer** [comment]
I think we can close this now
