### ISSUE TITLE
Make FrameWriter responsible for chunking writes by the frame size limit

### ISSUE THREAD

**Issue by louiscryan** [netty/netty#3966]
@Scottmitch @nmittler 

Currently the DefaultHttp2ConnectionEncoder.FlowControlledData is responsible for chunking writes by the flow-control limit as well as by max frame size.

Moving the chunking by frame-size into the frame writer allows it to be more efficient by allocating fewer buffers for the frame-prefix

**Comment by nmittler** [comment]
+1

@louiscryan are you working on a PR for this?

**Comment by louiscryan** [comment]
Not yet but its on my todo list.

**Comment by Scottmitch** [comment]
> Moving the chunking by frame-size into the frame writer allows it to be more efficient by allocating fewer buffers for the frame-prefix

@louiscryan - Can you expand on this a bit more? By `frame-prefix` do you mean the header portion of the frame?

**Comment by louiscryan** [comment]
Yes, say we are going to write N bytes in X sized frames. Then we need to write

N/X frame headers of size X and possibly one N % X sized frame. Today we do separate allocations for each of these headers when for any write we should have a max of 2.

**Comment by Scottmitch** [comment]
@louiscryan - Thought so :) So you will just take care to call `retain(N/X)` before writing the header buffer representing the X sized frames (and make sure you call `write` `N/X` times...or possibly `release` if you encounter failures)
