### ISSUE TITLE
SslHandler does not support FileRegion

### ISSUE THREAD

**Issue by nmittler** [netty/netty#3968]
I suspect that means that FileRegions would leak through unencrypted.

@normanmaurer is that right?

**Comment by normanmaurer** [comment]
Yes it does not support FileRegion as the whole point of using a FileRegion is to not transfer stuff to the user-space. I guess what we could do is just copy it to a ByteBuf.

**Comment by nmittler** [comment]
@normanmaurer I think failing if `SslHandler` receives a `FileRegion` may also be a reasonable (and simpler) change.  WDYT?

**Comment by normanmaurer** [comment]
@nmittler maybe... But I guess I could make the other work as well which would make it easier for the user... Let me check
