### ISSUE TITLE
Have (Int,Long,Char,...)ObjectMap implement Map interface.

### ISSUE THREAD

**Issue by buchgr** [netty/netty#3970]
I just noticed that Netty's primitive hash map implementations don't implement the JDK's `Map` interface. I think they would be much more useful if they did.

**Comment by buchgr** [comment]
Just do something like this:

```java
class IntObjectHashMap implements Map<Integer, Object> {
  public Object put(Integer key, Object value) {
    put(key.intValue(), value);
  }
  
  public Object put(int key, Object value) {
    // implementation goes here.
  }
}
```

That way one can use this as a normal `Map` and all those `IntObjectMap`, `LongObjectMap` interfaces can be deleted.

@nmittler @normanmaurer

**Comment by normanmaurer** [comment]
@buchgr the problem is that this will add extra boxing.

**Comment by nmittler** [comment]
I think it would be fine if there were boxing methods in addition to the existing non-boxing methods.

**Comment by buchgr** [comment]
@normanmaurer No it doesn't in my example above ?

**Comment by normanmaurer** [comment]
@nmittler @buchgr right if we keep both it would be fine

**Comment by buchgr** [comment]
@normanmaurer @nmittler I think we should do it before 4.1 is released. Map implementation would be much more elegant and useful. We should also get rid of the custom interfaces. WDYT?

**Comment by nmittler** [comment]
@buchgr Absolutely, I can't wait to review the PR that you put together without any help from us whatsoever! :stuck_out_tongue_winking_eye:

**Comment by normanmaurer** [comment]
lol

**Comment by buchgr** [comment]
@nmittler well I would really love to do that, but most unfortunately my hands are tied due to the nice folks at legal :-). 

However, to our rescue I do know a great and highly motivated dev at Google who would be perfect for the job *wink* *wink*! And you know ... I am a nice guy, so I am happy to with extreme care and in most detail review and comment on every line of that sweet PR :laughing:

**Comment by nmittler** [comment]
*sigh* ... I guess that would be "googly" of me :/

**Comment by nmittler** [comment]
@buchgr I've thrown together #3984 ... I await my free beer! ;)

**Comment by buchgr** [comment]
@nmittler I ll make it a pitcher boss :laughing:

**Comment by nmittler** [comment]
+1 :)
