### ISSUE TITLE
Expiration date of io.netty.handler.ssl.util.SelfSignedCertificate fails with iOS 8

### ISSUE THREAD

**Issue by ganskef** [netty/netty#3978]
iOS 8 (tested with 8.1.3) revokes certificates with expiration date set to the maximum possible value in X.509 specification: 9999-12-31 23:59:59. 
```java
    /** The maximum possible value in X.509 specification: 9999-12-31 23:59:59 */
    static final Date NOT_AFTER = new Date(253402300799000L);
```
@forestofrain has investigated the maximum date Mon, 24 Jan 6084 02:07:59 GMT. (see: ganskef/LittleProxy-mitm#6) I'm wondering, it could be a bug at Apple, but I've no idea, how to file an issue there.

Please consider to use an other expiration date, to support iOS devices for testing purposes.

**Comment by Scottmitch** [comment]
@ganskef - Have you observed this behavior with just the simulator, or does the phone also exhibit this behavior?

**Comment by ganskef** [comment]
Sorry for delay, I've missed your question. I've reproduced it with an iPad mini with iOS 8.1.3. It works well after fixing the proxy application. Please have a look at ganskef/LittleProxy-mitm#6.

**Comment by ganskef** [comment]
@Scottmitch ping

**Comment by Scottmitch** [comment]
@ganskef - I think we can make the NOT_BEFORE and NOT_AFTER dates configurable via system properties. Will that work for you?

**Comment by Scottmitch** [comment]
Fixed by https://github.com/netty/netty/pull/4257
