### ISSUE TITLE
Netty Pooled Buffer Caching from different threads

### ISSUE THREAD

**Issue by mspavan052** [netty/netty#3982]
Hi, 

     In our application we are using the netty 4.0.27, its a simple client and server program. 
        Client
                 i) Application thread will create the netty Bytebuf and update the request to it 
                ii) Then the same application will call channelHandlerContext.writeAndFlush(ByteBuf)
               iii) When receive the messages it will be given to the application & application will
take the ByteBuf directly and decode the message using multiple threads as the decoding
is very slow 

    As netty maintains the pooled cache at the thread level, even though we specify Pooled buffer
its really not buffering because 
  Sending Side
          a) ByteBuf is created by application thread T-1 
          b) Netty IO thread - pool-1-thread-1 writes to the under laying channel and invoke 
               io.netty.channel.ChannelOutboundBuffer.remove()
          c) io.netty.buffer.PoolArena.free(PoolChunk<T>, long, int, boolean) will check the initialize thread and current thread are same, If same then only it will be cached in the pool else it wont cache. 
     
    As in our case both threads are different its not caching, Is there any other approach to 
utilize the pooled buffer. 

   Here important point is the application encoding and decoding is time consuming, so it must be done in multiple thread

With Regards,
Kumar

**Comment by normanmaurer** [comment]
@mspavan052 Upgrade to netty 4.0.29.Final and it will work even for your use-case :)

https://github.com/netty/netty/commit/f765053ae740e300a6b696840d7dfe5de32afeb3

**Comment by mspavan052** [comment]
Thanks for the quick response, Can you please let me know what is the change

**Comment by normanmaurer** [comment]
@mspavan052 see my above comment... I linked the commit sha there. Just click on it.

**Comment by ywengineer** [comment]
@normanmaurer this commit will be merged to 5.0.0-Alpha2 at what time?

**Comment by normanmaurer** [comment]
@ywengineer it is also in master already.

**Comment by mspavan052** [comment]
@normanmaurer Why io.netty.util.Recycler.DefaultHandle<T> is still based on the Threadlocal i.e., 
Object pool is happening at the single thread level, So we will get same problem as were facing in the Buffer. 

Now we used 4.0.29 as suggested by you, now i can see the Buffers are reused its one great change But number of io.netty.util.Recycler.DefaultHandle<T> is very high and may be this is the reason no performance improvement we observed with 4.0.29. 

Can you please let me know the feasibility of making this pool also generic

**Comment by dozer47528** [comment]
This is a bug or just a performance issue?
My application will allocate and deallocate in different thread.
The application continuously eating memory, and I can't find the root case.
