### ISSUE TITLE
Epoll support for SCTP?

### ISSUE THREAD

**Issue by Tylerian** [netty/netty#3983]
Hello, 
SCTP currently has NIO and OIO implementations, but is not implemented with Epoll.
So... Is there any future plan to support SCTP with epoll?

Many Thanks

**Comment by normanmaurer** [comment]
@Tylerian not at the moment.. that said we love contributions

**Comment by normanmaurer** [comment]
Let me close this for now as we not have any plans for this.

**Comment by gaurav-4g** [comment]
Hi @normanmaurer , any plan for SCTP over epoll now? We got significant performance gain for TCP over epoll.

**Comment by normanmaurer** [comment]
nope not really
