### ISSUE TITLE
Documentation: wrong class mentioned in setter

### ISSUE THREAD

**Issue by justinjhendrick** [netty/netty#3997]
{@link ByteBufAllocator} -> {@link MessageSizeEstimator} on
https://github.com/netty/netty/blob/4.0/transport/src/main/java/io/netty/channel/ChannelConfig.java#L248

this effects 4.0, 4.1, and master branches

**Comment by Scottmitch** [comment]
@justinjhendrick - Thanks for pointing this out.  Also feel free to submit a PR and get credit for fixing :)

**Comment by justinjhendrick** [comment]
@Scottmitch, I would but my company wants to review any open source before we contribute. So, something small like this wouldn't be worth the time necessary for a review.

**Comment by normanmaurer** [comment]
No worries I will fix it

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4003
