### ISSUE TITLE
Use Netty 5.0.0.Alpha2 as proxyserver failed！

### ISSUE THREAD

**Issue by longlong524** [netty/netty#4004]
I am developing a proxies manager server with netty 5.0.0.Alpha2-SNAPSHOT named beastkeeper, you can see it as a proxy server. And the server's initChannel method code:

    protected void initChannel(Channel ch) throws Exception {
					
					 ChannelPipeline pipeline = ch.pipeline();

				        pipeline.addLast( new HttpRequestDecoder());

				       
				       pipeline.addLast("aggregator", new HttpObjectAggregator(1048576*1024));
				        pipeline.addLast(new HttpResponseEncoder());
				        pipeline.addLast("redeflater", new HttpContentCompressor());

				       pipeline.addLast(new NettyHttpServerHandler(manager));
				       
				        
				}	

And I test with chrome，firefox, htmlunit ,ie, phantomjs, java's url connection.
I send http request as belows:

      GET http://www.sogou.com/ HTTP/1.1
      Host: www.sogou.com
      Proxy-Connection: keep-alive
    Pragma: no-cache
    Cache-Control: no-cache
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)         Chrome/43.0.2357.132 Safari/537.36
    Accept-Encoding: gzip, deflate, sdch
    Accept-Language: zh-CN,zh;q=0.8

The result is that java's urlconnection, htmlunit , phantomjs is good but chrome, firefox, ie return 200 ok but have an ERR_CONTENT_DECODING_FAILED error. The http response header:

    HTTP/1.0 200 OK
    Server: nginx
    Date: Mon, 20 Jul 2015 01:50:22 GMT
    Content-Type: text/html
    Vary: Accept-Encoding
    Expires: Mon, 20 Jul 2015 01:50:22 GMT
    Cache-Control: max-age=0
    Connection: close
    Content-Encoding: gzip
    Transfer-Encoding: chunked

I use wireshark to see chrome's  http response, and it shows chunked encoding is correct, and gzip decoding is correct. But chrome show me ERR_CONTENT_DECODING_FAILED. 

I doubt the netty's gzip have some problems because chrome returns 4580 bytes compressed data with beastkeeper and  returns 4574 bytes compressed data with no beastkeeper. Something weird is both of them can be uncompressed by java's GZIPInputStream with no error. 

Now I don't know why. Could you help me?

**Comment by normanmaurer** [comment]
Please try latest version and reopen if you still have issues
