### ISSUE TITLE
Netty 5.0.0.Alpha2-SNAPSHOT can't parse http response with no header

### ISSUE THREAD

**Issue by longlong524** [netty/netty#4005]
I want to test proxy's https tunneling protocol.
I write a simple httpclient with 5.0.0.Alpha2-SNAPSHOT like this:
```
ChannelPipeline pipeline = ch.pipeline();
pipeline.addLast(new HttpResponseDecoder());
 pipeline.addLast("redeflater", new HttpContentDecompressor());
pipeline.addLast("aggregator", new HttpObjectAggregator(1048576*1024));
 pipeline.addLast( new HttpRequestEncoder());
```

and I send a connect request to a proxy 97.77.104.22:80(you can get a free  proxy from http://cn-proxy.com/) like this
```
FullHttpRequest req=null;
req=new DefaultFullHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.CONNECT, "www.baidu.com:443");
req.headers().add("Proxy-Connection","Keep-Alive");
req.headers().add("Host","www.baidu.com");
req.headers().add("User-Agent", "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36");
```

But netty cann't  get the response until more than 120 seconds. 
The response is :
```
Response: HTTP/1.0 200 Connection established\r\n\r\n
```
I think the reason is there is no header.

**Comment by Scottmitch** [comment]
@longlong524 - Sorry I missed this. Are you still experiencing this issue? Can you try again with 5.0.0.Alpha3?  Do you have a reproducer?

**Comment by Scottmitch** [comment]
5.x has been deprecated. Please try again with the latest 4.1 release and reopen if this still exists.
