### ISSUE TITLE
CompositeByteBuf leak detector design pattern different from other ByteBuf implementations

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4017]
The `CompositeByteBuf` implementation has a `ResourceLeak` member variable and other `ByteBuf` implementations rely on the `ByteBufAllocator` (particularly `AbstractByteBufAllocator`) to wrap the object and provide simple/advanced levels of leak detection.  Is there a reason why `CompositeByteBuf` needs to be different? On the surface it seems like the preferred approach is have `CompositeByteBuf` to remain consistent with the other `ByteBuf`implementations.  This provides separation of concerns and also avoids maintaining an extra member in `CompositeByteBuf` which may not be used.

**Comment by Scottmitch** [comment]
@normanmaurer @trustin - Any thoughts?

**Comment by nmittler** [comment]
+1 thanks for creating @Scottmitch

**Comment by normanmaurer** [comment]
@Scottmitch +1

**Comment by trustin** [comment]
@Scottmitch +1

**Comment by Scottmitch** [comment]
@nmittler - Looks like we have our answer :)  I'll take the assignment for now so it doesn't get dropped...feel free to take it though.

**Comment by nmittler** [comment]
@Scottmitch FYI this isn't a super high priority item for us ... I'm probably not going to pick it up any time soon.

**Comment by normanmaurer** [comment]
Taking so we get this fixed before the next release (which will be this week!) :)
