### ISSUE TITLE
Implement IP_FREEBIND and Any-IP in native JNI base epoll

### ISSUE THREAD

**Issue by burtonator** [netty/netty#4022]
It would be really nice to have netty support IP_FREEBIND and Any-IP.

Essentially it allows you to bind() to any IP address, even if it's not associated with an Interface.

I was thinking this could be really helpful in ipv6 setups whereby you just setup your webserver on a subnet with 16k IPs and then when you want to deploy a new webapp, you just give it one of those IPs.

The problem is that your box wouldn't want to manually add every IP as your ifconfig would then list 16k IPs.

With Any-IP you can add a whole subnet in one command.

Then you can bind sockets to it..

The PROBLEM is I can't find out how to do this with Java .  Using netty would allow you to build really awesome apps this way but I don't think you can bind sockets this way in Java.

The C programmers always seem to get the cool toys before we do!

http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=ab79ad14a2d51e95f0ac3cef7cd116a57089ba82

  IP_FREEBIND (since Linux 2.4)
              If enabled, this boolean option allows binding to an IP
              address that is nonlocal or does not (yet) exist.  This
              permits listening on a socket, without requiring the
              underlying network interface or the specified dynamic IP
              address to be up at the time that the application is trying to
              bind to it.  This option is the per-socket equivalent of the
              ip_nonlocal_bind /proc interface described below.

... I may be looking at this in the next few weeks/months and if so will just implement it myself.

**Comment by Scottmitch** [comment]
@burtonator - Thanks for reaching out! Sounds like a useful feature. I'll put this on the todo list but if you get around to it before we do please feel free to submit a PR.

**Comment by normanmaurer** [comment]
Thanks will check once i have a fee cycles

**Comment by normanmaurer** [comment]
@burtonator please check https://github.com/netty/netty/pull/4034

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4034
