### ISSUE TITLE
Need ability to U Turn at a given ChannelInboundHandlerAdapter

### ISSUE THREAD

**Issue by gitai** [netty/netty#4028]
I would like to build a handler that will co-exist with other handlers in the pipeline but will only process selected messages. My understanding is that events always propagate to the next handler and I would like to avoid this for specific messages. I don’t want to remove handlers or close the connection; simply put I want to instruct the pipeline to consider the previous handler as the ‘head’ for full writes. 

Is there support for such behavior? if not it would be convenient to have an additional boolean returning method like IsConsumed on ChannelInboundHandlerAdapter which can be queried by the pipeline to observe such request.

10x.

**Comment by NiteshKant** [comment]
Any message only goes to the next handler in the pipeline if done so explicitly via `ChannelHandlerContext.fireXXX()` methods. So, if any handler, in its `channelRead()` method does not call `ChannelHandlerContext.fireChannelRead()` for any received message, it is deemed to be terminally consumed by that handler.

**Comment by gitai** [comment]
Thanks. I now see it in ByteToMessageDecoder ...

But what about write? Correct me if I'm wrong, If I call it on the current ChannelHandlerContext the write will be handled by the "next" Handler but I would like to avoid this for the case where the "next" handler is also an Outbound handler and is of no relevance to the current handler response.

**Comment by gitai** [comment]
I have yet to delve into the internals but glimpsing through AbstractChannelHandlerContext it seems that any write operation takes into account the configured executer assigned to the next outbound handler, so I presume that if an EventExecuterGroup is configured for a successive handler then any write event triggered from the current handler to the next (outbound) handler would be dispatched outside the eventloop, which is unnecessary per my use-case..

**Comment by NiteshKant** [comment]
_DISCLAIMER: The following is my opinion based on my usage of netty._

>> but I would like to avoid this for the case where the "next" handler is also an Outbound handler and is of no relevance to the current handler response.

In general having a handler be aware of the pipeline configuration (i.e. who is next and whether it can handle a message) isn't a good idea. Instead the handler itself should decide whether to process a message or just pass it through (when not applicable). So, if the handler chain is:

```
Handler A -> Handler B -> Handler C
```

and Handler can only handle message MA, Handler B handles MB ... etc then the code in each of the handler should look like:

```
 if(msg instance of MX) {
    /// process
} else {
   ctx.write(msg);
}
```

instead of any handler trying to determine which handler should be invoked next.

>>> then any write event triggered from the current handler to the next (outbound) handler would be dispatched outside the eventloop, which is unnecessary per my use-case..

All handlers are associated with an executor and are always invoked by that executor. If the handler is not supposed to be executed in a different executor, then one should not specify any executor while adding that handler to the pipeline.

I think the meta point here is that you are trying to have a handler decide how & when to execute other handlers in the pipeline, which I don't think is a good idea as those handlers then are tied to a particular pipeline configuration and not generically applicable.

**Comment by gitai** [comment]
> DISCLAIMER: The following is my opinion based on my usage of netty.

Just to make sure we're on the same page. I’m referring to netty 4.0.30. I have no idea how things work in other versions.

>In general having a handler be aware of the pipeline configuration (i.e. who is next and whether it can handle a message) isn't a good idea.

This is orthogonal to my requirement for early "bail out" which in general should not have any impact on a successor handler as no “output” is handed over. I argue that a complete traversal of all channel handlers even from a given point is too strict.

Per your previous comment this is easy to achieve on the Inbound Path by simply avoiding a call to ChannelHandlerContext.fireChannelRead() 

The issue now concerns the Outbound Path where it appears that writes are bound to execute by whatever executer is configured for the next configured channel outbound handler, which can have totally different threading semantics and/or overridden write behavior.

>Instead the handler itself should decide whether to process a message or just pass it through (when not applicable)

I’m reluctant to agree with you in principle but there are other issues that come into play here such as who is responsible to enforce this and how.. there is also an issue of per channel handler custom threading execution model which is user configured… think about a pipeline that’s built from channel handlers from different authors, how would you establish a robust and optimized contract?

In any case this is a separate and complex issue. Currently I don’t see how you can simply drop in a channel handler into the pipeline without understanding what you get from a previous channel handler and what output you pass on. 

>All handlers are associated with an executor and are always invoked by that executor. If the handler is not supposed to be executed in a different executor, then one should not specify any executor while adding that handler to the pipeline.

The issue is that my channel handler response will be executed by an executer that I didn’t configure… when calling ‘write’ it is invoked by *some other* implementation regardless of what I configured for *my implementation*. That *some other implementation* can be perfectly valid for certain messages but invalid for other messages.

>I think the meta point here is that you are trying to have a handler decide how & when to execute other handlers in the pipeline, which I don't think is a good idea as those handlers then are tied to a particular pipeline configuration and not generically applicable.

This is not what I’m trying to do. If there is any meta point here it’s about loose coupling and a  specification that is symmetric for both inbound and outbound processing path, I think the bigger issue here is whether a channel handler should include an additional property of being Consuming/Terminating without inquiring side-effects by successive handlers.

**Comment by gitai** [comment]
BTW. My understanding of the behavior where a call to write() is invoked on the “next” ChannelHandlerContext is based on the explanation in “Netty In Action” book (Page. 91) which does not make a distinction between Inbound or Outbound ChannelHandler. If by “next” means next Outbound Handler “backwards” (effectively skipping all successor configured handlers) than there is no issue. I'll start looking into the implementation.

**Comment by gitai** [comment]
Ahh.. I should have looked into what findContextOutbound does in AbstractChannelHandlerContext

So calling 'write' on a channel handler context would traverse the context chain looking for the first channel handler context that *precedes* it and can also handle outbound events.

Here is sample console application which shows this logic, it may be useful when explaining this to others.

Output:

In SimpleChannelHandler1::channelActive
In SimpleChannelHandler2::channelActive
In SimpleChannelHandler3::channelActive
4551 [nioEventLoopGroup-4-1] DEBUG io.netty.util.ResourceLeakDetector  - -Dio.netty.leakDetectionLevel: simple
In SimpleChannelHandler1::channelRead
**In SimpleChannelHandler2::channelRead (CONSUMING)**
**In SimpleChannelHandler1::write**
4557 [nioEventLoopGroup-4-1] DEBUG io.netty.util.Recycler  - -Dio.netty.recycler.maxCapacity.default: 262144
**In SimpleChannelHandler1::flush**

public class Server {

    private static final EventExecutorGroup eeg = new DefaultEventExecutorGroup(5);

    public static void main(String[] args) {

        System.out.println("Hello Netty");

        EventLoopGroup parent = new NioEventLoopGroup(1);
        EventLoopGroup child = new NioEventLoopGroup();

        try {
            ServerBootstrap b = new ServerBootstrap();
            b.group(parent, child)
                    .channel(NioServerSocketChannel.class)
                    .childHandler(new SimpleChannelInitializer());

            Channel ch = b.bind(InetAddress.getLoopbackAddress(), 8020).sync().channel();
            ch.closeFuture().sync();

            System.out.println("Server Shutdown");

        } catch (InterruptedException e) {
            e.printStackTrace();
        } finally {
            parent.shutdownGracefully();
            child.shutdownGracefully();
        }
    }

    public static class SimpleChannelInitializer extends ChannelInitializer<SocketChannel> {

        @Override
        protected void initChannel(SocketChannel ch) throws Exception {
            ChannelPipeline pipeline = ch.pipeline();
            pipeline.addLast(new SimpleChannelHandler1());
            pipeline.addLast(new SimpleChannelHandler2());
            pipeline.addLast(eeg, new SimpleChannelHandler3());
        }
    }

    public static class SimpleChannelHandler1 extends ChannelInboundHandlerAdapter implements ChannelOutboundHandler {

        @Override
        public void channelActive(ChannelHandlerContext ctx) throws Exception {
            System.out.println("In SimpleChannelHandler1::channelActive");
            ctx.fireChannelActive();
        }

        @Override
        public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
            System.out.println("In SimpleChannelHandler1::channelRead");
            ctx.fireChannelRead(msg);
        }

        @Override
        public void bind(ChannelHandlerContext ctx, SocketAddress localAddress, ChannelPromise promise) throws Exception {
            ctx.bind(localAddress, promise);
        }

        @Override
        public void connect(ChannelHandlerContext ctx, SocketAddress remoteAddress, SocketAddress localAddress, ChannelPromise promise) throws Exception {
            ctx.connect(remoteAddress, localAddress, promise);
        }

        @Override
        public void disconnect(ChannelHandlerContext ctx, ChannelPromise promise) throws Exception {
            ctx.disconnect(promise);
        }

        @Override
        public void close(ChannelHandlerContext ctx, ChannelPromise promise) throws Exception {
            ctx.close(promise);
        }

        @Override
        public void deregister(ChannelHandlerContext ctx, ChannelPromise promise) throws Exception {
            ctx.deregister(promise);
        }

        @Override
        public void read(ChannelHandlerContext ctx) throws Exception {
            ctx.read();
        }

        @Override
        public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) throws Exception {
            System.out.println("In SimpleChannelHandler1::write");
            ctx.write(msg, promise);
        }

        @Override
        public void flush(ChannelHandlerContext ctx) throws Exception {
            System.out.println("In SimpleChannelHandler1::flush");
            ctx.flush();
        }
    }

    public static class SimpleChannelHandler2 extends ChannelInboundHandlerAdapter implements ChannelOutboundHandler {

        @Override
        public void channelActive(ChannelHandlerContext ctx) throws Exception {
            System.out.println("In SimpleChannelHandler2::channelActive");
            ctx.fireChannelActive();
        }

        @Override
        public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
            System.out.println("In SimpleChannelHandler2::channelRead (CONSUMING)");
            ctx.writeAndFlush(msg); 
        }

        @Override
        public void bind(ChannelHandlerContext ctx, SocketAddress localAddress, ChannelPromise promise) throws Exception {
            ctx.bind(localAddress, promise);
        }

        @Override
        public void connect(ChannelHandlerContext ctx, SocketAddress remoteAddress, SocketAddress localAddress, ChannelPromise promise) throws Exception {
            ctx.connect(remoteAddress, localAddress, promise);
        }

        @Override
        public void disconnect(ChannelHandlerContext ctx, ChannelPromise promise) throws Exception {
            ctx.disconnect(promise);
        }

        @Override
        public void close(ChannelHandlerContext ctx, ChannelPromise promise) throws Exception {
            ctx.close(promise);
        }

        @Override
        public void deregister(ChannelHandlerContext ctx, ChannelPromise promise) throws Exception {
            ctx.deregister(promise);
        }

        @Override
        public void read(ChannelHandlerContext ctx) throws Exception {
            ctx.read();
        }

        @Override
        public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) throws Exception {
            System.out.println("In SimpleChannelHandler2::write");
            ctx.write(msg, promise);
        }

        @Override
        public void flush(ChannelHandlerContext ctx) throws Exception {
            System.out.println("In SimpleChannelHandler2::flush");
            ctx.flush();
        }
    }

    public static class SimpleChannelHandler3 extends ChannelInboundHandlerAdapter implements ChannelOutboundHandler {

        @Override
        public void channelActive(ChannelHandlerContext ctx) throws Exception {
            System.out.println("In SimpleChannelHandler3::channelActive");
            ctx.fireChannelActive();
        }

        @Override
        public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
            System.out.println("In SimpleChannelHandler3::channelRead");
            ctx.fireChannelRead(msg);
        }

        @Override
        public void bind(ChannelHandlerContext ctx, SocketAddress localAddress, ChannelPromise promise) throws Exception {
            ctx.bind(localAddress, promise);
        }

        @Override
        public void connect(ChannelHandlerContext ctx, SocketAddress remoteAddress, SocketAddress localAddress, ChannelPromise promise) throws Exception {
            ctx.connect(remoteAddress, localAddress, promise);
        }

        @Override
        public void disconnect(ChannelHandlerContext ctx, ChannelPromise promise) throws Exception {
            ctx.disconnect(promise);
        }

        @Override
        public void close(ChannelHandlerContext ctx, ChannelPromise promise) throws Exception {
            ctx.close(promise);
        }

        @Override
        public void deregister(ChannelHandlerContext ctx, ChannelPromise promise) throws Exception {
            ctx.deregister(promise);
        }

        @Override
        public void read(ChannelHandlerContext ctx) throws Exception {
            ctx.read();
        }

        @Override
        public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) throws Exception {
            System.out.println("In SimpleChannelHandler3::write");
            ctx.write(msg, promise);
        }

        @Override
        public void flush(ChannelHandlerContext ctx) throws Exception {
            System.out.println("In SimpleChannelHandler3::flush");
            ctx.flush();
        }
    }

**Comment by gitai** [comment]
Having said that I’m still concerned about possible handler execution model dependency regardless if it’s “previous” or “next” because what it means that in order to skip processing messages in channel handlers configured with an event executer group the skip logic would need to be performed outside the eventloop... might be better to let channel handler implementers determine when to go off the event loop and explicitly signal when finished in order to return to the event loop

**Comment by gitai** [comment]
I'm closing this issue since it's ultimately a matter of usage (Thanks @NiteshKant  for the feedback)

**Comment by trustin** [comment]
Thank you very much for the discussion, @NiteshKant. Obviously I am too busy these days.
