### ISSUE TITLE
Headers, AsciiString, ByteString discussion

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4037]
A few items I would like to open up for discussion / investigation:

1. Does it make sense to use `String` instead of `ByteString` for HTTP/2 header names? The perception that the.  HTTP/2 headers don't need case insensitive comparisons and thus can use regular equals/hashCode, and these methods are intrinsic for `String`.
2. Can we remove the requirement that `ByteString` be able to track offset/length? This adds a great deal of complexity to the implementation, and potentially users of the interface.  The object footprint is also increased because of the extra memory required to track offset/length. Is this overhead justified?
3. Can we or decouple (or remove?) `AsciiString` and `ByteString` to reduce object footprint and simplify interfaces.  This may require that we duplicate the HTTP/1.x headers in HTTP/2 and have some sort of mapping to/from the different types.  We could also then move more toward a `HeaderEntity` approach (removed in de2872f7f7833356b97aefb0a341811fea5f1c25) which caches the hash code in accordance with the `HashingStrategy`.

**Comment by Scottmitch** [comment]
@trustin @normanmaurer  - @buchgr and I were discussing the above topics today.  Can you please comment on the above or list any other thoughts you may have on this topic?

**Comment by buchgr** [comment]
Thanks for writing this up Scott.

One thing I would like to add is that an empty AsciiString object uses up `40 bytes`, while an empty String object uses `24 bytes`. So at least for headers, there won't be memory savings. More likely `AsciiString` will use up more memory.

**Comment by Scottmitch** [comment]
One of the "extra" fields in `AsciiString` is caching the `toString()` result.  However if we remove this we could experience pain in 4.1 due to how the `HttpHeaders` interface is based on `String` instead of `CharSequence`.  Because the `HttpHeaders` interface is based on `String` most of the operations are still exposed in terms of `String`, and this means now that `AsciiString` exists we can expect `AsciiString.toString()` to be called a good deal in 4.1.

**Comment by Scottmitch** [comment]
ByteString is now dead in favor of AsciiString. We have not moved to String, and I don't think this is planned for 4.1.

@buchgr - Are you still interested in this, or should we close?

**Comment by buchgr** [comment]
@Scottmitch you can close :).
