### ISSUE TITLE
VoidPromise and others leak in 4.0.30.Final in my push server

### ISSUE THREAD

**Issue by taojiaenx** [netty/netty#4040]
Netty version: 4.0.30Final
Context:
I have been working on a push Server and I am testing the memory leak.
I use Netty to receive user request and send a result to user.

$ java -version
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)

 jvm argument:

-Xmx128M

Operating system:
win7 64bit
the client and the server are both my PC,the buffer is used up many times by the client.

reproduce:

![image001](https://cloud.githubusercontent.com/assets/7163099/8948164/8d8e0b7c-35d6-11e5-9276-b75965edc5ec.png)

I can provide all my code and the code is so sample I believe that the problem will be solved soon
https://github.com/taojiaenx/taojiane_push.git

When the client send a message, the client will close the connetion

org.ddpush.v1.node.PushListener  include all the work that netty do and I think  PushTask or TimerSolver(a class In pushListener.java) may cause the meomroy leak

the channelContext is referenced by PushTask and the PushTask is a "FutureTask" which work in threadPool, I have establish a timeout solver the reference of channelContext will be dereferenced at most 45 seconds later
 

 

I use this way to send a push messages.

code is in org.ddpush.v1.node.client.appuser.example

for(int j = 0; j < 30; ++j) {

             for(int i = 0; i < 5000; ++i) {

                new Thread(new send0x20Task(ip,pushPort,clientUUID, ("testfewfwefewfewfewfewfewfewfwefwe " + 1).getBytes("utf-8"))).start();

                  // when a push is finished, the connetion will be closed right now

             }

             TimeUnit.SECONDS.sleep(10);

            }

**Comment by Scottmitch** [comment]
@taojiaenx - Can you provide a bit more detail as to why you think there is a leak, and why you feel this leak is in Netty?  For example have you forced a GC and traced GC roots?

**Comment by taojiaenx** [comment]
I think may be this is the problem of my code and I just want to know how this happen, I will provider with the graph of class latter.

**Comment by taojiaenx** [comment]
this is the heap
![image](https://cloud.githubusercontent.com/assets/7163099/9114759/14c7f040-3c8e-11e5-87cc-6edc8442cc19.png)
there is no out going reference.
when I test the client will send a message to the server then close the connection immdiatly, and there are a lot of clients do this operation at the same time.
I thick those code may cause the leak
this code is in a class which is the son class of SimpleChannelInboundHandler<ByteBuf>
@Override
	public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause)
			throws Exception {
		if (ctx.channel().isActive()) {
			ctx.disconnect();
			ctx.close();
		}
		// cause.printStackTrace();
	}
Maybe  the leak is beacause of I use the ByteBuf in seperate thead, however there is no leak of ByteBuf.

**Comment by taojiaenx** [comment]
sorry ignore this, found the bug, sorry

**Comment by Scottmitch** [comment]
@taojiaenx - Glad you found it. Care to share what the root cause was?

**Comment by trustin** [comment]
Gentle ping to @taojiaenx. We are curious to know what the root cause was.

**Comment by taojiaenx** [comment]
sorry I have not see this. I cause leak beacuse I set a to big timeoutValue, sorry
