### ISSUE TITLE
Add support for "session present" flag in io.netty.handler.codec.mqtt.MqttConnAckVariableHeader

### ISSUE THREAD

**Issue by jorcasso** [netty/netty#4041]
Netty version: 4.1.0.Beta5

Context:
I'm implementing an MQTT broker based on netty using the classes from the package io.netty.handler.codec.mqtt, in the version 3.1.1 of the MQTT protocol it has been added a new flag in the variable header of the CONNACK message called "session present": http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718035, it would be great if that flag was supported in io.netty.handler.codec.mqtt.MqttConnAckVariableHeader.

**Comment by normanmaurer** [comment]
We love contributions. Maybe care to submit a PR?

**Comment by flozano** [comment]
@normanmaurer I tried to do it in PR. https://github.com/netty/netty/pull/4042

but I am not sure if it's OK to do it against 4.1 (the branch we're using) or if I should do it against master and you guys (or me?) take care of the cherry-pick

Also I just noticed now that I didn't format the commit properly, but it's so trivial I'm not sure it's worth it...

**Comment by Scottmitch** [comment]
@flozano - Thanks for the PR! Doing against 4.1 should be fine. We will take care of cherry-picking into other branches.

**Comment by normanmaurer** [comment]
@flozano thanks.. Adjusted commit message and cherry-picked into 4.1(a91e64850505938cfe3a2079e1ac2c247df6532b)  and master (6ff66fe967ed1aa45f2e87d263463f35c959b5cf).
