### ISSUE TITLE
Reduce hash collisions in protocol headers.

### ISSUE THREAD

**Issue by buchgr** [netty/netty#4048]
After re-introducing the 4.0 protocol headers in #4038, we see a lot of hash collisions [1]. There is room for improvement. We should look into it :-).

[1] https://drive.google.com/folderview?id=0B9onSiVGZDlVfjlDZTNEVEhoSjNDQk50WjVpanR2SFdZY1pHYy16OHM2dmM5T2NaOWl1RWs&usp=drive_web

**Comment by Scottmitch** [comment]
Thanks for reporting this @buchgr.

The actual hash algorithms may not be the problem, but instead the mapping of hash code to array index.

The word document structures are as follows:
`<array index> = <number of collisions> [<hash code>=<header name>, ...]`

**Comment by Scottmitch** [comment]
Also looking at the header names...`cookie:` header name has a `:` at the end. This should be removed in future tests.  I removed it in the benchmark.

**Comment by buchgr** [comment]
> The actual hash algorithms may not be the problem, but instead the mapping of hash code to array index.

aka the hash function ;-)

**Comment by Scottmitch** [comment]
Poor choice of words considering I was attempting to clarify terminology.  My intention was that the `hashCode()` methods (corrected in original comments) are likely not be the problem because there were 0 observed collisions in the tests so far (unless they are supposed to be equivalent because case insensitive hash code is used).  However the `index` function (i.e. ``entries[index(hashCode(object))]`) which maps from integer domain to array index function may be a better place to start.

**Comment by buchgr** [comment]
`hashfn := index(hashCode(object))`.

Anyways, the JDK's HashMap uses `sun.misc.Hashing.stringHash32(String)` for Strings. It's also available for `byte[]`, so we can do that for AsciiString and ByteString. It's worth a try I think. If it helps we can hide it in `PlatformDependent`. //cc @trustin @normanmaurer

**Comment by normanmaurer** [comment]
Sounds good!

**Comment by Scottmitch** [comment]
@buchgr - With the current class hierarchy and usage pattern we have to have an algorithm that is compatible between ByteString and AsciiString considering case insensitive values.  Is there a way to accomplish this using `sun.misc.Hashing.stringHash32(String)`?

Even if we could decouple ByteString and AsciiString the same would still be true for AsciiString (or at least what ever hash algorithm we use for HTTP header names).

**Comment by buchgr** [comment]
@Scottmitch Let me do some tests to see if it is any better first. If it is, I ll come up with a proposal of how to integrate it. Will require some work, but nothing super hard I think.

**Comment by Scottmitch** [comment]
@buchgr - SGTM! Thanks!

**Comment by Scottmitch** [comment]
@buchgr - Ping. It may be work re-visiting this as the hash algorithm has changed since this issue was reported.

**Comment by buchgr** [comment]
@Scottmitch Hey! I don't have cycles at the moment, and likely neither in the next few months. I think we can close this.

**Comment by Scottmitch** [comment]
@buchgr - sgtm! Also hope all is well! I see you have been looking into jemalloc recently ... any of that knowledge going to make its way into Netty :wink:?

**Comment by buchgr** [comment]
@Scottmitch all good. bed bugs are dead :smile: . yep I ll definitely want to look into netty's allocator :) interesting stuff!

**Comment by normanmaurer** [comment]
@buchgr lol :)
