### ISSUE TITLE
SpdyHttpDecoder fails to decode SpdyFrame to HttpRequest

### ISSUE THREAD

**Issue by blucas** [netty/netty#4053]
Netty Version: 5.0.0.Alpha3-SNAPSHOT (latest master)

Issue:
When the ```SpdyHttpDecoder``` attempts to decode a SPDY Frame into a ```FullHttpRequest``` a ```NullPointerException``` is thrown on [this line](https://github.com/netty/netty/blob/master/codec-http/src/main/java/io/netty/handler/codec/spdy/SpdyHttpDecoder.java#L353).  

The reason is that the call to ```headers.getAndConvert(METHOD)``` returns ```null```. ```headers``` *does* contain the ```:method``` pseudo-header, the problem is that ```METHOD``` is ```AsciiString```, but ```headers``` is looking for a key of type ```String```.  If you call ```headers.getAndConvert(METHOD.toString())``` the lookup succeeds.

I think this issue has been introduced because of: d31fa31cdcc5ea2fa96116e3b1265baa180df58a
This issue may also be present in other codecs/handlers that try to lookup headers.  This is the first place I spotted it.

/cc @buchgr @Scottmitch - You two seem to be the best placed to solve this one :smile:

**Comment by blucas** [comment]
I've just finished writing a unit test to better explain the issue.  Maybe this has something to do with the fact that ```DefaultSpdyHeaders``` uses a ```LinkedHashMap``` implementation while ```DefaultHttpHeaders``` uses a ```TreeMap```?

```java
import io.netty.handler.codec.http.DefaultHttpHeaders;
import io.netty.handler.codec.http.HttpHeaderNames;
import io.netty.handler.codec.http.HttpHeaders;
import io.netty.handler.codec.spdy.DefaultSpdyHeaders;
import io.netty.handler.codec.spdy.SpdyHeaders;
import junit.framework.Assert;
import org.junit.Test;

public class HeadersTest
{
   @Test
   public void testHttpHeaders() throws Exception
   {
      final HttpHeaders headers = new DefaultHttpHeaders(false);

      // Test adding String key
      final String connection = "keep-alive";
      headers.add("Connection", connection);

      // Passes
      final String value = headers.getAndConvert(HttpHeaderNames.CONNECTION.toString());
      Assert.assertNotNull(value);
      Assert.assertEquals(connection, value);

      // Passes
      final String value2 = headers.getAndConvert(HttpHeaderNames.CONNECTION);
      Assert.assertNotNull(value2);
      Assert.assertEquals(connection, value2);

      // Test adding AsciiString key
      final String cacheControl = "no-cache";
      headers.add(HttpHeaderNames.CACHE_CONTROL, cacheControl);

      // Passes
      final String value3 = headers.getAndConvert(HttpHeaderNames.CACHE_CONTROL);
      Assert.assertNotNull(value3);
      Assert.assertEquals(cacheControl, value3);

      // Passes
      final String value4 = headers.getAndConvert(HttpHeaderNames.CACHE_CONTROL.toString());
      Assert.assertNotNull(value4);
      Assert.assertEquals(cacheControl, value4);
   }

   @Test
   public void testSpdyHeaders() throws Exception
   {
      final SpdyHeaders headers = new DefaultSpdyHeaders();

      // Test adding String key
      final String method = "GET";
      headers.add(":method", method);

      // Passes
      final String value = headers.getAndConvert(SpdyHeaders.HttpNames.METHOD.toString());
      Assert.assertNotNull(value);
      Assert.assertEquals(method, value);

      // Should also pass, but doesn't!
      final String value2 = headers.getAndConvert(SpdyHeaders.HttpNames.METHOD);
      Assert.assertNotNull(value2);
      Assert.assertEquals(method, value2);

      // Test adding AsciiString key
      final String path = "/";
      headers.add(SpdyHeaders.HttpNames.PATH, path);

      // Passes
      final String value3 = headers.getAndConvert(SpdyHeaders.HttpNames.PATH);
      Assert.assertNotNull(value3);
      Assert.assertEquals(path, value3);

      // Should also pass, but doesn't!
      final String value4 = headers.getAndConvert(SpdyHeaders.HttpNames.PATH.toString());
      Assert.assertNotNull(value4);
      Assert.assertEquals(path, value4);
   }
}
```

**Comment by Scottmitch** [comment]
Thanks for reporting this issue and the unit test @blucas!  It is indeed because of the different map implementation. The `String` and `AsciiString` keys have different hash algorithms and thus the lookup in the LinkedHashMap fails (the equals are likely different too).  I believe this issue will disappear after PR https://github.com/netty/netty/pull/4038 is pulled in.

It would be appreciated if you could submit your test case as PR. Maybe put the `DefaultHttpHeaders` portion in `io.netty.handler.codec.http.DefaultHttpHeadersTest` and the `DefaultSpdyHeaders` part in a new file `io.netty.handler.codec.spdy.SpdyHeadersTest`.

**Comment by blucas** [comment]
@Scottmitch - I'll create a pull request for these later this week.  I'm glad to hear this is already fixed in an existing PR :+1:

**Comment by blucas** [comment]
Hey scott, I was going to create a PR for this today, but could not find a ```io.netty.handler.codec.http.DefaultHttpHeadersTest``` in master.  Should I just create one?

**Comment by Scottmitch** [comment]
@blucas https://github.com/netty/netty/blob/master/codec-http/src/test/java/io/netty/handler/codec/http/DefaultHttpHeadersTest.java exists in master so just use this. The SPDY test may not exist and you can just create a file for that.

**Comment by blucas** [comment]
Closing this as the issue is now fixed and the unit tests have been merged.

**Comment by Scottmitch** [comment]
@blucas - Thanks for reporting, verifying the a fix, and providing the unit tests!
