### ISSUE TITLE
using HttpProxyHandler netty open connection on proxied host

### ISSUE THREAD

**Issue by gfrison** [netty/netty#4055]
```java
Bootstrap.handler(new ChannelInitializer<SocketChannel>()
			{

				protected void initChannel(final SocketChannel ch) throws Exception
				{
					ChannelPipeline p = ch.pipeline();
					p.addFirst(new HttpProxyHandler(new InetSocketAddress("proxy", 8080)));
					p.addLast(sslCtx.newHandler(ch.alloc()));
					p.addLast(new LoggingHandler(LogLevel.DEBUG));
					p.addLast(new HttpClientCodec());
					p.addLast(new Handler());
				}
}).connect(InetSocketAddress.createUnresolved("proxyed", 443)).sync().channel();
```

I would expect that at 'connect' no connection is opened at 'proxied' (and no proxyed host name is resolved) because everything should pass through the proxy.

How can I avoid it?

Thank you,

**Comment by trustin** [comment]
It should connect to `proxy:8080` rather than `proxied:443` as you said. Do you observe a different behavior?

**Comment by gfrison** [comment]
Hello,

I see that it connects correctly to the proxy but at the end it open a direct connection to the proxied, without sending anything, but since the proxied is not mapped I got a DNS error (UnresolvedAddressException), this is why I noticed this behaviour.
Is there something I could do for avoiding this problem?

Thank you,

**Comment by normanmaurer** [comment]
@gfrison I still not understand what the problem is... @trustin you ?

**Comment by gfrison** [comment]
using the NoopNameResolver the problem is over.
Closing issue.

**Comment by jsachania** [comment]
Is there a way to exclude URLs from going through proxy? I have HttpProxyHandler and NoopNameResolver for all URLs. Typically we set $no_proxy to exclude URLs.
