### ISSUE TITLE
reuse for nioEventLoopGroup Thread

### ISSUE THREAD

**Issue by romanman** [netty/netty#4056]
Guys would you consider it as a good strategy 
to try and reuse threads behind `nioEventLoopGroup`
for server with a lot of connect/disconnect scenarios ?

Thanks in advance.

**Comment by Scottmitch** [comment]
@romanman - Thanks for reaching out. Please post questions on stackoverflow (more likely others will see and benefit from the answer). Github is for reporting issues/bugs and feature requests. Feel free to post a link to the stackoverflow question in this case, but in the future stick to stackoverflow for questions.

**Comment by romanman** [comment]
@Scottmitch : sorry for the mess, here it is: 
http://stackoverflow.com/questions/31795715/reuse-for-eventloopgroup
