### ISSUE TITLE
HttpObjectAggregator 100-continue behavior

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4057]
[HttpObjectAggregator](https://github.com/netty/netty/blob/4.0/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectAggregator.java#L131) automatically responds with a `100-continue`.  The sending of the `100-continue` should be sensitive to the `Content-Length` header and respond with a `417` as defined in [RFC 7231, 5.1.1](https://tools.ietf.org/html/rfc7231#section-5.1.1) if the `maxContentLength` is exceeded.

**Comment by Scottmitch** [comment]
@trustin - Commit 57dc0b3b added a `TODO` statement which relates to this issue. Any thoughts?

**Comment by Scottmitch** [comment]
I have a PR pending for this.

**Comment by trustin** [comment]
IIRC this has been resolved in 4.1 via the introduction of `MessageAggregator`.

**Comment by Scottmitch** [comment]
@trustin - Oops forgot to close this. This was fixed by https://github.com/netty/netty/pull/4083 for 4.0 and https://github.com/netty/netty/pull/4089 for 4.1 / master.  The `MessageAggregator` still did not handle this condition prior to #4089.
