### ISSUE TITLE
Unable to decode response from buggy web server implementation

### ISSUE THREAD

**Issue by rkosegi** [netty/netty#4063]
I'm using HttpClientCodec to get screen from IP camera.
It seems that camera has buggy web server as Netty fail to decode response. 

```
DefaultHttpResponse(decodeResult: failure(java.lang.IllegalArgumentException: Header name cannot contain the following prohibited characters: =,;: \t\r\n\v\f: Tue,))
```

Here are response headers from same camera using "curl -v"
```
< HTTP/1.1 200 OK
< Server: GoaHead
< Tue, 12 Jun 2012 01:56:34 GMT
< Content-Type:image/jpeg
< Content-Length:36212
< Connection: close
```

Obviously there is missing "Date:" prefix in header on 3rd line.
Question here is, if it is possible to use lax parsing of response or ignore parsing errors at all.
I recognize this as problem of buggy web server, not Netty's HTTP implementation.

**Comment by Scottmitch** [comment]
@rkosegi - Thanks for reaching out! Please use stackoverflow for questions about Netty as users are more likely to see the questions / responses there. Github is for reporting Netty errors / feature requests. In this case feel free to reply with the link to the stackoverflow question here (I will answer), but in the future please start with stackoverflow for questions.
