### ISSUE TITLE
Dependency on sun packages should be removed sooner rather than later.

### ISSUE THREAD

**Issue by nathantippy** [netty/netty#4068]
This is a key issue for compact profiles and may be a significant issue in Java 9.  By eliminating this dependency now (early) netty will be in a great position to grow its community when Java 9 is released.  This dependency also limits the number embedded deployments where netty could be used.

The goal should be to get netty to run out of the box under either compact2 or compact1 profile.

**Comment by Scottmitch** [comment]
This seems related to https://github.com/netty/netty/issues/4044.  Should we continue discussion there or do you have specific dependencies you are concerned about?

**Comment by Scottmitch** [comment]
Here are some modules that appear to use sun imports (other than `Unsafe` and `Cleaner`):
- transport-sctp
- resolver-dns
- common - PlatformDependent.java and PlatformDependent0.java need more investigation
- handler - OpenJdkSelfSignedCertGenerator.java
- transport - NioEventLoop.java

**Comment by normanmaurer** [comment]
@nathantippy I think these are "optional"... I'm missing something ?

**Comment by mxmind** [comment]
Do you have some progress on this issue?

**Comment by normanmaurer** [comment]
@mxmind nope... that said we should have fallbacks if these are not accessible.

**Comment by normanmaurer** [comment]
I think we can close this now as netty works on java9 as it falls-back to non sun classes.
