### ISSUE TITLE
Netty Truck Factor

### ISSUE THREAD

**Issue by gavelino** [netty/netty#4069]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Netty** and obtained a value of **2**.

The developers responsible for this TF are:

Trustin Lee - author of 71% of the files
Norman Maurer - author of 16% of the files

To validate our results, we would like to ask **Netty** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Netty**?

(b) Do you agree that **Netty** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Netty** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by Scottmitch** [comment]
(a) Yes. Lets just say we all hope here that neither of them get hit by a truck.

(b) Netty would suffer.

(c) Netty does have docs. The project is used by other projects and organizations who presumably have have a vested interest in Netty being maintained.

Are your calculations sensitive to time? For example can you derive TF for the last `n` months?

**Comment by gavelino** [comment]
Hi @Scottmitch ,

thanks for the answer. Currently, our approach is not sensitive to time. It calculates the TF for the entire repository history. But, we intend to implement this functionality.

**Comment by normanmaurer** [comment]
@Scottmitch thanks for taking care of this while I was on vacation :)
