### ISSUE TITLE
Merging a pull request instead of cherry-picking

### ISSUE THREAD

**Issue by trustin** [netty/netty#4070]
I see no problem merging a pull request as long as the pull request is properly rebased and squashed. It also means we can use the 'Merge pull request' button and 'Delete the merged branch' button in the Github pull request page, which is super convenient. What do you think?

**Comment by Scottmitch** [comment]
@trustin - I prefer to cherry picking for the following reasons:

1. We often have to put PR changes into multiple branches, and I think this means you will have to use command line most of the time anyways.
2. Keeps log cleaner, doesn't get cluttered up with merge branches.

I'm not against merging, but are there other positives besides convenience?

**Comment by trustin** [comment]
I think you are right. We use command line to work on more than one
branch almost always, there is not much merit of using web UI and
introducing merge commits.

**Comment by normanmaurer** [comment]
+1 to use cherry-pick

**Comment by md-5** [comment]
cherry pick gets my vote.
