### ISSUE TITLE
DNS: DnsNameResolver doesn't read /etc/hosts

### ISSUE THREAD

**Issue by erimatnor** [netty/netty#4074]
Being able to resolve hosts from /etc/hosts would be useful and probably the expected behavior for many. Preferably, it would monitor the file for changes too.

**Comment by trustin** [comment]
Perhaps we could write new `NameResolver` implementations:

- `HostsFileNameResolver` that resolves host names from /etc/hosts and monitors its changes.
- `CombinedNameResolver` that tries one or more resolvers - `new CombinedNameResolver(new HostsFileNameResolver(), new DnsNameResolver())`
- ... and preferably a utility class that simplifies construction and composition of the resolvers, like:
   - `NameResolvers.defaultNameResolver(...)`
   - `NameResolvers.of(NameResolver...)`

**Comment by trustin** [comment]
Please refer to this page for the location of the host file for different OSes: https://en.wikipedia.org/wiki/Hosts_(file) (whoa!)

**Comment by slandelle** [comment]
FYI, we've implemented hosts file resolution in Gatling (in a private branch atm).
We'll contribute at some point when we'll switch to 4.1 (using 4.0 + dnsjava for now).

**Comment by normanmaurer** [comment]
Thanks!

**Comment by slandelle** [comment]
@trustin @normanmaurer Where do you want the hosts file parser? Which module? Static methods in NetUtil or own class?

**Comment by normanmaurer** [comment]
hmm... just put it where you think makes most sense.

**Comment by normanmaurer** [comment]
closed by https://github.com/netty/netty/pull/4567
