### ISSUE TITLE
SimpleChannelPool/FixedChannelPool: Don't put unhealthy channel back to the pool on release

### ISSUE THREAD

**Issue by ioanbsu** [netty/netty#4077]
Currently it is *required* to release channel to the channel pool for ```FixedChannelPool```. 
Failure to release a channel may cause that ```FixedChannelPool.acquiredChannelCount``` becomes equal or bigger then ```FixedChannelPool.maxConnections```. So basically it means that we have to release back all the channels even those ones that are not *healthy*, and when channel is released it simply put back into a ```CimpleChannelPool.deque``` regardless if it's healthy or not.
Now, on acquire SimpelChannelPool will check if channel is healthy before returning it. If it turns out to be unhealthy then it will discard it and poll the next one from the pool(if there any left in pool) and will continue doing so until it gets healthy channel or until the ```deque``` is empty(in which case it will just create a new channel). Though this sort of lazy-discard approach works, I think there is a room for improvement, such as we can filter out unhealthy channels at the time when we release them. 

Here is example where such improvement may help:
1) Client application requested bunch of channels
2) Before releasing them back to pool all channels become closed cause remote tier closed them
3) We end up having channelPool full of unhealthy channels.
4) Next time we will try to acquire new channel we will have to cleanup/discard all unhealthy channels first which may take some time depending on number of unhealthy channels.

It also make sense to filter our unhealthy channels on release because in most cases when someone releases a channel he normally doesn't care about release performance. The more critical in my opinion is acquire performance.

**Comment by Scottmitch** [comment]
@normanmaurer - I recall discussing this when we originally reviewed the pool.  I think your rational was since we have to check the health anyways when we pull out of the pool, and the health check may be expensive (may include RTT), we wanted to minimize the number of health checks done. WDYT?

**Comment by normanmaurer** [comment]
@Scottmitch yep that was my argument, I may been wrong here and we should kind of make this configurable. WDYT ?

**Comment by Scottmitch** [comment]
@normanmaurer yes. As this issue describes I think there is value in having the option to check up front too.

**Comment by Scottmitch** [comment]
Fixed by https://github.com/netty/netty/pull/4078

**Comment by trustin** [comment]
@Scottmitch Please make sure not to introduce a build breakage when you cherry-pick into 4.0 and 4.1

**Comment by Scottmitch** [comment]
@trustin - I'm sorry. Will be more careful in the future. Thanks for cleaning up after my mess.

**Comment by trustin** [comment]
@Scottmitch No worries. I make the same mistake over and over. :-)
