### ISSUE TITLE
IllegalStateException seen when "Expect: 100-continue" header used

### ISSUE THREAD

**Issue by gjesse** [netty/netty#4079]
Netty version: 4.0.29.Final,  4.0.30.Final 

I am using netty to power an http server along with the rxNetty library. 

I am seeing this issue after upgrading from 4.0.28 to 4.0.30.Final  - When I submit a request that includes an "Expect: 100-continue header", I end up getting 2 response attempts for a single request, and an IllegalStateException on the second response from this line:

https://github.com/netty/netty/blob/netty-4.0.30.Final/codec-http/src/main/java/io/netty/handler/codec/http/HttpContentEncoder.java#L105

the response is being written here: 

https://github.com/netty/netty/blob/netty-4.0.30.Final/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectAggregator.java#L132

I verified the same issue occurs in 4.0.29.

**Comment by normanmaurer** [comment]
Let me check

**Comment by Scottmitch** [comment]
@gjesse - I haven't looked at this issue in detail but PR https://github.com/netty/netty/pull/4083 seems to address similar concerns. Would you mind trying this PR?

**Comment by gjesse** [comment]
@Scottmitch, It's certainly in the same area - not sure if it addresses my concerns but I will try it out and see what happens

**Comment by normanmaurer** [comment]
@Scottmitch @gjesse its not related... Working on a fix as we speak

**Comment by d-t-w** [comment]
Thanks @normanmaurer I just came across this issue while using 4.0.29. Updated to 4.0.31 and can confirm 100-continue behaves correctly again.
