### ISSUE TITLE
Out of memory: Resource leak detector is going recursive

### ISSUE THREAD

**Issue by mubarak** [netty/netty#4093]
Netty version: 4.1.0-Beta5

Context:
I encountered OOM and heap dump shows `ResourceLeakDetector` is going recursive and retains 99% of heap. We use 8 GB as max heap size with PooledByteBuf. Please find the screenshots. I can share the heap dump (if needed)

$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

Operating system: Linux

$ uname -a
Linux f376de121d98 3.18.6 #2 SMP Sat Feb 28 02:23:04 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

<img width="1648" alt="screen shot 2015-08-15 at 8 50 47 pm" src="https://cloud.githubusercontent.com/assets/668134/9291920/ab6098d2-4390-11e5-953c-a67053d6b06b.png">

<img width="1642" alt="screen shot 2015-08-15 at 8 56 14 pm" src="https://cloud.githubusercontent.com/assets/668134/9291921/b04ac49e-4390-11e5-8d71-9d2189d201ce.png">

<img width="1640" alt="screen shot 2015-08-15 at 8 56 45 pm" src="https://cloud.githubusercontent.com/assets/668134/9291922/b4e57300-4390-11e5-8c84-42ef9bbf8d76.png">

**Comment by normanmaurer** [comment]
@mubarak could you share the heap dump ?

**Comment by mubarak** [comment]
@normanmaurer You can download the heap dump from https://drive.google.com/file/d/0BwPlSk8lfXo9WWZUNm4walFObVk/view?usp=sharing

**Comment by mubarak** [comment]
@normanmaurer did you get a chance to take a look at heap dump? thanks for the help

**Comment by normanmaurer** [comment]
@mubarak sorry not yet... Will try today.

**Comment by normanmaurer** [comment]
@mubarak what resource leak detection level you use ?

**Comment by mubarak** [comment]
@normanmaurer we do use `-Dio.netty.leakDetectionLevel=paranoid`

**Comment by normanmaurer** [comment]
@mubarak that is most likely the problem... Try to reduce this by using the default.

**Comment by mubarak** [comment]
@normanmaurer its been running quite with `-Dio.netty.leakDetectionLevel=simple`

Any idea when will 4.1 Beta6 will be released? we are using 4.1 Beta5 and seems like some important fixes are committed after Beta5.

**Comment by normanmaurer** [comment]
@mubarak over the next few days
