### ISSUE TITLE
HttpObjectDecoder#isContentAlwaysEmpty does not handle upgrade responses correctly

### ISSUE THREAD

**Issue by stuartwdouglas** [netty/netty#4095]
I ran into the following when testing Undertow HTTP2 interop via upgrade. This method contains the following:

            // Correctly handle return codes of 1xx.
            //
            // See:
            //     - http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html Section 4.4
            //     - https://github.com/netty/netty/issues/222
            if (code >= 100 && code < 200) {
                // One exception: Hixie 76 websocket handshake response
                return !(code == 101 && !res.headers().contains(HttpHeaderNames.SEC_WEBSOCKET_ACCEPT));
            }

This assumes that every response that does not have SEC_WEBSOCKET_ACCEPT is a Hixie 76 response, which is obviously incorrect for HTTP2 upgrade requests. A better approach would be to check directly for Hixie 76 headers. The only way I could get h2c to work correctly was to add a fake sec-websocket-accept header to my upgrade request.

**Comment by normanmaurer** [comment]
@stuartwdouglas could you link me to the code you used for testing?

**Comment by stuartwdouglas** [comment]
https://github.com/undertow-io/undertow/commit/c44b8239e2bca6e246616b1369433e3ed85e477e
This is based on the http2 client example in the netty repo

If you remove the sec-websocket-accept header the test fails. I think a more correct approach to detect Hixie 76 would be to check for the presence of Sec-WebSocket-Key1 and Sec-WebSocket-Key2 headers.

**Comment by normanmaurer** [comment]
Thanks will check!
