### ISSUE TITLE
missing io.netty.util.collection package in master branch

### ISSUE THREAD

**Issue by BlueIceQ** [netty/netty#4100]
hi:
    I git clone netty，and I find in master branch have no io.netty.util.collection package,but it used in other class.
![aaa](https://cloud.githubusercontent.com/assets/3064438/9352641/7a86d3ae-4695-11e5-9f9e-aa9cdaa474b1.jpg)

**Comment by normanmaurer** [comment]
These classes are generated by maven.

run "mvn clean package"

**Comment by BlueIceQ** [comment]
first: mvn clean
![image](https://cloud.githubusercontent.com/assets/3064438/9353478/34e464aa-469b-11e5-90d2-e34f9aee5f1d.png)

but it has some exception:
/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin/java "-Dmaven.home=/Applications/IntelliJ IDEA 14.app/Contents/plugins/maven/lib/maven3" "-Dclassworlds.conf=/Applications/IntelliJ IDEA 14.app/Contents/plugins/maven/lib/maven3/bin/m2.conf" -Didea.launcher.port=7535 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 14.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA 14.app/Contents/plugins/maven/lib/maven3/boot/plexus-classworlds-2.4.jar:/Applications/IntelliJ IDEA 14.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain org.codehaus.classworlds.Launcher -Didea.version=14.1.4 clean
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for io.netty:netty-testsuite-osgi:jar:5.0.0.Alpha3-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.ops4j.pax.exam:maven-paxexam-plugin is missing. @ line 220, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: osx
[INFO] os.detected.arch: x86_64
[INFO] os.detected.classifier: osx-x86_64
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/aether/RepositorySystemSession
	at kr.motd.maven.os.DetectExtension.injectSession(DetectExtension.java:115)
	at kr.motd.maven.os.DetectExtension.afterProjectsRead(DetectExtension.java:92)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:274)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.RepositorySystemSession
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
	... 21 more
---------------------------------------------------
constituent[0]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/aether-api-1.13.1.jar
constituent[1]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/aether-connector-wagon-1.13.1.jar
constituent[2]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/aether-impl-1.13.1.jar
constituent[3]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/aether-spi-1.13.1.jar
constituent[4]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/aether-util-1.13.1.jar
constituent[5]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/commons-cli-1.2.jar
constituent[6]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/commons-io-2.2.jar
constituent[7]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/commons-lang-2.6.jar
constituent[8]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/maven-aether-provider-3.0.5.jar
constituent[9]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/maven-artifact-3.0.5.jar
constituent[10]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/maven-compat-3.0.5.jar
constituent[11]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/maven-core-3.0.5.jar
constituent[12]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/maven-embedder-3.0.5.jar
constituent[13]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/maven-model-3.0.5.jar
constituent[14]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/maven-model-builder-3.0.5.jar
constituent[15]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/maven-plugin-api-3.0.5.jar
constituent[16]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/maven-repository-metadata-3.0.5.jar
constituent[17]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/maven-settings-3.0.5.jar
constituent[18]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/maven-settings-builder-3.0.5.jar
constituent[19]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/plexus-cipher-1.7.jar
constituent[20]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/plexus-component-annotations-1.5.5.jar
constituent[21]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/plexus-interpolation-1.14.jar
constituent[22]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/plexus-sec-dispatcher-1.3.jar
constituent[23]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/plexus-utils-2.0.6.jar
constituent[24]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/sisu-guava-0.9.9.jar
constituent[25]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/sisu-guice-3.1.0-no_aop.jar
constituent[26]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/sisu-inject-bean-2.3.0.jar
constituent[27]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/sisu-inject-plexus-2.3.0.jar
constituent[28]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/wagon-file-2.8.jar
constituent[29]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/wagon-http-2.8-shaded.jar
constituent[30]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/wagon-http-shared-2.8.jar
constituent[31]: file:/Applications/IntelliJ%20IDEA%2014.app/Contents/plugins/maven/lib/maven3/lib/wagon-provider-api-2.8.jar
---------------------------------------------------

Process finished with exit code 1

**Comment by normanmaurer** [comment]
You need to use at least maven 3.2.1.

**Comment by trustin** [comment]
Upgrading to os-maven-plugin 1.3.0.Final might solve the problem with low Maven versions, FYI

**Comment by BlueIceQ** [comment]
Thanks!

**Comment by BlueIceQ** [comment]
![image](https://cloud.githubusercontent.com/assets/3064438/9374687/f8faba62-472a-11e5-97b6-0eeebc20c517.png)

pom.xml have some errors, how can i do?

**Comment by trustin** [comment]
It's safe to ignore it.

**Comment by BlueIceQ** [comment]
Thanks!
