### ISSUE TITLE
HttpUtil and HttpHeaderUtil naming and consolidation

### ISSUE THREAD

**Issue by trustin** [netty/netty#4120]
Now I see two `HttpUtil` classes in our source tree; one in codec.http and the other in codec.http2.

Would it be better renaming `http2.HttpUtil` to `Http2Util` to be less confusing?

I also see `HttpHeaderUtil` in codec.http which may be better getting merged into `HttpUtil`. Does it make sense, or is it better as it is?

/cc @Scottmitch @nmittler @normanmaurer

**Comment by Scottmitch** [comment]
@trustin - 
`http2.HttpUtil` is named this way because it is all HTTP/1.x specific stuff. I'm not sure if we should change this.
`http.HttpHeaderUtils` is very specific to headers with the exception of 2 methods: `encodeAscii0` (why don't we use `ByteBufUtil.writeAscii`) and `c2b` which is private and only used by `encodeAscii0`.
`http.HttpUtil` - I recently added this for a few URI methods (because I couldn't find any where better).  Maybe there is a better place I could have put this?

**Comment by trustin** [comment]
Thanks for explanation about `http2.HttpUtil`. How about:

- merging HttpHeaderUtils to HttpUtil
- renaming http2.HttpUtil to HttpConversionUtil then?

**Comment by trustin** [comment]
Re: `encodeAscii0()` - it's there because we couldn't find a better place IIRC. `ByteBufUtil` could be a better place if anyone is interested in using it though.

**Comment by Scottmitch** [comment]
@trustin - That sounds good. I will pull together a PR.

@nmittler - Any objection?

**Comment by Scottmitch** [comment]
@trustin - It looks like there is a "duplicate" copy of `encodeAscii0` in 4.1 in [HttpHeaders](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpHeaders.java#L1160) introduced by 7f57c5ed that is not doing the `?` character substitution. I have removed this to make sure everyone is using the `encodeAscii0` in `HttpUtil` (which looks what 4.0 is doing), however do you feel we need the `?` character substation? If not we may be able to just use `ByteBufUtil.writeAscii(..)`.

**Comment by Scottmitch** [comment]
@normanmaurer ^^ WDYT about the `?` character substitution?

**Comment by trustin** [comment]
@Scottmitch I think we need `?` substitution whenever we convert a string into an ASCII string. If we didn't do that anywhere, it sounds like a bug to me.

**Comment by nmittler** [comment]
> renaming http2.HttpUtil to HttpConversionUtil then?

@Scottmitch @trustin this SGTM

**Comment by Scottmitch** [comment]
>  it sounds like a bug to me.

@trustin - Standby for PR with fix.
