### ISSUE TITLE
HttpHeaders 4.1 deprecation and consistency with master

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4121]
The master branch has a unified class hierarchy for headers.  When this work was back-ported (PR https://github.com/netty/netty/pull/3074) we agreed to change APIs for everything but HttpHeaders/DefaultHttpHeaders (see https://github.com/netty/netty/pull/2908#issuecomment-59883796) for backwards compatibility reasons.  Recently some major rework was done to rectify performance issues, and the discrepancy between HttpHeaders/DefaultHttpHeaders in master and 4.1 was a pain point. The maintenance is currently difficult, maybe error prone, and essentially all methods in HttpHeaders/DefaultHttpHeaders have been deprecated.  How can we improve this situation:

1. Can we break API in 4.1 HttpHeaders/DefaultHttpHeaders? Complexity would go down, a layer of indirection would be removed, and maintenance would be easier/less error prone.
2. Should we re-analyze the recent updates in 4.1? For example should all the methods be deprecated (some with no direct replacements...bcz I don't want to have to maintain both the new and the old interface in 4.1)?

I guess this brings up the bigger question of "what is our deprecation policy?".  The only thing I can find is http://netty.io/news/2014/12/17/changes-in-deprecation-policy.html which acknowledges a change, but does not reference any other "original" policy. 

For this specific case it was OK to break some~~/most~~ APIs, but not others. Is there a hard/fast rule on what can/cannot be broken, or is this more of a judgement call based on perceived usage and how users would react. Should we take some sort of user poll to see if the API breakage is tolerable?

/cc @trustin @normanmaurer @buchgr @nmittler

**Comment by trustin** [comment]
The original policy was the semantic versioning, as detailed in http://semver.org/ I thought it's too strict about deprecation and the removal of the deprecated API, so I changed the deprecation policy, but the basic principle remains same. e.g. 4.1.x JAR should be a drop-in replacement of 4.0.x JAR as long as a user did not use the deprecated API, did not use our API in an unusual way, and did not touch our internal API.

> Can we break API in 4.1 HttpHeaders/DefaultHttpHeaders?

No? 

> Should we re-analyze the recent updates in 4.1?

I'm not sure. It would be easy to decide to deprecate the methods with replacements. If there's no replacement, I would document it properly - why it's deprecated without replacement. Of course I wouldn't deprecate it if there's no good reason.

> For this specific case it was OK to break some/most APIs, but not others.

IIUC, the classes that changed without backward compatibility did not exist in 4.0, so we can make any changes until we release 4.1.0.Final. I don't think we didn't break any rule here therefore.

Here's what I think (and @normanmaurer as well I guess):

- We basically employ semver + relaxed deprecation policy.
- However, we are not dogmatic about it; we might break the API when we are pretty sure usual users are not surprised.  Changing most public API will be surprising in most cases, so we should be very careful. Here are some changes which might be fine:
  - Changes that might affect transport implementations, such as:
    - Changing some protected methods in `AbstractChannel`
    - Changing the `Unsafe`
  - Changes under the `internal` package
  - Experimental modules like spdy (this isn't experimental anymore though.)

WDYT?

**Comment by normanmaurer** [comment]
+1

**Comment by Scottmitch** [comment]
> IIUC, the classes that changed without backward compatibility did not exist in 4.0, so we can make any changes until we release 4.1.0.Final. I don't think we didn't break any rule here therefore.

`SpdyHeaders` changed. As you said I think this is no longer experimental any more?  Does the fact that no one has complained mean anything?

> I'm not sure. It would be easy to decide to deprecate the methods with replacements. If there's no replacement, I would document it properly - why it's deprecated without replacement. Of course I wouldn't deprecate it if there's no good reason.

This sounds reasonable. The documentation approach was to deprecate, and indicate rational (new methods were linked when existed, or an indication that it will no longer be supported in future releases). See [HttpHeaders](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpHeaders.java) and [DefaultHttpHeaders](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/DefaultHttpHeaders.java). Some of the "this method will not be available in future releases" may be a bit aggressive and maybe we should not deprecate in this case... Since `HttpHeaders` class hierarchy will change, but the class will still remain (as an interface) it was not deprecated.

**Comment by trustin** [comment]
> SpdyHeaders changed. As you said I think this is no longer experimental any more? Does the fact that no one has complained mean anything?

I'm not exactly sure when we started to think spdy is not experimental anymore, although it's considered pretty stable these days. I must admit I did not care much about API changes in spdy until very recently. Given that the future of SPDY is unclear, I'm not sure what we are supposed to do about it to be honest.

Perhaps we should keep it experimental given that:

* it's a proprietary protocol whose changes are completely at the mercy of Google, and
* we have HTTP/2.

> Some of the "this method will not be available in future releases" may be a bit aggressive and maybe we should not deprecate in this case... Since HttpHeaders class hierarchy will change, but the class will still remain (as an interface) it was not deprecated.

Yeah, I would still want to remove the deprecated method without alternative if there's a good reason not to use it though. (e.g. it's broken or ill-behaving by its design.)

**Comment by Scottmitch** [comment]
> Perhaps we should keep it experimental

I have no objection to this. @jpinner ?

> Yeah, I would still want to remove the deprecated method without alternative if there's a good reason not to use it though. (e.g. it's broken or ill-behaving by its design.)

@trustin - Would you mind cleaning up the deprecated approach in HttpHeaders / DefaultHttpHeaders as you see fit?

**Comment by trustin** [comment]
@Scottmitch Will try.. My internal project is near its end, so it's getting a little bit busy here though..

**Comment by Scottmitch** [comment]
@trustin - I have a PR pending for this. I found another breakage related to this for EMPTY_HEADERS so I'll just address both together.

**Comment by Scottmitch** [comment]
Deprecation policy in 4.1 should now be improved to only deprecate methods with alternatives.
