### ISSUE TITLE
[HTTP/2] outbound frames doesn't send to the kept clients

### ISSUE THREAD

**Issue by idelpivnitskiy** [netty/netty#4124]
[Aerogear WebPush Server](https://github.com/aerogear/aerogear-webpush-server) is an implementation of the [WebPush Protocol](http://tools.ietf.org/html/draft-thomson-webpush-http2-02) specification and it's built atop netty-codec-http2.

The problem is in [section 6](http://tools.ietf.org/html/draft-thomson-webpush-http2-02#section-6) of WebPush Protocol.
WebPush Server [saves a client context](https://github.com/idelpivnitskiy/aerogear-webpush-server/blob/4.1.0.Beta6-SNAPSHOT/server-netty/src/main/java/org/jboss/aerogear/webpush/netty/WebPushFrameListener.java#L346-L347) when the client subscribes to a new push messages. And when you send a new push message for this client, [server gets the client from the map and sends the message](https://github.com/idelpivnitskiy/aerogear-webpush-server/blob/4.1.0.Beta6-SNAPSHOT/server-netty/src/main/java/org/jboss/aerogear/webpush/netty/WebPushFrameListener.java#L203-L213).

It works well with Netty 4.1.0.Beta4, but after update to the Netty 4.1.0.Beta5 or to the latest 4.1.0.Beta6-SNAPSHOT, it doesn't work. The outstanding client will never receive push messages until it won't send any request to the server again.

For more information about this problem and how you can reproduce it, please, see https://github.com/aerogear/aerogear-webpush-server/pull/15

Could you, please, help me to find out what is going wrong?

**Comment by Scottmitch** [comment]
Hey @idelpivnitskiy - I commented on your PR https://github.com/aerogear/aerogear-webpush-server/pull/15. Would you be able to describe the problem in terms of the HTTP/2 spec, or where you are seeing unexpected behavior from Netty?  I'm a bit strapped for time :(

@danbev - can you help do a bit more digging?  Seems like you are the primary contributor to the aerogear project.

**Comment by idelpivnitskiy** [comment]
@Scottmitch I've debugged it and found out the reason of the problem. After that I had tracked changes of 4.1.0.Beta5 version and I understood, that it is not a bug :) Apologize for the noise!

For the version 4.1.0.Beta5, according to #3712, I need to call `client.ctx.flush()` after all writes to the channel:
https://github.com/idelpivnitskiy/aerogear-webpush-server/blob/4.1.0.Beta6-SNAPSHOT/server-netty/src/main/java/org/jboss/aerogear/webpush/netty/WebPushFrameListener.java#L203-L213
And it solved my problem.

For the current version, according to #3860, I also need to call `client.encoder.flowController().writePendingBytes();`.

Isn't it? If everything is correct, the issue could be closed.

**Comment by danbev** [comment]
Sounds like the issue might have been solved already. If not, let me know
and I'll be happy to help out. Will be more active now after a few weeks of
catching up with everything.

fredag 21 augusti 2015 skrev Scott Mitchell <notifications@github.com>:

**Comment by Scottmitch** [comment]
Yes writes now require explicit flush calls (for performance / separation of concerns).  Http2ConnectionHandler has a few trigger points that trigger flushes behind the scenes:
[readComplete](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L469)
[writabilityChanged](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L427)


> For the current version, according to #3860, I also need to call client.encoder.flowController().writePendingBytes();.

If you are using Http2ConnectionHandler that may already be done for you https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L201.

Sounds like the issue was resolved and no changes to Netty required :)
