### ISSUE TITLE
epoll - random timeouts

### ISSUE THREAD

**Issue by ninja-** [netty/netty#4127]
this has been an issue for years and so far no one investigated....

there's an issue that connections do not get channelInactive() called after someone quits or they timeout or even worse, the connection stays forever and cannot be closed!

it CAN be reproduced every time

the application related is https://github.com/SpigotMC/BungeeCord with an epoll switch - the behaviour change is clearly visible. I tried to investigate it myself, adding debugs to channel closing, channel inactive etc. and confirmed it could be only an issue of netty. I am on netty4.30.final

@normanmaurer 

@md-5 @thinkofdeath may be interested if solution is found

not sure if related but I am running ovh-grsec kernel
 3.14.32-xxxx-grs-ipv6-64 #1 SMP Tue Jun 30 18:50:21 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ninja-** [comment]
checking if backporting 22cea8a2cc7c3082478f214876e8d06161307c59 fixes the problem

**Comment by ninja-** [comment]
a normal session, doing a server ping:

[pid  6100] 22:45:04 accept4(71, {sa_family=AF_INET, sin_port=htons(49905), sin_addr=inet_addr("89.77.136.139")}, [16], SOCK_CLOEXEC|SOCK_NONBLOCK) = 72
Process 6172 attached
[pid  6100] 22:45:04 accept4(71, 0x755d901252a0, [128], SOCK_CLOEXEC|SOCK_NONBLOCK) = -1 EAGAIN (Resource temporarily unavailable)
[pid  6172] 22:45:04 close(73)          = 0
22:45:04 [INFO] channelActive: [id: 0xb6e1bcc7]
>Process 6173 attached
Process 6174 attached
[pid  6174] 22:45:04 close(72)          = 0
[pid  6172] 22:45:04 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0x756229732300} ---
[pid  6174] 22:45:04 +++ exited with 0 +++
22:45:04 [INFO] channelInactive: [id: 0xb6e1bcc7]

**Comment by ninja-** [comment]
a broken close() example() (starting EXACTLY when I close my connection client-side)

 Process 6696 attached
[pid  6696] 22:46:21 close(72Process 6751 attached
 <unfinished ...>
[pid  6751] 22:46:32 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x8} ---
[pid  6751] 22:46:32 close(72)          = 0
[pid  6093] 22:46:42 close(72)          = 0
[pid  6093] 22:46:42 close(72)          = 0
[pid  6093] 22:46:42 close(72)          = 0
[pid  6093] 22:46:42 close(72)          = 0
[pid  6696] 22:46:45 <... close resumed> ) = 0
[pid  6696] 22:46:45 +++ exited with 0 +++
22:46:45 [INFO] channelInactive: [id: 0x629323a5]
>Process 6840 attached
[pid  6840] 22:46:45 close(76)          = 0
22:46:45 [INFO] [Player] -> UpstreamBridge has disconnected
22:46:45 [INFO] channelInactive: [id: 0x073a78fc]
22:46:45 [INFO] [Player] <-> DownstreamBridge <-> [server] has disconnected
>[pid  6840] 22:46:46 +++ exited with 0 +++

**Comment by ninja-** [comment]
the syscalls are looking quite the same without epoll but close() never hangs!

**Comment by ninja-** [comment]
a more detailed trace(exactly when quitting)

23:28:30 [INFO] Command not found
>Process 10465 attached
[pid 10465] 23:28:40 close(72
23:28:49 [INFO] Command not found
>Process 10517 attached
 <unfinished ...>
[pid 10517] 23:28:56 close(72)          = 0
 > /lib/x86_64-linux-gnu/libpthread-2.19.so(__close_nocancel+0x24) [0xf41d]
 > /tmp/libnetty-transport-native-epoll2171018356851944341.so(Java_io_netty_channel_unix_FileDescriptor_close+0x1d) [0x3b59]
 > unexpected_backtracing_error [0x6f54b5015b74]
[pid 10465] 23:29:04 <... close resumed> ) = 0
 > /lib/x86_64-linux-gnu/libpthread-2.19.so(__close_nocancel+0x24) [0xf41d]
 > /tmp/libnetty-transport-native-epoll2171018356851944341.so(Java_io_netty_channel_unix_FileDescriptor_close+0x1d) [0x3b59]
 > unexpected_backtracing_error [0x6f54b5015b74]
[pid 10465] 23:29:04 +++ exited with 0 +++
Process 10591 attached
23:29:04 [INFO] channelInactive: [id: 0x3f672170
>[pid 10591] 23:29:04 close(77)          = 0
 > /lib/x86_64-linux-gnu/libpthread-2.19.so(__close_nocancel+0x24) [0xf41d]
 > /tmp/libnetty-transport-native-epoll2171018356851944341.so(Java_io_netty_channel_unix_FileDescriptor_close+0x1d) [0x3b59]
 > unexpected_backtracing_error [0x6f54b5015b74]
23:29:04 [INFO] [Player] -> UpstreamBridge has disconnected
23:29:04 [INFO] channelInactive: [id: 0x6a6c4409
23:29:04 [INFO] [Player] <-> DownstreamBridge <-> [server] has disconnected
>[pid  9798] 23:29:05 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=0x6f54cc721380} ---
[pid 10591] 23:29:05 +++ exited with 0 +++
[pid 10368] 23:29:15 +++ exited with 0 +++

**Comment by ninja-** [comment]
@normanmaurer disabling so_reuseaddr has reduced the probability of a bugged connection by 80%. I think I am on a right track :)

**Comment by ninja-** [comment]
[FIX] The problem can be fixed by disabling SO_LINGER

[img]http://memeorama.com/wp-content/uploads/2012/02/FEELS-GOOD-MAN-GOAT-300x225.jpg[/img]

**Comment by ninja-** [comment]
[FIX] The problem has been identified and fixed to match NIO behaviour!

https://github.com/ninja-/netty/commit/5795c866c6d2462eff175306c039e9a5e163e279

**Comment by trustin** [comment]
@normanmaurer Could you take a look?

**Comment by normanmaurer** [comment]
Yes will do

**Comment by normanmaurer** [comment]
@ninja- can you tell me what config options your app use related to SO_LINGER ?

**Comment by ninja-** [comment]
@normanmaurer haven't used SO_LINGER but it would get overrided anyway since I used IP_TOS and it triggers setTrafficClass which incorrectly passes it's value as a so_linger value it makes 0 sense and is clearly a bug

**Comment by ninja-** [comment]
ok @normanmaurer I know where this is going haha look closely at this piece of code what a coincidence  :D

**Comment by ninja-** [comment]
https://github.com/ninja-/netty/blob/5795c866c6d2462eff175306c039e9a5e163e279/transport-native-epoll/src/main/c/io_netty_channel_epoll_Native.c#L1219

these two functions are "just" swapped :laughing:

**Comment by normanmaurer** [comment]
@ninja- thanks!

**Comment by bobwenx** [comment]
i get same exception on `4.1.0.Beta6`:

```
java.io.IOException: readAddress() failed: connect timeout
	at io.netty.channel.epoll.Native.newIOException(Native.java:130) ~[netty-all-4.1.0.Beta6-20150825.121128-219.jar:4.1.0.Beta6-SNAPSHOT]
	at io.netty.channel.epoll.Native.ioResult(Native.java:146) ~[netty-all-4.1.0.Beta6-20150825.121128-219.jar:4.1.0.Beta6-SNAPSHOT]
	at io.netty.channel.epoll.Native.readAddress(Native.java:287) ~[netty-all-4.1.0.Beta6-20150825.121128-219.jar:4.1.0.Beta6-SNAPSHOT]
	at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:244) ~[netty-all-4.1.0.Beta6-20150825.121128-219.jar:4.1.0.Beta6-SNAPSHOT]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:787) ~[netty-all-4.1.0.Beta6-20150825.121128-219.jar:4.1.0.Beta6-SNAPSHOT]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollRdHupReady(AbstractEpollChannel.java:339) [netty-all-4.1.0.Beta6-20150825.121128-219.jar:4.1.0.Beta6-SNAPSHOT]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:337) [netty-all-4.1.0.Beta6-20150825.121128-219.jar:4.1.0.Beta6-SNAPSHOT]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:253) [netty-all-4.1.0.Beta6-20150825.121128-219.jar:4.1.0.Beta6-SNAPSHOT]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:699) [netty-all-4.1.0.Beta6-20150825.121128-219.jar:4.1.0.Beta6-SNAPSHOT]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-all-4.1.0.Beta6-20150825.121128-219.jar:4.1.0.Beta6-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
```

**Comment by ninja-** [comment]
maybe, it's possibly but this bug too.
don't use 4.1 or 5.0 they are "abounded" and behind 4.0 with fixes

**Comment by Scottmitch** [comment]
> don't use 4.1 or 5.0 they are "abounded" and behind 4.0 with fixes

@ninja- - We apply bug fixes to all branches that are applicable. If you have a specific instance where you are seeing bad behavior in 4.1+ that is not observable in 4.0 please report it and we will work with you to address it.

**Comment by Scottmitch** [comment]
@bobwenx - Can you please open another issue and describe your configuration (java version, uname -a, ...), your use-case, what you feel is the Netty bug, and preferably provide a reproducer?

**Comment by normanmaurer** [comment]
@ninja- will commit fix soon.

**Comment by bobwenx** [comment]
@normanmaurer after upgrade to latest netty version, there is no exception be thrown!
seems the commit fix the problem.
