### ISSUE TITLE
No new nightly builds since August 8?

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#4130]
It appears there haven't been any new nightly builds since August 8. Is that intentional?

http://clinker.netty.io/nexus/content/repositories/snapshots/io/netty/netty-all/4.1.0.Beta6-SNAPSHOT/

**Comment by Scottmitch** [comment]
That may be right around the time the new build system showed up https://garage.netty.io/teamcity/overview.html.  @trustin - any ideas?

**Comment by trustin** [comment]
Yes, Clinker has been acquired by CloudBees and they are shutting down their services. We are now publishing our nightly builds to oss.sonatype.org only. Sorry for your inconvenience. Let me update the web stie.
