### ISSUE TITLE
PlatformDependent.throwException() with null argument takes down the JVM

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#4131]
I'm not sure if it's a bug or feature but it's certainly not easy to debug.

Netty 4.1.0-Beta6-SNAPSHOT

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f80fbe956c9, pid=1196, tid=140191066928896
#
# JRE version: Java(TM) SE Runtime Environment (8.0_40-b25) (build 1.8.0_40-b25)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x5756c9]  Exceptions::_throw(Thread*, char const*, int, Handle, char const*)+0x1d9
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /<path>/hs_err_pid1196.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/
#
```

**Comment by Scottmitch** [comment]
@rkapsi - Is `PlatformDependent.throwException(null)` called from Netty code, and if so do you know where from?

**Comment by rkapsi** [comment]
@Scottmitch no, not from Netty code. It was some code I wrote and one can argue it was my own fault (given the nature of that class) but I wish it'd have failed more gracefully.

**Comment by Scottmitch** [comment]
@rkapsi - Humm I guess at least in the case of unsafe we should ensure the language specification is honored:

http://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.18

>  If evaluation of the Expression completes normally, producing a null value, then an instance V' of class NullPointerException is created and thrown instead of null. The throw statement then completes abruptly, the reason being a throw with value V'.

@trustin @normanmaurer - WDYT?

**Comment by Scottmitch** [comment]
I have a PR pending for this.

**Comment by trustin** [comment]
+1. Thanks for taking care.
