### ISSUE TITLE
CompositeByteBuf.getBytes() [toComponentIndex()] slow?

### ISSUE THREAD

**Issue by ninja-** [netty/netty#4133]
Am I correct that there is a noticeable overhead?
Is there a room for improvement?

What I am trying to do is balance between trying to do stuff 100% zerocopy and ability to grow the packet buffer in _some_ cases before sending it back. 
(the use case is that at decoder level a buf is created: CompositeByteBuf[a slice from input stream, a new small buffer] and I am evaluating whether this is a performance improvement from just doing a .copy() )

Maybe if the overhead of CompositeByteBuf is bigger than always creating a .copy at packet decoder, I should just revert and get rid of it?

**Comment by trustin** [comment]
Yes, it's slow, mainly because it performs a binary search to find the right component.  Maybe we could improve its performance to some extent, but it's probably better just staying away from it when you need to access the content of the buffer.

Alternatively, you could get the component from the composite buffer and access it in lieu of accessing the composite buffer. This will remove the binary search, so it should be as fast as accessing a non-composite buffer.  For more information, please take a look into `CompositeByteBuf.componentAt()` and `numComponents()`.

**Comment by ninja-** [comment]
(updated description)

@trustin I started from a decoder that always did in.copy() looking for possible improvement. As I mentioned in updated description I sometimes need to grow the buffer. Is in.copy() that bad[the input is a slice from a frame decoder]?

I am asking because it feels like everything I do to the app, rewriting it to use best conventions etc., all the decoders encoders buffers, using epool, doesn't affect the CPU usage at all. Feels like maybe my whole app logic(proxing game connections) is 10% of the load and I have no control over the rest, so in that case there would be no sense to touch the logic arround .copy().

**Comment by Scottmitch** [comment]
@ninja- - What type of profiling have you done? If you can share the results of profiling your application we may be able to see what the netty hot spots are. A few questions:

- `all the decoders encoders buffers` - what do you mean by this?
- When you say `doesn't impact the CPU usage at all`, do you mean you are consistently saturated?  By using EPOLL does your throughput (or other metrics change at all).
- `Feels like maybe my whole app logic(proxing game connections) is 10% of the load` - what makes you feel this way? Is this what your profiling has shown?
- have you tried [PooledByteBufAllocator](https://github.com/netty/netty/blob/master/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java)?
- Do you use SSL/TLS?

**Comment by ninja-** [comment]
@Scottmitch I turned the profiler on today and I am currently waiting for load(players) to come, but the CompositeByteBuf.getBytes() is clearly a one [in.copy() vs CompositeByteBuf.getBytes() - what would create less load in total?]
>  Feels like maybe my whole app logic(proxing game connections) is 10% of the load - what makes you feel this way? Is this what your profiling has shown?

Maybe not profiling but looking at process cpu usage with the same count of active connections. It didn't quite change after optimizing to the max all the decoders, encoders, frame decoders etc. and adding epoll
and making every single bit 0-copy (and at the start, it was creating a copy like 3 times in the pipeline so maybe .copy() isn't a big deal)

Regarding PooledByteBufAllocator - yes, ssl/tls - no, there is a cipher involved but it's optimized to the max with native code (the basis is a popular BungeeCord project, and I am _experimenting_ with various optimizations.)

**Comment by Scottmitch** [comment]
> I turned the profiler on today 

Just curious what profiler are you using, and do you have a way to simulate player load?

> Also, the app always creates a 'system load' much higher than the summed process cpu usage. Is this normal behaviour?

You mean that the kernel is using a higher percentage of CPU than user space?

> there is a cipher involved but it's optimized to the max with native code (the basis is a popular BungeeCord project, and I am experimenting with various optimizations.)

So you have some custom JNI code somewhere in the mix?  What does the interface look like over the JNI boundary (are you passing pointers to direct buffers, or copying data)?

I think in general we should re-evaluate after you have collected benchmark results.  Why guess when we have tools that will tell us where to look :)

**Comment by ninja-** [comment]
@Scottmitch 

1.visualvm over jmx but I am struggling to get anything useful from it...
2.probably. in this theory the overhead of the proxy application is really small and the 200-300% process cpu is created primarily from read/write syscalls.
3. regarding jni - yes, that's direct buffers + zerocopy. I have recently removed cipher from the pipeline anyway so it's not that relevant.
https://github.com/SpigotMC/BungeeCord/blob/master/native/src/main/c/NativeCipherImpl.cpp

**Comment by Scottmitch** [comment]
@ninja- 

> 1.visualvm over jmx but I am struggling to get anything useful from it...

If you are using Oracle's JVM try [mission control](http://www.oracle.com/technetwork/java/javaseproducts/mission-control/java-mission-control-1998576.html). Much easier to remotely profile.

> 3. regarding jni - yes, that's direct buffers + zerocopy

I'm not a JNI expert but according to the [JNI spec](https://docs.oracle.com/javase/1.5.0/docs/guide/jni/spec/functions.html#wp9502) for `GetByteArrayElements` says: `the returned array may be a copy of the Java array`. The output parameter to determine if a copy was made is passed as `NULL` so how do you know if a copy is made or not?

> I have recently removed cipher from the pipeline anyway so it's not that relevant.

Good idea. isolate as much as possible.

**Comment by ninja-** [comment]
@Scottmitch don't worry about GetByteArrayElements, it's used only when cipher is initiated to load the key.
https://github.com/SpigotMC/BungeeCord/blob/master/native/src/main/java/net/md_5/bungee/jni/cipher/NativeCipher.java#L38 <- native cipher logic with a proof of being zerocopy and direct buffers

regarding the profiler Scott, I have kinda confirmed my theory. The proxy's logic is such a tiny bit in a full CPU time compared to native.readAddress and native.writeAddress (epoll internals) that I don't think it's worth optimizing anything with the buffers decoders etc.

**Comment by Scottmitch** [comment]
@ninja- - Would you mind sharing a screen shot of your results?

**Comment by Scottmitch** [comment]
> Also the data from visualvm are looking so incomplete...I don't know why. I need to try another tool.

Have you tried mission control like I suggested https://github.com/netty/netty/issues/4133#issuecomment-134481898? Overhead is much smaller than visualvm and easier to run remotely.  There is even a getting started video on the site I linked.

**Comment by ninja-** [comment]
@Scottmich I'll try mission control but I am having some problems with jmx roles. I need to find out which role would work because readwrite doesn't.

**Comment by ninja-** [comment]
@Scottmitch I reminded myself of a great tool to fully simulate the load. I'll try to get some data today, without testing on production. Then we can evaluate if there is _any_ point in optimizing bungee internals because if every part of logic is a tiny bit of what read/write takes, there's none. (to repeat the question, are read/write syscalls making the actual load?)

**Comment by Scottmitch** [comment]
> Then we can evaluate if there is any point in optimizing bungee internals 

Before we optimize anything lets focus on the profiler results. Please provide a FlightRecorder file or something similar so we can help.

> (to repeat the question, are read/write syscalls making the actual load or not much just like epollwait?)

Profiling native methods and system call execution time in java can be tricky, and some tools don't support this or require explicit configuration to enable it.

**Comment by ninja-** [comment]
@trustin could you make it so writing a CompositeByteBuf doesn't call #getBytes() but just writes each of it's components ? I could do it at the app level(creating another wrapper and then encoder) but this improvement sounds sane.

**Comment by trustin** [comment]
I'm not sure what it buys? Could you elaborate?

**Comment by ninja-** [comment]
well nevermind I guess

**Comment by normanmaurer** [comment]
Closing for nw
