### ISSUE TITLE
io.netty.channel.ChannelOutboundBuffer$Entry weird behaviour

### ISSUE THREAD

**Issue by ninja-** [netty/netty#4134]
Is it possible that a netty upgrade could cause these to start leaking? the netty leak detector doesn't show anything(paranoid mode), the refcnt on these 'leaked' buffers is 0. The only handle is at the Recycler.

```
   3:       3992174      255499136  io.netty.channel.ChannelOutboundBuffer$Entry
   1:       3992227      351315976  io.netty.buffer.PooledUnsafeDirectByteBuf
   2:       9039807      289273824  io.netty.util.Recycler$DefaultHandle
```

+ the RES of process 6gb and constantly growing

**Comment by normanmaurer** [comment]
@ninja- upgrading from which version ? Also could you provide the heap dump for inspection ?

**Comment by ninja-** [comment]
@normanmaurer I had problems loading smaller heap dumps and this one would take around 10gb...is there a better way to istolate the issue? 

4.0.24.Final, without thinking about it I increased the version to .30

**Comment by normanmaurer** [comment]
@ninja- if you could provide a small reproduce it would help. I'm not sure if it's an issue at all without more details. We start pooling Entry with netty 4.0.22.Final:

https://github.com/netty/netty/issues/2693

So I think I would need more infos or a reproducer to look into it.

**Comment by ninja-** [comment]
but why would you pool 4m buffers? before afaik after I removed players and forced gc the memory usage was down to just 10M without any buffers. Now it holds to ~ 1 GB in such test.

**Comment by normanmaurer** [comment]
@ninja- like I said it may be a bug.... the problem is without a reproducer / more infos it is hard for me to even get an idea where to look. What for example could help is have your upgrade version by version and let me know in which version it starts. 

Would this be possible ?

**Comment by ninja-** [comment]
yes I'll try to reproduce it without getting it on production. is there any useful debugging option for the recycler?

**Comment by normanmaurer** [comment]
@ninja- you could try to use `-Dio.netty.recycler.maxCapacity=10000` for example. This should set the maximal capacity for each thread to 10000. 

How many threads are you using that do allocations of buffers ?

**Comment by ninja-** [comment]
the thread count is default, 2*cpu, I'll try the maxcapacity option

**Comment by normanmaurer** [comment]
@ninja- how many cores we are talking here ?

**Comment by ninja-** [comment]
6-cores 12 with ht

**Comment by normanmaurer** [comment]
which means the max could be:

12 (cores) * 2 *  262144 (this is the default capacity per thread of the recycler elements)  = 6291456

**Comment by ninja-** [comment]
soo it's not a bug? but clearly a change in behaviour that I don't like because the resources are shared with other apps

**Comment by normanmaurer** [comment]
Yeah I think so... Can you try the system property and let me know if this help?

**Comment by ninja-** [comment]
it would take a while to get it on production because I don't want to restart. But I'll let you know the result.

**Comment by ninja-** [comment]
@normanmaurer ok I got the setting on production we'll see if it helps

**Comment by ninja-** [comment]
@normanmaurer could you tell me if doing setAutoRead(false) before closing a channel could cause this leak(so it would mean it's my fault)? 

currently I...
1. downgraded netty on prod. system 1
2. added maxcapacity on prod system 2

**Comment by normanmaurer** [comment]
@ninja- no it can not cause a leak.

**Comment by ninja-** [comment]
ok now I checked what exactly is ChannelOutboundBuffer$Entry. it's a buffer scheduled to be written to outbound channel but never kinda written?

**Comment by normanmaurer** [comment]
@ninja- yes... it is what was written via `channel.write(...)` but was not "flushed" out of the socket yet.

**Comment by ninja-** [comment]
clearly a regression  from netty4-final24 :( I think I would have a clear confirmation within a next hour or so(comparing two systems). I am working on a traffic simulator to test it outside of prod.

**Comment by Scottmitch** [comment]
@ninja- - Can you describe you scenario more and perhaps provide a reproducer?  I don't see much info we can use to help debug the issue.

- What are the trigger points in your application where you call `flush`? This could be a `writeAndFlush` call too.
- Are you taking into account `channel.isWritable()`? Based on your description it may be the case that the peer you are writing to is either not reading, or not reading fast enough to consume the data, and thus you experience memory pressure.

**Comment by ninja-** [comment]
@Scottmich the problem started happening after netty upgrade, flush() is called 
1. before closing the channel
2. when writing a packet always writeAndFlush is used (a packet is not written if channel.isWritable() returns false, and the "water marks" are set)

and it stays after all clients have disconnected...

**Comment by caipanjin** [comment]
It seems that Recycler didn't recycle the DefaultHandle even though the channel has been closed.I have the similar problem maybe related to it: https://github.com/netty/netty/issues/3319

**Comment by normanmaurer** [comment]
@ninja- we are not saying its not a bug I just try to get a better idea where to look and a reproducer would help a lot as I was not able to reproduce the problem here.

**Comment by ninja-** [comment]
@caipanjin I don't think the reason is https://github.com/netty/netty/commit/a9fda3c8e0b20a1a3da0353c033cb57be7ad49b2 because it is since final25 and we both had "this" problem on final24 and final30

**Comment by ninja-** [comment]
RELATED: #3166

**Comment by normanmaurer** [comment]
@ninja- I'm not sure this is related...

**Comment by caipanjin** [comment]
@caipanjin We also found this problem when we use final24, and we have tried to update to final30. So I thought this is related.

**Comment by ninja-** [comment]
@normanmaurer I created a testcase package on pc: bungee, spigot, snakebot. Now I am trying to push the ChannelOutboundBuffer count but it can't reach more than 10...

**Comment by ninja-** [comment]
@normanmaurer so I am running 100 bots and the $Entry count isn't increasing, it's still less than 10...where could the problem be?

**Comment by normanmaurer** [comment]
@ninja- I don't know that is why I'm struggling to help here :(

Maybe it only happens when the remote peer dies or is slow. Just guessing here though

**Comment by ninja-** [comment]
@normanmaurer good news it seems like I isolated the case :) it 'keeps' them when a remote peer joins and I see it increases and stays after this. where do we go from there?

**Comment by normanmaurer** [comment]
@ninja- what you mean with remote peer joins ?

**Comment by ninja-** [comment]
@normanmaurer hm I am working to make this reproducable every time but it seems a bit random. :( I got it to 1000 5 minutes ago(stressing with slow peers + 100 bots) but now it's hard to increase.

**Comment by ninja-** [comment]
hell @normanmaurer after long tries it triggered going to infinity by itself...
once triggered, it would I think leak one for every send packet _for a triggered connection_

  40:           203          12992  io.netty.channel.ChannelOutboundBuffer
   4:        212588       13605632  io.netty.channel.ChannelOutboundBuffer$Entry
   3:        425286       13609152  io.netty.util.Recycler$DefaultHandle

took 20 minutes of tries to get it 'activated'...before I was having problems reaching even 100/200 with every stressing I could make. then when it triggered it started going from ~ 200 to 200000

**Comment by normanmaurer** [comment]
@ninja- I'm really trying to help here but I'm not sure I understand what exactly you did to have it triggered. Can't you share your reproducer and tell me how I can run it myself ?

**Comment by ninja-** [comment]
@normanmaurer sure I can share the package, thanks for all your help :)
the package consists of

1. bungeecord
2. spigot instance
3. snakebot
4. configurations for all these apps
4. a script which prints current $Entry count from jmap every second

(I'll mail you the stuff)
but it needs a Minecraft client to connect to the snakebot. I would guess you don't have the game bought? In that case I'll try to isolate the case so it wouldn't need a Minecraft client to run.

Reproduced it again. Connected to server with bots, did nothing just waiting - out of sudden started going to infinity. Keep in mind this is netty 4.0-final24. Seems like time is the key...

   3:       4411127      282312128  io.netty.channel.ChannelOutboundBuffer$Entry
   2:       8822348      282315136  io.netty.util.Recycler$DefaultHandle

Recycler handles are 2x of $Entry. does that tell you anything?

**Comment by normanmaurer** [comment]
@ninja- I don't have minecraft and never played it actually ;)

**Comment by ninja-** [comment]
@normanmaurer yeah that's why I am working to isolate the problem so it doesn't need a client to test :(

**Comment by ninja-** [comment]
I feel that what I reproduced on .24 was a bug that @trustin fixed in .25.
The problem was occuring both on .24 and on .30 on production and I am struggling to reproduce _something_ in testing env while on netty .30

**Comment by ninja-** [comment]
@normanmaurer let's _assume_ there is no such problem in .30 and just the default max cache is too big ?

**Comment by normanmaurer** [comment]
@ninja- too big is a matter of taste I guess but yeah maybe we should use something smaller as default. @trustin WDYT ?

**Comment by ninja-** [comment]
@normanmaurer it's just that I liked to System.gc() my bungee when it's empty and this way I always got it back to 10MB of memory used. something changed between the versions so that it doesn't allow me to do it this way. Assuming .24 allowed me to purge the caches with gc but had an infinity bug and .30 doesn't have an infinity bug but doesn't allow to purge the caches.

**Comment by ninja-** [comment]
Related - #3166

**Comment by ninja-** [comment]
@normanmaurer @tea-dragon left us a hint at #3166 wdyt ?

**Comment by normanmaurer** [comment]
@ninja- I would like to know first if adjust the system property had any impact at all in the memory usage.  I'm talking about "-Dio.netty.recycler.maxCapacity=somenumber"

**Comment by ninja-** [comment]
@normanmaurer hm I think it did, example: this server
maxCapacity: 5000, 24 threads, pretty sure this one was running with netty .30

   7:         60820        3892480  io.netty.channel.ChannelOutboundBuffer$Entry

**Comment by ninja-** [comment]
but still...why ChannelOutboundBuffer$Entry and no other parts of code that are using the recycler? what is so special about it?

**Comment by trustin** [comment]
@ninja- TCP_NODELAY is on by default in Netty 4: https://github.com/netty/netty/blob/4.0/transport/src/main/java/io/netty/channel/socket/DefaultSocketChannelConfig.java#L52

**Comment by ninja-** [comment]
@trustin oh :\ no idea why it needed so much buffers at the same time, then

**Comment by tea-dragon** [comment]
Netty doesn't consolidate pending writes. So threads a, b, ..n all quickly make writes to some socket(s). Either it's already maxed it's bandwidth, or the writing thread(s) don't own the socket and the thread that does is busy. Meanwhile these writes will queue up in these entries.

Properly written code will eventually respect water marks, detect the build up, and back off. However, netty decides to keep the entries it was using (maybe even very transiently using) just in case it needs them again.

My original complaint comment was focused on cases where many threads could trick a recipient thread into holding way more cache objects than normal by taking advantage of its blind greed. It sort of sounds like that was addressed to some degree, but I haven't looked into it since.

**Comment by ninja-** [comment]
@tea-dragon regarding the part about greed it seems to be adressed (the part when a "trigger" made it go to infinity). it's still greedy and annoying but not to a point that could crash the application as far as I checked. I tweaked default value for maxRecyclerSomething to stop the greed and I am 100% happy with it.

**Comment by tea-dragon** [comment]
I have found the need to greatly lower many default netty settings (arena
sizes etc), so that doesn't surprise me.

**Comment by Scottmitch** [comment]
> I tweaked default value for maxRecyclerSomething to stop the greed and I am 100% happy with it.

@ninja- - Do you feel this issue can be closed?

**Comment by ninja-** [comment]
I think yes, I am testing these settings on production for next 24h but I am pretty sure the greed will go away.

**Comment by ninja-** [comment]
"normal" traffic (snakebot) + emptying the server afterwards

   3:        792848       50742272  io.netty.channel.ChannelOutboundBuffer$Entry
   1:        792873       69772824  io.netty.buffer.PooledUnsafeDirectByteBuf
   2:       1608897       51484704  io.netty.util.Recycler$DefaultHandle

+ forcing gc + using histo:live

-Dio.netty.eventLoopThreads=12 \
-Dio.netty.recycler.maxCapacity=10000 \

the numbers aren't adding up, @Scottmitch...wdyt

**Comment by trustin** [comment]
@tea-dragon It sounds like we need to change Netty so it does not choose too greedy default. Do you have any suggestion in mind? I opened a new issue dedicated for this: #4146 so let's continue the discussion there.

**Comment by ninja-** [comment]
@trustin the default ones are another topic...I have set a max and it grows to infinity @trustin...clearly a bug not a wrong default

**Comment by trustin** [comment]
@ninja- Yeah, that's why I created a different issue not to distract you. I'm sorry!

**Comment by ninja-** [comment]
solved: I was trying to use the _recycler property_ from master while it's key is different on 4.0. It should stop being greedy now!

**Comment by Scottmitch** [comment]
@ninja- - I'm glad you figured this out!  Next time it would be appreciated if you could provide a reproducer because otherwise it burns a bunch of our time trying to track things down.  We are happy to help...it just that time is a limited resource.

**Comment by daschl** [comment]
could https://github.com/netty/netty/commit/14cbf65762fcdc357a3b11a9cb49b398b02c21dd be a fix for this, maybe? just stumbled across it

**Comment by normanmaurer** [comment]
Yes maybe

**Comment by johnou** [comment]
@ninja- out of interest what settings did you settle with?

**Comment by glcanvas** [comment]
Hi!
Long time no see=)
I have the same problem, 
during this conversation, I understood that a lot of Entry creates when a client too slow, and the server floods the client. So could you clarify which properties you specify to get rid of such problems?
