### ISSUE TITLE
Using finalize() to release ByteBufs

### ISSUE THREAD

**Issue by jazdw** [netty/netty#4145]
Java calls finalize() when garbage collection of an object occurs. Is there any reason we shouldn't use this functionality to free ByteBufs?

**Comment by trustin** [comment]
Because 1) it can worsen your JVM's GC performance, 2) JVM never calls `finalize()` when we want (i.e. immediately when object became unreachable); it calls it only when it wants. What you're gonna see is quick OOME.

**Comment by jazdw** [comment]
I was thinking more in terms of putting it in an object which holds a ByteBuf rather than in the Netty code. Save's managing the lifecycle of an object in applications where performance is not so critical such as clients. Would it really cause quick OOME? How so when compared to an object which holds the same data in a byte array?

**Comment by trustin** [comment]
Ah, I see. It is a question, not a bug. I thought you are suggesting to implement ByteBuf.finalize().

Nonetheless, the idea of using `finalize()` to release a `ByteBuf` in your application is not a good idea. It might work OK if the traffic is not very high and the client application is short-living. I believe you won't get OOME faster than ordinary object that holds a byte array.

**Comment by jazdw** [comment]
Yeah sorry, more a question about using Netty. There doesn't seem to be anywhere else to ask. Thanks for your feedback.

**Comment by trustin** [comment]
A better place to ask would be StackOverflow.com. We answer questions tagged with 'netty'. :-)
