### ISSUE TITLE
Provide a way to disable recycling completely

### ISSUE THREAD

**Issue by trustin** [netty/netty#4147]
It seems like some users are observing an edge case where the `WeakOrderQueue` and `Stack` grow beyond its max capacity. Although we should fix it, there should be a way for a user to disable recycling completely so that he or she can perform with-recycler vs. without-recycler comparison.

/cc @ninja-

**Comment by normanmaurer** [comment]
@trustin should I take care?

**Comment by trustin** [comment]
Do you have spare cycles? Then please feel free to take it. :-)

**Comment by normanmaurer** [comment]
@trustin spare cycles not really but let me fix it anyway =P

**Comment by Scottmitch** [comment]
Given https://github.com/netty/netty/issues/4134#issuecomment-135484445 do we feel this is still worth it?  I think we should push to diagnose / solve issues rather than disable features.

**Comment by normanmaurer** [comment]
@Scottmitch I think it still make sense to allow it for people that have limited memory constraints etc.

**Comment by ninja-** [comment]
@normanmaurer @Scottmitch looking at Recycler, isn't setting the size to 0 giving that effect?

**Comment by Scottmitch** [comment]
@ninja- - We currently don't allow the property to be set to 0 (see https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/Recycler.java#L51). However doesn't seem like it would hurt if we did allow 0... @normanmaurer - Is this what you had in mind?

**Comment by ninja-** [comment]
@Scottmitch it's fine when set to 1 [per thread]. I think we can keep it like that.

**Comment by Scottmitch** [comment]
@ninja- - I don't fully understand your request. Are you asking for a way to be able to "purge" entries and reduce the size of the stack?  Maybe submit a PR so we can get a better idea?

**Comment by ninja-** [comment]
@Scottmitch not purging but the logic should include shrinking also. I am saying that the _current logic_ doesn't suit _any_ type of the app. I proposed a new type of logic for Recycler that would cache the objects, but to a reasonable extent.

**Comment by normanmaurer** [comment]
Fixed

**Comment by Scottmitch** [comment]
@ninja- - Please open another issue for a feature request for your "purging" / "shrinking" Recycler entries
