### ISSUE TITLE
Make DefaultChannelGroupFuture public

### ISSUE THREAD

**Issue by chrisprobst** [netty/netty#4152]
I really miss the possibility, to handle multiple futures at once.
Of course, many use cases are covered by the ChannelGroup, but even simple things like sending a different message to all channels in a ChannelGroup can not easily be done.

We already have a ChannelMatcher abstraction, so that you can decide to not use _all_ channels during a query.

For me this is a but redundant, because it's basically hiding the default ChannelGroupFuture implementation.

I think, the main idea was to do internal iteration instead of external (like iterator), so that a ChannelGroup can decide who to write to multiple channels.
But leaving it this way, we would have to invent more and more abstractions just to keep internal iteration semantics.

With an eye on Java 8, maybe using Streams will make sense one day.

But for now, I propose to add a method for creating a new ChannelGroupFuture without actually doing any operation.

Like

```
ChannelGroup.newGroupFuture(Collection<ChannelFuture> f);
```

What do you think about this topic ?

**Comment by normanmaurer** [comment]
@chrisprobst are you still interested in this ?

**Comment by Scottmitch** [comment]
closing due to lack of interest ... please re-open if this is still valid.
