### ISSUE TITLE
Licenses structure breaks Android Studio

### ISSUE THREAD

**Issue by r2DoesInc** [netty/netty#4153]
Full issue and images posted on SO for image hosting.
http://stackoverflow.com/questions/32258219/gradle-case-insensitive-file-management

Basically, OSX is not case sensitive, and having your licenses in /meta-inf/license conflicts with many others who have a /meta-inf/license file for their licenses. 

My thought is that it would be as simple as changing /meta-inf/license to /meta-inf/licenses

Netty version
----------------------------------
3.5.2.Final

FutureHax$ gradle --version
--------------------------------------

Gradle 2.1

Build time:   2014-09-08 10:40:39 UTC
Build number: none
Revision:     e6cf70745ac11fa943e19294d19a2c527a669a53

Groovy:       2.3.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_20 (Oracle Corporation 25.20-b23)
OS:           Mac OS X 10.10.4 x86_64

FutureHax$ uname -a
------------------------------
Darwin Kens-MBP 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

Android Studio 
--------------------
1.3

Android SDK Tools
--------------------------
24.1.2

**Comment by trustin** [comment]
We do not support 3.5 anymore. Please upgrade to 3.10.x and let us know if the problem still exists.

**Comment by normanmaurer** [comment]
Let me close this for now.. if you still have the problem with 3.10.x please reopen
