### ISSUE TITLE
Netty in android

### ISSUE THREAD

**Issue by xiaoerlyl** [netty/netty#4161]
When I used netty 4.0.29 in my android app to connect my server,  I ran into this bug. Firstly I pressed the "off" button of my android phone to make my phone blank screen. and then press "off" button to light my phone screen
It seems that the exception closed my NIOEventLoopGroup. I don't know what should i do . 

08-28 14:47:16.289: W/AbstractChannel(8434): Force-closing a channel whose registration task was not accepted by an event loop: [id: 0x5da34355]
08-28 14:47:16.289: W/AbstractChannel(8434): java.util.concurrent.RejectedExecutionException: event executor terminated
08-28 14:47:16.289: W/AbstractChannel(8434): 	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:707)
08-28 14:47:16.289: W/AbstractChannel(8434): 	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:299)
08-28 14:47:16.289: W/AbstractChannel(8434): 	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:690)
08-28 14:47:16.289: W/AbstractChannel(8434): 	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:421)
08-28 14:47:16.289: W/AbstractChannel(8434): 	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:60)
08-28 14:47:16.289: W/AbstractChannel(8434): 	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:48)
08-28 14:47:16.289: W/AbstractChannel(8434): 	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:64)
08-28 14:47:16.289: W/AbstractChannel(8434): 	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:315)
08-28 14:47:16.289: W/AbstractChannel(8434): 	at io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:134)
08-28 14:47:16.289: W/AbstractChannel(8434): 	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:116)
08-28 14:47:16.289: W/AbstractChannel(8434): 	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:97)
08-28 14:47:16.289: W/AbstractChannel(8434): 	at com.tencent.wetestcontroller.util.NettyClient$2.run(NettyClient.java:94)
08-28 14:47:16.289: W/AbstractChannel(8434): 	at java.lang.Thread.run(Thread.java:841)
08-28 14:47:16.295: W/System.err(8434): java.util.concurrent.RejectedExecutionException: event executor terminated
08-28 14:47:16.295: W/System.err(8434): 	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:707)
08-28 14:47:16.296: W/System.err(8434): 	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:299)
08-28 14:47:16.296: W/System.err(8434): 	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:690)
08-28 14:47:16.296: W/System.err(8434): 	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:421)
08-28 14:47:16.296: W/System.err(8434): 	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:60)
08-28 14:47:16.301: W/System.err(8434): 	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:48)
08-28 14:47:16.302: W/System.err(8434): 	at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:64)
08-28 14:47:16.303: W/System.err(8434): 	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:315)
08-28 14:47:16.303: W/System.err(8434): 	at io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:134)
08-28 14:47:16.304: W/System.err(8434): 	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:116)
08-28 14:47:16.304: W/System.err(8434): 	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:97)
08-28 14:47:16.305: W/System.err(8434): 	at com.tencent.wetestcontroller.util.NettyClient$2.run(NettyClient.java:94)
08-28 14:47:16.305: W/System.err(8434): 	at java.lang.Thread.run(Thread.java:841)

**Comment by normanmaurer** [comment]
I have no knowledge of android so I can not help. But maybe as the people who wrote "com.tencent.wetestcontroller.util.NettyClient" ?

**Comment by normanmaurer** [comment]
Let me close this and reopen with more info if you feel its a bug
