### ISSUE TITLE
[Improvement] Fix multiple issues around PoolSubpage / PoolArena

### ISSUE THREAD

**Issue by ninja-** [netty/netty#4168]
now after I disabled recycler, it looks like there are few things left to left the application _fresh_ without restarting
(currently the process's RES is around 6GB while the used heap is around 70mb, while the app has no traffic + 1 day uptime)

   2:        142122        9095808  io.netty.buffer.PoolSubpage

I would guess that the PoolSubpage doesn't take a lot in jvm heap, but retains quite a bit of native memory. Is it possible to allow PoolSubpage to shrink via some runtime option?

Am I correct that this behaviour will change with these paremeters?
```
    ## lots of processes use netty buffers now, so set them here
    # max number of thread-locally cached buffers per power of 2 up to 512
    # default is 512, which seems kind of high (although not having 600 frame
    # reader threads helps the most). The cached space is less of an issue than
    # the overhead for all the little entries
    io.netty.allocator.tinyCacheSize: 32
    # same deal for powers of 2 up to the page size (8192), defaults to 256
    io.netty.allocator.smallCacheSize: 32
    # same deal for powers of 2 up to the maximum cachable size (32K), defaults to 64
    io.netty.allocator.normalCacheSize: 32
    # this is the thread-local caching control for non-buffers; mostly only an issue due to some blind-write cases
    io.netty.recycler.maxCapacity.default: 512
```

**Comment by Scottmitch** [comment]
@ninja- - Can you share your rational for closing this issue?  Did you find a resolution?

**Comment by ninja-** [comment]
@Scottmitch yeah adding allocator settings works fine for poolsubpage

**Comment by Scottmitch** [comment]
@ninja- Thanks for the feedback!

**Comment by ninja-** [comment]
hm, looks like after more "tests" the settings don't apply to the PoolSubpage... 
   2:        176220       11278080  io.netty.buffer.PoolSubpage

any idea what would be the correct setting to keep it fresh?

**Comment by ninja-** [comment]
btw. seems like DEFAULT_CACHE_TRIM_INTERVAL is not used anywhere. was it left not implemented?

**Comment by ninja-** [comment]
ok I analyzed it aand the math behind the number of PoolSubpages is 4096 * numDirectArenas

**Comment by normanmaurer** [comment]
@ninja- DEFAULT_CACHE_TRIM_INTERVAL is used: 

https://github.com/netty/netty/blob/4.0/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java#L329

Or what branch you are talking about ?

**Comment by ninja-** [comment]
@normanmaurer I think I am looking up too much on master instead of 4.0...

**Comment by ninja-** [comment]
instance of io.netty.buffer.PooledHeapByteBuf@0x6f3f985df278 (108 bytes)
maxCapacity (I) : 2147483647

References to this object:
io.netty.util.Recycler$DefaultHandle@0x6f3f985df258 (40 bytes) : field value

doesn't want to shrink etc. that's one example

**Comment by normanmaurer** [comment]
Let me close this for now. Please open a new issue with clear details what you would change.
