### ISSUE TITLE
epoll force closes connection

### ISSUE THREAD

**Issue by ninja-** [netty/netty#4170]
a small (visual) regression when doing nio vs epoll: 

When _proxy_ is running on epoll, and the connection to backend is disconnected, the backend server shows a message:
Player lost connection: Internal Exception: java.io.IOException: Error while read(...): Connection reset by peer

instead of "Player lost connection: disconnected"

Any idea of what could be the cause?
(I'll update when I find the piece of code in epoll that could cause this regression)

random guess: there should be a shutdown() syscall before close().
where to look for comparsion: java nio socketchannel.close()

**Comment by normanmaurer** [comment]
Without any infos what your code does it's hard to say.

**Comment by Scottmitch** [comment]
> Player lost connection: disconnected

I don't believe this would be an exception generated by Netty.

**Comment by ninja-** [comment]
i never said "disconnected" was an exception! It's an _lack_, of exception. Regarding code we are talking just about channel.close() here. I am 90% sure that adding shutdown syscall would make it match behaviour with nio.

**Comment by Scottmitch** [comment]
@ninja- - It would be helpful if you describe your issue in terms of Netty expected behavior vs Netty observed behavior.  Your description mixes in application concepts that don't exist in Netty.  We generally don't have knowledge of your application running on top of Netty or what it is doing in these circumstances.

Like for example (I'm trying to guess based upon what you have provided thus far) in NIO are you observing a [channelInactive(..)](https://github.com/netty/netty/blob/4.0/transport/src/main/java/io/netty/channel/ChannelInboundHandler.java#L43) and in EPOLL are you observing an [exceptionCaught(..)](https://github.com/netty/netty/blob/4.0/transport/src/main/java/io/netty/channel/ChannelInboundHandler.java#L73)? If so in what situations, and can you provide a reproducer?

> random guess: there should be a shutdown() syscall before close().
where to look for comparsion: java nio socketchannel.close()
..
> I am 90% sure that adding shutdown syscall would make it match behaviour with nio.

Have you tried this? What did you observe?

**Comment by ninja-** [comment]
@Scottmitch I will try adding shutdown() and then update this bug with results.

**Comment by normanmaurer** [comment]
@ninja- any news ?

**Comment by normanmaurer** [comment]
@ninja- ping...

**Comment by ninja-** [comment]
@normanmauer i can test it today. It's just one line od code

**Comment by ninja-** [comment]
@normanmaurer it got more complicated because I now see shutdown() syscall is used in some places. so I am not sure where to insert it.

**Comment by ninja-** [comment]
here's your fix, I tested it and it closes the connection properly now (no ugly message!)

```
Index: transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java	(revision 250a09df635d70853e1576a9e522c846e918938e)
+++ transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java	(revision )
@@ -535,7 +535,9 @@
             // Calling super.doClose() first so splceTo(...) will fail on next call.
             super.doClose();
         } finally {
+            safeShutdownPipe(pipeIn);
             safeClosePipe(pipeIn);
+            safeShutdownPipe(pipeOut);
             safeClosePipe(pipeOut);
             clearSpliceQueue();
         }
@@ -581,6 +583,18 @@
             } catch (IOException e) {
                 if (logger.isWarnEnabled()) {
                     logger.warn("Error while closing a pipe", e);
+                }
+            }
+        }
+    }
+
+    private void safeShutdownPipe(int pipe) {
+        if (pipe != -1) {
+            try {
+                Native.shutdown(pipe, true, true);
+            } catch (IOException e) {
+                if (logger.isWarnEnabled()) {
+                    logger.warn("Error while shutting down a pipe", e);
                 }
             }
         }
```

**Comment by normanmaurer** [comment]
Thanks ... Looking

**Comment by normanmaurer** [comment]
@ninja- do you use spliceTo(...) ?

**Comment by ninja-** [comment]
@normanmaurer no I don't think so, I don't even know what's that

**Comment by normanmaurer** [comment]
@ninja- ups sorry... I meant `spliceIn(...)`... If you not use it I think this can not have anything to do with this as pipeIn and pipeOut are only != -1 if `spliceIn(...) is called at some point.

**Comment by ninja-** [comment]
@normanmaurer yea I guess I could quickly get rid of this fix to get a 100% confirmation that it's doing it's job...

**Comment by ninja-** [comment]
@normanmaurer I can't get it to uncleanly close connection without the fix......that's weird, I doubt you have recently fixed this by accident. I'll get back to this bug when I could get it to show unclean disconnect. Maybe it would be easier to spot the difference on production, so I'll test it there.

**Comment by ninja-** [comment]
ok I confirm the difference with and without the fix

```
    @Override
    protected void doClose() throws Exception {
        try {
            ChannelPromise promise = connectPromise;
            if (promise != null) {
                // Use tryFailure() instead of setFailure() to avoid the race against cancel().
                promise.tryFailure(CLOSED_CHANNEL_EXCEPTION);
                connectPromise = null;
            }

            ScheduledFuture<?> future = connectTimeoutFuture;
            if (future != null) {
                future.cancel(false);
                connectTimeoutFuture = null;
            }

            safeShutdownPipe(pipeIn);
            safeShutdownPipe(pipeOut);

            // Calling super.doClose() first so splceTo(...) will fail on next call.
            super.doClose();
        } finally {
            safeClosePipe(pipeIn);
            safeClosePipe(pipeOut);
            clearSpliceQueue();
        }
    }
```

**Comment by normanmaurer** [comment]
@ninja- I think I not understand what you suggest here. For me I think the provide patch makes no sense in terms of a fix if you not use splicing.

**Comment by ninja-** [comment]
@normanmaurer well it's about a difference in how nio vs epoll forces connection. nio in every case calls shutdown() before close and epoll doesn't which is visible to other side of the connection as a connection reset etc.

**Comment by normanmaurer** [comment]
@ninja-  so you say nio basically does: 
```
shutdown(fd);
close(fd);
```

While epoll does:
```
close(fd)
```

Is this what you trying to say here ?

**Comment by ninja-** [comment]
@normanmaurer exactly. I am also unsure where would be a correct place for shutdown() to match nio.

**Comment by normanmaurer** [comment]
@ninja- ok gotcha... let me check

**Comment by normanmaurer** [comment]
@ninja- please check https://github.com/netty/netty/pull/4256
