### ISSUE TITLE
ThreadProperties test failure

### ISSUE THREAD

**Issue by trustin** [netty/netty#4171]
https://garage.netty.io/teamcity/viewLog.html?guest=1&buildId=951&tab=buildResultsDiv&buildTypeId=netty_build_oraclejdk8#testNameId3461555976749362710

/cc @normanmaurer 

And maybe you could also rename `testThreadDetails` to `testThreadProperties`?

**Comment by normanmaurer** [comment]
Urgh... Will check

**Comment by normanmaurer** [comment]
Fixed
