### ISSUE TITLE
netty-codec MqttDecoder should validate CONNECT reserved flag in variable header

### ISSUE THREAD

**Issue by longkerdandy** [netty/netty#4182]
The MQTT 3.1.1 Protocol Specification says:
> The Server MUST validate that the reserved flag in the CONNECT Control Packet is set to zero and disconnect the Client if it is not zero.
MqttDecoder should validate and throw a exception if it not zero.

**Comment by normanmaurer** [comment]
@longkerdandy we love contributions... Maybe you could submit a PR with a fix ?

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4986
