### ISSUE TITLE
Example securechat is outdatet and doesnt work with the current netty version

### ISSUE THREAD

**Issue by JuKu** [netty/netty#4184]
The example securechat is outdatet.
SslContextFactory doesnt exists anymore.

**Comment by Scottmitch** [comment]
@JuKu - What version of Netty are you using?  Can you provide a link as to where `SslContextFactory` is used?

**Comment by normanmaurer** [comment]
@JuKu please reopen if you still see an issue. examples in 4.0, 4.1 and master branch looking good
