### ISSUE TITLE
Can I request a seminar related to netty?

### ISSUE THREAD

**Issue by JungMinu** [netty/netty#4186]
@trustin Well, I'm a korean student majoing software engineering who are really into netty and open-source.

For those who want to be involed in netty and open-source, if possible, can I request a seminar or a meeting in person?
Thanks in advance!

**Comment by lkoszanski** [comment]
Sent from my BlackBerry 10 smartphone on the Bell network.                                                                                                                                                                                                                From: Minwoo JungSent: Friday, September 4, 2015 08:31To: netty/nettyReply To: netty/nettySubject: [netty] Can I request a seminar related to netty? (#4186)@trustin Well, I'm a korean software engineer who are really into netty and open-source
If possible, can I request a seminar or a meeting in person?
Thanks in advance!

—Reply to this email directly or view it on GitHub.

**Comment by normanmaurer** [comment]
This is for issues only.. closing
