### ISSUE TITLE
Netty deadlock with custom OIO transports

### ISSUE THREAD

**Issue by tttomat19** [netty/netty#4199]
Netty version: 5.0.0-Alpha2

I have an application that uses Android Bluetooth as transport. Looking into code for netty-rxtx it happened to be possible to adopt Android Bluetooth API as a transport for Netty.

here's the source for BluetoothChannel: https://gist.github.com/flirtomania/42d0d36668e4176ae2f7

The only issue was some kind of deadlock, when I called `ctx.writeAndFlush()` in handlers nothing had happened. The problem was that Android's inputstream.read() for Bluetooth was blocking the whole eventloop..

The following workaround helped. I'm just trying not to call read() for Bluetooth inputstream until there are some bytes received:

```
@Override
protected int doReadBytes(ByteBuf buf) throws Exception {
  long timestamp = System.nanoTime();
  while (true) {
    if (available() > 0) {
      break;
    }
    Thread.sleep(config.getAvailableSleepTimeMillis());
    if (System.nanoTime() - timestamp > config().getReadTimeoutNanos()) {
      return 0;
    }
  }
  return super.doReadBytes(buf);
}
```

Then https://github.com/jkschneider/netty-jssc this library also implements channel for Netty over serial ports using jSSC library. And again the write operations was not performed because everything was locked, until channel was closed or some bytes were received.
Luckily the same workaround helped for this jssc transport too:
 https://github.com/flirtomania/netty-jssc/blob/master/src/main/java/com/github/jkschneider/netty/jssc/JsscChannel.java

The first handler in the pipeline is LoggingHandler():

```
return new Bootstrap()
  .group(workerGroup)
  .channel(channelClass)
  .handler(new ChannelInitializer<AbstractChannel>() {
    @Override
    public void initChannel(AbstractChannel ch) throws Exception {
      log.info("initChannel {}", ch);
      ch.pipeline()
        .addLast(new LoggingHandler(LogLevel.TRACE))
        .addLast(new LengthFieldBasedFrameDecoder(2048, 4, 2, -6, 0))
        ...
```

Can you please explain why is this happening? Is the workaround ok? What if `Thread.sleep(config.getAvailableSleepTimeMillis());` will be removed? Will the application consume a lot of CPU then?

Maybe the default implementation of OioByteStreamChannel.doReadBytes() is not ok?
This implementation returns at least 1 always, but it does not work with Android Bluetooth inputstream, causing it to lock also same for netty-jssc library.

```
@Override
protected int doReadBytes(ByteBuf buf) throws Exception {
    int length = Math.max(1, Math.min(available(), buf.maxWritableBytes()));
    return buf.writeBytes(is, length);
}
```

**Comment by normanmaurer** [comment]
This issue is very old... Let me close it as its also more a question then an issue.
