### ISSUE TITLE
Allow retrieving the domain match lists in DomainNameMapping

### ISSUE THREAD

**Issue by trustin** [netty/netty#4200]
Currently, there's no way to retrieve the list of all domain name patterns and their mapped values. It would be very useful when you have to build another `DomainNameMapping` (or an arbitrary `Mapping`) based on that list. e.g.

```java
DomainNameMapping<SslContext> mapping = ...;
MyNameMapping<MyService> newMapping = ...;
mapping.entries().stream().forEach(e -> newMapping.add(e.getKey(), ...));
```

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5265
