### ISSUE TITLE
Consider using builder pattern to construct DomainNameMapping

### ISSUE THREAD

**Issue by trustin** [netty/netty#4201]
`DomainNameMapping.add()` makes `DomainNameMapping` look like it's safe to call `add()` anytime, and this is never true. It's probably better deprecate `add()` and introduce `DomainNameMappingBuilder`.

**Comment by normanmaurer** [comment]
+1

**Comment by idelpivnitskiy** [comment]
@normanmaurer Looks like it was resolved by PR #4579 and may be closed

**Comment by trustin** [comment]
Thanks for pinging, @idelpivnitskiy :-)
