### ISSUE TITLE
[Improvement] Recycle channel promises for write ?

### ISSUE THREAD

**Issue by ninja-** [netty/netty#4209]
I have changed the model of my proxy app to work with AUTO_READ = false hoping to save some CPU(I am yet to test, if it's worth it).
This introduced need to partially remove usage of voidPromise and use a real promise along with a listener that triggers a read, after write finished. Now that was creating one promise per write and I didn't quite like it. I used a very pretty hack to workaround this:

```
import io.netty.channel.Channel;
import io.netty.channel.ChannelPromise;
import io.netty.channel.DefaultChannelPromise;
import io.netty.util.Recycler;
import io.netty.util.concurrent.Future;
import io.netty.util.concurrent.GenericFutureListener;
import lombok.Setter;
import lombok.experimental.Accessors;

@Accessors(chain = true, fluent = true)
public class DownstreamReadPromise extends DefaultChannelPromise implements ChannelPromise, GenericFutureListener {
    private Recycler.Handle handle;
    @Setter
    private Channel upstream;
    @Setter
    private Channel downstream;

    private static Recycler<DownstreamReadPromise> RECYCLER = new Recycler<DownstreamReadPromise>() {
        @Override
        protected DownstreamReadPromise newObject(Handle<DownstreamReadPromise> handle) {
            DownstreamReadPromise r = new DownstreamReadPromise(handle);
            r.addListener(r);
            return r;
        }
    };

    public static DownstreamReadPromise newInstance(Channel downstream, Channel upstream)
    {
        return RECYCLER.get().downstream(downstream).upstream(upstream);
    }

    @Override
    public void operationComplete(Future future) throws Exception {
        System.out.println("hello there!!!");
        downstream.read();
        recycle();
    }

    @Override
    public boolean isDone() {
        return false;
    }

    @Override
    public Channel channel() {
        return upstream;
    }

    public void recycle()
    {
        handle.recycle(this);
    }
    @Override
    @SneakyThrows
    public boolean trySuccess(Void result) {
        operationComplete(null);
        return true;
    }

    public DownstreamReadPromise(Recycler.Handle handle)
    {
        super(null);
        this.handle = handle;
    }
}
```

now with this, everything was like I wanted it to be. I could finish right there, but I I thought maybe I could push some API improvements for netty, for such a case.

Options:
1. Create a special WriteTaskPromise w/ recycler once the listeners have been notified. Use that for every write() call inside netty.

(wouldn't that be a GC improvement for all the applications?)
2. Create a class called ActionPromise similar to my hacky class. Then let the user create his recycler if needed, or just reuse the created promise forever.

**Comment by normanmaurer** [comment]
@ninja- your implementation may be good for your use-case but very problematic for a general usage as you never know how long the user will hold a reference to the ChannelPromise.

**Comment by ninja-** [comment]
@normanmaurer ok
