### ISSUE TITLE
[ForkJoinPool] Thread Local Leak detected

### ISSUE THREAD

**Issue by jfarcand** [netty/netty#4211]
The Atmosphere Framework bundles the [ForkJoinPool](https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/internal/chmv8/ForkJoinPool.java) implementation of Netty. It seems there is a Thread Local leak as reported [here](https://github.com/Atmosphere/atmosphere/issues/2048)
```java
SEVERE: The web application [/atmosphere-chat] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@41a80e5a]) and a value of type [org.atmosphere.util.chmv8.ForkJoinPool.Submitter]
 (value [org.atmosphere.util.chmv8.ForkJoinPool$Submitter@450ae3fb]) but failed to remove it when the web application was stopped. This is very likely to create a memory leak.
```
When using the JDK7/8 implementation the leak doesn't occurs (no error message) so I suspect the current implementation leaks.

**Comment by slandelle** [comment]
Note that those `Submitter` are just `int` wrappers, so I think the leak is more of an annoying warning than a severe issue.

**Comment by buchgr** [comment]
Also the Netty `ForkJoinPool` is just a copy of the OpenJDK FJP. So maybe a simple up date to the latest OpenJDK version would resolve this.

**Comment by slandelle** [comment]
@buchgr I wonder if it's actually a fork of Doug Lea's initial work for JSR166-e, before it was merged into OpenJDK and modified again.

Netty's version has this [ThreadLocal<Subscriber>](https://github.com/netty/netty/blob/netty-4.0.31.Final/common/src/main/java/io/netty/util/internal/chmv8/ForkJoinPool.java#L1082) than [OpenJDK hasn't](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/util/concurrent/ForkJoinPool.java#l1098).

**Comment by buchgr** [comment]
@slandelle good point. I am not exactly sure. Just saying that updating it might resolve such things.

**Comment by slandelle** [comment]
@buchgr I'm not sure you guys will want to fork OpenJDK as it's GPLv2. You might want to use [Doug Lea's JSR166](http://g.oswego.edu/dl/concurrency-interest/) work that's Creative Commons - public domain.

**Comment by slandelle** [comment]
But I agree, upgrading should fix the issue as Tomcat doesn't reported against regular CHMv8.

**Comment by Scottmitch** [comment]
@slandelle - Thanks for the heads up!

@normanmaurer - I'll assign to you for now...pending discussion about 5.0.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5270
