### ISSUE TITLE
[RFE][Backport to 4.1] Add WebSocket Extension handlers for client and server.

### ISSUE THREAD

**Issue by jfarcand** [netty/netty#4212]
Backport https://github.com/netty/netty/commit/282d6e73b82ec943a739201f7be1985c45ef032b so `permessage-deflate` can be used in production once `4.1` is released.

**Comment by Scottmitch** [comment]
@jfarcand - We love PRs :smile: Any interest in helping on with this one?

**Comment by mubarak** [comment]
If no one is working on this issue, can i work on it? @Scottmitch @normanmaurer

**Comment by normanmaurer** [comment]
Go ahead

**Comment by Scottmitch** [comment]
+1 @mubarak

**Comment by jfarcand** [comment]
@Scottmitch @mubarak I don't have the cycle to backport it as I'm completely swamped with my own [projects](https://github.com/jfarcand), but I do have the cycle and setup to test it via the Nettosphere project. So ping me if you need production testing...and big thanks.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4584
