### ISSUE TITLE
Spdy Server Push fails to work

### ISSUE THREAD

**Issue by CodingFabian** [netty/netty#4224]
After upgrade to 4.1.0.Beta6 server push no longer works.

initially nothing worked anymore, but after backporting the fixes from #4185 and the header validation, it worked again

**Comment by CodingFabian** [comment]
ok, this has been resolved on our side, we were using an uppercase header in our push response which failed validation

**Comment by Scottmitch** [comment]
@CodingFabian - Good to know :)

**Comment by CodingFabian** [comment]
lets cross fingers for beta7 :)

**Comment by Scottmitch** [comment]
@CodingFabian - Turn around time should be faster for beta7...just a few more PRs we want to get in :)
