### ISSUE TITLE
Netty's Default Executor requires Unsafe, even on platforms that don't support it

### ISSUE THREAD

**Issue by timothyjward** [netty/netty#4228]
The DefaultExecutorServiceFactory class creates a netty ForkJoinPool -> https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/concurrent/DefaultExecutorServiceFactory.java#L75

This ForkJoinPool requires sun.misc.Unsafe -> 
https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/internal/chmv8/ForkJoinPool.java#L1048

This breaks on systems without Unsafe, so the code in the DefaultExecutorServiceFactory should be using PlatformDependent to detect which implementation it should use.

**Comment by Scottmitch** [comment]
thanks for reporting @timothyjward !

**Comment by Scottmitch** [comment]
@normanmaurer - I'll assign to you for now :wink:

**Comment by normanmaurer** [comment]
@Scottmitch :kiss:

**Comment by normanmaurer** [comment]
Can be closed as the master branch was deprecated and we are not doing this anymore in 4.1 and 4.1
