### ISSUE TITLE
Unix domain sockets coupled to epoll

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4231]
Currently the only implementation of `DomainSocketChannel` is coupled to the epoll module. It would be nice to have this decoupled so other unix distributions could take advantage of this.

**Comment by nmittler** [comment]
+1

**Comment by normanmaurer** [comment]
I csn add a kqueue transport

**Comment by Scottmitch** [comment]
kqueue would be nice, but maybe we don't need to go that far just yet. Do you think it is possible just to extract the EPOLL specific stuff out of the channel implementations currently in the `transport-native-epoll` module? The end goal being we have shared channel implementations (where is it possible and make sense) across unix like ditros?

**Comment by normanmaurer** [comment]
@Scottmitch that was actually the plan :)

**Comment by normanmaurer** [comment]
@Scottmitch related to #2448

**Comment by Scottmitch** [comment]
PR https://github.com/netty/netty/pull/4335 starts the decouple process.

**Comment by marcuslinke** [comment]
@normanmaurer I need unix domain socket support for MacOS. Whats the current state for this now? I saw PR of @Scottmitch but I'm not sure what is needed beside this.

**Comment by normanmaurer** [comment]
Its a high priority for us atm. You would need to write a jni based transport that supports kqueue for it. This will be not a small task

**Comment by Scottmitch** [comment]
> Its a high priority for us atm.

*not* high priority?

**Comment by normanmaurer** [comment]
Ups yes NOT high priority . Somehow lost a word here...

**Comment by Scottmitch** [comment]
@marcuslinke - The non linux specific stuff has been decoupled in the code, but since we don't have multiple native transport implementations yet the packaging/distribution part of the problem also needs to be solved (in addition to implementing kqueue).

**Comment by marcuslinke** [comment]
@normanmaurer Lost the most important word... ;-) @Scottmitch Thanks for clarifying!

So could one of you check http://eradman.com/posts/kqueue-tcp.html as guideline for the native implementation please?

**Comment by Scottmitch** [comment]
I took a quick glance and the basics seem to be there (create an FD and register it with kqueue). We should have most of the "generic unix socket/FD" stuff already coded. I think the EPOLL module should provide a good basic structure and just using the [kqueue](https://www.freebsd.org/cgi/man.cgi?query=kqueue&sektion=2) mechanisms instead of `transport-native-epoll` will be a good start. There will be some linux specific features in `transport-native-epoll` that won't be necessary initially.

**Comment by Scottmitch** [comment]
Please see #6000

**Comment by trein** [comment]
Hi guys.

Do you have any updates on this?

Thanks

**Comment by Scottmitch** [comment]
@trein - PR #6000 decouples the linux specific stuff from the more generic unix stuff. The intention is to merge this PR after 4.1.9 is released.

It would be appreciated if you could run your use case against PR #6000 and provide feedback before it gets merged. The more milage on this new code the better!

**Comment by lukewhitt** [comment]
Apologies if this is the wrong place but just wanted to add that I've run my use case against PR #6000 and found no problems what so ever. Everything compiled and all tests passed.

My use case is quite straight forward (create domain socket and listen for incoming messages) but works perfectly on my machine (MBP, macOS 10.12.3, Java 1.8.0_101). 

Really appreciate the work you guys have put in to this!

**Comment by Scottmitch** [comment]
Great news ... thanks for the update @lukewhitt!
