### ISSUE TITLE
Connect Netty UDT Client to C/C++ server

### ISSUE THREAD

**Issue by peterRd** [netty/netty#4232]
I am trying to integrate netty's UDT client example with Netty 4.0.31 but I am hitting a wall after initially connecting to my UDT C++ server. The client is on Android 5.1, Galaxy S6

The C++ server is the basic one as provided on the UDT manual http://udt.sourceforge.net/udt4/index.htm. I am printing packets at either end to confirm receipt/dispatch of packets. The initial connection comes through fine and 6 packets are sent back and forth as part of an extremely simple handshake algorithm. However, it is here and sometimes after this point that the server and client bugs out/hangs. After awhile the client times out and the same is seen on the server.

When I perform a C++ Server <=> C++ Client, it goes through fine with multiple R/W.
However with a C++ Server <=> java Client, it stalls on the UDT::recv(i presume). I have tried it with a few UDT solutions, Netty, UDT-Java, a modified Giggle-UDT but all have the same behaviour. Thought this would be the best place to ask as it is the most comprehensive framework

C++ Server code

```
    printf("Starting UDT");
    UDTSOCKET serv = UDT::socket(AF_INET, SOCK_STREAM, 0);

    sockaddr_in my_addr;
    my_addr.sin_family = AF_INET;
    my_addr.sin_port = htons(atoi(port));
    my_addr.sin_addr.s_addr = INADDR_ANY;
    memset(&(my_addr.sin_zero), '\0', 8);

    if (UDT::ERROR == UDT::bind(serv, (sockaddr*)&my_addr, sizeof(my_addr)))
    {
      std::cout << "bind: " << UDT::getlasterror().getErrorMessage();
      return 0;
    }

    UDT::listen(serv, 10);

    int namelen;
    sockaddr_in their_addr;

    UDTSOCKET recver = UDT::accept(serv, (sockaddr*)&their_addr, &namelen);

    if (recver == UDT::INVALID_SOCK)
    {
        UDT::close(recver);
        return -1;
    }

    char ip[16];
    std::cout << "new connection: " << inet_ntoa(their_addr.sin_addr) << ":" << ntohs(their_addr.sin_port) ;

    char data[100];

    //do{
    for (int i=0; i<3; i++)
    {
        if (UDT::ERROR == UDT::recv(recver, data, 100, 0))
        {
          std::cout << "recv:" << UDT::getlasterror().getErrorMessage() ;
          return 0;
        }

        std::cout << data;
    }   

    //} while(data[0] != 0 || secret == std::string(&data[1]));

    return recver;
```

**Comment by normanmaurer** [comment]
Let me close this as the UDT transport is ´@deprecated´
