### ISSUE TITLE
OpenSslEngine returns NOT_HANDSHAKING instead of FINISHED

### ISSUE THREAD

**Issue by ijuma** [netty/netty#4235]
Netty version: commit 6daf3246365a1c035249583d752e19474293a89f

Context:

I was trying to use `OpenSslEngine` instead of JDK's `SslEngine` in Kafka and I noticed that the former returns a SSLEngineResult with handshakeStatus of `NOT_HANDSHAKING` instead of `FINISHED` from wrap and unwrap right after the handshake finishes. `SslHandler` has a workaround for this (`setHandshakeSuccessIfStillHandshaking`), which claims to be for Android, but it seems to also be needed for `OpenSslEngine` (I used this same workaround and it allowed me to make progress, but it took a while to diagnose the issue).

The reason this happens is that `getHandshakeStatus()` is called to populate `SSLEngineResult` and both overloads return `HandshakeStatus.NOT_HANDSHAKING` if `handshakeState` is `HandshakeState.FINISHED`. 

Fixing this probably involves using the return value of `handshake()` to correctly populate `SSLEngineResult`.

Steps to reproduce:
1. Add a println after every `case FINISHED:` in `SslHandler`
2. Run `OpenSslEngineTest`
3. Notice that it's never triggered
4. Run `JdkSslEngineTest`
5. Notice that it's triggered a number of times
6. Add a println in `setHandshakeSuccessIfStillHandshaking`
7. Run `OpenSslEngineTest`
8. Notice that it is triggered

$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode

Operating system: OS X 10.11

$ uname -a
Darwin ijuma.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
@ijuma so you have a patch?

**Comment by ijuma** [comment]
@normanmaurer My initial attempt caused `OpenSslEngineTest` to fail, so I thought I'd file the issue in case I was missing some detail.

**Comment by normanmaurer** [comment]
@ijuma ok gotcha... will look into it. So I understand right that the problem is that unwrap/unwrap will never return "FINISHED" but just "NOT_HANDSHAKING" ?

**Comment by ijuma** [comment]
@normanmaurer Thanks, that's indeed what I was seeing.

**Comment by normanmaurer** [comment]
@ijuma is this server or client side ?

**Comment by ijuma** [comment]
@normanmaurer Both server and client.

**Comment by normanmaurer** [comment]
Have a fix almost ready...

**Comment by ijuma** [comment]
Great! I found another potential issue, filing it now.

**Comment by normanmaurer** [comment]
@ijuma awesome... keep em coming :)

**Comment by ijuma** [comment]
Here it is: https://github.com/netty/netty/issues/4238. As I said there, it may be a feature instead of a bug. In any case, you will let me know one way or another. :)

**Comment by normanmaurer** [comment]
@ijuma https://github.com/netty/netty/pull/4263 can you check

**Comment by normanmaurer** [comment]
Was fixed
