### ISSUE TITLE
OpenSslEngine: `unwrap` sets the position of the source buffer incorrectly if it follows more than one `wrap` call

### ISSUE THREAD

**Issue by ijuma** [netty/netty#4238]
_Note that the description below has been updated to describe the actual problem after more investigation._

Netty version: commit 94bf412edbea73c0b1dbac4ada8919708c4f369e

Context:

I was trying to use `OpenSslEngine` instead of JDK's `SSLEngine` in Kafka and I ran into an issue where `unwrap` sets the position of the source buffer incorrectly if the `unwrap` call happens after two or more `wrap` calls. I included a test below that shows the problem, but it basically boils down to:
- Each `unwrap` call will return the data for one record
- Multiple `wrap` calls means that the source buffer has more than one record
- In `writeEncryptedData`, there is the following code:

```
netWrote = SSL.writeToBIO(networkBIO, addr, len);
if (netWrote >= 0) {
    src.position(pos + netWrote);
}
```
- So, we set the position of the source buffer based on what is written to `BIO` without taking into account that `SSL.readFromSSL` will not return all of the data that we wrote to the `BIO`.

Steps to reproduce:
1. Checkout the openssl-unwrap branch in my fork https://github.com/ijuma/netty/tree/openssl-unwrap
2. Run OpenSslEngineTest
3. Run JdkSslEngineTest
4. Notice that `testWrapWrapUnwrap` fails with the former and passes with the latter

$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode

Operating system: OS X 10.11

$ uname -a
Darwin ijuma.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
@ijuma thanks will check

**Comment by normanmaurer** [comment]
@ijuma is it fine to include your test-code into netty ?

**Comment by ijuma** [comment]
@normanmaurer of course!

**Comment by normanmaurer** [comment]
@ijuma I just tried to run your test-code against the JDK SSLEngine end it fails here. Is this expected ? I thought you said the SSLEngineImpl does unwrap both records.

**Comment by normanmaurer** [comment]
@ijuma actually fails is the wrong word here... it just runs forever :)

**Comment by ijuma** [comment]
@normanmaurer, I extracted the test case after debugging why the Kafka code worked fine with JDK's SSLEngine, but not OpenSslEngine. I took some shortcuts on the handshake code for the test though, it doesn't run delegated tasks for example (which is OK for OpenSslEngine). I would guess that's the reason why it's not working for you. I can fix those issues if that helps.

**Comment by normanmaurer** [comment]
I will check thanks :) so does this mean kafka is using netty?

**Comment by ijuma** [comment]
Kafka doesn't use Netty at the moment. I'm trying to quantify the benefit of using OpenSslEngine in Kafka after seeing your slides stating that it performed better and seeing some impressive results in a simple benchmark. To do this I'm using netty-tcnative and Netty's classes to build the appropriate SSLEngine. I haven't changed the rest (so I'm not using SslHandler for example, it would have been easier if Kafka had been using it from the start).

**Comment by normanmaurer** [comment]
@ijuma I was not able to spent much time on it today but just an update even if I run the delegating tasks on the client and server engine its always is "NEEDS_UNWRAP" when using the JDK impl.

**Comment by ijuma** [comment]
Thanks for the update. Let me take a stab at making the test work with both implementations.

**Comment by ijuma** [comment]
I got the test to work with the JDK provider, but it fails in the same way as the OpenSSL one. So, it looks like the issue is more complicated than I initially described. I'm investigating and will update the issue with more information as soon as I have it. In the meantime, please don't spend your time on this. And sorry for the noise.

**Comment by ijuma** [comment]
@normanmaurer I updated the test:

https://github.com/ijuma/netty/commit/8fa80c045e5c0b4989688536801a2ebbb2a95a68

The problem is actually simpler, it's just that the position of the source buffer is not updated correctly if there are two wrap calls followed by an unwrap one.

**Comment by normanmaurer** [comment]
@ijuma can you jump into the #netty irc channel on free node ?

**Comment by ijuma** [comment]
@normanmaurer sure, joining now.

**Comment by normanmaurer** [comment]
@ijuma can you check this: https://github.com/netty/netty/pull/4254 ?

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5995
