### ISSUE TITLE
Support an HTTP/2 flow controller that ignores priority

### ISSUE THREAD

**Issue by nmittler** [netty/netty#4246]
Many applications (such as gRPC) do not make use of priority. By ignoring priority we can significantly increase the performance of the flow controller. We should consider either making a new flow controller, or factoring out the allocation algorithm.

Here's a sketch of the proposed algorithm:

1. Maintain a queue of streams with data to write.
2. When a stream has new pending bytes added:
    * If it's the first write for the stream, it goes to the *head* of the queue. This is an optimization to accommodate streams with small writes, helping to decrease their latency.
    * Otherwise, if the stream is not currently in the queue, it is added to the `end` of the queue.
3. We select a quanta (e.g. 1024 bytes) to allocate per stream. We allocate by traversing the queue:
    * We pop the head of the queue and attempt to allocate the quanta to the stream (limited by flow control windows and writability of the channel).
    * If the stream still has unallocated bytes, we then add it back to the *end* of the queue
    * We stop iteration once the connection window or writability of the channel has been exhausted (or there's nothing left to allocate).

@ejona86 @Scottmitch WDYT?

**Comment by Scottmitch** [comment]
@nmittler - Just to be sure we are starting from the same place we will also be ignoring the `SHOULD` statement in https://tools.ietf.org/html/rfc7540#section-5.3.2?

> Streams with the same parent SHOULD be allocated resources
   proportionally based on their weight.

Just to clarify some other statements:

> 1. Maintain a queue of streams with data to write.

Queue of streams with non-empty data frames? 

> When a stream is written to:

Are we still talking about evaluating the allocation amount on a flush operation, or on each write operation?  We may lose the "coalesce" benefits if we write immediately. I guess if the stream's data is completely written we won't have to queue at all?

> We select a quanta (e.g. 1024 bytes) to allocate per stream. We allocate by traversing the queue:

I wonder if it we could still be "fair" but potentially cut down on number of iterations if the quanta was based upon some sort of average of the number of pending bytes for each stream.

**Comment by nmittler** [comment]
>> 1. Maintain a queue of streams with data to write.

> Queue of streams with non-empty data frames? 

Generally Yes, although in the implementation we'll have to make sure everything behaves properly for empty frames as well.  We've been bitten by that before :).

>> When a stream is written to:

> Are we still talking about evaluating the allocation amount on a flush operation, or on each write operation? We may lose the "coalesce" benefits if we write immediately. I guess if the stream's data is completely written we won't have to queue at all?

I was referring to when a new write is received from the application (i.e. new pending bytes have been added for a stream).  I've updated the text.

>> We select a quanta (e.g. 1024 bytes) to allocate per stream. We allocate by traversing the queue:

> I wonder if it we could still be "fair" but potentially cut down on number of iterations if the quanta was based upon some sort of average of the number of pending bytes for each stream.

Possibly. We may want to start out with something simple and see if that's good enough.

**Comment by Scottmitch** [comment]
@nmittler - Your suggestion sounds reasonable to me. However can you comment on my first question from https://github.com/netty/netty/issues/4246#issuecomment-142148841 (about ignoring weights too)?

> Generally Yes, although in the implementation we'll have to make sure everything behaves properly for empty frames as well. We've been bitten by that before :).

Agreed. This was just meant to call out that streams that only have empty data frames to send shouldn't have to be queued.

> Possibly. We may want to start out with something simple and see if that's good enough.

+1

**Comment by nmittler** [comment]
>  Just to be sure we are starting from the same place we will also be ignoring the SHOULD statement in https://tools.ietf.org/html/rfc7540#section-5.3.2?

Yes, exactly ... we're taking advantage of the `SHOULD` :). We're ignoring priority and weights altogether.

**Comment by Scottmitch** [comment]
Yes as previously discussed I think this makes sense. I think we should strive to have https://github.com/netty/netty/issues/4271 in place so we can evaluate these changes.  Any interest in migrating gRPC benchmarks :grin:?

**Comment by nmittler** [comment]
Closing this, since it's submitted now (https://github.com/netty/netty/commit/ebfe3d2ba737b55ab770d6385786586ef0858203)
