### ISSUE TITLE
StompSubframeDecoder fails to decode a STOMP frame whose content is split across multiple packets (buffers)

### ISSUE THREAD

**Issue by silvaran** [netty/netty#4248]
I implemented a simple STOMP server and occasionally receive frames with no content-length header that include a body.  According to the STOMP 1.2 specification, "If a frame body is present, the SEND, MESSAGE and ERROR frames SHOULD include a content-length header to ease frame parsing." (https://stomp.github.io/stomp-specification-1.2.html#Header_content-length)

The StompFrameDecoder fails at the first byte in the body with the following,
<pre>15:09:11,390 ERROR [STOMP] (nioEventLoopGroup-3-7) STOMP frame decode error: java.lang.IllegalStateException: unexpected byte in buffer 66 while expecting NULL byte
	at io.netty.handler.codec.stomp.StompSubframeDecoder.skipNullCharacter(StompSubframeDecoder.java:228) [netty-codec-stomp.jar:4.1.0.Beta6]
	at io.netty.handler.codec.stomp.StompSubframeDecoder.decode(StompSubframeDecoder.java:155) [netty-codec-stomp.jar:4.1.0.Beta6]
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:370) [netty-codec.jar:4.1.0.Beta6]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230) [netty-codec.jar:4.1.0.Beta6]</pre>
I sent the following data:
<pre>         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 53 45 4e 44 0a 64 65 73 74 69 6e 61 74 69 6f 6e |SEND.destination|
|00000010| 3a 6e 6f 77 68 65 72 65 0a 63 6f 6e 74 65 6e 74 |:nowhere.content|
|00000020| 2d 6c 65 6e 67 74 68 3a 34 0a 0a 42 6f          |-length:4..Bo   |
+--------+-------------------------------------------------+----------------+</pre>
With 4.1.0.Beta6, even including content-length won't work (it will still assume content-length:0) because of this issue: https://github.com/netty/netty/issues/4247

**Comment by Scottmitch** [comment]
@silvaran - The `content-length` portion of this issue should be verified with the PR for https://github.com/netty/netty/issues/4247

**Comment by normanmaurer** [comment]
Was fixed
