### ISSUE TITLE
Make LengthFieldBasedFrameDecoder extensible

### ISSUE THREAD

**Issue by n06** [netty/netty#4249]
The ```LengthFieldBasedFrameDecoder``` is an awesome decoder class. It is quite common to use customer frames to transmit data between client and server. It would be nice if this class were easily extensible however.

The ```decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out)``` method is, for some reason, ```final``` making it hard to properly extend. If, for instance, I would like to de-serialize each message in a frame based on a field in the frame's header, it would be very nice to be able to catch the ```Object``` created by the ```decode(ChannelHandlerContext ctx, ByteBuf in)``` method, cast it, and then add that to the out ```List<Object>```

On that same note, it seems that the  ```decode(ChannelHandlerContext ctx, ByteBuf in)``` method always returns a ```ByteBuf``` is there a reason that the method then returns an ```Object``` instead?

**Comment by normanmaurer** [comment]
@n06 it returns Object so people can override it and so change the return type which sounds like what you would like to do from your example.

**Comment by n06** [comment]
@normanmaurer thanks for the quick reply! Yeah that was kind of a stupid question. Strip the ByteBuf of its type so that you can more easily cast it. What do you think of the rest of my suggestion? If the top-level ```decode``` method weren't final then users with more advanced use-cases might be able to make changes more easily. If there's a reason for the final method, I'd love to learn why (sorry if these questions are amateurish)

**Comment by normanmaurer** [comment]
@n06 I'm still not sure I understand why you would need the "top-level" decode method to be non final to full-fill anything here. I mean the implementation just adds stuff to the list and nothing more. So can you give me an example what you would do there that can not be done in the "overridable" decode method ?

**Comment by n06** [comment]
Yeah, I guess that's fair. I think I just wanted to avoid making a super() but now that I've had a chance to step back and think about it, you're absolutely right. Sorry for the entirely useless issue, I'm closing this. Thanks for taking the time to discuss it with me!

**Comment by normanmaurer** [comment]
@n06 no problem... happy to help!
