### ISSUE TITLE
Adding DefaultHttpHeaders to itself creates infinite loop

### ISSUE THREAD

**Issue by willisblackburn** [netty/netty#4265]
Example:

    public void test() {
        HttpHeaders headers = new DefaultHttpHeaders();
        headers.add("foo", "bar");
        headers.add(headers);
        // This will never end
        headers.forEach(entry -> {});
    }

**Comment by ninja-** [comment]
...why would you even do that

**Comment by normanmaurer** [comment]
@willisblackburn thanks for the report. Will add a guard against this

**Comment by Scottmitch** [comment]
@willisblackburn - I'm assuming you are using Netty 4.0?
