### ISSUE TITLE
DefaultHttp2RemoteFlowController not re-visiting nodes that still have streamable bytes

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4266]
The allocation algorithm may not distributed all the available bytes even though the streams may be able to use all the bytes. This is caused by the children that have streamable bytes not being considered hungry because the `nextConnectionWindow` has collapsed.

Also related to [DefaultHttp2RemoteFlowController](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2RemoteFlowController.java#L377) not taking into account the streamable bytes of peers.
```java
int connectionWindowChunk = max(1, (int) (connectionWindow * (child.weight() / (double) totalWeight)));
```

**Comment by Scottmitch** [comment]
@nmittler - FYI

**Comment by Scottmitch** [comment]
This is also related to https://github.com/netty/netty/issues/4242

**Comment by blucas** [comment]
@Scottmitch - Could you give an example for when this would happen? I haven't had this happen to me yet when testing HTTP/2 with Chrome/FF.

**Comment by nmittler** [comment]
+1

@Scottmitch as discussed offline, the first thing we need is a new test in [DefaultHttp2RemoteFlowControllerTest](https://github.com/netty/netty/blob/master/codec-http2/src/test/java/io/netty/handler/codec/http2/DefaultHttp2RemoteFlowControllerTest.java) that demonstrates this.

**Comment by Scottmitch** [comment]
@nmittler - On it.

**Comment by Scottmitch** [comment]
@blucas - This issue was really the root cause of the issue https://github.com/netty/netty/issues/4242 you reported. However the fix for https://github.com/netty/netty/pull/4258 (which is also necessary for other reasons) should mask the negative effects which may result from this issue. I think the only "visible" effects from this should be extra tree traversal(s) to make sure all bytes are written.

**Comment by Scottmitch** [comment]
Fixed by https://github.com/netty/netty/pull/4282
