### ISSUE TITLE
ByteToMessageDecoder to call fireChannelRead more frequently

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4284]
If a large amount of objects are added to the `out` list in [ByteToMessageDecoder.decode](https://github.com/netty/netty/blob/master/codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java#L373) for a single channelRead operation then this can result in a large amount of  `ByteBuf` objects to be allocated. There may be an opportunity for improvement in terms of `ByteBuf` reuse and reduction of allocations if we can call `fireChannelRead` more frequently.   

From @ninja- https://github.com/netty/netty/issues/4205#issuecomment-143324727:

> @Scottmitch yeah actuall y I pointed a bad place. At the moment I am using a hack that fires it inside decode() so more like:

```
Inside the frame decoder:

    @Override
    protected void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) throws Exception {
        Object o = decode(ctx,in);
        if (o != null)
            ctx.fireChannelRead(o); // instant fire, reuse buffers quicker :)

        if (o != null && out.isEmpty())
            out.add(Unpooled.EMPTY_BUFFER); // to get the read() correctly

    }

    //    @Override
    protected ByteBuf decode(ChannelHandlerContext ctx, ByteBuf in) throws Exception
{
// decode a frame here
}
```

> so I am not changing the original class.

**Comment by Scottmitch** [comment]
@ninja- Feel free to add more description.

**Comment by ninja-** [comment]
looks good to me.

**Comment by ninja-** [comment]
done @ PR #4288
