### ISSUE TITLE
Mock DNS server for automated unit tests

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4289]
The DNS unit tests frequently fail because they are relying on external DNS servers. We should work to make them more reliable and ideally decouple their reliance on external DNS servers.

**Comment by Scottmitch** [comment]
@trustin @normanmaurer - FYI

**Comment by normanmaurer** [comment]
Already working on it :)

**Comment by Scottmitch** [comment]
Thanks @normanmaurer !

**Comment by trustin** [comment]
Thank you guys!
