### ISSUE TITLE
OpenSsl NPN/ALPN unit tests

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4293]
We should have NPN/ALPN tests for the OpenSsl provider like we do for the Jdk provider.  See [JdkSslEngineTest](https://github.com/netty/netty/blob/master/handler/src/test/java/io/netty/handler/ssl/JdkSslEngineTest.java)

**Comment by ifesdjeen** [comment]
@Scottmitch fi you haven't yet started working on that one, I could help / contribute, WDYT?

**Comment by normanmaurer** [comment]
Yes please! I know Scott has not started yet :)

**Comment by ifesdjeen** [comment]
OK, gotta start with that one :)

**Comment by Scottmitch** [comment]
+1. Help would be much appreciated here @ifesdjeen!

**Comment by ifesdjeen** [comment]
@Scottmitch i've started working on test suite, and ran accross some deprecated constructors in https://github.com/netty/netty/blob/master/handler/src/test/java/io/netty/handler/ssl/JdkSslEngineTest.java do you think it'd make sense to use an SslContextBuilder there, too? 

I may be missing something but it looks like ContextBuilder is only used in `OpenSsl` version for now.

**Comment by normanmaurer** [comment]
Using SslContextBuilder is the way to go

**Comment by Scottmitch** [comment]
@ifesdjeen @normanmaurer +1

**Comment by ifesdjeen** [comment]
Should we close it after #4627? If anything is missing please let me know.

**Comment by Scottmitch** [comment]
@ifesdjeen - I think we can close this now. I also have a cleanup PR pending https://github.com/netty/netty/pull/4633 ... sorry I missed this during review.
