### ISSUE TITLE
SslHandler misses to store all queued MessageEvents on channel closed

### ISSUE THREAD

**Issue by jenskordowski** [netty/netty#4296]
org.jboss.netty.handler.ssl.SslHandler on line 1765 (Netty 3.9):
There seems to be a typo: Instead of checking futures != null, the list should only be instantiated if futures == null. As an effect, all previously stored entries are lost and in many cases, only the last encryptedWrite is kept in mind.
In other constellations (no unencryptedWrites, but encryptedWrites existing), this would even lead to a NPE.

Best regards
Jens

**Comment by ninja-** [comment]
Netty 3 isn't actively maintained and SSL recently had lots of fixes in netty 4. What stops you from migrating?

**Comment by jenskordowski** [comment]
Camel 2.14.x using AHC 1.8.5 using Netty 3.9.x. At some point, we will update of course, but not for now.

**Comment by jenskordowski** [comment]
Only the not-yet-released AHC 2.x will use Netty 4. So we need to wait for this release first, then for the Camel AHC component to incorporate that. Seems this will take a while.

**Comment by normanmaurer** [comment]
@ninja- this is not true. Critical stuff is still fixed in 3.10

**Comment by jenskordowski** [comment]
Ah ok, sounds good then. From your previous post I understood that Netty 3 will not receive the fixes.

**Comment by normanmaurer** [comment]
@jenskordowski btw we love PR's ... if you could do a PR with the fix I would be more then happy to review.

**Comment by slandelle** [comment]
> Only the not-yet-released AHC 2.x will use Netty 4.

Coming... Doing my best :)

**Comment by normanmaurer** [comment]
@slandelle <3

**Comment by jenskordowski** [comment]
Pull request: https://github.com/netty/netty/pull/4297

**Comment by normanmaurer** [comment]
@jenskordowski thanks again... Fixed by de16cfe3537246d916ea966b2c9380f84d8113e8
