### ISSUE TITLE
Cannot add Channel handlers to EmbeddedChannel after created

### ISSUE THREAD

**Issue by balsukrishna** [netty/netty#4301]
Context: Writing unit tests for my channel handlers and Using EmbeddedChannel.

I want to add ChannelHandlers with name (my handlers have logic to change pipeline and  I identify existing handlers with name).  So I am using EmbeddedChannel.pipeline.addLast().

I saw EmbeddedChannel source code and it is because of LastInboundHandler that it is not triggered.

Can we have a work around/fix  for this?

Reproduce:
```
EmbeddedChannel  ec = new EmbeddedChannel();
ec.pipeline().addLast(new SimpleChannelHandler);
c.writeInbound("helloworld");

class SimpleChannelHandler extends ChannelHandlerAdapter
{
	
	@Override
	public void channelRead(ChannelHandlerContext ctx, Object msg) 
	{
		String data = (String) msg;
              System.out.println("Received " + data);
    }
}

```
Netty Version: 5.0.0.Alpha2
java Version: Java 8
OS: Linux

**Comment by balsukrishna** [comment]
On the other note, Can I actually use EmbeddedChannel for Unit testing Netty code, any other library suggestions?

**Comment by normanmaurer** [comment]
@balsukrishna need to think about it. As a workaround you can use "addFirst(....)" .

**Comment by balsukrishna** [comment]
Thanks. addFirst method is enough for me now.

**Comment by leogomes** [comment]
It may become an issue if the handler you're trying to test dynamically adds another handler to the pipeline using ``addLast(..)`` :/

**Comment by normanmaurer** [comment]
This was fixed
