### ISSUE TITLE
Http2ConnectionHandler should handle all exceptions

### ISSUE THREAD

**Issue by nmittler** [netty/netty#4310]
In the [current HTTP/2 exception handling logic](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L625), if a lower-level error occurs (e.g. the socket breaks), we can get into this scenario: https://github.com/grpc/grpc-java/issues/1097. The first stack trace is due to the fact that the http2 handler ignores the exception and passes it through ... this seems wrong.  I think our handler should catch any exception coming up the pipeline and assume any unrecognized exceptions to be connection errors.

In past discussions we had talked about application-specific exceptions and allowing them to pass through the handler.  I suspect that isn't a real use case, however, and even if it was it might be better accomplished through user events.  Fundamentally, HTTP/2 is a low-level protocol and I think it's safe to assume that any exception we receive is from a vital part of the protocol stack below us (e.g. socket/tls)
and if that's broken, we're broken. In addition, HTTP/2 is a little different than other Netty handlers, in that applications do a combination of extension and listening to get events, rather than appending handlers after it in the pipeline.

@normanmaurer @Scottmitch Let's discuss.

**Comment by Scottmitch** [comment]
@nmittler - I'm not yet convinced that `Http2ConnectionHanler` handler should unconditionally treat an unrecognized exception as a fatal one. Seems like we should not make assumptions about what else is or is not in the pipeline. I agree that the exception handling needs some work (to be finished in https://github.com/netty/netty/pull/4291) in terms of ensuring exceptions that occur while processing codec events are appropriately propagated, and treated as a connection error if appropriate.

Can you describe the implications of leaving things (w.r.t to this issue) the way they are? Are we missing events, or are the logs just noisy?

**Comment by ejona86** [comment]
I'm not excited about Http2ConnectionHandler handling all exceptions. It seems the application using Netty is the best place to handle such things. What is fundamentally broken with the application handling this case as well?

**Comment by nmittler** [comment]
@Scottmitch @ejona86 I guess it just seems strange to me to let a `RuntimeException` or `IOException` just squeak by though the handler unnoticed.  Maybe it's fine, but I suspect this will lead to many applications going into a sort of zombie mode where they don't receive any more data but it's not clear as to why.  Perhaps we just need to add some documentation WRT exception handling?

**Comment by nmittler** [comment]
After doing some more investigation I realized that gRPC is already handling this, but only for the client side: https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/NettyClientHandler.java#L262

Unfortunately this isn't done for the server-side currently.  I'm working on a PR to address.

In the meantime, I think we can just close this issue.  Sorry for the noise.

**Comment by nitinlodhe** [comment]
Hi Team - I am facing similar issue - raised it under 
https://github.com/LogNet/grpc-spring-boot-starter/issues/42

Can you please guide me on this ?

**Comment by nitinlodhe** [comment]
I am using <version>1.3.0</version>
