### ISSUE TITLE
HttpRequestDecoder fires channelReadComplete on every network read

### ISSUE THREAD

**Issue by scf37** [netty/netty#4312]
Expected: HttpRequestDecoder  should  fire channelReadComplete event when last available HttpMessage have been consumed

Observed: channelReadComplete on every network packet received.

How to reproduce:

```
ch.pipeline().addLast(new HttpRequestDecoder());
ch.pipeline().addLast(new HttpResponseEncoder());
ch.pipeline().addLast(new MyChannelInboundHandler()); //overrides channelReadComplete 
```

When connected to such server using Windows telnet (IMPORTANT because it flushes on every keystroke), channelReadComplete fires on every keystroke instead of once - when I finish entering http request.

It seems that ByteToMessageDecoder blindly forwards channelReadComplete while handling channelRead correctly.

Netty 4.0.28.Final. Oracle JDK 1.8.0_60. Windows 10.

**Comment by scf37** [comment]
Some background: I'm using HttpRequestDecoder with AUTO_READ=false and need to know when to call ChannelContext.read()

**Comment by Scottmitch** [comment]
@scf37 - I'm not sure that `channelReadComplete` behaves like you are expecting.

See [ChanneHandler](https://github.com/netty/netty/blob/master/transport/src/main/java/io/netty/channel/ChannelHandler.java#L221):
```java
/**
 * Invoked when the last message read by the current read operation has been consumed by
 * {@link #channelRead(ChannelHandlerContext, Object)}.  If {@link ChannelOption#AUTO_READ} is off, no further
 * attempt to read an inbound data from the current {@link Channel} will be made until
 * {@link ChannelHandlerContext#read()} is called.
 */
void channelReadComplete(ChannelHandlerContext ctx) throws Exception;
```

`channelReadComplete()` is not designed to signify any specific protocol event, but instead notifies you that no more reads will be performed on a particular channel before returning back to the event loop.  In your case a "complete http request" will be signified by an object of type [LastHttpContent](https://github.com/netty/netty/blob/master/codec-http/src/main/java/io/netty/handler/codec/http/LastHttpContent.java).

In general you can not control how your peers will write nor how bytes will arrive at your application. `autoRead=false` is a way to give your application more control as to when reads are done on the socket. So if you are expecting more data to come (and your application can handle more data) then you are responsible for invoking `Channel.read()` at your discretion.

**Comment by scf37** [comment]
I'm not talking about LastHttpContent. Imagine I'm receiving long POST body. which can contain many HttpContent-s. I override channelRead and process every message asynchronously to do not interfere with Netty thread. When there is no more messages to read, I call channelContext.read().

Problem here is I can't find out when "no more messages to read" occurs! HttpRequestDecoder can parse single network packet into multiple messages, so when channelRead is invoked by Netty, I need to know if there are more messages pending in memory or I should invoke read().

> notifies you that no more *reads* will be performed on a particular channel before returning back to the event loop.

Question here is what a 'read' here? Read bytes from network or read messages from previous handler? I assume second.

Kinda pseudo code:

    void channelRead(ChannelHandlerContext ctx, Object msg) {
        myExecutor.addMessage(ctx, (HttpObject) msg);
    }

    //invoked from non-Netty thread, so can block if needed
    void processMessageAsync(ChannelHandlerContext ctx, HttpObject msg) {
        doBlockingProcessing(msg);
        //to be effective on memory, I do not want to call read() if there are pending messages in previous handler
        //Original idea was to set this flag in channelReadComplete but currently channelReadComplete is triggered on network read!
        //In practice this means channelReadComplete will NOT be triggered after channelRead... 
        if (thereAreNoMoreMessagesToRead) {
            ctx.read();    
            thereAreNoMoreMessagesToRead = false
        }
    }

**Comment by Scottmitch** [comment]
> I need to know if there are more messages pending in memory or I should invoke read().

Maybe you can explain where you feel messages are pending in memory?  `if there are pending messages in previous handler` do you have other handlers in the pipeline that do aggregation, or are you experiencing difficulties because your application is multi-threaded?

`HttpRequestDecoder`'s job is to take network data and translate this into `HttpMessage` or `HttpContent` objects. It should not be holding on to memory any longer than is necessary to parse these objects.

See the javadocs for [Channel.read()](https://github.com/netty/netty/blob/master/transport/src/main/java/io/netty/channel/Channel.java#L432).  You calling `Channel.read()` basically requests from the event loop mechanism to be woken up when there data pending to be read (on the underlying transport), and does not do a read operation immediately.

> Question here is what a 'read' here? Read bytes from network or read messages from previous handler? I assume second.

Read from the underlying transport (network, pipe, fd, etc...).  What do you mean `read messages from previous handler`?

> //Original idea was to set this flag in channelReadComplete but currently channelReadComplete is triggered on network read!
    //In practice this means channelReadComplete will NOT be triggered after channelRead...

Can you explain why you feel `channelReadComplete` will not be called after `channelRead`? The general sequence of events when the event loop is woken up because it has been notified there is data to read for a particular channel is:

1. Read from transport (1 or more times).
2. Call channelReadComplete.

**Comment by scf37** [comment]
1. Pending messages.

Code from ByteToMessageDecoder.channelRead

    for (int i = 0; i < size; i ++) {
        ctx.fireChannelRead(out.get(i));
    }

I.e. if single incoming `ByteBuf` have been decoded into multiple messages, they will be kept until fed to downstream handler. Thanks, I understand now :-) I can safely invoke read() on every invocation of channelRead in downstream handler - actual read operation will not occur until ByteToMessageDecoder.channelRead finishes his work. Thus, no new messages added until already generated ones is processed.

That does not solve "I want to invoke read() only once" question but seems to be acceptable.

2. `channelReadComplete` semantics

I am assuming that "after channelReadComplete event will be no channelRead events until user calls channelContext.read()". Is that true?

For handler attached after `HttpRequestDecoder`, channelReadComplete can be called excessively:

- channelReadComplete //we received part of http request header
- channelReadComplete //we received another part of http request 
- channelRead                //we received last part of http request. `HttpRequestDecoder` combined those 3 parts and invoked channelRead()
- channelReadComplete //readComplete for that last part.

To me, first two readComplete-s are confusing. I'm working with HttpObject-s and readComplete events from messages I do not receive (`HttpRequestDecoder` does not pass them downstream) mess my logic.

**Comment by Scottmitch** [comment]
> I am assuming that "after channelReadComplete event will be no channelRead events until user calls channelContext.read()". Is that true?

If autoRead is false this is generally true.

> To me, first two readComplete-s are confusing.

Understood. Hense https://github.com/netty/netty/issues/4312#issuecomment-145315165.  Are you suggesting changing behavior of [ByteToMessageDecoder.channelReadComplete](https://github.com/netty/netty/blob/master/codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java#L285) such that `channelReadComplete` is only propagated if messages were decoded? I would need to think if that would have any negative consequences... @normanmaurer WDYT?

**Comment by Scottmitch** [comment]
@normanmaurer - Ping. IIRC you made some changes to `channelReadComplete` in one of the generic handlers ... is this still applicable?

**Comment by trustin** [comment]
IIRC, channelReadComplete() was propagated regardless whether a decoder triggered channelRead() or not because there's no good place for a user handler to call ctx.read() when only a partial message has been received. Looking from the current ByteToMessageDecoder.channelReadComplete(), it seems to call ctx.read() automatically when autoRead is off, so there's no reason to propagate channelReadComplete() when the decoder did not trigger channelRead(). (The old ByteToMessageDecoder.channelReadComplete() did not call ctx.read() automatically.)

**Comment by trustin** [comment]
So.. I'd say it's a cruft from the past.

**Comment by normanmaurer** [comment]
@trustin @Scottmitch yep.. Let me fix this

**Comment by normanmaurer** [comment]
@scf37 please check https://github.com/netty/netty/pull/6856

**Comment by scf37** [comment]
Hi guys, unfortunately so much time have passed I don't really understand changes and tests.

Initial issue was to make `channelReadComplete` under HttpRequestDecoder to behave according to javadoc:
`Invoked when the last message read by the current read operation has been consumed by channelRead` 

Example:
- calling read(), upstream TCP handler reads byte array containing http request and part of http body
- channelRead(HttpRequest)
- channelRead(HttpContent)
- channelReadComplete()  //read byte array exhausted
- call read() again
- channelRead(HttpContent)
- channelRead(LastHttpContent)
- either channelRead(HttpRequest) or channelReadComplete()

**Comment by normanmaurer** [comment]
I think we fixed this earlier this year ... Let me close it. Please re-open if you still think there is an issue
