### ISSUE TITLE
ByteBufUtil.writeUtf8 and WrappedByteBuf

### ISSUE THREAD

**Issue by scf37** [netty/netty#4313]
There is interesting comment:

    // Maybe we could also check if we can unwrap() to access the wrapped buffer which
    // may be an AbstractByteBuf. But this may be overkill so let us keep it simple for now.

But - simple HTTP server under load (like 5k req/sec) uses 38% time on String.getBytes. I use ByteBufUtil.writeUtf8 to write HTTP response (about 10Kb).

Please consider adding that check. Additional instanceof is cheap those days and do matter in some cases.

Well, I can try ByteBuf.unwrap() to get to AbstractByteBuf but is that safe?

Netty 4.0.32.Final, ResourceLeakDetector is on SIMPLE.

**Comment by normanmaurer** [comment]
Will check

**Comment by normanmaurer** [comment]
@scf37 can you show me your code and how this change would help you ?

**Comment by scf37** [comment]
Code is qute complex, but profiling via jmc states that `writeUtf8` is the bottleneck.

How 20-30% improved performance would help me? Good question. Not even sure what to answer. May be I should stick with unwrap() hack, at least it is fast.

    override def read(): Future[HttpContent] = {
      //reading by blocks of default socket buffer size
      val len = str.length
      
      if (readDone) {
        throw new IllegalStateException("Response.read() after EOF")
      }

      val size = Math.min(len - off, 65536)

      //netty internals use size * 3 to ensure buffer for utf-8 strings.
      //Set it as expected to avoid later resizing
      val buf = PooledByteBufAllocator.DEFAULT.ioBuffer(size * 3)
      
      //ByteBufUtil.writeUtf8 has fast path for WrappedByteBuf
      //unfortunately resource leak detector wraps it in WrappedByteBuf which is not detected
      //by writeUtf8
      //so, trying to unwraaaaap
      //see https://github.com/netty/netty/issues/4313
      val fastBuf = buf match {
        case buf: AbstractByteBuf => buf
        case buf if buf.unwrap().isInstanceOf[AbstractByteBuf] => buf.unwrap()
        case buf => buf
      }
      
      if (off == 0 && size == len) {
        ByteBufUtil.writeUtf8(fastBuf, str)
      } else {
        ByteBufUtil.writeUtf8(fastBuf, new CharSequenceView(str, off, size))
      }
      
      off += size
      
      if (off == len) {
        readDone = true
        Future successful new DefaultLastHttpContent(buf)
      } else {
        Future successful new DefaultHttpContent(buf)
      }
    }

**Comment by normanmaurer** [comment]
@scf37 ah got it! May I ask what  level for the leak detector you use ?

**Comment by scf37** [comment]
Default level. ResourceLeakDetector is on SIMPLE

**Comment by normanmaurer** [comment]
@scf37 thanks... working on a patch.

**Comment by normanmaurer** [comment]
@scf37 see #4345

**Comment by scf37** [comment]
@normanmaurer Assuming you are asking me to review. Done.

**Comment by normanmaurer** [comment]
@scf37 replied to your comments
