### ISSUE TITLE
Add DefaultHttpMessage constructor that takes a HttpHeaders instance

### ISSUE THREAD

**Issue by slandelle** [netty/netty#4315]
Netty version: 4.0.32.Final

Context:
In AHC, we have our own builder for requests, where we internally store headers into a `HttpHeaders` instance.

Sadly, there's no way to directly pass a `HttpHeaders` instance to `DefaultHttpMessage` hierarchy and we have to set our instance into the `DefaultHttpMessage`'s internal one that's been eagerly created.

This results is an excessive allocation that could be avoided.

Please let me know if you're interested in a PR, and which branch to target.

Regards

**Comment by normanmaurer** [comment]
If you can make it with breakage use 4.0

**Comment by slandelle** [comment]
Will do :)

**Comment by Scottmitch** [comment]
> If you can make it with breakage use 4.0

Just to clarify ... If you can make it **without** breaking use 4.0. @normanmaurer ?

**Comment by normanmaurer** [comment]
lol.. yes. Fat fingers :D

**Comment by slandelle** [comment]
Yeah, that made me smile, but I got it right, no worries ;-)

**Comment by normanmaurer** [comment]
@slandelle ping :)

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4639
