### ISSUE TITLE
EmbeddedChannel does not fireInactive when closing

### ISSUE THREAD

**Issue by nmittler** [netty/netty#4316]
`AbstractChannel` will `fireChannelInactive` when closed: https://github.com/netty/netty/blob/master/transport/src/main/java/io/netty/channel/AbstractChannel.java#L662.

However, this is not done for the `EmbeddedChannel`, so pipelines using `EmbeddedChannel` will not behave the same way as with other channels.

@Scottmitch @normanmaurer WDYT?

**Comment by ninja-** [comment]
is it because closeExecutor is null for EmbeddedChannel...

**Comment by normanmaurer** [comment]
@nmittler... yes its a bug. working on it, stay tuned.

**Comment by normanmaurer** [comment]
@ninja- and no its not because of closeExecutor is null.

**Comment by Scottmitch** [comment]
@normanmaurer - Thanks for taking this one!
