### ISSUE TITLE
Epoll level-triggered discards last packets when remote end disconnects

### ISSUE THREAD

**Issue by ninja-** [netty/netty#4317]
This is a regression that doesn't happen when the default edge-triggered mode is used.

Assigned for investigation: @normanmaurer

**Comment by Scottmitch** [comment]
@ninja- - What version of netty?

Are any exceptions being fired in the pipeline? Can you include the stack traces if so?

**Comment by ninja-** [comment]
netty 4.1 and no exceptions fired. as the remote end sends the last "kick" packet and closes the connection, the kick packet isn't received before channelInactive is fired.

**Comment by normanmaurer** [comment]
Thanks will investigate...

**Comment by ninja-** [comment]
#3709 related or not?

**Comment by ninja-** [comment]
ok @normanmaurer I have a fix. I'll paste the patch now and maybe PR later.

**Comment by ninja-** [comment]
```java
        /**
         * Called once EPOLLRDHUP event is ready to be processed
         */
        final void epollRdHupReady() {
            System.out.println("rd hup active= "+isActive());
            if (isActive()) {
                // If it is still active, we need to call epollInReady as otherwise we may miss to
                // read pending data from the underlying file descriptor.
                // See https://github.com/netty/netty/issues/3709
                epollInReady();

                // Clear the EPOLLRDHUP flag to prevent continuously getting woken up on this event.
                clearEpollRdHup();

                // we aren't shutting down the stream now, because according to epoll documentation
                // calling read(...) now is not guaranteed to return ALL the pending data
                // and we should wait with shutting down until th next read(...) returns 0
                // (that will be done by epollInReady() whenever called)

                // otherwise we might miss the last data when operating in LEVEL TRIGGERED MODE
            }
        }

```

**Comment by ninja-** [comment]
@RemyLebeau it does. I have an application which used to check for RDHUP and IN in that order. It had the bug that if the peer sends something (such as a termination reason) and immediately closes, my app was not receiving that data because it checked for RDHUP first and killed the connection. From what I've seen, this happens when both endpoints are on the same machine, not sure it happens on different machines. –  haelix Nov 7 '14 at 8:14
1	 	
@haelix I am looking at this right now, and can confirm this. A fast write/close on localhost will result in 0x2001 (RDHUP|IN), but with data in the pipe, and read returning first the data, then zero. Also for example a SIGPIPE will result in 0x2019 (RDHUP|HUP|ERR|IN) with a read returning zero. In this edge case you could skip the read and just act on the RDHUP, but in the case above you prob want the data sent, which in my mind makes RDHUP pretty useless since you anyway need to handle this when reading. –  Fredrik Widlund May 31 at 12:40
add a comment

**Comment by Scottmitch** [comment]
@ninja- - What is the value of `isActive()` in `epollRdHupReady()` where you have the print statement?

**Comment by ninja-** [comment]
AS I mentioned earlier its active in every case

**Comment by ninja-** [comment]
BTW it seems correct on 5.0

**Comment by ninja-** [comment]
Git blame goes tohttps://github.com/netty/netty/commit/d2683c391149332733017aed2aece6ff6de7c4f6 @Scottmitch

**Comment by Scottmitch** [comment]
@ninja- - Humm I'm surprised you don't see the issue on 5.0...code is largely the same.  Do you mean you ran with 5.0 and did not observe the issue?

> Git blame goes to d2683c3 @Scottmitch

I the problem you are experiencing pre-dates this commit....code paths and timing may just mask it. Have you verified you do not observe the issue before this commit?

**Comment by Scottmitch** [comment]
@ninja- 

> AS I mentioned earlier its active in every case

Thanks for providing explanation. Looks like you updated your messages after initial post?  Explanation was not initially present in my browser.

**Comment by ninja-** [comment]
> Git blame goes to d2683c3 @Scottmitch
I the problem you are experiencing pre-dates this commit....code paths and timing may just mask it. Have you verified you do not observe the issue before this commit?

you just didn't pull your d2683c3 to master keeping it to 4.0 and 4.1 so that's an accident.
I didn't really test 5.0 but I am pretty sure the problem is workarounded by removing the shutdown() line added by this commit which would tell me that without this commit the problem wouldn't be there

**Comment by Scottmitch** [comment]
@ninja- - https://github.com/netty/netty/commit/bb3b637b70535e6741903521e9ed32b4243abb0e is the merge of https://github.com/netty/netty/commit/d2683c391149332733017aed2aece6ff6de7c4f6 to master. Were you looking before this commit?

**Comment by ninja-** [comment]
@Scottmitch oh, I missed it. Nevermind that comments yet. Every branch would be correct now with your recent fixes.

**Comment by Scottmitch** [comment]
@ninja- - No problem. Thanks for clarifying.

**Comment by ninja-** [comment]
@Scottmitch why it isn't in 4.1?

**Comment by ninja-** [comment]
maybe you should remove that shutdownInput() like I did in first version ?

**Comment by normanmaurer** [comment]
@ninja- so you say it is still not working for you ?

**Comment by ninja-** [comment]
@normanmaurer works most of the tikme now, but still a 5-10% chance. I blame the shutdownInput() which wasn't in my original patch.

**Comment by Scottmitch** [comment]
@ninja- - Can you try to reproduce with https://github.com/netty/netty/pull/4336? If you could describe what the state looks like in `AbstractEpollChannel.epollRdHupReady` that would be much appreciated.

Some of the things of interest:
- value of `isActive()`
- (assuming `isActive()` is true) how does the `epolInReady()` loop terminate? This will depend upon what type of Channel you are using. However an example is in [AbstractEpollStreamChannel](https://github.com/netty/netty/blob/master/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java#L801). I would be interested on the last read ... if read returns an error, or the amount requested to read is read, or if we tried to read more data than was available.
- Do you enable `ChannelOption.ALLOW_HALF_CLOSURE`?

**Comment by ninja-** [comment]
I was about to remind you about this :D
the case you left me with is hard to test to see if properly fixed but I doubt anything at #4336 could change it. do you have anything against removing that shutdownInput @ RDHUP so it would work as my original version did? 99% that's it

**Comment by Scottmitch** [comment]
@ninja- - Yes I would like to check with the "newest" code just to remove any doubt.

Can you explain why you think removing the [shutdownInput](https://github.com/netty/netty/blob/master/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollChannel.java#L360) call is correct?  We are assuming that once we get notified of `EPOLLRDHUP` that the data queued in the OS buffers is all we will ever receive, and force 1 more read loop to read all of this data. We achieve this by calling [recvBufAllocHandle().receivedRdHup()](https://github.com/netty/netty/blob/master/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollChannel.java#L347) which ensures when [epollInReady()](https://github.com/netty/netty/blob/master/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollChannel.java#L353) will read until an error is received.

**Comment by ninja-** [comment]
> We are assuming that once we get notified of EPOLLRDHUP that the data queued in the OS buffers is all we will ever receive, and force 1 more read loop to read all of this data. 

that isn't always true in some scenarios that can cause the issue...mostly on localhost

**Comment by ninja-** [comment]
here's the "spec"

> A socket listening for epoll events will typically receive an EPOLLRDHUP (in addition to EPOLLIN) event flag upon the remote peer calling close or shutdown(SHUT_WR). This does not neccessarily mean the socket is dead. Subsequent calls to recv() will return any unread data on the socket and eventually “0” will be returned to indicate EOF. It may even be possible to send data back if the remote peer only did a half-close of its socket.

are you sure it breaks only when 0 is returned and not -1? is it even possible to detect when using splice...?

**Comment by ninja-** [comment]
I think that even without shutdownInput() it's 100% guaranteed to close when next EPOLLIN triggers.

**Comment by Scottmitch** [comment]
Can you provide a reproducer in which EPOLLRDHUP is triggered, and then at some later point EPOLLIN triggers?  It seems like the definition of EPOLLRDHUP is that the peer has shutdown their write end of the socket, and thus will not be writing any more data.

http://man7.org/linux/man-pages/man2/epoll_ctl.2.html:
>  EPOLLRDHUP (since Linux 2.6.17)
              Stream socket peer closed connection, or shut down writing
              half of connection.  (This flag is especially useful for
              writing simple code to detect peer shutdown when using Edge
              Triggered monitoring.)

> are you sure it breaks only when 0 is returned and not -1

We break for 0 or -1. However can you point out what error numbers can occur in this situation, and we can still expect to read data at some later point?

**Comment by ninja-** [comment]
so @Scottmitch  how about we get back to the first case without your changes(when I fixed it just by getting rid of shutdownInput) and from that point I am going to debug you the epoll events and "read" return values. this version was easy to trigger(90%)

**Comment by Scottmitch** [comment]
@ninja- - If you think this will helpful, although I'm more interested in the conditions that make https://github.com/netty/netty/pull/4325 not work.

**Comment by Scottmitch** [comment]
@ninja- - Any updates? Were your comments on the commit included in #4336 holding you up from trying to reproduce...if so sry they are fixed now :)

**Comment by ninja-** [comment]
this has been properly fixed since...you can remove the milestone, @normanmaurer

**Comment by Scottmitch** [comment]
@ninja- - Thanks for confirming the issue has been resolved!
