### ISSUE TITLE
A number of toString() methods on classes that implement ByteBufHolder can throw IllegalReferenceCountException

### ISSUE THREAD

**Issue by jroper** [netty/netty#4327]
Two examples that I've found include `WebSocketFrame.toString()` and `DefaultByteBufHolder.toString()`.  `toString()` implementations should always try to avoid throwing exceptions, since they're used for things like creating exception messages and arbitrary logging of inputs/outputs.  Consequently, if `toString()` does throw an exception, this will often hide another real problem, a typical example would be:

```java
TextWebSocketFrame frame = ...
try {
  String text = frame.text();
  ReferenceCountUtil.release(frame);
  doSomeProcessing(text);
} catch (Exception e) {
  log.error("Error processing frame: " + frame, e);
}
```

In this example, if `doSomeProcessing` throws an exception, the exception will be caught, but not logged, instead, when `frame.toString()` is invoked, that will throw an `IllegalReferenceCountException`.

I don't think there's any need to guard access to `ByteBuf.toString()`, since it likewise shouldn't throw an exception for the same reasons as above, so `ByteBufHolder` `toString()` implementations should just invoke that directly without going through any reference count checks.

**Comment by normanmaurer** [comment]
@jroper sounds like a bug... let me fix it.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4341
