### ISSUE TITLE
Suggestion to support Content Type parsing in HttpHeaders

### ISSUE THREAD

**Issue by Spikhalskiy** [netty/netty#4331]
HttpHeaders already has specific methods for such popular and simple headers like "Host", but if I need to convert POST raw body to string I need to parse complex [ContentType](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.17) header in my code.

Would be great to add two methods to HttpHeaders class to parse values from content-type header of message
```
<SomeWrapperForMimeType> HttpHeaders#getMIMETypeValue(HttpMessage message)
Charset HttpHeaders#getCharsetValue(HttpMessage message)
```

**Comment by normanmaurer** [comment]
We love contributions. What about submitting a PR?

**Comment by Spikhalskiy** [comment]
@normanmaurer yep, if you confirm that it would be good to have this in netty and it's not implemented yet, I will prepare PR in a week or two.

**Comment by Spikhalskiy** [comment]
Will prepare method to parse mime-type too in separate pull request. So, let's still leave it opened.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4894
