### ISSUE TITLE
Make buffer module stand-alone

### ISSUE THREAD

**Issue by nmittler** [netty/netty#4332]
Many other projects might benefit from the buffer API in Netty.  To better enable this, the buffer module should be made as lightweight as possible, preferably stand-alone.

We'll need to investigate whether this is feasible and what would need to change in order to facilitate the change.

@normanmaurer @Scottmitch  FYI

**Comment by NiteshKant** [comment]
:+1: Although I thought it is standalone (no deps)

**Comment by ninja-** [comment]
as long as "no deps" equals "depends on netty-internal" I think it's a realistic goal

**Comment by nmittler** [comment]
Just looked at the size of buffer and common modules ... they total nearly 1MB (355,607B, and 580,552B respectively as of 4.0.1.Beta7).  It's probably worth breaking things down a bit so that other projects can depend only on the parts they need.  One obvious way to start down this path would be to define a `buffer-api` module.  I'll start putting some thought into this.

**Comment by nmittler** [comment]
Not sure this is really worth doing ATM ... closing for now.

**Comment by normanmaurer** [comment]
+1
