### ISSUE TITLE
DefaultAttributeMap unexpected behavior

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4351]
The relationship between [DefaultAttributeMap](https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/DefaultAttributeMap.java#L28) and [DefaultAttributeMap.Attribute](https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/DefaultAttributeMap.java#L142) is such that methods on the `DefaultAttributeMap.Attribute` can impact their presence in the `DefaultAttributeMap` that contains them (see [remove0](https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/DefaultAttributeMap.java#L199)).

However there is no mechanism for `DefaultAttributeMap.Attribute` to re-insert itself back into the `DefaultAttributeMap`. This may create unexpected behavior in the following sequence:

Thread 1 -> x = map.attr(key)
Thread 2 -> y = map.attr(key)
Thread 1 -> x.remove();
Thread 2 -> a = y.getAndSet(value);
Thread 3 -> z = map.attr(key); /* Currently `z.get() == null`, but it maybe expected for `z` to represent the value `a` */

Should the `*set*` methods in `DefaultAttributeMap.Attribute` take into consideration if they have been removed, and re-insert themselves?

**Comment by Scottmitch** [comment]
@normanmaurer - WDYT?

**Comment by normanmaurer** [comment]
@Scottmitch I think the current behaviour is correct. Once you remove an Attribute it is expected that even if you call set on the Attribute it will not be in the map again.

**Comment by Scottmitch** [comment]
@normanmaurer - Seems like strange behavior that only some methods of [Attribute](https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/Attribute.java) would modify the state of the map ... but it is documented in the javadocs. Do you feel having some sort of disclaimer is necessary to call out the discrepancy of behavior w.r.t to modifying the map that contains the Attribute?

**Comment by normanmaurer** [comment]
@Scottmitch with some methods you are talking about "remove()" here ?

**Comment by Scottmitch** [comment]
@normanmaurer - Yes I was referring to `remove()` and `getAndRemove()`. These methods already document the map will be modified...the unexpected part is the setter methods don't reciprocate this behavior. The disclaimer would be something along the lines of (on each setter method):

```java
/**
 * This method will not modify the state of the {@link AttributeMap}. If this object has been removed 
 * from the {@link AttributeMap} this method will not attempt to update the {@link AttributeMap}'s value
 * for the key corresponding to this object.
 */

**Comment by normanmaurer** [comment]
I think we can close this now with the javadoc updates
