### ISSUE TITLE
Sending a large FileRegion breaks the WriteTimeoutHandler

### ISSUE THREAD

**Issue by andrelanka** [netty/netty#4353]
Sending a big file with only one FileRegion triggers only one write in the pipeline. That breaks the WriteTimeoutHandler that was added to the pipeline. 

Affected version: 4.0.29.Final

Current behavior: It closes the channel, when the transfer takes longer than the handler's threshold.
Expected  behavior: It closes the channel,  when no data was written within a certain period of time.

In case that it's impossible for you to see when data is written and when not, a remark in the JavaDoc will be great.

**Comment by normanmaurer** [comment]
Fixed
