### ISSUE TITLE
DefaultMessageSizeEstimator gives '0'  for FileRegion

### ISSUE THREAD

**Issue by andrelanka** [netty/netty#4354]
In the DefaultMessageSizeEstimator the size of a FileRegion message is estimated with 0. By this, the WriteBufferHighWaterMark has no effect, when sending a file chunk-wise using channel.writeAndFlush.

Chunk-wise sending of the file is mandatory for us: Sending the file using a single FileRegion doesn't work in combination with a WriteTimeoutHandler because of issue #4353.

Affected version: 4.0.29.Final

Current behavior: The message size is estimated with 0, so the number of pending bytes in the channel's OutputBuffer is not increased. So the buffer's 'bytesBeforeUnwritable' is always identical to  channel.config().getWriteBufferHighWaterMark(). By this it's impossible to reach the set WriteBufferHighWaterMark.

Expected behavior: Add the size of the given FileRegion correctly to the number of pending bytes and decrease it after it's actually written.

**Comment by normanmaurer** [comment]
@andrelanka actually this works like it should. The pending bytes should only be adjusted for stuff that is hold in memory. FileRegion is expected to be not in memory so it makes no sense to increase these.
