### ISSUE TITLE
OpenSslServerContext reinitializes the provided TrustManagerFactory with the key cert chain.

### ISSUE THREAD

**Issue by freels** [netty/netty#4355]
AFAICT, this is incorrect behavior, as the provided trust manager factory should already be initialized.

**Comment by normanmaurer** [comment]
@freels hmmm... s you would argue that either the user provides a full initialised TrustManagerFactory and not certs or none and the certs ?

**Comment by freels** [comment]
Yes. This would match the behavior of JdkSslServerContext as well.

In my case, I am trying to provide a trust manager initialized with a root CA cert that a server context will use to validate client certs. However, because OpenSslServerContext reinitializes the provided trust manager w/ the server's cert, it drops the root cert and trusts only its own server cert.

**Comment by freels** [comment]
Also, if neither a trust manager or trusted cert are provided, I'm pretty sure it should be able to use a default trust manager (w/o the call to init) in order to use the system provided trust store. (I'm looking at https://github.com/netty/netty/blob/4.0/handler/src/main/java/io/netty/handler/ssl/OpenSslServerContext.java#L370-L380 )

**Comment by normanmaurer** [comment]
Alright... Looking or if you like you could also do a pr ;) ?

**Comment by freels** [comment]
I'd be happy to provide a PR sometime in the next few days... just wanted to make sure this was something to fix before spending more time on it. :)

**Comment by normanmaurer** [comment]
If it is how it is done in Jdk one yes :)

**Comment by normanmaurer** [comment]
@freels nevermind... working on a fix, stay tuned :)

**Comment by freels** [comment]
Awesome, thanks!

**Comment by normanmaurer** [comment]
@freels please check https://github.com/netty/netty/pull/4387
