### ISSUE TITLE
Unpooled CompositeByteBufs log leak detection errors

### ISSUE THREAD

**Issue by freels** [netty/netty#4356]
If you create a CompositeByteBuf via Unpooled.wrappedBuffer(buffers...) or via Unpooled.compositeBuffer that itself wraps unpooled buffers, the resulting buffer will log a leak error on GC.

This seems like incorrect behavior...I'd expect only pooled buffers within a CompositeByteBuf or a CompositeByteBuf created via a pooled allocator to log leak errors.

**Comment by ninja-** [comment]
Unpooled != not reference counted

**Comment by freels** [comment]
Regardless of how many unpooled bytebufs "leak", the error is never logged, only with unpooled composite bytebufs. So either all unpooled bytebufs should warn, or unpooled composite bytebufs should not.

**Comment by normanmaurer** [comment]
Will look into it.

**Comment by normanmaurer** [comment]
Just checked and this was fixed already. Please reopen if you still see the problem

**Comment by freels** [comment]
Thanks, will do.
