### ISSUE TITLE
Assertion error in globalEventExecutor

### ISSUE THREAD

**Issue by luengnat** [netty/netty#4357]
I am using Vertx 3.1 with Netty 4.0.31. Every once in a while, I got an assert on this line:

     protected final Runnable pollScheduledTask(long nanoTime) {
        assert this.inEventLoop();

        Queue scheduledTaskQueue = this.scheduledTaskQueue;
        ScheduledFutureTask scheduledTask = scheduledTaskQueue == null?null:(ScheduledFutureTask)scheduledTaskQueue.peek();
        if(scheduledTask == null) {
            return null;
        } else if(scheduledTask.deadlineNanos() <= nanoTime) {
            scheduledTaskQueue.remove();
            return scheduledTask;
        } else {
            return null;
        }
    }

with the following stack trace:
"globalEventExecutor-1-1"@4,148 in group "main": RUNNING
pollScheduledTask():83, AbstractScheduledEventExecutor {io.netty.util.concurrent}
fetchFromScheduledTaskQueue():114, GlobalEventExecutor {io.netty.util.concurrent}
takeTask():99, GlobalEventExecutor {io.netty.util.concurrent}
run():230, GlobalEventExecutor$TaskRunner {io.netty.util.concurrent}
run():137, DefaultThreadFactory$DefaultRunnableDecorator {io.netty.util.concurrent}
run():745, Thread {java.lang} 

The thread that starts GlobalEventExecutor is
"main"@1 in group "main": RUNNING
<clinit>():37, GlobalEventExecutor {io.netty.util.concurrent}
<init>():35, MultithreadEventExecutorGroup {io.netty.util.concurrent}
<init>():49, MultithreadEventLoopGroup {io.netty.channel}
<init>():61, NioEventLoopGroup {io.netty.channel.nio}
<init>():52, NioEventLoopGroup {io.netty.channel.nio}
<init>():125, VertxImpl {io.vertx.core.impl}
<init>():114, VertxImpl {io.vertx.core.impl}
<init>():110, VertxImpl {io.vertx.core.impl}
vertx():34, VertxFactoryImpl {io.vertx.core.impl}
vertx():78, Vertx {io.vertx.core}

**Comment by normanmaurer** [comment]
Will check

**Comment by normanmaurer** [comment]
@luengnat ok I think i know where the problem is... working on a fix now :+1:

**Comment by normanmaurer** [comment]
Fixed

**Comment by tolbertam** [comment]
Oddly I started encountering this issue while upgrading from jdk 8u60 to 8u65.  Not really sure why that would explain this.  I was just curious @luengnat do you happen to remember what JDK you were on when you were encountering this?    We've been on 4.0.26/4.0.27 for about 6 months or and I hadn't seen this issue once until we recently upgraded JDKs in our CI environment and it seems to happen occasionally.
