### ISSUE TITLE
DefaultMessageSizeEstimator should have a default unknown size of 1

### ISSUE THREAD

**Issue by prange** [netty/netty#4363]
A size of 1 would prevent the task queue of the  eventLoop in the client from growing indefinitely in cases where the client is producing data faster than when the server can consume them.

**Comment by normanmaurer** [comment]
@prange that is actually a very good idea! Let me do a PR or you want to do it ?

**Comment by prange** [comment]
@normanmaurer If you could do that it would be great.

**Comment by normanmaurer** [comment]
Will do...
