### ISSUE TITLE
FixedChannelPool race condition when closed during acquire

### ISSUE THREAD

**Issue by stau** [netty/netty#4373]
An AssertionError is thrown when FixedChannelPool is being closed, while somewhere at the same time an acquire occurs. 
The acquire triggers FixedChannelPool::decrementAndRunTaskQueue(), while FixedChannelPool::close() sets                 acquiredChannelCount = 0;

This only happens when objects using the pool are not terminated prior to calling close.

**Comment by Scottmitch** [comment]
@normanmaurer - Can you take a look?

**Comment by fratboy** [comment]
@stau Can you show me the test code you made? 
I suspect `AssertionError` occurs when `FixedChannelPool::decrementAndRunTaskQueue()` is called after `FixedChannelPool::close()`.

**Comment by stau** [comment]
Yes, this occurs when an acquired Channel is released after the FixedChannelPool has been closed: 
```Java
        // set up Bootstrap etc
        ... 
        FixedChannelPool pool = new FixedChannelPool(b, handler, maxConnections);
        final Future<Channel> acquire = pool.acquire();
        final Channel channel = acquire.get();
        pool.close();
        pool.release(channel);
```

**Comment by normanmaurer** [comment]
@fratboy @stau I think in this case we may want to just close the Channel ?

**Comment by stau** [comment]
@normanmaurer By closing subsequent Channels, would it mean that the FixedChannelPool will remain in the "closed" state forever? The current implementation seems to be resetting the FixedChannelPool rather than closing it permanently.

**Comment by normanmaurer** [comment]
@stau yes it should stay closed forever

**Comment by fratboy** [comment]
@stau I think we should not call `pool.release(ch)` after call `pool.close()`. 
@normanmaurer  Is it better to set promise failed when a user call `pool.acquire` or `pool.release` after call `pool.close` ?

**Comment by stau** [comment]
@fratboy This shouldn't occur in normal circumstances, however when attempting to (best effort) clean up after an Exception, the pool may be closed before an acquired Channel is released. For example having a handler which releases a Channel after an operation is complete.

**Comment by normanmaurer** [comment]
@fratboy yeah failing the exception would be fine as well. Let me fix it.

**Comment by fratboy** [comment]
@normanmaurer =)

**Comment by normanmaurer** [comment]
@fratboy @stau should be fixed by https://github.com/netty/netty/pull/4389. Please check

**Comment by normanmaurer** [comment]
Fixed
