### ISSUE TITLE
Multi-threaded multi-channel EpollDatagramChannel memory leak

### ISSUE THREAD

**Issue by hnrkp** [netty/netty#4375]
Trying to work around the issue in #1706 where NioDatagramChannel would only use one worker thread for all IO we ended up with something like this for our service that proxies data packets for an VPN-like service that we run. It's pretty simple, we bind to one external udp socket which will receive the data packets, decrypt them and throw them at another service at localhost which will push it to a tun/tap device and the kernel will then route that IP packet wherever. A packet received in the other direction will be received from the tun/tap driver to the internal port (the internalBootstrap) below.

The VpnDataPacketInboundHandler will do a writeAndFlush() on the channel for the externalBootstrap. Since it's UDP and we keep track of the sessions and where the packets are supposed to go, the theory is that the packets can be written to any channel and read on any channel, so as long as we keep track of the sessions on our own, this will work.

And it does work, with NIO and Epoll, until you start applying that workaround in #1706 to get multi threading. Then...memory starts to leak really really badly, but only when load testing it and throwing a few thousand packets per second at it. It seems the write of the packets are never done, and stopping the traffic doesn't help, the JVM is only stuck with trying to GC and is thrashing away, doing nothing, and looking at what's taking up all the heap is:

```
io.netty.util.Recycler$DefaultHandle 934965 29918880 30084480
io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask 934890 37395600 414083696
java.nio.DirectByteBuffer 930997 59583808 59583808
java.nio.DirectByteBuffer$Deallocator 930985 29791520 29791520
sun.misc.Cleaner 930985 37239400 67030920
io.netty.buffer.UnpooledUnsafeDirectByteBuf 930927 67026744 67026744
io.netty.channel.DefaultChannelPromise 930875 44682000 44682000
[....]vpn.VpnDataPacket 930699 29782368 141066936
io.netty.buffer.SlicedByteBuf 930699 44673552 111084912
```

So..tested different things and trying to understand if there's some fundamental trouble with Epoll. So I tested pushing the writeAndFlush call to another thread to just a normal java Executor, and then (as in the code below) nothing leaks, everything seems to work. Removing the executor call breaks everything. Allocating new VpnDataMessages to write them instead of retaining the old packet doesn't do much either.

And even more strange, if I don't use the executor workaround but do writeAndFlush(msg).await() then the first two epoll threads (and ALWAYS the first two, never any other thread!) will (after a few seconds) stop and hang, but the rest of the threads spawned will happily run along and everything will work and nothing seems to leak, but those two threads are stuck forever waiting for the promise to arrive.

So, I might be doing something wrong or misunderstanding how netty works internally in a datagram setting but I don't really see how the executor fix is explained as far as memory leaks are concerned, nor can I think of any reason why the two threads hang then everything works-fact is something that is to be expected..

```

 epollEventLoopGroup-2-1 [WAITING]
java.lang.Object.wait() Object.java:503
io.netty.util.concurrent.DefaultPromise.await() DefaultPromise.java:254
io.netty.channel.DefaultChannelPromise.await() DefaultChannelPromise.java:129
io.netty.channel.DefaultChannelPromise.await() DefaultChannelPromise.java:28
[...].vpn.VpnDataPacketHandler.channelRead0(ChannelHandlerContext, VpnDataPacket) VpnDataPacketHandler.java:27
[...].vpn.VpnDataPacketInboundHandler.channelRead0(ChannelHandlerContext, VpnDataPacket) VpnDataPacketInboundHandler.java:13
[...].vpn.VpnDataPacketInboundHandler.channelRead0(ChannelHandlerContext, Object) VpnDataPacketInboundHandler.java:5
io.netty.channel.SimpleChannelInboundHandler.channelRead(ChannelHandlerContext, Object) SimpleChannelInboundHandler.java:105
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Object) AbstractChannelHandlerContext.java:308
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Object) AbstractChannelHandlerContext.java:294
io.netty.channel.SimpleChannelInboundHandler.channelRead(ChannelHandlerContext, Object) SimpleChannelInboundHandler.java:108
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Object) AbstractChannelHandlerContext.java:308
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Object) AbstractChannelHandlerContext.java:294
io.netty.channel.SimpleChannelInboundHandler.channelRead(ChannelHandlerContext, Object) SimpleChannelInboundHandler.java:108
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Object) AbstractChannelHandlerContext.java:308
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Object) AbstractChannelHandlerContext.java:294
io.netty.channel.SimpleChannelInboundHandler.channelRead(ChannelHandlerContext, Object) SimpleChannelInboundHandler.java:108
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Object) AbstractChannelHandlerContext.java:308
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Object) AbstractChannelHandlerContext.java:294
io.netty.channel.SimpleChannelInboundHandler.channelRead(ChannelHandlerContext, Object) SimpleChannelInboundHandler.java:108
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Object) AbstractChannelHandlerContext.java:308
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Object) AbstractChannelHandlerContext.java:294
io.netty.handler.codec.MessageToMessageDecoder.channelRead(ChannelHandlerContext, Object) MessageToMessageDecoder.java:103
io.netty.handler.codec.MessageToMessageCodec.channelRead(ChannelHandlerContext, Object) MessageToMessageCodec.java:111
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Object) AbstractChannelHandlerContext.java:308
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Object) AbstractChannelHandlerContext.java:294
io.netty.handler.codec.MessageToMessageDecoder.channelRead(ChannelHandlerContext, Object) MessageToMessageDecoder.java:103
io.netty.handler.codec.MessageToMessageCodec.channelRead(ChannelHandlerContext, Object) MessageToMessageCodec.java:111
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Object) AbstractChannelHandlerContext.java:308
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Object) AbstractChannelHandlerContext.java:294
io.netty.channel.DefaultChannelPipeline.fireChannelRead(Object) DefaultChannelPipeline.java:846
io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady() EpollDatagramChannel.java:585
io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventArray, int) EpollEventLoop.java:346
io.netty.channel.epoll.EpollEventLoop.run() EpollEventLoop.java:254
io.netty.util.concurrent.SingleThreadEventExecutor$2.run() SingleThreadEventExecutor.java:112
io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run() DefaultThreadFactory.java:137
java.lang.Thread.run() Thread.java:745


 epollEventLoopGroup-2-2 [WAITING]
java.lang.Object.wait() Object.java:503
io.netty.util.concurrent.DefaultPromise.await() DefaultPromise.java:254
io.netty.channel.DefaultChannelPromise.await() DefaultChannelPromise.java:129
io.netty.channel.DefaultChannelPromise.await() DefaultChannelPromise.java:28
[...].vpn.VpnDataPacketHandler.channelRead0(ChannelHandlerContext, VpnDataPacket) VpnDataPacketHandler.java:27
[...].vpn.VpnDataPacketHandler.channelRead0(ChannelHandlerContext, Object) VpnDataPacketHandler.java:7
io.netty.channel.SimpleChannelInboundHandler.channelRead(ChannelHandlerContext, Object) SimpleChannelInboundHandler.java:105
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Object) AbstractChannelHandlerContext.java:308
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Object) AbstractChannelHandlerContext.java:294
io.netty.handler.codec.MessageToMessageDecoder.channelRead(ChannelHandlerContext, Object) MessageToMessageDecoder.java:103
io.netty.handler.codec.MessageToMessageCodec.channelRead(ChannelHandlerContext, Object) MessageToMessageCodec.java:111
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Object) AbstractChannelHandlerContext.java:308
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Object) AbstractChannelHandlerContext.java:294
io.netty.channel.DefaultChannelPipeline.fireChannelRead(Object) DefaultChannelPipeline.java:846
io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady() EpollDatagramChannel.java:585
io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventArray, int) EpollEventLoop.java:346
io.netty.channel.epoll.EpollEventLoop.run() EpollEventLoop.java:254
io.netty.util.concurrent.SingleThreadEventExecutor$2.run() SingleThreadEventExecutor.java:112
io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run() DefaultThreadFactory.java:137
java.lang.Thread.run() Thread.java:745

```

```java
	private Bootstrap getExternalBootstrap(InetSocketAddress externalBindAddr) {
		Bootstrap b = new Bootstrap();
		b.group(eventLoops)
		 .localAddress(externalBindAddr)
		 .channel(EpollDatagramChannel.class)
		 .option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
		 .option(ChannelOption.SO_RCVBUF, 65536)
 		 .option(ChannelOption.SO_SNDBUF, 65536)
 		 .option(EpollChannelOption.SO_REUSEPORT, true)
		 .handler(new ChannelInitializer<Channel>() {
			protected void initChannel(Channel ch) throws Exception {
				ch.pipeline().addLast(
						new DtlsHandler(tlsEngine),
						new ExternalVpnPacketCodec(sessionMgr),
						new VpnLoginRequestHandler(loginManager),
						new VpnChallengeReplyHandler(vpnParams, sessionMgr, loginManager, vapiExecutor),
						new VpnIPAssignReplyHandler(),
						new VpnKeepaliveHandler(),
						new VpnDataPacketInboundHandler()
						);
			}
		 });
        return b;
	}
	
	private Bootstrap getInternalBootstrap(InetSocketAddress internalBindAddr, final InetSocketAddress vpnPeerAddr) {
		Bootstrap b = new Bootstrap();
		b.group(eventLoops)
		 .localAddress(internalBindAddr)
		 .channel(EpollDatagramChannel.class)
		 .option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
		 .option(ChannelOption.SO_RCVBUF, 65536)
		 .option(ChannelOption.SO_SNDBUF, 65536)
		 .option(EpollChannelOption.SO_REUSEPORT, true)
		 .handler(new ChannelInitializer<Channel>() {
			protected void initChannel(Channel ch) throws Exception {
				ch.pipeline().addLast(
						new InternalVpnPacketCodec(sessionMgr, vpnPeerAddr),
						new VpnDataPacketHandler()
						);
			}
		});
        return b;
	}
```

```java
		for (int i = 0; i < workerThreads; ++i) {
			ChannelFuture extFuture = externalBootstrap.bind().await();
			Channel extChannel = extFuture.channel();

			if (!extFuture.isSuccess()) {
				throw new Exception();
			}
			
			ChannelFuture intFuture = internalBootstrap.bind().await();
			Channel intChannel = intFuture.channel();
			
			if (!intFuture.isSuccess()) {
				throw new Exception();
			}
	
			// Setup pipes
			VpnDataPacketHandler extVDPH = extChannel.pipeline().get(VpnDataPacketHandler.class);
			extVDPH.setForwardChannel(intChannel);
			
			VpnDataPacketHandler intVDPH = intChannel.pipeline().get(VpnDataPacketHandler.class);
			intVDPH.setForwardChannel(extChannel);
		}

```

VpnDataPacketHandler excerpt:

```java
public class VpnDataPacketHandler extends SimpleChannelInboundHandler<VpnDataPacket> {
	private static Logger logger = Logger.getLogger(VpnDataPacketHandler.class);

	private Channel forwardChannel;
	private Executor executor;

	@Override
	protected void channelRead0(ChannelHandlerContext ctx, final VpnDataPacket msg) throws Exception {
		if (forwardChannel != null) {
			//logger.debug("Incoming from " + msg.getSourceAddr() + " via " + msg.getSourceSocket());
			msg.retain();

			executor.execute(new Runnable() {
				@Override
				public void run() {
				
					if (forwardChannel.isWritable()) {
						forwardChannel.writeAndFlush(msg);
					}
					
				}
			});
		}
	}
	
```

4.0.32.Final
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)

Linux 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@hnrkp only had a very quick look but i think you forgot to release the message if the channel is not writable anymore:

```java
public class VpnDataPacketHandler extends SimpleChannelInboundHandler<VpnDataPacket> {
    private static Logger logger = Logger.getLogger(VpnDataPacketHandler.class);

    private Channel forwardChannel;
    private Executor executor;

    @Override
    protected void channelRead0(ChannelHandlerContext ctx, final VpnDataPacket msg) throws Exception {
        if (forwardChannel != null) {
            //logger.debug("Incoming from " + msg.getSourceAddr() + " via " + msg.getSourceSocket());
            msg.retain();

            executor.execute(new Runnable() {
                @Override
                public void run() {
                    if (forwardChannel.isWritable()) {
                        forwardChannel.writeAndFlush(msg);
                    } else {
                       msg.release();
                    }
                }
            });
        }
    }
```

**Comment by hnrkp** [comment]
Ah, old version of the code. It doesn't matter since isWritable() has never returned false unless I'm shutting the channel down, which I never do unless ctrl-c:ing the server, since it's UDP. Even with the else-release added, same behavior.

And large amount of never-released io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask objects also are still there, which I would not expect to see if it was only a simple "I forgot to release the buffer"-bug. Or at least that's how I think I understand the netty world. :)

**Comment by hnrkp** [comment]
@normanmaurer Is there anything in my setup that seems off? Using netty for datagram is usually a bit harder since most examples and discussion about how to optimize usually are targeted towards tcp and http, so I might have done something strange. But I still feel that it smells of a bug, that the AbstractChannelHandlerContext$WriteAndFlushTask seems to leak. The rest of the leaks I guess are explained by that object holding a reference to the buffer, preventing the rest to release.

**Comment by ninja-** [comment]
you shouldn't call msg.retain() there. get rid of it

**Comment by hnrkp** [comment]
@ninja- Well, I'll try to get around it but since the buffer will be written to another channel with another context netty will release the message after I return from that read0(), so either I clone it before writing it or I'll just add the retain() and it won't be released until written to the next channel. Thought we'd save a few allocations that way.

**Comment by hnrkp** [comment]
Ok, so I started to not use PooledByteBufAllocator and now the need for the external executor seems to be gone. And during the afternoon and countless times of watching the GC do nothing at all, I think I might start to consider the fact that since it requires some amount of memory allocation to write() to my handlers (DTLS encrypt/decrypt via JNI, don't ask, or maybe do..), once the app hits the sweet spot memory wise, it can never escape it, since it needs to free data to be able to write() but there's none to be freed because after a while of slow output (caused by GC contention), all available heap is used by enqueued events to the EventGroup.

I can't really see any way of preventing this issue except fixing the firewall not to accept more packets/sessions than the server is able to handle. I think netty 3 have something like a memory aware threadpool based executor, but I haven't found anything like it in netty 4. What's the recommended pattern for these sorts of use cases with netty 4? Because I can't be the only one having this problem..right?

**Comment by ninja-** [comment]
umm @hnrkp you are entirely on a bad track. just delete that .retain() and that's all

**Comment by hnrkp** [comment]
@ninja- No, it's needed since it's proxying that message to another channel and different handlers, and the refcount is decremented once I return from the MessageToMessageCodec.write(). So to retain that message for the next channel i need to .retain() it, right? Anyway, it works now and is running along happily with a few tens of thousands of simultaneous connections throwing quite the number of packets per seconds at it, with no increase in heap usage according to the profiler.

I don't think that this is a memory leak issue but an issue of queueing events that cannot be written by the EventLoopGroup fast enough, until there's no more memory available to finish the write(). But I haven't figured out how to work around that, yet.

**Comment by ninja-** [comment]
so I am telling you that autoread = false is what you want

**Comment by hnrkp** [comment]
@ninja- Yeah, I've looked into it but since the datagramchannel is only one channel for all your clients then it's a bit hard to decide when you should disable read and enable it again. If there was any way of detecting if the queues for the eventloopgroup(s) start to build, then it would be nice to be able to kill the reads for that channel until the queue situation looks a bit better. But I'm not familiar with any way of doing that, since it seems non trivial to measure the queue length of the EpollEventLoopGroup. Or maybe (most likely) I'm missing something.

**Comment by hnrkp** [comment]
I implemented some throttling of incoming traffic (which generates outbound traffic) by flipping autoread true and false in a not so pretty but very well functioning fashion. Since this is obviously not the bug I initially described I'll just close it. Thanks, everyone.
