### ISSUE TITLE
tcnative Windows build

### ISSUE THREAD

**Issue by Gadreel** [netty/netty#4376]
The tcnative page says:

"If you are on Windows, you have to:
Build APR by yourself (or get the 64-bit DLL from our CI server),"

But the link to the CI server fails every time, been trying every day for the last 4 days.  It would be very valuable to have the Windows 64 bit binary for those of us without much Windows functionality, but who have customers using Windows.  thanks!

**Comment by normanmaurer** [comment]
@Gadreel I think we not provide this anymore. You should just build APR yourself like explained here:

http://netty.io/wiki/forked-tomcat-native.html#wiki-h3-6
