### ISSUE TITLE
Make ChannelPool::close to accept Promise

### ISSUE THREAD

**Issue by fratboy** [netty/netty#4377]
Sometimes I have to wait until `ChannelPool::close` ends, but there is no way right now.
I think it would be useful if I can pass a `Promise` to `ChannelPool::close`.
@normanmaurer What do you think about it?

**Comment by normanmaurer** [comment]
@fratboy actually maybe ChannelPool::close should only return once it is done ?

**Comment by fratboy** [comment]
@normanmaurer It is but I think it would be better we can be notified when underlying channel closing is done.

**Comment by fratboy** [comment]
@normanmaurer I'll think about it again. Thanks.
