### ISSUE TITLE
Http2 StreamBufferingEncoder does not write data frame for client initialized streams

### ISSUE THREAD

**Issue by dustismo** [netty/netty#4379]
Using the http2 example in in netty 4.1.0.Beta7 (both the tiles example nor the helloworld example)

Steps to reproduce:
1. start helloworld server example
2. start helloworld client example
--> client shows headers received, but no data.  

more details:
Client issues get request with streamId 3
Response sent from server:
1. Headers are correctly sent via StreamBufferingEncoder#writeHeaders
          header writing is triggered on line 151 (canCreateStream())
2. Server attempts to send data frame 
    StreamBufferingEncoder#writeData
    line 190: if (isExistingStream(streamId))  returns false, and pendingStream is null so promise is fail and data is released.

The problem appears to be 

```java
private boolean isExistingStream(int streamId) {
        return streamId <= connection().local().lastStreamCreated();
    }
```
where lastStreamCreated is always 0. 
 
```
$ java -version
Picked up _JAVA_OPTIONS: -Xmx2g
java version "1.7.0_71"
Java(TM) SE Runtime Environment (build 1.7.0_71-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.71-b01, mixed mode)

$ uname -a
Darwin dustismo 13.4.0 Darwin Kernel Version 13.4.0: Wed Mar 18 16:20:14 PDT 2015; root:xnu-2422.115.14~1/RELEASE_X86_64 x86_64
```

**Comment by normanmaurer** [comment]
@Scottmitch @nmittler can you check ?

**Comment by nmittler** [comment]
I'm able to reproduce with `4.1.0.Beta7` but `master` seems fine.  @dustismo can you confirm?

**Comment by normanmaurer** [comment]
Maybe it is related to the enforcing of max streams that I changed lately?

**Comment by nmittler** [comment]
Yup ... @Scottmitch, @normanmaurer  it looks the builder for Http2ConnectionHandler is broken in 4.1.0.Beta7: https://github.com/netty/netty/blob/netty-4.1.0.Beta7/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L188

Where as this is disallowed in master: https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L190

@normanmaurer perhaps `4.1.0.Beta7` missed your patch: https://github.com/netty/netty/commit/4fa6a645627c004e360659d622fcd08c4fb1e3ab?

**Comment by normanmaurer** [comment]
@nmittler yeah I think the patch was cherry-picked after the release.

**Comment by normanmaurer** [comment]
@dustismo please test with 4.1.0.Beta8-SNAPSHOT (current 4.1 branch).

**Comment by dustismo** [comment]
@normanmaurer yep, seems to be fixed in Beta8-SNAPSHOT.  thanks

**Comment by normanmaurer** [comment]
@dustismo thanks!
