### ISSUE TITLE
ByteToMessageDecoder have to watch out for empty buffers

### ISSUE THREAD

**Issue by ctron** [netty/netty#4386]
Netty version: 4.0.31

Context:
Unexpected behavior when implementing a `ByteToMessageDecoder`. Following up in issue #4087.

The Javadoc of `ByteToMessageDecoder` urges the implementer to let another filter handle the actual frame detection, so that the implementation of `ByteToMessageDecoder` can focus on decode the content of the frame. Which is a good idea.

However will the `decode` method always be called when the channel is closed, even if there is no remaining data. This seems illogical (to me) since the prepended `LengthFieldBasedFrameDecoder` has the task of not pushing through data in your chain which does not have a full frame (other decoders like `LengthFieldBasedFrameDecoder`do the same).

So in the end implementations of `ByteToMessageDecoder` and `ByteToMessageDecoder` (since issue #4087 is fixed) do need to check for the received buffer size before being able to decode.

Steps to reproduce:
1. Implement a `ByteToMessageDecoder`
2. Add a `LengthFieldBasedFrameDecoder` and your `ByteToMessageDecoder` implementation to the chain
3. Close the connection
4. `decode` gets called with an empty buffer

**Comment by normanmaurer** [comment]
@ctron I wonder why you even implement a ByteToMessageDecoder and not a MessageToMessageDecoder<ByteBuf> ? 

I think this would be the correct thing for you and also result in the desired behavoir.

**Comment by ctron** [comment]
Well I do have the intention of converting between bytes and messages. So the `ByteToMessageDecoder` with its Javadoc sounded like a good idea.

**Comment by demonhunterg** [comment]
@ctron can we send byte array to netty server without using netty lib? I want to write byte array byjava OutputStream, Ios NSInputStream.

**Comment by normanmaurer** [comment]
@ctron well the ByteToMessageDecoder will "buffer" data until you are ready to consume them. Which is not needed as you already cut out the frames. So MessageToMessageDecoder<ByteBuf> sounds right to me.

**Comment by demonhunterg** [comment]
Same confused.

**Comment by normanmaurer** [comment]
Closing this as explained above.

**Comment by alexstaytuned** [comment]
@normanmaurer,

I also agree with @ctron that this behavior is non-intuitive and hope this issue can be revisited.

Are you saying that for two-way conversion, MessageToMessageCodec<MyMessageType, ByteBuf> is recommended over ByteToMessageCodec<MyMessageType>? The latter seems more intuitive. Both are mentioned in Netty In Action as valid alternatives.

Also, by sending an empty buffer to decode, I think we are violating the integrity property that any message sent to decode has been previously sent. This is the code path sending empty buffers:

    public void channelInactive(ChannelHandlerContext ctx) throws Exception {
        RecyclableArrayList out = RecyclableArrayList.newInstance();
        try {
            if (cumulation != null) {
                callDecode(ctx, cumulation, out);
                decodeLast(ctx, cumulation, out);
            } else {
                decodeLast(ctx, Unpooled.EMPTY_BUFFER, out);
            }
        ...

Why is `decodeLast(ctx, Unpooled.EMPTY_BUFFER, out);` necessary here?

If we want people to not use ByteToMessageCodec due to this behavior, let's indicate so in the docs.

cc @trustin who is the author of this logic.

**Comment by trustin** [comment]
`decodeLast()` is called to give a decoder a chance to perform the last task like creating a new message from a cumulation buffer or releasing resources.

`decodeLast()` is a sort of `finally` block, so it must be invoked regardless if the cumulation buffer is empty or not.

The default behavior of `decodeLast()` is currently to delegate to `decode()` and thus it will drive `decode()` into the situation where it has to handle the case @ctron and @alexstaytuned.

Assuming that `decode()` is not a place to perform a clean-up task but `decodeLast()` is, I think `decodeLast()` should not call `decode()` if the buffer is empty.

What do you think, @normanmaurer ?

**Comment by Scottmitch** [comment]
> I think decodeLast() should not call decode() if the buffer is empty.

sounds reasonable to me. this behavior may extend into codecs too (`HttpObjectDecoder`).

**Comment by normanmaurer** [comment]
Let me take care

**Comment by normanmaurer** [comment]
was fixed
