### ISSUE TITLE
StackOverflowError when adding listener to DefaultPromise w/ ImmediateEventExecutor

### ISSUE THREAD

**Issue by maxwindiff** [netty/netty#4395]
This will produce a `StackOverflowError`:

```java
    @Test
    public void testName() throws Exception {
        DefaultPromise<Object> promise = new DefaultPromise<>(ImmediateEventExecutor.INSTANCE);
        promise.addListener(f1 -> {
            promise.addListener(f2 -> System.out.println("done"));
        });
        promise.tryFailure(new Exception());
    }
```

The error may not show up in console but if you add an exception breakpoint in IntelliJ / Eclipse you'll see it.

Reproduces on 4.1.0.Beta7

**Comment by Scottmitch** [comment]
thanks for reporting @maxwindiff!

**Comment by buchgr** [comment]
@Scottmitch Does this also fix https://github.com/netty/netty/issues/3450?

**Comment by normanmaurer** [comment]
@buchgr yes I think so.

**Comment by Scottmitch** [comment]
@buchgr - Based upon your description (exactly the same scenario that is described in this issue), I would think this should take care of #3450. Is it possible to verify?

**Comment by buchgr** [comment]
@Scottmitch I don't have the code anymore, but yeah it looks like it fixes both issues. I think it's a perfectly valid fix as it makes it work with Netty all provided Executors. However, it doesn't work with Guava's `DirectExecutor` or Developer Joes `SelfBakedDirectExecutor` :). I couldn't think of fix for those scenarios myself either ...

**Comment by Scottmitch** [comment]
@buchgr - I also couldn't think of a good way to generalize the behavior of `the executor will always (or on the next execute call) use the same thread to execute tasks.` ... and just punted for the near term :(
