### ISSUE TITLE
[perf] epoll - try vmsplice+splice instead of writev?

### ISSUE THREAD

**Issue by ninja-** [netty/netty#4397]
As I misunderstood what is the splice(...) support in netty (it's for something else entirely) I propose to try replacing write syscall with a pipe + vmsplice and see what happens. As far as I am aware write(...) causes memory pages to be copied from user-space to kernel-space.

We would keep our pipe which would be vmspliced to when writing. The second part would be easier as already implemented spliceTo(...) would be used to splice from the pipe.
There would be some conditions when write(...) would be forced instead for example when packets size exceeds allowed pipe size etc.

Thoughts? Worth implementing ?
I only wonder about one thing: currently write(...) can return/fail waiting for peer to catch up to the stream if it's lagging badly(filling netty's buffers). With splice this behaviour could change or something like that.

Note: currently splice support is locked to level-triggered epoll. This can be changed to support edge-triggered epoll without much problems(I am not saying that removing safety checks is enough. It boils down to saving current state based on last event(writable,readable).)

![screenshot](https://sc-cdn.scaleengine.net/i/a411ab99d85b37d5ff21c2b1f28e566c1.png)

**Comment by normanmaurer** [comment]
@ninja- no, replacing write / writev with pipe + vmsplice makes no sense. The only thing we could do in theory which may lead to performance gains would be to bypass the kernel network stack completely. But this is a different story...
