### ISSUE TITLE
FixedChannelPool for Netty Client get stuck after server restart

### ISSUE THREAD

**Issue by sandarenu** [netty/netty#4399]
I'm using netty-all 4.0.32-final and I've used `FixedChannelPool` to create a connection pool for a simple http client. I created the pool with maxCount = 2. But when a server restart happens, pool do not return a new connection when I call `connectionPool.acquire()`. It get stuck at that point. Even the timeout doesn't happen. 

I create the channel pool as follows. 
```
 final Bootstrap bootstrap = new Bootstrap();
            InetSocketAddress serverAddress = new InetSocketAddress(host, port);
            bootstrap.group(group)
                    .channel(NioSocketChannel.class)
                    .remoteAddress(serverAddress);

            ChannelPoolMap<InetSocketAddress, SimpleChannelPool> poolMap = new AbstractChannelPoolMap<InetSocketAddress, SimpleChannelPool>() {
                @Override
                protected SimpleChannelPool newPool(InetSocketAddress key) {
                   return new FixedChannelPool(bootstrap.remoteAddress(key), new ClientChannelPoolHandler(sslCtx), 2);

                }
            };

            final SimpleChannelPool channelPool = poolMap.get(serverAddress);

```

And accuire channel as follows.

```Channel channel = this.connectionPool.acquire().sync().get(poolAcquireTimeoutSeconds, TimeUnit.SECONDS);
           ```

When I increase the max connection count I get a new connetion, but when I do multiple server restarts same issue arises again. It looks like stale connections are not being removed from the Pool. What should be the issues here? Am I doing something wrong when creating the pool?

**Comment by normanmaurer** [comment]
@sandarenu could you submit a unit test that demonstrate the issue ?

**Comment by normanmaurer** [comment]
@sandarenu ping

**Comment by Scottmitch** [comment]
@sandarenu - Can you also show the code that demonstrates how you are releasing the channels back tot he pool?

**Comment by normanmaurer** [comment]
Let me close this for now... if you still think there is an issue please re-open
