### ISSUE TITLE
[perf] cache inbound/outbound invoker

### ISSUE THREAD

**Issue by ninja-** [netty/netty#4400]
![](https://camo.githubusercontent.com/3606bec29730b96b3199fe7aab5132ce69c8b573/68747470733a2f2f73632d63646e2e7363616c65656e67696e652e6e65742f692f6134313161623939643835623337643566663231633262316632386535363663312e706e67)

anything against adding cached variables to findInbound/findOutbound ? they would be looked for only once and stored in a variable. triggering handler addition/removal should clear cached variables for every handler.
I see there were some attempts to do it in 5.0 master("flags") but I don't like this approach, this one is a lot simpler and doesn't use reflection.

**Comment by normanmaurer** [comment]
@ninja- I'm not convinced it is really a performance bottleneck currently. Adding a cached variable introduce more complexity to ensure it is correct in multi-threaded environments.

**Comment by normanmaurer** [comment]
Closing this for now
