### ISSUE TITLE
OpenSSL client side "renegotiation unsupported" issue

### ISSUE THREAD

**Issue by slandelle** [netty/netty#4407]
* Netty 4.0.32.Final
* netty-tcnative 1.1.33.Fork10
* OSX El Capitan
* Hotspot 1.8.0_66

I'm trying to play with OpenSSL support on the client side.

In this [gist](https://gist.github.com/slandelle/5fbda68093273fcff3b8), the first sample works fine, but the second one crashes with a "renegotiation unsupported" SSLException.

Everything works fine with JDK SslProvider.
I checked the SSL logs, and I didn't seem to me there was any renegociation happening.

In the first one, I add the SslHandler in the ChannelInitializer while in the second one I do it on the fly once the connect future is successful.
In real code (AsyncHttpClient), I have to go with the second strategy because:
* I don't know the peer hostname and port beforehand, for hostname verification
* I might have to start over plain HTTP then upgrade, for proxy tunnelling

I don't really get neither how the event sequence is actually any different, nor why renegociation is happening.

Could you please help?

Thanks!

**Comment by slandelle** [comment]
Note that I had the following warning when installing OpenSSL with homebrew:

```
This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
```

I don't know how much of an impact this has.

**Comment by slandelle** [comment]
FYI, I have the same issue on Ubuntu 14.0.4.

**Comment by slandelle** [comment]
Mmm, things work when I move setting the SslHandler into `channelActive` instead of in the Listener in the connect Future. I noted that the listener is being called before channelActive. Does this make sense?

**Comment by normanmaurer** [comment]
Thanks for the info... Both ways should work. Will provide a fix soon

**Comment by normanmaurer** [comment]
@slandelle just checked... this was fixed in 4.0.33.Final-SNAPSHOT already. Running it with current 4.0 branch not shows the problem (yay).

**Comment by slandelle** [comment]
Great, I confirm that it work, thanks!!!

Is it this one? #4355

I feel stupid for not having checked the snapshot first...

**Comment by slandelle** [comment]
@normanmaurer Any idea when you might release 4.0.33?
