### ISSUE TITLE
Build fails on OSX

### ISSUE THREAD

**Issue by buchgr** [netty/netty#4409]
just wanted to build Netty master (mvn clean install) on a clean machine and building `microbench` fails

```
Failed to execute goal on project netty-microbench: 
Could not resolve dependencies for project io.netty:netty-microbench:jar:5.0.0.Alpha3-SNAPSHOT:
Failure to find io.netty:netty-transport-native-epoll:jar:osx-x86_64:5.0.0.Alpha3-SNAPSHOT
```

I am running on El Capitan, Java 1.8u60 and Maven 3.3.3. 

I am not familiar enough with Maven to fix this quickly, but can look into it if none if you know of a quick resolution either.

**Comment by slandelle** [comment]
I guess all the native transport related stuff should only be built/triggered when a Linux only maven profile is enabled.

**Comment by buchgr** [comment]
yes, that's also how the pom file seems to be set up, but idk how this "conditional dependency" stuff works in maven.

**Comment by buchgr** [comment]
aww i think I have a fix.

**Comment by slandelle** [comment]
@buchgr @normanmaurer CI build was successful and I just squashed the 2 commits.

**Comment by normanmaurer** [comment]
Fixed
