### ISSUE TITLE
Improve performance of FastThreadLocal slow path

### ISSUE THREAD

**Issue by buchgr** [netty/netty#4418]
Issues #4402 and #4417 gave some indication that there might be room for performance improvement on the slow path of `FastThreadLocal`.

The performance on the slow path might be critical if a user of Netty plugs in an `Executor` that does not use `FastThreadLocalThreads`.

**Comment by ninja-** [comment]
tip for you: current slow-path calls 2x Thread.currentThread(). have fun

**Comment by Scottmitch** [comment]
@normanmaurer - Any updates on this issue? Didn't have have a PR related to this?

**Comment by normanmaurer** [comment]
Nope lost track on this one. Should pock it up again

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5012
