### ISSUE TITLE
tomcat jni class not found when compile

### ISSUE THREAD

**Issue by stoneCrystal** [netty/netty#4425]
For example, these clasess in OpenSsl(4.1 branch)
import org.apache.tomcat.jni.Library;
import org.apache.tomcat.jni.Pool;
import org.apache.tomcat.jni.SSL;
import org.apache.tomcat.jni.SSLContext;

my IDE is IDEA(maven 2.2.1)

**Comment by normanmaurer** [comment]
What OS ?

**Comment by stoneCrystal** [comment]
macbook pro

**Comment by normanmaurer** [comment]
What version of osx?

**Comment by stoneCrystal** [comment]
10.10.5

**Comment by stoneCrystal** [comment]
![Uploading 屏幕快照 2015-10-31 下午7.03.06.png…]()

**Comment by stoneCrystal** [comment]
Maven: io.netty:netty-tcnative:${os.detected.classifier}:1.1.33.Fork10   seem this jar not import successful

**Comment by stoneCrystal** [comment]
*/.m2/repository/io/netty/netty-tcnative/1.1.33.Fork10/netty-tcnative-1.1.33.Fork10-javadoc.jar

**Comment by normanmaurer** [comment]
Does 'mvn clean package' in tge terminal work?

**Comment by stoneCrystal** [comment]
not work

**Comment by stoneCrystal** [comment]
I solve this issue by modify idea project file, I think the root cause is IDEA parse ${os.detected.classifier} varable have problem.

**Comment by normanmaurer** [comment]
@stoneCrystal if you just import it as a new "maven" project it should just work, as least this is how it works here.
