### ISSUE TITLE
Migration from 4.0.32.Final to 4.0.33.Final breaks my tests

### ISSUE THREAD

**Issue by doom369** [netty/netty#4439]
Hello. I have a bunch of tests for my main scenarios. I made this tests 8 months ago and was successful in migration from 4.0.18 until now. But after migration to 4.0.33 some of my tests failed. They look like that :

```
    @Test
    public void testConnectAppAndHardwareAndSendCommands() throws Exception {
        for (int i = 0; i < 100; i++) {
            clientPair.appClient.send("hardware 1 aw 1 1");
        }

        verify(clientPair.hardwareClient.responseMock, timeout(10000).times(100)).channelRead(any(), any());
    }
```

Scenario is very simple. I start locally netty server (before test start) and connect ```clientPair.appClient``` and ```clientPair.hardwareClient``` to it. Than I send 100 commands from ```clientPair.appClient``` to server and expecting that ```clientPair.hardwareClient``` will receive them all. But after switching to 4.0.33 ```clientPair.hardwareClient``` gets every time random number of request.

I made a look and found that problem itself in send method
```
    public void send(MessageBase msg) {
        if (channel.isWritable()) {
            channel.writeAndFlush(msg);
        }
    }
```

Behavior of ```channel.isWritable()``` in 4.0.33 is not same as in 4.0.32. Switching back to 4.0.32 fixes tests.

So I wonder - is that expected change? Is that correct?

**Comment by ninja-** [comment]
the defaults watermarks could've been changed since, they are the values used for determining isWritable(). maybe you want to set them explicitly?

**Comment by normanmaurer** [comment]
@doom369 I think this is most likely the result of :

https://github.com/netty/netty/pull/4380

So yes it is expected as the calculation before was not good enough and so the risk of getting a OOME was higher then it should have been.

**Comment by Scottmitch** [comment]
@doom369 - Looks like you already have the message allocated in `send` why don't you just write it?  Netty will provide queuing for you and write when channel becomes writable again.  Generally the writability is useful if you haven't already allocated the object (you can slow your peers down), but if you already have an object allocated the only options are to queue it and send later, or drop it on the floor.

**Comment by doom369** [comment]
@normanmaurer Ok, thank you. Just want to be sure this is something you aware of and this change expected.

@Scottmitch thank you for advise. Will change it.
