### ISSUE TITLE
Recyclable FileRegion

### ISSUE THREAD

**Issue by pjulien** [netty/netty#4441]
I have the following use case

- Single ring buffer per incoming request queue
- Multiple ring buffers can be used to write to a fairly static set of ``Channel``s, i.e., one to many relationship between ring buffers and channels
- A single ring buffer is backed by a memory mapped ``ByteBuffer`` file
- I keep the ``FileChannel`` of the ring buffer open
- To queue up data to the socket, I write to the ring buffer which in turns writes to the memory mapped buffer
- For forwarding the data, I just read the position and length of entries in the ring buffer to initialize a ``DefaultFileRegion``
- I have about 50,000 ring buffers, which implies 50,000 file descriptors.
- I can also peek multiple entries from the ring buffer, which means I can have multiple writes of ``FileRegion`` in-flight at the same time.

The problems I'm facing with ``DefaultFileRegion`` are:
- There is no constructor that allows leaving the ``FileChannel`` open when done.  Without this, I cannot keep the number of ``FileChannel``s static.
- Additionally, it would be nice if I could recycle ``DefaultFileRegion`` when done.  I would reset the position and length and perform a new write using the same object.  This is just for GC churn.

**Comment by normanmaurer** [comment]
@pjulien why you can't just extend `DefaultFileRegion` and override the `deallocate()` method ? This way it will not close the `FileChannel`.

**Comment by pjulien** [comment]
@normanmaurer  sure for the first use case but the object still can't be reused

**Comment by normanmaurer** [comment]
@pjulien I guess we could provide a recycle implementation, that said I think most users not need it. Maybe just implement it by your own for now ?

**Comment by pjulien** [comment]
@normanmaurer 

> Maybe just implement it by your own for now ?

Sure.

**Comment by normanmaurer** [comment]
Let me close this for now
