### ISSUE TITLE
4.0 HttpHeader.set(HttpHeader) will cause itself to be emptied when passed self

### ISSUE THREAD

**Issue by louiscryan** [netty/netty#4442]
public HttpHeaders set(HttpHeaders headers) {
        if (headers == null) {
            throw new NullPointerException("headers");
        }
        clear();
        for (Map.Entry<String, String> e: headers) {
            add(e.getKey(), e.getValue());
        }
        return this;
}

this is in conflict with DefaultHttpHeaders which will throw an exception when doing the same thing so there is inconsistency in the interface contract

**Comment by Scottmitch** [comment]
@louiscryan - I think we can close this now?
