### ISSUE TITLE
STOMP codec does not comply with STOMP 1.2 spec

### ISSUE THREAD

**Issue by LionelCons** [netty/netty#4448]
The Netty STOMP codec does not fully comply with the STOMP 1.2 specification (https://stomp.github.io/stomp-specification-1.2.html).

The most important violation is about header value encoding (see https://stomp.github.io/stomp-specification-1.2.html#Value_Encoding) which is completely missing. As a consequence, a header value with a colon (such as foo:bar) will be decoded by Netty as a value with \c instead (such as foo\cbar).

Solving this is tricky since the codec must know which version of STOMP is spoken in order to "do the right thing" and this version is negotiated as part of the first two frames (CONNECT/CONNECTED).

**Comment by Scottmitch** [comment]
@LionelCons - We love PRs :) Would you be interested in submitting one?

**Comment by LionelCons** [comment]
I could probably submit something but the problem is not straightforward to solve since the exact decoding/encoding to perform is linked to the version of the STOMP protocol negotiated one level up, outside of the codec.

One possibility would be to have three different codecs (STOMP 1.0, 1.1 and 1.2) and to switch to the right codec once the version has been negotiated.

Another possibility would be to have a single codec with a variable behaviour controlled from the outside.

I know very well STOMP but not Netty. Would it be possible to discuss the best integration strategy with someone with deep Netty knowledge?

**Comment by normanmaurer** [comment]
I think different codecs sounds like a good way to handle it

**Comment by Scottmitch** [comment]
if you feel that there is minimal overlap or sharing with the existing STOMP codec then new codec sounds good. How much overlap would there be between 1.2 and what is supported in Netty now?

**Comment by LionelCons** [comment]
@Scottmitch There would be a lot of overlap.

The existing codec looks good. The problem I reported (header value decoding/encoding) is quite easy to fix in the existing code. What is not easy is to have different codec behaviours based on the negotiated STOMP version. For instance, for STOMP 1.0, there should be no header value decoding/encoding.

FWIW, I wrote a Perl STOMP implementation (http://search.cpan.org/dist/Net-STOMP-Client/) that uses a single class with slightly different behaviours based on the negotiated STOMP protocol version.

**Comment by LionelCons** [comment]
Looking deeper in the existing codec implementation, there might be problems adding STOMP heart-beat support.

The protocol spec contains: "if the sender has no real STOMP frame to send, it MUST send an end-of-line (EOL)". The EOLs are currently read in StompSubframeDecoder's skipControlCharacters() and I don't know how to update a "last data receive time" to allow the program to detect an absence of new data within the heart-beat window.

Either the codec should emit empty STOMP frames (to allow the program to keep track of time itself) or it should handle time tracking itself.

Symmetrically, Netty's STOMP codec should be able to send EOLs / empty frames to tell the remote end that the program is still alive...

**Comment by LionelCons** [comment]
Since the STOMP 1.0 specification leaves many details unspecified and since most clients and servers anyway support STOMP 1.1 or greater, I would propose to officially restrict the Netty implementation to STOMP 1.1 and higher (i.e. 1.1 and 1.2). This way, Netty would not have to deal with backward compatibility hacks such as how to parse a header like "a:b:c" or whether or not to trim spaces in a header like "foo: bar".

At Netty's (low) level, STOMP 1.1 and STOMP 1.2 are almost identical. The only real difference is the line ending (LF vs. EOL). I would propose a pragmatic approach:
 - assume EOL when decoding
 - use LF when encoding

This way, we could have a single 100% STOMP 1.2 compliant implementation that would also work with STOMP 1.1 peers except for a very rare corner case (header values ending with a CR). BTW, it would also work with STOMP 1.0 peers using simple headers (no colons, no spaces...).

**Comment by Scottmitch** [comment]
@sskachkov @trustin - WDYT?

If stomp is only in 4.1+ there may not be as strong a case to maintain 1.0 for backwards compatibility reasons. We could just call stomp experimental for now?

@normanmaurer - Who generally drives the stomp development these days?

**Comment by LionelCons** [comment]
FWIW, there is another area where Netty does not comply to the STOMP >=1.1 spec: string encoding. The current codec has `buf.append((char) nextByte)` while the specs indicate UTF-8 encoding. In this area too, the STOMP 1.0 spec is silent...

**Comment by LionelCons** [comment]
One year has passed....

If Netty's STOMP support is not experimental then these compliance issues with the STOMP specifications should really be addressed.

**Comment by Scottmitch** [comment]
@LionelCons - I don't know who uses stomp /cc @sskachkov @silvaran. If you need support for this I think the best way would be to submit a PR.

**Comment by amizurov** [comment]
Hi, everyone i agree with @LionelCons. The STOMP support in Netty looks very experimental, I also would like to use STOMP via WebSockets, but with the current implementation of StompSubframeEncoder this is not very convenient, because the encoder returns ByteBuff to pipeline.

**Comment by Scottmitch** [comment]
Netty is an OpenSource project @LionelCons @amizurov. If these features are important to you please submit PRs to improve/fix. If the PR is large in scope I recommend creating an issue detailing the issues and your approach to fix them first to avoid spending effort in something that cannot be supported easily.
