### ISSUE TITLE
DefaultFullHttp(Request|Response).hashCode() throws IllegalRefCountException

### ISSUE THREAD

**Issue by blucas** [netty/netty#4458]
Netty Version: master (latest snapshot a6816bd59ef2923d82af5b7a7f3b722507a56a3a)

I've notice that if a ```DefaultFullHttpRequest``` or ```DefaultFullHttpResponse``` have been released, then calls to ```hashCode()``` will throw an ```IllegalRefCountException``` [here](https://github.com/netty/netty/blob/master/codec-http/src/main/java/io/netty/handler/codec/http/DefaultFullHttpRequest.java#L167) and [here](https://github.com/netty/netty/blob/master/codec-http/src/main/java/io/netty/handler/codec/http/DefaultFullHttpResponse.java#L170). I was wondering if this is considered the correct behaviour?

**Comment by normanmaurer** [comment]
No this is a bug

**Comment by blucas** [comment]
Is it just a matter of returning 0 if the content has been freed? If so I could provide a PR for it.  I wonder what would happen to lookups for entries in a hash-based container (such as a HashMap<DefaultFullHttpRequest, SomeObject>)?

**Comment by Scottmitch** [comment]
@blucas - Semantics would change (the lookup may fail the second time) if we use an arbitrary constant if the content has been released.  Perhaps we should cache some (or all) of the hash code that is considered "imitable". I can submit a PR to cleanup.

**Comment by normanmaurer** [comment]
@Scottmitch @blucas not sure what is the best way to fix this but I think we should not throw for equals(....), toString() and hashCode().

**Comment by blucas** [comment]
@Scottmitch - To give you some background, I discovered this issue when attempting to clear out data stored in a ```DefaultHttpDataFactory``` for a given request which had already been freed. It threw the ```IllegalRefCountException``` when attempting to lookup a value which was keyed by ```DefaultFullHttpRequest``` [here](https://github.com/netty/netty/blob/master/codec-http/src/main/java/io/netty/handler/codec/http/multipart/DefaultHttpDataFactory.java#L250).  Maybe it isn't a good idea to use ```FullHttpRequest``` or ```FullHttpResponse``` objects as keys in maps?

@normanmaurer - I agree, we shouldn't throw, regardless of what the fix is.

**Comment by Scottmitch** [comment]
@blucas - In general the hashCode and equals were added for testing purposes.  However it is not unreasonable to use these items as keys in a map. For example maybe a cache may use a request as a key into a map. You have to be aware of with the current implementation is that the content is used in the hash code generation, and it may be an expensive operation.

We can discuss the `DefaultHttpDataFactory` details in another issue if that is OK?

**Comment by Scottmitch** [comment]
See https://github.com/netty/netty/pull/4463

**Comment by blucas** [comment]
@Scottmitch - thanks for the quick PR.  With regards to ```DefaultHttpDataFactory``` I was just curious. No need to raise another issue unless you think it warrants one.

**Comment by Scottmitch** [comment]
@blucas - If you are happy then I am happy :). Honestly I would need to look into `DefaultHttpDataFactory` in more detail to see if it is necessary to use the entire `Full` message or not.

**Comment by Scottmitch** [comment]
Fixed by https://github.com/netty/netty/pull/4463. Thanks for reporting @blucas !
