### ISSUE TITLE
Remove master branch

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#4466]
After talking with @Scottmitch and also with @nmittler I would like to propose "dropping" current master and so not release any new 5.0 version for now. 

The major change of using a ForkJoinPool increases complexity and has not
demonstrated a clear performance benefit. Also keeping all the branches in sync is quite some work without a real need for it as there is nothin in current master which I think justifies a new major release.

Things that we should investigate to prepare for this change:
- Deprecate `exceptionCaught` in `ChannelHandler`, only expose it in `ChannelInboundHandler`
- Expose `EventExecutorChooser` from `MultithreadEventExecutorGroup` to allow the user more flexibility to choose next `EventLoop`
- Add another method to be able to send user events both ways in the pipeline. (https://github.com/netty/netty/pull/4378)

Please chime in here and let me / us hear any concerns.

**Comment by normanmaurer** [comment]
Also I should have mentioned that we should create a new branch from current master that we keep for "backup" reasons. So we can port code if the need arise later.

**Comment by trustin** [comment]
+1. I'd like to keep the handler type hierarchy simplification for later cherry-pick (?) though.

**Comment by blucas** [comment]
A few questions:
* So what do you propose creating exactly, for example where would these changes (deprecating ```exceptionCaught```, exposing ```EventExecutorChooser```, etc.) be applied - 4.1, 4.2, or a new 5.0 branch?
* If I remember correctly, 5.0 merged ```ChannelInboundHandler``` and ```ChannelOutboundHandler``` as well as introducing ```messageReceived``` as a replacement for ```channelRead0```.  What would happen to these changes?
* Will all features/improvements currently applied to master be ported to this new release? Obviously HTTP/2 was ported to 4.1, just wondering if there is anything else sitting on master that would need attention.

**Comment by ninja-** [comment]
That's a bit sad but I would support this change D: wasn't the major feature of 5.0 fixed eventloop migrations or something like that?

**Comment by Scottmitch** [comment]
> So what do you propose creating exactly, for example where would these changes (deprecating exceptionCaught, exposing EventExecutorChooser, etc.) be applied - 4.1, 4.2, or a new 5.0 branch?

@blucas - Unless there are objections I think the proposal is to apply these changes to 4.1. The discussion resolves around there not being enough API changes/core features to justify maintaining a different fork. Any deprecated methods/interfaces would also be marked accordingly in 4.0.

> If I remember correctly, 5.0 merged ChannelInboundHandler and ChannelOutboundHandler as well as introducing messageReceived as a replacement for channelRead0. What would happen to these changes?

Are you thinking of 4.1 [SimpleChannelInboundHandler.channelRead0](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/SimpleChannelInboundHandler.java#L128) vs 5.0 [SimpleChannelInboundHandler.messageReceived](https://github.com/netty/netty/blob/master/transport/src/main/java/io/netty/channel/SimpleChannelInboundHandler.java#L125)?  In 4.1 I guess we would keep channelRead0 to stay API compatible with [4.0](https://github.com/netty/netty/blob/4.0/transport/src/main/java/io/netty/channel/SimpleChannelInboundHandler.java#L128)

> Will all features/improvements currently applied to master be ported to this new release? Obviously HTTP/2 was ported to 4.1, just wondering if there is anything else sitting on master that would need attention.

That is the intention. If you know of any please call them out :)  We will rename the "master" branch so nothing will be lost if we forget/miss something.

**Comment by normanmaurer** [comment]
@blucas what @Scottmitch said.

**Comment by normanmaurer** [comment]
@ninja- event loop migration works in 4.0 as well.

**Comment by Scottmitch** [comment]
@normanmaurer - Also as a reminder we should revisit deprecated items in 4.1. If things have been deprecated in 4.1 in favor of a change in 5.0, we may want to un-deprecate these items.

**Comment by Scottmitch** [comment]
@normanmaurer - For example `AUTO_CLOSE` channel option may be a candidate.

**Comment by trustin** [comment]
Meanwhile, let me change the default branch from 'master' to '4.1'.

**Comment by normanmaurer** [comment]
Thanks! Will take care of the rest once back from vacation

**Comment by hepin1989** [comment]
As *Netty In Action* cover 4.x,I think this should be fine.

**Comment by normanmaurer** [comment]
master branch was rename to master_deprecated. Changes only need to go to 4.0 and 4.1 now.

**Comment by Scottmitch** [comment]
Woot! thanks @normanmaurer!

**Comment by junchaowu** [comment]
For existing 5.x user, do you recommend to change back to use 4.x  or I can still use 5.x? What's the recommend way now

**Comment by normanmaurer** [comment]
Use 4.0 or 4.1

**Comment by ShanniLi** [comment]
@normanmaurer this change will break TChannel-JAVA and all TChannel-JAVA users.

**Comment by normanmaurer** [comment]
@ShanniLi again just use netty 4.0 which works on android

**Comment by normanmaurer** [comment]
@ShanniLi 5.0 was alpha so you should expect breakage.

**Comment by zhangkan1983** [comment]
@normanmaurer @trustin:
My major concern is that in 4.X, when implement a UDP server, there is only one channel and Eventloop to handle all the IO operation by design(as far as i understand). This would definitely introduce a performance issue when many devices are try to connect to the server at the same time. And unfortunately, we cannot utilize the Linux epoll as the kernel version is only 2.6. Is there any workaround available in 4.X? Please let me know. 

Many Many Thanks!

Kan

**Comment by freevest** [comment]
Mark and support

**Comment by wxyjuly** [comment]
come on , waiting for next time updated

**Comment by niancheng** [comment]
mark

**Comment by LoveCtrip** [comment]
ok

**Comment by yschimke** [comment]
![image](https://user-images.githubusercontent.com/231923/48506294-ff164280-e840-11e8-82f1-3f22d4a118bb.png)


https://github.com/netty/netty/projects/1

**Comment by fuzhengwei** [comment]
netty demo for 4.1
https://bugstack.cn/index.php/category/netty%E4%B8%93%E9%A2%98/

**Comment by shihongwei** [comment]
mark

**Comment by abcdelf** [comment]
> netty demo for 4.1
> https://bugstack.cn/index.php/category/netty%E4%B8%93%E9%A2%98/

https://bugstack.cn/itstack-demo-netty/itstack-demo-netty.html
链接也更新一下呐

**Comment by shallwetalkge** [comment]
mark

**Comment by niancheng** [comment]
您好！您的来信我已经收到，我会尽快查阅并回复您的！
