### ISSUE TITLE
NioClientSocketChannelFactory.releaseExternalResources() hangs

### ISSUE THREAD

**Issue by pbostrom** [netty/netty#4467]
I have a long running process that uses AsyncHttpClient with Netty 3.10.4.Final. I've noticed that after the process has been running for a few days I will see a call to NioClientSocketChannelFactory.releaseExternalResources() hang indefinitely. Unfortunately I don't have much more detail as it happens so rarely. Here is the stack trace and system info:
```
sun.misc.Unsafe.park(boolean, long)
java.util.concurrent.locks.LockSupport.park(Object)
java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt()
java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(int)
java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(int)
java.util.concurrent.CountDownLatch.await()
org.jboss.netty.channel.socket.nio.AbstractNioSelector.shutdown()
org.jboss.netty.channel.socket.nio.NioWorker.shutdown()
org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool.shutdown()
org.jboss.netty.channel.socket.nio.NioClientSocketChannelFactory.releaseExternalResources()
com.ning.http.client.providers.netty.channel.ChannelManager.close()
com.ning.http.client.providers.netty.NettyAsyncHttpProvider.close()
com.ning.http.client.AsyncHttpClient.close()

$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
$ uname -a
Linux ip-10-139-57-253 4.1.10-17.31.amzn1.x86_64 #1 SMP Sat Oct 24 01:31:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ninja-** [comment]
doesn't look like latest 3.10, please use 3.10.6.Final-SNAPSHOT. quick googling reveals that problem was a netty bug that should be fixed by updating so I hope that should also help your case

**Comment by pbostrom** [comment]
I found a bug in our response handling code for AsyncHttpClient that causes an onCompleted handler to hang. This prevents the CountDownLatch from ever being released, which then prevents the client from being closed.
