### ISSUE TITLE
Wrong words in comments of class EventLoop

### ISSUE THREAD

**Issue by xiajunhust** [netty/netty#4469]
the comment of class EventLoop is:
`
Will handle all the I/O operations for a {@link Channel} once registered.
One {@link EventLoop} instance will usually handle more then one {@link Channel} but this may depend on implementation details and internals.
`

the word "then" should be "than".  
version:  
netty-all-5.0.0.Alpha2

thank you.

**Comment by pieteradejong** [comment]
@normanmaurer I only read that you'd self-assigned after I'd fixed it and submitted a PR #4485 - hope it helps!

**Comment by normanmaurer** [comment]
@pieteradejong thanks a lot
