### ISSUE TITLE
PooledByteBufAllocator simple constructor for max used memory

### ISSUE THREAD

**Issue by stepancheg** [netty/netty#4471]
Suppose, user wants to have `PooledByteBufAllocator` which cache size 500M. Currently it is not possible to do it without deep understanding of how `PooledByteBufAllocator` works.

So, requesting `PooledByteBufAllocator` with with max memory parameter. Something like this:

```
class PooledByteBufAllocator {
    PooledByteBufAllocator forMaxMemory(long maxMemory) {
        long maxArenaSize = ...;
        return new PooledByteBufAllocator(false, maxMemory / maxArenaSize, maxMemory / maxArenaSize, ...);
    }
}
```

Using netty 4.0.33.Final.

**Comment by normanmaurer** [comment]
@stepancheg sorry for the late response. So you want it to pool max of X memory and after this just allocate unpooled memory?

**Comment by stepancheg** [comment]
Yes, I think so. Isn't it how `PooledByteBufAllocator` works now?

**Comment by normanmaurer** [comment]
After thinking more about it I think there is not much we can do in terms of set a max limit.
