### ISSUE TITLE
PooledByteBufAllocator API access allocated memory size

### ISSUE THREAD

**Issue by stepancheg** [netty/netty#4472]
I need to output amount of memory used by netty to monitoring.

It would be nice if `PooledByteBufAllocator` had methods like:

```
long usedMemory();
long cachedMemory();
```

So `PooledByteBufAllocator` could be later tuned.

**Comment by normanmaurer** [comment]
You can do this now via the metrics that it expose per arena and cache

**Comment by stepancheg** [comment]
I tried to understand how to do it with `PooledByteBufAllocator` and I couldn't. It has dozen of methods like `int smallCacheSize()` or `List<PoolArenaMetric> directArenas()` with tens of methods inside, and without deep knowledge of netty internals I have not a clue, how to compute totals (especially, how to do it efficiently).

Simple methods like `usedMemory` and `cachedMemory` would be a big help.

Note, that jemalloc (which is mentioned in `PooledByBufAllocator`) provides such statistics. For example, it has `stats.allocated` property available via `mallctl` property.

**Comment by buchgr** [comment]
@stepancheg The sum of all `PoolArenaMetric.numActiveBytes()` should correspond to jemallocs `cachedMemory`.

@normanmaurer I think simple methods like `usedMemory()` and `cachedMemory()` would indeed be helpful?

**Comment by normanmaurer** [comment]
@buchgr yep that said I can not add these now as this would be a breaking change ( need to add methods to interface).
