### ISSUE TITLE
ALPN API dependency should have `provided` scope

### ISSUE THREAD

**Issue by jchambers** [netty/netty#4480]
According to [Jetty's ALPN docs](http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-understanding):

> To implement this interaction, Jetty's ALPN implementation provides an API to applications, hosted at Maven coordinates `org.eclipse.jetty.alpn:alpn-api`. You need to declare this dependency as provided, because the `alpn-boot` Jar already includes it (see the previous section), and it is therefore available from the boot classpath.

I know Netty's doing some slightly fancier things in its POM, but I *think* that advice still applies here. In both [4.1.0.Beta8](https://github.com/netty/netty/blob/6a93f331d3b12bbebcb2b6c2f65fd4ee00a134ea/pom.xml#L694) and [master](https://github.com/netty/netty/blob/bfac74e382df02827aee467e3b7002de6a4c2e56/pom.xml#L685), the `alpn-api` dependency is given the default (`compile`) scope.

**Comment by Scottmitch** [comment]
@jchambers - Thanks for reporting!
