### ISSUE TITLE
ReadString()

### ISSUE THREAD

**Issue by esfomeado** [netty/netty#4481]
Is there any plans in implementing a simple readString to the ByteBuf class?

Thanks

**Comment by normanmaurer** [comment]
@esfomeado why not use `ByteBuf.toString(....)` ?

**Comment by normanmaurer** [comment]
Closing as we need more info

**Comment by esfomeado** [comment]
ByteBuf.toString(...) works fine however you need to do the following steps in order to read a string from a ByteBuf:
1 - Read (U16) string length.
2 - Read the string itself.
3 - Move the readerIndex of the ByteBuf.

In you create a function to do this steps but it would look "ugly" when this could be integrated in Netty.
So i was thinking that would be great if was possible to encapsulate this steps in a readString() like there is a readByte(), readShort(), etc...
The readString() should support as parameter the Charset and if one wasn't passed it should use the default.

**Comment by Scottmitch** [comment]
This feels like a duplicate of https://github.com/netty/netty/issues/2936? @esfomeado - Can you describe how this request differs from the previous request?

**Comment by esfomeado** [comment]
@Scottmitch Is a duplicated.

In my opinion it makes some sense to have a readString(), writeString() directly in the ByteBuf because sometimes there is the need to send strings in the ByteBuf.
I can't use a decoder because i don't wanna convert all the ByteBuf to a string. I'm developing a MMO in my free time and this would be a great helper to simplify some stuff.

Regards
