### ISSUE TITLE
Netty 4.0.30.Final channel write hangs

### ISSUE THREAD

**Issue by Tochemey** [netty/netty#4482]
Please refer to issue on stackoverflow : http://stackoverflow.com/questions/33773643/netty-4-0-30-final-channel-write-issue?noredirect=1#comment55314235_33773643

**Comment by maxu78** [comment]
how do you resolved this problem？

**Comment by maxu78** [comment]
i have the same problem now，and it doesn't show up often. can you give me some suggestions？
