### ISSUE TITLE
Spaces in WebSocket URIs not handled correctly

### ISSUE THREAD

**Issue by rbi** [netty/netty#4505]
Websocket connections to URIs that have spaces in the path can not be established in Netty 4.0.21.

The problematic code seams to be [this line](https://github.com/netty/netty/blob/master/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshaker13.java#L129). If the URI contains a space encoded as %20, the [getPath](http://docs.oracle.com/javase/8/docs/api/java/net/URI.html#getPath--) Method decodes this back to a normal space. This decoded space is then send in the HTTP request at some deeper layer without properly reencoding it.

**Comment by rbi** [comment]
[This is the Workaround](https://github.com/saxsys/SynchronizeFX/blob/9789b889a160051c4f74097446a4bc563f2beabb/transmitter/netty-transmitter/src/main/java/de/saxsys/synchronizefx/netty/websockets/WhiteSpaceInPathWebSocketClientHandshaker13.java) i use. I basically use [getRawPath()](http://docs.oracle.com/javase/8/docs/api/java/net/URI.html#getRawPath--) instead of `getPath()`.

**Comment by Scottmitch** [comment]
@rbi - Thanks for reporting. Would you mind submitting a PR?

**Comment by normanmaurer** [comment]
Working on a fix...

**Comment by rbi** [comment]
Sorry for not answering but thank you for fixing it. I'm looking forward to Netty 4.0.34. 👍

**Comment by normanmaurer** [comment]
Fixed via https://github.com/netty/netty/pull/4552
