### ISSUE TITLE
DefaultPromise and ImmediateEventExecutor synchronization issues

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4506]
There is a potential synchronization issue in DefaultPromise if `ImmediateEventExecutor` is used. DefaultPromise uses a pattern for synchronization which relies upon all processing happening in the EventLoop thread to avoid the need for other synchronization primitives.  When the `ImmediateEventExecutor` is used it is possible that `notifyLateListener` will be invoked in a different calling thread that was used to initialize the internal data structures. This leads to race conditions and late listeners that never get notified.

This may be more generally applicable throughout Netty...more investigation may be needed.

**Comment by Scottmitch** [comment]
@normanmaurer - FYI

**Comment by normanmaurer** [comment]
@Scottmitch I wonder if we may should better `@deprecated` the `ImmediateEventExecutor`because of this issues. @trustin @nmittler WDYT ?

**Comment by Scottmitch** [comment]
@normanmaurer - What about folks that have their own version of "an executor that always executes in the calling thread"?

**Comment by nmittler** [comment]
Yeah I agree with @Scottmitch, I don't think we can just ignore "immediate" executors.

**Comment by normanmaurer** [comment]
@Scottmitch these should write their own `Promise` implementation. Honestly I think the implementation may not be "valid" if `inEventLoop` is not implemented probably.

**Comment by slandelle** [comment]
FWIW, I use `ImmediateEventExecutor` to adapt currently blocking implementations to non blocking APIs, until I can change them. For example, I want a non blocking hostname resolution API, but can't switch to Netty 4.1 yet, so I wrap my blocking implementation so it returns a Future.

If `ImmediateExecutor` isn't the proper way to do that, please advise. IMHO, there's 2 uses cases that would need it:
* blocking/immediate results that one wants to decorate into Futures 
* cheap Future transformation where you don't want the pay the penalty of jumping back into the event loop

**Comment by trustin** [comment]
`ImmediateExecutor` and `ImmediateEventExecutor` have their own uses when their users who know what they are doing. Perhaps we should add some warning sign in our API documentation?

**Comment by Scottmitch** [comment]
@trustin - Agreed at a minimum we should update APIs to clarify the limitations.  Maybe also some assert statements?

**Comment by Scottmitch** [comment]
There have been a few PRs to address this issue ... the latest is https://github.com/netty/netty/pull/5312
