### ISSUE TITLE
HttpClientUpgradeHandler.setUpgradeHeaders() append a wrong 'upgrade'.

### ISSUE THREAD

**Issue by trustin** [netty/netty#4508]
See [here](https://github.com/netty/netty/blob/92dee9e500bc141162e6c3a6ef91d8d22e50c449/codec-http/src/main/java/io/netty/handler/codec/http/HttpClientUpgradeHandler.java#L231).

It has to be `HttpHeaderValues.UPGRADE` instead. Most servers should be OK with `HttpHeaderNames.UPGRADE` because they do case-insensitive comparisons, but some (e.g. Jetty) requires it to be `Upgrade` (no lowercase u).

**Comment by Scottmitch** [comment]
Seems like we should use `HttpHeaderValues` here. The specification calls out the lowercase variant [1]. Should we change `HttpHeaderValues.UPGRADE` to lowercase, and should/are we using case insensitive compare when evaluating this header value?

[1] https://tools.ietf.org/html/rfc7230#section-6.7

> When Upgrade is sent, the sender MUST also send a Connection header
   field (Section 6.1) that contains an "upgrade" connection option

**Comment by trustin** [comment]
We are using case-insensitive comparison, which is fine in my opinion. (more tolerating)

Jetty uses case-sensitive comparison and expects `Upgrade`, which seems incorrect. (They just do `.contains()` on a `List<String>` IIRC.)

So, we could:

- Use `HttpHeaderValues.UPGRADE` instead,
- Change it from `Upgrade` to `upgrade`, and
- Ping the Jetty folks about this so they fix this or they have a chance to disagree.

**Comment by trustin** [comment]
Here's the code that uses `.contains("Upgrade")`: 

https://github.com/eclipse/jetty.project/blob/65d33f8b49bd51140d9fe9b024c5dd42ad7571d8/jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannelOverHttp.java#L373

`git blame` tells @gregw could help us here.

**Comment by gregw** [comment]
@trustin Ooops that looks wrong.  Fixing now..... standby.....

**Comment by Scottmitch** [comment]
@trustin Thanks for confirming we use case-insensitive compare. I agree we should change `HttpHeaderValues.UPGRADE` to lowercase, and use it here.

@gregw - Thanks for the fix!

**Comment by gregw** [comment]
@trustin @Scottmitch   Fix is committed to jetty 9.3 and master branches: https://bugs.eclipse.org/bugs/show_bug.cgi?id=483039

**Comment by normanmaurer** [comment]
@gregw thanks!

@Scottmitch should I take care ?

**Comment by Scottmitch** [comment]
@normanmaurer - Sure. Thanks!

**Comment by normanmaurer** [comment]
Ok working on a fix
