### ISSUE TITLE
HTTP Proxy support in Netty client 4.0.

### ISSUE THREAD

**Issue by iuliandolceanu** [netty/netty#4521]
Hello,

I see that proxy support is implemented for Netty 4.1, but not for Netty 4.0. an you please add the functionality in the 4.0 version's future release, too, please? We cannot use Netty 4.1 at the time, because of its Beta status.

Thank you,
Iulian

**Comment by Scottmitch** [comment]
With 4.1's release being relatively near term I'm not sure this is worth the effort. @normanmaurer @trustin - WDYT?

**Comment by iuliandolceanu** [comment]
What would the term be? I didn't find anything related to it anywhere on the Netty page.

**Comment by normanmaurer** [comment]
This year.

**Comment by normanmaurer** [comment]
Nope let us just release 4.1

**Comment by iuliandolceanu** [comment]
OK. I'll keep my eyes open for the stable release of 4.1.

Thanks!
Iulian

**Comment by iuliandolceanu** [comment]
Hi,

Sorry to bother, but it's 2016 and 4.1 is not marked as stable yet. Do you have a better estimate, or a way for us to track progress?

Thanks!

**Comment by Scottmitch** [comment]
Soon :smile:. Have you gone through the process of upgrading yet? I expect interfaces should be relatively stable in codec-http.

**Comment by iuliandolceanu** [comment]
No, not yet. We want to be sure before upgrading, so we decided to wait on it. Hopefully, it will not be too long. :smile:

**Comment by Scottmitch** [comment]
@iuliandolceanu - Since the plan has not changed (release of 4.1 should satisfy this issue) I will close for now. Stay tuned for 4.1!
