### ISSUE TITLE
QueryStringDecoder: plus sign in query strings ('+' as well as '%2B') corrupts unrelated non-ascii characters (netty 3.9)

### ISSUE THREAD

**Issue by besief** [netty/netty#4530]
Using netty 3.9.9.Final.

QueryStringDecoder replaces unescaped non-ascii characters with other characters, if a plus sign is part of the parameter’s value as well.
For example, the ™ character gets replaced with " (that's an ASCII double-quote).

Consider these simple test cases:
`new QueryStringDecoder("/s?q=+foo™").getParameters().get("q").get(0);`
Produces `" foo\""`.

`new QueryStringDecoder("/s?q=™foo%2B").getParameters().get("q").get(0);`
Produces `"\"foo+"`.

But:
`new QueryStringDecoder("/s?q=™foo").getParameters().get("q").get(0);`
Produces `"™foo"`.

But:
`new QueryStringDecoder("/s?q=™foo&w=bar++").getParameters().get("q").get(0);`
Produces `"™foo"` as well.

Other non-ascii characters behave similarly. The next one after '™', which is '℣', gets replaced with '#', then the next one ('ℤ') is replaced with '$' etc. I think that’s a clear pattern. :)

Now I understand that these non-ascii chars shouldn’t be in a URL to begin with, but unrelated parts of the string (it does not matter how far the '+' and other chars are apart, as long as they are part of the same parameter) triggering a certain misbehaviour is rather hard to see through.

**Comment by normanmaurer** [comment]
Please test again with latest 3.10.x release and reopen if you still see the issue.
