### ISSUE TITLE
RuleBasedIpFilter can not reject connection

### ISSUE THREAD

**Issue by p0mp0k0** [netty/netty#4531]
I used RuleBasedIpFilter to reject some remote IP's connection, but sometimes the reject action do not success. I create a class MyIPFilter extends from RuleBasedIpFilter and override the channelRejected to print some information like "channelRejected", and I found the "channelRejected" was printed, so I think accept function tested the reject rule and return false, but the decoder in pipeline after MyIPFilter always be fired and throw the exception when I readBytes from in buffer in decode function. If I add a customer handler extends from ChannelInboundHandlerAdapter after RuleBasedIpFilter, sometimes the new handler will call exceptionCaught with exception "connection close by peer".
What happened or why this happened? Does this is a issues?
All of 4.0.31,4.0.32,4.0.33 have this problem.

**Comment by normanmaurer** [comment]
Can you show us the exact code ?

Also the connection close by peer can happen if the remote peer closed the exception in between.

**Comment by p0mp0k0** [comment]
Thank for your reply.
I wrote a question at stackoverflow, but there was nobody answer from then on. There had detail code and echo information, url is http://stackoverflow.com/questions/34026784/same-ip-block-code-using-netty-rulebasedipfilter-but-one-is-success-another-fai

**Comment by p0mp0k0** [comment]
The exceptionCaught is not occur everytime. Besides, not all of the pipeline, which has DelimiterBasedFrameDecoder, work fine, some reject and stop fire to next decoder, others reject but still fire to next decoder.

**Comment by normanmaurer** [comment]
I will close this for now. If you still think there is an issue please reopen with more infos
