### ISSUE TITLE
"handlerRemoved" method not ivoked when ReadTimeoutHandler is removed from pipeline

### ISSUE THREAD

**Issue by doom369** [netty/netty#4534]
Hello. Netty 4.0.33. Use case :

I'm creating pipeline with new ReadTimeoutHandler(15). Also I have a logic in pipeline, so when user want yo change 15 sec to something else :

```
        if (newHardwareInterval > 0) {
            ctx.pipeline().remove(ReadTimeoutHandler.class);
            ctx.pipeline().addFirst(new ReadTimeoutHandler(newHardwareInterval));
        }
```

The problem is - after removing old handler timeout is still 15 sec and my connection is dropped. While new interval I'm passing is 60 secs.

Question is - does remove from pipeline should call "handlerRemoved", I read docs and according to them - it should. Am I wrong?

**Comment by normanmaurer** [comment]
Did you close this by mistake?

**Comment by doom369** [comment]
No. Problem was in my code.

**Comment by normanmaurer** [comment]
Thx for clearify!
