### ISSUE TITLE
Inconsistent pooled memory usage (can lead to OOM)

### ISSUE THREAD

**Issue by slandelle** [netty/netty#4544]
Netty 4.0.33.Final
OSX 10.11.1
Hotspot 1.8.0_66

I have a custom `ChunkedInput` that can get fed externally. I found out that memory usage can be pretty different depending on the queue used between the single producer and the single consumer (the Netty IO thread). Native memory usage can be as low as the initial 16Mb, or skyrocket to several 100Mb, or even crash with OOM.

Please check [this pure Netty based test case](https://github.com/slandelle/netty-native-mem-usage).

Note that I never had any issue with unpooled memory, so this definitively has to do with pooled memory recycling.

Here's some results I got on my machine (but the ABQ ones can vary):
```
testFairABQWithPut
Test completed in 75s
>>>Direct buffers count=4 capacity=16Mb used=16Mb

testUnfairABQWithPut
Test completed in 69s
>>>Direct buffers count=9 capacity=96Mb used=96Mb

testSPSC
Test completed in 39s
>>>Direct buffers count=4 capacity=16Mb used=16Mb

testUnfairABQWithOffer
Test completed in 57s
>>>Direct buffers count=4 capacity=16Mb used=16Mb
```

Plugging a monitoring tool during the run can make the memory usage skyrocket.

I don't really get how memory usage can grow this way in a SPSC scenario. If this is not an issue, could you please explain?

Thanks!

**Comment by normanmaurer** [comment]
@slandelle I will try to have a look soon.

**Comment by slandelle** [comment]
@normanmaurer Thanks.

**Comment by ihor-mielientiev-epam** [comment]
@normanmaurer do you have any updates about this issue?

**Comment by mielientiev** [comment]
@normanmaurer Do you have any updates about this issue?

**Comment by normanmaurer** [comment]
@slandelle @mielientiev to make it short, no :( I had no time yet.

**Comment by normanmaurer** [comment]
@slandelle can you give some more infos on how I should run this etc ?

**Comment by slandelle** [comment]
`mvn test`, https://github.com/slandelle/netty-native-mem-usage/blob/master/src/test/java/io/gatling/issues/NativeMemUsageTest.java is a JUnit based test.

**Comment by slandelle** [comment]
I tend to run the different tests in this class separately in my IDE.

**Comment by normanmaurer** [comment]
@slandelle you missed to release a `ByteBuf` here:

https://github.com/slandelle/netty-native-mem-usage/blob/master/src/test/java/io/gatling/issues/bodyfeed/BodyChunkedInput.java#L34

After I added a release() I never was able to reproduce a OOME. This was easy to discover by using `ResourceLeakDetector.setLevel(Level.ADVANCED)` btw ;)

**Comment by slandelle** [comment]
Thanks a lot!
