### ISSUE TITLE
Netty 4.1 generates the XxxObjectHashMapTest.java to the wrong package?

### ISSUE THREAD

**Issue by ThomasLau** [netty/netty#4546]
hi,when i update my branch to netty4.1,i get some compile errors:

<img width="171" alt="netty-4-1-2015-12-09" src="https://cloud.githubusercontent.com/assets/5381740/11678939/62fa71a6-9e87-11e5-9ea7-0e57f908768d.png">

(i  use maven 3.3.3, Mac OS)

i guess that is because we should move "templates/io.netty.util.collection/KObjectHashMapTest.template"
to 
"templates/io/netty/util/collection/KObjectHashMapTest.template"
,but i'm not sure about it, or did i missed something?

**Comment by Scottmitch** [comment]
@ThomasLau - Thanks for reporting! Sounds reasonable to me.

@nmittler - Would you mind taking care of this one?

**Comment by nmittler** [comment]
doh! yeah I'll send a PR shortly...

**Comment by nmittler** [comment]
Just created #4569

**Comment by ThomasLau** [comment]
@nmittler yeah , got it! Maven will compile **io.netty.util.collection/A.java** into **io/netty/util/collection/A.class** correctly, but eclipse-jdt will take it as a compile error.
this may because **javac** compiles io.netty.util.collection/A.java into io.netty.util.collection/A.class, but running **java io.netty.util.collection.A** may lead to a rumtime error.
