### ISSUE TITLE
ByteBufUtil allocates significant memory for hey dump facilities even when not used

### ISSUE THREAD

**Issue by CodingFabian** [netty/netty#4558]
About 200k of memory are allocated for the various hexDump helpers in ByteBufUtil, even when the application doesn't use them, because they are static in ByteBufUtil which is more likely to be used.

Could we move the actual dump preparation to separate class, so that it is only initialized if actually used?
so like:
```
 public static String hexDump(ByteBuf buffer, int fromIndex, int length) {
   ByteBufHexDumpUtil.hexDump(buffer, fromIndex, length);
 }
```

This will delay the static initializer.

**Comment by CodingFabian** [comment]
I can submit a PR if the idea is approved

**Comment by normanmaurer** [comment]
@CodingFabian yes please :) Thanks a lot!

**Comment by CodingFabian** [comment]
whoopsie, wrong target :-) Feel free to let me know what you think. I could also move it to separate class, but wanted to keep API identical.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4560
