### ISSUE TITLE
Question: ReferenceCounted.retain(void/int) have nearly identical impls

### ISSUE THREAD

**Issue by kevinarpe** [netty/netty#4561]
Hello,

I assume there is some history behind this code.  At first blush, a developer / reader says: "Hey, that's duplicated code."  Can you explain why `ReferenceCounted.retain(void)` and `retain(int)` have nearly identical impls in `AbstractReferenceCounted` and `AbstractReferenceCountedByteBuf`?

(There is similar overlap for `ReferenceCounted.release(void)` and `release(int)`.)

Sample code from 4.0.33.Final / `AbstractReferenceCountedByteBuf`:
```java
    @Override
    public ByteBuf retain() {
        for (;;) {
            int refCnt = this.refCnt;
            if (refCnt == 0) {
                throw new IllegalReferenceCountException(0, 1);
            }
            if (refCnt == Integer.MAX_VALUE) {
                throw new IllegalReferenceCountException(Integer.MAX_VALUE, 1);
            }
            if (refCntUpdater.compareAndSet(this, refCnt, refCnt + 1)) {
                break;
            }
        }
        return this;
    }

    @Override
    public ByteBuf retain(int increment) {
        if (increment <= 0) {
            throw new IllegalArgumentException("increment: " + increment + " (expected: > 0)");
        }

        for (;;) {
            int refCnt = this.refCnt;
            if (refCnt == 0) {
                throw new IllegalReferenceCountException(0, increment);
            }
            if (refCnt > Integer.MAX_VALUE - increment) {
                throw new IllegalReferenceCountException(refCnt, increment);
            }
            if (refCntUpdater.compareAndSet(this, refCnt, refCnt + increment)) {
                break;
            }
        }
        return this;
    }
```

**Comment by ninja-** [comment]
@kevinarpe this is to ensure maximum perf. and don't depend on inlining

**Comment by kevinarpe** [comment]
Ok, thanks.

**Comment by buchgr** [comment]
@kevinarpe i wouldn't take ninjas word for it :). might just be duplicated code that evolved over time. 

For such questions I would recommend sending them to the mailing list or opening a PR to fix it and see what people respond in code review. :-).
