### ISSUE TITLE
`org.tukaani.xz` should have `test` scope

### ISSUE THREAD

**Issue by jchambers** [netty/netty#4562]
[`org.tukaani.xz`](https://github.com/netty/netty/blob/dc13a10e7783dfb461a58e431098617a191afd1e/pom.xml#L913) appears to be a test dependency, but is included in the default (`compile`) scope in `master`, `4.0`, and `4.1.`

**Comment by slandelle** [comment]
You're referring to the dependencyManagement block, not the dependencies one.
`org.tukaani/xz` is only fetched from the test-suite module, so Netty runtime artifacts don't fetch it.

**Comment by jchambers** [comment]
Oops—my mistake!
