### ISSUE TITLE
ByteBuf#writeBytes(java.nio.ByteBuffer) can fail when ByteBuffer is read-only.

### ISSUE THREAD

**Issue by kevinherron** [netty/netty#4563]
If you try writing a read-only `java.nio.ByteBuffer` into a certain implementations of `ByteBuf` using `ByteBuf#writeBytes(java.nio.ByteBuffer)` a `java.nio.ReadOnlyBufferException` is thrown.

It seems at the very least `PooledUnsafeDirectByteBuf` is susceptible:

```scala
  val byteBuf = PooledByteBufAllocator.DEFAULT.buffer()

  val byteBuffer = ByteBuffer
    .wrap(Array[Byte](1, 2, 3, 4))
    .asReadOnlyBuffer()

  byteBuf.writeBytes(byteBuffer)
```

Results in:

```
Exception in thread "main" java.nio.ReadOnlyBufferException
	at java.nio.ByteBuffer.array(ByteBuffer.java:996)
	at io.netty.buffer.UnsafeByteBufUtil.setBytes(UnsafeByteBufUtil.java:368)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:205)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:877)
	at io.netty.buffer.WrappedByteBuf.writeBytes(WrappedByteBuf.java:637)
```

It looks like `UnsafeByteBufUtil` assumes `java.nio.ByteBuffer#array()` will always succeed, rather than checking `hasArray()` first.

**Comment by normanmaurer** [comment]
Thanks for reporting, will fix 👍

**Comment by kevinherron** [comment]
It seems this was fixed in f3f49c91fd3a72f6f7049023c276f6772ebbf159 in November... Sorry for the un-necessary report!

**Comment by normanmaurer** [comment]
@kevinherron thanks... working on a fix as we speak.

**Comment by normanmaurer** [comment]
@kevinherron that said `UnsafeByteBufUtil#getBytes(...)` will act correctly as it will throw an java.nio.ReadOnlyBufferException on array(). But there is another problem as we may allow to write to the buffer if its direct even if its read-only....

**Comment by normanmaurer** [comment]
Not an issue as explained before
