### ISSUE TITLE
AsciiString.contentEqualsIgnoreCase does not work correctly for AsciiString comparison

### ISSUE THREAD

**Issue by blucas** [netty/netty#4564]
Netty Version: master (6c0fef133baa4afce11953110a6947732d87ec8e)

```AsciiString.contentEqualsIgnoreCase``` fails when checking for equality between two ```AsciiString``` objects. For example 
```java
// returns true, should return false 
new AsciiString("foo").contentEqualsIgnoreCase(new AsciiString("bar"));
```
The issue is due to [the following line](https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/AsciiString.java#L533)

I think I've tracked this down to the following commit: https://github.com/netty/netty/commit/ba6ce5449ee852b782dde9a11933f6a09b123e22

Pull request to follow

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4565
