### ISSUE TITLE
Monitor DnsNameResolver actual resolutions

### ISSUE THREAD

**Issue by slandelle** [netty/netty#4568]
I'd like to be able to monitor every actual resolution: when an uncached resolution happened, which host and how long it took.

I see 2 possibilities:
- make some DnsNameResolver internals protected instead of private or package private so it can be extended
- make DnsNameResolver take an optional Listener

Please let me know which option you'd like and I'll provide a PR.

Thanks!

**Comment by normanmaurer** [comment]
@slandelle i think this is possible now. Please check and re-open if the support we added is not good enough

**Comment by slandelle** [comment]
Yes, I'll give the new `DnsQueryLifecycleObserver` API a try and report if it's lacking. Thanks a lot!

**Comment by slandelle** [comment]
@normanmaurer @Scottmitch Correct me if I'm wrong, but `DnsQueryLifecycleObserver` scopes every individual query, so it's not possible to get the global picture for the whole name resolution.

**Comment by Scottmitch** [comment]
@slandelle - I'm not exactly sure what you are trying todo but IIRC for each user initiated query [DnsQueryLifecycleObserverFactory](https://github.com/netty/netty/blob/4.1/resolver-dns/src/main/java/io/netty/resolver/dns/DnsQueryLifecycleObserverFactory.java#L31) is used to get a new `DnsQueryLifecycleObserver`, and then for the lifecycle of that query there are factory methods where your implementation of `DnsQueryLifecycleObserver` can return a new `DnsQueryLifecycleObserver` and track the entire query stats at the "parent" level, or you can just return the same object. For example see [DnsQueryLifecycleObserver#queryRedirected](https://github.com/netty/netty/blob/4.1/resolver-dns/src/main/java/io/netty/resolver/dns/DnsQueryLifecycleObserver.java#L66) ... is this useful?

**Comment by slandelle** [comment]
@Scottmitch Thanks for your help.

> I'm not exactly sure what you are trying to do

I'm trying to measure actual (not cached) hostname resolution overall duration.

I think `DnsQueryLifecycleObserverFactory` almost works for me, except that when resolving both IPv4 and IPv6, you create 2 `DnsQueryLifecycleObserver` instances that can't be easily correlated when performing multiple resolutions concurrently.

I guess I would either need a higher level component that would be instantiated only once per resolve call (a DnsResolutionObserverFactory :P ), or a resolution correlation id that would be passed `DnsQueryLifecycleObserverFactory#newDnsQueryLifecycleObserver`.

WDYT?

**Comment by Scottmitch** [comment]
> I'm trying to measure actual (not cached) hostname resolution overall duration.

The creation of a `DnsQueryLifecycleObserver` should be after the cache lookup fails.

> The problem is that multiple DnsQueryLifecycleObserverinstances can be created per resolution

I see. It is possible to get different behavior between the different queries. Can you provide some additional motivation for the benefits of being able to correlate these two events?

>  guess I would either need a higher level component that would be instantiated only once per resolve call (a DnsResolutionObserverFactory :P ), or a resolution correlation id

Makes sense ... I don't have a strong preference but the correlation ID would require some sort of map which may need to be concurrent. Because of this I would prefer the first approach.

**Comment by slandelle** [comment]
I want to break down total request-response duration into DNS resolution time, TCP connect duration, TLS handshake duration and HTTP response time. I don't want to count DNS cache look up. My current hack involves hacking the protected doResolveAll method and passing a custom one time cache that wraps the actual one and measure time between lookup failure and put.

This is super hacky and brittle, so I'd rather have a real API :)
Then maybe having caching concern extracted from DnsNameResolver and moved to a dedicated helper would help.

**Comment by Scottmitch** [comment]
Sounds like you want to be able to specify a `DnsQueryLifecycleObserverFactory` per `resolve` call?

> Also, DnsNameResolver + DnsNameResolverContext are growing huge. Wouldn't they be better implemented as Netty handlers?

Perhaps, but this is a separate discussion.

**Comment by slandelle** [comment]
> Sounds like you want to be able to specify a DnsQueryLifecycleObserverFactory per resolve call?

That could be a plan, yes!

**Comment by normanmaurer** [comment]
@Scottmitch gimme till tomorrow to think about it... my brain declared bankruptcy a few minutes before ;)
