### ISSUE TITLE
Using "global" class instances

### ISSUE THREAD

**Issue by guilhermecl** [netty/netty#4570]
I just started the implementation of a TCP server, and this is my first experience with Netty.

I want to instance a class and use it in the entire Netty aplication, sharing it between the connection threads.
Is it correct to do this in Netty? Or, at every new client connected at the server, I must instantiate new classes?
If it is OK to do this, then where should I put the code to instance the classes? and how do I pass them to the channels?

Thank you very much.

**Comment by normanmaurer** [comment]
Just create it and inject it to the ChannelHandler in the constructor ?
