### ISSUE TITLE
Http2ConnectionHandler builder API design issues

### ISSUE THREAD

**Issue by trustin** [netty/netty#4572]
I see the following design issues with the builder API of `Http2ConnectionHandler`.

- A user might want to extend `Http2ConnectionHandler` and define his/her own static inner `Builder` class that extends `Http2ConnectionHandler.BuilderBase`. This introduces potential confusion because there's already `Http2ConnectionHandler.Builder`. Your IDE will warn about this name duplication as well.
- `BuilderBase` exposes all setters with `public` modifier. A user's `Builder` might not want to expose them to enforce it to certain configuration. There's no way to hide them because it's public already and they are final.
- `BuilderBase.build(Http2ConnectionDecoder, Http2ConnectionEncoder)` ignores most properties exposed by `BuilderBase`, such as `validateHeaders`, `frameLogger` and `encoderEnforceMaxConcurrentStreams`. If any `build()` method ignores the properties exposed by the builder, there's something wrong.
- A user's `Builder` that extends `BuilderBase` might want to require more parameters in `build()`. There's no way to do that cleanly because `build()` is public and final already.

**Comment by trustin** [comment]
If there's no objection, I'll come up with a fix PR for this.

**Comment by Scottmitch** [comment]
@trustin - Improvements are always welcome. Any details for how you will improve the last 2 bullet points?

**Comment by trustin** [comment]
@Scottmitch I'd like to remove the build methods or to make them protected in BuilderBase so that Builder implementations choose to expose what/which build methods. Let me take a quick stab on this some time this week.

**Comment by Scottmitch** [comment]
@trustin - So multiple builders each with 1 `build` method, instead of 1 builder with multiple `build` methods?

**Comment by trustin** [comment]
@Scottmitch I think it depends on the builder implementation. What I mean is it's just not what BuilderBase has to enforce.

**Comment by trustin** [comment]
@Scottmitch Ended up with 1 builder with 1 build() method with some state validation - #4574

**Comment by normanmaurer** [comment]
@trustin I think this can be closed ?

**Comment by trustin** [comment]
@normanmaurer hell yeah :-)
