### ISSUE TITLE
State of Alpha 5.0alpha3 release?

### ISSUE THREAD

**Issue by AlainRoy** [netty/netty#4586]
Hi,

I'm working on a project that is using Netty 5.0alpha2: https://github.com/vmware/xenon

We're adding HTTP/2 support, and I hit a bug that is pretty serious for us. Fortunately it was fixed in alpha3. I verified that the latest snapshots of alpha3 work for us. The bug is: 
https://github.com/netty/netty/commit/44ee2cac433a6f8640d01a70e8b90b70852aeeae

We'd love to use Netty 5.0alpha3, but I'm reluctant to depend on a snapshot since unexpected changes could break us. 

Do you have an estimated date for a 5.0alpha3 release? 

Thanks!

**Comment by normanmaurer** [comment]
@AlainRoy we not plan to do any new 5.0alpha releases at any time soon. Please use 4.1.0.Beta8.

**Comment by normanmaurer** [comment]
@AlainRoy btw you may also want to add vmware to the adopters page :)

http://netty.io/wiki/adopters.html

**Comment by AlainRoy** [comment]
Sure, I can do that. 

Is the HTTP/2 support in 4.1alpha 8 stable?

**Comment by normanmaurer** [comment]
yes

**Comment by AlainRoy** [comment]
Excellent, thanks. I updated the adopters page on the Github wiki--that seemed like the right place to do it. 

I'll give Netty 4.1a8 a shot.
