### ISSUE TITLE
HTTP/2 DefaultHttp2RemoteFlowController Stream writability notification broken

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4587]
`DefaultHttp2RemoteFlowController.ListenerWritabilityMonitor` no longer reliably detects when a stream's writability change occurs. `ListenerWritabilityMonitor` was implemented to avoid duplicating iteration over all streams when possible and instead was relying on the `PriorityStreamByteDistributor` to call `write` for each stream during its iteration process. However the new `StreamByteDistributor` classes do not do an iteration over all active streams and so this assumption is now invalid.

The impact is isolated to stream writability change notifications and has no impact unless you explicitly add a listener, and use an allocator other than `PriorityStreamByteDistributor`.

**Comment by Scottmitch** [comment]
@nmittler - FYI

**Comment by nmittler** [comment]
@Scottmitch good find! Any thoughts on a fix?

**Comment by Scottmitch** [comment]
@nmittler - Yes. See https://github.com/netty/netty/pull/4599
