### ISSUE TITLE
HTTP/2 UniformStreamByteDistributor can get into an infinite loop

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4588]
UniformStreamByteDistributor loops over a queue until empty. It is possible for a stream state to continuously be added to a the queue and cause this loop to continue indefinitely.

A state is popped off the queue, and written. During that write process the `updateStreamableBytes` method is called by the flow controller. If `hasFrame()` returns true, then the state is enqueued. If the connection window is larger than the stream window, it is possible that the stream's window has become collapsed such that `streamableBytes` goes to 0 but `hasFrame()` will return true. An exit criteria on the loop is to check for `maxBytes` transitioning to zero, but this may never happen if the streams can not consume all of the connection window, and so the loop will never terminate.

This was discovered as part of the fix for https://github.com/netty/netty/issues/4587.

**Comment by Scottmitch** [comment]
I ran into this issue while attempting to use `UniformStreamByteDistributor ` in `DefaultHttp2RemoteFlowControllerTest`...which was done as part of the PR for #4587.

**Comment by Scottmitch** [comment]
@nmittler - FYI

**Comment by nmittler** [comment]
@Scottmitch good find!  Do you have a PR pending?

**Comment by Scottmitch** [comment]
@nmittler - Yes. #4599.

**Comment by Scottmitch** [comment]
Resolved with https://github.com/netty/netty/issues/4599
