### ISSUE TITLE
HTTP/2 RemoteFlowController$Listener.streamWritten

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4600]
We should evaluate whether [Http2RemoteFlowController$Listener.streamWritten](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2RemoteFlowController.java#L151) is necessary. If not we should remove it.

**Comment by Scottmitch** [comment]
@louiscryan @nmittler @ejona86 - I checked in gRPC and it looks like this is still not being used? Is the plan still to use this or eventually consume the stream writability changes?

**Comment by louiscryan** [comment]
So far it has not proven critical to performance and there are other perf improvements I would prioritize in GRPC above the use-case for this, particularly with the improvements in flow-control write allocations and frame merging.

Im OK with getting rid of this

**Comment by Scottmitch** [comment]
after we get PR https://github.com/netty/netty/pull/4599 pulled in I'll submit a PR for this.

**Comment by louiscryan** [comment]
Thanks Scott
