### ISSUE TITLE
isKeepAlive is not supported by Epoll

### ISSUE THREAD

**Issue by vrozov** [netty/netty#4604]
Calling isKeepAlive throws an exception

```
java.lang.UnsatisfiedLinkError: io.netty.channel.epoll.Native.isKeepAlive(I)I
	at io.netty.channel.epoll.Native.isKeepAlive(Native Method)
	at io.netty.channel.epoll.EpollSocketChannelConfig.isKeepAlive(EpollSocketChannelConfig.java:154)
```

**Comment by normanmaurer** [comment]
Sounds like an issue with loading the jni stuff. Can you show me how you specify the dependencies ?

**Comment by vrozov** [comment]
```
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-all</artifactId>
      <version>5.0.0.Alpha2</version>
      <scope>test</scope>
    </dependency>
```
it works if I comment out isKeepAlive() call. I think the problem is that isKeepAlive is missing in io_netty_channel_epoll_Native.h

**Comment by normanmaurer** [comment]
@vrozov please use 4.0.33.Final or 4.1.0.Beta8. It should work there. If not re-open

**Comment by normanmaurer** [comment]
Actually It seems like there is still the bug. Reopen now

**Comment by normanmaurer** [comment]
@vrozov fixed via https://github.com/netty/netty/pull/4619

**Comment by normanmaurer** [comment]
Fixed
