### ISSUE TITLE
Http gzip/deflate compression rules on the server side

### ISSUE THREAD

**Issue by kyankovski** [netty/netty#4608]
Hi Norman!

We are using/developing netty4.0-based high-load http server in our project and now we need to add gzip and deflate compression/decompression. That was easy to add such a feature (so it's working pretty well), but I have a question and would like to discuss it.

The question is about _io.netty.handler.codec.http.HttpContentCompressor#determineWrapper_ implementation. This method takes into account just a value from _"Accept-Encoding"_ request's header, but completely ignores _"Content-Encoding"_ request's header.

So I see there 2 issues:

##### --- ISSUE 1 ---
Client sends deflate-compressed request with the following headers:
```
Content-Encoding: deflate
Accept-Encoding: deflate, gzip
Content-Length: 1234
``` 
If I understand the http/1.1 specification correctly, it's an absolutely legal case to send such requests. The first header tells what kind of compression was used for this particular request, the second one tells which content-codings are acceptable for the client.
Response in this case will be compressed using 'gzip' algorithm, but not 'deflate' (as was request) because _qvalue_ is not defined for both 'deflate' and 'gzip' in the _'Accept-Encoding'_ header. So the default compressor (gzip) will be used (_HttpContentCompressor_ will choose it).

According to [HTTP/1.1 specification, section 14.3](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html) described case-1 is legal because the spec tells us how to choose an appropriate encoding based on _qvalue_ (_"3. If multiple content-codings are acceptable, then the acceptable content-coding with the highest non-zero qvalue is preferred."_) and do not say what to do if _qvalue_ is the same for several content-codings or is not declared at all. So netty's _HttpContentCompressor_ choose the default compressor - gzip.

In my humble opinion it will bemore logical to choose not the default netty's compressor (gzip) but look at _"Content-Encoding"_ header and send the response compressed with the same compression algorithm (deflate in this example). It will be also a valid behavior according to HTTP/1.1 spec (it tells nothing about missed _qvalue_). And it will be more predictable behavior for the client. The netty-based server should not worry that non-default compressor is used - the client said that both deflate and gzip are supported.

##### --- ISSUE 2 --- 
Client sends compressed request without "Accept-Encoding" header as in example below:
```
Content-Encoding: gzip
Content-Length: 1234
```

In this case  _io.netty.handler.codec.http.HttpContentCompressor_ wan't apply any compression for the response, but in my humble opinion that is not the best behavior.

According to [HTTP/1.1 specification, section 14.3](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html):
> "If no Accept-Encoding field is present in a request, the server MAY assume that the client will accept any content coding. In this case, if "identity" is one of the available content-codings, then the server SHOULD use the "identity" content-coding, unless it has additional information that a different content-coding is meaningful to the client."

So I think in such a case HttpContentCompressor should look not just at _"Accept-Encoding"_ but also at _"Content-Encoding"_ request's header and choose the same compression for the response that was used in the request. The server(netty) should not worry that compressed response won't be recognized by the client because:
1) The client used the same compression algorithm to send the request. So the server (netty) may suggest that the client will be able to decompress it as well.
2)  HTTP/1.1 spec says: _"If no Accept-Encoding field is present in a request, the server MAY assume that the client will accept any content coding."_

In my humble opinion that is more logical to answer using the same compression that was used in the request in case when _"Accept-Encoding"_ header is not defined (gzip in my example).

---------

What do you think about it? Do you agree to apply such a change to the netty distribution?

Thanks,
Konstantin

**Comment by slandelle** [comment]
ASAIK, Netty doesn't support request compression, neither on the client side, nor on the server one.

**Comment by kyankovski** [comment]
@slandelle of course it does.
io.netty.handler.codec.http.HttpContentDecompressor - unpacks gzip/deflate compressed request
io.netty.handler.codec.http.HttpContentCompressor - compresses response using gzip/deflate algorithm

**Comment by slandelle** [comment]
ok, so that's just client side request compression that's not implemented.

**Comment by kyankovski** [comment]
I had a meeting with our system architect (in my company) just an hour ago. He disagrees with my positition and agrees that the current _io.netty.handler.codec.http.HttpContentCompressor#determineWrapper_ implementation fully covers http/1.1 specification and my suggestion to look at _"Content-Encoding"_ request's header is based only on assumptions what the client wants. So the best behavior is the current - look at _"Content-Encoding"_ only.
Sorry for this issue. And thank you for your work and the excellent product.
