### ISSUE TITLE
Message size estimation issues

### ISSUE THREAD

**Issue by technocoreai** [netty/netty#4615]
#4380 introduced message size estimation for messages written outside the event loop. However, the implementation is problematic and leads to more problems than it solves. For example, our software uses writability checks to determine if it should start dropping events, and after updating to 4.0.33 we've got massive drops even though the TCP send buffer never goes above 10–20% of the configured `highWatermark` value.

I see the following problems with the current solution:

1. It pollutes *every single thread* writing to a Netty channel with a thread-local map used for caching message sizes. That's not very significant, since usually writes are done from a limited-size thread pool, but it's still not very tidy.
2. It doesn't take into account JVM flags. We're running with `CompressedOOPS`, but every single reference is still counted as 8 bytes instead of 4. Again, insignificant, but pretty much doubles the size of most estimated classes.
3. And, finally, the most important one: the message size estimations are **very** wrong. A basic `WriteAndFlushTask`, for example, is estimated as a whopping `1272` bytes for me, and most of it (`1192` bytes) is from the `ctx` variable which is shared between all outbound messages and so shouldn't be counted.

**Comment by Scottmitch** [comment]
@technocoreai - Would a pluggable size estimator as suggested in https://github.com/netty/netty/pull/4380#discussion_r42958184 address your concerns?

**Comment by technocoreai** [comment]
@Scottmitch: The user-provided size estimator assigned to the channel is already used in the size calculation. Netty then uses *another* estimation algorithm to figure out the size of its internal classes and this one is off by ~20x. I don't think it's a good idea to have such a broken implementation by default and make the users override it with something pluggable if they want to avoid this, besides, the mis-estimated classes are private to Netty so it'll be pretty hard to implement.

Implementing a generic message size estimation algorithm looks like an impossible task to me, since Netty has no idea whether the references it encounters will shared between different messages or not, or what sizes will their fields have. I'd remove the current brittle reflection-based code and either ignored the `AbstractWriteTask` overhead at all or hardcode some sensible default value (16 bytes for the header, 24 bytes for the various fields, plus whatever the user-provided estimator returns for `msg`).

**Comment by sirmax** [comment]
Also note that the whole `if (o instanceof …)` block in [`estimateSize(o, classSizes)`](https://github.com/netty/netty/blob/netty-4.0.33.Final/transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java#L895) is a no-op. This method has two invocations: one is [recursive](https://github.com/netty/netty/blob/netty-4.0.33.Final/transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java#L912) for the contents of an `Iterable`, and another one is  [`estimateSize(task, CLASS_SIZES.get())`](https://github.com/netty/netty/blob/netty-4.0.33.Final/transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java#L968) where `task` is `AbstractWriteTask`.

Thus `estimateSize(task, CLASS_SIZES.get())` estimates the size of only two `AbstractWriteTask` sub-classes (not their instances!) – `WriteTask` and `WriteAndFlushTask`… and does it in run-time… for each thread.

**Comment by normanmaurer** [comment]
We love PRs so if you guys can think of a better implementation feel free to provide a PR. I will review them for sure :)

Thanks!

**Comment by sirmax** [comment]
@normanmaurer the point is #4380 does much more harm than good. I'd revert it, to start with, and then wait for a better PR.

Personally I think Netty shouldn't impose this kind of task size estimation at all. Netty _might_ provide ways to make it easier, but ultimately it should be up to the client code to use it or not.

**Comment by normanmaurer** [comment]
@sirmax I think we need to provide at least some kind "estimation" as otherwise it is very easy for people to OOME if they write from outside of the EventLoop. But maybe it would be just good enough to use the size of the MessageSizeEstimater +  some fixed size for each task. So basically what @technocoreai suggested.

**Comment by technocoreai** [comment]
@normanmaurer Another issue I see with the whole approach is that it breaks code that puts the various coalescing/dropping logic into Netty handlers. For example, our code currently sends updates using `channel.write()` and the handler inside switches between write-through and coalescing mode based on `channelWritabilityChanged` callbacks on the assumption that channels only become unwritable if the client or the network have problems with consuming the data. This could lead to problems if for some reason the Netty event loop got so overloaded it became unable to dequeue write tasks, but since our handlers are pretty small this never happened, and this allows us to write much less code, because the complicated coalescing-related state is hidden inside one of the handlers. Doing size estimation on the first call to `write()` makes us unable to distinguish between slow network/clients and full queues on the server-side (because of a slow handler), and we'd like to handle these cases differently.

I'm not sure what the correct solution would be, since exposing the queue size would require new callbacks/APIs, but #4380 should definitely be reverted, or at least replaced with a static size. Do you have any issues with configuring that with new system properties (e.g. `io.netty.transport.estimateSizeOnSubmit` that defaults to `true` and `io.netty.transport.writeTaskSizeOverhead` that defaults to something like 40 bytes)?

**Comment by normanmaurer** [comment]
@technocoreai no this sounds fine... Could you come up with a PR ?

**Comment by normanmaurer** [comment]
@technocoreai just to be clear the system property thing + static size.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4620
