### ISSUE TITLE
Deprecate SimpleChannelPool and introduce a replacement

### ISSUE THREAD

**Issue by trustin** [netty/netty#4625]
`SimpleChannelPool` has a few design issues:

It is tightly coupled with `Bootstrap`. `Bootstrap` does provide a way to perform post-`channelActive` operations like TLS handshake and protocol upgrades via `ChannelInitializer` and `Bootstrap.handler()`. However, a user cannot use this facility because `SimpleChannelPool` overrides `Bootstrap.handler()`. Instead a user is expected to implement the channel initialization in `ChannelPoolHandler.channelCreated()` or `SimpleChannelPool.connectChannel()`.

This is not very ideal because a user can end up with 3 places to implement channel initialization: 1) `Bootstrap` creation 2) `ChannelPoolHandler.channelCreated()` 3) `SimpleChannelPool.connectChannel()`. We need a single place to perform the core operations required for building a channel pool, so that any `ChannelPool` implementation can depend on.

Therefore, I'd like to propose to replace `ChannelPoolHandler` and `ChannelHealthChecker` with a new interface:

``` java
public interface PooledChannelFactory {
    Future<Channel> newChannel(ChannelPool pool, Promise<Channel> promise) throws Exception;
    Future<Boolean> validateChannel(ChannelPool pool, Channel channel) throws Exception;
    // Invoked when a previously released channel is about to be acquired
    Future<Void> activateChannel(ChannelPool pool, Channel channel) throws Exception;
    // Invoked when an acquired channel is returned to the pool
    Future<Void> passivateChannel(ChannelPool pool, Channel channel) throws Exception;
    // Invoked when a channel is destroyed and thus not returned to the pool
    Future<Void> destroyChannel(ChannelPool pool, Channel channel) throws Exception;
}
```

Please note that I merged `ChannelHealthChecker` into this new interface because the creation, destruction, and validation of a channel are related with each other and thus it makes sense to keep them in a single place in many cases.

Since we introduced `SimpleChannelPool` in 4.0, we cannot simply do this large surgery directly on it. Instead, I'd like to:
- Deprecate `SimpleChannelPool` and introduce `DefaultChannelPool`
- Deprecate `ChannelPoolHandler` and `ChannelHealthChecker` in favor of the new interface
- Other things to consider:
  - Does it make sense to provide unbounded pool? Perhaps we should implement a bounded pool by default. (i.e. merge `FixedChannelPool` into `DefaultChannelPool`)
  - Give a user more control over when channel validation (health check) should be done via `EnumSet`
  - Channel eviction policy, like commons-pool's `EvictionPolicy`?
    - Consider reviewing well known pool implementations configuration properties (commons-pool, HikariCP, ..)
  - We probably should write a generic asynchronous object pool first?

I'm sure this will take some time to resolve this issue properly, so I wouldn't expect this to be part of 4.1.0.Final unless we are very lucky.

**Comment by Scottmitch** [comment]
@trustin - Reworking these pools and making a more generic object pool base sgtm. We may also want to consider https://github.com/netty/netty/issues/4715 at some level too.

**Comment by ztellman** [comment]
If we're adding feature requests for a new pool implementation, I'd like to request better support for metrics, too.  While the implementation at https://github.com/ztellman/dirigiste isn't a good drop-in solution, I think all of the metrics provided there have a high degree of utility.  I was forced to effectively rewrite the channel pool to get any visibility into queue lengths or utilization.

**Comment by jchambers** [comment]
I was halfway writing a separate proposal for some incremental changes to `SimpleChannelPool` (which I may still do if it seems like this is still a long way off). Instead, please let me throw my support behind this idea.

One half-baked suggestion I can throw in (lazily skipping the part where I read up on best practices from other implementations): I wonder if pools should return some kind of `PooledResourceHolder` that implements `Autocloseable`, and closing the holder would return the pooled resource to the pool:

```java
final Future<PooledResourceHolder<Channel>> holderFuture = moreDifferentPool.acquire();

// We're just going to pretend that blocking here is a good idea
try (final PooledResourceHolder<Channel> holder = holderFuture.get()) {
    final Channel channel = holder.getResource();
    channel.write("This channel will get returned to the pool automatically by auto-closing the holder.");
}
```

Cheers!

**Comment by jchambers** [comment]
I took an [initial stab](https://github.com/netty/netty/compare/4.1...jchambers:async_object_pool) at a generic, asynchronous object pool for funsies. I took Trustin's initial suggestion pretty literally, but found that performance wasn't quite where I hoped; with a single consumer thread performing acquire/release operations as fast as it can, I hit about 50,000 operations/second.

The strategy for my initial attempt was to use an `OrderedEventExecutor` in the pool to manage concurrent access to shared resources (which is what the existing `FixedChannelPool` implementation does). A weakness with that approach is that we wind up putting a bunch of tasks into the `OrderedEventExecutor` for every acquire/release attempt. At a minimum (assuming we're calling from outside the executor):

1. An initial, caller-initiated task to get an object from an internal queue
2. A handler for the "activate" step
3. A handler for the "validate" step (possibly two if we validate on the way back in, too)
4. A caller-initiated task to begin the "release" process
5. A handler for the "deactivate" step that puts the object back into the internal queue

To improve performance, I think we need to find a way to cut down on the number of asynchronous tasks. Two proposals jump to mind:

1. Make some of the proposed `PooledChannelFactory` methods (activate/deactivate? validate?) synchronous. This definitely limits flexibility going forward, and may be flat out unacceptable for many use cases.
2. Think about an entirely different architecture. We could go to a pipeline model for preparing objects for acquisition/release. That would involve more work for implementers and would be a departure from any pool architecture I've seen, but I think it carries a number of advantages. As with channel pipelines, pool pipeline handlers could operate synchronously when possible, but still have the option to perform asynchronous tasks when needed. Pipelines could also be as long or as short as needed for a particular use case (many object pools may not need to activate/passivate objects or even perform health checks), which could save a lot of overhead in some cases.

I intend to pursue the pipeline option, but please let me know if that's _a priori_ unacceptable for some reason.

Thanks!

**Comment by normanmaurer** [comment]
Was done for 5.0
