### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by lafual** [netty/netty#4628]
Hi , the user guide only has one chapter, but refers, with out links to other chapters. Where is the full user guide?

On the document home pages http://netty.io/wiki/index.html the code example links are to "local host".. For example localhost:4242/4.0/xref/io/netty/example/telnet/package-summary.html

**Comment by Scottmitch** [comment]
Docs may be a bit limited, but we appreciate contributions.

Also I hear there was a book published recently related to this topic ... @normanmaurer maybe you have also heard this :wink:

**Comment by nemecec** [comment]
Yeah, also noticed that http://netty.io/wiki/ links to http://localhost:4242/ for all the examples.

**Comment by windie** [comment]
Saw a complaint about the links here: http://stackoverflow.com/questions/35220628/netty-server-client-framework-is-it-really-serious-project

**Comment by Scottmitch** [comment]
@normanmaurer @trustin - It seems the links are not translated from the development address to the production address

https://github.com/netty/netty-website/blob/master/wiki/index.html.haml#L61
```html
%a{ :href=>"#{r.example_url('echo')}" } Echo
```

Where `example_url` is in [pipeline.rb](https://github.com/netty/netty-website/blob/master/_ext/pipeline.rb#L74) and I'm assuming some how the [base_url: http://netty.io/](https://github.com/netty/netty-website/blob/master/_config/site.yml#L2) line is not getting mapped to `site.base_url` correctly when the release happens somewhere? Any Ideas?

**Comment by trustin** [comment]
Fixed via https://github.com/netty/netty-website/commit/07cf35126115f5b37fd8404fe88e1022642d83c0 and https://github.com/netty/netty-website/commit/07cf35126115f5b37fd8404fe88e1022642d83c0

**Comment by Scottmitch** [comment]
thanks @trustin !
