### ISSUE TITLE
TeamCity CI not building

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4632]
It seems like the rename of the `master` branch has confused the TeamCity CI server. Last build was 11 days ago.

```
Failed to start build #604 in branch 4.0 at 17 Dec 15 12:51 on debian7-1
Failed to collect changes, error: Cannot find revision of the default branch 'master' of vcs root netty {internal id=51}
View build results »Failed to start build #605 in branch 4.1 at 17 Dec 15 12:51 on debian7-1
Failed to collect changes, error: Cannot find revision of the default branch 'master' of vcs root netty {internal id=51}
VCS problem: netty
Failed for the root '"netty" {instance id=51, parent internal id=5, parent id=netty, description: "https://github.com/netty/netty.git#master"}: Cannot find revision of the default branch 'master' of vcs root netty {internal id=51}
```

**Comment by Scottmitch** [comment]
@trustin - Can you take a look?

**Comment by normanmaurer** [comment]
I will check

**Comment by Scottmitch** [comment]
thanks @normanmaurer

**Comment by normanmaurer** [comment]
@Scottmitch I think I fixed it... let us see :)

**Comment by Scottmitch** [comment]
@normanmaurer - Humm it seems like the PR builds is not running yet

```
VCS problem: pulls_netty
Failed for the root '"pulls_netty" {instance id=55, parent internal id=9, parent id=pulls_netty, description: "https://github.com/netty/netty.git#master"}: Cannot find revision of the default branch 'master' of vcs root pulls_netty {internal id=55}
```

The `sonarqube` and `nightly` builds are also not running yet, but I'm not sure if it is because there is some fixed time they are configured to run at.

**Comment by normanmaurer** [comment]
Fixed now for real... at least it seem so

**Comment by Scottmitch** [comment]
@normanmaurer - Also noticed a warning that we are using most of the available memory for `PS Old Gen` ... should/can we tweak some knobs here?

>TeamCity server memory usage for PS Old Gen pool exceeded 92% of 341 MB maximum available. 450 MB used of 509 MB total heap available. See the TeamCity [documentation](https://confluence.jetbrains.com/display/TCD9/Installing+and+Configuring+the+TeamCity+Server#InstallingandConfiguringtheTeamCityServer-SettingUpMemorysettingsforTeamCityServer) for possible solutions.

**Comment by trustin** [comment]
@Scottmitch Added `-Xmx768m' and restarted the server. Please let me know if this doesn't help. :-)

**Comment by Scottmitch** [comment]
@trustin - thanks ... warning seems gone for now.

**Comment by Avvari590** [comment]
Failed for the root '"Medworxx-PF Master" {instance id=50, parent internal id=2, parent id=Medworxx_MedworxxPfMaster, description: "http://rdtfs01:8080/tfs/BackOffice/Medworxx/_git/PF#refs/heads/master"}: List remote refs failed: Unknown host: rdtfs01
