### ISSUE TITLE
ThreadDeathWatcher watching threads it shouldn't

### ISSUE THREAD

**Issue by kdubb** [netty/netty#4638]
When using netty, via the pgjdbc-ng PostgreSQL driver, inside Tomcat it doesn't shutdown properly.  The driver has a cleanup method and we are calling.  It both shuts down the thread pool and calls ```ThreadDeathWatcher.awaitInactivity(5, TimeUnit.SECONDS)```.  The pool threads shutdown fine but ThreadDeathWatcher persists.

After inspection of the "watchees" list in ```ThreadDeathWatcher.Watcher``` I have witnessed it is watching threads from Tomcat itself; which clearly won't shutdown before our application does. The threads are a *TaskThread* named such as *Thread[http-nio-8080-exec-2,5,main].  I can only associate those with Tomcat.

The *task* variable of ```ThreadDeathWatcher.Entry``` references PoolThreadCache$1.  So I can only assume it's a lambda or internal class related to PoolThreadCache.

Two questions... first how is this happening? Seems like something must be enumerating all threads and "watching" them, regardless of who owns/created them.  Second, obviously, is how can we fix this?

Wreaks havoc on integration tests.  They take much longer than they should because it's waiting the full time to kill this thread; which never happens.  Also, it spits out errors each time Tomcat is stopped or the archive is deployed.

**Comment by kdubb** [comment]
Experienced with netty 4.0.32/33 & 4.1.0.Beta8.

Also, here's what the debugger is showing me for the ThreadDeathWatcher at the time it cannot shutdown... (all three entries are the same)
<img width="551" alt="screen shot 2015-12-29 at 11 10 37 am" src="https://cloud.githubusercontent.com/assets/787655/12039533/9e1eb8b8-ae1e-11e5-9510-e1178ebeceb9.png">

**Comment by Scottmitch** [comment]
@normanmaurer - Ping :)

[PoolThreadCache](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/PoolThreadCache.java#L121) will create a thread local associated with threads that do ByteBuf allocations ([thread = Thread.currentThread()](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/PoolThreadCache.java#L60)). It looks like this should be cleaned up when the thread local [onRemoval](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java#L374) is called.

I have just a few questions to get more info ...

> via the pgjdbc-ng PostgreSQL driver

Is this what you are referring to https://github.com/impossibl/pgjdbc-ng? Just as an experiment can you change from using [PooledByteBufAllocator](https://github.com/impossibl/pgjdbc-ng/blob/1f8cdcb6f8f75b012fb37763ea8caefd29835dd4/src/main/java/com/impossibl/postgres/protocol/v30/ProtocolShared.java#L109) to [UnpooledByteBufAllocator](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/UnpooledByteBufAllocator.java#L28) and see if the symptoms go away?

Also can you call [PooledByteBufAllocator.freeThreadLocalCache](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java#L341) from threads which do allocation?

Do your unit tests (or other code) use [releaseLater](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/ReferenceCountUtil.java#L137)?

**Comment by kdubb** [comment]
> Is this what you are referring to https://github.com/impossibl/pgjdbc-ng <https://github.com/impossibl/pgjdbc-ng>?
> 
Yep.
> Just as an experiment can you change from using PooledByteBufAllocator <https://github.com/impossibl/pgjdbc-ng/blob/1f8cdcb6f8f75b012fb37763ea8caefd29835dd4/src/main/java/com/impossibl/postgres/protocol/v30/ProtocolShared.java#L109> to UnpooledByteBufAllocator <https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/UnpooledByteBufAllocator.java#L28> and see if the symptoms go away?
> 
UnpooledByteBufAllocator solves the problem
> Also can you call PooledByteBufAllocator.freeThreadLocalCache <https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java#L341> from threads which do allocation?
> 
Since the threads are called from any thread started by Tomcat I have no control over this.
> Do your unit tests (or other code) use releaseLater <https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/ReferenceCountUtil.java#L137>?
> 
Not sure how I would use this.

**Comment by Scottmitch** [comment]
Responses below ... however can you clarify the problem a bit?

> The driver has a cleanup method and we are calling. It both shuts down the thread pool and calls ThreadDeathWatcher.awaitInactivity(5, TimeUnit.SECONDS). The pool threads shutdown fine but ThreadDeathWatcher persists.

Can you describe the 'thread pool' and its relationship to ByteBuf allocations (e.g. do they do any)? Are any threads from this pool still "watched" by `ThreadDeathWatcher` after they have been shutdown? The behavior you describe from `ThreadDeathWatcher` sounds correct if it is still watching threads (Tomcat threads in this case) it has been asked to watch that have not yet terminated...is the issue just the behavior seems unexpected?

> UnpooledByteBufAllocator solves the problem

Thanks for verifying. Just wanted to narrow the problem into the usage of the PooledByteBufAllocator. I'm not suggesting making this change permanently.

> Since the threads are called from any thread started by Tomcat I have no control over this.

Do you mean since the methods which do allocation are called from threads owned by tomcat you have no control?

> Not sure how I would use this.

This function can be used to "lazily" release `ByteBuf` objects. Since switching to the `UnpooledByteBufAllocator` made the symptoms disappear, I'm guessing you do not do this on the tomcat threads.

**Comment by kdubb** [comment]
> Can you describe the 'thread pool' and its relationship to ByteBuf allocations (e.g. do they do any)?
> 

The "thread pool" is the pool owned by the JDBC driver to facilitate communication with the database. DB Requests are built on whatever thread is originating the DB statement. This can be any thread actively running DB code; including the HTTP request threads owned by Tomcat.  

I think the key takeaway here is that the netty “thread pool” isn’t doing the allocation of any ByteBufs specifically because it is only handling received packets of data from the database. Although internally netty is allocating ByteBufs somewhere for these “thread pool” threads to process.

> Are any threads from this pool still "watched" by ThreadDeathWatcher after they have been shutdown?
> 

As displayed in my screengrab above, after properly shutting down the driver’s thread pool, the only 3 threads still being watched by ThreadDeathWatcher are owned by Tomcat.  The shutting down of the “thread pool” and cleanup of its threads is working properly currently.  Also, no more commands from the driver can be executing at this time, we’ve already ensured all connections are closed.

> The behavior you describe from ThreadDeathWatcher sounds correct if it is still watching threads (Tomcat threads in this case) it has been asked to watch that have not yet terminated...is the issue just the behavior seems unexpected?
> 


Yes, because calling ThreadDeathWatcher.awaitInactivity(..) never shuts the ThreadDeathWatcher down.  It always believes there is something to do because the Tomcat threads are still alive.  This causes Tomcat (and other containers) to spit out warnings/errors because we have started threads that we haven’t stopped; it considers this a memory leak.

After looking at things I believe it *IS* a memory leak, due to the classloader isolation employed in containers like Tomcat .  When the current application is shutting down these container owned request threads have associated caches of ByteBufs that are only going to be associated with that specific instance of the web application. Since they are being referenced by a valid thread that is running the ThreadLocals will retain references to the cache of objects as well as the class itself, and the classloader… all the way up the chain.  The application shutting down just means these objects are all now orphaned.  A new web application (or version of the same web application) being started in this server will get a new classloader, and hence all “new” classes (even if they are exactly the same) and start the process all over again.   This is why containers warn of these issues.

> Since the threads are called from any thread started by Tomcat I have no control over this.
> 
> Do you mean since the methods which do allocation are called from threads owned by tomcat you have no control?
> 
Yes. Precisely.
> Not sure how I would use this.
> 
> This function can be used to "lazily" release ByteBuf objects. Since switching to the UnpooledByteBufAllocator made the symptoms disappear, I'm guessing you do not do this on the tomcat threads.
> 
I still cannot see how this would solve my issue unless lazily releasing ByteBuf objects also releases the ThreadDeathWatcher “hold" on the thread. From what I have seen it doesn’t but I might not be understanding it correctly.

**Comment by normanmaurer** [comment]
@kdubb sorry for the slow response ...

Can you just try to call `FastThreadLocal.destroy()` as part of your shutdown process ? I think this should fix your problem:

https://github.com/netty/netty/blob/4.0/common/src/main/java/io/netty/util/concurrent/FastThreadLocal.java#L93
http://netty.io/4.0/api/io/netty/util/concurrent/FastThreadLocal.html#destroy()

**Comment by Scottmitch** [comment]
> I still cannot see how this would solve my issue unless lazily releasing ByteBuf objects also releases the ThreadDeathWatcher “hold" on the thread. From what I have seen it doesn’t but I might not be understanding it correctly.

This was just informative ... I was just trying to narrow in on what potential causes of threads being watched were. If you aren't using it now don't worry about it.

**Comment by normanmaurer** [comment]
@kdubb did you try my suggestion ?

**Comment by normanmaurer** [comment]
@kdubb will close now... Please reopen if my suggestion not works

**Comment by kdubb** [comment]
Apologies, I have been quite busy with other things.  I will do as requested if it does not work.  Thanks for the help.

**Comment by fabienbk** [comment]
Hello, sorry to jump in, I have this *exact* problem and `FastThreadLocal.destroy()` did nothing.
