### ISSUE TITLE
IOException(File descriptor closed) occurred when we called EventLoopGroup#shutdownGracefully()

### ISSUE THREAD

**Issue by ifinver** [netty/netty#4656]
Today our team release a new version in a small scope(A/B test), almost 3000 users updated. Then our error reporting system collected this error just for one time within 3 hours.

here is stack trace:

    java.io.IOException: File descriptor closed
	at libcore.io.Posix.writeBytes(Native Method)
	at libcore.io.Posix.write(Posix.java:223)
	at libcore.io.BlockGuardOs.write(BlockGuardOs.java:313)
	at java.nio.SelectorImpl.wakeup(SelectorImpl.java:327)
	at io.netty.channel.nio.NioEventLoop.wakeup(NioEventLoop.java:591)
	at io.netty.util.concurrent.SingleThreadEventExecutor.shutdownGracefully(SingleThreadEventExecutor.java:539)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.shutdownGracefully(MultithreadEventExecutorGroup.java:146)
	at io.netty.util.concurrent.AbstractEventExecutorGroup.shutdownGracefully(AbstractEventExecutorGroup.java:69)
	at xxx.xxx.xxx.im.socket.IMSocketThread.run(IMSocketThread.java:85)

And this is our code    

    @Override
    public void run() {
        try {
            if (null == mChannel || !mChannel.isActive()) {
                InetSocketAddress remoteAddress = new InetSocketAddress(mAddress, mPort);
                mChannelFuture = mBootstrap.connect(remoteAddress).sync();
                if (!mChannelFuture.isDone()) {
                    throw mChannelFuture.cause();
                }
                mChannel = mChannelFuture.channel();
            }
            mChannel.closeFuture().sync();
        } catch (Throwable throwable) {
            //noinspection ConstantConditions
            //post disconnection event
            EventBus.getDefault().post(IMConnectEvent.MSG_SERVER_DISCONNECTED);
        } finally {
             mEventLoopGroup.shutdownGracefully();
        }
    }

The exception occoured at line:"mEventLoopGroup.shutdownGracefully();"
We can't recur it and don't know other details how it comes,our solution is:

       try {
                mEventLoopGroup.shutdownGracefully();
            }catch (Throwable ignored){}
is that ok when it comes again?
And we curious about how it comes..

**Comment by normanmaurer** [comment]
@ifinver do you by any chance call shutdownGracefully multiple times on the EventLoop concurrently ?

**Comment by ifinver** [comment]
SocketThread:

    public class IMSocketThread extends Thread {

    private final String mAddress;
    private final int mPort;
    private Bootstrap mBootstrap;
    private ChannelFuture mChannelFuture;
    private Channel mChannel;
    private EventLoopGroup mEventLoopGroup;
    private ChannelHandlerAdapter mChannelHandlerAdapter;

    public IMSocketThread(String address, int port, ChannelHandlerAdapter adapter) {
        this.mAddress = address;
        this.mPort = port;
        this.mChannelHandlerAdapter = adapter;
        if (TextUtils.isEmpty(address) || port < 0)
            throw new IllegalArgumentException("IM服务器和端口不合法");
        init();
    }

    private void init() {
        mEventLoopGroup = new NioEventLoopGroup();
        mBootstrap = new Bootstrap();
        mBootstrap.group(mEventLoopGroup);
        mBootstrap.channel(NioSocketChannel.class);

        mBootstrap.handler(new ChannelInitializer<Channel>() {
            @Override
            protected void initChannel(Channel ch) throws Exception {
                ch.pipeline().addLast("encoder", new IMPacketEncoder());
                ch.pipeline().addLast("decoder",new LengthFieldBasedFrameDecoder(Integer.MAX_VALUE  ,1,2,-3,0));
                ch.pipeline().addLast("handler", mChannelHandlerAdapter);
            }
        });
    }

    @Override
    public void run() {
        try {
            if (null == mChannel || !mChannel.isActive()) {
                InetSocketAddress remoteAddress = new InetSocketAddress(mAddress, mPort);
                mChannelFuture = mBootstrap.connect(remoteAddress).sync();
                if (!mChannelFuture.isDone()) {
                    throw mChannelFuture.cause();
                }
                mChannel = mChannelFuture.channel();
            }
            mChannel.closeFuture().sync();
        } catch (Throwable throwable) {
            //抛出断线事件
            EventBus.getDefault().post(IMConnectEvent.MSG_SERVER_DISCONNECTED);

        } finally {
            try {
                mEventLoopGroup.shutdownGracefully();
            }catch (Throwable ignored){}
        }
    }

    public void close() {
        if (mChannelFuture != null) {
            if (mChannelFuture.channel() != null)
                mChannelFuture.channel().close();
            mChannelFuture.cancel(true);
        }
    }

    public boolean send(IMPacket packet) {
        if (mChannel != null && mChannel.isActive()) {
            mChannel.writeAndFlush(packet);
            return true;
        }
        return false;
    }
}

Only one place it is used : 
      `IMSocketManager`:

     public synchronized void connectIMServer() {
        if(isInConnectProcess){
            //正在连接的过程中了,
            return;
        }
        isInConnectProcess = true;
        //清除重连计划
        imService.getImReconnectManager().clearPlan();

        if (imSocketThread != null) {
            imSocketThread.close();
            imSocketThread = null;
        }
        IMLog.d("start connect im server");
        imSocketThread = new IMSocketThread(address, port, new IMClientHandler(this));
        imSocketThread.start();
    } 

`IMSocketManager` is singleton pattern and this method is synchronized.

**Comment by zsxwing** [comment]
Looks like an Android special issue. Can `selector.wakeup` be called after `selector.close` on Android? It's fine in Mac OS X.

**Comment by ifinver** [comment]
We don't clear about that. It's difficult to recur this exception manually, so we care about a problem : we use `try-catch` to hide this `IOException` ,can netty connect server again when create a new IMSocketThread?

**Comment by normanmaurer** [comment]
@ifinver @zsxwing yeah looks like an android "bug". Selector.wakeup should never throw an IOException

**Comment by normanmaurer** [comment]
@ifinver so yes just catch and ignore should be safe.

**Comment by ifinver** [comment]
oh thanks
