### ISSUE TITLE
netty-transport-native-epoll pom.xml has encoding ISO-8859-15

### ISSUE THREAD

**Issue by cdancy** [netty/netty#4658]
Any particular reason why we are not UTF-8 encoding here? Putting together a project with Netty I'm unable to resolve this particular artifact (using ivy/gradle) due to its encoding. Is this something that can be changed?

**Comment by normanmaurer** [comment]
@cdancy no... can you just issue a PR with a fix ?

**Comment by cdancy** [comment]
Sure. Give me a minute to send it in. Thanks.

**Comment by normanmaurer** [comment]
@cdancy awesome. Please sign also the icla:
http://netty.io/s/icla

And also respect the commit message template:
http://netty.io/wiki/writing-a-commit-message.html

**Comment by cdancy** [comment]
@normanmaurer sent in. Signed your ICLA and refactored the commit message to conform to your projects standards.

**Comment by cdancy** [comment]
Not sure if you guys can easily backport and/or generate a new release (4.0.35 ?) but would be great if you could.

**Comment by normanmaurer** [comment]
Yes will take care this week

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4659
