### ISSUE TITLE
Why use SocketChannel.write(ByteBuffer[] srcs, int offset, int length) ? not other?

### ISSUE THREAD

**Issue by 879913935** [netty/netty#4664]
![ksidxm xif p_05qsw ox7](https://cloud.githubusercontent.com/assets/6321538/12164493/de05cbe0-b550-11e5-900f-5434ab142302.png)

In my applet,I write some code like this:
while(true){
    channel.writeAndFlush(msg);
}

Server-side received slow and network traffic is the same.

When I use nio,not netty,code like this:
while(true){
    socketChannel.write(ByteBuffer.wrap(byte[] bytes));
}
Server-side network traffic is busy.

I found that the method SocketChannel.write(ByteBuffer[] srcs, int offset, int length) has problem.

if length>16,returned writed bytes = 16*(ByteBuffer of srcs).size()

I don't konw why ,I hope you can understand:)

**Comment by normanmaurer** [comment]
@879913935 sorry no I don't understand :( If you ask why we are doing gathering writes than the answer is that it's because you have more then one ByteBuf in your outbound buffer. Also calling channel.writeAndFlush(...) in an endless loop is never a good idea as you will OOME your app if the remote host is not able to keep up

**Comment by 879913935** [comment]
calling channel.writeAndFlush(...) in an endless loop is really not a good idea,I just for test

I‘m confused:
![image](https://cloud.githubusercontent.com/assets/6321538/12165043/545549fc-b555-11e5-921d-d10ba544e215.png)

console print ret=160

It means that only 16 packet has bean written.I expected 50*10=500 bytes

**Comment by normanmaurer** [comment]
Actually if you would be able to write everything in one try it would print 450 (each buffer has 9 bytes in it as you only write 9 bytes). 

That said it is completely legal in terms of implementations that is only partial write stuff and let you try to write the rest laster. On my laptop it writes all in one try though.

**Comment by normanmaurer** [comment]
Closing as this is not really a netty question
