### ISSUE TITLE
Netty's DNS resolution should take into account system domain name

### ISSUE THREAD

**Issue by anuraaga** [netty/netty#4665]
On linux, a system's default domain name is configured in /etc/resolv.conf, and most OS's have a similar concept. This allows addresses to omit the default domain name and still resolve.

For example, if in /etc/resolv.conf includes

```
domain netty.com
```

Then both of the following will succeed
```
$ ping server1.netty.com
$ ping server1
```

In general, I think a good rule of thumb is any address that can be reachable with ping should be resolvable by netty-dns, and that requires at least handling this default domain (perhaps there are other corner cases too I'm not aware of).

**Comment by mauhiz** [comment]
Does it work fine now on JDK anyways ? http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6427214

**Comment by slandelle** [comment]
[dnsjava](http://www.dnsjava.org/) does honor `/etc/resolv.conf` on Unix so it would be pretty easy to do the same.
It also honors `ipconfig/winipcfg` on Windows, but warms that [the parsing might fail on non English systems](https://github.com/dnsjava/dnsjava/blob/6b86c9f72a849feb35f6d646ecde45dcbd8b5d6a/org/xbill/DNS/ResolverConfig.java#L20-L21), so I think we'd better forget about it.

Question now is: who's in?

**Comment by trustin** [comment]
I'd like to see this resolved. :-) Will take a look if @slandelle doesn't beat me.

**Comment by slandelle** [comment]
Today is Netty day for me, but I first want to give a stab at my caching thing. :)

**Comment by trustin** [comment]
![tumblr_ml87q0tkrp1re3x32o1_](https://cloud.githubusercontent.com/assets/173918/12166831/fb4e923e-b56b-11e5-80e0-7eb8a97e2e9b.gif)

**Comment by normanmaurer** [comment]
LOL

**Comment by slandelle** [comment]
I can work on this as soon as #4668 get merged :)

It's a bit tricky, because you have to fallback when standard resolution fails, and try the different search domains recursively. It would be great to be able to limit extra allocations (exceptions, promises and failed futures), but that might prove difficult.

**Comment by slandelle** [comment]
@trustin Do you have any idea about how OSs typically resolve names when there's some search domains configured?
dnsjava uses them as a fallback, but that might be wrong, and I guess it doesn't care about performance as it's a blocking library.
Should search domain based resolution be a fallback, or should it be performed concurrently, just like when searching against multiple DNS servers?
The former would significantly break the current design (fallbacks must only happen when failure isn't a timeout, and account for maximum number of queries).
The latter might dramatically increase the number of queries, as in theary, there's no way to tell if a name is absolute except if it ends with a dot.

WDYT?

**Comment by trustin** [comment]
@slandelle Sorry for a late reply. Thanks for great questions!

> Should search domain based resolution be a fallback, or should it be performed concurrently, just like when searching against multiple DNS servers?

According to the manpage:

```
domain Local domain name.
              Most  queries for names within this domain can use short names relative to the local domain.  If set to
              '.', the root domain is considered.  If no domain entry is present, the domain is determined  from  the
              local  hostname  returned  by gethostname(2); the domain part is taken to be everything after the first
              '.'.  Finally, if the hostname does not contain a domain part, the root domain is assumed.

       search Search list for host-name lookup.
              The search list is normally determined from the local domain name; by default,  it  contains  only  the
              local  domain name.  This may be changed by listing the desired domain search path following the search
              keyword with spaces or tabs separating the names.   Resolver  queries  having  fewer  than  ndots  dots
              (default  is 1) in them will be attempted using each component of the search path in turn until a match
              is found.  For environments with multiple subdomains please read options ndots:n below to avoid man-in-
              the-middle  attacks  and  unnecessary  traffic for the root-dns-servers.  Note that this process may be
              slow and will generate a lot of network traffic if the servers for the listed domains  are  not  local,
              and that queries will time out if no server is available for one of the domains.
```

Seems like we need to read the 'ndots' option to determine whether to append the domain.

```
              ndots:n
                     sets  a  threshold for the number of dots which must appear in a name given to res_query(3) (see
                     resolver(3)) before an initial absolute query will be made.  The default for  n  is  1,  meaning
                     that  if  there  are any dots in a name, the name will be tried first as an absolute name before
                     any search list elements are appended to it.  The value for this option is  silently  capped  to
                     15.
```

**Comment by slandelle** [comment]
@trustin I agree

So, for `doResolveUncached`:

```
if (hostname is absolute (start with dot) || no search path) {
 searchAsIs
} else {
  if (numDots(name) >= nDots) {
    searchAsIs
  }
  if (searchAsIs wasn't performed or failed) {
    searchWithSearchPathSequenciallyUntilOneSucceeds
  } 
}
```

For `doResolveAllUncached`, the question is: should we do the same and only perform path based search when absolute search wasn't successful?

Regarding implementation, this will probably involve some fun with recursive Promises and callbacks.

I can help reviewing, but I won't have time to contribute this myself before April, sorry.

**Comment by trustin** [comment]
> For doResolveAllUncached, the question is: should we do the same and only perform path based search when absolute search wasn't successful?

Yeah, I think we should do the same. The only difference between `doResolveUncached` and `doResolveAllUncached` is that `doResolveUncached` chooses only one record from the result.

**Comment by trustin** [comment]
.. and thanks for trying to help. I really appreciate it. No worries!

**Comment by slandelle** [comment]
If this can wait a few months, I'll be able to tackle it. So swamped atm...

**Comment by normanmaurer** [comment]
@slandelle final is very close (within 1 week I would say) you have time or we want to move it to 4.1.1.Final ?

**Comment by slandelle** [comment]
@normanmaurer Sorry, I really don't have time for this one atm. It's still on my radar, but I really don't know when I'll find time to work on this. So, yes, please remove from 4.1.0.

**Comment by vietj** [comment]
Hi,

we do need this feature in Vert.x 3.3 and we have implemented search domains resolution.

It implements according to the rules above - however it is implemented only for `doResolveUncached` and not for `doResolveAllUncached` (as we don't need it yet and we don't have time right now - it was implemented yesterday over night for upcoming 3.3.0).

The Vert.x codebase contains a temporary fork of the `DnsNameResolver` because we need a fix for a bug (that we reported and that Norman fixed) in this class and cannot wait for a Netty _4.1.2.Final_ version . So we could implement this feature there for Vert.x 3.3.0 release.

Anyway the code is here : https://github.com/eclipse/vert.x/commit/75c3b9a669221959bb5df60385a5cb15f71e1e88

I would be happy to contribute it to Netty (with improvements of course to meet Netty's expectations) in the following weeks or that @slandelle reuse it, since he was willing to implement it in the first place.

**Comment by Scottmitch** [comment]
@vietj - Thanks for reporting back ... +1 to submitting a PR when you have time

**Comment by vietj** [comment]
@Scottmitch should have time within a couple of weeks

**Comment by slandelle** [comment]
Salut @vietj! Sorry, I don't have the cycles for this atm, so I'll gladly let you do the hard work ;-)

**Comment by vietj** [comment]
hi,

here is a first implementation of search domains : https://github.com/vietj/netty/tree/dns-search-domains

- the default search domains uses the `sun.net.dns.ResolverConfiguration` search list
- the default ndots value is `1`

can you do an initial review before doing a more formal PR ?

**Comment by normanmaurer** [comment]
@vietj could you just open a PR... its easier to leave comments there. Thanks buddy!

**Comment by vietj** [comment]
@normanmaurer @slandelle done a PR here https://github.com/netty/netty/pull/5496

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5518
