### ISSUE TITLE
netty-all causes classpath problems

### ISSUE THREAD

**Issue by jroper** [netty/netty#4671]
I'm not sure if you remember the junit classpath nightmare prior to junit 4.11, basically, junit bundled all its dependencies, including hamcrest.  So, if you wanted to use a newer hamcrest version, you were at the mercy of classpath ordering as to whether you'd get it or not.  So they introduced a new artifact called junit-dep, which didn't bundle dependencies, that you could depend on.  But as soon as you depended on another test framework that depended on junit, you'd have an even worse problem, because now not only did you have multiple versions of hamcrest, you had multiple versions of junit on the classpath.  So you'd add exclusions, but the junit without bundled dependencies always snuck in there every few months as people added new dependencies.  Eventually it was fixed in junit 4.11, but the effects are still felt because there are still some projects that depended on junit-dep that your project might depend on, meaning junit still ends up on the classpath twice, so now you have to add exclusions for junit-dep.

netty-all basically has the same problem.  You end up with two different artifacts containing the same classes on the classpath, the dependency management system doesn't know that they contain the same classes so doesn't know to replace one with the other, and so you have an unpredictable classpath nightmare.  I went to raise an issue on Cassandra about this, and I searched for it in the Apache issue tracker, and found this list of issues caused by netty-all:

https://issues.apache.org/jira/browse/PIG-4630
https://issues.apache.org/jira/browse/CASSANDRA-10984
https://issues.apache.org/jira/browse/DIRKRB-355

Furthermore, I found at least 3 other Apache projects that are currently using netty-all, which means as soon as some end user tries to integrate with something that doesn't use netty-all (like Play), the same issue will happen.

Now, if netty-all didn't bundle any classes, but just depended on everything, then there would be no problem, the dependency manager would generally be able to work things out.  But since it's not doing that, I don't think that's the intent of netty-all, netty-all is probably designed for people not using dependency management that just want to drop a jar into their system.  For those people, that's fine, give them that file in a manual download.  But don't put that artifact out on maven central where it's going to cause these classpath issues.  Instead, publish an artifact on maven central that uses regular dependency management to bring in all the netty dependencies.

**Comment by hepin1989** [comment]
@jroper I see your point.
http://mvnrepository.com/artifact/io.netty/netty-all/4.1.0.Beta8 which have all the classes in it.a better way as you said,it should be an aggerate project.

**Comment by ifesdjeen** [comment]
@jroper I've sent a patch to Cassandra to update their deps, although you know that you can use transitive dependencies with exclusions, right? 

In any case, if something is _used_ in the transitive dependency with a different version, you just have to match their version for binary compatibility. If it's not _used_ but only referenced (e.g. the mega-jar is used but only handful of classes are actually used), just use maven excludes (or your build tool equivalent of those).

**Comment by jroper** [comment]
Yes I've worked around the problem easily enough.

**Comment by Scottmitch** [comment]
@normanmaurer - WDYT? Any strong reason for needing `netty-all` to repackage?

**Comment by ejona86** [comment]
@Scottmitch, one option is to keep the netty-all package, but no longer make it a repackage: just have simple dependencies on the other packages. That doesn't provide the "jumbo jar" anymore though, which is convenient when not using maven central for dependencies.

@nmittler, FYI

**Comment by Scottmitch** [comment]
> one option is to keep the netty-all package, but no longer make it a repackage: just have simple dependencies on the other packages.

Yip I'm wondering if there are any known use cases we are trying to support with the repackage, or opposition to `netty-all` just being a "reference other packages".  I take it you are OK with making this change?

Also /cc @trustin.

**Comment by normanmaurer** [comment]
@Scottmitch @ejona86 @jroper I think have netty-all just depend on everything else should be fine.

@trustin WDYT ?

**Comment by jroper** [comment]
That's fine by me :)

**Comment by trustin** [comment]
@normanmaurer Fine by me, but how about just removing netty-all completely?

**Comment by polarctos** [comment]
Any news on this issue?

I would prefer keeping `netty-all` available and just having it depend on everything else.

This has two advantages:
* most of the current users of `netty-all` can just keep updating their netty versions without having to adapt their POMs to new dependency names
* an additional 'jar-with-dependencies' could also easily be created to still offer a shaded JAR file for users that actually prefer manual download

Is a PR wanted?

**Comment by Scottmitch** [comment]
PR implementing https://github.com/netty/netty/issues/4671#issuecomment-173393054 sgtm

**Comment by Scottmitch** [comment]
No updates. PRs are welcome. The way netty-all is built will change with #6000 as well ... maybe worth revisiting after this.

**Comment by quaff** [comment]
I'm not opposed to produce empty netty-all.jar for maven repository, but a dedicated netty-all.jar is necessary for downloading at somewhere like github releases, some people or some projects manage dependence manually.
