### ISSUE TITLE
Spelling mistake at EmbeddedChannel#readOutbound()

### ISSUE THREAD

**Issue by ferrybig** [netty/netty#4676]
Netty 5.0.0.Alpha2

Context:
Javadoc of EmbeddedChannel#readOutbound(),
"from" is mistakenly spelled "froum"

https://github.com/netty/netty/blob/43ebbc3fa065155fa67732b0cbd7c12843b0f3f7/transport/src/main/java/io/netty/channel/embedded/EmbeddedChannel.java#L190

**Comment by normanmaurer** [comment]
@ferrybig how about doing a PR against the 4.1 branch ?

**Comment by ferrybig** [comment]
Pull request made: https://github.com/netty/netty/pull/4682 did not know how to add the pull request to this issue

**Comment by Scottmitch** [comment]
Fixed by https://github.com/netty/netty/pull/4682
