### ISSUE TITLE
Should `EventExecutorGroup#terminationFuture()` return a `Future<Void>` instead of `Future<?>`?

### ISSUE THREAD

**Issue by jchambers** [netty/netty#4680]
It looks to me like the termination future for `EventExecutorGroups` always succeeds with a value of `null`. Would it make sense to make [`terminationFuture()`](http://netty.io/4.1/api/io/netty/util/concurrent/EventExecutorGroup.html#terminationFuture()) return `Future<Void>` instead of `Future<?>`? The latter leaves callers wondering what could possibly be returned, while the former makes it clear that there's no meaningful return value (beyond "we're done").

Cheers!

**Comment by trustin** [comment]
SGTM. Care to send a PR? :-)

**Comment by jchambers** [comment]
> Care to send a PR?

I'll get on it. Cheers!

**Comment by jchambers** [comment]
As promised, #4687 is now open for your consideration.
