### ISSUE TITLE
State of 4.1 release?

### ISSUE THREAD

**Issue by AlainRoy** [netty/netty#4691]
Hi,

We're using Netty 4.1b8. For the most part, it's been great. However, we're running into one issue with 4.1b8 where HTTP/2 connections will fail to open--the server claims we sent data before a SETTINGS frame. As best I can tell, it's a Netty bug.

Fortunately, the latest 4.1.CR-SNAPSHOT builds don't show this symptom. So instead of worrying about a bug fix, I'm curious when the next non-SNAPSHOT release (beta or otherwise) is expected. Do you have an ETA?

Thanks!
-alain

**Comment by normanmaurer** [comment]
@AlainRoy this week :)

**Comment by AlainRoy** [comment]
Sweet, thanks!
