### ISSUE TITLE
Have an all-in-one tcnative jar

### ISSUE THREAD

**Issue by slandelle** [netty/netty#4692]
AFAIK, the java code in the tcnative jars for the different platforms is identical and only the native one changes.

Instead of relying on the build system to pick the proper platform, which only works with maven and tightly binds the binaries (think building and deploying a zip of an all-in-one jar) to one target platform, wouldn't it be better to pick the proper native code to load at runtime?

Here's an example of [how it's being done in lz4-java](https://github.com/jpountz/lz4-java/blob/master/src/java/net/jpountz/util/Native.java#L81-L99).

WDYT?

**Comment by johnou** [comment]
+1 our build environment, production environment and test client environments run different OS / architecture.

**Comment by Scottmitch** [comment]
@slandelle - Is this a duplicate of https://github.com/netty/netty-tcnative/issues/24? If not could you move this issue to the tcnative repo?

**Comment by slandelle** [comment]
@Scottmitch Absolutely. Sorry, I failed to realize you didn't centralize all Netty related issues there, and didn't check if netty-tcnative had a bug tracker.

Close as a duplicate of netty/netty-tcnative#24.

Thanks.
