### ISSUE TITLE
SSL handshake issue 

### ISSUE THREAD

**Issue by abhayavis** [netty/netty#4698]
We are facing a issue with netty 4.0.33 in https ssl handshake issue where server receives a CLIENT HELLO responds with ACK but never sends SERVER hello back . Once this happens then the only option is to kill the service and start again and it continue to work fine for few hours . 

When the problem comes the wireshark file of that time is attached which shows the problem . Pls let me know as to how to go about debugging this issue and resolve 
[dump_desk.zip](https://github.com/netty/netty/files/88484/dump_desk.zip)

**Comment by normanmaurer** [comment]
Can you share a reproducer?

**Comment by abhayavis** [comment]
We have not been able to simulate it , it comes on the production server and how it is triggered is unknown but the problem comes almost everyday .

**Comment by normanmaurer** [comment]
When it happens can you also get a thread-dump ?

**Comment by abhayavis** [comment]
Yes i have that from visual VM and it uses three different engine for normal socket , http and https . We had switched over to native epoll and the tump is with native epoll.
[ThreadDumpHang.txt](https://github.com/netty/netty/files/88850/ThreadDumpHang.txt)

**Comment by abhayavis** [comment]
I tried to change from JDK to openssl with netty-tcnative and still have the problem . So took a tcpdump of the server and found that the server (192.168.1.202) is busy sending sever hello and FIN,ACK to a client 192.168.1.22 and on receiving RST from client goes on to send the same server hello and FIN,ACK again to the same client on different ports which is weird .
[dump.pcap.zip](https://github.com/netty/netty/files/91977/dump.pcap.zip)

**Comment by abhayavis** [comment]
There is some analysis that is done . I am attaching a pcap file and starting from packet number 3983 looks like the client ip 192.168.1.98 is trying to tell the server 192.168.1.202 about the window full to which netty server probably not understanding the packet sends "Ignore unknown record" . Once the client recovers and is ready to receive it sends a "TCP Wondow Update" and netty still do not understand that and sends "Ignore Unknown Record" and is de-stabilized after that and as can be seen does not responds to client hello message with server hello message . 
[file627.zip](https://github.com/netty/netty/files/92927/file627.zip)

**Comment by normanmaurer** [comment]
@abhayavis sorry but without a way to reproduce I'm not able to help much atm :/

**Comment by normanmaurer** [comment]
Closing this for now... if there is still a problem please reopen with more details
