### ISSUE TITLE
Is there a problem in safeDuplicate of DefaultChannelGroup.java

### ISSUE THREAD

**Issue by kenro** [netty/netty#4700]
```java
private static Object safeDuplicate(Object message) {
        if (message instanceof ByteBuf) {
            return ((ByteBuf) message).duplicate().retain();
        } else if (message instanceof ByteBufHolder) {
            return ((ByteBufHolder) message).duplicate().retain();
        } else {
            return ReferenceCountUtil.retain(message);
        }
    }
```
duplicate() -just copy its inner byte[], and will not modify reader index and write index.

So if I send a ByteBuf to many channel, everything I call duplicate() , but its readerIndex is still old.

Will there be a problem? It seems that reader index has been change by many channel write.

I think we should also reset reader index to 0 after invoke duplicate()

**Comment by normanmaurer** [comment]
@kenro nope... duplicate not copy the inner byte[] but just creates another "view" on this buffer. So it's correct to call duplicate() and not modify the indexes.

**Comment by kenro** [comment]
thank normanmaurer ！I still confused： When a channel write a ByteBuf, it will change the ByteBuf's index. and next channel duplicate the ByteBuff,its index is the same as pre ByteBuf？  next channel write the copy ByteBuff ，should first reset the index？
