### ISSUE TITLE
Netty 4.1.CR-SNAPSHOT reusing HTTP/2 stream IDs when maxConcurrentStreams is set

### ISSUE THREAD

**Issue by AlainRoy** [netty/netty#4704]
I'm using Netty 4.1.CR-SNAPSHOT from January 12, 2016. We're trying to use Netty's HTTP/2 implementation as part of a distributed system that replicates large amounts of state. When a node joins a system, we can send large quantities of data in a small amount of time. When we configure HTTP with maxConcurrentStreams() and we exceed that concurrency by sending too many requests, Netty will re-use stream IDs, and that effectively drops messages. I expected them to be queued and sent when the concurrency level dropped--was that a bad expectation and it's actually a problem in our code?

This is a repeatable problem in our replication process that I was able to duplicate with a small test case. The test case is short but relies on our testing framework, so it's not amenable to copy-and-paste into a ticket, sorry. We can easily work something out if you want access to our code. (The test isn't committed yet, but it's part of github.com/vmware/xenon.)

Our test case does:
- Instantiate a REST-based API
- Do a POST to the API to give it state
- Issue 1500 GETs as quickly as possible to the API

In our replication code, we're doing a wider variety of operations, of course: GET, PUT, etc. But while this test exaggerates the scenario, the network traffic pattern isn't too different. 

I had configured configured the HTTP2Settings for for our HttpToHttp2ConnectionHandler to set maxConcurrentStreams to 1024. I didn't have a strong use case for limiting it, it just seemed right at the time. 

In this scenario, our code saw stream IDs being reused about the time we exceeded 1024 concurrent requests to Netty. More precisely, our client code provides its own HttpToHttp2ConnectionHandler that just duplicates the one in Netty, but adds a few lines of code to associate stream IDs with our data structures so we can manage the responses. (I couldn't easily subclass it.) It has this following code, duplicated from the Netty code: 

    private int getStreamId(HttpHeaders httpHeaders) throws Exception {
        return httpHeaders.getInt(HttpConversionUtil.ExtensionHeaderNames.STREAM_ID.text(),
                                  connection().local().nextStreamId());
    }

Normally, each time we call nextStreamId() in the write() method, we get a new stream ID that is two larger than the previous one. In this test, we'll see duplicate stream IDs. Normally it's the same ID duplicated for a long stream of write requests. I'm guessing it doesn't increment until the concurrent streams decreases, but I'm not sure. 

If I pace out the GET requests so we don't exceed our maximum concurrency, then we don't see the reused stream IDs.

I have a workaround: I just don't limit the maximum concurrent streams, and the problem goes away. Therefore, unless you think it's important to limit the maximum concurrent streams, the bug is not blocking me. However, it suggests to me that there may be a problem worth looking at, so I thought you'd appreciate knowing about it.

**Comment by AlainRoy** [comment]
I just noticed the encoderEnforceMaxConcurrentStreams() option. That didn't make any difference, unfortunately.

**Comment by normanmaurer** [comment]
@nmittler @Scottmitch can you have a look ?

**Comment by nmittler** [comment]
@AlainRoy You definitely need `encoderEnforceMaxConcurrentStreams`, since it adds the `StreamBufferingEncoder`, the purpose of which is to buffer due to `MAX_CONCURRENT_STREAMS`.

It looks like the bug is in `HttpToHttp2ConnectionHandler` (and your copy of its code).  This class doesn't know that buffering is occurring and just blindly calls `connection().local().nextStreamId()`. The problem is that the connection only knows about streams that have *actually* been created - it knows nothing about the buffered streams. If streams are being buffered, you'll end up creating streams with the same ID multiple times.

Fundamentally, this is a bug in the API - we shouldn't expose the `nextStreamId()` method or even require a stream ID when creating the stream.  Some work is in progress on a new API that will resolve this.  In the meantime, however, we should probably make `HttpToHttp2ConnectionHandler` use it's own mechanism for selecting the next stream ID.

@Scottmitch WDYT?

**Comment by Scottmitch** [comment]
@nmittler - Yip something needs to change. However it seems to make sense for the codec implementation to provide generation of the next stream ID so the protocol details (increment by 2, start at even or odd, reserved upgrade stream, etc...) do not have to leak out into the application. The "nextStreamId" mechanism (queueing or not) will be required at some level and may make sense to have this in the codec. What about changing the public method [DefaultHttp2Connection.nextStreamId](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2Connection.java#L860) to serve as a getAndSet() type interface?

`HttpToHttp2ConnectionHandler` also supports the `HttpConversionUtil.ExtensionHeaderNames.STREAM_ID` header if the application needs more fine grained control over stream id creation.

**Comment by nmittler** [comment]
@Scottmitch that sounds reasonable to me.  So maybe in addition to `nextStreamId`, we have `takeNextStreamId`?

**Comment by Scottmitch** [comment]
@nmittler - Stand by for PR :)

Currently I changed `Endpoint.nextStreadId()` -> `Endpoint.incrementAndGetNextStreamId()`. However we can change to `takeNextStreamId` if you prefer. So what was provided by `nextStreamId()` is no longer a public method.

**Comment by nmittler** [comment]
@Scottmitch no need to change ... I'm fine with your name :)

**Comment by AlainRoy** [comment]
Thank you!
