### ISSUE TITLE
ZlibCodecFactory enforces JZlib decoder by default

### ISSUE THREAD

**Issue by slandelle** [netty/netty#4707]
From [this line](https://github.com/netty/netty/blob/dc615ecaaf9749edd227413c32c2f288dfc1309e/codec/src/main/java/io/netty/handler/codec/compression/ZlibCodecFactory.java#L36:

```java
noJdkZlibDecoder = SystemPropertyUtil.getBoolean("io.netty.noJdkZlibDecoder", true);
```

JZlib is supposed to be an optional dependency and it should default to false when using JDK7+.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4709
