### ISSUE TITLE
High latency on FixedChannelPool when used from other EventLoops

### ISSUE THREAD

**Issue by ztellman** [netty/netty#4715]
I was going to try to provide some tests that demonstrate this behavior, but I thought maybe it would be better to first check if I was using it wrong.

My application is a router, which for each incoming request will make a request to an authentication service and then forward the request to the appropriate backend service.  In the initial implementation, each backend host had a single `FixedChannelPool` with a `Bootstrap` that shared the server's `EventLoopGroup`, but the `Channels` for the client, auth, and backend services were presumed to be on separate event loops.

This approach worked, but when we started to put the process under load we noticed that both `acquire` and `release` operations were taking 30-50ms, dwarfing the time spent everywhere else, even though there were enough connections to go around.  I couldn't find an easy way to look at the queue lengths for the event loops, but it seemed fairly obvious that the 48 event loops in the group were fighting to gain access to the much smaller number of event loops associated with the `FixedChannelPools`.

To test this theory, I wrote a variant of the `ChannelPoolMap` which takes an `EventLoop` as an additional argument, and always returns a `Channel` which uses the specified event loop.  The result was as expected: the acquire and release times went down to single-digit microseconds, and the router started behaving a lot better.

Now, I understand that all the code in Netty is written defensively so that it will run fast when everything's on the same event loop, but still work even if it isn't.  I also recognize that the `K` in `AbstractChannelPoolMap` can contain an `EventLoop`, which will give the thread-local behavior we're looking for.

But it seems like Netty's API could provide more explicit guidance on this count.  If `ChannelPoolMap` **required** you to provide an `EventLoop` as a parameter, fewer people would hit this dead end.  Also, classes like `FixedChannelPool`, which are fairly complex due to their defensive approach to concurrency, could just be written as simple single-threaded data structures with `assert executor.inEventLoop();` at the top of each function.

In any case, this is the approach I've ended up using.  I'd have to do some work to make it something suitable for inclusion in Netty proper, but I thought I'd check here first to see if there was any interest, or whether you're happy with the implementation as-is.

**Comment by Scottmitch** [comment]
@ztellman - Thanks for explaining the issue and your approach to mitigate. In the past I have accounted for this as you suggested (key identifies EventLoop). However your suggestion to make the Executor used for the pool more visible sounds reasonable to me. @normanmaurer @trustin - WDYT?
