### ISSUE TITLE
Netty 5.0 swallowing exceptions

### ISSUE THREAD

**Issue by Qix-** [netty/netty#4721]
Perhaps this is user error, but this is completely unintuitive in my opinion. Just sat here debugging something for a few hours; turns out Netty has been swallowing a bunch of exceptions, even when `exceptionCaught` was overridden.

The following code produces no output, and the server being connected to gets no data (it does, however, receive a connection).

```java
package com.boltery.bouncer;

import io.netty.bootstrap.Bootstrap;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.Unpooled;
import io.netty.channel.Channel;
import io.netty.channel.ChannelHandlerAdapter;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.ChannelOption;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioSocketChannel;
import io.netty.handler.codec.MessageToMessageEncoder;

import java.nio.charset.Charset;
import java.util.List;
import java.util.concurrent.TimeUnit;

public class Maine2 {
	public static void main(String[] args) throws Exception {
		final EventLoopGroup loopGroup = new NioEventLoopGroup();
		final Bootstrap bootstrap = new Bootstrap()
				.group(loopGroup)
				.channel(NioSocketChannel.class)
				.handler(new ChannelInitializer<SocketChannel>() {
					@Override
					protected void initChannel(final SocketChannel socketChannel) throws Exception {
						socketChannel.pipeline().addLast(new MessageToMessageEncoder<Object>() {
							@Override
							protected void encode(final ChannelHandlerContext channelHandlerContext, final Object o, final List<Object> list) throws Exception {
								throw new Exception();
							}

							@Override
							public void exceptionCaught(final ChannelHandlerContext ctx, final Throwable cause) throws Exception {
								// never hit...
								cause.printStackTrace();
							}
						});
					}
				})
				.option(ChannelOption.SO_KEEPALIVE, true);

		final Channel ch = bootstrap.connect("127.0.0.1", 11792).await().channel();

		final ByteBuf buf = Unpooled.buffer();
		buf.retain();
		buf.writeBytes("Hello".getBytes(Charset.forName("UTF-8")));
		ch.writeAndFlush(buf);

		loopGroup.awaitTermination(2, TimeUnit.SECONDS);
	}
}
```

Am I missing something here? Adding a future listener and checking `.isSuccess()` works as expected...

```java
ch.writeAndFlush(buf).addListener((future) -> {
	if (future.isSuccess()) {
		System.out.println("Success");
	} else {
		System.err.println("FAILED"); // correctly prints "FAILED" when run
	}
});
```

However if there isn't a listener, things should crash or `exceptionCaught` should be called. This is particularly useful in cases where a step _shouldn't_ fail. What if a listener hasn't been added? This makes debugging an _absolute nightmare_ to the point I would never want to use Netty in production.

**Comment by normanmaurer** [comment]
exceptionCaught(...) is only called for inbound exceptions. All outbound exceptions must by handled in a listener by design. If you always want to have exceptions handled in exceptionCaught(...) just add a ChannelOutboundHandler that will an listener for every outbound operation

**Comment by Qix-** [comment]
@normanmaurer `ChannelOutboundHandler` was deprecated in 5.0.

**Comment by normanmaurer** [comment]
And 5.0 was deprecated completly atm. Use 4.1 in which ChannelOutboundHandler was not deprecated. (In 5.0 you would have used ChannelHandler directly)

**Comment by Qix-** [comment]
How is 5.0 "deprecated completely"? Is it not the next Alpha version?

**Comment by normanmaurer** [comment]
No we not plan to work on 5.0 any time soon but concentrate on 4.0 and 4.1. All none breaking changes were backported to 4.1

**Comment by Qix-** [comment]
Sad, I liked the changes that occurred in 5.0.

**Comment by normanmaurer** [comment]
Can you list which ones and for what reason?

**Comment by Qix-** [comment]
The refactoring to use Java's Executor APIs a little more. Allows better interoperability between different libraries. That was a big one.

Call me crazy, but pipeline nodes should be agnostic to whether the data they're working on is inbound/outbound. Netty 5.0 started to move towards that I feel like.

One step further would be to explicitly specify which part of the duplex stream a pipeline handler should be put on. Having two streams (inbound/outbound) in the same "stack" (pipeline) gets confusing, and doing automagic determination as to which handlers should be called for inbound/outbound data makes the API a bit messier. I imagine it would reduce under-the-hood code as well.
