### ISSUE TITLE
slowly down if i set the socket read/write buffer

### ISSUE THREAD

**Issue by sinlang** [netty/netty#4724]
netty io will slowly down if i set the socket buffer. it only occurs in linux(centos5).  but normally in windows!

am i make a mistake or 'ChannelOption.SO_RCVBUF & SO_SNDBUF' is actually not the standard  socket option that i think?
```
bootstrap.childOption(ChannelOption.SO_RCVBUF, 8*1024)
bootstrap.childOption(ChannelOption.SO_SNDBUF, 8*1024)
```
the full code on init boostrap
```
bootstrap = new ServerBootstrap();
		bootstrap.group(NettyUtil.IO_BOSS_POOL, NettyUtil.IO_WORKER_POOL) //
				.channel(NioServerSocketChannel.class) //
				.option(ChannelOption.SO_BACKLOG, Configuration.SOCKET_BACKLOG.getValue())//
				.childOption(ChannelOption.TCP_NODELAY, true) //
				.childOption(ChannelOption.SO_KEEPALIVE, true) //
				.childOption(ChannelOption.SO_REUSEADDR, true) 
				.childOption(ChannelOption.AUTO_READ, Configuration.NETTY_AUTO_READ.getValue()) // 不主动读取数据
				.childHandler(new ChannelInitializer<SocketChannel>() {
					@Override
					public void initChannel(SocketChannel ch) throws Exception {
						ChannelPipeline p = ch.pipeline();
						p.addLast(new MultiSchemeHandler(new StreamNettyHandler(getHandler())));
					}
				});
		if (Configuration.SOCKET_READ_BUFFER.getValue() > 0) {
			bootstrap.childOption(ChannelOption.SO_RCVBUF, Configuration.SOCKET_READ_BUFFER.getValue());
		}
		if (Configuration.SOCKET_WRITE_BUFFER.getValue() > 0) {
			bootstrap.childOption(ChannelOption.SO_SNDBUF, Configuration.SOCKET_WRITE_BUFFER.getValue());
		}
```

**Comment by Scottmitch** [comment]
SO_RCVBUF and SO_SNDBUF should be "standard definition" of these socket options (see how they are used in [DefaultSocketChannelConfig](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/socket/DefaultSocketChannelConfig.java#L230)).

Can you provide what version of Netty you are using, and what transport type (e.g. `NIO`, `EPOLL`, etc..)?

What is the default value for both of these options if you don't explicitly set them?

**Comment by normanmaurer** [comment]
Closing... please reopen with more infos if you think it's a netty bug
