### ISSUE TITLE
DefaultEventExecutor: elevated context switching and CPU utilization when server is idle.

### ISSUE THREAD

**Issue by vikrum** [netty/netty#473]
In migrating to using DefaultEventExecutor within a pipeline I'm noticing elevated context switching and CPU utilization even when there are no clients connected.  Using io.netty.example.http.websocketx.server.WebSocketServerInitializer as a starting point: if you add a DefaultEventExecutor as such:

```
{ ...
private static final DefaultEventExecutor evntExec = new DefaultEventExecutor(64);

  @Override
  public void initChannel(SocketChannel ch) throws Exception {
      ChannelPipeline pipeline = ch.pipeline();
      pipeline.addLast("decoder", new HttpRequestDecoder());
      pipeline.addLast("aggregator", new HttpChunkAggregator(65536));
      pipeline.addLast("encoder", new HttpResponseEncoder());
      pipeline.addLast(evntExec, "handler", new WebSocketServerHandler());
  }  
}
```

Then: connect, send some messages, disconnect and repeat this a few times you'll observe elevated CPU even when no clients are connected.  Running visualvm (when there are no clients connected) reports io.netty.util.internal.LinkedTransferQueue.awaitMatch() taking up many of the cycles (whereas if DefaultEventExecutor isn't included in the pipeline, LinkedTransferQueue.awaitMatch() doesn't show up in the profiler when there are no clients connected).  Just wanted to ping the list and find out if the above is the correct way to utilize DefaultEventExecutor or if there is a bug at hand.

Here is a screenshot of the profiler when there are no clients connected to the server: http://misc.firebase.com/~vikrum/netty-eventexec-awaitMatch.png

I was able to reproduce the problem using the master from July 23, 2012 (961fc40b294d3680eb81866a08d5a3ce81a5e702) still no luck.

**Comment by spshukla** [comment]
I am using **Netty 4.1.5.Final** and observing following issue while using DefaultEventExecutorGroup.

The threads spawned from this event executor group is eating up all CPU. I took the thread dump of application and verified the thread count is same as defined as constructor param in **DefaultEventExecutorGroup**.

Initialize event executor group
`EventExecutorGroup eventExecutor = new DefaultEventExecutorGroup(executorThreadCount)`

Attach the executor group in Channel Handler like this
`p.addLast(eventExecutor, baseNettyServerHandler);`

As per the issue comments, I couldn't find any solution for this issue. Please help me with this.
