### ISSUE TITLE
Initializer Error Using Netty 4 with RoboVM

### ISSUE THREAD

**Issue by m3ltaw4y** [netty/netty#4730]
Netty version: 4.0.25

Context:
I encountered an exception trying to use Netty with RoboVM

Steps to reproduce:
1.  Simulate IOS via RoboVM
2.  Call new on an SimpleChannelInboundHandler

$ java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

Operating system: OSX El Capitan 64-bit

$ uname -a
Darwin TBombs-Mac-mini.attlocal.net 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64

I am trying to simulate my existing project on ios via robovm. The java project starts running, but quickly encounters a problem with Netty (4.0.25) libraries that I am using. I am using the latest version of RoboVM.

Here is the error:

java.lang.ExceptionInInitializerError
    at io.netty.util.internal.TypeParameterMatcher.get(TypeParameterMatcher.java:40)
    at io.netty.util.internal.TypeParameterMatcher.find(TypeParameterMatcher.java:78)
    at io.netty.channel.SimpleChannelInboundHandler.<init>(SimpleChannelInboundHandler.java:67)
    at io.netty.channel.SimpleChannelInboundHandler.<init>(SimpleChannelInboundHandler.java:57)
    at com.MyGame.MyThread.<init>(MyThread.java:22)
    at com.MyGame.MyGame.create(MyGame.java:50)
    at com.badlogic.gdx.backends.iosrobovm.IOSGraphics.draw(IOSGraphics.java:301)
    at com.badlogic.gdx.backends.iosrobovm.IOSGraphics$1.draw(IOSGraphics.java:202)
    at com.badlogic.gdx.backends.iosrobovm.IOSGraphics$1.$cb$drawRect$(IOSGraphics.java)
    at org.robovm.apple.uikit.UIApplication.main(Native Method)
    at org.robovm.apple.uikit.UIApplication.main(UIApplication.java:395)
    at com.MyGame.IOSLauncher.main(IOSLauncher.java:18)
Caused by: java.lang.NullPointerException
    at java.util.logging.Logger.log(Logger.java:1035)
    at io.netty.util.internal.logging.JdkLogger.log(JdkLogger.java:606)
    at io.netty.util.internal.logging.JdkLogger.info(JdkLogger.java:291)
    at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:91)
    ... 13 more
Here is the line pointed to in Netty:

        } else if (PlatformDependent.hasJavassist()) {
It seems to me that Netty is trying use code that is unavailable in RoboVM. This application runs fine in Android or Desktop versions, and the RoboVM version seems to run if I remove Netty references. Any help on how to make the two coexist greatly appreciated.

See my stackoverflow post:
http://stackoverflow.com/questions/34887562/initializer-error-using-netty-4-with-robovm

**Comment by Scottmitch** [comment]
Can you try with the latest Netty 4.0.33 version and step through the static initialization in [PlatformDependent](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/PlatformDependent.java#L72)? Seems we missed to catch an exception somewhere along the way, but not likely directly related to the `Javassist`. I can tighten up the exception processing but it would be good to know where exactly the exception is escaping.

**Comment by m3ltaw4y** [comment]
Error is exactly the same in 4.0.33.Final.  I'm not sure exactly how to step through as you are asking, as I seem to have problems getting the debugger to run at all with robovm... 
Error running iPhone-6s-Plus: Unable to open debugger port (127.0.0.1:53897): java.net.SocketException "Socket closed"

**Comment by Scottmitch** [comment]
@m3ltaw4y - Can you try to run with https://github.com/netty/netty/pull/4733?

**Comment by m3ltaw4y** [comment]
Forgive my ignorance, how would I do this via gradle?
(as oppsed to this)
compile 'io.netty:netty-all:4.0.33.Final'

**Comment by Scottmitch** [comment]
@m3ltaw4y - No problem. You want to build/install my branch into your local maven repo, and depend upon this new code. The version will be `io.netty:netty-all.4.0.34.Final-SNAPSHOT`. Here are the steps (do this on the same machine you will build your project with):

See http://netty.io/wiki/setting-up-development-environment.html to get ready to build.
1. git clone https://github.com/netty/netty.git
2. cd netty
3. git remote add scott https://github.com/Scottmitch/netty.git
4. git fetch scott
5. git checkout scott/platform_dep_init_exception_4.0 
6. mvn clean install -DskipTests
7. Change your application to depend upon `io.netty:netty-all.4.0.34.Final-SNAPSHOT`
8. Rebuild/deploy/test your application

**Comment by m3ltaw4y** [comment]
This did not seem to fix the problem, still seems to be crashing at the same point.  I followed your steps and then I pointed my compiler to netty/all/target/netty-all-4.0.34.Final-SNAPSHOT.jar which seemed to be right file.

**Comment by m3ltaw4y** [comment]
May have made some progress.  The application does not crash when I add this line to my robovm.xml
<forceLinkClasses><pattern>java.util.logging.ConsoleHandler</pattern></forceLinkClasses>
Though I still see this: 
java.util.logging.ErrorManager: GENERIC_FAILURE
The app does not immediately crash

**Comment by Scottmitch** [comment]
Can you provide a reproducer, and steps you used to setup the emulator and RoboVM?

**Comment by Scottmitch** [comment]
@m3ltaw4y - I'm not familiar with RoboVM, but sounds like there may be a problem with the logging configuration? Are you able to log anything at all (with `info` level or higher)?

**Comment by m3ltaw4y** [comment]
The robovm setup was generated by the newest version of libgdx's setup tool.  You could generate your own project via that possibly, and then try to do new to SimpleChannelInboundHandler somewhere in the default project it creates.  You would need to simulate on robovm as well.  After I forced the linking of the logger, things seemed to work fine, I think it is only the logging within netty that failed.

**Comment by Scottmitch** [comment]
What logging implementation are you using, and how are you configuring it for Netty? Is your emulation environment configured correctly for console logger?

**Comment by m3ltaw4y** [comment]
I'm not doing anything intentionally to setup or change logging.  It seems that robovm is missing the class  java.util.logging.ConsoleHandler and forcing it to link doesn't really solve the problem exactly, becausing the logging still throws the error I mentioned, but at least the app doesn't crash and I am able to continue running from there.  I'm not really sure the proper way to configure such things...

**Comment by Scottmitch** [comment]
See http://tutorials.jenkov.com/java-logging/configuration.html for java.util logging. We also support slf4j and log4j (see [InternalLoggerFactory](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/logging/InternalLoggerFactory.java#L54)). If you are sure the logging is setup correctly (you are able to log as expected using the logging framework of your choice independently of Netty) please report back.

**Comment by m3ltaw4y** [comment]
With  
compile 'io.netty:netty-all:4.0.34.Final-SNAPSHOT' //not a local copy
and these two lines added to my robovm.xml
    <forceLinkClasses><pattern>java.util.logging.ConsoleHandler</pattern></forceLinkClasses>
    <forceLinkClasses><pattern>java.util.logging.SimpleFormatter</pattern></forceLinkClasses>
I no longer have issues.  Logging works properly with these two lines, and no errors are generated from netty.

**Comment by Scottmitch** [comment]
@m3ltaw4y - Great thanks for confirming all is well! I also put in some cleanup code to ensure we catch any stray exceptions in the static exceptions on this code path.
