### ISSUE TITLE
OpenSslEngine.setEnabledProtocols fails to enable protocols that are currently disabled

### ISSUE THREAD

**Issue by blucas** [netty/netty#4736]
Netty Version: master (I know... :frowning: )

The ```OpenSslEngine.setEnabledProtocols()``` will not allow the user to enable a protocol that has already been disabled.  For example, netty (by default) disables ```SSLv3```. If you wish to enable ```SSLv3``` you should be able to call ```OpenSslEngine.setEnabledProtocols()``` including ```SSLv3``` as one of the parameters of the array.  Unfortunately this does not work.

The reason has to do with the implementation of the method.

It does the following:
1. Determine which protocols to disable
2. [Enable all protocols](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/OpenSslEngine.java#L1077)
3. Disable each protocol from step 1 above.

The problem is step 2 above does not work. I have no idea what ```SSL.SSL_OP_ALL``` actually does, but it doesn't do what the comment expects.

Solution:
Expose ```SSL_clear_options``` to netty via a new native method ```clearOptions()``` then use ```clearOptions``` in ```setEnabledProtocols```

Pull Requests to follow.  Will need one for netty-tcnative and netty.

**Comment by Scottmitch** [comment]
https://www.openssl.org/docs/manmaster/ssl/SSL_CTX_set_options.html
> SSL_OP_NO_SSLv3, SSL_OP_NO_TLSv1, SSL_OP_NO_TLSv1_1, SSL_OP_NO_TLSv1_2, SSL_OP_NO_DTLSv1, SSL_OP_NO_DTLSv1_2
These options turn off the SSLv3, TLSv1, TLSv1.1 or TLSv1.2 protocol versions with TLS or the DTLSv1, DTLSv1.2 versions with DTLS, respectively. As of OpenSSL 1.1.0, these options are deprecated, use SSL_CTX_set_min_proto_version and SSL_CTX_set_max_proto_version instead.

Looks like we should investigate using [SSL_CTX_set_min_proto_version](https://www.openssl.org/docs/manmaster/ssl/SSL_CTX_set_min_proto_version.html) and [SSL_CTX_set_max_proto_version](https://www.openssl.org/docs/manmaster/ssl/SSL_CTX_set_max_proto_version.html) instead.

**Comment by Scottmitch** [comment]
@blucas - Thanks for reporting. I'll submit a PR for tcnative and Netty.

**Comment by Scottmitch** [comment]
@blucas - Your approach described sounds reasonable.

**Comment by Scottmitch** [comment]
@normanmaurer - On a related note I wonder if we should be more careful about `SSL_OP_ALL`. See https://github.com/bagder/curl/blob/master/lib/vtls/openssl.c#L1730 and http://daniel.haxx.se/blog/2012/01/27/sloppily-using-ssl_op_all/.

**Comment by blucas** [comment]
@Scottmitch - On another related note (but outside the scope of this issue), it might be worth adding a ```setEnabledProtocols``` method to ```SslContextBuilder``` so that users do not have to call that method on the ```SslEngine``` implementation directly.

**Comment by Scottmitch** [comment]
> it might be worth adding a setEnabledProtocols method to SslContextBuilder

sgtm

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4737
