### ISSUE TITLE
Add ChannelHandlerContext.invoker() to 4.1

### ISSUE THREAD

**Issue by ejona86** [netty/netty#4738]
The now-defunct 5.0 had a [ChannelHandlerContext.invoker()](https://github.com/netty/netty/blob/master_deprecated/transport/src/main/java/io/netty/channel/ChannelHandlerContext.java#L148) method. I found it to be useful, and the method is already implemented; it just needs to be exposed on the interface. It's my understanding of Netty API stability policy that new methods can be added to interfaces between minor versions (thus, 4.1, since it isn't final _yet_). If 4.1 is too close to release to add the API, I understand.

I will grant that needing to use the invoker is rare and quite advanced, but in some ways it isn't that strange. When writing Http2MultiplexCodec I used the invoker because: 1) I needed to call a particular handler 2) from possibly a different thread 3) while ideally not having to deal with exceptions. Parts 2 and 3 are well-served by ChannelHandlerContext, but 1 isn't because it will call the _next_ or _previous_ handler and using the previous or next context (respectively) to compensate is unstable as the pipeline is modified.

It is possible to write your own invoker on top of `ctx.executor()`, but that seems like needless boilerplate and cause for trouble if someone has actually specified their own ChannelHandlerInvoker for the channel.

Some additional context: https://github.com/netty/netty/pull/4503#discussion_r45705972

**Comment by Scottmitch** [comment]
@normanmaurer @trustin - Any objections?

**Comment by normanmaurer** [comment]
@ejona86 works for me. Please open a pr
