### ISSUE TITLE
AsciiString.EMPTY_STRING.trim() fails in v.5.0.0.Alpha2

### ISSUE THREAD

**Issue by 2underscores-vic** [netty/netty#4741]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException

**Comment by normanmaurer** [comment]
Will have. a look

**Comment by Scottmitch** [comment]
@2underscores-vic - Thanks for reporting. I think it is still broken in 4.1.0 but important to note that the 5.0 branch is currently deprecated.

**Comment by 2underscores-vic** [comment]
Should I use 4.1 instead? What happend to 5.0 branch? Any links with more information?

**Comment by windie** [comment]
@normanmaurer fixed in #4743. Could you take a look? Thanks!

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4743 .

@windie thanks again :)

**Comment by Scottmitch** [comment]
@2underscores-vic - https://github.com/netty/netty/issues/4466
