### ISSUE TITLE
Enabling SNI, OpenSSL client from netty does not work 

### ISSUE THREAD

**Issue by jknair** [netty/netty#4746]
Netty version : 4.1 - ff11fe8 also tried with netty-4.1.0.Beta8
When trying to connect to a host with SNI enabled from the netty openssl client, handshake fails as :
 ```
OpenSSL error: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```
same issue when you use the openssl s_client :
```
openssl s_client -connect sni-enabled-host:443
140133327337120:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:770:
```
and works well for : 
```
openssl s_client -connect sni-enabled-host:443 -servername sni-enabled-host
```
The following code fails with Openssl and gives the same error but works fine with Openssl disabled (removed netty-tcnative) 
```
SSLEngine sslEngine = sslCtx.newEngine(ctx.channel().alloc(), peerHost,peerPort));
```

```
java -version 
java version "1.8.0_66"

uname -a
Linux linuxbox 4.2.1-040201-generic #201509211431 SMP Mon Sep 21 18:34:44 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

openssl version
OpenSSL 1.0.1f 6 Jan 2014
```

**Comment by normanmaurer** [comment]
@jknair I think this is the same issue as :

https://github.com/netty/netty/issues/4722

Looking into it atm.

**Comment by normanmaurer** [comment]
@jknair can you share a "full" reproducer ?

**Comment by jknair** [comment]
sorry for the delay, I will try to make one. Problem is I cant find any SNI enabled public host that will fail the handshake

**Comment by normanmaurer** [comment]
@jknair maybe there is no need at all. Let me check if I can write one myself

**Comment by normanmaurer** [comment]
@jknair can you show me a basic client setup that works with JDK version ?

Do you do the same as here:
https://www-01.ibm.com/support/knowledgecenter/#!/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/jsse2Docs/sni_extension.html
 ?

**Comment by jknair** [comment]
the following code does **NOT** work with Openssl client 
```java
SSLEngine sslEngine = sslCtx.newEngine(ctx.channel().alloc(), peerHost, peerPort);
 SSLParameters sslParameters = sslEngine.getSSLParameters();
sslParameters.setServerNames(new ArrayList<SNIServerName>(1) {{
     add(new SNIHostName(peerHost));
}});
sslEngine.setSSLParameters(sslParameters);
final SslHandler ssllHandler = new SslHandler(sslEngine);
```
and for the JDK version this works perfectly dont need to add any ```SNIServerName``` : 
```java
SSLEngine sslEngine = sslCtx.newEngine(ctx.channel().alloc(), peerHost, peerPort);
final SslHandler ssllHandler = new SslHandler(sslEngine);
```

**Comment by normanmaurer** [comment]
@jknair and peerHost and peerPort are anything public that I can hit ?

**Comment by normanmaurer** [comment]
@jknair ok I think I know whats wrong.. working on a fix.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4791

**Comment by jknair** [comment]
sorry for the delay but this worked perfectly. Thanks @normanmaurer
