### ISSUE TITLE
Cannot use HttpContentCompressor for outgoing requests

### ISSUE THREAD

**Issue by CodingFabian** [netty/netty#4748]
I want to gzip an outgoing requests. Therefore my I add a HttpContentCompressor handler:

```
          pipeline.addLast("deflater", new HttpContentCompressor(1));
```

this crashes with an exception due to the following:

HttpContentEncoder will accept my DefaultFullHttpRequest
```
    public boolean acceptOutboundMessage(Object msg) throws Exception {
        return msg instanceof HttpContent || msg instanceof HttpResponse;
    }
```
because a FullHttpMessage is a LastHttpContent which is HttpContent.

now when the code enters the encode method
```
    protected void encode(ChannelHandlerContext ctx, HttpObject msg, List<Object> out) throws Exception {
        final boolean isFull = msg instanceof HttpResponse && msg instanceof LastHttpContent;
        switch (state) {
            case AWAIT_HEADERS: {
                ensureHeaders(msg);
```
This will throw an exception:
```
io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: unexpected message type: io.netty.handler.codec.http.DefaultFullHttpRequest (expected: HttpResponse)
```

Am I missing something important here, or is gzipping a request (its a large json post) not supported?

**Comment by slandelle** [comment]
@CodingFabian Indeed, HttpContentCompressor doesn't work on the client side, the name is very misleading.

**Comment by normanmaurer** [comment]
@CodingFabian check our httpsnoop example.

**Comment by slandelle** [comment]
@normanmaurer Sorry, I think there's a misunderstanding. The question was about COMPRESSING REQUESTS, not compressing or decompressing responses.

The Snoop client sure sets up a [decompressor](https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http/snoop/HttpSnoopClientInitializer.java#L45), but not a compressor.

This question here is actually a duplicate of #2131, and AFAIK, Netty still can't compress requests on the client side. And I know the next answer: "contribs welcome" :)

**Comment by CodingFabian** [comment]
Furthermore, I think the existing (de) compressor should be better checking what to do. but maybe its hard to implement on the current type system where both are HttpContent.
