### ISSUE TITLE
WebSocketServerCompressionHandler doesn't work properly

### ISSUE THREAD

**Issue by mrniko** [netty/netty#4754]
Netty version: netty-4.1.0.CR1

Hi! I connected the `io.netty.handler.codec.http.websocketx.extensions.compression.WebSocketServerCompressionHandler` to my project ant it can't detect websocket upgrade request properly. 

`WebSocketExtensionUtil.isWebsocketUpgrade` is always returns false at WebSocketServerExtensionHandler:71 due to client sends `Connection` header with value `keep-alive, Upgrade` instead of expected `Upgrade`. After deep debug i found the cause it's in DefaultHeaders:264 line.

**Comment by normanmaurer** [comment]
@mrniko I will need to re-check the rfc but are you sure it is valid to have both values in the "Connection:" header on an upgrade ?

**Comment by mrniko** [comment]
socketio client used in FireFox works by this way. It sends `Upgrade` value only in Chrome browser. And socketio javascript server handles this correctly. Also websocket upgrade logic could be extracted to `protected` method for further extension.

**Comment by Scottmitch** [comment]
I don't see anything preventing an `upgrade` co-existing with other options.

https://tools.ietf.org/html/rfc7230#section-6.7
> When Upgrade is sent, the sender MUST also send a Connection header
   field (Section 6.1) that contains an "upgrade" connection option, in
   order to prevent Upgrade from being accidentally forwarded by
   intermediaries that might not implement the listed protocols.

**Comment by normanmaurer** [comment]
Got it... Let me fix it

**Comment by Scottmitch** [comment]
Perhaps we should have a utility method to detect upgrade which uses [containsIgnoreCase](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/AsciiString.java#L1385)

**Comment by normanmaurer** [comment]
@mrniko should be fixed by https://github.com/netty/netty/pull/4817. Please take a look...

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4817

**Comment by mrniko** [comment]
it works
