### ISSUE TITLE
Add @Sharable annotation to WebSocketClientCompressionHandler

### ISSUE THREAD

**Issue by mrniko** [netty/netty#4755]
Netty version: netty-4.1.0.CR1

Unable to use WebSocketServerCompressionHandler and WebSocketServerCompressionHandler handlers as single instances. Because of absence of @Sharable annotation.

**Comment by normanmaurer** [comment]
@mrniko you are right... I will fix it. In the meantime just create a new instance everytime.

**Comment by normanmaurer** [comment]
@mrniko PTAL https://github.com/netty/netty/pull/4769

**Comment by mrniko** [comment]
PTAL ? Sorry, what? :)

**Comment by normanmaurer** [comment]
@mrniko Please take a look ;)

**Comment by normanmaurer** [comment]
@mrniko actually only WebSocketClientCompressionHandler can be `@Sharable` as the other is keeping state. Fixed the PR.

**Comment by mrniko** [comment]
@normanmaurer OK, I got you!

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4769

**Comment by welkinxu** [comment]
@normanmaurer why WebSocketServerCompressionHandler cannot be be @Sharable . i can't understand.

**Comment by normanmaurer** [comment]
It's a subclass of `WebSocketServerExtensionHandler` which keeps state per `connection` so it cant be shared.
