### ISSUE TITLE
Update Netty internal Cleaner0 to reflect the new location of the OpenJDK Cleaner in JDK 9

### ISSUE THREAD

**Issue by chhegar** [netty/netty#4756]
There are upcoming changes in JDK 9 that will require, at least, a small update to common/src/main/java/io/netty/util/internal/Cleaner0.java.

OpenJDK issue no. 8148117: "Move sun.misc.Cleaner to jdk.internal.ref" [1], will move the Cleaner class from sun.misc to jdk.internal.ref. There is ongoing discussion about the possibility of providing a public supported API, maybe in the JDK 9 timeframe, for releasing NIO direct buffer native memory, see the core-libs-dev mail thread [2]. At the very least Cleaner0.java should be updated to have knowledge of the new location of the JDK Cleaner.

[1] https://bugs.openjdk.java.net/browse/JDK-8148117
[2] http://mail.openjdk.java.net/pipermail/core-libs-dev/2016-January/038243.html

**Comment by normanmaurer** [comment]
I will check

**Comment by chhegar** [comment]
This bug has been filed as an early heads-up. The OpenJDK changes have not been integrated into JDK 9 yet, but are due to land in the next couple of weeks.

**Comment by Scottmitch** [comment]
thanks for the heads up @chhegar !

**Comment by normanmaurer** [comment]
This was done by @varming

**Comment by IvanOVasiliev** [comment]
Has this been fixed in any netty version? I use 5.0.0Alpha2 and I still see a reference to old location sun.misc.Cleaner

**Comment by slandelle** [comment]
@IvanOVasiliev You should check the release dates.

The Netty 5 branch is currently stalled and hasn't been released for almost 10 years.
The current production branch is 4.1.
The future branch is 4.2, currently in release candidates phase.
