### ISSUE TITLE
WeightedFairQueueByteDistributor headers can be written out of order

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4758]
It is possible for the WeightedFairQueueByteDistributor to write headers out of order, and thus violate the "new stream ids must always be increasing" clause of the RFC. 

https://tools.ietf.org/html/rfc7540#section-5.1.1
>The identifier of a newly established stream MUST be numerically
   greater than all streams that the initiating endpoint has opened or
   reserved.  This governs streams that are opened using a HEADERS frame
   and streams that are reserved using PUSH_PROMISE.  An endpoint that
   receives an unexpected stream identifier MUST respond with a
   connection error (Section 5.4.1) of type PROTOCOL_ERROR.

**Comment by Scottmitch** [comment]
/cc @ejona86 @nmittler 

Possible approaches to resolve this issue:

1. Don't queue headers in flow controller.
 - We have previously discussed this and agreed that queueing the headers in the flow controller provides some benefits / conveniences. https://github.com/netty/netty/issues/4489.
2. Implement a "previous stream id look back". Whenever an allocation is done we must "look back" at the "previous stream" (current stream id - 2, assuming this is a valid stream id). If we find a "previous stream" that has not yet written its headers (and is still in a valid state, e.g. not closed) then we should instead allocate to this "previous stream". This process must iterate until the "youngest stream" which satisfies this condition is found.
 - Currently `WeightedFairQueueByteDistributor` is the only distributor that suffers from this issue. So we could implement this process outside of the distributor to ensure it is done no matter what the distributor is, but then the `UniformStreamByteDistributor` would incur unnecessary overhead. Also this would be unexpected from the distributors point of view if allocations are done outside of its control.

I'm open for more suggestions too.

**Comment by nmittler** [comment]
Queuing headers in the flow controller keeps coming up as a source of issues/added complexity and we have no metrics suggesting that it's helping performance. Certainly, the first options seems a lot simpler.

**Comment by Scottmitch** [comment]
> Certainly, the first options seems a lot simpler.

+1.

I forgot to mention that another option is to allow the distributor to have access to the `Writer` is more places. So the distributor can decide if it wants to queue header frames or not. For example if we pass the `Writer` into `updateStreamableBytes` the distributor could immediately send 0 length frames to avoid this situation if it doesn't want to deal with the complexity.

**Comment by ejona86** [comment]
Hmm... yeah, it'd be a bit of a pain to fix `WeightedFairQueueByteDistributor` for questionable gain. Yeah, bypassing flow controller for initial headers seems to be the way to go. Well, I guess it was worth a try to have everything go through the flow controller...

**Comment by Scottmitch** [comment]
Thanks for the feedback @ejona86 and @nmittler. I'll pull together a PR which takes option 1 (headers no longer queued in flow controller).
