### ISSUE TITLE
CompositeByteBuf.addComponent ownership clarification

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4760]
If all goes well `CompositeByteBuf.addComponent` will take "ownership" (will call `release()`) of the parameter. However there are cases where this is not the case. For example if the `CompositeByteBuf` has been released `addComponent` may throw an `IllegalReferenceCountException` and not release the parameter. At the very least the interface should be clarified so that the caller can understand expectations. However I would like see if there are any objections to `CompositeByteBuf.addComponent` always assuming "ownership" of the parameter. This would be analogous to a `Channel.write` always assuming responsibility of the parameter even if the underlying transport cannot actually support the write operation.

**Comment by normanmaurer** [comment]
@trustin ping again
