### ISSUE TITLE
HTTP/2 encoder frame merge does not handle integer overflow

### ISSUE THREAD

**Issue by nmittler** [netty/netty#4773]
The `DefaultHttp2ConnectionEncoder` does not handle integer overflow when merging frames.  Merge attempts should fail when integer overflow of the total size will occur: https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionEncoder.java#L360

**Comment by nmittler** [comment]
FYI @Scottmitch @louiscryan

**Comment by Scottmitch** [comment]
@nmittler - I will take care in https://github.com/netty/netty/pull/4763 as you suggested.

**Comment by nmittler** [comment]
@Scottmitch Thanks!

**Comment by Scottmitch** [comment]
Was fixed in #4763
