### ISSUE TITLE
DnsNameResolver behaves differently than DefaultNameResolver with VPN

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4778]
When on a VPN the `DnsNameResolver` is not able to resolve addresses that the `DefaultNameResolver` is able to resolve. In this particular case the ultimate call doing the resolution for `DefaultNameResolve` is `getaddrinfo` in JNI.  Should `DnsNameResolver` be able to mimic this behavior? If not it is problematic for testing purposes and the current workaround is to fall back to the `DnsNameResolver`.

**Comment by trustin** [comment]
@Scottmitch That's interesting. I wonder why `DnsNameResolver` fails to resolve a name when on VPN. Is it because your `/etc/resolv.conf` has `domain` or `search` option?

**Comment by Scottmitch** [comment]
@trustin - I can provide more details and Netty debug dumps of the dns requests/respones offline. Please email me if this would be useful and let me know what I can provide.

**Comment by trustin** [comment]
@Scottmitch Sure! Could you send me:

- your `/etc/resolv.conf`
- Wireshark dump of successful lookup via `getaddrinfo` on VPN
- Wireshark/`LoggingHandler` dump of unsuccessful lookup via `DnsNameResolver` on VPN

to my personal e-mail address?

**Comment by Scottmitch** [comment]
@trustin - Thanks a bunch for the help! Check you email.

**Comment by trustin** [comment]
@Scottmitch Sorry it's taking longer than expected. Trying to reduce my backlog ..

**Comment by Scottmitch** [comment]
@trustin - No problem. Let me know if you need any more info when you get around to it.

**Comment by slandelle** [comment]
(just scanning issues) Should this be closed as fixed by #6321?

**Comment by normanmaurer** [comment]
yes!

**Comment by Scottmitch** [comment]
yip all good now ... just missing some features :)
