### ISSUE TITLE
Certificate failing set in OpenSslServerContext on Linux under CR1

### ISSUE THREAD

**Issue by robeden** [netty/netty#4793]
Netty version: 4.1.0.CR1

Context:
I have at least one certificate that fails to initialize in OpenSslServerContext ("javax.net.ssl.SSLException: failed to set certificate chain") under Linux that used to work under beta8.

Here is output from my test app when the failure occurs:

>     OpenSSL: OpenSSL 1.0.1e-fips 11 Feb 2013
    Netty:
       netty-buffer = netty-buffer-4.1.0.CR1.c681a40
       netty-codec = netty-codec-4.1.0.CR1.c681a40
       netty-codec-http = netty-codec-http-4.1.0.CR1.c681a40
       netty-codec-http2 = netty-codec-http2-4.1.0.CR1.c681a40
       netty-common = netty-common-4.1.0.CR1.c681a40
       netty-handler = netty-handler-4.1.0.CR1.c681a40
       netty-resolver = netty-resolver-4.1.0.CR1.c681a40
       netty-tcnative = netty-tcnative-1.1.33.Fork11.c581f60
       netty-transport = netty-transport-4.1.0.CR1.c681a40
    Exception in thread "main" javax.net.ssl.SSLException: failed to set certificate chain
    	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:451)
    	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:408)
    	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:315)
    	at com.trustedcs.LinuxCertExplosionSslContext.testSSLContextBuild(LinuxCertExplosionSslContext.java:168)
    	at com.trustedcs.LinuxCertExplosionSslContext.testGenCert_bad2(LinuxCertExplosionSslContext.java:85)
    	at com.trustedcs.LinuxCertExplosionSslContext.main(LinuxCertExplosionSslContext.java:99)
    Caused by: javax.net.ssl.SSLException: failed to set certificate chain: error:0906D064:PEM routines:PEM_read_bio:bad base64 decode
    	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:446)
    	... 5 more

Steps to reproduce:
See [this Gist](https://gist.github.com/robeden/1c85bc78e5557ce5fe56) for full reproduction information.

$ uname -a
> Linux reden-dev1.il.tcs-sec.com 2.6.32-504.3.3.el6.x86_64 #1 SMP Wed Dec 17 01:55:02 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
    
$ java -version
> java version "1.8.0_66"
    Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
    Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

$ openssl version
> OpenSSL 1.0.1e-fips 11 Feb 2013

We've tried this on a couple systems. It seems to work with OpenSSL 1.0.2 but not with 1.0.1. Prior to CR1, things worked fine on this system (except for the issue relating certs with an encoded length divisible by 76, which is the reason we're trying to update).

**Comment by normanmaurer** [comment]
@robeden I guess you can't share the cert that fails ?

**Comment by robeden** [comment]
@normanmaurer It's in the sample code in the Gist. It's just a test cert, so of no real value.

**Comment by normanmaurer** [comment]
@robeden ah cool! Thanks will have a look.

**Comment by Scottmitch** [comment]
This may be related to https://github.com/netty/netty/pull/4595

**Comment by normanmaurer** [comment]
I dont think so

**Comment by normanmaurer** [comment]
@Scottmitch actually you are right and it is related.. Working on a fix.

**Comment by normanmaurer** [comment]
@robeden Please check https://github.com/netty/netty/pull/4846

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4846

**Comment by robeden** [comment]
Thanks, I'll check it out on Monday.

**Comment by robeden** [comment]
I can confirm that the fix worked for us. Thanks! (Tested with 4.1.0.CR3-20160211)
