### ISSUE TITLE
Out-of-order streams with `StreamBufferingEncoder`

### ISSUE THREAD

**Issue by jchambers** [netty/netty#4802]
I've noticed behavior in testing with 4.1.0 CR1 where streams are sent out of order when the client is enforcing a stream limit (and the server has actually set a limit). I haven't yet nailed down the precise cause.

What I'm trying to do is send a thousand messages from a client to a server. Each of those messages gets written by my `Http2ConnectionHandler` subclass as a `HEADER`/`DATA` frame pair. I noticed that some messages were getting lost, and when I added a `frameLogger` to my handler, I noticed that some frames were being sent out of order. The server imposes a stream limit of 8, and the order of outbound streams I'm seeing from the client is:

`3, 5, 7, 9, 11, 13, 15, 17, 19, 33, 31, 29, 27, 25, 23, 21, 35, 37, …`

For what it's worth, the server agrees about the order.

According to the [HTTP/2 spec](https://httpwg.github.io/specs/rfc7540.html#StreamIdentifiers):

> The identifier of a newly established stream MUST be numerically greater than all streams that the initiating endpoint has opened or reserved. This governs streams that are opened using a HEADERS frame and streams that are reserved using PUSH_PROMISE. An endpoint that receives an unexpected stream identifier MUST respond with a connection error (Section 5.4.1) of type PROTOCOL_ERROR.

As a result, streams 21-31 get lost because stream 33 arrived first. In my particular case—and I suspect in others—that means the server never replies (that seems like a maybe-separate bug), and the stream never closes, which I suspect could compound the problem in the `StreamBufferingEncoder`.

~~I wrote a minimal test that does NOT exhibit this problem, so I wonder if this is maybe a timing issue exposed by the work my client and server are doing when messages come and go.~~ (EDIT: [minimal test case](https://gist.github.com/jchambers/3a1eb112c205cd4ad125) DOES reproduce this problem) The problem does not surface if no stream limit is set. I think this is distinct from #4704 because I'm using my own subclass of `Http2ConnectionHandler` that writes frames directly and increments its own stream counter (it does almost exactly what `DefaultEndpoint` is doing as of 7d3cf1f et al).

I've posted the frame log (from the client's perspective) at https://gist.github.com/jchambers/9ce5ebedf0be4f292079. I'll keep poking at this a bit more, but wanted to open the report soon-ish in case the cause is immediately obvious to somebody else.

Thanks!

**Comment by jchambers** [comment]
I lied! This totally happens with my minimal test case! I just had the number of frames too low to notice. You can find the minimal test case at https://gist.github.com/jchambers/3a1eb112c205cd4ad125.

**Comment by jchambers** [comment]
Oops—looks like this is a duplicate of #4758.

**Comment by Scottmitch** [comment]
@jchambers - Yes looks like a duplicate of #4758 ... sorry I know this one can take a bunch of time to track down ... the PR that resolves the issue (https://github.com/netty/netty/issues/4788) attempts to increase visibility in this area too.

**Comment by jchambers** [comment]
Sounds good. Thanks! FWIW, I updated to 4.1 CR2 and can verify that this issue is fixed.
