### ISSUE TITLE
Make tcnative version dependency more clear

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4808]
Now that we are updating tcnative more frequently we should consider having a version compatibility check explicitly run to ensure the correct version is being loaded. Perhaps this would make sense to have when we load openssl in [OpenSsl.java](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/OpenSsl.java#L58).

**Comment by Scottmitch** [comment]
@normanmaurer @trustin @nmittler - FYI.

**Comment by nmittler** [comment]
@Scottmitch SGTM

**Comment by normanmaurer** [comment]
@Scottmitch sounds good. I can take care.

**Comment by Scottmitch** [comment]
thanks @normanmaurer !

**Comment by normanmaurer** [comment]
This was done by adding the netty bom
