### ISSUE TITLE
Expose defaultMachineId from DefaultChannelId

### ISSUE THREAD

**Issue by CodingFabian** [netty/netty#4818]
would it be reasonable to expose the defaultMachineId somehow?
Maybe moving it to a helper and making public?

I need such a functionality at the moment, and when looking "on the internet", there are plenty of really bad or sub-par implementations of what I think is actually solved pretty nicely in Netty code.

What you think?

**Comment by normanmaurer** [comment]
@CodingFabian where is it currently located ?

**Comment by CodingFabian** [comment]
It is an internal in DefaultChannelId, where it is used as "base" to compute ChannelIds from (using the machineid, processid, counter and random time stuff)

**Comment by CodingFabian** [comment]
io.netty.channel.DefaultChannelId.MACHINE_ID
and the static initializer part creating it.

I understand that this is not core business of netty, and maybe netty doesnt want to support this, but the code is very elaborate, and it reads out all network interfaces, so it is somehow netty related :)

As it is used as "helper" inside netty, I just thought it would be possible to open it up a bit.

**Comment by CodingFabian** [comment]
I have illustrated my idea with a PR. Naming is not final of course. Feedback welcome.

**Comment by normanmaurer** [comment]
Fixed... thanks @CodingFabian
