### ISSUE TITLE
Possible race condition in ResourceLeakDetector

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty#4827]
Context: I work on the gRPC project, which uses netty.  

I ran a race detector on our code and found a possible race condition in ResourceLeakDetector.  The relevant part of the stack trace is:

    #0 io.netty.util.ResourceLeakDetector.open(Ljava/lang/Object;)Lio/netty/util/ResourceLeak; (ResourceLeakDetector.java:207)  
    #1 io.netty.buffer.AbstractByteBufAllocator.toLeakAwareBuffer(Lio/netty/buffer/ByteBuf;)Lio/netty/buffer/ByteBuf; (AbstractByteBufAllocator.java:35)  
    #2 io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(II)Lio/netty/buffer/ByteBuf; (PooledByteBufAllocator.java:271)  
    #3 io.netty.buffer.AbstractByteBufAllocator.directBuffer(II)Lio/netty/buffer/ByteBuf; (AbstractByteBufAllocator.java:157)  
    #4 io.netty.buffer.AbstractByteBufAllocator.directBuffer(I)Lio/netty/buffer/ByteBuf; (AbstractByteBufAllocator.java:148)  
    #5 io.netty.buffer.AbstractByteBufAllocator.buffer(I)Lio/netty/buffer/ByteBuf; (AbstractByteBufAllocator.java:85)  

It appears that the write to `leakCheckCnt` in ResourceLeakDetector.open can be written to by multiple threads, since there is a static instance of RLD in AbstractByteBuf.leakDetector

cc: @nmittler & @normanmaurer

**Comment by normanmaurer** [comment]
@carl-mastrangelo will check...

**Comment by normanmaurer** [comment]
@carl-mastrangelo that is expected as we not care much about correctness and trade it for performance. It is only used to detect if we want to sample for a leak or not.

**Comment by carl-mastrangelo** [comment]
I know this is long closed, but this is a kind of interesting read on benign races becoming not benign:

https://software.intel.com/en-us/blogs/2013/01/06/benign-data-races-what-could-possibly-go-wrong

There's even an example of ref counting not being guarded, same as this issue.

**Comment by Scottmitch** [comment]
@normanmaurer - any objection to trying `AtomicLongFieldUpdater` (or AtomicLong) and see if performance is negatively impacted?

**Comment by cchantep** [comment]
Seems to encounter the same issue: https://stackoverflow.com/questions/47638309/typical-ref-counting-for-a-handler-pipeline (trace look like the one at https://github.com/grpc/grpc-java/issues/3353 )

**Comment by carl-mastrangelo** [comment]
The code in this issue has since been rewritten so it's unlikely this issue is the actual cause.

**Comment by cchantep** [comment]
Fix published? Otherwise look like another race issue

**Comment by carl-mastrangelo** [comment]
Resource Leak Detector reports leaks.   This issue is about race conditions in the detector itself.  Looking at the  SO link, it's just a leak somewhere.

**Comment by cchantep** [comment]
Race condition in the leak detector seems prone to lead to bad reporting to me, specially as the report cannot be raised unitly.

**Comment by carl-mastrangelo** [comment]
@cchantep The race has since been fixed.  In any case, I think you should file a new issue instead of reusing this one.
