### ISSUE TITLE
OpenSslContext throws UnsupportedOperationException when Unsafe not available 

### ISSUE THREAD

**Issue by floragunncom** [netty/netty#4828]
Netty 4.0.34.Final on OS X, Unsafe not available due to SecurityManager and restrictive policy file.

So this warning is issued: "[io.netty.util.internal.PlatformDependent] Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability."

OpenSslContext constructor fails with a UnsupportedOperationException because in OpenSslContext.java:542 "UnpooledDirectByteBuf.memoryAddress()" is not supported.

<pre>
Caused by: java.lang.UnsupportedOperationException
	at io.netty.buffer.UnpooledDirectByteBuf.memoryAddress(UnpooledDirectByteBuf.java:210)
	at io.netty.handler.ssl.OpenSslContext.newBIO(OpenSslContext.java:542)
	at io.netty.handler.ssl.OpenSslContext.toBIO(OpenSslContext.java:533)
	at io.netty.handler.ssl.OpenSslClientContext.<init>(OpenSslClientContext.java:289)
</pre>

**Comment by normanmaurer** [comment]
@floragunncom which java version and java brand ?

**Comment by floragunncom** [comment]
Oracle 1.8.0_45 on Mac OS Yosemite

java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

I need to create a new Open SSL Engine and i do it with:
<pre>
sslContext.newEngine(PooledByteBufAllocator.DEFAULT);
</pre>

Maybe this is the flaw?

**Comment by normanmaurer** [comment]
is it osgi ?

**Comment by normanmaurer** [comment]
@floragunncom that said I think we should use JDK provider if Unsafe is not present. I will come up with a patch

**Comment by normanmaurer** [comment]
@floragunncom actually I think we not need unsafe for OpenSsl. Working on a fix

**Comment by normanmaurer** [comment]
Fixed...
