### ISSUE TITLE
Race in PoolArena.allocate

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty#4829]
It appears there might be a race in `io.netty.buffer.PoolArena.allocate`, where `allocationsTiny` is incremented.  While the value is incremented under a lock, it also appears to be mutated elsewhere in the file without a lock.  A race detector suggested the two places where the class accesses this field in an unsynchronized way:
```
  Read of size 8 at 0x7f2f7be16108 by thread T53 (mutexes: write M95278):
    #0 io.netty.buffer.PoolArena.allocate(Lio/netty/buffer/PoolThreadCache;Lio/netty/buffer/PooledByteBuf;I)V (PoolArena.java:198)  
    #1 io.netty.buffer.PoolArena.reallocate(Lio/netty/buffer/PooledByteBuf;IZ)V (PoolArena.java:359)  
    #2 io.netty.buffer.PooledByteBuf.capacity(I)Lio/netty/buffer/ByteBuf; (PooledByteBuf.java:120)  
    #3 io.netty.buffer.AbstractByteBuf.ensureWritable0(I)V (AbstractByteBuf.java:269)  
    #4 io.netty.buffer.AbstractByteBuf.ensureWritable(I)Lio/netty/buffer/ByteBuf; (AbstractByteBuf.java:250)  
```
and
```
    #0 io.netty.buffer.PoolArena.allocate(Lio/netty/buffer/PoolThreadCache;Lio/netty/buffer/PooledByteBuf;I)V (PoolArena.java:198)  
    #1 io.netty.buffer.PoolArena.allocate(Lio/netty/buffer/PoolThreadCache;II)Lio/netty/buffer/PooledByteBuf; (PoolArena.java:133)  
    #2 io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(II)Lio/netty/buffer/ByteBuf; (PooledByteBufAllocator.java:262)  
    #3 io.netty.buffer.AbstractByteBufAllocator.directBuffer(II)Lio/netty/buffer/ByteBuf; (AbstractByteBufAllocator.java:157)  
    #4 io.netty.buffer.AbstractByteBufAllocator.directBuffer(I)Lio/netty/buffer/ByteBuf; (AbstractByteBufAllocator.java:148)  
```
cc: @nmittler & @normanmaurer

**Comment by normanmaurer** [comment]
Will check...

**Comment by buchgr** [comment]
yep that's a possible race, but it doesn't really happen in practice and I think if it does nobody will notice or care :).

It may happen if two threads have the same arena's assigned to them, and those two threads need to concurrently allocate from two different tiny size classes and there must not be any free regions available in the thread caches for both of those two tiny size classes (same is true for `allocationsSmall`).

However, by default Netty settings, each thread has its own arena (cores * 2) and almost all tiny allocations should be served by the cache. If it happens it shouldn't matter, cause `allocationsTiny` and `allocationsSmall` are just counter variables for stats, that aren't really in use.

Just saying ... still a bug :smile:

**Comment by normanmaurer** [comment]
@buchgr I agree... I'm not sure if it really worth to care here and take the performance hit. That said maybe we should and just allow to disable recording metrics. WDYT ?

**Comment by buchgr** [comment]
@normanmaurer up to you :-). I think correctness goes over performance and options for disabling/enabling is just adding unnecessary complexity. That being said, I think if the thread caches work correctly (>99.9% hit rate), there will not be a performance impact.

You can also leave this open for me to have a look at in ~4 weeks. I am planning to add some stat reporting to the allocator, to better understand what's happening in there for grpc.

**Comment by normanmaurer** [comment]
@buchgr let me maybe just fix it for now and we can revisit later. WDYT ?

**Comment by buchgr** [comment]
@normanmaurer sgtm

**Comment by carl-mastrangelo** [comment]
@buchgr fwiw the race detector found this when running our unit tests, which I believe are not atypical users of netty.  The race detector is similar to valgrind, which reports suspicious memory accesses.  To this end, I don't believe the race is hypothetical.

**Comment by buchgr** [comment]
@carl-mastrangelo do you know which unit test it was? If my understanding of the code is correct, a necessary condition for the race to happen would be that this test uses more than `2 * ncores` many event loops? You are right in saying that it's not hypothetical, it can happen, but if it happens nothing happens so to say :). it's just an unused stat counter. I am all for fixing it.

**Comment by buchgr** [comment]
@carl-mastrangelo that would actually be really helpful. If it happens with lte `2 * ncores` threads, then this might point at the logic assigning arenas to threads having a bug, which would be important to fix.

**Comment by carl-mastrangelo** [comment]
@buchgr I found it in this test: https://github.com/grpc/grpc-java/blob/master/interop-testing/src/test/java/io/grpc/testing/integration/Http2NettyLocalChannelTest.java  but It happens for most of the other tests in the same directory.

If it is infact a harmless race, then its probably okay.  I don't think I can configure my race detector to ignore particular races, so fixing this would help de-noise my test runs.

**Comment by buchgr** [comment]
@carl-mastrangelo thanks! I ll take a look. I assume the race detector is google internal?

**Comment by carl-mastrangelo** [comment]
Yeah, sadly.  Otherwise I would be more forthcoming with details.

**Comment by normanmaurer** [comment]
Any chance to opensource it ? **hint**

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4974
