### ISSUE TITLE
Race in OpenSslContext

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty#4833]
This one seems more hygienic than anything.  I have not included stack traces as I fear they may be internal details, but I did some looking and it seems that OpenSslCtx causes a data race in the JNI tcnative library.  It appears that the `ctx` variable is gaurded most of the time by OpenSslContext.class, but a race can arise where the context is used by two threads creating and shutting down an OpenSslEngine at the same time.  

From my guess, OpenSslContext.newEngine needs to be gaurded by the class lock.

(The race is on the info_callback function pointer in the ssl_ctx)

**Comment by carl-mastrangelo** [comment]
cc: @nmittler & @normanmaurer

**Comment by Scottmitch** [comment]
@normanmaurer - I looks like the synchronization of `ctx` in OpenSslContext is to ensure that multiple operations use the same `ctx` object (where it is necessary). I'm guessing the rational for no synchronization on the `newEngine` is `ctx` is volatile and it is expected `SSL.newSSL` will throw an exception if the operation fails (`tcn_ThrowException(e, "cannot create new ssl");`) ... WDYT?

**Comment by normanmaurer** [comment]
I think we fixed this a long time ago... Closing
