### ISSUE TITLE
Race in AddressResolverGroup

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty#4834]
https://github.com/netty/netty/blob/4.1/resolver/src/main/java/io/netty/resolver/AddressResolverGroup.java

Here, `resolvers` is synchronized when calling .get(), but not in the future callback `resolvers.remove(executor);`

**Comment by carl-mastrangelo** [comment]
cc: @nmittler & @normanmaurer

**Comment by slandelle** [comment]
Why not use a CHMv8 here? It seems the original concern was `AddressResolver` instantiation cost, but that's what computeIfAbsent is for. This would let us remove all the synchronized blocks.

**Comment by normanmaurer** [comment]
Because it's java8 only... Will fix the race though

**Comment by slandelle** [comment]
@normanmaurer I'm referring to your internal fork: https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/chmv8/ConcurrentHashMapV8.java

**Comment by normanmaurer** [comment]
@trustin WDYT?

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4844
