### ISSUE TITLE
CorsConfigBuilder allowNullOrigin method should be public instead of package private

### ISSUE THREAD

**Issue by odbuser2** [netty/netty#4835]
Netty version: 4.1.0-CR1

Class:
io.netty.handler.codec.http.cors.CorsConfigBuilder

Method:
method "allowNullOrigin" should be public but it is package private (no modifier)

**Comment by Scottmitch** [comment]
sgtm

**Comment by windie** [comment]
Fixed in #4852

**Comment by Scottmitch** [comment]
Thanks for the patch @windie !
