### ISSUE TITLE
HTTP/2 codec may not always call Http2Connection$Listener.onStreamRemoved

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4838]
If `Http2Connection$Listener.onStreamAdded` is called it is not always the case that `Http2Connection$Listener.onStreamRemoved` will be called. Some use cases (including `InboundHttp2ToHttpAdapter`) depend upon the `onStreamRemoved` method to be called in order to clean up allocated buffers.

[Http2ConnectionHandler.channelInactive](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L180) currently only iterates over active streams, and this does not account for streams which may still exist but are not active.

**Comment by Scottmitch** [comment]
@nmittler - FYI

related to https://github.com/netty/netty/issues/4780#issuecomment-179849253

**Comment by nmittler** [comment]
@Scottmitch yikes! Are you working on a patch?

**Comment by Scottmitch** [comment]
@nmittler - I was planning on it, but haven't got around to it yet.

**Comment by Scottmitch** [comment]
pr pending
