### ISSUE TITLE
JVM crash when websocket is closed from client

### ISSUE THREAD

**Issue by tmihalcin** [netty/netty#4841]
I'm using vert.x 3.2.0 with Netty 4.0.33.Final(tried 4.0.34.Final as well).

Whenever I close browser window, which has active websocket connection to server, JVM crashes.

These are last lines from application log:
`2016-02-04 20:33:41.151 [vert.x-eventloop-thread-1] DEBUG io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=8
2016-02-04 20:33:41.153 [vert.x-eventloop-thread-1] DEBUG io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder - Decoding WebSocket Frame length=2`

Attached hs_err_pid.log file

[hs_err_pid26167.txt](https://github.com/netty/netty/files/118211/hs_err_pid26167.txt)

`$uname -a`
`Linux raspberrypi 3.18.11-v7+ #781 SMP PREEMPT Tue Apr 21 18:07:59 BST 2015 armv7l GNU/Linux`

`java -version`
`java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) Client VM (build 25.0-b70, mixed mode)`

I had no such issues running on the same platform using vertx 2.1.5 with Netty 4.0.21.Final

**Comment by normanmaurer** [comment]
@tmihalcin can you share the app that allows to reproduce this ?

**Comment by normanmaurer** [comment]
Actually I think I see where the problem is... Let me fix it

**Comment by tmihalcin** [comment]
If you still need sample app, just let me know

**Comment by normanmaurer** [comment]
No all should be good. I'm right that you can only reproduce it on the PI?

**Comment by normanmaurer** [comment]
@tmihalcin also can you share which raspberrypi and which linux you are using ? Would be interested to  know.

**Comment by normanmaurer** [comment]
@tmihalcin this should fix it: https://github.com/netty/netty/pull/4845

**Comment by tmihalcin** [comment]
Yes you're right. No issues on Windows machine.
I'm using RPI2 with Raspbian.
Thank you for quick fix.

**Comment by tmihalcin** [comment]
@normanmaurer I have patched netty-buffer with your fix and I confirm that it works.
Thank you.
