### ISSUE TITLE
Increased number of IP packets, Segmentation by TLS layer below the MTU size.

### ISSUE THREAD

**Issue by ramahmoo** [netty/netty#4866]
We are using Netty as HttpServer and also HTTP client.

It was observed that IP packets which contains the TLS Application Data, are segmented in the TLS layer, significantly lower than the MTU size of 1500 octets.

This significantly increases the number of outgoing IP packets. Typically, a hardware-based segmentation is done by the network adapter on the IP layer. Therefore, a software-based segmentation by application at TLS layer seems unnecessary.

I am eager to know at which level this segmentation is happening, is Netty doing this or the underlying SSL Implementation? Any idea or advice, this is a crticial requirement from our customer.

![image](https://cloud.githubusercontent.com/assets/16151092/13005295/56f772be-d181-11e5-8867-f8f74347b47a.png)

**Comment by ramahmoo** [comment]
we are using Netty version 4.0.33.Final with OpenSSL.

**Comment by Scottmitch** [comment]
Can you show us some code demonstrating how are you configuring your socket/TLS options? How often do you call `flush` on the channel?

**Comment by ramahmoo** [comment]
Our application is acting as proxy.
The side accepting client requests extends SimpleChannelInboundHandler and has following pipeline
```java
ChannelPipeline pipeline = channel.pipeline();
addSSLServerHandler(pipeline);
pipeline.addLast("http-decoder", new HttpRequestDecoder());
pipeline.addLast("http-encoder", new HttpResponseEncoder());
pipeline.addLast("request_Handler", new BusinessModuleToProxyHandler());
```
The side forwarding requests and writing back responses also extends the SimpleChannelInboundHandler and has following
```java
ChannelPipeline pipeline = channel.pipeline();
addSSLClientHandler(pipeline);
pipeline.addLast("decoder", new HttpResponseDecoder());
pipeline.addLast("encoder", new HttpRequestEncoder());
pipeline.addLast("response_handler", new ProxyToBusinessServerHandler());
```
SSL setup is per JSSE standard.

Both side handlers override the method
```java
protected void channelRead0(ChannelHandlerContext ctx, HttpObject msg)
```

The msg object which could be HttpRequest/HttpResponse or HttpContent is written to wire using
```java
protected ChannelFuture write(HttpObject msg) {
		if (msg instanceof ReferenceCounted) {
			((ReferenceCounted) msg).retain();
		}

		ChannelFuture future = this.channel.writeAndFlush(msg).addListener(
				ChannelFutureListener.FIRE_EXCEPTION_ON_FAILURE);

		return future;
	}
```

**Comment by ramahmoo** [comment]
If i use the HttpObjectAggregator in pipeline then in channelRead0() i get the FullHttpRequest/FullHttpResponse and in wireshark trace i can see the application data is not segmented. 

But problem with HttpObjectAggregator() is max. size should be known (which is not possible as in proxy application we have to handle theoretically unlimited size post data) and also i am doubtful that it would effect the application resource utilization as it aggregates the data in memory.

**Comment by Scottmitch** [comment]
Instead of calling `writeAndFlush` can you call `write` and then `flush` at some later time (e.g. in `channelReadComplete`)?

> we have to handle theoretically unlimited size post data) and also i am doubtful that it would effect the application resource utilization as it aggregates the data in memory.

I'm a bit confused. It sounds like you would be OK with aggregating data, but because you have to accept unlimited amount of data this is not practical, and then you draw the conclusion that aggregating (potentially unlimited) data would not impact "resource utilization". Can you clarify what "resource utilization" means here?

**Comment by ramahmoo** [comment]
Sorry, here i meant memory utilization e.g when 1000's of requests with large data set have to be served in parallel.

**Comment by ramahmoo** [comment]
Thanks for suggesstion.

**Comment by ramahmoo** [comment]
What about if i compare the aggregated size of bytes being written and if they are smaller than predefined MTU size then do only write() and if bigger or equal to MTU size the writeAnFlush? Don't know how can i get the size in byte of HttpRequest/HttpResponse object(containing only meta information) 

Here is snippet from my thought
```java

private volatile int pendingFlushBytes = 0;
private int mtuSize = 1500;

protected ChannelFuture write(HttpObject msg) {

	if (msg instanceof ReferenceCounted) {
		((ReferenceCounted) msg).retain();
	}

	if ((msg instanceof HttpRequest) || (msg instanceof HttpResponse)) {
		this.pendingFlushBytes += getMessageSize(msg);
	} else {
		this.pendingFlushBytes += ((HttpContent) msg).content().readableBytes();
	}
	if (this.pendingFlushBytes >= this.mtuSize || (msg instanceof LastHttpContent)) {
		this.pendingFlushBytes = 0;
		return write(msg, true);
	} else {			
		return write(msg, false);
	}
}
``

**Comment by Scottmitch** [comment]
@ramahmoo - If that policy works for your use case then go for it :) Seems like it would be nice to not have to worry about MTU and instead write as much as you can before control is returned to the event loop (channelReadComplete can be used as a trigger point for this). If you are writing from threads other than the event loop thread you may have to have another policy.

**Comment by ramahmoo** [comment]
Closing this issue. This can be handled at application level and seems not an issue in Netty.
