### ISSUE TITLE
[Question] ChannelHandlerInvoker - example of usage

### ISSUE THREAD

**Issue by maseev** [netty/netty#4867]
I noticed that starting from Netty 4.1 [ChannelHandlerInvoker](http://netty.io/4.1/api/io/netty/channel/ChannelHandlerInvoker.html) can be specified in ChannelPipeline by calling one of the [addLast](http://netty.io/4.1/api/io/netty/channel/ChannelPipeline.html#addLast(io.netty.channel.ChannelHandlerInvoker,%20io.netty.channel.ChannelHandler...)) methods.

If I understood correctly (this question is related to [this](https://github.com/netty/netty/issues/2398) ticket though), by using my custom ChannelHandlerInvoker instead of the default one I can emulate the legacy behaviour that is available in Netty 3, when you basically can call write or writeAndFlush methods outside of the Netty worker threads.

On the other hand, in Netty 4, if you call a [ChannelHandlerContext.write](http://netty.io/4.0/api/io/netty/channel/ChannelHandlerContext.html#write(java.lang.Object)) method outside of the worker thread, the object you're trying to write will be [wrapped](https://github.com/netty/netty/blob/4.0/transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java#L690) in the WriteTask and delayed for the later execution (some kind of queue is involved in this process, I think).

Let's assume that we have an application which is based on Netty (obviously), and some kind of lock-free data structure (LMAX Disruptor, for example) that is used in order to parallel the parsing of incoming messages. So, Netty reads the incoming data from the IO thread and publishes that data in the ring buffer. A bunch of worker threads (not related to Netty) are constantly reading from the ring buffer, do some stuff and write some data back to the channel.

I would like to avoid creating the WriteTasks as well as pending my write requests to the Netty queue by using my custom ChannelHandlerInvoker. Is it safe, let's say to create something like this (see an example below) in order to achieve lower latency and higher throughput?

```java
public class CustomChannelHandlerInvoker extends DefaultChannelHandlerInvoker {

  private static final int MESSAGE_THRESHOLD = 10;

  private final AtomicInteger messageCounter;

  public CustomChannelHandlerInvoker(EventExecutor executor) {
    super(executor);
    messageCounter = new AtomicInteger(0);
  }

  @Override
  public void invokeWrite(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) {
    ChannelHandlerInvokerUtil.invokeWriteNow(ctx, msg, promise);
    
    if (messageCounter.incrementAndGet() >= MESSAGE_THRESHOLD) {
      ChannelHandlerInvokerUtil.invokeFlushNow(ctx);
      messageCounter.set(0);
    }
  }

  @Override
  public void invokeFlush(ChannelHandlerContext ctx) {
    ChannelHandlerInvokerUtil.invokeFlushNow(ctx);
  }
}
```

By the way, it would be great to see other use cases of custom ChannelHandlerInvoker implementations.

Thanks in advance for any help.

**Comment by Scottmitch** [comment]
Not sure if this will work. In addition to all of the `ChannelOutboundHandler`s in your pipeline must be able to handle this threading model (Netty's handler most likely won't) the [ChannelOutboundBuffer used by AbstractChannel.Unsafe.write()](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/AbstractChannel.java#L795) is not thread safe. Even if the `ChannelOutboundBuffer` was configurable, I'm guessing there may be other issues with the channel implementations which typically operate in a more constrained threading model. @normanmaurer - WDYT?

**Comment by maseev** [comment]
Ok. So calling ChannelOutboundHandler.write isn't thread safe because of the ChannelOutboundBuffer. Let's look at this approach from a different point of view. What about adding another ring buffer, which would be used by the first ring buffer worker threads in order to publish messages that are ready to be sent to the clients? So we've got something like this:

- N IO threads (Netty IO threds) are reading data from the network and publish that data to the first ring buffer
- M worker threads are constantly reading from the first ring buffer, parse messages, do some logic and put another messages to the second ring buffer
- 1 worker thread is reading messages from the second ring buffer and calls the write method which sends data back to the clients

As a result, we've got only one thread which is calling the ChannelHandlerContext.write method. Of course, we must have only one channel handler adapter in the pipeline which would be sending actual data back (MessageToByteEncoder or something).

What do you think @Scottmitch?

**Comment by maseev** [comment]
I think, I was able to figure it out. So, the custom ChannelHandlerInvoker now looks like the following:

```java
public class CustomChannelHandlerInvoker extends DefaultChannelHandlerInvoker {

  public CustomChannelHandlerInvoker(EventExecutor executor) {
    super(executor);
  }

  @Override
  public void invokeWrite(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) {
    ctx.channel().unsafe().write(msg, promise);
  }

  @Override
  public void invokeFlush(ChannelHandlerContext ctx) {
    ctx.channel().unsafe().flush();
  }
}
```

And the batching logic was moved to a ring buffer handler which is responsible for writing messages back to the network.

It works ok as long as I write and flush each message right away without creating a batch in the ring buffer handler. On the other hand, if I try to write and flush a big byte buffer, for some reason, `ctx.channel().isWritable()` becomes false and the byte buffer which I'm trying to write gets saved somewhere under the hood to be sent later, which leads to the broken byte buffer (because it's shared now between a Netty IO thread and a ring buffer handler's thread).

Is it possible to tell Netty that I want to send a big byte buffer to the network right away without pending  my request? I'm aware of `unsafe.flush()`, but it seems that this method isn't that simple as it might look like at the first glance.

**Comment by Scottmitch** [comment]
@maseev - Just a quick glance again but the approach seems similar to the previous approach. I would avoid using `unsafe` unless you are sure you know what you are doing. It is not guaranteed to be thread safe so you must take care in the threading model (your threading model and netty's) when using it.

**Comment by maseev** [comment]
@Scottmitch - with a threading model I described, it's guaranteed that all write and flush operations are going to happen from the single thread. But it turns out that `unsafe().flush()` can be delayed ([here](https://github.com/netty/netty/blob/43ebbc3fa065155fa67732b0cbd7c12843b0f3f7/transport/src/main/java/io/netty/channel/nio/AbstractNioChannel.java#L304) and [here](https://github.com/netty/netty/blob/43ebbc3fa065155fa67732b0cbd7c12843b0f3f7/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollChannel.java#L396) if you're using Linux epoll). 

So if you're trying to achieve a very low latency (less than a millisecond per request) than Netty isn't the best choice. I decided to stick with good old IO. With the old model, I can simply parallel reading and writing by using different threads.
