### ISSUE TITLE
DefaultHttp2ConnectionEncoder tries to create new stream for ids that was reset by client

### ISSUE THREAD

**Issue by nhnFreespirit** [netty/netty#4868]
Hi, 

I'm prototyping using Netty's codec.http2 as a replacement for a home spun http2 codec in a very high traffic environment.

So far so good. Using 4.1.0-CR2, I'm currently testing in a test environment with upwards of 40 RPS and the clients are happy, but I am seeing a number of exceptions like the following:

```
An exception was thrown by io.netty.channel.ChannelPromiseAggregator.operationComplete()
java.lang.IllegalStateException: complete already: DefaultChannelPromise@5e80403c(failure: io.netty.handler.codec.http2.Http2Exception: Request stream 109717 is not correct for server connection)
    at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:419)
    at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87)
    at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:28)
    at io.netty.util.concurrent.PromiseAggregator.operationComplete(PromiseAggregator.java:98)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:568)
    at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:416)
    at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87)
    at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:28)
    at io.netty.util.concurrent.PromiseAggregator.operationComplete(PromiseAggregator.java:101)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:568)
    at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:416)
    at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87)
    at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:197)
    at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:143)
```

Ignoring for now the issue with the double completed promise (that is likely my error handing needing a bit of tweaking), this seems to happen whenever a stream was reset by the client before the server gets around to writing headers. (It is worth mentioning that my implementation is a proxy of sorts, so while waiting for replies from a backend service, significant time might pass between receiving a request via HTTP2 frames and being able to start writing the HTTP2 response headers frame, hence the client has ample time to reset the stream)

Looking at the code for DefaultHttp2ConnectionEncoder I see:

```
    Http2Stream stream = connection.stream(streamId);
        if (stream == null) {
            stream = connection.local().createStream(streamId, endOfStream);
        } else {
            ....
```

So in any case where the stream does not exist, we try to create a new one. Seems to me that there should be a check for wether the stream id was previously valid, naively something like:

```
        if (stream == null) {
            if (connection.streamMayHaveExisted(streamId)) {
                throw new IllegalArgumentException(String.format("Stream %d no longer exists", streamId));
            }
            stream = connection.local().createStream(streamId, endOfStream);
        } else {
            ....
```

Does this make any sense or am I misunderstanding something?

I can try to implement a fix and a test if it is indeed an issue and not just me missing something.

**Comment by Scottmitch** [comment]
@nhnFreespirit - Thanks for reporting. When the client resets the stream, are you getting the reset stream read event (`Http2FrameListener.onRstStreamRead`)? If so what do you do when being notified that the stream is reset?  The error may be a bit misleading given the scenario you described but it seems strange to be writing to a stream after it has been closed.

**Comment by Scottmitch** [comment]
@nhnFreespirit - Also can you try your scenario with `4.1.0.CR3-SHAPSHOT`? There was an issue (56e6e07) related to sending RST_FRAMES in CR2 which was fixed.

**Comment by nhnFreespirit** [comment]
I have an overridden Http2EventAdapter. Then only custom processing I do in onRstStreamRead is to tear down whatever constructs I had in place for managing the Http1 request writer for that stream. I don't do anything else that relates to the Http2 pipeline in there.

I'm happy to try CR3.

**Comment by Scottmitch** [comment]
@nhnFreespirit - You mention you are implementing a proxy. Does the peer you are proxying understand HTTP/2, and are you forwarding on the reset? Also you may want to account for race conditions when your peer sends a frame which you normally would send to the request initiator because it hasn't yet received the reset frame you have already sent.

**Comment by nhnFreespirit** [comment]
yes, the peer being proxied (it is a bit of a simplification, but as much as I can reveal here) and my service communicate exclusively via HTTP2.

I'm really just swapping out one Netty based http2 codec (https://github.com/twitter/netty-http2) for another, and although they are implemented very differently, they rely on the same underlying Netty constructs.

**Comment by Scottmitch** [comment]
> they rely on the same underlying Netty constructs.

I'm not intimately familiar with Twitter's http2 codec but it has more consideration for multi-threaded environments (e.g. [HttpConnection uses a ConcurrentLinkedQueue](https://github.com/twitter/netty-http2/blob/master/src/main/java/com/twitter/http2/HttpConnection.java#L292)). Netty's http2 codec currently assumed all operations on on the same thread (the I/O thread).

**Comment by normanmaurer** [comment]
Let me close this for now... @nhnFreespirit if you still see issues please re-open
