### ISSUE TITLE
4.1.0.CR2: Missing shutdownOutput() method for EpollDomainSocketChannel

### ISSUE THREAD

**Issue by marcuslinke** [netty/netty#4881]
I wonder why there is no such public method? Is there any reason for that? I'm looking for an equivalent for `((NioSocketChannel)channel).shutdownOutput();`

See: https://github.com/docker-java/docker-java/issues/471

**Comment by normanmaurer** [comment]
@marcuslinke because we not implemented it yet ;) I will take care... Thanks for reporting

**Comment by Scottmitch** [comment]
Fixed by #4883
