### ISSUE TITLE
Don't Call handlerRemoved and channelUnregistered When "java.net.ConnectException"

### ISSUE THREAD

**Issue by yankuncheng** [netty/netty#4889]
When failure(java.net.ConnectException: Connection refused,don't call "handlerRemoved","channelUnregistered"
The Console only output(Without handlerRemoved and channelUnregistered):
"handlerAdded
channelRegistered
DefaultChannelPromise@f4721c7(failure(java.net.ConnectException: Connection refused: www.163.com/106.120.180.42:81)"

The Source Code:

import java.net.InetSocketAddress;

import io.netty.bootstrap.Bootstrap;
import io.netty.channel.ChannelFuture;
import io.netty.channel.ChannelFutureListener;
import io.netty.channel.ChannelHandlerAdapter;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.ChannelOption;
import io.netty.channel.ChannelPipeline;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioSocketChannel;

class LogHandler extends ChannelHandlerAdapter {

	@Override
	public void channelActive(ChannelHandlerContext ctx) throws Exception {
		System.out.println("channelActive");
	}

	@Override
	public void handlerAdded(ChannelHandlerContext ctx) throws Exception {
		System.out.println("handlerAdded");
	}

	@Override
	public void channelRegistered(ChannelHandlerContext ctx) throws Exception {
		System.out.println("channelRegistered");
	}

	@Override
	public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
		ctx.close();
		System.out.println("exceptionCaught:");
	}

	@Override
	public void handlerRemoved(ChannelHandlerContext ctx) throws Exception {
		System.out.println("handlerRemoved:" + ctx);
	}

	@Override
	public void channelUnregistered(ChannelHandlerContext ctx) throws Exception {
		System.out.println("channelUnregistered:" + ctx);
	}

	@Override
	public void channelInactive(ChannelHandlerContext ctx) throws Exception {
		System.out.println("channelInactive");
	}

	public static void main(String[] args) throws InterruptedException {
		Bootstrap bootstrap = new Bootstrap();
		EventLoopGroup group = new NioEventLoopGroup();
		bootstrap.group(group).channel(NioSocketChannel.class).handler(new ChannelInitializer<SocketChannel>() {
			@Override
			public void initChannel(SocketChannel ch) throws Exception {
				ChannelPipeline p = ch.pipeline();
				p.addLast(new LogHandler());
			}
		});
		bootstrap.connect(new InetSocketAddress("www.163.com", 81)).addListener(new ChannelFutureListener() {

			@Override
			public void operationComplete(ChannelFuture future) throws Exception {

				System.out.println(future);
			}

		});
		Thread.sleep(Long.MAX_VALUE);
	}
}

**Comment by normanmaurer** [comment]
You should update to latest 4.1 or 4.0 release. Works as expected there:

```
/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/bin/java -Didea.launcher.port=7532 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 15 CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/lib/javafx-doclet.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/lib/tools.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/htmlconverter.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Users/norman/Documents/workspace/netty/example/target/classes:/Users/norman/Documents/workspace/netty/transport/target/classes:/Users/norman/Documents/workspace/netty/buffer/target/classes:/Users/norman/Documents/workspace/netty/common/target/classes:/Users/norman/Documents/workspace/netty/resolver/target/classes:/Users/norman/Documents/workspace/netty/transport-sctp/target/classes:/Users/norman/Documents/workspace/netty/codec/target/classes:/Users/norman/Documents/workspace/netty/handler/target/classes:/Users/norman/Documents/workspace/netty/handler-proxy/target/classes:/Users/norman/Documents/workspace/netty/codec-http/target/classes:/Users/norman/Documents/workspace/netty/codec-http2/target/classes:/Users/norman/Documents/workspace/netty/codec-memcache/target/classes:/Users/norman/Documents/workspace/netty/codec-socks/target/classes:/Users/norman/Documents/workspace/netty/codec-stomp/target/classes:/Users/norman/.m2/repository/com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.jar:/Users/norman/.m2/repository/io/netty/netty-tcnative/1.1.33.Fork14/netty-tcnative-1.1.33.Fork14-osx-x86_64.jar:/Users/norman/.m2/repository/com/jcraft/jzlib/1.1.3/jzlib-1.1.3.jar:/Users/norman/.m2/repository/org/javassist/javassist/3.19.0-GA/javassist-3.19.0-GA.jar:/Users/norman/.m2/repository/com/yammer/metrics/metrics-core/2.2.0/metrics-core-2.2.0.jar:/Users/norman/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar:/Users/norman/Documents/workspace/netty/transport-udt/target/classes:/Users/norman/.m2/repository/com/barchart/udt/barchart-udt-bundle/2.3.0/barchart-udt-bundle-2.3.0.jar:/Users/norman/Documents/workspace/netty/transport-rxtx/target/classes:/Users/norman/.m2/repository/org/rxtx/rxtx/2.1.7/rxtx-2.1.7.jar:/Users/norman/.m2/repository/ch/qos/logback/logback-classic/1.0.13/logback-classic-1.0.13.jar:/Users/norman/.m2/repository/ch/qos/logback/logback-core/1.0.13/logback-core-1.0.13.jar:/Applications/IntelliJ IDEA 15 CE.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain io.netty.example.echo.LogHandler
handlerAdded
channelRegistered
DefaultChannelPromise@5ac0017a(failure: java.net.ConnectException: Connection refused: www.163.com/203.130.61.92:81)
channelUnregistered:ChannelHandlerContext(LogHandler#0, [id: 0x740bdaba])
handlerRemoved:ChannelHandlerContext(LogHandler#0, [id: 0x740bdaba])
```
