### ISSUE TITLE
Custom ChannelHandlerInvoker doesn't get invoked

### ISSUE THREAD

**Issue by maseev** [netty/netty#4890]
According to [this](https://github.com/netty/netty/issues/2398#issuecomment-40589341) comment, starting from Netty 4.1 I can specify my custom ChannelHandlerInvoker in order to emulate legacy thread model. I created a simple [echo server](https://github.com/maseev/cci) in order to demonstrate that the custom ChannelHandlerInvoker isn't used in case the channel pipeline has only one outbound ChannelHandler.

It turns out that my custom ChannelHandlerInvoker isn't used for, let's call them technical channel handler's. There're at least two of them - HeadContext (which is an outbound channel handler) and TailContext (which is an inbound channel handler). 

When I call [ctx.writeAndFlush](https://github.com/netty/netty/blob/c6a3729e4c7c1ebcc9400d4a1285924c4bc55aa4/transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java#L264), Netty is trying to find an outbound channel handler context, grabs a channel handler invoker and call the according methods.

The problem is Netty doesn't check the current channel handler context, but [moves](https://github.com/netty/netty/blob/c6a3729e4c7c1ebcc9400d4a1285924c4bc55aa4/transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java#L307) backwards until it finds an outbound one.

As I said previously, 'technical'  channel handlers don't get a custom channel handler invoker that I specify in the channel pipeline. As a result, HeadContext uses DefaulChannelHandlerInvoker instead my custom one.

To reproduce the problem, please do the following:

- grab the [source code](https://github.com/maseev/cci)
- build the project with `maven clean assembly:assembly`
- run it with `java -jar ./target/delivery/cci.jar -c` or `java -jar ./target/delivery/cci.jar -d`
- connect to the server via telnet: `telnet localhost 8080` and send a random message

If you run an application with a `-d` flag, you won't see any log messages on the server side if you send a message via telnet. On the other hand, if you run the application with a `-c` flag, you'll see two log messages on the server side per message that you send via telnet. If you specify the -c flag, the application will be using the redundant OutboundChannelHandlerAdapter in the pipeline which makes the CustomChannelHandlerInvoker work.

**Comment by normanmaurer** [comment]
@maseev I think what you explained make sense. If you want to have the invoker be used then you should call `ctx.channel().writeAndFlush(...)`. This will dispatch the write via the TailContext and so ensure the invoker is used.
