### ISSUE TITLE
Netty 4.0.33.Final: java.io.IOException: An established connection was aborted by the software in your host machine

### ISSUE THREAD

**Issue by JuKu** [netty/netty#4897]
I get the following exception on netty server:
`java.io.IOException: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:357)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:898)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)`

What does this exception mean?
English version of exception, searched by google:
`java.io.IOException: An established connection was aborted by the software in your host machine`

I use Netty 4.0.33.

**Comment by JuKu** [comment]
On Client side i get the following error message:
`
1013 [nioEventLoopGroup-2-1] DEBUG io.netty.channel.DefaultChannelPipeline  - Discarded inbound message ProxyClientMessage(SlicedAbstractByteBuf(ridx: 0, widx: 22, cap: 22/22, unwrapped: UnpooledUnsafeDirectByteBuf(ridx: 37, widx: 37, cap: 1024))) that reached at the tail of the pipeline. Please check your pipeline configuration.
`

Encoder and Decoders on client and server side are the same.
Server can send data to client, but if client send data to server, the exception is thrown.

**Comment by Scottmitch** [comment]
@JuKu - Thanks for reaching out. Can you provide a reproducer?

**Comment by normanmaurer** [comment]
Please reopen if you still see an issue and once you have more details / reproducer

**Comment by JuKu** [comment]
I could fix the problem now and currently, i couldnt reproduce the bug.

 

 

 

-----Original-Nachricht-----

Betreff: Re: [netty] Netty 4.0.33.Final: java.io.IOException: An 
established connection was aborted by the software in your host machine 
(#4897)

Datum: 2016-03-16T05:09:58+0100

Von: "Norman Maurer" <notifications@github.com>

An: "netty/netty" <netty@noreply.github.com>

 

 

 

Closed #4897 <https://github.com/netty/netty/issues/4897> .

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/netty/netty/issues/4897#event-590471085
<https://github.com/netty/netty/issues/4897#event-590471085>

 


<div style=\"border:0;border-bottom:1px solid black;width:100%;\"> Telekom 
Mail: Ihre Daten bleiben in Deutschland.
Jetzt persönliche E-Mail-Adresse sichern!
www.t-online.de/email-kostenlos

**Comment by normanmaurer** [comment]
How you fixed it?

**Comment by JuKu** [comment]
I have rewrite the networking code.

So i currently dont know, how i can reproduce the bug.

 

 

 

-----Original-Nachricht-----

Betreff: Re: [netty] Netty 4.0.33.Final: java.io.IOException: An 
established connection was aborted by the software in your host machine 
(#4897)

Datum: 2016-03-17T08:29:53+0100

Von: "Norman Maurer" <notifications@github.com>

An: "netty/netty" <netty@noreply.github.com>

 

 

 

How you fixed it?

> Am 16.03.2016 um 22:55 schrieb JuKu <notifications@github.com>:
>
> I could fix the problem now and currently, i couldnt reproduce the bug.
>
>
>
>
>
>
>
> -----Original-Nachricht-----
>
> Betreff: Re: [netty] Netty 4.0.33.Final: java.io.IOException: An
> established connection was aborted by the software in your host machine
> (#4897)
>
> Datum: 2016-03-16T05:09:58+0100
>
> Von: "Norman Maurer" <notifications@github.com>
>
> An: "netty/netty" <netty@noreply.github.com>
>
>
>
>
>
>
>
> Closed #4897 <https://github.com/netty/netty/issues/4897> .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/netty/netty/issues/4897#event-590471085
> <https://github.com/netty/netty/issues/4897#event-590471085>
>
>
>
>
> <div style=\"border:0;border-bottom:1px solid black;width:100%;\"> 
Telekom
> Mail: Ihre Daten bleiben in Deutschland.
> Jetzt persönliche E-Mail-Adresse sichern!
> www.t-online.de/email-kostenlos
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
>

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/netty/netty/issues/4897#issuecomment-197739007>

 


<div style=\"border:0;border-bottom:1px solid black;width:100%;\"> Telekom 
Mail: Ihre Daten bleiben in Deutschland.
Jetzt persönliche E-Mail-Adresse sichern!
www.t-online.de/email-kostenlos

**Comment by normanmaurer** [comment]
Let me close this for now then... Please reopen once you know more and still think it is a netty bug.

**Comment by JuKu** [comment]
@normanmaurer @Scottmitch Today i have get this error with Netty 4.0.34 again.

I have searched an little bit on Google about this problem and i think, the problem is very well known on netty and other netty based libraries:
  - https://samebug.io/exceptions/149460/java.io.IOException/eine-bestehende-verbindung-wurde-softwaregesteuert
  - https://samebug.io/exceptions/340613/java.io.IOException/eine-bestehende-verbindung-wurde-softwaregesteuert?soft=false
  - https://groups.google.com/forum/#!topic/play-framework/H79RkAjoEfM
  - https://groups.google.com/forum/#!msg/play-framework/H79RkAjoEfM/t1hTxCM5UJAJ

The problem is:
I dont know the really cause and to write an reproducer is very difficult, because this isnt an little project and the isnt shown every time.

**Comment by Scottmitch** [comment]
@JuKu - Sorry this issue came back, but we are still going to need more information. In general the `Discarded inbound message <msg> that reached at the tail of the pipeline. Please check your pipeline configuration.` means a `channelRead()` event reached the end of the [pipeline](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/DefaultChannelPipeline.java#L1356) and was therefor not handled by your application.  What codec are you using, and who in the pipeline is responsible for handling messages of type `ProxyClientMessage`?

**Comment by JuKu** [comment]
@Scottmitch I think this error message isnt the same for this problems, it seems to be that this was 2 different problems.

The current error message:
```
27083 [nioEventLoopGroup-12-1] WARN root  - An exception was caught in login handler: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
java.io.IOException: Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:357)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:898)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

Because i am from Germany, the first message is in german.
In english:
```
java.io.IOException: An established connection was aborted by the software in your host machine
```

I think the exception is thrown while reading from socket - but why?

@Scottmitch We are using an binary protocol.
ProxyClientMessage:
```
import com.pentaquin.proxy.lib.message.utils.ByteUtils;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.DefaultByteBufHolder;
import io.netty.buffer.Unpooled;

import java.nio.charset.StandardCharsets;

/**
 * Created by Justin on 30.09.2015.
 *
 * License: The following code belongs to the pentaquin.com project and isnt open source.
 * Copyright (c) 2016 Pentaquin.com, All Rights Reserved.
 */
public class ProxyClientMessage extends DefaultByteBufHolder {

    /** the message header length */
    public static final int HEADER_LENGHT = 11;

    /** the message type */
    protected final byte type;

    /** the message version */
    protected final byte version;

    /* 0x01 - normal message to client, 0x02 - broadcast message, 0x03 - server is shuting down, 0x04 - server is shuting down for updates  */
    protected final byte proxyMessageType;

    /* proxy server has to known characterID, because every user can have many characters on different sectors */
    protected final Long characterID;

    /**
     * Constructor which creates a new message and
     * sets the type, version and content.
     *
     * @param proxyMessageType
     *            the proxy message type
     * @param type
     *            the message type
     * @param version
     *            the message version
     * @param content
     *            the message content
     *
     * @link https://dev.pentaquin.com/w/wiki/bereiche/programmierung/client_proxy_protocol/
     */
    public ProxyClientMessage(byte proxyMessageType, Long characterID, byte type, byte version, ByteBuf content) {
        super(content);
        this.proxyMessageType = proxyMessageType;
        this.characterID = characterID;
        this.type = type;
        this.version = version;
    }

    /**
     * Constructor which creates a new message and
     * sets the type, version and content.
     *
     * @param proxyMessageType
     *            the proxy message type
     * @param type
     *            the message type
     * @param version
     *            the message version
     * @param content
     *            the message content
     *
     * @link https://dev.pentaquin.com/w/wiki/bereiche/programmierung/client_proxy_protocol/
     */
    public ProxyClientMessage(byte proxyMessageType, byte type, byte version, ByteBuf content) {
        super(content);
        this.proxyMessageType = proxyMessageType;
        this.characterID = 0l;
        this.type = type;
        this.version = version;
    }

    /**
     * Constructor which creates a new proxy message and
     * sets the proxyMessageType and content.
     *
     * @param proxyMessageType
     *            the proxy message type
     * @param content
     *            the message content
     */
    public ProxyClientMessage(byte proxyMessageType, ByteBuf content) {
        super(content);
        this.proxyMessageType = proxyMessageType;
        this.characterID = 0l;
        this.type = 0x00;
        this.version = 0x01;
    }

    /**
     * Constructor which creates a new proxy message and
     * sets the proxyMessageType and content.
     *
     * @param proxyMessageType
     *            the proxy message type
     * @param content
     *            the message content
     */
    @Deprecated
    public ProxyClientMessage(byte proxyMessageType, String content) {
        super(Unpooled.buffer().writeBytes(ByteUtils.getBytesFromString(content, StandardCharsets.UTF_8)));
        this.proxyMessageType = proxyMessageType;
        this.characterID = 0l;
        this.type = 0x00;
        this.version = 0x01;
    }

    /**
     * Gets the type of this message.
     *
     * @return the type of this message
     */
    public byte getType()
    {
        return type;
    }

    /**
     * Gets the version of this message.
     *
     * @return the version of this message
     */
    public byte getVersion() {
        return version;
    }

    /**
     * Gets the proxy message type of the message
     * for example 0x01 if the player authentificates or 0x02 if the p@cschaal94layer changes sector or if the server sneds an message to sector server
     *
     * @return the proxy message type of the message
     */
    public byte getProxyMessageType () {
        return this.proxyMessageType;
    }

    public Long getCharacterID () {
        return this.characterID;
    }

}
```

ProxyMessageEncoder:
```
import io.netty.buffer.ByteBuf;
import io.netty.channel.ChannelHandlerContext;
import io.netty.handler.codec.MessageToByteEncoder;

/**
 * Created by Justin on 03.10.2015.
 */
public class ProxyMessageEncoder extends MessageToByteEncoder<ProxyClientMessage> {

    @Override
    protected void encode(ChannelHandlerContext channelHandlerContext, ProxyClientMessage msg, ByteBuf out) throws Exception {
        out.writeInt(ProxyClientMessage.HEADER_LENGHT + msg.content().readableBytes());
        out.writeByte(msg.getProxyMessageType());
        out.writeLong(msg.getCharacterID());
        out.writeByte(msg.getType());
        out.writeByte(msg.getVersion());
        out.writeBytes(msg.content());
    }

}
```

ProxyMessageDecoder:
```
import io.netty.buffer.ByteBuf;
import io.netty.channel.ChannelHandlerContext;
import io.netty.handler.codec.ByteToMessageDecoder;

import java.util.List;

/**
 * Created by Justin on 03.10.2015.
 */
public class ProxyMessageDecoder extends ByteToMessageDecoder {

    @Override
    protected void decode(ChannelHandlerContext channelHandlerContext, ByteBuf in, List<Object> out) throws Exception {
        if (in.readableBytes() < 4) return;
        in.markReaderIndex();

        int length = in.readInt();
        if (in.readableBytes() < length)
        {
            in.resetReaderIndex();
            return;
        }

        byte proxyMessageType = in.readByte();
        Long characterID = in.readLong();
        byte type = in.readByte();
        byte version = in.readByte();
        ByteBuf content = in.slice(in.readerIndex(), length - ProxyClientMessage.HEADER_LENGHT);
        in.skipBytes(length - ProxyClientMessage.HEADER_LENGHT);

        // increment refcount since content is a slice of in and ByteToMessageDecoder will release in
        content.retain();

        ProxyClientMessage message = new ProxyClientMessage(proxyMessageType, characterID, type, version, content);
        out.add(message);
    }

}
```

Pipeline on server side (where the error oncurred):
```
       //add specific message encoder and decoder for client <--> proxy server connection
        pipeline.addLast("encoder", new ProxyMessageEncoder());
        pipeline.addLast("decoder", new ProxyMessageDecoder());

        //create new instance of login handler
        LoginHandler loginHandler = new LoginHandler();

        //Some code of login handler configuration here

        //add login handler to pipeline
        pipeline.addLast("loginHandler", loginHandler);
```

LoginHandler channelRead() method:
```
@Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
        this.logger.debug("LoginHandler channel " + ctx.name() + " read.");

        //cast to proxy client message
        ProxyClientMessage message = (ProxyClientMessage) msg;

        if (message.getProxyMessageType() == (byte) 0x01) {
            Logger.getRootLogger().debug("authorization message received.");

            //Some login code here

            if (sessionServerClient.isSession(sessionID, authKey)) {
                Logger.getRootLogger().debug("session " + sessionID + " with authKey " + authKey + " is valide.");

                if (session == null) {
                    Logger.getRootLogger().warn("Couldnt get session " + sessionID + " with authKey " + authKey + " from session server.");

                    //send authorization reponse message
                    LoginMessageResponse messageResponse = new LoginMessageResponse(sessionID, authKey, uuid, false);
                    ChannelFuture channelFuture = ctx.writeAndFlush(messageResponse.getMessage());

                    channelFuture.addListener(new ChannelFutureListener() {
                        @Override
                        public void operationComplete(ChannelFuture channelFuture) throws Exception {
                            if (channelFuture.isDone()) {
                                Logger.getRootLogger().info("Close connection. Cause: login failed.");

                                //close connection
                                ctx.close();
                            }
                        }
                    });

                    throw new IllegalStateException("session " + sessionID + " is valide, but cannot get session from session server.");
                }

                //send authorization reponse message
                LoginMessageResponse messageResponse = new LoginMessageResponse(sessionID, authKey, uuid, true);
                ctx.writeAndFlush(messageResponse.getMessage());

                //remove login handler and add message handler to pipeline
                this.updateHandlersAfterLogin(ctx, session, userID, username);
            } else {
                Logger.getRootLogger().debug("session " + sessionID + " with authKey " + authKey + " is invalide.");

                //send authorization reponse message
                LoginMessageResponse messageResponse = new LoginMessageResponse(sessionID, authKey, uuid, false);
                ChannelFuture channelFuture = ctx.writeAndFlush(messageResponse.getMessage());

                //execute authorization listeners
                this.callAuthListeners(sessionID, authKey, false);

                channelFuture.addListener(new ChannelFutureListener() {
                    @Override
                    public void operationComplete(ChannelFuture channelFuture) throws Exception {
                        if (channelFuture.isDone()) {
                            Logger.getRootLogger().info("Close connection. Cause: login failed.");

                            //close connection
                            ctx.close();
                        }
                    }
                });
            }
        }

        Logger.getRootLogger().debug("received proxy message type: " + message.getProxyMessageType());
    }
```

LoginHandler updateHandlersAfterLogin() method:
```
private void updateHandlersAfterLogin (ChannelHandlerContext ctx, WritableSession session, Long userID, String username) throws Exception {
        //ctx was saved in channelActive() method
        if (this.ctx == null) {
            throw new IllegalStateException("Channel isnt active yet, but loginSuccess() was called.");
        }

        Logger.getRootLogger().debug("remove login handler and add proxy message handler.");

        ProxyChannelHandler proxyChannelHandler = new ProxyChannelHandler(this.authorizationManager, this.proxyFirewall, this.playerManager, this.regionConnections, this.proxyServerID);

        //add logic channel handler to pipeline
        ctx.pipeline().addLast("handler", proxyChannelHandler);

        //remove handler from pipeline
        ctx.pipeline().remove("loginHandler");

        //send init message
        proxyChannelHandler.init(ctx, this.tmpMapRepository, session, userID, username);
    }
```

**Comment by JuKu** [comment]
Also other projects have this bug:
  - https://github.com/jirutka/spring-rest-exception-handler/issues/13 (an Tomcat module)

Because the error message was thrown by socket dispatcher and netty handles these sockets, i think its an netty bug. Maybe netty tries to read from Socket, but it crashes.

EDIT:
I have found an really interesting information about this bug:
http://stackoverflow.com/questions/14304658/c-sharp-an-established-connection-was-aborted-by-the-software-in-your-host-machi/14305484#14305484

If we believe in this message, the exception could only thrown in Windows.

Also interesting:
http://stackoverflow.com/questions/27942070/an-established-connection-was-aborted-by-the-software-in-your-host-machine-whe

Its about an leaking socket connection. Or it could also be an problem with multi threading. I think netty has to handle this exception.

Also very interesting is, that this exception is thrown on every connection now - since i have made a few changes in source, but this changes arent really interesting for this problem.

**Comment by JuKu** [comment]
I could reproduce the exception an little bit:
If i remove overriden channelActive() method, the exception isnt thrown.

EDIT:
```
@Override
    public void channelActive (ChannelHandlerContext ctx) throws Exception {
        this.ctx = ctx;

        //increment number of active connections
        ConnectionCounter.increment();

        //channel active
        logger.debug("channel " + ctx.name() + " active.");

        //the following code throws the exception

        try {
            //send welcome message for monitoring
            ByteBuf content = Unpooled.buffer();
            content.writeBytes(ByteUtils.getBytesFromString("connection successful."));
            ProxyClientMessage message = new ProxyClientMessage((byte) 0x00, content);
            ctx.writeAndFlush(message);
        } catch (Exception e) {
            Logger.getRootLogger().warn("exception caught in proxy login handler channelActive: " + e.getLocalizedMessage(), e);
        }
    }
```

But why? And if they are some problems in encoder / decoder, why netty doesnt throws an special exception?

**Comment by JuKu** [comment]
I could resolve the problem with using the eventloop, and sending this message after 50ms:
```
//send welcome message with delay of 50ms
ctx.channel().eventLoop().schedule(() -> {
    Logger.getRootLogger().debug("send welcome message to client.");

    //send welcome message
    ctx.writeAndFlush(message);
}, 50l, TimeUnit.MILLISECONDS);
```

Code of channelActive() method:
```
@Override
    public void channelActive (ChannelHandlerContext ctx) throws Exception {
        //channel active
        logger.debug("channel " + ctx.name() + " active.");

        try {
            //send welcome message for monitoring
            ByteBuf content = Unpooled.buffer();
            content.writeBytes(ByteUtils.getBytesFromString("connection successful."));
            ProxyClientMessage message = new ProxyClientMessage((byte) 0x00, content);

            //send welcome message with delay of 50ms
            ctx.channel().eventLoop().schedule(() -> {
                Logger.getRootLogger().debug("send welcome message to client.");

                //send welcome message
                ctx.writeAndFlush(message);
            }, 50l, TimeUnit.MILLISECONDS);
        } catch (Exception e) {
            Logger.getRootLogger().warn("exception caught in proxy login handler channelActive: " + e.getLocalizedMessage(), e);
        }
    }
```

But its an netty bug, i think. Before this fix the method tried to write into channel, but channel wasnt initialized yet, i think. Netty doesnt have any queue for this event, so netty tries to write into channel and the exception is thrown.

**Comment by aman28061994** [comment]
Hello @normanmaurer @Scottmitch
I am facing the same issue.
in my case the clients disconnects on every request and suddenly after 15 mins.
i receive this error java.io.IOException: An established connection was aborted by the software in your host machine
