### ISSUE TITLE
io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder unwraped UnsupportedCharsetException 

### ISSUE THREAD

**Issue by vietj** [netty/netty#4898]
- Netty 4.1.0.CR3
- Decode a POST multipart request
- Reproduce : submit a form with a content type having an invalid charset (see below)

```
    String body = "--a4e41223-a527-49b6-ac1c-315d76be757e\r\n" +
        "Content-Disposition: form-data; name=\"file\"; filename=\"tmp-0.txt\"\r\n" +
        "Content-Type: image/gif; charset=ABCD\r\n" +
        "Content-Length: 12\r\n" +
        "\r\n" +
        "some-content\r\n" +
        "--a4e41223-a527-49b6-ac1c-315d76be757e--\r\n";
```

line 858 of `HttpPostMultipartRequestDecoder` catch `IOException` but it will throw `UnsupportedCharsetException ` that is unchecked.

**Comment by trustin** [comment]
Hey @vietj, how's it going? :-)
It obviously looks like a bug. Care to submit a quick PR?

**Comment by vietj** [comment]
no problem, will do

**Comment by trustin** [comment]
@vietj Thanks!

**Comment by W12S12E12** [comment]
https://github.com/zcourts/higgs

**Comment by vietj** [comment]
see https://github.com/netty/netty/pull/4956

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4956
