### ISSUE TITLE
Remove 5.x references from documentation

### ISSUE THREAD

**Issue by koyadume** [netty/netty#4903]
On netty.io I can see that there is a user guide for version 5.x but I don't see any branch for this version in this git repository. Which branch contains code for 5.x version?

**Comment by bk1te** [comment]
https://github.com/netty/netty/issues/4893

**Comment by Scottmitch** [comment]
Thanks @bk1te.

We should clean up the docs and remove references to 5.x

**Comment by normanmaurer** [comment]
@trustin should I take care to update the site ?

**Comment by trustin** [comment]
@normanmaurer Yes, please. Good time to test whether the fix I pushed works for you.

**Comment by hepin1989** [comment]
How about the milestone of `5.0.0` ?

**Comment by trustin** [comment]
@hepin1989 Removed 5.0.0.Final, closed 5.0.0.Alpha3, removed milestone from unresolved 5.0 issues.

**Comment by tiecai** [comment]
@trustin  When the next version of 5.0.0 will be released? Thanks.

**Comment by normanmaurer** [comment]
@tiecai nothing planed yet as we not even working on 5.0 atm. Please use 4.0 or 4.1

**Comment by tiecai** [comment]
@normanmaurer  Understand. Thank you!

**Comment by normanmaurer** [comment]
was done
