### ISSUE TITLE
missing channelRegistered(...) invocation on first channel handler when added via pipeline.addFirst(...)

### ISSUE THREAD

**Issue by tbcs** [netty/netty#4906]
Inserting channel handlers into an empty pipeline yields different results depending on the method used for insertion.  When `pipeline.addLast(handlers...)` is used all handlers receive the channel registered event.  However, when `pipeline.addFirst(handlers...)` is used, then `channelRegistered(...)` is not invoked on the _first_ handler (subsequent handlers _do_ receive the event).

The following test case demonstrates the issue.

```
import io.netty.channel.ChannelDuplexHandler;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.embedded.EmbeddedChannel;
import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class ChannelPipelineTest {

	class DummyHandler extends ChannelDuplexHandler {
		public volatile boolean fired;

		@Override
		public void channelRegistered(ChannelHandlerContext ctx) {
			fired = true;
			ctx.fireChannelRegistered(); // forward event to next handler
		}

	}

	@Test
	public void channelRegisteredShouldFireOnAddFirstHandler() {
		DummyHandler
				handler1 = new DummyHandler(),
				handler2 = new DummyHandler(),
				handler3 = new DummyHandler();

		new EmbeddedChannel()
				.pipeline()
				.addFirst(handler1, handler2, handler3)
				.firstContext()
				.fireChannelRegistered();

		assertTrue(handler3.fired); // PASS
		assertTrue(handler2.fired); // PASS
		assertTrue(handler1.fired); // FAIL
	}

	@Test
	public void channelRegisteredShouldFireOnAddLastHandler() {
		DummyHandler
				handler1 = new DummyHandler(),
				handler2 = new DummyHandler(),
				handler3 = new DummyHandler();

		new EmbeddedChannel()
				.pipeline()
				.addLast(handler1, handler2, handler3)
				.firstContext()
				.fireChannelRegistered();

		assertTrue(handler1.fired); // PASS
		assertTrue(handler2.fired); // PASS
		assertTrue(handler3.fired); // PASS
	}

}
```

Tested with Netty v4.0.34.Final and git HEAD.

% java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
% uname -a
Linux marvin 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux

**Comment by tbcs** [comment]
I added the test case to [this branch](https://github.com/tbcs/netty/tree/issue_4906) for convenient assessment.

**Comment by Scottmitch** [comment]
thanks for reporting @tbcs - What version of netty are you using?

**Comment by Scottmitch** [comment]
@tbcs - I think there may be an issue, but not where you expect. The `// FAIL` behavior you indicate is actually expected behavior. What you are doing is saying starting from the `firstContext()`'s perspective fire an event. This will basically pass the event to the next context in the pipeline. If you want to ensure all handlers in the pipeline get the event use `pipeline().fireChannelRegistered()`. I think the issue is that the all the handlers in `channelRegisteredShouldFireOnAddLastHandler` see the event, which is an issue in `EmbeddedChannel`.

**Comment by Scottmitch** [comment]
@tbcs - Do I have permission to use / modify your unit test in a PR?

**Comment by tbcs** [comment]
@Scottmitch - Thanks for looking into this.  The issue could be on my side, maybe I just misunderstood the API.

> I think the issue is that the all the handlers in `channelRegisteredShouldFireOnAddLastHandler` see the event, which is an issue in `EmbeddedChannel`.

Originally I encountered the problem in a project building on [RxNetty](https://github.com/ReactiveX/RxNetty), using epoll channels.  In the tests I made an attempt to isolate the issue, that's why I used `EmbeddedChannel`.  The source of my troubles could be the way `channelRegistered` gets propagated in RxNetty, so this might be a downstream issue.  I'll investigate further on the RxNetty side.

> Do I have permission to use / modify your unit test in a PR?

Sure!

**Comment by tbcs** [comment]
I understand that there seems to be an issue with `EmbeddedChannel`'s handling of the pipeline.  However, I intended to report a different, unrelated issue.  I went back to check whether the behavior I experienced is specific to RxNetty and I can confirm that it is not.  After writing another test case I see now that the issue is specific to channel initialization, more specifically the way `ChannelInitializer`'s method `initChannel` is invoked.

@Scottmitch - I assume that you triaged this ticket according to the needs of the `EmbeddedChannel` issue, so I thought it's best to open a separate ticket for the `ChannelInitializer::initChannel` issue (it's filed under #4994).

**Comment by normanmaurer** [comment]
@tbcs thanks a lot!

**Comment by Scottmitch** [comment]
@tbcs - Yip looks like 2 separate issues.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5289
