### ISSUE TITLE
Build warning message due to missing  paxexam version

### ISSUE THREAD

**Issue by cnapagoda** [netty/netty#4909]
Netty version: 4.1.0.CR4-SNAPSHOT

Context:
I have noticed below warning message[1] when building netty project. 

[1].
[WARNING] Some problems were encountered while building the effective model for io.netty:netty-testsuite-osgi:jar:4.1.0.CR4-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.ops4j.pax.exam:maven-paxexam-plugin is missing. @ io.netty:netty-testsuite-osgi:[unknown-version], /home/chandana/Documents/branches/public/git/netty/testsuite-osgi/pom.xml, line 220, column 15
[WARNING] 

Steps to reproduce:
1. Try to build netty project
2. warning message will be logged in the stacktrace.

$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

Operating system: Ubuntu Linux 13.04 64-bit

$ uname -a
Linux chandana-Latitude-E6540 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cnapagoda** [comment]
Sent a PR[1] to fix this.

[1]. https://github.com/netty/netty/pull/4910

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4910
