### ISSUE TITLE
h2childchan: Allow clients to create new streams

### ISSUE THREAD

**Issue by ejona86** [netty/netty#4913]
This is a bit of a mess, sorry. There's a lot of options available, none of which are obviously correct.

There are two basic approaches: use a message or use a method.

## On the parent:

(This is assuming Http2MultiplexCodec has been split in two (#4914): one part that does conversion to Http2Frame objects, let's call it Http2FrameCodec, and one that Multiplexes to child channels)

For the child implementation, it would be nice if `Http2Stream`s could be created without yet assigning them an id, as that would allow creating them without providing Headers. That's related, but will probably become a discussion of its own.

Option 1a: The parent could work by just sending a Headers frame (or some `CreateStream` message). To get a reference to the Http2Stream, message would include a `Promise<Http2Stream>` that is set when allocated, which may be delayed by `MAX_CURRENT_STREAMS`.

Option 1b: Send a Headers frame (or some `CreateStream` message) where there is a later response `StreamCreated` message that includes a "cookie" from the initial message or includes the initial message itself.

Option 2a: A method on `Http2FrameCodec` that returns a `Promise<Http2Stream>`

Option 2b: Same as 2a, but we could possibly expose `Http2FrameCodec` (or an interface) on the `Channel` as an attribute. We could have utility methods that retrieve it from the `Channel`.

It's not clear to me whether 2b provides much benefit over 2. Without it you would need a reference to both the handler and the channel; with it you would only need a reference to the channel.

I think I like Option 1b the most, but I also only recently thought of it, so I've not mulled it over much.

Note that with all of these the application is not choosing a stream id. It should interact with `Http2Stream`s instead of stream ids.

It could be useful to get a reference to `Http2Stream` before it passed through `MAX_CURRENT_STREAMS` in order to queue work more easily. The application could listen to something, like the state moving from idle to open. Only Option 2a/b would receive the most benefit from this since Option 1 has no way to provide an object immediately.

## On the child:

Option 1a: We could have a message to create a new stream. The message could include a `ChannelInitializer`. You would not be able to get a reference to the new `Channel` immediately, however.

Option 1b: Same as 1a, but the message would include the request headers. This doesn't seem to have much benefit over 1a and is a greater deviation from the normal Bootstrap process for clients. I don't think this is a good option.

Option 2a: A method on `Http2MultiplexCodec`. It could directly accept `ChannelInitializer` and such, or it could even return a Bootstrap. In either case it could end up returning a `Channel` or `ChannelFuture` to allow access to the Channel immediately (which would allow things like writing the request immediately instead of in the initializer).

Option 2b: Same as 2a, but with the `Http2MultiplexCodec` (or interface) available as a getter (or maybe attribute) on the `Channel`.

Option 2c: A special Bootstrap that you provide the current channel and it locates Http2MultiplexCodec for you.

It would be nice if the `Channel` is created immediately, but only after passing through MAX_CURRENT_STREAMS would the `Channel` become connected. This is the way that normal Bootstrap works. However, there is an issue that depending on how things are handled on the parent, we may need to send Headers in order to learn whether we've passed through MAX_CONCURRENT_STREAMS.

I think I like option 2a or 2b the most. I think it'd be interesting to consider having the API reasonably easy to work for both HTTP/1 and HTTP/2. For example, if the current channel is HTTP/1 then it could create a new TCP connection to the server. Doing it generically has a lot of difficulties (SSL!) so probably isn't very feasible. But it probably is feasible if the code were application-specific. So I think Bootstrap has some advantages.

**Comment by buchgr** [comment]
looking into this next.

**Comment by buchgr** [comment]
Eric, I am starting to write some code for this. Here are some thoughts to your thoughts. Please let me know what you think.

1) The `Http2FrameCodec` simply fails the promise when exceeding MAX_CONCURRENT_STREAMS. We could use the `StreamBufferingEncoder` to work around this issue. That would interact quite nicely with the current code, as the `Http2FrameCodec` emits a `Http2StreamActiveEvent` for every stream that has been created (local and remote).

2) It seems to me that option 2c is the most natural. I am not sure what the downside is with having to provide headers immediately, as they have to be the first frame anyway.
```java
public class Http2StreamBootstrap extends AbstractBootstrap<Http2StreamBootstrap, AbstractHttp2StreamChannel> {
  // This can be a Http2StreamChannel or a parent channel. 
  public Http2StreamBootstrap(Channel parentChannel) {
  ...
  }
  
  public ChannelFuture connect(Http2Headers headers);

  // OR
  // public ChannelFuture connect(Channel parentChannel, Http2Headers headers);
}
```

The `connect(Http2Headers headers)` method writes a `CreateStream(Promise, EventLoop, ChannelHandler, Http2Headers)` object to the parent channel, which gets intercepted by the `Http2MultiplexCodec`. The multiplex codec then creates a _new child channel and stream id_, and writes the headers frame. That way, the channel is available immediately (assuming the same event loop is used) and one can also write to it immediately (assuming the parent channel is connected). The child channel would only become active, after the `Http2FrameCodec` has written the frame and emitted the `Http2StreamActiveEvent`.

That would work, but managing stream ids in the `Http2MultiplexCodec` is ugly, it therefore makes sense to move the creation of the child channel into the `Http2FrameCodec` and also assign the stream ids there. This comes also with the advantage that we can attach the `Http2StreamChannel` as a property on the `Http2Stream`. So we don't need a `stream id -> channel` mapping. In #5324 we discussed doing so by introducing a `Http2DifferentStream` type and attaching the child channel as a property there. I would argue that we don't need a `Http2DifferentStream`, but expose the child channel instead. The channel is the stream, so to speak.

```java
public interface Http2StreamFrame extends Http2Frame {
  Http2StreamFrame setStreamChannel(Http2StreamChannel ch);

  Http2StreamChannel streamChannel();
}

public interface Http2StreamChannel extends Channel {
  int streamId();
}
```

What do you think?

**Comment by ejona86** [comment]
> I am not sure what the downside is with having to provide headers immediately, as they have to be the first frame anyway.

It makes adapting to HTTP/1 hard. In HTTP/1 you would create a channel, wait for it to go active, and then send the headers. Creating the channel could be done in a helper (application-specific) utility, but waiting for active and sending the headers would be behavior of the Handler, and we would hope to be able to use the same Handler for HTTP/1 and HTTP/2 (with an adapter somewhere) with minimal modification.

> The connect(Http2Headers headers) method writes a CreateStream(Promise, EventLoop, ChannelHandler, Http2Headers) object to the parent channel, which gets intercepted by the Http2FrameCodec. The frame codec then creates a new child channel and stream id, and writes the headers frame. That way, the channel is available immediately (assuming the same event loop is used)

But you need to create ChannelFuture _before_ the write is necessarily complete. How will you make sure it points to the correct channel? It seems we need "thread-safe" (it may not need to change internal state), immediate creation of the Channel instance, but other things could be asynchronous. That would mean that either 1) `Http2StreamChannel` becomes static so it can be created without a reference to `Http2MultiplexCodec` from within Bootstrap or 2) we call a method on `Http2MultiplexCodec` (maybe not the end-user directly) to do the instantiation and then maybe use a normal write to get it registered so that `Http2MultiplexCodec` doesn't need to be thread-safe.

> and one can also write to it immediately (assuming the parent channel is connected)

I'm sure you remember, but there is a distinction between "writing to a channel" and the write getting to the head of the channel (such that it would case I/O). In general we don't need to support the latter, and supporting "writing to a channel" just requires having an instance of Channel, with the handler added, and registered to an event loop. Oh, look! [We have that!](https://github.com/netty/netty/blob/c3abb91/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java#L279) (Because I knew we would need it.)

I had prepared things such that even `Http2Stream` wouldn't be necessary for `Channel` creation. `Http2StreamChannel` [only used `Http2Stream` for notifying of consumed bytes](https://github.com/netty/netty/blob/c3abb91/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java#L531), which would begin using WINDOW_UPDATES. Although you undid that preparation in #5324 (which is why I wasn't wanting you to swap from stream Objects).

>  We need to move the creation of the child channel into the Http2FrameCodec and also assign the stream ids there.

Ewww. The channel creation should happen in MulitplexCodec. Now maybe the channel creation happens in MultiplexCodec which then calls the FrameCodec to get an id.

Also, if FrameCodec creates the Channel, then that means that it must have access to the MultiplexCodec (or the Http2StreamChannel becomes a static class).

> This comes also with the advantage that we can attach the Http2StreamChannel as a property on the Http2Stream.

That's concerning to me. I get really worried when I think about creating an Http2Stream without adding it to the trees that keep track of it. And if we do add it to the trees that keep track of it then now we will need synchronization lots of places, and I expect lots of code will become racy.

**Comment by buchgr** [comment]
> It makes adapting to HTTP/1 hard. In HTTP/1 you would create a channel, wait for it to go active, and then send the headers. Creating the channel could be done in a helper (application-specific) utility, but waiting for active and sending the headers would be behavior of the Handler, and we would hope to be able to use the same Handler for HTTP/1 and HTTP/2 (with an adapter somewhere) with minimal modification.

I understand. That makes sense.

> But you need to create ChannelFuture before the write is necessarily complete.

Yes, brain-fart on my side. Sorry 😅 

> 2) we call a method on Http2MultiplexCodec (maybe not the end-user directly) to do the instantiation and then maybe use a normal write to get it registered so that Http2MultiplexCodec doesn't need to be thread-safe.

I think that is a good option. I should be done in the bootstrap.

> That's concerning to me. I get really worried when I think about creating an Http2Stream without adding it to the trees that keep track of it. And if we do add it to the trees that keep track of it then now we will need synchronization lots of places, and I expect lots of code will become racy.

I am not sure I understand. I was suggesting to go back to attaching the channel as a property on the Http2Stream (which I removed in #5324) and not maintaining a map in `Http2MultiplexCodec`. The `Http2StreamFrames` would then have the channel attached. I think you had it that way originally?

> I had prepared things such that even Http2Stream wouldn't be necessary for Channel creation. Http2StreamChannel only used Http2Stream for notifying of consumed bytes, which would begin using WINDOW_UPDATES (using this as the stream id). Although you undid that preparation in #5324 (which is why I wasn't wanting you to swap from stream Objects).

Yes my change was a bit short sighted. I hadn't thought it all through so well. I guess what I am proposing is to go back to that and have the channel on the `Http2StreamFrame`.

I guess I ll see in code how that all works out. Are you of the opinion that I should pursue the path of having a `Http2StreamBootstrap` or do you see some major disadvantage?

**Comment by ejona86** [comment]
> I am not sure I understand. I was suggesting to go back to attaching the channel as a property on the Http2Stream

I'm fine with the property being there. The problem is, as phrased, it sounded like you would set the property immediately (from whatever thread was doing the creation). That means that you must have Http2Stream immediately. That's what I'm worried about, especially when using `StreamBufferingEncoder`. The code maintaining Http2Streams is not something I think we can easily make multi-threaded. If the creation of the Http2Stream is asynchronous, that sounds fine to me.

> Are you of the opinion that I should pursue the path of having a Http2StreamBootstrap or do you see some major disadvantage?

The bootstrap which you provide the channel sounds good. And since all the option 2s above are about the same difficulty to implement and use most of the same infrastructure, if we want to change it later it should be easy.

**Comment by buchgr** [comment]
> If the creation of the Http2Stream is asynchronous, that sounds fine to me.

oh now I understand. yeah, that was the plan.
