### ISSUE TITLE
h2childchan: Split Http2MultiplexCodec in two

### ISSUE THREAD

**Issue by ejona86** [netty/netty#4914]
Http2MultiplexCodec currently does two things: mapping the existing h2 API to frames and managing the child channels.

It would be better if the two parts were separated. This would allow less-coupled development of the HTTP/2 handlers (flow control could be its own handler, for instance) and allow applications to insert themselves between all streams and the codec, which permits custom logic and could be used, in part, to implement custom frame types.

It would also _greatly_ ease testing, as the child channel could be tested by itself without dealing with how frames are encoded on the wire.

I'd expect that at this layer stream-specific messages would use `Http2Stream` instead of an integer id.

**Comment by ejona86** [comment]
I forgot to mention that there is a cost to this: extra object allocation. Today we are able to use direct method calls for things like flow control; that would be forced to stop. We end up needing to create many more short-lived messages, like sending a WINDOW_UPDATE to the application when data has been written (even though no WINDOW_UPDATE was received; I'll discuss more about flow control later, but an idea of the possible costs is important).

**Comment by ejona86** [comment]
Inbound Flow Control
-----

[Today](https://github.com/netty/netty/blob/e24a5d8/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java#L447), this uses the callbacks of the non-h2childchan API and overriding to plumb the consumption notifications back to the remote flow controller. This means inbound flow control was implemented without any messages being passed. That won't work once `Http2MultiplexCodec` is split in two.

As I mentioned before, I thought we would want to use WINDOW_UPDATE for the messages to communicate when bytes are consumed to the remote flow controller. But the full details are a bit more interesting than that.

The only changes from HTTP/2 are:
 * the window would be advisory, not mandatory. 
 * the stream will not be informed the `INITIAL_WINDOW_SIZE`. Instead, the stream assumes there is some _unknown_ initial window size.

That means that when a stream observes the window to be `0` (such as immediately upon creation), the stream can assume that the sender will be able to send data, but doesn't know how much. Any time the window goes negative, the stream _must_ send a `WINDOW_UPDATE` to bring the window back to `0` if it requires more data. If the stream knows it needs `X` bytes, it may send a `WINDOW_UPDATE` increasing the window to `X`.

I like this design because it seems to do a good job of separating concerns while also being familiar. And the modifications don't seem like they add any real burden. It also seems powerful.

By default child channels auto-manage inbound flow control using the normal Netty mechanism based on reading (so disabling auto-read will push-back; this is implemented today, although under-tested). By default, when a child channel read occurs, it will send a WINDOW_UPDATE of the same length to the parent. However, advanced applications could (as a future feature) disable the auto-management and interact more directly with the flow control.

### Benefits

The flow controller on the parent channel is in a really good situation: it can manage the window like we do today but it also knows how much the stream wants, so if the window from a stream is increased above `0` it can make sure the window is at least that size. Let's say the `INITIAL_WINDOW_SIZE=1MB` and a h2childchan/stream sent a `WINDOW_UPDATE` to the parent channel increasing the window to 1MB. Then the local flow controller could leave things as-is, instead of increasing the remote window to 2MB; it can basically just use the `max(INITIAL_WINDOW_SIZE, additional stream window)`. If `INITIAL_WINDOW_SIZE=64KB`, the increase of the window to 1MB would allow greater throughput on many high-latency BDP links.

It is also good because the flow controller can do all sorts of fancy things for allocating memory, and the stream would not need to be aware. If the `INITIAL_WINDOW_SIZE` changes, the stream doesn't care. If additional window is provided to the remote in order to get better throughput (by making the window at least the BDP), the stream doesn't care. If memory is scarce so the flow controller sets `INITIAL_WINDOW_SIZE=0` and then only provides window to one stream at a time, the stream doesn't care. All the while, the flow controller knows that the stream is expecting `X` amount of additional data and can factor that in.

In gRPC, we would be using this where the `X` bytes of additional data would be the remainder of an RPC payload. Once we start receiving data for an RPC we know we need at least `X` more bytes before we have a complete message which would allow eventually freeing that memory. There are already some designs where we would strictly control the amount of memory used centrally across streams while guaranteeing liveness and optimizing throughput. Even though this design predates our gRPC design, it turned out to be compatible without modification.

**Comment by buchgr** [comment]
@ejona86 start with this, is that what you meant?

**Comment by ejona86** [comment]
@buchgr, yeah, this is the one I'd start with, since it will make testing all the other changes easier. It will also simplify things caused by #5252, since we would no longer need to call the handler itself and could use ctx.write, ctx.flush, and ctx.exceptionCaught directly.

**Comment by buchgr** [comment]
Eric,

I started working on this. Here is a small summary of my understanding. Essentially we want to create two handlers, `Http2FramingCodec` and `Http2StreamChannelCodec` (naming to be discussed). The `Http2FramingCodec` uses the callback-based HTTP/2 API to essentially convert each callback into a `Http2Frame` object (and vice versa when writing). Pipeline setup would be

```
p.addLast(new Http2FramingCodec())
p.addLast(new Http2StreamChannelCodec())
```

In the inbound case, those objects are passed along to the `Http2StreamChannelCodec` via `ctx.channelRead(frame)`. The `Http2StreamChannelCodec` then does the multiplexing of frames to `Http2StreamChannel`s. The `Http2StreamChannelCodec` doesn't know anything about the callback-based HTTP/2 API. The outbound case is just the reverse via `ctx.write(frame)`.

For inbound flow control, essentially the `Http2StreamChannelCodec` acks a read data frame by writing a window update frame, which is then consumed by the `Http2FramingCodec`.

Does that sum up roughly what you had in mind @ejona86 ?

**Comment by ejona86** [comment]
@buchgr, yes, that sums it up. Note that the WINDOW_UPDATE would not be special cased in the `Http2StreamChannelCodec`, but instead be handled within the child channel itself. `Http2StreamChannelCodec` should only have multiplexing logic.

I imagined `Http2StreamChannelCodec` would keep the current name `Http2MultiplexCodec`. `Http2FramingCodec` could eventually be named something like `Http2Codec` (or `Http2ServerCodec`, if there is a client/server split), although if we get rid of the pre-existing HTTP/2 API we may eventually split it the handler into more pieces (e.g., one that does just framing, one that handles flow control).

**Comment by buchgr** [comment]
> Note that the WINDOW_UPDATE would not be special cased in the Http2StreamChannelCodec, but instead be handled within the child channel itself.

Yes that's how I have it.

> I imagined Http2StreamChannelCodec would keep the current name Http2MultiplexCodec.

My current work in progress implementation has a `Http2MultiplexCodec` that bootstraps the pre-existing HTTP/2 API in the constructor and on `handlerAdded` adds `Http2FramingCodec` and `Http2StreamChannelCodec` to the pipeline and then removes itself. That is because the `Http2StreamChannelCodec` needs the `PropertyKey` from the `Http2Connection`.

```java
// constructor
Http2MultiplexCodec(...) {
  Http2Connection connection = new DefaultHttp2Connection(server);
  Http2ConnectionEncoder encoder = ...
  ...

  new Http2FramingCodec(decoder, encoder, settings);
  new Http2StreamChannelCodec(connection.newKey());
}
```

So in order to hide that boostraping from the user, I have the Http2MultiplexCodec. I think it's ugly and will try to get rid of it. Ideally the `Http2StreamChannelCodec` wouldn't have any dependency on the pre-existing HTTP/2 API. Will see ... 

Thanks Eric!

**Comment by buchgr** [comment]
will open a PR tomorrow. the devil is in the detail! 😄

**Comment by Scottmitch** [comment]
sounds great guys ... looking forward to a PR!

**Comment by normanmaurer** [comment]
Same here!

**Comment by buchgr** [comment]
@ejona86 
> I'd expect that at this layer stream-specific messages would use Http2Stream instead of an integer id.

I just noticed one problem with using `Http2Stream` over integers. That is, the lifecycle methods aren't useful and might lead to errors, i.e. calling `stream.closeLocalSide()` in a child channel. It's also not clear to me that any other information but the stream id is useful for someone working with child channels ... priorities, parent stream ... hmm? There might also be threading issues, if the child channel uses a different event loop and changes state of the stream object. Haven't thought deeply about it yet. One advantage of NOT using `Http2Stream` objects is also that the `Http2Frames` and the `Http2MultiplexCodec` would not depend on the callback API  at all. Thoughts?

**Comment by ejona86** [comment]
> That is, the lifecycle methods aren't useful and might lead to errors, i.e. calling stream.closeLocalSide() in a child channel. It's also not clear to me that any other information but the stream id is useful for someone working with child channels ... priorities, parent stream ... hmm?

Yeah, none of that is useful and we'd probably eventually replace it with something that mainly had properties.

> There might also be threading issues, if the child channel uses a different event loop and changes state of the stream object.

The child channel would not interact with the Http2Stream. At that level the streamId is forced to `null` (although we could make it be the child channel instead).

However, it is true there would be threading concerns if various _handlers_ were using different event loops. So that might mean we should use simple integers, or we use `DefaultAttributeMap` or some such.

> One advantage of NOT using Http2Stream objects is also that the Http2Frames and the Http2MultiplexCodec would not depend on the callback API at all.

I would expect to stop exposing Http2Stream eventually, but if we're expecting _some_ object in the end then Http2Stream is convenient today. I'm fine with leaving it as an int in this PR though.
