### ISSUE TITLE
sharp edges in netty-http2

### ISSUE THREAD

**Issue by mosesn** [netty/netty#4916]
The write and read APIs in the netty-http2 module are difficult to reason about or discover, because they're significantly different.  It seems like the main entrypoint for the API is the HttptoHttp2ConnectHandlerBuilder, which takes FrameListener for reading, and uses io.netty.http messages for the write API.

It's unclear how to write Http2 messages with Http2ConnectHandlerBuilder, even though it's public, and concrete, so presumably it's usable.

It seems like stream ids are generated by httptohttp2connectionhandler if they aren't explicitly specified on the http1.1 request, but this renders it unusable without synchronizing on writes or making writes single-threaded, because the stream id isn't exposed to the writer–at the same time, the writer thread must keep track of the stream id so that the frame listener can later match a response frame with a request.

It seems like it would be simpler to reason about the netty-http2 module if the surface area was clearly described, and write / read were symmetric.  As it is today, it's difficult to know what must be done by an implementor, and what the module already does for us.

**Comment by Scottmitch** [comment]
You may want to start with a [Http2ConnectionHandlerBuilder](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandlerBuilder.java), build it to get a [Http2ConnectionHandler](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java), and put it in the pipeline. The read events will be recieved by the [Http2FrameListener](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2FrameListener.java) you provide to the builder, and writes are done via [Http2ConnectionHandler.encoder()](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L114).

Checkout the [http2 helloworld server](https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/http2/helloworld/server) for an example. This class accounts for protocol upgrade of which you may be able to ignore. There is also another API issue related to pipeline initialization https://github.com/netty/netty/issues/4438.

There are a few classes in codec-http2 which exist for HTTP/1.x iterop. If you don't care about http/2 details and instead only care about HTTP/1.x semantics the `*HttptoHttp2*` classes will provide some interop with codec-http.

Longer term @ejona86 has been working on https://github.com/netty/netty/issues/3667. The end goal here is to make the HTTP/2 codec look much more like all the other codes, and be more "nettyish".

**Comment by mosesn** [comment]
Thanks @Scottmitch.  So if I'm writing a client, I should manage streams myself?  With the encoder, am I supposed to use Http2FrameWriter to write?  I was looking at the helloworld example for inspiration, but the client seemed to use the HttpToHttp2ConnectHandler, so I was a little confused.  Is the client example only showing off how to use the `*HttpToHttp2*` classes, or is that the recommended client API?

Thanks for the pointer to #3667–it looks like that will make it much easier to reason about.

It looks like #4503 is close to shipping.  Will that replace the existing API?  Should I hold off on trying to add http2 support until it ships?  More generally, do you expect the http2 api to continue churning significantly in the foreseeable future?

**Comment by Scottmitch** [comment]
> I was looking at the helloworld example for inspiration, but the client seemed to use the HttpToHttp2ConnectHandler

The server demonstrates the "raw http/2" use case and the client demonstrates the "http/1.x conversion layer" user case. You can use either method on either peer (both support client and server).

> It looks like #4503 is close to shipping. 

This PR is a great start but I think we still will have a ways to go until it is ready for prime time.

> Will that replace the existing API?

This is the preferred outcome. After we have all the features, tested to a reasonable extent, and ensured performance is on par then yes.

> More generally, do you expect the http2 api to continue churning significantly in the foreseeable future?

The HTTP/2 codec is "experimental" and will be even after 4.1.0 is released.  However the current "sharp" APIs and underlying implementation are relativity mature and stable.  The biggest churn I foresee is when we completely switch to the new APIs started in #4503

**Comment by mosesn** [comment]
@Scottmitch thanks for all the help!  I think we're going to try to build our new features against #4503 as it comes together.  Really glad to see that we're close to a more idiomatic implementation, thanks!  Is there a slack / gitter / irc where I can hang out to see how I can help?

**Comment by Scottmitch** [comment]
We try to keep our technical discussion in the issues here on github. After #4503 gets pulled in we will work with @ejona86 to see how/if work can be divided up.

**Comment by mosesn** [comment]
:+1: keep me in mind, I'm happy to pitch in.  Thanks again for all your help.

**Comment by trustin** [comment]
@Scottmitch Thanks for answering the questions!
