### ISSUE TITLE
Extend Atomic* instead of using Atomic*FieldUpdater

### ISSUE THREAD

**Issue by slandelle** [netty/netty#4922]
Scala people (cc @viktorklang) had the same concern as you regarding memory footprint of `Atomic*` fields and initially went with an `Atomic*FieldUpdater` for the `scala.concurrent.Future` design.

In Scala 2.12, they came up with a nice idea: extending `Atomic*` (see [code here](https://github.com/scala/scala/blob/2.12.x/src/library/scala/concurrent/impl/Promise.scala#L183) and [story here](https://github.com/viktorklang/blog/blob/master/Futures-in-Scala-2.12-part-8.md)): no indirection level, no extra allocation, `sun.misc.Unsafe` level perf.

It looks to me that most of the Netty classes that use `Atomic*FieldUpdater` could benefit from the same design. The only exceptions are the ones that use more than one FieldUpdater (only one can be stored in the AtomicReference) and ones that extend an abstract class, such as `AbstractReferenceCountedByteBuf`.

WDYT?

**Comment by normanmaurer** [comment]
@slandelle this will only work for things that are not public tho as otherwise it will be exposed to the user.

**Comment by slandelle** [comment]
@normanmaurer You're right, sadly.

**Comment by slandelle** [comment]
`HashedWheelTimer` maybe?

**Comment by slandelle** [comment]
And then wait for JDK 8u76: http://shipilev.net/blog/2015/faster-atomic-fu/#_conclusion_and_parting_thoughts

**Comment by normanmaurer** [comment]
@slandelle even for `HashedWheelTimer` there is not much we can do ....

**Comment by slandelle** [comment]
Nervermind
