### ISSUE TITLE
deregister().sync() strange behaviour

### ISSUE THREAD

**Issue by zergood** [netty/netty#4923]
Hello! 

I am new to netty and have a problem with a channel deregister method. I need to deregister a channel after http parsing complete and register it to another event loop. Channel derigstration/registration takes place in another thread not in the channel's evenloop and this thread is blocked forever by `ctx.deregister.sync()` method.

netty version: 4.0.34

I've made a sample illustrating my problem: https://github.com/zergood/netty-deregister.git.

**Comment by johnou** [comment]
@zergood would you please try and reproduce with the 4.0 branch / 4.0.35 snapshot?

**Comment by zergood** [comment]
It is fixed in 4.0.35 snapshot. @johnou thanks for the quick reply!

**Comment by johnou** [comment]
@normanmaurer :+1:
