### ISSUE TITLE
[Question] Netty 4.0.34 send messages parallel

### ISSUE THREAD

**Issue by JuKu** [netty/netty#4924]
Hi,

If 2 messages will be sended to client, will they be sended parallel, or does netty wait, that first message has received client?

`//send big message with 100MB of data, takes a while
ctx.writeAndFlush(message1);

//send message with 1 KB of data
ctx.writeAndFlush(message2);`

Why message2 isnt received before message1?

**Comment by fredericBregier** [comment]
Please use http://stackoverflow.com/questions/tagged/netty for such questions.

Now on your question: if this is the same channel (client side) used, then the messages are ordered as the program said, so message1 first, message2 second. If not, how could you manage your protocol ?
