### ISSUE TITLE
race between ChannelFuture satisfaction and fireChannelActive in nio/oio

### ISSUE THREAD

**Issue by mosesn** [netty/netty#4927]
When you call Bootstrap#connect or Channel#connect, we get a ChannelFuture back.  However, using that Future to start serving traffic is dangerous, because we satisfy that future before we ChannelPipeline#fireChannelActive in [nio][0] and [nio][1].  If we do initialization in ChannelInboundHandler#channelActive, we might start writing to the channel before initialization has finished.

In other Channel implementations, we sometimes satisfy the future after calling [ChannelPipeline#fireChannelActive][2].  I propose we do that in [nio][0] and [oio][1] too.

[0]: https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/nio/AbstractNioChannel.java#L254-L261
[1]: https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/oio/AbstractOioChannel.java#L66-L69
[2]: https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollDatagramChannel.java#L504-L514

**Comment by normanmaurer** [comment]
@mosesn usually you do your init stuff in `handlerAdded(...)` that said we should make it consistent. Let me look into it

**Comment by mosesn** [comment]
@normanmaurer hmm, this might be our fault then.  I'll look around what we're doing too and see if we can simplify any of this so that the order doesn't matter.

**Comment by mosesn** [comment]
I tried making it consistent where the promise is satisfied after fireChannelActive, and it seems to [pass tests][0]. 

[0]: https://github.com/mosesn/netty/tree/mnakamura/channel-active-race

**Comment by mosesn** [comment]
@normanmaurer could I rewrite finagle's [ChannelHandlerStats][0] to do initialization in handlerAdded?  It seems more natural to be in channelActive.

[0]: https://github.com/twitter/finagle/blob/develop/finagle-netty4/src/main/scala/com/twitter/finagle/netty4/channel/ChannelStatsHandler.scala#L55-L64

**Comment by normanmaurer** [comment]
@trustin I think there was a reason why we always notify the future first before firing the event through the pipeline. Can you remember ?

**Comment by trustin** [comment]
@normanmaurer I think it's just a consistency thing. Always notify future first and then pipeline.

**Comment by normanmaurer** [comment]
@trustin also wasn't it because otherwise the close future could be notified before the connect future if a client directly close ?

**Comment by trustin** [comment]
@normanmaurer Yeah it could be. Also, `ChannelFutureListener`s are always notified from an event loop thread while the handlers in a pipeline can be invoked from non-event-loop-thread, which makes timing pretty nasty.

**Comment by normanmaurer** [comment]
@trustin agree... we should just make it consistent which means always notify the future first. I will check if this is the case.

@mosesn I'm not sure what the problem is with moving the "instancing" of the object into `handlerAdded` and just update stuff in channelActive.

**Comment by mosesn** [comment]
@normanmaurer hmm, can channelActive be called more than once on a single ChannelHandler?  If that's the case, I might want to also do resetting in channelActive, which can mean that we miss writes if we do

```
t1: handlerAdded
t2: write
t1: channelActive
```

whatever statistics we collected because of the write will immediately be discarded because of the reset.

**Comment by mosesn** [comment]
@normanmaurer @trustin can you run into the same problem in reverse, if folks make channelInactive trigger before channelActive?  Or is there a strict preorder on active => inactive?

**Comment by Scottmitch** [comment]
> Also, ChannelFutureListeners are always notified from an event loop thread

@trustin - Unless its a "late listener" :) See https://github.com/netty/netty/issues/4506

**Comment by mosesn** [comment]
So based on my understanding of "correct" behavior, it looks like there's a bug in the example code for the [http2 client][0].  It does the http2 handshake in `channelActive`, which we know isn't safe unless you've agreed not to write yet.  It looks like this is pretty subtle.  Maybe I should document that the ChannelPromise means that the connection is open, but that fireChannelActive might not have been called yet?  It does feel to me like it might be simpler to ensure we notify the pipeline first then fire the promise, and ensure that there's a preorder on open => close.

[0]: https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http2/helloworld/client/Http2ClientInitializer.java#L134-L145

**Comment by mosesn** [comment]
Oh, I see, it doesn't matter because we block on the upgrade in the http client.  I think I'm getting the hang of this.  If we want to do something on connect, and make sure that we don't write until after that has finished, we make that explicit in our code, like in SslHandler?  So basically the onus is on the developer to enforce the order that they need.

**Comment by mosesn** [comment]
So we were talking about whether to put logic into hanging things off of the connect ChannelFuture or putting them in channelActive–it seems like they do basically the same thing.  Is the purpose of the redundancy to provide flexibility for handler implementors?

**Comment by normanmaurer** [comment]
@mosesn yes... Basically it allows to handle everything in a handler.
