### ISSUE TITLE
Adding ability to use more standard JSSE options when using JdkSslContext

### ISSUE THREAD

**Issue by harbulot** [netty/netty#4929]
(Please note the case difference between `SSLContext` and `SslContext` when reading this.)

I was trying to pass various SSL/TLS settings (checking the host name, setting a client certificate and a custom trust store) when using a `JdkSslClientContext` with Netty 4.0.29, when I realised it was actually quite difficult to pass an existing `javax.net.ssl.SSLContext` to the existing classes (`JdkSslContext` and its subclasses). (The code seems fairly similar in the latest 4.0 and 4.1 branches.)

It is currently possible to build a `JdkSslClientContext` using a `TrustManagerFactory` or a list of trusted certificates, a key file or a `KeyManagerFactory`, but there doesn't seem to be anywhere to set all this from an existing `SSLContext` instance (which is one of the main JSSE classes). I realise these can be very useful and convenient, but they make it difficult to use existing `SSLContext` classes (which seems more natural when you're used to the JSSE). (The package protection and `final` modifiers also make it quite tricky to subclass these classes to make such modifications.)

In addition, without any specific settings, it doesn't seem to use the "set" default `SSLContext`. Indeed, it initialises a new `TrustManagerFactory` with `(null, null, null)`, but that's not necessarily the same as `SSLContext.getDefault()` (which can be set with `SSLContext.setDefault(...)` since Java 6). From a JSSE point of view, this seems counter intuitive (since the default values would effectively have different settings from what you would get with `SSLServerSocketFactory.getDefault()`, for example).

Another parameter that would be interesting to pass would be an `SSLParameters` instance. It can provide many settings (otherwise repeated) such as the cipher suites. More importantly, it can provide hostname verification for free since Java 7.

Although Netty 4.x only relies on Java 6, being able to use an `SSLParameters` instance would let code that uses Netty and Java 7 or 8 pass this to enforce hostname verification (for HTTPS):

    SSLParameters sslParameters = new SSLParameters();
    sslParameters.setEndpointIdentificationAlgorithm("HTTPS");

Would you be interested in contributions and pull requests in that area? (That last point might be relevant w.r.t. issue #3534.)

**Comment by slandelle** [comment]
As a workaround, you can specify protocols, cipher suites and algorithm downstream, on each `SSLEngine` you get from `SslContext.newEngine`, before passing them to a `SslHandler`.

**Comment by slandelle** [comment]
> Another parameter that would be interesting to pass would be an SSLParameters instance.

Usually, you don't override the existing parameters, you "edit" them by getting a copy of the current ones, change what you want and set them back. So, instead of passing a value, I suggest passing a function/SAM interface.

**Comment by harbulot** [comment]
@slandelle Regarding the workaround, this is indeed possible, but it would certainly be better to address the problems upstream instead of having to tweak each library that uses Netty (a number of which don't fully expose useful SSL settings unfortunately).



>   > Another parameter that would be interesting to pass would be an SSLParameters instance.
> 
> Usually, you don't override the existing parameters, you "edit" them by getting a copy of the current ones, change what you want and set them back. So, instead of passing a value, I suggest passing a function/SAM interface.

I think there's a use for both. From an `SSLContext`/`SSLParameters` point of view, it would still make sense to be able to set the `SSLParameters` instance, in particular thanks to the fact `SSLContext.getDefaultSSLParameters` returns a *copy* of the default `SSLParameters`.

Hence, you could do something like this:

    SSLContext sslContext = /* ... create and init as required */
    SSLParameters sslParameters = sslContext.getDefaultSSLParameters();
    sslParameters.setProtocols(...);
    sslParameters.setCipherSuites(...);
    sslParameters.setEndpointIdentificationAlgorithm("HTTPS");

    JdkSslClientContext jdkSslContext = new JdkSslClientContext(sslContext, sslParameters);

You are right there is a issue of precedence regarding default settings. In particular, `SSLEngine.setSSLParameters(...)` will not change the instance's protocols and ciphers suites if those values are `null` in the `SSLParameters` instance, but it will change the other values. (See [`SSLEngine`](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/javax/net/ssl/SSLEngine.java#l1237) and [`SSLEngineImpl`](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/sun/security/ssl/SSLEngineImpl.java#l2093) implementations.)

The `JdkSslContext` code would indeed need to choose where it gets its settings from (and where precedence apply). I'd suggest something like:

    sslEngine.setEnabledCipherSuites(...); // and other settings...
    if (sslParameters != null) {
        sslEngine.setSSLParameters(sslParameters);
    }

That way, users using `SSLParameters` would override all the other settings (except protocols and cipher suite if they haven't set them in their `SSLParameters` instance). Users not using `SSLParameters` would use the current behaviour.

That said, it would certainly also make sense to have a function / SAM interface for improved customisation indeed. It seems it would make sense to have both mechanisms.

Maybe something along these lines could work (pseudo-code not to be taken too literally, of course):

    sslEngine.setEnabledCipherSuites(...); // and other settings...
    SSLParameters sslParameters = this.sslParameters; // null if not set
    if (sslParametersCallback != null) {
        sslParameters = sslParametersCallback.call(sslParameters != null ? 
                sslParameters : sslEngine.getSSLParameters);
    }
    if (sslParameters != null) {
        sslEngine.setSSLParameters(sslParameters);
    }

**Comment by slandelle** [comment]
If you have a SAM, you can decide to ignore the existing input and return a fresh instance instead.

**Comment by normanmaurer** [comment]
@harbulot let me work on this

**Comment by normanmaurer** [comment]
You can now create a `JdkSslContext` from a pre-configured `SSLContext`. See https://github.com/netty/netty/pull/5113
