### ISSUE TITLE
Netty 4.1.0.CR1: DNS resolver do not treat non-ASCII characters correctly

### ISSUE THREAD

**Issue by jonas-ren** [netty/netty#4937]
When resolving a domain name containing non-ASCII characters, Netty would send out DNS query but reject the response because the DnsQuestion doesn't match.

For example, when resolving www.äüöß.com, I'm getting:
```
04 Mar 2016 15:33:39,309 [WARN] (dns-response-handler-0) io.netty.resolver.dns.DnsQueryContext: Received a mismatching DNS response: DatagramDnsResponse(from: /x.x.x.x:53, to: /0:0:0:0:0:0:0:0:59756, 1499, QUERY(0), ServFail(2), RD RA)
	DefaultDnsQuestion(www.����.com IN A)
	DefaultDnsRawRecord(OPT flags:0 udp:4000 0B)
```

Looks like it's caused by a difference in encoding. I think the resolver should either validate the input domain name based on http://www.ietf.org/rfc/rfc1738.txt, or just fix the encoding.

**Comment by windie** [comment]
Could you try 4.1.0CR3? I cannot reproduce this error in the latest version.

**Comment by jonas-ren** [comment]
Tried with 4.1.0.CR3 and still got the same thing. I tested with multiple DNS resolvers (local resolver, google DNS and OpenDNS) and all got the same result. 

Perhaps it's platform dependent? I'm running on Mac OS X 10.11.

**Comment by trustin** [comment]
Shouldn't we convert it to IDN?

**Comment by W12S12E12** [comment]
https://github.com/curl/curl/blob/master/CHANGES.0

**Comment by normanmaurer** [comment]
@trustin +1

**Comment by normanmaurer** [comment]
@trustin I wonder what you think where with should use `IDN.toASCII(...)` in the `DefaultDnsRecordDecoder` ? Or just in the `equals(...)` method ?

**Comment by trustin** [comment]
@normanmaurer How about validating and converting the input when creating a `DefaultDnsQuestion` or `AbstractDnsRecord`?

**Comment by normanmaurer** [comment]
@trustin working on a fix.

**Comment by jonas-ren** [comment]
Found another related issue. If the domain name in DNS question has trailing dot, the resolver would also complain "Received a mismatching DNS response", because the question section in received DNS response doesn't have trailing dot.

**Comment by normanmaurer** [comment]
@jonas-ren can you check https://github.com/netty/netty/pull/4979 if it fixes all your problems ?

**Comment by normanmaurer** [comment]
Created a follow-up as https://github.com/netty/netty/issues/4993
