### ISSUE TITLE
h2childchan: Implement outbound flow control

### ISSUE THREAD

**Issue by ejona86** [netty/netty#4941]
The child channel needs to send its writes to the parent channel, where they may be buffered. This sort of behavior is special for our use-case and so `ChannelOutboundBuffer` gets in the way, in multiple ways. We will either need to enhance the API of `ChannelOutboundBuffer` (which is safe in 4.1 since it is a concrete class) or we will need to replace `ChannelOutboundBuffer` with something of our own. Replacing `ChannelOutboundBuffer` may end up forcing ourselves to no longer extend `AbstractChannel`, or to at least losing some tricky functionality that `AbstractChannel` provides.

If we solve enough to make outbound flow control work, we should naturally end up fixing the premature child promise completion in the child's doWrite due to `ChannelOutboundBuffer`.

**Comment by ejona86** [comment]
I investigated using user-defined writability for changing the writability state. It basically would require duplicating the buffer size logic from `ChannelOutboundBuffer` and would ideally consist of overriding `AbstractChannel.filterOutboundMessage` to be informed when new messages before flush(). I think it would be mostly safe from reentrancy concerns.

It seems fairly straight-forward to add a `ChannelPromise steal()` method to `ChannelOutboundBuffer`. It's basically a copy of `remove()` without `safeRelease` on the message and `safeSuccess` on the promise.

If we listen to the write futures, then we could learn when a message is written. That is fairly coarse, but would provide minimum functionality. I had considered earlier using WINDOW_UPDATES to indicate when bytes had been written. I'm already needing to do something similar for inbound, so it could be natural do to it for outbound. However, the WINDOW_UPDATES do cause some reentrancy concerns and I'm not quite sure where to trigger them. Another option is to use `ProgressivePromise` to be notified of writes, which doesn't have reentrancy concerns and would be precise. I don't think `ProgressivePromise` works correctly today with `CoalescingBufferQueue` and `DefaultHttp2FrameWriter`/`SimpleChannelPromiseAggregator`. Fixing `ProgressivePromise` may be necessary in general, but it does look complex to implement and seems very likely to have subtle bugs.

**Comment by normanmaurer** [comment]
This is implemented as part of #6896

**Comment by ejona86** [comment]
#6896 is merged. It seems fixed.
