### ISSUE TITLE
DatagramPacket.recipient() doesn't return the actual destination IP, but the IP the app is bound to

### ISSUE THREAD

**Issue by mpolonio** [netty/netty#4950]
I'm using epoll (on previous versions of my app I was using NIO and I think the behaviour is the same) on an application that is listening on all available interfaces (0.0.0.0). When I try to get the actual UDP packet destination IP, DatagramPacket.recipient() returns 0.0.0.0 and not the real packet destination IP. It seems to always return the IP the app is bound to.

Please, let me know if you need some extra information.

SO: Ubuntu 14.04.4
Netty version: 4.0.32.Final

**Comment by normanmaurer** [comment]
Will check...

**Comment by windie** [comment]
Looks like netty cannot get the udp destination address. See:

http://developerweb.net/viewtopic.php?id=4342
http://developerweb.net/viewtopic.php?id=4169

**Comment by mpolonio** [comment]
Thanks Windie for your comments. I think I have a better understanding of the problem now. IP_PKTINFO socket option should be set, in order to get the ancillary message with required extra information (Destination IP and more) available.
Java doesn't seem to provide any API to set this socket option, but I've searched this repo and epoll sockets seem to be created with C code (https://github.com/netty/netty/blob/4.0/transport-native-epoll/src/main/c/netty_unix_socket.c). So, maybe is still possible to have the UDP destination address available...

**Comment by normanmaurer** [comment]
@mpolonio yep I think I can make it work for native transport. Stay tuned.

**Comment by mpolonio** [comment]
Hi @normanmaurer, did you have the time to take a closer look on the issue?

**Comment by normanmaurer** [comment]
@mpolonio not yet... sorry super busy and not high priority atm :(

**Comment by mkarasik** [comment]
Do you have any plans to addrtess this?

**Comment by normanmaurer** [comment]
Sorry but I had no cycles yet to do this and its not very high on my to do list. That said we love contributions.

**Comment by mpolonio** [comment]
Thanks a lot

**Comment by pendula95** [comment]
Although this seems to be fixed this quite does not work for us. We are using a loading balance with KeepAlive which receives traffic via VIP address. Than it is routed to individual hosts via Direct Routing. Direct Routing works by replacing the target MAC in a package addressed to the loadbalancer to its virtual / loadbalancer IP with the MAC of the designated target server and re-sending it. This requires the servers to accept packages for the given IP, so they need to configure the corresponding IP on some local looopback / dummy device. 
For this we have setup dummy interfaces with VIP address on the server machines. UDP packages are received on the netty server that has been bootstrapped with IP_RECVORIGDSTADDR. 
Despite this msg.recipient() does not return the VIP address but and address of the server it has been routed for. I am not an expert for linux/bsd socketing so I am not sure if this is even supposed to work but I know there is software written in C (FreeRadius) which reads the correct address (VIP) as destination address of the received packet. 
We are doing this as we need to respond to the UDP packet from the same received address  specified by Radius Protocol.
Any idea why this is not working and how it can be fixed?
