### ISSUE TITLE
Netty4.0.24 LengthFieldBasedFrameDecoder has a bug?

### ISSUE THREAD

**Issue by omanhom** [netty/netty#4953]
In my project, I use netty4.0.24, but run for a period of time, the program will occasionally appear decode exception，here's my screenshot:
![image](https://cloud.githubusercontent.com/assets/13151762/13595412/035617ea-e546-11e5-8852-420efde7be82.png)

![image](https://cloud.githubusercontent.com/assets/13151762/13595519/f47f8200-e546-11e5-8457-12b15f8f4b2e.png)

![image](https://cloud.githubusercontent.com/assets/13151762/13595533/1e585228-e547-11e5-833b-64e94633decd.png)

Please tell me how to do,thanks

**Comment by normanmaurer** [comment]
@omanhom could you please upgrade to netty 4.0.34.Final and let me know if you still see the problem ?

**Comment by normanmaurer** [comment]
Please re-open if you still think there is any issue after upgrading.

**Comment by omanhom** [comment]
the cause of the problem is found, it is the client's business logic problem.so sorry!!
