### ISSUE TITLE
Android support on netty 5.x 

### ISSUE THREAD

**Issue by junchaowu** [netty/netty#4954]
As far as I know, it doesn't support Android on 5.x version right now. Have you planned to add it on road map?

**Comment by junchaowu** [comment]
``request failed due to: Unable to create Channel from class class io.netty.channel.socket.nio.NioSocketChannel``

**Comment by johnou** [comment]
@junchaowu see #4466

**Comment by junchaowu** [comment]
in that case do I need to change my project back to use 4.x version or I can stick with 5.x for netty? Which way you recommend?

**Comment by normanmaurer** [comment]
Use 4.0 or 4.1

**Comment by junchaowu** [comment]
Does 4.1 release on Fed 2016 support Android?

**Comment by normanmaurer** [comment]
Yes it should
