### ISSUE TITLE
Use shaded dependency on JCTools instead of copy and paste

### ISSUE THREAD

**Issue by nitsanw** [netty/netty#4960]
I thought this was not the case, but it appears Netty is using a C&P dependency model. This has some serious flaws, which is why versioned dependencies are the standard in Java for some time now...

**Comment by nitsanw** [comment]
Happy to PR a build change if that helps.

**Comment by Scottmitch** [comment]
@nitsanw - Copy/paste is for sure not ideal. I'm guessing ( @normanmaurer ? ) some of the rational for cpy/paste was to use Netty's `PlatformDependent` to isolate unsafe access ... I'm not sure if this is necessary anymore (looks like there is non-unsafe versions of queues in JCTools). Assuming there are no obstacles (compatibility, java6 support, etc...) I'm in favor of pulling in a shaded JCTools.

**Comment by nitsanw** [comment]
none that I know of, JCTools is supports JDK6. I believe the Netty copies are unmodified (beyond formatting etc).

**Comment by guidomedina** [comment]
@Scottmitch 

There isn't any obstacle that I can see in using PlatformDependent class (I looked at its source code) + JCtools as what it does is to return either a non-blocking queue if it supports Unsafe or its best JDK counterpart.

@nitsanw but it can't be version 1.1, it has to have the fixes you added lately.

**Comment by guidomedina** [comment]
@Scottmitch @nitsanw in fact, PlatformDependent is a convenient class as you can fallback to JCtools atomic version if Unsafe is not supported.

**Comment by nitsanw** [comment]
I would think starting with 1.1 to work out the build kinks would be fine. Moving to 1.2 when released (next few days I hope) will close #4959

**Comment by nitsanw** [comment]
@Scottmitch JCTools 1.2 released. Let me know if anything else is required

**Comment by Scottmitch** [comment]
@nitsanw - Thanks for the heads up!

@normanmaurer - This seems like a good thing todo ... wdyt?

**Comment by normanmaurer** [comment]
Let me have a look tomorrow

**Comment by nitsanw** [comment]
Any news? anything I can do to help?

**Comment by normanmaurer** [comment]
No news yet just to busy atm. But will try to pick it up next week

**Comment by guidomedina** [comment]
@normanmaurer @nitsanw

I have a branch with this migration done but I got stuck with the shade part please feel free to re-use/look at this commit: 

https://github.com/guidomedina/netty/commit/7d1a621e8af4344fe18a910cdd5c7cb372390ad5

**Comment by johnou** [comment]
@guidomedina something like this https://github.com/johnou/netty/commit/d977f65e4e496fa81c6ca94992d7e5f97232da6c 

I will create a PR later today.

**Comment by guidomedina** [comment]
@johnou excellent, it was easier than what I thought, I was too overwhelmed by netty-modules and netty-all but thanks to you guys with deep knowledge of Netty poms this is done.

**Comment by guidomedina** [comment]
@johnou minor thing, I think shade latest version is 2.4.3 according to https://maven.apache.org/plugins/maven-shade-plugin/usage.html

**Comment by johnou** [comment]
Alright, I will bump the version in my branch, test then squash / create a PR in a few hours. Cool thing with maven-shade-plugin is it should automatically create a dependency reduced pom for the common module so it will stay "zero dependency".

**Comment by johnou** [comment]
https://github.com/netty/netty/pull/5051

**Comment by nitsanw** [comment]
Any progress on this?

**Comment by normanmaurer** [comment]
Will look into it once back from vacation

**Comment by nitsanw** [comment]
@normanmaurer welcome back! _nudge nudge_

**Comment by normanmaurer** [comment]
@nitsanw looking into it as we speak

**Comment by normanmaurer** [comment]
Was merged
