### ISSUE TITLE
HttpObjectAggregator till max message size

### ISSUE THREAD

**Issue by wolftobias** [netty/netty#4962]
I`m facing the problem that I get a HttpMessage object and a LastHttpContent object message from HttpRequestDecoder/HttpResponseEncoder and we forward these message to the destination as a kind of proxy server. But then the HttpMessage and LastHttpContent objects are send each in new tcp frames, which is not what I want. They are small enough to fit in one tcp packet.
When I use the HttpObjectAggregator it works fine, until the complete message grows over the HttpObjectAggregator defined max size in the constructor. I need a HttpObjectAggregator which combines the HttpMessage and LastHttpContent into one and if they both exeed a limit it should be fall back into the HttpMessage, HttpContents and LastHttpContent mode. Is such a handler available?

**Comment by normanmaurer** [comment]
No there is not but you can just build such a handler by yourself
