### ISSUE TITLE
Change HttpServerUpgradeHandler.UpgradeCodec to allow aborting upgrade

### ISSUE THREAD

**Issue by ejona86** [netty/netty#4971]
I noticed that `Http2ServerUpgradeCodec.prepareUpgradeResponse()` [doesn't quite have the right behavior](https://github.com/netty/netty/blob/43ebbc3fa065155fa67732b0cbd7c12843b0f3f7/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ServerUpgradeCodec.java#L95), since failures in the UPGRADE protocol generally abort the upgrade instead of responding with an error. Primarily:
> A server MUST NOT upgrade the connection to HTTP/2 if this header field is not present or if more than one is present.

That said, the spec does not specify what should happen if the value of `HTTP2-Settings` is invalid (either invalid base64 or invalid SETTINGS payload).

To fix this behavior seems like it would be necessary to change the UpgradeCodec interface in codec-http. `prepareUpgradeResponse()` could return a `boolean` to indicate whether the upgrade is successful. If `false`, `HttpServerUpgradeHandler.upgrade()` would return false and the connection would continue using HTTP/1.

**Comment by normanmaurer** [comment]
Let me take care.

**Comment by normanmaurer** [comment]
Fixed
