### ISSUE TITLE
Remove misleading argument from HttpServerUpgradeHandler.UpgradeCodec.upgradeTo

### ISSUE THREAD

**Issue by ejona86** [netty/netty#4972]
`upgradeTo()` is currently passed `upgradeResponse`, but it doesn't appear like it can do anything useful with it since the response has already been sent. In addition, the [`upgradeTo()` documentation](https://github.com/netty/netty/blob/43ebbc3fa065155fa67732b0cbd7c12843b0f3f7/codec-http/src/main/java/io/netty/handler/codec/http/HttpServerUpgradeHandler.java#L75) is sort of misleading as it seems to imply that it should be sent and may be modified before sending.

**Comment by normanmaurer** [comment]
@ejona86 agree... let me take care of it.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4989
