### ISSUE TITLE
AbstractNioSelector.run doesn't read taskQueue in realTime

### ISSUE THREAD

**Issue by wahisoufiane** [netty/netty#4982]
Hi, 

in the netty 3.10 version, I met a problem in adding task to the taskQueue by registering it, but the task aren't found directly, it take a while (like 250 seconds) then the processTaskQueue() called from run() method found my tasks.

this code : 

```
    private void processTaskQueue() {
        for (;;) {
            System.out.println("SIZE FROM LOOP : "+taskQueue.size());
            final Runnable task = taskQueue.poll();
            if (task == null) {
                break;
            }
            task.run();
            try {
                cleanUpCancelledKeys();
            } catch (IOException e) {
                // Ignore
            }
        }
    }
   protected final void registerTask(Runnable task) {
        taskQueue.add(task);
        System.out.println("SIZE FROM REGISTER : "+taskQueue.size());
        Selector selector = this.selector;

        if (selector != null) {
            if (wakenUp.compareAndSet(false, true)) {
                selector.wakeup();
            }
        } else {
            if (taskQueue.remove(task)) {
                // the selector was null this means the Worker has already been shutdown.
                throw new RejectedExecutionException("Worker has already been shutdown");
            }
        }
    }

```

and in the log I found this result :

```
SIZE FROM REGISTER : 1
SIZE FROM LOOP : 0
SIZE FROM LOOP : 0
SIZE FROM LOOP : 0
SIZE FROM LOOP : 0
SIZE FROM LOOP : 0
...
SIZE FROM LOOP : 1
```

**Comment by normanmaurer** [comment]
@wahisoufiane are you sure you not block the IO thread somehow ?

**Comment by wahisoufiane** [comment]
I stop mysql service to generate the problem, but in the real case in the
server, there is no blocked IO Thread, everything went correctly till a
certain point when this problem occur.

What took my attention is why the taskQueue variable are full, but seen
like empty in the processQueue in the same time?!!

On Tue, Mar 15, 2016 at 3:35 PM, Norman Maurer <notifications@github.com>
wrote:

> @wahisoufiane <https://github.com/wahisoufiane> are you sure you not
> block the IO thread somehow ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/netty/netty/issues/4982#issuecomment-196881207
>



-- 
*Soufiane Wahi*

*Ingénieur Développement*

**Comment by normanmaurer** [comment]
@wahisoufiane I'm not sure I understand... can you maybe provide a failing unit test or so ?

**Comment by wahisoufiane** [comment]
I'm sorry I don't have any unit test, but I can clarify the situation
better.

In the AbstractNioSelector we have registerTask and we have an infinit loop
in the run() method.
We have a field collection of runnable named taskQueue.
When we call registerTask, we add a runnable to taskQueue.
The infinite loop (run()) call processQueue() and run the tasks on the
taskQueue.
Normally and logically, when we call registerTask with a task, the next
call of processQueue have to found this task in the collection, but here
when i do a println of the size of the collection both in the registerTask
and processQueue, I don't have the same size for a while. is this logic?

On Tue, Mar 15, 2016 at 3:42 PM, Norman Maurer <notifications@github.com>
wrote:

> @wahisoufiane <https://github.com/wahisoufiane> I'm not sure I
> understand... can you maybe provide a failing unit test or so ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/netty/netty/issues/4982#issuecomment-196886276
>



-- 
*Soufiane Wahi*

*Ingénieur Développement*

**Comment by normanmaurer** [comment]
@wahisoufiane I'm not sure if you "debugging" code is correct as between the `System.out.println(...)` and the poll the task me be added. So you will see `0` but the poll will actually be able to to see the element.

**Comment by wahisoufiane** [comment]
No I'm sure the poll didn't find anything because when I put breakpoint,
the task returned by the poll is null and didn't continue the loop it break
it.

**Comment by normanmaurer** [comment]
netty 3.x is EOL. Please upgrade to 4.x.
