### ISSUE TITLE
[Improvement] SniHandler doesn't support mutual ssl.

### ISSUE THREAD

**Issue by doom369** [netty/netty#4985]
Hello. I changed domain name on production system. And I found that netty allows easily handle such cases with SniHandler. But the problem is SniHandler doesn't allow to use mutual ssl contexts because of this code :

```
    private void select(ChannelHandlerContext ctx, String hostname) {
        SslContext selectedContext = mapping.map(hostname);
        selection = new Selection(selectedContext, hostname);
        SslHandler sslHandler = selectedContext.newHandler(ctx.alloc());
        ctx.pipeline().replace(this, SslHandler.class.getName(), sslHandler);
    }
```

I fixed that for myself with :

```
    private void select(ChannelHandlerContext ctx, String hostname) {
        AppSslContext selectedContext = mapping.map(hostname);
        selection = new Selection(selectedContext, hostname);
        final SSLEngine engine = selectedContext.sslContext.newEngine(ctx.alloc());
        if (isMutualSSL) {
            engine.setUseClientMode(false);
            engine.setNeedClientAuth(true);
        }
        SslHandler sslHandler = new SslHandler(engine);
        ctx.pipeline().replace(this, SslHandler.class.getName(), sslHandler);
    }
```

Where `isMutualSSL` is a flag that I pass on SniHandler creation. 
I could easily do PR in few days.

WDYT?

**Comment by normanmaurer** [comment]
@doom369 you can just specify this stuff when building the `SslContext` via `SslContextBuilder`. Does this not work ?

**Comment by doom369** [comment]
@normanmaurer Didn't know about that. Let me check.

**Comment by normanmaurer** [comment]
@doom369 https://github.com/netty/netty/blob/4.0/handler/src/main/java/io/netty/handler/ssl/SslContextBuilder.java#L380 . Please close the issue if it works.

**Comment by doom369** [comment]
@normanmaurer nice! Works perfectly. Thank you! When I wrote this code there was no such thing =). Anyway I think it would nice to add SniHandler example for noobs like me. I'll prepare PR in few days.

**Comment by normanmaurer** [comment]
@doom369 awesome... thanks!
