### ISSUE TITLE
ChannelInitializer prevents propagation of channelRegistered event

### ISSUE THREAD

**Issue by tbcs** [netty/netty#4994]
If I understand Netty's event handling correctly, in general it doesn't (shouldn't?) matter whether a channel handler was added to the pipeline via `addFirst` or `addLast`, the rules of event propagation are the same.  This is not the case though when the pipeline is modified within `ChannelInitializer::initChannel`.  `ChannelInitializer` is implemented as a handler, it's part of the pipeline when `initChannel` is invoked and it removes itself afterwards.  With the current implementation of `ChannelInitializer::channelRegistered`, handlers added via `addFirst` do not receive the channelRegistered event.

Tested with current HEAD of Netty's v4.1 branch.

% java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
% uname -a
Linux marvin 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4995
