### ISSUE TITLE
DefaultCookie's own name validation doesn't conform to RFC6265

### ISSUE THREAD

**Issue by slandelle** [netty/netty#4999]
`io.netty.handler.codec.http.cookie.DefaultCookie` does its own validation on the name characters.

This check has 2 issues:
* it doesn't conform to RFC6265, eg seperators such as `@` are allowed
* it's redundant with the checks performed in CookieEncoder/Decoder in STRICT mode (those are RFC6265 compliant)

IMO, we should remove it and let the encoders/decoders do the job.

**Comment by normanmaurer** [comment]
Sounds good

**Comment by slandelle** [comment]
If you want a distinct PR, I'll wait for the current one to get merged. Otherwise, I can simply amend.

**Comment by normanmaurer** [comment]
@slandelle Just merged it... Please do another PR with a test :)
