### ISSUE TITLE
Teamcity build: Should the target for building be 'install' instead of 'clean validate' 

### ISSUE THREAD

**Issue by danbev** [netty/netty#5010]
When a pull request is build it looks like the Maven goals [clean validate](https://garage.netty.io/teamcity/viewLog.html?buildId=6758&buildTypeId=pulls_netty&tab=buildLog#_focus=106) are executed. We have added a new codec named codec-sockjs which is [failing](https://garage.netty.io/teamcity/viewLog.html?buildId=6758&buildTypeId=pulls_netty&guest=1) because this is not yet available in a sonatype snapshot repository. If the Maven goal used was `install`, perhaps skipping tests at this first stage, then this artifact would be available in the local maven repo of the build server. 

Does this make sense or am I missing something here perhaps?

**Comment by normanmaurer** [comment]
@danbev I think the problem would be that it would install stuff locally that is not yet merged and may be picked up on other runs. Or I`m missing something ?

**Comment by danbev** [comment]
> I think the problem would be that it would install stuff locally that is not yet merged and may be picked up on other runs. Or I`m missing something ?

What I'm seeing is that this is a new maven module/project named codec-sockjs, which is not available in any Sonatype snapshot repository yet. The build is currently failing for this reason from what I can see. Does that make sense? 

Not sure how I can get the build server to complete as it will not get passed this stage.

**Comment by normanmaurer** [comment]
@trustin any idea ?

**Comment by eun-ice** [comment]
Maybe maven just tries to check for new versions of snapshot dependencies.

You could try using "mvn -o clean validate" or disabling snapshots from sonatype alltogether

```
    <repositories>
        <repository>
            <id>sonatype-nexus-snapshots</id>
            <name>Sonatype Nexus Snapshots</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

```

**Comment by trustin** [comment]
Unless the final goal is package or install, Maven tries to fetch the snapshot JARs from the repository and that will cause the problem @danbev reported.

There are two ways to solve the problem: 1) deploy snapshot JARs more frequently (e.g. for each commit) or 2) do not run `mvn clean validate` but just `mvn clean package`

The reason why I ran `mvn clean validate` first and then `mvn package` is because most PRs fail due to checkstyle errors. Given that all the tests and compilation takes much longer time than validation, it's better fail fast.

Probably the simplest solution would be (2) + increased number of TeamCity build agents (i.e. more computing resources)

**Comment by trustin** [comment]
Another PR build problem I wanna solve with this issue is to reject building a PR with diverged commits. This would be very useful when a user chose a wrong merge target when creating a PR.

**Comment by danbev** [comment]
> 2) do not run mvn clean validate but just mvn clean package

That sounds like a good idea to me and would work around this issue. Perhaps the running of tests could be deferred to speed things up a little so that checkstyle issues could be found early in the process, and then have an explicit run of the tests. Some thing like
```shell
$ mvn clean package -DskipTests
$ mvn test
```
Not sure if that is doable with the TeamCity server configuration. I looked around but could not find where the actual configuration is (might have been a permissions thing).

**Comment by danbev** [comment]
@trustin I'd be happy to try out your suggestion (nr 2) if you don't have the spare cycles at the moment. If so, could you give me the permissions required on the build server?

**Comment by trustin** [comment]
@danbev I've just updated the TeamCity settings so that it runs `mvn -DskipTests clean package` first and then `mvn package`. Thanks for a great idea!

**Comment by danbev** [comment]
@trustin Awesome, thanks for that!
