### ISSUE TITLE
Minor typo in DefaultStompFrame.toString()

### ISSUE THREAD

**Issue by ssimd** [netty/netty#5013]
Hi,

in current Netty 4.1.x, the DefaultStompFrame.toString() method writes a different class name (Default**Full**StompFrame)  than it actually is... I think it's a minor typo, however for new users of the Stomp codec it's confusing when you cannot locate the class at first.

https://github.com/netty/netty/blob/4.1/codec-stomp/src/main/java/io/netty/handler/codec/stomp/DefaultStompFrame.java#L97

Best regards,
Stefan

**Comment by normanmaurer** [comment]
Thanks for reporting. I will take care.
