### ISSUE TITLE
HandlerException:syscall:read(...)() failed: Connection reset by peer

### ISSUE THREAD

**Issue by ramtg** [netty/netty#5031]
I upgraded my server app from netty 4.0.34 to 4.0.35  and after a few hours started noticing exceptions when tcp socket clients attempted to connect to my app. 

I rolled it back to 4.0.34 and restartedand haven't seen those exceptions yet over the last 
18 hours.

Not sure whether it has anything remotely to do with 4.0.35 .

Any hints on what I might be doing wrong, will be much appreciated.

Thank you,
Ram

Here're some details:

==
HandlerException:syscall:read(...)() failed: Connection reset by peer

ServerBootstrap(group: EpollEventLoopGroup,
channelFactory: EpollServerSocketChannel.class,
options: {SO_REUSEPORT=true, SO_REUSEADDR=true},
childGroup: EpollEventLoopGroup,
childOptions: {SO_KEEPALIVE=false, TCP_NODELAY=true, SO_REUSEADDR=true}

)

== netty 4.0.35.Final 

== Server Bootstrap
new ServerBootstrap()
    .group(nettyNioThread)
    .option(EpollChannelOption.SO_REUSEPORT, true)
    .option(ChannelOption.SO_REUSEADDR, true)
    .childOption(ChannelOption.SO_KEEPALIVE, false)
/    .childOption(ChannelOption.TCP_NODELAY, true)
    .childOption(ChannelOption.SO_REUSEADDR, true)
    .childHandler(new ServerHandlerFactory(this));
if(listenerCfg.useEpoll() && Epoll.isAvailable()) {
    this.serverBootstrap.channel(EpollServerSocketChannel.class);
} else {
    this.serverBootstrap.channel(NioServerSocketChannel.class);
}

== OS
cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"

== uname -a
Linux <ip> 3.13.0-61-generic #100-Ubuntu SMP Wed Jul 29 11:21:34 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

== JVM
/usr/lib/jvm/java-8-oracle/bin/java  -version
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)

**Comment by normanmaurer** [comment]
@ramtg thanks for reporting... @Scottmitch PTAL

**Comment by Scottmitch** [comment]
@ramtg - Are your clients also built on top of Netty, or are the clients out of your control?

**Comment by normanmaurer** [comment]
@ramtg also if you would have an easy way to reproduce it would be helpful

**Comment by Scottmitch** [comment]
@ramtg - If you can't provide a reproducer ... can you provide a TCP dump of when the issue occurs with the relevant packets? The sequence of TCP events would also be very helpful.

**Comment by ramtg** [comment]
@Scottmitch  Most of my clients are written in 'C',  but even my Netty based test clients were having their connections dropped.   Unfortunately I didn't have a chance to do a wireshark capture.

**Comment by normanmaurer** [comment]
will have a look

**Comment by Scottmitch** [comment]
@ramtg - What is the value of SO_LINGER on these clients?

**Comment by ramtg** [comment]
@Scottmitch  The Connection Reset by peer issue occurred on all types of connections including Netty based test clients. and I did not have SO_LINGER set on my Netty based tester client socket.

**Comment by normanmaurer** [comment]
@ramtg could you try using NIO and let us know if you see the same (would be interested in 4.0.34 and 4.0.35)

**Comment by normanmaurer** [comment]
@ramtg ok I think I know whats going on... stay tuned.

**Comment by johnou** [comment]
@normanmaurer would you please confirm whether or not this issue is epoll only?

**Comment by normanmaurer** [comment]
@johnou yes epoll only.

**Comment by normanmaurer** [comment]
@ramtg can you test https://github.com/netty/netty/pull/5048 ?

**Comment by ramtg** [comment]
@normanmaurer  Is a snapshot including this change, available on a maven repo ?

**Comment by Scottmitch** [comment]
should be in snapshot yes.

https://oss.sonatype.org/content/repositories/snapshots/io/netty/netty-transport-native-epoll/4.0.36.Final-SNAPSHOT/
