### ISSUE TITLE
https://github.com/netty/netty/commit/acbca192bd93b2691c86c5cec06e4fc1f15d6a05 Typo

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#5033]
https://github.com/netty/netty/commit/acbca192bd93b2691c86c5cec06e4fc1f15d6a05 introduced a typo where `setsockopt` should be `getsockopt` at [netty_unix_socket.c#L303]
(https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/c/netty_unix_socket.c#L303)

**Comment by Scottmitch** [comment]
@normanmaurer - should be a quick fix can you take care?

**Comment by normanmaurer** [comment]
Yep

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5035

**Comment by Scottmitch** [comment]
thanks @normanmaurer !
