### ISSUE TITLE
http://netty.io/wiki/developer-guide.html lost its content

### ISSUE THREAD

**Issue by wallellen** [netty/netty#5034]
![image](https://cloud.githubusercontent.com/assets/5259908/14019860/a294fc24-f20f-11e5-83d4-69e7be33c45f.png)

**Comment by Scottmitch** [comment]
@trustin @normanmaurer - Can you take a look?

**Comment by normanmaurer** [comment]
@Scottmitch yep...

**Comment by normanmaurer** [comment]
Fixed

**Comment by trustin** [comment]
Out of curiosity, what happened?

**Comment by normanmaurer** [comment]
Someone renamed the page 👎

**Comment by wallellen** [comment]
thanks
