### ISSUE TITLE
Netty 4.1.0.Final Release Date

### ISSUE THREAD

**Issue by ssheng** [netty/netty#5037]
We're considering moving to Netty 4.1.0 for the newly added HTTP/2 codec classes. We noticed that it is still at version .CR4, do you anticipate backward incompatible interfaces with .Final version. When is the planned release date? Thanks!

**Comment by normanmaurer** [comment]
@ssheng http2 and dns codec will remain experimental even in 4.1.0.Final. This is not because we thing the code not works but because we may want to break the API later on without a need for a major release. 

We not have a fixed release date but aim for the end of this month.

Hope this helps

**Comment by ssheng** [comment]
@normanmaurer thanks.
