### ISSUE TITLE
How to connect to multiple sever at the same time via netty?

### ISSUE THREAD

**Issue by nezen** [netty/netty#5038]
I'm working on an android app which connects to multiple sever at the same time. And I code like this:

`
public class TestThread extends Thread{
    
    private static final List<String> hosts = new ArrayList<>();

    private static final int PORT = 1234;

    public TestThread(){
        hosts.add("192.168.8.101");
        hosts.add("192.168.8.102");
        hosts.add("192.168.8.103");
    }

    @Override
    public void run() {
        Iterator<String> iter = hosts.iterator();
        while (iter.hasNext()){
            String host = iter.next();
            configureBootstrap(new Bootstrap(), new NioEventLoopGroup(), host, PORT).connect();
        }
    }

    private static Bootstrap configureBootstrap(Bootstrap b, EventLoopGroup g, String host, int port) {
        b.group(g)
                .channel(NioSocketChannel.class)
                .remoteAddress(host, port)
                .option(ChannelOption.SO_KEEPALIVE, true)
                .option(ChannelOption.TCP_NODELAY, true)
                .handler(new ChannelInitializer<SocketChannel>() {
                    @Override
                    public void initChannel(SocketChannel ch) throws Exception {
                        ch.pipeline().addLast(new CustomChannelInboundHandler());
                    }
                });

        return b;
    }
}
`
The code works but I'm confused about Bootstrap and EventLoopGroup. For now, each time I establish a new connection, I Instantiate a new Bootstrap and a new EventLoopGroup, Is this the right way and only way to do my work?

**Comment by normanmaurer** [comment]
Nope you should instance the EventLoopGroup and Bootstrap only one time and pass the remoteAddress to the connect method.

**Comment by uuttxtgyf** [comment]
same sample code please. @nezen

**Comment by nezen** [comment]
Hi @uuttxtgyf , it's been a long time, but I hope this will help:

        NioEventLoopGroup nioEventLoopGroup = new NioEventLoopGroup();
        Bootstrap bootstrap = configureBootstrap(new Bootstrap(), nioEventLoopGroup);

        Iterator<String> iter = hosts.iterator();
        while (iter.hasNext()) {
            final String host = iter.next();
            CustomChannelInboundHandler handler = new CustomChannelInboundHandler(this);
            ChannelFuture f = bootstrap.handler(getChannelInitializer(handler)).connect(host, 8964);
            f.addListener(new GenericFutureListener<Future<Void>>() {
                @Override
                public void operationComplete(Future future) throws Exception {

                }
            });
        }

**Comment by uuttxtgyf** [comment]
two kind of different  Server can use different ChannelInitializer ？can use one Bootstrap？ 
thanks very match！@nezen
