### ISSUE TITLE
Problems with SSLv3 and TLSv1 after updating to 4.0.35

### ISSUE THREAD

**Issue by doom369** [netty/netty#5041]
Hello. I was using netty 4.0.33 with openSSL and epoll and moved to 4.0.35. After that I got few problems with my SSL clients.

First problem is that all Android clients with Android version 4.0.x stopped working (not netty clients, vanilla sockets). On such clients I get 

```
avax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x20c97d8: Failure in SSL library, usually a protocol error
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (external/openssl/ssl/s23_clnt.c:658 0x4026bcc3:0x00000000)
at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:460) ~[na:0.0]
at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:257) ~[na:0.0]
at com.blynk.android.transport.tcp.SocketReader.run(SocketReader.java:107) ~[na:0.0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) ~[na:0.0]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) ~[na:0.0]
at java.lang.Thread.run(Thread.java:864) ~[na:0.0]
  Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x20c97d8: Failure in SSL library, usually a protocol error
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (external/openssl/ssl/s23_clnt.c:658 0x4026bcc3:0x00000000)
at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method) ~[na:0.0]
at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:410) ~[na:0.0]
```

on server :
`
Reason : javax.net.ssl.SSLHandshakeException: error:1408A10B:SSL routines:SSL3_GET_CLIENT_HELLO:wrong version number`

I googled a bit and found that 4.0.x Android versions support only SSLv3 and TLSv1 and look like this is root cause.

Second problem - when I try to access my HTTPS API from specific hardware I get 

`Reason : javax.net.ssl.SSLHandshakeException: Client requested protocol SSLv3 not enabled or not supported`

Switching back to 4.0.33 resolves above issues.

from
```
        <netty.version>4.0.35.Final</netty.version>
        <netty.tcnative.version>1.1.33.Fork14</netty.tcnative.version>
```
to
```
        <netty.version>4.0.33.Final</netty.version>
        <netty.tcnative.version>1.1.33.Fork8</netty.tcnative.version>
```

 Does something was changed regarding those protocol versions? Could you please advise?

**Comment by johnou** [comment]
@doom369 see https://github.com/netty/netty-tcnative/commit/c9e7cde8d5bd52e338637a08c76ac284aff44683#commitcomment-16793242

**Comment by doom369** [comment]
@johnou Thanks! So I should rebuild netty 4.0.35 with fork-15?

**Comment by johnou** [comment]
@doom369 yep, I found rebuilding netty-handler was enough.

**Comment by normanmaurer** [comment]
Yes this would fix it

**Comment by doom369** [comment]
I'm getting 

> /usr/lib/jvm/java-8-oracle/bin/java: symbol lookup error: /tmp/libnetty-transport-native-epoll3378165418167624804.so: undefined symbol: netty_unix_util_prepend

I suppose this because I builded netty fully? not only handlers

**Comment by johnou** [comment]
@doom369 without knowing more details about your build environment it's hard to say, but you should be able to exclude netty-transport-native-epoll from the parent pom locally and run the mvn package / install goal with skipTests=true to save some time.

**Comment by johnou** [comment]
Just came to mind that now Norman has updated the tcnative dependency in the Netty project you can grab a snapshot of the handler jar from TC.

https://garage.netty.io/teamcity/repository/download/netty_nightly/6935:id/handler/target/netty-handler-4.0.36.Final-SNAPSHOT.jar

**Comment by doom369** [comment]
Ok. My my suggestion was correct. So I did next :

```
        <netty.version>4.0.35.Final</netty.version>
        <netty.tcnative.version>1.1.33.Fork14</netty.tcnative.version>
```

```
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-common</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-handler</artifactId>
            <version>4.0.36.Final-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-codec-http</artifactId>
            <version>${netty.version}</version>
        </dependency>
```

Where 4.0.36.Final-SNAPSHOT is locally build of netty with fork-15 and it is working!

Thank you for super fast response. I really appreciate this!

**Comment by Scottmitch** [comment]
@doom369 - Sorry for the inconvenience. We will push out a new release soon to correct this, and other issues.

**Comment by doom369** [comment]
@Scottmitch not a problem I catched this on QA envirnoment =).
