### ISSUE TITLE
OpenSSL from renamed library

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty#5043]
When initializing openssl, the io.netty.handler.ssl.OpenSsl class tries to load the library "netty-tcnative".  Our (gRPC) current use of this works, but we also have some code that takes all C++ compiled code and compiles it into a single shared object.  When openssl is compiled this way, the OpenSsl class cannot load  "netty-tcnative" since it has been compiled into another library which is loaded by an out of band means.

Would it be possible to change this class to allow outside code to tell it that the library was loaded already?  org.apache.tomcat.jni.Library, on which OpenSsl depends, already has a similar mechanism for doing this.

**Comment by normanmaurer** [comment]
Can you libk me to how the Library thing allows it?

**Comment by carl-mastrangelo** [comment]
Sure:

https://github.com/netty/netty-tcnative/blob/1.1.33/openssl-dynamic/src/main/java/org/apache/tomcat/jni/Library.java#L76


Using that special name (which OpenSsl is doing) bypasses calling System.loadLibrary

**Comment by normanmaurer** [comment]
Will have a look

**Comment by carl-mastrangelo** [comment]
Some possible ideas:

* Loading org.apache.tomcat.jni.SSL in the static init block of OpenSsl could speculatively try initializing the class

**Comment by carl-mastrangelo** [comment]
Friendly ping @nmittler & @normanmaurer

**Comment by nmittler** [comment]
@carl-mastrangelo Jetty's solution seems reasonable to me. 

@normanmaurer WDYT?

**Comment by normanmaurer** [comment]
What is Jetty's solution?

**Comment by nmittler** [comment]
@normanmaurer Jetty's solution is to initialize the library with a String "provided". We could do something similar, possibly using a system property.  Although I'm thinking we may not even need it ... perhaps we just try to load the library and if it fails we immediately just try to initialize the library. See the solution proposed in #5121.
