### ISSUE TITLE
websocket server sample does not work for netty-example-4.0.35.Final-sources

### ISSUE THREAD

**Issue by ohmygodlin** [netty/netty#5045]
Directly run http/websocketx/server sample in netty-example-4.0.35.Final-sources would get "socket is closed" error. Then i try to modify:
1. WebSocketServerInitializer.java add websocket handler：
        pipeline.addLast(new WebSocketIndexPageHandler(WEBSOCKET_PATH));
        **pipeline.addLast(new WebSocketServerProtocolHandler(WEBSOCKET_PATH));**
        pipeline.addLast(new WebSocketFrameHandler());
2. WebSocketIndexPageHandler.java add exclude websocket response, and pass request to next handler as:
      ** if (websocketPath.equals(req.getUri()))**
        **{**
            **ctx.fireChannelRead(req.retain());**
        **}**
        // Send the index page
        **else **if ("/".equals(req.getUri()) || "/index.html".equals(req.getUri())) {

Please verify whether the step is fine, or i miss anything, thanks!

BTW, if i want to just use websocket server function. could i just import netty-codec-http-4.0.35.Final.jar, not import netty-all-4.0.35.Final.jar?

**Comment by Scottmitch** [comment]
@ohmygodlin - Can you elaborate and explicitly list how you start the client/server and what frames you send? The client and the server example seem to talk to each other (see below), and the web browser works as a client too.

Client
```bash
$ ./run-example.sh websocket-client
[INFO] Running: websocket-client (io.netty.example.http.websocketx.client.WebSocketClient -D_)
[jetty-alpn-agent] Using: alpn-boot-8.1.7.v20160121.jar
WebSocket Client connected!
ping
WebSocket Client received pong
bye
WebSocket Client received closing
WebSocket Client disconnected!
```

Server
```bash
$ ./run-example.sh websocket-server
[INFO] Running: websocket-server (io.netty.example.http.websocketx.server.WebSocketServer -D_)
[jetty-alpn-agent] Using: alpn-boot-8.1.7.v20160121.jar
09:44:58.647 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x90d05515] REGISTERED
09:44:58.650 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x90d05515] BIND: 0.0.0.0/0.0.0.0:8080
Open your web browser and navigate to http://127.0.0.1:8080/
09:44:58.653 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x90d05515, L:/0:0:0:0:0:0:0:0:8080] ACTIVE
09:45:01.105 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x90d05515, L:/0:0:0:0:0:0:0:0:8080] RECEIVED: [id: 0x45f75579, L:/127.0.0.1:8080 - R:/127.0.0.1:60298]
```

**Comment by ohmygodlin** [comment]
i import netty-all-4.0.35.Final-sources.jar into eclipse as war (i could create a new Java project, then only include websoecket server source, but i think this way is the same, and fast). Then select ejbModule->io.netty.example->http->websocketx->server->WebSocketServer.java. Right click the main method, then run as Java Application. Then showing in the eclipse console:
Mar. 29, 2016 9:46:02 am io.netty.handler.logging.LoggingHandler channelRegistered
Info: [id: 0x59e297f1] REGISTERED
Mar. 29, 2016 9:46:02 am io.netty.handler.logging.LoggingHandler bind
Info: [id: 0x59e297f1] BIND(0.0.0.0/0.0.0.0:8080)
Open your web browser and navigate to http://127.0.0.1:8080/
Mar. 29, 2016 9:46:02 am io.netty.handler.logging.LoggingHandler channelActive
Info: [id: 0x59e297f1, L:/0:0:0:0:0:0:0:0:8080] ACTIVE

After that, i access http://127.0.0.1:8080/ through Chrome, then get error in the Output:
Web Socket closed.

When i did change as mentioned in my description, then i could access http://127.0.0.1:8080, then send "hello world" or something else to websocket server, and is able get response to show in the Output. Did i miss anything?

**Comment by Scottmitch** [comment]
@normanmaurer - It does look like the backport of (68bbd4e9669aab4c29dcc1d23ef331aaa2aee333) from 4.1 as (2e6544fc0e2581f96652be02d86e777e8e0493bc) into 4.0 may have been incomplete.  The [pipeline.addLast(new WebSocketServerProtocolHandler(WEBSOCKET_PATH, null, true));](https://github.com/netty/netty/commit/68bbd4e9669aab4c29dcc1d23ef331aaa2aee333#diff-8763764a23aff44c7b88bfe6e98357e0R48) line looks like it didn't make it into 4.0.  Can you verify/take care?

@ohmygodlin - The item 2 you list above may still be an issue, but lets re-evaluate after we resolve the merge issue.

**Comment by normanmaurer** [comment]
Will check

**Comment by ohmygodlin** [comment]
i want to use the websocket server function, since netty-4.0.35.Final.tar.bz2 ‐ 21-Mar-2016 is the Stable, Recommended version. So do you suggest me to choose 4.1 version?

**Comment by normanmaurer** [comment]
@Scottmitch Doh! Good catch, fixed by 949bfdf8c532e23c0925f08e4c0d9662857c0e3c . Shame on me :(

@ohmygodlin you can just use the version you used as the defect is only in the example. Current 4.0 branch has the fix already.

**Comment by ohmygodlin** [comment]
one more question, if i want to just use websocket server function. could i just import netty-codec-http-4.0.35.Final.jar, not import netty-all-4.0.35.Final.jar?

**Comment by normanmaurer** [comment]
@ohmygodlin if you also import its dependencies,yes.

**Comment by ohmygodlin** [comment]
1. Is there any docs to tell what is dependencies for netty-codec-http-4.0.35.Final.jar?
2. since i still use 4.0.35, so according to your comments. i still need the 2 steps i list in my description?
**ctx.fireChannelRead(req.retain());**
and 
**pipeline.addLast(new WebSocketServerProtocolHandler(WEBSOCKET_PATH, null, true));**
Right?

**Comment by ohmygodlin** [comment]
Oh, just notice you put pipeline.addLast(new WebSocketServerProtocolHandler(WEBSOCKET_PATH, null, true));
in front of the 
pipeline.addLast(new WebSocketIndexPageHandler(WEBSOCKET_PATH));
that works.
Please Ignore my question 2. So is there any docs to tell what is dependencies for netty-codec-http-4.0.35.Final.jar?
