### ISSUE TITLE
can I use EventLoop for a general purpose?

### ISSUE THREAD

**Issue by nezen** [netty/netty#5046]
according to the doc, 

> Will handle all the I/O operations for a Channel once registered. One EventLoop instance will usually handle more than one Channel but this may depend on implementation details and internals.

I'm wondering if I can use it for a general purpose. For example, I want to check whether my client  receives a specific data within a definite duration right after connected to a server. 

Here is my code:

`    
@Override

    public void channelActive(final ChannelHandlerContext ctx) {
        final EventLoop loop = ctx.channel().eventLoop();
        loop.schedule(new Callable<Void>() {
            @Override
            public Void call() throws Exception {
                if(isSpecificDataReceived()){
                    //keep connected and do sth else;
                }else {
                    //close tcp connection
                    ctx.close();
                }
                return null;
            }
        }, 1000, TimeUnit.MILLISECONDS);
    }
`

**Comment by nezen** [comment]
btw, if the Callable is a long-duration task or blocks, will something terrible happen?

**Comment by Scottmitch** [comment]
Please ask questions on stackoverflow. Github is to report bugs or request features.

> I'm wondering if I can use it for a general purpose

"general purpose" may be a bit strong. In a typical Netty application each I/O thread is responsible for handling many sockets, and so blocking one of these threads could impact/delay processing for each of these sockets. You are free to execute/schedule runnable tasks on the EventLoop thread but just be aware it is a trade off ... the more time the I/O thread spends on your runnables ... the less time it spends handling socket I/O. If your tasks are async, or short lived this may be acceptable but like everything its best to test a few options with representative production load.
