### ISSUE TITLE
Netty-tcnative with statically-linked boringssl uber-jar won't load

### ISSUE THREAD

**Issue by jchambers** [netty/netty#5052]
I created a simple project to try out the new statically-linked netty-tcnative uber-jar, and was surprised to discover that things weren't working as expected. Here are my dependencies (I chose `netty-codec-http2` for similarity with another project I'm working on):

```xml
<dependencies>
    <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-tcnative-boringssl-static</artifactId>
        <version>1.1.33.Fork15</version>
    </dependency>
    <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-codec-http2</artifactId>
        <version>4.1.0.CR4</version>
    </dependency>
</dependencies>
```

…and here's the app:

```java
public static void main(final String[] args) {
    System.out.println("OpenSSL available? " + OpenSsl.isAvailable());
    System.out.println("ALPN available?    " + OpenSsl.isAlpnSupported());

    if (OpenSsl.unavailabilityCause() != null) {
        System.out.println("Unavailability cause:");
        OpenSsl.unavailabilityCause().printStackTrace(System.out);
    }
}
```

When I run it under OS X (I'm afraid I don't have other environments handy right now), I get this:

```
OpenSSL available? false
ALPN available?    false
Unavailability cause:
java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty-tcnative-osx-x86_64, netty-tcnative]
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:167)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:78)
	at TcnativeBoringsslUberJarSandboxApp.main(TcnativeBoringsslUberJarSandboxApp.java:6)
```

Setting a breakpoint at [`NativeLibraryLoader.java#L164`](https://github.com/netty/netty/blob/4653dc1d05cfac8766bed63c4dd28c8d06128423/common/src/main/java/io/netty/util/internal/NativeLibraryLoader.java#L164), it looks like we're running into this for both `netty-tcnative-osx-x86_64` and `netty-tcnative`:

```
java.lang.UnsatisfiedLinkError: no netty-tcnative-osx-x86_64 in java.library.path
```

From [the wiki](http://netty.io/wiki/forked-tomcat-native.html), it sounds like adding the uber-jar as a dependency should be enough to get going. Did I miss a step, or is something amiss here?

Thanks!

**Comment by panchenko** [comment]
Looking on the file sizes in http://search.maven.org/#artifactdetails%7Cio.netty%7Cnetty-tcnative-boringssl-static%7C1.1.33.Fork15%7Cjar - looks like uberjar is not there.

**Comment by Scottmitch** [comment]
@nmittler @normanmaurer - WDYT?

**Comment by normanmaurer** [comment]
We did not release an uber jar yet. Wilk do this the first time for Fork16

**Comment by jchambers** [comment]
> We did not release an uber jar yet.

Well, that explains everything ;)

Thanks, and sorry for the bogus bug report.

**Comment by vietj** [comment]
@normanmaurer any ETA on Fork16 release ?
