### ISSUE TITLE
EmbeddedChannel instance should not share the same ID

### ISSUE THREAD

**Issue by SummerWish** [netty/netty#5053]
In current implementation, all `EmbeddedChannel` instances have the same id, which prevents them to be added to the `ChannelGroup`. This makes it impossible to test the "broadcast" scenario implemented by `ChannelGroup`.

**Comment by normanmaurer** [comment]
@SummerWis You can inject your own `ChannelId` for this case:

https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/embedded/EmbeddedChannel.java#L82

**Comment by SummerWish** [comment]
Thank you! But I found that this method does not exist in netty 5.0.0.Alpha2. Any workarounds?

**Comment by normanmaurer** [comment]
@SummerWish nope... you should switch to latest 4.1.0.CRx release anyway as the 5.0.x release series was deprecated and we will not do any more releases there in the near future.

**Comment by SummerWish** [comment]
Got it, thanks :-)
