### ISSUE TITLE
IpV4Subnet.contains() always returns true for single-address subnets (3.10.4)

### ISSUE THREAD

**Issue by ashleymercer** [netty/netty#5054]
I may have this wrong (since I'm fairly new to network programming) but my understanding is that a /32 CIDR block represents a single IP address, so I would expect an IpV4Subnet instance with this range to only match that exact IP - but, for example

new IpV4Subnet("1.1.1.1/32").contains("10.0.16.64")

both return true (at least in the version I tested, netty-3.10.4) The same is true for an IpV4Subnet instance constructed with mask notation (eg 1.1.1.1/255.255.255.255).

**Comment by normanmaurer** [comment]
checking...

**Comment by normanmaurer** [comment]
Verified that the issue not exists in 4.x. Looking into 3.10.x now.

**Comment by guidomedina** [comment]
Hi @normanmaurer I would like to know if there are any plans to fix this soon as I would like to see 3.10.6.Final released as soon as it is humanly possible.

**Comment by normanmaurer** [comment]
I had no time yet... If you want help submit a PR 👍

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5451
