### ISSUE TITLE
Can not use MqttEncoder

### ISSUE THREAD

**Issue by jorcasso** [netty/netty#5062]
Netty version: 4.1.0.CR5

Context:
I found that as of this commit https://github.com/netty/netty/commit/269677820df53b1b26cc17f772049cd6b7e88c9b the contructor of the `MqttEncoder` class becomes private and the only way to get an instance of this class is using the static attribute `MqttEncoder.INSTANCE`, however this handler is not marked as `Sharable`, so I can not use it in different pipelines.

**Comment by normanmaurer** [comment]
@jorcasso doh! my failure. Will fix it.

**Comment by jorcasso** [comment]
thanks!

**Comment by normanmaurer** [comment]
Fix in here: https://github.com/netty/netty/pull/5063

**Comment by normanmaurer** [comment]
Fixed https://github.com/netty/netty/pull/5063
