### ISSUE TITLE
Make NIO and EPOLL autoReadClear consistent

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#5069]
[AbstractNioChannel readPending](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/nio/AbstractNioChannel.java#L64) is volatile because it is directly set when [autoRead is cleared](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/socket/nio/NioSocketChannel.java#L364). The EPOLL transport takes an alternative approach and avoids the need for `readPending` to be volatile. [EpollChannelConfig calls clearEpollIn()](https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollChannelConfig.java#L175) which will run immediately if on the event loop and if not execute a runnable to run on the event loop.

**Comment by Scottmitch** [comment]
If the EPOLL approach is acceptable this would be preferred as it would remove a volatile which is written to frequently in the event loop. The only hesitation is that [AbstractNioChannel](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/nio/AbstractNioChannel.java#L133) exposes `readPending` with protected accessor methods ... however I'm not sure if anyone should be relying on the volatile nature of this variable...

@normanmaurer @trustin - WDYT?

**Comment by Scottmitch** [comment]
This was discovered during investigation in https://github.com/netty/netty/pull/5067 and removing a volatile will become more important as the call frequency to `setReadPending` will increase (if the changes in this PR are "correct").

**Comment by normanmaurer** [comment]
@Scottmitch I would agree that the EPOLL approach is "ok". @trustin WDYT ?
