### ISSUE TITLE
SslHandler and extra work on handshakeFuture

### ISSUE THREAD

**Issue by vkostyukov** [netty/netty#5078]
This is mostly a discussion, not an issue so I apologies if I used the wrong channel for that. But there is something I'm trying to do and I'm not 100% sure there is an API for this in Netty (`SslHandler`) so I decided to open this question and discuss a possible solution (or being told that there is already a way to do that and shamefully disappear).

I'm trying to run a simple validation (`SSLSession => Boolean`) of the `SSLSession` returned from the underlying engine on `SslHandler`. Naturally, I'm trying to use `handshakeFuture` to do that simply saying that "once handshake is done, please do validate the session". The problem is that I want to propagate custom exception (returned from the validation function) to the caller (in this case whoever initialized write) and fail its write-promise. 

The use case is following:

1. We `write` to the channel and use returned write-promise to determine whether or not the write succeed.
2. Write is queued in `SslHandler` and the handshake begins (write-promise is pending)
3. Handshake succeed and the `handshakeFuture` is satisfied (write-promise is still pending).
4. We run the custom validation function as a callback on `handshakeFuture`, which fails with exception (write-promise is still pending).
5. We want to fail the pending write promise with that exception to "explain" the caller why the write was failed, but there is no way to do that (right?).

We could close the channel, but it will fail our pending writes with `ClosedChannelException`. What I actually want to do is to call `pendingUnencryptedWrites.removeAndFailAll(cause)`, which is private on `SslHandler`.

Please, let me know if it doesn't make any sense and I'm totally doing something wrong. I'm pretty sure there is some piece that I'm missing in this puzzle.

**Comment by normanmaurer** [comment]
@vkostyukov so just to put it very simple you want to have the write futures failed with the ssl exception that are still queued in the SslHandler ?

**Comment by normanmaurer** [comment]
@vkostyukov ah I think I now understand better what you want to do... I think what you could do is actually return your own ChannelPromise to and full-fill it or fail it.

Something like:
```java
final Future<Channel> handshakeFuture = sslHandler.handshakeFuture();
final ChannelPromise promise = channel.newPromise();
channel.writeAndFlush(...).addListener((f) -> {
    if (!f.isSuccess()) {
        if (!handshakeFuture.isSuccess()) {
            promise.setFailure(handshakeFuture.cause());
        } else {
            promise.setFailure(f.cause());
        }
    } else {
        promise.setSuccess();
    }
}

return promise;
```

**Comment by vkostyukov** [comment]
Thanks @normanmaurer! This is pretty close to what I meant. Even though I was thinking of different relation, your example inspired me for an idea I think should work.

The reason I opened an issue is that I was thinking we can provide a method on `SslHandler` that fails an underlying pending writes (i.e., calls `pendingUnencryptedWrites.removeAndFailAll `). But I agree, it's doable w/o it, by keeping in mind, that you can always insert a handler before `SslHandler` and _collect_ your write promises there so you can fail them later (once handshake is done and a custom validation is performed) .

That's why I was hoping to discuss whether or not you think it's a popular use-case (perform extra work on successful handshake and fail pending writes if needed) and whether we need a method on `SslHandler` to simplify it (being able to do that w/o an extra handler and a trick with collecting promises).

Anyways, thanks a lot for your help. I'm extremely sorry to [be a bother](https://twitter.com/normanmaurer/status/717316926742114304) today.

**Comment by normanmaurer** [comment]
@vkostyukov no worries buddy. Happy to help

**Comment by normanmaurer** [comment]
@vkostyukov also this tweet was not related to you question ;)
