### ISSUE TITLE
DefaultThreadFactory should stick to the thread group where it was constructed

### ISSUE THREAD

**Issue by zhangkun83** [netty/netty#5084]
We (gRPC) encountered a bug that was triggered by https://github.com/grpc/grpc-java/commit/d927180a63ac2df4fae0082b51d51e3836771bb1. After that commit, event loop threads are created per task by `NioEventLoopGroup`, and inherits the thread group of the caller, which in our case is an application-provided request-scope thread. Things go south when the application tries to manipulate (e.g., interrupt and join) all threads of the request-scope thread group, which unexpectedly include the event loop threads.

I think `DefaultThreadFactory` should save the current thread group in constructor, and apply it to all new threads. I will come up with a PR soon.

@buchgr

**Comment by normanmaurer** [comment]
@zhangkun83 sounds good. Thanks!

**Comment by normanmaurer** [comment]
@zhangkun83 please ensure you sign our icla: http://netty.io/s/icla and use our commit message template http://netty.io/wiki/writing-a-commit-message.html when doing the pr :)

**Comment by buchgr** [comment]
@zhangkun83 good catch!

**Comment by jasontedor** [comment]
The fix in this PR is a mistake. For just one example, it means that the `DefaultThreadFactory` field in `GlobalEventExecutor` will have its thread group forever tied to the thread group that triggered the initialization of the `GlobalEventExecutor`. Since the `GlobalEventExecutor` is a global, a thread from another thread group could trigger the creation of a thread from this factory and will modify properties on the created thread. This is completely counter to the point of thread groups, and certain security managers will slap this down. Same for the `ThreadDeathWatcher`. I will open a PR to change.

**Comment by s1monw** [comment]
++ @jasontedor

**Comment by Scottmitch** [comment]
looking forward to a PR @jasontedor

**Comment by normanmaurer** [comment]
+1

**Comment by jasontedor** [comment]
@Scottmitch @normanmaurer It will be inbound later today, but it's basically going to amount to reverting the commit in this PR. I wanted to write a failing test case first to demonstrate the problem, and a test case to guard against future changes which I have up in a [gist](https://gist.github.com/jasontedor/7716d29c6bcc75df78b86341961dc6ca/665a2f07dc5d80b93e17d41a142d1c2b426d5541). I'll formalize this soon.

**Comment by normanmaurer** [comment]
@zhangkun83 @buchgr @nmittler @ejona86 WDYT ?

**Comment by jasontedor** [comment]
I opened #5533.

**Comment by ejona86** [comment]
It seems worse to have the threads be mixed from a random thread groups. If you create a thread from an event loop, then you could never tell what thread group it will be part of.

> will modify properties on the created thread.

Which properties are you referring to here? If it's name, I'd imagine we should just not care and ignore changing the name if it fails. It seems daemon would be the main issue here.

> This is completely counter to the point of thread groups

I don't think I understand this point. Would it make sense if they created their threads eagerly when created? I've already noticed that shutdown() creates any un-created threads anyway (just to then shut them down).

**Comment by jasontedor** [comment]
> It seems worse to have the threads be mixed from a random thread groups. If you create a thread from an event loop, then you could never predict what thread group it will be part of.

This is a problem brought on by global singletons like `GlobalEventExecutor`.

> Which properties are you referring to here? If it's name, I'd imagine we should just not care and ignore changing the name if it fails. It seems daemon would be the main issue here.

Setting daemon and priority, these both require permissions, and implicitly the uncaught exception handler will be inherited.

> Would it make sense if they created their threads eagerly when created?

I'm not sure if this makes sense in the context of, for example, `GlobalEventExecutor` or `ThreadDeathWatcher` which fire up a thread as needed.

**Comment by ejona86** [comment]
So maybe we allow a `null` ThreadGroup, which would mean to use the current ThreadGroup, and then the singletons would pass `null`? It seems that most event loops should use a consistent ThreadGroup, but yes, it seems that we need to do something weird for the singletons. Maybe it is also necessary to add `setThreadFactory()` methods to the two singletons.

**Comment by normanmaurer** [comment]
Sounds ok to me... Not sure we need the setters though

**Comment by jasontedor** [comment]
> So maybe we allow a `null` ThreadGroup, which would mean to use the current Thread's ThreadGroup, and then the singletons would pass `null`?

This is roughly the approach that I took in #5533. The difference is I just make the constructors on `DefaultThreadGroup` that do not take a `ThreadGroup` pass `null` leading to the desired behavior for the singletons.

**Comment by ejona86** [comment]
I don't care too much about the setters at the moment. But it would seem likely to be necessary eventually. Any time multiple ThreadGroups are actually in use "weird things" can happen if you don't use a consistent ThreadGroup from an event loop.

I'd want the default for DefaultThreadFactory to be a consistent and predictable ThreadGroup. Executors/ThreadPoolExecutor makes sure to use a consistent and predictable ThreadGroup decided at construction, only differing by trying System.getSecurityManager().getThreadGroup() first. Maybe that tweak is all that's necessary to fix the SecurityManager woes and there's no need to use the current Thread's ThreadGroup during newThread().

http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/util/concurrent/Executors.java#596
http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/util/concurrent/ThreadPoolExecutor.java#1195

**Comment by jasontedor** [comment]
> Executors/ThreadPoolExecutor makes sure to use a consistent and predictable ThreadGroup decided at construction only differing by trying System.getSecurityManager().getThreadGroup() first.

We take the same approach in [Elasticsearch](https://github.com/elastic/elasticsearch/blob/1bc12f52140d2e89d971b81b6d07c86192e655a1/core/src/main/java/org/elasticsearch/common/util/concurrent/EsExecutors.java#L118-L120). However, as this leads to a fixed thread group, the problem here is still the singletons like `GlobalEventExecutor`.

**Comment by normanmaurer** [comment]
@jasontedor wouldn't it be "good enough" for the singletons to just pass "null" in ?

**Comment by jasontedor** [comment]
> wouldn't it be "good enough" for the singletons to just pass "null" in ?

@normanmaurer It's fine, but I suppose the problem I see there is that it requires changing a bunch of call sites to use the four-args constructor that takes a thread group, or adding even more convenience constructors to a class that already has a lot of constructors. I'm happy to evolve #5533 as needed.

**Comment by normanmaurer** [comment]
@jasontedor I think I would be fine to change the call sites. No need to add even more constructors. There should be not too many singletons that need the factory.

**Comment by jasontedor** [comment]
> I think I would be fine to change the call sites. No need to add even more constructors. There should be not too many singletons that need the factory.

@normanmaurer Sounds good, I pushed a commit to #5533 to reflect this.
