### ISSUE TITLE
Prepend `(experimental)` to the package summary of experimental modules

### ISSUE THREAD

**Issue by trustin** [netty/netty#5088]
.. so we can pull the cool stuff in early (HTTP/2, SMTP and Redis) and give some room for polishing the API (Memcache)

Let's prepend `(experimental)` to the package summary. e.g:

    (experimental)  Handlers for sending and receiving HTTP/2 frames.

The list of experimental modules I can think of right now:

- codec-dns
- codec-http2
- codec-memcache
- codec-redis
- codec-smtp
- resolver-dns

Please let me know what else should be marked as experimental.

Also, is 'experimental' a good term here? What else could be used?

- early access
- beta

**Comment by normanmaurer** [comment]
Sounds good... Maybe beta would be better :)

**Comment by trustin** [comment]
Let me do a spin-off doclet project meanwhile. :-)

**Comment by buchgr** [comment]
In gRPC we are using the `ExperimentalApi` annotation for that. Might be easier to spot for developers? Or maybe have the whole packages under `io.netty.experimental.`?

I am not sure if people read the package description, especially when pulling in `netty-all`?

https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/ExperimentalApi.java

**Comment by trustin** [comment]
I'll write a Javadoc doclet that manipulates the generated Javadoc so every type description has a warning. :-)

**Comment by buchgr** [comment]
@trustin good idea! Does that transform the source code javadoc or only the generated HTML?

**Comment by trustin** [comment]
@buchgr Only the generated HTML. Like what I did with APIviz doclet.

**Comment by trustin** [comment]
My mind is fighting against itself between doing it right and just getting this s**t done. Don't expect this to be done any time soon, folks. :-)

**Comment by buchgr** [comment]
@trustin hmm :) But when using an annotation it will be in source code and generated HTML e.g. http://www.grpc.io/grpc-java/javadoc/io/grpc/Compressor.html ... no?

**Comment by normanmaurer** [comment]
@trustin I think what @buchgr suggests makes a lot of sense :)

**Comment by trustin** [comment]
Yeah, it's just boring to annotate all public classes. :-)

**Comment by trustin** [comment]
So.. I guess the discussion is over and we can move on to adding annotations.

**Comment by normanmaurer** [comment]
@trustin I agree but I guess only doing it on the package may be not good enough as people may miss it.

**Comment by trustin** [comment]
I thought it's about doing it on all public classes on experimental modules?

**Comment by normanmaurer** [comment]
not sure this is needed or not... maybe doing it on the package-info.java would be good enough ? @buchgr @Scottmitch @trustin WDYT ?

**Comment by buchgr** [comment]
I was thinking about adding the annotation to all public classes and adding some text (like @trustin suggested) to the `package-info.java`. I am suggesting this cause I personally don't recall ever looking at `package-info.java` and hardly ever at the HTML javadoc. I mostly just add a dependency to my build system, and start using it / reading docs in the source. Maybe that's just me, 'cause I am a lousy dev :-).

Additionally, I would explicitly mention the experimental packages in the release notes. Yes annoting classes is boring :). The upside is that (I am not sure if this is required),  by using an annotation you get the flexibility of gradually marking a subset of a module as stable.

Obviously it's your call and you guys are MUCH more experienced with this than me... just my thinking :-).

**Comment by normanmaurer** [comment]
@buchgr you are volunteer for a PR ;) ?

**Comment by buchgr** [comment]
@normanmaurer good try :stuck_out_tongue_winking_eye:

**Comment by Scottmitch** [comment]
maybe start out with a high level "this module is experimental" notice in release notes and comment on package-info ... and at the discretion of each module they can either just rip the band-aid off and make the entire module non-experimental at once ... or put annotations at the individual class level if necessary. Maintaining the annotations on all of these public classes from the start seems like it will be a PITA.

**Comment by normanmaurer** [comment]
@buchgr damn it 😆

**Comment by normanmaurer** [comment]
@trustin @buchgr @Scottmitch  I will take care

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5145
