### ISSUE TITLE
Some MsgEchoServer's problem

### ISSUE THREAD

**Issue by hellocrest** [netty/netty#5091]
hi,
  I'm a netty beginner,and when I git clone source code and run some examples,I found some problem in the next classes.
`io.netty.example.udt.echo.message.MsgEchoClient <br/>io.netty.example.udt.echo.message.MsgEchoServer`
  When I run the server and then run client,it'll always print some message like this "13:35:32.524 [connect-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x3846a69c, L:/127.0.0.1:8007 - R:/127.0.0.1:51116] FLUSH",both client and server.But when I run the client and server in debug mode,and set the breakpoint on LoggingHandler.flush(ChannelHandlerContext ctx),the problem is gone,I cann't find the reason,some one can help me ?

the code version:4.1.0.Final-SNAPSHOT

**Comment by Scottmitch** [comment]
@hellocrest - Can you pull the latest code, rebuild, run from the command line, and paste what you see? The client will send a message to the server, the server will echo it back, and then the client will also echo back what it reads ... so its basically an endless loop of sending back and forth (not just a single message). So if you look something like wireshark or tcpdump on local host you should see tons of packets going back and forth.

Server:
```bash
./run-example.sh echo-server
[INFO] Running: echo-server (io.netty.example.echo.EchoServer -D_)
[jetty-alpn-agent] Using: alpn-boot-8.1.7.v20160121.jar
11:31:58.689 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xfcf046a9] REGISTERED
11:31:58.692 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xfcf046a9] BIND: 0.0.0.0/0.0.0.0:8007
11:31:58.693 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xfcf046a9, L:/0:0:0:0:0:0:0:0:8007] ACTIVE
11:32:04.297 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xfcf046a9, L:/0:0:0:0:0:0:0:0:8007] RECEIVED: [id: 0x2418c50b, L:/127.0.0.1:8007 - R:/127.0.0.1:40794]
```

Client:
```bash
./run-example.sh echo-client
[INFO] Running: echo-client (io.netty.example.echo.EchoClient -D_)
[jetty-alpn-agent] Using: alpn-boot-8.1.7.v20160121.jar
```

**Comment by hellocrest** [comment]
@Scottmitch  thank you,I'll try.And paste the log later.

**Comment by hellocrest** [comment]
I've read the code,and I think I've known the reason,thank you. @Scottmitch
