### ISSUE TITLE
how Understanding Cause of NullPointerException in Java NIO Socket Channel

### ISSUE THREAD

**Issue by plx927** [netty/netty#5092]
Can anyone explain why this is happening? My code is below. Before the thread containing the run method is created I ensure the key.isAcceptable() is true.
`ExecutorService pool = Executors.newFixedPool(5);`
`pool.execute(new Runnable(){ ServerSocketChannel ssc = (ServerSocketChannel) key.channel(); sc = ssc.accept();})`
**why ssc.accepet is null?**

**Comment by normanmaurer** [comment]
@plx927 this is the issue tracker for netty and not a java user group.
