### ISSUE TITLE
ByteToMessageDecoder uses a heap buffer forcefully on handlerRemoved

### ISSUE THREAD

**Issue by Janmm14** [netty/netty#5093]
The [```ByteToMessageDecoder```](https://github.com/netty/netty/blob/4.0/codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java#L215) uses [```ByteBuf.readBytes(int)```](https://github.com/netty/netty/blob/4.0/buffer/src/main/java/io/netty/buffer/AbstractByteBuf.java#L670-L682), which is using a heap buffer forcefully without being able to change it.

I suggest the buffer should be allocated with ```ctx.alloc().buffer(readable)``` before we call ```readBytes(...)``` (so the user can define whether the buffer should be on heap or not).

This seems to be present in all current netty versions. This bug is originally from SpigotMC/BungeeCord#1717, where it could not properly slice a buffer. The quick fix was to copy the buffer instead. Reference to the quickfix commit: https://github.com/SpigotMC/BungeeCord/commit/8490d611bf21ee9436e7575157f7f6d13cf5e30f ([investigation by me](https://github.com/SpigotMC/BungeeCord/commit/8490d611bf21ee9436e7575157f7f6d13cf5e30f#commitcomment-16946545))

**Comment by normanmaurer** [comment]
@Janmm14 let me check and fix it :) Thanks for the report.

**Comment by Janmm14** [comment]
Probably one even does not have to copy the buffer and its the handler removed method when the handler is not going to be used again.
Btw. its not known whether this is the bug which caused SpigotMC/BungeeCord#1717.

**Comment by normanmaurer** [comment]
@Janmm14 its needs to be copied as other handlers in the pipeline may want to handle the remaining bytes.

**Comment by Janmm14** [comment]
@normanmaurer Yes, but if you have it like this:
```
if (readable > 0) {
    ctx.fireChannelRead(buf);
}
```
it seems to work and the ```buf``` is also released (only tested in bungeecord).

**Comment by normanmaurer** [comment]
Yes this may work most of the times but we never really know what the internal buffer is so its safer to copy it. For example we never want the ReplayingBuffer to escape the handler.

So better do a copy here, which is not a big deal as it only happens one time (when the handler is removed)

**Comment by Janmm14** [comment]
I'm sorry for all these commit references.

**Comment by normanmaurer** [comment]
Fixed
