### ISSUE TITLE
SNIHandler should allow using SSLContext (instead of SslContext)

### ISSUE THREAD

**Issue by slaskawi** [netty/netty#5095]
Hi!

In Infinispan we would need to support SNI for Hotrod server. However this issue is not as easy as it would seem...

Because our server has been built on the top of Wildfly, [the only thing we can get from it, is initialized SSLContext](https://github.com/infinispan/infinispan/blob/ea7849ad3c07e2d3b297b2a02050fafe25ca20c6/server/integration/endpoint/src/main/java/org/infinispan/server/endpoint/subsystem/ProtocolServerService.java#L111). Turning on SNI support should also be possible with `SSLContext` and `SslHandler` (since we need to replace it after the handshake is done). 

Thanks!
Sebastian

**Comment by normanmaurer** [comment]
@slandelle it is possible if you just write your own `SniHandler`. ;) Joke aside, let me see if I can somehow make it more "extensible".

**Comment by normanmaurer** [comment]
also related to #4929

**Comment by slaskawi** [comment]
@normanmaurer ekhem ekhem I'm planning to write a temporary one :D But that's something I won't tell my kids when I'm old...

Looking forward to remove it once we upgrade to `4.1.0` :)

**Comment by normanmaurer** [comment]
@slaskawi stay tuned I may be able to get something for 4.0 as well :)

**Comment by slaskawi** [comment]
Great! Thanks!

**Comment by normanmaurer** [comment]
@slachiewicz Please check https://github.com/netty/netty/pull/5113

**Comment by normanmaurer** [comment]
You can now create a `JdkSslContext` from a pre-configured `SSLContext`. See https://github.com/netty/netty/pull/5113

**Comment by slaskawi** [comment]
@normanmaurer Perfect! Thanks a lot! I'll check it right away. Could you tell me what is the ETA for 4.0.37 (so at least I have a rough idea how this fits into our calendar).

**Comment by normanmaurer** [comment]
Within 3 weeks I would say.
