### ISSUE TITLE
Http2Exception: Cannot create stream 1 since this endpoint has received a GOAWAY frame with last stream id 0

### ISSUE THREAD

**Issue by trustin** [netty/netty#5097]
I recently got the following exception:

    io.netty.handler.codec.http2.Http2Exception: Cannot create stream 1 since this endpoint has 
    received a GOAWAY frame with last stream id 0

It doesn't seem to make sense to me because 

- the stream 1 is the upgrade stream, so there's no chance of receiving a GOAWAY frame before its creation, and
- there's no stream 0 by definition.

Any clues? /cc @Scottmitch @nmittler

**Comment by normanmaurer** [comment]
@trustin just to clarify, what vrrsion of netty ? I think we fixed something like this before

**Comment by anuraaga** [comment]
Sorry to jump in, but it was my server so I can answer that. It was Netty 4.1.0CR3 (via armeria 0.12.2). FWIW, we've used this in many API servers/clients already with no issues so were surprised to see this after adding to yet another API server.

If it's already fixed in CR5 that'd be great news :)

**Comment by normanmaurer** [comment]
Hmm i think there was no such fix after CR3 😩

**Comment by Scottmitch** [comment]
A goaway will be sent automatically when the connection is closed [here](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L418) (also if an error is detect in the pipeline this may result in the connection being closed [here](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L572)). The [lastKnownStream](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L697) is initialized to 0 [here](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2Connection.java#L898). So it makes sense from a code perspective that this can happen. The scenario is also allowed by the RFC

https://tools.ietf.org/html/rfc7540#section-6.8
>  The last stream identifier in the GOAWAY frame contains the highest-
   numbered stream identifier for which the sender of the GOAWAY frame
   might have taken some action on or might yet take action on.  All
   streams up to and including the identified stream might have been
   processed in some way.  The last stream identifier can be set to 0 if
   no streams were processed.

**Comment by Scottmitch** [comment]
@trustin @anuraaga - Can you verify that a GOAWAY is being received, and identify the root cause as to why it is being sent (channel closed, channel error, etc...)?

**Comment by anuraaga** [comment]
Any tips on what to look for? I'll dig around but not sure if I'll come up with anything as it's difficult to repro. On the client we were seeing session establishment timeouts, which seem like the server never responded, and response timeouts, which seem like the server did connect but then never got back to it. There were no response timeouts on the server though, just that goaway exception.

For a bit more detail on the symptoms, we restarted a server to freshly point at an armeria/Netty port (used to point at nginx/tomcat with http1). For the first three hours, there was just one or so instance of the exception, then all of a sudden all requests started throwing and we had to rollback the client to point at tomcat again.

I'll see if an extended stream of high traffic against a test server can repro but not sure it will.

**Comment by Scottmitch** [comment]
@anuraaga - Can you clarify where the exception reported in this issue was observed (on the client or the server)?

> Any tips on what to look for?

Any GOAWAY frames being sent/received with [Last-Stream-ID](https://tools.ietf.org/html/rfc7540#section-6.8) of `0`. If so what is the `Error Code` and is there any content in the `Additional Debug Data`?  I'm not sure what tools access you have at your disposal however here are some options:
- if you can setup a packet sniffer (wireshark) and observe the packet exchange when this occurs
- add a log statement into [DefaultHttp2FrameWriter.writeGoAway](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameWriter.java#L343) that can dump the stack trace in this situation
- Set a [frameLogger](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/AbstractHttp2ConnectionHandlerBuilder.java#L262) when building the Http2ConnectionHandler.

I'm not sure what is exposed in `armeria` from what I listed, or if there are other/better tools available @trustin ?

**Comment by trustin** [comment]
We currently have difficulties in reproducing the problem.

Looking from the code, the exception message occurs only when `goAwayReceived()` returns `true`. `goAwayReceived()` returns only when `goAwayReceived(lastKnownStream, errorCode, debugData)

**Comment by trustin** [comment]
What I don't understand is why sending a response triggers the attempt to create a stream 1. It should exist already, because it's created on successful upgrade.

**Comment by Scottmitch** [comment]
yes this is strange ... just a sanity check can you verify/answer the following:

1. you are actually doing an upgrade in this scenario (IIRC the HTTP/2 codec doesn't prevent you from creating/operating on a stream with ID 1 ... in general this ID is subject to the same rules as all other streams).
2. How are you managing/creating stream IDs?
3. You are using `Http2ServerUpgradeCodec` and `Http2ClientUpgradeCodec`

**Comment by trustin** [comment]
1. Yes. The exception looks like it happened when sending the response to the upgrade request.
2. We just use the same stream ID the client sent. The client starts at the stream ID 3 after successful upgrade.
3. Yes.

**Comment by trustin** [comment]
We also sometimes saw this:

```
io.netty.handler.codec.http2.Http2Exception: Request stream 11 is not correct for server connection
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:82)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.checkNewStreamAllowed(DefaultHttp2Connection.java:1110)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:967)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:985)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:895)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:154)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:143)
	at io.netty.handler.codec.http2.HttpToHttp2ConnectionHandler.write(HttpToHttp2ConnectionHandler.java:83)
```

**Comment by trustin** [comment]
It could mean that the remote stream might have been closed for an unknown reason before sending a response.

**Comment by Scottmitch** [comment]
> io.netty.handler.codec.http2.Http2Exception: Request stream 11 is not correct for server connection

Interesting. This means you try to create a `odd` stream ID on the server's Endponit (see [here](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2Connection.java#L1106)). Do you see this error on the client or server (please clarify this when posting new info)?

This goes back to my question 2 above `How are you managing/creating stream IDs`?`

You responded:

> We just use the same stream ID the client sent. The client starts at the stream ID 3 after successful upgrade.

What I meant was when you are writing data for a new stream, how do you generate this new stream ID? For example the codec http2 offers a helper method [incrementAndGetNextStreamId](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2Connection.java#L935) which can be used, but is not required (you could have your own mechanism for choosing the stream ID).

**Comment by anuraaga** [comment]
＞  Do you see this error on the client or server (

The stream related error there and in the original message are on the server. The client only sees timeouts, presumably because the server is ignoring it.

**Comment by Scottmitch** [comment]
@anuraaga - Thanks for confirming. This makes me more interested in the stream ID creation code. This means the local endpoint was used to try to create an invalid stream ID as opposed to receiving a message which lead to stream ID creation. @trustin - Can you comment?

**Comment by trustin** [comment]
Seems like the server took too long to respond to the upgrade request and the client sent GOAWAY and closed the connection before getting the upgrade response due to timeout. i.e. not a bug.

Thanks for trying to help, @Scottmitch !

**Comment by Scottmitch** [comment]
@trustin - Glad you figured it out. Can you explain if the invalid stream ID exception was related to this or caused by a different issue?

```
io.netty.handler.codec.http2.Http2Exception: Request stream 11 is not correct for server connection
```
