### ISSUE TITLE
Server doesn't receive a channelInactive() from its client

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#5099]
Netty 4.1.0.Final-SNAPSHOT

Server doesn't receive a channelInactive() from its client after it's turning off auto reading (server turns off auto reading) and the client disconnects. 

I've opened a PR #5098 with an Unit Test which demonstrates the problem.

**Comment by Scottmitch** [comment]
thanks for reporting @rkapsi !

**Comment by normanmaurer** [comment]
Closing as "not a bug". See #5098
