### ISSUE TITLE
High Cpu Usage when the sctp socket connection is hanged with the CLOSED state

### ISSUE THREAD

**Issue by ozgurunc** [netty/netty#5118]
Hi,

We are using the sctp server client future. When client or server get shutdown ack from peer or one of the sctp interface down socket state is hanged with the closed state and cpu usage increased for that threads.  

netty-all-4.0.28.Final.jar
jdk1.7.0_79
SunOS v2ap1 5.10 Generic_150401-22 i86pc i386 i86pc

10.136.53.67.3869               10.133.142.28.3868               32768      0 102400      0  17/17  CLOSED

root@v2ap1 # prstat -Lp 6756
   PID USERNAME  SIZE   RSS STATE  PRI NICE      TIME  CPU PROCESS/LWPID      
  6756 server  2532M 2311M cpu1    30    0 120:31:38  13% java/145
  6756 server  2532M 2311M run     22    0 119:49:33  13% java/143
  6756 server  2532M 2311M run     21    0 123:43:39  12% java/142
  6756 server  2532M 2311M cpu2    31    0 122:00:01  12% java/137
  6756 server  2532M 2311M run     21    0 119:51:52  12% java/144
  6756 server  2532M 2311M cpu0    22    0 119:29:35  12% java/141
  6756 server  2532M 2311M run     22    0 120:15:27  12% java/139
  6756 server  2532M 2311M run     31    0 121:42:33  11% java/140
  6756 server  2532M 2311M sleep   59    0   1:05:58 0.2% java/191
  6756 server  2532M 2311M sleep   59    0   2:16:15 0.2% java/71
  
  
  Thread t@145: (state = IN_NATIVE)
 - sun.nio.ch.SctpChannelImpl.receive0(int, sun.nio.ch.SctpResultContainer, long, int, boolean) @bci=0 (Compiled frame; information may be imprecise)
 - sun.nio.ch.SctpChannelImpl.receiveIntoNativeBuffer(int, sun.nio.ch.SctpResultContainer, java.nio.ByteBuffer, int, int, boolean) @bci=19, line=853 (Compiled frame)
 - sun.nio.ch.SctpChannelImpl.receive(int, java.nio.ByteBuffer, sun.nio.ch.SctpResultContainer, boolean) @bci=73, line=829 (Compiled frame)
 - sun.nio.ch.SctpChannelImpl.receive(java.nio.ByteBuffer, java.lang.Object, com.sun.nio.sctp.NotificationHandler, boolean) @bci=237, line=772 (Compiled frame)
 - sun.nio.ch.SctpChannelImpl.receive(java.nio.ByteBuffer, java.lang.Object, com.sun.nio.sctp.NotificationHandler) @bci=5, line=734 (Compiled frame)
 - io.netty.channel.sctp.nio.NioSctpChannel.doReadMessages(java.util.List) @bci=86, line=278 (Compiled frame)
 - io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read() @bci=88, line=69 (Compiled frame)
 - io.netty.channel.nio.NioEventLoop.processSelectedKey(java.nio.channels.SelectionKey, io.netty.channel.nio.AbstractNioChannel) @bci=42, line=511 (Compiled frame)
 - io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(java.nio.channels.SelectionKey[]) @bci=37, line=468 (Compiled frame)
 - io.netty.channel.nio.NioEventLoop.processSelectedKeys() @bci=15, line=382 (Compiled frame)
 - io.netty.channel.nio.NioEventLoop.run() @bci=84, line=354 (Compiled frame)
 - io.netty.util.concurrent.SingleThreadEventExecutor$2.run() @bci=13, line=111 (Interpreted frame)
 - io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run() @bci=4, line=137 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)
 
 
 Thread t@142: (state = IN_VM)
 - sun.misc.Unsafe.allocateMemory(long) @bci=0 (Compiled frame; information may be imprecise)
 - java.nio.DirectByteBuffer.<init>(int) @bci=49, line=127 (Compiled frame)
 - java.nio.ByteBuffer.allocateDirect(int) @bci=5, line=306 (Compiled frame)
 - io.netty.buffer.UnpooledUnsafeDirectByteBuf.allocateDirect(int) @bci=1, line=108 (Compiled frame)
 - io.netty.buffer.UnpooledUnsafeDirectByteBuf.<init>(io.netty.buffer.ByteBufAllocator, int, int) @bci=125, line=69 (Compiled frame)
 - io.netty.buffer.UnpooledByteBufAllocator.newDirectBuffer(int, int) @bci=13, line=50 (Compiled frame)
 - io.netty.buffer.AbstractByteBufAllocator.directBuffer(int, int) @bci=21, line=155 (Compiled frame)
 - io.netty.buffer.AbstractByteBufAllocator.directBuffer(int) @bci=4, line=146 (Compiled frame)
 - io.netty.buffer.AbstractByteBufAllocator.ioBuffer(int) @bci=8, line=107 (Compiled frame)
 - io.netty.channel.AdaptiveRecvByteBufAllocator$HandleImpl.allocate(io.netty.buffer.ByteBufAllocator) @bci=5, line=104 (Compiled frame)
 - io.netty.channel.sctp.nio.NioSctpChannel.doReadMessages(java.util.List) @bci=44, line=272 (Compiled frame)
 - io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read() @bci=88, line=69 (Compiled frame)
 - io.netty.channel.nio.NioEventLoop.processSelectedKey(java.nio.channels.SelectionKey, io.netty.channel.nio.AbstractNioChannel) @bci=42, line=511 (Compiled frame)
 - io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(java.nio.channels.SelectionKey[]) @bci=37, line=468 (Compiled frame)
 - io.netty.channel.nio.NioEventLoop.processSelectedKeys() @bci=15, line=382 (Compiled frame)
 - io.netty.channel.nio.NioEventLoop.run() @bci=84, line=354 (Compiled frame)
 - io.netty.util.concurrent.SingleThreadEventExecutor$2.run() @bci=13, line=111 (Interpreted frame)
 - io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run() @bci=4, line=137 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)
 
 Thread t@137: (state = IN_VM)
 - sun.misc.Unsafe.allocateMemory(long) @bci=0 (Compiled frame; information may be imprecise)
 - java.nio.DirectByteBuffer.<init>(int) @bci=49, line=127 (Compiled frame)
 - java.nio.ByteBuffer.allocateDirect(int) @bci=5, line=306 (Compiled frame)
 - io.netty.buffer.UnpooledUnsafeDirectByteBuf.allocateDirect(int) @bci=1, line=108 (Compiled frame)
 - io.netty.buffer.UnpooledUnsafeDirectByteBuf.<init>(io.netty.buffer.ByteBufAllocator, int, int) @bci=125, line=69 (Compiled frame)
 - io.netty.buffer.UnpooledByteBufAllocator.newDirectBuffer(int, int) @bci=13, line=50 (Compiled frame)
 - io.netty.buffer.AbstractByteBufAllocator.directBuffer(int, int) @bci=21, line=155 (Compiled frame)
 - io.netty.buffer.UnpooledUnsafeDirectByteBuf.copy(int, int) @bci=15, line=466 (Compiled frame)
 - io.netty.buffer.AbstractByteBuf.copy() @bci=9, line=919 (Compiled frame)
 - com.oksijen.smlc.sctp.SctpServerHandler.channelRead(io.netty.channel.ChannelHandlerContext, java.lang.Object) @bci=25, line=37 (Compiled frame)
 - io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(java.lang.Object) @bci=9, line=308 (Compiled frame)
 - io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(java.lang.Object) @bci=35, line=294 (Compiled frame)
 - io.netty.channel.DefaultChannelPipeline.fireChannelRead(java.lang.Object) @bci=5, line=846 (Compiled frame)
 - io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read() @bci=193, line=93 (Compiled frame)
 - io.netty.channel.nio.NioEventLoop.processSelectedKey(java.nio.channels.SelectionKey, io.netty.channel.nio.AbstractNioChannel) @bci=42, line=511 (Compiled frame)
 - io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(java.nio.channels.SelectionKey[]) @bci=37, line=468 (Compiled frame)
 - io.netty.channel.nio.NioEventLoop.processSelectedKeys() @bci=15, line=382 (Compiled frame)
 - io.netty.channel.nio.NioEventLoop.run() @bci=84, line=354 (Compiled frame)
 - io.netty.util.concurrent.SingleThreadEventExecutor$2.run() @bci=13, line=111 (Interpreted frame)
 - io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run() @bci=4, line=137 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)
 
 

10.137.53.67.3869               10.133.143.60.3868               32768      0 102400      0  17/17  CLOSED
10.136.53.67.3869               10.133.142.60.3868               32768      0 102400      0  17/17  ESTABLISHED
10.136.53.67.3869               10.133.142.252.3868              32768      0 102400      0  17/17  CLOSED
10.137.53.67.3869               10.133.143.156.3868              32768      0 102400      0  17/17  CLOSED
10.136.53.67.3869               10.133.142.28.3868               32768      0 102400      0  17/17  CLOSED
10.136.53.67.3869               10.133.142.156.3868              32768      0 102400      0  17/17  CLOSED
10.136.53.67.3869               10.133.142.220.3868              32768      0 102400      0  17/17  CLOSED
10.136.53.67.3869               10.133.142.124.3868              32768      0 102400      0  17/17  CLOSED
10.137.53.67.3869               10.133.143.28.3868               32768      0 102400      0  17/17  CLOSED
10.136.53.67.3869               10.133.142.188.3868              32768      0 102400      0  17/17  CLOSED
10.136.53.67.3869               10.133.142.28.3868               32768      0 102400      0  17/17  CLOSED
10.137.53.67.3869               10.133.143.28.3868               32768      0 102400      0  17/17  ESTABLISHED
10.136.53.67.3869               10.133.142.28.3868               32768      0 102400      0  17/17  ESTABLISHED
10.136.53.67.3869               10.133.142.188.3868              32768      0 102400      0  17/17  ESTABLISHED
10.136.53.67.3869               10.133.142.220.3868              32768      0 102400      0  17/17  ESTABLISHED
10.136.53.67.3869               10.133.142.156.3868              32768      0 102400      0  17/17  CLOSED
10.136.53.67.3869               10.133.142.252.3868              32768      0 102400      0  17/17  ESTABLISHED
10.136.53.67.3869               10.133.142.156.3868              32768      0 102400      0  17/17  ESTABLISHED
10.137.53.67.3869               10.133.143.60.3868               32768      0 102400      0  17/17  ESTABLISHED
10.136.53.67.3869               10.133.142.124.3868              32768      0 102400      0  17/17  ESTABLISHED
10.137.53.67.3869               10.133.143.156.3868              32768      0 102400      0  17/17  ESTABLISHED

**Comment by Scottmitch** [comment]
@ozgurunc - Can you provide a reproducer for this issue?

**Comment by ozgurunc** [comment]
Thanks for the reply. Yes i can. if sctp interface down then sctp socket connection state change with the close and that thread cpu usage increased when interafe up again accepted new connection and established. Closed state hanged and cpu usage alloocated by that thread.

**Comment by normanmaurer** [comment]
@ozgurunc a unit test or so would be super nice :)

**Comment by ozgurunc** [comment]
Before the Sctp Interface Up and running 
# netstat -an | grep 3869
      *.3869                    0.0.0.0                          32768      0 102400      0  32/32  LISTEN
10.136.25.36.3869               10.133.142.93.3868               32768      0 102400      0  17/17  ESTABLISHED

root@vsmlcat1 # prstat                 
   PID USERNAME  SIZE   RSS STATE  PRI NICE      TIME  CPU PROCESS/NLWP       
     4878 server 2510M  579M sleep   59    0   0:03:39 0.1% java/140

After the sctp intrface down

# netstat -an | grep 3869
      *.3869                    0.0.0.0                          32768      0 102400      0  32/32  LISTEN
      *.3869                    10.133.142.93.3868               32768      0 102400      0  17/17  CLOSED

   PID USERNAME  SIZE   RSS STATE  PRI NICE      TIME  CPU PROCESS/NLWP       
  4878 server 2510M  581M cpu3    10    0   0:11:03  25% java/140

# prstat -Lp 4878
   PID USERNAME  SIZE   RSS STATE  PRI NICE      TIME  CPU PROCESS/LWPID      
  4878 server 2510M  581M cpu3     0    0   0:07:52  25% java/125
  4878 server  2510M  581M sleep   59    0   0:00:00 0.0% java/3
  4878 server  2510M  581M sleep   59    0   0:00:00 0.0% java/5

And getting thread dump for thread 125

# /usr/jdk/jdk1.7.0_79/bin/amd64/jstack -F 4878 > /tmp/jstack

Thread t@125: (state = IN_NATIVE)
 - sun.nio.ch.SctpChannelImpl.receive0(int, sun.nio.ch.SctpResultContainer, long, int, boolean) @bci=0 (Compiled
 frame; information may be imprecise)
 - sun.nio.ch.SctpChannelImpl.receiveIntoNativeBuffer(int, sun.nio.ch.SctpResultContainer, java.nio.ByteBuffer,
int, int, boolean) @bci=19, line=853 (Compiled frame)
 - sun.nio.ch.SctpChannelImpl.receive(int, java.nio.ByteBuffer, sun.nio.ch.SctpResultContainer, boolean) @bci=73
, line=829 (Compiled frame)
 - sun.nio.ch.SctpChannelImpl.receive(java.nio.ByteBuffer, java.lang.Object, com.sun.nio.sctp.NotificationHandle
r, boolean) @bci=237, line=772 (Compiled frame)
 - sun.nio.ch.SctpChannelImpl.receive(java.nio.ByteBuffer, java.lang.Object, com.sun.nio.sctp.NotificationHandle
r) @bci=5, line=734 (Compiled frame)
 - io.netty.channel.sctp.nio.NioSctpChannel.doReadMessages(java.util.List) @bci=67, line=274 (Compiled frame)
 - io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read() @bci=104, line=73 (Compiled frame)
 - io.netty.channel.nio.NioEventLoop.processSelectedKey(java.nio.channels.SelectionKey, io.netty.channel.nio.Abs
tractNioChannel) @bci=42, line=527 (Compiled frame)
 - io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(java.nio.channels.SelectionKey[]) @bci=37, lin
e=484 (Compiled frame)
 - io.netty.channel.nio.NioEventLoop.processSelectedKeys() @bci=15, line=398 (Compiled frame)
 - io.netty.channel.nio.NioEventLoop.run() @bci=115, line=370 (Compiled frame)
 - io.netty.util.concurrent.SingleThreadEventExecutor$5.run() @bci=44, line=742 (Interpreted frame)
 - io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run() @bci=4, line=137 (Interpreted fr
ame)
 - java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)

**Comment by ozgurunc** [comment]
I can laso provide dtrace out puts. it can be related with solaris arch?
/dstack 
dtrace: script '/dstack' matched 473 probes
CPU     ID                    FUNCTION:NAME
  3  63931                         :tick-5s 
  gtime                                                             0
  yield                                                             0
  nanosleep                                                         0
  getpmsg                                                           0
  so_socket                                                         0
  fcntl                                                             0
  close                                                             0
  lwp_cond_wait                                                     1
  lwp_cond_signal                                                   1
  open                                                              1
  send                                                              2
  read                                                              3
  sendmsg                                                           3
  putpmsg                                                           4
  lwp_park                                                          8
  pollsys                                                          12
  write                                                            12
  ioctl                                                           820
  recvmsg                                                        1190
  TOTAL:                                                         2069


 # dtrace -n 'syscall::ioctl: { @[execname] = count();}' -n tick-5sec'{trunc(@,20); printa(@); trunc(@); exit(0);}'
dtrace: description 'syscall::ioctl: ' matched 2 probes
dtrace: description 'tick-5sec' matched 1 probe
CPU     ID                    FUNCTION:NAME
  1  63932                       :tick-5sec 
  _python_executab                                                  4
  stat_daemon                                                       4
  spmd                                                              6
  dad                                                              20
  dsmd                                                             20
  nfs_stat                                                         20
  kuxagent                                                         38
  dtgreet                                                          40
  adclient                                                         48
  mount_stat                                                       66
  apmd                                                             72
  netd                                                             84
  aspd                                                           1168
  dtrace                                                         2625
  java                                                        2055825


 # dtrace -n 'syscall::ioctl: / execname == "java"  /{ @[ustack()] = count();}' -n tick-5sec'{trunc(@,5); printa(@); trunc(@); exit(0);}'
dtrace: description 'syscall::ioctl: ' matched 2 probes
dtrace: description 'tick-5sec' matched 1 probe
CPU     ID                    FUNCTION:NAME
  1  63932                       :tick-5sec 

              libc.so.1`ioctl+0xa
              0xfffffd7ffa7553a2
              0xfffffd7ffa7557d0
          1872930

**Comment by Scottmitch** [comment]
@ozgurunc - A reproducer in the form of a unit test will help us narrow in on the issue.

**Comment by ozgurunc** [comment]
I think this issue is related with the Solaris platforms. When i perform that on linux client and server get back internal error and cpu usage not increase. Most probably Solaris case run into this case because of the hanging of Closed state. I will try to get support from solaris for that.

B.R 

10.137.53.67.3869 10.133.143.60.3868 32768 0 102400 0 17/17 CLOSED


$ ./jdk1.7.0_79/bin/java -jar /home/mttadm/SctpMultiHomingEchoServer.jar 
Apr 12, 2016 3:07:28 PM io.netty.handler.logging.LoggingHandler channelRegistered
INFO: [id: 0x86db838e] REGISTERED
Apr 12, 2016 3:07:28 PM io.netty.handler.logging.LoggingHandler bind
INFO: [id: 0x86db838e] BIND(/10.136.25.61:8007)
Apr 12, 2016 3:07:28 PM io.netty.handler.logging.LoggingHandler channelActive
INFO: [id: 0x86db838e, L:/10.136.25.61:8007] ACTIVE
Apr 12, 2016 3:09:12 PM io.netty.handler.logging.LoggingHandler logMessage
INFO: [id: 0x86db838e, L:/10.136.25.61:8007] RECEIVED: [id: 0x2b94a1bf, L:/10.136.25.61:8007 - R:/10.136.25.62:8008]


Server Side
java.lang.InternalError: should not reach here
        at sun.nio.ch.SctpChannelImpl.receive0(Native Method)
        at sun.nio.ch.SctpChannelImpl.receiveIntoNativeBuffer(SctpChannelImpl.java:853)
        at sun.nio.ch.SctpChannelImpl.receive(SctpChannelImpl.java:829)
        at sun.nio.ch.SctpChannelImpl.receive(SctpChannelImpl.java:772)
        at sun.nio.ch.SctpChannelImpl.receive(SctpChannelImpl.java:734)
        at io.netty.channel.sctp.nio.NioSctpChannel.doReadMessages(NioSctpChannel.java:279)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:69)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)


Client Side


$ ./jdk1.7.0_79/bin/java -jar SctpMultiHomingEchoClient.jar
java.lang.InternalError: should not reach here
        at sun.nio.ch.SctpChannelImpl.receive0(Native Method)
        at sun.nio.ch.SctpChannelImpl.receiveIntoNativeBuffer(SctpChannelImpl.java:853)
        at sun.nio.ch.SctpChannelImpl.receive(SctpChannelImpl.java:829)
        at sun.nio.ch.SctpChannelImpl.receive(SctpChannelImpl.java:772)
        at sun.nio.ch.SctpChannelImpl.receive(SctpChannelImpl.java:734)
        at io.netty.channel.sctp.nio.NioSctpChannel.doReadMessages(NioSctpChannel.java:279)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:69)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)

**Comment by Scottmitch** [comment]
@ozgurunc - Thanks for the info. I will close this now, if you find it is attributed to Netty please re-open.
