### ISSUE TITLE
Why don't update `streamableBytes` when `pendingBytes` is changed?

### ISSUE THREAD

**Issue by louxiu** [netty/netty#5124]
Hi all, I just looked https://github.com/netty/netty/commit/96f9b0b91ba63c1f6232c6acca4358afe01fbb7f and I don't understand this line. 
> decrementPendingBytes(writtenBytes, false);

Why don't update `streamableBytes` when `pendingBytes` is changed?

Please help. Thanks

**Comment by normanmaurer** [comment]
@Scottmitch @nmittler PTAL

**Comment by nmittler** [comment]
I don't recall why it's separate ... I suspect that it could be combined.  If you feel like changing it, throw together a PR :)

**Comment by Scottmitch** [comment]
To clarify ... the call to `decrementFlowControlWindow` directly after the line you mentioned currently takes care of updating the `streamableBytes`, and we don't do it on the line you mentioned to avoid doing it twice.

**Comment by louxiu** [comment]
Oh, I see. Thanks
