### ISSUE TITLE
Missing OSGi header Bundle-NativeCode in netty-tcnative

### ISSUE THREAD

**Issue by fsiegrist** [netty/netty#5150]
The MANIFEST.MF of netty-tcnative-1.1.33.Fork15-[os-classifier].jar does not contain the `Bundle-NativeCode` header. Thus when running in an OSGi context (e.g. apache-felix), the bundle does not know the path to its native library (META-INF/native/...). As a result, the `NativeLibraryLoader` (in netty-common) cannot load the native library, because the call to `loader.getResource("META-INF/native/lib" + name + ".jnilib")` returns null.

After having manually added the following entry to the MANIFEST.MF (of the osx specific version of the netty-tcnative jar), the resource can be found:
`Bundle-NativeCode: META-INF/native/libnetty-tcnative.jnilib;osname=macosx; processor=x86; processor=x86_64`

**Comment by Scottmitch** [comment]
@fsiegrist - sounds like a packaging issue in tcnative. issue moved to https://github.com/netty/netty-tcnative/issues/135.
