### ISSUE TITLE
DefaultChannelGroup has Executor, but relies on EventExecutor when closing channels

### ISSUE THREAD

**Issue by ifesdjeen** [netty/netty#5151]
Hi, 
 
`DefaultChannelGroup` has it's own `Executor`, although, when `Channel` is closed in `DefaultChannelGroup::close`, it relies on `EventExecutor` from the `Channel` itself. 

I understand that it might be very well by design (since `Channel` already has it's own executor), just wanted to point it out (after finding a couple of issues that are related to closing the worker in parallel or out of order with channel group) that several people have stumbled on that :)

Do you think it'd be useful to shutdown `Channel` from the `Executor` that is owned by `DefaultChannelGroup` to make it a bit more obvious? I realise it's impossible to work around every case where user is not attentive enough tho.

Thank you.

**Comment by normanmaurer** [comment]
@ifesdjeen the `EventExecutor` is only used to notify the `ChannelGroupFuture`. I will do a javadoc update to clarify it.

**Comment by ifesdjeen** [comment]
Yup, I know. It's just a bit counter-intuitive. I should've said that documenting it could be a better idea.

**Comment by normanmaurer** [comment]
@ifesdjeen actually it is already in the javadocs:

`Creates a new group with a generated name and the provided {@link EventExecutor} to notify the {@link ChannelGroupFuture}s.`

**Comment by ifesdjeen** [comment]
Oh... somehow I have missed that. Sorry and thanks!
