### ISSUE TITLE
Throughput is low even with batching

### ISSUE THREAD

**Issue by maseev** [netty/netty#5152]
Hi, guys.

I created a simple client-server [app](https://github.com/maseev/clientserver) that sole purpose is to transfer 200 bytes messages as fast as possible between the client and the server.

During the tests, it turned out that the throughput isn't that high as I expected (about 20-30 Mb/sec on read/write), even though I call ```flush``` method on every 100th message:

![selection_001](https://cloud.githubusercontent.com/assets/3434800/14573847/63c80114-0379-11e6-9ba5-57f52e0ca8a1.png)

The [server](https://github.com/maseev/clientserver/blob/master/src/main/java/io/github/maseev/server/nio/Server.java) logic is pretty straightforward and doesn't do a lot (just batching messages and flush them when the counter hits the batch threshold).

I didn't see much difference by changing ```WRITE_BUFFER_HIGH_WATER_MARK``` and ``WRITE_BUFFER_LOW_WATER_MARK``` values either.
I could implement batching on the client side (that would definitely improve the overall throughput dramatically), but the thing is I can't really do this because the real client will be a third-party closed-source application.

According to this [ticket](https://github.com/netty/netty/issues/1759), I'm not the only one who's trying to implement a smart batching algorithm.
Am I missing something? Maybe there's some general approach how you can increase throughput in a Netty application which is supposed to transfer a gigantic amount of small messages (less than 300 bytes each)?

I couldn't find any answers in the Netty in Action book, as well as on StackOverflow. Netty's documentation (user guide, to be precise, which by the way only describes basic topics without going into details) doesn't say much about this particular use case.

**Comment by johnou** [comment]
Try context.write(msg, context.voidPromise());

**Comment by maseev** [comment]
@johnou, no luck. Throughput is still very low. The funny this is, I've got another application which is using Java NIO directly and does the same thing - reads data from the client, batches it and then sends it back to the client. For some reasons, it performs much better:

![screen](https://cloud.githubusercontent.com/assets/3434800/14579316/37c5a98e-03c6-11e6-8302-f44d2a3c4b13.png)

**Comment by ninja-** [comment]
@maseev I can give you some quick tips from my experience in similiar kind of netty apps...
1. use epoll (for example, there's a cool feature that writes all pending buffers in one syscall instead of N write(...) calls)
2. try not touching these if there's no clear improvement  

        .childOption(ChannelOption.WRITE_BUFFER_HIGH_WATER_MARK, HIGH_WATERMARK)
        .childOption(ChannelOption.WRITE_BUFFER_LOW_WATER_MARK, LOW_WATERMARK)
        .childOption(ChannelOption.SO_RCVBUF, RECEIVE_BUFFER)
        .childOption(ChannelOption.SO_SNDBUF, SEND_BUFFER)
3. 

```
                    if (ctx.channel().isWritable()) {
                      ctx.flush();
                    }
```

for me it seems like it should be flush() if !isWritable() so the other way around...but I am not sure if you even hit that case with your testing data

**Comment by maseev** [comment]
@ninja-, to be honest, I haven't noticed any significant improvements related to throughput.

**Comment by ninja-** [comment]
It doesn't look like you have proper batching because I don't see any message splitter. It's batching them randomly whenever piece of tcp data appears

**Comment by maseev** [comment]
Here's a message [splitter](https://github.com/maseev/clientserver/blob/master/src/main/java/io/github/maseev/server/nio/Server.java#L55). And here's message [batching](https://github.com/maseev/clientserver/blob/master/src/main/java/io/github/maseev/server/nio/Server.java#L79). If I remember correctly, ```ctx.write()``` doesn't send data to the wire right away. You have to call ```ctx.flush()``` in order to trigger that behaviour. So, I think everything is fine. Data stream is split into messages with ```FixedLengthFrameDecorder```. After that, separated messages goes to a custom ```ChannelInboundHandlerAdapter``` where's the batching magic is going on.

**Comment by Scottmitch** [comment]
@maseev - Hey thanks for reaching out. I don't really have time to dig in right now however the flushing strategy in the [Server](https://github.com/maseev/clientserver/blob/master/src/main/java/io/github/maseev/server/nio/Server.java) does seem like it could use some investigation. A few observations:

It looks like you are doing all your writes in the event loop. Typically a "reasonable" flushing strategy to start with for this use case is to flush in `channelReadComplete(ChannelHandlerContext ctx)`. The current strategy of flushing based upon how many messages you receive means when you actually write will be dependent on your peer's ability to send, those packets traversing the network, your OS notifying your application, and your application getting cycles for that particular channel (and other factors too). Try this approach and also tweaking the channel's [RecvByteBufAllocator](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/ChannelConfig.java#L178) to determine how much is read for each event loop wakeup for the channel.

**Comment by maseev** [comment]
@Scottmitch - I played with RecvByteBufAllocator a little bit. Used the [adaptive](https://github.com/netty/netty/blob/83c349ffa94d3992c4ee511d3625afc0c97c12bb/transport/src/main/java/io/netty/channel/AdaptiveRecvByteBufAllocator.java) one with the following parameters:

```
.childOption(ChannelOption.RCVBUF_ALLOCATOR, new AdaptiveRecvByteBufAllocator(200, 128 * 1024, 512 * 1024))
```

Also, I removed all batching logic and now I simply call ```ctx.flush()``` in ```channelReadComplete``` method. It doesn't seem to be performing any better. I still see that 20-30 Mb sec on read/write. 

My network activity diagram with all these spikes looks like the city buildings. Is there anything else I can do about this issue? It seems that Netty makes its own mind about how and when do the reading, flushing and stuff like that.

**Comment by Scottmitch** [comment]
What type of behavior do you see when you run your client against the [EchoServer](https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/echo)?

> I played with RecvByteBufAllocator a little bit

@maseev - What are you using for [maxMessagesPerRead](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/DefaultMaxMessagesRecvByteBufAllocator.java#L42)? Typically this is set to 16 for most channel types.

Can you post a link to your updated code, and describe how much concurrency in terms of number of clients requesting data your use case involves?  In your original server link you only have [1 worker thread](https://github.com/maseev/clientserver/blob/master/src/main/java/io/github/maseev/server/nio/Server.java#L25) ... a single thread to handle all events could limit the amount of concurrent work you are able to do.

> It seems that Netty makes its own mind about how and when to read, flush etc.

Generally we try to provide "reasonable defaults" and provide hooks to tweak things to fit your use case. If there are extension points you think make sense we can discuss those.

**Comment by maseev** [comment]
> What type of behavior do you see when you run your client against the EchoServer?

In terms of throughput - it's pretty much the same as my server application:

![selection_001](https://cloud.githubusercontent.com/assets/3434800/14687268/6e91f18e-075e-11e6-8ce2-38f2ccdd04bd.png)

> @maseev - What are you using for maxMessagesPerRead? Typically this is set to 16 for most channel types.

Well, I set 100 for this property. It didn't make any significant impact in terms of throughput.

> Can you post a link to your updated code, and describe how much concurrency in terms of number of clients requesting data your use case involves? In your original server link you only have 1 worker thread ... a single thread to handle all events could limit the amount of concurrent work you are able to do.

[Here](https://github.com/maseev/clientserver) you are. In this particular use case, I'm trying to achieve the maximum throughput with one active client. If I remember correctly, the client channel is bound to one of the worker thread which is processing all network events such as write, read operations and stuff like that. So in this use case, it doesn't really matter if I have 1 worker thread or 4, for example.

> Generally we try to provide "reasonable defaults" and provide hooks to tweak things to fit your use case. If there are extension points you think make sense we can discuss those.

I appreciate your work guys. You managed to create a really cool network framework which has very neat API and performs really well for most use cases. The sad thing is when you're trying to achieve maximum throughput or minimum latency you can't just go and look in the docs. That's where the fun begins :)

**Comment by maseev** [comment]
@Scottmitch The first thing that came to my mind - increasing TCP receive/send buffers, but this didn't work out. Then I thought about high and low watermarks but changing these parameters did almost nothing. Disabling Nagle's algorithm was a pretty obvious trick that almost anybody does when writing a client-server application. The only thing that I'm thinking is implementing batching on the client side. It'll boost throughput tremendously, but for some reason, I can't do this.

**Comment by Scottmitch** [comment]
@maseev - Try running the echo examples in the following configuration. Let me know what throughput you observe. This should demonstrate that higher throughput is possible (just with the default configuration).

```bash
$ ./run-example.sh echo-server
```

```bash
$ ./run-example.sh -Dsize=10000000 echo-client
```

>  when you're trying to achieve maximum throughput or minimum latency you can't just go and look in the docs.

Yip max performance is almost always a context sensitive ... typically there is no silver bullet here.

**Comment by maseev** [comment]
Well, the throughput is awesome:

![selection_003](https://cloud.githubusercontent.com/assets/3434800/14690033/e01c621e-076b-11e6-90c5-76d7f82afad7.png)

**Comment by maseev** [comment]
@Scottmitch I'm just curious, is there any difference in writing to a channel a big chunk of data like I did in the previous example (10Mb ByteBuf) and writing a bunch of small ByteBuffers with total size = 10Mb?
Because it's the only difference I see in this application.

**Comment by ninja-** [comment]
@maseev yes the difference could be quite big because then flush would have to flush them one by one in NIO case...you can try writing to your internal buffer and only flush the one when channel is flushed. But I doubt it could have a big impact on performance.

**Comment by Scottmitch** [comment]
@maseev - Yip writing smaller chunks can involve more object allocation, queuing, looping, and in general requires more work.  There is also a configuration which is designed to prevent any single channel from consuming too many resources on the write side called `getWriteSpinCount` (see its use in NIO [here](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/nio/AbstractNioByteChannel.java#L168)). If this is not tuned to your use case this could mean Netty will set the write flag on the polling mechanism and be woken up at some later time to write again, or if the channel is still writable execute a runnable to complete the rest of the writes later. @ninja- already commented in https://github.com/netty/netty/issues/5152#issuecomment-210807628 the potential benefits that transport-native-epoll's gathering write mechanism can bring ... the OS can gather multiple writes and do them in a single system call. All of this is also subject to your SO_SNDBUF and how quickly your peer is reading data.

**Comment by maseev** [comment]
@Scottmitch, @ninja- I was actually talking about the way how multiple writes are combined before they get flushed. Netty calls [SocketChannelImpl.write(ByteBuffer[])](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/sun/nio/ch/SocketChannelImpl.java#369) which calls [IOUtils.write](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/sun/nio/ch/IOUtil.java#182) that combines passed byte buffers into one native array and write them to the socket. So, from this point of view, the logic is pretty much the same.

I just found out that the real client application actually buffers data before sending it to the server. It sends chunks of data. Every chunk has size equals to 65536 bytes. But I noticed that my server application reads at most 65536 for every read operation whereas the other server app reads 500 kb of data constantly. 

I also noticed that from Netty 4.0.36 I can specify my custom [SelectStrategy](https://github.com/netty/netty/pull/4955). It seems that It can be used in order to improve overall throughput. Is there anything I can do in order to read in bigger chunks?

**Comment by trustin** [comment]
I wonder if `PooledByteBufAllocator` is being used. If you are using 4.0, `UnpooledByteBufAllocator` is the default allocator, and you'd better using the pooled one.

**Comment by trustin** [comment]
Never mind. Looked into your repository and it seems to use the pooled one.

**Comment by Scottmitch** [comment]
> Netty calls SocketChannelImpl.write(ByteBuffer[]) which calls IOUtils.write that combines passed byte buffers into one native array and write them to the socket. So, from this point of view, the logic is pretty much the same.

Yip that is true NIO will attempt to do gathering writes if [NioSocketChannel](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/socket/nio/NioSocketChannel.java#L305) is in use.

> But I noticed that my server application reads at most 65536 for every read operation whereas the other server app reads 500 kb of data constantly.

Setting the [RecvByteBufAllocator](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/ChannelConfig.java#L178) is how you control how much is read.  See the interface for `RecvByteBufAllocator`.

> I also noticed that from Netty 4.0.36 I can specify my custom SelectStrategy. It seems that It can be used in order to improve overall throughput. Is there anything I can do in order to read in bigger chunks?

This is not related to how much is read when the select loop detects there is read activity.

**Comment by maseev** [comment]
> Setting the RecvByteBufAllocator is how you control how much is read. See the interface for RecvByteBufAllocator.

Setting a custom AdaptiveRecvByteBufAllocator did the trick. Well, kind of:

![selection_006](https://cloud.githubusercontent.com/assets/3434800/14720600/0beb093c-0824-11e6-8b5a-1435f9e307fd.png)

Now server reads more data per socket read invocation, but the time gap between two read operations has increased dramatically.

**Comment by Scottmitch** [comment]
@maseev - This feels more like a configuration / performance tweaking exercise at the moment. Please feel free to re-open if you think this may actually be related to a Netty issue ... we try to keep github focused to issues and feature requests.

**Comment by maseev** [comment]
@Scottmitch Never mind. Thanks for your help guys. If you curious, these time gaps are actually related to the GC pauses. I think I need to profile my application more carefully.
