### ISSUE TITLE
Little Endian

### ISSUE THREAD

**Issue by matty** [netty/netty#5154]
I can't seem to find the right way to set incoming bytes as little endian for the byte order. I am using "LengthFieldBasedFrameDecoder" but I believe the bytes received are big endian, so the bytes are incorrect and the length of the message is read incorrectly.

Is this a missing feature or do I need to do it another way? (add another decoder to re order the bytes first?)

**Comment by johnou** [comment]
By default LengthFieldBasedFrameDecoder is big endian. You can set the byte order when creating the decoder. 

http://netty.io/4.0/api/io/netty/handler/codec/LengthFieldBasedFrameDecoder.html#LengthFieldBasedFrameDecoder(java.nio.ByteOrder,%20int,%20int,%20int,%20int,%20int,%20boolean)

**Comment by matty** [comment]
Oh! I must have missed that, couldn't find documentation anywhere. Is there a way to set the client bytebufs to little endian by default on any received data? or is the data that is received further down the pipeline ordered little endian as the LengthFieldBasedFrameDecoder is first in the pipeline?

**Comment by johnou** [comment]
Data received after LengthFieldBasedFrameDecoder should be little endian (if that is what you set in the constructor).

**Comment by matty** [comment]
It appears that it needed re ordering again, solved that issue now anyway. I have another query. If say I receive some data but half the data is encrypted, using the LengthFieldBasedFrameDecoder works for the first read by the second it errors because the data comes back as "454056334" (or some ridiculous length).

Setting auto read to false after the first read doesn't work because the data is already received, how do I do a first read, then pause reading until later? Auto read won't work because bytes are already received?
