### ISSUE TITLE
Little Endian support

### ISSUE THREAD

**Issue by matty** [netty/netty#5156]
I can't seem to find how to get proper support for little endian with Netty. The "MessageToByteEncoder" writing to "ByteBuf out" the out ByteBuf is a big endian.

Is this possible? How do I set all bytebufs to be little endian?

**Comment by matty** [comment]
I've created an custom allocator using

```
public class LittleIndianByteBufAllocator extends AbstractByteBufAllocator {
    @Override
    protected ByteBuf newHeapBuffer(int initialCapacity, int maxCapacity) {
        ByteBuf b = Unpooled.buffer();
        return b.order(ByteOrder.LITTLE_ENDIAN);
    }

    @Override
    protected ByteBuf newDirectBuffer(int initialCapacity, int maxCapacity) {
        ByteBuf b = Unpooled.directBuffer();
        return b.order(ByteOrder.LITTLE_ENDIAN);
    }

    @Override
    public boolean isDirectBufferPooled() {
        return false;
    }
}
```

Is this the only way?

**Comment by trustin** [comment]
Which version are you using? Since 4.1, `order(...)` has been deprecated. You can use `get/set/read/write...LE()` methods.

**Comment by matty** [comment]
I am using 4.0.*, So in 4.1 the order doesn't need to be set anymore? Just use write..LE, read..LE?

**Comment by trustin** [comment]
Yes.

**Comment by matty** [comment]
Ok, thanks. I'll close this issue now as this has been cleared up.
