### ISSUE TITLE
JsonObjectDecoder does not handle escaped backslash

### ISSUE THREAD

**Issue by Zpetkov** [netty/netty#5157]
I've noticed the JsonObjectDecoder checks end of value string by looking at the previous char and if its the escape char \ then it's not the end of string if the current char is double quote. This is not correct.

Let's send the json object with key "key" and value "something\" , it is serialized as this:

{"key":"something\\\"}

The decoder will not decode this since the last double quote is  after a backslash.
However this backslash is escaped but this is not handled in the code:
https://github.com/netty/netty/blob/83c349ffa94d3992c4ee511d3625afc0c97c12bb/codec/src/main/java/io/netty/handler/codec/json/JsonObjectDecoder.java#L194

This is with 5.0.0 Alpha2
Cheers

**Comment by buchgr** [comment]
@Zpetkov the 5.x branch has been deprecated and is no longer supported. However, the issue also exists in 4.1. I ll take care of this.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5203
