### ISSUE TITLE
ChunkedWriteHandler blocks with ChunkedStream input

### ISSUE THREAD

**Issue by user467x** [netty/netty#5159]
Netty Version: 5.0.0.Alpha3-20151217

Hello,
I have a use case where backend process streams have to pass through to http clients. It happens that netty ChunkedWriteHandler blocks in case the chunked size is bigger than the stream length.

I include the ChunkedWriteHandler dynamically into pipeline:

```java
// notify client about chunked transfer
HttpUtil.setTransferEncodingChunked(httpResponse, true);
// Write protocol version and header.
ctx.write(httpResponse, promise);

final ChunkedWriteHandler handler = ctx.pipeline().get(ChunkedWriteHandler.class);
if (handler == null)
{
ctx.pipeline().addBefore("auth", "chunkedWriter", new ChunkedWriteHandler());
}
contentFuture = ctx.write(new HttpChunkedInput(new ChunkedStream((InputStream)payload, 8192)));
// HttpChunkedInput will write the end marker (LastHttpContent) automatically
lastContentFuture = contentFuture;
```
 
I could track down the issue and have now following workaround:

```java
public class FixedChunkedWriteHandler extends ChunkedWriteHandler {
    public FixedChunkedWriteHandler() {
      super();
    }

    @Override
    public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) throws Exception {
        super.write(ctx, msg, promise);
        if (ctx.channel().isWritable()) {
          super.flush(ctx);
        }
    }
}
```

Is this a solution which can be integrated in original ChunkedWriteHandler?
BTW I did not notice a progress in version 5.0.0 development, nightly build downloads still stuck on version Alpha3-20151217. Should I switch back to version 4.x for new developments?

Thank you,

**Comment by Scottmitch** [comment]
> It happens that netty ChunkedWriteHandler blocks

Invoking flush can be controlled at the application level by using `channel.flush()`, `ctx.flush()`, or even `channel.writeAndFlush()`. Typically applications avoid calling `writeAndFlush` (or flushing with every write) and instead flush at some point after multiple writes are done to take advantage of gather writes. I don't think it makes sense to have the behavior described above in `ChunkedWriteHandler` for these reasons.

> BTW I did not notice a progress in version 5.0.0 development, nightly build downloads still stuck on version Alpha3-20151217.

5.0 is no longer supported ... see https://github.com/netty/netty/issues/4466
