### ISSUE TITLE
EPOLL OSGi header Bundle-NativeCode

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#5168]
Prompted by https://github.com/netty/netty/issues/5150

The transport-native-epoll module also does not generate the `Bundle-NativeCode` header in the `MANIFEST.MF`

**Comment by Scottmitch** [comment]
This is a possible duplicate of https://github.com/netty/netty/issues/5119 ... however I'm not sure what the scope of that issue is ... @MilosFabian WDYT?

**Comment by MilosFabian** [comment]
@Scottmitch I do not think so...in #5119 - the project is not packed as a bundle at all

**Comment by normanmaurer** [comment]
I fixed this a while ago
