### ISSUE TITLE
Add in SslContext a factory to create a SslHandler with startTls

### ISSUE THREAD

**Issue by victornoel** [netty/netty#5170]
Hi,

Before 4.1 is released, I have a small request for improvement.

When using the SslHandler facilities of netty I got confused because there is no way to use the SslContext to create a SslHandler with startTls enabled.

It would make sense to mirror the constructors of SslHandler with the newHandler methods of SslContext.

And also, wa can add a builder method to enable it in SslContextBuilder.

Thanks

**Comment by Scottmitch** [comment]
sounds reasonable @victornoel ... are you interested in submitting a PR?

**Comment by victornoel** [comment]
Good idea, I will work on it, should be easy. Any important things to know in term of process? It's my first contribution to netty.

**Comment by victornoel** [comment]
Actually it's not a so obvious change: if we want to change SslContextBuilder, it means we need to add a startTls member to SslContext (and thus modify all the subclasses constructors…). If not the parameter can simply be passed to newHandler() but then it's can't be in the builder…

I'm not sure which is best… @Scottmitch ? :)

**Comment by Scottmitch** [comment]
@victornoel - I don't think they are mutually exclusive but just a matter if we need to support both. Here is how I see supporting both would work...
- In terms of adding a member variable to SslContext ... you can just modify the constructors which are not deprecated, and pass `false` from the deprecated constructors to replicate the existing behavior.
- The existing `newHandler` methods can use the member variable as the parameter for the new `newHandler` methods (which take a `boolean startTls`).

I don't have a preference (for both vs just one) ATM but lets start with both and collect comments from others.

**Comment by victornoel** [comment]
Here it is :)

**Comment by victornoel** [comment]
@normanmaurer is it possible to have the CCLA officially referenced on the netty website? Thanks :)

**Comment by normanmaurer** [comment]
Fixed via https://github.com/netty/netty/pull/5178
