### ISSUE TITLE
NioDatagramChannel can only run under JDK 7+

### ISSUE THREAD

**Issue by wanganran** [netty/netty#5171]
Hi,

My Netty version is 4.0.35.Final. I found that `io.netty.channel.socket.nio.NioDatagramChannelConfig` imports `java.nio.channels.NetworkChannel` which is new in JDK 7.

This will cause `NioDatagramChannel` unusable in Android where its Dalvik VM is under Java 1.6. A temporary solution is using `OioDatagramChannel` instead.

How to reproduce:

Just import Netty to an Android app (my Android version: 4.2.2) and try to use `NioDatagramChannel`. Three errors appear during runtime:

```
Could not find class 'java.nio.channels.MembershipKey', referenced from method io.netty.channel.socket.nio.NioDatagramChannel.block
Could not find class 'java.nio.channels.MembershipKey', referenced from method io.netty.channel.socket.nio.NioDatagramChannel.leaveGroup
Could not find class 'java.nio.channels.NetworkChannel', referenced from method io.netty.channel.socket.nio.NioDatagramChannelConfig.<clinit>
```

This issue was also reported in #2816. I think it needs to be addressed in order to make NIO UDP communications compatible with JDK 6.

**Comment by Scottmitch** [comment]
@wanganran - Thanks for reporting.

@trustin - Looks like this was introduced in https://github.com/netty/netty/commit/ada61d4985571f5406ea6158b02755d51392ebff . Can you take care?

**Comment by normanmaurer** [comment]
will take care

**Comment by windie** [comment]
I think NioDatagramChannel should report an error: https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/socket/nio/NioDatagramChannel.java#L104

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5210
