### ISSUE TITLE
Expose Bootstrap getter methods and add some additional ones

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#5174]
The `Bootstrap` class (applies also to `AbstractBootstrap` and `ServerBootstrap`) has a few package private getter methods and some things such as `#attr()` and `#options()` aren't exposed at all. I'd argue there should be public getter methods for all of them.

Background: Our application is written in Java but we use Clojure as a configuration language (instead of XML, JSON, YAML) to skip the object mapping indirection. 

This creates a slight problem for partial configurations. Let's take the following example:

```clojure
(def myClientBootstrap (-> (Bootstrap.)
  (.option ChannelOption/SO_REUSEADDR true)
  (.remoteAddress "host" 8080)))
```

```java
Bootstrap myClientBootstrap = getClientBootstrapFromClojureLand();
```

There is no way for me to test if a `ChannelFactory` is configured and fill the blanks if it isn't for example (NIO on non-Linux and EPOLL on Linux). Ditto, I can't test if a remote address isn't configured and blow up. 

We're currently using a wrapper objects around `Bootstrap` and `ServerBootstrap` that provides getter methods but that seems unnecessary and adds only indirection.

**Comment by Scottmitch** [comment]
the underlying storage is currently exposed by `options` and `attr` and there is synchronization that must be applied when dealing with these collections. I'm guessing they are not exposed so the storage can be directly exposed and its assumed users of the interface "play nice" with synchronization and modifiability. We should consider these factors before making changes to these interfaces.

**Comment by normanmaurer** [comment]
Yeah I think the synchronisation is an issue. That said maybe we could just expose a copy of the attributes / options. Let me cook up something...

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5243
