### ISSUE TITLE
SocketChannel.shutdownInput()?

### ISSUE THREAD

**Issue by vrozov** [netty/netty#5175]
Is there a way to shutdownInput? I see that there is SocketChannel.shutdownOutput(), but no shutdownInput().

**Comment by Scottmitch** [comment]
At the moment not through this interface. What type of socket channel are you dealing with as there is likely a way to do it using an implementation of this interface.

**Comment by vrozov** [comment]
NioSocketChannel, EpollSocketChannel or OioSocketChannel

**Comment by Scottmitch** [comment]
I see you want it all ... stand by for a PR.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5269
