### ISSUE TITLE
Http2Stream Equivalent of ChannelConfig#setAutoRead

### ISSUE THREAD

**Issue by ssheng** [netty/netty#5176]
Our reactive stream implementation on HTTP/1.1 relies on turning on/off auto read on the ChannelConfig to enforce back pressure on the sender. With HTTP/2 flow control, this is ideally specified on the stream level. I wonder what is the best practice for enabling this?

**Comment by normanmaurer** [comment]
@Scottmitch @nmittler @louiscryan anyone ? ;)

**Comment by nmittler** [comment]
Control of inbound flow control in HTTP/2 can be done in a couple of places:

1) First, the callback for [Http2FrameListener.onDataRead](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2FrameListener.java#L41) allows you to immediately "consume" some amount of the inbound data. This effectively gives those bytes back to flow control to allow it to request more data from the remote endpoint (i.e. `WINDOW_UPDATE`).
2) For any bytes not immediately consumed by the listener, the application can consume them later via [Http2LocalFlowController.consumeBytes](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2LocalFlowController.java#L67).

**Comment by ssheng** [comment]
@nmittler Thanks.

**Comment by nmittler** [comment]
@ssheng agreed ... once we switch over to child channels, I suspect this will become more natural (i.e. Netty-like).

**Comment by ssheng** [comment]
@nmittler Thanks for the response. Sounds like child channels won't be part of the 4.1 final release. Do we have a target? Is there an opportunity to get involved?

**Comment by nmittler** [comment]
@ejona86 and @buchgr may have more regarding the timeline for child channels.

**Comment by ejona86** [comment]
@ssheng no timelines as of yet. There's a lot to do still to get feature parity. Much of the work isn't too hard, but some important pieces still need some in-depth decisions made (like outbound flow control). Inbound flow control is already mostly implemented for `Http2MultiplexCodec`/`AbstractHttp2StreamChannel`, although I won't say I've tested disabling auto read (it looks like `DefaultMaxMessagesRecvByteBufAllocator` should be handling that automatically, though). #3667 is tracking for the full implementation; feel free to look at/grab some of the issues linked there (or create a new one for something currently lacking an issue).
