### ISSUE TITLE
DNS name resolution queries should not be sent while the same query is in progress already.

### ISSUE THREAD

**Issue by trustin** [netty/netty#5179]
When you attempt to make a lot of connection attempts to the same target host at the same time and our DNS resolver does not have a record for it in the cache, the DNS resolver will send as many DNS queries as the number of connection attempts.

As a result, DNS server will reject or drop the requests, making the name resolution attempt fail.

To fix this, we could keep the list of name resolution queries and subscribe to the future of the matching query instead of sending a duplicate query.

Will work on a fix.

**Comment by trustin** [comment]
This is the patch I wrote for [Armeria](https://github.com/line/armeria):

https://github.com/line/armeria/pull/155/files

As shown in the PR above, we could write a decorating `NameResolver` that works for all `NameResolver` implementations. However, I'm not sure what the name of that class would be. Any suggestions?

**Comment by normanmaurer** [comment]
InflightDnsNameResolver ? Not sure its the best name though

**Comment by normanmaurer** [comment]
@trustin WDYT ?

**Comment by slandelle** [comment]
FlyingQueriesAwareDnsNameResolver ? Pro is that such name will make Spring people jealous ;-)

**Comment by slandelle** [comment]
InProgressAware?

**Comment by normanmaurer** [comment]
@trustin also we can just make it package private for now and find a good name later if we feel we not have a good one atm.

**Comment by trustin** [comment]
Alright. Let me cook some tomorrow.

**Comment by normanmaurer** [comment]
any news ?

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5267
