### ISSUE TITLE
Request: Create a 4.1.0 CR8 

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty#5181]
Would it be possible to get another release candidate?   There are some changes gRPC would like to use (namely the native library loading changes).

**Comment by normanmaurer** [comment]
My plan was to cut final next week once back from vacation. Is this good enough?

**Comment by carl-mastrangelo** [comment]
Sure, just eventually.  I didn't know how long it would be before one was released (it looked like you guys were doing one a week).

**Comment by carl-mastrangelo** [comment]
Friendly ping.

**Comment by normanmaurer** [comment]
@carl-mastrangelo working on getting everything done for the release...

**Comment by carl-mastrangelo** [comment]
Awesome, thanks!
