### ISSUE TITLE
HostsFileParser tries to resolve hostnames as case-sensitive

### ISSUE THREAD

**Issue by alexlehm** [netty/netty#5182]
Netty version: 4.1.0.CR7

Context:
I am implementing a mail client in vert.x, which uses netty as network library, when trying to connect to LOCALHOST in upper case, the dns client gives an UnknownHostException.
The regular behaviour of the /etc/hosts resolution should be match the hostnames case insensitive

Steps to reproduce:
run the following unit test:
https://gist.github.com/alexlehm/e921fca3c368617be29cc7432b376927

the test using "localhost" resolves, while the test using "LOCALHOST" fails

java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

Operating system: Windows 7 64-bit

I would guess the error is that the entries Map has to use hostname as case folded key here https://github.com/netty/netty/blob/4.1/resolver/src/main/java/io/netty/resolver/HostsFileParser.java#L157 and here https://github.com/netty/netty/blob/4.1/resolver/src/main/java/io/netty/resolver/DefaultHostsFileEntriesResolver.java#L30

**Comment by slandelle** [comment]
Should be pretty easy to contribute a fix :)

**Comment by alexlehm** [comment]
Included the unit test in the pr and added the fix for the issue
https://github.com/netty/netty/pull/5189
I am not sure if this change would require the cla to be signed, if so, this will take some time since I have to apply for clearance to participate in the project first.

**Comment by normanmaurer** [comment]
Fixed by #5189
