### ISSUE TITLE
Server HTTP can not accept the post request JSON parameters

### ISSUE THREAD

**Issue by donieh** [netty/netty#5183]
http server

       ServerBootstrap bootstrap = new ServerBootstrap();
                    bootstrap.group(bossGroup, workerGroup);
                    bootstrap.channel(NioServerSocketChannel.class);
                    bootstrap.childOption(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT);
                    bootstrap.childHandler(new ChannelInitializer<SocketChannel>() {
                        EventLoopGroup businessGroup = new NioEventLoopGroup(businessGroupPoolSize);

                        @Override
                        public void initChannel(SocketChannel channel) throws Exception {
                            channel.pipeline().addLast("http-decoder", new HttpRequestDecoder());
                            channel.pipeline().addLast("http-encoder", new HttpResponseEncoder());
                            channel.pipeline().addLast("http-aggregator", new HttpObjectAggregator(65536));
                            channel.pipeline().addLast("http-chunked", new ChunkedWriteHandler());
                            channel.pipeline().addLast(businessGroup, new RpcHttpServerHandler(serviceBeanHandlerMap));
                        }
                    });
                    bootstrap.option(ChannelOption.SO_BACKLOG, 1024);
                    bootstrap.childOption(ChannelOption.SO_KEEPALIVE, true);

httpServerHandler

     @Override
     protected void channelRead0(ChannelHandlerContext ctx, HttpObject msg) throws Exception {
        boolean keepAlive = true;
        try {

            Map<String, Object> map = null;
            if (msg instanceof HttpRequest) {
                HttpRequest request = (HttpRequest) msg;
                getParametersHandler(request);
            }
        }finally {

        }
    }
    
    private Map<String, Object> getParametersHandler(HttpRequest request) throws IOException {
        Map<String, Object> map = new HashMap<String, Object>();
        if (request.getMethod().name().equals("POST")) {
            HttpPostRequestDecoder decoder = new HttpPostRequestDecoder(new DefaultHttpDataFactory(false), request);
            List<InterfaceHttpData> interfaceHttpDatas = decoder.getBodyHttpDatas();
            for (InterfaceHttpData data : interfaceHttpDatas) {
                Attribute attribute = (Attribute) data;
                map.put(attribute.getName(), attribute.getValue());
            }
        } else {
            QueryStringDecoder queryStringDecoder = new QueryStringDecoder(request.getUri());
            Map<String, List<String>> params = queryStringDecoder.parameters();
            if (!params.isEmpty()) {
                for (Entry<String, List<String>> p : params.entrySet()) {
                    String key = p.getKey();
                    List<String> vals = p.getValue();
                    for (String val : vals) {
                        map.put(key, val);
                    }
                }
            }
        }
        return map;
    }

HTTP post request 

    JSONObject json = new JSONObject();
        Person person = new Person();
        person.setFirstName("donie");
        person.setLastName("Huang");
        json.put("person", person);
        DefaultHttpClient client = new DefaultHttpClient();
        HttpPost post = new HttpPost(url);
        JSONObject response = null;
        try {
            StringEntity s = new StringEntity(json.toString());
            s.setContentEncoding("UTF-8");
            s.setContentType("application/json");
            post.setEntity(s);
            HttpResponse res = client.execute(post);
            if(res.getStatusLine().getStatusCode() == HttpStatus.SC_OK){
                HttpEntity entity = res.getEntity();
                String result = EntityUtils.toString(res.getEntity());
                System.out.println(result);
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

**Comment by Scottmitch** [comment]
@donieh - Can you clarify the issue you are observing from Netty's perspective? Specifically what are you expecting to get from Netty that is not happening? What is `httpServerHandler`

**Comment by normanmaurer** [comment]
Please reopen with more details if you think there is a netty bug.
