### ISSUE TITLE
Infinite loop with late listeners notification

### ISSUE THREAD

**Issue by NiteshKant** [netty/netty#5185]
##### Netty Version

Tested with 4.1-CR7 but I think it exists in 4.0 too.

##### Context

I came across this while upgrading [RxNetty](https://github.com/ReactiveX/RxNetty) to netty 4.1-CR7. One of the tests happen to have a more convoluted form of the test specified in this issue.

##### Problem

This [code](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/concurrent/DefaultPromise.java#L846) in `DefaultPromise` has the potential to get into an infinite loop where the same task in enqueued repeatedly on the executor. The case happens when there are listeners as well as late listeners for a promise. In such a case when the late listeners are executed via the `LateListeners`task, it never reaches the [point](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/concurrent/DefaultPromise.java#L849) to notify the listeners, instead just [executes `self`](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/concurrent/DefaultPromise.java#L859) infinitely.
The simplest way to reproduce is with the below reproducer.

##### Reproducer

```java
        EmbeddedChannel channel = new EmbeddedChannel();
        channel.closeFuture().addListener(new ChannelFutureListener() {
            @Override
            public void operationComplete(ChannelFuture future) throws Exception {
                future.channel().close();
            }
        });

        channel.close().await();
```

The above code will result in an infinite loop due to the above explained issue.

**Comment by Scottmitch** [comment]
@NiteshKant - Thanks for reporting! This kinda a "known limitation" identified last time this was patched up https://github.com/netty/netty/issues/4395#issuecomment-153491183 for ImmediateExecutor ... however let me see if I can generalize this approach ... especially because it occurs with a Netty executor (EmbeddedEventLoop)
