### ISSUE TITLE
HTTP2 Frame Decoder Bug

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty#5186]
While debugging an apparent hang, I discovered what I believe the be a bug in the [DefaultHttp2FrameReader.readFrame](https://github.com/netty/netty/blob/5b5925065796471c2d00ad53d8aaff888f24b752/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameReader.java#L129 ).  

The sequence of events that can cause this is as follows:
1. C: Send Headers
2. C: Send Data
3. S: Receive Headers from 1
4. S: Receive Data from 2
5. S: Send Headers
6. S: Send Data
7. C: Receive headers from 5
8. S: Send Trailers
9. C: Receive Data from 6
10. C: Send Reset to server
11. S: Server Receives Reset
12.  C: Receive Headers from 8

At this point, the client has no idea about the stream any more, and considers the headers for the stream to be an error.  Trying to process the frame results in an exception thrown in [DefaultHttp2ConnectionDecoder.shouldIgnoreHeadersOrDataFrame]( https://github.com/netty/netty/blob/5b5925065796471c2d00ad53d8aaff888f24b752/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L567 )  The exception is caught back in [.readFrame]( https://github.com/netty/netty/blob/5b5925065796471c2d00ad53d8aaff888f24b752/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameReader.java#L160 )  Which sets the state of the connection to be in error, and rethrow the error.  

The error is propagated up to [Http2ConnectionHandler.onError]( https://github.com/netty/netty/blob/5b5925065796471c2d00ad53d8aaff888f24b752/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L535 )  which checks what kind of error it is.  It is correctly classified as a stream error rather than a connection error, so the whole connection isn't torn down.

Here is the bug.  The Frame reader thinks the whole connection is borked, and will just ignore any more data, while the rest of the code think the connection is still good.  This effectively stops processing on all streams and the program never recovers.

cc: @nmittler @ejona86 @buchgr

This bug is the root cause of https://github.com/grpc/grpc-java/issues/1682
I have included the Frame logging output  below, which include the other streams that were created at the time (as well as a small amount of unrelated noise).
[log.txt](https://github.com/netty/netty/files/241676/log.txt)

**Comment by Scottmitch** [comment]
@carl-mastrangelo - Thanks for the detailed report! Seems like settings the state to `ERROR` in [DefaultHttp2FrameReader](https://github.com/netty/netty/blob/5b5925065796471c2d00ad53d8aaff888f24b752/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameReader.java#L161) is a bit aggressive for stream errors. I would need to investigate more but I wonder if we even need the `State.ERROR` any more... @nmittler - WDYT?

**Comment by ejona86** [comment]
The sequence of events is a bit hard to read. In short, a client resets a stream but the server has frames in-route for that stream, when those frames are then received by the client the bug is triggered.

**Comment by Scottmitch** [comment]
pr pending

**Comment by buchgr** [comment]
@Scottmitch thanks!
