### ISSUE TITLE
Redis Buffer Leak

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#5190]
RedisDecoder calls `ByteBuf.retain()` and the next line may throw an exception, but the buffer is never released [1]. More investigation is needed in this class whenever retain is called to ensure it is either written or released.

[1] https://github.com/netty/netty/blob/4.1/codec-redis/src/main/java/io/netty/handler/codec/redis/RedisDecoder.java#L208

**Comment by Scottmitch** [comment]
@jongyeol - FYI

**Comment by jongyeol** [comment]
I'll check it soon too.

**Comment by normanmaurer** [comment]
Let me fix it.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5211
