### ISSUE TITLE
Bug in AbstractMemcacheObjectEncoder with FullMemcacheMessage(s)

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#5197]
Netty 4.1.0-SNAPSHOT

There is a bug in [AbstractMemcacheObjectEncoder](https://github.com/netty/netty/blob/4.1/codec-memcache/src/main/java/io/netty/handler/codec/memcache/AbstractMemcacheObjectEncoder.java) on line 48.

The `encode()` method returns and the `FullBinaryMemcacheRequest|Response` `content()` gets never written.

**Comment by Scottmitch** [comment]
@rkapsi - Thanks for reporting!

**Comment by Scottmitch** [comment]
Trivial fix to revert a commit see .. 9ed2f01853d82940b42c795eb541046872c3086b

If issue still persists please re-open.
