### ISSUE TITLE
http/2 message => http/1.1 message adapter for the new http/2 api

### ISSUE THREAD

**Issue by mosesn** [netty/netty#5199]
## problem

http/2 and http/1.1 have similar protocols, and it's useful to be able to implement a single server against a single interface.  There's an injection from http/1.1 messages to http/2 ones, so it makes sense to make folks program against http/1.1 and upgrade them under the hood.

## proposed solution

a `MessageToMessageDecoder<Http2StreamFrame>` which turns every kind of `Http2StreamFrame` domain object into an `HttpContent` domain object.

## what's next

I'm working on building this for myself, and I would love to contribute it back to netty.  Please let me know what you think!  Right now I'm able to avoid all aggregation, and the adapters that I've written so far are:

```
HeadersFrame is endStream => LastHttpContent with Trailers
                         is not endStream => HttpConversionUtil.toHttpRequest or toHttpResponse
Http2DataFrame is endStream => LastHttpContent
                            is not endStream => HttpContent
```

Right now I'm not handling goaway, reset, or stream id, and I figure we can add those as we go along.

The opposite is mostly symmetric, except that there are some http/1.1 messages which will decompose to more than one http/2 message, but that's easy to encode.

**Comment by ejona86** [comment]
I've added this to the checklist in #3667. What you've proposed sounds good.

GOAWAY and RST_STREAM can simply be ignored since the channel will closed automatically (they are propagated for additional information to those that want it; HTTP/1 doesn't want it). Stream ID should always be null on a child channel (at least for now), so there should be nothing to handle there either.

**Comment by Scottmitch** [comment]
Not sure if this is covered somewhere or is understood but just to clarify on the following....

> HeadersFrame is endStream => LastHttpContent with Trailers

A HEADERS frame with EOS doesn't necessarily mean the headers are trailers. This frame could just be the first HEADERS frame and there are no DATA frames to follow.

**Comment by mosesn** [comment]
OK, that's good to know.  So that would be converted to a FullHttpRequest with an empty content body?
