### ISSUE TITLE
WebSocket upgrade wrecks HttpProxyHandler

### ISSUE THREAD

**Issue by caillette** [netty/netty#5201]
Short story: `WebSocketClientHandshaker` reorganizes the Pipeline after receiving the upgrade from the server. If there is an `HttpProxyHandler` in the Pipeline, it has installed its own `HttpClientCodec` which gets wrecked by `WebSocketClientHandshaker`.

I used a handcrafted configuration which was easy to hack to see where the problem is. Since proxies don't support `ws://` I used `wss://` all along. I used Squid 3.4 as a proxy. I ran those configurations:
- Firefox and Netty's WebSocket demo server. Success.
- Firefox, Netty's WebSocket demo server, and Squid in the middle. Success.
- Netty WebSocket client, Netty's WebSocket demo server. Success.
- Netty WebSocket client, Netty's WebSocket demo server, Squid in the middle. Fails.

Using Netty's `LoggingHandler` here and here, I found that adding the `HttpProxyHandler` had unexpected side-effects. I finally dumped the `ChannelPipeline` and discovered that `#finishHandshake` reconfigures the first `HttpClientCodec` in the Pipeline, as shown by this short dump:

```
HttpClientCodec#0        <-- #finishHandshake hit this one.
ws-decoder               <-- We don't want this here.
ws-encoder               <-- We don't want this here.
Http11ProxyHandler#0
SslHandler#0
HttpClientCodec#1
                         <-- ws-xxcoder should appear here.
DownendChannelHandler#0  <-- My own stuff.
```

I'm using Netty-4.1.0.CR7 and Java 1.8.0_66.

I suggest to add a method to the `WebSocketClientHandshakerFactory` for passing a pair of method objects selecting the `HttpClientCodec` or the `HttpRequestEncoder` to modify in `WebSocketClientHandshaker#finishHandshake`. Please tell me if it makes sense.

I'll be happy to write a fix, including automated tests.

**Comment by normanmaurer** [comment]
@caillette I wonder if we would need to do something similar for all other handlers that it will try to remove or replace. WDYT ?

**Comment by normanmaurer** [comment]
@caillette also this should fix it as well:

https://github.com/netty/netty/pull/5142

Not sure its the best solution tho ....

**Comment by caillette** [comment]
I'm glad to see commits for this issue. Passing a `Set` of `ChannelPipeline`s looks much more handy than the `Predicate` I suggested.

I've written an ugly workaround, here it is in case somebody needs a quick fix:
https://gist.github.com/caillette/cd05ed3b9a7bc273bafe957084e40940
The `WebSocketClientHandshaker` keeps doing its job, except when it comes to Pipeline reconfiguration, which is delegated to some pluggable code (by default it is a copy-paste of what `WebSocketClientHandshaker` does).

**Comment by jboesl** [comment]
Is there any progress with this issue? I'm facing the same problem that I need to use HttpProxyHandler and WebSocketClientProtocolHandler together.

**Comment by jboesl** [comment]
I was able to get it working for my by updating the WebSocketClientHandshaker to first search for HttpClientCodec by a fixed name and if the name is not defined fall back to the old behaviour.

**Comment by bgorriz** [comment]
I am getting this error when trying to use a websocket through a compnay proxy. Any hints on how it can be fixed??

**Comment by jbaldassari** [comment]
@caillette @jboesl I opened a PR for this if you'd care to take a look.  I tried to follow the same approach you did: https://github.com/netty/netty/pull/9564

**Comment by gopal229** [comment]
I m hitting the same issue with Netty 4.1.42.Final. 'ws-decoder' and 'ws-encoder' handlers got inserted in the wrong place.

Handler order prior to the handshake

HttpClientCodec#0=io.netty.handler.codec.http.HttpClientCodec@20c73c43, 
proxy=io.netty.handler.proxy.HttpProxyHandler@459697d7, 
websocketClientCodec=io.netty.handler.codec.http.HttpClientCodec@19deaa68, 
aggregator=io.netty.handler.codec.http.HttpObjectAggregator@6887aeab, 
logger=io.netty.handler.logging.LoggingHandler@bb5b85d, 
frameaggregator=io.netty.handler.codec.http.websocketx.WebSocketFrameAggregator@1e1a300b, 
readTimeoutHandler=io.netty.handler.timeout.ReadTimeoutHandler@727b544a, 

post handshake is completed

HttpClientCodec#0=io.netty.handler.codec.http.HttpClientCodec@20c73c43,
ws-decoder=io.netty.handler.codec.http.websocketx.WebSocket13FrameDecoder@7c44e460, 
ws-encoder=io.netty.handler.codec.http.websocketx.WebSocket13FrameEncoder@72831598, 
proxy=io.netty.handler.proxy.HttpProxyHandler@459697d7,
ssl=io.netty.handler.ssl.SslHandler@e2ab13, 
websocketClientCodec=io.netty.handler.codec.http.HttpClientCodec@19deaa68, 
logger=io.netty.handler.logging.LoggingHandler@bb5b85d, 
frameaggregator=io.netty.handler.codec.http.websocketx.WebSocketFrameAggregator@1e1a300b, 
readTimeoutHandler=io.netty.handler.timeout.ReadTimeoutHandler@727b544a,

Any workarounds, suggestions how to fix this.

**Comment by gopal229** [comment]
> I m hitting the same issue with Netty 4.1.42.Final. 'ws-decoder' and 'ws-encoder' handlers got inserted in the wrong place.
> 
> Handler order prior to the handshake
> 
> HttpClientCodec#0=io.netty.handler.codec.http.HttpClientCodec@20c73c43,
> proxy=io.netty.handler.proxy.HttpProxyHandler@459697d7,
> websocketClientCodec=io.netty.handler.codec.http.HttpClientCodec@19deaa68,
> aggregator=io.netty.handler.codec.http.HttpObjectAggregator@6887aeab,
> logger=io.netty.handler.logging.LoggingHandler@bb5b85d,
> frameaggregator=io.netty.handler.codec.http.websocketx.WebSocketFrameAggregator@1e1a300b,
> readTimeoutHandler=io.netty.handler.timeout.ReadTimeoutHandler@727b544a,
> 
> post handshake is completed
> 
> HttpClientCodec#0=io.netty.handler.codec.http.HttpClientCodec@20c73c43,
> ws-decoder=io.netty.handler.codec.http.websocketx.WebSocket13FrameDecoder@7c44e460,
> ws-encoder=io.netty.handler.codec.http.websocketx.WebSocket13FrameEncoder@72831598,
> proxy=io.netty.handler.proxy.HttpProxyHandler@459697d7,
> ssl=io.netty.handler.ssl.SslHandler@e2ab13,
> websocketClientCodec=io.netty.handler.codec.http.HttpClientCodec@19deaa68,
> logger=io.netty.handler.logging.LoggingHandler@bb5b85d,
> frameaggregator=io.netty.handler.codec.http.websocketx.WebSocketFrameAggregator@1e1a300b,
> readTimeoutHandler=io.netty.handler.timeout.ReadTimeoutHandler@727b544a,
> 
> Any workarounds, suggestions how to fix this.

I found a workaround for this.  Instead of adding HttpClientCodec handler, add HttpResponseDecoder/HttpRequestEncoder to the channel pipeline.

**Comment by jano7** [comment]
> I found a workaround for this. Instead of adding HttpClientCodec handler, add HttpResponseDecoder/HttpRequestEncoder to the channel pipeline.

@gopal229 Could you provide a code snippet?

**Comment by gopal229** [comment]
@jano7  Here is the code change.  Just remove the HttpClientCodec and add HttpResonseDecoder, HttpRequestEncoder to the channel pipeline
-        channelPipeline.addLast("http", new HttpClientCodec());
+        channelPipeline.addLast("decoder", new HttpResponseDecoder());
+        channelPipeline.addLast("encoder", new HttpRequestEncoder());

**Comment by normanmaurer** [comment]
After thinking more about all of this I realised there is a very simple workaround.

PTAL:
https://github.com/netty/netty/pull/10103
