### ISSUE TITLE
Question: When is ChannelInboundHandlerAdapter channelActive called?

### ISSUE THREAD

**Issue by JuKu** [netty/netty#5215]
Hi,

I am using Netty 4.0.34.Final and an ChannelInboundHandlerAdapter, but sometimes the channel is changing his state very often, for example:

INACTIVE
ACTIVE
INACTIVE
ACTIVE

and so on.
Whats the cause? Is it an Bug or an feature?

**Comment by normanmaurer** [comment]
That woukd be a bug. It should only go to active and the inactive once.

Can you give more details or even a reproducer?

**Comment by normanmaurer** [comment]
@JuKu ping :)

**Comment by JuKu** [comment]
@normanmaurer I currently have an other problem, so i cannot see this bug, while this problem wasnt resolved. I will upload an reproducer an little bit later, if possible.

But i have seen, that channels will be also inactive, if you dont send any message in for example 5 seconds.

**Comment by normanmaurer** [comment]
@JuKu I will close this for now. If you still think there is an issue please reopen with more infos
