### ISSUE TITLE
netty 4.0.36.Final client receive duplicate message

### ISSUE THREAD

**Issue by liutaohua** [netty/netty#5217]
my netty server like:
```
DefaultChannelGroup nettyGroup;
for(int i =0; i < 100000; i++){ 
      nettyGroup.writeAndFlush(i);
}

```
and then , my client will recive like " 0,375,376,377,377..........."

**Comment by liutaohua** [comment]
i use `CaptureEncoder extends MessageToByteEncoder<Object>` to encode my data,
in debug model i can see ` encode` method recive duplicate message .

**Comment by liutaohua** [comment]
Thread[pool-1-thread-x]
```
DefaultChannelGroup nettyGroup;
for(int i =0; i < 100000; i++){ 
      nettyGroup.writeAndFlush(i);
}
```
Thread[nioEventLoopGroup-2-2]
```
 protected void encode(){
       dosome(x)
}
```


maybe this?

**Comment by liutaohua** [comment]
@normanmaurer can you help me ?

**Comment by normanmaurer** [comment]
Hard to say without see your encoder and decoder

**Comment by liutaohua** [comment]
oh, it's not encoder problem .
i you can follow next code to repetition :

1.create an class 
```
public class A {
      private Object value;
      // another properties
}
```

2.
```
DefaultChannelGroup nettyGroup;
**A[] a = new A[11];**
while(rs.next){
    for(int i =0; i < 12; i++){   
           A column  = new A();
           column.setValue(i);
           a[i] = column;
    }
    nettyGroup.writeAndFlush(a[i]);
}
```
i think i'm not to new the A[] array, so,
next send is come when the last time send not to begin .
then the same memory address value will be change ,right ?
my english is very poor,thanks !

**Comment by windie** [comment]
@liutaohua `writeAndFlush` is  asynchronous. You should send an immutable object. Otherwise, the consumer may see wrong datas.

**Comment by liutaohua** [comment]
@windie  yes,  thanks!
