### ISSUE TITLE
OpenSslContext#toBIO(PrivateKey) should zero the underlying byte[]

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#5218]
This is something that was brought up by our Security Engineers. The `OpenSslContext#toBIO(PrivateKey)` method shouldn't just `release()` the ByteBuf but explicitly fill the underlying byte[] with 0 before nulling the reference.

Right now it's creating 3 copies of the PrivateKey that will be lingering in memory for an unknown amount of time.

**Comment by normanmaurer** [comment]
@rkapsi sure let me take care.

**Comment by normanmaurer** [comment]
@rkapsi that said I`m not sure why zero out the ByteBuf will buy you as the PrivateKey itself is still in memory until GC-ed.

**Comment by rkapsi** [comment]
@normanmaurer yea that is also a problem but it is external to Netty. 

In our case, we roll our own PrivateKey implementation (we get pre-encoded bytes from somewhere and just pass them thru) and there is a `destroy()` method we can call.

For people who go the more traditional route it's a problem. You can use reflection to get the let's say RSAPrivateKey's underlying BigInteger and then use reflection again to zero that `int[]`.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5220... PTAL @rkapsi

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5220
