### ISSUE TITLE
UnsafeDirectByteBuf should use realloc() to expand and contract its buffer

### ISSUE THREAD

**Issue by Techcable** [netty/netty#5224]
UnsafeDirectByteBuf expands its capacity be allocating a new block of memory and copying from the old memory to the new memory.
Its more efficient to use `Unsafe.reallocateMemory(pointer, newSize)`, as it may just expand the size and not need to copy, and shrinking definitely won't need to copy.
I assume you're doing this to get a new ByteBuffer object, since it's capacity is fixed.
However this isn't needed, as DirectByteBuffer has a constructor `DirectByteBuffer(long ptr, int capacity)`.
[this is publicly available in JNI](https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/functions.html#NewDirectByteBuffer) so it should be fairly safe.

The only caveat I see is that this _may_ free the existing nio ByteBuffer, and the new ByteBuffer's address must be freed explicitly (no cleaner is present).

**Comment by Scottmitch** [comment]
thanks @Techcable !

@normanmaurer - IIRC we discussed this at some point... I'll assign to you for now.

**Comment by normanmaurer** [comment]
@Scottmitch yep :) I have another idea in this area.... Just need to find the time to implement it, but stay tuned ;)

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5350
