### ISSUE TITLE
HttpObjectAggregator.replace headers may enforce validation when they should not

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#5226]
`HttpObjectAggregator.replace` creates a new `DefaultFullHttpRequest` and does not specify a value for the `validateHeaders` during construction. This would mean that header validation is not consistent from the user's perspective and may enforce validation when the user does not want validation ... which may throw unexpected/undesired errors.

This issue also exists in other implementations of `replace` in codec-http.

**Comment by normanmaurer** [comment]
@Scottmitch I will take care.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7503
