### ISSUE TITLE
AssertionError in Hpack Decoder

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty#5228]
```
byte[] input = {
        19, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 31, -92, 91, 41, -92,
        33, 1, 0, -126, -1, -1, 0, 15, 0, -92, 0, 0
    };
Decoder decoder = new Decoder(MAX_HEADER_SIZE, MAX_HEADER_TABLE_SIZE);
      decoder.decode(new ByteArrayInputStream(input), listener);
```

This causes an error to be thrown from: [Decoder](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/internal/hpack/Decoder.java#L505)

The reason is because of the two 0xFF bytes in the input, which are interpretted as trailing padding in a huffman encoded value.  From reading the [spec](https://http2.github.io/http2-spec/compression.html#string.literal.representation), the last paragraph says that padding in excess of 7 bits is an error (rather than being ignored).

The problem here is that it should be an IOException instead of an Assert.

Finally, I don't see anywhere in the Spec that says 0 length values are not allowed, so I don't know why they are forbidden.   Did I just miss somewhere?

**Comment by normanmaurer** [comment]
@carl-mastrangelo good catch!

@nmittler @Scottmitch @jpinner WDYT ?

**Comment by carl-mastrangelo** [comment]
In case it matters, the Golang HPACK Decoder also treats the input as a zero length string, but I think that is a coding mistake; it should result in an error.  It isn't entirely clear to me what to do since the spec, netty, and Go all behave slightly differently.

**Comment by nmittler** [comment]
Agreed, `IOException` is more appropriate here.  @carl-mastrangelo do you want to send a PR?

**Comment by carl-mastrangelo** [comment]
Well, as I said, I am not entirely sure if my interpretation is right.  Zero length strings *are* allowed right?  Throwing an exception would make the situation better, but not compliant.  Does your reading of the spec match mine?

**Comment by Scottmitch** [comment]
@carl-mastrangelo -

I think we can reference the HTTP RFC in this case...

https://tools.ietf.org/html/rfc7230#section-3.2

> header-field   = field-name ":" OWS field-value OWS
field-name     = token

The definition for token is defined here ...
https://tools.ietf.org/html/rfc7230#section-3.2.6 (and here https://tools.ietf.org/html/rfc7230#appendix-B)

> token          = 1*tchar
 tchar          = "!" / "#" / "$" / "%" / "&" / "'" / "*"
                    / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~"
                    / DIGIT / ALPHA
                    ; any VCHAR, except delimiters

so it seems that a header name must have 1 or more characters.

**Comment by carl-mastrangelo** [comment]
@Scottmitch 

That is true for HTTP, but is it true for pure HPACK?  HPACK also allows binary values which http forbids.

**Comment by Scottmitch** [comment]
@carl-mastrangelo - I see your point. I don't see anywhere in HPACK that explicit forbids empty headers.  Perhaps it is more appropriate to modify the header validation code for the specific codecs. (e.g. [DefaultHttp2Headers.HTTP2_NAME_VALIDATOR](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2Headers.java#L37), [DefaultHttpHeaders.HttpNameValidator](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/DefaultHttpHeaders.java#L53), etc...).

@nmittler - WDYT?

**Comment by nmittler** [comment]
@Scottmitch SGTM

**Comment by Scottmitch** [comment]
i'll throw together a PR

**Comment by normanmaurer** [comment]
Thx!

**Comment by carl-mastrangelo** [comment]
FWIW I also filed this issue against [Golang](https://github.com/golang/go/issues/15614), and will probably be fixing the same bug there.

**Comment by carl-mastrangelo** [comment]
@Scottmitch  Are you sure that is the right change?  I think the problem is actually in overlong padding being accepted in https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/internal/hpack/HuffmanDecoder.java#L89

**Comment by Scottmitch** [comment]
@carl-mastrangelo - There may be multiple issues, we don't explicitly prohibit empty names in the http header validation. I will need to look more closely at the HPACK spec for the padding issue ... but in the mean time if you are confident about this and are comfortable submitting a PR please do :)

**Comment by carl-mastrangelo** [comment]
@Scottmitch You're PR is good, it just need to also reject bad Huffman encodings too.  I believe the only difference is checking that `bits` is <= 7 just before returning in the function I linked above.

**Comment by Scottmitch** [comment]
@carl-mastrangelo - I think there may be a bit more to it, but I have a PR pending for you to review.

**Comment by carl-mastrangelo** [comment]
@Scottmitch I think there are actually two issues rather than 1:  Name length validation in the layers above HPACK, and the treatment of padding inside of HPACK.  Your fix addresses the former, and is still needed.  I can submit a fix for the latter, since I am already in the process of doing so for.  

You should still submit your fix.  I don't see anything in my mailbox, did you mean you have a PR pending that needs review, or you are in the process of writing the PR?  Either way, let me know as soon as you are ready.

**Comment by Scottmitch** [comment]
> did you mean you have a PR pending that needs review

Yip. I think I have both covered ... stand by

**Comment by carl-mastrangelo** [comment]
@Scottmitch If it makes it any easier, the fix for the Go implementation (which is extremely similar to Netty's) is here:  https://go-review.googlesource.com/#/c/23067/

I also added a bunch of cases to their tests if you want to add them to your PR.

**Comment by Scottmitch** [comment]
@carl-mastrangelo - Thanks for the heads up ... seems like our fixes are very similar and I also added a few of tests ... there was actually already a test that was basically commented out :)
