### ISSUE TITLE
channel.attr(…) behaviour in Netty 4.1.0.CR7

### ISSUE THREAD

**Issue by evgenyvsmirnov** [netty/netty#5232]
Hi! Could you please comment on the following: as it is said [here](http://netty.io/wiki/new-and-noteworthy-in-4.1.html#channelhandlercontextattr--channelattr) ChannelHandlerContext.attr(…) == Channel.attr(…) since Netty 4.1. 

My application which uses channel attributes in order to share a data across all handlers of a pipeline (implemented originally with 4.0.28) started to fail after transition to 4.1.0.CR7. After a short research I found that sharable handlers access channel.attr(…) created from within other pipelines (and it seems that it is the the pipeline associated with the very first created channel). The issue was fixed by removal of Sharable annotation from such handlers. Is it a bug or feature of the new version?

Unfortunately can not provide you a test, but probably you can clarify or understand the issue with out it. Attributes are declared, placed and accessed in the following way:

```
static final AttributeKey<MyAttrType> MY_ATTR = AttributeKey.valueOf("myattr");
…
// First sharable handler
ctx.channel().attr(MY_ATTR).set(attrVal);
…
// Second sharable handler
ctx.channel().attr(MY_ATTR).get();

```

Thanks.

**Comment by normanmaurer** [comment]
@evgenyvsmirnov I'm not sure I understand correctly.. Do you say you can access attributes that belong to another `Channel` when the `ChannelHandler` is annotated with `@Sharable` ?

**Comment by evgenyvsmirnov** [comment]
Yes, exactly. If I work with my server (it is a http1.1 gateway) using two clients I see that channel created for the second one accesses and modifies data which belongs to channel created for the first one (using nio). And as I told before problem vanishes after removing sharable and creating separate handler instances for every channel.

**Comment by normanmaurer** [comment]
@evgenyvsmirnov interesting... let me have a look.

**Comment by normanmaurer** [comment]
@evgenyvsmirnov what you describe is not possible... The Attributes are stored in the Channel instance, are you really sure this is what happening ?

https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/DefaultAttributeMap.java

This one is extended by AbstractChannel.

Maybe you can point me to your code ?

**Comment by evgenyvsmirnov** [comment]
Unfortunately I can't. Let me make more experiments probably I'll be able to provide you more information or just close the issue. What is interesting – I can reproduce it in every test with two concurrent clients if I use the same instance of sharable handler for each pipeline and can't reproduce it if I create new sharable handlers for new clients. 

Scenario is quite ordinary for gateway: first handler creates connection to backing server and the second one transmits incoming chunks. Handlers are stateless – state (connection to destination server) is placed into channel attribute.

Is it possible that sharable handlers (which are singletons) use the only attrmap?

**Comment by evgenyvsmirnov** [comment]
So @normanmaurer since I can not provide more information right now and you are sure the described behaviour is impossible let us think its a propagated error. I will close the issue and create another one as soon as I can tell something new. Thank you for your attention.

**Comment by evgenyvsmirnov** [comment]
Hi @normanmaurer . I have additional information about the issue. In my case the problem occurs only with CombinedChannelDuplexHandlers.
See two versions of CCDH below. In both cases MyInboundHandler/MyOutboundHandler are stateless and access channel attributes. There was no such problem in 4.0.28. I have encountered it with 4.1.0.RC7 and it is still reproducible with 4.1.5.

Pipelines with such handler fail to process concurrent requests:
'''
/**
 * This version does not work
 */
@Sharable
class MyHandler extends CombinedChannelDuplexHandler<MyInboundHandler, MyOutboundHandler>
{
    private static final MyHandler INSTANCE = new MyHandler();
    
    static MyHandler getInstance()
    {
        return INSTANCE;
    }

    private MyHandler()
    {
        // MyInboundHandler and MyOutboundHandler are sharable and getInstance() returns the same instances.
        super(MyInboundHandler.getInstance(), MyOutboundHandler.getInstance());
    }
}
'''
when I remove @Sharable everything goes well:
'''
/**
 * This version works properly
 */
class MyHandler extends CombinedChannelDuplexHandler<MyInboundHandler, MyOutboundHandler>
{
    static MyHandler getInstance()
    {
        return new MyHandler();
    }

    private MyHandler()
    {
        // MyInboundHandler and MyOutboundHandler are still sharable and getInstance() returns the same instances.
        super(MyInboundHandler.getInstance(), MyOutboundHandler.getInstance());
    }
}
'''

**Comment by normanmaurer** [comment]
@evgenyvsmirnov sorry this totally dropped from my to do list... Do you still see the problem ?

**Comment by evgenyvsmirnov** [comment]
Hi @normanmaurer , no problem. I haven't checked it with 4.1.6 yet (but with 4.1.5 I have). I have isolated it and it doesn't look urgent anymore. If you don't have an idea what could happen between 4.0.28 and 4.1.0.CR7 I suggest postponing it until I'll be able to provide you a test. Thanks.

**Comment by normanmaurer** [comment]
@evgenyvsmirnov ok let me close this with `needs info` label
