### ISSUE TITLE
AbstractDerivedByteBuf.deallocate() method in Netty 4.1

### ISSUE THREAD

**Issue by evgenyvsmirnov** [netty/netty#5234]
Netty versions 4.1, 4.0.29

Context: AbstractDerivedByteBuf since 4.0.29 has «deallocate» method which is invoked after a backing ByteBuf is released. Same class in 4.1 (at least 4.1.0.CR7) doesn't have this method. Are you going to add it before the 4.1.0.Final release (I would like to use it in a subclass of ReadOnlyByteBuf)?

Thanks.

**Comment by normanmaurer** [comment]
@evgenyvsmirnov what you need it for ? Why not just use `release(...)` ?

**Comment by evgenyvsmirnov** [comment]
Need to bind additional actions with the moment when the bytebuf is released. Release in AbstractDerivedByteBuf is final so can not customise it.

**Comment by normanmaurer** [comment]
@evgenyvsmirnov actually `AbstractDerivedByteBuf ` is marked as `@Deprecated` in 4.1. So no we will not

**Comment by evgenyvsmirnov** [comment]
Now I see it in git. In CR7 released on 10.IV.2016 it was not deprecated. Thanks.
