### ISSUE TITLE
Memoryleak when using OpenSSL/netty-tcnative on openjdk7

### ISSUE THREAD

**Issue by floragunncom** [netty/netty#5235]
Using SSLHandler with OpenSSL provider and the following environment result in a MemoryLeak

* Ubuntu 12.04 / Linux amd64 3.13.0-86-generic
* Java Version: 1.7.0_95 Oracle Corporation
* JVM Impl.: 24.95-b01 Oracle Corporation OpenJDK 64-Bit Server VM
* netty-tcnative-1.1.33.Fork15-linux-x86_64
* Netty 4.0.36
* OpenSSL 1.0.1 14 Mar 2012

With other JVM like the following one its working without any problems:
* Java Version: 1.8.0_91 Oracle Corporation/JVM Impl.: 25.91-b14 Oracle Corporation OpenJDK 64-Bit Server VM
* Java Version: 1.8.0_45-internal Oracle Corporation/JVM Impl.: 25.45-b02 Oracle Corporation OpenJDK 64-Bit Server VM
* Java Version: 1.8.0_66 Oracle Corporation/JVM Impl.: 25.66-b17 Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
* Java Version: 1.7.0_80 Oracle Corporation/JVM Impl.: 24.80-b11 Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
* Java Version: 1.8.0_40 Oracle Corporation/JVM Impl.: 25.40-b25 Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
* Java Version: 1.7.0_91 Oracle Corporation/JVM Impl.: 24.91-b01 Oracle Corporation OpenJDK 64-Bit Server VM

**Comment by normanmaurer** [comment]
@floragunncom a native memory leak or heap memory leak ? Also do you have a heap dump for us ?

**Comment by floragunncom** [comment]
Sorry, can't get a heap dump out of my CI container. But after more investigation it seems that leak was introduced with netty-tcnative 1.1.33.Fork12. 1.1.33.Fork11 does use (in my use case) 8 time less memory than Fork12. It seems is not really a leak (in terms of memory grows an get not garbage collected) but i can say that i see Fork12 (and newer) uses 8 times more memory than Fork11. Looking into that with jprofiler i don't see big differences so i assume its native memory which gets excessivly increased.

**Comment by normanmaurer** [comment]
@floragunncom thats interesting... I will check if I can spot something. So you say it is native memory but is also freed later on ?

**Comment by normanmaurer** [comment]
@floragunncom also this is only true with the specific java version that you told be fore or does it happen with all of them ?

**Comment by floragunncom** [comment]
need to investigate futher, report back tomorrow

**Comment by normanmaurer** [comment]
Thx!

**Comment by normanmaurer** [comment]
@floragunncom also what you report is strange I just reviewed all the changes in tcnative between Fork11 and Fork12 and I can not find anything that could produce something like that. Could you provide a way to reproduce this ?

**Comment by floragunncom** [comment]
I cannot provide a reproducer for this and it seems the issue is indeed not related to 1.1.33.Fork12 (seems this was a misacception, sorry for that). What remains is that i see high memory footprint in very specific circumstances when OpenSSL is used. For Java-only SSL there are no such problems.

In general: Should the memory footprint of netty/SSLHandler with OpenSSL compared to Java-only SSL be considered to more or less even? Or is it expected that OpenSSL variant result in more memory will be used?

**Comment by normanmaurer** [comment]
@floragunncom the context may take more memory. Do we talk about per `SSLEngine` instance memory  here ?

**Comment by normanmaurer** [comment]
@floragunncom ping

**Comment by floragunncom** [comment]
yes, think we talk about ``SSLEngine instance memory``. This is a really strange thing here, maybe its somehow related to when java is running within a docker container. Will try to provide a reproducer ...

**Comment by normanmaurer** [comment]
Thx

**Comment by floragunncom** [comment]
this should reproduce it https://github.com/floragunncom/netty-memleak

**Comment by normanmaurer** [comment]
Will check soon

**Comment by normanmaurer** [comment]
@floragunncom so from the README are you saying that the problem is "bigger" with 3.x compared to 4.x ?

**Comment by floragunncom** [comment]
looks like that.

We do a little bit uncommons things which should however work:
Netty version is 3.10.5 but the SSLHandler gets a SSLEngine constructed by Netty 4.0.36

**Comment by normanmaurer** [comment]
@floragunncom so how you detected the leak ? Will it just OOME at some point ?

**Comment by floragunncom** [comment]
if you watch the memory the java process took (with 'top' or similar) it does only increase (never decrease) and then there is a OOME some point in time. I see also that this is not heap problem (heap looks fine and gets gc'ed from time to time) - so i assume it native memory which gets not freed.

**Comment by normanmaurer** [comment]
@floragunncom I now running the netty 4 only version for more then 4 hours... no leak visible. Are you sure its there as well ?

**Comment by floragunncom** [comment]
what about netty3+4 version?

**Comment by normanmaurer** [comment]
No leak so far... running for 4 hours.

**Comment by normanmaurer** [comment]
@floragunncom ping ...

**Comment by floragunncom** [comment]
With 4.0.38 and Fork18 it looks now much better so i think we can close it.

**Comment by metalvins** [comment]
Hello @floragunncom @normanmaurer ,
I am seeing a similar issue to this one, but the openssl version is different. However, I use similar setup Netty 3 with SSL handler built on Netty 4.
@floragunncom Can you please share what the issue was and how you resolved it?
Was it related to the discrepancy between the Netty version and SSLHandler Netty version?
@normanmaurer any additional info related to this problem?

Thanks,
Vinesh
