### ISSUE TITLE
Why does clearing a ByteBuf cause it to be reference collected?

### ISSUE THREAD

**Issue by Jire** [netty/netty#5237]
Why does clearing a `ByteBuf` cause it to be reference collected?

In `ByteBuffer`, clearing allows me to reuse the same buffer by essentially resetting its index. I wish to do the same with Netty's `ByteBuf`.

**Comment by Scottmitch** [comment]
@Jire - can you clarify what you are talking about when you say `clearing a ByteBuf cause it to be reference collected`?

[ByteBuf.clear()](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/ByteBuf.java#L445) does not release the `ByteBuf`.

**Comment by Jire** [comment]
@Scottmitch Sorry I am mistaken. I believe it is write/writeAndFlush that releases the buf, then my subsequent clear call throws ala ref count is 0 error.

**Comment by Jire** [comment]
Yes, retaining before write works. Code used here if anybody is interested: https://github.com/Jire/Acelta/blob/master/src/main/kotlin/com/acelta/net/Session.kt

**Comment by Scottmitch** [comment]
Yes retaining will avoid getting an exception in this case. However make sure you understand the following:

1. lifetime of the `content()`, and the responsibility to release (and re-use) is clear. Checkout http://netty.io/wiki/reference-counted-objects.html.
2. If you clear the indexes before the buffer is actually written (the write operation is asynchronous) ... then your data will not actually be written. See [ByteBuf.slice](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/ByteBuf.java#L2061) and [ByteBuf.duplicate](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/ByteBuf.java#L2086) which will ensure the ByteBuf that is written will have its own indexes.
