### ISSUE TITLE
CI server not reachable

### ISSUE THREAD

**Issue by floragunncom** [netty/netty#5238]
The CI server http://clinker.netty.io/jenkins/view/TCNative/ which is mentioned in http://netty.io/wiki/forked-tomcat-native.html is not reachable (at least not for me)

**Comment by Scottmitch** [comment]
try https://garage.netty.io/teamcity/

**Comment by Scottmitch** [comment]
wiki updated

**Comment by floragunncom** [comment]
thx, but looking for apr build for windows (originally here http://clinker.netty.io/jenkins/job/apr-windows/lastSuccessfulBuild/artifact/dist/bin/). Any ideas where i can find this now?

**Comment by Scottmitch** [comment]
I'm not sure if we have a job which independently builds this any more (@nmittler @normanmaurer?)

However we build and deploy tcnative in a standalone static library now.

**Comment by normanmaurer** [comment]
Yeah we not have it anymore... Let me update the docs
