### ISSUE TITLE
http2 cleartext server example not working

### ISSUE THREAD

**Issue by ayanamist** [netty/netty#5239]
I tested 3 server examples under https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/http2
`./run-example.sh http2-server|http2-tiles|http2-multiplex-server`
None of them works correctly with `nghttp` (pure h2) or `curl --http2` (http1.1 upgrade to h2) to provide h2c service.
Does it matter?

**Comment by normanmaurer** [comment]
@Scottmitch @nmittler can you have a look

**Comment by normanmaurer** [comment]
@nmittler ping

**Comment by nmittler** [comment]
Just tried nghttp and this is what I'm seeing in the netty example server:

```
java.lang.NullPointerException: name
	at io.netty.channel.AbstractChannelHandlerContext.<init>(AbstractChannelHandlerContext.java:80)
	at io.netty.channel.DefaultChannelHandlerContext.<init>(DefaultChannelHandlerContext.java:26)
	at io.netty.channel.DefaultChannelPipeline.newContext(DefaultChannelPipeline.java:111)
	at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:312)
	at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:297)
	at io.netty.handler.codec.http2.Http2ServerUpgradeCodec.upgradeTo(Http2ServerUpgradeCodec.java:136)
	at io.netty.handler.codec.http.HttpServerUpgradeHandler$1.operationComplete(HttpServerUpgradeHandler.java:325)
	at io.netty.handler.codec.http.HttpServerUpgradeHandler$1.operationComplete(HttpServerUpgradeHandler.java:318)
```

It seems that something may have broken WRT allowing null names.

@normanmaurer Any ideas?

**Comment by normanmaurer** [comment]
@nmittler yep will fix...

**Comment by nmittler** [comment]
SGTM ... thanks @normanmaurer!

**Comment by normanmaurer** [comment]
https://github.com/netty/netty/pull/5298

**Comment by normanmaurer** [comment]
Fixed via https://github.com/netty/netty/pull/5298

**Comment by normanmaurer** [comment]
@nmittler @ayanamist can you try again ?

**Comment by ayanamist** [comment]
I test with 2618c2a6
Still not work with nghttp

**Comment by normanmaurer** [comment]
Can you give me the exact steps to reproduce?

**Comment by ayanamist** [comment]
I modify pom.xml to loosen enforcer rules which force me to use centos.
![2016-05-24_163207](https://cloud.githubusercontent.com/assets/406779/15497461/70b35b04-21cd-11e6-97e3-eff0317b31ef.png)

**Comment by nmittler** [comment]
Hmm ... it's working for me with the latest 4.1 branch (thanks, @normanmaurer!).

Server:
`./run-example.sh http2-server`

Client:
```
nghttp -v -u -H':method:GET' http://localhost:8080/whatever
[  0.000] Connected
[  0.000] HTTP Upgrade request
GET /whatever HTTP/1.1
host: localhost:8080
connection: Upgrade, HTTP2-Settings
upgrade: h2c
http2-settings: AAMAAABkAAQAAP__
accept: */*
user-agent: nghttp2/1.11.0-DEV


[  0.133] HTTP Upgrade response
HTTP/1.1 101 Switching Protocols
connection: upgrade
upgrade: h2c
content-length: 0


[  0.133] HTTP Upgrade success
[  0.133] send SETTINGS frame <length=12, flags=0x00, stream_id=0>
          (niv=2)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):65535]
[  0.133] send PRIORITY frame <length=5, flags=0x00, stream_id=3>
          (dep_stream_id=0, weight=201, exclusive=0)
[  0.133] send PRIORITY frame <length=5, flags=0x00, stream_id=5>
          (dep_stream_id=0, weight=101, exclusive=0)
[  0.133] send PRIORITY frame <length=5, flags=0x00, stream_id=7>
          (dep_stream_id=0, weight=1, exclusive=0)
[  0.133] send PRIORITY frame <length=5, flags=0x00, stream_id=9>
          (dep_stream_id=7, weight=1, exclusive=0)
[  0.133] send PRIORITY frame <length=5, flags=0x00, stream_id=11>
          (dep_stream_id=3, weight=1, exclusive=0)
[  0.133] send PRIORITY frame <length=5, flags=0x00, stream_id=1>
          (dep_stream_id=11, weight=16, exclusive=0)
[  0.146] recv SETTINGS frame <length=0, flags=0x00, stream_id=0>
          (niv=0)
[  0.146] recv (stream_id=1) :status: 200
[  0.146] recv (stream_id=1) http-to-http2-upgrade: true
[  0.146] recv HEADERS frame <length=27, flags=0x25, stream_id=1>
          ; END_STREAM | END_HEADERS | PRIORITY
          (padlen=0, dep_stream_id=0, weight=16, exclusive=0)
          ; First response header
[  0.146] send GOAWAY frame <length=8, flags=0x00, stream_id=0>
          (last_stream_id=0, error_code=NO_ERROR(0x00), opaque_data(0)=[])
```

What version of Netty are you using?

**Comment by ayanamist** [comment]
@nmittler i use 2618c2a which is shown both in above comments and in the screenshot `git rev-parse HEAD`
I find that, i use `nghttp -v http://127.0.0.1/` which does not do upgrade request (no HTTP/1.1 request) and fail, you use `nghttp -u -v http://127.0.0.1/` which will do upgrade request, so it succeeds.
I use netty to build a RPC server like gRPC, so upgrade request is useless, and i see that example code is intended to support this simple h2c situation (the screenshot shows log `Directly talking: HTTP/2.0 (no upgrade was attempted)`）

**Comment by nmittler** [comment]
@ayanamist ok, I had misunderstood what you were trying to do. So you want to talk [HTTP/2 directly, without an upgrade] (http://httpwg.org/specs/rfc7540.html#known-http). Our examples don't support that currently.

@trustin IIRC you had brought this up a while back. Did we ever implement a way to support both direct HTTP/2 as well as HTTP 1->2 upgrade?

**Comment by Scottmitch** [comment]
@nmittler - I don't think there has been any movement on this yet https://github.com/netty/netty/issues/4210#issuecomment-204098033
