### ISSUE TITLE
JVM crashed in io.netty.util.internal.PlatformDependent#getByte

### ISSUE THREAD

**Issue by SerCeMan** [netty/netty#5257]
Hi!

* Netty version 4.1.0.Beta8
* It has happened only once
* JDK: 1.8.0_72-b15

All the relevant information in hs_err log
[hs_err_pid13125.txt](https://github.com/netty/netty/files/263060/hs_err_pid13125.txt)

**Comment by normanmaurer** [comment]
@SerCeMan this was fixed... Please upgrade to 4.1.0.CR7
