### ISSUE TITLE
Rename Netty project to "Netty McNetface"

### ISSUE THREAD

**Issue by nmittler** [netty/netty#5263]
@trustin @normanmaurer @Scottmitch @louiscryan  @ejona86 @carl-mastrangelo @buchgr :)

**Comment by trustin** [comment]
!?

**Comment by Scottmitch** [comment]
Happy Friday :beers: (unless @nmittler 's account was hacked)

**Comment by nmittler** [comment]
I say this issue can't be closed until @trustin gets the joke! :stuck_out_tongue_closed_eyes:

**Comment by fbettag** [comment]
lol

**Comment by trustin** [comment]
Noooooo! Please explain :-)

**Comment by nmittler** [comment]
Ha!

Here's the origin: http://www.nytimes.com/2016/03/22/world/europe/boaty-mcboatface-what-you-get-when-you-let-the-internet-decide.html?_r=0

And then Google's contribution: http://www.androidauthority.com/google-parsey-mcparseface-open-source-692352/

:)

**Comment by CodingFabian** [comment]
comes right in time before 4.1 ships. i think this justifies a new rc.

**Comment by trustin** [comment]
[![LGTM](http://lgtm.in/p/qJaaDdxOp)](http://lgtm.in/i/qJaaDdxOp)
