### ISSUE TITLE
IdleStateHandler does not account for voidPromise

### ISSUE THREAD

**Issue by maseev** [netty/netty#5264]
Netty version: 4.1.0.CR7

Context:
I'm trying to use `ctx.write(msg, ctx.voidPromise());` approach in order to avoid creating unnecessary objects. It's not working because I have IdleStateHandler in my pipeline.
Placing IdleStateHandler in the pipeline makes using `ctx.voidPromise `in `ctx.write` method absolutely useless because of [this](https://github.com/netty/netty/blob/89eae94542ae3d522a78e1f8b0172782c9786901/handler/src/main/java/io/netty/handler/timeout/IdleStateHandler.java#L282) piece of code that 'unvoid' void promise by creating an object.

**Comment by normanmaurer** [comment]
That is expected and there is nothing we can do about it. As a void promise not allows to add listeners to the promise

**Comment by maseev** [comment]
This 'expected behaviour' should be mentioned in the IdleStateHandler's documentation. How is anyone supposed to know that their `ctx.voidPromise()` won't make any difference in terms of generated garbage?
By the way, IdleStateHandler causes an exception to be thrown in Netty 4.0.36.Final, because somebody [decided](https://github.com/netty/netty/blob/4.0/handler/src/main/java/io/netty/handler/timeout/IdleStateHandler.java#L282) it would be a good idea to attach a listener to the void promise.
Please, stop closing issue until the problem is really solved.

**Comment by Scottmitch** [comment]
@maseev - Void promise can be tricky as it requires multiple layers to account for it ... would you be interested in submitting a PR to clarify docs and fix this issue you discovered?

**Comment by maseev** [comment]
@Scottmitch Ok, no problem. I'll submit a PR a little bit later.

**Comment by normanmaurer** [comment]
Thx a lot!
