### ISSUE TITLE
Connection reset exception then netty's buffer's content lost

### ISSUE THREAD

**Issue by longlong524** [netty/netty#5271]
Version:5.0.0.Alpha2
 
I write a httpclient with netty. If I disconnect network then  connection reset exception happens and netty's channel become  inactive and the data in the channel's buffer lost. I use wireshark to confirm data has arrived my conputer.
 Is this right? How can I received the lost data when  connection reset exception happens and channel inactive?

**Comment by normanmaurer** [comment]
Please use 4.1.0.CR7 and let us know if you still see the issue there.
