### ISSUE TITLE
NioServerSocketChannel.doReadMessages() creates a NioSocketChannel instance ignoring user ChannelOptions

### ISSUE THREAD

**Issue by codekrolik** [netty/netty#5276]
**NioServerSocketChannel.doReadMessages()** creates a NioSocketChannel instance ignoring user-defined ChannelOptions.

*ServerBootstrap* and *Bootstrap* classes create channels by calling *AbstractBootstrap.initAndRegister()* method.
Methods like *Bootstrap.connect()* and *ServerBootstrap.bind()* call method *AbstractBootstrap.initAndRegister() - AbstractBootstrap.init()* which ends up setting user-defined channel config options, e.g. custom ALLOCATOR.

Although that happens for client channel (*Bootstrap.connect()*) and server listening channel (*ServerBootstrap.bind()*), when a server accepts a connection method **NioServerSocketChannel.doReadMessages()** is triggered, and this method just creates a new *NioSocketChannel* without making any changes to it's Channel config. As a result, this new channel's options will be **always default**, and all user settings will be completely ignored.

That makes it impossible, for example, to set a custom buffer allocator, because in spite of the fact that *NioServerSocketChannel* itself will have the correct allocator set by *ServerBootstrap.initAndRegister()*, channels on server will be created using the faulty **NioServerSocketChannel.doReadMessages()** method, and will always have the default allocator attached.
That holds for any other *ChannelOption*. The entire options configuration of those channels will be always default, no matter what a user sets.

**Comment by taojiaenx** [comment]
Have you configured the channel by this way ? 
serverBootstarp = new ServerBootstrap()
				.group(bossGroup, workerGroup)
				.channel(EpollServerSocketChannel.class)
				.option(ChannelOption.SO_TIMEOUT, sockTimout)
				.option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
				.option(ChannelOption.TCP_NODELAY, true)
				.childOption(ChannelOption.ALLOCATOR,
						PooledByteBufAllocator.DEFAULT)
				.childOption(ChannelOption.TCP_NODELAY, true)
				.childHandler(pushListenerChannelInitializer);

**Comment by normanmaurer** [comment]
@codekrolik as @taojiaenx you need to use `childOption(...)` to configure the accepted channels.
