### ISSUE TITLE
Feature request: Optimized versions of LengthFieldBasedFrameDecoder and FixedLengthFrameDecoder

### ISSUE THREAD

**Issue by maseev** [netty/netty#5280]
Netty version: 4.1.0.CR7.

Context:
It turns out that `LengthFieldBasedFrameDecoder` and `FixedLengthFrameDecoder` produce quite a lot of garbage by creating ByteBuf per message. This is especially true in the context where the client sends data at a very high-speed rate. As a result, we've got a lot of GC pauses which significantly drop throughput and increase latency.

Instead of slicing an incoming chunk of data per message, I suggest batching this chunk and slice only in case it contains N messages. By doing so we could reduce excessive object allocation, and as a result of that reduce GC pauses. 

Instead of processing a ByteBuf that contains only one message, we could pass a ByteBuf that contains N messages and do something like this in order to process a chunk of data:

```java
while (chunk.isReadable()) {
  // read from chunk data for one message
}
```

I created a simple [echo server](https://github.com/maseev/echo) which demonstrates this approach.
You can run EchoServer with `-Doptimized=true` (it's false by default) in order to activate the optimized version of `FixedLengthFrameDecoder` (implemented as a `ChannelInboundHandlerAdapter` at the moment).

Here are some numbers:

Non-optmized version (throughput):
![non_optimized_throughput](https://cloud.githubusercontent.com/assets/3434800/15422571/15d7f56c-1e9b-11e6-85ce-7333468f6e60.png)
Optimized version (throughput):
![optmized_throughput](https://cloud.githubusercontent.com/assets/3434800/15422579/1ceda2ca-1e9b-11e6-8c13-4291f57b103e.png)
Non-optimized version (runtime responsiveness):
![non_optimized](https://cloud.githubusercontent.com/assets/3434800/15422587/2341d204-1e9b-11e6-8dc8-ee38ff599a1e.png)
Optimized version (runtime responsiveness):
![optimized](https://cloud.githubusercontent.com/assets/3434800/15422590/26ccc2f8-1e9b-11e6-9b73-d7331229a80d.png)
Runtime responsiveness (optimized and non-optimized versions):
![both](https://cloud.githubusercontent.com/assets/3434800/15422607/2f2a26ac-1e9b-11e6-9c44-b63879484e28.png)

It would be great to have additional frame decoders optimized for this particular use case.

**Comment by normanmaurer** [comment]
@maseev I think you should try latest 4.1 branch and see how it behaves as we now also pool Slices if you use the PooledByteBufAllocator here.

**Comment by maseev** [comment]
@normanmaurer I just tried latest 4.1 branch. GC's started working less frequently, but throughput didn't change at all. I can see from YouKit profiler that writing to the channel is performing in the very small chunks (around 100kb), whereas in optimized mode I'm able to send up to 300-400kb per call. It seems there's a some limitation that relates to how many times `channelRead` can be called.

**Comment by normanmaurer** [comment]
@maseev maybe you want to send a PR which implements an "optimised" `LengthFieldBasedFrameDecoder` and `FixedLengthFrameDecoder` ?

**Comment by maseev** [comment]
@normanmaurer I would love to. But I'd like to make sure that I'm not missing anything important. I mean, maybe I somehow misused Netty's frame decoder or something? The only thing I did is added FixedLenghtFrameDecoder which turned out to cause the major throughput drop.
I'll definitely send a PR when I have more free time. :disappointed:

**Comment by maseev** [comment]
@normanmaurer Finally found some free time to work on this issue. I've just made an interesting observation. It turns out that you can speed things up 'a little bit' by doing batching yourself rather than using ` ctx.write + ctx.flush` approach. Here's what I found out:

- You can use the `ctx.write + ctx.flush` approach that I mentioned earlier by doing something like [this](https://github.com/maseev/echo/blob/master/src/main/java/io/github/maseev/echo/server/DummyEchoServerHandler.java). You write a message through the `ctx.write` in the `channelRead` method and flush all written messages in `channelReadComplete`. Here's a network throughput chart:

![dummy](https://cloud.githubusercontent.com/assets/3434800/15611258/61283b48-244b-11e6-82ee-c8035b3d9661.png)

It turns out, that by using this approach, `ctx.channel().isWritable()` starts returning false pretty quickly.

- You can speed things up by doing batching [yourself](https://github.com/maseev/echo/blob/master/src/main/java/io/github/maseev/echo/server/BatchingEchoServerHandler.java). This approach provides much better throughput:

![batching](https://cloud.githubusercontent.com/assets/3434800/15611354/cd9eebaa-244b-11e6-8e27-5d81982602de.png)

- You can also combine `FixedLengthFrameDecoder` and writing/flushing in one [handler](https://github.com/maseev/echo/blob/master/src/main/java/io/github/maseev/echo/server/HighPerformanceEchoServerHandler.java). This particular approach gives the fastest throughput. It also reduces GC pauses to the minimum (probably one GC STW event every minute or so).

![optimised](https://cloud.githubusercontent.com/assets/3434800/15611497/6137eb78-244c-11e6-9a84-495ba8b1fe09.png)

I'm a little surprised by these results. I thought that by using the first approach I would be able to achieve almost the same results as in the second. Anyway, the [HighPerformanceEchoServerHandler](https://github.com/maseev/echo/blob/master/src/main/java/io/github/maseev/echo/server/HighPerformanceEchoServerHandler.java) provides the fastest solution that I was able to think of.

WDYT?

**Comment by johnou** [comment]
I don't think your handler can be Sharable with that buffer bytebuf.

**Comment by maseev** [comment]
@johnou You're right, it can't. Neither [LengthFieldBasedFrameDecoder](https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/LengthFieldBasedFrameDecoder.java) nor [FixedLengthFrameDecoder](https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/FixedLengthFrameDecoder.java) can be shareble because [ByteToMessageDecoder](https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java#L63) contains state. `ByteToMessageDecoder` clearly states that fact in the javadoc.
