### ISSUE TITLE
Why are ArrayList$Itr created when write and flushing to a channel?

### ISSUE THREAD

**Issue by Jire** [netty/netty#5292]
It seems `ArrayList$Itr` are created whenever I use `writeAndFlush` on a channel. I even pass in channel's `voidPromise`. There are also `MpscLinkedQueue$DefaultNode` that are created.

How can I avoid this?

Screenshot from VisualVM profiler: http://i.imgur.com/jkb2gGL.png

**Comment by normanmaurer** [comment]
Can you share the profiler snapshot?

**Comment by Jire** [comment]
@normanmaurer Here is the VisualVM memory profiler snapshot: https://www.dropbox.com/s/s3brzn2zepsch6l/snapshot.xml?dl=0

**Comment by normanmaurer** [comment]
@Jire hmmm... this is a .xml ? Shouldn't this be .nps or such ?

**Comment by Jire** [comment]
@normanmaurer Sorry, here is an nps: https://www.dropbox.com/s/izk54wt7oz8wgvt/profile.nps?dl=0

**Comment by normanmaurer** [comment]
@Jire hmmm... how can I see what holds the references of the ArrayList$itr ? Can you maybe just take a heap dump and share it so I can use yourkit or mat for this ?

**Comment by Jire** [comment]
@normanmaurer First time using YourKit, here is a memory snapshot (.snapshot): https://www.dropbox.com/s/gsrjinl6uqr2vqy/Acelta-2016-05-21%281%29.snapshot?dl=0

And here is the memory snapshot idiom (.idiom): https://www.dropbox.com/s/hhwub7uuflov0z2/Acelta-2016-05-21%281%29.snapshot.idom?dl=0

**Comment by normanmaurer** [comment]
@Jire you need to enable allocation recording so I can see where stuff is allocated:
https://www.yourkit.com/docs/java/help/allocations.jsp

**Comment by Jire** [comment]
@normanmaurer I noticed that in the stable Netty version the problem is significantly less. With 4.1.0.CR7 there are a lot of `MpscLinkedQueue$DefaultNode`. Also, lowering the amount of threads for `NioEventLoopGroup` significantly helps write/flush speeds.

https://www.dropbox.com/s/jucpptg530grqoc/Acelta-2016-05-21%288%29.snapshot?dl=0
https://www.dropbox.com/s/d29krolf5dm5xtx/Acelta-2016-05-21%288%29.snapshot.idom?dl=0

**Comment by normanmaurer** [comment]
Can you share a reproducer?

**Comment by Jire** [comment]
@normanmaurer My actual project is: https://github.com/Jire/Acelta

But I have written a minimal version in Java for your team: https://github.com/Jire/NettyExample

**Comment by normanmaurer** [comment]
@Jire can you hop of irc and ping me... irc.freenode #netty

**Comment by Jire** [comment]
@normanmaurer Yes, what's your nickname?

**Comment by normanmaurer** [comment]
This was fixed in 4.1.0.Final snapshot and the Itr stuff was created by java.util.logging

**Comment by Jire** [comment]
@normanmaurer Thank you for all the help, cheers!!

**Comment by normanmaurer** [comment]
No worries :)
