### ISSUE TITLE
configurable ChannelConfig for EmbeddedChannel

### ISSUE THREAD

**Issue by dschobel** [netty/netty#5294]
Hi, I'd like configure `EmbeddedChannel` instances directly to configure their `ChannelConfig` byte buf allocator instances. Currently I'm  using the ` io.netty.allocator.type` system property but that won't let me vary the allocator type between distinct clients and server when they run in the same VM since the `DefaultChannelConfig` evaluates the static `ByteBufUtil.DEFAULT_ALLOCATOR` to pick between a pooled or unpooled instance.

Is there api I'm overlooking that allows this or if not, would you be interested in a PR that adds it?

context: I'm looking at netty 4.1.CR7

**Comment by normanmaurer** [comment]
Why not using Channel.config().setOption(....) ?

**Comment by dschobel** [comment]
Ah, I didn't realize I could modify the allocator after the channel is created, thanks for the pointer!

A follow up question, the reason I'm asking about allocator configuration of `EmbeddedChannel` is because I found the `HttpContentCompressor` handler allocating pooled byte buffers when I installed it in a server pipeline where the bootstrap was configured with the unpooled allocator. 

The source of the pooled allocations is a `ZlibEncoder` handler using the allocator in the `EmbeddedChannel`'s channel context which uses the `ByteBufUtil.DEFAULT_ALLOCATOR`.

It seems like `HttpContentCompressor` could pass the allocator configuration of its `ChannelContext` to the `EmbeddedChannel`s it produces so that if the server wants to be unpooled, all allocations are consistently unpooled and vice versa. Is there a reason that wasn't done?

**Comment by normanmaurer** [comment]
Nope thats a bug.... Can you provide a fix?

**Comment by normanmaurer** [comment]
Let me fix this here and in some other places.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5311
