### ISSUE TITLE
ThreadPerChannelEventLoopGroup protected constructor

### ISSUE THREAD

**Issue by kfallah** [netty/netty#5295]
Hello, 

I apologize if I am doing this wrong but I could not find any resources online. I am trying to use ThreadPerChannelEventLoop instances for my workerGroup and tried this:

`EventLoopGroup workerGroup = new ThreadPerChannelEventLoopGroup(100);`

Since ThreadPerChannelEventLoopGroup has all its constructors as protected, this is not possible.

Thanks,
Kion

**Comment by trustin** [comment]
`ThreadPerChannelEventLoopGroup` is not meant to be used directly. What are you trying to achieve exactly?

**Comment by kfallah** [comment]
I'm trying to get each client to have its own thread.
