### ISSUE TITLE
WriteTimeoutHandler does not work as stated

### ISSUE THREAD

**Issue by xiaoshuang-lu** [netty/netty#5296]
The code hints that if there are no write operations this handler will never issue WriteTimeoutException.

In fact, this handler has the similar functionality like socket option SO_SNDTIMEO.

It is far away from "Raises a WriteTimeoutException when no data was written within a certain period of time".

**Comment by windie** [comment]
The doc was fixed in #4631. It should be `Raises a WriteTimeoutException when a write operation cannot finish in a certain period of time.`

**Comment by xiaoshuang-lu** [comment]
Hi windie, thanks for your comments.

From my perspective, it is not a good idea to revise the doc because users will be confused if ReadTimeoutHandler and WriteTimeoutHandler have different meaning.

Why not offer a WriteTimeoutHandler that will raise a WriteTimeoutException when no data was written within a certain period of time?

**Comment by windie** [comment]
Acutally, what you are looking for is IdleStateHandler. The ReadTimeoutHandler doc is wrong too. I'm working on fixing it.

**Comment by xiaoshuang-lu** [comment]
"The ReadTimeoutHandler doc is wrong too." I am afraid not. The code indicates that functionality is compliant with doc.

**Comment by windie** [comment]
@xiaoshuang-lu you are right. I was wrong about `ReadTimeoutHandler`. ReadTimeoutHandler does what the doc says. So nothing needs to be fixed :).

**Comment by windie** [comment]
Closing since the doc has been fixed in #4631

**Comment by xiaoshuang-lu** [comment]
This issue was not fixed.

**Comment by windie** [comment]
The behavior you want has been implemented in `IdleStateHandler`. I don't see any strong reason why we need to duplicate the same feature in `WriteTimeoutHandler`.

Secondly, `WriteTimeoutHandler` is a public API so we cannot change its behavior right now as it will break existing applications. Some applications may depend on the current behavior.

Since there is nothing to do, I just closed it.

**Comment by xiaoshuang-lu** [comment]
Why we need to duplicate the same feature in ReadTimeoutHandler?

**Comment by windie** [comment]
> Why we need to duplicate the same feature in ReadTimeoutHandler?

`ReadTimeoutHandler` was added before `IdleStateHandler`.

@normanmaurer - What do you think that deprecating `ReadTimeoutHandler`?

**Comment by normanmaurer** [comment]
@windie actually I think we could even mark `ReadTimeoutHandler` and `WriteTimeoutHandler` `@deprecated`. @Scottmitch @trustin WDYT ?

**Comment by Scottmitch** [comment]
@normanmaurer - I'm fine with deprecating both ... seems like `IdleStateHandler` can be used for either or both use cases.

**Comment by windie** [comment]
See #5399

**Comment by normanmaurer** [comment]
I think we can close this as  #5399 was merged
