### ISSUE TITLE
Http2ConnectionHandler always sends GO_AWAY when channel is closed

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#5307]
If the channel is active `Http2ConnectionHandler` will always send a GO_AWAY when the channel is closed. This may be unnecessary, and even confusing to the remote peer, if the local peer is attempting to do a [graceful shutdown](https://tools.ietf.org/html/rfc7540#section-6.8). For example if the local peer manually sends a GO_AWAY to indicate the connection is closing with some `Additional Debug Data` to indicate why, they may also want to send that same debug data in the next GO_AWAY message which carries the real `Last-Stream-ID`. Currently the `Http2ConnectionHandler` will always send a GO_AWAY with empty `Additional Debug Data` when the channel is closing.

One approach to give the user more control is if a GO_AWAY has already been sent when `Http2ConnectionHandler` close's method is called, then we don't send a GO_AWAY, but instead just wait for all the streams to close.

**Comment by Scottmitch** [comment]
@nmittler @ejona86 - WDYT?

**Comment by nmittler** [comment]
@Scottmitch Yeah I think that seems reasonable. I suspect we'll want to set some sort of timeout on how long we wait for all of the streams to close before sending a `hard` `GOAWAY` and just closing the connection. Having all of this "pluggable" in some way might be handy.

**Comment by ejona86** [comment]
@Scottmitch SGTM

**Comment by Scottmitch** [comment]
> I suspect we'll want to set some sort of timeout on how long we wait for all of the streams to close before sending a hard GOAWAY

When close is called we already have a timeout mechanism [gracefulShutdownTimeoutMillis](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L73) which attempts to wait for all streams to be closed before the connection is actually closed. Can you clarify if you think we need more than this?

**Comment by nmittler** [comment]
@Scottmitch ah right, I had forgotten about that :).  SGTM
