### ISSUE TITLE
 java.lang.management Missing on Android

### ISSUE THREAD

**Issue by geri-m** [netty/netty#5317]
Netty version: netty-all 4.1.0-final 

Context:
Using netty-all 4.1.0-final  on Android (SDK Level 23) causes an Issue when compiling the project. io.netty.build.junit.TimedOutTestsListener requires  java.lang.management which is not present on Android. (RC5 worked fine). This requires a workaround in lint, which makes it more complext to use. 

Steps to reproduce:
1. add to dependencies of an Android Project in the gradle file
dependencies {
....
    compile 'io.netty:netty-all:4.1.0.Final'
...
}
2. gradle clean
3. gradle build

$ java -version
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

Operating system: OSX 

$ uname -a
Darwin 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64

**Comment by windie** [comment]
@geri-m Thanks for reporting it. I submitted #5318 to fix it. You can just exclude all classes in `io.netty.build` right now.

**Comment by windie** [comment]
Fixed in #5318.
