### ISSUE TITLE
WrappedByteBuf

### ISSUE THREAD

**Issue by ensirius** [netty/netty#5331]
Using 5.0 alpha version i was extending WrappedByteBuf to add methods that i offten use for write  or read. For example:

```
    public void writeUUID(UUID uuid) {
        writeLong(uuid.getMostSignificantBits());
        writeLong(uuid.getLeastSignificantBits());
    }
```

After downgrading to 4.1 this class now private. I would like to not write boilerplate or use static helper. Please make it public.

**Comment by normanmaurer** [comment]
@ensirius why not just have static helper methods ?

**Comment by ensirius** [comment]
@normanmaurer Because it's much cleaner and understandable. 

```java
    @Override
    public void write(PacketBuffer buffer) {
           buffer.writeUUID(player.getPlayerId());
    }
```
```java
    @Override
    public void write(PacketBuffer buffer) {
           PacketBufferHelper.writeUUID(player.getPlayerId(), buffer);
    }
```

**Comment by johnou** [comment]
How about wrapping the buffer instead of extending it?

**Comment by ensirius** [comment]
@johnou This may be a solution, but it's produce a lot of boilerplate :|

**Comment by johnou** [comment]
I disagree, in fact by extending DefaultByteBufHolder you end up with reference-counting for free
and​ release resources out-of-the-box!

```java
public class WrappedByteBuf extends DefaultByteBufHolder {

    public WrappedByteBuf(@NotNull ByteBufAllocator allocator) {
        super(allocator.buffer());
    }

    public WrappedByteBuf(@NotNull ByteBuf data) {
        super(data);
    }
    
    public void writeUUID(UUID uuid) {
        writeLong(uuid.getMostSignificantBits());
        writeLong(uuid.getLeastSignificantBits());
    }
}
```

**Comment by ensirius** [comment]
@johnou There are no `writeLong` and etc. method

**Comment by johnou** [comment]
@ensirius updated code snippet.

**Comment by johnou** [comment]
@ensirius ok to close the issue?

**Comment by ensirius** [comment]
I found another solution using kotlin

**Comment by johnou** [comment]
Care to share the solution?
