### ISSUE TITLE
Feature Request: expose metrics for EventExecutor and ByteBufAllocator

### ISSUE THREAD

**Issue by ztellman** [netty/netty#5334]
Ideally, EventExecutor should expose some sort of HdrHistogram-ish metrics for queue length, queue latency, and event latency.  My basis for comparison is my own library, [Dirigiste](https://github.com/ztellman/dirigiste), which implements a highly instrumented Java executor.  At the very least, having some way to get the length of the queue would be helpful.

As for ByteBufAllocator, it's possible I'm missing where this can be found (there are a lot of values being exposed), but I don't see any way to tell if an off-heap OOM is approaching, nor any attempt in the allocator to prevent that from happening.

I've created [a few workarounds for this](https://gist.github.com/ztellman/3a4fcef2291151bea809184b8c5410a9), which work well enough for me, but I doubt I'm the only one who needs these.  If you have any questions, I'm happy to answer them.

**Comment by aphyr** [comment]
Seconded--even just being able to query queue depth would be a terrific metric--Riemann users really miss this from Netty 3.

**Comment by normanmaurer** [comment]
@ztellman @aphyr at least for the queue depth you can do this:

`((SingleThreadEventExecutor) eventLoop).pendingTasks()`.

**Comment by ztellman** [comment]
@normanmaurer Thanks, I'm not sure how I missed that.  Looking at the implementation, it looks like this assumes `pendingTasks()` is always called from within the event loop, correct?

**Comment by normanmaurer** [comment]
@ztellman this will be fixed in 4.0.37.Final and 4.1.1.Final. See https://github.com/netty/netty/pull/5309

**Comment by jmason** [comment]
Likewise, it'd be great to be able to get deque.size as a metric out of SimpleChannelPool.

**Comment by normanmaurer** [comment]
@ztellman working on some more metrics to expose... stay tuned.

**Comment by normanmaurer** [comment]
Please check https://github.com/netty/netty/pull/5397/files

**Comment by normanmaurer** [comment]
Let me close this... I think we now have enough metrics for all our `ByteBufAllocator` implementations and also for our `EventLoop` implementations (both can be called from any thread now).

**Comment by normanmaurer** [comment]
Please re-open if you can think of anything that is missing
