### ISSUE TITLE
HPACK Encoder.java data structure improvements 

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#5357]
Encoder.java's data structure looks very similar to the data structure used in `DefaultHeaders`. We should investigate making some of the same improvements in Encoder.java as were made in `DefaultHeaders`:
- The underlying array should be a power of 2. Then we can use a mask `&` operation to index into the array.
- The `hash(CharSequence)` function ~~should just use the `name.hashCode()`~~ could re-use the [CASE_INSENSITIVE_HASHER](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/AsciiString.java#L1353) instead of inventing a new hash algorithm.
  - Also the negative value checks can be removed from `hash`.
- Consider exposing the size of the hash array as a parameter to the constructor. For folks that don't want a Dynamic table, or if they anticipate it will be small ... we could limit the size consumed by the underlying array (this would be similar to [DefaultHeaders](https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/DefaultHeaders.java#L123).

**Comment by ejona86** [comment]
For `hash(CharSequence)`, it's a bit dangerous to use `hashCode()`. In `CharSequence`'s Javadoc:
> This interface does not refine the general contracts of the equals and hashCode methods. The result of comparing two objects that implement CharSequence is therefore, in general, undefined.

**Comment by Scottmitch** [comment]
@ejona86 - Great point. `name.hashCode()` would not work. I've updated the issue description to reflect this.
