### ISSUE TITLE
Discontinue support for Netty 3.x

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#5361]
Hey guys,

what you think about discontinue support for Netty 3.x ? This would mean we will not do any more releases etc. I think its about time to do this now.

@trustin @Scottmitch @nmittler WDYT ?

**Comment by johnou** [comment]
@normanmaurer after one last 3.x release? race condition fix by huguesb was pretty impressive.

**Comment by nmittler** [comment]
@normanmaurer +1

**Comment by Scottmitch** [comment]
@normanmaurer +1

**Comment by normanmaurer** [comment]
did the last 3.10.x release today.

**Comment by manish-striim** [comment]
Hi Guys,

we are running into some Netty conflict issue...Can any of you please offer some guidance on how to resolve that?
https://discuss.elastic.co/t/netty-dependency-issue-with-elasticsearch-5-4/89120

Really appreciate your help!

Thanks,
Manish

**Comment by Scottmitch** [comment]
Netty 3 and Netty 4 are in different name spaces and therefore shouldn't conflict. I recommend you consume with the elastic search folks.
