### ISSUE TITLE
Lack of support ChunkedInput for WebSocket protocol

### ISSUE THREAD

**Issue by zizigooloo** [netty/netty#5363]
Hi Dears
I was needed to ChunkedInput for WebSocket frame, that not found it into repository,   so i developed WebSocketChunkedInput class for that.

Please check it, if it's OK then put into repository . . . 

thx

[WebSocketChunkedInput.java.zip](https://github.com/netty/netty/files/302930/WebSocketChunkedInput.java.zip)

**Comment by Scottmitch** [comment]
@zizigooloo - Hey thanks for reaching out and providing some code! Please open a PR so you can get credit for your work. Plus this means we don't have to open a `.zip` file :)

**Comment by zizigooloo** [comment]
thx for hints
