### ISSUE TITLE
Could not found org.apache.tomcat.jni.SessionTicketKey

### ISSUE THREAD

**Issue by HappyHopeSnow** [netty/netty#5370]
I use the netty-4.1.2.Final,when I running the module of example,there have occur a dependency error.
can not import org.apache.tomcat.jni.SessionTicketKey,please check it,thank you .

**Comment by normanmaurer** [comment]
How do you run it ? Sounds like a class-path problem to me.

**Comment by windie** [comment]
Did you add the following dependency?
```xml
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-tcnative</artifactId>
    <version>1.1.33.Fork17</version>
</dependency>
```
It's optional and should be added explicitly.

**Comment by normanmaurer** [comment]
Let me close this... @windie provided the correct answer
