### ISSUE TITLE
Let OpenSslContext take pre-encoded pkcs#8 private key/cert bytes

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#5374]
Netty 4.1.1-SNAPSHOT

It would be great if it was possible to pass pre-encoded pkcs#8 private key and certificate bytes into OpenSslContext and skip some of the stuff that is happening in OpenSslContext's `toBIO(...)` methods (namely the Base64 encoding and appending of the "---- BEGIN/END ----" markers).

**Comment by Scottmitch** [comment]
@rkapsi - Would you be interested in submitting a PR?

**Comment by rkapsi** [comment]
@Scottmitch On it...

... but `io.netty.util.collection.*` seem to be missing on the 4.1 branch?!

**Comment by normanmaurer** [comment]
@rkapsi its generated ... run mvn clean compile in the common module

**Comment by rkapsi** [comment]
@normanmaurer thanks!

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5377
