### ISSUE TITLE
HttpContentCompressor/HttpContentEncoder should not set chunked transfer-encoding for HTTP 1.0

### ISSUE THREAD

**Issue by mrokitka** [netty/netty#5382]
Netty version: 4.1.0.Final

Context:
When using HttpContentCompressor and the HttpResponse is protocol version 1.0, HttpContentEncoder.encode() should not set the transfer-encoding header to chunked.  Chunked transfer-encoding is not valid for HTTP 1.0 - this causes ERR_CONTENT_DECODING_FAILED errors in chrome and similar failures in IE.

This is the snippet I'm referring to:

// Make the response chunked to simplify content transformation.
res.headers().remove(HttpHeaderNames.CONTENT_LENGTH);
res.headers().set(HttpHeaderNames.TRANSFER_ENCODING, HttpHeaderValues.CHUNKED);

**Comment by normanmaurer** [comment]
@mrokitka wow there are still people using HTTP/1.0 ? You are right we are currently only support it with HTTP/1.1, not sure if we will ever support HTTP/1.0. But at least we should "skip" HTTP/1.0 messages. Let me come up with a PR for this

**Comment by mrokitka** [comment]
@normanmaurer - I've run into this since we're using Squid as a caching proxy to handle caching of content for outbound proxy requests from a Netty based proxy server I'm implementing.  Squid doesn't fully support HTTP 1.1, so although it handles HTTP compression properly responses are always HTTP 1.0.

Kind of a drag, but if the compressor could handle the compression for HTTP 1.0 without the need for chunked encoding that would be great.

**Comment by normanmaurer** [comment]
@mrokitka the problem with this is that we would need buffer the full content in memory as we will need to set the "Content-Length" header. We could do this but not sure if this is really good :)

**Comment by mrokitka** [comment]
@normanmaurer perhaps a flag that could be programmatically set on the compressor to indicate if we want to support HTTP 1.0?  A true value would compress and buffer to set the content-length header for 1.0 responses, false would just skip 1.0 messages?

**Comment by normanmaurer** [comment]
@mrokitka maybe... let me see what I can come up with.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5405 . 

@mrokitka I may come up with a follow up to support compression for http 1.0 as well but currently very busy. If you like you can also contribute a PR.

**Comment by normanmaurer** [comment]
https://github.com/netty/netty/pull/5405
