### ISSUE TITLE
Running unit tests from within IntelliJ no longer works after JCTools change.

### ISSUE THREAD

**Issue by buchgr** [netty/netty#5383]
I can no longer run unit tests from within IntelliJ, after the JCTools #5316 change. I get 

```
java.lang.NoClassDefFoundError: org/jctools/queues/MpscChunkedArrayQueue
```

I assume it has something to do with the JCTools dependency being shaded. Does anyone else have this problem? I tried to run the `Http2MultiplexCodecTest` tests.

**Comment by Scottmitch** [comment]
+1. I just mentioned this to @normanmaurer .

I commented out the line which marks jctools as an optional dependency as a workaround 
https://github.com/netty/netty/blob/4.1/common/pom.xml#L51

**Comment by Scottmitch** [comment]
@guidomedina - Can you also take a look?

**Comment by normanmaurer** [comment]
Will check

**Comment by guidomedina** [comment]
Let me check what my IntelliJ (2016.1.3) does, one sec.

**Comment by guidomedina** [comment]
Got it working with `<shadeTestJar>true<shadeTestJar>` option set at the shade plugin section.

**Comment by guidomedina** [comment]
Will commit and PR, simple commit message OK? :)

**Comment by guidomedina** [comment]
Or you can stuff it into some commit and force push?

**Comment by normanmaurer** [comment]
@guidomedina nope need an extra pr... simple message is ok. Just reference that it fix this commit.

**Comment by guidomedina** [comment]
oki dokey

**Comment by guidomedina** [comment]
making sure they really run inside IntelliJ, at first they were not running outside IntelliJ by issuing a `mvn install`, once that change added Maven does it properly, but still failing on IntelliJ, give me some more time to get to the root of it.

**Comment by normanmaurer** [comment]
@guidomedina thanks! Be sure that `mvn clean package` still works in `testsuite-osgi` after `mvn clean install` in common.

**Comment by guidomedina** [comment]
Messy one, with `<scope>provided</scope>` at main pom.xml it compiles but testsuite-osgi errors saying that it is missing when I know it was packaged.

I'll continue tomorrow, brain dead after long day.

**Comment by normanmaurer** [comment]
Fixe by https://github.com/netty/netty/pull/5385

**Comment by Scottmitch** [comment]
@normanmaurer - Were the concerned in https://github.com/netty/netty/issues/5383#issuecomment-225291986 addressed? Still seems like `provided` is in the main pom.

**Comment by normanmaurer** [comment]
Yes I think so... The key is to gave it provided while override to compile in the common module (and also mark it as optional). All works now

**Comment by buchgr** [comment]
thanks @guidomedina !

**Comment by guidomedina** [comment]
Oh man, I was so tired that overslept, but after state of brain-dead and frustration found the trick that pleases all: tests, shade and OSGI 

Date: Fri, 10 Jun 2016 23:32:57 -0700

**Comment by guidomedina** [comment]
@normanmaurer @Scottmitch there was another way, to make it `<scope>test<scope>` at the main pom but then for any other Maven module that doesn't run as test; say some JMH would not see the dependency so I guess `provided` is the least intrusive while covering most cases.

**Comment by Scottmitch** [comment]
sgtm thanks for taking care @guidomedina !
