### ISSUE TITLE
io.netty.resolver.dns.DnsNameResolver does not resolve localhost on Windows

### ISSUE THREAD

**Issue by vietj** [netty/netty#5386]
On Windows localhost is not in hosts file and the DNS server does not resolve this address either, i.e it is handled by the Windows API. So using a `Bootstrap` (among others) with the resolver based on `DnsNameResolver` will not resolve localhost.

http://serverfault.com/questions/4689/windows-7-localhost-name-resolution-is-handled-within-dns-itself-why

**Comment by normanmaurer** [comment]
@vietj so what ? I think there is not much we can do without doing some crazy jni stuff :(

**Comment by vietj** [comment]
now in Vert.x we simply resolve localhost to `127.0.0.1` on Windows. Perhaps doing the same would make sense in Netty too.

**Comment by normanmaurer** [comment]
Yeah maybe… and logging a warning. Let me do this.

**Comment by vietj** [comment]
a workaround is to add this to the list of parsed hosts when it does not exists using the blocking API (which is not a problem usually as this is done in the resolver itself)

**Comment by vietj** [comment]
i.e you can still get the localhost value once and cache it in a static.

**Comment by vietj** [comment]
```
      try {
        if (!entries.containsKey("localhost")) {
          entries.put("localhost", InetAddress.getByAddress("localhost", InetAddress.getLocalHost().getAddress()));
        }
      } catch (UnknownHostException ignore) {
      }
      builder.hostsFileEntriesResolver(entries::get);
```

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5410
