### ISSUE TITLE
DnsNameResolver does not resolve property A+CNAME answer

### ISSUE THREAD

**Issue by vietj** [netty/netty#5391]
The current DnsNameResolver fails to resolve an A+CNAME answer. For example:

```
dig moose.rmq.cloudamqp.com

...
;; ANSWER SECTION:
moose.rmq.cloudamqp.com. 1800	IN	CNAME	ec2-54-152-221-139.compute-1.amazonaws.com.
ec2-54-152-221-139.compute-1.amazonaws.com. 583612 IN A	54.152.221.139
...
```

The resolver constructs a map of cnames but forgets the trailing "." in the values which lead to not resolve the A record: the DnsNameResolverContext#buildAliasMap returns a singleton map `moose.rmq.cloudamqp.com.->ec2-54-152-221-139.compute-1.amazonaws.com` without the trailing "." .

Then the `onResponseAorAAAA` cannot resolve `moose.rmq.cloudamqp.com` to the address `54.152.221.139`. as `if (rName.equals(resolved))` evalutes the false instead of true.

A possible fix is to change the last line of `decodeDomainName` to return `name.toString()` instead of `name.substring(0, name.length() - 1)`

**Comment by normanmaurer** [comment]
will check...

@vietj thanks for reporting!

**Comment by vietj** [comment]
it made my day epic :-)

**Comment by vietj** [comment]
DNS epic day

**Comment by normanmaurer** [comment]
lol

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5413
