### ISSUE TITLE
Initialization cycle in epoll native

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty#5396]
I am trying to make changes to the native epoll library to allow static linking, like those made previously here: https://github.com/netty/netty-tcnative/commit/cf8d01b1ec6872c5ae2530cc40cecdd2caa37ff8

One problem that came up is that the epoll library as written doesn't use the auto names that JNI uses to auto register native methods, and instead uses a a special table made for jar shading.  In my trials, I tried adding a special function that JNI 1.8 can call that skips the dl\* calls (since there is no dynamic loading and no jar shading needed in my case).  This eventually results in a call to   [netty_unix_util_register_natives](https://github.com/netty/netty/blob/83c349ffa94d3992c4ee511d3625afc0c97c12bb/transport-native-epoll/src/main/c/netty_unix_util.c#L45), which then calls `JNIEnv->FindClass`.  `FindClass`, for some reason then tries to initialize the class it does find, which sadly tries to load itself and fails.  [Native](https://github.com/netty/netty/blob/de2515ddd89129e59dc6703a099d6bf44356a093/transport-native-epoll/src/main/java/io/netty/channel/epoll/Native.java#L59)'s static initialization block tries to call `offsetofEpollData`, which will fail (since it is about to call `RegisterNatives` immediately after `FindClass`).  Finally, an exception is thrown trying to load itself (in the middle of loading itself), which then causes the whole thing to blow up.  

One possible solution is not try loading loading the library on static initialization, so that the in process loading will succeed.  Something along the lines of what OpenSsl does might work.

**Comment by carl-mastrangelo** [comment]
cc: @Scottmitch @nmittler

**Comment by Scottmitch** [comment]
@carl-mastrangelo - Yip you are correct. One negative of using the `RegisterNatives` is that you must do `FindClass` to satisfy the interface ... and this call will try to load the class ... which can get you into trouble. The workaround I used in the past was that any class which is loaded as a result of a JNI call must not have any static initialization which depends upon a JNI call. Practically this meant I moved all static initialization which utilizes JNI methods into a separate class (see [NativeStaticallyReferencedJniMethods](https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/NativeStaticallyReferencedJniMethods.java#L19)). Can we use a similar approach here?

**Comment by carl-mastrangelo** [comment]
That would work.  

An alternative I started working on after posting this issue was proposed by someone on our java team:  use the Class.forName overload which doesn't do initialization from the JNI Code.  It's more complicated, and I haven't finished checking if it works, but would easy changing the java code.

In general, static initialization seems to be problematic.  Personally I'd prefer a lazily created singleton, which makes custom or out-of-band initialization easier, and also makes for much easy to write tests.

**Comment by Scottmitch** [comment]
@carl-mastrangelo - Looking forward to seeing what you come up with ... however I wonder if this is as simple as not overloading `offsetofEpollData()` to check if the library is loaded ... and just adding another method (or use an existing "side effect free" method) into `NativeStaticallyReferencedJniMethods` to accomplish the same goal would solve the issue?

**Comment by normanmaurer** [comment]
@Scottmitch didnt you fix this ?

**Comment by Scottmitch** [comment]
@normanmaurer - I don't think so. I'll let @carl-mastrangelo comment more though.

**Comment by normanmaurer** [comment]
@carl-mastrangelo ping

**Comment by carl-mastrangelo** [comment]
I'm going to close this issue.  After looking at this about a month ago, I came to the conclusion that Netty Needs to be able to load itself.  When I was doing this I was calling `System.loadLibrary` myself, which does't work.  Netty handles the init cycle itself properly, but outside code doesn't.  (It depends on where in the cycle you start!)

This isn't an issue for me any more since I understand more how this works.  I believe it is WAI.
