### ISSUE TITLE
sec-websocket-origin should mention HTTPS

### ISSUE THREAD

**Issue by caillette** [netty/netty#5402]
I'm using Netty WebSockets with HTTPS. When performing the handshake, the header field `sec-websocket-origin` is set to a value starting with `http://`, which looks weird.
There is nothing about `sec-websocket-origin` in the RFC. 
The string `http` is set inconditionnally in `io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13`, line 165.
I'm using Netty-4.1.0.CR7.

**Comment by normanmaurer** [comment]
@caillette yet that sounds not right... let me come up with a fix quickly.

**Comment by normanmaurer** [comment]
Fixed https://github.com/netty/netty/pull/5419
