### ISSUE TITLE
Closing alive channels in case if OP_READ triggered with no data available

### ISSUE THREAD

**Issue by Spikhalskiy** [netty/netty#5421]
Hi,

I use http client based on netty in project. (Actually just a basic Bootstrap + FixedChannelPool + ChannelPoolMap). I added a handler that recording channel open and close counts and found that client close and open new connection on almost each request while connections should be keep-alive. My research of the problem below.

I made one request using client (so, connection created and should be put). After getting full response for this request (pipeline with HttpClientCodec and HttpObjectAggregator used), selector for this channel triggered once more with SelectionKey.OP_READ. But actually, no data is available in socket to read, because we already have been read all data.
I have no idea why do I get this READ trigger at all, while full response has been read already. It could be keep-alive tcp package maybe.

During processing of this READ trigger in code point below we get -1 because input stream is empty. (from ReadableByteChannel javadoc: -1 if the channel has reached end-of-stream)
```
	  at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:357)
	  at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:898)
	  at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242)
	  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
	  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
````

As a result, we return -1 from setBytes method like we do this in the case of ClosedChannelException. While there we no ClosedChannelException actually, it's just empty ScatteringByteChannel stream, which violates javadoc ```{@code -1} if the specified channel is closed```. We check this '-1' result and close channel in AbstractNioByteChannel:
```
    int localReadAmount = doReadBytes(byteBuf);
    if (localReadAmount <= 0) {
        // not was read release the buffer
        byteBuf.release();
        byteBuf = null;
        close = localReadAmount < 0;
        break;
     }
```

So, this phantom empty OP_READ leads to channel closing like there were ClosedChannelException.
What do you think?

Netty version 4.0.36

**Comment by Scottmitch** [comment]
`OP_READ` should be set by Netty if you have called `read()` or if `AUTO_READ` is enabled. This just broadcasts interest in read activity on a particular FD to the selector mechanism. Read activity may also include detecting a remote close of the socket. If there is no read activity the selector should not notify on that FD.

> As a result, we return -1 from setBytes ... While there we no ClosedChannelException actually

So you are saying [in.read(tmpBuf)](https://github.com/netty/netty/blob/netty-4.0.36.Final/buffer/src/main/java/io/netty/buffer/UnpooledUnsafeDirectByteBuf.java#L357) is returning `-1` to signal EOS but you don't think this should be interpreted as the channel is closed? Can you put a breakpoint here when this condition occurs and tell me what the OS reports for the state of the socket (e.g. `netstat`)?

**Comment by Spikhalskiy** [comment]
Hm... looks like in java SocketChannelImpl has open, isInputOpen, isOutputOpen=true with non-closed file descriptor. On the same time socket is in CLOSE_WAIT state in netstats on this breakpoint. So... need to find why do this socket closing almost after each request.

**Comment by Spikhalskiy** [comment]
I will spend more time for investigation. This issue could be closed for now, will back when having more info.

**Comment by Scottmitch** [comment]
@Spikhalskiy - thanks for the additional details. plz report back when you get more details.

**Comment by Spikhalskiy** [comment]
Found that it was a connection closing by the remote peer, so issue closed and is not netty problem. Thanks.
