### ISSUE TITLE
HttpContentDecompressor should change decompressed requests to chunked encoding

### ISSUE THREAD

**Issue by jroper** [netty/netty#5428]
In Netty, how do I know if an incoming HTTP request message has a body or not immediately without waiting for subsequent content messages?

If the answer to that is you can't, then there is no bug here, you can close this issue.

If the answer to that is by following the HTTP spec - ie, if the request has a `Content-Length` or `Transfer-Encoding` header, then you know it has a body, otherwise, you know it doesn't have a body - then there is a bug in `HttpContentDecompressor`, since it removes the `Content-Length` header from request, making it impossible to reliably determine whether a message has a body or not by looking at these two headers.

My opinion is that semantically the `HttpContentCompressor` is turning the request into one that uses a transfer encoding to indicate the size of the request message - ie, you now need an empty (last) content message to know the end of the message.  So if it's going to do that, in order to not break downstream handlers, it should add a chunked transfer encoding header - this means downstream handlers that use the content length and or transfer encoding headers according to the spec won't break.  Just removing the content length header violates the HTTP spec, and seeing as Netty generally requires apps to implement and enforce much of the HTTP spec themselves, Netty shouldn't confuse things by breaking it.

**Comment by NiteshKant** [comment]
Looks like a bug to me as `HttpContentEncoder` does add `Transfer-Encoding` header [here](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpContentEncoder.java#L169) but `HttpContentDecoder` [does not](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpContentDecoder.java#L101).

**Comment by normanmaurer** [comment]
@NiteshKant agreed. want to submit a PR with a fix and unit test ?

**Comment by NiteshKant** [comment]
@normanmaurer sure! I would be able to do this soon.

**Comment by NiteshKant** [comment]
[Here](https://github.com/netty/netty/pull/5429) is the PR

**Comment by slandelle** [comment]
Sorry if I get it wrong, but why does `HttpContentDecompressor ` remove the `Content-Length` header in the first place? `Content-Length` is the decompressed length, not the compressed one.

**Comment by normanmaurer** [comment]
@slandelle I don't think so... Do you have a link to a the RFC that state this ?

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5429

**Comment by slandelle** [comment]
@normanmaurer My bad...

**Comment by nremond** [comment]
Thank you guys ! I had a hard time analyzing the issue in Play.
