### ISSUE TITLE
Incorrect protocol version & "host" header in HttpProxyHandler

### ISSUE THREAD

**Issue by fchevassu** [netty/netty#5431]
[ netty-4.1.1.Final ]

There seem to be a couple of things in HttpProxyHandler that do not comply with [RFC 2817](http://www.faqs.org/rfcs/rfc2817.html) (Upgrading to TLS Within HTTP/1.1) 

- The HTTP version required to support the CONNECT method is 1.1,
whereas Netty's HttpProxyHandler class specifies a 1.0 version (line 123)

- The "Host" header should apparently hold the name of the target host,
whereas Netty specifies the proxy address instead, (lines 127-131).

Changing the original code in lines 122-131 :
```
  FullHttpRequest req = new DefaultFullHttpRequest(
          HttpVersion.HTTP_1_0, HttpMethod.CONNECT,
          rhost + ':' + raddr.getPort(),
          Unpooled.EMPTY_BUFFER, false);
  
  SocketAddress proxyAddress = proxyAddress();
  if (proxyAddress instanceof InetSocketAddress) {
      InetSocketAddress hostAddr = (InetSocketAddress) proxyAddress;
      req.headers().set(HttpHeaderNames.HOST, hostAddr.getHostString() + ':' + hostAddr.getPort());
  }
```

To something like this would solve both issues :
```
  final String host = rhost + ':' + raddr.getPort();
  
  FullHttpRequest req = new DefaultFullHttpRequest(
          HttpVersion.HTTP_1_1, HttpMethod.CONNECT,
          host,
          Unpooled.EMPTY_BUFFER, false);
  
  req.headers().set(HttpHeaderNames.HOST, host);
```

**Comment by trustin** [comment]
@fchevassu Care to send a PR? I don't have enough bandwidth these days.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5437
