### ISSUE TITLE
http2: Off-by-one accounting with flow control and padding

### ISSUE THREAD

**Issue by ejona86** [netty/netty#5434]
Per [the spec](http://httpwg.org/specs/rfc7540.html#DATA):
> The entire DATA frame payload is included in flow control, including the Pad Length and Padding fields if present.

However, it seems the pad length isn't being accounted for.
https://github.com/netty/netty/blob/netty-4.1.1.Final/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameReader.java#L397
https://github.com/netty/netty/blob/netty-4.1.1.Final/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L203

I suggest we [add 1 to readPadding(), when padding is present](https://github.com/netty/netty/blob/netty-4.1.1.Final/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameReader.java#L598). This does mean that the `padding` argument could be 256 (instead of maxing out at 255).

@carl-mastrangelo, FYI

**Comment by ejona86** [comment]
We also need to audit outbound path.

**Comment by ejona86** [comment]
cc: @Scottmitch, @normanmaurer, @nmittler

**Comment by buchgr** [comment]
@ejona86 should I take this?

**Comment by ejona86** [comment]
@buchgr, please do.

This will also need to be updated:
https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2DataFrame.java#L72

**Comment by Scottmitch** [comment]
If we add 1 to readPadding() we will have be sure to account that the byte is already read and the [int dataLength = payload.readableBytes() - padding;](https://github.com/netty/netty/blob/netty-4.1.1.Final/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameReader.java#L403) must account for this (and also for the other usages of `readPadding()`). An alternative would be to just adding `1` when we call the FrameListener [1] to ensure it is accounted for in flow control ... then we don't have to update usages of `readPadding()`. We should also update the comments on the `FrameListener` if we are going to include the "padding length byte" in the `padding` value.

[1] https://github.com/netty/netty/blob/netty-4.1.1.Final/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2FrameReader.java#L410

**Comment by buchgr** [comment]
ok i ll take this. will see what turns out best in code. can discuss on the pr.

**Comment by Scottmitch** [comment]
thanks @buchgr !

**Comment by buchgr** [comment]
A quick look at the outbound path seems to indicate, that the pad length field is also not counted towards flow control there.

Interestingly, the spec seems to allow zero length padding, that is the pad field is present with a value of zero.
> Note: A frame can be increased in size by one octet by including a Pad Length field with a value of zero.

I have to take a more detailed look tomorrow morning (11pm here), but this might indicate that we are doing padding wrong as when padding is 1, we really add two bytes (pad length and 1 byte padding). So probably we should just have padding to be a value in [0, 256], with a padding of 1 being special cased on the frame writer as pad length field present with value zero.
