### ISSUE TITLE
Security question: DiskAttribute uses user provided filename for temp file name

### ISSUE THREAD

**Issue by eun-ice** [netty/netty#5435]
Hi there,

maybe I'm paranoid, but I have a security concern.

If you use DiskFileUpload the temp file name is partly the user provided file name, only validation is this:

```
protected String getDiskFilename() {
    File file = new File(filename);
    return file.getName();
}
```

This catches the most obvious security gotchas (like /../../../somethingEvil) but almost everything else I tried is passed directly to the file system.

Is this safe? Why not simply use some random string?

Thanks
Aron

**Comment by normanmaurer** [comment]
@eun-ice we love PRs ... Maybe you want to submit one with a "fix" ?

**Comment by eun-ice** [comment]
Here it is: https://github.com/netty/netty/pull/5481
