### ISSUE TITLE
io.netty.util.collection.LongObjectHashMap  not found at branch 4.1

### ISSUE THREAD

**Issue by chadianshigeshuaige** [netty/netty#5447]
import io.netty.util.collection.LongObjectHashMap;
import io.netty.util.collection.LongObjectMap;

these two classes are not found，what should I do？

**Comment by Scottmitch** [comment]
these files are generated as part of the build. run a full build (`mvn clean install`) or build the common module (`cd common && mvn clean install`)

**Comment by mrgaoang** [comment]
I had run mvn clean install and  ( cd common && mvn clean install)  but these two classes still not found

**Comment by gutaoaining** [comment]
io.netty.internal.tcnative.SSL class not found, what should I do

**Comment by mrgaoang** [comment]
I have solved this problem ，（cd common && mvn clean install） it works ,but you need Refresh your project and reimport all maven project

**Comment by johnou** [comment]
@gutaoaining for starters hijacking other issues especially when they are not related is frowned upon, if io.netty.internal.tcnative.SSL is not on your classpath it means you have not bundled the netty-tcnative jar with your application.

**Comment by medusar** [comment]
@Scottmitch Do you have some wiki or instructions about how to build and develop the project? There are so many profiles in the project and it takes time for users to figure out.

**Comment by normanmaurer** [comment]
@medusar not sure what to tell you ... just use the "default" profile and it will be fine ? 

`./mvnw clean package`

**Comment by medusar** [comment]
@normanmaurer it works, thank you.
