### ISSUE TITLE
Channels leak in FixedChannelPool or javadoc for all recommended release calls required

### ISSUE THREAD

**Issue by Spikhalskiy** [netty/netty#5455]
Netty version: 4.0.37.Final

Context:
I try to use ChannelPool in simple netty http client. Especially FixedChannelPool implementation with 0 acquiring timeout to get fast fail in case if no connections are available.

I call ```ChannelPool#release()``` for channel in my main handler (which is last in the pipeline) in methods
1) ```channelRead()``` (with HttpObjectAggregator in the pipeline before)
2) ```exceptionCaught()```
3) ChannelFutureListener#operationComplete[!future.isSuccess()] added in ```write()``` method

Problem:
After some runtime of this client on the same load, I start to get TimeoutExceptions with "Acquire operation took longer then configured maximum time" and this number increases.

If pool itself works fine, looks like I have a leak somewhere and don't release channel in some flow.
Would be good to have javadoc with enumeration of all situations where release() should be called or
a reference client implementation with channels pooling.

About example from [Release Notes](http://netty.io/news/2015/05/07/4-0-28-Final.html):
I think it's not a very useful example because we call ```release()``` there just after acquiring a channel. It could be good in terms of resource releasing, but we release channel before any writes and reads would be completed, which is not correct in most real scenarios. Am I wrong here?

**Comment by Spikhalskiy** [comment]
So, what I found for now. My main handler (last in pipeline), which extends ChannelDuplexHandler has this sequence of calls:
channelReadComplete(ctx), read(ctx), write(ctx, msg, promise), writeCompleted success: true, channelReadComplete(ctx), read(ctx) -> channelInactive after that.
So, I don't return channel to pool, because no ```channelRead``` or ```exceptionCaught``` called. So, I get channelInactive call without any intermediate calls with additional information what really happened. It's rare situation, but caused leaking of ```release()```. State of channel in channelInactive is
ctx.channel().isActive() == false, ctx.channel().isOpen() == false, ctx.channel().isRegistered() == false, ctx.channel().isWritable() == false
It's pretty non obvious for me that it's normal states flow at all.
Will provide more info if investigate something additional.

As quickfix for leaking - will release channel in channelInactive, reason of breaking channel is still not clear with this fix.

**Comment by Spikhalskiy** [comment]
Ok, here is an example of such session 
<img width="1436" alt="session" src="https://cloud.githubusercontent.com/assets/532108/16454222/89e7a4b0-3e18-11e6-8798-d9d627f7b505.png">
Host with netty client is 10.201.13.48
So, remote host got request and respond with FIN-ACK instead of normal response. In this case, netty's handler will get channelInactive with the flow described above.
I can't estimate if it could and should be addressed in some way in netty's event or exception model.

**Comment by Scottmitch** [comment]
> if socket gets to CLOSE_WAIT because of RTS for example - we get an exception in exceptionCaught, but here we have just a silent channelInactive.

I haven't look in too much detail at this issue but this behavior sounds expected to me. A "FIN" type shutdown initiated by the peer will *not* generate `exceptionCaught` but instead will just call `channelInactive`. A "RST" shutdown initiated by the peer should call both `exceptionCaught` and then `channelInactive`.

**Comment by normanmaurer** [comment]
+1

That said we should handle the case for the user. Let me come up with a fix.

**Comment by normanmaurer** [comment]
Clarified via https://github.com/netty/netty/pull/5497
