### ISSUE TITLE
Remove final from EpollEventLoopGroup

### ISSUE THREAD

**Issue by bdnettleton** [netty/netty#5456]
Netty version: 4.1.0.CR7

Feature request: Please remove final from EpollEventLoopGroup for consistency with NioEventLoopGroup

Context:
We've been using NioEventLoopGroup in part of our project where we extend it and override the various submit, schedule and invoke methods to log any exceptions which occur when the tasks (Runnable/Callable) execute.

We're working on an extension to our project which utilizes EpollEventLoopGroup and would like to implement the same extension here however EpollEventLoopGroup is marked final so we aren't able to  subclass it.

I did check the issues already reported and see that Issue [#4727](https://github.com/netty/netty/pull/4727) already mentioned this, and included a check-in of the change.  However it looks like Issue [#4819](https://github.com/netty/netty/pull/4727) backed out this change, and then was backed out itself.

**Comment by Scottmitch** [comment]
@bdnettleton - In the end the change was never actually committed because there would be more interface changes required and the scope of changes to accomplish my initial goal (full wrapping of the EventLoopGroup) increased substantially, and in the end I found another way to approach the problem. I think was also a feeling that `NioEventLoopGroup` should have been final from the start, but we can make it final now bcz we don't want to break backwards compatibility.  However if there is a concrete use case that cannot easily be accomplished other ways then perhaps its better to make `NIo` and `Epoll` consistent ... @normanmaurer - WDYT?

**Comment by bdnettleton** [comment]
Thanks for the quick response.

Here's a little more about our use case as background.

We're extending NioEventLoopGroup with code below.  Our goal is to catch basic coding errors in tasks we submit to the EventLoopGroup and get them into our logging framework (basic but unfortunately still common things like NullPointerExceptions).

    public static final Logger LOG = LoggerFactory.getLogger(IsmNioEventLoopGroup.class);

    ...

    protected Runnable decorate(Runnable r) {
        return new Runnable() {

            @Override
            public void run() {
                try {
                    r.run();
                }
                catch(RuntimeException e) {
                    LOG.error("Unhandled Exception", e);
                }
            }
        };
    }

    @Override
    public <T> Future<T> submit(Runnable task, T result) {
        return super.submit(decorate(task), result);
    }


We also override the rest of the schedule and invoke methods with similar calls to decorate.

If there is a better way to log all errors in submitted tasks then we can alter our code appropriately.

**Comment by NiteshKant** [comment]
@bdnettleton `SingleThreadEventExecutor` does [log](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java#L370) any `Throwable` from `task.run()`.

Recently, there is also a way to log/handle rejected tasks via [this PR](https://github.com/netty/netty/pull/5441) if that interests you.

**Comment by Scottmitch** [comment]
@bdnettleton - Agreed it seems like what you want can be accomplished (or is already accomplished) via other means. Is there anything else you need that cannot be done?

**Comment by normanmaurer** [comment]
+1 ... I would prefer to keep it final

**Comment by normanmaurer** [comment]
This is "fixed" in the master branch where its possible to extend this stuff
