### ISSUE TITLE
DnsNameResolver should not bind locally

### ISSUE THREAD

**Issue by vietj** [netty/netty#5457]
Netty version: 4.1.1.Final (and master)

Context:
Dns resolution failures when using the `DnsNameResolver` and the JVM is not authorized to bind datagram channels.

Steps to reproduce:
Use the `DnsNameResolver` with an environment that does not allow to bind datagram channels.

The current `DnsNameResolver ` binds locally a `DatagramChannel` which is not necessary (and not always permitted).

The bind is used to obtain a channel and it is possible to create a `DatagramChannel` directly without the need to bind. The method `newChannel` in `DnsNameResolver` can be changed from:

```
  private ChannelFuture newChannel(
      ChannelFactory<? extends DatagramChannel> channelFactory, InetSocketAddress localAddress) {

    Bootstrap b = new Bootstrap();
    b.group(executor());
    b.channelFactory(channelFactory);
    final DnsResponseHandler responseHandler = new DnsResponseHandler();
    b.handler(new ChannelInitializer<DatagramChannel>() {
      @Override
      protected void initChannel(DatagramChannel ch) throws Exception {
        ch.pipeline().addLast(DECODER, ENCODER, responseHandler);
      }
    });

    ChannelFuture bindFuture = b.bind(localAddress);
    bindFuture.channel().closeFuture().addListener(new ChannelFutureListener() {
      @Override
      public void operationComplete(ChannelFuture future) throws Exception {
        resolveCache.clear();
      }
    });

    return bindFuture;
  }
```

to

```
  private ChannelFuture newChannel(
      ChannelFactory<? extends DatagramChannel> channelFactory, InetSocketAddress localAddress) {

    DatagramChannel channel = channelFactory.newChannel();
    channel.config().setOption(ChannelOption.DATAGRAM_CHANNEL_ACTIVE_ON_REGISTRATION, true);
    channel.config().setRecvByteBufAllocator(new FixedRecvByteBufAllocator(maxPayloadSize));
    final DnsResponseHandler responseHandler = new DnsResponseHandler();
    channel.pipeline().addLast(DECODER, ENCODER, responseHandler);
    channel.closeFuture().addListener(new ChannelFutureListener() {
      @Override
      public void operationComplete(ChannelFuture future) throws Exception {
        resolveCache.clear();
      }
    });

    return executor().register(channel);
  }
```

to achieve the same without binding.

**Comment by normanmaurer** [comment]
@vietj +1 ... Want to provide a pr?

**Comment by vietj** [comment]
will do soon @normanmaurer

**Comment by normanmaurer** [comment]
@vietj thanks a lot!

**Comment by vietj** [comment]
I'm seing an issue in tests because the channel is not yet initialized on registration, i.e the code:

```
        b.handler(new ChannelInitializer<DatagramChannel>() {
            @Override
            protected void initChannel(DatagramChannel ch) throws Exception {
                ch.pipeline().addLast(DECODER, ENCODER, responseHandler);
            }
        });
b.option(ChannelOption.DATAGRAM_CHANNEL_ACTIVE_ON_REGISTRATION, true);

ChannelFuture channelFuture = b.register();
```

does not guarantee that the `initChannel` is invoked when the `channelFuture` is succeeded. As consequence sometimes during tests the `DatagramDnsQuery` are not encoded as the `ENCODER` is not yet added to the pipeline.

One solution is to use a promise that is resolved after the pipeline has been modified instead of using the channelFuture.

Thoughts ?

**Comment by normanmaurer** [comment]
@vietj sounds good.

**Comment by normanmaurer** [comment]
@vietj I think even better would be to have the promise be notified once channelActive is called.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5461
