### ISSUE TITLE
PlatformDependent doesn't prefer JDK8 LongAdder 

### ISSUE THREAD

**Issue by CodingFabian** [netty/netty#5458]
I am running Netty on Java 8.

```
    /**
     * Creates a new fastest {@link LongCounter} implementaion for the current platform.
     */
    public static LongCounter newLongCounter() {
        if (HAS_UNSAFE) {
            return new LongAdderV8();
        } else {
            return new AtomicLongCounter();
        }
    }
```

On a normal modern Java8, where HAS_UNSAFE is true, this will always use the c&p LongAdderV8, otherwise the JDK Shipped AtomicLongCounter. Assuming that the JDK8 contained LongAdder is "better" (e.g. it might use intrinsics) I was wondering why there is no Java >=8 check which will directly use the JDK8 LongAdder (wrapped to comply to netty interface)

(also note the c&p typo "implementaion" in many of the javadocs)

**Comment by normanmaurer** [comment]
@CodingFabian I will fix this.

**Comment by normanmaurer** [comment]
@CodingFabian seems like there is no way to fix this as we still need to support java6 :(

**Comment by CodingFabian** [comment]
Huh? Cant you keep the current if else and just wrap with an if else that checks version and if >=8 delegates to the JDK  Version? You might need an indirection to avoid classloading in <8

**Comment by doom369** [comment]
@CodingFabian there are no specific intrinsics for `LongAdder`. However I agree that it is better to use JDK version as netty version differs from latest JDK version.

> You might need an indirection to avoid classloading in <8

Could you please show code example what do you mean?

**Comment by johnou** [comment]
@CodingFabian something like this? https://github.com/johnou/netty/commit/bffeee37ca9e415688f68f33a573d44cb71579dc

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6379
