### ISSUE TITLE
Wrong report regarding leak records on load test

### ISSUE THREAD

**Issue by o-pechenyi** [netty/netty#5480]
Netty version: 4.0.37.Final

Context:
during load test get wrong report regarding leak records 

Steps to reproduce:
1. Implement ByteToMessageDecoder that calls ByteBuf.retain to increase reference count during decoding. Later ByteBuf.release is called from another thread, not io. 
2, Set -Dio.netty.leakDetectionLevel=paranoid 
3. Run load testing

Result: huge amount of leak records is reported, however there should be less then 20 of them. 
Moreover, leak is reported wrongly at all

E 0701-0905:25,377 i.n.u.ResourceLeakDetector LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
WARNING: **7258** leak records were discarded because the leak record count is limited to 4. Use system property io.netty.leakDetection.maxRecords to increase the limit.
Recent access records: 5
#5:
        io.netty.buffer.AdvancedLeakAwareByteBuf.release(AdvancedLeakAwareByteBuf.java:61)
...
Created at:
        io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:280)
...

$ java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

$ uname -a
Linux ip-172-31-8-89.eu-central-1.compute.internal 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Scottmitch** [comment]
The debug statement you provided `WARNING: 7258 leak records were discarded ...` does not exist in 4.0.17.Final. Can you clarify what version you are using and update to the latest version (4.0.38.Final) to see if the issue still exists?

**Comment by o-pechenyi** [comment]
Sorry, made a misprint. I was using 4.0.37.Final version

**Comment by Scottmitch** [comment]
- Do you see the same behavior with `-Dio.netty.recycler.maxCapacity.default=0` system property?
- What do the stack traces look like if you increase the amount of stack traces in the leak record `-Dio.netty.leakDetection.maxRecords=32`?

**Comment by o-pechenyi** [comment]
- tried to set -Dio.netty.recycler.maxCapacity.default=0, behavior is the same
- when increase number of records in the stack trace can observe repeated records as if same object is used for storing records for different bytebufs:

#22:
	io.netty.buffer.AdvancedLeakAwareByteBuf.readInt(AdvancedLeakAwareByteBuf.java:419)
	com.playtech.openapi.core.codec.MessageFrameDecoder.decode(MessageFrameDecoder.java:27)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:879)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:360)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:276)
	io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	java.lang.Thread.run(Thread.java:745)


#28:
	io.netty.buffer.AdvancedLeakAwareByteBuf.readInt(AdvancedLeakAwareByteBuf.java:419)
	com.playtech.openapi.core.codec.MessageFrameDecoder.decode(MessageFrameDecoder.java:27)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:879)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:360)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:276)
	io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	java.lang.Thread.run(Thread.java:745)

**Comment by Scottmitch** [comment]
If you switch to the `Unpooled` allocator do you see the same behavior?

> Implement ByteToMessageDecoder that calls ByteBuf.retain to increase reference count during decoding. Later ByteBuf.release is called from another thread, not io. 

Can you provide a reproducer with minimal code?

**Comment by o-pechenyi** [comment]
Tried with UnpooledByteBufAllocator, the same issue exists.

> Can you provide a reproducer with minimal code?
Let me try

**Comment by normanmaurer** [comment]
Let me close this with needs info label
