### ISSUE TITLE
channelReadComplete calls without channelRead in handler cinfigured after HttpObjectAggregator

### ISSUE THREAD

**Issue by Spikhalskiy** [netty/netty#5483]
Netty version: 4.0.38.Final

Context:
Flow of ChannelInboundHandler's methods channelRead and channelReadComplete invocations after HttpObjectAggregator looks meaningless.

Steps to reproduce:

1) Create netty http client bootstrap with pipeline:
HttpClientCodec
OurLoggingHandler

After one request-response thru this client and shutting down we get something like this in log :
```
49:13,979 ERROR [Client-1-1] t.ChannelLifecycleStatsHandler - channelActive
49:14,161 ERROR [Client-1-1] t.ChannelLifecycleStatsHandler - channelRead
49:14,161 ERROR [Client-1-1] t.ChannelLifecycleStatsHandler - channelRead
49:14,161 ERROR [Client-1-1] t.ChannelLifecycleStatsHandler - channelReadComplete
49:14,163 ERROR [Client-1-1] t.ChannelLifecycleStatsHandler - channelRead
49:14,165 ERROR [Client-1-1] t.ChannelLifecycleStatsHandler - channelReadComplete
49:17,435 ERROR [Client-1-1] t.ChannelLifecycleStatsHandler - channelReadComplete <-- this last one is just before shutdown. Not too much sence too.
49:17,903 ERROR [Client-1-1] t.ChannelLifecycleStatsHandler - channelInactive
```

This flow looks more or less right except the last channelReadComplete, which I think we get because no meaningful HttpMessage formed, but channelRead triggered in HttpClientCodec.

2) Create netty http client bootstrap with pipeline:
HttpClientCodec
HttpObjectAggregator
OurLoggingHandler

After one request-response thru this client and shutting down we get something like this in log:
```
52:33,107 ERROR [Client-1-1] t.ChannelLifecycleStatsHandler - channelActive
52:33,326 ERROR [Client-1-1] t.ChannelLifecycleStatsHandler - channelReadComplete
52:33,328 ERROR [Client-1-1] t.ChannelLifecycleStatsHandler - channelRead
52:33,329 ERROR [Client-1-1] t.ChannelLifecycleStatsHandler - channelReadComplete
52:36,655 ERROR [Client-1-1] t.ChannelLifecycleStatsHandler - channelReadComplete
52:36,874 ERROR [Client-1-1] t.ChannelLifecycleStatsHandler - channelInactive
```

So, first two channelRead consumed by aggregator without any signals to OurLoggingHandler, which is fine, but we still pass channelReadComplete thru.

I'm not sure if it's incorrect behaviour, but does it make any sense to pass thru ```channelReadComplete```call to handler without any ```channelRead```? It makes processing a bit harder, while it could be a feature, not a bug. If it's a feature and as expected behaviour, I think it would be good to write about it explicitly in channelReadComplete javadoc to escalate this type of flow for users.

**Comment by normanmaurer** [comment]
@Spikhalskiy I think it is not well defined if its expected or not. I think the only thing defined is that there MUST be a channelReadComplete(...) after a channelRead(...). Thats it.
