### ISSUE TITLE
Race in Netty's DefaultPromise

### ISSUE THREAD

**Issue by buchgr** [netty/netty#5489]
As reported on the grpc issue tracker https://github.com/grpc/grpc-java/issues/2015

There seems to be a race between `DefaultPromise.trySuccess()` and `DefaultPromise.addListener(...)`. It looks like the offending line is [`if (listeners == null)` ](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/concurrent/DefaultPromise.java#L421).

Now, `listeners` is written in a `synchronized` block and read outside of it. Reasoning about about visiblity guarantees and ordering seems complicated. I think it's probably more complex than that comment one line above. We should probably make `listeners` volatile.

cc: @carl-mastrangelo @ejona86 @nmittler @Scottmitch @normanmaurer

**Comment by normanmaurer** [comment]
Sounds good

**Comment by buchgr** [comment]
I don't think writes of a field from within a synchronized block guarantee ordering and visiblity for reads of the field outside of a synchronized block. My reasoning is that the compiler might place the `listeners` field in a register and thus concurrent updates to `listeners` might not be populated between threads.

Worst case that could happen is Thread 0executes `DefaultPromise.addListener(...)` and Thread 1 executes `DefaultPromise.trySuccess()`. If `addListener` completes before `trySuccess()`, then `trySuccess` might not have gotten the update of `listeners`, and thus not execute the listener.

I think if that's true, there should probably be a new release of Netty, as this seems really serious.

**Comment by johnou** [comment]
Release early, release often :+1:

**Comment by normanmaurer** [comment]
@nitsanw would you mind checking as well mister concurrent wizard!

**Comment by buchgr** [comment]
Here seems to be one explanation of why this is not correct: http://shipilev.net/blog/2016/close-encounters-of-jmm-kind/#pitfall-semi-sync

**Comment by nitsanw** [comment]
Using the "write in syncronized block, read outside of it" requires the field to be volatile to be correct at all and even then it's an error prone optimization usually used for simple value fields and not references to potentially complex objects.
I'm not sure the DefaultFutureListeners is thread safe, but if it isn't that would be further trouble.

**Comment by normanmaurer** [comment]
@nitsanw `DefaultFutureListeners` is not thread-safe, what other issue you see here ?

**Comment by buchgr** [comment]
@normanmaurer that should not be a problem as the listeners are all executed in the event loop thread.

**Comment by normanmaurer** [comment]
@buchgr thanks... Merged your PR. I think the rest should be fine. Let me cut another release at the end of this week as there are a few others things I want to fix as well.

**Comment by nitsanw** [comment]
@buchgr @normanmaurer IIUC because notifyListeners0 is not in synchronized block you can add/remove listeners concurrently resulting in NPE/AIOOBE

**Comment by buchgr** [comment]
@nitsanw @normanmaurer hmm. the `listeners` field is only modified within a synchronized block. We don't iterate over the `listeners` field, but over a local variable [1]. So that should be fine?

That being said, since the promise has recently been rewritten, I wouldn't vouche for its correctness and maybe we should just make it simple and wrap stuff in synchronized blocks.

[1]https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/concurrent/DefaultPromise.java#L488

**Comment by nitsanw** [comment]
@buchgr @normanmaurer OK, what I missed there is the fact that the field is nulled out in the synchronized block. That should work then. I find the code quite confusing, listeners is a variable/field/method name, different names for different things would help here.

**Comment by buchgr** [comment]
thank you @nitsanw!

**Comment by normanmaurer** [comment]
+1 .. Thanks @nitsanw . 🍻 on me next time :)

**Comment by Scottmitch** [comment]
@buchgr - Thanks for the fix!

> since the promise implementation has recently been rewritten, I wouldn't vouche for its correctness 

This optimization was preserved from the previous implementation of DefaultPromise [1]. So IIUC this issues has existed for a while :cry:.

This check is just an optimization to try and avoid other more expensive operations (volatile reads, thread locals, and eventually synchronized). I wonder if we should just take out the null check all together (/cc @normanmaurer), as opposed to making `listeners` volatile? This would make sense if we assume that most of the time when the promise is completed there is at least 1 listener, but may be more costly if there are no listeners (we have to go through the synchronized just to find out). I would assume that having `listeners` not be volatile should also mean it is cheaper to add/remove listeners, and notify the `listeners` too.

[1] https://github.com/netty/netty/commit/f2ed3e6ce8039d142e4c047fcc9cf09409105243#diff-f1028c299e6b780683eb6eb692e01993L546

**Comment by buchgr** [comment]
@Scottmitch My apologies Scott. I wasn't trying to point fingers (I reviewed this change after all and didn't notice the bug). I was just trying to say that this is such a central part and we should probably only do optimizations if we are damn sure they are correct.

**Comment by Scottmitch** [comment]
> My apologies Scott. I wasn't trying to point fingers (I reviewed this change after all and didn't notice the bug). 

No worries ... didn't interpret as finger pointing ... just wanted to point out it is likely this race has existed for a while. Everyone should take this new release :+1: 

>  I was just trying to say that this is such a central part and we should probably only do optimizations if we are damn sure they are correct.

:+1: 

Also I have a PR pending with the changes suggested above ... I'll ping you on the review but let me know if the suggestion sounds reasonable.
