### ISSUE TITLE
why not let LineBasedFrameDecoder support \r?

### ISSUE THREAD

**Issue by taichu012** [netty/netty#5508]
Since LineBasedFrameDecoder support \r\n with WIN os,and.support \n with linux/unix based os, why not to support \r as one of line break flag for mac os?
thanks

**Comment by taichu012** [comment]
Maybe can update method as below to support both \n,\r\n,\r  
 /**
     * Returns the index in the buffer of the end of line found.
     * Returns -1 if no end of line was found in the buffer.
     */
    private static int findEndOfLine(final ByteBuf buffer) {
    	//OLD
//        int i = buffer.forEachByte(ByteProcessor.FIND_LF);
//        if (i > 0 && buffer.getByte(i - 1) == '\r') {
//            i--;
//        }
    	
    	//NEW        
        int idxr = buffer.forEachByte(ByteProcessor.FIND_LF);
        int idxn = buffer.forEachByte(ByteProcessor.FIND_CR);
        int i = (idxn<idxr)?idxn:idxr; //never equal
        if (i > 0 && buffer.getByte(i - 1) == '\r') {
            i--;
        }
        return i;
    }

**Comment by WhiteTrashLord** [comment]
I don't think this is necessary. Many protocols use \r\n which is supported by every OS. Should somebody make an own strange Mac OS protocol, he can also make his own FrameDecoder.

Your new code is also bad for the performance.

**Comment by taichu012** [comment]
OK, that's right, it needn't to handle the case nearly never appearance. 
Please just close this issue. Let me know if it must be closed by reporter.
