### ISSUE TITLE
MemoryFileUpload & DiskFileUpload NOT equals itself

### ISSUE THREAD

**Issue by isdom** [netty/netty#5514]
test code:

    @Test
    public final void testMemoryFileUploadEquals() {
        final MemoryFileUpload f1 = 
                new MemoryFileUpload("m1", "m1", "application/json", null, null, 100);
        
        assertEquals(f1, f1);
    }
    
    @Test
    public final void testDiskFileUploadEquals() {
        final DiskFileUpload f2 = 
                new DiskFileUpload("d1", "d1", "application/json", null, null, 100);
        
        assertEquals(f2, f2);
    }

The two testcase above have failed.

please review equals's code （[MemoryFileUpload.java](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/multipart/MemoryFileUpload.java#L71)）

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Attribute)) {
            return false;
        }
        Attribute attribute = (Attribute) o;
        return getName().equalsIgnoreCase(attribute.getName());
    }

**Comment by Scottmitch** [comment]
yes the equals implementation does seem suspect ... @veebs wdyt?

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5527
