### ISSUE TITLE
Writing simultaneous messages to same Channel with different InboundHandler issue

### ISSUE THREAD

**Issue by arunsraogithub** [netty/netty#5519]
We are having a multi thread application and want to avoid linear channel size based on simultaneous requests E.g., 30 parallel requests served by 30 open channels. So, we planned to use same channel for writing multiple messages wit adding different inbound channel handlers to pipeline. However, certain cases the response message for one handler is read by other handler and there is a request/response mismatch. Is there a better way of handling high transactions/second (TPS) without actually creating that many channels as it does not look practical (our TPS can go upto 100, so creating 100 channels!!).

Please suggest how we can handle request/response matching? Thanks..

**Comment by arunsraogithub** [comment]
@normanmaurer Seeking your suggestion for above issue. Thank you.

**Comment by NiteshKant** [comment]
@arunsraogithub We use [StackOverFlow](http://stackoverflow.com/questions/tagged/netty) for usage questions. Github issues are for reporting bugs, suggesting/discussing new features.

**Comment by arunsraogithub** [comment]
@NiteshKant Ok Sure. I am new to this and did not realize. Thanks!
