### ISSUE TITLE
in PoolArena's method of toString, part of smallSubpagePools should begin with index 0

### ISSUE THREAD

**Issue by songxianjia** [netty/netty#5520]
<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-all</artifactId> 
			<version>4.1.1.Final</version>
		</dependency>
io.netty.buffer.PoolArena

    @Override
    public synchronized String toString() {
        ...
        buf.append(StringUtil.NEWLINE)
           .append("small subpages:");
        for (int i = 1; i < smallSubpagePools.length; i ++) {
            PoolSubpage<T> head = smallSubpagePools[i];
            if (head.next == head) {
                continue;
            }

            buf.append(StringUtil.NEWLINE)
               .append(i)
               .append(": ");
            PoolSubpage<T> s = head.next;
            for (;;) {
                buf.append(s);
                s = s.next;
                if (s == head) {
                    break;
                }
            }
        }
       ...
    }

mycode:

        ...
	public static final ByteBufAllocator allocator = ByteBufAllocator.DEFAULT;
	
	@Test
	public void printAlloc(){
		allocator.ioBuffer(501);
		System.out.println(((PooledByteBufAllocator) allocator).dumpStats());
	}
        ...

the output:
8 direct arena(s):
Chunk(s) at 0~25%:
Chunk(136432db: 1%, 8192/16777216)
Chunk(s) at 0~50%:
none
Chunk(s) at 25~75%:
none
Chunk(s) at 50~100%:
none
Chunk(s) at 75~100%:
none
Chunk(s) at 100%:
none
tiny subpages:
small subpages:

**Comment by normanmaurer** [comment]
@songxianjia thanks will have a look

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5526
