### ISSUE TITLE
How to use io.netty.util.Recycler in multiple thread, will it cause a memory leak?

### ISSUE THREAD

**Issue by taojiaenx** [netty/netty#5521]
version:**4.1.0.final**
I was working on a Push server, and now I want to decrease the number of new objects, so I want to  achieve the goal by using the **io.netty.util.Recycle**r. However, when I read the source code and I found that in io.netty.util.Recycler.Stack.scavengeSome() line 376
`if (**cursor.owner.get() == null**) {
                    // If the thread associated with the queue is gone, unlink it, after
                    // performing a volatile read to confirm there is no data left to collect.
                    // We never unlink the first queue, as we don't want to synchronize on updating the head.
                    if (cursor.hasFinalData()) {
                        for (;;) {
                            if (cursor.transfer(this)) {
                                success = true;
                            } else {
                                break;
                            }
                        }
                    }
                    if (prev != null) {
                        prev.next = next;
                    }
                } else {
                    prev = cursor;
                }`

I imagine a situation as follows, I **get an object x In  thread A**, Then I **recyle the object x in thread B** and unfortunately the thread A is working in I/O progress (NIOeventLoopGroup)and thread B working in a threadpool which **means that A and B may never closed**, now will there  be a memory leak ?

**Comment by normanmaurer** [comment]
@taojiaenx no.. It can be used from multiple threads. That said be aware that the fast-path is optimised for the case where allocation and deallocation thread are the same

**Comment by taojiaenx** [comment]
WriteTask is a subtype of io.netty.util.Recycler and  a queue node when I call **channel.Write() in thread A**, there will create a writeTask, However the I/O thread is **B** and writeTask will recycle when the write start in thread **B**, now will the WriteTask cause a memory leak because  the allocation and deallocation are different?

**Comment by normanmaurer** [comment]
@taojiaenx again now... it will be put back in the Recycler.

**Comment by taojiaenx** [comment]
thanks, I got it
