### ISSUE TITLE
codec-http2: Http2FrameCodec never satisfies promise on Http2WindowUpdateFrame

### ISSUE THREAD

**Issue by olix0r** [netty/netty#5530]
I noticed that when Http2WindowUpdateFrame is written to Http2FrameCodec, the write [promise is never satisfied](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2FrameCodec.java#L144).  Is this intentional?  If not, I'm happy to submit a fix.

**Comment by normanmaurer** [comment]
@olix0r nope... A PR would be awesome :)

**Comment by normanmaurer** [comment]
@olix0r actually @Scottmitch made a good point. Can you wrap the code into a try / catch block and fail the promise on error ?
