### ISSUE TITLE
Http2 => Http headers mismatch

### ISSUE THREAD

**Issue by mosesn** [netty/netty#5540]
HttpConversionUtil takes a [simple][0] approach to encoding the URI, which I think might be a little too simple.  As an example, if I send an Http2Header with authority = "twitter.com", scheme = "https", and path = "/", I would expect the encoded URI to be "https://twitter.com/", but it's actually "/".

I propose that we use the JDK URI constructor instead of just directly using path, so something like:

```
(new URI(scheme, authority, path, null, null)).toString()
```

@ejona86 @normanmaurer @Scottmitch PTAL!  If this looks like the right direction, I can whip up a PR.

[0]: https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/HttpConversionUtil.java#L256-L285

**Comment by Scottmitch** [comment]
sgtm

**Comment by ejona86** [comment]
Which URI are you talking about? The request uri in HTTP/1 (the one that follows the HTTP method on the first line) is normally a path, with the Host header providing the host and scheme missing. Using a full URI is typically only done when proxies are involved. So I think the behavior you describe is what I would consider "normal" for HTTP.

**Comment by Scottmitch** [comment]
agreed @ejona86 ... @mosesn can you explain your use case? does it make sense to add a `boolean` paramter to this method to support the existing way (just take path), or the new way (build the URI)?

**Comment by mosesn** [comment]
OK, maybe I'm doing something wrong then.  I'm using the Http1.1 => Http2 converter on the client-side, which shells out to [HttpConversionUtil][0].  It requires that we get the scheme by inspecting the uri in the request, so it only accepts requests with uris in the form of "http://twitter.com".  Then, when we get to the server-side, instead of forming the uri back to be "http://twitter.com" the uri is instead "/".

Should we change the client-side behavior in HttpToHttp2ConnectionHandler instead?

[0]: https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/HttpConversionUtil.java#L464-L486

**Comment by Scottmitch** [comment]
> t requires that we get the scheme by inspecting the uri in the request, so it only accepts requests with uris in the form of "http://twitter.com".

This is the primary source where we try to derive scheme. If it cannot be derived from the URI then we check the [SCHEME extension header](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/HttpConversionUtil.java#L472), and finally the port. Can you provide an unit test demonstrating the issue?

**Comment by mosesn** [comment]
@Scottmitch 👍 

branch: https://github.com/mosesn/netty/tree/mnakamura/unit-test-uri
commit: https://github.com/mosesn/netty/commit/ce9e42bdde442e4d401ea43123209f8eb9508285

output:

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.435 sec <<< FAILURE! - in io.netty.handler.codec.http2.HttpConversionUtilTest
requestConversionIsReversible(io.netty.handler.codec.http2.HttpConversionUtilTest)  Time elapsed: 0.434 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[http://twitter.com]> but was:<[/]>
	at io.netty.handler.codec.http2.HttpConversionUtilTest.requestConversionIsReversible(HttpConversionUtilTest.java:37)
```

**Comment by Scottmitch** [comment]
Thanks @mosesn. I guess you have some sort of proxy where you need to forward the [absolute-form](https://tools.ietf.org/html/rfc7230#section-5.3.2) url? As I said I'm fine with extending the behavior of these methods with a `boolean` parameter (or something similar) to preserve the absolute-form if its necessary.

**Comment by mosesn** [comment]
@Scottmitch no, this is more about not surprising people with this behavior.  We have a finagle http Request type, which was based on http/1.1, but we now want to be usable over http/2, to ease migration.  I don't think this will be an uncommon use case, since if you want your clients and servers to be compatible with both http/1.1 and http/2, it's much easier to build everything against http/1.1 and then use netty downgraders.

If I send a request which looks a certain way, I have an expectation that it will look the same way when it comes out the other end.  This isn't to say that I expect that there's a bijection from Http/1.1 => Http/2, but it should at least be reversible, so that when I convert something from Http/1.1 to Http/2, I should be able to get it back intact.

If you're asking about why it's specifically important that I be able to use the `http://` prefix, I don't have a specific use case in mind, except that as you mentioned, netty fails to write the request and tells you to supply a scheme explicitly.

**Comment by mosesn** [comment]
Just realized I haven't explicit explained my setup.  I have a netty http/2 client which converts from http/1.1 types to http/2 types and then writes http/2 to the wire, talking to a netty http/2 server which converts from http/2 types it reads off the wire to http/1.1 types.

**Comment by mosesn** [comment]
What do you think about adding another extension header for URI?  if it's there, the header decoder doesn't have to guess about the URI.

**Comment by Scottmitch** [comment]
Whether the path is in absolute-form or some other form you should be able to reconstruct the URL [1]. If the goal is to "re-create" the original request with the same URI format won't you need some external state/info either way? The RFC [2] dictates what form the URI should be in depending if the destination is a proxy or an origin server.

[1] https://tools.ietf.org/html/rfc7230#section-5.5
[2] https://tools.ietf.org/html/rfc7230#section-5.3

**Comment by ejona86** [comment]
Scheme didn't exist on-the-wire in HTTP/1.1, other than for forward proxying. This is already a problem for servers in HTTP/1, as they simply have to "know" whether the port was encrypted or not in order to decide the scheme (or they just hard-code it or have it in a configuration file!). And when using a reverse proxy in HTTP/1 that doesn't work, which is a bit of a problem. There is `X-Forwarded-Proto` which is de facto standard to solve that problem, although I don't know how ubiquitous it is. `X-Forwarded-Proto` is a bit strange for this case though.

**Comment by ejona86** [comment]
And to be clear, `X-Forwarded-Protocol` is pretty common too, but it seems that the random consensus (maybe due to [AWS](https://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/x-forwarded-headers.html)) is `X-Forwarded-Proto`, such that people are changing their code to it. `Forwarded` is also [a thing](https://tools.ietf.org/html/rfc7239).

**Comment by mosesn** [comment]
I was able to work around my problem by using scheme extension headers, and dropping support for `http://twitter.com/`-style URIs, which it sounds like is common in http.  I read @Scottmitch's links in the http/1.1 spec, which made sense. If I run into a use case where I need this behavior, I'll revive this thread.  Thanks!
