### ISSUE TITLE
resolve "localhost" returns InetAddress object without hostname in Windows

### ISSUE THREAD

**Issue by alexlehm** [netty/netty#5554]
Netty version: 4.1.3.Final

Context:
When using the resolver for "localhost" in Windows (when the localhost entry is not present in the hosts file), the returned InetAddress object is created with the address but without the hostname, so that getHostName() returns the ip address 127.0.0.1 and not localhost. When localhost is resolved in the hosts file or if it is resolved on Linux, the object contains the hostname which is the behaviour I would expect in any case.
The address object comes from NettyUtils where the LOCALHOST4 and LOCALHOST6 objects are created from the address bytes without hostname so that the object does not know the hostname.

This at the least breaks an unit tests with ssl in my usecase (which is actually in vertx), I would prefer a consistent behaviour on the different platforms.

Steps to reproduce:
1. add "localhost" to the unit test DnsNameResolverTest in DOMAINS
2. in Windows 7+ make sure that \windows\system32\drivers\etc\hosts does not contain an entry for localhost 127.0.0.1
3. run the unit test

in testResolveA()
Expected: is "localhost"
     but: was "127.0.0.1"

java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
Operating system: Ubuntu Linux 13.04 64-bit

Windows 7 64 bit
ver
Microsoft Windows [Version 6.1.7601]

**Comment by alexlehm** [comment]
https://github.com/netty/netty/pull/5555

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5555
