### ISSUE TITLE
There is somthing wrong in netty download page

### ISSUE THREAD

**Issue by knight00800** [netty/netty#5556]
Hi, there.
   in the netty downloads page, there shows a version named "4.1.9.Final - 15-Jul-2016", but cannot to be downloaded, when you click this version, you will get an error page mention like this "The requested path was not found."
  And I have checked the netty github tags, there is no version named 4.1.9 (the latest version is 4.1.3), please check it.
  Thanks.

**Comment by normanmaurer** [comment]
@knight00800 ups... fixed.
