### ISSUE TITLE
Netty4.0.28 mem leak for io.netty.util.Recycler

### ISSUE THREAD

**Issue by nhynew** [netty/netty#5563]
In Netty4.0.28  , I found java gc can not recycle the old area, and i use jamp -histo:live  to export the heap info,  there are 985892 io.netty.util.Recycler$DefaultHandle Objects in mem.
![image](https://cloud.githubusercontent.com/assets/20569760/17009625/53e4d22a-4f2f-11e6-9d17-c30ff8fbc497.png)

In the other hand , I use unpooledbytebufallocator for send defalutfullhttprequest content.

Would you please give me some idea to solve this proplem? thanks.

**Comment by nhynew** [comment]
![image](https://cloud.githubusercontent.com/assets/20569760/17009733/523eeb08-4f30-11e6-99c2-146e1695ea38.png)

this is my code, and i am sure that the allactor thread is same to the reslease thread wich is in netty IO worker thread.

**Comment by Scottmitch** [comment]
can you sort the object list by number instances strongly retained?

**Comment by nhynew** [comment]
The follow pic is sorted by intances , please check it . thanks.
![image](https://cloud.githubusercontent.com/assets/20569760/17014377/e6160f70-4f56-11e6-8ecd-1ae2a1b306fd.png)

**Comment by Scottmitch** [comment]
It looks like there are a bunch of WriteAnFlushTask objects in the heap ... how are you applying back pressure?

Also can you update to the latest released version 4.0.39 and confirm if the issue still exists and if any behavior changes?

**Comment by nhynew** [comment]
This situation is in the case of the emergence of stress tests, after the pressure test is completed, I performed manually fullgc, and I found that these objects can not  released, and I found this class Recycler.java each recycle time will apply to other threads referenced object into a WeakHashMap, this will generate a lot of references of the same Object, but I do not know where and how these references are released.

My case is as follows:
1, I use ChannelHandlerContext.writeAndFlush(DefaultFullHttpRequest) in the biz Thread. and this will create WriteAndFlushTask which owner thread is biz thread by Recycler 
![image](https://cloud.githubusercontent.com/assets/20569760/17044135/b23b5f2c-4fef-11e6-8791-6933252455ff.png)

2, When the task finished， it will be recycled the reference into WeakHashMap beacause its owner thread is not same to the current thread. So each invocation will to do this , I think it will generate huge number of references for the same one WriteAndFlushTask  Object.  Just like the picture shown above I post.
![image](https://cloud.githubusercontent.com/assets/20569760/17044214/a6a73c84-4ff0-11e6-8752-88103d010cdf.png)

I'm not sure I understand correctly, Would you please give me some help for this  ?

Then  I will try it again by the version 4.0.39 .

**Comment by nhynew** [comment]
I have tried use the version 4.0.39 and I found there are huge number of DefaultHandle  and  WriteAnFlushTask  Objects.  The pic is as follows:
![image](https://cloud.githubusercontent.com/assets/20569760/17052329/905ca2cc-502f-11e6-8e8d-d3c2f78c0ae0.png)

I am sure that there are no reqeusts for the server, and the test is finished.  Then I performed fullgc mannually many times, but these two objects can not recycle by java gc.  is this correctly? 
any help for pleasure. thanks.

**Comment by Scottmitch** [comment]
Generally when there are a lot of WriteAndFlush tasks still strongly referenced it is because they are waiting until the channel becomes writable so they can be flushed.  This may happen if for example you are writing faster than the peer can read the data, or if the peer is no longer reading data. This is why I was asking how you apply back pressure. Is the channel you are writing to still open? Can you provide a heap dump? Using a tool like [Eclipse MAT](http://www.eclipse.org/mat/) makes it relatively easy to find all strong references to GC roots to confirm this theory.

**Comment by nicmunroe** [comment]
We just updated from Netty 4.0.36.Final to 4.0.39.Final on a service yesterday and ran into memory leak that looks very close (if not identical) to what is being discussed here. Here's a screenshot:

![possible_netty_mem_leak](https://cloud.githubusercontent.com/assets/15578205/17069730/0d60af48-500d-11e6-9656-9bfffd9dc3dc.png)

We don't have any WriteAndFlush objects in the heap dump, but we do have a bunch of DefaultHandles.

Reverting back to 4.0.36.Final made the problem go away.

**Comment by normanmaurer** [comment]
@nicmunroe could this be related to https://github.com/netty/netty/pull/5569 ? If so can you try move back to 4.0.38.Final or use 4.0 branch and see if it still reproduce ?

**Comment by nicmunroe** [comment]
I'm not sure if it's related or not. I can try out 4.0.38.Final and see how it goes. It will probably be several hours (if not tomorrow) before I can scrape together some time to test and get back to you but I'll do my best.

FWIW - I just now logged into a different box that has been out of the load balancer for 4 hours, did some netstat commands to verify nothing was connected to it, and forced some garbage collections with jcmd. The old gen size did not drop after the GCs. So even with an idle box that has nothing connected to it this memory is not reclaimable.

**Comment by normanmaurer** [comment]
@nicmunroe Also looking at your screenshot is it right that you create and destroy a lot threads (Which also includes EventLoopGroup instances)?

**Comment by nicmunroe** [comment]
@normanmaurer we have a cached thread pool for performing some long running stuff that couldn't be on the Netty worker threads - that's the only place where threads should be frequently created/destroyed. We do have a SimpleChannelPool with a Netty client bootstrap for making downstream HTTP calls with pooled connections that we create on the server, but the SimpleChannelPool, client bootstrap, and associated EventLoopGroup are only created once and reused. Not sure if that answered your question.

I'll have info on the different versions as you requested in a minute.

**Comment by nicmunroe** [comment]
@normanmaurer - I created three canaries the same way, each one with a different Netty version, and deployed them. Here are the results:

* 4.0.38.Final: All good (no memory leak)
* 4.0.39.Final: Memory leak exists
* 4.0.40.Final-SNAPSHOT (from today's snapshot on https://oss.sonatype.org/content/repositories/snapshots): Memory leak exists

So the problem we're seeing was introduced between 4.0.38.Final and 4.0.39.Final, and is *not* fixed on 4.0.40.Final-SNAPSHOT. It seems like this can't be *exactly* the same issue @nhynew is seeing since this issue was opened against 4.0.38.Final and we're not seeing the leak on our service, however it also smells related somehow just based on the heap dumps?

**Comment by johnou** [comment]
@nicmunroe netty-common-4.0.40.Final-20160722.121107-7-sources.jar.md5	Fri Jul 22 12:11:08 UTC 2016	32 (latest I see) does not contain the fix from https://github.com/netty/netty/commit/688e65fc5fa80ea20febfa0a9082868e89e54d61

**Comment by nicmunroe** [comment]
Ah, I didn't realize that commit was so new. I can retest when the snapshot rebuilds and contains that commit, or if someone points me at a different maven repo that contains a snapshot build that does have the commit. Unfortunately building Netty from source and jury-rigging my service to use it would take more time and effort than I have to spare right now.

Worst case I can try again tomorrow with a new snapshot build.

**Comment by normanmaurer** [comment]
Yep please test one a new snapshot is online

**Comment by nhynew** [comment]
@Scottmitch  With the same situation of @nicmunroe , I have object pool with netty channels  of http for downstream http calls,  I have allocate 2000 NioEventLoop for max 2000 connections,  The http call normally very fast. When i receive the httpresponse  i log the response for test. and i am sure the channel is still open when i writing datas.   When i finished the test, on the other hand, no pressure for the server. I found the huge number WriteAndFlush objects in the heap after i run the fullgc mannaully.  
I think the normal situation is that when the server is idle after stress test, these object should be relaeased by java gc.  But the current situation is clearly not the case.
The MAT result is as follows:
![image](https://cloud.githubusercontent.com/assets/20569760/17078547/ac64df4e-5128-11e6-8db5-92a320999273.png)

**Comment by normanmaurer** [comment]
@nhynew not really as we "pool" these objects by default to reduce GC pressure. If you want to disable object pooling you can do this with `-Dio.netty.recycler.maxCapacity=0`.

That said I think using 2000 EventLoops is not what you want. The whole point of using NIO is to use not 1 thread per connection. Using the default number of EventLoops when creating a NioEventLoopGroup should be a good start.

**Comment by normanmaurer** [comment]
@nicmunroe any updates yet ?

**Comment by nicmunroe** [comment]
@normanmaurer Just kicked off the test with the new snapshot. I'll have results in 30-60 minutes.

**Comment by normanmaurer** [comment]
@nicmunroe cool... thanks!

**Comment by nicmunroe** [comment]
@normanmaurer and @johnou looks good with last night's snapshot. No detectable leak. Sorry for hijacking this ticket - looks like they might be separate issues. But thanks for the help. It's good to know the problem has been fixed!

**Comment by normanmaurer** [comment]
Thanks for confirm the fix!

**Comment by nhynew** [comment]
@normanmaurer  I will try it again use default NioEventLoopGroup. thank you for your suggestion.

**Comment by nhynew** [comment]
@normanmaurer  @Scottmitch  I had tried with default NioEventLoopGroup, I found the WriteAndFlushTask only have 5w much less than before by the version 4.0.39.Final  and when the old area full  ,it can be released by java gc successfully. thanks for your help. thanks!

![image](https://cloud.githubusercontent.com/assets/20569760/17081124/bf33c4e0-517e-11e6-9ea8-1f46a32205a5.png)

**Comment by normanmaurer** [comment]
So can we close this?

**Comment by nhynew** [comment]
@normanmaurer  I also have one question.   I have notice that each thread only have one Stack object which is a inner calss in Recycler.java  and When the recycle method has been invoked, the WriteAndFlushTask Object will be recycled into WeakHashMap<Stack, WeakOrderQueue>.  At this point there will only have one WeakOrderQueue for each Thread  right ?   But I found a different case.  There have many WeakHashMap.Entry in one thread. is this reasonable ? 
Would you please give me some help? thanks very much!

![image](https://cloud.githubusercontent.com/assets/20569760/17084699/414522e4-51f7-11e6-96f3-f676b60c4ca0.png)

**Comment by nhynew** [comment]
yes . I read the code of Recycler and finally understand how the Object pool implement. Normally the pool will keep small number objects in it and reuse the Object in the pool to reduce allocated number . thus it also will reduce GC pressure.  good idea !  But When the high pressure of the system come out. 
the pool will accumulate many objects in the WeakHashMap . When the heap is full ,GC will release some weak reference . Do I understand right?  

if i understand right , I think it should controll the entry number of WeakHashMap to Stop it grow indefinitely， right? 

thanks for your help .

**Comment by normanmaurer** [comment]
@nhynew the `WeakHashMap` should at max have one entry per `Stack` and `Thread`. So it would be `number of Stacks` * `number of Threads` as worse-case. The contained `WeakOrderQueue` is bound.

**Comment by nhynew** [comment]
@normanmaurer  But I have 16 Threads and i statistic the number of WeakHashMap.Entry wich have more 300+ totally.
is it exists cycle references ? any help for much pleasure.
The screenshot is as below:
![image](https://cloud.githubusercontent.com/assets/20569760/17087540/5e0bf482-523f-11e6-8c5e-5eaa40da5ca8.png)

**Comment by normanmaurer** [comment]
@nhynew can you upload the heap dump somewhere ? I assume you write from other threads then the IO threads as well.

**Comment by nhynew** [comment]
@normanmaurer The dump is not yet available, because it contains information about the company. I will provide another test dump that does not include company information, but it will take some time.

But i have reviewed my code, I am sure the wirter thread is the same to the release one wich is the IO thread by debug it.

sorry for taking some time to provide you  the dump.

**Comment by nhynew** [comment]
@normanmaurer The dump is not yet available, because it contains information about the company.
I have reviewed my code , i invoke Channel.writeAndFlush in biz Thread  and it will be wrapped into a WriteAndFlushTask in taskQuque and it will be executed by IO thread. When the task finished, it will be recycled by the Recycler in IO thread. is it reasonable?

**Comment by nhynew** [comment]
@normanmaurer The dump is not yet available, because it contains information about the company.
But i have found the proplem.  it have a relationship with a previous bug. https://github.com/netty/netty/pull/5569,   

I have reviewed my code and I invoke the channel.writeAndFlush in Biz thread, and then it will be wrapped into  a WriteAndFlushTask in taskQueue  and when the task finished ,it will be recycled by the IO thead. then it will be push into WeakOrderQueue. 

the version 4.0.39.Final has the bug about #5569  and would you please build a release version contains the fix?

**Comment by normanmaurer** [comment]
You csn grab the SNAPSHOT for now. Will release a new version with the fix this week

**Comment by nhynew** [comment]
Ok, thanks very much for your help for the problem.
