### ISSUE TITLE
OpenSslServerContext NullPointEexception when using a KeyManagerFactory

### ISSUE THREAD

**Issue by JackOfMostTrades** [netty/netty#5565]
Support for using a KeyManagerFactory with OpenSSL was added by [PR 5493](https://github.com/netty/netty/pull/5439). However, there are a couple lingering `checkNotNull()` [assertions](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/OpenSslServerContext.java#L352) that cause a NullPointerException when using a KeyManagerFactory instead of a certificate-chain/private-key pair.

I think it's intended that these variables can be null now since there's an `if (keyCertChain != null)` check on line 370.

**Comment by JackOfMostTrades** [comment]
I added a PR for this: #5567

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5567
