### ISSUE TITLE
ChannelInitializer doesn't works properly for parent channel in ServerBootstrap

### ISSUE THREAD

**Issue by Spikhalskiy** [netty/netty#5566]
Netty version: 4.1.3.Final, 4.0.39.Final

Context:
Initialization of parent channel handler using ChannelInitializer doesn't work properly for ServerBootstrap

Steps:

1) Create server using
```
    ServerBootstrap sb = new ServerBootstrap();
    sb.channel(...).group(...).childHandler(...).handler(ourHandler);
```

2) Create server using
```
    ServerBootstrap sb = new ServerBootstrap();
    sb.channel(...).group(...).childHandler(...).handler(
        new ChannelInitializer<Channel>() {
            @Override
            protected void initChannel(Channel ch) throws Exception {
                ChannelPipeline pipeline = ch.pipeline();
                pipeline.addLast(ourHandler);
            }
        }
    );
```

Expected result:
```ourHandler``` receives all lifecycle calls fine in both cases.

Actual result:
1. First exampe works fine, ```ourHandler``` receives ```handlerAdded()``` call and ```channelRead``` calls if we receive message from client.
2. In the second example, ```ourHandler``` receives ```handlerAdded()``` call and no any ```channelRead``` calls after that.

Tests reproduce bug: https://github.com/Spikhalskiy/netty/commit/d26e14711d8a384948a0d82dc95d014864d6d9b6

```testParentHandler()``` emulates first scenario and works fine
```testParentHandlerViaChannelInitializer()``` emulates second scenario and fails

**Comment by normanmaurer** [comment]
@Spikhalskiy will have a look.

**Comment by normanmaurer** [comment]
@Spikhalskiy should be fixed by https://github.com/netty/netty/pull/5576

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5576
