### ISSUE TITLE
Move SPDY / RTSP out of http into its own codec

### ISSUE THREAD

**Issue by CodingFabian** [netty/netty#5583]
I never fully understood why spdy was sharing its package/jar with http.
Now that support for spdy has been dropped like a hot potato by everybody, it might not be desirable to carry around the classes when one actually does not need them anymore

Was there a special reason for re-using the http package?
Are there any concerns besides backwards compatibility about moving it out?
How would this move happen backwards compatible?

If we can find answers, I am willing to doe the work needed to separate the classes out.

**Comment by Scottmitch** [comment]
> Was there a special reason for re-using the http package?

/cc @jpinner @normanmaurer @trustin

> Are there any concerns besides backwards compatibility about moving it out?

IIUC the goal is to "not have spdy/rtsp in the http jar" ... then I'm not sure how this can be done without a breaking change.

**Comment by CodingFabian** [comment]
I would say that depends on your contracts :)
What would be possible for example to make it a maven dependency. This way users would still get both on the classpath but one could exclude them.

I am not heavily lobbying for this. I just noticed this when dropping all of our spdy code. If you come to the conclusion that this is not worth the trouble this is fine with me as well.

**Comment by Scottmitch** [comment]
if it can be done w/out breaking backwards compatibility then sgtm ... what you suggest (users can "opt-out") sounds reasonable to me ... @normanmaurer ?

**Comment by CodingFabian** [comment]
having looked at a couple of options, i think there is no backwards compatible way to do this. so it might be a 5.x item. closing for now.
