### ISSUE TITLE
Adding Kernel 4.5 epoll flags

### ISSUE THREAD

**Issue by PunKeel** [netty/netty#5586]
Hello,

With the recent introduction of EPOLLEXCLUSIVE/RR, and the update from nginx (1.11.12), I think it might be good to support the new epoll flags.

More informations here: https://lwn.net/Articles/673312/

Thanks! (I do think this is a quite easy task and would appreciate to do it, but want your approval first)

**Comment by normanmaurer** [comment]
@PunKeel can you explain how `EPOLLEXCLUSIVE` can be useful for us ? We only have one thread blocking on epoll_wait(...) all the time.

**Comment by PunKeel** [comment]
@normanmaurer This is why I wanted you approval first, I had no clue this would be useless.

Sorry for the useless issue.
