### ISSUE TITLE
Unpooled tries to double release empty buffer

### ISSUE THREAD

**Issue by tkaitchuck** [netty/netty#5597]
See:
https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/Unpooled.java#L316
In unpooled when an empty buffer is at the start of the list of several to be wrapped, it first detects the empty buffer. Then without removing it from the list it passes the whole list to the CompositeByteBuf constructor. Which will attempt to take ownership of the buffer, calling release on each of the buffers it is passed. This results in release being called twice on the empty buffer, which can cause an exception to be thrown.

**Comment by normanmaurer** [comment]
Thanks will check

**Comment by Scottmitch** [comment]
thanks for reporting @tkaitchuck !

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5605
