### ISSUE TITLE
SslHandler: log spam on channel close

### ISSUE THREAD

**Issue by technocoreai** [netty/netty#5598]
SslHandler tries to flush the unsent data and negotiate the closure with the peer when I close the channel. It force-closes the channel if it can't do that safely after a timeout. However, every time it does that, I get multiple warnings in the logs:

    [WARN  2016-07-29 09:04:04.954] [nioEventLoopGroup-9-3] [io.netty.handler.ssl.SslHandler]: [id: 0xe36ca335, ...] Last write attempt timed out; force-closing the connection.
    [WARN  2016-07-29 09:04:04.956] [nioEventLoopGroup-9-3] [io.netty.util.concurrent.PromiseNotifier]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@2740946b (success)
    [WARN  2016-07-29 09:04:04.956] [nioEventLoopGroup-9-3] [io.netty.util.concurrent.PromiseNotifier]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@2740946b (success)

    [WARN  2016-07-29 09:05:49.033] [nioEventLoopGroup-9-1] [io.netty.handler.ssl.SslHandler]: [id: 0x00508dd6, ...] Last write attempt timed out; force-closing the connection.
    [WARN  2016-07-29 09:05:49.034] [nioEventLoopGroup-9-1] [io.netty.util.concurrent.PromiseNotifier]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@46cf0584 (success)
    [WARN  2016-07-29 09:05:49.034] [nioEventLoopGroup-9-1] [io.netty.util.concurrent.PromiseNotifier]: Failed to mark a promise as success because it is done already: DefaultChannelPromise@46cf0584 (success)

Our code doesn't use PromiseNotifier and since the warnings always happen after SSL force-close, it looks like they're coming from `SslHandler#safeClose` callbacks. Is there any point in keeping those warnings in?

**Comment by normanmaurer** [comment]
@technocoreai which version of netty ?

**Comment by technocoreai** [comment]
Sorry, forgot to include that! 4.0.40 currently, but it's been present for a while.

**Comment by normanmaurer** [comment]
@technocoreai thanks let me check

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5604
