### ISSUE TITLE
UnknownHostException mentions hostname with search domain added

### ISSUE THREAD

**Issue by alexlehm** [netty/netty#5602]
Netty version: 4.1.4.Final

Context:
While testing the dns resolution of vert.x I found the cosmetic issue that the exception for UnknownHost mentions the hostname with the last attempted search domain appended, which is kind of confusing. I would prefer to see the original hostname supplied to the method in the exception. The resolution function is based on the netty resolver, the exception text is created in DnsNameResolverContext.

I tried to reproduce the issue with a unit test in netty, which I didn't get quite right, however it is shown when doing the following:

1. add an unknown hostname to the list of hostnames in DnsNameResolverTest, e.g. "unknown.hostname"
2. remove the line .nameServerAddresses(DnsServerAddresses.singleton(dnsServer.localAddress())) in newResolver() to enable dns resolution with real dns
3. add at least one search domain (I used internal.example.com)
4. run the unit test testResolveA()
5. if should fail with the error

java.net.UnknownHostException: failed to resolve 'unknown.hostname.internal.example.com'

$ java -version
java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) Client VM (build 25.71-b15, mixed mode)

Operating system: Windows 10 Home 64 bit

Microsoft Windows [Version 10.0.10586]

(edit: I  choose a rather bad example as search domain before, I have changed the example to example.com now)

**Comment by alexlehm** [comment]
To show the issue inside vert.x the following unit test should show the error message when running it inside the current master of eclipse/vert.x

https://gist.github.com/alexlehm/d4d4ffdf95c97c78dff7ba91de1b0d09

Starting test: UnknownHostExceptionTest#testResolveExceptionHostname 
java.net.UnknownHostException: failed to resolve 'sdfsdfsdfsdsdffd.internal.example.com'. Exceeded max queries per resolve 3

**Comment by normanmaurer** [comment]
@alexlehm makes sense... interested in proving a PR ?

**Comment by alexlehm** [comment]
https://github.com/netty/netty/pull/5608
