### ISSUE TITLE
Setting Http Headers using predefined HttpheaderNames allocates strings

### ISSUE THREAD

**Issue by CodingFabian** [netty/netty#5607]
I was surprised to se my profiler telling me that:

    request.headers().set(HttpHeaderNames.CONTENT_TYPE, "application/json; charset=UTF-8");

performs a string allocation.
It turns out that HttpHeaderNames.CONTENT_TYPE is an ascii string, which allocates String when used as above:

    public HttpHeaders set(CharSequence name, Object value) {
        return set(name.toString(), value);
    }

is that intentional? I see that even netty internal method calls end up on this path. I was under the assumption that using the HttpHeaderNames, I can avoid allocation. but as it seems It is better for me just to write `"content-type"` as this simply uses the constant rather than an allocation every header.

**Comment by normanmaurer** [comment]
Hmm DefaultHttpHeaders should not call toString. If ut dies its a bug

**Comment by CodingFabian** [comment]
<img width="753" alt="screen shot 2016-07-30 at 16 48 50" src="https://cloud.githubusercontent.com/assets/176132/17271184/8a121b12-5675-11e6-8600-0848476310e0.png">

You are right, I missed that DefaultHttpHeaders indeed has an implementation which does not call to string. I wonder why JProfiler however shows an allocation in HttpHeaders

**Comment by CodingFabian** [comment]
Possibly misattribution of autoboxed value. Will have closer look tonite

**Comment by normanmaurer** [comment]
Keep me posted!

**Comment by CodingFabian** [comment]
Yes its misattributed but indeed something that can be improved:

io.netty.handler.codec.http.HttpUtil.setContentLength(HttpMessage, long)

message.headers().set(HttpHeaderNames.CONTENT_LENGTH, length);

this will autobox the long to a Long. It seems HttpHeaders/DefaultHttpHeaders is missing a setLong() method. DefaultHeaders has a setLong so it should be easy to add.
If noone does this before me, I will make a pr during the next days.

**Comment by CodingFabian** [comment]
On the other hand it will end up anyway in io.netty.handler.codec.CharSequenceValueConverter.convertLong(long) - so it doesnt really matter. It will be garbage one way or another. Maybe still a setLong would be great for API completeness

**Comment by CodingFabian** [comment]
closing this. Thought was on something but got fooled by looking into the HttpHeaders not DefaultHttpHeaders. No need for any change.
