### ISSUE TITLE
Proposal : remove commons logging classes

### ISSUE THREAD

**Issue by doom369** [netty/netty#5615]
Remove `CommonsLogger` and `CommonsLoggerFactory` classes.

Commons-logging project is not updated for 2 years already. I propose to remove it also from netty too.

Let me know If I can submit PR.

**Comment by Feng-Zihao** [comment]
I agree, I prefer `SLF4J-API` and `Logback`

**Comment by doom369** [comment]
> it is causing any harm?

No harm. It is very outdated and not used within netty for long time. Deprecation also fine.

**Comment by normanmaurer** [comment]
+1 for deprecated.

**Comment by normanmaurer** [comment]
+1 for deprecated.

**Comment by normanmaurer** [comment]
Fixed
