### ISSUE TITLE
Is there any experiment done with TX/RX queue?

### ISSUE THREAD

**Issue by luengnat** [netty/netty#5626]
While it is possible to achieve some performance gain by distributing works through multiple CPUs, Netty kinda limits itself to use just a few number of CPUs to process the work. I wonder whether @normanmaurer has any thought around making it possible to pin certain CPU to process the work to avoid the cache contention which could potentially improve performance.
https://blog.cloudflare.com/how-to-achieve-low-latency/

**Comment by normanmaurer** [comment]
@luengnat you can do this without any change in netty by using something like:
https://github.com/peter-lawrey/Java-Thread-Affinity

**Comment by luengnat** [comment]
@normanmaurer Thanks for the reply. It seems that there are two steps involved. First, we need to lock NIO event loop thread to a particular CPU and then we also need to set the RX/TX RSS/multiple queue to that CPU as well.

I asked that because I'm not sure whether it worths the effort or not. Have you ever received any reports of someone doing so?
