### ISSUE TITLE
Netty 4.1.4 and Android M

### ISSUE THREAD

**Issue by digitalm4ster** [netty/netty#5627]
Does Netty 4.1.4 support Android M? My login routine works with no problem on ICS and Lollipop and shows the following logs:

LoggingHandler: [id: 0xad3e9c3e] REGISTERED
LoggingHandler: [id: 0xad3e9c3e] CONNECT: xxxxxx.xxx-xxxxxxx.xx/xxx.xxx.xxx.xxx:xxxx
LoggingHandler: [id: 0xad3e9c3e, L:/xxx.xxx.xxx.xx:xxxxx - R:xxxxxx.xxx-xxxxxxx.xx/xxx.xxx.xxx.xxx:xxxxx] ACTIVE
LoggingHandler: [id: 0xad3e9c3e, L:/xxx.xxx.xxx.xx:xxxxx - R:xxxxxx.xxx-xxxxxxx.xx/xxx.xxx.xxx.xxx:xxxxx] WRITE: 52B
...
LoggingHandler: [id: 0xad3e9c3e, L:/xxx.xxx.xxx.xx:xxxxx - R:xxxxxx.xxx-xxxxxxx.xx/xxx.xxx.xxx.xxx:xxxxx] FLUSH
LoggingHandler: [id: 0xad3e9c3e, L:/xxx.xxx.xxx.xx:xxxxx - R:xxxxxx.xxx-xxxxxxx.xx/xxx.xxx.xxx.xxx:xxxxx] WRITE: 0B
LoggingHandler: [id: 0xad3e9c3e, L:/xxx.xxx.xxx.xx:xxxxx - R:xxxxxx.xxx-xxxxxxx.xx/xxx.xxx.xxx.xxx:xxxxx] FLUSH
LoggingHandler: [id: 0xad3e9c3e, L:/xxx.xxx.xxx.xx:xxxxx - R:xxxxxx.xxx-xxxxxxx.xx/xxx.xxx.xxx.xxx:xxxxx] RECEIVED: 350B
...

The same routine results On Android M:

LoggingHandler: [id: 0xbed66a5b] REGISTERED
LoggingHandler: [id: 0xbed66a5b] CONNECT: xxxxxx.xxx-xxxxxxx.xx/xxx.xxx.xxx.xxx:xxxx
LoggingHandler: [id: 0xbed66a5b, L:/xxx.xxx.xxx.xx:xxxxx - R:xxxxxx.xxx-xxxxxxx.xx/xxx.xxx.xxx.xxx:xxxxx] ACTIVE
LoggingHandler: [id: 0xbed66a5b, L:/xxx.xxx.xxx.xx:xxxxx - R:xxxxxx.xxx-xxxxxxx.xx/xxx.xxx.xxx.xxx:xxxxx] WRITE: 104B
...                                                                                                           
LoggingHandler: [id: 0xbed66a5b, L:/xxx.xxx.xxx.xx:xxxxx - R:xxxxxx.xxx-xxxxxxx.xx/xxx.xxx.xxx.xxx:xxxxx] FLUSH
LoggingHandler: [id: 0xbed66a5b, L:/xxx.xxx.xxx.xx:xxxxx ! R:xxxxxx.xxx-xxxxxxx.xx/xxx.xxx.xxx.xxx:xxxxx] INACTIVE
LoggingHandler: [id: 0xbed66a5b, L:/xxx.xxx.xxx.xx:xxxxx ! R:xxxxxx.xxx-xxxxxxx.xx/xxx.xxx.xxx.xxx:xxxxx] FLUSH
LoggingHandler: [id: 0xbed66a5b, L:/xxx.xxx.xxx.xx:xxxxx ! R:xxxxxx.xxx-xxxxxxx.xx/xxx.xxx.xxx.xxx:xxxxx] CLOSE
LoggingHandler: [id: 0xbed66a5b, L:/xxx.xxx.xxx.xx:xxxxx ! R:xxxxxx.xxx-xxxxxxx.xx/xxx.xxx.xxx.xxx:xxxxx] UNREGISTERED
...

And connection is closed. What could be the problem?

**Comment by normanmaurer** [comment]
no idea without more infos... Please add more things like pipeline config etc.

**Comment by digitalm4ster** [comment]
Thanks for the quick response!

My channel initializer looks like this:

```
public class MyChannelInitializer extends ChannelInitializer<SocketChannel> {
    private static final String TAG = MyChannelInitializer.class.getName();	
	private final ChannelInboundHandlerAdapter channelInboundHandlerAdapter;
	private final Context context;

	public SmartClientChannelInitializer(ChannelInboundHandlerAdapter channelInboundHandlerAdapter, Context context) {	    
		this.channelInboundHandlerAdapter = channelInboundHandlerAdapter;
        this.context = context;
    }
	
	@Override
	protected void initChannel(SocketChannel channel) throws Exception {
		ChannelPipeline channelPipeline = channel.pipeline();
		
		SSLEngine sslEngine = SSLContextFactory.getContext(context).createSSLEngine();
		sslEngine.setUseClientMode(true);
		sslEngine.setEnabledCipherSuites(new String[] { "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA", "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384" });
		
		channelPipeline.addLast("logger", new LoggingHandler(LogLevel.INFO));
		channelPipeline.addLast("ssl", new SslHandler(sslEngine));
		channelPipeline.addLast("frameDecoder", new ProtobufVarint32FrameDecoder());
		channelPipeline.addLast("protobufDecoder", new ProtobufDecoder(Protocol.TrackAndTraceMessage.getDefaultInstance()));
		channelPipeline.addLast("frameEncoder", new ProtobufVarint32LengthFieldPrepender());
		channelPipeline.addLast("protobufEncoder", new ProtobufEncoder());
		channelPipeline.addLast("idleStateHandler", new IdleStateHandler(0, 0, 0));	
		channelPipeline.addLast("handler", channelInboundHandlerAdapter);		
	}
}

```
The connecting is carried out by the following method:

```
private boolean doConnect() {
        this.group = new NioEventLoopGroup();
        ChannelFuture connectFuture = new Bootstrap()
            .group(group)
            .channel(NioSocketChannel.class)
            .handler(new MyChannelInitializer(this.channelInboundHandlerAdapter, this.context))
            .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, this.connectTimeoutMillis)
            .connect(CommunicationGlobals.SERVER_IP, CommunicationGlobals.SERVER_PORT);

        this.channelToServer = connectFuture.channel();
        connectFuture.awaitUninterruptibly();

	return connectFuture.isSuccess();
    }
```

Any advice will be appreciated.

**Comment by normanmaurer** [comment]
@digitalm4ster can you add a ChannelFutureListener to your write future and see if any exception is logged ?

**Comment by digitalm4ster** [comment]
There is a HandshakeException on server side, it seems to be a cipher mismatch. So it is not netty's fault. Thank you for your help. I will close the issue.
