### ISSUE TITLE
Unpooled.wrappedBuffer with a direct ByteBuffer on android/dalvik wraps as a heap bytebuf

### ISSUE THREAD

**Issue by nlavan** [netty/netty#5629]
in https://github.com/netty/netty/blob/4.0/buffer/src/main/java/io/netty/buffer/Unpooled.java

when wrapping a java.nio.ByteBuffer that is direct (indeed a java.nio.DirectByteBuffer), the function 
public static ByteBuf wrappedBuffer(ByteBuffer buffer) (line 182) 
tests if the buffer hasArray() in order to determine if to create an UnpooledHeapByteBuffer or an UnpooledDirectByteBuffer. 
Obviously, we expect this function to chose, in our case, an UnpooledDirectByteBuffer for the wrapping. But on android/dalvik, the result is the opposite, because the dalvik direct ByteBuffer returns true for its member .hasArray() !
Don't ask me why.

I suggest to change line 186 from:
if (buffer.hasArray()) {
to:
if (buffer.hasArray() && ! buffer.isDirect()) {

just to make sure in the case of a dalvik direct ByteBuffer that apparently "hasArray" while being a direct ByteBuffer.

Tested on dalvik API level 19

**Comment by normanmaurer** [comment]
@nlavan thanks for reporting. I will fix it... I was a bit surprised but it seems "valid" that even a direct buffer may have an byte[].

See
https://docs.oracle.com/javase/8/docs/api/java/nio/ByteBuffer.html#allocateDirect-int-

**Comment by nlavan** [comment]
yep, i didnt check the dalvik source code...

btw, i think your fix should also apply to 4.1 branch, right?

**Comment by normanmaurer** [comment]
yep 4.0 and 4.1

**Comment by normanmaurer** [comment]
@nlavan will be fixed by https://github.com/netty/netty/pull/5636

**Comment by nlavan** [comment]
@normanmaurer thanks for the quick fix, and for Netty's amazing work in general. Netty rocks, after the learning curve is passed...

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5636
