### ISSUE TITLE
HTTP2 without ALPN (bootstrap lib)

### ISSUE THREAD

**Issue by jknack** [netty/netty#5630]
Hi,

Will be nice if Netty provides something similar to: [ALPNHackSSLEngine](https://github.com/undertow-io/undertow/blob/fa1fc5d60cd7b2770b191d132efcda63a4bfc347/core/src/main/java/io/undertow/protocols/ssl/ALPNHackSSLEngine.java)

It is a hacky way to support ALPN in Java 8, but simplify distributions and deployment of Netty powered servers.

To be clear, I don't ask for removal of ALPN just one more alternative for Java 8.

Thanks.

**Comment by jknack** [comment]
Thanks @normanmaurer !

I didn't know about netty-tcnative-* will try! 

Thanks again

**Comment by Scottmitch** [comment]
I don't think we will develop an alternative to alpn-boot for JDK8 and lower. We will support ALPN in JDK9 eventually. As @normanmaurer said I think your best bet is to use tcnative-*-static if alpn-boot is too painful.

**Comment by jknack** [comment]
That's OK, tcnative-*-static works perfectly.

Thanks
