### ISSUE TITLE
Wrap native pointer with ByteBuf without requiring ByteBuffer

### ISSUE THREAD

**Issue by tkowalcz** [netty/netty#5645]
I was unable to find a method for ByteBuf to wrap already allocated native memory pointer (e.g. using Unsafe.allocateMemory). 

My specific use case if when using Unsafe/DirectBuffers from Agrona and interfacing with Aeron. At some point, I want to pass data to Netty based client.

**Comment by normanmaurer** [comment]
@tkowalcz let me take care of it.

**Comment by normanmaurer** [comment]
@tkowalcz btw Im not sure if it helps but if you can somehow create a `ByteBuffer` from your memory address you can wrap it via `Unpooled.wrappedBuffer(...)` in the meantime :)

**Comment by tkowalcz** [comment]
I can gladly work on that. But I am not sure if I need to create new type of buffer or modify one of existing implementations (but all versions of *DirectByteBuf store memory address but need  ByteBuffer to pass to super constructor).

I have seen somewhere a trick to create DirectBB and change its address using reflection. No hurry here, so far we are copying it to a pooled byte array.

**Comment by normanmaurer** [comment]
@tkowalcz check https://github.com/netty/netty/pull/5661

**Comment by tkowalcz** [comment]
Exactly what I had in mind. Thanks, that PR looks great.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5661
