### ISSUE TITLE
Consider reusing Undertow ALPN SSL engine for JDK8

### ISSUE THREAD

**Issue by vietj** [netty/netty#5646]
Undertow has implemented an SSL engine that implements ALPN on JDK8 without the need for setting up an agent like the Jetty ALPN solution.

While it may be a discussable solution for production, it could be interesting to provide this option for  those who cares (examples, first experience, tests).

The relevant code is here : https://github.com/undertow-io/undertow/tree/master/core/src/main/java/io/undertow/protocols/ssl

**Comment by slandelle** [comment]
Why is it an arguable solution for production? Is it just so fresh it's not production battled yet, or is it not intended for production?

**Comment by vietj** [comment]
I think it's rather not intended for production, see https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/protocols/ssl/ALPNHackSSLEngine.java#L75

**Comment by vietj** [comment]
@normanmaurer my personal opinion is that I tend to agree with you and this is not a feature request per se.

My intention is that it's worth considering this alternative solution in the Netty community and have it discussed.

**Comment by vietj** [comment]
That being said @normanmaurer is think it's a much more usable solution than Jetty ALPN (no need for changing the bootclasspath or using an agent) and thing is that people use Jetty ALPN even though `netty-tcnative-boringssl-static` is available.

**Comment by Scottmitch** [comment]
I would be interested in seeing a PR, but I don't think this is a very high priority item since we have tcnative-*-static and ALPN boot (even though it may be painful).

**Comment by vietj** [comment]
@Scottmitch imho ALPN boot has severe drawbacks : can break with new JDK version, need to override bootclasspath, maven/gradle build is painful

**Comment by normanmaurer** [comment]
@vietj that is why I say just use netty-tcnative and be happy... The undertow one also can break at any time as it uses reflection and so depend on implementation details of the JDK. So not sure why you think it is better in terms of easy breakage compared to ALPN boot. That said I agree ALPN boot is a big pita to setup etc.

**Comment by normanmaurer** [comment]
I think because of maintainance we will not do this...
