### ISSUE TITLE
netty 4.0.37: HashedWheelTimer is susceptible to OOM

### ISSUE THREAD

**Issue by aniketbhatnagar** [netty/netty#5647]
It appears that if the rate at which new timeouts are created is very high and the created timeouts are not cancelled, then the JVM can crash because of out of heap space. There should be a guard in the implementation to prevent this (for example the constructor of HashedWheelTimer can take an optional max pending timeouts parameter beyond which it will reject new timeouts) or atleast should have a public API that returns the number of pending timeouts so that clients can implement their own guard or expose the count as metric.

Note that this issue is only true in case majority of timeouts are not cancelled.

The following code can be used to reproduce OOM:

```
import com.google.common.util.concurrent.ThreadFactoryBuilder;
import io.netty.util.HashedWheelTimer;
import io.netty.util.Timeout;
import io.netty.util.Timer;

import java.util.concurrent.TimeUnit;

public class HashTest {

  public static void main(String args[]) throws InterruptedException {
    Timer timer = hashedWheelTimer();
    Thread publisherThread = new Thread(() -> {
      while (true) {
        Timeout timeout = timer.newTimeout((t) -> {}, 10, TimeUnit.MILLISECONDS);
       // Uncommenting the following line results in JVM being stable.        
       //timeout.cancel(); 
      }
    });
    publisherThread.start();

    publisherThread.join();
  }

  private static Timer hashedWheelTimer() {
    // 128 ticks per wheel and each tick of 80 microseconds = 10,240 microseconds (10.2 milliseconds)
    return new HashedWheelTimer(new ThreadFactoryBuilder().setNameFormat("hashedwheel-timer-%d")
                                                          .build(),
        80, TimeUnit.MICROSECONDS, 128);
  }

}
```

**Comment by normanmaurer** [comment]
@aniketbhatnagar agree . Let me come up with something.

**Comment by Scottmitch** [comment]
thanks for reporting @aniketbhatnagar !

**Comment by normanmaurer** [comment]
@aniketbhatnagar maybe you want to come up with a PR ?

**Comment by aniketbhatnagar** [comment]
Sure. Let me me come up with one.

**Comment by aniketbhatnagar** [comment]
Create PR #5852. Please have a look.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5852
