### ISSUE TITLE
io.netty.util.Recycler$DefaultHandle Using memory giant

### ISSUE THREAD

**Issue by christ258** [netty/netty#5651]
hi，i also changed 4.0.40.Final. Run for a long time,but 'jmap -histo:live'.
io.netty.util.Recycler$DefaultHandle Using memory giant.The following：
 num     #instances         #bytes  class name
----------------------------------------------
   1:       1168877       37404064  io.netty.util.Recycler$DefaultHandle
   2:        506673       32427072  io.netty.channel.ChannelOutboundBuffer$Entry
   3:        103093       29590656  [B
   4:        662108       21187456  io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask
   5:        120022       16870688  [Lio.netty.util.Recycler$DefaultHandle;
   6:         91734       12073096  <constMethodKlass>
   7:         91734       11752048  <methodKlass>
   8:          8769        9129088  <constantPoolKlass>
   9:           718        7648624  [Ljava.nio.ByteBuffer;
  10:          8769        6858848  <instanceKlassKlass>
  11:         63776        5815488  [C
  12:          7507        5334656  <constantPoolCacheKlass>
  13:          4349        4673480  [I
  14:         30060        4220800  [Ljava.lang.Object;
  15:        115215        3686880  io.netty.util.Recycler$WeakOrderQueue$Link
  16:         80711        3228440  java.lang.ref.Finalizer
  17:         76049        3041960  java.util.WeakHashMap$Entry
  18:         75533        3021320  io.netty.util.Recycler$WeakOrderQueue
  19:          5687        2670232  <methodDataKlass>
  20:         78906        2524992  java.lang.ref.WeakReference
  21:         29578        2129616  com.asiainno.garuda.chatroom.protobuf.GarudaMessage$UserInfo
  22:         77139        1851336  com.google.protobuf.ByteString$LiteralByteString
  23:         52447        1678304  java.util.concurrent.ConcurrentHashMap$HashEntry
  24:         51108        1635456  java.util.HashMap$Entry
  25:         57712        1385088  java.lang.String
  26:         50071        1201704  java.lang.Long
  27:          9389        1117464  java.lang.Class
  28:         29109         931488  java.lang.ThreadLocal$ThreadLocalMap$Entry
  29:         10477         840656  [Ljava.lang.ThreadLocal$ThreadLocalMap$Entry;
  30:         14609         747208  [[I
  31:         13046         729848  [S
  32:         15169         728112  java.util.HashMap
  33:         43651         698416  java.lang.Object

12 hours, still so
And memory don't release, leading to larger and larger.Looking forward to your reply.Thank you very much!

**Comment by normanmaurer** [comment]
@christ258 you are writing to fast... You will need to put some back-pressure into place.

**Comment by christ258** [comment]
When large amounts of TCP request data, will be like this

**Comment by christ258** [comment]
When large amounts of TCP request data, will be like this
num     #instances         #bytes  class name
----------------------------------------------
   1:      19277272      616872704  io.netty.util.Recycler$DefaultHandle
   2:      17646090      564674880  io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask
   3:      12656437      506257480  io.netty.channel.DefaultChannelPromise
   4:        118076      285597280  [C
   5:       1814848      116150272  java.nio.DirectByteBuffer
   6:       1596673      114960456  io.netty.buffer.UnpooledUnsafeNoCleanerDirectByteBuf
   7:       1631134      104392576  io.netty.channel.ChannelOutboundBuffer$Entry
   8:         39330       47844120  [Ljava.lang.Object;
   9:        431661       40196368  [Lio.netty.util.Recycler$DefaultHandle;
  10:       1596669       38320056  com.asiainno.garuda.net.common.handler.GarudaDefaultNettyHandler$1
  11:        116300       21049192  [B
  12:        427929       13693728  io.netty.util.Recycler$WeakOrderQueue$Link
  13:         93655       12351552  <constMethodKlass>
  14:         93655       11998064  <methodKlass>
  15:          9086        9455608  <constantPoolKlass>
  16:          9086        7062616  <instanceKlassKlass>
  17:          7814        5550944  <constantPoolCacheKlass>
  18:         40027        3202160  com.asiainno.garuda.chatroom.protobuf.GarudaMessage$GMessage
  19:        113172        2716128  java.lang.String
  20:          5694        2617272  <methodDataKlass>
  21:           350        2477696  [Ljava.nio.ByteBuffer;
  22:         91655        2199720  com.google.protobuf.ByteString$LiteralByteString
  23:          3604        1468080  [I
  24:          9715        1156392  java.lang.Class
  25:         34280        1096960  java.util.HashMap$Entry
  26:         29241         935712  java.util.concurrent.ConcurrentHashMap$HashEntry
  27:         21993         879720  com.google.protobuf.Any
  28:         11301         813672  io.netty.channel.DefaultChannelHandlerContext
  29:         15077         764648  [[I
  30:         13488         751680  [S
  31:         18518         740720  java.lang.ref.Finalizer
  32:         18287         731480  java.util.WeakHashMap$Entry
  33:         12905         722680  io.netty.util.ResourceLeakDetector$DefaultResourceLeak

**Comment by christ258** [comment]
@normanmaurer

**Comment by christ258** [comment]
@normanmaurer 
put some back-pressure into place？
Can say in detail please？

**Comment by christ258** [comment]
i find WRITE_BUFFER_HIGH_WATER_MARK and WRITE_BUFFER_LOW_WATER_MARK.
How to use a combination of the specific want excuse me please ？

**Comment by christ258** [comment]
I use netty used in chat rooms, this business data forwarding is bigger, a separate link, netty performance is good, once the increasing fluctuation of message, I found the Old Gen growing very quickly, I of the JVM USES is the CMS GC, do you have any good solution to this?
Looking forward to your reply, thank you！

**Comment by maseev** [comment]
@christ258 Basically, you have to make sure that you can write to the channel without putting your data to the Netty's queue. Netty has a couple of methods which you can use in order to implement a backpressure mechanism in your application. Here they are:

- [Channel::isWritable](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/Channel.java#L164)
- [ChannelConfig::setAutoread](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/ChannelConfig.java#L195)
- [ChannelInboundHandlerAdapter::channelWritablityChanged](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/ChannelInboundHandlerAdapter.java#L118)

So, you need to check if a channel is writable, before writing any data in it by checking Channel::isWritable method. If it returns false, you just disable `autoread` option and wait until the ChannelInboundHandlerAdapter::channelWritablityChanged method is called (you need to override it, though). When it's called, you should check `writability` status again and if it's true - you process your chunk of data (writing to the channel). Don't forget to update the `autoread` property when the channel becomes `writable`, though.

I hope you get the idea.

**Comment by christ258** [comment]
hi，I found in the test, if increase isWritable then writeAndFlush, stability, in this case, we need to do in the channelWritablityChanged：
if(ctx.channel().isWritable())
            ctx.channel().config().setAutoRead(true);
        else
            ctx.channel().config().setAutoRead(false);
Looking forward to your reply，
Thank you

**Comment by maseev** [comment]
@christ258 Sorry dude. It's a little bit difficult to understand what you're talking about. It would be helpful if you provided a code example.

**Comment by christ258** [comment]
I set WRITE_BUFFER_HIGH_WATER_MARK and WRITE_BUFFER_LOW_WATER_MARK on childOptions.Then, when the server sends the message done if isWritable then writeAndFlush.
exp:
if(channle.isWritable())
  channle.writeAndFlush(msg);
That it really control memory.
I want to ask is, do this for?Whether also need to deal with channelWritablityChanged.
exp:
in channelWritablityChanged:
if(ctx.channel().isWritable())
ctx.channel().config().setAutoRead(true);
else
ctx.channel().config().setAutoRead(false);

Looking forward to your reply，
Thank you

**Comment by christ258** [comment]
@maseev

**Comment by maseev** [comment]
@christ258 Hope this code snippet helps you:

```java
public class MyHandler extends ChannelInboundHandlerAdapter {

  private ByteBuf buff;

  public MyHandler() {
    buff = PooledByteBufAllocator.DEFAULT.directBuffer();
  }

  @Override
  public void channelRead(ChannelHandlerContext ctx, Object obj) throws Exception {
    final ByteBuf msg = (ByteBuf) obj;

    try {
      buff.writeBytes(msg);
    } finally {
      msg.release();
    }
  }

  @Override
  public void channelReadComplete(ChannelHandlerContext ctx) throws Exception {
    if (ctx.channel().isWritable()) {
      processChunk(ctx);
    } else {
      ctx.channel().config().setAutoRead(false);
    }
  }

  @Override
  public void channelWritabilityChanged(ChannelHandlerContext ctx) throws Exception {
    if (ctx.channel().isWritable()) {
      ctx.channel().config().setAutoRead(true);
      processChunk(ctx);
    }
  }

  private void processChunk(final ChannelHandlerContext ctx) {
    ctx.writeAndFlush(buff);
    buff = ctx.alloc().directBuffer();
  }
}
```

**Comment by christ258** [comment]
@maseev 
hi,When the server side take the initiative to send data number down, not go write?
For example: channle writeAndFlush (), or rewritten
@ Override
Public void write (ChannelHandlerContext CTX, Object MSG, ChannelPromise promise) throws the Exception
Don't know if I understand right

**Comment by maseev** [comment]
@christ258 Well, If I understand you correctly, you can apply the same mechanism in order to prevent OOM in your application. Check the channel status (isWritable) before trying to write anything to it. I think it should be pretty straightforward.

**Comment by christ258** [comment]
OK,I get it,thank you very very much
