### ISSUE TITLE
Disable IPv6 address lookups when -Djava.net.preferIPv4Stack=true

### ISSUE THREAD

**Issue by trustin** [netty/netty#5657]
According to [the Oracle documentation](http://docs.oracle.com/javase/8/docs/technotes/guides/net/ipv6_guide/):

> java.net.preferIPv4Stack (default: false)
>
> If IPv6 is available on the operating system, the underlying native socket will be an IPv6 socket. This allows Java applications to connect to, and accept connections from, both IPv4 and IPv6 hosts.
>
> If an application has a preference to only use IPv4 sockets, then this property can be set to true. The implication is that the application will not be able to communicate with IPv6 hosts.

which means, if `DnsNameResolver` returns an IPv6 address, a user (or Netty) will not be able to connect to it.

Perhaps a more sensible default when `-Djava.net.preferIPv4Stack=true` is specified is not to send an AAAA query at all.

**Comment by normanmaurer** [comment]
@trustin so you will look into it ?

**Comment by trustin** [comment]
Yes

**Comment by normanmaurer** [comment]
Ok cool thx

**Comment by alexlehm** [comment]
I believe a vert.x user observed this issue when running his program in google cloud (and trying to connect to www.googleapis.com) https://groups.google.com/d/topic/vertx/7xTo_a_lOWk/discussion

**Comment by vietj** [comment]
would be worth mentioning this issue in the group thread for the record @alexlehm

**Comment by vietj** [comment]
and perhaps create a corresponding issue in Vert.x project ?

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5659
