### ISSUE TITLE
NotYetConnectedException from write to connected channel

### ISSUE THREAD

**Issue by ztellman** [netty/netty#5660]
Simplified code:

```java
public static final EventLoop LOOP = Utils.eventLoopGroup(1, "").next();

...

Promise<Channel> p = LOOP.newPromise();

new Bootstrap()
                .group(LOOP)
                .channel(Utils.clientSocketChannelClass())
                .option(ChannelOption.AUTO_READ, true)
                .option(ChannelOption.RCVBUF_ALLOCATOR, new FixedRecvByteBufAllocator(16384))
                .option(ChannelOption.SO_REUSEADDR, true)
                .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 1000)
                .handler(new ChannelInitializer<Channel>() {
                    @Override
                    protected void initChannel(Channel socketChannel) throws Exception {
                        // initialize pipeline with HttpClientCodec and a few others
                    }

                    @Override
                    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
                        p.tryFailure(cause);
                    }
                })
                .connect(address)
                .addListener((ChannelFuture conn) -> {
                    conn.channel().writeAndFlush(request).addListener(f -> {
                        if (f.isSuccess()) {
                            p.trySuccess(conn.channel());
                        } else {
                            p.tryFailure(f.cause());
                        }
                    });
                });

return p;
```

This is called a few times a second: an HTTP request is made, the response received, and the connection is closed.  However, after 5-20 minutes, the write will fail with a `NotYetConnectedException`, which doesn't seem like it should be possible.  Is there some event I need to wait for, and if so, how do I wait for it?

**Comment by normanmaurer** [comment]
@ztellman which netty version ?

**Comment by normanmaurer** [comment]
@ztellman also can you include the stacktrace ?

**Comment by ztellman** [comment]
Sorry, left a few details out.  Version is `4.1.0.Final`.  Some information on my environment:

```
> uname -a
Darwin aztlan.local 15.5.0 Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64

> java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

I added in a workaround once I identified that the writes were failing, and didn't save the errors I saw earlier.  Currently trying to reproduce again, I'll update once I have the trace.

**Comment by normanmaurer** [comment]
@ztellman ok thanks... keep me posted.

**Comment by normanmaurer** [comment]
@ztellman ping :)

**Comment by ztellman** [comment]
Hi, sorry for the delay in updating the issue.  I've been out sick pretty much since I reported the issue, and my attempts to reproduce the issue in the last few days haven't met with any success.  The code where the exception was thrown isn't reflected in source control, and at this point I'm starting to think I actually *did* write to the channel before it was connected (maybe in the ChannelInitializer) and my "workaround" for this bug just fixed my mistake.  At this point I'd be happy to close the issue, and reopen it if I can actually put together a reproducing case.

Thoughts?

**Comment by normanmaurer** [comment]
Sounds good... closing for nw
