### ISSUE TITLE
Allow to adjust timeout of Selector.select(timeout) via System Property

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#568]
We use a timeout of 10ms when doing Selector.select(..) by default. This is sometimes a bit to aggressive for some users. So we should make it possible to adjust this via a System property

**Comment by maseev** [comment]
Sorry for bringing up the old topic. I couldn't find a ```io.netty.selectTimeout``` parameter in the Netty's source code. So, it doesn't seem to be working if I set it. Did you guys remove the possibility to configure the select's timeout or there's another way to do that?

**Comment by maseev** [comment]
Oh, it seems that I can specify custom selector provider according to this https://github.com/netty/netty/pull/4955. Could find this in the documentation, though :(
