### ISSUE TITLE
Is it possible to get EventLoop for verticle by using open API only?

### ISSUE THREAD

**Issue by avasenin** [netty/netty#5682]
I need to get verticle's `EventLoop` to use it in netty-based library. I want to reuse it to avoid any issues with synchronization. I found only how to get `EventLoopGroup` but in this case this library will be executed on different `EventLoop`.

I found another way by using internal structure case `((ContextImpl) vertx.getOrCreateContext()).nettyEventLoop();`. Is it possible to add this method to `Context` interface?

**Comment by normanmaurer** [comment]
@avasenin please open this issue on the vert.x project. This is netty ;)
