### ISSUE TITLE
Inheritance problem with ReferenceCountedOpenSslContext

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#5693]
There is potential inheritance problem with ReferenceCountedOpenSslContext.

It doesn't just implement the ReferenceCounted interface but actually does the reference counting which leads to problems if you mix reference countable and non-reference countable (Open)SslContexts in the same code path.

Something like this...

```java
SslContext context = SslContextBuilder.forServer(...)
  .sslProvider(SslProvider.OPENSSL)
  .build();

boolean released = ReferenceCountUtil.release(context);
assert (released); // <- unexpected
```

I wish `OpenSslContext` as a class wasn't already taken. I'd extend that from SslContext and have it implement a noop version of the ReferenceCounted interface.

And then...

```
OpenSslContext < FinalizingOpenSslContext < FinalizingOpenSslClient/ServerContext
OpenSslContext < ReferenceCountedSslContext < ReferenceCountedOpenSslClient/ServerContext
```

**Comment by normanmaurer** [comment]
@Scottmitch can you check ?

**Comment by Scottmitch** [comment]
Preserving backwards compatibility in this case is challenging ... can you describe your use case in a bit more detail? Is this unexpected just because `OpenSslContext` previously didn't implement `ReferenceCounted`? Where you previously calling `shutdown()` instead of `ReferenceCountUtil.release(context);`? Are you calling `retain()` conditionally?

**Comment by rkapsi** [comment]
My assumption/expectation was that only OPENSSL_REFCNT'd contexts are reference counted. But that's not true. Reference counting applies also to `SslProvider#OPENSSL` contexts. The only difference between the two is finalization.

In our use-case there is N-instances of OPENSSL_REFCNT'd SslContexts and one fallback OPENSSL context.

The OPENSSL_REFCNT'd contexts are being loaded out of an AsyncMapper that is backed by a reference counting & time boxed Heap cache. And there is a semi custom SniHandler in the pipeline that does `release()` on the context every time the client disconnects.

The fallback OPENSSL context is used if the client doesn't support SNI or the AsyncMapper failed to produce a SslContext.

I'm currently solving the problem with a custom `release()` method to prevent the singleton fallback SslContext instance from getting destroyed. An alternative would be to `retain()` it.

I think the root problem is that I didn't expect `SslProvider#OPENSSL` to be reference counted and there are use-cases where you want to mix reference counted and non-reference counted OpenSslContext's in the same codepath.

```java
public class MoreReferenceCountUtil {
  
  public static boolean release(SslContext context) {
    if (isReferenceCounted(context)) {
      return ReferenceCountUtil.release(context);
    }
    
    return false;
  }
  
  public static boolean isReferenceCounted(SslContext context) {
    SslProvider sslProvider = sslProvider(context);
    return sslProvider == SslProvider.OPENSSL_REFCNT;
  }
  
  public static SslProvider sslProvider(SslContext context) {
    if (context instanceof JdkSslContext) {
      return SslProvider.JDK;
    
    } else if (context instanceof ReferenceCounted) {
      if (context instanceof OpenSslContext) {
        // This one is strange
        return SslProvider.OPENSSL;
      }
      
      return SslProvider.OPENSSL_REFCNT;
    }
    
    throw new IllegalArgumentException();
  }
}
```

**Comment by Scottmitch** [comment]
> My assumption/expectation was that only OPENSSL_REFCNT'd contexts are reference counted

Correct. `OPENSSL` being reference counted was assumed to be an implementation detail. Existing use cases shouldn't have to worry about releasing in this case, and the finalizer will take care of releasing just as it did before. To implement the behavior you described, making sure the reference counted version didn't have a finalizer, and preserving exiting APIs would require some other means to share code and likely require more code ... it was not clear this is/was necessary. If you have a better/simpler approach plz let me know and maybe we can improve the situation :)

if you are willing to step into the reference counting world ... can you just use the reference counts to handle this situation? `ReferenceCountUtil.retain(..)` when ever its "re-used" and `ReferenceCountUtil.release(..)` whenever its "un-used"? This seems simpler and more generalized than the conditionals described above.

**Comment by rkapsi** [comment]
@Scottmitch retain/release on the fallback context works.

Maybe one thing we could do is... Let `ReferenceCountedOpenSslContext` implement the `ReferenceCounted` interface but all methods ref count methods are NOOPs. For  example `release()` returns always false, `refCnt()` always returns 1.

`OpenSslContext` (i.e. `SslProvider#OPENSSL`) inherits the above behavior and two `SslProvider#OPENSSL_REFCNT` classes override the reference counting with a real implementation.

I dunno, maybe save that stuff for next API breaking release.

**Comment by Scottmitch** [comment]
@rkapsi - Humm I'm not so sure ... maybe best to re-visit when the next API breaking change opportunity comes up.

**Comment by rkapsi** [comment]
@Scottmitch sounds good. Close?
