### ISSUE TITLE
about kcp feature

### ISSUE THREAD

**Issue by beykery** [netty/netty#5694]
the kcp is fast for realtime pvp game， netty
should think about it . 
addr  :  https://github.com/skywind3000/kcp
@normanmaurer

**Comment by normanmaurer** [comment]
@beykery we love contributions... So if you are interested consider submitting a PR :)

**Comment by maseev** [comment]
@beykery It seems that the project's description is written in Chinese, I believe. Is there an English version that describes that protocol (my Google-fu isn't that strong right now :disappointed: )?

**Comment by beykery** [comment]
@maseev yes the project's description is written in Chinese and there is no English version by now.
BTW , i am working on it .

**Comment by beykery** [comment]
i have created jkcp project : https://github.com/beykery/jkcp
it just based on netty's NioDatagramChannel , and i have no
 idea about how to 'plug in' netty..

**Comment by normanmaurer** [comment]
@beykery Let me close this for now. Once you made more progress you could open a PR. That said I am not sure we should really include it in netty itself.
