### ISSUE TITLE
Cannot add two WebSocketServerProtocolHandler at different URIs

### ISSUE THREAD

**Issue by ktonga** [netty/netty#5696]
I'm trying to setup Netty to implement a web server which serves a few HTTP web pages and two separate WebSocket services all tree differentiated by the URI pattern:
- `/websocket1` handle request to WebSocket service 1
- `/websocket2` handle request to WebSocket service 2
- `/docs` handle HTTP request, respond HTML pages

I almost get it working, simple HTTP service and one WebSocket service con coexist, but I'm failing at making the second WebSocket service work nicely together with the first one.

`initChannel` method in my `ChannelInitializer` looks like:

``` java
    pipeline.addLast(new HttpServerCodec());
    pipeline.addLast(new HttpObjectAggregator(65536));
    pipeline.addLast(new WebSocketServerProtocolHandler("/websocket1"));
    pipeline.addLast(new WebSocketFrameHandler1());
    pipeline.addLast(new WebSocketServerProtocolHandler("/websoket2"));
    pipeline.addLast(new WebSocketFrameHandler2());
    pipeline.addLast(new DocsHandler(docs));
```

With this setup the docs (HTTP) and the first WebSocket service are working great, but when I try to open a connection the the second WebSocket service the client hangs forever and the connection never gets established.

In my case, I'm using separate URIs for the WebSocket services just to use different message formats, maybe I'm doing something wrong and that should be done in a different way.

Any ideas?

Thank you.

**Comment by normanmaurer** [comment]
I think this was fixed. Please reopen if you still think there is a problem

**Comment by ktonga** [comment]
you know which PR? so I can take a look.

**Comment by loststarsXD** [comment]
@ktonga Maybe, seperated websocket service is a better choice.
