### ISSUE TITLE
git conflict markers in public javadoc

### ISSUE THREAD

**Issue by ferrybig** [netty/netty#5701]
The following file contains git conflict markers: https://github.com/netty/netty/blob/4.0/buffer/src/main/java/io/netty/buffer/ByteBufUtil.java#L107

These conflict markers are visible in the public javadoc for the hashcode and hexdump methods:

https://netty.io/4.0/api/io/netty/buffer/ByteBufUtil.html

**Comment by normanmaurer** [comment]
ups... let me fix it.

**Comment by Scottmitch** [comment]
thanks for reporting @ferrybig !

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5725
