### ISSUE TITLE
SNI issue similar to #4746

### ISSUE THREAD

**Issue by jknair** [netty/netty#5708]
openssl handshake issue similar to #4746

openssl s_client seems to connect with servername flag but netty fails.
The only difference I could see was the domain consisting of ```Multi-Domain``` part in the certificate netty would fail
```
subject=/OU=Domain Control Validated/OU=PositiveSSL Multi-Domain/CN=sni.domain-provider.com
```

```
netty version : 4.1.4-Final
java version: 1.8.0_u20
openssl version: 1.0.1k
linux version: 3.16.0-4-amd64 Debian
```

**Comment by normanmaurer** [comment]
@jknair can you share how exactly you use openssl client and against which host etc ? So I can try to reproduce

**Comment by jknair** [comment]
The code is : 
```java
SSLEngine sslEngine = sslCtx.newEngine(ctx.channel().alloc(), peerHost, peerPort);
 SSLParameters sslParameters = sslEngine.getSSLParameters();
sslParameters.setServerNames(new ArrayList<SNIServerName>(1) {{
     add(new SNIHostName(peerHost));
}});
sslEngine.setSSLParameters(sslParameters);
final SslHandler ssllHandler = new SslHandler(sslEngine);
```

let me see if I can find any public host to help you with the same.

**Comment by Scottmitch** [comment]
until you get a public host can you put a break point in [OpenSslEngine#setSSLParameters](https://github.com/netty/netty/blob/netty-4.1.4.Final/handler/src/main/java/io/netty/handler/ssl/OpenSslEngine.java#L1461) and describe the behavior you see? Does `SSL.setTlsExtHostName` get called, and with what arguments?

**Comment by jknair** [comment]
hey sorry still cant find any public hostname. debugged that point and 
```
SSL.setTlsExtHostName(ssl, (String) GET_ASCII_NAME_METHOD.invoke(serverName));
```
 gets invoked with an instance of ssl object and ```serverName``` as an object of ```SNIHostName```

**Comment by Scottmitch** [comment]
Thanks for confirming. Reproducer would be helpful now. If you can create simple client/server which demonstrates just this issue that would be ideal.

**Comment by jknair** [comment]
Was not using the required cipher and that was the issue :
```OpenSsl.availableOpenSslCipherSuites()``` worked flawlessly. Thanks @normanmaurer nd @Scottmitch

**Comment by Scottmitch** [comment]
np ... thanks for following up!
