### ISSUE TITLE
Allow clients to override userDefinedWritabilityIndex from AbstractTrafficShapingHandler

### ISSUE THREAD

**Issue by jqmichael** [netty/netty#5712]
Hello, 

AbstractTrafficShapingHandler has a package-private method called "userDefinedWritabilityIndex()". If I create two sub-classes of ChannelTrafficShapingHandler (one for throttling on bandwidth and the other for throttling on message size), I cannot make them independent from each other in terms of writability, because they will all have the same index as ChannelTrafficShapingHandler, which cannot be overridden. 

Can we change the access of userDefinedWritabilityIndex() to _protected_ such that it can be overridden by clients? 

Thanks

Michael

**Comment by normanmaurer** [comment]
Let me take care

**Comment by fredericBregier** [comment]
@normanmaurer Sorry to be late again (very busy those last 9 months). I look at your commit, fine for me.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5791

**Comment by jqmichael** [comment]
Thanks guys! I could've sent you a poll request but wasn't sure if this is the right design.
