### ISSUE TITLE
ByteToMessageDecoder incorrectly releasing bytes

### ISSUE THREAD

**Issue by mosesn** [netty/netty#5717]
I'm using the Http/2 client codec in [finagle][0] and I'm trying to make it look like an http/1.1 codec by converting to the netty http/1.1 types.  I'm now reimplementing the InboundHttp2ToHttpAdapter, and I've found that frames get released before I would expect them to.  Through debugging, it seems like the problem is that although the bytes make it properly into my application, and have `refCnt = 1` when they do, BytesToMessageDecoder subsequently frees the bytes when it sees that a different [ByteBuffer has no readable bytes left][1].  Do you know what's going on?  This doesn't seem right to me.  Do I have to copy those bytes onto the heap if I want to hold onto them?

[0]: https://github.com/twitter/finagle/blob/develop/finagle-http2/src/main/scala/com/twitter/finagle/http2/Http2Transporter.scala

[1]: https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java#L254-L257

**Comment by normanmaurer** [comment]
@mosesn if you want to hold a reference to the `ByteBuf` you will need to call `ByteBuf.retain()`. This will also ensure its not getting released / freed.

**Comment by mosesn** [comment]
@normanmaurer I understand the mechanics of why it's freed.  I think the semantics are wrong.  The ref count is still 1 when I inspect it–it's only that after I have my hands on the ByteBuf, and I think it's my responsibility, someone else goes and frees it.  Should I assume that every single thing that touches a `ByteBuf` should retain and then later release the `ByteBuf` when it doesn't need it?  In the reference counting [wiki page][0] it says that the one who accesses it last should destroy it . . . but in `ByteToMessageDecoder`, `ByteToMessageDecoder` obviously isn't who references it last, since it passes the message along to the next codec.

I guess it seems to me like the clean thing to do would be to think of it as each channel handler passing ownership to the subsequent channel handler, with the terminal channel handler having the responsibility to release it.  I don't understand why I have to retain it instead.

[0]: http://netty.io/wiki/reference-counted-objects.html#who-destroys-it
