### ISSUE TITLE
Better way to access to the selected subprotocol in WebSocket server

### ISSUE THREAD

**Issue by ktonga** [netty/netty#5734]
I'm implementing a WS server which supports several message formats, the client has to specify which one should be used configuring the connection subprotocol.

I don't know if I missing something, but the only way I found to get the selected subprotocol seems a little bit dirty to my taste. The snippet is in Scala but should have no mayor differences with Java:

```scala
val handshakerKey: AttributeKey[WebSocketServerHandshaker] =
    AttributeKey.valueOf(classOf[WebSocketServerHandshaker], "HANDSHAKER")

override protected def userEventTriggered(ctx: ChannelHandlerContext, evt: Object): Unit = {
    if (HANDSHAKE_COMPLETE == evt) {
      Future {
        // Sorry about this tricky hack, it's the only way I found to access the handshaker
        // associated with the channel so I can ask it for the selected subprotocol.
        // The thing is that for the time when we receive this event the handshaker wasn't
        // set as a channel attribute yet. So we MUST wait for it for a few millis, and for
        // some reason we MUST do it in a separate thread.
        // See: [WebSocketServerProtocolHandshakeHandler.java:88](https://git.io/v6DcJ)
        Thread.sleep(500)
        val subprotocol = ctx.channel().attr(handshakerKey).get().selectedSubprotocol()
        
        // Do stuff with the subprotocol name
        ...
      }
    }
  }
``` 

Maybe a better approach for something like this would be to make the selected subprotocol available within the `HANDSHAKE_COMPLETE` event since it can be any object according to `userEventTriggered` signature.

Does it sound sensible to you guys?
Let me know what you think.

Thanks.

**Comment by normanmaurer** [comment]
@ktonga yeah sounds like a good idea. Would you be interested to come up with a PR for this ?

**Comment by ktonga** [comment]
Sure. I could give it a try. Can I target 4.1?

**Comment by normanmaurer** [comment]
@ktonga yes... Just ensure you also keep the "zero args" constructor of the enum to no break the API.

**Comment by sunng87** [comment]
Nice, we were using the same approach to retrieve handshake information includes websocket handshake url and headers.

**Comment by ktonga** [comment]
@sunng87 I was going to add just the subprotocol to the event. You think I should add more?

**Comment by sunng87** [comment]
@ktonga Do you think we should also expose websocket extensions here?

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5751
