### ISSUE TITLE
Could not initialize class io.netty.channel.ChannelOption

### ISSUE THREAD

**Issue by mmobini** [netty/netty#5740]
What's reason of this error? Please tell me if you need extra information.

```
NoClassDefFoundError

Could not initialize class io.netty.channel.ChannelOption
AbstractNioByteChannel.java in closeOnRead at line 67application

AbstractNioByteChannel.java in handleReadException at line 89application

AbstractNioByteChannel.java in read at line 162application

NioEventLoop.java in processSelectedKey at line 511application

NioEventLoop.java in processSelectedKeysOptimized at line 468application

NioEventLoop.java in processSelectedKeys at line 382application

NioEventLoop.java in run at line 354application

SingleThreadEventExecutor.java in run at line 116application

DefaultThreadFactory.java in run at line 137application

Thread.java in run at line 745
```

**Comment by normanmaurer** [comment]
@mmobini looks like a class path problem.

**Comment by mmobini** [comment]
Thanks @normanmaurer
I'm using this code in our staging environment in docker and its working. But doesn't work in our production environment with same config.

**Comment by normanmaurer** [comment]
@mmobini sorry no idea.. Like I said this sounds like a class path problem.  Maybe check your java version etc

**Comment by mmobini** [comment]
Also it works in spring boot brixton.M5 but not working in spring-boot SR1 or SR4.

**Comment by normanmaurer** [comment]
@mmobini then talk with the spring guys... maybe a version mixup or something like it. Nothing we can do here.

**Comment by mmobini** [comment]
Thanks. I will. I will close issue when I find the answer to help other people facing same issue.

**Comment by mmobini** [comment]
Seems duplicate of another issue in spring.
https://github.com/spring-projects/spring-boot/issues/6616
