### ISSUE TITLE
using ipfilter in netty 4.x, http client receive java.net.SocketException: Software caused connection abort: socket write error

### ISSUE THREAD

**Issue by xysLion** [netty/netty#5756]
I use ipfilter of netty 4.0.34.Final in my application, then use jmeter 3.0 to send a file to my application, get result 
![image](https://cloud.githubusercontent.com/assets/6614075/18024676/baff7b1a-6c42-11e6-83a4-7aef1968cacf.png)

**Comment by normanmaurer** [comment]
Please provide more informations and try use the latest netty release. If issue still remain reopen
