### ISSUE TITLE
HTTP/2: SETTINGS_HEADER_TABLE_SIZE should be an unsigned int

### ISSUE THREAD

**Issue by buchgr** [netty/netty#5762]
The HTTP/2 spec demands that the max value for `SETTINGS_HEADER_TABLE_SIZE ` should be an unsigned 32-bit integer. However, it seems that some [limitations in HPACK](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2CodecUtil.java#L90) prevent us from supporting that.

h2spec test suite 6.5 fails due to this limitation. The exception is `Setting HEADER_TABLE_SIZE is invalid: 4294967295`.

```
        × Sends a SETTINGS frame
          - The endpoint MUST sends a SETTINGS frame with ACK.
            Expected: SETTINGS frame (Flags: 1)
              Actual: GOAWAY frame (Length: 56, Flags: 0, ErrorCode: PROTOCOL_ERROR)
```

**Comment by normanmaurer** [comment]
@buchgr will look into it.

**Comment by normanmaurer** [comment]
Should be fixed by https://github.com/netty/netty/pull/5798

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5798
