### ISSUE TITLE
DefaultEventLoopGroup doesn't expose ctor variant that accepts custom Executor

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#5763]
The `DefaultEventLoopGroup` class extends `MultithreadEventExecutorGroup` but doesn't expose the ctor variants that accept a custom Executor like `NioEventLoopGroup` and `EpollEventLoopGroup` do.

Is that on purpose or just an oversight?

**Comment by normanmaurer** [comment]
@rkapsi oversight... let me fix it.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5782
