### ISSUE TITLE
ByteBufAllocator for localChannel & localServerChannel

### ISSUE THREAD

**Issue by blueswhisper** [netty/netty#5770]
I found the default ByteBufAllocator for localChannel & localServerChannel is directBufferPreferred = true without additional config. 
local transport aim to transport message in one java process internally.  is reasonable to use directBuffer during local transport ?

I suggest create a LocalChannelConfig class which ByteBufAllocator only use heapBuffer. 

my runtime env:
```
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

Linux kernel
3.10.0-229.el7.x86_64
```

**Comment by normanmaurer** [comment]
@blueswhisper sounds like a good idea... that said I think we should not change this in a bug-fix release as it changes behaviour and may surprise users. Maybe not a big deal but not sure.... @Scottmitch @nmittler @trustin WDYT ?

**Comment by trustin** [comment]
+1

**Comment by Scottmitch** [comment]
I'm fine with making this change (with proper communication as @trustin said)

**Comment by blueswhisper** [comment]
close this issue ? @normanmaurer

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5792
