### ISSUE TITLE
Netty Version 4.0.36 Above

### ISSUE THREAD

**Issue by jokopitoyo** [netty/netty#5775]
Iam using Netty to handle more than thousand of GPS Tracker, since upgrade above 4.0.36 version my application problem, GPS work abnormal, many GPS Tracker want' update... but i can't debug what the part make this problem...

**Comment by normanmaurer** [comment]
@jokopitoyo sorry but without more informations we can not help. You will at least need to provide some more details. Also you may want to try which specific commit is the problem by just using `git bisect` between version 4.0.35.Final and 4.0.36.Final.

See 
http://webchick.net/node/99

This will help us to better understand where the problem may be

**Comment by jokopitoyo** [comment]
@normanmaurer, i will try your advice,

**Comment by normanmaurer** [comment]
@jokopitoyo any news ?

**Comment by normanmaurer** [comment]
@jokopitoyo please reopen with more infos once you are sure there is an issue
