### ISSUE TITLE
Netlink library

### ISSUE THREAD

**Issue by coderplay** [netty/netty#5777]
Not sure it's right place to post this.  I am thinking about contributing netty a lib of netlink which is the cornerstone of cloud networking, will someone be interested in that?

Netlink is quite similar with unix domain socket, they share the same functions like bind, sendmsg, sendto, recvmsg, recvfrom, close. Thus we can reuse almost all of the existing jni code. But the functionality for netlink differs from unix domain socket. Netlink is designated to be used to transfer information between the kernel and user-space processes.   Through netlink,  users can add/modify bridge, veth, vxlan .. as well as control netfilter.  

see: https://en.wikipedia.org/wiki/Netlink

Please put your thought here.

**Comment by normanmaurer** [comment]
@coderplay is this also related to user-space tcp ?

**Comment by coderplay** [comment]
Netlink itself doesn't use TCP protocol, but through NETLINK_INET_DIAG, we can diagnose TCP connections. An famouse example is [ss](http://linux.die.net/man/8/ss) , [source code](https://github.com/sivasankariit/iproute2/blob/master/misc/ss.c). [Another example](https://github.com/kristrev/inet-diag-example).

**Comment by coderplay** [comment]
Oh @normanmaurer  You mentioned `user-space tcp`, I don't think netlink has relationship with `user-space tcp`. It's a channel for communication between kernel and user-space. The user-space can control kernel I/Os through netlink, also can listen IO events from kernel.  It's a successor of ioctl, but much more powerful.

**Comment by normanmaurer** [comment]
@coderplay sorry for the late response... I am not sure this is really something most people need and would put some more "maintenance" burden on us. So I think I would suggest you just host it in a separate repository for now.

**Comment by normanmaurer** [comment]
So let me close this for now
