### ISSUE TITLE
DnsAddressResolverGroup does not respect java.net.preferIPv4Stack=true

### ISSUE THREAD

**Issue by jknair** [netty/netty#5785]
For async DNS queries using 
```
DnsAddressResolverGroup resolverGroup = new DnsAddressResolverGroup(EpollDatagramChannel.class, DnsServerAddresses.defaultAddresses());
```
wanted to only connect to ipv4 addresses. The jvm flag ```java.net.preferIPv4Stack=true``` passed is not respected

```
netty 4.1.4.Final
```

**Comment by normanmaurer** [comment]
Was fixed in 4.1.5.Final:

https://github.com/netty/netty/issues/5657
