### ISSUE TITLE
Weak spot in SniHandler

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#5787]
This is a follow up to #5786 

IMHO, the `select()` call at line ~244-247 should catch, re-throw it via `fireExceptionCaught()` and exit altogether. Exceptions are currently being caught by the outer `try-catch-Throwable` which will do a fallback to non-SNI.

Basically it's currently not possible to "refuse service" (if I have detected abusive behavior for example) and it'll always do that fallback which leads to being hit 2x.

If the `AsyncMapper` has a non O(1) cost it's a great way to generate some extra load on the server. ;)

**Comment by Scottmitch** [comment]
@rkapsi - having the ability to reject sounds good to me

**Comment by rkapsi** [comment]
@Scottmitch on closer look there appears to be also a bug. Notice how select's isDone() path throws an DecoderException which in turn goes down the non-SNI path (described above) and if the Future isn't done yet it's adding that listener which doesn't throw but rather sends it down the pipeline.

You'll basically get an inconsistent behavior where the non-SNI path sometimes executes and sometimes doesn't.

I'll open a PR in a bit.
