### ISSUE TITLE
Cannot enable EpollChannelOption.SO_REUSEPORT for a client

### ISSUE THREAD

**Issue by hbli** [netty/netty#5799]
Hi,

I am trying to enable SO_REUSEPORT option for a client Bootstrap. But I am getting the following problem. It seems that EpollChannelOption.SO_REUSEPORT is implemented for ServerBootstrap only. Could you please add this feature for client sockets as well?

Sep 07, 2016 12:34:06 AM io.netty.bootstrap.Bootstrap init
WARNING: Unknown channel option: io.netty.channel.epoll.EpollChannelOption#SO_REUSEPORT=true

**Comment by normanmaurer** [comment]
Can you explain why this option is useful for a client?

**Comment by hbli** [comment]
Trying to implement a peer to peer communication via TCP, where the same port will be used for both  client sockets and a server socket for hole punching purpose.

**Comment by normanmaurer** [comment]
@hbli I tried to even doing this in pure c and it seems like SO_REUSEPORT not works there. So are you sure its even possible ?

**Comment by normanmaurer** [comment]
@hbli ping

**Comment by hbli** [comment]
Looks like it is not possible. I can't get it to work neither... We may close this issue. Thanks a lot.
