### ISSUE TITLE
Logging caller or line number error

### ISSUE THREAD

**Issue by looly** [netty/netty#5802]
![image](https://cloud.githubusercontent.com/assets/1432613/18343841/9a8799ae-75e7-11e6-9bb0-813bbadeb71c.png)

When I debug log , and I want to show caller of this log or line number, but I only get the 

```
io.netty.util.internal.logging.Slf4JLogger.debug(Slf4JLogger.java:76) 
```

Please check it , thank you!

**Comment by normanmaurer** [comment]
I just checked here and it shows the correct log number. Maybe something bad with your setup ?

**Comment by looly** [comment]
http://stackoverflow.com/questions/29093144/slf4j-decorator-is-logging-the-decorator-fqcn-not-the-calling-fqcn

I saw the source code of netty  logging package, maybe this problem. Because of FQCN, log only show  decorator class line number, not the invoking class.

![image](https://cloud.githubusercontent.com/assets/1432613/18422528/07024716-78cf-11e6-8819-04fd605534f5.png)
