### ISSUE TITLE
Why does Netty not support allocating ByteBufs off heap?

### ISSUE THREAD

**Issue by buchgr** [netty/netty#5803]
The backing memory of a `ByteBuf` can be allocated off heap, but not the object itself. Is there a particular reason for that?

**Comment by mheath** [comment]
Can you even allocate a Java object off-heap? How would the garbage collector know when to remove the object?

**Comment by JuKu** [comment]
@mheath You can do this with sun.misc.Unsafe. :D 
Then you have to clean your object yourself, the garbage collector than doesnt knows this object. :D

**Comment by Underbalanced** [comment]
@buchgr @JuKu What would be the gain for having this implemented? I would imagine that would take some time to add correctly.

**Comment by buchgr** [comment]
@Underbalanced 

Typically a considerable portion of the JVM heap is `ByteBuf` objects. We already do reference counting, so I imagine this could be implemented transparently in the `Recycler`, without any public API changes.

As for the benefit, I imagine it would help reduce GC times, as those objects no longer have to be copied. To be fair, it would mostly affect full GCs due to the implied longevity of pooled objects.

**Comment by Underbalanced** [comment]
@buchgr 
That thought actually bypassed my mind. I have not really checked my ByteBuf objects and and GC thought I do allocate tons of small messages all the time (Massive Multiplayer Game).

**Comment by CodingFabian** [comment]
Depending on the scope of the object, they might be allocated on stack rather than on-heap. The backing array cannot be allocated on the stack.

**Comment by buchgr** [comment]
@CodingFabian 

I think that's rather unlikely for most Netty use cases, where one eventually sends the ByteBuf through the pipeline.

**Comment by evgenyvsmirnov** [comment]
I think such implementation can be useful when it is necessary to pass some data to third party code or legacy code (not necessarily as ByteBuf itself but as Closable for example) and streaming is not possible. 

I would rather think of moving data on disk as soon as a specified threshold is reached … HttpObjectAggregator would benefit from such BB version.

**Comment by maseev** [comment]
@buchgr Why not simply pool `ByteBuf` objects? You can definitely allocate a chunk of memory through `sun.misc.Unsafe`, but you would need an enclosing object in order to make it possible to use (set fields, get fields of your 'object' etc.) anyway.
The idea itself is great. It would be especially useful for people who care about GC pauses (low-latency network applications).

**Comment by maseev** [comment]
Just checked it. You're right. According to YourKit `java.nio.DirectByteBuffer` objects are the ones which cause GC to pause. At least `java.nio.DirectByteBuffer` is at the top of the allocation table :disappointed:

**Comment by normanmaurer** [comment]
@maseev can you share the profiler snapshot?

**Comment by maseev** [comment]
@normanmaurer Should I attach the profiler snapshot to this issue or send it to you by email?

**Comment by normanmaurer** [comment]
if you can attach it do it... if not send via email or upload it somewhere :) Thanks again

**Comment by maseev** [comment]
@normanmaurer Here you go: [EchoServer-2016-12-06.snapshot.zip](https://github.com/netty/netty/files/633661/EchoServer-2016-12-06.snapshot.zip)

**Comment by normanmaurer** [comment]
@maseev can I see the code of the server as well ?

**Comment by maseev** [comment]
@normanmaurer Here [it](https://github.com/maseev/echo) is. And [here's](https://github.com/maseev/echo/blob/master/server/src/main/java/io/github/maseev/echo/EchoServer.java#L68) the pipeline I collected the memory profiler snapshot for.

**Comment by normanmaurer** [comment]
@maseev makes sense.. I think if you would use the epoll transport on linux it will eliminate these allocations. Can you try ?

**Comment by maseev** [comment]
@normanmaurer It did the trick. Now there are only 28 `java.nio.DirectByteBuffer` object that have been GCed. Here's the profiler snapshot in case you're interested: [EchoServer-2016-12-06-1.snapshot.zip](https://github.com/netty/netty/files/633792/EchoServer-2016-12-06-1.snapshot.zip)

**Comment by normanmaurer** [comment]
@maseev you are welcome ;) 

The reason is that in our native transport we not need to create a new `ByteBuffer` for a write and just act directly on the memory addresses.

**Comment by maseev** [comment]
@normanmaurer That's great! Kudos to you guys! :smile:

**Comment by normanmaurer** [comment]
Let me close this...
