### ISSUE TITLE
OioEventLoopGroup's schedule throws UnsupportedOperationException

### ISSUE THREAD

**Issue by p0mp0k0** [netty/netty#5805]
I use netty to operate serial port with rxtx accroding to the rxtx sample, and try to reconnect when the connection broken, I followed the trusting's code at stackoverflow to schedule check, but application throws UnsupportedOperationException. I checked the source code, found these code in OioEventLoopGroup.java
    public class OioEventLoopGroup extends ThreadPerChannelEventLoopGroup
and these code in  AbstractEventExecutorGroup.java
    public <V> ScheduledFuture<V> schedule(Callable<V> callable, long delay, TimeUnit unit) {
        return this.next().schedule(callable, delay, unit);
    }
these code in ThreadPerChannelEventLoopGroup.java
   public EventLoop next() {
        throw new UnsupportedOperationException();
    }

so, it always throw UnsupportedOperationException.
Does ThreadPerChannelEventLoopGroup not support schedule?
Thanks.

**Comment by normanmaurer** [comment]
@p0mp0k0 yes its not supported at all with ThreadPerChannelEventLoopGroup

**Comment by p0mp0k0** [comment]
Do you mean that OioEventLoopGroup  does not support shcedule?
