### ISSUE TITLE
Question: Correct way to allocate ByteBuf

### ISSUE THREAD

**Issue by JuKu** [netty/netty#5810]
Hi,

Whats the correct way to create / get an new ByteBuf?

Currently i use Unpooled.buffer().
```java
ByteBuf content = Unpooled.buffer();
```

Is there an better way? Maybe using pooled buffers?
Can you add such things into your documentation?

**Comment by johnou** [comment]
Set the pooled buffer allocator in your bootstrap then alloc the buffers via context / channel reference. There are plenty of usages in the user guide or examples.. http://netty.io/wiki/user-guide-for-4.x.html . 

As I mentioned in https://github.com/netty/netty/issues/5793 please use SO for questions regarding usage.

**Comment by JuKu** [comment]
@johnou In your documentation / examples isnt any buffer allocator in the bootstrap set.

```java
ServerBootstrap b = new ServerBootstrap(); // (2)
b.group(bossGroup, workerGroup)
    .channel(NioServerSocketChannel.class) // (3)
    .childHandler(new ChannelInitializer<SocketChannel>() { // (4)
        @Override
        public void initChannel(SocketChannel ch) throws Exception {
            ch.pipeline().addLast(new DiscardServerHandler());
        }
    })
    .option(ChannelOption.SO_BACKLOG, 128)          // (5)
    .childOption(ChannelOption.SO_KEEPALIVE, true); // (6)

    // Bind and start to accept incoming connections.
    ChannelFuture f = b.bind(port).sync(); // (7)
```

I think it doesnt makes sense, if every user post an question at stackoverflow. The documentation is responsible to answer such questions!
But if i am honestly, the documentation answer only such beginner questions, no advanced things.
The documentation does only contains some specific examples yet, or?

**Comment by doom369** [comment]
@JuKu I think recommended way would be : 

`
//using default allocator
ByteBuf buf = ctx.alloc().buffer();
or
ByteBuf buf = channel.alloc().buffer();
or
ByteBuf buf = PooledByteBufAllocator.DEFAULT.buffer();
`

all this 3 methods are doing the same. Your approach is also fine, however it is uses unpooled allocator. While Netty default allocator in latest version is Pooled (should be a bit faster against Unpooled).

**Comment by Scottmitch** [comment]
as @doom369 suggests generally you want to use the allocator from the ChannelHandlerContext or Channel if available, unless you need a specific allocator for a good reason (static allocations, wrapping heap based arrays, etc..)
