### ISSUE TITLE
The example of websocketx doesn't work with jdk 1.6

### ISSUE THREAD

**Issue by joymufeng** [netty/netty#5812]
This issue exists in netty-4.1.5.Final.
**Run server.WebSocketServer and client.WebSocketClient with JDK 1.6.0_45**
Input "hello" in WebSocketClient's console, no response back:
```
WebSocket Client connected!
hello
```
After switch to JDK 1.7.0_79, it works fine.

**Comment by normanmaurer** [comment]
Can you check with 4.1 branch ?

**Comment by joymufeng** [comment]
Great! It works fine with 4.1 branch.
