### ISSUE TITLE
libnetty-transport-native-epoll.so is 64 bits only. How to use epoll classes on 32 bit Android devices?

### ISSUE THREAD

**Issue by hbli** [netty/netty#5813]
Dear developer,

Currently libnetty-transport-native-epoll.so has only the 64 bit version. I don't think it is possible to use Epoll classes on Android devices. Could you please build a 32 bit version? For Android application, do we need to rebuild the library with Android NDK? Thank you for your time and looking forward to your feedback,

**Comment by normanmaurer** [comment]
@hbli why you even need it on android ? We usually only build 64 versions of the native libs.

**Comment by 4ntoine** [comment]
I'd love to try gRPC as JNI replacement: gRPC service on C++ side and client on Java side. Some details https://stackoverflow.com/questions/65389428/how-to-connect-to-grpc-c-inprocesschannel-not-from-c

**Comment by 4ntoine** [comment]
@hbli were you able to build it for Android?

**Comment by 4ntoine** [comment]
JIC trying to do it here: https://github.com/4ntoine/netty/tree/epoll-android

**Comment by 4ntoine** [comment]
now [works](https://github.com/4ntoine/JniBenchmarking/blob/a056d4030fc0d9841c48d62f6209b2ca773a18d5/rpc/src/androidTest/java/com/eyeo/ctu/rpc/AndroidRpcTest.kt#L166) for me, [MR](https://github.com/netty/netty/pull/10881 )
