### ISSUE TITLE
Override allocator delegate for receive buffers

### ISSUE THREAD

**Issue by vkostyukov** [netty/netty#5819]
While the advantages of using pooling allocations are clear for everybody, there are projects that can't afford go that road just immediately (by the variety of reasons), but require some reasonable migration path. For example, in Finagle we decided to stay compatible with the Netty 3 at the first so we can safely migrate users maintaining the same behaviour and performance.

Simply speaking we had no choice, but to use unpooled allocators in the beginning and we're super excited about trying out `RecvByteBufAllocator` that supposed to override the receive buffer allocators. This sounded like what we wanted to do to be as-close-as-possible to the Netty 3 implementation, which uses some primitive polling for receive buffers.

Turns out `RecvByteBufAllocator` is not an allocator itself, but something that guesstimates a size and reuses and channel's allocator. Not exactly what we wanted since our default allocator is unpolled.

To make sure this whole story makes some sense, we forked `AdaptiveRecvByteBufAllocator` and made it use the allocator we pass in the constructor (default pooled allocator) instead of the one passed into an `allocate` function (unpooled allocator). Results were quite shocking - we save  **a lot** of CPU. So this is the game changer for us (and I hope somebody else).

In this ticket, I'm proposing to **allow users the override the receive buffer allocator delegate** passed to the `RecvByteBufAllocator`. We can use channel's allocator by default to be backward compatible, but allow users to pass their own thing.

Given that `RCVBUF_ALLOCATOR` is taken I assume we can use `RCVBUF_ALLOCATOR_DELEGATE` (the best name I can come up with) and point it to `ALLOCATOR` by default.

What do people think about that tiny change? Is that something Netty community (except for Twitter) would be interesting in? 

I'm happy to open a PR with the change, just decided to start the thread before and get some feedback.

**Comment by normanmaurer** [comment]
@vkostyukov I am not sure if I really understand :) Can you show me the change you did ?

**Comment by johnou** [comment]
Do you have benchmarks or profiling which you can share wrt CPU usage?

**Comment by vkostyukov** [comment]
Ah sorry @normanmaurer I wasn't clear enough.

What I want to do is to use different allocator (different to channel's allocator) for receive buffers. So I'm proposing to add a new allocator (and a channel option) to a channel so it can be passed to `RCVBUF_ALLOCATOR`. This would allow us to distinct receive buffer allocators (which we want to be pooled) from everything else (which we want to be unpooled).

**Comment by buchgr** [comment]
@vkostyukov so you want to use a pooled allocator for reading data off the wire and unpooled for everything else?

**Comment by vkostyukov** [comment]
@johnou Sorry I don't have a benchmark, but we did test/canary this change on one of the production services at Twitter. We reliably reproduced the results on different hardware platforms: ~10% less CPU and 25% less p99 latency (maintaining the same throughput).

**Comment by normanmaurer** [comment]
@vkostyukov I see... Just be aware that this may still "leak" pooled buffers to the user. As a received buffer may be received by the user.

**Comment by vkostyukov** [comment]
Yes, that's a very good point @normanmaurer. We're safe here since we copy everything to the unpooled heap in the very first handler. But this is a very different story and problem deserves a blog post of something. We can chat more when you're in HQ this week :)

**Comment by vkostyukov** [comment]
So what do people think? Can this be useful in general?

I totally get that our use case is somewhat special so not everybody mixing pooled/unpooled allocators in their pipelines/apps. That's why I decided to ask here is there are any other possible use cases for that so it deserves it's own channel option.

Even for the apps that end-to-end pooling/unpooling I can this distinction might be useful. Some example:

- Disable leaks only for non-receive buffer allocators (unpooled)
- Supply different area/cache sizes for receive and non-receive allocators (pooled)

Does it make any sense? Or is it just me trying to come up with some intrusive use case to justify the change?

**Comment by normanmaurer** [comment]
@vkostyukov I am not sure why you need any changes for this in netty. Why not just do something like this:

```java
public class MyRecvByteBufAllocator extends AdaptiveRecvByteBufAllocator {
    
    private final ByteBufAllocator allocator;
    
    public MyRecvByteBufAllocator(ByteBufAllocator allocator) {
        this.allocator = allocator;
    }

    @Override
    public Handle newHandle() {
        final MaxMessageHandle handle = (MaxMessageHandle) super.newHandle();
        return new MaxMessageHandle() {
            @Override
            public int guess() {
                return handle.guess();
            }

            @Override
            public ByteBuf allocate(ByteBufAllocator alloc) {
                return super.allocate(allocator);
            }

            @Override
            public void reset(ChannelConfig config) {
                handle.reset(config);
            }

            @Override
            public boolean continueReading() {
                return handle.continueReading();
            }

            @Override
            public void readComplete() {
                handle.readComplete();
            }

            @Override
            public int attemptedBytesRead() {
                return handle.attemptedBytesRead();
            }

            @Override
            public void attemptedBytesRead(int bytes) {
                handle.attemptedBytesRead(bytes);
            }
        };
    }
}
```

Then just set it via `ChannelOption. RCVBUF_ALLOCATOR`

**Comment by vkostyukov** [comment]
Thanks @normanmaurer! This is nearly an exact copy of what I have right now (and it works just fine). I was just wondering if we need to have a generic way of doing that. Please, don't get me wrong, I'm totally happy to keep using this approach internally, but decided to check if people think this might be useful for a general case.

**Comment by vkostyukov** [comment]
Actually, this version is much more clear than mine! I forgot I can call `super.newHandler` and had to fork the implementation since `HandleImpl` is private. Thanks a lot for the help on this, @normanmaurer! I think I can live with having this wrapped `MaxMessageHandle` - the change is super small now and doesn't seem to cause any maintenance burden. Thanks again!

**Comment by normanmaurer** [comment]
@vkostyukov yay... happy to help :)

**Comment by vkostyukov** [comment]
Turns out (thanks @kevinoliver!), there `DelegatingHandle` that makes it a pure joy to implement this!

**Comment by normanmaurer** [comment]
@vkostyukov high-five to @kevinoliver

**Comment by kevinoliver** [comment]
no, but really, need a :beer: for @normanmaurer. thanks!

**Comment by Scottmitch** [comment]
late to the party ... but using `DelegatingHandle` sgtm. If we were to accept this upstream we would also need to ensure the "copy" semantics are also always used when this `AdaptiveRecvByteBufAllocator` is in use (to avoid leaks as mentioned by @normanmaurer) ... maybe easier / cleaner just to keep it at the higher level?
