### ISSUE TITLE
NetUtil.bytesToIpAddress broken for IPv4

### ISSUE THREAD

**Issue by henrik-lindqvist** [netty/netty#5821]
For textual IPv4 representation the method incorrectly performs bit shifts on the array bytes.

4.1.5.Final

**Comment by normanmaurer** [comment]
@henrik-lindqvist maybe you can provide a PR ?

**Comment by Scottmitch** [comment]
or provide a link to an RFC or specification which describes expected behavior and an input which doesn't produce the expected output.

**Comment by henrik-lindqvist** [comment]
NetUtil.bytesToIpAddress(new byte[] { 83, -1, -20, 16 }, 0, 4) returns "0.255.255.16" not "83.255.236.16" as expected. See initial post for cause.
