### ISSUE TITLE
MQTT codec : why will message is a "simple" String

### ISSUE THREAD

**Issue by ppatierno** [netty/netty#5828]
Hi,

why the choice to have the will message in the CONNECT message as a simple String in the MqttConnectPayload class and not a ByteBuf like the payload field in the MqttPublishMessage class ?

Thanks,
Paolo.

**Comment by normanmaurer** [comment]
@ppatierno because we thought this is the most useful. Why you want it to be a `ByteBuf` ?

**Comment by ppatierno** [comment]
The encoding for the payload of the MqttPublishMessage uses a ByteBuf and it's right because the payload of a published MQTT message (PUBLISH) must be considered as something binary (not necessary printable characters like for a String). For the same reason the will message inside CONNECT should be something binary; when the MQTT broker has to send the will message, it builds a PUBLISH message and in this case putting the will message into a binary payload. Why restricting the will payload to be a String ?

**Comment by ppatierno** [comment]
so @normanmaurer does it make sense to you ? Or do you have any concerns about it ?

**Comment by normanmaurer** [comment]
@ppatierno I think it makes sense that said I think we not really can change it without breaking the API. Or I am missing anything ?

**Comment by ppatierno** [comment]
@normanmaurer could we ....

- a new constructor for MqttConnectPayload with ByteBuf payload as parameter
- changing the backing field from String to ByteBuf
- the problem is that we can't change the willMessage() which returns a String (we brake the API). It should build the String from the backing ByteBuf; then we need another method willMessageAsBytes() or something like that to return the ByteBuf

I see this way to avoid breaking API even if it's not so clear.

Do you think I missed something as well ?

**Comment by normanmaurer** [comment]
@ppatierno I think this will not work as if we wrap a `ByteBuf` we also need a way to release it.

**Comment by ppatierno** [comment]
@normanmaurer does it mean to implement the ByteBufHolder interface for the MqttConnectPayload class ? so having new methods that today no people are using ... so we can't brake their software ?

I can be wrong ... I'm quite new to the awesome Netty :-)

**Comment by normanmaurer** [comment]
@ppatierno yes... The problem is once it implements `ByteBufHolder, the user is responsible to call `release()` so we can not add this later on.

**Comment by ppatierno** [comment]
@normanmaurer understood ... you are absolutely right (it couldn't be different ;)). 
I understand the point to not brake the API but it's a big limitation on the will message.
It's sad that we can't change it forever ...

**Comment by ppatierno** [comment]
@normanmaurer is this the first time you have to handle such situation on Netty ?

**Comment by normanmaurer** [comment]
@ppatierno we could maybe add some new constructor param which allow to configure that a `ReferenceCounted` `MqttConnectPayload` is used. In this case the user would be aware that he needs to take special action. 

This is the best that I can think of atm,

**Comment by ppatierno** [comment]
@normanmaurer if I can help on that with a PR ... do you mean some new constructor param to the MqttConnectPayload class ? Should we derive this class from ReferenceCounted ? Should we change willMessage field from String to ByteBuf ?

Can you give me more information about your idea ? Thanks !

**Comment by ppatierno** [comment]
@normanmaurer any news on that ? I'd like to provide my support but your idea is still not so clear to me :(

**Comment by normanmaurer** [comment]
@ppatierno sorry I missed this... We need a new pojo to do this as we can not change the return type as I said before. And yes if it holds a ByteBuf it should extend ReferenceCounted or extend ByteBufHolder

**Comment by ppatierno** [comment]
@normanmaurer when you say "a new pojo" do you mean a new class instead of MqttConnectPayload which extend ReferenceCounter (or extend ByteBufHolder) and using ByteBuf for the willMessage field ? What about the MqttConnectMessage class which uses the MqttConnectPayload ?

**Comment by mtaylor** [comment]
@normanmaurer @ppatierno I also ran into this recently with MQTT protocol handler in Apache Artemis.  It'd be preferable if this was passed along as a buffer vs a UTF8 encoded string.  I'd expect that this may cause problems if the will message payload is not a well formed UTF8 string?  

The MQTT spec says that the will message has no encoding only 2 byte length, the content could be anything, serialized object, application specific encoding etc...

**Comment by suyambuganesh** [comment]
I think this issue can be closed. Check the issue https://github.com/netty/netty/issues/6750

**Comment by normanmaurer** [comment]
You are right
