### ISSUE TITLE
HttpServerCodec annot encode a respons e to HEAD request with a 'content-encoding: chunked' header

### ISSUE THREAD

**Issue by bryce-anderson** [netty/netty#5831]
Netty versions: 4.x
### Context

It is valid to send a response to a HEAD request that contains a `transfer-encoding: chunked` header, but there is no way to do this using the netty4 `HttpServerCodec`.
### Root of the problem

The root cause is that the netty4 `HttpObjectEncoder` will [transition to the state](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectEncoder.java#L80) `ST_CONTENT_CHUNK` and the only way to transition back to `ST_INIT` is through the `encodeChunkedContent` method which [will write the terminating length](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectEncoder.java#L163-L180) (`0\r\n\r\n\r\n`), a protocol error when responding to a HEAD request. I don't believe this is a problem with netty3: it looks like submitting a new `HttpMessage` [effectively resets the encoder](https://github.com/netty/netty/blob/3.10/src/main/java/org/jboss/netty/handler/codec/http/HttpMessageEncoder.java#L62-L101), while the same strategy with netty4 [results in an illegal state exception](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectEncoder.java#L68-L70).
### Workaround

The `content-encoding` MAY be omitted ([RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3.2)), but it would be nice to have.

**Comment by normanmaurer** [comment]
@bryce-anderson interested to provide a PR + unit test ?

**Comment by bryce-anderson** [comment]
@normanmaurer Do you mean PR to fix or PR to demonstrate? I'm happy to provide a PR either way, I just want to be clear on what PR we want. 😄

If we are talking about a fix, the easy solution is to adopt the netty3 behavior of resetting the encoder on every new `HttpMessage`, but before making the change I think it's worth quickly discussing if that is an acceptable solution: in my minds eye someone introduced that `IllegalStateException` for a reason.

**Comment by normanmaurer** [comment]
let me fix this...

**Comment by normanmaurer** [comment]
@bryce-anderson actually I not understand how this happens. Can you provide a unit test that shows it ?

**Comment by normanmaurer** [comment]
@bryce-anderson nevermind... I think I understand it now

**Comment by bryce-anderson** [comment]
Ah, and I just hacked together an example! Just in case, here it is: https://github.com/bryce-anderson/netty/commit/0fdfcacb67eff649699d266ea6425cb2b93b1218

I apologize in advance, there is probably a cleaner way to do it.

**Comment by normanmaurer** [comment]
@bryce-anderson PTAL at https://github.com/netty/netty/pull/5846

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5846
