### ISSUE TITLE
Regression: JVM crash in tcnative-boringssl during mutual TLS handshake with chain

### ISSUE THREAD

**Issue by douglasc-nflx** [netty/netty#5841]
Netty version: 4.1.5.Final

Context:
Initiating client TLS negotiation with a certificate chain (client cert + trust chain) on netty 4.1.5.Final with netty-tcnative-boringssl-static 1.1.33.Fork21 on Ubuntu 14.04 causes the JVM to crash with SIGABRT / exit code 134.

This scenario worked with netty 4.1.3.Final / netty-tcnative-boringssl-static 1.1.33.Fork19 and prior.  It still succeeds when the client supplies only a single cert with no trust chain.

Steps to reproduce:
Example program to reproduce posted using grpc 1.0.1:
https://github.com/douglasc-nflx/netty-tcnative-crash-demo

$ java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

$ uname -a
Linux darkstar 3.13.0-95-generic #142-Ubuntu SMP Fri Aug 12 17:00:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@douglasc-nflx will check

**Comment by normanmaurer** [comment]
can you also try with 4.1.6.Final-SNAPSHOT which uses a new (netty-tcnative version) ?

**Comment by normanmaurer** [comment]
@douglasc-nflx can you provide me a full working reproducer ? I tried `gradle run` but this not works as a standalone

**Comment by douglasc-nflx** [comment]
Where can I find 4.1.6.Final-SNAPSHOT, and which tcnative does it do I need to build it?  We tried using 4.1.5-Final with the latest netty-tcnative-boringssl-static 1.1.33.Fork22 and observe the same crash.

It runs as a standalone program on my Ubuntu 14.04 host:

$ sudo apt-get install gradle
$ sudo ln -s /usr/lib/jvm/java-8-oracle /usr/lib/jvm/default-java
$ gradle run


:compileJava
:processResources
:classes
:run
Sep 21, 2016 9:13:13 AM io.grpc.internal.ManagedChannelImpl <init>
INFO: [ManagedChannelImpl@543788f3] Created with target localhost:4999
:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 134

**Comment by normanmaurer** [comment]
@douglasc-nflx where can I see the crash log ?

**Comment by normanmaurer** [comment]
@douglasc-nflx ah sorry I missed it will cause a "SIGABRT". Let me check whats wrong

**Comment by luengnat** [comment]
Looks like it crashes in CRYPTO_refcount_dec_and_test_zero method

```
Thread 26 Crashed:: Java: grpc-default-worker-ELG-4-1
0   libsystem_kernel.dylib        	0x00007fff8eabcf06 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff9356b4ec pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff9a6ad6df abort + 129
3   libnetty-tcnative-osx-x86_644614122747330544519.dylib	0x000000012b564338 CRYPTO_refcount_dec_and_test_zero + 72
4   libnetty-tcnative-osx-x86_644614122747330544519.dylib	0x000000012b510f61 asn1_item_combine_free + 113
5   libnetty-tcnative-osx-x86_644614122747330544519.dylib	0x000000012b510ee7 ASN1_item_free + 23
6   libnetty-tcnative-osx-x86_644614122747330544519.dylib	0x000000012b4892bb Java_org_apache_tomcat_jni_SSL_parseX509Chain + 251
7   ???                           	0x000000010f4179d4 0 + 4550916564
8   ???                           	0x000000010f407dd0 0 + 4550852048
9   ???                           	0x000000010f408040 0 + 4550852672
10  ???                           	0x000000010f4007a7 0 + 4550821799
11  libjvm.dylib                  	0x000000010de8bf06 JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*) + 1710
12  libjvm.dylib                  	0x000000010dec3111 jni_invoke_nonstatic(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, Thread*) + 748
13  libjvm.dylib                  	0x000000010deb31bb jni_CallObjectMethod + 363
14  libnetty-tcnative-osx-x86_644614122747330544519.dylib	0x000000012b48c1bf cert_requested + 479
15  libnetty-tcnative-osx-x86_644614122747330544519.dylib	0x000000012b4965de ssl3_send_client_certificate + 190
16  libnetty-tcnative-osx-x86_644614122747330544519.dylib	0x000000012b494295 ssl3_connect + 357
17  libnetty-tcnative-osx-x86_644614122747330544519.dylib	0x000000012b4a6862 ssl_read_impl + 194
18  ???                           	0x000000010f4179d4 0 + 4550916564
19  ???                           	0x000000010f407d00 0 + 4550851840
20  ???                           	0x000000010f407d00 0 + 4550851840
21  ???                           	0x000000010f408040 0 + 4550852672
22  ???                           	0x000000010f408040 0 + 4550852672
23  ???                           	0x000000010f408040 0 + 4550852672
24  ???                           	0x000000010f407a90 0 + 4550851216
25  ???                           	0x000000010f4082bd 0 + 4550853309
26  ???                           	0x000000010f4082bd 0 + 4550853309
27  ???                           	0x000000010f408302 0 + 4550853378
28  ???                           	0x000000010f4082bd 0 + 4550853309
29  ???                           	0x000000010f4082bd 0 + 4550853309
30  ???                           	0x000000010f408114 0 + 4550852884
31  ???                           	0x000000010f408302 0 + 4550853378
32  ???                           	0x000000010f4082bd 0 + 4550853309
33  ???                           	0x000000010f4082bd 0 + 4550853309
34  ???                           	0x000000010f408114 0 + 4550852884
35  ???                           	0x000000010f408302 0 + 4550853378
36  ???                           	0x000000010f4082bd 0 + 4550853309
37  ???                           	0x000000010f4082bd 0 + 4550853309
38  ???                           	0x000000010f4082bd 0 + 4550853309
39  ???                           	0x000000010f4082bd 0 + 4550853309
40  ???                           	0x000000010f408302 0 + 4550853378
41  ???                           	0x000000010f408302 0 + 4550853378
42  ???                           	0x000000010f4007a7 0 + 4550821799
43  libjvm.dylib                  	0x000000010de8bf06 JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*) + 1710
44  libjvm.dylib                  	0x000000010de8c694 JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*) + 356
45  libjvm.dylib                  	0x000000010de8c840 JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*) + 74
46  libjvm.dylib                  	0x000000010dee7029 thread_entry(JavaThread*, Thread*) + 124
47  libjvm.dylib                  	0x000000010e1085ab JavaThread::thread_main_inner() + 155
48  libjvm.dylib                  	0x000000010e109c98 JavaThread::run() + 450
49  libjvm.dylib                  	0x000000010e02833a java_start(Thread*) + 246
50  libsystem_pthread.dylib       	0x00007fff9356899d _pthread_body + 131
51  libsystem_pthread.dylib       	0x00007fff9356891a _pthread_start + 168
52  libsystem_pthread.dylib       	0x00007fff93566351 thread_start + 13
```

**Comment by douglasc-nflx** [comment]
You may fork https://github.com/douglasc-nflx/netty-tcnative-crash-demo and/or include this code in netty if needed.  Thanks.

**Comment by luengnat** [comment]
Is it a double free bug somewhere caused by https://github.com/netty/netty/commit/7d774584c8fbf6652e1efbaf80afd64d6b82f324 ?

**Comment by normanmaurer** [comment]
@douglasc-nflx is that I think I know what causes the problem and currently writing a unit test.  Thanks for providing the code!

@luengnat no its not related.

**Comment by normanmaurer** [comment]
@douglasc-nflx this fixes the problem: https://github.com/netty/netty-tcnative/pull/190 ... Working on an self-contained test-case now.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5875 and netty/netty-tcnative#190
