### ISSUE TITLE
h2childchan: Stream active and closed events

### ISSUE THREAD

**Issue by buchgr** [netty/netty#5853]
The `Http2FrameCodec` emits `Http2StreamActive` and `Http2StreamClosed` events for whenever a stream becomes active or is closed. 

I would argue that emitting an event on stream active is only useful when creating a new stream through a HEADERS frame, as it might fail due to e.g. stream id exhaustion or max concurrent streams. In the case of an incoming active stream, it does not seem useful as the event is immediatelly followed by the first HEADERS frame of that stream anyway.

Further, I would argue that a stream closed event is never useful, as one usually wants to act differently depending on the cause. That is, one wants to take different action depending on whether the stream was closed due to END_STREAM, RST_STREAM (remote / local), Channel inactive, etc...

So I think it make sense to update the frame codec, to only emit a active stream event when creating a new stream locally, and get rid of the closed stream event completely.

**Comment by buchgr** [comment]
Even in the case when creating an outgoing stream, one could just listen to the write future. So I think it can be removed completely.

**Comment by normanmaurer** [comment]
@buchgr isnt at least the "active" event useful as otherwise a user would have to check if the stream was active on each header processing to do something to init the stream one time.

**Comment by buchgr** [comment]
I have yet to open a PR, but I have reworked the `Http2FrameCodec` a bit and removed the active and closed event. Here is what it will eventually look like without events. I think that's much easier and netty-like.

```java

class MyChannelHandler extends Http2ChannelDuplexHandler {

  void createNewOutboundStream() {
    // newStream() is part of the Http2ChannelDuplexHandler
    final Http2Stream stream = newStream();
    // Attach some stream specific state, that will be attached to all frames of that stream
    // and automatically cleaned up when the stream is closed.
    stream.managedState(new StreamSpecificState());

    ctx.write(new DefaultHttp2HeadersFrame(headers).stream(stream))
        .addListener(new ChannelFutureListener() {
        public void operationComplete(ChannelFuture future) {
        if (future.isSuccess()) {
          // stream active
          System.out.println(stream.id());
          stream.closeFuture().addListener(new DoSomethingOnStreamClosed());
        } else {
           if (future.cause() instanceof Http2NoMoreStreamIdsException) {
             ...
           } else if (...) {
              ...
           }
       }
       }
    }
  }

  @Override
  public void channelRead(ChannelHandlerContext ctx, Object msg) {
    if (msg intstanceof Http2HeadersFrame) {
       Http2HeadersFrame headersFrame = (Http2HeadersFrame) msg;
       Http2Stream stream = headersFrame.stream();

       if (stream.managedState() == null) {
          // New inbound active stream
       }
    }
  } 
}
```

WDYT?

**Comment by buchgr** [comment]
Will be removed by #5914
