### ISSUE TITLE
http/2 cleartext upgrade + prior knowledge

### ISSUE THREAD

**Issue by mosesn** [netty/netty#5857]
http/2 cleartext has two mechanisms, the http/1.1 upgrade header, and the connection preface.  Netty supports inspecting the connection preface in Http2ConnectionHandler, and supports upgrading via the http/1.1 upgrade header in HttpServerUpgradeHandler + Http2ServerUpgradeCodec.  However, it's not obvious how to combine the two of these into a single piece.  One difficulty is that there are several moving pieces–we need an HttpCodec, and an HttpServerUpgradeHandler, which comes with an Http2ServerUpgradeCodec and the Http2Codec we will want to replace the HttpCodec with.

This looks like:

`==Bytes==>[Early stuff in pipeline]==>[HttpCodec]==HttpRequest==>[HttpServerUpgradeHandler]===>[Rest of the pipeline]==END`

which should be transformed into

`==Bytes==>[Early stuff in pipeline]==>[Http2Codec]==END`
which has child handlers which look like
`==Http2Frame==>[Rest of the pipeline]`

When we want to add prior knowledge support, the prior knowledge support must be before the HttpCodec, but must do the same work as the HttpServerUpgradeHandler.

`==Bytes==>[Early stuff in pipeline]==>[Prior Knowledge Upgrader]==>[HttpCodec]==HttpRequest==>[HttpServerUpgradeHandler]===>[Rest of the pipeline]==END`

but it still transforms to the same thing as before.

One thing we were considering was how we might add it simply to the Http2ServerUpgradeCodec, so that it installs the prior knowledge upgrader before the SourceCodec in the pipeline when it's installed.  Another possible way was to have a separate PriorKnowledgeHandler which is installed separately from the HttpServerUpgradeHandler.

Please let us (me + @nhnFreespirit) know what you think would be the right way forward here.

cc @Scottmitch @buchgr @normanmaurer @ejona86

**Comment by Scottmitch** [comment]
related to https://github.com/netty/netty/issues/4438

**Comment by normanmaurer** [comment]
@mosesn @nhnFreespirit @Scottmitch is this somehow related to https://github.com/netty/netty/pull/6430 ?

**Comment by nhnFreespirit** [comment]
@normanmaurer yeah, same thing. 

Because we never really heard back on this one, I went ahead and added an implementation to Finagle in https://github.com/twitter/finagle/commit/b46a3f96002da7a7d50d197b8907d968fc4640ca

Since it is basically just a Netty ChannelInboundHandlerAdapter I did plan on eventually pushing it upstream, but never got around to it.

**Comment by normanmaurer** [comment]
@nhnFreespirit sorry for not come back to you... So does the one in the PR work for you or any changes needed ?

**Comment by nhnFreespirit** [comment]
I added sone comments on the PR. Mainly I'd like to see handling of buffers containing a partial preface.

**Comment by normanmaurer** [comment]
I think this was fixed by https://github.com/netty/netty/issues/6496 . Please reopen if this is not the case
