### ISSUE TITLE
HttpUtil.getContentLength(HttpMessage, long) throws unexpected NumberFormatException

### ISSUE THREAD

**Issue by ewie** [netty/netty#5861]
The Javadocs of `HttpUtil.getContentLength(HttpMessage, long)` and its `int` overload state that the provided default value is returned if the Content-Length value is not a number. `NumberFormatException` is thrown instead [1] causing the method to behave like `HttpUtil.getContentLength(HttpMessage)` where the exception is explicitly documented for this case.

[1] https://github.com/netty/netty/blob/149916d052180dd2b0e0e98598f349454ea200ba/codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java#L187

**Comment by normanmaurer** [comment]
@ewie sounds like a bug... let me fix it.

**Comment by normanmaurer** [comment]
@ewie should be fixed by https://github.com/netty/netty/pull/5877

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5877
