### ISSUE TITLE
Http2EventAdapter's onUnknownFrame() is missing throws Http2Exception

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#5862]
`Http2EventAdapter` implements the `Http2FrameListener` interface but implements the `#onUnknownFrame(...)` method without the interface's `throws Http2Exception`.

... causing compiler errors down the road if you're trying to implement a delegate or something like that.

**Comment by normanmaurer** [comment]
Let me fix it

**Comment by normanmaurer** [comment]
Fixes by https://github.com/netty/netty/pull/5876
