### ISSUE TITLE
io.netty.buffer.AbstractUnpooledSlicedByteBuf.getBytes(int index, ByteBuffer dst) bug

### ISSUE THREAD

**Issue by patrickseptem** [netty/netty#5864]
The checkIndex0 method will throw java.lang.IndexOutOfBoundsException when I pass a dst which remaining greater than the buf's data size. 

The 4.0.23 version doesn't have this issue, while 4.0.36 & above version all get this issue. Could you take a look? Thanks.

**Comment by normanmaurer** [comment]
@patrickseptem can you provide a reproducer ?

**Comment by patrickseptem** [comment]
import static org.junit.Assert.*;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.Unpooled;

import java.nio.ByteBuffer;

import org.junit.Test;

public class NettyTest {

	@Test
	public void test() {
		ByteBuffer nioBuffer = ByteBuffer.allocate(1000);
		ByteBuf wrappedBuffer = Unpooled.wrappedBuffer("abcdefg".getBytes(), 1, 6);
		wrappedBuffer.getBytes(wrappedBuffer.readerIndex(), nioBuffer);
		assertEquals("bcdefg", new String(nioBuffer.array()).trim());
	}
}

**Comment by normanmaurer** [comment]
@patrickseptem actually I think this is correct as stated in the javadocs:

```
    /**
     * Transfers this buffer's data to the specified destination starting at
     * the specified absolute {@code index} until the destination's position
     * reaches its limit.
     * This method does not modify {@code readerIndex} or {@code writerIndex} of
     * this buffer while the destination's {@code position} will be increased.
     *
     * @throws IndexOutOfBoundsException
     *         if the specified {@code index} is less than {@code 0} or
     *         if {@code index + dst.remaining()} is greater than
     *            {@code this.capacity}
     */
```

**Comment by patrickseptem** [comment]
If you mean the second exception condition met in the above test case, then I can provide another not failed which met the condition: index+des.remaining()>this.capacity also:
```
      @Test
    public void test2() {
        ByteBuffer nioBuffer = ByteBuffer.allocate(1000);
        ByteBuf wrappedBuffer = Unpooled.wrappedBuffer("abcdefg".getBytes(), 0, 7);
        wrappedBuffer.getBytes(wrappedBuffer.readerIndex(), nioBuffer);
        assertEquals("abcdefg", new String(nioBuffer.array()).trim());
    }
```

And this exception condition confuse me: why I transfer a ByteBuf's data to a bigger ByteBuffer which still has enough capacity will throw an IndexOutOfBoundsException.

**Comment by normanmaurer** [comment]
@patrickseptem is this exactly what the javadocs say ?

```
@throws IndexOutOfBoundsException
     *         if the specified {@code index} is less than {@code 0} or
     *         if {@code index + dst.remaining()} is greater than
     *            {@code this.capacity}
```

Just limit the ByteBuffer to the readableBytes of the ByteBuf.

**Comment by patrickseptem** [comment]
Yah, the doc just described the exception condition, no more. I meet the issue because I upgrade the netty version from 4.0.23 to 4.0.41, then I try to use the latest 4.1.5 to resolved, all failed. 

If the implemention of getBytes() in latest netty is correct, then the issue should be in 4.0.23, and the second test case "test2" pasted above should failed too.

Test cases "test" and "test2" should be both failed or successful, the behavior of getBytes() is supposed to same.

**Comment by normanmaurer** [comment]
@patrickseptem yep... let me ensure it is consistent.

**Comment by normanmaurer** [comment]
Fixed consistency issues in https://github.com/netty/netty/pull/5878
