### ISSUE TITLE
netty epoll native throw java.lang.IllegalArgumentException in linux(debian)

### ISSUE THREAD

**Issue by dreamershl** [netty/netty#5865]
Netty version: 4.1.5.Final

When start application, the following exception is thrown from netty

    Caused by: java.lang.IllegalArgumentException
    at sun.misc.Unsafe.allocateMemory(Native Method)
    at io.netty.util.internal.PlatformDependent0.allocateMemory(PlatformDependent0.java:627)
    at io.netty.util.internal.PlatformDependent.allocateMemory(PlatformDependent.java:262)
    at io.netty.channel.epoll.IovArray.<init>(IovArray.java:64)
    at io.netty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:62)
    at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:130)
    at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:35)
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)

The reason is caused by another library which contains the android-2.3.3.jar. Netty EPOLL native try to detect the system by checking the functions & class. In the PlatformDependent::isAndroid0(), because of the android jar, it will believe itself is running in android.

    private static boolean isAndroid0() {
    boolean android;
    try {
        Class.forName("android.app.Application", false, getSystemClassLoader());
        android = true;
         ...
So the function hasUnsafe0() will wrongly believe there is no sun.misc.Unsafe.

    private static boolean hasUnsafe0() {
    if(isAndroid()) {
        logger.debug("sun.misc.Unsafe: unavailable (Android)");
        return false;
Because of this, the exception is thrown when it is calling the native memory allocation. Its parameter is negative value!!!

**Comment by Scottmitch** [comment]
The EPOLL transport assumes that all Linux platforms will support Unsafe. The `allocateMemory` method has no "non unsafe" alternative ... and it looks like your platform doesn't support Unsafe. To be safe we should likely check that Unsafe is supported in `Epoll.java` in order for the EPOLL transport to make itself available ... @normanmaurer - WDYT?

**Comment by dreamershl** [comment]
The mentioned issue is caused by the isAndroid() check. Because it check whether there is android app class in the class path. That is why, the hasUnsafe0() return false even my application is running in debian OS.

**Comment by Scottmitch** [comment]
Based upon your description I'm not sure how `hasUsafe0()` has any impact on the exception being thrown .. can you elaborate? Actually looking a bit deeper we do already restrict the EPOLL module's availability based upon `Unsafe`'s availability [here](https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/Epoll.java#L57). So it looks like `hasUnsafe()` returns true, and then `sun.misc.Unsafe.allocateMemory` throws an unexpected exception when called (IIRC android only partially implements `Unsafe`).

**Comment by xceder** [comment]
In the PlatformDependent class, the IS_ANDROID flag is result of this function. So it check whether the class "android.app.Application" is in the class path. 

    private static boolean isAndroid0() {
        boolean android;
        try {
            Class.forName("android.app.Application", false, getSystemClassLoader());
            android = true;
        } catch (Throwable ignored) {
            // Failed to load the class uniquely available in Android.
            android = false;
        }

        if (android) {
            logger.debug("Platform: Android");
        }
        return android;
    }

In the function  io.netty.channel.epoll.IovArray::IovArray(). It will allocate the memory with the size CAPACITY. The mentioned exception is caused by this "CAPACITY". It is negative value. 

    IovArray() {
        memoryAddress = PlatformDependent.allocateMemory(CAPACITY);
    }

The reason for this negative value is because of the result value of   PlatformDependent.addressSize()

    /** The size of an address which should be 8 for 64 bits and 4 for 32 bits. */
    private static final int ADDRESS_SIZE = PlatformDependent.addressSize();

    /**
     * The size of an {@code iovec} struct in bytes. This is calculated as we have 2 entries each of the size of the
     * address.
     */
    private static final int IOV_SIZE = 2 * ADDRESS_SIZE;

    /**
     * The needed memory to hold up to {@link Native#IOV_MAX} iov entries, where {@link Native#IOV_MAX} signified
     * the maximum number of {@code iovec} structs that can be passed to {@code writev(...)}.
     */
    private static final int CAPACITY = Native.IOV_MAX * IOV_SIZE;

The PlatformDependent.addressSize() -> PlatformDependent.addressSize0(). In later function, it will call PlatformDependent.hasUnsafe(), will return -1 if it is true. While the function PlatformDependent.hasUnsafe() just return the flag HAS_UNSAFE, which is initialized by the function hasUnsafe0(). 

So that is why the allocation of memory will throw the exception.

**Comment by Scottmitch** [comment]
As stated above if the platform is detected as android the epoll module shouldn't be available ('Epoll.isAvailable()'). You should check the result of this method before you try to use the epoll transport.

**Comment by dreamershl** [comment]
it is not android platform. it is debian, just my system get a android jar file in the class path. My point is the adroid detection is misled. Anyway, The issue is reported here to respond the recommendation in stackoverflow.
