### ISSUE TITLE
HttpToHttp2ConnectionHandler ignores HttpConversionUtil.ExtensionHeaderNames.STREAM_DEPENDENCY_ID in write(ctx, msg, promise)

### ISSUE THREAD

**Issue by evgenyvsmirnov** [netty/netty#5866]
Hello. I’m trying to open a dependent HTTP/2 stream but it seems that HttpToHttp2ConnectionHandler.write(ctx, msg, promise) ignores HttpConversionUtil.ExtensionHeaderNames.STREAM_DEPENDENCY_ID header in outbound message (and so all streams depend on connection). Isn’t it necessary to use the following version of writeHeaders version when the mentioned header is specified?
```java
    ChannelFuture writeHeaders(ChannelHandlerContext ctx, int streamId, Http2Headers headers,
            int streamDependency, short weight, boolean exclusive, int padding, boolean endStream,
            ChannelPromise promise);
```
Netty version: 4.1.5.Final

Thanks.

**Comment by normanmaurer** [comment]
@evgenyvsmirnov I think you are right... let me fix it.

**Comment by evgenyvsmirnov** [comment]
Thanks. I think the same story with InboundHttp2ToHttpAdapter.onHeadersRead (the fact that streamDependency != 0 is ignored).

BTW. Why it is in 4.0.42.Final milestone? Shouldn't it be in 4.1.6.Final (I'm using 4.1.5.Final)?

**Comment by normanmaurer** [comment]
@evgenyvsmirnov yep... sorry milestone was wrong.

**Comment by normanmaurer** [comment]
@evgenyvsmirnov isn't this handled in `InboundHttp2ToHttpPriorityAdapter` ?

**Comment by evgenyvsmirnov** [comment]
I'm sure it is not (at least in 4.1.5.Final). A FullHttpResponse I got in subsequent handlers doesn't contain STREAM_DEPENDENCY (it is > 0 in onHeadersRead invocation).

I had to «fix» in following way:

```java
    @Override
    public void onHeadersRead(ChannelHandlerContext ctx, int streamId, Http2Headers headers, int streamDependency,
            short weight, boolean exclusive, int padding, boolean endOfStream) throws Http2Exception
    {
        Http2Stream stream = connection.stream(streamId);
        FullHttpMessage msg = processHeadersBegin(ctx, stream, headers, endOfStream, true, true);
        if (streamDependency != 0)
        {
            msg.headers().add(HttpConversionUtil.ExtensionHeaderNames.STREAM_DEPENDENCY_ID.text(), streamDependency);
        }
        
        if (msg != null)
        {
            // inlined private InboundHttp2ToHttpAdapter.processHeadersEnd(ctx, stream, msg, endOfStream);
            if (endOfStream)
            {
                fireChannelRead(ctx, msg, getMessage(stream) != msg, stream);
            }
            else
            {
                putMessage(stream, msg);
            }
        }
    }
```

**Comment by normanmaurer** [comment]
@evgenyvsmirnov ah sorry I see now :)

**Comment by normanmaurer** [comment]
@evgenyvsmirnov can you check https://github.com/netty/netty/pull/5879 ?

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5879
