### ISSUE TITLE
OpenSSL with netty 4.1.5 and tcnative 1.1.33.Fork21/22 crash

### ISSUE THREAD

**Issue by floragunncom** [netty/netty#5870]
OpenSSL with netty 4.1.5 and tcnative 1.1.33.Fork21 and 1.1.33.Fork22 crash:

<pre>
[Dynamic-linking native method sun.nio.ch.SocketChannelImpl.checkConnect ... JNI]
[Dynamic-linking native method org.apache.tomcat.jni.SSL.readFromBIO ... JNI]
[Dynamic-linking native method sun.nio.ch.SocketChannelImpl.checkConnect ... JNI]
[Dynamic-linking native method sun.nio.ch.FileDispatcherImpl.preClose0 ... JNI]
[Dynamic-linking native method org.apache.tomcat.jni.SSL.readFromSSL ... JNI]
[Dynamic-linking native method org.apache.tomcat.jni.SSL.getLastErrorNumber ... JNI]
[Dynamic-linking native method sun.nio.ch.FileDispatcherImpl.preClose0 ... JNI]
[Dynamic-linking native method org.apache.tomcat.jni.SSL.getShutdown ... JNI]
[Dynamic-linking native method sun.nio.ch.FileDispatcherImpl.preClose0 ... JNI]
[Dynamic-linking native method sun.nio.ch.FileDispatcherImpl.preClose0 ... JNI]
[Dynamic-linking native method org.apache.tomcat.jni.SSL.clearError ... JNI]
[Dynamic-linking native method sun.nio.ch.FileDispatcherImpl.preClose0 ... JNI]
[Dynamic-linking native method org.apache.tomcat.jni.SSL.clearError ... JNI]
[Dynamic-linking native method org.apache.tomcat.jni.SSL.clearError ... JNI]
[Dynamic-linking native method org.apache.tomcat.jni.SSL.clearError ... JNI]
[Dynamic-linking native method sun.nio.ch.FileDispatcherImpl.preClose0 ... JNI]
[Dynamic-linking native method sun.nio.ch.SocketChannelImpl.checkConnect ... JNI]
[Dynamic-linking native method org.apache.tomcat.jni.SSL.authenticationMethods ... JNI]
[Dynamic-linking native method sun.nio.ch.FileDispatcherImpl.preClose0 ... JNI]
[Dynamic-linking native method org.apache.tomcat.jni.SSL.setCertificateBio ... JNI]
[Dynamic-linking native method org.apache.tomcat.jni.SSL.getVersion ... JNI]
[Dynamic-linking native method org.apache.tomcat.jni.SSL.getOptions ... JNI]
[Dynamic-linking native method org.apache.tomcat.jni.SSL.parseX509Chain ... JNI]
java(59270,0x12a0ac000) malloc: *** error for object 0x7fc570f046b0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
</pre>

1.1.33.Fork20 is working (possibly related to commit af89478)

Environment:
<pre>
OS: Mac OS X x86_64 10.10.5
Java Version: 1.8.0_102 Oracle Corporation
JVM Impl.: 25.102-b14 Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
Open SSL version: OpenSSL 1.0.2h  3 May 2016
</pre>

**Comment by normanmaurer** [comment]
I think this is a duplicate of:

https://github.com/netty/netty-tcnative/pull/190

**Comment by normanmaurer** [comment]
@floragunncom WDYT ?

**Comment by floragunncom** [comment]
I'll test it with 1.1.33.Fork23-SNAPSHOT. Is this available somewhere in a public maven repo?

**Comment by floragunncom** [comment]
1.1.33.Fork23 (released today) works on linux (so it seems this issue is resolved).

But it fail completely on macos with "java.lang.AssertionError: OpenSSL not available: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty-tcnative-osx-x86_64, netty-tcnative]" Should i open a new issue for this?

**Comment by normanmaurer** [comment]
@floragunncom yep... that said can you do "brew install apr" and see if it works after it ?

**Comment by floragunncom** [comment]
that fixed it, thx
