### ISSUE TITLE
SniHandlerTest.testServerNameParsing() fails 

### ISSUE THREAD

**Issue by radai-rosenblatt** [netty/netty#5874]
the test runs up to line 154:

``` java
try {
   // Push the handshake message.
   // Decode should fail because SNI error
   ch.writeInbound(Unpooled.wrappedBuffer(DatatypeConverter.parseHexBinary(tlsHandshakeMessageHex1)));
   ch.writeInbound(Unpooled.wrappedBuffer(DatatypeConverter.parseHexBinary(tlsHandshakeMessageHex)));
   fail();
} catch (DecoderException e) {
   // expected
}

assertThat(ch.finish(), is(true)); <--- line 154
```

but at that point, both `ch.inboundMessages` and `ch.outboundMessages` are null, so `ch.finish()` returns false and the test fails as it expects true.

this happens to me when building under windows 7 using the git shell:

```
$ uname -a
MINGW64_NT-6.1 latitude 2.5.0(0.295/5/3) 2016-03-31 18:47 x86_64 Msys
$ java -version
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
$ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)
Maven home: C:\dev\tools\maven
Java version: 1.8.0_92, vendor: Oracle Corporation
Java home: C:\dev\tools\jdk\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"
```

**Comment by radai-rosenblatt** [comment]
also happens on OSX at commit 1c588ce7e9573a6327f0a8a86cf1d754fd10e775:
```
$ uname -a
Darwin rrosenbl-mn1 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
$ java -version
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
$ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)
Maven home: /usr/local/apache-maven-3.3.9
Java version: 1.8.0_102, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
```

**Comment by Scottmitch** [comment]
@radai-rosenblatt - thanks for reporting. I also run into this issue this week ... I will submit a PR soon.

**Comment by normanmaurer** [comment]
@Scottmitch thanks a lot!

**Comment by normanmaurer** [comment]
@Scottmitch ping

**Comment by Scottmitch** [comment]
https://github.com/netty/netty/issues/5971#issuecomment-258476405

I got side tracked. Not sure when I will get back to this issue.

**Comment by nhnFreespirit** [comment]
seeing this with on my MacBook Pro

uname -a
Darwin some_laptop_name 13.4.0 Darwin Kernel Version 13.4.0: Mon Jan 11 18:17:34 PST 2016; root:xnu-2422.115.15~1/RELEASE_X86_64 x86_64

java -version
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)


mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)
Maven home: /opt/twitter_mde/homebrew_minimal/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_72, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.9.5", arch: "x86_64", family: "mac"

**Comment by normanmaurer** [comment]
@nhnFreespirit can you test with latest java version and report if you still see the problem there ?

**Comment by nhnFreespirit** [comment]
Not sure I have an easy way of upgrading java 8 on this laptop as that is part of a managed dev env.

**Comment by normanmaurer** [comment]
@nhnFreespirit ah ok... let me try to grab the same JDK version you have and see if I can reproduce it here. Will ping you if I need more infos from you.

**Comment by normanmaurer** [comment]
@radai-rosenblatt @nhnFreespirit @Scottmitch ok I can reproduce it when using `SslProvider.JDK`. Looking now.

**Comment by normanmaurer** [comment]
working on a fix

**Comment by normanmaurer** [comment]
@nhnFreespirit can you test https://github.com/netty/netty/pull/6011 ? Thanks!

**Comment by nhnFreespirit** [comment]
@normanmaurer so the SNI issue does seem to be fixed. seeing another issue now but that seems like it might be a network thing?

> 17:10:56.541 [main] DEBUG o.o.p.u.m.i.AetherBasedResolver - Resolved (io.netty:netty-build:jar:22) as /Users/nnielsen/.m2/repository/io/netty/netty-build/22/netty-build-22.jar
> 17:10:56.543 [main] DEBUG o.o.p.e.n.i.NativeTestContainer - + Install (start@3) MavenArtifactUrlReference{groupId='io.netty', artifactId='netty-build', version='22', type='null'}
> 17:10:56.547 [main] DEBUG o.o.pax.url.mvn.internal.Connection - Resolving [mvn:io.netty/netty-codec-mqtt/4.1.7.Final-SNAPSHOT]
> 17:10:56.547 [main] DEBUG o.o.p.u.m.i.AetherBasedResolver - interval1: null, interval2: daily
> 17:10:56.547 [main] DEBUG o.o.p.u.m.i.AetherBasedResolver - interval1: null, interval2: daily
> 17:10:56.548 [main] DEBUG s.o.e.a.i.i.DefaultLocalRepositoryProvider - Using manager SimpleLocalRepositoryManager with priority 0.0 for /Users/nnielsen/.m2/repository
> 17:10:56.557 [main] WARN  o.o.p.u.m.i.AetherBasedResolver - Error resolving artifactio.netty:netty-codec-mqtt:jar:4.1.7.Final-SNAPSHOT:Could not find artifact io.netty:netty-codec-mqtt:jar:4.1.7.Final-SNAPSHOT
> shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact io.netty:netty-codec-mqtt:jar:4.1.7.Final-SNAPSHOT
> 	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
> 	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
> 	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
> 	at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
> 	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:615)
> 	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:570)
> 	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:548)
> 	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:523)
> 	at org.ops4j.pax.url.mvn.internal.Connection.getInputStream(Connection.java:123)
> 	at org.apache.felix.framework.util.SecureAction.getURLConnectionInputStream(SecureAction.java:525)
> 	at org.apache.felix.framework.cache.JarRevision.initialize(JarRevision.java:166)
> 	at org.apache.felix.framework.cache.JarRevision.<init>(JarRevision.java:77)
> 	at org.apache.felix.framework.cache.BundleArchive.createRevisionFromLocation(BundleArchive.java:878)
> 	at org.apache.felix.framework.cache.BundleArchive.reviseInternal(BundleArchive.java:550)
> 	at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:153)
> 	at org.apache.felix.framework.cache.BundleCache.create(BundleCache.java:277)
> 	at org.apache.felix.framework.Felix.installBundle(Felix.java:2971)
> 	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:167)
> 	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:140)
> 	at org.ops4j.pax.exam.nat.internal.NativeTestContainer.installAndStartBundles(NativeTestContainer.java:340)
> 	at org.ops4j.pax.exam.nat.internal.NativeTestContainer.start(NativeTestContainer.java:209)
> 	at org.ops4j.pax.exam.spi.reactors.AllConfinedStagedReactor.invoke(AllConfinedStagedReactor.java:79)
> 	at org.ops4j.pax.exam.junit.impl.ProbeRunner$2.evaluate(ProbeRunner.java:267)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:98)
> 	at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
> 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
> 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
> 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
> Caused by: shaded.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.netty:netty-codec-mqtt:jar:4.1.7.Final-SNAPSHOT
> 	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:434)
> 	... 40 common frames omitted
> 17:10:56.563 [main] INFO  o.o.p.e.spi.reactors.ReactorManager - suite finished
> Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 12.654 sec <<< FAILURE! - in io.netty.osgitests.OsgiBundleTest
> testResolvedBundles(io.netty.osgitests.OsgiBundleTest)  Time elapsed: 12.166 sec  <<< ERROR!
> java.io.IOException: Error resolving artifact io.netty:netty-codec-mqtt:jar:4.1.7.Final-SNAPSHOT: Could not find artifact io.netty:netty-codec-mqtt:jar:4.1.7.Final-SNAPSHOT
> 
> 
> Results :
> 
> Tests in error: 
>   OsgiBundleTest.testResolvedBundles » IO Error resolving artifact io.netty:nett...
> 
> Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
> 
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO] 
> [INFO] Netty .............................................. SUCCESS [  7.027 s]
> [INFO] Netty/Common ....................................... SUCCESS [ 53.846 s]
> [INFO] Netty/Buffer ....................................... SUCCESS [ 54.939 s]
> [INFO] Netty/Resolver ..................................... SUCCESS [  5.348 s]
> [INFO] Netty/Transport .................................... SUCCESS [ 53.985 s]
> [INFO] Netty/Codec ........................................ SUCCESS [ 21.223 s]
> [INFO] Netty/Codec/DNS .................................... SUCCESS [  7.198 s]
> [INFO] Netty/Codec/HAProxy ................................ SUCCESS [  4.710 s]
> [INFO] Netty/Handler ...................................... SUCCESS [ 12.559 s]
> [INFO] Netty/Codec/HTTP ................................... SUCCESS [ 13.695 s]
> [INFO] Netty/Codec/HTTP2 .................................. SUCCESS [ 21.898 s]
> [INFO] Netty/Codec/Memcache ............................... SUCCESS [  6.159 s]
> [INFO] Netty/Codec/MQTT ................................... SUCCESS [  5.257 s]
> [INFO] Netty/Codec/Redis .................................. SUCCESS [  5.379 s]
> [INFO] Netty/Codec/SMTP ................................... SUCCESS [  4.944 s]
> [INFO] Netty/Codec/Socks .................................. SUCCESS [  6.421 s]
> [INFO] Netty/Codec/Stomp .................................. SUCCESS [  4.892 s]
> [INFO] Netty/Codec/XML .................................... SUCCESS [  4.651 s]
> [INFO] Netty/Resolver/DNS ................................. SUCCESS [  8.277 s]
> [INFO] Netty/Transport/RXTX ............................... SUCCESS [  2.245 s]
> [INFO] Netty/Transport/SCTP ............................... SUCCESS [  2.735 s]
> [INFO] Netty/Transport/UDT ................................ SUCCESS [ 21.298 s]
> [INFO] Netty/Handler/Proxy ................................ SUCCESS [ 14.498 s]
> [INFO] Netty/Example ...................................... SUCCESS [  5.621 s]
> [INFO] Netty/Testsuite .................................... SUCCESS [14:04 min]
> [INFO] Netty/Testsuite/OSGI ............................... FAILURE [ 23.710 s]
> [INFO] Netty/Microbench ................................... SKIPPED
> [INFO] Netty/All-in-One ................................... SKIPPED
> [INFO] Netty/Tarball ...................................... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 20:17 min
> [INFO] Finished at: 2016-11-11T17:11:04-08:00
> [INFO] Final Memory: 115M/1768M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project netty-testsuite-osgi: There are test failures.
> [ERROR] 
> [ERROR] Please refer to /Users/nnielsen/workspace/netty-netty/testsuite-osgi/target/surefire-reports for the individual test results.
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <goals> -rf :netty-testsuite-osgi

**Comment by normanmaurer** [comment]
@nhnFreespirit I think if you do a `mvn clean install` it will go away. Thanks for testing!

**Comment by nhnFreespirit** [comment]
@normanmaurer Indeed, all green now. thanks!

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6011
