### ISSUE TITLE
SslContextBuilder build SslContext from javax.net.ssl.SSLContext

### ISSUE THREAD

**Issue by jeffpeiyt** [netty/netty#5888]
the current SslContextBuilder seems cannot accept jks file input or construct from the java normal SSLContext.  Could anyone provide an example to load from the javax.net.ssl.SSLContext ?

We are migrating from async http client from 1.x to 2.0.15,  where latest version using netty 4.x for ssl context 

thanks!

**Comment by normanmaurer** [comment]
@jeffpeiyt you can use `JdkSslContext(....)` to wrap an existing `SSLContext`. Does this help ?

**Comment by jeffpeiyt** [comment]
@normanmaurer  yes it is comping now!  thanks for the prompt help !
