### ISSUE TITLE
DefaultHttp2HeadersDecoder undesirable behavior when oversized headers received?

### ISSUE THREAD

**Issue by exell-christopher** [netty/netty#5889]
When oversized headers are received by the DefaultHttp2HeadersDecoder, a go away with the error code enhance your calm is sent. This appears to be an attempt to prevent attack traffic, however, this has a somewhat undesirable effect when multiple requests are streaming over a connection, as a single oversized request can kill all other requests on the connection.  The HTTP/2 spec indicates that a 431 is the correct response in the event of oversized headers.

https://http2.github.io/http2-spec/#MaxHeaderBlock

Would it be possible to have two header size settings in the DefaultHttp2HeadersDecoder? One for filtering out slightly oversized requests, which would send a 431, and one for filtering out attack requests?  Maybe > 8k for a 431 and >80k for a go away. In both cases, we'd stop recoding any data after 8k.

Working on a change for this, but I figured that there would be discussion on this, so I'm opening an issue first.

This relates to #5774

**Comment by Scottmitch** [comment]
IIRC this should be resolved by https://github.com/netty/netty/pull/5845

**Comment by normanmaurer** [comment]
@exell-christopher ...

**Comment by exell-christopher** [comment]
Sorry for the delayed reply.  I looked over the code, and assuming that I read it correctly, this change takes care of respecting/negotiating the header table size WOOT! However, when the header table size is exceeded, it produces a protocol error which results in a go away instead of a 431.

**Comment by normanmaurer** [comment]
@Scottmitch can you have a look buddy ?

**Comment by exell-christopher** [comment]
Thanks for investigating this!!

**Comment by Scottmitch** [comment]
IIRC a RST stream frame is sent in the referenced PR with a protocol error which provides a consistent approach between client and server. The 431 response is not required by the RFC but we can consider adding support for sending a 431 on the server in the future.

https://tools.ietf.org/html/rfc7540#section-10.5.1
> A server that receives a larger header block than it is willing to
   handle can send an HTTP 431 (Request Header Fields Too Large) status
   code [RFC6585].

**Comment by normanmaurer** [comment]
@Scottmitch let me know what you prefer. We could also just close this one and point to the PR as you said.

**Comment by exell-christopher** [comment]
I'd love to have a 431 response, even if it was something that is enabled via configuration, we've added outbound handlers locally for this to work with the new code.

When working with the new change, we did notice one unusual behavior in the InboundHttp2ToHttpAdapter (this may have already been the behavior with the prior GO_AWAY behavior), the InboundHttp2ToHttpAdapter doesn't seem to translate the RST into a completed or errored request, and thus no response is ever seen.

**Comment by Scottmitch** [comment]
`InboundHttp2ToHttpAdapter` is for reading application level data. IIUC in this case your local endpoint would be sending a RST. Are you saying your peer is not receiving a RST frame when they violate the header size?

**Comment by exell-christopher** [comment]
I'm going to close this given that 431 handling is now present.
