### ISSUE TITLE
Allow the SSL protocol to be configurable for JdkSslContext and OpenSslContext

### ISSUE THREAD

**Issue by aneeshynot** [netty/netty#5891]
**Netty version: 4.1.5.Final**

**Netty target version: 4.1.6.Final** (If possible)

**Context:**
We want to be able to configure the SSL PROTOCOL version in JDK and OpenSSL SslContext. 
We need this because we need to be able to limit the SSL protocol to TLSv1.2, however, this does not seem to be possible currently. Currently it is hard coded to allow TLS all versions in both cases.

**Java version:** Not dependent on Java version

**Operating system:** Not dependent on OS version.

**Changes required:**

For **JdkSslContext**:

In class, _io.netty.handler.ssl.JdkSslContext_  currently we have the following code -
```

public class JdkSslContext extends SslContext {

	 static final String PROTOCOL = "TLS";
    
	 static {
        SSLContext context;
        int i;
        try {
            context = SSLContext.getInstance(PROTOCOL);
            context.init(null, null, null);
        } catch (Exception e) {
            throw new Error("failed to initialize the default SSL context", e);
        }
...
```
		
Since the PROTOCOL is being initialized in static block, it may not be possible to specify this from the ssl context builder. Hence, the suggestion is to allow to configure this using a System property.

Can we change this to -

```
public class JdkSslContext extends SslContext {

	 static final String PROTOCOL = System.getProperty("JdkSslContext_SSLProtocol", "TLS");
...

```	 
	 

	 
For **OpenSslContext**:

In class, _io.netty.handler.ssl.OpenSslContext_ currently we have the following code -

```
OpenSslContext(Iterable<String> ciphers, CipherSuiteFilter cipherFilter,
                   OpenSslApplicationProtocolNegotiator apn, long sessionCacheSize,
                   long sessionTimeout, int mode, Certificate[] keyCertChain,
                   ClientAuth clientAuth) throws SSLException {
    
.....

 synchronized (OpenSslContext.class) {
                try {
                    ctx = SSLContext.make(aprPool, SSL.SSL_PROTOCOL_ALL, mode);
                } catch (Exception e) {
                    throw new SSLException("failed to create an SSL_CTX", e);
                }
				
```
				
For OpenSSL we can use either System property as done above for JdkSslContext to keep it uniform, or we can specify the protocol from the builder and have appropriate changes in the builder to allow to specify 'int supportedSslProtocol' -

```
static final int PROTOCOL = Integer.getInteger("OpenSslContext_SSLProtocol",SSL.SSL_PROTOCOL_ALL);

OpenSslContext(Iterable<String> ciphers, CipherSuiteFilter cipherFilter,
                   OpenSslApplicationProtocolNegotiator apn, long sessionCacheSize,
                   long sessionTimeout, int mode, Certificate[] keyCertChain,
                   ClientAuth clientAuth) throws SSLException {
    
.....

 synchronized (OpenSslContext.class) {
                try {
                    ctx = SSLContext.make(aprPool, PROTOCOL, mode);
                } catch (Exception e) {
                    throw new SSLException("failed to create an SSL_CTX", e);
                }


```

OR-

```
OpenSslContext(Iterable<String> ciphers, CipherSuiteFilter cipherFilter,
                   OpenSslApplicationProtocolNegotiator apn, long sessionCacheSize,
                   long sessionTimeout, int mode, Certificate[] keyCertChain,
                   ClientAuth clientAuth, int supportedSslProtocol) throws SSLException {
    
.....

 synchronized (OpenSslContext.class) {
                try {
                    ctx = SSLContext.make(aprPool, supportedSslProtocol, mode);
                } catch (Exception e) {
                    throw new SSLException("failed to create an SSL_CTX", e);
                }


```
We can optionally have a separate mapping for specifying SSL protocol with a uniform interface for both Jdk and OpenSsl, instead of directly depending on org.apache.tomcat.jni.SSL for OpenSsl and the protocol string value for Jdk.	

Please let me know if you can think of a better way of making the SSL protocol configurable in the SslContexts.

**Comment by doom369** [comment]
Did you try 

```
SslHandler sslHandler = sslCtx.newHandler(ch.alloc()));
sslHandler.engine().setEnabledProtocols(new String[] {"TLSv1.2"});
```

?

**Comment by normanmaurer** [comment]
@aneeshynot what @doom369 suggested is exactly how you would do it. Please let us know if this works or not.

**Comment by aneeshynot** [comment]
Thank you for that immediate response doom369 and Norman!
I have tested your suggestion and works properly for both JDK and OpenSSL.
Cheers!

And thanks Norman and all contributors for this amazing library!
