### ISSUE TITLE
EOF for variable length, non chunked, compressed HTTP response is incorrectly treated as premature channel closure

### ISSUE THREAD

**Issue by alkemist** [netty/netty#5892]
The fundamental issue here (I think) is that HttpContentDecoder is modifying the incoming request headers to indicate the request is chunked when it might actually be variable length EOF terminated.

This happens here: https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpContentDecoder.java#L102

This then causes https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java#L411 to yield a true value. The net effect of this is that a `PrematureChannelClosureException` is raised instead of emitting a `LastHttpContent`.

I wasn't able to create a test case for this because HttpContentEncoder enforces chunked responses. I discovered this issue when using Netty to reverse proxy a Jetty server, that uses EOF framing for streamed responses when not using keepalive.

I suspect that this is actually a regression caused by https://github.com/netty/netty/commit/ee0897a1d9d80119990964834d62f906f800afb8 as part of the fix for #5428.

**Comment by alkemist** [comment]
I've just confirmed that this issue isn't present with 4.1.1.

**Comment by normanmaurer** [comment]
@alkemist sounds correct... Want to create a PR for it ?

**Comment by normanmaurer** [comment]
@alkemist actually can you confirm this is really caused by the commit you listed here ? I am a bit confused as you say you see a `PrematureChannelClosureException` which would be caused by the `HttpRequestDecoder` that sit in front of the `HttpContentDecoder` so what you do in `HttpContentDecoder` should have no impact here. Or do you think it happens because its used as proxy and so modify the stuff in between?

**Comment by alkemist** [comment]
@normanmaurer sorry, I made a mistake in my description. No `PrematureChannelClosureException` is raised. The problem is that https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java#L441 does not happen, because `HttpObjectDecoder` thinks that the channel was prematurely closed. I thinks this, because it's seeing `Transfer-Encoding: chunked` that was added by `HttpContentDecoder`, but that wasn't actually on the request.

My fix for this would be to effectively move https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java#L441 to somewhere around https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java#L606. That is, read and store whether the request was variable length just after reading the headers. Do you have a better idea?

Can you also please point me to a test for a similar kind of thing that I can use as a starting point.

**Comment by normanmaurer** [comment]
@alkemist no worries I think I have an idea how to easily fix it and write a test. stay tuned...

**Comment by normanmaurer** [comment]
@alkemist hopefully I can fit this in before I cut the release this week.

**Comment by alkemist** [comment]
@normanmaurer I hate to be that guy, but… any update on this? :)

**Comment by normanmaurer** [comment]
@alkemist sorry was on vacation... Please check https://github.com/netty/netty/pull/5957

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5957

**Comment by liucyu** [comment]
good job !
