### ISSUE TITLE
Huge increase in NativeIoExceptions after upgrade to 4.1.5.Final from 4.1.0.CR2

### ISSUE THREAD

**Issue by jknair** [netty/netty#5895]
After upgrade from netty version 4.1.0.CR2 to 4.1.5.Final we have started seeing a lot of 
```NativeIoException syscall:read(...)() failed: Connection reset by peer```

I am not sure how to reproduce this as this seems to occur only on high load. 

```
netty version : 4.1.5-Final
java version: 1.8.0_u20
openssl version: 1.0.1k
linux version: 3.16.0-4-amd64 Debian
```

**Comment by Scottmitch** [comment]
This exception is expected if your peer sends a TCP RST. Can you verify that using a packet sniffer? Also is there an issue caused as a side effect of this behavior?

**Comment by jknair** [comment]
I will try that out. But these issues did not come up in the older version and with the upgrade not much but a few classes that netty had deprecated have been changed with respect to the code.

**Comment by jknair** [comment]
```tcpdump -ilo -n -v 'tcp[tcpflags] & (tcp-rst) != 0'```
a few RST packets are going across but that does not equal the rate of Exceptions. Both the server and client are netty based. Why would the RST packet be sent when a close is initiated ?

**Comment by Scottmitch** [comment]
Setting SO_LINGER to `0` is one way to cause a `RST` (see [1] for some extra details).

Can you provide a reproducer?

[1] http://stackoverflow.com/questions/3757289/tcp-option-so-linger-zero-when-its-required

**Comment by jknair** [comment]
dont bother it was an HA proxy load balancing the netty servers which was on http mode that was eating up ```Connection: close``` headers and the clients were sending RSTs. Sorry about that :(

**Comment by normanmaurer** [comment]
@jknair thanks for closing the loop! :)
