### ISSUE TITLE
InsecureTrustManagerFactory is sometimes not insecure enough.

### ISSUE THREAD

**Issue by trustin** [netty/netty#5910]
In some execution path, JDK seems to wrap `InsecureTrustManager` with a wrapper (`AbstractTrustManagerWrapper`, which is a _final_ class!?). Because the wrapper performs an additional DN comparison, a user will see certificate validation fails even if he or she specified `InsecureTrustManagerFactory.INSTANCE`.

To fix this problem, `InsecureTrustManager` has to extend `X509ExtendedTrustManager` instead of `X509TrustManager`. It will need a little bit of refactoring if we want it to work on older JDK because `X509ExtendedTrustManager` is since Java 7:

- Extract the current `InsecureTrustManager` implementation into a top level class.
- Add `InsecureExtendedTrustManager` which extends `X509ExtendedTrustManager`
- Modify `InsecureTrustManagerFactory` so that it chooses the right `TrustManager` implementation depending on current Java version.

https://github.com/line/armeria/pull/303 shows the new `TrustManager` implementation that extends `X509ExtendedTrustManager`, which is pretty trivial to write.

**Comment by trustin** [comment]
We should make similar changes to `FingerprintTrustManagerFactory` as well.

**Comment by Scottmitch** [comment]
sgtm
