### ISSUE TITLE
Not a WebSocket handshake request: missing upgrade

### ISSUE THREAD

**Issue by johnnyquestep** [netty/netty#5916]
I am running the websocket sample on solaris. 
response data i see in chrome is eror 400 , OPCOCE(1)
when i inspected it using wireshark i see the below.

```
GET /websocket HTTP/1.1
Host: x.x.x.x:8080
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: http://x.x.x.x:8080
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Sec-WebSocket-Key: uT0Y/9AfO+fwqw8BnaYiTg==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

HTTP/1.1 400 Bad Request

not a WebSocket handshake request: missing upgrade
```

same jar file works in linux and windows. 
i have tried jdk 6,7 and 8.

why doe is it say Upgrade is missing when we can see it in the headers ?

**Comment by normanmaurer** [comment]
@johnnyquestep which netty version ?

**Comment by johnnyquestep** [comment]
netty version 4.1.5

**Comment by normanmaurer** [comment]
@johnnyquestep can you paste the output so that it is easier to see if there are any extra spaces on the end of lines etc ?

**Comment by johnnyquestep** [comment]
is there a way to enable additional logging ? 
. In the ui i see socket closed and in the chrome console i see

> (index):17 WebSocket connection to 'ws://hostname.:8081/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400

In the chrome developer tools under the websoket frames i see

>  (Opcode -1)

Below is all i have in the log. the section you see after the small gap in the logs is where the first http request for page comes in

> -bash-3.2$ /app/jdk/jdk1.8.0_66/bin/java -jar WebSocketServer_arg3.jar 8081 8082
> Oct 14, 2016 5:36:06 PM io.netty.channel.DefaultChannelId defaultMachineId
> WARNING: Failed to find a usable hardware address from the network interfaces; u                                                                                                                                                             sing random bytes: aa:e2:48:67:64:ee:93:7b
> Oct 14, 2016 5:36:06 PM io.netty.handler.logging.LoggingHandler channelRegistere                                                                                                                                                             d
> INFO: [id: 0x483f61de] REGISTERED
> Oct 14, 2016 5:36:06 PM io.netty.handler.logging.LoggingHandler bind
> INFO: [id: 0x483f61de] BIND: 0.0.0.0/0.0.0.0:8081
> Open your web browser and navigate to http://127.0.0.1:8081/
> Oct 14, 2016 5:36:06 PM io.netty.handler.logging.LoggingHandler channelActive
> INFO: [id: 0x483f61de, L:/0.0.0.0:8081] ACTIVE
> 
> 
> 
> 
> 
> Oct 14, 2016 5:37:28 PM io.netty.handler.logging.LoggingHandler channelRead
> INFO: [id: 0x483f61de, L:/0.0.0.0:8081] RECEIVED: [id: 0xc3d35fa7, L:/10.144.0.1                                                                                                                                                             42:8081 - R:/10.191.208.92:57434]
> WebSocketServerInitializer::: initializing
> io.netty.handler.codec.http.DefaultHttpHeaders@75896058
> sending indext page
> Oct 14, 2016 5:37:29 PM io.netty.handler.logging.LoggingHandler channelRead
> INFO: [id: 0x483f61de, L:/0.0.0.0:8081] RECEIVED: [id: 0xe81b93cb, L:/10.144.0.1                                                                                                                                                             42:8081 - R:/10.191.208.92:57435]
> WebSocketServerInitializer::: initializing

**Comment by johnnyquestep** [comment]
I tried to compile on solaris,failed due to missing tcnative dependency. anything else i can try  ?

**Comment by rz-itac** [comment]
Hi. I'm having the same problem. Made a Websocket application, server running on Solaris 10. Websocket handshake always fails on Solaris (HTTP 400 Bad Request: not a WebSocket handshake request: missing upgrade). 

After debbuging, I found that Netty is unable to find the header "Connection", the reason is that the return value of hashCode in AsciiString is not the same as PlatformDependent.hashCodeAscii(value)

in class io.netty.util.AsciiString:
```
public static int hashCode(CharSequence value) {
        if (value == null) {
            return 0;
        }
        if (value.getClass() == AsciiString.class) {
            return value.hashCode();
        }

        return PlatformDependent.hashCodeAscii(value);
}
```

A simple workaround is to comment the second if in the above code, but I guess it would be a performance overhead.

Thank you for any pointers you can give me, another workaround is going back to a previous version, like it is suggested here: http://stackoverflow.com/questions/36444181/netty-4-1-not-a-websocket-handshake-request-missing-upgrade, but I need the chunked classes for websocket introduced in 4.1.x, so I cannot go back to 4.0.x.

**Comment by Scottmitch** [comment]
closed by https://github.com/netty/netty/pull/5935
