### ISSUE TITLE
Possible thread leak

### ISSUE THREAD

**Issue by yogeshvedpathak** [netty/netty#592]
Hi, I am using netty version 3.5.6 and on server side I am seeing that worker threads are not being properly returned to the pool. First for each new connection a a new worker thread is created and even if the connection is closed the thread is not returned to the pool neither it dies. If I open a new connection then a new thread is created. After few minutes I see on order of thousand connections. 
When I use netty 3.5.7 my server dies with OutOfMemeoryError (java.lang.OutOfMemoryError: unable to create new native thread). I am guessing it's a same problem in 3.5.7 but turn in runtime exception because of workaround. This runtime exception is holding us back from using 3.5.7. 

Can you please take a look at it? Let me know if you need any more data.

**Comment by TigranTsat** [comment]
Was this issue resolved or not? I am hitting same issue that number of IO threads is going extremely high (currently, I having 60 IO Workers)

**Comment by AlexSylka** [comment]
I have high cpu load and 5000 IO Workers
