### ISSUE TITLE
Do we still use HashedWheelTimer in Netty?

### ISSUE THREAD

**Issue by jianjin** [netty/netty#5921]
In Netty 4.X, i do not found any other class use it. If we do not use it anymore, should be remove it from codebase?

**Comment by slandelle** [comment]
FWIW, I use it in [AsyncHttpClient](https://github.com/AsyncHttpClient/async-http-client) for managing my timeouts. I seems legit to do so as it's both public and not in an "internal" package.

I would be fine if it were to be deprecated and removed in a future minor release, I would then fork it if needed. But please don't remove in a fix.

**Comment by johnou** [comment]
It's also used in Redisson.

**Comment by Scottmitch** [comment]
We can consider this as part of future releases but it is currently part of the public API. IMO we should keep it for now ... potentially deprecate the existing one and move it in an internal package as it is still a useful utility in the context of network related timeouts.

**Comment by eun-ice** [comment]
We rely on it too.

**Comment by normanmaurer** [comment]
I think we should just keep it as it is for now.
