### ISSUE TITLE
Consolidate some of AbstractChannel's methods (and maybe deprecate a few of ChannelPIpeline's)?

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#5927]
I'm experimenting with extending the LocalChannel class and am looking into overriding the `connect(...)` method for example. Ideally I'd have to override only one of the methods or maybe just the ones that have a `ChannelPromise` argument to intercept the user call and change the behavior of the returned future.

Each of AbstractChannel's methods is however calling straight out to the pipeline (like below) and forcing me to override each flavor of `connect(...)`.

``` java
class AbstractChannel {
  ChannelFuture connect(SocketAddress remoteAddress) {
    return pipeline.connect(remoteAddress);
  }

  ChannelFuture connect(SocketAddress remoteAddress, ChannelPromise promise) {
    return pipeline.connect(remoteAddress, promise);
  }
}
```

As a result there appears to be also some duplication in `DefaultChannelPipeline` or rather `AbstractChannelHandlerContext` to consolidate everything into `connect(remote, local, promise)`.

Would it make sense to deprecate the different flavors of the same methods in the pipeline/ctx interfaces and instead funnel everything to the right method in the AbstractChannel class? Like this:

``` java
class AbstractChannel {
  ChannelFuture connect(SocketAddress remoteAddress) {
    return connect(remoteAddress, newPromise());
  }

  ChannelFuture connect(SocketAddress remoteAddress, ChannelPromise promise) {
    return connect(remoteAddress, null, promise);
  }

  ChannelFuture connect(SocketAddress remoteAddress, SocketAddress localAddress, ChannelPromise promise) {
    return pipeline.connect(remoteAddress, localAddress, promise);
  }
}
```

**Comment by normanmaurer** [comment]
@rkapsi I am not sure if there is really some benefit to deprecate all of these :) Override each of these sounds ok to me.

**Comment by normanmaurer** [comment]
@rkapsi like I said I don't think it is worth it... Let me close this for now
