### ISSUE TITLE
"OutOfMemoryError: GC overhead limit exceeded" occurs while using HTTP2 based on netty-4.1.5

### ISSUE THREAD

**Issue by liuhualh** [netty/netty#5930]
Hi, dears

Our backend service using HTTP2 to send Apple push notification to APNS, but we may load many different SSL certificated in one process.  While testing we found Java execute GC and fail (OutOfMemoryError) after the service instance reaches 2000~

Anaylzed using jvisualvm, we found there are about:

io.netty.util.internal.shaded.org.jctools.queues.MpscArrayQueue 4.8919438505775705  224,333 (4.9%)  147,162,448 (10.9%)
java.lang.Object[]  11.54954768714657   529,635 (11.5%) 963,235,296 (71.7%)

Majority of the java.lang.Object[] is referenced by MpscArrayQueue

I wonder what happens for this case, and if there is some specific notice I have ignored while using netty HTTP2

Thank you for your any advice

**Comment by Scottmitch** [comment]
can you provide a heap dump while the memory leak is visible? Also are you able to isolate this issue into a minimal reproducer?

**Comment by liuhualh** [comment]
This is overview of the heap dump,  java.lang.Object[] occupies 71.4% heap size, and MpsArrayQueue occupies 10.9% heap size

<img width="984" alt="netty-memory-leak-overview" src="https://cloud.githubusercontent.com/assets/3794741/19595961/e593f692-97be-11e6-99ad-633ac37a7d90.png">

From this picture,  manny java.lang.Object[] are referenced by MpsArrayQueue

<img width="992" alt="netty-memory-leak-objectarray" src="https://cloud.githubusercontent.com/assets/3794741/19596097/895a555a-97bf-11e6-9abf-bcf2679b5aca.png">

From this picture, MpsArrayQueue is reference by other object through ThreadLocal, one of is my application thread (RcApnsService.procThread)

<img width="979" alt="netty-memory-leak-objref" src="https://cloud.githubusercontent.com/assets/3794741/19596129/b9e1f912-97bf-11e6-910d-db04ea548b19.png">

However, my application thread does not have reference to Netty buffer explicitly.  The  application thread  waits for user notification and calls Netty channel.write(httpRequest) eventually, I don't know if this make the above reference established.

Additionally, my classpath contains two Netty jars because of some other reason(netty-3.9.0.Final.jar, and netty-all-4.1.5.Final.jar), I don't know if this also may cause the problem, because [this article](http://www.infoq.com/cn/articles/netty-version-upgrade-history-thread-part) says local thread cache mechanism has changed between 3.x.x and 4.x.x

When the problem occurs, the CPU load becomes high and maybe GC try recycle memory but can not, and eventually throw "OutOfMemoryError: GC overhead limit exceeded"

Can anyone give me some advice, thank you very much

**Comment by normanmaurer** [comment]
Can you try using:
-Dio.netty.recycler.maxCapacity=0

Please let us know if you still see problem

**Comment by liuhualh** [comment]
@normanmaurer 
I just try again with parameters you mentioned, but it seams not work
The memory is still grow high

**Comment by liuhualh** [comment]
This is callstack how my application thread (RcApnsService) called InternalThreadLocalMap.
If Netty has some constraint where can or cannot call netty's function?  or maybe there is something wrong for my usage?

<img width="589" alt="netty-memory-leak-callstack" src="https://cloud.githubusercontent.com/assets/3794741/19620346/2e5b82ce-98ae-11e6-81a6-b22f3dbbdb5d.png">

**Comment by normanmaurer** [comment]
@liuhualh could you upload the dump somewhere ?

**Comment by normanmaurer** [comment]
@liuhualh ping

**Comment by liuhualh** [comment]
@normanmaurer I have upload heapdump file to [here](https://drive.google.com/open?id=0B8UhAB_v1hsqTWxlTTZiMzMyM1U), you can download it

Additionally, we have changed our application thread model and remove application thread (RcApnsService), and then this issue disappears

But I still want to know why this case occurs and its root reason,  later I try write mini-code to reproduce this case and share on github, please help to check if I take wrong usage for netty

Thank you very much

**Comment by normanmaurer** [comment]
@liuhualh can you check if this still happens with latest 4.1 code ?

**Comment by normanmaurer** [comment]
@liuhualh also what I think happens is that you allocate from "non-io" threads `ByteBuf` and have a lot of these "non-io" threads. Can this be the case ? I am asking as each thread will hold various caches for allocations.

**Comment by liuhualh** [comment]
@normanmaurer, you get the case and I also think so, from the above call stack, RcApnsService$2.run is a "non-io" thread, in my application there maybe have 
hundreds of this kind thread (one per certificate). Also from the above call stack, the "non-io" thread calls SslContextBuilder.build() which eventually calls TheadLocal cache needed by OpenSslClientContext.

But my question is if it is constraint rule that allocation  ByteBuf from a "non-io" thread directly or   which allocation Thread Local cache from some Netty API indirectly

If it is indeed a constraint rule, is there some documents about that.  or there are some other solutions, for example some explicit release or destroy API ?

Thank you very much

**Comment by normanmaurer** [comment]
@liuhualh usually only a very limited number of threads allocate `ByteBuf` and so the default value for caches is ok. That said once you start to allocate from a ton of different non-IO threads the default value for caches may be too high. So there are multiple things you can do:

- Use a separate `PooledByteBufAllocator` instance with caches disabled for allocation that is done from outside the IO thread
- Size the caches smaller

You can adjust the caches either via the constructor of `PooledByteBufAllocator` or via System properties:
https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java#L95

That said let me also write a change which allows you to use the same instance of `PooledByteBufAllocator ` and disable the use of caches for non IO threads. 

@liuhualh makes sense ?

**Comment by normanmaurer** [comment]
I will close this for now... please reopen if you think there is still an issue

**Comment by liuhualh** [comment]
@normanmaurer Thank you very much 👍

**Comment by krischung** [comment]
Hi, we use the latest netty (4.1.16) and have similar issue.

JVM heap memory usage of MpscArrayQueue and [Ljava.lang.Object keep increasing.
The server design also similar to @liuhualh , we have several hundreds of non-IO threads to alloc ByteBuf and write these ByteBuf to channel in the same non-IO thread.
I saw the allocator from IO thread and non-IO thread is the same object.
@normanmaurer do you have any suggestion?
@liuhualh  how do you solve this issue?

Thanks.

**Comment by liuhualh** [comment]
We remove "hundreds of non-IO threads" later by optimizing our service architecture, but maybe you can disable "useCacheForAllThreads" feature mentioned in #6085

Wish help you ~

**Comment by krischung** [comment]
@liuhualh
Finally we come out a solution is use MessageToBytesEncoder (IO thread) to generate ByteBuf.
Thanks for your reply.
