### ISSUE TITLE
ProxyHandler stalls the proxy handshake when auto-read=false

### ISSUE THREAD

**Issue by vkostyukov** [netty/netty#5933]
We're (Finagle) using the N4 tooling around proxies and just discovered a bug in [`ProxyHandler`](https://github.com/netty/netty/blob/4.1/handler-proxy/src/main/java/io/netty/handler/proxy/ProxyHandler.java). When auto-read is disabled (our default) a connection established with the proxy server goes into a stall state waiting for a first response and never receives that (fires a handshake timeout). This is a common problem and might be reproduced with both HTTP and SOCKS5.

While debugging this we noticed that a response was actually sent by a server, but was never read from the pipeline by a `ProxyHandler` since [it doesn't issue a read-request explicitly](https://github.com/netty/netty/blob/4.1/handler-proxy/src/main/java/io/netty/handler/proxy/ProxyHandler.java#L194-L211) and relies on auto-read (or previous handlers to issue the read).

The solution to this bug is pretty straightforward - we have to issue a read request (once for HTTP and twice for SOCKS5) if the auto-read is disabled.

We're working on the PR (with the fix) right now.

**Comment by vkostyukov** [comment]
Adding some new details. Turns out we only need to issue one read to trigger the handshake (no matter how many messages it takes to complete for HTTP and SOCKS5) given that [`ProxyHandler.readComplete()`](https://github.com/netty/netty/blob/4.1/handler-proxy/src/main/java/io/netty/handler/proxy/ProxyHandler.java#L387-L389) will keep reading for us.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5939
