### ISSUE TITLE
Incomplete Cipher Suits for ALPN

### ISSUE THREAD

**Issue by johnson-li** [netty/netty#5937]
Netty version
===
 4.1.6.Final

Context
===
I used [Http2Client](https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http2/helloworld/client/Http2Client.java) to get page from [this site](https://instagramstatic-a.akamaihd.net/h1/bundles/en_US_Commons.js/27575146c4ea.js), and encountered an exception

> 7:04:41.814 [nioEventLoopGroup-2-1] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalStateException: unknown protocol: 
	at io.netty.example.http2.helloworld.client.Http2ClientInitializer$1.configurePipeline(Http2ClientInitializer.java:110)
	at io.netty.handler.ssl.ApplicationProtocolNegotiationHandler.userEventTriggered(ApplicationProtocolNegotiationHandler.java:92)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:326)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:318)
	at io.netty.handler.ssl.SslHandler.setHandshakeSuccess(SslHandler.java:1196)
......

Inspection
===
To inspect the problem, I used chrome to load the same page and found that this site uses `AES_256_GCM` for TLS, whick works fine.

After that, I check the client hello package and the server hello package of Netty through wireshark. The client hello package only contains 4 cipher suites:

- TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)
- TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)
- TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x009e)
- TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 (0x00a2)
 
`AES_256_GCM` is not included in them.

And the server hello package states the cipher suite as TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f), but this package contains no protocol information, which made Netty fail to recognize the correct protocol.

I am not sure why the server returned this strange response, but I am more curious about why Netty only supports these 4 cipher suites? Is there any way for Netty to support AES_256_GCM(add this to client hello package)?

ps: I am using alpn-boot-8.1.9.v20160720.jar, is this the limitation of alpn-boot and how can I solve the problem?

**Comment by slandelle** [comment]
This is a duplicate of #5859 that has already been fixed (will be released in 4.1.6.Final).
Check this issue for instruction on how to explicitly set enabled cipher suites.

**Comment by johnson-li** [comment]
It seems I'm using the fixed version of Netty. 

`.ciphers(Http2SecurityUtil.CIPHERS, SupportedCipherSuiteFilter.INSTANCE)`
[This line](https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http2/helloworld/client/Http2Client.java#L74) calls SslContextBuilder.ciphers(). And Http2SecurityUtil.CIPHERS truely contains `AES_256_GCM`. 

`cipherSuites = checkNotNull(cipherFilter, "cipherFilter").filterCipherSuites(ciphers, DEFAULT_CIPHERS, SUPPORTED_CIPHERS);`
But unfortunately, in the [place](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/JdkSslContext.java#L178) where CipherSuiteFilter.filterCipherSuites() is called, `AES_256_GCM`  is not included in SUPPORTED_CIPHERS.

So who can I make Netty support `AES_256_GCM` with alpn-boot?

**Comment by slandelle** [comment]
@johnson-li Missing [JCE strength policy files](http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html)?

**Comment by johnson-li** [comment]
@slandelle 
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

I don't think there is any problem of my JDK. How can I tell if JCE strength policy files are missing?

**Comment by johnson-li** [comment]
@slandelle US_export_policy.jar and local_policy.jar both exist on my system

**Comment by slandelle** [comment]
> US_export_policy.jar and local_policy.jar both exist on my system

IIRC, they always do and the patch replaces them.

**Comment by johnson-li** [comment]
@slandelle That's great! AES_256_GCM works fine now.

But I was wrong about why this exception occurred, the root cause is that the server requires [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication). 

So I changed 
`pipeline.addLast(sslCtx.newHandler(ch.alloc()));` to `pipeline.addLast(sslCtx.newHandler(ch.alloc(), host, port));` in [Http2ClientInitializer](https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http2/helloworld/client/Http2ClientInitializer.java#L97)

Thanks a lot for your help!

**Comment by normanmaurer** [comment]
What java version?
