### ISSUE TITLE
non-daemon thread with DefaultThreadFactory

### ISSUE THREAD

**Issue by wu-xiang** [netty/netty#5938]
Why  not set daemon to true in DefaultThreadFactory by default?
Our application will not terminate for this reason.

**Comment by Scottmitch** [comment]
I'm not sure if this has been considered but it would be a breaking change. Can you just use one of the [constructors](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/concurrent/DefaultThreadFactory.java#L62) that allows you to control if threads are daemons?

**Comment by normanmaurer** [comment]
@wu-xiang if you correctly shutdown your resources (like the `EventLoopGroup`) there should be no problems. If it hangs you miss to shutdown stuff correctly which I consider a bad thing. 

That said as @Scottmitch pointed out you can just use a different constructor and use a `ThreadFactory` which creates daemon threads if you really want to.
