### ISSUE TITLE
OCSP Stapling 

### ISSUE THREAD

**Issue by creativeprogramming** [netty/netty#5943]
Please read this article:
https://letsencrypt.org/2016/10/24/squarespace-ocsp-impl.html

Especially:

> Our extension is a standalone library but we could equally well fold it into the netty-tcnative library itself. If there is interest, we can contribute it upstream as part of Netty’s next API-breaking development cycle.

hoping you'll show that there's interest! my 2 cents

**Comment by rkapsi** [comment]
Hey there,

I'm the one who wrote that said library at Squarespace. The C code is really simple. Maybe 300 LoC with comments. Getting that plugged into Netty in the current incarnation is a bit more elaborate. It works for us but isn't something we'd want to support externally. Adding it straight to SslContext and SslEngine would condense it down to an enable/disable method and a add/remove callback method. It's really simple but I don't know how people feel about maintaining C code.

Happy to chat more about it.

**Comment by creativeprogramming** [comment]
Hi @rkapsi I'm no one to endorse Netty positions, just a user, but as still no reply I want to give another 'my 2 cents' to this cause, saying that an open source PR with C code will surely appreciated by many, if not in Netty also in other open source projects, e.g. VertX devs https://github.com/eclipse/vert.x/issues/1689 showed interest in having this feature in VertX that uses Netty's SslContext internally so they can surely review one PR from you.

> It works for us but isn't something we'd want to support externally. Adding it straight to SslContext and SslEngine would condense it down to an enable/disable method and a add/remove callback method. It's really simple but I don't know how people feel about maintaining C code.

Of course it can be disabled by default and of course you can share the code 'AS IT IS, WITHOUT WARRANTY OF ANY KIND'  in pure open source spirit :) 

In any case Thank you, even you article on letsencrypt blog was precious for me and I think many others!

**Comment by normanmaurer** [comment]
Do you think we could merge it into netty-tcnative ?

**Comment by normanmaurer** [comment]
@rkapsi Ping :)

**Comment by rkapsi** [comment]
@normanmaurer Pong

That would be the idea. Either adding the native code directly to netty-tcnative or leave it as a sidecar library. The important part is to move the "lifecycle" of the Java side of this stuff under SslContext's control. The user should be able to enable/disable OCSP straight on the context and every SslEngine that comes out of it is ready to pass along the staple (server) or verify the staple (client).

Right now it's managed externally and is a bit specific to our use-case. It's definitively not a simple matter adding it to the classpath. Existing projects would need some refactoring and would be subject to API breakage. Something I wouldn't want to endorse nor support. A win-win for everybody would be to incorporate it into Netty. :)

I should mention that this is only dealing with passing the staple in the form of a `byte[]` into OpenSSL (server) and being called from OpenSSL to verify it (client). It's pretty raw. How that `byte[]` comes to existence is a different problem. It's probably worth looking at [JEP 249](http://openjdk.java.net/jeps/249) for inspiration but it will balloon the API quickly. It'll all depend on what you want to get out of this.

**Comment by normanmaurer** [comment]
@rkapsi please do a "dirty and quick" PR against netty-tcnative and we can discuss directly there :) Thanks!

**Comment by rkapsi** [comment]
@normanmaurer pushed a PR with an UML diagram which will hopefully give some context down the road. Code will follow over the weekend or so.

**Comment by leogomes** [comment]
@rkapsi @normanmaurer Any progress on this? Would external help be welcome :) ?

**Comment by rkapsi** [comment]
@leogomes it's done. I think the only thing that hasn't happened yet is a new tcnative release.

https://github.com/netty/netty-tcnative/commit/1e77375fd0b74b214c8b578b6b358e972ae2fec2

https://github.com/netty/netty/commit/077a1988b9c96b5f3e5693a3bb1b2e118992f3a8

**Comment by Scottmitch** [comment]
Since these PRs have been merged lets close this issue. This feature should be available in the next release. Good stuff @rkapsi.

**Comment by eolivelli** [comment]
For future reference, if have found this interesting example that tells how to effectively use OSCP with Netty

https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/ocsp/OcspServerExample.java
