### ISSUE TITLE
About WebSocketServerCompressionHandler.class problem

### ISSUE THREAD

**Issue by zhangweixin** [netty/netty#5944]
I use WebSocket function of netty(4.1.5) in my project. When  I add that handler to ChannelPipeline in 
 server , the client(chrome/firefox) sends a message will fail, and then shut down automatically socket link. 
 If I didn't do that, client can work normally. I  find server response building link has one field As shown
 in the figure below ,when server have that handler in  ChannelPipeline .
![image](https://cloud.githubusercontent.com/assets/8088377/19720669/bae0565c-9ba1-11e6-8585-913821361ddf.png)
then , client(chrome/firefox) client does not work. if server haven't that handler , That field in response will  not exist and client is ok. the netty4 example about websocket server has the same problem.
I hope someone tell me why,thanks!

**Comment by normanmaurer** [comment]
@zhangweixin can you show me the code ?

**Comment by normanmaurer** [comment]
I will close this for now... Please re-open with more infos if the problem still exists and you think its a netty bug
