### ISSUE TITLE
OpenSslSession#initPeerCerts creates too long almost empty arrays

### ISSUE THREAD

**Issue by ichaki5748** [netty/netty#5945]
netty 4.1.6 

io.netty.handler.ssl.ReferenceCountedOpenSslEngine.OpenSslSession#initPeerCerts

```
final byte[] clientCert;
...
int len = clientCert.length + 1; // <------ BUG: raw certificate byte array size is used
peerCerts = new Certificate[len];
x509PeerCerts = new X509Certificate[len];

```

But should probably be

`int len = chain.length + 1; // <------ so we have first entry as client cert + chain.length`

**Comment by normanmaurer** [comment]
Maybe want to provide a PR with a fix?

**Comment by ichaki5748** [comment]
Yes, sure, will try to do it this week

**Comment by normanmaurer** [comment]
Thx

**Comment by ichaki5748** [comment]
Also io.netty.handler.ssl.OpenSslJavaxX509Certificate#unwrap

**Comment by ichaki5748** [comment]
Also io.netty.handler.ssl.OpenSslJavaxX509Certificate.* 
could theoretically blow in concurrent usage because of lazy init in io.netty.handler.ssl.OpenSslJavaxX509Certificate#unwrap because 
io.netty.handler.ssl.OpenSslJavaxX509Certificate#wrapped is not volatile (certificate would not be fully initialized)?

**Comment by normanmaurer** [comment]
@iainmcgin please open separate PRs for the separate issues and ping me once you are ready. I will review then

**Comment by iainmcgin** [comment]
You probably meant to reference @ichaki5748

**Comment by normanmaurer** [comment]
@iainmcgin ups yes... sorry I need more ☕️

**Comment by ichaki5748** [comment]
@normanmaurer Hi, please see PR https://github.com/netty/netty/pull/5965 and https://github.com/netty/netty/pull/5966

**Comment by ichaki5748** [comment]
@normanmaurer Hi, please see https://github.com/netty/netty/pull/5967 https://github.com/netty/netty/pull/5966

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5967
