### ISSUE TITLE
LineEncoder and StringEncoder are slower than naive java implementation

### ISSUE THREAD

**Issue by doom369** [netty/netty#5946]
Hello. I had a production code : 

```
public static ByteBuf makeStringMessage(String data) {
    byte[] byteData = data.getBytes(StandardCharsets.UTF_8);
    return PooledByteBufAllocator.DEFAULT.buffer(byteData.length).writeBytes(byteData);
}
```

it was working fine, however I found that netty `LineEncoder` and `StringEncoder` using another code : 

```
    @Override
    protected void encode(ChannelHandlerContext ctx, CharSequence msg, List<Object> out) throws Exception {
        if (msg.length() == 0) {
            return;
        }

        out.add(ByteBufUtil.encodeString(ctx.alloc(), CharBuffer.wrap(msg), charset));
    }
```

So i was expecting that those `ByteBufUtil.encodeString` will work faster (as netty uses it :)). So before any changes I made benchmark that showed me quite opposite. 

Here is benchmark that show this difference : 

```
@BenchmarkMode(Mode.AverageTime)
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@State(Scope.Thread)
@Fork(1)
@Warmup(iterations = 5, time = 1, timeUnit = TimeUnit.SECONDS)
@Measurement(iterations = 10, time = 1, timeUnit = TimeUnit.SECONDS)
public class StringToByteBufPerfTest {

    public PooledByteBufAllocator DEFAULT;

    @Param({"", "small", "This is test String!", "ddddddd dddddddddddddd ddddddddddddd ddddddddddddddddddddddddddddddddd"})
    public String data;

    @Setup
    public void setup(BenchmarkParams params) {
        DEFAULT = new PooledByteBufAllocator(true);
    }

    @Benchmark
    public ByteBuf javaWay() {
        ByteBuf byteBuf = null;
        try {
            byte[] bytes = data.getBytes(StandardCharsets.UTF_8);
            byteBuf = DEFAULT.buffer(bytes.length).writeBytes(bytes);
            return byteBuf;
        } finally {
            if (byteBuf != null) {
                byteBuf.release();
            }
        }
    }

    @Benchmark
    public ByteBuf nettyWay() {
        ByteBuf byteBuf = null;
        try {
            byteBuf = ByteBufUtil.encodeString(DEFAULT, CharBuffer.wrap(data), StandardCharsets.UTF_8, 0);
            return byteBuf;
        } finally {
            if (byteBuf != null) {
                byteBuf.release();
            }
        }
    }

    @Benchmark
    public ByteBuf nettyWayWriteUtf8() {
        ByteBuf byteBuf = null;
        try {
            byteBuf = ByteBufUtil.writeUtf8(DEFAULT, data);
            return byteBuf;
        } finally {
            if (byteBuf != null) {
                byteBuf.release();
            }
        }
    }

}
```

Result : 

```
Benchmark                                                                                                  (data)  Mode  Cnt    Score    Error  Units
StringToByteBufPerfTest.javaWay                                                                                    avgt    5  131.835 ± 15.606  ns/op
StringToByteBufPerfTest.javaWay                                                                             small  avgt    5  140.924 ± 12.812  ns/op
StringToByteBufPerfTest.javaWay                                                              This is test String!  avgt    5  154.179 ± 18.794  ns/op
StringToByteBufPerfTest.javaWay            ddddddd dddddddddddddd ddddddddddddd ddddddddddddddddddddddddddddddddd  avgt    5  180.712 ± 30.660  ns/op
StringToByteBufPerfTest.nettyWay                                                                                   avgt    5  130.567 ± 10.860  ns/op
StringToByteBufPerfTest.nettyWay                                                                            small  avgt    5  157.845 ± 17.236  ns/op
StringToByteBufPerfTest.nettyWay                                                             This is test String!  avgt    5  211.887 ± 27.286  ns/op
StringToByteBufPerfTest.nettyWay           ddddddd dddddddddddddd ddddddddddddd ddddddddddddddddddddddddddddddddd  avgt    5  362.991 ± 54.220  ns/op
StringToByteBufPerfTest.nettyWayWriteUtf8                                                                          avgt    5   91.747 ±  2.087  ns/op
StringToByteBufPerfTest.nettyWayWriteUtf8                                                                   small  avgt    5  100.506 ± 11.378  ns/op
StringToByteBufPerfTest.nettyWayWriteUtf8                                                    This is test String!  avgt    5  108.312 ±  2.074  ns/op
StringToByteBufPerfTest.nettyWayWriteUtf8  ddddddd dddddddddddddd ddddddddddddd ddddddddddddddddddddddddddddddddd  avgt    5  140.643 ± 20.216  ns/op
```

So my proposal would be to change current `LineEncoder` / `StringEncoder` implementation with :

```
    if (utf-8) {
         byteBuf = ByteBufUtil.writeUtf8(DEFAULT, data);
    } else { 
         byte[] bytes = data.getBytes(charset);
         byteBuf = DEFAULT.buffer(bytes.length).writeBytes(bytes);
    }
```

WDYT? I would be happy to make PR. 

P. S. There is also `Unpooled` class that uses `ByteBufUtil.encodeString0`. However it requires further investigation.

Netty 4.1.5.Final
Ubuntu 14.04
Java 1.8.0_101

**Comment by slandelle** [comment]
Actually, the proper Netty way for UTF-8 should be `ByteBufUtil.writeUtf8(DEFAULT, average);`.

On my side, I tend to test charset, go with a fast path for UTF-8, which is the most common use case, and then fallback to a pooled CharsetEncoder based path.

**Comment by doom369** [comment]
@slandelle nice. Thanks for pointing. Your approach seems the fastest possible way.

**Comment by doom369** [comment]
@slandelle do you have some code samples? Look like `ByteBufUtil.writeUtf8(DEFAULT, average);` allocates larger ByteBuf (string.length * 3) and I'm not sure how to correctly truncate it to writer index.

**Comment by ichaki5748** [comment]
I would say that perf difference happens because netty version eventually writes to ByteBuf like one 'char' at a time but in String.getBytes java writes everything to array and you just copy everything in one go to ByteBuf. So writing to byte array is cheaper than writing to bytebuf (http://stackoverflow.com/questions/18913001/when-to-use-array-buffer-or-direct-buffer)

But it would be interesting to compare heap memory footprints especially for 'long' strings. Taking into account that everything could be stack allocated by JIT

**Comment by doom369** [comment]
`I would say that perf difference happens because netty version eventually writes to ByteBuf like one 'char' at a time in for loop (for PooledDirectByteBuf) but in String.getBytes java writes everything to array and you just copy everything in one go to ByteBuf.`

That's not true. Netty version (except utf8Write) uses same code as JDK. Netty just does additional caching of Encoder + unnecessary wrapping `CharBuffer.wrap(msg)` that causes performance degradation.

**Comment by ichaki5748** [comment]
Stack trace would be like:
```
io.netty.buffer.ByteBufUtil#encodeString(io.netty.buffer.ByteBufAllocator, java.nio.CharBuffer, java.nio.charset.Charset)
io.netty.buffer.ByteBufUtil#encodeString0
java.nio.charset.CharsetEncoder#encode(java.nio.CharBuffer, java.nio.ByteBuffer, boolean)
java.nio.charset.CharsetEncoder#encodeLoop

```
in encodeLoop for e.g. UTF-8 we will have `var1.hasArray() == false` for Direct buffers and it will loop

```
protected final CoderResult encodeLoop(CharBuffer var1, ByteBuffer var2) {
            return var1.hasArray() && var2.hasArray()?this.encodeArrayLoop(var1, var2):this.encodeBufferLoop(var1, var2);
        }
```

Please correct me if I am wrong

Also your point is that netty creates two additional objects but that should give constant overhead independent on string size but your benchmarks shows opposite every character write has it's own added cost. 

Also I would say that if you would force usage of Heap Buffers you should not see big difference and it would be independent on size

**Comment by doom369** [comment]
You are right. My bad, sorry.

**Comment by ichaki5748** [comment]
No problem :) Please write if you try HeapBuffers or profile memory allocation - it would be interesting

**Comment by normanmaurer** [comment]
@doom369 do I understand right that we can close this one now ?

**Comment by doom369** [comment]
I think yes. `StringEncoder` is still slower, however there are pull request -https://github.com/netty/netty/pull/5532 with possible fix. So I'll wait for it. As within own code I did optimization.
