### ISSUE TITLE
Make it possible to specify initial settings for Http2Codec

### ISSUE THREAD

**Issue by nhnFreespirit** [netty/netty#5947]
Currently, when instantiating an Http2Codec, there does not appear to be any way of specifying non default initial settings.

**Comment by normanmaurer** [comment]
@nhnFreespirit so just to ensure I understand you right you suggest that we should for example allow to pass it in into the constructor ?

**Comment by nhnFreespirit** [comment]
Yeah, having it in  a constructor of Http2Codec would solve my issues nicely.

When constructing an http/2 client, it is possible to specify non default initial settings by subclassing AbstractHttp2ConnectionHandlerBuilder and invoking the initialSettings method, but unless I am missing something, there is no reasonable way to accomplish the same when using Http2Codec to build an http/2 server.

**Comment by nhnFreespirit** [comment]
I have a version of Netty with this added.

Only problem is I don't really like it, as to keep the initial settings optional, I have to add 2 new constructors to Http2Codec, so hesitant to create a pull request for this.

**Comment by nhnFreespirit** [comment]
created https://github.com/netty/netty/pull/5991

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5991#issuecomment-259270529
