### ISSUE TITLE
tcnative fails to load JNI library when embedded tomcat is in classpath

### ISSUE THREAD

**Issue by hzariv** [netty/netty#5948]
I have a Spring Boot application that is using embedded Tomcat. I needed to use netty-tcnative-boringssl-static (1.1.33.Fork23) but I am finding that when tomcat-embedded-core artifact is in the classpath the org.apache.tomcat.jni.Library gets picked up from tomcat-embedded-core instead of  netty-tcnative-boringssl-static. The results in failing to load the JNI library. Here is the code in question in io.netty.handler.ssl.OpenSsl class.

`private static void initializeTcNative() throws Exception {
       Library.initialize("provided");
        SSL.initialize(null);
    }`

**Comment by Scottmitch** [comment]
dup of https://github.com/netty/netty-tcnative/issues/151

We are planning to put netty-tcnative in its own namespace to avoid these conflicts.
