### ISSUE TITLE
Upgrade to JCTools v2.0, use the Unbounded MPSC to replace Chunked

### ISSUE THREAD

**Issue by nitsanw** [netty/netty#5951]

**Comment by normanmaurer** [comment]
@nitsanw can you explain what the `advantages` of the new impl is ?

**Comment by nitsanw** [comment]
IIUC Netty originally had an unbounded linked queue here. It then moved to using Chunked which is bounded and just set a very very high boundary on max size. Unbounded should offer a slightly faster and simpler resize logic, and a more accurate representation of the original intention.
Also note that this release fixes an issue with the Growable variant, but I don't think Netty uses it.
