### ISSUE TITLE
HttpClientUpgradeHandler waits for the fully buffered stream

### ISSUE THREAD

**Issue by mosesn** [netty/netty#5954]
The HttpClientUpgradeHandler should only need the headers to decide whether to upgrade or not, but it waits for the entire response.  This means that servers that respond with infinite streams will never know that their clients are only buffering the response.

We should instead change it to only buffer once it has decided that it is switching protocols.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5956
