### ISSUE TITLE
ByteBuf to its own library/project

### ISSUE THREAD

**Issue by cdancy** [netty/netty#5963]
I swear I've seen this talked about before but can't seem to find the thread or remember what the outcome of the discussion was.

Any thoughts/ideas/opinions to separating out Netty's ByteBuf impl into its own generic library? We know netty can be used in this way already but doing so brings in all the rest of netty (which may/may-not be Ok) and could potentially (depending on your build/execution context) bring in many dependencies that again may/may-not be Ok.

**Comment by slandelle** [comment]
> We know netty can be used in this way already but doing so brings in all the rest of netty

`ByteBuf` is already isolated into the `netty-buffer` module that only depends on `netty-commons`.

**Comment by cdancy** [comment]
@slandelle really? Huh ... I'll have to check that out. Thanks for pointing me in the right direction.
