### ISSUE TITLE
Possible bug in OpenSslEngine

### ISSUE THREAD

**Issue by nmittler** [netty/netty#5973]
Just looking at the code and it appears that we should be incrementing `bytesProduced` here: https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java#L623

@normanmaurer is this a bug or WAI?

**Comment by johnou** [comment]
@nmittler looks intentional, bytesProduced is passed into and incremented in readPendingBytesFromBIO.

**Comment by normanmaurer** [comment]
@nmittler yep as @johnou said.

**Comment by normanmaurer** [comment]
@nmittler so to clarify its not a bug.

**Comment by nmittler** [comment]
@johnou @normanmaurer *sigh* ... yep, sorry for the noise :P
