### ISSUE TITLE
Openssl-based SSLEngine differs slightly in unwrap behavior

### ISSUE THREAD

**Issue by jrudolph** [netty/netty#5975]
We are experimenting with netty's openssl based SSLEngines as an alternative to the JDK one ([for our effort](https://github.com/akka/akka-http/tree/jr/http2-on-netty-openssl) to produce an HTTP/2 implementation for akka-http). We use 
netty-tcnative-boringssl-static, version 1.1.33.Fork23. Thanks for providing that! When we talked at reactive summit you mentioned that you put much effort into making the openssl-based SSLEngines compatible with the JDK ones. So, you might be interested in the difference we found (knowing that the SSLEngine API has enough degrees of freedom to warrant a lot of behavior...).

I found that our stream-based wrapper around SSLEngine doesn't read all incoming data from the SSLEngine when there is no new incoming data from the network, so the application gets stuck waiting for incoming data. After some debugging I found out that with netty's openssl SSLEngine unwrap seems to produce plain text data in smaller chunks (probably single TLS frames) and keeps buffering the rest of the data internally. The src buffer is fully consumed but calling unwrap again with an empty src buffer will still produce more data. This differs from what the JDK SSLEngine does in two points:
 * the JDK SSLEngine consumes and produces as much data as possible in one go while the openssl one produces less output in one call
 * the JDK SSLEngine doesn't buffer encrypted data internally between calls to `unwrap` but "puts them back" into the src buffer

This also somewhat documented with this comment from https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLEngine.html:

> The SSLEngine produces/consumes complete SSL/TLS packets only, and does not store application data internally between calls to wrap()/unwrap().

Consequently, we [implemented the `unwrap` loop](https://github.com/akka/akka/blob/master/akka-stream/src/main/scala/akka/stream/impl/io/TLSActor.scala#L402) as

```scala
private def doUnwrap(ignoreOutput: Boolean = false): Unit = {
    val result = engine.unwrap(transportInBuffer, userOutBuffer)
    // ...
    result.getStatus match {
      case OK ⇒
        result.getHandshakeStatus match {
          case NEED_WRAP ⇒ // ...
          case FINISHED ⇒ // ...
          case _ ⇒
            if (transportInBuffer.hasRemaining) doUnwrap() // loop here only if there's still src data available
            else flushToUser()
```

With the openssl SSLEngine we are seeing the src buffer fully consumed after the first call to `unwrap` and we won't continue to call `unwrap` in a loop.

We can fix it for now by changing the condition to 

```scala
if (transportInBuffer.hasRemaining || (result.bytesProduced() > 0)) doUnwrap()
```

to keep looping while `unwrap` produces output.

Wouldn't it be more efficient to do this loop internally in the openssl implementation of `unwrap` to write as much data as possible into the output buffer?

**Comment by johnou** [comment]
Related? https://github.com/netty/netty/pull/4254

**Comment by jrudolph** [comment]
Yes, seems so. Thanks for the pointer.

**Comment by normanmaurer** [comment]
@jrudolph would be possible to submit a small unit test that works with JDK SSLEngine and fails with the OpenSslEngine ?

**Comment by jrudolph** [comment]
@normanmaurer yes, will try to build one, shouldn't be too hard.

**Comment by normanmaurer** [comment]
@jrudolph also when you say "the JDK SSLEngine doesn't buffer encrypted data internally between calls to unwrap but "puts them back" into the src buffer" do you mean that if you not completely drain   stuff into the dst buffer it will just adjust the position of the src buffer and so try to process it on the next call again ?

**Comment by jrudolph** [comment]
Here's a test I added to SslEngineTest: https://github.com/jrudolph/netty/tree/w/5975-SslEngine-test

It seems I was wrong about my first point. The JDK SSLEngine also only decrypts only one frame per unwrap call. Still it doesn't consume data that it hasn't read so far.

> @jrudolph also when you say "the JDK SSLEngine doesn't buffer encrypted data internally between calls to unwrap but "puts them back" into the src buffer" do you mean that if you not completely drain stuff into the dst buffer it will just adjust the position of the src buffer and so try to process it on the next call again ?

Hmm, no, I originally don't meant to imply that case. But, indeed, the difference can be seen here as well. JDK returns BUFFER_OVERFLOW without consuming the src buffer while openssl consumes the buffer. I added a commented out block in the test to check this behavior as well.

**Comment by normanmaurer** [comment]
@jrudolph let me look into it

**Comment by jrudolph** [comment]
I think the test case is not much different than @ijuma's [here](https://github.com/ijuma/netty/commit/0f6eff24885bfbe965d0cabd61115067d14feedc#diff-08da41869dfc1d842df441440b1c605bR232), so it might indeed just be a duplicate of #4238. Hi, @ijuma btw ;)

**Comment by normanmaurer** [comment]
@jrudolph are you license the shared code as ASL2 so I can include it in netty when I have a fix ?

**Comment by normanmaurer** [comment]
@jrudolph so after some digging I found out that the SSLEngineImpl (the JDK one) always only consume if a full packet is present while we even consume when it is only partly present. Both implementations correctly return `BUFFER_OVERFLOW` tho. I wonder if what we do is permitted.. I could not see details in the javadocs of `SSLEngine` which state that you can not consume a partial record. I am missing anything ?

The other "problem" is that our implementation will consume multiple records in one unwrap call but not write multiple out to the dsts buffers. The JDK implementation only consume one one record at a time (per unwrap call). Again I am not sure if what we do is allowed in terms of the the API and is just an implementation detail. That said I think we should also try to fill more then one record into the dsts buffers if we also consume more then one. 

@jrudolph WDYT ?

**Comment by normanmaurer** [comment]
@jrudolph actually I think this sentence may state we are not allowed to consume and still return a `BUFFER_OVERFLOW`:

```
The SSLEngine produces/consumes complete SSL/TLS packets only, and does not store application data internally between calls to wrap()/unwrap().
```
Agree ?

**Comment by normanmaurer** [comment]
@jrudolph ok nevermind.. I think I know how to "fix" the problems stated here. Will need to check what performance impact this has and if it is too much I may introduce a "strict" and non "strict" mode for the `OpenSslEngine`. Will keep you posted.

**Comment by jrudolph** [comment]
> @jrudolph are you license the shared code as ASL2 so I can include it in netty when I have a fix ?

Yes, here as well ;)

**Comment by jrudolph** [comment]
> @jrudolph actually I think this sentence may state we are not allowed to consume and still return a BUFFER_OVERFLOW:
> 
> The SSLEngine produces/consumes complete SSL/TLS packets only, and does not store application data internally between calls to wrap()/unwrap().
> Agree ?

Yes, exactly. (I quoted that sentence above as well.) Hard to say if this is a requirement or just a description of the implementation. It's probably impossible to take the javadoc as a water-tight specification (I guess you know best about that...).

IMO it's nice if you can rely on the openssl engine not to keep user data in internal buffers (if possible). I haven't looked into it in detail but how does the openssl engine provide backpressure? What happens if you always call `unwrap` e.g. with input buffers of size 30000 and output buffers of size 20000? Will data start to accumulate internally in the openssl engine or will it stop consuming the input buffer at some point?

**Comment by normanmaurer** [comment]
I have a fix locally here so it works as the JDK impl :) will open a PR later today 👍

**Comment by johnou** [comment]
@normanmaurer with the strict / non-strict as you previously mentioned? or did you manage to keep it simple?

**Comment by normanmaurer** [comment]
Was able to keep it simple

**Comment by normanmaurer** [comment]
@jrudolph  should be fixed by https://github.com/netty/netty/pull/5995

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5995

**Comment by borconi** [comment]
@jrudolph  - I know it's not nice to comment on an ancient closed topic especially when it's off-topic, but I will like to say a BIG TANK YOU. Your findings and description solved my 2 days no-sleep pain with SSLEngine, where the unconsumed data was copied back in the src, leaving my implementation hanging and waiting for more data. You are a life saver, so again a big THANKS!
