### ISSUE TITLE
Openssl SSLEngine reports too little size in session.getPacketBufferSize

### ISSUE THREAD

**Issue by jrudolph** [netty/netty#5976]
It seems OpenSSLEngine needs more package buffer space than the JDK one. Both JDK and Openssl report for `session.getPacketBufferSize` 18713 bytes (16665 + 2048) but the OpenSSLEngine will in some cases only succeed with buffers of size 16665 + 2048 + 58 (I bisected the exact amount, 1 byte less will still fail) and will otherwise return a BUFFER_OVERFLOW. 

This isn't a fatal problem as you can just provide more buffer space and call again. However, 
we relied on the invariant that a call to `wrap` can never result with BUFFER_OVERFLOW if the destination buffer was at least of size `session.getPacketBufferSize`. This allows us not to care for BUFFER_OVERFLOWs at all using the JDK SSLEngine. Not sure if that invariant really exists, though, so, one could say that this is just another degree of freedom the SSLEngine might leave to implementors.

**Comment by normanmaurer** [comment]
@jrudolph thats interesting... I wonder where the 58 bytes come from. Any idea ?

**Comment by normanmaurer** [comment]
@jrudolph also do you have a reproducer for this as well ? Would be interested to see when this happens.

**Comment by normanmaurer** [comment]
@jrudolph ping...

**Comment by jrudolph** [comment]
@normanmaurer sorry for the delay... Here's a reproducer: https://github.com/netty/netty/compare/4.1...jrudolph:5976-test-case

I couldn't reproduce the number above exactly. Instead, I found that the number of output buffer space depends on the number of input bytes. I guess the reason is that the openssl engine tries to output all outstanding data for several frames in one go.

**Comment by normanmaurer** [comment]
@jrudolph thanks a lot! I will open a PR with a fix for the other reported issue today. Maybe this will also fix this one :) Can you please confirm you grant me the right to include your test-code and so publish it under the ASL2 license as part of netty ?

**Comment by jrudolph** [comment]
Yes, I confirm that you can take the code under ASL2 license.

**Comment by normanmaurer** [comment]
@jrudolph I think that it fails is kind of expected as `OpenSslEngine` will return `18668`and `SSLEngineImpl` will return `16921` from `session.getSession().getPacketBufferSize()`. The difference exists as the `OpenSslEngine` also supports compression (if openssl was compiled with support for it) while the JDK implementation does not so has no need to account for the maximum overhead of it for a record. That said I wonder if we can detect if compression should be used or not and depending on this "select" the correct value.

Makes sense ?

**Comment by jrudolph** [comment]
Hmm I thought `session.getSession().getPacketBufferSize()` would be about the output side, i.e. the second argument of the `wrap` call. The hard coded number in the test is the amount of data going into the `wrap` call.

So, the difference is that for `SslEngineImpl` the amount of output for a `wrap` call always be <= `getPacketBufferSize` while the `OpenSslEngine` will return `BUFFER_OVERFLOW` depending on the amount of input data.

**Comment by normanmaurer** [comment]
@jrudolph ah sorry I misread the test-code. Let me check again... Stay tuned.

**Comment by normanmaurer** [comment]
@jrudolph ok I think there is another "issue" which is not related to #5975 . Debugging now.

**Comment by normanmaurer** [comment]
I know why this happen now 👍 Let me think about a fix

**Comment by normanmaurer** [comment]
@jrudolph please verify https://github.com/netty/netty/pull/6010 ... This should fix it

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6010

**Comment by pveentjer** [comment]
In which 4.1.x branch is this fixed?

**Comment by normanmaurer** [comment]
When you click on the commit you can see this... 4.1.7.Final
