### ISSUE TITLE
There may be resource leak in ChannelPool

### ISSUE THREAD

**Issue by xiaoshuang-lu** [netty/netty#5977]
Affects Version: 4.0 4.1

Here is the scenario which can reproduce this issue.

```
for (int i = 0; i < 8; ++ i) {
    Future<Channel> future = channelPool.acquire();
    future.get();
}

channelPool.close();
```

All channels acquired from channelPool leak.

What about making SimpleChannelPool introduce a container to hold all the channels created from the pool?

**Comment by normanmaurer** [comment]
@xiaoshuang-lu so you say closing the pool should also close all channels ?

**Comment by xiaoshuang-lu** [comment]
@normanmaurer Exactly.

**Comment by rkapsi** [comment]
I'd personally argue that it shouldn't close them right away but rather close all Channels that are being `release(...)` and it should fail all new `acquire(...)` requests.

But TBH, there are so many different use-cases that justify all kinds of different behaviors. Not sure an one-size-fits-all approach works here.

**Comment by normanmaurer** [comment]
@rkapsi @xiaoshuang-lu actually I think what @rkapsi suggested is the better option.

**Comment by xiaoshuang-lu** [comment]
Hi @normanmaurer, I think it will be much better if we remove the `final `qualifier for class `FixedChannelPool `since netty has no plan to fix issue. If so, customers can override `acquire`, `release`, and `close` of `FixedChannelPool`. What's your opinion?

**Comment by normanmaurer** [comment]
@xiaoshuang-lu its not final anymore... See https://github.com/netty/netty/commit/f6b37a38bac6dbea5dd2282c68a0f41c456f67a2. Let me close this one
