### ISSUE TITLE
getPayload() method returns nothing

### ISSUE THREAD

**Issue by GeorgeMatveev** [netty/netty#5979]
Hi, I am working on MQTT broker project based on Moquette 
which in turn relies on netty_parser, (via netty/PublishDecoder). 

When I try to get message data using msg.getPayload() I am getting NO data at all. 
And if I "stuff" my message with my data using ByteBuffer then everything works fine (see below).

    //This code WORKS fine!
    byte [] ba = new byte [] {'G','e','o','r','g','e'};
    ByteBuffer bb = ByteBuffer.wrap(ba);
    msg.setPayload(bb);//this works

Later I write it via FileChannel to disk, and get correct result:

$ cat mqtmessage.dat
George

And the whole program (i.e. my own code) works fine!

But code that comes standard with Moquette (using netty API) does not work:

    //copyMqt = new String(msg.getPayload().array());//NOP
    //copyMqt = new String(msg.getPayload().array());//NOP

So the problem seems to be in getPayload() method.

And it seems that was the reason Moquette project removed some code from their original version:

fedd296

Who would be the right person to fix this bug? 
Any ideas/estimations how/what is to be done?

It is MAJOR blocking issue in the whole MQTT broker project
and possibly other projects that depend on netty API.

Br,
GM

**Comment by normanmaurer** [comment]
@GeorgeMatveev it may be because the `ByteBuf` is not backed by heap memory but direct memory. Please report this to the `Moquette` project as I have no idea what exactly they are doing. Or provide an unit test that fails.

**Comment by GeorgeMatveev** [comment]
Hi,
good to hear from you.
You  have exactly repeated what developers from moquette project say:
"write test and look into their (netty) API" :-)

Here is more info with code, tech comments, as well as netty code from PublishDecoder where getPayload().array() is used:

https://github.com/andsel/moquette/issues/230

They used netty code originally but then removed it in July,
 see last comment on that page.

If you have an idea which part of netty code needs to be customized/fixed,
please give me a clue! We could possibly fix it.

Cheers,
GM
