### ISSUE TITLE
HttpObjectAggregator closes the http/1.x connection without a 'Connection: close' header

### ISSUE THREAD

**Issue by bryce-anderson** [netty/netty#5982]
Netty version: 4.1.6.Final

The [HttpObjectAggregator](https://github.com/netty/netty/blob/eb7f751ba519cbcab47d640cd18757f09d077b55/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectAggregator.java) will take it upon itself to return a 413 response when the message has too large of body [here](https://github.com/netty/netty/blob/eb7f751ba519cbcab47d640cd18757f09d077b55/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectAggregator.java#L216-L249). On the response it sends back, it does not add a `Connection: close` header, presumably to place nice with 100-continue requests. However, for the common case the connection _is_ closed, and by unexpectedly closing the connection, netty can trigger problems for clients which attempt to reuse the connection since it has not received notice that its being closed.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5983
