### ISSUE TITLE
build fails with and without tests (-DskipTests)

### ISSUE THREAD

**Issue by GeorgeMatveev** [netty/netty#5990]
Hi,
I cloned netty sources from git repo and attempted building it.

But build fails both with tests (mvn clean install) and without tests (mvn clean install -DskipTests):

[INFO] Reactor Summary:
[INFO] 
[INFO] Netty .............................................. SUCCESS [  8.208 s]
[INFO] Netty/Common ....................................... SUCCESS [ 24.477 s]
[INFO] Netty/Buffer ....................................... SUCCESS [ 10.972 s]
[INFO] Netty/Resolver ..................................... SUCCESS [  3.388 s]
[INFO] Netty/Transport .................................... SUCCESS [ 11.660 s]
[INFO] Netty/Codec ........................................ SUCCESS [ 10.157 s]
[INFO] Netty/Codec/DNS .................................... SUCCESS [  4.670 s]
[INFO] Netty/Codec/HAProxy ................................ SUCCESS [  3.823 s]
[INFO] Netty/Handler ...................................... SUCCESS [  9.985 s]
[INFO] Netty/Codec/HTTP ................................... SUCCESS [ 13.872 s]
[INFO] Netty/Codec/HTTP2 .................................. SUCCESS [ 11.299 s]
[INFO] Netty/Codec/Memcache ............................... SUCCESS [  4.509 s]
[INFO] Netty/Codec/MQTT ................................... SUCCESS [  3.705 s]
[INFO] Netty/Codec/Redis .................................. SUCCESS [  3.857 s]
[INFO] Netty/Codec/SMTP ................................... SUCCESS [  3.506 s]
[INFO] Netty/Codec/Socks .................................. SUCCESS [  4.627 s]
[INFO] Netty/Codec/Stomp .................................. SUCCESS [  3.747 s]
[INFO] Netty/Codec/XML .................................... SUCCESS [  3.722 s]
[INFO] Netty/Resolver/DNS ................................. SUCCESS [  4.684 s]
[INFO] Netty/Transport/RXTX ............................... SUCCESS [  2.449 s]
[INFO] Netty/Transport/SCTP ............................... SUCCESS [  3.393 s]
[INFO] Netty/Transport/UDT ................................ SUCCESS [  4.118 s]
[INFO] Netty/Handler/Proxy ................................ SUCCESS [  4.080 s]
[INFO] Netty/Example ...................................... SUCCESS [  7.905 s]
[INFO] Netty/Testsuite .................................... SUCCESS [  5.584 s]
[INFO] Netty/Testsuite/OSGI ............................... SUCCESS [ 12.819 s]
[INFO] Netty/Transport/Native/Epoll ....................... FAILURE [  9.657 s]
[INFO] Netty/Microbench ................................... SKIPPED
[INFO] Netty/All-in-One ................................... SKIPPED
[INFO] Netty/Tarball ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:16 min
[INFO] Finished at: 2016-11-08T14:15:18+01:00

Cheers,
GM

P.S. why do you close issues (e.g. 5979)  without resolving them???

**Comment by normanmaurer** [comment]
@GeorgeMatveev because I want you to reopen if its really a netty bug with more infos. 

For more details on the requirements for build see:
http://netty.io/wiki/native-transports.html#wiki-h2-2

**Comment by normanmaurer** [comment]
Please re-open if you still have trouble to build with the full console output included.
