### ISSUE TITLE
4.0.42.Final websocket syscall:read(...)

### ISSUE THREAD

**Issue by christ258** [netty/netty#5993]
hi，
I am using 4.0.42.Final.the websocket under some IP will appear the following error.When shaking hands with authorization server error display is in the back to the message wrong.

io.netty.channel.unix.Errors$NativeIoException: syscall:read(...)() failed: Connection reset by peer
        at io.netty.channel.unix.FileDescriptor.readAddress(...)(Unknown Source)

In 4.0.40.Final the still
Looking forward to your reply，Thank you！

**Comment by normanmaurer** [comment]
@christ258 this means the remote server has closed the connection forcibly. Nothing we can do about this in netty.

**Comment by christ258** [comment]
After the test, I found the reason is the network is very poor. There is no such way？
