### ISSUE TITLE
 Why bytebuf1.readBytes (byteBuf2) byteBuf1 in the byteBuf1 readable data is less than the length of byteBuf2 will be an error: IndexOutOfBoundsException.

### ISSUE THREAD

**Issue by carryxyh** [netty/netty#6014]
----------------------------------the method which throws exception-------------------
/**
     * Throws an {@link IndexOutOfBoundsException} if the current
     * {@linkplain #readableBytes() readable bytes} of this buffer is less
     * than the specified value.
     */
    protected final void checkReadableBytes(int minimumReadableBytes) {
        if (minimumReadableBytes < 0) {
            throw new IllegalArgumentException("minimumReadableBytes: " + minimumReadableBytes + " (expected: >= 0)");
        }
        checkReadableBytes0(minimumReadableBytes);
    }

    private void checkReadableBytes0(int minimumReadableBytes) {
        ensureAccessible();
        if (readerIndex > writerIndex - minimumReadableBytes) {
            throw new IndexOutOfBoundsException(String.format(
                    "readerIndex(%d) + length(%d) exceeds writerIndex(%d): %s",
                    readerIndex, minimumReadableBytes, writerIndex, this));
        }
    }

------------------------my code------------------------------------------
ByteBuf testRW1 = Unpooled.buffer(16, 16);
		ByteBuf testRW2 = Unpooled.buffer(16, 16);

		testRW1.writeInt(1);
		testRW1.writeInt(2);
		testRW1.writeInt(3);

		System.out.println("读之前可读长度:" + testRW1.readableBytes());
		System.out.println("读之前可写长度:" + testRW1.writableBytes());

		System.out.println("读之前writerIndex:" + testRW1.writerIndex());
		System.out.println("读之前readerIndex:" + testRW1.readerIndex());

		System.out.println("2的readIndex" + testRW2.readerIndex());
		System.out.println("2的writIndex" + testRW2.writerIndex());

		System.out.println("2的可读" + testRW2.readableBytes());
		System.out.println("2的可写" + testRW2.writableBytes());

		while (testRW1.isReadable()) {
			// testRW1.readBytes(testRW2);
			testRW1.readBytes(new byte[16]);
			System.out.println(testRW1.readableBytes());
		}

		System.out.println("读之后可读长度:" + testRW1.readableBytes());
		System.out.println("读之后可写长度:" + testRW1.writableBytes());

		System.out.println("读之后writerIndex:" + testRW1.writerIndex());
		System.out.println("读之后readerIndex:" + testRW1.readerIndex());

		System.out.println("读之后2的可读长度:" + testRW2.readableBytes());
		System.out.println("读之后2的可写长度:" + testRW2.writableBytes());

		System.out.println(testRW2.readerIndex());
		System.out.println(testRW2.writerIndex());

**Comment by normanmaurer** [comment]
@carryxyh sorry I am not sure if I understand your question ? Are you asking why we method was specified like this on the `ByteBuf` abstract class ?

**Comment by carryxyh** [comment]
I am very sorry,but my English is not so well.
I have a piece of code.
ByteBuf testRW1 = Unpooled.buffer(16, 16);
ByteBuf testRW2 = Unpooled.buffer(16, 16);

These are two ByteBuf. Then , I write something into testRW1:

testRW1.writeInt(1);
testRW1.writeInt(2);
testRW1.writeInt(3);

After writing , there are 12 bytes in the testRW1.
Then I want to move the 12 bytes data from testRW1 to testRW2 and I called the readBytes method:
testRW1.readBytes(testRW2);

Then,I get a IndexOutOfBoundsException : readerIndex(0) + length(16) exceeds writerIndex(12).

I want to know why the Exception was threw.

In my opionion，testRW2 is empty right ? And it's capacity is enough (It have 16 bytes space) ! Why can't move 12 bytes into testRW2 ?

This is the method which threw exception : (This method is in AbstractByteBuf.class.)
/-----------------------------/
private void checkReadableBytes0(int minimumReadableBytes) {
    ensureAccessible();
    if (readerIndex > writerIndex - minimumReadableBytes) {
        throw new IndexOutOfBoundsException(String.format(
                "readerIndex(%d) + length(%d) exceeds writerIndex(%d): %s",
                readerIndex, minimumReadableBytes, writerIndex, this));
    }
}
/-----------------------------/

**Comment by normanmaurer** [comment]
@carryxyh ah ok... let me check. This may be a bug.

**Comment by carryxyh** [comment]
Thanks for listening ! If u have some new information about this , please tell me ~ Thanks !!!

**Comment by normanmaurer** [comment]
@carryxyh actually this is exactly what the java docs explains. 

```
     * @throws IndexOutOfBoundsException
     *         if {@code dst.writableBytes} is greater than
     *            {@code this.readableBytes}
```

This is what you want to do to archive this tho:

```java
        ByteBuf testRW1 = Unpooled.buffer(16, 16);
        ByteBuf testRW2 = Unpooled.buffer(16, 16);
        testRW1.writeInt(1);
        testRW1.writeInt(2);
        testRW1.writeInt(3);

        testRW1.readBytes(testRW2, Math.min(testRW1.readableBytes(), testRW2.writableBytes()));
```
