### ISSUE TITLE
PooledByteBufAllocatorTest#testThreadCacheToArenaMappings random failure

### ISSUE THREAD

**Issue by slandelle** [netty/netty#6015]
Just happened on my machine: OSX, Hotspot 1.8.0_112

```
<<< FAILURE! - in io.netty.buffer.PooledByteBufAllocatorTest
testThreadCacheToArenaMappings(io.netty.buffer.PooledByteBufAllocatorTest)  Time elapsed: 0.215 sec  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<0>
	at io.netty.buffer.PooledByteBufAllocatorTest.testThreadCacheToArenaMappings(PooledByteBufAllocatorTest.java:238)
```

**Comment by normanmaurer** [comment]
interesting... never saw this. Can you reproduce it in a regular fashion @slandelle ?

**Comment by slandelle** [comment]
I haven't investigated nor tried to reproduce yet. It happened while working on an unrelated PR on codec-http (so built downstream this failing test). I wanted to report before I might forget.

**Comment by normanmaurer** [comment]
will check

**Comment by normanmaurer** [comment]
Ok I think what is wrong... But no worries its just a race in the test. Looking into it now.

**Comment by slandelle** [comment]
cool :)

**Comment by normanmaurer** [comment]
@slandelle fixed by https://github.com/netty/netty/pull/6077

**Comment by slandelle** [comment]
@normanmaurer Yeah, I saw that :) Great job!
