### ISSUE TITLE
Clear-text http/2 upgrade not working when multiple "connection" headers provided

### ISSUE THREAD

**Issue by ximyu** [netty/netty#6019]
According to https://tools.ietf.org/html/rfc7230#section-3.2.2, when multiple headers with same field name provided, the values should be concatenated, separated by comma.  However, at https://github.com/netty/netty/blob/eb7f751ba519cbcab47d640cd18757f09d077b55/codec-http/src/main/java/io/netty/handler/codec/http/HttpServerUpgradeHandler.java#L287 it's picking up only the value of the first "connection" header.

We ran into this issue then a Proxygen clients tries to connect to a server written in Netty 4.1.  Proxygen is sending multiple "connection" headers, containing "upgrade" and "HTTP2-Settings" respectively.  However, Netty is expecting one single "connection" header containing "upgrade,HTTP2-Settings".

**Comment by normanmaurer** [comment]
@nmittler @Scottmitch can you have a look please ?

**Comment by Scottmitch** [comment]
https://tools.ietf.org/html/rfc7230#section-3.2.2

> A sender MUST NOT generate multiple header fields with the same field
   name in a message unless either the entire field value for that
   header field is defined as a comma-separated list [i.e., #(values)]
   or the header field is a well-known exception (as noted below).

Strictly speaking Proxygen should not be generating multiple headers with the same name. However the updated HTTP/1.x maybe a bit too late to define this constraint as this can be common in practice, and in fact Netty doesn't always strictly enforce this constraint (although it can via `CombinedHttpHeaders`). I wouldn't be against accommodating for both csv and duplicate header names here. @nmittler @normanmaurer - WDYT?

**Comment by nmittler** [comment]
SGTM ... @ximyu do you want to throw together a PR?

**Comment by ximyu** [comment]
Sure

**Comment by normanmaurer** [comment]
@ximyu thanks!

**Comment by normanmaurer** [comment]
@ximyu ping

**Comment by ximyu** [comment]
Sorry for the delay. We ended up fixing the issue from client side (Proxygen).
