### ISSUE TITLE
How to convert DefaultHttp2HeadersFrame object to byte(ByteBuf)?

### ISSUE THREAD

**Issue by killjason** [netty/netty#6027]
How to convert DefaultHttp2HeadersFrame object to byte(ByteBuf)?

**Comment by normanmaurer** [comment]
@killjason this will be done by the `Http2FrameCodec` in the http2 package

**Comment by killjason** [comment]
@normanmaurer Http2FrameCodec doc describe as following:

>  Outgoing Http2Frame objects received via write are converted to the HTTP/2 wire format. 
So Http2FrameCodec just convert data to HTTP/2 format, not ByteBuf ?

**Comment by Scottmitch** [comment]
`Http2FrameCodec` is responsible for translating Http2 POJOs to/from Bytes. The `Http2FrameCodec` is currently in alpha and may not be feature complete. We have an alternative production grade API (which may be replaced some day by the `Http2FrameCodec` API) which does not use the same POJOs see https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/http2/helloworld/server for an example of this API

**Comment by killjason** [comment]
@Scottmitch Thank you for reply, actually this problem happened when I am trying to create a http2 reverse proxy, see :https://github.com/netty/netty/issues/6030

**Comment by killjason** [comment]
@Scottmitch the example you gave:
`    @Override
    public void onHeadersRead(ChannelHandlerContext ctx, int streamId,
                              Http2Headers headers, int padding, boolean endOfStream) {
        if (endOfStream) {
            ByteBuf content = ctx.alloc().buffer();
            content.writeBytes(RESPONSE_BYTES.duplicate());
            ByteBufUtil.writeAscii(content, " - via HTTP/2");
            sendResponse(ctx, streamId, content);
        }
    }`
It just convert String "- via HTTP/2" to ByteBuf, My problem is how to convert Http2Headers object to ByteBuf?

**Comment by Scottmitch** [comment]
Use `Http2ConnectionHandler#encoder()` to get the `Http2ConnectionEncoder` and then get the `Http2FrameWriter` via `Http2ConnectionEncoder#frameWriter()` then call `Http2FrameWriter#writeHeaders(...)`.

**Comment by killjason** [comment]
@Scottmitch Thank you.

**Comment by Scottmitch** [comment]
@killjason - np. Also make sure you are in the EventLoop thread while writing and generally interacting with the current HTTP/2 API as it is not thread safe.
