### ISSUE TITLE
http2 reverse proxy problem when execute writeAndFlush:unsupported message type

### ISSUE THREAD

**Issue by killjason** [netty/netty#6030]
I am creating a http2 reverse proxy , I copied the original example from : https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/proxy.
I change the `HexDumpProxyFrontendHandler ` to extend `Http2FrameCodec`;
Then in the `channelRead ` method, ` outboundChannel.writeAndFlush(msg)` throws an exception:
`DefaultChannelPromise@796d938f(failure: java.lang.UnsupportedOperationException: unsupported message type: DefaultHttp2HeadersFrame (expected: ByteBuf, FileRegion))`
What should I do to resolve this problem?

**Comment by killjason** [comment]
It seems that channel.writeAndFlush only support byte; so how to convert the DefaultHttp2HeadersFrame to byte? I googled a a lot but always failed with error: DefaultHttp2HeadersFrame is not serilizable...

**Comment by Scottmitch** [comment]
@killjason - the `Http2FrameCodec` portion of the API is in alpha

https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2FrameCodec.java#L44
>  * <p><em>This API is very immature.</em> The Http2Connection-based API is currently preferred over
 * this API. This API is targeted to eventually replace or reduce the need for the Http2Connection-based API.

Please use the currently supported HTTP/2 API or you may encounter some rough edges.

**Comment by killjason** [comment]
OK, got it.
