### ISSUE TITLE
Make FixedChannelPool non final

### ISSUE THREAD

**Issue by derbylock** [netty/netty#6037]
We use **FixedChannelPool**  in our project. But we have some problems adopting it to our needs. For example, we want to override methods **_pollChannel_** and **_offerChannel_** for monitoring purposes. We want to monitor count of channel objects in the pool. But it is difficult because **FixedChannelPool** is final. Could you consider removing final keyword from it, please?

**Comment by normanmaurer** [comment]
Sounds ok to me... @Scottmitch ?

**Comment by Scottmitch** [comment]
sgtm

**Comment by normanmaurer** [comment]
@derbylock could you provide a PR ?

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6059
