### ISSUE TITLE
Testfailure in ClientCookieDecoderTest

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#6049]
https://garage.netty.io/teamcity/viewLog.html?buildId=13846&buildTypeId=netty_build_oraclejdk7

java.lang.AssertionError: expected: 50, actual: -9223372036854775808
    at io.netty.handler.codec.http.cookie.ClientCookieDecoderTest.testDecodingSingleCookieV0(ClientCookieDecoderTest.java:50)

@slandelle can you have a look?

**Comment by slandelle** [comment]
I haven't been able to reproduce so far.

I even turned the test into a JMH benchmark with no avail:
```java
@Benchmark
public Cookie test() {
    String cookieString = "myCookie=myValue;expires=XXX;path=/apathsomewhere;domain=.adomainsomewhere;secure;";
    cookieString = cookieString.replace("XXX",
            DateFormatter.format(new Date(System.currentTimeMillis() + 50000)));

    Cookie cookie = ClientCookieDecoder.STRICT.decode(cookieString);

    boolean fail = true;
    for (int i = 40; i <= 60; i++) {
        if (cookie.maxAge() == i) {
            fail = false;
            break;
        }
    }
    if (fail) {
        throw new IllegalArgumentException("expected: 50, actual: " + cookie.maxAge());
    }

    return cookie;
}
```

**Comment by slandelle** [comment]
@normanmaurer Could you please merge my pending PR, before I send another one to improve the test and try to figure out what's going on?

**Comment by slandelle** [comment]
@normanmaurer Actually, I wonder if this failure really happened on the version that got finally merged. This failure might have been caused by an intermediate version that got fixed before final cherry-pick.

<img width="539" alt="teamcity" src="https://cloud.githubusercontent.com/assets/849197/20465795/6e062ec8-af66-11e6-9386-820e49b5d945.png">

**Comment by radai-rosenblatt** [comment]
happens to me, at 782b7bcf4a1db5f33078fe8f7ded8059770f7fc4
`cookieString="myCookie=myValue;expires=Mon, 21 Nov 2016 00:36:11 GMT;path=/apathsomewhere;domain=.adomainsomewhere;secure;"`

it eventually fails to find the time part out of that expired string.

**Comment by radai-rosenblatt** [comment]
after some further investigation the issue is parsing time stamps around midnight - "00:**:**".
this triggers the following code in HttpHeaderDateFormatter:
```
            char c = txt.charAt(i);
            if (isDigit(c)) {
                currentPartValue = currentPartValue * 10 + getNumericalValue(c);
            } else if (c == ':') {
                if (currentPartValue == 0) {
                    // invalid :: (nothing in between)
                    return false;   <----- WRONG
                }
```
00  means currentPartValue is 0, but the code thinks this means an error (which is wrong)

**Comment by radai-rosenblatt** [comment]
i've put up a PR to try and resolve this - https://github.com/netty/netty/pull/6050

**Comment by normanmaurer** [comment]
Fixe by #6050
