### ISSUE TITLE
Question of ioRatio in NioEventLoop and two backed array in SelectedSelectionKeySet

### ISSUE THREAD

**Issue by lightningMan** [netty/netty#6058]
Hi,
I was reading netty source code these days, netty is really a great project and the source code is so beautiful！

Now I have two questions to ask for your help：
## purpose of ioRatio in [NioEventLoop](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/nio/NioEventLoop.java#L452).

Does ioRatio mean the elapsed time of io operation?As the method`processSelectedKey` above   is cpu intennsive(copy bytes from tcp buffer to jvm direct buffer), is `ioRatio` simply used to control the proportion of copy bytes and business task?Is there any other purpose,like efficiency? ^^

## perhaps two backed array in [SelectedSelectionKeySet](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/nio/SelectedSelectionKeySet.java) may be reduced to one.

I see this set is backed by two arrays, but I think use one array can also do the same thing as every time after `NioEventLoop`call `processSelectedKeysOptimized(SelectionKey[] selectedKeys)`, the two `SelectionKey[]` is filled with `Null` point 

> flip method in SelectedSelectionKeySet
```java
SelectionKey[] flip() {
        if (isA) {
            isA = false;
            keysA[keysASize] = null;
            keysBSize = 0;
            return keysA;
        } else {
            isA = true;
            keysB[keysBSize] = null;
            keysASize = 0;
            return keysB;
        }
    }
```
perhaps if the flip method is replaced with `end` method as follows can do the same and also avoid exec`if (isA)` ^^
> end method
```java
   SelectionKey[] end() {
        keys[keysSize] = null;
        keysSize = 0;
        return keys;
    }
```

Thank you for your help!!!

**Comment by Scottmitch** [comment]
> purpose of ioRatio in NioEventLoop.

This provides a rough mechanism to control how much time is spent processing IO related tasks (socket reads, connects, closed, hangups, etc..) vs "non-IO" related tasks. The "non-IO" the Executor related events the IO thread has queued. The lower the number the more time will be spent on "non-IO" tasks, and currently 100 disables the timeout all together and runs all pending "non-IO" tasks.

> perhaps two backed array in SelectedSelectionKeySet may be reduced to one.

Some of the methods may return "invalid values" if we are operating on the internal array (e.g. `size`) ... however this may be OK if the interface is only inconsistent while we are using it ... @normanmaurer @trustin  - WDYT?

Also I wonder if the iteration to bounds in `processSelectedKeysOptimized` can be handled better:

https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/nio/NioEventLoop.java#L582

```java
// to call the updated method:
int size = selectedKeys.size();
processSelectedKeysOptimized(selectedKeys.flip(), size);

// alternatively if we make the changes suggested in this issue:
// processSelectedKeysOptimized(selectedKeys.array(), selectedKeys.size());


private void processSelectedKeysOptimized(SelectionKey[] selectedKeys, int end) {
  for (int i = 0; i < size; ++i) {
   final SelectionKey k = selectedKeys[i];
   // null out entry in the array to allow to have it GC'ed once the Channel close
   // See https://github.com/netty/netty/issues/2363
   selectedKeys[i] = null;

   ...

    if (needsToSelectAgain) {
      for (int x = i + 1; x < size; ++x) {
        selectedKeys[i] = null;
      }
      ...
    }
  }
}
```

**Comment by Scottmitch** [comment]
let me take a stab at this...

**Comment by lightningMan** [comment]
@Scottmitch thank you for eliminating my doubts, this is my first time to create an issue in github. I am so happy for receiving your reply^^

**Comment by lxchinesszz** [comment]
还是不太明白ioRatio 到底是什么作用,能给解释下吗

**Comment by Scottmitch** [comment]
@lxchinesszz - can you translate to English please?

**Comment by jiakme** [comment]
@lxchinesszz 

> This provides a rough mechanism to control how much time is spent processing IO related tasks (socket reads, connects, closed, hangups, etc..) vs "non-IO" related tasks. The "non-IO" tasks are Runnable objects queued in the EventLoopGroup due to using the Executor interface (e.g. Executor#execute(..). The lower the number the more time will be spent on "non-IO" tasks, and currently 100 disables the timeout all together and runs all pending "non-IO" tasks.

上面团队成员已经回答了啊.用来大致控制IO相关任何和非IO相关任务的时间分配比.

**Comment by Scottmitch** [comment]
thanks @jiakme
