### ISSUE TITLE
EpollServerDomainSocketChannel.isActive() return false after bind operation succeed

### ISSUE THREAD

**Issue by byoengguk** [netty/netty#6061]
Netty version: 4.1.0.Final

Context: I found bug on EpollServerDomainSocketChannel class. Its isActive() method always return false. It is required to set isActive = true in doBind() operation like EpollServerSocketChannel.

Steps to reproduce:
1. Use EpollServerDomainSocketChannel class to server bootstrap's channel class
2. Bind any unix domain socket.
3. Server Channel's channelActive() is not called due to EpollServerDomainSocketChannel.isActive() return false.

$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

Operating system: Cent OS 7.2 64-bit

$ uname -a
Linux  3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
Will check later today

**Comment by normanmaurer** [comment]
@byoengguk thanks for reporting... you are right. Let me fix this

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6078
