### ISSUE TITLE
Memory leak with ThreadDeathWatcher

### ISSUE THREAD

**Issue by pfpmeijers** [netty/netty#6062]
We are suffering from a memory leak:
At certain point in time ~200 M instances of MemoryRegionCache$Entry objects, retained by ~5000 of ThreadDeathWatcher$Entry objects. These ThreadDeathWatcher$Entry objects are all connected into a linked list. 
The ThreadDeathWatcher$Watcher's watchees array only contains 96 of direct references to ThreadDeathWatcher$Entry objects. In normal cases the size of this watchees array equals the total items in the linked list.
Hence, it looks like the linked list is not updated properly.

Is this a known issue? Any info on root cause, solution, work-around, etc.

Thanks in advance, Patrick

**Comment by normanmaurer** [comment]
Can you share a heapdump?

**Comment by normanmaurer** [comment]
Also which Version of meets you are using @pfpmeijers

**Comment by pfpmeijers** [comment]
Its very big (10 GB) and because of security rules I am not allowed to share a complete heap dump. I am really sorry. I still hope there is some help possible without.
I can share specific views if you indicate what you want to see in the dump.

We use following version:
        <version.netty>3.2.6.Final</version.netty>

**Comment by normanmaurer** [comment]
Sorry but 3.x is EOL ... please Upgrade to 4.x

**Comment by normanmaurer** [comment]
That said you could also try upgrading to latest 3.x version. Yours is super old

**Comment by normanmaurer** [comment]
@pfpmeijers actually you must be using netty 4.x as 3.x has no `MemoryRegionCache`. So please share some screenshots which show the references. Also I wonder what linked-list you are talking about as we not use a linked list in `ThreadDeathWatcher `

**Comment by pfpmeijers** [comment]
I mean the ThreadDeathWatcher$Entry, see following picture. The MpscLinkedQueue refers to the head and the tail.
![image](https://cloud.githubusercontent.com/assets/8824711/20642889/724fad7e-b41b-11e6-8a2c-ca33933b2125.png)
Path to PoolThreadCache and MemoryRegionCache entries:
![image](https://cloud.githubusercontent.com/assets/8824711/20642896/96a225a8-b41b-11e6-9bb2-b0d499b9b1f0.png)
![image](https://cloud.githubusercontent.com/assets/8824711/20642901/a0348ba6-b41b-11e6-979a-c29a7c99e880.png)
  
Links to ThreadDeathWatcher$Entry items:
![image](https://cloud.githubusercontent.com/assets/8824711/20642919/0a18782a-b41c-11e6-8461-bef17779a40b.png)

Note the difference between what is in the linked list and the "watchees" array size.
![image](https://cloud.githubusercontent.com/assets/8824711/20642874/12a2511a-b41b-11e6-942a-92ed3d2f16c8.png)
![image](https://cloud.githubusercontent.com/assets/8824711/20642879/1f3ba4da-b41b-11e6-9354-3fe4a8a56bd5.png)
In "normal" thread dumps I see these numbers being equal.

**Comment by normanmaurer** [comment]
Do you use a lot of different threads that allocate buffers?

**Comment by pfpmeijers** [comment]
Could be, actually don't know the exact context. Not looked into that yet.
Started with Jprofiler to analyse the heap dump

**Comment by pfpmeijers** [comment]
I had a look at the ThreadDeathWatcher code (4.0 version). Now have little better understanding. 
The problem seems to be that I have ~5000 items in the pendingEntries queue, with a huge amount of retained memory.
Its the Watcher's fetchWatchees() function that polls the items out of this queue and puts them into the watchees list. 
In the dump I can see the ThreadDeathWatcher.started field is true. But then you would expect the pending entries to be picked up by the Watcher's run()/fetchWachtees() function, assumed the thread also is running. 
Could there be some race condition?
Note that the increase of these items up to ~5000 took many minutes, hence it cannot be the sleep call that delayed the fetch.

I will check the amount of threads to be watched tomorrow with some other guy.

**Comment by normanmaurer** [comment]
@pfpmeijers a lot of items in the `pendingEntries` queue does not sound correct. Let me check the code if i can spot something

**Comment by normanmaurer** [comment]
@pfpmeijers also please tell me the "exact" version you are using.

**Comment by normanmaurer** [comment]
@pfpmeijers after looking into your diagrams again I think you use an old 4.0.x version which had an issue in `MpscLinkedQueue`. Could you please upgrade to latest 4.0.x release and let me know if you still see the problem ?

**Comment by pfpmeijers** [comment]
We are using version 4.0.26. 
Unfortunately an upgrade is not something easily done. We are using netty for many years now. First time we see this mem leak issue. It might be hard to reproduce, unless we know better what could be triggering the problem. 
Do you have more info about the issue in MpscLinkedQueue (issue number)?

I also checked whether one of the items close to the head might contain a null next pointer (instead of the tail item), but that is not the case. The link chain looks ok from head to tail in the heap dump.

**Comment by normanmaurer** [comment]
These are somehow related I think.


https://github.com/netty/netty/pull/3684 <https://github.com/netty/netty/pull/3684>
https://github.com/netty/netty/pull/5309 <https://github.com/netty/netty/pull/5309>

Basically calling isEmpty() from multiple threads can result in a live-lock:
https://github.com/netty/netty/blob/netty-4.0.28.Final/common/src/main/java/io/netty/util/internal/MpscLinkedQueue.java#L186 <https://github.com/netty/netty/blob/netty-4.0.28.Final/common/src/main/java/io/netty/util/internal/MpscLinkedQueue.java#L186>


So I think the only way to know for sure is if you upgrade or provide a unit test that fails with your version and we can run it with the new version.

**Comment by normanmaurer** [comment]
@pfpmeijers also could tell me if all the threads are active or not ?

**Comment by pfpmeijers** [comment]
You mean the threads that are referred to by the ThreadDeathWatch$Entry items?
There are ~5000 of these threads. Don't know how to check for being active easily within JProfiler.

See the overview:
![image](https://cloud.githubusercontent.com/assets/8824711/20670970/bbabdf72-b57b-11e6-9f40-90565b0eb901.png)

Typical names of the java.lang.Thread instances: “Thread-12345 (HornetQ-client-global-threads-123456789)”
Typical names of the org.hornetq.jms.server.recovery… instances: “HornetQ Recovery Discovery Reinitialization”

![image](https://cloud.githubusercontent.com/assets/8824711/20671012/dfafbdd0-b57b-11e6-9ece-4f1cc2d5bd9a.png)

**Comment by normanmaurer** [comment]
`threadStatus = 2` means its terminated : http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/sun/misc/VM.java?av=f .

And these are the `Entry`s that are in the pendingEntries queue ?

**Comment by pfpmeijers** [comment]
Mostly. I have 5157 ThreadDeathWatch$Entry items:
![image](https://cloud.githubusercontent.com/assets/8824711/20671648/73c8efbc-b57e-11e6-90bb-d5e2491abeb0.png)
91 items in the watchees list:
![image](https://cloud.githubusercontent.com/assets/8824711/20671761/f0c1eca8-b57e-11e6-8a31-4b6133021abf.png)
Need to check for the overlap, but from the code I would assume there isn't. In fetchWatchees() they are moved from the pendingEntries queue into the watchees arrary.

**Comment by pfpmeijers** [comment]
Hum strange, the head entry seems to be in the queue as well as in the array:
![image](https://cloud.githubusercontent.com/assets/8824711/20672201/a6f0eb18-b580-11e6-9e09-f8bbac8d4d33.png)
Its thread is terminated. I checked a few others in the queue and these are termined as well.
Also checked a few items in the watchees array, which are not terminated (high status number, e.q. 1025)

**Comment by normanmaurer** [comment]
@pfpmeijers I am afraid but I am suspect its a bug caused by what I linked you before, so you will need to upgrade. Also without a heap-dump and without you running the latest version its not easy to help and debug. Your version is 1,5 years old....

**Comment by pfpmeijers** [comment]
OK. We will try to find a scenario to reproduce the problem within our context.
Thanks for the help.

**Comment by pfpmeijers** [comment]
I had another close look at the code.
(I now understand why the head node is in the queue, as well as in the array. This is by design. The head is the previously polled node and not the next one being polled out.)

For the ThreadDeadWatcher's MpscLinkQueue usage:
isEmpty() (which does a peekNode()) is only used in the consumer thread. Not in the producer threads. 
The producer threads only use the add() method.

If isEmpty()/peekNode() would be live-locking, then head.next should be null, I guess.
(` do { next = head.next(); } while (next == null);`)
This is not the case in our dump.
![image](https://cloud.githubusercontent.com/assets/8824711/20685569/28b533a0-b5b5-11e6-8bfd-cf937df30ea6.png)

So apologies for my doubts/stubbornness, but I am not (yet) convinced that we are running into the issue that has been solved by these fixes (not saying that these fixes wouldn't solve our problem).

For us to decide whether we take the burden of porting and re-qualifying with the latest netty version, it is important that we understand the chance that the problem will occur again. Hence my effort in trying to find the root cause. And unfortunately I do not have any hypothesis left ...

Hopefully it will reproduce, and we will be able to attach profiler while still running, such that we can peek into the watcher deamon thread's activity.

**Comment by normanmaurer** [comment]
@pfisterer `isEmpty()` may be called by multiple threads at the same time as it can happen that more then one Thread is running the Watcher task at the same time. Just check the code.

I suspect it is caused by this that said I can't be 100 % sure without a reproducer. This is the only thing that really looks like it could cause a problem.

**Comment by pfpmeijers** [comment]
Check. In between the `stopped = started.compareAndSet(true, false);` and the `if (!started.compareAndSet(false, true))` the original watcher thread itself is still running (this code) but also a new thread can be started when a new watch request is done.

**Comment by normanmaurer** [comment]
Yep so it can be executed concurrently

**Comment by pfpmeijers** [comment]
One scenario that causes live lock (if I read/understood the code correctly):

```
Original watcher thread: 
	Finished fetching and notifying watchees.
	Checks pendingEntries.isEmpty(), which returns true => Queue: entry0 -> null
	Sets started flag to false.
	Checks pendingEntries.isEmpty():
		Checks peekNode():
			Gets head => entry0

Producer thread does a watch request:
	Adds a new entry (entry1) => Queue: entry0 -> entry1
	Starts a new watcher thread, because started flag was false.

Yet another producer thread does a watch request:
	Adds a new entry (entry2) => Queue: entry0 -> entry1 -> entry2

New watcher thread continues with fetching:
	Loop:
		Calls pendingEntries.poll():
			Calls peekNode(), which returns entry1.
			Sets head to entry1.
			Unlinks entry0	=> entry0 -> null, Queue: entry1 -> entry2

Original watcher thread:		
			If head != tail (which is the case), then waits for head.next != null, 
			=> Live lock. Head (entry0) is no longer in the queue.
```

This pattern can repeat itself. (Don't know whether this has been solved with the newer version. )
But anyhow this is not the scenario that we ran into, because in our case there are no dangling entries with next = null. 
So have to continue puzzling ... ;-)

**Comment by normanmaurer** [comment]
@pfpmeijers sorry but without more infos / thread-dump / profiler snapshot / heap dump I can not help you :(

**Comment by pfpmeijers** [comment]
@normanmaurer, I sent message to your gmail account (norman.maurer@googlemail.com).

**Comment by mckamps** [comment]
@normanmaurer: together with pfpmeijers we have discovered what caused the leak in our environment.

The watcher thread does a Thread.sleep(1000), and in some rare conditions this sleep simply does not return. And then (after 12-80 hours) we have an entry list of 5000 and huge memory consumption.
The question is still why such a sleep could hang (and we are still chasing that), but it makes the watcher thread vulnerable. I also came across other reports where thread.sleep hung in a VMware environment.

Pictures below are taken from the profiler when we reproduced the issue by having a short connectivity loss between VM and network storage; we instrumented the ThreadDeathWatcher class and it only shows watch requests on CPU - and the thread status remains sleeping:
![call stack - sleeping](https://cloud.githubusercontent.com/assets/25841421/23062613/b8e39b52-f506-11e6-9fd3-f85b0a5f52d4.PNG)
![thread status - sleeping](https://cloud.githubusercontent.com/assets/25841421/23062581/9cd9a924-f506-11e6-9ec5-08d42955e545.PNG)

After we interrupted the thread the CPU also shows fetchWatchees and notifyWatchees - and memory consumption immediately drops.
![call stack - running](https://cloud.githubusercontent.com/assets/25841421/23062625/c9efe4d2-f506-11e6-9ecf-84474bfcf495.PNG)
![thread status - running](https://cloud.githubusercontent.com/assets/25841421/23062628/d17a43d2-f506-11e6-8e73-6a5c41ab9970.PNG)

I would be curious to hear if you ever encountered this before? Would you agree to investigate if a better alternative exist for Thread.sleep?

**Comment by normanmaurer** [comment]
@mckamps @pfpmeijers wow... I never encountered this before. I am afraid but even if we would remove `Thread.sleep(...)` here you may get into trouble in other areas as even the JDK itself uses `Thread.sleep(...)` in a lot of places. If this only happens on vmware (which seems to be the case) I think you will need to work with vmware to fix it. 

As you can see its just a native method in Java:

http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/dcc009356125/src/share/classes/java/lang/Thread.java#l301
http://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/dcc009356125/src/share/native/java/lang/Thread.c#l51
http://hg.openjdk.java.net/jdk8u/jdk8u/hotspot/file/e765322578aa/src/share/vm/prims/jvm.cpp#l3172

**Comment by johnou** [comment]
@mckamps @pfpmeijers is ntp configured on that machine? you might want to try date -s "`date`"
 to ensure it is not related to the leap second bug.

**Comment by mckamps** [comment]
@normanmaurer Of course it would be best to fix the root cause, but I'm not sure yet if that is possible.
On the other hand: this `Thread.sleep(...)` is maybe more crucial than others - when this watcher thread remains asleep it will crash the application server.
BTW: may I assume that netty (and WildFly/EAP) is qualified in virtualized environments, or did I overlook some disclaimers?

@johnou Yes NTP is configured. But since the first occurrence was in November and the second end of January, I don't see a link with the leap second yet.

**Comment by dizzzz** [comment]
I found this:  http://bugs.java.com/bugdatabase/view_bug.do;jsessionid=c0af3bf36ff7fffffffffdbd3372166fe34d?bug_id=6311057

**Comment by mckamps** [comment]
@dizzzz Yes, something like that could explain it, but this specific bug is fixed iJava 6, and we run a somewhat newer version (7u51).

**Comment by dizzzz** [comment]
@mckamps well related http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6900441 is fixed in java8 ....

**Comment by normanmaurer** [comment]
@mckamps I am afraid but I still not think it makes sense to remove `Thread.sleep(...)` here. IMHO it sounds more like a JDK bug as @dizzzz suggested or linux / vmware bug. I am a bit shocked that you run 7u51 in prod tho, this is super old and EOL since a long time. Please upgrade your Java version and report back.

**Comment by dizzzz** [comment]
@normanmaurer  i'd like to suggest to create a github template for Issues, where reporters always should report Java version / OS / etc ... (helps us to understand) see [here ](https://github.com/blog/2111-issue-and-pull-request-templates ).

**Comment by normanmaurer** [comment]
@dizzzz actually we did add this after the issue was created ;) https://github.com/netty/netty/blob/4.1/CONTRIBUTING.md

**Comment by Scottmitch** [comment]
Also we have https://github.com/netty/netty/blob/4.1/.github/ISSUE_TEMPLATE.md for GitHub integration ... this template was also added a few days after this issue was created.

**Comment by mckamps** [comment]
@normanmaurer We found that either upgrading our Java version or upgrading the kernel version would solve the problem. We'll do both :-)

**Comment by dizzzz** [comment]
Suggest to close issue.....

**Comment by johnou** [comment]
@dizzzz I take it that updating Java and / or Kernel solved the issue then?

**Comment by Scottmitch** [comment]
Please re-open or create a new issue if you think there is still a Netty issue.
