### ISSUE TITLE
netty-common-4.1.6.Final.jar   \io\netty\util\collection 

### ISSUE THREAD

**Issue by sshling** [netty/netty#6065]
The source of the lack of “io.netty.util.collection” package, I do not know whether to migrate, or other circumstances.

from  http://mvnrepository.com/artifact/io.netty/netty-common/4.1.6.Final  
Jar package contains that  package

**Comment by normanmaurer** [comment]
@sshling its generated during the build from a template. Just run mvn clean compile and it will appear.

**Comment by sshling** [comment]
@normanmaurer 
Thanks。Yes, mvn clean compile 。
In the target directory to generate the corresponding .class file ,but src/main/java/io/netty/util not generate the corresponding .java file.

I am using IntelliJ IDEA, transport-native-epoll module io.netty.channel.epoll.EpollEventLoop.java cann't resolve symbol IntObjectMap, maybe need special settings idea, do you know?

**Comment by normanmaurer** [comment]
Just do man compile and the reimport the module
