### ISSUE TITLE
Server always waiting when client throws OutOfDirectMemoryError

### ISSUE THREAD

**Issue by stayfool** [netty/netty#6072]
After channel active, server sends a huge data to client, and then client throws OutOfDirectMemoryError,  then call  channel.close(), but the server doesn't  receive this event and still waiting, version is 4.0.33 .
This is the main code : 
server:
```java
    @Override
    public void channelActive(ChannelHandlerContext ctx) throws Exception {
        ctx.executor().parent().submit(() -> {
            int num = 0;
            try {
                while (true) {
                    log.error("starting send message {} ......", ++num);
                    ctx.channel().writeAndFlush(Unpooled.wrappedBuffer(new byte[1024 * 1024 * 200])).sync();
                }
            } catch (InterruptedException e) {
                e.printStackTrace();
                ctx.fireExceptionCaught(e);
            }
        });
    }
    @Override
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
        ctx.close();
        log.error(" lose connection ");
    }
```
client:
```java
    @Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
        log.error("accept something ");
    }
    @Override
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
        ctx.close();
        log.error(" lose connection ");
    }
```

**Comment by Scottmitch** [comment]
@stayfool - Please provide a complete reproducer. It is not clear what type of object is expected in the client's `channelRead` and what type of handler this is. For example are you expecting `ReferenceCounted` objects in this method?

**Comment by stayfool** [comment]
@Scottmitch object type is `ByteBuf` ,I didn't do anything with it, handler is a subtye of `ChannelInboundHandlerAdapter`.

Server:
`
public class OutBufferServer {
    private Logger log = LoggerFactory.getLogger(getClass());

    public static void main(String[] arg) {
        new OutBufferServer().start();
    }

    public void start() {
        ServerBootstrap b = new ServerBootstrap();
        NioEventLoopGroup nelg = new NioEventLoopGroup();
        try {
            b.group(nelg).channel(NioServerSocketChannel.class)
                    .childHandler(new ChannelInitializer<SocketChannel>() {
                        @Override
                        protected void initChannel(SocketChannel ch) throws Exception {
                            ch.pipeline().addLast(new OutBufferHandler());
                        }
                    })
                    .bind(9900).sync();
            log.error(" server start at : {}", 9900);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}

class OutBufferHandler extends ChannelInboundHandlerAdapter {
    private Logger log = LoggerFactory.getLogger(getClass());

    @Override
    public void channelActive(ChannelHandlerContext ctx) throws Exception {
        ctx.executor().parent().submit(() -> {
            int num = 0;
            try {
                while (true) {
                    log.error("starting send message {} ......", ++num);
                    ctx.channel().writeAndFlush(Unpooled.wrappedBuffer(new byte[1024 * 1024 * 200])).sync();
                }
            } catch (InterruptedException e) {
                e.printStackTrace();
                ctx.fireExceptionCaught(e);
            }
        });
    }

    @Override
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
        ctx.close();
        log.error(" lose connection ");
    }
}`

Client:
`
public class OutBufferClient {

    public static void main(String[] arg) {
        new OutBufferClient().start();
    }

    public void start() {
        Bootstrap b = new Bootstrap();
        NioEventLoopGroup nelg = new NioEventLoopGroup();
        b.group(nelg).channel(NioSocketChannel.class)
                .handler(new ChannelInitializer<SocketChannel>() {
                             @Override
                             protected void initChannel(SocketChannel ch) throws Exception {
                                 ch.pipeline().addLast(new DonotAcceptAnythin());
                             }
                         }
                );
        try {
            ChannelFuture cf = b.connect("localhost", 9900).sync();
            cf.channel().closeFuture().sync();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}

class DonotAcceptAnythin extends ChannelInboundHandlerAdapter {

    private Logger log = LoggerFactory.getLogger(getClass());

    @Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
        log.error("accept something ");
    }


    @Override
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
        ctx.close();
        log.error(" lose connection ");
    }
}`

**Comment by Scottmitch** [comment]
I'm not sure if this is intentional to demonstrate the OOME but `DonotAcceptAnythin#channelRead` must release the `msg`. See [1] for more details.

`OutBufferHandler` blocks the IO thread in a few different ways:

1. calling `sync` in the IO thread.
2. infinite loop

So if you don't return control back to the IO thread for that socket than that IO thread will not be able to detect any socket events.

[1] http://netty.io/wiki/reference-counted-objects.html

**Comment by stayfool** [comment]
I'm simulating if client can not deal with the data what will be happen

**Comment by Scottmitch** [comment]
@stayfool - Gotcha. Does the `OutBufferHandler` part make sense? It sounds like eventually the writes on the server will not be "completed" (the future will not be completed) because your peer is not reading the data, and therefore you are blocking the IO thread.

**Comment by stayfool** [comment]
@Scottmitch I did't try that. I think retain a number of buffer for control maybe better。
