### ISSUE TITLE
operationComplete of ChannelFuture is not called

### ISSUE THREAD

**Issue by liuhualh** [netty/netty#6073]
My application calls channel.writeAndFlush to send a HTTP2 request and then get a ChannelFuture, then calls addListener in order to be noticed while the writing procedure complete,  but from log there are some case that the operationComplete is not called, actually at that time the HTTP2 response has been received, 

I want to know if there are some cases that operationComplete could not be called after writeAndFlush

Thank you for any advice

**Comment by normanmaurer** [comment]
it must be always called..

Can you share your code.

**Comment by Scottmitch** [comment]
this sounds like an issue please share a reproducer

**Comment by liuhualh** [comment]
These days I have extracted HTTP2 related code from my application, but unfortunately I can not reproduce this case. But I still can reproduce it in our testing application.

Additionally, while trying to reproduce this case , only one time I reproduce this case, at that time I sent some HTTP2 POST request before HTTP2 SETTING negotiation finished, I don know if this the reason for lost of ** operationComplete**

Do you have some other advice for me to find the root cause, Thank you

**Comment by liuhualh** [comment]
Have found root reason, this is a bug in my application, sorry for disturbing

**Comment by normanmaurer** [comment]
@liuhualh thanks for closing the loop :)
