### ISSUE TITLE
Consider using an issue template

### ISSUE THREAD

**Issue by maseev** [netty/netty#6074]
I've noticed that despite the fact there are the [guidelines for contributing](https://github.com/netty/netty/blob/4.1/CONTRIBUTING.md), people still keep creating issues that contain so little information that is sometimes absolutely impossible to do anything without asking additional questions like:

- What Netty's version is a person using?
- What steps do I have to perform in order to reproduce the problem?
- What's the context of the problem (i.e expected behavior - actual behavior)?
- Any additional information: network configuration, JVM version, OS type/version, heap dump, stack trace, etc.

You might have heard about these features that GitHub [provides](https://github.com/blog/2111-issue-and-pull-request-templates). By creating a simple *.md file in the repository, GitHub will automatically use it as a template for any new issues/PRs (different *.md file, though). So, instead of asking people all these questions you might consider using the issue template. Chances are that you'll save a hell of a lot of time by integrating this feature into the current workflow.

[Here's](https://github.com/orientechnologies/orientdb/issues) an example of a project which uses this technique and here are the examples how to create [the pull request template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) and [the issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/).

**Comment by Scottmitch** [comment]
@maseev - I had not heard about this ... but this sounds great thanks!
