### ISSUE TITLE
http2 reverse proxy: how to reduce connections with backend server?

### ISSUE THREAD

**Issue by killjason** [netty/netty#6076]
imagine there are 10k http2-clients, they established 10k http2 connections(TCP-connections) with the http2 reverse proxy; then http2 reverse proxy create 10k http2 connections(TCP-connections) to the origin(backend) server.
**Is it possible to reduce the 10k connections between proxy and origin(backend) server?**
for example, can a connection pool be used in reverse proxy to reduce connections with backend server?

**Comment by killjason** [comment]
feed back:
there are some discusstions on: 
https://groups.google.com/forum/#!topic/grpc-io/fvS1ZkhikaQ

**Comment by Scottmitch** [comment]
I don't see anything which would prevent this. I'll defer to discussions on the google form since this doesn't appear to be a Netty bug.
