### ISSUE TITLE
First Close File Stream in NativeLibraryLoader's Load Method

### ISSUE THREAD

**Issue by jimdragongod** [netty/netty#6092]
When I used [pushy](https://github.com/relayrides/pushy) which  depends on the netty-handler 4.1.5.Final lib, and ran the Sample Code in README.md on Windows 7 x64, I got the lock exception of the netty-tcnative-windows-x86_64.dll file: “Another program is using this file, the process can not access”.
Finally I found the cause in the class' load method:
......
            out.flush();
            loadLibrary(loader, tmpFile.getPath(), true);
        } catch (Exception e) {
            throw (UnsatisfiedLinkError) new UnsatisfiedLinkError(
                    "could not load a native library: " + name).initCause(e);
        } finally {
            closeQuietly(in);
            closeQuietly(out);
......
Because the out stream is not close before invoking the loadLibrary method, the loadLibrary throws the exception.
Please fix it, many thanks!

**Comment by johnou** [comment]
It was fixed with 4.1.6.Final. See https://github.com/netty/netty/pull/5776

**Comment by jimdragongod** [comment]
I see, Thanks!
