### ISSUE TITLE
Building native transport epoll linux-x86_64_fedora

### ISSUE THREAD

**Issue by dlmarion** [netty/netty#6093]
Trying to build the native epoll transport. I cloned the repo, checked out the 4.0.38.Final tag, and issuing 'mvn clean install' in the netty/transport-native-epoll directory. It detects the operating system as:
```
[transport-native-epoll]$ mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 2.6
[INFO] os.detected.version.major: 2
[INFO] os.detected.version.minor: 6
[INFO] os.detected.release: centos
[INFO] os.detected.release.version: 6
[INFO] os.detected.release.like.rhel: true
[INFO] os.detected.release.like.fedora: true
[INFO] os.detected.release.like.centos: true
[INFO] os.detected.classifier: linux-x86_64-fedora
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Netty/Transport/Native/Epoll 4.0.38.Final
[INFO] ------------------------------------------------------------------------
```

However, the artifact is not named with the fedora classifier, it is simply named `netty-transport-native-epoll-4.0.38.Final-linux-x86_64.jar`. What am I missing?

**Comment by Scottmitch** [comment]
Can you clarify the issue? Is it that you want to build the `transport-native-epoll` module on a fedora based system (see [1]), or that you are expecting a `linux-x86_64-fedora` to exist in maven central?

[1] http://netty.io/wiki/native-transports.html#building-the-native-transport

**Comment by dlmarion** [comment]
@Scottmitch The issue is that the built artifact is named linux-x86_64, not linux-x86_64-fedora. So, if I specify the dependency in my project as directed in [1], it won't find it in my local maven repo. Is there something I am missing to get the classifier added to the artifact name during the build process, or do I need to rename it manually?

[1] http://netty.io/wiki/native-transports.html#building-the-native-transport

**Comment by dlmarion** [comment]
> or that you are expecting a linux-x86_64-fedora to exist in maven central?

That would be great. For now I am trying to build it myself.

**Comment by Scottmitch** [comment]
try to use the same classifier as netty does [<epoll.classifier>${os.detected.name}-${os.detected.arch}</epoll.classifier>](https://github.com/netty/netty/blob/4.1/pom.xml#L229) for your dependency. The wiki may need to be updated as I don't think we need a different `epoll` artifact for fedora.

**Comment by dlmarion** [comment]
Thanks, I will try that tomorrow.

**Comment by normanmaurer** [comment]
@dlmarion did it work ? ( I think it should )

**Comment by dlmarion** [comment]
@normanmaurer I got sidetracked with other issues. I will be able to try it mid week

**Comment by dlmarion** [comment]
@Scottmitch  @normanmaurer  changing the classifier as suggested works and all of my tests pass. Is it the case that I don't need a fedora-flavored native epoll jar? I will test further in the next day or so.

**Comment by normanmaurer** [comment]
@dlmarion yes that is the case... We will update the wiki.

**Comment by johnou** [comment]
@dlmarion iirc the only fedora-flavored Netty jar is netty-tcnative and that's because the shared libraries have a different naming convention..

tmp $ ldd linux-x86_64-fedora/META-INF/native/libnetty-tcnative.so
ldd: warning: you do not have execution permission for `linux-x86_64-fedora/META-INF/native/libnetty-tcnative.so'
linux-vdso.so.1 =>  (0x00007ffcb0966000)
libssl.so.10 => /usr/lib64/libssl.so.10 (0x00007f41ede72000)
libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f41eda8d000)
tmp $ ldd linux-x86_64/META-INF/native/libnetty-tcnative.so
ldd: warning: you do not have execution permission for `linux-x86_64/META-INF/native/libnetty-tcnative.so'
linux-vdso.so.1 =>  (0x00007ffcbb9f9000)
libssl.so.1.0.0 => not found
libcrypto.so.1.0.0 => not found

**Comment by Scottmitch** [comment]
I updated the wiki @normanmaurer PTAL.

**Comment by normanmaurer** [comment]
@Scottmitch thanks! LGTM :)

Let me close this one now
