### ISSUE TITLE
EventLoop.java shouldn't catch ConcurrentModificationException and just move on.

### ISSUE THREAD

**Issue by s1monw** [netty/netty#6095]
[EventLoop.java ](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/nio/NioEventLoop.java#L368) catches CME and simply continues to do what it was doing. I am not sure if that's intentional I mean if you hit this exception something really bad is going on. I wonder if this can happen due to concurrent close of the selector etc. There is also some really questionable code in this class that should be cleaned up like [this](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/nio/NioEventLoop.java#L192-L204) where some members of internal JDK classes are replaced with a very questionable implementation that according to it's [commit message](https://github.com/netty/netty/commit/3ce9ab2e72235bf2ae45f57de11803249419cb69) a not so sizeable performance gain. I am happy to open another issue for this but this class really needs some love given it's the core of the project.

**Comment by normanmaurer** [comment]
@s1monw I am looking into the first issue ATM. 

The second thing you brought about is more about reduce garbage and unfortunately is needed. Other high perf libraries like for example Aeron are doing basically the same for the same reason (reducing garbage).

**Comment by normanmaurer** [comment]
@s1monw also you can disable the optimization via a system property if it makes you feel uneasy

**Comment by normanmaurer** [comment]
@s1monw https://github.com/netty/netty/pull/6101 PTAL

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6101

**Comment by s1monw** [comment]
> The second thing you brought about is more about reduce garbage and unfortunately is needed. Other high perf libraries like for example Aeron are doing basically the same for the same reason (reducing garbage).

I think there is way more to this than you considered in your reply. Lemme give you some opinions and questions. 

* I really disagree with making crazy optimizations like the default behavior the fact that X% of people need to opt out of something that only  Y% use (I assume this is not necessary for the majority of users) is concerning.

* You are replacing an internal datastrucutre with a highly optimized implementation that does not suffice the contract of the set interface is concerning and I think if you do that then please do it right.

* SelectedSelectionKeySet.java doesn't have a single unit-test in place and it's used inside your event loop, really?

* I wonder, (I haven't looked so please enlighten me) how you test the different code-paths throughout your test suite. Something like this should be exercised well and afaik you have a bunch of different code-paths using that selector set. The `SelectedSelectionKeySet` one doesn't allow you to pull an iterator which prevents sharing code-paths (again I only looked briefly). Do you have randomization in place ie. use a framework like [Randomized Runner](https://labs.carrotsearch.com/randomizedtesting.html) to at least give both ways enough coverage. 

 * If you use netty with a security manager you automatically opt out of these optimizations which is difficult since debugging and reproducing of issues might be very very hard. Are you running your tests with a security manager installed to see how things behave?

I think there are many aspects and there is no up-to-date perf/impact testing that justifies this optimization. From a pure engineering perspective I really hope decisions can be re-though and re-evaluated and / or the environment that this stuff is developed in must be improved to at least make all code-paths viable for endusers.

**Comment by normanmaurer** [comment]
@s1monw can you please open another issue for this so we can discuss there ?

**Comment by normanmaurer** [comment]
@s1monw thanks! And don't get me wrong I am really happy that you take the time and energy to bring up these things.

**Comment by s1monw** [comment]
> @s1monw thanks! And don't get me wrong I am really happy that you take the time and energy to bring up these things.

don't worry I opened #6105
