### ISSUE TITLE
Regression: SSL session contains extraneous NULL extries in peer certificate chain.

### ISSUE THREAD

**Issue by JackOfMostTrades** [netty/netty#6098]
Netty version: 4.1.6.Final

Context:
Initiating client TLS negotiation with a certificate chain (client cert + trust chain) on netty 4.1.6.Final (with grpc-netty 1.02 and netty-tcnative-boringssl-static 1.1.33.Fork23) results in the SSLSession presenting a peer certificate chain array that is longer that the actual peer certificate chain, though the extra entries are all NULL. In the example below, the expected peer chain length is 2, but the returned array length is 412.

This scenario worked with grpc-netty 1.0.1, netty 4.1.5.Fina, and netty-tcnative-boringssl-static 1.1.33.Fork23.

Steps to reproduce:
Example program to reproduce posted using grpc 1.0.2:
https://github.com/JackOfMostTrades/netty-tcnative-crash-demo

$ java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.6 (jessie)
Release:	8.6
Codename:	jessie

$ uname -a
Linux lgud-ihaken 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@JackOfMostTrades i think this was fixed by https://github.com/netty/netty/commit/4ee361e3024b33ac3a160e8124ee7f0e5a1f4b42#diff-a1fda854eff0bab9ba7a0975852e7ed6 And so will be fixed in the next release
