### ISSUE TITLE
Memory leak path in MessageToByteEncoder.write

### ISSUE THREAD

**Issue by EclecticEngineer** [netty/netty#6108]
In MessageToByteEncoder.write, if the allocateBuffer method is overridden to return a direct buffer, there is a potential for a memory leak. Here is the implementation of the write method:

>         ByteBuf buf = null;
>         try {
>             if (acceptOutboundMessage(msg)) {
>                 @SuppressWarnings("unchecked")
>                 I cast = (I) msg;
>                 buf = allocateBuffer(ctx, cast, preferDirect);
>                 try {
>                     encode(ctx, cast, buf);
>                 } finally {
>                     ReferenceCountUtil.release(cast);
>                 }
> 
>                 if (buf.isReadable()) {
>                     ctx.write(buf, promise);
>                 } else {
>                     buf.release();
>                     ctx.write(Unpooled.EMPTY_BUFFER, promise);
>                 }
>                 buf = null;
>             } else {
>                 ctx.write(msg, promise);
>             }
>         } catch (EncoderException e) {
>             throw e;
>         } catch (Throwable e) {
>             throw new EncoderException(e);
>         } finally {
>             if (buf != null) {
>                 buf.release();
>             }
>         }

Notice that if buf.isReadable() returns false, buf.release will get called, but if it's true, it won't get called. Then, buf is set to null which causes the finally block to not release the buf.

Normally, it's a heap based buffer, so missing the release() isn't a problem. But if it's a direct buffer, this will be an off-heap memory leak every time write is called.

**Comment by normanmaurer** [comment]
If ctx.write(...) is called the ownership of the buffer is transferred to the next handler in the pipeline and if there is no other to the transport itself. Once the buffer is written to the OS it will automatically be released. So there is no leak
