### ISSUE TITLE
Netty fails to build on ppc64le platform

### ISSUE THREAD

**Issue by anuphalarnkar** [netty/netty#6111]
**OS:** Ubuntu 14.04
**Arch:** Power (ppc64le)

**Command to build:**
mvn clean install -DskipTests

**Failure message:**
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-tools) @ netty-parent ---
[WARNING] Rule 2: org.apache.maven.plugins.enforcer.RequireProperty failed with message:
x86_64 JDK must be used.

Any inputs on above will be greatly appreciated. 

Thanks in advance,
Anup Halarnkar

**Comment by normanmaurer** [comment]
@anuphalarnkar does this work ?:

`mvn clean install -DskipTests=true -Denforcer.skip=true`

**Comment by normanmaurer** [comment]
@anuphalarnkar let me close this ... if it still not works let me know
