### ISSUE TITLE
ResourceLeakDetectorTest.testConcurentUsage failure

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#6114]
### Expected behavior
ResourceLeakDetectorTest.testConcurentUsage should always pass.

### Actual behavior
ResourceLeakDetectorTest.testConcurentUsage failed while building on the CI server.
```
[22:46:42] :             [io.netty:netty-common] Tests in error:
[22:46:42] :             [io.netty:netty-common]   ResourceLeakDetectorTest.testConcurentUsage:89->Object.wait:-2 » TestTimedOut ...
```

https://garage.netty.io/teamcity/viewLog.html?buildId=14412&buildTypeId=pulls_netty&tab=buildLog

### Steps to reproduce
Build on the CI server

### Minimal yet complete reproducer code (or URL to code)
N/A (existing unit test).

### Netty version
4.1.7-SNAPSHOT
PR https://github.com/netty/netty/pull/6106 (assumed to be unrelated)

### JVM version (e.g. `java -version`)
Java HotSpot(TM) 64-Bit Server VM
jdk1.8.0_112

### OS version (e.g. `uname -a`)
Linux, version 3.16.0-4-amd64
https://garage.netty.io/teamcity/agentDetails.html?id=7&agentTypeId=7&realAgentName=debian7-1

**Comment by Scottmitch** [comment]
@normanmaurer - PTAL

**Comment by normanmaurer** [comment]
Will check

**Comment by normanmaurer** [comment]
@Scottmitch from the thread dump it seems like it was just not complete yet as it still created new leaks etc. I will increase the timeout .

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6120
