### ISSUE TITLE
Discard PooledByteBuf on demand

### ISSUE THREAD

**Issue by xdy2001** [netty/netty#6116]
### Expected behavior
Add a method `PooledByteBuf.discard()`. This method will discard the object instead pooling it again. 
Scenario: When a DirectByteBuf or HeapByteBuf is too large, the application can release memory. This is a complementary method to `PooledByteBuf.release()`

### Actual behavior
Pool all objects only limited by Recycler.maxCapacity
### Steps to reproduce
1. Out Product processes MySQL protocol, using Netty as the tcp message handler. The size of the response from MySQL server is from bytes to hundreds kilobytes. The capacity of all the pooling PooledDirectByteBuf objects will increasing larger and larger. finally the java process consumed >20G direct memry and crashed every 1 ~ 2 weeks. 
2. After we set io.netty.recycler.maxCapacity.default to 0 according to Netty documents. the problem resolved. The usage of memory is absolutely stable. 

3. But there is bottleneck on peaktime without pooling. The bottleneck is on direct memory allocation and deallocation as we check the jvm stracktrace.

### Minimal yet complete reproducer code (or URL to code)
N/A

### Netty version
4.1.2.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

### OS version (e.g. `uname -a`)
Linux 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Scottmitch** [comment]
Can you try Netty 4.1.6.Final and see if you can reproduce?

Also have you tried using a smaller default value (it is per thread).

**Comment by xdy2001** [comment]
Looks this parameter,  io.netty.threadLocalDirectBufferSize, is to limit the max size of pooling ByteBuf. this is exactly what this issue proposed. We will try to set this parameter and verify. Thanks @Scottmitch .
