### ISSUE TITLE
o.netty.handler.codec.http2.Http2ConnectionRoundtripTest.flowControlProperlyChunksLargeMessage test failure

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#6121]
```
java.lang.AssertionError
    at io.netty.handler.codec.http2.Http2ConnectionRoundtripTest.flowControlProperlyChunksLargeMessage(Http2ConnectionRoundtripTest.java:413)
------- Stdout: -------
10:24:23.310 [defaultEventLoopGroup-45-2] DEBUG io.netty.buffer.PoolThreadCache - Freed 5 thread-local buffer(s) from thread: defaultEventLoopGroup-45-2
10:24:23.517 [defaultEventLoopGroup-46-1] DEBUG io.netty.buffer.PoolThreadCache - Freed 4 thread-local buffer(s) from thread: defaultEventLoopGroup-46-1
```

See https://garage.netty.io/teamcity/viewLog.html?buildId=14438&buildTypeId=pulls_netty&guest=1

**Comment by normanmaurer** [comment]
@Scottmitch @nmittler can you have a look ?

**Comment by nmittler** [comment]
@normanmaurer when did this start happening? Do we have any recent changes that might be causing this?

**Comment by normanmaurer** [comment]
@nmittler it only happened one time... so I think it's a Race somewhere

**Comment by Scottmitch** [comment]
I've run the test 10,000 times locally and have not been able to repro yet. We have also seen other "first time" timeouts recently on the build servers (https://github.com/netty/netty/pull/6122). Not sure if these are related...

**Comment by normanmaurer** [comment]
@Scottmitch maybe... Let us just watch this for now I guess...

**Comment by normanmaurer** [comment]
We increased the timeout. Let me close this for now
