### ISSUE TITLE
Add readDoubleLE and readFloatLE methods to ByteBuf

### ISSUE THREAD

**Issue by mrniko** [netty/netty#6127]
ByteBuf.order methods are deprecated now and getShortLE, getIntLE .. methods should be used instead. But such important methods like `readDoubleLE` and `readFloatLE` are not implemented.

### Netty version
Netty 4.1.6

**Comment by Scottmitch** [comment]
Although this wouldn't be consistent with `readDouble` and `readFloat` (which abstract and implemented in `AbstractByteBuf`) we could add these methods and default implementations to `ByteBuf` ... @normanmaurer WDYT?

**Comment by normanmaurer** [comment]
@Scottmitch yeah... not sure about it... Let me think about it :)

**Comment by normanmaurer** [comment]
This was fixed by https://github.com/netty/netty/pull/7099
