### ISSUE TITLE
HttpObjectDecoder is unable to decode messages on AIX and Solaris (Big Endian platforms)

### ISSUE THREAD

**Issue by IgorAlelekov** [netty/netty#6128]
HttpObjectDecoder makes mistake calculating hash codes of AsciiString objects on Big Endian platforms (AIX and Solartis, please see test results below).
As the result it can't get "Content-Length" header from the incoming message and is unable to extract message's body.

**Test to reproduce issue:**

import io.netty.util.AsciiString;

public class Test {
	private static final String CONTENT_LENGTH = "Content-Length";
	
	public static void main(String[] args) {
		System.out.println("Java String:       hash=#" + AsciiString.hashCode(CONTENT_LENGTH));
		System.out.println("Netty AsciiString: hash=#" + AsciiString.hashCode(new AsciiString(CONTENT_LENGTH)));
	}
}

**Test Results:**

Windows:
Java String:        hash=#-142559256
Netty AsciiString:  hash=#-142559256

AIX 6.1:
String hash=#2100908492
Ascii  hash=#193356951

Solaris 5.11
String hash=#2100908492
Ascii  hash=#193356951

### Netty version
4.1.6

**Comment by normanmaurer** [comment]
@IgorAlelekov  this was fixed in 4.1 branch and will be part of 4.1.7.Final release.
