### ISSUE TITLE
Wrong regular expression to check MACAdresses in DefaultChannelId

### ISSUE THREAD

**Issue by jo-kin** [netty/netty#6132]
Using Netty on a Java-VM running on IBM z/OS it occurs, that creating a unique channel-id leads to problems.
It seems to me, that this process bases at least on the MAC-Address of networking hardware.  On IBM z/OS this information is not available with the usual JAVA-methods in NetworkInterface.  Netty logs always a warning to System.err running on z/OS that it fell back to a random MAC.
So I decided to use the VM-Option io.netty.machineId=xxxxxxxx to inject here a valid MAC-Address retrieved from non-java resources on z/OS.

**To my regrets it does not work. The problem is not platform-dependent, even with in a SUN-VM running on Windows it is not possible to use this option.** 

Probably the Regular Expression, used to check the input, is not correct.
I would recommend to change the used RegExp 
` private static final Pattern MACHINE_ID_PATTERN = Pattern.compile("^(?:[0-9a-fA-F][:-]?){6,8}$");`
to an expression more like 
`([0-9a-fA-F]{2}[:-]){5,7}[0-9a-fA-F]{2}`

### Expected behavior
DefaultChannelId allows to customize the used MACAddress via System.property.
Using -Dio.netty.machineId=00-14-5E-5A-AF-77 as Java-VM-option should be accepted as valid MACAddress.

### Actual behavior
Netty rejects this MACAddress as malformed:

`Dez 14, 2016 2:10:49 PM io.netty.channel.DefaultChannelId <clinit>
WARNING: -Dio.netty.machineId: 00-14-5E-5A-AF-77 (malformed)
Dez 14, 2016 2:10:49 PM io.netty.handler.logging.LoggingHandler channelRegistered
INFO: [id: 0xa9354b7b] REGISTERED
Dez 14, 2016 2:10:49 PM io.netty.handler.logging.LoggingHandler bind
INFO: [id: 0xa9354b7b] BIND: 0.0.0.0/0.0.0.0:8007
Dez 14, 2016 2:10:49 PM io.netty.handler.logging.LoggingHandler channelActive
INFO: [id: 0xa9354b7b, L:/0:0:0:0:0:0:0:0:8007] ACTIVE`

### Steps to reproduce
Start any Netty-using application (i.e. your sample io.netty.example.echo.EchoServer) with VM-option -Dio.netty.machineId=xxxxxxxx to overrule the standard MAC-Address ascertaining in MacAddressUtil.bestAvailableMac(), where xxxxxxx is any MAC-Address in standard (IEEE 802) format for printing MAC-48 addresses in human-friendly form.

### Minimal yet complete reproducer code (or URL to code)
see above. Reproducible via VM-option

### Netty version
4.1.5

### JVM version (e.g. `java -version`)
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

### OS version (e.g. `uname -a`)
Windows 7 Professional Service Pack 1

**Comment by Scottmitch** [comment]
@jo-kin - Thanks for reporting. Stand by for a PR.

**Comment by jo-kin** [comment]
Thanx a lot.
Deeply impressed by speed and thoroughness. Will report how it works for me soon.
Wishing you a very Happy Christmas and New Year 2017.
