### ISSUE TITLE
netty framework only support the following 4 http post

### ISSUE THREAD

**Issue by wangqianfront** [netty/netty#6143]
### netty version: 4.1

![default](https://cloud.githubusercontent.com/assets/692238/21306811/d12c5f8c-c60d-11e6-95f5-5b8817f3092b.png)

**Comment by normanmaurer** [comment]
@wangqianfront as @fredericBregier noted we could most likely change this to only "throw" if the method is `HEAD`. Interested in providing a PR ?

**Comment by normanmaurer** [comment]
actually this is a duplicate of #6138
