### ISSUE TITLE
Calls to discardSomeReadBytes() causes the JsonDecoder to get corrupted.

### ISSUE THREAD

**Issue by andrewmccall** [netty/netty#6156]
### Expected behavior
JsonDecoder should keep reading bytes even if the call to discardSomeReadBytes() is made.

### Actual behavior
JsonDecoder internal idx value is not reset, so the reader can no longer read bytes.

### Steps to reproduce
Send lots of data to a connection with a JsonDecoder, when a call to discardSomeReadBytes() is made the readerIndex will be reset. The internal idx of the JsonDecoder won't be reset so the decoder won't be able to read anymore bytes.

### Minimal yet complete reproducer code (or URL to code)
N/A

### Netty version
4.1

### JVM version (e.g. `java -version`)
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

### OS version (e.g. `uname -a`)
Darwin Andrews-MBP 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
@andrewmccall may want to contribute a PR with a fix ?

**Comment by andrewmccall** [comment]
Needed the issue before I could create one. :)

**Comment by normanmaurer** [comment]
@andrewmccall actually you can even create a PR without  creating an issue first ;)

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6157
