### ISSUE TITLE
OpenSslEngine doesn't respond to close_notify

### ISSUE THREAD

**Issue by markdascher** [netty/netty#6167]
### Expected behavior

When a Netty server receives a TLS close_notify, it should respond with a close_notify.

### Actual behavior

Netty's [OpenSslEngine](https://github.com/netty/netty/blob/netty-4.1.6.Final/handler/src/main/java/io/netty/handler/ssl/OpenSslEngine.java) (actually [ReferenceCountedOpenSslEngine](https://github.com/netty/netty/blob/netty-4.1.6.Final/handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java)) never sends the close_notify response.  When a close_notify comes in, it's processed inside of [unwrap()](https://github.com/netty/netty/blob/netty-4.1.6.Final/handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java#L699), eventually reaching this [closeAll()](https://github.com/netty/netty/blob/netty-4.1.6.Final/handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java#L845) call on line 845.  Then, [closeInbound()](https://github.com/netty/netty/blob/netty-4.1.6.Final/handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java#L1007) calls [shutdown()](https://github.com/netty/netty/blob/netty-4.1.6.Final/handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java#L359), which deallocates the OpenSSL data structures, before we have a chance for netty to grab the data.

The native Java [SSLEngine](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLEngine.html) works fine.  This [unwrap()](https://github.com/netty/netty/blob/netty-4.1.6.Final/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L968)
 call returns an SSLEngineResult where `status == CLOSED`, `handshakeStatus == NEED_WRAP`. As a result, [wrapNonAppData(ctx, true)](https://github.com/netty/netty/blob/netty-4.1.6.Final/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L1005) sets [needsFlush = true](https://github.com/netty/netty/blob/netty-4.1.6.Final/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L609), which lets netty know to flush the close_notify out to the network.

### Steps to reproduce

* In terminal window 1, run a tcpdump to monitor TLS traffic: `sudo tcpdump -lilo0 port 8992 | fgrep -v 'length 0'`
* In terminal window 2, build the Secure Chat example, and run with `netty-tcnative-boringssl-static-1.1.33.Fork25.jar` in the CLASSPATH.  Test from terminal window 3: `openssl s_client -connect 127.0.0.1:8992 -tls1`.  Send a couple test messages, and then close the TLS connection by entering `Q` on a line by itself.  The tcpdump shows a close_notify sent from the client, but nothing coming back from the server.  This shows that close_notify goes unanswered when using OpenSSL.  Terminate the server.
* In terminal window 2, build the Secure Chat example, but run without `netty-tcnative-boringssl-static-1.1.33.Fork25.jar` in the CLASSPATH.  Test from terminal window 3: `openssl s_client -connect 127.0.0.1:8992 -tls1`.  Send a couple test messages, and then close the TLS connection by entering `Q` on a line by itself.  The tcpdump shows a close_notify sent from the client, and a response sent from the server.  This shows that close_notify works properly when using the native JDK implementation.  Terminate the server.

### Minimal yet complete reproducer code
Secure Chat example from netty-4.1.6.Final:
[SecureChatServer.java](https://github.com/netty/netty/blob/netty-4.1.6.Final/example/src/main/java/io/netty/example/securechat/SecureChatServer.java)
[SecureChatServerHandler.java](https://github.com/netty/netty/blob/netty-4.1.6.Final/example/src/main/java/io/netty/example/securechat/SecureChatServerHandler.java)
[SecureChatServerInitializer.java](https://github.com/netty/netty/blob/netty-4.1.6.Final/example/src/main/java/io/netty/example/securechat/SecureChatServerInitializer.java)

### Netty version

[netty-all-4.1.6.Final.jar](https://repo1.maven.org/maven2/io/netty/netty-all/4.1.6.Final/netty-all-4.1.6.Final.jar)
[netty-tcnative-boringssl-static-1.1.33.Fork25.jar](https://repo1.maven.org/maven2/io/netty/netty-tcnative-boringssl-static/1.1.33.Fork25/netty-tcnative-boringssl-static-1.1.33.Fork25.jar)

### JVM version

```
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
```

### OS version

Mac OS X El Capitan v10.11.6 with latest updates

**Comment by normanmaurer** [comment]
@markdascher I think this is fixed in 4.1.7.Final-SNAPSHOT (current 4.1 branch). Can you please test and let us know ?

**Comment by markdascher** [comment]
Wow, wasn't expecting an answer so fast.  👍

I just downloaded [netty-all-4.1.7.Final-20161230.120821-77.jar](https://oss.sonatype.org/content/repositories/snapshots/io/netty/netty-all/4.1.7.Final-SNAPSHOT/netty-all-4.1.7.Final-20161230.120821-77.jar), but the behavior is the same.

**Comment by normanmaurer** [comment]
Ok thx will have a look

**Comment by Scottmitch** [comment]
thanks for the detailed issue description @markdascher! seems reasonable to me and very helpful.

**Comment by markdascher** [comment]
Yay!

The best workaround I've found, for the moment, is to add a listener to `SslHandler.sslCloseFuture()` to close the TCP connection immediately.  For example, replace [line 47](https://github.com/netty/netty/blob/netty-4.1.6.Final/example/src/main/java/io/netty/example/securechat/SecureChatServerInitializer.java#L47) of SecureChatServerInitializer.java with:

```
SslHandler sslHnd = sslCtx.newHandler(ch.alloc());
sslHnd.sslCloseFuture().addListener(
	new GenericFutureListener<Future<Channel>>() {
		@Override
		public void operationComplete(Future<Channel> future) throws Exception {
		if (future.isSuccess()) {
			future.getNow().close();
		}
	}
});
pipeline.addLast(sslHnd);
```

That at least prevents the connection from sitting idle while the client waits for an answer, but it'll still be better to have the close_notify go out first.  I'm pretty new to Netty, so please correct me if there's a better way to do it.  (e.g. Would `.disconnect()` be better than `.close()`?)

**Comment by normanmaurer** [comment]
Looking now...

**Comment by normanmaurer** [comment]
Stay tuned for a PR... I think I know the best way to fix this.

**Comment by normanmaurer** [comment]
@markdascher https://github.com/netty/netty/pull/6189 should fix it... Can you check ?

**Comment by markdascher** [comment]
Looks like that does the trick!  I built netty from the `fix_close_notify` branch, and now see the close_notify whether or not I use `netty-tcnative-boringssl-static-1.1.33.Fork25.jar`.

Thanks!

**Comment by normanmaurer** [comment]
@markdascher boom! Thanks for reporting back :)

**Comment by normanmaurer** [comment]
@markdascher and thanks again for the detailed description how to reproduce it easily. Without this it would have take a lot longer.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6189
