### ISSUE TITLE
Wrong link in documentation

### ISSUE THREAD

**Issue by RevvyDevvyDoo** [netty/netty#6172]
### Expected behavior
Clicking on the link takes me to http://localhost:8080/

### Actual behavior
Clicking on the link takes me to http://localhost:8080/, (Note the comma at the end)

### Steps to reproduce
Click on the link in http://netty.io/4.1/xref/io/netty/example/http/websocketx/server/WebSocketServer.html#34

### Minimal yet complete reproducer code (or URL to code)
Irrelevant

### Netty version 
4.1.6 final

### JVM version (e.g. `java -version`)
Irrelevant

### OS version (e.g. `uname -a`)
Irrelevant

**Comment by normanmaurer** [comment]
Let me fix it

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6190
