### ISSUE TITLE
Request for 4.1.7 release?

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty#6174]
It seems netty has not had a point release for several months now.  Would it be possible to make a point release soonish in order to take advantage of all the commits that have happened since 4.1.6 ?

**Comment by normanmaurer** [comment]
Next week once I am back from vacation 🎉👍

**Comment by jasontedor** [comment]
Is this going to materialize? We are impacted by https://github.com/netty/netty/commit/ee63d01cb15b0d3b29edf1b7345b52e225adc781.

**Comment by Scottmitch** [comment]
The plan is still to release this week. @normanmaurer is back and itching to pull the release trigger ... just trying to do some validation and make sure everything is in good order.

**Comment by normanmaurer** [comment]
Yes! Today or tomorrow latest

**Comment by jasontedor** [comment]
Thank you @normanmaurer.
