### ISSUE TITLE
HttpObjectDecoder discards trailer headers in chunked mode

### ISSUE THREAD

**Issue by adrian-w-liu** [netty/netty#6176]
### Expected behavior
Suppose the last http content is as bellows:
Foo-Header: foo/r/n/r/n
And as TCP is a stream protocol, netty receives two ByteBuf object:
Foo-Header: foo/r/n and /r/n
In this case, netty shouldl return a DefaultLastHttpContent with the header in the content.

### Actual behavior
In this case, netty returns an empty last content.
I read the code and think that netty should return the trailer stored in HttpObjectDecoder if it is not null before trying to return empty last content.

### Netty version
I'm using 4.1.0.Beta8.  I also checked the latest code, and I believe the bug is still there.

**Comment by normanmaurer** [comment]
Let me check

**Comment by normanmaurer** [comment]
@adrian-w-liu actually I think it will never have anything stored in `trailer` when it uses an empty last content. Can you share a reproducer or unit test ?

**Comment by normanmaurer** [comment]
@adrian-w-liu I think it works as epected. If you still thing there is a bug please reopen with a reproducer / testcase.
