### ISSUE TITLE
Comment error

### ISSUE THREAD

**Issue by wangyuntao** [netty/netty#6177]
[AbstractChannelHandlerContext.invokeHandler](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java#L981)'s comment perhaps should be: "If this method returns {@code **_FALSE_**} we will not..." ?

**Comment by normanmaurer** [comment]
@wangyuntao yes... let me fix this.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6188
