### ISSUE TITLE
PortUnreachableExceptions thrown without detail message

### ISSUE THREAD

**Issue by InfoSec812** [netty/netty#6179]
### Expected behavior
When a PortUnreachableException is thrown, calling exception.getLocalizedMessage() should return a non-null String.

### Actual behavior

PortUnreachableException has an available empty constructor which is being used by the underlying Netty library... Here's the call stack which leads to the Exception being created:

```
"vert.x-eventloop-thread-1@1858" prio=5 tid=0x14 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.net.PortUnreachableException.<init>(PortUnreachableException.java:51)
	  at sun.nio.ch.DatagramChannelImpl.receive0(DatagramChannelImpl.java:-1)
	  at sun.nio.ch.DatagramChannelImpl.receiveIntoNativeBuffer(DatagramChannelImpl.java:414)
	  at sun.nio.ch.DatagramChannelImpl.receive(DatagramChannelImpl.java:392)
	  at sun.nio.ch.DatagramChannelImpl.receive(DatagramChannelImpl.java:345)
	  - locked <0x868> (a java.lang.Object)
	  at io.netty.channel.socket.nio.NioDatagramChannel.doReadMessages(NioDatagramChannel.java:248)
	  at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75)
	  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610)
	  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551)
	  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465)
	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	  at java.lang.Thread.run(Thread.java:745)
```

So, this appears to be a JDK or a Netty problem, not a Vert.x problem.

### Steps to reproduce

Attempt a UDP socket send to a non-existent service.

### Minimal yet complete reproducer code (or URL to code)

I did this in Vert.x, so here is that code in Groovy:

```groovy
vertx.createDnsClient(8053, '127.0.0.1').lookup('www.google.com', { res ->
    if (res.succeeded()) {
        LOG.info('SUCCESS')
    } else {
        LOG.error('FAILURE')
        LOG.error(res.cause().getLocalizedMessage()) // Returns NULL
    }
})
```

### Netty version

4.1.5

### JVM version (e.g. `java -version`)

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

### OS version (e.g. `uname -a`)
Several
* Darwin Kernel Version 15.6.0: Wed Nov  2 20:30:56 PDT 2016; root:xnu-3248.60.11.1.2~2/RELEASE_X86_64 x86_64
* Linux ideapad 4.8.0-32-generic #34-Ubuntu SMP Tue Dec 13 14:30:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* Windows 7 Professional

**Comment by normanmaurer** [comment]
@InfoSec812 this is thrown by the JDK impl itself so not much we can do here

**Comment by InfoSec812** [comment]
That's unfortunate! What about catch8ng and rethrowing?

Deven

**Comment by normanmaurer** [comment]
Yep that is a good idea.. let me do this

**Comment by InfoSec812** [comment]
Awesome! Thanks!

**Comment by InfoSec812** [comment]
The Vert.x project is also tracking this as https://github.com/eclipse/vert.x/issues/1755

**Comment by normanmaurer** [comment]
@InfoSec812 one question.. what you would link to have in the exception message ?

**Comment by InfoSec812** [comment]
Received Port Unreachable when attempting to send to <socket addr>?

Something like that.

And thanks again!

Deven

**Comment by Scottmitch** [comment]
Can't the rethrowing be done at a higher level? I just wonder if this will be useful for all use cases, or maybe some won't care about the message ... or can derive their own if necessary? Maybe not a big deal but just want to make sure the extra object allocation / wrapping is more generally useful.

**Comment by InfoSec812** [comment]
I would suggest that the error should be useful at the lowest level
possible so the all downstream users benefit. Also, adding the message will
not break existing implementations which currently handle the value being
null.

Deven

**Comment by normanmaurer** [comment]
@Scottmitch I think it make sense to add it to netty as its basically the same as we do with out "ConnectException" stuff. I will also do an openjdk patch so we may get it fixed in openjdk at some point  tho 👍

**Comment by InfoSec812** [comment]
Woot! Thanks all!

**Comment by normanmaurer** [comment]
At the end we decided we dont want to catch and rethrow.
