### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by wangyuntao** [netty/netty#6185]
[DefaultEventExecutorChooserFactory.PowerOf**Tow**EventExecutorChooser](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/concurrent/DefaultEventExecutorChooserFactory.java#L46)

Should be PowerOf**Two** ?

**Comment by normanmaurer** [comment]
yep... fixing

**Comment by normanmaurer** [comment]
@wangyuntao fixed by https://github.com/netty/netty/pull/6191

**Comment by wangyuntao** [comment]
OK!

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6191
