### ISSUE TITLE
Add some warn log about unknown channel option?

### ISSUE THREAD

**Issue by wangyuntao** [netty/netty#6192]
Should add some WARN log [at this point](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/DefaultChannelConfig.java#L109) ? like [this one](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/bootstrap/ServerBootstrap.java#L242) ?

**Comment by normanmaurer** [comment]
@wangyuntao we warn in `ServerBootstrap` and `Bootstrap`. The rest is up to the user when the methods return false.

**Comment by wangyuntao** [comment]
@normanmaurer , I checked the code and found that [Bootstrap](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/bootstrap/Bootstrap.java#L272) has warn logs, but [ServerBootstrap](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/bootstrap/ServerBootstrap.java#L144) does't.

**Comment by normanmaurer** [comment]
@wangyuntao ups... let me fix this then.

**Comment by normanmaurer** [comment]
Should be fixed by https://github.com/netty/netty/pull/6235

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6235
