### ISSUE TITLE
use ssl protocol send file  failed

### ISSUE THREAD

**Issue by mrsWangxing** [netty/netty#6202]
I write 2 demo test netty ssl.
The first demo, I didn't use the SSL protocol.The second demo I use the SSL protocol.
this is the client code.Send the file to the server

This is my handler:
```
 public void channelActive(ChannelHandlerContext ctx) throws Exception {
        //Globle.channel = ctx;
    	//Thread.sleep(10000);                                (1)
    	System.out.println(ctx.channel().toString());
        System.out.println(ctx.channel().localAddress() + "channelActive"+'-'+ new Date());
        System.out.println("start" + new Date());
        String fileUrl = "C:/work/setup/ubuntu-14.04.4-desktop-amd64.iso";
        FileControl fileControl = new FileControl(ctx);
        fileControl.sendNotice();
        fileControl.sendFile(fileUrl);
        System.out.println("end" + new Date());
    }
```
```
public void sendFile(String fileUrl) {
        // 开始执行
        RandomAccessFile raf = null;
        try {
            raf = new RandomAccessFile(fileUrl, "rw");
            ChunkedFile chunkedFile = new ChunkedFile(raf);
            channel.writeAndFlush(chunkedFile).addListener(new ChannelFutureListener() {
                @Override
                public void operationComplete(ChannelFuture future) throws Exception {
                    future.channel().close();
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```
When I use the SSL protocol ,I found that sending a large file to server.The server receives the file handler will only trigger channelActive and channelInactive without triggering channelRead events
If I send a small file，it is OK. 
But If (1) location using 10 seconds delay, send a small file will fail

### Netty version
netty-all-5.0.0.Alpha1.jar
### JVM version (e.g. `java -version`)
jdk1.7.0_67

**Comment by Scottmitch** [comment]
netty 5.0 is not supported. please use netty 4.1 and report back with any updates.

**Comment by mrsWangxing** [comment]
Yse , You are right. I use  netty-all-4.1.6.Final.jar  can upload large file。but I find that the file is not  incomplete， missing 8 KB。I try to upload small file also miss 8Kb。if I do not  use the SSL protocol, there is no this problem。

**Comment by mrsWangxing** [comment]
https://github.com/mrsWangxing/netty-ssl-send-large-file/tree/master   is my test demo

**Comment by Scottmitch** [comment]
I don't have time to dig into this code at the moment. If you could reduce it to a Netty unit test that would be very helpful.

**Comment by mrsWangxing** [comment]
ok ,I close this issues。

**Comment by mrsWangxing** [comment]
I tested several times. If I send a 8 KB TXT file,the server  will receive is an empty file .
I also  find that the first 8Kb bytes will send failure. 
I hope you will have time to determine if this is the program I wrote problem or a problem with netty

**Comment by mrsWangxing** [comment]
Thank you!

**Comment by johnou** [comment]
@mrsWangxing is it still an issue with 4.1.7?

**Comment by mrsWangxing** [comment]
@johnou yes

**Comment by mrsWangxing** [comment]
If you have time,  you can look at my demo. thanks.
https://github.com/mrsWangxing/netty-ssl-send-large-file/tree/master is my test demo

**Comment by Scottmitch** [comment]
If you still believe this is a Netty issue then lets leave it open. Have you narrowed down the problem to be on the client or the server via tcpdump or Wireshark?

**Comment by mrsWangxing** [comment]
192.168.0.102  is client,192.168.0.101 is server .I use wireshark to monitor their card respectively.Their monitoring data are the same.I do not know much about network knowledge, I don't know whether it can determine the netty issue.
![server11](https://cloud.githubusercontent.com/assets/8254733/21955857/8f4fd188-daae-11e6-89f2-69260e482409.png)

**Comment by slandelle** [comment]
I suspect that you're not sending a LastHttpContent after your ChunkedFile, so your payload is not terminated.

```java
channel.write(chunkedFile);
channel.writeAndFlush(LastHttpContent.EMPTY_LAST_CONTENT)
             .addListener(ChannelFutureListener.CLOSE);
```

@normanmaurer WDYT?

**Comment by mrsWangxing** [comment]
Until now I also didn't find the real reason。Later, I changed a kind of writing, it can work normally,I do not know why.My guess is that the original writing  can not work well in netty4 environment.
