### ISSUE TITLE
Investigate performance of Base64

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#6205]
`Base64.encode(...)` / `Base64.decode(...)` is quite slow as it acts on byte-level. We may want to look into optimise this.

See also:
https://github.com/netty/netty/pull/6145#issuecomment-271899281

**Comment by Scottmitch** [comment]
thanks for reporting!

**Comment by normanmaurer** [comment]
This can be closed as these are now merged: 

#6433
#6404
