### ISSUE TITLE
HTTP/2 RFC compliance for stream state involving "Priority Only Streams" 

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#6206]
### Expected behavior

https://tools.ietf.org/html/rfc7540#section-5.1.1
> The first use of a new stream identifier implicitly closes all
   streams in the "idle" state that might have been initiated by that
   peer with a lower-valued stream identifier.

Streams which are in IDLE but have had frames exchanged (e.g. PRIORITY frames) should be transitioned to CLOSED when a frame with a numerically higher stream ID is used (for the respective endpoint).

Care must be taken into how these "priority only streams" (stream which only have PRIORITY frames exchanged) are treated with respect to the dependency tree. We should have some capacity to retain CLOSED streams in the dependency tree to accommodate cases like "priority only streams". Note we previously did retain CLOSED streams in the priority tree but this was removed in https://github.com/netty/netty/commit/d580245afc77f11e4b82a7f3320f5619b555c2ec.

At one point there was a desire to use the SETTINGS frame to inform the heuristic algorithm to discard "priority only streams" in closed from the dependency tree. However it is not clear this is beneficial and if not the [Http2Connection$Endpoint#maxStreams](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2Connection.java#L281) related APIs should be revisited.

### Actual behavior
We leave "priority only streams" in idle even if numerically higher stream IDs are in use. This is not RFC compliant and may lead to an inconsistent view in stream state with our peers.

### Netty version
[4.1.0, 4.1.7-SNAPSHOT]

**Comment by Scottmitch** [comment]
@nmittler - FYI. IIRC we have discussed this in the past, but it fell off my radar for a while. I want to make sure I track it here so it isn't lost. We should address this for the 4.1.8 release.

**Comment by Scottmitch** [comment]
A case such as the following should result in an error (stream ID 3 is closed when the headers are sent)

```
1. Client [Priority, id: 3] -> Server
2. Client [Headers, id: 5] -> Server
3. Client [Headers, id: 3] -> Server
```

**Comment by nmittler** [comment]
@Scottmitch sgtm.  Did you have a PR for this that you were working on?

**Comment by Scottmitch** [comment]
@nmittler - I haven't started yet no, but I can fit it into my schedule in the next couple weeks ... unless you are volunteering to do it sooner :)

**Comment by nmittler** [comment]
@Scottmitch the general approach sgtm. I suspect we'll need to add information to the nodes to speed up the processing (e.g. option 2).

**Comment by chhsiao90** [comment]
Hi @Scottmitch ,

I just find this interesting issue and want to provide my opinion related to this!
I had some similar issue recently and had seen discussion about this at some http2 implementation.
related issue https://github.com/h2o/h2o/pull/1136

In https://tools.ietf.org/html/rfc7540#section-5.1.1 that there is another paragraph said
> The identifier of a newly established stream MUST be numerically greater than all streams that the initiating endpoint has opened or reserved. This governs streams that are opened using a HEADERS frame and streams that are reserved using PUSH_PROMISE. An endpoint that receives an unexpected stream identifier MUST respond with a connection error of type PROTOCOL_ERROR

So I preferred the conclusion ```priority frame won't increase that minimum stream id```
And it will result with
```Priority[id = 3] => Header[id = 1] (Accept)```
```Header[id = 3] => Header[id = 1] (Not accept)```

**Comment by Scottmitch** [comment]
@chhsiao90 - Can you use the same format as in https://github.com/netty/netty/issues/6206#issuecomment-272024705 so it is clear the order of frames and which endpoint is sending/receiving?

**Comment by Scottmitch** [comment]
@chhsiao90 - The issue you reference seems to be unrelated. 

> PRIORITY frames can be sent for idle streams, and shouldn't affect the
number of open streams.

This issue is not about accounting for the number of open streams. I believe we already do this correctly.

> Not doing so resulted in the server closing the connection with a
PROTOCOL_ERROR when a PRIORITY frame for stream id 3 was followed by
a HEADER frame for stream id 1.

We don't have this issue.

**Comment by chhsiao90** [comment]
@Scottmitch ,

I start netty http2-server from example and run h2spec with https://github.com/summerwind/h2spec/pull/67
And got the result
```
6.3. PRIORITY
  × Sends a PRIORITY frame for an idle stream, then send a HEADER frame for a lower stream id
    - The endpoint MUST respond to the HEADER request with no connection error.
        Actual: RST_STREAM frame (Length: 4, Flags: 0, ErrorCode: STREAM_CLOSED)
```

The example with format
```
1. Client [Priority, id: 3] -> Server
2. Client [Headers, id: 1] -> Server
```
That h2spec expected it's a passed case, but it seems that netty would failed the test.

My idea is that [DefaultHttp2ConnectionDecoder](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L331) increase stream id accidentally.

Or maybe my comment that is unrelated to this issue!
I just seen ```Priority Only Streams``` in issue title, and thought that it's related to.

**Comment by Scottmitch** [comment]
@chhsiao90 - Interesting. This actually seems like it violates the RFC. I commented on the PR to discuss in more detail.

**Comment by chhsiao90** [comment]
That the rfc seems not defined it very clearly, different people would have different explanation. :)
