### ISSUE TITLE
unresolve dependency

### ISSUE THREAD

**Issue by Lomad** [netty/netty#6211]
### JVM version 1.7

this is my os version  :A 64 bit operating system, based on x64 processor

error: netty/example unresolve dependency : io.netty:netty-tcactive:windows-x86_32:1.1.33.Fork25

because of my os?   I think this is not reasonable...

**Comment by Lomad** [comment]
another error which appers in handler/ssl /ReferenceCountedOpenSslClientContext.java , all about "import org.apache.tomcat.jni.*  cannot resolve symbol

**Comment by johnou** [comment]
There is no 32 bit tcnative in Maven, check you are running 64-bit Java and OS.

**Comment by Lomad** [comment]
ok,thanks.please check the comment which I submit before,it's the another error I have no idea about

**Comment by Lomad** [comment]
@johnou    
ok,thanks.please check the comment which I submit before,it's the another error I have no idea about

**Comment by johnou** [comment]
Both errors are because Maven is trying to resolve 32 bit tcnative artifact which doesn't exist in central Maven.

**Comment by Lomad** [comment]
@johnou
Got it. So thanks!
