### ISSUE TITLE
Slf4jLoggerFactory masks all output when using slf4j-simple

### ISSUE THREAD

**Issue by johnrengelman** [netty/netty#6212]
### Expected behavior
Normal logging occurs to the console when using slf4j-simple

### Actual behavior
Output is hidden.

### Steps to reproduce
Initialize the Slf4jLoggerFactory before any Slf4jLogger (.e.g SimpleLogger)

### Netty version
4.1.5.FINAL

### JVM version (e.g. `java -version`)
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

### OS version (e.g. `uname -a`)
Darwin <hostname> 14.5.0 Darwin Kernel Version 14.5.0: Mon Jan 11 18:48:35 PST 2016; root:xnu-2782.50.2~1/RELEASE_X86_64 x86_64

Found this when working Ratpack. We moved some code around such that `ResourceLeakDetector.setLevel(ResourceLeakDetector.Level.DISABLED);` was called prior to any Sl4fj logger being instantiated in a `static` context.

This cause `Slf4jLoggerFactory` to replace `System.err` with it's own implementation which caused slf4j (with the slf4j-simple binding) to pick it up and use it for it's loggers. The implementation in `Slf4jLoggerFactory` never outputs to the original `System.err`. It simply appends all data to a `StringBuffer`.

https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/logging/Slf4JLoggerFactory.java#L52

Notice that the buffer is only flushed at instantiation here: https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/logging/Slf4JLoggerFactory.java#L63

**Comment by normanmaurer** [comment]
@johnrengelman let me check...

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6240
