### ISSUE TITLE
HTTP2 Encoder Failure on encode of oversized headers corrupts dynamic table consistency

### ISSUE THREAD

**Issue by exell-christopher** [netty/netty#6213]
### Problem Description
When the HTTP/2 encoder fails to encode headers due to headers that exceed the MAX_HEADER_LIST_SIZE during an encode where new headers are added, the dynamic on the sending side is updated, but the dynamic table on the receiving side is not. This can cause subsequent encodes of headers that already exist in the dynamic table to map to an incorrect index on the receiving side, in a production environment this can cause headers from one request/response to end up on another.

This bug is closely related to #6209 

### Expected behavior
When oversized headers are encoded a GO_AWAY with an INTERNAL_ERROR should be sent to prevent the connection from becoming corrupted. Additionally, the failure to encode should be returned to the promise that represents the encode, right now this appears to fail silently.

### Steps to reproduce
See attached maven project zip

### Netty version
4.1.6, 4.1.7

[netty-debug.zip](https://github.com/netty/netty/files/705828/netty-debug.zip)

**Comment by exell-christopher** [comment]
@Scottmitch You may already be looking at this with #6209. I'm opening another bug to track this issue. Let me know if you need additional info, the test case is a bit convoluted, but demonstrates the issue.

**Comment by exell-christopher** [comment]
One other thing worth noting. With the current behavior, if headers fail to encode, but the request/response has headers and data, the headers won't send, but the data frame will. Likely sending a GO_AWAY will prevent this.

**Comment by Scottmitch** [comment]
@exell-christopher thanks for reporting. I actually already fixed this as part of the fix for PR https://github.com/netty/netty/issues/6209 and added a unit test.

**Comment by Scottmitch** [comment]
@exell-christopher - I will close this now. Please re-open if this is not completely fixed.
