### ISSUE TITLE
Clarification requested: Netty 4.0 vs 4.1

### ISSUE THREAD

**Issue by rschmitt** [netty/netty#6217]
A [SO answer](http://stackoverflow.com/a/30477520) from a few years ago states the following:

> 4.0 is the current stable version. When in doubt, use this version.
>
> 4.1 is a backward compatible version of 4.0. It adds some cool new features like HTTP/2 and asynchronous DNS resolver. So, 4.1 is the version you might want to try when your application already runs on top of 4.0 and you wanna try the new features.

Is this generally correct? Is it accurate to describe Netty 4.1 as a generally experimental branch, and Netty 4.0 as the "default" major version?

**Comment by Scottmitch** [comment]
4.1 is considered stable and mostly conforms to 4.0 APIs while adding some features and improvements in some areas. If you are starting a new project you should use 4.1. If your project has been using 4.0 with no issues and you don't need any new features from 4.1 then stick with 4.0.
