### ISSUE TITLE
Client initiated renegotiation supported when using OpenSSL?

### ISSUE THREAD

**Issue by jplock** [netty/netty#6223]
### Expected behavior

Renegotiation is supported

### Actual behavior

```
CONNECTED(00000003)
depth=1 CN = ca
verify return:1
depth=0 CN = localhost
verify return:1
---
Certificate chain
 0 s:/CN=localhost
   i:/CN=ca
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDlTCCAX0CAQEwDQYJKoZIhvcNAQELBQAwDTELMAkGA1UEAxMCY2EwHhcNMTYx
MjMwMjIwOTUwWhcNMTcxMjMwMjIwOTUwWjAUMRIwEAYDVQQDEwlsb2NhbGhvc3Qw
ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDBshWIvTNrWeMLb84adWI5
pjaR209EuOlHZyxi7XfgVjyZ6Y9sDFPlEycWN2zS/9t+QNiqLfxbr2VglmKrflHB
IE10YH/IbvhFcm5xlb/gKSqUTw+5Y8570n361D6ct5QZf7B3XVpLLnsf9WuQLitD
A61PPRGpjd8bd5RmGyTogZmMlnN69asRR7ds/seYQM3kEMCimFtefyXundkPygMh
qlT9MAiWGFeU/7oWUpOBcD/gx0NQ/8vC58LBQshVSDNMiTXzVCL5zCZN6mAQSkip
Wkoq6YDVb4lwP4uY1iz+Ca54zvpfsZtd+nJCbeR5rLUHyYGbWdGk0Ql0MqLvgaJ1
AgMBAAEwDQYJKoZIhvcNAQELBQADggIBABe1e3nD0yN/Pf+piPp9ap2fH5AajQ7Z
DvfJCAl1GCCgEYm58Rj9X5NgYyG/F53PGa4y7JAAn4IcKvEwbkdx/slRpGwg6WKG
0ulEFpr80rzYjSbayfYiciNm+/3UPjdynTHtwwWtthdmCOr9vva3ugLnvSTrHD8A
T1BHRlJftRCL7u8n/DsRHqmJ/LYkfr2dfe39fBjgxNa6Er1+HtApbX1aqLeemGN1
dq+JPk6jEw5+XzYlVcfxMCbKw62w5+9N1omx3ZPEFZpJ3Dvc4VBc5eZg+hL73VN4
dTMat64Srf0/291Na0ODGalh8bPYkkSmAvFXoyLfw36y1pELqm+nIyiyv6R7sXCy
QO1AXKtjnIIst58XxPECm9q4PIhSVD0CUKUz5jr0LRQejkRCVcH3Ly4khpfKzWEd
7ZQJ5p110dMg/cOpH/VIM36/Uzu973UNP2bl0UxLDbXMeNAyZEhJKaQmy6qavKrm
PZqmnzn0fyzK5fprUTaj+xPTC0tFiuKqZ7DM7K4g16GsVGo6+W4nUCXLqbGV88F+
tkTrSCQD8EMAQsutMVnrlpjeeI2xmzWagWVBGhS3Sh/U+clMCjNzuBxuN7qKj2Xc
HFexCGsR1EpSQsZ+D3b8RtheUemKRnaHFcbg4TAR/TWBSqmhoTlXJMOLQ4IlrKX1
isktyFUSlQ8e
-----END CERTIFICATE-----
subject=/CN=localhost
issuer=/CN=ca
---
Acceptable client certificate CA names
/CN=ca
---
SSL handshake has read 1475 bytes and written 2922 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: CBBE4796278BEE996B1C7CE55E7AF2DEBBDD399BBD18CE6AE9E1849264F55594
    Session-ID-ctx: 
    Master-Key: DAC63D8CD9AD2E20430032DDDDA26B9FDA321F33C433FC773ECE065AB78C5F14FC82F59DD9F1DBF0B073DD30A0FEB87F
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1484595604
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
R
RENEGOTIATING
140737471710880:error:1409444C:SSL routines:SSL3_READ_BYTES:tlsv1 alert no renegotiation:s3_pkt.c:1263:SSL alert number 100
140737471710880:error:1409E0E5:SSL routines:SSL3_WRITE_BYTES:ssl handshake failure:s3_pkt.c:599:
```

The server is advertising that renegotiation is supported `Secure Renegotiation IS supported` but when using `netty-tcnative-boringssl-static`, `openssl s_client` is returning an error when triggering renegotiation.

If I remove the boringssl-static dependency and fall back on the JDK, it works fine.

I noticed in https://github.com/netty/netty/issues/5859 that the server is advertising that renegotiation is not supported.  Is that an option to resolve this? https://github.com/netty/netty/issues/4407 sounds similar as well.

### Steps to reproduce

1. Launch a Netty instance with SSL mutual authentication enabled.
2. Connect to the instance using the OpenSSL client (`openssl s_client -connect 127.0.0.1:4433 -cert client1.crt -key client1.key -CAfile ca.crt "$@"`)
3. type 'R' to trigger renegotiation

### Minimal yet complete reproducer code (or URL to code)

https://github.com/smoketurner/uploader

### Netty version

4.1.7.FINAL

### JVM version (e.g. `java -version`)

```
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)
```

### OS version (e.g. `uname -a`)

```
Darwin mymachine.local 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
```

**Comment by normanmaurer** [comment]
@jplock as far as I know boringssl does not support renegation by default and so we not support it when using netty-tcnative-boringssl-static. @nmittler @davidben please correct me if I am wrong.

**Comment by Scottmitch** [comment]
IIRC server initiated renegotiation is supported (maybe a compiler flag is necessary) but client initiated renegotiation isn't supported (for boringssl).

FYI renegotiation is removed in TLS 1.3.

**Comment by jplock** [comment]
if it's not supported, should netty respond that it's not available though?

**Comment by normanmaurer** [comment]
@jplock yes...Thats why I included the boringssl people (@davidben @nmittler ) to ensure this is really the case ;)

**Comment by davidben** [comment]
That's right. BoringSSL only implements renegotiation in limited circumstances:
https://boringssl.googlesource.com/boringssl/+/HEAD/PORTING.md#TLS-renegotiation

What the server is advertising is the renegotiation indication extension (RFC 5746). It's not especially relevant for a non-renegotiating server, but is still advertised for features and clients that require servers be patched against the bug.

**Comment by davidben** [comment]
I forget where the thread was, but RI for non-renegotiating servers came up at IETF at some point and the conclusion was it would be simpler to have non-renegotiating servers implement a trivial form of RI rather than complicate every feature to say "RI must be implemented unless renego doesn't end up being used."

**Comment by jplock** [comment]
Thanks for the explanation everyone.  I'm going to close this out for now and try the netty-tcnative version (not boringssl).
