### ISSUE TITLE
Is it necessary to add ServerBootstrapAcceptor handler to the pipeline in a delayed fashion?

### ISSUE THREAD

**Issue by wangyuntao** [netty/netty#6227]
Here is the [souce code](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/bootstrap/ServerBootstrap.java#L182), and the following are the part of it:

```java
p.addLast(new ChannelInitializer<Channel>() {
    @Override
    public void initChannel(Channel ch) throws Exception {
        final ChannelPipeline pipeline = ch.pipeline();
        ChannelHandler handler = config.handler();
        if (handler != null) {
            pipeline.addLast(handler);
        }

        // We add this handler via the EventLoop as the user may have used a ChannelInitializer as handler.
        // In this case the initChannel(...) method will only be called after this method returns. Because
        // of this we need to ensure we add our handler in a delayed fashion so all the users handler are
        // placed in front of the ServerBootstrapAcceptor.
        ch.eventLoop().execute(new Runnable() {
            @Override
            public void run() {
                pipeline.addLast(new ServerBootstrapAcceptor(
                        currentChildGroup, currentChildHandler, currentChildOptions, currentChildAttrs));
            }
        });
    }
});
```
In the above code, the ServerBootstrapAcceptor handler was added to pipeline in a delayed fashion, the reason for this according to the comments  is that "**the user may have used a ChannelInitializer as handler**", but I read the related codes of netty and write some example code, I think this may not be necessary.

**Comment by normanmaurer** [comment]
its necessary as if the user used `ChannelInitializer` it will otherwise mess up the order. Here is the unit test:
https://github.com/netty/netty/commit/4638df20628a8987c8709f0f8e5f3679a914ce1a

**Comment by wangyuntao** [comment]
Hi @normanmaurer , I changed the ServerBootstrap code back to the original one according to that commit, and both tests still passed.

**Comment by wangyuntao** [comment]
@normanmaurer , please check it.
