### ISSUE TITLE
Question about name resolution IPv4 / IPv6 and reachability

### ISSUE THREAD

**Issue by brianatpurestorage** [netty/netty#6255]
I can see that netty does do a resolve all when given a name to resolve. How does it currently decide which address to actually connect to? 

Let's say we have:
root@c14-d38-lp1:~# host yahoo.com
yahoo.com has address 206.190.36.45
yahoo.com has address 98.139.183.24
yahoo.com has address 98.138.253.109
yahoo.com has IPv6 address 2001:4998:c:a06::2:4008
yahoo.com has IPv6 address 2001:4998:58:c02::a9
yahoo.com has IPv6 address 2001:4998:44:204::a7

What will netty connect to:
1. First returned
2. IPv6 preferred?
3. Is there any connectivity check to make sure that the address chosen is reachable?

I guess what I would like to see is given this list of addresses do something like RFC-6555. Then you would know that the address you are trying to reach is reachable. Without doing this, there could be unreachable addresses in this list, particularly in IPv6 where reachability can be problematic. Do you consider this possibility at all?

Thanks,
Brian

**Comment by normanmaurer** [comment]
We basically detect if ipv4 or ipv6 is preferred and decide based on this (just like the JDK does).
