### ISSUE TITLE
Missing log placeholder for "-Dio.netty.allocator.useCacheForAllThreads" (io.netty.buffer.PooledByteBufAllocator)

### ISSUE THREAD

**Issue by isdom** [netty/netty#6265]
netty start log SHOULD output: -Dio.netty.allocator.useCacheForAllThreads true/false

BUT now start log output: -Dio.netty.allocator.useCacheForAllThreads, missing actual value

start any netty server or client with LOG Level : DEBUG

<img width="736" alt="2017-01-23 7 48 12" src="https://cloud.githubusercontent.com/assets/2010691/22202831/f5b4b2d4-e1a4-11e6-85d2-03440380b6f9.png">

netty-all-4.1.7.Final

JDK: java version "1.8.0_102"

OS: Linux XXX 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Now [code](https://github.com/netty/netty/blob/2b8fd8d43be916e29836943fc9d57ec494251756/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java#L130) is:

`logger.debug("-Dio.netty.allocator.useCacheForAllThreads", DEFAULT_USE_CACHE_FOR_ALL_THREADS);
`
Would PooledByteBufAllocator LOG code be better to code like this?

`logger.debug("-Dio.netty.allocator.useCacheForAllThreads: {}", DEFAULT_USE_CACHE_FOR_ALL_THREADS);
`

**Comment by normanmaurer** [comment]
@isdom yes... Want to open a PR to fix it ?

**Comment by jasontedor** [comment]
In Elasticsearch we use a [logger checker](https://github.com/elastic/elasticsearch/blob/d9a3ffcea077b0694275e91e71d2cd9cefea6090/test/logger-usage/src/main/java/org/elasticsearch/test/loggerusage/ESLoggerUsageChecker.java) to ensure that this never happens; we fail the build if the placeholders do not match the arguments.

**Comment by isdom** [comment]
@normanmaurer I fell asleep...  next time I will try open a PR to fix simple issue.

**Comment by normanmaurer** [comment]
@isdom you can still do if you like :) We love contributions 👍

**Comment by isdom** [comment]
thanks @normanmaurer ,  let me try...

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6268
