### ISSUE TITLE
race condition in http/2 around connection preface

### ISSUE THREAD

**Issue by mosesn** [netty/netty#6272]
### Expected behavior

h2 clients should buffer messages until after the connection preface has been sent

### Actual behavior

h2 will try to write http/2 frames before writing the connection preface.

### Steps to reproduce

Construct a netty pipeline, add an http2connectionhandler, call connect, then immediately try writing an http/2 message.

### Minimal yet complete reproducer code (or URL to code)

Remove this line: https://github.com/twitter/finagle/blob/develop/finagle-http2/src/main/scala/com/twitter/finagle/http2/Http2Transporter.scala#L113 and then try running our test suite.

https://github.com/twitter/finagle

### Netty version

4.1.7 (goes back as far as 4.1.0, I think)

### JVM version (e.g. `java -version`)

8

### OS version (e.g. `uname -a`)

Darwin tw-172-25-138-25.office.twttr.net 14.5.0 Darwin Kernel Version 14.5.0: Sun Sep 25 22:07:15 PDT 2016; root:xnu-2782.50.9~1/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
@nmittler @Scottmitch PTAL

**Comment by Scottmitch** [comment]
Instead of queuing in the http/2 codec in practice we wait for the `channelActive` to flow through the pipeline before we start writing. Queuing at this level (if necessary) is currently the responsibility of a higher layer. If you want to contribute an encoder which queues frames until `channelActive` occurs that sounds reasonable.

**Comment by mosesn** [comment]
@Scottmitch this isn't a safe assumption to make in general, so in other channel handlers with this kind of requirement (like [TLS][0]) we enqueue it in the handler.  I think we should take the same action here.  I think it's a much better API.

[0]: https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L591-L598

**Comment by mosesn** [comment]
@Scottmitch I almost forgot–the reason I filed this ticket was because I found that it wasn't always triggered on channelActive, so right now I have to try to guess when the preface will be sent.  As an example, if I'm using ALPN to decide whether to install the http/2 connection handler or not, when I add the handler, channelActive has already been triggered, so instead it sends the connection preface on handlerAdded.  This means I need a different buffering handler depending upon how it's added to the pipeline.

**Comment by Scottmitch** [comment]
Agreed the fragmentation is not ideal here. My assumption of what is involved here is object wrappers and queues.  I don't want to introduce "unconditional queuing" (always have a queue in the way) into the "low level API" to avoid this overhead. However if the queueing is "conditional" (only active before the preface is sent) or optional that sounds reasonable. This may be more easily accomplished in the "higher level API" where everything is already wrapped in an object.

This is also related to waiting until receiving settings until sending data (which is also currently left to the application layer).

**Comment by mosesn** [comment]
Yeah, I was thinking of the conditional queueing.  I agree that unconditional queueing is also not great.

Oof, I always forget about the framewriter stuff in Http2ConnectionHandler.  Would you be open to changing HttpToHttp2ConnectionHandler to buffer?  Another option that would make this easier would be to at least have the Http2ConnectionHandler emit a `userEventTriggered` or expose a method we could override `onPrefaceSent` or something like that.

What's the race with the settings?  My understanding is that h2 allows you to start sending messages before you receive settings.

**Comment by Scottmitch** [comment]
> Would you be open to changing HttpToHttp2ConnectionHandler to buffer

Conditional and/or optional buffering here sgtm. Are you interested in submitting a PR?

> Http2ConnectionHandler emit a userEventTriggered

+1

> What's the race with the settings? My understanding is that h2 allows you to start sending messages before you receive settings.

Yes the specification allows you to exchange frames before the initial settings have been received at the risk of you violating these not-yet-received SETTINGS and having streams RST or the connection shutdown. Some conservative endpoints may want to wait for the first settings frame to be received before sending data (optionally).

**Comment by mosesn** [comment]
OK, this isn't high priority for us, since we have something working, but I'll see if I can schedule some time for a PR for this.

**Comment by Scottmitch** [comment]
@mosesn - Adding a new user event shouldn't be too much effort. Let me take this and I ping on review.

**Comment by mosesn** [comment]
oh, awesome!  that would be really helpful 👍

**Comment by normanmaurer** [comment]
@mosesn @Scottmitch can we close this one ?

**Comment by Scottmitch** [comment]
IIUC ... @mosesn please re-open if I missed something
