### ISSUE TITLE
Announcing CAs with OpenSSL mutual auth causes extreme slowdown with paranoid leak detection

### ISSUE THREAD

**Issue by jchambers** [netty/netty#6298]
After upgrading to Netty 4.1.8/netty-tcnative fork26, I've observed that [unit tests involving HTTP/2](https://github.com/relayrides/pushy/blob/v0.9.1/pushy/src/test/java/com/relayrides/pushy/apns/ApnsClientTest.java) have become extremely slow with `-Dio.netty.leakDetectionLevel=PARANOID`. Under Netty 4.1.6/tcnative fork24, tests would run in ~100ms with paranoid leak detection. Under Netty 4.1.8/fork26 (or fork25—Netty 4.1.8 doesn't seem to work with anything older than fork25), the same tests take roughly 10 seconds.

Preliminary profiling doesn't reveal anything obvious (I'm not using the most sophisticated tools), but I'll see if I can do more to isolate the issue. Still, I wanted to open this in the meantime in case the cause is immediately obvious to somebody else.

**Comment by normanmaurer** [comment]
@jchambers that is sadly expected and the cause is explained here:

https://github.com/netty/netty/pull/6145#issuecomment-271899281

**Comment by jchambers** [comment]
Understood; should we leave this issue open for future consideration, or close it because the timeout is just a fact of life now?

**Comment by normanmaurer** [comment]
@jchambers maybe leave it open and just change the title to reflect why ?

**Comment by jchambers** [comment]
Sold. Thanks!

**Comment by Scottmitch** [comment]
@normanmaurer - You mention in https://github.com/netty/netty/pull/6145#issuecomment-271899281 a factor may be because of the number of certificates we have in our tests ... do you think reducing the number will improve things?

**Comment by normanmaurer** [comment]
I think this can be closed now with these pulled in:

https://github.com/netty/netty/pull/6433
https://github.com/netty/netty/pull/6404
