### ISSUE TITLE
Bytes are dropped when using epoll and auto read = false when peer closes connection

### ISSUE THREAD

**Issue by alkemist** [netty/netty#6303]
### Expected behavior

Received but not yet emitted bytes at time of peer connection close when using epoll edge triggered and `autoRead=false` should be emitted (i.e. behaviour as of 4.1.6).

### Actual behavior

As of 4.1.7, As soon as the remote peer disconnects, no further bytes will be emitted.

The problematic change is here: https://github.com/netty/netty/commit/631077c79391fde22afdb1e43d0f642ba530101e#diff-5d2d71235faad7440ee0020202cfa744L59

This is effectively a different take on #3709, but for the non auto read case and is a regression introduced to fix #6173.

`maybeMoreDataToRead() && config.isAutoRead() || super.continueReading()` is _always_ `false` when `autoRead=false`.  This means that queued up bytes are not drained https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollChannel.java#L378 when `EPOLLRDHUP` is read, and the subsequent `shutdownInput();` causes future `channel.read()` calls to effectively NOOP because of https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java#L972 (i.e. `isInputShutdown()` is `true`).

I don't know what the right fix is, but my best naive guess would be to change the start of `epollInReady()` to be:

```
if (!maybeMoreDataToRead && fd().isInputShutdown()) {
  clearEpollIn0();
  return;
}
```

**Comment by alkemist** [comment]
I think this is likely to affect lots of people, and is also blocking a new release of Ratpack. Can you please also indicate when a resolution for this could be released (i.e. is there already a planned patch release? are there other open issues blocking a 4.1.9?), when it is actually resolved. 

Thanks!

**Comment by normanmaurer** [comment]
@Scottmitch PTAL

**Comment by Scottmitch** [comment]
I'm on it ... will keep you posted when I have a fix. This will be fixed for 4.1.9.

**Comment by normanmaurer** [comment]
@alkemist as a workaround you could use NIO for now.

**Comment by alkemist** [comment]
Thanks @normanmaurer & @Scottmitch.

**Comment by alkemist** [comment]
@Scottmitch bad news, the problem persists. I built from the PR @ ae3365c4793cd8d3233875a8aa35fa20999c7c34.

How do you want to proceed? I can give you instructions to be able to run the test I'm running in IDEA against a 4.1.9-SNAPSHOT loaded from maven local.

**Comment by normanmaurer** [comment]
@alkemist yes please leave infos how to reproduce here.

**Comment by alkemist** [comment]
It's not pretty, but let's see how we go.

1. Checkout https://github.com/ratpack/ratpack/tree/netty-6303-repro
1. Ensure you have a `4.1.9-SNAPSHOT` installed in your local maven repo
1. in checkout, run `./gradlew idea`
1. Open the checkout dir in IDEA
1. In IDEA, Navigate to `HttpClientResponseStreamingSpec` and run `chunked responses are streamed reliably`

You'll see that the test “hangs” and will eventually timeout. If you run with NIO, it will complete in < 1s.

The most relevant interface with Netty here is: https://github.com/ratpack/ratpack/blob/b488f4a1d32d9d420495b72d925583ccca945f20/ratpack-core/src/main/java/ratpack/http/client/internal/ContentStreamingRequestAction.java#L88-L88

**Comment by Scottmitch** [comment]
@alkemist - thanks for the repro ... looking now.

**Comment by Scottmitch** [comment]
@alkemist - I believe I found the issue. Please verify https://github.com/netty/netty/pull/6391.

**Comment by alkemist** [comment]
@Scottmitch fix confirmed! Nice one.

**Comment by Scottmitch** [comment]
@alkemist - Great! Thanks for the reproducer ... makes life so much easier.
