### ISSUE TITLE
'Can not initialize class PlatformDependent0' error in Java 9 with Jigsaw

### ISSUE THREAD

**Issue by Snake1999** [netty/netty#6309]
### Behavior
I'm trying to compile a project with java-9 armed Intellij IDEA (Intellij IDEA uses netty to connect to compile server). When compiling, an internal error thrown showing there is something wrong with netty. 
Is it because of `sun.misc.Unsafe` deleted in Java 9? 
http://fuzhizhantie.com/pastes/7324

IDEA 2017.3.4 uses `netty-all-4.1.5.Final`

### Java & OS version 
```
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+153-jigsaw-nightly-h6003-20170124)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+153-jigsaw-nightly-h6003-20170124,
 mixed mode)
```

``` 
Windows 7 
Microsoft Windows [Version 6.1.7601]
```

**Comment by Underbalanced** [comment]
Related to #6309?

**Comment by GotoFinal** [comment]
@Underbalanced nope, this is old, and already fixed netty bug.
Not sure which one, probably this one?
https://github.com/netty/netty/issues/5987

@Snake1999 update your netty/intellij/report bug to intellij.
I manually updated netty version in intellij library files, as this was fixed in one of next netty version (4.1.6 or 7)
And I think it works fine in EAP of Intellij IDEA.

**Comment by Snake1999** [comment]
@GotoFinal Thank you, after updated to 4.1.7.Final my compiler works fine.

**Comment by hakdogan** [comment]
Hi.

I'm trying to modularize a simple vertx project which only depends on vert.x core dependency.

I've compiled the project and create a modular jar. I'm getting the following message when I run the jar with the command

```sh
java -jar -p namedmodules \
--module-path mylib \
--add-opens=java.base/java.nio=ALL-UNNAMED 
\ -m helloworld/com.kodcu.main.Starter
```

> May 10, 2020 11:55:43 PM io.netty.util.internal.PlatformDependent <clinit>
> INFO: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
> May 10, 2020 11:55:43 PM io.vertx.core.spi.resolver.ResolverProvider
> INFO: Using the default address resolver as the dns resolver could not be loaded
> May 10, 2020 11:55:44 PM com.kodcu.main.Starter
> INFO: Deployment failed!

So the verticle deployment is failed.

mylib folder contains

* vertx-core-3.9.0.jar
* netty-buffer-4.1.48.Final.jar
* netty-common-4.1.48.Final.jar
* netty-resolver-4.1.48.Final.jar
* netty-transport-4.1.48.Final.jar

As can be seen from the list above, my net version is 4.1.48.Final

Does anyone have any idea about the solution?

**Comment by hakdogan** [comment]
I found the reason for the deployment failure is the lack of netty-handle dependency but still the simple server example not working.
