### ISSUE TITLE
Add links to a serie of articles in Netty documentation

### ISSUE THREAD

**Issue by caillette** [netty/netty#6316]
Hi, 

I suggest to add to Netty documentation a serie of articles I wrote about Netty. They are in French, but if you don't speak French then Google translate is your friend. 

Netty (1/6)
https://groups.google.com/d/msg/techos/7OhdFbsHOjI/RZs1Ncs0EAAJ

Netty (2/6) : Modèle de programmation (programming model)
https://groups.google.com/d/msg/techos/BArGTlHcgu0/VKdJdz12EAAJ

Netty (3/6) : Recyclage de la mémoire (memory recycling)
https://groups.google.com/d/msg/techos/pPKiuxd3RkU/-vG78bDHEAAJ

Netty (4/6) : que faire avec (what to do with it)
https://groups.google.com/d/msg/techos/BZxM5IKKXXk/iGQwqgwqEQAJ

Netty (5/6) : Étude de cas ; existant (case study)
https://groups.google.com/d/msg/techos/y5p_y8fHdYA/5aHXc4BuEQAJ

Netty (6/6) : Constatations ; conclusion (facts and conclusion)
https://groups.google.com/d/msg/techos/CGGil5VK4oQ/6DWDc4puEQAJ

**Comment by normanmaurer** [comment]
@caillette you can add them to http://netty.io/wiki/related-articles.html by yourself.
