### ISSUE TITLE
OutOfDirectMemoryError still exists in netty 4.1.8 on Solaris

### ISSUE THREAD

**Issue by MarkVilkel** [netty/netty#6317]
I have client server application based on netty.
Starting with netty 4.1.7 server started to get OutOfDirectMemoryError.
The fix https://github.com/netty/netty/pull/6252 helped for Linuxes, but on Solaris problem still presented.

I have memory dump on hands. There are 46 java.nio.DirectByteBuffers x 16,777,216 bytes each. 736 Mb in total, this is too much I think.
There are two major paths from GC root groups:
1.
```
java.nio.DirectByteBuffer capacity = 16,777,216 64 64
  memory of io.netty.buffer.PoolChunk 16576 80
    head of io.netty.buffer.PoolChunkList 40 40
      parent of io.netty.buffer.PoolChunk 16512 80
        chunk of io.netty.buffer.PooledUnsafeDirectByteBuf [Stack Local] 120 88
          <local variable> of java.lang.Thread [Thread]  "[NettyTransportServer] NettyTransportThread - 6" daemon tid=513 [BLOCKED] 62544 120

```
2.
```
java.nio.DirectByteBuffer capacity = 16,777,216 64 64
  msg of io.netty.channel.ChannelOutboundBuffer$Entry 136 64
    unflushedEntry of io.netty.channel.ChannelOutboundBuffer 200 64
	  buffer of io.netty.channel.PendingWriteQueue 160 48
	    pendingUnencryptedWrites of io.netty.handler.ssl.SslHandler [Stack Local] 336 112
	      <local variable> of java.lang.Thread [Thread]  "[NettyTransportServer] NettyTransportThread - 15" daemon tid=539 [BLOCKED] 62552 120 

```
There are of course some more other paths from GC roots.

I'm using:

Netty 4.1.8

java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

Solaris 10 5/09 s10s_u7wos_08 SPARC

**Comment by doom369** [comment]
Seems like back pressure issue I had. Do you have `channel.isWritable()` checks in your code?

**Comment by MarkVilkel** [comment]
Yes, but this check doesn't stop data sending.
It schedules a checker, which checks is data still processing on client side. If data is processing (even if slowly), server doesn't disconnect client.
Server settings for WRITE_BUFFER_HIGH_WATER_MARK = 50Kb, WRITE_BUFFER_LOW_WATER_MARK =  10Kb.
Clients connected to the server count is about 250.
So 250 x 50 Kb = 12,5 Mb.

Looks like I've got the problem. Possibly I should refactor my code - not to write too much data to slow clients.
So my question is - will be there OutOfDirectMemoryError if server produce much faster than clients can consume?

**Comment by normanmaurer** [comment]
@MarkVilkel yes... if you continue producing and the remote peer will not consume it you will run out of memory at some point in time.

**Comment by MarkVilkel** [comment]
No, I lied in previous comment (sorry about that, I have just reviewed my code). Server doesn't send any data if channel is not writable.

**Comment by normanmaurer** [comment]
@MarkVilkel can you share the heap-dump ? I suspect it does (which should be noticeable in the heap-dump by looking at `ChannelOutboundBuffer` instances and check if the writable field is 0 or 1).

**Comment by MarkVilkel** [comment]
@normanmaurer, I understand that this is impolite from my point to ask for the help like I do, but I can not provide heap dump. Sorry about that.
I've reviewed tens of ChannelOutboundBuffers, all of them have unwritable = 0. nioBufferSize values are rather small hundreds of bytes only.

**Comment by MarkVilkel** [comment]
@normanmaurer,  @doom369
I've switched back transport to netty 4.0.42 and deployed on the same live environment under Solaris. Problem disappeared.

I'm going to prepare test environment with the same load as on live and will provide heap-dump a bit later.

**Comment by normanmaurer** [comment]
@MarkVilkel any update ?

**Comment by MarkVilkel** [comment]
Sorry for late answer, not yet.

**Comment by normanmaurer** [comment]
@MarkVilkel ping

**Comment by MarkVilkel** [comment]
Hi!
I've found the problem in my code.
Sorry and thanks for the help!
