### ISSUE TITLE
bufferPool.direct.capacity(MBean) is incorrect when use unsafe

### ISSUE THREAD

**Issue by louxiu** [netty/netty#6325]
### Expected behavior
`bufferPool.direct.capacity` shows the correct value that direct buffer allocated
### Actual behavior
`bufferPool.direct.capacity` shows incorrect value
### Steps to reproduce
Execute example below
### Minimal yet complete reproducer code (or URL to code)
    public static void main(String[] args) throws Exception {
        int size = 16777217;
        boolean noUnsafe = false;
        ByteBuffer byteBuffer = null;
        if (noUnsafe) {
            System.setProperty("io.netty.noUnsafe", "true");
             byteBuffer = ByteBuffer.allocateDirect(size);
        } else {
             byteBuffer = PlatformDependent.allocateDirectNoCleaner(size);
        }

        System.out.println(SharedSecrets.getJavaNioAccess().getDirectBufferPool().getName());
        System.out.println(SharedSecrets.getJavaNioAccess().getDirectBufferPool().getCount());
        System.out.println(SharedSecrets.getJavaNioAccess().getDirectBufferPool().getMemoryUsed());
        System.out.println(SharedSecrets.getJavaNioAccess().getDirectBufferPool().getTotalCapacity());
    }

### Netty version
4.1.7.Final
### JVM version (e.g. `java -version`)
1.8.0_102
### OS version (e.g. `uname -a`)
Darwin 14.5.0 Darwin Kernel Version 14.5.0

Not sure wether this result is expected.  If this is expect, is there a way to measure how much direct memory is used by netty?

**Comment by normanmaurer** [comment]
@louxiu this is expected. You can "fix" this by using '-Dio.netty.maxDirectMemory=0'

https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/PlatformDependent.java#L134
