### ISSUE TITLE
CorsConfigBuilder exposeHeaders and allowedRequestHeaders should accept CharSequence

### ISSUE THREAD

**Issue by slandelle** [netty/netty#6328]
### Expected behavior

In Netty 4.1, `HttpHeaderNames` constants are `AsciiString`s. It should be possible to directly pass those constants to `CorsConfigBuilder` methods such as `exposeHeaders`, `allowedRequestHeaders`.

### Actual behavior

Those methods take `String`, so one has to convert and call `toString` on the `AsciiString`s.

### Netty version

4.1.8.Final

**Comment by slandelle** [comment]
I can provide a PR.

The question is: "can we use CharSequence all the way down, meaning having CorsConfig::exposedHeaders and CorsConfig:: allowedRequestHeaders return Set<CharSequence> instead of Set<String>?".

**Comment by slandelle** [comment]
> can we use CharSequence all the way down, meaning having CorsConfig::exposedHeaders and CorsConfig:: allowedRequestHeaders return Set<CharSequence> instead of Set<String>?

Answer my own question: no without breaking API (Java's Set is invariant).

**Comment by Scottmitch** [comment]
[AsciiString#toString()](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/AsciiString.java#L1152) caches the string conversion. So with these static methods you should only have to pay the price 1 time. Also with the string improvements in jdk9 we may investigate removing `AsciiString` when we can support jdk9.

**Comment by slandelle** [comment]
@Scottmitch Got it. Closing then, thanks!

**Comment by slandelle** [comment]
Actually, in terms of API, we could just make the `CorsConfigBuilder` accept `CharSequence` and call `toString` internally. WDYT?

**Comment by Scottmitch** [comment]
I haven't thought about it too much but the class is final so on the surface that seems reasonable.

**Comment by slandelle** [comment]
I'll send a PR later tonight.

**Comment by normanmaurer** [comment]
@slandelle cool.. Just ensure you also keep the old methods to preserve binary compatibility.

**Comment by slandelle** [comment]
@normanmaurer Well, I just plan to expand to super type in covariant position (`foo(String)` -> `foo(CharSequence)`), so it should be fine, shouldn't it?

**Comment by normanmaurer** [comment]
Nope this is not fine see also:

https://github.com/netty/netty/issues/6283

**Comment by slandelle** [comment]
Mmm, #6283 looks very different to me (at least from a types perspective).

`addAll(Future[])` (varargs are arrays) is NOT a generalization of `addAll(Promise[])`, event though `Promise` extends `Future` because arrays are invariant, not covariant.

My first guess was that it wasn't necessary in #6292 to restore `add(Promise)`.

Then, I'm not 100% sure of what happens in the Java bytecode, let me check.

**Comment by slandelle** [comment]
My bad, Java arrays are covariant.

**Comment by slandelle** [comment]
I stand corrected :)

**Comment by slandelle** [comment]
PR: #6340
