### ISSUE TITLE
Exception parsing hostname

### ISSUE THREAD

**Issue by loxal** [netty/netty#6330]
My corporate hostname is something “funny” like **MUCM29044565D** and when I launch my Spring Boot application, I get the following exception 

> java.lang.IllegalArgumentException: value is not supported [MAC-48, EUI-48, EUI-64]
> 	at io.netty.util.internal.MacAddressUtil.parseMAC(MacAddressUtil.java:166) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
> 	at io.netty.channel.DefaultChannelId.<clinit>(DefaultChannelId.java:90) ~[netty-all-4.1.8.Final.jar:4.1.8.Final]
> 	at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:107) [netty-all-4.1.8.Final.jar:4.1.8.Final]
> 	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:79) [netty-all-4.1.8.Final.jar:4.1.8.Final]

**Comment by jasontedor** [comment]
I think that you're setting `io.netty.machineId` to your hostname and that's not right, it should look like a MAC address (or just don't set it all).

**Comment by loxal** [comment]
I am not setting anything explicitly. Apparently it’s the Spring Boot that uses some defaults that are wrong and come to light with my odd host name. So it looks rather like a Spring Boot issue that passes wrong values.

**Comment by loxal** [comment]
Actually in the logs I see something like 

> 2017-02-07 23:04:14.273  WARN 94119 --- [  restartedMain] io.netty.channel.DefaultChannelId        : -Dio.netty.machineId: 9a47e861 (malformed)

…for some reason.

**Comment by jasontedor** [comment]
Again, that's because it's explicitly being set to an invalid value. That specific log message is only emitted if the system property `io.netty.machineId` is defined and can not be parsed as a MAC address. You have to find where that it is being done and stop it.
