### ISSUE TITLE
Remove OpenSSLEngine unwrap restriction

### ISSUE THREAD

**Issue by nmittler** [netty/netty#6335]
Creating this as a point of discussion. A caller of an `SSLEngine` should be able to pass a large buffer into `unwrap`, which it received from the network. 

However, we currently have [this check](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java#L824) to make sure that the number of input bytes is <= a maximum packet size. 

This doesn't seem valid anymore since the new package processing logic was added [here](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslEngine.java#L873). IIUC, this logic should protect against any attacks related to the input buffer size.

This was discovered in a [Conscrypt bug](https://github.com/google/conscrypt/issues/76)

@normanmaurer thoughts?

**Comment by normanmaurer** [comment]
@nmittler +1 ... Let me fix it.

**Comment by nmittler** [comment]
@normanmaurer awesome, thanks! I think you just have to remove the check.

**Comment by normanmaurer** [comment]
Yes and adding a Unit Test ;)

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6350
