### ISSUE TITLE
feature request: expose read only property PlatformDependent.getDirectMemoryCounter

### ISSUE THREAD

**Issue by maxcellent** [netty/netty#6341]
We occasionally get OutOfDirectMemory error. It may indicates a real leak. But can also simply be so many connected clients.

From the code, I can see PlatformDependent.DIRECT_MEMORY_COUNTER is used as an internal counter, which is not currently exposed. 

If we can have PlatformDependent.getDirectMemoryCounter to expose a read only attribute, then we can keep track of the number, and easier to monitor the correlation between direct memory usage and other metrics like num connections etc.

**Comment by Scottmitch** [comment]
Have you tried turning up the the [leak detector level](http://netty.io/wiki/reference-counted-objects.html#leak-detection-levels)?

We can add a getter here but note that this class is in an `internal` package and not part of Netty's public API (subject to change at any time).

**Comment by maxcellent** [comment]
@Scottmitch 

Yes, but still getting Direct Memory OOM after all leaks are cleared. I believe there is a chance that we can only support that many concurrent connections with our limited direct memory (256m).  Would like to make it a reportable metrics so that we can monitor it on time series.

**Comment by CodingFabian** [comment]
+1 from my side. I have no problems using an internal api for that.

**Comment by Scottmitch** [comment]
perhaps this will be unnecessary pending https://github.com/netty/netty/issues/6349

**Comment by normanmaurer** [comment]
@Scottmitch let me introduce something which will either return our number or the one used by the JDK based on the config.

**Comment by normanmaurer** [comment]
@CodingFabian @maxcellent btw you can already get the number of bytes used for heap / direct memory when you use the `PooledByteBufAllocator`.

There you can do:

```
PooledByteBufAllocator allocator = ....;
long directMemory = 0;
for (PoolArenaMetric metric: allocator.directArena()) {
    directMemory += metric.numActiveBytes();
}
```

**Comment by Scottmitch** [comment]
from https://github.com/netty/netty/issues/6349#issuecomment-282079611
me:
> Also it still maybe useful to support something like #6341 to improve visibility when Netty's accounting is used instead of the JVMs.

from https://github.com/netty/netty/issues/6349#issuecomment-282103917
@normanmaurer:

> @Scottmitch I think I would still prefer to just have the "stats" on the ByteBufAllocator implementations and so not expose something in the internal package. WDYT ?

Agreed having to rely on an internal API is not preferred. As long as there is a reasonable way to get at the info that is a good start ... maybe https://github.com/netty/netty/issues/6341#issuecomment-279998604 is good enough but what about the unpooled allocator?

**Comment by maxcellent** [comment]
Thanks @normanmaurer, this is working quite well to me. Overall how expensive is this approach? As in:

1. how big list is directArenas likely to return? 
2. PoolArea.numActiveBytes uses a synchronised for loop, is it likely to block other operations?

**Comment by normanmaurer** [comment]
@maxcellent it depends on the configuration. By default it uses 2 * cores number of arenas. It could block allocations.

**Comment by normanmaurer** [comment]
@maxcellent @CodingFabian @Scottmitch PTAL https://github.com/netty/netty/pull/6460

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6460

**Comment by klk-** [comment]
The merged fixes allow you to get the bytes used by a ByteBufAllocator.  This is fine if you have created your own allocator and have a reference to it.  But if you also have 3rd party libraries using Netty direct memory, you cannot use these metrics to track that usage.

So it seems like exposing the global direct memory counter from PlatformDependent would still be useful.
