### ISSUE TITLE
DnsNameResolver uses public dns servers in java 9

### ISSUE THREAD

**Issue by yschimke** [netty/netty#6347]
I realise this is known, but it seems broken enough to deserve a tracking issue.

### Expected behavior

Should use system dns servers 

### Actual behavior

Logs a warning "Default DNS servers: [/8.8.8.8:53, /8.8.4.4:53] (Google Public DNS as a fallback)"
Then uses the google servers.

n.b. It logs the warning even *if* you manually set the nameServerAddresses

        .nameServerAddresses(
            DnsServerAddresses.sequential(new InetSocketAddress("x.x.x.x", 53),
                new InetSocketAddress("x.x.x.x", 53)))

### JVM version (e.g. `java -version`)

java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+149)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+149, mixed mode)

### Workaround

set on command line

--add-opens=java.base/sun.net.dns=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED  --add-opens=java.base/java.nio=ALL-UNNAMED  --add-opens=java.base/sun.nio.ch=ALL-UNNAMED

**Comment by yschimke** [comment]
Somewhat related with Java 9 without these options I get

```
java.lang.NullPointerException
	at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:250)
	at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:347)
	at com.baulsupp.oksocial.network.NettyDns.<init>(NettyDns.java:49)
	at com.baulsupp.oksocial.network.NettyDns.byName(NettyDns.java:92)
	at com.baulsupp.oksocial.Main.createClientBuilder(Main.java:589)
	at com.baulsupp.oksocial.Main.initialise(Main.java:425)
	at com.baulsupp.oksocial.Main.run(Main.java:277)
	at com.baulsupp.oksocial.Main.main(Main.java:106)
	at com.baulsupp.oksocial.TestMain.main(TestMain.java:5)
```

Because b.register() returns a failed ChannelFuture with null channel

```
        channelFuture = responseHandler.channelActivePromise;
        ch = (DatagramChannel) b.register().channel();
        ch.config().setRecvByteBufAllocator(new FixedRecvByteBufAllocator(maxPayloadSize));
```

**Comment by normanmaurer** [comment]
@yschimke thanks for reporting... working on a fix

**Comment by normanmaurer** [comment]
@yschimke fixed by https://github.com/netty/netty/pull/6590 . Please check

**Comment by yschimke** [comment]
As commented on the other issue, this worked for me

**Comment by yschimke** [comment]
should have just commented...

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6590
