### ISSUE TITLE
Change default value of io.netty.maxDirectMemory ?

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#6349]
We introduced `io.netty.maxDirectMemory` to allow creating a Direct ByteBuffer which not is allocated through `Bits.reserveMemory` as this method and the corresponding `Bits.unreserveMemory` were static synchronized. This reduced the overhead but also made it harder to monitor direct memory usage as these are not exported through JMX anymore by Java itself. 

Since Java version 8u72 these methods are not static synchronized anymore so we may want to consider change the default back to use the normal allocation / deallocate path:
https://bugs.openjdk.java.net/browse/JDK-6857566

@Scottmitch @trustin @nmittler @snazy WDYT ?

**Comment by snazy** [comment]
Yes, the methods are not (or no longer) synchronized. But IMO the real issue is in the implementation in {{Bits}} (forcing GC) and how the allocations are managed (linked list).

However, having some MXBean that allows people to get metrics about direct memory usage would be great.

**Comment by Scottmitch** [comment]
Sounds good in general. However didn't this allow use to use a `realloc` in a few places. Maybe worth benchmarking?

**Comment by nmittler** [comment]
Agreed with @Scottmitch ... assuming benchmarks are good, SGTM.

**Comment by normanmaurer** [comment]
@snazy I am more concerned about the static synchronized  which is gone now. I think it would "good enough" to just use the default JDK impl as default and if people really want to make use of this "optimisation" they are free to use it. This way the metrics which are exposed via JMX etc are at least correct. 

@Scottmitch yeah we may be able to `realloc` in some places. That said I think as long as we allow the user to enable it again (via the property) its fine.  WDYT ?

**Comment by normanmaurer** [comment]
@trustin any comments ?

**Comment by Scottmitch** [comment]
My only concern is if performance is impacted in a meaningful way. If there is impact and we still want to change the default then we should call out the change in the Release notes.

**Comment by johnou** [comment]
@snazy don't forget that sleep.. :)

```java
    // These methods should be called whenever direct memory is allocated or
    // freed.  They allow the user to control the amount of direct memory
    // which a process may access.  All sizes are specified in bytes.
    static void reserveMemory(long size, int cap) {
        synchronized (Bits.class) {
            if (!memoryLimitSet && VM.isBooted()) {
                maxMemory = VM.maxDirectMemory();
                memoryLimitSet = true;
            }
            // -XX:MaxDirectMemorySize limits the total capacity rather than the
            // actual memory usage, which will differ when buffers are page
            // aligned.
            if (cap <= maxMemory - totalCapacity) {
                reservedMemory += size;
                totalCapacity += cap;
                count++;
                return;
            }
        }

        System.gc();
        try {
            Thread.sleep(100);
        } catch (InterruptedException x) {
            // Restore interrupt status
            Thread.currentThread().interrupt();
        }
        synchronized (Bits.class) {
            if (totalCapacity + cap > maxMemory)
                throw new OutOfMemoryError("Direct buffer memory");
            reservedMemory += size;
            totalCapacity += cap;
            count++;
        }

    }

    static synchronized void unreserveMemory(long size, int cap) {
        if (reservedMemory > 0) {
            reservedMemory -= size;
            totalCapacity -= cap;
            count--;
            assert (reservedMemory > -1);
        }
    }
```

**Comment by normanmaurer** [comment]
@snazy @Scottmitch IMHO if people really care about the last percent of performance they can still set the system property. In most cases there will be no difference IMHO as when using the `PooledByteBufAllocator` allocating / deallocating direct buffers is not really happen often. The only difference will be when realloc can be used but for this I have another idea how to address this by doing "cheap realloc" in the PooledChunk itself. So my vote is to change the default and so make it less surprising for users and call it out in the release notes.

@nmittler @trustin WDYT ?

**Comment by normanmaurer** [comment]
That said I think we should also expose the used memory in the allocator itself. But this is a different story that I will fix soon.

**Comment by normanmaurer** [comment]
See https://github.com/netty/netty/pull/6444

**Comment by Scottmitch** [comment]
@normanmaurer - System properties may not always be obvious and may not be the most discoverable knobs. This is especially true if there are layers of libraries on top of Netty. I would still like to know what the impacts of this change are. Also it still maybe useful to support something like https://github.com/netty/netty/issues/6341 to improve visibility when Netty's accounting is used instead of the JVMs.

**Comment by normanmaurer** [comment]
@Scottmitch I think I would still prefer to just have the "stats" on the `ByteBufAllocator` implementations and so not expose something in the internal package. WDYT ?

**Comment by normanmaurer** [comment]
Closing as won't fix
