### ISSUE TITLE
DefaultChannelId equals, hashCode, compareTo clarification

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#6371]
`DefaultChannelId` chooses a hash as a random value in the constructor [1] and uses the `data` array in the comparison for `equals` [2]. This means that two `DefaultChannelId` could be `equal()` but have different `hashCode()` values which violates the interface contract of `Object#hashCode()`. 

`DefaultChannelId#compareTo()` always returns `0` [3]. The violates a "strong recommendation" on the `Comparable` interface that if `(x.compareTo(y)==0) == x.equals(y)`. Why is this?

This code has been around for a while [4] so I'm not sure if it is intentional or just cruft.

[1] https://github.com/netty/netty/blame/4.1/transport/src/main/java/io/netty/channel/DefaultChannelId.java#L181
[2] https://github.com/netty/netty/blame/4.1/transport/src/main/java/io/netty/channel/DefaultChannelId.java#L264
[3] https://github.com/netty/netty/blame/4.1/transport/src/main/java/io/netty/channel/DefaultChannelId.java#L251
[4] https://github.com/netty/netty/commit/40003ed250a41286dd73683e62737e318ab003ce

### Netty version
4.1.8

**Comment by Scottmitch** [comment]
@trustin - Can you provide any insight on this?

**Comment by CodingFabian** [comment]
@Scottmitch I think you are reading `Object#hashCode()` wrong. it is perfectly valid to produce the same hashCode when objects are unequal:

```
It is <em>not</em> required that if two objects are unequal
according to the {@link java.lang.Object#equals(java.lang.Object)}
method, then calling the {@code hashCode} method on each of the
two objects must produce distinct integer results
```

I agree on the problem with compareTo, is there any order we can impose on channelIds?

**Comment by Scottmitch** [comment]
> it is perfectly valid to produce the same hashCode when objects are unequal:

Agreed. I over stated this and will correct the issue description.

**Comment by trustin** [comment]
> @trustin - Can you provide any insight on this?

Two `DefaultChannelId` instances in the same VM can never be equal to each other. Having a random hash value doesn't matter therefore.

**Comment by trustin** [comment]
Oh, by the way, the `compareTo()` implementation is not correct obviously. It has to compare the underlying arrays.

**Comment by trustin** [comment]
> Two DefaultChannelId instances in the same VM can never be equal to each other.

If this assumption is broken, then obviously hashCode() implementation is broken. I can't find a counter-example, but I agree that the code is neither intuitive nor simple, so please feel free to make it straightforward.

**Comment by Scottmitch** [comment]
thanks for clarifying @trustin ... not high priority but we will clean this up

**Comment by jasontedor** [comment]
> `DefaultChannelId` chooses a hash as a random value in the constructor and uses the data array in the comparison for equals. This means that two `DefaultChannelId` could be `equal()` but have different `hashCode()` values which violates the interface contract of `Object#hashCode()`.

I don't think that this can happen. The hash code is chosen at random, but the random value is used as the last four bytes of the data array that comprises the channel ID. The equals implementation here compares the arrays, so if two instances are equal, the arrays are equal. If the arrays are equal, the last four bytes are equal. If the last four bytes are equal, the random values that were computed as the hash codes are equal.

**Comment by jasontedor** [comment]
That said, I do think there should just be straightforward implementations here. I opened #6377.

**Comment by Scottmitch** [comment]
> I don't think that this can happen. 

Agreed. Thanks for clarifying. I missed the hashCode being written into the array.

**Comment by jasontedor** [comment]
I think this can be closed now?

**Comment by normanmaurer** [comment]
done
