### ISSUE TITLE
Websocket closes during HTTP 101 on java 1.6.x

### ISSUE THREAD

**Issue by nika-begiashvili** [netty/netty#6373]
### Expected behavior
Websocket connection should be established
### Actual behavior
Websocket connection closes unexpectedly during upgrade protocol
### Steps to reproduce
use general var connection = new WebSocket('ws://127.0.0.1:8181');
### Minimal yet complete reproducer code (or URL to code)
[pastebin.com/5bvbaz1N](http://pastebin.com/5bvbaz1N)
### Netty version
4.1.x
### JVM version (e.g. `java -version`)
1.6.x 32bit
### OS version (e.g. `uname -a`)
Windows 10, Ubuntu xenial under vagrant (Windows 10)

issue only occurs on netty 4.1.x and java 1.6.x combination
same code works on java 1.7+
downgrading code to netty 4.0.44 works as well
**no visible Exception**

**Comment by normanmaurer** [comment]
@nika-begiashvili will have a look

**Comment by normanmaurer** [comment]
@nika-begiashvili can you please test with latest 4.1 branch and re-open if the issue still exists ?
