### ISSUE TITLE
netty https website points to non-https scripts

### ISSUE THREAD

**Issue by mosesn** [netty/netty#6375]
### Expected behavior

https://netty.io/wiki/reference-counted-objects.html#wiki-h3-11 should be properly styled, but it's not because chrome doesn't load non-https scripts when you claim to be on https.

### Actual behavior

https://netty.io/wiki/reference-counted-objects.html#wiki-h3-11 looks unstyled in chrome

### Steps to reproduce

open https://netty.io/wiki/reference-counted-objects.html#wiki-h3-11 should be properly styled
 in chrome

### Minimal yet complete reproducer code (or URL to code)

https://netty.io/wiki/reference-counted-objects.html#wiki-h3-11 should be properly styled

**Comment by Scottmitch** [comment]
thanks @mosesn ... need to investigate more but looks like [bootstrap.min.js](https://github.com/netty/netty.github.com/blob/master/wiki/reference-counted-objects.html#L14) is a problem.

**Comment by normanmaurer** [comment]
I can take a look

**Comment by normanmaurer** [comment]
@mosesn sorry for the long turn-around. Fixed by https://github.com/netty/netty-website/commit/5f015d8cb23433f807cf7ecbbdc348b5e4405bd1

**Comment by normanmaurer** [comment]
This is a better fix https://github.com/netty/netty-website/commit/6e8204733b96ce712f5f536404da53a295f47ea0
