### ISSUE TITLE
NetworkInterface.getNetworkInterfaces() can return null

### ISSUE THREAD

**Issue by CodingFabian** [netty/netty#6384]
To my suprise NetworkInterface.getNetworkInterfaces() can return null:
```
    public static Enumeration<NetworkInterface> getNetworkInterfaces()
        throws SocketException {
        final NetworkInterface[] netifs = getAll();

        // specified to return null if no network interfaces
        if (netifs == null)
            return null;
```

(not sure where its "specified")

https://github.com/netty/netty/blob/42c035982093d6e08201af9572ea43c7cf269adf/common/src/main/java/io/netty/util/internal/MacAddressUtil.java#L55

https://github.com/netty/netty/blob/3344cd21acc61819c327976ed5281daa49b0c05e/common/src/main/java/io/netty/util/NetUtil.java#L166

**Comment by CodingFabian** [comment]
(derived from a bug report by a customer, not sure how they ended up having no network interfaces, also not sure if its relevant to use netty if you do not have network interfaces :))

**Comment by normanmaurer** [comment]
@CodingFabian let me fix this

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/issues/6389
