### ISSUE TITLE
allowMaskMismatch documentation issue

### ISSUE THREAD

**Issue by TheCycoONE** [netty/netty#6387]
Netty version 4.1.8.Final

The documentation for allowMaskMismatch on various websocketx classes reads as follows:
'Allows to loosen the masking requirement on received frames. When this is set to false then also frames which are not masked properly according to the standard will still be accepted.'

The actual usage of this flag is here: https://github.com/netty/netty/blob/eb7f751ba519cbcab47d640cd18757f09d077b55/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocket08FrameDecoder.java#L192

So in fact when the flag is set to *true* then frames which are not masked properly according to the standard will still be accepted.

Suggest new wording:
'When set to true, frames which are not masked properly according to the standard will still be accepted'

(This same comment is present in quite a few classes: the Handshaker, HandshakerFactory, and Decoder classes for each version of the WebSocketClient.)

**Comment by normanmaurer** [comment]
@TheCycoONE sounds good... Can you submit a PR ?

**Comment by TheCycoONE** [comment]
Sure.

**Comment by normanmaurer** [comment]
@TheCycoONE thanks!

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6390
