### ISSUE TITLE
HttpPostRequestDecoder for http2

### ISSUE THREAD

**Issue by jk-5** [netty/netty#6393]
Trying to decode post bodies using the http2 api. The HttpPostRequestDecoder is built for http1.x only.
Most of the fields below are not really relevant for this issue. The point is that no equivalent of the HttpPostRequestDecoder exists for http2.

### Expected behavior
Able to decode post bodies using the HttpPostRequestDecoder, or an equivalent.

### Actual behavior
The HttpPostRequestDecoder api only supports the http1 interfaces

### Steps to reproduce
Try to create a new instance of the HttpPostRequestDecoder from an http2 handler

### Minimal yet complete reproducer code (or URL to code)
    new HttpPostRequestDecoder(<instance of Http2Headers or something>);

This should be obvious

### Netty version
`4.1.8.Final`

### JVM version (e.g. `java -version`)
`1.8.0_121`

### OS version (e.g. `uname -a`)
Ubuntu 16.04
`Linux lptp-jeffrey 4.9.6-040906-generic #201701260330 SMP Thu Jan 26 08:32:10 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Scottmitch** [comment]
codec-http2 supports a light weight compatibility layer to codec-http objects which allows you to use codec-http handlers in your pipeline. See [HttpToHttp2ConnectionHandler](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/HttpToHttp2ConnectionHandler.java) and [InboundHttp2ToHttpAdapter](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/InboundHttp2ToHttpAdapter.java). If this is not good enough then we love PRs :) If you are interested in submitting a PR please describe your approach before hand to be sure everyone is on the same page.

**Comment by normanmaurer** [comment]
Let me close this for now
