### ISSUE TITLE
What happen when received many reset frame from http2 server! 

### ISSUE THREAD

**Issue by wangjianwen** [netty/netty#6405]
We developed a http2 reserve proxy server based on netty.  In http2 proxy, we adapt long connection for connect proxy to http2 server. After http2 prxoy run some time,  from a certain point in time， the frame we received from http2  server  all are one head frame(endFlag=false)、 one reset frame(errorCode=8)  in some of EventExecutorGroup.  Then the proxy dose no work any way. What happen for this problem?

### Netty version
netty 4.1.6

### JVM version (e.g. `java -version`)
jdk 1.8
### OS version (e.g. `uname -a`)
centos 7

**Comment by Scottmitch** [comment]
Can you please provide a reproducer for this issue, describe the specific steps which result in this unexpected behavior, and what the expected behavior is?

**Comment by wangjianwen** [comment]
@Scottmitch , the http2 reserve proxy server we designed looks like the proxy , one of example in netty source code [(simple proxy)](https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/proxy). It also includes ProxyFrontendHandler and ProxyBackendHandler. One difference is that we adopt a long connection strategy for connect proxy to http2 server. So we must init connect from proxy to http2 server when starting the proxy server.  In addition，in order to add business handle(such as route、filter、loadbalance etc) , we used Http2FrameCodec for decoding http2 frame .
    
At first the http2 reserved proxy server was running normally, but after running for some time, many request from proxy to http2 server timeouts. 
   
By viewing running log, we discover that some of EventExecutorGroup  work normal , but some of EventExecutorGroup received three very big http2DataFrame  from http2 server from a point in time,  then these EventExecutorGroup only received DefaultHttp2ResetFrame(errorCode=8) and no other frame. The big data frame looks like as blow：

__DefaultHttp2DataFrame(streamId=664125, content=UnpooledSlicedByteBuf(ridx: 0, widx: 16384, cap: 16384/16384, unwrapped: PooledUnsafeDirectByteBuf(ridx: 16393, widx: 18432, cap: 32768)), endStream=false, padding=0),_

What reason will cause this problem?

**Comment by Scottmitch** [comment]
> we used Http2FrameCodec for decoding http2 frame

`Http2FrameCodec` is experimental [1].

> What reason will cause received all are DefaultHttp2ResetFrame?

`DefaultHttp2ResetFrame` is designed to correlate to the `RST_STREAM` frame. Error code `8` means `CANCEL: Used by the endpoint to indicate that the stream is no longer needed.`. Without more details I will refer you to the RFC [2].

I don't know why you receive a data frame, and it is not clear why you think this is an issue. As previously requested please provide a reproducer for this issue.

[1] https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2FrameCodec.java#L44
[2] https://tools.ietf.org/html/rfc7540#section-6.4

**Comment by normanmaurer** [comment]
@wangjianwen I will close this now as there is lack of feedback. If you still think there is an issue please add more details and re-open
