### ISSUE TITLE
Bungeecord - Failed to find a usable hardware address

### ISSUE THREAD

**Issue by Mineville** [netty/netty#6406]
### Expected behavior
Bungeecord starts without an error
### Actual behavior
bungeecord throws an error at start
### Steps to reproduce
restart bungeecord
### Minimal yet complete reproducer code (or URL to code)
io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces;
### Netty version
latest
### JVM version (e.g. `java -version`)
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-1~bpo8+1-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
### OS version (e.g. `uname -a`)
Linux server 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux

**Comment by johnou** [comment]
That's a warning, not an error..?

**Comment by Mineville** [comment]
[SEVERE] Feb 16, 2017 7:57:58 PM io.netty.util.internal.MacAddressUtil defaultMachineId

It is working, no question. But it did not appear before upgrading and can not be positive anyways.

**Comment by md-5** [comment]
Correct, it's a warning and there is no harm done - just ignore it, it's not causing issues.
I think it likely that this commit fixes it: https://github.com/netty/netty/commit/42c035982093d6e08201af9572ea43c7cf269adf which will be in 4.1.9

**Comment by johnou** [comment]
@Mineville would you please try with 4.1.9.SNAPSHOT?

**Comment by normanmaurer** [comment]
As @md-5 said this should be fixed in current 4.1 branch. Closing
