### ISSUE TITLE
Http server parsing post parameters

### ISSUE THREAD

**Issue by yusufbulentavci** [netty/netty#6418]
Parsing on disk
Http server parsing post parameters failed with "file exists already" error

### Steps to reproduce
Post empty value for a field

### Netty version
I am using 4.1.6. 

### I RESOLVED IT WITH OVERRIDING AbstractDiskHttpData->setContent
    public void setContent(ByteBuf buffer) throws IOException {
        if (buffer == null) {
            throw new NullPointerException("buffer");
        }
        try {
            size = buffer.readableBytes();
            checkSize(size);
            if (definedSize > 0 && definedSize < size) {
                throw new IOException("Out of size: " + size + " > " + definedSize);
            }
            if (file == null) {
                file = tempFile();
            }
            if (buffer.readableBytes() == 0) {
////////////////////// CHANGE BEGIN ////////////////////////
            	if(file.exists())
            		return;
////////////////////// CHANGE END ////////////////////////
                // empty file
                if (!file.createNewFile()) {
                    throw new IOException("file exists already: " + file);
                }
                return;
            }
            FileOutputStream outputStream = new FileOutputStream(file);
            try {
                FileChannel localfileChannel = outputStream.getChannel();
                ByteBuffer byteBuffer = buffer.nioBuffer();
                int written = 0;
                while (written < size) {
                    written += localfileChannel.write(byteBuffer);
                }
                buffer.readerIndex(buffer.readerIndex() + written);
                localfileChannel.force(false);
            } finally {
                outputStream.close();
            }
            setCompleted();
        } finally {
            // Release the buffer as it was retained before and we not need a reference to it at all
            // See https://github.com/netty/netty/issues/1516
            buffer.release();
        }
    }

**Comment by normanmaurer** [comment]
@yusufbulentavci please open a PR with the proposed fix.

**Comment by normanmaurer** [comment]
@yusufbulentavci ping

**Comment by KowalczykBartek** [comment]
Pong @normanmaurer  https://github.com/netty/netty/pull/7697
