### ISSUE TITLE
wrap() invoked when engine is already closed

### ISSUE THREAD

**Issue by johnou** [netty/netty#6419]
### Expected behavior

wrap() not invoked when engine is closed.

### Actual behavior

wrap() is invoked when engine is closed..

```
javax.net.ssl.SSLException: SSLEngine closed already
	at io.netty.handler.ssl.SslHandler.wrap(...)(Unknown Source) ~[netty-handler-4.1.8.Final.jar:?]
```

### Steps to reproduce

```java
ListenableFuture<Response> listenableFuture = asyncHttpClient.preparePost(API_URL)
        .setHeader("Connection", "Keep-Alive")
        .addHeader("Content-Type", "application/json")
        .addHeader("Authorization", apiKey)
        .setBody(JsonUtils.getObjectMapper().writeValueAsBytes(data))
        .execute();
listenableFuture.toCompletableFuture().exceptionally(throwable -> {
    // SSLException logged.
    return null;
});
```

### Minimal yet complete reproducer code (or URL to code)

None yet.

### Netty version

4.1.8.Final

### JVM version (e.g. `java -version`)

java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

### OS version (e.g. `uname -a`)

Linux xxxx 4.4.19-29.55.amzn1.x86_64 #1 SMP Mon Aug 29 23:29:40 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Scottmitch** [comment]
thanks for reporting @johnou ... keep us posted if you have a repro and we will look in the mean time.

**Comment by johnou** [comment]
@Scottmitch sgtm, soon as 4.1.9.Final is out I'll deploy a canary build.

**Comment by Scottmitch** [comment]
I took a closer look and this exception originates from [1]. Can you explain why you think this is unexpected behavior?

[1] https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L664

**Comment by johnou** [comment]
@Scottmitch I was unsure which is why I didn't create the issue initially, so you are saying in my scenario (using async-http-client) the client establishes a connection with the server, ssl handshake completes and before the client has a chance to send the http request the connection is interrupted / closed? If so then I am happy to close this issue.

**Comment by Scottmitch** [comment]
This exception is generated if after a `wrap` the SSLEngine signifies the engine has closed. At this point we will fail all pending writes which have not yet been wrapped. This may happen during the handshake or also at other times, but I don't see any indication in this case of it being a problem. Yes please close if this makes sense and you don't have any additional information which would indicate an issue in Netty.
