### ISSUE TITLE
Unpooled buffer acquired from pooled allocator may have .alloc() returning null

### ISSUE THREAD

**Issue by nayato** [netty/netty#6436]
### Expected behavior
- .alloc() returns allocator that buffer originated from. Backed by following behavior:
 - `allocator` field is reset on `deallocate()`.
 - `allocator` field is set properly in `initUnpooled()`
### Actual behavior
`.alloc()` returns null if buffer is initialized through `initUnpooled()` and was just created. It also may return wrong allocator if it was previously backed by chunk from different pooled buffer allocator.

### Steps to reproduce
https://github.com/netty/netty/blob/66b9be3a469a2cdcc5d18a8b94c679940ce002a9/buffer/src/main/java/io/netty/buffer/PooledByteBuf.java#L128 -- `alloc()` is backed by `allocator` field. As object is pooled it must be initialized during `init()` or `initUnpooled()`

https://github.com/netty/netty/blob/66b9be3a469a2cdcc5d18a8b94c679940ce002a9/buffer/src/main/java/io/netty/buffer/PooledByteBuf.java#L52 -- `allocator` initialized (as expected)

https://github.com/netty/netty/blob/66b9be3a469a2cdcc5d18a8b94c679940ce002a9/buffer/src/main/java/io/netty/buffer/PooledByteBuf.java#L60 -- `allocator` is not initialized.

### Netty version
current 4.1 branch code.

**Comment by normanmaurer** [comment]
Good catch let me fix it

**Comment by normanmaurer** [comment]
@nayato PTAL https://github.com/netty/netty/pull/6440

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6440
