### ISSUE TITLE
PromiseCombiner is not thread-safe

### ISSUE THREAD

**Issue by mrniko** [netty/netty#6459]
### Expected behavior
PromiseCombiner should be thread-safe
### Actual behavior
PromiseCombiner is not thread-safe
### Netty version
4.1.8

Current PromiseCombiner implementation can't be used in several threads concurrently, because its internal state is changed in non thread-safe manner.

**Comment by normanmaurer** [comment]
@mrniko this is expected.

**Comment by fovecifer** [comment]
Hi @normanmaurer Could you explain more details about the design(PromiseCombiner is not thread-safe)?
I found that the sub-promises of PromiseCombiner could fired in different threads, and all sub-promise share the same listener in PromiseCombiner, I think this is a race condition.

**Comment by normanmaurer** [comment]
@fovecifer you are right... we should either put a guard in place to ensure all the `Promise` / `Future` us the same `EventExecutor` or make it thread-safe.

@Scottmitch @nmittler ^^ WDYT ?

**Comment by fovecifer** [comment]
@normanmaurer   Thanks for your help!

In my opinion, ensure all Promise/Future use same EventExecutor is not good option,
it is difficult to make all Promise/Future using same thread 
and this will hurt the "concurrency"

In my code, I use a "spinlock" to fix it and try to avoid context switches

**Comment by loststarsXD** [comment]
@fovecifer I agree with you. An option with CLH queues is a good choice.

**Comment by Scottmitch** [comment]
the class wasn't meant to be thread safe and was intended to be simple/performant for use on the same EventLoop (defect -> feature request?). The class will need work to be thread safe as there is a few areas of disconnected state. Futures may change the event loop they notify on different threads to make things interesting.

**Comment by mayflaver** [comment]
@normanmaurer   @Scottmitch We can create new CombinePromise(a special promise which monitors other future) by combine PromiseCombiner with PromiseAggregator,  it's executor guards thread-safe issues(thread confinement).

**Comment by normanmaurer** [comment]
As far as I can tell we ensure it is used correctly now
