### ISSUE TITLE
hello! is there a jt808 codec?

### ISSUE THREAD

**Issue by yipanbo** [netty/netty#6468]
你好，netty是一个很强大的框架，但是我在网上找不到部标808（jt808）的解码器，我是netty新手，所以希望netty能出一个jt808的解码器，或者可以解析那种以标识头，标识尾来区分一条消息的解码器，谢谢！

Hello! i am a green hand in netty, is there a jt808 codec?  i don`t find the jt808 codec in network, so i hope there is a jt808 codec, or some codec can parse the message which begin with some letter (7e or other),and end up with some letter (7e or other), Thank you!

**Comment by blueswhisper** [comment]
JT808协议场景太局限了，目测netty官方不会提供解析的。
[JT808协议解析样例](http://www.jianshu.com/p/c4cd52af5338)

**Comment by yipanbo** [comment]
@blueswhisper 还是希望能出一个，jt808的例子实在是太少了，网上好像也只有这一篇文章，还有个gps经理的一系列blog，但是都是收费的，强烈希望能出一个，毕竟用标识位标识一条消息也是一种方法，但是netty官网好像没有这种的解码器。

**Comment by normanmaurer** [comment]
Nope there is none but you can write it by yourself extending for example `ByteToMessageDecoder`

**Comment by yipanbo** [comment]
@normanmaurer Thank you very much!

**Comment by RobertWangCN** [comment]
you can write a codec by yourself extending like me that writed a decoder for modbus,it could analyzed most of  manufacturer's protocols by characteristic
