### ISSUE TITLE
can WeakHashMap DELAYED_RECYCLED in Recycler be GC?

### ISSUE THREAD

**Issue by likebean** [netty/netty#6470]
I read the recycler.java, I can not understand why DELAYED_RECYCLED declare as WeakHashMap ?for GC? if for GC purpose,the entry key in the WeakHashMap is Stack,which is Strong referenced by Thread's threadLocal,so I think the entries in the weakhashmap can not  GC，am I wrong?

thanks for reply.

**Comment by normanmaurer** [comment]
@likebean not sure I understand your question but its basically to ensure we can collect these when threads die.

**Comment by likebean** [comment]
Our threads is in threadpool, and not die.if thread not die,will not GC?

**Comment by normanmaurer** [comment]
yeah as long as the threads are alive these will not be collected.

**Comment by normanmaurer** [comment]
closing, please re-open if you think there is an issue
