### ISSUE TITLE
OpenSslEngine does not initialise peer certificates when TLS handshake fails

### ISSUE THREAD

**Issue by keshava88** [netty/netty#6476]
### Expected behavior
In  a scenario where a TLS server makes a certificate request from the TLS client and TLS server fails to trust the client certificate, TLS handshake is expected to fail. This is ok. But the TLS server upon TLS handshake failure should be able to access peer certificate with  javax.net.ssl.SSLSession#getPeerCertificates() to perform some TLS server business (like alarming the user that a client authentication failed and produce the certificate that the client had produced during handshake).
### Actual behavior
When  a TLS handshake fails as per above scenario, access to javax.net.ssl.SSLSession#getPeerCertificates() throws SSLPeerUnverifiedException. 
As per javadoc in https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLSession.html#getPeerCertificateChain() 
SSLPeerUnverifiedException is thown if the peer's identity has not been verified. But in the above case the client identity has been verified but the verification was not sucessful. So TLS server should be able to access the peer certificate.
### Steps to reproduce
I have modified SecureChat example to expose this problem. The base version i have used in 4.1.3.Final. See code patch attached.
### Minimal yet complete reproducer code (or URL to code)
See code patch [netty_issue.patch.txt](https://github.com/netty/netty/files/809699/netty_issue.patch.txt) . ,  Run the junit io.netty.example.securechat.SecureChatCertificateTest#testGetPeerCertificates_serverDoesNotTrustClient()
Sorry the code path is huge since i had to use certificates, private keys etc.

I also have a possible fix in [possible_fix.patch.txt](https://github.com/netty/netty/files/809698/possible_fix.patch.txt) .

### Netty version
4.1.3.Final
### JVM version (e.g. `java -version`)
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

### OS version (e.g. `uname -a`)
Linux host-135-249-45-170 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@keshava88 will check

**Comment by normanmaurer** [comment]
@keshava88 actually I think your assumption is not correct and it works as expected. Just change `                .sslProvider(SslProvider.OPENSSL)` to `sslProvider(SslProvider.JDK)` and you will see the exact same happens with JDK implementation. I am missing anything ?

**Comment by keshava88** [comment]
@normanmaurer  Thanks for the response. 
You are right, JDK SSL engine does the same thing. 

But netty allows us a nice feature with which we can supply our own trust manager when SslProvider is JDK. With that we can supply a trust manager that uses the callback com.alcatel.netconf.api.x509certificates.CallHomeX509TrustManagerImpl#checkServerTrusted() to catch hold of the certificate in case the validation fails.
(same case with client com.alcatel.netconf.api.x509certificates.CallHomeX509TrustManagerImpl#checkClientTrusted() method here).

Will it help if a provide a secure chat code patch to demonstrate these ?

**Comment by normanmaurer** [comment]
@keshava88 yes please show me the code. That said our behaviour should be the same as the JDK impl.

**Comment by Scottmitch** [comment]
> But netty allows us a nice feature with which we can supply our own trust manager when SslProvider is JDK

You can do this if the SslProvider is OPENSSL too. Can you explain why the trust manager behavior should impact the behavior of the SSLEngine w.r.t to providing an SSLSession when the handshake has failed?

**Comment by keshava88** [comment]
@Scottmitch I read from the javadoc that we cna supply a trust manager factory only if the ssl provider is JDK. See ![javadoc](https://cloud.githubusercontent.com/assets/1835123/23495628/dbd606ca-ff3f-11e6-81d6-31aeee1151c1.png)
@normanmaurer  working on the code patch.

**Comment by normanmaurer** [comment]
@keshava88 the javadoc is incorrect... This is not the case anymore since a long time. Let me fix it. Also please update to latest 4.1. release

**Comment by normanmaurer** [comment]
@keshava88 see https://github.com/netty/netty/pull/6484

**Comment by keshava88** [comment]
@normanmaurer So maybe i will try using my own trust manager factory instead.

**Comment by normanmaurer** [comment]
Yes... Let me close this
