### ISSUE TITLE
DnsResolver should be able to handle retry

### ISSUE THREAD

**Issue by testn** [netty/netty#6479]
### Expected behavior
The original Java DNS uses getaddrinfo which retries 2 times by default. DnsResolver should have a mechanism to retry as well.

### Actual behavior
It does not seem to have a retry mechanism unless the DNS servers were specified multiple times.

### Netty version
Netty 4.1.5

### JVM version (e.g. `java -version`)
Java 1.8.0u112

### OS version (e.g. `uname -a`)
Linux

**Comment by Scottmitch** [comment]
Please explain why [DnsNameResolverBuilder#maxQueriesPerResolve](https://github.com/netty/netty/blob/4.1/resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolverBuilder.java#L230) doesn't satisfy your needs.

**Comment by testn** [comment]
My bad.. I was looking for it in the wrong place. That should work.
