### ISSUE TITLE
netty3.9.2 : netty do not write message, dump memory found DownStreamMessageEvent future's cause is StackOverFlowError，why do not write, just this one channel

### ISSUE THREAD

**Issue by andyyin** [netty/netty#6489]

**Comment by andyyin** [comment]
![image](https://cloud.githubusercontent.com/assets/5555453/23536304/e42a94b6-fffe-11e6-9c85-d52444d696a8.png)
accumulate A lot of DownStreamMessageevent

**Comment by Scottmitch** [comment]
Netty 3.x is no longer supported [1]. Please update to Netty 4.1 if you want support.

[1] http://netty.io/news/2016/06/29/3-10-6-Final.html

**Comment by andyyin** [comment]
thank you all the same
