### ISSUE TITLE
Cookies MaxAge

### ISSUE THREAD

**Issue by formalizator** [netty/netty#649]
Code (server-side):
        try{
            HttpRequest request = (HttpRequest) message;
            String value = request.getHeader(HttpHeaders.Names.COOKIE);
            Set<Cookie> cookies = new CookieDecoder().decode(value);
            for (Cookie cookie : cookies) {
                System.out.println(cookie.getMaxAge());
            }
        }catch(Exception exception){
            //not important
        }

Result:
-2147483648
-2147483648
-2147483648
-2147483648
-2147483648
-2147483648
-2147483648
-2147483648
-2147483648
-2147483648

Chrome shows that some cookies are Session, but some Expires Mon, 15 Oct 2012 20:00:11 GMT.

Where am I doing wrong?

**Comment by purplefox** [comment]
I don't see any issue here. It's normal for browsers not to send cookie attributes back to the server. Only the name: value goes from client to server.

From http://en.wikipedia.org/wiki/HTTP_cookie:

"They will only send the cookie’s name-value pair. Cookie attributes are used by browsers to 
determine when to delete a cookie, block a cookie or whether to send a cookie (name-value pair) to the servers."

**Comment by formalizator** [comment]
Problem is that I can't determine if the browser sent me only name-value pair or I got the expired cookie. 
This cookie handler should return null for received cookies. Not the Integer.MIN_VALUE.
