### ISSUE TITLE
Typo in WebSocketServerExtension?

### ISSUE THREAD

**Issue by fenik17** [netty/netty#6503]
Is it a typo [WebSocketServerExtension.new**Reponse**Data()](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/WebSocketServerExtension.java#L29)? `Reponse` instead of `Response`.
Sorry if it's normal. I'm not strong in the English )

**Comment by Scottmitch** [comment]
Looks like a typo to me. However since its an interface, and we can't use default methods bcz we support jdk6 ... I'm not really sure what we can do here.

**Comment by fenik17** [comment]
May be just add `TODO` in the code now, and make this deprecated (with default method) after migrated to JDK 8?

**Comment by normanmaurer** [comment]
+1 can you do a pr?

**Comment by fenik17** [comment]
done #6514
