### ISSUE TITLE
Invalid signature on ECDH server key exchange message

### ISSUE THREAD

**Issue by ClarkHobbie** [netty/netty#6508]
### Expected behavior
Connection and echoing

### Actual behavior
Throws exception

### Steps to reproduce
Use the following commands to get the code:
git clone git@github.com:ClarkHobbie/ssltest.git
Follow steps in the README.md

### Minimal yet complete reproducer code (or URL to code)
https://github.com/ClarkHobbie/ssltest

### Netty version
4.1.6.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

### OS version (e.g. `uname -a`)
"ver" from the command promp give:

Microsoft Windows [Version 10.0.14393]

###Misc
Created the same program with core Java and apache mina version 2.0.16 at ssltest2 & ssltest3.
They are available on GitHub via git@github.com:ClarkHobbie/ssltest2.git and git@github.com:ClarkHobbie/ssltest3.git
or via https://github.com/ClarkHobbie/ssltest2 & https://github.com/ClarkHobbie/ssltest3

**Comment by normanmaurer** [comment]
@ClarkHobbie can you please update to netty 4.1.9.Final-SNAPSHOT and let us know if the problem still persist ?

**Comment by ClarkHobbie** [comment]
This happend with netty-all-4.1.9.Final-20170302.120717-30.

**Comment by Scottmitch** [comment]
Can you list the explicit steps in sequence for how you generate the keystone and trust store? Running the `keytool –keystore serverkeystore –genkey –alias server -keyalg rsa -storepass whatever` command generates `Illegal option:  –keystore`.

Also you are blocking on the EventLoop thread when you read input from `stdin`, which will prevent the EventLoop from making progress. If you need to block you should offload this onto some custom `Executor`.

Here is my java version info:
> java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

**Comment by Scottmitch** [comment]
Also it looks like you are trying to import the `ca-certificate.pem.txt` into the `serverkeystore`. Can you explain why you are doing this?

I would expect the client trust store should contain a list of trusted certificates (including `ca-certificate.pem.txt` in this example), and the server's keystore should the certificate chain including something that is trusted by the CA's certificate, and the associated private key.

See [generate-certs.sh](https://github.com/netty/netty/blob/4.1/handler/src/test/resources/io/netty/handler/ssl/generate-certs.sh) which generates certs/keys using `openssl` for additional reference.

**Comment by ClarkHobbie** [comment]
I have updated the README file to use -importcert instead of -import.  I have also included the motivation behind each step.  

Please remember that the example comes with truststore and serverkeystore which have already undergone these steps: the instructions are there only if you want to recreate these files.

Regarding why I am trying to import ca-certificate.pem.txt: 

I am trying to create a distributed system that uses SSL/TLS encrytpion to communicate.  Each user of the system needs to get their own certificate.  Rather than requiring general certificates I am using locally signed certificates.  This requires that I create a certificate authority and import that certificate authority in various places, including keystores.  Hence my trying to import ca-certificate.pem.txt.

The steps to creating truststore and keystore:

1) Create the local CA self-signed certificate and private key

    openssl req -x509 -newkey rsa:2048 -keyout ca-key.pem.txt -out ca-certificate.pem.txt -days 365 -nodes

2) Create the truststore

    keytool -importcert -keystore truststore -file ca-certificate.pem.txt -alias ca  -storepass whatever

3) Create the server keystore

    keytool –keystore serverkeystore –genkey –alias server -keyalg rsa -storepass whatever

4) Create a certificate signing request for the server

    keytool –keystore serverkeystore -storepass whatever –certreq –alias server –file server.csr

5) Sign the server CSR with the local CA

    openssl x509 -req -CA ca-certificate.pem.txt -CAkey ca-key.pem.txt -in server.csr -out server.cer -days 365 –CAcreateserial

6) Import the local CA to the server keystore

    keytool -importcert -keystore serverkeystore -storepass whatever -file ca-certificate.pem.txt -alias ca

7) Import the singed certificate to the sever kestore

    keytool -importcert -keystore serverkeystore -storepass whatever -file server.cer -alias server

For whatever reason, my version of keytool interprets "-import" as "-importcert"

**Comment by Scottmitch** [comment]
> For whatever reason, my version of keytool interprets "-import" as "-importcert"

This is not the issue. See https://github.com/netty/netty/issues/6508#issuecomment-284868914. The issue is `Illegal option: –keystore`.

> the instructions are there only if you want to recreate these files.

In order to provide assistance all of the steps to reproduce the issue must be listed. In this case the generation of the certificates/keys are relevant.

> The steps to creating truststore and keystore:

Please answer my question from https://github.com/netty/netty/issues/6508#issuecomment-284870327 ... why step 6?

**Comment by ClarkHobbie** [comment]
To avoid the following error:

keytool error: java.lang.Exception: Failed to establish chain from reply

keytool wants the certificate authority to be installed before the server certificate.

**Comment by Scottmitch** [comment]
As described above I am unable to run the reproducer you provided. Please address the issues listed above and report back.

**Comment by ClarkHobbie** [comment]
Appologies regarding -import/-keystore issue, I misunderstood. 

I took a look at the docs and according to http://docs.oracle.com/javase/8/docs/technotes/tools/unix/keytool.html -keystore is a valid option.

> In order to provide assistance all of the steps to reproduce the issue must be listed. In this case the generation of the certificates/keys are relevant.

If creating the truststore and serverkeystore are causing problems, I can remove those steps from the README

I have modified SSLTest so that the user input does not block the EventLoop.

**Comment by ClarkHobbie** [comment]
I just noticed that the server side is now printing out the following:

Mar 08, 2017 2:48:30 PM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at io.netty.handler.ssl.SslHandler$SslEngineType$2.unwrap(SslHandler.java:223)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1123)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1045)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 16 more

This appears to be new with 4.1.9

**Comment by Scottmitch** [comment]
> If creating the truststore and serverkeystore are causing problems, I can remove those steps from the README

As discussed in https://github.com/netty/netty/issues/6508#issuecomment-285148114 ideally I want to be able to retrace your steps for how the certificates/keys are generated. This will help provide more context into the scenario. We have many unit tests and users which do successfully do handshakes and a known difference are your keys/certs.

**Comment by ClarkHobbie** [comment]
In order to generate truststore and serverkeystore using my instructions, you need to get a version of keytool that supports -keystore.  This should be included in java 8 which you can download from http://www.oracle.com/technetwork/java/javase/downloads/index-jsp-138363.html

Please note that the same files, truststore and serverkeystore, work without modification with core Java and mina.  See https://github.com/ClarkHobbie/ssltest2 and https://github.com/ClarkHobbie/ssltest3 for details.

**Comment by Scottmitch** [comment]
When building the `SslContext` on the server side you are using the certificate for the `CA` [1] and the key for the `server` [2]. These don't match and I would expect the handshake to fail. You should be using the server's key with the server's certificate chain (including a certificate that can be tracked back to something trusted by the peer).

[1] https://github.com/ClarkHobbie/ssltest/blob/master/src/main/java/SSLTest.java#L327
[2] https://github.com/ClarkHobbie/ssltest/blob/master/src/main/java/SSLTest.java#L328
