### ISSUE TITLE
[feature request] add support for SameSite cookie attribute

### ISSUE THREAD

**Issue by alunny** [netty/netty#6509]
### Expected Behavior

Modern browsers support a new attribute `SameSite` on cookies, to mitigate CSRF attacks. From https://tools.ietf.org/html/draft-west-first-party-cookies-07

> This document updates RFC6265 by defining a "SameSite" attribute
   which allows servers to assert that a cookie ought not to be sent
   along with cross-site requests.  This assertion allows user agents to
   mitigate the risk of cross-origin information leakage, and provides
   some protection against cross-site request forgery attacks.

It is enabled by default in Chrome 51, and has public support from Firefox: https://www.chromestatus.com/feature/4672634709082112

I should be able to set the SameSite attribues (either SameSite, SameSite=lax or SameSite=strict) on netty cookies.

### Actual behavior

There are no getters/setters for this attribute defined here:
https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/cookie/Cookie.java

Attempting to set this attribute in the value of the cookie results in it being (correctly) escaped.

**Comment by johnou** [comment]
@alunny while the RFC is still draft I find it unlikely any getters/setters will be added, that said the class you linked to is actually an interface, you can implement it yourself or even extend DefaultCookie, SameSite would then need to be added in the toString method.

**Comment by alunny** [comment]
Thanks for the explanation @johnou - I'm using netty via finagle so the extension would be a bit convoluted (would need to extend ServerCookieEncoder also, as well as the finagle wrapper types). But I understand why you wouldn't want to add a draft attribute to the base interface.

**Comment by johnou** [comment]
I said unlikely, didn't say it won't happen as I am not a maintainer and it isn't my place. Let's see what the others say.

**Comment by slandelle** [comment]
Not a maintainer either, but I know the answer for sure: Cookie is an API, and it's not possible to break it until next major release. I'm not aware of any ETA for that, but it should give ample time so see if this draft becomes popular and decide to support if if so.

**Comment by normanmaurer** [comment]
Exactly what @slandelle said :)

**Comment by normanmaurer** [comment]
Let me close this for now... We can re-evolate once we start working on next major version

**Comment by AlexLaviolette** [comment]
Any update on this? More relevant now with the disclosure of [spectre/meltdown](https://www.chromium.org/Home/chromium-security/ssca)

**Comment by slandelle** [comment]
It seems that FireFox 58 will be supporting it too: https://github.com/mozilla/http-observatory/issues/64#issuecomment-348821473

But sadly, that doesn't change the API breakage problem :(
