### ISSUE TITLE
Improve doc on detecting disconnected remote peers with long running connections

### ISSUE THREAD

**Issue by rstoyanchev** [netty/netty#6511]
I've found various bits and pieces but no conclusive summary. Apologies if I've missed anything.

For some context, consider a server writing an infinite stream of SSE events. If there is time between events when the server is not writing and the browser is closed, the server should find out to remove resources. On Linux with `EpollEventLoop` a "channelInactive" fires immediately but with `NioEventLoop` I don't get notifications until the next write fails.

From everything I've seen I gather this is expected but I wanted to confirm that there aren't any options on `ChannelConfig` or elsewhere I'm missing or is `IdleStateHandler` the way to go?

I'd submit a PR if you think it's a good idea to have this summarized somewhere or if you have a suggestion where. `ChannelInboundHandler#channelInactive` perhaps? There are similar [considerations on the reading side](https://github.com/netty/netty/pull/5098#r58975120) I've come across that would be worth mentioning too.

Netty version is 4.1.8.

**Comment by Scottmitch** [comment]
can you provide a means to reproduce this? I can think of why there might be a difference between `EPOLL` and `NIO` but in general they should behave the same.

**Comment by rstoyanchev** [comment]
There is a runnable [application here](https://github.com/bsideup/SPR-15306/blob/master/src/main/java/com/example/DemoApplication.java) you can run with `gradle bootRun` or from an IDE using the main class. 

From the command line `curl -v http://localhost:8080/` and at any time after Ctrl+C. Only one event will be sent but the server keep logging events but not write due to the `distinctUntilChanged` operator. On Linux with epoll you should a "cancel" signal logged (triggered by channelInactive) and the logging should stop. With nio the server events keeps going but if you remove `distinctUntilChanged` it fails on the next write.

This should let you debug but I can pair down the example if need be.

**Comment by Scottmitch** [comment]
yes please a Netty only reproducer would be helpful ... lot of moving parts in this example. I'm not even sure how to change the `EventLoopGroup`.

**Comment by rstoyanchev** [comment]
Okay [another sample](https://github.com/rstoyanchev/netty-6511) with Reactor Netty (since it reflects how we use Netty) and also plain Netty for comparison. I've explicitly configured the EventLoopGroup so you can see how to change it.

With Reactor Netty channelIactive fires for epoll only. With plain Netty it fires for both epoll and nio. However if `autoRead=false` the results are the same, it fires for epoll only. 

The reason for `autoRead=false` is because Reactor Netty implements Reactive Streams with back-pressure on read and write. In this SSE case however the response is committed and we're not expecting more reads so I'm not sure if the flag should make a difference or not.
