### ISSUE TITLE
Is there any Netty metrics available

### ISSUE THREAD

**Issue by wolvever** [netty/netty#6523]
Found this `https://mvnrepository.com/artifact/io.netty/netty-metrics-yammer` that haven't been updated since 2012.  

Started netty/example application, didn't find any jmx metrics specific to netty using jconsole.

The latest discussion related seems to be `https://github.com/netty/netty/issues/4981`.

Didn't see any issue in milestone 4.1.8/4.1.9 mentioned about metrics.

Does that means Netty metrics is still under development/discussion ?  Is there any Netty metrics avaiable now?

### Netty version
4.1.8

### JVM version (e.g. `java -version`)
java version "1.8.0_112"

**Comment by normanmaurer** [comment]
@wolvever nope there is nothing atm
