### ISSUE TITLE
Meet a problem when using netty with http POST method(Decode body, headers mistake or incorrect)

### ISSUE THREAD

**Issue by ductrungcnt** [netty/netty#6532]
Hi!

I using netty version 4.1.4 --> 4.1.9 and meet a problem when i try decode body and headers. it is mistake or incorrect albeit with small in number. I do not know how to fix it. below code i using netty:

### body mistake or incorrect
/?id=9faf008486456ï¿½ï¿½Oï¿½ï¿½8ï¿½ï¿½ï¿½
     ï¿½ï¿½Rkï¿½A@ï¿½eï¿½ï¿½&ï¿½^Oï¿½2ï¿½ï¿½ï¿½ï¿½/uï¿½mkï¿½ï¿½,ï¿½ï¿½G×žï¿½'ï¿½ï¿½ï¿½ï¿½×¸ï¿½Wï¿½<q(ï¿½ï¿½U\k

### headers mistake or incorrect
content-Type=nection: close|User-Agent=Datext/plain; charset=utf-8|Conlvik/1.6.0=|Host=myhost:myport|Accept-Encoding=gzip|Content-Length=251

Content-Type=text/plain; charset=utf-8|Connection=close|User-Agent=Dalvik/2.1.0 (Linux; U; Android 5.1.1; SM-J111F Build/LMY47V)|Host=|ï¾°ï¿©ï¿…"ï¾‹ï¾€ï¿¼ï¾£ï¿§%ï¿¯ï¿‹Rï¾¥%ï¾®ï¿½U.ï¿‘?ï¿žï¿¿ï¿§X\.ï¿lï¾‰ï¿µï¾€ï¾¤dï¾œï¾—ï¾¶%;QXï¿¯ï¾ ï¾œï¿±7ï¿¥ï¿¡ï¿ºï¾¶ï¿½]ï¾€ï¾‹ï¿188|content-length=0|

### using code with epoll transport:

> ServerBootstrap b = new ServerBootstrap();
> b.group(bossGroup, workerGroup)
> 	.channel(EpollServerSocketChannel.class)
> 	.option(EpollChannelOption.SO_RCVBUF, this.mReceiveBufferSize)
> 	.option(EpollChannelOption.SO_REUSEADDR, this.mReuseAddress)
> 	.option(EpollChannelOption.SO_REUSEPORT, this.mReusePort)
> 	.option(EpollChannelOption.IP_FREEBIND, this.mFreeBind)
> 	.option(EpollChannelOption.SO_BACKLOG, this.backlog)
> 
> 	.childOption(EpollChannelOption.TCP_NODELAY, this.mTcpNoDelay)
> 	.childOption(EpollChannelOption.SO_REUSEADDR, this.mReuseAddress)
> 	.childOption(EpollChannelOption.SO_KEEPALIVE, this.keepAlive)
> 	.childOption(EpollChannelOption.CONNECT_TIMEOUT_MILLIS, this.mConnectTimeout)
> 	.childOption(EpollChannelOption.TCP_USER_TIMEOUT, this.tcpUserTimeout)
> 
> 	.childOption(EpollChannelOption.SO_RCVBUF, this.mReceiveBufferSize)
> 	.childOption(EpollChannelOption.SO_SNDBUF, this.mReceiveBufferSize)
> 	.childHandler(new HttpServerInitializer());
> b.bind(new InetSocketAddress(this.mPort)).sync().channel().closeFuture().sync();

HttpServerInitializer.class
> public class HttpServerInitializer extends ChannelInitializer<SocketChannel> {
>     @Override
>     public void initChannel(SocketChannel ch) {
>         ChannelPipeline p = ch.pipeline();
>         p.addLast("server_codec", new HttpServerCodec());
>         p.addLast("aggregator", new HttpObjectAggregator();
>         p.addLast("handler", new HttpSimpleServerHandler(workflow));
>     }
> }

HttpSimpleServerHandler .class
> public class HttpSimpleServerHandler extends SimpleChannelInboundHandler<FullHttpRequest> {
>     @Override
>     public void channelRead0(ChannelHandlerContext ctx, FullHttpRequest request) throws Exception {
>         if ((!request.decoderResult().isSuccess()) || (HttpUtil.is100ContinueExpected(request))) {
>             return;
>         }
>         if (request.method() == HttpMethod.POST) {
>             ByteBuf content = request.content();
>             if ((content != null) && (content.isReadable())) {
>                 Log.info(content.toString(CharsetUtil.UTF_8));
>                 Log.info(dumpHttpHeaders(request));
>             }
>         }
>    }
> 
> private StringBuilder dumpHttpHeaders(HttpRequest request) {
>         StringBuilder builder = new StringBuilder();
>         HttpHeaders headers = request.headers();
>         if ((headers != null) && (!headers.isEmpty())) {
>             for (Map.Entry<String, String> h : headers) {
>                 builder.append(h.getKey()).append("=").append(h.getValue()).append("|");
>             }
>         }
>         return builder;
>     }
> }

### TCP status
142 CLOSING
29168 ESTABLISHED
1604 FIN_WAIT1
121 FIN_WAIT2
6 LAST_ACK
1 LISTEN
2618 SYN_RECV
13424 TIME_WAIT

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b15)
OpenJDK 64-Bit Server VM (build 25.111-b15, mixed mode

### OS version (e.g. `uname -a`)
Linux vps 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 
GNU/Linux

**Comment by Scottmitch** [comment]
could you please submit a link to a GitHub repo that includes a full reproducer? This would mean include the client that reproduces, or instructions with a commonly available client (e.g browser/curl).

**Comment by ductrungcnt** [comment]
could you please review the code below has any problems?
I frequently have problems with Android 5.1.1, 4.1.2, 4.4.2 and 6.0.1. My client is Android only

Thanks!
`
//
protected static String postToServer(String url, Map<String, String> valuePairs) {

        HttpURLConnection conn = null;
        try {
            conn = (HttpURLConnection) new URL(url).openConnection();
            HttpURLConnection.setFollowRedirects(true);
            conn.setInstanceFollowRedirects(false);
            conn.setRequestProperty("Content-Type", "text/plain; charset=utf-8");
            conn.setRequestProperty("Connection", "close");
            conn.setConnectTimeout(10000);
            conn.setReadTimeout(10000);
            conn.setRequestMethod("POST");
            conn.setDoOutput(true);
            conn.setDoInput(true);
            conn.connect();

            DataOutputStream dStream = new DataOutputStream(conn.getOutputStream());
            dStream.writeBytes(createParameters(valuePairs));
            dStream.flush();
            dStream.close();

            int responseCode = conn.getResponseCode();
            if (responseCode == HttpURLConnection.HTTP_OK) {
                return slurp(conn.getInputStream(), 8192);
            } else {
            }

        } catch (Exception e) {
        }

        return null;
    }
	
	private static String createParameters(Map<String, String> parameters) {
        StringBuilder builder = new StringBuilder("/?");
        if (parameters != null) {
            boolean firstParamater = true;
            for (Map.Entry<String, String> entry : parameters.entrySet()) {
                if (firstParamater) {
                    builder.append(entry.getKey());
                    firstParamater = false;
                } else {
                    builder.append("&").append(entry.getKey());
                }
                builder.append("=").append((entry.getValue() == null) ? "" : URLEncoder.encode(entry.getValue()));
            }
        }

        return builder.toString();
    }`

**Comment by Scottmitch** [comment]
This is not a complete reproducer. Please re-open when you are able to provide a complete, self contained, and minimal reproducer as requested in https://github.com/netty/netty/issues/6532#issuecomment-289642926. I don't have adequate information to debug at this point.
