### ISSUE TITLE
Memory maybe leak

### ISSUE THREAD

**Issue by zld406504302** [netty/netty#6533]
### Expected behavior
Memory should be decrease  after client received all message completely
### Actual behavior
But Memory not be decrease until I closed client.
### Steps to reproduce
 * unzip the attachment
 * run BankingServer class
 * run BankingClient class
 * look into os memory 
### Netty version 
4.0.45.Final
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
win10

[Uploading nettyinaction.zip…]()

**Comment by maseev** [comment]
@zld406504302 Looks like the link to a zip archive you've attached is malformed. It would be much convenient to have a GitHub repository with code that reproduces the problem.

**Comment by normanmaurer** [comment]
@zld406504302 please reopen with more details
