### ISSUE TITLE
SelectedSelectionKeySet uses unnecessary Memory

### ISSUE THREAD

**Issue by CodingFabian** [netty/netty#6538]
Forgive me for not knowing, but what does SelectedSelectionKeySet do and why does it need t reserve a 1024 element array?

<img width="471" alt="screen shot 2017-03-13 at 19 35 33" src="https://cloud.githubusercontent.com/assets/176132/23869755/692b64d8-0824-11e7-8d83-df9d1f2c4db6.png">
<img width="678" alt="screen shot 2017-03-13 at 19 35 08" src="https://cloud.githubusercontent.com/assets/176132/23869756/692dfd60-0824-11e7-9fe8-1656476ea41f.png">

In a dump i was analysing, I was pointed at those empty arrays that take up much space.
I do not know if they are supposed to be non-empty (the dump was out of memory, so maybe the keys "unregistered") but if it could be a normal case that they are unused, would it make sense to init this empty first? or start with smaller element count?

**Comment by CodingFabian** [comment]
if its "works as designed" i am also fine with this, but I thought its worth pointing out, maybe it is really a leftover or bug of sorts?

**Comment by normanmaurer** [comment]
@CodingFabian @Scottmitch changed this to only need one array anymore in the latest release. We still start with 1024 array length tho which I think is reasonable.

**Comment by CodingFabian** [comment]
thanks. yeah this was still 4.1.8
