### ISSUE TITLE
Bootstrap a EmbeddedChannel failed

### ISSUE THREAD

**Issue by chhsiao90** [netty/netty#6545]
I found EmbeddedChannel  will registered itself in its constructor at [EmbeddedChannel.java#L178](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/embedded/EmbeddedChannel.java#L178).
And Bootstrap connect will try register channel after create it and found it had been registered and throw exception [AbstractBootstrap.java#L332](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/bootstrap/AbstractBootstrap.java#L332).

Because it was just for some test purpose, so it's not a big deal.
But it would be better if we can bootstrap a EmbeddedChannel!
Some of my idea: maybe we can ignore register if registered at [EmbeddedEventLoop.java#L130](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/embedded/EmbeddedEventLoop.java#L130), because EmbeddedChannel never blocked.

### Expected behavior
Following code should pass.
```
import io.netty.bootstrap.Bootstrap;
import io.netty.channel.Channel;
import io.netty.channel.ChannelFuture;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.embedded.EmbeddedChannel;
import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class BootstrapEmbeddedChannel {
    @Test
    public void shouldGetEmbeddedChanenl() {
        EmbeddedChannel firstCh = new EmbeddedChannel();

        ChannelFuture secondChFuture = new Bootstrap()
                .group(firstCh.eventLoop())
                .channel(firstCh.getClass())
                .handler(new ChannelInitializer<Channel>() {
                    @Override
                    protected void initChannel(Channel ch) throws Exception {

                    }
                }).connect("localhost", 9999);

        assertTrue(secondChFuture.isSuccess());
    }
}
```

### Actual behavior

```
java.lang.IllegalStateException: registered to an event loop already
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:460)
	at io.netty.channel.embedded.EmbeddedEventLoop.register(EmbeddedEventLoop.java:130)
	at io.netty.channel.embedded.EmbeddedEventLoop.register(EmbeddedEventLoop.java:124)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:332)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:126)
```
### Minimal yet complete reproducer code (or URL to code)
Same above.

### Netty version
4.1.9.Final

### JVM version (e.g. `java -version`)
1.8.0_65

### OS version (e.g. `uname -a`)
Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

**Comment by Underbalanced** [comment]
That is because Embedded Channels initialize a internal EventLoopGroup.

Here is the source code for embedded channel.
[EmbededChannel.java](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/embedded/EmbeddedChannel.java)

**Comment by Underbalanced** [comment]
So have you resolved this because this isn't a issue. If so please close.

**Comment by chhsiao90** [comment]
@Underbalanced - Thanks for the comment and sorry for the lately reply.

I think I had no big problem about this, there is many ways to bypass it when writing unit test.
Just have this issue for some discussion.

I know that EmbeddedChannel would create a EmbeddedEventLoop, and register itself into that loop that I had point out at my first comment.
Just curious that if we can bootstrap an EmbeddedChannel that will be great.

For example, at one of example in netty [HexDumpProxyFrontendHandler.java#L46-L48](https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/proxy/HexDumpProxyFrontendHandler.java#L46-L48)
I will think about if we want to write an unit test for it, the easiest way to test it is to create an EmbeddedChannel and verify these channels' inbounds and outbounds.

Or maybe the ability to bootstrap an EmbeddedChannel is not a good idea.
I will close the issue after a while.

And thanks for the comments!

**Comment by asarkar** [comment]
@chhsiao90 I'm also trying to unit test the same class. What did you end up doing?

**Comment by chhsiao90** [comment]
hi @asarkar -EmbeddedChannel was used in unit test for my case, so I use some mock library to prevent the bootstrapping of an EmbeddedChannel..

**Comment by asarkar** [comment]
@chhsiao90 Hmm. I could get bootstrap working in unit test so I took it out using a factory class. It's cleaner design, but still bothering me. Netty has good examples, but sadly no accompanying unit testing samples.

Here my learning project: https://github.com/asarkar/kotlin/tree/master/netty-learning/joke-proxy

**Comment by chhsiao90** [comment]
@asarkar - agreed! that's what I'm doing too, create a channel factory instead of using bootstrap directly. And writing unit test is always hard....
