### ISSUE TITLE
HttpServerKeepAliveHandler closes connection on 204 response

### ISSUE THREAD

**Issue by sschepens** [netty/netty#6549]
### Expected behavior

Netty Http Server responds 204 without body, maintaining the connection open.

### Actual behavior

`HttpServerKeepAliveHandler` closes the connection unless the response is `Informational` or has `Content-Length` set, but 204 responses are not Informational but should not carry a `Content-Length` header [rfc](https://tools.ietf.org/html/rfc7230#section-3.3.2).
```
A server MUST NOT send a Content-Length header field in any response
   with a status code of 1xx (Informational) or 204 (No Content).  A
   server MUST NOT send a Content-Length header field in any 2xx
   (Successful) response to a CONNECT request
```
A condition regarding 204 responses should be added [here](https://github.com/netty/netty/blob/149916d052180dd2b0e0e98598f349454ea200ba/codec-http/src/main/java/io/netty/handler/codec/http/HttpServerKeepAliveHandler.java#L115).

### Steps to reproduce

Create Http Server adding `https://github.com/netty/netty/blob/149916d052180dd2b0e0e98598f349454ea200ba/codec-http/src/main/java/io/netty/handler/codec/http/HttpServerKeepAliveHandler.java#L115`

Send a 204 response without body and `Content-Length`.

**Comment by Scottmitch** [comment]
see https://github.com/netty/netty/pull/6587
