### ISSUE TITLE
Http2StreamChannel doesn't inherit config of the parent channel

### ISSUE THREAD

**Issue by vkostyukov** [netty/netty#6551]
# Problem

As you probably aware, Finagle is a bit special when it comes to Netty 4 usage. For example, we neither use pooling nor prefer direct buffers at the moment. We're getting close to the pooled/direct utopia, but we're not there yet.

That said, Finagle's HTTP/2 pipelines are unpooled and yet we've discovered that inbound messages on the server-side are pooled in some cases. Turns out, `Http2StreamChannel` doesn't inherit the channel config from the parent channel (in our case, a channel with unpooled allocator) and just [defaults to a standard setup effectively enabling pooling](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/AbstractHttp2StreamChannel.java#L58).

A possible workaround is to override the default allocator (`-Dio.netty.allocator.type`).

Is there any reason to not pass parent's channel config to the `Http2StreamChannel` constructor to make sure it re-uses its settings? I'm happy to make a PR if that sounds like a reasonable solution.

I'm not excluding the possibility that this is done intentionally for HTTP/2 and there is a good reason to not reuse parent's channel config. I apologize if that's the case and I'm eager to hear your thoughts about this.

# Env Details

* Netty version: 4.1.9-Final
* JVM version: 1.8.0_111-b14
* OS: Darwin 15.6.0

**Comment by normanmaurer** [comment]
@vkostyukov this is a bug... Please open a PR FTW :)

**Comment by vkostyukov** [comment]
Thanks @normanmaurer! I'm on it!

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6552
