### ISSUE TITLE
Last written packet not being delivered (epoll)

### ISSUE THREAD

**Issue by ninja-** [netty/netty#6557]
### Expected behavior

The packet is always delivered and the connection is closed with FIN or FIN+RST?, when using this piece of code:
```java
channel.writeAndFlush(kickPacket).addListener(ChannelFutureListeners.CLOSE);
```

### Actual behavior

There's a 10% chance this code will race and will result with connection reset for the client.
A working so-far workaround is to add a listener that waits 50ms before calling channel.close().

### Steps to reproduce
...?

### Minimal yet complete reproducer code (or URL to code)

Not sure yet, it's hard to unit test a race :(

### Netty version

4.1.9-FINAL-Snapshot as of 4 weeks ago(9ee4cc0)
Soon I'll test again on latest master, but I haven't seen any commits relating to fixing epoll write functionalities.
(I know the read() epoll bugs were fixed just recently, but nothing related to write() )

### JVM version (e.g. `java -version`)

OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

### OS version (e.g. `uname -a`)

cc @Scottmitch

**Comment by ninja-** [comment]
I just confirmed this on latest Netty 4.19-FINAL

internal exception: java.io.ioexception: an existing connection was forcibly closed by remote

**Comment by ninja-** [comment]
That's seriously interesting :o I just tested it with Wireshark.

The packet IS delivered(flags PSH+ACK). Soon after there's a RST+ACK packet. The client still gets "forcibly closed by remote" before the packet is handled. Why is that?

**Comment by ninja-** [comment]
On a case where it's received correctly(the ratio I see now is more like 40% race, 60% not racing) the sequence is:

SERVER -> CLIENT(PSH+ACK): kick packet
CLIENT -> SERVER: FIN+ACK
SERVER->CLIENT: RST+ACK

**Comment by ninja-** [comment]
When I kick myself on a legit server there is no RST anywhere, there's FIN. Clearly something wrong on the netty side.

**Comment by ninja-** [comment]
I checked whether I am overriding SO_LINGER with 0 which could create this problem according to this http://stackoverflow.com/a/8764491 but I see no mention of this in my codebase.

**Comment by ninja-** [comment]
I found a unit test for this bug, but somehow it's still passing

![](https://vderp.net/s/xkE3v_chrome_2017-03-22_12-58-21.png)

**Comment by ninja-** [comment]
According to this comment this may be a problem with calls to shutdown(...)?
http://stackoverflow.com/a/8875362

**Comment by ninja-** [comment]
Yeah so adding channel.shutdownOutput() before channel.close() makes it work properly....Now it's sending FIN. This should be the default behaviour. I can come up with a PR...

**Comment by normanmaurer** [comment]
@ninja- did you read: http://m.blog.csdn.net/article/details?id=29864509 ?

I think what you describe may be expected. Did you check the nio transport and see if it acts the same ? (it should).

**Comment by Scottmitch** [comment]
@ninja- - Before you come up with a PR to change behavior can you submit a stand alone unit test which demonstrates the issue. If this is just a matter of calling shutdown can this be done at the application layer if your application requires this behavior?

**Comment by ninja-** [comment]
@Scottmitch maybe it's a client-side bug? I remember a netty bug that caused connection resets to be processed before processing incoming data. The client is using some version of netty 4 out of 2015 I think (which is the build date of the game client...) so that's something I don't 100% control.

Anyway, I added a delay and I am happy enough with this code:

```java
            handle.writeAndFlush(new Kick(reason)).
                addListener(new ChannelFutureListener() {
                    @Override
                    public void operationComplete(ChannelFuture future) throws Exception {
                        ((DuplexChannel) future.channel()).shutdownOutput();
                        future.channel().eventLoop().schedule(new Runnable() {
                            @Override
                            public void run() {
                                handle.close(); // workaround some problems related to kicks
                            }
                        }, 50L, TimeUnit.MILLISECONDS);
                    }
                });
```

**Comment by Scottmitch** [comment]
@ninja- - We have had some bugs in this area in the past, and a lot has changed since 2015 so it is possible the older client code is contributing. Let me close this for now and if you are able to provide a unit test which demonstrates the issue we will fix it.
