### ISSUE TITLE
Unneeded call to writev(...) when writing just 1 buffer

### ISSUE THREAD

**Issue by ninja-** [netty/netty#6560]
### Expected behavior

When writing epoll data and there is just one buffer in outbound buffer, write(...) syscall should be used.

### Actual behavior

For some reason writev(...) is called with iovcount = 1 every time.

```
[pid 14295] writev(106, [{"xxx"..., 50}], 1) = 50
```

With the args being: file descriptor, {[buffer bytes, buffer size]}, buffer count(= 1)

### Steps to reproduce

Should reproduce on every epoll server.

### Netty version

Netty 4.1.9 Final, no patches.

**Comment by ninja-** [comment]
I can't spot a logical mistake in piece of code https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java#L468

**Comment by ninja-** [comment]
The logic fail may be here:
what do you think @normanmaurer?

https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java#L458

here using in.size() (counting flushed+unflushed messages ?)

https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java#L527

here using forEachFlushedMessage(counting only flushed messages?)

**Comment by normanmaurer** [comment]
I will check soon, just super busy atm

**Comment by normanmaurer** [comment]
@ninja- this can happen when multiple write loops are needed to write all buffers and the cnt goes down to 1:

https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java#L344

This should not happen very frequently I think it not really does any harm. Otherwise we would need to add an extra branch which will be expected on every loop execution. So I think this issue can be closed .

@ninja- agree ?

**Comment by ninja-** [comment]
@normanmaurer I can't see a single write(...) call in the logs, so it's very frequent

**Comment by ninja-** [comment]
@normanmaurer are you able to reproduce ?

**Comment by normanmaurer** [comment]
Had no time yet... a reproducer and details how you debugged this will help

**Comment by ninja-** [comment]
Sure thing, I'll prepare a reproducer that will show the problem with strace.

**Comment by normanmaurer** [comment]
@ninja- any news on the reproducer ?

**Comment by ninja-** [comment]
It should reproduce on every epoll server-client demo and you can see the writev calls on strace...Do you need a 100% automated one?

**Comment by johnou** [comment]
@ninja- well you did offer to provide a reproducer to show the problem with strace ;)

**Comment by ninja-** [comment]
@normanmaurer @johnou I did some debugging now. The problem is that my app is using EMPTY_BUFFER for control flow to know when data has been written. I tried to get rid of it but I can't.. The empty buffer is removed at IovArray.add level. So msgCount is always 2 and iovArray.count() is always 1. Are you fine with adding a second if in doWriteMultiple which - as I tested - will fix the problem?

**Comment by normanmaurer** [comment]
@ninja- I see this makes sense then. While I think adding another branch will most likely not hurt I would like to understand why you even care. Can you explain why this matters for you ?

**Comment by ninja-** [comment]
writev does memcpy for every piece of data...the CPU usage ratio for my proxy app is 2;1 or 3:1 - writev:read. So writev calls take 2x or 3x as much as the read calls. The CPU usage of other components is marginal compared to what write/read takes. I suspect changing writev with write could reduce cpu usage.

**Comment by normanmaurer** [comment]
@ninja- usually writev should have not much overhead when implemented in the kernel for the device (which should be the case for network io). So I am not expecting any gains here, especially as its only one buffer and so there will be not much to copy (if it needs to copy at all). Can you just test it locally and see if it really improves things ? My guess is it will not at all.

**Comment by ninja-** [comment]
From your experience would that ratio of read to write CPU usage be normal?

**Comment by normanmaurer** [comment]
@ninja- this is something that complete depends on what you do in your app. So there is no "general correct" answer to it.

**Comment by ninja-** [comment]
Let's assume that the app is proxying every packet from client to backend and from backend to client while squashing pending packets to a single buffer so there is always 1 buffer to write. That's very close to how I use it.

**Comment by normanmaurer** [comment]
@ninja- very close is not good enough ... I would need to check the code etc and analyse it. It may be that for example the remote peer is not able to read fast enough which at the end may produce more write calls etc. If you are sure it will improve things why not just patch it and try it yourself ? Again I would be surprised if it really makes a difference but I will be happy to proven wrong.

**Comment by ninja-** [comment]
I'll test that within a few days and let you know :) For remote peer not reading fast enough there's backpressure protection used...read() is not called until last batch of packets have been fully written

**Comment by normanmaurer** [comment]
@ninja- the back pressure you talk about will not really make a difference here as it could be that you will be notified again that the remote peer channel became writable and so try to write again which may result again in a partial write. In this case having more writes then reads make perfect sense

**Comment by ninja-** [comment]
it would make sense to compare number of invocations for writev and read though to know this, but I can't currently do this via VisualVM. Maybe I can count this via strace.

**Comment by ninja-** [comment]
my guess is that partial writes probably happen close to never

**Comment by normanmaurer** [comment]
@ninja- again please take the time to debug / trace / profile. Guesses are not very useful when it comes to "performance work".

**Comment by normanmaurer** [comment]
Closing this for now...  Please open again once you did the profiling andthink its really an issue
