### ISSUE TITLE
Some characters decoded by QueryStringDecoder are not encoded by QueryStringEncoder

### ISSUE THREAD

**Issue by lewisd32** [netty/netty#6561]
### Expected behavior

When a path is decoded by `QueryStringDecoder`, encoding it with `QueryStringEncoder` should result in the original path again.

### Actual behavior

Since #5590, `%0d` and `%0a` (and probably others) in the query string are now decoded, to `\r` and `\n` respectively. However, `QueryStringEncoder` does not re-encode these characters.

### Steps to reproduce

See reproducer code below.

### Minimal yet complete reproducer code (or URL to code)

```Java
final String originalUri = "/%0d%0afoo";

final QueryStringDecoder qsd = new QueryStringDecoder(originalUri);
final String path = qsd.path();
assertEquals("/\r\nfoo", path); // this passes

final QueryStringEncoder qse = new QueryStringEncoder(path);
final String encodedUri = qse.toString();
assertEquals(originalUri, encodedUri); // this fails
```

### Netty version

4.0.42 (and probably older, but not sure what version), anywhere else #5590 is upstream of probably.

### JVM version (e.g. `java -version`)

NA

### OS version (e.g. `uname -a`)

NA

### Notes

We use `QueryStringDecoder` to separate out the path and query parameters of requests. For some requests, we send a 301 redirect to the original path, but with a trailing `/` appended. Because #5590 changed `%0d` (and others) to be decoded, this pattern now throws an exception when we attempt to set the `Location` header for the redirect:
```
java.lang.IllegalArgumentException: Only ' ' and '\t' are allowed after '\n': http://localhost:8080/
foo/	at io.netty.handler.codec.http.HttpHeaders.validateHeaderValue(HttpHeaders.java:1254)
	at io.netty.handler.codec.http.DefaultHttpHeaders.set(DefaultHttpHeaders.java:212)
	at io.netty.handler.codec.http.DefaultHttpHeaders.set(DefaultHttpHeaders.java:203)
	at io.netty.handler.codec.http.HttpHeaders.setHeader(HttpHeaders.java:669)
```
I've tried using `QueryStringEncoder` to re-encode the decoded path, but as described above, it's not re-encoding those characters. I'm not sure if there's a 'correct' way to do this redirect pattern at the moment.

**Comment by fenik17** [comment]
IIUC, encoded CRLF [`%0d%0a`] can be passed with http params, but should not be encoded into the URL path (at least to prevent a "CRLF Injection" / "HTTP Response Splitting" attacks).
Perhaps we should modify the `QueryStringDecoder` so that it doesn't consider the CR/LF as part of the URL path.

And I didn't quite understand yours use case of the `QueryStringEncoder` for redirects..

**Comment by lewisd32** [comment]
I see. That does make some sense.

I'll try to explain our use case for `QueryStringEncoder`. We're not actually using it right now, but while trying to find a workaround for this "bug" (maybe not but?) I tried using it.

All the resources our Netty-using-server serves are expected to have a trailing `/`, for purposes of simplifying the use of relative URLs in the HTML content. To ensure this, any request we receive that doesn't have a `/` on the end, we redirect to `path + "/?" + queryString`.
So a request to `/foo?bar=1` redirects to `/foo/?bar=`.

The `path` we're using is the output of `QueryStringDecoder`. Previously (before #5590) a request to `/foo%0d%0abar` would return a `path` of `/foo%0d%0abar` and we would redirect to `/foo%0d%0abar`, now the same request is returning `path` of `/foo\r\nbar` so we redirect to `/foo\r\nbar/`. Then `HttpHeaders.validateHeaderValue` correctly says this is invalid when we try to set the `Location` header.

I thought that using `QueryStringEncoder` to re-encode the `\r\n` to `%0d%0a` would be a suitable way of handling it, but `QueryStringEncoder` doesn't re-encode those characters.

I'm not sure what the "correct" way of sending a redirect to `path + "/?" + queryString` would be, after the change in #5590.

**Comment by fenik17** [comment]
You easily can redirect to `/foo/?bar=`. But `path` (`/foo/`) can't contain `\r` or `\n` - it's wrong `path` anyway. However, in the params this is entirely acceptable:

```java
String originalUri = "/?%0d%0afoo";

QueryStringDecoder qsd = new QueryStringDecoder(originalUri);
String path = qsd.path();
String param = qsd.parameters().entrySet().iterator().next().getKey();
assertEquals("\r\nfoo", param);

QueryStringEncoder qse = new QueryStringEncoder(path);
qse.addParam(param, null);
String encodedUri = qse.toString();
assertTrue(originalUri.equalsIgnoreCase(encodedUri));
```

But not in the `path`. Where do you get them from? )
Optionally, you can filtering wrong paths or crop to CR/LF.

**Comment by lewisd32** [comment]
Yeah, I can see how that would work. I'm not worried about them in the query string right now though, just the path.
I realize these requests are probably bots or scans, but I'd like to be able to return 400 rather than 500. I'm not sure how to accomplish that right now without explicit checks for `\r` or `\n` in the request, which definitely isn't the right way.

Prior to #5590, our code would successfully send the redirect (to `/%0d%0afoo/` for example) and then the request for `/%0d%0afoo` would return a 404, since it's not a path our system serves.

Since #5590 though, the redirect throws an exception because it has `\r` instead of `%0d`. I'm not sure what we should be doing to detect that the path we're redirecting to contains illegal characters. Checking for `\n` and `\r` ourselves in our code seems wrong. Something like "cleaning" the path somehow, or detecting them, seems like it should be the responsibility of the http library. I'm not sure where that would be best though.

Is there some other encoder we should be using for encoding the path for our redirect, rather than `QueryStringEncoder`? I would expect there to be something that can take a fairly arbitrary string, and encode any characters that are illegal in a path.

**Comment by fenik17** [comment]
If you want just to add a slash at the end of any paths, maybe don't need to decode/encode query? How about something like this:
```java
    public static String ensurePathSlashEnded(String query) {
        int idx = query.indexOf('?');
        if (idx > 0) {
            if (query.charAt(idx - 1) != '/') {
                return query.substring(0, idx) + '/' + query.substring(idx);
            }
        } else if (idx < 0) {
            if (query.isEmpty() || query.charAt(query.length() - 1) != '/') {
                return query + '/';
            }
        } else {
            return '/' + query;
        }
        return query;
    }
```

Alternatively, you may provide a PR to improve `QueryStringDecoder` and `QueryStringEncoder` so they return a custom exception (e.g. `MalformedURLException`), catch this in your code to return 400 for bad request. 

Or forking / override QueryStringDecoder/QueryStringEncoder..

**Comment by lewisd32** [comment]
I've just found out that this:
`curl -I http://localhost/%0d%0a%09a:b`
when using the path from `QueryStringDecoder` as part of the `Location` header (in order to do a relative redirect) results in:
```
HTTP/1.1 301 Moved Permanently
Location: http://localhost:8080/
	a:b/
Content-Length: 0
```
This was introduced by #5590. Prior to #5590, the same request would result in:
```
HTTP/1.1 301 Moved Permanently
Location: http://localhost:8080/%0d%0a%09a:b/
Content-Length: 0
```
It seems to me like #5590 increased the potential for "CRLF Injection" / "HTTP Response Splitting" attacks as you mentioned originally.
If `%0d` and `%0a` are not allowed in the path part of requests, than rather than decoding them (the change that #5590 makes) it should probably be disallowing them, either throwing an exception, or ignoring the path/url after those characters.

What do you think?

**Comment by fenik17** [comment]
You're right. I think it makes sense to fix the `QueryStringDecoder` so that it be consistent with `QueryStringEncoder`. This will be a change in behavior, but can prevent a potential attack vector and make classes behavior more consistent.

@normanmaurer @Scottmitch @trustin - what do you think about it?

**Comment by Scottmitch** [comment]
IIUC there are 2 questions raised in this issue:
1. Should `QueryStringDecoder` (or somewhere) validate URL contents.
2. Should `QueryStringDecoder`'s decode operation be symmetric with `QueryStringEncoder`'s encode operation w.r.t. the URI.

For (1) - As the class name indicates `QueryString*` is primarily focused on the query string. These classes currently don't make any guarantees about sanitizing the URI component.

For (2) - Not the best answer but I think "it depends" or "not necessarily". For "unreserved characters" it is allowed by the spec to decode them and not be required to re-encode them:

https://tools.ietf.org/html/rfc3986#section-2.3
> For consistency, percent-encoded octets in the ranges of ALPHA
   (%41-%5A and %61-%7A), DIGIT (%30-%39), hyphen (%2D), period (%2E),
   underscore (%5F), or tilde (%7E) should not be created by URI
   producers and, when found in a URI, should be decoded to their
   corresponding unreserved characters by URI normalizers.

For "reserved characters" we may have to re-encode them, and maybe not. For example some of these characters maybe OK to not encode (`/` (as delimiting a path component), `?` for query string, etc... see https://tools.ietf.org/html/rfc3986#section-3).

**Comment by fenik17** [comment]
@Scottmitch thanks for the detailed answer! As seen, RFC doesn't clarify whether to sanitize the url path.. But, what is your opinion on this issue? See [related commit in the CURL](https://github.com/curl/curl/commit/75ca568fa1c19de4c5358fed246686de8467c238).

**Comment by Scottmitch** [comment]
sgtm ... lets close.
