### ISSUE TITLE
LoggingHandler does not override channelReadComplete or channelWritabilityChanged

### ISSUE THREAD

**Issue by kevinoliver** [netty/netty#6566]
### Expected behavior

`io.netty.handler.logging.LoggingHandler` logs when these events happen.

### Actual behavior

Because these methods are not overridden in `LoggingHandler`, no logging happens.

### Steps to reproduce

(I think this is self-explanatory)

### Minimal yet complete reproducer code (or URL to code)

(I think this is self-explanatory)

### Netty version

4.1.9

### JVM version (e.g. `java -version`)

(N/A)

### OS version (e.g. `uname -a`)

(N/A)

***

I am happy to put a PR to fix these as they are trivial. I wanted to confirm the fix before moving forward.

**Comment by normanmaurer** [comment]
Sounds good... PR for the win and glory

**Comment by kevinoliver** [comment]
cool. opened https://github.com/netty/netty/pull/6567 to fix this.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6567
