### ISSUE TITLE
SSLHandler slow

### ISSUE THREAD

**Issue by floragunncom** [netty/netty#6571]
### Expected behavior
Minimal SSL overhead (max 5-10 %) with Java SSL.
OpenSSL fails with "io.netty.util.internal.OutOfDirectMemoryError", will open separate issue

### Actual behavior
Pure Java SSL > 3 times slower than without SSL

### Steps to reproduce
Run the provided code

### Minimal yet complete reproducer code (or URL to code)
https://github.com/floragunncom/netty-memleak/tree/bigsslslow (see README)
https://github.com/floragunncom/netty-memleak/releases/tag/slow1
Logs: https://gist.github.com/floragunncom/8e52824974675d3de523ff1ef1aa478f

### Netty version
4.1.9.Final

### JVM version (e.g. `java -version`)
Java Version: 1.8.0_102 Oracle Corporation
JVM Impl.: 25.102-b14 Oracle Corporation Java HotSpot(TM) 64-Bit Server VM

### OS version (e.g. `uname -a`)
Mac OS X x86_64 10.10.5

**Comment by floragunncom** [comment]
maybe related to https://github.com/netty/netty/issues/6139

**Comment by Scottmitch** [comment]
@floragunncom - Are you writing large amounts of data? If so please try https://github.com/netty/netty/pull/6569.

**Comment by floragunncom** [comment]
@Scottmitch #6569 ist not the problem here i think because pure Java SSL is also slow

**Comment by floragunncom** [comment]
@Scottmitch @normanmaurer What is the expected max. overhead of using SSL in terms of data throughput with recent Java 8 on modern hardware?

**Comment by Scottmitch** [comment]
PR #6569 only applies to the OpenSSL based engine, which is why I suggested trying this. However it looks like the OpenSSL memory issue is being tracked in https://github.com/netty/netty/issues/6572.

The maximum overhead may depend upon a few things ... hardware support for encryption primitives, cipher used, etc... The Java SSLEngine is known to be slow and introduce relatively high amounts of overhead in certain configurations. This is why we go through the trouble of supporting a SSLEngine based upon OpenSSL.

**Comment by floragunncom** [comment]
With 4.1.10.Final-SNAPSHOT (and fixed #6572) i get now some measurements:

* No ssl -> 482 ms
* Java SSL -> 5000 ms
* OpenSSL -> 1392 ms
* OpenSSL Refcount -> 1482 ms

OpenSSL is 3 times slower than without ssl (but > 3 times faster than Java SSL)

So OpenSSL add an overhead of approx. 300% to SSL communication. Seems way to much for me?

**Comment by normanmaurer** [comment]
@floragunncom I am not sure what is the expected overhead of SSL. I guess it also really depends on the cipher etc. Did you check what kind of overhead you for example see with a C app ?

**Comment by floragunncom** [comment]
I started with creating a simple java program which transfer bytes over simple plain sockets (non-ssl socket vs. ssl sockets). SSL is approx 100% slower than without. This also not really what i expected but its a lot faster compared to the netty tests.

Results:
<pre>
Mac14,1
4 x 2,7 GHz Intel Core i5

OS: Mac OS X x86_64 10.10.5
Java Version: 1.8.0_131 Oracle Corporation
JVM Impl.: 25.131-b11 Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLSv1.2
200 mbyte in 7433 ms
28 mbyte/sec
224 mbit/sec


OS: Mac OS X x86_64 10.10.5
Java Version: 1.8.0_131 Oracle Corporation
JVM Impl.: 25.131-b11 Oracle Corporation Java HotSpot(TM) 64-Bit Server VM
no ssl mode
200 mbyte in 3518 ms
66 mbyte/sec
528 mbit/sec
</pre>

https://github.com/floragunncom/netty-memleak/tree/simpleperf
https://github.com/floragunncom/netty-memleak/releases/tag/simpleperf1

**Comment by normanmaurer** [comment]
@floragunncom I will have a look tomorrow.

**Comment by normanmaurer** [comment]
@floragunncom please note that your different Main* classes do different things in terms of how these are echo back data. You should build your server on top of the `EchoServer` if you want to compare it. I hacked up something very quickly here and actually the perf is even better in netty compares to just use plain sockets (I still used java sockets for the client side tho to make it easier to compare). Also in your code you also do an extra  memory copy for each write by calling data.copy() which is also not what you do in your socket example where you not do an extra memory copy each time.

So to make it short your two tests are not really comparable.

**Comment by floragunncom** [comment]
@normanmaurer I think you got me wrong. Its not about the absolute figures, its about the ratio between SSL and nonSSL figures. So i'am not comparing netty vs. the plain socket impl, i compare the ratio between SSL/nonssl for netty and the ratio between SSL/nonssl for plain socket.

Netty: Java SSL ist about 6 times slower than without SSL
Plain Socket: Java SSL is about two times slower than without SSL

**Comment by floragunncom** [comment]
@normanmaurer any idea how we can proceed here?

**Comment by Scottmitch** [comment]
@floragunncom - There are a few PRs pending which may impact the performance of the SslHandler. Please try the following PRs https://github.com/netty/netty/pull/6365 https://github.com/netty/netty/pull/6720.

I very briefly looked at the code and the server does a writeAndFlush of 5 bytes on every read to every channel [1]. Each TLS packet will have at least this much overhead (and more overhead after the handshake) for framing/encryption/etc... Perhaps try and aggregate data (which is what https://github.com/netty/netty/pull/6720 does) and simplify the test case to remove the collection of channels to remove some variability.

[1] https://github.com/floragunncom/netty-memleak/blob/bigsslslow/src/main/java/io/netty/example/securechat/SecureChatServerHandler.java#L63

**Comment by floragunncom** [comment]
Maybe related to https://github.com/netty/netty/issues/3318

**Comment by Scottmitch** [comment]
@floragunncom - Please update your example and try the PRs as requested above. The smaller the size of each plaintext `write` the larger the overhead will be for TLS.

**Comment by Scottmitch** [comment]
I will close this issue for now as there are issues as identified above and suggestions made to improve the measurement. Feel free to re-open after the suggested approaches have been implemented and please report the specific impact and direction taken.
