### ISSUE TITLE
ByteBuf does not have access methods for little endian floats and doubles

### ISSUE THREAD

**Issue by trustin** [netty/netty#6576]
### Expected behavior

`ByteBuf` has `get/read/set/writeFloatLE()` and `get/read/set/writeDoubleLE()`.

### Actual behavior

`ByteBuf` does not have the little endian variant of float/double access methods.

### Netty version

4.0.x and 4.1.x

**Comment by trustin** [comment]
Probably not a good idea to add these methods to 4.1 but probably we could in 4.2+

**Comment by normanmaurer** [comment]
@trustin I guess we still could as `ByteBuf` is an abstract class and just implement them directly there. We then could implement these in an optimized way in the sub-classes. WDYT ?

**Comment by trustin** [comment]
Sounds good to me as long as we put some noticeable note in the announcement. :-)

**Comment by normanmaurer** [comment]
@trustin want to take a crack on this or should I do ?

**Comment by trustin** [comment]
Will find some time this week since this isn't an urgent one. :-)

**Comment by normanmaurer** [comment]
@trustin ok cool :)

**Comment by martin3361** [comment]
I came to a point in our game project where we need this and we cannot use it

+1

**Comment by normanmaurer** [comment]
@martin3361 if you want to you could provide a pr for this.

**Comment by martin3361** [comment]
I'm not sure if I can since I'm not familiar with endianness and how to implement it

**Comment by martin3361** [comment]
Here is what I use for workaround:

	private void writeFloat(ByteBuf in, float value) {
		in.writeBytes(ByteBuffer.allocate(4).order(ByteOrder.LITTLE_ENDIAN).putFloat(value).array());
	}

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7099

**Comment by binakot** [comment]
I'm working on gps devices server and I really need this asap 🚜 

+1
