### ISSUE TITLE
Expose the hpack decoder

### ISSUE THREAD

**Issue by guillaumecle** [netty/netty#6579]
Hello,

grpc is using the hpack decoder in [GrpcHttp2HeadersDecoder](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersDecoder.java) and in netty 4.1.9.Final its visibility has been [changed to private](https://github.com/zer0se7en/netty/pull/2/commits/f9001b9fc07a71a9d6eaf0462470416780302107).
This is preventing grpc to be used with netty 4.1.9.Final and with netty-tcnative 2.0.0.Final.

Would it be possible to expose back this feature to the public api?

Thank you,

Reference discussion: https://groups.google.com/forum/#!topic/grpc-io/jkgIbSC9PlI

**Comment by normanmaurer** [comment]
@nmittler @ejona86 can we get around this without exposing it again ?

**Comment by nmittler** [comment]
I'll defer to @ejona86 and @carl-mastrangelo

**Comment by nmittler** [comment]
I just chatted with @carl-mastrangelo offline and this is blocking them from migrating to 4.1.9.Final.  Easiest thing would be to just expose it.

@Scottmitch any objections?

**Comment by carl-mastrangelo** [comment]
FYI: we (gRPC Team) don't mind too much working around breaking method signatures and moving code.  We accept that the HTTP/2 API is unstable.

**Comment by guillaumecle** [comment]
Thanks everyone for working on this. I'm really existed to try this when released.

**Comment by Scottmitch** [comment]
@guillaumecle - Just to clarify your end goal is just to use gRPC after it has consumed a new version of Netty, not necessarily directly using the HPACK classes, correct?

I would like to avoid exposing HPACK if possible (see https://github.com/netty/netty/issues/6591)

**Comment by guillaumecle** [comment]
Correct, especially use cloud-bigtable-client after it has consumed new versions of gRPC and Netty.

**Comment by guillaumecle** [comment]
We are really eager to consume this fix, any idea of when Netty 4.1.10.Final will be released?

**Comment by normanmaurer** [comment]
@guillaumecle end of this week.
