### ISSUE TITLE
MessageAggregator doesn't manage read flow (auto-read is disabled)

### ISSUE THREAD

**Issue by vkostyukov** [netty/netty#6583]
### Expected behavior

This was discovered in Finagle's [HTTP proxy support handler](https://github.com/twitter/finagle/blob/develop/finagle-netty4/src/main/scala/com/twitter/finagle/netty4/proxy/HttpProxyConnectHandler.scala#L103-L106).

Calling `ctx.read()` (when auto-read is disabled) in any handler placed right after the [`MessageAggregator`](https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/MessageAggregator.java) (or `HttpObjectAggregator`) should guarantee at least one inbound message to be fired in a feasible future.

### Actual behavior
`MessageAggregator` doesn't manage the read-flow when auto-read is disabled so the connection just stalls if there are several things that have to be aggregated. I searched for `read()` in `MessageAggregator` and didn't find anything.

I think we should keep issuing read-requests from `MessageAggregator` if (1) a previous handler issued a read-request and (2) message aggregation is still in progress. Please, let me know what do you think about that. As usual, I'm happy to prepare a PR.

### Environment:

Netty 4.1.9-Final

**Comment by normanmaurer** [comment]
@vkostyukov yes this is a bug. Can you please submit a pr ?

**Comment by normanmaurer** [comment]
@vkostyukov maybe let me also think about if we can fix this in a more generic way so it "just works" for all handlers.

**Comment by normanmaurer** [comment]
@vkostyukov so yes just do a PR for now. I may be able to come up with a more general solution but not sure yet and it may take some time.

**Comment by vkostyukov** [comment]
Thanks @normanmaurer! I think fixing it in `MessageAggregator` will be generic enough since it will also fix `HttpObjectMessageAggretator`, `WebSocketFrameAggregator`, `AbstractMemcacheObjectAggregator`, `RedisBulkStringAggregator`, etc.

Working on a fix and a test.

**Comment by vkostyukov** [comment]
So I was playing with the implementation today and it turns out it's not that easy to do.

Because `MesasgeAggregator` is an inbound handler, there is no way to intercept a read request from one of the next handlers, which I planned to use as a predicate whether or not start managing the read-flow (think about it this way: there is no need to keep reading if nobody asked us to). We could probably just do it (no matter if the read request was issued or not) and it will be more-or-less fine. I'd personally prefer this "implicit" auto-read=true (which we could document) for the pipelines with installed message aggregator rather than stalled connections, but I can totally see why people may not like this magical behavior change.

@normanmaurer, @Scottmitch What do you think about that?

**Comment by vkostyukov** [comment]
Another option would be just changing `MessageAggregator` to be a duplex channel handler but that's a public API change.

**Comment by Scottmitch** [comment]
@vkostyukov - Can we use a similar strategy as [ByteToMessageDecoder](https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java#L304)? `MessageAggregator` would essentially track if anything was added to `out` in `channelRead`, and check/reset that state in `channelReadComplete`.

**Comment by vkostyukov** [comment]
Oh I like it @Scottmitch! Thans a lot! Going to try this out.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6604 .. @vkostyukov thanks!
