### ISSUE TITLE
ReadTimeoutHandler configuration improvement

### ISSUE THREAD

**Issue by thiaguten** [netty/netty#6585]
## Expected behavior

In my project, I want to use Java 8 API class java.time.Duration to configure the ReadTimeoutHandler in the pipeline.

```
long timeout = java.time.Duration.ofHours(1).getSeconds();
pipeline.addLast("timeout", new ReadTimeoutHandler(timeout));
```

## Actual behavior

The ReadTimeoutHandler has a constructor, [ReadTimeoutHandler(int timeoutSeconds)](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/timeout/ReadTimeoutHandler.java#L71), with a int value as parameter, so a can't use this constructor because the Java 8 API [Duration#getSeconds()](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#getSeconds--) return a long value.

## Workaround

I had to extend the ReadTimeoutHandler class and create my own constructor with a long value as parameter.

```
public class CustomReadTimeoutHandler extends ReadTimeoutHandler {

  @Deprecated
  public CustomReadTimeoutHandler(int timeoutSeconds) {
    super(timeoutSeconds);
  }

  public CustomReadTimeoutHandler(long timeoutSeconds) {
    this(timeoutSeconds, TimeUnit.SECONDS);
  }

  public CustomReadTimeoutHandler(long timeout, TimeUnit unit) {
    super(timeout, unit);
  }
}
```

## Netty version

4.1.9.Final

Sorry for my bad english.
Thanks! :)

**Comment by fenik17** [comment]
Why not just cast long to int?
`new ReadTimeoutHandler((int) timeout);`

**Comment by thiaguten** [comment]
Yes, that is a possibility too. But why not change int to long in the constructor? I want to understand why an int was used.

**Comment by fenik17** [comment]
> why an int was used

Maybe because it's enough for the seconds? :) Honestly I don't see the problem. Also you can successfully use a pure `long` with `TimeUnit.SECONDS` as second param...

**Comment by normanmaurer** [comment]
@thiaguten as @fenik17 said, so let me close this one

**Comment by thiaguten** [comment]
@normanmaurer @fenik17 No problem. Thanks! :)
