### ISSUE TITLE
Avoid exposing HPACK classes

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#6591]
HPACK is an internal detail of HTTP/2 and if possible it would be nice to avoid exposing this in the public interface of the codec-http2. Recently PR https://github.com/netty/netty/pull/6589 exposed `HpackDecoder` for extensibility reasons. In this particular case the extensibility point seemed to be focused on creating a different type of `Http2Headers` object than `DefaultHttp2Headers`. I would like to propose an alternative approach to exposing `HpackDecoder` and instead make `DefaultHttp2HeadersDecoder`'s creation of the `Http2Header` object overridable. In this particular case [GrpcHttp2HeadersDecoder](https://github.com/grpc/grpc-java/blob/master/netty/src/main/java/io/grpc/netty/GrpcHttp2HeadersDecoder.java) is duplicating logic which also exists in `DefaultHttp2HeadersDecoder` and IMO would be nice to remove this duplication and consolidate the logic in `DefaultHttp2HeadersDecoder`.

Related:
https://github.com/netty/netty/issues/6579
https://github.com/netty/netty/pull/6589

**Comment by Scottmitch** [comment]
@carl-mastrangelo @nmittler - I would like to propose reverting https://github.com/netty/netty/pull/6589 and instead submit a new PR which makes the necessary changes to `DefaultHttp2HeadersDecoder`. WDYT?

**Comment by carl-mastrangelo** [comment]
@Scottmitch I think the reason for that file was to make unsafe assumptions gRPC can safely make.

**Comment by Scottmitch** [comment]
@carl-mastrangelo - Just to be sure I understand you...

> I think the reason for that file

GrpcHttp2HeadersDecoder?

Can you clarify your thoughts on my suggestion above? Extending `DefaultHttp2HeadersDecoder` seems like a cleaner approach and will reduce duplication. Do you agree, and do you have concerns (e.g. performance, functionality missing, etc...)?

**Comment by carl-mastrangelo** [comment]
The `decodeHeaders` forces construction of DefaultHttp2Headers, which is what we want to avoid.  If there was an overload for the construction of the Http2Headers object that is populated, that would work too.

**Comment by ejona86** [comment]
@Scottmitch, your suggestion sounds fine. The main objective was just to override `DefaultHttp2Headers`. That is easy to accomplish in other ways (factory, or overriding a construction method). From what I can tell, that would allow avoiding `HpackDecoder` without any regression.

**Comment by Scottmitch** [comment]
> If there was an overload for the construction of the Http2Headers object that is populated

Yes this is my suggestion.

Thanks for the feedback @carl-mastrangelo @ejona86 ... it sounds like we are on the same page. Let me move ahead with this approach. @carl-mastrangelo - I will ping you on the PR so you can make sure you have the necessary extension points in gRPC.

**Comment by carl-mastrangelo** [comment]
We are keen to start using this change; @normanmaurer is there an ETA for 4.1.10 ?

**Comment by Scottmitch** [comment]
should be in the next couple weeks.
