### ISSUE TITLE
Why does DelimiterBasedFrameDecoder discards buffer if delimiter is not found ?

### ISSUE THREAD

**Issue by sshntt** [netty/netty#6595]
I am looking at the code for the DelimiterBasedFrameDecoder in netty 4.1. My understanding is, if packets with the specified delimiter have not arrived, minDelim will be null which means that even though the frame does not exceed the defined maxFrameLength, the buffer is discarded.

Is my understanding correct ? Or am I missing something ?

**Comment by fenik17** [comment]
> Is my understanding correct ?

No... You can debug this test:

```java
    @Test
    public void incompleteFramesNulDelimeter() {
        EmbeddedChannel ch = new EmbeddedChannel(new DelimiterBasedFrameDecoder(8, Delimiters.nulDelimiter()));
        ch.writeInbound(Unpooled.copiedBuffer("Test", CharsetUtil.US_ASCII));
        assertNull(ch.readInbound());
        ch.writeInbound(Unpooled.copiedBuffer("Line\0abc\0", CharsetUtil.US_ASCII));

        ByteBuf buf = ch.readInbound();
        assertEquals("TestLine", buf.toString(CharsetUtil.US_ASCII));

        ByteBuf buf2 = ch.readInbound();
        assertEquals("abc", buf2.toString(CharsetUtil.US_ASCII));
        assertNull(ch.readInbound());
        ch.finish();

        buf.release();
        buf2.release();
    }
```

A first call of the `readInbound()` return `null`. But a second call return "TestLine", which means that "Test" in the buffer has not been discarded.

**Comment by sshntt** [comment]
Thanks !
