### ISSUE TITLE
SslHandler closes TCP connection before sending an alert on certificate check failure

### ISSUE THREAD

**Issue by risenberg** [netty/netty#6611]
I have a netty server with certificate check performed by TLS SSL engine. A client with a certificate signed by an unknown CA tries to connect to server, and the server just closes the connection without sending a proper SSL alert - I see it in wireshark.
My server is configured like that:
```
SSLContext serverContext = SSLContext.getInstance("TLS");
serverContext.init(keyManagers, trustManagers, null);
SSLEngine engine = buildContext().createSSLEngine();
engine.setUseClientMode(false);
engine.setNeedClientAuth(true);
SslHandler handler = new SslHandler(engine);
```
Looks like the problem is in `SslUtils::notifyHandshakeFailure` - it closes the channel context without flushing pending data from SSLEngine. I found two workarounds for that. First - comment out `ctx.close()` from that method and add a last channel handler with
```
@Override
public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
    ctx.close();
}
```
Second - no patching of netty, just add a special handler
```
@Override
public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
    if (evt instanceof SslHandshakeCompletionEvent) {
        if (evt != SslHandshakeCompletionEvent.SUCCESS) {
            ctx.close();
        }
    }
    super.userEventTriggered(ctx, evt);
}
```

### Expected behavior
Server closes SSL connection correctly without any additional configuration.

### Actual behavior
Added a special handler to make the server close SSL connection correctly.

### Netty version
4.0.42.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

### OS version (e.g. `uname -a`)
Linux risenberg.localdomain 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@risenberg please update to latest netty version and report back if the issue still exists as I think we fixed it
