### ISSUE TITLE
Http2Codec closing streams prematurely

### ISSUE THREAD

**Issue by mosesn** [netty/netty#6612]
### Expected behavior

The stream isn't closed until after the response is sent.

### Actual behavior

The stream is sometimes closed prematurely.

I can only reproduce in an integration test for now, just wanted to file a ticket in case anyone else was seeing it.  Will keep digging into it.

I'm still not 100% sure whether it's in my stuff or not, so please don't investigate yet unless you're seeing it too.

### Netty version

4.1.9.Final

### JVM version (e.g. `java -version`)

8

### OS version (e.g. `uname -a`)

OSX

**Comment by zqureshi** [comment]
I am seeing this with a raw TCP `ChannelHandler` too. Trying to build a simplified test case.

**Comment by normanmaurer** [comment]
@mosesn any update ?

**Comment by mosesn** [comment]
@normanmaurer I think it's something we're doing wrong . . . we're working on a fix now, will see if we can still reproduce after our fix.  we were writing stream ids out of order, which might have made it look like this.

**Comment by normanmaurer** [comment]
@mosesn ok cool... please keep us posted

**Comment by mosesn** [comment]
I don't remember what this was anymore, so I'm going to close this.
