### ISSUE TITLE
DefaultEventExecutorGroup owns thread count is Incorrect

### ISSUE THREAD

**Issue by zmyer** [netty/netty#6617]
### Actual behavior
This is a strange question：
when I Set(10 threads):
`this.workerGroup = new DefaultEventExecutorGroup(10,
            ThreadUtils.newGenericThreadFactory("NettyClientWorkerThreads"));`

but result is（there are only 3 threads）:
"NettyClientWorkerThreads_3" #44 prio=5 os_prio=31 tid=0x00007febd2305000 nid=0x9003 waiting on condition [0x0000700003126000]
"NettyClientWorkerThreads_2" #40 prio=5 os_prio=31 tid=0x00007febd1a01800 nid=0x8803 waiting on condition [0x0000700002d1a000]
"NettyClientWorkerThreads_1" #36 prio=5 os_prio=31 tid=0x00007febd1a00800 nid=0x8003 waiting on condition [0x000070000290e000]

What is wrong with it

### Netty version
4.1.6.Final
### JVM version (e.g. `java -version`)
JDK8
### OS version (e.g. `uname -a`)
MacOS

**Comment by normanmaurer** [comment]
The threads are started in a lazy fashion. If you will have call `group.next().execute(...)` 10 times you will see all of them.
