### ISSUE TITLE
Maven build failure on MacOX Sierra 10.12.4

### ISSUE THREAD

**Issue by kennylbj** [netty/netty#6618]
### Expected behavior
Building successful in command line using command "mvn clean package -DskipTests".
### Actual behavior
Current netty is ok to build, but we will occur build failure if we clone a new netty project.

Failure while building Netty/Handler module.
Here is the error output:

[ERROR] Failed to execute goal on project netty-handler: Could not resolve dependencies for project io.netty:netty-handler:jar:4.1.10.Final-SNAPSHOT: Failure to find io.netty:netty-tcnative:jar:osx-x86_64:2.0.1.Final-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]

### Steps to reproduce
1. mkdir tmp & cd tmp  Or   just remove current netty:  rm -rf netty/
2. clone a new netty project:   git clone https://github.com/netty/netty.git
3. cd netty
4. mvn clean package -DskipTests
### Netty version
4.0 && 4.1
### JVM version (e.g. `java -version`)

java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

### OS version (e.g. `uname -a`)

Darwin kenny.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

### Maven version
Apache Maven 3.3.9

### Location
China

### NOTE
I have built successfully a week ago, Is that possible for the commit https://github.com/netty/netty/commit/077a1988b9c96b5f3e5693a3bb1b2e118992f3a8  ?

I tried to download the missing jar Manually. However the latest version of netty-handler is 4.1.9.Final and netty-tcnative is 2.0.0 Final

netty-handler:    https://mvnrepository.com/artifact/io.netty/netty-handler
netty-tcnative:    https://mvnrepository.com/artifact/io.netty/netty-tcnative

**Comment by chhsiao90** [comment]
Hi @kennylbj ,
It's caused by https://github.com/netty/netty/commit/4bcfa07a7 that used the latest snapshot version of netty-tcnative. And the [nightly build](https://oss.sonatype.org/content/repositories/snapshots/io/netty/netty-tcnative/2.0.1.Final-SNAPSHOT/) didn't contains the build for MacOS...

So the solution might be build latest netty-tcnative by ourselves or maybe we should wait for netty-tcnative release.

**Comment by kennylbj** [comment]
thanks! @chhsiao90

**Comment by chhsiao90** [comment]
I'm also stuck at this as an OSX user 😆

**Comment by kennylbj** [comment]
waiting for update    XD

**Comment by Scottmitch** [comment]
If you want to build locally please add a snapshot repo to your build. We will release tcnative in the next week or so and that should no longer be necessary.

**Comment by kennylbj** [comment]
thanks @Scottmitch

**Comment by normanmaurer** [comment]
Fixed... we now also deploy the OS X version
