### ISSUE TITLE
Some ScheduledExecutorServices like AbstractScheduledEventExecutor break the contract of the interface

### ISSUE THREAD

**Issue by dapengzhang0** [netty/netty#6627]
### Expected behavior
As the javadoc of `ScheduledExecutorServices` stated: 

```
Zero and negative delays (but not periods) are also allowed in schedule methods, 
and are treated as requests for immediate execution.
```

### Actual behavior
For passing a negative delay, `AbstractScheduledEventExecutor#schedule` throws
`IllegalArgumentException`

### Netty version
4.1.3 Final

**Comment by normanmaurer** [comment]
Sounds like a bug.... let me fix it

**Comment by normanmaurer** [comment]
@dapengzhang0 PTAL https://github.com/netty/netty/pull/6633

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6633
