### ISSUE TITLE
Could not find artifact io.netty:netty-tcnative:jar:osx-x86_64:2.0.1.Final-SNAPSHOT

### ISSUE THREAD

**Issue by qiaodaimadelaowang** [netty/netty#6628]
### Expected behavior
mvn -s ~/.m2/settings_default.xml package is ok.

### Actual behavior
Could not find artifact io.netty:netty-tcnative:jar:osx-x86_64:2.0.1.Final-SNAPSHOT

### Steps to reproduce
1.git clone https://github.com/netty/netty.git
2.mvn -s ~/.m2/settings_default.xml package

### Netty version
latest source code on 4.1 branch

### JVM version (e.g. `java -version`)
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### OS version (e.g. `uname -a`)
Darwin tinyhuiwang 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64 i386 MacBookPro12,1 Darwin

### others
I found in pom.xml(netty-parent)，the tcnative.version is 2.0.1.Final-SNAPSHOT,but in http://repo1.maven.org/maven2/io/netty/netty-tcnative/ ,can not find this version ,only 2.0.0,and not SNAPSHOT.

**Comment by normanmaurer** [comment]
Fixed... we now also deploy the OS X snapshot version

**Comment by qiaodaimadelaowang** [comment]
Which remote repository will upload? Is it only sonatype-nexus?

**Comment by normanmaurer** [comment]
https://oss.sonatype.org/content/repositories/snapshots/io/netty/netty-tcnative/2.0.1.Final-SNAPSHOT/

We will release a final version this week tho

**Comment by qiaodaimadelaowang** [comment]
At this time ,the final version is not release.

**Comment by normanmaurer** [comment]
@qiaodaimadelaowang it is... Why you say otherwise ?

http://repo1.maven.org/maven2/io/netty/netty-tcnative/2.0.1.Final/

**Comment by qiaodaimadelaowang** [comment]
Sorry，I find it.

**Comment by qiaodaimadelaowang** [comment]
Sorry.

**Comment by qiaodaimadelaowang** [comment]
Final version in http://repo1.maven.org/maven2/io/netty/netty-tcnative/
and SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots/io/netty/netty-tcnative ?

**Comment by normanmaurer** [comment]
Yes
