### ISSUE TITLE
Error with my BungeeCord

### ISSUE THREAD

**Issue by FullDarkness19** [netty/netty#6637]
### Expected behavior
Bungeecord starts without an error
### Actual behavior
bungeecord throws an error at start ( One warning and one severe )
### Steps to reproduce
Download BungeeCord again and restart my VPS 
### Minimal yet complete reproducer code (or URL to code)

07:49:53 [SEVERE] Apr 18, 2017 7:49:53 AM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 0e:3c:d0:3d:99:0f:0a:b8

### Netty version
#1229
### JVM version (e.g. `java -version`)
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

### OS version (e.g. `uname -a`)
Ubuntu 16.04 
Linux LaYoce 2.6.32-41-pve #1 SMP Sun Oct 4 11:49:58 CEST 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
This is harmless and will be fixed in the next release.

**Comment by FullDarkness19** [comment]
Do you have a solution to this problem waiting for the update because my bungeecord dont work when i launched it.

**Comment by normanmaurer** [comment]
@FullDarkness19 you should report it in the boungeecord issue tracker then as this one is just a `WARNING` which will not prevent an application to work.
