### ISSUE TITLE
Include JCTools sources for shaded classes in the sources jar 

### ISSUE THREAD

**Issue by cstancu** [netty/netty#6640]
Is it possible to include the original sources for the shaded JCTools classes? This would be useful for debugging purposes. Even if I add the JCTools sources jar to the classpath eclipse doesn't pick them up because the path inside the jar doesn't match. 

I am currently working with vert.x, which depends on netty-4.1.8. 

Related issue: #4960 Use shaded dependency on JCTools instead of copy and paste

**Comment by normanmaurer** [comment]
@cstancu if you can point me to how to do this yes :)

**Comment by cstancu** [comment]
The maven-shade plugin has two parameters: `createSourcesJar` and `shadeSourcesContent` which should do just that. I tried adding:

`<createSourcesJar>true</createSourcesJar>`
`<shadeSourcesContent>true</shadeSourcesContent>`
in 
`netty/common/pom.xml` (since I only care about netty-common right now)

at line 103, inside the `<configuration></configuration>` just after `</relocations>` and run `mvn package`, but the generated sources jar does not contain the shaded sources.

**Comment by normanmaurer** [comment]
@cstancu seems like its a known maven plugin bug ? 

https://issues.apache.org/jira/browse/MSHADE-252

**Comment by cstancu** [comment]
@normanmaurer that issue you mention might be related but it doesn't exhibit the exact same symptoms as what I am encountering. I cannot get any sources to be added under the `shaded` package in the sources jar. That issue mentions that the shade plugin "will blindly shade all the source files, including those that are excluded form shading by relocation rules", which tells me that in that case it at least adds the sources to the jar, but it ignores the relocation rules when rewriting the imports.

Anyway, searching for solutions I came across other reported issues with the shade plugin, so maybe it is not worthed to spend more time with it. Is there still a need in netty for shading JCTools? What is the exact conflict that shading is trying to address? (I am new to netty and I was not able to find the reason explained in other threads.) I wonder if I could instead make my own netty build that would pull JCTools as an eternal dependency rather than shading it. 

In the meantime I am left with manually inspecting the JCTools code. :)

Thanks!

**Comment by normanmaurer** [comment]
@cstancu its because netty core aims to be zero dependency.
