### ISSUE TITLE
CORSHandler closing WebSocket Connection

### ISSUE THREAD

**Issue by FelixMarcus** [netty/netty#6645]
Using Netty 4.1.9.Final, Java 8

We have one Netty pipeline processing both websocket and http connections on the same port filtering through SimpleChannelInboundHandler entensions. We can send both websocket and http requests and they are separately and correctly processed and responded to.

This works fine until we add a CorsHandler to the pipeline (for the http requests). Then, all WS connections are closed before the handshake can even complete. 

The pipeline is simple enough: 

```
ch.pipeline().addLast(
                                    new LoggingHandler(),
                                    new HttpServerCodec(),
                                    new HttpObjectAggregator(262144),
                                    new WebSocketServerProtocolHandler("/", null, true, 262144),
                                    webSocketServer extends SimpleChannelInboundHandler<WebSocketFrame>,
                                    //new CorsHandler(corsConfig),
                                    httpServer extends SimpleChannelInboundHandler<FullHttpRequest>);
```

Removing the CorsHandler line comment will result in the issue.

Sending a websocket request will result in seeing : 
`
WebSocket connection to 'ws://HOST:PORT/' failed: Connection closed before receiving a handshake response in the browser network `

NB, neither of the SimpleChannelInboundHandlers call fireChannelRead(), so I'm surprised that the CorsHandler even is reached, but it still makes all the difference.

It looks like the CorsHandler is adding a listener to close the connection if the message is not keep-alive, which we aren't guaranteeing at this time.

**Comment by FelixMarcus** [comment]
Further investigation has revealed the source of the problem. 

Websocket protocol requires a handshake message be sent back to the client. This message is sent by the WebSocketServerProtocolHandshakeHandler and its constituents up the pipeline from the base to the source, passing through the entire pipeline to the transport point (not as originally believed by the poster from the point where the protocol handler to transport). Thus the handshake message passes through the CorsHandler.

The CorsHandler assumes that it has received an incoming request for every outgoing response. In this case, it has not. When attempting to setOrigin (CorsHandler.java:98), a call is made to get the origin of the incoming message. This results in a null pointer exception being thrown, cancelling the handshake message and causing the websocket connection to fail. 

N.B. This exception is also swallowed silently by the handshake protocol handler. No explicit message is returned to the client regarding the failure of the initial websocket connection request.

**Comment by Scottmitch** [comment]
Is it possible to put the `CorsHandler` in the pipeline after the handshake has completed?

**Comment by FelixMarcus** [comment]
A runtime insertion? That is a workaround, yes. 

Given that we could be getting either a WS connection (No ```CorsHandler``` needed) or an HTTP connection (```CorsHandler``` definitely needed), then we could have an additional helper after the codec that inserts the ```CorsHandler``` depending on the instance type. Similar to what we've implemented in the meantime.

Doesn't solve the actual bug though, i.e. crashing the connection when a ```CorsHandler``` exists for a handshake, nor does it seem like a viable solution that can be put it into the framework (requires a third handler immediately after your codec). 

Perhaps the ```CorsHandler``` could be adapted so that it makes that check and adds/removes itself from the pipeline as necessary to stop the error in question from occurring? 

Alternatively, the ```HandshakeHandler``` checking for and removing the ```CorsHandler``` when handshaking? Not so sure about this given the cross handler coupling it introduces.

A less elegant yet simpler and more obvious solution is just for the ```CorsHandler``` to check if any incoming message is a handshake and ignore if it is. I'd have concerns regarding the naivety of this solution though. Sticking appropriate headers on any message could allow it to bypass the CORS validation...

**Comment by Scottmitch** [comment]
Can you provide more context why you think this is a bug? The loose coupling with higher level logic that controls the pipeline contents seems like a feature. What if the handshake happens after the CorsHandler removes itself?

**Comment by FelixMarcus** [comment]
Sorry Scott, should have been clearer. 

When I refer to a bug, I mean that the CorsHandler is throwing a NullPointerException that is being swallowed silently and is closing the handshake connection before it leaves the server pipeline. This is unexpected behaviour, it seems, whether the designers believe the `CorsHandler `and `WebSocketHandshakeHandler ` should be coexisting or not.

From my point of view, it makes sense to be able to run a Corshandler alongside a websocket handshake handler. Currently, when the two exist in tandem on a pipeline and a websocket connection is requested, one blocks the other from functioning properly. This may be according to design, but it doesn't seem documented anywhere that I've seen. If this is a feature of the framework, then it seems it should be at least be stated in the log that the handshake is being specifically dropped and what to do to avoid the issue, no? 



---

With regards to the suggestion that I made regarding the CorsHandler altering its existent in the pipeline, I was considering whether the CorsHandler could alter the pipeline dynamically as a request comes in. This is an extension of what you were suggesting, I believe, that the CorsHandler is added after the handshake is completed. 

A request comes in, and hits the CorsHandler. If it is something that should be Cors aware, then a second handler is added after the current one that actually does any request/response checks (that are causing the NPE to be thrown); else if, for example, the request is an initial WS connection request, then nothing is added to the pipeline and the handshakeHandler continues on as normal.

I suggest this approach so that the CorsHandler remains self-controlling, instead of forcing users to implement extra logic, i.e. having diagnosed the problems for themselves, they then have to write their own custom handler to perform this manipulation further up the pipeline. It's possible that this isn't a feasible approach, but I feel that the problem is one worth addressing. I was merely putting my own thoughts on the topic as I think out a possible solution. Let me know if there are any flaws that you can think of.

**Comment by normanmaurer** [comment]
Can you show us the stacktrace of the NPE?

**Comment by Scottmitch** [comment]
Swallowing a NPE sounds undesirable. If you could submit a unit test for this that would be great. I'm still not clear on the approach and the amount of coupling required. Are you are suggesting another handler todo the orchestration or is this something the Cors handler can do in isolation,  without prematurely removing itself in situations other than the one you describe?

**Comment by normanmaurer** [comment]
Will close as there was no respond for a year... Please reopen if you still think there is an issue
