### ISSUE TITLE
SIGILL on OSX when using io.netty:netty-tcnative-boringssl-static:1.1.33.Fork26

### ISSUE THREAD

**Issue by vkedia** [netty/netty#6646]
### Actual behavior
We got a SIGILL while using a client (Google Cloud Spanner Client) that depends on io.netty:netty-tcnative-boringssl-static:1.1.33.Fork26 . SIGILL seems to come from the native tcnative library.
Here is the error report and the stack trace of the relevant thread:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x000000011b9f5ec0, pid=1869, tid=0x0000000000007903                            
#
# JRE version: Java(TM) SE Runtime Environment (8.0_101-b13) (build 1.8.0_101-b13)                    
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.101-b13 mixed mode bsd-amd64 compressed oops)        
# Problematic frame:
# C  [libnetty-tcnative-osx-x86_641800715405814754196.dylib+0xeeec0]  CRYPTO_memcmp+0xb0 
```

```
Stack: [0x000070000273a000,0x000070000283a000],  sp=0x00007000028387f0,  free space=1017k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libnetty-tcnative-osx-x86_641800715405814754196.dylib+0xeeec0]  CRYPTO_memcmp+0xb0
C  [libnetty-tcnative-osx-x86_641800715405814754196.dylib+0x77ee2]  X25519+0x22
C  [libnetty-tcnative-osx-x86_641800715405814754196.dylib+0x28182]  ssl_x25519_accept+0xb2
C  [libnetty-tcnative-osx-x86_641800715405814754196.dylib+0x17f40]  ssl3_connect+0xec0
C  [libnetty-tcnative-osx-x86_641800715405814754196.dylib+0x2a520]  ssl_read_impl+0x80
j  org.apache.tomcat.jni.SSL.readFromSSL(JJI)I+0
j  io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(Ljava/nio/ByteBuffer;)I+37
j  io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap([Ljava/nio/ByteBuffer;II[Ljava/nio/ByteBuffer;II)Ljavax/net/ssl/SSLEngineResult;+732
j  io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap([Ljava/nio/ByteBuffer;[Ljava/nio/ByteBuffer;)Ljavax/net/ssl/SSLEngineResult;+9
j  io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(Lio/netty/handler/ssl/SslHandler;Lio/netty/buffer/ByteBuf;IILio/netty/buffer/ByteBuf;)Ljavax/net/ssl/SSLEngineResult;+59
j  io.netty.handler.ssl.SslHandler.unwrap(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;II)Z+38
j  io.netty.handler.ssl.SslHandler.decode(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;Ljava/util/List;)V+194
j  io.netty.handler.codec.ByteToMessageDecoder.callDecode(Lio/netty/channel/ChannelHandlerContext;Lio/netty/buffer/ByteBuf;Ljava/util/List;)V+58
j  io.netty.handler.codec.ByteToMessageDecoder.channelRead(Lio/netty/channel/ChannelHandlerContext;Ljava/lang/Object;)V+81
j  io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Ljava/lang/Object;)V+16
j  io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Lio/netty/channel/AbstractChannelHandlerContext;Ljava/lang/Object;)V+31
j  io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(Ljava/lang/Object;)Lio/netty/channel/ChannelHandlerContext;+5
j  io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(Lio/netty/channel/ChannelHandlerContext;Ljava/lang/Object;)V+2
j  io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Ljava/lang/Object;)V+16
j  io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(Lio/netty/channel/AbstractChannelHandlerContext;Ljava/lang/Object;)V+31
j  io.netty.channel.DefaultChannelPipeline.fireChannelRead(Ljava/lang/Object;)Lio/netty/channel/ChannelPipeline;+5
j  io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read()V+127
j  io.netty.channel.nio.NioEventLoop.processSelectedKey(Ljava/nio/channels/SelectionKey;Lio/netty/channel/nio/AbstractNioChannel;)V+119
j  io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized([Ljava/nio/channels/SelectionKey;)V+38
j  io.netty.channel.nio.NioEventLoop.processSelectedKeys()V+15
j  io.netty.channel.nio.NioEventLoop.run()V+126
j  io.netty.util.concurrent.SingleThreadEventExecutor$5.run()V+44
j  io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run()V+4
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x2ecf06]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x6ae
V  [libjvm.dylib+0x2ed694]  JavaCalls::call_virtual(JavaValue*, KlassHandle, Symbol*, Symbol*, JavaCallArguments*, Thread*)+0x164
V  [libjvm.dylib+0x2ed840]  JavaCalls::call_virtual(JavaValue*, Handle, KlassHandle, Symbol*, Symbol*, Thread*)+0x4a
V  [libjvm.dylib+0x348029]  thread_entry(JavaThread*, Thread*)+0x7c
V  [libjvm.dylib+0x5695ab]  JavaThread::thread_main_inner()+0x9b
V  [libjvm.dylib+0x56ac98]  JavaThread::run()+0x1c2
V  [libjvm.dylib+0x48933a]  java_start(Thread*)+0xf6
C  [libsystem_pthread.dylib+0x399d]  _pthread_body+0x83
C  [libsystem_pthread.dylib+0x391a]  _pthread_body+0x0
C  [libsystem_pthread.dylib+0x1351]  thread_start+0xd
C  0x0000000000000000
```

To me this seems like an incorrect version of the native library is somehow being used. We looked at the maven dependencies of our project and we are only including one version of tcnative.

### Netty version
4.1.8 Final
### JVM version (e.g. `java -version`)
JRE version: Java(TM) SE Runtime Environment (8.0_101-b13) (build 1.8.0_101-b13)                    
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.101-b13 mixed mode bsd-amd64 compressed oops)  

### OS version (e.g. `uname -a`)
OSX

**Comment by normanmaurer** [comment]
hmmm... Seems like it "dies" in `CRYPTO_memcmp+0xb0 ` which comes from boringssl. @davidben any idea ?

**Comment by davidben** [comment]
Does macOS trigger SIGILL only on an actual illegal instruction or is it also for things like segfaults? `CRYPTO_memcmp` isn't written in assembly or anything, but maybe the compiler did something.

You all produce precompiled things right? How would I get a copy of libnetty-tcnative-osx-x86_641800715405814754196.dylib to see what instructions are at those addresses? (Sorry, I am totally unfamiliar with how Java things are distributed.)

**Comment by normanmaurer** [comment]
@davidben just unpack http://repo1.maven.org/maven2/io/netty/netty-tcnative-boringssl-static/2.0.1.Final/netty-tcnative-boringssl-static-2.0.1.Final.jar . you will find these in the "META-INF/native folder

**Comment by davidben** [comment]
Thanks! http://repo1.maven.org/maven2/io/netty/netty-tcnative-boringssl-static/1.1.33.Fork26/netty-tcnative-boringssl-static-1.1.33.Fork26-osx-x86_64.jar but yeah, that matches the stack trace.

Looks like the compiler is actually vectorizing that loop and sticking a `pmovzxbd` instruction in there. Huh. If you're getting a `SIGILL`, I'm guessing `netty-tcnative-boringssl-static-1.1.33.Fork26-osx-x86_64.jar` was built targeting newer hardware than you have? That's an SSE 4.1 instruction.

@vkedia What hardware are you running this on? This page lists when SSE 4.1 was added to Macs.
https://en.wikipedia.org/wiki/List_of_Macintosh_models_grouped_by_CPU_type#Penryn

@normanmaurer Do you know how that file was built? The compiler seems to have been told that SSE 4.1 is fair game. Dunno if that was intentional.

**Comment by davidben** [comment]
Ah, looks like `clang` (on a Mac at least) will just assume SSE 4.1 is available by default.

**Comment by jprante** [comment]
Reporter states `OSX` which seems not up-to-date with current macOS Sierra, and macOS Sierra requires SSE 4.1.

**Comment by vkedia** [comment]
Thanks for looking into this. I will find out what hardware was this.

**Comment by vkedia** [comment]
Do you know if there is a way to check on the machine, if SSE 4.1 is available?

**Comment by normanmaurer** [comment]
@jprante @davidben ^^

**Comment by jprante** [comment]
By typing the command

> sysctl machdep.cpu.features

Macs will return the CPU flags and will print if SSE4.1 is supported. Example:

> machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C

**Comment by vkedia** [comment]
This is the output of that command on my machine:
```
vikask-macbookpro1:annotations vikask$ sysctl machdep.cpu.features
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C
```

**Comment by normanmaurer** [comment]
Please update to the latest version and reopen if you still see the problem. Thanks!
