### ISSUE TITLE
The role of wakenUp and oldWakenUp variables in NioEventLoop class

### ISSUE THREAD

**Issue by joyyiwei** [netty/netty#6649]
NioEventLoop wakenUp and oldWakenUp seemingly useless, because the hasTasks () method has been able to meet the needs of

**Comment by normanmaurer** [comment]
Please write in english...

**Comment by joyyiwei** [comment]
This problem is bothering me, can you help me to explain it?

**Comment by johnou** [comment]
@joyyiwei did you read through the code comments? https://github.com/netty/netty/blob/0692bf1b6a6764dee22132630bef7ee2f850771e/transport/src/main/java/io/netty/channel/nio/NioEventLoop.java#L410-L436 if you think you're able to improve it please feel free to create a pull request with an optimized version + benchmarks.

**Comment by joyyiwei** [comment]
@johnou yes ,but I think hasTasks () this method can also be done to repair the external thread to wake up again, whether it is left to do the expansion, the two variables

**Comment by normanmaurer** [comment]
@trustin you wrote this... can you comment ?

**Comment by normanmaurer** [comment]
@trustin ping

**Comment by normanmaurer** [comment]
Sorry but I still get what the issue is ... Please re-open with more details if you still think there is any issue
