### ISSUE TITLE
Misleading comment in `ServerBootstrap`

### ISSUE THREAD

**Issue by herberteuler** [netty/netty#6652]
The mechanism of registering handlers seems to have been changed since #5566 has been fixed, making [this](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/bootstrap/ServerBootstrap.java#L178) comment misleading.

I did not have time to inspect the whole history, but the user's `initChannel` is now not called after the current invocation returns. As an evidence, the code patched with the following change on tag `4.1.9.Final` also passes [this test case](https://github.com/netty/netty/blob/4.1/transport/src/test/java/io/netty/bootstrap/ServerBootstrapTest.java#L81), which was introduced to ensure that #5566 was fixed.

```
$ git diff
diff --git a/transport/src/main/java/io/netty/bootstrap/ServerBootstrap.java b/transport/src/main/java/io/netty/bootstrap/ServerBootstrap.java
index f9042af46..b73239ffa 100644
--- a/transport/src/main/java/io/netty/bootstrap/ServerBootstrap.java
+++ b/transport/src/main/java/io/netty/bootstrap/ServerBootstrap.java
@@ -174,7 +174,9 @@ public class ServerBootstrap extends AbstractBootstrap<ServerBootstrap, ServerCh
                 if (handler != null) {
                     pipeline.addLast(handler);
                 }
-
+                pipeline.addLast(new ServerBootstrapAcceptor(
+                        ch, currentChildGroup, currentChildHandler, currentChildOptions, currentChildAttrs));
+                /*
                 // We add this handler via the EventLoop as the user may have used a ChannelInitializer as handler.
                 // In this case the initChannel(...) method will only be called after this method returns. Because
                 // of this we need to ensure we add our handler in a delayed fashion so all the users handler are
@@ -185,7 +187,7 @@ public class ServerBootstrap extends AbstractBootstrap<ServerBootstrap, ServerCh
                         pipeline.addLast(new ServerBootstrapAcceptor(
                                 ch, currentChildGroup, currentChildHandler, currentChildOptions, currentChildAttrs));
                     }
-                });
+                });*/
             }
         });
     }
```

Please consider changing the comment, it could be very confusing for newcomers.

### Expected behavior

N/A

### Actual behavior

N/A

### Steps to reproduce

N/A

### Minimal yet complete reproducer code (or URL to code)

N/A

### Netty version

4.1.9.Final

### JVM version (e.g. `java -version`)

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### OS version (e.g. `uname -a`)
 
Linux herberteuler 4.9.22 #1-NixOS SMP Wed Apr 12 10:41:42 UTC 2017 x86_64 GNU/Linux

**Comment by Underbalanced** [comment]
@herberteuler Would you be able to make the changes and put in a PR if what you say is accurate? Contributions are welcome!

**Comment by herberteuler** [comment]
Alright, so I have investigated further and found that it was `ChannelInitializer` that was changed to make this comment inaccurate. The change was introduced by 26aa348, in which `initChannel` was also invoked from `handlerAdded` to ensure the correct order. I will create a pull request soon.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6656#pullrequestreview-35908160
