### ISSUE TITLE
Websocket use ssl failed Error in connection establishment: net::ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by huigesv123** [netty/netty#6661]
this is code in my server

`public class WebsocketInitializer extends
		ChannelInitializer<SocketChannel> implements Constant{

    private String tlsMode;
    
    private static final String CA_JKS_PATH = "smartcloud.jks";

    public WebsocketInitializer(String TLS_MODE) {
    	tlsMode = TLS_MODE;
    }
	
	@Override
	protected void initChannel(SocketChannel ch) throws Exception {
	
		ChannelPipeline pipeline = ch.pipeline();
		
		SSLEngine engine = null;
		if (SSLMODE.CA.toString().equals(tlsMode)) {
		    engine = SmartCloudSslContextFactory
			    .getServerContext(
				    tlsMode,
				    CA_JKS_PATH,
				    null).createSSLEngine();
		} 

		
	pipeline.addLast(SSL_HANDLER_NAME, new SslHandler(engine));
	pipeline.addLast(HTTP_SERVER_CODEC_HANDLE_NAME, new HttpServerCodec());
        pipeline.addLast(HTTP_OBJECT_AGGREGATOR_HANDLE_NAME, new HttpObjectAggregator(65536));
        pipeline.addLast(WEBSOCKET_SERVERCOMPRESSION_HANDLER_NAME, new WebSocketServerCompressionHandler());
        pipeline.addLast(WEBSOCKET_SERVERPROTOCOL_HANDLER_NAME, new WebSocketServerProtocolHandler(WEBSOCKET_PATH, null, true));
       
	pipeline.addLast(TEMP_TIMEOUT_HANDLER_NAME, new CustomReadTimeHander(TEMP_READ_TIMEOUT));
	pipeline.addLast(ENCODE_BINARY_HANDLER_NAME, new SmartMsgWebsocketEncoder());
	pipeline.addLast(ENCODE_HANDLER_NAME, new WebSocket13FrameEncoder(false));
        pipeline.addLast(DECODE_HANDLER_NAME, new SmartCloudWebsocketFrameDecoder());
	pipeline.addLast(LOGIN_AUTH_RESP_HANDLER, new LoginAuthRespHandler(USER_CONNECT.WEBSOCKET));
	}

}`

I use javascript to connect the webserver, but it doesn't work. and it show '' failed Error in connection establishment: net::ERR_CONNECTION_CLOSED""IsTrusted:true" in Chrome 58
`Websocket websocket = new Websocket('wss://rubycomet.vanwardsmart.com:2301/ws')`; 

4.1.8.Final

Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux Centos7

**Comment by normanmaurer** [comment]
Without more debug info its impossible to help. Anything propagated to `exceptionCaught(...)` ?

**Comment by huigesv123** [comment]
in WebSocketServerProtocolHandler exceptionCaught method, I got a error -->" Client/Server mode not yet set" @normanmaurer

**Comment by normanmaurer** [comment]
Please show me the stacktrace

**Comment by huigesv123** [comment]
I have changed my ca cert in my jks file and "engine.setUseClientMode(false);" ,then fix it.

However, i have a problem. The exceptionCaught  of WebSocketServerProtocolHandler class does not fireException to next handler.......so I can not find problem before.....

**Comment by normanmaurer** [comment]
@huigesv123 can you provide a full reproducer ?
