### ISSUE TITLE
UnsatisfiedLinkError: how to shade native

### ISSUE THREAD

**Issue by MarcMagnin** [netty/netty#6665]
### Expected behavior
Uses Channel from gRPC with Unix Domain Sockets

### Actual behavior
Throwable is launched:
```
java.lang.UnsatisfiedLinkError: io.netty.shadednetty.channel.epoll.NativeStaticallyReferencedJniMethods.epollin()I
        at io.netty.shadednetty.channel.epoll.NativeStaticallyReferencedJniMethods.epollin(Native Method) ~[app-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at io.netty.shadednetty.channel.epoll.Native.<clinit>(Native.java:69) ~[app-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at io.netty.shadednetty.channel.epoll.IovArray.<clinit>(IovArray.java:57) ~[app-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at io.netty.shadednetty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:54) ~[app-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
...
java.lang.NoClassDefFoundError: Could not initialize class io.netty.shadednetty.channel.epoll.IovArray
        at io.netty.shadednetty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:54) ~[app-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at io.netty.shadednetty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:134) ~[app-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
        at io.netty.shadednetty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:35) ~[app-1.0-SNAPSHOT.jar:1.0-SNAPSHOT]
...
```
### Steps to reproduce
``` java 
Channel channel = NettyChannelBuilder.forAddress(new DomainSocketAddress("/tmp/somesoscket.socket"))
                .eventLoopGroup(new EpollEventLoopGroup())
                .channelType(EpollDomainSocketChannel.class)
                .usePlaintext(true)
                .build();
```

### Netty version
4.1.8
### gRPC version
1.2.0

### JVM version (e.g. `java -version`)
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

### OS version (e.g. `uname -a`)
Linux MarcUbuntu16 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

My netty dependencies are (gradle project):
`compile 'io.netty:netty-all:4.1.8.Final'`
`compile 'io.netty:netty-transport-native-epoll:4.1.8.Final:linux-x86_64'`

I'm shading io.netty to io.netty.shadednetty using shadow plugin as I have other netty dependencies in the project.
Most of the strings in /tmp/libnetty-transport-native-epollxxxxxxxxx.so looks like:
```
Java_io_netty_channel_unix_FileDescriptor_writeAddress
Java_io_netty_channel_epoll_Native_sizeofEpollEvent
Java_io_netty_channel_unix_Socket_getReceiveBufferSize
Java_io_netty_channel_epoll_Native_splice0
Java_io_netty_channel_unix_Errors_errnoEWOULDBLOCK
Java_io_netty_channel_epoll_Native_setTcpNotSentLowAt
Java_io_netty_channel_epoll_Native_epollin
Java_io_netty_channel_unix_Socket_isKeepAlive
```
where they should look like: 
```
Java_io_netty_shadednetty_channel_unix_FileDescriptor_writeAddress
Java_io_netty_shadednetty_channel_epoll_Native_sizeofEpollEvent
Java_io_netty_shadednetty_channel_unix_Socket_getReceiveBufferSize
Java_io_netty_shadednetty_channel_epoll_Native_splice0
Java_io_netty_shadednetty_channel_unix_Errors_errnoEWOULDBLOCK
Java_io_netty_shadednetty_channel_epoll_Native_setTcpNotSentLowAt
Java_io_netty_shadednetty_channel_epoll_Native_epollin
Java_io_netty_shadednetty_channel_unix_Socket_isKeepAlive
```

Any help about shading this would be great!

**Comment by johnou** [comment]
@MarcMagnin check out the io.netty.packagePrefix system property.

**Comment by johnou** [comment]
https://github.com/netty/netty/commit/075a54af3e607c20eeaf7809a2a08602abd5d735

**Comment by MarcMagnin** [comment]
Cheers, I've been looking at https://github.com/netty/netty/issues/4800 but I can't get this to work yet.

**Comment by MarcMagnin** [comment]
all good, 
With `relocate 'io.netty', 'shade.io.netty'`, it needed a `System.setProperty("shade.io.netty.packagePrefix", "shade.");` and a rename of `META-INF/native/lib-netty-transport-native-epoll.so` to `META-INF/native/libshade-netty-transport-native-epoll.so`

**Comment by Scottmitch** [comment]
Sorry for the delay ... but sounds like you got it. You need to set the system property and relocate the native library to match (to be sure we load the "correct" native library instead of potentially some other library).

**Comment by MarcMagnin** [comment]
No worries. Basically I was stuck because of the most nightmarish problem: I was setting `System.setProperty("shade.io.netty.packagePrefix", "shade");` instead of `System.setProperty("shade.io.netty.packagePrefix", "shade.");`.
This type of issue took days of my life already : )

**Comment by johnou** [comment]
@MarcMagnin feel free to contribute to the wiki, you might save others!
