### ISSUE TITLE
Add update method to HashedWheelTimer Timeout

### ISSUE THREAD

**Issue by yuyijq** [netty/netty#6669]
Add update method to HashedWheelTimer Timeout, so we can reuse Timeout object many times ,avoid new objects.
`
Timeout t = timer.newTimeout(task, 10, TimeUnit.Seconds);
`
If I want to delay this timeout, I must cancel this timeout, if Timeout has an update method, we can do it like this:
`
t.update(10, TimeUnit.Seconds);
`

**Comment by normanmaurer** [comment]
No we not support this and I think its not worth it in general
