### ISSUE TITLE
ProxyHandler.connectFuture and its execution order

### ISSUE THREAD

**Issue by vkostyukov** [netty/netty#6671]
As you probably aware, Finagle has adopted `ProxyHandler` in its Netty 4 implementation (see [Netty4ProxyConnectHandler](https://github.com/twitter/finagle/blob/develop/finagle-netty4/src/main/scala/com/twitter/finagle/netty4/proxy/Netty4ProxyConnectHandler.scala)) and it works just great for us, besides one quite surprising behavior its API exposes.

We've recently discovered that `ProxyHandler.connectFuture` [gets notified/satisfied before it removes its underlying proxy codec pieces from the pipeline](https://github.com/netty/netty/blob/4.1/handler-proxy/src/main/java/io/netty/handler/proxy/ProxyHandler.java#L290-L298), which means any possible subsequent write, triggered on `connectFuture.onSuccess` (which I would assume quite an intuitive way of using that future) will fail given the pipeline is malformed. Normally, we'd assume that `ProxyHandler` will queue those wires and drain them later when the pipeline is cleaned up. Although, this is not what exactly happens since when the connect is finished (we set that flag before notifying the listeners) [we just bypass outbound messages](https://github.com/netty/netty/blob/4.1/handler-proxy/src/main/java/io/netty/handler/proxy/ProxyHandler.java#L397-L399). Simply speaking, the following would never work (sorry for Scala):

```scala
proxyHandler.connectFuture.addListener(new GenericFutureListener[NettyFuture[Channel]] {
  override def operationComplete(future: NettyFuture[Channel]): Unit = {
    if (future.isSuccess) {
      ctx.write(something) // will fail since proxyHandler's codec is still in the pipeline
    }
}
```

This is slightly misleading so I suggested we either:

 - document it
 - run the promise **after** we remove the proxy codec

I'm happy to open a PR as usual (with docs or the fix). What do you think about that?

PS: We've workaround that by running `ctx.wirte` in the event loop (`ctx.executor.schedule()`) such that it's queued.

**Comment by normanmaurer** [comment]
let me fix it by notify the promise after removal :)

**Comment by normanmaurer** [comment]
@vkostyukov please check https://github.com/netty/netty/pull/6672

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6672

**Comment by vkostyukov** [comment]
Thanks a lot, @normanmaurer for such a quick turn around!

**Comment by normanmaurer** [comment]
@vkostyukov np... thanks for reporting ! :)
