### ISSUE TITLE
Netty BOM inherit from parent and its own dependency management

### ISSUE THREAD

**Issue by snicoll** [netty/netty#6674]
A BOM was recently added in #5994 but is not valid.

A BOM should only expose dependency management for the artifacts that the project produces (so in this case, netty artifacts). It should not have an opinion about third party dependencies (otherwise including that BOM in a project potentially overrides decisions that were made about them).

One way to fix that would be to stop inheriting from `netty-parent`. Also, I'd set the version of each dependency in the bom rather than using `${project.version}`. If you're including the bom for netty X.Y.Z, it should be X.Y.Z. and nothing else (Maven does not allow to override that property, which is good so it's not strictly necessary but the intent is more clear if you hardcode the current version).

Here is an example of BOM for reference: http://repo.spring.io/release/org/springframework/spring-framework-bom/4.3.8.RELEASE/spring-framework-bom-4.3.8.RELEASE.pom

We'd like to [use this bom in Spring Boot](https://github.com/spring-projects/spring-boot/issues/8553) but we can't for that reason.

**Comment by johnou** [comment]
I'll fix this as it was my doing.

**Comment by johnou** [comment]
@snicoll by removing the reference to the parent the version of the bom artifact is no longer updated when the version is bumped via Maven plugins, I will check into this soon.

**Comment by snicoll** [comment]
@johnou you can use the `oss-parent` (you'll have to add a few more details to the pom so that you can publish it to Maven central anyway).

**Comment by johnou** [comment]
@jasontedor I see that the recent artifact you contributed (netty-dev-tools) uses oss-parent instead of netty-parent, do you know if the artifact version for netty-dev-tools will be incremented as part of the release / deploy cycle? At least with my local tests using versions:set -DnewVersion=.. it is not updated.

**Comment by johnou** [comment]
to answer myself I believe the answer is yes, just tested with the following.. mvn --batch-mode release:update-versions -DdevelopmentVersion=4.1.11.Final-SNAPSHOT

**Comment by jasontedor** [comment]
Yes, you got it.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6676
