### ISSUE TITLE
Improve warning when native libraries extracted to volume with `noexec` set

### ISSUE THREAD

**Issue by mkw** [netty/netty#6678]
### Expected behavior

A Docker-version of our application suddenly failed to work when the `--tmpfs` flag was added to the Docker run command.  Digging into the cause resulted in a surprise that this causes Docker to mount the temp directory with `noexec`; the Netty stack trace (below) does clearly report the `failed to map segment from shared object` error, but this is a bit ambiguous to anyone who did not expect Docker to do this.  Given how popular containers in general, and Docker in particular, has gotten, it seems appropriate to try to log a better message.

### Actual behavior

Only warning is:

```
java.lang.UnsatisfiedLinkError: /tmp/libnetty-transport-native-epoll5589732826809244917.so: /tmp/libnetty-transport-native-epoll5589732826809244917.so: failed to map segment from shared object: Operation not permitted
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) ~[?:1.8.0_121]
	at java.lang.Runtime.load0(Runtime.java:809) ~[?:1.8.0_121]
	at java.lang.System.load(System.java:1086) ~[?:1.8.0_121]
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36) ~[netty-common-4.1.9.Final.jar!/:4.1.9.Final]
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:259) ~[netty-common-4.1.9.Final.jar!/:4.1.9.Final]
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226) ~[netty-common-4.1.9.Final.jar!/:4.1.9.Final]
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:269) ~[netty-transport-native-epoll-4.1.9.Final-linux-x86_64.jar!/:4.1.9.Final]
	at io.netty.channel.epoll.Native.<clinit>(Native.java:64) ~[netty-transport-native-epoll-4.1.9.Final-linux-x86_64.jar!/:4.1.9.Final]
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:33) ~[netty-transport-native-epoll-4.1.9.Final-linux-x86_64.jar!/:4.1.9.Final]
        at ... (truncated for brevity)
```

### Steps to reproduce

Attempt to use epoll or OpenSSL (any version) with the temp directory set to a volume with `noexec` set.

### Netty version

4.1.9

### JVM version (e.g. `java -version`)

8u121 (should not matter)

### OS version (e.g. `uname -a`)

Any flavor of unix supporting volumes with `noexec`.

### Proposed improvement

Add an explicit warning and suggested use of `-Dio.netty.native.workdir=...` when the extracted native library is readable and fails to load with `failed to map segment from shared object`.  This would also address netty/netty-tcnative#264, where this issues was first discovered (when the bundled boringssl library failed to load; error is the same for epoll above).

I'm waiting on my company to sign the contributor agreement before I submit a PR, but the following trivial snippet, added as a catch block in `io.netty.util.internal.NativeLibraryLoader#load`, fixes it:

```java
        } catch (UnsatisfiedLinkError e) {
            // Linux will clearly state that the operation is not permitted when
            // the temp directory is mounted with the "noexec" option (common in
            // secure environments and the default for Docker's --tmpfs option).
            try {
                if (!isWindows() && tmpFile.isFile() && tmpFile.canRead() &&
                    e.getMessage().matches(".*failed to map segment from shared object.*")) {
                    logger.info("{} exists and is readable but cannot be loaded; volume mounted with noexec? " +
                                " Use -Dio.netty.native.workdir=[path] to set native working directory separately.",
                                tmpFile.getPath());

                }
            } catch (Throwable t) {
                // Ignore
            }
            // Re-throw to fail the load
            throw e;
```

**Comment by Scottmitch** [comment]
I'm all for making exception messages more informative, however my preference is to avoid doing inspection of exception messages. Inspecting the string portion of exceptions is fragile and subject to fail.

**Comment by mkw** [comment]
Well, I agree with that.  Unfortunately, the only non-message-parsing (not calling these better) solutions that I know of are:

1. Invoking "mount" and parsing the results
2. Attempting to read the mount information off the filesystem
3. Lots of reflection to get to and invoke `sun.fs.nio.UnixMountEntry#getOption(String)`

I have a patch doing number 3 in the list above that I'll submit as a PR in a few minutes.  Arguably, the reflection should be done in`io.netty.util.internal.PlatformDependent` instead of in a static inner class (to lazy initialize) of `io.netty.util.internal.NativeLibraryLoader`.

**Comment by normanmaurer** [comment]
@mkw I would prefer to not use reflection if possible as this will fail on java9 :(

**Comment by mkw** [comment]
Doh!  I literally just pushed a reflective version with a comment indicating that `--add-opens java.base/sun.nio.fs=...` is required for Java 9.  Would you prefer message parsing?  That's certainly simpler, but does depend on the message from the Kernel not changing (and I can't easily test it on anything but a handful of linux flavors).

**Comment by normanmaurer** [comment]
@mkw maybe its ok if we just try to do it and "silently" fail if we can not do the reflection hack. Kind of best-effort.

**Comment by mkw** [comment]
Definitely a best-effort warning.  I'm locally testing suppressing the stack trace from the `java.lang.reflect.InaccessibleObjectException` exception and instead suggesting the `--add-opens java.base/sun.nio.fs=...` flag if initialization fails.  This will only happen 1 on startup, and it's logged at debug.  Will push once I confirm that it works.

**Comment by normanmaurer** [comment]
We did this but forgot to close the issue...
