### ISSUE TITLE
Metrics for HashedWheelTimer

### ISSUE THREAD

**Issue by vkostyukov** [netty/netty#6681]
Netty's `HashedWheelTimer` is great but it's really hard to observe it's state given it's all private. Historically, we've been using reflection to get access to timer's private fields and expose some primitive metrics like "number of pending tasks".

Would you be open to introducing `HashedWheelTimer.pendingTasks` as the first step towards better observability story for Netty timers? I'm not sure we need something as complex as `PoolArenaMetric` (by analogy with allocators) but having at least `pendingTasks` will go a long way in providing a reasonable level of visibility into timer's internal state.

I'm happy to open a PR that adds this method (presumably based on our internal version of it) if you think it's something we can add as a public API. Please, let me know.

**Comment by normanmaurer** [comment]
@vkostyukov sounds good to me.

**Comment by vkostyukov** [comment]
Thanks, @normanmaurer! I opened #6682, please take a look.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6682
