### ISSUE TITLE
native binary for DPDK 

### ISSUE THREAD

**Issue by JatinderSingh** [netty/netty#6683]
Some networking frameworks have got a significant boost in throughput using http://dpdk.org/
https://en.wikipedia.org/wiki/Data_Plane_Development_Kit. Will using above library for driver based optimizations improve throughput of netty as well? What changes would be needed for this?

**Comment by normanmaurer** [comment]
@JatinderSingh as far as I know you will need to write a new jni based transport for this. So its non-trivial. That said contributions welcome

**Comment by maseev** [comment]
Sorry for bringing up this closed issue. What would be the best way to implement a new native transport for Netty? I mean, if I needed to implement a new type of transport which would use, let's say, [DPDK](http://www.dpdk.org/) or [FD](https://fd.io/), what would be the best way to integrate one of these libraries with Netty? Any recommendations?

**Comment by normanmaurer** [comment]
Just write a new Transport as what we have done with the Linux epoll transport. Not sure I get what you are asking for

**Comment by Scottmitch** [comment]
transport-native-kqueue and transport-native-epoll are good places to start looking at what is involved.
