### ISSUE TITLE
SslContextBuilder no longer raising an SSLException 

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#6687]
I have a canary unit test for OPENSSL that is checking for a SSLException being thrown if an attempt is being made to construct an SslContext with valid but mismatching PrivateKey/Certificate.

Please note that the JDK provider doesn't raise a Exception and the new outcome of my canary test could be interpreted either as a bug or feature.

### Expected behavior

```
javax.net.ssl.SSLException: failed to set certificate and key
  at io.netty.handler.ssl.ReferenceCountedOpenSslServerContext.newSessionContext(ReferenceCountedOpenSslServerContext.java:127)
  at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:351)
  at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:335)
  at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:415)
  at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:414)
  at io.netty.handler.ssl.OpenSslContextTest.testExceptionOnMismatch(OpenSslContextTest.java:28)
  Caused by:
  javax.net.ssl.SSLException: failed to set certificate and key
      at io.netty.handler.ssl.ReferenceCountedOpenSslContext.setKeyMaterial(ReferenceCountedOpenSslContext.java:730)
      at io.netty.handler.ssl.ReferenceCountedOpenSslServerContext.newSessionContext(ReferenceCountedOpenSslServerContext.java:112)
      ... 5 more
      Caused by:
      java.lang.Exception: Error setting private key (error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
          at io.netty.internal.tcnative.SSLContext.setCertificateBio(Native Method)
          at io.netty.handler.ssl.ReferenceCountedOpenSslContext.setKeyMaterial(ReferenceCountedOpenSslContext.java:722)
          ... 6 more
```

### Actual behavior

No exception being thrown

### Steps to reproduce

See below

### Minimal yet complete reproducer code (or URL to code)

```java
@Test(expectedExceptions=SSLException.class)
  public void testForException() throws Exception {
    
    SelfSignedCertificate cert1 = new SelfSignedCertificate();
    SelfSignedCertificate cert2 = new SelfSignedCertificate();
    
    try {
      SslContext context = SslContextBuilder.forServer(cert1.certificate(), cert2.privateKey())
        .sslProvider(SslProvider.OPENSSL)
        .build();
      
      ReferenceCountUtil.safeRelease(context);
      fail("This should have failed with an SSLException!");
      
    } finally {
      cert1.delete();
      cert2.delete();
    }
  }
```

### Netty version

Netty 4.1.10.Final+

### JVM version (e.g. `java -version`)

n/a

### OS version (e.g. `uname -a`)

n/a

**Comment by Scottmitch** [comment]
This exception will be raised if you don't have a version of OpenSSL which provides the necessary methods to support the KeyManager interface. You can also simulate this behavior with `-Dio.netty.handler.ssl.openssl.useKeyManagerFactory=false`. Is it possible that your tests were running with an older version of openssl (`<0x10002000`), or if you were previously using the tcnative jar from maven central which uses openssl (which is built against 1.0.1)?

**Comment by rkapsi** [comment]
Running the test with `-Dio.netty.handler.ssl.openssl.useKeyManagerFactory=false` does raise the exception.

I'm pretty sure I've been running w/ OpenSSL 1.0.2.

**Comment by rkapsi** [comment]
@Scottmitch on further thought, what is the benefit of using KeyManagerFactory over straight `SslContext#setKeyMaterial(...)`? It seems the KeyManagerFactory is a bit more costly as it needs to create a KeyStore and do a SPI lookup.

As far as I can tell, the `SslContext#setKeyMaterial(...)` was the old default and my canary test is indirectly telling me that the default has changed and I now need to decide whether I want to use KMF or disable it with the system property :thinking:

**Comment by normanmaurer** [comment]
@rkapsi the advantage is that its a "drop-in" replacement for the JDK implementation, which uses the KeyManagerFactory. Thats it 👍

**Comment by rkapsi** [comment]
:+1: make sense. Closing this ticket.
