### ISSUE TITLE
io.netty.handler.codec.EncoderException: MessageToMessageCodec$1 must produce at least one message.

### ISSUE THREAD

**Issue by mskaric** [netty/netty#6695]
I'm not sure whether this is an error or normal behavior. But i am sure that the error message is misleading.
### Expected behavior
No error
### Actual behavior
io.netty.handler.codec.EncoderException: MessageToMessageCodec$1 must produce at least one message.
### Steps to reproduce
try to write empty string only like this:
ctx.write(new DefaultHttpContent(Unpooled.copiedBuffer("", CharsetUtil.UTF_8)), ctx.voidPromise());

### Netty version
4.1.10
### JVM version (e.g. `java -version`)
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
### OS version (e.g. `uname -a`)
linux 4.4.0-71-generic #92-Ubuntu SMP

**Comment by normanmaurer** [comment]
Can you also show your codec impl or share which included codec was used?

**Comment by mskaric** [comment]
Of course I can Norman. That is the least I can do.
The problem shows itself when I use chunked transfer e.g. I don't use content-length header.
I think the problem is because 0 length chunk should be the last chunk.
My workaround is to check whether business layer is sending 0 length chunk and ignore it completely but I think this solution should be implemented in HttpResponseEncoder class.

 ChannelPipeline p = ch.pipeline();
        if (sslCtx != null) {
            p.addLast(sslCtx.newHandler(ch.alloc()));
        }        
        p.addLast("TIMER", new ReadTimeoutHandler(30));                        
        p.addLast("DECODER",new HttpRequestDecoder());        
        p.addLast("AGGREGATOR",new HttpObjectAggregator(4194304)); //4MB
        p.addLast("ENCODER",new HttpResponseEncoder());        
        p.addLast("COMPRESOR",new WebContentCompressor());        
        p.addLast(dataEventExecutorGroup,new WebServerHandler(handler));

**Comment by mskaric** [comment]
This is the solution I am using:

public void write(ByteBuf buf) {
        **if(buf.writerIndex()==buf.readerIndex())
            return;**
        if (writeResponse) {
            ctx.write(response);
            writeResponse = false;
        }
        ctx.write(new DefaultHttpContent(buf), ctx.voidPromise());
    }

**Comment by leopinho** [comment]
I have the same problem when running websocket Netty 4.1 sample. After the handshake - as it doesn't return any data in the http response body - only headers
https://netty.io/4.1/xref/io/netty/example/http/websocketx/server/package-summary.html

**Comment by leopinho** [comment]
Netty 4.1.11 source code:

io.netty.handler.codec.EncoderException: MessageEncoder must produce at least one message.
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:98)
        ...
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
	at io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker.handshake(WebSocketServerHandshaker.java:194)

**Comment by normanmaurer** [comment]
So you run just the sample and see this? Can you tell me the exact steps how to repro?

**Comment by normanmaurer** [comment]
@mskaric sorry I totally forgot about this... I added two test-cases for what you describe and all works:

https://github.com/netty/netty/pull/7057

can you please let me know what I missed ?

**Comment by mskaric** [comment]
Sorry Norman,
At the moment I am unable to recall where the problem was. I think I
managed to circumvent it somehow but at the moment I am not sure how.


Srdačan pozdrav,

*Milan*

**Comment by normanmaurer** [comment]
Ok let me close this then for now..
