### ISSUE TITLE
http2 - Stream does not exist - under load

### ISSUE THREAD

**Issue by CodingFabian** [netty/netty#6705]
Running on latest netty 4.1.10:

I create a netty http/2 client along these lines:
```
          final Http2Connection connection = new DefaultHttp2Connection(false);
          ChannelPipeline pipeline = ch.pipeline();
          pipeline.addLast(sslCtx.newHandler(ch.alloc()));
          HttpToHttp2ConnectionHandler http2ConnectionHandler = new HttpToHttp2ConnectionHandlerBuilder()
              .frameListener(new DelegatingDecompressorFrameListener(connection,
                  new InboundHttp2ToHttpAdapterBuilder(connection).maxContentLength(Integer.MAX_VALUE)
                      .propagateSettings(true).build()))
              .connection(connection).build();
          pipeline.addLast(http2ConnectionHandler);
```

and then pump requests through it
```
    FullHttpRequest request = new DefaultFullHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.POST, path, msgBytes, false);
    request.headers().set(HttpConversionUtil.ExtensionHeaderNames.SCHEME.text(), HttpScheme.HTTPS);
channel.writeAndFlush(request)
```

This works fine most of the time. But sometimes we encounter:
```
java.lang.IllegalArgumentException: Stream does not exist: <streamid>
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.requireStream(DefaultHttp2ConnectionEncoder.java:324)
```

I was now able to produce a "load test" that can more or less reliably trigger the problem.

it seems for me that there is a race condition somewhere. potentially increasing the currentStreamId already before the frame for the last stream id is sent.

I am still trying to make this a runnable reduced test case for you guys. But maybe somebody who knows about the internals can look at possible race conditions around the streamId

**Comment by CodingFabian** [comment]
The problem possibly lies in
io.netty.handler.codec.http2.HttpToHttp2ConnectionHandler.write(ChannelHandlerContext, Object, ChannelPromise)

where currentStreamId is assigned from getStreamId(httpMsg.headers());
when this is invoked twice before further down the HttpContent is written the currentStreamId changes.

Also
io.netty.handler.codec.http2.DefaultHttp2Connection.DefaultEndpoint.incrementAndGetNextStreamId()
is not threadsafe.

Is a single http2 connection not designed to be threadsafe?

how would I correctly synchronize?

**Comment by CodingFabian** [comment]
Trying to manually manage the stream ids is not much better:


```
    request.headers().set(HttpConversionUtil.ExtensionHeaderNames.STREAM_ID.text(), streamId.getAndAdd(2));
```

```
[io.netty.handler.codec.http2.Http2ConnectionHandler] : [id: 0x33857cc0, L:/127.0.0.1:64468 - R:localhost/127.0.0.1:8448] Sending GOAWAY failed: lastStreamId '0', errorCode '1', debugData 'Request stream 25 is behind the next expected stream 29'. Forcing shutdown of the connection.
```

**Comment by CodingFabian** [comment]
DefaultHttp2Connection.streamMap also does not seem to be threadsafe.

**Comment by CodingFabian** [comment]
Ok, closing this as user error
It is 
        throw streamError(streamId, REFUSED_STREAM, "Maximum active streams violated for this endpoint.");
Under load. somehow the exception is swallowed so i did not see them.

**Comment by CodingFabian** [comment]
Maybe there is still some value.
Apparently this stream error is caught and handled:
io.netty.handler.codec.http2.Http2ConnectionHandler.onStreamError(ChannelHandlerContext, Throwable, StreamException)

but never printed/thrown to the user (aka me)

**Comment by CodingFabian** [comment]
should anybody find this issue. there is actually a netty setting which can prevent this:
encoderEnforceMaxConcurrentStreams(true)

it feels like it should be default true, or the non-default behaviour should be more robust.

**Comment by Scottmitch** [comment]
@CodingFabian - `encoderEnforceMaxConcurrentStreams` was not made the default at the time because it introduces overhead which may not be necessary depending on the use case. do you have a suggestion to make this more visible? would firing an exception up the pipeline make things more visible or adding logging to `resetUnknownStream` ?

**Comment by CodingFabian** [comment]
yes either of that @Scottmitch - as you can see from this ticket history it took me a while to realize whats going on.

**Comment by Scottmitch** [comment]
I'm fine with logging an exception in this method. Would you be interested in submitting a PR?
