### ISSUE TITLE
SslHandler does not work with little endian buffers

### ISSUE THREAD

**Issue by sudheeshkatkam** [netty/netty#6709]
### Expected behavior
SslHandler to work regardless of LE or BE buffers
### Actual behavior
SslHandler uses [SslUtils#getEncryptedPacketLength](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslUtils.java#L123) which does not work with little endian buffers.

Looks like the issue was fixed in [16750ff](https://github.com/netty/netty/commit/16750ffc2802e6098e624df56ea6fbbe5c1055c3) but the change was not carried forward. I suspect there is an alternative then?

From the doc in the fix:
> Reads a big-endian short integer from the buffer.  Please note that we do not use
> {@link ChannelBuffer#getShort(int)} because it might be a little-endian buffer.

### Minimal yet complete reproducer code (or URL to code)
Code to reproduce the issue is here: [8b415c1](https://github.com/sudheeshkatkam/netty/commit/8b415c1949e0320b4fa1b7a2c7430c1af4eabd52). This bootstraps the chat server and client with a little endian bytebuf allocator, and adds details to console output.

To reproduce the failure (handshake timeout), start server using this command (in root directory):
> ./run-example.sh -Dlebba=true securechat-server

And then the client, using this command:

> ./run-example.sh -Dlebba=true securechat-client

To fix the use, apply a modified version of [16750ff](https://github.com/netty/netty/commit/16750ffc2802e6098e624df56ea6fbbe5c1055c3) which is here: [f7da006](https://github.com/sudheeshkatkam/netty/commit/f7da006152eaaee40b3482b7126e2f1f2bd90b3d).
### Netty version
4.1
### JVM version (e.g. `java -version`)
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

**Comment by normanmaurer** [comment]
@sudheeshkatkam will check... thanks!

**Comment by normanmaurer** [comment]
@sudheeshkatkam PTAL https://github.com/netty/netty/pull/6713

**Comment by sudheeshkatkam** [comment]
LGTM!

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6713
