### ISSUE TITLE
StringDecoder Sticky bag problem

### ISSUE THREAD

**Issue by stkkk** [netty/netty#6712]
The server uses netty，but the client doesn't use netty,
Whether the server can overcome the sticky bag problem by using StringDecoder,
if not , what should i do？

**Comment by normanmaurer** [comment]
@stkkk can you explain what exact issues you see ? I don't understand what you try to explain in the issue.

**Comment by stkkk** [comment]
@normanmaurer 
I was using netty to create a TCP server,  but the calling client does not use netty,
Will there be a sticky question on my writing?
If so, how to deal with

here is the code:
                       ServerBootstrap server = new ServerBootstrap();
			server.group(bossGroup, workerGroup);
			server.channel(NioServerSocketChannel.class);
			server.option(ChannelOption.SO_BACKLOG, 1024);
			
			// pooled  ByteBuf
			server.option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT);
			server.childOption(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT);
			
			
			// server.childHandler(new SocketServerChannelInitializer(clazz));
			server.childHandler(new ChannelInitializer<SocketChannel>() {
				@Override
				public void initChannel(SocketChannel ch) throws Exception {
					
					ChannelPipeline pipeline = ch.pipeline();
					pipeline.addLast("decoder", new StringDecoder(CharsetUtil.UTF_8));
					pipeline.addLast("encoder", new StringEncoder(CharsetUtil.UTF_8));
					pipeline.addLast((ChannelInboundHandlerAdapter)clazz.newInstance());
					
				}
			});

**Comment by normanmaurer** [comment]
@stkkk I am still no sure why you asking for. What does "sticky question" mean here ? Its just bytes at the end so it not matters if your other peer is using netty or not.
