### ISSUE TITLE
EventLoopGroup with java-thread-affinity use only one cpu

### ISSUE THREAD

**Issue by caoli5288** [netty/netty#6714]
### Expected behavior
I add java-thread-affinity code followed [here](http://netty.io/wiki/thread-affinity.html). I think this will make thread launch and bind to each core of my server but not.

### Actual behavior
![](https://cloud.githubusercontent.com/assets/3120587/25790054/588da402-33e8-11e7-96c3-143af455976e.png)

### Steps to reproduce
new NioEventLoopGroup with AffinityThreadFactory.

### Minimal yet complete reproducer code (or URL to code)
```java
ThreadFactory threadFactory = new AffinityThreadFactory("netty-io", AffinityStrategies.DIFFERENT_CORE);
EventLoopGroup workerGroup = new NioEventLoopGroup(0, threadFactory);
```

### Netty version
4.1.9

### JVM version (e.g. `java -version`)
1.8.0_121

### OS version (e.g. `uname -a`)
centos-6-x86_64

**Comment by normanmaurer** [comment]
@caoli5288 NioEventLoopGroups will be started in a lazy fashion. Are you sure all of them are started yet ? If this still not helps you may want to ask the maintainer of `java-thread-affinity` as we only "delegate" to it.

**Comment by caoli5288** [comment]
About 200+ connection handled while I take this screenshot so all thread must be launched:/
I'll open a issue in java-thread-affinity. THX

**Comment by maseev** [comment]
This ticket is probably related to this one - #2381. Not sure if this related, but it appears that Java-Thread-Affinity library has some issues working on some RedHat versions of Linux according to this [ticket](https://github.com/OpenHFT/Java-Thread-Affinity/issues/10).

**Comment by normanmaurer** [comment]
Let me close this for now as it seems to be a know "bug" in java-thread-affinity as @maseev pointed out
