### ISSUE TITLE
OpenSsl.java line 143 creates file and doesn't delete it

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#6716]
The OpenSsl class at line [143](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/OpenSsl.java#L143) creates a SelfSignedCertificate but doesn't delete it once it's done with it.

### Expected behavior

File getting deleted once it's done with it

### Actual behavior

File may or may not getting deleted depending on if `File#deleteOnExit()` gets triggered.

**Comment by normanmaurer** [comment]
@rkapsi good catch. Let me fix this very quickly.

**Comment by normanmaurer** [comment]
@rkapsi fixed by https://github.com/netty/netty/pull/6718

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6718
