### ISSUE TITLE
The value of the SNI extension is ASCII encoded but Netty uses UTF-8

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#6717]
The value of the SNI extension is ASCII encoded but Netty's SNI code tries to decode the `byte[]` as UTF-8.

The was flagged by @fenik17 in this https://github.com/netty/netty/pull/6623#discussion_r111070719

https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/AbstractSniHandler.java#L188

https://tools.ietf.org/html/rfc6066#page-6

> "HostName" contains the fully qualified DNS hostname of the server,
   as understood by the client.  The hostname is represented as a byte
   string using ASCII encoding without a trailing dot.  This allows the
   support of internationalized domain names through the use of A-labels
   defined in [RFC5890].  DNS hostnames are case-insensitive.  The
   algorithm to compare hostnames is described in [RFC5890], Section
   2.3.2.4.

### Expected behavior

Do as the RFC says?

### Actual behavior

Not doing as the RFC says!

**Comment by normanmaurer** [comment]
@rkapsi sounds good (do it as the RFC). You want to do a PR or should I put it on my back burner ?

**Comment by rkapsi** [comment]
Sounds good, inbound PR shortly

**Comment by normanmaurer** [comment]
<3
