### ISSUE TITLE
netty4-setautoreadfalse-with-epoll-transport

### ISSUE THREAD

**Issue by devpage** [netty/netty#6724]
### Minimal yet complete reproducer code (or URL to code)
http://stackoverflow.com/questions/43646038/netty4-setautoreadfalse-with-epoll-transport
### Netty version
4.1.9
### JVM version (e.g. `java -version`)
1.8.x
### OS version (e.g. `uname -a`)
linux

I am using Netty 4.1.9 with Epoll transport. I have a test case to pause netty server processing any request and check for few invariants in my project and then resume processing requests again. I use channel config setAutoRead(false) to pause and set it again to true to resume processing. With EPOLL transport, once auto read set to false, at least one request is processed. But, with NIO I don't see this issue.

Is this expected? and why?

this issue is a fork from http://stackoverflow.com/questions/43646038/netty4-setautoreadfalse-with-epoll-transport

**Comment by Scottmitch** [comment]
> I have a test case

Please provide the test case. In general we should re-register and read any pending data. I assume you have tried with `EpollMode` LEVEL_TRIGGERED and EDGE_TRIGGERED?

Possibly related:
https://github.com/netty/netty/issues/6173
https://github.com/netty/netty/issues/6303

**Comment by normanmaurer** [comment]
I will close this for now due lack of response. Please re-open if you still think there is anything wrong in netty
