### ISSUE TITLE
kqueue bootstrap 'Failed to set channel option 'IP_TOS'' (4.1.11.Final)

### ISSUE THREAD

**Issue by jhrussell** [netty/netty#6741]
Running into an error trying to set IP_TOS while using the new kqueue native transport.  This works for both NIO and EPOLL transports.  And by works, I mean at the very least it doesn't throw any errors.

### Expected behavior
No errors.  Perhaps even setting channel option IP_TOS.

### Actual behavior
Warning/exception thrown.  The channel appears to be bootstrapped okay otherwise.

> 2017-05-12T17:41:46.835 [KQueueEventLoopGroup-4-2] WARN  io.netty.bootstrap.ServerBootstrap - Failed to set channel option 'IP_TOS' with value '184' for channel '[id: 0x413f8ecb, L:/127.0.0.1:8554 - R:/127.0.0.1:55500]'
> io.netty.channel.ChannelException: setsockopt() failed: Invalid argument
> 	at io.netty.channel.unix.Socket.setTrafficClass(Native Method)
> 	at io.netty.channel.unix.Socket.setTrafficClass(Socket.java:385)
> 	at io.netty.channel.kqueue.KQueueSocketChannelConfig.setTrafficClass(KQueueSocketChannelConfig.java:288)
> 	at io.netty.channel.kqueue.KQueueSocketChannelConfig.setOption(KQueueSocketChannelConfig.java:116)
> 	at io.netty.bootstrap.AbstractBootstrap.setChannelOption(AbstractBootstrap.java:459)
> 	at io.netty.bootstrap.AbstractBootstrap.setChannelOptions(AbstractBootstrap.java:451)
> 	at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:248)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
> 	at io.netty.channel.kqueue.AbstractKQueueServerChannel$KQueueServerSocketUnsafe.readReady(AbstractKQueueServerChannel.java:110)
> 	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:355)
> 	at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:198)
> 	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:270)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
> 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
> 	at java.lang.Thread.run(Thread.java:748)

### Steps to reproduce
1. Bootstrap a socket or datagram channel setting  `ChannelOption.IP_TOS` and using kqueue transport.
2. Make a client and or server connection
3. observe the logs

### Minimal yet complete reproducer code (or URL to code)
```
        Channel serverChannel = new ServerBootstrap()
                .group(new KQueueEventLoopGroup(), new KQueueEventLoopGroup())
                .channel(KQueueServerSocketChannel.class)
                .childHandler(...)
                .childOption(ChannelOption.TCP_NODELAY, false)
                .childOption(ChannelOption.CONNECT_TIMEOUT_MILLIS, (int)TimeUnit.MINUTES.toMillis(1))
                .childOption(ChannelOption.AUTO_READ, true)
                .childOption(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
                .childOption(ChannelOption.IP_TOS, 0xB8) //184 - High Priority Expedited Forwarding (EF)
                .bind(8080).sync()
                .channel();
```

### Netty version
4.1.11.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### OS version (e.g. `uname -a`)
Darwin ... 16.6.0 Darwin Kernel Version 16.6.0: Mon Apr 17 17:15:27 PDT 2017; root:xnu-3789.60.24~21/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
Will check... thanks for reporting
