### ISSUE TITLE
Netty 4.1 Facing thread Leak issue

### ISSUE THREAD

**Issue by ankitLu** [netty/netty#6746]
### Thread count checked through below command should be minimal
 ps -u |grep <PID>| wc -l

### Thread count starts from 41 initially, reaches to 200 within minutes and eventually jvm is not able to support new connections. Total client connections initially are 20, but client tries to reconnect after connection reset.
Also there is a load balancer continuously querying TCP port for active state, which is configured as force close.

###  Code
                     

                      `final EventLoopGroup bossGroup = new NioEventLoopGroup();
		        final EventLoopGroup workerGroup = new NioEventLoopGroup();
		        try {
		            final ServerBootstrap b = new ServerBootstrap();
		            b.group(bossGroup, workerGroup)
		                    .channel(NioServerSocketChannel.class)
		                    .childHandler(new MySocketInitialiser())
		                    .option(ChannelOption.SO_BACKLOG, 100)
		                    .childOption(ChannelOption.SO_KEEPALIVE, true);
		            String hostname = getHostName();
		            ch = b.bind(hostname, 12110).sync().channel();
		            System.out.println("Started on port : server "+ port + ":"+hostname);
		            ch.closeFuture().sync();
		        } finally {
		            bossGroup.shutdownGracefully();
		            workerGroup.shutdownGracefully();
		        }`

                     `private class MySocketInitialiser extends ChannelInitializer<SocketChannel> {
		        @Override
		        public void initChannel(final SocketChannel ch) throws Exception {
		            final ChannelPipeline pipeline = ch.pipeline();
		            
		            
		            final EventExecutorGroup group = new DefaultEventExecutorGroup(5);
		            pipeline.addLast(group, "handler", new SomeHandler());
		           
		        }
		    }`

                    
                          ` public class SomeHandler extends ChannelInboundHandlerAdapter {
		        @Override
				public void channelRead(ChannelHandlerContext channelHandlerContext, Object notification) throws Exception {
		        	 // Read the message sent from client.
		        		++packetNumber;
		                ByteBuf in = (ByteBuf) notification;
		                incomingMsg = new StringBuffer();
		                try {
		                    while (in.isReadable()) { // (1)
		                    	incomingMsg.append((char) in.readByte());
		                    }
		                  
				            System.out.println("Going to write response:"+response);
				            channelHandlerContext.writeAndFlush(Unpooled.copiedBuffer(response, CharsetUtil.UTF_8));
		                }
		                catch(Exception e){
		                
		                }finally{
		                    ReferenceCountUtil.release(channelHandlerContext);
		                    channelHandlerContext.close();
		                }
		            
		        }`

**Comment by lizhanhui** [comment]
```java
   final EventExecutorGroup group = new DefaultEventExecutorGroup(5);
   pipeline.addLast(group, "handler", new SomeHandler());
```

This line is obviously buggy. You need to reuse `group` instead of creating new instance for each connection.

**Comment by Scottmitch** [comment]
thanks @lizhanhui .. let me close this for now as this doesn't seem to be a Netty issue.

**Comment by ankitLu** [comment]
hi @lizhanhui 
Thanks for your time. As you recommended, I tried reusing the group. But this is not helping, as the thread count is still increasing with pace.


###Code
` final EventExecutorGroup group = new DefaultEventExecutorGroup(20);

                    
                    private class MySocketInitialiser extends ChannelInitializer<SocketChannel> {
                        @Override
                        public void initChannel(final SocketChannel ch) throws Exception {
                            final ChannelPipeline pipeline = ch.pipeline();

                            pipeline.addLast(group, "handler", new SomeHandler());
                            System.out.println("Exitting initchannel method()");
                        }
                    }`
