### ISSUE TITLE
codec.mqtt: wrong password and willMessage field types in MqttConnectPayload/MqttEncoder (should be byte[])

### ISSUE THREAD

**Issue by oakad** [netty/netty#6750]
In the present implementation of MqttConnectPayload/MqttEncoder, willMessage and password fields are  strings. However, spec (3.1.3.5) clearly mandates that the password filed should support arbitrary binary data:

> The Password field contains 0 to 65535 bytes of binary data prefixed with a two byte length field which indicates the number of bytes used by the binary data (it does not include the two bytes taken up by the length field itself). 

Same for willMessage (3.1.3.3):

> This field consists of a two byte length followed by the payload for the Will Message expressed as a sequence of zero or more bytes.

Thus, the relevant field and encoder bits must treat the password and willMessage fields as byte[] or ByteBuf (the former is probably enough).

This has important practical implications and the fix is straightforward and simple.

**Comment by Scottmitch** [comment]
are you interested in submitting a PR to correct this issue?

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/681
