### ISSUE TITLE
Backward- and forward compatibility

### ISSUE THREAD

**Issue by floragunncom** [netty/netty#6752]
Is netty a.b.x supposed to be API and ABI backward compatible with a.b.y where x>y ?
(In other words: If i have a application compiled against netty 4.1.0 will this work with, say, netty 4.1.99)

And also the other way around: Is netty a.b.y supposed to be API and ABI forward compatible with a.b.x where x>y ?
(In other words: If i have a application compiled against netty 4.1.99 will this application also work with netty 4.1.0 [apart from the fact that i may face bug which are fixed in newer versions])

**Comment by Scottmitch** [comment]
We generally stick to semantic versioning so API compatibility should be preserved. There are exceptions about unstable packages, internal APIs, API bugs, etc...

**Comment by normanmaurer** [comment]
@floragunncom just to make it more clear... using for example 4.1.11 for an app that was compiled against 4.1.0 will work. If the app was compiled against 4.1.11 it may not work to use 4.1.0 due missing features.
