### ISSUE TITLE
Instances of ResourceLeakDetector are created even io.netty.leakDetection.level is disabled

### ISSUE THREAD

**Issue by doom369** [netty/netty#6754]
### Expected behavior

No instances of `ResourceLeakDetector` when used `ResourceLeakDetector.setLevel(ResourceLeakDetector.Level.DISABLED);`.

### Actual behavior

Few instances of `ResourceLeakDetector` are still created.

### Steps to reproduce

Set `ResourceLeakDetector.setLevel(ResourceLeakDetector.Level.DISABLED);` on start.

Case 1: 
Create `new HashedWheelTimer()`.
Field initialized:

```
    private static final ResourceLeakDetector<HashedWheelTimer> leakDetector = ResourceLeakDetectorFactory.instance()
            .newResourceLeakDetector(HashedWheelTimer.class, 1);

```

Case 2:
`new SelfSignedCertificate()`

```
    static String[] newSelfSignedCertificate(
            String fqdn, PrivateKey key, X509Certificate cert) throws IOException, CertificateEncodingException {
        // Encode the private key into a file.
        ByteBuf wrappedBuf = Unpooled.wrappedBuffer(key.getEncoded());
```

Field of `AbstractByteBuf` initialized: 

```
    static final ResourceLeakDetector<ByteBuf> leakDetector =
            ResourceLeakDetectorFactory.instance().newResourceLeakDetector(ByteBuf.class);
```

### Netty version

4.1.11-Final

**Comment by Scottmitch** [comment]
The level is allowed to change dynamically via `ResourceLeakDetector#setLevel`. So it will not be trivial to eliminate this allocation. What is the problem with allocating instances of `ResourceLeakDetector` in this case?

**Comment by normanmaurer** [comment]
@doom369 as @Scottmitch said ....

**Comment by doom369** [comment]
@Scottmitch no problem. Just seems a bit wrong. I looked through code, yeap, seems like fix wouldn't be easy. Let's close as minor issue.
