### ISSUE TITLE
HttpObjectEncoder#isContentAlwaysEmpty cannot be overridden by subclasses

### ISSUE THREAD

**Issue by vietj** [netty/netty#6761]
### Expected behavior

the `HttpObjectEncoder#isContentAlwaysEmpty()` method is package private, so subclasses can change its behavior. Currently Vert.x has a subclass extending `HttpObjectEncoder `.

### Actual behavior

the `HttpObjectEncoder#isContentAlwaysEmpty()` method is package private

### Steps to reproduce

n/a

### Minimal yet complete reproducer code (or URL to code)

n/a

### Netty version

4.1.8.Final

### JVM version (e.g. `java -version`)

n/a

### OS version (e.g. `uname -a`)

n/a

**Comment by normanmaurer** [comment]
@vietj so you say it is package private and it should be not package-private ? Whats your use-case ?

**Comment by vietj** [comment]
my use case is to not send content in a response to HEAD, Vert.x has a special subclass (that you actually created) of `HttpObjectEncoder` that forces the usage of direct buffers, so we cannot use the `HttpServerCodec`.

Another motivation is that we might want to handle the HEAD check with a custom implementation of `HttpMessage` and not use an a FIFO queue of HttpMessage like in `HttpServerCodec`.

**Comment by vietj** [comment]
any news about this ?

**Comment by normanmaurer** [comment]
Can you just create a PR for this change ?


On 26. May 2017 at 10:26:16, Julien Viet (notifications@github.com) wrote:

isContentAlwaysEmpty

**Comment by vietj** [comment]
sure I will

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6788
