### ISSUE TITLE
Diffie-Hellman group smaller than 2048 bits (tls-dh-prime-under-2048-bits)

### ISSUE THREAD

**Issue by llname** [netty/netty#6763]
### Expected behavior
tls-dh-prime-2048-bits
### Actual behavior
Diffie-Hellman group smaller than 2048 bits (tls-dh-prime-under-2048-bits)
### Netty version
4.0.27.Final
### JVM version (e.g. `java -version`)
jdk_8u121
### OS version (e.g. `uname -a`)
Linux 3.10.0-229.x.x86_64

**Comment by Scottmitch** [comment]
Can you provide more context, and some example code? How are you configuring your SslContext, what SslProvider are you using, etc...?

**Comment by normanmaurer** [comment]
@llname please re-open with more details and update your netty version to the latest one if you still think its an issue

**Comment by llname** [comment]
SSL：TLSv1.2 TLS_DHE_RSA_WITH_AES_
io.netty.handler

**Comment by johnou** [comment]
Stab in the dark.. http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

**Comment by llname** [comment]
YES，I have installed @johnou

**Comment by johnou** [comment]
As Scott mentioned please provide example client server code.
