### ISSUE TITLE
Adding handlers to a closed Channel's pipeline

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#6768]
It appears the a ChannelPipeline will happily add a handler to a closed Channel's pipeline and will call `handlerAdded(...)` but will not call `handlerRemoved(...)` or blow up in some other way to let the caller know that things aren't in a good state.

Just wondering if there wouldn't be edge cases where we'd potentially leak resources (e.g. `SslHandler#handlerRemoved0(...)` which is supposed to release a reference counted SSLEngine).

### Expected behavior

Fail with Exception or `handlerRemoved(...)` getting called after `handlerAdded(...)` 

### Actual behavior

`handlerAdded(...)`  getting called as if everything is ok

### Minimal yet complete reproducer code (or URL to code)

```java
@Test
public void testHandlerAfterClose() throws Exception {
  EmbeddedChannel channel = new EmbeddedChannel();
  channel.close().syncUninterruptibly();
  
  assertFalse(channel.isActive());
  
  final CountDownLatch addedLatch = new CountDownLatch(1);
  final CountDownLatch removedLatch = new CountDownLatch(1);
  
  ChannelPipeline pipeline = channel.pipeline();
  pipeline.addLast(new ChannelHandlerAdapter() {
    @Override
    public void handlerAdded(ChannelHandlerContext ctx) throws Exception {
      addedLatch.countDown();
    }

    @Override
    public void handlerRemoved(ChannelHandlerContext ctx) throws Exception {
      removedLatch.countDown();
    }
  });
  
  assertTrue(addedLatch.await(1L, TimeUnit.SECONDS));
  assertTrue(removedLatch.await(1L, TimeUnit.SECONDS));
}
```

**Comment by normanmaurer** [comment]
@rkapsi will check

**Comment by Scottmitch** [comment]
thanks for reporting @rkapsi ... sounds like a bug to me

**Comment by normanmaurer** [comment]
@Scottmitch @rkapsi I wonder what you think is the better option here. Throw an exception when calling add or just remove it directly after it is added automatically ? I guess 1) is better. WDYT ?

**Comment by rkapsi** [comment]
I'd go with Exception as well.

**Comment by normanmaurer** [comment]
@Scottmitch sounds good to you as well ?

**Comment by Scottmitch** [comment]
Exception should be fine (static exception?), hopefully we have been diligent in handling exceptions in cases where ReferenceCounted things are added to the pipeline :sweat_smile:

**Comment by normanmaurer** [comment]
@Scottmitch I think non static exception is better as I not expect this to be thrown often and it will be better to have some context

**Comment by normanmaurer** [comment]
I will take care

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6774

**Comment by normanmaurer** [comment]
Reopen this one

**Comment by normanmaurer** [comment]
Yes I missed to close this :/
