### ISSUE TITLE
GlobalEventExecutor short lived threads

### ISSUE THREAD

**Issue by Shorttail** [netty/netty#6782]
### Expected behavior
NioEventLoopGroup uses the thread pool it has been given.

### Actual behavior
A new thread is spawned every second, with a one second lifetime, named globalEventExecutor-1-x.

### Steps to reproduce
Start a server from a ServerBootstrap with a `new NioEventLoopGroup(1)` or `new NioEventLoopGroup(1, Executors.newSingleThreadExecutor())` as the group.

### Minimal yet complete reproducer code (or URL to code)
n/a

### Netty version
4.1.11

### JVM version (e.g. `java -version`)
1.8.0_131

### OS version (e.g. `uname -a`)
Windows 10

### Details

VisualVM (Java profiler) shows threads starting every second and idling for a second before dying. Reproducing the issue is fickle, but with `new NioEventLoopGroup(1)` it happens most of the time on my system. `new NioEventLoopGroup(1, Executors.newSingleThreadExecutor())` experiences the issue 30% - 50% of the time.

Replacing it with `new NioEventLoopGroup(2, Executors.newSingleThreadExecutor())` seems to fix the issue.

I searched through the instantiation of `NioEventLoopGroup`, but couldn't find anything hinting at why it would default to `GlobalEventExecutor` when the number of threads is 1.

**Comment by normanmaurer** [comment]
@Shorttail I can not reproduce... anything else I need to do beside starting the server ?

**Comment by Shorttail** [comment]
@normanmaurer I'm trying to reproduce it on a smaller scale, but I'm having trouble. Meanwhile, when is the GlobalEventExecutor supposed to be active?

**Comment by normanmaurer** [comment]
@Shorttail it should mainly run when the EventLoop is terminated

**Comment by Shorttail** [comment]
It would appear I was completely wrong. The setup with `new NioEventLoopGroup(2, Executors.newSingleThreadExecutor())` blocked somewhere internally and the Netty servers were never accepting clients. Setting the number of threads to 1 still yields the constant thread starting behavior.

@normanmaurer When you say the EventLoop is terminated, what does that mean? What event loop? Could I accidentally send tasks to it? The Netty servers are started once and run until the program is manually terminated.

**Comment by Shorttail** [comment]
I found the culprit. Calling `ChannelGroup#writeAndFlush()` is what spawns all the extra threads. Replacing it with manually looping over clients removed the thread spam.

Is there a way to use `ChannelGroup` letting the same thread execute whatever it's executing instead of the `GlobalEventExecutor`?
