### ISSUE TITLE
Netty force encodes already encoded responses

### ISSUE THREAD

**Issue by NSProgrammer** [netty/netty#6784]
### Expected behavior

Brotli content passes through with Content-Encoding being untouched

### Actual behavior

Content-Encoding changed to gzip and already encoded content (in brotli) encoded again with gzip

### Steps to reproduce

1) Encode response with Brotli
2) Set Content-Encoding to "br"

### Netty version

4.1.11

**Comment by normanmaurer** [comment]
Can you provide a reproducer / testcase?

**Comment by NSProgrammer** [comment]
Here's a unit test

https://github.com/netty/netty/pull/6785/commits/efebcc327ccb61876fb7e70c1ee7cf3ce65a6525
