### ISSUE TITLE
JdkSslServer/ClientContext  TLS protocol causes TLSv1 protocol only with IBM JVMs

### ISSUE THREAD

**Issue by veffen** [netty/netty#6795]
### Expected behavior

JdkSslServer/ClientContext should optionally allow to specify the PROTOCOL instead ot setting it hard-wired

### Actual behavior

JdkSslServer/ClientContext set the ssl protocol hard wired:

            static final String PROTOCOL = "TLS";

            SSLContext ctx = SSLContext.getInstance(PROTOCOL);

Setting TLS as protocol on IBM JVMs causes the IBM JSSE to set TLSv1 as protocol, which might lead to handshake failures, see:

https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/jsse2Docs/protocols.html

### Steps to reproduce
 Use SslContextBuilder.build() on IBM J9 JVM 1.8 SR4 FP2, check for enabled protocols

### Minimal yet complete reproducer code (or URL to code)

                SslContextBuilder sslContextBuilder = SslContextBuilder.forClient();
                context = sslContextBuilder.build();
                SSLEngine engine = context.createSSLEngine();
                for(String prot : engine.getEnabledProtocols()) {
                    System.out.println(prot+" ");
                }
### Netty version
4.0.32
### JVM version (e.g. `java -version`)
(at customer)
java.vm.info                    : JRE 1.8.0 AIX ppc64-64 Compressed References 20170314_340265 (JIT enabled, AOT enabled)
J9VM - R28_20170314_2309_B340265
JIT  - tr.r14.java.green_20170314_134138
GC   - R28_20170314_2309_B340265_CMPRSS
J9CL - 20170314_340265

### OS version (e.g. `uname -a`)
os.arch                         : ppc64
os.name                         : AIX
os.version                      : 7.1

**Comment by Scottmitch** [comment]
Please specify your desired protocol on the SSLEngine, or update your Netty version and specify it on the `SslContextBuilder#protocols(...)` [1]. It is not clear there is any issue in Netty ... please provide a complete reproducer if you think there is an issue in Netty.

[1] https://github.com/netty/netty/blob/4.0/handler/src/main/java/io/netty/handler/ssl/SslContextBuilder.java#L409
