### ISSUE TITLE
Not specified field in MQTT codec

### ISSUE THREAD

**Issue by Sammers21** [netty/netty#6802]
### Expected behavior
According to the [MQTT 3.1.1 spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html), the variable header must not have a messageId in the variable header when publishing PUBLISH packet. It must have only these two: Topic Name and Packet Identifier.

### Actual behavior
In io.netty.handler.codec.mqtt.MqttPublishVariableHeader there are two fields and one of them is messageId which is not specified.

### Question
What the meaning of messageId field in MqttPublishVariableHeader?

Thank you,
Pavel

**Comment by Scottmitch** [comment]
@mousom - ping (for reference see [1])

@Sammers21 - You can see how PUBLISH is encoded here [2]. Do you think there is an issue with this?

[1] http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html#_Toc385349775
[2] https://github.com/netty/netty/blob/4.1/codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttEncoder.java#L298

**Comment by Sammers21** [comment]
@Scottmitch, After reading how to PUBLISH packet encodes I would assume that messageId in code is the same as Packet Identifier in spec. Maybe it would be better to rename messageId field into packetId? 
Can I create PR?

**Comment by normanmaurer** [comment]
@Sammers21 I think we can not rename interface methods as we otherwise would break user-code or you talking about something else ?

**Comment by Sammers21** [comment]
@normanmaurer, yes, you are right, renaming of one of the fields would break user code. But in my point of view, fields should are named in the same way as it in a protocol otherwise it can be tricky for new users to understand what the field really mean.

**Comment by Scottmitch** [comment]
If you want to submit a PR to correct naming you can deprecate the existing accessors and refer to the new accessors (if you think its worth it).

**Comment by Sammers21** [comment]
@Scottmitch , I have marked the old method with @deprecated  and opened PR. Check it out.
