### ISSUE TITLE
JDKZlibEncoder or JDKZlibDecoder can't work correct with large data

### ISSUE THREAD

**Issue by lsqlebai** [netty/netty#6804]
### Expected behavior
work 
### Actual behavior
decode error(protobuf decode error)
### Steps to reproduce
i have 2 server. and them communicate with tcp.
and the pipeline init code double with them.
when the send data > 16000 byte (maybe less). the decode side can't correct decode (protobuf decode error). 
### Minimal yet complete reproducer code (or URL to code)
decode error code:
Code:

        ChannelPipeline pipeline = ch.pipeline();
        pipeline.addLast(new ProtobufVarint32FrameDecoder());
        pipeline.addLast(ZlibCodecFactory.newZlibDecoder(ZlibWrapper.NONE));
        pipeline.addLast(new ProtobufDecoder(GameServer.ServerData.getDefaultInstance()));
        pipeline.addLast(new ProtobufVarint32LengthFieldPrepender());
        pipeline.addLast(ZlibCodecFactory.newZlibEncoder(ZlibWrapper.NONE));
        pipeline.addLast(new ProtobufEncoder());

i had 2 test:
     remove zlib, can be work.like this:
     
      ChannelPipeline pipeline = ch.pipeline();
        //receive
        pipeline.addLast(new ProtobufVarint32FrameDecoder());
        pipeline.addLast(new ProtobufDecoder(GameServer.ServerData.getDefaultInstance()));
        //send
        pipeline.addLast(new ProtobufVarint32LengthFieldPrepender());
        pipeline.addLast(new ProtobufEncoder());

change to the JZlibDecoder and JZlibEncoder can be work. like this:
        
        ChannelPipeline pipeline = ch.pipeline();
        //receive
        pipeline.addLast(new ProtobufVarint32FrameDecoder());
        pipeline.addLast(new JZlibDecoder(ZlibWrapper.NONE));
        pipeline.addLast(new ProtobufDecoder(GameServer.ServerData.getDefaultInstance()));
        //send
        pipeline.addLast(new ProtobufVarint32LengthFieldPrepender());
        pipeline.addLast(new JZlibEncoder(ZlibWrapper.NONE));
        pipeline.addLast(new ProtobufEncoder());
### Netty version
4.1.7
### JVM version (e.g. `java -version`)
java version "1.8.0_101"
### OS version (e.g. `uname -a`)
windows

**Comment by normanmaurer** [comment]
@lsqlebai can you please provide a full reproducer ? Also please update to latest netty version just to be sure.

**Comment by lsqlebai** [comment]
sorry the netty version is 4.1.6.Final

**Comment by lsqlebai** [comment]
@normanmaurer What would you want? my project is so large. maybe i can give u a demo when i free.

**Comment by normanmaurer** [comment]
@lsqlebai I want you to upgrade to latest 4.1. version and try again if it happens. If it still happens provide me some way to reproduce.

**Comment by Scottmitch** [comment]
> my project is so large. maybe i can give u a demo when i free.

Ideally folks that file issues will provide a minimal/complete (so we can run it, but don't have to understand your entire application logic) ... the easier it is to reproduce the more likely we will be able to figure out the issue (assuming its a Netty issue) and fix it.

**Comment by lsqlebai** [comment]
@Scottmitch @normanmaurer i wrote a demo, how can i give you? by email or???

**Comment by lsqlebai** [comment]
@Scottmitch @normanmaurer would u please try this code:[https://github.com/lsqlebai/testzlib](url)

**Comment by Scottmitch** [comment]
I took a brief look. It seems like the issue is in this case the `JdkZlibDecoder` happens to break the decode up into 2 buffers and the `JZlibDecoder` decodes into a single buffer, and the `ProtobufDecoder#decoder` assumes all content is in the same `ByteBuf`. See https://github.com/netty/netty/pull/6816 for a PR which makes the two decoders consistent.
