### ISSUE TITLE
HttpContentCompressor/HttpContentEncoder should reset the content-length header for FullHttpMessages

### ISSUE THREAD

**Issue by bryce-anderson** [netty/netty#6808]
### Expected behavior
When the `HttpContentEncoder` is tasked with compressing a full `HttpMessage` that already contains a `Content-Length` header it should perform the compression and _adjust_ the `Content-Length`.

### Actual behavior
All messages compressed result in `Transfer-Encoding: Chunked` and don't have a `Content-Length` header.

### Minimal yet complete reproducer code (or URL to code)
```java
@Test
    public void testAmendContentLength() throws Exception {
        EmbeddedChannel ch = new EmbeddedChannel(new HttpContentCompressor());
        ch.writeInbound(newRequest());

        ByteBuf content = Unpooled.copiedBuffer("Hello, world!", CharsetUtil.UTF_8);
        HttpMessage res = new DefaultFullHttpResponse(HttpVersion.HTTP_1_1, HttpResponseStatus.OK, content);
        HttpUtil.setContentLength(res, content.readableBytes());

        ch.writeOneOutbound(res);

        HttpMessage compressedResponse = ch.readOutbound();
        assertThat(res.headers().get(HttpHeaderNames.CONTENT_ENCODING), is("gzip"));
        assertTrue(HttpUtil.isContentLengthSet(compressedResponse));
    }
```

### Netty version 4.1 branch at SHA 24f801c7d1d1 (should affect most versions)

**Comment by bryce-anderson** [comment]
This appears to be a very deliberate behavior, but I don't see a reason other than for implementation convenience. I'm happy to take a look at this if you're willing to accept a patch.

**Comment by Scottmitch** [comment]
IIUC it was done out of convenience (not required ... chunked should be "semantically correct" in either case so no need for a specialization). However a PR to adjust `content-length` if full object sgtm.

**Comment by bryce-anderson** [comment]
@Scottmitch thanks for the quick reply. I've opened a PR, #6809, that preserves the `content-length` header for full responses.

**Comment by normanmaurer** [comment]
fixed by https://github.com/netty/netty/pull/6809
