### ISSUE TITLE
Cannot use slf4j's MDC with Netty

### ISSUE THREAD

**Issue by daemas** [netty/netty#6810]
### Expected behavior
Ability to use [Mapped Diagnostic Context (MDC)](https://logback.qos.ch/manual/mdc.html) after some tuning of NioEventLoopGroup.

### Actual behavior
Unable to subclass NioEventLoop (as it is a final class) to override execute(), submit() and schedule...() methods to save current MDC values into a Runnable/Callable, to restore them on the target thread. 

### Netty version
4.0.x/4.1.x/5.x

MDC uses ThreadLocal storage to hold it's context Map. To pass the value of MDC.getCopyOfContextMap() together with a Runnable/Callable instance from the calling thread to the target thread on which channel handling routines are running, it is required to wrap a Runnable/Callable into another auxiliary Runnable/Callable, to put there a copy of MDC context map on the calling thread and restore after a Runnable.run() is called on a target thread. The best place to create such a wrapper is within execute(), submit(), and schedule...() methods of the EventLoop. NioEventLoopGroup creates its child EventLoop's within newChild method, which can be overridden, but the NioEventLoop class itself is declared final and thus cannot be subclassed to override required methods. Calling super.newChild(..) and wrapping the result into a facade class does not help, because register(...) methods will still register channels with the actual wrapped instance, not the wrapper facade.

**Comment by slovdahl** [comment]
I would also like to set MDC for `EventLoopGroup` threads. I haven't done any extensive testing nor studied `io.netty.util.concurrent.DefaultThreadFactory` in detail, but shouldn't it be doable by using a custom `ThreadFactory` that creates threads using something like this?
```java
public class MDCThread extends Thread {
    private final Map<String, String> mdc;
    
    MDCThread( ThreadGroup group, Runnable target, String name, Map<String, String> mdc ) {
        super( group, target, name, 0 );
        this.mdc = mdc;
        // .. if needed, set properties like daemon, priority
    }

    @Override
    public void run() {
        if ( mdc != null ) {
            MDC.setContextMap( mdc );
        }
        try {
            super.run();
        }
        finally {
            if ( mdc != null ) {
                MDC.clear();
            }
        }
    }
}
```

This, of course, under the assumption that all threads created by an `EventLoopGroup` should have the same MDC.

**Comment by normanmaurer** [comment]
I think you can do as @slovdahl said... Please re-open if this not works

**Comment by RaviH** [comment]
Hi @normanmaurer , @slovdahl ,

I was pointed to this thread from https://github.com/lettuce-io/lettuce-core/issues/951

Does anyone know how to use proposed solution in lettuce?
