### ISSUE TITLE
impossible to restore the order of parameters after using QueryStringDecoder 

### ISSUE THREAD

**Issue by evgenijvorobey** [netty/netty#6812]
### Expected behavior
Order of parameters at query string doesn't change

### Actual behavior
After using such classes as QueryStringDecoder the order of query string parameters changes

if any external library uses you decoder they will have a structure that will break the order of parameters
before:    param1=1&param2=2&param1=3
after:       param1=1&param1=3&param2=2

Is it so neccessary to use such structure to store the parameters:
`Map<String, List<String>>` 
because it is impossible to restore the order after we put parameters into value list here(addParams method of QueryStringDecoder.class):
```
 List<String> values = params.get(name);
 if (values == null) {
      values = new ArrayList<String>(1);  // Often there's only 1 value.
      params.put(name, values);
  }
 values.add(value);
```

**Comment by Scottmitch** [comment]
can you provide a link to the RFC which states the order of query params with independent names is significant? I didn't see anything in https://tools.ietf.org/html/rfc3986#section-3.4 which indicates there is any ordering requirements.

**Comment by fenik17** [comment]
@evgenijvorobey what is your purpose of using a `QueryStringDecoder`? If you want to get original query string, just use `QueryStringDecoder.uri()`.

**Comment by evgenijvorobey** [comment]
@fenik17, but i want to use Decoder but also to have possibility to restore the order of parameters.
@Scottmitch, i think that the decision to depend from order or not should depends from developers.

i found this when i looked through the [browsermob](https://github.com/lightbody/browsermob-proxy) code. i use it as proxy and found that the order of parameters will change if i use proxy. And if there is any dependency from the parameters order in application - proxy will break it.

**Comment by Scottmitch** [comment]
Can you clarify what exactly is "broken"? What depends upon the order or query parameters and why can't you use `QueryStringDecoder.uri()` for your use case?

> i think that the decision to depend from order or not should depends from developers.

If there is no requirement to preserve order defined in any RFC your application shouldn't depend upon a 3rd party library providing this functionality. If you want/need this behavior (and it is not defined in an RFC) I suggest you implement this behavior in your application.

**Comment by normanmaurer** [comment]
What @Scottmitch said

**Comment by evgenijvorobey** [comment]
1. `QueryStringDecoder.uri()` - why do you suggest me to use this method? as i can see from code:
```
 public QueryStringDecoder(URI uri, Charset charset, int maxParams) {
        String rawPath = uri.getRawPath();
        if (rawPath == null) {
            rawPath = EMPTY_STRING;
        }
        String rawQuery = uri.getRawQuery();
        // Also take care of cut of things like "http://localhost"
        this.uri = rawQuery == null? rawPath : rawPath + '?' + rawQuery;
        this.charset = checkNotNull(charset, "charset");
        this.maxParams = checkPositive(maxParams, "maxParams");
        pathEndIdx = rawPath.length();
}
```
this will return me query without any changes. So it is better to remove this Decoder at all.

2. I will try to explain the issue that i found:

Some days ago i found call that have the following parameters in query string: ad.=&name=nameValue&.ad=&a.=&name=nameValue&.a=&.....
after using browsermob as proxy i found that query string was changed to:
ad.=&name=nameValue&name=nameValue&.ad=&a.=&.a=&.....

as i understood there is something like object where 'ad.' is start , '.ad' is finish and 'name' is field . the same is for 'a'. I looked through the browsermob code and found that they use your decoder. It is clear that you obeyed certain rules when you created your decoder, but as i know proxy server shouldn't modify calls that go through it. Your structure doesn't give possibility to restore the order so, apperently, they should use other decoder.

thank you for your help!

**Comment by Scottmitch** [comment]
> but as i know proxy server shouldn't modify calls that go through it.

I would expect a proxy should preserve the semantics of the protocol. This doesn't necessarily mean what comes in is exactly what goes out.

I will close this issue now. If you find a spot in the HTTP related RFCs which describes the behavior you request please re-open and provide a link.
