### ISSUE TITLE
ChannelFuture stop awaitUninterruptibly causing deadlocks

### ISSUE THREAD

**Issue by ejsfreitas** [netty/netty#6815]
### Netty version
4.0.32.Final

### JVM version
1.7.0_80

### OS version
Red Hat Enterprise Linux Server release 6.7

I found a issue very similar with https://github.com/netty/netty/issues/3662 but using version 4.0.32. 
I'm doing a awaitUninterruptibly and the thread hangs forever. 

```
public void close() {
    if(nettyChannel != null) {
	nettyChannel.close().awaitUninterruptibly();
    }
}
```
This happended on a production system and we were not able to gather alot of information. 
We had some TCP issues that increased the load of the platform (x10 times the normal traffic) and the connections to the clients were disconnecting/connecting all the time, but after that the system never recovered. 

One of the things that we did was a thread dump and it lead me to https://github.com/netty/netty/issues/3662

Thread dump:
```
   java.lang.Thread.State: WAITING
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:503)
        at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:286)
        at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:135)
        at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:28)
        at XXXXXXXX.close(XXXXXXXX.java:340)
```

After the restart the system started working corretly and since then we were not able to replicate the problem in our lab enviroment.

I search the issues of versions 4.0.32+ and didn't find anything related and google didn't help also.

I understand that without replicate the problem any possible correction will be very difficult. Does anyone had some similar issue that can help me solve this problem? Or at least replicate it?

Thanks in advance!

**Comment by Scottmitch** [comment]
There were some concurrency related fixes made to DefaultPromise in newer releases [1]. Please update to the latest Netty version and report back if you are able to collect more info.

[1] https://github.com/netty/netty/commit/c9a29c493b5380c187a87e8fd34cd66da98a43b4
[2] https://github.com/netty/netty/commit/453b9589885dfd1441c31a0436abb30694cdb49c

**Comment by normanmaurer** [comment]
Let me close this for now and please reopen if you think there is an issue with the latest release
