### ISSUE TITLE
Creating a session in Netty like in Mina

### ISSUE THREAD

**Issue by Hema-Chandra** [netty/netty#6820]
I am new to Github and also to Netty. I am currently using netty 4.1.11. I also worked slightly with Mina package. In Mina whenever a client gets connected to a Server automatically a session is created. Is there anyway doing the same in Netty? I am working in Stocking market.As a result I need to connect to the Exchange market and get the data. For this I need to create a session. Is there anyway for creating a session in Netty? Can anyone please provide an example. It will help others also.
A simple client that creates a session whenever it is connected to a server.

 JVM version :1.8
OS version :windows

**Comment by normanmaurer** [comment]
@Hema-Chandra what is a Session in mina ?

**Comment by Hema-Chandra** [comment]
Every time a client connects to the server, a new session is created on the server, and will be kept in memory until the client is disconnected. If you are using MINA on the client side, everytime you conect to a server, a session will be created on the client too.

A session is used to store persistent informations about the connection, plus any kind of information the client or the server might need to use during the request processing, and eventually during the whole session life.

This is also your access point for any operation you need to do on a session : sending messages, closing the session, etc...

You can get a sample look here: 
https://mina.apache.org/mina-project/userguide/ch4-session/ch4-session.html

**Comment by normanmaurer** [comment]
I guess `Channel.attr(...)` is what you are looking for to store stuff and then you would just use Channel.* or ChannelHandlerContext.* operations for write etc

**Comment by Hema-Chandra** [comment]
Sorry, I didn't get you. Can you please provide an example. I have been searching for this from past 9 days
