### ISSUE TITLE
The import io.netty.util.collection cannot be resolved

### ISSUE THREAD

**Issue by laosijikaichele** [netty/netty#6824]
### Steps to reproduce
download zip source from https://github.com/netty/netty/archive/netty-4.1.11.Final.zip
### Minimal yet complete reproducer code (or URL to code)
import to eclipse, get error:**The import io.netty.util.collection cannot be resolved**
![image](https://user-images.githubusercontent.com/29225782/26861213-0220d5c2-4b75-11e7-8334-fa28b6d080bd.png)
I searched the source files, not found the class: io.netty.util.collection.IntObjectHashMap
Is it missed?

**Comment by normanmaurer** [comment]
These are generated during build, run:

mvn clean package
