### ISSUE TITLE
FixedChannelPool throw java.lang.IllegalStateException: Channel is unhealthy not offering it back to pool

### ISSUE THREAD

**Issue by fian46** [netty/netty#6831]
Hi, i am trying to write some TCP stuff with FixedChannelPool. The documentation says i have to return any channel that borrow from pool even if the channel already dead, but when i do return the channel, FixedChannelPool throw java.lang.IllegalStateException: Channel is unhealthy not offering it back to pool.
Is this bug ?
if i don't release the channel to FixedChannelPool its never give any connection when dead channel count = max_pool_size.
if i just ignore the exception, everything works fine, but i think this should never happend.

### Expected behavior
i expect no exception thrown
### Actual behavior
throw  java.lang.IllegalStateException: Channel is unhealthy not offering it back to pool.
### Steps to reproduce
1. Create FixedChannelPool.
2. call aquire channel
3. kill channel
4. call release channel, but the returned ChannelFuture call get()
5. TA DA throw  java.lang.IllegalStateException: Channel is unhealthy not offering it back to pool.

### Minimal yet complete reproducer code (or URL to code)
`public class MaybeBug {`
`    @Test`
`    public void test() throws InterruptedException, ExecutionException{`
`        Bootstrap config = new Bootstrap();`
`        config.remoteAddress("localhost", 1234);`
`        config.option(ChannelOption.TCP_NODELAY, true);`
`        config.channel(NioSocketChannel.class);`
`        config.group(new NioEventLoopGroup(1));`
`        FixedChannelPool pool = new FixedChannelPool(config, new AbstractChannelPoolHandler() {`
`            @Override`
`            public void channelCreated(Channel ch) throws Exception {`
`                /**`
`                 * ignore`
`                 */`
`            }`
`        }, 2);`
`        Channel fresh = pool.acquire().get();`
`        fresh.close().get();`
`        pool.release(fresh).get();`
`    }
}`
### Netty version
4.1.5
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
Windows 10

NB: sorry for bad english.

**Comment by normanmaurer** [comment]
@fian46 please check https://github.com/netty/netty/pull/6843

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6843
