### ISSUE TITLE
Use of SCHEDULE_PURGE_INTERVAL

### ISSUE THREAD

**Issue by louxiu** [netty/netty#6834]
I think the name of [SCHEDULE_PURGE_INTERVAL](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java#L835) is misleading and I also doubt that whether `SCHEDULE_PURGE_INTERVAL` should be return if there is no scheduled task. Why not return a `MAX` value? Please take a look. @normanmaurer

**Comment by normanmaurer** [comment]
@louxiu because we want to check again in `SCHEDULE_PURGE_INTERVAL` if there are some canceled scheduled tasks that we need to purge

**Comment by louxiu** [comment]
got it. Thanks
