### ISSUE TITLE
Netty IdleStateHandler doesn't work if bytes stuck in ReplayingDecoder

### ISSUE THREAD

**Issue by niranjan-kachhawa** [netty/netty#6842]
### Expected behavior
It should close the channel after given expiry time in IdleStateHandler.

### Actual behavior
Doesn't close the channel if ByteBuf processing stuck in ReplayingDecoder

### Steps to reproduce
1. Given a string which have three fields : MacId, task, content but if we provide only MacId and Task then ReplayingDecoder hangs till he didn't received another chunk.

### Netty version
4.1.9.Final

### JVM version (e.g. `java -version`)
1.8

### OS version (e.g. `uname -a`)
issue on both, windows 7 and linux ubuntu 16

**Comment by Scottmitch** [comment]
are you interested in submitting a PR? I'm not sure who uses the ReplayingDecoder (/cc @trustin)

**Comment by trustin** [comment]
A user should place the `IdleStateHandler` before a decoder. This can happen to any decoder when `IdleStateHandler` is placed after the decoder. i.e. not a bug

**Comment by normanmaurer** [comment]
@trustin +1 ... Let me just add this to the java docs

**Comment by niranjan-kachhawa** [comment]
@trustin  that's correct. This solved my issue. Thanks :)

**Comment by normanmaurer** [comment]
@niranjan-kachhawa @trustin @Scottmitch FYI https://github.com/netty/netty/pull/6848
