### ISSUE TITLE
Reconsider growing strategy in HpackHuffmanDecoder

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#6846]
At the moment we just increase my intialCapacity but it may make sense to double it up to a certain size:

https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/HpackHuffmanDecoder.java#L237

**Comment by Scottmitch** [comment]
thanks for reporting @normanmaurer! My guess is this will have a measurable impact if the initial size is too small (currently defaults to 32).

**Comment by normanmaurer** [comment]
@Scottmitch agree... I would say we should double up to 512 bytes . WDYT ? I can do a pr

**Comment by Scottmitch** [comment]
It will depend upon the use case but can we derive a guess from https://github.com/http2/http_samples or some other sample size? We can start with 512 or 1024 and refine later if you don't have much cycles to investigate.

**Comment by normanmaurer** [comment]
@Scottmitch good idea... let me check

**Comment by normanmaurer** [comment]
@Scottmitch here you go https://github.com/netty/netty/pull/6857. I think I will have not much time to long into it in more detail so I just used 1024 for now

**Comment by Scottmitch** [comment]
1024 sounds like a good start to me ... we can revise/improve later if necessary.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6857
