### ISSUE TITLE
4.1.12.Final bom uses 4.1.12.Final-SNAPSHOT for the version of netty-transport-unix-common

### ISSUE THREAD

**Issue by wilkinsona** [netty/netty#6849]
### Expected behavior

The bom provides consistent versions for all of Netty's modules

### Actual behavior

netty-transport-unix-common is using a different (and snapshot) version

### Steps to reproduce

Import the bom and try to resolve netty-transport-unix-common from Maven Central

### Minimal yet complete reproducer code (or URL to code)

N/A

### Netty version

4.1.12.Final

### JVM version (e.g. `java -version`)

N/A

### OS version (e.g. `uname -a`)

N/A

**Comment by wilkinsona** [comment]
And now I've noticed that the module name's incorrect. I believe it should be `netty-transport-native-unix-common`. Sorry, if that's the case, I should have spotted it when reviewing https://github.com/netty/netty/pull/6740.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6851
