### ISSUE TITLE
Netty bom does not provide dependency management for netty-transport-native-epoll

### ISSUE THREAD

**Issue by snicoll** [netty/netty#6852]
### Expected behavior

The bom provides consistent versions for all of Netty's modules

### Actual behavior

No dependency management for ` io.netty:netty-transport-native-epoll` is available, leading to a potential mismatch

### Steps to reproduce

Import the bom and try to resolve `netty-transport-native-epoll` without a version.

### Minimal yet complete reproducer code (or URL to code)

N/A

### Netty version

4.1.12.Final

### JVM version (e.g. `java -version`)

N/A

### OS version (e.g. `uname -a`)

N/A

**Comment by Scottmitch** [comment]
Are you interested in submitting a PR?

**Comment by Scottmitch** [comment]
Oh I see PR https://github.com/netty/netty/pull/6853 now ... thanks!

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6853
