### ISSUE TITLE
Proposal: make SslHandler creation consistent with all other handlers

### ISSUE THREAD

**Issue by doom369** [netty/netty#6860]
Right now SslHandler creation look like this:

`pipeline.addLast(sslCtx.newHandler(ch.alloc()));`

However, it differs from the creation of all other handlers:

```
pipeline.addLast(new DelimiterBasedFrameDecoder(8192, Delimiters.lineDelimiter()));
pipeline.addLast(new StringDecoder());
pipeline.addLast(new StringEncoder());
```

Shouldn't `SslHanlder` follow the same pattern:

`pipeline.addLast(new SslHandler(sslCtx));`

WDYT?

Not a big deal, but consistency is always good.

**Comment by normanmaurer** [comment]
@doom369 I think it is ok how it is atm as it allows us to do some optimisations in some cases. That said you can create a `SslHandler` and five an SSLEngine by yourself if you like to.
