### ISSUE TITLE
netty4.1.9.Final openjdk8 connection refused

### ISSUE THREAD

**Issue by songxin1990** [netty/netty#6865]
I use circleci to build my project:
https://circleci.com/gh/songxin1990/brave/4
When using openjdk8,it occurs something like this:
![buildresult](https://user-images.githubusercontent.com/6946828/27224949-74981a28-52ca-11e7-94c6-c4dd3bdffa08.png)

After i modifed circle.yml to oraclejdk8,all the test past and none error happend.
https://circleci.com/gh/songxin1990/brave/7

**So,there must be something wrong with openjdk8 or netty4.1.9Final in openjdk8.**

### Steps to reproduce
1.  git clone git@github.com:songxin1990/brave.git
2.  modify circle.yml to openjdk8
3.  wait for circleci to build.
Then you can see:
java.net.ConnectException: Failed to connect to localhost/127.0.0.1:7654
Caused by: java.net.ConnectException: Connection refused

**For more details:**
https://github.com/openzipkin/brave/pull/441
[nettybuild.txt](https://github.com/netty/netty/files/1084479/nettybuild.txt)

Is there someone can help? @trustin @normanmaurer

**Comment by songxin1990** [comment]
@hepin1989  can you give me a hand?

**Comment by Scottmitch** [comment]
please isolate your issue into a unit test so we can take a look without digesting all of brave. also update to the latest Netty release (currently 4.1.12).

**Comment by songxin1990** [comment]
@Scottmitch  Ok,I will first try to use 4.1.12,then write a standalone unit test

**Comment by songxin1990** [comment]
holyshit,I  used a window's openjdk8 ,all the unit test passed.
then write a junit test with circle to build it, successed.
so it's not the openjdk8's problem.
