### ISSUE TITLE
ByteBuf which contatins multi direct buffers(eg. CompositeByteBuf) needs no extra copy before send

### ISSUE THREAD

**Issue by louxiu** [netty/netty#6870]
### Expected behavior
ByteBuf which contains multi direct buffers(eg. CompositeByteBuf) needs no extra copy in `filterOutboundMessage`. Related commit https://github.com/netty/netty/pull/6825

### Actual behavior
Extra copy is made with function `UnixChannelUtil#isBufferCopyNeededForWrite`

### Netty version
4.0.48

**Comment by normanmaurer** [comment]
This was merged
