### ISSUE TITLE
HTTP/2 Prior Knowledge does not appear to work with Http2Codec and Http2ServerDowngrader

### ISSUE THREAD

**Issue by rschmitt** [netty/netty#6881]
### Expected behavior

The `CleartextHttp2ServerUpgradeHandler` should work with both HTTP Upgrade and Prior Knowledge when downgrading HTTP/2 requests internally.

### Actual behavior

HTTP Upgrade works, but not Prior Knowledge. In the latter case, nghttp reports: `(last_stream_id=0, error_code=PROTOCOL_ERROR(0x01), opaque_data(96)=[HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 000000040100000000])`

### Steps to reproduce

1. Fire up `io.netty.example.http2.helloworld.server.Http2Server` with the modifications described in the next section
2. Install `nghttp`
3. Run `nghttp --upgrade --verbose --no-dep http://localhost:8080/`; it should succeed
4. Run `nghttp --verbose --no-dep http://localhost:8080/`; it fails like so:

```
[  0.002] Connected
[  0.002] send SETTINGS frame <length=12, flags=0x00, stream_id=0>
          (niv=2)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):65535]
[  0.002] send HEADERS frame <length=33, flags=0x05, stream_id=1>
          ; END_STREAM | END_HEADERS
          (padlen=0)
          ; Open new stream
          :method: GET
          :path: /
          :scheme: http
          :authority: localhost:8080
          accept: */*
          accept-encoding: gzip, deflate
          user-agent: nghttp2/1.23.1
[  0.005] recv SETTINGS frame <length=6, flags=0x00, stream_id=0>
          (niv=1)
          [SETTINGS_MAX_HEADER_LIST_SIZE(0x06):8192]
[  0.005] send SETTINGS frame <length=0, flags=0x01, stream_id=0>
          ; ACK
          (niv=0)
[  0.006] recv GOAWAY frame <length=104, flags=0x00, stream_id=0>
          (last_stream_id=0, error_code=PROTOCOL_ERROR(0x01), opaque_data(96)=[HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 000000040100000000])
Some requests were not processed. total=1, processed=0
```

### Minimal yet complete reproducer code (or URL to code)

Run the `Http2Server` example code, using the following modified `configureClearText` method:

```java
    private void configureClearText(SocketChannel ch) {
        final ChannelPipeline p = ch.pipeline();
        final HttpServerCodec sourceCodec = new HttpServerCodec();

        final Http2Codec http2Codec = new Http2CodecBuilder(true, new ChannelInitializer<Channel>() {
            @Override
            protected void initChannel(Channel channel) throws Exception {
                ChannelPipeline p = channel.pipeline();
                p.addLast("downgrader", new Http2ServerDowngrader(true));
                p.addLast("chunk-aggregator", new HttpObjectAggregator(1048576));
                p.addLast("http1-handler", new HelloWorldHttp1Handler("Downgrade"));
            }
        }).build();

        final UpgradeCodecFactory upgradeCodecFactory = new UpgradeCodecFactory() {
            @Override
            public UpgradeCodec newUpgradeCodec(CharSequence protocol) {
                if (AsciiString.contentEquals(Http2CodecUtil.HTTP_UPGRADE_PROTOCOL_NAME, protocol)) {
                    return new Http2ServerUpgradeCodec("server-upgrade-codec", http2Codec);
                } else {
                    return null;
                }
            }
        };

        final HttpServerUpgradeHandler upgradeHandler = new HttpServerUpgradeHandler(sourceCodec, upgradeCodecFactory);

        final CleartextHttp2ServerUpgradeHandler cleartextHttp2ServerUpgradeHandler =
            new CleartextHttp2ServerUpgradeHandler(sourceCodec, upgradeHandler, http2Codec);

        p.addLast(cleartextHttp2ServerUpgradeHandler);

        p.addLast(new SimpleChannelInboundHandler<HttpMessage>() {
            @Override
            protected void channelRead0(ChannelHandlerContext ctx, HttpMessage msg) throws Exception {
                // If this handler is hit then no upgrade has been attempted and the client is just talking HTTP.
                System.err.println("Directly talking: " + msg.protocolVersion() + " (no upgrade was attempted)");
                ChannelPipeline pipeline = ctx.pipeline();
                ChannelHandlerContext thisCtx = pipeline.context(this);
                pipeline.addAfter(thisCtx.name(), null, new HelloWorldHttp1Handler("Direct. No Upgrade Attempted."));
                pipeline.replace(this, null, new HttpObjectAggregator(maxHttpContentLength));
                ctx.fireChannelRead(ReferenceCountUtil.retain(msg));
            }
        });

        p.addLast(new UserEventLogger());
    }
```

### Netty version

Latest `4.1` branch

### JVM version (e.g. `java -version`)

java 8u131

### OS version (e.g. `uname -a`)

macOS 10.12.4

**Comment by normanmaurer** [comment]
@Scottmitch can you take a look ?

**Comment by chhsiao90** [comment]
I think I can take a look for this issue!

**Comment by normanmaurer** [comment]
@chhsiao90 <3... That would be awesome.

**Comment by chhsiao90** [comment]
Here is my finding, I think it's a little hard to be fixed.

#### For Conclusion
Currently, ```CleartextHttp2ServerUpgradeHandler``` cannot work well with ```Http2Codec```.

#### How CleartextHttp2ServerUpgradeHandler Works
```CleartextHttp2ServerUpgradeHandler``` will peek the first 24 bytes to see that it's HTTP2 preface or not, and then it will remove it from the pipeline so that the inbound bytes will forward to the handler after ```CleartextHttp2ServerUpgradeHandler```.

#### What happened when using Http2Codec with CleartextHttp2ServerUpgradeHandler
##### When channel initialized
The ```CleartextHttp2ServerUpgradeHandler``` will add ```PriorKnowledgeHandler``` into the pipeline and remove itself from pipeline.
```
+---------------------------------- Pipeline ---------------------------+
| +------+         +------------------------+                 +------+  |
| | Head |  -->    | PriorKnowledgeHandler  | -->  ..... ->   | Tail |  |
| +------+         +------------------------+                 +------+  |
+-----------------------------------------------------------------------+
```
And ```PriorKnowledgeHandler``` will start to **peek** (will not consume) the inbound, and determine the protocol and configure pipeline when it knows about the protocol.

##### When detect HTTP2 connection preface
When ```PriorKnowledgeHandler``` found HTTP2 connection preface, it will add handlers for HTTP2 and remove itself. After ```PriorKnowledgeHandler``` was removed, the inbound will forward to **The handler after PriorKnowledgeHandler** <- This is the point.

Here is the steps what handler added/removed.
1. [PriorKnowledgeHandler] Replace PriorKnowledgeHandler with Http2Codec
2. [Http2Codec] Add Http2FrameCodec before itself
3. [Http2FrameCodec] Add Http2ConnectionHandler before itself
4. [Http2Codec] Add Http2MultiplexCodec before itself
5. [Http2Codec] Remove itself
6. And other stuff

After that, the pipeline will look like
```
(H) -> Head
(T) -> Tail
+---------------------------------- Pipeline -------------------+
| +---+        +-----------------------+                  +---+ |
| | H |  -->  | Http2ConnectionHandler | -->  ..... -->   | T | |
| ----+        +-----------------------+                  +---+ |
+---------------------------------------------------------------+
Outside pipeline
+------------------------+    +------------+             +---+
| PriorKnowledgeHandler | --> | Http2Codec | --> ... --> | T |
+------------------------+    +------------+             +---+
```
So we can see the inbound bytes was forward to orphan handlers, not forward to Http2ConnectionHandler.

#### Solution or Workaround
Currently, I don't have any idea about solution or workaround, but will keep think about it.

**Comment by rschmitt** [comment]
Are you saying that the inbound bytes are getting forwarded to `Http2Codec`, even though it has been removed from the pipeline?

**Comment by chhsiao90** [comment]
Yes, that's what I mean!

**Comment by rschmitt** [comment]
It sounds like there's a much deeper design issue here. Why does Netty allow a Handler to pass an event via its `ChannelHandlerContext` when that Handler is no longer present in the pipeline and therefore does not have a defined position in that pipeline? After all, the `ChannelHandlerContext` represents a Handler's association with a pipeline--shouldn't it throw an `IllegalStateException` as soon as you try to do this?

And as for the various HTTP2 pipeline components, do they really need to rely on pipeline mutation so heavily? Your root cause analysis seems like a great example of how complex mutation-oriented programming can be *even in a single-threaded context*.

As for a fix, can `PriorKnowledgeHandler` add `Http2Codec` after itself (instead of calling `replace`), propagate the data down the pipeline, and *then* remove itself from the pipeline?

**Comment by chhsiao90** [comment]
@rschmitt - I address a PR to fix this issue! PTAL

**Comment by rschmitt** [comment]
@normanmaurer Can you provide any insight as to whether this may represent a bug in `replace` and/or the behavior of a `ChannelHandlerContext` after it has been removed from a pipeline?

**Comment by normanmaurer** [comment]
@rschmitt sorry I am quite busy atm... Generally speaking I would love to change the contract to throw an `IllegalStateException` if someone tries to do operations after the handler was removed from the pipeline. That said I think this may break user-code and so is a breaking change so it can not be done in a non major release :/

**Comment by rschmitt** [comment]
Right, it would have to be done as an opt-in change. Maybe something like:

1. Define a system property (`io.netty.channel.ChannelHandlerContext.enforcePipelineMembership` or something)
2. Throw an `IllegalStateException` when the above property is set
3. When the above property is not set, log an error the first time this illegal state is detected
4. Run all of Netty's tests with the `enforcePipelineMembership` property set to ensure that this bug isn't hiding anywhere else in Netty's codebase
5. Document that passing events to a removed context has undefined behavior and will be made illegal in a future release

**Comment by normanmaurer** [comment]
@rschmitt @Scottmitch @chhsiao90 https://github.com/netty/netty/pull/7035 is a better fix imho... PTAL

**Comment by normanmaurer** [comment]
Nevermind let me pull this one in for now...

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6952

**Comment by Scottmitch** [comment]
> Nevermind let me pull this one in for now...

@normanmaurer - can you explain this change in opinion?

**Comment by normanmaurer** [comment]
@Scottmitch see what @ejona86 said in https://github.com/netty/netty/pull/7035... We may want to reconsider even remove `replace(...)` in next major release. But I need to think more about this...
