### ISSUE TITLE
channelInactive() not getting called when ctx.close() is called on the ChannelHandlerContext

### ISSUE THREAD

**Issue by lothbrok72** [netty/netty#6894]
### Expected behavior
channelInactive() gets called when ctx.close() is called on the ChannelHandlerContext

### Actual behavior
channelInactive() does not get called when ctx.close() is called on the ChannelHandlerContext.

### Steps to reproduce
We have a test where we write invalid xml to a test channel. ctx.close() is called within exceptionCaught() and I would expect channelInactive to fire. The test is as below. Assert.assertTrue(listener.connectionClosed) is currently failing whereas it was previously passing when using netty-handler 4.0.28.Final. 

        listener.connectionError = null;
        Assert.assertFalse(listener.connectionClosed);
        TestUtils.writeInbound(channel, xml5);
        Assert.assertEquals(null, readNext());
        Assert.assertNotNull(listener.connectionError);
        Assert.assertTrue(listener.connectionClosed);

### Minimal yet complete reproducer code (or URL to code)

    @Override
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable exc) {
        if (connectionListener == null) {
            return;
        }
        // Treat unexpected exceptions as fatal to the connection
        try {
            connectionListener.connectionError(exc);
        } finally {
            ctx.close();
        }
    }

    @Override
    public void channelInactive(ChannelHandlerContext ctx) throws Exception {
        if (connectionListener == null) {
            return;
        }
        connectionListener.connectionClosed();
    }

### Netty version
netty-all 4.1.11.FINAL

**Comment by normanmaurer** [comment]
@lothbrok72 can you come up with a test-case please ?

**Comment by lothbrok72** [comment]
@normanmaurer Our current test case (Invalid XML file, should cause a connection exception and connection close)
- We write a file containing invalid xml to an EmbeddedChannel
- call poll() on the CollectingListener
- check that a connectionError has been thrown
- check that the connection has been closed i.e. channelInactive was called.

I can provide more code of out test setup if required.

Also, seems to work fine when I call ctx.channel().close() instead of ctx.close().

**Comment by normanmaurer** [comment]
So this happens with EmbeddedChannel correct? Like the ChannelHandler is in the pipeline of an EmbeddedChannel?

**Comment by lothbrok72** [comment]
Yes it is an EmbeddedChannel:

    @Before
    public void before() {
        listener = new CollectingListener();
        sync = new SyncStreamRestart();
        Debugger debugger = new ConsoleDebugger();
        EventExecutorGroup listenerExecutor = ImmediateEventExecutor.INSTANCE;
        XmppPipeline xmppPipeline = new XmppPipeline(listener, sync, listenerExecutor, debugger);
        channel = new EmbeddedChannel(xmppPipeline);
    }

**Comment by normanmaurer** [comment]
@lothbrok72 can you also show me the `XmppPipeline` class ?

**Comment by lothbrok72** [comment]
@normanmaurer of course:

public class XmppPipeline extends ChannelInitializer<Channel> {

    private final ConnectionListener eventListener;
    private final Debugger debugger;
    private final SyncStreamRestart sync;
    private final EventExecutorGroup listenerThreadPool;

    public XmppPipeline(ConnectionListener eventListener, SyncStreamRestart sync, EventExecutorGroup listenerExector) {
        this(eventListener, sync, listenerExector, null);
    }

    public XmppPipeline(ConnectionListener eventListener, SyncStreamRestart sync,
            EventExecutorGroup listenerThreadPool, Debugger debugger) {
        this.eventListener = eventListener;
        this.sync = sync;
        this.debugger = debugger;
        this.listenerThreadPool = listenerThreadPool;
    }

    @Override
    public void initChannel(Channel ch) {
        ch.pipeline().addLast(new XmlEventDecoder(sync), new XmppEventDecoder(debugger));
        ch.pipeline().addLast(listenerThreadPool, new XmppEventDispatcher(eventListener));

        if (debugger != null) {
            ch.pipeline().addLast(new DebugHandler(debugger));
        }
        ch.pipeline().addLast(new XmppEncoder());
    }
}

**Comment by normanmaurer** [comment]
Can I also see `XmppEventDispatcher `  :)

**Comment by lothbrok72** [comment]
Here you go:

class XmppEventDispatcher extends ChannelInboundHandlerAdapter {

    private static final Logger LOG = MchLoggerFactory.getLogger(XmppEventDispatcher.class);

    private final ConnectionListener connectionListener;

    /**
     * @param connectionListener Listener to dispatch events to. If null, no events will be dispatched.
     */
    public XmppEventDispatcher(ConnectionListener connectionListener) {
        this.connectionListener = connectionListener;
    }

    @Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) {
        if (connectionListener == null) {
            return;
        }

        if (msg instanceof StreamError) {
            StreamErrorException exc = new StreamErrorException((StreamError)msg);
            connectionListener.connectionError(exc);
            // As per XMPP spec, server will close connection after a stream error
        } else {
            connectionListener.accept(msg);
        }
    }

    @Override
    public void channelInactive(ChannelHandlerContext ctx) throws Exception {
        if (connectionListener == null) {
            return;
        }
        connectionListener.connectionClosed();
    }

    @Override
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable exc) {
        if (exc instanceof DecoderException) {
            // Log and ignore messages with XMPP extensions that we don't support
            Throwable cause = exc.getCause();
            if (cause instanceof XmppMarshalException) {
                LOG.error("Ignoring unparseable message: {}", cause.getMessage(), cause);
                return;
            }
        }

        if (connectionListener == null) {
            return;
        }

        // Treat unexpected exceptions as fatal to the connection
        try {
            connectionListener.connectionError(exc);
        } finally {
            ctx.close();
        }
    }
}

**Comment by normanmaurer** [comment]
@lothbrok72 please check https://github.com/netty/netty/pull/6897. This fixes the problem

**Comment by lothbrok72** [comment]
Great, thank you @normanmaurer

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6897
