### ISSUE TITLE
HttpPostRequestDecoder decode json error contains =and%

### ISSUE THREAD

**Issue by zyhui98** [netty/netty#6898]
### Expected behavior
decode right

### Actual behavior
io.netty.handler.codec.http.multipart.HttpPostRequestDecoder$ErrorDataDecoderException: Bad string: '%"}'

### Steps to reproduce
`

		LastHttpContent content = new DefaultLastHttpContent(
				Unpooled.copiedBuffer("{\"currentPage\":1,\"pageSize\":10,\"token\":\"9897c020356401a027bbd0df8ac40921\",\"reportItemName\":\"dfdfdfd =%\"}",
						CharsetUtil.UTF_8));
		DefaultHttpRequest defaultHttpRequest =
				new DefaultHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.POST, "/");
		HttpPostRequestDecoder decoder = new HttpPostRequestDecoder(defaultHttpRequest);

		try {
			decoder.offer(content).getBodyHttpDatas().get(0).touch().toString();
		} catch (HttpPostRequestDecoder.ErrorDataDecoderException e) {
			e.printStackTrace();
		} finally {
			decoder.destroy();
			content.release();
		}
	

`

### Netty version
4.1.12
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
windows and linux

```

**Comment by fenik17** [comment]
I think, yours HTTP POST request is incorrect.. Looks like [testFormEncodeIncorrect](https://github.com/netty/netty/blob/0bc30a123e88bc7b038e0c260937581097a903f7/codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestDecoderTest.java#L479).
This is variant works fine:

```java
String boundary = "dLV9Wyq26L_-JQxk6ferf-RT153LhOO";
DefaultFullHttpRequest req = new DefaultFullHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.POST, "/");
req.headers().add(HttpHeaderNames.CONTENT_TYPE, "multipart/form-data; boundary=" + boundary);
String data = "{\"currentPage\":1,\"pageSize\":10,\"token\":\"9897c020356401a027bbd0df8ac40921\",\"reportItemName\":\"dfdfdfd =%\"}";
String body =
		"--" + boundary + "\r\n" +
		"Content-Disposition: form-data; name=\"form\"\r\n" +
		"Content-Type: text/plain\r\n" +
		"\r\n" +
		data + "\r\n" +
		"--" + boundary + "--\r\n";

req.content().writeBytes(body.getBytes(CharsetUtil.UTF_8));
HttpPostRequestDecoder decoder = new HttpPostRequestDecoder(new DefaultHttpDataFactory(false), req);
String data2 = ((Attribute) decoder.getBodyHttpDatas().get(0)).getValue();
System.out.println(data.equals(data2)? "SUCCESS" : "ERROR");
decoder.destroy();
```

**Comment by fenik17** [comment]
If you don't want to use `multipart/form-data` content type, and want use `application/x-www-form-urlencoded` instead, you should encode query params and values (e.g. through `QueryStringEncoder` or `URLEncoder`).

**Comment by normanmaurer** [comment]
As @fenik17  said... Let me close this

**Comment by zyhui98** [comment]
ok，I Know，thank fenik17
