### ISSUE TITLE
Typo? EpollSocketChannelConfig.setTcpKeepCntl

### ISSUE THREAD

**Issue by testn** [netty/netty#6909]
https://github.com/netty/netty/blob/3cc405296310643bccddc8c81998c97f25b3201c/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollSocketChannelConfig.java#L420

shouldn't it be called setTcpKeepCnt?

**Comment by johnou** [comment]
yep but it's public so it cannot be changed until the next major version.

**Comment by normanmaurer** [comment]
It can not be changed but we can add a new method and deprecate the old one... let me do in a few minutes

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6910. Please check

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6910
