### ISSUE TITLE
netty-all:4.1.12.Final resolve with IPV4_PREFERRED cannot resolve IPv6 addresses

### ISSUE THREAD

**Issue by jianyuanzh** [netty/netty#6925]
### Expected behavior
I have a dns configured with IPv6 address only. When construct the netty dns resolver, I choose IPV4_PREFERRED mode. From the comments, with this configure, resolver should be able to resolve out IPv6 address. 

### Actual behavior
But the created resolver cannot resolve the dns which only has IPv6 address. 

### Steps to reproduce
```java
_innerBuilder = new DnsNameResolverBuilder(loopGroup.next())
                    .channelType(NioDatagramChannel.class)
                    .resolvedAddressTypes(ResolvedAddressTypes.IPV4_PREFERRED)

_innerBuilder.resolve("ipv6only.domain.com")
```

Notice, the domain here is not a real domain, my ipv6 domain is a local domain and cannot access from internet. 

### Netty version
netty-all:4.1.12

### JVM version (e.g. `java -version`)
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```
### OS version (e.g. `uname -a`)
```
Linux dev-testing 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by normanmaurer** [comment]
@slandelle can you have a look as you added this ?

**Comment by slandelle** [comment]
Sure. Travelling atm. Will have a look this weekend.

**Comment by normanmaurer** [comment]
@slandelle <3 Thanks buddy!

**Comment by Scottmitch** [comment]
Don't we have unit tests to cover this case (away from computer)?

**Comment by normanmaurer** [comment]
@Scottmitch I thought so... but maybe there is something wrong...

**Comment by slandelle** [comment]
I've tried to reproduce, with no luck so far:
* modify `TestDnsServer` so it doesn't return A records (remove [those lines](https://github.com/netty/netty/blob/4.1/resolver-dns/src/test/java/io/netty/resolver/dns/TestDnsServer.java#L277-L279))
* run `mvn -Dtest=DnsNameResolverTest#testResolveAorAAAA test` on `resolver-dns` module

=> test passes

I don't have a real world IPv6 only domain at hand, so I'm not sure I can help much here :(

**Comment by normanmaurer** [comment]
@jianyuanzh is this still an issue ? We failed to reproduce so far :(

**Comment by jianyuanzh** [comment]
@normanmaurer , please close this. We have no such issue in prod environment.

**Comment by normanmaurer** [comment]
Closing as requested.
