### ISSUE TITLE
netty Dns resolver can not work properly with two dns servers when one of the dns server cannot work

### ISSUE THREAD

**Issue by betaxer** [netty/netty#6926]
### Expected behavior
My device is configured with two dns servers:
```
nameserver 10.130.10.7
nameserver 114.114.114.114
```
Here, the 10.130.10.7 is a dead dns server, and with this configure, InetAddress.getByName() can resolve dns. I expect the netty resolver can work too.
### Actual behavior
But exactly, the netty resolver cannot work with this configure. 

### Steps to reproduce
Add an invalid dns server to the dns server list. Or, specify MultiDnsServerAddressStreamProvider with one bad dns server address and one good server address, and test on the domains. 
 
### Minimal yet complete reproducer code (or URL to code)
```
NioEventLoopGroup loopGroup = new NioEventLoopGroup(1);

        DnsNameResolver resolver = new DnsNameResolverBuilder(loopGroup.next())
                .channelType(NioDatagramChannel.class)
                .nameServerProvider(
                        new MultiDnsServerAddressStreamProvider(
                                new SingletonDnsServerAddressStreamProvider(SocketUtils.socketAddress("10.130.10.7", 53)),
                                new SingletonDnsServerAddressStreamProvider(SocketUtils.socketAddress("114.114.114.114", 53))
                        )
//                        new RotationalDnsServerAddressStreamProvider(DnsServerAddresses.rotational(
////                                SocketUtils.socketAddress("10.130.10.17", 53),
//                                SocketUtils.socketAddress("114.114.114.114", 53)
//                        ))
                )
                .maxQueriesPerResolve(2)
                .build();


        AtomicLong failed = new AtomicLong();

        DOMAINS.parallelStream().forEach(dns -> {
            try {
                LogMsg.info("", "" + resolver.resolve(dns).sync().getNow());
            }
            catch (Exception e) {
                failed.incrementAndGet();
                LogMsg.warn("resolve failed", "" + dns + ": " + e.getMessage());
            }
        });
```
### Netty version
Netty-all 4.1.12.Final
### JVM version (e.g. `java -version`)
1.8_131
### OS version (e.g. `uname -a`)
Mac Os  and CentOs.

**Comment by normanmaurer** [comment]
@betaxer dead server means it will not respond at all ?

**Comment by Scottmitch** [comment]
Can you send a tcpdump or wireshark of the JDK resolution and Netty's resolution to clarify?

**Comment by betaxer** [comment]
Hi, @Scottmitch , I have uploaded a wireshark capture files for both InetAddres.getByName and our netty dns resolve.  
For JDK dns resolve, it will query both dns servers, but netty will query only one of the two dns server for every url

[dns_resolve.zip](https://github.com/netty/netty/files/1118894/dns_resolve.zip)

**Comment by Scottmitch** [comment]
@betaxer - There were a few issues. See PR https://github.com/netty/netty/pull/6937. However using `MultiDnsServerAddressStreamProvider` will not give you the expected results. You should use something like `SequentialDnsServerAddressStreamProvider`. `DnsServerAddressStreamProvider` is expected to return the `DnsServerAddressStream` which should be used for a query, and only a single one will be used per query.

**Comment by betaxer** [comment]
@Scottmitch , thanks. Using MultiDnsServerAddressStreamProvider works for me as a workaround.
