### ISSUE TITLE
lose data when send 100000 of syslog per second by UDP

### ISSUE THREAD

**Issue by txf7337** [netty/netty#6929]
### Expected behavior
receive all of syslog
### Actual behavior
lose syslog when first time to receive
### Steps to reproduce
start app and use tool send data by udp
### Minimal yet complete reproducer code (or URL to code)
    private void initUDPServer() {
        final EventLoopGroup group;
        final Class<? extends DatagramChannel> datagramChannelClass;
        if (Epoll.isAvailable()) {
            group = new EpollEventLoopGroup();
            datagramChannelClass = EpollDatagramChannel.class;
        } else {
            group = new NioEventLoopGroup();
            datagramChannelClass = NioDatagramChannel.class;
        }
        Bootstrap b = new Bootstrap();
        b.group(group)
                .channel(datagramChannelClass)
                .handler(new ChannelInitializer<Channel>() {
                    @Override
                    public void initChannel(Channel ch) throws Exception {
                        ch.pipeline().addLast(new DatagramPacketDecoder(new LogDecoder()), new FileHandler());
                    }
                });
        b.bind(nettyConfig.getPort());
    }
    protected void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) throws Exception {
        if (in.readInt() == 0xabcdabcd) {
            byte[] bytes = new byte[in.readableBytes()];
            in.readBytes(bytes);
            out.add(bytes);
        }

    protected void decode(ChannelHandlerContext ctx, byte[] msg, List<Object> out) throws Exception {
        final short version = (short) (msg[1] & 0xff | (msg[0] & 0xff) << 8);
        final short count = (short) (msg[3] & 0xff | (msg[2] & 0xff) << 8);
        l += count;
    }
### Netty version
4.1.12.final
### JVM version (e.g. `java -version`)
1.6.0_45
### OS version (e.g. `uname -a`)
Linux localhost.localdomain 3.2.82-1.el5.elrepo #1 SMP PREEMPT Tue Aug 23 12:08:46 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by txf7337** [comment]
I try to use FixedRecvByteBufAllocator(65536) or set allocator.pageSize/marOrder/numDirectArenas,but not work

**Comment by Scottmitch** [comment]
please provide a complete/minimal reproducer and explain all steps required to reproduce.

**Comment by txf7337** [comment]
the tool is writed by language c, and not mine.
is somewhere alloc memory not fast,so rewrited and no error log

**Comment by Scottmitch** [comment]
In general please be more specific about your description. We are not aware of any context that you operate in nor the conditions which lead to this issue.

> the tool is writed by language c, and not mine.

What tool are you talking about, and why do we need the source code for this tool?

> is somewhere alloc memory not fast

In Netty or in this tool?

> so rewrited and no error log

Does this mean you resolved the issue and we can close this?

**Comment by normanmaurer** [comment]
Let me close this for now.. please re-open and provide more infos if you still think this is a netty issue.
