### ISSUE TITLE
java.lang.AbstractMethodError: java.nio.channels.SocketChannel.bind

### ISSUE THREAD

**Issue by Donaldhan** [netty/netty#6934]
my os is win10, jdk is 1.7.0.17,netty is 4.1.12. I try run the  MsgEchoServer/Client example in udt package, 
then  MsgEchoServer is started, when start the MsgEchoClient,get this errror:

[INFO ] 2017-07-02 21:57:25 io.netty.handler.logging.LoggingHandler [id: 0xdf676102] REGISTERED
[INFO ] 2017-07-02 21:57:25 io.netty.handler.logging.LoggingHandler [id: 0xdf676102] CONNECT: /192.168.32.129:10020
Exception in thread "main" java.lang.AbstractMethodError: java.nio.channels.SocketChannel.bind(Ljava/net/SocketAddress;)Ljava/nio/channels/SocketChannel;
	at io.netty.util.internal.SocketUtils$4.run(SocketUtils.java:96)
	at io.netty.util.internal.SocketUtils$4.run(SocketUtils.java:93)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.SocketUtils.bind(SocketUtils.java:93)
	at io.netty.channel.udt.nio.NioUdtMessageConnectorChannel.doBind(NioUdtMessageConnectorChannel.java:101)
	at io.netty.channel.udt.nio.NioUdtMessageConnectorChannel.doConnect(NioUdtMessageConnectorChannel.java:112)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:254)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:530)
	at io.netty.handler.logging.LoggingHandler.connect(LoggingHandler.java:201)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:545)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:530)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:512)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:985)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:255)
	at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:252)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:722)
[INFO ] 2017-07-02 21:57:25 io.netty.handler.logging.LoggingHandler [id: 0xdf676102] CLOSE
[DEBUG] 2017-07-02 21:57:25 com.barchart.udt.SocketUDT done : [id: 0x217cc2f8] DATAGRAM CLOSED bind=null:0 peer=null:0
[INFO ] 2017-07-02 21:57:25 io.netty.handler.logging.LoggingHandler [id: 0xdf676102] UNREGISTERED
[DEBUG] 2017-07-02 21:57:25 com.barchart.udt.EpollUDT ep 1 rem [id: 0x217cc2f8] DATAGRAM CLOSED bind=null:0 peer=null:0
.
i search some resolves,buf has no effect.
i wonder the question of udt dependency barchart-udt-bundle,   my as follow,

 <dependency>
	    <groupId>com.barchart.udt</groupId>
	    <artifactId>barchart-udt-bundle</artifactId>
	    <version>2.3.0</version>
</dependency>

or java compiler?

MsgEchoServer :
```
public final class MsgEchoServer {
	private static final Logger log = LoggerFactory.getLogger(MsgEchoServer.class);
	public static final String ip = System.getProperty("host", "192.168.32.129");
    static final int port = Integer.parseInt(System.getProperty("port", "10020"));

    @SuppressWarnings("deprecation")
	public static void main(String[] args) throws Exception {
        final ThreadFactory acceptFactory = new DefaultThreadFactory("accept");
        final ThreadFactory connectFactory = new DefaultThreadFactory("connect");
        final NioEventLoopGroup acceptGroup =
                new NioEventLoopGroup(1, acceptFactory, NioUdtProvider.MESSAGE_PROVIDER);
        final NioEventLoopGroup connectGroup =
                new NioEventLoopGroup(1, connectFactory, NioUdtProvider.MESSAGE_PROVIDER);

        // Configure the server.
        try {
            final ServerBootstrap boot = new ServerBootstrap();
            boot.group(acceptGroup, connectGroup)
                    .channelFactory(NioUdtProvider.MESSAGE_ACCEPTOR)
                    .option(ChannelOption.SO_BACKLOG, 10)
                    .handler(new LoggingHandler(LogLevel.INFO))
                    .childHandler(new ChannelInitializer<UdtChannel>() {
                        @Override
                        public void initChannel(final UdtChannel ch)
                                throws Exception {
                            ch.pipeline().addLast(
                                    new LoggingHandler(LogLevel.INFO),
                                    new MsgEchoServerHandler());
                        }
                    });
            InetSocketAddress inetSocketAddress = new InetSocketAddress(ip,port);
            // Start the server.
            final ChannelFuture future = boot.bind(inetSocketAddress).sync();
            log.info("=========UDT Server is start=========");
            // Wait until the server socket is closed.
            future.channel().closeFuture().sync();
        } finally {
            // Shut down all event loops to terminate all threads.
            acceptGroup.shutdownGracefully();
            connectGroup.shutdownGracefully();
        }
    }
}
```
MsgEchoClient :
```
public final class MsgEchoClient {
    private static final Logger log = LoggerFactory.getLogger(MsgEchoClient.class);
    public static final String ip = System.getProperty("host", "192.168.32.129");
    static final int port = Integer.parseInt(System.getProperty("port", "10020"));
    public static final int SIZE = Integer.parseInt(System.getProperty("size", "256"));

    @SuppressWarnings("deprecation")
	public static void main(String[] args) throws Exception {

        // Configure the client.
        final ThreadFactory connectFactory = new DefaultThreadFactory("connect");
        final NioEventLoopGroup connectGroup = new NioEventLoopGroup(1,
                connectFactory, NioUdtProvider.MESSAGE_PROVIDER);
        try {
            final Bootstrap boot = new Bootstrap();
            boot.group(connectGroup)
                    .channelFactory(NioUdtProvider.MESSAGE_CONNECTOR)
                    .handler(new ChannelInitializer<UdtChannel>() {
                        @Override
                        public void initChannel(final UdtChannel ch)
                                throws Exception {
                            ch.pipeline().addLast(
                                    new LoggingHandler(LogLevel.INFO),
                                    new MsgEchoClientHandler());
                        }
                    });
            InetSocketAddress inetSocketAddress = new InetSocketAddress(ip,port);
            log.info("=========UDT Client is start=========");
            // Start the client.
            final ChannelFuture f = boot.connect(inetSocketAddress).sync();
            // Wait until the connection is closed.
            f.channel().closeFuture().sync();
        } finally {
            // Shut down the event loop to terminate all threads.
            connectGroup.shutdownGracefully();
        }
    }
}

```

**Comment by fenik17** [comment]
Maybe related for #6146.

**Comment by fenik17** [comment]
@Donaldhan just guessing.. Сan you decompile `SocketChannelUDT` class file from yours local jar file `barchart-udt-bundle-2.3.0.jar`? If there is no method `bind(final SocketAddress localAddress)`, maybe library builded for java 6.

**Comment by Donaldhan** [comment]
@fenik17 
decompile result:
```
 public SocketChannelUDT bind(SocketAddress localAddress)
        throws IOException
    {
        socketUDT.bind((InetSocketAddress)localAddress);
        return this;
    }
```
the bind method  exists

**Comment by Donaldhan** [comment]
i run the UDTClientServerConnectionTest in package testsuit, is right , but the test demo is to Verify UDT connect/disconnect life cycle with  UDT Byte Stream mode, no the UDT Message Flow.

and from NioUdtMessageConnectorChannel  source, is Deprecated, and  no longer maintained and will be removed, why remove in netty 4.1.12 ? the #6146 is in 20170120, and SocketUtils is commit , then
netty 4.1.12 was realease in 20170609 ?

**Comment by fenik17** [comment]
@tbrooks8 can you look?

**Comment by tbrooks8** [comment]
This is the same case as the `NioUdtByteConnectorChannel`. SocketChannelUDT does not have the java 7 `bind()` method. It will need the same thing [workaround](https://github.com/netty/netty/blob/4.1/transport-udt/src/main/java/io/netty/channel/udt/nio/NioUdtByteConnectorChannel.java#L198) as `NioUdtByteConnectorChannel`.

It has a `bind` method with an identical signature. But it was compiled for java 6.

**Comment by fenik17** [comment]
@tbrooks8 thanks!

@Donaldhan I think it will help: #6940.

**Comment by fenik17** [comment]
Note that udt transport is deprecated atm: #6471

**Comment by Donaldhan** [comment]
@fenik17 
@tbrooks8 
thanks

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6940
