### ISSUE TITLE
HashedWheelTimer does not always respect maxPendingTimeouts

### ISSUE THREAD

**Issue by kevinoliver** [netty/netty#6947]
### Expected behavior

HashedWheelTimer should respect the `maxPendingTimeouts` parameter.

### Actual behavior

When the value is unlimited (e.g. `<= 0`), users can still hit an `java.lang.IllegalStateException: Queue full` from the underlying Queue which comes from `PlatformDependent.newMpscQueue()` in the constructor.

### Steps to reproduce

Create a HashedWheelTimer with unlimited `maxPendingTimeouts` then add a task that never completes (e.g. `while (true) println("hi");`). Then keep adding tasks to the queue until you get the queue full exception.

Here is an example (partial) stacktrace:

```
Caused by [alertable exception] java.lang.IllegalStateException: Queue full
     at java.util.AbstractQueue.add(AbstractQueue.java:98)
     at io.netty.util.HashedWheelTimer.newTimeout(HashedWheelTimer.java:423)
     ...
```

### Netty version

4.1.12

**Comment by kevinoliver** [comment]
I think we can address this, at least partially, by delaying creation of the MPSC queue and passing it the `maxPendingTimeouts` parameter for its `maxCapacity`. Though it looks like even that isn't always going to work... 

Happy to work on a PR here if you are interested.

**Comment by johnou** [comment]
@Scottmitch addressed with https://github.com/netty/netty/pull/6295 right?

**Comment by Scottmitch** [comment]
Once #6295 is pulled in we should be able to leverage the queue limits and unlimited queue size in `HashWheelTimer` ... hopefully we can get rid of `pendingTimeouts` in `HashWheelTimer` at this time.

**Comment by kevinoliver** [comment]
sounds good to me. thanks @johnou and @Scottmitch

**Comment by normanmaurer** [comment]
@Scottmitch +1

**Comment by vkostyukov** [comment]
@Scottmitch Why getting rid of `pendingTimeouts`? These are quite useful as a visibility point into a timer. Finagle uses them to report Timer statistics to the users.

**Comment by Scottmitch** [comment]
> Why getting rid of pendingTimeouts? 

I was AFK at the time but I was referring to the member variable and not the public method. My preference would be to rely upon the queue implementation to enforce the limits and then just use the queue's `size()` method. However it seems like the semantics in `HashedWheelTimer` don't lend themselves toward removal of `pendingTimeouts`.

**Comment by Scottmitch** [comment]
@kevinoliver - Now that https://github.com/netty/netty/pull/6295 has been pulled in ... and `HashedWheelTimer` already uses `PlatformDependent.newMpscQueue()` (unbounded queue), and we enforce the limit via `pendingTimeouts` ... is there any more action required to close this issue?

**Comment by kevinoliver** [comment]
@Scottmitch nothing else needed from my end. thank you!
