### ISSUE TITLE
pthread_create (1040KB stack) failed: Out of memory

### ISSUE THREAD

**Issue by Tipsyume** [netty/netty#6949]
### Expected behavior
 my program  throw "pthread_create (1040KB stack) failed: Out of memory" exception when it's run in mWorkerGroup.shutdownGracefully() ,here is my code:
` mWorkerGroup = new NioEventLoopGroup(0, Executors.newFixedThreadPool(5));
        try {
            Bootstrap mBootstrap = new Bootstrap();
            mBootstrap.group(mWorkerGroup)
                    .channel(NioSocketChannel.class)
                    .option(ChannelOption.TCP_NODELAY, true)
                    .option(ChannelOption.SO_KEEPALIVE, true)
                    .handler(new ChannelInitializer<SocketChannel>() {
                        @Override
                        protected void initChannel(SocketChannel socketChannel) throws Exception {
                            ChannelPipeline pipeline = socketChannel.pipeline();
                            pipeline.addLast(new LengthFieldBasedFrameDecoder(1024 * 4, 0, 4, 0, 0));
                            pipeline.addLast(new IdleStateHandler(HEART_BEAT_WAIT_SECOND, HEART_BEAT_WAIT_SECOND, HEART_BEAT_WAIT_SECOND + 3, TimeUnit.SECONDS));
                            pipeline.addLast(new LoggingHandler(LogLevel.INFO));
                            pipeline.addLast(new ClientChannelHandler());
                        }
                    })
                    .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 4000);

            mBootstrap.connect(new InetSocketAddress(host, port)).addListener(mConnectFutureListener)
                    .sync().channel().config().setAllocator(PooledByteBufAllocator.DEFAULT);
        } catch (Throwable e) {
            L.e(TAG, "Exception: " + e.getMessage());
            netState = Constant.NETTY_STATE_DISCONNECT;
            HeartThreadResease();
            if (mWorkerGroup != null)
                mWorkerGroup.shutdownGracefully();
            Constant.connectCount++;
        }`
### Netty version
netty-all-4.1.12.Final

### JVM version (e.g. `java -version`)
--
### OS version (e.g. `uname -a`)
android

**Comment by normanmaurer** [comment]
@Tipsyume this means that you ran out of memory so you may need to increase the memory settings for the app .

**Comment by Tipsyume** [comment]
@normanmaurer actually i'm settings  android:largeHeap="true" in AndroidManifest.xml,but it's still happen yet.

**Comment by normanmaurer** [comment]
I have no idea about android but this error tells you you are running out of memory. Maybe take an heap dump and inspect what's in there
