### ISSUE TITLE
Unhandled exception in native epoll: io.netty.channel.unix.Errors$NativeIoException: syscall:read

### ISSUE THREAD

**Issue by dschobel** [netty/netty#6950]
a service running netty 4.1.12 and using native epoll transport sees the following in its logs:

```
WAR [20170629-22:20:03.859]: Unhandled exception in connection with /10.56.145.106:34060, shutting down connection
WAR [20170629-22:20:03.859]: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
WAR [20170629-22:20:03.859]:     at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source)
```

that's on CentOs 7.3.1611 + java 1.8.0_131

We don't have a repro and it shows up intermittently.

**Comment by normanmaurer** [comment]
@dschobel which class is logging this ? Connect-reset is quite usual, from what I can tell its not something within netty itself that logs this:

```
─[11:54:32] norman@Normans-MacBook-Pro-8/~/Documents/workspace/netty
( 4.1: ✔
╰─○ grep -lr "Unhandled exception in connection with" *

╭─[11:54:42] norman@Normans-MacBook-Pro-8/~/Documents/workspace/netty
( 4.1: ✔
```

**Comment by dschobel** [comment]
@normanmaurer yeah the first log line is from our [last line exception handler](https://github.com/twitter/finagle/blob/develop/finagle-netty4/src/main/scala/com/twitter/finagle/netty4/channel/ChannelExceptionHandler.scala#L38-L56) that finagle installs. It seems strange that given the same pipeline we'd see socket read errors caught at different handlers just by varying the transport implementation. 

I'm looking into a way to forge RSTs to see if I can get  a simple repro.

**Comment by Scottmitch** [comment]
To clarify this issue revolves around seeing different behavior from the NIO transport (not seeing connection reset) and Epoll (seeing connection reset)? Connection reset typically is the result of your peer sending a RST (set SO_LINGER to 0 and close to send RST) which depends upon your peer and may occur in the wild.

**Comment by dschobel** [comment]
@Scottmitch the RST happens in both cases but with the Epoll transport it's happening at a different point in our pipeline. I'll do some more testing using the SO_LINGER trick

**Comment by dschobel** [comment]
turns out it was our exception mapping code not being aware of the new exception types from Epoll. sorry for the false alarm

**Comment by normanmaurer** [comment]
No worries thanks for the update 👍

**Comment by Scottmitch** [comment]
+1 ... thanks @dschobel !

**Comment by zhangxingping** [comment]
what's your solution of "Error [io.netty.channel.unix.Errors$NativeIoException: syscall:write(..) failed: "

**Comment by zhangxingping** [comment]
unhapply
