### ISSUE TITLE
Writing to released ByteBuf

### ISSUE THREAD

**Issue by fenik17** [netty/netty#6951]
What is the concept of checking the possibility of accessing to `ByteBuf`?

Probably a bug. A `writeCharSequence` (`setCharSequence`) can allow writing to released buffer:
```java
    ByteBuf buf = Unpooled.directBuffer(16);
    buf.release();
    buf.writeCharSequence("1", CharsetUtil.US_ASCII); // <-- no exceptions
```
With an `UnpooledHeapByteBuf` this code leads to `IllegalReferenceCountException` due to call  `ensureAccessible()` in the `capacity()`. IIUC this done only to prevent NPE for released buffed. Perhaps it's better to rewrite the method like this:
```java
    public int capacity() {
        byte[] array = this.array;
        if (array != null) {
            return array.length;
        }
        // array is null if refCnt == 0
        ensureAccessible();
        return 0;
    }
```

Also, a `setCharSequence` - the only `set` method which can increase capacity...

**Comment by Scottmitch** [comment]
We should check the ref count before writing to the underlying storage. Typically method use [checIndex](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/AbstractByteBuf.java#L1346) to accomplish this. I'm AFK but can look in more detail later.

**Comment by normanmaurer** [comment]
That's a bug... looking now

**Comment by normanmaurer** [comment]
Ok I have a fix... stay tuned

**Comment by normanmaurer** [comment]
@fenik17 please check https://github.com/netty/netty/pull/6953

**Comment by fenik17** [comment]
@normanmaurer #6953 this is OK. Thanks! But what about this:
> a setCharSequence - the only set method which can increase capacity...

IMHO, this is not fine.. For example:
```java
        ByteBuf buf = Unpooled.directBuffer(1);
        buf.setCharSequence(0, "AB", CharsetUtil.US_ASCII); // no exception. capacity == 2

        buf.resetWriterIndex().capacity(1);
        buf.setBytes(0, new byte[]{1, 2}); // IndexOutOfBoundsException
```
I think only `write` methods should increase capacity.

**Comment by fenik17** [comment]
> I think only write methods should increase capacity.

Although, if fix it now, someone's code can breaks...

**Comment by normanmaurer** [comment]
@fenik17 let me investigate later today. Need to finish some other stuff first.

**Comment by normanmaurer** [comment]
@fenik17 you are correct and this is a bug. I have fixed it here: https://github.com/netty/netty/pull/6957. I think its fine to change it here as it is clearly a bug and we can just mention it in the release note to give more visibility.

**Comment by fenik17** [comment]
@normanmaurer good. Thanks!

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6953
