### ISSUE TITLE
[question] does netty support fixed size of heap buffer pool?

### ISSUE THREAD

**Issue by amosbird** [netty/netty#6961]
so that we can specify the total amount of heap memory a pool can use. Also providing customized strategies used to wait for enough memory.

**Comment by Scottmitch** [comment]
> so that we can specify the total amount of heap memory a pool can us

The heap memory is limited in the typical way for a java application (e.g. `-Xms` and `-Xmx`).

> Also providing customized strategies used to wait for enough memory.

No. ByteBufAllocator is synchronous (e.g. `ByteBuf b = allocator.heapBuffer()`) so there is nothing "built in" that you can rely upon to delay the result if there isn't enough memory. This would have to be built on top at a higher level. This is the same semantics as the `new` operator.
