### ISSUE TITLE
-Dio.netty.packagePrefix should not be required when shading

### ISSUE THREAD

**Issue by ejona86** [netty/netty#6963]
### Expected behavior

A library may use shading transparently to the user and would be able to be combined with other libraries that also use Netty. Similarly, an application should be able to use shading transparently to the user.

### Actual behavior

The shader has to choose whether to rename the native components of epoll and tcnative. If they are renamed, then `-Dio.netty.packagePrefix` must be set at runtime, which may not be possible programatically. If they aren't renamed, then epoll and tcnative can fail when mixed with other libraries because: 1) there is a name collision of the `META-INF/native/` files in the class path and 2) [`System.loadLibrary(String)` does nothing if it previously loaded a particular name](http://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#loadLibrary-java.lang.String-).

### Possible fixes

`NativeLibraryLoader` [currently](https://github.com/netty/netty/blob/f208b147a6c1748092f1d23f71865e9082b00534/common/src/main/java/io/netty/util/internal/NativeLibraryLoader.java#L188) defaults to a package prefix of `""`:
```java
String name = SystemPropertyUtil.get("io.netty.packagePrefix", "").replace('.', '-') + originalName;
```

Instead of defaulting to `""`, I think it should at least attempt to find a package prefix from the class path. There are many options. A sampling:
```java
// Semi-readable implicit
String maybeShaded = NativeLibraryLoader.class.getName();
// Use ! instead of . to avoid shading utilities from modifying the string
String expected = "io!netty!util!internal!NativeLibraryLoader".replace('!', '.');
if (maybeShaded.endsWith(expected)) {
  return maybeShaded.substring(0, maybeShaded.length() - expected.size());
} else {
  throw ...;
}

// Quick and dirty implicit
String name = NativeLibraryLoader.class.getName();
// 42 == "io.netty.util.internal.NativeLibraryLoader".length()
return name.substring(0, name.length() - 42);

// Pre-configured (explicit). User created a file for Netty to read
String resourceName = obfuscateConcat("/META-INF/native/", "io.netty.packagePrefix");
// Could also be a relative, but then users would need to create a file in
// io/netty/util/internal or similar subpackage (I don't see any class in
// io.netty package).
// String resourceName = "packagePrefix";
InputStream is = NativeLibraryLoader.class.getResourceAsStream(resourceName);
if (is == null) {
  return "";
}
return asStringUtf8(is);
```

In my mind, when shaded, a `""` fallback is counter-productive. It gives the appearance that Netty has been properly shaded when in fact it still collides. As a user, I'd much rather epoll and tcnative obviously fail when improperly shaded. So for me an implicit solution has the _benefit_ of failing when misconfigured. But we can mix-and-match behaviors pretty easily.

Depending on the solution, supporting `io.netty.packagePrefix` may not be necessary any more. An explicit configuration by the user (via `io.netty.packagePrefix` or similar) may be a necessary supplement to implicit solutions since shading may not use prefixing; `io.netty` may have been rewritten as `a.b` or `com.example.shadednetty`.

I'd be willing to submit a PR for necessary changes, although I'd hope we could agree on an approach first.

**Comment by Scottmitch** [comment]
Something like the first approach sounds good. The assumption is this is currently done at a higher level to keep the shading logic (of the java code, and rename/move of the JNI library) in a single layer but moving it into Netty sounds good to me. I will need to validate this works as expected but assuming it does I'm OK with removing `io.netty.packagePrefix` (@normanmaurer may not be though).

> io.netty may have been rewritten as a.b or com.example.shadednetty

The native code currently only supports prepending a prefix to existing netty class names. If it is desired to support arbitrary renaming then work would be needed at the JNI layer. Is support beyond appending a prefix necessary?

**Comment by ejona86** [comment]
> The assumption is this is currently done at a higher level to keep the shading logic (of the java code, and rename/move of the JNI library) in a single layer but moving it into Netty sounds good to me.

I'm not too picky as to the solution, as long as it can be transparent to the user. While it is possible to set `io.netty.packagePrefix` via code, that can be hard/strange for a library and is not guaranteed to be permitted. It also means that every transitive user of Netty may end up needing that logic in code (not just shading configuration).

> The native code currently only supports prepending a prefix to existing netty class names. ... Is support beyond appending a prefix necessary?

Ah, that's a good point; I got so tied up with library loading I forgot the packagePrefix was used other places. I think just supporting a prefix is sufficient, but I just wanted to call out ways that my suggested change may accidentally limit existing configurations. But now that's obviously not the case :smile:.

**Comment by Scottmitch** [comment]
@ejona86 - We are on the same page. +1 for moving this logic into Netty and not relying on a system property.

**Comment by normanmaurer** [comment]
@ejona86 sorry late to party due slacking during vacation =P +1 (1 sounds good.

**Comment by ejona86** [comment]
I'll send out a PR then using the "Semi-readable implicit" approach then. Truth be told, @normanmaurer, you didn't slow down the PR at all :smile:.

Unless someone says otherwise, I'll keep `io.netty.packagePrefix` for the moment to 1) give time for users to try the implicit method and find issues and 2) ease migration from the system property. If things work out and it is redundant then it is easy to remove it in the future.

**Comment by normanmaurer** [comment]
@ejona86 sounds good... go ahead :)

**Comment by johnou** [comment]
@ejona86 is that maybe something we could use the unstable api annotation for?

**Comment by ejona86** [comment]
@johnou, not really, since there isn't an explicit API.
