### ISSUE TITLE
TlsReadTest tests are misleading

### ISSUE THREAD

**Issue by nayato** [netty/netty#6968]
Tests rely on channel having AutoRead = false and verify that read was issued through setting readIssued. In reality read method is called during construction of EmbeddedChannel - because AutoRead is true at this time, before AutoRead is set to false in test.

**Comment by normanmaurer** [comment]
@nayato can you submit a pr with something that you think makes things more clear ?

**Comment by Scottmitch** [comment]
@nayato - please check if https://github.com/netty/netty/pull/6982 is what you had in mind.

**Comment by normanmaurer** [comment]
@nayato does https://github.com/netty/netty/pull/6987 work for you ?

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6987
