### ISSUE TITLE
Question: Is it necessary to remove listeners in Netty 4.1?

### ISSUE THREAD

**Issue by MartyIX** [netty/netty#6977]
I have the following simple code:

```
ChannelFuture response = channel.writeAndFlush(frame);
response.addListener(new GenericFutureListener<Future<? super Void>>() {
    @Override
    public void operationComplete(Future<? super Void> future) throws Exception {
        // do something here
    }
});
```

There is also `removeListener` method for `ChannelFuture`. However, I was unable to find information if it is necessary to remove listeners by hand (i.e. to explicitly call `removeListener` method) or not. I ask because I don't want to create memory leaks in my program. It would be very helpful if there was a note in Netty's source code. 

### Netty version

4.1.13

**Comment by normanmaurer** [comment]
This is an issue tracker so please use StackOverflow the next time for questions...

That said no you not need to remove a listener by hand. This method exists if you want to remove it after it was added by the future was not notified yet.
