### ISSUE TITLE
bom still uses snapshot for netty-transport-native-unix-common version

### ISSUE THREAD

**Issue by tsachev** [netty/netty#6979]
### Expected behavior
released bom should not contain snapshot versions
### Actual behavior
it still has snapshot version
### Minimal yet complete reproducer code (or URL to code)
see
http://repo1.maven.org/maven2/io/netty/netty-bom/4.1.13.Final/netty-bom-4.1.13.Final.pom
and
http://repo1.maven.org/maven2/io/netty/netty-bom/4.0.49.Final/netty-bom-4.0.49.Final.pom
### Netty version
4.1.13.Final and 4.0.49.Final
### OS version (e.g. `uname -a`)

`netty-transport-unix-common` should be `netty-transport-native-unix-common`

Seem that this was addressed by @wilkinsona in #6849 , but something went wrong in the end probably when merging/cherry-picking and #6852 also used the wrong artifact ids

in `4.1.13.Final`
```
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-transport-unix-common</artifactId>
        <version>4.1.13.Final-SNAPSHOT</version>
        <classifier>linux-x86_64</classifier>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-transport-unix-common</artifactId>
        <version>4.1.13.Final-SNAPSHOT</version>
        <classifier>osx-x86_64</classifier>
      </dependency>
```
in `4.0.49.Final`
```
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-transport-unix-common</artifactId>
        <version>4.0.48.Final-SNAPSHOT</version>
      </dependency>
```

**Comment by normanmaurer** [comment]
@tsachev will investigate later today.

**Comment by normanmaurer** [comment]
Please check https://github.com/netty/netty/pull/6989

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6989
