### ISSUE TITLE
MQTT unknown message type isn't handled as decoding error

### ISSUE THREAD

**Issue by ppatierno** [netty/netty#6984]
### Expected behavior

When there is an MQTT decoding error, an invalidMessage is created and a DecodeResult with failure and related cause exception is filled with right information so that the user application can see what's the problem. It should happens in any step in the decoding phase.

### Actual behavior

It doesn't work if the problem is in the fixed header with a not valid MQTT message type.
Poisoning a message with the first byte set to 0xF0 (so 15 that is not a valid MQTT message type), the IllegalArgumentException is raised and propagated. There is no way to have a failed DecodeResult as in the other scenarios.

### Steps to reproduce

Building a server pipeline with the MqttDecoder and then after opening the connection sending a packet with just two bytes 0xF0 0x00.

### Netty version

4.1.13 Final

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6985
