### ISSUE TITLE
Netty Epoll fails in IPv6 only environment

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty#6993]
https://github.com/netty/netty/blob/83de77fbe5385130ba9afc666fecbe9b59bd8032/transport-native-unix-common/src/main/c/netty_unix_socket.c#L198

In this code, it tries to set dual stack sockets, but fails when running in an IPv6 only environment.  Such an environment exists in Google by blocking all IPv4 functionality in the kernel in order to prove code is IPv6 compatible.  

cc: @pmarks-net

**Comment by normanmaurer** [comment]
@Scottmitch please remember to set the milestone when you close issues so it is listed for the correct version.
