### ISSUE TITLE
Websocket example and WebSocketHandshakeException

### ISSUE THREAD

**Issue by MartyIX** [netty/netty#6998]
Hi,

Websocket example contains the following code:

        if (!handshaker.isHandshakeComplete()) {
            handshaker.finishHandshake(ch, (FullHttpResponse) msg);
            System.out.println("WebSocket Client connected!");
            handshakeFuture.setSuccess();
            return;
        }

(https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http/websocketx/client/WebSocketClientHandler.java#L85)

The problem I've encountered is that `finishHandshake` may throw `WebSocketHandshakeException` exception. It would be nice to handle the exception. Possibly like this:

        try {
            handshaker.finishHandshake(ch, (FullHttpResponse) msg);
            handshakeFuture.setSuccess();
        } catch (WebSocketHandshakeException e) {
            handshakeFuture.setFailure(e);
        }

I'm quite new to Netty so I don't know there is a better way. Does the modification make sense to you? 

### Netty version

4.1.13

Regards,
Martin

**Comment by normanmaurer** [comment]
@MartyIX yes... Can you please open a PR with a fix ?

**Comment by MartyIX** [comment]
Yes, https://github.com/netty/netty/pull/6999

**Comment by normanmaurer** [comment]
Fixes by https://github.com/netty/netty/pull/6999 . @MartyIX thanks
