### ISSUE TITLE
@Sharable annotation proper use

### ISSUE THREAD

**Issue by 243826** [netty/netty#700]
Hi,

  After creating handler, I am reusing it with a new channel after the old channel is unregistered. I still get the warning that I need to declare the handler Sharable. Is that right?

  I think it should be okay to reuse (e.g. i was connected and connection dropped, so i want to reestablish the connection without recreating my handlers).
## 

Regards,
Chetan

**Comment by majiaji** [comment]
Hi @normanmaurer 
I wonder why we need to create a new instance of handler such like ByteToMessageDecoder .
