### ISSUE TITLE
NioEventLoopGroup vs EpollEventLoopGroup on Linux performance

### ISSUE THREAD

**Issue by Sammers21** [netty/netty#7014]
I would like to know is there any difference in performance between NioEventLoopGroup and EpollEventLoopGroup on Linux platform. I know that EpollEventLoopGroup should perform better by is there any real tests?

**Comment by spccold** [comment]
[Why native epoll support is introduced in Netty?](https://stackoverflow.com/questions/23465401/why-native-epoll-support-is-introduced-in-netty)

**Comment by normanmaurer** [comment]
@Sammers21 see the link @spccold provided.

**Comment by Scottmitch** [comment]
with performance its usually best to evaluate based upon your work load ... and then let us know what you find :)

**Comment by Sammers21** [comment]
Are there any benchmarks? I want to see numbers. I that EpollEventLoopGroup perform better but the question is it worth it.

**Comment by johnou** [comment]
@Sammers21 I think @Scottmitch was suggesting that you create your own metrics try both and see how they compare because performance will vary depending on the type of workload / application. Bonus points if you can come back here with the results!

**Comment by Scottmitch** [comment]
+1 @johnou.

@Sammers21 - it is relatively easy to switch between transports ... so assuming you have some existing mechanism to measure performance of your application you can just swap the transports and observe any differences.

**Comment by Sammers21** [comment]
@Scottmitch, @johnou, thank you, I got your point

**Comment by danh22** [comment]
@Sammers21 Have you done the performance test between these two EventLoopGroup yet? If you have done it, can you post your test results here please?

**Comment by Sammers21** [comment]
@danh22, nope, I haven't.

**Comment by kofemann** [comment]
Testes on Linux:

kernel: 5.18.0-0.rc1.18.fc37.x86_64+debug
2xCPU HT, i7-6600U CPU @ 2.60GHz
Java: openjdk-17.0.2

Test: https://gist.github.com/kofemann/43300f27fff44869243f00d912b553c4
```
Benchmark                        (type)   Mode  Cnt      Score      Error  Units
NettyGroupBenchmark.sendMessage   epoll  thrpt   20  14455.782 ± 1682.250  ops/s
NettyGroupBenchmark.sendMessage     nio  thrpt   20  17605.324 ±  824.115  ops/s
```
 The result is highly depends on the use-case.

**Comment by franz1981** [comment]
The benchmark mentioned is testing the loop group as an executor you can use to submit tasks: this is not saying anything related to the performance of takes executed within the event loop itself and it is not fed by any incoming I/O.

What are you trying to estimate/measure?

**Comment by kofemann** [comment]
The goal is to understand which EventLoopGroup should be used. I have looked around and didn't find any specific numbers or guidelines. So, the benchmark is a starting point for my investigation.
