### ISSUE TITLE
ipv6 support test in netty_unix_socket.c misses some cases

### ISSUE THREAD

**Issue by dschobel** [netty/netty#7021]
We ran into a problem with the native epoll transport on [Aurora](https://aurora.apache.org/) when ipv6 networking is disabled where [the test to determine if ipv6 is supported](https://github.com/netty/netty/blob/4.1/transport-native-unix-common/src/main/c/netty_unix_socket.c#L179-L188) successfully created a ipv6 socket but all connections to it fail because, as mentioned, ipv6 networking is disabled.

This seems like strange behavior in Aurora and we can work around it with the `preferIPv4Stack` flag but I wonder whether netty should have a stronger test and try to connect to the test socket to confirm that ipv6 networking is really working.

**Comment by normanmaurer** [comment]
@dschobel can you give some more details how it fails ?

**Comment by dschobel** [comment]
sure, so the test linked above returns AF_INET6 because it can create the socket. when it comes time to connect though, the connection fails with `connect: Cannot assign requested address`

**Comment by normanmaurer** [comment]
Interesting... will the same error happen when you try to bind to an IPv6 address?

**Comment by normanmaurer** [comment]
@dschobel can you check if this fixes it for you: https://github.com/netty/netty/pull/7022

**Comment by dschobel** [comment]
> will the same error happen when you try to bind to an IPv6 address?

`bind` looks like it succeeds. when running this https://gist.github.com/dschobel/0af22b79179c6f4fd3aa5267d87f7d3f in the same aurora container it prints out:

```
successfully bound!
successfully listening!
listening on a00:9157:: port number 37207
```

**Comment by normanmaurer** [comment]
@dschobel and if you add a `connect` to the address it fails ?

**Comment by dschobel** [comment]
@normanmaurer creating the ipv6 socket + then connecting is what failed to begin with, did you mean that I should try bind before connect?

**Comment by normanmaurer** [comment]
@dschobel I asked you if you could try to do the connect and so give me a c reproducer so I can see what is going on :)

**Comment by dschobel** [comment]
https://gist.github.com/dschobel/e9f29aa318304d2192d4357a02653da1 was my test case which is basically inlining netty's native socket code when the ip address is 0.0.0.0 or ::/0

**Comment by normanmaurer** [comment]
@dschobel hmm this looks not correct to me as you use wild card addresses and try to connect to these here:
https://gist.github.com/dschobel/e9f29aa318304d2192d4357a02653da1#file-connect-c-L66

Are you sure this works with ipv4 ? Can you try to not use a wildcard address when connect with ipv6 like `::1`

**Comment by dschobel** [comment]
@normanmaurer alright, updated to connect to ::1  in https://gist.github.com/dschobel/e9f29aa318304d2192d4357a02653da1  but please check my work because this the most C I've written in a decade  :)

the result in our aurora cluster is: `connect: Cannot assign requested address` when it's the AF_INET6 domain. 

AF_INET however, succeeds.

**Comment by normanmaurer** [comment]
@dschobel can you let me know what happens if you use the NIO transport ?

**Comment by dschobel** [comment]
test case: https://gist.github.com/dschobel/b5d1d0f4b8c1c90733002c018e01d5c4

NIO:

```
useNative: false, port: 1463
native epoll available? true
trying to connect to 0.0.0.0/0.0.0.0:1463
init channel fired!
connected!
client channel: [id: 0x93c41b74, L:/10.71.129.139:37759 - R:0.0.0.0/0.0.0.0:1463]
remote address: 0.0.0.0/0.0.0.0:1463
local address: /10.71.129.139:37759
connection succeeded!
```

native:
```
useNative: true, port: 1463
native epoll available? true
trying to connect to 0.0.0.0/0.0.0.0:1463
init channel fired!
client channel: [id: 0x687bea1e]
remote address: null
local address: null
connection failed with io.netty.channel.AbstractChannel$AnnotatedConnectException: connect(..) failed: Cannot assign requested address: 0.0.0.0/0.0.0.0:1463
```

**Comment by normanmaurer** [comment]
Thx will check in detail

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7022
