### ISSUE TITLE
ChannelFuture not completed when "java.net.BindException: Address already in use" is thrown

### ISSUE THREAD

**Issue by sundarms** [netty/netty#7024]
### Expected behavior
When ServerBootstrap.bind(port) fails ChannelFuture returned by bind should be failed with exception
### Actual behavior
Top level BindException is thrown and ChannelFuture never completes.

### Steps to reproduce

1. Run `nc -l <port>`
2. Run `telnet localhost <port>`
3. Find client side port used by telnet and make Server to bind to that port.

ChannelFuture returned by bind(port) should be completed with BindException instead the exception is thrown at the top level.

### Minimal yet complete reproducer code (or URL to code)
https://gist.github.com/sundarms/da511665b69bcf7a72ee99e8c06420d8

This is in scala will try to get java version.

### Netty version
4.1.11.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_131"

### OS version (e.g. `uname -a`)
Linux test-server.domain 2.6.32-642.6.2.el6

At least my understanding was whenever a method returns a Future it should try to set an exception in that Future and not throw an exception.

**Comment by normanmaurer** [comment]
@sundarms I can not reproduce with a pure netty test-case:

```java

    @Test
    public void testBindException() throws Exception {
        ServerSocket serverSocket = new ServerSocket();
        serverSocket.bind(new InetSocketAddress(NetUtil.LOCALHOST, 0));
        SocketAddress address = serverSocket.getLocalSocketAddress();

        final EventLoopGroup group = new NioEventLoopGroup(1);
        ServerBootstrap b = new ServerBootstrap();
        try {
            b.group(group)
                    .channel(NioServerSocketChannel.class)
                    .option(ChannelOption.SO_REUSEADDR, true)
                    .childHandler(new ChannelInboundHandlerAdapter());

            try {
                b.bind(address).syncUninterruptibly();
                fail();
            } catch (Exception e) {
                assertTrue(e instanceof BindException);
            }
        } finally {
            group.shutdownGracefully();
            serverSocket.close();
        }
    }
```

**Comment by normanmaurer** [comment]
Also the future is notified correctly and only throws because I call `syncUninterruptibly()` which is expected.

**Comment by sundarms** [comment]
Sorry, may be I am missing something here because of I am trying to avoid try catch in my Scala code. 
1. Do I have to call syncUninterruptibly() always with bind()?
2. I cannot always depend on ChannelFuture returned by bind to determine the status? For ex: if I don't have try block for bind() only the outer block gets called and ChannelFuture is never updated. 
3. I will try to write my logic java code and update here.

Thanks
