### ISSUE TITLE
Http2FrameLogger to many char[] allocation when logger disabled

### ISSUE THREAD

**Issue by Gordiychuk** [netty/netty#7025]
### Expected behavior
No char[] allocation when logger disabled

### Actual behavior
The logger always performing a hex dump of the ByteBufs regarless whether or not the log would take place. I faced with huge allocation during run grpc benchmarks
![screenshot from 2017-07-26 15 40 17](https://user-images.githubusercontent.com/10699594/28621281-17ec8cfa-7219-11e7-8579-d51b7489072d.png)

### Netty version
io.netty:netty-codec-http2:4.1.13.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by Gordiychuk** [comment]
Check enable or not logger before encode already was introduced in #3492 but then lost in #6877

**Comment by normanmaurer** [comment]
Will fix ...

**Comment by Gordiychuk** [comment]
@normanmaurer sorry, I already prepare PR #7026

**Comment by normanmaurer** [comment]
Ha! Even better

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7026.
