### ISSUE TITLE
Creating of SslContext in paranoid mode takes too long

### ISSUE THREAD

**Issue by doom369** [netty/netty#7029]
I have ~400 integration tests. Every test creates `SslContext` and destroys it at the end. Recently I switched my tests from JDK provider to OpenSSL provider and now my tests are executed forever :).

I found that the reason is in SslContext creation with Paranoid mode.

### Expected behavior

OpenSsl context creation performance should be close to JDK ssl context creation.

### Minimal yet complete reproducer code (or URL to code)

This minimal unit test reproduces situation:

```
    @Test
    public void testCreateContext() throws Exception {
        ResourceLeakDetector.setLevel(ResourceLeakDetector.Level.PARANOID);
        while(true) {
            SelfSignedCertificate ssc = new SelfSignedCertificate();
            SslContextBuilder builder = SslContextBuilder.forServer(ssc.certificate(), ssc.privateKey())
                    .sslProvider(SslProvider.OPENSSL);
            long now = System.currentTimeMillis();
            SslContext sslContext = builder.build();
            System.out.print(System.currentTimeMillis() - now);
            assertNotNull(sslContext);
        }
    }
```

In my case `builder.build()` takes 4 seconds. JDK Ssl cotext creation takes few millis.

Profiling shows that issue in `ResourceLeakDetector.newRecord()` method. It takes all the time and allocates hundreds of megabytes of objects.

### Netty version

4.1.13.Final

### JVM version (e.g. `java -version`)

1.8.0_131

### OS version (e.g. `uname -a`)

Ubuntu 16.04

**Comment by normanmaurer** [comment]
@doom369 its a "known" issue as we need to call `Base64.*` methods when creating the `OpenSsl*Context` instances and this is heavy on buffer operations.

**Comment by doom369** [comment]
Ok. I can switch to `advanced` mode. However - this page http://netty.io/wiki/reference-counted-objects.html recommends to use `paranoid`, but it really slow with OpenSSL...

**Comment by normanmaurer** [comment]
@doom369 that is because usually its not expected to have these created and destroyed very frequently. That said I think I could improve it for java8 use case... Stay tuned...

**Comment by normanmaurer** [comment]
@doom369 PTAL https://github.com/netty/netty/pull/7030 and test

**Comment by doom369** [comment]
@normanmaurer much better now! Thanks.

Now 
OpenSSL takes 40 ms;
JDK take 2ms;

**Comment by normanmaurer** [comment]
@doom369 reopen till merged.

**Comment by normanmaurer** [comment]
@doom369 is this still an issue ? I think we improved the perf a lot here

**Comment by doom369** [comment]
@normanmaurer I think the issue is fixed. Now I run the test again in paranoid mode and they are executed pretty fast. Not so fast as with advanced more, but still much faster than before.

**Comment by normanmaurer** [comment]
Ok thanks.. closing

**Comment by normanmaurer** [comment]
@Selvantamil599 actually yes... it's highly encouraged that you build the context once and re-use it.

**Comment by Selvantamil599** [comment]
@normanmaurer Ok. Thank you
