### ISSUE TITLE
Http2ConnectionHandler#resetStream does not refund unconsumed bytes to the connection flow control window

### ISSUE THREAD

**Issue by ssheng** [netty/netty#7040]
### Expected behavior
HTTP/2 reset stream through Http2ConnectionHandler#resetStream should refund unconsumed bytes to the connection flow control window. Otherwise, call has to explicitly invoke #incrementWindowSize with #unconsumedBytes to update the connection flow control window.

### Actual behavior
HTTP/2 reset stream through Http2ConnectionHandler#resetStream does not seem to trigger the local flow controller to refund unconsumed bytes to the connection flow control window.

### Steps to reproduce
1. Server sends a DATA frame
2. Client receives the DATA frame but does not invoke consumeBytes
3. Client issues resetStream
4. Connection window can be exhausted and server can no longer send further DATA frames

### Netty version
4.1.13

### JVM version (e.g. `java -version`)
8u121

### OS version (e.g. `uname -a`)
Darwin ssheng-mn1 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
Sounds legit... @ssheng maybe you want to provide a PR to fix this ?

**Comment by Scottmitch** [comment]
We need to be careful about auto-returning bytes to flow controller. If the user does later return these bytes we could end up violating flow control. If a user is asynchronously returning bytes to the flow control window we may get into trouble by doing something behind there back.

**Comment by normanmaurer** [comment]
@Scottmitch @ejona86 so what to do about this ? Closing as `won't fix` ?

**Comment by Scottmitch** [comment]
I would need to investigate but when a stream is closed we implicitly return bytes to flow control so it is not clear this requires action.

**Comment by ssheng** [comment]
Actually the DefaultHttp2LocalFlowController handles this quite elegantly. I will verify my test again. For now I will close this issue.
https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2LocalFlowController.java#L111
