### ISSUE TITLE
OioSocketChannel writability change notifications

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#7054]
OioSocketChannel does not notify of writability changes in the same way as the other transport types [1].

[1] https://github.com/netty/netty/pull/7041#discussion_r130725832

**Comment by Scottmitch** [comment]
I'm not sure if this is an issue but lets investigate.

**Comment by normanmaurer** [comment]
@Scottmitch +1... Let me assign this to myself for now

**Comment by normanmaurer** [comment]
As OioSocketChannel was `@deprecated` and was removed from the master branch I will just close this as `won't fix`
