### ISSUE TITLE
writeAndFlush() doesn's work.

### ISSUE THREAD

**Issue by Deen12520** [netty/netty#7061]
### Expected behavior
I want to send a large Json (about 150kb) string to server_B.
My code is in server_C.
### Actual behavior
It doesn's work. 

**logs for server_B** 

11:08:20.822 [nioEventLoopGroup-11-1] DEBUG io.netty.buffer.PoolThreadCache - Freed 1 thread-local buffer(s) from thread: nioEventLoopGroup-11-1
11:10:17.862 [nioEventLoopGroup-3-4] DEBUG io.netty.channel.nio.NioEventLoop - Selector.select() returned prematurely 3 times in a row for Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@fe21d88.
MsgServer:/127.0.0.1:39954在线
MsgServer:/127.0.0.1:39954掉线
11:11:07.204 [nioEventLoopGroup-3-2] DEBUG io.netty.channel.nio.NioEventLoop - Selector.select() returned prematurely 4 times in a row for Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@647f9c1d.

### Steps to reproduce
![image](https://user-images.githubusercontent.com/9816736/29055211-cc4ad670-7c2d-11e7-997b-1cfa21546820.png)

In the code, the response can print,but the message cannot be sent.

### Netty version
Netty 4.1.12.Final

### JVM version 
Jdk 1.8

### OS version
CentOs 6.5

**Comment by Scottmitch** [comment]
You are calling `writeAndFlush` and then immediately closing the channel (`ctx.close()`). You are also closing the channel after your write completes (`.addListener(ChannelFutureListener.CLOSE)`) ... I'm not sure what you are trying to do but waiting until the write completes typically makes more sense.

If you think there are more issues please provide a complete reproducer (that we can be run to reproduce the issue).

**Comment by Deen12520** [comment]
Thank you. 
The problem is what you said. I solved.
