### ISSUE TITLE
should HttpObjectAggregator strip 'expect' header after sending 100 continue response?

### ISSUE THREAD

**Issue by dschobel** [netty/netty#7075]
There is a behavior difference in how [HttpObjectAggregator](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectAggregator.java#L162) and [HttpServerExpectContinueHandler](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpServerExpectContinueHandler.java#L92) 
deal with requests which set 'expect: 100-continue' headers and meet expectations.

`HttpServerExpectContinueHandler` removes the expect header from the client request and `HttpObjectAggregator` does not.

In the case where `HttpObjectAggregator` has sent the 100 response it seems that there is no value in propagating the header further so it would make sense to also remove the header.

This is the behavior as of Netty 4.1.12.Final

**Comment by normanmaurer** [comment]
@dschobel agree.. want to do a pr ?

**Comment by dschobel** [comment]
Sure, happy to do it.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7086
