### ISSUE TITLE
h2childchan: Child channel read queue initial size

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#7080]
Http2MultiplexCodec currently uses an `ArrayDeque` with an initial size of `4`, but the implementation of `ArrayDeque` limits the smallest initial size to `8`. We should investigate if it makes sense to adjust our initial size or use an alternative data structure to trade initial memory vs. resize/copy operations.

https://github.com/netty/netty/pull/6896#discussion_r132092019

**Comment by normanmaurer** [comment]
Let us close this for now. I think writing a new datastructure just for this is overkill.
