### ISSUE TITLE
h2childchan: DefaultHttp2StreamChannel initial writability

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#7082]
Currently the initial writability of `DefaultHttp2StreamChannel` is false if we have not yet created the underlying `Http2Stream` object. Typically a channel is default writability is true, unless conditions otherwise prohibit this. In the case of `DefaultHttp2StreamChannel` we should investigate if the following policy makes sense: the default state is writable unless the connection window has collapsed, and we may also want to consider the parent channel's writability.

https://github.com/netty/netty/pull/6896#discussion_r132339750

**Comment by normanmaurer** [comment]
This is "fixed" by https://github.com/netty/netty/pull/7181 ... To make it short no it makes no sense.

**Comment by normanmaurer** [comment]
Fixed by #7181

**Comment by Scottmitch** [comment]
@normanmaurer - Can you explain why the policy suggested here "makes no sense"? The policy implemented in #7181 seems incomplete and may incorrectly report writability in a few cases:
- depending on initial settings for outbound streams (https://github.com/netty/netty/pull/7181#discussion_r139296524)
- depending on connection window
- depending on channel writability
