### ISSUE TITLE
Wrong order with httpObjectAggregator and HttpResponseEncoder

### ISSUE THREAD

**Issue by okou19900722** [netty/netty#7087]
I catch a exception message:unsupported message type: DefaultFullHttpResponse(expected: ByteBuf, FileRegion)
I know if a message(not ByteBuf or FileRegion) write to AbstractNioByteChannel without Encoder, it will throw exception,but a add the HttpResonseEncoder to the ChannelPipeline. so i read the source find the code in MessageAggregator at line 227,
`final ChannelFuture future = ctx.writeAndFlush(continueResponse).addListener(listener);`
write a message with ChannelHandlerContext, it's will back from this ChannelHandler, but my HttpResponseEncoder is after HttpObjectAggregator,
So, I think it must be `final ChannelFuture future = ctx.channel().writeAndFlush(continueResponse.addListener(listener));`

sorry for bad english from a Chinese Programmer

**Comment by normanmaurer** [comment]
@okou19900722 thats an error in your ChannelPipeline setup.  You need to put `HttpResponseEncoder` before `HttpObjectAggregator`. Its even stated in the javadocs:

https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectAggregator.java#L43
