### ISSUE TITLE
WebSocketServerHandshaker user event not triggered 

### ISSUE THREAD

**Issue by martin3361** [netty/netty#7089]
### Expected behavior
As written in docs of `WebSocketServerProtocolHandler`:
/**
 * To know once a handshake was done you can intercept the
 * {@link ChannelInboundHandler#userEventTriggered(ChannelHandlerContext, Object)} and check if the event was instance
 * of {@link HandshakeComplete}, the event will contain extra information about the handshake such as the request and
 * selected subprotocol.
 */

### Actual behavior
userEventTriggered does not get called at all, let alone with Handshake complete

### Steps to reproduce
Use the below code in a WebSocketDecoder.

### Minimal yet complete reproducer code (or URL to code)
	@Override
	public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
		super.userEventTriggered(ctx, evt);
		// does not get called at all
		if (evt instanceof HandshakeComplete) {
			ctx.channel().attr(Constants.IS_WEB_SOCKET_KEY).set(Boolean.TRUE);
		}
	}

	private void handleHttpRequest(ChannelHandlerContext ctx, FullHttpRequest req) {
		// Handle a bad request.
		if (!req.decoderResult().isSuccess()) {
			return;
		}

		// Allow only GET methods.
		if (req.method() != GET) {
			return;
		}

		// Handshake
		WebSocketServerHandshakerFactory wsFactory = new WebSocketServerHandshakerFactory(
				String.format("ws://%s:%d", Constants.HOST, Constants.PORT), null, true, 5 * 1024 * 1024);
		this.handshaker = wsFactory.newHandshaker(req);
		if (this.handshaker == null) {
			WebSocketServerHandshakerFactory.sendUnsupportedVersionResponse(ctx.channel());
		} else {
			this.handshaker.handshake(ctx.channel(), req);

			// TODO remove once I catch the event
			ctx.channel().attr(Constants.IS_WEB_SOCKET_KEY).set(Boolean.TRUE);
		}
	}

### Netty version
latest stable downloadable version from the site

**Comment by amizurov** [comment]
Hi @martin3361,  i think it's not framework problem, please look carefully in example: https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/http/websocketx/server

**Comment by normanmaurer** [comment]
@martin3361 @amizurov is right... you will only get the behaviour if you use `WebSocketServerProtocolHandler`. Please check the examples
