### ISSUE TITLE
InternalThreadLocalMap recent change is causing increased GCs

### ISSUE THREAD

**Issue by alobodzki** [netty/netty#7092]
### Expected behavior
InternalThreadLocalMap.stringBuilder() method is returning thread local java.lang.StringBuilder() object without causing too much of GC overhead. Implementation before 4.1.13 had thread-local large builders, that basically were always reused, in most cases without being collected. I would expect the 1024 limit that is currently on the stringBuilder could be bigger, as 1K for Cookie headers is nothing special.

### Actual behavior
After changes in netty 4.1.14 how StringBuilder object is being trimmed, if you operate with headers ~1Kb, the method will create a new big char[] array on every request, due to how StringBuilder.trimToSize() is implemented, which in case of HotSpot at least is causing big (20% in our case) increase of minor GCs and huge outside of TLAB memory allocation, which doesn't have any added value.

### Steps to reproduce
Execute heavy performance tests with requests that will have  ~2K Cookie header with a setup that will also do some io.netty.handler.codec.http.cookie.ClientCookieEncoder.encode(Cookie[]) execution.

### Netty version
4.1.14
### JVM version (e.g. `java -version`)
jdk1.8.0_45

**Comment by fenik17** [comment]
+1
I added #7093.

**Comment by normanmaurer** [comment]
Was fixed by https://github.com/netty/netty/pull/7093
