### ISSUE TITLE
Potentially breaking change in regards to default OpenSSL/JDK cipher suites

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#7094]
See 43ae9748d0d2e33813b2d5e13cca951ab04dd033

We use an explicit cipher list in conjunction with a CipherSuiteFilter (code included in the unit test) which' purpose it is to ignore Netty's default ciphers.

To put it differently, we have a list of ciphers and we want to drop everything from that list that isn't supported. We don't want include netty's defaults in the output.

The additional twist is that we've been using OpenSSL's naming convention to express our list.

I believe the "bug" is this: https://github.com/netty/netty/commit/43ae9748d0d2e33813b2d5e13cca951ab04dd033#diff-82f94494cc35616a8a19b6aa9ed033efL274

```java
unmodifiableCiphers = Arrays.asList(checkNotNull(cipherFilter, "cipherFilter").filterCipherSuites(
 -                convertedCiphers, DEFAULT_CIPHERS, OpenSsl.availableOpenSslCipherSuites()));
 +                convertedCiphers, DEFAULT_CIPHERS, availableJavaCipherSuites()));
```

Notice the switch from `availableOpenSslCipherSuites()` to `availableJavaCipherSuites()`.

### Minimal yet complete reproducer code (or URL to code)

```java
public class CipherTest {

  private final List<String> input = Arrays.asList(
      "ECDHE-ECDSA-CHACHA20-POLY1305",
      "ECDHE-RSA-CHACHA20-POLY1305",
      "ECDHE-ECDSA-AES128-GCM-SHA256",
      "ECDHE-RSA-AES128-GCM-SHA256",
      "ECDHE-ECDSA-AES256-GCM-SHA384",
      "ECDHE-RSA-AES256-GCM-SHA384",
      "DHE-RSA-AES128-GCM-SHA256",
      "DHE-RSA-AES256-GCM-SHA384",
      "ECDHE-ECDSA-AES128-SHA256",
      "ECDHE-RSA-AES128-SHA256",
      "ECDHE-ECDSA-AES128-SHA",
      "ECDHE-RSA-AES256-SHA384",
      "ECDHE-RSA-AES128-SHA",
      "ECDHE-ECDSA-AES256-SHA384",
      "ECDHE-ECDSA-AES256-SHA",
      "ECDHE-RSA-AES256-SHA",
      "DHE-RSA-AES128-SHA256",
      "DHE-RSA-AES128-SHA",
      "DHE-RSA-AES256-SHA256",
      "DHE-RSA-AES256-SHA",
      "AES128-GCM-SHA256",
      "AES256-GCM-SHA384",
      "AES128-SHA256",
      "AES256-SHA256",
      "AES128-SHA",
      "AES256-SHA");
  
  @Test
  public void testOne() {
    CipherSuiteFilter cipherFilter = new NoDefaultsCipherSuiteFilter();
    
    String[] output = cipherFilter.filterCipherSuites(
        input, OpenSsl.DEFAULT_CIPHERS, OpenSsl.availableJavaCipherSuites());
    
    assertFalse("Expected output to be equal to input and certainly not empty", output.length == 0);
  }
  
  @Test
  public void testTwo() throws Exception {
    SelfSignedCertificate cert = new SelfSignedCertificate();
    try {
      SslContextBuilder.forServer(cert.certificate(), cert.privateKey())
          .sslProvider(SslProvider.OPENSSL)
          .ciphers(input, new NoDefaultsCipherSuiteFilter())
          .build();
      
      // This will fail with "SSLException: failed to set cipher suite: []"
    } finally {
      cert.delete();
    }
  }
  
  /**
   * A {@link CipherSuiteFilter} that ignores the defaults and only uses things 
   * that are defined in the supported working set.
   */
  private static class NoDefaultsCipherSuiteFilter implements CipherSuiteFilter {
    @Override
    public String[] filterCipherSuites(Iterable<String> ciphers, List<String> defaultCiphers, Set<String> supportedCiphers) {
      List<String> dst = new ArrayList<>();
      for (String value : ciphers) {
        if (value != null && supportedCiphers.contains(value)) {
          dst.add(value);
        }
      }
      
      return dst.toArray(new String[dst.size()]);
    }
  }
}
```

### Netty version

4.1.14

**Comment by normanmaurer** [comment]
@rkapsi looking into it...

**Comment by rkapsi** [comment]
That was quick :)

**Comment by rkapsi** [comment]
I'm fine switching to JDK naming convention if that's deep down the intention of the change and maybe our ability to use OpenSSL names was a bug in the first place.

**Comment by normanmaurer** [comment]
@rkapsi PTAL https://github.com/netty/netty/pull/7095 ... I am not sure if we should not support both... @Scottmitch wdyt ?

**Comment by rkapsi** [comment]
Ah yea, I think there is value in being able to use either.

**Comment by Scottmitch** [comment]
my preference would be not to leak the OpenSSL cipher names in our public API. I would prefer to handle that as an implementation detail. That way folks don't have to switch cipher suites just because they switch their engine. The only hesitation would be if our RFC<->OpenSSL cipher name algorithm didn't support some cipher(s) ... but I think the better approach is to fix our algorithm.

**Comment by rkapsi** [comment]
@Scottmitch - I'll give the RFC names a try. If I read the code correctly then `availableJavaCipherSuites()` returns a list of JDK+OpenSSL ciphers in RFC naming convention?

**Comment by Scottmitch** [comment]
`availableJavaCipherSuites()` should return a set which includes:
- the set of RFC cipher names which are supported
- that same set, substituting the `TLS_` prefix with `SSL_` (a workaround for IBM's JDK ... see https://github.com/netty/netty/pull/6941 for additional details).

**Comment by rkapsi** [comment]
:+1: - I've switched to RFC names and everything works.

**Comment by johnou** [comment]
@rkapsi so you're passing in a custom list of RFC cipher names into SslContextBuilder.ciphers(..)?

**Comment by rkapsi** [comment]
@johnou correct. We were using OpenSSL names which resulted in...

```java
Caused by: javax.net.ssl.SSLException: failed to set cipher suite: []
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:282) ~[netty-all-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:43) ~[netty-all-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:347) ~[netty-all-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:335) ~[netty-all-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:421) ~[netty-all-4.1.14.Final.jar:4.1.14.Final]
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:441) ~[netty-all-4.1.14.Final.jar:4.1.14.Final]
```

We have now switched to RFC names.

**Comment by Scottmitch** [comment]
> Might make sense to update the javadoc of the method to mention it only accepts RFC cipher names.

We can if you think this is useful however I think it would be unexpected if we didn't, and also unexpected if we accepted non-RFC cipher names (e.g. OpenSSL custom cipher names at the `SslContextBuilder` level). The JDK generally accepts RFC cipher names [1] and we try to be consistent with this approach.

[1] http://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html
