### ISSUE TITLE
This DirectMemory should be released

### ISSUE THREAD

**Issue by MKudo** [netty/netty#7103]
I faced the huge direct memory usage in my application (using Netty). I research it and found this ReadOnlyByteBufferBuf copy method.

https://github.com/netty/netty/blob/eb7f751ba519cbcab47d640cd18757f09d077b55/buffer/src/main/java/io/netty/buffer/ReadOnlyByteBufferBuf.java#L419

It seams to create DirectByteBuffer and put it to UnpooledDirectByteBuf constructor. In this constructor, 'doNotFree field' will set to true. Then this DirectByteBuffer seams be not freed (by code. But GC will free this memory).

I hope Netty free this memory.

**Comment by ninja-** [comment]
ByteBuffers are cleaned by JVM on garbage collection.
doNotFree is true, but since it's UnpooledDirectByteBuf they will both be garbage collected properly.
So my analysis here is that the code is correct.

You should use netty's ByteBufs whenever possible.

**Comment by MKudo** [comment]
> You should use netty's ByteBufs whenever possible, and also use the pooled allocator and avoid using Unpooled*
Thank you your advice. Unfortunately I only using Cassandra driver (which using Netty). If I can find out fix point, I will send the request it for Cassandra driver developer.


But, UnpooledDirectByteBuf seams to try to free the memory directory. (I know if there are no Cleaner, it will do nothing and GC will free the memory.) And my hope is simply try this free.


In realloc case(capacity(int, int))
https://github.com/netty/netty/blob/66b17310418230d12c21f1f91287c22022d8d847/buffer/src/main/java/io/netty/buffer/UnpooledDirectByteBuf.java#L156
call setByteBuffer method. And it will call freeDirect method.
https://github.com/netty/netty/blob/66b17310418230d12c21f1f91287c22022d8d847/buffer/src/main/java/io/netty/buffer/UnpooledDirectByteBuf.java#L122


In dealloc case, deallocate method also call freeDirect method.
https://github.com/netty/netty/blob/66b17310418230d12c21f1f91287c22022d8d847/buffer/src/main/java/io/netty/buffer/UnpooledDirectByteBuf.java#L667

**Comment by MKudo** [comment]
In my understand. The problem came from ReadOnlyByteBufferBuf's miss use of UnpooledDirectByteBuf constructor. The UnpooledDirectByteBuf's constructor is used by Unpooled#wrappedBuffer.
https://github.com/netty/netty/blob/b662afeece60faf349e82c8a624f6bfd7cfe7b1f/buffer/src/main/java/io/netty/buffer/Unpooled.java#L205
In this case, set doNotFree to true is important to save original Buffer. But in copy of ReadOnlyByteBufferBuf case, it should be released.

**Comment by normanmaurer** [comment]
@MKudo let me check

**Comment by normanmaurer** [comment]
@MKudo please check https://github.com/netty/netty/pull/7107 ...

**Comment by MKudo** [comment]
It looks good. It will help me. Thank you for your quick fix!

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7107
