### ISSUE TITLE
socket fd leak

### ISSUE THREAD

**Issue by superminipig** [netty/netty#7112]
### Steps to reproduce
shell : watch -n 1 "ls -l /proc/24141/fd|grep socket:"
service start: By default there are three socket fd.

More than 20 clients connect to the server.
Run for a while.
close all clients.
shell : watch -n 1 "ls -l /proc/24141/fd|grep socket:"  
More than 3 socket fd.

I found that these socket fd just created not used.

### Netty version
nettall 4.1.8.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

### OS version (e.g. `uname -a`)
Linux izwz93cggnjvxxhx76uex9z 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@superminipig you will need to provide more infos here (like a reproducer) . Also note your netty and java version are quite old so please upgrade and test again

**Comment by superminipig** [comment]
watch -n 1 'cat /proc/net/tcp|grep 1F90>>tcp.log'

watch -n 1 "ls -l /proc/24141/fd|grep socket:>>socket.log"

In the tcp.log,I can not find these socket fd that is not released.

**Comment by superminipig** [comment]
Which version do I use to be better?

**Comment by normanmaurer** [comment]
@superminipig well the latest 4.1 release and the latest java 8 release. Also I will need to have a small reproducer, like a netty server that shows the problem.

**Comment by superminipig** [comment]
Sorry, the project relies too much and there is no way to provide the smallest procedure.

**Comment by superminipig** [comment]
I first upgrade netty, try it.

**Comment by Scottmitch** [comment]
> Sorry, the project relies too much and there is no way to provide the smallest procedure.

Please extract out the necessary parts which reproduce the issue in order to get support.

**Comment by normanmaurer** [comment]
I will close this for now... please reopen if you still see issues
