### ISSUE TITLE
Multiple Set-Cookie HTTP headers should not be folded into one 

### ISSUE THREAD

**Issue by jianglai** [netty/netty#7115]
According to [RFC 6265](https://tools.ietf.org/html/rfc6265#section-3):

> Origin servers SHOULD NOT fold multiple Set-Cookie header fields into
   a single header field.  The usual mechanism for folding HTTP headers
   fields (i.e., as defined in [RFC2616]) might change the semantics of
   the Set-Cookie header field because the %x2C (",") character is used
   by Set-Cookie in a way that conflicts with such folding.

However `ServerCookieEncoder` [Javadoc](http://netty.io/4.1/api/io/netty/handler/codec/http/cookie/ServerCookieEncoder.html) states: 

> A RFC6265 compliant cookie encoder to be used server side, so some fields are sent (Version is typically ignored). As Netty's Cookie merges Expires and MaxAge into one single field, only Max-Age field is sent. Note that multiple cookies are supposed to be sent at once in a single "Set-Cookie" header.
 // Example
 HttpRequest req = ...;
 res.setHeader("Cookie", ServerCookieEncoder.encode("JSESSIONID", "1234"));

This is contradicting to the RFC and misleading.

Also the example is outdated with the `setHeader` method, has `req` in one line and `res` in another line, and should use "Set-Cookie" instead of "Cookie".

**Comment by slandelle** [comment]
My fault :(

`ServerCookieEncoder` javadoc is wrong (implementation and behavior are correct), should be:

>A RFC6265 compliant cookie encoder to be used server side, so some fields are sent (Version is typically ignored). As Netty's Cookie merges Expires and MaxAge into one single field, only Max-Age field is sent.
 // Example
 HttpResponse resp = ...;
 resp.setHeader("Set-Cookie", ServerCookieEncoder.encode("JSESSIONID", "1234"));

I'm off for the next 10 days and won't be able to provide a PR until then. Feel free to provide one.

**Comment by slandelle** [comment]
I just sent a PR for fixing the javadoc

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7158
