### ISSUE TITLE
GC can cause unexpected selector timeout

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty#7116]
I was comparing Netty's NioEventLoop to another event loop to see if there were any behavioral differences.  One difference I found was a bug fix that doesn't seem to be in Netty.  It is possible that Netty is not affected.  Consider the following scenario:

A client is connected to a server, and periodically sends keep alives, or health checks.   The server records these health checks, and has a scheduled task that makes sure the client is still connected.  At some point, the server enters a very heavy GC cycle, which may take longer than the keep alive interval.    The relevant code is in NioEventLoop:

```
                int selectedKeys = selector.select(timeoutMillis);
                selectCnt ++;

                if (selectedKeys != 0 || oldWakenUp || wakenUp.get() || hasTasks() || hasScheduledTasks()) {
                    // - Selected something,
                    // - waken up by user, or
                    // - the task queue has a pending task.
                    // - a scheduled task is ready for processing
                    break;
                }
```

When the selector times out, it will notice that no keys have been selected, but it does have scheduled tasks.  The scheduled tasks will run, namely the health checker.  Seeing that no health check was received since the last time, it will think the client has gone away, and kill the connection.  However, the client did in fact send a health check; the server would have noticed it on the next select.

The fix in our code looks like this:
```
        int selected = selector.select(timeoutMs);
        if (selected == 0) {
          selector.selectNow();
        }
```

In the event that nothing was selected, a last ditch `selectNow` is made to be sure.  It was decided that the cost of this second select was small, and would happen at most once per second  (Our default timeout, same as Netty).  

Before I go further on trying to make a reproducible test case and fix, I wanted to see what others think of this situation?  Keep Alives are a higher level concept, but need a fix at a lower layer.  

@normanmaurer @Scottmitch @ejona86  thoughts?

**Comment by ejona86** [comment]
I think it's fine without the "fix"? Whose to say what's happening in the scheduled tasks? Maybe the timeout is to _send_ a watchdog keepalive, and so the extra I/O delays sending even further.

Any time something like keepalives and super-long GC are combined, things will be "interesting" and you'll have to deal with it.

Note that this change would only really help if the scheduled task was the same event loop. While that _is_ likely, it seems strange to special-case.

**Comment by carl-mastrangelo** [comment]
+ @zhangkun83  who originally made the fix.

**Comment by zhangkun83** [comment]
The original fix (more like a hack) on our internal system was deemed necessary because the delay was annoying enough -- it stopped an integration test from starting up. Another factor to consider is that our internal system heavily relies on timely health-checking, which is not the case for gRPC.

**Comment by Scottmitch** [comment]
Note that PR https://github.com/netty/netty/pull/7042 changes this timeout handling approach for EPOLL.

I agree with @ejona86 that timers + GC (which may block the current thread) may lead to unexpected results.

**Comment by normanmaurer** [comment]
Agree with @ejona86 here as well. I would suggest we close this issue for now

**Comment by normanmaurer** [comment]
Let me close this for now... @carl-mastrangelo if you still think we need to do anything please reopen.
