### ISSUE TITLE
Strange warning when running on Raspberry PI (armv7l)

### ISSUE THREAD

**Issue by doom369** [netty/netty#7120]
One of our users reported this warning when running server based on Netty:

> pi@raspberrypi:~/Blynk $ java -jar server-0.26.2.jar -dataFolder /home/pi/Blynk Java HotSpot(TM) Client VM warning: You have loaded library /tmp/libnetty-transport-native-epoll8349522589992915587.so which might have disabled stack guard. The VM will try to fix the stack guard now.
> It's highly recommended that you fix the library with 'execstack -c ', or link it with '-z noexecstack'.

In code I'm using this check: 

`Epoll.isAvailable()`

And provided jar has native library only for linux-x86_64.

```
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-epoll</artifactId>
            <version>${netty.version}</version>
            <classifier>linux-x86_64</classifier>
        </dependency>
```

I think this is because of armv7l architecture that is 32 bit. But shouldn't `Epoll.isAvailable()` skip the library loading in that case?

Netty 4.1.14.Final

```
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)
```

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7163
