### ISSUE TITLE
MemoryRegionCache leak

### ISSUE THREAD

**Issue by yangsj19870829** [netty/netty#7132]
Hi,
We are using Netty 4.0.28.Final as http server, in the past few days the service had three times same problem. the cpu grow crazy, FGC runs high frequencly，but the memory can't recover. we have to restart servcie.  netty MemoryRegionCache maybe leak.   
![gc](https://user-images.githubusercontent.com/19920538/29494305-c086ba74-85d9-11e7-9313-b12dd9a6f055.png)

![jmap](https://user-images.githubusercontent.com/19920538/29494302-b7700ea4-85d9-11e7-9eab-f8391b294ce1.png)

**Comment by Scottmitch** [comment]
Are you aware of reference counting [1] and have you enabled leak detection and ruled out the possibility for a reference count leak?

Have you taken a heap dump to determine the GC routes? If there is a lot of allocation off of the EventLoop threads it is possible that the `Recycler`/pool is retaining a lot of objects. You can disable pooling on non-EventLoop threads via a system property [2] or create your own `PooledByteBufAllocator` to control this manually.

[1] http://netty.io/wiki/reference-counted-objects.html
[2] https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java#L138

**Comment by normanmaurer** [comment]
@yangsj19870829 as @Scottmitch said you may just need to size the cache differently. That said you may also want to upgrade to a more recent version of netty. The version you are using is very old already.

**Comment by johnou** [comment]
@yangsj19870829 how many threads are you running?

**Comment by yangsj19870829** [comment]
@johnou  300 threads running,  before tow day, this problem happens again,  we have taken a heap dump, it cause by a  common component developed by ourself.   the same time, we have upgrade from 4.0.28 to 4.1.10.

**Comment by yangsj19870829** [comment]
@johnou  300 threads running, before three days, this problem happens again, we have taken a heap dump, **it cause by a common component developed by ourself**. the same time, we have upgrade netty from 4.0.28 to 4.1.10.  Thank you all @normanmaurer @Scottmitch @johnou .
