### ISSUE TITLE
Apex minecraft hosting server "failed to mark promise as success because it has succeeded"

### ISSUE THREAD

**Issue by Divx001** [netty/netty#7137]
Renting a server from apex and installed few mods was running great but then the console started filling with the error above and everytime it appeared it lagged the whole server. Just looking for a fix so i can play on the server with friends tried updating netty on the server by replacing the one in both the com and io folders with the latest jar on the netty site and i still get the errors that lag everything. I saw another post said solved but im not sure how to use the solutions cause they involve installing a differnt netty or something and i dont know how to do that on the server. Heres the error that repeatedly apears. Dont even need to move or do anything in game just start it join server and then this starts. Thanks for the help id give a crash report but the game never crashes just lags or rather freezes and then continues seconds later before repeating

io.netty.channel.ChannelOutboundBuffer safeSuccess
 
WARNING: Failed to mark a promise as success because it is done already: DefaultChannelPromise@118e41(success)

**Comment by normanmaurer** [comment]
@Divx001 this sounds like a bug in the system that is using netty. Which basically means they complete a `ChannelPromise` but also forward it through the pipeline. Please report the issue to the software creator itself
