### ISSUE TITLE
WebSockets on Android

### ISSUE THREAD

**Issue by om26er** [netty/netty#7139]
Hi!

I work for Crossbar.io, the main sponsor of Autobahn libraries. We are working on [autobahn-java](https://github.com/crossbario/autobahn-java). For headless our autobahn-java is based on Netty's websocket APIs that works fine as it should.

For Android I want to know if Netty is the right choice i.e. is Netty's WebSocket implementation officially supported on Android ? I ask this because I found some old stackoverflow discussions that talked about issues of Netty on Android, though that was from 2014. How is the situtation today, is it recommended to base our work off Netty for Android ?

PS: I did do some basic testing and Netty's WebSocket seems to work fine on Android but some official words from the Netty project would be very assuring.

**Comment by Scottmitch** [comment]
We generally don't target the Android platform, so I wouldn't say its officially supported. However we do get issues from time to time related to Netty on Android and when reasonable we fix them and may file issues if appropriate. We have a few contributors that maybe able to say more on the topic (/cc @ejona86 @carl-mastrangelo @nmittler).

**Comment by ejona86** [comment]
I've seen it work without much hassle. Android is quite different from OpenJDK in terms of I/O, allocations, and TLS, so Netty is sort of tuned opposite of what is best for Android. It seems like WebSockets are supported with OkHttp; that's probably what I'd be more inclined to go with on Android.

**Comment by Scottmitch** [comment]
Let me close this since this is not a Netty issue ... feel free to continue discussion though
