### ISSUE TITLE
ChannelProgressiveFuture should be changed

### ISSUE THREAD

**Issue by WhiteTrashLord** [netty/netty#7145]
I did some tests with the example HttpStaticFileServer.
I downloaded a file and canceled the connection before completion.
In order to better handle such an abort, I have 2 ideas:

1)

Adding a new method to ChannelProgressiveFutureListener

operationCanceled(ChannelProgressiveFuture future, long progress, long total) which will be called instead of the operationComplete in such a case.

or

2)

Changing the existing method operationComplete to something like this:
operationComplete(ChannelProgressiveFuture future, long progress, long total)

**Comment by normanmaurer** [comment]
@WhiteTrashLord the problem is we can not change this as it would be a API breaking change for now :(
