### ISSUE TITLE
There is Something wrong with NioEventLoop in Android 7.1.1

### ISSUE THREAD

**Issue by wooi** [netty/netty#7169]
### Expected behavior
The closeFuture's ChannelFutureListener  callback when the phone network change from enable to disable  
### Actual behavior
I got the callback in other android version when  I build up socket connetion and trun off the network others version except for Android 7.1.1. 
### Netty version
4.1.6.Final
### JVM version 
java version "1.8.0_141"
### OS version
Android 7.1.1

**Comment by normanmaurer** [comment]
@wooi please try use a more recent version of netty and if the issue still exists please provide more details and maybe even a minimal reproducer
