### ISSUE TITLE
New HTTP/2 child-channel API lacks InboundHttp2ToHttpAdapter

### ISSUE THREAD

**Issue by Bennett-Lynch** [netty/netty#7171]
The new HTTP/2 child-channel API is great, but it appears to lack support for something equivalent to InboundHttp2ToHttpAdapter (and outbound as well).

Is there anything planned for the new API to support this?  HTTP/2 is largely focused on multiplexing, and having the support to treat requests as HTTP/1-like is very helpful.

**Comment by mosesn** [comment]
@Bennett-Lynch on the server-side, there's https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ServerDowngrader.java, you might be able to do something analogous on the client-side.

**Comment by Bennett-Lynch** [comment]
Thanks. I wasn't aware of this class. Is there a client-side solution other than writing my own?

**Comment by mosesn** [comment]
@Bennett-Lynch not that I'm aware of.  The client-side API is still relatively fresh.

**Comment by normanmaurer** [comment]
@Bennett-Lynch @mosesn is correct... If you end up rolling your own please consider providing a PR for netty so we can include it :)

**Comment by normanmaurer** [comment]
@Bennett-Lynch stay tuned I think we should have something pretty soon.

**Comment by normanmaurer** [comment]
Was fixed by #7233
