### ISSUE TITLE
NPE in cleartext upgrade

### ISSUE THREAD

**Issue by mosesn** [netty/netty#7173]
### Expected behavior
No null pointer exceptions

### Actual behavior
When an HTTP/1.1 upgrade request comes in, we call `onHttpServerUpgrade` in Http2ConnectionHandler.  This makes us create a stream, which eventually calls `new DefaultHttp2StreamChannel`, which is fine, except that it assumes that handlerAdded has already been called on Http2MultiplexCodec . . . which is always true except when we're doing a cleartext upgrade.

### Steps to reproduce

Make an HttpServerUpgradeHandler, with an Http2MultiplexCodec.  Send an h2c upgrade request.

### Minimal yet complete reproducer code (or URL to code)

Try to upgrade this to netty 4.1.15.

https://github.com/twitter/finagle/blob/develop/finagle-http2/src/main/scala/com/twitter/finagle/http2/Http2CleartextServerInitializer.scala#L74

### Netty version
4.1.15.Final

**Comment by mosesn** [comment]
Digging a little deeper, the exactly problem here is because we call `prepareUpgradeResponse` before we call `upgradeTo` in Http2ServerUpgradeCodec.

**Comment by mosesn** [comment]
I was able to get around this problem by setting two private fields in HttpMultiplexCodec (both named ctx).  @normanmaurer if I merge a fix into netty, what's the ETA on a release?

**Comment by normanmaurer** [comment]
@mosesn end of next week sounds doable... so yeah please provide a pr if you already have one

**Comment by mosesn** [comment]
@normanmaurer I don't have one yet, but I'm happy to take a stab today.  Where do you think we should fix this?  HttpServerUpgradeHandler seems pretty stable (hasn't been changed in a year) so I'm more inclined to do it in Http2ServerUpgradeCodec.

Looks like maybe we could try dumping all the code from prepareUpgradeResponse into upgradeTo?

https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ServerUpgradeCodec.java#L132

What do you think?

**Comment by normanmaurer** [comment]
@mosesn sounds reasonable to me.

**Comment by normanmaurer** [comment]
@mosesn actually I think we need another fix... let me come back to you asap.

**Comment by normanmaurer** [comment]
@mosesn actually I think the real "problem" is that `Http2ConnectionHandler.on*Upgrade` is called before the handler is actually added to the pipeline. IMHO this is not very consistent with everything else as I think we should only call methods on handlers after these are part of the pipeline. The catch here is that its at the moment not possible to add the `Http2ConnectionHandler` to the pipeline as this will trigger `sendPreface(...)` and so `onHttp2ServerUpgrade(...)` will throw an exception as its called after the preface is sent. I am not currently sure what is the best way to fix this tho, as we may still need to sent the preface sometimes when the handler is added to the pipeline, just not when we will trigger an upgrade. 

@nmittler @ejona86 @carl-mastrangelo @Scottmitch @mosesn any good ideas ?

**Comment by mosesn** [comment]
Hmm . . . we might just need to supply something that's aware on creation that it's speaking h2c.  We need to effectively do this anyway on the client-side to make sure clients start on stream id 3 instead of stream id 1, so I don't think this is too heinous.

**Comment by normanmaurer** [comment]
@mosesn sounds reasonable to me... let me try to finish a pr later today or tomorrow.

**Comment by normanmaurer** [comment]
@ejona86 any concerns ?

**Comment by normanmaurer** [comment]
@mosesn PTAL https://github.com/netty/netty/pull/7184

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7184
