### ISSUE TITLE
 in junit test can EmbeddedChannel  bind a port and accept other http client's request ?

### ISSUE THREAD

**Issue by songxin1990** [netty/netty#7175]
in junit test can EmbeddedChannel  bind a port and accept other http client's request ?

**Comment by songxin1990** [comment]
@mosesn@normanmaurer

**Comment by normanmaurer** [comment]
@songxin1990 no... if you want to bind you need to use `LocalServerChanel` or a real `SocketChannel`

**Comment by hepin1989** [comment]
@songxin1990 read the book or doc
