### ISSUE TITLE
Http2MultiplexCodec can not work together with ChunkedWriteHandler

### ISSUE THREAD

**Issue by Apache9** [netty/netty#7179]
### Expected behavior
When used at server side, the `ChunkedWriteHandler` should be able to write out data chunk by chunk(multiple `Http2DataFrame`s)
### Actual behavior
The `ChunkedWriteHandler` always finds out that the channel is not writable so nothing can be written out.
### Steps to reproduce
Use `ChunkedWriteHandler` at server side.
### Minimal yet complete reproducer code (or URL to code)
See this UT
https://github.com/Apache9/netty/commit/001ec097a56c3a818819875acba881cb06dc804d
### Netty version
4.1.15.Final
### JVM version (e.g. `java -version`)
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
### OS version (e.g. `uname -a`)
Linux ubuntu 4.10.0-27-generic #30~16.04.2-Ubuntu SMP Thu Jun 29 16:07:46 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Apache9** [comment]
The problem is that the `writable` field for server side `DefaultHttp2StreamChannel` is always `false`. 

At client side, the `writable` will be changed after calling the `onStreamActive` in the `Http2ConnectionAdapter` of `DefaultHttp2RemoteFlowController`. It will finally reach the `DefaultHttp2StreamChannel.writabilityChanged`.

But at server side, the calling trace is broken up at `Http2FrameCodec.Http2RemoteFlowControllerListener.writabilityChanged`. In this method, the `Http2FrameStream` gotten from the `Http2Stream` is null, so we give up.

https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2FrameCodec.java#L588

No idea why it is null only at server side...

**Comment by normanmaurer** [comment]
@Apache9 can I reuse some of your test-code within netty and include it as part of the project under the AL2 license ?

**Comment by Apache9** [comment]
Sure.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7181
