### ISSUE TITLE
log  incorrect output use Log4J2Logger-FQCN in PatternLayout (%F:%L)%c.%M

### ISSUE THREAD

**Issue by takeseem** [netty/netty#7186]
### Expected behavior
log4j2 PatternLayout (%F:%L)%c.%M

`2017-09-07 02:20:43,500 DEBUG [main] -Dio.netty.noUnsafe: false (PlatformDependent0.java:361)io.netty.util.internal.PlatformDependent0.explicitNoUnsafe0`

### Actual behavior

`2017-09-07 01:46:24,109 DEBUG [main] -Dio.netty.noUnsafe: false (Log4J2Logger.java:73)io.netty.util.internal.PlatformDependent0.debug`

### Steps to reproduce

* config log4j2.xml
```
	<Appenders>
		<Console name="console">
			<PatternLayout pattern="%d %-5p [%t] %m (%F:%L)%c.%M%n" />
		</Console>
	</Appenders>
```
* in main() set netty use Log4j2Logger
`io.netty.util.internal.logging.InternalLoggerFactory.setDefaultFactory(io.netty.util.internal.logging.Log4J2LoggerFactory.INSTANCE)`

### Netty version
4.1.15.FINAL
### JVM version (e.g. `java -version`)
```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```
### OS version (e.g. `uname -a`)
`Linux k590s 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by normanmaurer** [comment]
Fixed in https://github.com/netty/netty/pull/7185
