### ISSUE TITLE
[Proposal] Consider separating the inbound and outbound channel handlers

### ISSUE THREAD

**Issue by maseev** [netty/netty#7196]
At the moment, Netty calls [these](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java#L934) [two](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java#L942) methods in order to find an appropriate channel handler to pass the data through the pipeline. Wouldn't it be better if the inbound and outbound channel handlers were separated? 

So instead of creating basically a double-linked list where each node contains a channel handler as well as two references (prev and next) it could be implemented in such a way that it wouldn't have to iterate through the channel handlers by checking the `inbound` or `outbound` field in the `do-while` loop. It could save some CPU cycles and make the code more JIT-friendly.

Consider the following pipeline:

Channel handler | Type
------------ | -------------
SSLHandler|inbound/outbound (duplex)
IdleStateHandler|inbound/outbound (duplex)
MessageToByteEncoder|outbound
LengthFieldBasedFrameDecoder|inbound
ByteToMessageDecoder|inbound
MyCustomHandler|inbound

Let's say we need to write some data from the `MyCustomHandler` channel handler. Using the current approach, Netty has to pass two inbound handlers (`ByteToMessageDecoder` and  `LengthFieldBasedFrameDecoder`) in order to get to the first outbound handler (`MessageToByteEncoder`).

Using the new approach won't require iterating through this list trying to find the outbound channel handler. So, it would basically call something like `ctx.outbound.next` or something similar.

The pipeline I mentioned above might look like a little bit simplistic and it might not seem worth the effort because you have to pass only two handlers before you get the one you need, but I think it might be beneficial for pipelines which have a lot of inbound handlers.

BTW, is there any way I can set up a pipeline without starting a Netty server so I can implement a simple JMH benchmark? Just to validate the idea.

WDYT?

This [ticket](https://github.com/netty/netty/issues/4468) might be related.

**Comment by normanmaurer** [comment]
@maseev this sounds like a good idea in general ... I think you could validate this by creating an instanceof `DefaultChannelPipeline` by yourself and passing an Channel implementation into it.

**Comment by maseev** [comment]
@normanmaurer Ok, thanks. I'll have a look.

**Comment by normanmaurer** [comment]
@maseev did you ever got around doing this? I am very interested in the outcome :)

**Comment by maseev** [comment]
@normanmaurer sorry for not responding for too long, I'm on vacation right now. I'll definitely take a look when I get back home.

**Comment by maseev** [comment]
I managed to create a very similar "pipeline" which is completely independent of Netty in order to test this particular use case which I described earlier. 
I did this because implementing the approach I mentioned in my first message in Netty would take me quite a long time.

Here are the benchmark results:
```
Benchmark                                                    Mode  Samples         Score  Score error  Units
i.g.m.OptimizedPipelineBenchmark.optimizedImplementation    thrpt      200  60575354.645   201711.003  ops/s
i.g.m.PipelineBenchmark.defaultImplementation               thrpt      200  53440521.232   288763.812  ops/s
```

As you can see, the performance gain is rather marginal (11%) compared to an amount of code it would require to implement it in Netty. Besides, in my opinion, using the optimized version of the pipeline would greatly increase the cognitive complexity of the code.

**Comment by kiril-me** [comment]
Can you share the code?

**Comment by maseev** [comment]
@kiril-me [here](https://github.com/maseev/netty-pipeline-benchmark) you go.
