### ISSUE TITLE
MQTT encode doesn't complain if password is set but username not

### ISSUE THREAD

**Issue by ppatierno** [netty/netty#7205]
### Expected behavior

The MQTT decoder should raise an exception trying to build a CONNECT packet where password field is set but not the username one (as by MQTT 3.1/3.1.1 spec).

### Actual behavior

The CONNECT packet is built and hasUsername and hasPassword aren't handled in the right way.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7206#pullrequestreview-62812166
