### ISSUE TITLE
Are there any plans to start publishing the netty-tcnative-openssl-static-{os_arch} packages to Maven Central?

### ISSUE THREAD

**Issue by nhnFreespirit** [netty/netty#7208]
The new netty-tcnative-openssl-static-{os_arch} packages seem very useful to us but currently we have to build them ourselves. Are there any plans to start publishing pre built versions of these packages?

Thanks

**Comment by johnou** [comment]
uber jar ftw? cc @Scottmitch

**Comment by johnou** [comment]
openssl static uber jar ftw? cc @normanmaurer @Scottmitch the disclaimer on the boringssl website isn't reassuring "Although BoringSSL is an open source project, it is not intended for general use, as OpenSSL is.".

**Comment by normanmaurer** [comment]
@johnou thats why we have google folks on the team like @nmittler @ejona86 and @carl-mastrangelo  ;)

@nhnFreespirit back in the days @Scottmitch and myself discussed this and decided against publishing openssl static builds as we didnt want to be responsible to publish new releases everytime there is a CVE reported with openssl (which sadly happens often enough 😢 ). I am not super strong here tho... @Scottmitch WDYT ?

**Comment by ejona86** [comment]
Is the main drive for this the disclaimer on the boringssl website, or something else? We've been working closely with the BoringSSL team and accept the API instability. So for the purposes of Netty's users I'm not aware of any big deficiency with using BoringSSL, unless you want a feature it dropped.

**Comment by johnou** [comment]
@ejona86 so the disclaimer is specific to the library API and not compatibility with other devices and implementations?

**Comment by ejona86** [comment]
> not compatibility with other devices and implementations

It is wire compatible with other implementations. Now, it may more aggressively remove old/broken ciphers and such. But since it provides TLS support to Chrome and Android, it has to work with a wide variety of implementations.

The main thing is that it doesn't support as many old/minority features to reduce attack surface. It also threw away problematic APIs. Comparing the OpenSSL vulnerability rate to BoringSSL's (which is a bit hard), it has proven an effective approach.

**Comment by normanmaurer** [comment]
@nhnFreespirit I think for now we will not publish other static builds then the boringssl version on maven central for the reason stated above.
