### ISSUE TITLE
Discarded inbound message that reached at the tail of the pipeline with ByteToMessageDecoder

### ISSUE THREAD

**Issue by mrtechit** [netty/netty#7211]
### Netty version
4.1.9.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### OS version (e.g. `uname -a`)
Windows 10

### Steps to reproduce
This does not reproduce every single time, however still is very evident.
1. Close the netty server (NioServerSocketChannel) while it is processing a request.
2. The client will disconnect abruptly (Till this point the server application might already be stopped)
3. Start the server again on same machine with same port.
4. All messages will be discarded with this found in DEBUG logs of netty : 
(These logs are after server restart. 

2017-09-14 16:07:04 DEBUG [nioEventLoopGroup-5-15] LoggingHandler - [id: 0xda3abef0, L:/127.0.0.1:3535 - R:/127.0.0.1:54832] REGISTERED
2017-09-14 16:07:04 DEBUG [nioEventLoopGroup-5-15] LoggingHandler - [id: 0xda3abef0, L:/127.0.0.1:3535 - R:/127.0.0.1:54832] ACTIVE
2017-09-14 16:07:04 DEBUG [nioEventLoopGroup-5-15] LoggingHandler - [id: 0xda3abef0, L:/127.0.0.1:3535 - R:/127.0.0.1:54832] RECEIVED: 186B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 30 31 38 32 31 31 30 30 33 32 33 30 30 35 43 30 |01821100323005C0|
|00000010| 32 38 43 31 38 30 30 30 30 30 30 30 30 30 30 30 |28C1800000000000|
|00000020| 30 30 30 30 30 31 30 30 32 34 30 39 31 34 31 36 |0000010024091416|
|00000030| 30 37 30 34 32 35 30 35 35 30 31 37 30 39 31 34 |0704250550170914|
|00000040| 31 36 30 37 30 34 41 30 31 32 30 31 41 30 30 31 |160704A01201A001|
|00000050| 34 30 31 30 31 31 35 30 36 35 31 37 32 32 34 37 |4010115065172247|
|00000060| 30 38 33 33 32 32 30 30 30 30 30 30 30 30 38 31 |0833220000000081|
|00000070| 39 33 3d 39 39 39 39 37 32 35 37 31 36 32 35 30 |93=9999725716250|
|00000080| 35 35 30 30 30 30 30 30 30 30 31 30 30 30 30 30 |5500000000100000|
|00000090| 30 30 30 30 30 30 30 30 30 31 30 32 36 31 30 30 |0000000001026100|
|000000a0| 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 30 |0000000000000000|
|000000b0| 30 30 30 30 30 30 30 34 31 34                   |0000000414      |
+--------+-------------------------------------------------+----------------+
2017-09-14 16:07:04 DEBUG [nioEventLoopGroup-5-15] DefaultChannelPipeline - Discarded inbound message **** that reached at the tail of the pipeline. Please check your pipeline configuration.

### Minimal yet complete reproducer code (or URL to code)
**Server start :** 
public void start() throws InterruptedException {

        getBootstrap().bind().addListener(
                (ChannelFuture future) -> {
                    final Channel channel = future.channel();
                    setChannel(channel);
                    logger.info("Server is started and listening at {}", channel.localAddress());
                }
        ).sync().await();
    }
**Server bootstrap :** 
bootstrap.group(getBossEventLoopGroup(), getWorkerEventLoopGroup())
                .channel(NioServerSocketChannel.class)
                .localAddress(getSocketAddress())
                .childHandler(new Iso8583ChannelInitializer<>(
                        getConfiguration(),
                        getConfigurer(),
                        getWorkerEventLoopGroup(),
                        getIsoMessageFactory(),
                        getMessageHandler()
                ));

**Pipelline :**  
final ChannelPipeline pipeline = ch.pipeline();
        
        pipeline.addLast("logger", new LoggingHandler());
        pipeline.addLast("lengthFieldFameDecoder", new StringLengthFieldBasedFrameDecoder(
                configuration.getMaxFrameLength(), 0, headerLength, 0, headerLength));
        pipeline.addLast("iso8583Decoder", createIso8583Decoder(isoMessageFactory));
        pipeline.addLast("iso8583Encoder", isoMessageEncoder);
if (customChannelHandlers != null) {
            pipeline.addLast(workerGroup, customChannelHandlers);
        }
        if (configurer != null) {
            configurer.configurePipeline(pipeline, configuration);
        }
iso8583Decoder is handler which extends ByteToMessageDecoder. I have not put "setSingleDecode as true"

**Comment by normanmaurer** [comment]
@mrtechit please share all the code of your custom handlers.

**Comment by normanmaurer** [comment]
Closing as the reporter did not provide the info
