### ISSUE TITLE
Add 'Automatic-Module-Name' to MANIFEST for forward compatibility with JDK9 

### ISSUE THREAD

**Issue by zyxist** [netty/netty#7218]
When a non-modular library (e.g. built for JDK8 or JDK9) is used within a modular JDK9 application, Java creates an automatic module for it. Modules should be named from the root packages they own, but the default algorithm uses JAR file name instead. If Netty migrates to JDK9 and Jigsaw one day, this may cause serious dependency issues (JVM will refuse to start, if the same module is required with two different names, e.g. `netty` and `io.netty`).

It is possible to specify the automatic module name explicitly through a Manifest entry `Automatic-Module-Name`, while the project is still built against JDK7.

I suggest to add `Automatic-Module-Name` to the manifests to acquire your root packages as module names, since JDK9 is going to be released within a few days.

**Comment by normanmaurer** [comment]
Interesting... can you open a PR for this?

**Comment by zyxist** [comment]
I need to take a closer look, how Netty Maven project structure is organized. If it turns out to be straightforward, I can try to create a PR.

**Comment by mp911de** [comment]
@zyxist See https://git1-us-west.apache.org/repos/asf?p=maven-resolver.git;a=commit;h=d1724eb7. That's a nice approach without too much hassle in the particular modules.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7245
