### ISSUE TITLE
Method setHandshakeTimeout of SslHandler does not work in server side

### ISSUE THREAD

**Issue by BillyYccc** [netty/netty#7230]
### Expected behavior
I want to enable `setHandshakeTimeout()` in server side. I call the method setHandshakeTimeout() like this `sslHandler.setHandshakeTimeout(1,TimeUnit.MILLISECONDS);` The value of HandshakeTimeout is set to a very small value so that the client and server can not complete the handshake since the handshake is timeout. 

### Actual behavior
But it can not work when I use this in server.The connection can still be established between server and client. However when I do the same in client, the SSL connection can not be established , this is what I expect to see. 

### Steps to reproduce
1. call the `sslHandler.setHandshakeTimeoutMillis(1);` or `sslHandler.setHandshakeTimeout(1,TimeUnit.MILLISECONDS);` in server
2. do connect and SSL connection can be successfully established
3. do 1 and 2 again in client side, and SSL connection can not be established

### Minimal yet complete reproducer code (or URL to code)
You may use [SecureChat](http://netty.io/4.1/xref/io/netty/example/securechat/package-summary.html) example or any other SSL example to reproduce

### Netty version
4.1.15.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by normanmaurer** [comment]
@BillyYccc please check https://github.com/netty/netty/pull/7277

**Comment by normanmaurer** [comment]
Fixed
