### ISSUE TITLE
netty-tcnative-boringssl-static-{os_arch} requires apr to be installed and updated to version 7.0.0

### ISSUE THREAD

**Issue by Authorlove** [netty/netty#7237]
### Expected behavior
netty-tcnative-boringssl-static-{os_arch} doesn't require apr as the [wiki](http://netty.io/wiki/forked-tomcat-native.html) says

### Actual behavior
netty-tcnative-boringssl-static-{os_arch} requires apr to be installed and updated to version 7.0.0

### Steps to reproduce
Here is the boringssl-static version
```
<dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-tcnative-boringssl-static</artifactId>
                <version>2.0.6.Final</version>
                <classifier>${os.detected.classifier}</classifier>
</dependency>
```
### Netty version
4.1.15.Final

### JVM version (e.g. `java -version`)
1.8.0_92

### OS version (e.g. `uname -a`)
OSX

**Comment by Authorlove** [comment]
the error message:
Reason: Incompatible library version: libnetty_tcnative716738964507841247.dylib requires version 7.0.0 or later, but libapr-1.0.dylib provides version 5.0.0

**Comment by normanmaurer** [comment]
This may be caused by a problem we had in netty 4.1.15.Final. Can you please test with 4.1.16.Final and report back ?

**Comment by Authorlove** [comment]
Yeah, it's good with 4.1.16.Final, thanks!

**Comment by normanmaurer** [comment]
Just for the record this was fixed by https://github.com/netty/netty/pull/7224
