### ISSUE TITLE
Multiple Channels with Different Service Paths - WebSocket

### ISSUE THREAD

**Issue by Lahiru-J** [netty/netty#7239]
I have a use case where channels with different service paths should be connected to the same port. 
I followed the WebSocket example and the example provided in the _Netty In Action_ book but in those cases there is a hard coded String ( `"/websocket"` ) for the `WebSocketServerProtocolHandler`.
Since `ServerBootstrap` class won't allow to add multiple `ChannelHandler`s how should I get this work done?

**Comment by normanmaurer** [comment]
You can add multiple handlers by using `ChannelInitializer` and populate the pipeline in its `initChannel` method. There are multiple examples doing this included in netty.

**Comment by gaut2112** [comment]
I see this error in 4.1.39FINAL version. 
 pipeline.addLast(new HttpServerCodec());
        pipeline.addLast(new HttpObjectAggregator(65536));
        pipeline.addLast(new WebSocketServerCompressionHandler());
        pipeline.addLast(new WebSocketServerProtocolHandler("/wsA", null, true));
        pipeline.addLast(new WebSocketFrameHandlerA());
        pipeline.addLast(new WebSocketServerProtocolHandler("/wsB", null, true));
        pipeline.addLast(new WebSocketFrameHandlerB());


Am I doing something wrong here

**Comment by csccoder** [comment]
> I see this error in 4.1.39FINAL version.
> pipeline.addLast(new HttpServerCodec());
> pipeline.addLast(new HttpObjectAggregator(65536));
> pipeline.addLast(new WebSocketServerCompressionHandler());
> pipeline.addLast(new WebSocketServerProtocolHandler("/wsA", null, true));
> pipeline.addLast(new WebSocketFrameHandlerA());
> pipeline.addLast(new WebSocketServerProtocolHandler("/wsB", null, true));
> pipeline.addLast(new WebSocketFrameHandlerB());
> 
> Am I doing something wrong here

I made a successful example, the content is as follows：

```
serverBootstrap.group(bossGroup, workGroup)
.channel(NioServerSocketChannel.class)
.childHandler(new ChannelInitializer<NioSocketChannel>() {
    @Override
    protected void initChannel(NioSocketChannel ch) throws Exception {
        ChannelPipeline pipeline = ch.pipeline();
        //HTTP编解码支持
        pipeline.addLast(new HttpServerCodec());

        //HTTP大文件编写
        pipeline.addLast(new ChunkedWriteHandler());
        //HTTP Message聚合
        pipeline.addLast("HttpObjectAggregator",new HttpObjectAggregator(Integer.MAX_VALUE));

        pipeline.addLast(new WsSwitchHandler());
    }
})

public class WsSwitchHandler extends ChannelInboundHandlerAdapter {
    @Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
        if (msg instanceof FullHttpRequest) {
            String uri = ((FullHttpRequest) msg).getUri();
            ctx.pipeline().remove(this);

            if ("/ws1".equalsIgnoreCase(uri)) {
                ctx.pipeline().addAfter("HttpObjectAggregator", WebSocketServerProtocolHandler.class.getName(), new WebSocketServerProtocolHandler(uri));
                ctx.pipeline().addAfter(WebSocketServerProtocolHandler.class.getName(), WebsocketHandler.class.getName(), new WebsocketHandler());
            } else if ("/ws2".equalsIgnoreCase(uri)) {
                ctx.pipeline().addAfter("HttpObjectAggregator", WebSocketServerProtocolHandler.class.getName(), new WebSocketServerProtocolHandler(uri));
                ctx.pipeline().addAfter(WebSocketServerProtocolHandler.class.getName(), WebsocketBHandler.class.getName(), new WebsocketBHandler());
            } else {
                ctx.channel().close();
                return;
            }

            ctx.pipeline().fireChannelRead(msg);
        }
    }
}

```
