### ISSUE TITLE
Epoll static loading broken in 4.1.16

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty#7249]
### Expected behavior
Be able to load Epoll statically

### Actual behavior
Loading fails because the shared object can't be found.

**Comment by normanmaurer** [comment]
@carl-mastrangelo what you mean with loading "statically" ?

**Comment by carl-mastrangelo** [comment]
In my case, we have a java launcher, which has all native deps linked in.  Essentially, everything from the JNI code is linked into a single binary, whose entry point is the JVM.

**Comment by normanmaurer** [comment]
got it...

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7250
