### ISSUE TITLE
ApplicationProtocolNegotiationHandler does not use fallback when with Java 9 and extension ignored  

### ISSUE THREAD

**Issue by vietj** [netty/netty#7251]
### Expected behavior

The fallback given to the `ApplicationProtocolNegotiationHandler ` is provided in the `configurePipeline` method.

### Actual behavior

The `configurePipeline` method is called with an empty string instead of the given fallback protocol. This is because the engine returns an empty string and the `ApplicationProtocolNegotiationHandler ` checks the nullity of the protocol string, it should also check wether it's empty or not.

### Steps to reproduce

A bootstrap setup with an `SslHandler` and the `ApplicationProtocolNegotiationHandler` using JDK engine. The bootstrap connects to an SSL server that does not support ALPN and ignores the extension.

### Minimal yet complete reproducer code (or URL to code)

None provided (obvious case, can contribute something next week)

### Netty version

4.1.15.Final

### JVM version (e.g. `java -version`)

```
java version "9"
Java(TM) SE Runtime Environment (build 9+181)
Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
```
### OS version (e.g. `uname -a`)

```
Darwin julien 15.6.0 Darwin Kernel Version 15.6.0: Fri Feb 17 10:21:18 PST 2017; root:xnu-3248.60.11.4.1~1/RELEASE_X86_64 x86_64
```

**Comment by normanmaurer** [comment]
@vietj I am not sure I really understand the issue :( Can you point me to the code you are talking about. For example which `configurePipeline` method ?

**Comment by vietj** [comment]
here : https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/ApplicationProtocolNegotiationHandler.java#L92

I think `protocol != null` should be replaced by `protocol != null && protocol.length() > 0`

**Comment by normanmaurer** [comment]
Ok got it... I think we need a different fix but I will take care today

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7258
