### ISSUE TITLE
Remove final keywords from basic pipeline handlers

### ISSUE THREAD

**Issue by sergey-sw** [netty/netty#7252]
It's not the first time I need to customize logic in handler classes but they are final.
Examples: io.netty.handler.proxy.HttpProxyHandler, io.netty.handler.codec.http.HttpClientCodec, sure there are more.

Classes should be open for extension, no need to prevent developers from shooting in the leg if they want to.

Netty-version: 4.1.15.Final

**Comment by normanmaurer** [comment]
@AdamSkywalker well.. as soon as we make these non-final we need to guarantee to not break stuff which means we are very care fun to do this. Can you explain what you need to change and why ?

**Comment by AdamSkywalker** [comment]
My case: for proxy handler I needed to analyse response headers from proxy server (first authorization request to proxy server) to allow/interrupt further request, today I needed to add marker interface to some handlers in pipeline to tweak them between requests in one connection.

Also, didn't understand how you can break something by allowing class inheritance

**Comment by normanmaurer** [comment]
@AdamSkywalker you can break things if people start to override methods that are either `protected` or `public` and we need to change these later on.

**Comment by normanmaurer** [comment]
Ler me close this for now...
