### ISSUE TITLE
A lot of ChannelInputShutdownReadComplete events fired for NIO channel with ALLOW_HALF_CLOSURE

### ISSUE THREAD

**Issue by khitrin** [netty/netty#7255]
### Expected behavior
Single `ChannelInputShutdownReadComplete` event will be fired for closed socket.

### Actual behavior
`ChannelInputShutdownReadComplete` event fired on each NIO event loop run.
`NioEventLoop` begin consuming a lot of CPU.

### Steps to reproduce
Create upstream connection channel with enabled `ALLOW_HALF_CLOSURE` and disabled `AUTO_READ`, do a single HTTP keep-alive request and wait until connection being closed by remote server.

### Netty version
4.1.16.Final

### JVM version (e.g. `java -version`)
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### OS version (e.g. `uname -a`)
Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

macOS Sierra 10.12.6

Also confirmed on Linux.

### Suspicious code fragment

from `io.netty.channel.nio.AbstractNioByteChannel::read`

https://github.com/netty/netty/blob/f57d8f00e17a3cbd127aeb2b499c3f2787c002e4/transport/src/main/java/io/netty/channel/nio/AbstractNioByteChannel.java#L124-L133

`readPending` not cleared when `allocHandle.lastBytesRead() <= 0`.

Negative read bytes indicates socket closed state, but each consecutive selection of this socket key with `OP_READ` will succeed immediately (may be related to http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4531726).

### Fix proposal

Call `removeReadOp()` on closed sockets.

**Comment by khitrin** [comment]
Thank you for fast response and this nice and similar fix for all channel implementations.

But, after checking code for every four affected classes, I afraid that this problem can hurt non-NIO implementations and channels with auto-read.

**Comment by khitrin** [comment]
Thank you for fast response. It will fix issue for non-autoread channels (original issue), but after looking at affected code I'm afraid that channels with `AUTO_READ` can be hurt with this wakeups.

**Comment by normanmaurer** [comment]
@khitrin so you are saying it is not fixed with the PR ?

**Comment by khitrin** [comment]
I've built netty with the PR and can confirm that original issue is fixed.

But I think we need further investigation of this case.

1. For 4.1.16.Final (from Maven central) event spam begins immediately when upstream break the connection. Also I checked that setting `readPending` to `false` by debugger helps, so the PR clearly must fix the issue.

2. For 4.1.17.Final-SNAPSHOT (with the PR) single event fired on next `.read()` call.
It is absolutely correct behaviour, but why 4.1.16.Final fires event without `.read()` and why it fixed by this PR?
I will try to rebuild 4.1.16.Final on Mac and test it on Mac and Linux platforms. 

Also similar issue may affect channels with auto read enabled and `readPending` disabling might be not enough here.

**Comment by normanmaurer** [comment]
also @Scottmitch ....

**Comment by khitrin** [comment]
Finally confirmed on Linux.

**Comment by normanmaurer** [comment]
@khitrin when you say confirmed... what do you mean ? Confirmed as this pr fix it or what ?

**Comment by grossws** [comment]
@normanmaurer, I've checked against @khitrin's source with 4.1.16.Final where issue is present on Linux and with 4.1.17.Final-SNAPSHOT from your PR #7259 which behaves same as on MacOSX.

**Comment by RoganDawes** [comment]
I'm still seeing this problem in 4.1.22.Final, which appears to have all the abovementioned fixes in place. I'm using the default NIO channel implementation, and am seeing thousands of these events fired when I shutdown the input.

**Comment by normanmaurer** [comment]
hmm interesting... @Scottmitch Can you have a look ?

**Comment by Scottmitch** [comment]
See https://github.com/netty/netty/pull/7801

**Comment by fuyou001** [comment]
@khitrin   how do you find the Suspicious code?
