### ISSUE TITLE
Get ClosedChannelException when close channel before SSL handshake

### ISSUE THREAD

**Issue by Jianzhu91** [netty/netty#7262]
Hi, recently I encounter a problem when using `Netty` and its `SlsHandler`. I would like to close a channel before SSL handshake based on my throttling configuration. I try to implement as below, but I will receive `ClosedChannelException` when I close the channel.

I add my `ThrottleHandler` before `SslHandler` in my `ChannelInitializer` . It overrides the `channelActive` method in order to determine whether we should do the SSL handshake or close the channel before the handshake. The `SslHandler` is setting in a server mode.

From my understanding, the SSL handshake should starts when the channel become active, so my closing operation should run before the SSL handshakes starts. However, I still receive a `ClosedChannelException` when closing the channel. This exception is triggered in `channelInactive` method in `SslHandler`. Does the handshake starts when the channel is active, or it just starts when you add `SslHandler` to the pipeline?

### Expected behavior
The channel should be closed normally without any exception. The handshake should not have started.

### Actual behavior
The `SslHandler` triggers `ClosedChannelException` when I close the channel before the handshake.

    java.nio.channels.ClosedChannelException
        at io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source) ~[netty-all-4.1.jar:4.1.6.Final]

### Steps to reproduce
Normally start a simple server which enables the SSL/TLS feature by adding a `SslHandler` into the `ChannelInitializer`. The `SslHandler` is setup with a Java `SSLEngine` in server mode. Then add the `ThrottleHandler` (codes are listed below) before `SslHandler`.

### Minimal yet complete reproducer code (or URL to code)
    @ChannelHandler.Sharable
    public class ThrottleHandler extends ChannelInboundHandlerAdapter {
        private ThrottleConfig config;
        private ThrottleConfig config;

        public ThrottleHandler(ThrottleConfig config) {
            super();
            this.config = config;
        }

        @Override
        public void channelActive(ChannelHandlerContext ctx) throws Exception {
            if (config.isThrottled) {
                log.info("Close a connection by throttle handler");
                ctx.close();
                return;
            }

            ctx.pipeline().remove(this);
            ctx.fireChannelActive();
        }
    }

    public class AbstractChannelInitializer extends ChannelInitializer<SocketChannel> {
        private ThrottleHandler throttleHandler;
        private SslHandler handshakeHandler;

        @Override
        protected void initChannel(SocketChannel channel) throws Exception {
            channel.pipeline().addLast(throttleHandler);
           // Add Netty SslHandler
            channel.pipeline().addLast(handshakeHandler);

            // other handlers for business logics
        }
    }

### Netty version
    4.1.6.Final

### JVM version (e.g. `java -version`)
    java version "1.8.0_144"
    Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
    Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by normanmaurer** [comment]
@Jianzhu91 before looking into this can you please upgrade your netty version to the latest 4.1 release and let me know if you still see the issue ?

**Comment by Jianzhu91** [comment]
@normanmaurer I just try again with the Netty 4.1.16.Final version. That issue still happens.

**Comment by normanmaurer** [comment]
@Jianzhu91 ok will check once I find some cycles.

**Comment by normanmaurer** [comment]
@Jianzhu91 can you give me a few more details about this. I inspected the code and I think we should only fire and `SslHandshakeCompletionEvent` event in this case and notify the pending writes. Where exactly do you see the error ? Is it in an `exceptionCaught(...)` callback or a `ChannelFutureListener` ?

**Comment by Jianzhu91** [comment]
@normanmaurer  I add a handler before `SslHandler` to close the channel when necessary.  What we want to do is to close the channel before `SSL` handshake. However, when you close the channel, the `channelInactive()` method is invoked and throws the `java.nio.channels.ClosedChannelException` (logs in the Actual Behavior section above). it's not in the `exceptionCaught(...)` or `ChannelFutureListener`. At the same time, an `SslHandshakeCompletionEvent` is fired, and notify us the failure of `SSL` handshake. We have our channel tracker to track the status of `SSL` handshake. I expect that we should not receive any exceptions and the `SslHandshakeCompletionEvent`, since the `SSL` handshake has not started.

**Comment by normanmaurer** [comment]
@Jianzhu91 so just to clarify you log it via the `SslHandshakeCompletionEvent` which you think should not be fired at all ?

**Comment by Jianzhu91** [comment]
@normanmaurer Yes. I expect `SslHandshakeCompletionEvent` should not be fired. From my understanding, SSL handshake should not starts if we add a handler before SslHandler to close the channel.

**Comment by normanmaurer** [comment]
@Jianzhu91 PTAL: https://github.com/netty/netty/pull/7368

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7368
