### ISSUE TITLE
Unable to use Netty native transports in modularized Java 9 projects

### ISSUE THREAD

**Issue by doom369** [netty/netty#7266]
Due to automatic name generation in Java 9 it is impossible to use Netty native transports - Epoll, KQueue in modularized Java 9 projects. For example, automatic module name for the epoll transport would be : 

`netty.transport.native.epoll`

And `native` is the reserved keyword which doesn't allow the module to be exported to any other module. I created also [question in SO](https://stackoverflow.com/questions/46501388/how-to-deal-with-native-keyword-in-auto-generated-module-names-in-java-9) in case there any workarounds.

However, there is actually very simple fix without moving the whole netty to java 9 that netty can apply right now.

We can add to manifest next line and it will solve the issue for Java 9. I checked it already and it works.

`<Automatic-Module-Name>netty.transport.epoll</Automatic-Module-Name>`

WDYT?

**Comment by johnou** [comment]
@doom369 ptal https://github.com/netty/netty/issues/7218

**Comment by doom369** [comment]
@johnou thanks. I saw that. My PR just fixes the concrete issue with epoll and kqueue. I think there is no need right now to give precise names for other modules until netty will provide `module-info.java` files.

**Comment by zyxist** [comment]
@doom369 -> actually, there is a need to give them now: http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html

I'll remove the `native` word from my PR.

**Comment by Scottmitch** [comment]
Wasn't this fixed recently?

**Comment by normanmaurer** [comment]
@Scottmitch yep.. good catch
