### ISSUE TITLE
If using more than one shaded netty-tcnative library in a JVM, only the first loads successfully

### ISSUE THREAD

**Issue by steveniemitz** [netty/netty#7272]
Now that netty can automatically detect the package prefix ( #6995 ), I attempted to shade netty into two different packages, lets call them `A` and `B`.

Package `A` loaded tcnative successfully (lets say it was shaded to `A.repackaged.io.netty`).

However, when package `B` attempted to load, I got an `UnsatisfiedLinkError` invoking `aprMajorVersion()` in `io.netty.internal.tcnative.Library`.

Digging in more, I do see the native library (from package `B`) being unpacked and loadLibrary being called on it (and not throwing an exception).  However, `lldb` reports that it is not loaded (eg it doesn't show up in `image list`, only the library from package `A` does), and further, running the JVM with `-verbose:jni` shows the JNI native methods for the shaded version of tcnative in package `A` being registered (again) instead of `B`. ex:

`[Registering JNI native method A.repackaged.io.netty.internal.tcnative.Library.initialize0]`

I've tested this on OSX, but not Linux yet.

**Comment by johnou** [comment]
cc @ejona86

**Comment by normanmaurer** [comment]
also @carl-mastrangelo

**Comment by carl-mastrangelo** [comment]
@steveniemitz to clarify, you mean the *shaded* version of `io.netty.internal.tcnative.Library` right?  At leats on OpenJDK, most of the interesting Native library loading logic is in ClassLoader.  Have you tried stepping through it in a debugger yet?

**Comment by steveniemitz** [comment]
Sorry, yeah my post was confusing there.  I do mean the shaded version of `Library`.

Working from memory right now, I have stepped through.  The call to (native) `System.loadLibrary` succeeds, and it does pass the expected correct shaded lib name.  I haven't stepped though the native code though.

**Comment by Xeli** [comment]
Sorry to add noise to this issue, but how did you manage to shade netty with tcnative at all? I run into the problem that netty cannot load the native library (for details: [)](https://stackoverflow.com/questions/46650776/after-shading-io-netty-tcnative-stops-working)

**Comment by ejona86** [comment]
@Xeli, you also need to rename the .so's, .jnilib, and .dll. See #6995 for some more information.

**Comment by normanmaurer** [comment]
@steveniemitz so can you please clarify what exactly the issue is ?

**Comment by steveniemitz** [comment]
Sorry,  I'm not sure how I could be more descriptive,  what is unclear here?

**Comment by Scottmitch** [comment]
> However, when package B attempted to load, I got an UnsatisfiedLinkError invoking aprMajorVersion() in io.netty.internal.tcnative.Library.

As @ejona86 said https://github.com/netty/netty/issues/7272#issuecomment-335524387 you need to rename the native libraries. This is generally not done automatically by shading plugins for maven and gradle ... you need to configure an extra step.

**Comment by steveniemitz** [comment]
Yes, I realize the native libraries need to be renamed.  Both shaded jars work fine on their own.  The problem manifests only after the first shaded library has loaded and registered its JNI methods.

**Comment by ejona86** [comment]
As far as investigation, I think we should just try the same setup as mentioned: two normally-incompatible tcnatives, with at least one shaded.

I think this is the sort of case I've been mentioning I was concerned about (offline). I've not had time to investigate, and it'll probably be time-consuming. I'm worried there won't be a solution, other than swapping to Conscrypt. Since Conscrypt (will have) a stable API, you don't shade, and so there's only one version in play.

**Comment by steveniemitz** [comment]
fwiw, I was testing with (I think, this was over a month ago now)
- google-cloud-trace library + tcnative 2.0.6 (shaded), 
- bigtable-client-core + tcnative 2.0.6 (shaded)

So the same version of the lib (also binary identical).  My naive guess is the OSX loader is detecting that a native lib is being `dlopen`ed twice and simply ignoring the second one.

**Comment by Scottmitch** [comment]
> Yes, I realize the native libraries need to be renamed. 

@steveniemitz - my mistake ... I glanced to quickly at the issue description.

**Comment by Scottmitch** [comment]
Here are some options which maybe viable:

https://stackoverflow.com/a/6540059

If the binaries are identical ... it maybe just sufficient to have the `JNI_OnLoad` method invoked, which will do the JNI registration under the shaded method names.

If the binaries are not identical we would want both libraries to be loaded to avoid conflicts. Have tried with different versions of `tcnative` @steveniemitz ?

**Comment by steveniemitz** [comment]
I have not tried two different versions.  Based on my guess from above I expect it'd work though.

**Comment by acharis** [comment]
While others in my organization running OSX have run into this issue, I can confirm that on linux this works for me.

**Comment by jhaber** [comment]
To expand on what Alex said, we ran into this issue in our apps that were using a mix of grpc-netty-shaded as well as another copy of shaded netty under a different package prefix (both copies are version 4.1.22.Final). This was the minimal reproducible example we came up with:

```java
public static void main(String... args) throws Exception {
    System.out.println(io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.isAvailable());
    System.out.println(other.netty.shaded.io.netty.handler.ssl.OpenSsl.isAvailable());
}
```

On OSX, whichever OpenSsl class is invoked first returns true, and the second always returns false. But it's not reproducible on the flavors of Linux that we've tried. We haven't tested on Windows.

**Comment by normanmaurer** [comment]
@acharis yes please... Can you also explain "this works for me" means ? Does it mean that everything "just works" as it is for you on linux ?

**Comment by acharis** [comment]
Yes, sorry, I was far too terse.
Running jhaber's minimal example above prints
```
true
true
```
on my linux machine.

Additionally, members of my team have gotten that example to run on OSX by running OSX's `install_name_tool` to change the id of the dylib for our differently shaded netty.

**Comment by normanmaurer** [comment]
@acharis can you give some more details on what exactly they did with `install_name_tool` ?

**Comment by acharis** [comment]
`install_name_tool -id my_id <path to dylib>`

**Comment by normanmaurer** [comment]
Please see https://github.com/netty/netty/pull/8207 ... I will do the same changes for tcnative as well.

Also I really think about writing a maven and gradle plugin to do all of the needed steps to shade netty / netty-tcnative so people will not need to mess with all of this. Thoughts ?

**Comment by ejona86** [comment]
:-/. Needing to run `install_name_tool` means we must do the shading on OS X. That's going to be annoying. I _really_ hope no Windows- or Linux-specific issue pops up where we must run commands on those platforms as well.

**Comment by normanmaurer** [comment]
@ejona86 yeah it is a mess :( I am investigate if there is any way to just do it manually . I guess it’s a matter of rewriting the Mach-o header

**Comment by normanmaurer** [comment]
@ejona86 PTAL https://github.com/netty/netty/pull/8210 :)

**Comment by normanmaurer** [comment]
Last missing part https://github.com/netty/netty-tcnative/pull/382 :)
