### ISSUE TITLE
##Cannot call initChannel

### ISSUE THREAD

**Issue by quyetpv** [netty/netty#7282]
### Expected behavior
I setup server as below:
EventLoopGroup bossGroup = new NioEventLoopGroup(1);
		EventLoopGroup workerGroup = new NioEventLoopGroup(50);
		try {
			ServerBootstrap b = new ServerBootstrap();
			b.group(bossGroup, workerGroup).channel(NioServerSocketChannel.class)
					.handler(new LoggingHandler(LogLevel.ERROR)).childHandler(new ChannelInitializer<SocketChannel>() {
						@Override
						public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
							System.out.println("loi exceptionCaught");
							cause.printStackTrace(System.out);
							super.exceptionCaught(ctx, cause);
						}
						@Override
						public void initChannel(SocketChannel ch) {
							ChannelPipeline p = ch.pipeline();
							p.addFirst(new SeverHandler());
						}
					});
			b.childOption(ChannelOption.SO_KEEPALIVE, true);
			b.childOption(ChannelOption.TCP_NODELAY, true);
			// Bind and start to accept incoming connections.
			ChannelFuture f = b.bind(LISTEN_PORT).sync();
			
			f.channel().closeFuture().sync();
### Steps to reproduce
I create a thread which create many thread to connect server. I connect about 2000 connection. The connection will close after 5 seconds. When all connection is closed I create more connection but I only see the log: 
[nioEventLoopGroup-2-1] ERROR logging.LoggingHandler  ---- [id: 0x3f94fa1a, L:/0:0:0:0:0:0:0:0:8011] READ: [id: 0xe76fe9a1, L:/192.168.1.104:8011 - R:/192.168.1.206:64697]
[nioEventLoopGroup-2-1] ERROR logging.LoggingHandler  ---- [id: 0x3f94fa1a, L:/0:0:0:0:0:0:0:0:8011] READ COMPLETE

I debug and it not call to function public void initChannel(SocketChannel ch).  Please help me explain when initChannel cannot call.

### Netty version
4.1.16
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
Window and Centos.

**Comment by normanmaurer** [comment]
@quyetpv initChannel(...) is called once the connection was accepted. Maybe you are blocking the EventLoop ? Please provide more infos like for example  profiler snapshot that will show if the threads are blocked or not

**Comment by normanmaurer** [comment]
Please reopen with more infos if you still think its a netty issue

**Comment by quyetpv** [comment]
The issues cause my code it make EventLoop blocking. I have resolve it.
Thanks,
