### ISSUE TITLE
When the client closes the connection, if the server attempt to write on the socket, the read buffer is lost.

### ISSUE THREAD

**Issue by amorillotraxens** [netty/netty#7287]
My use case is :
- The client opens the connection, write more than 1Kb of data and closes the connection
- The server reads 1024b from the buffer, writes a response that fails because the socket is closed, and then do not read anymore data.
Though all the data has been written (checked with tcpdump).

Here is my ChannelInitializer :

`    
@Override
    protected void initChannel(final SocketChannel ch) throws Exception {
        final ChannelPipeline pipeline = ch.pipeline();

        ch.config().setRecvByteBufAllocator(new AdaptiveRecvByteBufAllocator());
        
        // log
        pipeline.addLast("loggingHandler", loggingHandler);

        pipeline.addLast("stringenc",new StringEncoder());
        pipeline.addLast("stringdec",new StringDecoder());
        
        pipeline.addLast("serverHandler", this.serverHandler);
    }
`

and my ServerHandler :

`
public class TestServerHandler extends SimpleChannelInboundHandler<String> {

    @Override
    protected void channelRead0(ChannelHandlerContext ctx, String request) throws Exception {
        ctx.write(""+request.length());
    }
    @Override
    public void channelReadComplete(ChannelHandlerContext ctx) {
        ctx.flush();
    }
`

To write to the socket :

`        
try (   Socket socket = new Socket("localhost", 3970);
                OutputStream outputStream = socket.getOutputStream()) {
            outputStream.write(msg.getBytes());
            outputStream.flush();
            socket.close();
        }
`

Please note that if I don't use "setRecvByteBufAllocator", the whole buffer is read and the flush is done once everything has been read.
Also, if I use writeAndFlush instead of write + flush, the second par of the buffer is also lost.

- Netty version : 4.1.16.Final.
- Java Version : java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

The attached logs shows 1100 bytes of data sent. On the first case, the "setRecvByteBufAllocator" has not been set, no data is lost (OK.log file).
On the second case, the "setRecvByteBufAllocator" has been set, only the 1024 first bytes are read (KO.log file).
[OK.log](https://github.com/netty/netty/files/1367812/OK.log)
[KO.log](https://github.com/netty/netty/files/1367813/KO.log)

**Comment by NiteshKant** [comment]
By default `AUTO_CLOSE` [1] is `true` for a channel, which means a write failure closes the channel. IIUC, you do not want write failures to close the channel and continue reading till read fails. If so, then you can turn `AUTO_CLOSE` to false for the child channel, which will allow to read more data if available.

AFAICT, using `AdaptiveRecvByteBufAllocator` may trigger `readComplete()` earlier which triggers `flush` that detects channel close on write [2] earlier than default max byte allocator.

[1]https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/ChannelOption.java#L108
[2]https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/AbstractChannel.java#L936

**Comment by normanmaurer** [comment]
@amorillotraxens exactly as @NiteshKant said.

**Comment by amorillotraxens** [comment]
Thanks for the reply. It seems to work with setAutoclose(false). Though, setAutoclose and isAutoclose are deprecated. Will they be replaced ? Should I still use these methods ?

Regards,

**Comment by normanmaurer** [comment]
You should use them if you want... we will not remove these anytime soon. In fact I should remove the deprecation on these.

Will open a PR shortly
