### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by mytang0** [netty/netty#7294]
My Applications:
	
		bossGroup = new NioEventLoopGroup();
		workerGroup = new NioEventLoopGroup();
		ServerBootstrap b = new ServerBootstrap();
		b.group(bossGroup, workerGroup).channel(NioServerSocketChannel.class)
				.childHandler(new ChannelInitializer<SocketChannel>() {
					@Override
					public void initChannel(SocketChannel ch) throws Exception {
						ChannelHandler[] handlers = createHandlers();
						for (ChannelHandler handler : handlers) {
							ch.pipeline().addLast(handler);
						}
					}
				}).option(ChannelOption.SO_BACKLOG, 128)
				.option(ChannelOption.SO_REUSEADDR, true)
				.childOption(ChannelOption.SO_KEEPALIVE, true)
				.childOption(ChannelOption.SO_REUSEADDR, true);

On the Linux server, the client continually initiates a connection request and the number of connections on the server continues to increase; when the server-open file descriptor reaches the system limit (RLIMIT_NOFILE), the listening port is shut down！

Netty version: netty-all-4.0.42.Final.jar
JDK version: 1.8.0_121
Linux version: 3.0.101-63-default

**Comment by mytang0** [comment]
I found the problem as a result of the following code：


 protected boolean closeOnReadError(Throwable cause) {
        // ServerChannel should not be closed even on IOException because it can often continue
        // accepting incoming connections. (e.g. too many open files)
        return cause instanceof IOException &&
                !(cause instanceof PortUnreachableException) &&
                this instanceof ServerChannel;
    }


[this instanceof ServerChannel;]
changed to
[!(this instanceof ServerChannel);]

The problem seems to have been fixed.

I do not know here, the author is not another consideration.

**Comment by normanmaurer** [comment]
Yes this was fixed a long time ago
