### ISSUE TITLE
Sometimes netty doesn't  flush data to client

### ISSUE THREAD

**Issue by shindonghyeok** [netty/netty#7296]
My netty server is http  relay server. 
My process is like this.. 

1. client A ->(request) -> netty server -> (request) -> client B
2. client A <-(response) <- netty server <-(response) <- client B 

The problem is that process '1' always success. however  when netty server relay response which is from client B to client A, netty doesn't flush data to client A in  process '2'.

    protected void channelRead0(ChannelHandlerContext ctx, FullHttpResponse msg) throws Exception {
        RESPONSE = HTTP_RESPONSE.response_relay(jsonBuf);
        CHANNEL_GROUP.stream().filter(i -> i.attr(ID).get().equals(DESTINATION_ID)).forEach(i -> i
                .pipeline().addAfter("beesHandler","responseEncoder",new HttpResponseEncoder())

        );
        CHANNEL_GROUP.stream().filter(i -> i.attr(ID).get().equals(DESTINATION_ID)).forEach(i -> i
                .writeAndFlush(RESPONSE)
        );
        CHANNEL_GROUP.stream().filter(i -> i.attr(ID).get().equals(DESTINATION_ID)).forEach(i ->i
                .pipeline().remove("responseEncoder")
        );

    }

The reason which add 'responseEncoder' and remove it is channel's pipeline was set to flush request in basically.. 
Anyway sometimes it work very well. but sometimes it doesn't work(flush). pipeline's content alway same.

**Comment by johnou** [comment]
`writeAndFlush` returns a future, you might want to wait for that to complete before removing the response encoder.

**Comment by shindonghyeok** [comment]
thank you for your reply. but unfourtunatly, i am beginner of netty.. so could you explain  how to do that in detail?

**Comment by pkolaczk** [comment]
Also make sure the other end is reading the data. If you forget to call `ctx.read()` and `AUTO_READ` is off, the data will not be passed to the handler on the receiving side, despite `writeAndFlush` being successful on the sender.

**Comment by shindonghyeok** [comment]
I had solved a problem using 'ChannelFuture' and 'Listener'
    ChannelFuture cf = i.writeAndFlush(RESPONSE);
                    cf.addListener(new ChannelFutureListener() {
                            @Override
                            public void operationComplete(ChannelFuture channelFuture) throws Exception {
                                if(channelFuture.isSuccess()){
                                    DESTINATION_CHANNEL.pipeline().remove("responseEncoder");
                                    DESTINATION_CHANNEL = null;
                                }else{
                                }
                            }
                    });

like this...
