### ISSUE TITLE
Expose SocketChannel class on EventLoop/Group

### ISSUE THREAD

**Issue by kiiadi** [netty/netty#7302]
When configuring a `Bootstrap` the channel class type depends on the type of the `EventLoopGroup` which leads to code like:

```java
if (eventLoopGroup instanceOf EpollEventLoopGroup) {
    return EpollChannelSocket.class;
} else if (eventLoopGroup instanceOf KQueueEventLoopGroup) {
    return KQueueChannelSocket.class;
} else {
    return NioChannelSocket.class;
}
```
see here: https://github.com/aws/aws-sdk-java-v2/blob/master/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java#L135

Since the `EventLoopGroup` type and the `SocketChannel` are coupled together does it make sense to expose the type of `SocketChannel` on the `EventLoopGroup` itself? Basically extending the EventLoopGroup interface to add:

```java
Class<? extends SocketChannel> socketChannelClass();
```
Happy to submit a PR for this - just wanted to float the idea before I did.

**Comment by johnou** [comment]
@kiiadi something like this? https://github.com/netty/netty/pull/6873

**Comment by kiiadi** [comment]
Pretty much! I'll resolve this at watch that PR!
