### ISSUE TITLE
A simpler example for beginners

### ISSUE THREAD

**Issue by erelsgl** [netty/netty#7305]
I am considering to use netty in a Java course, to teach basics of using web services and web sockets.
I am looking for a very simple and short example to begin with;
a simple web-service (or socket) that just takes a string and returns it in reverse.

I looked at the user guide:  https://netty.io/wiki/user-guide-for-4.x.html
but, the example there looks quite long and complicated.

Is it possible to add to the documentation, a simpler start-up example?

Thanks

**Comment by fucongchan** [comment]
https://github.com/netty/netty/tree/4.1/example

**Comment by erelsgl** [comment]
I did not understand, where is the example in your link?

*--- Erel Segal-Halevi   (http://erelsgl.github.io
<http://erelsgl.github.io>) אראל סגל הלוי*

**Comment by johnou** [comment]
@erelsgl all the subdirectories are example projects.

**Comment by normanmaurer** [comment]
@erelsgl as @johnou said... closing
