### ISSUE TITLE
Dangling ThreadDeathWatcher Thread After Shutting Down EventLoopGroup

### ISSUE THREAD

**Issue by hiranya911** [netty/netty#7310]
I'm experimenting with a slight variation of the [WebSocketClient](https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http/websocketx/client/WebSocketClient.java) example. When I finally tear down the channel and the event group I expected all netty-related threads to terminate gracefully. But it always leaves a threadDeathWatcher thread dangling. So far the only way to force it to terminate it seems to be calling `FastLocalThread.removeAll()`. Is this behavior normal?

### Expected behavior

Clean termination of all threads.

### Actual behavior

Dangling thread:

```
"threadDeathWatcher-1-1" #17 daemon prio=1 os_prio=0 tid=0x00007fd05815b800 nid=0x26af2 waiting on condition [0x00007fd0d8efc000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:152)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:745)
```

### Steps to reproduce

Start the websocket client example, and exchange a few messages. Finally I would terminate the program by calling:

```
channel.close();
group.shutdownGracefully();
```

### Netty version

`v4.1.14`

### JVM version (e.g. `java -version`)

```
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
```

### OS version (e.g. `uname -a`)

```
Linux 4.4.0-89-generic #112~14.04.1-Ubuntu SMP Tue Aug 1 22:08:32 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by normanmaurer** [comment]
Yes its expected as it is used by the static instance of PooledByteBufAllocator.
