### ISSUE TITLE
how to Reduce Size   in android

### ISSUE THREAD

**Issue by lgengsy** [netty/netty#7312]
I use  netty 4.1.16 and found  the netty-all-4.1.16.Final.jar files is 3.8M .I want to Reduce the netty Size  ,so  i use those jar files .but  i don't know which is necessary .What documents can I refer to? thks.

**Comment by su1216** [comment]
the code below works for me.
`compile 'io.netty:netty-buffer:4.1.13.Final'
compile 'io.netty:netty-codec:4.1.13.Final'
compile 'io.netty:netty-common:4.1.13.Final'
compile 'io.netty:netty-handler:4.1.13.Final'
compile 'io.netty:netty-resolver:4.1.13.Final'
compile 'io.netty:netty-transport:4.1.13.Final'`

**Comment by fenik17** [comment]
Use only the modules those that you need. Do not use `netty-all`.

**Comment by lgengsy** [comment]
get it  ,thks @su1216
