### ISSUE TITLE
NioSocketChannel leaks file descriptors even when closing

### ISSUE THREAD

**Issue by tobier** [netty/netty#7321]
### Expected behavior
I expect that if an exception is thrown when calling `NioSocketChannel#close`, any open sockets should be closed. 

### Actual behavior
If I run the program below, it indicates that file descriptors are leaking. Similar problems are seen in larger applications.

### Steps to reproduce
Run the code below, observe the output.

#### Example java code

```java
public class NioSocketChannelLeaks
{
    public static void main(String[] args) throws NumberFormatException, IOException
    {
        // Get process ID (first comment in https://stackoverflow.com/a/6372205)
        int pid = Integer.parseInt(new File("/proc/self").getCanonicalFile().getName());

        ProcessBuilder builder = new ProcessBuilder("lsof", "-p", Integer.toString(pid));
        builder.inheritIO().redirectOutput(ProcessBuilder.Redirect.PIPE);

        for (int i = 0; i < 1024; ++i)
        {
            try
            {
                NioSocketChannel channel = new NioSocketChannel();
                channel.close();
            }
            catch (IllegalStateException x)
            {
                try (BufferedReader reader = new BufferedReader(new InputStreamReader(builder.start().getInputStream())))
                {
                    System.out.printf("Got exception: '%s', current open file descriptors: %d%n", x.getMessage(), reader.lines().count());
                }
            }
        }
    }
}
```
#### Output from above program when run in Eclipse 4.6
```
Got exception: 'channel not registered to an event loop', current open file descriptors: 217
Got exception: 'channel not registered to an event loop', current open file descriptors: 218
Got exception: 'channel not registered to an event loop', current open file descriptors: 219
Got exception: 'channel not registered to an event loop', current open file descriptors: 220
Got exception: 'channel not registered to an event loop', current open file descriptors: 221
Got exception: 'channel not registered to an event loop', current open file descriptors: 222
Got exception: 'channel not registered to an event loop', current open file descriptors: 223
Got exception: 'channel not registered to an event loop', current open file descriptors: 224
Got exception: 'channel not registered to an event loop', current open file descriptors: 225
[... output continues and descriptors increase ...]
```

### Netty version
Netty 4.0.47

### JVM version (e.g. `java -version`)
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### OS version (e.g. `uname -a`)
Linux 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by NiteshKant** [comment]
You are getting an exception from `channel.close()` as you can see in the log:

> 'channel not registered to an event loop'

As the message suggests, you have not registered the channel with an eventloop which is required to close the channel. One easy way to fix this is to create this channel using a [`Bootstrap`](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/bootstrap/Bootstrap.java#L49) which correctly registers with eventloop and sets up the channel.

**Comment by normanmaurer** [comment]
@tobier as @NiteshKant said... closing this one

**Comment by tobier** [comment]
@NiteshKant Thanks! It was obvious that I had to do something like this (or, perhaps there was a bug in Netty), but my Google-fu was not good enough. I'll use a Bootstrap as you suggest and hopefully it works.
