### ISSUE TITLE
Expiry strategy improvement request for DefaultDnsCache

### ISSUE THREAD

**Issue by jianyuanzh** [netty/netty#7329]
### Expected behavior
Hostname configured with both IPv4 and IPv6 dns records. Netty dns resolver is configured to prefer IPv4 addresses, so I should always get IPv4 address.

### Actual behavior
but after several minutes run, it can only return ipv6 record.

### Steps to reproduce
Create a NettyDns resolver with DefaultDnsCache, and keep it running for several minutes. You can see finally only ipv6 record can be got.

### Minimal yet complete reproducer code (or URL to code)
the url have the issue is "mirrors.servercentral.com"

### Netty version
4.1.15.Final

### JVM version (e.g. `java -version`)
```
java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```
### OS version (e.g. `uname -a`)
```
uname -a
Darwin zhangjianyuans-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

**Comment by jianyuanzh** [comment]
The root cause for this issue if the expire strategy of the DefaultDnsCache. The DefaultDnsCache controls the expiry per record, and remove the record from the list if the record is expired. In this case, the ipv4 record ttl is 60, while the ipv6 record ttl is 21599. 

So, ipv4 record will surely be expired before ipv6 record. And ipv6 record is still recorded in DefaulDnsCache, so query the DefaultDnsCache can still get the record for the URL with the ipv6 record.  

But as mentioned above, we are expecting the ipv4 record.

**Comment by normanmaurer** [comment]
@jianyuanzh hmm I think what you describe is actually what I would expect. Can you show me how exactly your build the `DnsNameResolver` ?

**Comment by jianyuanzh** [comment]
@normanmaurer , here is my demo script to check the TTL for DNS record:
```
String dns = "mirrors.servercentral.com.";

EventLoopGroup loopGroup = new NioEventLoopGroup(1)

StringBuilder sb = new StringBuilder()
DnsNameResolver resolver = new DnsNameResolverBuilder(loopGroup.next())
        .channelType(NioDatagramChannel.class)
        .resolvedAddressTypes(ResolvedAddressTypes.IPV4_PREFERRED)
        .maxQueriesPerResolve(16)
        .resolveCache(new MyDefaultDnsCache(sb))
        .queryTimeoutMillis(500).build()


for (int i = 0; i < 10 ; i++) {
    Thread.sleep(60000)
    println resolver.resolveAll(dns).get()
}

println sb.toString()
loopGroup.shutdownGracefully()

class MyDefaultDnsCache extends DefaultDnsCache {
    final StringBuilder sb
    MyDefaultDnsCache(StringBuilder sb) {
        this.sb = sb;
    }
    @Override
    DnsCacheEntry cache(String hostname, DnsRecord[] additionals, InetAddress address, long originalTtl, EventLoop loop) {
        sb.append("originalTtl: ").append(address.getHostAddress()).append(" ").append(originalTtl).append("\n");
        return super.cache(hostname, additionals, address, originalTtl, loop)
    }
}
```

And by change the resolve type, I can sse that the TTL for ipv4 and ipv6 record differ greatlly. 
```
>> !groovy
Exit code: 0, output:
returns DefaultPromise@35883680(incomplete)
output:
[mirrors.servercentral.com./2001:1838:2000:601:0:0:0:10]
[mirrors.servercentral.com./2001:1838:2000:601:0:0:0:10]
[mirrors.servercentral.com./2001:1838:2000:601:0:0:0:10]
[mirrors.servercentral.com./2001:1838:2000:601:0:0:0:10]
[mirrors.servercentral.com./2001:1838:2000:601:0:0:0:10]
[mirrors.servercentral.com./2001:1838:2000:601:0:0:0:10]
[mirrors.servercentral.com./2001:1838:2000:601:0:0:0:10]
....
originalTtl: 2001:1838:2000:601:0:0:0:10 21599
>> !groovy
Exit code: 0, output:
returns DefaultPromise@5758e491(incomplete)
output:
[mirrors.servercentral.com./204.93.249.148]
[mirrors.servercentral.com./204.93.249.148]
.....
originalTtl: 204.93.249.148 60
```

**Comment by normanmaurer** [comment]
@jianyuanzh so you say you think its a bug because it should try to refetch ipv4 as there was an ipv4 record before that was in the cache ?

**Comment by jianyuanzh** [comment]
yes, almost there.

As the DefaultDnsCache's impl, when ipv4 expired it will remove the ipv4 recod, and ipv6 is still there. The following dns reolving will always returning an IPv6 record.

**Comment by normanmaurer** [comment]
@jakubjanecek https://github.com/netty/netty/pull/7656 for a possible fix.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7656
