### ISSUE TITLE
Epoll errors still appearing on Netty 3.9.9 version

### ISSUE THREAD

**Issue by ashishjayaswal** [netty/netty#7335]
### Platform Details:
Netty: 3.9.9 Final
Jave: "1.8.0_101"
Scala: 2.11.1
Play: 2.3.0

OS: Linux Server release 6.8 
### Expected behavior
CPU Utilization should not go beyond 40% in a load test having 8-9hits per sec. 
### Actual behavior
CPU Utilization is going high and reaching 100% for New I/O worker for Epoll.
Example threads:
"New I/O worker #32" #2709 daemon prio=5 os_prio=0 tid=0x00007f11401bf000 nid=0x2a8f runnable [0x00007f110997e000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006f732bd78> (a sun.nio.ch.Util$2)
	- locked <0x00000006f732bd60> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006f7354980> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
New I/O worker #26" #2703 daemon prio=5 os_prio=0 tid=0x00007f11400b3800 nid=0x2a89 runnable [0x00007f1109f84000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006f72fd8b0> (a sun.nio.ch.Util$2)
	- locked <0x00000006f72fd8f8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006f730faf0> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at org.jboss.netty.channel.socket.nio.SelectorUtil.select(SelectorUtil.java:68)
New I/O worker #17" #96 prio=5 os_prio=0 tid=0x00007f11aec32000 nid=0x761e runnable [0x00007f110facd000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006d6559ac0> (a sun.nio.ch.Util$2)
	- locked <0x00000006d6559aa8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006d6cf6e90> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)

### Steps to reproduce
Few months back, I was able to perform load test with 15hits per sec without even reaching 25% of CPU Utilization but now when I am performing a load test even with 5hits per second having 4cores CPU it reaches 100% CPU Utilization.

I know this has been discussed in below 2 threads but not with my platform thought I referred it too:
https://github.com/netty/netty/pull/565
https://github.com/netty/netty/issues/327

I tried enabling below property which didn't helped.
-Dorg.jboss.netty.epollBugWorkaround=true

Could you please help in checking if the workaround was removed with this release or is there any other issue with java 1.8?

Thanks

**Comment by ashishjayaswal** [comment]
@normanmaurer

**Comment by johnou** [comment]
@ashishjayaswal Netty 3.x is eol, please try updating to 4.x.

**Comment by ashishjayaswal** [comment]
@johnou : Thanks for replying John! Few queries:
- Could you please recommend a final version where epoll workaround flag will work in case we will still see the issue? 
- Is the code applied on 3.5.7 still included in 4.x?

**Comment by johnou** [comment]
@ashishjayaswal you might want to try the latest 4.1.x (currently 4.1.16.Final). Yes the code is still in 4.x branch https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/nio/NioEventLoop.java#L328

**Comment by ashishjayaswal** [comment]
@johnou Thanks john for confirming! I will upgrade to latest version and let you know my findings in sometime.

**Comment by ashishjayaswal** [comment]
@johnou I have upgraded the version but now started getting a new error as below:
Uncaught error from thread [play-akka.actor.default-dispatcher-15] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[play]
java.lang.NoSuchMethodError: org.jboss.netty.handler.codec.http.HttpRequest.setHeader(Ljava/lang/String;Ljava/lang/Object;)V
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.construct(NettyAsyncHttpProvider.java:691)
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.buildRequest(NettyAsyncHttpProvider.java:648)
        at com.ning.http.client.providers.netty.NettyConnectListener$Builder.build(NettyConnectListener.java:144)


Does that mean I need to remove setHeader from my code or is there any other dependency I am missing. I am using netty-all in my sbt file to install new version.

**Comment by johnou** [comment]
Looks like you might need to upgrade akka too to a version which supports Netty 4.x.

**Comment by slandelle** [comment]
> Looks like you might need to upgrade akka

That's not Akka, that's Play :)

@ashishjayaswal You seem to be using a very old Play version that was using Netty 3 for both server side, and client side through AsyncHttpClient (the actual client underneath the Ws API) 1.
Both Netty 3 and AHC 1 have reached end of life for a very long time and are no longer maintained.
Any question related to those dead versions will face the same answer: please upgrade.

You must upgrade your Play version to a modern one. Don't try to upgrade your dependencies, that won't work with your Play version as APIs are different.

**Comment by ashishjayaswal** [comment]
Thanks @slandelle ! This may take sometime for me to upgrade as I am getting lot of dependencies issues after upgrading. I will let you all know once the upgrades are completed.

**Comment by ashishjayaswal** [comment]
@slandelle : Hi guys, I tried upgrading version and below are those and I am still having the same issue
Error:
java.lang.NoSuchMethodError: org.jboss.netty.handler.codec.http.HttpRequest.setHeader(Ljava/lang/String;Ljava/lang/Object;)

Details on changes:
scalaVersion : "2.11.11"
libraryDependencies :
"org.webjars" % "webjars-play_2.11" % "2.6.2",
"com.typesafe.akka" %% "akka-cluster-tools" % "2.4.4",
"org.asynchttpclient" % "async-http-client" % "2.0.24",
"io.netty" % "netty-all" % "4.1.8.Final" force()

Is there anything I am missing?

**Comment by normanmaurer** [comment]
Seems like you still have an dependency on netty 3 somewhere. You will need to figure this out and see if you can update it.
