### ISSUE TITLE
Netty nio in javafx

### ISSUE THREAD

**Issue by kristosh** [netty/netty#7336]
I have a javafx game which is a simple QA game. I want to create multiplayer scenario in order two players to play in the same time and exchanging some information. Firstly, I want to check that both of them are waiting to enter the platform and then during the real game to send some infom between them. I am investigating netty nio and how can I use it in order to do what I want. Firstly, I am trying to use an architecture of one server and two clients (each one a unique player) and try to check when two channels are connected to the server.  I am using the code[ founded here](https://github.com/eugenp/tutorials/tree/master/libraries/src/main/java/com/baeldung/netty). What am trying to find is how the server handler is working. What is the difference between the extends ChannelInboundHandlerAdapter and extends SimpleChannelInboundHandler<String>. In which method should i check in the server about my number of connections and how can i sent this info automatically to both clients?

**Comment by normanmaurer** [comment]
@kristosh please use stackoverflow for questions ... this is a bug-tracker.
