### ISSUE TITLE
Investigate whether it's possible not to use finalizer for Recycler$WeakOrderQueue

### ISSUE THREAD

**Issue by luengnat** [netty/netty#7343]
Recycler$WeakOrderQueue has a finalize() method. It could potentially harm the GC performance. We should investigate whether it's possible not to use finalize() method.

**Comment by johnou** [comment]
@luengnat feel free to investigate, you can see https://github.com/netty/netty/pull/5577 for background on why it was used.

**Comment by johnou** [comment]
While it could potentially harm GC performance I would be interested in seeing a reproducer, if not then maybe just close this issue if it's not a problem..

**Comment by johnou** [comment]
@normanmaurer something for the new ObjectCleaner?

**Comment by normanmaurer** [comment]
@johnou once in, yes

**Comment by normanmaurer** [comment]
Please check https://github.com/netty/netty/pull/7530

**Comment by normanmaurer** [comment]
This was fixed
