### ISSUE TITLE
EventLoop.schedule with big delay fails

### ISSUE THREAD

**Issue by zyclonite** [netty/netty#7365]
this behaviour was discovered by accident, so there is no actual usecase behind it but it is definitely not possible to use Long.MAX_VALUE in milliseconds for a scheduled event

### Expected behavior
runnable should trigger after given delay
getting a proper exception if something goes wrong

### Actual behavior
working with delays smaller of around 10_000_000_000ms on all platforms i tested with (osx, linux)
failing on osx with already a delay of 15_768_000_000ms (5 years)
with the following exception
```
Nov 04, 2017 2:08:39 PM io.netty.channel.nio.NioEventLoop handleLoopException
WARNING: Unexpected exception in the selector loop.
java.io.IOException: Invalid argument
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:746)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
```
failing on linux with around 946_080_000_000 (300 years)
which immediately triggers the runnable without exception

### Minimal yet complete reproducer code (or URL to code)
```
public class Main {
    public static void main(String[] args) {
        final ThreadFactory threadFactory = new DefaultThreadFactory("test-eventloop");
        NioEventLoopGroup eventLoopGroup = new NioEventLoopGroup(1, threadFactory);
        eventLoopGroup.setIoRatio(50);
        EventLoop el = eventLoopGroup.next();
        Runnable toRun = Main::handle;
        Future<?> future = el.schedule(toRun, 1000L * 60 * 60 * 24 * 365 * 300, TimeUnit.MILLISECONDS);
        System.out.println("timer scheduled");
    }

    private static void handle() {
        System.out.println("timer fired");
    }
}
```

### Netty version
seems to happen on all 4.1.x versions (tested on 4.1.8, 4.1.15, 4.1.16)

### JVM version (e.g. `java -version`)
osx oracle 1.8.0_152
linux openjdk 1.8.0_144

### OS version (e.g. `uname -a`)
darwin 16.7.0
linux 4.13.9 and 4.13.11

**Comment by normanmaurer** [comment]
will have a look. Most likely its an overflow.

**Comment by normanmaurer** [comment]
@zyclonite please check https://github.com/netty/netty/pull/7402

**Comment by zyclonite** [comment]
thank you for the fast fix!
works for linux so far (will test it for osx in the evening)

typo or on purpose? ```static final long MAX_SCHEDULED_DAYS = 356 * 3;```

**Comment by zyclonite** [comment]
works on osx as well and shows consistent behaviour

**Comment by normanmaurer** [comment]
fixed by https://github.com/netty/netty/pull/7402
