### ISSUE TITLE
Feature request - Native transport on ARM system

### ISSUE THREAD

**Issue by konsultaner** [netty/netty#7367]
Is it planned to support native transport on ARM systems? Or is it somehow supported? I get the error

    could not load a native library: netty_transport_native_epoll_arm_32

when calling 

    Epoll.unavailabilityCause().getMessage()

**Comment by normanmaurer** [comment]
@konsultaner there is currently no plan to ship support for arm systems. That said you should be able to compile it by yourself on the system.

**Comment by konsultaner** [comment]
@normanmaurer I'll give it a try but gcc-multilib is not available on raspian. Do I have to have it?

**Comment by doom369** [comment]
@konsultaner keep up updated in case of success. You don't need raspian in order to compile native transport for ARM as far as I know. And `gcc-multilib` is used exactly for cross-compilation.

**Comment by elharo** [comment]
ARM has grabbed a lot of marketshare in the last few years, and is still growing. Is the plan still not to ship binaries for ARM?

If this hasn't happened yet, but the Netty project is interested in it, it's possible I can find funding for this effort.

**Comment by normanmaurer** [comment]
@elharo we do cross compile for aarch64... I think this should be enough ?
