### ISSUE TITLE
pom.xml  Cannot resolve symbol 'jacoco.argLine

### ISSUE THREAD

**Issue by xyzroundo** [netty/netty#7369]
### OS window7

![image](https://user-images.githubusercontent.com/1466075/32424749-64bdedd2-c2e9-11e7-8c13-348ec039f5a9.png)

**Comment by johnou** [comment]
It's more of a warning, really. simply means no default value is defined for the jacoco.argLine property in the coverage profile.

**Comment by normanmaurer** [comment]
yep.. Let me close it

**Comment by nprhust** [comment]
so, is it means that we can ignore the warning like this "Can not resolve symbol "jacoco.argLine"?

**Comment by johnou** [comment]
yes, unless it's actually causing Maven mojos to fail.
