### ISSUE TITLE
The method initChannel(SocketChannel) of handler not triggered when use FixedChannelPool#acquire()

### ISSUE THREAD

**Issue by leiqiao0** [netty/netty#7371]
### Expected behavior
When pool.acquire() called, same as bootstrap.connect()
### Actual behavior
not triggered
### Minimal yet complete reproducer code (or URL to code)
sorry, we can not access gist in my contry
### Netty version
4.1.10.Final
### JVM version (e.g. `java -version`)
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
### OS version (e.g. `uname -a`)
Linux ring 4.4.0-98-generic #121~14.04.1-Ubuntu SMP Wed Oct 11 11:54:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
Sorry I dont understand the problem. Can you please share some code which highlights it ?

**Comment by normanmaurer** [comment]
@leiqiao0 please re-open with more details if you still think its a netty issue
