### ISSUE TITLE
How To set upper limit for UDP DatagramPacket

### ISSUE THREAD

**Issue by kdobbler** [netty/netty#7372]
Hi,

I'm using netty 4.0.0Alpha8 and I'm currently facing a problem with maximum datagram packet size, which is 2048. 

How can I set the limit to a higher value? 

I tried to set it with 

bootStrap.group(new NioEventLoopGroup())
				.channel(NioDatagramChannel.class)
				.localAddress(new InetSocketAddress(port))
				.option(ChannelOption.SO_BROADCAST, true)
				.option(ChannelOption.UDP_RECEIVE_PACKET_SIZE, 6192)
				//.option()
				.handler(new OSCServerHandler(oscServerListener));

but this causes the warning:

Unknown channel option: UDP_RECEIVE_PACKET_SIZE=6192

Any hints appreciated.
Thanks, BR Klaus

**Comment by normanmaurer** [comment]
@kdobbler use `new FixedSizeRecvByteBufAllocator(numBytes)`.

Also you want to update your netty version!
