### ISSUE TITLE
Docs - User guide for 4.x - Broken images

### ISSUE THREAD

**Issue by surrealcristian** [netty/netty#7374]
On the [User Guide for 4.X, section "Dealing with a Stream-based Transport"](http://netty.io/wiki/user-guide-for-4.x.html#dealing-with-a-stream-based-transport), the images shows the text "No puml file found!".

Image links:

- https://camo.githubusercontent.com/24ed1176ecca468dfb2b8b017bb927a8715a16f2/687474703a2f2f756d6c2e6d766e7365617263682e6f72672f676973742f3832653366626530653264346466323833323262
- https://camo.githubusercontent.com/5b595baf5071bf669f81d08b7554064f4142cc69/687474703a2f2f756d6c2e6d766e7365617263682e6f72672f676973742f6233316330626437626266633639666438326436
- https://camo.githubusercontent.com/24ed1176ecca468dfb2b8b017bb927a8715a16f2/687474703a2f2f756d6c2e6d766e7365617263682e6f72672f676973742f3832653366626530653264346466323833323262

**Comment by madgnome** [comment]
This seems to work now

**Comment by kingluo** [comment]
Do not work! I cannot see the images too. @normanmaurer could you replace them with other stable url? Is it github issue?
