### ISSUE TITLE
While migrating our application from wildfly 9 to Wildfly 10 existing transaction attributes result in locking error. Is it a wildfly bug?

### ISSUE THREAD

**Issue by crinaboitor** [netty/netty#7379]
Our statefull sessionbeans methods with default transaction attribute (required) that were working on the previous configuration no longer work on Wildfly 10. Method access is locked from the transaction of the previous method call.

Is it a Wildfly specific issue and we should have a specific configuration?

**Comment by normanmaurer** [comment]
I think you should ask this on the wildfly issue tracker and not here.
