### ISSUE TITLE
Android problem with Netty 4.1.16

### ISSUE THREAD

**Issue by acarioni** [netty/netty#7385]
Is there any reason why in netty-common-4.1.16.Final.jar every class is compiled with Java 6 except for io/netty/util/internal/shaded/org/jctools/queues/package-info.class, which is compiled with Java 8? 
I am developing an Android app using Netty 4.1.16 and apk building fails because of that class. If I remove it from the jar, everything is fine.

**Comment by johnou** [comment]
@acarioni it's fixed in the next 4.1.x release.

**Comment by johnou** [comment]
https://github.com/netty/netty/pull/7284
