### ISSUE TITLE
Remove obsolete packages from mvnrepository? 

### ISSUE THREAD

**Issue by eun-ice** [netty/netty#7386]
On mvn repository https://mvnrepository.com/artifact/io.netty there are some outdated packages

io.netty » netty
Netty/All In One
Last Release on Dec 3, 2012

And for the newer packages the "last release date" shows the last netty 5 alpha:

io.netty » netty-all
Netty/All In One
Last Release on Mar 3, 2015

March 2015 is the last alpha of the discontinued 5.0.0 branch.

Maybe removing that would help users find the right netty version for them.

**Comment by normanmaurer** [comment]
IMHO removing jars is a bad practice as it can break builds

**Comment by eun-ice** [comment]
Even alpha jars?

**Comment by normanmaurer** [comment]
Yes... everything that is not SNAPSHOT may break stuff

**Comment by rkapsi** [comment]
> everything that is not SNAPSHOT may break stuff

:100:
