### ISSUE TITLE
Getting unable to open input stream error when trying to use Netty in IBM WAS server

### ISSUE THREAD

**Issue by iosnewbie2016** [netty/netty#7389]
Hi - Am trying to use netty jars, as part of pushy library(https://github.com/relayrides/pushy) to send apple push notifications. It runs fine in my local tomcat. When I try to deploy the same on IBM WAS and start my server, it gives me the below exception.

com.ibm.ws.ecs.internal.scan.context.impl.ScannerContextImpl scanJAR unable to open input stream for resource io/netty/util/internal/shaded/org/jctools/queues/package-info.class in archive WEB-INF/lib/netty-common-4.1.16.Final.jar

Pls find below the versions am using. 

WAS - 8.5.5
Java - 1.7
Netty - 4.1.16

Pls help me understand the cause for the issue and how to fix the same. Thanks.

**Comment by fenik17** [comment]
It's fixed by #7284. Wait next release.

**Comment by iosnewbie2016** [comment]
thanks. Can you pls let me know rough timeline for the next release? And I assume this is issue with Java 7 and it will work fine with Java 8?

**Comment by fenik17** [comment]
Yep, this should works fine with Java 8.
About the release date we can ask @normanmaurer )

**Comment by iosnewbie2016** [comment]
@normanmaurer, can you pls help us with the release date? Thanks.

**Comment by normanmaurer** [comment]
This week
