### ISSUE TITLE
pooled ByteBuf copy will create unpooled ByteBuf

### ISSUE THREAD

**Issue by las1991** [netty/netty#7393]
-Dio.netty.allocator.type : pooled

When i call CompositeByteBuf.copy , but it create a Unpooled ByteBuf.
and then my server frequently GC.
I think this method should be written like this :

`public ByteBuf copy(int index, int length) {`
`checkIndex(index, length);`
`ByteBuf dst = ByteBufAllocator.DEFAULT.buffer(length);`
`if (length != 0) {`
`copyTo(index, length, toComponentIndex(index), dst);`
`}`
`return dst;`
`    }`

This is just one of my Suggestions, if right, hope to fix it later. If not, please correct it.

**Comment by ninja-** [comment]
I think changing copy() to create pooled buffers would be api breaking and would cause memory leaks in user apps...(no need to call .release() right now)
Personally I avoid using copy() for the reason you mentioned and replace it with:
1. create new pooled buffer with the same size
2. newBuf.readBytes(buf)

**Comment by ninja-** [comment]
I would also recommend avoiding CompositeByteBuf for most use cases, especially for high performance

**Comment by normanmaurer** [comment]
@ninja- I disagree with your point about API breakage. You are supposed to call release() if you not do its a bug. That said I will need to have a look whats going on here.

**Comment by normanmaurer** [comment]
@las1991 please check https://github.com/netty/netty/pull/7395 ... This should fix it

**Comment by las1991** [comment]
@normanmaurer thank you
