### ISSUE TITLE
FixedChannelPool out of memory

### ISSUE THREAD

**Issue by sparkfax** [netty/netty#7394]
The following link show out of memory info from hprof:
[hprof summary](https://www.evernote.com/shard/s428/sh/184600fb-cb43-4ed8-97a5-49dfb860bef7/d5fa26e81c51123d5acaba6662f0e00a)
[hprof original file](https://s3.amazonaws.com/bidder-code-data/java.tar.gz)
### Steps to reproduce
10 client Pools, 350 connection per pool. 
### Minimal yet complete reproducer code (or URL to code)
      //client send code, need use any pool class to replace Unpooled.copiedBuffer ?
        ByteBuf byteBuf = Unpooled.copiedBuffer(content, StandardCharsets.UTF_8);
        FullHttpRequest msg = new DefaultFullHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.POST, uri.getRawPath() + "?" + uri.getRawQuery(), Unpooled.wrappedBuffer(byteBuf));
        msg.headers().set(HttpHeaderNames.HOST, uri.getHost());
        msg.headers().set(HttpHeaderNames.CACHE_CONTROL, false);
        msg.headers().set(HttpHeaderNames.ACCESS_CONTROL_ALLOW_HEADERS, false);
        msg.headers().set(HttpHeaderNames.CONTENT_TYPE, new AsciiString("application/json"));
        msg.headers().set(HttpHeaderNames.CONTENT_LENGTH, byteBuf.readableBytes());
       ClientPool.sendMsg(msg);
   //ClientPool  sendMsg code
        final FixedChannelPool pool = getInstance().poolMap.get(address);

        Future<Channel> future = pool.acquire();

        future.addListener(new FutureListener<Channel>() {

            public void operationComplete(Future<Channel> f) {

                if (f.isSuccess()) {
                    Channel ch = null;
                    try {
                        ch = f.getNow();
                        ReferenceCountUtil.retain(msg); //need?
                        ch.writeAndFlush(msg);
                    } catch (Throwable a) {
                        a.printStackTrace();
                    } finally {
                        ReferenceCountUtil.release(msg);  //need?
                 }else{ 
                           //f.isSuccess()==false, no channel available
                         //some business operation
                        //   ReferenceCountUtil.release(msg);   //need?  no add this right now
                    }

              
when received response from server,
ClientPool.release(ctx.channel());
I active the release method when server response.  If server response slow, it will produce many f.isSuccess()=false.   Is this cause out of memory?

### Netty version
nettyall 4.1.16 Final
### JVM version (e.g. `java -version`)
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
### OS version (e.g. `uname -a`)
Linux ip-172-31-9-182.ec2.internal 3.10.0-514.21.2.el7.x86_64 #1 SMP Sun May 28 17:08:21 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
can you share the hprof file ?

**Comment by sparkfax** [comment]
Is the above hrof html file enough? or do you need original hrof file?

**Comment by normanmaurer** [comment]
@sparkfax interesting... the original file would be helpful

**Comment by sparkfax** [comment]
@normanmaurer I have added original hrof file.

**Comment by normanmaurer** [comment]
So I looked at your heap-dump and yes this is the cause of the out of memory. All the DefaultPromise in the heap dump are failed because of too many acquired calls (you can see this by inspect the Throwable that failed it). The problem here is the the Listener holds a reference to the `ClientPool` that also holds a reference to the `DefaultFullHttpRequest` which you seem to never release. So yep this will result in a leak for sure.

Here you can see a snip of the issue:

![screen shot 2017-11-21 at 19 08 31](https://user-images.githubusercontent.com/439362/33089043-bde43404-ceef-11e7-9400-0d8a8a040364.png)
