### ISSUE TITLE
Runtime Java 6 support - but Java 7 API called

### ISSUE THREAD

**Issue by boaks** [netty/netty#7398]
I'm not sure, if perhaps just the project description is deprecated, but netty currently states to run on java 6, but netty 4.1.15 calls `java.nio.channels.SocketChannel.shutdownInput` and `java.nio.channels.SocketChannel.shutdownOutput`, which are according to javadoc introduced since 1.7.

Calling that java 7 stuff would force android to use also a higher API level.

So is this intended? Or are there other solutions possible?

**Comment by normanmaurer** [comment]
@boaks it works because it will only call these methods if you run on a java version >= 7:

```java
        if (PlatformDependent.javaVersion() >= 7) {
            javaChannel().shutdownOutput();
        } else {
            javaChannel().socket().shutdownOutput();
        }
```

So while we use newer java stuff when possible we will fall-back to the "old" way if needed.

**Comment by normanmaurer** [comment]
@boaks It does as we always assume java version 6 on android ;)
https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/PlatformDependent0.java#L804
