### ISSUE TITLE
Support for writing float and double little endian

### ISSUE THREAD

**Issue by martin3361** [netty/netty#7401]
### Expected behavior
be able to do ByteBuf.writeFloatLE(float value) and ByteBuf.writeDoubleLE(double value)

### Actual behavior
those methods are missing, what I do for current workaround is:
`out.writeBytes(ByteBuffer.allocate(4).order(ByteOrder.LITTLE_ENDIAN).putFloat(value).array());`

**Comment by normanmaurer** [comment]
These were added a while back to the 4.1 branch... Please update your netty version.

**Comment by martin3361** [comment]
sorry, I was using 4.14 and it didn't have it. my bad
