### ISSUE TITLE
API changes report for Netty snapshot

### ISSUE THREAD

**Issue by lvc** [netty/netty#7410]
Hi,

I'd like to share report on API changes and backward compatibility for the Netty library: https://abi-laboratory.pro/java/tracker/timeline/netty-all/

BC — binary compatibility
SC — source compatibility

The report is generated by the https://github.com/lvc/japi-tracker tool according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

The analysis result for the latest snapshot is included to the report. Hope it will be helpful for users and maintainers of the library.

Thank you.

![netty-all-1](https://user-images.githubusercontent.com/1517837/32835372-dde99344-ca16-11e7-993f-53c4127b079b.png)

![netty-all-2](https://user-images.githubusercontent.com/1517837/32835371-ddc9bc18-ca16-11e7-9945-dfef94bd20cc.png)

**Comment by normanmaurer** [comment]
Thanks... let me close this as its not an issue but just some "information"
