### ISSUE TITLE
Some trouble for WRITER_IDLE_STATE_EVENT

### ISSUE THREAD

**Issue by oojeek** [netty/netty#7412]
### Expected behavior
WRITER_IDLE_STATE_EVENT not trigged when sending data

### Actual behavior
WRITER_IDLE_STATE_EVENT is trigged

### Steps to reproduce
sometimes I need send big data pack, which would take several seconds, but when the data is sending, the WRITER_IDLE_STATE_EVENT event still can be trigged, even if I set the observeOutput as true as bellow:
pipeline.addFirst("idleStateHandler", new IdleStateHandler(true,9, 2, 11, TimeUnit.SECONDS));
I want to know how to resolve this question

### Minimal yet complete reproducer code (or URL to code)
public class MyClientHandler extends SimpleChannelInboundHandler<String> {
    private String tempString;

    public MyClientHandler() {
        // generate a large pack
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < 1024 * 1024; i++) {
            builder.append("abcdefghijklmnopqrstuvwxyz");
        }
        tempString = builder.toString();
    }

    @Override
    protected void channelRead0(ChannelHandlerContext ctx, String msg) throws Exception {
        System.out.println(LocalDateTime.now().toString() + "----" + ctx.channel().remoteAddress().toString() + "----" + msg.length());
    }

    @Override
    public void channelActive(ChannelHandlerContext ctx) throws Exception {
        super.channelActive(ctx);
        sendData(ctx);
    }

    // this function made the data sending all the time, but WRITER_IDLE_STATE_EVENT can still be trigged
    private void sendData(ChannelHandlerContext ctx) {
        if (!ctx.channel().isActive())
        {
            System.out.println("channel inactive...");
            ctx.close();
            return;
        }

        System.out.println("send a large pack of data ...");

        long tickCount = System.currentTimeMillis();
        ChannelFuture future = ctx.writeAndFlush(tempString);
        ChannelPromise promise = (ChannelPromise)future;
        promise.addListener(new GenericFutureListener<Future<? super Void>>() {
            @Override
            public void operationComplete(Future<? super Void> future) throws Exception {
                System.out.println("send completed");
                sendData(ctx);
            }
        });
        System.out.println("Time elapse:" + (System.currentTimeMillis() - tickCount));
    }

    @Override
    public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
        if (evt == IdleStateEvent.READER_IDLE_STATE_EVENT) {
            System.out.println("READER_IDLE_STATE_EVENT");
        } else if (evt == IdleStateEvent.WRITER_IDLE_STATE_EVENT){
            // for heartbit
            System.out.println("WRITER_IDLE_STATE_EVENT----" + LocalDateTime.now().toString());
            //ctx.writeAndFlush("ACK");
        } 
        super.userEventTriggered(ctx, evt);
    }
}

This is my console output:
WRITER_IDLE_STATE_EVENT----2017-11-16T15:30:12.166
WRITER_IDLE_STATE_EVENT----2017-11-16T15:30:14.167
WRITER_IDLE_STATE_EVENT----2017-11-16T15:30:16.171
WRITER_IDLE_STATE_EVENT----2017-11-16T15:30:18.175
WRITER_IDLE_STATE_EVENT----2017-11-16T15:30:20.177
WRITER_IDLE_STATE_EVENT----2017-11-16T15:30:22.177
WRITER_IDLE_STATE_EVENT----2017-11-16T15:30:24.179
WRITER_IDLE_STATE_EVENT----2017-11-16T15:30:26.182
WRITER_IDLE_STATE_EVENT----2017-11-16T15:30:28.185
WRITER_IDLE_STATE_EVENT----2017-11-16T15:30:30.186
WRITER_IDLE_STATE_EVENT----2017-11-16T15:30:32.187
WRITER_IDLE_STATE_EVENT----2017-11-16T15:30:34.188
WRITER_IDLE_STATE_EVENT----2017-11-16T15:30:36.189
WRITER_IDLE_STATE_EVENT----2017-11-16T15:30:38.192
WRITER_IDLE_STATE_EVENT----2017-11-16T15:30:40.193
WRITER_IDLE_STATE_EVENT----2017-11-16T15:30:42.197
WRITER_IDLE_STATE_EVENT----2017-11-16T15:30:44.197
WRITER_IDLE_STATE_EVENT----2017-11-16T15:30:46.199
WRITER_IDLE_STATE_EVENT----2017-11-16T15:30:48.199

### Netty version
'io.netty:netty-all:4.1.9.Final'

### JVM version (e.g. `java -version`)
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### OS version (e.g. `uname -a`)
macOS 10.12.6 (16G29)

**Comment by normanmaurer** [comment]
@oojeek can you please upgrade to the latest netty version and report back if you still see the issue ?

**Comment by oojeek** [comment]
@normanmaurer I use the version of 4.1.17.Final，but the issue still seen.
