### ISSUE TITLE
No Little Endian accessor for Double or Float

### ISSUE THREAD

**Issue by davecramer** [netty/netty#7413]
### Expected behavior
getFloatLE or getDoubleLE are not available

**Comment by normanmaurer** [comment]
It exists in the latest 4.1 release.

**Comment by davecramer** [comment]
I have 4.1.17 and I must be blind because readDoubleLE doesn't exist ?

Dave Cramer

**Comment by normanmaurer** [comment]
https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/ByteBuf.java#L1552 ?

**Comment by davecramer** [comment]
thx.

Apparently 4.1.7 is not the same as 4.1.17

Dave Cramer

**Comment by normanmaurer** [comment]
@davecramer yep ;)
