### ISSUE TITLE
Usage of DefaultHttpHeader.names() outcome may result in java.lang.ArrayStoreException

### ISSUE THREAD

**Issue by mikkokar** [netty/netty#7428]
`DefaultHttpHeader.names()` exposes HTTP header names as a `Set<String>`. Converting the resulting set to an array using `toArray(String[])` throws an exception: `java.lang.ArrayStoreException: io.netty.util.AsciiString`. 

### Expected behavior

I expect following code to return an array of String objects:

```
        Set<String> nettyHeaders = new DefaultHttpHeaders(true)
                .add(HttpHeaderNames.CONTENT_LENGTH, "50")
                .names();
        
        String[] namesArray = nettyHeaders.toArray(new String[nettyHeaders.size()]);
```

### Actual behavior

But the code above throws an exception:

```
java.lang.ArrayStoreException: io.netty.util.AsciiString

	at io.netty.handler.codec.HeadersUtils$DelegatingStringSet.fillArray(HeadersUtils.java:234)
	at io.netty.handler.codec.HeadersUtils$DelegatingStringSet.toArray(HeadersUtils.java:227)
	at io.netty.handler.codec.http.DefaultHttpHeadersTest.providesHeaderNamesAsArray(DefaultHttpHeadersTest.java:222)        ...
```
### Steps to reproduce

See below.

### Minimal yet complete reproducer code (or URL to code)

I have constructed this test to demonstrate the issue:

```
    @Test
    public void providesHeaderNamesAsArray() throws Exception {
        Set<String> nettyHeaders = new DefaultHttpHeaders(true)
                .add(HttpHeaderNames.CONTENT_LENGTH, "50")
                .names();

        String[] namesArray = nettyHeaders.toArray(new String[nettyHeaders.size()]);
        assertArrayEquals(namesArray, new String[]{"content-length"});
    }
```

### Root Cause

The problem lies in the DelegatingStringSet class in HeaderUtils.java, which adapts the underlying `CharSequence` to a `String`. Well, the adaptation is implemented for the `iterator()` only, but not for `toArray()` method. 

### Netty version

4.1.17 and latest Netty 4.1 branch.

### JVM version (e.g. `java -version`)

jdk 1.8.0_131

**Comment by normanmaurer** [comment]
@mikkokar thanks! Will check

**Comment by normanmaurer** [comment]
@mikkokar PTAL https://github.com/netty/netty/pull/7429

**Comment by normanmaurer** [comment]
Fixed via https://github.com/netty/netty/pull/7429
