### ISSUE TITLE
Netty ChannelGroup size error (with same IP but different ports)

### ISSUE THREAD

**Issue by andymacau853** [netty/netty#7430]
My server is ready 9001 port to telnet, now just use netty's channelgroup to do local test:

### Expected behavior
The client:
telnet 127.0.0.1:9001
telnet 127.0.0.1:9001
telnet 127.0.0.1:9001
telnet 127.0.0.1:9001

The server:
127.0.0.1:1301   <---- ChannelGroup size = 1
127.0.0.1:1302   <---- ChannelGroup size = 2
127.0.0.1:1303   <---- ChannelGroup size = 3
127.0.0.1:1304   <---- ChannelGroup size = 4

### Actual behavior
The client:
telnet 127.0.0.1:9001
telnet 127.0.0.1:9001
telnet 127.0.0.1:9001
telnet 127.0.0.1:9001

The server:
127.0.0.1:1301   <---- ChannelGroup size = 1
127.0.0.1:1302   <---- ChannelGroup size = 1
127.0.0.1:1303   <---- ChannelGroup size = 1
127.0.0.1:1304   <---- ChannelGroup size = 1

### Steps to reproduce
Using local PC to telnet server by 127.0.0.1:9001 then test it.

### Netty version
4.1.16 final (netty-all)

### JVM version (e.g. `java -version`)
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

### OS version (e.g. `uname -a`)
Windows 8.1 Pro + Netbeans 8.2 full

**Comment by andymacau853** [comment]
import io.netty.bootstrap.ServerBootstrap;
import io.netty.channel.ChannelFuture;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.ChannelPipeline;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.handler.codec.LineBasedFrameDecoder;
import io.netty.handler.codec.bytes.ByteArrayDecoder;
import io.netty.handler.codec.bytes.ByteArrayEncoder;

public class Server {

    private static final int port = 9001;

    public static void main(String[] args) throws Exception {
        EventLoopGroup bossGroup = new NioEventLoopGroup();
        EventLoopGroup workerGroup = new NioEventLoopGroup();
        ServerBootstrap b = new ServerBootstrap();
        ChannelFuture f = b.group(bossGroup, workerGroup)
                .channel(NioServerSocketChannel.class)
                .childHandler(new ChannelInitializer<SocketChannel>() {
                    @Override
                    protected void initChannel(SocketChannel ch) {
                        ChannelPipeline p = ch.pipeline();
                        p.addLast(new LineBasedFrameDecoder(128));
                        p.addLast(new ByteArrayDecoder());
                        p.addLast(new ByteArrayEncoder());
                        p.addLast(new ServerHandler());
                    }
                })
                .bind(port)
                .sync();
        System.out.println("The server at port " + port + " is ready.");
    }
}

**Comment by andymacau853** [comment]
import io.netty.channel.Channel;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelInboundHandlerAdapter;
import io.netty.channel.group.ChannelGroup;
import io.netty.channel.group.DefaultChannelGroup;
import io.netty.util.ReferenceCountUtil;
import io.netty.util.concurrent.GlobalEventExecutor;
import java.io.ByteArrayOutputStream;

public class ServerHandler extends ChannelInboundHandlerAdapter {

    private final ChannelGroup cg = new DefaultChannelGroup("Default", GlobalEventExecutor.INSTANCE);
    private final ByteArrayOutputStream s = new ByteArrayOutputStream();

    @Override
    public void handlerAdded(ChannelHandlerContext ctx) throws Exception {
        Channel c = ctx.channel();
        this.cg.add(c);
    }

    @Override
    public void handlerRemoved(ChannelHandlerContext ctx) throws Exception {
        Channel c = ctx.channel();
        this.cg.remove(c);
    }

    @Override
    public void channelActive(ChannelHandlerContext ctx) throws Exception {
        System.out.println("The client connected to server from " + ctx.channel().remoteAddress() + "; ChannelGroup is " + this.cg.size());
    }

    @Override
    public void channelInactive(ChannelHandlerContext ctx) throws Exception {
        System.out.println("The client disconnected to server from " + ctx.channel().remoteAddress() + "; ChannelGroup is " + this.cg.size());
    }

    @Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {

        this.s.flush();
        ReferenceCountUtil.release(msg);
    }

    @Override
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {
        cause.printStackTrace();
        ctx.close();
    }
}

**Comment by normanmaurer** [comment]
@andymacau853 this is a bug in your code. You will need to share the same `ChannelGroup` for all your `ServerHandler` instances. In your correct code a new `ServerHandler` is created per connection.

One approach would be to mark the `ServerHandler` `@Sharable` and use the same instance when adding it to the pipeline

**Comment by andymacau853** [comment]
oh yes, sorry my mistake
