### ISSUE TITLE
Netty 4 threading model question

### ISSUE THREAD

**Issue by rschmitt** [netty/netty#7437]
Is the following statement true, false, or undefined behavior?

> An invocation of `write` or `writeAndFlush` *happens-before* the invocation of any `ChannelFutureListener` callbacks associated with the write operation.

To elaborate: any thread can call `channel.write()`, and the [threading model](https://netty.io/wiki/new-and-noteworthy-in-4.0.html#well-defined-thread-model) states that "the `ChannelFutureListeners` added to `ChannelFuture` are always invoked by the `EventLoop` thread assigned to the future's associated `Channel`." By cases:

1. If `write` is invoked from the `EventLoop` thread, the `ChannelFutureListeners` will be invoked from the same thread, which trivially implies a *happens-before* relationship.
2. If `write` is invoked from another thread, a write task will be created and invoked on the `EventExecutor` associated with the tail of the pipeline. `EventExecutor` is a subtype of `java.util.concurrent.Executor`, which states: "Memory consistency effects: Actions in a thread prior to submitting a `Runnable` object to an `Executor` *happen-before* its execution begins, perhaps in another thread."

Keep in mind that I am not asking about ordering guarantees of writes made from different threads, I'm just asking about the presence or absence of a memory barrier between the `channel.write()` call and the invocation of the callback.

**Comment by normanmaurer** [comment]
@rschmitt yes thats correct

**Comment by rschmitt** [comment]
Thanks!

By the way, I suggest removing the mention of `ChannelHandlerInvoker` from the [documentation](https://netty.io/wiki/new-and-noteworthy-in-4.0.html#well-defined-thread-model), as it appears to have been removed before the release of 4.1.0-Final.

**Comment by wangx1949** [comment]
@normanmaurer
