### ISSUE TITLE
Received Messages Look Like Certificate's Content in Android (SSL)

### ISSUE THREAD

**Issue by kurniawanrizzki** [netty/netty#7447]
### Netty version
4.1.9
### OS version (e.g. `uname -a`)
Lollipop (5.0)

Please to following this code to initiate `SslContext` : 

`private void initContext () throws KeyStoreException, CertificateException, NoSuchAlgorithmException, IOException, UnrecoverableKeyException {

        KeyStore key = KeyStore.getInstance("BKS");
        key.load(keyIn, password.toCharArray());

        TrustManagerFactory factory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
        factory.init(key);

        context = SslContextBuilder.forClient().trustManager(factory).build();
    }`

And the `pipeline` : 

`    public SslHandler getSslHandler (SocketChannel ch, String host, int port) {

        SslHandler handler = context.newHandler(ch.alloc(), host, port);
        handler.engine().setUseClientMode(true);

        return handler;

    }`

`    private ChannelInitializer<SocketChannel> createChannelInitializer(final SimpleChannelInboundHandler<String> clientHandler) {
        return new ChannelInitializer<SocketChannel>() {

            @Override
            public void initChannel(SocketChannel ch) throws Exception {
                ChannelPipeline pipeline = ch.pipeline();
                InputStream keyIn = context.getResources().openRawResource(R.raw.mtrax);
                SocketContextBuilder builder = new SocketContextBuilder(keyIn, "changeit");

                handler = builder.getSslHandler(ch, host, port);

                // Add the text line codec.
                pipeline.addLast(new DelimiterBasedFrameDecoder(8192, Delimiters.lineDelimiter()));
                pipeline.addLast(new StringDecoder(UTF8));
                pipeline.addLast(new StringEncoder(UTF8));
                pipeline.addLast(handler);

                // and then business logic.
                pipeline.addLast(clientHandler);
            }
        };
    }` 

Are there wrong implemetations in our code? I have been try all the way to solved our problem, because the received messages look like certificate's content when we use SSL. Please to be kindly to help us.

**Comment by normanmaurer** [comment]
@kurniawanrizzki sorry but I not understand your problem... Can you give more details about what problem you see and what you thing should be done ?

**Comment by kurniawanrizzki** [comment]
I'm not sure if i already implement SSL well in android using netty, the content message that was sent to the server looks like certificate content. Could you please give us example how implement it in android? 
Currently we're using BKS's type certificate on android side, while on the server side, we're using JKS's type certificate. Thank you.

**Comment by kurniawanrizzki** [comment]
I already solved the issue, but the status said if it's NOT_HANDSHAKING (I used netty 4.1.9). 
In other side i try to use the latest one (4.1.18), but it's said if the handshake was failed, could you please to help us how to solved it? or is it okay when i use 4.1.9? Thank you. 

Android : 5.0

`12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err: io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Handshake failed
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at java.lang.Thread.run(Thread.java:818)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err: Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:436)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:1006)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:292)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1248)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1159)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1194)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err:     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err: 	... 16 more
12-15 16:10:33.465 1580-4979/com.firstwap.mobiletrax W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0xf00ec200: Failure in SSL library, usually a protocol error
12-15 16:10:33.466 1580-4979/com.firstwap.mobiletrax W/System.err: error:1408E0F4:SSL routines:SSL3_GET_MESSAGE:unexpected message (external/openssl/ssl/s3_both.c:498 0xebae2ce0:0x00000000)
12-15 16:10:33.466 1580-4979/com.firstwap.mobiletrax W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake_bio(Native Method)
12-15 16:10:33.466 1580-4979/com.firstwap.mobiletrax W/System.err:     at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:423)
12-15 16:10:33.466 1580-4979/com.firstwap.mobiletrax W/System.err: 	... 23 more`

**Comment by kurniawanrizzki** [comment]
sorry it has been solved, i just missed with the information. Thank You.

**Comment by normanmaurer** [comment]
@kurniawanrizzki how you solved it ?
