### ISSUE TITLE
Channel pool enforces downstream ops in I/O thread

### ISSUE THREAD

**Issue by rvansa** [netty/netty#7452]
### Expected behavior

When a channel pool contains active channel, listener registered through `channelPool.acquire().addListener(...)` should be called in caller thread (as I am using the channel pool on client, the client would like to start with a write).

### Actual behavior

`SimpleChannelPool.doHealthCheck` which in turn invokes the listener is always called in event loop thread. The default health check calls only `channel.isActive()` and does not invoke any upstream events (afaik).

### Netty version

4.1.9

**Comment by normanmaurer** [comment]
@rvansa I just checked and its by design. We do it to ensure there is no need for any synchronisation needed.

**Comment by rvansa** [comment]
@normanmaurer While debugging I've found out that writes from other threads end up executing a `AbstractChannelHandlerContext.WriteAndFlushTask` in the event loop anyway, so my pool implementation is not effective :-/
Maybe what I am doing is a premature optimization, but in my view the synchronization point should be at the pool, nowhere else.
