### ISSUE TITLE
Javadoc for checkPositive method in io.netty.util.internal.ObjectUtil is not correct

### ISSUE THREAD

**Issue by zhanglong318** [netty/netty#7455]
The javadoc for checkPositive method in io.netty.util.internal.ObjectUtil is not correct, and indeed the description is reversal. The javadoc for checkPositive method says: "Checks that the given argument is strictly positive. If it is, throws {@link IllegalArgumentException}. Otherwise, returns the argument."

 The correct description should be like this: "Checks that the given argument is strictly positive. If it is *not*, throws {@link IllegalArgumentException}. Otherwise, returns the argument." 

 Netty of version 4.1.15.Final and 4.1.16.Final are affected, maybe other versions can be affected, but I don't check.

**Comment by normanmaurer** [comment]
@zhanglong318 thanks will fix... Or if you like you can also submit a PR and get the glory ;)

**Comment by zhanglong318** [comment]
@normanmaurer ok, I will submit a PR later, thanks for your so quick response :-)

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7481
