### ISSUE TITLE
Feature request - support for npipe:// protocol on Windows 

### ISSUE THREAD

**Issue by borlander** [netty/netty#7456]
It would be nice if Netty had a native support for npipe:// protocol similar to existing support for unix sockets

Currently there is at least one major producer of npipe:// pipes, namely the native docker on windows, see e.g discussion at https://youtrack.jetbrains.com/issue/IDEA-158826

**Comment by normanmaurer** [comment]
@borlander We always open for contributions. That said even if someone would contribute it I am not sure we could maintain it as the core-developers of netty not have much windows experience when it comes to native code :(

**Comment by Scottmitch** [comment]
agreed we would need a contributor savvy on windows who is willing to develop/maintain it.

**Comment by Scottmitch** [comment]
@gesellix - we still don't have a JNI based transport target at windows, so I'm guessing there would be (a lot?) more todo here.

**Comment by gesellix** [comment]
@Scottmitch ah, I thought there's already unix socket support in Netty, but I guess I'm wrong?

**Comment by normanmaurer** [comment]
@gesellix there is unix domain socket support for linux and macOS.

**Comment by Scottmitch** [comment]
> there is unix domain socket support for linux and macOS.

Which is unfortunately coupled to a whole bunch of other unix stuff, and also each JNI transport is tied to its respective OS flavor.

**Comment by normanmaurer** [comment]
Let me close this for now as I think we are not planing to support this in the future.
