### ISSUE TITLE
transport-native-epoll cross compiling for aarch64

### ISSUE THREAD

**Issue by jaingaurav27** [netty/netty#7459]
### JVM version (e.g. `java -version`)
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

**Comment by normanmaurer** [comment]
@jaingaurav27 you will at least need to add some details... like what build error you see etc

**Comment by jaingaurav27** [comment]
mvn compile
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 4.10
[INFO] os.detected.version.major: 4
[INFO] os.detected.version.minor: 10
[INFO] os.detected.release: ubuntu
[INFO] os.detected.release.version: 16.04
[INFO] os.detected.release.like.ubuntu: true
[INFO] os.detected.release.like.debian: true
[INFO] os.detected.classifier: linux-x86_64
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Netty/Transport/Native/Epoll 4.1.18.Final-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ netty-transport-native-epoll ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-tools) @ netty-transport-native-epoll ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.12.1:check (check-style) @ netty-transport-native-epoll ---
[INFO] Starting audit...
Audit done.

[INFO] 
[INFO] --- xml-maven-plugin:1.0.1:check-format (check-style) @ netty-transport-native-epoll ---
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:get (get-jetty-alpn-agent) @ netty-transport-native-epoll ---
[INFO] Resolving org.mortbay.jetty.alpn:jetty-alpn-agent:jar:2.0.6 with transitive dependencies
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:parse-version (parse-version) @ netty-transport-native-epoll ---
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (ant-get-systeminfo) @ netty-transport-native-epoll ---
[WARNING] Parameter tasks is deprecated, use target instead
[INFO] Executing tasks

main:
[INFO] Executed tasks
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:regex-property (regex-glibc-sendmmsg) @ netty-transport-native-epoll ---
[INFO] No match to regex '^((?!^[^)]+\)\s+(0*2\.1[4-9]|0*2\.[2-9][0-9]+|0*[3-9][0-9]*|0*[1-9]+[0-9]+).*).)*$' found in 'ldd (Ubuntu GLIBC 2.23-0ubuntu9) 2.23'. The initial value 'ldd (Ubuntu GLIBC 2.23-0ubuntu9) 2.23' is left as-is...
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:regex-property (regex-linux-sendmmsg) @ netty-transport-native-epoll ---
[INFO] No match to regex '^((?!^[0-9]*[3-9]\.?.*).)*$' found in '4.10.0-28-generic'. The initial value '4.10.0-28-generic' is left as-is...
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (write-version-properties) @ netty-transport-native-epoll ---
[INFO] Executing tasks

main:
     [echo] Current commit: 09a05b6 on 2017-11-28 13:43:28 +0100
    [mkdir] Created dir: /home/gaurav/netty/transport-native-epoll/target/classes/META-INF
[propertyfile] Creating new property file: /home/gaurav/netty/transport-native-epoll/target/classes/META-INF/io.netty.versions.properties
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:unpack-dependencies (unpack) @ netty-transport-native-epoll ---
[INFO] Unpacking /home/gaurav/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.18.Final-SNAPSHOT/netty-transport-native-unix-common-4.1.18.Final-SNAPSHOT-linux-x86_64.jar to /home/gaurav/netty/transport-native-epoll/target/unix-common-lib with includes "META-INF/native/**" and excludes ""
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:regex-property (regex-combined-sendmmsg) @ netty-transport-native-epoll ---
[INFO] No match to regex '.*IO_NETTY_SENDMSSG_NOT_FOUND.*' found in '4.10.0-28-genericldd (Ubuntu GLIBC 2.23-0ubuntu9) 2.23'. The initial value '4.10.0-28-genericldd (Ubuntu GLIBC 2.23-0ubuntu9) 2.23' is left as-is...
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:regex-property (regex-unset-if-needed-sendmmsg) @ netty-transport-native-epoll ---
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ netty-transport-native-epoll ---
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ netty-transport-native-epoll ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/gaurav/netty/transport-native-epoll/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ netty-transport-native-epoll ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 28 source files to /home/gaurav/netty/transport-native-epoll/target/classes
[WARNING] /home/gaurav/netty/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java:[864,54] [deprecation] Handle in RecvByteBufAllocator has been deprecated
[WARNING] /home/gaurav/netty/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java:[866,81] [deprecation] Handle in RecvByteBufAllocator has been deprecated
[WARNING] /home/gaurav/netty/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java:[901,52] [deprecation] Handle in RecvByteBufAllocator has been deprecated
[WARNING] /home/gaurav/netty/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java:[1005,52] [deprecation] Handle in RecvByteBufAllocator has been deprecated
[INFO] 
[INFO] --- maven-hawtjni-plugin:1.14:generate (build-native-lib) @ netty-transport-native-epoll ---
[INFO] executing: /bin/sh -c ./autogen.sh
[INFO] 
[INFO] --- maven-hawtjni-plugin:1.14:build (build-native-lib) @ netty-transport-native-epoll ---
[INFO] executing: /bin/sh -c ./configure --disable-ccache --prefix=/home/gaurav/netty/transport-native-epoll/target/native-build/target 'LDFLAGS=-L/home/gaurav/netty/transport-native-epoll/target/unix-common-lib/META-INF/native/lib -Wl,--no-as-needed -lrt -Wl,--whole-archive -lnetty-unix-common -Wl,--no-whole-archive' 'CFLAGS=-O3 -Werror -fno-omit-frame-pointer -Wunused-variable -I/home/gaurav/netty/transport-native-epoll/target/unix-common-lib/META-INF/native/include'
[INFO] configure: WARNING: unrecognized options: --disable-ccache
[INFO] checking build system type... x86_64-pc-linux-gnu
[INFO] checking host system type... x86_64-pc-linux-gnu
[INFO] checking target system type... x86_64-pc-linux-gnu
[INFO] checking for gcc... aarch64-linux-gnu-gcc
[INFO] checking whether the C compiler works... yes
[INFO] checking for C compiler default output file name... a.out
[INFO] checking for suffix of executables... 
[INFO] configure: error: in `/home/gaurav/netty/transport-native-epoll/target/native-build':
[INFO] configure: error: cannot run C compiled programs.
[INFO] If you meant to cross compile, use `--host'.
[INFO] See `config.log' for more details
[INFO] checking whether we are cross compiling... 
[INFO] rc: 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.071 s
[INFO] Finished at: 2017-12-01T14:37:02+05:30
[INFO] Final Memory: 22M/55M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.14:build (build-native-lib) on project netty-transport-native-epoll: build failed: org.apache.maven.plugin.MojoExecutionException: ./configure failed with exit code: 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by jaingaurav27** [comment]
using comand ./configure --host=aarch64-linux-gnu
i am able to build .so, but i want to build it using mvn compile. 
can you please suggest where in pom.xml, i can specify host ?
