### ISSUE TITLE
qps is unstable

### ISSUE THREAD

**Issue by andyyin** [netty/netty#7472]
### Expected behavior

if has code  { System.out.print(" ");}，qps is 4-5w，stable and very high

if put off code  { System.out.print(" ");}  qps is unstable, very low。

 why? (the similar code netty 3 no this problem)
(server just read message)
### Minimal yet complete reproducer code (or URL to code)

    private static final String message = RandomStringUtils.randomAlphanumeric(1000) + "\r\n";
    public static void main(String[] args) {
        EventLoopGroup group = new NioEventLoopGroup(1 * 2);
        try {
            Bootstrap bootstrap = new Bootstrap();

            bootstrap.channel(NioSocketChannel.class).group(group)
                    .option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
                    .option(ChannelOption.TCP_NODELAY, Boolean.TRUE)
                    .option(ChannelOption.SO_SNDBUF, 100000)
                    .option(ChannelOption.WRITE_BUFFER_HIGH_WATER_MARK, 100000000)
                    .handler(new ChannelInitializer<Channel>() {

                        @Override
                        protected void initChannel(Channel ch) throws Exception {
                            ChannelPipeline pipeline = ch.pipeline();
                            pipeline.addLast("framer", new DelimiterBasedFrameDecoder(8192,
                                    Delimiters.lineDelimiter()));

                            pipeline.addLast("decoder", new StringDecoder());
                            pipeline.addLast("encoder", new StringEncoder());
                            pipeline.addLast("clientHandler", new ClientHandler());
                        }
                    });

            ChannelFuture f = bootstrap.connect(new InetSocketAddress("127.0.0.1", 8888));
            
            final Channel channel = f.channel();
            while (!Thread.currentThread().isInterrupted()) {
                System.out.print(" ");
                if (channel.isWritable()) {
                    ChannelFuture future = channel.writeAndFlush(message);
                }
            }

            f.channel().closeFuture().sync();
        } catch (Exception e) {

        } finally {
            group.shutdownGracefully();
        }
### Netty version
4.0.24.Final
### JVM version (e.g. `java -version`)
jdk7
### OS version (e.g. `uname -a`)
mac

**Comment by whoisyao** [comment]
@andyyin is this issue resolved?
