### ISSUE TITLE
sslhandler 报异常java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by xiaofenyang** [netty/netty#7473]
### os: Darwin xiaofenmac.local 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64

网上有类似的https://github.com/netty/netty/issues/2098 问题，但是升级版本没啥用，现在不知道怎么解决

**Comment by normanmaurer** [comment]
Please open a new issue in English
