### ISSUE TITLE
netty should strip the http2-setting header

### ISSUE THREAD

**Issue by mosesn** [netty/netty#7477]
### Expected behavior
HTTP2-Settings is a magic header that embeds the http/2 settings in the h2c upgrade request.  After it's read by the upgrade handler in netty, it should be removed.

### Actual behavior
Instead it's turned into a header in the http/2 headers, and gets propagated to the application, which can make implementing an h2c proxy complicated.

### Steps to reproduce
Make an h2c proxy in netty, or examine an h2c upgrade request after it's converted to an http/2 request in Http2MultiplexCodec.

### Netty version
4.1.16.Final

### JVM version (e.g. `java -version`)
jdk8

### OS version (e.g. `uname -a`)
osx, linux

**Comment by normanmaurer** [comment]
@ejona86 @carl-mastrangelo @Scottmitch WDYT ?

**Comment by carl-mastrangelo** [comment]
@mossen I haven't heard of that header before, is it in an RFC ?

**Comment by ejona86** [comment]
@carl-mastrangelo, it's in the HTTP/2 RFC. See §3.2.1.

I thought we already strip hop-to-hop headers.
> Since the upgrade is only intended to apply to the immediate connection, a client sending the HTTP2-Settings header field MUST also send HTTP2-Settings as a connection option in the Connection header field to prevent it from being forwarded

**Comment by mosesn** [comment]
@ejona86 that's a good point, maybe the issue is that it's not in the `connection` header?  I'll do some digging.

**Comment by mosesn** [comment]
OK, I think I found the issue.  Before https://github.com/netty/netty/commit/d976dc108d587e84c6ffb4dfdb3a9704442db29f#diff-c7163d5a69a787c44984f0d7f8913e5e we were stripping the `connection` header, but we weren't removing the things it pointed to.  I'm still on the version that doesn't have the fix, so we don't see the `connection` header, and HTTP2-Settings is also not stripped.  This should be fixed after I upgrade to the latest version.  Sorry for the noise!

**Comment by mossen** [comment]
@carl-mastrangelo Thanks to pull me in by your mentioning 👍

**Comment by normanmaurer** [comment]
Thanks for closing the loop
