### ISSUE TITLE
SingleThreadEventExecutor ignores startThread failures

### ISSUE THREAD

**Issue by rvansa** [netty/netty#7483]
### Expected behavior
SingleThreadEventExecutor should throw an exception when it can't start the thread second time.

### Actual behavior
When `doStartThread` throws an exception, e.g. due to the actual executor being depleted of threads and throwing in its rejected execution handler, the STEE ends up in started state anyway. If we try to execute another task in this executor, it will be queued but the thread won't be started anymore and the task will linger forever.

### Netty version
4.1.9

### JVM version (e.g. `java -version`)
1.8

**Comment by normanmaurer** [comment]
@rvansa looking now

**Comment by normanmaurer** [comment]
@rvansa PTAL  #7492

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7492
