### ISSUE TITLE
Ability to define Head+Tail ChannelHandler

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#7484]
I'm working on a new Channel type that extends AbstractChannel and is in some ways a hybrid version of a LocalChannel or EmbeddedChannel. Its purpose is to act as a proxy between two other Channels (say EpollChannel or NioChannel) and also provide a disposable section of a ChannelPipeline with a proper EventLoop.

This is pretty straight forward and just requires handlers that scoop up the various events at the ends of the pipeline and to some extent it'd be the Channel itself (more on that later).

The problem is that there's no elegant way of ensuring the position of a handler and `addLast(...)` is in particular a pain in the neck as it's the goto method for users to manipulate the pipeline. Kind of defeating the purpose of trying to give users (of our Netty based software) a section of pipeline they can safely manipulate without breaking everything to the left (head) or right (tail) of it.

Technically I wouldn't want to introduce any new API as it's all there. It just needs to be a bit more extensible.

Idea 1: Change `AbstractChannel` to depend on `ChannelPipeline` instead of `DefaultChannelPipeline` (ditto `Unsafe` instead of `AbstractUnsafe`). This would allow me to use delegation/composition and override `addFirst/Last(...)` and ensure that users can't add their handlers before/after the required head/tail handlers. Not my favorite (final and concrete classes are IMHO overused in Netty ;)).

Idea 2: Change `DefaultChannelPipeline` and add a bunch of protected methods alongside `onUnhandledInboundMessage(...)` for all the other events that are currently being swallowed (say `channelReadComplete(...)` on the `TailContext` that I'd like to translate into a `flush()`, or `channelWritabilityChanged(...)` for managing back pressure).

Idea 3: Let ChannelPipeline fire a "pipeline modified event" every time a handler gets added or removed. My head and tail handlers could simply look for it in the `userEventTriggered(...)` method and move themselves if they're not head or tail. 

I think number 2 is my favorite as it's most aligned with the intent to scoop up the events that reach the ends of the pipeline. If I could I'd also break up AbstractChannel's dependency on concrete classes from number one but that is not needed in this context. Number 3 I'm not sure about. It's simple but has problems. For one I can create a loop if there are two competing handlers and I wouldn't want to introduce this new event for every Netty user out there if none of them cares about it.

**Comment by normanmaurer** [comment]
2) sounds ok to me... @Scottmitch @carl-mastrangelo @trustin WDYT ?

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7494
