### ISSUE TITLE
Allow to use SOCKS5 proxy with DnsNameResolver

### ISSUE THREAD

**Issue by amal** [netty/netty#7486]
### Expected behavior
Possibility, to specify the `Socks5ProxyHandler` for `DnsNameResolver`.
The best variant would be to allow dynamically customize pipeline for each request. This way we'll get an option to use the different proxy settings for each HTTP request. For example, [AsyncHttpClient](https://github.com/AsyncHttpClient/async-http-client) library can use such functionality.

### Actual behavior
Currently, `DnsNameResolver` will use local network to resolve domain name address even if I use the SOCKS5 proxy for the request (it's already in pipeline). In my case domain is blocked by my internet provider, so domain resolving leads me to the stub server with just notification about blocking.

**Comment by bk1te** [comment]
For now there is no dns over tcp, so this possibly could work over socks5udp if this is what you like.

**Comment by amal** [comment]
Yeah, I'm talking about socks5udp.
So for this functionality, something like new `Socks5UdpProxyHandler` class should be written at first, yes?

**Comment by normanmaurer** [comment]
Sorry I still dont get it... Please provide a PR with the changes you would like to see and we can continue discuss there.

**Comment by 2259289435** [comment]
> Yeah, I'm talking about socks5udp. So for this functionality, something like new `Socks5UdpProxyHandler` class should be written at first, yes?
> 
> Also, there is a "[DNS over HTTPS](https://developers.google.com/speed/public-dns/docs/dns-over-https)" from Google. It can resolve domain name via both TCP SOCKS4 or SOCKS5.

Is the problem solved? I also had the same problem！

**Comment by baiyangzhuhong** [comment]
> > Yeah, I'm talking about socks5udp. So for this functionality, something like new `Socks5UdpProxyHandler` class should be written at first, yes?
> > Also, there is a "[DNS over HTTPS](https://developers.google.com/speed/public-dns/docs/dns-over-https)" from Google. It can resolve domain name via both TCP SOCKS4 or SOCKS5.
> 
> Is the problem solved? I also had the same problem！

see https://github.com/netty/netty/issues/7487

Bootstrap bootstrap = new Bootstrap();
bootstrap.resolver(NoopAddressResolverGroup.INSTANCE);

this helps me
