### ISSUE TITLE
Is there an easy way to connect two embedded channels?

### ISSUE THREAD

**Issue by konsultaner** [netty/netty#7488]
In my project I provide a server an multiple clients. I have a scenario where I would like to connect the server to the client without any network traffic, so just by using the ChannelHandlers. I thought maybe the EmbeddedChannel could do that for me? Is there a good way to do that?

At the moment I help myself with a very hacky extention of the AbstractChannel and the AbstractChannelHandlerContext.

**Comment by normanmaurer** [comment]
@konsultaner I think the `LocalChannel` / `LocalServerChannel` is what you are looking for ?

**Comment by konsultaner** [comment]
@normanmaurer awesome, thank you!

**Comment by konsultaner** [comment]
@normanmaurer Could you imagine a scenario where an incomming message from a server is directly responded from the client but then never read by the server. I came up with the localChannel having an issue where exactly that happend. I worked with the loopback address. Wireshark showed me that the message would leave the client, that was actually sharing the same EventLoopGroup. The server never read the channel. The NioSocketChannel.doReadBytes was never called. 

I haven't tested it in depth now, but using the LocalChannel seem to showed the same Problem now.
