### ISSUE TITLE
libnetty_transport_native_epoll_x86_64.so

### ISSUE THREAD

**Issue by zhengbin1015** [netty/netty#7495]
4.1.18 use 4.1.17's libnetty_transport_native_epoll_x86_64.so?
The netty-all-4.1.18.Final.jar with out transport-native-epoll

**Comment by normanmaurer** [comment]
Sorry but what’s the question?

**Comment by zhengbin1015** [comment]
There is no transport-native-epoll in netty-all-4.1.18.Final.jar packaging. There are some of the previous versions. Do you need to wrap transport-native-epoll in netty-all-4.1.17 into netty-all-4.1.18.Final.jar?

**Comment by normanmaurer** [comment]
@zhengbin1015 hmmm are you sure ? I just downloaded the jar and unpacked it and it seems to be all there:

http://repo1.maven.org/maven2/io/netty/netty-all/4.1.18.Final/netty-all-4.1.18.Final.jar

Where did you download it from ?

**Comment by zhengbin1015** [comment]
http://netty.io/downloads.html
http://dl.bintray.com/netty/downloads/netty-4.1.18.Final.tar.bz2

**Comment by normanmaurer** [comment]
Thanks... Just uploaded a new tar that fixes it.
