### ISSUE TITLE
FixedChannelPool  or  SimpleChannelPool can add a Method  to clean channel ?

### ISSUE THREAD

**Issue by seiferff** [netty/netty#7497]
### Expected behavior
I use FixedChannelPool    to create a  channel pool,

When using  IdleStateHandler  find channel ( which is in channel pool ) is Idle . 

But close channel  is not very well  in channelHandler   when channel is IdleState 

Bad things such as  
step1   close channel  in handle thread   becase channel is IdleState  ,
setp2  bussness thread acquire the  closed handle using FixedChannelPool .acquire()

So I think It is better to  clean channel In ChannelPool 。It is  safe  

Who can help answer it?

tks .  Many thanks

### Netty version
Netty 4.1.9

**Comment by normanmaurer** [comment]
@seiferff sorry but I not fully understand what you suggest or asking for. Can you give some more detailed example ?

**Comment by seiferff** [comment]
@normanmaurer  Sorry for my poor Englisg

In my code

1、In My Client  ChannelInitializer<SocketChannel>    

    protected void initChannel(SocketChannel ch) throws Exception {
        log.debug("initChannel {}",ch);
        ChannelPipeline p = ch.pipeline();
        p.addLast(new ReadTimeoutHandler(60));    //this handler will close a ctx in 60s while it is idle
        p.addLast(new JsonRpcReplyDeCoder(msgMap,maxReplyLen));
        p.addLast(new JsonRpcReqEnCoder());
        
    }

2、In other Thread I uee fixedChannelPool to acquire channel

                    Future<Channel> channelFuture = fixedChannelPool.acquire();
                    Channel  channel = channelFuture.get();
                    channel.write(pkg)
                    //some code to wait from pkg reply 


3、Two  kinds of Bad thing 
      3.1、 my pkg can be send to server , and  ReadTimeoutHandler  close the channel.  I can not recevie 
            reply

      3.2、my pkg can not send pkg becase ReadTimeoutHandler   close the channel.

4 、I  suggest  :  I can Extends IdleStateHandler   , When chanel is idle , I can use FixedChannelPool  to close channel 。 So the two bad things will not be happened .

tks again.

**Comment by normanmaurer** [comment]
@seiferff why not just use a `FutureListener` that you attach to the Future returned by `release(...)` and remove the handler by yourself there ?

**Comment by seiferff** [comment]
@normanmaurer  can you show more code for example ?  I can not understand .

**Comment by normanmaurer** [comment]
```java
                Future<Void>future = fixedChannelPool.release(channel);
                future.addListener( f -> {
                   channel.pipeline().remove(handler):
               });

```

**Comment by Nick-The-Uncharted** [comment]
@normanmaurer I think @seiferff is trying to say that if we just close channel when channel being idle, it is possible that this channel is already acqured from channelPool and used by our bussniess-logic thread, and then the bussniess-logic will get a ClosedChannelException. So its best to let ChannelPool to provide a method which close the channel if it is not already acquired.
