### ISSUE TITLE
Latest Netty still doesn't have Automatic-Module-Name property within MANIFEST.MF for native transports

### ISSUE THREAD

**Issue by doom369** [netty/netty#7501]
```
jar --file=netty-transport-native-epoll-4.1.18.Final-linux-x86_64.jar --describe-module
Unable to derive module descriptor for: netty-transport-native-epoll-4.1.18.Final-linux-x86_64.jar
netty.transport.native.epoll: Invalid module name: 'native' is not a Java identifier
```

Look like plugins that build native modules override/erase `Automatic-Module-Name` property specified in `pom.xml` of `transport-native-*` modules.

All other modules are fine. Problem is just with native modules: epoll, kqueue.

I'll try to look what exactly plugin does that when I have free time.

Part of https://github.com/netty/netty/pull/7245

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7502 .. @doom369 thanks
