### ISSUE TITLE
JNI function calls and exception handling

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#7508]
We should investigate how we handle any exceptions that may be thrown from JNI function calls [1]. For example if we call a JNI method, and it puts an exception on the stack, we may not want to make subsequent system calls with data obtained from JNI because it maybe undefined.

[1] https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/functions.html#exceptions

Originally discussed here: https://github.com/netty/netty/pull/7507#discussion_r157093433

**Comment by normanmaurer** [comment]
I will check out code base.

**Comment by normanmaurer** [comment]
@Scottmitch checked and we are good... This is only needed when you call java methods from JNI which we only do for accessing the limit and position of ByteBuffer (and only if we can not access the fields directly). These will never throw and so we are safe.
