### ISSUE TITLE
HTTP/2 UniformStreamByteDistributor has an infinite loop problem when transferring content that exceeds 2 GB.

### ISSUE THREAD

**Issue by durigon** [netty/netty#7509]
### Expected behavior
no infinite loop 

### Actual behavior
HTTP/2 UniformStreamByteDistributor has an infinite loop problem when transferring content that exceeds 2GB.

- [Http2CodecUtil streamableBytes - If pendingBytes is out of the integer range, streamableBytes may be zero.](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2CodecUtil.java#L226)
- [Since there is a frame and windowSize is greater than 0, writing 0 bytes is infinitely repeated.](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/UniformStreamByteDistributor.java#L170)
- [UniformStreamByteDistributor  StreamState.streamableBytes](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/UniformStreamByteDistributor.java#L118)

- Workaround : Add flow controller so that HTTP/2 stream pending bytes do not exceed the integer(pendingBytes, streamableBytes).

### Steps to reproduce
Use curl with limit-rate to request more than 2Gbytes of content In multiple terminal(More than 6 terminals)
`curl -v https://localhost/3gbytes.bin -o/dev/null --http2 --insecure --limit-rate 1M `

### Netty version
netty-4.1.12.Final

### JVM version (e.g. `java -version`)
#java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)

### OS version (e.g. `uname -a`)
uname -a
Linux sunggonsong 2.6.32-696.13.2.el6.x86_64 #1 SMP Thu Oct 5 21:22:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linu

**Comment by normanmaurer** [comment]
@durigon just to ensure did you try 4.1.18.Final as well ?

**Comment by durigon** [comment]
#4283 and #4585 are still in process, so it seems that it has not been fixed.

**Comment by Scottmitch** [comment]
I think this will be resolved once https://github.com/netty/netty/issues/4283 is resolved.

**Comment by Scottmitch** [comment]
@durigon - Can you run your tests with https://github.com/netty/netty/pull/7523 ?

**Comment by durigon** [comment]
@Scottmitch Thank you. I'll test it and share the results.

**Comment by durigon** [comment]
@Scottmitch As expected, there is no infinite loop.

**Comment by Scottmitch** [comment]
thanks for reporting and verifying @durigon!

**Comment by Scottmitch** [comment]
Fixed by #7523
