### ISSUE TITLE
double counting header name length in http/2

### ISSUE THREAD

**Issue by mosesn** [netty/netty#7511]
### Expected behavior

A header with a name of length X and a value of length Y gets considered as being length X + Y in total.

### Actual behavior

A header with a name of length X and a value of length Y gets considered as being length 2X + Y in total.  I think this is where the bug is:

https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/HpackDecoder.java#L262

### Steps to reproduce

Use hpack decoder to decode a header.

### Netty version

4.1.16.Final

### JVM version (e.g. `java -version`)

jdk8

**Comment by normanmaurer** [comment]
@mosesn can you open a PR with a unit test ?

**Comment by mosesn** [comment]
@normanmaurer yeah, I'll take a look.

**Comment by normanmaurer** [comment]
@mosesn thanks buddy

**Comment by mosesn** [comment]
I still haven't been able to make a unit test, but I have a better idea of what's happening.

After we have already added the name length and value length  of the header with the long name length to the headersLength, we can go into "Literal Header Field with Incremental Indexing" mode, and then we go to READ_LITERAL_HEADER_VALUE_LENGTH_PREFIX , and if index is not 127 or 0, we go into into the same area as before, because `nameLength` hasn't changed yet.
