### ISSUE TITLE
Can not find  class   io.netty.util.collection.LongObjectHashMap   in   4.1.8.final   

### ISSUE THREAD

**Issue by zhisheng17** [netty/netty#7518]
### In the  version   4.1.8.final    

module   codec-redis   

class     FixedRedisMessagePool

already  import  the  follow  class   

```
import io.netty.util.collection.LongObjectHashMap;
import io.netty.util.collection.LongObjectMap;
```

it  Prompt error message is as follows ：Unused import statemen

![_15135786085710](https://user-images.githubusercontent.com/10086212/34092800-383114a0-e400-11e7-874a-d452f635921e.png)

but  I   can  not find  the class  in  the whole  project.

### In  the   4.1.6  final  and   4.1.7  final  version

I  find  these  classes   in  the   `io.netty.util.collection`    package

![tim 20171218143611](https://user-images.githubusercontent.com/10086212/34092978-efd77b4e-e400-11e7-9c38-064c89b5f056.png)

### In  the   4.1.8  final  version

the  whole  project  is  changed.   I   find    the  `io.netty.util`   package  is   in   `common`       module，

But   I   can not  find  in  `io.netty.util.collection`   package ，in   the  whole  project  ,   it   also  didn't  find  it  .

I   thought  it  may  forget  to  copy  the    `io.netty.util.collection`   package  in  the module  `common` .

only  my   thougnt,   help  me  @sprsquish @adamv @mheath @ngocdaothanh    ,   thank  you   

In addition， I    am   from   China,     bad   English  ,  Please wait

**Comment by normanmaurer** [comment]
@zhisheng17 its generated during build. run `mvn clean compile` in the `common` module.

**Comment by zhisheng17** [comment]
thanks！

**Comment by Quantriple** [comment]
朋友 mvn clean我使用了  还是没用  求教

**Comment by johnou** [comment]
@Quantriple did you call `compile` as well?

**Comment by Quantriple** [comment]
@johnou   thx  mvn clean  then install          perfect

**Comment by YangZhuoNJ** [comment]
@Quantriple  like with you , but i find the way : using high version maven , i change my idea maven setting , using the 3.5.3 version , someone tell me , you can try it.  
 In addition， I am from China, bad English ......

**Comment by Quantriple** [comment]
@YangZhuoNJ   嗯   已经解决了  不过还是 谢谢你  都是国人 我就  不说 蹩脚的英文了

**Comment by DestinyWang** [comment]
```bash
cd common;
mvn clean compile;
```

Reason in the common module `common/src/main/templates/io/netty/util/collection` directory. 

The `.template` file.

**Comment by InuYasha000** [comment]
在我这为什么不生效， Failure to find io.netty:netty-dev-tools:jar:4.1.26.Final-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository，这个错有人遇到过没

**Comment by InuYasha000** [comment]
早上试了一个小时了，这个答案对我没用，要么报错Failure to find io.netty:netty-dev-tools:jar:4.1.26.Final-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository，要么不报错，但是问题也不解决，就是这么神奇。
