### ISSUE TITLE
Telnet to server without protocol version doesn't work

### ISSUE THREAD

**Issue by manish-panwar** [netty/netty#7526]
We use Vertx as HTTP listener on port 80. Vertx internally uses Netty to listen on a socket. When we telnet without protocol version, connection is getting closed immediately. See below debug logs. Everything works fine if we pass the protocol version(e.g. HTTP/1.1)

**Telnet command:**

> telnet 112.21.70.119 80
> Trying 112.21.70.119...
> Connected to 112.21.70.119.
> Escape character is '^]'.
> GET /
> Connection closed by foreign host.

**Netty debug logs:**

> 2017-12-19 13:31:24.450 DEBUG (vert.x-eventloop-thread-1) [i.n.h.l.LoggingHandler] - [id: 0x739e7b9d, L:/112.21.70.119:80 - R:/172.16.8.166:58174] READ: 7B
>          +-------------------------------------------------+
>          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
> +--------+-------------------------------------------------+----------------+
> |00000000| 47 45 54 20 2f 0d 0a                            |GET /..         |
> +--------+-------------------------------------------------+----------------+
> 2017-12-19 13:31:24.450 DEBUG (vert.x-eventloop-thread-1) [i.n.h.l.LoggingHandler] - [id: 0x739e7b9d, L:/112.21.70.119:80 - R:/12.61.8.116:58174] CLOSE
> 2017-12-19 13:31:24.450 DEBUG (vert.x-eventloop-thread-1) [i.n.h.l.LoggingHandler] - [id: 0x739e7b9d, L:/112.21.70.119:80 ! R:/12.61.8.116:58174] READ COMPLETE
> 2017-12-19 13:31:24.450 DEBUG (vert.x-eventloop-thread-1) [i.n.h.l.LoggingHandler] - [id: 0x739e7b9d, L:/112.21.70.119:80 ! R:/12.61.8.116:58174] INACTIVE
> 2017-12-19 13:31:24.450 DEBUG (vert.x-eventloop-thread-1) [i.n.h.l.LoggingHandler] - [id: 0x739e7b9d, L:/112.21.70.119:80 ! R:/12.61.8.116:58174] UNREGISTERED

 

### Expected behavior
Server should return 200 response.

### Actual behavior
Connection is getting closed

### Steps to reproduce

> telnet 1.2.3.4 80
> GET /

### Netty version 

4.0.47.Final

### JVM version (e.g. `java -version`)

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

### OS version (e.g. `uname -a`)

16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Given below are the logs from successful invocation when we pass the protocol version.**

**Telnet Command:**

> telnet 112.21.70.119 80
> Trying 112.21.70.119... 
> Connected to 112.21.70.119. 
> Escape character is '^]'. 
> GET / HTTP/1.1 
> HTTP/1.1 200 OK 
> Content-Type: text/html 
> Transfer-Encoding: chunked

**Netty Debug logs:**

> 2017-12-19 13:30:52.755 DEBUG (vert.x-eventloop-thread-3) [i.n.h.l.LoggingHandler] - [id: 0x4323a474, L:/112.21.70.119:80 - R:/12.61.8.116:58167] READ: 16B
>          +-------------------------------------------------+
>          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
> +--------+-------------------------------------------------+----------------+
> |00000000| 47 45 54 20 2f 20 48 54 54 50 2f 31 2e 31 0d 0a |GET / HTTP/1.1..|
> +--------+-------------------------------------------------+----------------+
> 2017-12-19 13:30:52.755 DEBUG (vert.x-eventloop-thread-3) [i.n.h.l.LoggingHandler] - [id: 0x4323a474, L:/112.21.70.119:80 - R:/12.61.8.116:58167] READ COMPLETE
> 2017-12-19 13:30:59.716 DEBUG (vert.x-eventloop-thread-3) [i.n.h.l.LoggingHandler] - [id: 0x4323a474, L:/112.21.70.119:80 - R:/12.61.8.116:58167] READ: 18B
>          +-------------------------------------------------+
>          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
> +--------+-------------------------------------------------+----------------+
> |00000000| 43 6f 6e 6e 65 63 74 69 6f 6e 3a 63 6c 6f 73 65 |Connection:close|
> |00000010| 0d 0a                                           |..              |
> +--------+-------------------------------------------------+----------------+
> 2017-12-19 13:30:59.716 DEBUG (vert.x-eventloop-thread-3) [i.n.h.l.LoggingHandler] - [id: 0x4323a474, L:/112.21.70.119:80 - R:/12.61.8.116:58167] READ COMPLETE
> 2017-12-19 13:31:00.419 DEBUG (vert.x-eventloop-thread-3) [i.n.h.l.LoggingHandler] - [id: 0x4323a474, L:/112.21.70.119:80 - R:/12.61.8.116:58167] READ: 2B
>          +-------------------------------------------------+
>          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
> +--------+-------------------------------------------------+----------------+
> |00000000| 0d 0a                                           |..              |
> +--------+-------------------------------------------------+----------------+
> 2017-12-19 13:31:00.419 DEBUG (vert.x-eventloop-thread-3) [c.a.s.h.Diagnostic] - Rendering info.
> 2017-12-19 13:31:00.419 DEBUG (vert.x-eventloop-thread-3) [i.n.h.l.LoggingHandler] - [id: 0x4323a474, L:/112.21.70.119:80 - R:/12.61.8.116:58167] READ COMPLETE
> 2017-12-19 13:31:00.419 DEBUG (vert.x-eventloop-thread-3) [i.n.h.l.LoggingHandler] - [id: 0x4323a474, L:/112.21.70.119:80 - R:/12.61.8.116:58167] WRITE: 91B
>          +-------------------------------------------------+
>          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
> +--------+-------------------------------------------------+----------------+
> |00000000| 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d |HTTP/1.1 200 OK.|
> |00000010| 0a 43 6f 6e 74 65 6e 74 2d 54 79 70 65 3a 20 74 |.Content-Type: t|
> |00000020| 65 78 74 2f 68 74 6d 6c 0d 0a 43 6f 6e 6e 65 63 |ext/html..Connec|
> |00000030| 74 69 6f 6e 3a 20 63 6c 6f 73 65 0d 0a 54 72 61 |tion: close..Tra|
> |00000040| 6e 73 66 65 72 2d 45 6e 63 6f 64 69 6e 67 3a 20 |nsfer-Encoding: |
> |00000050| 63 68 75 6e 6b 65 64 0d 0a 0d 0a                |chunked....     |
> +--------+-------------------------------------------------+----------------+
> 2017-12-19 13:31:00.419 DEBUG (vert.x-eventloop-thread-3) [i.n.h.l.LoggingHandler] - [id: 0x4323a474, L:/112.21.70.119:80 - R:/12.61.8.116:58167] WRITE: 4B
>          +-------------------------------------------------+
>          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
> +--------+-------------------------------------------------+----------------+
> |00000000| 38 34 0d 0a                                     |84..            |
> +--------+-------------------------------------------------+----------------+
> 2017-12-19 13:31:00.419 DEBUG (vert.x-eventloop-thread-3) [i.n.h.l.LoggingHandler] - [id: 0x4323a474, L:/112.21.70.119:80 - R:/12.61.8.116:58167] WRITE: 132B
>          +-------------------------------------------------+
>          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
> +--------+-------------------------------------------------+----------------+
> |00000000| 4d 61 73 6b 65 64 20 49 50 20 3a 20 2a 2a 2a 2e |Masked IP : ***.|
> |00000010| 2a 2a 2a 2e 2a 2a 2a 2e 31 35 39 3c 62 72 3e 20 |***.***.159<br> |
> |00000020| 56 65 72 73 69 6f 6e 20 3a 20 6d 61 73 74 65 72 |Version : master|
> |00000030| 3c 62 72 3e 20 42 75 69 6c 64 20 4e 75 6d 62 65 |<br> Build Numbe|
> |00000040| 72 20 3a 20 4a 53 45 47 2d 53 45 47 2d 4a 4f 42 |r : J-Build-Prod|
> |00000050| 31 2d 31 39 34 32 3c 62 72 3e 20 42 75 69 6c 64 |1-1942<br> Build|
> |00000060| 20 44 61 74 65 20 3a 20 4d 6f 6e 20 44 65 63 20 | Date : Mon Dec |
> |00000070| 31 38 20 30 39 3a 30 30 3a 30 33 20 45 53 54 20 |18 09:00:03 EST |
> |00000080| 32 30 31 37                                     |2017            |
> +--------+-------------------------------------------------+----------------+
> 2017-12-19 13:31:00.419 DEBUG (vert.x-eventloop-thread-3) [i.n.h.l.LoggingHandler] - [id: 0x4323a474, L:/112.21.70.119:80 - R:/12.61.8.116:58167] WRITE: 2B
>          +-------------------------------------------------+
>          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
> +--------+-------------------------------------------------+----------------+
> |00000000| 0d 0a                                           |..              |
> +--------+-------------------------------------------------+----------------+
> 2017-12-19 13:31:00.419 DEBUG (vert.x-eventloop-thread-3) [i.n.h.l.LoggingHandler] - [id: 0x4323a474, L:/112.21.70.119:80 - R:/12.61.8.116:58167] WRITE: 0B
> 2017-12-19 13:31:00.419 DEBUG (vert.x-eventloop-thread-3) [i.n.h.l.LoggingHandler] - [id: 0x4323a474, L:/112.21.70.119:80 - R:/12.61.8.116:58167] FLUSH
> 2017-12-19 13:31:00.419 DEBUG (vert.x-eventloop-thread-3) [i.n.h.l.LoggingHandler] - [id: 0x4323a474, L:/112.21.70.119:80 - R:/12.61.8.116:58167] CLOSE
> 2017-12-19 13:31:00.419 DEBUG (vert.x-eventloop-thread-3) [i.n.h.l.LoggingHandler] - [id: 0x4323a474, L:/112.21.70.119:80 ! R:/12.61.8.116:58167] INACTIVE
> 2017-12-19 13:31:00.419 DEBUG (vert.x-eventloop-thread-3) [i.n.h.l.LoggingHandler] - [id: 0x4323a474, L:/112.21.70.119:80 ! R:/12.61.8.116:58167] UNREGISTERED

**Comment by normanmaurer** [comment]
@manish-panwar thats expected as netty itself does not support HTTP/0.9 . That said the closing itself is done by vert.x and not netty. They could also just respond with some HTTP error in this case. So please report in vert.x.

/cc @vietj

**Comment by vietj** [comment]
@normanmaurer is there a way to distinguish this specific decoder error ?

**Comment by normanmaurer** [comment]
@vietj would need to check in detail. If not I guess it would be easy to do so.

**Comment by manish-panwar** [comment]
@normanmaurer - If you can point me to class/method, I will be happy to do a PR.
