### ISSUE TITLE
Disabling Recycler causes increased GC pressure in new TLAB from MessageToMessageEncoder

### ISSUE THREAD

**Issue by johnou** [netty/netty#7528]
### Expected behavior

Less GC pressure coming from LengthFieldPrepender (extends MessageToMessageEncoder).

### Actual behavior

GC pressure coming from LengthFieldPrepender.

### Steps to reproduce

I will provide a reproducer soon(tm), just wanted to file this issue in the meantime.

### Netty version

4.1.19

### JVM version (e.g. `java -version`)

java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

### OS version (e.g. `uname -a`)

4.13.15-300.fc27.x86_64 #1 SMP Tue Nov 21 21:10:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by johnou** [comment]
![screenshot from 2017-12-19 15-59-21](https://user-images.githubusercontent.com/323497/34212448-91363060-e59c-11e7-9120-84275bc0311d.png)

**Comment by johnou** [comment]
@normanmaurer LengthFieldPrepender isn't final *pulls hair out*

**Comment by johnou** [comment]
https://gist.github.com/johnou/b15c98dc34090f445068a787f40d69e8

**Comment by johnou** [comment]
@normanmaurer ping

**Comment by johnou** [comment]
@normanmaurer shall we close this in favour of https://github.com/netty/netty/pull/7551? In the long run I think https://gist.github.com/johnou/b15c98dc34090f445068a787f40d69e8 would make more sense for LengthFieldPrepender but that might require waiting for the next major release.

**Comment by normanmaurer** [comment]
I think we can close this for now but yeah in the next major release we should address this in general
