### ISSUE TITLE
 DefaultChannelPromise.setSuccess(null) throw NPE  when I update netty-version from 4.0.36.Final to 4.1.16.Final

### ISSUE THREAD

**Issue by Lihuanghe** [netty/netty#7537]
### Actual behavior
 `futurn.setSuccess(null) throw NPE  when I update netty-version from 4.0.36.Final to 4.1.16.Final`
### Steps to reproduce
EveryTime when I call method doBusiness 
### Minimal yet complete reproducer code (or URL to code)
source like this:

```java
public ChannelPromise doBusiness(){
  // many other code
  //...
  //...
  
  DefaultChannelPromise futurn = new DefaultChannelPromise(null);
  futurn.setSuccess(null);  // netty-4.1.16-Final throw NPE
  return futurn;

}
```

### Netty version
4.1.16.Final
### JVM version (e.g. `java -version`)
sun-hotspot-jdk1.7
### OS version (e.g. `uname -a`)
centos6.5

**Comment by normanmaurer** [comment]
@Lihuanghe this is expected and it was in fact a bug that it did not before. That said I think we should throw directly when the constructor is invoked to fail fast. 

If you want to create a `ChannelPromise` you should use `channel.newPromise()` or if you want a `Promise` use `executor.newPromise()`

**Comment by Lihuanghe** [comment]
thank you .
