### ISSUE TITLE
Why custom ThreadFactory is slow ?

### ISSUE THREAD

**Issue by hank-whu** [netty/netty#7538]
### OS version: Windows 10

new NioEventLoopGroup(0, new io.netty.util.concurrent.DefaultThreadFactory(NioEventLoopGroup.class))
is slow
jmh:
Warmup Iteration   2: 71.169 ops/ms
Warmup Iteration   3: 80.204 ops/ms
Warmup Iteration   4: 85.780 ops/ms
Warmup Iteration   5: 81.681 ops/ms
Iteration   1: 84.452 ops/ms
Iteration   2: 84.801 ops/ms
Iteration   3: 85.283 ops/ms
Iteration   4: 85.253 ops/ms
Iteration   5: 84.905 ops/ms

eventLoopGroup = new NioEventLoopGroup(0);
is fast
jmh:
Warmup Iteration   2: 74.367 ops/ms
Warmup Iteration   3: 98.894 ops/ms
Warmup Iteration   4: 102.583 ops/ms
Warmup Iteration   5: 98.344 ops/ms
Iteration   1: 105.881 ops/ms
Iteration   2: 106.302 ops/ms
Iteration   3: 107.134 ops/ms
Iteration   4: 107.732 ops/ms
Iteration   5: 107.150 ops/ms

everything else is the same
what's the reason ?

**Comment by normanmaurer** [comment]
Please share the benchmark code

**Comment by hank-whu** [comment]
[netty-benchmark.zip](https://github.com/netty/netty/files/1582122/netty-benchmark.zip)

**Comment by hank-whu** [comment]
key file:
netty-server:benchmark.rpc.Server
netty-client:benchmark.rpc.netty.client.NettyClientConnector

**Comment by normanmaurer** [comment]
@hank-whu can you just push it to GitHub as a repository so its easier to browse and comment ?

**Comment by johnou** [comment]
registering my interest as we use a custom ThreadFactory.

**Comment by hank-whu** [comment]
https://github.com/hank-whu/rpc-benchmark

**Comment by normanmaurer** [comment]
@hank-whu honestly it should not make any difference as you see in our source we also just use `DefaultThreadFactory` if you not specify one.

**Comment by hank-whu** [comment]
yes, it should be same, 
but can you run the test in your computer ?

**Comment by normanmaurer** [comment]
@hank-whu can you add details how to exactly run it etc ? I am on a Mac

**Comment by hank-whu** [comment]
@normanmaurer it's very easy: 
1.cd benchmark-base; mvn install 
2.cd netty-server; mvn clean; mvn test
3.cd netty-client; mvn clean; mvn test

then change the source

**Comment by johnou** [comment]
@hank-whu what if you create the thread factory outside of the benchmark? eg. in the jmh state.

**Comment by hank-whu** [comment]
@johnou what's your meaning, can you show me the code?
this is the source code:
https://github.com/hank-whu/rpc-benchmark

**Comment by normanmaurer** [comment]
sorry I can not reproduce... Please update to latest version and verify again. If you still thing there is an issue please re-open
