### ISSUE TITLE
Issue when service or port is blocked by windows network load balancer (NLB)

### ISSUE THREAD

**Issue by mrtechit** [netty/netty#7545]
### Expected behavior
When a netty client makes a TCP connection to a server, when it is not able to connect it knows it instantly.
For eg - The server which netty client connects is stopped, **then it works fine.**
However, when a port is blocked by Windows network load balancer, it take 20 secs for netty to timeout.

Below is the error shown in the logs : 

io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /10.10.128.99:4545
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:352)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection timed out: no further information
	... 11 more

### Actual behavior
The client should realise if port is blocked instantly irrespective of server being stopped or port blocked by windows NLB.

### Steps to reproduce
Block any port at server side by using Windows NLB.
Try to connect by netty client.

### Minimal yet complete reproducer code (or URL to code)
Client code : 
public ChannelFuture connect() throws InterruptedException {
        final Channel channel = connectAsync().sync().channel();
        setChannel(channel);
        return channel.closeFuture();
    }
public ChannelFuture connect(String host, int port) throws InterruptedException {
        return connect(new InetSocketAddress(host, port));
    }
public ChannelFuture connect(SocketAddress serverAddress) throws InterruptedException {
        setSocketAddress(serverAddress);
        //TODO custom chaange
        //return connect().sync();
        return connect();
    }
 public ChannelFuture connectAsync() {
        logger.info("Connecting to {}", getSocketAddress());
        final Bootstrap b = getBootstrap();
        reconnectOnCloseListener.requestReconnect();
        final ChannelFuture connectFuture = b.connect();
        connectFuture.addListener(connFuture -> {
            if (!connectFuture.isSuccess()) {
                reconnectOnCloseListener.scheduleReconnect();
                return;
            }
            Channel channel = connectFuture.channel();
            logger.info("Client is connected to {}", channel.remoteAddress());
            setChannel(channel);
            channel.closeFuture().addListener(reconnectOnCloseListener);
        });

        return connectFuture;
    }

public ChannelFuture sendAsync(IsoMessage isoMessage) {
        Channel channel = getChannel();
        if (channel == null) {
            throw new IllegalStateException("Channel is not opened");
        }
        if (!channel.isWritable()) {
            throw new IllegalStateException("Channel is not writable");
        }
        return channel.writeAndFlush(isoMessage);
    }

    public void send(IsoMessage isoMessage) throws InterruptedException {
        sendAsync(isoMessage).sync().await();
    }

    public boolean isConnected() {
        Channel channel = getChannel();
        return channel != null && channel.isActive();
    }

### Netty version
4.1.9.Final
### JVM version (e.g. `java -version`)
1.8.0_144
### OS version (e.g. `uname -a`)
Windows server 2012 R2

**Comment by normanmaurer** [comment]
@mrtechit there is nothing we can do here its just how TCP works. Just try the same using `telnet` and you will see it exactly behaves the same way.
