### ISSUE TITLE
Using transport-native-kqueue on FreeBSD

### ISSUE THREAD

**Issue by RikkiGibson** [netty/netty#7548]
I'm wondering if anyone has used the kqueue transport on FreeBSD or any OS besides macOS, or if anyone is planning to make that possible.

### Expected behavior
KQueue native transport can be used on FreeBSD by adding netty-transport-native-kqueue as a dependency.

### Actual behavior
Build error due to being unable to [find an artifact with the classifier freebsd-x64](https://oss.sonatype.org/content/repositories/releases/io/netty/netty-transport-native-kqueue/4.1.19.Final/), and if classifier is removed, an `InvocationTargetException` with the message "failed to load the required native library" occurs at runtime.

### Steps to reproduce
Create a simple Maven project using Netty and add a `<dependency>` tag like the one at http://netty.io/wiki/native-transports.html#using-the-macosbsd-native-transport.

### Minimal yet complete reproducer code (or URL to code)
Should be adequately explained by "steps to reproduce"

### Netty version
4.1.19.Final

### JVM version (e.g. `java -version`)
openjdk version 1.8.0_144

### OS version (e.g. `uname -a`)
FreeBSD 11.1-RELEASE

**Comment by Scottmitch** [comment]
During initial development of the `KQueue` transport I made a "best effort" to support `FreeBSD`. However there was an issue [1] that prevented complete testing at that time. IIUC there has been a patch pushed to address this issue, but I have not tested the patch.

> Build error due to being unable to find an artifact with the classifier freebsd-x64

As you can see we currently don't publish artifacts for for FreeBSD, so this is expected. However theoretically you should be able to build your own artifact. The code isn't intended to be macOS specific, and there was effort to support FreeBSD initially, so I hope it should "just work" (testing is needed). We currently don't have the CI infrastructure setup or developers with experience on FreeBSD willing to support this distribution.

[1] https://lists.freebsd.org/pipermail/freebsd-current/2016-July/062547.html

**Comment by RikkiGibson** [comment]
Thanks for the context and suggestion to try building the sources for FreeBSD.

**Comment by normanmaurer** [comment]
@RikkiGibson let me know if it worked :)
