### ISSUE TITLE
Detecting client disconnection when autoRead=false

### ISSUE THREAD

**Issue by rschmitt** [netty/netty#7550]
I had a two-part question:

1. Is it possible for a server to listen for client disconnection, other than by calling `read()`?
2. Could it be? Is such a thing supported by epoll, nio, or kqueue?

**Comment by Scottmitch** [comment]
It depends upon the transport. For NIO you will have to express interest in reading/writing or potentially attempting to write may also give you an error. For EPOLL/KQUEUE we set a flag that will notify you of a remote hangup without resetting for reading.

Please re-open if you think there is a Netty issue/bug.

**Comment by rschmitt** [comment]
Thanks for the information! Is this documented anywhere?
