### ISSUE TITLE
Provide ability to decompress response using any header, not just Content-Encoding

### ISSUE THREAD

**Issue by asarkar** [netty/netty#7553]
### Expected behavior
`HttpContentDecompressor` works only based on `Content-Encoding` header, but not all servers are well-behaved citizens of HTTP. The server I'm dealing with doesn't return a `Content-Encoding` header, but sets the `Content-Type = application/x-gzip`, and there's nothing I can do to change that. We need a way to _easily_ plug in different implementations of `HttpContentDecoder` that accept `HttpHeaders`, not just content encoding. The current design of `HttpContentDecoder` is too restrictive, and doing the above would require a ton of code.

### Actual behavior

Response is not decompressed.

### Steps to reproduce

Create a rogue server that returns compressed response without `Content-Encoding` header.

### Reactor Netty version

4.1.17.Final

### JVM version (e.g. `java -version`)

Irrelevant.

### OS version (e.g. `uname -a`)

Irrelevant.

**Comment by Scottmitch** [comment]
In general we try to keep changes in Netty that explicitly compensate for peers who do not follow RFCs to a minimum. I would suggest modifying your pipeline to translate the custom `Content-Type` into the expected `Content-Encoding` header before It gets to `HttpContentDecoder`.

**Comment by asarkar** [comment]
Ok, how do I do that? I’m new to Netty and on top of that using Spring WebClient. Can you point me to an example?

**Comment by asarkar** [comment]
I came up with the following:

```
public class HttpContentForcedDecompressor extends HttpContentDecompressor {
    private final boolean forceAcceptCompression;
    private boolean continueResponse;

    @Override
    protected void decode(ChannelHandlerContext ctx, HttpObject msg, List<Object> out) throws Exception {
        if (msg instanceof HttpResponse && ((HttpResponse) msg).status().code() == 100) {

            if (!(msg instanceof LastHttpContent)) {
                continueResponse = true;
            }
            // 100-continue response must be passed through.
            out.add(ReferenceCountUtil.retain(msg));
            return;
        }

        if (continueResponse) {
            if (msg instanceof LastHttpContent) {
                continueResponse = false;
            }
            // 100-continue response must be passed through.
            out.add(ReferenceCountUtil.retain(msg));
            return;
        }

        if (msg instanceof HttpMessage) {
            final HttpMessage message = (HttpMessage) msg;
            final HttpHeaders headers = message.headers();

            String contentEncoding = headers.get(CONTENT_ENCODING);
            if (contentEncoding != null) {
                contentEncoding = contentEncoding.trim();
            } else if (forceAcceptCompression) {
                log.warn("Forcefully setting {} = {}.", CONTENT_ENCODING, GZIP);
                contentEncoding = GZIP.toString();
            } else {
                contentEncoding = IDENTITY.toString();
            }

            headers.set(CONTENT_ENCODING, contentEncoding);
        }

        super.decode(ctx, msg, out);
    }
}
```

**Comment by Scottmitch** [comment]
Seems a bit fragile due to the code duplication but I will close this for now because I think there are more preferred ways to work around the client issue than modifying code in Netty.

**Comment by asarkar** [comment]
> I think there are more preferred ways
@Scottmitch If you don't say, how will I know what the preferred ways are? you commented that the code I posted is fragile, but didn't offer an alternative. I'm not getting any help here :(

**Comment by Scottmitch** [comment]
An alternative was offered in https://github.com/netty/netty/issues/7553#issuecomment-354879331

> I would suggest modifying your pipeline to translate the custom Content-Type into the expected Content-Encoding header before It gets to HttpContentDecoder.

**Comment by asarkar** [comment]
Perhaps it's my inexperience with Netty, but I was under the impression that the implementation I posted was in fact, adding a header. After seeing your comment, I created the following that I'm now adding before `HttpContentDecompressor`. Is this what you suggested?

```
public class HttpResponseHeadersHandler extends ChannelInboundHandlerAdapter {
    private final HttpHeaders httpHeaders;

    @Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) {
        if (msg instanceof HttpResponse &&
                !HttpStatus.resolve(((HttpResponse) msg).status().code()).is1xxInformational()) {
            HttpHeaders headers = ((HttpResponse) msg).headers();

            httpHeaders.forEach(e -> {
                log.warn("Modifying {} from: {} to: {}.", e.getKey(), headers.get(e.getKey()), e.getValue());
                headers.set(e.getKey(), e.getValue());
            });
        }
        ctx.fireChannelRead(msg);
    }
}
```

**Comment by Scottmitch** [comment]
In general yes the approach is to create a ChannelHandler, and insert it in the pipeline in-between `HttpCodec` and `HttpContentDecompressor`. I don't understand why you are iterating the headers, and I don't see where you are using `Content-Type` header value so that `Content-Encoding` is set correctly. I would expect something like:

check if `headers.get(HttpHeaderNames.CONTENT_TYPE)` is `application/x-gzip`, and if so then `headers.set(HttpHeaderNames.CONTENT_ENCODING, HttpHeaderValues.GZIP)`. You may want to consider removing/modifying `HttpHeaderNames.CONTENT_TYPE` so that it is not equal to `application/x-gzip`.

**Comment by asarkar** [comment]
> the approach is to create a ChannelHandler, and insert it in the pipeline in-between HttpCodec and HttpContentDecompressor

Got it, thanks.

> why you are iterating the headers

I set the `Content-Encoding = gzip` so that `HttpContentDecompressor` works, and the `Content-Type = application/json` so that Spring decoder later parses the JSON. If I remove `Content-Type`, Spring won't know it's JSON.

I made the code generic, such that it can overwrite any header passed in by the caller, not just two.

**Comment by normanmaurer** [comment]
@asarkar so can we close this issue ?

**Comment by asarkar** [comment]
@normanmaurer Is your take on this the same as Scott's? I'm not sure why having a way for clients to look at other headers can't be entertained? Yes, it may not be 100% compliant with the RFC, but the client would knowingly make that decision, and it doesn't make Netty non-compliant.
