### ISSUE TITLE
faulty "isAndroid" behavior on Desktop

### ISSUE THREAD

**Issue by bsideup** [netty/netty#7556]
Hello!

### Expected behavior
`isAndroid` returns true only if running on Android

### Actual behavior
`isAndroid` returns `true` on Desktop if there is an Android SDK on the classpath 

### Steps to reproduce
Add Android SDK to the classpath and run with OpenJDK. `PlatformDependent.isAndroid()` returns `true`.

### Minimal yet complete reproducer code (or URL to code)
```groovy
@GrabResolver(name='google', root='https://maven.google.com')
@Grapes([
    @Grab(group='io.netty', module='netty-common', version='4.1.11.Final'),
    @Grab(group='com.google.android', module='android', version='+'),
])
import io.netty.util.internal.PlatformDependent

ClassLoader.scl = this.class.classLoader

assert PlatformDependent.isAndroid() == false
```

### Netty version
Any, including the latest `4.1.19.Final`

### JVM version (e.g. `java -version`)
Any Desktop JVM

### OS version (e.g. `uname -a`)
Any

**Comment by Scottmitch** [comment]
@bsideup - Are you interested in submitting a PR? We make a best effort to support Android but it is  currently not officially supported.

**Comment by bsideup** [comment]
Hi @Scottmitch,

In general, I don't mind to help with PR, let's just agree on the implementation.

I had a quick chat in Twitter with @normanmaurer, he proposed an approach where system property can force the check, while I suggested to use properties file (i.e. `netty.properties`) on the classpath.
The reasoning is simple - we ( https://github.com/testcontainers ) have some users (i.e. Flyway) who happened to have Android SDK on their classpath, but run the tests on Desktop, and it fails because of the issue I reported.
System property-like approach will make it hard to run individual tests because you will have to configure it per run configuration, while properties file will make it possible to put it under `/src/test/resources` and disable Android detection for every test.

WDYT?

**Comment by nibuen** [comment]
Possibly a different ticket, but also to note with Android API 26+ assuming java 6 for Android is no longer true.  For example NIO Datagram Channels are supported now assuming Android developer targets/uses that minimum version, but with isAndroid() check in class makes it not avaliable on Android and unit tests.

**Comment by Scottmitch** [comment]
@bsideup - Netty has a (bad?) habit of using static state for configuration, which can make testing challenging. However I would prefer to avoid a file based approach which brings in new conventions and dependencies to initialization (which may block) if it can be avoided. If we need to add a programatic way to override the value and your project wants to drive this value based upon a configuration file that would be preferable IMHO.

**Comment by normanmaurer** [comment]
Related to https://github.com/netty/netty/pull/7679

**Comment by normanmaurer** [comment]
Should be fixed by https://github.com/netty/netty/pull/7679
