### ISSUE TITLE
Why netty does not use log4j2 to record internal logs

### ISSUE THREAD

**Issue by Zhangjk2012** [netty/netty#7560]
in my project, I just only use Log4j which version is 2.10.0. when i ran my project,  I found that netty used the JdkLogger. 

the source code is:
```
@SuppressWarnings("UnusedCatchParameter")
    private static InternalLoggerFactory newDefaultFactory(String name) {
        InternalLoggerFactory f;
        try {
            f = new Slf4JLoggerFactory(true);
            f.newInstance(name).debug("Using SLF4J as the default logging framework");
        } catch (Throwable t1) {
            try {
                f = Log4JLoggerFactory.INSTANCE;
                f.newInstance(name).debug("Using Log4J as the default logging framework");
            } catch (Throwable t2) {
                f = JdkLoggerFactory.INSTANCE;
                f.newInstance(name).debug("Using java.util.logging as the default logging framework");
            }
        }
        return f;
    }
```

**Comment by johnou** [comment]
@Zhangjk2012 use the slf4j logging facade with the log4j2 adapter.

**Comment by Zhangjk2012** [comment]
because i found the io.netty.util.internal.logging package has a Log4J2LoggerFactory class and the class has no `Deprecated` annotated . so i thought netty will use log4j2 logging the logs when my project used log4j2 .

**Comment by Scottmitch** [comment]
I don't know the history behind why `InternalLogger*` classes were introduced but the intention is to provide an abstraction internal to Netty so we can avoid a dependency on any specific logging api/facade from being wide spread throughout the Netty code base. Whether or not it is necessary any more is debatable and something worth re-visiting as part of the next major release (see https://github.com/netty/netty/issues/5430#issuecomment-355182251).

Note that classes which reside in a `*.internal.*` package are intended only for internal Netty use, are subject to change at any time, and generally are  not intended to be used by applications. You are welcome to use your favorite logging implementation just make sure the appropriate API/SPI and implementations are on your class path.

**Comment by laosijikaichele** [comment]
reason and discussion can be found here: https://github.com/netty/netty/issues/64

**Comment by Zhangjk2012** [comment]
@laosijikaichele ths a lot
