### ISSUE TITLE
StompFrame.copy() does not copy headers 

### ISSUE THREAD

**Issue by amizurov** [netty/netty#7561]
### Expected behavior
Call stompFrame.copy() do copies of content and headers.

### Actual behavior
After call stompFrame.copy() only content was copy.

### Minimal yet complete reproducer code (or URL to code)

 `StompFrame stompFrame = new DefaultStompFrame(StompCommand.CONNECT);`
 `stompFrame.headers().set(StompHeaders.HOST, "localhost");`
 `StompFrame copyFrame = stompFrame.copy();`
 `Assert.assertTrue(copyFrame.headers().isEmpty());`

### Netty version
4.1.20.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

### OS version (e.g. `uname -a`)
Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7562
