### ISSUE TITLE
JdkZlibDecoder ignores everything but first GZIP stream, non-compliant with RFC 1952

### ISSUE THREAD

**Issue by asarkar** [netty/netty#7566]
### Expected behavior
gzip content is fully consumed
### Actual behavior
gzip content is partially consumed
### Steps to reproduce
n/a
### Minimal yet complete reproducer code (or URL to code)
n/a
### Netty version
4.1.17
### JVM version (e.g. `java -version`)
n/a
### OS version (e.g. `uname -a`)
n/a

I'm using Spring WebClient to read a large (12 million records) gzipped response. I've set up the Netty pipeline as follows:
```
ctx.addHandlerLast(new ReadTimeoutHandler(readTimeoutMillis, TimeUnit.MILLISECONDS));
ctx.addHandlerLast(new Slf4JLoggingHandler());
if (forceDecompression) {
    io.netty.handler.codec.http.HttpHeaders httpHeaders = new ReadOnlyHttpHeaders(
            true,
            CONTENT_ENCODING, GZIP,
            CONTENT_TYPE, APPLICATION_JSON
    );
    HttpResponseHeadersHandler headersModifier = new HttpResponseHeadersHandler(httpHeaders);
    ctx.addHandlerFirst(headersModifier);
}
ctx.addHandlerLast(new HttpContentDecompressor());
```
The `HttpResponseHeadersHandler` overwrites headers in the response because the server doesn't send an `Content-Encoding` header. Details and implementation can be found [here](https://github.com/netty/netty/issues/7553#issuecomment-355249883).

Problem is, processing stops after about 130,000 records. No errors are shown. I've debugged and found out that the `JdkZlibDecoder` used for decompression stops reading and enters the finished block. I've tests that work fine for fewer number of records (100 or so).

However, using a different client (okhttp), if I don't set the `Content-Encoding` header and wrap the input stream with `GZIPInputStream`, everything works as expected.

So, question is, if `GZIPInputStream` doesn't have a problem, why does `JdkZlibDecoder`? And since it does, why won't it report what it thinks is the issue?

```
>> GET http://myserver.mycompany.com/.../businesses.20180104.json.gz
<< 200 OK
<< connection -> [keep-alive]
<< accept-ranges -> [bytes]
<< content-disposition -> [attachment; filename="businesses.20180104.json.gz"; filename*=UTF-8''businesses.20180104.json.gz] 
<< content-type -> [application/x-gzip]
<< content-length -> [3384998203]
<< date -> [Fri, 05 Jan 2018 00:43:32 GMT]
<< etag -> [0e49d5fa7ba9f68058bfbb4a98bef032c3a73871]
<< last-modified -> [Thu, 04 Jan 2018 23:54:26 GMT]
<< x-artifactory-id -> [9732f56568ea1e3d:59294f65:160b8066066:-8000]
<< x-checksum-md5 -> [451ca1b1414e7b511de874e61fd33eb2]
<< x-artifactory-filename -> [businesses.20180104.json.gz]
<< server -> [Artifactory/5.3.0]
<< x-checksum-sha1 -> [0e49d5fa7ba9f68058bfbb4a98bef032c3a73871]
```

For full disclosure, Initially posted a [question](https://stackoverflow.com/q/48094553/839733) on stackoverflow. Also related to https://github.com/square/okhttp/issues/3759.

**Comment by yschimke** [comment]
Quite a lot of relevant discussion on the OkHttp issue that is linked to above https://github.com/square/okhttp/issues/3759

**Comment by asarkar** [comment]
It has been established in https://github.com/square/okhttp/issues/3759 that this is a bug and non-compliant behavior with [RFC 1952[https://tools.ietf.org/html/rfc1952)

**Comment by asarkar** [comment]
@normanmaurer @yschimke Please review my MR.

**Comment by normanmaurer** [comment]
Merged... @asarkar thanks a lot!

**Comment by asarkar** [comment]
@normanmaurer what version will this fix go in, and when will be that available on Maven Central?

**Comment by normanmaurer** [comment]
@asarkar once we release... most likely end of the week or early next week.
