### ISSUE TITLE
Does netty honor -DsocksProxyHost and -DsocksProxyPort?

### ISSUE THREAD

**Issue by golimarrrr** [netty/netty#7570]
I'm running an application that uses Netty (v3.10.6.Final), and don't have the source code so I thought I could use the -DsocksProxyHost and -DsocksProxyPort args for the JVM, to make the connections go through a running SOCKS server and reach some final machines
### Expected behavior
I expected the application to try to connect to the SOCKS server address/port
### Actual behavior
The application tries to connect directly to the final machines
### Steps to reproduce
java -DsocksProxyHost -DsocksProxyPort -jar application.jar
### Netty version
3.10.6.Final
### JVM version (e.g. `java -version`)
1.8.0_151-b12
### OS version (e.g. `uname -a`)
Windows 7 64bit

**Comment by normanmaurer** [comment]
As you already found out it’s not supported... also 3.x is EOL

**Comment by golimarrrr** [comment]
Ok, thought that the JVM did the tunneling (i.e. that you don't need to support it on your application)
