### ISSUE TITLE
Attribute should support "computeIfAbsent" method

### ISSUE THREAD

**Issue by oakad** [netty/netty#7571]
An useful pattern in channel attributes is an optional attribute, which is created only if needed, to the tune:

```java
UsefulObject getUseful(Channel ch) {
    return channel.attr(ATTR_KEY).setIfAbsent(new UsefulObject());
}
```
Clearly, such a pattern results in unnecessary allocations of `UsefulObject`s, which are immediately discarded.

Thus, it will be most helpful if `Attribute` supported an atomic `computeIfAbsent` method, taking a functionally compatible interface as an argument. 

```java
UsefulObject getUseful(Channel ch) {
    // Older Java versions can still use a dynamic or pre-allocated factory class reference here.
    return channel.attr(ATTR_KEY).computeIfAbsent(UsefulObject::new);
}
```

**Comment by normanmaurer** [comment]
@oakad This will be a breaking change as it will change the `Attribute` interface. This will have to wait until the next major version or until we switch to using java8 and so can use default methods.

**Comment by normanmaurer** [comment]
Closing this and adding it to https://github.com/netty/netty/issues/5430
