### ISSUE TITLE
why set Thread.MAX_PRIORITY as default priority level on NioEventLoopGroup thread?

### ISSUE THREAD

**Issue by laosijikaichele** [netty/netty#7576]
Actually this is a question, normally we set thread level as `Thread.NORM_PRIORITY`. but I see when doing `new NioEventLoopGroup()`, netty will create threads with `MAX_PRIORITY`, why is that?

**Comment by normanmaurer** [comment]
@laosijikaichele You can change this by either use your own `Executor` or `ThreadFactory` when create the `NioEventLoopGroup`. Its just the default that netty uses when you not specify it yourself as we consider the IO the most "important" work to do.
