### ISSUE TITLE
Making contributions should be easier 

### ISSUE THREAD

**Issue by asarkar** [netty/netty#7578]
### Expected behavior
Someone intending to contribute should be able to set up their development environment quickly and easily. 

### Actual behavior
Development environment [setup](http://netty.io/wiki/setting-up-development-environment.html) requires several manual steps:
- Local Maven installation is required.
- Git line-ending manual configuration is required.

**Comment by Scottmitch** [comment]
Were the docs not clear/complete/correct, and was there any place that was particularly challenging. Do you have any suggestions on how to improve this process?

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7579
