### ISSUE TITLE
Compile against Java 8

### ISSUE THREAD

**Issue by asarkar** [netty/netty#7581]
### Expected behavior
Produced bytecode is targeted for Java 8. It is almost 4 years since Java 8 was released, and more than a decade since Java 6 was released. I don't want to make this ticket into "new features in Java 7 and 8", since there are millions of posts/articles on that, but the benefits are obvious.

Extreme affinity for backward compatibility is progress killer. Java `Thread` class still has a `stop` method that was deprecated, I believe, in Java 1.1!  If someone is still stuck with Java 6, well, too bad.

Perhaps this can happen in Netty 5.

### Actual behavior
Produced bytecode is targeted for Java 6.

### Steps to reproduce
N/A

### Minimal yet complete reproducer code (or URL to code)
N/A

### Netty version
N/A

### JVM version (e.g. `java -version`)
N/A

### OS version (e.g. `uname -a`)
N/A

**Comment by fenik17** [comment]
This is in the plans: #5430

**Comment by normanmaurer** [comment]
Yep netty 5... I will start to kick of discussions for the next major version in the next few weeks.

**Comment by normanmaurer** [comment]
Let me close it as it is already contained in #5430
