### ISSUE TITLE
Provide a Docker image for reproducible builds

### ISSUE THREAD

**Issue by asarkar** [netty/netty#7585]
### Expected behavior
Developer can build on any platform using a Docker image without having to install additional native packages. Simply cloning the repo and following an one-liner build command should be enough.

We should provide a fully-configured Docker image, and also configure the TeamCity CI to use it (I hope it has support for Docker). That way, every build will be reproducible without the million variables that are involved today (OS, OS version, Linux distro, package version, Maven version, etc etc).
FWIW, the Maven version dependency will be eliminated with this PR https://github.com/netty/netty/issues/7578

Sample build command:
```
docker run -it -v /path/to/local/repo:/home/netty/netty netty/netty-build
```

The above command assumes that the default entrypoint to the Docker image is `mvn -f /home/netty/netty clean install`. Of course, the actual path and the build commands can vary, I just made these up.

### Actual behavior
Build is pretty much wild west. For building on Linux, additional native packages need to be installed. Haven't tried on Windows, but I couldn't get it working on a Mac using a Debian VM or Docker image as it kept running OOM. I don't accept having to install a bunch of additional packages on my system for various reasons, security being an obvious one.

### Steps to reproduce
Clone the repo and run `mvn clean install`. Watch it fail.

### Minimal yet complete reproducer code (or URL to code)
N/A

### Netty version
N/A

### JVM version (e.g. `java -version`)
N/A

### OS version (e.g. `uname -a`)
N/A

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7594 ... @asarkar PTAL

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7594
