### ISSUE TITLE
Check/enforce backwards compatibility for patch releases

### ISSUE THREAD

**Issue by ppalaga** [netty/netty#7586]
### Expected behavior

Patch releases of the same major.minor version should follow strict rules that will guarantee that for any _x_, _y_ and _z_ , any code compiled against netty _x.y.z_ will have no API compatibility issues to run with _x.y.z+1_

This is something @normanmaurer and @Scottmitch seem to be implying in https://github.com/netty/netty/issues/6752 and perhaps also elsewhere.

### Actual behavior

This is unfortunately not the case for netty 4.1.x. 
https://github.com/netty/netty/commit/e074df2ae6501d99921543369198c53e4d99ed1b#diff-22eb274f9da6d99eba6c855a8a3c0004L53 Changed the signature of a public constructor thus making code compiled against 4.1.9- throw NoSuchMethodErrors, see https://github.com/jurmous/etcd4j/pull/146

It would be nice if netty addopted some automatic per-PR API checks, such as https://revapi.org of @metlos or perhaps also japi mentioned in https://github.com/netty/netty/issues/7410

**Comment by slandelle** [comment]
@ppalaga This class is annotated [@UnstableApi](https://github.com/netty/netty/blob/e074df2ae6501d99921543369198c53e4d99ed1b/resolver-dns/src/main/java/io/netty/resolver/dns/DnsAddressResolverGroup.java#L42) to advertise that it is still in incubation and subject to changes.

**Comment by ppalaga** [comment]
> This class is annotated @UnstableApi to advertise that it is still in incubation and subject to changes.

I wonder do you have checks in place guaranteeing that stable parts do not depend on parts marked as @UnstableApi?

Do you offer a distro that has the @UnstableApi parts stripped away? If not, would such distro be possible in theory at least?

**Comment by metlos** [comment]
If you decide to go ahead with adding the API checks to Netty build, I'm more than happy to help out with that...

**Comment by normanmaurer** [comment]
@ppalaga no we not have any checks in place that "stable" parts not depend on "unstable" parts. The unstable parts are mainly meant to be something that may change over time and you can not depend on its API to be stable for now.

**Comment by metlos** [comment]
I'm not sure to what extent you follow semantic versioning (different projects have different policies for what they allow in different version number increments), but I'm just throwing this here in case you were interested what revapi found between 4.1.0.Final and 4.1.19.Final of the netty-resolver-dns (and anything it transitively exposes in the API): https://diff.revapi.org/?groupId=io.netty&artifactId=netty-resolver-dns&old=4.1.0.Final&new=4.1.19.Final

**Comment by ppalaga** [comment]
@normanmaurer thanks for the answer. As you may well suspect, my questions are motivated by the following: In large projects that aggregate multiple third party libs (think WildFly or Apache Camel) some of those libs happen to depend on netty. They may naturally choose to compile against various microversions of netty. With this @unstableapi thing, Netty upgrades in the aggregating project thus becomes quite a pain. It would be cool if we could at least figure out somehow (ideally during the build of the aggregating project) that libs that we aggregate use code marked as @unstableapi. Having a netty distro with @unstableapi parts stripped away could help us to do just that. Maybe you have other ideas?

**Comment by normanmaurer** [comment]
I think we did this now:

https://github.com/netty/netty/commit/14ef469f3170842fdf6e3f41c745017fcd9679e4
