### ISSUE TITLE
Should negative content-length headers be treated as bad requests?

### ISSUE THREAD

**Issue by pyr** [netty/netty#7590]
### Expected behavior

I'm on the fence on the expected behavior. The HTTP RFC mandates that when
`content-length` exists, it should be a positive integer or zero, as evidenced in [https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.13].

### Actual behavior

When netty's `HttpObjectDecoder` encounters a negative `content-length` header, it assumes that no content length has
been specified (see: https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java#L625-L629) and switches to the `READ_VARIABLE_LENGTH` state. This states consumes an incoming body until the connection closes and continues raises no error.

This can of course be guarded against in application code when receiving the initial `HttpRequest` message downstream, this is more a question than an issue: should netty take care of this and would you be interested in a patch that handle negative content-length.

It's debatable but since `HttpObjectDecoder` does treat content-length specifically as it uses it to determine the behavior it should adopt, it could decide to validate against malformed content-length.

### Steps to reproduce

With a standard `HttpServerCodec` based pipeline, listening on port 8080 perform the following:

```
curl -X PUT -H 'Content-Length: -5' --data-raw foobar http://localhost:8080
```

### Minimal yet complete reproducer code (or URL to code)

The example **webfile** server in https://github.com/pyr/net exposes this behavior
https://github.com/pyr/net/tree/master/examples/webfile

It can be started with `lein run /tmp/webfile` and the above curl command to exhibit hanging.
Guarding against this can be done by application code, the question remains whether it should be up to application code or not to do so (my initial expectation was that the `validateheaders` flag would ensure valid names and values).

### Netty version

```
4.1.19
```

### JVM version (e.g. `java -version`)

```
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)
```

### OS version (e.g. `uname -a`)

```
4.14.13-1-ARCH
```

**Comment by normanmaurer** [comment]
@ejona86 @Scottmitch @carl-mastrangelo WDYT ?

**Comment by normanmaurer** [comment]
@trustin any idea ?

**Comment by trustin** [comment]
A more robust behavior would be to produce a zero-length message with failed `DecoderResult`?

**Comment by pyr** [comment]
@trustin you mean using the existing `/bad-request` DecoderResult mechanism? If so I can look into providing this.

**Comment by ejona86** [comment]
[Section 4.4](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4) is might shed more light:
> If a request contains a message-body and a Content-Length is not given, the server SHOULD respond with 400 (bad request) if it cannot determine the length of the message, or with 411 (length required) if it wishes to insist on receiving a valid Content-Length.

> Messages MUST NOT include both a Content-Length header field and a non-identity transfer-coding. If the message does include a non- identity transfer-coding, the Content-Length MUST be ignored.

> When a Content-Length is given in a message where a message-body is allowed, its field value MUST exactly match the number of OCTETs in the message-body. HTTP/1.1 user agents MUST notify the user when an invalid length is received and detected.

I wanted to find where this was documented in httpbis though. It seems [RFC 7230so§3.3.3](https://tools.ietf.org/html/rfc7230#section-3.3.3) is close. But it isn't as specific.

**Comment by pyr** [comment]
@ejona86 This isn't true when transfer-encoding is set to chunked, since a content-length cannot be provided in this case.

**Comment by ejona86** [comment]
> This isn't true when transfer-encoding is set to chunked

@pyr, what is "this"?

I quoted this part of the spec:
> If the message does include a non- identity transfer-coding, the Content-Length MUST be ignored.

So although the Content-Length MUST NOT be sent in that case, the server MUST ignore it if it is there.

**Comment by normanmaurer** [comment]
I will close this due no followup.
