### ISSUE TITLE
Add fatal level for leak detector

### ISSUE THREAD

**Issue by electrum** [netty/netty#7593]
It would be helpful to have a `FATAL` level that is the same as `PARANOID` but does a `System.exit(1)` for use in integration tests. The Maven Surefire plugin doesn't have a facility to fail the build based on test output, so this would allow it to work easily out-of-the-box.

**Comment by normanmaurer** [comment]
@electrum may want to provide a PR ?

**Comment by KowalczykBartek** [comment]
I am willing to do this (easy picking ;D) but - can you @electrum tell what is scenario for this failing Maven Surefire plugin ? how I can reproduce this ?

**Comment by normanmaurer** [comment]
@electrum ping

**Comment by normanmaurer** [comment]
@electrum ping

**Comment by electrum** [comment]
Sorry for not following up. I can put up a PR within a few days. Our use case is that our unit tests were sufficient to trigger leaks, but no one noticed because the tests still pass (just a message in the log that no one sees).

**Comment by normanmaurer** [comment]
@electrum yeah sure I would be interested in a PR if its general useful :)

**Comment by normanmaurer** [comment]
Will close this as there was no more activity. Please re-open if you still want to do it.
