### ISSUE TITLE
Writing an Http2 client with Http2MultiplexCodec

### ISSUE THREAD

**Issue by Bennett-Lynch** [netty/netty#7599]
I'm trying to write an Http2 client using the new `Http2MultiplexCodec` API, and I'm struggling a bit, especially since there's still [no client example](https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/http2/helloworld) using thew new API.

Since it's still lacking some documentation, here's my understanding of the API -- please correct me if anything's wrong:

- You bootstrap your client's `SocketChannel` pipeline by using a `Http2MultiplexCodecBuilder`.  The `ChannelHandler`/`ChannelInitializer` that this builder takes is only used for _remotely_ created streams (server pushes?).
- To send a new request from the client, you need to open a new `Http2StreamChannel`, accomplished by using the primary `SocketChannel` to create a new `Http2StreamChannelBootstrap`.  The `ChannelHandler`/`ChannelInitializer` that you pass into this bootstrap will be used for the locally created stream.

The problem I'm encountering is that all new locally created streams are using stream ID 0 (the stream ID [reserved for control messages](https://http2.github.io/http2-spec/#StreamIdentifiers)).  I don't see a transparent way to change the ID, and I'd expect to not have to manage the current stream ID state by myself with the new API.

Design wise, I find this a but clunky/confusing.  I would rather declare my pipeline setup one time, as part of the `Http2MultiplexCodecBuilder` (similar to the server setup), rather than for every newly created stream.

But that aside, is there any way to correctly obtain new valid stream IDs (3, 5, etc.) for new client streams?  And is there a working client example using `Http2MultiplexCodec` anywhere?

**Comment by Bennett-Lynch** [comment]
Just noticed that part of the problem might be that the new API is not specifying the stream ID using `ExtensionHeaderNames.STREAM_ID` -- which I'm currently relying on.  A working example would help a lot of this header is not being used anymore.

**Comment by Scottmitch** [comment]
Yes you will need to use `Http2StreamChannelBootstrap`. Until we get around to adding an example you can see usages of this class in [Http2MultiplexCodecTest](https://github.com/netty/netty/blob/4.1/codec-http2/src/test/java/io/netty/handler/codec/http2/Http2MultiplexCodecTest.java#L200).

> The problem I'm encountering is that all new locally created streams are using stream ID 0

For outbound streams the stream IDs are assigned by the codec at the appropriate time behind the scenes (e.g. when a frame is written which must transitions the stream to a non-idle state).

**Comment by Scottmitch** [comment]
The initial settings can be set in [Http2FrameCodecBuilder](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2FrameCodecBuilder.java#L61-L64). You don't necessarily have to wait for the settings like in this example. However you should wait for the `Http2ConnectionPrefaceAndSettingsFrameWrittenEvent` user event on the client side before you start writing.

**Comment by Bennett-Lynch** [comment]
Thanks, slowly working my way through this.

I tried inserting a `ChannelInboundHandlerAdapter` after `Http2MultiplexCodec` (_forClient_) that overrides `userEventTriggered` and checks for `evt instanceof Http2ConnectionPrefaceAndSettingsFrameWrittenEvent` -- this does not seem to be reached.

Also, on an unrelated note, I seem to be having an issue with multiple threads attempting to call `Http2StreamChannelBootstrap#open().syncUninterruptibly().getNow()`.  The first thread works fine and I can write to the tail-end of the channel, the second one results in a `Write failed: java.nio.channels.ClosedChannelException`.

**Comment by normanmaurer** [comment]
@Bennett-Lynch can you show some reproducer for the `CloseChannelException` ? 

Also the exact code you used for the client where you dont receive `Http2ConnectionPrefaceAndSettingsFrameWrittenEvent ` will help

**Comment by Bennett-Lynch** [comment]
Sorry for the slow response.  I spent some time trying to create a minimal/complete/verifiable example, and I was able to successfully recognize the `Http2ConnectionPrefaceAndSettingsFrameWrittenEvent` and bootstrap multiple new `Http2StreamChannel`s simultaneously -- so something's wrong somewhere in my specific application logic.  I'll spend some time debugging it.

Closing this out, thanks for the responses.  Would still love to see an official Http2 client example still though.  My attempt to reproduce is a bit hacky, but feel free to ping me if you think it'd be useful as a starting point.

**Comment by lusong64** [comment]
hi @Bennett-Lynch and @normanmaurer 

I am struggling to write a client based on Http2MultiplexCodec too. Basically, I tried to modify the example/http2/client/Http2ClientInitializer. Here is how I added the Http2MultiplexCodec: 
 
`Http2ClientUpgradeCodec upgradeCodec = new Http2ClientUpgradeCodec(
        Http2MultiplexCodecBuilder
            .forClient(new SimpleChannelHandler())
            .frameLogger(new Http2FrameLogger(INFO, Http2MultiplexClientInitializer.class))
            .build()
    );`
`   ch.pipeline().addLast(sourceCodec,
        upgradeHandler,
        new UpgradeRequestHandler(),
        new UserEventLogger());`

However, it did not work. Mind if giving some hint? Thanks!

**Comment by lusong64** [comment]
Never mind. I found an example.

**Comment by artgon** [comment]
Just wanted to bump this, is there an example for the new client API that someone can point me to?

**Comment by ssheng** [comment]
Same here. @lusong64 could you share the example you have found?

**Comment by lusong64** [comment]
I developed our code based on http://codegists.com/snippet/java/multiplexcodeccleartexthttp2testjava_jprante_java

**Comment by TristanPerry** [comment]
Just in-case anyone finds this from Google (or elsewhere), codegists.com is dead however the mentioned example is available in [jprante/netty-http](https://github.com/jprante/netty-http).
