### ISSUE TITLE
should add java-doc for method DefaultPromise#cancel(boolean mayInterruptIfRunning)

### ISSUE THREAD

**Issue by laosijikaichele** [netty/netty#7609]
### Expected behavior
implementation of method `io.netty.util.concurrent.DefaultPromise#cancel(boolean mayInterruptIfRunning)` actually ignored the param `mayInterruptIfRunning`.
so it need to make a comment like following:
(this comment is copied from `java.util.concurrent.CompletableFuture#cancel`):

>      * @param mayInterruptIfRunning this value has no effect in this
>      * implementation because interrupts are not used to control
>      * processing.
the other method `io.netty.util.concurrent.CompleteFuture#cancel` may do the same too.
### Actual behavior
there is no comment about the param `mayInterruptIfRunning`, which will make user confusing when call the `cancel` method with a param `mayInterruptIfRunning`.
### Netty version
4

**Comment by normanmaurer** [comment]
@laosijikaichele PRs welcome... that said I am not sure if we need anything here as `mayInterruptIfRunning` already signals that it may interrupt or not.

**Comment by laosijikaichele** [comment]
I am setting up the netty development environment, after that, I will try a PR for this doc issue. :)

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7624
