### ISSUE TITLE
tests in error under netty-transport module

### ISSUE THREAD

**Issue by laosijikaichele** [netty/netty#7613]
### Expected behavior
run `mvn test` under netty/transport, should finish successfully.
### Actual behavior

> Tests in error: 
  NioSocketChannelTest.testChannelReRegisterReadDifferentEventLoop:167->testChannelReRegisterRead:233->Object.wait:502->Object.wait:-2 » TestTimedOut
  NioSocketChannelTest.testChannelReRegisterReadSameEventLoop:162->testChannelReRegisterRead:233->Object.wait:502->Object.wait:-2 » TestTimedOut
  NioSocketChannelTest.testShutdownOutputAndClose:259->Object.wait:502->Object.wait:-2 » TestTimedOut
Tests run: 239, Failures: 0, Errors: 3, Skipped: 6
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

### Steps to reproduce
run `mvn test` under netty/transport
### Minimal yet complete reproducer code (or URL to code)
should not matter
### Netty version
4.1
### JVM version (e.g. `java -version`)

> java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

### OS version (e.g. `uname -a`)
macOS 10.13.2 (17C205)

**Comment by Scottmitch** [comment]
Seems like the `testChannelReRegister*` tests failed before the connection was established.
- can you increase [the timeouts](https://github.com/netty/netty/blob/4.1/transport/src/test/java/io/netty/channel/nio/NioSocketChannelTest.java#L160) (e.g. to 10 seconds) and run again?
- does this failure happen consistently or sporadically?
- is your machine particularly busy while running the tests?

**Comment by laosijikaichele** [comment]
@Scottmitch 
- I increased timeout to 10 seconds, run 3 times, same errors still occurred.
- I revert the timeout to 3 seconds, run 3 times, same errors still occurred.
- My machine is not busy during running the tests:short time 80% CPU usage before run into NioSocketChannelTest. after NioSocketChannelTest begin running, the CPU usage is pretty low(about 20%).

**Comment by normanmaurer** [comment]
@laosijikaichele very strange I am using macOS as well and all just works.

**Comment by laosijikaichele** [comment]
@normanmaurer  my macOS installed the following security update several days ago: https://support.apple.com/en-us/HT208397,
does this matter?

**Comment by normanmaurer** [comment]
I have the same installed and it just works. Maybe its a firewall ?

**Comment by amizurov** [comment]
On my laptop MacOs 10.12.6 (16G1212) its work properly to.

**Comment by laosijikaichele** [comment]
@amizurov I think there must be some dependencies/config affect the `mvn test`. I am switching to docker env and try to make it running.

**Comment by Scottmitch** [comment]
@laosijikaichele - can you please provide some rational as to why you closed the issue. Was the issue resolved, and if so how?

**Comment by laosijikaichele** [comment]
@Scottmitch from this issue https://github.com/netty/netty/issues/7585 , I need to install additional packages on my macOS, I can not do this for some security reason. So I switched to netty-docker env and try to make it running in docker, but I still got `mvn` failed under the docker env, please refer this issue https://github.com/netty/netty/issues/7616.
