### ISSUE TITLE
mvn test failed under netty docker environment

### ISSUE THREAD

**Issue by laosijikaichele** [netty/netty#7616]
### Expected behavior
`mvn test` should run successfully in docker environment
### Actual behavior
`mvn test` failed with many failures and errors
 the failure occurred in `handler` module:
> Tests run: 1185, Failures: 172, Errors: 332, Skipped: 134

console log is attached here:
[netty-docker-mvn-test-console.log](https://github.com/netty/netty/files/1658801/netty-docker-mvn-test-console.log)

### Steps to reproduce
- git clone netty 4.1 branch code
- go to path `netty/docker`
- run command from https://github.com/netty/netty/blob/4.1/docker/README.md
- after docker started, run `mvn clean test` inside docker under path `/code/`

### Minimal yet complete reproducer code (or URL to code)
should not matter
### Netty version
4.1
### JVM version (e.g. `java -version`)

> java version "1.8.0_91"
> Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

> docker version
> Client:
>  Version:	17.12.0-ce
>  API version:	1.35
>  Go version:	go1.9.2
>  Git commit:	c97c6d6
>  Built:	Wed Dec 27 20:03:51 2017
>  OS/Arch:	darwin/amd64
> 
> Server:
>  Engine:
>   Version:	17.12.0-ce
>   API version:	1.35 (minimum version 1.12)
>   Go version:	go1.9.2
>   Git commit:	c97c6d6
>   Built:	Wed Dec 27 20:12:29 2017
>   OS/Arch:	linux/amd64
>   Experimental:	false

### OS version (e.g. `uname -a`)
macOS 10.13.2 (17C205)

Do I need to install additional dependencies on my host machine?  I think the host dependencies should not affect the docker environment.

**Comment by normanmaurer** [comment]
Again I can not reproduce :( I can build Netty within docker and it’s exactly how the releases are done as well

**Comment by laosijikaichele** [comment]
@normanmaurer , I switched to google cloud instance with following env:

**Docker version**

> sudo docker version
> Client:
>  Version:       17.12.0-ce
>  API version:   1.35
>  Go version:    go1.9.2
>  Git commit:    c97c6d6
>  Built: Wed Dec 27 20:10:14 2017
>  OS/Arch:       linux/amd64
> Server:
>  Engine:
>   Version:      17.12.0-ce
>   API version:  1.35 (minimum version 1.12)
>   Go version:   go1.9.2
>   Git commit:   c97c6d6
>   Built:        Wed Dec 27 20:12:46 2017
>   OS/Arch:      linux/amd64
>   Experimental: false

**OS version (e.g. uname -a)**

> Linux 84b6263c923b 4.12.8-1.el7.elrepo.x86_64 #1 SMP Thu Aug 17 09:11:11 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

**then do the same docker setting up steps, after run `mvn clean compile` inside docker, got following errors:**
[netty-docker-in-GCP-mvn-compile-console.log](https://github.com/netty/netty/files/1659067/netty-docker-in-GCP-mvn-compile-console.log)

**Comment by normanmaurer** [comment]
hmm... I dont see the compile error in the output. Can you add `-X` when you run the `mvn` command ?

Also not sure it really matters but can you try `mvn clean package`

**Comment by laosijikaichele** [comment]
@normanmaurer  I run `mvn clean package -X`, the errors in output is attached here:
[netty-docker-in-GCP-mvn-clean-package-console.log](https://github.com/netty/netty/files/1659095/netty-docker-in-GCP-mvn-clean-package-console.log)

**Comment by normanmaurer** [comment]
Hm... are you sure you have a clean checkout of the 4.1 branch ? what sha are you on ?

**Comment by laosijikaichele** [comment]
> [root@4e5d46a2a2cf code]# git status
>    On branch 4.1
> nothing to commit (working directory clean)

**Comment by laosijikaichele** [comment]
this is the cmd histrory I set up netty docker env in GCP instance(I delete some wrong typing cmds):

> history
> 39 sudo git clone https://github.com/netty/netty.git
> 41 cd netty/
> 42 git status  **(this shows i am in 4.1 branch)**
> 43 cd docker/
> 47 sudo docker build -f Dockerfile-netty-centos6 . -t netty-centos6
> 50 sudo docker images
> 57 sudo docker run -it -v ~/.m2:/root/.m2 -v ~/.ssh:/root/.ssh -v ~/.gnupg:/root/.gnupg -v
> pwd:/code -w /code netty-centos6 bash

**Comment by laosijikaichele** [comment]
@normanmaurer  I record the process as a video:
https://www.youtube.com/watch?v=1Z3Yz6uEVA0
Is there any step wrong?

**Comment by normanmaurer** [comment]
I still can not reproduce... it just works here :(

**Comment by JLofgren** [comment]
I am also having issues building. In various environments I get various build errors.  Even using the docker process I get one error when building in Linux Mint 18.3, and a different error when building in CentOS 7. And BTW, they are both different errors than @laosijikaichele is getting.

**Comment by normanmaurer** [comment]
@JLofgren I only tested it on macOS so far and this works (at least for me...)

**Comment by JLofgren** [comment]
What linux distro(s) are known to work?

**Comment by normanmaurer** [comment]
@JLofgren like I said I only used it on macOS so far.

**Comment by JLofgren** [comment]
Do you build natively in MacOS or using the docker build process?

**Comment by normanmaurer** [comment]
Both

**Comment by normanmaurer** [comment]
@laosijikaichele Please try to use docker-compose as explained in our docs now. I tested it on linux and macOS and it "just works". Please reopen if you still see issues.
