### ISSUE TITLE
ObjectCleanerThread not be closed

### ISSUE THREAD

**Issue by hank-whu** [netty/netty#7617]
### Netty version
4.1.20.Final

### JVM version (e.g. `java -version`)
9.0.1

### OS version (e.g. `uname -a`)
Windows 10

Non-finished threads:

Thread[DestroyJavaVM,5,main]

Thread[ObjectCleanerThread,1,main]
  at java.base@9.0.1/java.lang.Object.wait(Native Method)
  at java.base@9.0.1/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
  at app//io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:52)
  at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  at java.base@9.0.1/java.lang.Thread.run(Thread.java:844)

**Comment by normanmaurer** [comment]
@hank-whu it should be after 10 seconds maximum if there are no more references: https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/ObjectCleaner.java#L52

Are you sure there are no more references hold ?

**Comment by johnou** [comment]
@normanmaurer why isn't there a break in the loop if the thread is interrupted? wouldn't that indicate the application is shutting down?

**Comment by normanmaurer** [comment]
@johnou I think it should still cary on cleanup until there are no more references as otherwise we may leak direct memory etc. It should only exit once the `LIVE_SET` is empty imho.

**Comment by johnou** [comment]
@normanmaurer then how about a daemon thread? Allowing the JVM process to terminate in a timely manner.

**Comment by normanmaurer** [comment]
@johnou we decided against a daemon thread to make harder guarantees about cleanup. If it would be a deamon thread we may leak direct memory for example when someone hot-deploy stuff. 

Also /cc @Scottmitch , as both of us had the discussion :)

**Comment by Scottmitch** [comment]
Yes we considered daemon but decided against it. Although I would expect most OSes we run on will clean up process resources after the process dies we can’t be sure of this. Since we allocate native resources outside the scope of the JVM the more conservative approach is to go non daemon. The mitigation factor was to have a timeout on the poll. This may cause issues if some of the jvm shutdown processing contains references to items registered in the cleaner but I don’t think this is likely.

**Comment by hank-whu** [comment]
@normanmaurer 
shoud i wait 10 seconds after shutdown the EventLoopGroup ?
it doesn't seem like a good way.
can add a "shutdown(long mills)" method to ObjectCleanerThread ?

**Comment by normanmaurer** [comment]
@hank-whu it may take up to 10 seconds... That said you can tune this with a system property:

https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/ObjectCleaner.java#L36

**Comment by johnou** [comment]
@normanmaurer it can actually stop the jvm from terminating, I'll post more details shortly.

**Comment by normanmaurer** [comment]
Thx...

**Comment by hank-whu** [comment]
Ensure all threads are closed, "wait some time" is the only way.
I think this is not very good. 
I need a method to ensure all threads are closed.

**Comment by johnou** [comment]
@normanmaurer I would expect something like this to exit gracefully without an explicit System.exit call.

```java
public class Main {

    public static void main(String[] args) {
        ByteBuf byteBuf = PooledByteBufAllocator.DEFAULT.buffer();
        byteBuf.release();
        System.gc();
        System.runFinalization();
        // hangs because ObjectCleanerThread is not a daemon thread / LIVE_SET is not empty.. additionally sigterm also 
    }
}
```

**Comment by normanmaurer** [comment]
@hank-whu @johnou https://github.com/netty/netty/pull/7627 PTAL

**Comment by Scottmitch** [comment]
@johnou - interesting example! interesting implication of having the main thread running the `main` method is objects referenced from here may not be GC'ed, or at least not detectable by the application.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7627

**Comment by slandelle** [comment]
Hi @normanmaurer Any ETA for the next release? This issue is hurting us pretty badly :(

**Comment by normanmaurer** [comment]
Hopefully tomorrow, latest Friday.

**Comment by slandelle** [comment]
Wow, great, you rock!

**Comment by mcfongtw** [comment]
Hi, is this fix included in any 4.1.x release yet?

**Comment by fenik17** [comment]
@mcfongtw yep. since 4.1.21.

**Comment by mcfongtw** [comment]
Thanks. @fenik17
