### ISSUE TITLE
method `io.netty.handler.codec.http2.Http2ConnectionHandler#flush` not compatible with previous version

### ISSUE THREAD

**Issue by laosijikaichele** [netty/netty#7630]
After upgraded netty from 4.1.6 to 4.1.20, the following code can not compile:

> try {
>     flush(thisContext); // **this call the flush(..) method extended from Http2ConnectionHandler**
> } catch (Http2Exception e) {  // **can not compile after upgraded.**
>     log.error(e.getMessage(),e);
> }
may be is because of this commit: https://github.com/netty/netty/commit/74f24a5c19f8f351e9c6a7a84bdd9fbcc7a07ada

**Comment by normanmaurer** [comment]
What you mean with can not Compile ? It compiles here and on the CI without any problems... if you talk about that the method signature changes then it’s ok as the class is marked as unstable

**Comment by laosijikaichele** [comment]
sorry I did not notice the @UnstableApi annotation. 
`not compile`  means when I run `mvn compile`  on the code above, it failed with error:`can not throw io.netty.handler.codec.http2.Http2Exception`.
anyway, this is OK because @UnstableApi annotation. I will adjust my own code and close this issue. 
Sorry for my mindless.
