### ISSUE TITLE
The Http2MultiplexCodec StreamChannel will fire channelInactive without the channel.isOpen method reporting false

### ISSUE THREAD

**Issue by bryce-anderson** [netty/netty#7638]
### Expected behavior

When part of a HTTP/2 `StreamChannel` the `StreamChannel.isOpen()` method should report `false` within a call to a `ChannelInboundHandler`s `channelInactive` method.

### Actual behavior

Within the `channelInactive` method, `ctx.channel().isOpen() == true`

### Minimal yet complete reproducer code (or URL to code)

Within the `Http2MultiplexCodecTest:
```java
    @Test
    public void channelClosedWhenInactiveFired() {
        LastInboundHandler inboundHandler = streamActiveAndWriteHeaders(inboundStream);
        Http2StreamChannel childChannel = (Http2StreamChannel) inboundHandler.channel();

        final AtomicBoolean channelWasOpen = new AtomicBoolean(false);

        childChannel.pipeline().addLast(new ChannelInboundHandlerAdapter() {
            @Override
            public void channelInactive(ChannelHandlerContext ctx) throws Exception {
                channelWasOpen.set(ctx.channel().isOpen());
                super.channelInactive(ctx);
            }
        });

        childChannel.close().syncUninterruptibly();
        assertFalse(channelWasOpen.get());
    }
```

Result: 
java.lang.AssertionError
io.netty.handler.codec.http2.Http2MultiplexCodecTest.channelClosedWhenInactiveFired(Http2MultiplexCodecTest.java:471)

### Netty version

4.1

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_152"

### OS version (e.g. `uname -a`)
Darwin

**Comment by bryce-anderson** [comment]
See the discussion in https://github.com/netty/netty/pull/7631 for more details including a possible solution.

**Comment by normanmaurer** [comment]
@bryce-anderson thanks a lot! I will fix it :)

**Comment by normanmaurer** [comment]
@bryce-anderson PTAL https://github.com/netty/netty/pull/7640

**Comment by normanmaurer** [comment]
Fixed
