### ISSUE TITLE
The Promise passed to a StreamChannel.close(..) call will report channel().isOpen() == true in its listeners

### ISSUE THREAD

**Issue by bryce-anderson** [netty/netty#7641]
### Expected behavior

When the promise is completed, it's channel should report being closed in the handler.

### Actual behavior

The channel still reports open.

### Minimal yet complete reproducer code (or URL to code)
Test case added to `Http2MultiplexCodecTest`:
```java
    @Test
    public void channelClosedWhenClosePromiseCompletes() {
        LastInboundHandler inboundHandler = streamActiveAndWriteHeaders(inboundStream);
        Http2StreamChannel childChannel = (Http2StreamChannel) inboundHandler.channel();

        assertTrue(childChannel.isOpen());
        assertTrue(childChannel.isActive());

        final AtomicBoolean channelOpen = new AtomicBoolean(true);

        final ChannelPromise p = childChannel.newPromise();

        p.addListener(new ChannelFutureListener() {
            @Override
            public void operationComplete(ChannelFuture future) throws Exception {
                channelOpen.set(future.channel().isOpen());
            }
        });

        childChannel.close(p).syncUninterruptibly();

        assertFalse(channelOpen.get());
    }
```

### Netty version
4.1

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_152"

### OS version (e.g. `uname -a`)
Darwin

**Comment by bryce-anderson** [comment]
See https://github.com/netty/netty/pull/7640 for the discussion. The solution is to change the order of promise satisfaction [here](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java#L893) as `ch.isClose()` is predicated on the state of the `StreamChannel`s `closePromise` [here](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java#L511).

**Comment by bryce-anderson** [comment]
Btw, I'm happy to contribute a fix for this. We make heavy use of Netty and are building out on these new API's so I'd personally love to get more involved. That said, fft just fix it if you think its expedient.

**Comment by normanmaurer** [comment]
Sounds good 👌 that said I think you should not re-order the promises but use an extra volatile boolean that is updated before any of the promises is notified. This way the notifications of the promises is also consistent with AbstractChannel and so other transports...

So please provide a PR with the suggestion I made 👍

**Comment by bryce-anderson** [comment]
Awesome. I'll work on it once https://github.com/netty/netty/pull/7640 and https://github.com/netty/netty/pull/7631 have merged since they will certainly conflict.

**Comment by bryce-anderson** [comment]
Actually, I need some clarification: it looks to me like `AbstractChannel` actually closes the `closeFuture` _before_ the passed `promise` in the `doClose0` method [here](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/AbstractChannel.java#L761) so reversing the order of promise completion seems like the right thing to do.

This can be demonstrated with the following test which can be added to `NioSocketChannelTest`:
```java
@Test(timeout = 3000)
    public void testOrderOfClosePromises() throws IOException {
        NioEventLoopGroup group = new NioEventLoopGroup(1);
        ServerSocket socket = new ServerSocket();
        socket.bind(new InetSocketAddress(0));
        Socket accepted = null;
        try {
            Bootstrap sb = new Bootstrap();
            sb.group(group).channel(NioSocketChannel.class);
            sb.handler(new ChannelInboundHandlerAdapter());

            SocketChannel channel = (SocketChannel) sb.connect(socket.getLocalSocketAddress())
                .syncUninterruptibly().channel();

            accepted = socket.accept();

            final AtomicInteger counter = new AtomicInteger(0);

            final AtomicInteger onClosePromiseCount = new AtomicInteger(0);
            final AtomicInteger passedClosePromiseCount = new AtomicInteger(0);

            channel.closeFuture().addListener(new ChannelFutureListener() {
                @Override
                public void operationComplete(ChannelFuture future) throws Exception {
                    onClosePromiseCount.set(counter.getAndIncrement());
                }
            });

            final ChannelPromise f = channel.newPromise();
            f.addListener(new ChannelFutureListener() {
                @Override
                public void operationComplete(ChannelFuture future) throws Exception {
                    passedClosePromiseCount.set(counter.getAndIncrement());
                }
            });

            channel.close(f).syncUninterruptibly();

            assertEquals(0, onClosePromiseCount.get());
            assertEquals(1, passedClosePromiseCount.get());
        } finally {
            if (accepted != null) {
                try {
                    accepted.close();
                } catch (IOException ignore) {
                    // ignore
                }
            }
            try {
                socket.close();
            } catch (IOException ignore) {
                // ignore
            }
            group.shutdownGracefully();
        }
    }
```
with the nugget being the asserts right before the finally block.

**Comment by Scottmitch** [comment]
just catching up ... see https://github.com/netty/netty/pull/7643 ... but as you mentioned there are a bunch of PRs touching the same area at the moment. My suggestion would be to do the following:

1. @normanmaurer - resolve https://github.com/netty/netty/pull/7631#discussion_r164259753 ... since the intention of this PR was to make things more consistent with AbstractChannel anyways.
2. I will revert the code changes in PR https://github.com/netty/netty/pull/7643 ... and we can pull in the unit tests

Then we should be good. wdyt?

**Comment by bryce-anderson** [comment]
sgtm. Thanks @Scottmitch.

**Comment by normanmaurer** [comment]
@bryce-anderson you are right... I should not write suggestions from my phone ;)

**Comment by normanmaurer** [comment]
Fixed...

**Comment by bryce-anderson** [comment]
@normanmaurer no worries, and thanks again!
