### ISSUE TITLE
Determination of MAX_DIRECT_MEMORY in io.netty.util.internal.PlatformDependent fails on z/OS

### ISSUE THREAD

**Issue by jo-kin** [netty/netty#7654]
### Expected behavior
 MAX_DIRECT_MEMORY, which controls later behaviour of Netty , should be initialized with correct value.

### Actual behavior
On z/OS netty initializes this value with 64M, even the direct accessible memory is actually unbounded.

Reason is the way, how the IBM Java VM administrates direct memory. 
The Windows- or Linux-based VMs report the correct final value asking the corresponding APIs , i.e. sun.misc.VM.maxDirectMemory(().
But the IBM JVM on z/OS returns here just the initial start value for accessible direct memory, 64MB, even this is not the final limit. (see [https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.zos.80.doc/diag/appendixes/cmdline/xxmaxdirectmemorysize.html](url)
The IBM JVM increments this value on demand in 32MB steps.

Netty asks only once in a static initializer for this value and, for z/OS, erroneously assumes, that would be the final value. 
The so unnecessarily bounded value of 64M leads finally to 
> io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16921 byte(s) of direct 
 memory (used: 67092277, max: 67108864)
 at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:615)

Conclusion: on z/OS the used APIs offer not the desired correct value for available direct memory.

Suggested solution:
the heuristic in io.netty.util.internal.PlatformDependent.maxDirectMemory0() has to consider the System.os. In case of z/OS the first try with sun.misc.VM.maxDirectMemory() is to skip. the following search for -XX:MaxDirectMemorySize or Runtime.maxMem() may offer the correct value.

by the way: limit the available direct memory with -XX:MaxDirectMemorySize=512M helps as workarround. Adding this argument at start the IBM VM returns 512M as initial value which is quite the correct final value.

### Steps to reproduce
run added code on z/OS

### Minimal yet complete reproducer code (or URL to code)
This code is a copy of  io.netty.util.internal.PlatformDependent.maxDirectMemory0(), 
needed method added, Shortcuts removed, some System.out.println() added.

```
import java.lang.reflect.Method;
import java.security.AccessController;
import java.security.PrivilegedAction;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class JVMMaxDirectMemory
{
   private static final Pattern MAX_DIRECT_MEMORY_SIZE_ARG_PATTERN = Pattern.compile(
      "\\s*-XX:MaxDirectMemorySize\\s*=\\s*([0-9]+)\\s*([kKmMgG]?)\\s*$");

   public static void main(String[] args)
   {
      long mem = maxDirectMemory0();
   }

   private static long maxDirectMemory0()
   {
      ClassLoader systemClassLoader = null;
      try
      {
         // Try to get from sun.misc.VM.maxDirectMemory() which should be most accurate.
         systemClassLoader = getSystemClassLoader();
         Class<?> vmClass = Class.forName("sun.misc.VM", true, systemClassLoader);
         Method m = vmClass.getDeclaredMethod("maxDirectMemory");
         long maxDirectMemory = ((Number) m.invoke(null)).longValue();
         System.out.println("invoking sun.misc.VM.maxDirectMemory() offers: " + maxDirectMemory);
      }
      catch (Throwable ignored)
      {
         System.out.println("invoking sun.misc.VM.maxDirectMemory() fails with: " + ignored.toString());
      }

      try
      {
         // Now try to get the JVM option (-XX:MaxDirectMemorySize) and parse it.
         // Note that we are using reflection because Android doesn't have these classes.
         Class<?> mgmtFactoryClass = Class.forName(
            "java.lang.management.ManagementFactory", true, systemClassLoader);
         Class<?> runtimeClass = Class.forName(
            "java.lang.management.RuntimeMXBean", true, systemClassLoader);

         Object runtime = mgmtFactoryClass.getDeclaredMethod("getRuntimeMXBean").invoke(null);   
         List<String> vmArgs = (List<String>) runtimeClass.getDeclaredMethod("getInputArguments").invoke(runtime);

         for (int i = vmArgs.size() - 1; i >= 0; i--)
         {
            Matcher m = MAX_DIRECT_MEMORY_SIZE_ARG_PATTERN.matcher(vmArgs.get(i));
            if (!m.matches())
            {
               continue;
            }

            long maxDirectMemory = Long.parseLong(m.group(1));
            switch (m.group(2).charAt(0))
            {
               case 'k':
               case 'K':
                  maxDirectMemory *= 1024;
                  break;
               case 'm':
               case 'M':
                  maxDirectMemory *= 1024 * 1024;
                  break;
               case 'g':
               case 'G':
                  maxDirectMemory *= 1024 * 1024 * 1024;
                  break;
            }
           System.out.println("invoking java.lang.management.RuntimeMXBean.getInputArguments() offers: " + maxDirectMemory);
            break;
         }       
      }
      catch (Throwable ignored)
      {
         System.out.println("invoking java.lang.management.RuntimeMXBean.getInputArguments() fails with: " + ignored.toString());
      }

      long maxDirectMemory = Runtime.getRuntime().maxMemory();
      System.out.println("invoking Runtime.getRuntime().maxMemory() offers: " + maxDirectMemory);

      return maxDirectMemory;
   }

   static ClassLoader getSystemClassLoader()
   {
      if (System.getSecurityManager() == null)
      {
         return ClassLoader.getSystemClassLoader();
      }
      else
      {
         return AccessController.doPrivileged(new PrivilegedAction<ClassLoader>()
         {
            @Override
            public ClassLoader run()
            {
               return ClassLoader.getSystemClassLoader();
            }
         });
      }
   }
```

Output:

> 
>  WINDOWS:
> --------------
> java -cp . JVMMaxDirectMemory
> invoking sun.misc.VM.maxDirectMemory() offers: 1882718208
> invoking java.lang.management.RuntimeMXBean.getInputArguments() offers: 1882718208
> invoking Runtime.getRuntime().maxMemory() offers: 1882718208
> 
> z/OS:
> --------------
> $ java -cp . JVMMaxDirectMemory
> invoking sun.misc.VM.maxDirectMemory() offers: 67108864
> invoking java.lang.management.RuntimeMXBean.getInputArguments() offers: 67108864
> invoking Runtime.getRuntime().maxMemory() offers: 536870912
> 
> z/OS plus -XX:MaxDirectMemorySize:
> ---------------------------------
> $ java -XX:MaxDirectMemorySize=250M -cp . JVMMaxDirectMemory
> invoking sun.misc.VM.maxDirectMemory() offers: 262144000
> invoking java.lang.management.RuntimeMXBean.getInputArguments() offers: 262144000
> invoking Runtime.getRuntime().maxMemory() offers: 536870912

### Netty version
occured with 4.1.13, but involved code is unchanged until 4.1.20

### JVM version (e.g. `java -version`)
$ java -version
java version "1.7.0"
Java(TM) SE Runtime Environment (build pmz3170_27sr3fp40-20160422_01(SR3 FP40))
IBM J9 VM (build 2.7, JRE 1.7.0 z/OS s390-31 20160406_298393 (JIT enabled, AOT enabled)
J9VM - R27_Java727_SR3_20160406_0942_B298393
JIT  - tr.r13.java_20160328_114186
GC   - R27_Java727_SR3_20160406_0942_B298393
J9CL - 20160406_298393)
JCL - 20160421_01 based on Oracle jdk7u101-b14
$

### OS version (e.g. `uname -a`)
 - - - - - - - - - - - - - - - - - - - - - - - - - - -
 -    Welcome to  Unix System Services of z / O S    -
 -             Version 2 Release 2                   -
 - - - - - - - - - - - - - - - - - - - - - - - - - - -
$ uname -a
OS/390 ZOSU 25.00 04 2828
$

**Comment by normanmaurer** [comment]
@jo-kin I have no access to z/OS . Would you be interested to submit a PR ?

**Comment by jo-kin** [comment]
@normanmaurer Already thought so, too. Currently I try to persuade my employer to get involved with Netty development. It's obvious, that I am not the owner of the used mainframe...
Give me some time, please.

**Comment by normanmaurer** [comment]
@jo-kin thanks keep me posted.

**Comment by normanmaurer** [comment]
@jo-kin any updates ?

**Comment by normanmaurer** [comment]
@jo-kin ping

**Comment by jo-kin** [comment]
@normanmaurer Sorry, my idea to support netty stranded at Legal Affairs. Additinally R&D did not want to open a bug ticket for the described behaviour of  IBM's JVM due to just opening a IBM Service Request is not for free. Mainframe has it's own rules and nothing is cheap there...

The only suggestion i can do is to offer an example how io.netty.util.internal.PlatformDependent.maxDirectMemory0() could be changed to handle z/OS's quirks. Perhaps someone has the pity to make a Pull Request out of it.  Anyway, this issue could be closed from my view.

Proposal:

`   private static long maxDirectMemory0() {
        long maxDirectMemory = 0;
        ClassLoader systemClassLoader = null;
        try {
            // if given -XX:MaxDirectMemorySize rulez (even on z/OS):
            // So try first to get the JVM option (-XX:MaxDirectMemorySize) and parse it.
            // Note that we are using reflection because Android doesn't have these classes.
            Class<?> mgmtFactoryClass = Class.forName(
                    "java.lang.management.ManagementFactory", true, systemClassLoader);
            Class<?> runtimeClass = Class.forName(
                    "java.lang.management.RuntimeMXBean", true, systemClassLoader);

            Object runtime = mgmtFactoryClass.getDeclaredMethod("getRuntimeMXBean").invoke(null);

            @SuppressWarnings("unchecked")
            List<String> vmArgs = (List<String>) runtimeClass.getDeclaredMethod("getInputArguments").invoke(runtime);
            for (int i = vmArgs.size() - 1; i >= 0; i --) {
                Matcher m = MAX_DIRECT_MEMORY_SIZE_ARG_PATTERN.matcher(vmArgs.get(i));
                if (!m.matches()) {
                    continue;
                }
                maxDirectMemory = Long.parseLong(m.group(1));
                switch (m.group(2).charAt(0)) {
                    case 'k': case 'K':
                        maxDirectMemory *= 1024;
                        break;
                    case 'm': case 'M':
                        maxDirectMemory *= 1024 * 1024;
                        break;
                    case 'g': case 'G':
                        maxDirectMemory *= 1024 * 1024 * 1024;
                        break;
                }
                break;
            }
        } catch (Throwable ignored) {
            // Ignore
        }

        // N.B: IBM VM's implementation of sun.misc.VM.maxDirectMemory() offers initially always only
        // 64M for direct memory independent from real limitation.
        // so skip this for z/OS and use trailing fallback 
       // maxDirectMemory = Runtime.getRuntime().maxMemory();"
        String os1 = System.getProperty("os.name", "").toLowerCase();
        if (!os1.contains("z/os")) {
            try {
                // Try to get from sun.misc.VM.maxDirectMemory() which should be most accurate.
                systemClassLoader = getSystemClassLoader();
                Class<?> vmClass = Class.forName("sun.misc.VM", true, systemClassLoader);
                Method m = vmClass.getDeclaredMethod("maxDirectMemory");
                maxDirectMemory = ((Number) m.invoke(null)).longValue();
            } catch (Throwable ignored) {
                // Ignore
            }

            if (maxDirectMemory > 0) {
                return maxDirectMemory;
            }
        }

        if (maxDirectMemory <= 0) {
            maxDirectMemory = Runtime.getRuntime().maxMemory();
            logger.debug("maxDirectMemory: {} bytes (maybe)", maxDirectMemory);
        } else {
            logger.debug("maxDirectMemory: {} bytes", maxDirectMemory);
        }

        return maxDirectMemory;
    }`

**Comment by normanmaurer** [comment]
@jo-kin PTAL https://github.com/netty/netty/pull/7886

**Comment by jpfourny** [comment]
FYI, I am able to reproduce this issue on Windows with the latest IBM Java 8 JRE. Setting '-XX:MaxDirectMemorySize=512M' works around the problem, however. I am running Spark 2.2, which ships with Netty-all-4.0.43.Final. It does not appear to be specific to Z/OS.

**Comment by jpfourny** [comment]
Here are the relevant sys props:

java.vendor=IBM Corporation,
java.vendor.url=http://www.ibm.com/,
java.vm.vendor=IBM Corporation,
java.vm.name=IBM J9 VM,
java.vm.specification.name=Java Virtual Machine Specification,
java.vm.specification.vendor=Oracle Corporation,
java.vm.info=JRE 1.8.0 Windows 10 amd64-64 Compressed References 20170812_360168 (JIT enabled, AOT enabled)
J9VM - R28_20170812_0201_B360168
JIT  - tr.r14.java_20170812_360168
GC   - R28_20170812_0201_B360168_CMPRSS
J9CL - 20170812_360168
java.version=1.8.0,
java.runtime.name=Java(TM) SE Runtime Environment,
java.runtime.version=pwa6480sr4fp11-20170823_01 (SR4 FP11),
os.arch=amd64,
os.name=Windows 10

**Comment by jpfourny** [comment]
According to IBM docs:

> By default, the JVM does not set a limit on how much memory is reserved for Direct Byte Buffers. A soft limit of 64 MB is set, which the JVM automatically expands in 32 MB chunks, as required.

There is no hard limit, until -XX:MaxDirectMemorySize is specified on command line. It will keep allocating until the process hits whatever limits are set by the kernel on the process. This is probably a dangerous default policy, IMHO. 

Having Netty enforce a reasonable default limit on direct memory allocation is still a good idea - you just have to pick a value by some other means. However, if you see VM.maxDirectMemory() is higher than your chosen default limit, you should go with the higher one. This means the user probably explicitly configured a limit, and you will want to respect that. That's my two cents.

**Comment by normanmaurer** [comment]
BTW PRs are always welcome

**Comment by normanmaurer** [comment]
@jpfourny could you verify: https://github.com/netty/netty/pull/7966 ?

**Comment by jo-kin** [comment]
To complete this i just add the System.properties from Java running on a Z-System with z/OS 2.2:

 - - - - - - - - - - - - - - - - - - - - - - - - - - -
 -    Welcome to  Unix System Services of            -
 -          z / O S   Version 2 Release 2            -
 - - - - - - - - - - - - - - - - - - - - - - - - - - -

$ java -version
java version "1.7.0"
Java(TM) SE Runtime Environment (build pmz3170_27sr3fp40-20160422_01(SR3 FP40))
IBM J9 VM (build 2.7, JRE 1.7.0 z/OS s390-31 20160406_298393 (JIT enabled, AOT enabled)
J9VM - R27_Java727_SR3_20160406_0942_B298393
JIT  - tr.r13.java_20160328_114186
GC   - R27_Java727_SR3_20160406_0942_B298393
J9CL - 20160406_298393)
JCL - 20160421_01 based on Oracle jdk7u101-b14

$ java -cp . PrintSystemProps

java.vendor: IBM Corporation
sun.java.launcher: SUN_STANDARD
os.name: z/OS
sun.boot.class.path: /usr/lpp/java/J7.1/lib/s390/default/jclSC170/vm.jar:/usr/lpp/java/J7.1/lib/se-service.jar:/usr/lpp/java/J7.1/lib/math.jar:/usr/lpp/java/J7.1/lib/ibmorb.jar:/usr/lpp/java/J7.1/lib/ibmorbapi.jar:/usr/lpp/java/J7.1/lib/ibmcfw.jar:/usr/lpp/java/J7.1/lib/ibmpkcs.jar:/usr/lpp/java/J7.1/lib/ibmcertpathfw.jar:/usr/lpp/java/J7.1/lib/ibmjgssfw.jar:/usr/lpp/java/J7.1/lib/ibmjssefw.jar:/usr/lpp/java/J7.1/lib/ibmsaslfw.jar:/usr/lpp/java/J7.1/lib/ibmjcefw.jar:/usr/lpp/java/J7.1/lib/ibmjgssprovider.jar:/usr/lpp/java/J7.1/lib/ibmjsseprovider2.jar:/usr/lpp/java/J7.1/lib/ibmcertpathprovider.jar:/usr/lpp/java/J7.1/lib/xmldsigfw.jar:/usr/lpp/java/J7.1/lib/xml.jar:/usr/lpp/java/J7.1/lib/charsets.jar:/usr/lpp/java/J7.1/lib/resources.jar:/usr/lpp/java/J7.1/lib/rt.jar:/usr/lpp/java/J7.1/lib/dataaccess.jar:/usr/lpp/java/J7.1/lib/ibmgpu.jar:/usr/lpp/java/J7.1/lib/RACF.jar
java.vm.specification.vendor: Oracle Corporation
java.runtime.version: pmz3170_27sr3fp40-20160422_01 (SR3 FP40)
user.name: xxxxxxx
java.compiler: j9jit27
os.encoding: ISO8859_1
com.ibm.util.extralibs.properties:
com.ibm.jcl.checkClassPath:
user.language: en
com.ibm.oti.vm.bootstrap.library.path: /usr/lpp/java/J7.1/lib/s390/default:/usr/lpp/java/J7.1/lib/s390
sun.boot.library.path: /usr/lpp/java/J7.1/lib/s390/default:/usr/lpp/java/J7.1/lib/s390
java.version: 1.7.0
user.timezone:
com.ibm.system.agent.path: /usr/lpp/java/J7.1/lib/s390
sun.arch.data.model: 32
com.ibm.zero.version: 2
java.endorsed.dirs: /usr/lpp/java/J7.1/lib/endorsed
com.ibm.oti.vm.library.version: 27
sun.jnu.encoding: IBM-1047
file.encoding.pkg: sun.io
file.separator: /
java.specification.name: Java Platform API Specification
com.ibm.packed.version: 2
java.class.version: 51.0
user.country: US
java.home: /usr/lpp/java/J7.1
java.vm.info: JRE 1.7.0 z/OS s390-31 20160406_298393 (JIT enabled, AOT enabled)
J9VM - R27_Java727_SR3_20160406_0942_B298393
JIT  - tr.r13.java_20160328_114186
GC   - R27_Java727_SR3_20160406_0942_B298393
J9CL - 20160406_298393
os.version: 02.02.00
java.awt.fonts:
path.separator: :
java.vm.version: 2.7
java.util.prefs.PreferencesFactory: java.util.prefs.FileSystemPreferencesFactory
user.variant:
java.awt.printerjob: sun.print.PSPrinterJob
sun.io.unicode.encoding: UnicodeBig
awt.toolkit: sun.awt.X11.XToolkit
ibm.signalhandling.sigint: true
user.home: /home/xxxxx
com.ibm.cpu.endian: big
java.specification.vendor: Oracle Corporation
ibm.signalhandling.sigchain: false
sun.security.policy.utf8: false
java.library.path: /usr/lpp/java/J7.1/lib/s390/default:/usr/lpp/java/J7.1/lib/s390:/usr/lpp/java/J7.1/lib/s390/default:/usr/lpp/java/J7.1/lib/s390/j9vm:/usr/lpp/java/J7.1/lib/s390:/usr/lpp/java/J7.1/../lib/s390:/usr/lpp/java/J7.1/lib/s390:.:/lib:/usr/lib:/usr/lpp/Printsrv/lib:/usr/lpp/db2a10/jdbc/lib:/usr/lpp/perl/lib/5.8.7/os390-thread-multi/CORE
java.vendor.url: http://www.ibm.com/
java.vm.vendor: IBM Corporation
platform.notASCII: true
java.fullversion: JRE 1.7.0 IBM J9 2.7 z/OS s390-31 20160406_298393 (JIT enabled, AOT enabled)
J9VM - R27_Java727_SR3_20160406_0942_B298393
JIT  - tr.r13.java_20160328_114186
GC   - R27_Java727_SR3_20160406_0942_B298393
J9CL - 20160406_298393
java.runtime.name: Java(TM) SE Runtime Environment
sun.java.command: PrintSystemProps
java.class.path: .
java.vm.specification.name: Java Virtual Machine Specification
java.vm.specification.version: 1.7
sun.cpu.endian: big
java.io.tmpdir: /tmp
ibm.system.encoding: IBM-1047
os.arch: s390
java.awt.graphicsenv: sun.awt.X11GraphicsEnvironment
ibm.signalhandling.rs: false
java.ext.dirs: /usr/lpp/java/J7.1/lib/ext
user.dir: /home/xxxxx
line.separator:

java.vm.name: IBM J9 VM
com.ibm.oti.shared.enabled: false
com.ibm.vm.bitmode: 32
file.encoding: IBM-1047
com.ibm.oti.jcl.build: 20160406_298393
java.specification.version: 1.7
com.ibm.oti.configuration: scar
$
