### ISSUE TITLE
MqttDecoder incorrectly discards error codes in SubAck messsages

### ISSUE THREAD

**Issue by kirillkh** [netty/netty#7665]
### Expected behavior
The QoS returned from the broker can be 0, 1, 2 or 0x80. 0x80 means an error occurred. 

### Actual behavior
MqttDecoder.decodeSubackPayload() discards error code 0x80 when it performs bitwise AND with 0x03.

### Netty version
Latest git

I think the fix is as simple as changing this line:
`int qos = buffer.readUnsignedByte() & 0x03;`
into this:
`int qos = buffer.readUnsignedByte();
if(qos != 0x80) qos &= 0x03;`

**Comment by normanmaurer** [comment]
Please open a PR with a unit test

**Comment by kirillkh** [comment]
I'm not working with Netty's source code, I'm looking at it in debugger from Vert.x MQTT. Could you do this please?

**Comment by normanmaurer** [comment]
@kirillkh can you at least point me to the right RFC section ?

**Comment by kirillkh** [comment]
@normanmaurer http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Figure_3.26_-

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7685
