### ISSUE TITLE
whether  lastExecutionTime >= deadline changed  lastExecutionTime - deadline >= 0，just because of the possibility of numerical overflow 

### ISSUE THREAD

**Issue by yangzhongj** [netty/netty#7669]
https://github.com/netty/netty/blob/95b9b0af5ca986e07cd48730a1d935af6beee301/common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java#L412

**Comment by normanmaurer** [comment]
Sorry can you add some more details I am not sure I understand the report :(

**Comment by normanmaurer** [comment]
@yangzhongj ping

**Comment by normanmaurer** [comment]
Closing this as there was not response at all
