### ISSUE TITLE
4.1.20 HttpPostMultipartRequestDecoder destroy duplicate

### ISSUE THREAD

**Issue by luastar** [netty/netty#7689]
### Netty version
4.1.20

### 
when use HttpPostMultipartRequestDecoder.destroy=>cleanFiles，it will call factory(DefaultHttpDataFactory).cleanRequestHttpData，and call data.release()【in netty 4.1.19 is data.delete()】 but at the end of destroy call data.release() again。
then get a Exception 
java.lang.IllegalStateException: HttpPostMultipartRequestDecoder was destroyed already

**Comment by doom369** [comment]
@luastar did you use Netty upload example? Could be same issue as I had - https://github.com/netty/netty/issues/7611

**Comment by johnou** [comment]
@doom369 does the upload example need to be fixed?

**Comment by doom369** [comment]
@johnou probably yes. `data.release();` from `readHttpDataChunkByChunk()` of `HttpUploadServerHandler` should be removed. Need to check it. I haven't chance to check.
