### ISSUE TITLE
JVM destroy seems to be broken with 4.1.20.Final

### ISSUE THREAD

**Issue by comtel2000** [netty/netty#7692]
### Expected behavior
JVM must shutdown after close the EventLoopGroup

### Actual behavior
since 4.1.20.Final the VM cleanup/shutdown hangs
all previous netty versions are shutdown the VM as expected
Sometimes there is a:
`Exception in thread "Thread-2" java.lang.IncompatibleClassChangeError`

### Steps to reproduce
- start test Sample
- check if JVM still runs

### Minimal yet complete reproducer code
```java
public class Sample {

  public static void main(String[] args) {

    EventLoopGroup group = new NioEventLoopGroup();
    try {
      Bootstrap b = new Bootstrap();
      b.group(group).channel(NioSocketChannel.class).remoteAddress(new InetSocketAddress("localhost", 0)).handler(new ChannelInitializer<SocketChannel>() {
        @Override
        public void initChannel(SocketChannel ch) throws Exception {
          ch.pipeline().addLast(new LoggingHandler());
        }
      });

      ChannelFuture f = b.connect().sync();

      f.channel().closeFuture().sync();
    } catch (InterruptedException e) {
      e.printStackTrace();
    } finally {
      group.shutdownGracefully();
    }
  }
}
```
### Netty version
4.1.20.Final

### JVM version
JDK 1.8-162

### OS version
Windows 10 x64

**Comment by slandelle** [comment]
This has already been reported as #7617 and fix has been shipped in 4.1.21 that was released today.

**Comment by comtel2000** [comment]
fixed, thx

**Comment by ngocdaothanh** [comment]
> 4.1.21 that was released today

Thanks. Can you publish that news to the Netty home page?

**Comment by normanmaurer** [comment]
On my to do list for tomorrow.... ran out of time today
