### ISSUE TITLE
HttpHeaders::get - missing break

### ISSUE THREAD

**Issue by fabienrenaud** [netty/netty#7693]
### Expected behavior

Code should exit loop as soon as header matches input string.

### Actual behavior

Code loops through all headers, always. When header name is present more than once, the last value is returned instead of the first.

### Steps to reproduce

Read the code:
```java
HeaderEntry<K, V> e = entries[i];
V value = null;
// loop until the first header was found
while (e != null) {
    if (e.hash == h && hashingStrategy.equals(name, e.key)) {
        value = e.value; // need a break here.
    }

    e = e.next;
}
return value;
```

https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/DefaultHeaders.java#L127

Notice also how the comment doesn't match the implemented behavior.

### Netty version

master
https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/DefaultHeaders.java#L127

**Comment by normanmaurer** [comment]
@fabienrenaud can you provide a PR with fix and unit test ?

**Comment by fabienrenaud** [comment]
Nvm. Implementation actually hashes headers by keys so the iteration is per-header and not for all headers.
Implementation is fine.
Closing.

**Comment by ankurdhama** [comment]
> Nvm. Implementation actually hashes headers by keys so the iteration is per-header and not for all headers.
> Implementation is fine.
> Closing.

I think there should still be a break inside the if block. If you do:
```
headers.add("A","a")
headers.add("A","b")
```
Then, `headers.get("A")` will return "a", ideally it should return "b".

**Comment by normanmaurer** [comment]
@ankurdhama I dont think so... IMHO it should return the first header value.
