### ISSUE TITLE
Lack of Immediate-state futures

### ISSUE THREAD

**Issue by mdindoffer** [netty/netty#7708]
Netty's ChannelFutures are a weaker versions of Guava's ListenableFutures. However, they do lack immediately-complete implementations such as Guava's [ImmediateCancelledFuture](https://google.github.io/guava/releases/23.0/api/docs/com/google/common/util/concurrent/Futures.html#immediateCancelledFuture--) and [ImmediateFailedFuture](https://google.github.io/guava/releases/23.0/api/docs/com/google/common/util/concurrent/Futures.html#immediateFailedFuture-java.lang.Throwable-). This hurts proper multithreaded designs.

For example, consider a method to open a TCP connection to a server:
```java
public synchronized ChannelFuture openConnection() {
    ...
    return bootstrap.connect("127.0.0.1", "4321");
}
```
It may be called by a number of threads simultaneously. The first caller connects to a server and returns the associated ChannelFuture. However, the successive invocations that may come afterwards should see that a connection has either already been established, or is being established and return with something like the `ImmediateCancelledFuture`.

Netty already has a `FailedChannelFuture`, however its constructor is package-private and requires `Channel` and `EventExecutor` as its arguments. This prevents it from being used in aforementioned scenario.

**Comment by slandelle** [comment]
What about `new DefaultPromise<T>(ImmediateEventExecutor.INSTANCE).setFailure()`?

**Comment by Scottmitch** [comment]
As you mentioned we do have `newSucceededFuture` and `newFailedFuture` [1], however the notification is tied to an EventLoop.  So if you wanted the notification to always be on the calling thread you should use `ImmediateEventExecutor.INSTANCE` as suggested above (https://github.com/netty/netty/issues/7708#issuecomment-364861505). Unfortunately the current APIs don't allow for overriding of the `EventLoop` during construction. In terms of requiring a `Channel` ... we plan on re-visiting the `Future`/`ChannelFuture` APIs in the next major release, but that is some time away.

[1] https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/ChannelOutboundInvoker.java#L242-L254

**Comment by normanmaurer** [comment]
Let me close this for now... Please re-open if the suggestion by @slandelle / @Scottmitch not works for you
