### ISSUE TITLE
DefaultHeaders does not correctly implement interface

### ISSUE THREAD

**Issue by jkinkead** [netty/netty#7710]
### Expected behavior

One-argument convert-and-get methods (`get{Byte,Double,Float,Int,Long,Short}`) should return `null` when invoked on a header that can't be converted, per the documentation (e.g. [for `getInt(String)`](https://github.com/netty/netty/blob/4f982be91e6d61c7c7a9d8d63115e0ebe65b2774/codec/src/main/java/io/netty/handler/codec/Headers.java#L175-L176)).

Similarly, two-argument convert-and-get methods should return the default value provided when the header can't be converted.

### Actual behavior

Conversion getter methods throw `NumberFormatException`.

### Steps to reproduce

Set a header to a non-numeric value, then attempt to read it as a number.

### Minimal yet complete reproducer code (or URL to code)

```java
io.netty.handler.codec.http2.DefaultHttp2Headers headers = new io.netty.handler.codec.http2.DefaultHttp2Headers();

headers.set("example", "abc");                                                                  

// Throws NumberFormatException, counter to documentation.    
int value = headers.getInt("example", 123); 
```

### Netty version

4.1

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7715

**Comment by normanmaurer** [comment]
@jkinkead please check https://github.com/netty/netty/pull/7715

**Comment by jkinkead** [comment]
Awesome, thanks for the quick fix! It looks good barring other reviewer's comment (should catch `RuntimeException`).

It might be worth adding docs to [the converter interface](https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/ValueConverter.java) for the exceptions.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7715

**Comment by normanmaurer** [comment]
I will also update the interface with some docs.
