### ISSUE TITLE
DefaultHttp2Headers has inconsistent handling of `getBoolean`.

### ISSUE THREAD

**Issue by jkinkead** [netty/netty#7717]
### Expected behavior

`getBoolean` should have clearly-documented semantics, and they should be consistent.

`getBoolean` should return the same truth value for the same string value, regardless of the underlying type.

### Actual behavior

`AsciiString` values use a [null-byte-check](https://github.com/netty/netty/blob/4f982be91e6d61c7c7a9d8d63115e0ebe65b2774/common/src/main/java/io/netty/util/AsciiString.java#L1217-L1219) to determine truthfulness.

Other `CharSequence`s use [`Boolean.parseBoolean`](https://github.com/netty/netty/blob/4f982be91e6d61c7c7a9d8d63115e0ebe65b2774/codec/src/main/java/io/netty/handler/codec/CharSequenceValueConverter.java#L68-L73), which treats [only strings matching "true"](https://docs.oracle.com/javase/9/docs/api/java/lang/Boolean.html#parseBoolean-java.lang.String-) as truthful (case-insensitive).

### Steps to reproduce

Store any string that isn't a `"true"` variant as an `AsciiString` and `String` in a `DefaultHeaders` implementation, and fetch the value using `getBoolean`.

### Minimal yet complete reproducer code (or URL to code)

```java
// Extends to DefaultHeaders.
io.netty.handler.codec.http2.DefaultHttp2Headers headers =
    new io.netty.handler.codec.http2.DefaultHttp2Headers();

headers.set("string", "false");
headers.set("ascii-string", new io.netty.util.AsciiString("false"));

// Returns false.
headers.getBoolean("string", false);
// Returns true.
headers.getBoolean("ascii-string", false);
```

### Netty version

4.1

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7720
