### ISSUE TITLE
JsonPbjectDecoder 4.1.21.Final

### ISSUE THREAD

**Issue by ManuelPivotal** [netty/netty#7722]
### Expected behavior
Send a set of JSON objects, for example 20 big json objects of 1300 bytes each, using netcat and a file

### Actual behavior
if a JSON object is between 2 buffers, the decoding stops.

### Steps to reproduce
Create a set of 20 json objects of size 1300 bytes each, write a server using the JsObjectDecoder, only the first 10 will arrive and nothing else on this channel

### Minimal yet complete reproducer code (or URL to code)
The fix I did is : 
in the JsonObjectDecoder (line 93)
        if (this.idx > in.readerIndex() && lastReaderIndex != in.readerIndex()) {
            this.idx = in.readerIndex();
            if (state == ST_DECODING_ARRAY_STREAM) {
                insideString = false;
                openBraces = 1;
            } else if(state == ST_DECODING_NORMAL) {
                insideString = false;
                openBraces = 0;
            }
        }
instead of the original
        if (this.idx > in.readerIndex() && lastReaderIndex != in.readerIndex()) {
            this.idx = in.readerIndex();
            if (state == ST_DECODING_ARRAY_STREAM) {
                insideString = false;
                openBraces = 1;
            }
        }
works.
That is because you go back to the beginning of the json object to add it to the out list, but if the openBraces is > 0, it never goes back to 0

Thanks,
Manuel

### Netty version
4.1.21.FINAL

### JVM version (e.g. `java -version`)
8
### OS version (e.g. `uname -a`)
Mac OS

**Comment by normanmaurer** [comment]
@ManuelPivotal can you just open a PR with the fix + test case ?

**Comment by ManuelPivotal** [comment]
sure, what is a PR :-) ?

**Comment by normanmaurer** [comment]
@ManuelPivotal https://help.github.com/articles/about-pull-requests/ :) Basically do the change and submit it so we can pull it in

**Comment by ManuelPivotal** [comment]
I see. As it was not working, I took the JsonObjectDecoder and integrated it in my project to debug it locally, I have not changed the original class. I can pull and change it if you want, while adding a test case

**Comment by normanmaurer** [comment]
yes please

**Comment by ManuelPivotal** [comment]
Ok, sorry for the delay.
I wrote a small test locally which is in JsonObjectDecoderTest
I fails, unless you change in JsonObjectDecoder.java, decode() method
`
        if (this.idx > in.readerIndex() && lastReaderIndex != in.readerIndex()) {
            this.idx = in.readerIndex();
            if (state == ST_DECODING_ARRAY_STREAM) {
                insideString = false;
                openBraces = 1;
            } else if(state == ST_DECODING_NORMAL) { // this has to be added to come back to 0 as we go back to the object start.
                insideString = false;
                openBraces = 0;
            }
        }

`

`
    @Test
    public void testJsonObjectOverMultipleWritesWithSubObjects() {
        EmbeddedChannel ch = new EmbeddedChannel(new JsonObjectDecoder());

        String objectPart1 = "{\"firstname\": \"John\", \"more\" : { \"age\" ";
        String objectPart2 = ": 18 },\n \"surname\" :";
        String objectPart3 = "\"Doe\", age:22   \n}";
        String objectPart33 = "{ \"firstname\": \"John\", \"more\" : {";

        String objectPart4 = " \"age\" ";
        String objectPart5 = ": 19 },\n \"surname\" :";
        String objectPart6 = "\"Doe\", age:23   \n}";

        // Test object
        ch.writeInbound(Unpooled.copiedBuffer(objectPart1, CharsetUtil.UTF_8));
        ch.writeInbound(Unpooled.copiedBuffer(objectPart2, CharsetUtil.UTF_8));
        ch.writeInbound(Unpooled.copiedBuffer(objectPart3 + objectPart33, CharsetUtil.UTF_8));
        ch.writeInbound(Unpooled.copiedBuffer(objectPart4, CharsetUtil.UTF_8));
        ch.writeInbound(Unpooled.copiedBuffer(objectPart5, CharsetUtil.UTF_8));
        ch.writeInbound(Unpooled.copiedBuffer(objectPart6, CharsetUtil.UTF_8));

        ByteBuf res = ch.readInbound();
        assertNotNull(res);
        assertEquals(objectPart1 + objectPart2 + objectPart3, res.toString(CharsetUtil.UTF_8));
        res = ch.readInbound();
        assertNotNull(res);
        assertEquals(objectPart33 + objectPart4 + objectPart5 + objectPart6, res.toString(CharsetUtil.UTF_8));
        res.release();

        assertFalse(ch.finish());
    }

`
Hope it helps.
Manuel

**Comment by normanmaurer** [comment]
@ManuelPivotal thanks but can you please follow the steps explained here:

https://help.github.com/articles/about-pull-requests/

This will help us to consume the fix in a correct way and also attribute it to you.

**Comment by normanmaurer** [comment]
@ManuelPivotal did you see my answer ?

**Comment by ManuelPivotal** [comment]
Yep
Thanks for reminding me, I will do this in the coming days.

Best,
Manuel

**Comment by ikurovsky** [comment]
@ManuelPivotal Should be fixed by #7820
