### ISSUE TITLE
SSL connection not closed properly after handshake failure in v4.1.21

### ISSUE THREAD

**Issue by jianglai** [netty/netty#7724]
### Expected behavior
When SSL handshake fails, the connection is closed.

### Actual behavior
Even though the SSL engine is closed, the connection itself is not closed.

### Steps to reproduce
See below.

### Minimal yet complete reproducer code (or URL to code)
Run the demo code [here](https://github.com/jianglai/netty-bug/blob/master/src/main/java/test/Main.java). The program hangs and "Channel closed." is never printed to stdout. If you change the Netty version in the pom.xml file to 4.1.17, the channel is closed as expected.

### Netty version
4.1.21

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_112-google-v7"
OpenJDK Runtime Environment (build 1.8.0_112-google-v7-181886826-181741640)
OpenJDK 64-Bit Server VM (build 25.112-b01, mixed mode)

### OS version (e.g. `uname -a`)
Linux 4.9.0-5-amd64 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux

I think this is a regression introduced by https://github.com/netty/netty/commit/978a46cc0a5242702f248842f6feb97b8fbe0123.

More specifically, [`handshakePromise.tryFailure`](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L1183)  is called within the `try` clause, and the promise is set to failure. Later in the `finally` clause, [`setHandshakeFailure`](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L1529) calls [`notifyHandshakeFailure`](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L1542]), which is no longer calling [`SslUtils.notifyHandshakeFailure`](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslUtils.java#L320) because the promise has been marked as finished. Therefore `ctx.close()` is never called to close the channel.

**Comment by normanmaurer** [comment]
@jianglai thanks I will check.

**Comment by normanmaurer** [comment]
@jianglai should be fixed by https://github.com/netty/netty/pull/7727.

**Comment by jianglai** [comment]
Thanks for the quick turnaround!

**Comment by normanmaurer** [comment]
@jianglai no problem... would be nice if you can verify the fix

**Comment by Scottmitch** [comment]
fixed by #7727

**Comment by jianglai** [comment]
Confirmed that with 4.1.22.Final-SNAPSHOT, the demo code works as intended.

Thanks!

**Comment by normanmaurer** [comment]
@jianglai thanks a lot !
