### ISSUE TITLE
Downloading large file halts during transfer

### ISSUE THREAD

**Issue by blucas** [netty/netty#7729]
### Expected behavior
When downloading a large file (50MB) from a netty based server, I expect to receive the entire file and that the download does not halt during the transfer.

### Actual behavior
Download of file halts during the transfer. Transfer eventually terminates due to idle timeout. 

### Steps to reproduce
1. Setup a Netty HTTP server using Epoll Edge Triggered
2. Set the low water mark to 8192 bytes (8k) and high to 32768 bytes (32k)
3. Transfer the file using 8k chunks, flushing when unwritable

### Minimal yet complete reproducer code (or URL to code)
Will try to create one

### Netty version
4.1.21.Final

### JVM version (e.g. `java -version`)
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

### OS version (e.g. `uname -a`)
Linux

### Notes
FYI, downgrading to Netty 4.1.17.Final fixes the issue.  I believe the issue has been introduced by https://github.com/netty/netty/commit/b215794de31f28355e4469fcc04782f55076c80c. I use a custom handler to chunk `FullHttpResponse` objects and send them outbound, so it may be an issue with that handler in conjunction with the netty commit mentioned above.

/cc @Scottmitch Since you did the work on that commit

**Comment by doom369** [comment]
Have the same issue. Increasing chunk size from 8kto 128k fixes the issue.

**Comment by Scottmitch** [comment]
thanks for reporting. Can you clarify how you are writing the file? Are you using `FileRegion` or do you cache the file in memory and write `ByteBuf`s? Do you have an `SslHandler` in the pipeline?

**Comment by doom369** [comment]
@Scottmitch I was using default Netty Static File example. 

SslHandler is present and this part is used:

```
ctx.writeAndFlush(new HttpChunkedInput(new ChunkedFile(raf, 8 * 1024)),
                            ctx.newProgressivePromise());
```

> Can you confirm if the data is actually being written (wire shark, LoggingHandler, etc...)

Yes. Adding progress listener show that server sends every time the random number of chunks (40-60% of the file). Tested both via browser and curl.

**Comment by Scottmitch** [comment]
@doom369 - Can you list the precise steps you used to reproduce using the "Netty Static File example" (I'm assuming `HttpStaticFileServer`)? What file did you download, did you change any code, what browser were you using, what transport are you able to reproduce with?

**Comment by doom369** [comment]
@Scottmitch correct. I used handler from `HttpStaticFileServer` (just handler). My server also users epoll along with openssl. Browser chrome. I'll try to cut off some minimal reproducer when I have some time.

**Comment by Scottmitch** [comment]
@blucas - reproducer was very helpful to narrow in on the issue!

**Comment by blucas** [comment]
@Scottmitch - You're welcome! Glad it helped!
