### ISSUE TITLE
ByteBuf.slice can only take int for the length value

### ISSUE THREAD

**Issue by konsultaner** [netty/netty#7732]
I want to chunk a ByteBuf into large slices. I cannot do it because the 

```
ByteBuf.slice(int index, int length)
```
 obviously limits it to `Integer.MAX_VALUE`. I need Long values. Can I just simply use a CompositeBuffer to compensate my problem or should I just never slice with such big values for some reason? If so, what is the reason?

**Comment by normanmaurer** [comment]
@konsultaner thats because arrays are only addressable via "int" and the `ByteBuf` may be backed by an byte[]. So you are currently limited by Integer.MAX_VALUE.
