### ISSUE TITLE
Proposal: DnsAddressResolverGroup to use injectable DnsNameResolverBuilder

### ISSUE THREAD

**Issue by kachayev** [netty/netty#7749]
### Expected behavior

It should be possible to create `DnsAddressResolverGroup` having `DnsNameResolverBuilder` ready-to-go.

### Actual behavior

Right now, if I want setup custom settings for `DnsAddressResolver` I need to sub-class `DnsAddressResolverGroup` and override `newNameResolver` [method](https://github.com/netty/netty/blob/06dcca1dbcc048b6ce7d954e4ecdf1d3ed6af034/resolver-dns/src/main/java/io/netty/resolver/dns/DnsAddressResolverGroup.java#L97) as it creates new `DnsNameResolverBuilder` with "almost" default settings internally.

Ideally, I want to instantiate `DnsNameResolverBuilder` by my own and pass it to the `DnsAddressResolverGroup` as an argument. More than that, I don't need `channelFactory` and `nameServerProvider` being carried over `DnsAddressResolverGroup`: I can set them directly to the `DnsNameResolverBuilder` instance.

It probably would be even easier to create a new `AddressResolverGroup` implementation to work this way, but `InflightNameResolver` is not allowed to be used from the outside of the package, so if the user wants to benefit from it, it should follow `DnsAddressResolverGroup` API and override `newNameResolver`.

### Netty version

4.1.*

### Proposal

There're 2 options here:

1. Upgrade `DnsAddressResolverGroup` with a new constructor 

```java
public DnsAddressResolverGroup(DnsNameResolverBuilder builder);
```

and appropriate checker if we have `DnsNameResolverBuilder` or we need to create a new one.

2. Create a new `AddressResolverGroup` implementation, like `PluggableDnsAddressResolverGroup` (? naming is hard).

What do you think? Happy to create a PR if there are no objections here.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7793
