### ISSUE TITLE
Feature Request: ability to set/get ResourceLeakDetector's targetRecords programmatically

### ISSUE THREAD

**Issue by r-joshi** [netty/netty#7754]
### Description

Currently ResourceLeakDetector's leak detection target records number can be set as a JVM option: io.netty.leakDetection.targetRecords. Would it be possible to provide a programmatic way to set this, i.e., a setter method: 

ResourceLeakDetector.setTargetRecords(int)

This is similar to how the leak detection level can be set using a JVM option as well as using a setter.

Also a getter: ResourceLeakDetector.getTargetRecords() would be useful.

### Netty version
4.1.22.Final

**Comment by normanmaurer** [comment]
Its not clear yet why this would be useful. Closing this issue

**Comment by r-joshi** [comment]
The original use case that I had in mind is to be able to update the value of targetRecords at run time without the need to restart the application. For example, initially the application can have default values for level and target records. However, if a resource leak is encountered in logs, for further investigation, the values could be updated at run time (e.g. using JMX) without process restart. 

The other case is when integration tests run against the application, if get method is available, the tests can validate that the application is running at the desired level and target records values. If set method is available, the tests can validate that the ability to update at run time is working.
