### ISSUE TITLE
@Sharable should also support @Target(ElementType.TYPE_USE)

### ISSUE THREAD

**Issue by raner** [netty/netty#7756]
### Expected behavior
`@Sharable` should also be usable with anonymous inner types, so that it is no longer necessary to make named classes (top-level or nested) for sharable handlers. Since Java 8, this is possible with the new `ElementType` `TYPE_USE`.
The practical problem here is that either (a) Netty would have to, at some point, *require* Java 8 (don't think that's the case yet), or (b) an additional Java-8-specific `@Sharable` annotation would have to be introduced.

### Actual behavior
`@Sharable` only targets `ElementType` `TYPE` and requires a proper (i.e., named) class.

### Steps to reproduce
Add `@Sharable` annotation to inner class, observe compilation error.

### Minimal yet complete reproducer code (or URL to code)
```
ChannelInboundHandler echoHandler = new @Sharable ChannelInboundHandlerAdapter() {
      @Override
      public void channelRead(ChannelHandlerContext context, Object message) {
           context.write(message);
      }
}
```
### Netty version
4.1.22.Final

### JVM version (e.g. `java -version`)
1.8.0_152

### OS version (e.g. `uname -a`)
Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64 (MacOS 10.12.6)

**Comment by kiril-me** [comment]
Yes, this is the excellent feature. Also, I would like to have ElementType.TYPE_PARAMETER as well.

The main problem that netty currently support Java 6.

**Comment by normanmaurer** [comment]
This makes perfect sense and we are planing to start work on the next major version of netty very soon which will hopefully be able to fix this.

Stay tuned, I will start a proposal for all of this soon.

**Comment by normanmaurer** [comment]
@raner / @kiril-me if you are interested you may want to contribute a PR against master which is Java8+ now.

**Comment by kiril-me** [comment]
I can work on that.

**Comment by normanmaurer** [comment]
@kiril-me thanks a lot for all the help!
