### ISSUE TITLE
how to run benchmarkserver in https protocol?

### ISSUE THREAD

**Issue by mingxing47** [netty/netty#7757]
### Expected behavior
I run the example in netty/example/src/main/java/io/netty/example/http/websocketx/benchmarkserver/ path.
I want to start the example in https protocol.
### Actual behavior
The console shows that:
Open your web browser and navigate to http://127.0.0.1:8080/
but what I want is 
Open your web browser and navigate to https://127.0.0.1:8443/

### Steps to reproduce
I have debuged this program, and in the WebsocketServer class, the 'static final boolean SSL = System.getProperty("ssl") != null' is false.
### Minimal yet complete reproducer code (or URL to code)
I don't change any code in netty/example/src/main/java/io/netty/example/http/websocketx/benchmarkserver/
for netty 4.1
### Netty version
here is my maven pom file:
`
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.simon</groupId>
	<artifactId>nettyHttpsWebsocket</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<dependencies>
		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-all</artifactId>
			<version>4.1.16.Final</version>
			<scope>compile</scope>
		</dependency>
	</dependencies>
</project>
`
### JVM version (e.g. `java -version`)
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
### OS version (e.g. `uname -a`)
Darwin Simons-MacBook-Pro.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
You will need to use "-Dssl" or set the property by yourself before starting it.

**Comment by mingxing47** [comment]
thank you! I manged it by setting the property by myself.
Another question is, I want to use it in a dynamic way when I received a http request , I want to establish a ws channel , and when I received a https request, I want to establish a wss channel instead.
How should I manage it?

**Comment by mingxing47** [comment]
now I create a method to get the property , like here:
``` java
    public String getWebSocketProtocol() {
        String websocketProtocol = "ws";
        if (!"http".equals(ConfigFileUtil.getConfig("websocket.protocol"))) {
            websocketProtocol = "wss";
        }
        return websocketProtocol;
    }
```
and I establish the websocket connection blow:
```
        String protocol = getWebSocketProtocol();
        WebSocketServerHandshakerFactory wsFactory = new WebSocketServerHandshakerFactory(
                protocol + "://" + req.headers().get(HttpHeaderNames.HOST), SysConstants.SUB_PROTOCOLS, false);
```
I don't think it's a good way to solve this question , but I can't come up with a good solution.

**Comment by johnou** [comment]
@mingxing47 maybe check out io.netty.handler.ssl.OptionalSslHandler or the portunification example https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/portunification
