### ISSUE TITLE
HashedWheelTimer doesn't handle very large values

### ISSUE THREAD

**Issue by ivankelly** [netty/netty#7760]
### Expected behavior
If I set a timeout with Long.MAX_VALUE (effectively trying to disable it), it should never run.

### Actual behavior
It runs. It runs a lot.

### Steps to reproduce
```
    @Test
    public void testMassiveTimeout() throws InterruptedException {
        final Timer timer = new HashedWheelTimer();
        final CountDownLatch barrier = new CountDownLatch(1);
        final Timeout timeout = timer.newTimeout(new TimerTask() {
            @Override
            public void run(Timeout timeout) throws Exception {
                fail("This should not have run");
                barrier.countDown();
            }
        }, Long.MAX_VALUE, TimeUnit.SECONDS);
        assertFalse(barrier.await(3, TimeUnit.SECONDS));
        assertFalse("timer should not expire", timeout.isExpired());
        timer.stop();
    }
```

### Netty version

Behaviour observed in 4.1.21.Final
Tested on 4.1 branch from January 2 (062d9269120bac0064408025b78788613d41d36d)

### JVM version (e.g. `java -version`)

openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-1~deb9u1-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

### OS version (e.g. `uname -a`)

Linux eshmun 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@ivankelly this sounds clearly like a bug... Let me check as soon as I have a few cycles or if you like you could also try to provide a PR .

**Comment by ivankelly** [comment]
@normanmaurer I had a quick look. The logic looks sound. If I get more time, I'll look again. It's going to be something to do with something being added to turn it negative.

**Comment by normanmaurer** [comment]
@ivankelly yep sounds like it... looking now

**Comment by normanmaurer** [comment]
@ivankelly ok I know whats wrong... writing a fix now

**Comment by ivankelly** [comment]
:+1:

**Comment by normanmaurer** [comment]
@ivankelly https://github.com/netty/netty/pull/7765
