### ISSUE TITLE
Memory Leak detected when Channel Writes are not flushed fast enough

### ISSUE THREAD

**Issue by ashutoshvsingh** [netty/netty#7762]
### Red Hat Enterprise Linux Server release 6.7 (Santiago)

We are seeing the Resident memory of the JVM running Netty (IMAP server) is growing to a point where we are running out of heap on the machine and JVM is getting killed. 
This happens under a certain load where the we are proxying the commands and load coming to the Server from Client X and we are forwarding to Server Y. This load is no more than 10% of the load we take normally. But with new load we are seeing the memory leak.
The only thing different about this load is that we are not protected for slow clients and slow server that we are proxying to. 
We are going to patch to code to not read from client when the Proxy or Write side is not writeable but will take some time to roll that code out. 
In the meantime what can we do to disable this direct buffer or whatever is using non-jvm heap memory to not have JVM heap side grow. 
I have changed the setting for advance leak detection and will be happy to paste the output for you once I gather the data. I have put the host back in rotation to take traffic. These servers are running at 67K + connections.
Ash

**Comment by normanmaurer** [comment]
Sorry for the slow response as I was travelling. There is really nothing we can do about it as even without the `PooledByteBufAllocator` you will run into trouble as the GC can not free the memory. You really need to ensure you stop writing (which in this case could be done by stop reading) once you are not able to flush out data fast enough.

**Comment by ashutoshvsingh** [comment]
Hi Norman,
Thanks, that is what we did. We check if the channel is writeable and only
then read from the client. This fixed the memory leak.
Ash
