### ISSUE TITLE
Netty using WebSocker08Frames after WebSocket version 13 handshake

### ISSUE THREAD

**Issue by konsultaner** [netty/netty#7767]
I have noticed a weired behavior that is not explainable to me:

```
17:13:11.360 [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocketServerHandshaker - [id: 0x092505f7, L:/0:0:0:0:0:0:0:1:443 - R:/0:0:0:0:0:0:0:1:51684] WebSocket version V13 server handshake
17:13:11.362 [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocketServerHandshaker - WebSocket version 13 server handshake key: YzEzYzE1MzItMzM5MS00Zg==, response: gGD2w9YWJ8UmS5w3RBn6ciK116w=
17:13:11.820 [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame opCode=1
17:13:11.820 [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.w.WebSocket08FrameDecoder - Decoding WebSocket Frame length=421
```

The handshake was `WebSocket version 13` but the decoder is a `WebSocket08FrameDecoder `

### Steps to reproduce

This is my pipe
```
pipeline.addLast(new ChannelHandler[]{new HttpServerCodec()});
pipeline.addLast(new ChannelHandler[]{new HttpContentCompressor()});
pipeline.addLast(new ChannelHandler[]{new HttpContentDecompressor()});
pipeline.addLast(new ChannelHandler[]{new HttpObjectAggregator(this.maxContentLength)});
pipeline.addLast(WebSocketServerProtocolHandler.class.getName(), new WebSocketServerProtocolHandler(webSocketPath, subProtocols, allowExtensions, maxFramePayloadLength));
```
I connected WampSharp to the WebSocketServer and also created an [issue there](https://github.com/Code-Sharp/WampSharp/issues/240)

### Netty version
4.1.20

### JVM version (e.g. `java -version`)
jdk1.8.0_152

### OS version (e.g. `uname -a`)
Win10

**Comment by slandelle** [comment]
`WebSocket13FrameDecoder` extends `WebSocket08FrameDecoder` and you're just seeing some logs from the parent class, see https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocket08FrameDecoder.java#L87

**Comment by konsultaner** [comment]
@slandelle Thanks! But thats really confusing
