### ISSUE TITLE
pom error when I import netty into eclipse

### ISSUE THREAD

**Issue by mingxing47** [netty/netty#7772]
### Actual behavior
When I import netty (https://github.com/netty/netty.git) into eclipse, the pom shows errors.
for example here:
Missing artifact io.netty:netty-tcnative:jar:${os.detected.classifier}:2.0.7.Final
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack-dependencies (execution: unpack, phase: generate-sources)
…

the sum of the errors is 100.
### Netty version
4.1.23.Final-SNAPSHOT
### JVM version (e.g. `java -version`)
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
### OS version (e.g. `uname -a`)
Darwin bogon 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

I've searched the Internet but I can't figure out how to deal with these problems, and could you please tell me how to fix these errors?

**Comment by mingxing47** [comment]
I'm sorry I find the solution here:
Set up Eclipse with M2E and Java 7/8
Ensure to use the 64-bit version of Eclipse.
Download os-maven-plugin and put it into <ECLIPSE_INSTALLATION_DIR>/plugins (Eclipse 4.5) or <ECLIPSE_INSTALLATION_DIR>/dropins (Eclipse 4.6) directory to work around the problem where m2e does not evaluate an extension specified in our pom.xml. (Unlike its name, it's both a Maven plugin and an Eclipse plugin.)
Import the project via the 'File → Import... → Existing Maven Projects' menu.
Netty project Maven pom.xml settings dictate use of Java SE 1.6, while implicitly using Java 7/8 (1.7/1.8) features if present. This may result in compilation errors in Eclipse. There are two ways to work around this problem:
Look in the 'Window → Preferences → Installed JRE' menu:
Make sure you have Java 7/8 installation available under 'Installed JRE'
Map this Java 7/8 installation onto Java 6: 'Installed JRE → Execution Environments → Java SE 1.6'
Alternatively, Java 7/8 JRE can be selected on per-project basis for each Netty module.

http://netty.io/wiki/developer-guide.html

and I'll have a try.

**Comment by normanmaurer** [comment]
Sorry but I think this is more an eclipse question then a netty one. All the developers use IntelliJ so I am not sure if anyone is a great help here. So let me close this here.

**Comment by mingxing47** [comment]
Thank you all the same! When I switch my IDE from eclipse to IntelliJ, the question is solved.
I'm sorry to ask this question to waste your time, thx~
