### ISSUE TITLE
TooLongFrameException only throw one time in DelimiterBasedFrameDecoder

### ISSUE THREAD

**Issue by zhoujie0101** [netty/netty#7775]
Hi, i am a new netty user, when i read DelimiterBasedFrameDecoder source code(branch 4.1.x), in decode(ChannelHandlerContext ctx, ByteBuf buffer) method, if minDelim never found and because discardingTooLongFrame is init to false, first time discardingTooLongFrame is assigned to true and throw TooLongFrameException, but second time source code as below:
// Still discarding the buffer since a delimiter is not found.
tooLongFrameLength += buffer.readableBytes();
buffer.skipBytes(buffer.readableBytes());
was execute but never throw TooLongFrameException again, is it a bug?

**Comment by normanmaurer** [comment]
@zhoujie0101 no its not a bug... We only want to throw it one time and then its up to the user to handle it. Most of the times the correct thing is just log it and close the `Channel`

**Comment by zhoujie0101** [comment]
got it，thanks
