### ISSUE TITLE
Could not find artifact io.netty:netty-transport-native-kqueue:zip:native-src:4.1.22.Final in central (https://repo.maven.apache.org/maven2)

### ISSUE THREAD

**Issue by ikatraev** [netty/netty#7776]
I am trying to build netty (*master* and *netty-4.1.22.Final*) using maven version 3.5 using the following commands:
  
    mvn clean -U
    mvn install -U

Got the following build error:

    [INFO] --- maven-hawtjni-plugin:1.14:build (build-native-lib) @ netty-transport-native-kqueue ---
    Downloading: https://repo.maven.apache.org/maven2/io/netty/netty-transport-native-kqueue/4.1.22.Final/netty-transport-native-kqueue-4.1.22.Final-native-src.zip
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary:
    [INFO] 
    [INFO] Netty .............................................. SUCCESS [  6.718 s]
    [INFO] Netty/Common ....................................... SUCCESS [ 52.907 s]
    [INFO] Netty/Buffer ....................................... SUCCESS [ 46.102 s]
    [INFO] Netty/Resolver ..................................... SUCCESS [  5.503 s]
    [INFO] Netty/Transport .................................... SUCCESS [ 58.557 s]
    [INFO] Netty/Codec ........................................ SUCCESS [ 20.482 s]
    [INFO] Netty/Codec/DNS .................................... SUCCESS [  6.161 s]
    [INFO] Netty/Codec/HAProxy ................................ SUCCESS [  4.780 s]
    [INFO] Netty/Handler ...................................... SUCCESS [ 44.912 s]
    [INFO] Netty/Codec/HTTP ................................... SUCCESS [ 17.606 s]
    [INFO] Netty/Codec/HTTP2 .................................. SUCCESS [ 25.005 s]
    [INFO] Netty/Codec/Memcache ............................... SUCCESS [  5.184 s]
    [INFO] Netty/Codec/MQTT ................................... SUCCESS [  5.602 s]
    [INFO] Netty/Codec/Redis .................................. SUCCESS [  4.968 s]
    [INFO] Netty/Codec/SMTP ................................... SUCCESS [  4.491 s]
    [INFO] Netty/Codec/Socks .................................. SUCCESS [  6.714 s]
    [INFO] Netty/Codec/Stomp .................................. SUCCESS [  4.717 s]
    [INFO] Netty/Codec/XML .................................... SUCCESS [  4.677 s]
    [INFO] Netty/Handler/Proxy ................................ SUCCESS [ 15.012 s]
    [INFO] Netty/Resolver/DNS ................................. SUCCESS [ 10.501 s]
    [INFO] Netty/Transport/RXTX ............................... SUCCESS [  3.314 s]
    [INFO] Netty/Transport/SCTP ............................... SUCCESS [  3.248 s]
    [INFO] Netty/Transport/UDT ................................ SUCCESS [ 20.022 s]
    [INFO] Netty/Example ...................................... SUCCESS [  9.047 s]
    [INFO] Netty/Transport/Native/Unix/Common ................. SUCCESS [  5.950 s]
    [INFO] Netty/Testsuite .................................... SUCCESS [07:03 min]
    [INFO] Netty/Transport/Native/Unix/Common/Tests ........... SUCCESS [  2.783 s]
    [INFO] Netty/Transport/Native/KQueue ...................... FAILURE [  2.824 s]
    [INFO] Netty/All-in-One ................................... SKIPPED
    [INFO] Netty/Dev-Tools .................................... SKIPPED
    [INFO] Netty/Tarball ...................................... SKIPPED
    [INFO] Netty/Transport/Native/Epoll ....................... SKIPPED
    [INFO] Netty/Testsuite/Autobahn ........................... SKIPPED
    [INFO] Netty/Testsuite/Http2 .............................. SKIPPED
    [INFO] Netty/Testsuite/OSGI ............................... SKIPPED
    [INFO] Netty/Microbench ................................... SKIPPED
    [INFO] Netty/BOM .......................................... SKIPPED
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 13:42 min
    [INFO] Finished at: 2018-03-10T17:52:35-06:00
    [INFO] Final Memory: 76M/1251M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.14:build (build-native-lib) on project netty-transport-native-kqueue: build failed: org.apache.maven.plugin.MojoExecutionException: Requested download does not exist.: Could not find artifact io.netty:netty-transport-native-kqueue:zip:native-src:4.1.22.Final in central (https://repo.maven.apache.org/maven2)
    [ERROR] 
    [ERROR] Try downloading the file manually from the project website.
    [ERROR] 
    [ERROR] Then, install it using the command: 
    [ERROR]     mvn install:install-file -DgroupId=io.netty -DartifactId=netty-transport-native-kqueue -Dversion=4.1.22.Final -Dclassifier=native-src -Dpackaging=zip -Dfile=/path/to/file
    [ERROR] 
    [ERROR] Alternatively, if you host your own repository you can deploy the file there: 
    [ERROR]     mvn deploy:deploy-file -DgroupId=io.netty -DartifactId=netty-transport-native-kqueue -Dversion=4.1.22.Final -Dclassifier=native-src -Dpackaging=zip -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
    [ERROR] 
    [ERROR] 
    [ERROR]   io.netty:netty-transport-native-kqueue:zip:4.1.22.Final
    [ERROR] 
    [ERROR] from the specified remote repositories:
    [ERROR]   sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots, releases=false, snapshots=true),
    [ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
    [ERROR] -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
    [ERROR] 
    [ERROR] After correcting the problems, you can resume the build with the command
    [ERROR]   mvn <goals> -rf :netty-transport-native-kqueue

with the following environment:
* Mac OSX high Sierra 10.13.3
* Java version: 1.8.0_151, vendor: Oracle Corporation

I have found similar issue [#2558](https://github.com/netty/netty/issues/2558) but that was for Linux environment.

**Comment by lovepoem** [comment]
I think you issue is similar with what i met .  https://github.com/netty/netty/issues/7748

**Comment by ikatraev** [comment]
Yes. It does fix the issue.
@lovepoem thanks a lot
