### ISSUE TITLE
How to release a broadcasted byteBuf

### ISSUE THREAD

**Issue by konsultaner** [netty/netty#7779]
I use a `MessageToMessageDecoder<WebSocketFrame>` an a `ByteToMessageDecoder` where I take the retained `byteBuf`. The `byteBuf` has a reference count of `2`. My code has to do the final release to set the reference count to `0`, but I don't know how in my scenario.

I wand to broadcast that `byteBuf` to multiple channels. What I tried was:

```java
for(Channel channel : channels){
    // refCount == 1
    channel.writeAndFlush(byteBuf);
    // refCount == 0
}

// io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1 -> for each incoming message
```

```java
for(Channel channel : channels){
    byteBuf.retain();
    // refCount == 2
    channel.writeAndFlush(byteBuf);
    // refCount == 1
}

// LEAK: ByteBuf.release() was not called before it's garbage-collected.
```

```java
for(Channel channel : channels){
    byteBuf.retain();
    channel.writeAndFlush(byteBuf);
    byteBuf.release();
}

// Works a lot better but sometimes I get both errors but a lot less
// LEAK: ByteBuf.release() was not called before it's garbage-collected.
// io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1 -> for each incoming message
```

I have no real idea where to start at. Any suggestions where to start debugging at? Or should one of the solutions actually work?

**Comment by konsultaner** [comment]
One more question. Is there a way to zero copy a ByteBuf. I want to receive a slice of a byteBuf but with its indepandent refCount, but it should not copy the underlying direct memory. It should have its own reservation somehow. Something like `ByteBuf.copy` but as zero copy.

**Comment by johnou** [comment]
@konsultaner have you seen io.netty.channel.group.DefaultChannelGroup?

**Comment by konsultaner** [comment]
@johnou I do, but does it make a difference? I decided to not use it, because I have different conditions to broadcast. I didn't build a separate channel matcher, but I could if this is the solution.

At the moment it seems like the `MessageToMessageDecoder<WebSocketFrame>` pushes independent `byteBuf` messages to my broad caster where as the `ByteToMessageDecoder` pushes only slices. If I now release the slice more then one slice, the incoming `byteBuf` is zeroed too. I'm still investigating ;)

**Comment by normanmaurer** [comment]
@konsultaner so you need to do it exactly as `DefaultChannelGroup` does. Which basically means you need to duplicate and retain it before passing it to `writeAndFlush`.

**Comment by normanmaurer** [comment]
@konsultaner I think what you want is `ByteBuf.retainedSlice`.

**Comment by konsultaner** [comment]
@normanmaurer Thanks! I think I got it
