### ISSUE TITLE
ResourceLeakDetector does not retain the initial record

### ISSUE THREAD

**Issue by trustin** [netty/netty#7781]
### Expected behavior

The leak report printed by `ResourceLeakDetector` retains the stack trace of the moment the buffer was created.

### Actual behavior

The record with `Created at:` heading is not actually the creation record, e.g.

```
Created at:
    io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:616)
    ...
```

### Steps to reproduce

Not sure, but probably write an app that generates a lot of access records and leak?

### Minimal yet complete reproducer code (or URL to code)

Sorry, no.

### Netty version

4.1.22

### JVM version (e.g. `java -version`)

```
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

### OS version (e.g. `uname -a`)

```
Linux infinity 4.14.25-1-lts #1 SMP Fri Mar 9 22:02:42 CET 2018 x86_64 GNU/Linux
```

**Comment by normanmaurer** [comment]
Will have a look

**Comment by normanmaurer** [comment]
@trustin please check the PR.
