### ISSUE TITLE
Enable different Cors rules per origin

### ISSUE THREAD

**Issue by gustavonalle** [netty/netty#7785]
### Expected behavior

It'd be nice to configure the CorsHandler so that I can specify a different set of permissions based on the Origin. 

Example, if origin is http://localhost:8080/ I'd like to allow all methods and auth, but for a certain external Url I'd like to be stricter and limit it for GET only.

### Actual behavior

Current the CorsHandler is configured with a single CorsConfig object that specifies the permissions for one or more origin; CorsConfig's ```allowedRequestMethods```, ```allowedRequestHeaders``` and others apply to all origins.

### Netty version

4.1.22.Final

**Comment by normanmaurer** [comment]
@gustavonalle PRs welcome

**Comment by gustavonalle** [comment]
Working on it
