### ISSUE TITLE
Native-epoll 32-bit artifact

### ISSUE THREAD

**Issue by sgammon** [netty/netty#7789]
I would like to humbly request that Netty include a 32-bit artifact for native epoll support.

Specifically, I am trying to use a 32-bit JDK in a container environment (Docker), where a small heap (<2gb) is acceptable, to host a Netty-based service in epoll-supporting Linux.

I know this issue has been raised before in #5813, but perhaps this use case - micro-services in containers - was not considered when that was filed.

If a 32-bit artifact doesn't make sense to ship with Netty itself, some directions to compile and use your own would be fine but I presume depending libraries would have to ship that themselves?

**Comment by normanmaurer** [comment]
@sgammon honestly I think we are currently not interested in shipping a 32bit version as well as it will also make the whole release process more complicated. I would guess the way how to do it is just to follow the usually build instruction but on a 32 bit system. Let me know if you have more questions.
