### ISSUE TITLE
DnsNameResolverContext.resolve(Promise) may skip the first search domain

### ISSUE THREAD

**Issue by trustin** [netty/netty#7794]
I'm not sure I understood the logic clearly, but for example when ndot is 1 and search list is `[ 'foo.com', 'bar.com' ]`, the resolve requests for `some.host` would be:

- `some.host.` (queries first because ndot of `some.host` is >= 1.)
- `some.host.foo.com.` (with the first suffix in the search list)
- `some.host.bar.com.` (with the last suffix in the search list)

However, `DnsNameResolverContext.resolve(Promise)` seems to simply skip the first item in the search list: https://github.com/netty/netty/blob/netty-4.1.22.Final/resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolverContext.java#L134

As a result, only the two queries will be sent:

- `some.host.`
- `some.host.bar.com.`

Is this correct, or am I missing something?

**Comment by trustin** [comment]
@shyiko @normanmaurer PTAL

**Comment by trustin** [comment]
If anyone confirms this is a bug, let me send a PR.

**Comment by normanmaurer** [comment]
@trustin hmm this sounds not right to me... @shyiko WDYT ?

**Comment by shyiko** [comment]
```
if hasNDots() is true
	initialHostname = hostname
	initialSearchDomainIdx = 0
	doSearchDomainQuery is executed for initialHostname + searchDomains[0:] 
		(in this order, until one succeeds) 
else 
	initialHostname = hostname + '.' + searchDomains[0]
	initialSearchDomainIdx = 1
	doSearchDomainQuery is executed for initialHostname + searchDomains[1:] + hostname (through internalResolve)  
		(in this order, until one succeeds)
```
so it looks like everything is as it should be.

**Comment by trustin** [comment]
@shyiko You are correct. I misread the code. :sweat_smile:
