### ISSUE TITLE
A small problem in the thread model of netty

### ISSUE THREAD

**Issue by zhaojigang** [netty/netty#7809]
Suppose the server has two CPU, and workerGroup has two EventLoop,
and two channel are registered on each EventLoop.

If the two channel on the first EventLoop is busy, and the two channel on the second EventLoop are free. 

At this point, we only use one CPU, the other is idle, isn't it a waste?(By default, a EventLoop is handled with a thread)

I am a Chinese, my English is poor.

**Comment by normanmaurer** [comment]
Well its a trade-off.... Context switching is not for free either. The model netty uses is a very popular model in terms of thread to event loop mapping (that you can also find in node.js for example). Usually over time you will have Channels spread across `EventLoop` s and so have a more balanced usage of resources.

**Comment by zhaojigang** [comment]
thanks!
