### ISSUE TITLE
Netty4.0.28 mem leak for "io.netty.channel.ChannelOutboundBuffer"

### ISSUE THREAD

**Issue by sfomp** [netty/netty#7812]
hi,
I found there are too many  ChannelOutboundBuffer  objects in my server application.
there are 400000  long-connections keep between the phone and my server.
![image](https://user-images.githubusercontent.com/6062964/38017441-a37103d6-32a4-11e8-931f-154681447d85.png)

![image](https://user-images.githubusercontent.com/6062964/38020304-70243b6c-32ac-11e8-87a2-0ea50d997e02.png)

i didn't check channel.isWritable() before channel.writeAndFlush().
if i check the channel iswritable before  writeAndFlush  , could i solve the memory leak problem.
WRITE_BUFFER_HIGH_WATER_MARK=8 * 1024 * 1024
WRITE_BUFFER_LOW_WATER_MARK=1024 * 1024
should i update the version of netty to 4.0.40 final?

and i have two other question.
1、 i wonder whether the server network occur “broken network” or only the client's network had problem， it seems it not possible the 400000  long-connection had problem at the same time.

2、The water mark means one channel or all channels
@normanmaurer  could you please check this, thank you .

### Netty version
4.0.28Final
### JVM version (e.g. `java -version`)
1.7
### OS version (e.g. `uname -a`)
linux

**Comment by normanmaurer** [comment]
These are `ChannelOutboundBuffer.Entry` objects which are not unique per connection. So all of these could also be related to one Channel. All in all this sounds like a typical "not implemented back-pressure / writing to fast" case.  And yes there watermark is per Channel

**Comment by sfomp** [comment]
thanks!
It is not necessary to set the water buffer mark in 4.1.20 Final version ? i saw this option is marked as "@Deprecated" like belowing picture . Whether it is a new feature after 4.0.28Final version.
![image](https://user-images.githubusercontent.com/6062964/38095424-0a55ab70-33a3-11e8-894a-d12844bafdce.png)
@normanmaurer

**Comment by normanmaurer** [comment]
@sfomp as you can see in the javadocs you should use `ChannelOption.WRITER_BUFFER_MARK`:

https://netty.io/4.1/api/io/netty/channel/ChannelOption.html#WRITE_BUFFER_HIGH_WATER_MARK

**Comment by sfomp** [comment]
ok, thank you very very much!
