### ISSUE TITLE
characters output twice

### ISSUE THREAD

**Issue by sstong123** [netty/netty#7818]
### Expected behavior
characters output once.

### Actual behavior
output twice

### Minimal yet complete reproducer code (or URL to code)

1.downoald the [echo sever code](http://netty.io/4.1/xref/io/netty/example/echo/package-summary.html)
2.run the EchoServer.java ;
3.use cmd tool and run:  telnet localhost 8007
4.when connected input ‘’test” in the cmd wind,will find the output is “teesstt” ,not "test"
### Netty version
4.1.22.Final
### JVM version (e.g. `java -version`)
java 8
### OS version (e.g. `uname -a`)
windows 10

**Comment by johnou** [comment]
Telnet echoes input as you type it as well as the received data so the output you observe is correct.

**Comment by sstong123** [comment]
why it's "teesstt "not "test "or "t**t**eesstt"

**Comment by amizurov** [comment]
@sstong123, on my environment work properly, input: test -> output: test

**Comment by normanmaurer** [comment]
Can not reproduce either.. All works as expected

**Comment by normanmaurer** [comment]
Let me close this and please provide a reproducer if you still think there is an issue
