### ISSUE TITLE
promise already done caused by ChunkedWriteHandler writing the same (non chunked) message twice

### ISSUE THREAD

**Issue by xpromache** [netty/netty#7819]
Hello,

I get an exception "promise already done" apparently caused by the ChunkedWriteHandler which is called twice for the same message, one from my flush and the other time from the channelWritabilityChanged.

Not sure if the ChunkedWriteHandler.doFlush method is supposed to be called twice in the same write but it looks to work ok when it's called twice and the message is ChunkedInput.

Maybe lines 304 and 305 should be reversed from:
```
                ctx.write(pendingMessage, currentWrite.promise);
                this.currentWrite = null;
```
to:
```
                this.currentWrite = null;
                ctx.write(pendingMessage, currentWrite.promise);
```

A stacktrace is attached.
[stack-trace.txt](https://github.com/netty/netty/files/1863541/stack-trace.txt)

**Comment by normanmaurer** [comment]
Yes this sounds good.... can you provide a PR?
