### ISSUE TITLE
HpackEncoder limits header list size to 8K by default

### ISSUE THREAD

**Issue by ejona86** [netty/netty#7825]
### Expected behavior
Sending a header list of arbitrary size would succeed, except when the receiver prohibits header list larger than a certain size.

RFC7540 defines SETTINGS_MAX_HEADER_LIST_SIZE's initial value to be unlimited.

### Actual behavior
If the receiver does not specify a maximum header list size in SETTINGS, Netty disallows header list sizes greater than 8K.

The problem seems to be [in HpackEncoder](https://github.com/netty/netty/blob/netty-4.1.22.Final/codec-http2/src/main/java/io/netty/handler/codec/http2/HpackEncoder.java#L89). While defaulting to 8K makes sense for HpackDecoder in order for it to protect itself against the remote, there's no need for such behavior in HpackEncoder. In fact, since SETTINGS_MAX_HEADER_LIST_SIZE is advisory and the content is locally generated, it could ignore the setting completely and only risk wasting bandwidth.

This was reported against gRPC at grpc/grpc-java#4284. CC @JLofgren

### Netty version
4.1.17.Final

I'd be happy to send a PR changing the initialization to use `MAX_HEADER_LIST_SIZE`. @Scottmitch, @normanmaurer, concerns?

**Comment by ejona86** [comment]
Looks like I can call `defaultHttp2HeadersEncoder.maxHeaderListSize(MAX_HEADER_LIST_SIZE)` to workaround this. If done immediately on creation, it looks like it won't collide with any received SETTINGS requesting a lower value.

**Comment by JLofgren** [comment]
I've created a demo of this bug here: https://github.com/JLofgren/demo-grpc-java-bug-4284

Locally I have built netty initializing the max header size in HpackEncoder to MAX_HEADER_LIST_SIZE and shown that this solves the issue. I am working on a PR, but am having some issues dotting all the i's of your PR process.
