### ISSUE TITLE
There is a memory leak when continuely create ChannelGroup to broadcast message.

### ISSUE THREAD

**Issue by DickLoong** [netty/netty#7828]
### Expected behavior
When I was doing benchmark to compare the performance between MINA and Netty,I found that if I use ChannelGroup  to broadcast messages,the ChannelGroup will not be detroyed .This issue could be shown by Eclipse Memory Analyse Tools.
### Minimal yet complete reproducer code (or URL to code)
1.import project zipped in attachment with  Eclipse;
2.run NettyTestServer first then TestClient_Netty;
3.dump then jvm memory file with jmap or fetch it with MAT(Eclipse Memory Analyse Tools) in two different time
then we can see that NettyTestServer occupy more and more memory and analyzation would show that more and more ChannelGroup stay in memory.
[TestServerClientPars.zip](https://github.com/netty/netty/files/1865307/TestServerClientPars.zip)

here is an example
![image](https://user-images.githubusercontent.com/11652469/38161881-a0a5c198-3509-11e8-9a2b-92fc91e52e68.png)
![image](https://user-images.githubusercontent.com/11652469/38161885-adbdb3fe-3509-11e8-8d2b-5fae6fb84b99.png)
![image](https://user-images.githubusercontent.com/11652469/38161889-b8f91bfa-3509-11e8-9857-575702a4bdfb.png)

### Netty version
4.1.6
### JVM version (e.g. `java -version`)
jdk1.8
### OS version (e.g. `uname -a`)
windows 10

**Comment by normanmaurer** [comment]
@DickLoong maybe I am missing something but how should he ever be released... you adding the 
`DefaultChannelGroup` to a static instance of `ConcurrentLinkedQueue` and never remove it.

All of this is done in `EchoLogic_Netty`.

Also on a unrelated note please upgrade to a more recent version of netty. I will close this one now... Please reopen if you still think there is an issue.

**Comment by DickLoong** [comment]
it's my fault for leaving some test code which try to fix this issue ,sorry..
well this issue would still apear if you remove line 20 and 51 of EchoTest_Netty,
and when i run the project replacing netty 4.1.6 to 4.1.22,my pc crashed.

**Comment by DickLoong** [comment]
it's my fault for leaving some test code which try to fix this issue ,sorry..
well this issue would still apear if you remove line 20 and 51 of EchoTest_Netty,
and when i run the project replacing netty 4.1.6 to 4.1.22,my pc crashed.
@normanmaurer
