### ISSUE TITLE
Improve Timer Wakeup for Native Transports

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#7829]
from https://github.com/netty/netty/pull/7816#discussion_r178171275

This topic comes up in frequently enough that I usually forget the answer .... "why do we need to have a max wakeup time of 1 second instead of unbounded" for the EventLoop implementations. IIRC the answer is when we schedule tasks we don't check if the new time results in a sooner deadline than the previous wakeup on the EventLoop. I think I investigated other events from outside the EventLoop and they should be invoking `wakeup` (and we have an atomic boolean protecting wakeup to avoid too many system calls). I wonder if now that we are saving the `prevDeadlineNanos`, and we have a timer mechanism independent of `epoll_wait`,  if we can avoid waking up every second (and additional `timerfd_settime` system calls), and instead only wakeup when necessary.

Potential benefits:
- if there are no scheduled task, we only wakeup when I/O occurs
- we will be more responsive to schedule tasks (because we can adjust the wakeup to the minimum delay as new tasks are scheduled)

Potential negatives:
- in the degenerate case if someone schedules tasks in decreasing order of expiration (10 seconds from now, 9 seconds, 8 seconds, etc...) we will have to touch the the `timerfd_settime` on each schedule. For outside the EventLoop we wouldn't have to wakeup the `epoll_wait` call (assuming `timerfd_settime` is thread safe).

@normanmaurer @carl-mastrangelo - wdyt? We could do the same thing for kqueue too (we would need to use a timerfd equivalent there too though).

**Comment by Scottmitch** [comment]
@carl-mastrangelo 
> I had assumed the periodic wakeup was some sort of safety net when I saw it. If the intent was to periodically check the scheduledTasks, then yeah, wakeup should probably be the correct mechanism, even if it results in timerfd_settime calls. Arguably there are already a ton of timerfd_settime calls when the group is idle. Doesn't seem all that bad of of a downside to me.

Right. Your PR https://github.com/netty/netty/pull/7816 will reduce the number of calls for `epoll_wait`, and this change would effectively pull arming the timer outside of the `epoll_wait` call. So the resolution of this issue may result in more calls to `timerfd_settime` after your PR is merged, compared to the state before your PR my guess is for most use cases it will be a net reduction in `timerfd_settime` calls (in addition to less wakeups when low activity / or no scheduled tasks).

@normanmaurer 
> @Scottmitch that sounds fine to me... That said I think we should be careful and test this carefully :)

+1. `WriteTask` is an exception to the "all events that occurs outside the EventLoop do a wake up". However for the purposes of this issue I don't think it will be too impactful. The worst that may happen is the queue length of the `EventLoop` may grow if there is no flush, and no other event to wakeup the `EventLoop`. This seems unlikely to be an issue because if there is no flush we won't actually write data to the OS, and the writes would sit in the `ChannelOutboundBuffer` queue anyways so the memory consumption should be roughly equivalent.

**Comment by Scottmitch** [comment]
@M-AJ - #7808 doesn't provide the complete context for me to judge if this will have any impact for your use case. However you can try out PR https://github.com/netty/netty/pull/7834 now and let me know 🥇.

**Comment by M-AJ** [comment]
I will try it out tonight and see how it goes!

**Comment by M-AJ** [comment]
What's the maven artifact id for this build?
