### ISSUE TITLE
Consider removing executeAfterEventLoopIteration

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#7833]
executeAfterEventLoopIteration is an `Unstable` API and doesn't appear to be used in Netty, can we remove it? This will remove an additional queue, simplify some control flow logic, and leave less work each event loop run. IIRC executeAfterEventLoopIteration was added [1] when we were exploring a more automated flush approach when writing inside / outside the event loop. I think the work stopped because the write tasks were not structured to wakeup the event loop, and potentially some other outstanding discussions. The application maybe able to implement higher level flush strategies without this feature and I would like to keep the core simple/minimal if possible.

/cc @NiteshKant @normanmaurer - WDYT?

[1] https://github.com/netty/netty/commit/77770374fbe6b0767cfe5eccd0b59a5d66ec998a

**Comment by NiteshKant** [comment]
@Scottmitch yeah there hasn't been any progress on the auto-flush work and it isn't yet clear whether similar strategy can be applied without this (or similar) hook. It also doesn't look like there is any sort of agreement on whether we want to pursue the auto-flush changes. So, yes I agree lets remove this API and we can revisit if/when we want to resume the auto-flush work. 

Here are the related PRs which I can close: 

#5716 (Auto-flush for channels. (`ChannelHandler` implementation))
#6779 (https://github.com/netty/netty/pull/6779)

**Comment by Scottmitch** [comment]
Thanks @NiteshKant. The resolution to https://github.com/netty/netty/issues/7829 has some overlap with this issue so I will wait until after that issue is resolved before taking action here.

**Comment by normanmaurer** [comment]
Removing is fine by me...

**Comment by normanmaurer** [comment]
done
