### ISSUE TITLE
CorsHandler do writeAndFlush in override ChannelHandlerContext#write method

### ISSUE THREAD

**Issue by amizurov** [netty/netty#7837]
Do not really understand, why in `CorsHandler` invoked writeAndFlash ? It's strange side effect.
### Actual behavior

https://github.com/netty/netty/blob/473f6a6edb8353728ea8e711ac8241ddc21adf08/codec-http/src/main/java/io/netty/handler/codec/http/cors/CorsHandler.java#L198-L209
### Steps to reproduce
Add `CorsHandler` to pipeline then write response in your own handler, response flushed automatically.

### Netty version
4.1.22

**Comment by normanmaurer** [comment]
@amizurov its a bug :(
 
Fixed https://github.com/netty/netty/pull/7839

**Comment by amizurov** [comment]
@normanmaurer Thanks a lot, It's really quickly as well as Netty :)
