### ISSUE TITLE
netty-dev-tools dependency not built early enough

### ISSUE THREAD

**Issue by davidmoten** [netty/netty#7842]
### Expected behavior
When I clone the repository and call `mvn clean install` it should complete without error.

### Actual behavior
`netty-common` build fails because `netty-dev-tools` has not been built yet.

### Steps to reproduce

as above

### Minimal yet complete reproducer code (or URL to code)
as above 

### Netty version
4.1.24.Final-SNAPSHOT

### JVM version (e.g. `java -version`)
1.8.0_161

### OS version (e.g. `uname -a`)
`Linux ubuntu1 3.19.0-33-generic #38~14.04.1-Ubuntu SMP Fri Nov 6 18:17:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

### How to fix
Fix might be to add `netty-dev-tools` to `common/pom.xml` as a *test* scoped dependency (with comments to indicate why it's there) so maven build is aware that `netty-common` depends on `netty-dev-tools`.

**Comment by normanmaurer** [comment]
@davidmoten thanks for reporting
