### ISSUE TITLE
the code in Netty.docs does not run as described in the document.

### ISSUE THREAD

**Issue by oHao** [netty/netty#7845]
there is the doc http://netty.io/wiki/user-guide-for-4.x.html and the code：
```java
 @Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) {
        ctx.write(msg); // (1)
        ctx.flush(); // (2)
    }
```
on the part of EchoServer.
it makes that the data server received not return to the client.
I try to call the method flush() in channelReadComplete(ctx) and it works as I expect.
I guess its time to update the doc.
### Netty version
4.1.22.Final
### JVM version (e.g. `java -version`)
1.9
### OS version (e.g. `uname -a`)
10.13.3

**Comment by normanmaurer** [comment]
Hmm that's strange... Both should just work fine. Are you sure about this and can you check what the future of the write tells you after it was completed ?

**Comment by oHao** [comment]
emm。。 well， i will check it

**Comment by normanmaurer** [comment]
Closing as no feedback
