### ISSUE TITLE
Logo design offer

### ISSUE THREAD

**Issue by redmusic27** [netty/netty#7850]
Hello, sir. I want to offer something to you, do you need a new logo for your project? if you want i can make it to you

**Comment by albertok** [comment]
The current logo is pretty sweet already.

![alt text](http://design.jboss.org/netty/logo/final/netty_logo_600px.png)

**Comment by redmusic27** [comment]
Oke no problem sir. Thanks

**Comment by normanmaurer** [comment]
I think we are good for now... Thanks for the offer tho.
