### ISSUE TITLE
New NullInternalLogger implementation of InternalLogger wished for?

### ISSUE THREAD

**Issue by paul-hammant** [netty/netty#7851]
To fit the NullObject pattern, `NullInternalLogger` would be great.  It should extend `AbstractInternalLogger` for expedience, but otherwise be totally benign in operation.

It is possible to make one dynamically with the Null factory from https://proxytoys.github.io/toys.html, but who wants to slurp one more shaded cglib into your uber-jar solution?

**Comment by normanmaurer** [comment]
@paul-hammant why not just use SLF4j with noop binding ?

**Comment by normanmaurer** [comment]
Let me close this now now... Please provide more infos if you are still think its something that should be done
