### ISSUE TITLE
java.lang.NoSuchMethodError with 4.1.23

### ISSUE THREAD

**Issue by CodingFabian** [netty/netty#7854]
java.lang.NoSuchMethodError: io.netty.handler.codec.http2.Http2ConnectionEncoder.writePing(Lio/netty/channel/ChannelHandlerContext;ZLio/netty/buffer/ByteBuf;Lio/netty/channel/ChannelPromise;)Lio/netty/channel/ChannelFuture;

no stack trace, is that a non backwards compatible change?

**Comment by CodingFabian** [comment]
Will check if i can get a stacktrace and figure out where this comes from

**Comment by slandelle** [comment]
> is that a non backwards compatible change?

Http2ConnectionEncoder is flagged as @UnstableAPI so breaking changes can happen anytime.

https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionEncoder.java#L27

**Comment by CodingFabian** [comment]
yeah found that-  thanks for checking with me
