### ISSUE TITLE
Can't get websocket IP address through amazon ELB

### ISSUE THREAD

**Issue by thiennguyen1308** [netty/netty#7856]
### Expected behavior
Hi, I use netty for websocket, and I want to get IP address from client. 
### Actual behavior
When I use ELB load balancer, the only IP that I can get is IP of ELB machine, how can I get real ip from client ?
I saw that someone use this, but  I can only get WebSocketFrame object, can I get header of Http Websocket Upgrade request ?

`  @Override
    public void channelRead0(ChannelHandlerContext ctx, HttpObject msg)
            throws Exception {
        if (msg instanceof HttpRequest) {
            HttpRequest mReq = (HttpRequest) msg;
            String clientIP = mReq.headers().get("X-Forwarded-For");
            if (clientIP == null) {
                InetSocketAddress insocket = (InetSocketAddress) ctx.channel()
                        .remoteAddress();
                clientIP = insocket.getAddress().getHostAddress();
            }
        }
    }`
### Netty version
4.1.22_final
### JVM version (e.g. `java -version`)
jdk 1.8.0_161
### OS version (e.g. `uname -a`)
Amazon Linux EC2

**Comment by normanmaurer** [comment]
You will need to put the handler in front of your upgrade handler. Please show your pipeline confidence.g

**Comment by amizurov** [comment]
@thiennguyen1308 I think your balancer should add 'X-Forwarded-For' header and then you can get real ip in your own handler before websocket upgrade.

**Comment by thiennguyen1308** [comment]
@normanmaurer Thank for your instruction, I have already get client IP now. 👍

**Comment by thiennguyen1308** [comment]
@amizurov  Yup, it's enabled by default.
