### ISSUE TITLE
When is SocketChannel closed is netty 3.10?

### ISSUE THREAD

**Issue by QAZThe** [netty/netty#7859]
I dont know the internal system of netty so I came here for help.

I have two different systems with the same amount of load. In one of the system, I am seeing like a few SocketChannel close calls per day while the other has like 100 calls per day. 

This issue stats when the close method below is called from line 93 of [NioWorker class](https://github.com/netty/netty/blob/3.10/src/main/java/org/jboss/netty/channel/socket/nio/NioWorker.java)

       if (ret < 0 || failure) {
            k.cancel(); // Some JDK implementations run into an infinite loop without this.
            close(channel, succeededFuture(channel));
            return false;
        }

To debug this issue I am trying to find out what are the events that might cause this method to be called.  With what I have understood from the code, the method is called when SocketChannel is closed but what are the reasons for the SocketChannel to be closed? Is it closed when the host is down, host is idle for sometime or something else? Knowing this might help me figure out why the two different systems have different number of SockeChannel being closed.

**Comment by normanmaurer** [comment]
@QAZThe Sorry but netty 3.x is EOL for a long time. Please upgrade to a newer version.  That said this happens when either `read(...)` returns an error or EOF.
