### ISSUE TITLE
HttpPostRequestEncoder creates an invalid body 

### ISSUE THREAD

**Issue by jameskleeh** [netty/netty#7868]
### Expected behavior
The request is formed correctly

### Actual behavior
The line of the body starting the mixed part has duplicate boundaries.

<img width="849" alt="screen shot 2018-04-13 at 12 21 52 am" src="https://user-images.githubusercontent.com/1583789/38716883-2f3164f2-3eb1-11e8-9f02-afdaaa802d20.png">

### Steps to reproduce
Submit a request with 2 parts containing the same name in EncoderMode.RFC1738

### Minimal yet complete reproducer code (or URL to code)
https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostRequestEncoder.java#L647

### Netty version
4.1.23

### JVM version (e.g. `java -version`)
1.8.0_131

### OS version (e.g. `uname -a`)
Darwin Jamess-MacBook-Pro.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

**Comment by jameskleeh** [comment]
In this test, if you move the attribute to be after the files, the problem can be reproduced

https://github.com/netty/netty/blob/4.1/codec-http/src/test/java/io/netty/handler/codec/http/multipart/HttpPostRequestEncoderTest.java#L144

**Comment by normanmaurer** [comment]
@jameskleeh sorry I am currently super busy but you may want to provide a fix via PR if you can and I will be happy to review.

**Comment by vietj** [comment]
I think this issue can be closed because of https://github.com/netty/netty/pull/9270 @normanmaurer
