### ISSUE TITLE
Add support for IP_TRANSPARENT socket option for UDP connections

### ISSUE THREAD

**Issue by kubuzetto** [netty/netty#7871]
Push request at #6835 does not include 'transparent proxy' mode for UDP. setOption() function in EpollDatagramChannelConfig should include IP_TRANSPARENT option.

**Comment by normanmaurer** [comment]
@kubuzetto PRs welcome

**Comment by normanmaurer** [comment]
Fixed via https://github.com/netty/netty/pull/7872
