### ISSUE TITLE
NoopAddressResolverGroup immutability?

### ISSUE THREAD

**Issue by CodingFabian** [netty/netty#7873]
I am looking at a memory leak problem and was wondering if NoopAddressResolverGroup is working as intended.
We have multiple Bootstrap instances, which all do something like this:
```
      bootstrap = new Bootstrap();
      if (useProxyDnsResolution) {
        bootstrap.resolver(NoopAddressResolverGroup.INSTANCE);
      }
```
Now what happens is that for each Bootstrap (3 in the following picture) there is one key value pair added to the resolvers HashMap.

Is that intended? the NoopAddressResolver does not need the executor? it could always return the same instance regardless of the executor?
Are you sure that the cleanup of this shared instance is working fine or is this leaking resolvers?
<img width="1105" alt="screen shot 2018-04-17 at 11 07 26" src="https://user-images.githubusercontent.com/176132/38860126-c138a7da-422f-11e8-9500-8f52bc055b76.png">

**Comment by normanmaurer** [comment]
Let me close this as I think all if ok... if not please re-open with more details
