### ISSUE TITLE
LocalChannel / LocalServerChannel not respect ChannelOption. MAX_MESSAGES_PER_READ

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#7880]
LocalChannel / LocalServerChannel not respect ChannelOption.MAX_MESSAGES_PER_READ and just keeps processing messages until there are no more present.

**Comment by KowalczykBartek** [comment]
@normanmaurer do you mean MAX_MESSAGES_PER_READ in netty-5.0.0.Alpha ?

**Comment by normanmaurer** [comment]
Ups yes https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/ChannelOption.java#L83
