### ISSUE TITLE
AddressResolver.resolveAll doesn't return consistent result

### ISSUE THREAD

**Issue by mrniko** [netty/netty#7882]
### Expected behavior
AddressResolver.resolveAll always returns full list of ips.

### Actual behavior
AddressResolver.resolveAll returns some part of full list ips.

### Steps to reproduce
`dev.myredis.com` host has two ips: 127.0.0.2, 127.0.0.3.
I guess AddressResolver.resolveAll should always return these two ips, but it's not true on practice if DnsAddressResolverGroup object shared between multiple threads

If this object created per invocation then the problem is gone.
Seems like DnsAddressResolverGroup is not thread safe!

### Minimal yet complete reproducer code (or URL to code)
Here is my test case:
```java
        NioEventLoopGroup niogroup = new NioEventLoopGroup();
        
        DnsAddressResolverGroup group = new DnsAddressResolverGroup(NioDatagramChannel.class, DnsServerAddressStreamProviders.platformDefault());
        ExecutorService es = Executors.newFixedThreadPool(2);
        for (int i = 0; i < 100; i++) {
            es.execute(new Runnable() {
                @Override
                public void run() {
                    AddressResolver<InetSocketAddress> resolver = group.getResolver(niogroup.next());
                    try {
                        URI uri = new URI("redis://dev.myredis.com:6379");
                        Future<List<InetSocketAddress>> allNodes = resolver.resolveAll(InetSocketAddress.createUnresolved(uri.getHost(), uri.getPort()));
                        List<InetSocketAddress> list = allNodes.syncUninterruptibly().getNow();
                        System.out.println(list);
                    } catch (URISyntaxException e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }
                }
            });
        }

        Thread.sleep(10000);
        group.close();
        es.shutdown();
        niogroup.shutdownGracefully();
```

Output is:

[dev.myredis.com/127.0.0.3:6379, dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379, dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.2:6379, dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379, dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379, dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379, dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.2:6379, dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379, dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379, dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379, dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.2:6379, dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379, dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379, dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379, dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.2:6379, dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379, dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379, dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379, dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.2:6379, dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379, dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379, dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379, dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.2:6379, dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379, dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379, dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379, dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.2:6379, dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379, dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379, dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379, dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379, dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379, dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.2:6379]
[dev.myredis.com/127.0.0.3:6379]
[dev.myredis.com/127.0.0.3:6379]

But it always should be: [dev.myredis.com/127.0.0.2:6379, dev.myredis.com/127.0.0.3:6379]

### Netty version
4.1.23.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

### OS version (e.g. `uname -a`)
Windows 7

**Comment by normanmaurer** [comment]
@mrniko can you share a query that I can retry here to reproduce it ?

**Comment by mrniko** [comment]
I used http://maradns.samiam.org/ to reproduce that. You can find its config attached to this message.
[maradns-config.zip](https://github.com/netty/netty/files/1941275/maradns-config.zip)

**Comment by normanmaurer** [comment]
@mrniko I was looking for a query that I can run against a dns server that shows this behaviour :)

**Comment by mrniko** [comment]
sorry, I can't help here

**Comment by normanmaurer** [comment]
@mrniko I have an idea... can you actual disable the cache by using a `NoopDnsCache` and let me know if you still see the issue ?

**Comment by mrniko** [comment]
@normanmaurer How do I define it? DnsAddressResolverGroup doesn't expose any method to do it.

**Comment by normanmaurer** [comment]
@mrniko actually I think I was wrong and this needs a bit more work. I am looking into fixing it as we speak.

**Comment by normanmaurer** [comment]
@mrniko now for real... Can you check https://github.com/netty/netty/pull/7906. I think this will fix it as I could not reproduce it anymore with the pr pulled in.

**Comment by mrniko** [comment]
Thanks for your work! I tested it against default_dns_cache_fix. I don't see the issue anymore, but a new one - `java.net.UnknownHostException: failed to resolve 'dev.myredis.com' after 2 queries `. This problem is arise if DnsAddressResolverGroup object shared between multiple threads. Have a look at attached log [error.txt](https://github.com/netty/netty/files/1974469/error.txt)

**Comment by normanmaurer** [comment]
@mrniko I think you just close the channel to early. Use a `CountDownLatch` and only shutdown stuff after all queries returned.

**Comment by mrniko** [comment]
No, this won't happen if I comment out `resolver.close();` line

**Comment by normanmaurer** [comment]
@mrniko please show me the code you use... I tested it to resolve multiple different hostnames (like for example "web.de") and it always returns the same results.

**Comment by mrniko** [comment]
the code is at `Minimal yet complete reproducer code (or URL to code)` section

**Comment by normanmaurer** [comment]
yes I did and could not reproduce... Can you reproduce with query for example `web.de`

**Comment by normanmaurer** [comment]
Basically what I ask you is to change the code to:

```java
        NioEventLoopGroup niogroup = new NioEventLoopGroup();
        
        DnsAddressResolverGroup group = new DnsAddressResolverGroup(NioDatagramChannel.class, DnsServerAddressStreamProviders.platformDefault());
        ExecutorService es = Executors.newFixedThreadPool(2);
        CountDownLatch latch = new CountDownLatch(100);
        for (int i = 0; i < 100; i++) {
            es.execute(new Runnable() {
                @Override
                public void run() {
                    AddressResolver<InetSocketAddress> resolver = group.getResolver(niogroup.next());
                    try {
                        URI uri = new URI("redis://dev.myredis.com:6379");
                        Future<List<InetSocketAddress>> allNodes = resolver.resolveAll(InetSocketAddress.createUnresolved(uri.getHost(), uri.getPort()));
                        List<InetSocketAddress> list = allNodes.syncUninterruptibly().getNow();
                        System.out.println(list);
                    } catch (URISyntaxException e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    } finally {
                        latch.countDown();
                    }
                }
            });
        }
        latch.await();
        group.close();
        es.shutdown();
        niogroup.shutdownGracefully();
```

**Comment by mrniko** [comment]
@normanmaurer OK. Thanks for the clarification!
