### ISSUE TITLE
HpackDecoder's maxHeaderListSizeGoAway kills stream unnecessarily

### ISSUE THREAD

**Issue by ejona86** [netty/netty#7887]
Consider this a bit of a TODO for myself, although @Scottmitch or @normanmaurer may have opinions about avoiding killing the connection in this case.

### Expected behavior

Sending too large of headers would not unnecessarily kill the connection.

### Actual behavior

When maxHeaderListSizeGoAway is exceeded, HpackDecoder will throw a connection error, killing the entire connection.

```
                            // Check new header size against max header size
                            if ((long) index + nameLength > maxHeaderListSizeGoAway - headersLength) {
                                headerListSizeExceeded(maxHeaderListSizeGoAway);
                            }
```

Note, I'm not talking about the separate check later against maxHeaderListSize and throws a _stream_ error:
```
        // we have read all of our headers, and not exceeded maxHeaderListSizeGoAway see if we have
        // exceeded our actual maxHeaderListSize. This must be done here to prevent dynamic table
        // corruption
        if (headersLength > maxHeaderListSize) {
            headerListSizeExceeded(streamId, maxHeaderListSize, true);
        }
```

Even though both of those call `headerListSizeExceeded()`, they call different overloads of the method which will throw different types of exceptions (connection vs stream).

The value of maxHeaderListSizeGoAway is likely 1.25 the size of maxHeaderListSize, although I see there's some ways it could be something different and I didn't dig in more.

This killing of the connection seems unnecessary though, as:
1) It seems it would be pretty easy to throw away this batch of headers, by setting `headers` to a `Http2Headers` implementation that throws away further adds (similar complexity to `EmptyHttp2Headers`). This could be done any time `headersLength > maxHeaderListSize`.
2) When decode is called, the "entire header block is contained in {@code in}". So this protection doesn't protect us from buffering any more data; it only reduced the decoded headers size. That is, throwing away decoded headers as suggested in (1) does not seem to expose us to other problems.

Note also there are separate checks in `DefaultHttp2FrameReader.HeadersBlockBuilder` that protect against too large of compressed HEADERS+CONTINUATION. This is what constrains the size of `in`.

**Comment by normanmaurer** [comment]
I think what you said @ejona86 makes sense... want to do a pr ?

**Comment by ejona86** [comment]
I worked on the change last night :) but didn't send it out because I was investigating further changes. Sent it out now.
