### ISSUE TITLE
Bug in the method of onRemoval of the final instance variable threadLocal of Recycle

### ISSUE THREAD

**Issue by xiaoqiangCai** [netty/netty#7893]
### source code
private final FastThreadLocal<Stack<T>> threadLocal = new FastThreadLocal<Stack<T>>() {
        @Override
        protected Stack<T> initialValue() {
            return new Stack<T>(Recycler.this, Thread.currentThread(), maxCapacityPerThread, maxSharedCapacityFactor,
                    ratioMask, maxDelayedQueuesPerThread);
        }

        @Override
        protected void onRemoval(Stack<T> value) {
            // Let us remove the WeakOrderQueue from the WeakHashMap directly if its safe to remove some overhead
            if (value.threadRef.get() == Thread.currentThread()) {
               if (DELAYED_RECYCLED.isSet()) {
                   DELAYED_RECYCLED.get().remove(value);
               }
            }
        }
    };

### Bug description
In the method of onRemoval, value.threadRef which is assigned by the thread who invoke initialValue method  must not equal to Thread.currentThread which is running in the context of the cleanup task of FastThreadLocal.

### Netty version
4.1.24.Final
4.1.25.Final-SNAPSHOT

**Comment by normanmaurer** [comment]
@xiaoqiangCai actually I think the code is correct as e can only "safely" call the method if the Thread matches. If it not matches it will be handled by the nature of `WeakHashMap`.

Can you explain why you think it is wrong?

**Comment by xiaoqiangCai** [comment]
Sorry, it's my fault. I think wrongly the method of onRemoval will only be invoked by cleanup task however we could invoke  initiatively 'remove' method of FastThreadlocal to release more quickly.
