### ISSUE TITLE
ProxyHandler - Option to exclude URLs

### ISSUE THREAD

**Issue by jsachania** [netty/netty#7902]
### Expected behavior
There is a common use case to exclude URLs ($no_proxy env var) from going through proxy. I was looking to extend HttpProxyHandler but the class is marked as final. Is there a suggested way to handle it? 

### Netty version
4.1

**Comment by normanmaurer** [comment]
Not that I know of... Could you easily archive it if the class would be not final ?

**Comment by jsachania** [comment]
I don't think so. Even the`ProxyHandler#connect` is final. I am not sure making these extendable would be sufficient.

**Comment by kachayev** [comment]
@jsachania Introducing this functionality to `ProxyHandler` might violate the contract at least twice: `ProxyConnectionEvent` (someone in the pipeline might be waiting to get either this event or exception about connection failure) and `connectFuture` (same here, this will be never released or released w/o actual connection which might "confuse" other handlers in the pipeline). Is there a chance you can handle this *prior* of creating the pipeline (just do not include `ProxyHandler` in case you don't need it)?

**Comment by jsachania** [comment]
@kachayev I ended up creating a separate channel for handling http proxy which has ProxyHandler configured.

**Comment by kachayev** [comment]
@jsachania Cool! That's pretty much what I've talked about :)

**Comment by normanmaurer** [comment]
let me close this

**Comment by kachayev** [comment]
Would be nice to have this mentioned somewhere in the documentation... I've been working with code for quite some time, so let me check what can be done here.

**Comment by normanmaurer** [comment]
@kachayev PRs welcome of course :)
