### ISSUE TITLE
http/2 message aggregation

### ISSUE THREAD

**Issue by mosesn** [netty/netty#7908]
HTTP/1.1 supplies HttpObjectAggregator, which makes it easy to speak HTTP/1.1, since the entire message is in one piece.  There's no analog in the HTTP/2 Http2Frame API.  Does it make sense for netty to supply one, or should users roll our own buffering and aggregation?  Are there any plans to make an H2 object aggregator as is available for the H1 model?

**Comment by normanmaurer** [comment]
@mosesn What typo of frame would this produce ?

**Comment by bryce-anderson** [comment]
Good question. Either the h2 model could be more like the h1 model (unlikely to be what we want) or the h2 aggregator could at least aggregate the body of a stream into one big body. 

Another way to frame it is, "what _should_ people be doing if they want aggregation?" Should they do it themselves? Should they use the downgrade-to-http1 tools and use the http1 aggregation? 

I think what @mosesn is getting at is that we currently have an asymmetry, and what is the recommended way to rectify it. IMO, most servers/clients don't really want to be bothered with the details of if it's h1 or h2 under the hood, they just want their entire message.

**Comment by normanmaurer** [comment]
@bryce-anderson the question is if people only care about these semantics why not just use the HTTP2 -> HTTP1 conversation handlers we provide ? This way you can easily also aggregate stuff.

**Comment by normanmaurer** [comment]
@bryce-anderson maybe the solution would be to not copy the headers but create a wrapper around the headers that an map from http2 headers to http1 headers and vice-versa ?

**Comment by bryce-anderson** [comment]
@normanmaurer, that's a reasonable suggestion, we'll probably explore that.

**Comment by bryce-anderson** [comment]
I just wanted get a definitive answer to the original question so we can close this: it sounds like there aren't plans to build aggregation of H2 messages directly, correct?

**Comment by normanmaurer** [comment]
Correct... at least not for now. I think using the conversation layer is the better answer here. Patches welcome to improve performance of course

**Comment by zzmao** [comment]
@normanmaurer   I am thinking to implement a http2 message aggregator, since our project https://github.com/linkedin/ambry needs it.(Ambry plan is to handle http2 request only) 
Do you have any tips before I implement it?
