### ISSUE TITLE
Incorrect Exception Description

### ISSUE THREAD

**Issue by cwginac** [netty/netty#7910]
This function in AbstractChannelBuffer.java:

    public void writerIndex(int writerIndex) {
        if (writerIndex < readerIndex || writerIndex > capacity()) {
            throw new IndexOutOfBoundsException("Invalid readerIndex: "
                    + readerIndex + " - Maximum is " + writerIndex);
        }
        this.writerIndex = writerIndex;
    }

gives an incorrect IndexOutOfBoundsException description.  This exception will get thrown if the writerIndex is too low (lower than readerIndex), or too high (greater than the capacity).

The description should be more like "Invalid writerIndex: XX - Minimum is: (readerIndex) - Maximum is: (capacity).

**Comment by cwginac** [comment]
Sorry, this is in 3.10 branch (specifically using 3.10.6).

**Comment by normanmaurer** [comment]
3.x is EOL since at least 1,5 years so I think we can just close this ?
