### ISSUE TITLE
DnsNameResolver.resolveAll(...) does not always follow CNAMEs

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#7915]
At the moment if you do a resolveAll and at least one A / AAAA record is present we will not follow any CNAMEs that are also present. I wonder if this is bug or a "feature". I would have expected to have CNAMEs followed as well honestly.

**Comment by normanmaurer** [comment]
@slandelle @trustin @Scottmitch @carl-mastrangelo @ejona86 @mosesn Any thoughts on this ?

**Comment by normanmaurer** [comment]
Also related to this the JDK always seems to follow the CNAME here.

**Comment by mosesn** [comment]
Yeah, I would copy whatever InetAddress.resolveAllByName does.  I think that's the most intuitive.  If folks need to have a resolveAll that doesn't follow CNAMEs we can add a new API.

**Comment by trustin** [comment]
+1 for having the same behavior with OpenJDK. Not sure if we need an option for customizing it.

**Comment by ejona86** [comment]
Note that InetAddress.resolveAllByName is OS-defined behavior, not JDK.
