### ISSUE TITLE
what does PageRun/PoolSubpage mean？

### ISSUE THREAD

**Issue by zekaryu** [netty/netty#7924]
In comment of io.netty.buffer.PooledChunk  class，the first comment description said：

` ** Description of algorithm for PageRun/PoolSubpage allocation from PoolChunk**`

I just don't get the meaning of “PageRun/PoolSubpage”，can anyone tell me how to understand it

**Comment by normanmaurer** [comment]
I think your best bet is to read the jemalloc white paper:

https://www.bsdcan.org/2006/papers/jemalloc.pdf

**Comment by zekaryu** [comment]
OK, thank you
