### ISSUE TITLE
Why is the maven.compiler.target set to 1.6?

### ISSUE THREAD

**Issue by cstancu** [netty/netty#7928]
Hi, I have a simple question. While playing around with building the Netty integration tests from source I noticed that the [maven.compiler.target is set at 1.6](https://github.com/netty/netty/blob/cff87de44cfaa4544360715dc83e5ad1aa2c0bd7/pom.xml#L180)?
```   
<maven.compiler.target>1.6</maven.compiler.target>
```

 What is the reason for that? Is this a strong requirement for Netty? Thank you!

**Comment by normanmaurer** [comment]
It’s what we supported for a long time but will change in the next major release. We just can not do this in a bugfix release

**Comment by cstancu** [comment]
And another related question: would it be possible to release the integration tests on maven? What I mean by integration tests is code under `src/test` packages, e.g., [the Netty transport tests.](https://github.com/netty/netty/tree/4.1/transport/src/test/java/io/netty). The reason I am asking for this is that I work on the [GraalVM/SubstrateVM project](https://github.com/oracle/graal/tree/master/substratevm) and I am running some of these tests to get Netty running on our VM. I currently build them from source, which is not such a big deal, but an integration with maven would make things easier. Thank you!
