### ISSUE TITLE
Proxy rules doesn't get applied while connecting through Netty

### ISSUE THREAD

**Issue by ldclakmal** [netty/netty#7930]
### Description
It is observed that some rules applied thorough a proxy is not supported by Netty because of the HTTP CONNECT request is sent initially. 

### Steps to reproduce
Setup the following proxy with the given rules and send a GET request to http://abc.com/foo/bar/1.

Proxy - Squid
Rule - Block destination URL http://abc.com/foo/bar/1

#### Expected behaviour
It is expected to **block** http://abc.com/foo/bar/1 but **allow** http://abc.com/foo/bar/2

#### Actual behavior
The actual behavior is that both URLs are allowed and  200 OK responses are returned.
But the expected behavior can be seen by Mozilla Firefox for the same proxy with same set of rules.

### Netty version
4.1.19.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_171"

**Comment by ldclakmal** [comment]
I tested with Netty version **4.1.24.Final** as well. But the issue is still there.
Following is a abstract code of the Netty pipeline.

```
    @Override
    protected void initChannel(SocketChannel socketChannel) throws Exception {
        ChannelPipeline clientPipeline = socketChannel.pipeline();
        configureProxyServer(clientPipeline);
        if (sslConfig != null) {
            clientPipeline.addLast(Constants.SSL_HANDLER, new SslHandler(sslEngine));
        } else {
            configureHttpPipeline(clientPipeline, targetHandler);
        }
    }

    private void configureProxyServer(ChannelPipeline clientPipeline) {
        if (proxyServerConfiguration != null) {
            if (proxyServerConfiguration.getProxyUsername() != null
                    && proxyServerConfiguration.getProxyPassword() != null) {
                clientPipeline.addLast(Constants.PROXY_HANDLER,
                        new HttpProxyHandler(proxyServerConfiguration.getInetSocketAddress(),
                                proxyServerConfiguration.getProxyUsername(),
                                proxyServerConfiguration.getProxyPassword()));
            } else {
                clientPipeline.addLast(Constants.PROXY_HANDLER,
                        new HttpProxyHandler(proxyServerConfiguration.getInetSocketAddress()));
            }
        }
    }
```

This is a Wireshark screenshot when I access blocked URL from Firefox.
![image](https://user-images.githubusercontent.com/9639050/39981803-bd9fe570-576f-11e8-9eb6-c76fdc922697.png)

This is a Wireshark screenshot when I access blocked URL from HTTP client based on Netty.
![image](https://user-images.githubusercontent.com/9639050/39981774-a1c60d5c-576f-11e8-9c07-47481d4f6885.png)

**Comment by slandelle** [comment]
@ldclakma HttpProxyHandler currently only supports HTTP tunneling, hence performing an initial CONNECT request. This mechanism is standardly used for HTTPS and WebSockets. Usually, it's not used for clear HTTP and it seems Squid doesn't support it. Just connect to your proxy and send a request with an absolute url.

**Comment by ldclakmal** [comment]
@slandelle Following is a Wireshark screenshot when I send request with and absolute URL. But also doesn't get blocked. So, is that due to CONNECT request initially sent or a bug of squid?

![image](https://user-images.githubusercontent.com/9639050/39989533-df1d218c-5787-11e8-907f-29d2959cff37.png)

**Comment by slandelle** [comment]
Don't use HttpProxyHandler. Just connect to your proxy and send a request with an absolute url.

**Comment by ldclakmal** [comment]
Thank you for the response.

**Comment by nathsomdatta59** [comment]
@ldclakmal @normanmaurer  I have similar issue when I created a webclient to connect through proxy.  The issue I created : https://github.com/issues/created?issue=nathsomdatta59%7Caws-web%7C1
Not sure if this should be a discussion topic.  I letting almost everything through squid. 
Any insight will be helpful.
