### ISSUE TITLE
when using udp NioDatagramChannel , the process will takes tens of thousand of file Descriptor 

### ISSUE THREAD

**Issue by JasonHuangHuster** [netty/netty#7931]
### Expected behavior

when using udp NioDatagramChannel , the process will takes tens of thousand of file Descriptor 

### Actual behavior

in normal udp situation , every message will takes a fd , and close method should called on the socket to free the fd after msg was send . my process takes 20k fds , and they are ocopied by udp . 

### Netty version

netty-all-4.0.25

### JVM version (e.g. `java -version`)

Java(TM) SE Runtime Environment (build 1.6.0_21-b06)

### OS version (e.g. `uname -a`)

x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
Please upgrade to a recent version and report back. The version you are using is very old. Also please provide a reproducer

**Comment by JasonHuangHuster** [comment]
this fd leak is not caused by netty io ,  this issue could be closed , tks for your help ! :D
