### ISSUE TITLE
CodecOutputList does not implement java.util.list.add(int index, E element) correctly

### ISSUE THREAD

**Issue by jozefbalga** [netty/netty#7938]
### Expected behavior
When an element is added to the beginning of CodecOutputList, the remaining elements should be shifted to the right, see https://docs.oracle.com/javase/8/docs/api/java/util/List.html#add-int-E-
### Actual behavior
The new element is added to the correct position, but the remaining elements are modified.
### Steps to reproduce
Create a new CodecOutputList, add integer 1, then add interger 0 to the position 0. The element at position 1 is null
### Minimal yet complete reproducer code (or URL to code)
package io.netty.handler.codec;

import java.util.ArrayList;
import java.util.List;

import org.junit.Assert;
import org.junit.Test;

import io.netty.handler.codec.CodecOutputList;

public class CodecOuputListTest {

	@Test
	public void testArrayListAdd() {
		List<Object> arrayList = new ArrayList<>();
		arrayList.add(1);
		arrayList.add(0, 0);
		Assert.assertEquals(2, arrayList.size());
		Assert.assertEquals(0, arrayList.get(0));
		Assert.assertEquals(1, arrayList.get(1));
	}

	@Test
	public void testCodecOutputListAdd() {
		List<Object> codecOutputList = CodecOutputList.newInstance();
		codecOutputList.add(1);
		codecOutputList.add(0, 0);
		Assert.assertEquals(2, codecOutputList.size());
		Assert.assertEquals(0, codecOutputList.get(0));
		Assert.assertNotNull(codecOutputList.get(1));
		Assert.assertEquals(1, codecOutputList.get(1));
	}

}
### Netty version
4.1.25
### JVM version (e.g. `java -version`)
1.8.0_152
### OS version (e.g. `uname -a`)
Linux wks-balga 4.14.35 #1 SMP Mon Apr 23 06:09:12 UTC 2018 x86_64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz GenuineIntel GNU/Linux

**Comment by normanmaurer** [comment]
@jozefbalga thanks.... working on a fix.

**Comment by normanmaurer** [comment]
@jozefbalga PTAL https://github.com/netty/netty/pull/7939

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7939
