### ISSUE TITLE
channelWritabilityChanged called multiple times

### ISSUE THREAD

**Issue by scottsue** [netty/netty#7944]
### Expected behavior
When we have slow consumers, the channelWritabilityChanged method will be called.  Upon inspecting the channel writable state, we can check to see if we are going into a writable -> non-writable (aka slow consumer), or non-writable -> writable (aka coming out of a slow consumer back into normal) state.  

### Actual behavior
What we're seeing is that netty sometimes calls the channelWritabilityChanged multiple times when the channel itself is writable.  i.e. our assumption is that it channelWritabilityChanged will go from writable -> non-writable and vice-versa.  What we have observed is that when channelWritabilityChanged is invoked, it can sometimes be writable -> writable.

### Steps to reproduce
1) Setup a client and server socket
2) From the server socket, flood the channel with messages to induce slow consumer.
3) The channelWritabilityChanged method is called from the same thread (EventLoop thread), however upon checking the channel it can sometimes be writable multiple times one after the other, i.e. no interleaving non-writeable state

### Minimal yet complete reproducer code (or URL to code)
Unfortunately our code is wired in quite tight into this at the moment so will be difficult to give a reproducer

### Netty version
4.1.20

### JVM version (e.g. `java -version`)
Oracle 1.8.0_111, Zing 1.8.0-zing_17.06.1.0

### OS version (e.g. `uname -a`)
Linux server-name 2.6.32-696.10.1.el6.x86_64 #1 SMP Tue Aug 22 18:51:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

MacOS High Sierra

**Comment by normanmaurer** [comment]
I suspect this is a matter of the channel become writable again before we were able to fire the event. That said these events are harmless

**Comment by scottsue** [comment]
Hi Norman thanks.  Ok if this is expected, I'll need to manage the state of the connection outside of netty.  From our applications perspective, we listen to these events to perform certain logic, dropping events, blocking threads whilst flushing data, etc.  Are these events something that I can rely on to perform this 'critical' logic? Or are these events supposed to be only used for more informational purposes?

**Comment by normanmaurer** [comment]
@scottsue just to clarify it may be that you see multiple notifications for the same writability state (kind of like spurious wakeups) but you should never be NOT notified. So I would say there may be false-positives but never be any missed events. So I think these events should still be useful for your use case ?

**Comment by scottsue** [comment]
Thanks @normanmaurer for the clarification
