### ISSUE TITLE
PongWebSocketFrames are inaccessible in handlers downstream of a WebSocketClientProtocolHandler

### ISSUE THREAD

**Issue by nicktrav** [netty/netty#7954]
This is probably more of a question / request rather than a bug, as it looks like this was a deliberate decision ([source](https://github.com/netty/netty/blob/netty-4.1.25.Final/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketProtocolHandler.java#L32-L35)).

The use-case is a handler being able to assert that a pong frame was received from a Netty-based proxy server.

### Expected behavior

`PongWebSocketFrame`s are visible to a channel handler installed _downstream_ of a `WebSocketClientProtocolHandler`.

### Actual behavior

Sending a `PingWebSocketFrame` from a client to a server results in receipt of a `PongWebSocketFrame` by the client in the `WebSocketClientProtocolHandler`, but this frame is not propagated further along the channel pipeline.

### Steps to reproduce

I've pushed a commit [here](https://github.com/nicktrav/netty/commit/4cae21eb36fe873d24073e730cbda9bb1994741b) which demonstrates the issue.

### Minimal yet complete reproducer code (or URL to code)

Check out commit and run:
```bash
$ mvn test -pl codec-http -Dtest=io.netty.handler.codec.http.websocketx.PongFrameIgnoreTest
```

### Netty version

`4.1.25.Final`. Also run against `HEAD` of `4.1` branch @ 987c44388.

### JVM version (e.g. `java -version`)

```bash
$ java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```

### OS version (e.g. `uname -a`)

```bash
$ uname -a
Darwin nickt.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
```

**Comment by normanmaurer** [comment]
@nicktrav actually I think the idea was that usually PONG frames should be dropped on the floor. That said I would argue that is not the best thing to do "magically" and it may be better to let the user decide to drop it or not. So maybe we should not do this ?

**Comment by nicktrav** [comment]
Yeah, that would be awesome for us. Principle of least surprise, etc, etc.

I might take a crack at this one, if that's cool? I was thinking I'd just remove those lines so the frames are propagated, and I'll add a couple tests for it in the server and client handler subclasses. Wdyt?

**Comment by normanmaurer** [comment]
yeah... please :)

**Comment by doom369** [comment]
@normanmaurer wouldn't this cause regression? Maybe making `decode` method of `WebSocketServerProtocolHandler` public would be enough, so users can override this behavior?

**Comment by normanmaurer** [comment]
@doom369 I think we should just do what @trustin suggested in the PR and make it configurable and use the old behaviour as default.

**Comment by amizurov** [comment]
@nicktrav , @normanmaurer In our case we extend ``WebSocketServerProtocolHandler`` and override decode() for handling pong and close frames, but we can add some handler before ``WebSocketServerProtocolHandler`` and listen all web socket frames. Maybe in downstream handler anybody want listen close frame ???
