### ISSUE TITLE
OpenSSL server has a lower throughput than JDK SSL with larger responses

### ISSUE THREAD

**Issue by timyates** [netty/netty#7957]
### Expected behavior

I expected the native OpenSSL provider to be faster than the JDK provider, no matter what the size of the response payload is.

### Actual behavior

A Netty server using the JDK SSL provider is faster for any payload (I have tested 1MB up, and see the same results)

The results below are from running on an `i3.xlarge` EC2 box running `Amazon Linux AMI 2018.03.0`, but I have seen reproducible similar behaviour running on both Alpine Linux, and Os X 10.13.4.

OpenSSL on this EC2 box has the version:

```
$ openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017
```

### Steps to reproduce

I have linked to a project that reproduces the problem reliably for me, running the `runProfiling.sh` script executes 6 tests.

1. empty response (OpenSSL)
2. empty response (JDK SSL)
3. 5MB response (OpenSSL)
4. 5MB response (JDK SSL)
5. 20MB response (OpenSSL)
6. 20MB response (JDK SSL)

The results for these tests (a full run takes around 60 mins) are then available in `build/jmeter-report`.

#### Empty Response

The empty test results are as expected;

OpenSSL
![image](https://user-images.githubusercontent.com/49317/40312057-ab3144de-5d09-11e8-9178-744bdff5087a.png)
JDK
![image](https://user-images.githubusercontent.com/49317/40312076-b76539ea-5d09-11e8-83b8-089375c92d8c.png)

#### 5MB Response

The JDK SSL version gives a higher throughput than OpenSSL which is unexpected...

OpenSSL
![image](https://user-images.githubusercontent.com/49317/40312152-eb5c7ce0-5d09-11e8-9ccd-d5d3584c05bc.png)
JDK
![image](https://user-images.githubusercontent.com/49317/40312175-f72a4840-5d09-11e8-80b0-a752b701ca6a.png)

#### 20MB response

Again, the JDK SSL version has a higher throughput

OpenSSL
![image](https://user-images.githubusercontent.com/49317/40312246-35bcf580-5d0a-11e8-862d-79c5a42189b8.png)
JDK
![image](https://user-images.githubusercontent.com/49317/40312252-3fa3f954-5d0a-11e8-9325-79a5c0a79071.png)

### Minimal yet complete reproducer code (or URL to code)

https://github.com/timyates/netty-openssl-perf-test

Run `./runProfiling.sh` and wait (around an hour) for the 6 tests to generate jMeter dashboards.

### Netty version

```
4.1.25.Final
```

and

```
io.netty:netty-tcnative-boringssl-static:2.0.8.Final
```

### JVM version (e.g. `java -version`)

```
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
```

### OS version (e.g. `uname -a`)

```
Linux ip-172-31-12-49 4.14.26-46.32.amzn1.x86_64 #1 SMP Fri Mar 30 22:29:54 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by timyates** [comment]
CC: @ldaley

**Comment by normanmaurer** [comment]
Are you sure you use the same ciphers ?

**Comment by timyates** [comment]
I thought they were the same...

Looking again with wireshark output when running the JDK SSL version, I get (in the Server Hello)

> Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)

But with the OpenSSL version, I get:

> Cipher Suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)

**Comment by normanmaurer** [comment]
@timyates please set the used cipher to the same (via the SslContextBuilder) and re-run. TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 is not supported by Java8 so no-wonder you see different ones.

**Comment by timyates** [comment]
Cool, I've [set both](https://github.com/timyates/netty-openssl-perf-test/commit/8e54451fe9c09c8414b9666d11ceff2d498aefd9) to use `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA`, and will return with results once it's finished profiling 👍

**Comment by timyates** [comment]
Specifying the cipher seems to have solved it 🤯

Is there a way to decide on a cipher, or collection of them?  I found the [table here](https://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html#SupportedCipherSuites) which by trial and error I ended up with `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA` as also working with both the JDK and OpenSSL.

Results for the record:

### `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA`

#### 20MB response

OpenSSL
![image](https://user-images.githubusercontent.com/49317/40328390-1a829548-5d3e-11e8-805e-240573c228e7.png)
JDK
![image](https://user-images.githubusercontent.com/49317/40328407-2bb63a72-5d3e-11e8-9439-4d550ff0d7b5.png)

### `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA`

#### 20MB response

OpenSSL
![image](https://user-images.githubusercontent.com/49317/40328452-5aa1f13c-5d3e-11e8-9790-37e8722b995b.png)
JDK
![image](https://user-images.githubusercontent.com/49317/40328476-6d30d7d2-5d3e-11e8-901a-def9f1691748.png)

**Comment by normanmaurer** [comment]
@timyates hmm I think we not provide anything atm. But let me add something that allows to find ciphers that work for all.

**Comment by timyates** [comment]
Cool, thanks again!

Can you think of a reason why jMeter negotiated a cipher with OpenSSL that Java does not support? 🤔

No worries if not, I'll do some digging 👍

**Comment by normanmaurer** [comment]
@timyates maybe you use Java 9 or higher on the system you run JMeter on ?

**Comment by normanmaurer** [comment]
Also let me close this issue.
