### ISSUE TITLE
JXRay: Reference Chains for Bad Primitive Arrays: big overhead from netty 

### ISSUE THREAD

**Issue by Tagar** [netty/netty#7959]
We started looking at YARN NodeManager GC issues and most impact comes 
according to http://www.jxray.com/ comes from netty with a huge portion of buffers being all zeros:

"The problem is that Netty has various buffers managed by netty. 
They may be too big, so a big portion of them stays unused, containing only zeroes"

### Expected behavior
Allocated buffers' sized accordingly to workload. 

### Actual behavior
- A lot of memory overhead for the application.
- Most of buffers are all-zeros.
- Huge GC overhead.

### Steps to reproduce
Hard to reproduce outside of a live Hadoop Yarn application, but we can provide java heap dump,
or full jxray report.

### Netty version
netty-3.10.6

### JVM version (e.g. `java -version`)

> $ java -version
> java version "1.8.0_152"
> Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
> Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
> 

### OS version (e.g. `uname -a`)

> RHEL 7.4
> Linux 3.10.0-693.11.6.el7.x86_64
> 

![image](https://user-images.githubusercontent.com/3013418/40331513-df1e40a4-5d0d-11e8-935d-3240f49b2e19.png)

**Comment by slandelle** [comment]
You're using a very outdated version. Only the 4.1 train is currently maintained.
Then, Netty 4.0 introduced new memory management mechanism and it's likely that the problem you mention has been fixed.
You need to upgrade to latest 4.1 and then report back if issue still exists.

**Comment by normanmaurer** [comment]
@Tagar beside what @slandelle said this is kind expected as the PoolChunk is part of the `PooledByteBufAllocator` and so the memory is pooled. You may want to adjust the settings for `PooledByteBufAllocator` and use settings that better match your requirement / expectations.

There is really nothing wrong here.
