### ISSUE TITLE
DTLS in Netty

### ISSUE THREAD

**Issue by MarkVilkel** [netty/netty#7960]
I'm using netty 4.1.25.

Is it possible somehow to use the same io.netty.handler.ssl.SslHandler instance for NioDatagramChannel, having NioServerSocketChannel between the same client and the server?

I mean the situation when a client app has secured connection with a server via NioServerSocketChannel. And then the same client decides to exchange messages with the same server via NioDatagramChannel, still having alive NioServerSocketChannel. Thus the client will have both channels active and secured.

Server can close SslHandler when NioServerSocketChannel dies.

Of course would be nice to have fully independent DTLS in netty.

**Comment by normanmaurer** [comment]
@MarkVilkel I dont think so... sorry

**Comment by yulianoifa-mobius** [comment]
Please see BC and Netty based DTLS Implementation
https://github.com/mobius-software-ltd/java-dtls
