### ISSUE TITLE
HttpClientCodec emits LastHttpContent if content-length=0

### ISSUE THREAD

**Issue by buchgr** [netty/netty#7962]
The `HttpClientCodec` emits a `EmptyLastHttpContent` message if the HTTP/1.1 response is empty and a `Content-Length: 0` header being present: https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java#L255. In HTTP/1.1 I would expect `LastHttpContent` to only be emitted for chunked encoding. WDYT?

**Comment by vietj** [comment]
@buchgr I think it's expected, unless the first message `HttpResponse` is updated and changed to `FullHttpResponse`: the application using this handler will always expect to receive a `LastHttpMessage` as part of the messages emitted by this handler.

**Comment by buchgr** [comment]
makes sense. thanks :-)
