### ISSUE TITLE
DefaultHttpResponse does not implement equals and hashCode to cover response status

### ISSUE THREAD

**Issue by ewie** [netty/netty#7964]
### Expected behavior
Two DefaultHttpResponse instances with different response status should not be considered equal. Headers and HTTP version are already covered in DefaultHttpMessage. DefaultFullHttpResponse also covers content and trailing headers. I would assume the response status is considered as well.

### Actual behavior
Response status is ignored by equals and hashCode. DefaultHttpResponse does not override those methods.

### Steps to reproduce
Run example below.

### Minimal yet complete reproducer code
```java
import io.netty.handler.codec.http.DefaultHttpResponse;
import io.netty.handler.codec.http.HttpResponseStatus;
import io.netty.handler.codec.http.HttpVersion;

class ResponseStatusEquality
{
  public static void main(String... args)
  {
    var ok = new DefaultHttpResponse(HttpVersion.HTTP_1_1, HttpResponseStatus.OK);
    var notFound = new DefaultHttpResponse(HttpVersion.HTTP_1_1, HttpResponseStatus.NOT_FOUND);
    if (ok.equals(notFound)) {
      throw new AssertionError(); // should not throw!
    }
  }
}
```

### Netty version
4.1.25.Final

### JVM version (e.g. `java -version`)
openjdk version "10.0.1" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10)
OpenJDK 64-Bit Server VM (build 10.0.1+10, mixed mode)

### OS version (e.g. `uname -a`)
Linux 4.16.10

**Comment by normanmaurer** [comment]
sounds like a bug to me... looking now

**Comment by normanmaurer** [comment]
@ewie thanks for reporting, fixed by https://github.com/netty/netty/pull/7965
