### ISSUE TITLE
Make Http2UnknownFrame extend Http2StreamFrame rather than Http2Frame

### ISSUE THREAD

**Issue by Bennett-Lynch** [netty/netty#7969]
This is a follow-up issue regarding: https://github.com/netty/netty/issues/7860

### Expected behavior

Writing an `Http2UnknownFrame` to a child channel will be written to the parent channel and underlying HTTP/2 connection via `Http2MultiplexCodec`.

When `Http2MultiplexCodec` reads an `Http2UnknownFrame`, it will be propagated to the correct child channel.

### Actual behavior

`Http2MultiplexCodec` rejects the write since `Http2UnknownFrame` is not an `instanceof Http2StreamFrame`.

https://github.com/netty/netty/blob/dfeb4b15b587bf5298555e969a01378853efab8f/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java#L1021-L1028

`Http2MultiplexCodec` does not propagate reads to child channels since `Http2UnknownFrame` is not an `instanceof Http2StreamFrame`.

https://github.com/netty/netty/blob/dfeb4b15b587bf5298555e969a01378853efab8f/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java#L219-L221

### Proposal

`Http2UnknownFrame` should extend `Http2StreamFrame`, rather than `Http2Frame`, as it already defines the two stream-related methods that the two interfaces differ in.

Should it possibly declare an `isEndStream` method as well, similar to `Http2DataFrame`?

**Comment by normanmaurer** [comment]
@Bennett-Lynch let it extend `Http2StreamFrame` sounds like the correct thing to do. Would you be interested in proving a PR ?

I think I would leave the `isEndStream` as it is and just use the `Http2Flags` for it.

**Comment by normanmaurer** [comment]
@Bennett-Lynch I had a bit time this morning so I just did it myself and adding unit tests:

https://github.com/netty/netty/pull/7976

PTAL

**Comment by Bennett-Lynch** [comment]
Thanks, @normanmaurer -- change looks good to me.

Fine with using `Http2Flags` for detecting `isEndStream`, but may I ask your reasoning for it?  Maintaining a consistent interface across frame types seems more ideal, but I realize these UnknownFrames are a bit of an edge case.

**Comment by normanmaurer** [comment]
@Bennett-Lynch because its redundant as it exists in the flags already (and you can have other flags as well).
