### ISSUE TITLE
NioEventLoop has too low MAX_SCHEDULED_DAYS

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty#7970]
### Expected behavior
Create a scheduled task with some reasonable, arbitrary delay.

### Actual behavior

`NioEventLoop.validateScheduled`   throws an illegal argument exception when passing a delay of greater than 3 years. 

### Netty version
4.1.25

A user of gRPC noticed that when passing a really big deadline, the above exception was thrown.  The deadline in question was 100 years, which, while high, was previously allowed.   [EpollEventLoop](https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java) allows about 31 years, but this actually appears wrong.    The man page says the number of /nanoseconds/ must be less than 999999999, not the number of seconds, as implemented.

I think a more reasonable number would be the Long.MAX_VALUE of nanos, which is about 292 years.  If the underlying poller can't support, I think clamping the value is right.   The ScheduledFuture can keep its deadline, there would just be a spurious wake up. 

cc: @ejona86

**Comment by normanmaurer** [comment]
This sounds like a better solution then throwing... let me work on a fix
