### ISSUE TITLE
WebsocketClientHandshaker can fail if multiple X-Websocket-Key headers are present on the upgrade request

### ISSUE THREAD

**Issue by nicktrav** [netty/netty#7973]
### Expected behavior

A websockets handshake should not fail if a `X-Websockets-Key` header exists in the custom headers passed to the handshaker.

### Actual behavior

The handshake fails if the server picks the incorrect key on which to compute its challenge response (as opposed to the key that is set by the `WebsocketsClientHandshaker`).

### Steps to reproduce

Use the `WebsocketsClientHandshaker` to send a request to a websockets server along with passing custom headers that also contain an `X-Websockets-Key` header.

If the server happens to pick the _last_ `X-Websockets-Key` in the request headers on which to compute the `X-Websockets-Accept` value, the client handshake will fail with the following, as the `X-Websockets-Accept` value it expects was calculated on the _first_ `X-Websockets-Key`:

```
20:04:35.727 [nioEventLoopGroup-3-1] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.http.websocketx.WebSocketHandshakeException: Invalid challenge. Actual: w7cyq/iodDhF6MfTw9LCsDqUyBQ=. Expected: +RND8EYF2d5MkuthghnnAyg9DN0=
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker13.verify(WebSocketClientHandshaker13.java:223)
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker.finishHandshake(WebSocketClientHandshaker.java:216)
	at io.netty.handler.codec.http.websocketx.WebSocketClientProtocolHandshakeHandler.channelRead(WebSocketClientProtocolHandshakeHandler.java:57)
... snip ...
```

### Minimal yet complete reproducer code (or URL to code)

Reproducer [here](https://github.com/nicktrav/netty/commit/219d1dd5c00a2d2d92ef8224392f88a2a386668c).

### Netty version

HEAD of 4.1 branch, as of 8a8576150.

### JVM version (e.g. `java -version`)

```
$ java -version
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

### OS version (e.g. `uname -a`)

```
$ uname -a
Darwin nickt.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
```

**Comment by nicktrav** [comment]
One way to fix this could be to add the custom headers _first_, and the call `HttpHeaders#set` for each of the websocket-specific headers. It would require some re-ordering of calls in `WebSocketClientHandshaker13#newHandshakeRequest` (and variants).

One downside to this approach is that is would overwrite any header values that are present. I don't know if that's an issue though, as there should never really be duplicate handshake headers on the upgrade request. I couldn't see anything in the spec about this either.

Another option could be to throw, although that feels a little heavy handed.

If either of these sound reasonable, I can open up a PR with a fix.

**Comment by normanmaurer** [comment]
I think I would go with the first approach
