### ISSUE TITLE
[QUESTION] about the toHandle(int bitmapIdx)  method of PoolSubpage

### ISSUE THREAD

**Issue by zekaryu** [netty/netty#7977]
private long toHandle(int bitmapIdx) {
        return 0x4000000000000000L | (long) bitmapIdx << 32 | memoryMapIdx;
    }

When I study the code, at first I just cant figure out what is “ 0x4000000000000000L”  here for ??
Then I googled it, someone explained that it is used to help distinguish whether the init operation is for subpage or not:

    void initBuf(PooledByteBuf<T> buf, long handle, int reqCapacity) {
        int memoryMapIdx = memoryMapIdx(handle);
        int bitmapIdx = bitmapIdx(handle);
        if (bitmapIdx == 0) {
            byte val = value(memoryMapIdx);
            assert val == unusable : String.valueOf(val);
            buf.init(this, handle, runOffset(memoryMapIdx) + offset, reqCapacity, runLength(memoryMapIdx),
                     arena.parent.threadCache());
        } else {
            initBufWithSubpage(buf, handle, bitmapIdx, reqCapacity);
        }
    }

    private static int bitmapIdx(long handle) {
           return (int) (handle >>> Integer.SIZE);
    }

here if bitmapIdx == 0 means init normal buffer , if not then init subpage buffer.

    private void initBufWithSubpage(PooledByteBuf<T> buf, long handle, int bitmapIdx, int reqCapacity) {
        assert bitmapIdx != 0;
        int memoryMapIdx = memoryMapIdx(handle);PoolSubpage<T> subpage = subpages[subpageIdx(memoryMapIdx)];
        assert subpage.doNotDestroy;
        assert reqCapacity <= subpage.elemSize;

        buf.init(
            this, handle,
            runOffset(memoryMapIdx) + (bitmapIdx & 0x3FFFFFFF) * subpage.elemSize + offset,
                reqCapacity, subpage.elemSize, arena.parent.threadCache());
    }

so the only reason of this action( "bitmapIdx & 0x3FFFFFFF" ) is to eliminate the effect of  “ 0x4000000000000000L” , am I right？ 
Because there is no javadoc about this , so I think it's a little bit obscure to understand
Since I'm not a English native speaker ,maybe my expression is a bit clumsy，I‘m not sure if I make my point clearly?@trustin @normanmaurer

**Comment by normanmaurer** [comment]
Yeah you are right.
