### ISSUE TITLE
exceptioncaught closing 1 channel will effect other channels when a client connects multiple servers

### ISSUE THREAD

**Issue by tommwang** [netty/netty#7978]
### Expected behavior 
only current channel be closed when exceptioncaught
### Actual behavior
others channel lost but checking isactive is true
### Steps to reproduce
there is a client, connecting to multiple servers with different IP and same port. when 1 channel has Exception, handler will go into exceptioncaught method, ctx.close(). then current channel will be closed. that is correct. but other channel cannot send or receive data anymore. if you check isactive, showing true.
### Netty version
 5.0.0.apha 2
### JVM version (e.g. `java -version`)
 1.8
### OS version (e.g. `uname -a`)
ubatu

**Comment by normanmaurer** [comment]
@tommwang 5.0.2 is super old.. Use 4.1.25.Final and test again. Also you need to at least give us some code to reproduce this.

**Comment by tommwang** [comment]
@normanmaurer thanks, that is an old project using netty_5.2, anyway we will try latest version 4 or 5_alpha3

**Comment by tommwang** [comment]
Tried v4, issue has not been resolved.
Just noted here.

**Comment by normanmaurer** [comment]
@tommwang thanks
