### ISSUE TITLE
Application crashing with memory leaks

### ISSUE THREAD

**Issue by hiteshkotian** [netty/netty#7983]
### Actual behavior
I have an application that I built with netty version 4.0.40.Final. The application seems to be crashing every hour and when I analyzed the dump file, it looks like most of the leaks are happening because of "io.netty.util.concurrent.SingleThreadEventExecutor". Can someone please help me out with this?

### Netty version
4.0.40.Final 

### JVM version (e.g. `java -version`)
IBM Java 1.8

### OS version (e.g. `uname -a`)
Windows Server 2012  R2

**Comment by normanmaurer** [comment]
What you mean by leaks ? Why it crashes ? Also can you share the dump ?

**Comment by hiteshkotian** [comment]
Actually I can't delete th

**Comment by hiteshkotian** [comment]
@normanmaurer : Sorry I was told I can't share the heap dumps. But I think I might have figured out where the problem could be. 

Is it ok if I get back to you in a few days? If I can still replicate the issue I will write up a sample program which will emulate the issue so that it would be easier for you to check.

**Comment by normanmaurer** [comment]
Sounds good

**Comment by hiteshkotian** [comment]
@normanmaurer: I think I have a memory leak issue because the code I'm working on has a scheduled task running using quartz, which essentially does a bunch of cleanups. 
I know I can create such sceduled tasks using netty right?

For that would you suggest using the event loop of the parent loop group?
 
So essentially here is the code snippet I have:
`public void startServer () {
   // .... other code here
   EventLoopGroup master = new NioEventLoopGroup();
   EventLoopGroup slave  = new NioEventLoopGroup(5);
   
   ServerBootstrap bootstrap = new ServerBootstrap();
   bootstrap.group(master, slave);
   // ... Other bootstrapping logic

   master.scheduleAtFixedRate(new Runnable() {
      @Override
      public void run() {
         // .. Running scheduled cleanup tasks
      }	 }, 0, 3, TimeUnit.SECONDS);
}
`

Do you think this is fine? Or is this wrong?

**Comment by normanmaurer** [comment]
@hiteshkotian generally speaking yes you can do this but you will need to be sure you not block in the Runnable as otherwise you will block an EventLoop

**Comment by hiteshkotian** [comment]
cool. Thanks for the info! this will be of great help for us.
