### ISSUE TITLE
CharSequenceValueConverter.convertToByte works differently for AsciiString vs String

### ISSUE THREAD

**Issue by henrik-lindqvist** [netty/netty#7990]
### Netty version
4.1

Looking at function CharSequenceValueConverter.convertToByte (CharSequence):
https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/CharSequenceValueConverter.java#L79

For AsciiString it takes the first byte, but for any other kind of CharSequence it parse the number value of the entire sequence, i.e. using Byte.parseByte(). This is surely not expected behavior.

See also:
https://docs.oracle.com/javase/8/docs/api/java/lang/Byte.html#parseByte-java.lang.String-

**Comment by normanmaurer** [comment]
@henrik-lindqvist yes this sounds like a bug...

@carl-mastrangelo @ejona86 @Scottmitch @trustin What you think is the correct behaviour here ?

**Comment by Scottmitch** [comment]
I agree there is inconsistency here, and it is not just with `convertToByte` but also with other `convertTo` methods that have a special case for `AsciiString`. The `AsciiString` special case was done for performance reasons, but I think it is more correct to consider the entire value during conversion. We can keep the performance optimization and enforce a max length check too if we want.

We should also be consistent with convertToChar [1] which doesn't have an `AsciiString` optimization but should follow the same semantics.

[1] https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/CharSequenceValueConverter.java#L88

**Comment by carl-mastrangelo** [comment]
My own 2cents: Delete it, or return null.   I don't think there is a reasonable default behavior.  Also, there is hardly anyone using this method, except `getByteAndRemove`, which is itself seldomly used.  Poking around on github's search shows no users.

ValueConverter makes no claims about what subclasses _should_ do, so who can say what will happen?  Further, if I had an instance of type ValueConverter, the implementation would be really important to know.   It cannot provide the abstraction it promises.

**Comment by henrik-lindqvist** [comment]
To be consistent with convertByte is should parse the number, not use the first byte. See: 
https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/CharSequenceValueConverter.java#L74

**Comment by normanmaurer** [comment]
@henrik-lindqvist PTAL https://github.com/netty/netty/pull/7994
