### ISSUE TITLE
Can it be optimized with 'nextIndex' in InternalThreadLocalMap

### ISSUE THREAD

**Issue by fingthinking** [netty/netty#7992]
**English is so bad, Just look at it**

When I new FastThreadLocal, I get a `index` assigned by InternalThreadLocalMap to indicate the location of the object stored in the InternalThreadLocalMap. If index is already more than 32, each InternalThreadLocalMap will assign a 32 location size Object[] when generation, then the Object[] will not be used. I hope to be able to generate index generation from FastThreadLocalThread.

Pre:
```Java
// InternalThreadLocalMap
 public static int nextVariableIndex() {
        int index = nextIndex.getAndIncrement();
        if (index < 0) {
            nextIndex.decrementAndGet();
            throw new IllegalStateException("too many thread-local indexed variables");
        }
        return index;
    }
```

After:
```Java
// InternalThreadLocalMap
 public static int nextVariableIndex() {
        Thread thread = Thread.currentThread();
        AtomicInteger nextIndex;
        if (thread instanceof FastThreadLocalThread) {
            nextIndex = ((FastThreadLocalThread) thread).getNextIndex();
        } else {
            InternalThreadLocalMap localMap = slowGet();
            nextIndex = (AtomicInteger) localMap.indexedVariable(0);
            if (nextIndex == UNSET) {
                localMap.setIndexedVariable(0, nextIndex = new AtomicInteger(1));
            }
        }
        int index = nextIndex.getAndIncrement();
        if (index < 0) {
            nextIndex.decrementAndGet();
            throw new IllegalStateException("too many thread-local indexed variables");
        }
        return index;
    }

// FastThreadLocalThread

public class FastThreadLocalThread extends Thread {
  
   // other codes
  private final AtomicInteger nextIndex = new AtomicInteger(0);

    public AtomicInteger getNextIndex() {
        return nextIndex;
    }
}
```

**Comment by normanmaurer** [comment]
@fingthinking sorry I think I not really get what you propose... Also I wonder if optimisations really matter here as its only done when a new FastThreadLocal is created imho.

**Comment by xuezhongde** [comment]
when a new FastThreadLocal is created, it would be hold a indexedVariables (default, Object[] array = new Object[32];).
but now if the FastThreadLocal's index (index = InternalThreadLocalMap.nextVariableIndex()) was great than 32, we must expand the indexedVariable.
because the ahead position of the indexedVariable can not be used(@see InternalThreadLocalMap#setIndexedVariable). 
his(@fingthinking ) mean this would be a waste i guess.

**Comment by fingthinking** [comment]
@normanmaurer thank you, I have realized the mistake of my idea. Thanks again.

**Comment by SongCF** [comment]
> 

hi 为什么错了呢，我觉得 @xuezhongde 说的是很对呀，如果大量创建fastThreadLocal后，每次新线程创建第一个fastThreadLocal都会重新分配indexedVariable，导致indexedVariable前面的内存大量浪费
