### ISSUE TITLE
Receiving CloseWebSocketFrame for every 6 to 9 minutes

### ISSUE THREAD

**Issue by sekharsa82** [netty/netty#7997]
Hi,
We are receiving CloseWebSocketFrame request from netty api for every 6 to 9 minutes. Here is the actual frame received.
CloseWebSocketFrame(data: PooledUnsafeDirectByteBuf(ridx: 0, widx: 2, cap: 2))

We are new to netty, could some one explain what it means and possible fix we need to apply in netty client.

Best Regards

**Comment by amizurov** [comment]
Hi @sekharsa82 , ``CloseWebSocketFrame`` meaning that server or client decide start close transport handshake, any endpoint that received a close frame must respond with the same frame and content. After that, the server closes the connection.

**Comment by normanmaurer** [comment]
@amizurov it may just happen because the remote peer thinks the connection did idle for too long and so want to close it. Thats when it will send the `CloseWebSocketFrame`. You may be able to prevent this by sending `PingWebSocketFrame`s in a regular basis.
