### ISSUE TITLE
Threads blocked with IN_NATIVE state inside Netty 

### ISSUE THREAD

**Issue by vivek-konnect** [netty/netty#8000]
### Expected behavior
All the threads managed by Netty need to co-run to complete all Network I/O initiated from multiple application threads that use Netty.

### Actual behavior
We noticed that the system is unable to move further (i.e, JVM Hang) to process new resource creation requests via HTTP RESTful API, as all such calls ended up not having threads to be used to complete the request.

Across 3 thread-dumps spaced between 10-15 seconds , Out of 750 threads available on the system during a Jstack dump, atleast 1/3rd of the JVM threads have blocked on Netty (207 threads).

Thread 25375 - threadId:Thread 25375 - state:IN_NATIVE
stackTrace:
- io.netty.channel.epoll.Native.epollWait0(int, long, int, int) @bci=0 (Compiled frame; information may be imprecise)
- io.netty.channel.epoll.Native.epollWait(int, io.netty.channel.epoll.EpollEventArray, int) @bci=10, line=109 (Compiled frame)
- io.netty.channel.epoll.EpollEventLoop.epollWait(boolean) @bci=117, line=232 (Compiled frame)
- io.netty.channel.epoll.EpollEventLoop.run() @bci=65, line=256 (Compiled frame)
- io.netty.util.concurrent.SingleThreadEventExecutor$2.run() @bci=13, line=112 (Interpreted frame)
- io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run() @bci=4, line=145 (Interpreted frame)
- java.lang.Thread.run() @bci=11, line=748 (Compiled frame)

### Steps to reproduce
We have not come up yet with the shortest way to reproduce the problem.

### Netty version
3.10.6.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

### OS version (e.g. `uname -a`)
Linux cic-2.domain.tld 4.4.0-78-generic #99~14.04.2-Ubuntu SMP Thu Apr 27 18:49:46 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by johnou** [comment]
Would you check your Netty version again, Netty 3.10.6 would use the org.jboss.netty package, not io.netty.

**Comment by normanmaurer** [comment]
@vivek-konnect like @johnou already said the thread-dump shows Netty 4.x and not 3.x (also note that 3.x is EOL for a long time). That said have threads stuck in  `io.netty.channel.epoll.Native.epollWait0 ` is normal as it just tells you that there is no IO to handle at the moment and we wait for the Kernel / OS to wakeup and tell us we need to process some IO events. Why you think there is an issue ?

**Comment by vivek-konnect** [comment]
We will reconfirm the Netty version.  

We think there is definitely issue because we have more than 1/3rd of the threads in the production system are locked up in IN_NATIVE state (precisely 207 threads out of 750 threads)  and the production system freezes.  Two incidents of such a freeze both point to this same Jstrack Thread Trace.

Are there some other things we can continously monitor in production system so that we can attach more information here for further support ?

**Comment by vivek-konnect** [comment]
From within Karaf of OpenDaylight Controller, the version is showing up for us as 3.10.6.Final.
opendaylight-user@root>bundle:list | grep Netty
214 | Active   |  80 | 3.10.6.Final                       | Netty                                   
opendaylight-user@root>

Is there a better way to confirm the version of the Netty.jar?  
Shall we do:
unzip -p netty.jar META-INF/MANIFEST.MF

**Comment by vivek-konnect** [comment]
We got the required information..

 Two versions of Netty are being run under our Karaf container but the one our software uses is 4.0.37.Final

Can you please advise further?

opendaylight-user@root>bundle:list | grep -i netty
165 | Active   |  80 | 4.0.37.Final                       | Netty/Buffer
166 | Active   |  80 | 4.0.37.Final                       | Netty/Common
167 | Active   |  80 | 4.0.37.Final                       | Netty/Transport
168 | Active   |  80 | 4.0.37.Final                       | Netty/Codec
169 | Active   |  80 | 4.0.37.Final                       | Netty/Codec/HTTP
170 | Active   |  80 | 4.0.37.Final                       | Netty/Handler
171 | Active   |  80 | 4.0.37.Final                       | Netty/Transport/Native/Epoll
172 | Active   |  80 | 0.5.4.SNAPSHOT                     | org.opendaylight.controller.netty-config-api
173 | Active   |  80 | 0.5.4.SNAPSHOT                     | org.opendaylight.controller.netty-event-executor-config
174 | Active   |  80 | 0.5.4.SNAPSHOT                     | org.opendaylight.controller.netty-threadgroup-config
175 | Active   |  80 | 0.5.4.SNAPSHOT                     | org.opendaylight.controller.netty-timer-config
214 | Active   |  80 | 3.10.6.Final                       | Netty
opendaylight-user@root>

**Comment by normanmaurer** [comment]
@vivek-konnect again I think there is nothing wrong with have threads sitting in this state... Its expected if there is no IO ready to be handled atm. The number of threads really depends on how many `*EventLoopGroup`s you have but that's up to you.

**Comment by normanmaurer** [comment]
Let me close this as I think its not an actual issue (if its an issue then its one because you or the library you are using is creating to many `EventLoop`s). Please re-open if you still think there is an issue and provide more info why you think so.
