### ISSUE TITLE
Http2CodecUtil.java - emptyPingBuf() is no longer needed (as writePing takes a long)

### ISSUE THREAD

**Issue by vsabella** [netty/netty#8002]
https://github.com/netty/netty/blob/b192bf12ad2af92bba0f32c9d3127b1192e54670/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2CodecUtil.java#L177

In https://github.com/netty/netty/commit/501662a77f8166382eefd18a8620983d27f59d4a - emptyPing data changed to long (instead of buffer data)

This should be updated.

**Comment by normanmaurer** [comment]
@vsabella I guess we should just remove it completely. 

@carl-mastrangelo @ejona86 @Scottmitch thoughts ?

**Comment by normanmaurer** [comment]
Also @mosesn @bryce-anderson WDYT ?

**Comment by bryce-anderson** [comment]
Looks like dead code to me and `Http2CodecUtil` is still tagged `@UnstableApi` so removing it seems like the right move.

**Comment by normanmaurer** [comment]
@bryce-anderson sounds good... Will try to find time to write a patch or if you want you could also if you have time 👍

**Comment by bryce-anderson** [comment]
I can take it. Unless it is actually in use it should be trivial to remove.

**Comment by normanmaurer** [comment]
Thanks that would be awesome

**Comment by normanmaurer** [comment]
Thanks @bryce-anderson
