### ISSUE TITLE
Unaligned intrinsics in Java 9

### ISSUE THREAD

**Issue by hc-codersatlas** [netty/netty#8003]
Java 9 introduced intrinsics for ByteBuffer.put* / ByteBuffer.get*, which is provided by jdk.internal.misc.Unsafe unaligned get/set functions. Can this be added to the current unsafe implementation to improve performance?

**Comment by normanmaurer** [comment]
@hc-codersatlas unfortunately not at the moment. Once we change the JDK version we use for compiling we may be able to do this.

**Comment by normanmaurer** [comment]
@hc-codersatlas can you also point me to the intrinsics you are talking about ?

**Comment by hc-codersatlas** [comment]
Sorry for the delay, it's in jdk.internal.misc.Unsafe class
