### ISSUE TITLE
After the netty client disconnects from the network, how does the server immediately sense?

### ISSUE THREAD

**Issue by a173030685** [netty/netty#8004]
My side, deliberately disconnected from the client, hoping to allow the server to immediately detect the client has been off the net, is there any way? How to achieve the code?
I don't want to judge by heartbeat, because this method is not real-time. For example, I set it to 50 seconds. He must wait 50 seconds to know. If someone just pushes the message within 50 seconds, the server will think it is Can push, but the client actually can not receive.
Or can you check whether the channel is alive before sending it through the channel? I tried isActive and isOpen. They return true in case of a broken network. Please ask for a good solution. Thank you very much!

**Comment by amizurov** [comment]
Hi @a173030685. In most of cases you need write your own `ping/pong`, `heartbeating` handler for detecting unresponsive clients, but  some times (exception: connecection reset by peer) you may immediate detect problem with channel. Also remember that `TCP` protocol keep alive your connection and have guarantee delivery. For example if write to channel message and after 60s (it's depend on OS) if the client not send `ack` for package you get timeout exception.

**Comment by normanmaurer** [comment]
Exactly what @amizurov said...
