### ISSUE TITLE
Order between channelActive invocation on server, and channel being active on client?

### ISSUE THREAD

**Issue by srdo** [netty/netty#8008]
Hi,

We have a test on Netty 3.x that starts up a server and client, and verify that they can talk to each other. The server keeps a list of all connected channels in a ChannelGroup, and adds new channels as channelConnected is called. 

The test waits for the client channel to be open, and also waits for all channels in the server's ChannelGroup to be connected.

We're migrating to Netty 4, and the test has become flaky because it appears that the client channel may become active before the server channelActive method is invoked. As a result, the test starts before the server has registered the client in the ChannelGroup.

I'm not sure whether this is a bug. Is the server's channelActive supposed to be invoked before the client's channel becomes active, or was it just a happy accident that it worked in Netty 3?

**Comment by normanmaurer** [comment]
@srdo can you show some code ?

**Comment by srdo** [comment]
Yes. The flaky test is here https://github.com/srdo/storm/blob/3a52302cfc985263c60548c8f4b284a99d0ebb56/storm-core/test/jvm/org/apache/storm/messaging/netty/NettyTest.java#L178. 

The waitUntilReady method is waiting for the single channel in the client to be active https://github.com/srdo/storm/blob/3a52302cfc985263c60548c8f4b284a99d0ebb56/storm-client/src/jvm/org/apache/storm/messaging/netty/Client.java#L224, as well as for every channel in the server ChannelGroup to be active https://github.com/srdo/storm/blob/3a52302cfc985263c60548c8f4b284a99d0ebb56/storm-client/src/jvm/org/apache/storm/messaging/netty/Server.java#L214.

When the client connects, the channelActive method is called on the server's handler https://github.com/srdo/storm/blob/3a52302cfc985263c60548c8f4b284a99d0ebb56/storm-client/src/jvm/org/apache/storm/messaging/netty/StormServerHandler.java#L40, which causes it to add the new channel to the ChannelGroup.

The intent for the test waitUntilReady method is to wait until the client has connected to the server, and channelActive has run on the server. In Netty 3 it seems to have been the case that the client wouldn't claim to have a ready channel until the server had run channelConnected. In Netty 4 it sometimes happens that the client channel becomes active before the server has run channelActive (I checked this by adding a log line to channelActive). This causes the test to fail by running too early, because it tries to push messages to all channels connected to the server, which doesn't include the client yet.

Let me know if you need a smaller reproduction, and I'll try to make one.

**Comment by normanmaurer** [comment]
@srdo I will try to find some time and check it soon. Sorry quite busy atm

**Comment by srdo** [comment]
Thank you.

**Comment by normanmaurer** [comment]
@srdo I think what you are seeing comes from the fact that we always complete the promise before we call the corresponding event callback. Which means for example that the future returned by `connect` will be notified before `channelActive` is called. 

Does this make sense ?

**Comment by srdo** [comment]
@normanmaurer Yes, that makes sense. Thanks. We can work around it in the test by sending a message to the server and waiting for it to respond before running the rest of the test, since at that point the server is guaranteed to have run channelActive.

I don't know if there's a reason to make a change to Netty? The only case I can think of where the order of these events matters is when someone starts a server and client in the same JVM, and want to test broadcasting from the server.

**Comment by normanmaurer** [comment]
@srdo ok cool.... Let me close this one then.

**Comment by ntherrien** [comment]
@normanmaurer, about what you said about the connectFuture being notified before the handler's channelActive, could you explain why it is the case? I wrote code thinking the "completed" future would be the very last thing to be notified (ie: can start sending stuff right away via handlers) but I can see the handlers are not yet ready to start sending because they haven't been activated yet...

**Comment by normanmaurer** [comment]
@ntherrien this was done to give the user a chance to for example add handlers to the pipeline in the connect future listener and still receive the `channelActive` event.

**Comment by ntherrien** [comment]
@normanmaurer and anyone encountering problems related to the order in which listeners are being notified, here is a solution that works well: queueing work on the event loop:
```
            ChannelFuture connectFuture = clientBootstrap.connect();
            connectFuture.addListener(new ChannelFutureListener() {
                @Override
                public void operationComplete(ChannelFuture channelFuture) throws Exception {
                    if(channelFuture.isSuccess()) {
                        logger.info("Connection to: " + remoteClientName + " succeeded.");
                        group.execute(() -> somethingtodo.initialize());
                    }
                    else {
                        logger.error("Connection to: " + remoteClientName + " failed.", channelFuture.cause());
                    }
                }
            });
```

putting the work on the group loop will ensure the handler's channelActive listener will be call before this is executed.
