### ISSUE TITLE
Techempower benchmark issues

### ISSUE THREAD

**Issue by re-thc** [netty/netty#8016]
Hi, does anyone maintain the [Techempower benchmark](https://www.techempower.com/benchmarks/#section=data-r16&hw=ph&test=plaintext) code from Netty? I noticed a huge difference (relatively) from the current round (and last).

Looking at the [Github repo ](https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Java/netty) it seems that some of the startup options, e.g. io.netty.tryAllocateUninitializedArray aren't enabled.

Perhaps there are other best practices that can be done for setup?

The benchmarks do get quite a lot of press release and definitely helps with adoption. Netty's been quite high on the charts for quite a number of years.

**Comment by doom369** [comment]
@hc-codersatlas I did few improvements about 9 months ago. I don't see any updates since then. The only netty version is updated.

**Comment by hc-codersatlas** [comment]
@doom369 was the JDK version updated between the 2 benchmarks? In Java 9 onwards reflection and unsafe might need some --add-opens for it to perform well. Might be other options worth investigating.

**Comment by doom369** [comment]
@hc-codersatlas yes, they also updated JDK from Java 8 to Java 10.

**Comment by normanmaurer** [comment]
closing for now... please let us know if you still think there is an issue
