### ISSUE TITLE
Http2MultiplexCodec.DefaultHttp2StreamChannel.Http2ChannelUnsafe has a different order of close events than other channel implementation

### ISSUE THREAD

**Issue by bryce-anderson** [netty/netty#8018]
The `HttpObjectAggregator`, when it encounters a too-large-message, [does the following](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectAggregator.java#L281) when handling a too large response:
```java
ctx.close();
throw new TooLongFrameException("Response entity too large: " + oversized);
```
The tail of the pipeline gets an `exceptionCaught` event before receiving a `channelInactive` event because channel deregistration is always done '[later](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/AbstractChannel.java#L813)'. This is not the case in the `Http2ChannelUnsafe` which triggers shutdown events [immediately](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java#L925). That means when using the `HttpObjectAggregator` in a stream channel, we will receive  the`channelInactive` event before the `exceptionCaught` event, making it difficult to handle gracefully.

### Netty version

4.1.26-SNAPSHOT

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_162"

### OS version (e.g. `uname -a`)
Darwin

**Comment by bryce-anderson** [comment]
Presuming I haven't messed this up, I'd love to get this fixed before 4.1.26 since it would make it really difficult to use symmetric pipelines for our HTTP/2 and HTTP/1.x clients.

**Comment by normanmaurer** [comment]
This sounds like a bug... interested in working on a PR?

**Comment by bryce-anderson** [comment]
Absolutely, just wanted confirmation that I wasn't just using it wrong. 😄

**Comment by bryce-anderson** [comment]
Just to be clear, I think the deferred close operations is what we want, correct? I could see it going the other way: technically the `ctx.close` was called first, but the operation is asynchronous so it seem like legal behavior to defer the events.

**Comment by normanmaurer** [comment]
Yes just as for normal channels

**Comment by normanmaurer** [comment]
@bryce-anderson I think at some point it did extend it but I changed it (my memory may be wrong here) because something was not needed and did not even work then extending the `AbstractChannel`. If I am not wrong this was related to the `ChannelOutboundBuffer`.

**Comment by normanmaurer** [comment]
@bryce-anderson thanks for the PR and yes I agree we should see if we can make `AbstractChannel` useable for it in the next major release.
