### ISSUE TITLE
Math.random usage in Websocket code

### ISSUE THREAD

**Issue by hc-codersatlas** [netty/netty#8023]
Hi, minor issue, but consistency / performance reasons WebSocketUtil and related handshakers make use of Math.random instead of ThreadLocalRandom. Math.random is pretty slow...

**Comment by normanmaurer** [comment]
@hc-codersatlas PRs welcome...

**Comment by hc-codersatlas** [comment]
Sure, but have a question about that part of the code in WebSocketUtil (and a few other files):

`    static int randomNumber(int minimum, int maximum) {
        return (int) (Math.random() * maximum + minimum);
}`

Is this correct? Assuming Math.random() produces 0.9999 (for convenience let's say 1.0) - the result exceeds the maximum value, i.e. 1.0 * maximum + minimum > maximum.

**Comment by normanmaurer** [comment]
looks like a bug to me... PR with fix and test welcome :)

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/8048
