### ISSUE TITLE
E/Multipart ERROR: error => com.android.volley.NoConnectionError: java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by khuranakaran** [netty/netty#8030]
Trying to upload a .mp3 as large as 100mb. While trying to upload a file <10mb everything works fine. But when trying to upload a big file volley throws this error E/Multipart ERROR: error => com.android.volley.NoConnectionError: java.net.SocketException: Connection reset.

**Comment by normanmaurer** [comment]
connection reset just means that the remote peer did close the connection. There is nothing we can do here. Maybe its done by a load-balancer in between or by the peer itself.

**Comment by vickykumarvc802679-rgb** [comment]
https://github.com/netty/netty/issues/8030

**Comment by vickykumarvc802679-rgb** [comment]
Sandes app is not login
