### ISSUE TITLE
Reusing DefaultFullHttpRequest

### ISSUE THREAD

**Issue by xttam** [netty/netty#8032]
I'm doing the following, which basically creates one POST request, sets its body, `writesAndFlush` a `retainedDuplicate` of it, changes its body and `writesAndFlush` another `retainedDuplicate` of it.

I haven't run this example in particular but I've seen in other cases all requests gets executed with the correct content length in each case, but with the same body except for the last bytes. It looks like the second request overrides the first bytes of the body of the first request, even after `retainedDuplicate`.

What is the correct way to reuse `DefaultFullHttpRequest`?

```java
DefaultFullHttpRequest request = new DefaultFullHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.POST, "/echo");
request.headers().set(HttpHeaderNames.HOST, host);

// ...

String body = "foo=bar&test=blah&t=123";
request.headers().set(HttpHeaderNames.CONTENT_TYPE, HttpHeaderValues.APPLICATION_X_WWW_FORM_URLENCODED);
request.headers().set(HttpHeaderNames.CONTENT_LENGTH, body.length());
request.content().clear().writeBytes(body.getBytes());
channel.writeAndFlush(request.retainedDuplicate());

String body = "foo=yada&t=456";
request.headers().set(HttpHeaderNames.CONTENT_TYPE, HttpHeaderValues.APPLICATION_X_WWW_FORM_URLENCODED);
request.headers().set(HttpHeaderNames.CONTENT_LENGTH, body.length());
request.content().clear().writeBytes(body.getBytes());
channel.writeAndFlush(request.retainedDuplicate());
```

**Comment by normanmaurer** [comment]
@xttam This is expected as you call `writeBytes()` while the first may not be completely written. Both `ByteBuf` which are the content share the same storage. If you want to replace the content you should use `request.copy(...)`.

**Comment by xttam** [comment]
Got it, thought `duplicate` would actually `copy` it. Thanks.
