### ISSUE TITLE
Http2MultiplexCodec in client mode can trigger a GOAWAY if it creates a stream after getting a GOAWAY

### ISSUE THREAD

**Issue by bryce-anderson** [netty/netty#8041]
### Expected behavior

When a client attempts to utilize a new stream channel using Http2MultiplexCodec _after_ receiving a GOAWAY, the client will gracefully fail the stream channel with an exception that signifies the stream wasn't processed, perhaps such a RST_STREAM(REFUSED_STREAM).

### Actual behavior

When a client attempts to create a new stream channel using Http2MultiplexCodec _after_ receiving a GOAWAY, the client will throw it's own PROTOCOL_EXCEPTION that gets sent to the server and the connection gets torn down. It's also debatable as to whether the server should be actively tearing down the connection due to that message since it is still processing client streams.

### Steps to reproduce

Establish a client connection using Http2MultiplexCodec, have the server send a GOAWAY with one outstanding client stream, and attempt to create another client stream. You can observe a client-sent GOAWAY(last processed stream: 0) with a message similar to: 
```
Cannot create stream 5 since this endpoint has received a GOAWAY frame with last stream id 3.
```

### Netty version
4.1.26.Final-SNAPSHOT (as of 6/20/2018)

**Comment by bryce-anderson** [comment]
A simple solution might be to add something like
```java
} else if (connection().goAwayReceived()) {
    ReferenceCountUtil.release(frame);
    promise.setFailure(Http2Exception.streamError(-1, Http2Error.REFUSED_STREAM, "Received GOAWAY before stream was initialized.")
    );
    return;
}
```
[here](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java#L1102) in the write method of the `Http2MultiplexCodec.DefaultHttp2StreamChannel.Http2ChannelUnsafe`.

**Comment by bryce-anderson** [comment]
And I'm happy to work on this once we have a consensus on direction.

**Comment by Scottmitch** [comment]
> PROTOCOL_EXCEPTION that gets sent to the server and the connection gets torn down.

Can you clarify exactly what is being sent to the server? If the connection is being hard-shutdown that sounds like a problem, but sending a GO_AWAY and initiating local graceful close isn't necessarily a problem IIUC (this just prevents the server from pushing any streams). The rational accompanied with the GO_AWAY is a bit awkward from the perspective of the server and is somewhat leaking client state ... but the rational is only meant to be informative anyways. Can you clarify if this is causing a problem or breaking something?

If we no longer want to send a GO_AWAY and initiate graceful closure from the local end point in this scenario I would propose the following patch (or something similar):

```diff
diff --git a/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2Connection.java b/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2Connection.java
index 4251317457..1b6f15bc44 100644
--- a/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2Connection.java
+++ b/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2Connection.java
@@ -864,9 +864,9 @@ public class DefaultHttp2Connection implements Http2Connection {
         private void checkNewStreamAllowed(int streamId, State state) throws Http2Exception {
             assert state != IDLE;
             if (goAwayReceived() && streamId > localEndpoint.lastStreamKnownByPeer()) {
-                throw connectionError(PROTOCOL_ERROR, "Cannot create stream %d since this endpoint has received a " +
-                                                      "GOAWAY frame with last stream id %d.", streamId,
-                                                      localEndpoint.lastStreamKnownByPeer());
+                throw streamError(streamId, REFUSED_STREAM,
+                    "Cannot create stream %d since this endpoint has received a GOAWAY frame with last stream id %d.",
+                        streamId, localEndpoint.lastStreamKnownByPeer());
             }
             if (!isValidStreamId(streamId)) {
                 if (streamId < 0) {
```

The rational being the actual H2 logic resides in the lower level API and we should ensure consistent behavior between the child channel API and lower level API.

**Comment by bryce-anderson** [comment]
This is causing an issue as the client sends a GOAWAY and closes the connection on flush. The exception is generated in the [`DefaultHttp2ConnectionEncoder`](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionEncoder.java#L166) which passes it to the lifecycle manager [here](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionEncoder.java#L234), which passes it to the [`Http2ConnectionHandler`](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L617), and ultimately the `onConnectionError` method and the hard shutdown pathway [here](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L654).

I think the patch you're proposing will result in a stream exception which is fine from the side of the client, but I think it will result in sending a RST_STREAM to the peer for a stream in the idle state which is a connection level protocol error. We could try to intercept it for the case of 'trying to initiate a stream' but I suspect it will start to get complex. Alternatively, maybe we can just add the graceful shutdown hint to the connection error for this case, though threading that info through might also be pretty complex. If things are working right, that should put us in the 'not a problem' behavior you mentioned above where the client sends a GOAWAY but it's a draining GOAWAY. This is still pretty awkward since it's triggered by attempting to initiate a new stream as opposed to being a response to a received GOAWAY, and it signals draining of inbound streams in response to an outbound stream concern, and the client didn't signal that it wasn't interested in pushed streams anymore just because the server won't accept new streams.

What is the pattern that the users of the non-multiplexcodec API should use to ensure they don't start a new stream after receiving a GOAWAY? In our usage of the old-style API we handle GOAWAY frames manually and stop accepting new streams at that point [here](https://github.com/twitter/finagle/blob/develop/finagle-http2/src/main/scala/com/twitter/finagle/http2/transport/StreamTransportFactory.scala#L125). Attempts to initiate new dispatches check this state and fail if we've gotten a GOAWAY. This section of code has more or less the same job as the stream channels of Http2MultiplexCodec so that might be why it feels natural to do the state checking there.

**Comment by bryce-anderson** [comment]
@Scottmitch, do you have any more suggestions/opinions? I'd like to get this into 4.1.26 if at all possible, which I believe is knocking at the door. That said, I think it's more desirable to be correct than released earlier. 😄

**Comment by bryce-anderson** [comment]
I went ahead and opened PR https://github.com/netty/netty/pull/8057 with what feels like the right thing to do based on our usage of the old Http2 API, namely that we had to handle ensuring a GOAWAY hadn't been issued already ourselves. I put it up eagerly so that it has a chance of getting into Netty 4.1.26 if it's the right thing to do, but I'm happy to throw that away if we can come to a decision that something else should be done.

**Comment by Scottmitch** [comment]
Sorry was AFK for the past few days ...

> I think it will result in sending a RST_STREAM to the peer for a stream in the idle state 

Good point. We would need to avoid violating the protocol. Failing the promise should be sufficient.

> the client didn't signal that it wasn't interested in pushed streams anymore just because the server won't accept new streams.

Another good point. I agree that forcing a GO_AWAY doesn't make much sense in this scenario.

In general I think we should make the fix in the interface API which is responsible for the core H2 logic instead of fragmenting the logic. The exception path in the interface API for outbound events is not consistent with Netty's typical error propagation pattern (read events throw, write events fail promises) and I think this should be corrected. Everything above (e.g. child channel API) would then inherit the fix.

**Comment by bryce-anderson** [comment]
> In general I think we should make the fix in the interface API which is responsible for the core H2 logic instead of fragmenting the logic in the child channel API. Everything above (e.g. child channel API) would then inherit the fix.

Failing the promise on such a failed write should be sufficient to get the behavior I want and will work for all APIs. We can fail the promise for both API's either in the `Http2FrameCodec` or in the `DefaultHttp2ConnectionEncoder`. If we modify the `Endpoint.incrementAndGetNextStreamId()` method to consider received GOAWAY's it will fail the promise in `Http2FrameCodec` which feels pretty good.

I'd prefer the change to `incrementAndGetNextStreamId()` unless we don't consider it part of the `Endpoint`s job to validate that possibility. It seems like it should be.

**Comment by Scottmitch** [comment]
See PR https://github.com/netty/netty/pull/8069 for my proposal. I think the change in `Http2ConnectionHandler` is useful either way bcz as you pointed out we may end up inadvertently sending a RST on a stream that never existed which would kill the connection.

> I'd prefer the change to incrementAndGetNextStreamId()

Can you clarify this suggestion. It isn't clear how `incrementAndGetNextStreamId` would be changed (e.g. would it throw, would it know about the promise, etc...).

**Comment by bryce-anderson** [comment]
@Scottmitch, see https://github.com/netty/netty/pull/8067 for what I mean by changing `incrementAndGetNextStreamId()`. It already has the semantics of returning negative values to signal that a stream id couldn't be assigned and this is extended to cover the case that a GOAWAY has been issued by the peer.

A quick skim of your PR looks like it would probably accomplish the same goal. It would have the result in burning reserved stream id's that would go unused, but I don't think that's of any real consequence. I don't see a reason that both changes couldn't coexist in case someone wants to use the `Http2ConnectionHandler` and not the `Http2FrameCodec`.

**Comment by bryce-anderson** [comment]
This is fixed now, though we've unfortunately hit the situation where the client will send a RST_STREAM(cancel) on an idle stream. I have a couple PRs up, any of which should fix it https://github.com/netty/netty/pull/8067, https://github.com/netty/netty/pull/8086, though the fallout is different for each.

**Comment by bryce-anderson** [comment]
https://github.com/netty/netty/pull/8086 has been merged, so I think this can be closed.
