### ISSUE TITLE
Invalid HTTP2 pseudo-headers kill the session instead of being treated as malformed

### ISSUE THREAD

**Issue by bryce-anderson** [netty/netty#8043]
### Expected behavior

When a peer receives invalid pseudo headers the request or response should be treated as malformed as prescribed in section [8.1.2.1](https://http2.github.io/http2-spec/#rfc.section.8.1.2.1). This entails a stream level PROTOCOL_ERROR as described in section [8.1.2.6](https://http2.github.io/http2-spec/#rfc.section.8.1.2.6)

### Actual behavior

The [HpackDecoder](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/HpackDecoder.java#L401) throws a connection level PROTOCOL_ERROR mid-decode, resulting in the connection being torn down.

### Steps to reproduce

Attempt to send a HTTP/2 request with an unknown pseudo header, pseudo headers out of order, or a mix of request and response type pseudo headers.

**Comment by bryce-anderson** [comment]
This is causing minor issues for us migrating to version of Netty that included the commit associated with PR https://github.com/netty/netty/pull/7500. Those problems include killing connections in production (relatively infrequent, but happens enough to be noticed) and some failing tests. We can work around it by validating headers before they are sent to the peer or disabling validation but ideally the receiving end, which should do this validation regardless to adhere to the spec, only needs to do it and behave correctly.

**Comment by normanmaurer** [comment]
@Scottmitch @ejona86 any comments ?

**Comment by mosesn** [comment]
@bryce-anderson just to double check, the spec says we should send an RST?  I agree that seems reasonable.

**Comment by bryce-anderson** [comment]
@mosesn, that's my interpretation of http2 spec section [8.1.2.6](https://http2.github.io/http2-spec/#rfc.section.8.1.2.6):
> Malformed requests or responses that are detected MUST be treated as a stream error (Section 5.4.2) of type PROTOCOL_ERROR.

I think you noted in your review of the patch that introduced validation that tearing down the connection is pretty heavy handed. 😄

**Comment by ejona86** [comment]
Stream-level PROTOCOL_ERROR seems good.

**Comment by normanmaurer** [comment]
+1

**Comment by bryce-anderson** [comment]
I'm happy to work on this and I think we have two options.

1. We can leave validation in the HPACK decoder but move it to the end of the decode phase: we need to completely decode the headers to keep the HPACK state consistent.
2. We can move it clear out of the HPACK decoder (it's not really a HPACK concern) and change the API to specify if the headers belong to a request, response, or trailers.

I'd speculate that we should start with 1 and do 2 after a bit more research into the right place and how it will affect current users.

**Comment by normanmaurer** [comment]
1) sounds good to me... @ejona86 @carl-mastrangelo @Scottmitch agree ?

**Comment by carl-mastrangelo** [comment]
SGTM as well.

**Comment by Scottmitch** [comment]
(1) sgtm.

**Comment by normanmaurer** [comment]
@bryce-anderson thanks for the fix
