### ISSUE TITLE
why: final SelectionKey selectionKey = this.selectionKey;

### ISSUE THREAD

**Issue by zhaojigang** [netty/netty#8049]
It's a not an issue. Instead, I'm asking for help.

![image](https://user-images.githubusercontent.com/14085645/41806690-8d3743f6-76f5-11e8-9389-8b4062c50bd0.png)

I cant understand why adding this row：final SelectionKey selectionKey = this.selectionKey;
because i think when i change the inner selectionKey， and the outer selectionKey will change together.

Hope you could give a hand. Really appreciate.

**Comment by normanmaurer** [comment]
@zhaojigang its because selectionKey is volatile and so may change in between + its "expensive" to access it.
