### ISSUE TITLE
Is there BinaryWebSocketFrame to/from MqttMessage codec?

### ISSUE THREAD

**Issue by jast90** [netty/netty#8060]
### Expected behavior
I want using netty implement MQTT over WebSocket? 
ChannelInitializer as follow:
```
pipeline.addLast(new HttpServerCodec());
pipeline.addLast(new HttpObjectAggregator(65536));
pipeline.addLast(new WebSocketServerProtocolHandler("/mqtt", "mqtt,mqttv3.1", true));
pipeline.addLast(new TextWebSocketFrameHandler());
pipeline.addLast(new MqttDecoder());
pipeline.addLast(MqttEncoder.INSTANCE);
pipeline.addLast("timeout", new IdleStateHandler(30, 0, 20, TimeUnit.SECONDS));
pipeline.addLast(new MqttServerHandler());

```
But i find I need BinaryWebSocketFrame to/from MqttMessage codec.
### Netty version
4.1.22
### JVM version (e.g. `java -version`)
java version "1.8.0_05"
Java(TM) SE Runtime Environment (build 1.8.0_05-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.5-b02, mixed mode)
### OS version (e.g. `uname -a`)
Microsoft Windows [版本 10.0.17134.112]

**Comment by normanmaurer** [comment]
@jast90 there is not... you will need to implement it yourself.
