### ISSUE TITLE
which is branch have 5.0.0.Alpha2 resource code? 

### ISSUE THREAD

**Issue by WilliamShoww** [netty/netty#8063]
I want to read this resource code. Code demo use 5.0.0.Alpha2 version,but I don't know how pull this version code.

**Comment by normanmaurer** [comment]
You should not use it... Use 4.1.x as 5.0.0* was deprecated and is dead for now. 

If you really want to checkout the tag you can use `git checkout netty-5.0.0.Alpha2`.
