### ISSUE TITLE
Is isFlushPending necessary when flush ?

### ISSUE THREAD

**Issue by carryxyh** [netty/netty#8066]
Before NioSocketChannel call `flush0`, it will call `io.netty.channel.nio.AbstractNioChannel.AbstractNioUnsafe#isFlushPending` method.

Is here `isFlushPending` necessary?
In my oponion, all the write and flush will be done with `NioEventLoop`(single thread).
In whick case, `isFlushPending` will return true before `io.netty.channel.AbstractChannel.AbstractUnsafe#flush0` method is called ?

**Comment by normanmaurer** [comment]
@carryxyh its an optimisation... if we already registered with the Selector to be notified when the Channel becomes writable there is no need to try to write it to the underlying fd at all as the write will also not succeed. Once the Channel becomes writable again we will try to writer everything to the underlying fd.
