### ISSUE TITLE
Http2Headers pseudoheader setting methods incorrectly documented

### ISSUE THREAD

**Issue by mosesn** [netty/netty#8068]
Here in the docs it says the setter sets the header conditionally, but it seems to actually be unconditional.

[Docs][0]:

```
    /**
     * Sets the {@link PseudoHeaderName#METHOD} header or {@code null} if there is no such header
     */
    Http2Headers method(CharSequence value);
```

[Implementation][1]:
```
    @Override
    public Http2Headers method(CharSequence value) {
        set(PseudoHeaderName.METHOD.value(), value);
        return this;
    }
```

One of these is wrong, but I don't know which one it is.

[0]: https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2Headers.java#L138-L141
[1]: https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2Headers.java#L134

**Comment by normanmaurer** [comment]
@Scottmitch @trustin  thoughts ?

**Comment by normanmaurer** [comment]
@trustin @ejona86 @carl-mastrangelo @Scottmitch ping...

**Comment by carl-mastrangelo** [comment]
Looks like a typo.  The blame line shows that being present for a while.  I'm not sure what the docs mean:  Does it clear the header if it doesnt exist?  Does it clear it if it doesn't apply (such as in a response header)?  I would support making the doc take no position on the matter.

**Comment by ejona86** [comment]
The doc does seem wrong. Null doesn't even make sense in that context. Seems it should be "Sets the {@link PseudoHeaderName#METHOD} header".

**Comment by normanmaurer** [comment]
@ejona86 want to do a PR ?
