### ISSUE TITLE
Does ssl or http compression done in I/O thread?

### ISSUE THREAD

**Issue by kingluo** [netty/netty#8071]
As known, the netty 4.0 requires the channel pipeline get executed in single I/O thread, and one I/O thread may serve many channels concurrently, so it's bad to block the I/O thread.

So what about ssl and compression codec handlers? They're CPU consumption. Do they get executed in I/O thread? If not, then it turns to pay thread context-switch overhead (because write() must be delegated to I/O thread)?

Moreover, most app logic could not be handled in I/O thread:

* They may likely use legacy BIO libraries, e.g. JDBC
* They may likely do CPU or Block-device sensitive tasks
* Even they only use pure netty or libraries based on netty, you cannot ensure the app logic co-use the same I/O thread

So it seems that context-switch is unavoidable? I know the intention of current thread model is to get rid of threading race, but it seems that we most likely get the context-switch overhead as the cost?

**Comment by normanmaurer** [comment]
@kingluo everything is done in the `EventLoop` (IO-Thread) by default in netty. If you need to do long-running computation or blocking work you will need to dispatch it to another `Thread`. If this is needed or not highly depends on your application tho. There are plenty of use-cases where this is never needed at all.

So just to make it clear, sure as soon as you need to dispatch from the `EventLoop` to another `Thread` there is a need for a context-switch.

**Comment by kingluo** [comment]
@normanmaurer Yes, it's ideal to finish all tasks within the same IO thread. But I think in most cases, for server app, the business logic should use third party libraries, and cannot only depend on the sockets bound to the IO thread.

Obviously, the ssl and http compression is good case to use a lot of CPU, which may block the IO thread, more or less. So how do you consider it?

**Comment by normanmaurer** [comment]
@kingluo in my experience doing SSL in the IO thread is fine. Compression depends a bit on the algorithm. There are multiple solution here. Either use more IO threads or offload the compression.

**Comment by kingluo** [comment]
@normanmaurer It's hard to take any solution.
More IO threads should be fine, as long as netty could apply some work-stealing logic on the event dispatching. Think that when one thread get blocking, other threads could steal the tasks on it and eliminates the impact. And it should be better that the thread pool could be dynamically sized.
On the other hand, if we move compression to independent execution group, then context switch would be the penalty.
