### ISSUE TITLE
Avoid creating FileInputStream and FileOutputStream for obtaining FileChannel

### ISSUE THREAD

**Issue by leventov** [netty/netty#8078]
There are multiple places in the production code of the project, e. g. in `ChunkedNioFile`, where `FileInputStream` or `FileOutputStream` are created solely to obtain a `FileChannel` from them. Until Netty projects bumps the compatibility level to Java 7 (where `FileChannel.open()` methods were added), it's better to obtain a FileChannel by means of creating a `RandomAccessFile`, because the latter doesn't override `Object.finalize()`. Also, I would extract those pieces of code into a utility methods like `openChannelForRead(File)` and `openChannelForWrite(File)`.

**Comment by hc-codersatlas** [comment]
Same goes for BufferedReader instances - same finalize problem. It's used in DNS and some other modules.

**Comment by normanmaurer** [comment]
@leventov good catch... Check https://github.com/netty/netty/pull/8110
