### ISSUE TITLE
Does ByteBuf need to be allocated and released in same thread (IO or non-IO)?

### ISSUE THREAD

**Issue by kingluo** [netty/netty#8079]
Normally, the `ByteBuf` is allocated and released in the same IO thread.

But what about other cases?
* allocate in IO thread, release in different IO thread
* allocate in non-IO thread, release in IO thread
* allocate in IO thread, release in non-IO thread
* allocate in non-IO thread, release in different non-IO thread

Is there some official clarification about this topic?

**Comment by normanmaurer** [comment]
Allocation and releasing of a buffer is a thread-safe operation. Every other operation on the buffer is not thread-safe.

**Comment by kingluo** [comment]
I just saw some posts which said buffer releasing on other thread may bring issues. Is there some threadlocal design which would cause memory leak when we release buffer in other thread? Or those posts are outdated for current netty version?

**Comment by normanmaurer** [comment]
@kingluo there are no issues, this is done in lot of use-cases. You just need to ensure you not use it anymore after it.
