### ISSUE TITLE
how to make FixedChannelPool Multiplex

### ISSUE THREAD

**Issue by wsrspirit** [netty/netty#8083]
I hava a problem using FixedChannelPool, I read the code, and I know if where is 4 channels in channelpool, named A B C D, that I `acquire` one, if it is A, then B C D channels in `deque`.
What I want is that I get A and the other can also get A before I call `release`. I can find out which thread use this channel to send tcp msg by a seq num (I think is more efficient to reuse channel and create less fd), so how can I do? Please help me.

**Comment by normanmaurer** [comment]
@wsrspirit you will need to implement your own `ChannelPool`, sorry.

**Comment by wsrspirit** [comment]
I think maybe change `SimpleChannelPool` so it can easy to extend to do so, give me some advice?

**Comment by normanmaurer** [comment]
@wsrspirit sorry but I am currently too busy to look into it myself. If you will find out that we need some changed feel free to submit a PR tho
