### ISSUE TITLE
Compatibly of TCN 2.0.12 with Netty 4.1.25? Mutual TLS is maybe broken?

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#8089]
I don't have much info about it at the moment and won't be able to investigate it for the next two weeks but upgrading TCN (OpenSSL) from 2.0.10 to 2.0.12 seems to break something. On the first glance it's mutual TLS but I'm not sure (i.e. could be all TLS).

I'll be able to provide more info when I'm back.

**Comment by normanmaurer** [comment]
It’s not compatible... 4.1.26.Final will be the first that is

**Comment by johnou** [comment]
@normanmaurer picked a date for 4.1.26.Final?

**Comment by normanmaurer** [comment]
Let me close this as stated its because its not compatible.

**Comment by rkapsi** [comment]
@normanmaurer just to close the loop, I can confirm that it was a 2.0.12 w/ 4.1.25 incompatibility. 

What are your thoughts on semver'ing TCN? Would the incompatibly warranted a TCN release of 2.1.0 instead of 2.0.12?
