### ISSUE TITLE
failed to load the required native library

### ISSUE THREAD

**Issue by liuhea** [netty/netty#8093]
```
sslCtx = SslContextBuilder
                    .forClient()
                    .sslProvider(SslProvider.OPENSSL)
                    .trustManager(SingUtilsKt.openAsset(this, "ca.cer"))
                    .keyManager(SingUtilsKt.openAsset(this, "cc.crt"), SingUtilsKt.openAsset(this, "cc.pkcs8.pem"))
                    .clientAuth(ClientAuth.REQUIRE).build();
```
### Expected behavior
     Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_aarch_64, netty_tcnative_linux_aarch_64_fedora, netty_tcnative]

### Netty version
    implementation group: 'io.netty', name: 'netty-handler', version: '4.1.15.Final'
    implementation group: 'io.netty', name: 'netty-tcnative-boringssl-static', version: '2.0.6.Final'

### JVM version (e.g. `java -version`)

openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

### OS version (e.g. `uname -a`)
Linux liuhe-linux 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
We do not ship native libraries for aarch_64 so you can not use it there

**Comment by liuhea** [comment]
can you help me? netty client runing android, i need add sslContext to verify Certification, what can I do ?

**Comment by normanmaurer** [comment]
Just use SslProvider.JDK

**Comment by liuhea** [comment]
Server implement the feature by the way of SslProvider.OPENSSL, and java clinet can do it , why android client can't do it ?I am very troubled　and if i remove sslCtx ,my code run good.
