### ISSUE TITLE
Where's the codes to ensure single-threading model when addlast() with EventExecutorGroup?

### ISSUE THREAD

**Issue by kingluo** [netty/netty#8095]
The netty 4.0 wiki said:

> If multithreaded EventExecutor or EventLoop is specified, one of the threads will be chosen first and then the chosen thread will be used until deregistration.

But I cannot find codes to implement such logic. The context's executor seems `final` and set in constructor, and it seems that all `EventExecutorGroup` sub-classes do not ensure such single-threading restriction.

**Comment by normanmaurer** [comment]
Its done here: https://github.com/netty/netty/blob/netty-4.1.25.Final/transport/src/main/java/io/netty/channel/DefaultChannelPipeline.java#L123
