### ISSUE TITLE
Misleading native transports doc?

### ISSUE THREAD

**Issue by njhill** [netty/netty#8097]
The [native transports wiki page](https://netty.io/wiki/native-transports.html#using-the-linux-native-transport) suggests using the `os-maven-plugin` maven plugin to configure the classifier of e.g. the `netty-transport-native-epoll` dependency.

But this will substitute the os name and arch based on the _build_ environment, which would typically be arbitrary/variable (e.g. a CI platform, local workstation, ...). Whereas this is only really important for the target _runtime_ environment.

Furthermore, only `linux-x86_64` is supported for epoll, and so it seems to me the correct advice would be to have the `<classifier>` fixed to this wherever the dependency is included, regardless of the build/runtime envs. This is effectively what happens already when using `netty-all`.

**Comment by normanmaurer** [comment]
@njhill want to do a PR ?

**Comment by njhill** [comment]
@normanmaurer AFAICT you can't do PRs for github wiki content, so I just edited that page directly. If there are any concerns/comments we can easily revert or update it, PTAL: https://github.com/netty/netty/wiki/Native-transports/_compare/3111bd83110138c5930666ccc948c39813847204...3692b87b30c6adc46c11c9e8d28762c303ca62d4

**Comment by njhill** [comment]
@normanmaurer updating the doc wiki doesn't appear to have updated the pages yet. Assuming you agree with the changes, is there something which needs to run to regenerate?

**Comment by normanmaurer** [comment]
I will need to re-generate these... doing as we speak.
