### ISSUE TITLE
Proposal: introduce isWritable() method for ChannelHandlerContext

### ISSUE THREAD

**Issue by doom369** [netty/netty#8098]
Very often I have to use next code pattern:

`ctx.channel().isWritable()`

It would be very convenient to introduce the same method for the `ChannelHandlerContext`:

`ctx.isWritable()`

WDYT?

**Comment by normanmaurer** [comment]
I think I would only do it if there is any notion of have different writability states per `ChannelHandlerContext` otherwise you could basically say this for most `Channel` methods.
