### ISSUE TITLE
More compression codecs

### ISSUE THREAD

**Issue by trustin** [netty/netty#81]
Check this out: https://github.com/ning/jvm-compressor-benchmark/wiki

**Comment by idelpivnitskiy** [comment]
Check [aircompressor](https://github.com/airlift/aircompressor), according to the @slandelle's suggestion: https://github.com/netty/netty/pull/4607#issuecomment-208310679

**Comment by normanmaurer** [comment]
I think we can close this for now as we added a lot of these

**Comment by slandelle** [comment]
@normanmaurer One day, I'd like to investigate Brotli and SDCH. No idea when :(
