### ISSUE TITLE
failed to initialize the client-side SSL context

### ISSUE THREAD

**Issue by liuhea** [netty/netty#8101]
### Actual behavior

07-05 10:10:53.396 17821-17821/com.example.administrator.testnetty E/MainActivity: failed to initialize the client-side SSL context

### Steps to reproduce

``` 
InputStream crt = SingUtilsKt.openAsset(this, "TBOX000012.crt");
            InputStream pkcs = SingUtilsKt.openAsset(this, "TBOX000012.pkcs8.pem");
            InputStream ca = SingUtilsKt.openAsset(this, "ca.cer");

SslContextBuilder.forClient()
                    .sslProvider(SslProvider.JDK)
                    .keyManager(crt, pkcs)
                    .trustManager(ca)
                    .clientAuth(ClientAuth.REQUIRE)
                    .ciphers(cipher)
                    .build();
```
### Netty version
    implementation files('src/libs/netty-all-4.1.15.Final.jar')
    implementation files('src/libs/netty-tcnative-2.0.7.Final-linux-x86_64.jar')

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

### OS version (e.g. `uname -a`)
Linux liuhe-linux 4.15.0-24-generic #26~16.04.1-Ubuntu SMP Fri Jun 15 14:35:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
you should remove `netty-tcnative-2.0.7.Final-linux-x86_64.jar` from your class path... Also please include all the stack traces.

**Comment by liuhea** [comment]
use netty4.1.25 reslove my crash problems.
