### ISSUE TITLE
Netty - PooledByteBufAllocator and Unpooled.wrappedBuffer method - potential bug?

### ISSUE THREAD

**Issue by felixunivers** [netty/netty#8103]
After allocating some direct buffers and trying them to be combined into a wrapped buffer,
the referenced initial buffers become unusable / freed. Example:

        ByteBufAllocator pbba = PooledByteBufAllocator.DEFAULT;
        BUFFERS.add(0, pbba.directBuffer(32, 32));      // buffer of fixed size  32 bytes - header 1
        BUFFERS.add(1, pbba.directBuffer(128, 128));    // buffer of fixed size 128 bytes - header 2
        BUFFERS.add(2, pbba.directBuffer(256));         // buffer of minimum size 256 (can grow) - for data of various size

                                                        // Combine 2 buffers - indexes: 0 and 2
        BUFFERS.add(3, Unpooled.wrappedBuffer(BUFFERS.get(0), BUFFERS.get(2)));

If we now do:

    ByteBuf bb0 = BUFFERS.get(0);
    System.out.println(bb0.refCnt());    // returns 0  !!!
    bb0.writeBytes(headerPrefix);        // throws exception;   headerPrefix = 4 bytes array

bb0 is shown by debugger as 'freed',  .refCnt() returns 0,  and the next line -  bb0.writeBytes(x) throws exception: 
    io.netty.util.IllegalReferenceCountException: refCnt: 0

BUT, if we write some data into the buffer before we call the wrappedBuffer(...) method,
all appears to be working fine:

    HEADER_BUFFERS.get(0).writeBytes(headerPrefix);   // headerPrefix = 4 bytes array
    Unpooled.wrappedBuffer(BUFFERS.get(0), BUFFERS.get(2));
    ByteBuf bb0 = BUFFERS.get(0);
    System.out.println(bb0.refCnt());              // returns 1  !!!
 
BUT, since we did not write any data to the 2nd buffer, the problem remains there.
    ByteBuf bb2 = BUFFERS.get(2);
    System.out.println(bb2.refCnt());              // returns 0  !!!

Perhaps this is a feature to auto-release unused memory, but in this case it presents itself rather as a bug. Hopefully it is something Netty designers/insiders could clear up for us.

**Comment by normanmaurer** [comment]
@felixunivers I am not sure if I correctly understand the problem but if I understood it correctly you are surprised that calling `Unpooled.wrappedBuffer(...)` with an "empty buffer" will release the "empty buffer" right away.  I think this works as "designed" as once you call this method the ownership is transferred and in this case it will just release the buffer directly as its empty.

I can see why this may be confusing and could lead to surprising and hard to debug code. Let me do a pr to change this and discuss with the other developers in this pr.

**Comment by normanmaurer** [comment]
@felixunivers so actually after thinking a bit more about it and reading our java docs again I think it works as expected... Changing it would be surprising to people that expect it to work like documented.

That said we just deprecated these methods in favour of using `Unpooled.wrappedUnmodifiableBuffer(...)`. The new method will work exactly how you expected. 

WDYT?

**Comment by normanmaurer** [comment]
See also https://github.com/netty/netty/pull/8040 and https://github.com/netty/netty/pull/8096

**Comment by felixunivers** [comment]
Norman's explanation and further experiencing the design shows that one really has to pay attention to how buffers are used in the code and complement with .retain() where needed. 

Unpooled.unreleasableBuffer(...) appears also useful for similar situations. However, it raises a question regarding potential memory leak:

If I declare in my class:
`    ByteBuf fixedBuf = Unpooled.unreleasableBuffer(PooledByteBufAllocator.DEFAULT.directBuffer(64, 64));
`

This should reserve a 64 bytes chunk of off-heap memory. As documented, Netty ignores here the 'release()' and 'retain()' functionality, therefore, the chunk remains allocated throughout the life of my class. What will happen to the allocated off-heap memory chunk once my class gets out of scope? Will JVM/GC release it? If not, or if I want to discard the 'fixedBuf ' programatically, how can I best deallocate the claimed memory blocks for such ByteBuf objects?

Would you please also point to  explanation(s) / example(s) / best practice for avoiding any memory leaks and issues on ByteBuf objects?

**Comment by Underbalanced** [comment]
> Perhaps, when you Netty gentlemen get bored - a "DynamicWrappedBuffer" that reflects all changes in the member buffers dynamically / instantly could be a cool buffer to add. (Likely a bit PITA to design though).

They take contributions FYI. They probably hardly get bored. 😄

**Comment by normanmaurer** [comment]
Closing as it seems like all is working as designed
