### ISSUE TITLE
Getting the size of an object like DefaultHttpRequest is very difficult

### ISSUE THREAD

**Issue by WhiteTrashLord** [netty/netty#8104]
I just noticed that classes like DefaultHttpRequest or DefaultHttpResponse have no easy method which returns the size of this object in bytes. For me this would be very useful. And probably also for some other people. For example some people might want to block too big requests.

Maybe this can be changed in the next version of Netty?

**Comment by doom369** [comment]
> For example some people might want to block too big requests.

You can do that with  `public HttpObjectAggregator(int maxContentLength);`

Also in HTTP you can use `HttpUtil.getContentLength(HttpMessage message, long defaultValue)` that will give you `content-length` header.

**Comment by WhiteTrashLord** [comment]
There are cases when you don't want to use HttpObjectAggregator.

But I think it would be a good idea to add another parameter for HttpObjectAggregator which can set the maximum Requestheadersize.

Sometimes the header content-length might be missing.
It would make things easier for me if objects which don't use a ByteBuf would store the size in bytes.

**Comment by normanmaurer** [comment]
honestly I think this is not something we want to change. IF you need it you can implement it by yourself.
