### ISSUE TITLE
Log4J2 Auto-detection

### ISSUE THREAD

**Issue by apimastery** [netty/netty#8107]
Not sure if I'm missing something...

[#5047](https://github.com/netty/netty/pull/5047) added Log4J2LoggerFactory and Log4J2Logger. It appears that Log4J2 auto-detection in InternalLoggerFactory wasn't added?
https://github.com/netty/netty/blob/fef462c04333950201ddbfd505c0af730a0c2ffd/common/src/main/java/io/netty/util/internal/logging/InternalLoggerFactory.java#L39

Cheers!

**Comment by normanmaurer** [comment]
@apimastery good catch... See https://github.com/netty/netty/pull/8109
