### ISSUE TITLE
IllegalArgumentException in EpollEventLoop.closeAll() method when stopping the server

### ISSUE THREAD

**Issue by doom369** [netty/netty#8117]
> 05:30:58.576 WARN - Unexpected exception in the selector loop.
> java.lang.IllegalArgumentException: Illegal Capacity: -1
> 	at java.util.ArrayList.<init>(ArrayList.java:158) ~[?:?]
> 	at io.netty.channel.epoll.EpollEventLoop.closeAll(EpollEventLoop.java:357) ~[server-0.38.5.jar:?]
> 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326) ~[server-0.38.5.jar:?]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[server-0.38.5.jar:?]
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server-0.38.5.jar:?]
> 	at java.lang.Thread.run(Thread.java:844) [?:?]

netty.version - 4.1.25.Final
boring.ssl.version - 2.0.8.Final

```
java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```

**Comment by normanmaurer** [comment]
Interesting... This means `IntObjectHashMap.size()` must have returned -1... Not sure yet how this could happen

**Comment by doom369** [comment]
@normanmaurer yeah, same conclusion. I see only one possibility `IntObjectHashMap.removeAt()` was called somewhere. Also this issue appeared only with default java 10 GC - G1. When using parallel GC no errors.

**Comment by normanmaurer** [comment]
@doom369 is it reproducible ?

**Comment by doom369** [comment]
@normanmaurer nope, as this was a single production server where I ran G1 by mistake :).

**Comment by doom369** [comment]
Haven't seen this error for a year. So closing.
