### ISSUE TITLE
Only apply copyMemoy safepoint for java <= 8

### ISSUE THREAD

**Issue by hc-codersatlas** [netty/netty#8122]
Hi, as per https://bugs.openjdk.java.net/browse/JDK-8149596 (and the source code of Java.nio.Bits) safepoint polling is no longer required (or rather it shouldn't be done). It's included as part of Unsafe.copyMemory.

Can we add a check to PlatformDependent where this occurs for java version <= 8 so we don't essentially do safepoint polling twice?

Thanks.

**Comment by normanmaurer** [comment]
sounds good.

**Comment by hc-codersatlas** [comment]
Thanks for the PR. Looks good.

**Comment by johnou** [comment]
b109, should we be checking build too?

**Comment by normanmaurer** [comment]
@johnou honestly I think we either should either just assume its ok if people use java8 (and if its not they should really upgrade) or only not use it for java9 and higher. /cc @hc-codersatlas WDYT ?

**Comment by hc-codersatlas** [comment]
@normanmaurer agree
