### ISSUE TITLE
TCP_QUICKACK need to setoption after each recv()

### ISSUE THREAD

**Issue by Broadroad** [netty/netty#8129]
this flag is not permanent, it only enables a switch to or from quickack mode. Unlike disabling Nagle’s Algorithm, disabling Delayed ACKs on Linux is not a one-time operation: processing within the TCP stack can cause Delayed ACKs to be re-enabled. As a result, to use TCP_QUICKACK effectively requires setting and unsetting the socket option during the life of the connection. 

So I doubt whether it is useful in netty we only set it one time?

**Comment by KowalczykBartek** [comment]
as far as I understand, this is similar behaviour that TCP_QUICKACK in ExtendedSocketOptions expose :)

**Comment by normanmaurer** [comment]
Yes that’s right

**Comment by Broadroad** [comment]
So I need to re-enable this flag after each recv, right? How to do it in netty? Because as I know, netty set it when configure channel, how to continually enable this flag in the connection lifecycle?

**Comment by normanmaurer** [comment]
@Broadroad you can just call `channel.config().setOption(...)`.

**Comment by sgammon** [comment]
@normanmaurer is it sufficient to set `TCP_QUICKACK` on channel create, or do you mean you must set that on the config after each TCP interaction?
