### ISSUE TITLE
Do not use TLS renegotiation if TLS >= 1.3

### ISSUE THREAD

**Issue by hc-codersatlas** [netty/netty#8132]
TLS 1.3 disables renegotiation . Need to check and guard against running the renegotiation code in the SSLHandler and other? places.

Noticed there's a pull request on Java 11 testing and TLS 1.3 is part of 11 (so might as well test it too).

**Comment by normanmaurer** [comment]
I dont think so... if the user requests renegotiation but the protocol does not allow it it should fail (which it does atm).
