### ISSUE TITLE
Should if statement add result == UNCANCELLABLE of DefaultPromise#getNow()

### ISSUE THREAD

**Issue by zhaojigang** [netty/netty#8135]
![image](https://user-images.githubusercontent.com/14085645/42871479-12c03e4a-8aad-11e8-954d-398c70b5aad7.png)

Should if statement change to below:

![image](https://user-images.githubusercontent.com/14085645/42871586-46691500-8aad-11e8-920f-7ad24c467782.png)

**Comment by zhaojigang** [comment]
and if result==null,  setUncancellable() return true?
![image](https://user-images.githubusercontent.com/14085645/42876484-613fa130-8ab9-11e8-9b10-c7d6fdaceeed.png)

**Comment by normanmaurer** [comment]
@zhaojigang good catch.. See https://github.com/netty/netty/pull/8154.
