### ISSUE TITLE
JUnit tests failure in Netty 4.0.56.Final

### ISSUE THREAD

**Issue by dshatov** [netty/netty#8137]
### Expected behavior
Successful tests passing when build latest 4.0.x (4.0.56.Final) release.
### Actual behavior
Tests failure.
```
Tests run: 747, Failures: 183, Errors: 315, Skipped: 61
```
### Steps to reproduce
```bash
git clone https://github.com/netty/netty.git
cd netty
git checkout netty-4.0.56.Final
mvn test
```
Furthermore, it looks like the same problem (at least the number of failed tests is the same) occurred on the CI-server when I tried to open a pull-request for merging into the 4.0 branch: [see here.](https://garage.netty.io/teamcity/viewLog.html?buildId=31819&buildTypeId=pulls_netty&guest=1)

Strange, but, according to [this page](https://garage.netty.io/teamcity/viewType.html?buildTypeId=netty_nightly&branch_netty=4.0&tab=buildTypeStatusDiv), there are no problems with the nightly builds of the 4.0 branch.
### Netty version
4.0.56
### JVM version (e.g. `java -version`)
1.8.0_171
### JDK version (e.g. `javac -version`)
1.8.0_171
### OS version (e.g. `uname -a`)
4.4.0-130-generic Ubuntu SMP x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
works here without problems. That said 4.0 is EOL please upgrade
