### ISSUE TITLE
Backport #7806 to 4.0 to improve behavior on IOException

### ISSUE THREAD

**Issue by ignasi35** [netty/netty#8138]
https://github.com/netty/netty/pull/7806 improved the handling of Exception and specially the logic in the particular case of `IOException`

> Also even on an IOException we should check if the Channel itself is still active or not and if not stop reading.

That PR is only merged on the `4.1` branch. Would it be possible to backport it to `4.0`?

**Comment by normanmaurer** [comment]
4.0 is EOL for over an year please upgrade to 4.1

**Comment by ignasi35** [comment]
Thanks @normanmaurer for the quick response. Will do.

Closing.
