### ISSUE TITLE
LengthFieldBasedFrameDecoder LEAK

### ISSUE THREAD

**Issue by yangRy** [netty/netty#8140]
I use LengthFieldBasedFrameDecoder  in my server. When the load is heavy(the client send so many Strings), some leaks occurred.

### Netty version
4.1.24.Final

### JVM version 
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

### OS version 
Linux deb79143d178f427-000.docker.py 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### The log is as follows:
 [ERROR] LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:
#1:
        Hint: 'LengthFieldBasedFrameDecoder#0' will handle the message from this point.
        io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:116)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
        io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        java.lang.Thread.run(Thread.java:745)
#2:
        Hint: 'DefaultChannelPipeline$HeadContext#0' will handle the message from this point.
        io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:116)
        io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
        io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        java.lang.Thread.run(Thread.java:745)
#3:
        io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:634)
        io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
        io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
        io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        java.lang.Thread.run(Thread.java:745)
Created at:
        io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
        io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
        io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
        io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
        io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        java.lang.Thread.run(Thread.java:745)

**Comment by normanmaurer** [comment]
please show us your handlers in the pipeline. I suspect you are not correctly release the buffer in a following handler

**Comment by yangRy** [comment]
@normanmaurer Thanks for your replay, There are just two handlers in my programe, one is LengthFieldBasedFrameDecoder, the other is ServerHandler writhen by myself. and I have check the ServerHandler so many times and I do release the buffer.
**the pipline is as follows:**
protected void initChannel(SocketChannel socketChannel) throws Exception {
     socketChannel.pipeline().addLast(new LengthFieldBasedFrameDecoder(msgMaxLen, 0, 4, 0, 4));
     socketChannel.pipeline().addLast(new ServerHandler(parseThreadPool, storageThreadPool, cpds, clientAddrs));
}

the ServerHandler is as follows:
public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
		ByteBuf buf = (ByteBuf)msg;
		try {
                     int readableByteLength = buf.readableBytes();
                     while (true) {
                           long remain = Server.dataMemLimit.get();
                           if (remain >= buf.readableBytes()) {
                               if (Server.dataMemLimit.compareAndSet(remain, remain - readableByteLength)) {
                                   break;
                               }
                           } else {
                               ctx.writeAndFlush(Unpooled.copiedBuffer("fail", CharsetUtil.UTF_8));
                               ctx.close();
                               return;
                           }
                    }
                    byte[] data = new byte[readableByteLength];

                    buf.readBytes(data);
                    String request = new String(data, "utf-8");
                    data = null;

                     Runnable task = new ParseTask(request, readableByteLength, cpds, ctx, storageThreadPool, clientAddrs);
                     parseThreadPool.execute(task);
             } finally {
                     ReferenceCountUtil.release(buf);
              }
    }

**Comment by normanmaurer** [comment]
@yangRy sorry I totally forgot about this one... Can you run with Paranoid leak detection and share the details here ?

**Comment by normanmaurer** [comment]
@yangRy ping

**Comment by normanmaurer** [comment]
We fixed another possibility for false-positives in 4.1.30.Final. Please upgrade and report back if you still see the issues.
