### ISSUE TITLE
Http2UnknownFrames being written out of order w/ Http2MultiplexCodec

### ISSUE THREAD

**Issue by Bennett-Lynch** [netty/netty#8142]
### Expected behavior

I would expect/like for `Http2MultiplexCodec` to write both `Http2DataFrame`s and `Http2UnknownFrame`s in the same order that they are written to the Codec from a child channel.

### Actual behavior

`Http2DataFrame`s and `Http2UnknownFrame`s are written potentially out of order.  Presumably this has something to do with flow control only applying to `Http2DataFrame`s. This is especially concerning when a frame with the `END_OF_STREAM` flag set is written out of order (i.e., prematurely).

Here is an example:
```
20:05:58.888 Client write of: DefaultHttp2HeadersFrame(stream=null, headers=DefaultHttp2Headers[:path: /foo, :method: POST], endStream=false, padding=0)
20:05:58.901 Client write of: DefaultHttp2DataFrame(stream=null, content=UnpooledHeapByteBuf(ridx: 0, widx: 424, cap: 424/424), endStream=false, padding=0)
20:05:58.906 Client write of: DefaultHttp2UnknownFrame(frameType=20, stream=null, flags=value = 1 (ACK,END_OF_STREAM,), content=UnpooledHeapByteBuf(ridx: 0, widx: 255, cap: 255/255))
20:05:58.930 Server read of: DefaultHttp2HeadersFrame(stream=3, headers=DefaultHttp2Headers[:path: /foo, :method: POST], endStream=false, padding=0)
20:05:58.932 Server read of: DefaultHttp2UnknownFrame(frameType=20, stream=3, flags=value = 1 (ACK,END_OF_STREAM,), content=UnpooledSlicedByteBuf(ridx: 0, widx: 255, cap: 255/255, unwrapped: PooledUnsafeDirectByteBuf(ridx: 344, widx: 777, cap: 1024)))
20:05:58.941 Server read of: DefaultHttp2DataFrame(stream=3, content=UnpooledSlicedByteBuf(ridx: 0, widx: 424, cap: 424/424, unwrapped: PooledUnsafeDirectByteBuf(ridx: 777, widx: 777, cap: 1024)), endStream=false, padding=0)
```

My understanding of HTTP/2 flow control is admittedly minimal.  I see in the [spec](https://http2.github.io/http2-spec/#fc-principles) that:

> 5. The frame type determines whether flow control applies to a frame. Of the frames specified in this document, only DATA frames are subject to flow control; all other frame types do not consume space in the advertised flow-control window. This ensures that important control frames are not blocked by flow control.
> 6. Flow control cannot be disabled.

Would there be anyway to guarantee ordering of these two frame types while still adhering to the spec?  How do we guarantee that a trailing `Http2HeadersFrame` with `END_OF_STREAM` flag is not delivered before a `Http2DataFrame`?

### Netty version
4.1.27.Final

**Comment by normanmaurer** [comment]
@ejona86 @bryce-anderson @mosesn @Scottmitch can you chime in ?

**Comment by ejona86** [comment]
The problem is these are unknown frame types. We don't know how to handle them. We'd have to have some sort of knowledge of whether they should be in-line with flow controlled frames. I've always questioned the usefulness of unknown frame handling in Netty, because of things like this.

Note that receive-side is especially tricky. If Netty _receives_ one of these unknown frames, how does it know to delay delivering it to the application until after the DATA frames that preceded it?

@Bennett-Lynch, can you share at all what this unknown frame is?

**Comment by bryce-anderson** [comment]
I don't think this is specific to `Http2MultiplexCodec`, is it?

as @ejona86's pointed out, there is not any way for Netty to know auto-magically, but the interface `Http2RemoteFlowController.FlowControlled` may be helpful. It's used in the `FlowControlledHeaders` class for exactly this purpose: to preserve order.

According to the h2 spec unknown or unsupported extension frames should be ignored. Maybe Netty should be doing that instead of trying to handle them to avoid situations like this.

**Comment by Bennett-Lynch** [comment]
Thanks for the replies, @ejona86 and @bryce-anderson.

I admit some of my issues and feature requests are probably pushing the boundaries for what Netty ought to offer in terms of supporting "unknown" frames.  As you both accurately pointed out, these frames are -- by their very definition -- "unknown" and Netty does not know how to handle them.

However, I think Netty is in compliance with the [spec](https://http2.github.io/http2-spec/#extensibility) in terms of how it handles these frames today:

> Implementations MUST ignore unknown or unsupported values in all extensible protocol elements. Implementations MUST discard frames that have unknown or unsupported types. This means that any of these extension points can be safely used by extensions without prior arrangement or negotiation.

By forwarding these unknown frame types down the channel, it is letting the application (i.e., "implementation") choose to ignore/discard them, or to potentially act on them in such a way that would not require a Netty version update in the case of an extension of the protocol (however unlikely that may be).  It is also doing it in a way that does not create unnecessary noise for normal use cases.

To answer your question, @ejona86, I'm taking advantage of the fact that any significant protocol extension seems unlikely, and I'm using these frames to represent different data types across a single stream ID.

However, I discovered that sending the `END_OF_STREAM` flag in a `Http2DataFrame` will allow these unknown frames to be sent first, making this issue less of a concern for me personally.  As such, and since I think your points are valid, I'm going to go ahead and close this out -- unless you think it merits further discussion.  Thanks again for the replies.
