### ISSUE TITLE
Http2MultiplexCodec's usage of ConnectionPreface does not adhere to the spec

### ISSUE THREAD

**Issue by Bennett-Lynch** [netty/netty#8146]
### Expected behavior

Section [3.5 HTTP/2 Connection Preface](https://http2.github.io/http2-spec/#rfc.section.3.5) of the HTTP/2 spec states that:

> To avoid unnecessary latency, clients are permitted to send additional frames to the server immediately after sending the client connection preface, without waiting to receive the server connection preface. It is important to note, however, that the server connection preface SETTINGS frame might include parameters that necessarily alter how a client is expected to communicate with the server. Upon receiving the SETTINGS frame, the client is expected to honor any parameters established. In some configurations, it is possible for the server to transmit SETTINGS before the client sends additional frames, providing an opportunity to avoid this issue.

I expect for a client to be able open a new HTTP/2 connection with a server and immediately begin writing HEADER and DATA frames.

### Actual behavior

Netty's usage of the [Http2ConnectionPrefaceAndSettingsFrameWrittenEvent](https://netty.io/4.1/api/io/netty/handler/codec/http2/Http2ConnectionPrefaceAndSettingsFrameWrittenEvent.html) _requires_ that the client waits for the server to receive the preface before writing any data:

> Signifies that the connection preface and the initial SETTINGS frame have been sent. The client sends the preface, and the server receives the preface. The client shouldn't write any data until this event has been processed.

This requirement seems to specifically not adhere to the spec above, and it enforces unnecessary latency.

A client that does not wait for the `Http2ConnectionPrefaceAndSettingsFrameWrittenEvent` will receive the following connection-level exception:

```
io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: ...
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:318)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450)
	...
```

### Netty version

4.1.27.Final

**Comment by normanmaurer** [comment]
@Scottmitch @ejona86 @bryce-anderson @mosesn thoughts?

**Comment by normanmaurer** [comment]
Also @Lukasa for input :)

**Comment by Scottmitch** [comment]
The H2 codec doesn't attempt to queue any data nor delay sending until after the preface has been sent. Instead it uses pipeline events (`channelActive` and/or `handlerAdded`) to [trigger sending the preface](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L360-L383). The `Http2ConnectionPrefaceAndSettingsFrameWrittenEvent` user event is meant to provide the trigger point for folks sequence their writes or queue if they so desire.

> Netty's usage of the Http2ConnectionPrefaceAndSettingsFrameWrittenEvent requires that the client waits for the server to receive the preface before writing any data:

It is not necessary that the server receive the preface before the client can write any data. You demonstrated this from the exception you provided above. You just need to make sure that you locally sequence the writes on the client so that the server receives the preface before anything else. That is what the `Http2ConnectionPrefaceAndSettingsFrameWrittenEvent` is designed to help with.

**Comment by Lukasa** [comment]
Yup, @Scottmitch seems to be right: the event seems to be a sequencing requirement, nothing more.

**Comment by bryce-anderson** [comment]
My understanding is the same as @Scottmitch described: the event is only to let the pipeline know that the preface/settings have been encoded and placed in the outbound queue (but not necessarily sent across the connection) and that the h2 session is ready to be used for dispatches.

**Comment by Bennett-Lynch** [comment]
Thanks for the replies.

I think I was misled by the Javadoc, which sort of makes it sound like a client/server handshake:

> The client sends the preface, and the server receives the preface. The client shouldn't write any data until this event has been processed.

Closing this out.

**Comment by normanmaurer** [comment]
@Bennett-Lynch if you can think of any way to make this clearer please open a PR with doc enhancements.

**Comment by ejona86** [comment]
Seems everything is handled.

I would just point out that "clients are permitted" does not mean that clients _must_ support avoiding the RTT. The spec does _not_ require clients to avoid the RTT. So Netty would still be in spec-compliance if it waited for the HTTP/2 SETTING handshake to complete.

But yes, Netty does allow issuing other frames before the initial handshake is complete.
