### ISSUE TITLE
Significant epoll native memory usage jump in 4.1.26.Final

### ISSUE THREAD

**Issue by njhill** [netty/netty#8159]
### Expected behavior

Native memory use is stable between releases.

### Actual behavior

Significant jump in native memory usage when using epoll transport between 4.1.25.Final and 4.1.26.Final.

### Steps to reproduce

Observe process native memory usage when using `EpollEventLoopGroup`(s) between the above versions. Usage is comparable between NIO and epoll in version 4.1.25.Final, and also between 4.1.25.Final and 4.1.26.Final when using NIO.

This is particularly significant when using the default ELG size (cores *2) on large SMP machines, and/or when there are multiple ELGs in the JVM due to use of netty in different libraries. In this case the difference can run into hundreds of MB (despite the heap being only 512M), and easily breach cgroup mem limits.

I assume this is caused by https://github.com/netty/netty/pull/8062. Also in light of that change it appears this comment is no longer accurate: https://github.com/netty/netty/blob/d20370dd5f15c7e08c252e0b818c91113d7bea94/transport-native-epoll/src/main/java/io/netty/channel/epoll/NativeDatagramPacketArray.java#L103

### Netty version

4.1.26.Final, 4.1.27.Final, 4.1.28.Final

### JVM version (e.g. `java -version`)

```
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```

### OS version (e.g. `uname -a`)

```
4.4.0-127-generic #153-Ubuntu SMP x86_64 GNU/Linux
```

**Comment by njhill** [comment]
#8062 changed things so that `NativeDatagramPacketArray` and associated mem gets allocated on event loop construction, rather than first use of `EpollDatagramChannel` (which may often not be used at all). Opened #8160 with a simple fix for this.

**Comment by normanmaurer** [comment]
@njhill thanks... left a few comments but mostly nits :)
