### ISSUE TITLE
Restarting an event loop thread to deal with indefinitely blocking handlers.

### ISSUE THREAD

**Issue by trustin** [netty/netty#816]
Due to some reason (implementation problem, environment problem, etc), there's a case where a handler sometimes blocks indefinitely.  In this case, an administrator might want to create a new event loop thread and migrate all channels (except the blocked one) to the new thread to keep the server working.

**Comment by normanmaurer** [comment]
@trustin can we just close this ?

**Comment by trustin** [comment]
And the reason is?

**Comment by normanmaurer** [comment]
@trustin no-one seems to have time doing it and no-one asked for it except you ;) ? If you are still interested please assign it to you. Just trying to cleanup the issue tracker a bit atm

**Comment by trustin** [comment]
Closing, then. :-)
