### ISSUE TITLE
SameSite attribute support for response cookies

### ISSUE THREAD

**Issue by trustin** [netty/netty#8161]
From: https://github.com/spring-projects/spring-framework/commit/09d9450154be796349dabdc606ade57beae08724

> As explained in rfc6265bis, this attribute can be used to limit the scope of a cookie so that it can't be attached to a request unless it is sent from the "same-site". This feature is currently supported by Google Chrome and Firefox, other browsers will ignore this attribute. This feature can help prevent CSRF attacks; this is why this commit adds this attribute by default for SESSION Cookies in WebFlux. See: https://tools.ietf.org/html/draft-ietf-httpbis-rfc6265bis

**Comment by slandelle** [comment]
Dup of #6509, planned for next major version where we can break API.

**Comment by trustin** [comment]
Oh, that's true. I guess it's time to split Cookie into RequestCookie and ResponseCookie?

**Comment by slandelle** [comment]
How would this help? We have different encoders and decoders for client and server side.

**Comment by slandelle** [comment]
I don’t think it’s very common to craft client side cookies. On the client side, you either have a CookieStore or you’re writing a proxy and just want to transfer. I suspect having distinct APIs would make things more comfortable complicated.

**Comment by trustin** [comment]
I thought `samesite` attribute is only applicable to `ServerCookieEncoder`? We could just add it to `Cookie` and document properly to mention it's only useful for response cookies, though.

**Comment by trustin** [comment]
Alternatively, we could introduce some type hierarchy like `ResponseCookie` being a subtype of `Cookie`.

**Comment by slandelle** [comment]
We’ll have to find a good balance between clarity and performance. If we have 2 hierarchies, client side will have to allocate more when converting ResponseCookies from the CookieStore into ClientCookies for the client encoder. Maybe the better design is worth it.
Can’t wait for the work on next gen Netty to start :)

**Comment by trustin** [comment]
>  Can’t wait for the work on next gen Netty to start :)

Yes, sir! Looking forward to seeing an awesome PR :-D

**Comment by bryce-anderson** [comment]
With the imminent changes to [Chrome](https://blog.chromium.org/2019/10/developers-get-ready-for-new.html) (and it sounds like Firefox and Edge will follow) is there now a stronger case for supporting `SameSite` attributes in Netty4? I haven't looked into the details, but we could lend a hand if it's just a matter of getting it done.

**Comment by slandelle** [comment]
@bryce-anderson I think the issue is not a lack of manpower but a semver one as `io.netty.handler.codec.http.cookie.Cookie` is considered a stable public API. I can't think of a way to add a new attribute without breaking it (no Java 8 default methods). Maybe introduce a CookieV2?
Generally speaking, I think there's a risk new attributes might be added to Cookies at a faster pace than Netty major versions and we need to design a strategy for this.

**Comment by bryce-anderson** [comment]
@slandelle, that's true, and I suppose a risk of making much of the API open interfaces that anybody can extend. Are you aware of any projects making their own implementations of `Cookie`? Not that it matters in the context of the semver question, but in future iterations if it doesn't make senses to let users implement a specific API, most commonly data only API's like cookies, maybe they'd be better off as final classes.

**Comment by slandelle** [comment]
> Are you aware of any projects making their own implementations of Cookie?

No I'm not.

> maybe they'd be better off as final classes.

I completely agree. I fail to see a use case for wanting to bring a different implementation.

**Comment by bryce-anderson** [comment]
Well, one hack around this would be to enhance the `DefaultCooke` implementation and downcast. It's definitely not pretty though and I don't know if anybody else is suffering from the same pain as we are. Following a few links from above it looks like others are just writing their own cookie parsers to address this.

**Comment by bryce-anderson** [comment]
Just so you know, I feel dirty about the above suggestion so no need for extra judgement. 😉

**Comment by slandelle** [comment]
Well, DefaultCookie is non final, so the semver rule applies too.
Sadly, if we can’t break semver here, several people (including myself, super sad, all the more as I contributed some of this code) will end up forking until this get fixed in Netty 5.

**Comment by slandelle** [comment]
Hence my suggestion of having the new implementation live next to the existing one in Netty 4.1 in a different package, and possibly Cookie implement for compatibility.

**Comment by dvlato** [comment]
I would think that adding a field to DefaultCookie would not be a breaking change (as opposed to an interface without default methods).

However, I would be happy with your suggestion of having a new implementing class for cookies (maybe ResponseCookies as per trustin's comment?)   that would include the attribute.

This works seems quite important considering Chrome's timeline: https://www.chromium.org/updates/same-site?pli=1#20190930

**Comment by slandelle** [comment]
@normanmaurer it's up to you, we just need a decision :)

**Comment by ddjones-fss** [comment]
While you decide, our applications are about to fail in production due to our inability to move forward... !!

**Comment by normanmaurer** [comment]
@slandelle an extra field to `DefaultCookie` should be fine imho...

**Comment by slandelle** [comment]
Cool.
On vacation atm, will come up with a PR next week, except if someone is in a hurry and want to give it a shot.

**Comment by dvlato** [comment]
Hi,  as per @normanmaurer comment in  https://github.com/HotelsDotCom/styx/pull/607#issuecomment-586278932,  I have pushed some changes into my fork with the same kind of fix we added for the SameSite attribute. 

Our changes to netty did not include any checks regarding whether the value of SameSite attribute is valid or not (so not checking anywhere if it is equal to Lax | Strict | None) as it seemed good enough for us. However I do not know if that's acceptable in Netty or you'd rather check the value is valid - I initially implemented this field as an enum indeed... 

Would you like to take a look and suggest any changes?   https://github.com/netty/netty/compare/4.1...dvlato:issue-354-samesite-attribute?expand=1. I haven't sent a PR as I imagine I have to get Expedia to sign the ccla first.
