### ISSUE TITLE
setDefaultHostnameVerfier

### ISSUE THREAD

**Issue by trondarild-lode-tobiassen-heidelberg** [netty/netty#8163]
Feature request

### Expected behavior: ```
SSLEngine sslEngine = ....
sslEngine.setDefaultHostnameVerfier(new HostnameVerifier(){@Override
                        public boolean verify(String arg0, SSLSession arg1) {
                            return true; //or other test
                        }});
```

### Actual behavior: nonexistent

### Steps to reproduce: nonexistent

### Minimal yet complete reproducer code (or URL to code): nonexistent

### Netty version: latest

### JVM version (e.g. `java -version`) 8 and later

### OS version (e.g. `uname -a`) WIn7 and later, Android 8 and later

**Comment by slandelle** [comment]
`javax.net.ssl.SSLEngine` is a JDK API, not a Netty one!

SSLEngine doesn't have a notion of HostnameVerifier atm, only `javax.net.ssl.HttpsURLConnection` has.
Since Java 7, it's possible to turn hostname verification and other features on, see `SSLParameters#setEndpointIdentificationAlgorithm`.
But it's not possible to plug your own implementation.

**Comment by trondarild-lode-tobiassen-heidelberg** [comment]
Sorry, should have checked the package before I posted. Maybe somehow via Bootstrap. But I will Check SSLParameters.

**Comment by trondarild-lode-tobiassen-heidelberg** [comment]
Trying something like this to avoid check of server name (FQDN) against certificate CN:

`										SSLParameters params = new SSLParameters();
										List<SNIMatcher> matchers = new LinkedList<>();
										SNIMatcher matcher = new SNIMatcher(0) {
											
											@Override
											public boolean matches(SNIServerName serverName) {
												return true;
											}
										};
										matchers.add(matcher);
										params.setSNIMatchers(matchers);
										engine.setSSLParameters(params);
`

**Comment by Underbalanced** [comment]
Contributions are welcome. These guys are very busy like everyone else. [Commit Your Code Section](https://netty.io/community.html).

In regards to the FQDN. There are many thing you may have to write your own abstraction on. Unless its a very common use case and the whole group will benefit from or you write the code yourself to contribute to the library. I.E.

**Comment by normanmaurer** [comment]
Like @slandelle said this is part of the JDK not netty. Closing
