### ISSUE TITLE
Http2MultiplexCodec must be in the ChannelPipeline of Channel

### ISSUE THREAD

**Issue by ssheng** [netty/netty#8169]
Hi Folks,

I'm hitting this exception when using Http2StreamChannelBootstrap to create outbound stream channels on the client side. The exception message is very clear on what was missing. But my question is how to use Http2StreamChannelBootstrap and ApplicationProtocolNegotiationHandler on the client side.

ApplicationProtocolNegotiationHandler adds Http2MultiplexCodec upon a successful SslHandshakeCompletionEvent. I currently have to rely on a promise to ensure Http2MultiplexCodec is added before invoking Http2StreamChannelBootstrap#open.

I find using the promise a bit awkward. Is there a better practice you'd recommend?

Is non-ALPN based HTTP/2 supported, like prior knowledge maybe?

Piggybacking another question. When I receive a response, will it be on the same instance of the Http2StreamChannel that sent the original request?

Much thanks,
Sean

**Comment by normanmaurer** [comment]
Can you share the code ?

**Comment by normanmaurer** [comment]
Closing as no response from reporter
