### ISSUE TITLE
Can hex dumping in LoggingHandler be disabled?

### ISSUE THREAD

**Issue by jianglai** [netty/netty#8172]
Hex dump is nice when one wants to look at each byte carefully, but sometimes I just want the content itself (maybe we can specify an encoding in the constructor to decode the bytes correctly).

More importantly, hex dump interferes with the ability to effectively search the content. For example I have some service that uses LoggingHandler to log all messages that it processes. When something goes wrong, I want to debug by searching in the log for specific strings that indicate a specific message. With hex dump enable, I have something like this to search in:

```
|00000320| 3c 73 76 54 52 49 44 3e 50 38 67 6e 36 6b 63 4b |<svTRID>P8gn6kcK|
|00000330| 51 74 53 37 5a 74 46 64 59 41 76 65 68 51 3d 3d |QtS7ZtFdYAvehQ==|
|00000340| 2d 36 39 3c 2f 73 76 54 52 49 44 3e 0a 20 20 20 |-69</svTRID>.   |
|00000350| 20 20 20 20 20 3c 2f 74 72 49 44 3e 0a 20 20 20 |     </trID>.   |
|00000360| 20 3c 2f 72 65 73 70 6f 6e 73 65 3e 0a 3c 2f 65 | </response>.</e|
|00000370| 70 70 3e 0a                                     |pp>.            |
+--------+-------------------------------------------------+----------------+
```

You can see that the `<svTRID>` tag is cut off and if I search for its content `P8gn6kcKQtS7ZtFdYAvehQ==-69` I won't be able to find this log.

The [javadoc](https://netty.io/4.1/api/io/netty/handler/logging/LoggingHandler.html) for constructors of `LoggingHandler` mentions "with hex dump enabled" several times, so it is natural to assume that there are ways to disable it.

If there's no such functionality yet, will you be willing to look at a PR that adds this?

Thanks!

**Comment by BrokenDream** [comment]
@jianglai  i don't think it's a problem. 

if we look at the method 'format(ChannelHandlerContext ctx, String eventName, Object arg)' of LoggingHandler, we will find that it just do hex dumping if the type of **arg** is **ByteBuf** or **ByteBufHolder**,
so i think if you put the LoggingHandler  in the different position of the pipeline, you may get the different forms of log, it depends on the TYPE of **arg**.

BTW i think "with hex dump enabled" just means the LOG LEVEL is DEBUG.

Forgive my poor English...

**Comment by jianglai** [comment]
Thanks, but I do want to keep my `LoggingHandler` where it is right now in the channel pipeline. More specifically I am logging HTTP requests and response objects and I like it that the `LoggingHandler` prints out the headers nicely. The content of the HTTP objects are stored in `ByteBuf` so they are hex dumped.

I'm willing to do the work to optionally disable the hex dump maintainer is open to such a PR.

**Comment by normanmaurer** [comment]
@jianglai I am kind of confused... What exactly you propose ? Maybe you can show it with a PR ?

**Comment by jianglai** [comment]
@normanmaurer My intention is be able to turn off hexdump and just have the `LoggingHandler` output the raw data in a ByteBuf. Like in the example I have in the original post, there's no way to search for the string `P8gn6kcKQtS7ZtFdYAvehQ==-69` (name of the tag `<svTRID>`) in the output of `LoggingHandler` because it was cut off to three parts.

Will make a PR.

**Comment by shubhamgoyal297** [comment]
@jianglai have you found any solution?

**Comment by jianglai** [comment]
@shubhamgoyal297 unfortunately no. I think your best choice is to write your own logging handler.

**Comment by normanmaurer** [comment]
@jianglai @shubhamgoyal297 isn't it just as easy as extending the `LoggingHandler` and override the format* methods ?

**Comment by jianglai** [comment]
Yes that's that I meant by "writing your own logging handler" :)

**Comment by CiaranMcCann** [comment]
Have the same issue, would be great to have it added as optional output from the debug logs.

**Comment by normanmaurer** [comment]
Like I said I think people should just extend. Closing
