### ISSUE TITLE
When will HTTP/2 API be stabilized?

### ISSUE THREAD

**Issue by jianglai** [netty/netty#8185]
We are interested in using HTTP/2 but the unstable API makes it hard for us to get internal approval to use it. Are there plans to make the API stable?

**Comment by carl-mastrangelo** [comment]
cc: @ejona86

**Comment by normanmaurer** [comment]
Also @Scottmitch @trustin @mosesn @bryce-anderson

**Comment by ejona86** [comment]
@jianglai, I'll note that Http2ConnectionHandler is unlikely to be stabilized. The API around Http2MultiplexCodec is more feasible. It's unclear to me how close it is. The semi-recent stuff with HTTP/1.1 plaintext upgrade makes me feel like parts of it aren't ready yet. But maybe the majority is.

**Comment by jianglai** [comment]
Thanks for the update. Is there an ETA in mind? I also saw that Netty’s HTTP/2 hello world client example is 2 years old. Maybe the client side of things are more or less stable?

**Comment by huchuanling** [comment]
hello

**Comment by gaurav-4g** [comment]
Hello community, we are excited with the release of Netty 4.1.x to support HTTP/2 and it is expected to make this flawless as compared to other HTTP/2 libraries in the market. As we can see, lots of alternatives are available to implement HTTP/2 based communication using Netty APIs, can we have a consolidated example to showcase various use cases.

**Comment by rschmitt** [comment]
@normanmaurer @Scottmitch Any updates?

**Comment by rschmitt** [comment]
@normanmaurer @Scottmitch Any news? The APIs seem fairly stable ever since the Builder APIs were added (and the corresponding constructors encapsulated), despite some internal churn within the implementation of multiplexing.
