### ISSUE TITLE
GraalVM native image support

### ISSUE THREAD

**Issue by sdeleuze** [netty/netty#8192]
GraalVM now offers an official way to detect its presence via the [`org.graalvm.nativeimage.imagecode` system property](https://github.com/oracle/graal/blob/master/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/ImageInfo.java). We use that in Spring to adapt to Graal (see [GraalDetector](https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/GraalDetector.java)). You could maybe add similar capabilities to Netty `PlatformDependent`. That's seems similar to what you are doing now depending on JDK versions and other parameters, and I think Netty + Graal native images are a pretty exciting combination.

Current area that need customization with Reactor Netty that could take advantage of a dedicated GraalVM detection mechanism are:
 -  `ClassNotFoundException: com.jcraft.jzlib.Deflater` when `--report-unsupported-elements-at-runtime` is not used, see https://github.com/oracle/graal/issues/494
 - `-Dio.netty.noUnsafe=true` has to be specified explicitly

[This blog post](https://medium.com/graalvm/instant-netty-startup-using-graalvm-native-image-generation-ed6f14ff7692) contains also valuable information.

**Comment by sdeleuze** [comment]
Any chance to see that one part of Netty 5 ?

**Comment by normanmaurer** [comment]
@sdeleuze this sounds like a good idea to me... would you be interested in submitting a PR against the master branch ?

**Comment by sdeleuze** [comment]
No sure to have the bandwidth for now, but if that changes I will.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/8963
