### ISSUE TITLE
File upload memory usage with HttpObjectAggregator

### ISSUE THREAD

**Issue by jknack** [netty/netty#8195]
Hi,

Netty ran out of memory when uploading large files using `HttpObjectAggregator`.

The `HttpObjectAggregator` keeps the entire request in memory, then while parsing the request with `HttpPostMultipartRequestDecoder` a new **copy** of the request is made causing OOM issues.

It doesn't matter if `HttpPostMultipartRequestDecoder` was configured to use disk when there is a `HttpObjectAggregator` in the pipeline.

I wonder if HttpObjectAggregator could use the file system when the incoming request exceeds a specific number of bytes.

Thanks.

**Comment by normanmaurer** [comment]
@jknack You would need to write your own aggregator. We are currently not plan to offload to disk.
