### ISSUE TITLE
Use netty 4.1+ TLS with Android 6

### ISSUE THREAD

**Issue by selop** [netty/netty#8199]
My project currently uses a modified version of `4.0.28.Final` which runs on Android 6.0.1. The diff is basically removing all classes which are not existent on Android 6.0.1 to be able to compile netty as a shared library for our Android build.
To use TLS with the parameters needed we construct the `SSLEngine` ourself and hand it over to the netty `SslHandler(SSLEngine engine)`.

We wanted to upgrade netty to `4.1.28.Final` which has better Android support and tons of fixes regarding TLS compared to version `4.0.28.Final`. Since we are using Android 6.0.1 with Conscrypt/BoringSSL the constructed `SSLEngine` is a `org.conscrypt.OpenSSLEngineImpl`.

### Expected behavior
When we init `SslHandler()` with `org.conscrypt.OpenSSLEngineImpl` we expect `SslHandler` to detect the given `SSLEngine` to be a `SslEngineType.CONSCRYPT`.

### Actual behavior
`SSLHandler` will fallback to `SslEngineType.JDK` due to:

    engineType = SslEngineType.forEngine(engine);

   which calls

    static SslEngineType forEngine(SSLEngine engine) {
        return engine instanceof ReferenceCountedOpenSslEngine ? TCNATIVE :
        engine instanceof ConscryptAlpnSslEngine ? CONSCRYPT : JDK;
    }

I also noticed `PlatformDependent0.javaVersion0()` will set to

    if (isAndroid0()) {
        majorVersion = 6;
    } 

but Android 6.0.1 will provide Java 1.7.

### Steps to reproduce
    SSLContext sslContext = SSLContext.getInstance("TLSv1.2");
    sslContext.init(kmf.getKeyManagers(),tmf.getTrustManagers(), new SecureRandom());
    SSLEngine sslEngine = sslContext.createSSLEngine();
    sslEngine.setUseClientMode(true);
    SslHandler sslHandler = new SslHandler(sslEngine);
    channel.pipeline().addFirst(sslHandler)

### Minimal yet complete reproducer code (or URL to code)
N.A.

### Netty version
netty-4.1.28.Final

### JVM version (e.g. `java -version`)
SDK API-level 23
Java 1.7

### OS version (e.g. `uname -a`)
Linux localhost 4.4.111-1.1.1 #14 SMP PREEMPT Wed May 16 01:39:17 CEST 2018 armv7l

**Comment by normanmaurer** [comment]
@selop maybe you could provide a PR ? We love contributions :)

**Comment by normanmaurer** [comment]
@selop maybe you just need to have an extra instanceof check ?

**Comment by normanmaurer** [comment]
@selop so I did some digging and I think the problem here is that Android uses a "different conscrypt" implementation than what we use here. So I think it is not really "that" easy.  Can you tell me what problem you have because of the current implementation ? I think even with JDK it should "just work". 

/cc @nmittler @ejona86 @carl-mastrangelo

**Comment by selop** [comment]
The current situation is that netty accepts the given `OpenSSLEngineImpl` without complaints and a channel is beeing established. Tracing with Wireshark I don't see any Handshake messages at all until the other endpoints (also netty server, version 4.1.27) runs into the default Handshake timeout after 10s.

> So I think it is not really "that" easy. 

Agreed. I read about the PR provided by @nmittler which added support for Conscrypt. Netty depends on a 1.0+ version of Conscrypt which we currently don't provide with our Android build. It seems netty will only work with Conscrypt when we let netty init the SSLEngine via `SslContextBuilder` but not handing over a SSLEngine to `SslHandler` directly. See e.g. cast to `ConscryptAlpnSslEngine` here:
https://github.com/netty/netty/blob/8255f85f24edab5316c0db3aa55bb9709448daa5/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L258

As far as I understand we would need to bump Conscrypt and BoringSSL in our Android build first. I need to do more digging to find our why the JDK fallback does not work at all.

**Comment by normanmaurer** [comment]
@selop it should definitely also work with the JDK stuff.... Please let me know once you find out whats wrong.

**Comment by normanmaurer** [comment]
@selop please let me know once you know more .

**Comment by selop** [comment]
@normanmaurer I was on vacation for the last week. Have not forgotten the issue, no worries.

**Comment by normanmaurer** [comment]
@selop ping

**Comment by normanmaurer** [comment]
@selop any more updates ?

**Comment by selop** [comment]
@normanmaurer Sorry about the late reply. The problem could be that we have a Bouncycastle in the chain which also needs updates. I could not get a timeslot to further investigate this in the last couple of weeks.

**Comment by normanmaurer** [comment]
I will close this for now... Please reopen if you still think there is a problem

**Comment by gnarea** [comment]
See also  #10181
