### ISSUE TITLE
[Question] Can I restore merged http/2 stream?

### ISSUE THREAD

**Issue by lovers36** [netty/netty#8205]
I want to make a server for proxy.

client  ------> proxy server ------> origin server (http/2)
                                               |
                                               ---> origin server (http 1.1)

client send to proxy server HTTP/2 stream data (ex : 3 payloads)
and check HTTP header by proxy server.
if there is special header, send to origin server(http/2) 

I made simple proxy server.

as my test, stream requests are merged.

ex)

header : XXXXX

request 1 payload :  "name, 1"
request 2 payload  :  "date, 3"
request 3 payload  :  "birth, 2"

----> 
header : XXXXX
payload : "name, 1, date, 3, birth, 2"

This is my question.

I want to send origin server(http/2) by streaming (http/2)
(origin server(http 1.1) is OK.)

1. Can I restore merged http/2 stream?
2. if not, how can I seperate payload ? 

I don't find the way for solutions in docs.

have you an Idea ?

**Comment by normanmaurer** [comment]
I am not sure what exactly you try to do... @ejona86 @mosesn @bryce-anderson any idea ?

**Comment by bryce-anderson** [comment]
I'm also not sure what the goal is. _Maybe_ the goal is to preserve the payload chunk structure? It's not clear to me if this represents one request sent with 3 chunks or 3 requests each sent with 1 chunk that are merged into a single request.

**Comment by ejona86** [comment]
If this is talking about data frame payloads, then this is 100% expected and nothing would really change it. Flow control makes it impossible to retain the original chunks.

But in the "payload" it looks like commas are being inserted, so this may be about RFC 7230 allowing merging values:

>    A recipient MAY combine multiple header fields with the same field
   name into one "field-name: field-value" pair, without changing the
   semantics of the message, by appending each subsequent field value to
   the combined field value in order, separated by a comma.

If that is causing a problem, then that means the original header is invalid. Also from 3.2.2:

>    A sender MUST NOT generate multiple header fields with the same field
   name in a message unless either the entire field value for that
   header field is defined as a comma-separated list [i.e., #(values)]
   or the header field is a well-known exception (as noted below).

**Comment by lovers36** [comment]
@bryce-anderson @ejona86 
Thank you for your answer. and I'm sorry for Explanation is not clear.
I'm starter about netty.
My goal is making proxy server for gRPC like a zuul 2. (or using zuul 2)
process what I want is below.

1. support bi-direction streaming of gRPC.
2. there is a few filters using http/2 header.
3. proxy server can't have proto files for gRPC.

grpc client - (netty server - netty client) - grpc server

I guess that if the proxy server can passing http/2 stream, I can achieve the goals.
and I guess that zuul is help me

but, Zuul 2 is not support http/2 proxy.
so, I have been try changing zuul core. but payload had merged.

how can I avoid merged payload?

**Comment by ejona86** [comment]
@lovers36, I think the answer is "everything's fine;" don't worry about the merging. The merging could have actually happened on the grpc client. If the grpc client/server is producing an actual error, I could look at that and try to figure out what's wrong. But if you aren't getting an error, then I think everything's working normally.
