### ISSUE TITLE
Support hosts file encoded in unicode format

### ISSUE THREAD

**Issue by ramtech123** [netty/netty#8208]
### Expected behavior
Netty should be able to resolve IP address from hosts file when the file is encoded in unicode format.

Java is able to resolve hostname from unicode encoded hosts file. Disabling Vertx (Netty) hostname resolution using `-Dvertx.disableDnsResolver=true` flag in our application was the workaround that we used, until we finally identified root cause.

### Actual behavior
`HostsFileParser.parseSilently()` returns `HostsFileEntries` instance with zero entries if the hosts file is encoded in unicode format.

### Steps to reproduce
Open hosts file with text editor (Eg. Windows Notepad) as Administrator.
Save hosts file with unicode encoding.
Run the reproducer and observe the console output.

### Minimal yet complete reproducer code (or URL to code)
https://github.com/ramtech123/pocs/tree/master/netty-hosts-reproducer

### Netty version
4.1

### JVM version (e.g. `java -version`)
Java 1.8

### OS version (e.g. `uname -a`)
Tested with Windows10, Windows Server 2012, 2016

**Comment by normanmaurer** [comment]
@ramtech123 thanks.. Check https://github.com/netty/netty/pull/8211. This allows you to specify the charset to use while decoding.

**Comment by ejona86** [comment]
Based on my own testing with Windows Server 2016, it seems like Windows auto-detects the encoding. I tried with ANSI (ASCII), Unicode (UTF-16), and UTF-8 and they all worked. I saved a trash hostname in `hosts` (different for each test) and then did a ping. Ping noticed my trash hostname configuration each time.

**Comment by ejona86** [comment]
https://serverfault.com/a/452269 seems to think that the encoding should be UTF-8. I wonder if Windows became more permissive in a later version of Windows. I wasn't able to find any official documentation as to the encoding.

**Comment by normanmaurer** [comment]
@ejona86 I mean what we could do is test UTF-8, ASCII, Unicode (in this order) until we were able to parse something when on windows... WDYT ?

**Comment by ramtech123** [comment]
@ejona86 , I also could not find any standards around hosts file encoding. The comment here https://serverfault.com/questions/926706/is-there-any-ietf-rfc-standard-defined-for-hosts-file-encoding indicates it never had a formal standard.

@normanmaurer just curious about "...until we were able to parse something when on windows" - don't we expect this situation in non-Windows machine?

**Comment by normanmaurer** [comment]
@ramtech123 I never heard of using something linux unicode for `/etc/hosts`.

**Comment by ramtech123** [comment]
ok

**Comment by ejona86** [comment]
@normanmaurer, that sounds like it would work. Note that ASCII doesn't get you anything over UTF-8. Although Latin-1 or similar would, which may be the system's default encoding (dunno). And to be precise, "Unicode" would be "UTF-16" (probably UTF-16LE).

Linux has been using UTF-8 for a really, really long time now. I did dig through glibc a very quick amount and it looks like it just used the system encoding in normal C-style ("does this char* look like this char*?").

In both cases, using _actual_ unicode codepoints may not be at issue (at which point UTF-8 vs some-random-codepage are the same). It sounds like @ramtech123 mainly suffered issue because the file was encoded with UTF-16.

**Comment by normanmaurer** [comment]
@ejona86 PTAL https://github.com/netty/netty/pull/8211 again
