### ISSUE TITLE
SUBACK fixed header, 1st byte 

### ISSUE THREAD

**Issue by matfil** [netty/netty#8213]
### Expected behavior
fixed header should be 0x90
### Actual behavior
it is 0x92
### Steps to reproduce
connect, subscribe to any topic 
### Netty version
4.1
### JVM version (e.g. `java -version`)
1.7
### OS version (e.g. `uname -a`)
ubuntu 18.04 bionic beaver LTS

**Comment by normanmaurer** [comment]
@matfil would you be interested in providing a PR ?

**Comment by amizurov** [comment]
@matfil Can you please provide more information for example which broker you are used ?  I checked test and it's look properly with SUBACK(9).

**Comment by normanmaurer** [comment]
Closing as no follow up provided
