### ISSUE TITLE
Obsolete attribute

### ISSUE THREAD

**Issue by christ258** [netty/netty#8214]
hi, I find this:

/**
     * @deprecated Use {@link MaxMessagesRecvByteBufAllocator}
     */
    @Deprecated
    public static final ChannelOption<Integer> MAX_MESSAGES_PER_READ = valueOf("MAX_MESSAGES_PER_READ");

I used to use this ‘MAX_MESSAGES_PER_READ’, Now use this 'MaxMessagesRecvByteBufAllocator', how can I use this?

**Comment by normanmaurer** [comment]
Use `MaxMessagesRecvByteBufAllocator#maxMessagesPerRead`
