### ISSUE TITLE
HTTP 1.1 Header working in all browsers throws an error

### ISSUE THREAD

**Issue by frutak** [netty/netty#8216]
Hi,

I am issues parsing an HTTP response from my IP cam - the header that is parsed correctly by ie, firefox and chrome is throwing an error in netty.

The header:
```
HTTP/1.1 200 OK
Server: GoaHead
Tue, 12 Jun 2012 01:56:34 GMT
Content-Type:image/jpeg
Content-Length:21003
Connection: close
```

I assume the issue is the date coming without "Date:" tag, but somehow the response works in all browsers I tested it in. 
1. Are you able to confirm it is the date that is causing the issue?
2.Is there any chance the modification that would make the syntax parsable would be included in the future releases?

thanks in advance,
Szymon

**Comment by normanmaurer** [comment]
yeah I think its the date but I would need to test it.. I dont think we would support this tho as it completely wrong in terms of the RFC
