### ISSUE TITLE
Why convert set to array in FastThreadLocal#removeAll()？

### ISSUE THREAD

**Issue by zhaojigang** [netty/netty#8223]
hi，I have a doubt why we need convert set to array in FastThreadLocal#removeAll()
![image](https://user-images.githubusercontent.com/14085645/44587724-61cde400-a7e6-11e8-82fb-3feff5b31821.png)

**Comment by normanmaurer** [comment]
Actually I dont think we need... @trustin any recollection why you added this ? 

That said this will not be called very frequently so I am not really concerned about the extra copy.

**Comment by zhaojigang** [comment]
hi, @normanmaurer I know why we need! because if we use set, for-remove will occurs java.util.ConcurrentModificationException, but array will not!
I closed this issue.
