### ISSUE TITLE
FixedChannelPool.close deadlock

### ISSUE THREAD

**Issue by mihalyr** [netty/netty#8238]
This bug was discovered during testing Netty as both server and client sharing the same worker EventLoopGroup. The Netty client used AbstractChannelPoolMap with FixedChannelPool with persistent HTTP/1.1 connections.

During the test we saw an increasing number of not closed sockets for connections closed by the remote side. We discovered that the Netty client was blocking I/O threads that kept receiving new server connections, but haven't had chance to react on the remote close and to close the sockets.

The problem was traced back to a commit made for 4.1.26 Final https://github.com/netty/netty/commit/583fc272f26373ff5f51c0871d9730370cd39a3e that changed FixedChannelPool.close to a blocking call. The close operation is also called from AbstractChannelPoolMap.get when a new pool is not needed and being closed. Since we shared EventLoops between server and client, ChannelPoolMap.get was triggered from an I/O thread based on a request accepted by the server side and entered the blockin close, which was waiting for another I/O thread to complete the close, however the other thread was doing the same and multiple threads ended up in a deadlock situation.

An example scenario:

1.
Thread A1 calls ChannelPoolMap.get(A)
Thread A2 calls ChannelPoolMap.get(A)
Thread B1 calls ChannelPoolMap.get(B)
Thread B2 calls ChannelPoolMap.get(B)

2.
Thread A1 gets a new pool on eventexecutor thread X1 (anywhere but A2 or B2)
Thread B1 gets a new pool on eventexecutor thread X2 (anywhere but A2 or B2)
Thread A2 gets a new pool on eventexecutor thread B2
Thread B2 gets a new pool on eventexecutor thread A2

3.
Thread A1 succeeds on updating the map and moves on
Thread B1 succeeds on updating the map and moves on
Thread A2 fails to update the map and submits blocking close to thread B2
Thread B2 fails to update the map and submits blocking close to thread A2

At this point Threads A2 and B2 are in a deadlock situation

### Expected behavior

FixedChannelPool.close does not enter a blocking wait for other thread.

### Actual behavior

FixedChannelPool.close enters a blocking wait for an other thread which might be entering a wait for this thread and end up deadlocking each other.

### Steps to reproduce

Please see the reproducer code.

### Minimal yet complete reproducer code (or URL to code)

I have added barriers to ensure both eventloops are executing the tasks before executing the close, but I could quite reliably reproduce even without the barrier. Running both close operations on the same pool or each on their own works as expected, the problem is only when they get executed on the other pool's loop.

```java
import io.netty.bootstrap.Bootstrap;
import io.netty.channel.Channel;
import io.netty.channel.DefaultEventLoop;
import io.netty.channel.EventLoop;
import io.netty.channel.local.LocalAddress;
import io.netty.channel.local.LocalChannel;
import io.netty.channel.pool.AbstractChannelPoolHandler;
import io.netty.channel.pool.ChannelPool;
import io.netty.channel.pool.ChannelPoolHandler;
import io.netty.channel.pool.FixedChannelPool;
import io.netty.util.concurrent.Future;
import org.junit.Test;

import java.util.concurrent.CyclicBarrier;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

public class FixedChannelPoolDeadlockTest {

    @Test
    public void testFixedChannelDeadlock() throws Exception {
        EventLoop eventloop1 = new DefaultEventLoop();
        Bootstrap bootstrap1 = new Bootstrap()
                .channel(LocalChannel.class)
                .group(eventloop1)
                .localAddress(new LocalAddress("#1"));

        EventLoop eventloop2 = new DefaultEventLoop();
        Bootstrap bootstrap2 = new Bootstrap()
                .channel(LocalChannel.class)
                .group(eventloop2)
                .localAddress(new LocalAddress("#2"));

        ChannelPoolHandler handler = new AbstractChannelPoolHandler() {
            public void channelCreated(Channel ch) throws Exception {}
        };

        // assign eventloop1 to pool1 and eventloop2 to pool2
        final ChannelPool pool1 = new FixedChannelPool(bootstrap1, handler, 1);
        final ChannelPool pool2 = new FixedChannelPool(bootstrap2, handler, 1);

        // make sure both tasks are entered
        CyclicBarrier barrier = new CyclicBarrier(2);

        // execute pool1.close from eventloop2 and pool2.close from eventloop1
        Future<?> closeFuture1 = eventloop2.submit(() -> closePool(barrier, pool1));
        Future<?> closeFuture2 = eventloop1.submit(() -> closePool(barrier, pool2));

        try {
            // The expected scenario is that both pools close,
            // but instead they block each other and the below times out
            closeFuture1.get(1, TimeUnit.SECONDS);
            closeFuture2.get(1, TimeUnit.SECONDS);
        } catch (TimeoutException e) {
            // Fail the test on timeout to distinguish from other errors
            throw new AssertionError(e);
        } finally {
            eventloop1.shutdownGracefully(0, 0, TimeUnit.SECONDS);
            eventloop2.shutdownGracefully(0, 0, TimeUnit.SECONDS);
        }
    }

    private void closePool(CyclicBarrier barrier, ChannelPool pool) {
        try {
            barrier.await(100, TimeUnit.MILLISECONDS);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        pool.close();
    }

}
```

### Netty version

4.1.26 Final
4.1.27 Final
4.1.28 Final
4.1.29 Final

### JVM version (e.g. `java -version`)

openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

### OS version (e.g. `uname -a`)

Linux 3.2.50

**Comment by normanmaurer** [comment]
@mihalyr I will try to have a look soon.

**Comment by normanmaurer** [comment]
@mihalyr btw if you have a good idea how to fix this I would be more then happy to review.

**Comment by mihalyr** [comment]
@normanmaurer Hi Norman, thank you for looking into. I was testing with simply making the close async and adding a closeFuture similar to what you do in Channel, so we can wait for the completion on shutdown etc, the future could be also returned from close. However, that would break customers already relying on the sync behaviour. An alternative to preserve compatibility could be a new closeAsnyc call, that could be used in places like ChannelPoolMap, but not sure that is in line with the style used in project.

If you could share your preference or ideas about this, I will try to look into it and get permission for a fix.

**Comment by efimovandr** [comment]
Got similar problem. Commented on commit which causes the issue: https://github.com/netty/netty/commit/583fc272f26373ff5f51c0871d9730370cd39a3e#commitcomment-32343726

**Comment by normanmaurer** [comment]
@mihalyr I think adding a new method (as long as its on a class and not interface) sounds good.

**Comment by mihalyr** [comment]
Hi @normanmaurer, sorry for being late with this, too many things come up. I see that @divijvaidya added already a `closeAsync` function to `FixedChannelPool` (#9226), that's half of what I wanted to do. 

I've put together something right now that fixes this issue by moving `closeAsync` to the `ChannelPool` interface and then using the async calls in `AbstractChannelPoolMap`.
