### ISSUE TITLE
SelectedSelectionKeySet.java throw UnsupportedOperationException

### ISSUE THREAD

**Issue by monkey1993** [netty/netty#8242]
### Expected behavior
When I use reflection to get a obejct that contains all fields, and then, I input it's info when I iterate it . But,I find an error that is UnsupportedOperationException

### Minimal yet complete reproducer code (or URL to code)
class SelectedSelectionKeySet.java
at line 62

### Netty version
4.1.27
### JVM version (e.g. `java -version`)
8u172
### OS version (e.g. `uname -a`)
win7

**Comment by normanmaurer** [comment]
@monkey1993 please share the code that you used.

**Comment by monkey1993** [comment]
No code. Just see SelectedSelectionKeySet.java at line 62

**Comment by normanmaurer** [comment]
@monkey1993 sure but why you even access this `SelectedSelectionKeySet` ? I mean its internal and we not expose it at all.

**Comment by monkey1993** [comment]
Reflection to get a object that contains all fields.Analyze memory footprin.

**Comment by monkey1993** [comment]
Calculate each ChannelHandlerContext to occupy memory.

**Comment by normanmaurer** [comment]
@monkey1993 I still dont get why you need this... just take an heap-dump and use a heap-dump analyser. I mean I can implement `iterator` but I am really not sure why you try to hand-roll this stuff.

**Comment by monkey1993** [comment]
Calculate objects and their subobjects to occupy memory.

**Comment by normanmaurer** [comment]
yeah and this is exactly what a heap-dump will give you and can be accessed via a heap-dump analyser like eclipse mat.

**Comment by monkey1993** [comment]
it's will be---> _make(8) + long(8) + int(4) + boolean(1) + boolean(1) + padding(2) + ref(4) + padding(4) = 32byte. But no ChannelHandlerContext object is calculated.

**Comment by normanmaurer** [comment]
@monkey1993 while I still not understand why you bother handrolling a memory profiler I did the changes as it was trivial to fix:

https://github.com/netty/netty/pull/8244

PTAL

**Comment by monkey1993** [comment]
I need to estimate the memory footprint of each object to make sure how many people my system can hold, and how it can expand when it expands.

**Comment by monkey1993** [comment]
As you said, that's trivial, and I can still circumvent it to figure out how much memory an object occupies.
