### ISSUE TITLE
sctp not running in some version linux

### ISSUE THREAD

**Issue by khanhlv93** [netty/netty#8243]
sctp echo sample not runing in ubuntu 16.04lts, 18.04 lts but work well in centos 7 or ubuntu 17.10. because Server send ABORT chunk as response on INIT .but  command sctp_darn is working normal.  Can someone please help me [`file pcap`](https://drive.google.com/file/d/17ALBWsVT_gZBjrU4kTyNsUgJmx3AACdr/view)

**Comment by normanmaurer** [comment]
@khanhlv93 we just use what the JDK includes so I think you will need to fill an openjdk bug.

**Comment by khanhlv93** [comment]
i tried both oracle jdk7 and orack jdk8 but it same result "abort init" .

**Comment by normanmaurer** [comment]
@khanhlv93 again I think you need to open an issue for openjdk with a reproducer.
