### ISSUE TITLE
OOME in SslHandlerCoalescingBufferQueue

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#8265]
I just had an instance of our Netty app OOME. It seems the SslHandlerCoalescingBufferQueue of one connection filled up with `<EmptyByteBuf, ChannelPromise>` pairs.

### Netty version

4.1.29 w/ TCN 2.0.15 (OpenSSL 1.1.0i, linux, static)

### OS version (e.g. `uname -a`)

![screenshot from 2018-09-05 10-51-42](https://user-images.githubusercontent.com/191635/45102017-bcc2dd80-b0fa-11e8-9f5d-1536c701a619.png)

![screenshot from 2018-09-05 10-52-07](https://user-images.githubusercontent.com/191635/45102031-c4828200-b0fa-11e8-9dca-9e55820476e5.png)

![screenshot from 2018-09-05 10-52-57](https://user-images.githubusercontent.com/191635/45102047-ca786300-b0fa-11e8-8291-87bfe6c214a1.png)

![screenshot from 2018-09-05 10-55-30](https://user-images.githubusercontent.com/191635/45102077-d82de880-b0fa-11e8-9777-53dcefca4812.png)

**Comment by normanmaurer** [comment]
Can you share the heap dump ?

**Comment by rkapsi** [comment]
Unfortunately no due to private keys being in there and such. But I'll poke around and share screenshots/values if you have ideas what to look at in particular.

The connection appears to be HTTP/2. This seems very similar to #7659.

**Comment by rkapsi** [comment]
Possibly same cause (me) :thinking:

**Comment by rkapsi** [comment]
Closing for now, probably exactly the same as #7659.
