### ISSUE TITLE
Feature request: Exposing Number of Channels per Eventloop

### ISSUE THREAD

**Issue by Wingfril** [netty/netty#8276]
Netty doesn't expose the number of channels per event loop for Kqueue|Epoll|Nio. It might be helpful for monitoring performances to expose this. 
Could also be useful for a better way of assigning channels to event loops as well. (My results on this were inconclusive, but the simulations I wrote might not be good).

**Comment by vkostyukov** [comment]
Perhaps [`EventLoopGroup.registeredChannels`](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/EventLoopGroup.java) could be a good API to expose?

**Comment by vkostyukov** [comment]
@normanmaurer How do you feel about exposing this API (see above)? I might have time to contribute this little improvement if you find that useful.

**Comment by normanmaurer** [comment]
@vkostyukov yeah I think it is a good one... That said we will need to implement it without breaking other impls so it will need to go into an implementation of EventLoopGroup I guess.

**Comment by vkostyukov** [comment]
Sounds good! Let me give a try.

**Comment by normanmaurer** [comment]
@vkostyukov any update ?

**Comment by vkostyukov** [comment]
@normanmaurer Yes - I was looking into where to expose this and the best I can come up with is concrete implementations of event-loops, `NioEventLoop`, `EpollEventLoop`. 

I wish we could put this under `SingleThreadEventLoop` (by analogy with `pendingTasks`) but we don't really have access to the underlying channel-map from there. My vote would probably be start with `Nio|Epoll` classes and see how it goes. Does it sound reasonable?

**Comment by normanmaurer** [comment]
@vkostyukov the problem here is that `EpollEventLoop` is not public but I guess we could change this.
