### ISSUE TITLE
Native epoll channels/sockets take longer to shutdown/close?

### ISSUE THREAD

**Issue by vkostyukov** [netty/netty#8278]
This is neither a bug report nor feature request. I figured I use Github issues to solicit peoples experience and knowledge about Netty's native epoll transports. We've been running Finagle with native epoll (on Linux) for quite a while internally and finally decided to switch our OSS version to it.

To our surprise, switching over to a native epoll caused out showdown tests to fail. Turns out, our previous graceful timeout (order of a couple of seconds) didn't do it for native epoll socket/channel (shutting down an HTTP server running with epoll=true). We had to bump our timeouts significantly to ensure the test passes: think of going from 2s to 30s.

Before we start digging into why closing epoll channels (server channels if that matters) takes so much longer I decided to ask around if somebody has seen this before. Any pointers would be totally appreciated!

I will try to post with thread with the updates should we know more.

**Comment by normanmaurer** [comment]
I am not aware of anything like this @vkostyukov

**Comment by normanmaurer** [comment]
@vkostyukov did you find out anything ?

**Comment by vkostyukov** [comment]
@normanmaurer Nope - we haven't really made any progress there yet. We've only seen this problem in our tests and were keeping an eye on complains coming from out users. Nobody really complained about slower shutdown yet thus we haven't really invested into it.

**Comment by normanmaurer** [comment]
k ok :)

**Comment by njhill** [comment]
@vkostyukov would be interesting to know if #9616 resolves this (assuming it still happens for you).

**Comment by normanmaurer** [comment]
I think this should be fixed by #9616 . Closing.
