### ISSUE TITLE
aarch64 native bits.

### ISSUE THREAD

**Issue by rhenwood-arm** [netty/netty#8279]
Hi,

It is valuable for me to have native aarch64 bits included in the release artifacts. I see there has been interest in a cross-compile previously: https://github.com/netty/netty/issues/7459 

It appears that the release is made on a RHEL 6 x86_64 compatible and I would like to explore making the necessary changes to the project to add in a cross-compile step for aarch64.

Assuming this is accurate, is the project open to a pull request to generate aarch64 bits during the release cycle?

best regards,
Richard

**Comment by normanmaurer** [comment]
@rhenwood-arm if we can easily cross-compile there we could do it I guess.

**Comment by normanmaurer** [comment]
@rhenwood-arm btw if you do so you may also be interested in providing a pr for netty-tcnative.

**Comment by rhenwood-arm** [comment]
Thanks for the prompt response and guidance @normanmaurer !

I'll spend some time looking into this in detail.

**Comment by normanmaurer** [comment]
@rhenwood-arm any update ?

**Comment by normanmaurer** [comment]
@rhenwood-arm ping

**Comment by rhenwood-arm** [comment]
Hi @normanmaurer 
I am working with a colleague on this activity, so I've reached out to them to see where they are. Still waiting for an update.

NOTE: I am assuming that this is a 'nice to have' for the project today. Please let me know if you have observed other interest in this work which will help me prioritize it.

**Comment by fugui** [comment]
We are using netty on ARM64v8.   and waiting this very important feature.

**Comment by aygalinc** [comment]
Hi @rhenwood-arm do you have start some work around this topic ? I'm also interested to provide cross compilation for arm v7 32 bit architecture.

**Comment by rhenwood-arm** [comment]
Hi,

I don't have time to work on this currently, but I will ask to see if I can get some help...

**Comment by rhenwood-arm** [comment]
It looks like the EPEL 6 repository would need to be added to the release requirement to at least provide the GCC cross compilers for AArch64 and Armv7.

@normanmaurer would you be amenable to that?

**Comment by normanmaurer** [comment]
@rhenwood-arm sounds fair :)

**Comment by normanmaurer** [comment]
@rhenwood-arm ping..

**Comment by rhenwood-arm** [comment]
Thanks for the reminder @normanmaurer . I think the plan to move forward is:

1. Add EPEL as a release dependency to this project. This will provide the cross compiler.
2.

**Comment by wangxiyuan** [comment]
We have the same requirement about netty on aarch64 as well. Any progress? Anything I can do to help with the ARM release?

**Comment by wangxiyuan** [comment]
@rhenwood-arm @normanmaurer Can I take over this issue? I'd like to do the work that @rhenwood-arm pointed.

**Comment by normanmaurer** [comment]
Sure 🙏

**Comment by rhenwood-arm** [comment]
@wangxiyuan : please do! :)

**Comment by wangxiyuan** [comment]
I tested locally with java_1.8.0_222 and maven 3.6.0 on an ARM machine. The build and tests for 4.1.44 are passed at all. I'll test cross-compile next. I'll create the PR for it if everything works well.

**Comment by wangxiyuan** [comment]
@rhenwood-arm @normanmaurer I tested cross compile locally. The official yum package for `gcc-aarch64-linux-gnu` doesn't work. It missed lots of files. I used linaro ones instead. The minimum version is 4.9: https://releases.linaro.org/components/toolchain/binaries/4.9-2016.02/aarch64-linux-gnu/ and it relies on glibc 2.14 which CentOS 6.9 doesn't support by default. So I bumped glibc from `2.13` to `2.14` by hand. Then with the linaro gcc, the cross compile passed. 

As you can see, since the tools on CentOS 6 is a little old by default, we can't cross compile by default. How do you think about the step? Is it acceptable?

**Comment by normanmaurer** [comment]
@wangxiyuan unfortunately bumping up GLIBC is not an option imho. So what we could do is to only support it on centos7 and newer for arm.

**Comment by wangxiyuan** [comment]
@normanmaurer Using CentOS 7 is a better way of cause.

I'm not sure how `transport-native-epoll` jar is released to Maven Repo. But I find that it relies on CentOS 6.9 if I'm correct. https://github.com/netty/netty/blob/4.1/transport-native-epoll/pom.xml#L96
Is it possible to bump to 7?

**Comment by normanmaurer** [comment]
Nope it is not possible to require centos7 in general. I wonder if we can just build on both and release

**Comment by wangxiyuan** [comment]
@normanmaurer make sense. Let me try 7 now.

BTW, I'm not sure how to support both 6 and 7 in netty. Will there be two jar, one for 6 and another for 7?

**Comment by normanmaurer** [comment]
@wangxiyuan there would be one jar for arm and one for x86 I guess . And the one for arm would be centos7 ?

**Comment by rhenwood-arm** [comment]
The glibc version seems to be the critical factor in providing architecture support. I suggest separate multiple releases of the same code-base are distinguished with that in-mind. One obvious approach is to include the glibc version in the release name. So far, I personally think will be the simplest way to avoid confusion and gives a good path to future-proofing new architectures.

I can also see labeling with centos6, centos7 etc (or el6, el7, el8) would be an OK alternative for me personally... but I do recognize there are other distributions out there that people might choose to run :)

**Comment by wangxiyuan** [comment]
@rhenwood-arm @normanmaurer I just added a new profile `linux-aarch64` for `transport-native-epoll` and its dependents `transport-native-unix-common` to build the aarch64 packge. Here is the step to cross compile:
1. Make sure the OS is CentOS 7.6 (which contains glibc>=2.14  by default )
2. Download aarch64-gcc toolchin  https://releases.linaro.org/components/toolchain/binaries/4.9-2016.02/aarch64-linux-gnu/gcc-linaro-4.9-2016.02-x86_64_aarch64-linux-gnu.tar.xz
3. Unpack it and add its `bin` folder into the user's default PATH( `maven-hawtjni-plugin` will use the default PATH to find aarch64-gcc, `export` doesn't work.)
4. go into `transport-native-unix-common`, try `mvn clean install -Plinux-aarch64`.
5. go into `transport-native-epoll`, try `mvn clean install -Plinux-aarch64`.

Is that OK?

And I don't know how netty releases jar to maven center. Should I add some release change to parent pom.xml?

**Comment by normanmaurer** [comment]
@wangxiyuan left a comment on the PR. I think we should add a docker file for this and then we can make it happen as part of the release process.

**Comment by wangxiyuan** [comment]
sure, Let me add one. Thanks for your quick response.

**Comment by geoffreyblake** [comment]
Any progress on this?  This seems to build fine on an AWS a1 machine running RHEL8.  Getting the binaries for aarch64 released would be helpful for people wanting to run Hadoop/Spark etc on Arm machines.
