### ISSUE TITLE
class not found

### ISSUE THREAD

**Issue by x7LoveLin** [netty/netty#8284]
### Expected behavior
found class
### Actual behavior
not found
### Netty version
lastest

### JVM version (e.g. `java -version`)

1.8

### OS version (e.g. `uname -a`)

![image](https://user-images.githubusercontent.com/11347393/45464809-d8566580-b744-11e8-842a-c1096ef50de3.png)

**Comment by johnou** [comment]
@x7LoveLin run `mvn clean compile`, the classes are auto-generated.
