### ISSUE TITLE
WebSocket is closed without an error on protocol violations

### ISSUE THREAD

**Issue by ursaj** [netty/netty#8295]
When client sends a message exceeding server restrictions, web socket should be closed with correct error code and message.

### Expected behavior
response frame is sent: CloseWebSocketFrame(1002, "Max frame length of ... has been exceeded")

### Actual behavior
response frame is sent: CloseWebSocketFrame(1000, null)

### Steps to reproduce
Limit single message size accepted by server.
```
static int MAX_CLIENT_MESSAGE_SIZE = 128 * 1024;

ctx.pipeline().addAfter(ctx.name(), "ws-protocol-handler", new WebSocketServerProtocolHandler(
    webSocketPath, null, true, MAX_CLIENT_MESSAGE_SIZE, false, false));`
```

Send message from client with a greater size:
```
ByteBuf buf = Unpooled.wrappedBuffer(new byte[MAX_CLIENT_MESSAGE_SIZE + 1]);
clientChannel.writeAndFlush(new BinaryWebSocketFrame(buf));
```

### Minimal yet complete reproducer code (or URL to code)
n/a

### Netty version
4.1.29.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b25, mixed mode)

### OS version (e.g. `uname -a`)
Linux gmafxu42 3.0.101-108.35-default #1 SMP Mon Feb 19 21:13:08 UTC 2018 (251ec24) x86_64 x86_64 x86_64 GNU/Linux

### Root cause

io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder#protocolViolation(io.netty.channel.ChannelHandlerContext, io.netty.handler.codec.CorruptedFrameException)

```
private void protocolViolation(ChannelHandlerContext ctx, CorruptedFrameException ex) {
    state = State.CORRUPT;
    --- if (ctx.channel().isActive()) {
    +++ if (ctx.channel().isActive() && closeOnProtocolViolation) {
        Object closeMessage;
        if (receivedClosingHandshake) {
            closeMessage = Unpooled.EMPTY_BUFFER;
        } else {
            --- closeMessage = new CloseWebSocketFrame(1002, null);
            +++ closeMessage = new CloseWebSocketFrame(1002, ex.getMessage());
        }
        --- ctx.writeAndFlush(closeMessage).addListener(ChannelFutureListener.CLOSE);
        +++ ctx.channel().writeAndFlush(closeMessage).addListener(ChannelFutureListener.CLOSE);
    }
    throw ex;
}
```

**Comment by normanmaurer** [comment]
@ursaj would you be interested in providing a PR and include a test case there ?

**Comment by amizurov** [comment]
@ursaj @normanmaurer Guys, be careful, the specification has a specific code (1009) indicates that an endpoint is terminating the connection  because it has received a message that is too big for it to
process. https://tools.ietf.org/html/rfc6455#section-7.4.1
