### ISSUE TITLE
Infinite loop in JdkZlibEncoder.deflate()

### ISSUE THREAD

**Issue by swrdlgc** [netty/netty#8299]
<pre>
private void deflate(ByteBuf out) {
    int numBytes;
    do {
        int writerIndex = out.writerIndex();
        numBytes = deflater.deflate(
                out.array(), out.arrayOffset() + writerIndex, out.writableBytes(), Deflater.SYNC_FLUSH);
        out.writerIndex(writerIndex + numBytes);
    } while (numBytes > 0);
}
</pre>
if out.writableBytes() is ZERO and numBytes>0, the function will never return!

**Comment by normanmaurer** [comment]
Are you interested in providing a PR?

**Comment by normanmaurer** [comment]
@swrdlgc

**Comment by normanmaurer** [comment]
@swrdlgc actually this can never happen as `deflate(...)` will return the number of bytes written to the output buffer which will be 0 if it was not writable.

**Comment by normanmaurer** [comment]
The good thing is because of this bug report I think I spotted a bug which is unrelated to the reported problem tho ;)

**Comment by swrdlgc** [comment]
thanks for replay, you are right, this can never happen.
