### ISSUE TITLE
Mqtt v5 support

### ISSUE THREAD

**Issue by enricosecondulfo** [netty/netty#8303]
Hello guys, 
thanks for the great work. I'd like to know, if it's possible,  if and when support for version 5 of mqtt will be introduced.

Thanks

**Comment by slandelle** [comment]
Dup of #6285.
I'm afraid Netty core committers team lacks an MQTT expert for reviewing #7342.

**Comment by enricosecondulfo** [comment]
Thank you very much for the quick reply

**Comment by slandelle** [comment]
That's just my personal opinion here, I'm not a committer.

**Comment by andsel** [comment]
Hi guys, I'm the promoter of that PR, it's still there for one year and half :-( probably it has to be updated to the MQTTv5 is GA and Moqsuitto and Paho are updated to it (or is updating to it)

**Comment by normanmaurer** [comment]
The code was moved to https://github.com/moquette-io/netty-mqtt5-codec

**Comment by chenzhiguo** [comment]
MQTT V5 has support by this PR: #10483
