### ISSUE TITLE
Netty Epoll Bug occurs again (WorkAround Not working)

### ISSUE THREAD

**Issue by prakash-premkumar** [netty/netty#8306]
I'm using Netty 4.1.29.Final.
Java Version  1.8.0_181-b13
Amazon AMI Linux 4.9.119-44.140.amzn1.x86_64 (2017.09)

I' using lafaspot imapnio client which uses netty. [(https://github.com/lafaspot/imapnio)]
I'm running my Java App in Tomcat 8.5.29.

I get the following exception while shutting down the tomcat server.
The NIO threads are not being killed, causing a memory leak.

> 20-Sep-2018 13:07:36.516 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [IMAPNIO-THREAD-POOL-CUSTOM-1-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
 sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
 sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
 sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
 sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
 io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
 io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:737)
 io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:392)
 io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
 io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 java.lang.Thread.run(Thread.java:748)

> 20-Sep-2018 13:07:36.517 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [IMAPNIO-THREAD-POOL-CUSTOM-3-1] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
>  sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
>  sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
>  sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
>  sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
>  sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
>  io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
>  io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:737)
>  io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:392)
>  io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
>  io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>  java.lang.Thread.run(Thread.java:748)
> 
> 

This is the code I'm using to create and shutdown threads:

`public class IMAPClient {

    /** instance id used for debug. */
    private final String instanceId = Integer.toString(new Random(System.nanoTime()).nextInt());

    /** counter for session. */
    private AtomicInteger sessionCounter = new AtomicInteger(1);

    /** The netty bootstrap. */
    private final Bootstrap bootstrap;

    /** Event loop group that will serve all channels for IMAP client. */
    private final EventLoopGroup group;

    /**
     * Constructs a NIO based IMAP client.
     *
     * @param threads number of threads to be used by IMAP client
     */
    public IMAPClient(final int threads) {
        this.bootstrap = new Bootstrap();
        this.group = new NioEventLoopGroup(threads, new DefaultThreadFactory("IMAPNIO-THREAD-POOL-CUSTOM"));
        bootstrap.channel(NioSocketChannel.class);
        bootstrap.group(group);
    }

    /**
     * Close all of the sessions within a client, and shutdown the event group.
     */
    public void shutdown() {
		Future<?> future = this.group.shutdownGracefully();
		try {
			
			if(future != null) {
				future.await();
			}
			boolean isTerminated = this.group.awaitTermination(300, TimeUnit.SECONDS);
			
		} catch (InterruptedException e) {
			
		}
       }
 }`

> I tried the workaround mentioned here  https://netty.io/news/2012/09/13/4-0-0-alpha4.html
> 
> I added the -Dio.netty.epollBugWorkaround=true to JAVA_OPTS. But still I get this error.

Can you please tell me how to fix this error ?

**Comment by normanmaurer** [comment]
That’s strange... can you share a reproducer with me that I can run ?

**Comment by prakash-premkumar** [comment]
May I know what you mean by reproducer ? It's actually a web app where netty runs inside tomcat. 
Which snippet of the code do you want to see ?

**Comment by normanmaurer** [comment]
I want you to create a small app that reproduces it that I can run myself

**Comment by prakash-premkumar** [comment]
Okay. I will write it up and post it here !

**Comment by prakash-premkumar** [comment]
@normanmaurer  , Unfortunately, I will not be able to share the reproducer with you, since it invloves some proprietary code.

Tomcat is being shutdown although, it complains of failure to stop threads. Will there by any memory leak in this case ?

Is there a way to fix this problem ?

**Comment by normanmaurer** [comment]
@prakash-premkumar sorry without a way to reproduce here I can not really help. For me it looks like you not correctly shutdown all the `EventLoopGroup`s.

**Comment by johnou** [comment]
`-Dio.netty.epollBugWorkaround=true` also has nothing to do with the stacktrace you pasted. How are you invoking `shutdown()`?

**Comment by prakash-premkumar** [comment]
@johnou, Thanks a lot for your reply.

I'm invoking shutdown in the contextDestroyed() of tomcat (which will be called when tomcat shuts down)

This is the shutdown method of the IMAPClient.


```
public void shutdown() {
		try {
			Future<?> future = this.group.shutdownGracefully().sync();
			if(future != null) {
				future.await();
			}
			boolean isTerminated = this.group.awaitTermination(60, TimeUnit.SECONDS);	
		} catch (InterruptedException e) {
			
		}
}
```


This is how I initialize the EventLoopGroup


 ```
public IMAPClient(final int threads) {
        this.bootstrap = new Bootstrap();
        this.group = new NioEventLoopGroup(threads, new DefaultThreadFactory("IMAPNIO-THREAD- 
         POOL-CUSTOM"));
        bootstrap.channel(NioSocketChannel.class);
        bootstrap.group(group);
    }
```

**Comment by johnou** [comment]
Are you sure that you are tracking all IMAPClient instances and invoking shutdown on all of them in contextDestroyed()?

**Comment by johnou** [comment]
It's important to note that if you are terminating the JVM there won't be a memory leak. The message you are seeing is only a problem if you are redeploying webapps without shutting down Tomcat.

**Comment by normanmaurer** [comment]
Sorry but without a reproducer I can run I will not be able to help any further. As explained before I think you miss to call shutdown in some cases. Please re-open with more details if you still think there is a bug. 

And yes if you restart tomcat there will be no leak
