### ISSUE TITLE
Netty create temp file and add deleteOnExitHook hit memory leak

### ISSUE THREAD

**Issue by houbic** [netty/netty#8310]

**Comment by houbic** [comment]
I use netty to develop an HTTP server, netty will create temp file if request body over setting size when decode.But netty will create temp file  add path to DeleteOnExitHook, it will hit memory leak.

Netty code:

/**
     * @return a new Temp File from getDiskFilename(), default prefix, postfix and baseDirectory
     */
    private File tempFile() throws IOException {
        String newpostfix;
        String diskFilename = getDiskFilename();
        if (diskFilename != null) {
            newpostfix = '_' + diskFilename;
        } else {
            newpostfix = getPostfix();
        }
        File tmpFile;
        if (getBaseDirectory() == null) {
            // create a temporary file
            tmpFile = File.createTempFile(getPrefix(), newpostfix);
        } else {
            tmpFile = File.createTempFile(getPrefix(), newpostfix, new File(
                    getBaseDirectory()));
        }
        if (deleteOnExit()) {
            tmpFile.deleteOnExit();
        }
        return tmpFile;
    }

**Comment by normanmaurer** [comment]
@houbic which class is this from ?

**Comment by houbic** [comment]
> @houbic which class is this from ?

https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/multipart/AbstractDiskHttpData.java

This class, could you review it please?Thanks!

**Comment by normanmaurer** [comment]
@houbic when you say "hit memory leak" you mean you run out of memory because it adds the hooks ?

**Comment by johnou** [comment]
@houbic you might consider setting deleteOnExit to false, then running your own cleanup strategy on the configured tmp directory.

**Comment by houbic** [comment]
> @houbic when you say "hit memory leak" you mean you run out of memory because it adds the hooks ?

Yes, because it adds the hooks always but not release if my program doesn't quit

**Comment by houbic** [comment]
> @houbic you might consider setting deleteOnExit to false, then running your own cleanup strategy on the configured tmp directory.

@johnou Any setting in netty for this please? Use DiskAttribute.deleteOnExitTemporaryFile = false when my program to run?

**Comment by normanmaurer** [comment]
@houbic yes... 

Closing the issue as there is a way to control it.
