### ISSUE TITLE
Netty's HTTP Decoder doesn't seem to allow CRLF in the HTTP Request line.

### ISSUE THREAD

**Issue by sudheerv** [netty/netty#8312]
### Expected behavior

Per RFC 7230 (https://tools.ietf.org/html/rfc7230#section-3.1.1) CRLF (\r\n) included in the Request Line should be honored.

request-line   = method SP request-target SP HTTP-version CRLF

For e.g.

GET / HTTP/1.1 \r\n

### Actual behavior

It seems like Netty's HTTP decoder is throwing an IllegalArgumentException (invalid HTTP version) when CRLF is included. 

### Steps to reproduce

%telnet 127.0.0.1 7001
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET / HTTP/1.1 \r\n
Connection closed by foreign host.

### Netty version

4.1.27.Final

### JVM version (e.g. `java -version`)

1.8.0_121

### OS version (e.g. `uname -a`)
Mac OS X

### Additional Context
I work at Netflix on Zuul and we are currently running Netty 4.1.27.

**Comment by sudheerv** [comment]
https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectDecoder.java#L212

*splitInitialLine* doesn't seem to exclude CRLF in parsing the request line. 

Wondering if there's a reason for not honoring CRLF or am I mis interpreting something.

**Comment by sudheerv** [comment]
Additional Reference:

https://httpwg.org/specs/rfc7230.html#rfc.section.3.5

In the interest of robustness, a server that is expecting to receive and parse a request-line SHOULD ignore at least one empty line (CRLF) received prior to the request-line.

_Although the line terminator for the start-line and header fields is the sequence CRLF, a recipient MAY recognize a single LF as a line terminator and ignore any preceding CR.

Although the request-line and status-line grammar rules require that each of the component elements be separated by a single SP octet, recipients MAY instead parse on whitespace-delimited word boundaries and, aside from the CRLF terminator, treat any form of whitespace as the SP separator while ignoring preceding or trailing whitespace; such whitespace includes one or more of the following octets: SP, HTAB, VT (%x0B), FF (%x0C), or bare CR. However, lenient parsing can result in security vulnerabilities if there are multiple recipients of the message and each has its own unique interpretation of robustness (see Section 9.5)._

**Comment by normanmaurer** [comment]
@sudheerv I am no sure I understand you ... Are you including `\r\n` (typed) in the line ? This does not sound correct to me....

**Comment by sudheerv** [comment]
@normanmaurer 

Thanks for the response. yes, I’m including <\r\n> appended at the end of the request line (after <HTTP/1.1>).

We ran into this while setting up an AWS NLB to in our production environment. The HTTP based Health checks performed by AWS NLB seems to include those extra CRLF in the request line. Reading the RFC 7230, it seems like CRLF should be valid in the request line (references in my comments above).

**Comment by normanmaurer** [comment]
Hmm \r\n as a carriage return yes but as typed directly I don’t think so

**Comment by sudheerv** [comment]
Hmm..just to clarify the health check from the NLB is not including <\r\n> as 4 ASCII characters '\' 'r' '\' 'n'). It is including them as 2 control characters 0x0D (for CR) 0x0A (for LF). And that seems to be failing.

**Comment by normanmaurer** [comment]
@sudheerv ah ok... then I misunderstood you... Are you interested in providing a PR for this ?

**Comment by sudheerv** [comment]
@normanmaurer Yeah, reading back my description, I could tell it was somewhat misleading. Sorry for the confusion. Yeah, I'll dig in some more to confirm there is nothing else strange in the NLB's health check request and then will provide a PR if needed. (Sorry to open an issue to just ask a somewhat random question like this, but, I didn't know how else to contact you). Thanks!

**Comment by normanmaurer** [comment]
@sudheerv ah good it :) Not sure if this is of any interest for you but we also support proxy protocol: https://github.com/netty/netty/tree/4.1/codec-haproxy

**Comment by sudheerv** [comment]
@normanmaurer Thanks! Yeah, we do already support PPV1 and PPV2 in Zuul using Netty's HAProxy decoders. This was a problem caused by receiving unexpected PPV2 packets on the ports setup for processing Health Check (which were not configured with the appropriate channel handlers that handle the PP octets).
