### ISSUE TITLE
endless loop

### ISSUE THREAD

**Issue by liuhanjim** [netty/netty#8328]
### Netty version（4.1.23.Final-SNAPSHOT）
![image](https://user-images.githubusercontent.com/11403678/46135512-f610e800-c277-11e8-953b-61cbb6ba9fa5.png)
it in io.netty.util.Recycler.Head.run(), I think it will endless loop!

**Comment by normanmaurer** [comment]
@liuhanjim this was reported before and was fixed. Update to latest 4.1.x release (4.1.29.Final).

**Comment by liuhanjim** [comment]
thanks
