### ISSUE TITLE
java.lang.ClassCastException: io.netty.bootstrap.FailedChannel cannot be cast to io.netty.channel.socket.DatagramChannel

### ISSUE THREAD

**Issue by MikeBlink** [netty/netty#8329]
### Expected behavior

Some kind of information about underlying issue.

### Actual behavior

Class cast exception is being thrown from the DnsNameResolver as it's trying to hard cast a FailedChannel to DatagramChannel.

### Steps to reproduce

Not sure, what I'm doing is using a library that utilises Netty underneath (Redisson). It's trying to open a connection to localhost redis instance, but before it gets to it netty builds DnsNameResolver and this fails. Unfortunately it happens in CircleCI inside a docker container and not locally, which would suggest an underlying issue in the CI system / configuration, but I can't figure out what the issue is because all I get is a class cast exception.

### Netty version
4.1.29.Final, but tried with a few other 4.1.X versions with same result (as the code is the same).

### OS Version

Docker image of 14.04.1-Ubuntu

### Stacktrace

[error] Caused by: org.redisson.client.RedisConnectionException: Unable to connect to Redis server: 127.0.0.1/127.0.0.1:6379
[error] 	at org.redisson.connection.pool.ConnectionPool$2$1.operationComplete(ConnectionPool.java:137)
[error] 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
[error] 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
[error] 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
[error] 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
[error] 	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:108)
[error] 	at org.redisson.connection.pool.ConnectionPool.promiseFailure(ConnectionPool.java:305)
[error] 	at org.redisson.connection.pool.ConnectionPool.access$400(ConnectionPool.java:53)
[error] 	at org.redisson.connection.pool.ConnectionPool$4.operationComplete(ConnectionPool.java:270)
[error] 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
[error] 	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:504)
[error] 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:483)
[error] 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
[error] 	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:121)
[error] 	at org.redisson.misc.RedissonPromise.tryFailure(RedissonPromise.java:108)
[error] 	at org.redisson.client.RedisClient$2$1$2.run(RedisClient.java:250)
[error] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[error] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[error] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446)
[error] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[error] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[error] 	at java.lang.Thread.run(Thread.java:748)

[error] Caused by: java.lang.IllegalStateException: failed to create a new resolver
[error] 	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:71)
[error] 	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:200)
[error] 	at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:49)
[error] 	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:188)
[error] 	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:174)
[error] 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
[error] 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
[error] 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
[error] 	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
[error] 	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[error] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:978)
[error] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:512)
[error] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
[error] 	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
[error] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[error] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[error] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446)
[error] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[error] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[error] 	at java.lang.Thread.run(Thread.java:748)

[error] Caused by: java.lang.ClassCastException: io.netty.bootstrap.FailedChannel cannot be cast to io.netty.channel.socket.DatagramChannel
[error] 	at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:359)
[error] 	at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:412)
[error] 	at io.netty.resolver.dns.DnsAddressResolverGroup.newNameResolver(DnsAddressResolverGroup.java:114)
[error] 	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:94)
[error] 	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:79)
[error] 	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
[error] 	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:200)
[error] 	at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:49)
[error] 	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:188)
[error] 	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:174)
[error] 	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
[error] 	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
[error] 	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
[error] 	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:103)
[error] 	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
[error] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:978)
[error] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:512)
[error] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
[error] 	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
[error] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[error] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[error] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446)
[error] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[error] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[error] 	at java.lang.Thread.run(Thread.java:748)

**Comment by normanmaurer** [comment]
Was fixed and will be in 4.1.30.Final https://github.com/netty/netty/pull/8280. That said it only happens if there is something wrong during registration which is a bit unexpected.
