### ISSUE TITLE
EpollSocketChannelConfig is repeating the channel field 3x

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#8331]
The`EpollSocketChannelConfig` class is repeating the `channel` field 3x through inheritance. The field has also protected and package-private visibility in the super classes which is potentially bug-prone.

![screenshot from 2018-09-27 13-46-22](https://user-images.githubusercontent.com/191635/46164564-542fd200-c25c-11e8-988b-0fa7f3d14eea.png)

**Comment by normanmaurer** [comment]
@rkapsi doh... Want to send over a pr ?

**Comment by rkapsi** [comment]
@normanmaurer consider it done (hopefully tomorrow morning)
