### ISSUE TITLE
Make DnsNameResolver constructor public again

### ISSUE THREAD

**Issue by slandelle** [netty/netty#8334]
### Expected behavior

DnsNameResolver can be extended.

### Actual behavior

Since 4.0.30, non-deprecated constructor is now package protected.

### Netty version

4.0.30.Final

**Comment by normanmaurer** [comment]
@slandelle why exactly you need to extend it ? I would have hoped we can remove all the public constructors at some point as it just take so many args.

**Comment by slandelle** [comment]
I have a pluggable resolve cache logic, so I extend DnsNameResolver so I can plug onto `doResolveAll`.

**Comment by normanmaurer** [comment]
Can you show me the code ? I would love to find a way without extending

**Comment by slandelle** [comment]
* https://github.com/gatling/gatling/blob/master/gatling-http/src/main/scala/io/gatling/http/resolver/ExtendedDnsNameResolver.scala
* https://github.com/gatling/gatling/blob/master/gatling-http/src/main/scala/io/gatling/http/resolver/CacheOverrideNameResolver.scala#L49

**Comment by normanmaurer** [comment]
@slandelle I may not understand your code correctly but I wonder why you can not archive the same by just using the `DnsNameResolverBuilder` and use a `NoopDnsCache`. Can you give me some pointers ?

**Comment by slandelle** [comment]
I'm trying to have Gatling virtual users share a single DnsNameResolver instance, but with each having its own DnsCache.

So far, I'm hacking my (ugly) way and directly call doResolveAll and pass the DnsCache instance for this resolution instead of using the global one.

I can't build a wrapper that would take care of the caching logic and delegate to the DnsNameResolver because the caching logic is deeply entangled with the resolution one (get happens in DnsNameResolver#doResolveAllCached while cache happens in DnsAddressResolveContext#cache).

**Comment by slandelle** [comment]
Even if I share the same EventLoop, I'd be creating tons of channels.

**Comment by normanmaurer** [comment]
Ok so what about if you could share the Channel and EventLoop ?

**Comment by slandelle** [comment]
Also, I use my DnsCache instances to figure out if a given resolution was a cache hit or a cache miss. I need per resolution DnsCache instances to deal with concurrent resolutions with the same DnsNameResolver instance.

In an ideal world, caching and resolution would be separate concerns, with caching being a wrapper of resolution.

**Comment by slandelle** [comment]
> Ok so what about if you could share the Channel and EventLoop ?

Not sure about this: https://github.com/netty/netty/blob/4.1/resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java#L408-L416

**Comment by slandelle** [comment]
The most simple solution for me would be to have resolve/resolveAll overloads that let one pass a custom DnsCache. Would that be fine with you?

**Comment by slandelle** [comment]
What I want to achieve is to have one single `DnsNameResolver` (for performance) but have each Gatling virtual users have their own `DnsCache`. A typical use case is dealing with an elastic architecture where new records are added to the DNS server under load so new incoming users would resolve the new IPs while the former ones would stick to the original ones until ttl.

I looked at wrapping a `DnsNameResolver` with a `NoCache` and dealing with the caching myself in the wrapper. Sadly, the caching logic is quite complex I would have to duplicate lots of Netty code.

It looks to me that the ideal solution would be that `DnsNameResolver` `resolve` and `resolveAll` had overloads that take a `DnsCache` to override the global one. This way, I could stop extending `DnsNameResolver`.

Would that work for you? Would you accept such a PR?

**Comment by normanmaurer** [comment]
@slandelle let me think about it... I think you would also need to pass in a `AuthoritativeDnsServerCache` no ?

**Comment by slandelle** [comment]
> I think you would also need to pass in a AuthoritativeDnsServerCache no ?

Indeed
