### ISSUE TITLE
set log level to INFO for Default DNS servers output of DefaultDnsServerAddressStreamProvider

### ISSUE THREAD

**Issue by mrniko** [netty/netty#8341]
### Expected behavior
`Default DNS servers` printed with log level INFO
### Actual behavior
`Default DNS servers` printed with log level DEBUG
### Netty version
4.1.30.Final

This would help to realize which dns servers currently used by netty.

**Comment by normanmaurer** [comment]
@mrniko actually I am not sure if this is really something we want to change. IMHO it really belongs to debug level. @Scottmitch @trustin @carl-mastrangelo @ejona86 @bryce-anderson WDYT ?

**Comment by trustin** [comment]
+1 for DEBUG. As a library, I'd like to keep non-DEBUG messages minimal.

**Comment by ejona86** [comment]
+1 for DEBUG.

**Comment by normanmaurer** [comment]
Ok let me close as "won't fix" then
