### ISSUE TITLE
json body not decoded correctly

### ISSUE THREAD

**Issue by cipri7329** [netty/netty#8346]
### Expected behavior
my request is the following 

```
curl -X POST \
  http://localhost:3002/api/dsl \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 308c8d00-a9be-4fbd-b9d7-3ca3a0ece72c' \
  -H 'cache-control: no-cache' \
  -d '{
    {
      "dsl": "pipe titanic | where Pclass = 3 | as t3",
       "messageId": "test"
    }
}'
```

I expect the get the content from the Request on the server side the complete json.
Scala code
```
request: HttpRequest
val requestBody = request.getContent.toString(UTF_8)
```

I expect the requestBody to be 
```
{
    {
      "dsl": "pipe titanic | where Pclass = 3 | as t3",
       "messageId": "test"
    }
}
```
### Actual behavior
The actual requestBody is an incomplete JSON string 
```
       "messageId": "test"
    }
}
```

### Steps to reproduce
see above CURL command
### Minimal yet complete reproducer code (or URL to code)
see above CURL command

In the following line if I change the `=` symbol with `+` for example, I get the complete JSON deserialized in the `requestBody`.

With this line it works:  ` "dsl": "pipe titanic | where Pclass + 3 | as t3",`

### Netty version
io.netty:netty:jar:3.9.9.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_181"
Scala code runner version 2.11.12

### OS version (e.g. `uname -a`)
Mac OSX High Sierra

**Comment by normanmaurer** [comment]
Sorry but 3.x is EOL for a long time (over a year).
