### ISSUE TITLE
new method for ByteBufUtil Expected: compare(use equal) ByteBuf with a static final byte[]

### ISSUE THREAD

**Issue by sosoeo** [netty/netty#8381]
### new method/function Expected for ByteBufUtil
I need strongly a new method in ByteBufUtil which works like this:
 boolean equals(ByteBuf a, int aStartIndex, **byte[]** b, int bStartIndex, int length)
I want to compare a ByteBuf with a static final byte array, now I without this,I have to create a new ByteBuf to hold the static final array,doesn't it?

**Comment by sosoeo** [comment]
now I have to use Unpooled wrappedBuffer to prepare a ByteBuf for later ByteBufUtil.equals():
    private static final ByteBuf heartBeatMessage = 
Unpooled.wrappedBuffer(new byte[]{(byte)0x88,(byte)0x88,(byte)0x88,(byte)0x88,0x01});

is this the only or designed way?

**Comment by normanmaurer** [comment]
@sosoeo yep you should just create a `ByteBuf` to compare to. You can also make it readOnly.
