### ISSUE TITLE
shutdownOutput may loss read ops ?  just a doubt

### ISSUE THREAD

**Issue by yangyi438** [netty/netty#8382]
0, netty 4.1.19.Final
1, set the SoLinger() > 0
2, config().isAutoClose() = false
3, writeAndFlush(msg)
4, doWrite happen exception, with io  .
run  code in  
io.netty.channel.AbstractChannel   
line 644 

Executor closeExecutor = prepareToClose()

`private void shutdownOutput(final ChannelPromise promise, Throwable cause) {
       if (!promise.setUncancellable()) {
                return;
            }

            final ChannelOutboundBuffer outboundBuffer = this.outboundBuffer;
            if (outboundBuffer == null) {
                promise.setFailure(CLOSE_CLOSED_CHANNEL_EXCEPTION);
                return;
            }
            this.outboundBuffer = null; // Disallow adding any messages and flushes to outboundBuffer.

            final Throwable shutdownCause = cause == null ?
                    new ChannelOutputShutdownException("Channel output shutdown") :
                    new ChannelOutputShutdownException("Channel output shutdown", cause);
                    **Executor closeExecutor = prepareToClose();  //fixme** 
            if (closeExecutor != null) {
                closeExecutor.execute(new Runnable() {
                    @Override
                    public void run() {
                        try {
                            // Execute the shutdown.
                            doShutdownOutput();
                            promise.setSuccess();
                        } catch (Throwable err) {
                            promise.setFailure(err);
                        } finally {
                            // Dispatch to the EventLoop
                            eventLoop().execute(new Runnable() {
                                @Override
                                public void run() {
                                    closeOutboundBufferForShutdown(pipeline, outboundBuffer, shutdownCause);
                                }
                            });
                        }
                    }
                });
            } else {
                try {
                    // Execute the shutdown.
                    doShutdownOutput();
                    promise.setSuccess();
                } catch (Throwable err) {
                    promise.setFailure(err);
                } finally {
                    closeOutboundBufferForShutdown(pipeline, outboundBuffer, shutdownCause);
                }
            }
        }`

In function  prepareToClose()  we will  <<<cancel the SelectorKey >>>
a doubt , 

1,,
the channel may be gc  we will lose it, 
It seems that  channelInactive has no triggered, if i not call channel.close in exceptionHandler

2,,
 Is readOps of selectKey valid?
Can read from TCP receive buffer,but could not write?
If it exists, we lose part of the TCP receive buffer 

----Just a puzzle  , I might be wrong

**Comment by normanmaurer** [comment]
Sorry I don't get it I think...

**Comment by normanmaurer** [comment]
Closing as no followup
