### ISSUE TITLE
Feature request: let one pass a SecureRandom instance when building SslContext

### ISSUE THREAD

**Issue by slandelle** [netty/netty#8384]
### Expected behavior

When spawning multiple `JdkSslContext`, it should be possible to reuse a single SecureRandom instance and save allocations.

### Actual behavior

`SslContextBuilder` won't let one pass a SecureRandom instance.
Both `JdkSslServerContext#newSSLContext` and `JdkSslClientContext#newSSLContext` pass a null random value to `SSLContext#init` that allocates a new `SecureRandom` instance.

### Minimal yet complete reproducer code (or URL to code)

NA

### Netty version

4.1.30

### JVM version (e.g. `java -version`)

NA

### OS version (e.g. `uname -a`)

NA

**Comment by slandelle** [comment]
@normanmaurer please let me know if I can send a PR

**Comment by normanmaurer** [comment]
@slandelle I wonder if you would not be better of to just create your `SSLContext` (the java one) directly and then construct the JdkSslContext from it ?

**Comment by slandelle** [comment]
Oh right, I didn't notice you were keeping the `JdkSslContext` constructor public.
Yes, that would work for me, thanks!

**Comment by slandelle** [comment]
Actually, the "full" constructor is package protected, so there's no way to pass my own `SSLContext` and disable old protocols such as SSLv3.

**Comment by normanmaurer** [comment]
@slandelle what about adding another public constructor that allows this ?  Also in the meantime you can also just wrap the `JdkSslContext` that you created via a `DelegatingSslContext` and override `initEngine` where you can just set the protocols etc.

**Comment by slandelle** [comment]
PR sent: #8389
