### ISSUE TITLE
rawPath(wsURL) causes encoded query string be decoded，causing the wrong request to be sent

### ISSUE THREAD

**Issue by mawenyu** [netty/netty#8387]
https://github.com/netty/netty/blob/04001fdad1ca3c72625cddb1b1c7789381cb5f30/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshaker13.java#L129

My original URL is：http://192.168.1.5/v1/test?info=test%40abc%23def
String path = rawPath(wsURL);  ==>    http://192.168.1.5/v1/test?info=test@abc#def

Am I doing anything wrong? or this is a bug?

**Comment by normanmaurer** [comment]
@mawenyu this may be a bug... would you be able to provide a pr to fix this ?

**Comment by mawenyu** [comment]
This bug has fixed。 I am using netty 4.1.5-Final，so the problem exist
![image](https://user-images.githubusercontent.com/1763479/47061840-e0069f80-d205-11e8-91b7-155a41934043.png)
![image](https://user-images.githubusercontent.com/1763479/47061861-fd3b6e00-d205-11e8-8f26-b3f49afd1827.png)
