### ISSUE TITLE
CompositeByteBuf.decompose() doesn't work as expected.

### ISSUE THREAD

**Issue by atcurtis** [netty/netty#8400]
### Expected behavior
It is expected that the arguments to CompositeByteBuf decompose() are the same as for slice()

### Actual behavior
We get random garbage at the start.

### Steps to reproduce

Call decompose with valid arguments.

### Minimal yet complete reproducer code (or URL to code)

    ByteBufAllocator alloc = PooledByteBufAllocator.DEFAULT;    
    ByteBuf buf = alloc.directBuffer(16384).setIndex(0, 16384);

    StringBuilder sb = new StringBuilder(16384);
    while (sb.length() < 16000) {
      sb.append(UUID.randomUUID());
    }
    buf.setBytes(0, sb.toString().getBytes());

    CompositeByteBuf composite = alloc.compositeBuffer();
    composite.addComponents(true,
        buf.retainedSlice(100, 200),
        buf.retainedSlice(300, 400),
        buf.retainedSlice(10000, 1000));

    ByteBuf test1 = composite.slice(150, 700);

    ByteBuf test2 = Unpooled.wrappedBuffer(composite.decompose(150, 700).toArray(new ByteBuf[0]));

    Assert.assertTrue(ByteBufUtil.equals(test1, test2)); // this equality test fails.

### Netty version
4.1.22

### JVM version (e.g. `java -version`)
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

### OS version (e.g. `uname -a`)
Linux acurtis-ld1 3.10.0-514.36.5.el7.x86_64 #1 SMP Thu Dec 28 21:42:18 EST 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@atcurtis thanks for reporting... Should be fixed by https://github.com/netty/netty/pull/8403. PTAL
