### ISSUE TITLE
channel.localAddress() returns a wrong value in some cases

### ISSUE THREAD

**Issue by WhiteTrashLord** [netty/netty#8419]
I am using Netty 4.1.30.
In my Netty application I only bind the IP 127.0.0.1. In an initializer I call channel.localAddress() for this channel. Most of the times the return value is the expected /127.0.0.1. But sometimes I also see 0.0.0.0/0.0.0.0 for the local address. Is this a bug? I think I have this problem only on Windows when I can't use Epoll but I am not very sure about it. Maybe it has something to do with IPv6?

**Comment by normanmaurer** [comment]
Are you sure channelActive was called yet ?

**Comment by WhiteTrashLord** [comment]
Yes, the channel should be active. The application is very similar to the example HexDumpProxy.  
The channel.localAddress() is called on the inboundChannel in the Initializer for the class HexDumpProxyBackendHandler. I added the Initializer class.

**Comment by WhiteTrashLord** [comment]
Will the local address of a channel which is no longer active bet set to 0.0.0.0/0.0.0.0?
After some changes in the code I no longer see this problem. I will reopen this issue in case I see it again.
