### ISSUE TITLE
EpollArrayWrapper.epollCtl IOException:File exists

### ISSUE THREAD

**Issue by wenweihu86** [netty/netty#8424]
<img width="1120" alt="2018-10-23 17 51 36" src="https://user-images.githubusercontent.com/2144079/47352455-7fd39a00-d6ec-11e8-8229-29fc6de43509.png">

### Netty version
4.1.15.Final
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
Linux

**Comment by normanmaurer** [comment]
@wenweihu86 this version is super wild... please upgrade and report back. Also please not that its thrown by the jdk itself and not netty so you may want to upgrade java as well.
