### ISSUE TITLE
ChannelOption for FIRE_EXCEPTION_ON_FAILURE?

### ISSUE THREAD

**Issue by Bennett-Lynch** [netty/netty#8429]
I want to be able to react to *any* outbound channel failure.

I can add a handler to the tail of my pipeline that will call `promise.addListener(ChannelFutureListener.FIRE_EXCEPTION_ON_FAILURE)` for every outbound event, but this is not sufficient.

Specifically, in the case of a `MessageToMessageEncoder` that outputs more than one object, new promises are created for all but the last object:
https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/codec/src/main/java/io/netty/handler/codec/MessageToMessageEncoder.java#L112-L127

If one of those objects then triggers a failure on a subsequent outbound handler, the exception is suppressed.  There might be other scenarios where this can happen as well.

How can I react to these failures when I don't have the opportunity to inject a `ChannelFutureListener.FIRE_EXCEPTION_ON_FAILURE`?

Would it be reasonable to have a `ChannelOption` for `FIRE_EXCEPTION_ON_FAILURE`?

### Netty version

4.1.30.Final

**Comment by normanmaurer** [comment]
@Bennett-Lynch that's a good question.. I like the idea of the `ChannelOption` but I would need to investigate if this is easily doable without breaking any API (I suspect it should be doable).

**Comment by normanmaurer** [comment]
@Bennett-Lynch https://github.com/netty/netty/pull/8448 PTAL

**Comment by Bennett-Lynch** [comment]
@normanmaurer I would like to re-open this issue, as I believe that the current implementation of making users manually inject `ChannelFutureListener.FIRE_EXCEPTION_ON_FAILURE` to writes is still cumbersome, and problematic in more complex pipelines that might have writes triggered by multiple sources.

The `MessageToMessageEncoder` fix was helpful, but I am still encountering use cases where I would like to be able to default this behavior to ON for an entire pipeline.  For example, if I have a handler that detects some special case and writes a response object to a pipeline, I have to ensure that it writes to the `ChannelHandlerContext`, and not the `Channel`, in order to pass through my `FIRE_EXCEPTION_ON_FAILURE` injecting-handler.  This introduces some unnecessary coupling and is just generally awkward.

I want to be able to know about all outbound failures (even if they're my own programming fault), in a simple and transparent manner.  I'm okay paying a small performance cost for it, if it's opt-in.

@trustin @bryce-anderson @ejona86 Can I convince you of the same?  Is there a better solution that I am not thinking of?  The motivation that I'm after is fairly simple, in that I want guaranteed visibility on any outbound failure.

**Comment by ejona86** [comment]
> I have to ensure that it writes to the Channel, and not the ChannelHandlerContext, in order to pass through my FIRE_EXCEPTION_ON_FAILURE injecting-handler

This is generally necessary. While I agree it isn't obvious to new users, any time you get it wrong is a recipe for weird things to happen.

Although I'm also not quite sure why writing to the Channel would break things in this particular case; it would eventually go through the current Handler's ctx either way.

> Otherwise, I would have to insert a FIRE_EXCEPTION_ON_FAILURE injecting-handler before and after every single handler, as writes may enter the pipeline from any point, and they mail fail at any point.

If you need it between ever handler, then I'm not sure how FIRE_EXCEPTION_ON_FAILURE would be implemented. It seems in both cases there's a problem with adding a listener for every handler in the pipeline, which would not be great.

**Comment by Bennett-Lynch** [comment]
@ejona86 My concern is that I'm essentially *required* to write to the tail of the pipeline every time.  And there are valid use cases where you don't *always* want to write to the tail end of the pipeline.  A simple encoder-like handler would be one.

If I have a pipeline like so:

`{Socket} - [ A ] - [ B ] - [ C ] - [ D ]`

Where `A` is the first inbound handler, and `D` is the tail.

Assume that writes can insert the pipeline at any of the handlers.  And assume that any of the handlers can have their write fail for some unpredictable reason.

To safely cover my "requirements" (guaranteed visibility on any outbound failure), I would need to insert a handler that injects `ChannelFutureListener.FIRE_EXCEPTION_ON_FAILURE` in between all of the handlers picture above.

This is actually doable today, but it entails incredibly clunky behavior in place of what seems like should be a simple channel option.

There's not strictly a problem with adding a listener for every handler.  Every handler can simply remove-then-add to ensure they are idempotent:

```
@Override
public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) {
    promise.removeListener(ChannelFutureListener.FIRE_EXCEPTION_ON_FAILURE);
    promise.addListener(ChannelFutureListener.FIRE_EXCEPTION_ON_FAILURE);
    ctx.write(msg, promise);
}
```

Besides being clunky, this probably carries unnecessary performance costs as well.

**Comment by ejona86** [comment]
Okay. I see what you were meaning now. In any case a "ChannelOption for FIRE_EXCEPTION_ON_FAILURE" wouldn't fix this behavior; the Channel has just as hard of a time managing the future failure as you are having now.

The only idea I have would be for {ctx, channel, pipeline}.newPromise() to return a promise with the listener already added. The main way to "break" that behavior would be to construct a DefaultChannelPromise manually, which would be pretty rare. But having a promise with an auto-installed listener seems a bit too magical.

**Comment by Bennett-Lynch** [comment]
@ejona86 The ask isn't so much to magically auto-install a listener, but to simply offer a channel option that will revert the behavior back to how it used to behave in Netty 3: https://github.com/netty/netty/pull/8448
