### ISSUE TITLE
[Netty 5]: Remove the HttpObjectDecoder `maxChunkSize` parameter in Netty 5.x

### ISSUE THREAD

**Issue by bryce-anderson** [netty/netty#8430]
This is a cleanup request for Netty 5.x. The family of HTTP codecs passes a parameter called `maxChunkSize` to `HttpObjectDecoder` which limits the size of chunks that decoder will emit. Note that this doesn't cause the HTTP dispatch to switch from a `FullHttpMessage` to a regular message or to avoid buffering data, it only means that any already buffered content data may be split into smaller messages if its size exceeds the limit. For example, if the raw `buffer` has 16kb of message content but the `maxChunkSize` is 2kb, it will simply split the content into 8*2kb `HttpContent` instances instead of a single 16kb instance.

The current value of this is questionable and was likely more useful in the Netty3 model when the decoder may have emitted fully buffered messages.

### Netty version
4.1.x

**Comment by vkostyukov** [comment]
For the reference, this is us unsetting the limit in Finagle: https://github.com/twitter/finagle/commit/990c8650366e5374ea062c753a4628c5971fc40e

**Comment by normanmaurer** [comment]
@bryce-anderson @vkostyukov agree... @Scottmitch also told me at some point he wanted to remove it.

**Comment by normanmaurer** [comment]
@bryce-anderson want to do a PR against the master branch ?

**Comment by bryce-anderson** [comment]
@normanmaurer, I'll take this one, probably early next week.

**Comment by normanmaurer** [comment]
@bryce-anderson thanks a lot!
