### ISSUE TITLE
NioEventLoop task execution might throw UnsupportedOperationException on shutdown

### ISSUE THREAD

**Issue by vietj** [netty/netty#8475]
### Expected behavior
Execution instead throws `RejectedExecutionException`.

### Actual behavior
There is a racy `UnsupportedOperationException` instead because the task removal is delegated to `MpscChunkedArrayQueue` that does not support removal. This happens with `SingleThreadEventExecutor` that overrides the `newTaskQueue` to return an MPSC queue instead of the `LinkedBlockingQueue` returned by the base class such as `NioEventLoop`, `EpollEventLoop` and `KQueueEventLoop`.

### Steps to reproduce
Schedule task to an event loop concurrently to an event loop shutdown.

### Minimal yet complete reproducer code (or URL to code)
```
    @Test
    public void testTaskRemovalOnShutdownThrowsUnsupportedOperationException() throws Exception {
        NioEventLoopGroup group = new NioEventLoopGroup(1);
        final NioEventLoop loop = (NioEventLoop) group.next();
        final Runnable task = new Runnable() {
            @Override
            public void run() {
                try {
                    Thread.sleep(1);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        };
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    loop.execute(task);
                }
            }
        }.start();
        Thread.sleep(10);
        loop.shutdownNow();
        Thread.sleep(100000);
    }
```

this is a racy test, the event loop shutdown race against the the task producing thread, if you run it enough it will fail:

```
Exception in thread "Thread-0" java.lang.UnsupportedOperationException
	at org.jctools.queues.BaseMpscLinkedArrayQueue.iterator(BaseMpscLinkedArrayQueue.java:201)
	at java.util.AbstractCollection.remove(AbstractCollection.java:282)
	at io.netty.util.concurrent.SingleThreadEventExecutor.removeTask(SingleThreadEventExecutor.java:340)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:781)
	at io.netty.channel.nio.NioEventLoopTest$8.run(NioEventLoopTest.java:195)
```

### Netty version
At least 4.1.x

### JVM version (e.g. `java -version`)
N/A

### OS version (e.g. `uname -a`)
N/A

**Comment by normanmaurer** [comment]
@vietj thanks! Will provide a fix soon.
