### ISSUE TITLE
My Android App netty-all-4.1.23.Final.jar change to 4.1.31.Final.jar  and show this wrong, just show this log

### ISSUE THREAD

**Issue by jasonSuzhow** [netty/netty#8478]
this is the log:::::::::::
`I: Rejecting re-init on previously-failed class java.lang.Class<io.netty.util.internal.logging.Log4J2Logger>: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/logging/log4j/spi/ExtendedLoggerWrapper;
I:     at io.netty.util.internal.logging.InternalLoggerFactory io.netty.util.internal.logging.InternalLoggerFactory.newDefaultFactory(java.lang.String) (InternalLoggerFactory.java:50)
I:     at io.netty.util.internal.logging.InternalLoggerFactory io.netty.util.internal.logging.InternalLoggerFactory.getDefaultFactory() (InternalLoggerFactory.java:67)
I:     at io.netty.util.internal.logging.InternalLogger io.netty.util.internal.logging.InternalLoggerFactory.getInstance(java.lang.String) (InternalLoggerFactory.java:93)
I:     at io.netty.util.internal.logging.InternalLogger io.netty.util.internal.logging.InternalLoggerFactory.getInstance(java.lang.Class) (InternalLoggerFactory.java:86)
I:     at void io.netty.channel.MultithreadEventLoopGroup.<clinit>() (MultithreadEventLoopGroup.java:35)
I:     at void com.dlm.amazingcircle.net.netty.NettyClient.connectServer() (NettyClient.java:78)
I:     at void com.dlm.amazingcircle.net.netty.NettyClient.access$200(com.dlm.amazingcircle.net.netty.NettyClient) (NettyClient.java:27)
I:     at void com.dlm.amazingcircle.net.netty.NettyClient$1.run() (NettyClient.java:66)
I: Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.logging.log4j.spi.ExtendedLoggerWrapper" on path: DexPathList[[zip file "/data/app/com.dlm.amazingcircle-2/base.apk", zip file "/data/app/com.dlm.amazingcircle-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.dlm`

### Minimal yet complete reproducer code (or URL to code)
EventLoopGroup group = new NioEventLoopGroup();

### Netty version
netty-4.1.31.Final

### JVM version (e.g. `java -version`)
Java 1.8

### OS version (e.g. `uname -a`)
macos 10.12.4

**Comment by normanmaurer** [comment]
@jasonSuzhow are you sure you use the correct log4j2 version ?

**Comment by jasonSuzhow** [comment]
> @jasonSuzhow are you sure you use the correct log4j2 version ?

My peoject don't configure this log4j2, and i dont know how to change this.
![image](https://user-images.githubusercontent.com/13963143/48190029-8add2a00-e37c-11e8-82d4-6b25ccbf7001.png)
i searched my project, just find this

**Comment by normanmaurer** [comment]
So you say you don not include log4j at all ?

**Comment by chenjinying1988** [comment]
@jasonSuzhow Have you solved it yet?

**Comment by johnou** [comment]
@jasonSuzhow you can set it like this.. 

```
InternalLoggerFactory.setDefaultFactory(JdkLoggerFactory.INSTANCE);
```

**Comment by johnou** [comment]
https://static.javadoc.io/io.netty/netty-common/4.1.31.Final/io/netty/util/internal/logging/InternalLoggerFactory.html

**Comment by jasonSuzhow** [comment]
> @jasonSuzhow you can set it like this..
> 
> ```
> InternalLoggerFactory.setDefaultFactory(JdkLoggerFactory.INSTANCE);
> ```

Thanks, I solved it

**Comment by jasonSuzhow** [comment]
> @jasonSuzhow Have you solved it yet?
Yeah, The solution is @johnou's answer

**Comment by jasonSuzhow** [comment]
> @jasonSuzhow Have you solved it yet?

Yeah, The solution is @johnou's answer

**Comment by johnou** [comment]
@normanmaurer slf4j in Netty 5?
