### ISSUE TITLE
some problems with netty debug log

### ISSUE THREAD

**Issue by strongmanwj** [netty/netty#8483]
### Expected behavior
netty can print rigth debug log with its parameter.
### Actual behavior
can not print its parameter.
[DEBUG][2018-11-08 16:26:58,872][io.netty.util.internal.logging.InternalLoggerFactory]Using SLF4J as the default logging framework
[DEBUG][2018-11-08 16:26:58,882][io.netty.channel.MultithreadEventLoopGroup]-Dio.netty.eventLoopThreads: {}
[DEBUG][2018-11-08 16:26:58,913][io.netty.channel.nio.NioEventLoop]-Dio.netty.noKeySetOptimization: {}
[DEBUG][2018-11-08 16:26:58,913][io.netty.channel.nio.NioEventLoop]-Dio.netty.selectorAutoRebuildThreshold: {}
### Steps to reproduce
problem happpened when using slf4j-log4j12 for logger.  when i just  use log4j it is ok.  How to solve? 
<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.7.25</version>
		</dependency>
### Netty version
4.1.31
### JVM version (e.g. `java -version`)
1.8

**Comment by normanmaurer** [comment]
Should be fixed by #8595
