### ISSUE TITLE
Why dependencies to common and buffer are transitive?

### ISSUE THREAD

**Issue by Feri73** [netty/netty#8496]
Many of the modules use common and buffer directly (for example by defining a variable of a type declared in buffer module). However, they do not have explicit dependency to these modules (in maven) and the jars are added because of transitivity of dependencies. What is the reason? Isn't it a good practice to explicitly define these kind of dependencies?

**Comment by normanmaurer** [comment]
Yes you are right. We love PRs

**Comment by normanmaurer** [comment]
@Feri73 ^^

**Comment by Feri73** [comment]
I got this and will send a pull request addressing this and one other issue as soon as I can get the build work on windows.
