### ISSUE TITLE
In case of connection issue channel.remoteAddress() returns null

### ISSUE THREAD

**Issue by Andremoniy** [netty/netty#8501]
### Expected behavior

It should return the request address, which is correctly passed into the `AnnotatedConnectionException`:

`
        protected final Throwable annotateConnectException(Throwable cause, SocketAddress remoteAddress) {
...
}
`

### Actual behavior

It returns `null` when trying to get it from the channel on receiving an exception.

### Netty version

4.x.x.

**Comment by Andremoniy** [comment]
This is not actually a bug, because the spec states that the method returns `null` if the channel is not connected:

> {@code null} if this channel is not connected.

But could be an improvement because it is useful to have this information in some error handlers.

**Comment by Jovons** [comment]
Agree. If `channelInactive` cannot see remote address, how could it reconnect?
