### ISSUE TITLE
[Netty 5] AttributeMap removal 

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#8508]
We want to remove the `AttributeMap` and also the `attr(...)` method from the `Channel` / `ChannelHandlerContext`. 

There are two possibilities for this:
 * provide another way to map things to a `Channel`. How exactly this is done is not clear yet, but perhaps the extensibility improvements will allow for wrapping the `Channel`, or state can be kept in a `ChannelHandler`. 
 * Just don't offer a replacement and have the user use stateful `ChannelHandler`.

**Comment by slandelle** [comment]
> We want to remove the AttributeMap and also the attr(...) method from the Channel / ChannelHandlerContext.

@normanmaurer Why? What's the issue?

**Comment by normanmaurer** [comment]
@slandelle the API is sometimes hard to use and not really gives a lot of advantages over just store the state in the ChannelHandler itself or use a `Map<ChannelId, Whatever>`.

**Comment by slandelle** [comment]
@normanmaurer I agree that `AttributeMap` is not useful for `ChannelHandler`.

But I tend to disagree for `Channel`.

I use `AttributeMap` on `Channel` to store concurrent HTTP/2 streams count. Using a global map would actually make things more complicated: I would have to deal with concurrency and clean up (when channel gets closed so I don't leak memory).

**Comment by normanmaurer** [comment]
@slandelle thats a good feedback :) What about providing something like `ChannelLocal` that we had in Netty 3 ?https://github.com/netty/netty/blob/3.10/src/main/java/org/jboss/netty/channel/ChannelLocal.java

**Comment by slandelle** [comment]
@normanmaurer Isn't ChannelLocal what was replaced by AttributeMap in Netty 4? I guess it was dropped/replaced for a reason. Maybe listener overhead?

The API could be simplified for sure, but I like the feature :)

**Comment by normanmaurer** [comment]
@slandelle yep it was... The reason was basically be cause @trustin and myself felt that it should be part of the `Channel` itself. That said I am not convinced of it anymore and it comes with a cost.

**Comment by rkapsi** [comment]
Alternatively use composition over inheritance and don't extend Channel from AttributeMap.

**Comment by johnou** [comment]
@normanmaurer you don't foresee any performance hit with `Map<ChannelId, Whatever>` vs a session object stored directly in the channel which can easily be referenced every read?

**Comment by normanmaurer** [comment]
@johnou I am not convinced that this is the right thing to use for every read. For every read you should store the state directly in the ChannelHandler IMHO.

**Comment by johnou** [comment]
@normanmaurer now I'm wondering why I didn't implement it with a ChannelHandler in the first place :wink:

**Comment by doom369** [comment]
I use both approaches, channel attributes, and `ChannelHandler` state. Attributes are more user-friendly and simpler in terms of usage and implementation. However, when I need maximum performance, I chose `ChannelHandler`. I vote for @rkapsi proposal. Less inheritance - less footprint for every channel object, while API is still there.

**Comment by vietj** [comment]
@normanmaurer we use it to store the SNI host name on the server with an SNI handler override, so it is attached to the channel

**Comment by normanmaurer** [comment]
@vietj can you show me the code ?

**Comment by vietj** [comment]
- https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/net/impl/SslHandshakeCompletionHandler.java#L40
- https://github.com/eclipse-vertx/vert.x/blob/master/src/main/java/io/vertx/core/net/impl/ConnectionBase.java#L319

@normanmaurer

**Comment by Bennett-Lynch** [comment]
I would push back against possibility #2.  I think maintaining state across a Channel is an incredibly common and valid use case, and Netty ought to provide some native support for that.

**Comment by normanmaurer** [comment]
@Bennett-Lynch @vietj thanks for your suggestions so far.

**Comment by trustin** [comment]
I find the ability to attach an arbitrary object to a `Channel` very useful in practice, especially when I do not wish to introduce tight coupling between handlers or when there's stateful information that do not belong to any handlers. The `AttributeMap` API is somewhat ugly although it serves my needs well.

**Comment by medusar** [comment]
Attaching an object to a Channel is very useful, for example, if you want some object to have the same lifetime with a channel, attaching the object to a channel is the best choice, otherwise you will have to save the object somewhere else and add a listener for the event, which introduces thread safety issues.

**Comment by normanmaurer** [comment]
Ok let's close this as it seems the community would like to keep it.
