### ISSUE TITLE
[Netty 5] Half Closure

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#8509]
Half closure is not exposed as a first class citizen in the channel APIs. This leads to inconsistent, and often buggy code, related to handling half closed state. Should we make half closed a more first class concept in the new APIs? This concepts exists in most modern full duplex protocols, and may be simulated via the methods returning the same value otherwise. The confusion is compounded because `isActive()` and `isOpen()` is vaguely defined in the APIs and may still return true while the channel is half closed. This likely includes keeping a concept like `AUTO_CLOSE` to avoid prematurely closing the `Channel` before data is read.

`shutdownInput` / `shutdownOutput` don't flow through from the user through pipeline and are currently propagated via user events when only when inbound events occur. We should have a better story for the outbound/user events relative to the pipeline.

We would like to take action here and improve this scenario. For example one idea we had was to add another “enum” which represent different way of closing a `Channel` and also different “states” of `Channel` in terms of active and inactive.

**Comment by medusar** [comment]
what can i do if i'd like to shutdownInput in netty 4.1 ?
