### ISSUE TITLE
[Netty 5] EventLoop(Group) / EventExecutor(Group) extensibility 

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#8514]
The `EventLoop` and `Channel` implementations are very tightly coupled, and the `EventLoop` also has some factory methods internally which don't facilitate wrapping. We should make sure the ?`EventLoop` and `EventExecutor` APIs support wrapping so users can maintain metrics and otherwise extend the capability of existing implementations. 
Extending event loops such as `EpollEventLoop` would allow applications to implement asynchronous architectures such as thread per core, by handling all events in the loop (file, network and application). In order to support latency SLAs, some applications may not be able to use the loops offered by Netty as they are. For example, they may need to handle events according to different priorities, or support back pressure, or have more timely wake up mechanisms and so forth. These requirements are very application specific, so they should not be concerns of Netty. However, allowing extending event loops such as `EpollEventLoop` would remove from applications low level concerns that are platform specific. 

We want to support this, but more investigation is needed as to “how”. Extensibility in general is a priority and the `EventLoop` in particular is currently lacking.

**Comment by johnou** [comment]
This is particularly interesting to me, I have gone to a great deal of effort to lower overhead (writing only from the correct eventloop) with our server application, I wrote up a small explanation here https://github.com/netty/netty/issues/7020#issuecomment-388007409

**Comment by normanmaurer** [comment]
This should be complete
