### ISSUE TITLE
[Netty 5] Future Generics cleanup / simplification

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#8515]
The generic type parameters for `Future`s should be investigated and fixed. For example the generic parameter on `GenericFutureListener` are overly complicated and make effective usage of the generic parameters difficult without a subtype of `Future`.

**Comment by chrisvest** [comment]
It's possible to do this _if_ Future is generic over its implementation.
However, that in turn makes it hard to declare a generic type of Future without using subclassing to terminate the type recursion that comes from futures generalising over themselves:

```java
public interface Fut<R, F extends Fut<R, F>> {
    F onComplete(Consumer<? super F> callback);
    F a();

    interface Future<R> extends Fut<R, Future<R>> {
        void b();
    }

    interface ChannelFuture<R> extends Fut<R, ChannelFuture<R>> {
        Channel channel();
        void c();
    }

    static void main(String[] args) {
        // Can't declare Fut vars easily
        Fut<Integer, ?> fut = null;

        fut.onComplete(f -> {
            f.a();
        }).a().a();

        Future<Integer> future = null;
        future.onComplete(f -> {
            f.a().b();
        }).b();

        ChannelFuture<Integer> cf = null;

        cf.onComplete(f -> {
            f.channel();
            f.a().c();
        }).c();

        Consumer<ChannelFuture<Integer>> a = null;
        cf.onComplete(a).c();
//        fut.onComplete(a); // rejected
//        future.onComplete(a); // rejected

        Consumer<Fut<Integer, ?>> b = null;
        cf.onComplete(b).c();
        fut.onComplete(b).a();
        future.onComplete(b).b();

        Consumer<Fut<?, ?>> c = null;
        cf.onComplete(c).c();
        fut.onComplete(c).a();
        future.onComplete(c).b();
    }
}
```

The `a()`, `b()`, and `c()` methods are used to prove that the correct future-types flow through.
Also, ignore all the `null` values; the above is only about how the types fit together.

**Comment by NiteshKant** [comment]
I am wondering if we should have a result type at all for our `Future`s. The fact that all data flow through the pipeline and the primary usage is `ChannelFuture` which carries no result, I feel supporting anything apart from `Future<Void>` is an overhead. WDYT?

**Comment by normanmaurer** [comment]
> I am wondering if we should have a result type at all for our Futures. The fact that all data flow through the pipeline and the primary usage is ChannelFuture which carries no result, I feel supporting anything apart from Future<Void> is an overhead. WDYT?

I think we definitely need to have a result type as we also want to use our futures for example in `DnsNameResolver` etc.

**Comment by ejona86** [comment]
> For example the generic parameter on GenericFutureListener are overly complicated and make effective usage of the generic parameters difficult without a subtype of Future.

Taking from https://github.com/netty/netty/pull/11517#discussion_r679297862, the generic isn't verified at all so mostly just hides an implicit cast.

**Comment by chrisvest** [comment]
Considering #8516, if we end up not having `ChannelFuture`, then I think we won't need to ever abstract over the implementation of `Future`. They should just all behave the same. And then we'll only generalise over the result type.
