### ISSUE TITLE
[Netty 5] ChannelFuture type

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#8516]
This special type of Future is associated with a `Channel`. However it is not always necessary to have this association and we may be able to remove this type entirely to simplify the type hierarchy. One specific complication with this is the `Bootstrap` has to return a `ChannelFuture`, but it may not have a `Channel` if the operation fails. 

We proposed a complete removal of `ChannelFuture` in the f2f meeting, and there was no strong objection. More investigation is needed if there are compelling use cases that can’t be accommodated in other ways which may necessitate keeping `ChannelFuture`, but at a minimum will we only use it where absolutely necessary (if at all).

**Comment by ejona86** [comment]
I'm trying to remember the details of this. [gRPC does use](https://github.com/grpc/grpc-java/blob/v1.16.0/netty/src/main/java/io/grpc/netty/NettyClientTransport.java#L251) the "bootstrap returns a ChannelFuture" to discover what the Channel is before it has started. But we also go out of our way to detect the "failed to create case."

I think I remember now. We discussed splitting bootstrap creation into two parts: initialization (create the Channel) and registration. Initialization can happen synchronously whereas registration would remain asynchronous.

**Comment by normanmaurer** [comment]
@ejona86 yes kind of... a Channel should always be constructed with an `EventLoop` and register(...) should just register for IO (like register on an `Selector`). 

So I think in this case bootstrap would return a `Future<Channel>`. 

Does this make thinks more clear ?

**Comment by ejona86** [comment]
`Future<Channel>` isn't enough, as we need to know the `Channel` before `registration()` is 100% complete. (The EventLoop selection needs to have been done, but not the `channelRegistered()` notifications). We need to know the `Channel` synchronously. So just some way to get the `Channel` reference without waiting for `channelRegistered()` notification to complete.

**Comment by normanmaurer** [comment]
@ejona86 got it... this should be easy to do.

**Comment by chrisvest** [comment]
I've been looking through the remaining uses of `ChannelFuture`, and specifically its `channel()` method, which is the one thing that makes them stand out. We're currently able to enjoy potentially allocation-free callbacks like the constants in `ChannelFutureListener`.

To replicate that, including the allocation-freedom, we'd need to attach not only a listener but also a context that will be passed to the listener. This way, the listener can be non-capturing. Something like this:

```java
// Existing method:
Future<V> addListener(GenericFutureListener<? extends Future<? super V>> listener);

// Added method:
<C> Future<V> addListener(C context, GenericFutureListenerCtx<? extends Future<? super V>, C> listener);

// Where GenericFutureListenerCtx defines:
void operationComplete(C context, F future) throws Exception;
```

Having the promise hold on to both the listener and its context without any extra allocation is left as an engineering exercise for … someone.

**Comment by NiteshKant** [comment]
I would say having a custom `Future` type which carries the "context" isn't entirely bad if it is used at an appropriate place. Specially if we have to add a new API for propagating this context, I would start questioning the removal of the custom type. Having said that, I think pursuing low allocations for listeners is a good goal to have.

**Comment by ejona86** [comment]
I've argued before that the `ChannelFutureListener` callbacks should have limited use, as using them from handlers is improper. Handlers should use `ctx` instead of `channel`. So less convenient access to `channel()` from the future may be a blessing.

It seems GenericFutureListenerCtx works equally for `ctx` as `channel`, which is good.
