### ISSUE TITLE
[Netty 5] DefaultChannelPromise / DefaultPromise threading

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#8517]
`DefaultPromise` requires an `EventExecutor` which provides the thread to notify listeners on. `DefaultPromise` currently accounts for the `EventExecutor` being able to change during its lifetime. This complicates the implementation of `DefaultPromise` and in many cases would violate assumptions of the listeners if the thread did change. If we are able to drop support for Channel deregister/re-register we can remove this complexity and improve the efficiency of this class (which provides the basis for asynchronous events in Netty). 

We would like to drop re-registration support which will also simplify promise to not worry about the `EventExecutor` changing.

**Comment by normanmaurer** [comment]
This depends on #8513

**Comment by trustin** [comment]
It'd still be nice if we provide a way to suspend a channel from being handled by its event loop temporarily, so that a user can take the full control of the channel when he or she wants to do something really low-level.

**Comment by normanmaurer** [comment]
@trustin yep that is the plan... It should just be impossible to change the `EventLoop` but register / deregister / register on the same EventLoop should be possible.  When saying register / deregister I am talking about handling IO, `eventLoop()` should always return the `EventLoop` tho.
