### ISSUE TITLE
[Netty 5] VoidChannelPromise / VoidPromise abstraction

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#8518]
This class exists to reduce the overhead of listener notification and maintaining the collections to maintain listeners. However the implementation is viral in that it often requires specific knowledge of the `VoidChannelPromise` type in order to avoid exceptions being thrown in code paths which attempt to add listeners (via `isVoid` and `unVoid` on the `ChannelFuture`|`ChannelPromise`] API).
We would like to remove `VoidChannelPromise` and instead support null (with `@Nullable` annotations) as a substitute. This makes the contract a lot clearer and harder to misuse it.

**Comment by chrisvest** [comment]
`VoidChannelPromise` was removed in #11348.
Shall we close this, or wait for the proposed replacement API, such as in #11378 ?

**Comment by normanmaurer** [comment]
I think we can close this .
