### ISSUE TITLE
[Netty 5] Netty Future should not extend java.util.concurrent.Future

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#8520]
Netty’s `Future` interface extends `java.util.concurrent.Future`. This requires implementing some methods which are more prevalent in blocking applications (e.g. `get(..)`), and also brings some semantics that we may want to avoid (e.g. https://github.com/netty/netty/issues/7712 ).

Nettys `Future` should not extend `java.util.concurrent.Future` and not provide a means to block. We will provide a conversion layer between Netty’s `Future` and the `java.util.concurrent.Future`. Same goes for `CompletionStage` and `CompletableFuture`.

**Comment by hepin1989** [comment]
Built on top of https://docs.oracle.com/javase/9/docs/api/java/util/concurrent/Flow.html ?

**Comment by normanmaurer** [comment]
@chrisvest I guess we can close this one now ?

**Comment by chrisvest** [comment]
Yes. Weird it didn't get closed from the linked pull request.
