### ISSUE TITLE
[Netty 5]: Promise should not extend Future 

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#8522]
Netty’s `Promise` currently extends Netty’s `Future` interface. A common practice is to separate concerns between the `Promise` (writer view) and the `Future` (reader view). The `Promise` can have a method which provides the `Future` view of that `Promise`, but doesn’t necessarily have to extend `Future`. 

We want to change this to match what is often done by have these separate interfaces but allow to get a `Future` which belongs to a Promise (but not the other way around).  
Something like `toFuture()`.

**Comment by eolivelli** [comment]
Do you have considered CompletableFuture or at least CompletionStage?

**Comment by normanmaurer** [comment]
@eolivelli yes... Honestly I am not a big fan of these. That said I think we should allow to convert between our type and these easily

**Comment by eolivelli** [comment]
The best would be not to need to have a memory allocation but this would imply that Netty Promise/Future extend CompletableFuture, and this will be tricky and I guess not feasible at all.

**Comment by normanmaurer** [comment]
@eolivelli yeah not sure if this would be possible. That said with https://github.com/netty/netty/pull/8680 you would be able to extend `SingleThreadEventLoop` and so  override the implementation of promise / future that is used.
