### ISSUE TITLE
[Netty 5] Future cancellation 

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#8524]
Cancellation on the `Future` API has different meanings for different use cases. For example in I/O at some point we disable cancellation, and often have conditional checks spread throughout the code to check if a `Future` is still cancellable. However for scheduled operations cancellation may always be valid. Cancellation creates complexity in the I/O path and may not even make sense for ordered protocols. 

We will not support cancellation for I/O operations, but we will support cancellation for scheduled operations.

**Comment by rkapsi** [comment]
What about scenarios as the following. Some heavyweight side task we want to execute on a dedicated but potentially constrained thread pool. Kind of embracing eventual consistency here. If a hypothetical client remains connected then it'll eventually produce the value. If a client disconnects though then we'd like to cancel the Future.

```java
Future<T> execute(Supplier<T> heavyweight, Promise<T> promise) {
  executor.execute(new Runnable() {
    @Override
    public void run() {
      if (!promise.isDone()) {
        promise.trySuccess(heavyweight.get());
      }
    }
  });
  return promise;
}
```

**Comment by normanmaurer** [comment]
I think there is nothing that stops you from this as long as you hold a reference to the `Promise`. The important is that `Future` should be "read-only".

**Comment by rkapsi** [comment]
ACK. But I wonder if in terms of API it's valid for a consumer to be able to signal that they're no longer interested in the future computation.

**Comment by normanmaurer** [comment]
@rkapsi in future computation yes... thats why I said `We will not support cancellation for I/O operations, but we will support cancellation for scheduled operations.`

**Comment by normanmaurer** [comment]
@rkapsi yes

**Comment by rkapsi** [comment]
Just a little snag, ScheduledFuture don't have a ScheduledPromise counterpart. One of the things I like about the Future/Promise API is that one has great control over the callback Thread.

If the existing ScheduledFuture is kept as is without a ScheduledPromise counterpart then all scheduled things trying to accomplish what my little sample code shows will require some synchronized handoff from the listener to the Channel's event loop.

**Comment by hepin1989** [comment]
`Task` ,`Promise` and `Future`

**Comment by chrisvest** [comment]
If the idea is to make `ChannelOutboundInvoker` return a different kind of future that doesn't have the `cancel()` method, then we would see the return of the complexity we got rid of by removing `ChannelFuture`. We won't have a single `Future` type anymore.

I think that complexity would be worse than the current complexity of having various `*Channel.*Unsafe` implementations check for and deal with cancellation, because multiple future types shows up in the API and usage sites. Meanwhile, the complexity of handling cancellation only shows up in our internal implementations, which currently already handle this.

So I'm not sure if the status quo can be improved upon.

**Comment by NiteshKant** [comment]
I agree with @chrisvest here, I do not think removing `cancel()` is worth the hassle.

**Comment by chrisvest** [comment]
Talked with Norman off-line, and he was also in agreement. I'll go ahead and close thi. It can be revived if there's more to discuss.
