### ISSUE TITLE
[Netty 5] Drop support for WebSocket drafts 

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#8529]
Netty contains support for early websockets drafts but we should only support the final rfc

**Comment by trustin** [comment]
Sounds good to me, but I'm curious if it reduces how much of complexity in terms of public API. If it doesn't change much perhaps we can leave them in the dark corner for backward compatibility's sake?

**Comment by normanmaurer** [comment]
I am not strong on this... @vietj @smaldini @slandelle @mosesn @vkostyukov WDYT ?

**Comment by slandelle** [comment]
I'm the one who suggested this, I'm still for in favor of it. I have never met an AsyncHttpClient user who was still using a draft version. Stable spec was release end of 2011.

**Comment by normanmaurer** [comment]
This was done by @NiteshKant
