### ISSUE TITLE
[Netty 5] ByteBuf should be an interface

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#8534]
`ByteBuf` is currently an abstract class with no state. `CompositeByteBuf` is a concrete class and could be made to have no state. Before java 1.8 this allowed for evolving the interface over time, but java 1.8 provides support for default methods on interfaces. Having both of these classes be interfaces would make it easier to mock/wrap these classes and ensure all required methods are being implemented.

**Comment by ijuma** [comment]
Also need to verify that performance doesn't suffer from using `invokeinterface` instead of `invokevirtual`.

**Comment by trustin** [comment]
We need to keep the number of `ByteBuf` implementations that actually show up during runtime as small as possible. Maybe some test-time test?

**Comment by normanmaurer** [comment]
@trustin what you mean with test-time test ?

**Comment by vietj** [comment]
@trustin do you mean for jit efficiency ?

**Comment by trustin** [comment]
> @trustin do you mean for jit efficiency ?

Yes. To remove the chance of megamorphic invocations.

> @trustin what you mean with test-time test ?

Running some test traffic and see if the limited number of `ByteBuf` implementations are passed to handlers? Just an idea though.

**Comment by ninja-** [comment]
yeah, it _was_ an interface before and the reason one of you changed it to be abstract class was performance...

> Also need to verify that performance doesn't suffer from using invokeinterface instead of invokevirtual.
