### ISSUE TITLE
[Netty 5] Default PooledByteBufAllocator configuration

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#8536]
Default memory per chunk that the arena allocates is 16MB. We allocate 2 times number of arenas for direct and for heap buffers. This can be a large amount of memory for applications that may not need it. We should consider reducing the default values to reduce the initial memory footprint, and applications can tune the allocator if they need more chunks.

**Comment by vkostyukov** [comment]
👍 

We [override these in Finagle](https://github.com/twitter/finagle/blob/develop/finagle-netty4/src/main/scala/com/twitter/finagle/netty4/Netty4Init.scala#L30-L60) for the very same reason.

**Comment by normanmaurer** [comment]
@chrisvest want to have a look ?

**Comment by chrisvest** [comment]
@normanmaurer Yeah, I'll make a note to look at this soon.
