### ISSUE TITLE
[Netty 5] Revisit ReferenceCounted 

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#8543]
We currently make heavy use of `ReferenceCounted` with netty. This especially true for our `ByteBuf` abstraction. We should revisit and see if this is still needed or if for example using the new `Cleaner` will be just good enough. Using reference counted APIs is hard and is especially confusing for people that dont have C background.

That said we need to ensure the performance hit (if any) that we take is not to big and outweighs the wins of the removal in general.

**Comment by Bennett-Lynch** [comment]
I find this particularly interesting. Could someone elaborate on why this would be a feasible option now, as opposed to before? Removing the need for reference counting would be a huge win.

**Comment by normanmaurer** [comment]
@normanmaurer mostly because the JVM did make multiple improvements in terms of GC. That said after some initial tests I am not really optimistic we can remove it :/
