### ISSUE TITLE
The difference between netty3 and netty4 default threads

### ISSUE THREAD

**Issue by psxbmbb** [netty/netty#8559]
Can anyone tell me why the worker thread in netty3 defaults is core+1 but netty4 is core*2?
Many thanks.

**Comment by normanmaurer** [comment]
Actually it is also core * 2 in netty3:

https://github.com/netty/netty/blob/3.10/src/main/java/org/jboss/netty/channel/socket/nio/SelectorUtil.java#L31

That said what is a good value depends highly on your application.
