### ISSUE TITLE
[Question] Possible race condition on AbstractReferenceCounted

### ISSUE THREAD

**Issue by merlimat** [netty/netty#8563]
I'm investigating an issue with a custom object that inherit from `AbstractReferenceCounted` and looking at the code I got one doubt. 

My expectation is that after calling `retain()`, if I didn't get an exception, the object should be guaranteed not to be deallocated. 

Looking at the retain and release methods:

https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/common/src/main/java/io/netty/util/AbstractReferenceCounted.java#L54-L62

https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/common/src/main/java/io/netty/util/AbstractReferenceCounted.java#L79-L90

The scenario I was considering is : 
 1. Object has `refCnt==1`
 2. We have 3 threads playing with this object 
 3. Thread-1 calls `obj.release()`
 4. Thread-2 calls `obj.retain()` and sees the `oldRef==0` then rolls back the increment (but the rollback is not atomic)
 5. Thread-3 calls `obj.retain()` and sees `oldRef==1` (from T-2 increment) therefore thinks the object is not dead
 6. Thread-1 will call `obj.deallocate()`

Is this a possible scenario or am I missing something?

Would it make a difference to use a loop and compareAndSet() (which could probably have a perf penalty)?

**Comment by normanmaurer** [comment]
@carl-mastrangelo PTAL

**Comment by carl-mastrangelo** [comment]
@merlimat yes, but at least one thread does see an exception.  This was mentioned on the original PR.  Also, IIRC, the quiescent state still ends up at the same ref count of zero.  

I don't think it's really a recoverable scenario.   The Linux Kernel uses CAS and makes sure all `retain` calls starting from 0 stay at 0, and all `release` calls from INT_MAX stay at INT_MAX.    Netty could copy this if it wants to pay the performance penalty, but from my point of view, the ref counting is not meant to be water-tight.

**Comment by merlimat** [comment]
(I hadn't actually checked the PR description for that change)

> yes, but at least one thread does see an exception. 

Yes, in my above example T-1 will get exception but T-2 will not.

> Netty could copy this if it wants to pay the performance penalty, but from my point of view, the ref counting is not meant to be water-tight.

The problem is that I have no way to validate that my object is still valid after calling `retain()`. Eg: we might have ByteBuf pointing to garbage data or leading to NPEs. 

Sure, this only happens with 3+ threads but I don't see a workaround to it.

**Comment by carl-mastrangelo** [comment]
> The problem is that I have no way to validate that my object is still valid after calling retain()

A reasonable alternative is to call `System.exit` on getting a ref count exception.

**Comment by merlimat** [comment]
> A reasonable alternative is to call System.exit on getting a ref count exception.

Take this code for example: 
 * This is a cache of entries
 * The cache keeps 1 ref count to always keep the entry valid. 
 * Whenever we try to get 1 entry out of the cache, we retain() the entry so that if it's being evicted we either get it or we get an exception 

https://github.com/apache/pulsar/blob/579e0dc74039c081301662e5fd55209c1a4abe5c/managed-ledger/src/main/java/org/apache/bookkeeper/mledger/util/RangeCache.java#L83-L96

**Comment by njhill** [comment]
@merlimat the scenario you described doesn't sound right to me. I think there should be no problems of this kind if you are only releasing/retaining a single ref at a time (as is most common and looks like the case for you here).

Thread-3 should not see `oldRef==1` in step 5, it should see `oldRef==0` or possibly `oldRef==-1`, since T-2's rollback is incrementing from -1 back to 0.

**Comment by carl-mastrangelo** [comment]
From my reading, that code isn't valid.   Catching and discarding throwable is going to cause problems anyways.   ReferenceCounted doesn't really say what should happen in the event of errors, likely because different implementations might want different behavior.  

It's hard to see this as a bug when there isn't expected behavior.   Ensuring that every retain/release throws upon reaching an invalid state is costly, and not every use may want to pay that cost.   

Additionally, you have a reasonable work around:  You could wrap the objects in your cache in a custom implementation of ReferenceCounted and rely on the exact error behavior you want.

**Comment by merlimat** [comment]
> Additionally, you have a reasonable work around: You could wrap the objects in your cache in a custom implementation of ReferenceCounted and rely on the exact error behavior you want.

I can certainly fix that by having a different `AbstractReferenceCounted` base class, though my concern is that this will still apply to `ByteBuf` instances coming from a pool, where I cannot asses whether the buffer is pointing to valid data or not.

**Comment by carl-mastrangelo** [comment]
> though my concern is that this will still apply to ByteBuf instances coming from a pool, where I cannot asses whether the buffer is pointing to valid data or not.

Looking more thoroughly at that code, it seems the issue is that adding/remove values from the cache, and retain/releasing them is not done atomically.   If it were the case, you could use wrapper objects to do the ref counting and not have to extend or override the Value objects.

**Comment by merlimat** [comment]
@carl-mastrangelo would it work to have some system property to control which implementation is being used?

**Comment by carl-mastrangelo** [comment]
@merlimat I'm reluctant to make it configuration based, because that tends to not play well in Netty is shaded.   It could work, though I can't make that call.

**Comment by merlimat** [comment]
Would it make sense to have option for both strict and relaxed semantic in `ReferenceCounted` interface? 

Eg: 
 * `void retain()`  -> requires the object to have `refCnt >= 1`, otherwise undefined behavior
 * `boolean tryRetain()` -> return true if it was able to keep the object alive, false otherwise (and no exception)

**Comment by normanmaurer** [comment]
@merlimat @carl-mastrangelo I think I have an idea how to fix this which will still give good performance in the happy path. Stay tuned.

**Comment by normanmaurer** [comment]
never mind this does not work :( 

@carl-mastrangelo I think we need to revert 83a19d5 as it clearly breaks what we is documented in the  api docs :( I tried to come-up with a way to at least retain some of the performance wins but did not find any good way that still guarantee correct semantics in all cases.

**Comment by normanmaurer** [comment]
@carl-mastrangelo just to be more clear I think we need to guarantee that once an object was released (which means `release(...)` returned true) all other calls to `release(....)` and `retain(...)` must throw.

**Comment by njhill** [comment]
@carl-mastrangelo @normanmaurer not sure this is of interest but I thought of a way to retain roughly half of the speedup and address _most_ of the race condition problems, see 0c0e092e8588d5c6729080b5ae7345e041470616. Apologies if this is just the same as your already-dismissed idea.

In particular this guarantees @normanmaurer's above requirement in all cases and also ensures there can never be a double de-allocation (as is possible with the current logic). However, it can suffer from some of the existing problems if releases coincide with retains overflowing (above `Integer.MAX_VALUE + 1`). Maybe that still disqualifies it for consideration, in which case nevermind!

A couple of other observations:
- Although the original "optimistic add" optimization improves the most highly contended cases, it actually harmed uncontended cases which I was wondering may actually be more common? maybe in those cases latency generally isn't as important?
- If any CAS loop is going to be used (e.g. if reverting to the originally logic), a small optimization could be to use a non-volatile read for the first try (as done in the above commit)

**Comment by normanmaurer** [comment]
@njhill will need to check in detail. In the meantime PTAL https://github.com/netty/netty/pull/8574

**Comment by normanmaurer** [comment]
@njhill @merlimat @carl-mastrangelo also somewhat related to this issue: https://github.com/netty/netty/issues/8576
