### ISSUE TITLE
Why Netty4 **boss thread** was dead? 

### ISSUE THREAD

**Issue by pez1420** [netty/netty#8565]
### Actual behavior
 Api Gateway of network IO model of our company was implemented by Netty4.1.25. Now, We used **Jmeter** that is a performance testing tool to  run a 90K concurrent users test, and then linux kenel parameter of  **Max Open Files(ulimit -n)** is modified  to 10K. 

Boss threads and Worker threads configuration:
+ **Boss threadpools** have just only one thread, which was used to  accept incoming connections;
+ **Worker threadpools**  have 4 worker threads(currently default 2*number of cores), which was used to performs non-blocking I/O for one or more Channels  and complex bussiness logic.

We had defined a **ChannelHandler** used to run **complex bussiness logical**,and logical mainly including flow control, concurrency, circuit breaking and load protection, to protect service reliability.

Finally, we got a testing result:
+ Boss thread was terminated(** jstack pid**), But it didn't throw any exception and print error logs.
+ Two of the worker thread was terminated. But,  it also didn't throw any exception and print error logs.

### Steps to reproduce

we got boss thread was abored by **jstack --pid** tools, and find some valuable information of **ChannlePipeline**.

>A user is supposed to have one or more ChannelHandlers in a pipeline to receive I/O events (e.g. >read) and to request I/O operations (e.g. write and close). For example, a typical server will have >the following handlers in each channel's pipeline, but your mileage may vary depending on the >complexity and characteristics of the protocol and business logic.

It means that if **ChannelHandler** performed  complex business logic (such as  time-consuming network communication, querying databases, redis connection and so on),  IO worker thread may will be **blocked**.

Therefore, we  execute the blocking calls in DefaultEventExecutorGroup and create custom threadpool that can be added to when the handler is added

```java
        ServerBootstrap serverBootstrap = new ServerBootstrap();

        serverBootstrap
            .group(this.proxyThreadPools.getClientToProxyAcceptorPool(),
                proxyThreadPools.getClientToProxyWorkerPool())
            .channel(NioServerSocketChannel.class)
            .childHandler(new ChannelInitializer<SocketChannel>() {
                @Override
                protected void initChannel(SocketChannel ch) throws Exception {
                    ch.pipeline().addLast(new LoggingHandler(LogLevel.DEBUG))
                        .addLast(newHttpServerCodec())
                        .addLast(new HttpObjectAggregator(
                                serverConfig.getHttpServerAggregatorMaxContentLength())) //15728640
                        .addLast(new HttpContentCompressor())
                        .addLast(new IdleStateHandler(0, 0,
                            serverConfig.getHttpServerChannelIdleTimeOut()))
                        .addLast(proxyThreadPools.getBusinessWorkerPool(), new ClientToProxyHandler(
                            requestSender, serverConfig, httpFiltersProvider));
                }
            }).option(ChannelOption.TCP_NODELAY, true);
```

The problem is solved , when we create custom **bussiness threadpool** to proccess time-consuming Handler.
```
proxyThreadPools.getBusinessWorkerPool()

EventExecutorGroup  businessWorkerPool = new DefaultEventExecutorGroup(businessWorkerThreads,
            new NameableThreadFactory(serverGroupName, "BusinessWorker", serverGroupId));
```

I still had some questions:
+  Where does the boss thread(NioEventLoop) abort may occur? Now, I am debugging code  of **NioEventLoop**, But I am still not sure.
+ How do I print  NioEventLoop aborted errors to log? Did it has some effective ways or netty configuration?
+ How do I  implement and degisn the boss/worker thread monitoring in netty4?

### Netty version
4.1.25.final

### JVM version (e.g. `java -version`)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)

### OS version (e.g. `uname -a`)
Linux hz-bd-gw-199-137-180 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pez1420** [comment]
@normanmaurer

**Comment by normanmaurer** [comment]
@pez1420 

> Where does the boss thread(NioEventLoop) abort may occur? Now, I am debugging code of NioEventLoop, But I am still not sure.

It should only happen when you shutdown the `NioEventLoop`. You may want to adjust the netty log level to debug for `NioEventLoop` to see if anything is logged.

> How do I print NioEventLoop aborted errors to log? Did it has some effective ways or netty configuration?

See above.

How do I implement and degisn the boss/worker thread monitoring in netty4?

> Depends on what exactly you want to monitor. Please provide more infos.

**Comment by normanmaurer** [comment]
Closing as no followup... also please upgrade to latest netty release
