### ISSUE TITLE
Allow adjusting the sampling rate of ResourceLeakDetector v2

### ISSUE THREAD

**Issue by tjake** [netty/netty#8567]
Hi!

Same request as #1970.

We have a highly cpu bound netty workload and we see the stacktrace generated by leak sampling takes ~1% of the flamegraph.  I'd really like to be able to adjust this to 0.1%.

It would be a very [small change](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/ResourceLeakDetector.java#L129)

**Comment by normanmaurer** [comment]
@tjake system property is good enough ?

**Comment by tjake** [comment]
Yeah :+1:

**Comment by normanmaurer** [comment]
@tjake can you submit a pr ?

**Comment by tjake** [comment]
will do!

**Comment by normanmaurer** [comment]
@tjake <3

**Comment by normanmaurer** [comment]
This was fixed by #8574
