### ISSUE TITLE
Testsuite throws "leader premature close"

### ISSUE THREAD

**Issue by cooooderr** [netty/netty#8571]
When trying to build netty 4.1.32.Final-SNAPSHOT on windows 10, testsuite fails because something throws an exception with message "leader premature close".

**Comment by normanmaurer** [comment]
@cooooderr actually I think the test only works on Linux / BSD. Is this the only one that fails ?

**Comment by cooooderr** [comment]
Yes

**Comment by normanmaurer** [comment]
Got it ... this makes sense. Let me add some code to skip this test on windows
