### ISSUE TITLE
 A little doubt about the EPOLL WAIT method.

### ISSUE THREAD

**Issue by carryxyh** [netty/netty#8585]
Hi, community,

The netty_epoll_native_epollWait0 method uses timerfd to control the timeout. But epoll_wait can specify the wait time directly in the parameters. Why don't we use epoll_wait directly instead of timerfd?

code like this:

```
do {
    result = epoll_wait(efd, ev, len, tcSec);
    return result;
} while((err = errno) == EINTR);
```

**Comment by normanmaurer** [comment]
@carryxyh because timerfd allows for nanoseconds ;)

**Comment by carryxyh** [comment]
Thx a lot :)
Very fast response speed!
