### ISSUE TITLE
 A question about EPOLLBUSYWAIT.

### ISSUE THREAD

**Issue by carryxyh** [netty/netty#8586]
I am very sorry that I have just submitted an issue.

When do we currently call io.netty.channel.epoll.EpollEventLoop#epollBusyWait? Code:

`Int strategy = selectStrategy.calculateStrategy(selectNowSupplier, hasTasks());`

It will be executed when strategy = -3. But for now, it only returns -1 or a number greater than or equal to 0. Will not return -3.

Is this place a problem I understand or is it really impossible to reach epollbusywait?

**Comment by carryxyh** [comment]
Somebody here?
:0

**Comment by normanmaurer** [comment]
You can use your own `SelectStrategy` implementation.

**Comment by carryxyh** [comment]
thank you for your reply.
Maybe I should try to customize my own SelectStrategy.
