### ISSUE TITLE
udt of netty 4.x is remove？

### ISSUE THREAD

**Issue by zhanfffmmm** [netty/netty#8588]
I want to use to udt of netty 4.x, but  heard that netty 5 does not support UDT. udt of netty 4.x is remove？

**Comment by johnou** [comment]
It is deprecated in 4.x, see https://github.com/netty/netty/pull/8578 for the reason(s).

**Comment by normanmaurer** [comment]
as @johnou said... its deprecated and will be removed.

**Comment by zhanfffmmm** [comment]
@johnou @normanmaurer  thanks, I see.
