### ISSUE TITLE
[Netty 5] ByteBuf methods to respect reader/writer indexes

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#8601]
`ByteBuf` has some `get*` methods which do not respect the reader/writer indexes, and instead only respect the capacity of the buffer. This may result in accessing uninitialized memory and lead to unexpected results. I would propose that by default we have methods respect the reader/writer indexes and only if necessary expand the `ByteBuf` API to include methods which ignore the reader/writer index (e.g. new methods, optional parameter, etc...).

[1] https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/ByteBuf.java#L810-L813

**Comment by ejona86** [comment]
+1

**Comment by trustin** [comment]
+1
