### ISSUE TITLE
Example HttpStaticFileServerHandler: raf is not closed.

### ISSUE THREAD

**Issue by yao-qingdong** [netty/netty#8604]
Recently I use this HttpStaticFileServerHandler as file server, but I can't download mp4 file correctly. Then I found raf is not closed.

There is a issue mention about it: https://github.com/netty/netty/issues/2235, but it seems don't fix it.

I asked about it at stackoverflow: https://stackoverflow.com/questions/53500128/netty-httpstaticfileserverhandler-problem/53511572#53511572

Here is my change,and it's working.

    RandomAccessFile raf;
        try {
            raf = new RandomAccessFile(file, "r");
        } catch (FileNotFoundException ignore) {
            sendError(ctx, NOT_FOUND);
            return;
        }

    ...

    sendFileFuture.addListener(new ChannelProgressiveFutureListener() {
            @Override
            public void operationProgressed(ChannelProgressiveFuture future, long progress, long total) 
    {
                if (total < 0) { // total unknown
                    System.err.println(future.channel() + " Transfer progress: " + progress);
                } else {
                    System.err.println(future.channel() + " Transfer progress: " + progress + " / " + total);
                }
            }

            @Override
            public void operationComplete(ChannelProgressiveFuture future) {
                System.err.println(future.channel() + " Transfer complete.");
                raf.close();// close raf when transfer completed
            }
        });

**Comment by normanmaurer** [comment]
@yqd1992 want to do a PR and submit it to receive contribution?

**Comment by yqd1992** [comment]
I think it's need to be fixed. There is no use to create a pull request for me, it's a small change.

**Comment by normanmaurer** [comment]
oh ok... I will fix it then. I thought you may want to receive the contribution.

**Comment by samaitra** [comment]
@normanmaurer I have raised PR https://github.com/netty/netty/pull/8643 for the fix. Please let me know if you have any feedback.

**Comment by normanmaurer** [comment]
As I mentioned in the PR I think this fix is not "correct" Please provide a reproducer and we can fix it tho. Closing it for now
