### ISSUE TITLE
Could it be possible to make the `WebSocketClientHandshaker` reusable without creating a new instance of it ?

### ISSUE THREAD

**Issue by 391861737** [netty/netty#8607]
Hi all.
### Expected behavior
It might rather be an improvement than an issue that the boolean flag `io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker#handshakeComplete` could be set to `false` again while starting a re-connecting process, so that we do not need to create a new instance of a sepcific `WebSocketClientHandshaker` again.
### Actual behavior
It does not do what was mentioned above. Methods access the `handshakeComplete` flag only set it to `true` flatly or read it's value.
### Steps to reproduce
It might not need any reproduction.
### Minimal yet complete reproducer code (or URL to code)
Same as above.
### Netty version
4.1.24.Final (And I've inspected the master branch seeing the behavior of the flag `handshakeComplete` the same as 4.1.24.Final)
### JVM version (e.g. `java -version`)
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
### OS version (e.g. `uname -a`)
Windows 7 [service pack 1]

**Comment by normanmaurer** [comment]
I think we should just keep it as it is. I dont see big benefits here.
