### ISSUE TITLE
Out of Direct Memory because of IdleStateHandler

### ISSUE THREAD

**Issue by LiangKongRong** [netty/netty#8608]
### Expected behavior
When I use netty as a server, I use IdleStateHandler to keep heartbeat for each client. When a lot of clients connected the server should works fine.

### Actual behavior
When a lot of clients connected, the server raised OutOfDirectMemoryError. 

### Steps to reproduce
1. Create instance of IdleStateHandler to make readeridle time bigger than 0.
      new IdleStateHandler(60, 0, 0, TimeUnit.SECONDS)
2. Connect a lot of clients to the server.

### Netty version
4.1.6 Final

### JVM version (e.g. `java -version`)
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### OS version (e.g. `uname -a`)
Linux PW6J1216 3.0.101-63-default #1 SMP Tue Jun 23 16:02:31 UTC 2015 (4b89d0c) x86_64 x86_64 x86_64 GNU/Linux

######################################################
I found this issue is because of the state was not well protected in multi-thread enviroment.
The code io.netty.handler.timeout.IdleStateHandler.java(from version 4.1.6 to netty-all-5.0.0.Alpha2):
`

     private void initialize(ChannelHandlerContext ctx) {
        switch (state) {   // Mark A. Here can reach many times
        case 1:
        case 2:
            return;
        }

       state = 1;   // Mark B. Here can reach many times

        EventExecutor loop = ctx.executor();

        lastReadTime = lastWriteTime = System.nanoTime();
        if (readerIdleTimeNanos > 0) {
            readerIdleTimeout = loop.schedule(
                    new ReaderIdleTimeoutTask(ctx),  // Mark C. Here can reach many times
                    readerIdleTimeNanos, TimeUnit.NANOSECONDS);
        }
        if (writerIdleTimeNanos > 0) {
            writerIdleTimeout = loop.schedule(
                    new WriterIdleTimeoutTask(ctx),  // Mark D. Here can reach many times
                    writerIdleTimeNanos, TimeUnit.NANOSECONDS);
        }
        if (allIdleTimeNanos > 0) {
            allIdleTimeout = loop.schedule(
                    new AllIdleTimeoutTask(ctx), // Mark F. Here can reach many times
                    allIdleTimeNanos, TimeUnit.NANOSECONDS);
        }
    }
`

When code executing in multi-thread ENV, many threads can reach the place of Mark A/Mark B at the same time(in both version of 4.1.6 and even the lastest version netty-all-5.0.0.Alpha2), so the place mark as Mark C/D/F can reach many times. I found code changed in netty-all-5.0.0.Alpha2, the member state changed from "private int state" to "private volatile int state", but it still not multi-thread safe. I prefer to change it to "private AtomicInteger state = new AtomicInteger(0)", here is my code:

`
public class IdleStateHandler extends ChannelDuplexHandler {
...
    private AtomicInteger state = new AtomicInteger(0); // 0 - none, 1 - initialized, 2 - destroyed
...
    private void initialize(ChannelHandlerContext ctx) {
        if(state.compareAndSet(0, 1)) {
            EventExecutor loop = ctx.executor();

            lastReadTime = lastWriteTime = System.nanoTime();
            if (readerIdleTimeNanos > 0) {
                readerIdleTimeout = loop.schedule(
                        new ReaderIdleTimeoutTask(ctx),
                        readerIdleTimeNanos, TimeUnit.NANOSECONDS);
            }
            if (writerIdleTimeNanos > 0) {
                writerIdleTimeout = loop.schedule(
                        new WriterIdleTimeoutTask(ctx),
                        writerIdleTimeNanos, TimeUnit.NANOSECONDS);
            }
            if (allIdleTimeNanos > 0) {
                allIdleTimeout = loop.schedule(
                        new AllIdleTimeoutTask(ctx),
                        allIdleTimeNanos, TimeUnit.NANOSECONDS);
            }
        }
    }

    private void destroy() {
        state.set(2);

        if (readerIdleTimeout != null) {
            readerIdleTimeout.cancel(false);
            readerIdleTimeout = null;
        }
        if (writerIdleTimeout != null) {
            writerIdleTimeout.cancel(false);
            writerIdleTimeout = null;
        }
        if (allIdleTimeout != null) {
            allIdleTimeout.cancel(false);
            allIdleTimeout = null;
        }
    }

...

}`

**Comment by amizurov** [comment]
@LiangKongRong HI, Do you use ```IdleStateHandler``` in shared mode or create new instance per channel ?

**Comment by normanmaurer** [comment]
@LiangKongRong like @amizurov suggested this sounds more like a missusage. Can you you confirm how you use it ?

**Comment by LiangKongRong** [comment]
Thanks @amizurov , new instance per channel.

Thanks @normanmaurer .

We use IdleStateHandler when connecting request recieved. The code is something like `ctx.channel().pipeline().addFirst(new IdleStateHandler(600, 0,0)) ;` in the channelRead0() method of a sub class of SimpleChannelInboundHandler. When 160K clients connected, normally the instance number of 
 ReaderIdleTimeoutTask should be 160K because nubmer of IdleStateHandler is 160K, but I got 16000K ReaderIdleTimeoutTask. Finally when I fixed this with my code, ReaderIdleTimeoutTask drop to 160K.

Sorry, Out of direct memory was not because of this bug. I am still investingating for the root. I think it may be cause by to many direct memory pooled in the stack.

**Comment by normanmaurer** [comment]
@LiangKongRong are you sure this issue is still present in 4.1.32.Final which is the latest version of netty that was released ?. 

`initialize(..)` and `destroy(...)` should never be called concurrently and always from the same thread. So I don't see why you would need an atomic here.

**Comment by LiangKongRong** [comment]
@normanmaurer We add a new IdleStateHandler() in channelActive(ChannelHandlerContext ctx) method of  another handler, I am not sure if it was misused. I see most code add handlers in ChannelInitializer. I will check this in version 4.1.32.Final later. Thanks.

**Comment by LiangKongRong** [comment]
@normanmaurer I found the root cause of Out Of Direct Memory. We send BinaryWebSocketFrame by writeAndFlush() of a nio channel in my thread, and direct memory allocated in this thread. But when the message sent out, the direct memory cached inside the netty event loop thread. Direct memory exhaust when a lot of direct memory allocated in my thread and cached in netty event loop thread. I fixed my code to make writeAndFlush() executing inside event loop thread. But I think it will better if writeAndFlush() can do something to make it safer. Unspoken rules is not user friendly.

**Comment by johnou** [comment]
@amizurov if you want the read timeout to be per channel it cannot be shared because the handler has a state.

**Comment by amizurov** [comment]
@johnou, sorry the message above to me ?

**Comment by amizurov** [comment]
@normanmaurer If I correct understand that different between execution in eventLoop and in separate thread that we create ``WriteAndFlushTask.newInstance(next, m, promise);`` and reserved memory for this task``ctx.pipeline.incrementPendingOutboundBytes(task.size);`` so this is can change channel writability, maybe this is root of problem ?

**Comment by johnou** [comment]
@amizurov I was just pointing out that if you want to d/c clients that stop writing to the socket a new IdleStateHandler is required per session to detect this.

**Comment by LiangKongRong** [comment]
@normanmaurer Merry Christmas. I am sorry, most of the instances of io.netty.util.concurrent.ScheduledFutureTask is unreachable, I use JVisualVM tool inside JDK before it cannot identify reachable/uncheachable state. I used another tool (Eclipse MAT), the number of reachable instances is normal. But I have another question: It seems schedule new task in IdleStateHandler by method schedule() instead for scheduleAtFixedRate() or scheduleWithFixedDelay() can make the timeout most precise, but as a result many many tasks created. In my application 40% instances are io.netty.util.concurrent.ScheduledFutureTask and io.netty.util.concurrent.PromiseTask$RunnableAdapter, I think it increase the precessure of GC. If application can except timeout not so precise, scheduleAtFixedRate() or scheduleWithFixedDelay() would be better choise.

Thanks everybody too. @amizurov @johnou @medusar

**Comment by normanmaurer** [comment]
@LiangKongRong I am happy to review a PR ... Please provide one if you think you can improve it.
