### ISSUE TITLE
Help： LEAK: ByteBuf.release() was not called before it's garbage-collected

### ISSUE THREAD

**Issue by strongmanwj** [netty/netty#8625]
### Expected behavior
No leak 
### Actual behavior
1. when  server  processed devliery msg，many leaks happened
2 some  log ，many are duplicate：
2018-12-05 14:44:13 518[ERROR][ResourceLeakDetector.java-311][nioEventLoopGroup-3-3]-LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
	io.netty.buffer.AdvancedLeakAwareByteBuf.duplicate(AdvancedLeakAwareByteBuf.java:112)
	com.woai.ulc.channelserver.codec.UlcEncoder.encodeDeliveryReqMsg(UlcEncoder.java:159)
	com.woai.ulc.channelserver.codec.UlcEncoder.doEncode(UlcEncoder.java:76)
	...
Created at:
	io.netty.buffer.SimpleLeakAwareByteBuf.unwrappedDerived(SimpleLeakAwareByteBuf.java:143)
	io.netty.buffer.SimpleLeakAwareByteBuf.readRetainedSlice(SimpleLeakAwareByteBuf.java:67)
	io.netty.buffer.AdvancedLeakAwareByteBuf.readRetainedSlice(AdvancedLeakAwareByteBuf.java:107)
	io.netty.handler.codec.ReplayingDecoderByteBuf.readRetainedSlice(ReplayingDecoderByteBuf.java:589)
	com.woai.ulc.channelserver.codec.UlcDecoder.decodeDeliveryReqPayload(UlcDecoder.java:353)
	...
	
: 1 leak records were discarded because they were duplicates
: 42 leak records were discarded because the leak record count is targeted to 4. Use system property io.netty.leakDetection.targetRecords to increase the limit.
2018-12-05 14:44:13 695[ERROR][ResourceLeakDetector.java-311][nioEventLoopGroup-3-2]-LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:286)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1432)
	io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1211)
	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1245)
	..
#2:
	io.netty.buffer.AdvancedLeakAwareByteBuf.readUnsignedByte(AdvancedLeakAwareByteBuf.java:406)
	io.netty.handler.codec.ReplayingDecoderByteBuf.readUnsignedByte(ReplayingDecoderByteBuf.java:523)
	com.woai.ulc.channelserver.codec.UlcDecoder.decodeMsbLsb(UlcDecoder.java:455)
	...
#3:
	io.netty.buffer.AdvancedLeakAwareByteBuf.toString(AdvancedLeakAwareByteBuf.java:748)
	io.netty.handler.codec.ReplayingDecoderByteBuf.toString(ReplayingDecoderByteBuf.java:912)
	com.woai.ulc.channelserver.codec.UlcDecoder.decodeConnectReqPayload(UlcDecoder.java:378)
	...
#4:
	io.netty.buffer.AdvancedLeakAwareByteBuf.internalNioBuffer(AdvancedLeakAwareByteBuf.java:736)
	io.netty.handler.ssl.SslHandler.toByteBuffer(SslHandler.java:1442)
	...
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:1912)
	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1292)
	
#2:
	io.netty.buffer.AdvancedLeakAwareByteBuf.readUnsignedByte(AdvancedLeakAwareByteBuf.java:406)
	io.netty.handler.codec.ReplayingDecoderByteBuf.readUnsignedByte(ReplayingDecoderByteBuf.java:523)
	com.woai.ulc.channelserver.codec.UlcDecoder.decodeMsbLsb(UlcDecoder.java:454)
#3:
	io.netty.buffer.AdvancedLeakAwareByteBuf.readByte(AdvancedLeakAwareByteBuf.java:400)
	io.netty.handler.codec.ReplayingDecoderByteBuf.readByte(ReplayingDecoderByteBuf.java:517)
	com.woai.ulc.channelserver.codec.UlcDecoder.decodeFixedHeader(UlcDecoder.java:198)
#4:
	Hint: 'UlcDecoder' will handle the message from this point.
	io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:116)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
#5:
	io.netty.buffer.AdvancedLeakAwareByteBuf.internalNioBuffer(AdvancedLeakAwareByteBuf.java:736)
	io.netty.handler.ssl.SslHandler.toByteBuffer(SslHandler.java:1442)
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)

### Steps to reproduce
1. my server handlerchain：
sslHandler->UlcDecoder->ServiceProcessHandler->UlcEncoder
2.UlcDecoder and UlcEncoder is similar to MQTT decoder and encoder.
3. ServiceProcessHandler just process some connect and delivery msg.
  when processing delivery msg, many leaks happened.
### Minimal yet complete reproducer code (or URL to code)
1 .  i have some doubtful point but i don't know where is the problem is .
2.  i am  lost when should i need to use ReferenceCountUtil.release(msg) ?
    Need release  after writeandflush a msg? 
    should every msg  be released in the last hander of inbound? 
   if ByteBuf is a member of one message object, should i release  it in some where ?
3.  some code:
   (1)UlcDecoder:
 ```
   private static Result<?> decodeDeliveryReqPayload(ByteBuf buffer, int bytesRemainingInVariablePart)
    {
         ByteBuf b = buffer.readRetainedSlice(bytesRemainingInVariablePart);
        return new Result<ByteBuf>(b, bytesRemainingInVariablePart);
   }
```
(2) UlcEncoder
```
     private static ByteBuf encodeDeliveryReqMsg(ByteBufAllocator byteBufalloc, UlcDeliveryReqMsg msg)
     {
        ByteBuf payload = msg.getPayload().duplicate();
        UlcDeliveryReqVariableHeader variableHeader = msg.getVariableHeader();
        UlcMsgFixedHeader fixedHeader = msg.getFixedHeader();
        
        //size
        //payload 
        int payloadbufsize = payload.readableBytes();
    }
```
(3)ServiceProcessHandler extends ChannelInboundHandlerAdapter
```
    public void channelRead(ChannelHandlerContext ctx, Object msg)  throws Exception
    {
        if (msg instanceof UlcMessage)
        {
            try
            {
                UlcMessage ulcmsg = (UlcMessage)msg;
                //非正常状态消息也需要处理
                DecoderResult decoderResult = ulcmsg.getDecoderResult();
                if (DecoderResult.SUCCESS != decoderResult)
                {
                    return;
                }
                Channel ch = ctx.channel();
                Class<?>[] parameterTypes = {UlcMessage.class, Channel.class};
                Object[] parameters = {ulcmsg, ch};
                UlcMessage responseMsg =
                    (UlcMessage)invokeMethod(ulcmsg, "callbackProcessor", parameterTypes, parameters);
                if (null != responseMsg)
                {
                    ctx.writeAndFlush(responseMsg);
                  
                }
            }
            finally
            {
                ReferenceCountUtil.release(msg); //Need release?
            }
    }
```
(4)DeliveryReqMsgProcessor  invoked by ServiceProcessHandler .
  here  just  writeAndFlush msg  in channelRead...   any problem ?

   ` ChannelFuture future = attr.getChannel().writeAndFlush(reqMsg);`
          
Thanks very much .
### Netty version
4.1.31
### JVM version (e.g. `java -version`)
1.8

**Comment by normanmaurer** [comment]
Yes you need to release the ByteBuf once you are done with it.  Also please use proper markdown to format the code so its readable.

**Comment by strongmanwj** [comment]
ok.  fixed it.
Can you pls tell that what the probable problem is in the above code? i am lost.
Thanks.

**Comment by normanmaurer** [comment]
@strongmanwj I can not tell you without look at the whole code. But from the leak-report it seems like you do not correctly release the buffer that is used by `UlcDecoder` as input.

**Comment by strongmanwj** [comment]
@normanmaurer 
Thanks. 
 Last problem:
ByteBuf A is a class member of Class BMsg, and when invoking writeAndflush(BMsg), need to realease A ?

**Comment by strongmanwj** [comment]
solved.
Thanks.
