### ISSUE TITLE
why add selector.wakeup() after select(wakenUp.getAndSet(false)) ?

### ISSUE THREAD

**Issue by gs88pansh** [netty/netty#8644]
I'm sorry that I don't understand why do `selector.wakeUp()` again in the NioEventLoop.java.
```            
select(wakenUp.getAndSet(false));            
// 'wakenUp' is set to true too early if:
// 1) Selector is waken up between 'wakenUp.set(false)' and
//    'selector.select(...)'. (BAD)
// 2) Selector is waken up between 'selector.select(...)' and
//    'if (wakenUp.get()) { ... }'. (OK)
//
// In the first case, 'wakenUp' is set to true and the
// following 'selector.select(...)' will wake up immediately.
// Until 'wakenUp' is set to false again in the next round,
// 'wakenUp.compareAndSet(false, true)' will fail, and therefore
// any attempt to wake up the Selector will fail, too, causing
// the following 'selector.select(...)' call to block
// unnecessarily.
if (wakenUp.get()) {
    selector.wakeup();
}
```
the author explained that in the first situation, maybe (I think) if the external thread call `execute(task)` method and then set the `wakenUp` to `true` when the internal thread runs between the `wakenUp.set(false)` and  `selector.select(timeOut)`, the `selector.select(timeOut)` will return immediately. then during the next steps, if the external thread call `execute(task)` to add tasks, it will fail to call `wakenUp.compareAndSet(false, true)` and will not call `selector.wakeUp()`, and thus, any attempt to wake up the Selector will fail. But firstly, after the `selector.select()` was waken up, the internal thread will call 
```
if (selectedKeys != 0 || oldWakenUp || wakenUp.get() || hasTasks() || hasScheduledTasks()) {
    // - Selected something,
    // - waken up by user, or
    // - the task queue has a pending task.
    // - a scheduled task is ready for processing
    break;
}
```
to break the loop and run the next code:
```
try {

    processSelectedKeys();
    ...
    runAllTasks();
}
```
secondly, during the period, if the external thread call `execute(task)` method many times, the task had been added to the `taskQueen`, so it doesn't matter and the task will be run immediately because `selectStrategy.calculateStrategy(selectNowSupplier, hasTasks())` will judge if the `taskQueen` have tasks. So I don't understand why the author add 
```
if (wakenUp.get()) {
    selector.wakeup();
}
```
after 
```
select(wakenUp.getAndSet(false));   
```
 could you please explain that what the first situation really is you comment in the src file?

**Comment by laiwenqiang** [comment]
do you have the answer ？I am confused too.

**Comment by normanmaurer** [comment]
@trustin mind having a look ? This code was added by you a long time ago.

**Comment by zhikaiwu** [comment]
me too

**Comment by gfkobe** [comment]
The code when the explain added is absolutely different from v4.1.Checkout that version then you will know everything.
