### ISSUE TITLE
certificate error with elliptic curve 

### ISSUE THREAD

**Issue by konsultaner** [netty/netty#8657]
I got a new certificate by global sign that uses [ecc](https://support.globalsign.com/customer/portal/articles/1994347-ecc). I get the following error. How do I enable ecc support? Is this netty related or do I need to update java with something?

```
Dec 12 14:29:55 dls-rbg-mb-10 java: Exception in thread "Thread-1" java.lang.IllegalArgumentException: File does not contain valid private key: /etc/pki/tls/private/app_dls-gmbh_biz.key.pem
Dec 12 14:29:55 dls-rbg-mb-10 java: at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:251)
Dec 12 14:29:55 dls-rbg-mb-10 java: at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:206)
Dec 12 14:29:55 dls-rbg-mb-10 java: at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:49)
Dec 12 14:29:55 dls-rbg-mb-10 java: at de.konsultaner.wamp.peer.Router.run(Router.java:144)
Dec 12 14:29:55 dls-rbg-mb-10 java: at java.lang.Thread.run(Thread.java:745)
Dec 12 14:29:55 dls-rbg-mb-10 java: Caused by: java.security.NoSuchAlgorithmException: EC KeyFactory not available Dec 12 14:29:55 dls-rbg-mb-10 java: at java.security.KeyFactory.<init>(KeyFactory.java:138)
Dec 12 14:29:55 dls-rbg-mb-10 java: at java.security.KeyFactory.getInstance(KeyFactory.java:172)
Dec 12 14:29:55 dls-rbg-mb-10 java: at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:947)
Dec 12 14:29:55 dls-rbg-mb-10 java: at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:918)
Dec 12 14:29:55 dls-rbg-mb-10 java: at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:249)
Dec 12 14:29:55 dls-rbg-mb-10 java: ... 4 more
```

This error might be related to #8149

### Netty version
4.1.20

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

### OS version (e.g. `uname -a`)
Linux 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by konsultaner** [comment]
I could send you the key as email. I would like to use it in production and github is not the right place share a private key 😅

**Comment by normanmaurer** [comment]
Cant I just use openssl to generate a self-signed one that reproduce it somehow ?

**Comment by normanmaurer** [comment]
@konsultaner ^^

**Comment by konsultaner** [comment]
@normanmaurer sorry, I didn't create any of those. I'm still having problems with other people involved to give you material to work on this issue. As soon as I have everything I will post it here.

**Comment by konsultaner** [comment]
@normanmaurer  this is the old cert: [cert.zip](https://github.com/netty/netty/files/2702188/cert.zip)

I will send you the password as email.

**Comment by normanmaurer** [comment]
I think this due your openjdk version you use. Please use a more recent version.

There are also multiple bug-reports against RHEL / centos related to this. Like: https://bugzilla.redhat.com/show_bug.cgi?id=1245810

Please report back one you did the upgrade and re-open if you still have the problem.

```
Caused by: java.security.NoSuchAlgorithmException: EC KeyFactory not available
```

Is thrown because the JDK does not support EC.
