### ISSUE TITLE
Where will the request been cached if Netty Channel isWritable() return false

### ISSUE THREAD

**Issue by weiguoOU** [netty/netty#8669]
I'm implementing the back pressure for the sender which continuously sending data to the netty. From the netty channel API, I saw the isWritable() queue the requests if return false. Could I know where will the request be queued? in heap or direct memory. What's the queue size. In what case, it will cause the out of direct memory issue?

isWritable():
"Returns true if and only if the I/O thread will perform the requested write operation immediately. Any write requests made when this method returns false are queued until the I/O thread is ready to process the queued write requests."

Thanks
Wei

**Comment by normanmaurer** [comment]
@weiguoOU the queue itself is in the heap, but if the queued data is using direct memory or not depends on the data itself. The Queue is unbound but netty will notify you with `isWritable()` and `channelWritabilityChanged` when you queue to much data.
