### ISSUE TITLE
High CPU usage with OioEventLoopGroup on Android 6.0 in my embedded device

### ISSUE THREAD

**Issue by rel1ve** [netty/netty#8679]
### Expected behavior
I use netty running on USB-HID based embedded device. After channel (extends OioByteStreamChannel) is connected, while idle for reading or writing, CPU usage should be very low, expected less than 1%.

### Actual behavior
Actually CPU usage is at least 30%.

### Steps to reproduce
I debug with AS profiler, and found ThreadPerChannelEventLoop.run() cost much cpu time. Can I add code like "Thread.sleep(1)" in this loop to avoid high CPU usage?
Such thing also happens on my thinkpad E560, and CPU usage is 25%.

### Minimal yet complete reproducer code (or URL to code)
            EventLoopGroup group = new OioEventLoopGroup();
            Bootstrap b = new Bootstrap();
            b.group(group)
                    .channel(HidRpcChannel.class)
                    .handler(new ChannelInitializer<HidRpcChannel>() {
                        @Override
                        public void initChannel(HidRpcChannel ch) throws Exception {
                            HidChannelConfig config = (HidChannelConfig) ch.config();
                            config.setWaitTime(0).setFake(fake);

                            ch.pipeline().addLast(
                                    new IdleStateHandler(5, 0, 0, TimeUnit.SECONDS),
                                    new DatagramDuplexHandler(1024),
                                    new JsonMessageDuplexHandler(),
                                    new HeartbeatServerHandler(),
                                    new TimeoutDuplexHandler(timeoutListener),
                                    new MessageReceivedHandler(messageReceivedListener),
                                    new ExceptionHandler(exceptionListener)
                            );
                        }
                    });

            channel = b.connect(new CommDeviceAddress("HID_MAIN")).sync().channel();
### Netty version
4.1.31.Final
### JVM version (e.g. `java -version`) 
1.6.0_45
### OS version (e.g. `uname -a`)
Android 6.0

**Comment by normanmaurer** [comment]
You may need to create your own EventLoop implementation to do this or something similar. There is no API provided for this kind of stuff
