### ISSUE TITLE
Help：new ServerSocketChannel

### ISSUE THREAD

**Issue by strongmanwj** [netty/netty#8682]
### Expected behavior
**Now  our server is based on Netty‘s  epoll. But now we need to get better performance, we got a new TCPIP protocal  stack  lib which has been greatly optimized  and provide the same interface as  linux socket posix interface  and epoll interface.  So i want to know if can i use new lib to replace  libnetty_transport_native_epoll_x86_64.so in netty ?
Where can i get libnetty_transport_native_epoll_x86_64.so source code ?
If I want to use new lib instead of linux's socket or epoll, what need i do ? Is that difficulty?
3Q**
### Netty version
4.1.31
### OS version (e.g. `uname -a`)
linux centos7

**Comment by normanmaurer** [comment]
this is a bug tracker ... please only use it to report bugs. All the native code is included in */src/main/c.
