### ISSUE TITLE
Dead Loop in DNS resolver

### ISSUE THREAD

**Issue by slggamerTrue** [netty/netty#8687]
### Problem
There is a dead loop in DnsResolveContext.onExpectedResponse when there is a loop in the CNAMES
![image](https://user-images.githubusercontent.com/20608396/50428555-8ac8c780-08f3-11e9-908c-5ea0c8cf1d6a.png)

We found this problem because one DNS meet the problem
![image](https://user-images.githubusercontent.com/20608396/50428579-ca8faf00-08f3-11e9-829c-8927ebf72baf.png)

### Steps to reproduce
There is a small chance that the "www.altura.org" would response the loop CNAME. It's easy to reproduce the problem by your own DNS server.
The same case can be handled by the JDK DNS Resolver.

### Netty version
4.1.27

### JVM version (e.g. `java -version`)
JDK 1.8.181

### OS version (e.g. `uname -a`)
Centos 7.0

**Comment by normanmaurer** [comment]
@slggamerTrue thanks for reporting. Let me come up with a unit test and fix.

**Comment by normanmaurer** [comment]
@slggamerTrue can you test https://github.com/netty/netty/pull/8691 ?

**Comment by slggamerTrue** [comment]
Thanks @normanmaurer. The fix is perfect. Looking forward to the new release.

**Comment by normanmaurer** [comment]
@slggamerTrue thanks for checking and reporting
