### ISSUE TITLE
how to make Bootstrap single instance?

### ISSUE THREAD

**Issue by wenweihu86** [netty/netty#8690]
### Expected behavior
make Bootstrap single instance

### Actual behavior
if a module has to connect to two cluster servers, and has different connect timeout for different cluster,
I can only create two bootstrap since connect_timeout is set on Bootstrap.
creating Bootstrap is time consuming, so I want to create single instance of Bootstrap for all servers.

### Steps to reproduce
no

### Minimal yet complete reproducer code (or URL to code)
no

### Netty version
4.1.30.Final

**Comment by normanmaurer** [comment]
@wenweihu86 just create a new instance as you do at the moment. You should only use the same `Bootstrap` if the config is the same.

**Comment by wenweihu86** [comment]
@normanmaurer since connect_timeout_ms is set in the Bootstrap, so different cluster server should have different Bootstrap instance. But Bootstrap instantiation is time consuming.
could you please upgrade netty to make connect_timeout_ms to be set out side of Bootstrap？
