### ISSUE TITLE
Channel#close() can succeed before port is unbound under Java 11

### ISSUE THREAD

**Issue by jchambers** [netty/netty#8697]
### Expected behavior

When a server channel bound to a port is closed, the `Future` returned by `serverChannel.close()` should succeed only after the port to which the channel is bound has been released.

### Actual behavior

Under Java 11, it appears that it's possible for the `Future` returned by `serverChannel.close()` to succeed before the port has been released.

### Minimal yet complete reproducer code

```java
import io.netty.bootstrap.ServerBootstrap;
import io.netty.channel.ChannelFuture;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.util.concurrent.Future;

public class RebindPortExampleApp {

    private static final int PORT = 8443;

    public static void main(final String... args) throws Throwable {

        // Note: this problem is reproducible regardless of the number of threads
        // in the event loop group.
        final NioEventLoopGroup eventLoopGroup = new NioEventLoopGroup(1);

        final ServerBootstrap serverBootstrap = new ServerBootstrap();
        serverBootstrap.group(eventLoopGroup);
        serverBootstrap.channel(NioServerSocketChannel.class);
        serverBootstrap.childHandler(new ChannelInitializer<SocketChannel>() {
            protected void initChannel(final SocketChannel socketChannel) {
            }
        });

        while (true) {
            final ChannelFuture bindFuture = serverBootstrap.bind(PORT).await();

            if (bindFuture.isSuccess()) {
                System.out.println("Bind attempt succeeded.");
            } else {
                // This is where things fall apart on the second iteration because
                // the port is already in use.
                System.err.println("Bind attempt failed.");
                throw bindFuture.cause();
            }

            final Future<Void> closeFuture = bindFuture.channel().close().await();

            if (closeFuture.isSuccess()) {
                System.out.println("Close attempt succeeded.");
            } else {
                System.err.println("Close attempt failed.");
                throw closeFuture.cause();
            }

            // Everything works as expected if we add a pause between loops, which
            // suggests that the port is at least on its way to being released by the
            // time the future has succeeded.
            // Thread.sleep(100);
        }
    }
}
```

### Netty version

4.1.32, but I can reproduce this going as far back as (at least) 4.1.0.

### JVM version

```
$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

I've _maybe_ seen a rare related test failure in Java 8, but can only reproduce the problem with the above code under Java 11. It seems fine under Java 9, and I don't have a copy of Java 10 readily available (thanks, Homebrew).

### OS version

```
$ uname -a
Darwin laminar.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```

**Comment by normanmaurer** [comment]
@jchambers will have a look but this may be a JDK "bug" as we just call `close()` on the JDK `Channel` and only notify the future once the call is done.

**Comment by jchambers** [comment]
I figured that might be the case. I'll see if I can reproduce the problem at the JDK level.

**Comment by jchambers** [comment]
Hm. I hate to say it, but the ultra-minimal test case does _not_ reproduce the problem at the JDK level:

```java
import java.net.InetSocketAddress;
import java.net.SocketAddress;
import java.nio.channels.ServerSocketChannel;

public class JdkRebindPortExampleApp {

    private static final SocketAddress SOCKET_ADDRESS = new InetSocketAddress(8443);

    public static void main(final String... args) throws Exception {
        while (true) {
            final ServerSocketChannel serverSocketChannel = ServerSocketChannel.open();
            serverSocketChannel.bind(SOCKET_ADDRESS);

            serverSocketChannel.close();
        }
    }
}
```

I've also tried variations with calls to `accept()` for good measure, and those all seem fine, too.

**Comment by normanmaurer** [comment]
Can you also try to configure the channel as non blocking and add it to a selector ?

**Comment by jchambers** [comment]
> add it to a selector

Ah—good call. I can, indeed, reproduce the problem by registering the channel with a selector:

```java
import java.net.InetSocketAddress;
import java.net.SocketAddress;
import java.nio.channels.SelectionKey;
import java.nio.channels.Selector;
import java.nio.channels.ServerSocketChannel;
import java.nio.channels.spi.SelectorProvider;

public class JdkRebindPortExampleApp {

    private static final SocketAddress SOCKET_ADDRESS = new InetSocketAddress(8443);
    private static final SelectorProvider SELECTOR_PROVIDER = SelectorProvider.provider();

    public static void main(final String... args) throws Exception {
        final Selector selector = SELECTOR_PROVIDER.openSelector();

        while (true) {
            final ServerSocketChannel serverSocketChannel = SELECTOR_PROVIDER.openServerSocketChannel();
            serverSocketChannel.configureBlocking(false);
            serverSocketChannel.register(selector, SelectionKey.OP_ACCEPT);

            serverSocketChannel.bind(SOCKET_ADDRESS);
            serverSocketChannel.close();
        }
    }
}
```

It's _mostly_ fine under Java 8/9 (and presumably others). I say _mostly_ because, if we continue to use `while (true)`, we'll eventually hit a limit on file descriptors. We can work around that by stopping after some finite number of iterations, but that feels like cheating to me (especially because the Netty case above doesn't run out of file descriptors). I can solve the file descriptor limit issue by closing the selector after each iteration, but then that _also_ resolves the `AlreadyBoundException` issue:

```java
import java.net.InetSocketAddress;
import java.net.SocketAddress;
import java.nio.channels.SelectionKey;
import java.nio.channels.Selector;
import java.nio.channels.ServerSocketChannel;
import java.nio.channels.spi.SelectorProvider;

public class JdkRebindPortExampleApp {

    private static final SocketAddress SOCKET_ADDRESS = new InetSocketAddress(8443);
    private static final SelectorProvider SELECTOR_PROVIDER = SelectorProvider.provider();

    public static void main(final String... args) throws Exception {

        while (true) {
            try (final Selector selector = SELECTOR_PROVIDER.openSelector();
                 final ServerSocketChannel serverSocketChannel = SELECTOR_PROVIDER.openServerSocketChannel()) {

                serverSocketChannel.configureBlocking(false);
                serverSocketChannel.register(selector, SelectionKey.OP_ACCEPT);

                serverSocketChannel.bind(SOCKET_ADDRESS);
            }
        }
    }
}
```

I have to admit we're bumping up against the limits of my experience with NIO, and so I could be making an obvious mistake (which seems likely given that I seem to have created a new problem that Netty doesn't have).

From here, if you agree this is a JDK problem and I'm not doing really weird, I'm happy to start jumping through the hoops at https://bugreport.java.com/bugreport/ unless you have secret bug-reporting powers.

**Comment by normanmaurer** [comment]
What happens if you cancel the registration before closing the channel ? I would suspect you will see the same behaviour as with Netty

**Comment by jchambers** [comment]
I suspect you're right.

I've had a busier-than-expected couple of weeks and haven't been able to follow up yet. I'm really sorry for the delay! I'll be out next week, too, but hope to verify as soon as I'm back. Thanks for your patience.

**Comment by normanmaurer** [comment]
@jchambers no worries... happy to help. I also just returned from vacation and so try to process my backlog as well 😢

**Comment by normanmaurer** [comment]
@jchambers let me close this one as there is nothing we can do about this. Please re-open if you believe there is anything we should / can do tho.

**Comment by AlanBateman** [comment]
Here's the JDK issue to track adding documentation, via implementation note, on this issue:
  https://bugs.openjdk.java.net/browse/JDK-8207045

The behavior when closing a channel registered with a Selecor has always been platform specific so you've never been guaranteed to be able to re-bind until the channel is flushed from the Selector.
