### ISSUE TITLE
Build Issue with maven-antrun-plugin: "Plugin execution not covered by lifecycle configuration"

### ISSUE THREAD

**Issue by veebs** [netty/netty#87]
Just installed Eclipse Indigo Service Release 1

It comes with M2E - Maven Integration for Eclipse 1.1

When I load up the Netty project, I get the following error:

```
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-antrun-plugin:1.7:run (execution: write-version, phase: validate)   pom.xml /netty  line 320    Maven Project Build Lifecycle Mapping Problem
```

```
      <plugin>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>1.7</version>
        <executions>
          <execution>
            <id>write-version</id>
            <phase>validate</phase>
            <goals>
              <goal>run</goal>
            </goals>
         ...
        </execution>
      </plugin>
```

Seems like `maven-antrun-plugin` does not like the the `validate` phase.  

The error goes away if I set the phase to `package` - but I am not sure if this is what is required.

**Comment by chandu1988** [comment]
??????

**Comment by chandu1988** [comment]
Description Resource	Path	Location	Type
Mapping file orm.xml does not have supported content for this JPA platform.	orm.xml	/spring-social-tutorial/src/main/java/META-INF	 JPA Problem

**Comment by JavaHelper** [comment]
Could someone please guide on this issue http://stackoverflow.com/questions/35523664/java-util-concurrent-executionexception-org-apache-catalina-lifecycleexception/35923065#35923065 ?
