### ISSUE TITLE
ChunkedWriteHandler may report a failed write as a successful one

### ISSUE THREAD

**Issue by kachayev** [netty/netty#8700]
### Expected behavior

If the writing of the last chunk of the chunked input message failed, the corresponding promise should be failed with an appropriate exception. 

### Actual behavior

`operationComplete` callback [reports success](https://github.com/netty/netty/blob/fa84e2b3af45ec7fd47909eff0aa7d2be5a54972/handler/src/main/java/io/netty/handler/stream/ChunkedWriteHandler.java#L268) with no check of the `future.isSuccesful()`. If I'm not missing anything and this was not done on purpose, I'll submit a PR with a fix.

### Steps to reproduce

n/a

### Minimal yet complete reproducer code (or URL to code)

n/a

### Netty version

4.1.32

### JVM version (e.g. `java -version`)

n/a

### OS version (e.g. `uname -a`)

n/a

**Comment by kachayev** [comment]
Another related question. When using `HttpChunkedInput` with `ChunkedWriteHandler`, `lastHttpContent` would be written/flushed even in case write promise is already reported as a failed one. We rely on `endOfInput` being `true` after `closeInput` was called, which doesn't work for  `HttpChunkedInput`.

**Comment by normanmaurer** [comment]
@kachayev yes this is a bug... would you mind open a PR with a fix ?

**Comment by kachayev** [comment]
@normanmaurer Sure! Will do shortly.
