### ISSUE TITLE
netty-all java 11 support

### ISSUE THREAD

**Issue by ViktorValkov** [netty/netty#8708]
Are you planning to release a netty-all version which is compatible with Java 11? If yes, when do you expect this will happen?
The jdeps report is complaining for:

netty-all.jar -> JDK removed internal API netty-all.jar -> java.base netty-all.jar -> jdk.unsupported io.netty.util.internal.PlatformDependent0 -> sun.misc.Cleaner JDK internal API (JDK removed internal API) io.netty.util.internal.PlatformDependent0 -> sun.misc.Unsafe JDK internal API (jdk.unsupported) io.netty.util.internal.PlatformDependent0 -> sun.nio.ch.DirectBuffer JDK internal API (java.base) io.netty.util.internal.UnsafeAtomicIntegerFieldUpdater -> sun.misc.Unsafe JDK internal API (jdk.unsupported) io.netty.util.internal.UnsafeAtomicLongFieldUpdater -> sun.misc.Unsafe JDK internal API (jdk.unsupported) io.netty.util.internal.UnsafeAtomicReferenceFieldUpdater -> sun.misc.Unsafe JDK internal API (jdk.unsupported) io.netty.util.internal.chmv8.ConcurrentHashMapV8 -> sun.misc.Unsafe JDK internal API (jdk.unsupported) io.netty.util.internal.chmv8.ConcurrentHashMapV8$1 -> sun.misc.Unsafe JDK internal API (jdk.unsupported) io.netty.util.internal.chmv8.ConcurrentHashMapV8$TreeBin -> sun.misc.Unsafe JDK internal API (jdk.unsupported) io.netty.util.internal.chmv8.CountedCompleter -> sun.misc.Unsafe JDK internal API (jdk.unsupported) io.netty.util.internal.chmv8.CountedCompleter$1 -> sun.misc.Unsafe JDK internal API (jdk.unsupported) io.netty.util.internal.chmv8.ForkJoinPool -> sun.misc.Unsafe JDK internal API (jdk.unsupported) io.netty.util.internal.chmv8.ForkJoinPool$2 -> sun.misc.Unsafe JDK internal API (jdk.unsupported) io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue -> sun.misc.Unsafe JDK internal API (jdk.unsupported) io.netty.util.internal.chmv8.ForkJoinTask -> sun.misc.Unsafe JDK internal API (jdk.unsupported) io.netty.util.internal.chmv8.ForkJoinTask$1 -> sun.misc.Unsafe JDK internal API (jdk.unsupported) io.netty.util.internal.chmv8.Striped64 -> sun.misc.Unsafe JDK internal API (jdk.unsupported) io.netty.util.internal.chmv8.Striped64$1 -> sun.misc.Unsafe JDK internal API (jdk.unsupported) io.netty.util.internal.chmv8.Striped64$Cell -> sun.misc.Unsafe JDK internal API (jdk.unsupported) JDK Internal API Suggested Replacement ---------------- --------------------- sun.misc.Cleaner Use java.lang.ref.PhantomReference @since 1.2 or java.lang.ref.Cleaner @since 9 sun.misc.Unsafe See http://openjdk.java.net/jeps/260

Implementation-Version: 4.0.17.Final

Thanks in advance for the reply.

**Comment by ViktorValkov** [comment]
@normanmaurer @jchambers ?

**Comment by jchambers** [comment]
Sorry, @ViktorValkov; I'm an external contributor, just like you. This really isn't my territory.

**Comment by normanmaurer** [comment]
Netty 4.1.30.Final and later works on java11 without problems.

**Comment by valenpo** [comment]
> Netty 4.1.30.Final and later works on java11 without problems.

migrating to java11 and run jdeps for libs, it report 

`digraph "netty-common-4.1.82.Final.jar" {
   "io.netty.util.internal.CleanerJava9"              -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.CleanerJava9$1"            -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.CleanerJava9$2"            -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.PlatformDependent$Mpsc$1"  -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.PlatformDependent0"        -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.PlatformDependent0$1"      -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.PlatformDependent0$2"      -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.PlatformDependent0$3"      -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.PlatformDependent0$4"      -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.PlatformDependent0$6"      -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.shaded.org.jctools.queues.BaseLinkedQueueConsumerNodeRef" -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.shaded.org.jctools.queues.BaseLinkedQueueProducerNodeRef" -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueueColdProducerFields" -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueueConsumerFields" -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueueProducerFields" -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.shaded.org.jctools.queues.LinkedQueueNode" -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.shaded.org.jctools.queues.MpscArrayQueueConsumerIndexField" -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.shaded.org.jctools.queues.MpscArrayQueueProducerIndexField" -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.shaded.org.jctools.queues.MpscArrayQueueProducerLimitField" -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.shaded.org.jctools.util.UnsafeAccess" -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
   "io.netty.util.internal.shaded.org.jctools.util.UnsafeRefArrayAccess" -> "sun.misc.Unsafe (JDK internal API (jdk.unsupported))";
}
`
Should I ignore it ?
