### ISSUE TITLE
Does netty-all contains netty-transport-native-epoll or not?

### ISSUE THREAD

**Issue by tuohai666** [netty/netty#8714]
I've learned how to using the linux native transport from here: https://netty.io/wiki/native-transports.html
It tells me **the native transport is not part of the Netty core, you need to pull the netty-transport-native-epoll as a dependency in your Maven pom.xml:**

![image](https://user-images.githubusercontent.com/24643893/51082379-c27f9e00-1740-11e9-9b03-7a3a0f118885.png)

My questions are:
1. What is the **Netty core**? What's the relationship between **Netty core** and **nett-all**?
2. Does netty-all contains netty-transport-native-epoll or not? If not why call it netty-**all**?
3. If netty-all contains netty-transport-native-epoll, should I follow the instruction from the wiki above?
4. I noticed that some projects pull the netty-all and netty-transport-native-epoll together as dependencies in the Maven pom.xml, is this the right way? Just like this:

![image](https://user-images.githubusercontent.com/24643893/51082359-6e74b980-1740-11e9-8274-8b53d9bae4dc.png)

**Comment by njhill** [comment]
@tuohai666 netty-all _does_ currently contain epoll and kqueue, with their corresponding classifiers. There's no need to include them as separately as described in the wiki page or your example above.

I actually posed a related question in https://github.com/netty/netty/issues/8097 a little while back, which didn't get any responses.

**Comment by tuohai666** [comment]
>  as described in the wiki page or your example above.

Thanks a lot! Could you show me the wiki page? I didn't find the corresponding information from https://netty.io/wiki/native-transports.html

**Comment by tuohai666** [comment]
@njhill Thanks for your respond.
