### ISSUE TITLE
Netty encoder  decoder

### ISSUE THREAD

**Issue by xiaozaiyuji** [netty/netty#8722]
### Expected behavior
As we all know,netty is a effective tool to nio ,but I faced a problem make me crazy.I want write a netty program to support mqtt,websocket,stomp ,but I found this decoder and encoder is different.but I did not know the them deply.So I have to check files to find how to sovle this problem.
I think as netty support all this procotol,why netty not to combine all this like mqtt,websocket,stomp with a more flexible way.
May be I just not find the right method,so I support to get some advices.

Good blees you!

**Comment by normanmaurer** [comment]
Please use stackoverflow for questions. This is a bug tracker.
