### ISSUE TITLE
Netty causing StreamCorruptedException when using different Java versions

### ISSUE THREAD

**Issue by UKreher** [netty/netty#8730]
This is somewhat a follow-up of #1148: Not being aware that Netty requires the same Java version on client and on server side, we were quite surprised to get a `StreamCorruptedException` when using different Java versions. In our scenario we cannot ensure that all communicating Java processes use the same version; even the vendor may differ.
The solution is rather simple: Use copies of `ObjectEncoder` and `ObjectDecoder` replacing `CompactObjectOutputStream` with `ObjectOutputStream` and `CompactObjectInputStream` with `ObjectInputStream`.

But why do you need to do this? Are the compact variants missing so much logic compared to `Object*putStream`, e. g. the ability to handle additional fields? Then some documentation would be nice, e. g. javadoc explaining when (not) to use these classes.

The following is just for the sake of completeness in case someone wants to reproduce the problem:

### Expected behavior
Different Java versions can communicate with each other using object serialisation just like using `ObjectInputStream` and `ObjectOutputStream` would.

### Actual behavior
The `CompactObjectInputStream` and `CompactObjectOutputStream` handle the (de)serialisation somewhat differently leading to a `StreamCorruptedException`.

### Steps to reproduce
Run the `io.netty.example.objectecho.ObjectEchoServer` with a Java 8 or earlier. Run the `io.netty.example.objectecho.ObjectEchoClient` with Java 9 or later. Let the client sent a `StackTraceElement`. Due to additional fields within the class in Java 9, the server gets a `StreamCorruptedException`.

### Minimal yet complete reproducer code (or URL to code)
Insert/replace the following lines in `io.netty.example.objectecho.ObjectEchoClient`
```java
            // Start the connection attempt.
            Channel channel = b.connect(HOST, PORT).sync().channel();
            channel.write(new StackTraceElement("classLoader", "module", "moduleVersion", "class", "method", "file", 42));
            channel.close().sync();
```

### Netty version
4.1.32

### JVM version (e.g. `java -version`)
java version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)

java version "11" 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)

### OS version (e.g. `uname -a`)
Linux *** 4.4.0-141-generic #167~14.04.1-Ubuntu SMP Mon Dec 10 13:20:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@UKreher yep this is a limitation. Would you willing to do a PR with an improvement for the java docs ?
