### ISSUE TITLE
HTTP/2 failures when netty update from 4.1.22.Final to 4.1.23.Final

### ISSUE THREAD

**Issue by ldclakmal** [netty/netty#8742]
### Description
We are updating the netty version of https://github.com/wso2/transport-http from **4.1.19.Final** to **4.1.33.Final**. But when updating we noticed that HTTP/2 related test cases are failing. It has happened when updating from **4.1.22.Final** to **4.1.23.Final**.

Further, we noticed that in netty version _4.1.22.Final_, when client side upgrading the UPGRADE_ISSUED and UPGRADE_SUCCESSFUL user events are triggered.

But after upagrade to netty version _4.1.23.Final_, only the UPGRADE_ISSUED event is triggered and UPGRADE_SUCCESSFUL event is not triggered.

Any idea what could be the reason for this? Really appreciate help on this.

### Netty version
4.1.23.Final

### JVM version (e.g. `java -version`)
1.8.0_201

### OS version (e.g. `uname -a`)
Ubuntu 16.04

**Comment by normanmaurer** [comment]
Can you share a reproducer ?

**Comment by normanmaurer** [comment]
@ldclakmal ping ... or this related to: https://github.com/netty/netty/pull/8848 ?

**Comment by ldclakmal** [comment]
@normanmaurer Yes, this issue is related to #8848.

**Comment by ldclakmal** [comment]
The issue is fixed with #8848. Hence closing the issue.
