### ISSUE TITLE
HttpObjectAggregator w/ isStartMessage: Bug or Feature?

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#8772]
Let's say you want to be very selective when and if to aggregate HttpRequests and Responses. Say you want to only aggregate responses with a content-type of application/json. Naturally I went with this:

```java
public class MyHttpObjectAggregator extends HttpObjectAggregator {
  
  public MyHttpObjectAggregator(int maxContentLength) {
    super(maxContentLength);
  }

  @Override
  protected boolean isStartMessage(HttpObject msg) throws Exception {
    if (msg instanceof HttpResponse) {
      HttpResponse response = (HttpResponse) msg;
      HttpHeaders headers = response.headers();
      
      String contentType = headers.get(HttpHeaderNames.CONTENT_TYPE);
      if (AsciiString.contentEqualsIgnoreCase(contentType, HttpHeaderValues.APPLICATION_JSON)) {
        return true;
      }
    }
    
    return false;
  }
}
```

... but it will not work due to the following two conditions

1) isContentMessage returns true for any HttpContent

https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/codec/src/main/java/io/netty/handler/codec/MessageAggregator.java#L99

2) Subsequently we enter decode(), isContentMessage returns again true but `currentMessage` is null and early exits. Leaving the aggregator in a bad state.

https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/codec/src/main/java/io/netty/handler/codec/MessageAggregator.java#L261-L265

My work around is to introduce a toggle flag in my aggregator that looks like this:

```java
public class MyHttpObjectAggregator extends HttpObjectAggregator {
  
  private boolean aggregating;
  
  public MyHttpObjectAggregator(int maxContentLength) {
    super(maxContentLength);
  }

  @Override
  protected boolean isStartMessage(HttpObject msg) throws Exception {
    if (msg instanceof HttpResponse) {
      HttpResponse response = (HttpResponse) msg;
      HttpHeaders headers = response.headers();
      
      String contentType = headers.get(HttpHeaderNames.CONTENT_TYPE);
      if (AsciiString.contentEqualsIgnoreCase(contentType, HttpHeaderValues.APPLICATION_JSON)) {
        aggregating = true;
        return true;
        
      } else {
        aggregating = false;
        return false;
      }
    }
    
    return false;
  }

  @Override
  protected boolean isContentMessage(HttpObject msg) throws Exception {
    return aggregating && super.isContentMessage(msg);
  }
}
```

I'm wondering if this is intended behavior or a bug?

**Comment by normanmaurer** [comment]
@rkapsi hmmm good question. For me it sounds more like a bug. WDYT ?

**Comment by rkapsi** [comment]
@normanmaurer same, I'll create a PR
