### ISSUE TITLE
HashedWheelTimer

### ISSUE THREAD

**Issue by carryxyh** [netty/netty#8774]
Hi, community.

Recently there was a discussion in the dubbo community. We introduced netty's hashedWheelTimer to make some optimizations, but some people have doubts about using HashedWheelTimer. The doubt is that we found that netty itself does not use HashedWheelTimer, so I would like to ask why netty is no longer The reason for using HashedWheelTimer. Can someone answer?

**Comment by normanmaurer** [comment]
@carryxyh just because we usually want to be on the same thread as the `EventLoop` of the Channel. that said there is nothing wrong about the `HashedWheelTimer`.
