### ISSUE TITLE
Read the source code : The problem with waiters in DefaultPromise .

### ISSUE THREAD

**Issue by duaicxx** [netty/netty#8782]
The waiters in DefaultPromise use synchronized(this) when they operate, and use decWaiters immediately after using incWaiters. Waiters are not always between 1 and 0. What is the meaning of this?

**Comment by normanmaurer** [comment]
sorry I dont get what you are asking for... maybe link to the code and give some example what you think should be changed ?

**Comment by duaicxx** [comment]
There is no place to understand, just don't understand why the author did this, and it bothered me. The waiters variable in DefaultPromise has the current lock for his operation. This means that the waiters can only be 1 and 0. Is that true? Thank you very much for your answer.

**Comment by normanmaurer** [comment]
@duaicxx not sure I correctly understand your question but even it has the current lock others can obtain it once it executed `wait(...)`. See also https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#wait()

**Comment by duaicxx** [comment]
@normanmaurer

**Comment by duaicxx** [comment]
Well, this is the case, but the waiters do the subtraction before releasing the lock, which means that the waiters get the lock plus 1 minus 1 when the lock is released, so the waiters always switch between 1 and 0. The problem is only I don't borrow when I read the source code. I don't know if I missed the idea of the author doing this, so I raised this question. Thank you very much for your answers and delay your time.

**Comment by johnou** [comment]
@duaicxx if you have a shared DefaultPromise multiple threads may invoke await and subsequently wait() putting the thread into WAITING state, at this point waiters can increase all the way up to Short.MAX_VALUE.. when the promise is fulfilled (success or failure) all waiting threads will be notified and finally decrement the waiters value.

**Comment by kezhenxu94** [comment]
> @duaicxx if you have a shared DefaultPromise multiple threads may invoke await and subsequently wait() putting the thread into WAITING state, at this point waiters can increase all the way up to Short.MAX_VALUE.. when the promise is fulfilled (success or failure) all waiting threads will be notified and finally decrement the waiters value.

@duaicxx As @johnou explained, and I slightly add a ASCII picture to show this more intuitively.
```java


        synchronized (this) { // <-- 3. Thread-2 goes here and obtains the lock 
            while (!isDone()) {
                incWaiters(); // <-- 1. Thread-1 increases the waiters count (count is 1)
                              // <-- 4. Thread-2 goes here and increases the waiters count (count is 2), etc.
                try {
                    wait();  // <--- 2. Thread-1 suspends here and the lock is released
                } finally {
                    decWaiters();
                }
            }
        }
```

**Comment by normanmaurer** [comment]
as @johnou and @kezhenxu94 said... closing
