### ISSUE TITLE
netty Multicast mode cannot communicate before different hosts,All multicast configurations were tried and all known possibilities analyzed,Failure to fix, is it a bug?ask for help!

### ISSUE THREAD

**Issue by huqingkang** [netty/netty#8791]
### Expected behavior
multicast Communication between hosts is possible
### Actual behavior
Multicast mode failed to communicate between different hosts
### Steps to reproduce
Open two computers, multicast mode,A computer is used to send messages, A computer is used to  receive message
### Minimal yet complete reproducer code (or URL to code)
receive:
public void MulticastInit() {
InetSocketAddress groupAddress = new InetSocketAddress(Constant.PDXP_SERVER_IP, Constant.PDXP_SERVER_PORT);
EventLoopGroup group = new NioEventLoopGroup();
try {
NetworkInterface ni = NetUtil.LOOPBACK_IF;
Enumeration addresses = ni.getInetAddresses();
InetAddress localAddress = null;
while (addresses.hasMoreElements()) {
InetAddress address = addresses.nextElement();
if (address instanceof Inet4Address) {
localAddress = address;
}
}
Bootstrap b = new Bootstrap();
b.group(group)
.channelFactory(new ChannelFactory() {

                    @Override
                    public NioDatagramChannel newChannel() {
                        return new NioDatagramChannel(InternetProtocolFamily.IPv4);
                    }
                })
                .localAddress(localAddress, groupAddress.getPort())
                .option(ChannelOption.IP_MULTICAST_LOOP_DISABLED, true)
                .option(ChannelOption.IP_MULTICAST_ADDR, localAddress)
                .option(ChannelOption.SO_REUSEADDR, true)
                .handler(new ChannelInitializer<NioDatagramChannel>() {
                    @Override
                    public void initChannel(NioDatagramChannel ch) throws Exception {
                        ch.pipeline().addLast(new MulticastReceiveServerHandler(redisTemplate));
                    }
                });

        NioDatagramChannel ch = (NioDatagramChannel) b.bind(groupAddress.getPort()).sync().channel();
        ch.joinGroup(groupAddress, ni);
        System.out.println("Multicast server start");
        ch.closeFuture().await();
    } catch (InterruptedException e) {
        e.printStackTrace();
    } catch (Exception e) {
        e.printStackTrace();
    } finally {
        group.shutdownGracefully();
    }
}
handler
public class MulticastReceiveServerHandler extends SimpleChannelInboundHandler {
public MulticastReceiveServerHandler(StringRedisTemplate redisTemplate) {
this.redisTemplate = redisTemplate;
}

private StringRedisTemplate redisTemplate;
private static int i = 0;

@Override
public void channelRead0(ChannelHandlerContext ctx, DatagramPacket packet) throws Exception {
    ByteBuf readBuffer = packet.copy().content();
    byte[] tempDatas = new byte[Constant.PDXP_DATA_LENGTH];
    readBuffer.readBytes(tempDatas);
    readBuffer.release();
    System.out.println("receive send messages" + i++ );

}

@Override
public void channelReadComplete(ChannelHandlerContext ctx) {
    ctx.flush();
}

@Override
public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {
    cause.printStackTrace();
}

send:

public void run() {
EventLoopGroup group = new NioEventLoopGroup();
try {

        NetworkInterface ni = NetUtil.LOOPBACK_IF;
        Enumeration<InetAddress> addresses = ni.getInetAddresses();
        InetAddress localAddress = null;
        while (addresses.hasMoreElements()) {
            InetAddress address = addresses.nextElement();
            if (address instanceof Inet4Address){
                localAddress = address;
            }
        }
        byte[] tempbytes = new byte[1024];
        InputStream in = null;
        in = new FileInputStream("D:\\111.dat");
        Bootstrap b = new Bootstrap();
        b.group(group)
                .channelFactory(new ChannelFactory<NioDatagramChannel>() {

                    @Override
                    public NioDatagramChannel newChannel() {
                        return new NioDatagramChannel(InternetProtocolFamily.IPv4);
                    }
                })
                .localAddress(localAddress, groupAddress.getPort())
                .option(ChannelOption.IP_MULTICAST_IF, ni)
                .option(ChannelOption.SO_REUSEADDR, true)
                .handler(new ChannelInitializer<NioDatagramChannel>() {
                    @Override
                    public void initChannel(NioDatagramChannel ch) throws Exception {
                        ch.pipeline().addLast(new MulticastSendDataClientHandler());
                    }
                });

        DatagramChannel ch = (DatagramChannel) b.bind(groupAddress.getPort()).sync().channel();

        int i=0;

        while (in.read(tempbytes) != -1) {

            ch.writeAndFlush(new DatagramPacket(
                    Unpooled.copiedBuffer(tempbytes),
                    groupAddress)).sync();
            System.out.println(i++);
        }

        ch.close().awaitUninterruptibly();
    } catch (InterruptedException e) {
        e.printStackTrace();
    } catch (Exception e) {
        e.printStackTrace();
    } finally {
        group.shutdownGracefully();
    }
}
handler
public class MulticastSendDataClientHandler extends SimpleChannelInboundHandler {

@Override
public void channelRead0(ChannelHandlerContext ctx, DatagramPacket msg) throws Exception {

}

@Override
public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {
    cause.printStackTrace();
    ctx.close();
}
### Netty version
io.netty
netty-all
4.1.29.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
### OS version (e.g. `uname -a`)

windows or centos7

**Comment by huqingkang** [comment]
Hi, I have a question on the netty project.Is about the netty framework multi - host multicast communication problem.This has been bothering me for more than two months.Please check it. @normanmaurer ,thanks.

**Comment by huqingkang** [comment]
My question has been there for more than a month. Why hasn't anyone replied?
Please help me. Thanks a lot！ @adamv @sprsquish

**Comment by normanmaurer** [comment]
@huqingkang can you try to run the multicast test that we have in netty and see if it works for you ?
https://github.com/netty/netty/blob/4.1/testsuite/src/main/java/io/netty/testsuite/transport/socket/DatagramMulticastTest.java

**Comment by huqingkang** [comment]
Thank you. It's settled today
