### ISSUE TITLE
Unnecessary Execution of notifyListenersNow

### ISSUE THREAD

**Issue by zhengdehui** [netty/netty#8795]
### Expected behavior
When canceling a `DefaultPromise`, should not schedule task when this is no listener for the DefaultPromise

### Actual behavior
When canceling a `DefaultPromise`, a task is scheduled and executed even this is no listener for DefaultPromise, which causes 2% CPU cost in our scenario

### Steps to reproduce

schedule tasks using eventLoop and cancel the `ScheduledFutureTask`
~~~java
channelCtx.channel().eventLoop().schedule(() -> { Thread.sleep(1000); }).cancel(true)
~~~

### Netty version
4.1.25.Final

### JVM version (e.g. `java -version`)
All JVM

### OS version (e.g. `uname -a`)
All OS

![defaultpromise_flame](https://user-images.githubusercontent.com/3377113/51905961-b7459700-23fd-11e9-8d03-95e8f64fb069.png)

**Comment by normanmaurer** [comment]
@zhengdehui sounds like something we could optimize... I will try to have a look or if you have a fix in mind please let me know and submit a PR :)

**Comment by zhengdehui** [comment]
@normanmaurer Actually I was thinking of this way too, by checking the `listeners != null`. However there seems to be a concurrency issue that the cancel() method could be called by another thread and it may not get the latest value of the `listeners` since listeners is not `volatile`. But I am not sure whether it is a good idea to make the listeners volatile to increase the cost of cancel()

**Comment by normanmaurer** [comment]
@zhengdehui from what I see there can't be any concurrency issue here as listeners is only invoked from within the `synchronized` block and if another thread will add a listener in the meantime it will schedule a task if needed.

**Comment by zhengdehui** [comment]
@normanmaurer From #8797 listeners is used outside `synchronized` block

~~~java
    /**
     * Check if there are any waiters and if so notify these.
     * @return {@code true} if there are any listeners attached to the promise, {@code false} otherwise.
     */
    private synchronized boolean checkNotifyWaiters() {
        if (waiters > 0) {
            notifyAll();
        }
        return listeners != null;
    }
~~~

**Comment by normanmaurer** [comment]
@zhengdehui huh ? The whole method os synchronised so why you think it is outside of the scope here ?

**Comment by zhengdehui** [comment]
@normanmaurer oh, sorry,,,, I missed the `synchronized` in the method name line. I think it will solve the problem, will test in our env and give you feedback

**Comment by normanmaurer** [comment]
@zhengdehui thanks... please let me know once you had a chance
