### ISSUE TITLE
AppendableCharSequence.subSequence throws instead of returning empty subsequence

### ISSUE THREAD

**Issue by aimozg** [netty/netty#8796]
I am writing message decoder using as a base approach of `HttpRequestDecoder` (`ByteBuf -> AppendableCharSequence`) and encountered following problem:
`AppendableCharSequence.subSequence(int start, int end);` violates the `CharSequence` interface contract when `start == end`.

### Expected behavior
Return an empty sequence, as specified in `CharSequence.subSequence` doc:
> _if <tt>start == end</tt> then an empty sequence is returned._

### Actual behavior
`IllegalArgumentException: length: 0 (length: >= 1)`

### Minimal yet complete reproducer code (or URL to code)
```
		AppendableCharSequence asc = new AppendableCharSequence(128);
		asc.append('/');
		Matcher m = Pattern.compile("/([^ ]*+)").matcher(asc);
		if (m.matches()) m.group(1);
```
or https://gist.github.com/aimozg/075074c6e6362f800bb1fff21bf6a047

### Netty version
4.124.Final

### Java version
1.8

**Comment by normanmaurer** [comment]
@aimozg sounds like a bug... Can you submit a PR with a test and fix ?

**Comment by aimozg** [comment]
@normanmaurer I'd rather someone more experienced with netty internals do it, really.
I'm unsure how to fix it - 
1) Just return an min-size empty ASC?
2) Allow 0-size in constructors? (Is that used somewhere)
3) Something else?

quick-and-dirty 1) would be 
```diff
    @Override
    public AppendableCharSequence subSequence(int start, int end) {
+       if (start == end) {
+           return new AppendableCharSequence(1);
+       }
        return new AppendableCharSequence(Arrays.copyOfRange(chars, start, end));
    }
```

**Comment by normanmaurer** [comment]
@aimozg please check https://github.com/netty/netty/pull/8798 ... That said you should not use this class as its in the "internal" package and so may be removed / changed etc without notice.
