### ISSUE TITLE
Memory footprint increase after upgrading to 4.1.32.Final

### ISSUE THREAD

**Issue by johnou** [netty/netty#8814]
### Expected behavior

Memory footprint is more or less consistent.

### Actual behavior

Substantial memory footprint increase after updating from 4.1.30.Final to 4.1.32.Final.

### Steps to reproduce

Working on it..

### Minimal yet complete reproducer code (or URL to code)

Working on it..

### Netty version

4.1.32.Final and 4.1.33.Final show a large memory footprint increase compared to 4.1.30.Final.

### JVM version (e.g. `java -version`)

java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

### OS version (e.g. `uname -a`)

Linux 4.14.77-70.82.amzn1.x86_64 #1 SMP Mon Dec 3 20:01:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by johnou** [comment]
![screenshot from 2019-01-30 16-11-59](https://user-images.githubusercontent.com/323497/51990716-eb769180-24a9-11e9-844f-b31ded59a3db.png)

**Comment by normanmaurer** [comment]
@johnou is it direct memory or heap ?

**Comment by johnou** [comment]
@normanmaurer I believe it's direct memory / off-heap because it doesn't seem to be visible in the heap graphs.

**Comment by johnou** [comment]
I have also disabled the allocator and that doesn't seem to help.. not sure where to look next.

```
io.netty.allocator.tinyCacheSize=0
io.netty.allocator.smallCacheSize=0
io.netty.allocator.normalCacheSize=0
io.netty.allocator.numHeapArenas=0
io.netty.allocator.numDirectArenas=0
io.netty.allocator.useCacheForAllThreads=false
```

**Comment by normanmaurer** [comment]
hmm... Can you describe a bit what "native parts" you are using ? Like do you use the native epoll transport. If yes what parts of it. native SSL etc

**Comment by normanmaurer** [comment]
@johnou also even if its native memory you may be able to spot something when looking at heap dumps as we may retain more "heap allocated containers" that wrap the native memory.

**Comment by johnou** [comment]
netty-transport-native-epoll + netty-tcnative-boringssl-static.

There's a combination of client and server application logic using Netty epoll eg. Redisson which uses the event loop (epoll) and dns resolver. Socket server which uses epoll and SSL (io.netty.handler.ssl.SslHandler).

**Comment by johnou** [comment]
Good point on the container objects, I will try and compare the smaller objects this time in the good / bad build heap dumps.

**Comment by johnou** [comment]
@normanmaurer it's epoll.

**Comment by normanmaurer** [comment]
@johnou what exactly in epoll ? And why you say so ?

**Comment by johnou** [comment]
![screenshot from 2019-01-30 18-15-58](https://user-images.githubusercontent.com/323497/51999629-7dd36100-24bb-11e9-853d-248585596c2d.png)

**Comment by johnou** [comment]
working on finding that out now, just got back from picking up the kid.

**Comment by normanmaurer** [comment]
@johnou i am confused ... doesn’t it look like the memory goes up when disabled ?

**Comment by johnou** [comment]
@normanmaurer that's memory available.

**Comment by normanmaurer** [comment]
Got it.. how much more memory or takes compared to 4.1.30 ?

**Comment by johnou** [comment]
Looks like it was 200-300 meg between five JVMs.

**Comment by normanmaurer** [comment]
@johnou and what size is normal ? Also can you also upgrade to 4.1.31.Final and see how it goes. Just to make it easier to find the culprit .

**Comment by johnou** [comment]
In general the memory footprint between epoll and nio is huge in 4.1.33.Final (more than double), 1860G free memory with nio vs 780M with epoll. I will see how it compares with 4.1.31.Final now.

**Comment by johnou** [comment]
![screenshot from 2019-01-30 19-44-37](https://user-images.githubusercontent.com/323497/52004518-8fbb0100-24c7-11e9-9df3-bbf13da4612e.png)

**Comment by johnou** [comment]
@normanmaurer yep I just finished deploying a build with 4.1.31.Final, building 4.1.32.Final right now. Will post here when I have the results.

**Comment by normanmaurer** [comment]
@johnou thx

**Comment by johnou** [comment]
@normanmaurer after further investigation of dependencies and creating canary builds I have finally narrowed it down to DnsAddressResolverGroup constructed by Redisson.. 

```java
        return new DnsAddressResolverGroup(channelType, nameServerProvider);
->
io.netty.resolver.dns.DnsAddressResolverGroup#DnsAddressResolverGroup(java.lang.Class<? extends io.netty.channel.socket.DatagramChannel>, io.netty.resolver.dns.DnsServerAddressStreamProvider)
```
vs

```java
return new DnsAddressResolverGroup(new DnsNameResolverBuilder()
                    .channelType(channelType)
                    .nameServerProvider(DnsServerAddressStreamProviders.platformDefault())
                    .resolvedAddressTypes(ResolvedAddressTypes.IPV4_ONLY));
->
io.netty.resolver.dns.DnsAddressResolverGroup#DnsAddressResolverGroup(io.netty.resolver.dns.DnsNameResolverBuilder)
```

I'm not 100% sure why the workaround class was created in the first place cc @mrniko but now that it has been removed there's a substantial memory footprint increase with epoll..

**Comment by johnou** [comment]
![screenshot from 2019-01-30 21-33-44](https://user-images.githubusercontent.com/323497/52011025-38249180-24d7-11e9-9eb0-e413805735b1.png)

**Comment by normanmaurer** [comment]
@johnou I am not sure I understand what you are saying here... So are you saying it is caused by how redisson uses netty ? Also what code snipped is the good one ? the first or the second ? Did you also upgrade redisson as part of this ?

**Comment by normanmaurer** [comment]
@njhill yeah I wonder if we should try to minimise this a bit. Or at least provide some sort of system property. WDYT ?

**Comment by johnou** [comment]
@normanmaurer I'm going to rerun deploys today, with the original library versions we noticed problems with in production.

**Comment by johnou** [comment]
It's also worth noting that we continuously run DNS lookups which are essentially not cached because the TTL is so low (AWS ElastiCache failover) using netty-dns w/ epoll event loop.

**Comment by johnou** [comment]
I reproduced the memory footprint increase with Netty 4.1.32.Final, no problems with 4.1.31.Final. All using same version of Redisson with epoll enabled.

![screenshot from 2019-01-31 12-52-35](https://user-images.githubusercontent.com/323497/52052779-c17ba880-2557-11e9-915b-e2a034a00b98.png)

**Comment by mrniko** [comment]
@johnou 

Same for 4.1.33.Final?

**Comment by johnou** [comment]
@mrniko yes same for 4.1.33.Final.

**Comment by johnou** [comment]
@njhill based on the test deploys this morning I believe something was changed in 4.1.32.Final wrt netty-dns / epoll.

**Comment by normanmaurer** [comment]
@johnou thanks for all the details.

I have a suspect what's going on. Could you try to revert this commit: https://github.com/netty/netty/commit/d728a72e745d840da397e287ab9c59f810cdadb4 and see if it changes anything ?

I suspect this performance optimisation (to use sendmmsg when using the epoll transport) may now have the effect of lazy init `NativeDatagramPacketArray` which was not done before if you only used the `EpollDatagramChannel` for `DnsResolver` but for nothing else. `NativeDatagramPacketArray` is initialised per `EventLoop` that is used and can be quite heavy (as @njhill pointed out before).

**Comment by johnou** [comment]
@normanmaurer I'll give it a go now.

One thing I noticed is that io.netty.channel.unix.IovArray#IovArray allocates a direct ByteBuffer up front and never deallocates, wouldn't it make more sense if IovArray used the PooledByteBufAllocator and gave back the memory to the pool _after_ a write?

**Comment by normanmaurer** [comment]
@normanmaurer probably not as it would be a very big allocation and so may be costly.

**Comment by johnou** [comment]
@normanmaurer d728a72e745d840da397e287ab9c59f810cdadb4 doesn't revert cleanly, newDnsQueryLifecycleObserver is missing.

**Comment by normanmaurer** [comment]
@johnou if you need any help let me know and I will push a branch with this

**Comment by johnou** [comment]
I think there may have been intermediate commits or a force push, tests are running now. I checked out the 4.1.33 tag, reverted d728a72 but there were compiler errors.

```
Index: resolver-dns/src/main/java/io/netty/resolver/dns/DnsResolveContext.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- resolver-dns/src/main/java/io/netty/resolver/dns/DnsResolveContext.java	(date 1548946092000)
+++ resolver-dns/src/main/java/io/netty/resolver/dns/DnsResolveContext.java	(date 1548946181000)
@@ -515,7 +515,7 @@
                 //                ....
                 if (!res.isAuthoritativeAnswer()) {
                     query(nameServerAddrStream, nameServerAddrStreamIndex + 1, question,
-                            newDnsQueryLifecycleObserver(question), true, promise, null);
+                            newDnsQueryLifecycleObserver(question), promise, null);
                 }
             }
         } finally {
@@ -523,6 +523,10 @@
         }
     }
 
+    private DnsQueryLifecycleObserver newDnsQueryLifecycleObserver(DnsQuestion question) {
+        return parent.dnsQueryLifecycleObserverFactory().newDnsQueryLifecycleObserver(question);
+    }
+
     /**
      * Handles a redirect answer if needed and returns {@code true} if a redirect query has been made.
      */
```

**Comment by normanmaurer** [comment]
@johnou ok cool.. let me know once you have the result.

**Comment by johnou** [comment]
@normanmaurer nailed it, d728a72 is the culprit.

**Comment by normanmaurer** [comment]
@njhill happy if you have a good idea here ;)

**Comment by normanmaurer** [comment]
Alright stay tuned... working on a fix.

**Comment by normanmaurer** [comment]
@johnou https://github.com/netty/netty/pull/8825 could you try the fix and let me know if it fixes the problems you are seeing :)
