### ISSUE TITLE
Websocket handlers to support handshake timeout

### ISSUE THREAD

**Issue by kachayev** [netty/netty#8841]
The same way `SslHandler` provides `handshakeTimeoutMillis` setting... On the application level, it makes sense to limit the time we need to move from `HANDSHAKE_ISSUED` to `HANDSHAKE_COMPLETE` states when upgrading to WebSockets. If there are no objections to introducing this functionality out of the box, I'll do a PR.

**Comment by normanmaurer** [comment]
@kachayev sounds like a good idea... :)
