### ISSUE TITLE
When more than one connection header is present in h2c upgrade request, upgrade fails

### ISSUE THREAD

**Issue by arukshani** [netty/netty#8846]
### Expected behavior
$subject occurs, with this change https://github.com/netty/netty/pull/7824. (@bryce-anderson and @normanmaurer )

Now that more than one connection header is allowed with this https://github.com/netty/netty/pull/7824,
 line https://github.com/netty/netty/blob/737519314153f9146eaf532cd4e945a621cf3fa5/codec-http/src/main/java/io/netty/handler/codec/http/HttpServerUpgradeHandler.java#L295 returns false and the upgrade fails since the connection header value returned from this is not the upgrade but some other connection header value. 

If we are allowing multiple connection headers, then in HttpServerUpgradeHandler I think we need to check  whether any of the connection header value is upgrade and then remove other connection headers. https://tools.ietf.org/html/rfc7540#section-8.1.2.2

### Steps to reproduce
Send an upgrade request with multiple conection headers to HTTP/2 server and the request hangs.

Example request:
GET / HTTP/1.1
Host: localhost:9000
connection: keep-alive
forwarded: by=127.0.0.1
content-length: 0
upgrade: h2c
HTTP2-Settings: AAEAABAAAAIAAAABAAN_____AAQAAP__AAUAAEAAAAYAACAA
connection: HTTP2-Settings,upgrade

### Netty version
From 4.1.33.Final (This issue  started to occur from From 4.1.23.Final onwards)

**Comment by normanmaurer** [comment]
@arukshani sounds about right... Are you interested in providing a PR to fix it ? /cc @bryce-anderson

**Comment by arukshani** [comment]
Yup. Will send a PR with the fix @normanmaurer
