### ISSUE TITLE
WARN  KQueueEventLoop - events[[1, 88, -1]]=[[1, 88, -1], {}] had no channel!

### ISSUE THREAD

**Issue by amizurov** [netty/netty#8849]
### Expected behavior
No warning ``2019-02-06 23:05:16.068 [KQueueEventLoopGroup-2-2] WARN  i.n.channel.kqueue.KQueueEventLoop - events[[1, 88, -1]]=[[1, 88, -1], {}] had no channel!``
### Actual behavior
Unexpected warning when client application kill -9 or reset peer
``2019-02-06 23:05:16.068 [KQueueEventLoopGroup-2-2] WARN  i.n.channel.kqueue.KQueueEventLoop - events[[1, 88, -1]]=[[1, 88, -1], {}] had no channel!``

Not received reset peer exception in ``exceptionCaught(ChannelHandlerContext ctx, Throwable cause)``
when interrupt client socket
### Steps to reproduce
Run snippet code below and kill client

### Minimal yet complete reproducer code (or URL to code)

public class ClientKQueue {

    public static void main(String[] args) throws Exception {
        Bootstrap clientBootstrap = new Bootstrap()
            .channel(KQueueSocketChannel.class).group(new KQueueEventLoopGroup())
            .handler(new ChannelInboundHandlerAdapter());
        Channel channel = clientBootstrap.connect("localhost", 8080).awaitUninterruptibly().channel();

        channel.closeFuture().awaitUninterruptibly();
    }
}

public class ServerKQueue {

    public static void main(String[] args) {
        ServerBootstrap serverBootstrap = new ServerBootstrap()
            .channel(KQueueServerSocketChannel.class).group(new KQueueEventLoopGroup())
            .childHandler(new ChannelInitializer() {

                @Override
                protected void initChannel(Channel ch) throws Exception {
                    ch.pipeline()
                        .addLast(new ChannelInboundHandlerAdapter() {

                            @Override
                            public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
                                System.out.println(cause.getMessage());
                            }
                        });
                }
            });

        Channel channel = serverBootstrap.bind(8080).awaitUninterruptibly().channel();
        channel.closeFuture().awaitUninterruptibly();
    }
}

### Netty version
4.1.33

### JVM version (e.g. `java -version`)
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

### OS version (e.g. `uname -a`)
18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

**Comment by amizurov** [comment]
Hi, @normanmaurer I think it's related with Fix ClassCastException and native crash when using kqueue transport. (#8665)

**Comment by normanmaurer** [comment]
will check

**Comment by amizurov** [comment]
> will check

Thanks a lot. If you need additional info, ping me.

**Comment by normanmaurer** [comment]
@amizurov hmm how does your code reproduce this ? Where do you interrupt the socket ?

**Comment by amizurov** [comment]
@normanmaurer Sorry if not clear, in this example I simple kill -9 client in 4.1.32 it's work fine, but in 4.1.33 I got a ``WARN ..  had no channel!```. I'll tried make reproducer with reset by peer exception, that I got on production system.

**Comment by kachayev** [comment]
I'm working on introducing KQueue transport support to the Aleph library, and I can confirm that with `4.1.33.Final` such warnings happen pretty randomly, hard to tell what is the root cause.

```
user=> [aleph-netty-client-event-pool-1] WARN io.netty.channel.kqueue.KQueueEventLoop - events[1]=[69, -1] had no channel!
user=> [aleph-netty-client-event-pool-2] WARN io.netty.channel.kqueue.KQueueEventLoop - events[1]=[71, -1] had no channel!
```

**Comment by normanmaurer** [comment]
@amizurov @kachayev can you check https://github.com/netty/netty/pull/8881 ?

**Comment by kachayev** [comment]
@normanmaurer I'll check in a couple of hours. 

p.s. One small thing, I think `test.log` was added by mistake.

**Comment by normanmaurer** [comment]
@kachayev ups yes... let me remove.

**Comment by kachayev** [comment]
@normanmaurer Nice! Works on my end. I didn't have a strong reproducer but I saw quite a few WARN messages while running my tests. No I don't see any of those. Thanks.

**Comment by amizurov** [comment]
@normanmaurer Thanks, looks good. No more WARN messages on my side.
