### ISSUE TITLE
a place for benchmarks

### ISSUE THREAD

**Issue by carrot-garden** [netty/netty#885]
since now there is official netty module for metrics, 
the question comes: what is appropriate place for benchmarks?

in my case, I store code in tests:
https://github.com/barchart/barchart-udt/blob/master/barchart-udt-core/src/test/java/bench/transfer/BenchXferOne.java

and publish results on wiki:
https://github.com/barchart/barchart-udt/wiki/bench.transfer.BenchXferOne

if you enable wiki here, and establish rules for naming and storing benchmarks code and results, 
I think we could assemble quite broad statistics from many many people.

**Comment by normanmaurer** [comment]
Let me just close this as we have the microbenchmark module now
