### ISSUE TITLE
Support semicolon as a normal character in URI (no longer a parameter separator)

### ISSUE THREAD

**Issue by marcban** [netty/netty#8855]
### Expected result
According to the 2014 W3C Recommendation, semicolon is now illegal as a parameter separator in a http URI.
`?foo=bar;baz` means the parameter `foo` will have the value `bar;baz`

see https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#url-encoded-form-data
(thanks to https://stackoverflow.com/questions/3481664/semicolon-as-url-query-separator)

### Current result
The URI decoder now supports the obsolete 1999 W3C recommendation
 `?foo=bar;baz` is decoded as `?foo=bar & baz=`

(see QueryStringDecoder.java, line 230 :  `case '&': case ';':` both characters are handled equally)

### Netty version
tested (through vert.x) on 1.4.19

### JVM version (e.g. `java -version`)
1.8.0_60

### OS version (e.g. `uname -a`)
Windows i686-pc Intel

_Of course this issue is linked to  #3044 and #2896, but as the norm changed, I suppose it's better to open a new issue_

**Comment by normanmaurer** [comment]
@slandelle WDYT ?

**Comment by slandelle** [comment]
👍 I've been parsing URIs this way (HTML5's form-url-encoded) for many years in both AHC and Gatling and I don't recall anyone ever complaining that semi-colon wasn't interpreted as a parameter separator.

**Comment by marcban** [comment]
Note also that when encoding an URL with java URI.tostring(), semicolons are _not_ encoded, so the client has extra replaces to do before sending the request

**Comment by normanmaurer** [comment]
@slandelle @marcban so I am a bit confused what should be done here... Anyone interested in a PR ?

**Comment by marcban** [comment]
For me the correction would only be to delete the `case ‘;’ :` on line 230 of QueryStringDecoder.java. But maybe there are tests to correct also. Never done a PR but I can try...

**Comment by slandelle** [comment]
> Note also that when encoding an URL with java URI.tostring(), semicolons are _not_ encoded, so the client has extra replaces to do before sending the request

I suppose you mean: if my server is Netty and uses `QueryStringDecoder`, I have to encode semicolons manually so `QueryStringDecoder` doesn't mess up with parsing, as URI.toString() won't encode them (which is expected).

> For me the correction would only be to delete the `case ‘;’ :` on line 230 of QueryStringDecoder.java. But maybe there are tests to correct also. Never done a PR but I can try...

This is a low hanging fruit so it would be a perfect ft for a first PR indeed :)

**Comment by marcban** [comment]
1/ exactly!
2/ I have some docs to read first... :-)
