### ISSUE TITLE
Feature request: SSH codec

### ISSUE THREAD

**Issue by kevemueller** [netty/netty#8860]
To whom it may concern,
I am wondering why there is no first class SSH codec available for netty. I am aware of jSCH, mina-sshd and termd as useable SSH implementations, but despite mina-sshd offering a netty wrapper the programming model is very different from pure netty. 
Is there any specific reason why this was left out? Is there interest in addressing this?

Cheers,

Keve

**Comment by normanmaurer** [comment]
@kevemueller there are currently no plans to add this to netty itself. That said there is no reason why you could not implement something like this by yourself and host it in your own repository.

**Comment by vietj** [comment]
there is one SSH adapter available in Apache SSHD https://github.com/apache/mina-sshd/tree/master/sshd-netty

it's not a codec but it remains very easy to use and does all the heavy lifting for you.

**Comment by kevemueller** [comment]
Hi @normanmaurer, thanks for the heads-up. I fully understand that netty is perfectly suitable as a building block for a ssh client/server stack. I was just wondering why nobody ever did this, despite its clear advantages. I understand that you prefer not to have this in netty (core).

Hi @vietj, yes I am aware of Apache Mina SSHD and your work of linking it against a netty backbone. I am currently using this path, but it requires some un-netty work to get a pipeline on top of the provided SshChannel (which is my use case, tunneled TCP as well as pipeline on top of the SSH exec stream). Also this work creates a lot of latency due to the unnecessary conversion from OIO to the pipeline.

As @normanmaurer  spoke a verdict, feel free to close this issue. Anybody interested in getting this further is welcome to contact me in PM.
