### ISSUE TITLE
Cause Exception is Swallowed when ChannelOperationsHandler#channelRead throws

### ISSUE THREAD

**Issue by mld-ger** [netty/netty#8861]
I had the case that my application throwed an IllegalStateException when ChannelOperationsHandler#channelRead was invoked. The Exception is caught by 
```
catch (Throwable err) {
    Exceptions.throwIfFatal(err);
    exceptionCaught(ctx, err);
    ReferenceCountUtil.safeRelease(msg);
}
```
(ChannelOperationsHandler:163)

But the Throwable is never printed since ReferenceCountUtil#safeRelease is invoked without passing the original error.
This behavior is unexpected because the Exception that gets thrown in the end does not reflect the original cause but instead an arbitrary Netty error.

I use Netty-common version 4.1.31.Final

**Comment by normanmaurer** [comment]
@mid-ger Netty does not contain any class Called `ChannelOperationsHandler`.

**Comment by kachayev** [comment]
I think the issue refers to `reactor-netty` project. @mld-ger right?

**Comment by mld-ger** [comment]
You're absolutely right @kachayev. I got confused by the stacktrace. I'll open an issue there.
