### ISSUE TITLE
DefaultFileRegion.transferTo with invalid count may cause hang 

### ISSUE THREAD

**Issue by georgeOsdDev** [netty/netty#8868]
### Expected behavior

`DefaultFileRegion.transferTo` will end successfully or throws Exception.

### Actual behavior

Thread will be hang and CPU usage increase to 100%

### Steps to reproduce

Initialize `DefaultFileRegion` with `count` larger than the actual `FileChannel ` size.

```
new DefaultFileRegion(raf.getChannel(), 0, fileLength)
```

### Minimal yet complete reproducer code (or URL to code)

https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http/file/HttpStaticFileServerHandler.java#L175-L193

Truncate files from another process between L175 and L192

Related issue.
https://github.com/xitrum-framework/xitrum/issues/675

### Netty version
4.1

### JVM version (e.g. `java -version`)

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

### OS version (e.g. `uname -a`)

Darwin OshidaIMac.local 17.7.0 Darwin Kernel Version 17.7.0: Wed Oct 10 23:06:14 PDT 2018; root:xnu-4570.71.13~1/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
@georgeOsdDev what you suggest we should do here ? You are saying we should check in the constructor that you do not construct something "invalid" ?

**Comment by georgeOsdDev** [comment]
I'm not sure to check `count` in the constructor.
`sun.nio.ch.FileChannelImpl` does not throws Exception even if `count ` is larger than real file size.
https://docs.oracle.com/javase/8/docs/api/java/nio/channels/FileChannel.html#transferTo-long-long-java.nio.channels.WritableByteChannel-

---
When CPU usage increase, It seems `NioSocketChannel.doWrite` is called repeatedly. So it seems to be a matter of eventLoop handling
```
io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:375)
io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934)
io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:367)
io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:639)
io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
```

When `count` is *not* larger than realSize,  `in.remove();` is called and doWrite is called just once.
https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/nio/AbstractNioByteChannel.java#L238

**Comment by normanmaurer** [comment]
Looking into it

**Comment by normanmaurer** [comment]
@georgeOsdDev PTAL https://github.com/netty/netty/pull/8885
