### ISSUE TITLE
in  websocket handshake

### ISSUE THREAD

**Issue by tianzhenjiu** [netty/netty#8869]
When the websocket handshake, your http header is all lowercase. If the Sec-WebSocket-Key is also lowercase, it will return 400.

**Comment by amizurov** [comment]
Hi, @tianzhenjiu Could you please provide WebSocket upgrade request, because ``WebSocketServerHandshaker13`` can throw exception if this header is absent
```
CharSequence key = req.headers().get(HttpHeaderNames.SEC_WEBSOCKET_KEY);
        if (key == null) {
            throw new WebSocketHandshakeException("not a WebSocket request: missing key");
        }
```

**Comment by normanmaurer** [comment]
@tianzhenjiu ping

**Comment by normanmaurer** [comment]
closing as no response from the reporter. @tianzhenjiu please reopen if you still think this is an issue.
