### ISSUE TITLE
http: netty does not upgrade to https

### ISSUE THREAD

**Issue by SplotyCode** [netty/netty#8872]
### Expected behavior
Netty handles the HTTP response or upgrades it to https
### Actual behavior
Netty handles to https requests fine but fails on http request eg resets connection (upgrade-Insecure-Requests	
1 does not change anything)
### Steps to reproduce
Netty pipeline with SSLHandler, HttpRequestDecoder, HttpObjectAggregator, HttpResponseEncoder and HttpContentCompressor

### Minimal yet complete reproducer code (or URL to code)
https://hastebin.com/afabacevag.java
The SSL context is a self-signed one
### Netty version
4.1.24.Final
### JVM version (e.g. `java -version`)
java-8-openjdk-amd64
### OS version (e.g. `uname -a`)
Linux 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
Please provide more details.... Like how exactly you test it, what exception, what you expect etc.

**Comment by SplotyCode** [comment]
No exceptions. I just added the ssl handler to a project and if I access with https I don't get redirected the requests with http are just not handled

**Comment by SplotyCode** [comment]
I really don't see an opertunity to allow https and redirect http to https.
In SSLHandler#decodeJdkCompatible directly calls setHandshakeFailure() both of the methods are private so there is no change to avoid that Http request are blocked by the SSLHandler

**Comment by SplotyCode** [comment]
OptionalSslHandler is the key here. After reading this https://github.com/netty/netty/pull/6438
