### ISSUE TITLE
ChunkedWriteHandler does not close successful ChunkedInputs

### ISSUE THREAD

**Issue by lutovich** [netty/netty#8875]
### Expected behavior
`ChunkedWriteHandler` invokes `ChunkedInput#close()` after the input is fully consumed and `ChunkedInput#isEndOfInput()` returns `true.`

### Actual behavior
`ChunkedInput#close()` is not invoked when the input completes successfully. This can result in resource leaks when the input is based on an external resource, like a file handle.

### Steps to reproduce

Run the attached test.

### Minimal yet complete reproducer code (or URL to code)

```java
@Test
public void testCloseSuccessfulChunkedInput() throws Exception {
    final int totalChunks = 10;
    final AtomicBoolean closeInvoked = new AtomicBoolean();

    ChunkedInput<ByteBuf> input = new ChunkedInput<ByteBuf>() {
        int chunksProduced = 0;

        @Override
        public boolean isEndOfInput() throws Exception {
            return chunksProduced >= totalChunks;
        }

        @Override
        public void close() throws Exception {
            closeInvoked.set(true);
        }

        @Override
        public ByteBuf readChunk(ChannelHandlerContext ctx) throws Exception {
            return readChunk(ctx.alloc());
        }

        @Override
        public ByteBuf readChunk(ByteBufAllocator allocator) throws Exception {
            ByteBuf buf = allocator.buffer(4);
            buf.writeInt(chunksProduced);
            chunksProduced++;
            return buf;
        }

        @Override
        public long length() {
            return totalChunks;
        }

        @Override
        public long progress() {
            return chunksProduced;
        }
    };

    EmbeddedChannel ch = new EmbeddedChannel(new ChunkedWriteHandler());

    ch.writeAndFlush(input).sync();

    for (int i = 0; i < totalChunks; i++) {
        ByteBuf buf = ch.readOutbound();
        assertEquals(i, buf.readInt());
    }

    assertTrue(closeInvoked.get()); // this assertion fails
}
```

### Netty version

Problem exists only in `4.1.33.Final`.

### JVM version (e.g. `java -version`)

```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

### OS version (e.g. `uname -a`)

```
Darwin MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

This issue can be fixed by closing the input in a write future listener [here](https://github.com/netty/netty/blob/netty-4.1.33.Final/handler/src/main/java/io/netty/handler/stream/ChunkedWriteHandler.java#L286-L287) after the input is consumed. I have a branch with a tentative fix https://github.com/lutovich/netty/commit/1534f7778ad8c14d488fe17916c5baed5aaedc60 and can create a PR if it looks okay.

**Comment by normanmaurer** [comment]
@lutovich fix looks good. Please submit a PR :)

**Comment by lutovich** [comment]
@normanmaurer done, thank you.
