### ISSUE TITLE
Possible LEAK using 4.1.24.Final

### ISSUE THREAD

**Issue by asafm** [netty/netty#8878]
### Expected behavior
No "LEAK" messages printed

### Actual behavior
The following ERROR log is printed:
```
LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
	io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.lang.Thread.run(Thread.java:748)
```
### Steps to reproduce

I don't have yet a reproducible project yet. My Netty server is receiving traffic from both HTTP and TCP. 

What I wanted to get is some hints to try to focus on specific area in the server.
Do you think this exception shows it's not a buffer I create, thus it's a bug in Netty? Or that I can somehow (how?) can cause this in my code?
Would love to get some hints.

### Minimal yet complete reproducer code (or URL to code)
Not available yet

### Netty version
4.1.24.Final

### JVM version (e.g. `java -version`)
1.8.151_b12
### OS version (e.g. `uname -a`)
Ubuntu SMP Wed Oct 3 14:52:35 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
You most likely do not correctly release the buffer. Please turn on the paranoid leak detection and check the report there. It should give you a clue. Also you should upgrade as the version is really old.

Please reopen with more details if you still think its a netty issue
