### ISSUE TITLE
DNS Issue on Kubernetes (ndots=5 + search domain query)

### ISSUE THREAD

**Issue by m1schka** [netty/netty#8880]
### Expected behavior
DNS Resolution works always

### Actual behavior
Some hosts are not resolving and keep getting DnsNameResolverTimeoutException. 

```
SearchDomainUnknownHostException: Search domain query failed. Original hostname: 's3-eu-central-1.amazonaws.com' failed to resolve 's3-eu-central-1.amazonaws.com.default.svc.cluster.local' after 2 queries 
    at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:845)
    at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:806)
    at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:333)
    at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:322)
    at io.netty.resolver.dns.DnsResolveContext.access$500(DnsResolveContext.java:62)
...
(17 additional frame(s) were not displayed)

DnsNameResolverTimeoutException: [/100.64.0.10:53] query timed out after 5000 milliseconds (no stack trace available)
```
The issue is not only relevant for cluster external dns entries, but also when querying `<service-name>`, which should resolve when using search path. using the FQDN `<service-name>.default.svc.cluster.local` makes the issue less noticable, except for external names due to the ndots.

The DNS server (coredns pod) is located on the same kubernetes node. performing dns queries on the shell using `dig +search [...]` or `nslookup` always yield the correct result

### Steps to reproduce
inside a kubernetes pod, try resolving internal names and external names. doesn't seem to be a network issue, I've seen it on weave ([with the tc fix applied](https://github.com/Quentin-M/weave-tc)) and flannel-vxlan and all other non-netty pods don't have any issues with DNS

this is the `/etc/resolv.conf`
```
nameserver 100.64.0.10
search default.svc.cluster.local svc.cluster.local cluster.local eu-central-1.compute.internal
options ndots:5
```
this rules out the fix applied for #8261 because it's a single dns server

### Minimal yet complete reproducer code (or URL to code)
working on that part right now. Really hard to make it reproducable. I've tried ruling out everything else, see above
### Netty version
4.1.30 (through Vert.x 3.6.3)

### JVM version (e.g. `java -version`)
8
### OS version (e.g. `uname -a`)
CentOS 7.6 (Docker)

**Comment by normanmaurer** [comment]
@m1schka let me know once you have a reproducer

**Comment by normanmaurer** [comment]
Also please try to update to latest Netty version and see if this still exists.

**Comment by normanmaurer** [comment]
@m1schka any update ?

**Comment by kachayev** [comment]
@m1schka Actually, this might be the problem with `kube-dns` not with Netty. [Here](https://github.com/kubernetes/kubernetes/issues/45976) is a long discussion about performance problems with the default settings of search domains + ndots=5. Is this the case?

**Comment by m1schka** [comment]
sorry for the delay.

@normanmaurer it's hard for me to write a reproducer since I'm not directly using netty but vert.x. any help is appreciated.

It still occurs like ~1-2 times per day but significantly less after changing to FQDN for kubernetes services (i.e using `.<namespace>.svc.cluster.local`).

@kachayev I'm not using kube-dns but coredns. I'm aware of issues with kube-dns. Also I don't use an alpine based image (which shouldn't matter anyway, since the dns query is not done by musl) and I shouldn't be affected by [conntrack issue because I installed weave-tc](https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts).

Next step for me is disabling the ipv6. maybe that helps

**Comment by m1schka** [comment]
I'm closing this issue until I've got a full picture on this issue. also watching https://github.com/weaveworks/weave/issues/3287 in the meantime

**Comment by m1schka** [comment]
disabling ipv6 seems to fix this issue

**Comment by gkozyryatskyy** [comment]
@m1schka 
Seems like I have the same issue. Also using kubernetes + vertx + netty.
disabled IPv6 with ```ENV JAVA_OPTS="$JAVA_OPTS -Djava.net.preferIPv4Addresses=true -Djava.net.preferIPv4Stack=true"``` but still see the issue time to time (~ once a day for now).

Any suggestions? Did you fix the issue completely?

**Comment by garyschulteog** [comment]
We had this same issue and found it was related to a linux kernel udp bug, detailed here:
https://blog.quentin-machu.fr/2018/06/24/5-15s-dns-lookups-on-kubernetes/

What we ended up doing was adding a `single-request-reopen` dnsC=onfig for our deployments to ensure we had sequential lookups.  This 100% fixed our problem, e.g. 
```
    spec:
      dnsConfig:
        options:
          - name: single-request-reopen
```
Incidentally the alpine linux base images we were using use libmusl rather than glibc, so the single-request-reopen option for resolv.conf did nothing until we changed our base images to debian:stretch (since it is glibc based)

**Comment by caicarabruno** [comment]
https://pracucci.com/kubernetes-dns-resolution-ndots-options-and-why-it-may-affect-application-performances.html
