### ISSUE TITLE
Websocket client closing handshake to support "force close" after given timetout

### ISSUE THREAD

**Issue by kachayev** [netty/netty#8883]
RFC455 defines that, generally, a WebSocket client should not close a TCP connection as far as a server is the one who's responsible for doing that. In practice, when I do not control the server, this might lead to connections leak if the server does not comply with the RFC.

[RFC455#7.1.1](https://tools.ietf.org/html/rfc6455#section-7.1.1) says

> In abnormal cases (such as not having received a TCP Close from the server after a reasonable amount of time) a client MAY initiate the TCP Close.

I suggest to add `forceCloseAfterMillis` option to `WebSocketClientHandshaker` (and to `WebSocketClientProtocolHandler` appropriately) and schedule a channel close when necessary after `CloseWebSocketFrame` being flushed [here](https://github.com/netty/netty/blob/f176384a729c1d9352c9ed878b9b967ca2f31bf8/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshaker.java#L430-L435). If there's no objections, I'm happy to provide a PR.

**Comment by normanmaurer** [comment]
@kachayev this sounds good... Its also inline with what we do in SslHandler.

**Comment by kachayev** [comment]
@normanmaurer I'll do a PR for WebSockets first, as I know this code quite well. Will check `SslHandler` later ;)

**Comment by normanmaurer** [comment]
Sorry maybe I was not clear here... we have this kind of code already in SslHandler. I just wanted to mention it as it may gives you some good examples

**Comment by kachayev** [comment]
Ah, okay! Now it's clear. I thought you meant that we need to do the same for SSL. Thanks!
