### ISSUE TITLE
DNS query encoder emits potentially released buffer  

### ISSUE THREAD

**Issue by kachayev** [netty/netty#8884]
I don't have a reproducer, just spotted it reading the code [here](https://github.com/netty/netty/blob/d02b51965f6b4906ca1f8f9648c2eb801df7b94a/codec-dns/src/main/java/io/netty/handler/codec/dns/DatagramDnsQueryEncoder.java#L65-L76).

If an exception was thrown somewhere in `encodeHeader`, `encodeQuestions` or `encodeRecords` we release the buffer and still emit a new `DatagramPacket` with it. Hard to tell what may go wrong with encoders but spitting out a packet, in that case, seems unreasonable.

**Comment by normanmaurer** [comment]
@kachayev huh ? Why would we emit a new DatagramPacket ? We will never reach the `out.add(...)` in this case. What I am missing ?

**Comment by kachayev** [comment]
Oh... Yeah, my bad. Misinterpreted it while debugging 🤦‍♂️
