### ISSUE TITLE
Why we need to reset the readingChunks =true in the Handler of http/upload examples?

### ISSUE THREAD

**Issue by gfYaya** [netty/netty#8892]

**Comment by gfYaya** [comment]
I'm a green hand in netty, then I started to learn netty by the examples in the github.
Now I start the Http upload exersice by this demo: https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http/upload/HttpUploadServerHandler.java.
From line 168 to 171, 
if (readingChunks) {
                // Chunk version
                responseContent.append("Chunks: ");
                readingChunks = true;
  }

If the variable  readingChunks is true , why I need to reset readingChunks = true in this block? And the Channel ,ChannelHandler is thread safe right?Is this a fault?
I'm so sorry for that my English is so broken.

**Comment by gfYaya** [comment]
Oh , I'm so sorry, The channel Handler is not thread safe. How to delete this issues?
I'm so sorry for that....
Sorry.

**Comment by gfYaya** [comment]
Because a ChannelHandler can belong to more than one ChannelPipeline, it can be
bound to multiple ChannelHandlerContext instances. A ChannelHandler intended
for this use must be annotated with @Sharable; otherwise, attempting to add it to
more than one ChannelPipeline will trigger an exception. Clearly, to be safe for use
with multiple concurrent channels (that is, connections), such a ChannelHandler
must be thread-safe.
This listing shows a correct implementation of this pattern.

Netty in Action ,Page 91.  the last sentence:Clearly, to be safe for use
with multiple concurrent channels (that is, connections), such a ChannelHandler
must be thread-safe. So I think, the ChannelHandler is thread safe.

**Comment by normanmaurer** [comment]
Fixed here https://github.com/netty/netty/pull/8976

**Comment by gfYaya** [comment]
Thank you very much for your reply, normanmaurer .
