### ISSUE TITLE
Can't find PingMessage class from javadoc example

### ISSUE THREAD

**Issue by cemehehko** [netty/netty#8893]

**Comment by normanmaurer** [comment]
Which class exactly you are talking about and where exactly is it linked ?

**Comment by cemehehko** [comment]
In class IdleStateHandler there are:
 * // Handler should handle the {@link IdleStateEvent} triggered by {@link IdleStateHandler}.
 * public class MyHandler extends {@link IdleStateAwareChannelHandler} {
 *
 *     {@code @Override}
 *     public void channelIdle({@link ChannelHandlerContext} ctx, {@link IdleStateEvent} e) {
 *         if (e.getState() == {@link IdleState}.READER_IDLE) {
 *             e.getChannel().close();
 *         } else if (e.getState() == {@link IdleState}.WRITER_IDLE) {
 *             e.getChannel().write(new PingMessage());
 *         }
 *     }
 * }

I have found PingMessage is replaced by PingWebSocketFrame.
Please, correct the doc.

**Comment by cemehehko** [comment]
I've found IdleStateHandler is not only about WebSocket. It is my mistake. MyPingMessage or MyProtocolPingMessage name will be better.

**Comment by kachayev** [comment]
@normanmaurer Ref to the Javadoc in question: https://netty.io/4.1/api/index.html?io/netty/handler/timeout/IdleStateHandler.html

**Comment by normanmaurer** [comment]
It's just an example of a class and not part of netty itself. So I think it is fine ?

**Comment by darklynx** [comment]
I agree with @cemehehko that `MyPingMessage` would be less confusing

**Comment by normanmaurer** [comment]
@darklynx if you feel strongly about it please open a PR

**Comment by darklynx** [comment]
Thanks, I'll do so.

I just fell into the same trap as @cemehehko and had to google for `PingMessage` class, since it look so tempting to reuse the example logic :)
