### ISSUE TITLE
[Netty 5] Make HttpMethod an Enum

### ISSUE THREAD

**Issue by Bennett-Lynch** [netty/netty#8897]
Why is [HttpMethod](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpMethod.java) not an enum?

Is it so that it can be extended?  If so, is there any valid concern in not being able to extend it?

Making it an enum would make comparisons cleaner, possible input values more transparent, and allow it to be used in data structures like [EnumMap](https://docs.oracle.com/javase/8/docs/api/java/util/EnumMap.html) and [EnumSet](https://docs.oracle.com/javase/8/docs/api/java/util/EnumSet.html).

@doom369 @Scottmitch @trustin

**Comment by trustin** [comment]
It is to support other HTTP-like protols like STOMP and RTSP. It is also useful to handle a non-standard method which is not defined in RFCs. For example, a user could add support for a new HTTP method like PATCH even before we add it to the list. (We already support PATCH, but it's just an example.)

However, I think using an enum has its own advantage, so I'm not against reconsidering this old decision.

**Comment by Bennett-Lynch** [comment]
Just to be pedantic, and to argue in favor of the enum approach, would it be fair to say that "HTTP-like" should not be an "HttpMethod"?

Understood on the RFC-extension case, though I'm not sure how legitimate of a concern that is.

I'm an enum-junky, and this has always been sort of a Netty API annoyance for me.

**Comment by trustin** [comment]
I agree with you that they'd better using `StompMethod` or `RtspMethod`. I think it's doable with some refactoring in 5. Didn't give much thought, but it's good time to make it happen.

**Comment by doom369** [comment]
@Bennett-Lynch +1. I considered this too. However, from performance point of view this doesn't make any sense as `HttpMethod` does equals by reference and, in fact, uses `EnumMap` for lookups. Code still could be simplified a bit with enums.

**Comment by slandelle** [comment]
I’m strongly against enforcing a closed list of HTTP methods. I’ve been reported custom HTTP methods many times, eg Varnish’s PURGE https://varnish-cache.org/docs/trunk/users-guide/purging.html. One never know what users will come up with, all the more when this works fine with most common technologies, eg curl.

**Comment by SplotyCode** [comment]
What we could do is creating an interface named HttpMetod that has a getName() method and then an Enum named DefaultHttpMethod what implements HttpMetod.

If the request it a standard Http Method we could assign the enum and if not we create HttpMetod interface. If you like that design I could do a PR.

**Comment by vietj** [comment]
WebDav has specific HTTP methods too.

**Comment by normanmaurer** [comment]
@Bennett-Lynch @trustin @doom369 WDYT about the concerns raised here ? I think with all this in mind it would be better to just keep it as it is.

**Comment by trustin** [comment]
Yes. Valid concerns raised.

**Comment by Bennett-Lynch** [comment]
Yes, I think enough valid concerns were raised.  Closing this out.  Thanks everyone for your feedback.
