### ISSUE TITLE
Suspected that HttpToHttp2ConnectionHandler.java has a bug

### ISSUE THREAD

**Issue by tommy-ham** [netty/netty#8898]
Hello, I'm using HttpToHttp2ConnectionHandler class to send responses to client in multi-threaded environment. 

While reading the class, I have found that the currentStreamId was defined as a global variable. 

I think that the variable should not be global because the write method on this handler might be called by multiple threads simultaneously so it cause the crash of the variable.

If the code is right, please explain how you to prevent crashes the variable.

Thanks.

**Comment by normanmaurer** [comment]
The handler must not be shared between different Channels and so it is guaranteed that its methods are always executed by the same EventLoop which means by the same thread. If you trigger a write from outside of the EventLoop it will be dispatched on the EventLoop and so run on the right thread.

**Comment by tommy-ham** [comment]
Thank you for your response and kindly explain.

I understood your explain. but I have a additional question related with this.
I think that if I use FullHttpResponse as parameter then your explain is right but If I use two message with HttpMessage and HttpContent seperately then the header frame and the data frame might have a different streamId each other.  

Thank you.
