### ISSUE TITLE
Trustmanager with Openssl as provider getting netty.io certificate before the actual server certificate

### ISSUE THREAD

**Issue by pavanrangain** [netty/netty#8911]
Hi team,
I am trying to use netty-tcnative with openssl as provider. For client connections we are trying to give a trustmanager factory to check the validity of server certificate (using thumbprint/custom trust store). This works but first time the trustmanager 'checkServerTrusted' method is always called with certificate whose issuer is netty.io. Even if we throw CertificateException this callback is called again with a valid server certificate. How can we avoid the first callback with netty.io certificate?

### Expected behavior
Callback being called only once with server certificate
### Actual behavior
Callback is being called twice. First time with netty.io certificate and second time with the server cert chain
### Steps to reproduce#
Run the reproducer attached
[OpenSSLTrustManagerSample.txt](https://github.com/netty/netty/files/2924308/OpenSSLTrustManagerSample.txt)

Check that first callback happens with cert length = 1 and this certificate has Subject: CN=netty.io

NUMBER OF CERTS: 1
------------------ CERTIFICATE -----------------------------------
[
[
  Version: V3
  Subject: CN=netty.io
  Signature Algorithm: SHA1withRSA, OID = 1.2.840.113549.1.1.5

  Key:  Sun RSA public key, 1024 bits
  modulus: 98414152349892151735199774368410346701252114125227183448915187279783844011579568821075167731725384054481983654309585598526026514506105336408359484491726263818697737710334412948288031793758024621735253658535411697001251417167051932084275395575445742717036704533511501201000065338129039966180837289329574935307
  public exponent: 65537
  Validity: [From: Fri Oct 20 18:16:36 UTC 2017,
               To: Fri Dec 31 23:59:59 UTC 9999]
  Issuer: CN=netty.io
  SerialNumber: [    f73d2c79 8afcd388]

]
  Algorithm: [SHA1withRSA]
  Signature:
0000: 70 2D B7 05 40 31 3B 65   33 49 A0 3E 17 AC 5A D7  p-..@1;e3I.>..Z.
0010: C6 53 EC B8 26 7B 94 D3   1C 60 86 EE 1E 2A 56 57  .S..&....`...*VW
0020: A9 E4 6B 6E 0B C5 5B 64   65 EE 1A 99 B2 B0 FD 26  ..kn..[de......&
0030: 71 53 D0 94 6D 29 F1 06   70 69 07 D2 F5 FD CD 28  qS..m)..pi.....(
0040: BE B7 AD D2 A2 87 A8 33   96 B3 6D 35 F9 7B 5B 4B  .......3..m5..[K
0050: 97 EA 40 79 B8 C5 EB D4   54 0C 09 78 15 E6 0D 31  ..@y....T..x...1
0060: AF C6 D1 75 D4 EE EF 7C   31 D0 13 10 D7 47 CC 95  ...u....1....G..
0070: 63 ED E3 69 A3 B9 DA 9F   80 FE 76 77 31 82 6D 77  c..i......vw1.mw

]

### Netty version
netty-tcnative = 2.0.20.Final:linux-x86_64
netty version = 4.1.32.Final
using apr with openssl version = 1.0.2q
### JVM version (e.g. `java -version`)
1.8.0_201

**Comment by normanmaurer** [comment]
@pavanrangain this is expected... during init of the `SslContext` we invoke your `TrustManager` one time to do some verifications. This is only down when building the SslContext, so you should only see the `netty.io` cert one time (during the build of `SslContext`). 

As a side note you should re-use the `SslContext` and not build a new one all the time.
