### ISSUE TITLE
OutOfMemory Error

### ISSUE THREAD

**Issue by machao23** [netty/netty#8917]
Netty application seems to gradually 'eat up' all memory and eventually out of memory. But Netty LEAK detection doesn't show anything.

This screenshot shows  the heap dump , and the load on product server is pretty low - 50req/sec, with ~40 active connections. 
![image](https://user-images.githubusercontent.com/5095336/53795269-92988e00-3f6c-11e9-9fa0-f706e9cb752a.png)

And  found out too many pool chunks in heap. The actual value size of byte array is very small:
![image](https://user-images.githubusercontent.com/5095336/53795320-af34c600-3f6c-11e9-96d5-e399bc7e298c.png)

Netty version is 4.1.29.Final
Java version is jdk1.8.0_201

Unfortunately I wasn't able to reproduce this issue on test env.  The heap dump size is 4G, so I cannot upload it. Please let me know if you need more info.

**Comment by normanmaurer** [comment]
Did you try to run with paranoid / advanced leak detection ?

**Comment by normanmaurer** [comment]
Please re-open with more infos once you can provide these if you still think this is a netty issue
