### ISSUE TITLE
benchmark UDT: Native vs Netty

### ISSUE THREAD

**Issue by carrot-garden** [netty/netty#892]
I have 2 conceptually similar benchmarks:

1) with [native sockets](https://github.com/barchart/netty-udt/blob/master/transport-udt/src/test/java/io/netty/transport/udt/bench/xfer/BenchNative.java)

```
1/3/13 10:43:42 PM =============================================================
io.netty.transport.udt.bench.xfer.BenchNative:
  bench size:
    count = 65,536
  bench time:
    count = 60,000
  send rate:
             count = 17,565,483,008
         mean rate = 291,258,595.45 bytes/s
     1-minute rate = 259,059,778.33 bytes/s
     5-minute rate = 212,857,616.70 bytes/s
    15-minute rate = 201,432,047.84 bytes/s
```

2) with [netty api](https://github.com/barchart/netty-udt/blob/master/transport-udt/src/test/java/io/netty/transport/udt/bench/xfer/BenchNetty.java)

```
1/3/13 10:52:47 PM =============================================================
io.netty.transport.udt.bench.xfer.BenchNetty:
  bench size:
    count = 65,536
  bench time:
    count = 600,000
  send rate:
             count = 54,581,002,240
         mean rate = 154,755,149.75 bytes/s
     1-minute rate = 180,488,911.76 bytes/s
     5-minute rate = 114,247,979.60 bytes/s
    15-minute rate = 51,218,740.02 bytes/s
```

observations:
- it takes native about 1 minute to reach plateau of 290 M bytes/sec
- it takes netty about 10 minutes to reach plateau of 180 M bytes/sec
- netty is about 38% slower then native

I profiled and looked through the code, but do not see any obvious clues;
any advice on how to bridge the gap is much appreciated?

**Comment by slachiewicz** [comment]
Does anyone still uses this protocol? The project publishes the latest news at the end of 2011.

**Comment by normanmaurer** [comment]
UDT was deprecated and will be removed. Let me close this
