### ISSUE TITLE
spring and netty

### ISSUE THREAD

**Issue by xaidanwang** [netty/netty#8920]
### Description:
An attempt was made to call the method io.netty.util.concurrent.DefaultEventExecutorGroup.<init>(ILjava/util/concurrent/ThreadFactory;)V but it does not exist. Its class, io.netty.util.concurrent.DefaultEventExecutorGroup, is available from the following locations:
    jar:file:/C:/Users/Administrator/.m2/repository/io/netty/netty-all/5.0.0.Alpha2/netty-all-5.0.0.Alpha2.jar!/io/netty/util/concurrent/DefaultEventExecutorGroup.class
    jar:file:/C:/Users/Administrator/.m2/repository/io/netty/netty-common/4.1.31.Final/netty-common-4.1.31.Final.jar!/io/netty/util/concurrent/DefaultEventExecutorGroup.class
It was loaded from the following location:
    file:/C:/Users/Administrator/.m2/repository/io/netty/netty-all/5.0.0.Alpha2/netty-all-5.0.0.Alpha2.jar
Action:
Correct the classpath of your application so that it contains a single, compatible version of io.netty.util.concurrent.DefaultEventExecutorGroup
Process finished with exit code 1
### Steps to reproduce
GhostServer.java
public class GhostServer {

    public void bind(int port) throws InterruptedException {

        EventLoopGroup bossGroup = new NioEventLoopGroup();
        EventLoopGroup workGroup =  new NioEventLoopGroup();
        try {
            ServerBootstrap bootstrap = new ServerBootstrap();
            bootstrap.group(bossGroup,workGroup)
                    .channel(NioServerSocketChannel.class)
                    .option(ChannelOption.SO_BACKLOG,1024)
                    .childHandler(new LoggingHandler(LogLevel.INFO))
                    .handler(new ChannelInitializer<SocketChannel>() {
                        @Override
                        protected void initChannel(SocketChannel ch) throws Exception {

                            ch.pipeline().addLast(new AuthLoginRespHandler());
                        }
                    });

            ChannelFuture future = bootstrap.bind(port).sync();

            future.channel().closeFuture().sync();
        }finally {
            bossGroup.shutdownGracefully();
            workGroup.shutdownGracefully();
        }
    }

run class GhostMasterServerApplication
GhostMasterServerApplication.java
@SpringBootApplication
@EnableDiscoveryClient
public class GhostMasterServerApplication implements CommandLineRunner {

    public static void main(String[] args) throws InterruptedException {
        SpringApplication.run(GhostMasterServerApplication.class,args);
    }
    @Override
    public void run(String... args) throws Exception {
        new GhostServer().bind(8080);
    }
}

### Netty version
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>5.0.0.Alpha2</version>
        </dependency>
### spring boot version:
<dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.8.RELEASE</version>
</dependency>

**Comment by xaidanwang** [comment]
I used redis in this project. ，my pom.xmd add this
 <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
            <version>2.1.3.RELEASE</version>
        </dependency>
and application.yml configure
server:
  port: 9002
spring:
  application:
    name: sppc-ghost-slave
  redis:
    host: 192.168.48.138
    port: 6379
    database: 0
When I delete this dependency, the project can run successfully.
Why is this?

**Comment by amizurov** [comment]
@xaidanwang I think it's because you use two different version in your dependencies. Try to use one version 4.1.31.Final.

**Comment by xaidanwang** [comment]
thank you for your help，You are right.
