### ISSUE TITLE
IdleStateHandler may close channel in use.

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [netty/netty#8926]
### Expected behavior
Any channel brrowed from channelPool should not be closed by ourselves.
### Actual behavior
According to the [example usage of IdleStateHandler](https://netty.io/4.0/api/io/netty/handler/timeout/IdleStateHandler.html) , we can just call ctx.close if the  IdleStateEvent was triggered, but this channel may just be brrowed from channelPool by another thread, if we close it that thread will get a ClosedChannelException.
### related issue
#7497 
### Steps to reproduce
none.
### Minimal yet complete reproducer code (or URL to code)
```
     public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
         if (evt instanceof IdleStateEvent) {
             IdleStateEvent e = (IdleStateEvent) evt;
             if (e.state() == IdleState.READER_IDLE) {
                 ctx.close();
             } else if (e.state() == IdleState.WRITER_IDLE) {
                 ctx.writeAndFlush(new PingMessage());
             }
         }
     }
```
### Netty version
4.0.14
### JVM version (e.g. `java -version`)
java version "1.8.0_152"
### OS version (e.g. `uname -a`)
Linux DF1 3.0.101-0.47.106.11-default #1 SMP Tue Jan 2 10:46:28 UTC 2018 (afabf7c) x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
That is expected... You will need to remove the `IdleStateHandler` from the Channel before put it back.

**Comment by Nick-The-Uncharted** [comment]
@normanmaurer It's make senses if we are just using IdleStateHandler to detect response timeout (In fact, if our protocol has something like requestId, we dont need to wait for response before sending next request, and response of next request may come before first response, rendering the timeout of first response useless). But I am trying to use IdleStateHandler to save server resources, closing channels from client that are being idle for too long. 

BTW, if `io.netty.channel.pool.SimpleChannelPool#POOL_KEY` is public, I could have checked it myself without using reflection.
