### ISSUE TITLE
Netty threads taking huge amount of heap space

### ISSUE THREAD

**Issue by shivendra-kumar** [netty/netty#8927]
We are facing an issue in production where netty threads take hug amount of heap leading to lots of Full GCs. We are using Redisson- java client which uses Netty.

We noticed netty threads used by redisson consumed 12GB of total 16GB of allocated heap space in one application and 8GB out of 16 GB on another application . One observation i have made is that netty threads had created around 275,000 thread local maps with each consuming around a fixed amount of heap. It all seems to be related with weblogic context aware classloader because it is shared by all the netty threads.
Since the heap dump is quite large I will be attching the screenshots.

**Netty Version : 4.1.25**
**JDK - 1.8**
**App server - weblogic 12c** 

![netty_memory _leak](https://user-images.githubusercontent.com/38030846/54082315-74021080-4339-11e9-818f-37da42067bc6.png)

**Comment by normanmaurer** [comment]
Which version of netty? Also I think I will need the heap dump to analyze this :(

**Comment by shivendra-kumar** [comment]
Netty version is 4.1.25. Heap dump is very large around 30 Gbs. Also this issue persists even after multiple system restarts. I can share screenshots of specifc areas if that can help.

**Comment by normanmaurer** [comment]
That’s a very old netty version. Please upgrade to the latest first and let me know if the problem still persist

**Comment by shivendra-kumar** [comment]
Is there a reported issue of memory consumption in Netty - 4.1.25? If yes, can you please share the link?

**Comment by normanmaurer** [comment]
@shivendra-kumar we removed the `ObjectCleaner` as it had some problems. So yes it could been fixed already.

**Comment by ninja-** [comment]
have you been live reloading your app frequently while it's running?

**Comment by shivendra-kumar** [comment]
No we don't use live reloading. We just deployed the application and let users use it for a day. By the end of the day netty memory consumption reaches almost 80-90% of the total allocated heap.

**Comment by shivendra-kumar** [comment]
Simulated it locally now attaching the heap dump.

**Comment by normanmaurer** [comment]
@shivendra-kumar like I said please upgrade netty and report back. `ObjectCleaner` was removed due various issues.

**Comment by shivendra-kumar** [comment]
Attaching Heap Dump Screenshots
![netty1](https://user-images.githubusercontent.com/38030846/54188870-a6954000-44d6-11e9-907b-5ee5e6ed1de4.png)
![netty2](https://user-images.githubusercontent.com/38030846/54188871-a6954000-44d6-11e9-8c2c-1cfb59d5a7d3.png)

**Comment by normanmaurer** [comment]
@shivendra-kumar again please upgrade first and then re-run.

**Comment by normanmaurer** [comment]
Closing as no response from reporter for almost 3 weeks. Please re-open if you still think there is any issue.

**Comment by shivendra-kumar** [comment]
@normanmaurer Sorry for the super late response.  Upgarding netty did certainly help as the above issue is not coming anymore

**Comment by normanmaurer** [comment]
@shivendra-kumar thanks a lot for confirming :)
