### ISSUE TITLE
Run cloned code and get error "java.lang.NoClassDefFoundError: io/netty/channel/EventLoopGroup"

### ISSUE THREAD

**Issue by Chenfengldw** [netty/netty#8936]
1 git clone the repo; add Native transport dependencies to pom.xml.
2 "mvn clean package" under "netty/" and "netty/example/" path
3 cd example/
4 run "java -cp target/classes io.netty.example.echo.EchoServer"
5 get error
> Error: A JNI error has occurred, please check your installation and try again
> Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/channel/EventLoopGroup
> 	at java.lang.Class.getDeclaredMethods0(Native Method)
> 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
> 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
> 	at java.lang.Class.getMethod0(Class.java:3018)
> 	at java.lang.Class.getMethod(Class.java:1784)
> 	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
> 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
> Caused by: java.lang.ClassNotFoundException: io.netty.channel.EventLoopGroup
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 7 more

### Netty version
4.1
### JVM version (e.g. `java -version`)

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

### OS version (e.g. `uname -a`)

Linux storage05 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I have already built and add native transports dependencies to pom.xml according to Netty docs, but when running the code it seems not working.

**Comment by nimit95** [comment]
What was the issue here?

**Comment by conrosebraugh** [comment]
>What was the fix here?

bump
