### ISSUE TITLE
AbstractEpollServerChannel:86 Exception gives no information

### ISSUE THREAD

**Issue by 68CodingMonkeys** [netty/netty#8937]
### Expected behavior
channelPromise.setFailure(new UnsupportedOperationException("server channel can not issue connect"));
### Actual behavior
channelPromise.setFailure(new UnsupportedOperationException());

### Steps to reproduce
EpollEventLoopGroup grp        = null;
grp = new EpollEventLoopGroup();
DomainSocketAddress socketAddress = new DomainSocketAddress( "/tmp/TerryPratchett" );

Bootstrap clientBootstrap = new Bootstrap();
clientBootstrap.group( grp )
			               .channel( EpollServerDomainSocketChannel.class )
			               .handler( new ClientChannelInitializer() );
Channel channel = clientBootstrap.connect( socketAddress ).sync()

### Netty version
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.34.Final</version>
        </dependency>

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

### OS version (e.g. `uname -a`)
Linux 3.10.0-042stab134.8 #1 SMP Fri Dec 7 17:16:09 MSK 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
Honestly I think it is just fine ... `UnsupportedOperationException` is quite clear imho.

**Comment by 68CodingMonkeys** [comment]
Ok fine with that but please answer me one question:

WHERE is that documented?
