### ISSUE TITLE
Add support for binding to NetworkInterface in Bootstrap

### ISSUE THREAD

**Issue by loganrosen** [netty/netty#8940]
`Bootstrap` allows you to set a `localAddress` for outbound TCP connections, either via the `Bootstrap.localAddress(localAddress)` or `Bootstrap.connect(remoteAddress, localAddress)` methods. This works well if you want to bind to just one IP address on an interface.

However, I am in a situation where a network interface has both IPv4 and IPv6 addresses, and I want to bind to one or the other based on the remote address. Right now, I have to implement the logic to resolve the remote address and choose the corresponding interface address to bind to myself.

It would be much better if Netty just let me pass a `NetworkInterface` object that represents the interface I'd like to bind to, and then it automatically chooses which `localAddress` to use based on the `remoteAddress` I'm connecting to. Does this fit within the scope of what Netty should do, versus what the client should implement?

**Comment by normanmaurer** [comment]
@loganrosen so just to clarify... the interface is configured to have ipv4 and ipv6 addresses ?

**Comment by loganrosen** [comment]
@normanmaurer Correct. This is the code we're currently using to get the IPv4 and IPv6 addresses for the interface, in case it's useful:
```Java
NetworkInterface networkInterface = NetworkInterface.getByName(interfaceName);
if (networkInterface == null) {
  throw new InternalError("SERIOUS PROBLEM: No network interface found for " + interfaceName);
}
if (!networkInterface.isUp()) {
  throw new InternalError("SERIOUS PROBLEM: network interface is not up: " + interfaceName);
}

List<InetAddress> inetAddressStream = networkInterface.getInterfaceAddresses().stream().map(InterfaceAddress::getAddress)
    .filter(inetAddress -> !inetAddress.isLoopbackAddress() && !inetAddress.isLinkLocalAddress()).collect(Collectors.toList());

Inet4Address inet4Address = inetAddressStream.stream().filter(inetAddress -> inetAddress instanceof Inet4Address)
    .findFirst().map(Inet4Address.class::cast).orElseThrow(() ->
        new InternalError("SERIOUS PROBLEM: No IPv4 address found for network interface " + interfaceName));

Inet6Address inet6Address = inetAddressStream.stream().filter(inetAddress -> inetAddress instanceof Inet6Address)
    .findFirst().map(Inet6Address.class::cast).orElse(null);
```

**Comment by normanmaurer** [comment]
@loganrosen ok got it... let me think about it :)

**Comment by normanmaurer** [comment]
PTAL https://github.com/netty/netty/pull/8982
