### ISSUE TITLE
Add native-image options and substitutions to netty artifacts for OOTB GraalVM native-image support

### ISSUE THREAD

**Issue by olpaw** [netty/netty#8959]
As described in https://medium.com/graalvm/simplifying-native-image-generation-with-maven-plugin-and-embeddable-configuration-d5b283b92f57 (see _Composable native-image.properties_) GraalVM native-image building supports embedding native-image configuration options and substitutions right into jar-files.

Currently when Netty is used in the context of building an image, configuration options and substitutions need to be provided from the outside. Please add the [required substitutions](https://github.com/graalvm/graalvm-demos/blob/master/native-netty-plot/src/main/java/com/oracle/svm/nettyplot/NettySubstitutions.java) and [build options](https://github.com/graalvm/graalvm-demos/tree/master/native-netty-plot/src/main/resources/META-INF/native-image/com.oracle.substratevm/netty-plot) right into Netty as described in the article. This will allow Netty to be used in image builds without requiring any external configuration.

**Comment by normanmaurer** [comment]
Are you interested in providing a PR?

**Comment by pmlopes** [comment]
The bare minimum 3 needed for any vertx app or the netty examples is here: https://github.com/pmlopes/vertx-starter/blob/develop/templates/graal-nativeimage/src/main/java/SVMSubstitutions.java 

If you want I can help with this, just let me know which package would best and module.

**Comment by olpaw** [comment]
> is here: https://github.com/pmlopes/vertx-starter/blob/develop/templates/graal-nativeimage/src/main/java/SVMSubstitutions.java

Obviously the vertx specific parts in SVMSubstitutions.java would need to be removed before adding it to the Netty codebase (e.g. with classname `io.netty.native.Feature`). Also using `@AutomaticFeature` is problematic. Better make it a regular feature and use
```
Args = --features=io.netty.native.Feature
```
in `META-INF/native-image/io.netty/netty-all/native-image.properties`.

Even better, instead of using `RuntimeReflection.register` calls in a Feature you can instead use a `reflection-config.json` file to configure which parts need to be [reflectively accessible](https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md). Then you don't need to use a Feature at all (having the Substitutions on the classpath is sufficient, see https://github.com/graalvm/graalvm-demos/blob/master/native-netty-plot/src/main/java/com/oracle/svm/nettyplot/NettySubstitutions.java).

In this case you would simply have the Substitutions e.g. in  `io.netty.native.NettySubstitutions` and a `META-INF/native-image/io.netty/netty-all` that contains `reflection-config.json` and `native-image.properties` with:
```
Args = -H:ReflectionConfigurationResources=${.}/reflection-config.json \
       --delay-class-initialization-to-runtime=io.netty.handler.codec.http.HttpObjectEncoder
```

**Comment by pmlopes** [comment]
@olpaw yes the link I posted was an example, the vertx one should not be in netty of course, but in vert.x. Basically they are the same you also use on netty plot demo.

**Comment by pmlopes** [comment]
@olpaw could you review this before I open a pull request? https://github.com/pmlopes/netty/commit/26b8a14cfa61d9ae33f31a80beda8be8a685536d 

@normanmaurer I am facing an issue with check style that does not recognize the copyright comment on the property files, could you peek at the commit above and let me know how I should format it? or just point me to some example (which i could not find on my own, sorry).

**Comment by sdeleuze** [comment]
Thanks for contributing the PR @pmlopes! I guess https://github.com/netty/netty/issues/8192 can be closed as a duplicate in favor of that one ?
