### ISSUE TITLE
serialize to SocketChannel

### ISSUE THREAD

**Issue by zhanfffmmm** [netty/netty#8977]
hello
   Please help me
   my project detail code has [map <String,SocketChannel> map = new ConcurrentHashMap<String,SocketChannel>()],so I want to this code to replace in Memory server. it do not work when the Memory server serialize to SocketChannel to byte.how  can I do?can you suggest to me some way?

**Comment by normanmaurer** [comment]
This is an issue tracker, please use stackoverflow for questions

**Comment by zhanfffmmm** [comment]
thank you
