### ISSUE TITLE
some question about object pool recycle

### ISSUE THREAD

**Issue by NickleHuang** [netty/netty#8978]
i can't understand why recycle use strong reference stack to recycle object, sometimes lots of threads will cause memory error, i think should use soft reference instead of it, What do you think？

**Comment by normanmaurer** [comment]
@NickleHuang what specific you think should be a `SoftReference` here ? Maybe you can provide a PR to show your idea ?

**Comment by NickleHuang** [comment]
> @NickleHuang what specific you think should be a `SoftReference` here ? Maybe you can provide a PR to show your idea ?
@normanmaurer 
I think that should keep the Stack in the Recycle object SoftReference object make it, I learned that you are using this Stack object to an object pool to reduce YGC, but do they have a problem: a large number of threads can cause full gc until the JVM crash, mostly don't know how parameters can adjust the size of the pool, there are a lot of people don't know why can lead to a crash, so I think if the cache object into a SoftReference will avoid appear this kind of circumstance, the code is as follows:
 static final class DefaultHandle<T> implements Handle<T> {
        private int lastRecycledId;
        private int recycleId;

        boolean hasBeenRecycled;

        private Stack<?> stack;
        private Object value;

        DefaultHandle(Stack<?> stack) {
            this.stack = stack;
        }

        @Override
        public void recycle(Object object) {
            if (object != value) {
                throw new IllegalArgumentException("object does not belong to handle");
            }
           //Since a strong reference to the cached object is maintained here, causing Full gc, I think the cached object should be allowed to be invalidated，So what I suggest is that you cache objects here using soft references
            stack.push(this);
        }
    }

**Comment by normanmaurer** [comment]
@belliottsmith /cc

**Comment by belliottsmith** [comment]
This looks a lot like what [PR #8052](https://github.com/netty/netty/pull/8052) is trying to achieve, so probably better to discuss it there.

**Comment by NickleHuang** [comment]
> This looks a lot like what [PR #8052](https://github.com/netty/netty/pull/8052) is trying to achieve, so probably better to discuss it there.
@belliottsmith I looked at the link you gave me, but I didn't find the final solution.It is up to the user to specify whether to use the object pool or not

**Comment by normanmaurer** [comment]
Like @belliottsmith said... lets discuss in #8052
