### ISSUE TITLE
limit the access permissions of io.netty.channel.ChannelOption#newInstance

### ISSUE THREAD

**Issue by liuhaozzu** [netty/netty#8983]
#### limit the access of io.netty.channel.ChannelOption#newInstance from public to private.   
now this method is public and will throw Excepiton when recreate a constant. It's better to use io.netty.channel.ChannelOption#valueOf(java.lang.String), it's much safer and easy to use.
### Actual behavior
now this method is public and will throw Excepiton when recreate a constant.
### Steps to reproduce
recreate a constant
### Minimal yet complete reproducer code (or URL to code)
```
ChannelOption timeout2 = ChannelOption.newInstance("abc");
ChannelOption timeout3 = ChannelOption.newInstance("abc");
```
### Netty version
4.1.33.Final
### JVM version (e.g. `java -version`)
"1.8.0_201"
### OS version (e.g. `uname -a`)
Darwin Kernel Version 18.2.0

**Comment by normanmaurer** [comment]
I think this is expected and by design... that said I think we could deprecate it as we also dont use it at all in Netty... @trustin thoughts ?

**Comment by liuhaozzu** [comment]
yes, marking it as @Deprecated is also helpful for the new netty users.
