### ISSUE TITLE
How does netty NioDatagramChannel get socket objects?

### ISSUE THREAD

**Issue by whstywh** [netty/netty#8984]
I would use the extends NioDatagramChannel to call javaChannel().socket() to get the DatagramSocket object, but NioDatagramChannel is final.

**Comment by normanmaurer** [comment]
You should not.. Why you need this ?

**Comment by whstywh** [comment]
I am trying to use the built-in VpnService in Android to capture traffic and send it to a remote server. I am trying to use Netty, but it seems that I have come to an impasse.

In order to send data from the phone to the server I need to call Protect() on the socket otherwise all the data I transmit will just be looped back into the VpnService. However I am not sure if it’s possible to get a hold of a Socket object or its filedescriptor when using Netty4.

**Comment by normanmaurer** [comment]
@whstywh I see...

What you can do is to create a `NioDatagramChannel` from an existing `DatagramChannel` by passing it into the constructor. I think this should allow you to do what you want:

https://github.com/netty/netty/blob/netty-4.1.34.Final/transport/src/main/java/io/netty/channel/socket/nio/NioDatagramChannel.java#L147
