### ISSUE TITLE
Non-configurable epoll timeout

### ISSUE THREAD

**Issue by localstorm** [netty/netty#8986]
After reviewing the internals of Netty 4 implementation it appears to me that if someone wants to offload heavy-lifting processing to a thread other than Netty IO thread they are running into the following issue:

Depending on what's going on on the same or other socket channel handled by the same thread and whether there are any tasks to execute any time soon, IO thread might decide to enter blocking epoll with a timeout up to 1s. 

If it happens that other thread which is doing heavy processing and is building result to reply is ready to write result back to client at the time when IO thread is still blocked on epoll, the write will wait until IO thread exits epoll to make such write, which exacerbates the latency of the server's response for the client.

The following StackOverflow answer from a member of Netty dev community seems to confirm my suspicion:

https://stackoverflow.com/questions/44782682/netty-channelhandlercontext-writing-from-different-thread 

The following code was looked at:

https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java#L276

Therefore a couple of questions:

- Is there any best practice to avoid such delayed write? 
- Should the maximum timeout generally be configurable and/or much smaller?
- Is the coupling between writes and epoll intentional? I assume it is to honor the promise of being notified about events on the channel from the same IO thread

**Comment by ninja-** [comment]
Interesting observation. Are you sure you were able to see this in practice?
IIRC sending a task to eventloop will produce a wakeup event

> Is there any best practice to avoid such delayed write?
The pattern you linked on stackoverflow is the best way to go.

> Is the coupling between writes and epoll intentional? I assume it is to honor the promise of being notified about events on the channel from the same IO thread
Yes that's intentional to keep everything in sync. We already use write(...) syscall in nonblocking mode which is best option available.

**Comment by localstorm** [comment]
Interesting, so you basically say that in order to unblock epoll there is a special file descriptor which is always in the epoll list which other threads are writing into to wake it up.

Makes sense, I will take a look more into it, thank you for explaining.
