### ISSUE TITLE
Netty does not allow for configuring key store type

### ISSUE THREAD

**Issue by DanielBauman88** [netty/netty#8998]
### Expected behavior
I expect netty to allow me to specify configuration for the key store type to use.
### Actual behavior
Netty uses the default key store:
https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslContext.java#L1038
https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslContext.java#L1146
### Netty version
4.1
### JVM version (e.g. `java -version`)
any
### OS version (e.g. `uname -a`)
any

### Impact
New versions of java use pkcs12 as the default keystore type instead of jks.
http://openjdk.java.net/jeps/229
Creating a jks keystore is significantly faster than a pkcs12 keystore (some basic testing showed 1ms vs 80ms). I would like to be able to configure netty to use jks keystores without having to override the security properties of my entire jvm.

This has a big impact on code where ssl contexts have to be created frequently.

**Comment by SplotyCode** [comment]
Seems correct. I will make a PR tomorrow if no else wants/will do it

**Comment by DanielBauman88** [comment]
Thank you!

**Comment by normanmaurer** [comment]
@SplotyCode thanks a lot... will review once done

**Comment by bergerst** [comment]
Why is there a null parameter for setting the client keystore type?

https://github.com/netty/netty/commit/5a27f2f78b4f9630ca71ba46e75332009fb5f785#diff-71806bf8745a8afbcc579df0168dd5a6R289

I'm experiencing errors right now because the wrong keystore is created for client authentication. They only workaround I have found so far is creating my own KeyManagerFactory.

**Comment by normanmaurer** [comment]
@bergerst if you think there is a bug or there is something that can be improved please provide a pr.

**Comment by bergerst** [comment]
@normanmaurer Done.
