### ISSUE TITLE
Issue with Linux kernel 5.0.x and epoll

### ISSUE THREAD

**Issue by omarkilani** [netty/netty#8999]
I’m not confident in the exact culprit for this issue, but wanted to add it here in case someone else hits it and decides to Google.

There’s something wrong with netty and kernels 5.0 through 5.0.3 (haven’t tested 5.0.4 or 5.0.5 but the Changelogs don’t seem applicable).

I’m not sure if this is a JDK issue but I tried OpenJDK 11 and 12.

Basically, on 5.0.x I see a lot of extra WRITABILITY_CHANGED events in the netty debug output that don’t happen on any older kernel version (I tested the latest 4.14.x through 4.20.x).

Along with the extra events, the data netty writes to the socket doesn’t seem to be fully flushed or something, and the other end of the socket will time out thinking it has to read more data.

Unfortunately as this happened in production on a canary deployment it’s hard for me to test it again without annoying users. Maybe 5.0.x has some changes to epoll the JDK isn’t aware of?

**Comment by normanmaurer** [comment]
Can you show me how you bootstrap your channel ?

**Comment by omarkilani** [comment]
Hi Norman,

Sure:

https://github.com/unfiltered/unfiltered/blob/0.10.x/netty-server/src/main/scala/Server.scala#L110

**Comment by normanmaurer** [comment]
Can you try to use EpollServerSocketChannel and EpollEventLoopGroup and let me know how it works out ?

**Comment by omarkilani** [comment]
Will do.

I added support for native transports to unfiltered:

https://github.com/unfiltered/unfiltered/pull/440

Will test it in some real apps soon.

**Comment by omarkilani** [comment]
Hi Norman,

Amazingly, I was able to repro this with a smallish unfiltered example.

One interesting thing to note is that I could repro it with HTTP keepalive off. With it on it doesn't trigger whatever the issue is.

Anyway, with native transports it works either way. So I'm not sure what that says. Are you interested in the repro case if it uses scala/unfiltered, or should I work on a "netty only" Java example?

Thanks!

**Comment by omarkilani** [comment]
Just for my own notes, this is still broken in 5.0.5. I'm going to test on 5.0.6.

Is it fair to say that if it works with native transports we can rule out an issue in netty and it's more likely some JDK issue?

**Comment by normanmaurer** [comment]
@omarkilani yes I would say so.

**Comment by normanmaurer** [comment]
@omarkilani any update ?

**Comment by normanmaurer** [comment]
@carl-mastrangelo @ejona86 @vkostyukov did you hear of anything like this in your env ?

**Comment by omarkilani** [comment]
I had to pause my research into this but 5.0.6 made the problem much more frequent.

I’ll test 5.0.7 today. I’ll close this if it’s taking up your brain space. It’s a very weird sort of issue, but I did manage to pcap it in production so I’m trying to study the wireshark output.

Happy to share that with you once I make sure there’s no customer data in it.

**Comment by normanmaurer** [comment]
@omarkilani would be interested

**Comment by ejona86** [comment]
I've not seen anything similar to this in our environment, but we aren't running Linux 5.0 and we aren't running OpenJDK 11... I am aware of one binary that would be using OpenJDK 11+grpc, but it still wouldn't be running on Linux 5.0.

**Comment by normanmaurer** [comment]
@omarkilani I just talked with @franz1981 and he mentioned that maybe it is related to edge vs level triggered. NIO uses level triggered while our native epoll transport uses edge triggered by default. Could you try to switch to level triggered for epoll and see if you see the same effect ? Would be interesting to see the outcome :)

`bs.option(EpollChannelOptions.EPOLL_MODE, EpollMode.LEVEL_TRIGGERED)`

and if its a `ServerBootstrap` also:

`bs.childOption(EpollChannelOptions.EPOLL_MODE, EpollMode.LEVEL_TRIGGERED)`

**Comment by omarkilani** [comment]
I tested 5.0.7 and it's still broken. However, I've narrowed the issue down to 7 kernel commits.

So I'm going to revert each one and recompile and retest.

**Comment by normanmaurer** [comment]
Nice! Keep us posted

**Comment by omarkilani** [comment]
Just an update on this. I was able to make nginx fail in a similar way using epoll, so I’m going to close this.

My hunch on the cause is this commit (or the ones surrounding it, but they’re all interdependent so it’s not really possible to revert just one):

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=v5.1-rc5&id=c5a282e9635e9c7382821565083db5d260085e3e

The issue is hard to reproduce because you need to have a lot of epoll usage on the system to trigger whatever it is. So just running the jvm, you need a bunch of CPUs and a load tester with a lot of clients, etc.

It’s easier when you run more things that use epoll. So I chained:

nginx - haproxy - jvm/netty

Basically just proxying the request but generating a lot of epoll events in the kernel. With this chain nginx fails after about 1000 requests from 100 concurrent clients (the error message references epoll_wait, but I had to stop my testing for today so I forget the exact message. Since it’s not netty related it doesn’t matter I guess).

Weirdly enough, I can never get haproxy to fail. The jvm fails in epoll after something like 9,000,000 requests if load tested directly.

So, however haproxy uses epoll doesn’t trigger whatever the issue is.

Anyway, this thing is annoying me a lot, but every time I need to test it I need to use a VM with 64+ cores which costs a bunch of money. So I’m not sure I can keep chasing it. Hopefully someone else hits it and hasn’t more bandwidth. It’s one of those things that’s hard to believe is happening but there’s definitely something happening, I swear. :)
