### ISSUE TITLE
Finer grained ChannelOutboundBuffer total pending write byte size changes.

### ISSUE THREAD

**Issue by qeesung** [netty/netty#9005]
`ChannelOutboundBuffer`  total pending write byte size decreases only when entry is removed from the flush list. But if a large Entry has been flushing slowly (for some reason, the network speed is slow, or the client processing speed is too slow to cause the TCP sliding window to be zero), then the total pending write byte size of `ChannelOutboundBuffer` is always unchanged when entry is flushing is observed from the outside. For example, issue #8912 is the result of this.

### Expected behavior
When `ChannelOutboundBuffer` is flushing a large entry, should be able to observe a change in total pending write byte size.

### Actual behavior
The total pending write byte size remains unchanged when `ChannelOutboundBuffer` flushing the large entry.

### Netty version
4.1.34.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

### OS version (e.g. `uname -a`)
Windows 10

**Comment by normanmaurer** [comment]
@qiaodaimadelaowang this actually by design as until we wrote the full message we can not release it and so can not give the memory back to the pool. This helps to prevent OOME. 

#8912  will need another "fix", I will have a look soon.

**Comment by qeesung** [comment]
@normanmaurer  Ok, I noticed that each flush entry has a progress field (although the progress will only be updated if the promise of entry is instance of `ChannelProgressivePromise`). How about fixing #8912 by adding a check on entry's progress to the [IdleStateHandler. hasOutputChanged](https://github.com/netty/netty/blob/52411233d322c10687c03e99279cadbceec2b9f4/handler/src/main/java/io/netty/handler/timeout/IdleStateHandler.java#L438) method

```java
if (buf != null) {
    int messageHashCode = System.identityHashCode(buf.current());
    long pendingWriteBytes = buf.totalPendingWriteBytes();
    long currentEntryProgress = buf.currentProgress();

    if (messageHashCode != lastMessageHashCode || 
             pendingWriteBytes != lastPendingWriteBytes ||
             currentEntryProgress != lastCurrentEntryProgress) {
        lastMessageHashCode = messageHashCode;
        lastPendingWriteBytes = pendingWriteBytes;
        lastCurrentEntryProgress = currentEntryProgress;

        if (!first) {
            return true;
        }
    }
}
```
