### ISSUE TITLE
SelfSignedCertificate fails with FIPS enabled causing OpenSsl to fail

### ISSUE THREAD

**Issue by fzakaria** [netty/netty#9018]
### Expected behavior

For compliance reasons, we have BouncyCastle FIPS mode enabled and use Netty's OpenSSL bindings for TLS termination.

I've noticed that Netty is failing to startup correctly since within `OpenSsl.java` static constructor it creates a `SelfSignedCertificate` with **1024** bits -- as such it is failing to create a KeyManagerFactory.

FIPS 140-2 encryption requires the key length to be 2048 bits or greater.
I would like to  submit a PR to bump the bits for SelfSignedCertificate default to 2048.

### JVM version (e.g. `java -version`)

JRE 1.8

### OS version (e.g. `uname -a`)

darwin (OSX) & OracleLinux

**Comment by normanmaurer** [comment]
Sounds good 👌
