### ISSUE TITLE
isActive() returns true after syncing the disconnect() of server socket channel

### ISSUE THREAD

**Issue by pcperera** [netty/netty#9026]
### Expected behavior
Upon invoking disconnect().sync() on NioServerSocketChannel, isActive() should return **false**.

### Actual behavior
isActive() returns **true** while isOpen() and isRegistered() returns **false**.

### Steps to reproduce

- Bind NioServerSocketChannel

- Print isActive(), isOpen(), isRegistered() state of the channel.

- disconnect().sync() server socket channel

- Print isActive(), isOpen(), isRegistered() state of the channel.

### Minimal yet complete reproducer code (or URL to code)

`import io.netty.bootstrap.ServerBootstrap;
import io.netty.channel.Channel;
import io.netty.channel.ChannelFuture;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import org.testng.Assert;

import java.net.InetSocketAddress;

public class EchoServer {
    private final int port;
    public EchoServer(int port) {
        this.port = port;
    }

    public void start() throws Exception {
        final EchoServerHandler serverHandler = new EchoServerHandler();
        EventLoopGroup eventLoopGroup = new NioEventLoopGroup();
        ServerBootstrap serverBootstrap = new ServerBootstrap();
        ChannelInitializer<SocketChannel> channelInitializer = new ChannelInitializer<SocketChannel>() {
            @Override
            public void initChannel(SocketChannel ch) {
                ch.pipeline().addLast(serverHandler);
            }
        };

        serverBootstrap.group(eventLoopGroup)
                .channel(NioServerSocketChannel.class)
                .localAddress(new InetSocketAddress(port))
                .childHandler(channelInitializer);

        ChannelFuture channelFuture = serverBootstrap.bind().sync();
        Thread.sleep(5000);
        printChannelState(channelFuture.channel(), "After connect()");
        Assert.assertTrue(channelFuture.channel().disconnect().sync().isSuccess());
        printChannelState(channelFuture.channel(), "After disconnect()");
    }

    private void printChannelState(Channel channel, String log) {
        System.out.println("=========" + log + "==========");
        System.out.println("isRegistered = " + channel.isRegistered());
        System.out.println("isOpen = " + channel.isOpen());
        System.out.println("isActive = " + channel.isActive());
        System.out.println("=====================================");
    }
}`

### Netty version
4.1.19.Final

### JVM version (e.g. `java -version`)
1.8.0_172

### OS version (e.g. `uname -a`)
MINGW64_NT-6.1 LP-MLB23333 2.10.0(0.325/5/3) 2018-04-23 03:21 x86_64 Msys

**Comment by normanmaurer** [comment]
Thanks for reporting... This is a bug and should be fixed here: https://github.com/netty/netty/pull/9030
