### ISSUE TITLE
Using class EmbeddedChannel test codec : invoking writeOutbound() method then invoking readOutbound()

### ISSUE THREAD

**Issue by zbkpointer** [netty/netty#9028]
When I use class **EmbeddedChannel** to test the correctness of **LengthFieldBasedFrameDecoder** and **LengthFieldPrepender**  in custom protocol with ProtoBuf，I expect to  get all data by encoding . Firstly, I invoke the method **ch.writeOutbound()** to add my message object. Second , I  invoke the method **ch.readOutbound()** to get the **ByteBuf**. I expect get the ByteBuf that combines the length field  ByteBuf and the message ByteBuf. But I only get  ByteBuf wrapping the length field which is **PooledUnsafeDirectByteBuf(ridx: 0, widx: 4, cap: 4)**. That confuses me. Then I  **debug the program**. I can understand the principle about polling from **outmessage**. So I get  the length field  ByteBuf firstly. Why designing in this way? Can I get all the data by encoding. The following is my test code.
`  
 @Test
    public void testAlarmProto(){

        AlarmProto.Alarm.Builder builder = AlarmProto.Alarm.newBuilder();

        builder.setCommunity("Quene Home");
        builder.setBuildingId(31);
        builder.setBuildingPart("B");
        builder.setCellId(1);
        builder.setRoomId(204);
        builder.setAlarmCategory("Fire");
        builder.setAttachment("Current time");

        MessageProto.MessageBase.Body.Builder body = MessageProto.MessageBase.Body.newBuilder();
        body.setContext(builder.build());

        MessageProto.MessageBase.Header.Builder header =MessageProto.MessageBase.Header.newBuilder();
        header.setType(MessageProto.MessageBase.MessageType.SERVICE_REQ);

        MessageProto.MessageBase.Builder message = MessageProto.MessageBase.newBuilder();
        message.setHeader(header.build());
        message.setBody(body.build());

       //create EmbeddedChannel
        EmbeddedChannel ch = new EmbeddedChannel();

        ch.pipeline().addLast("frameDecoder",new LengthFieldBasedFrameDecoder(1048576,0,4,0,4));
       // ch.pipeline().addLast("frameDecoder",new ProtobufVarint32FrameDecoder());
        ch.pipeline().addLast("decoder",new ProtobufDecoder(MessageProto.MessageBase.getDefaultInstance()));
        ch.pipeline().addLast("frameEncoder",new LengthFieldPrepender(4));

      //  ch.pipeline().addLast("frameEncoder",new ProtobufVarint32LengthFieldPrepender());
        ch.pipeline().addLast("encoder",new ProtobufEncoder());

       //write outbound data to ch
        ch.writeOutbound(message.build());

       //get data from ch but only the 
        ByteBuf byteBuf = ch.readOutbound();
    
        ch.writeInbound(byteBuf);
        ch.finish();
        MessageProto.MessageBase messageBase = ch.readInbound();

        System.out.println(messageBase.getHeader().getType().getNumber());
        System.out.println(messageBase.getBody().getContext().getBuildingPart());

    }`

**Comment by normanmaurer** [comment]
@zbkpointer it works as expected as it produces two buffers. If you want to have both buffers merged you will need to call `readOutbound()` in a loop and merge these buffers.
