### ISSUE TITLE
Typo Documentation - MessageSizeEstimator.class

### ISSUE THREAD

**Issue by Mr00Anderson** [netty/netty#9031]
https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/transport/src/main/java/io/netty/channel/MessageSizeEstimator.java#L19

"Responsible to estimate size of a message. The size represent how much memory the message will ca. reserve in memory."

I was going through the source and trying to determine where MessageSizeEstimator.class is used and what "ca" in the documentation means. I will make the pull request once I know what "ca" means, if it needs to be corrected.

**Comment by normanmaurer** [comment]
@Mr00Anderson ca. == approximately  . So yep PRs welcome
