### ISSUE TITLE
how to config Netty DefaultMessageSizeEstimator  unknownSize 

### ISSUE THREAD

**Issue by fuyou001** [netty/netty#9049]
### Expected behavior
Netty server write  msgData to client,but client process slowly,so we use WRITE_BUFFER_HIGH_WATER_MARK ,and set WRITE_BUFFER_HIGH_WATER_MARK to 16MB

### Actual behavior
but ChannelOutboundBuffer  totalPendingSize value is 13,864,807,459
### Steps to reproduce
1. start server,push big data to client,eg write 1MB data to client every 50ms
2. client thread sleep 
3. then dump JVM,and use mat profile

### Netty version
4.0.22.FInal
### JVM version (e.g. `java -version`)
1.8.0_102
### OS version (e.g. `uname -a`)
2.6.32-

**Comment by normanmaurer** [comment]
Just configure your own instance of `DefaultMessageSizeEstimator` when bootstrap the server / client.
