### ISSUE TITLE
the length of clientId in MQTT 3.1 should not be forced to set between 1 and 23 characters

### ISSUE THREAD

**Issue by xdx54321** [netty/netty#9054]
in method
```
io.netty.handler.codec.mqtt.isValidClientId(MqttVersion mqttVersion, String clientId)
```
there are these code 
```
if (mqttVersion == MqttVersion.MQTT_3_1) {
            return clientId != null && clientId.length() >= MIN_CLIENT_ID_LENGTH &&
                clientId.length() <= MAX_CLIENT_ID_LENGTH;
        }
```
the code restrict the _clientId_ length must not exceed _MAX_CLIENT_ID_LENGTH_(it has been set to 23),
but according to the CONNECT message of [MQTT 3.1](http://public.dhe.ibm.com/software/dw/webservices/ws-mqtt/mqtt-v3r1.html#connect) it can exceed 23 characters.

**Comment by normanmaurer** [comment]
@xdx54321 PRs welcome :)
