### ISSUE TITLE
 Unable to integrate this project into android studio using gradle

### ISSUE THREAD

**Issue by TangPinJia** [netty/netty#9061]

**Comment by normanmaurer** [comment]
This is more a question... please use stackoverflow

**Comment by TangPinJia** [comment]
I downloaded it and used it as a file.
Thank you for your reply.





------------------ 原始邮件 ------------------
发件人: "Norman Maurer"<notifications@github.com>;
发送时间: 2019年4月18日(星期四) 凌晨4:38
收件人: "netty/netty"<netty@noreply.github.com>;
抄送: "1070022846"<1070022846@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [netty/netty]  Unable to integrate this project into androidstudio using gradle (#9061)




Closed #9061.
