### ISSUE TITLE
[Netty 4]how to close different port properly in one application?

### ISSUE THREAD

**Issue by Buffer2Disk** [netty/netty#9076]
### Expected behavior
i use different bootstrap to bind different port in one netty application,like this below
`for(int port : ports){
     serverBootstrap.bind(server, port).sync();
}`

now i need to close some ports , so how can i achieve that ?
i have tried two different ways to close port ：
 
1.
one port use one eventLoopGroup , and   close  their own  eventLoopGroup
`eventLoopGroup.shutdownGracefully().sync()`

2.
all ports use one eventLoopGroup , and close their own serverBootstrap
`ChannelFuture channelFuture = serverBootstrap.bind(server, port).sync();
channelFuture.channel().closeFuture().sync();`

### Actual behavior
when i use the fisrt way to close port , it close port properly
but when i use second way to close port ,
`channelFuture.channel().closeFuture().sync();`
 it looks like blocked by something , and cost a lot of time to close port 

i can not use the first way because i have quite a lot port to bind and that means i need to create a lot eventLoopGroups for different port to shutdown, it will cosume a lot of memory

In a sense ， i prefer to use the second way , but it  blocked by something , i don‘t know why

### Netty version
4.1.24.Final
### JVM version (e.g. `java -version`)
java 8
### OS version (e.g. `uname -a`)
centos 6

**Comment by Buffer2Disk** [comment]
now , i tried 
`channelFuture.channel().close().sync();`
it works fine ,  emmmmm

**Comment by SplotyCode** [comment]
`channelFuture.channel().close().sync();` gets the channel, closes it and waits until it is closed.

`channelFuture.channel().closeFuture().sync();` gets the channel and WAITS until it is closed without closing it.

`eventLoopGroup.shutdownGracefully().sync()` shutdownGracefully() is very cautious it takes a lot of time (because of a quiet Period) so why don't you just remove the sync() if you need to do it fast. sync() means block this thread util it is finished. If you want to keep sync() on shutdownGracefully() you can reduce the quiet Period as you can sea it in the [docs](https://netty.io/4.0/api/io/netty/util/concurrent/EventExecutorGroup.html#shutdownGracefully-long-long-java.util.concurrent.TimeUnit-).

**Comment by Buffer2Disk** [comment]
> `channelFuture.channel().close().sync();` gets the channel, closes it and waits until it is closed.
> 
> `channelFuture.channel().closeFuture().sync();` gets the channel and WAITS until it is closed without closing it.
> 
> `eventLoopGroup.shutdownGracefully().sync()` shutdownGracefully() is very cautious it takes a lot of time (because of a quiet Period) so why don't you just remove the sync() if you need to do it fast. sync() means block this thread util it is finished. If you want to keep sync() on shutdownGracefully() you can reduce the quiet Period as you can sea it in the [docs](https://netty.io/4.0/api/io/netty/util/concurrent/EventExecutorGroup.html#shutdownGracefully-long-long-java.util.concurrent.TimeUnit-).

thanks for your reply , i don't quiet understand what does it mean
 'gets the channel and WAITS until it is closed without closing it.'

especially 'without closing it'

**Comment by SplotyCode** [comment]
`channelFuture.sync()` waits until the server is started and `channelFuture.channel().closeFuture().sync()` waits untel it is closed but it dosent close itself.

Okay, for example, you have your main thread that calls `channelFuture.channel().closeFuture().sync()` so your main threads waits until is closed now you close the channel from a channelHandler(other thread) and your main thread will work again.
BTW: if your sync() after the future is complete it will not block at all.
