### ISSUE TITLE
Can we replace LIVE_SET in ObjectCleaner with AtomicInteger?

### ISSUE THREAD

**Issue by xiaoheng1** [netty/netty#9077]
The role of LIVE_SET is simply to determine if there is a value, then can we use AtomicInteger instead of this part of the work to reduce the use of space?

**Comment by johnou** [comment]
iirc ObjectCleaner is no longer in use in the latest 4.1, update your version of Netty if you are experiencing problems with high memory.

**Comment by xiaoheng1** [comment]
Understand, thank you!
