### ISSUE TITLE
[netty 4] why netty must modify "multipart request" to "chunked"?

### ISSUE THREAD

**Issue by nexxxxxxx** [netty/netty#9079]
I want to send "multipart request"(in other words, Content-Type = multipart/form-data),
but I don't want this request to be chunked

how can I do this? thanks!

**Comment by medusar** [comment]
@reenWYJ Maybe you need to provide some more information about your need.

**Comment by normanmaurer** [comment]
Yeah without more infos we can not help.. please reopen when you can provide more.
