### ISSUE TITLE
Netty LengthFieldPrepender causes memory leak

### ISSUE THREAD

**Issue by medusar** [netty/netty#9083]
### Expected behavior
no memory leak detected
### Actual behavior
memory leak detected, and output error log:
```
2019-04-22 19:02:24,526 ERROR i.n.u.ResourceLeakDetector [WriteThread-4-15] LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:334)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115)
	io.netty.handler.codec.LengthFieldPrepender.encode(LengthFieldPrepender.java:193)
	io.netty.handler.codec.LengthFieldPrepender.encode(LengthFieldPrepender.java:55)
	io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:706)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:698)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:780)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
	io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:706)
	io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:698)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:780)
	io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
```
### Steps to reproduce
Sorry, my codes are not available now,  codes in `LengthFieldPrepender`:
```
 out.add(ctx.alloc().buffer(4).order(byteOrder).writeInt(length));
```
i think the `ByteBuf` allocated above should be released, am i right ?

### Netty version
4.1.34.Final
### JVM version (e.g. `java -version`)
ava version "1.8.0_102"
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode)
### OS version (e.g. `uname -a`)
Linux  2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 00:57:44 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
No you are wrong... the next handler must release the buffer. My guess is you forgot to call release() in your handler

**Comment by medusar** [comment]
> No you are wrong... the next handler must release the buffer. My guess is you forgot to call release() in your handler
> […](#)
> Am 22.04.2019 um 14:51 schrieb JasonWong ***@***.***>: Expected behavior no memory leak detected Actual behavior memory leak detected, and output error log: 2019-04-22 19:02:24,526 ERROR i.n.u.ResourceLeakDetector [WriteThread-4-15] LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information. Recent access records: Created at: io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:334) io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187) io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178) io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115) io.netty.handler.codec.LengthFieldPrepender.encode(LengthFieldPrepender.java:193) io.netty.handler.codec.LengthFieldPrepender.encode(LengthFieldPrepender.java:55) io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:706) io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:698) io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:780) io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691) io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113) io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:706) io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:698) io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:780) io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691) Steps to reproduce Sorry, my codes are not available now, codes in LengthFieldPrepender: out.add(ctx.alloc().buffer(4).order(byteOrder).writeInt(length)); i think the ByteBuf allocated above should be released, am i right ? Minimal yet complete reproducer code (or URL to code) Netty version 4.1.34.Final JVM version (e.g. java -version) ava version "1.8.0_102" Java(TM) SE Runtime Environment (build 1.8.0_102-b14) Java HotSpot(TM) 64-Bit Server VM (build 25.102-b14, mixed mode) OS version (e.g. uname -a) Linux 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 00:57:44 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

em... I am working to figure it out, i will update soon..

**Comment by medusar** [comment]
My Codes are like this:
```

import io.netty.bootstrap.ServerBootstrap;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.PooledByteBufAllocator;
import io.netty.channel.Channel;
import io.netty.channel.ChannelDuplexHandler;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.ChannelOption;
import io.netty.channel.ChannelOutboundHandlerAdapter;
import io.netty.channel.ChannelPipeline;
import io.netty.channel.ChannelPromise;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.handler.codec.ByteToMessageCodec;
import io.netty.handler.codec.ByteToMessageDecoder;
import io.netty.handler.codec.LengthFieldBasedFrameDecoder;
import io.netty.handler.codec.LengthFieldPrepender;
import io.netty.handler.codec.MessageToByteEncoder;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

/**
 * Created By wlb on 2019-04-22 20:57
 */
public class MemoryLeakServer {

  public static void main(String[] args) {

    System.setProperty("io.netty.leakDetection.level", "paranoid");

    List<Channel> channels = new ArrayList<>();

    ServerBootstrap serverBootstrap = new ServerBootstrap();
    serverBootstrap
        .channel(NioServerSocketChannel.class)
        .group(new NioEventLoopGroup(1), new NioEventLoopGroup())
        .childOption(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
        .childHandler(new ChannelInitializer<SocketChannel>() {
          @Override
          protected void initChannel(SocketChannel ch) throws Exception {
            ChannelPipeline pipeline = ch.pipeline();
            pipeline.addLast(new LengthFieldBasedFrameDecoder(16 * 1024, 0, 4, 0, 4));
            pipeline.addLast(new LengthFieldPrepender(4));
            pipeline.addLast(new MyEncoder());
            pipeline.addLast(new MyDecoder());
            pipeline.addLast(new ChannelDuplexHandler() {

              @Override
              public void channelActive(ChannelHandlerContext ctx) throws Exception {
                channels.add(ctx.channel());

                while (true) {
                  channels.forEach(ch -> ch.writeAndFlush(new Packet("what's wrong with my app?".getBytes())));
                  TimeUnit.MILLISECONDS.sleep(100);
                }
              }

              @Override
              public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise)
                  throws Exception {
                if (msg instanceof Packet) {
                  ctx.write(msg, promise);
                }
              }
            });
          }
        });

    Channel channel = serverBootstrap.bind(9999).channel();
    channel.closeFuture().syncUninterruptibly();
  }

  static class MyEncoder extends MessageToByteEncoder {

    @Override
    protected void encode(ChannelHandlerContext ctx, Object msg, ByteBuf out) throws Exception {
      if (msg instanceof Packet) {
        ((Packet) msg).encode(out);
      }
    }
  }

  static class MyDecoder extends ByteToMessageDecoder {

    @Override
    protected void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out)
        throws Exception {
      out.add(Packet.decode(in));
    }
  }

  static class Packet {

    private byte[] body;

    public Packet(byte[] body) {
      this.body = body;
    }

    public void encode(ByteBuf out) {
      out.writeBytes(body);
    }

    public static Packet decode(ByteBuf in) {
      byte[] data = new byte[in.readableBytes()];
      in.readBytes(data);
      return new Packet(data);
    }
  }

}
```
The only place i do with ByteBuf is `MyDecoder` and `MyEncoder`, in other classes, so it is really strange, and i can't reproduce now,  the error happened about 3 hours ago, when i was doing some pressure tests...

**Comment by njhill** [comment]
@medusar couple of comments on your example:
- You shouldn't sleep in the event loop - this could cause some unexpected behaviour
- What's the reason for overriding `ChannelDuplexHandler.write()`? Right now this could leak if any pooled non-`Packet` messages are encountered. You should at least have an `else { ReferenceCountUtil.release(msg); }`.

**Comment by medusar** [comment]
@njhill Thank you for your advice. 
- The code i provide is just for demonstration.
- The reason for overriding `ChannelDuplexHandler.write()` is that i will do some extra work, for example, msg compressing and  encrypting. I will  add `ReferenceCountUtil.release(msg);` and try again.

**Comment by medusar** [comment]
Let me close this, i will update when i figure something out..
