### ISSUE TITLE
the problem of netty dropping?

### ISSUE THREAD

**Issue by god8816** [netty/netty#9089]
1: network environment： 4G mobile card
2: gateway environment： Linux
3: problem:
The gateway has 7000 long links of industrial control. If 2000 industrial control units are added to the gateway, more than 2000 industrial control units will be offline and then continue to be online.（网关有7000台工控长链接，在加入2000台工控，会导致大于2000台工控下线，然后在持续上线。）

**Comment by normanmaurer** [comment]
sorry but without any more details it is impossible to give you any help.
