### ISSUE TITLE
DNS over HTTPS (DoH) and DNS Over TLS (DoT) Support

### ISSUE THREAD

**Issue by hyperxpro** [netty/netty#9091]
Any Plans To Support DNS over HTTPS (DoH) or DNS over TLS (DoT) in Netty?

DoH: https://tools.ietf.org/html/rfc8484
DoT: https://tools.ietf.org/html/rfc7858

**Comment by normanmaurer** [comment]
No no plans at all atm. That said we are happy to review contributions
