### ISSUE TITLE
EmbeddedChannel Close Regression with 4.1.35.Final

### ISSUE THREAD

**Issue by daschl** [netty/netty#9092]
In one of my unit tests I have code like:

```java
    final Throwable expectedCause = new Exception("something failed");
    EmbeddedChannel channel = new EmbeddedChannel(new ChannelOutboundHandlerAdapter() {
      @Override
      public void close(ChannelHandlerContext ctx, ChannelPromise promise) {
        promise.tryFailure(expectedCause);
      }
    });
   channel.disconnect().addListener(future -> {
    // future should fail, but is successful since 4.1.35.Final
   });
```

To simulate a failing channel close. This worked great up until 4.1.34.Final, but in the latest version 4.1.35.Final this test failed. 

Turns out when I debug into it, the close method of the `ChannelOutboundHandlerAdapter` is never called on `channel.disconnect()` and as a result my assertions fail since the channel close completes successfully instead of triggering the failure.

Is this expected?

**Comment by normanmaurer** [comment]
Nope will look into it next week.

Does it work when calling channel.close() ?

**Comment by daschl** [comment]
Yes, when calling `channel.close()` my handler is triggered, when calling `channel.disconnect()` it is not.

**Comment by normanmaurer** [comment]
Ok thanks will check but not before Monday. Feel free to investigate in the meantime if you have cycles

**Comment by daschl** [comment]
@normanmaurer no rush. won't have time to dig into it before next week either - let's sync up then.

**Comment by njhill** [comment]
@normanmaurer @daschl see #9098
