### ISSUE TITLE
The isValidIpV6Address method of the NetUtil class determines that ::0:0:0:0:FFFF:255.255.255.255 is a valid IpV6 address. Is it reasonable?

### ISSUE THREAD

**Issue by xiaoheng1** [netty/netty#9097]
The isValidIpV6Address method of the NetUtil class determines that ::0:0:0:0:FFFF:255.255.255.255 is a valid IpV6 address. Is it reasonable?

@Test
    public void test006() throws UnknownHostException {
        System.out.println(NetUtil.isValidIpV6Address("::0:0:0:0:FFFF:255.255.255.255"));
    }

but the result is true.

i see https://tools.ietf.org/html/rfc5952#section-4

4.2.1.  Shorten as Much as Possible

   The use of the symbol "::" MUST be used to its maximum capability.
   For example, 2001:db8:0:0:0:0:2:1 must be shortened to 2001:db8::2:1.
   Likewise, 2001:db8::0:1 is not acceptable, because the symbol "::"
   could have been used to produce a shorter representation 2001:db8::1.

**Comment by normanmaurer** [comment]
@xiaoheng1 are you saying it should only return true if you pass in `::FFFF:255.255.255.255` ?

**Comment by xiaoheng1** [comment]
@normanmaurer Yes, I saw https://tools.ietf.org/html/rfc5952#section-4.
Its section 4.2.1. says it should be as short as possible.
The specific description is as follows:
The use of the symbol "::" MUST be used to its maximum capability.
   For example, 2001:db8:0:0:0:0:2:1 must be shortened to 2001:db8::2:1.
   Likewise, 2001:db8::0:1 is not acceptable, because the symbol "::"
   could have been used to produce a shorter representation 2001:db8::1.

So, I think that only ::FFFF:255.255.255.255 returns true may be better.

**Comment by fenik17** [comment]
> Shorten as Much as Possible

This is only recomendation for representation. Netty must accept any legitimate [RFC4291] format. 
And "::0:0:0:0:FFFF:255.255.255.255" is a legitimate format.

> The recommendation in this section SHOULD be followed by systems when generating an
> address to be represented as text, *but all implementations MUST
> accept and be able to handle any legitimate [RFC4291] format*.

**Comment by normanmaurer** [comment]
As @fenik17 said...

**Comment by xiaoheng1** [comment]
@fenik17 @normanmaurer Understand, thanks!
