### ISSUE TITLE
The public int lastIndexOf(CharSequence string) method of the AsciiString class always returns -1

### ISSUE THREAD

**Issue by xiaoheng1** [netty/netty#9099]
public int lastIndexOf(CharSequence string) {
        // Use count instead of count - 1 so lastIndexOf("") answers count
        return lastIndexOf(string, length());
    }

@Test
    public void test004(){
        byte[] bytes = new byte[]{1,2,3,4,5,6,7,8,9,10};
        AsciiString ascii = new AsciiString(bytes, 0, 10, false);
        int b = ascii.lastIndexOf("6");
        System.out.println(b);

    }

the result is -1.

**Comment by jxl4650152** [comment]
- Which version do you use?
- -1 means no substring found.
- 6 in array _bytes_ of your method _test004()_ is a byte which will be interpreted \u0006 in AsciiString, while "6" is a string  whose ascii value is \u0036.
- `byte[] bytes =  new byte['1', '2', '3', '4', '5', '6', '7', '8', '9'] ` may be what you want.

**Comment by xiaoheng1** [comment]
1. i use netty-4.1.34 version.
2.Based on your comments, I added a test case：
@Test
    public void test005(){
        AsciiString ascii = new AsciiString("12345678910");
        int b = ascii.lastIndexOf("6");
        System.out.println(b);

    }
But the result is still -1, this is not what I expected.In my opinion, this should return 5.

I looked at the source code,

public int lastIndexOf(CharSequence string) {
// Use count instead of count - 1 so lastIndexOf("") answers count
return lastIndexOf(string, length());
}

lastIndexOf(string, length()) should be modified to lastIndexOf(string, 0) ?

**Comment by qeesung** [comment]
@xiaoheng1 You're right. I also checked the source code. This should be an issue, I will do PR later.

**Comment by xiaoheng1** [comment]
OK,  Thanks!

**Comment by njhill** [comment]
Thanks @xiaoheng1, have opened #9103 to address this.

**Comment by xiaoheng1** [comment]
OK, Thanks!
