### ISSUE TITLE
refCnt() is 1 but internally 2?

### ISSUE THREAD

**Issue by konsultaner** [netty/netty#9104]
I found a memory leak in my software and wanted to fix it. The problem is, that I'm not shure where the `refCnt` really is:

![image](https://user-images.githubusercontent.com/2699538/56890887-02ae2680-6a7b-11e9-90d6-240317bdf86a.png)

if i realease the `byteBufMessage` after adding the message to the list object, I get an error that the refcnt already is 0.

my inbound stack:
SSLHandler -> Websocket -> Some custom handler
my outbound stack
MessageToMessageEncoder -> IdleStateHandler

**Comment by normanmaurer** [comment]
enable paranoid leak detection and it should give you some clues:

https://netty.io/wiki/reference-counted-objects.html#troubleshooting-buffer-leaks

**Comment by konsultaner** [comment]
@normanmaurer paranoid leak detection is enabled. I just don't get why the the same object has 2 different refCnt?

**Comment by normanmaurer** [comment]
@konsultaner because `CompositeByteBuf` is a container of multiple `ByteBuf` ?

**Comment by konsultaner** [comment]
@normanmaurer sorry, I don't want to be enoying, I just don't get it. All 3 Components also have a refCnt of 2. 
![image](https://user-images.githubusercontent.com/2699538/56909245-2b98e080-6aa8-11e9-9980-206a9a586a60.png)

**Comment by njhill** [comment]
@konsultaner the raw value of the internal `refCnt` field itself is not the actual ref count, as warned by the [comment](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/AbstractReferenceCountedByteBuf.java#L44) next to it:
```java
// Value might not equal "real" reference count, all access should be via the updater
```
The mapping is described here: https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/ReferenceCountUpdater.java#L32-L34

**Comment by konsultaner** [comment]
@njhill Thank you very much. Its not trivial to have everything leak free. Helped me a lot!

**Comment by shoudlee** [comment]
Thanks, I met this weird thing too...
