### ISSUE TITLE
(Nio)EventLoop is triggering unnecessary wakeup(s)

### ISSUE THREAD

**Issue by franz1981** [netty/netty#9112]
In order to test the impact of https://github.com/netty/netty/pull/9109 I have found an unexpected behaviour on NioEventLoop.
To reproduce it is necessary to run a modified BurstCostExecutorsBenchmark with NioEventLoop burstLength = 1 , work = 0 on NioEventLoop:
```java
    private int executeBurst(final PerThreadState state) {
        final ExecutorService executor = this.executor;
        final int burstLength = this.burstLength;
        final Runnable completeTask = state.completeTask;
        for (int i = 0; i < burstLength; i++) {
            executor.execute(completeTask);
        }
        final int value = state.spinWaitCompletionOf(burstLength);
        state.resetCompleted();
        Blackhole.consumeCPU(100);
        return value;
    }
```
The `Blackhole.consumeCPU(100)` is enough to force an awaken selector to go to sleep and I was expecting to pay the full cost of awaking it while offering, but it isn't happening.
It seems to me that 
```
if (wakenUp.get()) {
    selector.wakeup();
}
```
on NioEventLoop is refilling the "awake credits", making the subsequent `select(timeout)` to return immediately.
I would work in order to reproduce it with a simpler and minimal test and maybe is just my understanding of the event loop duty cycle that is giving me false expectations on the outcome of such test.

**Comment by franz1981** [comment]
@njhill wdyt? I know you are interested into learning how the event logic work so if you have any thoughts on that please share :)

**Comment by franz1981** [comment]
I have found the relevant behaviour, but given that is a concurrent mechanism is not that easy to reproduce it: 

1. NioEventLoop is gone to select(timeout)  and wakenUp = false (with old wakenUp = false)
2. a task's offer happen: wakenUp succeed to false -> true and selector::wakeup() is called on the offering thread
3. select(timeout) will exit due to the wakeup (== true) or hasTask == true
4. wakeup == true, so selector::wakeup() is called in the event loop
5. the existing task is being executed
6. the event loop will go nto select(timeout)  and wakenUp = false (with old wakenUp = true)

For now on, the event loop has a previous call to selector::wakeup() that will return it "immediately" (it is taking ~1 us on my machine): if due to lucky timing a new offer will arrive in time, the offering thread won't pay the full cost of awaking the selector, because it was already awaking AND an additional selector::wakeup() will be called by the event loop.

This logic is nice, because allows the eventloop to "linger"  before going into a deep sleep, saving expensive signaling on offer side, but is kinda "cheating", because there was no reasons to give an additional selector::wakeup() from teh event loop.
it means that for slow throughput offers we "spin" at least one additional time before going to sleep.
If is the expected behaviour I can close this issue.

**Comment by njhill** [comment]
@franz1981 I am interested but it will need to look at it closely for a bit to absorb what's going on myself too. From a quick read of your analysis though it sounds right and I assume is behaving as intended. If so I guess the question is more whether the mechanics are optimal w.r.t. balancing the various signalling costs, when taking into account "real life" workloads.
