### ISSUE TITLE
KQueueEventLoop might unregister active channels due to domain socket file descriptor reuse

### ISSUE THREAD

**Issue by vietj** [netty/netty#9113]
### Expected behavior
The current `KQueueEventLoop` implementation does not unregister active channels when domain socket file descriptor are reused.

### Actual behavior
The current `KQueueEventLoop` implementation does not process concurrent domain socket channel registration/unregistration in the order they actual happen since unregistration are delated by an event loop task scheduling. When a domain socket is closed, it's file descriptor might be reused quickly and therefore trigger a new channel registration using the same descriptor.

Consequently the `KQueueEventLoop#add(AbstractKQueueChannel)` method will overwrite the current inactive channels having the same descriptor and the delayed `KQueueEventLoop#remove(AbstractKQueueChannel)` will remove the active channel that replaced the inactive one.

As active channels are registered, events for this file descriptor won't be processed anymore and the channels will never be closed. The `KQueueEventLoop` will also log such events with `WARN io.netty.channel.kqueue.KQueueEventLoop - events[2]=[120, -1] had no channel!`

### Steps to reproduce
Connect multiple channels doing a simple request/response and let the client close the channels when it receive the response. When there are enough channels, this will happen.

### Minimal yet complete reproducer code (or URL to code)
I will provide a PR with a test and a tentative fix.

### Netty version
4.1.34.Final and above

### JVM version (e.g. `java -version`)
Not related

### OS version (e.g. `uname -a`)
Darwin MacBook-Pro-de-julien.local 17.7.0 Darwin Kernel Version 17.7.0: Fri Nov  2 20:43:16 PDT 2018; root:xnu-4570.71.17~1/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
@vietj sorry I had to revert your PR as it lead to build failures locally. I will need to dig into this but I have no time atm :/

**Comment by vietj** [comment]
ok, I think another option to fix it would be sure that the event arrive in the correct order, i.e an unregister does not happen after a register

**Comment by vietj** [comment]
I believe at least what could be changed for now is the fact that registering a channel with an existing descriptor would thrown an IllegalStateException to have proper failure when this happen

**Comment by normanmaurer** [comment]
@vietj PTAL at https://github.com/netty/netty/pull/9149 for a proper fix. Thanks again for the initial code :)
