### ISSUE TITLE
Need clarification regarding eventloop task execution order

### ISSUE THREAD

**Issue by arukshani** [netty/netty#9128]
### Actual behavior
We have a HTTP/2 client and a server written in netty and the scenario is a proxy, where when the httpcontent is received from the inbound handler(client/upstream), it passes that content to the  downstream respond call. 

Logic is similar to the following. When the content is received it calls the firstMethod(). Then when the stream becomes not writable for downstream, it stops the consumeByte logic. Then when it becomes writable again it calls the secondMethod to immediate consume the unconsumed bytes. 

`firstMethod(httpcontent) {
  channelHandlerContext.channel().eventLoop().execute(() -> {
      h2LocalFlow.consumeBytes(httpcontent.lenght);
  });
}`

`secondMethod() {
 channelHandlerContext.channel().eventLoop().execute(() -> {
       h2LocalFlow.consumeBytes(uncomsumedbytes)
  });
}`

My question is, even though the firstMethod is getting called from the same eventloop as in its task, firstMethod's execute logic won't get executed immediately. 
 
So the execution order is, assume I get three httpcontents, then 
firstMethod() >> put it in task list
firstMethod() >> put it in task list
firstMethod() >> put it in task list
secondMethod() >> task executes immediately.
firstMethod's task gets executed
firstMethod's task gets executed
firstMethod's task gets executed

Can someone please help me understand the execution order of the tasks and why firstMethod's task gets executed later even though the calling thread and the execute thread are same?

### Netty version
4.1.34.Final

**Comment by normanmaurer** [comment]
If you call `execute(...)` it does not matter if you are on the same thread or not we always will put it in the queue. If you need to execute directly you should just check if you are on the EventLoop or not and if so execute directly and not use `execute`.

**Comment by arukshani** [comment]
Got it. Thanks @normanmaurer
