### ISSUE TITLE
WebSocketClientHandshaker13 Invalid Handshake

### ISSUE THREAD

**Issue by davydotcom** [netty/netty#9134]
### Expected behavior

Origin Header should be sent on handshake

### Actual behavior

Sec-WebSocket-Origin Header is sent instead which is not a client handshake but rather a server to client origin handshake per the Specification

**Comment by normanmaurer** [comment]
@davydotcom do you have a reproducer ?

**Comment by davydotcom** [comment]
Use websocket client in netty in any way and it’s very easily reproduced code is wrong in handshaker

**Comment by marci74** [comment]
We use Netty through Vert.x for an application. For some of our websocket tests we modify the "origin" header of the client requests. This does not work anymore due to the changes here. Maybe you can change the behaviour and set the "origin" header only if it is not already present?

**Comment by marci74** [comment]
Resolved in #9435. Sorry for the duplicate comment.
