### ISSUE TITLE
Boringssl TLS handshake ignores servers cipher suite preference even if preferLocalCipherSuites is set

### ISSUE THREAD

**Issue by polarctos** [netty/netty#9140]
### Expected behavior
The JDK SSL provider `SslProvider.JDK` correctly prioritizes the cipher suites configured on the server side (if configured at server) if one RSA and one ECC signed certificate are used for the same endpoint.  
This same prioritization behavior is also expected from the `SslProvider.OPENSSL`.

The server preference is set via: `sslHandler.engine().getSSLParameters().setUseCipherSuitesOrder(true)`

### Actual behavior
When the BoringSSL provider `SslProvider.OPENSSL` is configured, the cipher suite preference from the client is used, irrespective of the priority configuration on the server side.
(Prioritizing the server cipher suites is a recommended configuration for servers. See e.g. [nginx on cipherlist,](https://cipherli.st/) the JDK also provides a configuration option for this.)

Native SSL is used via `netty-tcnative-boringssl-static`.

### Steps to reproduce

Start a server with TLS 1.2 and configure CipherSuites, in this order: `"TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"`

I used the [secure chat example](https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/securechat) to reproduce this behavior.
Instead of a self signed certificate from the example use a `KeyStore ` (PKCS12) that includes both a certificate using ECC (ECDSA) and one using RSA for the same subject names.

Configure the `SSLHandler `with:
`sslHandler.engine().getSSLParameters().setUseCipherSuitesOrder(true);`

With e.g. OpenSSL as test client use:
`openssl s_client -connect localhost:8992 -cipher "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384" -sigalgs "ECDSA+SHA256:RSA+SHA256" -tls1_2`

Now:
* With JDK Provider: cipher with RSA is chosen correctly, and RSA certificate sent to client
* With OpenSSL Provider: cipher with ECDSA is chosen, and ECC certificate sent to client ⚠️

### Minimal yet complete reproducer code (or URL to code)
_Not yet online. If required I'll put together a small reproducer._

### Netty version
`io.netty:netty-handler:4.1.36.Final`
`io.netty:netty-tcnative-boringssl-static:2.0.25.Final`

### JVM version (e.g. `java -version`)
`OpenJDK Runtime Environment (Zulu 8.36.0.1-CA-win64) (build 1.8.0_202-b05)`

### OS version (e.g. `uname -a`)
`Microsoft Windows [Version 10.0.16299.1087]`

**Comment by normanmaurer** [comment]
@polarctos just so I get this right you configure it with dual cert (like EC and RSA) ? If so this is not surprising as BoringSSL does currently not support this :/

https://bugs.chromium.org/p/boringssl/issues/detail?id=249

**Comment by polarctos** [comment]
@normanmaurer Thanks for the link to the handling in BoringSSL.

However as far as I debugged it, the certificate selection actually currently happens in the JDK part of the TLS handling, also when the `SslProvider.OPENSSL` is used.
The keystore contains two aliases, thus the non caching KeyManager is chosen and for every handshake the suitable certificates are selected in the [X509KeyManagerImpl](https://github.com/JetBrains/jdk8u_jdk/blob/master/src/share/classes/sun/security/ssl/X509KeyManagerImpl.java).

Thus when the client only presents one cipher suite, for both the JDK and the OpenSSL SslProviders the handshake works correctly.
So for the server with two certificates/keys in a KeyStore configured as described in the issue:
* `openssl s_client -connect localhost:8992 -cipher "ECDHE-ECDSA-AES256-GCM-SHA384" -sigalgs "ECDSA+SHA256" -tls1_2`
-> returns the EC certificate
* `openssl s_client -connect localhost:8992 -cipher "ECDHE-RSA-AES256-GCM-SHA384" -sigalgs "RSA+SHA256" -tls1_2`
-> returns the RSA certificate

**Comment by normanmaurer** [comment]
@polarctos Yep we hook in the java `KeyManager` but the "problem" is still the same... BoringSSL need to fix this first before we can support it. If you change to use `netty-tcnative` you will see it will work (using openssl).

**Comment by polarctos** [comment]
@normanmaurer When using OpenSSL with `netty-tcnative` instead of BoringSSL it actually works and the correct cipher suite is selected!

So until it is fixed in BoringSSL it won't work with that dependency. Thanks for the clarification.

**Comment by JimmyBaize** [comment]
Is that the reason for the problem?
https://github.com/netty/netty/blob/1ecc053e70d57a8da70bf23bf5293b2072337b09/handler/src/main/java/io/netty/handler/ssl/OpenSslKeyMaterialManager.java#L79

`keyType `  should come from  client ciphersuit ,instead of  `engine.authMethods()`




https://github.com/netty/netty/blob/1ecc053e70d57a8da70bf23bf5293b2072337b09/handler/src/main/java/io/netty/handler/ssl/ReferenceCountedOpenSslServerContext.java#L228
keyTypeBytes is null.

Can't  the method get keyType of client when use boringssl?
