### ISSUE TITLE
Version Branch 4.1 - Does not compile.

### ISSUE THREAD

**Issue by LoveraSantiago** [netty/netty#9144]
### OS version (e.g. `uname -a`) - windows

On version of Branch 4.0 on package "common/src/main/java/io/netty/util/" it has "collection" (package-folder).
But on Branch 4.1 this folder does not exist anymore. Wich causes error of compilation on class FixedRedisMessagePool on imports imports "io.netty.util.collection.LongObjectHashMap;" and 
"import io.netty.util.collection.LongObjectMap;"

If I am wrong I apologize for creating an unnecessary issue.

![image](https://user-images.githubusercontent.com/7741737/57573725-cecfeb00-7402-11e9-9b3c-cfbaac2a4ddc.png)

![image](https://user-images.githubusercontent.com/7741737/57573738-fc1c9900-7402-11e9-9cea-aeb0d604b703.png)

**Comment by amizurov** [comment]
Hi @LoveraSantiago, this is autogenerate collection. Run this  `mvn compile -pl common -am`

**Comment by LoveraSantiago** [comment]
Thanks @amizurov .
