### ISSUE TITLE
JVM warnings running Netty 3.6.6.Final on Java 11

### ISSUE THREAD

**Issue by agrawalrahul0305** [netty/netty#9163]
### Expected behavior
No Warnings from JVM
### Actual behavior
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jboss.netty.util.internal.ByteBufferUtil (file:.m2/repository/io/netty/netty/3.6.6.Final/netty-3.6.6.Final.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.jboss.netty.util.internal.ByteBufferUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
### Steps to reproduce
Run a Netty 3.6.6 or 4.0.0 application on JDK 11
### Netty version
3.6.6.Final also happens on higher version
### JVM version (e.g. `java -version`)
Open JDK 11.0.2
### OS version (e.g. `uname -a`)
MacOS High Sierra

**Comment by normanmaurer** [comment]
@agrawalrahul0305 netty 3.x is EOL for years and so is not maintained anymore. You should upgrade to 4.1.x.

**Comment by agrawalrahul0305** [comment]
@normanmaurer i tried upgrading to 4.1.6.Final but i get below error after that.

Caused by: java.lang.NoClassDefFoundError: org/jboss/netty/channel/ChannelFutureListener

**Comment by normanmaurer** [comment]
@agrawalrahul0305 yes because it is a major version bump... you will need to adjust the code-base to move from 3.x to 4.1.x.

**Comment by agrawalrahul0305** [comment]
Thanks.
