### ISSUE TITLE
ctx.writeAndFlush throws BlockingOperationException even channel handler is in separate EventExecutorGroup

### ISSUE THREAD

**Issue by baijianhua** [netty/netty#9164]
### Expected behavior
BlockingOperationException only need to be thrown when calling await inside IO thread

### Actual behavior
This is exception is thrown even when doing this:
```
ChannelInitializer(){
      initChannel(...){
           addLast(....)
           addLast(eventExecutorGroup,"businessExecutor", new SimpleChannelInboundHandler(){
                 channelRead0(...){
                        val p = ctx.writeAndFlush(msg)
                        p.await()
                 }  
           })
      }
}
```
### Netty version
4.1.36

**Comment by baijianhua** [comment]
Can this method in DefaultChannelPromise.java
`
protected void checkDeadLock() {
        if (channel().isRegistered()) {
            super.checkDeadLock();
        }
}
`

be changed to 
protected void checkDeadLock() {
        if (channel().isRegistered() && channel().eventLoop() == executor()) {
            super.checkDeadLock();
        }
}

**Comment by medusar** [comment]
why do you need to block? you can add a listener to the ChannelFuture.

**Comment by normanmaurer** [comment]
@baijianhua it makes no sense to call `p.wait()` in a `ChannelHandler` that uses the same `EventExecutor` as the `ChannelPromise`.

**Comment by baijianhua** [comment]
@medusar 
> why do you need to block? you can add a listener to the ChannelFuture.

Using listener makes the code ugly.  the use case of writeAndFlush().await is I'm encoding msg to a list of small messages and send them later in IO thread.

**Comment by baijianhua** [comment]
@normanmaurer If I do not call await, there should be no guarantee that previous operation is done successfully, if previous operation is not success, then I would cancel remained steps.

**Comment by qeesung** [comment]
No blocking operation should be included in EventLoop because EventLoop is single-threaded and can cause deadlocks if blocked. As an alternative, adding a listener or await future in a custom thread pool is a reasonable solution

**Comment by baijianhua** [comment]
@qeesung 
I'm using DefaultEventExecutorGroup, it  extends MultithreadEventExecutorGroup

**Comment by qeesung** [comment]
Although EventGroup is multi-threaded, Channel is registered as a thread in EventGroup after it is created, so asynchronous writeAndFlush and synchronous await operations are in the same thread. Blockage of await causes writeAndFlush to never be executed.

The thread that calls the await method is the IO thread.

**Comment by baijianhua** [comment]
@qeesung 
I'm not sure if I understood you correctly. but from the code I'm using, channel's eventloop is in different thread than my business executor. So there is not dead lock. await in business executor, will be notified later by channel's event loop thread.

here is the kotlin code after I modified the DefaultChannelPromise.java
```
fun main(){
    val mBoss = NioEventLoopGroup(1) //for listen fvbgd
    val mWorker = NioEventLoopGroup(4) //for processing i/o of each socket/channel
//    val businessExecutor = MsEventExecutorGroup(4) //业务线程池
    val businessExecutor = DefaultEventExecutorGroup(4) //业务线程池


    val bs = ServerBootstrap()
    bs.group(mBoss, mWorker)
        .channel(NioServerSocketChannel::class.java)
        .option(ChannelOption.SO_BACKLOG, 128)
        .childOption(ChannelOption.SO_KEEPALIVE, true)
        .option(ChannelOption.SO_REUSEADDR,true)
        .childHandler(object : ChannelInitializer<SocketChannel>(){
            override fun initChannel(ch: SocketChannel?) {
                val pipe = ch?.pipeline() ?: return
                with(pipe){
                    addLast("decoder",object:StringDecoder(){
                        override fun decode(ctx: ChannelHandlerContext?, msg: ByteBuf?, out: MutableList<Any>?) {
                            mslog.info("MsString decoder")
                            super.decode(ctx, msg, out)
                        }
                    })
                    addLast("encoder",object:StringEncoder(){
                        override fun encode(ctx: ChannelHandlerContext?, msg: CharSequence?, out: MutableList<Any>?) {
                            Thread.sleep(1000)

                            mslog.info("MsStringEncoder")
                            super.encode(ctx, msg, out)
                        }
                    })
//                    addLast("business",object:SimpleChannelInboundHandler<String>(){
                    addLast(businessExecutor,"business",object:SimpleChannelInboundHandler<String>(){
                        override fun channelRead0(ctx: ChannelHandlerContext?, msg: String?) {
                            if(ctx == null)
                                return

                            try{
                                mslog.info("Received a string=$msg")
                                mslog.info("reply")
                                mslog.info("channel.eventloop=${channel().eventLoop()} channel.executor=${channel().pipeline().firstContext().executor()} currentExectutor=${ctx?.executor()}")
                                val p1 = ctx.writeAndFlush("Reply")
                                p1.await()
                                val p2 = ctx.writeAndFlush("Reply2")
                                p2.await()
                                val p3 = ctx.writeAndFlush("Reply3")
                                p3.await()


                                mslog.info("2 Last handler ======= $msg")
                            }catch (e:Exception){
                                e.printStackTrace()
                            }
                        }
                    })
                }
            }
        })

    val f = bs.bind("0.0.0.0", 8899).sync()
    if (f.isSuccess) {
        println("server  is started at ")
    } else {
        exitProcess(0)
    }
    f.channel().closeFuture().addListener { exitProcess(0) }
}
```

**Comment by qeesung** [comment]
@baijianhua Sorry, I didn't notice that you put the Handler in a thread separate from the I/O Thread.
I think it is necessary to detect in `ChannelPromise` (`ChannelFuture`) whether the current thread and the thread bound to the channel are the same thread.

**Comment by baijianhua** [comment]
@qeesung thank you. so it make sense to add this change?

**Comment by qeesung** [comment]
@normanmaurer When adding a Handler, specifying an `ExecutorGroup` that is different from the childGroup, then all I/O-related tasks in this Handler (such as wirte, bind) will be submitted to the childGroup, in other words, `ChannelFuture.await` Will not cause a deadlock, because the execution of the task associated with the promise and the wait for the promise are in separate threads.

Do you think it is necessary to check whether the executor of Promise and the current channel executor are the same thread in the `checkDeadLock` method in `ChannelPromise`?

Like the following

```java
@Override
protected void checkDeadLock() {
    if (channel().isRegistered() && channel().eventLoop() == executor()) {
        super.checkDeadLock();
    }
}
```

**Comment by normanmaurer** [comment]
@qeesung I think it is still necessary as you could still end up with a deadlock if another handler that is in from of the handler and uses the same `EventExecutorGroup` will delay the notification of the promise.

**Comment by qeesung** [comment]
@normanmaurer I see. Thank you

**Comment by qeesung** [comment]
@baijianhua As @normanmaurer said, If the same `EventGroupExecutor` is bound to different handlers on the same Pipeline, calling await can cause deadlock, although the thread calling await and the IO thread are not the same thread.

Like the following

```java
pipe.addLast(executorGroup1, handler1);
pipe.addLast(executorGroup2, handler2);
pipe.addLast(executorGroup1, new SimpleChannelInboundHandler<String>() {
    @Override
    protected void channelRead0(ChannelHandlerContext ctx, String msg) throws Exception {
        ChannelFuture f = ctx.writeAndFlush("hello world");
        f.await();
    }
});
```

Instead, I recommend adding listener, or await it it in a custom thread (pool).
