### ISSUE TITLE
what kind of conditions will cause channeFuture got this info ?

### ISSUE THREAD

**Issue by AnnieCattice** [netty/netty#9178]
`DatagramPacket datagramPacket = new DatagramPacket(response, msg.sender());
		ChannelFuture future = ctx.writeAndFlush(datagramPacket);
		logger.info("future info:{}", JSON.toJSONString(future));`

when i run this code on docker container , my udp client cannot get server's response.

 i try to print ChannelFuture info and got the following result:
future info:{"cancellable":true,"cancelled":false,"done":false,"success":false,"void":false,cause:null}

why the udp server failed to write data without throwable? 
and i don't understand what would cause this result.

**Comment by normanmaurer** [comment]
The Future is not completed yet... Add the logger to a ChannelFutureListener or block on the ChannelFuture to ensure it is complete when the logging happens.
