### ISSUE TITLE
Do you have plans to support the IETF's QUIC protocol?

### ISSUE THREAD

**Issue by cocowolf** [netty/netty#9194]
Hi
The IETF organization has split google's QUIC protocol into two protocols, QUIC and HTTP3.
QUIC is the perfect solution for lockstep games.Do you have plans to support the IETF's QUIC protocol?

Thanks!

**Comment by normanmaurer** [comment]
Yes... see https://github.com/netty/netty/issues/3778

**Comment by normanmaurer** [comment]
The work for QUIC is happening here and I think we are very close for a release: https://github.com/netty/netty-incubator-codec-quic
