### ISSUE TITLE
The method toString() of MqttSubscribePayload throw ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by xiangwangcheng** [netty/netty#9197]
### Expected behavior
print MqttSubscribePayload correctly
### Actual behavior
ArrayIndexOutOfBoundsException was thrown
### Steps to reproduce
new a MqttSubscribePayload which has no topicSubscriptions(size of List<MqttTopicSubscription> is 0)

Though the MqttSubscribePayload couldn't be empty in MQTT protocol. There also some cases like unit test that should cover this situation.
So, I think the code below seems not gracefully enough.

```
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder(StringUtil.simpleClassName(this)).append('[');
        for (int i = 0; i < topicSubscriptions.size() - 1; i++) {
            builder.append(topicSubscriptions.get(i)).append(", ");
        }
        builder.append(topicSubscriptions.get(topicSubscriptions.size() - 1));
        builder.append(']');
        return builder.toString();
    }
```
Could we implement it like this below?
```
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder(StringUtil.simpleClassName(this)).append('[');
        for (int i = 0; i <= topicSubscriptions.size() - 1; i++) {
            builder.append(topicSubscriptions.get(i)).append(", ");
        }
        if (builder.substring(builder.length() - 2).equals(", ")) {
            builder.delete(builder.length() - 2, builder.length());
        }
        builder.append(']');
        return builder.toString();
    }
```
### Minimal yet complete reproducer code (or URL to code)
```
    @Test
    public void test_MqttSubscribePayload_toString() {
        List<MqttTopicSubscription> subscriptions = new ArrayList<>();
        MqttSubscribePayload payload = new MqttSubscribePayload(subscriptions);

        System.out.println(payload.toString());
    }
```
### Netty version
4.1.32.Final
### JVM version (e.g. `java -version`)
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

### OS version (e.g. `uname -a`)
windows

**Comment by SplotyCode** [comment]
I could provide a PR. You can use set Length instead of delete in String Builder btw

**Comment by normanmaurer** [comment]
@SplotyCode please if you have time :)

**Comment by xiangwangcheng** [comment]
@SplotyCode Thanks for your suggestion, it's much better.
