### ISSUE TITLE
HAProxyMessage memory leak due unreleased TLVs 

### ISSUE THREAD

**Issue by shevah** [netty/netty#9201]
`HAProxyMessage` isn't a `ReferencedCounted` object. 
A component consuming an `HAProxyMessage` object and not passing it further might not release it, while it should be released as it contains a list of TLVs created in the static function `readNextTLV`:

https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java#L235-L241

Notice that this function retains a slice of the original header ByteBuf increasing its refCnt and causing a possible memory leak if one forgets to release them explicitly:

https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/codec-haproxy/src/main/java/io/netty/handler/codec/haproxy/HAProxyMessage.java#L296

I would expect `HAProxyMessage` to implement `ReferencedCounted` and release the TLVs in a similar fashion to: `haProxyMessage.tlvs().forEach(tlv -> tlv.release());` 

We have found this issue only after we had leaks.

Furthermore, it seems that slices are purposely retained as seen in Netty tests, am I missing something?

https://github.com/netty/netty/blob/00afb19d7a37de21b35ce4f6cb3fa7f74809f2ab/codec-haproxy/src/test/java/io/netty/handler/codec/haproxy/HAProxyMessageDecoderTest.java#L642-L650

### Netty version
4.1.36

**Comment by normanmaurer** [comment]
@shevah yes this sounds like a bug... Would you be willing to create a PR to fix it ?

**Comment by shevah** [comment]
Yes

**Comment by shevah** [comment]
Yes
