### ISSUE TITLE
WebSocketClientHandshaker13 doesn't work with HTTP proxies over clear HTTP

### ISSUE THREAD

**Issue by slandelle** [netty/netty#9205]
### Expected behavior

When talking with an HTTP proxy over clear HTTP, a user agent should sent requests with an **absolute** url.

### Actual behavior

`WebSocketClientHandshaker13::newHandshakeRequest` generates a request with [relative url](https://github.com/netty/netty/blob/netty-4.1.36.Final/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshaker13.java#L164).

### Steps to reproduce

NA

### Minimal yet complete reproducer code (or URL to code)

NA

### Netty version

4.1.36.Final

### JVM version (e.g. `java -version`)

irrelevant

### OS version (e.g. `uname -a`)

irrelevant

**Comment by normanmaurer** [comment]
@slandelle will you provide a PR ?

**Comment by slandelle** [comment]
FYI, it's currently very hard to workaround this issue by subclassing WebSocketClientHandshaker13: `expectedChallengeResponseString` is private, `WebSocketUtil` is package private.

I would love to contribute a fix but I'd like your opinion:

* is this too much of a corner case so we should move WebSocketClientHandshaker13's url computation into a protected method so usr can subclass?
* or should we add yet another constructor with a new boolean parameter to all WebSocketClientHandshakerXX classes and another factory method in WebSocketClientHandshakerFactory?

**Comment by normanmaurer** [comment]
@slandelle will it be a problem to always use the relative url ?

**Comment by slandelle** [comment]
@normanmaurer Absolutely, most server implementations will rightfully blow up because of the malformed request. The only case you use absolute urls is with HTTP proxy over clear HTTP.

**Comment by normanmaurer** [comment]
hmm I see... I am not sure what is better (protected vs static method). WDYT ?

**Comment by slandelle** [comment]
I'd say to go with the additional parameter/constructors/factory for Netty 4.1.

But this really needs to be cleaned up for Netty 5: drop early specs, make single constructor package protected and introduce a Builder a la `DnsNameResolverBuilder`.

WDYT?

**Comment by normanmaurer** [comment]
@slandelle sounds fine to me...
