### ISSUE TITLE
Http2ConnectionHandler#goAway should not initiate channel graceful shutdown

### ISSUE THREAD

**Issue by voidzcy** [netty/netty#9207]
Introduced by #9094, in  [Http2ConnectionHanlder](https://github.com/netty/netty/blob/ec69da9afb8388c9ff7e25b2a6bc78c9bf91fb07/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L842), when there is no active stream, doing GO_AWAY with error code NO_ERROR will immediately shut down the channel once the GO_AWAY frame is sent. This breaks higher layer implementation's logic of graceful shutdown, such as [in gRPC](https://github.com/grpc/grpc-java/blob/276b7d8512d4b74851f86314b1f20ff962b3bd90/netty/src/main/java/io/grpc/netty/NettyServerHandler.java#L874). Now that [the `GOAWAY(<max id>)`, `PING`, `PING(ACK)`, `GOAWAY(<real id>)` approach](https://github.com/netty/netty/pull/9094#issuecomment-487231456) is left for higher layer implementations, graceful shutdown should not be initiated in `Http2ConnectionHandler#goAway(...)`. 

/cc @Scottmitch @ejona86 @carl-mastrangelo @dapengzhang0

**Comment by carl-mastrangelo** [comment]
Is there any chance a fix for this could go into the 4.1.37 cut?

**Comment by normanmaurer** [comment]
@carl-mastrangelo yes we definitely want to "fix" this before.

**Comment by Scottmitch** [comment]
please review https://github.com/netty/netty/pull/9227

**Comment by normanmaurer** [comment]
@carl-mastrangelo @voidzcy @ejona86 can you test with the latest snapshot and verify this fixes the issue in GRPC ?

**Comment by carl-mastrangelo** [comment]
@normanmaurer I'll work with @voidzcy    to try it out tomorrow.

**Comment by normanmaurer** [comment]
Thanks a lot !

**Comment by voidzcy** [comment]
@normanmaurer I just pulled `4.1.37.Final-SNAPSHOT/	Fri Jun 07 21:05:54 UTC 2019` to build gRPC and it succeeded.

**Comment by normanmaurer** [comment]
@voidzcy thanks a lot for verify the fix :)
