### ISSUE TITLE
readComplete when handlerRemoved

### ISSUE THREAD

**Issue by lifeinwild** [netty/netty#9208]
### Expected behavior
dont call fireChannelReadComplete
call fireHandlerRemoved or nothing

### Actual behavior
call fireChannelReadComplete

https://github.com/netty/netty/blob/a33200ca38990b88315a48637e5ac5da398b100d/codec/src/main/java/io/netty/handler/codec/ByteToMessageDecoder.java
line 255
>ctx.fireChannelReadComplete();

### Steps to reproduce
handler is removed in port unification
https://netty.io/4.1/xref/io/netty/example/portunification/PortUnificationServerHandler.html
>p.remove(this);

the removing handler has nothing to do with readComplete.

### Minimal yet complete reproducer code (or URL to code)
you can reproduce it anytime by removing handler.

### Netty version
4.1.31

### JVM version (e.g. `java -version`)
corretto 8

### OS version (e.g. `uname -a`)
win 10

**Comment by lifeinwild** [comment]
There are two problems.
If you make "byte[] big" smaller or remove the line of Thread.sleep (1000 * 5), you can send all the data.
Even in this case, channelReadComplete () may be called on the client side even though reception has not been completed. But eventually the client receives all the data.
If you increase "byte[] big" or put the line of Thread.sleep (1000 * 5), the client side will not receive all data.

That is, there is a problem that channelReadComplete () is called on halfway, and a problem that responding is stopped halfway.

**Comment by qeesung** [comment]
There is no `fireHandlerXXX` method in `ChannelHandlerContext`, only `fireChannelXXX` method. If you want to propagate handler Removed event, you can try `fireUserEventTriggered`.

**Comment by lifeinwild** [comment]
My understanding of channelReadComplete () may not be sufficient.

If it is a valid specification that channelReadComplete () is called when deleting a handler in port unification, close this issue.
The behavior was unexpected just for me.

**Comment by njhill** [comment]
Thanks @lifeinwild, I think you're right that it would be better for the removal not to trigger this unless the handler is mid-read. I see that @normanmaurer has opened #9211 to address it.

**Comment by normanmaurer** [comment]
Yes I did fix it... closing
