### ISSUE TITLE
kqueue channel getPeerCredentials does not return PID 

### ISSUE THREAD

**Issue by EliyahuStern** [netty/netty#9213]
Calling KQueueDomainSocketChannel#peerCredentials returns PeerCredentials with PID field not set.

The reason for that is given in the following note:
https://github.com/netty/netty/blob/ec69da9afb8388c9ff7e25b2a6bc78c9bf91fb07/transport-native-kqueue/src/main/c/netty_kqueue_bsdsocket.c#L162

but the above note is not necessarily true. It is also possible to get the peer PID using get_sock_opts with LOCAL_PEERPID (see https://stackoverflow.com/questions/38185024/check-sender-when-listening-to-unix-socket/38207320#answer-38207320%E2%80%8F).

**Comment by normanmaurer** [comment]
@EliyahuStern would you be interested to submit a pr ?

**Comment by EliyahuStern** [comment]
@normanmaurer sure, just created https://github.com/netty/netty/pull/9219
