### ISSUE TITLE
A question about allLeaks in DefaultResourceLeak

### ISSUE THREAD

**Issue by ro9er** [netty/netty#9215]
Hi community
   Recently I have gone through the code of ResourceLeakDetector and I have a question. In my opinion, the `allLeaks` set is the key to determine whether a leak exist. If the method `dispose` invoke `allLeaks.remove` before `close`, then netty will find a leak. 
  My question is, why we use a set (based on ConcurrentHashMap) to do the check, we can just use an AtomicFieldUpdate or AtomicBoolean to store the status and check leaks. The cas will have some performance advantage to `allLeaks` set.

**Comment by normanmaurer** [comment]
@ro9er please submit a pr if you think it can be improved... I will have a look :)

**Comment by ro9er** [comment]
> @ro9er please submit a pr if you think it can be improved... I will have a look :)

Ok, I have submit a pr and please have a look.
Thanks for your help and looking forward for your reply!

**Comment by normanmaurer** [comment]
As explained in the PR the `Set` is needed.... closing.
