### ISSUE TITLE
Reconsider io.netty.monitor

### ISSUE THREAD

**Issue by trustin** [netty/netty#922]
@spullara said in #65:

> I think we could compromise here and provide an implementation of Yammer Metrics that isn't required and not reinvent the wheel while at the same time making it possible to get all the stats we need. They have successfully instrumented many projects at arms-length:
> 
> http://metrics.codahale.com/manual/
> 
> If it isn't possible to do that with Netty perhaps we don't have the right level of extensibility. I know that Twitter has successfully instrumented our Netty usage (in Finagle) with Ostrich, which is similar. Perhaps that API would be a callback interface that you register?

It is unfortunate that I didn't pick up his idea on time, but it's better be late than never.

Instead of providing the monitoring API that can never beat Yammer Metrics, I think it's much better to provide proper extension points so that the monitor library instruments itself into Netty.

Therefore, I propose to:
- ditch `io.netty.monitor`,
- keep collecting the list of potentially interesting metrics,
- add proper extension points if it's not possible to get the interesting metric using public API, and
- provide a library that instruments into Netty and reports metrics via Yammer Metrics.

**Comment by stanleyyang1987** [comment]
Hi,I can not file the io.netty.monitor package in Netty 4.1. stuff.May know the reason of the change？and 
 how can I achieve the  monitor function in Netty 4?
