### ISSUE TITLE
Raw File Output using FileChannel to write inbound/outbound traffic to session files

### ISSUE THREAD

**Issue by redbrain** [netty/netty#9220]
Hi, I have used netty to rewrite all networking in a large legacy application, and just want to say i love this project so much its made everything unit-testable etc.

But i was unable to find an approach to add to my pipeline to write inbound traffic to a inbound.dat or an outbound.dat respectively just writing the raw bytes to file.

Ideally i wanted to do this:

```
@Override
    protected void setupPipeline(SocketChannel socketChannel) {
        socketChannel.pipeline()
                .addLast("feedIdleStateHandler",
                         new IdleStateHandler(0, 0, 10)
                );
        socketChannel.pipeline().addLast(new IXDecoder());
        socketChannel.pipeline().addLast(new IxMessageHeartbeatingInBoundHandler((m, c) -> {
            /// some business logic
        })
        {
            // write to recovery channel
            @Override
            protected boolean sendDownstream() {
                return true;
            }
        });
        socketChannel.pipeline().addLast(new InBoundTrafficLogger("inbound.dat", append))
        socketChannel.pipeline().addLast(new OutBoundTrafficLogger("outbound.dat", append))
```

I am happy to try and implement something akin to the log handler implementation but the only way i was able to implement this requirement was to extend ChannelInboundHandler and in the last pipeline step do a ctx.fireRead() to then get the channelread0 callback and write to a fileoutput stream. The message object i decode has a getting for the raw bytes for reference so i didnt have to do anything there but this could be something added early on in the pipeline before any decoder or logic to avoid the decoding issue to objects.

I might have been missing something really obvious so i thought i would ask here first before attempting a patch.

**Comment by normanmaurer** [comment]
@redbrain there is nothing build in into netty. Keep in mind that file IO may block so you should off-load this to another thread.
