### ISSUE TITLE
Support Setting Parent Channel for EmbeddedChannel

### ISSUE THREAD

**Issue by ryanoneill** [netty/netty#9228]
### Expected behavior

It would be beneficial for testing the effects of Netty multiplexed protocols (i.e. HTTP/2) on generic functionality if `EmbeddedChannel` had the capability for setting a parent `Channel`. There are situations where the child `Channel` and `ChannelPipeline` is processing a message, yet the desired information is actually contained within the parent `Channel` that is responsible for managing the connection (e.g. when trying to determine whether an `SslHandler` is being used on this connection). 

### Actual behavior

`EmbeddedChannel` extends `AbstractChannel` but always sets the parent `Channel` for the `AbstractChannel` constructor to 'null'.

### Netty version
4.1.35

### JVM version (e.g. `java -version`)
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

### OS version (e.g. `uname -a`)
Darwin xxxxx 17.7.0 Darwin Kernel Version 17.7.0: Wed Apr 24 21:17:24 PDT 2019; root:xnu-4570.71.45~1/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
@ryanoneill sounds good... want to do a pr ?

**Comment by ryanoneill** [comment]
Would like to, I just need to find the time. It might be a few weeks before I could do it. What do you think?

**Comment by normanmaurer** [comment]
@ryanoneill just had a few minutes and so did it... PTAL https://github.com/netty/netty/pull/9230
