### ISSUE TITLE
SSL error when server SslContext with startTls=true and handler uses ctx.writeAndFlush

### ISSUE THREAD

**Issue by violetagg** [netty/netty#9231]
This issue is related to https://github.com/reactor/reactor-netty/issues/757

### Expected behavior
When requesting the server to receive the expected content ("Hello World")

### Actual behavior
`curl: (56) LibreSSL SSL_read: error:1404C10B:SSL routines:ST_OK:wrong version number, errno 0`

When `startTls=true` for the SslContext on the server and sending response with `ctx.writeAndFlush(...)` the error above is received. When using `ctx.write(...)` and then `flush` invocation in `channelReadComplete` there is no issue.

### Minimal yet complete reproducer code (or URL to code)
The reproducible example from https://github.com/reactor/reactor-netty/issues/757

- Go to https://github.com/trevorwhitney/reactor-netty-error/blob/master/src/main/kotlin/io/pivotal/reactor/netty/experiment/HttpServerHandler.kt
Comment the `flush` invocation in `channelReadComplete ` and in `channelRead0 ` instead of `ctx.write(response)` use `ctx.writeAndFlush(response)`

- Run `./gradlew clean plain-netty`

- `curl -k https://localhost:8080/ --cacert src/main/resources/certs/exporterCA.crt --cert src/main/resources/certs/prometheus.crt --key src/main/resources/certs/prometheus.key`

### Netty version
4.1.36.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

### OS version (e.g. `uname -a`)
Darwin MacBook-Pro-8.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
Thanks will have a look.

**Comment by normanmaurer** [comment]
@violetagg why do you use STARTTLS btw ? This seems to be not right and most likely the problem. I guess the sequencing may just vary a bit in so it works "by chance"...

**Comment by trevorwhitney** [comment]
@normanmaurer you are correct that using STARTTLS was incorrect. Removing that fixes our problem. However, I'm curious about this only working in the "plain netty" implementation in the example code "by chance". Could you elaborate on that? Out of 1000 requests, the "plain netty" implementation passes 100% of the time, while the "reactor netty" implementation fails 100% of the time.

**Comment by normanmaurer** [comment]
@trevorwhitney so how starttls works in netty is that once you do the first "flush" it switches to "encrypted mode". So I suspect in netty we receive a `channelReadComplete` before `channelRead` and so we already switched to encryption mode while in project-reactor this is not the case. While there is not anything wrong with the "extra" `channelReadComplete` in the case of netty I think general speaking we should not fire it. I will have a look while we do once I have some time.

**Comment by trevorwhitney** [comment]
@normanmaurer thanks for the explanation, that clears it up!
