### ISSUE TITLE
Very high context switching of netty-3.10.6.Final

### ISSUE THREAD

**Issue by lord-i-will** [netty/netty#9232]
### Expected behavior
Low context switching.
### Actual behavior
Very high interruption and context switching.
![image](https://user-images.githubusercontent.com/14847104/59167454-ef0adb00-8b63-11e9-8840-47369bf361da.png)

### Steps to reproduce
Reference: https://stackoverflow.com/questions/56491729/big-data-transmission-flume-avro-source-netty-server-epoll-cause-lots-of-contex
### Minimal yet complete reproducer code (or URL to code)
The following code is copied from Flume AvroSource
```
channelFactory = new NioServerSocketChannelFactory(
          Executors.newCachedThreadPool(new ThreadFactoryBuilder().setNameFormat(
              "Avro " + NettyTransceiver.class.getSimpleName() + " Boss-%d").build()),
          Executors.newFixedThreadPool(20, new ThreadFactoryBuilder().setNameFormat(
              "Avro " + NettyTransceiver.class.getSimpleName() + "  I/O Worker-%d").build()));

Map<String, Object> options = new HashMap<>();
options.put("child.receiveBufferSizePredictorFactory",
    new AdaptiveReceiveBufferSizePredictorFactory(1024 * 1024,
        5 * 1024 * 1024, 10 * 1024 * 1024));// min: 1MB, init: 5MB, max: 10MB
options.put("child.receiveBufferSize", 10 * 1024 * 1024);// 10MB
ServerBootstrap bootstrap = new ServerBootstrap(channelFactory);
bootstrap.setOptions(options);
bootstrap.setPipelineFactory(new ChannelPipelineFactory() {
  @Override
  public ChannelPipeline getPipeline() throws Exception {
    ChannelPipeline p = pipelineFactory.getPipeline();
    p.addLast("frameDecoder", new NettyTransportCodec.NettyFrameDecoder());
    p.addLast("frameEncoder", new NettyTransportCodec.NettyFrameEncoder());
    if (executionHandler != null) {
      p.addLast("executionHandler", executionHandler);
    }
    p.addLast("handler", new NettyServerAvroHandler());
    return p;
  }
});
bootstrap.bind(addr);
```

### Netty version
3.10.6.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

### OS version (e.g. `uname -a`)
Linux 2.6.32-642.el6.x86_64 #1 SMP Tue May 10 17:27:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lord-i-will** [comment]
@trustin @normanmaurer Could you please have a look at my problem?

**Comment by DATuan91** [comment]
@lord-i-will Version 3.10.6 is obsolete and no longer supported by now. Moreover, version 3.x has a lot of gc and memory management issues. I think you should really consider upgrade to 4.1.x
