### ISSUE TITLE
How to init dns resolver for bootstrap?

### ISSUE THREAD

**Issue by Buffer2Disk** [netty/netty#9233]
### Expected behavior
i want customize dns server for bootstrap to resolve domain , separate from the default dns server ,then how can i init AbstractAddressResolver  for google dns 8.8.8.8?

`bootstrap.resolver(new AbstractAddressResolver<>())`
### Netty version
netty 4
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
centos 7

**Comment by qeesung** [comment]
You can specify DNS server when sending query requests:
```java 
DefaultDnsQuestion defaultDnsQuestion = new DefaultDnsQuestion("gmail.com", DnsRecordType.MX);
InetSocketAddress dnsServerAddr = new InetSocketAddress("ns1.google.com", 53);
Future<AddressedEnvelope<DnsResponse, InetSocketAddress>> future = resolver.query(dnsServerAddr, defaultDnsQuestion);

```

**Comment by Buffer2Disk** [comment]
> You can specify DNS server when sending query requests:
> 
> ```java
> DefaultDnsQuestion defaultDnsQuestion = new DefaultDnsQuestion("gmail.com", DnsRecordType.MX);
> InetSocketAddress dnsServerAddr = new InetSocketAddress("ns1.google.com", 53);
> Future<AddressedEnvelope<DnsResponse, InetSocketAddress>> future = resolver.query(dnsServerAddr, defaultDnsQuestion);
> ```
hi , i'm not quite undertand what does it mean **resolver** ?
because i want bind dns server to **Bootstrap** , so each connection can use my own dns server

**Comment by normanmaurer** [comment]
the resolver itself is only used when using connect, and so only on the client side.
