### ISSUE TITLE
Conversion from ByteBuf to byte[]  returns different length arrays for same data

### ISSUE THREAD

**Issue by ga92yup** [netty/netty#9234]
Hi, 

I am experiencing a behavior I would like to explain:
I am reading the same data from my local machine and in a network application as part of adding some code to Apache Pulsar.
The data is in ByteBuf format and needs to be converted to byte[] for further computation.
When reading the data locally, I use:
byte[] msgArray =   buf.array();
The network code is as follows:
               if(msg.hasArray()) {
                  msgArray = msg.array();
                } else {
                    int readableBytes = msg.readableBytes();
                    msgArray = new byte[readableBytes];
                    int readerIndex = msg.readerIndex();
                    msg.getBytes(readerIndex, msgArray);
                }
}
The same data locally has byte size of 259475, while in the network the size is 62290

Could you, help me understand what is happening here? 

Thank you!

Regards,

Milena

**Comment by qeesung** [comment]
I guess your server (client) didn't receive the complete data, maybe only 62290 bytes of data. Maybe you can try to assemble multiple message fragments in custom `Decoder`

**Comment by ga92yup** [comment]
Thanks a lot for your reply!

**Comment by normanmaurer** [comment]
Also be sure you take `readerIndex`, `arrayOffset` and `readableBytes` into account when acting on the backing array.
