### ISSUE TITLE
TimeoutException

### ISSUE THREAD

**Issue by ScottShen-Syd** [netty/netty#9237]
OS: Centos 7.4.1708
Java:  1.8.0_151
Netty:  4.1.36

Shouldn't that the FixedChannelPool.AcquireTimeoutAction.FAIL throws io.netty.handler.timeout.TimeoutException? However, tested it throws java.util.concurrent.TimeoutException instead

-- Test Code --
try
{
     Future< Channel > fc = fixedChannelPool.acquire().sync();
}
catch( Exception e )
{
    if( e instanceof java.util.concurrent.TimeoutException )
    {
    }
}

**Comment by normanmaurer** [comment]
This is by design... the transport jar has no dependencies on handler
