### ISSUE TITLE
How should FlowControlHandler be used?

### ISSUE THREAD

**Issue by xiaoheng1** [netty/netty#9241]
i use netty4.1.34.

I see FlowControlHandler source code. and i give a example about how to use FlowControlHandler.

```
<pre>{@code
 * ChannelPipeline pipeline = ...;
 *
 * pipeline.addLast(new HttpServerCodec());
 * pipeline.addLast(new FlowControlHandler());
 *
 * pipeline.addLast(new MyExampleHandler());
 *
 * class MyExampleHandler extends ChannelInboundHandlerAdapter {
 *   @Override
 *   public void channelRead(ChannelHandlerContext ctx, Object msg) {
 *     if (msg instanceof HttpRequest) {
 *       ctx.channel().config().setAutoRead(false);
 *
 *       // The FlowControlHandler will hold any subsequent events that
 *       // were emitted by HttpObjectDecoder until auto reading is turned
 *       // back on or Channel#read() is being called.
 *     }
 *   }
 * }
 * }</pre>
```

However, I found that when ctx.channel().config().setAutoRead(false) is called, the channel cancels the OP_READ event, then msg will not be stored in the FlowControlHandler's queue. Therefore, the queue property in FlowControlHandler is useful ?

In my opinion, the channel should not cancel the OP_READ event, and msg will be stored in the queue property in the FlowControlHandler.

**Comment by qeesung** [comment]
You should explicitly call `ctx.read()` to read data. Ensures that only one message per `read()` is sent downstream

**Comment by xiaoheng1** [comment]
@qeesung I understand what you mean, by the way, what is the role of the queue in FlowControlHandler?

**Comment by normanmaurer** [comment]
@xiaoheng1 if you call `read()` you may receive multiple `channelRead(...)` invocations. This `queue` helps to ensure you only receive one per `read()` call.
