### ISSUE TITLE
[Feature] Flutter compability?

### ISSUE THREAD

**Issue by Fernthedev** [netty/netty#9246]
Not really an issue, but would there be any support or ways to use Flutter client with a netty server. If not, then what would you suggest would be the best way for a developer to accomplish this. I've already tried using protobuf but with netty's implementation of protobuf it adds extra bytes which I don't know how to interpret in dart (The extra bytes show how long the protobuf message is). Currently I am using dart's socket system and netty's protobuf system. Is this feature even realistically possible for the netty team to implement or is it something that developers should implement themselves with things such as protobuf?

**Comment by normanmaurer** [comment]
I think you would need to write your own decoder / encoder for this.
