### ISSUE TITLE
PooledByteBufAllocator doesn't decrease usedDirectMemory upon ByteBuf release

### ISSUE THREAD

**Issue by shevah** [netty/netty#9253]
Consider 

```
private static void test1(){
    PooledByteBufAllocator alloc = new PooledByteBufAllocator(true, 1, 1, 8192, 11, 0, 0, 0);
    ByteBuf b = alloc.buffer(3000000, 3000000);
    b.release();
    System.out.println("test1 usedDirectMemory:" + alloc.metric().usedDirectMemory()); //test1 usedDirectMemory:0
}
private static void test2(){
     PooledByteBufAllocator alloc = new PooledByteBufAllocator(true, 1, 1, 8192, 11, 0, 0, 0);
     ByteBuf b = alloc.buffer(1000000, 1000000);
     b.release();
     System.out.println("test2 usedDirectMemory:" + alloc.metric().usedDirectMemory()); //test2 usedDirectMemory:16777216
}
```

Why is `usedDirectMemory` changes in the first test but not in the second one?

### Minimal yet complete reproducer code (or URL to code)
[netty-usedDirectMemoty](https://github.com/shevah/netty-usedDirectMemoty)

### Netty version
4.1.36

**Comment by normanmaurer** [comment]
I suspect the first allocation is too big to be pooled and so is allocated as a "unpooled" buffer and so once you released it will return the direct memory to the system directly. The second is small enough to end up in the pool itself and so will remain there and no be freed.
