### ISSUE TITLE
Why class AbstractReferenceCountedByteBuf in Netty-4.1.34 use even refCnt?

### ISSUE THREAD

**Issue by shallowinggg** [netty/netty#9255]
When I see Netty-4.1.34 source code, I find that class AbstractReferenceCountedByteBuf's field *refCnt* use even number, but in previous version, it's not, what's the benefit to do this?

    // even => "real" refcount is (refCnt >>> 1); odd => "real" refcount is 0
    private volatile int refCnt = 2;

    // get real refCnt
    private static int realRefCnt(int rawCnt) {
        return (rawCnt & 1) != 0 ? 0 : rawCnt >>> 1;
    }

    private ByteBuf retain0(final int increment) {
        // all changes to the raw count are 2x the "real" change
        int adjustedIncrement = increment << 1; // overflow OK here
        int oldRef = refCntUpdater.getAndAdd(this, adjustedIncrement);
        if ((oldRef & 1) != 0) {
            throw new IllegalReferenceCountException(0, increment);
        }
        // don't pass 0!
        if ((oldRef <= 0 && oldRef + adjustedIncrement >= 0)
                || (oldRef >= 0 && oldRef + adjustedIncrement < oldRef)) {
            // overflow case
            refCntUpdater.getAndAdd(this, -adjustedIncrement);
            throw new IllegalReferenceCountException(realRefCnt(oldRef), increment);
        }
        return this;
    }

**Comment by njhill** [comment]
@shallowinggg this is part of an internal optimization to reduce concurrent ref counting overhead while ensuring that that the count can only reach zero once. You should not notice any difference if using the public methods.

**Comment by shallowinggg** [comment]
> @shallowinggg this is part of an internal optimization to reduce concurrent ref counting overhead while ensuring that that the count can only reach zero once. You should not notice any difference if using the public methods.

@njhill I know what you say, and I want to know what is the principle of this optimization too, please explain how it works. Thank you!

**Comment by single-wolf** [comment]
In previous version it do all operation in while(CAS) loop and that is work correctly
`retain() compareAndSet(this, refCnt, refCnt + 1)`
`release() compareAndSet(this, refCnt, refCnt - 1)`
then its modified at 83a19d565064ee36998eb94f946e5a4264001065 though i dont think thats more efficient XD. that cause some issues #8563 and now even&odd is solution
