### ISSUE TITLE
Advice for configuration with high rate of small messages

### ISSUE THREAD

**Issue by benitocm** [netty/netty#9261]
We have developed a service running in a virtual linux box (3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux, 8 vcpus 16 GBytes)  with Java 8 , Spring Boot 2.1.5 using Reactor, Reactor and Netty (4.1.36.Final.jar) . The service exposes a websocket end-point where the clients devices send a high rate of websocket small messages  (around 40 bytes per message). Those messages are forwarded with a small processing via websockets to another external system.
The systems has a lot of network io.  Next, I have added some information about the Netty configuration that is provided at startup time by the service with debug log. Would it be possible to somebody check if there is a big error in those values that prevent to obtain a good performance?
Thanks in advance.

-Dio.netty.noUnsafe: false
Java version: 8
sun.misc.Unsafe.theUnsafe: available
sun.misc.Unsafe.copyMemory: available
java.nio.Buffer.address: available
direct buffer constructor: available
java.nio.Bits.unaligned: available, true
jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
java.nio.DirectByteBuffer.<init>(long, int): available
sun.misc.Unsafe: available
-Dio.netty.tmpdir: /tmp (java.io.tmpdir)
-Dio.netty.bitMode: 64 (sun.arch.data.model)
-Dio.netty.maxDirectMemory: 9663676416 bytes
-Dio.netty.uninitializedArrayAllocationThreshold: -1
java.nio.ByteBuffer.cleaner(): available
-Dio.netty.noPreferDirect: false
[http] resources will use the default LoopResources: DefaultLoopResources {prefix=reactor-http, daemon=true, selectCount=8, workerCount=8}
[http] resources will use the default ConnectionProvider: PooledConnectionProvider {name=http, poolFactory=reactor.netty.resources.ConnectionProvider$$Lambda$196/1415157681@4cf4d528}
-Djava.net.preferIPv4Stack: true
-Djava.net.preferIPv6Addresses: false
Loopback interface: lo (lo, 127.0.0.1)
/proc/sys/net/core/somaxconn: 1024
-Dio.netty.native.deleteLibAfterLoading: true
-Dio.netty.native.tryPatchShadedId: true
Successfully loaded the library /opt/xxxxxx/libnetty_transport_native_epoll_x86_646088280200333694474.so
Default Epoll support : true
Default KQueue support : false
-Dio.netty.eventLoopThreads: 16
-Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
-Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
org.jctools-core.MpscChunkedArrayQueue: available
-Dio.netty.processId: 866 (auto-detected)
-Dio.netty.machineId: 00:50:56:ff:fe:8c:67:24 (auto-detected)
-Dio.netty.leakDetection.level: simple
-Dio.netty.leakDetection.targetRecords: 4
-Dio.netty.allocator.numHeapArenas: 16
-Dio.netty.allocator.numDirectArenas: 16
-Dio.netty.allocator.pageSize: 8192
-Dio.netty.allocator.maxOrder: 11
-Dio.netty.allocator.chunkSize: 16777216
-Dio.netty.allocator.tinyCacheSize: 512
-Dio.netty.allocator.smallCacheSize: 256
-Dio.netty.allocator.normalCacheSize: 64
-Dio.netty.allocator.maxCachedBufferCapacity: 32768
-Dio.netty.allocator.cacheTrimInterval: 8192
-Dio.netty.allocator.cacheTrimIntervalMillis: 0
-Dio.netty.allocator.useCacheForAllThreads: true
-Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
-Dio.netty.allocator.type: pooled
-Dio.netty.threadLocalDirectBufferSize: 0
-Dio.netty.maxThreadLocalCharBufferSize: 16384

**Comment by normanmaurer** [comment]
There is not way to give an guidance without know more about the system... Also you may want to attach a profiler etc. In general if all the messages are small you may also want to experiment with `TCP_NO_DELAY` settings.

**Comment by benitocm** [comment]
Hi,

What we have seen is that under load we have around 40% system CPU and 40% user CPU and we are wondering if we can do something at netty configuration side. What information would you need to be able to provide some guidance?

Thanks

**Comment by normanmaurer** [comment]
well a cpu profiler snapshot for example... that said even with this I dont know enough about your exact workload pattern most likely.
