### ISSUE TITLE
readCharSequence(0) is inconsistent

### ISSUE THREAD

**Issue by hban** [netty/netty#9271]
`readCharSequence(0, charset)` returns different results for `EmptyByteBuf` than for other types of buffers.

### Expected behavior

`readCharSequence(0, charset)` to always return empty string.

### Actual behavior

```
Unpooled.buffer().readCharSequence(0, StandardCharsets.UTF_8) => ""
Unpooled.EMPTY_BUFFER.readCharSequence(0, StandardCharsets.UTF_8) => null
```

### Netty version

4.1.36

**Comment by normanmaurer** [comment]
@hban thanks a lot that is a bug...

**Comment by normanmaurer** [comment]
@hban thanks for reporting... Fix https://github.com/netty/netty/pull/9272
