### ISSUE TITLE
Does netty support open a connection with prior knowledge?

### ISSUE THREAD

**Issue by Trenson** [netty/netty#9283]
### Expected behavior
Netty support open a connection with prior knowledge, for the server is Rust-h2, which handshake by  prior knowledge.
### Actual behavior
Server is Rust-h2, which handshake by  prior knowledge. But my client is written by java-netty, my client can't handshake with the server.

**Comment by normanmaurer** [comment]
@Trenson do you are talking about client side ?

**Comment by Trenson** [comment]
> @Trenson do you are talking about client side ?

Yes, client side.

**Comment by normanmaurer** [comment]
@Trenson I am confused... Basically it should do this as soon as you add the Http2ConnectionHandler to the pipeline and the channel becomes active. What is the problem ?

**Comment by normanmaurer** [comment]
I will close this for now... @Trenson please re-open if you have more questions.
