### ISSUE TITLE
About FastThreadLocal Cache line padding ????

### ISSUE THREAD

**Issue by jiangxinlingdu** [netty/netty#9284]
// Cache line padding (must be public)
    // With CompressedOops enabled, an instance of this class should occupy at least 128 bytes.
    public long rp1, rp2, rp3, rp4, rp5, rp6, rp7, rp8, rp9;

why use 9 nums long  
![TIM图片20190626155119](https://user-images.githubusercontent.com/6373972/60161478-44b0da00-982a-11e9-9b20-11b8c2838cec.png)

**Comment by johnou** [comment]
@jiangxinlingdu what's the problem?

**Comment by jiangxinlingdu** [comment]
why use  public long rp1, rp2, rp3, rp4, rp5, rp6, rp7, rp8, rp9;  not
public long rp1, rp2, rp3, rp4, rp5, rp6, rp7, rp8;  

I figured out why I figured out 136.  not 128  why not To remove a long？？？？？

**Comment by franz1981** [comment]
@jiangxinlingdu  you can use https://plugins.jetbrains.com/plugin/10953-jol-java-object-layout and check it out how it is the layout with your case too :+1:

**Comment by jiangxinlingdu** [comment]
> @jiangxinlingdu you can use https://plugins.jetbrains.com/plugin/10953-jol-java-object-layout and check it out how it is the layout with your case too



I'll try

**Comment by franz1981** [comment]
@jiangxinlingdu @johnou I see other issues instead: if the purpose of the padding was to protect from false sharing the internal fields `InternalThreadLocalMap`from the rest of the heap it won't work without COOPS and 64 bit JDK ie

With COOPS 64 bit, 8 bytes aligned:
```io.netty.util.internal.InternalThreadLocalMap object internals:
 OFFSET  SIZE                                               TYPE DESCRIPTION                                                    VALUE
      0    12                                                    (object header)                                                N/A
     12     4                                                int UnpaddedInternalThreadLocalMap.futureListenerStackDepth        N/A
     16     4                                                int UnpaddedInternalThreadLocalMap.localChannelReaderStackDepth    N/A
     20     4                                           Object[] UnpaddedInternalThreadLocalMap.indexedVariables                N/A
     24     4                             Map<Class<?>, Boolean> UnpaddedInternalThreadLocalMap.handlerSharableCache            N/A
     28     4                                      IntegerHolder UnpaddedInternalThreadLocalMap.counterHashCode                 N/A
     32     4                                  ThreadLocalRandom UnpaddedInternalThreadLocalMap.random                          N/A
     36     4                Map<Class<?>, TypeParameterMatcher> UnpaddedInternalThreadLocalMap.typeParameterMatcherGetCache    N/A
     40     4   Map<Class<?>, Map<String, TypeParameterMatcher>> UnpaddedInternalThreadLocalMap.typeParameterMatcherFindCache   N/A
     44     4                                      StringBuilder UnpaddedInternalThreadLocalMap.stringBuilder                   N/A
     48     4                       Map<Charset, CharsetEncoder> UnpaddedInternalThreadLocalMap.charsetEncoderCache             N/A
     52     4                       Map<Charset, CharsetDecoder> UnpaddedInternalThreadLocalMap.charsetDecoderCache             N/A
     56     4                                  ArrayList<Object> UnpaddedInternalThreadLocalMap.arrayList                       N/A
     60     4                                             BitSet InternalThreadLocalMap.cleanerFlags                            N/A
     64     8                                               long InternalThreadLocalMap.rp1                                     N/A
     72     8                                               long InternalThreadLocalMap.rp2                                     N/A
     80     8                                               long InternalThreadLocalMap.rp3                                     N/A
     88     8                                               long InternalThreadLocalMap.rp4                                     N/A
     96     8                                               long InternalThreadLocalMap.rp5                                     N/A
    104     8                                               long InternalThreadLocalMap.rp6                                     N/A
    112     8                                               long InternalThreadLocalMap.rp7                                     N/A
    120     8                                               long InternalThreadLocalMap.rp8                                     N/A
    128     8                                               long InternalThreadLocalMap.rp9                                     N/A
Instance size: 136 bytes
Space losses: 0 bytes internal + 0 bytes external = 0 bytes total
```
Without CCOPS 64 bit, 8 bytes aligned:
```io.netty.util.internal.InternalThreadLocalMap object internals:
 OFFSET  SIZE                                               TYPE DESCRIPTION                                                    VALUE
      0    16                                                    (object header)                                                N/A
     16     4                                                int UnpaddedInternalThreadLocalMap.futureListenerStackDepth        N/A
     20     4                                                int UnpaddedInternalThreadLocalMap.localChannelReaderStackDepth    N/A
     24     8                                           Object[] UnpaddedInternalThreadLocalMap.indexedVariables                N/A
     32     8                             Map<Class<?>, Boolean> UnpaddedInternalThreadLocalMap.handlerSharableCache            N/A
     40     8                                      IntegerHolder UnpaddedInternalThreadLocalMap.counterHashCode                 N/A
     48     8                                  ThreadLocalRandom UnpaddedInternalThreadLocalMap.random                          N/A
     56     8                Map<Class<?>, TypeParameterMatcher> UnpaddedInternalThreadLocalMap.typeParameterMatcherGetCache    N/A
     64     8   Map<Class<?>, Map<String, TypeParameterMatcher>> UnpaddedInternalThreadLocalMap.typeParameterMatcherFindCache   N/A
     72     8                                      StringBuilder UnpaddedInternalThreadLocalMap.stringBuilder                   N/A
     80     8                       Map<Charset, CharsetEncoder> UnpaddedInternalThreadLocalMap.charsetEncoderCache             N/A
     88     8                       Map<Charset, CharsetDecoder> UnpaddedInternalThreadLocalMap.charsetDecoderCache             N/A
     96     8                                  ArrayList<Object> UnpaddedInternalThreadLocalMap.arrayList                       N/A
    104     8                                               long InternalThreadLocalMap.rp1                                     N/A
    112     8                                               long InternalThreadLocalMap.rp2                                     N/A
    120     8                                               long InternalThreadLocalMap.rp3                                     N/A
    128     8                                               long InternalThreadLocalMap.rp4                                     N/A
    136     8                                               long InternalThreadLocalMap.rp5                                     N/A
    144     8                                               long InternalThreadLocalMap.rp6                                     N/A
    152     8                                               long InternalThreadLocalMap.rp7                                     N/A
    160     8                                               long InternalThreadLocalMap.rp8                                     N/A
    168     8                                               long InternalThreadLocalMap.rp9                                     N/A
    176     8                                             BitSet InternalThreadLocalMap.cleanerFlags                            N/A
Instance size: 184 bytes
Space losses: 0 bytes internal + 0 bytes external = 0 bytes total
```
In the latter case `cleanerFlags` is likely to sugger false sharing if surrounding regions of the heap are being modified.
The solution would be to move `private BitSet cleanerFlags;` into `UnpaddedInternalThreadLocalMap` to protect it.
@jiangxinlingdu 
I see your point: yes, probably just 8 `long` would have been enough: TBH, according to the `adiacent lilne prefetch` optimization of Intel CPU (for Core and Netburst archs) it is not enough too.
We would need at least 128 bytes of padding, but that's another story.

**Comment by normanmaurer** [comment]
@franz1981 want to do a PR to fix all of this ?

**Comment by franz1981** [comment]
@normanmaurer Sure bud: let me take some time to figure it out the original purpose and real effects of the padding too (maybe searching on the original PR that has introduced it) :+1:

**Comment by jiangxinlingdu** [comment]
@franz1981  
Your meaning  all Cache line padding  additional additions are required 8 bytes

**Comment by jiangxinlingdu** [comment]
> @franz1981
> Your meaning all Cache line padding additional additions are required 8 bytes

cache line size is 64 meaning Instance size: 72 bytes

cache line size is 128meaning Instance size: 136 bytes

**Comment by franz1981** [comment]
@jiangxinlingdu 

> Your meaning all Cache line padding additional additions are required 8 bytes

Exactly, to be 100% no false sharing could happen...but the point is it worths?
That's what I want to now: having + 128 bytes (due to padding) on each thread local instance is not a small footprint...so I would like to be sure that it wasn't a premature optimization (maybe not)

**Comment by zl7261** [comment]
https://tech.meituan.com/2016/11/18/disruptor.html if you can read chinese.

This code for compute optimize for memory sharing.

In java,the Long type is 8 bytes, but when you load a Long data, your cpu(x64) will load 64 bytes as minium data,cpu's cache has min unit as 64 bytes in x64 cpu.

In many time,you can ignore it,cause it's not a bug.

**Comment by jiangxinlingdu** [comment]
@zl7261 I have read，but why use public long rp1, rp2, rp3, rp4, rp5, rp6, rp7, rp8, rp9; not
public long rp1, rp2, rp3, rp4, rp5, rp6, rp7, rp8;

I figured out why I figured out 136. not 128 why not To remove a long？？？？？

**Comment by zl7261** [comment]
> @zl7261 I have read，but why use public long rp1, rp2, rp3, rp4, rp5, rp6, rp7, rp8, rp9; not
> public long rp1, rp2, rp3, rp4, rp5, rp6, rp7, rp8;
> 
> I figured out why I figured out 136. not 128 why not To remove a long？？？？？

Sorry,I don't see your issue detail at first.
This code also make me comfused.
Waiting for netty's official answer.

**Comment by johnou** [comment]
If I had to guess the class was probably refactored and the padding wasn't recalculated.

**Comment by jiangxinlingdu** [comment]
> If I had to guess the class was probably refactored and the padding wasn't recalculated.

sure？？？ It would be great if that were true, but is it?

**Comment by hilaryfrank** [comment]
I have checked the code in old version and found that the size of InternalThreadLocalMap is 128Bytes in version 4.0.33. And now in latest code in github the size of InternalThreadLocalMap is 136. And the reason is that some has added two parameters: cleanerFlags (in class InternalThreadLocalMap) and arrayList (in parent class UnpaddedInternalThreadLocalMap).
In my view, the contributors has pushed the two parameters ignoring the Cache line padding. So it is a problem!

**Comment by franz1981** [comment]
@hilaryfrank I've already commented about it on https://github.com/netty/netty/issues/9284#issuecomment-505776892

> In my view, the contributors has pushed the two parameters ignoring the Cache line padding. So it is a problem!

The thing is: why the padding was needed? And why only on one side? :)

**Comment by jiangxinlingdu** [comment]
> I have checked the code in old version and found that the size of InternalThreadLocalMap is 128Bytes in version 4.0.33. And now in latest code in github the size of InternalThreadLocalMap is 136. And the reason is that some has added two parameters: cleanerFlags (in class InternalThreadLocalMap) and arrayList (in parent class UnpaddedInternalThreadLocalMap).
> In my view, the contributors has pushed the two parameters ignoring the Cache line padding. So it is a problem!

My doubt is solved by you, thank you!!!

**Comment by normanmaurer** [comment]
@franz1981 yep... I am not even sure it is needed at all. I would need to see a benchmark that it really matters at all. If we need padding then we should have it on both sides.

**Comment by jiangxinlingdu** [comment]
> @franz1981 yep... I am not even sure it is needed at all. I would need to see a benchmark that it really matters at all. If we need padding then we should have it on both sides.

Waiting for netty's official answer.

**Comment by franz1981** [comment]
@normanmaurer Totally agree...the thing is that such bench is not simplebecause we need to be sure to have some "noisy neighbours" around the padded instance and that GC won't move things all around...

**Comment by jiangxinlingdu** [comment]
> @normanmaurer Totally agree...the thing is that such bench is not simple because we need to be sure to have some "noisy neighbours" around the padded instance and that GC won't move things all around...

why should have it on both sides and why not only on one side??????

**Comment by jiangxinlingdu** [comment]
@franz1981  I see somedemo use on one side. 

why should have it on both sides and why not only on one side??????

**Comment by franz1981** [comment]
@jiangxinlingdu 

> why should have it on both sides and why not only on one side??????

That's a secret.....
Just joking...the reason is strictly related to the motivation of the original padding.
The padding usually is needed to avoid false sharing (please search over google what it is ;) )
and the Java heap in a real production system is filled of many instances (and not only...!)
that could mutate, invalidating the cache lines where the thread local map fields are sitting, causing
additional cache misses when accessed. You *could* need on both side because you would like to protect fields from both sides no?
That's the short answer!

**Comment by jiangxinlingdu** [comment]
@franz1981   thanks！！！

**Comment by jiangxinlingdu** [comment]
@franz1981 in cause a instance has attribute : 
long p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16 

when access p6 attribute the cache line  is begin from p6 p7 …………………… 
or p6 in middle ,the cache line is begin from p4 p5 p6 p7………………

how to understand ？？？？

**Comment by franz1981** [comment]
@jiangxinlingdu you won't know :)
It depends on the alignment of the instance: if the instance is alligend to cache line boundaries, you can exactly know which fields is falling is which cache line, but given that we don't know (AFAIK java instances are being alligned to 16/8 bytes boundaries) you need to compute the padding by assuming the worst case scenario.

**Comment by jiangxinlingdu** [comment]
@franz1981  3Q

**Comment by tzy123321** [comment]
so cool

**Comment by medusar** [comment]
So.. is there any update for this issue?

**Comment by coderlongren** [comment]
good

**Comment by yessimida** [comment]
cool
