### ISSUE TITLE
SSLContextBuilder should accept Iterable parameters too

### ISSUE THREAD

**Issue by anuraaga** [netty/netty#9293]
### Expected behavior

It is possible to pass parameters like SSL providers to `SslContextBuilder` without having to convert iterables to arrays, which is tedious.

### Actual behavior

Need to convert to arrays, except for the `ciphers` method.

Wanted to run this by everyone - if the API change makes sense I'd be happy to send a PR. Accepting `Iterable` would make the class easier to use and also make it more consistent.

/cc @trustin

**Comment by normanmaurer** [comment]
@anuraaga this sounds like a good idea... I think we may also want to support varargs ... Maybe you want to provide an PR ?

**Comment by normanmaurer** [comment]
@anuraaga interested in doing a pr ?

**Comment by anuraaga** [comment]
Yup - sorry for the delay have had some stuff lately but will be able to get to this by next week.

**Comment by normanmaurer** [comment]
@anuraaga are you still interested ?
