### ISSUE TITLE
Proposal: Decrease ChannelHandlerAdapter memory footprint by removing "boolean added" field

### ISSUE THREAD

**Issue by doom369** [netty/netty#9294]
Motivation:

`ChannelHandlerAdapter.added` field is used only to detect the duplicate handler within the pipeline when handler is added. This is actually "nice to have" check, but not a must and it has a  price.
Our pipelines in average have ~25 handlers. Holding this field brings additional ~100-200 bytes (depends on JVM) of the memory overhead per pipeline.

Solution 1:

The simplest solution would be just to iterate through existing handlers and check for identity. However, it could bring additional CPU cost during pipeline construction. In general, this shouldn't be a big problem as users don't add handlers often (just assumption).

Solution 2:

Hold the state about identity within the pipeline. In that case, state will bring the same memory overhead or even more, but it could be avoided through system property. So, it could be turned on test environments and turned off on the productions.

WDYT?

**Comment by qeesung** [comment]
`ChannelHandlerAdapter.added` is used to avoid adding a non-shared handler instance to multiple pipelines, and each handler instance should have an `added` filed to detect whether it has been added or not.

Solution 1:
If there are many channel connections, or pipelines, traversing handlers can cause serious performance problems.

Solution 2:
I don't quite understand this solution. How do we save state in pipeline?

**Comment by doom369** [comment]
>  is used to avoid adding a non-shared handler instance to multiple pipelines, and each handler instance should have an added filed to detect whether it has been added or not.

Exactly, that's why it doesn't worth the overhead. Especially, for static pipelines.

> If there are many channel connections, or pipelines, traversing handlers can cause serious performance problems.

I would say, it depends on pipeline usage.

> I don't quite understand this solution. How do we save state in pipeline?

```
if (duplicateCheckIsEnabled) {
  if (identityHashMap.containsKey(handler)) {
     throw
  } else {
     identityHashMap.put(handler);
  }
}
```

**Comment by normanmaurer** [comment]
@doom369 this will only work if `identityHashMap` is static and shared across threads or made ThreadLocal so it will work at some point... 

Honestly I think there are others things that or more important / provide more value in 4.x. For master we can revisit this of course.

**Comment by normanmaurer** [comment]
also you should check with JOL if it really saves anything. We may just be lucky and have it padded the right way.

**Comment by doom369** [comment]
I checked with JOL before the ticket.
Ok, I close for now, still think this should be handled with property in order to avoid unnecessary overhead.

**Comment by njhill** [comment]
Just for reference, we had some related discussion here: https://github.com/netty/netty/pull/8957#discussion_r267496330
