### ISSUE TITLE
ByteBufUtil.prettyHexDump may have a problem when calculating the initial capacity of StringBuilder

### ISSUE THREAD

**Issue by xiaoheng1** [netty/netty#9301]
i use netty4.1.34

source code in netty4.1.34

```
private static String prettyHexDump(ByteBuf buffer, int offset, int length) {
            if (length == 0) {
              return StringUtil.EMPTY_STRING;
            } else {
                int rows = length / 16 + (length % 15 == 0? 0 : 1) + 4;
                StringBuilder buf = new StringBuilder(rows * 80);
                appendPrettyHexDump(buf, buffer, offset, length);
                return buf.toString();
            }
        }
```

in my opinion, rows = length / 16 + (length & 15 == 0? 0 : 1) + 4;

if  int rows = length / 16 + (length % 15 == 0? 0 : 1) + 4;
when length = 0 or length = 15, length % 15 always 0，this is wrong.

**Comment by qeesung** [comment]
This should be an issue. The way to find the remainder is either `length % 16` or `length & 15`. `length & 15` performs better.

**Comment by xiaoheng1** [comment]
@qeesung yes，i think so.

**Comment by normanmaurer** [comment]
PR welcome

**Comment by xiaoheng1** [comment]
@normanmaurer Ok, I will submit a PR.

**Comment by franz1981** [comment]
@qeesung 
> length & 15 performs better.

I'm not that sure: last time I've checked length % 16, the JIT, given that 16 is constant, is able to perform the same optimization you'll perform by hand. Please check the assembly or perform a benchmark to be sure of it

**Comment by qeesung** [comment]
@franz1981 I will check it more deeply. :-)

**Comment by SplotyCode** [comment]
I am pretty sure that HashMap uses &. As the HashMap is very optimized I think & might be faster

**Comment by qeesung** [comment]
> I am pretty sure that HashMap uses &. As the HashMap is very optimized I think & might be faster

I found the code in the JDK7 source code
https://github.com/openjdk-mirror/jdk7u-jdk/blob/f4d80957e89a19a29bb9f9807d2a28351ed7f7df/src/share/classes/java/util/HashMap.java#L272-L277

**Comment by SplotyCode** [comment]
Maby they also used this method because length may not be constant?

**Comment by franz1981** [comment]
@SplotyCode @qeesung The JVM doesn't trust final (non static) fields unless for specific internal java util (invoke) classes ie length cannot be assumed (from the JIR) as constant on both `ArrayDeque` and `IdentityHashMap` or other impls need to use the "clever" mask bit-trick. 
`prettyHexDump` is hardcoding as constant 16 so this kind of trick is not needed and should be avoided as "premature" optimization unless there are strong proof that the JVM has failed to optimize it.
