### ISSUE TITLE
ByteBufInputStream.read() may have a problem

### ISSUE THREAD

**Issue by xiaoheng1** [netty/netty#9305]
i use netty4.1.34

souce code:

```
public int read() throws IOException {
        if (!buffer.isReadable()) {
            return -1;
        }
        return buffer.readByte() & 0xff;
    }
```
In my opinion, the buffer.isReadable() method should not be used here to judge, but the available() method should be used. Because ByteBufInputStream is passed in length when constructing, so if the buffer.isReadable() method is used here If judged, it may exceed the limit of length, which is unreasonable.

**Comment by normanmaurer** [comment]
@xiaoheng1 good point... are you willing to open a PR ?

**Comment by xiaoheng1** [comment]
@normanmaurer I am glad to，i will open a PR.

**Comment by xiaoheng1** [comment]
#

**Comment by xiaoheng1** [comment]
#Fix public int read() throws IOException method exceeds the limit of length

**Comment by xiaoheng1** [comment]
#9306 Fix public int read() throws IOException method exceeds the limit of length
