### ISSUE TITLE
Set the number of receiving threads to 2, but only one seems to be working

### ISSUE THREAD

**Issue by brucelwl** [netty/netty#9309]
Set the number of receiving threads to 2, but only one seems to be working. Maybe I didn't understand the principle. Please give me some advice.

**Comment by qeesung** [comment]
Could you please provide code that can reproduce?

**Comment by brucelwl** [comment]
@qeesung  How do I make sure that both threads set up here are working? I found that only one thread is working through source debugging
![image](https://user-images.githubusercontent.com/13413715/60397009-df871c80-9b7a-11e9-9dbb-bebf2b5b260e.png)

**Comment by qeesung** [comment]
Although it's not clear what your purpose is, if you want all threads of `acceptGroup` to be running, you can register multiple channels into `acceptGroup`. Like the following:

```java
bootstrap.bind(port1).sync();
bootstrap.bind(port2).sync();
bootstrap.bind(port3).sync();
```

**Comment by brucelwl** [comment]
@qeesung I want two threads to listen for client connections at the same time and use the same port. But your example needs to open multiple ports. One of netty's threading models is that there are multiple receiving threads and multiple working threads.

**Comment by normanmaurer** [comment]
If you only call bind one time it will only use one thread to accept connections as there is only one ServerChannel. That said the accepted connections will be distributed across the threads. If you want to accept with multiple threads on the same port you need to use SO_REUSEADDR and call bind multiple times

**Comment by brucelwl** [comment]
@normanmaurer I set up reuse as you said and called bind () twice, but there may be two problems, one of which is that serverchannel is closed, and the other is that the port is being used.
![image](https://user-images.githubusercontent.com/13413715/60399723-9abfad80-9b9b-11e9-9efc-58ed94a7846f.png)
![image](https://user-images.githubusercontent.com/13413715/60399727-b3c85e80-9b9b-11e9-8cbf-29b0f6ccd06c.png)

**Comment by normanmaurer** [comment]
This only works with the native wool transport

**Comment by brucelwl** [comment]
@normanmaurer 
That is to say, if i use NioEventLoopGroup or EpollEventLoopGruop, the receiving thread can only use one. Multithreading does not work, does it?

**Comment by qeesung** [comment]
@brucelwl After you enable SO_REUSEADDR option, you should specify the IP address when binding, otherwise, address conflict exception will be thrown.
Like the following:

```java
serverBootstrap.bind("192.168.1.100", 8080).sync();
serverBootstrap.bind("127.0.0.1", 8080).sync();
```
Use the following command to check the connection in the `LISTEN` state
```bash
# netstat -plnt | grep 8088                                                                                          
tcp6       0      0 127.0.0.1:8088          :::*                    LISTEN      115825/java
tcp6       0      0 192.168.1.100:8088      :::*                    LISTEN      115825/java
```

**Comment by brucelwl** [comment]
@qeesung This is not a good solution. My case is to open two threads. If I open n threads, I need to set n IP addresses on the same machine.

**Comment by qeesung** [comment]
as @normanmaurer  said, this should not work in netty

**Comment by brucelwl** [comment]
@qeesung So how to understand netty's multi-threaded receiving connection, multi-threaded read-write threading model
