### ISSUE TITLE
RuleBasedIpFilter can not work correctly when remoteAddress is not in IpFilterRule.

### ISSUE THREAD

**Issue by bright60** [netty/netty#9313]

**Comment by bright60** [comment]
I find out about RuleBasedIpFilter API only works correctly when remoteAddress is in IpFilterRule, if remoteAddress is not in IpFilterRule, it always returns true, this means the connection will be accepted by default. Should we change the last statement to return false?

The following code snippets are from RuleBasedIpFilter.

    @Override
    protected boolean accept(ChannelHandlerContext ctx, InetSocketAddress remoteAddress) throws Exception {
        for (IpFilterRule rule : rules) {
            if (rule == null) {
                break;
            }

            if (rule.matches(remoteAddress)) {
                return rule.ruleType() == IpFilterRuleType.ACCEPT;
            }
        }
       
        // Should we change this line to return false when remoteAddress is not in IpFilterRule？
        return true;
    }

**Comment by qeesung** [comment]
As javadoc said: If no rules are provided, all connections will be accepted. 
If you want to customize the filter logic, you can inherit `RuleBasedIpFilter` or `AbstractRemoteAddressFilter` and override the `accept` method.

**Comment by bright60** [comment]
yes, that's the what I did. However the logic of filter is misleading in RuleBasedIpFilter.

**Comment by normanmaurer** [comment]
@bright60 like @qeesung said it is documented exactly like this in the javadocs. We can not just change it as it would break other peoples code.
