### ISSUE TITLE
netty-codec-http WebSocketFrameAggregator bug

### ISSUE THREAD

**Issue by stone99** [netty/netty#9315]
![image](https://user-images.githubusercontent.com/8908278/60562297-948f2400-9d89-11e9-8f6f-433f089aaefc.png)

multi frames aggregate in one frame。 cannot get the correct data。

**Comment by qeesung** [comment]
How does your client send messages? Could you please provide code that can be reproduced?

**Comment by stone99** [comment]
sorry, I can't provide the code. The client was written by c/c++ and does not send the unreadable sigin，this can be added by netty-codec-http.this bug happens when the network is unstable. I guess the aggregator does not work correctly. hope this can help you.

> How does your client send messages? Could you please provide code that can be reproduced?

**Comment by normanmaurer** [comment]
@stone99 sorry but without more informations its impossible to help

**Comment by normanmaurer** [comment]
Closing as the reporter did not provide more infos. Please re-open with more infos
