### ISSUE TITLE
Do I need to call Bytebuf.release() when using ProtobufVarint32LengthFieldPrepender

### ISSUE THREAD

**Issue by nichoding** [netty/netty#9325]
### Netty version 
4.1.37
### JVM version (e.g. `java -version`)
openjdk version "1.8.0_171"
### OS version (e.g. `uname -a`)
GNU/Linux

Today I upgraded the version of netty from 4.0 to 4.1. 
The following prompt appears in the console:
LEAK: ByteBuf.release() was not called before it's garbage-collected...
After reviewing the documentation, I learned that I need to manually call release() to release the reference-counted object.
Do I need to call Bytebuf.release() when using ProtobufVarint32LengthFieldPrepender 
for encoding message?I found that this release method is not called in this class.
BTW,I did not call release()  when I used 4.0, and there was no leak in the past year.I don't know why...
Thanks!

**Comment by normanmaurer** [comment]
Please show the full log

**Comment by nichoding** [comment]
@normanmaurer 
FYI.
 2019-07-04 17:02:55.831 ERROR [client-netty-worker-17-thread-3][io.netty.util.ResourceLeakDetector]- LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:349)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:139)
	io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	java.lang.Thread.run(Thread.java:748)

**Comment by nichoding** [comment]
@normanmaurer 
public void initChannel(SocketChannel ch) {
							ch.pipeline().addLast(new IdleStateHandler(60L, 0, 0, TimeUnit.SECONDS));
							ch.pipeline().addLast(new ClientIdleStateTrigger());
							ch.pipeline().addLast(new ProtobufVarint32FrameDecoder());
							ch.pipeline().addLast(new ProtobufVarint32LengthFieldPrepender());
							ch.pipeline().addLast(new ClientTcpSocketServerHandler());
						}

**Comment by nichoding** [comment]
The reason why I upgraded the version is because there is a connection leak when using 4.0. There are some features, such as "too many open files" , CLOSE_WAIT states. I also saw some people in the forum asking similar questions. Some of the answers are upgraded versions. Does 4.0 really have this problem?

**Comment by normanmaurer** [comment]
Well 4.0 is EOL but I know people use it in prod without problems. 

From the log you are posted it looks more like you missed to call release in your `ClientTcpSocketServerHandler`

**Comment by nichoding** [comment]
@normanmaurer 
Thanks,
I have called release when Inbound，do I need call release when Outbound.
I know netty framework will release if I do not use ProtobufVarint32LengthFieldPrepender.
What about using ProtobufVarint32LengthFieldPrepender?I nocited that this release method is not called in this class.

**Comment by normanmaurer** [comment]
no you should not need to call release for outbound as long as you pass the object.

**Comment by nichoding** [comment]
protected void encode(ChannelHandlerContext ctx, ByteBuf msg, ByteBuf out)
			throws Exception {
		int bodyLen = msg.readableBytes();
		int headerLen = computeRawVarint32Size(bodyLen);
		out.ensureWritable(headerLen + bodyLen);
		writeRawVarint32(out, bodyLen);
		out.writeBytes(msg, msg.readerIndex(), bodyLen);
	}
These are code of ProtobufVarint32LengthFieldPrepender. I noticed that it passes object 'out' on  without releasing object 'msg'.This does not match the documentation.
https://netty.io/wiki/reference-counted-objects.html#wiki-h3-8
------
Outbound messages
Unlike inbound messages, outbound messages are created by your application, and it is the responsibility of Netty to release these after writing them out to the wire. However, the handlers that intercept your write requests should make sure to release any intermediary objects properly. (e.g. encoders)
------

**Comment by normanmaurer** [comment]
@nichoding look at the base class of it ... it handles the releasing.

**Comment by nichoding** [comment]
Aha.Got it,thanks a lot!!! @normanmaurer

**Comment by nichoding** [comment]
BTW, does 4.0 really have the connection leak problem...
