### ISSUE TITLE
what is HashedWheelTimer waitForNextTick function  mean?

### ISSUE THREAD

**Issue by opver** [netty/netty#9327]
in  waitForNextTick  function of HashedWheelTimer class, what is following code mean:

final long currentTime = System.nanoTime() - startTime;
                long sleepTimeMs = (deadline - currentTime + 999999) / 1000000;

                if (sleepTimeMs <= 0) {
                   if (currentTime == Long.MIN_VALUE) {
                        return -Long.MAX_VALUE;
                    } else {
                        return currentTime;
                    }
                }

**Comment by normanmaurer** [comment]
I think it is very well explained here:

https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/HashedWheelTimer.java#L552

Basically `MIN_VALUE` has a special meaning so we need to convert it if it happens to be `currentTime`
