### ISSUE TITLE
Can we change the global index(UnpaddedInternalThreadLocalMap.nextIndex) to thread scope in FastThreadLocal?

### ISSUE THREAD

**Issue by hilaryfrank** [netty/netty#9328]
@coinary1 ah ok... yeah its an optimisation as this allows us to ensure we never have a clash without doing any heavy locking etc.

_Originally posted by @normanmaurer in https://github.com/netty/netty/issues/8271#issuecomment-419892698_

As it was discussed in the issue 8271（above）, the InternalThreadLocalMap will waste memory(space).
But I have a question. Why don't we change the global index(UnpaddedInternalThreadLocalMap.nextIndex) to thread scope.
In this case , every InternalThreadLocalMap instance has an individual nextIndex. That means every thread has an individual nextIndex. That will make sure every FastThreadLocal instance has a unique index in a thread and InternalThreadLocalMap.indexedVariables doesn't waste space., moreover we don't need to use heavy lock.
Can we do like this?

**Comment by normanmaurer** [comment]
@hilaryfrank please open a PR with the code changes you suggest. It is hard for me to follow your thoughts here.
