### ISSUE TITLE
HttpRequestDecoder writes automatically

### ISSUE THREAD

**Issue by WhiteTrashLord** [netty/netty#9334]
I am using Netty 4.1.37.Final.
My pipeline looks like this:
	 p.addLast("decoder", new HttpRequestDecoder());
    	 p.addLast("encoder", new HttpResponseEncoder());

Auto_Read is set to false. 
I noticed that the ChannelInboundHandler will read objects like LastHttpContent and DefaultHttpContent automatically even before I call a new read on the channel.
Is this behaviour intended or a bug?

**Comment by normanmaurer** [comment]
@WhiteTrashLord yes that is expected... one `ctx.read()` may produce more then one element as of today.
