### ISSUE TITLE
ChannelFuture vs Multiple Handlers

### ISSUE THREAD

**Issue by kawang108** [netty/netty#9341]
Hi netty community,

I'm building a man-in-the-middle http proxy where the proxy accepts a client's SSL connection and then creates a separate SSL connection with the server. I don't want to start reading & forwarding the data from client to server until the two connections are successfully established.

Currently I have a single handler that executes a series of 3 steps: accept client's TCP connection by returning a 200, conduct 2-way SSL handshake with the client, connect to server over SSL. 

Each of these steps returns a ChannelFuture (e.g., sslHandler.handshakeFuture() returns a future). Because these steps have to be executed and completed in sequence, I'm chaining the 3 ChannelFutures inside **one handler** by adding a listener to the future and inside the listener I would fetch the next step to execute. The idea is like this in expanded form (actual code is recursive):

`acceptClientConnectionFuture.addListener(f -> {`
`  if (f.isSuccess()) {`
`    handshakeWithClientFuture = handshakeWithClient();`
`     handshkeWithClientFuture.addListener(f -> {`
`         if (f.isSuccess()) {`
`            connectToServerFuture = connectToServer();`
`             connectToServerFuture.addListener(......);`
`         `}
`     }`
`  }`
`}`

In theory, this is all async. However, I have been wondering if this works in harmony with Netty's eventloop. The worker threads are going to work on these futures, right? If so, will it impact the proxy's ability of processing more requests at a high QPS?

Another option is to put each step into its own handler, and only continue when the future completes:
acceptClientHandler -> handshakeWithClientHandler -> connectToServerHandler

A third option is to have these 3 steps running in a separate threadpool.

Which design choice is the best? Or is there a better design outside of these 3 options?

### Netty version
4.1.36

**Comment by normanmaurer** [comment]
I think what you describe is what I would do... Just ensure that both connections are using the same EventLoop to reduce latency introduced by hopping between threads.

**Comment by kawang108** [comment]
@normanmaurer thanks for much for your response!
