### ISSUE TITLE
java.lang.ClassCastException: io.netty.buffer.PooledUnsafeDirectByteBuf cannot be cast to [Ljava.lang.Object;

### ISSUE THREAD

**Issue by cmadsen** [netty/netty#9342]
### Expected behavior
The following test runs with out errors. The test case works using e.g. netty 4.0.25.

### Actual behavior
Test fails with:

```
java.lang.ClassCastException: io.netty.buffer.PooledUnsafeDirectByteBuf cannot be cast to [Ljava.lang.Object;
Exception in thread "main" java.lang.ClassCastException: io.netty.buffer.PooledUnsafeDirectByteBuf cannot be cast to [Ljava.lang.Object;
```

### Steps to reproduce
Run the test case.

### Minimal yet complete reproducer code (or URL to code)

```java
	@Test
	public void test() {
		try {
			EmbeddedChannel channel = new EmbeddedChannel(new StringEncoder(),
					new StringDecoder());
			channel.writeOutbound("HELLO WORLD");
			channel.writeInbound(channel.readOutbound());
			String s = (String) channel.readInbound();
			assertThat(s).contains("HELLO WORLD");
		} catch (Exception e) {
			e.printStackTrace();
			throw e;
		}
	}
```

### Netty version
4.1.37

### JVM version (e.g. `java -version`)
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

### OS version (e.g. `uname -a`)
Linux localhost.localdomain 5.0.16-100.fc28.x86_64

**Comment by amizurov** [comment]
I think on JAVA 1.7 compiler target it will be work and looks like: `channel.writeInbound(new Object[]{channel.readOutbound()});`, but on JAVA 1.8 this is replaced to: `channel.writeInbound((Object[])channel.readOutbound());`

**Comment by cmadsen** [comment]
So is this expected behaviour, ie just switching from netty 4.0.25 to 4.1.37 will result in a java.lang.ClassCastException: io.netty.buffer.PooledUnsafeDirectByteBuf in the above test case?

**Comment by normanmaurer** [comment]
@cmadsen unfortunately yes ...
