### ISSUE TITLE
Epoll question: Why level-triggered?

### ISSUE THREAD

**Issue by njhill** [netty/netty#9349]
I was wondering what the reason is for supporting/exposing level-triggered mode in the epoll transport? As far as I understand, ET versus LT is somewhat of an implementation choice/detail that's beneath the existing netty abstractions, evidenced by the fact that epoll is interchangeable with the java NIO transport.

I found some references to certain features not supported in ET mode, such as auto-read (I guess outdated) and maxMessagePerRead, but can't think why it shouldn't be possible to make such features work. I also can't think of cases where ET wouldn't be preferable performance-wise.

Any explanation/insight would be appreciated!

If LT really isn't needed (I know that's a big if, there's likely something I've overlooked), maybe we could consider simplifying the implementation to be ET only?

**Comment by njhill** [comment]
@normanmaurer looking back at #3346, it sounds like the original reason for introducing LT was that "a messagesPerRead limit can not be enforced correctly, as we need to consume everything from the channel when notified", but is that really the case? I don't follow why using ET implies we need to consume everything (or is it possible that was a prior misconception)?

Digging some more I saw that the splice functionality requires LT mode, I wonder might it be possible to make that work with ET too? This doesn't necessarily say much but the unit tests still pass when using ET mode with the the mode parameter validation commented out.

**Comment by normanmaurer** [comment]
@njhill I think in general there is really no need anymore to support LT. All should work also with ET. That said I think we can not just remove it from 4.1 but can for master.

**Comment by njhill** [comment]
Thanks @normanmaurer
> I think we can not just remove it from 4.1

Are you sure? :) isn't it more an implementation detail tied to how we handle notifications internally and so shouldn't affect the semantics from users' pov? I.e. I'm not sure it even makes sense to say that it's "supported" or not since it's not a visible feature as such. Of course the config option would remain but we could just document the fact that was now obsolete and does not have any effect.

I just feel the code would be much simpler and more robust without it.

**Comment by normanmaurer** [comment]
@njhill that's fair enough... I guess at the end we could just have the user set it and do nothing ;)

**Comment by normanmaurer** [comment]
@njhill lets do it for the master branch... you are fancy to do a PR ?

**Comment by njhill** [comment]
@normanmaurer I'd be happy to though can't promise an ETA... already have a few things on my netty list like porting #9470 to master. So if you want to do it sooner I won't mind at all. I still think it would be nice/feasible to do in 4.1 too :)

**Comment by normanmaurer** [comment]
This was fixed
