### ISSUE TITLE
java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)

### ISSUE THREAD

**Issue by merryhe1990** [netty/netty#9355]
### Expected behavior
work well

### Actual behavior

Appeared after about 12 hours of running on Android 7.0,it work well on android 6.0,After quitting the application, it still can't work, and the system restart can work normally.

### Minimal yet complete reproducer code (or URL to code)
client code:
       if (!isConnect) {
                isConnecting = true;
                group = new NioEventLoopGroup();
                StringEncoder = new StringEncoder(CharsetUtil.UTF_8);
                lineBasedFrameDecoder = new LineBasedFrameDecoder(1024);
                stringDecoder = new StringDecoder(CharsetUtil.UTF_8);
                nettyClientHandler = new NettyClientHandler(listener);
                channelInitializer = new ChannelInitializer<SocketChannel>() { // 5
                    @Override
                    public void initChannel(SocketChannel ch) throws Exception {
                        ch.pipeline().addLast("ping", new IdleStateHandler(0, 5, 0, TimeUnit.SECONDS));//5s未发送数据，回调userEventTriggered
                        ch.pipeline().addLast(StringEncoder);
                        ch.pipeline().addLast(lineBasedFrameDecoder);//黏包处理
                        ch.pipeline().addLast(stringDecoder);
                        ch.pipeline().addLast(nettyClientHandler);
                    }
                };

                bootstrap = new Bootstrap().group(group)
                        .option(ChannelOption.TCP_NODELAY, true)//屏蔽Nagle算法试图
                        .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, CONNECT_TIMEOUT_MILLIS)
                        .channel(NioSocketChannel.class)
                        .handler(channelInitializer);

                try {
                    String ip = GlobalDataManager.getInstance().getConfig().getStringValue(IConfigField.LOCALIP);
                    Trace.i(TAG, "conn remote ip=" + ip);
                    channelFuture = bootstrap.connect(ip, tcp_port).addListener((ChannelFutureListener) channelFuture1 -> {
                        if (channelFuture1.isSuccess()) {
                            Trace.e(TAG, "连接成功");
                            isConnect = true;
                            channel = channelFuture1.channel();
                        } else {
                            Trace.e(TAG, "连接失败");
                            isConnect = false;
                        }
                        isConnecting = false;
                    }).sync();

                    // Wait until the connection is closed.
                    channelFuture.channel().closeFuture().sync();
                    Trace.e(TAG, " 断开连接");
                } catch (Exception e) {
                    e.printStackTrace();
                    Trace.i(TAG, "netty client err=" + e.getMessage());
                } finally {
                    isConnect = false;
                    listener.onServiceStatusConnectChanged(NettyListener.STATUS_CONNECT_CLOSED);
                    if (null != channelFuture) {
                        if (channelFuture.channel() != null && channelFuture.channel().isOpen()) {
                            channelFuture.channel().close();
                        }
                        channelFuture = null;
                    }
                    channel = null;
                    group.shutdownGracefully();
                    group = null;
                    bootstrap = null;
                    channelInitializer = null;
                    reconnect();
                }
            }
server code:

        bossGroup = new NioEventLoopGroup(1);
        workerGroup = new NioEventLoopGroup();
        try {
            b = new ServerBootstrap();
            inetSocketAddress  = new InetSocketAddress(port);

            channelInitializer =  new ChannelInitializer<SocketChannel>() {

                @Override
                public void initChannel(SocketChannel ch) throws Exception {
                    Trace.i(TAG,"initChannel ch:" + ch);
                    stringEncoder = new StringEncoder(CharsetUtil.UTF_8);
                    lineBasedFrameDecoder =  new LineBasedFrameDecoder(1024);
                    stringDecoder = new StringDecoder(CharsetUtil.UTF_8);
                    echoServerHandler = new EchoServerHandler(listener);

                    ch.pipeline().addLast(stringEncoder);
                    ch.pipeline().addLast(lineBasedFrameDecoder);
                    ch.pipeline().addLast(stringDecoder);
                    ch.pipeline().addLast(echoServerHandler);
                }
            };

            b.group(bossGroup, workerGroup)
                    .channel(NioServerSocketChannel.class)
                    .localAddress(inetSocketAddress)
                    .childOption(ChannelOption.SO_KEEPALIVE, true)
                    .childOption(ChannelOption.SO_REUSEADDR, true)
                    .childOption(ChannelOption.TCP_NODELAY, true)
                    .childHandler(channelInitializer);

            // Bind and start to accept incoming connections.
            ChannelFuture f = b.bind().sync(); // 8

            Trace.i(TAG, EchoServer.class.getName() + " started and listen on " + f.channel().localAddress());
            isServerStart = true;
            listener.onStartServer();
            // Wait until the server socket is closed.
            f.channel().closeFuture().sync();
        } catch (Exception e) {
            Trace.e(TAG, "connection ="+e.getLocalizedMessage());
            e.printStackTrace();
        } finally {
            isServerStart = false;
            listener.onStopServer();
            workerGroup.shutdownGracefully();
            bossGroup.shutdownGracefully();
            b = null;
            inetSocketAddress =null;
            reconnect();
        }
### Netty version
netty-all-4.1.23.Final.jar
### JVM version (e.g. `java -version`)
java -1.8
### OS version (e.g. `uname -a`)
Android 7.0

**Comment by normanmaurer** [comment]
This version of Netty is super old... please upgrade and report back
