### ISSUE TITLE
How to use both SSL and protobuf.

### ISSUE THREAD

**Issue by gogym** [netty/netty#9371]
How to use both SSL and protobuf. If you use SSL with protobuf. Unable to decode.
error:
io.netty.handler.codec.DecoderException: com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.

ask for help

`@Override
	public void initChannel(SocketChannel ch) throws Exception {
		ChannelPipeline pipeline = ch.pipeline();

		SslHandler sslHandler = SSLContextFactory.getSslHandler();
		if (sslHandler != null) {
			 pipeline.addLast("ssl",sslHandler);
		}

		
		ExtensionRegistry registry = ExtensionRegistry
				.newInstance();
		MessageClass.registerAllExtensions(registry);
		
		// ----配置Protobuf处理器----
		// 用于decode前解决半包和粘包问题（利用包头中的包含数组长度来识别半包粘包）
		pipeline.addLast("frameDecoder", new ProtobufVarint32FrameDecoder());
		// 配置Protobuf解码处理器，消息接收到了就会自动解码，ProtobufDecoder是netty自带的，Message是自己定义的Protobuf类
		pipeline.addLast("protobufDecoder",
				new ProtobufDecoder(Message.getDefaultInstance(),registry));

		// 用于在序列化的字节数组前加上一个简单的包头，只包含序列化的字节长度。
		pipeline.addLast("frameEncoder",
				new ProtobufVarint32LengthFieldPrepender());
		// 配置Protobuf编码器，发送的消息会先经过编码
		pipeline.addLast("protobufEncoder", new ProtobufEncoder());

		// ----Protobuf处理器END----
		

		// 心跳起搏器
		pipeline.addLast(new IdleStateHandler(120, 0, 0, TimeUnit.SECONDS));
		// 心跳检测
		pipeline.addLast(new HeartBeatServerHandler());
		// ip过滤
		// pipeline.addLast(new RuleBasedIpFilter(new IpFilterRuleHandler()));
		pipeline.addLast(new ConnectManageHandler());
		pipeline.addLast(new ChatServerHandler());

	}`

### Netty version
4.1.36.final
### JVM version (e.g. `java -version`)
jdk8

**Comment by gogym** [comment]
Is there anyone who can help me?

**Comment by normanmaurer** [comment]
imho it should just work... can you share a full reproducer ?

**Comment by gogym** [comment]
> imho it should just work... can you share a full reproducer ?
The problem has been solved. Thank you.

**Comment by gogym** [comment]
@normanmaurer The problem has been solved. Thank you.
