### ISSUE TITLE
Where is the memory of direct buffer allocated by netty, kernel space or user space?

### ISSUE THREAD

**Issue by zonghaishang** [netty/netty#9373]

**Comment by franz1981** [comment]
If/when Netty allocates off-heap memory it relies on the system allocator, so it is like calling malloc/new on it. I don't understand what do you mean with user/kernel? Is the usual operating system virtual memory machinery.

**Comment by zonghaishang** [comment]
@franz1981 I want to know if the direct memory is in the kernel buffer.
I read this article： https://www.linuxjournal.com/article/6345?page=0,0

**Comment by franz1981** [comment]
>  if the direct memory is in the kernel buffer

Is always user space AFAIK

**Comment by normanmaurer** [comment]
as @franz1981  said
