### ISSUE TITLE
NullPointerException in AbstractHttp2StreamChannel

### ISSUE THREAD

**Issue by bryce-anderson** [netty/netty#9375]
### Expected behavior
No NPE's

### Actual behavior
NPE's

### Netty version
4.1.37-Final.

I don't have a clean repro for this, it's showing up in tests that I'm running to upgrade Netty in finagle. A representitive stack trace looks like this:
```
285 2019-07-16 11:01:39,967 ERR Caught Throwable from listener onStreamClosed.
 286 java.lang.NullPointerException: null
 287         at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.doBeginRead(AbstractHttp2StreamChannel.java:786)
 288         at io.netty.handler.codec.http2.AbstractHttp2StreamChannel.streamClosed(AbstractHttp2StreamChannel.java:277)
 289         at io.netty.handler.codec.http2.Http2MultiplexCodec.onHttp2StreamStateChanged(Http2MultiplexCodec.java:195)
 290         at io.netty.handler.codec.http2.Http2FrameCodec$ConnectionListener.onStreamClosed(Http2FrameCodec.java:459)
 291         at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:356)
 292         at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.removeFromActiveStreams(DefaultHttp2Connection.java:1000)
 293         at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.deactivate(DefaultHttp2Connection.java:956)
 294         at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:512)
 295         at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:518)
 296         at io.netty.handler.codec.http2.Http2ConnectionHandler.closeStream(Http2ConnectionHandler.java:605)
```
I suspect that we're getting a `close` call triggered by a `doRead` and that is causing the `inboundBuffer` field to be `null` just in time for the `.poll()` call.

**Comment by normanmaurer** [comment]
@bryce-anderson yeah this sounds plausible... I guess we should just add an extra null check. Want to do a PR ?

**Comment by normanmaurer** [comment]
@bryce-anderson also what version you upgrade from ?

**Comment by bryce-anderson** [comment]
4.1.25-Final.

**Comment by normanmaurer** [comment]
@bryce-anderson ok that is quite a step :)

**Comment by bryce-anderson** [comment]
I'm sorry, 4.1.35-Final. (I'll correct above)

**Comment by normanmaurer** [comment]
interesting... I didn't expect any changes here that could cause this... Can you try to upgrade one release at a time to understand where this regression happened.

**Comment by bryce-anderson** [comment]
Sure, I can take a swing at it. There was a regression in 4.1.36 that made us skip that upgrade but it was related to H2 session shutdown behavior so I think we can see if this NPE surfaces without worrying about it.

**Comment by normanmaurer** [comment]
@bryce-anderson thanks a lot... keep me posted.

**Comment by bryce-anderson** [comment]
Seems to have been introduced between 4.1.36 and 4.1.37. Likely this phab: https://github.com/netty/netty/commit/307efbe49c6c71664250e06200123c0ae3e1ec4a#diff-8c9a7d1d9b0fdb6c5aef2794d05a9f88

Before the split we never null'ed out `inboundBuffer`, after it was moved to AbstractHttp2StreamChannel we null out `inboundBuffer` on close.

**Comment by normanmaurer** [comment]
@bryce-anderson doh... want to provide a fix ?

**Comment by bryce-anderson** [comment]
Np.

**Comment by normanmaurer** [comment]
@bryce-anderson  np == yes ;) ? If not I will have a look.

**Comment by bryce-anderson** [comment]
I'll take it. I hope to have something up this afternoon.
