### ISSUE TITLE
Netty on Android: DnsNameResolverTimeoutException

### ISSUE THREAD

**Issue by netty-issue** [netty/netty#9376]
### Expected behavior
When running the following code in an AsyncTask on Android, a DnsNameResolverTimeoutException is thrown. However when I run it on a desktop Java VM, it works fine.

        EventLoopGroup group = new NioEventLoopGroup();
        try {
            DnsNameResolver resolver = new DnsNameResolverBuilder(group.next())
                    .channelType(NioDatagramChannel.class)
                    .nameServerProvider(
                            new SingletonDnsServerAddressStreamProvider(
                                    new InetSocketAddress(req.nameserver, 53)))
                    .build();
            try {

                Future<AddressedEnvelope<DnsResponse,
                        InetSocketAddress>> future2 =
                        resolver.query(new DefaultDnsQuestion(
                                req.host, req.dnsRecordType));
                AddressedEnvelope<DnsResponse, 
                        InetSocketAddress> ae =
                        future2.syncUninterruptibly().getNow();
            // ... more code that is never reached ...
            } finally {
                resolver.close();
            }
        } finally {                                                                              
            group.shutdownGracefully();
        }

The request class:

    public static class DnsLookupRequest {
        String host = "google.com";
        String nameserver = "8.8.8.8";
        DnsRecordType dnsRecordType = DnsRecordType.ANY;
    }

The Exception is: "DnsNameResolverTimeoutException: [/8.8.8.8:53] query timed out after 5000 milliseconds"

What is causing this exception and how to fix it?

### Netty version
4.1.36
### JVM version (e.g. `java -version`)
Android 7.0 (24) / Desktop: Oracle JDK1.8.0_152

**Comment by normanmaurer** [comment]
I am not an android expert... This means that you did not receive a dns response within 5000 ms... Is it even allowed to use UDP on android to random servers ?

**Comment by normanmaurer** [comment]
No response from the reporter... let me close it
