### ISSUE TITLE
Netty direct memory never shrink after growing bigger

### ISSUE THREAD

**Issue by medusar** [netty/netty#9381]
### Expected behavior

Netty direct memory usage shrink after no connection was established.

### Actual behavior

Direct memory usage is still high after connections are released.

### Steps to reproduce

Log out `PooledByteBufAllocator.DEFAULT.metric()`  every 15 seconds.  Establish some connections and send and receive a few data. Check the log.

After a few hours, the log still shows that direct memory is used.
![image](https://user-images.githubusercontent.com/10563859/61345891-7e08c280-a889-11e9-8010-145b1dbfc4ed.png)

### Minimal yet complete reproducer code (or URL to code)
Not yet.
### Netty version
4.1.35.Final
### JVM version (e.g. `java -version`)
```
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
```
It also occurs in java 8. 
### OS version (e.g. `uname -a`)
```
Linux  5.1.14-1.el7.elrepo.x86_64 #1 SMP Sat Jun 22 08:30:29 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by normanmaurer** [comment]
That may be alright... memory is pooled and released after some time. If you don't want to use the pool as you care more about memory usage you can use `UnpooledByteBufAllocator`.
