### ISSUE TITLE
netty-codec-stomp server and client for stomp.js example

### ISSUE THREAD

**Issue by llm163520** [netty/netty#9383]
### Steps to reproduce
server: stomp codec
ChannelPipeline pipeline = ch.pipeline();
pipeline.addLast("decoder", new StompSubframeDecoder());
pipeline.addLast("encoder", new StompSubframeEncoder());
pipeline.addLast("aggregator", new StompSubframeAggregator(65536));
pipeline.addLast("handler", new StompServerHandler());
client: stomp.js,html
var stompClient = Stomp.client("ws://127.0.0.1:8083");
stompClient.connect({userName: "张三", userId: "test1"}, function(frame) {
       console.error("连接成功");
});

### Minimal yet complete reproducer code (or URL to code)
stomp codec
### Netty version
4.1.37

### JVM version (e.g. `java -version`)
1.8

### OS version (e.g. `uname -a`)
w10

**Comment by llm163520** [comment]
![1563345998(1)](https://user-images.githubusercontent.com/22343834/61354029-c03efd80-a8a3-11e9-93fa-5bbbd8c2e5f3.jpg)

**Comment by llm163520** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>并发测试连接数</title>
</head>
<body>
<div>当前并发个数为: <span id="successnum">0</span></div>
<div>当前错误个数为: <span id="errornum">0</span></div>
<div id="allUser">

</div>
<script src="sockjs.min.js"></script>
<script src="stomp.min.js"></script>
<script type="text/javascript">
    var successnum = 0, errornum = 0;
    //new WebSocket("ws://127.0.0.1:8083/");
	//setInterval(function () {
		//var socket = new SockJS("http://127.0.0.1:8083/stomp");
		//var stompClient = Stomp.over(socket);
		//var stompClient = Stomp.client("ws://10.154.70.54:61614");
		//var socket = new SockJS("ws://127.0.0.1:61616/stomp");
		
		//var stompClient = Stomp.client("ws://127.0.0.1:8083/chat");
		//var stompClient = Stomp.client("ws://127.0.0.1:61614/stomp");
		var stompClient = Stomp.client("ws://127.0.0.1:8083");
		stompClient.connect({userName: "张三", userId: "test1"}, function(frame) {
			console.log('Connected:' + frame);
			stompClient.subscribe('/topic/todoTask/open', function(response) {

			});
			successnum++;
			document.getElementById("successnum").innerText=successnum;
		}, function(error){
			//console.error(arguments);
			console.error("连接失败！", error);
			errornum++;
			document.getElementById("errornum").innerText=errornum;
		});
		
	//}, 100);
</script>
</body>
</html>

**Comment by amizurov** [comment]
Hi llm163520, please add before stomp decoder/ encoder `WebSocketServerProtocolHandler`

**Comment by llm163520** [comment]
Hi @amizurov 

Thansk you!

add before and after stomp decoder/ encoder WebSocketServerProtocolHandler try, But it didn't solve!

.childHandler(new ChannelInitializer<NioSocketChannel>() {
                    @Override
                    protected void initChannel(NioSocketChannel ch) throws Exception {
                        ChannelPipeline pipeline = ch.pipeline();
                        pipeline.addLast("decoder", new StompSubframeDecoder());
                        pipeline.addLast("encoder", new StompSubframeEncoder());
                        pipeline.addLast(new WebSocketServerProtocolHandler("/chat", null, true, 10485760));
                        pipeline.addLast("aggregator", new StompSubframeAggregator(65536));
                        pipeline.addLast("handler", new StompServerHandler());
                    }
                });

Can help provide a complete server and client example

**Comment by amizurov** [comment]
First of all you need set you primary transport (e.t. websocket) after that you configure sub protocol (e.t. stomp) but this is only codec without any logic that you need to implement.
This is simple example:
   ```
/**
 * @author Andrey Mizurov
 * @since 19.07.2019
 */
public class WebSocketStompServer {

    public static void main(String[] args) throws Exception {

        ServerBootstrap bootstrap = new ServerBootstrap()
            .group(new NioEventLoopGroup())
            .channel(NioServerSocketChannel.class)
            .childHandler(new ChannelInitializer<SocketChannel>() {

                @Override
                protected void initChannel(SocketChannel channel) {
                    channel.pipeline()
                        .addLast(new HttpServerCodec())
                        .addLast(new HttpObjectAggregator(64 * 1024))
                        .addLast(new WebSocketServerProtocolHandler("/ws"))
                        .addLast(new StompSubProtocolInitializer());
                }
            });

        ChannelFuture chf = bootstrap.bind(8080);
        chf.addListener(future -> {
            if (future.isSuccess()) {
                System.out.println("Server started !!!");
            } else {
                System.out.println("Cannot start server, follows exception " + future.cause());
            }
        }).channel().closeFuture().sync();

    }
    
    static class StompSubProtocolInitializer extends SimpleChannelInboundHandler<WebSocketFrame> {

        @Override
        public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
            if (evt instanceof HandshakeComplete) {
                String ctxName = ctx.name();
                ctx.pipeline()
                    .addAfter(ctxName, "stompHandler", new StompHandler())
                    .addAfter(ctxName, "stompAggregator", new StompSubframeAggregator(65536))
                    .addAfter(ctxName, "stompEncoder", new StompSubframeEncoder())
                    .addAfter(ctxName, "stompDecoder", new StompSubframeDecoder());
            } else {
                super.userEventTriggered(ctx, evt);
            }
        }

        @Override
        protected void channelRead0(ChannelHandlerContext ctx, WebSocketFrame webSocketFrame) {
            if (webSocketFrame instanceof TextWebSocketFrame || webSocketFrame instanceof BinaryWebSocketFrame) {
                ctx.fireChannelRead(webSocketFrame.content().retain());
            }
        }

    }

    static class StompHandler extends SimpleChannelInboundHandler<StompFrame> {

        @Override
        protected void channelRead0(ChannelHandlerContext channelHandlerContext, StompFrame stompFrame) {
            // Stomp handling
            System.out.println("Received frame: " + stompFrame.toString());
        }
    }

}
```

**Comment by acai420** [comment]
hi @llm163520 , Has this issue's problem been solved?

**Comment by llm163520** [comment]
No, I replaced the components;
vertx

**Comment by amizurov** [comment]
@acai420 @llm163520 Guys a `netty-codec-stomp` is not implementation of STOMP server it just codec that allow you to decode/encode stomp frames.

**Comment by acai420** [comment]
OK，thinks all

**Comment by llm163520** [comment]
> @llm163520 First of all you need set you primary transport (e.t. websocket) after that you configure sub protocol (e.t. stomp) but this is only codec without any logic that you need to implement.
> This is simple example:
> 
> ```
> /**
> * @author Andrey Mizurov
> * @since 19.07.2019
> */
> public class WebSocketStompServer {
> 
>  public static void main(String[] args) throws Exception {
> 
>      ServerBootstrap bootstrap = new ServerBootstrap()
>          .group(new NioEventLoopGroup())
>          .channel(NioServerSocketChannel.class)
>          .childHandler(new ChannelInitializer<SocketChannel>() {
> 
>              @Override
>              protected void initChannel(SocketChannel channel) {
>                  channel.pipeline()
>                      .addLast(new HttpServerCodec())
>                      .addLast(new HttpObjectAggregator(64 * 1024))
>                      .addLast(new WebSocketServerProtocolHandler("/ws"))
>                      .addLast(new StompSubProtocolInitializer());
>              }
>          });
> 
>      ChannelFuture chf = bootstrap.bind(8080);
>      chf.addListener(future -> {
>          if (future.isSuccess()) {
>              System.out.println("Server started !!!");
>          } else {
>              System.out.println("Cannot start server, follows exception " + future.cause());
>          }
>      }).channel().closeFuture().sync();
> 
>  }
>  
>  static class StompSubProtocolInitializer extends SimpleChannelInboundHandler<WebSocketFrame> {
> 
>      @Override
>      public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
>          if (evt instanceof HandshakeComplete) {
>              String ctxName = ctx.name();
>              ctx.pipeline()
>                  .addAfter(ctxName, "stompHandler", new StompHandler())
>                  .addAfter(ctxName, "stompAggregator", new StompSubframeAggregator(65536))
>                  .addAfter(ctxName, "stompEncoder", new StompSubframeEncoder())
>                  .addAfter(ctxName, "stompDecoder", new StompSubframeDecoder());
>          } else {
>              super.userEventTriggered(ctx, evt);
>          }
>      }
> 
>      @Override
>      protected void channelRead0(ChannelHandlerContext ctx, WebSocketFrame webSocketFrame) {
>          if (webSocketFrame instanceof TextWebSocketFrame || webSocketFrame instanceof BinaryWebSocketFrame) {
>              ctx.fireChannelRead(webSocketFrame.content().retain());
>          }
>      }
> 
>  }
> 
>  static class StompHandler extends SimpleChannelInboundHandler<StompFrame> {
> 
>      @Override
>      protected void channelRead0(ChannelHandlerContext channelHandlerContext, StompFrame stompFrame) {
>          // Stomp handling
>          System.out.println("Received frame: " + stompFrame.toString());
>      }
>  }
> 
> }
> ```
for error:
![image](https://user-images.githubusercontent.com/22343834/77815296-94dc0600-70f4-11ea-81a9-25c715e477e9.png)

javascript plugins by stomp.js
javascript connection example
var stompClient = Stomp.client("ws://127.0.0.1:8083/ws");
            stompClient.connect('admin', '123456', function(frame){
                
                console.log('Connected:' + frame);
               
            }, function(){
                       console.log('error:');
            }, '/');

**Comment by llm163520** [comment]
Server sample error still exists

**Comment by amizurov** [comment]
Hi, in my example was not defined `subProtocols` I added "v11.stomp". 
```
...
 .addLast(new WebSocketServerProtocolHandler("/ws", "v11.stomp"))
...
```
I checked this via https://raw.githubusercontent.com/jmesnil/stomp-websocket/master/lib/stomp.js.

@normanmaurer WDYT, do we need additional example `STOMP Over WebSocket` (e.g. chat) ?

**Comment by normanmaurer** [comment]
@amizurov PRs welcome

**Comment by amizurov** [comment]
> @amizurov PRs welcome

OK, maybe it can be useful for people who want to use STOMP and Netty on server side.

**Comment by llm163520** [comment]
The problem has already been solved, thanks!

**Comment by llm163520** [comment]
An exception is thrown when the client connects to the server and responds
![image](https://user-images.githubusercontent.com/22343834/77853200-66a21780-7215-11ea-95de-a929c5e1de29.png)
![image](https://user-images.githubusercontent.com/22343834/77853193-5db14600-7215-11ea-922c-960c35862bc1.png)

**Comment by llm163520** [comment]
code files
https://github.com/stomp-js/stompjs
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>WebSocket</title>
</head>
<body onload="disconnect()">
    <noscript>
        <h2 style="color:#ff0000">貌似你的浏览器不支持websocket</h2>
    </noscript>
    <div>
        <div>
            <button id="connect" onclick="connect()">connect</button>
            <button id="disconnect"  onclick="disconnect();">disconnect</button>
        </div>
        <div id="conversationDiv">
            <label>name</label> <input type="text" id="name" />
            <br>
            <label>message</label> <input type="text" id="messgae" />
            <button id="send" onclick="send();">send</button>
            <p id="response"></p>
        </div>
    </div>
    <script src="stomp.umd.min-5.4.2.js"></script>
    <script src="jquery.min.js"></script>
    <script type="text/javascript">
        var stompClient = null;
        function setConnected(connected) {
            document.getElementById('connect').disabled = connected;
            document.getElementById('disconnect').disabled = !connected;
            document.getElementById('conversationDiv').style.visibility = connected ? 'visible' : 'hidden';
            $('#response').html();
        }
        var stompClient = null;
        function connect() {
            var userId = "admin", stompConfig = {
                brokerURL: "ws://127.0.0.1:8083/chat",
                connectHeaders: {
                    login: userId,
                    userId: userId,
                    userName: "administrator"
                },
                disconnectHeaders: {},
                debug: function (str) {
                    console.info(str);
                },
                reconnectDelay: 5000,
                heartbeatIncoming: 10000,
                heartbeatOutgoing: 10000,
                onConnect: function(frame) {
                    setConnected(true);
                    //任务topic消息, open, close
                    stompClient.subscribe('/topic/todoTask/open', function (frame) {
                        showResponse(frame.body);
                    }, {});
                },
                onWebSocketClose: function (frame) {
                    //console.warn("onWebSocketClose", frame);
                    showResponse(frame.body);
                }
            };
            stompClient = new StompJs.Client(stompConfig);
            stompClient.activate();
        }

        function disconnect() {
            if (stompClient != null) {
                stompClient.deactivate();
            }
            setConnected(false);
            console.log("Disconnected");
        }

        function send() {
            var name = $('#name').val();
            var message = $('#messgae').val();
            stompClient.send("/topic/todoTask/open", {userName: "zhangsan", userId: "test1"}, JSON.stringify({channel:"/topic/test/message",userId:name,formNo:message}));
        }

        function showResponse(message) {
            var response = $('#response');
            response.append(message+"</br>");
        }
    </script>
</body>
</html>

**Comment by llm163520** [comment]
ok, thanks！
