### ISSUE TITLE
Commit 306299323cd seems to have broken finagle tests

### ISSUE THREAD

**Issue by bryce-anderson** [netty/netty#9395]
### Expected behavior

Using the 4.1.38.Final-SNAPSHOT would not break out internal tests

### Actual behavior

Tests broken

### Steps to reproduce

Checkout commit 306299323cd (or later) and run the finagle tests. 

### Netty version

Snapshot SHA 306299323cd.

I don't yet know why it's broken, it could be finagle depending on a bug, but I wanted to file a ticket to let you know so if we need a fix we can get it into 4.1.38.Final. I'm looking into the issue now.

**Comment by normanmaurer** [comment]
That’s interesting... keep me posted

**Comment by normanmaurer** [comment]
@bryce-anderson btw as this was only some cleanup we can also revert the commit while trying to figure out what's wrong. WDYT ?

**Comment by bryce-anderson** [comment]
Let me try master with this reverted and we can go from there.

**Comment by normanmaurer** [comment]
thanks ...

**Comment by bryce-anderson** [comment]
Revert does fix it. It's a small enough diff that we might be able to sort it out pretty quick. Do you want to wait until tomorrow before reverting to give me a few hours to check how to fix it? The revert isn't 100% clean.

**Comment by normanmaurer** [comment]
Yeah sounds good

**Comment by bryce-anderson** [comment]
Added some comments to the commit.
https://github.com/netty/netty/commit/306299323cd47fed6d15767291a3d52e48d16786#r34402442
