### ISSUE TITLE
Connect timeout does not always work

### ISSUE THREAD

**Issue by A-Willems** [netty/netty#9399]
### Expected behavior
We configure our Bootstrap with ChannelOption.CONNECT_TIMEOUT_MILLIS to set the connect timeout to 2 seconds. We expect, that after 2 seconds the connect attempt will be canceled, e.g. due to a firewall blocking the connection attempt.

### Actual behavior
In most cases the timeout works as expected, however in some environments it does not work. After running our application for several hours in one of our clients environment, there were delays of up to 140 minutes before the timeout was handled.

### Steps to reproduce
I narrowed the problem down to the point where tasks are scheduled on an event loop group. We use an NioEventloopGroup with default size (i.e. double number of CPUs, in our case 12 threads). As connect attempts and scheduled timeouts use the same event loop group, there is a chance that the timeout task is scheduled to the same event loop as the connect task. In case that the connect task blocks, the timeout task is not executed as expected.

It is merely impossible to reproduce this behavior in an network environment, but I was able to setup  a small example using NioEventLoopGroup with two threads that simulates the problem.
It just starts a long running task and afterwards schedules 10 tasks to be executed after 2 seconds.
The blocking thread starts immediately on one event loop and the scheduled threads are distributed in a round robin manner on the two event loops. This leads to 5 tasks being executed after 2 seconds and the other 5 tasks to be executed after the long running task has terminated.

This example forces the behavior that we determined in our customers logs. We do not know exactly what causes one thread to block and to prevent connect timeout tasks to be executed. It might be - as I assume - a blocking connection attempt.  But it might be as well some other code of our own.
Anyways, the result is that the connect timeout task is not executed as it should be.

Therefore the question is, shouldn't there be a separate EventLoopGroup for the connection timeouts so that these are guaranteed to be executed?

### Minimal yet complete reproducer code (or URL to code)
```java
package test;

import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;

import io.netty.channel.EventLoopGroup;
import io.netty.channel.nio.NioEventLoopGroup;

public class NioTest {

    private static int SCHEDULED_TASK_COUNT = 10;

    private static long start;

    private static long diff() {

        return (System.nanoTime() - start) / 1000_000;
    }

    public static void main(String[] args) throws InterruptedException {

        // use a small event loop group to force the unexpected behavior
        EventLoopGroup loopGroup = new NioEventLoopGroup(2);

        CountDownLatch cdl = new CountDownLatch(SCHEDULED_TASK_COUNT + 1);

        start = System.nanoTime();
        System.out.println("start: " + diff());

        // submit a task, that is executed immediately
        loopGroup.submit(() -> {

            System.out.println(String.format("blocking task started    at %6d on thread %6d. Count down %d", diff(), Thread.currentThread().getId(), cdl.getCount()));
            System.out.println("waiting for 10 seconds ...");
            try {
                // wait for 5 seconds to simulate a blocking operation
                Thread.sleep(5000);
            } catch (InterruptedException e) {
            }
            System.out.println(String.format("blocking task finished  at %6d. Count down %d", diff(), cdl.getCount()));
            cdl.countDown();
        });
        System.out.println(String.format("blocking task submitted  at %6d. Count down %d", diff(), cdl.getCount()));

        for (int i = 0; i < SCHEDULED_TASK_COUNT; i++) {

            final int fi = i; // necessary to be accessible in closure ...

            // schedule tasks to be executed in 2 seconds
            loopGroup.schedule(() -> {
                String message = String.format("task %3d      started   at %6d on thread %6d. Count down %d",
                    fi, diff(), Thread.currentThread().getId(), cdl.getCount());

                System.out.println(message);
                cdl.countDown();
            }, 2, TimeUnit.SECONDS);

            System.out.println(String.format("task %3d      submitted at %6d. Count down %d", i, diff(), cdl.getCount()));
        }

        cdl.await();
        System.out.println(String.format("All tasks completed at %6d", diff()));
        loopGroup.shutdownGracefully();
    }
}
```

The result is

```
start: 0
blocking task submitted  at      8. Count down 11
blocking task started  at      8 on thread     13. Count down 11
waiting for 10 seconds ...
task   0      submitted at     12. Count down 11
task   1      submitted at     12. Count down 11
task   2      submitted at     12. Count down 11
task   3      submitted at     12. Count down 11
task   4      submitted at     13. Count down 11
task   5      submitted at     13. Count down 11
task   6      submitted at     13. Count down 11
task   7      submitted at     13. Count down 11
task   8      submitted at     13. Count down 11
task   9      submitted at     13. Count down 11
task   0      started   at   2014 on thread     14. Count down 11
task   2      started   at   2015 on thread     14. Count down 10
task   4      started   at   2015 on thread     14. Count down 9
task   6      started   at   2016 on thread     14. Count down 8
task   8      started   at   2016 on thread     14. Count down 7
blocking task finished  at   5010. Count down 6
task   1      started   at   5010 on thread     13. Count down 5
task   3      started   at   5010 on thread     13. Count down 4
task   5      started   at   5010 on thread     13. Count down 3
task   7      started   at   5011 on thread     13. Count down 2
task   9      started   at   5011 on thread     13. Count down 1
All tasks completed at   5011
```

### Netty version
4.1.23

### JVM version (e.g. `java -version`)
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

### OS version (e.g. `uname -a`)
Linux myhost 4.4.180-102-default #1 SMP Mon Jun 17 13:11:23 UTC 2019 (7cfa20a) x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@A-Willems this is completely expected... if you block the EventLoop all bets are off. You MUST never block the EventLoop.

**Comment by normanmaurer** [comment]
All connect attempts done by Netty are non-blocking.

**Comment by A-Willems** [comment]
Thank you for the reply. I think I found the weak spot in our code.
