### ISSUE TITLE
About netty4 multithreading codec

### ISSUE THREAD

**Issue by wangx1949** [netty/netty#9407]
@normanmaurer 
In netty4, Can io thread visible property "name" ? Property "name" is not **volatile**.

According to my understanding of happens-before, Property "name" may be in the CPU cache and not in main memory.

```
User user = new User(); //business thread
user.setName("admin");
channel.write(user); 
...
encoder.encode(user); //io thread
...

```

**Comment by amizurov** [comment]
I think this is will be work, because - synchronization actions. Also i can be wrong because talking about JMM is very difficult ))

**Comment by ninja-** [comment]
It will work correctly although I am not sure how to word the explanation 😄

**Comment by normanmaurer** [comment]
Yes this will work because of memory barriers provided by the underlying implementations. The important bit is that you will "NOT" modify the `USer` after you called write / encode.
