### ISSUE TITLE
Basic Auth doesn't work

### ISSUE THREAD

**Issue by GautamaBuddha** [netty/netty#9408]
DefaultHeaders class calculates same index for `Authorization` and `accept` headers.
NettyRequestFactory on the first step adds `Authorization` header after that is set `accept` to the same position in `entries` array.

![image](https://user-images.githubusercontent.com/1217820/62050755-929a7280-b21a-11e9-8586-014392c1f6ad.png)
![image](https://user-images.githubusercontent.com/1217820/62050765-96c69000-b21a-11e9-8135-98932a0a5191.png)
after `accept` is set we don't have Authorization header:
![image](https://user-images.githubusercontent.com/1217820/62050790-a645d900-b21a-11e9-89d7-fee3905fab24.png)

**Comment by normanmaurer** [comment]
Can you provide a unit test that shows the problem ?

**Comment by slandelle** [comment]
There’s something very suspicious here. You have « accept » in minor case as expected from constants from HttpHeaderNames but « Authorization » with a capital A?!
Have you forked AHC or Netty?

Are you sure you’re not modifying DefaultHttpHeaders instant from another thread?

**Comment by normanmaurer** [comment]
I will close this now as the reporter did vanish :/
