### ISSUE TITLE
[Enhancement Request] Expose DnsCache size

### ISSUE THREAD

**Issue by j-white** [netty/netty#9412]
We're using Netty v4.1.37 for asynchronous DNS resolution.

I would like view and keep track of cache statistics, particularly the size of the cache (num elements), but this isn't currently exposed via any public methods.

**Comment by normanmaurer** [comment]
Why not just write your own DnsCache which expose this ?

**Comment by j-white** [comment]
Size is already there, so I figured it would be easy to expose.

We've ran into some other limitations with the cache though, so we'll end up rolling our own anyways.
