### ISSUE TITLE
Thread pool for Netty Threads [Question]

### ISSUE THREAD

**Issue by Dimezis** [netty/netty#9418]
I'm setting up a gRPC server based on Netty (netty-4.1.38). According to all docs/papers I've found, Netty has 3 types of threads:
Boss, Worker, and Application Executor.
I've set up a server with thread pools for all of them (thread number = 1 just for test).

```Kotlin
NettyServerBuilder.forPort(port)
            .executor(Executors.newFixedThreadPool(1) {
                Thread(it)
                    .apply {
                        name = "Executor thread $id"
                    }
            })
            .workerEventLoopGroup(
                NioEventLoopGroup(1, ThreadFactory {
                    Thread(it)
                        .apply {
                            name = "Worker thread $id"
                        }
                })
            )
            .bossEventLoopGroup(NioEventLoopGroup(1, ThreadFactory {
                Thread(it)
                    .apply {
                        name = "Boss thread $id"
                    }
            }))
```

But when I run the server and connect with the client, I see some extra "Netty Threads" apart from those 3 expected (Boss, Worker, and Executor are present there too).

![image](https://user-images.githubusercontent.com/1433500/62362417-2753e780-b51d-11e9-9b71-ed97a69d99fe.png)

The call stack for such thread looks like this:
![image](https://user-images.githubusercontent.com/1433500/62362447-3b97e480-b51d-11e9-86e8-88fa02946407.png)

So it seems to be doing exactly the same thing as Worker threads do.

Also, more of these threads are spawning as the load increases. And my question is, what are those and why I can't control them via any thread pool?
I've searched through both Netty and gRPC repos and didn't find any Thread factory that spawns threads with "Netty Thread" name.

**Comment by ninja-** [comment]
> I've searched through both Netty and gRPC repos and didn't find any Thread factory that spawns threads with "Netty Thread" name.

What's your stack? I bet it's something like your database client ;)

**Comment by Dimezis** [comment]
Rx-gRPC (https://github.com/salesforce/reactive-grpc) -> Java gRPC  -> Netty. 
That's it, no db, and the setup is extremely simple so far, not deployed anywhere, only testing on localhost.

**Comment by ninja-** [comment]
Keep in mind looking for pattern might not be a direct find cause there are functions like this https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/concurrent/DefaultThreadFactory.java#L95 in libraries that build the actual name...you might need to dig deeper

**Comment by ninja-** [comment]
I did some digging for you and can't find anything that can spawn this as well. can you share more code?

**Comment by Dimezis** [comment]
Thanks! TBH there's not much to share.

Server's setup is dead simple. If I don't set up those pools, these threads are spawned as well.

```Kotlin
NettyServerBuilder.forPort(port)
            .addService(service)
            .intercept(interceptor)
            .build()
            .start()
            .awaitTermination()
```
The rest is my code inside of services, which is Rx only and operates on Rx Schedulers.

Nothing too special

```Kotlin
override fun some(request: Single<Request>): Flowable<SomeStream> {
    return request.flatMapPublisher { doStuff() }
}
```

**Comment by ninja-** [comment]
I'd say if netty maintainers were to join in, they'd ask for a minimum reproducer example(a repo) anyway, so if you can provide one I can dig it out for you

**Comment by Dimezis** [comment]
Yeah will make one on the weekend, just thought it's something more or less common

**Comment by ninja-** [comment]
Also you can try this trick: put a breakpoint in Thread constructor or Thread#start or somewhere there and you'll know where it's spawned. If the stacktrace is trash, just look more deeply in stack variables to find what it's related to.

**Comment by njhill** [comment]
@Dimezis is your client running in the same process? Seems likely it would be that if so. Can see from the stack that `KQueueEventLoop` is being used, which means it must be explicitly be configured somewhere separately. If not then something must be running another instance of netty in the same jvm as @ninja- suggested.

**Comment by ninja-** [comment]
@njhill it's not our KQueueEventLoop, it's standard NioEventLoop and Oracle's KQueue

**Comment by njhill** [comment]
@ninja- ah yes you're right of course! But my client question still applies :)

**Comment by Dimezis** [comment]
Alright, mystery solved :) Thank you guys for help!
So in my case it was a Lightstreamer library, totally forgot about it, and actually had no idea it uses Netty.
