### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by nichoding** [netty/netty#9419]
uname -a 
Linux toutiaopre 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)

netty version 
netty-all-4.0.30.Final.jar
netty-all-4.1.37.Final.jar

ulimit -n
65535

We have two similar online services based on netty,running on the same os and same jvm.
'A' has been online for a year and a half, and has never had any problem.
'B' has just been online for three months.
One and a half months ago, 'B' was down because of the server-open file descriptor reaches the system limit.

Since the first occurrence of this problem, the same problem has appeared several times in the past one and a half months.
We solved the problem every time by restarting the service...

At first we used the version 'netty-all-4.0.30.Final.jar'.
We tried to solve this problem by upgrading netty version to 'netty-all-4.1.37.Final.jar'.
Several day ago, we submitted the latest version to the production environment.
Unfortunately, this problem has happened again today.

There are two points worth thinking about:
1.**After the process restarts, the service can run normally for a few days or weeks.
During this time, the Non-Establish TCP Connection has been below 200.
But once the problem occurs, the number of Non-Establish TCP Connection starts to grow slowly,and it will never fall again.**

2.A and B run on the same operating system and jvm.

Since 'A' has more online users than 'B',the moment when the problem occurred seems to have nothing to do with the number of online users.

I have the heapdump, I can provide it if needed.
I found that many NioSockedServer objects are not released.
But in my system, only the 'ClientSession' refers to the NioSocketChannel object.
And ClientSession objects were released normally.

Here are some related pictures and code.
![1](https://user-images.githubusercontent.com/3257824/62371262-f4364600-b566-11e9-8073-839d246da1fb.png)
![2](https://user-images.githubusercontent.com/3257824/62371282-fd271780-b566-11e9-9f52-a089581a2606.png)
![3](https://user-images.githubusercontent.com/3257824/62371291-01533500-b567-11e9-97cd-cc8f0da73eb7.png)
![4](https://user-images.githubusercontent.com/3257824/62371292-031cf880-b567-11e9-864a-7e7fee7085b7.png)

You can see normal NioSocketChannel objects and abnormal NioSocketChannel objects in the heapdump.

![5](https://user-images.githubusercontent.com/3257824/62371892-8c80fa80-b568-11e9-85cc-5b3fc82c315f.png)
![6](https://user-images.githubusercontent.com/3257824/62371895-91de4500-b568-11e9-9da4-219895169d91.png)

Looking forward to your help, thank you very much!

**Comment by ninja-** [comment]
what's your normal online and what's holding references to these NioSocketChannels you think should be released?

**Comment by nichoding** [comment]
Thanks!@ninja
My mormal online is about 400 to 800.

There‘s no other class holding NioSocketChannels’s references except ClientSession.

This does not seem to be a connection attack because Non Established connection grows very slowly.
From the beginning of the problem to reach system limit, it usually takes several days.
I noticed that the error file descriptors are not established-connection yet.
**The connection state changes to CLOSE_WAIT before netty receives the ChannelActive event,even have't received the ChannelRegister event.
When a new error file descriptors appears, at first, I can use netstat to see the error connection, but after timeout, I can only see them by lsof.NioSocketChannels object has been created in memory,never get released.**

**Comment by ninja-** [comment]
> There‘s no other class holding NioSocketChannels’s references except ClientSession.
you have 600 ClientSessions and 5000 Channels so that doesn't make much sense to me?

**Comment by ninja-** [comment]
ok I now see you have highlighted the difference between a good channel and a bugged-out unregistered channel. but it's very important to know the gc roots of these buggy channels because if we can point out that they are in ArrayList in EventLoop or something, that's a start.

**Comment by ninja-** [comment]
also, keep in mind this can be just as well a leak from unclosed db connections if driver uses netty, or a http client etc. we can't be sure at this point these are sockets from your game server

**Comment by ninja-** [comment]
on a second look at these screenshots, if I understand correctly, these objects(both) are trash anyway without gc roots so they would be removed at next GC

**Comment by nichoding** [comment]
Thanks @ninja- 
I have checked the gc roots,I rememberd the buggy channels are in ArrayList in EventLoop.
Since we are not working hours now, I will confirm this again tomorrow.
In my application,netty is only used to process game client messages.

**Comment by nichoding** [comment]
[https://test-yaoji-ddz.oss-cn-hangzhou.aliyuncs.com/dsh/netty/7163.bin.tar.gz
](url)
this is the heapdump

**Comment by ninja-** [comment]
I had a look. It looks to me like you are having very big backpressure/cpu usage? problems.
The gc roots of these bugged channels are coming from WriteAndFlushTasks inside EventLoop.
These WriteAndFlushTasks have grown to like 5MB in heap just of them which I think is a hell lot.
It's not like they would be insta removed when channel is dead, because EventLoop tasks are a linked list, so they would be removed when EventLoop catches up.
So my interpretation here is that EventLoop is having _terrible_ problems catching up because of CPU usage.
You can try reducing the number of flushes you do in your app for example?

**Comment by nichoding** [comment]
Thanks! @ninja- 
Your explanation makes sense.
Cpu load was in very low level.
I have a question, are these buggy channels established?
If not, I could not send any message.

**Comment by ninja-** [comment]
I am not 100% sure on the problem here but for now use a few tips:
- switch NIO backend to EPOLL
- try to batch your writes if possible, so a few write() and one flush()
- use PooledAllocator because I see you are using unpooled

**Comment by nichoding** [comment]
ok.
Thank you for your suggestion, I will try it tomorrow.
Now that the online production environment is happening, I just got a few screenshots.
![2](https://user-images.githubusercontent.com/3257824/62386365-38870d80-b58a-11e9-8e67-0a8c08863576.png)

![3](https://user-images.githubusercontent.com/3257824/62386388-48065680-b58a-11e9-8755-001892ce3204.png)

**Comment by nichoding** [comment]
@ninja- 
NON_ESTABLISHED are buggy channel file descriptors.

**Comment by ninja-** [comment]
And how do you check if it's NON_ESTABLISHED cause that doesn't sound like a Linux socket state. What is on netstat?

**Comment by nichoding** [comment]
![5](https://user-images.githubusercontent.com/3257824/62387442-2fe40680-b58d-11e9-8d55-9b2b2eade5bd.png)

**Comment by nichoding** [comment]
[root@toutiaopre ~]# netstat -an | awk '/^tcp/ {++y[$NF]} END {for(w in y) print w, y[w]}'
LISTEN 34
CLOSE_WAIT 51
ESTABLISHED 397
FIN_WAIT1 4
FIN_WAIT2 1
TIME_WAIT 32

CLOSE_WAIT connections disappear when timeout.

**Comment by ninja-** [comment]
Also get rid of so_keepalive. Doesnt it bump the default timeout to 2 hours?

**Comment by nichoding** [comment]
lsof result like this:
java    7163 root 1041u     sock                0,7       0t0 55912330 protocol: TCP
java    7163 root 1042u     sock                0,7       0t0 56110643 protocol: TCP
java    7163 root 1043u     sock                0,7       0t0 56056825 protocol: TCP
java    7163 root 1044u     sock                0,7       0t0 56053716 protocol: TCP
java    7163 root 1045u     sock                0,7       0t0 56205292 protocol: TCP
java    7163 root 1046u     sock                0,7       0t0 56003231 protocol: TCP
java    7163 root 1047u     sock                0,7       0t0 55927162 protocol: TCP
java    7163 root 1048u     sock                0,7       0t0 55971051 protocol: TCP
java    7163 root 1049u     sock                0,7       0t0 56077685 protocol: TCP

**Comment by nichoding** [comment]
It can't be found in netstat after two hours timeout.
But also can be seen in lsof,like 'java 7163 root 1041u sock 0,7 0t0 55912330 protocol: TCP'

**Comment by ninja-** [comment]
Just remove it

**Comment by nichoding** [comment]
@ninja- 
remove? 
I don't understand what you mean.

**Comment by nichoding** [comment]
these file descriptor exists  because of unreleased channels.

**Comment by ninja-** [comment]
Remove so keepalive

**Comment by nichoding** [comment]
ok!
Thank you for your advice.I appreciate it very much.

**Comment by medusar** [comment]
mark

**Comment by ninja-** [comment]
@nichoding I am really curious if that fix worked for you 🤔

**Comment by normanmaurer** [comment]
closing as no update by reporter

**Comment by nichoding** [comment]
> @nichoding I am really curious if that fix worked for you
@ninja- 
It seems that it has not been fixed.
I removed so-keepalive and changed NIO to EPOLL.
Then it has been running for two weeks without any problem.
Yesterday I found that server-open file descriptor could'nt been released.
As your suggestion,I will try to batch your writes.

**Comment by chixuan777** [comment]
> > @nichoding I am really curious if that fix worked for you
> > @ninja-
> > It seems that it has not been fixed.
> > I removed so-keepalive and changed NIO to EPOLL.
> > Then it has been running for two weeks without any problem.
> > Yesterday I found that server-open file descriptor could'nt been released.
> > As your suggestion,I will try to batch your writes.

did it work？i have the same issue

**Comment by karolsteve** [comment]
I have the same issue

**Comment by takhir-atamuratov** [comment]
I had the same issue, because there were keep_alive true and I had not close channels, after (client) leave the system. I solve it by change keep_alive to false and close all clients channel when they left the system. You have to check your application, may be you too does not close the channels.

**Comment by sms0070** [comment]
Is there any update on this?
I'm getting this issue with 4.1.48.Final as well.

**Comment by VLoye** [comment]
I have the same issue.
I run a http server application with netty, and F5 detect if the listener port is alive through using tcp three-way handshake.I found than it would cause file description increase constantly and its growth rate is is consistent with the detection frequency of F5.

**Comment by emacsist** [comment]
I have the same issue.

**Comment by WeHoHo** [comment]
@nichoding I have the same issue.  How did you fix this finally?

**Comment by gm100861** [comment]
I have the same issue.

**Comment by gavin0713** [comment]
I have the same issue.

**Comment by KeithTt** [comment]
I have the same issue.

Any update...?

**Comment by cococomeon** [comment]
<img width="1444" alt="image" src="https://github.com/netty/netty/assets/16988275/3cfc3ed0-ea92-4897-8fa4-167a437d2ef7">
got the same issue
