### ISSUE TITLE
ctx.channel().writeAndFlush

### ISSUE THREAD

**Issue by lovlyhao** [netty/netty#9421]
![image](https://user-images.githubusercontent.com/30038949/62407599-7bc69800-b5ed-11e9-82ab-a642aa6da4b2.png)

Without task business logic, what output time interval is 1 second, sometimes 10 milliseconds. Where is the wrong configuration? Call method ctx. writeAndFlush

**Comment by normanmaurer** [comment]
Please use stackoverflow for questions
