### ISSUE TITLE
LengthFieldPrepender.encode

### ISSUE THREAD

**Issue by huyechao** [netty/netty#9422]
### Why in the LengthFieldPrepender, memory copy must occur once for write length,I think I can provide a way to write the length to the specified position.

@Override
    protected void encode(ChannelHandlerContext ctx, ByteBuf msg, ByteBuf out) throws Exception {
        int length = msg.readableBytes() + lengthAdjustment;
        if (lengthIncludesLengthFieldLength) {
            length += lengthFieldLength;
        }

        if (length < 0) {
            throw new IllegalArgumentException(
                    "Adjusted frame length (" + length + ") is less than zero");
        }

        switch (lengthFieldLength) {
        case 1:
            if (length >= 256) {
                throw new IllegalArgumentException(
                        "length does not fit into a byte: " + length);
            }
            out.writeByte((byte) length);
            break;
        case 2:
            if (length >= 65536) {
                throw new IllegalArgumentException(
                        "length does not fit into a short integer: " + length);
            }
            out.writeShort((short) length);
            break;
        case 3:
            if (length >= 16777216) {
                throw new IllegalArgumentException(
                        "length does not fit into a medium integer: " + length);
            }
            out.writeMedium(length);
            break;
        case 4:
            out.writeInt(length);
            break;
        case 8:
            out.writeLong(length);
            break;
        default:
            throw new Error("should not reach here");
        }

        out.writeBytes(msg, msg.readerIndex(), msg.readableBytes());
    }

**Comment by normanmaurer** [comment]
Please open a PR if you think you can provide an improvement with a good change

**Comment by huyechao** [comment]
ok，thank you
