### ISSUE TITLE
AbstractBoostrap: consider making options/attrs immutable or CopyOnWrite data structures

### ISSUE THREAD

**Issue by fabienrenaud** [netty/netty#9426]
In `AbstractBoostrap`, `options` and `attrs` are `LinkedHashMap` that are synchronized on for every read, copy/clone, write operation.
When a lot of connections are triggered concurrently on the same bootstrap instance, the synchronized blocks lead to contention, Netty IO threads get blocked, and performance may be severely degraded. 

We should consider rewriting these options/attrs data structure without synchronization nor locking on read, and minimal to no locking on write.
Methods to add multiple options/attrs at once should also be added.

It is unclear to me why the order of these options/attrs need to be preserved (why `LinkedHashMap` instead of `HashMap`).
Solutions could be to use `CopyOnWriteArrayList` of pairs or a `ConcurrentHashMap` if preserving order is not important.

**Comment by normanmaurer** [comment]
@fabienrenaud there is no need to preserve ordering... I would be happy to review a pr for this.

**Comment by normanmaurer** [comment]
@fabienrenaud PTAL https://github.com/netty/netty/pull/9458
