### ISSUE TITLE
How can I write a log outgoing a raw HTTP Requests?

### ISSUE THREAD

**Issue by aukhatov** [netty/netty#9428]
Hello guys!
I have a little trouble. I need to write a log outgoing HTTP Requests. These requests produced by Netty http-client.

### Netty version
4.1.36
### JVM version (e.g. `java -version`)
OpenJDK 11.0.3
### OS version (e.g. `uname -a`)
Linux Ubuntu 18.04

**Comment by amizurov** [comment]
Hi, could you please provide more information. Usually you can use log4j2 or logback, or any other loggers.

**Comment by aukhatov** [comment]
Hi @amizurov 
I use logback.

**Comment by amizurov** [comment]
Try to pipeline.addFirst("logger", new io.netty.handler.logging.LoggingHandler()) to your pipeline.

**Comment by aukhatov** [comment]
> Try add logger to pipeline `pipeline.addFirst("logger", new io.netty.handler.logging.LoggingHandler())`.

What is a `pipeline`?

**Comment by amizurov** [comment]
Could you please share piece of code and which is http-client you use ?

**Comment by normanmaurer** [comment]
Closing as no response from original reporter
