### ISSUE TITLE
Http2FrameCodec & Http2MultiplexHandler race condition

### ISSUE THREAD

**Issue by Bennett-Lynch** [netty/netty#9432]
I am experiencing what appears to be a race condition as part of trying to migrate HTTP/2 client code from `Http2MultiplexCodec` to `Http2FrameCodec`/`Http2MultiplexHandler`, as was introduced/recommended in Netty 4.1.37.

As per the [release notes](https://netty.io/news/2019/06/28/4-1-37-Final.html), we are recommended to change:
```
pipeline.addLast(Http2MultiplexCodecBuilder.forServer(new HelloWorldHttp2Handler()).build());
```
to:
```
pipeline.addLast(Http2FrameCodecBuilder.forServer().build());
pipeline.addLast(new Http2MultiplexHandler(new HelloWorldHttp2Handler());
```

My client code is written in an event-driven fashion so that upon opening up a new HTTP/2 connection and detecting a `Http2ConnectionPrefaceAndSettingsFrameWrittenEvent`, it will open a new stream with `Http2StreamChannelBootstrap#open()`. This is the recommended usage of the API/event as per https://github.com/netty/netty/issues/7599#issuecomment-359640185.

Problem:

1. Upon `Http2FrameCodec` being added to the pipeline, it may instantly fire a `Http2ConnectionPrefaceAndSettingsFrameWrittenEvent` (if the connection is already active).
2. This triggers a call to `Http2StreamChannelBootstrap#open()`, before `Http2MultiplexHandler` has been added to the pipeline.
3. `Http2MultiplexHandler` requires that `Http2FrameCodec` be present in the pipeline when adding it, so it cannot be added first.

So what used to be an atomic operation is no longer one, resulting in this apparent race condition.  This does not appear to be an issue if the connection is not yet active, but there are some use cases where some type of logic/handshake might be performed before registering the HTTP/2 codecs.

I could potentially work around this by creating and firing my own user event for once both `Http2FrameCodec` and `Http2MultiplexHandler` have been added to the pipeline, but I believe I would need to await both that event and the `Http2ConnectionPrefaceAndSettingsFrameWrittenEvent`, in case the latter is not fired instantly for some reason. This also seems hacky and seems to defeat the purpose of the `Http2ConnectionPrefaceAndSettingsFrameWrittenEvent`.

@normanmaurer

**Comment by normanmaurer** [comment]
@Bennett-Lynch https://github.com/netty/netty/pull/9442 PTAL
