### ISSUE TITLE
WebSocket08FrameEncoder Code redundancy

### ISSUE THREAD

**Issue by GeXin666** [netty/netty#9434]
### Netty version
4.1.29
### OS version (e.g. `uname -a`)

protected void encode(ChannelHandlerContext ctx, WebSocketFrame msg, List<Object> out)

int maskLength = maskPayload ? 4 : 0;
          //Has made a judgment length is less than or equal to 125
            if (length <= 125) {
                int size = 2 + maskLength;
               //length <= GATHERING_WRITE_THRESHOLD 
              //Is it redundant logic?????????
                if (maskPayload || length <= GATHERING_WRITE_THRESHOLD) {
                    size += length;
                }
                buf = ctx.alloc().buffer(size);
                buf.writeByte(b0);
                byte b = (byte) (maskPayload ? 0x80 | (byte) length : (byte) length);
                buf.writeByte(b);
            } else if (length <= 0xFFFF) {
                int size = 4 + maskLength;
                if (maskPayload || length <= GATHERING_WRITE_THRESHOLD) {
                    size += length;
                }
                buf = ctx.alloc().buffer(size);
                buf.writeByte(b0);
                buf.writeByte(maskPayload ? 0xFE : 126);
                buf.writeByte(length >>> 8 & 0xFF);
                buf.writeByte(length & 0xFF);
            } else {
                int size = 10 + maskLength;
                if (maskPayload || length <= GATHERING_WRITE_THRESHOLD) {
                    size += length;
                }
                buf = ctx.alloc().buffer(size);
                buf.writeByte(b0);
                buf.writeByte(maskPayload ? 0xFF : 127);
                buf.writeLong(length);
            }

**Comment by normanmaurer** [comment]
Please open a PR
