### ISSUE TITLE
io.netty.handler.ssl.SslContext javadoc mistake

### ISSUE THREAD

**Issue by petrbouda** [netty/netty#9444]
Javadoc contains:

 // In your ChannelInitializer:
 ChannelPipeline p = channel.pipeline();
 SslContext sslCtx = SslContextBuilder.forServer(...).build();
 p.addLast("ssl", sslCtx.newHandler(channel.alloc()));
 
I suppose it supposed to be **addFirst**

**Comment by normanmaurer** [comment]
@petrbouda actually both is just fine and if you add it as first or last really depends on your use-case.

**Comment by petrbouda** [comment]
Aah OK, sorry for this non-relevant issue :)
