### ISSUE TITLE
An information leakage from AbstractBootstrap to log

### ISSUE THREAD

**Issue by xqfu** [netty/netty#9446]
Netty version 4.1.19.Final
JVM version 1.8.0_191

In io.netty.bootstrap.AbstractBootstrap, 

    private static void setChannelOption(
            Channel channel, ChannelOption<?> option, Object value, InternalLogger logger) {

        try {
            if (!channel.config().setOption((ChannelOption<Object>) option, value)) {
                logger.warn("Unknown channel option '{}' for channel '{}'", option, channel);
            }
        } catch (Throwable t) {
            logger.warn(
                    "Failed to set channel option '{}' with value '{}' for channel '{}'", option, value, channel, t);
        }
    }
Sensitive information about option and channel is leaked. The logger.isWarnEnabled() conditional statements should be added:

    private static void setChannelOption(
            Channel channel, ChannelOption<?> option, Object value, InternalLogger logger) {

        try {
            if (!channel.config().setOption((ChannelOption<Object>) option, value)) {
				if (logger.isWarnEnabled())
					logger.warn("Unknown channel option '{}' for channel '{}'", option, channel);
            }
        } catch (Throwable t) {
			if (logger.isWarnEnabled())
				logger.warn(
                    "Failed to set channel option '{}' with value '{}' for channel '{}'", option, value, channel, t);
        }
    }

**Comment by medusar** [comment]
The `logger.warn` method will check log level internally. And i don't think it has anything to do with sensitive information.

**Comment by normanmaurer** [comment]
as @medusar is right...
