### ISSUE TITLE
An information leakage from SingleThreadEventExecutor to log

### ISSUE THREAD

**Issue by xqfu** [netty/netty#9449]
Netty version 4.1.19.Final
JVM version 1.8.0_191

In io.netty.util.concurrent.SingleThreadEventExecutor, 

    private void doStartThread() {
        assert thread == null;
        executor.execute(new Runnable() {
            @Override
            public void run() {
				......
                            if (!taskQueue.isEmpty()) {
                                logger.warn(
                                        "An event executor terminated with " +
                                                "non-empty task queue (" + taskQueue.size() + ')');
                            }
				......               
            }
        });
    }
Sensitive information about the queue size is leaked. The logger.isWarnEnabled() conditional statement should be added:

    private void doStartThread() {
        assert thread == null;
        executor.execute(new Runnable() {
            @Override
            public void run() {
				......
                            if (!taskQueue.isEmpty()) {									     
								if (logger.isWarnEnabled())       
									logger.warn(
                                        "An event executor terminated with " +
                                                "non-empty task queue (" + taskQueue.size() + ')');
                            }
				......               
            }
        });
    }

**Comment by normanmaurer** [comment]
Like mentioned in other issues this is fine as it is not expensive to create the log message
