### ISSUE TITLE
An information leakage from PlatformDependent to log

### ISSUE THREAD

**Issue by xqfu** [netty/netty#9450]
Netty version 4.1.19.Final
JVM version 1.8.0_191

In io.netty.util.internal.PlatformDependent, 

	static {
		...... 
		        logger.debug("-Dio.netty.maxDirectMemory: {} bytes", maxDirectMemory);
		...... 
        logger.debug("-Dio.netty.uninitializedArrayAllocationThreshold: {}", UNINITIALIZED_ARRAY_ALLOCATION_THRESHOLD);
	}
    private static long maxDirectMemory0() {
		...... 
        if (maxDirectMemory <= 0) {
            maxDirectMemory = Runtime.getRuntime().maxMemory();
            logger.debug("maxDirectMemory: {} bytes (maybe)", maxDirectMemory);
        } else {
            logger.debug("maxDirectMemory: {} bytes", maxDirectMemory);
        }
		...... 
    }

    private static File tmpdir0() {
        File f;
		...... 
                logger.debug("-Dio.netty.tmpdir: {}", f);
		...... 
                logger.debug("-Dio.netty.tmpdir: {} (java.io.tmpdir)", f);
		...... 
                    logger.debug("-Dio.netty.tmpdir: {} (%TEMP%)", f);
		...... 
                        logger.debug("-Dio.netty.tmpdir: {} (%USERPROFILE%\\AppData\\Local\\Temp)", f);
  		...... 
                        logger.debug("-Dio.netty.tmpdir: {} (%USERPROFILE%\\Local Settings\\Temp)", f);
		...... 
                    logger.debug("-Dio.netty.tmpdir: {} ($TMPDIR)", f);
		...... 
        logger.warn("Failed to get the temporary directory; falling back to: {}", f);
        return f;
    }
	
	private static int bitMode0() {
		...... 
            logger.debug("-Dio.netty.bitMode: {}", bitMode);
 		...... 
            logger.debug("-Dio.netty.bitMode: {} (sun.arch.data.model)", bitMode);
		...... 
            logger.debug("-Dio.netty.bitMode: {} (com.ibm.vm.bitmode)", bitMode);
   		...... 
        if (bitMode > 0) {
            logger.debug("-Dio.netty.bitMode: {} (os.arch: {})", bitMode, arch);
        }
   		...... 
    }
	
Sensitive information about maxDirectMemory, file or bitmode is leaked. The logger.isDebugEnabled() and logger.isWarnEnabled() conditional statements should be added:

 	static {
		...... 
			if (logger.isDebugEnabled())
		        logger.debug("-Dio.netty.maxDirectMemory: {} bytes", maxDirectMemory);
		...... 
			if (logger.isDebugEnabled())
				logger.debug("-Dio.netty.uninitializedArrayAllocationThreshold: {}", UNINITIALIZED_ARRAY_ALLOCATION_THRESHOLD);
	}
    private static long maxDirectMemory0() {
		...... 
        if (maxDirectMemory <= 0) {
            maxDirectMemory = Runtime.getRuntime().maxMemory();
			if (logger.isDebugEnabled())
				logger.debug("maxDirectMemory: {} bytes (maybe)", maxDirectMemory);
        } else {
			if (logger.isDebugEnabled())
				logger.debug("maxDirectMemory: {} bytes", maxDirectMemory);
        }
		...... 
    }

    private static File tmpdir0() {
        File f;
		...... 
			if (logger.isDebugEnabled())
                logger.debug("-Dio.netty.tmpdir: {}", f);
		...... 
			if (logger.isDebugEnabled())
                logger.debug("-Dio.netty.tmpdir: {} (java.io.tmpdir)", f);
		...... 
                
			if (logger.isDebugEnabled())
				logger.debug("-Dio.netty.tmpdir: {} (%TEMP%)", f);
		...... 		
					if (logger.isDebugEnabled())
                        logger.debug("-Dio.netty.tmpdir: {} (%USERPROFILE%\\AppData\\Local\\Temp)", f);
  		...... 
		
					if (logger.isDebugEnabled())
                        logger.debug("-Dio.netty.tmpdir: {} (%USERPROFILE%\\Local Settings\\Temp)", f);
		...... 		
				if (logger.isDebugEnabled())
                    logger.debug("-Dio.netty.tmpdir: {} ($TMPDIR)", f);
		...... 
		if (logger.isWarnEnabled())
			logger.warn("Failed to get the temporary directory; falling back to: {}", f);
        return f;
    }
	
	private static int bitMode0() {
		...... 
			if (logger.isDebugEnabled())
				logger.debug("-Dio.netty.bitMode: {}", bitMode);
 		...... 		
			if (logger.isDebugEnabled())
				logger.debug("-Dio.netty.bitMode: {} (sun.arch.data.model)", bitMode);
		...... 		
			if (logger.isDebugEnabled())
				logger.debug("-Dio.netty.bitMode: {} (com.ibm.vm.bitmode)", bitMode);
   		...... 
        if (bitMode > 0) {			
			if (logger.isDebugEnabled())
				logger.debug("-Dio.netty.bitMode: {} (os.arch: {})", bitMode, arch);
        }
   		...... 
    }

**Comment by normanmaurer** [comment]
Like mentioned in other issues this is fine as it is not expensive to create the log message
