### ISSUE TITLE
An information leakage from PromiseNotificationUtil to log

### ISSUE THREAD

**Issue by xqfu** [netty/netty#9451]
Netty version 4.1.19.Final
JVM version 1.8.0_191

In io.netty.util.internal.PromiseNotificationUtil, 

    public static void tryCancel(Promise<?> p, InternalLogger logger) {
        if (!p.cancel(false) && logger != null) {
            Throwable err = p.cause();
            if (err == null) {
                logger.warn("Failed to cancel promise because it has succeeded already: {}", p);
            } else {
                logger.warn(
                        "Failed to cancel promise because it has failed already: {}, unnotified cause:",
                        p, err);
            }
        }
    }

    public static <V> void trySuccess(Promise<? super V> p, V result, InternalLogger logger) {
        if (!p.trySuccess(result) && logger != null) {
            Throwable err = p.cause();
            if (err == null) {
                logger.warn("Failed to mark a promise as success because it has succeeded already: {}", p);
            } else {
                logger.warn(
                        "Failed to mark a promise as success because it has failed already: {}, unnotified cause:",
                        p, err);
            }
        }
    }

    public static void tryFailure(Promise<?> p, Throwable cause, InternalLogger logger) {
        if (!p.tryFailure(cause) && logger != null) {
            Throwable err = p.cause();
            if (err == null) {
                logger.warn("Failed to mark a promise as failure because it has succeeded already: {}", p, cause);
            } else {
                logger.warn(
                        "Failed to mark a promise as failure because it has failed already: {}, unnotified cause: {}",
                        p, ThrowableUtil.stackTraceToString(err), cause);
            }
        }
    }
	
Sensitive information about promise is leaked. The logger.isWarnEnabled() conditional statements should be added:

    public static void tryCancel(Promise<?> p, InternalLogger logger) {
        if (!p.cancel(false) && logger != null) {
            Throwable err = p.cause();
            if (err == null) {
				if (logger.isWarnEnabled())
					logger.warn("Failed to cancel promise because it has succeeded already: {}", p);
            } else {
				if (logger.isWarnEnabled())
					logger.warn(
                        "Failed to cancel promise because it has failed already: {}, unnotified cause:",
                        p, err);
            }
        }
    }

    public static <V> void trySuccess(Promise<? super V> p, V result, InternalLogger logger) {
        if (!p.trySuccess(result) && logger != null) {
            Throwable err = p.cause();
            if (err == null) {			
				if (logger.isWarnEnabled())
					logger.warn("Failed to mark a promise as success because it has succeeded already: {}", p);
            } else {		
				if (logger.isWarnEnabled())
					logger.warn(
                        "Failed to mark a promise as success because it has failed already: {}, unnotified cause:",
                        p, err);
            }
        }
    }

    public static void tryFailure(Promise<?> p, Throwable cause, InternalLogger logger) {
        if (!p.tryFailure(cause) && logger != null) {
            Throwable err = p.cause();
            if (err == null) {	
				if (logger.isWarnEnabled())
					logger.warn("Failed to mark a promise as failure because it has succeeded already: {}", p, cause);
            } else {	
				if (logger.isWarnEnabled())
					logger.warn(
                        "Failed to mark a promise as failure because it has failed already: {}, unnotified cause: {}",
                        p, ThrowableUtil.stackTraceToString(err), cause);
            }
        }
    }

**Comment by normanmaurer** [comment]
Like mentioned in other issues this is fine as it is not expensive to create the log message
