### ISSUE TITLE
An information leakage from NioEventLoop

### ISSUE THREAD

**Issue by xqfu** [netty/netty#9455]
In io.netty.channel.Channel.NioEventLoop, statements logger.warn(....) don't have LOG configuration controls.	

        private void select(boolean oldWakenUp) throws IOException {
            if (time - TimeUnit.MILLISECONDS.toNanos(timeoutMillis) >= currentTimeNanos) {
                    selectCnt = 1;
            } else if (SELECTOR_AUTO_REBUILD_THRESHOLD > 0 && selectCnt >= SELECTOR_AUTO_REBUILD_THRESHOLD) {
                    logger.warn(
                            "Selector.select() returned prematurely {} times in a row; rebuilding Selector {}.",
                            selectCnt, selector);
			......					
        }
	Sensitive information about selectCnt and selector may be leaked. The LOG.isWarnEnabled() conditional statement should be added:
	
        private void select(boolean oldWakenUp) throws IOException {
            if (time - TimeUnit.MILLISECONDS.toNanos(timeoutMillis) >= currentTimeNanos) {
                    selectCnt = 1;
            } else if (SELECTOR_AUTO_REBUILD_THRESHOLD > 0 && selectCnt >= SELECTOR_AUTO_REBUILD_THRESHOLD) {
				if (logger.isWarnEnabled())
                    logger.warn(
                            "Selector.select() returned prematurely {} times in a row; rebuilding Selector {}.",
                            selectCnt, selector);
			......					
        }

**Comment by medusar** [comment]
There is no need to add extra log level check.

**Comment by xqfu** [comment]
Dear Jason Wong:

    In the source code (version 4.1.19), there are many log level checks.

    For example, in io.netty.channel.AbstractChannelHandlerContext,

 lines 286-298:

            } catch (Throwable error) {
                if (logger.isDebugEnabled()) {
                    logger.debug(
                        "An exception {}" +
                        "was thrown by a user handler's exceptionCaught() " +
                        "method while handling the following exception:",
                        ThrowableUtil.stackTraceToString(error), cause);
                } else if (logger.isWarnEnabled()) {
                    logger.warn(
                        "An exception '{}' [enable DEBUG level for full stacktrace] " +
                        "was thrown by a user handler's exceptionCaught() " +
                        "method while handling the following exception:", error, cause);
                }


    I don't know why some statements need log level check while others don't.


   Please help me check them.


   Thank you very much!

   Yours sincerely

________________________________

**Comment by medusar** [comment]
In the code below, because the parameter in `logger.debug` is too long, and multiple strings are connected together by `+`,  add a log level check will save time and space when your log level is `info`.

For example, the parameter is a string, and the string is generated by connect multiple strings together.
```
    "An exception {}" +
                        "was thrown by a user handler's exceptionCaught() " +
                        "method while handling the following exception:",
                        ThrowableUtil.stackTraceToString(error),
```
As you can see, there is a `ThrowableUtil.stackTraceToString(error)`, which will generate a large string, if the log level is `info`, then there is no need to generate the strings. So add a `isDebugEnabled` will save both time and space.

But if the parameter is not too long, or there is no extra work to generate a string, `isDebugEnable` check is not necessary because the method `log.debug` will check it internally.

As for slf4j, it provids a placeholder `{}` to pass multiple strings into the method, and after checking the log level, it will connect all the parameters together by replacing the placeholder.

**Comment by xqfu** [comment]
In io.netty.channel.epoll.AbstractEpollStreamChannel, 
lines 708-715:
    private static void safeClosePipe(FileDescriptor fd) {
        if (fd != null) {
            try {
                fd.close();
            } catch (IOException e) {
                if (logger.isWarnEnabled()) {
                    logger.warn("Error while closing a pipe", e);
                }
            }
        }
    }

The parameter is not long and there is no extra work to generate the string. 
Is the (logger.isWarnEnabled()) reduntant?

**Comment by medusar** [comment]
Yes, i think so. I think it is not necessary do an extra check.

**Comment by medusar** [comment]
@xqfu I think you'd better close all those issues you have created about log level check.

**Comment by normanmaurer** [comment]
Like mentioned in other issues this is fine as it is not expensive to create the log message
