### ISSUE TITLE
Some log level checks (logger.isWarnEnabled()) should be removed

### ISSUE THREAD

**Issue by xqfu** [netty/netty#9456]
Netty version 4.1.19.Final
JVM version 1.8.0_191

For the short parameter which is generated simply, logger.isWarnEnabled() check is not necessary.
For example, in io.netty.channel.epoll,AbstractEpollStreamChannel, 

    private static void safeClosePipe(FileDescriptor fd) {
        if (fd != null) {
            try {
                fd.close();
            } catch (IOException e) {
                if (logger.isWarnEnabled()) {
                    logger.warn("Error while closing a pipe", e);
                }
            }
        }
    }

The "if (logger.isWarnEnabled())" should be removed:

    private static void safeClosePipe(FileDescriptor fd) {
        if (fd != null) {
            try {
                fd.close();
            } catch (IOException e) {
                    logger.warn("Error while closing a pipe", e);
                }
            }
        }
    }

Same problems also exist in io.netty.channel.DefaultFileRegion, io.netty.channel.nio.AbstractNioChannel, io.netty.util.HashedWheelTimer, io.netty.handler.stream.ChunkedWriteHandler, io.netty.channel.udt.nio.NioUdtMessageConnectorChannel

**Comment by normanmaurer** [comment]
@xqfu please open a pr with the changes in question.

**Comment by xqfu** [comment]
Dear  Norman:
    I want to open a pr but I cannot access github to create a branch.

$ git push origin Remove_loggerisWarnEnabledchecks
remote: Permission to netty/netty.git denied to xiaoqin-fu.
fatal: unable to access 'https://github.com/netty/netty.git/': The
requested URL returned error: 403

    How to apply to a contributor for Netty?


    Thank you very much!
    Yours sincerely
    Xiaoqin Fu

**Comment by normanmaurer** [comment]
@xqfu you need to fork Netty and create the branch in your fork. Once done you can open a PR.

**Comment by xqfu** [comment]
@normanmaurer 
How to apply Netty contributor and then I will have the right to push my branch?
I  already set up my development environment and signed the contributor license agreement according to the document at https://netty.io/wiki/developer-guide.html,

**Comment by SplotyCode** [comment]
You need to fork over github then add the fork as remote in your ide. Create the branch on your fork and then create a pr over github and select the branch from your fork.

**Comment by xqfu** [comment]
I am very sorry that I had created the branch in my IDE. I need push right for the remote branch now.
