### ISSUE TITLE
WebSocketClientHandshakerFactory#newHandshaker method ignores mask parameters

### ISSUE THREAD

**Issue by vietj** [netty/netty#9463]
### Expected behavior

`WebSocketClientHandshakerFactory#newHandshaker` method overload does not ignore mask parameters

### Actual behavior

`WebSocketClientHandshakerFactory#newHandshaker` overload method ignores mask parameters

```
    public static WebSocketClientHandshaker newHandshaker(
            URI webSocketURL, WebSocketVersion version, String subprotocol,
            boolean allowExtensions, HttpHeaders customHeaders, int maxFramePayloadLength,
            boolean performMasking, boolean allowMaskMismatch) {
        return newHandshaker(webSocketURL, version, subprotocol, allowExtensions, customHeaders,
                maxFramePayloadLength, true, false, -1);
    }
```

`performMasking` and `allowMaskMismatch` are not used instead `true` and `false` are used.

### Steps to reproduce

Use `WebSocketClientHandshakerFactory#newHandshaker(URI, WebSocketVersion, boolean, HttpHeaders, boolean, boolean)` method with `performMasking` false or `allowMaskMismatch` true values

### Minimal yet complete reproducer code (or URL to code)

Not really needed.

### Netty version

4.1.39.Final

### JVM version (e.g. `java -version`)

N/A

### OS version (e.g. `uname -a`)

N/A

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/9464
