### ISSUE TITLE
Example HTTP/2 client uses extra bogus request

### ISSUE THREAD

**Issue by gustavonalle** [netty/netty#9482]
The http/2 client in the examples section adds an [channel handler](https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http2/helloworld/client/Http2ClientInitializer.java#L129)  to send a [bogus request](https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http2/helloworld/client/Http2ClientInitializer.java#L140) just for the sake of initiating a clear text upgrade.

Further along, there's a [wait ](https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http2/helloworld/client/Http2Client.java#L108) to verify the setting messages was received. 

Is this really necessary? I was wondering if there's any client side handlers/codecs support for clear text upgrades (including http/2 prior knowledge) that handle this in a better way

**Comment by TristanPerry** [comment]
That particular examples uses the 'old' `InboundHttp2ToHttpAdapter`/`HttpToHttp2ConnectionHandler` approach for creating a HTTP/2 client  which actually uses the HTTP/1 objects (`FullHttpRequest`/`FullHttpResponse`) - in essence hiding away the underlying HTTP/2 functionality, which may account for the clunky approach in this client example.

`Http2MultiplexHandler` and `Http2FrameCodec` (`Http2FrameCodecBuilder.forClient()`) can instead be used which gives more fine-grained control, and which exposes the direct HTTP/2 frames (via `DefaultHttp2Headers`, `DefaultHttp2DataFrame`, `DefaultHttp2SettingsFrame` etc). This would be the approach for HTTP/2 prior knowledge or HTTP-ALPN (with HTTP/2) and some examples of this can be seen in  #8692 and #7599. There's no official client examples of this at current, though.

For clear text client upgrades using the 'new' approach, I struggled with this myself (albeit I only  played around with it for 30 minutes). However `Http2FrameCodec` is a `Http2ConnectionHandler`, so `new Http2ClientUpgradeCodec(Http2FrameCodecBuilder.forClient().initialSettings(Http2Settings.defaultSettings()).build())` would probably be a good starting point?
