### ISSUE TITLE
Consider programmatically exposing current Netty version

### ISSUE THREAD

**Issue by Bennett-Lynch** [netty/netty#9483]
Sometimes Netty makes behavioral/functional changes between minor releases. For example, a  recent PR, https://github.com/netty/netty/pull/9442, fixed a race condition with the HTTP/2 codecs. While this is a backwards compatible change from an API perspective, usage of these codecs could yield different results with different versions of Netty.

Visibility on the current Netty version could be beneficial from this perspective alone, esp. for logging purposes... but in the scenario where you might be vending a library that depends on a non-shaded version of Netty, it might be critically important what version of Netty is available on the class path.  If the current version was programmatically exposed, libraries could use it to make decisions in a similar fashion that Netty itself uses `PlatformDependent.javaVersion()`.

**Comment by normanmaurer** [comment]
@Bennett-Lynch I think you are correct that this would be useful. The only question I have here is would you do this for netty-common alone or for each jar as at the end it could be that someone has a mix of different jars. I think netty-common alone would be fine.

**Comment by Bennett-Lynch** [comment]
That’s a good point. Personally, I would be fine with netty-common, as I typically import Netty via netty-all, and it would probably be too complicated to do it for every jar. I suspect netty-common would probably be fine for most people with that specific caveat called out.

**Comment by normanmaurer** [comment]
@Bennett-Lynch you are fancy doing a PR ?

**Comment by Bennett-Lynch** [comment]
I can try to submit a PR for this. Do you have any suggestions for how to keep the version automatically up to date with builds/releases?

**Comment by normanmaurer** [comment]
@Bennett-Lynch cool... I think we may be able to just use some maven goal / plugin to replace it while the jar is packaged.

**Comment by jakub-dzon** [comment]
@Bennett-Lynch It seems that `io.netty.util.Version` should do the trick.

**Comment by normanmaurer** [comment]
@jakub-dzon you are completely right! I honestly did completely forget we already have something like this 🤦‍♂ .

@Bennett-Lynch I will close the ticket now :)
