### ISSUE TITLE
Recommended JDK / JVM for Netty

### ISSUE THREAD

**Issue by WhiteTrashLord** [netty/netty#9485]
Is there any JDK / JVM which should be the most stable for a Netty application?
Do your Netty testsuites only run with Oracle Java?
I read that Netty had some problems with OpenJ9 in the past so I would appreciate some advice.

**Comment by normanmaurer** [comment]
@WhiteTrashLord no there is none... We test with OpenJDK, OracleJDK, OpenJ9 and GraalVM on our CI tho. So it all comes down to preference and needs I guess.
