### ISSUE TITLE
Netty source jars don't contain C source code

### ISSUE THREAD

**Issue by battleblow** [netty/netty#9494]
### Expected behavior

Giving an example for netty 4.1.39 (current release)

netty-transport-native-epoll-4.1.39.Final-linux-x86_64.jar contains the file META-INF/native/libnetty_transport_native_epoll_x86_64.so, but 
netty-transport-native-epoll-4.1.39.Final-sources.jar only contains the Java source, not the C source that was used to create the shared library.  The same is true for the KQueue JARs.

I thought the C code would be distributed as well and was wondering if it was deliberately not included.

### Actual behavior

C code for the shared libraries is not distributed in the corresponding source JAR.

### Steps to reproduce

Run 'jar tf' on the relevant JARs

### Minimal yet complete reproducer code (or URL to code)

jar tf netty-transport-native-epoll-4.1.39.Final-linux-x86_64.jar | grep so
jar tf netty-transport-native-epoll-4.1.39.Final-sources.jar| less

### Netty version

4.1.39

### JVM version (e.g. `java -version`)

N/A

### OS version (e.g. `uname -a`)

N/A

**Comment by normanmaurer** [comment]
@battleblow sounds like a bug... we should include these.

**Comment by normanmaurer** [comment]
@battleblow PTAL https://github.com/netty/netty/pull/9497

**Comment by battleblow** [comment]
Thanks!
