### ISSUE TITLE
Data Receiving Problem of Serial Port Connection

### ISSUE THREAD

**Issue by Ward-Wang** [netty/netty#9496]
Hello, I am currently trying to connect to the serial device using netty, and introduced the 4.1.39.Final version of the netty-transport-rxtx and netty-all packages via maven.
I used the RxtxChannel class and configured the parameters needed for the serial connection. When I successfully established a connection with the device, 
I sent the request and the response data was returned by the device successfully.
The main problem is that netty splits and receives a piece of data when it receives data. This situation does not occur in other serial debugging software.
I want to know how to configure, can the data reception of serial communication be accepted once and completely?
In addition, is there any other way to communicate with serial devices in the 4.1.39.Final version?

**Comment by normanmaurer** [comment]
@Ward-Wang I think there is no way to configure it to not split...

**Comment by normanmaurer** [comment]
@Ward-Wang PTAL https://github.com/netty/netty/pull/9497

**Comment by Ward-Wang** [comment]
I tried to turn off the channel's autoRead option, set up the connection and send the data, waited for 5 seconds using Thread.sleep, and then actively read the data from the Channel, at which point all data was received at one time instead of being received in batches.
I decided to use the fixed length or delayed receiving method to process the data, thank you for your help.
