### ISSUE TITLE
Unefficient use of io.netty.util.ByteProcessor$IndexOfProcessor

### ISSUE THREAD

**Issue by comtel2000** [netty/netty#9499]
### Expected behavior
ByteBufUtils.indexOf(..) or in my case ByteBuf$bytesBefore for any ByteBuf
should work as efficient as a simple for loop without object allocation for ByteProcessor$IndexOfProcessor

### Actual behavior
Usage of ByteBuf$indexOf or ByteBuf$bytesBefore stress the garbage collector by allocate ByteProcessor$IndexOfProcessor for each call

By replace all indexOf and bytesBefore with simple for loops reduce the garabge in my App by 50%

### Steps to reproduce
compare object allocation / memory footprint for:
```java
AbstractByteBuf$bytesBefore(byte b)
```

and a simple:

```java
    protected static int bytesBefore(ByteBuf in, byte b) {
      for (int i = in.readerIndex(); i < in.writerIndex(); i++) {
        if (in.getByte(i) == b) {
          return i - in.readerIndex();
        }
      }
      return -1;
    }
```

### Minimal yet complete reproducer code (or URL to code)
-
### Netty version
4.1.39-Final
### JVM version (e.g. `java -version`)
1.8.212 x64
### OS version (e.g. `uname -a`)
Windows 10

**Comment by normanmaurer** [comment]
@comtel2000 that's a good one... we can definitely add some optimisation here.. Will open a pr shortly

**Comment by normanmaurer** [comment]
@comtel2000 PTAL https://github.com/netty/netty/pull/9502
