### ISSUE TITLE
Java 11 with Netty 4.1.39 - Illegal access DnsResolver (Windows only)

### ISSUE THREAD

**Issue by aaloise** [netty/netty#9500]
Vert,x 3.8.1 depends on Netty 4.1.39. Created a simple app based on https://how-to.vertx.io/http-client-howto/

If the jar is runned on Windows, it says:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.resolver.dns.DnsNameResolver (file:/C:/Users/1585988/Downloads/my-first-app/target/my-first-app-1.0.0-SNAPSHOT-fat.jar) to method sun.net.dns.ResolverConfiguration.open()
WARNING: Please consider reporting this to the maintainers of io.netty.resolver.dns.DnsNameResolver
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

But in Linux no illegal access appears. Java version in both environments is 11.0.4

Can this be related to #8318 ?

**Comment by normanmaurer** [comment]
need to check...

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/9511
