### ISSUE TITLE
Http2MultiplexHandler forces to provide an upgradeStreamHandler during client side cleartext upgrade

### ISSUE THREAD

**Issue by nizarm** [netty/netty#9508]
When we use Http2MultiplexHandler along with a clear tex upgrade in client side using Http2ClientUpgradeCodec, it throws an exception when a ChannelHandler is not provided for upgradeStreamHandler as shown below.

```java
// We need to handle upgrades special when on the client side.
                        if (stream.id() == Http2CodecUtil.HTTP_UPGRADE_STREAM_ID && !isServer(ctx)) {
                            // We must have an upgrade handler or else we can't handle the stream
                            if (upgradeStreamHandler == null) {
                                throw connectionError(INTERNAL_ERROR,
                                        "Client is misconfigured for upgrade requests");
                            }
                            ch = new Http2MultiplexHandlerStreamChannel(stream, upgradeStreamHandler);
                            ch.closeOutbound();
                        } else {
                            ch = new Http2MultiplexHandlerStreamChannel(stream, inboundStreamHandler);
                        }
```
It might make sense to force to provide the upgradeHandler when it is used in the server side. But when it is used in the client side the user can chose to create the outbound channel using Http2StreamChannelBootstrap. So it would be better to ignore the creation of StreamChannel when the upgradeHandler is null and the user can choose to create client side outbound channel purely through Http2StreamChannelBootstrap (as shown in the below code snippet)
```java
// We need to handle upgrades special when on the client side.
                        if (stream.id() == Http2CodecUtil.HTTP_UPGRADE_STREAM_ID && !isServer(ctx)) {
                            // We must have an upgrade handler or else we can't handle the stream
                            if (upgradeStreamHandler != null) {
                                ch = new Http2MultiplexHandlerStreamChannel(stream, upgradeStreamHandler);
                               ch.closeOutbound();
                        } else {
                            ch = new Http2MultiplexHandlerStreamChannel(stream, inboundStreamHandler);
                        }
```
In my implementation I am passing a DummyHandler for now as I am not using the upgradeChannel and using Http2StreamBootStrapChannel class to create new outbound http2StreamChannels.

Please review and let me know if this make sense. If we are okay - happy to provide a PR for this change !

**Comment by normanmaurer** [comment]
Sounds good

**Comment by normanmaurer** [comment]
@nizarm you will provide a PR for this ?

**Comment by normanmaurer** [comment]
@nizarm ping... if you don't have time just let me know and I will look into it.

**Comment by normanmaurer** [comment]
@nizarm PTAL https://github.com/netty/netty/pull/9533

**Comment by nizarm** [comment]
> @nizarm ping... if you don't have time just let me know and I will look into it.

Being on "onCall" last week didnt help me look in to this. Thanks for taking this up !

**Comment by nizarm** [comment]
> @nizarm PTAL #9533

LGTM

**Comment by nizarm** [comment]
Thanks for the fix. We may close this issue now !

**Comment by normanmaurer** [comment]
Like explained in https://github.com/netty/netty/pull/9533#issuecomment-529390319 there are "better" ways to handle this.
