### ISSUE TITLE
Why does Netty  have a default WebSocket frame size of only 65536 byte

### ISSUE THREAD

**Issue by GitHubDongChen** [netty/netty#9510]
https://github.com/netty/netty/blob/7c5a3c5898b03e839fcbb8e2fd6e7203303b7dfa/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerProtocolHandler.java#L144

The WebSocket protocol limits the size to 18,446,744,073,709,551,615 bytes. Is there a reason for that low frame size?

**Comment by normanmaurer** [comment]
@GitHubDongChen if the limit is too low it may allow the remote peer to exhaust the memory of the receiving end.
