### ISSUE TITLE
The `netty-all.jar` is missing the `native-image.properties` files from sub-modules

### ISSUE THREAD

**Issue by cstancu** [netty/netty#9514]
The GraalVM Native Image configuration files under `META-INF` are automatically included in the generated jar of the corresponding module, e.g., [`native-image.properties`](https://github.com/netty/netty/blob/4.1/codec-http/src/main/resources/META-INF/native-image/io.netty/codec-http/native-image.properties) is included in the `netty-codec-http.jar`, but not in `nety-all.jar`. I looked around the Netty build system but couldn't figure it out. It looks like the sub-module jars include the files in the corresponding `META-INF` directories automatically. 
cc: @pmlopes

**Comment by pmlopes** [comment]
I don't know the inner details of the `netty-all` build process. I guess it would be nice to have but I am at the same level as you here...

**Comment by normanmaurer** [comment]
I will have a look.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/9518... PTAL
