### ISSUE TITLE
HttpObjectAggregator can't split truck 

### ISSUE THREAD

**Issue by tanjoc** [netty/netty#9520]
### Expected behavior
I used netty to proxy http request between inner network and internet, and the layout: netty proxy server in internet, inner proxy server and inner web server. I got response form inner web server via a channel has been create between  inner proxy server and netty server when I post a request with chrome client,  I can got http response success. but if I post more request quickly with chrome client, 
### Actual behavior
I got a page which contains  some source javascript code and html page if i send quickly.

### Minimal yet complete reproducer code (or URL to code)
  public void startup() {

        try {
            ServerBootstrap b = new ServerBootstrap();
            b.group(bossGroup, workerGroup)
                    .channel(NioServerSocketChannel.class)
                    .option(ChannelOption.SO_BACKLOG, 1024)
                    .childHandler(new ChannelInitializer<SocketChannel>() {
                        @Override
                        protected void initChannel(SocketChannel socketChannel) throws Exception {
                            socketChannel.pipeline().addLast(
                                    new IdleStateHandler(READER_IDLE_TIME, WRITER_IDLE_TIME, ALL_IDLE_TIME),
                                    //new HttpRequestEncoder(),
                                    //new EmaHttpResponseDecoder(),
                                    new HttpClientCodec(deviceConnectServerChannelStorageService,
                                            channelClosedService),
                                    new HttpObjectAggregator(65536),
                                    new RemoteWebDevConnectChannelHandler(
                                            deviceConnectServerChannelStorageService,
                                            clientConnectServerChannelStorageService,
                                            channelClosedService)
                            );
                        }
                    });
            ResourceLeakDetector.setLevel(ResourceLeakDetector.Level.ADVANCED);
            Channel channel = b.bind(remoteDevPort).sync().channel();
            log.info("Started Remote device Server in port {}...", remoteDevPort);
            channel.closeFuture().sync();
        } catch (InterruptedException e) {
            log.error("Failed create remote device server, {}", e.getMessage());
        } finally {
            workerGroup.shutdownGracefully();
            bossGroup.shutdownGracefully();
        }
    }

 @Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
        this.deviceSn = (String) ctx.channel().attr(KEY).get();
        log.debug("Received device request msg {},deviceSn  {}", msg, deviceSn);
        Optional<Channel> channelOptional = clientConnectServerChannelStorageService.getChannel(deviceSn);
        if (channelOptional.isPresent()) {
            Channel channel = channelOptional.get();
            channel.writeAndFlush(msg).addListener((ChannelFutureListener) channelFuture -> {
                if (channelFuture.isSuccess()) {
                    Channel clientChannel = clientConnectServerChannelStorageService.remove(deviceSn);
                    log.info("send device response to website with channel {}", clientChannel.id());
                }
            });
        }
    }

### Netty version
4.1.33.final

### JVM version (e.g. `java -version`)
java 8

### OS version (e.g. `uname -a`)
centos 7.6

**Comment by normanmaurer** [comment]
sorry but without more infos it will be impossible to help.

Please provide more infos / a reproducer.

**Comment by normanmaurer** [comment]
Closing as no response from reporter.
