### ISSUE TITLE
Performance regression introduced in 4.1.35 and later

### ISSUE THREAD

**Issue by zoewangg** [netty/netty#9522]
While upgrading netty version from `4.1.33` to `4.1.39` in our application, we observed performance regression in the newer versions.

After narrowing down, the client performance seems gradually degraded since `4.1.35`. We are using JMH to measure throughput for our netty client code and starting from `4.1.37`, the throughput has been decreased by around 10%.  The degradation occurred for both H1 and H2 code path.

Are you aware of anything between those versions that could cause performance degradation? Are there any performance tests in place to catch regressions?

**Comment by normanmaurer** [comment]
@zoewangg I am not aware of anything and did not detect any regressions in our microbenchmarks. Can you share the benchmark / flamegraphs ?

**Comment by franz1981** [comment]
Looking into https://netty.io/news/2019/06/28/4-1-37-Final.html I can't see stuff that could cause any perf hit @zoewangg there is anything on that list that recall you what you're doing in your JMH bench?

**Comment by zoewangg** [comment]
This is our benchmark code: https://github.com/aws/aws-sdk-java-v2/tree/master/test/sdk-benchmarks/src/main/java/software/amazon/awssdk/benchmark/apicall/httpclient/async

Background: AWS Java SDK v2 uses Netty client under the hood for async requests.  All the benchmark code does is to use netty http client to send sequential or concurrent requests to local mock h1 or h2 servers with openssl or default jdk ssl handler and measure throughput.

Below is the comparison between using 4.1.39 and 4.1.33. The only change in the SDK is the Netty version number. Diff <= 100 is treated as tolerable margin.

Benchmark  |  4.1.39 vs. 4.1.33 throughput comparison |     
-----------| --------                          
NettyClientH1NonTlsBenchmark.concurrentApiCall  |  -2.9%
NettyClientH1NonTlsBenchmark.sequentialApiCall |  tolerable difference
NettyHttpClientH1Benchmark.concurrentApiCall (jdk) |  -7.8%
NettyHttpClientH1Benchmark.concurrentApiCall (openssl) | -5%
NettyHttpClientH1Benchmark.sequentialApiCall (jdk) |  tolerable difference
NettyHttpClientH1Benchmark.sequentialApiCall (openssl) |  tolerable difference
NettyHttpClientH2Benchmark.concurrentApiCall (jdk) | -9.8%
NettyHttpClientH2Benchmark.concurrentApiCall (openssl) | -11.4%
NettyHttpClientH2Benchmark.sequentialApiCall (jdk) | tolerable difference
NettyHttpClientH2Benchmark.sequentialApiCall (openssl) | tolerable difference

Looking at the release notes, could this contribute to the slow down? https://github.com/netty/netty/pull/9240/files#r293832922

**Comment by normanmaurer** [comment]
@zoewangg I don't think so... can you please also share flamegraps ?

**Comment by normanmaurer** [comment]
@zoewangg I am wondering if the cause is maybe:

https://github.com/netty/netty/pull/9274

It seems like you not bin a specific cipher which means it may pick `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384` and so be slower ... Can you verify if this is the case ?

**Comment by zoewangg** [comment]
Sorry for the delay, we were able to identify the cause for the slowdown. Will report back the issue and possible fix.

**Comment by normanmaurer** [comment]
Thanks a lot! Looking forward to more details :)

**Comment by dagnir** [comment]
Hi @normanmaurer, after some profiling, it seems this is the change that is affecting us: https://github.com/netty/netty/commit/f17bfd0f64189d91302fbdd15103788bf9eabaa2. Spefically, it seems to be the change to stop using a static instance of `CancellationException` in `DefaultPromise#cancel()` that's taking up extra CPU in our case.

For context, in the SDK we use a new `WriteTimeoutHandler` that is added to the channel pipeline before sending an HTTP request: https://github.com/aws/aws-sdk-java-v2/blob/79a22b071b381ecbce2b94ce7935ed879971f25f/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyRequestExecutor.java#L187-L194. Since this handler `cancel`s the pending task on a successful write (which is pretty much 100% in our benchmark code), a lot of time gets taken up creating the exceptions.

Added an SS of the flame graph for a profiling capture I did.
![netty-4-1-39-cancellationexception](https://user-images.githubusercontent.com/261310/64210791-07d01780-ce59-11e9-9994-11384670c461.png)

**Comment by normanmaurer** [comment]
@dagnir thanks a lot for the details... This makes a lot of sense. @njhill is working on a fix already :)

**Comment by dagnir** [comment]
Thanks @normanmaurer, @njhill!

**Comment by normanmaurer** [comment]
@dagnir could you test with the change merged as part of https://github.com/netty/netty/pull/9534 ?

**Comment by dagnir** [comment]
Thanks @normanmaurer. Running our benchmark suite now.

**Comment by dagnir** [comment]
@normanmaurer @njhill  Our numbers are back to baseline with this change (or slightly improved). Thanks for the quick turnaround!

When can we expect to see 4.1.40.Final released to Maven?

**Comment by normanmaurer** [comment]
@dagnir thanks a lot to confirm this! I will release the next version mid next week.

**Comment by dagnir** [comment]
Hi @normanmaurer just checking in to see if this fix is still on track to be released this week. Thanks!

**Comment by normanmaurer** [comment]
Yes! On my to do list for tomorrow
