### ISSUE TITLE
Netty should set request header host by default when http1.1 is used.

### ISSUE THREAD

**Issue by LUGYHAN** [netty/netty#9543]
### Expected behavior
Netty should set request header host by default when http 1.1 is used if customer does not set the host header.

### Actual behavior
Get 400 response if do not set header host.

### Steps to reproduce
Use examples in the project, and delete set host header action in examples.

### Netty version
4.0.24.Final

### JVM version (e.g. `java -version`)
build 1.8.0_151-b12

### OS version (e.g. `uname -a`)
MacOS Mojavae 10.14.5

**Comment by normanmaurer** [comment]
I disagree.. the user should do it as it is not clear if a hostname / ip etc should be used.
