### ISSUE TITLE
Netty giving SSL handshaking error while connecting to SNI enabled end points

### ISSUE THREAD

**Issue by bipin-naggarro** [netty/netty#9544]
### Expected behavior
I expect Netty to successfully complete SSL handshaking and establish HTTPS connection

### Actual behavior
Netty fails during SSL handshaking

### Netty version
		<netty.version>4.1.39.Final</netty.version>

### JVM version (e.g. `java -version`)
java version "1.8.0_211"
### OS version (e.g. `uname -a`)
Windows-10

Below are the logs

INFO   | jvm 1    | main    | 2019/09/06 12:42:47.269 | WARN  [clientHTTP21] [CharonHandler] this is a blocking call, be aware of performance concerns
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.269 | INFO  [clientHTTP21] [CharonHandler] baseUrl:https://idp.qa.client.com.vn/auth/oauth2/default/v1/authorizerest/oauth2/v1, method:POST, consumes:Optional[application/x-www-form-urlencoded], uri:/token
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.270 | ERROR [nioEventLoopGroup-2-1] [ResponseHandler] javax.net.ssl.SSLException: Received fatal alert: handshake_failure
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.270 | io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: handshake_failure
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.270 | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:475) ~[netty-codec-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.271 | 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283) ~[netty-codec-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.271 | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.271 | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.272 | 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.278 | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.278 | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.279 | 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.279 | 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.280 | 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.280 | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.281 | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.281 | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.281 | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511) [netty-transport-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.282 | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) [netty-common-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.283 | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.283 | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.283 | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.284 | Caused by: javax.net.ssl.SSLException: Received fatal alert: handshake_failure
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.284 | 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[?:1.8.0_161]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.288 | 	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666) ~[?:1.8.0_161]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.290 | 	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634) ~[?:1.8.0_161]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.294 | 	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800) ~[?:1.8.0_161]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.295 | 	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083) ~[?:1.8.0_161]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.295 | 	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907) ~[?:1.8.0_161]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.296 | 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[?:1.8.0_161]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.296 | 	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_161]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.296 | 	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:282) ~[netty-handler-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.297 | 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1329) ~[netty-handler-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.299 | 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224) ~[netty-handler-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.304 | 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1271) ~[netty-handler-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.305 | 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505) ~[netty-codec-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.305 | 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444) ~[netty-codec-4.1.39.Final.jar:4.1.39.Final]
INFO   | jvm 1    | main    | 2019/09/06 12:42:47.305 | 	... 17 more

**Comment by bipin-naggarro** [comment]
Netty client is working fine with server where SNI is not enabled . But gives SSL handshaking error with server where SNI is enabled . 

Please help me to fix the issue.

**Comment by normanmaurer** [comment]
Please provide the code-snippet where you setup the SslHandler.

**Comment by bipin-naggarro** [comment]
thanks @normanmaurer  for quick reply . there is other framework (Charon ) which is using Netty . I just configure HTTPS url in config file . Charon using netty is performing all the communication with HTTPS url and returns the response to application . can you please give some hint , will Charon build the SSLHandler or Netty ?

**Comment by normanmaurer** [comment]
It will be `Charon`... I suspect they not use the correct overload of `SslContext` which takes a hostname as well which is used for SNI. Please open a bug there. 

They need to use this one:

https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslContext.java#L988

**Comment by bipin-naggarro** [comment]
@normanmaurer  thanks for your response. So you are suggesting to use **newHandler(alloc, peerHost, peerPort, startTls)** to build SSLHandler , but https end point do not have port . 
URL is https://api-ts.uat.apac.client.net/ . There is no port .

Also can you please share me sample demo project that I can use to test Netty with SSLHandler you are suggesting .

**Comment by normanmaurer** [comment]
if there is no port specified in the url and its https the port is 443 as it the standard port for https.
