### ISSUE TITLE
netty nextReceiveBufferSize bug

### ISSUE THREAD

**Issue by brucelwl** [netty/netty#9549]
I think netty's dynamic memory computing may be a bug, please see netty source code ``AdaptiveRecvByteBufAllocator.HandleImpl#record``, if ``actualReadBytes`` is 2155, the final result of var ``nextReceiveBufferSize`` should be 4196, but the reality is that it will always 8192,
the reason is that var ``index``  is reduced by one, but if judged it will continue to be subtracted by one.
please see my example code. on branch `` netty_bug_demo`` ,executing my sample code console will print memory allocation information.
run NettyServer and NettyClient .
https://github.com/brucelwl/demo/tree/netty_bug_demo

![image](https://user-images.githubusercontent.com/13413715/64473965-e300da80-d19f-11e9-9810-bc5e832f443d.png)

**Comment by brucelwl** [comment]
@johnou @normanmaurer normanmaurer Why is no one confirming this issue?

**Comment by johnou** [comment]
@brucelwl to best honest I don't think the unit test is up to snuff, plus waiting for feedback from @trustin
