### ISSUE TITLE
NonStickyOrderedEventExecutor source reading problem

### ISSUE THREAD

**Issue by duaicxx** [netty/netty#9552]
NonStickyOrderedEventExecutor What is the NonSticky definition?

**Comment by duaicxx** [comment]
Why is it NonSticky?

**Comment by johnou** [comment]
It implies that Threads may change between execution of tasks for an EventExecutor but ordering is still guaranteed.

**Comment by duaicxx** [comment]
Does it mean that the thread and the currently executing task are non-sticky

**Comment by duaicxx** [comment]
> It implies that Threads may change between execution of tasks for an EventExecutor but ordering is still guaranteed.

Does the thread switch during the execution of the thread? But when creating a group, the executor can't be an order, and there is an executor inside it. How to understand it? I saw an unorder group for an implementation of the jdk default task pool. Other groups use the executor's own task pool, so other group executions have no order and unorder is ordered. My understanding is whether ordering depends on whether a thread's execution task has a sequential concept like this?

**Comment by normanmaurer** [comment]
@duaicxx basically the guarantee is that everything is executed in the order it was submitted but it is not guaranteed that the same Thread will process it.
