### ISSUE TITLE
SocksAuthRequest constructor occasionally throws IllegalStateException on CharsetEncoder#canEncode(CharSequence) call

### ISSUE THREAD

**Issue by jbaldassari** [netty/netty#9556]
### Expected behavior
The `SockAuthRequest` constructor call always completes successfully.

### Actual behavior
Occasionally the `SocksAuthRequest` constructor will throw `IllegalStateException` when checking whether the given username and password can be encoded as `US_ASCII`.  The following stack trace is observed:

```
java.lang.IllegalStateException: Current state = RESET, new state = FLUSHED
	at java.base/java.nio.charset.CharsetEncoder.throwIllegalStateException(CharsetEncoder.java:989)
	at java.base/java.nio.charset.CharsetEncoder.flush(CharsetEncoder.java:672)
	at java.base/java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:801)
	at java.base/java.nio.charset.CharsetEncoder.canEncode(CharsetEncoder.java:907)
	at java.base/java.nio.charset.CharsetEncoder.canEncode(CharsetEncoder.java:982)
	at io.netty.handler.codec.socks.SocksAuthRequest.<init>(SocksAuthRequest.java:43)
```

`SocksAuthRequest` declares the following static member:

```
private static final CharsetEncoder asciiEncoder = CharsetUtil.encoder(CharsetUtil.US_ASCII);
```

It it then used in the constructor like this:

```
        if (!asciiEncoder.canEncode(username) || !asciiEncoder.canEncode(password)) {
            throw new IllegalArgumentException(
                    "username: " + username + " or password: **** values should be in pure ascii");
        }
```

One of these calls to `canEncode` occasionally throws the `IllegalStateException`.  It should be noted that multiple threads may be invoking this constructor concurrently.  However, nothing about `SocksAuthRequest` implies that it has any restrictions regarding multi-threaded use. Looking at `CharsetUtil`, it appears that it is caching a thread-local encoder instance.  I wonder if some _other_ use of `CharsetUtil#encoder` is putting the cached encoder into a bad state where it later blows up.  My code never calls `CharsetUtil`, so if cache poisoning is indeed happening, it must be somewhere else in the Netty SOCKS code.

### Steps to reproduce

Unfortunately I don't have a simple reproducer for this issue.  It happens only very occasionally in code I've written that utilizes the SOCKS classes included with Netty.

### Minimal yet complete reproducer code (or URL to code)

None at this time.

### Netty version

4.1.27.Final

### JVM version (e.g. `java -version`)

```
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)
```

### OS version (e.g. `uname -a`)

```
$ uname -a
Linux t560 4.20.17-gentoo #2 SMP Wed May 29 13:35:58 EDT 2019 x86_64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz GenuineIntel GNU/Linux
```

**Comment by jbaldassari** [comment]
I think the issue may actually be the fact that this encoder is being declared as a `static` member.  When it is used this way, there is no guarantee that the thread that initialized the class is the same thread that is performing the `canEncode` check (and actually it's very unlikely).  I think that instead of using a single static encoder, the constructor should be calling `CharsetUtil.encoder(CharsetUtil.US_ASCII)` every time to ensure that it gets the correct thread-local encoder instance for its thread.  I'll create a PR.

**Comment by normanmaurer** [comment]
@jbaldassari good catch... this sounds like it may be the case.

**Comment by jbaldassari** [comment]
PR posted: https://github.com/netty/netty/pull/9558

I think this is my first netty PR, so please let me know if I'm missing something.  Based on the other open PRs I found, it looks like this should go against the `4.1` branch rather than `master`, but let me know if I'm supposed to open a PR against `master` as well.  Thanks!
