### ISSUE TITLE
Cannot add two WebSocketServerProtocolHandler at different URIs

### ISSUE THREAD

**Issue by gaut2112** [netty/netty#9559]
Pardon my knowledge of netty
I'm trying to setup Netty (4.1.39final) to implement a web server which serves two separate WebSocket services differentiated by the URI pattern:

/wsA : service 1 , 
/wsB : service 2 

initChannel method in my ChannelInitializer looks like:

    pipeline.addLast(new HttpServerCodec());
    pipeline.addLast(new HttpObjectAggregator(65536));
    pipeline.addLast(new WebSocketServerProtocolHandler("/wsA"));
    pipeline.addLast(new WebSocketFrameHandlerA());
    pipeline.addLast(new WebSocketServerProtocolHandler("/wsB"));
    pipeline.addLast(new WebSocketFrameHandlerB());

when I try to open a connection the the second WebSocket service the client hangs forever and the connection never gets established.
Is this expected behavior?
What am I doing wrong here
I have been through netty examples but could not find answers

**Comment by normanmaurer** [comment]
As far as I can tell this will not work... What you could do is dynamically add the handler to the pipeline depending on the URI.
