### ISSUE TITLE
enormous amount of FastThreadLocal instances

### ISSUE THREAD

**Issue by mrniko** [netty/netty#9562]
### Expected behavior

FastThreadLocal instances aren't growing

### Actual behavior

FastThreadLocal instances are growing - about 550K instances

### Minimal yet complete reproducer code (or URL to code)

Heap dump https://cmoviepic.bj.bcebos.com/production%2Foom%2Fwalle_api_bj-B-01_heap.hprof.tar.gz

### Netty version

4.1.39.Final

Can anybody help to realize why it's happening?

**Comment by songjiesdnu** [comment]
Actual behavior is "FastThreadLocal instances aren't growing"? In my app, the actual behavior is that,  FastThreadLocal is growing bigger and bigger.

**Comment by mrniko** [comment]
@songjiesdnu 

I fixed the description.

**Comment by songjiesdnu** [comment]
@mrniko 
I read some source codes of redisson, and debug it for a while. Here is what I find about how  it's happening.
1. In class `org.redisson.client.handler.ConnectionWatchdog`，when method `channelInactive(ChannelHandlerContext ctx)` is invoked, `bootstrap.connect(SocketAddress remoteAddress)` is invoked.

**Comment by Liyixin95** [comment]
Why not make the field `state ` static?

**Comment by mrniko** [comment]
Fixed in Redisson lib

**Comment by normanmaurer** [comment]
@mrniko can you link the commit ?

**Comment by mrniko** [comment]
@normanmaurer 

Sure. Here it is https://github.com/redisson/redisson/commit/3a47ed40c0e088937c839111ee062861bc0d21ec
