### ISSUE TITLE
Netty won't load OpenSSL 

### ISSUE THREAD

**Issue by lihao5257** [netty/netty#9567]
Hello ,I am putting the TLS into a RPC project. I copied the Netty example source codes and run it. But I got an exception when I used the OpenSSL .
Exception:
java.lang.IllegalArgumentException: Failed to load any of the given libraries:
 [netty_tcnative_windows_x86_64, netty_tcnative_x86_64, netty_tcnative]

### Expected behavior
should work
### Actual behavior
I followed the official guide on the wiki on how to install the netty-tcnative with the following link [(https://netty.io/wiki/forked-tomcat-native.html)]

maven file
...
      <dependency>
	      <groupId>io.netty</groupId>
	      <artifactId>netty-tcnative-boringssl-static</artifactId>
	      <version>2.0.0.Final</version>
	      <classifier>${os.detected.classifier}</classifier>
       </dependency>
       ...
    	<extensions>
	      <extension>
	        <groupId>kr.motd.maven</groupId>
	        <artifactId>os-maven-plugin</artifactId>
	        <version>1.4.0.Final</version>
	      </extension>
	    </extensions>

I got the following exception when I run the souce code.
    java.lang.IllegalArgumentException: Failed to load any of the given libraries:
 [netty_tcnative_windows_x86_64, netty_tcnative_x86_64, netty_tcnative]

### Steps to reproduce

// Configure SSL.
        SslContext sslCtx;
        try {
            if (SSL) {
                SslProvider provider = **OpenSsl.isAlpnSupported()** ? SslProvider.OPENSSL : SslProvider.JDK;
                SelfSignedCertificate ssc = new SelfSignedCertificate();
                sslCtx = io.netty.handler.ssl.SslContextBuilder
                    .forServer(ssc.certificate(), ssc.privateKey())
                    .sslProvider(provider)
                    /*
                     * NOTE: the cipher filter may not include all ciphers required by the HTTP/2
                     * specification. Please refer to the HTTP/2 specification for cipher
                     * requirements.
                     */
                    .ciphers(Http2SecurityUtil.CIPHERS, SupportedCipherSuiteFilter.INSTANCE)
                    .applicationProtocolConfig(
                        new ApplicationProtocolConfig(
                            ApplicationProtocolConfig.Protocol.ALPN,
                            // NO_ADVERTISE is currently the only mode supported by both OpenSsl and JDK
                            // providers.
                            ApplicationProtocolConfig.SelectorFailureBehavior.NO_ADVERTISE,
                            // ACCEPT is currently the only mode supported by both OpenSsl and JDK
                            // providers.
                            ApplicationProtocolConfig.SelectedListenerFailureBehavior.ACCEPT,
                            ApplicationProtocolNames.HTTP_2, ApplicationProtocolNames.HTTP_1_1))
                    .build();
### Netty version
Netty version
4.1.25.Final 
### JVM version (e.g. `java -version`)
"1.8.0_221"
### OS version (e.g. `uname -a`)
Win 10 pro

**Comment by lihao5257** [comment]
In the official document [https://netty.io/wiki/forked-tomcat-native.html](url), there are 3 ArtifactIds present. 
Because I don't want to download OpenSSl or require APR , I choosed the netty-tcnative-boringssl-static-{os_arch} to use  and followed the "How to download netty-tcnative-boringssl-static" stuctions.
Read the stuctions, and I think all I need is adding  os-maven-plugin extension and the netty-tcnative-boringssl-static dependency, am I right?

I tried many attemps and failed.
Plean give me some help and thanks in advance.

**Comment by johnou** [comment]
Please provide full output of java -version

I suspect you are not running x64 JVM.

**Comment by lihao5257** [comment]
java -version

java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

**Comment by normanmaurer** [comment]
Please show your pom.xml

**Comment by lihao5257** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <artifactId>sofa-rpc-extension-impl</artifactId>
        <groupId>com.alipay.sofa</groupId>
        <version>5.5.1</version>
    </parent>

    <artifactId>sofa-rpc-remoting-http</artifactId>
    
    <dependencies>
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>sofa-rpc-extension-common</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
       **<dependency>
	      <groupId>io.netty</groupId>
	      <artifactId>netty-tcnative-boringssl-static</artifactId>
	      <version>2.0.0.Final</version>
	      <classifier>${os.detected.classifier}</classifier>
	    </dependency>**
	           
    </dependencies>

    <build>
    	**<extensions>
	      <extension>
	        <groupId>kr.motd.maven</groupId>
	        <artifactId>os-maven-plugin</artifactId>
	        <version>1.4.0.Final</version>
	      </extension>
	    </extensions>**
        <sourceDirectory>src/main/java</sourceDirectory>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
                <includes>
                    <include>**/**</include>
                </includes>
            </resource>
        </resources>
        <testSourceDirectory>src/test/java</testSourceDirectory>
        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>false</filtering>
                <includes>
                    <include>**/**</include>
                </includes>
            </testResource>
        </testResources>


        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <configuration>
                    <skip>${module.install.skip}</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-deploy-plugin</artifactId>
                <configuration>
                    <skip>${module.deploy.skip}</skip>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <skipTests>${skipTests}</skipTests>
                    <includes>
                        
                        <include>**/*Test.java</include>
                    </includes>
                    
                    <forkMode>once</forkMode>
                </configuration>
            </plugin>

        </plugins>
    </build>
</project>

**Comment by normanmaurer** [comment]
What netty version you use ? 

Also you should use the latest netty-tcnative-boringssl-static version:

```
      <version>2.0.25.Final</version>
```

**Comment by lihao5257** [comment]
netty-all-4.1.25.Final.jar

I am now trying to use the  latest netty-tcnative-boringssl-static version and confirm the result.

**Comment by normanmaurer** [comment]
also please use latest netty version (4.1.42.Final)

**Comment by lihao5257** [comment]
OK I 'll try it.

**Comment by lihao5257** [comment]
Bingo.
Thank you very much! @normanmaurer 
netty version : netty-all-4.1.25.Final.jar
latest netty-tcnative-boringssl-static version: 2.0.25.Final

**Comment by lihao5257** [comment]
I appreciate your help.

**Comment by normanmaurer** [comment]
So can we close this ?

**Comment by lihao5257** [comment]
Of course. Thank you

**Comment by NupurAluria** [comment]
hi ,

For  java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)


I am getting error java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_windows_x86_64, netty_tcnative_x86_64, netty_tcnative]
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:114)
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:710)


I used  <dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-all</artifactId>
    <version>4.1.42.Final</version>
</dependency>
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-tcnative-boringssl-static</artifactId>
    <version>2.0.25.Final</version>
</dependency>

**Comment by chrisvest** [comment]
@NupurAluria `io.grpc.netty.shaded.…` – you're really using shaded grpc netty, not your netty-all 4.1.42.
