### ISSUE TITLE
how to get the result ByteBuf of MessageToByteEncoder.encode()

### ISSUE THREAD

**Issue by wjjboy** [netty/netty#9569]
We want to save every output ByteBuf communication log to db.
How to get the result ByteBuf of MessageToByteEncoder.encode() when using `channel.writeAndFlush(data)` 
thanks for all.

**Comment by normanmaurer** [comment]
Just add a `ChannelOutboundHandlerAdapter` in the pipeline before the encoder and intercept the `write(...)` by overriding the method.
