### ISSUE TITLE
Content gets appended to Http Method if content-length header is not set.

### ISSUE THREAD

**Issue by nikhilvavs** [netty/netty#9576]
### Expected behavior
I have a client and a server both using netty to send and receive requests. Both of them have HttpObjectAggregators and work on the FullHttpRequest/FullHttpResponse.
If content is set, but the content-length header is not set, the request sent from the client looks as expected, but the request received by the server has the content appended to the method.

**Expected:** Method in the HttpRequest should not be polluted with contents (irrespective of whether content-length header is set)

### Actual behavior
The HttpRequest as seen by the server has content appended to the method type.

### Steps to reproduce

1. Create a client to send the request.
2. Create a request in the client with some content but don't set the content-length header.
3. Log the request as sent by the client.
4. Log the request as received by the server.
#### Client Side
```
ByteBuf content = Unpooled.wrappedBuffer("co".getBytes());
FullHttpRequest request =
        new DefaultFullHttpRequest(
            HttpVersion.HTTP_1_1,
            methodType,
            uri,
            content);
setContentType(request, protoRequest);
logger.info(request.method().toString());
logger.info(request.toString());
```
```
public class HttpProxyChannelPoolHandler extends BaseChannelPoolHandler {

  @Override
  public void initialisePipeline(Channel channel) {
    ChannelPipeline pipeline = channel.pipeline();
    pipeline.addLast("idleHandler", new IdleStateHandler(0, 0, 60));
    pipeline.addLast("httpCodec", new HttpClientCodec());
    //    1 MB
    pipeline.addLast("aggregator", new HttpObjectAggregator(1024 * 1024));
    pipeline.addLast(HTTP_PROXY_HANDLER, new HttpProxyChannelHandler());
  }
}
```

#### Server Side
HttpHandler.java
```
public class HttpHandler extends ChannelInboundHandlerAdapter {

private final Router router;

  public HttpHandler(
      Router router) {
    this.router = router;
  }

  @Override
  public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
    logger.debug("Starting Channel Read");
    if (!(msg instanceof FullHttpRequest)) {
      throw new IllegalArgumentException("This handler can only handle http requests");
    }

    FullHttpRequest request = (FullHttpRequest) msg;
    logger.info("-------##########----------");
    logger.info(request.method().toString());
    logger.info(request.uri() + " __ " + request.content().readableBytes());
    logger.info(request.content().toString());
    logger.info(request.toString());
    logger.info("----------********--------------");
  }
}

```

```
public class MyInitializer extends ChannelInitializer<Channel> {

  private final HttpHandler httpHandler;

  @Inject
  public Initializer(HttpHandler httpHandler) {
    this.httpHandler = httpHandler;
  }

  @Override
  protected void initChannel(Channel ch) throws Exception {
    ChannelPipeline pipeline = ch.pipeline();
    pipeline.addLast("httpCodec", new HttpServerCodec());
    pipeline.addLast("chunkAggregator", new HttpObjectAggregator(5120000));
    pipeline.addLast("httpHandler", httpHandler);
  }
}
```

#### Client output:
```
2019-09-18 12:27:28 [core-thread-3] INFO  c.u.s.g.s.i.BiDiHttpRequestHandler - GET
2019-09-18 12:27:28 [core-thread-3] INFO  c.u.s.g.s.i.BiDiHttpRequestHandler - DefaultFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 2, cap: 64))
GET /users/072cb3ed-27bf-436d-aa38-309c0280a3d4/mailboxes HTTP/1.1
header1: value1
Content-Type: application/json
```
Here the method type is **GET** as expected.

#### Server output
```
.12:40:43.503 [core-thread-5] INFO - coGET
.12:40:43.503 [core-thread-5] INFO - /users/072cb3ed-27bf-436d-aa38-309c0280a3d4/mailboxes __ 0
.12:40:43.503 [core-thread-5] INFO - CompositeByteBuf(ridx: 0, widx: 0, cap: 0, components=0)
.12:40:43.503 [core-thread-5] INFO - HttpObjectAggregator$AggregatedFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 0, cap: 0, components=0))
coGET /users/072cb3ed-27bf-436d-aa38-309c0280a3d4/mailboxes HTTP/1.1
Content-Type: application/json
header1: value1
content-length: 0
```
Here the method is **coGET**, the body was appended to the method.

### Netty version
4.1.15

### JVM version (e.g. `java -version`)
penjdk version "1.8.0_212"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b04, mixed mode)

### OS version
Mac OS Mojave 10.14.6 (18G95)

**Comment by amizurov** [comment]
Hi, it's expected behavior  see 
https://github.com/netty/netty/blob/72716be648cce725590259305e63f39f12742c7e/codec-http/src/main/java/io/netty/handler/codec/http/HttpObjectAggregator.java#L230-L242

**Comment by nikhilvavs** [comment]
Hi @sprsquish ,
The problem is not that content length header is being set. It is that the content gets appended to the method type.
So, the method type becomes **coGET** instead of **GET**

**Comment by amizurov** [comment]
Oh, sorry missed `coGET`, could you please provide minimal reproducer, I wrote simple example and everything work properly if you not set manually `coGET` method.

**Comment by normanmaurer** [comment]
@nikhilvavs please provide a re-producer and re-open if you still think there is an issue. I could not find any in the implementation by looking through it (which may still not mean there is none).

**Comment by normanmaurer** [comment]
Also please update to latest netty version as your version is very old.
