### ISSUE TITLE
the memory size of the channel increases When the channel is closed and connected again

### ISSUE THREAD

**Issue by zhanfffmmm** [netty/netty#9594]
### Expected behavior

the memory size of the channel should remain unchanged When the channel is closed and connected again 

### Actual behavior

the memory size of the channel increases When the channel is closed and connected again

### Steps to reproduce
the client  connect , i put the channel to map,
when the  client  close,i remove the channel for map,
i found this channel memory size to increases in the map when the  other  client connect,i put the channel to map

### Minimal yet complete reproducer code (or URL to code)
private static Map<String, Channel> map = new ConcurrentHashMap<String, Channel> ();
map.put("1",channel);
map.remove("1");
map.put("1",channel);

## test tools
Instrumentation

### Netty version 
4.1.41

### JVM version (e.g. `java -version`)
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

### OS version (e.g. `uname -a`)
centos7 and windows10

**Comment by normanmaurer** [comment]
In Netty it is not possible to re-connect a Channel. Once it is closed it will remain closed, so I am not sure what you do... You will need to provide more details and a reproducer.

**Comment by zhanfffmmm** [comment]
step 1: the server to start and the client to connect, this channel   memory size is 3255192
step 2: step 1 the client  close , and then the other client to connect to server, this channel memory size is 3826360

## test java tool
package com.zb.objectsizeof;

import java.lang.instrument.Instrumentation;
import java.lang.reflect.Array;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.IdentityHashMap;
import java.util.Map;
import java.util.Stack;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SizeOfAgent {
	
	private static final Logger log = LoggerFactory.getLogger(SizeOfAgent.class);

	 static Instrumentation instrumentation;
	 
	   
	    public static void premain(String agentArgs, Instrumentation instP) {
	        instrumentation = instP;
	    }
	 
	   
	    public static long sizeOf(Object o) {
	        if (instrumentation == null) {
	            throw new IllegalStateException("Can not access instrumentation environment.\n" +
	                    "Please check if jar file containing SizeOfAgent class is \n" +
	                    "specified in the java's \"-javaagent\" command line argument.");
	        }
	        return instrumentation.getObjectSize(o);
	    }
	 
	    /**
	     *
	     * 
	     * @param obj object to calculate size of
	     * @return object size
	     */
	    public static long fullSizeOf(Object obj) {
	        Map<Object, Object> visited = new IdentityHashMap<Object, Object>();
	        Stack<Object> stack = new Stack<Object>();
	 
	        long result = internalSizeOf(obj, stack, visited);
	        int i = 1;
	        while (!stack.isEmpty()) {
	        	//log.info("stack {} object size:{}",i, stack.size());
	            result += internalSizeOf(stack.pop(), stack, visited);
	            i++;
	           
	        }
	        visited.clear();
	        log.info(" size result :{}", result);
	        return result;
	    }
	 
	    // 
	    private static boolean skipObject(Object obj, Map<Object, Object> visited) {
	        if (obj instanceof String) {
	            // 
	            if (obj == ((String) obj).intern()) {
	                return true;
	            }
	        }
	        return (obj == null) // 
	                || visited.containsKey(obj);
	    }
	 
	    private static long internalSizeOf(Object obj, Stack<Object> stack,  Map<Object, Object> visited) {
	 
	    	
	    	
	        if (skipObject(obj, visited)){
	            return 0;
	        }
	        
	        //stack.forEach((e)->log.info("class: {}",e.getClass()));
	        
	        visited.put(obj, null);
	 
	        long result = 0;
	        // get size of object + primitive variables + member pointers
	        result += SizeOfAgent.sizeOf(obj);
	 
	        // 
	        Class clazz = obj.getClass();
	        log.info("class: {}",clazz);
	        if (clazz.isArray()) {
	            //
	            if(clazz.getName().length() != 2) {// skip primitive type array
	                int length =  Array.getLength(obj);
	                for (int i = 0; i < length; i++) {
	                    stack.add(Array.get(obj, i));
	                }
	            }
	            return result;
	        }
	 
	        // 
	        while (clazz != null) {
	            Field[] fields = clazz.getDeclaredFields();
	            for (int i = 0; i < fields.length; i++) {
	                // 
	                if (!Modifier.isStatic(fields[i].getModifiers())) {
	                    // 
	                    if (fields[i].getType().isPrimitive()) {
	                        continue;
	                    } else {
	                        // 
	                        fields[i].setAccessible(true);
	                        try {
	                            // objects to be estimated are put to stack
	                            Object objectToAdd = fields[i].get(obj);
	                            if (objectToAdd != null) {
	                                stack.add(objectToAdd);
	                            }
	                        } catch (IllegalAccessException ex) {
	                            assert false;
	                        }
	                    }
	                }
	            }
	            clazz = clazz.getSuperclass();
	        }
	        return result;
	    }
}
## detail code 
public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
        SizeOfAgent.fullSizeOf(ctx.channel())) //step 1 channel  memory size is 3255192
                                                                         //step 2 channel  memory size is 3826360
}

**Comment by zhanfffmmm** [comment]
Is there a problem with my calculation? @normanmaurer 
i need to save the channel in my project. i hope can you help me?
thanks

**Comment by normanmaurer** [comment]
@zhanfffmmm sorry I am quite busy atm so did not have time yet to check. That said I would suggest taking heap-dumps and using some heap-dump analyzer to understand how much memory is used by an instance of a class.

**Comment by normanmaurer** [comment]
@zhanfffmmm did you try my suggestions ?

**Comment by zhanfffmmm** [comment]
@normanmaurer  sorry, I Still analyzing the problem when i try your suggestions.
