### ISSUE TITLE
How to release pooled direct buffer when it doesn't enter in channel pipline? 

### ISSUE THREAD

**Issue by lanxia** [netty/netty#9622]
We built up a very sophisticated proxy based on Netty. Considering the performance issue, we using pooled direct buffer to store user request and corresponding response. Unfortunately we have a memory leak and we hunt it for months. And finally we found it may be caused by this scenario: 
when the request or response is too large, we will set channel.auto_read to false. And if the connection is lost, we doubt the direct buffer not entering the pipeline is not correctly be released. So, is there any method to deal with these buffer ?

### Netty version
4.1.8.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

### OS version (e.g. `uname -a`)
Linux xxx(hostname) 2.6.32_1-19-0-0 #2 SMP Wed Aug 31 20:43:21 CST 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
You will need to share some code before we can help. There should be no leaks.

**Comment by normanmaurer** [comment]
Closing for now... please reopen if you still think there is any issue.
