### ISSUE TITLE
When Will Netty HTTP/2 Multiplexing Become Stable?

### ISSUE THREAD

**Issue by hyperxpro** [netty/netty#9633]
### Netty version
Netty 4.1.42.Final

### OS version (e.g. `uname -a`)

Http2MultiplexHandler is still having @UnstableApi Annotation. When will Http2MultiplexHandler become Stable? Can I use Http2MultiplexHandler in Production Systems as of now if needed? Is it safe?

**Comment by TristanPerry** [comment]
`@UnstableApi` is on pretty much every class in the http2 codec (on `4.1` and `master` branches). But despite its name, it doesn't mean that it's not production ready.

YMMV but from my experience, `Http2MultiplexHandler` is fine to use in production.

In terms of when the annotation will be removed, I thought I read that it would be removed in Netty 5 but I can't find that now. https://github.com/netty/netty/issues/8185 hasn't been updated in a while but it has a bit more info.

**Comment by hyperxpro** [comment]
Thanks!

**Comment by hyperxpro** [comment]
> `@UnstableApi` is on pretty much every class in the http2 codec (on `4.1` and `master` branches). But despite its name, it doesn't mean that it's not production ready. It just means that it could be refactored in a future release, meaning that you need to pay attention to release notes when upgrading:
> 
> > `@UnstableApi` Indicates a public API that can change at any time (even in minor/bugfix releases).
> 
> YMMV but from my experience, `Http2MultiplexHandler` is fine to use in production.
> 
> In terms of when the annotation will be removed from the HTTP2 codec, #8552 and #8185 touch on it a bit.

Thanks!

**Comment by normanmaurer** [comment]
Dup of https://github.com/netty/netty/issues/8185

**Comment by hyperxpro** [comment]
> Dup of #8185

I hope it get stable soon. :-)

**Comment by hyperxpro** [comment]
> Dup of #8185

I hope it gets stable soon. :-)
