### ISSUE TITLE
ByteToMessageDecoder Optimization

### ISSUE THREAD

**Issue by SteNicholas** [netty/netty#9637]
Netty provides a convenient decoding tool class ByteToMessageDecoder, this class has accumulate bulk unpacking capability, can read bytes from the socket as much as possible, and then synchronously call the decode method to decode the business object. And compose a List. Finally, the traversal traverses the List and submits it to ChannelPipeline for processing. Here we made a small change, as shown in the bottom half of the figure, the content to be submitted is changed from a single command to the entire List, which reduces the number of pipeline executions and improves throughput. This mode has no advantage in low-concurrency scenarios, and has a significant performance boost in boost throughput in high-concurrency scenarios.
[AbstractBatchDecoder](https://github.com/sofastack/sofa-bolt/blob/master/src/main/java/com/alipay/remoting/codec/AbstractBatchDecoder.java) is the optimization of ByteToMessageDecoder.
@normanmaurer Can you answer this issue?

**Comment by normanmaurer** [comment]
@SteNicholas can you open a PR against `ByteToMessageDecoder` with the changes? Seems like `AbstractBatchDecoder` is mostly identically here so maybe we could just modify `ByteToMessageDecoder` directly.

**Comment by SteNicholas** [comment]
@normanmaurer I have already opened a PR against `ByteToMessageDecoder` with chanages.Please review these changes,thanks.

**Comment by azzahrah** [comment]
Mybe this small code change, always check size before call fireChannelRead, correct me please
//Original
`int size = out.size();
                firedChannelRead |= out.insertSinceRecycled();
                fireChannelRead(ctx, out, size);
                out.recycle();
`
//Modified
`int size = out.size();
                if (size == 0) {
                    decodeWasNull = true;
                } else if (size == 1) {
                    ctx.fireChannelRead(out.get(0));
                } else {
                    ArrayList<Object> ret = new ArrayList<Object>(size);
                    for (int i = 0; i < size; i++) {
                        ret.add(out.get(i));
                    }
                    ctx.fireChannelRead(ret);
                }

                out.recycle();`

**Comment by SteNicholas** [comment]
@azzahrah Yeah, channelRead use batch way to improve performance.

**Comment by normanmaurer** [comment]
Let me close this and lets discuss on the proposed PR.
