### ISSUE TITLE
How to Specify SecureRandom in SslContext?

### ISSUE THREAD

**Issue by hyperxpro** [netty/netty#9638]
### Netty version
4.1.42.Final
### JVM version (e.g. `java -version`)
openjdk version "11.0.4" 2019-07-16 LTS
### OS version (e.g. `uname -a`)
Windows 10 Pro x64

I'm looking for way to integrate custom SecureRandom in SslContext of Netty but unable to find anyway. Can anyone help?

**Comment by slandelle** [comment]
AFAIK, providing your own SecureRandom would only make sense for JDK based SslContext implementation and not for OpenSSL based one.
Currently, SslContextBuilder is very generic and doesn't take parameters that are specific to a given implementation.
The only way would be to build your own `java.net.ssl.SSLContext` and pass your SecureRandom to `init` and then wrap into Netty's `JdkSslContext`.

**Comment by hyperxpro** [comment]
> AFAIK, providing your own SecureRandom would only make sense for JDK based SslContext implementation and not for OpenSSL based one.
> Currently, SslContextBuilder is very generic and doesn't take parameters that are specific to a given implementation.
> The only way would be to build your own `java.net.ssl.SSLContext` and pass your SecureRandom to `init` and then wrap into Netty's `JdkSslContext`.

If I warp SSLContext to Netty JdkSslContext then I will lose OpenSSL Performance Benefits. Is my understanding correct?

**Comment by slandelle** [comment]
I think @normanmaurer would agree this can be closed and such questions are better asked on StackOverFlow than on this bug tracker.

**Comment by normanmaurer** [comment]
As @slandelle said... Closing

**Comment by hyperxpro** [comment]
TBH, Support is really rude here. Never mind.
