### ISSUE TITLE
Netty SslContext Client SNI

### ISSUE THREAD

**Issue by hyperxpro** [netty/netty#9643]
### Expected behavior
SslContext forClient Sending SNI to Server
### Actual behavior
SslContext forClient not Sending SNI to Server
### Steps to reproduce
Just create a normal Netty HTTPS Client and Capture TLS Client Hello Packet
### Netty version
4.1.42.Final
### JVM version (e.g. `java -version`)
openjdk version "11.0.4" 2019-07-16 LTS
### OS version (e.g. `uname -a`)
Windows 10 Pro x64

Why Netty SslContext forClient doesn't include "server_name" TLS Extension in Client Hello?

**Comment by normanmaurer** [comment]
How you create the `SslHandler` / `SslEngine` ? You need to use the method that will take a hostname / port as well as argument.

**Comment by hyperxpro** [comment]
> How you create the `SslHandler` / `SslEngine` ? You need to use the method that will take a hostname / port as well as argument.

I'm using typical SslContext with SslContextBuilder.
SslContext sslCtx = SslContextBuilder.forClient().build();

I don't wanna use SSLEngine (javax.net.ssl.SSLEngine) because of obvious reasons. Help, please?

**Comment by normanmaurer** [comment]
@hyperxpro I am interested in how you use the `SslContext` later on .

**Comment by hyperxpro** [comment]
> @hyperxpro I am interested in how you use the `SslContext` later on .

        System.setProperty("jsse.enableSNIExtension", "true");
        EventLoopGroup childGroup = new NioEventLoopGroup();
        
        SslContext sslCtx = SslContextBuilder.forClient().build();

        Bootstrap bootstrap = new Bootstrap();
        bootstrap.group(childGroup)
                .channel(NioSocketChannel.class)
                .handler(new SimpleChannelInboundHandler<>() {
                    @Override
                    protected void channelRead0(ChannelHandlerContext ctx, Object msg) throws Exception {
                        // JUST RANDOM CODE TO MAKE TLS REQUEST
                        FullHttpRequest fullHttpRequest = new DefaultFullHttpRequest(HTTP_1_1, HttpMethod.GET, "/", Unpooled.EMPTY_BUFFER);
                        ctx.writeAndFlush(fullHttpRequest);
                    }
                });

        Channel ch = bootstrap.connect(new InetSocketAddress("facebook.com", 443)).sync().channel();
        ch.pipeline().addFirst(sslCtx.newHandler(ch.alloc()));

**Comment by hyperxpro** [comment]
I am able to send SNI using SSLParameters in SSL Engine. Is this the correct way? And Will I get OpenSSL Provider using this code?

        // EventLoop
        EventLoopGroup childGroup = new NioEventLoopGroup();

        // SSL Parameters to set SNI TLS Extension
        SSLParameters sslParameters = new SSLParameters();
        sslParameters.setServerNames(Collections.singletonList(new SNIHostName("facebook.com")));

        // Build SSLContext for Client
        SslContext sslContext = SslContextBuilder.forClient().sslProvider(SslProvider.OPENSSL).build();

        // SSLEngine with SSL Parameters for SNI
        SSLEngine sslEngine = sslContext.newEngine(ByteBufAllocator.DEFAULT);
        sslEngine.setSSLParameters(sslParameters);

        // SSL Handler
        SslHandler sslHandler = new SslHandler(sslEngine);

        Bootstrap bootstrap = new Bootstrap();
        bootstrap.group(childGroup)
                .channel(NioSocketChannel.class)
                .handler(new SimpleChannelInboundHandler<>() {
                    @Override
                    protected void channelRead0(ChannelHandlerContext ctx, Object msg) throws Exception {
                        // JUST RANDOM CODE TO MAKE TLS REQUEST
                        FullHttpRequest fullHttpRequest = new DefaultFullHttpRequest(HTTP_1_1, HttpMethod.GET, "/", Unpooled.EMPTY_BUFFER);
                        ctx.writeAndFlush(fullHttpRequest);
                    }
                });

        Channel ch = bootstrap.connect(new InetSocketAddress("facebook.com", 443)).sync().channel();
        ch.pipeline().addFirst(sslHandler);

**Comment by normanmaurer** [comment]
@hyperxpro yes this should work...  Alternative you can also use:

```
sslContext.newHandler(allocator, "facebook.com", 443);
```

**Comment by hyperxpro** [comment]
> @hyperxpro yes this should work... Alternative you can also use:
> 
> ```
> sslContext.newHandler(allocator, "facebook.com", 443);
> ```

If I specify Host "google.com" instead of "facebook.com" in 
```
sslContext.newHandler(allocator, "facebook.com", 443);
```
but connect to "www.shieldblaze.com". Will SslContext respect Bootstrap connect or the Peer Host and Port which I specified in Handler?
```
Channel ch = bootstrap.connect(new InetSocketAddress("facebook.com", 443)).sync().channel();
```

I am building HTTPS Inspection Application so I need to customize SNI. 

However, thanks a lot for the help so far!

**Comment by hyperxpro** [comment]
> @hyperxpro yes this should work... Alternative you can also use:
> 
> ```
> sslContext.newHandler(allocator, "facebook.com", 443);
> ```

If I specify Host "google.com" instead of "facebook.com" in 
```
sslContext.newHandler(allocator, "google.com", 443);
```
but connect to "www.shieldblaze.com". Will SslContext respect Bootstrap connect or the Peer Host and Port which I specified in Handler?
```
Channel ch = bootstrap.connect(new InetSocketAddress("facebook.com", 443)).sync().channel();
```

I am building HTTPS Inspection Application so I need to customize SNI. 

However, thanks a lot for the help so far!

**Comment by hyperxpro** [comment]
> @hyperxpro yes this should work... Alternative you can also use:
> 
> ```
> sslContext.newHandler(allocator, "facebook.com", 443);
> ```

> @hyperxpro yes this should work... Alternative you can also use:
> 
> ```
> sslContext.newHandler(allocator, "facebook.com", 443);
> ```

If I specify Host "google.com" instead of "facebook.com" in 
```
sslContext.newHandler(allocator, "google.com", 443);
```
but connect to "www.shieldblaze.com". Will SslContext respect Bootstrap connect or the Peer Host and Port which I specified in Handler?
```
Channel ch = bootstrap.connect(new InetSocketAddress("www.shieldblaze.com", 443)).sync().channel();
```

I am building HTTPS Inspection Application so I need to customize SNI. 

However, thanks a lot for the help so far!

**Comment by hyperxpro** [comment]
> @hyperxpro yes this should work... Alternative you can also use:
> 
> ```
> sslContext.newHandler(allocator, "facebook.com", 443);
> ```

If I specify Host "google.com" instead of "facebook.com" in 
```
sslContext.newHandler(allocator, "google.com", 443);
```
but connect to "www.shieldblaze.com". Will SslContext respect Bootstrap connect or the Peer Host and Port which I specified in Handler?
```
Channel ch = bootstrap.connect(new InetSocketAddress("www.shieldblaze.com", 443)).sync().channel();
```

I am building HTTPS Inspection Application so I need to customize SNI. 

However, thanks a lot for the help so far!

**Comment by hyperxpro** [comment]
Solved!
