### ISSUE TITLE
Add proper support for TCP Fast Open in native transport

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#9651]
We currently support to set the TCP_FAST_OPEN `ChannelOption` in our native epoll transport.  While this is generally good enough for servers it is not good enough for client-side usage. Here we will need to introduce the usage of `sendto(...)` to replace the usage of `connect(...)` when TCP_FAST_OPEN is used.

See https://lwn.net/Articles/508865/

**Comment by colinrgodsey** [comment]
Going to take a crack at this today

**Comment by colinrgodsey** [comment]
I'm guessing we'll have to let the channel connect 'optimistically' succeed until data is first sent. Kind of necessary to allow the '0RTT' transmission there.

**Comment by colinrgodsey** [comment]
Now I'm getting all hung up trying to figure out how to handle TCP_FASTOPEN_CONNECT vs TCP_FASTOPEN... there doesn't seem to be any way to test for TCP_FASTOPEN_CONNECT support. I wonder if its worth just replacing the TCP_FASTOPEN_CONNECT functionality with the classic TCP_FASTOPEN? The _CONNECT form seems to just be boilerplate to make workflow with TCP_FASTOPEN easier. Netty users will be blind to the underlying implementation anyways (also, the TCP_FASTOPEN channel open is an Integer types which makes it kind of odd with the client implementation, as there's no threshold).

**Comment by colinrgodsey** [comment]
I've got this far: https://github.com/netty/netty/compare/4.1...colinrgodsey:4.1 

Code format clobbered some random things, so need to fix that... plus some other cleanup, and some new tests.

**Comment by colinrgodsey** [comment]
(sorry, just journaling things here...)

Yea, I really think hijacking TCP_FASTOPEN_CONNECT is the best option. There's not actually a socket flag for client fast open anyways, its just a special flag on "sendto". While it's kind of a "lie" that we're not actually using the new TCP_FASTOPEN_CONNECT flag, we are effectively doing the same thing (from what I can tell in the kernel code, the end effects are reasonably identical). So this extends existing functionality without introducing any visible API changes.

**Comment by colinrgodsey** [comment]
Works now, getting through tests.... seems to be some weirdness with LEVEL_TRIGGERED epoll, and one of the connect tests (doesnt like the empty local address)

**Comment by colinrgodsey** [comment]
Alright, so I added client fast open to the epoll permutations and.... lots of things are failing. The normal data transmission pattern stuff works, so thats good (overall write pattern works), but it seems to failing with some of the epoll trigger mechanics and connection mechanics. not surprising about the connection mechanics, this does ultimately change how all of that works. still working through the tests

**Comment by colinrgodsey** [comment]
Alright, so... some things to consider:

a) Should TCP_FASTOPEN_CONNECT be replaced with the more-compatible sendto/sendmsg form.
b) TCP_FASTOPEN_CONNECT doesn't seem to have been in any tests, and it likely exhibits the same behavior issues as the other form, but not sure. 
c) Should the behavior changes be considered "expected", and a normal caveat of the feature? (it is after all a stateless connection). These caveats can be handled piecemeal in the Epoll test suite to help further cement which behaviors are expected to be violated. 

Personally, I think it's best to leave the fastopen behavior in the epoll permutations, and for each test case that is violated by the fastopen behavior, provide a different EpollSocketTestPermutation that leaves out the fastopen client. That way its searchable and can be used as a definitive source for producing a list of 'caveats' for TCP client fastopen.
