### ISSUE TITLE
Cache SelectorProvider is not suitable for NioServerSocketChannel

### ISSUE THREAD

**Issue by brucelwl** [netty/netty#9660]
I found the issue https://github.com/netty/netty/issues/2308 saying that calling ``SelectorProvider#provider`` for every new channel creation causes performance problems，So the ``SelectorProvider`` is cached. But cache ``SelectorProvider`` is not suitable for ``NioServerSocketChannel``, because ``NioServerSocketChannel`` will only be created once, it will not be created many times like ``NioSocketChannel``, caching ``SelectorProvider`` in ``NioServerSocketChannel`` is instead a memory consumption.

**Comment by johnou** [comment]
How does it cause unnecessary memory overhead when it is a static field?

**Comment by normanmaurer** [comment]
Also an application may create multiple server channels

**Comment by brucelwl** [comment]
@normanmaurer Maybe it's not good enough for me to describe. Although an application can create multiple server channels, it is definitely not a lot of concurrent creation. So there is no need to use static fields to store ``SelectorProvider``, because static fields themselves need to occupy memory, even though this memory Occupied very small. But when the application is started, ``SelectorProvider`` is no longer used for ``NioServerSocketChannel``,but it will always occupy memory, I personally think it is a waste of resources.

**Comment by johnou** [comment]
Unless it's a measurable difference in memory footprint I would leave it as is, consider the Netty test-suite which creates and tears down thousands of server channels..

**Comment by normanmaurer** [comment]
I agree with @johnou . Lets keep the code as it is.
