### ISSUE TITLE
The expansion of the WeakOrderQueue$Link volume caused memory leaks.

### ISSUE THREAD

**Issue by carryxyh** [netty/netty#9665]
Hi, 
Recently we discovered that there is a similar memory overlap problem with one of our HTTP servers.

Our bootstrap is here:

![image](https://user-images.githubusercontent.com/12047600/66798164-bfb81080-ef3f-11e9-88dd-316e7435f9f6.png)

The memory looks like this(keep increasing until 90%):

![image](https://user-images.githubusercontent.com/12047600/66798187-cd6d9600-ef3f-11e9-8f27-9186f0fdd17a.png)

When I open jprofiler for some info, I found that the `WeakOrderQueue$Link` and `DefaultHandle[]` instance count is very big and keep increasing, another thing, `DefaultHandle` instance counts is not very big, pic is here(this pic is last night's data):

![image](https://user-images.githubusercontent.com/12047600/66798312-263d2e80-ef40-11e9-90a4-aa49de057643.png)

I keep send http request to this server for one night, this is the heap memory info this morning:

![image](https://user-images.githubusercontent.com/12047600/66798447-91870080-ef40-11e9-80b5-3f5f18aa7971.png)

Looks like `WeakOrderQueue$Link` and `DefaultHandle[]` will always increase...

It looks like the root cause is `WeakOrderQueue$Link`'s leak.  Find `incoming references` for `WeakOrderQueue$Link`:

![image](https://user-images.githubusercontent.com/12047600/66798533-df036d80-ef40-11e9-9305-0605bfe283a1.png)

Since the `Head` override `finalize` method, is this cause a memory leak? 

I find a explain at stackoverflow: https://stackoverflow.com/questions/8355064/is-memory-leak-why-java-lang-ref-finalizer-eat-so-much-memory

Is this a real leak problem? If not, how can I avoid it...

### Netty version
4.1.42.Final

**Comment by carryxyh** [comment]
By the way, close `Recycler` will solve this problem:

![image](https://user-images.githubusercontent.com/12047600/66807949-c903a600-ef5c-11e9-8ed3-8bdbbb8c2f4f.png)

Memory usage is stable and won't increase.

**Comment by normanmaurer** [comment]
@carryxyh can you share the heap dump for when the problem encounters ?

**Comment by normanmaurer** [comment]
@carryxyh ping :)

**Comment by carryxyh** [comment]
Hi, norman, sorry for late.
I keep sending http request for one night, it occurs again:

![image](https://user-images.githubusercontent.com/12047600/67447521-bd903900-f646-11e9-8eb7-6a68c7d79919.png)

I will send heap dump to u soon. Thx for your reply.

**Comment by carryxyh** [comment]
@normanmaurer 

Hi, I sent an email to you(norman_maurer@apple.com) since the dump file is a little big.
Please pay attention to check.

**Comment by normanmaurer** [comment]
Will do... I suspect you can’t share the reproducer code ?

**Comment by carryxyh** [comment]
No, I can't...
This part of the code is internal to our company.

**Comment by normanmaurer** [comment]
@carryxyh ok ... that was what I suspected.

**Comment by carryxyh** [comment]
After investigation, it was not a leak. 

The program can perform GC normally to ensure that no OOM occurs. Regarding the memory usage of 6G, this is because the JVM applied for 6G memory but did not return them to the system.

Thanks to Norman for help and remind us to use a custom ThreadFactory. :)

**Comment by carryxyh** [comment]
More details:

Run Full GC with jprofile remoting attach. Seems that the number of 'Link' decrease. That indicated this isn't a leak problem.

![image](https://user-images.githubusercontent.com/12047600/67647334-e711d300-f96c-11e9-854c-31a227e03266.png)

The 'top' command:

![image](https://user-images.githubusercontent.com/12047600/67647394-23ddca00-f96d-11e9-9e9e-a4b0314ecfe1.png)

Still cost 6G memory. This is because the JVM applied for 6G memory but did not return them to the system.

I also let this application run for one night, I found three times Full GC and all of them can collect unusage memory, this is two of them:

![image](https://user-images.githubusercontent.com/12047600/67647449-5c7da380-f96d-11e9-859c-bafca9bfaac8.png)

![image](https://user-images.githubusercontent.com/12047600/67647454-5edffd80-f96d-11e9-816c-ab05c7dd4105.png)

Pull request for optimize:
https://github.com/netty/netty/pull/9713

**Comment by carryxyh** [comment]
Another pull request that maybe optimize this situation:
https://github.com/netty/netty/pull/9727
