### ISSUE TITLE
FlowControllerHandler swallows read-complete event when auto-read is disabled

### ISSUE THREAD

**Issue by ursaj** [netty/netty#9667]
### Expected behavior

IdleStateHandler should trigger read-timeout events when registered after FlowControlHandler.

### Actual behavior

IdleStateHandler does NOT trigger read-timeout event.

### Steps to reproduce

Server pipeline:

    p.addLast("flow-control", new FlowControlHandler)
    p.addLast("keep-alive", new PingInactiveHandler(readTimeout))// extends IdleStateHandler
    p.addLast("handler", new AppHandler) // trigger read

When no upstream messages from the client within time limit, then READER_IDLE event should be triggered. However it does NOT happen.

### Netty version

* Version 4.1.31 - no problem, example code works.
* Version 4.1.39 - has a problem, example code does NOT work.

Seems like related to PR #9664 

### JVM version (e.g. `java -version`)

Oracle JDK 1.8.0_221-b27

### OS version (e.g. `uname -a`)

* Windows  7 Enterprise
* Linux gmafxu42 3.0.101-108.98-default #1 SMP Mon Jul 15 13:58:06 UTC 2019 (262a94d) x86_64 x86_64 x86_64 GNU/Linux

### How to fix

    @Override
    public void channelReadComplete(ChannelHandlerContext ctx) throws Exception {
    ---    // Don't relay completion events from upstream as they
    ---    // make no sense in this context. See dequeue() where
    ---    // a new set of completion events is being produced.
    +++    if (isQueueEmpty()) {
    +++        ctx.fireChannelReadComplete();
    +++    }
    }

**Comment by normanmaurer** [comment]
@ursaj sounds legit. Want to do a PR ?
