### ISSUE TITLE
@normanmaurer I find that when I write   httpTohttp2  client ,I use 10 threads to  send  http message ,server accept every Http2HeadersFrame message,and sometime  lost some Http2DataFrame message,Client log also dispaly that some outbound message is not write.

### ISSUE THREAD

**Issue by joachern** [netty/netty#9675]
@normanmaurer I find that when I write   httpTohttp2  client ,I use 10 threads to  send  http message ,server accept every Http2HeadersFrame message,and sometime  lost some Http2DataFrame message,Client log also dispaly that some outbound message is not write.

Would you please give some suggest? Thank you 
### Thread code
         for(int i=0;i<10 ;i++)          // 10 Tread
            {
                URI uriSimple = new URI("http://127.0.0.1:8080/postfile333"+"?+id="+i);
            	TaskFile taskFile =    new TaskFile(  streamId+2*i,  responseHandler, channel ,   uriSimple,   file1,   factory );
         //   EventLoopGroup workerGroup = new NioEventLoopGroup();
            	workerGroup.next().execute(taskFile);  
            }
### Main Task Code
                 HttpScheme scheme =  HttpScheme.HTTP;
	        AsciiString hostName = new AsciiString(HOST + ':' + PORT);
	        HttpRequest request = new DefaultHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.POST, uriSimple.toASCIIString());
	        HttpHeaders headers = request.headers();
	        headers.add(HttpHeaderNames.HOST, hostName);
	        headers.add(HttpConversionUtil.ExtensionHeaderNames.SCHEME.text(), scheme.name());
	        headers.add(HttpHeaderNames.ACCEPT_ENCODING, HttpHeaderValues.GZIP);
	        headers.add(HttpHeaderNames.ACCEPT_ENCODING, HttpHeaderValues.DEFLATE);
	        headers.set(HttpHeaderNames.ACCEPT, "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8");
	    		HttpPostRequestEncoder bodyRequestEncoder;
				bodyRequestEncoder = new HttpPostRequestEncoder(factory, request, true);
				bodyRequestEncoder.addBodyAttribute("getform", "luAAAAAAAAAaa");			
				bodyRequestEncoder.addBodyAttribute("info", "first valuAAAAAe");
			 bodyRequestEncoder.addBodyFileUpload("myfile", file, "application/x-zip-compressed", false);
	        // finalize request
	        request = bodyRequestEncoder.finalizeRequest();        
	        channel.writeflush( request,);
	        if (bodyRequestEncoder.isChunked()) { // could do either request.isChunked()
	        	channel.writeflush( bodyRequestEncoder);
	        	
	        }
	      
	        bodyRequestEncoder.cleanFiles();
	        bodyRequestEncoder.close();

_Originally posted by @joachern in https://github.com/netty/netty/issues/9573#issuecomment-542464237_

**Comment by joachern** [comment]
@normanmaurer  I see the code  HttpToHttp2ConnectionHandler not support muiltyThread 。
Is the reason？

    private int getStreamId(HttpHeaders httpHeaders) throws Exception {
        return httpHeaders.getInt(HttpConversionUtil.ExtensionHeaderNames.STREAM_ID.text(),
                                  connection().local().incrementAndGetNextStreamId());
    }

**Comment by joachern** [comment]
Now I find that   write thread lose some message 
It shows that some message are losed before writeflush.

**Comment by joachern** [comment]
I got Solution 

 public   void  addRequest(String id, Channel channel, HttpRequest request,HttpPostRequestEncoder bodyRequestEncoder)
    {
    	try
		{
		lock.lock();
    	ChannelFuture future;
    	if(bodyRequestEncoder!=null)
    	{
    		 future = channel.writeAndFlush(request);
    		 channel.writeAndFlush(bodyRequestEncoder);
    	}else
    	{
    		  future = channel.writeAndFlush(request);
    	}
    	sendPromiseMap.put(id, new SimpleEntry<ChannelFuture, ChannelPromise>(future, channel.newPromise()));
		}finally
		{
			lock.unlock();
		}
    }

**Comment by normanmaurer** [comment]
Please use stackoverflow for questions
