### ISSUE TITLE
Can we run perfectly on JDK13

### ISSUE THREAD

**Issue by MrXionGe** [netty/netty#9677]
### Expected behavior
Perfect running on JDK13

### Actual behavior
Throw an IllegalAccessException

### Steps to reproduce
When using Vertx to create an HTTP client, netty-common throw an IllegalAccessException.
And the HTTP client cannot send the request.

### Minimal yet complete reproducer code (or URL to code)
Exception Message: "java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @7f552bd3"

### Netty version
4.1.42

### JVM version (e.g. `java -version`)
Oracle JDK13 64bit

### OS version (e.g. `uname -a`)
Windows10 64bit

**Comment by MrXionGe** [comment]
#### java -version
java version "13" 2019-09-17
Java(TM) SE Runtime Environment (build 13+33)
Java HotSpot(TM) 64-Bit Server VM (build 13+33, mixed mode, sharing)

**Comment by MrXionGe** [comment]
The same code can run on JDK12. I tried to upgrade Vertx to 4.0.0, but I got the same result.
I guess that exception caused the problem.

**Comment by MrXionGe** [comment]
This problem does not seem to be caused by netty.
On JDK13. I tried to use other components that depend on netty. E.g. WebFulx. The exception information mentioned above was also thrown, but the program itself did not go wrong.

**Comment by johnou** [comment]
are you running the JVM with `--add-exports=java.base/jdk.internal.misc=ALL-UNNAMED`?

**Comment by johnou** [comment]
Try setting your root logger log level to debug to see if there's another exception, currently Netty CI only builds against 8, 11 and 12.

It could also be an issue with Vertx, if changing the log level doesn't reveal anything please try creating a Netty only reproducer project you can share.
