### ISSUE TITLE
EpollEventLoopGroup slow shutdown regression

### ISSUE THREAD

**Issue by vietj** [netty/netty#9678]
### Expected behavior
`EpollEventLoopGroup` regular shutdown takes a few millis to complete.

### Actual behavior
`EpollEventLoopGroup` takes about 1 second to shutdown. This only apply since 4.1.42.Final, it might be related to https://github.com/netty/netty/commit/76592db0bde9d4908191c2d7e54af3466ffd4673#diff-824cfcec3522343772416dd064658a83

### Steps to reproduce
Shutdown an `EpollEventLoopGroup` and wait for its completion. We noticed it because Vert.x testsuite using Epoll on Linux takes much longer than usual (making timeout CI jobs).

### Minimal yet complete reproducer code (or URL to code)
Clone https://github.com/eclipse-vertx/vert.x and run `mvn test -PtestNativeTransport`

### Netty version
4.1.42.Final

### JVM version (e.g. `java -version`)
OpenJDK 8

### OS version (e.g. `uname -a`)
Linux XXX 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by njhill** [comment]
@vietj would you be able to try with the latest 4.1.43 snapshot? Some fixes have already gone in which hopefully address this.

**Comment by vietj** [comment]
sure, do you have snapshots published in sonatype OSS repository ?

**Comment by normanmaurer** [comment]
@vietj yes

**Comment by vietj** [comment]
awesome will give a run soon.

**Comment by vietj** [comment]
it does not seem to work for me at the moment, I'll report later

**Comment by normanmaurer** [comment]
@vietj let us know once you have any feedback to share

**Comment by vietj** [comment]
it works fine with latest 4.1..43.Final-SNAPSHOT https://travis-ci.org/vietj/vert.x/builds/599121826

**Comment by normanmaurer** [comment]
Ok cool then lets close this
