### ISSUE TITLE
Is it possible there is a NullPointerException in ChunkedWriteHandler.java?

### ISSUE THREAD

**Issue by ljnelson** [netty/netty#9680]
I am working with `ChunkedWriteHandler` and a `ChunkedInput` implementation.  I happened to notice this:

https://github.com/netty/netty/blob/3d7dba373fff33270a897a7de86f7311952301a2/handler/src/main/java/io/netty/handler/stream/ChunkedWriteHandler.java#L276-L288

The important lines are (in the permanent link above) 276 and 288.  Won't `currentWrite` at line 288 always be `null`?

I thought I would err on the side of filing this issue.  If this is not a bug I hope it is sufficiently clear to dismiss quickly and that I haven't wasted anyone's time.

This issue may indirectly relate to #303.

**Comment by normanmaurer** [comment]
@ljnelson no there is a different between `this.currentWrite` and `currentWrite`.
