### ISSUE TITLE
Netty SSLHandler uses large buffer in memory pool for small response data size

### ISSUE THREAD

**Issue by gmcatsf** [netty/netty#9685]
### Expected behavior
When server writes a lot of responses with small size to client though Netty, with SSLhandler in the pipeline, we would expect Netty memory pool would allocate size close to actual pending encrypted data size not sent to client yet.  

### Actual behavior
Large number of native memory is allocated in Netty memory pool which is not proportional to actual response size. Looking at the SSLHandler code, the buffer size is calculated by EngineType. 

https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L2152

For JDK EngineType, it always returns 16K regardless of response size. That means native memory pool will allocate 16K even if response size is 10 bytes.

https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L305

Since ByteBuf capacity is self-adjustable, it would expand if its initial capacity is less than necessary size to accommodate ssl result. If this is true, would it make more sense to allocate buffer with some size based on actual response size? I understand server can batch responses together, or throttle by channel.isWritable() to avoid creating new memory allocation, but it'd be great to avoid excessive memory.

### Steps to reproduce
1. Set up Netty server and client with SSL enabled.
2. Let server write and flush a lot of small 10-byte response.
3. Notice that SSLHandler.allocateOutNetBuf allocates 16K buffer in memory pool.

### Minimal yet complete reproducer code (or URL to code)
https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L305

### Netty version
4.1.36

### JVM version (e.g. `java -version`)
Java 9

### OS version (e.g. `uname -a`)
GNU/Linux

**Comment by normanmaurer** [comment]
@gmcatsf unfortunately there is not much we can do here as the `SSLEngineImpl` that is part of the JDK will tell us to increase the buffer anyway until it matches the packet size:

https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/master/src/java.base/share/classes/sun/security/ssl/SSLEngineImpl.java#L207

So the only advice I can give you is to use our native implementation aka `
netty-tcnative` or `netty-tcnative-boringssl-static`

**Comment by normanmaurer** [comment]
I think the only thing we could do is to allocate these as heap buffers to reduce the pressure on the native memory. Not sure this would help or not. You could already force this by creating your `ByteBufAllocator` which prefers heap buffers tho.

**Comment by gmcatsf** [comment]
@normanmaurer, thanks for the suggestion, yeah one solution I tried is to group bytes in heap before flushing to native memory, this avoids blowing up native memory. Native memory can get really big when there are a lots of fast and small writes, say 100K * 16K = 1.6GB.

**Comment by normanmaurer** [comment]
I have a change ready here... will cleanup and let you know once the PR is open

**Comment by normanmaurer** [comment]
@gmcatsf can you check https://github.com/netty/netty/pull/9696 ?
