### ISSUE TITLE
why  the code  occurs  Not Found  Package  class name?

### ISSUE THREAD

**Issue by LiujunjieALiling** [netty/netty#9686]
### Expected behavior
test DiscardClient, run  main method  expect build  passed
### Actual behavior
But Occurs Not Found Class  'LongObjectHashMap' in   'FixedRedisMessagePool'

### Steps to reproduce
![image](https://user-images.githubusercontent.com/42363259/67063719-5a139080-f19a-11e9-9798-2deeac0958de.png)

### Netty version
5.0.0.Final-SNAPSHOT
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
Windows 10

**Comment by LiujunjieALiling** [comment]
Is  anybody   here ?

**Comment by LiujunjieALiling** [comment]
@johnou  the same error  with  4.1 branch...   and  what's  wrong with this ?  
![image](https://user-images.githubusercontent.com/42363259/67082037-e9d13300-f1ca-11e9-9219-a7b71c5cb2f4.png)

**Comment by johnou** [comment]
nothing, or the Netty CI builds would fail. IDE hints are not bullet proof and cannot resolve everything.

**Comment by normanmaurer** [comment]
Like @johnou says...
