### ISSUE TITLE
Recent snapshots of netty-transport-native-kqueue don't include native libs nor classifier

### ISSUE THREAD

**Issue by simonbasle** [netty/netty#9689]
For 4.1.43, the snapshots repository does contain a jar with `osx-x86_64` classifier for `4.1.43.Final-SNAPSHOT`, but only one.
Newer versions with a newer timestamp don't include the native library nor classifier 😢

Compare just the filenames of [kqueue](https://oss.sonatype.org/content/repositories/snapshots/io/netty/netty-transport-native-kqueue/4.1.43.Final-SNAPSHOT/) vs [epoll](https://oss.sonatype.org/content/repositories/snapshots/io/netty/netty-transport-native-epoll/4.1.43.Final-SNAPSHOT/) and notice epoll consistently has the `linux-x86_64` classifier, while kqueue doesn't.

I initially stated this in a comment on #8100, but since the issue was already closed I'm reopening one for visibility.

**Comment by normanmaurer** [comment]
@simonbasle thanks a lot...

**Comment by normanmaurer** [comment]
There is something we need to fix here with a macOS CI slave. Will dig into it.

**Comment by normanmaurer** [comment]
I wonder if there is a way to run something like this as a GitHub action ... Is macOS supported there ?

**Comment by violetagg** [comment]
@normanmaurer take a look here https://github.com/reactor/reactor-netty/blob/master/.github/workflows/check_netty_snapshots.yml

**Comment by normanmaurer** [comment]
@violetagg interesting... is there any way to ensure the right compiler etc is present on macOS ?

**Comment by violetagg** [comment]
@normanmaurer here is what they provide https://github.com/actions/starter-workflows/tree/master/ci

**Comment by normanmaurer** [comment]
I need to check... that said I saw no failures on my MacBook as well :/

**Comment by violetagg** [comment]
Sorry I meant that we (dependent projects) can run our build against the published snapshots.

**Comment by chrisvest** [comment]
@violetagg We don't use MacOS GitHub Actions agents for reasons… I think that's, at least partially, why there are no kqueue native libs.
