### ISSUE TITLE
Simplify WebSocket handlers constructor arguments hell

### ISSUE THREAD

**Issue by ursaj** [netty/netty#9698]
### Expected behavior

a) I can specify **only** those parameters, I'm interested in. In any combination. E.g.:

    ctx.pipeline().addLast(new WebSocketClientProtocolHandler(
        URI.create("wss://my-domain/service"),
        WebSocketVersion.V13,
        customHeaders,
        handshakeTimeoutMillis
    ))

b) I can easily contribute new parameter without significant impact on API, e.g. `handleCloseFrames`:

    io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandler#decode
    if (handleCloseFrames && frame instanceof CloseWebSocketFrame) {

### Actual behavior

a) I need to specify a huge number of irrelevant parameters, whose values I don't really care. I want them to be defaulted.
b) I need to add new constructor with a huge number of all other parameters. Then... see (a).

### Netty version

4.1.39

### JVM version (e.g. `java -version`)

openjdk version "12.0.1" 2019-04-16

### OS version (e.g. `uname -a`)

Darwin ursaj-mbp2.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
wouldn't it be cool if we had default values in java :/

**Comment by ursaj** [comment]
groovy has default values, but it doesn't really help, e.g.:

    public MyClass(int number = 1, boolean someFlag = false, boolean anotherFlag = true, ...)
    ...
    // no way to pass only 'anotherFlag'.
    def obj1 = new MyClass(??) 

    // you can pass 'Map', but you will lose compile-time checks
    def obj2 = new MyClass([anotherFlag: true, irrelevantFlag: true])

kotlin is more mature in this aspect, but it has its own problem. e.g. a need for runtime dependency

scala, lombok, protobuf, etc - there are a lot of solutions in the market.

however I think the problem lays in concept - if you need a huge/complex configuration, it should be a separate entity. this way it will work with any technology. 

while attempts to mix configuration and behaviour within a single entity would lead to the current mess.
