### ISSUE TITLE
maven install failed on netty-transport-native-kqueue

### ISSUE THREAD

**Issue by GrayWind33** [netty/netty#9700]
### Expected behavior
install succeess
### Steps to reproduce
mvn clean install
### Minimal yet complete reproducer code (or URL to code)

```
[ERROR] Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.14:build (build-native-lib) on project netty-transport-native-kqueue: build failed: org.apache.maven.plugin.MojoExecutionException: Requested download does not exist.: Failure to find io.netty:netty-transport-native-kqueue:zip:native-src:4.1.43.Final-SNAPSHOT in http://maven.aliyun.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus-aliyun has elapsed or updates are forced
[ERROR] 
[ERROR] Try downloading the file manually from the project website.
[ERROR] 
[ERROR] Then, install it using the command: 
[ERROR]     mvn install:install-file -DgroupId=io.netty -DartifactId=netty-transport-native-kqueue -Dversion=4.1.43.Final-SNAPSHOT -Dclassifier=native-src -Dpackaging=zip -Dfile=/path/to/file
[ERROR] 
[ERROR] Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]     mvn deploy:deploy-file -DgroupId=io.netty -DartifactId=netty-transport-native-kqueue -Dversion=4.1.43.Final-SNAPSHOT -Dclassifier=native-src -Dpackaging=zip -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR] 
[ERROR]   io.netty:netty-transport-native-kqueue:zip:4.1.43.Final-SNAPSHOT
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   nexus-aliyun (http://maven.aliyun.com/nexus/content/groups/public, releases=true, snapshots=true)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]
```

### Netty version
4.1.43.Final-SNAPSHOT
### JVM version (e.g. `java -version`)
1.8.0_181
### OS version (e.g. `uname -a`)
macOS Darwin Kernel Version 18.5.0

**Comment by GrayWind33** [comment]
`[INFO] 
[INFO] ---------------< io.netty:netty-transport-native-kqueue >---------------
[INFO] Building Netty/Transport/Native/KQueue 4.1.43.Final-SNAPSHOT     [29/39]
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/fusesource/hawtjni/maven-hawtjni-plugin/1.14/maven-hawtjni-plugin-1.14.pom
Downloaded from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/fusesource/hawtjni/maven-hawtjni-plugin/1.14/maven-hawtjni-plugin-1.14.pom (5.0 kB at 6.0 kB/s)
Downloading from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/fusesource/hawtjni/maven-hawtjni-plugin/1.14/maven-hawtjni-plugin-1.14.jar
Downloaded from nexus-aliyun: http://maven.aliyun.com/nexus/content/groups/public/org/fusesource/hawtjni/maven-hawtjni-plugin/1.14/maven-hawtjni-plugin-1.14.jar (37 kB at 108 kB/s)
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ netty-transport-native-kqueue ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-tools) @ netty-transport-native-kqueue ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.0.0:check (check-style) @ netty-transport-native-kqueue ---
[INFO] 开始检查……
检查完成。
[INFO] 
[INFO] --- xml-maven-plugin:1.0.1:check-format (check-style) @ netty-transport-native-kqueue ---
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:get (get-jetty-alpn-agent) @ netty-transport-native-kqueue ---
[INFO] Resolving org.mortbay.jetty.alpn:jetty-alpn-agent:jar:2.0.8 with transitive dependencies
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:parse-version (parse-version) @ netty-transport-native-kqueue ---
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (write-version-properties) @ netty-transport-native-kqueue ---
[INFO] Executing tasks

main:
     [exec] Result: 128
     [exec] Result: 128
     [echo] Current commit: 0 on 1970-01-01 00:00:00 +0000
   [delete] Deleting: /Users/keye/workspace/netty/transport-native-kqueue/target/classes/META-INF/io.netty.versions.properties
[propertyfile] Creating new property file: /Users/keye/workspace/netty/transport-native-kqueue/target/classes/META-INF/io.netty.versions.properties
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:unpack-dependencies (unpack) @ netty-transport-native-kqueue ---
[INFO] Unpacking /Users/keye/workspace/netty/transport-native-unix-common/target/netty-transport-native-unix-common-4.1.43.Final-SNAPSHOT-osx-x86_64.jar to /Users/keye/workspace/netty/transport-native-kqueue/target/unix-common-lib with includes "META-INF/native/**" and excludes ""
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:add-source (default) @ netty-transport-native-kqueue ---
[INFO] Source directory: /Users/keye/workspace/netty/transport-native-kqueue/src/main/c added.
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ netty-transport-native-kqueue ---
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ netty-transport-native-kqueue ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/keye/workspace/netty/transport-native-kqueue/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ netty-transport-native-kqueue ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- forbiddenapis:2.2:check (check-forbidden-apis) @ netty-transport-native-kqueue ---
[INFO] Scanning for classes to check...
[INFO] Reading API signatures: /Users/keye/workspace/netty/transport-native-kqueue/target/dev-tools/forbidden/signatures.txt
[INFO] Loading classes to check...
[INFO] Scanning classes for violations...
[INFO] Scanned 45 (and 181 related) class file(s) for forbidden API invocations (in 0.06s), 0 error(s).
[INFO] 
[INFO] --- animal-sniffer-maven-plugin:1.16:check (default) @ netty-transport-native-kqueue ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1
[INFO] 
[INFO] >>> maven-bundle-plugin:2.5.4:manifest (generate-manifest) > process-classes @ netty-transport-native-kqueue >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ netty-transport-native-kqueue ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-tools) @ netty-transport-native-kqueue ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.0.0:check (check-style) @ netty-transport-native-kqueue ---
[INFO] 开始检查……
检查完成。
[INFO] 
[INFO] --- xml-maven-plugin:1.0.1:check-format (check-style) @ netty-transport-native-kqueue ---
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:get (get-jetty-alpn-agent) @ netty-transport-native-kqueue ---
[INFO] Resolving org.mortbay.jetty.alpn:jetty-alpn-agent:jar:2.0.8 with transitive dependencies
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:parse-version (parse-version) @ netty-transport-native-kqueue ---
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (write-version-properties) @ netty-transport-native-kqueue ---
[INFO] Executing tasks

main:
     [exec] Result: 128
     [exec] Result: 128
     [echo] Current commit: 0 on 1970-01-01 00:00:00 +0000
   [delete] Deleting: /Users/keye/workspace/netty/transport-native-kqueue/target/classes/META-INF/io.netty.versions.properties
[propertyfile] Creating new property file: /Users/keye/workspace/netty/transport-native-kqueue/target/classes/META-INF/io.netty.versions.properties
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-dependency-plugin:2.10:unpack-dependencies (unpack) @ netty-transport-native-kqueue ---
[INFO] Unpacking /Users/keye/workspace/netty/transport-native-unix-common/target/netty-transport-native-unix-common-4.1.43.Final-SNAPSHOT-osx-x86_64.jar to /Users/keye/workspace/netty/transport-native-kqueue/target/unix-common-lib with includes "META-INF/native/**" and excludes ""
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:add-source (default) @ netty-transport-native-kqueue ---
[INFO] Source directory: /Users/keye/workspace/netty/transport-native-kqueue/src/main/c added.
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ netty-transport-native-kqueue ---
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ netty-transport-native-kqueue ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/keye/workspace/netty/transport-native-kqueue/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ netty-transport-native-kqueue ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- forbiddenapis:2.2:check (check-forbidden-apis) @ netty-transport-native-kqueue ---
[INFO] Scanning for classes to check...
[INFO] Reading API signatures: /Users/keye/workspace/netty/transport-native-kqueue/target/dev-tools/forbidden/signatures.txt
[INFO] Loading classes to check...
[INFO] Scanning classes for violations...
[INFO] Scanned 45 (and 181 related) class file(s) for forbidden API invocations (in 0.06s), 0 error(s).
[INFO] 
[INFO] --- animal-sniffer-maven-plugin:1.16:check (default) @ netty-transport-native-kqueue ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1
[INFO] 
[INFO] --- maven-hawtjni-plugin:1.14:generate (build-native-lib) @ netty-transport-native-kqueue ---
[INFO] executing: /bin/sh -c ./autogen.sh
[INFO] auto reconf...
[INFO] ./autogen.sh: line 33: autoreconf: command not found
[INFO] rc: 127
[INFO] 
[INFO] <<< maven-bundle-plugin:2.5.4:manifest (generate-manifest) < process-classes @ netty-transport-native-kqueue <<<
[INFO] 
[INFO] 
[INFO] --- maven-bundle-plugin:2.5.4:manifest (generate-manifest) @ netty-transport-native-kqueue ---
[WARNING] Manifest io.netty:netty-transport-native-kqueue:jar:4.1.43.Final-SNAPSHOT : Unused Import-Package instructions: [sun.misc.*, sun.security.*] 
[INFO] 
[INFO] --- maven-hawtjni-plugin:1.14:generate (build-native-lib) @ netty-transport-native-kqueue ---
[INFO] executing: /bin/sh -c ./autogen.sh
[INFO] auto reconf...
[INFO] ./autogen.sh: line 33: autoreconf: command not found
[INFO] rc: 127
[INFO] 
[INFO] --- maven-hawtjni-plugin:1.14:build (build-native-lib) @ netty-transport-native-kqueue ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Netty 4.1.43.Final-SNAPSHOT:
[INFO] 
[INFO] Netty/Dev-Tools .................................... SUCCESS [  0.723 s]
[INFO] Netty .............................................. SUCCESS [  3.253 s]
[INFO] Netty/Common ....................................... SUCCESS [  6.684 s]
[INFO] Netty/Buffer ....................................... SUCCESS [  2.139 s]
[INFO] Netty/Resolver ..................................... SUCCESS [  1.025 s]
[INFO] Netty/Transport .................................... SUCCESS [  2.606 s]
[INFO] Netty/Codec ........................................ SUCCESS [  2.076 s]
[INFO] Netty/Codec/DNS .................................... SUCCESS [  1.255 s]
[INFO] Netty/Codec/HAProxy ................................ SUCCESS [  0.893 s]
[INFO] Netty/Handler ...................................... SUCCESS [  2.888 s]
[INFO] Netty/Codec/HTTP ................................... SUCCESS [  2.802 s]
[INFO] Netty/Codec/HTTP2 .................................. SUCCESS [  2.359 s]
[INFO] Netty/Codec/Memcache ............................... SUCCESS [  0.988 s]
[INFO] Netty/Codec/MQTT ................................... SUCCESS [  0.921 s]
[INFO] Netty/Codec/Redis .................................. SUCCESS [  0.881 s]
[INFO] Netty/Codec/SMTP ................................... SUCCESS [  0.830 s]
[INFO] Netty/Codec/Socks .................................. SUCCESS [  1.144 s]
[INFO] Netty/Codec/Stomp .................................. SUCCESS [  0.855 s]
[INFO] Netty/Codec/XML .................................... SUCCESS [  1.010 s]
[INFO] Netty/Handler/Proxy ................................ SUCCESS [  0.909 s]
[INFO] Netty/Resolver/DNS ................................. SUCCESS [  1.408 s]
[INFO] Netty/Transport/RXTX ............................... SUCCESS [  0.785 s]
[INFO] Netty/Transport/SCTP ............................... SUCCESS [  0.951 s]
[INFO] Netty/Transport/UDT ................................ SUCCESS [  0.910 s]
[INFO] Netty/Example ...................................... SUCCESS [  2.695 s]
[INFO] Netty/Transport/Native/Unix/Common ................. SUCCESS [  0.968 s]
[INFO] Netty/Testsuite .................................... SUCCESS [  1.799 s]
[INFO] Netty/Transport/Native/Unix/Common/Tests ........... SUCCESS [  0.769 s]
[INFO] Netty/Transport/Native/KQueue ...................... FAILURE [  2.535 s]
[INFO] Netty/Transport/Native/Epoll ....................... SKIPPED
[INFO] Netty/All-in-One ................................... SKIPPED
[INFO] Netty/Tarball ...................................... SKIPPED
[INFO] Netty/Testsuite/Autobahn ........................... SKIPPED
[INFO] Netty/Testsuite/Http2 .............................. SKIPPED
[INFO] Netty/Testsuite/OSGI ............................... SKIPPED
[INFO] Netty/Testsuite/Shading ............................ SKIPPED
[INFO] Netty/Testsuite/NativeImage ........................ SKIPPED
[INFO] Netty/Microbench ................................... SKIPPED
[INFO] Netty/BOM .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  49.591 s
[INFO] Finished at: 2019-10-22T22:14:35+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.14:build (build-native-lib) on project netty-transport-native-kqueue: build failed: org.apache.maven.plugin.MojoExecutionException: Requested download does not exist.: Failure to find io.netty:netty-transport-native-kqueue:zip:native-src:4.1.43.Final-SNAPSHOT in http://maven.aliyun.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus-aliyun has elapsed or updates are forced
[ERROR] 
[ERROR] Try downloading the file manually from the project website.
[ERROR] 
[ERROR] Then, install it using the command: 
[ERROR]     mvn install:install-file -DgroupId=io.netty -DartifactId=netty-transport-native-kqueue -Dversion=4.1.43.Final-SNAPSHOT -Dclassifier=native-src -Dpackaging=zip -Dfile=/path/to/file
[ERROR] 
[ERROR] Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]     mvn deploy:deploy-file -DgroupId=io.netty -DartifactId=netty-transport-native-kqueue -Dversion=4.1.43.Final-SNAPSHOT -Dclassifier=native-src -Dpackaging=zip -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR] 
[ERROR]   io.netty:netty-transport-native-kqueue:zip:4.1.43.Final-SNAPSHOT
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   nexus-aliyun (http://maven.aliyun.com/nexus/content/groups/public, releases=true, snapshots=true)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :netty-transport-native-kqueue
`

**Comment by normanmaurer** [comment]
@GrayWind33:

```
[INFO] ./autogen.sh: line 33: autoreconf: command not found
```

You will need to install the needed tools / libs via brew:
https://netty.io/wiki/native-transports.html#building-the-macosbsd-native-transport
