### ISSUE TITLE
DatagramMulticastTest.testMulticast() not tagged as @Test

### ISSUE THREAD

**Issue by infynyxx** [netty/netty#9702]
### Expected behavior
``` java
public class DatagramMulticastTest extends AbstractDatagramTest {
....
@Test
public void testMulticast(Bootstrap sb, Bootstrap cb) throws Throwable {
....
```
### Actual behavior

Not tagged as `@Test`.  

### Minimal yet complete reproducer code (or URL to code)

https://github.com/netty/netty/blob/netty-4.1.42.Final/testsuite/src/main/java/io/netty/testsuite/transport/socket/DatagramMulticastTest.java#L52

Not sure if its typo or intentionally ignored. If intentionally ignored, I will close the issue :)

### Netty version

netty-4.1.42.Final

### JVM version (e.g. `java -version`)

JDK 8

**Comment by normanmaurer** [comment]
@infynyxx this is expected ... We annotate the method that has no arguments.
