### ISSUE TITLE
WebSocketServerProtocolHandshakeHandler can not be extended

### ISSUE THREAD

**Issue by egerardus** [netty/netty#9703]
### Expected behavior

I need to provide a custom `isNotWebSocketPath` function (using endsWith) for `WebSocketServerProtocolHandshakeHandler` but the class is not publicly visible. 

I'm not sure if this is a design decision or a typo.

### Steps to reproduce
```java
import io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandshakeHandler;
```
### Minimal yet complete reproducer code (or URL to code)

The offending line [is here](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerProtocolHandshakeHandler.java#L45).

My failed attempt is here:
```java
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.ChannelPipeline;
import io.netty.channel.socket.SocketChannel;
import io.netty.handler.codec.http.FullHttpRequest;
import io.netty.handler.codec.http.HttpObjectAggregator;
import io.netty.handler.codec.http.HttpServerCodec;
import io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandler;
import io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandler.HandshakeComplete;
import io.netty.handler.codec.http.websocketx.extensions.compression.WebSocketServerCompressionHandler;
import io.netty.handler.ssl.SslContext;
import io.netty.handler.stream.ChunkedWriteHandler;

// this is not publicly visible and cannot be imported
import io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandshakeHandler;

public class ServerPipeline extends ChannelInitializer<SocketChannel>
{
    private static final String WEBSOCKET_PATH = "/websocket";
    private final SslContext sslContext;

    public ServerPipeline(SslContext sslContext)
    {
        this.sslContext = sslContext;
    }

    @Override
    public void initChannel(SocketChannel channel)
    {
        ChannelPipeline pipeline = channel.pipeline();
        if (sslContext != null)
        {
            pipeline.addLast(sslContext.newHandler(channel.alloc()));
        }
        pipeline.addLast(new HttpServerCodec());
        pipeline.addLast(new HttpObjectAggregator(65536));
        pipeline.addLast(new WebSocketServerCompressionHandler());

        // cannot do this because it is not publicly visible
        pipeline.addLast(new WebSocketServerProtocolHandshakeHandler(
                WEBSOCKET_PATH, true, false, 10000, null) {
            
            @Override
            private boolean isNotWebSocketPath(FullHttpRequest req) {
                return !req.uri().endsWith(WEBSOCKET_PATH);
            }
        });
        pipeline.addLast(new WebSocketServerProtocolHandler(WEBSOCKET_PATH, null, true));
        pipeline.addLast(new MyWebSocketHandler());
    }
}

```

### Netty version
netty-4.1.42.Final

### JVM version (e.g. `java -version`)

JDK 11

### OS version (e.g. `uname -a`)

Windows Server 2016

**Comment by egerardus** [comment]
For now, as a workaround, I've done some copy/paste work to recreate the standard handlers changing this function. It might be good to make it visible for future efforts however.

**Comment by normanmaurer** [comment]
@egerardus can you explain why you need this ?

**Comment by egerardus** [comment]
@normanmaurer this is for a migration from Tomcat to a more specialized netty server API that hosts many different contexts (like app namespaces) available at different paths. 

All of the existing namespace websocket connection strings are done with relative paths, e.g.:
```javascript
const url = new URL('websocket', window.location.href); 
// url is now https://host:port/namespace/websocket
url.protocol = url.protocol.replace('http', 'ws');
const websocket = new WebSocket(url.href);
```
And _not_ absolute paths:
```javascript
const url = new URL('/websocket', window.location.href);
// url is now https://host:port/websocket
url.protocol = url.protocol.replace('http', 'ws');
const websocket = new WebSocket(url.href);
```

Rather than switching everything to absolute paths and adding some kind of path injection function to the front end websocket class it is wanted that we keep things as simple as possible for the front end devs and keep using relative paths.

As noted above, I was not sure if it was a typo or done intentionally to prevent incorrectly done extensions of `WebSocketServerProtocolHandshakeHandler` which I can see now would break `WebSocketServerProtocolHandler` as it statically referenced in that class.

If it is something more involved than a typo fix I can understand not wanting to reconsider design decisions for this single use case and am fine with closing.

**Comment by kjhedkjez** [comment]
what is a easy
javascript or html

**Comment by kjhedkjez** [comment]
what is a easy
javascript or ### html****

**Comment by egerardus** [comment]
> what is a easy
> javascript or ### html****

@kjhedkjez sorry, I don't understand the question

**Comment by ZiWee** [comment]
i have the same

> For now, as a workaround, I've done some copy/paste work to recreate the standard handlers changing this function. It might be good to make it visible for future efforts however.

have u resolved it？ i also met 
```
        ch.pipeline().addLast("protoc-handler-a", new WebSocketServerProtocolHandler("/ws-A"));
        ch.pipeline().addLast("text-handler-a", new HandlerA());
        ch.pipeline().addLast("protoc-handler-b", new WebSocketServerProtocolHandler("/ws-B"));
       /*{
        if (cp.get(WebSocketServerProtocolHandshakeHandler.class) == null) { //skip
            // Add the WebSocketHandshakeHandler before this one.
            ctx.pipeline().addBefore(ctx.name(), WebSocketServerProtocolHandshakeHandler.class.getName(),
                    new WebSocketServerProtocolHandshakeHandler(websocketPath, subprotocols,
                            allowExtensions, maxFramePayloadLength, allowMaskMismatch, checkStartsWith));
        }
 
       }*/
        ch.pipeline().addLast("text-handler-b", new HandlerB());
  
```
