### ISSUE TITLE
HashedWheelTimer cost too many CPU time on windows

### ISSUE THREAD

**Issue by michaelmao999** [netty/netty#9710]
When tickDuration is set to 1, sleep time will be ignore in waitForNextTick on HashedWheelTimer, it  will waste CPU time to perform waitForNextTick again and agin.

### OS version (e.g. `uname -a`) windows 10

Here, I just post workaround for your reference.
 if (Platform.isWindows()) {
                    sleepTimeMs = sleepTimeMs / 10 * 10;
                    if (sleepTimeMs == 0) {
                        sleepTimeMs = 1;
                    }
                }

**Comment by normanmaurer** [comment]
@michaelmao999 can you provide a PR to fix this ?

**Comment by normanmaurer** [comment]
@michaelmao999 can you check https://github.com/netty/netty/pull/9714... This should fix it.
