### ISSUE TITLE
Can't disable HTTP negotiation to send HTTP2 request

### ISSUE THREAD

**Issue by liuzhuo-bj** [netty/netty#9716]
Dear,

I am a new player for Netty. It may be not a really issue but only because I don't find correct method. Anyway it will be very appreciate if can get your answer.

When I tried use Netty to send HTTP2 request to server directlly. The client always trys to start HTTP Negotiation first, then start the waiting time.  Unfortunately the Server doesn't support negotiation process, it caused the Client fail send packet util time expired.

### Expected behavior
Client can send HTTP2 request to server without HTTP Negotiation.

### Actual behavior
The client always trys to start HTTP Negotiation first. 

### Steps to reproduce

	public void post(boolean ssl, String HOST, Integer PORT, String URL, String URL2DATA) throws Exception {
		// Configure SSL.
		//[Peter:]We don't need SSL, so disable it.
		final SslContext sslCtx;
		String http2 = ApplicationProtocolNames.HTTP_2;
		if (SSL) {
			... ...
		} else {
			sslCtx = null;
		}

		EventLoopGroup workerGroup = new NioEventLoopGroup();
		Http2ClientInitializer initializer = new Http2ClientInitializer(sslCtx, Integer.MAX_VALUE);

		try {
			// Configure the client.
			Bootstrap b = new Bootstrap();
			b.group(workerGroup);
			b.channel(NioSocketChannel.class);
			b.option(ChannelOption.SO_KEEPALIVE, true);
			b.remoteAddress(HOST, PORT);
			b.handler(initializer);

			// Start the client.
			Channel channel = b.connect().syncUninterruptibly().channel();
//			ChannelFuture f = b.connect(HOST, PORT).sync();
			System.out.println("Connected to [" + HOST + ':' + PORT + ']');

			// Wait for the HTTP/2 upgrade to occur.
			//[Peter:]
			//remove following two lines to disable HTTP negotiation start
//			Http2SettingsHandler http2SettingsHandler = initializer.settingsHandler();
//			http2SettingsHandler.awaitSettings(5, TimeUnit.SECONDS);
			//disable HTTP negotiation end

			HttpResponseHandler responseHandler = initializer.responseHandler();
			int streamId = 3;
			HttpScheme scheme = SSL ? HttpScheme.HTTPS : HttpScheme.HTTP;
			AsciiString hostName = new AsciiString(HOST + ':' + PORT);
			System.err.println("Sending request(s)...");
				if (URL2 != null) {
					....
					//method 1 ：
					//after disabled HTTP Negotiation, there will report a NULL Point Error.
					responseHandler.put(streamId, channel.write(request), channel.newPromise());
					
					
//					//method 2 start ：
					//after disabled HTTP Negotiation, Use these functions, we can send HTTP packet, but it is follow HTTP1.1 sepc.
					f.channel().write(request);
					f.channel().flush();
					f.channel().closeFuture().sync();
					//method 2 end;

					streamId += 2;
				}
			//disable HTTP negotiation start
//				responseHandler.awaitResponses(5, TimeUnit.SECONDS);
			//disable HTTP negotiation end

			// Wait until the connection is closed.
			channel.close().syncUninterruptibly();
		} finally {
			workerGroup.shutdownGracefully();
		}
	}

### Netty version
4.1.39
### JVM version (e.g. `java -version`)
Java-9

**Comment by kapsterio** [comment]
It is not an issue indeed. Netty support establishing  HTTP/2 connections over cleartext TCP by http1.1 upgrade or prior Knowledge, and also support ALPN when using HTTP2 over TLS.  If you are sure about your server support  http2, your client code should use the `Http2ConnectionHandler` to send connection preface directly.  Seems you use `Http2ClientInitializer` to initialize your client Netty pipeline, it will always negotiate with server to setup http2 connection (h2 or h2c) .

**Comment by normanmaurer** [comment]
Like @kapsterio said... closing.
