### ISSUE TITLE
A redundant comparison operation

### ISSUE THREAD

**Issue by MrYangxf** [netty/netty#9725]
Hi, when I read the source code, I happened to notice this
https://github.com/netty/netty/blob/ff2a7929235257642d8f63edb1c580347307f3ee/transport/src/main/java/io/netty/channel/nio/NioEventLoop.java#L669-L674
The `eventLoop == null` is unnecessary. Although the c2 compiler optimizes it, c1 doesn’t seem to optimize it. Though it’s a small problem，it doesn’t look elegant enough.

equivalent
```java
if (eventLoop == this) {
    unsafe.close(unsafe.voidPromise());
}
return;
```

**Comment by franz1981** [comment]
processSelectedKey should be an hot path and very likely to be compiled at C2 level so I don't think it would make any difference perf-wise. For readability is fine, agree :)

**Comment by normanmaurer** [comment]
@MrYangxf sounds good... Can you please submit a PR ?

**Comment by MrYangxf** [comment]
@normanmaurer Of course :)
