### ISSUE TITLE
Http2 Client with H2C prior knowledge

### ISSUE THREAD

**Issue by Tiller** [netty/netty#9733]
### Expected behavior
Being able to create an http2 client that uses h2c prior knowledge (no http1 upgrade)

### Actual behavior
I fail to see a way to do so using the existing classes, and the lack of example / documentation doesn't help

### Steps to reproduce
I tinkered with a lot of classes / handlers sequences to end-up with:

```java
            final Http2FrameCodec http2FrameCodec = Http2FrameCodecBuilder
                    .forClient()
                    .initialSettings(new Http2Settings().maxConcurrentStreams(100))
                    .build();

            final NewStreamProxy proxy = new NewStreamProxy(http2FrameCodec);

            channel
                    .pipeline()
                    .addLast(http2FrameCodec)
                    .addLast(new ChannelInboundHandlerAdapter() {
                        @Override
                        public void channelActive(ChannelHandlerContext ctx) throws Exception {
                            super.channelActive(ctx);
                            ctx.flush();
                        }
                    })
                    .addLast(new Http2StreamFrameToHttpObjectCodec(false, false) {

                        @Override
                        protected void encode(ChannelHandlerContext ctx, HttpObject obj, List<Object> out) throws Exception {
                            super.encode(ctx, obj, out);

                            if (!out.isEmpty()) {
                                Http2FrameStream stream = ((AbstractHttp2StreamFrame) out.get(0)).stream();
                                if (stream == null) {
                                    stream = new FuckingCompatibilityLayer(http2FrameCodec).newStream();
                                }

                                for (Object object : out) {
                                    ((AbstractHttp2StreamFrame) object).stream(stream);
                                }
                            }
                        }
                    })
                    .addLast(new HttpObjectAggregator(Integer.MAX_VALUE));
```
With
```java
package io.netty.handler.codec.http2;

public class NewStreamProxy {
    private Http2FrameCodec codec;

    public NewStreamProxy(Http2FrameCodec codec) {
        this.codec = codec;
    }

    public DefaultHttp2FrameStream newStream() {
        return codec.newStream();
    }
}
```

And there 2 things that I can't wrap my head around:
1. the fact I have to explicitly flush the context when the channel gets active in order to trigger the magic header + settings exchange
2. my ugly hack with `NewStreamProxy` and the override of `Http2StreamFrameToHttpObjectCodec`. The problem here is that `Http2StreamFrameToHttpObjectCodec` creates a new `DefaultHttp2HeadersFrame` (and optional data) without setting the stream. And then, when `Http2FrameCodec.writeHeadersFrame()` tries to write the frame, it fails with NPE as `headersFrame.stream()` returns null. The worse thing about all that is that I have to create my proxy in the netty package, as I just can't find a way to trigger the creation of a new stream using public methods only.

So, am I missing a big step that will auto-magically resolve my issues, or it there a design flaw somewhere?

Thanks

### Netty version
4.1.43.Final

**Comment by normanmaurer** [comment]
I think you want to use `Http2StreamChannelBootstrap` if you use `Http2MultiplexHandler`.

```
Bootstrap bootstrap = new Bootstrap();
bootstrap.group(group)
                .channel(NioSocketChannel.class)
                .handler(new ChannelInitializer<Channel>() {
                    @Override
                    protected void initChannel(Channel channel) {
                        Http2FrameCodec http2FrameCodec = Http2FrameCodecBuilder.forClient() .build();
                        channel.pipeline().addLast(http2FrameCodec);
                        channel.pieline().addLast(new Http2MultiplexHandler());
                    }
                });

Channel channel = bootstrap.connect(...).sync();
Http2StreamChannelBootstrap  streamBootstrap = new Http2StreamChannelBootstrap(channel).handler(yourHandler);

Channel streamChannel = streamBootstrap.open().syncUninterruptibly().getNow();
 //  ... write headers etc

```

Or alternative you may want to use `Http2ChannelDuplexHandler` when only use `Http2FrameCodec`. (I would recommend you use `Http2MultiplexHandler `.

```java
Bootstrap bootstrap = new Bootstrap();
bootstrap.group(group)
                .channel(NioSocketChannel.class)
                .handler(new ChannelInitializer<Channel>() {
                    @Override
                    protected void initChannel(Channel channel) {
                        Http2FrameCodec http2FrameCodec = Http2FrameCodecBuilder.forClient() .build();
                        channel.pipeline().addLast(http2FrameCodec);
                        channel.pieline().addLast(new Http2ChannelDuplexHandler() {
                            public void channelActive(ChannelHandlerContext ctx) {
                                Http2FrameStream stream = newStream();
                               //  ... write headers etc
                            }
                        });
                    }
                });

Channel channel = bootstrap.connect(...).sync();
```

**Comment by Tiller** [comment]
@normanmaurer thanks, it seems to work, however just one question: in your example, I replaced "yourHandler" by a new ChannelInboundAdapter which on handleAdded registers my different handlers into the channel's pipeline.
However, the constructor of Http2MultiplexHandler also take a channel handler as parameter. Do you know what I'm supposed to give? I gave a random ChannelInboundAdapter that does nothing and everything seem to work so far

**Comment by normanmaurer** [comment]
@Tiller yep alternative you may just use `ChannelInitializer` and add your handlers there.

The handler used in `Http2MultplexHandler` constructor is used for new "inbound" streams. Which in case of a client would be a stream created via push promise. I think for your use-case you may not need to do anything special here .
