### ISSUE TITLE
Should netty threads be daemonized? 

### ISSUE THREAD

**Issue by smillies** [netty/netty#9754]
This links back to issue #2832, which was closed in August 2014 with a comment that Netty 5 would use daemon threads. However, 5 years later, the current version is 4.1.43 and Netty still uses non-daemon threads, which is a bit of a pain with regard to shutdown behavior, and differs from the default behavior of other embedded servers, like Tomcat.

Do you think this should be changed in Netty 4.x after all?

**Comment by normanmaurer** [comment]
@smillies I don't think we want to change this in a non major release. You can specify your own `ThreadFactory` if you like tho

**Comment by smillies** [comment]
I see. Could you explain in a few words how I could configure my own thread factory (which I guess I should back by the DefaultThreadFactory and just change the daemon property of the threads). I haven't been able to find anything about it in the User Guide or API docs. Preferably, this should be by external configuration, not programmatic, because I am using the Netty server that is embedded in Helidon SE, and I don't want to touch Helidon code.

**Comment by normanmaurer** [comment]
@smillies the only way is to construct the `*EventLoopGroup` with your own `ThreadFactory`. You will need to ask the Helidon maintainers to expose this to you.
