### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by kiki1992** [netty/netty#9761]
https://github.com/netty/netty/blob/af532d2b7ec2c151e5327a34c0b7e581d4dad2ab/transport/src/main/java/io/netty/channel/DefaultChannelPipeline.java#L143

it seems that addFirst0 method not thread safe here, can somebody kindly tell me why it's OK here.

**Comment by normanmaurer** [comment]
@kachayev it actually  is  as prev and next is volatile

**Comment by kiki1992** [comment]
> @kachayev it actually is as prev and next is volatile

Thanks for your reply, but I found that prev and next in DefaultChannelHandlerContext is not marked as volatile in master branch

**Comment by normanmaurer** [comment]
@kiki1992 that's correct as in the master branch all these modifications are done in the same Thread (EventLoop thread).

**Comment by kiki1992** [comment]
@normanmaurer if I call addFirst method from thread other than EventLoop thread, addFirst0 will be executed later by EventExecutor, it seems not thread safe here.

if (!inEventLoop) {
                try {
                    executor.execute(() -> addFirst0(newCtx));
                    return this;
                } catch (Throwable cause) {
                    handlers.remove(0);
                    throw cause;
                }
            }

**Comment by njhill** [comment]
@kiki1992 `executor` here _is_ the event loop (there is only one per pipeline unlike 4.1).

**Comment by kiki1992** [comment]
> @kiki1992 `executor` here _is_ the event loop (there is only one per pipeline unlike 4.1).

what about use a multiThread EventLoop implementation rather than SingleThreadEventLoop here.

**Comment by njhill** [comment]
@kiki1992 event loops are always single-threaded  `EventLoop extends OrderedEventExecutor` (technically could be multiple threads but tasks would still be serialized in that case)

**Comment by kiki1992** [comment]
> @kiki1992 event loops are always single-threaded `EventLoop extends OrderedEventExecutor` (technically could be multiple threads but tasks would still be serialized in that case)

got it! this means that we have to rely on a correct implementation of EventLoop,Right?

**Comment by njhill** [comment]
@kiki1992 that’s correct. and you could also replace “EventLoop” in that sentence with “any interface that we might ever use”, that is kind of the definition of an interface :)

**Comment by kiki1992** [comment]
> @kiki1992 that’s correct. and you could also replace “EventLoop” in that sentence with “any interface that we might ever use”, that is kind of the definition of an interface :)

Thanks a lot!
