### ISSUE TITLE
[Discussion] API Support for TrustManager and KeyManager in SslContext

### ISSUE THREAD

**Issue by ZhenLian** [netty/netty#9767]
Hello Netty team,

I am part of the Production Security team at Google. Our team wants to implement a utility library that can support [SPIFFE](https://spiffe.io/) on top of gRPC, and we need to pass in a custom **TrustManager** and **KeyManager** when creating **SslContext**. However, since **SslContext** only supports **TrustManagerFactory** and **KeyManagerFactory** as its building blocks, we currently have two options as I know:
1. register another **Provider** on JVM with our *ManagerFactory* classes that can produce the custom *Manager* classes we want
2. extend classes like **SimpleTrustManagerFactory** and implement functions like **engineGetTrustManagers**

However, as I see, none of the options seems neat enough if we could pass in a custom **TrustManager** and **KeyManager** directly. By having these two classes as parameters, users like us don't need to wrap custom *Manager* classes into *ManagerFactory* ones. Also, it seems in current Netty implementation, the only use of the *ManagerFactory* is to produce *Manager*. It could also be better if we add two more APIs similar with **newServerContextInternal** and **newClientContextInternal**, but provides *Manager* classes directly, as far as I see. 
I have already discussed with @ejona86  from gRPC team and we both thought this could be a good complement of current **SslContext**  APIs, and I want to collect some suggestions from the Netty community. We can help make a PR if everyone agrees on this.
@normanmaurer 
Could you please take a look and share your thoughts? Thank you in advance for your reply!

@jiangtaoli2016 FYI.

**Comment by ejona86** [comment]
To be clear, the main change would be to add overloads to `SslContextBuilder` to receive the managers instead of manager factories. It could immediately convert the managers into factories and let factories continue to pass through Netty. Or it could try to pass the managers directly into the deeper parts of the SslContext handling.

**Comment by normanmaurer** [comment]
@ZhenLian @ejona86 I think we could support to just pass in `TrustManager / KeyManager` but I am not sure how much this really buys people. I mean implement the factory is kind of trivial. That said I am not against the change, so I am happy to review a PR :)

**Comment by ejona86** [comment]
@normanmaurer, the SPI stuff is probably the biggest issue, which I think makes it non-trivial or at least scary. We'll send out a PR!

**Comment by normanmaurer** [comment]
@ejona86 sounds good

**Comment by ZhenLian** [comment]
Thanks for the discussion going on here @ejona86 and @normanmaurer ! I will close this issue and send out a PR accordingly.
