### ISSUE TITLE
DefaultHttpHeaders contains(CharSequence name, CharSequence value, boolean ignoreCase) does not ignore case

### ISSUE THREAD

**Issue by camron-johnson** [netty/netty#9769]
### Expected behavior
DefaultHttpHeaders contains(CharSequence name, CharSequence value, boolean ignoreCase) should not ignoreCase when third param is false.

### Actual behavior
DefaultHttpHeaders contains(CharSequence name, CharSequence value, boolean ignoreCase) does ignoreCase when third param is false.

### Steps to reproduce
Run the test below. 
`headers.contains("someNAME", "value", false)` correctly returns true. 
However, `headers.contains("somename", "value", false)` incorrectly returns true as well.

### Reproducer code
    @Test
    public void testHttpHeaderFieldNameCasing() {
        EmbeddedChannel ch = new EmbeddedChannel(new HttpRequestDecoder());
        ch.writeInbound(Unpooled.copiedBuffer("GET / HTTP/1.0\n", CharsetUtil.UTF_8));
        ch.writeInbound(Unpooled.copiedBuffer("someNAME: value\n\n", CharsetUtil.UTF_8));

        HttpRequest httpRequest = ch.readInbound();
        HttpHeaders headers = httpRequest.headers();
        assertTrue(headers.contains("someNAME", "value", false));
        assertFalse(headers.contains("somename", "value", false));
    }

### Netty version
4.1.42

### JVM version
11.0.5

### OS version
Darwin Kernel Version 18.7.0

**Comment by njhill** [comment]
@camron-johnson HTTP header names are always case-insensitive per the RFC. The `ignoreCase` arg here applies to the value, not the name.

**Comment by normanmaurer** [comment]
@camron-johnson as @njhill said... Let me make it more clear in the java docs tho.

**Comment by normanmaurer** [comment]
Actually it is already called out in the java docs. Closing this one
