### ISSUE TITLE
Websoket frame failes if the frame content is deflated partial EOM (0,0,-1,-1) from Tomcat.

### ISSUE THREAD

**Issue by sakshamverma** [netty/netty#9770]
Scenario is when the tomcat communicates to netty with websocket connection. The frmae size is 8192 bytes.
Tomcat sends the compressed websocket data frames to netty. 
When tomcat sends the websocket frames to netty, every frame ends with the EOM byte sequence which is 0,0,-1,-1. 
There are four conditions now:
1. The compressed data is small enough that the complete content and the EOM is contained in one frame. 

2. The data is large that it takes multiple frames to complete and the last frame contains some part data and the complete EOM. 

3. The  data is such that the EOM is in the two frames. e.g. the data is 8189 bytes, so the EOM starts in one and spreads over the next one. 

4.  The data and the EOM totals the 8192bytes. even in this case a next frame is sent with 0 as the first byte.

The conditions 1and 2 passes but 3 and 4 fails. Becuase the frame that contains only the partial EOM of previous frame is unable to be deflated in the DeflateDecoder
io.netty.handler.codec.compression.JdkZlibDecoder.decode(ChannelHandlerContext, ByteBuf, List<Object>)

### Expected behavior
The websocket message should be successfully sent. 

### Actual behavior
The message fils with the below exception 
Caused by: io.netty.handler.codec.CodecException: cannot read uncompressed buffer
at io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder.decode(DeflateDecoder.java:89)
at io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoder.decode(PerMessageDeflateDecoder.java:64)
at io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoder.decode(PerMessageDeflateDecoder.java:30)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)

### Steps to reproduce
Host a zip file in tomcat and transfer to netty application on a websocket connection.
But it is not reproducible with any zip file, only with the ones where content is not compressible by the java Deflater class. 

### Minimal yet complete reproducer code (or URL to code)
I have debugged in a complicated software, I am in process of creating a minimal code, but if the issue is crlear can we please get the fix. 

Though not in a perfect way, but I was able to fix the code by following changes in DeflateDecoder
[DeflateDecoder.txt](https://github.com/netty/netty/files/3828375/DeflateDecoder.txt)
:

boolean partialEOMFrame = true;
        for (int i = 0; i < msg.content().readableBytes(); i++) {
            byte contentAtI = msg.content().readByte();
            if (contentAtI != 0 && contentAtI != -1) {
                partialEOMFrame = false;
                break;
            }
        }
        msg.content().readerIndex(0);
;
;
;

if (!partialEOMFrame && readable && compositeUncompressedContent.numComponents() <= 0) {
            compositeUncompressedContent.release();
            throw new CodecException("cannot read uncompressed buffer");
        }

### Netty version
4.1.15
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
windows.

**Comment by normanmaurer** [comment]
@sakshamverma can you please upgrade to 4.1.43.Final and see if the problem still exists ? @amizurov did some fixes related to this as far as I remember.

**Comment by amizurov** [comment]
Hi @sakshamverma , @normanmaurer, will look as soon as possible, also it will be great to have some reproducer or steps (websocket handshake request and sequence of frames). As well I try to check compression on latest autobahn testsuite.

**Comment by normanmaurer** [comment]
@sakshamverma I think this is fixed by https://github.com/netty/netty/commit/491b1f428b00bba45a2c51d171cf819704b0fbe6#diff-30ed3b7e954d7e7b8509e71945b53430 . Please upgrade and report back if you still see the issue.

**Comment by amizurov** [comment]
@normanmaurer it was another problem, I checked compression with latest autobahn testsuite and some test not passed, that depends on some last fragmented frames, i'll try to dig deeper and fix it.

**Comment by normanmaurer** [comment]
Alight let me reopen it then @amizurov
