### ISSUE TITLE
Unwritable event triggered only once

### ISSUE THREAD

**Issue by brucelwl** [netty/netty#9771]
1. In the ``ChannelOutboundBuffer``, if the ``totalPendingSize`` exceeds 65536, ``setUnwritable (invokelater)`` method will be triggered, but only once the ``fireChannelWritabilityChanged(invokeLater)`` method will be triggered. I feel that this is unreasonable. Is this a bug?

The problem is that when ``setUnwritable`` is called for the first time, ``unwritable`` is set to 1, and only when the oldvalue in the condition is 0 will the ``firechannelwritabilitychanged`` method be called, resulting in the ``firechannelwritabilitychanged`` method being called only once. If you want to trigger ``firechannelwritabilitychanged`` multiple times, ``oldvlue `` should not be used as one of the judging conditions.

![image](https://user-images.githubusercontent.com/13413715/68548223-68656d00-0425-11ea-9e7e-ac1667a63ce2.png)

2. If it was originally designed to call ``firechannelwritabilitychanged`` only once, it is recommended to call ``isWritable()`` before `` setUnwritable(invokeLater);`` to determine whether it can be written. This can avoid the use of spin locks.
The code is as follows : 
```
private void incrementPendingOutboundBytes(long size, boolean invokeLater) {
     if (size == 0) {
          return;
     }

     long newWriteBufferSize = TOTAL_PENDING_SIZE_UPDATER.addAndGet(this, size);
     if (newWriteBufferSize > channel.config().getWriteBufferHighWaterMark()
          && isWritable() ) { //add
         setUnwritable(invokeLater);
     }
 }
```

**Comment by normanmaurer** [comment]
@brucelwl can you come up with a PR and unit test ?

**Comment by brucelwl** [comment]
> @brucelwl can you come up with a PR and unit test ?

I can come up with a PR and unit test. In this issue, I raise two questions, but I don't know which scheme the original author intended to adopt.

**Comment by brucelwl** [comment]
> @brucelwl can you come up with a PR and unit test ?

Here are two options:
1. As long as the length of the write queue is exceeded, event ``Unwritable`` will be triggered. If  continue to write data to the queue, this event will be triggered every time .
2. Only one ``Unwritable`` event is triggered, but the change of state value should be optimized

Both of them are reasonable. I hope I can get the author's response so that I can know the author's original ideas

**Comment by jiafu1115** [comment]
thus I am not the author for the design. But I think current design trigger once is more better due to if you can't catch the event. then you won't catch it even it trigger more and more times.

**Comment by normanmaurer** [comment]
@brucelwl @jiafu1115 after thinking more about it I think the current design is the correct one. We should only notify once. This will also ensure we keep the overhead low. 

@brucelwl if you feel like we can improve 2) I would be happy to review a pr :)

**Comment by brucelwl** [comment]
@normanmaurer hope you can review this pr https://github.com/netty/netty/pull/9821
