### ISSUE TITLE
Write an empty message to the channel

### ISSUE THREAD

**Issue by akefirad** [netty/netty#9772]
(I already asked the [question](https://stackoverflow.com/questions/58399274) on SO but nobody answered. I suspected that is a bug or something.)
I'm trying to send an empty message over the channel using:
`channelHandlerContext.writeAndFlush(Unpooled.EMPTY_BUFFER)`
### Expected behavior
An empty message (some TCP packet) to be sent over the channel.
### Actual behavior
Nothing happens. Using wireshark, I can confirm that there's no TCP packet going over the wire.
### Steps to reproduce
```
# Run the server
$ mvn spring-boot:run
# in a different terminal, connect to the server
$ telnet localhost 8080
# Start capturing using wireshare or any other tools.
```
### Minimal yet complete reproducer code (or URL to code)
https://github.com/akefirad/netty-tcp-keep-alive-demo
### Netty version
4.1.43.Final
### JVM version (e.g. `java -version`)
```
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
```
### OS version (e.g. `uname -a`)
```
Linux catter 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by normanmaurer** [comment]
Thats expected… writing an empty buffer will not result in any sys call.

**Comment by akefirad** [comment]
@normanmaurer thanks for the reply. So you mean [this](https://github.com/adamfisk/LittleProxy/search?q=EMPTY_BUFFER&unscoped_q=EMPTY_BUFFER) code is useless?

**Comment by normanmaurer** [comment]
@akefirad I did not check in detail but often an empty buffer is written down the pipeline to do something once all previous writes are complete (like closing the channel). For example people use this to close the channel once all previous data was written
