### ISSUE TITLE
Epoll native library timeout on WSL after upgrade from 4.1.42.Final to 4.1.43.Final

### ISSUE THREAD

**Issue by atoom** [netty/netty#9776]
### Expected behavior
Http client requests issued via Spring WebTestClient should handle responses properly and not time out.

### Actual behavior
WebTestClient times out after default 5 seconds
```
java.lang.IllegalStateException: Timeout on blocking read for 5000 MILLISECONDS
	at atoom.examples.reactor.netty.ReactorNettyTimeoutRegressionApplicationTest.testRequestResponse(ReactorNettyTimeoutRegressionApplicationTest.java:86)
```

### Steps to reproduce
`git clone https://github.com/atoom/reactor-netty-timeout-example.git && mvn test` in WSL Windows 10 build <= 16299

### Minimal yet complete reproducer code (or URL to code)
https://github.com/atoom/reactor-netty-timeout-example/tree/master

### Netty version
4.1.43.Final

### JVM version (e.g. `java -version`)
```
$ java -version
openjdk version "11.0.4" 2019-07-16 LTS
OpenJDK Runtime Environment Zulu11.33+15-CA (build 11.0.4+11-LTS)
OpenJDK 64-Bit Server VM Zulu11.33+15-CA (build 11.0.4+11-LTS, mixed mode)
```
### OS version (e.g. `uname -a`)
```
C:\>systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.16299 N/A Build 16299
```

**Comment by atoom** [comment]
If we downgrade netty-transport-native-epoll to version 4.1.42.Final everything works as expected. We have also tried on newer versions of WSL (Windows 10 Build 17763) and that also solves this problem - however it will be quite a task for us to try to get an update of our corporate version of Windows 10 on all the developer machines.

Not sure how easy it is for a Netty developer to reproduce this error since it requires specific Windows versions. If more debug information is needed just let me know and I will try to produce it!

**Comment by ninja-** [comment]
> Not sure how easy it is for a Netty developer to reproduce this error since it requires specific Windows versions. If more debug information is needed just let me know and I will try to produce it!

If you're willing to work on it, it would be fairly easy to setup a `git bisect` that tests with a given netty commit and finds the commits that breaks WSL :)

**Comment by ninja-** [comment]
also, consider blocking epoll backend on your developer setup...
seriously, in dev environment it won't benefit you much...

**Comment by atoom** [comment]
I have done a bisect based on commits below and the commit that introduces the breaking change is https://github.com/netty/netty/commit/166caf96ef87cf1d7ebfb43141939e596486928e

Unfortunately I don't have the knowledge to analyze the code change in order to determine what could be the cause. I could add some debug logging if someone can give me pointers on suitable code blocks / lines ?

```
$ git log --oneline netty-4.1.42.Final..netty-4.1.43.Final -- transport-native-epoll
d066f163d7 (HEAD, tag: netty-4.1.43.Final) [maven-release-plugin] prepare release netty-4.1.43.Final
166caf96ef Avoid unnecessary epoll event loop wake-ups (#9605)
ca915ae590 Initialize dynamicMethods before use (#9618)
c591d03320 Remove redundant epollWaitNow() call in EpollEventLoop#closeAll() (#9614)
170e4deee6 Fix event loop shutdown timing fragility (#9616)
fed552d09d Fix broken pipe due to /usr/bin/ldd (#9606)
92941cdcac [maven-release-plugin] prepare for next development iteration
```

**Comment by njhill** [comment]
@atoom this is a WSL bug, I think you just need to update to the newer build: https://github.com/Microsoft/WSL/issues/2462

**Comment by atoom** [comment]
@njhill Thanks for the information - I will close this issue and try to push for an update of Windows on our developer machines!
