### ISSUE TITLE
Use pointer bumping to improve operations of CodecOutputLists

### ISSUE THREAD

**Issue by MrYangxf** [netty/netty#9781]
#### Motivation:

`CodecOutputList` has an internal recycler called `CodecOutputLists`. This recycler maintains elements index with mask operations and an extra `count` field. I think the mask operations are unnecessary in this case. And we should use pointer bumping instead of the mask operations.

#### Modifications:

Replace `(idx + 1) & mask` with `idx + 1` and `(currentIdx - 1) & mask` with `currentIdx - 1`
and then remove `count`

**Comment by normanmaurer** [comment]
@MrYangxf you are right as it is not an `Queue` :)

**Comment by MrYangxf** [comment]
@normanmaurer thanks for you reply.
In fact,I think it's more like a stack than a queue.
It looks like a ring buffer but it is not actually...
Am I missing something?
