### ISSUE TITLE
Why is the wakeup flag still checked after NioEventLoop.select is executed?

### ISSUE THREAD

**Issue by jffree** [netty/netty#9782]
### Netty version
4.1

### Description
In `NioEventLoop.run` function:

```
                       if (wakenUp.get()) {
                            selector.wakeup();
                        }
```

Why is the `wakeup` flag still checked after `NioEventLoop.select` is executed?In `NioEventLoop.select` function, already use `hasTasks` func to check if there are new tasks joined. I don't think this step is necessary.

**Comment by normanmaurer** [comment]
@njhill can you have a look as you worked on this stuff ?

**Comment by franz1981** [comment]
For different reasons I've come at a similar conclusion some time ago: linking the issue here hoping will help https://github.com/netty/netty/issues/9112

**Comment by njhill** [comment]
I actually had not really dug into the `NioEventLoop` impl too much, prior focus was on streamlining `EpollEventLoop`. But from what I'd seen it was really in need of an equivalent overhaul.

The latest structure of `EpollEventLoop` should actually be mostly applicable to the other async transports including NIO so I took a quick stab at refactoring `NioEventLoop` along those lines, will open a PR.

**Comment by njhill** [comment]
@normanmaurer @franz1981 @jffree PTAL #9782
