### ISSUE TITLE
 ResourceLeakDetector: LEAK: ByteBuf.release() was not called before it's garbage-collected.

### ISSUE THREAD

**Issue by wbo4958** [netty/netty#9784]
### Expected behavior

No leak info

### Actual behavior

19/11/13 12:19:15 ERROR ResourceLeakDetector: LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:349)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:139)
	io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.lang.Thread.run(Thread.java:748)
19/11/13 12:19:15 ERROR ResourceLeakDetector: LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.AbstractByteBufAllocator.compositeDirectBuffer(AbstractByteBufAllocator.java:223)
	io.netty.buffer.AbstractByteBufAllocator.compositeBuffer(AbstractByteBufAllocator.java:201)
	org.apache.spark.network.util.TransportFrameDecoder.decodeNext(TransportFrameDecoder.java:167)
	org.apache.spark.network.util.TransportFrameDecoder.channelRead(TransportFrameDecoder.java:98)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.lang.Thread.run(Thread.java:748)

### Steps to reproduce
I'm running Spark 3.0 which packed netty 4.1.42.Final version. and it can easily repro if I use big data.

### Netty version
netty 4.1.42.Final
### JVM version (e.g. `java -version`)
1.8

### OS version (e.g. `uname -a`)
ubuntu 16

**Comment by wbo4958** [comment]
I've found a similar issue https://github.com/netty/netty/issues/8878

**Comment by normanmaurer** [comment]
@wbo4958 this looks like a spark bug... I will have look soon.

**Comment by wbo4958** [comment]
@normanmaurer  thx very much

**Comment by normanmaurer** [comment]
Yes this is a spark bug... let me work on a fix for them and contribute it.

**Comment by wbo4958** [comment]
@normanmaurer amazing work. When done, could you paste your PR in this thread

**Comment by normanmaurer** [comment]
@wbo4958 I will link the PR here once it is done...

**Comment by normanmaurer** [comment]
@wbo4958 https://github.com/apache/spark/pull/26609

**Comment by normanmaurer** [comment]
Closing this one as this will be fixed in spark

**Comment by wbo4958** [comment]
thx very much .

**Comment by karolsteve** [comment]
I get the same issue. this is my decoder. please need help @normanmaurer 
```
public class RTDecoder extends ReplayingDecoder {
    @Override
    protected void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) throws Exception {
        int length = in.readInt();
        byte[] data = new byte[length];
        in.readBytes(data);
        ByteBuf next = ctx.alloc().buffer(data.length);
        next.writeBytes(CipherUtils.rawDecryptData(data));
        out.add(next.toString(CharsetUtil.UTF_8));
    }
}
```
