### ISSUE TITLE
Netty drops the connection approximately every 10 minutes

### ISSUE THREAD

**Issue by ramtellams** [netty/netty#9789]
### Expected behavior
Connection should have been up for hours.
### Actual behavior

Connection gets dropped every 10 minutes. 
Error seen while writing to the socket, and then the connections gets reset.
2019-11-19 21:21:21,377 [INFO ][Timer-23718:SendHeartbeatTask.writeHeartbeatCommand():177] - Channel id=6d7a8a5f Remote address=/40.128.37.2:51320 Serial=18B169E6B14C Done writing Heartbeat command.... result state is DefaultChannelPromise@27db8714(incomplete)

### Steps to reproduce
Just writing to a socket after 10 minutes would fail.

### Minimal yet complete reproducer code (or URL to code)
if (channel != null && channel.isOpen()) {
				ByteBuffer bb = ByteBuffer.allocate(4); // Header
				bb.putShort((short)215);
				bb.putShort((short)0);

				bb.position(0);
				ChannelFuture future = ctx.writeAndFlush(Unpooled.copiedBuffer(bb)).addListener(new ChannelFutureListener() {
			         public void operationComplete(ChannelFuture future) {
			        	// Flush it now.
			        	 ctx.flush();
			         }
			     });
				logger.info(" Done writing Heartbeat command...." + " result state is " + future);

				// if heart beat send failed, then raise an alarm.
				if (!future.isSuccess()) {
					logger.debug(" Heart beat failed. Will try in the next cycle.");
				}
}
### Netty version
4.1.31.Final
### JVM version (e.g. `java -version`)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
### OS version (e.g. `uname -a`)
Cent OS 7.2

**Comment by normanmaurer** [comment]
This looks more like a problem of the remote peer closing the connection when no interactions happens for some time or something related. Netty itself will not close any connection by itself.
