### ISSUE TITLE
When set AUTO_READ = false, the netty lost some data

### ISSUE THREAD

**Issue by zman2013** [netty/netty#9802]
### Expected behavior
I tried to implement backpressure by invoking channel.read() manually. But it seems client will miss some data.

### Actual behavior
**Example**:  
Server sends an incremental integer per 1s, and print the integer.  
Client read from the socket per 5s, then writes the integer to console log.

**Result**  
Server side:
```
Mon Nov 25 00:22:48 CST 2019 write to socket: 1 channel : [id: 0x2aba8985, L:/127.0.0.1:8081 - R:/127.0.0.1:65361]
write to socket successfully 1
Mon Nov 25 00:22:49 CST 2019 write to socket: 2 channel : [id: 0x2aba8985, L:/127.0.0.1:8081 - R:/127.0.0.1:65361]
write to socket successfully 2
Mon Nov 25 00:22:50 CST 2019 write to socket: 3 channel : [id: 0x2aba8985, L:/127.0.0.1:8081 - R:/127.0.0.1:65361]
write to socket successfully 3
Mon Nov 25 00:22:51 CST 2019 write to socket: 4 channel : [id: 0x2aba8985, L:/127.0.0.1:8081 - R:/127.0.0.1:65361]
write to socket successfully 4
Mon Nov 25 00:22:52 CST 2019 write to socket: 5 channel : [id: 0x2aba8985, L:/127.0.0.1:8081 - R:/127.0.0.1:65361]
write to socket successfully 5
Mon Nov 25 00:22:53 CST 2019 write to socket: 6 channel : [id: 0x2aba8985, L:/127.0.0.1:8081 - R:/127.0.0.1:65361]
write to socket successfully 6
Mon Nov 25 00:22:55 CST 2019 write to socket: 7 channel : [id: 0x2aba8985, L:/127.0.0.1:8081 - R:/127.0.0.1:65361]
write to socket successfully 7
Mon Nov 25 00:22:56 CST 2019 write to socket: 8 channel : [id: 0x2aba8985, L:/127.0.0.1:8081 - R:/127.0.0.1:65361]
write to socket successfully 8
Mon Nov 25 00:22:57 CST 2019 write to socket: 9 channel : [id: 0x2aba8985, L:/127.0.0.1:8081 - R:/127.0.0.1:65361]
write to socket successfully 9
Mon Nov 25 00:22:58 CST 2019 write to socket: 10 channel : [id: 0x2aba8985, L:/127.0.0.1:8081 - R:/127.0.0.1:65361]
write to socket successfully 10
Mon Nov 25 00:22:59 CST 2019 write to socket: 11 channel : [id: 0x2aba8985, L:/127.0.0.1:8081 - R:/127.0.0.1:65361]
write to socket successfully 11
```

Client Side:
```
Mon Nov 25 00:22:47 CST 2019 received signal: 0
Mon Nov 25 00:22:52 CST 2019 received signal: 1
Mon Nov 25 00:22:57 CST 2019 received signal: 5
Mon Nov 25 00:23:02 CST 2019 received signal: 10
Mon Nov 25 00:23:07 CST 2019 received signal: 15
Mon Nov 25 00:23:12 CST 2019 received signal: 20
```

**Question**:  
The socket read buffer doesn't exceed at the client side, but it missed the number 2/3/4/6/7/8/9/...  

Where these number gone?

### Steps to reproduce
Refer the above example.

### Minimal yet complete reproducer code (or URL to code)
You can replay the case easily with the test case: [link][1]  
The `server` code: [link][2]  
The `client` code: [link][3]

### Netty version
```xml
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.24.Final</version>
        </dependency>
```

### JVM version (e.g. `java -version`)
`java version "1.8.0_201"`

### OS version (e.g. `uname -a`)
`Darwin localhost 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64`

Appreciate

  [1]: https://github.com/zman2013/net-pull
  [2]: https://github.com/zman2013/net-pull/blob/master/src/test/java/server/NettyServer.java
  [3]: https://github.com/zman2013/net-pull/blob/master/src/test/java/client/NettyClient.java

**Comment by ninja-** [comment]
it took me a while to figure what the hell happened here...
so the problem is that you're not draining the buffer in channelRead, only reading the first 4 bytes...

**Comment by zman2013** [comment]
@ninja- Great!  

I didn't realized this apparent mistake and was going a wrong way to dig it.

Fixed the test case by draining the buffer in channelRead.
```java
int readableBytesSize = buf.readableBytes();

while( readableBytesSize/4 > 0 ) {
    int signal = buf.readInt();
    System.out.println(new Date()
            + " received signal: "
            + signal);
    readableBytesSize -= 4;
}
```
