### ISSUE TITLE
Use CAS instead of sync in Recycler.Stack

### ISSUE THREAD

**Issue by MrYangxf** [netty/netty#9823]
Consider the following `Recycler.Stack` code snippet:
https://github.com/netty/netty/blob/4a6f5b19b7f51a7016b7b659a549b5b3b34ad35c/common/src/main/java/io/netty/util/Recycler.java#L510-L514
I guess there is little or no contend here...only happens when object recycle at different threads.
Direct cas more effective than sync spins(or bias) in this case.
Like following `setHead` method
```java
final void setHead(WeakOrderQueue newHead) {
    WeakOrderQueue oldHead;
    do {
        oldHead = head;
        newHead.setNext(oldHead);
    } while (!casHead(this, oldHead, newHead));
}
```

**Comment by normanmaurer** [comment]
I think a `synchronized` is good enough here and it only happens very rarely anyway. Let's close this
