### ISSUE TITLE
Example for Proxy with  Http2

### ISSUE THREAD

**Issue by amit2103** [netty/netty#9828]
Is there a simple example which shows Proxy with Http2 ? Even a simple example or guide will do.
Sorry for the naive question and thanks in advance

**Comment by bishwenduk029** [comment]
@amit2103 , you refer this git repo for Netty based Proxy, it is experimental but you can get some conceptual understanding...
https://github.com/chhsiao90/nitmproxy

**Comment by normanmaurer** [comment]
closing as this is an issue tracker
