### ISSUE TITLE
US Export control rating (ECCN) for netty-handler-4.1.29.Final.jar

### ISSUE THREAD

**Issue by rdss12345** [netty/netty#9841]
Sorry to add this as an issue but I couldn't see where else to raise it.

Ref: netty-handler-4.1.29.Final.jar

We are conducting export control checks on software that uses this library and have identified it as potentially containing cryptography.

As the download links for this library are hosted by github can the developers please confirm whether the required notification under the EAR related to open source encryption source code has been made to US Government or advise the grounds why the developers deem such notification isn’t required?

The requirement comes from US EAR legislation and github T&Cs relating to submissions.

"You may not use GitHub in violation of export control or sanctions laws of the United States or any other applicable jurisdiction. You may not use GitHub if you are or are working on behalf of a Specially Designated National (SDN) or a person subject to similar blocking or denied party prohibitions administered by a U.S. government agency. GitHub may allow persons in certain sanctioned countries or territories to access certain GitHub services pursuant to U.S. government authorizations. For more information, please see our Export Controls policy."

https://help.github.com/en/github/site-policy/github-terms-of-service
https://help.github.com/en/github/site-policy/github-and-trade-controls

For background information and some FAQ’s please see
http://www.apache.org/dev/crypto.html
https://www.ecfr.gov/cgi-bin/text-idx?SID=00a8f54989eaf101a84eff3db59ac6e9&mc=true&node=se15.2.742_115&rgn=div88

Many thanks,
Rowland

**Comment by normanmaurer** [comment]
@rdss12345 we just use crypto libraries like `OpenSSL` or what is provided by the `JDK` itself. So I think there needs to be nothing done by us itself ?

**Comment by headius** [comment]
@normanmaurer This account appears to be filing the same issue against several projects, including some like jnr-constants that have zero crypto-related code.

**Comment by normanmaurer** [comment]
@headius thanks for the headsup... let me just close it.

**Comment by rdss12345** [comment]
Thank you for your quick response. In summary, we need a US export control licence for our product. In order to gain that we need a rating for the FOSS libraries used by it. We either need to find a rating already provided by a library's authors or get a statement from the authors. As you can imagine there are going to be false positives where we need the author to state that there is no cryptography in the library and that they are exempt. Unfortunately we are not allowed to inspect the code and determine this ourselves. I believe that your post on 4/12/19 will suffice for what I need. Thank you very much.
Rowland
