### ISSUE TITLE
No reply from Postgres domain socket on Google App Engine

### ISSUE THREAD

**Issue by tsegismont** [netty/netty#9853]
Hi, this is Thomas from the Vert.x team.

While upgrading the [Vert.x + Postgres example for Google App Engine](https://github.com/tsegismont/samples/blob/vertx-updates/java11/vertx-cloudsql-postgres/README.md) to the latest Vert.x release (3.8.4, based on Netty 4.1.42.Final), I found that we were no longer receiving Postgres data.

On GAE, you can connect to a Google Cloud SQL instance through a domain socket. This is supported by the Vert.x Postgres Client with Netty Epoll.

I tracked down the issue to be related to this PR #9583 (Vert.x gets Postgres data again after rebuilding Netty 4.1 branch with the corresponding commit reverted).

I'm not sure how I can help any further. Do you need more info about the environment?

Cheers

**Comment by normanmaurer** [comment]
@njhill can you have a look ?

**Comment by normanmaurer** [comment]
@tsegismont just to ensure it is not fixed already can you try to use 4.1.43.Final as well ?

**Comment by tsegismont** [comment]
@normanmaurer thanks for the quick reply!

I tried with 4.1.43.Final without success. However, if you checkout 4.1 branch and revert 2b9f69ac38, it works again.

**Comment by njhill** [comment]
@normanmaurer sure I will take a look but expect I will need to try and repro locally, may not have enough time until later next week.

@tsegismont any chance you could try it out with non-domain socket epoll?

**Comment by tsegismont** [comment]
Hi @njhill , thanks for helping!

I can't try with non-domain socket epoll, GAE only supports domain socket connection for Cloud SQL.
Do you mean trying on my laptop with epoll and Postgres TCP?

**Comment by njhill** [comment]
@tsegismont ah, I assumed they might support regular socket connection too.

Yes the next step I guess would be to try some permutations locally, maybe starting just with the unit tests of the postgres client standalone https://github.com/eclipse-vertx/vertx-sql-client/tree/3.8/vertx-pg-client/src/test/java/io/vertx/pgclient. I can try this too but as I said may not get to it for a bit.

**Comment by normanmaurer** [comment]
@njhill I wonder if we should in the meantime just revert the commit for the next commit and then reapply to investigate ? I am thinking of this as I think a new release is about to happen this PR is really just an "optimisation" so its not critical and can be reverted without much pain. WDYT ?

**Comment by tsegismont** [comment]
@njhill I believe the Pg client has integration tests for local domain socket transport with epoll, but I'll double-check and keep you informed

@normanmaurer releasing would be nice but don't do it just for Vert.x Pg client because I'm not sure we'll have another 3.8.x soon anyway, right @vietj ?

**Comment by njhill** [comment]
@normanmaurer fine with me, agree it would be prudent. Maybe hold off for a couple more hours though if possible, I may have a little time right now so will see if I can repro/debug quickly.

**Comment by normanmaurer** [comment]
@njhill sure... that said I would like to get https://github.com/netty/netty/pull/9850 sorted as a priority

**Comment by njhill** [comment]
@normanmaurer sorry I didn't get too far with debugging and may not have time for a few days so please feel free to revert for the release.

Re #9850, am waiting for next response from @Scottmitch ... unless there's something I still haven't understood (entirely possible), the change seems unnecessary.

**Comment by normanmaurer** [comment]
@njhill yeah lets do this for now...

**Comment by normanmaurer** [comment]
Reverted via 9fa8b02

**Comment by tsegismont** [comment]
@njhill @normanmaurer sorry for the late reply, I checked the `vertx-sql-client` test suite and we do have an test for Pg with domain socket connection and epoll. It works fine locally. So it's only reproducible on GAE so far.

@normanmaurer do you want me to give a try to the latest snapshot?

**Comment by normanmaurer** [comment]
Latest 4.1 branch

**Comment by njhill** [comment]
@tsegismont I'd also verified that test works locally, however I don't think it actually exercises the connection in this case. As a next step it may be good to modify the rest of the test suite to also use the domain socket if possible.

**Comment by tsegismont** [comment]
>Latest 4.1 branch

@normanmaurer I can confirm that latest 4.1 branch build fixes the issue

>As a next step it may be good to modify the rest of the test suite to also use the domain socket if possible.

@njhill I'll find some time to do this asap and keep you informed
