### ISSUE TITLE
Make content compression configurable per content type

### ISSUE THREAD

**Issue by dvlato** [netty/netty#9867]
### Expected behavior
Content compression can be enabled for specific content types. This mean we would like to configure ContentCompressor so we can define what content types should be compressed; in this case we wouldn't compress JPEG or GIF files as those formats are already compressed.

This PR tried to fix the issue: https://github.com/netty/netty/pull/3847 but it seems it was abandoned.

### Actual behavior
Compression affects all the content types,  even if there's little no gain from compressing that type (e.g., JPEG files).

### Netty version
netty-4.1.43.Final

**Comment by doom369** [comment]
Very good idea. Recently I had the same thoughts. Also, it would be cool to have size limited compression. So for small messages like < 20 bytes you don't need compression.

**Comment by njhill** [comment]
@dvlato @doom369 if I'm not mistaken this should be already possible by just subclassing `HttpContentCompressor` and overriding `acceptOutboundMessage(Object)`.

**Comment by doom369** [comment]
@njhill you are right. Also, `HttpContentCompressor` already has `contentSizeThreshold`. However, there is no such option for WebSockets. And it is not that trivial there :).

**Comment by amizurov** [comment]
@dvlato @doom369 guys this is already exist see #8910 we use this functionality on production.

**Comment by amizurov** [comment]
You can implement something like this:
```
public class SelectiveCompressionFilterProvider implements WebSocketExtensionFilterProvider {

    private final int contentSizeThreshold;

    public SelectivityCompressionFilterProvider(int contentSizeThreshold) {
        this.contentSizeThreshold = contentSizeThreshold;
    }

    @Override
    public WebSocketExtensionFilter encoderFilter() {
        return webSocketFrame -> {
            if (contentSizeThreshold > 0) {
                return (webSocketFrame instanceof BinaryWebSocketFrame || webSocketFrame instanceof TextWebSocketFrame)
                    && webSocketFrame.isFinalFragment()
                    && webSocketFrame.content().readableBytes() < contentSizeThreshold;
            }

            return false;
        };
    }

    @Override
    public WebSocketExtensionFilter decoderFilter() {
        return WebSocketExtensionFilter.NEVER_SKIP;
    }

}
```
and pass it to `PerMessageDeflateServerExtensionHandshaker` for example.

**Comment by doom369** [comment]
@amizurov cool, thanks for hint!

**Comment by doom369** [comment]
@dvlato @njhill here the code that allow to skip certain content types:

```
public final class BlynkHttpCompressor extends HttpContentCompressor {

    @Override
    protected Result beginEncode(HttpResponse response, String acceptEncoding) throws Exception {
        if (response.headers().containsValue(HttpHeaderNames.CONTENT_TYPE, "font/woff2", false)) {
            return null;
        }
        return super.beginEncode(response, acceptEncoding);
    }

}
```

**Comment by normanmaurer** [comment]
@dvlato as @doom369 said you can easily implement this. So closing this issue

**Comment by dvlato** [comment]
Hi, 
I'd already tried the beginEncode() solution and now I've added some support in 'acceptOutboundMessage'  but I still see high spikes in the latency of our application (in the 99% percentile) when the compression filter has been added even though the client does not send any 'accept-encoding' header! Has anyone experienced this issue previously?

**Comment by doom369** [comment]
@dvlato it could be anything. You need to profile in order to make correct conclusions that the problem in `HttpContentCompressor`. According to the code in `HttpContentCompressor.beginEncode()` it does nothing if no encoding header was provided.
