### ISSUE TITLE
How do we control compression behavior?

### ISSUE THREAD

**Issue by carryxyh** [netty/netty#9870]
Recently we tried to add compression support to our RPC framework. I found that Netty already has a variety of compressed encoders and decoders(support lzf, snappy, zlib and so on).

However, because the length of the data in the channel is inconsistent, in general, we want to compress the longer data and not the shorter data. So I submitted a pull request to control whether the compress encoder works:

https://github.com/netty/netty/pull/9869#issuecomment-564412427

But this is a wrong pull request. Because the decoder on the other side does not know whether the data has been compressed, the decoder only performs the decompression operation. When the decoder performs a decode operation on uncompressed data, only a decode exception will be generated.

Do we have a solution to this problem?

Can we use the hack compression protocol to identify whether this data has been compressed (such as adding a byte mark before the whole content)?

**Comment by amizurov** [comment]
@carryxyh hi, websocket selective compression is work how you want but this is on protocol level (RSV1 mark it is compressed payload or not).

**Comment by carryxyh** [comment]
Thank you very much for your answer. :)

Currently, our rpc framework uses a proprietary protocol built on the TCP protocol. The overall cost of protocol switching is very high. Did not meet our requirements...

**Comment by amizurov** [comment]
@carryxyh I meant if you can expand your protocol then do like websocket or another way, because I'm not sure that is good idea to read some first bytes from payload and try to guess is it snappy or zlib without any agreement.

**Comment by carryxyh** [comment]
Got it. It's a good way to extend the protocol for us.

It seems that in this way, we can't make good use of the existing compression encoder/decoder provided by Netty, but need to perform the compression / decompression operation ourselves, right?

Or we have other way to use provided encoder/decoder?

**Comment by amizurov** [comment]
You can extend or aggregate existing compression encoder/decoder and write your handler with logic that will be make design should be compression apply or not e.g. https://github.com/netty/netty/blob/a7c18d44b46e02dadfe3da225a06e5091f5f328e/codec-http/src/main/java/io/netty/handler/codec/http/HttpContentCompressor.java#L135-L141
The similar approach we use in WebSocket compression extension `PerMessageDeflateEncoder` that use `WebSocketExtensionFilter` responsible to skip evaluation of compression or not.

**Comment by carryxyh** [comment]
Solved my confusion, I think I should study your example. 
Thank you very much for your reply.
