### ISSUE TITLE
IllegalArgumentException when sorting cookies in ClientCookieEncoder

### ISSUE THREAD

**Issue by gerdriesselmann** [netty/netty#9881]
We use Netty to crawl a lot of websites, and from time to time get the following exception:

```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
java.base/java.util.TimSort.mergeHi(TimSort.java:903)
java.base/java.util.TimSort.mergeAt(TimSort.java:520)
java.base/java.util.TimSort.mergeForceCollapse(TimSort.java:461)
java.base/java.util.TimSort.sort(TimSort.java:254)
java.base/java.util.Arrays.sort(Arrays.java:1441)
io.netty.handler.codec.http.cookie.ClientCookieEncoder.encode(ClientCookieEncoder.java:165)
```

I tried to write a testcase to reproduce the behavior, but since TimSort only throws this exception under some circumstance, I failed. 

However, I think I can spot the cause. The code in question uses this comparator (io/netty/handler/codec/http/cookie/ClientCookieEncoder.java:91):

```
   /**
     * Sort cookies into decreasing order of path length, breaking ties by sorting into increasing chronological
     * order of creation time, as recommended by RFC 6265.
     */
    private static final Comparator<Cookie> COOKIE_COMPARATOR = (c1, c2) -> {
        String path1 = c1.path();
        String path2 = c2.path();
        // Cookies with unspecified path default to the path of the request. We don't
        // know the request path here, but we assume that the length of an unspecified
        // path is longer than any specified path (i.e. pathless cookies come first),
        // because setting cookies with a path longer than the request path is of
        // limited use.
        int len1 = path1 == null ? Integer.MAX_VALUE : path1.length();
        int len2 = path2 == null ? Integer.MAX_VALUE : path2.length();
        int diff = len2 - len1;
        if (diff != 0) {
            return diff;
        }
        // Rely on Java's sort stability to retain creation order in cases where
        // cookies have same path length.
        return -1;
    };
```

If I pass two cookies C1 and C2 with the same path length to this function it would return C1 < C2 and C2 < C1. This - in my eyes  - is a violation of contract. And I suspect, this is causing the exception.

Returning 0 instead of -1 should fix this.

### Expected behavior

Cookies are always sorted by path

### Actual behavior

Sorting cookies by path sometimes throws an exception

### Steps to reproduce

Difficult. Depends on the concrete cookies set, since TimSort contract violation detection is a byproduct which is triggered occasionally. TimSort does not actively looks for contract violations.

### Minimal yet complete reproducer code (or URL to code)

Not available

### Netty version

4.1.43.Final

### JVM version (e.g. `java -version`)

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

### OS version (e.g. `uname -a`)

Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-62-generic x86_64)

**Comment by normanmaurer** [comment]
@gerdriesselmann this sounds about right... Are you interested in providing a PR to fix it ?
