### ISSUE TITLE
JdkSslContext deprecated constructor with no clear alternative.

### ISSUE THREAD

**Issue by hedefalk** [netty/netty#9898]
I'm creating a JdkSslContext with this constructor that I got from some tutorial:

https://github.com/netty/netty/blob/2f32e0b8adb63decd9031e26fa5dd4154d93ce97/handler/src/main/java/io/netty/handler/ssl/JdkSslContext.java#L185

However, that constructor is deprecated and refers to the expanded constructor with a default param that are unfortunately package private:
 
`jdkDefaultApplicationProtocolNegotiator.INSTANCE`

So I can't just rid the deprecation by expanding myself. And there's little else in the javadocs to help me. I'm also calling this from Scala so no easy way to suppress warnings unfortunately.

**Comment by slandelle** [comment]
Use [this one](https://github.com/netty/netty/blob/2f32e0b8adb63decd9031e26fa5dd4154d93ce97/handler/src/main/java/io/netty/handler/ssl/JdkSslContext.java#L219) and pass the extra parameters as null.

**Comment by normanmaurer** [comment]
@hedefalk usually you should use the `SslContextBuilder` to create `SslContext` instances
