### ISSUE TITLE
Honor local cipher suites preference with netty

### ISSUE THREAD

**Issue by wlqing** [netty/netty#9901]
In `SSLParameters`, [setUseCipherSuitesOrder](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLParameters.html#setUseCipherSuitesOrder-boolean-) allows to configure honoring local cipher suites preference, in netty [SslContextBuilder](https://netty.io/4.1/api/index.html?io/netty/handler/ssl/SslContextBuilder.html), `setEnabledCipherSuites` is provided, what's the correct way to configure honoring local cipher suites preference? 
#### Netty version
4.1.36.final
#### JVM version (e.g. `java -version`)
1.8.0_231
#### OS version (e.g. `uname -a`)
windows

**Comment by normanmaurer** [comment]
@wlqing if you want to call `setUseCipherSuitesOrder` just do it on the SslParameters and pass these down to the `SslEngine` as you would do normally. There is nothing special in netty here.
