### ISSUE TITLE
Support creating http2 stream frames with given streamId

### ISSUE THREAD

**Issue by mostroverkhov** [netty/netty#9903]
### Expected behavior
Create outbound http2 streams with given streamId
### Actual behavior
Looks like there is no public api to create http2 stream frames with provided streamId
### Netty version
4.1.44.Final
### JVM version (e.g. `java -version`)
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Ubuntu-0ubuntu1.118.04, mixed mode, sharing)
### OS version (e.g. `uname -a`)
Linux maksym-desktop 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mostroverkhov** [comment]
I tried add one locally with https://github.com/mostroverkhov/netty/commit/e164d723c2d401fd3555156f32f7013b0576ac36, but then there is `Stream object required for identifier: 3` on https://github.com/netty/netty/blob/bc026ef8ba70ab4f1be20ee4a768f16d834a4382/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2FrameCodec.java#L595, happening because https://github.com/netty/netty/blob/bc026ef8ba70ab4f1be20ee4a768f16d834a4382/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2FrameCodec.java#L461 not called as map is populated with respective key only if stream headers frame id is invalid. Could workaround with https://github.com/mostroverkhov/netty/commit/28555a38d53d56043413880b20efc5a0c738597b - may be there is an easier way?

**Comment by normanmaurer** [comment]
@mostroverkhov why you want to supply your own stream id ? Is this for push promise ?

**Comment by mostroverkhov** [comment]
@normanmaurer I use http2 streams to carry another protocol frames which have their own ids

**Comment by mostroverkhov** [comment]
At least can this line https://github.com/netty/netty/blob/bc026ef8ba70ab4f1be20ee4a768f16d834a4382/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2FrameCodec.java#L677 access level  change from `private` to `package-private` so I can workaround outside of netty codebase (would make things more consistent as a bonus point)?

**Comment by normanmaurer** [comment]
@mostroverkhov I need to think about this a bit... I am not really liking the idea of have people adjust the id this way as it is super easy to mess up etc.

**Comment by normanmaurer** [comment]
@mostroverkhov I still don't get why you can't just use your own `Http2FrameStream` and provide a "valid" stream id. It should only cast in the case of it being not valid. Can you give some more details ?

**Comment by mostroverkhov** [comment]
@normanmaurer if I just use `Http2FrameStream` like 
```
        Http2FrameStream stream = new Http2FrameStream() {
            @Override
            public int id() {
                return streamId;
            }

            @Override
            public Http2Stream.State state() {
                return Http2Stream.State.IDLE;
            }
        };
```
I get `Stream object required for identifier: 3` on https://github.com/netty/netty/blob/bc026ef8ba70ab4f1be20ee4a768f16d834a4382/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2FrameCodec.java#L595.  The same result is with `DefaultHttp2FrameStream`, reason is only one of `Http2FrameStream` and `Http2Stream` have said ID set (if I recall correctly - happened 3 weeks ago). The workaround is approximately as mentioned is 2nd message of this issue.

**Comment by mostroverkhov** [comment]
I dont know if `http2codec` is intended for people to send streams directly to It (still It looks odd not to), if so - most probably would prefer to just provide streamId alone.
>  I am not really liking the idea of have people adjust the id this way as it is super easy to mess up
I found It is not easy to mess as http2 codec is rather strict (out-of-order ids, frames for closed streams and so on)

**Comment by normanmaurer** [comment]
@mostroverkhov PTAL https://github.com/netty/netty/pull/9953

**Comment by mostroverkhov** [comment]
I ended up doing things in codec expected way: create `FrameStream` with `Http2ChannelDuplexHandler.newStream()` and reuse It until stream completion. Instead of setting stream id explicitly I wait until It is set by codec and verify It has expected value.

**Comment by IsanHu** [comment]
@mostroverkhov @normanmaurer Hello does Netty support this now? I can't find a way to create http2 stream frames with given streamId
