### ISSUE TITLE
why netty don't use mmap to map socket fd in to directbytebuffer ?

### ISSUE THREAD

**Issue by zhihao1996** [netty/netty#9904]
why netty don't use mmap to map socket fd in to directbytebuffer to avoid additional memory copy ?

**Comment by zhihao1996** [comment]
do you guys think if java support mmap to  socket , it will be benificial to netty performance?

**Comment by liudinghua** [comment]
mmap has lower performance then sendfile




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhihao1996"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月24日(星期二) 下午2:26
收件人:&nbsp;"netty/netty"<netty@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [netty/netty] why netty don't use mmap to map socket fd in to directbytebuffer ? (#9904)




do you guys think if java support mmap to  socket , it will be benificial to netty performance?

**Comment by limeuser** [comment]
but, if you want to send a memory buffer to socket, not a file, you can't use sendfile
