### ISSUE TITLE
writeAndFlush(message) can't flush out in an ChannelInboundHandlerAdapter. 

### ISSUE THREAD

**Issue by lyj-eternity** [netty/netty#9905]
### Description：
I use "ctx.pipeline().writeAndFlush(message);" to send message in an inboundHandler's channelRead method.  But the message can't send out.The location of inboundHandler in the pipeline as below:
![image](https://user-images.githubusercontent.com/37172335/71413117-af34bc80-268b-11ea-96c3-16de86263182.png)
When I use writeAndFlush in one outboundHandler(such as ResourceLogHandler),the message send out successful.
![image](https://user-images.githubusercontent.com/37172335/71413310-852fca00-268c-11ea-8f59-053194aaec1d.png)
Why?  Summary,I writeAndFlush message in an inboundHandler,which in the middle of pipline.If I just use write but not flush in every outboundHandler in the pipline,the message can't send out.In other words,client can't receive the message I send.

### Netty version
4.1.42
### JVM version (e.g. `java -version`)
8
### OS version (e.g. `uname -a`)
windows10

**Comment by Tinet-lizy** [comment]
I hava the same Question.you can write like this and it worked,but i dont konw why.
` future.channel().writeAndFlush(byteBuf).sync();`

**Comment by lyj-eternity** [comment]
> I hava the same Question.you can write like this and it worked,but i dont konw why.
> ` future.channel().writeAndFlush(byteBuf).sync();`

It really confuses me.Why the message can't flush out in an inboundHandler......

**Comment by normanmaurer** [comment]
@lyj-eternity check if the future is failed after it completes.
