### ISSUE TITLE
How can netty server send a message immediately to client when the connection established? 

### ISSUE THREAD

**Issue by alan-tang-tt** [netty/netty#9908]
How can netty server send a message immediately to client when the connection established? At this time, the client hasn't send any message to server but only establishing the connection. I tried to add a handler to the ServerBootstrap, and write message when channelRead0(), but it failed because of 'channel not registered to an event loop'. I read the source code, and then found that the handler added by 'bootstrap.handler(new SomeHandler());'  run before 'ServerBootstrapAcceptor' when the EventLoop hadn't initialized. I tried to find whether I can add handler after ServerBootstrapAcceptor but no result. So, how can I send message immediately  after connection establised?

**Comment by carryxyh** [comment]
```
public class EchoClientHandler extends SimpleChannelInboundHandler<ByteBuf> {

    @Override
    public void channelActive(ChannelHandlerContext ctx) throws Exception {
        ctx.writeAndFlush(Unpooled.copiedBuffer("Netty rocks!", CharsetUtil.UTF_8));
        ctx.fireChannelActive();
    }
}
```

this way maybe help u..

**Comment by normanmaurer** [comment]
What @carryxyh said

**Comment by alan-tang-tt** [comment]
Thank you very much. I read the source code again, and found that sub handler's active method will be called when accepted. @carryxyh 谢谢，大佬很厉害。
