### ISSUE TITLE
WS403Responder always stays in the pipeline

### ISSUE THREAD

**Issue by doom369** [netty/netty#9913]
After handshake is done `WS403Responder` handler stays within the pipeline. I think this is wrong and `WebSocketServerProtocolHandler` should remove it as it is not needed anymore.

WDYT?

**Comment by amizurov** [comment]
Hi @doom369 for me your suggestion looks reasonable, also I'm not sure if we need to keep `WebSocketServerHandshaker` for each channel in attribute only for close websocket handshake.
https://github.com/netty/netty/blob/06a5173e8d700f5f431557f21f647f2199bb3d52/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerProtocolHandler.java#L238-L251

**Comment by doom369** [comment]
@amizurov sorry, I did a mistake. I actually mean `WS403Responder` handler. After handshake is done WS403Responder handler is still within a pipeline.
Also, additional `WebSocketCloseFrameHandler` probably could be merged into `WebSocketServerProtocolHandler` to minimize the pipeline.

**Comment by normanmaurer** [comment]
@doom369 yeah we should remove WS403Responder.

**Comment by normanmaurer** [comment]
@doom369 @amizurov actually after thinking more about it I wonder what's the matter of the `WS403Responder` at all. This handler makes no sense to me at all and I think we should just remove it. WDYT ?

**Comment by doom369** [comment]
@normanmaurer I think you are right. I believe it was added in order to skip the duplicated "upgrade"  query while the handshake is not finished.

**Comment by amizurov** [comment]
@normanmaurer, @doom369 hi guys, i agree looks like a guard. Also without it we will throw `io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException` and handle this case.

**Comment by normanmaurer** [comment]
@doom369 @amizurov imho throwing is more correct as as soon as you started the upgrade you should not send any HTTP anymore.

**Comment by normanmaurer** [comment]
Let me remove this code all together.

**Comment by normanmaurer** [comment]
@doom369 @amizurov PTAL https://github.com/netty/netty/pull/9941

**Comment by doom369** [comment]
@normanmaurer looks good. I also checked the specification, error 403 should be returned only when server doesn't want to accept the origin. So look like those handler was a really unnecessary thing.

**Comment by doom369** [comment]
@normanmaurer just one thing. I personally don't care, but removal of this handler can cause back compatibility issue in case someone expects this handler to be in the pipeline.

**Comment by amizurov** [comment]
LGTM, also i don't think that package-private API is a good chose to build logic on top of it.
