### ISSUE TITLE
ByteBufUtil.indexOf inefficient for substring search (can do a PR)

### ISSUE THREAD

**Issue by linasm** [netty/netty#9914]
We have found out that `ByteBufUtil.indexOf` is inefficient for substring search, both in terms of algorithm complexity (worst case `O(needle.readableBytes * haystack.readableBytes)`, and in constant factor (esp. on Composite buffers).

We have solved the issue on our end by implementing more performant search algorithms (the improvement is on the order of magnitude), and I wanted to ask maintainers of the project whether they would see a benefit of having it contributed to the Netty code base. If the answer is positive, I would be able to submit a PR within a few weeks.

Some details on the algorithms in question:
1. [Knuth Morris Pratt](https://en.wikipedia.org/wiki/Knuth–Morris–Pratt_algorithm) - classical textbook algorithm, a good default choice.
2. Bit mask based algorithm - best overall performance, but limited to maximum search substring (the `needle`) length of 64 bytes.
3. [Aho–Corasick](https://en.wikipedia.org/wiki/Aho–Corasick_algorithm) - worse performance and higher memory consumption, but it supports multiple substring (the `needles`) search by inspecting every byte of the `haystack` only once.

Each algorithm processes every byte of underlying buffer only once, so they can be implemented as `ByteProcessor`. 

They all have linear time complexity:
- `O(needle.readableBytes)` for preprocessing (in case of [3] it is `O(SUM(needle.readableBytes))`
- `O(haystack.readableBytes)` for actual search

In practice search substring (the `needle`) is often a fixed value, which allows to do preprocessing only once.

Please let me know if this is of interest for Netty.

**Comment by normanmaurer** [comment]
Yes! Please include a benchmark as well

**Comment by njhill** [comment]
+1
