### ISSUE TITLE
FlushConsolidationHandler does not flush when write during flush

### ISSUE THREAD

**Issue by Delorien84** [netty/netty#9923]
Hi, I have found unexpected behavior when using `FlushConsolidationHandler` in proxy like application (eg. similar to https://netty.io/4.1/xref/io/netty/example/proxy/package-summary.html ). 

I have two channels and I "resend" data between channels. When I write some data to outbound channel with `FlushConsolidationHandler` the data is not flushed properly in some case. 

When write to channel based on flush event the second data is not. The problem is in `FlushConsolidationHandler#flushTask`. When additional `writeAndFlush` happened inside `flush` (line 110). `scheduleFlush` method will do nothing because `nextScheduledFlush` is still set.  If that happened, the data is not flushed until:

1. read happened 
1. additional flush happened (not in same stack trace, in next "loop")

Because my code will do both cases only after data is written (flushed) the channel is effectively in "deadlock" state.

### Possible fix

Possible fix is to swap line 110 and 111 in `FlushConsolidationHandler` to clear `nextScheduledFlush` before calling actual `flush`.
```
nextScheduledFlush = null;
ctx.flush();
```

Or to do check after `ctx.flush()` if there is additional `flushPendingCount` and flush again (possible in loop)

### Expected behavior
all data are flushed correctly

### Actual behavior
when write data based on flush 

#### General case
code like this will not flush `data2`
```
channel.writeAndFlush(data).addListener(f -> channel.writeAndFlush(data2));
```

#### More complex example

- auto read is turn off
- both channels have same event loop 

```
Channel outboundChannel = .... 
outboundChannel.pipeline().addLast(
new WriteOnlyFlushConsolidationHandler(FlushConsolidationHandler.DEFAULT_EXPLICIT_FLUSH_AFTER_FLUSHES, true));

Channel inboundChannel = ....
inboundChannel.pipeline().addLast(
  new FlowControlHandler(),
  new MyHandler(outboundChannel)
);

class MyHandler extends ChannelInboundHandlerAdapter {
   public void channelRegistered(ChannelHandlerContext ctx) {
      // here onFlush event I start to read from the channel, and if there is buffered data, channelRead will write and flush additional data
      outboundChannel.writeAndFlush(some initial data).addListener(f -> ctx.read());
   }

  public void channelRead(ChannelHandlerContext ctx, Object msg) {
       outboundChannel.writeAndFlush(msg).addListener(f -> {
            if (canWrite) {
                ctx.read();
            }
       }
  }  
}
```

### Netty version
4.1.42

### JVM version (e.g. `java -version`)
OpenJDK 12

### OS version (e.g. `uname -a`)
Linux  5.4.8-arch1-1 #1 SMP PREEMPT Sat, 04 Jan 2020 23:46:18 +0000 x86_64 GNU/Linux

**Comment by carryxyh** [comment]
I'd like try to fix this.
https://github.com/netty/netty/pull/9931

**Comment by Delorien84** [comment]
Thanks for quick fix.
