### ISSUE TITLE
Problem with Connect timeout and Graal generated native-image

### ISSUE THREAD

**Issue by petermd** [netty/netty#9928]
I've been researching an issue  ([micronaut-core#2335](https://github.com/micronaut-projects/micronaut-core/issues/2335)) with running micronaut apps as graal native-image on AWS Lambda, and think there might be a problem with the current settings.

### Expected behavior
Netty Connect Timeout works in a Graal Native Image 

### Actual behavior
Generated NativeImage does not work on some ephemeral environments like AWS Lambda, instead any connections timeout immediately as if the timeout was set to 0.

### Steps to reproduce
Full discussion of the issue (including reproducer) [micronaut-core#2335](https://github.com/micronaut-projects/micronaut-core/issues/2335), repeating my findings here

On investigating I've noticed that the Netty class `io.netty.util.concurrent.ScheduledFutureTask` contains a memoized static value from `System.nanoTime()` that all task timers are normalized to (see [ScheduledFutureTask.java#L28](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/concurrent/ScheduledFutureTask.java#L28)).

Because Netty is [defaulting to `initialize-at-build-time`](https://github.com/netty/netty/blob/4.1/codec-http/src/main/resources/META-INF/native-image/io.netty/codec-http/native-image.properties#L15), this value is computed when the native image is created, but `System.nanoTime()` can return an arbitrary value, not one that is consistent across environments. If the value memoized in `native-image` is higher than the one returned by `System.nanoTime()` at runtime then the computed deltas go negative and get clamped to 0 causing the immediate timeout.

This isn't a problem if the build & runtime are the same machine, but if you run the generated image on an ephemeral environment then the issue is much more likely to occur.

I have successfully applied a workaround to change `io.netty.util.concurrent.ScheduledFutureTask` to `initialize-at-run-time` but it seems like this is a general issue and the Netty vended `native-image.properties` could be updated?

Happy to submit a PR for same if that is the right path forward.

### Netty version
4.1.43.Final

### JVM version (e.g. `java -version`)
* openjdk version "1.8.0_191"
* graal 19.2.0.1, 19.2.1

### OS version (e.g. `uname -a`)
AmazonLinux 2018.03

**Comment by normanmaurer** [comment]
@petermd yes this like an issue... can you submit a pr ?

**Comment by petermd** [comment]
Fixed by https://github.com/netty/netty/pull/9963
