### ISSUE TITLE
 Security Vulnerability - Common Weakness Enumeration (CWE) CWE-295

### ISSUE THREAD

**Issue by vibin22** [netty/netty#9930]
###  is there a fix for 
Common Weakness Enumeration (CWE)
CWE-295 - Improper Certificate Validation
The software does not validate, or incorrectly validates, a certificate.

**Comment by vibin22** [comment]
![bd-vulns](https://user-images.githubusercontent.com/3473841/71996815-dacab180-320a-11ea-950f-9636fe34e66a.png)

**Comment by johnou** [comment]
Are you passing the host and port into https://netty.io/4.0/api/io/netty/handler/ssl/SslContext.html#newEngine-io.netty.buffer.ByteBufAllocator-java.lang.String-int- ?

**Comment by slandelle** [comment]
This refers to https://github.com/netty/netty/issues/8537.

In Java, hostname verification is not enabled by default, you have to set the protocol to "HTTPS" in the SSLParameters of the SSLEngine, see https://github.com/netty/netty/issues/8537 and https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLParameters.html#setEndpointIdentificationAlgorithm-java.lang.String-

**Comment by slandelle** [comment]
You indeed need to see the hostname and port when creating the SSLEngine but that alone doesn’t suffice, it only enables SNI. You also need to configure the algorithm.

**Comment by normanmaurer** [comment]
@vibin22 like @slandelle said. I would argue this is not an issue with netty but with the configuration that the user applies.

**Comment by johnou** [comment]
cc @stevebillings

**Comment by johnou** [comment]
cc @gkillough

**Comment by slandelle** [comment]
Side node : SSLParameters#setEndpointIdentificationAlgorithm doesn't exist on Android... When Google implemented Java 7, they choose to not add this method and instead automatically enable HTTPS algorithm. So if Netty was to enable HTTPS algorithm by default in a future release, it would have to test PlatformDependent.isAndroid.

**Comment by vibin22** [comment]
> @vibin22 like @slandelle said. I would argue this is not an issue with netty but with the configuration that the user applies.

Thanks for the response.
