### ISSUE TITLE
Man-in-the-Middle vulnerability

### ISSUE THREAD

**Issue by sureshkrishnamoorthy** [netty/netty#9938]
###  Man-in-the-Middle vulnerability
Software vulnerability checker(Veracode) reports that netty-handler is vulnerable to Man-in-the-Middle attack. Issue description is provided below. Please let us know how to address this.

"_netty-handler is vulnerable to man-in-the-middle attacks. The library uses an SSLEngine that does not verify certificate hostnames when establishing connections with clients by default. This allows an attacker to potentially intercept and modify network traffic in a successful man-in-the-middle attack._"

**Comment by hyperxpro** [comment]
Duplicate of https://github.com/netty/netty/issues/9930
