### ISSUE TITLE
Merge WebSocketCloseFrameHandler into WebSocketProtocolHandler in order to minimize pipeline

### ISSUE THREAD

**Issue by doom369** [netty/netty#9944]
`WebSocketCloseFrameHandler` could be easily merged into `WebSocketProtocolHandler` and thus we don't need to add/hold an additional handler in the websockets pipeline. I think it would nice improvement for websockets pipeline.

@normanmaurer @ursaj @amizurov WDYT?

**Comment by normanmaurer** [comment]
Sounds Good
