### ISSUE TITLE
io.netty.channel.abstractchannel$annotatedconnectexception connection timed out no further informa

### ISSUE THREAD

**Issue by Unrestriction** [netty/netty#9946]
### Expected behavior
My friends and I can connect to my server
### Actual behavior
The only way to connect is by typing my ipv4:25565 which means my friends cant join
### Steps to reproduce
Launch the server and try to connect
### Minimal yet complete reproducer code (or URL to code)
No code
### Netty version
I don't know, I'm a noob.
### JVM version (e.g. `java -version`)
1.8.0_231
### OS version (e.g. `uname -a`)
Windows 10???

**Comment by Unrestriction** [comment]
I did the port forwarding and the port is open

**Comment by SplotyCode** [comment]
I assume you are running a minecraft server because of port 25565. I gues it would be better to go to minecraft forums and ask. You can connect to the server with localhost and your public ip address?

**Comment by normanmaurer** [comment]
as @SplotyCode said... Closing
