### ISSUE TITLE
Suspicious NioSocketChannel leak

### ISSUE THREAD

**Issue by hbprotoss** [netty/netty#9951]
### Expected behavior
Memory release correctly

### Actual behavior
We have 3.5G heap in dump, and one of the `NioSocketChannel` consumes 2.4G retained heap.

It seems `NioSocketChannel` refers to each other via `SelectionKeyImpl.attachment`

![image](https://user-images.githubusercontent.com/2310905/72333785-59d25500-36f7-11ea-8d75-7c2a1b4c8a69.png)

dominator tree, 461793 `EpollSelectorImpl` instances
![image](https://user-images.githubusercontent.com/2310905/72421423-6e782100-37bb-11ea-8353-d07f26a1b572.png)

### Steps to reproduce
Not sure

### Minimal yet complete reproducer code (or URL to code)
Not sure

### Netty version
4.1.12

### JVM version (e.g. `java -version`)
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

### OS version (e.g. `uname -a`)
Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
Please update to latest netty version and report back if there is still the problem. The version you are using is super old
