### ISSUE TITLE
Source Code junit test is error

### ISSUE THREAD

**Issue by wuhulala** [netty/netty#9954]
when i pull this code,build in intellij idea, some junit test is error
such as

![image](https://user-images.githubusercontent.com/10361981/72446125-e95a2f80-37ed-11ea-99f3-949ee298250b.png)

i use `Long.valueOf` can fixed this.

```
        assertEquals(Long.valueOf(3L), channel.readOutbound());
```

but it is so many

i need help

### Netty version
4.1.x
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
windows 10

**Comment by normanmaurer** [comment]
not sure what is up with IntelliJ here but it works here without problems and also compiles via the cmd line

**Comment by medusar** [comment]
Maybe you need `./mvnw install` before do anything else.

**Comment by zhousiliang163** [comment]
How did you solve the problem？
