### ISSUE TITLE
transfer socket(FD) between two java process

### ISSUE THREAD

**Issue by zhenjunMa** [netty/netty#9957]
### Expected behavior

now，i want to transfer existed sockets to a new process when the old process who accepted this socket must be killed.

i have known this can be done by call linux function like `sendmsg`.
more info please see: https://stackoverflow.com/questions/1997622/can-i-open-a-socket-and-pass-it-to-another-process-in-linux

i found related method in `io.netty.channel.unix.Socket`, which encapsulate JNI method.

`private static native int recvFd(int fd);`
`private static native int sendFd(int socketFd, int fd);`

i think these method can achieve my goals, and i want to ask two questions:
1. when the new process received the socket, can netty help me manage the read/write event produced by this socket later?
2. where can i find more documents about this? demo is best, i think only few people should care these method.

### Netty version
4.1.x
### JVM version (e.g. `java -version`)
1.8 ~ 1.14  any
### OS version (e.g. `uname -a`)
centOS

**Comment by normanmaurer** [comment]
@zhenjunMa yes this is possible... We have a unit test for this which should give you some ideas:

https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/test/java/io/netty/channel/epoll/EpollDomainSocketFdTest.java#L38
