### ISSUE TITLE
Why WeakOrderQueue extends WeakReference<Thread>?

### ISSUE THREAD

**Issue by rushsky518** [netty/netty#9962]
Why does WeakOrderQueue class extend WeakReference[Thread], but doesn't implement a run method.
````java
private static final class WeakOrderQueue extends WeakReference<Thread>
````

**Comment by normanmaurer** [comment]
@rushsky518 because we want to be able to collect the `Thread` that is hold by it if `WeakOrderQueue` is the only reference to it.
