### ISSUE TITLE
AbstractChannel.java :AbstractUnsafe: inFlush0 should be volatile

### ISSUE THREAD

**Issue by wuwenbin555** [netty/netty#9975]
**private boolean inFlush0**   in    **AbstractChannel.java**   class    **AbstractUnsafe**
the inFlush0 in  private void close(...)  and   **protected void flush0()**, Two method maybe in two threads, but two method depend the variable inFlush0，So i think it should be declare：

**private volatile boolean inFlush0**；

**Comment by normanmaurer** [comment]
@wuwenbin555 nope... all methods in `AbstractUnsafe` are only called from within the `EventLoop` and so will be single threaded
