### ISSUE TITLE
DEFAULT_CACHE_TRIM_INTERVAL_MILLIS debug log is incorrect

### ISSUE THREAD

**Issue by LinShunKang** [netty/netty#9981]
### Expected behavior
Print debug log `-Dio.netty.allocation.cacheTrimIntervalMillis: {}`

### Actual behavior
Print debug log `-Dio.netty.allocator.cacheTrimIntervalMillis: {}`. 

In `PooledByteBufAllocator.java` use `io.netty.allocation.cacheTrimIntervalMillis` to get system property value for `DEFAULT_CACHE_TRIM_INTERVAL_MILLIS` rather than `io.netty.allocator.cacheTrimIntervalMillis`, this can be misleading.

### Netty version
4.1.44

### JVM version (e.g. `java -version`)
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

### OS version (e.g. `uname -a`)
Linux 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@LinShunKang sorry but I dont get the problem... Can you explain it more or just open a PR to fix it ?

**Comment by LinShunKang** [comment]
@normanmaurer Compare these two lines of code:  
https://github.com/netty/netty/blob/922e4635240e1519d22edc0cb1ff9d2382464886/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java#L128

https://github.com/netty/netty/blob/922e4635240e1519d22edc0cb1ff9d2382464886/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java#L160

**Comment by normanmaurer** [comment]
@LinShunKang ah I see... let me fix this

**Comment by normanmaurer** [comment]
@LinShunKang FYI https://github.com/netty/netty/pull/9994
