### ISSUE TITLE
increase MQTT decoder maximum size

### ISSUE THREAD

**Issue by BigGitWorld** [netty/netty#9983]
I'd like to send a mqtt message so that its length is larger than ``DEFAULT_MAX_BYTES_IN_MESSAGE = 8092``.
Now I get the below error:
```
Caused by: io.netty.handler.codec.DecoderException: too large message: 8144 bytes
```
what is best way to handle it?
1. Should I break my mqtt message and send it several times with lower size?
2. Should I increase allowable maximum size of the mqtt decoder?

**Comment by kachayev** [comment]
@BigGitWorld `MqttDecoder` has public constructor that accepts `maxBytesInMessage` as an argument: https://github.com/netty/netty/blob/a9863f8128189098263ebfe42359d8c6d53f4b4e/codec-mqtt/src/main/java/io/netty/handler/codec/mqtt/MqttDecoder.java#L66-L69

**Comment by BigGitWorld** [comment]
@kachayev Thank you man for the response. I know that constructor exist.
I mean is it good to use an **infinite** value for this parameter?In fact I want to remove this constraint to avoid getting the above exception.
Because it's possible that my mqtt subscriber wants to subscribe to a lot topics.
Attachment:
If you are familiar with **Paho mqtt library**, there is a ``subscribe(String[] topics, ...)`` method, so that you can subscribe to several topics by this method. Therefore I encountered with the above exception if I use this subscribe method with a large size ``String[] topics``.
What is the best solution in my netty-based server side for this scenario?

**Comment by kachayev** [comment]
@BigGitWorld In practice, you can't process infinitely large message as far as your RAM is limited. MQTT protocol defines max size for topic string (16kb, [here](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718016)) and for message payload (256mb, [here](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718023)).
