### ISSUE TITLE
DefaultHttp2ConnectionDecoder triggers stream channel closes more eagerly than it should

### ISSUE THREAD

**Issue by bryce-anderson** [netty/netty#9986]
### Expected behavior
When a Http2FrameCodec receives a GOAWAY the stream channels with ID's greater than the last seen will get notified of the GOAWAY so they can bubble up a retryable signal.

### Actual behavior
The connection is notified first which eagerly closes the streams. This happens [here](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L215).

A work around is to add a listener to the `Http2Connection` that eagerly sends another copy of the `Http2GoAwayFrame` down the pipeline. This works because [connection listeners get called](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2Connection.java#L234) before the extra streams are culled, but that is also painful because the `DefaultHttp2GoAwayFrame` [constructor](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2GoAwayFrame.java#L80) that allows your to set the `lastStreamId` is package private.

### Netty version
4.1.43.Final but also appears to affect 4.1

**Comment by normanmaurer** [comment]
@bryce-anderson will you look into a proper fix ?

**Comment by bryce-anderson** [comment]
@normanmaurer, yes. I suspect it will be either really easy or really hard.

**Comment by normanmaurer** [comment]
@bryce-anderson ok cool... let me know once you have something to review.

**Comment by bryce-anderson** [comment]
@normanmaurer https://github.com/netty/netty/pull/10002
