### ISSUE TITLE
Document for Mqtt codec

### ISSUE THREAD

**Issue by BigGitWorld** [netty/netty#9992]
Is there any document about MQTT codec?

**Comment by amizurov** [comment]
I'm not sure about specific for Netty MQTT docs, but you can look to example  [MQTT](https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/mqtt/heartBeat)

**Comment by normanmaurer** [comment]
@BigGitWorld only the javadocs and the examples as mentioned
