### ISSUE TITLE
SmtpCommand lacks AUTH

### ISSUE THREAD

**Issue by yuanrw** [netty/netty#9995]
### Expected behavior
I'm writing a smtp client based on netty. SmtpCommand lacks the AUTH command. It is used to login to an SMTP server.

See it in https://www.ietf.org/rfc/rfc4954.txt

Is it possible to add it ?
### Actual behavior
Can not create an AUTH command.

### Netty version
4.1.45.Final

### JVM version (e.g. `java -version`)
11.0.1
### OS version (e.g. `uname -a`)
Darwin Mac.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
We love love contributions so feel free to submit a PR if you have time. Otherwise it may take a bit before I will have a chance to do it

**Comment by yuanrw** [comment]
@normanmaurer  ok. I will do it :-)

**Comment by yuanrw** [comment]
After send AUTH, the client need to send encoded username and password without any command, but SmtpCommand is a required field for SmtpRequest. So I think it's necessary to add an EMPTY command which means a request with only parameters. WDYT? @normanmaurer
